### PR TITLE
DEL - Sort file names in reverse order

### PR DESCRIPTION
**Pull request by vovodroid**
Implementation of #24937

Currently files could be sorted by name, with option recent FAT entry first. So it could be difficult find new file.

Some slicers (at least Prusa) allows add date/time at the file name beginning like 202221028-174608. Reverse sort puts new file at the list top.

### CODE REVIEW

**Comment by thinkyhead** [comment]
If the first 9 or 10 characters of a filename are near identical and this is how they are chosen to be kept on the SD card, this is going to make it hard to identify the file you want. And, when someone comes along with a different SD card the behavior is going to be strange to them. I don't think this has a broad appeal, but I'll have some other devs review it and we'll see what the consensus is.

**Comment by vovodroid** [comment]
> first 9 or 10 characters of a filename are near identical

It not must to be such long. For practical usage prefix MMDD-hhmm like 1204-0831 is good enough, so only first 4 or 5 are identical during the same day. Nevertheless latest file will be always the first one.


> when someone comes along with a different SD card

Never give to strangers access to you printer!!! )))

**Comment by thinkyhead** [comment]
> Never give to strangers access to you printer!!! )))

Always re-flash your printer to something with standard behavior before selling!!! )))

**Comment by vovodroid** [comment]
Merged

**Pull request closed without merging**
