### PR TITLE
Bugfix 2.0.x add BIGTREE SKR V1.3 motherboard pins define

### PR DESCRIPTION
**Pull request by Msq001**
- Add SKR v1.3 pins define
- Fix SKR v1.1 `SS_PIN` of SD card CS pin

It can print file from TF card on board, not SD card on LCD.

### CODE REVIEW

**Comment by gloomyandy** [comment]
@Msq001 Have you actually tested that SS_PIN change? I do not believe it is correct. That pin is used when talking to the onboard SD card, but you have specified the use of the chip select pin for the LCD based SD card reader.

**Comment by gloomyandy** [comment]
Just to be clear. There are two different SD card configurations provided here for Marlin. One of them provides Marlin access to the SD card reader on an attached LCD display. This needs to use the following pins:
```C
  #define SCK_PIN          P0_15
  #define MISO_PIN         P0_17
  #define MOSI_PIN         P0_18
  #define SS_PIN           P1_23   // Chip select for SD card used by Marlin
 ```
The other configuration is for when Marlin uses the onboard SD card reader. This needs to use the following pins:
```C
  #define SCK_PIN          P0_07
  #define MISO_PIN         P0_08
  #define MOSI_PIN         P0_09
  #define SS_PIN           P0_06   // Chip select for SD card used by Marlin
```
The change made in the PR has modified the second configuration to use the chip select pin used by the first configuration. That makes no sense at all and I do not believe it will work as intended. It will certainly not provide access to the onboard SD card reader.

**Comment by gloomyandy** [comment]
I can confirm that the change to the SS_PIN definition in this PR has broken access to the onboard SD card from Marlin. Reverting the change fixes the problem. @Msq001 can you explain why this change was made, what is it you are trying to fix/achieve?

@thinkyhead what is the best way to handle this? Do I need to create an issue for it? A new PR that reverts the code?

**Comment by Msq001** [comment]
@gloomyandy  Sorry for that, this change of SS_PIN is really wrong, It needs to be restored.  My pins define of sd card can work normal because of I have 
`#define SDSS               P0_06`  
in my "skr_pins.h" file,  so the sd init  will use P0_06 directly instead of SS_PIN

Let me explain why I want to change.
There are two define in the "skr_pins.h" file 
  ```
#define SS_PIN          P1_23   // Chip select for SD card used by Marlin
#define ONBOARD_SD_CS   P0_06   // Chip select for "System" SD card
```
I think 
when `#define LPC_SD_LCD`  ONBOARD_SD_CS should to be HIGH LEVEL to cancel SPI CS, and SS_PIN is used for SD card CS.
when `#define LPC_SD_ONBOARD`  SS_PIN should to be HIGH LEVEL to cancel SPI CS, and ONBOARD_SD_CS is used for SD card CS.
So they need to be defined as two different pins, But now I know this idea is wrong.
And now I wonder to know what is the purpose of `# define ONBOARD_SD_CS P 0_06 `

**Comment by gloomyandy** [comment]
SS_PIN is the chip select pin used when Marlin accesses the SD card for reading gcode etc. ONBOARD_SD_CS is the chip select pin used by the LP1768 framework when accessing the onboard SD card to share it with a PC over USB. So when things are defined for Marlin to use the onboard SD card both need to be set to P0_06 and the LCD SD card reader is not used. Both Marlin and the PC have access to the same card. 

When things are defined so that Marlin uses the LCD SD card reader then SD_PIN needs to be P1_23 but ONBOARD_SD_CS remains as P0_06 so that the PC can still access the onboard SD card for uploading firmware. 

The correct setting of these pins is controlled by the following defines...
```C
//
// SD Support
//
//#define USB_SD_DISABLED     // Disable host access to SD card as mass storage device through USB
#define USB_SD_ONBOARD        // Enable host access to SD card as mass storage device through USB

//#define LPC_SD_LCD          // Marlin uses the SD drive attached to the LCD
#define LPC_SD_ONBOARD        // Marlin uses the SD drive on the control board.  There is no SD detect pin
                              // for the onboard card.  Init card from LCD menu or send M21 whenever printer
                              // is powered on to enable SD access.

```


Oh and I would remove the setting of SDSS from yourSKR V1.3 pins file. It will be set to the correct value by the HAL layer (see spi_pins.h). It does not need to be defined here.

**Comment by Msq001** [comment]
thanks for your work ,  and I still have two question about this skr_pins.h
1. marlin access to sd card with `#define LCD_SDSS` and `#define SS_PIN`, so 
what's the purpose of `# define ONBOARD_SD_CS`. I tried to comment out it,  and seems that work normal too.
2.  Why don't you define the on board TF card detect pin? `#undef SD_DETECT_PIN `, skr motherboard has this pin,  and it's `#define SD_DETECT_PIN  P0_27`

**Comment by gloomyandy** [comment]
When running on LPC1768 based boards there are two file system stacks, one is the standard Marlin stack and is used by Marlin to read and write files to access gcode etc. This stack uses the SS_PIN to define the chip select pin when accessing the card. The other is implemented by a combination of the LPC1768 HAL and the LPC1768 framework and is used to allow access to the onboard SD card via USB from an attached PC. This stack uses the ONBOARD_SD_CS define to specify the pin to use for chip select when performing USB I/O to the onboard SD card. If you do not define ONBOARD_SD_CS then you will probably not be able to access the onboard SD card via USB (There is the possibility that it may still work as the actual pins used for USB access are hard coded in the LPC1768 framework as well as in the Marlin configuration). But really if you want USB access you should define this pin.

The on board SD detect pin is not defined because at the time I created this version of the pins file I did not know what (if any pin) was used by the SKR for SD detect. However it is of limited use. It will not be used by the framework USB code and when the onboard SD card is being shared by both USB access and Marlin we deliberately do not define an SD detect pin. This is so that Marlin will activate the menu SD card switching code which is needed to allow the user to control which of the stacks (Marlin or USB) has control of the SD card as it is not safe to have both access the card at the same time. So the only time that this pin would be of use is if you turn off USB access to the onboard SD card, but have things defined such that Marlin uses this card rather then one attached to an LCD display. Very few people set things up this way. Please do not just define this pin if you do not understand how this all works.

So at the moment with the changes you have made it is not possible to have both Marlin and a PC connected via USB share the SD card. This is a very useful combination as it allows a user to slice code on a PC and then just copy the file over using the USB access and then select that file from the LCD and print it. This is a work flow that many people seem to like and for that reason is the default setup for many LPC1768 based boards. At the moment that default configuration is broken on the SKR V1.1 board (and probably on the V1.3 board, but I can't test that). So we need to revert this change.

**Comment by Msq001** [comment]
I'm sorry again about this change.  And skr1.3/skr1.1 are no different about TF cards. We may need to create a new PR to change the skr1.1_pins.h and skr1.3_pins.h. Thank you very much for your reply!

**Comment by gloomyandy** [comment]
No problem, are you going to create the PR? I could do it for the 1.1 board but can't really for the 1.3 as I really like to check things before pushing them to Scott. Oh and do you know when/if the 1.3 board will be available from Amazon in the UK? I will probably pick one up as I suspect it will be very popular and I'd like to help folks that use it (I may even swap the SBase board in my main printer for it at some point as it looks like it will do everything I need in a smaller form factor).

**Comment by Msq001** [comment]
I have created the PR, #13272 .  and 1.3 wil be available at March 1st  Friday 10:00 am EST. Thank you again for your help.

**Comment by gloomyandy** [comment]
Hi thanks for doing that. Do you happen to know if the 1.3 board will be available from a UK supplier?

**Comment by Msq001** [comment]
Sorry. I don't know about it.  Maybe you can go to Bigtree's Facebook team to ask it

**Comment by ReneHezser** [comment]
Thank you for supporting the SKR V1.3. If I enable **FILAMENT_RUNOUT_SENSOR** a pin needs to be defined. According to the [video](https://youtu.be/oaXfXkPYHpw?t=613) this need to be

    #ifndef FIL_RUNOUT_PIN
      #define FIL_RUNOUT_PIN P1_28
    #endif

**Comment by Msq001** [comment]
Yes. it need to be added

**Pull request merged**
