### PR TITLE
test1

### PR DESCRIPTION
**Pull request by classicrocker883**

### CODE REVIEW

**Comment by thisiskeithb** [comment]
@classicrocker883 Please run tests in your own fork.

**Comment by classicrocker883** [comment]
@thisiskeithb thats what im doing.... this was a mistake thats why I closed it

**Comment by classicrocker883** [comment]
jeeze dude really? did you not notice? did you *have* to say anything at all? youre making me seem like an asshole by telling me what to do

**Comment by classicrocker883** [comment]
https://github.com/classicrocker883/Marlin/pull/1 

see, when I did a pull request it automatically went here, thats what happened

**Comment by thisiskeithb** [comment]
> see, when I did a pull request it automatically went here, thats what happened

That's not how GitHub works, but feel free to hop on our [Discord](https://discord.gg/n5NJ59y) if you'd like to discuss this further.

**Comment by classicrocker883** [comment]
open a pull request on your end, and you will see it goes right upstream. dont act like i did it on purpose when I closed it when I saw it right away.

**Pull request closed without merging**
