### PR TITLE
Fix G30/Single Z-Probe for JyersUI

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Fix G30/Single Z-Probe for JyersUI

### Requirements

JyersUI

### Configurations

Use [MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3 V2/CrealityV422/CrealityUI](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3%20V2/CrealityV422/CrealityUI), disable `DWIN_CREALITY_LCD` and enable:
- `DWIN_CREALITY_LCD_JYERSUI`
- `BLTOUCH`
- `Z_SAFE_HOMING`

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/24539

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Don't merge yet. I'm waiting on @TruncatedPi to respond: https://github.com/MarlinFirmware/Marlin/issues/24539#issuecomment-1193225146

**Review by TruncatedPi — APPROVED** [review]

**Review by TruncatedPi — APPROVED** [review]

**Comment by thisiskeithb** [comment]
@TruncatedPi Please attach a config that causes this error.

Edit: Closing so this doesn't get merged prematurely.

**Comment by TruncatedPi** [comment]
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9175198/Configuration.zip)

#define DWIN_CREALITY_LCD_JYERSUI

**Comment by thisiskeithb** [comment]
> [Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9175198/Configuration.zip)
> #define DWIN_CREALITY_LCD_JYERSUI

@TruncatedPi Your config does not build due to invalid settings:

- `#error "LIN_ADVANCE and S_CURVE_ACCELERATION may not play well together! Enable EXPERIMENTAL_SCURVE to continue."`
- `#error "USE_CONTROLLER_FAN requires a CONTROLLER_FAN_PIN. Define in Configuration_adv.h."`
- `#error "LED_CONTROL_MENU requires BLINKM, RGB_LED, RGBW_LED, PCA9533, PCA9632, or NEOPIXEL_LED."`
- `#error "LED_CONTROL_MENU requires an LCD controller that implements the menu."`
- `#error "Z_STEPPER_AUTO_ALIGN requires more than one Z stepper."`

---

Having said that, I took the configs from [MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3 V2/CrealityV422/CrealityUI](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/Creality/Ender-3%20V2/CrealityV422/CrealityUI), disabled `DWIN_CREALITY_LCD` and enabled `DWIN_CREALITY_LCD_JYERSUI`, `BLTOUCH`, and `Z_SAFE_HOMING` and was able to reproduce the error you reported in https://github.com/MarlinFirmware/Marlin/issues/24539, so this PR is needed.

**Pull request merged**
