### PR TITLE
Add MIN_PROBE_EDGE comments

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

Make MIN_PROBE_EDGE clearer, as to many are getting it wrong.

### Description

Add some comments to Configuration_adv.h in regards how to use 
MIN_PROBE_EDGE values correctly.

### Benefits

Less support requests due to users presuming these values are all 0,0 relative.

### Related Issues
None

### CODE REVIEW

**Comment by thinkyhead** [comment]
What do people think it means, if not the distance to the edge? I can't think of any sensible alternative interpretation.

**Comment by ellensp** [comment]
They seem to presume all measurements are from x0, y0, so have very large MIN_PROBE_EDGE_RIGHT and MIN_PROBE_EDGE_BACK. I don't understand why either... but they keep doing this.  The comments spell it out for them.

**Comment by ellensp** [comment]
Perhaps a Conditionals checks that these values are not > half of the bedsize would help?

**Comment by sjasonsmith** [comment]
I believe the problem is that people find these settings by searching for their old `PROBE_BED_POSITION` constants, and assume they should be set the same. Yes, they could read the details, but the explanation is pretty long and confusing.

Maybe the way to stop the misuse is to just remove the mention of the old variables, so that people don't find these so easily. Your average user should never need these.

**Comment by thinkyhead** [comment]
Clearer sanity checks:
```cpp
#elif defined(LEFT_PROBE_BED_POSITION)
  #error "LEFT_PROBE_BED_POSITION is obsolete. Set a margin with MIN_PROBE_EDGE or MIN_PROBE_EDGE_LEFT instead."
#elif defined(RIGHT_PROBE_BED_POSITION)
  #error "RIGHT_PROBE_BED_POSITION is obsolete. Set a margin with MIN_PROBE_EDGE or MIN_PROBE_EDGE_RIGHT instead."
#elif defined(FRONT_PROBE_BED_POSITION)
  #error "FRONT_PROBE_BED_POSITION is obsolete. Set a margin with MIN_PROBE_EDGE or MIN_PROBE_EDGE_FRONT instead."
#elif defined(BACK_PROBE_BED_POSITION)
  #error "BACK_PROBE_BED_POSITION is obsolete. Set a margin with MIN_PROBE_EDGE or MIN_PROBE_EDGE_BACK instead."
```

**Pull request merged**
