### PR TITLE
✨ [WIP] Expanded M73 functionality and all-granular progress display options

### PR DESCRIPTION
**Pull request by EvilGremlin**
Prusa-like M73 that report values back. This will allow hosts to get M73 progress from SD printing.
Final objective is to untangle M73 from any display requirements, i will do this in next commit hopefully.

### CODE REVIEW

**Comment by EvilGremlin** [comment]
[@arkem](https://github.com/arekm) (octo plugin maintainer)

**Comment by GMagician** [comment]
I still get progress from sd print, at least in %. Repetier is using bytes processed/total bytes message sent by Marlin

**Comment by EvilGremlin** [comment]
This is M27 and it's never right, slicer estimate is best you can get when printing from SD.

**Comment by EvilGremlin** [comment]
@thinkyhead I left it in test-failing state intentionally for now

**Comment by arekm** [comment]
Plugin only needs regex update now (with all things in m73 serial output being optional):
https://github.com/arekm/octopi_eta_override/blob/devel/octoprint_PrusaETAOverride/__init__.py

**Comment by arekm** [comment]
And added - https://github.com/arekm/octopi_eta_override/tree/marlin2

**Comment by EvilGremlin** [comment]
https://github.com/MarlinFirmware/Marlin/runs/8236421157?check_suite_focus=true#step:7:42
~~seriously, WTF? why it's blind?~~ test grabs example config and still set all the options on top, this is stupid, gotta fix that

**Comment by EvilGremlin** [comment]
BTW status_screen_lite_ST7920 is full of unidentified reference... literally every function

**Comment by arekm** [comment]
Closed?

**Comment by EvilGremlin** [comment]
I opened PR like this in hope for some comments, will roll out later all finished and squashed.

**Comment by arekm** [comment]
Ok (was looking at your changes waiting for first testable version).

**Comment by EvilGremlin** [comment]
it's testable now, i didn't push failing code

**Comment by arekm** [comment]
Using your tree, bf2.1-prusaM73echo branch

```
Building in release mode
Compiling .pio/build/mega2560/src/src/inc/Warnings.cpp.o
Linking .pio/build/mega2560/firmware.elf
/var/folders/_c/p6pcdx7x65q8vd1j31szm7k40000gn/T//ccKkIC1e.ltrans0.ltrans.o: In function `MarlinUI::status_screen()':
<artificial>:(.text+0x3980): undefined reference to `MarlinUI::string_ptr'
<artificial>:(.text+0x3982): undefined reference to `MarlinUI::string_ptr'
collect2: error: ld returned 1 exit status
*** [.pio/build/mega2560/firmware.elf] Error 1
```

HAS_PRINT_PROGRESS is defined, all SHOW_*_TIME defined, too. I don't see why it fails linking.

**Comment by EvilGremlin** [comment]
i see it now too, just on ESP32
LPC1768 compiled fine, i have no idea why this happening yet

**Comment by arekm** [comment]
Tried (based on https://stackoverflow.com/questions/16284629/undefined-reference-to-static-variable-c ):

```
     static bool prev_blink;
     static uint8_t i;
+    void (*string_ptr[STRINGS])();
     if (prev_blink != get_blink()) {
       prev_blink = get_blink();
       if (++i >= STRINGS) i = 0;
       (*string_ptr[i])();
```

which makes linking succeed but doesn't work - it crashes in rotate_progress() and firmware restarts, boots, tries to print on lcd, crashes again and so on - a loop. So I commented out entire rotate_progress.

```
Send: M73
Recv: echo:  M73 Percent done: 10; Print time remaining in mins: 10; Change in mins: 20;
```

M73 R, C, P seem to be working (via serial).

The only thing is not initialized vs initialized (time for example). Like no "M73 C.." at all vs "M73 C0". No way to notice the
difference. (prusa uses -1 initially).

**Comment by EvilGremlin** [comment]
constexpr was a failure point  - i pushed fix

**Comment by EvilGremlin** [comment]
@arekm i added PRINT_PROGRESS_SHOW_DECIMALS to M73 report (for uniformity), you might need to tweak parsing a bit
Overall, i'm done with everything i wanted to do, will squash and throw new PR tomorrow

**Comment by arekm** [comment]
Great news!

I'll test when it becomes available.

(git push --force-with-lease of squashed commit would work on this pull req/branch, too)

**Comment by EvilGremlin** [comment]
you can compile my branch as is, just insert required options to your conf

**Comment by arekm** [comment]
Ok. Github mislead me (usually it added some message here, to pull req page, when new pushes were made but it seems that it doesn't do that when pull request is closed).

**Comment by arekm** [comment]
Why it adds .0 only sometimes?

Edit: Ok, it's mentioned in #24767:

"permyriadtostr4 need further touchups: whole single digit values don't show decimal, doesn't look nice."

```
2022-09-17 18:14:59,340 - Recv: echo:  M73 Percent done:   1; Print time remaining in mins: 19; Change in mins: 0;
2022-09-17 18:14:59,343 - Recv: echo:  M73 Percent done:   1; Print time remaining in mins: 19; Change in mins: 0;
2022-09-17 18:15:14,164 - Recv: echo:  M73 Percent done:   2; Print time remaining in mins: 19; Change in mins: 0;
2022-09-17 18:15:14,166 - Recv: echo:  M73 Percent done:   2; Print time remaining in mins: 19; Change in mins: 0;
2022-09-17 18:15:24,440 - Recv: echo:  M73 Percent done:   3; Print time remaining in mins: 19; Change in mins: 0;
2022-09-17 18:15:24,443 - Recv: echo:  M73 Percent done:   3; Print time remaining in mins: 19; Change in mins: 0;
2022-09-17 18:15:26,372 - Recv: echo:  M73 Percent done:   3; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:15:36,313 - Recv: echo:  M73 Percent done:   4; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:15:36,317 - Recv: echo:  M73 Percent done:   4; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:15:53,762 - Recv: echo:  M73 Percent done:   5; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:15:53,765 - Recv: echo:  M73 Percent done:   5; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:16:05,398 - Recv: echo:  M73 Percent done:   6; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:16:05,401 - Recv: echo:  M73 Percent done:   6; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:16:12,696 - Recv: echo:  M73 Percent done:   7; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:16:12,774 - Recv: echo:  M73 Percent done:   7; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:16:24,202 - Recv: echo:  M73 Percent done:   8; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:16:24,206 - Recv: echo:  M73 Percent done:   8; Print time remaining in mins: 18; Change in mins: 0;
2022-09-17 18:16:29,169 - Recv: echo:  M73 Percent done:   8; Print time remaining in mins: 17; Change in mins: 0;
2022-09-17 18:16:36,343 - Recv: echo:  M73 Percent done:   9; Print time remaining in mins: 17; Change in mins: 0;
2022-09-17 18:16:36,344 - Recv: echo:  M73 Percent done:   9; Print time remaining in mins: 17; Change in mins: 0;
2022-09-17 18:16:38,226 - Recv: echo:  M73 Percent done:   9; Print time remaining in mins: 17; Change in mins: 0;
2022-09-17 18:16:48,564 - Recv: echo:  M73 Percent done: 10.0; Print time remaining in mins: 17; Change in mins: 0;
2022-09-17 18:16:48,568 - Recv: echo:  M73 Percent done: 10.0; Print time remaining in mins: 17; Change in mins: 0;
2022-09-17 18:16:59,743 - Recv: echo:  M73 Percent done: 11.0; Print time remaining in mins: 17; Change in mins: 0;
[...]
2022-09-17 18:33:49,882 - Recv: echo:  M73 Percent done: 94.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:33:51,100 - Recv: echo:  M73 Percent done: 95.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:34:04,559 - Recv: echo:  M73 Percent done: 96.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:34:04,563 - Recv: echo:  M73 Percent done: 96.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:34:17,260 - Recv: echo:  M73 Percent done: 97.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:34:17,263 - Recv: echo:  M73 Percent done: 97.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:34:31,496 - Recv: echo:  M73 Percent done: 97.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:34:32,113 - Recv: echo:  M73 Percent done: 98.0; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:35:00,537 - Recv: echo:  M73 Percent done:  100; Print time remaining in mins: 0; Change in mins: 0;
2022-09-17 18:35:00,538 - Recv: echo:  M73 Percent done:  100; Print time remaining in mins: 0; Change in mins: 0;
```

**Comment by EvilGremlin** [comment]
i addressed thisin PR: permyriadtostr4 need further touchups: whole single digit values don't show decimal

**Comment by thisiskeithb** [comment]
Since this PR is superseded by https://github.com/MarlinFirmware/Marlin/pull/24767, comments should go there 🙂

**Pull request closed without merging**
