### PR TITLE
Update Azteeg X5 Mini Wifi pins, add CreatBot DX

### PR DESCRIPTION
**Pull request by ModMike**
### Requirements

Azteeg X5 Mini Wifi
Marlin 2.0.x Bugfix

CreatBot DX

### Description

Fixed servos pin and added support for new CMSIS framework

Added Creatbot DX

1) Creatbot DX config.h
2) Creatbot Dx config_adv.h
3) pins_creatbot.h
4) Pins.h
5) boards.h config

### Benefits

Azteeg:

- Enables Marlin to access the onboard SD card for printing.
- Allows SD card access via WEB UI host or USB host. 

Creatbot:

Adds Creatbot DX support to Marlin 2.0.x

### Related Issues

Azteeg:

Addresses issue #11639

CreatBot:

Need library integrations for LCD and USB drive support so currently not supported.  Meant to be used with Octoprint.

### CODE REVIEW

**Comment by thinkyhead** [comment]
The title of this PR leaves a lot to be desired.

**Comment by thinkyhead** [comment]
You seem to have started from some older version of Marlin, as this is reverting a lot of recent updates.

**Comment by ModMike** [comment]
Yes I did but then I reforked latest and simply added files.  Would it just be better to upload them to my fork and do a pull from there?

Not sure how to proceed.

**Comment by thinkyhead** [comment]
To bring your fork up to date you can use the git command line:
```
git fetch upstream
git checkout bugfix-2.0.x
git reset --hard upstream/bugfix-2.0.x
git push -f origin
```
Then you're good to go for making a new branch:
```
git checkout bugfix-2.0.x -b bf2_azteeg_creatbotdx
```

**Comment by ModMike** [comment]
@thinkyhead I am trying to locate a document I saw a few days ago that explains how to properly fork and branch marlin using GitHub desktop.  I have been searching for 1.5 hours and can't seem to find it.

Do you happen to know what document I am describing and where I can find it?

I could kick myself for not bookmarking it.

**Comment by thinkyhead** [comment]
You have to fork Marlin from the main MarlinFirmware/Marlin page, using the "fork" button. The new fork appears under your account. You can then use the "Open in Desktop" button to download it to your machine through GitHub Desktop. You can then use GitHub Desktop to create new branches, commit changes, publish them to your fork, and submit PRs to the main project.

**Comment by lcmschattenkerk** [comment]
Hi mike,
I have a creatbot dx2
Can you help me with the complete marlin files for creatbot dx2.

Thanks in advanced
Greetings laurens

**Comment by ModMike** [comment]
I have everything working except display and front USB slot.

I will send you the files later today.

**Pull request closed without merging**
