### PR TITLE
Ubl delta fixes and improvements

### PR DESCRIPTION
**Pull request by oldmcg**
UBL (all): change direct state.active assignment to set_bed_leveling_enabled() calls in order to maintain apply/unapply leveling adjustments to current_position.

UBL_DELTA: fix unapply_leveling calculation so apply/unapply round trip works with workspace z offset.

UBL (all): fix fade height changes to temporarily disable/re-enabled leveling to preserve current_position via unapply/apply leveling.

UBL_DELTA: change name of routine from ubl.prepare_linear_move_to to ubl.prepare_segmented_line_to as more accurate name.

UBL_DELTA: changed the segmented line routine to work in raw coordinate space throughout routine to avoid logical-to-raw calculations during inverse_kinematics for each segment, and inlined delta kinematics.

UBL (all): added ubl.set_all_mesh_points_to_value() and changed handful of places to call this routine instead of multiple embedded loops.

UBL (all): corrected G29 loops that intended to fill "all remaining" grid positions but would only fill reachable positions to also fill unreachable positions (primarily delta corners).

UBL (all): cleanup a few compiler warnings

ALL: add M114 D (detail) option for reporting current position, not compiled by default, needed to track down leveling system inconsistencies but can be generally useful.

### CODE REVIEW

**Comment by oldmcg** [comment]
@Roxy-3D, can you please look over this since quite a few changes affect UBL generally?  Thx.

**Comment by Roxy-3D** [comment]
Yes...  I will do that in the morning.   And I'll probably load it up on one of my printers too...   But I don't have a Delta that is running right now.  So I can only test the Cartesian stuff directly.

**Comment by oldmcg** [comment]
@Roxy-3D, after this PR, I THINK that turning on PLANNER_LEVELING for regular cartesian UBL in conditionals_post.h...

  `#define PLANNER_LEVELING      (ABL_PLANAR || ABL_GRID || ENABLED(MESH_BED_LEVELING) || ENABLED(AUTO_BED_LEVELING_UBL))`

...will allow all the non ubl.line_to_destination_cartesian() motions such as uninterpolated_move_to and arc to perform UBL leveling and remain consistent with apply/unapply leveling.  But I don't have a cartesian machine to verify on, just that it compiles properly.

**Comment by Roxy-3D** [comment]
@oldmcg    So, if I understand correctly....   I should:
- review changes.   (I'm almost ready to start that)
- load it up on my printer and insure the Cartesian side of the world is correct and behaves rationally.
- and then make that one line change in conditionals_post.h to turn on PLANNER_LEVELING and do some more testing,.

**Comment by oldmcg** [comment]
That is what I recommend, but before your turn on PLANNER_LEVELING, turn on #define M114_DETAIL and use M114D to view current location with respect to all the logical,raw,leveled,unleveled,stepper,and from-stepper layers while UBL is enabled and disabled, before and after some linear moves and some Z-only moves.  Disable fade height to keep it simple at first, I think you'll see that without PLANNER_LEVELING there are some discrepancies.  I think that G1 Z50 (then M114D) followed by G1 X50 (and M114D) will initially result in an unleveled Z50 and then first segment to X50 will hit leveling at first segment crossing.  Then another G1 Z49 will result in unleveled Z then another XY motion will start leveling again.  But once you turn on PLANNER_LEVELING it should all stay leveled.  At least that is what I expect from looking at the code, because Z-only moves go to planner.buffer_line not ubl.line_to_destination.  PLANNER_LEVELING will cause those buffer_line moves to be leveled.

**Comment by Roxy-3D** [comment]
OK.

I wonder if this should be bumped down to 1000 or maybe even 500 ?   5 seconds seems kind of long.  Some of the heaters  change temperature very fast now.  And the printer is just sitting there waiting any way?
```cpp
   bool unified_bed_leveling::turn_on_heaters() {
 -    millis_t next;
 +    millis_t next = millis() + 5000UL;
```
I can do that next time I make a change...

**Comment by oldmcg** [comment]
I didn't even look at what that routine was doing -- it was creating an unitialized compiler warning so I moved the initialization to the definition.

Looks like it just using the 5 seconds to print current heater status while otherwise spinning in idle()/clicked() loop waiting for target temp.  5 seconds between print_heaterstates() seems reasonable to me but more frequent wouldn't hurt anything, just fill up the console faster.

**Comment by Roxy-3D** [comment]
One more question:   For Delta's it is still not possible to use the G29 P4 interactive mesh point editor for points that are outside the PRINTABLE_RADIUS, right?   

Maybe...  for Cartesians we still do 
```cpp
    memset(not_done, 0xFF, sizeof(not_done));
```
but for Delta's we do a small loop to populate all mesh points within DELTA_PRINTABLE_RADIUS +/- 1   ????     
And then just a little bit of logic to clamp the nozzle movement so it can't leave the printable radius ????

**Comment by Roxy-3D** [comment]
> Looks like it just using the 5 seconds to print current heater status while otherwise spinning in idle()/clicked() loop waiting for target temp. 5 seconds between print_heaterstates() seems reasonable to me but more frequent wouldn't hurt anything, just fill up the console faster.

Oh!  OK!  That makes sense.   I didn't look at it close enough to realize that.   I haven't even looked at that code for 6 months so I forgot about that issue.

**Comment by oldmcg** [comment]
That's pretty much why I added G29 P3.1 earlier and in this PR changed G29 i999 and G29 P3 Cnnn R999 to actually invalidate or populate all of the unreachable points as well.

So far I've ignored G29 P4 since it is intended for after G26 mesh printed.  There is just no mechanism for setting probe-and-nozzle-unreachable points without either extrapolation (G29 P3.1 which should probably be default for delta G29 P3) or manually setting values with G29 P3 Cnnn, which is what I enabled with this PR.

For delta points just outside the radius, we COULD move the nozzle (or probe on probe side of bed) to the absolute edge of the printable radius nearest the invalid grid point and get a value (P1 or P2) and then load it in the WLSF routine to "better" extrapolate the unreachable point.  But this should only be done after the reachable section is done for better net tilt extrapolation.  So the flow would have to be something like...
    G29 P1 (auto probe all probe-reachable points)
    G29 P2 (manual probe all nozzle-reachable points that were not probe-reachable)
    G29 P1.5 (auto probe all nearly-reachable points and extrapolate them)
    G29 P2.5 (manual probe all nearly-nozzle-reachable points and extrapolate them)
    G29 P3.1 (auto fill the remaining invalid corner points with extrapolated values)

I suppose that P1 could just do the nearly-reachable points automatically after all the reachable points since there should be enough bed defined for WLSF extrapolation.  And likewise P2 could just do manual probing of nearly-reachable points after all the truly-reachable points, so we don't really need a P1.5 and P2.5 as distinct steps.

But for P4 since the G26 mesh doesn't leave a neat target hole for the nearly-reachable points, it would require further tweaking of G26 to place a semi-circle target where the just-inside-radius probe point would be.

I'll do some more thinking about this.

**Comment by Roxy-3D** [comment]
My perspective is it is helpful and nice to have a Z-Probe.  But without a Z-Probe, if you are willing to watch your printer and stop it if the nozzle is getting too close to the surface, you should be able to do:
- G29 P0
- G26    (and carefully monitor it so you don't damage the extruder)
- G29 P4    on any areas that need adjustment.
- go back to the G26 and repeat until the mesh is good!

If we come up with a simple and clever way to allow G29 P4 to edit the mesh points just outside the DELTA_PRINTABLE_RADIUS, even Delta's without a Z-Probe start working with UBL.

> But for P4 since the G26 mesh doesn't leave a neat target hole for the nearly-reachable points, it would require further tweaking of G26 to place a semi-circle target where the just-inside-radius probe point would be.

I'm not sure I like this idea.  But one way to communicate what is going on to the user would be to print a big circle right at the DELTA_PRINTABLE_RADIUS at the end of the pattern.   And then draw short tick marks on that circle that if extended out would point at the next mesh point outside of the radius.   And for that matter...  We could use the LCD Panel to alert users that the current point being edited is not within the DELTA_PRINTABLE_RADIUS.   Perhaps the nozzle could position on the tick mark and then maybe a cautionary, constant chirp sound along with different text on the LCD Screen?

**Comment by oldmcg** [comment]
Since the manual probe point is at the very edge of the printable radius, all you could print in G26 would be a semi-circle.  You could not even print right-angle ticks like it does now, so would probably have to look something like this:

image

I will continue to think about this.

**Comment by oldmcg** [comment]
Also, maybe for delta beds, G26 should connect the outer probe rings with direct lines instead of just squared lines.  I'll have to draw that and see what it would look like, but it would make the mesh easier to peel off in once piece.

**Comment by Roxy-3D** [comment]
Yeah...  I was thinking just a single small line segment.   Not even doing the complex drawing of an arc.   And it would be a small (3mm or 4mm) line segment.    It might make sense to do the tick mark at the closest place between the outside mesh point and the circle.  Or...  It might be more clear to just do it where the line from the center of the bed crosses the circle and do it in a direction pointing at the outside mesh point.

And as far as connecting up the circles that are just inside the DELTA_PRINTABLE_RADIUS...  Even if those locations were not on the radius, they would be close enough to the circle at DELTA_PRINTABLE_RADIUS that people would know what was going on when the nozzle moved to the edge (and was positioned over a tick mark on the circle).

The most confusing thing to handle would be a case at X=0 and the mesh point is exactly on the circle or just inside it.   In that case, how do you indicate you are editing the inside or the outside mesh point?   The nozzle is in the same location.  But given it edits closest points first, that helps.  And with some LCD Panel assistance, it should be possible to make it clear what is happening.

**Comment by Roxy-3D** [comment]
@oldmcg 

I'm having trouble getting a difficult print to finish.  But the problem aren't these latest changes.  I think I have a roll of bad filament.    It looks like the basic Cartesian stuff is OK.    

I have not had a chance to do the extended tests with the PLANNER_LEVELING.   

Is it helpful for me to do a 'Squash and Merge' ?

**Comment by oldmcg** [comment]
The PLANNER_LEVELING for regular cartesian UBL is NOT enabled by this PR -- it can be tested later.  I just set all the groundwork for it so one line change in conditionals_post.h will enable it whenever you're ready to test it.

Last time I tried to squash it didn't work, so I'd prefer you squash it whenever you feel comfortable with the change and ready to merge it.  Thx.

**Comment by Roxy-3D** [comment]
> Last time I tried to squash it didn't work, so I'd prefer you squash it whenever you feel comfortable with the change and ready to merge it. Thx.

 As long as everything in a Pull Request is for a single topic, we have a "Squash and Merge" option.  It happens automatically.   Please don't do the extra work to squash things.

**Comment by oldmcg** [comment]
Thanks Roxy.

**Pull request merged**
