### PR TITLE
Configurable number of M106 fans

### LINKED ISSUE #18529: [BUG] LCD Temperature Menu Shows Two Fans When Configured For Just One
### Bug Description

Marlin v2.0.5.3 Configuration is for only One Fan (extruder E0), however LCD 'Temperature' menu shows: 
```
Fan Speed 1:     0%
Fan Speed 2:     0%
```

**Expected behavior:** Since only one fan being used on printer and configuration is for only one fan, expect to see only one fan in LCD Temperature menu:

`Fan Speed:    0% `

### My Configurations

[ConfigFiles.zip](https://github.com/MarlinFirmware/Marlin/files/4870593/ConfigFiles.zip)

### PR DESCRIPTION
**Pull request by GMagician**
This should fix #18529

Once approved I'll update all other configurations files

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I've been testing the Biqu B1 (with an SKR 1.4) and I noticed it had an extra fan option that didn't do anything. I thought it was due to a Marlin misconfiguration out of the box, but starting with a scratch-built config, it had the same issue.

The hotend cooling fan is always powered (so not connected to `HE1`/`FAN1_PIN` like the pins file auto-defines), but setting `FAN1_PIN` to `-1` got rid of the extraneous menu item.

Having something like what's in the PR seems more logical.

**Comment by GMagician** [comment]
> 've been testing the Biqu B1 (with an SKR 1.4) and I noticed it had an extra fan option 

Yeah, this is because Marlin uses the defined pins to know how many fans it has...but that not always is the real machine config.
Overriding pins definition seems not a "correct" action, even if it solves.

**Comment by thinkyhead** [comment]
In general it would be good to get rid of the assumption in Marlin that if a fan pin exists, it should be available for control. The idea behind this was originally to allow easier expansion by enabling all fans on a board. But with the way we now re-assign pins to other things when not in use, that approach is less feasible.

So, it's a good idea to add the ability to configure how many `M106` fans you want, and then only throw a sanity-check error if there aren't pins defined for the number of fans requested.

**Comment by GMagician** [comment]
@thinkyhead it's not clear to me. Are you asking to add a sanity check when FANS is bigger than available pins?
Sorry but sometimes I have "translation/understanding" problems...

**Comment by thinkyhead** [comment]
The way this PR works is okay, since it is essentially specifying which fans will be controllable by `M106`, even if that means having more fans than extruders. It would be good to add a sanity-check in case the `FANS` value is set to something impossible.

The one other change that might be good is to rename the new `FANS` option to `NUM_M106_FANS` or `NUM_COOLING_FANS` so that it's clear that this setting refers to fans that can be controlled by `M106`.

**Pull request merged**
