### PR TITLE
[RFC] Potential improvement for serial port naming

### PR DESCRIPTION
**Pull request by X-Ryl669**
### Description

Right now, we have a situation where we are mixing `HAS_MULTISERIAL` with the fact of having 2 serial ports. This prevent declaring more than 2 serial ports in Marlin, and users asked to support 3 of them (or more).

Also, the serial ports behavior are currently generated by a combination of features (now per serial port, hopefully) but this is leading to a huge monstrosity of `#ifdef/#elif/#etc` chain. Adding a 3rd serial port to the mix will make it even uglier.

Here, I propose to nuke the serial port configuration that used to exists in Marlin and instead rely on the compiler accepting strong typing instead. 

This change can not happen for a minor release, so it means that it'll have to reach a 2.1.x release (or 3.0.x ?) 

While doing this, I think we can rely on some compiler magic here to replace the unintelligible:
```cpp
#define SERIAL_PORT -1
#define SERIAL_PORT_2 2
#define SERIAL_PORT_3 5
#define MEATPACK_ON_SP_1
#define BINARY_FILE_TRANSFER
```
into this:
```cpp
#define SERIAL_PORTS USB, UART2.with(Meatpack).with(BinaryFileTransfer), UART5
```

IMHO it'll be easier for user to grasp (and less error prone).

### Pros:
1. We can construct the compounded serial type from the user's declaration, thanks to template specialization, so not more `#ifdef MULTISERIAL` spread over the complete code base, and no #ifdef chains anymore
2. Have HAL specialize the available type (UART1, UART2 but not UART3) 
3. Could add features later on without changing the syntax in Config headers
4. Simplify sanity check code

### Cons:
1. Errors will be compiler generated (but we can minimize the ugliness by using `static_assert` here) instead of #error lines. Understand: it'll be more verbose
2. Need to rewrite a lot of code so it'll create another bug storm while it's worked on.

<details>
<summary>
  For those interested about how it could work, here's the basic implementation idea (pseudo code)
</summary>

```cpp
namespace SerialDeclaration {
    // Import the serial type supported by the current platform/board, here, we'll have USB, UART0, UART1, etc...
    #include "HAL/[...]/SerialDeclaration.h"
  
   template <typename Decl>
   struct DeduceSerialTypeToUse {
      typedef ForwardSerial1<Decl> type;
      constexpr static DeduceSerialTypeToUse<MeatPackSerial<Decl>> with(MeatpackType & a); // Does not need any definition, since we only use the type  
    };

   // Equivalent to sanity check for some HAL (could/should be in the HAL subfolder):
   template <> struct DeduceSerialTypeToUse<UART3> { DeduceSerialTypeToUse() { static_assert(false, "UART3 is not supported on STM32F1"); }};

   // And the magic is here
   typedef DeduceSerialTypeToUse<SERIAL_PORTS>::type SERIAL_IMPL;
```

</details>

The goal of this PR is to query the developers' opinion on this change to check if it would be accepted (and worth spending time on it). 

### Requirements

N/A

### Configurations

See the current commit for an example of the syntax

### Related Issues

This will create related issues.

### CODE REVIEW

**Comment by rhapsodyv** [comment]
I don’t like it. Config is data, not code. If we start marking it look like code, we will have far more user support.
And I don’t see any advantage on this composition, as we will never have too many options to all this flexibility make sense.

**Comment by X-Ryl669** [comment]
Ok. I'm trying to find a way that's not cryptic to user (like what I got this morning "Did not know -1 was USB", or the user writing "I don't understand, I'm using UART2 and enabled Meatpack on SERIAL_PORT_2 and it does not work"). 

So I think if the user could write `#define SerialPort1 USB` `#define SerialPort2 UART3` it'd be easier to understand.

If you look into the HAL code, it's a real mess when dealing with all the possible cases (`#if SERIAL_PORT == -1 #elif WITHIN(SERIAL_PORT, 0, 6) #elif multiserial #if SERIAL_CATCHALL`" + Meatpack on top and the composition becomes a nightmare to maintain. 

Most meatpack errors recently are due to user misconfiguring Marlin. 

And there are users asking for 3 serial ports, so I don't even think about how painful it'll be to handle all possible cases if we start implementing 7 serials port like it is now. 

So we have to find a way to make it, at the same time, both easier for the user to "do it right" and less painful for us to support.
What do you think, how should we do it?

**Comment by thinkyhead** [comment]
> If you look into the HAL code, it's a real mess when dealing with all the possible cases…

I agree that it is not concise, but I look at a lot of that element in the serial headers as documentation about the platforms that they target. (And we can most easily error-check the user's configuration setting if it is numeric.) We can see in those headers exactly how many ports are expected and in what order, and so on. Moving that responsibility off to the user removes that context and makes it more likely that we will all be scanning datasheets more often. So, now we simply say "There are X ports and '-1' is the USB port," and that is simplified … but I agree it is oversimplified when looking to the future. It would be better to start by adding this…
```cpp
#define _USB_ -1 // In a header
. . .
#define SERIAL_PORT _USB_ // Could be -1, or whatever...
#define SERIAL_PORT_2 3 // (i.e., UART3)
```
…and then as more 'distinct' ports come along (other than `UART0`, `1`, `2`, etc.) those can get unique named identifiers as well.

If we allow users to set options as code directly, we cannot easily error-check them, and we tie configurations to very specific implementations…. So, I will have to vote against allowing user to set options in this manner at this time.

My suggestion is to move the bits scattered around the headers into an "intermediate layer" which allows users to directly set the "eventual" ports that will come out, but if they don't set them directly then it falls back to the numeric-settings-as-lookups as we now have them.

**Comment by thinkyhead** [comment]
Following up on that, just using numeric defines (see `drivers.h`) we can of course do this 👇🏻 kind of thing too, for up to 32 options on a single line…

```cpp
#define SERIAL_PORT _USB_ + _MEATPACK_ + _BINSTREAM_
// OR if you prefer…
#define SERIAL_PORT _USB_ | _MEATPACK_ | _BINSTREAM_
. . .
#define CAN_MEATPACK(P) !((P) & _LCD_) // Some LCD that won't MeatPack
. . .
#define WANT_MEATPACK(P) ((P) & _MEATPACK_)
. . .
#if WANT_MEATPACK(SERIAL_PORT)
  . . .
#endif
```

**Comment by thinkyhead** [comment]
To clarify the "`HAS_MULTISERIAL`" option one could rename it "`HAS_MULTI_HOST`" and it only relates to the way Marlin sends all serial output that hosts would care about out to multiple destinations as the default behavior. The define formerly named `SERIAL_BOTH`, now named `SERIAL_ALL` is the ID used when Marlin wants to refer to this "multi-host" situation.

Please feel free to rename anything which is defined by the `Conditionals*` files, to update their meaning so they better reflect changes in the code. We should not argue with the past. Everything beyond the end user's common view is malleable.

**Comment by X-Ryl669** [comment]
We can use USB and UART3 here (no need for `_USB_` decoration). The only trick is to expand the macro in a namespace so it does not collide with existing name. The namespace can have all sanity check we want, but instead of macro, it can be static_assert. 

From a user perspective, it'll be cleaner, IMHO. We can even use enum for the name `enum SerialPort { USB = -1, UART0 = 0, etc...` so old configuration with numbers still work.

I agree that ORing the flags can probably make it better than ".with(something)". It's still code, but it's probably easier to understand.

**Comment by rhapsodyv** [comment]
I sent to Scott some time ago, and some days ago again, my idea to solve the main issue with those serial config: the user don't know what means the numbers. So, they should not see any number. Of course we can have a config for advanced users, but the normal user just want "USB" and "TFT" enabled.... Not "-1" and "3".

So I have an unpublished work that does this:

Each board define the number of the named serial.
For example:
In the Nano V2 pins file:
```cpp
#define SERIAL_USB_NUMBER 3
#define SERIAL_WIFI_NUMBER 1
#define SERIAL_TFT_NUMBER 1
```

Then, the user just select which serial he wants enabled:
```cpp
#define SERIAL_USB
#define SERIAL_TFT
//#define SERIAL_WIFI
```

I'm pretty ok with the `MEATPACK_ON_SERIAL_PORT_1`, but we can add this in my original idea:
```cpp
#define SERIAL_USB MEATPACK | BINARY
#define SERIAL_TFT
//#define SERIAL_WIFI
```

**Comment by thinkyhead** [comment]
Keep me posted as you work on developing the best solution. I've gotta get back to working on tasks for the release.

**Comment by X-Ryl669** [comment]
I think it's a good idea not to talk about serial port 1 and 2 anymore. And I think it'll be possible to compute the *Giant Serial Typedef* without the #ifdef hell if set this way.

**Comment by thinkyhead** [comment]
Build it the best way, but if possible don't make users have to type out the letters U-A-R-T in their configs because it's just mean to expose them to our jargon.

**Comment by X-Ryl669** [comment]
@rhapsodyv What is the branch you are referring to ?

**Comment by rhapsodyv** [comment]
> @rhapsodyv What is the branch you are referring to ?

I will revive my stash and push it

**Comment by X-Ryl669** [comment]
If it's not finished, just point me on your branch and I'll take over.

**Comment by X-Ryl669** [comment]
I'm rethinking about this one, and Victor's solution would not work if there are more than 1 port per type (for example, if you have 2 UART on your board, `#define SERIAL_UART` isn't clear which one to use, and expecting the user to fix the pin file is bad IMHO).

Right now, the serial port are indexed in the Arduino's jargon (serial0 is the port that Arduino's framework uses for its first UART, and so on), plus a bit of dark magic (like -1 for USB, or -2 for telnet)...

So it's obscure anyway for a user which number matches which UART (unless they dig into their framework's internals), they'll just copy what they got from someone else configuration. Using UART here would probably be easier, since most board's schematic specify which UART a port is using (and not the Arduino's SerialN).
I guess each Arduino framework in use currently try to set Serial to first UART (0 or 1 depending on the numbering chosen) and SerialN to the N-th UART.

So, instead of what I've initially proposed, we could have:
```cpp
#define SERIAL_PORT_1 USB
#define SERIAL_PORT_2 Port1 + MeatPack + Binary
#define SERIAL_PORT_3 LCD
```

**Comment by rhapsodyv** [comment]
I never suggested “SERIAL_UART”, it simply doesn’t make sense.

My suggestion is SERIAL_(SLOT NAME OR USAGE).
Uart is the underlying protocol. Most of boards have 2 or 3 available uarts. Each one linked to one slot with designed functionality: LCD, WIFI, USB…

I think you misunderstood my suggestion.

**Comment by X-Ryl669** [comment]
Let's take an example here. I've a Robin Nano board. Here, the PC serial port is UART3, WIFI use UART1. Yet, we have 4  more UART for TMC stepper controller, and UART2 is also available, but requires soldering pins on the motherboard.
Also, the USART3 goes into a UART/USB conversion chip, so from the user's point of view, it's a USB port. 

How would you name the serial port then ?
1. UART3 <=> SERIAL_USB  ?? (even if it's not USB in reality from the µc point of view)
2. UART1 = SERIAL_WIFI (ok, this one is easy)
3. UART2 = SERIAL_OPTIONAL ?
4. Software serialX to X+4 = SERIAL_TMC_X ?

**Comment by rhapsodyv** [comment]
Nano board pins file will set:

```cpp
#define SERIAL_USB_NUMBER 3
#define SERIAL_WIFI_NUMBER 1
#define SERIAL_TFT_NUMBER 2
```

And the user, in the `Configuration.h` will set:
```cpp
#define SERIAL_USB MEATPACK
#define SERIAL_USB_BAUDRATE 250000

#define SERIAL_WIFI
#define SERIAL_WIFI_BAUDRATE 1150000

//#define SERIAL_TFT
```

For the user point of view, he wants enable the "usb to talk with the computer" or the "tft" or the "wifi module"... Most of the users don't know or don't care if the usb connect is uart or usb serial... 

If a power user want to customize things, he can add in the Configuration.h:
```cpp
#define SERIAL_CUSTOM_1_NUMBER 1
#define SERIAL_CUSTOM MEATPACK

#define SERIAL_CUSTOM_2_NUMBER 2
#define SERIAL_CUSTOM
```
I don't even see yet the need for a custom serial definition, but we can have one or two.

**Pull request closed without merging**
