### PR TITLE
⚡️ Menu usability tweaks

### PR DESCRIPTION
**Pull request by EvilGremlin**
### Description

Removed redundant space-wasting back item for TFT UIs, moved filament change up to first screen where it belongs.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> Removed redundant space-wasting back item for color_ui,

For TFTs with encoders & `TOUCH_SCREEN` disabled, you have no way to go back unless you rely on `LCD_TIMEOUT_TO_STATUS`.

**Comment by EvilGremlin** [comment]
Drat, that's true. And  i remember couple guys telling they prefer encoder even with touchscreen. Will fix.

**Comment by thisiskeithb** [comment]
> And i remember couple guys telling they prefer encoder even with touchscreen. 

I'm one of them 😄

**Comment by EvilGremlin** [comment]
if wonder if it'll catch all?
``` 
#if HAS_ROTARY_ENCODER
    BACK_ITEM(MSG_INFO_SCREEN);
```
nope, adc buttons too...

**Comment by thisiskeithb** [comment]
> #if HAS_ROTARY_ENCODER

I don't think there will be other input gizmos on the various TFTs, but you never know.

**Comment by thisiskeithb** [comment]
I don’t think https://github.com/MarlinFirmware/Marlin/pull/24607/commits/dd03a0366c8d4eea050f2955ac6ef5d496048d67 does what you want since you can have any combination of encoder/touch screen and it can still result in the back (Main) menu item showing up.

Example: B1 SE Plus with a BTT TFT35 SPI  which is a touchscreen TFT that has an encoder. With `TOUCH_SCREEN` enabled, that “Main” menu item will still show up in `TFT_COLOR_UI`.

**Comment by EvilGremlin** [comment]
Yep, that was intention, so both can be used.
But maybe add someting like USE_ENCODER_TOO under TOUCHSCREEN?

**Comment by thisiskeithb** [comment]
There may be another macro for encoder/ADC buttons/other input, but this will hide the "Main" option in `TFT_CLASSIC_UI` and `TFT_COLOR_UI` if `TOUCHSCREEN` is enabled and you still have an encoder/adc buttons:

```cpp
#if DISABLED(TOUCHSCREEN) && EITHER(HAS_ROTARY_ENCODER, HAS_ADC_BUTTONS)
  BACK_ITEM(MSG_INFO_SCREEN);
#endif
```

**Comment by EvilGremlin** [comment]
This is same as just `#if DISABLED(TOUCHSCREEN)`
And that top back item exist in all other menus too, though it's not so wasteful there.
So it gotta be `SHOW_BACK_ITEM` condition and then TERN_() in all the menus.

**Comment by EvilGremlin** [comment]
Squash doesn't work quite like i imagined :(

**Pull request closed without merging**
