### PR TITLE
Provide fan speed, status for BTT touch-screen

### PR DESCRIPTION
**Pull request by StarNamer**
### Requirements

This change allows M117 messages to display in the info area of the BigTreeTech touchscreen display and the fan speed to be updated when it's changed by an M106 command

### Description

The current version of firmware for the BigTreeTech touchscreen firmware (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware) which is common to various models (TFT24, TFT28, TFT35, etc) recognises 'echo:' messages received on its serial interface. A message of the for 'echo:  M106 P<fan> S<speed>' will update the fan speed indicator. Any unrecognised message is displayed in the 'info' area.

This change, controlled by defining BTT_TOUCHSCREEN, will cause the M117 command to send the text of the message to the BTT TFT (actually of both serial ports). If the fan speed is changed, by any means, but usuallly M106, the change is notified to the BTT TFT by echoing a simulated 'M106 P<fan> S<speed>' message, e.g. 'M106 P0 S255' to indicate fan zero to 100%.

### Benefits

Without this, M117 messages are ignored when using a TFTxx screen in touch mode; they are only visible while using the 12864 simulator. Similarly, touch mode is not notified of fan speed so it remains at 0%.

### Configurations

Configuration_adv.h is included with the extra definition of the BTT_TOUCHSCREEN variable.

Code was tested with an Ender-3; configuration.h, configuration_adv.h and platformio.ini attached

[platformio.ini & configuration.h.zip](https://github.com/MarlinFirmware/Marlin/files/5171146/platformio.ini.configuration.h.zip)

### Related Issues

No related issues. I originally thought the display of M117 messages needed changes to the BTT Tpuchscreen firmware, but it turns out that the Marlin firmware is simply not sending the info to the TFT.

### CODE REVIEW

**Comment by StarNamer** [comment]
Screwed up by including all commits pushed!

**Comment by StarNamer** [comment]
This is the first time I've tried to create a Pull Request and I think I screwed it up. I don't think it should have included everyone else's commits which were pushed to bring my fork up to date, but am not sure what I did wrong.

[Update: I worked out what was wrong!]

**Comment by StarNamer** [comment]
OK. I sorted it. The pull request was against the wrong base!

**Comment by thisiskeithb** [comment]
Does the `BTT_TOUCHSCREEN` define need to be there?

BigTreeTech put in a PR recently that announces print completion on all serial ports without it: https://github.com/MarlinFirmware/Marlin/pull/19102

**Comment by rhapsodyv** [comment]
Is this specific for BTT, or any other serial TFT will benefit from this? Maybe even octoprint? 🤔

**Comment by thisiskeithb** [comment]
> Is this specific for BTT, or any other serial TFT will benefit from this? Maybe even octoprint? 🤔

That's what I was thinking. Just make it generic and announce to all serial ports without the special define.

**Comment by thinkyhead** [comment]
I'd like to see if this could be modified to send the message only to the serial port that the display is connected to. I'm not sure how to determine that, unless it can be assumed based on the total number of serial ports and the number of controllers that are connected.

**Review by rhapsodyv — COMMENTED** [review]
I think “LCD_” is not a good prefix.. I think is better: “SERIAL_”, is it is not necessarily related to a lcd... and any serial client would benefit

**Comment by thinkyhead** [comment]
I'm not keen on adding more noise on all the serial lines, echoing everything to everyone. A host can already see the bytes it is sending so it doesn't necessarily need an always-on echo. Many hosts like to send lots of `M117` messages to show time remaining or other information, so echoing that back to the sender is unnecessary.

I'd prefer that this PR stick to its narrow intention, to fulfill the need for LCDs that want these messages. But in the naming of these options I want to express what they actually do. Maybe they ought to be defined in a Conditionals file instead, based on which LCD is enabled in the configuration. Maybe we need to add a new LCD here?

I'd rather not make this change into something "for the benefit of every serial host" because I don't think this PR is quite the right way to start down that road.

**Comment by thisiskeithb** [comment]
> Maybe we need to add a new LCD here?

That seems like a slippery slope and would need to be done for every standalone TFT, not just BigTreeTech's that communicates via serial when they worked in the past with only needing to enable the correct serial port settings (and in BigTreeTech's-specific case, `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` or `CR10_STOCKDISPLAY` for "Marlin Mode".)

**Comment by rhapsodyv** [comment]
I understand the concern about "feature for everyone". I'm working with marlin for a few months, but for me, LCD is one thing, SERIAL is another and TFT is another.
The fact that some TFT use the serial to communicate with marlin, for me, needs to be transparent to Marlin. Marlin use serial to communicate gcodes and send responses. It's a standard marlin "interface". 
If any TFT needs some special protocol through serial, they need write they own "tft module" using extui, for example.

Calling a "standard" serial output as "LCD_THING", at least for me, is very confusing. Or BTT (and others) parse marlin standard serial interface, or they write they own "extui".

What the user is asking, for me, is really a serial announcement... as we already have some others, like `AUTO_REPORT_SD_STATUS`... 

Now, which serial it is outputting, if it is correct or not, I think is another question.

We have:
 - LCDs (old fashioned/simple) displays
 - TFT (marlin controlled TFT)
 - Standard Marlin Serial Interface 
 - Custom Marlin Serial Protocols specific to some displays (extui)
 
BTT "Smart" TFT, for me, is not a thing that marlin must know, as it just use the standard marlin serial interface. Like OctoPrint.

**Comment by AnHardt** [comment]
Up to now the "BTT smart displays" (and MKS) with own processor and serial interace are "hosts" - like OctoPrint, RH, Pronterface, Slic3r, ... . That would stay the sam regardless of being connected via Serial, USB, Bluetooth, WiFi, Network, IR-link, ... .
So the problem, for me, is, if we want to allow allow multiple hosts at all: "How to inform the other host(s) about what is/was changed by one of them."
We already have the same problem with the Marlin native menus. In the direction of informing the host. Our menu has the advantage over normal hostes in being able to read Marlins variables directly - so it is (can be) always informed. Since sending g-codes its also kind of a host.

If the view is widened even more the files systems are dumb hosts - needing no informational feedback because they can't react. But what shall we do when they are changing parameters - like feedrate, accelerations, ... .

That needs to have a solid concept. Up to now we only patched the places where the problem became obvious.

**Comment by thisiskeithb** [comment]
> So the problem, for me, is, if we want to allow allow multiple hosts at all: "How to inform the other host(s) about what is/was changed by one of them."

Running OctoPrint in combination with these serial TFT screens/hosts is a common config, so having Marlin be able to talk to both hosts (and keep them in sync) would be ideal.

**Comment by StarNamer** [comment]
Because OctoPrint + serial TFT screen seemed so common, I was surprised this hadn't come up before. Obviously, a more 'generic' solution of keeping multiple hosts informed about each other's changes would be better; this was simply a solution to a perceived issue. I did consider adding logic to only send to the 'other' host, but decided it was simpler and did no harm to send to both.

**Comment by StarNamer** [comment]
It seems the fan speed reporting is already covered by PR [#18013](https://github.com/MarlinFirmware/Marlin/pull/18013) which implemented the REPORT_FAN_SPEED flag. So the change to temperature.cpp is redundant but whatever flag sets reporting for BTT touchscreen or similar serial hosts should also #define REPORT_FAN_SPEED.

**Comment by StarNamer** [comment]
Of course, it seems OctoPrint Dashboard ignores changes reported by echoing M106 Px Sy....!

**Comment by rhapsodyv** [comment]
about naming, `REPORT_FAN_SPEED` or `REPORT_sssss` is a way better that `LCD_`, and solves the `serial_` noise...

**Comment by thinkyhead** [comment]
It occurs to me that these options could or should be defined as the serial port that the report will go to, instead of assuming that they should go to all ports. If you do want to report to all the ports you can define them without a value, or perhaps use "`SERIAL_BOTH`." AFAIK there's no general way in Marlin to determine which serial port pertains to the LCD.

**Comment by rhapsodyv** [comment]
> It occurs to me that these options could or should be defined as the serial port that the report will go to, instead of assuming that they should go to all ports. If you do want to report to all the ports you can define them without a value, or perhaps use "`SERIAL_BOTH`." AFAIK there's no general way in Marlin to determine which serial port pertains to the LCD.

Having a way to define that auto reports goes for one or other, or all serial is a good idea.

But I don't think marlin needs to know the serial that have a LCD. It just need to know that serial X needs something. But it could be a LCD, or any other client, transparent to Marlin.

Maybe we need a general GCode that enable those auto reports in the serial it was called... or we rely on the user to defining it right.

Like: M0000 F -> enable auto report for feature FOO in the current serial....

**Comment by thinkyhead** [comment]
Be careful to distinguish the features in Marlin which are currently referred to as "auto reporting" (where Marlin is instructed by `M155` or `M122` to send reports at regular timed intervals) and calls to `report_position` or other reporting functions (where Marlin emits a string immediately in response to a state change).

These immediate responses to state change are not "auto reporting" but more like "echoing" so I suppose they might be called "`ECHO_FAN_SPEED`" and "`ECHO_STATUS_MESSAGE`."

**Comment by whitedavil** [comment]
The problem is the display. It's not parsing the //action:notification.
On the btt github in the thread issue of the author, I posted the solution with a small pieces of code. Unfortunately I'm not able to open a new branch and a new pull request ecc. for add my solution on the master branch. 
Please check the issue on btt github for the solution.

**Comment by thinkyhead** [comment]
Please confirm whether this is still needed, given that there have been updates to the touchscreen firmware. This is now cleaned and simplified about as much as possible.

**Comment by thisiskeithb** [comment]
> Please confirm whether this is still needed, given that there have been updates to the touchscreen firmware. This is now cleaned and simplified about as much as possible.

I don’t think so since the TFT firmware now (correctly) uses `HOST_ACTION_COMMANDS`:

```cpp
/**
 * Notification M117
 * If enabled, any notification received from Marlin through "//action:notification" is also
 * stored on the notification screen. The notification screen reporting the history of the
 * received notifications is displayed pressing on the notification bar.
 *
 * NOTE: Marlin notifications are also always displayed on the Status Screen menu.
 *       Furthermore, they are also displayed on the notification bar as toast messages
 *       in case the current menu is not the Status Screen menu.
 *
 *   Options: [disable: 0, enable: 1]
 */
#define NOTIFICATION_M117 0  // Default: 0
```

Also, adding a `BTT_SERIAL_CONTROLLER` define is going to inevitably confuse users since they still need to define `REPRAP_DISCOUNT_SMART_CONTROLLER`, `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`, or `CR10_STOCKDISPLAY` depending on how the TFT is connected / configured if they want to use “Marlin Mode”.

**Pull request closed without merging**
