### PR TITLE
MightyBoard: Fix digipot I2C pullups, remove MightyCore, add optimized build flags

### PR DESCRIPTION
**Pull request by grauerfuchs**
### Requirements
Bugfixes and optimizations for Mightyboard

### Description
The MegaCore library not only defines pins differently than the extended library (and the old Sailfish instructions for modifying the pins file), but it also introduces a number of different library versions that will complicate debugging efforts. Now that the mega2560ext variant is here and tested to be stable, this will switch the MightyBoard over to using the variant definition provided by that without also requiring different library versions.

This PR also introduces an option into the MCP4018 digipot code to enable internal pull-ups. This had previously been the default of the custom revision of SlowSoftI2CMaster formerly listed in the MCP4018 code. However, moving to the primary repository eliminated the pull-ups and caused issues with the digipots (issue #20459). Because the default has now been to *not* enable pull-ups, an option was added to enable the feature and prevent potential conflicts with code/hardware following the assumption that internal pull-ups are not used.

Additionally, this PR adapts the optimizations / tuning previously introduced for the atmega1284p into use for both the atmega2560 and atmega1280 on the Mightyboard. These build flags are stable on these chips and will reduce the code size considerably.

### Benefits
Corrects I2C issues related to issue #20459
Allows other boards using MCP4018 to enable internal pull-ups for I2C communication where needed
Adds build-time optimization for Mightyboard environments

### Related Issues
Issue #20459

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Related issue: https://github.com/MarlinFirmware/Marlin/issues/20459

**Comment by thisiskeithb** [comment]
It helps maintainers a lot if you stick to the PR template 🙂

**Comment by grauerfuchs** [comment]
It's a lot easier to do when you're not trying to complete running edits via the web interface. All you had to do was wait a few minutes.

**Comment by thinkyhead** [comment]
I believe the line `board_upload.maximum_size = 253952` might be a safety guard. Do you know that it is safe to remove?

**Comment by grauerfuchs** [comment]
It was a safety guard against the defaults in the MegaCore libs, which were intended for use with a completely different bootloader. The only reason I removed it here was because the default megaatmega2560 board definition from PlatformIO expects the STKv2 bootloader, which is what FFCP/MightyBoard Rev E uses.

From the megaatmega2560.json file dated Oct 29:
```
...
  "name": "Arduino Mega or Mega 2560 ATmega2560 (Mega 2560)",
  "upload": {
    "maximum_ram_size": 8192,
    "maximum_size": 253952,
    "protocol": "wiring",
    "require_upload_port": true,
    "speed": 115200
  },
...
```

**Comment by thinkyhead** [comment]
Excellent. I like it when these threads become repositories of useful info!

**Pull request merged**
