### PR TITLE
Init all ESP01 WIFI pins (ESP01 module)

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
On the ESP01 WIFI module the **GPIO0** and **GPIO2** pins can be left open and the module will still operated properly.  This is because the ESP3D software configures the **GPIO0** and **GPIO2** pins as inputs with pullups.

This PR gives the user the option of explicitly driving these pins high.

~This PR is strictly a defensive move in case the WIFI module's software is changed or we run into a motherboard that doesn't follow convention.~

---

The module will operate normally if the **RESET** pin is also left open.  I never did find primary source documentation stating this was OK.

---

FYI - **ESP_WIFI_MODULE_COM** and **ESP_WIFI_MODULE_BAUDRATE** defines in the **pins_YOUR_BOARD.h** file don't actually do anything.  Their only purpose is to inform/remind the user.

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Per PR #17531, we've now seen one ESP01/motherboard combo that requires explicitly driving the four pins for proper operation.

**Comment by MoellerDi** [comment]
Thanks, this PR allows me to actually use my ESP01S on SKR Pro ;-)

**Comment by Bob-the-Kuhn** [comment]
Switched to the latest **language_de.h.** 

Previously guessed wrong as to which of the duplicate defines would be kept.

**Comment by DroneMang** [comment]
> Thanks, this PR allows me to actually use my ESP01S on SKR Pro ;-)

Could you outline the steps needed to get this working on the SKR PRO?  Trying to get this working myself.  Thanks!

**Comment by MoellerDi** [comment]
@DroneMang sure ;-)
I managed to flash ESP3D on my ESP01S and just set the related serial port
(#define SERIAL_PORT_2 6) in Marlin. 

Most difficult part was to get ESP3D running on the ESP01S; I was following https://github.com/luc-github/ESP3D/wiki/Install-Instructions

However w/o this PR the ESP01S wasn't working when it was plugged (but working fine otherwise). It's working fine now with this PR merged.

**Pull request merged**
