### PR TITLE
Add example configs. Expand custom menu.

### PR DESCRIPTION
**Pull request by Vertabreak**
Add Configs for

- Anet E10
- Geeetech D200
- Geeetech M201
- JGAurora Magic
- MakerFarm Pegasus 12

Expands custom menu to 25.

### CODE REVIEW

**Comment by thinkyhead** [comment]
The custom menu stuff is probably optional. We provide a set of 10 that gives the gist of how they work, and we assume enterprising hobbyists who want more will figure out how to add more if they really need it.

**Comment by Vertabreak** [comment]
ill trim it back to 10 in configuration_adv.h could drop in some examples if you want?

**Comment by thinkyhead** [comment]
> ill trim it back to 10 in configuration_adv.h could drop in some examples if you want?

No need. Note that any change made to the config must be propagated to the other 120+ config files.

**Comment by Vertabreak** [comment]
well if you need me to make any adjustments to the PR i will just let me know.

**Pull request merged**
