### PR TITLE
Use RTD for MAX31865 reading

### PR DESCRIPTION
**Pull request by GadgetAngel**
## Requirements

The following equipment was used to test this PR: 
* SKR V1.4 Turbo board
* 2 PT100 sensors
* (1) 100K Thermistor (to verify the temperatures being displayed by the Adafruit MAX31865 boards with PT100 sensors attached)
* BTT TFT35 V3.0 display attached to EXP1 and EXP2 port on the SKR V1.4 Turbo board
* a clamp on tap for the EXP2 ribbon cable so I can access the default hardware SPI lines (https://www.digikey.com/product-detail/en/te-connectivity-amp-connectors/1658622-1/AKC10B-ND/825411)
* a soldering iron in a soldering stand
* "helping hands" to hold the three temperature sensor so I can adjust them to see if temperature readings are correct and change as expected
* laptop with USB connection to the SKR V1.4 Turbo for use with pronterface
* Ohm meter to check the PT100 sensor to ensure that they read ~110 Ohm
* Dupont jumper cables to attach the two Adafruit MAX31865 boards. Some Dupont Jumpers cables were used to also create Y-Jumper cables

#### This pull request fixes the values sent to the serial port when `#define SHOW_TEMP_ADC_VALUES` and `#define AUTO_REPORT_TEMPERATURES` are enabled.  This pull request also stream lines the Marlin code to get ride of a redundant calls to  Adafruit_MAX31865::temperature routine.

---
### Special Editing to get Marlin to run Adafruit MAX31865 boards on SKR V1.4 Turbo Board
To allow Adafruit MAX31865 boards to run on SKR V1.4 Turbo I had to change the following in Adfruit_MAX31865.h file:
original code:
```
#if (ARDUINO >= 100)
#include "Arduino.h"
#else
#include "WProgram.h"
#endif
```
Edited code:
```
#if (ARDUINO >= 100 || ARDUINOLPC >= 100)
#include "Arduino.h"
#else
#include "WProgram.h"
#endif
```
The platform files for SKR V1.4 Turbo https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip do not set the ARDUINO compiler constant. The platform does set the compiler constant ARDUINOLPC.

To fix the issue with the Adafruit MAX31865 SPI speed being converted to 125,000 from 500,00 I had to do the following change in Adafruit_MAX31865.cpp code:
Original code:
```
static SPISettings max31865_spisettings =
    SPISettings(500000, MSBFIRST, SPI_MODE1);
```
Edited code:
```
#ifdef TARGET_LPC1768
  static SPISettings max31865_spisettings =
    SPISettings(SPI_SIXTEENTH_SPEED, MSBFIRST, SPI_MODE1);
#else
  static SPISettings max31865_spisettings =
    SPISettings(500000, MSBFIRST, SPI_MODE1);
#endif
```
---

#### Below I describe where I added code to Marlin or fixed the code that was present in Marlin:

In Marlin\src\module\temperature.h file I added a new private member "convert_rtd_resistance".

The rest of the changes where done in temperature.cpp code (Temperature::read_max6675 routine).

At line 2207 I instantiate a new variable called max31865_resistance.

At line 2252, I remove the code that called Adafruit_MAX31865::temperature routine and replace it with a call to calculate the RTD resistance value (Temperature::convert_rtd_resistance routine).  The call to convert the RTD value to temperature in Celsius is done in Temperature::analog_to_celsius_hotend routine which is the next call that Temperature::updateTemperaturesFromRawValues() does after it receives the raw values from Temperature::read_max6675 routine.  Otherwise, we end up calling Adafruit_MAX31865::temperature routine twice for no reason.

At line 2332, I add a comment and code to allow the calculated RTD resistance value to be returned to Temperature::updateTemperaturesFromRawValues() routine.

At line 2342, I added a private member to Temperature  class called "convert_rtd_resistance" routine, which does the actual calculation of the RTD resistance value.

### Benefits

This is the background of why I have asked for this pull request:

#### Bug Description

The Adafruit MAX31865 is being called multiple times for temperature when only one time is needed.  

Also, The ADC value being sent back to thermalManager.auto_report_temperatures(); routine appears to be the RTD value from the MAX31865 chip but I am not really sure because the MAX31865 is not a MAX6675 board and the code is built on top of the MAX6675 code.  

I would like to see the RTD value converted to a resistance value and placed in temp_hotend[0].raw and temp_hotend[1].raw.  Right now both temp_hotend[0].raw and temp_hotend[1].raw variables, (when the MAX31865), are getting an ADC count of  ~3,000, when AUTO_REPORT_TEMPERATURES is enabled. Which looks like a bug because the values at room temperature should be ~190.  

This issue is in temperature.cpp code. There are two places in temperature.cpp code that calls the Adafruit_MAX31865::temperature() routine:  The first routine to call Adafruit_MAX31865::temperature is Temperature::updateTemperaturesFromRawValues() routine which calls the Adafruit_MAX31865::temperature() routine twice. 

Temperature::updateTemperaturesFromRawValues():
```
  TERN_(HEATER_0_USES_MAX6675, temp_hotend[0].raw = READ_MAX6675(0));
  TERN_(HEATER_1_USES_MAX6675, temp_hotend[1].raw = READ_MAX6675(1));
  #if HAS_HOTEND
    HOTEND_LOOP() temp_hotend[e].celsius = analog_to_celsius_hotend(temp_hotend[e].raw, e);
  #endif
```
Temperature::updateTemperaturesFromRawValues() makes a call to Temperature::read_max6675() which in turn calls Adafruit_MAX31865::temperature and the value is placed in max6675_temp which gets immediately over written and set to 0 (look for section of code with comment // Read a big-endian temperature value).  

Temperature::read_max6675():
```
    #if HAS_MAX31865
      Adafruit_MAX31865 &maxref = MAX6675_SEL(max31865_0, max31865_1);
      max6675_temp = int(maxref.temperature(
        MAX6675_SEL(MAX31865_SENSOR_OHMS_0, MAX31865_SENSOR_OHMS_1),
        MAX6675_SEL(MAX31865_CALIBRATION_OHMS_0, MAX31865_CALIBRATION_OHMS_1)
      ));
    #endif
    //
    // TODO: spiBegin, spiRec and spiInit doesn't work when soft spi is used.
    //
    #if !MAX6675_SEPARATE_SPI
      spiBegin();
      spiInit(MAX6675_SPEED_BITS);
    #endif

    MAX6675_WRITE(LOW);  // enable TT_MAX6675
    DELAY_NS(100);       // Ensure 100ns delay

    // Read a big-endian temperature value
    max6675_temp = 0;
    for (uint8_t i = sizeof(max6675_temp); i--;) {
      max6675_temp |= TERN(MAX6675_SEPARATE_SPI, max6675_spi.receive(), spiRec());
      if (i > 0) max6675_temp <<= 8; // shift left if not the last byte
    }
```
So why do we need the call to Adafruit_MAX31865::temperature in Temperature::read_max6675()? 

We need to see if there is an error due to the Adafruit MAX31865 board but that is now handled by maxref.readFault() call.  

What is really needed in Temperature::read_max6675() is the calculation of the resistance value of the RTD device and have that returned back into temp_hotend[0].raw and temp_hotend[1].raw so that thermalManager.auto_report_temperatures(); routine will display a reasonable count value for the Marlin user.

The second place in Temperature::updateTemperaturesFromRawValues() routine that calls Adafruit_MAX31865::temperature() is the correct way to handle the call.  Since the second calls' return value is being placed in a variable that wants the temperature converted in Celsius,  temp_hotend[e].celsius.
```
HOTEND_LOOP() temp_hotend[e].celsius = analog_to_celsius_hotend(temp_hotend[e].raw, e);
```
The interesting thing about the above call to Temperature::analog_to_celsius_hotend(const int raw, const uint8_t e) is that the calling routine's variable temp_hotend[e].raw  (or raw when inside Temperature::analog_to_celsius_hotend routine) is NEVER used by the MAX31865.  I know its used by other devices but the temp_hotend[0].raw and temp_hotend[1].raw are not used when a extruder has a MAX31865 temperature sensor. So those variables are only used to display the ADC values of the temperature sensor, which in the MAX31865 boards is the RTD resistance calculation value not the raw RTD value.

Temperature::analog_to_celsius_hotend(const int raw, const uint8_t e):
```
      if (e > HOTENDS - DISABLED(TEMP_SENSOR_1_AS_REDUNDANT)) {
        SERIAL_ERROR_START();
        SERIAL_ECHO((int)e);
        SERIAL_ECHOLNPGM(STR_INVALID_EXTRUDER_NUM);
        kill();
        return 0;
      }
      
    switch (e) {
      case 0:
        #if HEATER_0_USER_THERMISTOR
          return user_thermistor_to_deg_c(CTI_HOTEND_0, raw);
        #elif HEATER_0_USES_MAX6675
          return TERN(MAX6675_0_IS_MAX31865, max31865_0.temperature(MAX31865_SENSOR_OHMS_0, MAX31865_CALIBRATION_OHMS_0), raw * 0.25);
        #elif HEATER_0_USES_AD595
          return TEMP_AD595(raw);
        #elif HEATER_0_USES_AD8495
          return TEMP_AD8495(raw);
        #else
          break;
        #endif
      case 1:
        #if HEATER_1_USER_THERMISTOR
          return user_thermistor_to_deg_c(CTI_HOTEND_1, raw);
        #elif HEATER_1_USES_MAX6675
          return TERN(MAX6675_1_IS_MAX31865, max31865_1.temperature(MAX31865_SENSOR_OHMS_1, MAX31865_CALIBRATION_OHMS_1), raw * 0.25);
        #elif HEATER_1_USES_AD595
          return TEMP_AD595(raw);
        #elif HEATER_1_USES_AD8495
          return TEMP_AD8495(raw);
        #else
          break;
        #endif
      case 2:
        #if HEATER_2_USER_THERMISTOR
          return user_thermistor_to_deg_c(CTI_HOTEND_2, raw);
        #elif HEATER_2_USES_AD595
          return TEMP_AD595(raw);
        #elif HEATER_2_USES_AD8495
          return TEMP_AD8495(raw);
        #else
          break;
        #endif
.
.
.
    }

    #if HAS_HOTEND_THERMISTOR
      // Thermistor with conversion table?
      const temp_entry_t(*tt)[] = (temp_entry_t(*)[])(heater_ttbl_map[e]);
      SCAN_THERMISTOR_TABLE((*tt), heater_ttbllen_map[e]);
    #endif

    return 0;
``` 

### Configuration Files

[Configuration-Fix-MAX31865-Show-Values.zip](https://github.com/GadgetAngel/Test/files/5558033/Configuration-Fix-MAX31865-Show-Values.zip)

### Steps to Reproduce

1. Download the latest Marlin bugfix-2.0.x branch
2. hook up an Adafruit MAX31865 board to your MCU board
3. make the appropriate changes to your MCU board's PINS file to allow MAX31865 to work in Software SPI or Hardware SPI
4. in configuration.h:
 ```
#define TEMP_SENSOR_0 -5
#define MAX31865_SENSOR_OHMS_0      100
#define MAX31865_CALIBRATION_OHMS_0 430
```
5. in configuration_adv.h:
```
#define SHOW_TEMP_ADC_VALUES
#define AUTO_REPORT_TEMPERATURES

```

**Expected behavior:**

I would expect the count value being displayed for AUTO_REPORT_TEMPERATURES and SHOW_TEMP_ADC_VALUES would have some indication on the resistance value being seen by Marlin by the RTD temperature sensor

**Actual behavior:**

I am actually getting number that do not correlate easily with the Celsius temperature readings being displayed by AUTO_REPORT_TEMPERATURES.

### Related Issues

none

### CODE REVIEW

**Comment by GadgetAngel** [comment]
I do not understand why the checks are failing.  The messages are coming from warning and it is failing.  Can someone help me figure out why?

EDIT: All over a stupid IF statement!!

**Comment by zeleps** [comment]
Hi @GadgetAngel, do you mind taking a look at #21638? I really wonder how this issue does not affect you...

**Comment by GadgetAngel** [comment]
> Hi @GadgetAngel, do you mind taking a look at #21638? I really wonder how this issue does not affect you...

Yes, I will look into this .  Give me a week or two.  I am out of town right now and will be back in one week .

**Comment by zeleps** [comment]
> > Hi @GadgetAngel, do you mind taking a look at #21638? I really wonder how this issue does not affect you...
> 
> Yes, I will look into this . Give me a week or two. I am out of town right now and will be back in one week .

Thank you for your reply! whenever you can, there's no rush.

**Pull request merged**
