### PR TITLE
DWIN LCD pins for BTT SKR Mini E3

### PR DESCRIPTION
**Pull request by blazewicz**
This is a companion patch to following issue:

* https://github.com/MarlinFirmware/Configurations/issues/535

Inspired by:

* https://github.com/MarlinFirmware/Marlin/pull/22229

### CODE REVIEW

**Comment by ellensp** [comment]
You might want to consider add some ascii art of the wiring diagram, save having to go look for it

**Comment by blazewicz** [comment]
You're right, now it should also work with SKR Mini E3 V1.0 and V1.2.

**Comment by tome9111991** [comment]
You can add BTT_SKR_E3_TURBO for LCD serial port 1?
Would be nice :)

**Comment by thisiskeithb** [comment]
> You can add BTT_SKR_E3_TURBO for LCD serial port 1?
> Would be nice :)

Pins were added for this LCD/board combo in https://github.com/MarlinFirmware/Marlin/pull/22229, so that would make sense.

**Comment by hddvrn** [comment]
Hello! nowhere could I find information on how to make BT SCR Mini E3 V3 work with ender 3 v2.  You can help. I can't do it myself at all, I used a lot of options. Thank you very much.

**Comment by thisiskeithb** [comment]
@hddvrn 

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Pull request merged**
