### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by xuhan050**

### CODE REVIEW

**Comment by fiveangle** [comment]
This was surely a mistake, plus no submissions are accepted against the 1.1.x release branch (target bugfix1.1.x).  Please close ?

**Comment by xuhan050** [comment]
Dave Johnson <notifications@github.com>于2017年10月3日 周二下午10:29写道：

> This was surely a mistake, plus no submissions are accepted against the
> 1.1.x release branch (target bugfix1.1.x). Please close ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MarlinFirmware_Marlin_pull_7837-23issuecomment-2D334053639&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=YMdtX_bymsnhN9VDSniVZA&m=QpPOcMnU0MYHDX3qNR56UqUsxaCL9Y4HPf2A2kEJVlU&s=iZy1fX3iqYK0r8VhzJr5qAdO7f06sDcFqwvM0YpBj9M&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Abik5vTfEPsETC2xkb0978oUNbfC91Usks5soxeqgaJpZM4Ps6dt&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=YMdtX_bymsnhN9VDSniVZA&m=QpPOcMnU0MYHDX3qNR56UqUsxaCL9Y4HPf2A2kEJVlU&s=tAlDbKNn6L8msevNnMFvgoEg4dHNypxzn8Mpw1z0gPI&e=>
> .
>
I sorry. It is a mistake.
 First time to use it. Can you help me close it?

**Comment by fiveangle** [comment]
Click the "[view it on GitHub](https://github.com/MarlinFirmware/Marlin/pull/7837#issuecomment-334053892)" link, then click the "Close" button to close it.

**Comment by xuhan050** [comment]
Dave Johnson <notifications@github.com>于2017年10月3日 周二下午11:02写道：

> Click the "view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MarlinFirmware_Marlin_pull_7837-23issuecomment-2D334053892&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=YMdtX_bymsnhN9VDSniVZA&m=deKN9mPyms2cR6fsRQuhqC7FiOhStgsqEVBT5IueNQo&s=w5sFkJFbLya1nZRyylsa24feApRbhB6baQBQ3lne7xE&e=>"
> link, then click the "Close" button to close it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MarlinFirmware_Marlin_pull_7837-23issuecomment-2D334057927&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=YMdtX_bymsnhN9VDSniVZA&m=deKN9mPyms2cR6fsRQuhqC7FiOhStgsqEVBT5IueNQo&s=vNnE0KIYUBWl_84k8bhclMpHAwMcZiU9zZ63DOlZQVI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Abik5r4vXWBOSx2AfN4GYUFmRtBYE0Hqks5sox-2DKgaJpZM4Ps6dt&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=YMdtX_bymsnhN9VDSniVZA&m=deKN9mPyms2cR6fsRQuhqC7FiOhStgsqEVBT5IueNQo&s=-aIXRX0ndG9RkzIFIEyz8z88mlN_oOwhOz5UdDkrfQA&e=>
> .
>
It should be closed now. Thank you so much.

**Pull request closed without merging**
