### PR TITLE
CNC GCode dialect compatibility improvements

### PR DESCRIPTION
**Pull request by TheSFReader**
### Description
This PR provides additional parsing and gcode interpretation to Marlin, allowing it to better interpret "CNC like" GCODE dialect

it mainly improves on two points:
- Parenthese comments : Strings delineated by parentheses are interpreted as comments and ignored
- "Sticky move mode / modal move": when receiving a G0, G1 G2 G3 G5 or G38.x command, this move mode is cached and reused when receiving following "parameters only" commands

For now, I only modified a single configuration_adv file, but will update them all once we're agreed on the content/formatting

### Benefits

This increases Marlin's usability as a firmware to use with CNCs,drawing, or laser CAMs, which usually use a different dialect.  

### Related Issues

Answers to #11934 by allowing providing a feedrate alone

### CODE REVIEW

**Comment by thinkyhead** [comment]
Rebased, squashed, cleaned up, tweaked, corrected, and extended.

**Comment by AnHardt** [comment]
```
C:\Users\andre\AppData\Local\Temp\arduino_build_175272\sketch\src\gcode\motion\G80.cpp:30:6: error: 'GcodeSuite' has not been declared

 void GcodeSuite::G80() {

      ^

C:\Users\andre\AppData\Local\Temp\arduino_build_175272\sketch\src\gcode\motion\G80.cpp: In function 'void G80()':

C:\Users\andre\AppData\Local\Temp\arduino_build_175272\sketch\src\gcode\motion\G80.cpp:32:3: error: 'parser' was not declared in this scope

   parser.cancel_motion_mode();

   ^

exit status 1
```

**Comment by AnHardt** [comment]
How about 
```
#include "../gcode.h"
```
in `G80.cpp`?

I begin to hate this completely untested stuff.
If it does not compile - how can it be tested?

**Comment by TheSFReader** [comment]
Will correct and compile this evening, sorry about that.

**Comment by thinkyhead** [comment]
Patched!

**Comment by TheSFReader** [comment]
Tanks !

**Comment by AnHardt** [comment]
Patched but still not compiling. :-(

**Comment by thinkyhead** [comment]
Interesting! It's compiling for me and Travis CI (`STM32F1_tests`).

**Comment by AnHardt** [comment]
Downloaded bugfix-2.0.x right now.
Activated
```
#define PAREN_COMMENTS      // Support for parentheses-delimited comments
#define GCODE_MOTION_MODES  // Remember the motion mode (G0 G1 G2 G3 G5 G38.X) and apply for X Y Z E F, etc.
```
Arduino 1.8.7

```
C:\Users\ah\AppData\Local\Temp\arduino_build_435250\sketch\src\gcode\motion\G80.cpp:32:6: error: 'GcodeSuite' has not been declared

 void GcodeSuite::G80() {

      ^
```
This error makes perfectly sense to me.
Why it's not caught by travis is a mystery.

**Comment by thinkyhead** [comment]
Interesting! I wonder why this error didn't show up for me… I must have done something to work around it. Patched again!

**Comment by AnHardt** [comment]
Does compile now.

**Pull request merged**
