### PR TITLE
[1.1.x] add Calibrate Z (M915) to Prepare Menu

### PR DESCRIPTION
**Pull request by MikeLud**
If `TMC_Z_CALIBRATION` is enabled this will add Calibrate Z to the prepare menu #11331 counterpart

### CODE REVIEW

**Comment by bossman74** [comment]
I imagine this requires sensorless homing, but could this work if using only one TMC2130 to drive both Z axis steppers ?

**Comment by MikeLud** [comment]
@bossman74 
No it does not require sensorless homing. This will work with only one TMC2130 driving both Z axis steppers, that is how mine is setup see http://marlinfw.org/docs/gcode/M915.html for more details

**Comment by thinkyhead** [comment]
@MikeLud — Thanks! Can you make an equivalent PR for `bugfix-2.0.x` also?

**Comment by MikeLud** [comment]
@thinkyhead PR is done already and merged see PR #11331

**Comment by Flawl3ssSWE** [comment]
That would be nice!

**Comment by MikeLud** [comment]
@Flawl3ssSWE PR for bugfix-2.0.x is done already and merged see PR #11331

**Comment by Flawl3ssSWE** [comment]
Sorry for asking what is meant by PR have seen it a lot around here? Also, can the Marlin 2.0 still be used on 8-bit boards as the MKS GEN L series, Ramps etc?

**Comment by Sickeroni** [comment]
@Flawl3ssSWE 
"Pull Request"
if you Fork a Git-Repository, you can modify the code in your fork. if the changes should go back to the main-repository you create something like "hey i have changes, please add them". That is a pull request, because you request they pull your changes.

**Comment by Flawl3ssSWE** [comment]
ahh ok, thank you very much!

**Comment by MikeLud** [comment]
@Flawl3ssSWE  you can use Marlin 2.0 on 8 bit boards, I have the MKS GEN L with 2.0 loaded.

**Pull request merged**
