### PR TITLE
Code for slow down the frequency of PWM (to circa 0.125Hz) and minimum state times useful for heater drived by relay

### PR DESCRIPTION
**Pull request by DinoMesina**
Dear,
I have added some code in the "temperature.cpp" for have the possibility of control the time of the states with the heater drived by relays, with this feature now it is possible use PID function in conjunction with relay to control the temperature. I have made some tests and the temperature stay always in the range of +-1°C from the setted temp.
There is the possibility of turn on this features adding "#define SLOW_PWM_HEATERS" in Configuration.h

### CODE REVIEW

**Comment by alexborro** [comment]
Do you think if it is complicated to make this feature a little more configurable?
I mean, the user can choose the frequency?? It may be useful for folks using SSR on AC heater.

Cheers.

Alex.

**Comment by DinoMesina** [comment]
Hello, 
it is possible to vary the frequency of the PWM by changing the value 64, for example at 128 (about 0.06HZ) in the file temerature.cpp:
   // Increment slow_pwm_count only every 64 pwm_count about 65.5ms
   if ((pwm_count% 64) == 0) {
     slow_pwm_count ++;

While it is possible to vary the minimum state time of ON or OFF varying MIN_STATE_TIME
in temperature.cpp:
"#define MIN_STATE_TIME 16 // MIN_STATE_TIME * 65.5 = time in milliseconds"

But I think that it is can go well for all.

With SSR on AC in a second how much it increases the temperature?

**Comment by boelle** [comment]
could you send this one to the dev branch?

**Comment by DinoMesina** [comment]
If you please explain to me how do I do it willingly, I do not know how.

**Comment by boelle** [comment]
fork the dev branch and make the changes and then submit a pull request... 

the other request you made is ok


you might need to delete the fork you allready have

**Pull request closed without merging**
