### PR TITLE
IDEX clean up

### PR DESCRIPTION
**Pull request by Roxy-3D**
First set of changes to clean up IDEX code....

All tested...    All working...

### CODE REVIEW

**Comment by Roxy-3D** [comment]
This compiles clean with Arduino.    But for some reason, Travis is having issues.

**Comment by thinkyhead** [comment]
Did you try building for DELTA?

**Comment by Roxy-3D** [comment]
Oh!   Is that all that is wrong?   OK!   I'll get that fixed...

**Comment by Roxy-3D** [comment]
I think there is a problem with Teensy and LPC1768.     The LPC1768 case is particularly strange.   It has something to do with delay() ????

**Comment by Roxy-3D** [comment]
@thinkyhead   The Teensy change fixed that part of the Travis test.   But the LPC1768 is still sick.

**Comment by Roxy-3D** [comment]
THANK YOU!!!!!

**Pull request merged**
