### PR TITLE
Creality cr-2020 board support

### PR DESCRIPTION
**Pull request by sandro197802**
### Requirements

creality cr-2020 motherboard support in bugfix 2.0.x

I don't see anything about cr-2020 in Marlin supported  boards, is it possible to support it?

### CODE REVIEW

**Comment by GMagician** [comment]
I think this is not a pull request. Close it and post as new issue with title starting with [FR]

**Comment by sandro197802** [comment]
Thanks for your answer.
I really don't know how to do that, can you do it for me?
Or explain me how to (anche in italiano ☺️)

**Comment by GMagician** [comment]
Since this is a global repository, in respect of other, English is better.

First you have to press close button at bottom of this page.
Second, open Marlin github web page (not your cloned one), select "issues" tab and "new issue" button

**Comment by sandro197802** [comment]
I did it. Thanks for your support and patience.

**Pull request closed without merging**
