### PR TITLE
👷 Local URL checking script

### PR DESCRIPTION
**Pull request by thinkyhead**
~~Add an automated URL checker to run once per week. Subscribe to the action to get notifications.~~

A script to check URLs in the project. Run periodically to check for broken links. If the script can be made more reliable and to better understand the common use of redirects it might be possible to make into an action to run periodically. So far I have not been able to get it to add comments to this issue from the action, which would be one way to be able to get a notification. That problem seems to be permissions-related.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> Subscribe to the action to get notifications.

As far as I can tell, there's no way to subscribe to an Action:

image

---

How do you view the URL(s) that failed? I can only see successful ones with `[ OK ]` in the log and then the failed message with no prior URL:

image

**Comment by sjasonsmith** [comment]
@thisiskeithb error show up in there, but they are hard to spot. It would be nice if they were captured in a list and summarized at the end.

image

**Comment by thisiskeithb** [comment]
> error show up in there, but they are hard to spot. It would be nice if they were captured in a list and summarized at the end.

Ah, I misunderstood the script and assumed it'd stop after finding a bad URL.

---

As for "subscribing" to an Action per the [Notifications for workflow runs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs) page:
> Notifications for scheduled workflows are sent to the user who initially created the workflow. If a different user updates the cron syntax in the workflow file, subsequent notifications will be sent to that user instead. 

This will be a thinkyhead-only notification, so it might be better to bump the timeline out to once a month and someone on the team can manually check the logs each time it runs so the workload is spread out.

…or have the script create a new Issue with a list of bad URLs?

Automate all the things!

**Comment by thinkyhead** [comment]
One "weird" way to get a notification would be to have the action add a comment to an existing issue, then anyone could subscribe to the issue. Might be worth exploring. I'll see if it can add a comment to this issue, for a start.

**Comment by thinkyhead** [comment]
Testing gh from command line

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:\nhttps://www.st.com/en/microcontrollers-microprocessors/stm32f103.html
https://www.nosuchdomain-really.com
https://www.thinkyhead.com
https://marlinfw.org/no-such-page

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- http://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- http://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- http://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- http://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- http://marlinfw.org/

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- http://marlinfw.org/

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- http://marlinfw.org/

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- https://marlinfw.org/
- http://marlinfw.org/

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- http://marlinfw.org/

**Comment by thinkyhead** [comment]
URL Checker reports one or more URLs could not be reached:
- http://marlinfw.org/
- https://marlinfw.org/no-such-page
- https://www.thinkyhead.com
- http://www.thinkyhead.com
- https://www.nosuchdomain-really.com

**Pull request merged**
