### PR TITLE
[2.0.x] Correct step pulse width on LPC1768, DUE & Teensy35_36

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
The step pulse widths are longer than expected for the LPC1768, DUE & Teensy35_36.  This is because the **STEPPER_TIMER_PRESCALE** macro was wrong.

----

Here are the before and after numbers for LPC1768 & DUE
```
All numbers are in microseconds
MINIMUM_STEPPER_PULSE is the setting in Configuration_adv.h
        MINIMUM_STEPPER_PULSE  0    1    2    3    4    8
LPC1768 previous               0.6  6.1  9.5  13.0 18.5
        corrected              0.6  1.1  2.1  3.1  4.0  8.2
DUE     previous               1.1  6.0  6.0  8.6  11.3 18.6
        corrected              1.1  1.4  2.0  3.1  4.0  7.8
```

----

We may want to drop the Teeny35_36 change because I don't have one to verify against.

If I read the code correctly the Teeny35_36 step pulse is infinite.  I have a hard time believing that so I expect someone will step up with a different explanation.

The current macros end up with **PULSE_TIMER_PRESCALE** being zero because of the following defines:
```
#define STEPPER_TIMER_PRESCALE   0 // Not defined anywhere else!
#define PULSE_TIMER_PRESCALE    STEPPER_TIMER_PRESCALE
```

The following defines the width of the X, Y & Z step pulses.  Since PULSE_TIMER_PRESCALE is zero the while loop will never terminate.
`while (EXTRA_CYCLES_XYZE > (uint32_t)(HAL_timer_get_count(PULSE_TIMER_NUM) - pulse_start) * (PULSE_TIMER_PRESCALE)) { /* nada */ }`

### CODE REVIEW

**Comment by thinkyhead** [comment]
One can only laugh, madly, like The Joker, when such fun bugs are found … and fixed.

**Comment by thinkyhead** [comment]
@Bob-the-Kuhn — Something about this has broken babystepping for LPC and maybe others. According to comments at #10731 setting `STEPPER_TIMER_PRESCALE` back to 1.0 restores the functionality of babystepping. But obviously, we don't want to just revert this if we just need to make it more accurate.

If I rearrange and calculate out the defines in `HAL_LPC1768/HAL_timers.h` we get the following numbers:
```cpp
#define HAL_TIMER_RATE         ((SystemCoreClock) / 4)  // (25 million)
#define HAL_STEPPER_TIMER_RATE HAL_TIMER_RATE   // (25 million)
#define HAL_TICKS_PER_US       ((HAL_STEPPER_TIMER_RATE) / 1000000) // (25)
#define STEPPER_TIMER_PRESCALE (CYCLES_PER_MICROSECOND / HAL_TICKS_PER_US) // (4)
```

Babystepping calculates the pulse delay using `PULSE_TIMER_PRESCALE`, so the problem must be caused by `STEPPER_TIMER_PRESCALE` evaluating to 4. The value of `PULSE_TIMER_PRESCALE` is set to the value of `STEPPER_TIMER_PRESCALE`. And then the logic for babystepping is…

```cpp
#define EXTRA_CYCLES_BABYSTEP (STEP_PULSE_CYCLES - (CYCLES_EATEN_BABYSTEP))
#define _SAVE_START const hal_timer_t pulse_start = HAL_timer_get_count(STEP_TIMER_NUM)
#define _PULSE_WAIT while (\
  EXTRA_CYCLES_BABYSTEP
  > (uint32_t)(HAL_timer_get_count(STEP_TIMER_NUM) - pulse_start) * (PULSE_TIMER_PRESCALE) \
) { /* nada */ }
```

We need to double-check these values (maybe the babystep pulse delay logic) to make sure everything adds up correctly. With the settings above, the value of `STEP_PULSE_CYCLES` should be 200 for the SBASE with the `MINIMUM_STEPPER_PULSE` set to 2 (for DRV8825), and then `EXTRA_CYCLES_BABYSTEP` should also end up 200. Since `PULSE_TIMER_PRESCALE` is 4 and the stepper timer is _supposedly_ running at 25MHz, the delay ought to add up to 200 cycles, or 2µs. But apparently not…?!

The fact that setting `STEPPER_TIMER_PRESCALE` to 1.0 causes babystepping to work makes sense, since the logic changes from `while (200 > T * 4)` to `while (200 > T)`, giving a 4 times longer pulse duration. But note that the person reporting the issue has tried setting `MINIMUM_STEPPER_PULSE` as high as 8 and it still didn't work.

I can only surmise from all this that we have the rate of the timer wrong — that it's actually running faster than `SystemCoreClock / 4`. Or, maybe there's just something wrong with the babystep pulse delay logic.

**Comment by Bob-the-Kuhn** [comment]
OK - I'll look into it.

I've never used babystepping.  I expect it'll be 1-2 days before I can setup the logic analyzer, verify the timer rate, learn about the babystepping system & test changes.

**Comment by thinkyhead** [comment]
As this is 2.0 stuff, I'm not going to lose too much sleep over it. I'm sure we'll work out the details in plenty of time for the release.

**Pull request merged**
