### PR TITLE
[1.1.x] Move BABYSTEP_ZPROBE_GFX_OVERLAY out of HAS_TEMP_BED section

### PR DESCRIPTION
**Pull request by tcm0116**
[Concise Diff](8447/files?w=1)

The bitmaps defined for `BABYSTEP_ZPROBE_GFX_OVERLAY` are currently in the `HAS_TEMP_BED` section, which prevents compilation with on systems without a heated bed.

Note that this issue is not present in bugfix-2.0.x because it appears to have been addressed in #8038 (which has not yet been ported back to 1.1.x).

### CODE REVIEW

**Comment by thinkyhead** [comment]
I don't know how it's possible that #8038 didn't get ported to the 1.1.x branch. Everyone here knows that we don't merge a pull request for one branch until there exist PRs for both branches. I will put together the necessary PR now.

**Comment by Roxy-3D** [comment]
> I don't know how it's possible that #8038 didn't get ported to the 1.1.x branch. Everyone here knows that we don't merge a pull request for one branch until there exist PRs for both branches. I will put together the necessary PR now.

Yes.  Now we know that.   But at the time this got merged it wasn't clear.   It was more like new stuff we put in bugfix_v2.0.0 and when that is ready to go live there will be one more merge between the branches to get everything right.

**Comment by cdedwards** [comment]
it might also help if there was a guide to using github desktop and github to submit PR's properly as well as keeping local configuration.h options available to those of us not in the know.

**Comment by thinkyhead** [comment]
> here will be one more merge between the branches to get everything right.

That would be cool. But we can't do that . We must do these manually if we want them in both branches. Hence the reason I am so anxious to kill the 1.1.x branches asap. Doing everything twice takes twice as long.

**Comment by thinkyhead** [comment]
> it might also help if there was a guide

Github itself provides excellent documentation on this. If you're looking for deeper insights, I will be doing a livestream soon demonstrating my personal use of Github and how I manage to get 5x as much done by using scripts from the command-line — only using Github Desktop for very basic things, which is all Github Desktop does anyway.

I posted a recent livestream at https://www.youtube.com/watch?v=mywFNCBzwEg if you'd like to see some of this in action within a recent bug-fix session.

**Comment by tcm0116** [comment]
@thinkyhead Something odd is going on. This change shows as having been merged into bugfix-1.1.x, but it's not there. Any idea what could have happened?

**Comment by thinkyhead** [comment]
@tcm0116 I believe everything is now resolved, as I decided to catch this feature up earlier today.

**Comment by tcm0116** [comment]
@thinkyhead Nope. The `BABYSTEP_ZPROBE_GFX_OVERLAY` and `MESH_EDIT_GFX_OVERLAY` section is still within the `HAS_TEMP_BED` section in the current bugfix-1.1.x branch.

For whatever reason, the commit attached to this PR wasn't actually merged, even though GitHub says that it was.

**Comment by Roxy-3D** [comment]
That same thing is happening with:  https://github.com/MarlinFirmware/MarlinDocumentation/pull/106

This was merged.   But it doesn't show up.

**Comment by thinkyhead** [comment]
I've recovered MarlinFirmware/MarlinDocumentation#106. I must've run a publish right around the same moment as the branch was merged, because my script pulls down the latest changes just before publishing, but the publish itself takes a few minutes to finish.

To recover the PR it I just merged in the commits from the PR and ran publish again.

**Comment by tcm0116** [comment]
That did the trick. Thanks!

**Comment by thinkyhead** [comment]
> For whatever reason, the commit attached to this PR wasn't actually merged, even though GitHub says that it was.

When pushing single changes from local branches, to avoid breaking other changes we're supposed to use `git push upstream HEAD:bugfix-1.1.x` —**instead of `git push -f`**— but sometimes a `git push -f` gets through by mistake. The commit from this PR may have gotten pruned by one of those.

Even a `git push -f` can be okay as long as it's preceded by `git fetch upstream; git rebase upstream/bugfix-1.1.x` to fast-forward to the end.

We're probably going to keep making some direct commits to fix small issues. We'll just have to be extra careful to always use `git push`.

**Comment by tcm0116** [comment]
Since I can't write directly to Marlin's branches, I'll leave those details
up to you :-)

**Comment by thinkyhead** [comment]
Indeed! If anything should get lost again, poke me with a pointy stick. All that's needed to recover any PR is the last commit ID.

**Pull request merged**
