### PR TITLE
Fix LEVEL_CORNERS_USE_PROBE with BLTOUCH_HS_MODE

### PR DESCRIPTION
**Pull request by qwewer0**
### Description

Changes for `LEVEL_BED_CORNERS`, `LEVEL_CORNERS_USE_PROBE` to work with `BLTOUCH_HS_MODE`.

### Requirements

- `LEVEL_CORNERS_USE_PROBE`
- `BLTOUCH_HS_MODE`

### Benefits

`LEVEL_CORNERS_USE_PROBE` now works with `BLTOUCH_HS_MODE` enabled.

### Configurations

Default.

### Related Issues

Fixes https://github.com/MarlinFirmware/Marlin/issues/21084

### CODE REVIEW

**Comment by warewolf** [comment]
This works for me, thank you!

**Comment by qwewer0** [comment]
> This works for me, thank you!

Does `LEVEL_CORNERS_USE_PROBE` works with `BLTOUCH_HS_MODE` just as without `BLTOUCH_HS_MODE`?

**Comment by warewolf** [comment]
Yep, I never ran my printer in normal-speed bltouch mode before, so level corners never worked before.  Just build and reflashed a normal-speed firmware and it works exactly the same.

**Comment by qwewer0** [comment]
> Yep, I never ran my printer in normal-speed bltouch mode before, so level corners never worked before. Just build and reflashed a normal-speed firmware and it works exactly the same.

Thanks for the feedback.

**Comment by galluccib** [comment]
Think mine might have been something else... I went back to 2/11 compiled and been running fine since..  On 2/11 BLTOUCH_HS_MODE is enabled..

**Comment by qwewer0** [comment]
> Think mine might have been something else... I went back to 2/11 compiled and been running fine since.. On 2/11 BLTOUCH_HS_MODE is enabled..

@galluccib Could you share the commit link that you used and is working with `BLTOUCH_HS_MODE`?

**Comment by ils15** [comment]
Worked here
thanks

**Comment by thinkyhead** [comment]
Guidance on `BLTOUCH_HS_MODE` is that it should only be enabled when it works properly, otherwise it should be turned off. Is there some way that we can adjust the behavior of the corner leveling so that it only stows when necessary (i.e., after the last probe move in the multi-probe of the corner) so that it gets the change in behavior intended from `BLTOUCH_HS_MODE`?

**Comment by qwewer0** [comment]
> Guidance on `BLTOUCH_HS_MODE` is that it should only be enabled when it works properly, otherwise it should be turned off. Is there some way that we can adjust the behavior of the corner leveling so that it only stows when necessary (i.e., after the last probe move in the multi-probe of the corner) so that it gets the change in behavior intended from `BLTOUCH_HS_MODE`?

I will try some stuff out, but can't promise anything.

**Comment by qwewer0** [comment]
Added a deploy at the beginning, and z clearance, stow at the end for BLTOUCH_HS_MODE.

Not sure if this is how it should be done, but it should work. (By my test, it worked)

**Comment by thinkyhead** [comment]
This seems clean and minimal, and it makes sense comparing to other probing procedures. The only other worry is that the deployed pin might be so low that it could hit obstacles, so when doing travel moves in XY with `BLTOUCH_HS_MODE` the Z height should be increased by 7mm.

**Comment by qwewer0** [comment]
> This seems clean and minimal, and it makes sense comparing to other probing procedures. The only other worry is that the deployed pin might be so low that it could hit obstacles, so when doing travel moves in XY with `BLTOUCH_HS_MODE` the Z height should be increased by 7mm.

You are right, I totally forgot about that. Thanks.

**Comment by thinkyhead** [comment]
We'll soon encapsulate these common HS mode behaviors into something that these routines can share, probably as extra helper or accessor methods in the BLTouch class.

**Comment by Guilouz** [comment]
@qwewer0 When BLTOUCH_HS_MODE enabled, the Last Z value always return 0 on the screen, no problem when disabled.

**Comment by qwewer0** [comment]
> @qwewer0 When BLTOUCH_HS_MODE enabled, the Last Z value always return 0 on the screen, no problem when disabled.

@Guilouz  Doesn't happen to me, so you might want to open an issue for that.

**Pull request merged**
