### PR TITLE
Specific character LCD libraries

### PR DESCRIPTION
**Pull request by thinkyhead**
Set flags more specifically to prevent unnecessary download / compile of LCD libraries.

### CODE REVIEW

**Comment by rhapsodyv** [comment]
I think now you may be able to remove the LiquidTWI2 from some lib_ignore

**Comment by thinkyhead** [comment]
When `lib_deps` contains more than one entry of the same name, the last one is the one that matters, correct? If that is the case then some `lib_deps` can also be cleaned up.

**Comment by rhapsodyv** [comment]
> When `lib_deps` contains more than one entry of the same name, the last one is the one that matters, correct? If that is the case then some `lib_deps` can also be cleaned up.

I tested this:
```
TFT_LVGL_UI         = MKS-LittlevGL=https://github.com/makerbase-mks/MKS-LittlevGL/archive/master.zip
                                  MKS-LittlevGL=https://github.com/lvgl/lvgl/archive/master.zip
```
PlatformIO will use last... But if the two versions are downloaded (one before, on later), the will use both!! ... :-/ 

Then yes, looks like it just use the last one (for the propose of your change).

**Comment by thinkyhead** [comment]
> But if the two versions are downloaded (one before, on later), [they] will use both

That's interesting. I will have to do some tests to see what's up with that. I would expect a `lib_deps` entry with the same name to completely hide the pre-existing one.

**Comment by rhapsodyv** [comment]
LDF try to infer the libs we need... It may go a bit crazy:

Installing the two versions, it created two folder for LVGL:
```
Adafruit MAX31865 library_ID1253                   U8glib-HAL_ID1932
Adafruit NeoPixel_ID28                             SailfishLCD
Arduino-L6470_ID2404                               SlowSoftI2CMaster_ID7005
LiquidCrystal_ID136                                TMC26XStepper
LiquidTWI2_ID6063                                  TMCStepper_ID5513
MKS-LittlevGL                                      
MKS-LittlevGL@src-440e6ca91917e8f98ddc4c601ee7472e
```

And it added the two deps! Its even think one lvgl depends on other :-p
```
Dependency Graph
|-- <lvgl> 7.1.0
|   |-- <lvgl> 6.1.1
|-- <U8glib-HAL> 0.4.1
|   |-- <Wire> 1.0
|   |-- <SPI> 1.0
|-- <Wire> 1.0
|-- <SlowSoftI2CMaster> 1.0.0
|-- <Adafruit NeoPixel> 1.5.0
|-- <TMCStepper> 0.7.1
|   |-- <SPI> 1.0
|   |-- <SoftwareSerial> 1.0
|-- <LiquidCrystal> 1.5.0
|   |-- <Wire> 1.0
|-- <LiquidTWI2> 1.2.7
|   |-- <Wire> 1.0
|-- <SailfishLCD>
|-- <SPI> 1.0
|-- <lvgl> 6.1.1
|-- <Arduino-L6470> 0.8.0
|-- <TMC26XStepper>
|   |-- <SPI> 1.0
|-- <Adafruit MAX31865 library> 1.1.0
|   |-- <SPI> 1.0
|-- <EEPROM> 2.0
|-- <SoftwareSerial> 1.0
```

I hope this PR solve a few problems of forgotten libs in .pio/lib_deps: #18728

**Comment by thinkyhead** [comment]
> And it added the two deps! Its even think one lvgl depends on other :-p

Yes, it's important to remember that `lib_ignore` can refer to sub-dependencies. In some cases these dependencies are not really absolute dependencies, but just libraries that an external library _might_ use.

**Comment by rhapsodyv** [comment]
WOW, using regex to match the features will make it very powerful and versatile!! :clap: :muscle: :beers:

**Pull request merged**
