### PR TITLE
[2.0.x] delta height follows z offset change

### PR DESCRIPTION
**Pull request by LVD-AC**

### CODE REVIEW

**Comment by LVD-AC** [comment]
I think this could end this endless discussion whether or not M851 should automatically change the `delta_height` accordingly.

If you find such behavior 'confusing' or unwanted comment
`#define DELTA_HEIGHT_FOLLOWS_Z_OFFSET_CHANGE`
in Configuration.h; and if you find such behavior 'handy' and want this uncommand that statement

Adjusting `delta_height` has been working flawless from RC7 up to 1.1.6 without generating one single issue, so I've put it uncommented as default in the exemple configs; that way nothing changes to the user unless they comment this new `DELTA_HEIGHT_FOLLOWS_Z_OFFSET_CHANGE`. That avoids dozens of calibration guides, wikis, blogs, videos,.. that are all over the net to be rewritten.

The right spot is to put this in is `recalc_delta_settings` since this applies to all delta users, not only those who calibrate with G33.

So @thinkyhead can turn this feature off on his delta printer (sic) because it's to confusing and @LVD-AC can turn it on his delta printer because it makes life so much easier; everybody happy.

**Comment by thinkyhead** [comment]
This is not acceptable as an optional feature either. We must not tie `delta_height` or any other previously-measured or set value to changes in `zprobe_zoffset`.

The probe offset is meant to be set before you use your probe, and will apply to all subsequent probing operations. And modifying `zprobe_zoffset` must not affect any value except `zprobe_zoffset` alone.

That's the specification for Marlin 1.1.7 and all future versions of Marlin until further notice.

To change `delta_height`, we have `M665 H` and the Delta Calibration LCD menu.

**Comment by LVD-AC** [comment]
> The probe offset is meant to be set before you use your probe...

...and how exactly do you do that on an uncalibrated delta printer?

**Comment by thinkyhead** [comment]
> ...and how exactly do you do that on an uncalibrated delta printer?

How do people calibrate their probe offsets on Cartesians? How did we accomplish this before `G33` came along? These are not the greatest mysteries.

Maybe `G33` can provide an option to acquire the probe offset. First it goes down to the bed with the probe until it triggers. Then you adjust Z with the knob or with G1 until you have your nozzle tip at "zero" and click to confirm. Now we know both the delta height and the probe offset.

That would beat the Cartesians in the arms race. They don't have this feature yet either.

----
All I'm saying is that we need a more comprehensive solution: a feature that is more specifically about adjusting everything together, whether it ties in with `M851` or not. At the moment, we aren't able to use modifications of `zprobe_zoffset` to retroactively adjust the mesh in SRAM, let alone UBL meshes stored in multiple slots in the EEPROM.

It would be very convenient to have a feature that "repairs" all previous measurements when you change the Probe Z Offset. But this must be (1) obvious to the user and (2) truly apply to all previous values, including (I would assert) the meshes stored in EEPROM.

The most complicating factor was the introduction of `BABYSTEP_Z_OFFSET` because it moves the Z axis at the same time as it modifies `zprobe_zoffset`. I like the general idea and had tried to have it modify the mesh data at the same time. But it's impossible to accomplish with the way meshes are currently stored (i.e., `probed_z - zprobe_zoffset`). If we want to have this capability, we need to include `zprobe_zoffset` in the mesh data, subtracting it upon use, and this means slightly more overhead for each leveled point.

Here's the scenario that leads to this requirement…
- Babystepping Z+2mm will subtract 2 from `zprobe_zoffset`
- Since the probe offset changed, to "repair" the mesh data apply Z-2 to each point.
- Oops! Since the Z axis was moved this causes a doubling of the Z offset.
  - Bad solution: Add 2 to `current_position[Z_AXIS]` too, canceling out the mesh change.
    It's bad because babystepping should never change the `current_position`.
    (But, it also makes bizarro sense because Z _might_ have been homed with the probe.)

With the probe offset included in the mesh data…
- Babystepping Z+2mm subtracts 2 from `zprobe_zoffset`
- The probe offset changed, so "repair" the mesh data (Z-2 each point).
- No problem! We're subtracting `zprobe_zoffset` during leveling so the mesh still applies.

Similar fixes would be needed for 3-point and "planar grid" leveling.

Since the current focus is on fixing existing stability issues and producing a 1.1.7 release, that work is being held off (along with any other features that muddy the water), and we are simply reverting to pre-1.1.6 behavior.

**Comment by LVD-AC** [comment]
Fine that you revert to pre-1.1.6 because G29 has been running into trouble; but that one statement `delta_height -= diff`; is pre-G33 and thus pre-RC8. At the time I did not encapsulated it with #define ENABLED(DELTA_AUTO_CALIBRATE) but with #define ENABLED(DELTA) since IMO it is useful to all delta printers no matter how they are calibrated. But what the heck. If only you would allow that one statement to be put back... inside G33 if you which. Because deliberately crippling G33 to a state it never has been in because the Cartesian G29 has troubles is beyond me. That is NOT reverting things to a previous stable state, but creating new unstableness that never existed before.

#8602 and #8603; and then I give up trying to do maintenance here on G33 and trying to keep it's functionality.

delta_height is only changed when the user invokes G33, and as such **wants** and **chooses** to recalibrate the delta settings. But I guess the answer will be that a user wanting to set his delta_height correctly with an auto-calibration routine is **unacceptable** and he should do this manually with M665 H.

**Comment by tcm0116** [comment]
>Since the probe offset changed, to "repair" the mesh data apply Z-2 to each point.

I'm wondering if this is what's causing some confusion here. If the Z offset changes, there is no need to modify the mesh data. Here's an example. Suppose the probe triggers when the nozzle is 2mm above the bed. If you have a Z offset of 0 and build the mesh, then the resulting mesh will cause the nozzle to be 2mm above the bed, but all of the mesh values will be around 0. If you then start a print and adjust the Z offset to the correct -2mm, then the nozzle will be moved down to the bed via babystepping. On a cartesian machine that homes with the probe, the next homing event of the Z axis will incorporate the new Z offset of -2, causing the nozzle to be on the bed at Z=0. If the leveling is then enabled, the nozzle will remain on the bed because the mesh data is centered around 0. 

The problem lies with systems that don't home with the probe. If babystepping is enabled, then the example above would be the same up to when the printer is re-homed. Because the Z offset is not part of the homing process, the change to the Z offset won't be incorporated into the newly homed position. This leads to an inconsistency because now the Z offset is -2, but the nozzle is 2mm above the bed at Z=0 with leveling enabled. 

This is where this PR an my suggestion in #9027 come into play for delta machines. By giving the option to adjust the delta height in conjunction with the z offset, the change to z offset can now be persisted. This especially makes sense if G33 was use to measure the delta height. 

However, this solution only apples to delta machines and not other machine types that use the probe for leveling but not for homing. I assume the only mechanism for correcting the un-leveled nozzle height is via the home offset, but I don't think there's a way to measure the home offset using the probe in a similar manner to measuring the delta height with G33. 

At the very least, `BABYSTEP_Z_OFFSET` needs to be prohibited on machines that don't use the probe for homing due to the inconsistency pointed out above, at least until some other solution is provided.

**Comment by LVD-AC** [comment]
On a Delta **with bed-levelling disabled**: M851 does nothing at all; the LCD menu to change the z_offset does noting at all; z-offset baby-stepping : you can put an electric drill on the dial so you can go from zero to one hundred in two seconds flat, but the nozzle does not move a micron. The only solution seems to be re-calibrating the printer **after each print** - but beware not to put G28 in your end-code to move the nozzle away because homing will dump your changes. At least G33 is proving to be very useful since 1.1.7. Before 1.1.7 when you re-calibrated with G33, re-running a full calibration did stop after 1 iteration, 2 tops; now it iterates 3 to 5 times each time. The code of the G33 routine didn't change???

All of this is related; but #9027 nor this PR do solve these problems when **bed-levelling is disabled**.

**Comment by thinkyhead** [comment]
> Fine that you revert to pre-1.1.6 because G29 has been running into trouble

There may yet be some issues to solve. No need for the nuclear option. We're clever.

>  I guess the answer will be that a user wanting to set his delta_height correctly with an auto-calibration routine is unacceptable
> `delta_height` is only changed when the user invokes `G33`, and as such wants and chooses to recalibrate the delta settings

I've been very clear that I don't have a problem with that. It's the subsequent modification of `delta_height` via `M851 Z` that needs more consideration. I've given a very detailed description of a methodology I would happily accept.

> #8602 and #8603; and then I give up trying to do maintenance here on G33 and trying to keep its functionality.

I'm rolling my eyes and sighing loudly because heck, I've just been too busy chasing bugs and dealing with other things to get deep into these tricky questions. Let's see if we can find some reasonable compromise that fulfills all our needs.

**Comment by thinkyhead** [comment]
> If the Z offset changes, there is no need to modify the mesh data.

Well, we had a request to do so, as a point of completeness around editing the probe z offset. This was an idea proposed by Roxy that seemed reasonable at first. So I implemented it, and then I realized the incompatibility with babystepping the Z probe offset (affecting both delta and cartesian).

So, I reverted that change, and now the mesh just stays unchanged. I realized that saving the mesh data in terms of nozzle position (not subtracting the probe offset) like it used to do would be one way to be able to recover this ability.

At the same time I put a temporary embargo on any retroactive mods in response to `M851`. Some developers would prefer everything **_now_**, but I'm playing it conservatively while investigating leveling and acceleration/jerk issue reports.

We'll figure it out, so let's try to be patient and not get antagonizing. Hotheads 😡 get banned.

**Comment by thinkyhead** [comment]
> On a Delta with bed-levelling disabled: M851 does nothing at all;
>  the LCD menu to change the z_offset does noting at all;

They both change the value of the `zprobe_zoffset` variable. That's all they are meant to do.

> z-offset baby-stepping : you can put an electric drill on the dial so you can go from zero to one hundred in two seconds flat, but the nozzle does not move a micron.

Is this a bug report that Z babystepping is broken?

> The only solution seems to be re-calibrating the printer **after each print**

A printer that needs recalibration that often has mechanical problems.

> but beware not to put G28 in your end-code to move the nozzle away because homing will dump your changes.

Correct. The proper way to do a move away is with a Pause (M25 or M125) or with a G1.

> At least G33 is proving to be very useful since 1.1.7.
> Before 1.1.7 when you re-calibrated with G33, re-running a full calibration did stop after 1 iteration, 2 tops; now it iterates 3 to 5 times each time. The code of the G33 routine didn't change???

_Something_ must have changed.

**Comment by thinkyhead** [comment]
> a user wanting to set his delta_height correctly with an auto-calibration routine is unacceptable and he should do this manually with M665 H

> deliberately crippling G33 to a state it never has been in because the Cartesian G29 has troubles is beyond me.

If you mischaracterize things or oversimplify they _can_ tend to look bizarre. What you call "crippling G33" I call "maintaining an embargo on certain changes until this 'probe offset retroactively modifying things' concept can be given the broader attention it deserves."

You have the `G33` you want on your own machine. Enjoy it, take a break if you're getting stressed out, and let us figure out how best to integrate such things in our own time. This occasionally happens, and some developers can handle it, and others want to take their ball and go home. Which way you want to go is totally up to you.

**Comment by tcm0116** [comment]
>I realized that saving the mesh data in terms of nozzle position (not subtracting the probe offset) like it used to do would be one way to be able to recover this ability.

The mesh is saved in terms of the nozzle position because the probe offset is subtracted. For example, with a probe offset of -2mm, the probe will trigger when the nozzle at 2mm, but `probe_pt` will subtract `zprobe_zoffset` (`measured_z = run_z_probe() + zprobe_zoffset`), resulting in a value of 0, which is where we want the nozzle to be at Z=0. 

Perhaps I'm misunderstanding what your mean, and you're referring to the 'nozzle position' as the position of the nozzle when the probe triggers. In any case, I think the current way of storing the mesh in terms of where the nozzle should be in Z at the given X,Y position makes the most sense. 

>Some developers would prefer everything now, but I'm playing it conservatively while investigating leveling and acceleration/jerk issue reports.

I'm more than happy to help on this front. Let me know if there's anything you'd like me to look into.

**Comment by thinkyhead** [comment]
> The mesh is saved in terms of the nozzle position because the probe offset is subtracted.

It is saved in terms of the **_probe's position at the time of probing**_.

**Comment by thinkyhead** [comment]
> The mesh is saved in terms of the nozzle position because the probe offset is subtracted.

It is saved in terms of the **probe's position _at the time of probing_**.

> you're referring to the 'nozzle position' as the position of the nozzle when the probe triggers. 

Correct! We're only talking about the period of probing and the mesh storage.

**Comment by thinkyhead** [comment]
> anything you'd like me to look into.

I'd like to understand why so many principal developers are here in Texas!

**Comment by tcm0116** [comment]
>I'd like to understand why so many principle developers are here in Texas!

Because it's the best state! If you're ever up in DFW, let me know.

**Comment by Roxy-3D** [comment]
>> If the Z offset changes, there is no need to modify the mesh data.

> Well, we had a request to do so, as a point of completeness around editing the probe z offset. This was an idea proposed by Roxy that seemed reasonable at first. 

None of this stuff is easy and obvious.   It is best we discuss ideas and try to get consensus first.   And even with that...  There is some chance that problems show up.     Even the best ideas have some chance of causing other problems.

I don't feel any regrets suggesting that altering the definition of what mesh points represents is potentially problematic.   I can't state what problems it will cause.   But the bed leveling code is complicated enough I want to move slowly and carefully.    I'm almost 100% certain it is going to break the UBL G29 J mesh tilting.    It is going to take time to rewrite (and TEST!!!!) that code.   So let's make sure there is consensus that this approach is the right direction to go.    

Let's take a step back and realize everybody contributing to Marlin wants the same thing.  We want the code base to handle more while at the same time wanting it to stay clean and allow the addition of more functionality.    There is no harm discussing things for a few days prior to merging changes.

**Comment by thinkyhead** [comment]
> If you're ever up in DFW, let me know.

Will do!

> There is no harm discussing things for a few days prior to merging changes.

Indeed. And sometimes it's only a matter of making the change better _understood_. My initial response with any major change is to be guarded, especially at this time when we want 1.1.9 to be basically a bugfix release to 1.1.8. I'm all for revamps, revolutions, and radical overhauls, but the cutoff for that with 1.1.x is nigh. Let's get all the simple patches that make `G33` stable in basic usage merged. And let's reserve the more creative changes for 2.0.x.

**Pull request closed without merging**
