### PR TITLE
Configurator utility

### PR DESCRIPTION
**Pull request by thinkyhead**
- 100% browser-based Javascript application, requires no back-end
- Provides a dynamic form with fields for configuration values
- Modifies configuration files in-place highlighting changes
- Reads and parses the Configuration.h (etc.) files directly from Github
- Modifies configurations dynamically in-place, with visual confirmation
- Provides download links, dynamically created via Javascript
- Demo work-in-progress posted at http://www.thinkyhead.com/_marlin/

### CODE REVIEW

**Comment by MagoKimbra** [comment]
Good... I downlaod the file, but not function... I put file in same dir to marlin fw...

**Comment by fmalpartida** [comment]
I'll give it a shot.

**Comment by alexborro** [comment]
I tried to reload it many times, no results..

I'm using the latest Google Chrome.

2015-02-05 13:47 GMT-02:00 fmalpartida notifications@github.com:

> I'll give it a shot.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/pull/1467#issuecomment-73068260
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by thinkyhead** [comment]
It might be related to file access permissions - or maybe ".." isn't "up one folder" on your file-system. I find it works fine on OS X with Safari and Chrome. I have developer tools enabled for both, if that makes any difference.

The `configurator.js` file has a setting `marlin_config` at the top for the config files location. It _might_ work if you make a folder `Marlin/configurator/config` and place `boards.h`, `Configuration.h`, and `Configuration_adv.h` there, then set `marlin_config = 'config';` to point to that folder.

Alternatively, try moving the contents of `configurator` into the `Marlin` folder, then either set `marlin_config = '';` or `marlin_config = '.';`. I just want to suss out whether your browsers are allowed to read relative paths.

I might also try prefixing with `file://` – but I want to also use it on `localhost` so I need to do a check.

**Comment by thinkyhead** [comment]
Since file reading seems to be flaky, I've added a file field with drag and drop support to the top of the form. Drop a file on this field and it should load right away. It will accept `boards.h`, `Configuration.h`, and `Configuration_adv.h`. It's best to drop `boards.h` on it first to populate the Motherboards list.

**Comment by ntoff** [comment]
By default I think chrome is prevented from loading files from the hard disk through file://

http://peter.sh/experiments/chromium-command-line-switches/ there's an override there

**Comment by thinkyhead** [comment]
@ntoff Well, not a big deal. For development, I can make a **config** folder at the same level as **index.html** and put the three files there, then it should be able to load them as relative links. I'll give it a try in a more restrictive environment.

**Comment by thinkyhead** [comment]
For easier testing, on OS X you can launch Chrome like so from Terminal.app:

```
/Applications//Google\ Chrome.app/Contents/MacOS/Google\ Chrome --allow-file-access-from-files &>/dev/null &
```

For other systems [follow a different procedure](http://www.chromium.org/developers/how-tos/run-chromium-with-flags).

**Comment by ntoff** [comment]
How hard would it be to write some sort of python front end?

**Comment by thinkyhead** [comment]
@ntoff Pronterface is a Python front end. :-)

**Comment by ntoff** [comment]
I know, that's why I suggested it over tinkering with the way chrome launches. I figured most hard core printer users would already have python installed

**Comment by thinkyhead** [comment]
I've uploaded the configurator-in-progress to my website so it can be tested by the community without having to deal with browser security issues.

**http://www.thinkyhead.com/_marlin/**

I'm sticking to Javascript and no back-end for this project, even if it may be supplanted later, because the browser and Javascript are ubiquitous and we should have something that works without any additional installs on the part of users during the development phase. (Plus I'm not yet versed in Python.) Once it works fully, it can be deployed as a multi-platform application using Adobe Air, AppJS, Sentenza, NW.js, as a Chrome app, etc.

**Comment by thinkyhead** [comment]
There are 231 unique settings in `Configuration.h`, but some are specialized only for certain devices. `Configuration_adv.h` has 123. (Delta and SCARA settings not included in these counts.) Most settings will remain untouched for most users, so although I am currently aiming to make the entire configuration editable and intelligent about #if #else #endif blocks, it will definitely take some hands-on to make sure options are organized well and that users don't have to worry about options for devices they don't have.

In the process of scrutinizing these configs I am looking closely at the way they are organized and where there are dependencies. There are some changes I would definitely make for the sake of consistency, and for simplicity too! For example, I would replace multiple defines that only differ by number (`TEMP_SENSOR_0…3`, `HEATER_0…3_MINTEMP`, etc.) with single **const** arrays, which don't use any space in the compiled code. You can refer to _single_ **const** values in `#if` blocks (but not individual array elements of const arrays). However, when the compiler will strip unreachable code, so we can actually use `if (…)` in many cases, and that does work with const arrays. The final advantage to using **const** arrays is that the const array can replace the array currently being built using single #define values. All of this is of course TBD.

**Comment by nophead** [comment]
I don't think that it is true that you can use const values in an #if expression. The preprocessor will not know what they are so take them as 0. 

You can use them in if statements and rely on the dead code being eliminated but it still needs to compile. I.e. can't use other symbols that don't exist.

**Comment by galexander1** [comment]
You can't use const variables in #if at all _shrug_.

I haven't looked at your work so far yet.  But I think it is not
unreasonable to mark-up Configuration.h to make the job easier for a
configurator.

/\* SETTING: DELTA_SEGMENTS_PER_SECOND; DEP: DELTA; DEFAULT: 200;
   DESC: Make delta curves from many straight lines (linear interpolation).
   This is a trade-off between visible corners (not enough segments) and
   processor overload (too many expensive sqrt calls).
 */
// #define DELTA_SEGMENTS_PER_SECOND 200

i.e., regex /*\s_SETTING:\s_([^;]_);\s_DEP:\s_([^;]_);\s_DEFAULT:\s_([^;]_);\s_DESC:\s_(._)*/

Or what-have-you.  Just some way to add dependency and defaults
information that will not get in the way of people manually editting, but
will make it unambiguous to a configurator.

Just my two cents.

**Comment by thinkyhead** [comment]
@nophead @galexander1 You are correct, as I discovered today by trial! Fortunately there are some other preprocessor tricks we can use to _at least_ remove the need to initialize arrays in a manner that every time the number of extruders changes (for example) it becomes a game of hunt and seek. Actually that case is handled concisely by `ARRAY_BY_EXTRUDERS` - but there are clever ways to initialize up to thousands without too much trouble. (`#define` followed by `#include` is the key.)

**Comment by thinkyhead** [comment]
Good news! I've updated this configurator to load the configurations from Github. So it no longer has any browser compatibility issues, and can always obtain desired configurations. This also makes it possible to load whichever ones you like. The Github API also provides easy methods to get file listings, so all configurations in the repo can appear in the interface. I'll look into all of that pretty soon.

Otherwise, the tool is coming along well... Much yet to do on the organizational front, but the core functionality —the fun stuff— is almost complete.

**Comment by CONSULitAS** [comment]
@galexander1 @thinkyhead 
I dont like any hard coded behavior at all. So @galexander1 proposed a great idea. It would be harder to devolp a flexible configurator but on the long end we would either have the problem to keep it in sync with every change of config files.

If it is written once, it could handle EVERY config file - even for non Marlin configs!

To make it convenient to develop and flexible in use I would suppose the following additions to the tagging comment:

```
/* AUTOCONFIG
SETTING: DELTA_SEGMENTS_PER_SECOND
SECTION: Geometry
TYPE: INTEGER
DEP: DELTA,ADVANCED
DEFAULT: 200;
URL: http://some.help.text/or/howto
DESC: Make delta curves from many straight lines (linear interpolation). This is a trade-off between visible corners (not enough segments) and processor overload (too many expensive sqrt calls).
*/
// #define DELTA_SEGMENTS_PER_SECOND 200 
```

with
- every parameter on own line for simple parsing and readability
- `/* AUTOCONFIG` as magic value - every other comment will be simply copied
- `SETTING:` name of the parameter
- `SECTION:` tab for the parameter or group - depending on UI
- `TYPE:` simple data type ONOFF,BOOL,INTEGER,FLOAT,TEXT or comma separated list for dropdown
- `DEP:` Dependencies; separated by colon (optional)
- `DEFAULT:` if OFF parameter will be commented out (optional)
- `URL:` URL for further readings e.g. calculation guide to steps/mm (optional)
- `DESC:` Last and only parameter to allow multiline content - `*/` as stop sign

@thinkyhead What do you think? Would this be something to be worth coding on?

Cheers and good night
Jochen

**Comment by thinkyhead** [comment]
@CONSULitAS I've been thinking along a similar line, but I think there may be another way. Instead of cluttering the configuration file itself with extra information that makes it harder to actually find the option you need when editing, and puts an extra burden on both developers and maintainers, we could make this a separate file included in the configurator folder, which just has to be kept up-to-date by the maintainer of the configurator (for now, _moi_ ! ). Now that I've learned how to get files and file listings off Github, and added this as a feature, we can put whatever extras that the distributed configurator needs into the repository, and it will always keep up to date.

**Comment by galexander1** [comment]
@thinkyhead The idea that this will not pose a burden on developers is
fallacious.  It will be a burden, and the reward will make it worthwhile.
If exposed clearly, the burden will be less than the current burden of
maintaining example configs.

Or to put it another way, the only thing about the web-based configurator
that makes me uneasy is that it puts the burden on the author of the
configurator, which is a lot like not solving the problem that sent us
down this path in the first place.

**Comment by nophead** [comment]
How does a nice configurator reduce the burden of maintaining example
configs?

I suggest removing all sample configs and letting people who want to
champion a machine keep a Github fork with the correct configuration for
that machine and a version of Marlin tested on that machine.

**Comment by galexander1** [comment]
@nophead Okay, this is what I thought the motivation was.

The status quo sucks, because there is a proliferation of configurations
_within_ the Marlin tree that are all tied to a specific non-HEAD (i.e.,
obsolete) version of Marlin.  Some of those are vendor-provided, and same
are for geometries like delta.  Most of those only want to override a few
key settings, but wind up replacing the whole Configuration.h and
everything else that winds up in there.

The status quo sucks, because there is a proliferation of configurations
_outside_ the Marlin tree that are all tied to a specific obsolete version
of Marlin.

The status quo sucks, because there is the beginning of a proliferation
of configurators _outside_ the Marlin tree that are all tied to a specific
obsolete version of Marlin.

I thought those were the problems we were trying to solve here.  If they
aren't, someone please tell me what the point is.

**Comment by nophead** [comment]
Perhaps rather than hacking the config files they should be fixed and define a default config. Machine specific variations should then define just the bits that differ from the default. That would make them short  and thus far more version independent. Also what is unique about the machine would be explicit.

**Comment by galexander1** [comment]
@nophead With #ifndef, right?  I suggested that 4 times now. :)

The downside to that approach is that then there is no convenient single
place to go to look and see authoritatively what your current config is.
To understand the config, you would have to mesh information from your
overrides with information from the default.

**Comment by nophead** [comment]
Yes with ifdef or undef, depends which order things are defined.

When I have done this sort of thing in the past I wrote a DSL where I could define things three ways: a fixed value that could not be changed, a value with a default that could be overridden or a name without a value that must be defined later or gives an error. That is more flexible than the C preprocessor. It generated C from templates and then you could look at the result to see your resulting configuration.

I don't think there is a perfect solution to having software that supports such a large variety of devices and evolves as well.

**Comment by scotty1024** [comment]
How about a machine.h file included from configuration.h? That file would include a machine-model.h file.

The machine.h file would document the over-rides possible via machine-model.h

Anything defined in machine.h would by definition be fairly stable with much wailing and gnashing of teeth required to alter. Or put more plainly machine.h would be the public contract for how to configure Marlin for a given line of bots eg k8200.

EEPROM is used to hold calibration for a particular instance of a machine-model. With machine.h/machine-model.h expected to provide reasonably sane seed values for EEPROM calibration values.

OEM's and enthusiasts would maintain a collection of machine-model.h files.

Your 90% user would calibrate a couple EEPROM values and promptly forget Marlin exists.

The 10%'s could still configure and compile.

Eventually the machine-model.h files in the repo could be used to establish a CI build that would both test the known machine builds as well as produce a repo of binaries the community could draw upon. The 90%'s would then no longer even need to compile.

The CI build could use an environment variable to direct machine.h to include the desired machine-k8200.h instead of machine-model.h as it chugs along looping through a directory of such model files.

Eventually things like heated bed yes/no could be altered to come from EEPROM as well. Marlin could be set for four extruders and the actual number of extruders attached be in EEPROM.

Further down the road OctoPrint and ilk could have calibration tools built in to print calibration models and have users measure them and OctoPrint could then tweak the EEPROM. It could also issue an Mxxx to get the GitHub ID of the binary and check for a newer binary and handle flashing it via a Marlin flashing API.

**Comment by nophead** [comment]
I don't like the idea of requiring the use of EEPROM. I don't enable it on my machines because it is far too confusing having settings stored in two different places and far to easy to loose them.

I keep settings for all my machines on a server, edit them there and then flash the firmware with ino running on an RPI whenever I change anything.

**Comment by thinkyhead** [comment]
I can certainly add a (valuable) report option to the configurator, which would list all settings, highlighting those that have been customized. Really, _my_ aim with this is indeed to wrangle settings into a manageable form, and then to be able to mess with them in more automated ways, including, but not limited to:
- writing out the default settings in the format matching the EEPROM
- Renaming settings (across the code-base)
- Writing out a file that _only_ contains altered settings (aka `machine.h`)
- and more concepts that I will keep adding in future days....

**Comment by thinkyhead** [comment]
Regarding the maintenance problem, I think I can largely solve it by having the configurator be very up-front about the settings it knows and those it doesn't, and making a (relatively simple) editable JSON file that the configurator can ask the user to edit, if they don't mind, but which should be very close to up-to-date with current settings all the time. All the JSON file needs to describe is exceptions to typical behavior, and anything that can't be gleaned from the Configuration files themselves. (e.g., the list of possible options for a particular field.)

In the short run we should end up with something of some value, a machine-digestible file that describes all the Marlin configuration options pretty fully, and from that we can generate documentation in .md, .html, etc.

**Comment by ntoff** [comment]
Just leave config and config_adv alone and make an override.cfg. Add a line to marlin somewhere that if override.cfg exists, #include it (or whatever, I don't know if #include is right).

That way if you download a new version of marlin and for some reason config and config_adv have changed drastically, as long as it still looks for an overrides then your personalized settings will be intact.

Would that make sense?

**Comment by thinkyhead** [comment]
@ntoff The configurator can certainly do things like add `#include` lines to the files it generates, but the Arduino compiler has no way to check for an include file before deciding to include it.

There has been some mumbling about splitting up the Configurations more. The on/off switches would be in the main Configuration file, and it would conditionally `#include` the others. The main configuration then becomes much smaller, and then each one could include more documentation. So, for example `Configuration.geometry.h`, `Configuration.temperature.h`, `Configuration.lcd.h`, `Configuration.delta.h`, `Configuration.scara.h`, `Configuration.probes.h`, `Configuration.sensors.h`, `Configuration.goodies.h`, etc., each only containing relevant options. Adding a `Configuration.override.h` (normally empty) would work in that scheme.

But for the time-being, I am splitting up the options just by adding headings in the config files that can be noticed and turned into tabs in the form. Available options I'm hiding in comments as JSON objects. That's all just in my own copies of the config files, and only for experimentation. The final outcome I can't fully anticipate yet.

Check out the latest additions. I'm pleased all these things can now be done so easily in Javascript!

**Comment by thinkyhead** [comment]
I've added the first level of dependency tracking so the form can enable/disable (or hide/show) fields that depend on other defines being enabled.

Next I still have to add support for "overrides" – a second (3rd, 4th, etc.) occurrence of a symbol, which is defined conditionally. For example, with `Z_DUAL_STEPPER_DRIVERS` enabled, `EXTRUDERS` should become unavailable to set, and should be overridden with the value `1`. Or, when `MAKRPANEL` is enabled, `ULTIPANEL` will be overridden (as "enabled"), causing items that depend on `ULTIPANEL` (such as `FILAMENTCHANGEENABLE`) to be enabled.

Also next, I'm adding a preprocess step to gather similar fields together into a single input line. For example, `MANUAL_X_HOME_POS`, `MANUAL_Y_HOME_POS`, and `MANUAL_Z_HOME_POS` will fields be gathered together with a single label **Manual XYZ Home Pos**.

Once that last step is done I'll have a comprehensive set of data structures encapsulating all the configuration data, and pretty robust methods for extracting the structure from the configuration text.

**Comment by thinkyhead** [comment]
Ok, I've added the pre-processing step to find adjacent related fields, and grouping is now applied when building the form. I rearranged some settings in `Configuration.h` to get better grouping. It still needs to look for overridden defines inside conditional blocks. These will be assumed to be "hard" overrides – not intended to be altered – usually within the "hidden" section.

So far the only config annotations I've needed to add to the configuration files are to specify in which **@section** the following options should appear, or to show special options, as in the case of `POWER_SUPPLY`, `X_ENABLE_ON`, etc.

**Comment by thinkyhead** [comment]
Development will continue on Marlin Configurator as time allows. It's still in the experimental alpha stage, as I develop methods to parse and generate configurations, form fields, etc. It has only a raw "expert" interface so far (with almost every option exposed) but will get a simplified interface and a presets menu over time. Now hosted at:
- https://github.com/thinkyhead/MarlinConfigurator
- https://rawgit.com/thinkyhead/MarlinConfigurator/master/src/index.html

**Pull request merged**
