### PR TITLE
Support for up to 6 Linear Axes

### PR DESCRIPTION
**Pull request by DerAndere1**
### Requirements

- [x] Fix EEPROM (M500, M504) datasize error
- [x] More hardware testing with  NON_E_AXES 5 or 6 (axes XYZIJK) plus extruder) and TMC / L64xx drivers 
- [ ] Compatibility with displays and niche features
- [x] Think about sanity checks 

### Description

This is only a starting point for discussion. Documentation: https://github.com/DerAndere1/Marlin/wiki . I understand that multi-axis support might be out of scope for MarlinFirmware/Marlin. Currently, not all niche features  are compatible with LINEAR_AXES >= 4 (see https://github.com/DerAndere1/Marlin/issues). 

* Tested on 8 bit AVR (Melzi_optiboot) with four non-extruder axes (LINEAR_AXES 4)

* Tested on 32bit Teensy 3.6 (LINEAR_AXES 6)

* Was adapted by others for Alfawise U20/U20+/U30 with 5 non-extruder axes and a 32bit BTT SKR Pro v1.1 

Contributions:

| Name | Contact | contribution |
|--- |--- |--- |
| DerAndere | [@DerAndere1](https://github.com/DerAndere1) | idea for multi-axis suport, initial implementation, added EVENT_GCODE_TOOLCHANGE_T0, EVENT_GCODE_TOOLCHANGE_T1, FOAMCUTTER_XYUV |
| Gabriel Beraldo | [@GabrielBeraldo](https://github.com/GabrielBeraldo) | hardware debugging, bugfixes yielding first working prototype with more than 3 linear axes (make additional axes move, fix EEPROM) |
| Olivier Briand | [@hobiseven](https://github.com/hobiseven) | testing, added experimental compatibility with different configurations, code review, `FOAMCUTTER_XYUV` feed rate interpretation mode |
| Wolverine | [@MohammadSDGHN](https://github.com/MohammadSDGHN) | added experimental compatibility with different configurations (BigTreeTech SKR Pro 1.1, Trinamic TMC drivers, StealthChop, sensorless homing) |
| bilsef | [@bilsef](https://github.com/bilsef) | testing, code review, bugfixes (fix movement of additional axes, fix types.h, fix EEPROM)|
| Scott Lahteine | [@thinkyhead](https://github.com/thinkyhead) | code review, big refactoring | 

### Benefits

The additional non-extruder axes I, J, and/or K can be used to control additional stepper motors, syncronized with XYZ-movement. They are designed as first-class axes that offer the same functionality as XYZ (endstops, homing). 
Axis codes can be configured to match G-code standards (X,Y,Z,A,B,C or  X,Y,Z,U,V,W ).  Now Marlin can also be used as firmware for  pipetting robots and 4-axis FOAMCUTTERS. Most code is in if/endif preprocessor directives

### Related Issues

Towards fulfilling old feature requests:
- https://github.com/MarlinFirmware/Marlin/issues/15717
- https://github.com/MarlinFirmware/Marlin/issues/8519

Includes code from
- https://github.com/MarlinFirmware/Marlin/pull/17283

Test config for RAMPS:
[RAMPS_XYZI.zip](https://github.com/MarlinFirmware/Marlin/files/5112660/RAMPS_XYZI.zip)

### CODE REVIEW

**Comment by thinkyhead** [comment]
For extra guidance on extending the number of linear axes in Marlin, take a look at Marlin 1.1.9 and study the `HANGPRINTER` feature. At that time all of Marlin's coordinates were stored in simple arrays, so it was a bit more straightforward to implement. But the types defined in `types.h` shouldn't be too hard to modify.

**Comment by DerAndere1** [comment]
I appreciate that you took the time to have a look at my big messy code.  Your improvements to readability are already great. Don't feel pushed to dig too deep into this. I'm curious how you managed to replace the deeply nested `#if #if #endif #endif` sections by the more flat #if#endif#if #endif structure so fast.

**Comment by DerAndere1** [comment]
What could be the most likely cause of the "EEPROM datasize error" bug that I introdced? i.e. What is the meaning of
```
error: EEPROM datasize error
echo: index: 645 Size 737
```
and 
`Error: Field planner_leveling_active mismatch` ?
I suspect it has to do with 
a) the order of variables in settings.cpp or 
b) the use of arrays with variable element count depending on NON_E_AXES/LINEAR_AXES (instead of dummy values).

Also, the use of the macro LIST_N does not seem to work if the later, unused array elements are undefined.

**Comment by thinkyhead** [comment]
> I'm curious how you managed to replace the deeply nested … so quickly

I know all the keyboard shortcuts. But also, I spent about 6 hours on this.

> `Error: Field planner_leveling_active mismatch` ?

The structure at the top of `settings.cpp` exists to validate the offsets of data written to the EEPROM. This error indicates that something between the previous error-check and the `planner_leveling_active` check is writing too much or too little data. It's also possible that the structure is incorrect concerning the size of one or more fields.

**Comment by DerAndere1** [comment]
A 6 axis configuration for Teensy 3.6 by @bilsef can be found in the attachment of this comment.
[6axisConfig.zip](https://github.com/MarlinFirmware/Marlin/files/5247708/6axisConfig.zip)

**Comment by DerAndere1** [comment]
Updated the description to reflect the fact that the most annoying bugs were fixed and the CANNED_DRILLING_CYCLES feature from PR https://github.com/MarlinFirmware/Marlin/pull/17283 was incorporated.

**Comment by thinkyhead** [comment]
One thing to watch out for is that custom axis letters may conflict with extended parameters on commands that use `gcode.get_destination_from_command` (`G0`, `G1`, `G2`, `G3`, `G5`, `G38`). We can add some asserts / sanity-checks to catch those cases.

**Comment by bilsef** [comment]
@thinkyhead Last changes to types.h break compile for axes > 3.  The e axis must only be included after the last linear axis.  I was able to fix it like this, but perhaps you have a better solution.

```cpp
// XYZE coordinates, counters, etc.
//
template<typename T>
struct XYZEval {
  union {
    struct{ T LIST_N(LINEAR_AXES, x, y, z, i, j, k), e; };
    struct{ T a, b, c; };
    T pos[LINEAR_AXES + 1];
  };
  FI void reset()                                             { e = GANG_N(LINEAR_AXES, x =, y =, z =, i =, j =, k =) 0; }
  #if ENABLED(ASYNC_SECONDARY_AXES)
    FI T magnitude() const { return (T)sqrtf(e*e + x*x + y*y + z*z); }
  #else
    FI T magnitude() const { return (T)sqrtf(e*e GANG_N(LINEAR_AXES, + x*x, + y*y, + z*z, + i*i, + j*j, + k*k)); }
  #endif
  FI operator T* ()                                           { return pos; }
  FI operator bool()                                          { return e GANG_N(LINEAR_AXES, || x, || y, || z, || i, || j, || k); }
  FI void set(const T px)                                     { x = px;               }
  FI void set(const T px, const T py)                         { x = px;    y = py;    }
  FI void set(const XYval<T> pxy)                             { x = pxy.x; y = pxy.y; }
  FI void set(const T px, const T py, const T pz)             { x = px;    y = py;    z = pz; }
  #if LINEAR_AXES < 4
    FI void set(const T px, const T py, const T pz, const T pe) { x = px;    y = py;    z = pz; e = pe;}
  #endif
  FI void set(const XYval<T> pxy, const T pz)                 { x = pxy.x; y = pxy.y; z = pz; }
  #if LINEAR_AXES >= 4
    FI void set(const T px, const T py, const T pz, const T pi)                         { set(px,  py, pz); i = pi; }
    FI void set(const XYval<T> pxy, const T pz, const T pi)                             { set(pxy,     pz); i = pi; }
    #if LINEAR_AXES < 5
      FI void set(const T px, const T py, const T pz, const T pi, const T pe)             { set(px,  py, pz,    pi); e = pe; }
      FI void set(const XYval<T> pxy, const T pz, const T pi, const T pe)                 { set(pxy,     pz,    pi); e = pe; }
      FI void set(const XYval<T> pxy, const T pi, const XYval<T> pze)                     { set(pxy,     pze.z, pi); e = pze.e; }
    #endif
  #endif
  #if LINEAR_AXES >= 5
    FI void set(const T px, const T py, const T pz, const T pi, const T pj)             { set(px,  py, pz,    pi); j = pj; }
    FI void set(const XYval<T> pxy, const T pz, const T pi, const T pj)                 { set(pxy,     pz,    pi); j = pj; }
    #if LINEAR_AXES < 6
      FI void set(const T px, const T py, const T pz, const T pi, const T pj, const T pe) { set(px,  py, pz,    pi, pj); e = pe; }
      FI void set(const XYval<T> pxy, const T pz, const T pi, const T pj, const T pe)     { set(pxy,     pz,    pi, pj); e = pe;}
      FI void set(const XYval<T> pxy, const T pi, const T pj, const XYval<T> pze)         { set(pxy,     pze.z, pi, pj); e = pze.e; }
    #endif
  #endif
  #if LINEAR_AXES >= 6
    FI void set(const T px, const T py, const T pz, const T pi, const T pj, const T pk)             { set(px, py, pz,    pi, pj); k = pk; }
    FI void set(const XYval<T> pxy, const T pz, const T pi, const T pj, const T pk)                 { set(pxy,    pz,    pi, pj); k = pk; }
    FI void set(const T px, const T py, const T pz, const T pi, const T pj, const T pk, const T pe) { set(px, py, pz,    pi, pj, pk); e = pe; }
    FI void set(const XYval<T> pxy, const T pz, const T pi, const T pj, const T pk, const T pe)     { set(pxy,    pz,    pi, pj, pk); e = pe; }
    FI void set(const XYval<T> pxy, const T pi, const T pj, const T pk, const XYval<T> pze)         { set(pxy,    pze.z, pi, pj, pk); e = pze.e; }
  #endif

```

**Comment by thinkyhead** [comment]
That's pretty much the best available solution. I tweaked it slightly, adding the cases for 3 linear axes too.

**Comment by thinkyhead** [comment]
Merged from bugfix-2.0.x to bring it up to date. What we really need is to expand this with a total of 9 (or any number) of linear axes so that robotic arms can be controlled in a coordinated way.

And we also need to avoid parameter letter conflicts with any G-code commands where we want to add support for up to 9 linear axes. So, if a command will now take XYZ but also takes other parameters, we need to add checks that any letters assigned to extra axes don't introduce conflicts. And if a conflict is introduced, then we need to supply a solution for each case.

I see this is now failing compilation, so I'll take a stab at patching it up in the morning.

**Comment by bosd** [comment]
As an proud owner of the BTT GTR V1.0 board. With the potential of driving 11 individual axis.
Currently I am building a custom purpose CNC machine based on this board.

I'm eyeballing this commit very closely. 
(just a beginner in the Marlin space, but willing to help)
The opening post mentions that the multi-axis support is out of scope of Marlin.
Yet, standard Marlin does already achieve a lot of functionality.
So, seems logical to built further upon the marlin base.
Will the multi-axis be implemented in Marlin, or will it be an fork?

Like thinkyhead mentions, it would be very interesting to be able to control robot arms.

**Comment by thinkyhead** [comment]
@DerAndere1 — I've just done a rebase to squash this down to one commit and make it easier to see changes in relation to the current codebase. To update your working copy, use the git console and enter the commands:
```
git checkout 6axis_PR1
git fetch origin
git reset --hard origin/6axis_PR1
```

**Comment by DerAndere1** [comment]
I will have a Look at this. Any suggestion which extra axis names should be allowed are welcome. 
I suggest for now to remove support for names I,J,K and only to allow standard-compliant 'U','V','W','A','B','C'. Extension to 9 axes could be done in a separate PR. 

@thinkyhead : we should rebase again and edit the commit message to retain the Original attributions (and add newer contributors like FNeo31 and bilsef), including `Co-authored-by:` tags so that co-authors are tracked by github. 
What Follows is my proposal for the commit message.
```
towards support for extra linear axes. Contributions:

DerAndere (26200979+DerAndere1@users.noreply.github.com): idea, initial 
implementation of experimental support for 6 non-extruder axes for Marlin

Gabriel Beraldo (gabrielgbst@hotmail.com): hardware debugging, bug fixes

Olivier Briand (48122416+hobiseven@users.noreply.github.com): testing,
compile error fixes, FOAMCUTTER_XYUV kinematics

Wolverine (MohammadSDGHN@users.noreply.github.com): added compatibility
with BigTreeTech SKR Pro v1.1, Trinamic TMC drivers, STEALTHCHOP,
SENSORLESS_HOMING)

bilsef <bilsef1@gmail.com>: clean-up, bug fixes

FNeo31 (37299777+FNeo31@users.noreply.github.com): added M81 (drill), 
M82 (spot drill), M83 (pecking) drilling cycles

Scott Lahteine <thinkyhead@users.noreply.github.com>: clean-up, update,
code review

Co-authored-by: DerAndere <26200979+DerAndere1@users.noreply.github.com>
Co-authored-by: GabrielBeraldo <gabrielgbst@hotmail.com>
Co-authored-by: Olivier Briand <48122416+hobiseven@users.noreply.github.com>
Co-authored-by: Wolverine <MohammadSDGHN@users.noreply.github.com>
Co-authored-by: bilsef <bilsef1@gmail.com>
Co-authored-by: FNeo31 <37299777+FNeo31@users.noreply.github.com>
Co-authored-by: Scott Lahteine <thinkyhead@users.noreply.github.com>
```

**Comment by chepo92** [comment]
Following this very closely, for a 3 or more DOF robotic arm it would be needed an inverse kinematic right? , how may I start diving into coding that? I was thinking in starting from a delta kinematics (I believe most calculation are donde in delta.cpp, right? )

**Comment by DerAndere1** [comment]
I did another interactive rebase, added the sanitychecks against conflicting axis names. To update your local working copy, you should be able use thinkyhead's nice trick:
```
git checkout 6axis_PR1
git fetch origin
git reset --hard origin/6axis_PR1
```

**Comment by DerAndere1** [comment]
> Following this very closely, for a 3 or more DOF robotic arm it would be needed an inverse kinematic right? , how may I start diving into coding that? I was thinking in starting from a delta kinematics (I believe most calculation are donde in delta.cpp, right? )

@chepo92 :  Yes you would need to add inverse kinematics for your robot. Be aware: code related to specific (inverse) kinematics is not only in one file like delta.cpp. It is currently scattered all over the codebase. Search for all occurances of 'ENABLED(DELTA)' and 'IS_KINAMITIC'... DELTA kinematics are a good place to start. In order to see how to use more than 3 axes, see occurances of 'FOAMCUTTER_XYUV'  in my PR

**Comment by GMagician** [comment]
Is there any news about the status of this PR?

**Comment by DerAndere1** [comment]
It works for me but it needs more testers before it is ready for production. Always supervise your test-runs whenever you change configs or when you run a new G-code and be ready to hit the kill-button on your machine in case something unexpected happens. I got positive reports from several people using it with different cartesian setups or with syringe pumps. More feedback on what is running well is highly welcome. For testing, clone https://github.com/DerAndere1/Marlin and checkout the branch [6axis_PR1](https://github.com/DerAndere1/Marlin/tree/6axis_PR1). Please report at https://github.com/DerAndere1/Marlin/issues/13 what worked well. Otherwise, open new bug reports at https://github.com/DerAndere1/Marlin/issues. In each case, it helps if testers attach their config files.

**Comment by GMagician** [comment]
Is there any reason new axes are called ijk and not a more standard uvw?

**Comment by DerAndere1** [comment]
IJK was chosen as internal axis names because IJK are generic identifiers. If I understand LinuxCNC correctly, they use UVW specifically to refer to **linear** axes. In my PR, the axis name used in G-code can be defined in configuration.h to be either A/B/C (for rotary axes) or U/V/W (for linear axes). Note, that in my original PR, the feature was called NON_EXTRUDER_AXES which was changed to the arguably less correct but shorter name LINEAR_AXES during code review. We can use hard-coded axis names XYZUVWABC when we extend Marlin to support up to 9 axes. In places where inverse kinematics have been applied, I would prefer distinct internal names in the form `ax1`, `ax2`, `ax3`, `ax4`...

**Comment by TWilmer** [comment]
Hi,
I didn't know this pr existed, I used a different fork (Bills fork) for 6 Axis support and I extended it to attempt to support more internal axis, I continued with L and M - which was a very dump idea because L and especially M clash with some macros.

So I would prefer to use axis names - internally - which don't clash with other macros.  Do you plan to switch for this reason to uvwabc - do you know if these wouldn't clash?

Or would you prefer to stick with it and only support 6 Axis. 

Wouldn't it make sense to rework this entirely to support n-Axis? Or do you think this should be a later change once this pr is merged?

Or do you think this is too much work or for some other reason not a good idea or at least long term goal?

Kind Regards
 Thorsten

**Comment by DerAndere1** [comment]
@TWilmer :  Looking at your git history reveals that you chose the Marlin fork by bilsef as a basis for your work. For some time, bilsef collaborated with me on the 6 axis code (see commit message of this PR). but this PR branch got a massive cleanup later. I propose the following steps: 
1. You may have forgotten to add code for L and M axes in types.h l319-334 https://github.com/TWilmer/Marlin/blob/373992daa97ccffc47013d9517b1bb8047d9b4c7/Marlin/src/core/types.h#L319-L334 
2.  Which macros do you suspect to conflict with L_AXIS and M_AXIS ? I don't expect any problems.
3. Once steps 1) and 2) are sorted out, we should review your changes at https://github.com/TWilmer/Marlin/tree/2.0.x more closely
4. Only then we should think about changing to internal names XYZUVWAB. Ideally, that change would happen in the cleaned up code of this PR-branch (after you report successful movement + homing with your code).

**Comment by thinkyhead** [comment]
Merged and cleaned up.

It's not up front but the axes can be renamed. And this will be more important as more axes are added.

Eventually, it's desirable to get this up to a total of 9 linear axes, plus the extruder. Collisions with other axes will become a lot tougher at that point, so to set things up for the future it would be good to have some extended G-code syntax that can support any number of axes. One simple parameter syntax is to treat the comma as an 'increment' to the next parameter or axis. So `G1 X12,,10` would be like `G1 X12 Z10`. Other syntaxes are possible, like using braces to specify an array or colons to split up elements of a G-code parameter. RepRapFirmware is probably the one to emulate.

**Comment by FlorianFritz** [comment]
I've tried to compile the code (from DerAndere1's Repo 6axis_PR1) for a Arduino Mega 2560/RAMPS with the REPRAP_DISCOUNT_SMART_CONTROLLER enabled. And it fails on missing language strings in Marlin/src/lcd/language/language_en.h. Adding following lines solved the problem:

```
PROGMEM Language_Str MSG_AUTO_HOME_I = _UxGT("Home ") AXIS4_STR;
PROGMEM Language_Str MSG_AUTO_HOME_J = _UxGT("Home ") AXIS5_STR;
PROGMEM Language_Str MSG_AUTO_HOME_K = _UxGT("Home ") AXIS6_STR;
```
  
[language_en.patch.txt](https://github.com/MarlinFirmware/Marlin/files/6383308/language_en.patch.txt)

**Comment by DerAndere1** [comment]
Commit  fd197de  actually fixed G28 completely for my 4 axis setup. `G28 A` also works for homing the 4th axis,. the issue with `G28A` that I mentioned in the commit message was due to a G-code syntax error during my test run.

**Comment by DerAndere1** [comment]
I assign myself to the task of bringing paloky's extension of this code for up to 9 linear axes up to date. I will open a pull request targeted at my 6axis_PR1  branch in the next days and leave it unmerged for code review. There will be white space issues again, so the inital code might be too ugly for bringing it right into the 6axis_PR1 branch. As I said earlier, I think extension to 9 axes can wait. But at least there will be a proof of principle.

**Comment by thinkyhead** [comment]
I should be through messing with this in the next hour or so. I've got the basic compilation for LINEAR_AXES == 2 working, and now I'm just breaking a few things as I go through the rest of the references to `LINEAR_AXES >= 4` and apply `LINEAR_AXES >= 3` where needed.

**Comment by DerAndere1** [comment]
Please comment about the (still untested) 9 axis PR https://github.com/DerAndere1/Marlin/pull/49 .  Some lines are still way too long. In general I propose to group long parameter lists as indicated below,if possible. In types.h I would keep lines as long as required and not split them up.
```
void func(int xxxx, int yyyy, int  zzzz
  int iiii, iint jjjj, int kkkk,
  int mmmm, int oooo, int pppp, int qqqq,
  int eeee
);
```
or with Macros:
```
void func(LOGICAL_AXIS_LIST(int eeee, int xxxx, int yyyy, int  zzzz
  int iiii, iint jjjj, int kkkk,
  int mmmm, int oooo, int pppp, int qqqq)
);
```

**Comment by thinkyhead** [comment]
A grouping like that will work just fine. In the long run I want to work out an alternative architecture so we can simply use good old arrays. I have some ideas about that. It would also be possible in the short term to generate these lists without having to include every element inside the macro call. For example, we could decide that any list of variables will follow a common pattern, so your example then becomes:
```cpp
void func(LOGICAL_AXIS_ARGS(int)); // Variables always named ee, xx, yy, etc.
```

**Comment by DerAndere1** [comment]
Hi thinkyhead, the commit https://github.com/MarlinFirmware/Marlin/pull/19112/commits/94da283862ba33495b6287dfb337002d0379ccd0 ("Shorthand for args, elem, dec1") is a great achievement regarding extendibility.
But I have the feeling that it will make it harder to read and contribute code to Marlin by others that are not so familiar with the Macros. For example it might be difficult to unserstand  for others how planner.h line 802 works: 
```
      return buffer_line(LOGICAL_AXIS_ELEM(cart), fr_mm_s, extruder, millimeters OPTARG(SCARA_FEEDRATE_SCALING, inv_duration));
```
also, the parameters of functions like tmc_util.h line 927  look quite far away from standard C++ to me, because the reader only sees the type with no variables:
```
void tmc_report_all(LOGICAL_AXIS_ARGS(const bool)) { 
```
You will have to decide if you feel comfortable with having this in mainstream Marlin. 
I wonder if there is an alternative way to group those individual axes together. I imagiine something like an `axes` struct or class so that one can pass the `axes`  object as a sngle parameter and have access to its elements axes.x, paxes.y, axes.z ...

**Comment by thinkyhead** [comment]
I expect the initial implementation to be less than ideal, but over time it can be improved. I don't think IntelliSense or other context-aware parsers like Marlin very much anyway. In the long run I hope to find some way —via heavy use of `constexpr` and template classes— to make it possible to describe an "axis" and an "axis group" and to build them up in a more intuitive manner, so all their scattered properties and behaviors are better encapsulated. Maybe each axis or axis grouping ought to get its own header file. Out of our gradual evolutions we will find some revolutions.

**Comment by thinkyhead** [comment]
So, for simplification I also got rid of the `Stepper::` and `Planner::` methods that take the coordinates as separate arguments. Now you have to pass a coordinate object instead. This change ended up optimizing some things, such as the UBL motion code, even though it may require making a temporary object here and there.

**Comment by DerAndere1** [comment]
HendrikJan-5D found an [issue with AUTO_BED_LEVELING_3POINT](https://github.com/DerAndere1/Marlin/issues/44#issuecomment-851382846). I think it could have to do with the matrix_3x3 class or other parts of vector_3.h . vector_3 is designed with 3 elements in mind but the code is full of xyz_float_t which hold more elements for LINEAR_AXES >=4. This may also be the reason why more than 9 matrix elements are needed in settings.cpp to make EEPROM work with LINEAR_AXES >=4.  Quote from HendrikJan-5D:

> When further testing Marlin-6axis_RP1 I run into the following problem.
> G28 home all axes
> G1 works for all axes
> G29 bed leveling works
> M503 indicates that M420 S0 has now become M420 S1
> G1 no longer works for all axes
> this can be solved by
> M502
> M500
> G28 home
> Now I can operate all axes again
> 
> In summary: after performing a bed leveling all axes are blocked by something written in the EEPROM

**Comment by thinkyhead** [comment]
Don't forget to reset the EEPROM with `M502`, `M500` when you get an EEPROM Data Size error. If the error persists after that, enable `DEBUG_EEPROM_READWRITE` to get a more accurate location for the bug.

**Comment by thinkyhead** [comment]
Please check whether `M502`, `M500` clears up the error. If that doesn't help then we'll have to look closer.

**Comment by thinkyhead** [comment]
The problem is with the updated definition of `vector_3`. I'll patch that up shortly….

**Comment by Sinclair5** [comment]
this is truly amazing,  thinkyhead  directed me here from discord.  i hope to use this as a firmware for a diy  sls  printer

**Comment by thinkyhead** [comment]
@DerAndere1 — With the number of commits growing very large, I decided to rebase this on the latest `bugfix-2.0.x` and squash it down to a single commit. To update your working copy (once it's passing CI tests):
```
git checkout 6axis_PR1
git fetch origin
git reset --hard origin/6axis_PR1
```

**Comment by thinkyhead** [comment]
At this point all we can do is keep testing this code on a variety of machines, and clear bugs as we find them. The best way to catch bugs is to merge and see how badly it breaks for random testers. Since this is passing tests and I've been over the important parts a couple dozen times, I will merge it now and we can build the other 3 axes in once we've debugged the first 6….

**Comment by DrumClock** [comment]
@thinkyhead  chyba při kompilaci :
```
Compiling .pio\build\rumba32\libb2a\TMCStepper\source\CHOPCONF.cpp.o
Marlin\src\module\settings.cpp: In static member function 'static bool MarlinSettings::save()':
Marlin\src\module\settings.cpp:1179:9: error: 'const tmc_hybrid_threshold_t' has no non-static data member named 'E2'
 1179 |         };
      |         ^
*** [.pio\build\rumba32\src\src\module\settings.cpp.o] Error 1
================================================================ [FAILED] Took 13.61 seconds ===========================
```

**Comment by DerAndere1** [comment]
@thinkyhead and everyone else involved: thanks for your hard work. Lets see what bugs crop up after the merge. I will watch out for multi-axis-related bug reports at  https://github.com/MarlinFirmware/Marlin/issues.

@DrumClock: Please attach your configs and pin file for your board.

**Comment by DrumClock** [comment]
@DerAndere1 
ani dnešní verze FW Bugfix nic neřeší..... konfigurační soubory : [RUMBA32 new.zip](https://github.com/MarlinFirmware/Marlin/files/6603900/RUMBA32.new.zip)

**Comment by DerAndere1** [comment]
@DrumClock : Thanks for the report. With current bugfix-2.0.x, your configs do not compile due to other reasons. Please first configure your firmware according to the instructions at https://marlinfw.org/docs/hardware/boards.html, then make sure you get no errors from SanityCheck.h . Currently I get 
```
SERVO1_PIN must be defined for your SWITCHING_EXTRUDER
``` 
and  
```
"Z_MIN_PROBE_PIN must be defined if Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN is not enabled.
```
with your configs. That seems unrelated to this pull request. It looks more like you forgot some pin definitions

**Comment by DrumClock** [comment]
Ahoj @DerAndere1 .... nezapomněl jsi použit tyto soubory z mojí konfigurace ?

```
Conditionals_LCD.h
pins_RUMBA32_common.h
pins_RUMBA32_MKS.h
```
Je zde definice pinů upravené desky RUMBA a možnost využití 2x `SWITCHING_EXTRUDER` (E0/E1 a E2/E3 = dva motory E)

Před aktualizací v pátek (Support for up to 6 linear axes (#19112)) bylo vše v pořádku a funkční....
Kompilace skončí chybou:
```

Compiling .pio\build\rumba32\src\src\module\tool_change.cpp.o
Marlin\src\module\settings.cpp: In static member function 'static bool MarlinSettings::save()':
Marlin\src\module\settings.cpp:1179:9: error: 'const tmc_hybrid_threshold_t' has no non-static data member named 'E2'
 1179 |         };
      |         ^
Compiling .pio\build\rumba32\src\src\sd\Sd2Card.cpp.o
*** [.pio\build\rumba32\src\src\module\settings.cpp.o] Error 1

```
Nemůže to být konflikt mezi funkcemi **SWITCHING_EXTRUDER** a  **6 Linear Axes** ?

**Comment by DrumClock** [comment]
..... pokud funkci `SWITCHING_EXTRUDER` zakážu, kompilace proběhne bez chyb.

**Comment by DerAndere1** [comment]
@DrumClock I could reproduce the compile error with your config. Should be fixed with pull request 22068

**Comment by DrumClock** [comment]
@DerAndere1 děkuji, dnes již kompilace proběhla v pořádku

**Pull request merged**
