### PR TITLE
Fix missed grace period causing compile error

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Followup to obsolete grace period

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Why would that cause a compile time error?
(unless grace_period is out of scope???)

**Comment by tpruvot** [comment]
> Why would that cause a compile time error?
> (unless grace_period is out of scope???)

https://travis-ci.org/MarlinFirmware/Marlin/builds/568159309

**Comment by InsanityAutomation** [comment]
Because it just got deleted in another PR merged a little while ago ( #14798 ) so this call is undefined now. Something else is going on with software serial for a couple platforms. I didnt look at that yet.

**Comment by robbycandra** [comment]
Duplicate with https://github.com/marlinfirmware/marlin/commit/fc39c925ca0e40ea41b217b910913f0e935338b5

**Comment by InsanityAutomation** [comment]
> 
> 
> Duplicate with [fc39c92](https://github.com/MarlinFirmware/Marlin/commit/fc39c925ca0e40ea41b217b910913f0e935338b5)

Id call that the dupe since this was opened a couple hours earlier, but either way this one is no longer necessary then!

**Pull request closed without merging**
