### PR TITLE
Move LPC1768 framework out of Marlin source folder

### PR DESCRIPTION
**Pull request by tcm0116**
This PR moves the CMSIS LPC1768 framework out of the Marin source folder as a separate PIO library. The purpose of this change is to allow for different compiler settings to pave the way for cleaning up the various warnings that are generated during Re-ARM compilation.

UPDATE: I realized that every HAL was being compiled in every configuration, so I've modified platformio.ini to only compile the necessary HAL for the specific configuration being compiled.

### CODE REVIEW

**Comment by fiveangle** [comment]
@tcm0116 - can you resubmit to see if Travis issue is cleared up ?  I tried compiling with the options that it choked on, but it worked fine for me on bf20 as of just an hour ago.

We need to get this one into bf20 becasue there are targets that cannot compile in PIO due to errors on the LPC17xx HAL (which they shouldn't be compiling anyway)

**Comment by tcm0116** [comment]
@fiveangle I'll try and get that done this afternoon. I may have to re-work just a bit with the new file layout, but it shouldn't be too difficult.

**Comment by tcm0116** [comment]
@fiveangle @thinkyhead looks like it's passing Travis now

**Comment by p3p** [comment]
3a20ba3 I originally had the specific include of HAL folders in the [platformio.ini](https://github.com/MarlinFirmware/Marlin/commit/b908e38d084377e445428f1053ce24a2a0e6f6ff), all source files inside the HAL_* folders needs to be wrapped in guards for the specific platforms for the Arduino toolchain to work so I removed them to make sure guard omissions are caught in Travis (we had quite a few slip through), was it causing compile issues?

**Comment by tcm0116** [comment]
@p3p no. I just noticed that it was compiling files for HALs that weren't needed by the target. I think this is a better approach than the guards since it makes the HALs more generic if we ever move to something more sophisticated.

**Comment by tcm0116** [comment]
@p3p plus it's possible that someone could miss a guard around a function/file that is unique to a HAL that would pass Travis but potentially result in a larger binary containing functions not really needed.

**Comment by p3p** [comment]
@tcm0116 Nothing is getting compiled that shouldn't. The preprocessor guards completely cover all source files (or should anyway). It is the better approach though, that's why I added them originally, but unfortunately while we support the Arduino toolchain it's better to have missing guards caught by Travis than to slip through silently breaking all builds with Arduino IDE.

**Comment by tcm0116** [comment]
@p3p I hadn't considered compiling with the Arduino IDE. I've reversed the last two commits, so now this PR just moves the framework out of the Marlin folder as a separate library that can have different compiler settings than the main Marlin code.

**Comment by thinkyhead** [comment]
> all source files inside the HAL_* folders needs to be wrapped in guards

Definitely! That's something that we need to go over throughout the source too, but especially in the HAL and other new code. I'll add some notes to the Coding Standards about how to use guards in relation to whole files, generally. Some things to look for…
- Never guard `.h` files. Guard the `#include` instead.
- For platform-specific files, guard the whole `.cpp` file with the platform flag.
- For feature-specific files, include `MarlinConfig.h` first, other `#include`s only if needed.
- If an `.h` file tests for features, include `MarlinConfig.h`, others only as needed.
- etc.…

Anyway, I see this is still getting patched up in real-time, so let me know when you feel it's stable and I will merge it in. Thanks for patching this up!

**Comment by tcm0116** [comment]
@thinkyhead assuming it passes Travis, this should be good to go. I'm going to create a different PR with a bunch of fixes to cleanup all of the warnings that are generated during compilation, and this was just the starting point.

**Comment by thinkyhead** [comment]
Thanks for persevering. Since most work is happening within the HAL folder, I took the opportunity to consolidate the G-codes down to fewer files. Users should be far less likely to hit the compiler limits now.

**Pull request merged**
