### PR TITLE
Adding ukrainian language support

### PR DESCRIPTION
**Pull request by akaJes**
under testing yet

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
That's looking nice, tidy and complete to me.
I can't talk about the language - but the programming seems to be ok.

**Comment by akaJes** [comment]
i have tested it on hardware - everything works fine

**Comment by thinkyhead** [comment]
@akaJes Look at you! This is perfect.

**Comment by akaJes** [comment]
@thinkyhead thank you

**Pull request merged**
