### PR TITLE
Configuration sanity-checking

### PR DESCRIPTION
**Pull request by thinkyhead**
- Add `Conditionals.h` with calculated configuration values
- Add `SanityCheck.h` with checks for configuration errors
- Remove equivalent code from all configurations
- Move error checks from some sources to `SanityCheck.h` also
- Fix initialization of count_direction in stepper.cpp
- Removes almost 400 lines from Configuration files.

### CODE REVIEW

**Comment by clefranc** [comment]
@thinkyhead just uploaded from your repo, printing right now on Prusa i3, so far so good! Will try the delta later...

**Comment by thinkyhead** [comment]
I particularly want to make sure anything I've moved into `Conditionals.h` and `Conditionals_lcd.h` will be truly invariant. Some of the values that are calculated, pins that are set, etc., might in fact be intended to be configurable. I tried to only move the most obvious ones, but some were a little ambiguous.

**Comment by alexborro** [comment]
Nice job @thinkyhead . I would join both Conditionals files.. I see no need for 2 files here. We can separate the content inside the file. 
And what if we include configuration.h and configuration_adv.h at the beginning of config specific files?? After that there will be no need to update dozen config files to add a single feature.

Cheers.

Alex.

**Comment by thinkyhead** [comment]
@alexborro The reason `Conditionals_lcd.h` exists is because some things in `Configuration_adv.h` depend on the LCD defines that are conditionally produced in that file existing.

I like the idea of reducing the contributed configurations. But those are actually meant to stand alone, replacing the configuration files. If we were to make some kind of override system, it would require some kind of default configuration file(s) that are never edited, then the `Configuration.h` file should only contain overrides.

**Comment by thinkyhead** [comment]
One way I can think of to get rid of `Conditionals_lcd.h` would be to allow `Conditionals.h` to be included twice. It can look for a defined macro that only exists in `Configuration_adv.h` and if it isn't there, it will only produce the LCD defines. If it is there, it will skip the LCD defines, but do the rest.

[edit] Done!

**Comment by thinkyhead** [comment]
I'm going to merge this and then we can figure out how it would be possible to make files that only need overrides. The problem I foresee is that the `Conditionals.h` items must be included last, but also ahead of the others, so you would need to do something like:

```
#include "Configuration.h"

// Apply overrides for Configuration.h here

#include "Configuration_adv.h" // which includes "Conditionals.h" at the top

// Apply overrides for Configuration_adv.h here

#include "Conditionals.h"
```

If that's not too ugly, then it should work.

**Pull request merged**
