### PR TITLE
PLR/M43 warnings fixes

### PR DESCRIPTION
**Pull request by tpruvot**

### CODE REVIEW

**Comment by thinkyhead** [comment]
What is the warning? I'd like to avoid trying to allocate over 112 bytes on the stack if the strings we're making are never actually going to be longer than 30 characters. Note that we have 100% control over the sizes of those strings within this method.

**Comment by AnHardt** [comment]
When writing in Chinese every glyph may have up to 3 bytes.

**Comment by tpruvot** [comment]
```
> Marlin/src/feature/power_loss_recovery.cpp: In static member function 'static void PrintJobRecovery::resume()':
> Marlin/src/feature/power_loss_recovery.cpp:249:6: warning: '%s' directive writing up to 104 bytes into a region of size 46 [-Wformat-overflow=]
> void PrintJobRecovery::resume() {
> ^~~~~~~~~~~~~~~~
> In file included from /root/.platformio/packages/framework-arduinoststm32-maple/STM32F1/cores/maple/WString.h:29:0,
> from /root/.platformio/packages/framework-arduinoststm32-maple/STM32F1/cores/maple/wirish.h:47,
> from /root/.platformio/packages/framework-arduinoststm32-maple/STM32F1/cores/maple/Arduino.h:30,
> from Marlin/src/feature/../sd/../inc/../HAL/HAL_STM32F1/../shared/Marduino.h:33,
> from Marlin/src/feature/../sd/../inc/../HAL/HAL_STM32F1/HAL.h:40,
> from Marlin/src/feature/../sd/../inc/MarlinConfig.h:30,
> from Marlin/src/feature/../sd/cardreader.h:24,
> from Marlin/src/feature/power_loss_recovery.h:28,
> from Marlin/src/feature/power_loss_recovery.cpp:31:
> /root/.platformio/packages/framework-arduinoststm32-maple/STM32F1/cores/maple/avr/pgmspace.h:28:37: note: 'sprintf' output between 5 and 109 bytes into a destination of size 50
> #define sprintf_P(s, f, ...) sprintf((s), (f), __VA_ARGS__)
> ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
> Marlin/src/feature/power_loss_recovery.cpp:411:3: note: in expansion of macro 'sprintf_P'
> sprintf_P(cmd, PSTR("M23 %s"), fn);
> ^~~~~~~~~
> 
```

**Comment by thinkyhead** [comment]
> When writing in Chinese every glyph may have up to 3 bytes.

I'll tweak the code soon so it only allocates the space required, by checking the `strlen_P` from any string that will be used in a `printf("... %s", ...)` situation.

**Pull request merged**
