### PR TITLE
Add meatpack serial packing

### LINKED ISSUE #20768: [FR] Interest in an on-the-fly serial/g-code compression technique from Prusa's FW? Existing PR...
### Description

I designed an implemented a simple but effective way to compress g-code over the serial connection by a factor of ~0.61, with no computational cost to the firmware. I've also written an associated OctoPrint plugin that compresses the data from the PC-side automatically, and manages the configuration state between firmware and PC.

It was noted by a few people this could benefit many other printers with slower MCUs, which may struggle to keep up with fast printing on low baud-rate serial connections.

### Feature Workflow

Please see the Prusa Firmware PR here: https://github.com/prusa3d/Prusa-Firmware/pull/2955

If there is interest, I will make the associated modifications to the Marlin FW. I will need someone to test with OctoPrint (with the associated plugin), as I do not have another printer with which I can flash Marlin.

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Quick attempt at adding meatpack serial packing to marlin2. [Concise Diff](20802/files?w=1)
Space removal added
I don't have a way to test this at the moment.

### Requirements

#define MEATPACK and something to pack the data at the sending end. Currently only the octoprint plugin [OctoPrint-MeatPack](https://github.com/scottmudge/OctoPrint-MeatPack/)

### Benefits

Faster data rate for serial communications, particularly useful for UART based serial

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/20768

### CODE REVIEW

**Review by nasseralmohr3600 — APPROVED** [review]

**Comment by thinkyhead** [comment]
I've been reading the packing code and it seems to be pretty simplified. From what I can gather this is the whole format that the plugin's packing script produces:

- Start the file with `0xFF` `0xFF` `0xFB` ("packing enabled" command)
- Whole line comments are left intact
- Pack up the bytes in one of three ways:
  - Neither character is packable: `0xFF` `0x##` (not `0xFF`) `0x##`
  - First character is packable: `0x#F`  (not `0xFF`) `0x##`
  - Second character is packable: `0xF#`  (not `0xFF`) `0x##`
  - Two packable characters: `0x##` (two packed chars, not `0xF#` or `0x#F`)
- End the file with `0xFF` `0xFF` `0xF9` ("reset device state" command)

That should pack most commands down very well, except maybe the occasional `M117` command….

The unpacking code looks perfectly good to me when I run it in my head. I have an OctoPrint setup and can give it a try soon.

I guess it doesn't make too much sense to worry about implementing it for SD printing, but that wouldn't be too hard to add if someone wants it.

**Comment by ellensp** [comment]
next version strips white space from G0-9 ie all low gcodes..

**Comment by ellensp** [comment]
Now with support for space removal. NB needs re tested. When this was tried on prusa firmware  eg G1 X40 Y20 E12  became G1X40Y20E12 and Y was incorrectly interpreted as Y20<sup>12</sup> (ie 20 to the power of 12) .

**Comment by thinkyhead** [comment]
> Y was incorrectly interpreted as Y2012

Haha. Marlin knows to replace the E before interpreting the number.

**Comment by scottmudge** [comment]
Thanks for migrating, integrating, and merging.

**Pull request merged**
