### PR TITLE
Fix BLTOUCH and FAN PWM conflicts on SKR E3 v2 boards

### PR DESCRIPTION
**Pull request by Asterchades**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description
Corrects the same issue as #15547 on the newer SKR Mini E3 v2 boards. Also re-ordered the conditions to put all the SKR Mini E3s together, though that has no functional benefit (though if someone knows how to wild-card the condition it could be more evident what needs to be included).

### Benefits
Prevents some Z probes (notably certain BLTouch clones) from deploying randomly when the PWM fan is triggered while using a newer BTT SKR Mini E3 v2 board. Prevents damage to both the print and probe. Tested for over an hour with zero random deployments mid-print.

### Configurations
N/A

### Related Issues
None listed. Personal issue encountered during recent experiments which, given the previous issue, is likely to impact other users with similar configurations.

As per discussion in my misplaced original pull request (https://github.com/MarlinFirmware/Marlin/pull/19205) this snippet may be complete but there should be alterations made following. In specific, the Mini E3 v2 does _not_ use PA8 for the FAN_PIN, rather they use PC6 as mentioned by @thisiskeithb.

### CODE REVIEW

**Comment by Asterchades** [comment]
OK... I can't figure out this whole "pull" system. I wanted to push one - just one - change. A single line in a single file. Why it's saying 78 is well and truly beyond me. Feel free to edit, remove, whatever is required as I give up.

**Comment by AnHardt** [comment]
Update your "bugfix-2.0.x".
Brach from "bugfix-2.0.x" not "2.0.x".
Make your changes.
Send a PR against "MarlinFirmware:bugfix-2.0.x"

Else you are sending a PR to *downgrade* "bugfix-2.0.x" to ("2.0.x" plus your changes).

**Comment by Asterchades** [comment]
Gotta be honest... this whole process is more annoying than it was chasing the probe around the print bed with a piece of electrical tape when I discovered the problem. Where the option to just pick a file, hit "edit", and say "I want to make this change"?

**Comment by AnHardt** [comment]
It's  just the first times.
After a while it's just as 'natural' as saving a file after editing it.

**Pull request closed without merging**
