### PR TITLE
[2.0.x] Add LCD controller conditionals

### PR DESCRIPTION
**Pull request by thinkyhead**
Currently Marlin does conditional compilation based on the type of LCD controller, distilled down to a few basics like `ULTRA_LCD`, `ULTIPANEL`, `NEWPANEL`, `DOGLCD`, etc.

This PR adds conditionals more indicative of actual functionality:

conditional|description
---|---
`HAS_SMART_LCD`|An LCD whose content can be changed
`HAS_GRAPHIC_LCD`|A graphical LCD whose content can be changed
`HAS_CHARACTER_LCD`|A character-based (HD44780) display
`HAS_LCD_DISPLAY`|An LCD display whose contents may or may not be altered
`HAS_LCD_ENCODER`|An LCD with some kind of encoder
`HAS_BUTTONS`|An input device with at least one button
`HAS_LCD_MENU`|Has Marlin custom menus (not just status screen)
`HAS_RESUME_CONTINUE`|Has a button or `M108` to break out of wait loops

Conversion to these conditions is partial, but will be filled in as this PR develops.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I like the direction....  But can we chop out some of the granularity to make it easier to understand?   For starters...   When don't we have a "HAS_SMART_LCD" ?   If the display can't be changed...   I'm thinking we don't have an LCD.   

The "HAS_GRAPHIC_LCD" and "HAS_CHARACTER_LCD" is valuable!  But I would change the defination to be whether it is bit mapped graphics or if it is displaying pre-defined (and user configurable) character  cells.  This is important to know just because of the amount of time it takes to update the display.

Etc...

But let's ditch all the existing "ULTRA_LCD, ULTIPANEL, NEWPANEL, DOGLCD,"  control names!!!!!

**Comment by thinkyhead** [comment]
Well, some of these pre-existing items have specific meanings and can't be entirely eliminated. For example, `NEWPANEL` indicates that the controller is derived from the old-style Ultimaker Panel and uses a shift register, in contrast to the newer style Ultimaker Panel that is like most current displays, with `EN1`, `EN2`, and `ENC` pins for a click-wheel. So there's still value for the pins files and the `ultralcd.*` code to refer to `NEWPANEL` by name. The higher-level code can skip it.

If the only concern in a block of code is that there be something for the user to click it can simply refer to `HAS_BUTTONS`. For wait loops that should be allowed to be canceled, `HAS_RESUME_CONTINUE` is more appropriate.

The `HAS_SMART_LCD` define doesn't cover every single type of display. It is distinct from the emerging class of touch-screens that simply send G-code. The only one we currently support is the `MALYAN_LCD`, but we can expect more (Nextion, etc.) to be integrated as time goes on. While dumb touch displays can't implement custom menus or full-screen graphics, they can display alert messages, a status line, and even SD card listings.

`HAS_LCD_DISPLAY` indicates that there is _some_ kind of LCD display, either a smart display or a dumb touch display. This will go away if it doesn't end up being useful.

`HAS_BUTTONS` covers any device that has buttons, including a keypad with no display. This will be false for LCDs such as a simple 16x2 display that has no interface.

`HAS_LCD_MENU` will be set for most common controllers, but will be false if the menus are disabled with `NO_LCD_MENUS`, or if the display is incapable of implementing them like the `MALYAN_LCD`. It also indicates there's no way to go to extra screens for informational display.

And the old `HAS_RESUME_CONTINUE` setting has the same meaning as before: that there is some way for users to indicate continue, whether `M108` or some kind of button.

Can `DOGLCD` be replaced entirely by `HAS_GRAPHIC_LCD`? Possibly. I'm pretty sure at this point that the generic `DOGLCD` option can be removed from `Configuration.h`. But it may be useful in future for some no-name generic graphical display.

**Comment by landodragon141** [comment]
My 2¢, let's get rid of DOGLCD if we can. Those of us that have been using Marlin for a long time know what it is but it isn't an intuitive name for a newbie. I think that Software robustness and ease of use are the most important things in the reprap world as we seek to become accessible to more people.

**Comment by Roxy-3D** [comment]
> My 2¢, let's get rid of DOGLCD if we can. 

Agreed...   And I don't know that we care if the the LCD Panel has a shift register or not.   Presumably...  the driver code should make it functional.    

Some code is going to want to be able to differentiate between a graphical or character cell based display.    It would be good to have a clean way of knowing that.

**Comment by thinkyhead** [comment]
> let's get rid of DOGLCD if we can.

I think we're in luck, and `DOGLCD` can be removed from `Configuration.h` since it doesn't really mean anything by itself. I'll do that as part of the config cleanup.

> I don't know that we care if the the LCD Panel has a shift register or not

Shift register panels get different pin assignments for the controller part, and additional initialization code for those pins.

**Comment by marcio-ao** [comment]
> If the display can't be changed... I'm thinking we don't have an LCD.

@Roxy-3D: In our lab, I have a printer where the LCD was disconnected internally because we were testing it with a board that did not support that particular display. So I took a picture of the LCD from a working printer, printed out a paper copy in color and pasted it over the inactive display. It was realistic enough that I fooled one of my co-workers as he was walking by.

So yeah, displays that can't be changed do exist, but mostly as a practical joke :)

**Pull request closed without merging**
