### PR TITLE
Fix SKR Mini E3 V2 EEPROM

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Fix sporadic EEPROM errors on the SKR Mini E3 V2.

### Requirements

SKR Mini E3 V2-based build.

### Benefits

Users won't have to disable the onboard EEPROM.

### Configurations

Any SKR Mini E3 V2-based build, but this will work: https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%202.0

### Related Issues

#22524

### CODE REVIEW

**Comment by Zwaubel** [comment]
@thisiskeithb 
This fix does break _maple targets. 
SDA and SCL are not defined and the following errors are thrown during the build process:
```
In file included from Marlin\src\HAL\shared\../../inc/../pins/pins.h:521:0,
                 from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:34,
                 from Marlin\src\HAL\shared\eeprom_if_i2c.cpp:28:
Marlin\src\HAL\shared\../../inc/../pins/stm32f1/pins_BTT_SKR_MINI_E3_V2_0.h:33:44: error: 'SDA' was not declared in this scope
   #define I2C_SDA_PIN                      SDA
                                            ^
Marlin\src\HAL\shared\eeprom_if_i2c.cpp:36:36: note: in expansion of macro 'I2C_SDA_PIN'
   SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
                                    ^~~~~~~~~~~
Marlin\src\HAL\shared\../../inc/../pins/stm32f1/pins_BTT_SKR_MINI_E3_V2_0.h:34:44: error: 'SCL' was not declared in this scope
   #define I2C_SCL_PIN                      SCL
                                            ^
Marlin\src\HAL\shared\eeprom_if_i2c.cpp:36:49: note: in expansion of macro 'I2C_SCL_PIN'
   SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
                                                 ^~~~~~~~~~~
Marlin\src\HAL\shared\../../inc/../pins/stm32f1/pins_BTT_SKR_MINI_E3_V2_0.h:34:44: note: suggested alternative: 'SCK'
   #define I2C_SCL_PIN                      SCL
                                            ^
Marlin\src\HAL\shared\eeprom_if_i2c.cpp:36:49: note: in expansion of macro 'I2C_SCL_PIN'
   SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
                                                 ^~~~~~~~~~~
```
   
While using the _maple target together with an Ender 3 V2 and the SKR Mini E3 V2 I never experienced the issue described in  #22524. It seems the OP of the corresponding thread never had the issue when using _maple either.

**Comment by thisiskeithb** [comment]
> While using the _maple target together with an Ender 3 V2 and the SKR Mini E3 V2 I never experienced the issue described in #22524. It seems the OP of the corresponding thread never had the issue when using _maple either.

Maple environments will be deprecated, but I’ll see if there’s a way to make it work for both for now.

**Comment by thisiskeithb** [comment]
@Zwaubel: Can you [open an issue](https://github.com/MarlinFirmware/Marlin/issues/new/choose) so it can be tracked?

**Comment by Zwaubel** [comment]
done - see #22952


Additionally, I have no problem with switching to the normal stm32f1.. target. 
I started using the maple target only because it seemed like a better performing framework quite a while ago.
But as there has been quite a lot of development for the stm32f1, the 'normal' target seems to have matured a lot. My knowledge about the which dial to turn in the config and slicer settings probably did so, too.

**Comment by Pseudostud** [comment]
I attempted to compile Marlin 2.0.9.2 tonight to update my CR-10/SKR Mini E3, and I got the maple compile errors listed in the comments above. I had to comment lines 31, 33-34 to get a successful build on STM32F103RC_BTT_maple. The STM32F103RC_btt_512K has been deprecated, so maple is the only option for those who have updated PIO.

pins_lines

**Comment by thisiskeithb** [comment]
@Pseudostud: This has been fixed in the latest bugfix.

Also, you should not build with the maple environments as they are legacy and will be phased out.

**Pull request merged**
