### PR TITLE
General option PAUSE_BEFORE_DEPLOY_STOW

### PR DESCRIPTION
**Pull request by thinkyhead**
Convert the fix-mounted-only option to pause for probe preparation ("probaration"?) to a general option that can be applied to any chosen probe.

- Convert `MANUAL_DEPLOY_STOW` to `PAUSE_BEFORE_DEPLOY_STOW`.

Reference: https://github.com/MarlinFirmware/Marlin/pull/11899#issuecomment-423866766

### CODE REVIEW

**Comment by brandstaetter** [comment]
it's still only applied to fix mounted probes though

edit: never mind, should not comment before first coffee.

**Comment by thinkyhead** [comment]
Should be ready to go, methinks!

**Comment by brandstaetter** [comment]
I'll do a quick test on my machine

**Comment by brandstaetter** [comment]
Seems to work perfectly.

**Comment by AnHardt** [comment]
Thanks.

**Pull request merged**
