### PR TITLE
Animated boot screen

### PR DESCRIPTION
**Pull request by N95JPL**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Adding a base script to enable custom bootscreen animations on DOGM LCD Screens. (More to follow)
Supporting up to 10 frames (At the suggested 100ms would make a 1 second animation which is then held for the "CUSTOM_BOOTSCREEN_TIMEOUT" delay.
Can be fully disabled by the "#define CUSTOM_BOOTSCREEN_ANIMATION" setting.

### Benefits

Fix: Nothing
Improve: I've seen a large interest in Animated Bootscreens, more for fun than practical use of the 3D Printer. Can be personalized to the users wants/needs.

### Related Issues

My own feature request (Seeking approval)

Thanks,
Joshua N Pope-Lewis

### CODE REVIEW

**Comment by N95JPL** [comment]
Ooops, sorry about the title!
I see thinkyhead has modified, Thanks!

**Comment by thinkyhead** [comment]
I assume this is not in any way meant to be merged, because it would break Marlin.

**Comment by N95JPL** [comment]
Sorry? I don't follow you - I have this working on my version of Marlin?
It's also passed all the checks (below?)

**Comment by thinkyhead** [comment]
You've added a `_Bootscreen.h` file to the root of the Marlin folder. Should everyone who downloads Marlin from now on have this file in the root of the Marlin folder?

**Comment by N95JPL** [comment]
Oh dear - No sorry that was meant to be an example - I can remove that.
It isnt required to build whilst animation & custom bootscreen is disabled.

**Comment by thinkyhead** [comment]
Although you added new options to one `Configuration.h` file, you didn't add the same options to all the other `Configuration.h` files in the `config` folder. That would also be required for this to be complete.

But anyway, don't do that. I have some suggested updates that I will push shortly.

**Comment by N95JPL** [comment]
Okay - I can surely arrange that.
Thanks, I look forward to looking at them.

**Comment by thinkyhead** [comment]
Here's the gist of the added commit:
- Move bootscreen settings into the bootscreen file so they go along with it
- Move the bootscreen file into the examples folder
- Put the animation frames into an array for easier animation
- Modify the code to use the frames array, automatically picking up the frame count
- Make an inline function to draw a single bootscreen (or frame) for reuse
- Use only the last animation frame if `ANIMATED_BOOTSCREEN` is commented out
- Reduce the size of the bitmaps by removing empty top/bottom lines (-560 bytes)

**Comment by N95JPL** [comment]
Thats absolutely perfect - I have fixed a small compiling issue with the way the const array was constructed (See merge)
I have now uploaded onto my TEVO Tornado and it works perfectly.

I'm not able to test the LPC1768 - So unsure what the issue is there?
The 2560 failed due to a timeout?
Using Arduino 1.9.0 its compiled and uploaded successfully.

**Pull request merged**
