### PR TITLE
Filament management via LCD 

### PR DESCRIPTION
**Pull request by maverikou**
Based on on https://github.com/lajos/Marlin/commits/tantillus

Is this interesting to anyone?

### CODE REVIEW

**Comment by thinkyhead** [comment]
With various functions being added that load and unload filament and do other lengthy operations, it seems like we should talk about how they can show progress during these processes, and how we can make them easy to interrupt – at least using the LCD. In my own setup I use GCode files named "load" and "eject" which could do one very long move, but instead they are broken up into hundreds of smaller moves so that they can be canceled with "Stop SD Print," and they contain M117 messages that continually display the amount of filament remaining to be loaded/ejected.

**Comment by boelle** [comment]
Please rebase, the code cant be merged as is

**Comment by se3d** [comment]
Maybe a Filament Count (configuring the size of filament by menu)? This can be used for maintence print alert for example.

**Comment by Nandox7** [comment]
Why not follow the workflow existing in the bQ fork of Marlin?
- Filament Load/Unload:
- \- Load Filament
- \- Unload Filament

Then both actions ask for needed temperature and waits until that temp is reached to initiate the action.
It's simple to use and no need to weird actions, only code needed apart from the menu implementation is the one that keeps track of the current nozzle temperature.

**Pull request closed without merging**
