### PR TITLE
Fix CR10 Stock Display timing with SKR_PRO V1.1

### PR DESCRIPTION
**Pull request by dan-and**
### Requirements

SKR Pro v1.1 and the CR10 Display (as used on CR10, Ender 3, Ender 5 etc.) 

### Description

Using the BIGTREETECH SKR Pro v1.1 and the Creality CR10 StockDisplay (Also used on Ender 3 / 5) the timings are off and the display will show pixel garbage only. So just for the CR10 StockDisplay an undef of the timings, will allow setting them as used for other display. 

### Benefits

CR10 Displays will work on SKR Pro v1.1

### CODE REVIEW

**Comment by sl1pkn07** [comment]
Hi

What gerbage you mean? when power on the machine? This can be apply on other boards? have a garbage in the LCD in my ReARM with stock Ender3 LCD connected on the J3 pinhead when power on my machine. After some seconds, apears the marlin bootscreen and runs with normality

example https://www.youtube.com/watch?v=a3HgWvxrc_U

greetings

**Comment by dan-and** [comment]
I have no photo by hand, but the LCD will not work fine after a few seconds, since the timings are off. 
The issue have been discussed on reddit as well (not my account): https://www.reddit.com/r/3Dprinting/comments/d9ttxj/trying_to_configure_skr_pro_v11_for_ender_3/ 

The "fix" which goes around on this is fixing in the  Marlin/src/inc/Conditionals_LCD.h which is not a good idea because it would change things globally, when the issue only occurs on the SKR PRO v1.1. 

So sorry that I have no fix for your ReARM effect.

**Comment by sl1pkn07** [comment]
i have tested in my copy. unfortunately, do nothing :(

i'm not sure if the file structure is related. because is different (the LCD part) than skr_pro pins file

i need test more

greetings

**Comment by dan-and** [comment]
> i have tested in my copy. unfortunately, do nothing :(
Because this is a different issue instead of your problem.

**Comment by sl1pkn07** [comment]
oks. thanks

**Comment by sjasonsmith** [comment]
> The "fix" which goes around on this is fixing in the Marlin/src/inc/Conditionals_LCD.h which is not a good idea because it would change things globally, when the issue only occurs on the SKR PRO v1.1.

That was my suggestion. It took my quite a while to figure out what was going on, and to realize that the timings in the pin file were not being used. I don't think a universal override should exist, if it doesn't work universally. If different HALs/Boards need different timing, then the values should be in the HAL/Board. It probably impacts other users as well, just you and me noticed it on an SKR Pro. The default values would make sense if applied elsewhere in the code, that is only considered after all other headers are included, so that it can still be set by the HAL or pins file.

I didn't submit a Pull Request to remove those defines, because as you mentioned, it would probably break some people. Everyone with a MELZI_CREALITY board would be fine, because it defines timings in the pins file, but that isn't true for every controller out there.

My preference would be to "rip off the band-aid" and remove the timing defines from Conditionals_LCD.h. They are only going to cause more problems as more users move to 32-bit boards with various processors on them. It is worth nothing that this is the only display which alters timings inside Conditionals_LCD.h.

A compromise could be to move the overrides into the Configuration.h file, so they can be easily seen and modified. I don't love it, but at least it would be more transparent than the current behavior.

```
#define CR10_STOCKDISPLAY
#if ENABLED(CR10_STOCKDISPLAY)
  // Default timings for CR-10 display with a stock control board.
  // Comment out to use settings from HAL or pins file.
  #define ST7920_DELAY_1 DELAY_NS(125)
  #define ST7920_DELAY_2 DELAY_NS(125)
  #define ST7920_DELAY_3 DELAY_NS(125)
#endif
```

**Comment by sjasonsmith** [comment]
Another option could be to remove the defines, and rename CR10_STOCKDISPLAY. An informational message could then be added in SanityCheck.h, telling people what to check to get their display working again.

**Comment by dan-and** [comment]
@sjasonsmith 
> I didn't submit a Pull Request to remove those defines, because as you mentioned, it would probably break some people. 

That's why I added it to the SKR_PRO pins definition. It is occurring only on SKR_PRO with CR10 display and it is fixed there.

**Pull request merged**
