### PR TITLE
Lin Advance K per extruder

### PR DESCRIPTION
**Pull request by GMagician**
#24819 implementation

### CODE REVIEW

**Comment by thinkyhead** [comment]
For consistency (?) I made `DISTINCT_E_FACTORS` apply to the Linear Advance K factor since it (more or less) fits into the same family as other E motion values like `axis_steps_per_mm`, `max_feedrate_mm_s`, etc. After this change, if `DISTINCT_E_FACTORS` is disabled, only a single K value exists, and it applies to all extruders.

**Comment by GMagician** [comment]
> since it (more or less) fits into the same family as other E motion values like `axis_steps_per_mm`, `max_feedrate_mm_s`, etc. 

~~I was thinking that K factor was related to material and/or bowden lenght, then 2 extruders, with maybe the same steps will may require different K values...my poor knowkledge...~~

ok, my fault, I read code and turn out that:
`#define DISTINCT_E E_STEPPERS` so its what I was expecting

**Comment by GMagician** [comment]
...not clear... if someone has 3 extruders and no DISTINCT_E_FACTOR than DISTINCT_E is 1.
LCD will edit just K[0]: `EDIT_ITEM(float42_52, MSG_ADVANCE_K, &planner.extruder_advance_K[0], 0, 10);`
`extruder_advance_K[]` array will have 1 element but  shouldn't these 3 extruders have a K value each?

**Comment by thinkyhead** [comment]
I was more concerned about `DISTINCT_E` being 0 but it appears we have that covered, and it will not be less than 1.

**Comment by GMagician** [comment]
> ... but shouldn't these 3 extruders have a K value each?

Should I change back to EXTRUDERS?

**Comment by thinkyhead** [comment]
> if someone has 3 extruders and no `DISTINCT_E_FACTOR` [then] `DISTINCT_E` is 1.

With the distinct option left off, we should expect there to be a single K factor that can be set at any time (for the current tool) without specifying an index, applying to all tools until altered.

**Comment by fnsign** [comment]
I receive following warning:
Marlin/src/gcode/feature/advance/M900.cpp: In static member function 'static void GcodeSuite::M900()':
Marlin/src/gcode/feature/advance/M900.cpp:52:23: warning: unused variable 'tool_index' [-Wunused-variable]
   52 |     constexpr uint8_t tool_index = 0;

unused variable 'tool_index' [-Wunused-variable] [Ln 52, Col 23]

**Pull request merged**
