### PR TITLE
Fix for TFTGLCD Panel

### PR DESCRIPTION
**Pull request by Serhiy-K**
### Description

- I added a new `CLR_SCREEN` command to protocol to reduce bus traffic.
- The call of the `WRITE` macro has been replaced by a call `extDigitalWrite` function, since for some boards the pin corresponding to `TFTGLCD_CS` may be described as analog in the `variant.h` file and the `WRITE` macro does not work correctly. For example it present for Generic_F4xxxx boards.
- Fix for some boards.

### CODE REVIEW

**Comment by thinkyhead** [comment]
> …for some boards the pin corresponding to `TFTGLCD_CS` may be described as analog in the `variant.h` file…

How is `extDigitalWrite` (usually an alias of `digitalWrite`) able to distinguish between the integer value of `TFTGLCD_CS` being an analog index value versus a digital I/O pin number? Why is a "CS" pin –a digital function– described in terms of an analog pin index?

**Comment by Serhiy-K** [comment]
Perhaps I did not quite correctly formulate the phrase.

I use "Black Pill" board with STM32F411 MCU. In my `pins_PILL_F401XX.h` file `TFTGLCD_CS` pin defined as **PA4** in format as other pins.  In `variant.h` file for `Generic_F401Cx` board pins from **PA0** to **PA7** defined as **A0**-**A7**, not 0-7 as for digital pins. In this case **A0**=**NUM_ANALOG_FIRST**=**(NUM_DIGITAL_PINS + 1)**=**36 !!!** for this board. 

`WRITE(IO,V)` macro  uses `STM_PIN(X)`  which returns **0** when **X>0xF** - our **An** pin from `variant.h` file. Therefore `WRITE(IO,V)` actually switches **PA0** pin, not **PAn**.

`digitalWrite` uses `digitalPinToPinName` macro which sets GPIO right.

**Comment by thinkyhead** [comment]
That's screwy. The reason I want to preserve `WRITE` is that it's optimal for most platforms. But this implies that for certain platforms the use of `WRITE` is broken. Perhaps there is some way to detect that `A0`-`A7` is being passed into `WRITE` and this can be converted to the appropriate DIO. This will allow the new code to be used optimally even with AVR boards.

**Comment by Serhiy-K** [comment]
Maybe just replace `STM_PIN(X)` in `WRITE(IO,V)` to `digitalPinToPinName(p)` which works good?

**Comment by thinkyhead** [comment]
> Maybe just replace `STM_PIN(X)` in `WRITE(IO,V)` to `digitalPinToPinName(p)` which works good?

I have made this change now. Please confirm that it works properly. I should do some builds to compare sizes, since my changes seem to have some effect on the build size.

**Comment by Serhiy-K** [comment]
I made small changes and tested with LPC1768, STM32F103 and STM32F411. Now `WRITE` with STM32F4xx works well.

I changed **digitalPinToPinName(digitalPin[IO])** to **digitalPinToPinName(IO)** in `fastio.h` for STM32. In debug mode I saw no differences, but I think it's easier.

**Comment by thisiskeithb** [comment]
Looks like this had some unintended consequences: https://github.com/MarlinFirmware/Marlin/issues/19677

**Pull request merged**
