### PR TITLE
Compiler warnings  ' filament runout char size)

### PR DESCRIPTION
**Pull request by studiodyne**
Compiler warning  truncated string ! Because need one char more !

### CODE REVIEW

**Comment by sjasonsmith** [comment]
@studiodyne can you provide a configuration which exhibited problems with this? I can't reproduce the warning. Perhaps it has already been fixed in another way.

It initially made sense that this could be off by one, but during the print the `%c` is replaced by the extruder number. Since that is a single digit it actually does still have room for NUL termination.

I tried building for AVR and STM32, and neither produced any compiler warnings with the configuration I created.

**Comment by studiodyne** [comment]
@sjasonsmith 
Hi , i have made two files in my account ,   compilerwarning and compilernowarning , you must use ' rumba32'

It's about the process of the runout script. Some ' M600' or anything like is expected , but i use my own script that do pause + sms + other , and it's when we use personnal scripts . Marlin code doesn't made for personnal script, but by adding one char, all is perfect

thks

**Comment by thisiskeithb** [comment]
> Hi , i have made two files in my account , compilerwarning and compilernowarning , you must use ' rumba32'

Using your configs from https://github.com/studiodyne/Marlin/tree/compilerwarning on current `bugfix-2.1.x`, I had to disable `DEACTIVATE_SERVOS_AFTER_MOVE` as required by the sanity check.

<details><summary>I get the following warnings:</summary>
<p>

```prolog
In file included from /.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/WString.h:29,
                 from /.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/Print.h:27,
                 from /.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/Stream.h:26,
                 from /.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/HardwareSerial.h:29,
                 from /.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/WSerial.h:5,
                 from /.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/wiring.h:47,
                 from /.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/Arduino.h:36,
                 from Marlin/src/feature/../sd/../inc/../HAL/../HAL/STM32/../shared/Marduino.h:36,
                 from Marlin/src/feature/../sd/../inc/../HAL/../HAL/STM32/HAL.h:27,
                 from Marlin/src/feature/../sd/../inc/../HAL/HAL.h:30,
                 from Marlin/src/feature/../sd/../inc/MarlinConfig.h:33,
                 from Marlin/src/feature/../sd/cardreader.h:24,
                 from Marlin/src/feature/runout.h:28,
                 from Marlin/src/feature/runout.cpp:31:
Marlin/src/feature/runout.cpp: In function 'void event_filament_runout(uint8_t)':
Marlin/src/feature/../inc/../../Configuration.h:1920:34: warning: 'snprintf' output truncated before the last format character [-Wformat-truncation=]
 1920 |   #define FILAMENT_RUNOUT_SCRIPT "M7\nG4S2\nM9\nM125T"
/.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/avr/pgmspace.h:30:20: note: in definition of macro 'PSTR'
   30 | #define PSTR(str) (str)
      |                    ^~~
Marlin/src/feature/runout.cpp:138:21: note: in expansion of macro 'F'
  138 |         script.setf(F(FILAMENT_RUNOUT_SCRIPT), AS_CHAR(tool));
      |                     ^
Marlin/src/feature/runout.cpp:138:23: note: in expansion of macro 'FILAMENT_RUNOUT_SCRIPT'
  138 |         script.setf(F(FILAMENT_RUNOUT_SCRIPT), AS_CHAR(tool));
      |                       ^~~~~~~~~~~~~~~~~~~~~~
/.platformio/packages/framework-arduinoststm32@4.10900.200819/cores/arduino/avr/pgmspace.h:74:39: note: 'snprintf' output 17 bytes into a destination of size 16
   74 | #define snprintf_P(s, n, ...) snprintf((s), (n), __VA_ARGS__)
      |                               ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
Marlin/src/feature/../sd/../inc/../core/mstring.h:70:28: note: in expansion of macro 'snprintf_P'
   70 |   #define SNPRINTF_P(V...) snprintf_P(V)
      |                            ^~~~~~~~~~
Marlin/src/feature/../sd/../inc/../core/mstring.h:152:52: note: in expansion of macro 'SNPRINTF_P'
  152 |   MString& setf_P(PGM_P const fmt, Args... more) { SNPRINTF_P(str, SIZE, fmt, more...); debug(F("setf_P")); return *this; }
```

</p>
</details>

So the warnings have been confirmed.

> It's about the process of the runout script. Some ' M600' or anything like is expected , but i use my own script that do pause + sms + other , and it's when we use personnal scripts . Marlin code doesn't made for personnal script, but by adding one char, all is perfect

I just tested `#define FILAMENT_RUNOUT_SCRIPT "M7\nG4S2\nM9\nM125T"` using a different board (SKR 3), and it compiles without these warnings, so this seems to be a board/framework-specific issue.

**Comment by ellensp** [comment]
Config has #define EXTRUDERS 2

With NUM_RUNOUT_SENSORS  > 1 (you have it set to EXTRUDERS, ie 2) the FILAMENT_RUNOUT_SCRIPT **requires** the %c parameter so that the tool that triggers the run-out is known

With   #define FILAMENT_RUNOUT_SCRIPT "M7\nG4S2\nM9\nM125T%c"  there is no warning. 


There is a preflight that check for this common miss configuration, but since you removed M600 from the script, the preflight check did not see this

**Comment by studiodyne** [comment]
@ellensp 🥇

**Pull request closed without merging**
