### PR TITLE
Added z offset to mesh leveling

### PR DESCRIPTION
**Pull request by epatel**
Added z offset to mesh leveling, and display option with G29 S4. Also described in docs.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Note that I've added `M420` and `M421` to support mesh (and other kinds of) bed leveling, and as part of the PR that makes it possible to reproduce all EEPROM settings in GCode. #1974 So, if you add new EEPROM options to MBL, you should make sure to add support either by extending `M420` or by adding a new command `M422`. Check `configuration_store.cpp` for all the latest changes, particularly in the `M503` function, `Config_PrintSettings`.

**Comment by epatel** [comment]
Looking at this now. I guess you haven't tried it as it did not compile (when enabling MESH). I also imagine outputting X/Y positions and then trying to get indexes back can be an area of error. (select_x/y_index() was only designed for the bi-linear calculations). i.e one would never be able to get index of the last index as the resulting index must have one more point to be able to calculate a line between the two points.
Think I'll just output indexes.

**Comment by thinkyhead** [comment]
Aha, I fixed the compile error in #2001 also.

**Comment by boelle** [comment]
does this one still need to be updated?

**Comment by thinkyhead** [comment]
@boelle @epatel Yes, I think the `M420` part needs some more consideration and discussion so that it can be generalized for other leveling systems. I find it makes more sense to store the actual X, Y values instead of the indices; that way if the code is recompiled using different mesh XY positions (but the same number of indices) the EEPROM code can take note of the difference and re-initialize those points rather than treating them as the same points.

And, while the methodology used in `G29` to invoke itself in different stages is sound within the scope of G-code syntax, I think the last addition – setting the Z offset for mesh bed leveling – might be stretching `G29` one step too far outside the familiar specification for `G29`, and we should consider using a new code for it, perhaps `M422` or `M852`.

Also, the EEPROM version might need to be bumped to "V21" for the new z offset, because I think it was recently bumped to "V20" to handle the change in sign of `zprobe_zoffset`.

**Comment by epatel** [comment]
I added the `G29` as it makes it possible to fine-tune the levelling apart from the measuring. The measuring will give a mesh that does the overall compensation but it can be off slightly up/down from the measuring method. By setting an overall z-offset it can be fine-tuned. If `G29` is good or bad for this I don't know. It is definitely different from the "other" levelling method/s. This is a new way to level and I think it will need to be configured and added in controller softwares as OctoPrint when they seem it fit, or not. Until then it is pure manual to its nature. I could perhaps add an automatic version, but I need to get my hands on a machine with those parts. I seldom program in the blind without being able to test what I have written.

I don't think its good to store the actually X/Y values as I have described earlier, i.e. you will not be able to get the right indexes with that method.

**Comment by thinkyhead** [comment]
@epatel Well, `M48` is meant to help fix up repeatability problems. And if you aren't getting the right Z values across the whole bed, well you can already change the `zprobe_zoffset` to compensate.

**Comment by thinkyhead** [comment]
> you will not be able to get the right indexes with that method

"Not be able" is stretching it, and remember you're talking to a coder! To me it looks like a nice one-hour programming challenge. The heuristics to figure out the indices are fairly simple, and if for some reason it just can't figure them out, well it can reject them and clear the matrix, just as with any too-large configuration change.

**Comment by epatel** [comment]
About `zprobe_zoffset`, it seems only to be used when `ENABLE_AUTO_BED_LEVELING` is enabled. Which should not be enabled when using the mesh method.

About the indexes, sure you might come up with some interpolation method, anything is possible. I am a coder too ;) What I meant is that how you wrote it today I can't see how it will fly. As I mentioned earlier you won't even be able to reach the last index. I'd think its not worth pursuing, what problem are you solving? Saving "text" config, re-compile Marlin with a different mesh size config, and then reading the saved "text" config? and then expect that to work without any problem? Why change the mesh size anyway if one want to keep the measurement? Keep it simple and save your time! I'd say, changing mesh size will require re-measuring is an acceptable requirement. But hey, thats me, and I am actually using these parts. 

I wish I had a machine with some auto level details so I could add that part in the code. Might design my own sensor just for this.

**Comment by thinkyhead** [comment]
> zprobe_offset

Well, that can certainly be remedied! I see no reason not to include it with both.

**Comment by thinkyhead** [comment]
> what problem are you solving?

Unification of probed mesh points into a single G-Code. If Mesh Bed Leveling used points instead of indices then it wouldn't be necessary to figure out indices. And if Auto Bed Leveling used indices instead of points, then I could store indices instead of points. But, for maximum compatibility (and to get the most useful output from `M501`) it seems most prudent to store the actual probed points.

**Comment by boelle** [comment]
the build failed, please rebase on latest devlopment

**Pull request closed without merging**
