### PR TITLE
Updated Azteeg X5 Mini Wifi pins for onboard SD

### PR DESCRIPTION
**Pull request by ModMike**
**Requirements**

Azteeg X5 Mini Wifi
Marlin 2.0.x Bugfix

**Description**

Fixed servos pin and added support for new CMSIS framework

**Benefits**

1. Enables Marlin to access the onboard SD card for printing.
2. Enables SD card access via WEB UI host or USB host for printing or file transfer

**Related Issues**

#11639

### CODE REVIEW

**Comment by ModMike** [comment]
This is what was supposed to happen.  Sorry for being such a hack.

**Comment by thinkyhead** [comment]
Please, please, please follow our guidelines on writing good commit messages.

**Comment by ModMike** [comment]
@thinkyhead  I'm very sorry for trying your patience so much, especially lately.  I tried to look at a few to get an idea but I imagine there are guidelines somewhere.  I will read up before I commit anything again.

I figured out what you meant about the Creatbot revert and will commit those as soon as I rebuild the configs from the latest files.

Again, thank you for being so patient.

**Comment by thinkyhead** [comment]
Github lets us put up guidelines, then they put them into a tiny corner of the "New Issue" and "New PR" page just to make sure everyone misses them. Like so…

image

So here are some links to the relevant bits of info…

- [Contributing](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md)
- [Marlin Development stuff](http://marlinfw.org/meta/development/)

**Pull request merged**
