### PR TITLE
Correct SCK and MOSI pins in MARLIN_F103Rx

### PR DESCRIPTION
**Pull request by ellensp**
### Description

MARLIN_F103Rx/variant.h seems to have incorrect pins for PIN_SPI_MOSI and PIN_SPI_SCK when  DEFAULT_SPI == 2 or DEFAULT_SPI == 3

Updated these pins

### Requirements

Any motherboard using MARLIN_F103Rx board variant.

### CODE REVIEW

**Comment by ellensp** [comment]
Going crosseyed, can someone double check this

**Comment by ellensp** [comment]
CI is broken again...  this time with issue https://github.com/MarlinFirmware/Marlin/issues/23279

**Comment by ellensp** [comment]
Has been confirmed as an issue.

**Comment by tpruvot** [comment]
image

image

**Comment by tpruvot** [comment]
To note, SPI3 may not be available on the RC chips, at least if we can trust the variant files...  https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/PlatformIO/variants/MARLIN_F103Rx/PeripheralPins.c#L342-L343

**Comment by ellensp** [comment]
https://www.st.com/resource/en/datasheet/stm32f103rc.pdf says spi3 is on STM32F103xC, STM32F103xD, STM32F103xE
As far as I can tell, so that's a second issue....

**Comment by ellensp** [comment]
But #define HAL_SPI_MODULE_ENABLED is not enabled for any stm32f103xC/D or E  based controllers so that variant limitation is not a issue  (as far as I can see, need to check in framework too..)

**Comment by tpruvot** [comment]
beware if you touch that, look like the RE (& RC) can have both SPI3 & SPI1 ALT the #else seems wrong too...  same also for most of the recent F103, these pins are common to all package/pins sizes. (not at the same time sure for SPI3/SPI1 (PB3/4/PB5) but both are possible, even if i dont see a good reason to change SPI1 pins if there is a SPI3)

Only if I2S2 or I2S3 is used, they are not available for SPI

**Comment by tpruvot** [comment]
hmm, HAL_SPI_MODULE_ENABLED should be enabled by default... if i remember right

**Comment by ellensp** [comment]
MARLIN_F103Rx/PeripheralPins.c is a copy of the provided Generic_F103Rx/PeripheralPins.c  in the version of framework-arduinoststm32 used. (framework-arduinoststm32 4.10900.200819 (1.9.0) https://github.com/stm32duino/Arduino_Core_STM32/blob/codeql/variants/Generic_F103Rx/PeripheralPins.c 

The much later version from https://github.com/stm32duino/Arduino_Core_STM32/blob/main/variants/STM32F1xx/F103R(C-D-E)T/PeripheralPins.c#L225 applies to all C/D/E 

I think we would leave this alone...   and just apply the patch I provided.

**Comment by tpruvot** [comment]
the later seem to confirm SPI3 is available...

**Pull request merged**
