### PR TITLE
Option to confirm SD print of a file

### PR DESCRIPTION
**Pull request by thinkyhead**
Alternative to #13605

- Add a general confirmation screen
- Confirm selection and print of an SD file

### CODE REVIEW

**Comment by robbycandra** [comment]
@thinkyhead ,
General confirmation screen an full Long Filename is good. 

But..
What if later we want to add other menu before printing... like we want to check the file Info or check dimension to print ?

What about this
--FILE NAME--
-> Back
-> Print
-> FIle Info
-> --other gcode file related menu--

**Comment by thinkyhead** [comment]
That sounds like the kind of thing a vendor might want to do for their own purposes, but not something we would care to add to the core project at this time. Dimensions involves pre-scanning, and so on. It's a bit of the Marlin philosophy for the firmware to be mostly brainless.

**Comment by robbycandra** [comment]
> That sounds like the kind of thing a vendor might want to do for their own purposes, but not something we would care to add to the core project at this time. Dimensions involves pre-scanning, and so on. It's a bit of the Marlin philosophy for the firmware to be mostly brainless.

Well Noted....
Its a slicer job.

**Comment by robbycandra** [comment]
@thinkyhead , what about remove file extension ".gco" or ".gcode" at LCD display?

**Comment by thinkyhead** [comment]
It's under consideration, but I think this might bother users who expect to see a whole filename.

**Comment by robbycandra** [comment]
Reason : 
1.  Windows default is to hide filename extension
2. The display is shorter without extension.
3. Marlin only read .gco extension so there are no other extension.
4. We can add option to hide / display the extension

**Comment by thinkyhead** [comment]
This is not a new idea, and if it doesn't require my time right this minute, I have over 900 issues to attend to.

**Comment by robbycandra** [comment]
I like to help if there is something i can do.

**Pull request merged**
