### PR TITLE
Fix problem Width Cura

### PR DESCRIPTION
**Pull request by MagoKimbra**
Repair parsing code width CURA.
Cura non have space between number line and command Gcode.
NxxxGxx or NxxxMxxx or NxxxTx

### CODE REVIEW

**Comment by MagoKimbra** [comment]
Sorry I did not see that had already been done!!!!

**Comment by AnHardt** [comment]
@MagoKimbra 
OK - ok it's your fix.

**Comment by MagoKimbra** [comment]
I'm sorry I had not seen that you had already opened the correction and I opened it too ...

Can I ask you a favor if you can ...
Can I have my name in the collaborator of Marlin?
Also it is written in small at the end of the list, I'd love, but only if you can ....
I am Italian, my real name is Alberto Cotronei and i have 47 old years.
Exusme for this request...

**Comment by AnHardt** [comment]
@MagoKimbra 
Sorry i can not. But you have my :+1:  
But the owners can. 
@daid , @boelle, @ErikZalm

**Comment by MagoKimbra** [comment]
Thanks @AnHardt

**Pull request merged**
