### PR TITLE
Remove configuration files so it's not a PITA to send / update PR

### PR DESCRIPTION
**Pull request by X-Ryl669**
### Description

Let's remove the `Configuration.h` and `Configuration_adv.h` file from the repository!

When submitting a PR, it's a real PITA not to submit those 2 files and still continue building on our side.
Also, there are numerous thousand forks just because they've modified those files.

So, let's rename them `Configuration.h.template` (resp. `Configuration_adv.h.template`) instead and be done with it once for all.
I've added the minimal stuff in the common-dependency script so they are copied back from the template file if missing from the repository, so for the **few** number of people using **default** configuration on a mega2560, it'll still work.

### Requirements

None

### Benefits

Ease the life of fellow developers so they can keep there own configuration files in their repository and never be bothered anymore to revert/reset a commit to remove them.

### Configurations

NA

### Related Issues

Last actions in:
#21003

### CODE REVIEW

**Comment by rhapsodyv** [comment]
Scott already refused that idea here: #18632

**Comment by X-Ryl669** [comment]
Too bad, I haven't rewound that far in history then.

Unlike your attempt, this one does actually build out of the box. So it should address @thinkyhead's first point. 
Maybe we could add a additional step to help his workflow, like a `show_config_diff` to show the diff ?

Let me think about a solution that could work for both side of the coin.

**Comment by rhapsodyv** [comment]
I discussed a lot on discord about it, back there... And the main reason I just gave up was only one: Users. Marlin has lots of non technical users that download and build the firmware. Most of them don't even know what a compiler is.

So, I ended up agreeing that we (devs) can work a bit more, just to keep Marlin easy for non technical people.

**Comment by thisiskeithb** [comment]
This has been discussed/tried several times in the past, but it was decided to stick with the current implementation.

Note that this breaks actions like rebasing configs in forks (to keep them up to date) since the config files no longer exist in the same location upstream.

**Comment by thinkyhead** [comment]
The ready configurations are useful in a number of ways, including as part of the Configurations update workflow, so I prefer to keep them.

**Comment by X-Ryl669** [comment]
Would you accept a script doing [this](https://practicalgit.com/blog/make-git-ignore-local-changes-to-tracked-files.html) (at least) ?

The idea is that local changes to Conf files are ignored by git unless they are modified upstream.

**Pull request closed without merging**
