### PR TITLE
Add HAS_SERVO_ENDSTOPS to simplify conditionals

### PR DESCRIPTION
**Pull request by thinkyhead**
Redo of #2539 with additional code tweaks.

### CODE REVIEW

**Comment by thinkyhead** [comment]
So far all the `HAS_*` defines come out of `Conditionals.h` and are not configuration options that you would set in `Configuration.h` or through a `-D` flag. They are always boolean. Might as well keep it that way.

**Comment by Wackerbarth** [comment]
Well, there is one exception. :) But the policy is fine and we can change any non-conforming instances.
But that does leave the question of a naming policy for on/off OPTIONS (as opposed to those which have a parametric value)

So, for example, how should I tell the compiler that I do (or don't) want to use the LCD screen?
It needs to be a selector .  Testing for some pin being defined, is not appropriate because I may actually have the peripheral, but want to ignore it.

Perhaps, we can use the _OPTION suffix.

#if ENABLED(SOME_OPTION)

reads well and allows us to use either form of definition.

**Comment by thinkyhead** [comment]
> Well, there is one exception

Ah yes, and a notable one: `HAS_AUTOMATIC_VERSIONING`.

> Perhaps, we can use the `_OPTION` suffix

Little by little, as we go. I don't want to completely throw users for a loop on a single update. For now, the `ENABLED` / `DISABLED` macros at least begin to make it clearer which options are plain on/off switches.

**Comment by thinkyhead** [comment]
> how should I tell the compiler that I do (or don't) want to use the LCD screen?

Currently if you don't select which LCD you have (or at least `ULTRA_LCD`), no support is compiled in.

**Comment by Wackerbarth** [comment]
Deprecation is the way to change something like that.  Support using either indicator for a while and give notice that we have changed the preferred form and will drop the old form at some specified point.

**Comment by Wackerbarth** [comment]
"Currently if you don't select which LCD you have" --- But that is the point I HAVE the device and want to be able to put all of its specifications (whatever the are) in the profile for that printer. However, I don't want to actually have it used.

**Pull request merged**
