### PR TITLE
Add GD32F103RE_btt env (96 MHz)

### PR DESCRIPTION
**Pull request by blazewicz**
### Description

Recently I bought [BIGTREETECH SKR Mini E3 V2.0](https://www.biqu.equipment/products/bigtreetech-skr-mini-e3-v2-0-32-bit-control-board-integrated-tmc2209-uart-for-ender-3?variant=31995437744226) board to replace damaged Creality v4.2.2 (bed MOSFET released the [magic smoke](https://en.wikipedia.org/wiki/Magic_smoke)) on my Ender 3 V2 and I noticed that instead of usual STM32F103RET6 it came equipped with [GigaDevice GD32F103RET6](https://www.gigadevice.com/microcontroller/gd32f103ret6/). This chip is a clone of the STM, but not an exact one. It actually has a PLL capable of running the core at 108 MHz, that is **50% faster than the original**. I thought it would be a waste not to enable its full potential.

**EDIT**: Full speed 108 MHz is not compatible with USB support, max usable frequency is 96 MHz.

BTT_SKR_Mini_V2_GD32F103RET6

Also I disabled the HSI clock as it was never used, all board use HSE for system clock.

### Requirements

Any printer with BTT SKR Mini E3 V2.0 with GD32F103RET6 MCU. Could be extended to any board equipped with this MCU.

### Benefits

Thanks to ~~50%~~ 33% faster operation, in theory, this could allow more advanced operations to be performed by the CPU. Processing intensive operations like UI refreshing will execute faster.

### Configurations

My full setup is descibed in following issue:

* https://github.com/MarlinFirmware/Configurations/issues/535

### CODE REVIEW

**Comment by blazewicz** [comment]
I had to remove `GD32F103RE_btt_USB` variant. USB clock divider has no suitable value to make 48 MHz out of 108 MHz main clock (2.25 ratio), hence USB support is not possible with this clock rating.

**Comment by blazewicz** [comment]
Let me explain why exactly this is tricky.

Below is a fragment of a clock distribution diagram for GD32F10x chip. By USB standard the CK_USBFS clock **must** be exactly 48 MHz, its very important to match this frequency as close as possible. Only possible source of CK_USBFS clock is CK_PLL which in our case is equal to main system clock CK_SYS divided by USB prescaler.

Zrzut ekranu 2021-07-3 o 00 16 43

Only possible values for USB prescaler are 1, 1.5, 2 and 2.5.

Zrzut ekranu 2021-07-2 o 23 37 53

Assuming 8 MHz crystal oscillator this implies following:

CK_USBFS | USBFSPSC | CK_PLL | CK_PLL/CK_HXTAL | PREDV0 | PLLMF
-----------|----|----------|----------|--------|----------
48 MHz |  1     |  48 MHz         | 6              | 1          | 6
48 MHz |  1.5  |  72 MHz         | 9              |  1         | 9
48 MHz |  2    |  96  MHz       | 12        | 1      | 12
48 MHz |  ~~2.25~~ | 108 MHz | 27/2  | 2 | 27
48 MHz |  2.5 | ~~120 MHz~~ | 15   | 1   | 15

I don't understand why they decided to keep 2.5 and not to implement 2.25. I tought maybe its a mistake in datasheet, but its not, 2.5 divider with 108 MHz PLL doesn't work.

Anyway, max we can get still having working USB is 96 MHz, still 33% performance upgrade.

---

EDIT: I must have been tired, 2*48=96, not 86.

**Comment by p3p** [comment]
We had a quick look over the STM32 platform licenses a few days ago with regard to GD MCUs and although most of them do not appear to be too restrictive, the USB peripheral drivers seem to require to be run on STM supplied MCUs, adding official Marlin support for these clones (rather than incidental support due to inter-compatibility) may not be the best idea.

**Comment by looxonline** [comment]
> We had a quick look over the STM32 platform licenses a few days ago with regard to GD MCUs and although most of them do not appear to be too restrictive, the USB peripheral drivers seem to require to be run on STM supplied MCUs, adding official Marlin support for these clones (rather than incidental support do to inter-compatibility) may not be the best idea.

Agreed. The GD devices simply need a single endpoint buffer for USB to work correctly and this seems to be about the only difference between it and an STM device. Including a build switch that is board dependent that changes the USB endpoint buffers to single instead of double would allow compatibility without explicitly adding any GD support. Boards that manufacturers ship that use both STM and GD would need to invoke this switch. The STM should still work with the single buffer although a little slower.

**Comment by InsanityAutomation** [comment]
> 
> 
> > We had a quick look over the STM32 platform licenses a few days ago with regard to GD MCUs and although most of them do not appear to be too restrictive, the USB peripheral drivers seem to require to be run on STM supplied MCUs, adding official Marlin support for these clones (rather than incidental support do to inter-compatibility) may not be the best idea.
> 
> Agreed. The GD devices simply need a single endpoint buffer for USB to work correctly and this seems to be about the only difference between it and an STM device. Including a build switch that is board dependent that changes the USB endpoint buffers to single instead of double would allow compatibility without explicitly adding any GD support. Boards that manufacturers ship that use both STM and GD would need to invoke this switch. The STM should still work with the single buffer although a little slower.

Id agree with this approach. I just started playing with one of these GD boards over the weekend. No major issues to report yet.

**Comment by thinkyhead** [comment]
> Including a build switch that is board dependent that changes the USB endpoint buffers to single instead of double would allow compatibility without explicitly adding any GD support.

So, what does that mean for this PR? Is it still needed, or do we need to change gears and add this build switch?

**Comment by looxonline** [comment]
> So, what does that mean for this PR? Is it still needed, or do we need to change gears and add this build switch?

I would say go the build switch route. Even though it would be difficult for ST to lay any claim against Marlin devs (since the devs are not physically executing STM code on non STM devices and it seems that the licence prohibits specifically that and not the building of STM code for non-STM devices) including a build switch would remove all concerns around that completely. Furthermore, since there is no point in running the GD device at the higher freq due to the USB bus master not being able to reach the needed 48MHz with the available PLL settings it seems like it is a better option to just leave the compatibility implicit rather than explicit.

**Comment by blazewicz** [comment]
>  Furthermore, since there is no point in running the GD device at the higher freq due to the USB bus master not being able to reach the needed 48MHz with the available PLL settings

It's not able to run at 108 MHz, but it can run at 96 MHz, which is still faster than STM with 72 MHz max.

**Comment by thinkyhead** [comment]
> it can run at 96 MHz

If we want that capability, then I guess we must go with a variant. I don't think this PR ought to be any problem for ST Micro, but it sounds like 3D printer vendors who shipped a machine with a GD32 and Marlin installed using the GD32 target might run afoul of their terms. If that is the case, we may supply a disclaimer in the form of an `#error` or `#warning`.

**Comment by p3p** [comment]
> we may supply a disclaimer in the form of an #error or #warning

Still not sure it's a good idea to add a specific build environment where the produced binary cannot be executed on the target MCU without breaching STMs license even if in doing so Marlin is not liable.

I only had a quick look at the licenses and I am not a lawyer, but it seems to only apply to the USB peripheral driver, you could add a build with that disabled by default?

**Comment by thinkyhead** [comment]
Since the firmware —including the USB peripheral driver— can already be built without this PR to run on the GD32, we are _already_ "facilitating" that capability. This PR additionally adjusts some parameters to improve performance on the GD32, but it isn't providing any new _capability_ to run on GD32.

So, if we are very concerned about the STM32-USB targets being run on GD32, we would need to do not only drop this PR but also do something to limit that capability. It seems to me that there must be more to this license issue, since presumably even ST Micro's own tools "facilitate" running the USB peripheral driver on GD32 in just the same way… unless their tools are programmed to only write to their own MCUs.

**Comment by InsanityAutomation** [comment]
I think there is a big difference between implicit its targeted to STM but happens to work on GD and explicit exclusively for GD devices and wont work on an STM at all. If a GD env is added, according to the license it has to exclude the USB lib or we are explicitly non compliant with the license whereas if it is cross compatible, its still targeting compliance and if the use is not, its out of our control.

In all honestly the chip is being used interchangeably due to the current shortages so most users wont even know which they have.

**Comment by looxonline** [comment]
> Since the firmware —including the USB peripheral driver— can already be built without this PR to run on the GD32, we are _already_ "facilitating" that capability. This PR additionally adjusts some parameters to improve performance on the GD32, but it isn't providing any new _capability_ to run on GD32.
> 
> So, if we are very concerned about the STM32-USB targets being run on GD32, we would need to do not only drop this PR but also do something to limit that capability. It seems to me that there must be more to this license issue, since presumably even ST Micro's own tools "facilitate" running the USB peripheral driver on GD32 in just the same way… unless their tools are programmed to only write to their own MCUs.

The license in question is here: https://www.st.com/content/ccc/resource/legal/legal_agreement/license_agreement/group0/eb/8e/f9/c1/9e/64/49/95/SLA0048/files/SLA0048.txt/jcr:content/translations/en.SLA0048.txt

The point in question states: 

> "4. This software package or any part thereof, including modifications and/or derivative works of this software package, must be used and execute solely and exclusively on or in combination with a microcontroller or a microprocessor devices manufactured by or for STMicroelectronics."

According to that, the software should be used and execute solely on STM devices. So the question really is about who that responsibility falls on. Execution is most certainly the responsibility of the vendor or end user installing the package. Use is perhaps a little more grey. Could STM claim that by explicitly including support the Marlin Devs were facilitating use? Is that even a thing? I would assume not. I think that it would probably be fair to say that use and execution are the same thing.

With the new environments (moving away from maple) I understand that it is far more than just the USB driver that is affected. In fact, replacing maple means that most of the arduino framework on these devices is now executed by STMCore code.

On another note, I have been testing this on a GD board for some time and I have found that the single buffer USB endpoint fails after a few hours. I don't know if it is just my setup so I am waiting on feedback from other users but I don't think that alone should hold up this PR. In fact, if anything, it should support it because it means that the single buffer endpoint may not be as stable as the double buffer endpoint and for that reason we may want to split the GD boards away from the STM boards so that the STM boards are not forced to use a single buffer where manufacturers choose to use the chips interchangeably. In such cases the user would need to try and observe what IC he has and select the correct env and then eventually, once a fix is found for the GD USB comms stability, it can be integrated into that env.

**Comment by blazewicz** [comment]
> the single buffer USB endpoint fails after a few hours

I can confirm this one, serial connection fails randomly after few hours of operation (print from Octoprint). Doesn't matter if clock is at 72 or 96 MHz.

**Comment by thinkyhead** [comment]
Someone mentioned on another thread that they don't trust the `USBCON` build flag. Is that being used for your target board? Maybe this flag can be disabled to see if there is any difference.

**Comment by looxonline** [comment]
> Someone mentioned on another thread that they don't trust the `USBCON` build flag. Is that being used for your target board? Maybe this flag can be disabled to see if there is any difference.

Will give this a try tomorrow and offer some feedback.

**Comment by rhapsodyv** [comment]
USBCON enabled/disable usb serial in stm32duino, if I remember right.

I have another fix for GD board (single sized CDC buffer) waiting for this discussion: we can or cannot have a GD env or board in marlin using stm32 libs?

**Comment by thinkyhead** [comment]
> we can or cannot have a GD env or board in marlin using stm32 libs?

Likely not. But, it would be good to be able to provide an STM32 build that runs reasonably well on the GD32, even though not explicitly targeted for the GD32.

**Comment by tpruvot** [comment]
clocks are also tunable on normal STM32 chips, but like he said, some features like USB (also spi and rtc) need the right core/PLL clocks.. timer clock and serial baudrate can be fixed in code. V & Z chips seems to handle better the highest clocks... (bigger chip = better cooling i guess)

**Comment by blazewicz** [comment]
> Someone mentioned on another thread that they don't trust the USBCON build flag. Is that being used for your target board? Maybe this flag can be disabled to see if there is any difference.

USB serial doesn't work without this flag, it would require more changes to remove this feature.

So far I moved from `*_btt_USB` to `*_btt`, and I was able to run 5h print from Octoprint without an issue. I had to change USB buffer from double to single in arduino code to make it work.

I'll try something closer to 10h tonight and report back if it succeeds.

```diff
--- ~/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/usb/usbd_ep_conf.c	2021-07-19 00:26:39.000000000 +0200
+++ ~/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/usb/usbd_ep_conf.c	2021-07-19 00:26:30.000000000 +0200
@@ -37,7 +37,7 @@
 #else
   {0x00,       PMA_EP0_OUT_ADDR, PCD_SNG_BUF},
   {0x80,       PMA_EP0_IN_ADDR,  PCD_SNG_BUF},
-  {CDC_OUT_EP, PMA_CDC_OUT_ADDR, PCD_DBL_BUF},
+  {CDC_OUT_EP, PMA_CDC_OUT_ADDR, PCD_SNG_BUF},
   {CDC_IN_EP,  PMA_CDC_IN_ADDR,  PCD_SNG_BUF},
   {CDC_CMD_EP, PMA_CDC_CMD_ADDR, PCD_SNG_BUF}
 #endif
```

**Comment by tpruvot** [comment]
interesting, indeed here https://community.st.com/s/question/0D50X0000A1lW3r/stm32f302-use-usb-double-buffer-the-transmit-data-will-over-buffer-setting they say the double buffering cannot be used if the IN & OUT are on same EPn (end point)

**Comment by thinkyhead** [comment]
Yes, that is very interesting! And this library seems worth a look, at least to understand the issues involved: https://github.com/IntergatedCircuits/USBDevice

**Comment by blazewicz** [comment]
Suggestion from @CRCinAU (https://github.com/MarlinFirmware/Marlin/issues/22390#issuecomment-884291983) about both MSC and CDC running on same USB seems to be true.

With `STM32F103RE_btt` env (with patch mentioned above) I have no more issues with connection stability. My printer just finished 8.5h print from Octopi, with `*_btt_USB` env I couldn't print a 3DBenchy.

**Comment by blazewicz** [comment]
I think this should be continued in its own thread, I've opened new issue.

* https://github.com/MarlinFirmware/Marlin/issues/22431

**Comment by th3dstudio** [comment]
<details><summary>Previous Thread</summary>

> > Since the firmware —including the USB peripheral driver— can already be built without this PR to run on the GD32, we are _already_ "facilitating" that capability. This PR additionally adjusts some parameters to improve performance on the GD32, but it isn't providing any new _capability_ to run on GD32.
> > So, if we are very concerned about the STM32-USB targets being run on GD32, we would need to do not only drop this PR but also do something to limit that capability. It seems to me that there must be more to this license issue, since presumably even ST Micro's own tools "facilitate" running the USB peripheral driver on GD32 in just the same way… unless their tools are programmed to only write to their own MCUs.
> 
> The license in question is here: https://www.st.com/content/ccc/resource/legal/legal_agreement/license_agreement/group0/eb/8e/f9/c1/9e/64/49/95/SLA0048/files/SLA0048.txt/jcr:content/translations/en.SLA0048.txt
> 
> The point in question states:
> 
> > "4. This software package or any part thereof, including modifications and/or derivative works of this software package, must be used and execute solely and exclusively on or in combination with a microcontroller or a microprocessor devices manufactured by or for STMicroelectronics."
> 
> According to that, the software should be used and execute solely on STM devices. So the question really is about who that responsibility falls on. Execution is most certainly the responsibility of the vendor or end user installing the package. Use is perhaps a little more grey. Could STM claim that by explicitly including support the Marlin Devs were facilitating use? Is that even a thing? I would assume not. I think that it would probably be fair to say that use and execution are the same thing.
> 
> With the new environments (moving away from maple) I understand that it is far more than just the USB driver that is affected. In fact, replacing maple means that most of the arduino framework on these devices is now executed by STMCore code.
> 
> On another note, I have been testing this on a GD board for some time and I have found that the single buffer USB endpoint fails after a few hours. I don't know if it is just my setup so I am waiting on feedback from other users but I don't think that alone should hold up this PR. In fact, if anything, it should support it because it means that the single buffer endpoint may not be as stable as the double buffer endpoint and for that reason we may want to split the GD boards away from the STM boards so that the STM boards are not forced to use a single buffer where manufacturers choose to use the chips interchangeably. In such cases the user would need to try and observe what IC he has and select the correct env and then eventually, once a fix is found for the GD USB comms stability, it can be integrated into that env.
</details>

This is concerning as we put out firmware for the SKR E3 Mini boards. Since we are a US company, if we are putting out "GD32" specific firmware would that potentially open us up to being sued by ST?

**Comment by looxonline** [comment]
> This is concerning as we put out firmware for the SKR E3 Mini boards. Since we are a US company, if we are putting out "GD32" specific firmware would that potentially open us up to being sued by ST?

I doubt that they would be able to open any sort of a case. You are neither using nor executing it on the boards as a company provided you don't ship boards with it pre-installed. The second that changes it becomes a different story.

**Comment by thinkyhead** [comment]
I heard a rumor that inexpensive Voxelab (aka Flashforge) Aquila printers are shipping with a GD chip and Marlin installed.

**Comment by looxonline** [comment]
> I heard a rumor that inexpensive Voxelab (aka Flashforge) Aquila printers are shipping with a GD chip and Marlin installed.

I can confirm this. There are multiple reddit threads of users discussing their boards with GD chips.

**Comment by th3dstudio** [comment]
> > I heard a rumor that inexpensive Voxelab (aka Flashforge) Aquila printers are shipping with a GD chip and Marlin installed.
> 
> I can confirm this. There are multiple reddit threads of users discussing their boards with GD chips.

Yes they are, I have one here. They used the Creality V4.2.2 board ENV to make the firmware for it as well. Need to dust that machine off and test it to see if it has any issues because it's a 256K CPU using a 512K CPU env as well. :/ Haven't tested the USB on it, just SD. Their board appears to be pin-compatible with the Creality V4.2.2 board in the unit we have.

Looking at the voxelab firmware they are using the reality STM32 512K env name but they modified the code to limit it to 256K. See here as this may help out with determining how to get the GD chips better supported in Marlin: https://github.com/Voxelab-64/Marlin

**Comment by thinkyhead** [comment]
There is already a board called the "DICE" so I guess this one is the "Roulette"?

**Comment by th3dstudio** [comment]
Found a since-deleted article talking about the USB issues due to the multipliers available: https://web.archive.org/web/20200220151836/http://www.rogerclark.net:80/gd32f103-a-stm32f103-on-steroids/

As for the "legal issue" with the ST libraries, I found some other projects where they added envs for the GD chips and didn't seem to get problems. I'm still torn on "official" support of the GD chips solely because of the threat of legal issues from ST...

**Comment by th3dstudio** [comment]
@blazewicz - a BTT engineer contacted me and stated that those boards with the GD32 CPU were only sent to beta testers. Did you purchase it or did you receive it in a beta test?

**Comment by thisiskeithb** [comment]
> a BTT engineer contacted me and stated that those boards with the GD32 CPU were only sent to beta testers. Did you purchase it or did you receive it in a beta test?

To mitigate any potential delays, BigTreeTech sent GD-based SKR Mini E3 V2s to distributors ahead of beta testing since the MCU was the only component swap out. Some distributors obviously shipped out these boards before they were supposed to.

Similar to the RC and RE purchase options for the current SKR Mini E3 V2, these boards were always meant to be shipped & sold as GD variants.

The GD-based boards should also have a "GD" sticker on the back for easier identification:

**Comment by th3dstudio** [comment]
> > a BTT engineer contacted me and stated that those boards with the GD32 CPU were only sent to beta testers. Did you purchase it or did you receive it in a beta test?
> 
> To mitigate any potential delays, BigTreeTech sent GD-based SKR Mini E3 V2s to distributors ahead of beta testing since the MCU was the only component swap out. Some distributors obviously shipped out these boards before they were supposed to.
> 
> Similar to the RC and RE purchase options for the current SKR Mini E3 V2, these boards were always meant to be shipped & sold as GD variants.
> 
> The GD-based boards should also have a "GD" sticker on the back for easier identification:
> 

Why would they be sending out boards when the firmware was not ready 100% for them? If those have the firmware that was made with the ST libraries the resellers could be on the hook legally for the license violation.

**Comment by looxonline** [comment]
> > > a BTT engineer contacted me and stated that those boards with the GD32 CPU were only sent to beta testers. Did you purchase it or did you receive it in a beta test?
> > 
> > 
> > To mitigate any potential delays, BigTreeTech sent GD-based SKR Mini E3 V2s to distributors ahead of beta testing since the MCU was the only component swap out. Some distributors obviously shipped out these boards before they were supposed to.
> > Similar to the RC and RE purchase options for the current SKR Mini E3 V2, these boards were always meant to be shipped & sold as GD variants.
> > The GD-based boards should also have a "GD" sticker on the back for easier identification:
> > 
> 
> Why would they be sending out boards when the firmware was not ready 100% for them? If those have the firmware that was made with the ST libraries the resellers could be on the hook legally for the license violation. And swapping out the MCU is not a small thing to do. Look at what happened with the SKR2 and the MOSFET issues...They never learn.

For simple reasons that can be discussed in a rational manner without jumping to false conclusions and then spreading those conclusions around as if they are fact. So let's do that:

1.) These boards are identical in every way to the STM E3 mini boards barring the MCU. That takes a tremendous number of variables off the table.

2.) Before the boards were even sent out to beta evaluators they were tested by BTT and found to be working with the Maple environments. Both serial USB and MSC enumeration were working using Maple. This indicated that the hardware itself was fine but with the shift over to STM core there was a need for evaluators to test whether these libraries were compatible.

3.) Since the hardware had proven itself BTT made the call to manufacture an initial production run and ship a small number to distributors in anticipation of the evaluation being completed and producing firmware that irons out any issues that may be found with the switch to the STM Core framework.

4.) When issues were found with the STM Core framework during the evaluation, the BTT engineers worked with the evaluators to find fixes and get them patched. Unlike you falsely claim they had no intention of leaving the Marlin community to fix the issues. This thread started because a distributor sent a board out without BTTs knowledge and the recipient happened to have the technical knowledge to figure out that he had a different board.

5.) After BTT had decided to start selling the boards using the Maple framework via their Ali channel one of the evaluators identified that there is a licensing issue. On the 23rd of July, long before you were even aware that this board existed, BTT made an announcement to all evaluators that they had decided not to sell the GD variant due to the licensing issues.

**Comment by th3dstudio** [comment]
Those are a lot of words to confirm that they jumped the gun on shipping these out before everything was ready. I wish I could say I am surprised but I am not since this is how BTT does business. I wouldn't know about their internal dealings since I am not "buddy-buddy" with them like you and Keith are. 

Tell them to be less sloppy with their dealings and issues like this won't happen. I still don't buy the story as it seems like they are scrambling now that it's in the wild that these boards shipped to customers. If they were planning to NOT sell them then Luciano would not have sent me a message stating that they were "flawless" a couple of days ago until I called out using clones when him and I specifically talked about them NOT doing that months ago. The stories don't line up, period.

BTW, how much are they paying you guys to shill for their products and to do damage control for them?

**Comment by looxonline** [comment]
> Those are a lot of words to confirm that they jumped the gun on shipping these out before everything was ready. I wish I could say I am surprised but I am not since this is how BTT does business. I wouldn't know about their internal dealings since I am not "buddy-buddy" with them like you and Keith are.
> 
> Tell them to be less sloppy with their dealings and issues like this won't happen. I still don't buy the story as it seems like they are scrambling now that it's in the wild that these boards shipped to customers. If they were planning to NOT sell them then Luciano would not have sent me a message stating that they were "flawless" a couple of days ago until I called out using clones when him and I specifically talked about them NOT doing that months ago. The stories don't line up, period.
> 
> BTW, how much are they paying you guys to shill for their products and to do damage control for them?

Tim, human to human you are wrecking your name. I'm trying to have a rational conversation with you while you try to come back with lies, speculation and twisted half truths. 

The facts have been presented and there is no point in defending the truth because it should be clear for all to see. 

Nevertheless, in case you would like further evidence that they made the call not to sell them based on the licensing issues you are welcome to take another screenshot of my post. I also address why I help them and that I have never been paid a cent from them in the same post.

**Comment by th3dstudio** [comment]
msedge_2021-08-05_02-53-08

You want to have a "rational conversation" yet you are tossing around baseless claims and accusing me of "racism"? I'm done with you clowns. I'll be sure to share this with everyone and let people see that you're now resorting to actual libel.

**Comment by looxonline** [comment]
> msedge_2021-08-05_02-53-08
> 
> You want to have a "rational conversation" yet you are tossing around baseless claims and accusing me of "racism"? I'm done with you clowns. I'll be sure to share this with everyone and let people see that you're now resorting to actual libel.

Thanks Tim. This is a technical thread focused on technical matters. Let's keep it that way.

**Comment by thinkyhead** [comment]
I also have the SKR Mini E3 V2.0 board with GDF103RET6 so I am able to experiment with this MCU to see how it behaves. See my comments at https://github.com/MarlinFirmware/Marlin/issues/22431#issuecomment-896306174

**Comment by blazewicz** [comment]
@thinkyhead after #25267 and #25405 were merged, would you reconsider having this PR merged too?

I've been using this config with 96 MHz clock on my Ender 3 V2 since 2021 and didn't have any stability issues with it.

**Comment by thisiskeithb** [comment]
This board was recalled from vendors, so it doesn’t make sense to add an environment for it.

**Comment by blazewicz** [comment]
That's true, probably it's just me who has this unique board and I'm okay with maintaining this env in the fork that I use for my builds.

But, `env:trigorilla_v006` and `env:GD32F103RET6_sovol_maple` could both benefit from having option to enable 96 MHz clock since they're based on GD MCU and are supported by Marlin. I could refactor this PR to add `GD32F10x` and `board_build.f_cpu = 96000000L` to these environments.

@thinkyhead, what do you think about it?

**Pull request closed without merging**
