### PR TITLE
ReadMe: Add project description (2)

### PR DESCRIPTION
**Pull request by penguineer**
Follow-up to #9052, now on the 2.0 development branch. 

The ReadMe did not feature a project description. Use the description from
GitHub and add some links to tell everyone what this actually is.

Also add the (longer) description from the Marlin homepage.

I leave it open for discussion (or the mergers decision) if both commits or just the first should be pulled.

### CODE REVIEW

**Comment by thinkyhead** [comment]
The main `README.md` in the bugfix branches is not the one we use for release branches. We just make a copy of the README from the previous release and add new details. As I assured you in the previous PR, I will be certain to add a project description to the README on the next release (1.1.9), which may be as soon as today.

**Comment by penguineer** [comment]
I have no doubt that you will add the information to the release's README. :)

However, I believe that it is beneficial to have the short description in the `README.md` in this very repository, as proposed in the PR. Don't you think?

**Comment by thinkyhead** [comment]
>  I believe that it is beneficial to have the short description in the README.md in this very repository, as proposed in the PR. Don't you think?

Not particularly! The README in the bugfix branch isn't really a world-facing document, and those of us messing with bugfix already know what Marlin is.

Plus, I really despise that paragraph describing Marlin as "reliable and precise" as though that's some kind of distinction. Please, just burn it. I'll write something less flowery for the actual release.

**Comment by penguineer** [comment]
> The README in the bugfix branch isn't really a world-facing document, and those of us messing with bugfix already know what Marlin is.

That's your misconception. I found Marlin because it was laying around and I had a look at the git remote before deleting a directory somebody may have just left. After clone the README is all you can see.

> Plus, I really despise that paragraph describing Marlin as "reliable and precise" as though that's some kind of distinction. Please, just burn it. I'll write something less flowery for the actual release.

I took this from the Marlin homepage! Blame them. ;)

Anyways, the PR repo is long gone.

**Comment by thinkyhead** [comment]
> I took this from the Marlin homepage! Blame them. ;)

Blame me. I put it there originally.

**Pull request closed without merging**
