### PR TITLE
Fix source typo

### PR DESCRIPTION
**Pull request by luzpaz**
### Description

Fix typo in source. Change has not been tested. 

### Benefits

Self-explanatory

### CODE REVIEW

**Comment by ellensp** [comment]
You cannot do this without updating all references to TotalHeigh In Arduino_Core_STM32
Eg it is defined as 
`  uint32_t            TotalHeigh;                /*!< configures the total height.
`
In Arduino_Core_STM32
https://github.com/stm32duino/Arduino_Core_STM32/blob/main/system/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_ltdc.h#L103

Marlin will not compile with this change when this code is included.

**Comment by tpruvot** [comment]
well wait, you pointed main branch but we are not on it...
1.9 is closer to codeql branch (legacy branch)
https://github.com/stm32duino/Arduino_Core_STM32/blob/codeql/system/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_ltdc.h#L146

**Comment by tpruvot** [comment]
nevermind, i linked bad line/var.. https://github.com/stm32duino/Arduino_Core_STM32/blob/codeql/system/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_ltdc.h#L103 yea :p

**Comment by ellensp** [comment]
Test procedure. Set the following
platfomio.ini
default_envs = BTT_SKR_SE_BX

Configuration.h
#define SERIAL_PORT -1
#define MOTHERBOARD BOARD_BTT_SKR_SE_BX
#define BIQU_BX_TFT70
#define TFT_CLASSIC_UI

Applying this PR results in this error. 

```CPP
Marlin/src/HAL/STM32/tft/tft_ltdc.cpp: In function 'void LTDC_Config()':
Marlin/src/HAL/STM32/tft/tft_ltdc.cpp:186:16: error: 'struct LTDC_InitTypeDef' has no member named 'TotalHeight'; did you mean 'TotalHeigh'?
  186 |   hltdc_F.Init.TotalHeight = (TFT_HEIGHT + LTDC_LCD_VSYNC + LTDC_LCD_VBP + LTDC_LCD_VFP - 1);
      |                ^~~~~~~~~~~
      |                TotalHeigh
*** [.pio/build/BTT_SKR_SE_BX/src/src/HAL/STM32/tft/tft_ltdc.cpp.o] Error 1

```

**Comment by thisiskeithb** [comment]
This was "fixed" once before in https://github.com/MarlinFirmware/Marlin/pull/22531 and I reverrted it in https://github.com/MarlinFirmware/Marlin/pull/22776.

Perhaps we need comments on these types of variables to prevent them from being caught up in spell check PRs.

**Comment by thisiskeithb** [comment]
> default_envs = BTT_SKR_SE_BX

We also have a [standard BX config now](https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/BIQU/BX), so perhaps our CI test should be updated (it would have caught this).

**Comment by ellensp** [comment]
@thisiskeithb looking at luzpaz GitHub, this seems to be a mostly automated system for finding spelling errors in code. 
So comments may not help, but a CI test will stop this occurring again...

**Comment by luzpaz** [comment]
I'll submit typo fixes to the upstream repo: https://github.com/stm32duino/Arduino_Core_STM32.git  
There are so many typos in the source (currently at 723 files and still not done)

**Pull request closed without merging**
