### PR TITLE
incorrect position Info Menu

### PR DESCRIPTION
**Pull request by Ludy87**
incorrect position Info Menu
See: https://github.com/MarlinFirmware/MarlinDocumentation/blob/master/_features/lcd_menu.md

### CODE REVIEW

**Comment by silentninja1** [comment]
This defeats the purpose of @marcio-ao 's request to move the print from SD menu down.

**Comment by marcio-ao** [comment]
We do prefer having it at the bottom, but I don't think a decision was ever made one way or another. There were [pros and cons for either way](https://github.com/MarlinFirmware/Marlin/issues/12487). With the latest Marlin, the SD stuff moved to the bottom, which is a change we welcome, but if the consensus is it needs to be somewhere else, we will make the modification to our FW.

**Comment by Ludy87** [comment]
To navigate with the buttons is annoying, but then every time down, is too much of a good thing.
With an encoder this is easier and faster, but not with the button.

If necessary, I bow to the majority.

**Comment by InsanityAutomation** [comment]
Since im not sure theres any good way to determine every button type vs dial type lcd, I can add a define in the lcd section for HAS_BUTTONS and display this at the top with buttons or bottom by default. Since I do believe the majority is dials, I would make that the default option.

**Comment by marcio-ao** [comment]
@InsanityAutomation: How 'bout a new option, SD_PRINT_ON_BOTTOM. It can be enabled by default, disabled by the user if they have buttons.

**Comment by Ludy87** [comment]
That would be a compromise

**Comment by InsanityAutomation** [comment]
I was thinking a block like this : 

//
// Use this if your LCD uses buttons instead of a dial encoder
// Changes locations of some menus for usability
//#define ENCODER_TYPE_BUTTONS

That way we can shuffle other things around in the future if a conflict arises without a separate define for each. I can imagine individual defines everywhere button vs dial conflict could get unwieldy...

**Comment by InsanityAutomation** [comment]
This look like it satisfies everyone, aside from the annoying code duplication in the menu? 

https://github.com/InsanityAutomation/Marlin/commit/4f3e969aaa98f30002cba0a560ac2d29f84a1330

**Comment by marcio-ao** [comment]
@InsanityAutomation: Since you are explaining what it actually changes in the comment, then it works for me (I would probably object if it didn't explain).

**Comment by InsanityAutomation** [comment]
@marcio-ao good thing we didnt need to get you a fresh gavel then (or make you turn back to tomato farming).... :)

**Comment by marcio-ao** [comment]
> This look like it satisfies everyone, aside from the annoying code duplication in the menu?

Yes, looks good. The annoying duplication is annoying, for sure. I wish that could be made into a function, but all the macro magic makes it impossible (I tried, at one point).

**Comment by InsanityAutomation** [comment]
Ok, I plan to modify a few more menu's for SINGLENOZZLE standby temp stuff later on today. Ill make a PR with that all together later tonight or tomorrow morning.

**Comment by Ludy87** [comment]
Then I close this PR ?!

**Comment by InsanityAutomation** [comment]
@Ludy87 as long as you're in agreement with the above as well, yup go ahead and close this and ill get the all encompassing compromise submitted for Scott to review with the rest of my in progress changes shortly.

**Comment by Ludy87** [comment]
Thank you for the fast and factual cooperation

**Comment by InsanityAutomation** [comment]
NP. Ive been working around this stuff a good bit the last few days. Pause / resume from LCD is caught up to everything else now with feedback to streamers, stepper parking with hotend cooldown, and all the screens working. I fell into a rabbit hole of it trying to finish up a few bits for singlenozzle menus when someone pointed out that they couldnt actually pause and resume with certain options :)

**Comment by Roxy-3D** [comment]
> To navigate with the buttons is annoying, but then every time down, is too much of a good thing.  With an encoder this is easier and faster, but not with the button.

Perhaps it would make sense to add an option to allow the menu to wrap around.   If we had that option, we can put the SD-Card menu and the bottom, and people with buttons can get to it with one click.  (an up click)

**Comment by InsanityAutomation** [comment]
That wouldn't be too bad either for buttons. Headache on scroll wheels though.

**Pull request closed without merging**
