### PR TITLE
Bugfix2.0 "more" menu for lvglui interface

### PR DESCRIPTION
**Pull request by Malderin**
### Description

Added "more" menu when using the interface from MKS LVGL (#define TFT_LVGL_UI in configuration.h). The menu is activated by the #define CUSTOM_USER_MENUS parameter in configuration_adv.h It is possible to add up to 7 custom commands.
Tested on MKS Robin nano v.2 with mks tft 35.

### CODE REVIEW

**Comment by rhapsodyv** [comment]
I don’t think this PR will work this way. Where this code came from? From MKS?

**Comment by Malderin** [comment]
> I don’t think this PR will work this way. Where this code came from? From MKS?

The code in draw_more.cpp is already present in the main code of marlin bugfix 2.0.
I just added the missing lines to configuration_adv.h and draw_tool.cpp to display the menu.

**Comment by rhapsodyv** [comment]
Try recreate the PR from bugfix. The branch you used as base is totally out of the shape.

For example: you can create a new branch from bugfix and copy the code to make more menu working to this new branch.

It will a lot less work, than fixing all those conflicts.

The current state of this branch is a dead end.

**Comment by Malderin** [comment]
@rhapsodyv 
https://github.com/MarlinFirmware/Marlin/pull/20940

**Pull request closed without merging**
