### PR TITLE
Splitted due platforms for platform.io

### PR DESCRIPTION
**Pull request by RalphSch**
Changed/copied plattform DUE to ramps4due and radds.

### CODE REVIEW

**Comment by p3p** [comment]
The platformio.ini file will become far too cluttered if each motherboard has its own section, the solution to this will be either to leave it as is and expect users to change it in the platformio.ini or remove the motherboard define leaving it up to the user to specify in the config like usual, I think I prefer the latter.

(There's nothing wrong with the PR by the way and I realise there are other duplicates that only differ by motherboard, just pointing out it's probably a bad idea to go down that path)

**Comment by fiveangle** [comment]
Was thinking about this myself and fully agree @p3p - we need to come up with an agreed upon solution and better to figure it out earlier rather than later.

I think a better solution is to auto-fire a generic helper python script that picks up the board from the BOARD definition in Configuration.h and does the needful.  This way, the platformio.ini contains a single "Marlin" target entry.  I just don't know if that's possible.

Edit: Looks like there's probably many ways to skin this cat: http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#projectconf-advanced-scripting

-=dave

**Comment by Roxy-3D** [comment]
> we need to come up with an agreed upon solution and better to figure it out earlier rather than later.

> and expect users to change it in the platformio.ini or remove the motherboard define leaving it up to the user to specify in the config like usual,

Agreed to both thoughts.

Users are already used to having to specify a Mother Board type in Configuration.h  My vote is we continue with that until we have consensus on a better path.

**Comment by fiveangle** [comment]
What about board-specific stuff like "upload_speed" (like on the current anet10 entry) ?  If we want non-savvy users to have to tweak platformio.ini like the Configuration* files then wouldn't there need to be documentation how to configure it ?

**Comment by RalphSch** [comment]
Okay, I see the problem with putting all the controllers and their variants to platformio.ini but there are so many things broken or incomplete in Due code that anyone with a Due hardware (which is afaik the cheapest entry to 32bit) should be able to start as easy as possible (like it's for the other controllers which are already in platformio.ini). Simplifying this would only be a super small benefit for some developers but slows down anyone who might be willing to help. Maybe it's also to early to decide a better solution because a more stable Marlin 2.0 will bring in more people with more new/different/unknown hardware which may lead to more "special" cases like the Anet controller bootloader variants.

**Comment by fiveangle** [comment]
I'm starting to agreed… better to have the "pain" of mainataining the ini as a reminder that an auto-configuring script that pulls from configs so there's zero mainentance for the ini  needs to be made, else it will never get done.

**Comment by p3p** [comment]
I agree that there will be special cases which will require multiple ini sections for the same platformio board, but in the case where the difference is only the shield (or Motherboard) I still think that it shouldn't be controlled via the platformio.ini file and users should change the config as is required for all other motherboards. It doesn't add complexity it makes sure there is only one place the Motherboard is set 
 in all cases and avoids confusion.

**Comment by fiveangle** [comment]
I think everyone here has very valid points.  My humble suggestion:

1. We ideally write helper script(s) to have platformio.ini pull in all required info from the existing information (Configuration*.h, HAL, and pins_[board].h even augmenting with build-enviornment entries such as "#define BOOTLOADER_SERIAL_SPEED", etc if required) so platformio.ini is never touched at all.
2. Until No. 1 occurs, if we want to limit the platformio.ini file to architectures only and not allow granularity to the board level for cleanliness sake and to reduce overhead churn of managing all the PRs to it, then a clear document on the wiki explaining what options need to be set must be created before that happens.  This would correspond to cleaning up the ini to remove all board-specific entries (for ALL archs, not just the AVRs - all or nothing, e.g. every Due owner would have to manually set their platformio.ini board-specific parameters in their stub "due" section, just like they need to do in their Config*s).  Skeleton entries for all possible options available for each arch entry would need to be created (serial_speed, cpu_freq, etc) even if commented out, so each arch entry matches the as-yet-written documentation so users will find all required stub information for them to fill out, guided by the wiki instruction.
3. Until 2 happens, we accept all board-specific commits any board owner is willing to submit, willy nilly so that for now, users just select the board from the enviornment selection in PIO (the current model).

With this approach, we allow the ini to be "busy" now during this initial phase when more and more 32-bit boards are coming online so it is as easy as possible for them (with a smattering of 8-bit targets from users who happen to want to use PIO for compiling their AVR boards, perhaps Windows users due to Arduino build issues, etc).  The theory is that while the number of entries is low, the ini being being "busy" won't be that painful.  By the time the board-level entries become unwieldy No. 2 will happen, squashing all of it, or No. 1 (even better).

The reason I suggest allowing all, even for mobo-only changes, is that a new user doesn't know what they need to change for their board until they actually have it up and working - chicken, meet egg 😀.  It also allows us to see what kind of struggles people have with any board-specific build options they end up needing to specify in the ini, so we can better perform No 2. or No. 1 when inclined instead of just assuming every board will be easy to configure (which we don't really know explicitely yet).

Scott could even have a canned comment he puts on any new AVR board PR to the ini as well as the top of the ini saying that  "[the ini is intended for architecture level granularity and in the future any board level entries may be removed, requireing manual configuration for your specific board]" just so people find this info when they're considering sititng down and adding entries for AVR boards for the fun of it.

This isn't an ideal solution, but if we don't have No. 2 available to point new users to who are trying to bring a board up using PIO, it will be a nightmare in the issue tracker.

**Comment by thinkyhead** [comment]
I would prefer to close this PR without merging, since we don't want to override `MOTHERBOARD` from anyplace else. Is there a problem with PlatformIO not being able to build for these two boards under the single "DUE" heading?

**Comment by p3p** [comment]
I assume the issue is that you can't override the DUE MOTHERBOARD from the config file because its currently set in the platformio.ini, but like all platforms that support multiple boards (shields) it shouldn't be (in my opinion as was discussed above ;) ).

**Comment by fiveangle** [comment]
The issue isn't the over-writing of MOTHERBOARD IMO but that the current landscape has platformio.ini holding board definitions so if someone is going to claim we should reject board-level environment submissions in the platformio.ini then execute No. 2 above as I suggested and let's move on.  But we can't blame people for submitting board-level entries when that's how it appears things are supposed to be.

**Comment by fiveangle** [comment]
> I would prefer to close this PR without merging, since we don't want to override MOTHERBOARD from anyplace else.

It's already being done:

https://github.com/MarlinFirmware/Marlin/blob/1.1.x/platformio.ini#L40-L61

I didn't even know that the MOTHERBOARD define wasn't required until this thread discussion came up and I investigated.  So it's not suprising others don't know either (since nothing about this is written down anywhere).

**Comment by RalphSch** [comment]
@thinkyhead , yes, the MOTHERBOARD=BOARD_RAMPS4DUE_EFB in platfomio.ini in the DUE section made compilation for radds impossible. That's why I had to get a separate radds section with the right motherboard definition.

I already fixed some small bugs (reprapdiscount display now working, controller_fan compilation fixed) but there are still some things missing. I think some macros are not provided by the Due hal which are needed for pwm (case_light: USEABLE_HARDWARE_PWM) and timers (idle stepper disable, idle controller fan disable, auto exit lcd menu: PENDING).

**Comment by thinkyhead** [comment]
> But we can't blame people for submitting board-level entries when that's how it appears things are supposed to be.

> I didn't even know that the MOTHERBOARD define wasn't required until this thread discussion came up and I investigated. 

I understand the confusion now. So, yeah, we just want these to pertain to the CPU on the board, and not to specific boards unless there are differences at that level. The `MOTHERBOARD` should not have been set, and I simply never noticed it would lead to a problem. Also, no one thought to add documentation to the `platformio.ini` file, but then few (myself included) were fully familiar with it.

I'll document in `platformio.ini` that `MOTHERBOARD` should definitely _not_ be set there, but by editing `Configuration.h`.

As for this PR, I would prefer we keep everything except the override of `MOTHERBOARD`, even though it makes the two sections identical, and forces users to set it in `Configuration.h`. (They won't notice any difference.) I think it's totally fine to have identical sections in `platformio.ini` under different names if it makes it easier to choose the correct environment.

**Comment by Roxy-3D** [comment]
As a separate topic....   It would be very helpful if we could get BugFix-2.0.0 rebased against the current BugFix-1.1.x branch.  And whatever outstanding BugFix-2.0.0  Pull Requests merged into it.   Right now, It isn't clear what is the 'current' state of work.   I don't know what to pull in to have the 'latest'.   It would be good to give everybody a clean starting point for future work.

**Comment by fiveangle** [comment]
I was under the impression that bf2 and bf1 are now as in sync as they will ever be, and that any new items added to bf1 will be hand-ported over to bf2 by @thinkyhead when he's doing the merge ?

A while back I remember a discussion about this when people began submitting PRs to bf2 for general new features and it was decided to re-direct them at that time to bf1 for those, and focused on 32-bit porting and compile issues on bf2 ?

**Comment by thinkyhead** [comment]
> It would be very helpful if we could get BugFix-2.0.0 rebased against the current BugFix-1.1.x branch.

Unfortunately the codebases are no longer suitable for rebase, due to the splitting up and relocation of so many parts of the code. So all changes that are being merged into `bugfix-1.1.x` now need to be _manually_ reapplied to `bugfix-2.0.x` — and that's what I've been doing with incoming PRs this past week. You'll see in the closed PR log several pairs of entries for the same thing, only targeted at the two different branches.

This is necessary to clean up bugs in the 1.1.x branch and provide something up-to-date for our early adopters, while keeping 2.0.x in parity with those changes. The 1.1.x branch cannot really be retired until the 2.0.x branch gets an official release and takes over as the new current version. And 2.0.x cannot really be released until the platforms we're including are working relatively well.

To accelerate testing and get 2.0.x put through more of its paces, well, last time we found that having a lengthy period of RC releases led to a lot more testing and feedback, so that would be a good approach once there's enough confidence in the HAL.

Right now 2.0.x builds all the platforms that 1.1.x supports just great, so theoretically it could transparently "take over" as the new release codebase. But I think it's good to keep on this track of testing, fixing bugs, and generally improving the code for a while until it feels more solid overall.

**Comment by thinkyhead** [comment]
> when people began submitting PRs to bf2 for general new features and it was decided to re-direct them at that time to bf1 for those

Yes, and this has been working very well. People are generally more comfortable with the 1.1.x code, and the porting process is usually little more than cut-and-paste into the right files. The extra work is no burden, in that sense, and it gives me ample opportunity to get more accustomed to the relation between old and new code, and to come up with things for the to-do list.

Some little fixes from 2.0.x are getting back-ported to 1.1.x, but definitely the bigger patches should go to 1.1.x first, while almost all our dev focus on 2.0.x is in the HAL folder.

**Comment by thinkyhead** [comment]
So… In #7826 I've documented and reformatted `platformio.ini`, removing overrides of `MOTHERBOARD`, and leaving only a single [env:DUE] section. This should clear up confusion concerning what these sections apply to — not specific boards, but general architectures / platforms.

Maybe in future we can supply an alternative `platformio.ini` that lists every single entry in `boards.h`, but I have a feeling this would be messy. There's no [env] key for setting a readable name which would appear in a menu or list, so the UI wouldn't be too good.

**Pull request closed without merging**
