### PR TITLE
auto define NUM_SERVO_PLUGS based on SERVO PINS

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Had a user who defined #define NUM_SERVOS 3 when their board only had 1 defined
This did not cause any compile time errors when it should (in my view)

I found that Marlin already has this check which looked promising  

```
#if NUM_SERVOS > NUM_SERVO_PLUGS
  #error "The selected board doesn't support enough servos for your configuration. Reduce NUM_SERVOS."
#endif

```

But NUM_SERVO_PLUGS is effectively always set to 4

I've updated Marlin/src/pins/pins_postprocess.h to count the number of
SERVO[0..4]_PIN that are actually defined and set  NUM_SERVO_PLUGS appropriately

Now the above error is trigger as expected.

### Requirements

Setting NUM_SERVOS > defined servo pins.

### Benefits

It now errors that this is not a good idea.

### Configurations
eg https://github.com/MarlinFirmware/Marlin/files/13851845/IssueGithub.zip

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/26638

### CODE REVIEW

**Comment by ellensp** [comment]
Please check thoroughly, brain is down to 1 cylinder and is misfiring!

**Comment by thinkyhead** [comment]
Since `NUM_SERVOS` can be set automatically based on configured servo indexes I adjusted the sanity check message to allude to that.

**Comment by thinkyhead** [comment]
As usual, found a number of things to adjust in relation to the topic. Mainly, extending support for up to 6 servos in all instances where all the servos are referenced.

**Comment by ellensp** [comment]
Seems to still function as desired

**Pull request merged**
