### PR TITLE
Basic support for Azteeg_X5_GT

### PR DESCRIPTION
**Pull request by alexxy**
Basic support for Azteeg X5 GT board.

Signed-off-by: Alexey Shvetsov <alexxy@gentoo.org>

### CODE REVIEW

**Comment by tcm0116** [comment]
You'll want to undo the changes to Marlin/Configuration.h and Marlin/Configuration_adv.h since those are the default configuration files.

**Comment by alexxy** [comment]
Ok

**Comment by alexxy** [comment]
@tcm0116 any ideas about endstop behavior?

**Comment by tcm0116** [comment]
I didn't realize, but the Azteeg X5 G5 is a controller and not an entire printer. We usually just define pins files for controllers (if needed) and example configuration files for entire printers. 

I did notice that you have all of the `USE_[X|Y|Z][MIN|MAX]_PLUG` defines enabled in Configuration.h. Does your setup have dual endstops? If not, you should disable the ones you're not using.

**Comment by tcm0116** [comment]
Also, have you tried using `M43` to see what's happening with the endstops? You might want to try is using my branch from #8119 as I fixed some issues with `M43`.

**Comment by alexxy** [comment]
Endstops are fixed. Issue was:
This board has a switch for endstops (5v or 3.3v) by default its 3.3v, mine endstops are 5v. 
Also pin numbers for endstops are fixed, so they are actualy working.

Next step is check servo (board has one dedicated servo pin, and some of endstop pins can be mapped to servo signals)

**Comment by alexxy** [comment]
Servos also working, its possible to map some unused endstop pins as servos

**Comment by alexxy** [comment]
Can someone merge this PR?

**Pull request merged**
