### PR TITLE
make use of dispays capabillitys and fit to taste language_de.h

### PR DESCRIPTION
**Pull request by AnHardt**
make use of dispays capabillitys and fit to taste.

Now only with words what contain Umlaute.

Better translation in #1431

### CODE REVIEW

**Comment by CONSULitAS** [comment]
+1 from me. :+1: 
Reasonable first step. We can improve later. Thanks Andreas.

Cheers Jochen

**Comment by JustAnother1** [comment]
thanks for doing this. looks good.

A better description for UMLAUTE_DE 4 might be a possible improvement, or is this just me?
//#define UMLAUTE_DE 4 // for my (your) way

Something like "avoiding Umlaute by rephrasing" or "intelligent wording that doe not use Umlaute" ?

**Comment by AnHardt** [comment]
Hi again @JustAnother1 
My intention was: 'fill in what you want'. Three examples on top.

**Comment by thinkyhead** [comment]
#1431

**Comment by JustAnother1** [comment]
I saw this as complete list of available option, So uncomment the one you want. Therefore 4 would be the one with "Hauptauswahl.." and "Vorheizen PLA" and "Duese"

This should not stop merging, it just got me confused,...

**Comment by AnHardt** [comment]
We can have some more or less good Umlaute on the U8glib displays out of the box

#if DISPLAY_CHARSET==3 // U8glib
#define STR_Ae "\304" // yes
#define STR_ae "\344" // yes
#define STR_Oe "\326" // yes
#define STR_oe "\326" // no
#define STR_Ue "\334" // yes
#define STR_ue "\334" // no
#define STR_sz "\337" // yes
#define STR_Deg "\260" // yes
#endif

Sadly mussing 'ö' and ü''

\000 - \077


\100 - \177


\200 - \277


\300 - \377

**Comment by thinkyhead** [comment]
I like the approach you last suggested in #1418. I think it's a good idea to put the custom character options in `language.h` and use those defines in `language_de.h`. We can add some logic to language.h to pick the appropriate umlaut characters based on the LCD options, and we can allow users to override that with a define in Configuration.h as part of the LCD options.

**Comment by AnHardt** [comment]
Umpf. Definitions in language.h are not available in language_de.h because  language_de.h is caled by language.h?

No. It works! :-)

**Comment by AnHardt** [comment]
Please don't merge this. Will update #1434 soon.

**Pull request closed without merging**
