### PR TITLE
Derive NUM_AXES from *_DRIVER_TYPE

### PR DESCRIPTION
**Pull request by ellensp**
### Description

User are defining driver types for axis I,J,K,U,V,W without increasing NUM_AXES. This causes many compile errors.(as expected) 
Added a sanity check to warn not to do this.

### Requirements

Set
I_DRIVER_TYPE with NUM_AXES < 4
J_DRIVER_TYPE with NUM_AXES < 5
K_DRIVER_TYPE with NUM_AXES < 6
U_DRIVER_TYPE with NUM_AXES < 7
V_DRIVER_TYPE with NUM_AXES < 8
W_DRIVER_TYPE with NUM_AXES < 9

### Benefits

Less confused users

### Related Issues
Issue https://github.com/MarlinFirmware/Marlin/issues/24103

### CODE REVIEW

**Comment by DerAndere1** [comment]
An alternative would be to remove the `NUM_AXES` setting from configuration.h and deduce it internally from the `*_DRIVER_TYPE` definitions. But the good thing about the the explicit `NUM_AXES` setting is that it makes documentation and error messages simpler.

**Comment by ellensp** [comment]
NUM_AXES is used internally in Configuration.h So quite difficult to do that  (without adding excessive code to Configuration.h)

**Comment by thinkyhead** [comment]
> An alternative would be to remove the `NUM_AXES` setting from configuration.h and deduce it internally from the `*_DRIVER_TYPE` definitions.

Giving that a try now. It seems to be fully consistent with all example configs.

**Comment by thisiskeithb** [comment]
The changes from this PR / https://github.com/MarlinFirmware/Marlin/commit/b37d13af7278c241064b61279e7e8538a03206a3 now break on any config that doesn't explicitly define driver types.

Before, A4988's were assumed when undefined.

**Pull request closed without merging**
