### PR TITLE
Add Danish translations

### PR DESCRIPTION
**Pull request by Wackerbarth**
This is an effort to rework #2416. Originally submitted by @Simonm12.

Someone who speaks (read) the language needs to verify the entries and provide additional updates for the untranslated items.

### CODE REVIEW

**Comment by AnHardt** [comment]
@boelle 
Would you please be so kind to have a look on this?

**Comment by boelle** [comment]
on it

**Comment by boelle** [comment]
not sure why i cant edit thou i'm logged in:

but here a copy of my notepad:

first one comes twice??

+#define MSG_COOLDOWN                        "Afkøl"
+#define MSG_DISABLE_STEPPERS                "Slå stepper fra"
+#define MSG_SET_HOME_OFFSETS                "Sæt home offsets"
+#define MSG_SET_ORIGIN                      "Sæt origin"
+#define MSG_SWITCH_PS_ON                    "Slå strøm til"
+#define MSG_SWITCH_PS_OFF                   "Slå strøm fra"

+#define MSG_NOZZLE                          "Dyse"
+#define MSG_NOZZLE1                         "Dyse2"
+#define MSG_NOZZLE2                         "Dyse3"

+#define MSG_FAN_SPEED                       "Blæser hastighed"

+#define MSG_HEATING                         "Opvarmer..."
+#define MSG_HEATING_COMPLETE                "Opvarmet"
+#define MSG_BED_HEATING                     "Opvarmer plade"
+#define MSG_BED_DONE                        "Plade opvarmet"

+#define MSG_END_HOUR                        "Timer"
+#define MSG_END_MINUTE                      "Minutter"

+#define MSG_BED                             "Plade"

+#define MSG_POSITION_UNKNOWN                "Home X/Y før Z"

+#define MSG_CONTROL_RETRACTF                "Tilbagetræk  V"

+#define MSG_USERWAIT                        "Venter på bruger..."
+#define MSG_RESUMING                        "Forsætter printet"

+#define MSG_PAUSE_PRINT                     "Pause printet"
+#define MSG_RESUME_PRINT                    "Forsæt printet"

unsure on these ones:

+#define MSG_RETRACT                         "Retract"

**Comment by boelle** [comment]
i will run through them again once these initials ones has been corrected

**Comment by Wackerbarth** [comment]
Transfered to MarlinDev

**Pull request closed without merging**
