### PR TITLE
Park heads with electromagnet

### PR DESCRIPTION
**Pull request by alexkv**
Printing heads parking algorithm applicable for CoreXY or HBot kinematics.
It implies the location of all printing heads on one side of the 
printer and their fixation with electromagnet.
This scheme was developed for more than 2 printing heads.

Please find an example here: https://youtu.be/JolbsAKTKf4

### CODE REVIEW

**Comment by chai-md** [comment]
This looks similar to SWITCHING_TOOLHEAD except for servo or electromagnet.
Could this share codes and settings with SWITCHING_TOOLHEAD?

**Comment by alexkv** [comment]
> This looks similar to SWITCHING_TOOLHEAD except for servo or electromagnet.
> Could this share codes and settings with SWITCHING_TOOLHEAD?

Thanks for your comment, it's a good idea. I considered how to do it and merged configs and shared some params. 
But there are some issues to share code in tool_changer.cpp, the existing MAGNETIC_SWITCHING_TOOLHEAD is for nonelecrtomagnets and it uses a specific scheme of a printing head holding. That's why sharing will require a lot of 'if's even in the very beginning. And I think it will be very difficult to support both schemes in one function.

**Comment by chai-md** [comment]
I have a idea that ELECTROMAGNETIC_SWITCHING_TOOLHEAD is sharing with SWITCHING_TOOLHEAD, not MAGNETIC_SWITCHING_TOOLHEAD, because of motions.

It looks that electromarnetic_switching_toolhead() is able to share codes with switching_toolhead_tool_change() except for est_*_solenoid() or MOVE_SERVO().
In the point of configurable Z-hop and detailed descriptions, I'm prefer the former.

**Comment by thinkyhead** [comment]
Squashed and rebased. To get the latest code into your working copy:
```
git fetch origin
git checkout ph_parking_scheme_with_electromagnet
git reset --hard origin/ph_parking_scheme_with_electromagnet
```

**Pull request merged**
