### PR TITLE
[1.1.x] Mistake

### PR DESCRIPTION
**Pull request by RowanMeara**

### CODE REVIEW

**Comment by Roxy-3D** [comment]
It is strange Travis isn't finding this bug...   We are missing a right bracket here:

```cpp
     soft_pwm_count_fan[1] = ((soft_pwm_count_fan[1] & pwm_mask) + soft_pwm_amount_fan[1) >> 1;
```

**Comment by RowanMeara** [comment]
The travis script could use an update.  There are a bunch of features that are not tested at all.

**Comment by RowanMeara** [comment]
Although we're not going to be using the 1.1.x branch much longer so it's probably not worth bothering.

**Comment by Roxy-3D** [comment]
No...   The 1.1.x branch isn't being abandoned.   A lot of people will want something like it that is only getting bug fixes.

This line needs to be fixed because it is missing a right brace.   Normally, I can edit the commits.  But GitHub isn't allowing me to do that for this Pull Request.

```cpp
-          soft_pwm_count_fan[1] = (soft_pwm_count_fan[1] & pwm_mask) + soft_pwm_amount_fan[1] >> 1;
+          soft_pwm_count_fan[1] = ((soft_pwm_count_fan[1] & pwm_mask) + soft_pwm_amount_fan[1) >> 1;
```

**Comment by RowanMeara** [comment]
Yeah, I force pushed to squash some commits together which apparently killed the pull request.  I can't reopen it either.

**Comment by fiveangle** [comment]
> A lot of people will want something like it that is only getting bug fixes

Uhhh... that's not happening at all of course :)   Everything is getting cross-ported as far as I can tell.  

I agree that at some point 1.1.x should be for bugfixes only but that's simply not happening at the moment.  Once the Arduino IDE path length issue on Windows is resolved, maybe convince Scott to roll 1.2 as the last 1.x "freeze" release, then ONLY bugfixes from then on — no optimizations, "prettyfying" code, no new boards, no new features, just bugfixes for 1.x reported issues and users-submitted board-specific pin file updates ?

And that that point, the need for additional TravisCI tests sould drop to nil because the test coverage would have to rise exponentially to be useful, since the bug reports should drop accordingly: additional effort in Travis won't be likely to catch additional issues for the minor changes.

**Pull request closed without merging**
