### PR TITLE
Python3 AB compatibility

### PR DESCRIPTION
**Pull request by GMagician**
Now AB can works with python3

This is my very first job with python, please forgive me if fix is not done as "state of art"

### CODE REVIEW

**Comment by GMagician** [comment]
I have python3 and it works as expected. Can't test with python2

**Comment by GMagician** [comment]
mmmm to open PR I had to merge latest marlin...now I get a:

> UnboundLocalError: local variable 'auto_build' referenced before assignment

message at end of build

**Comment by sl1pkn07** [comment]
hi

is not atom deprecated in PIO in favour of VScode?

https://github.com/MarlinFirmware/MarlinDocumentation/issues/176

greetings

**Comment by GMagician** [comment]
@sl1pkn07 this script is also used by VScode extension

**Comment by sl1pkn07** [comment]
~~~
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/Creality Ender 3/Marlin/buildroot/share/vscode/AutoBuildMarlin]|
└───╼  grep -R atom
extension.js:    terminal.sendText("python buildroot/share/atom/auto_build.py build");
extension.js:    terminal.sendText("python buildroot/share/atom/auto_build.py clean");
extension.js:    terminal.sendText("python buildroot/share/atom/auto_build.py upload");
extension.js:    terminal.sendText("python buildroot/share/atom/auto_build.py traceback");
~~~

i see. but i thik, if Atom is now deprecated on PIO, is not better move that scripts to vscode folder and remove the Atom folder?

**Comment by GMagician** [comment]
>  is not better move that scripts to vscode folder and remove the Atom folder?

That's not up to me. I saw thinkyhead updated this and I found it was not working on my Win10 due to Python 2/3 incompatibility. I just fixed that so now I can compile my platform without changing everytime .ini file

**Comment by thinkyhead** [comment]
For VSCode it looks like we can just read the `MOTHERBOARD` setting (`pins.h`, etc.) and present an interface to start build/upload/test/clean inside of the AutoBuildMarlin view, entirely from the `extension.js` file. Once that interface is built, `Tk` and Python will no longer be needed to present the interface or to initiate the build.

**Pull request merged**
