### PR TITLE
LULZBOT_TOUCH_UI: Only use %S on AVR

### PR DESCRIPTION
**Pull request by marcio-ao**
I noticed that using "%S" in "sprintf" does not work on the Due. Grrrr.

With this PR:

- Broke out formatting routines into a separate file
- Ensured compatibility with AVR and non-AVR platforms
- Fixed reliance on AVR-only "%S" in sprintf
- Turned off GCC warnings due to non-standard AVR use of "%S" on a file specific way (rather than in Makefile)

### CODE REVIEW

**Comment by thinkyhead** [comment]
What is `%S` designed to do differently from `%s`?
I will Google to see if there's a general answer.

**Comment by sjasonsmith** [comment]
> What is `%S` designed to do differently from `%s`?
> I will Google to see if there's a general answer.

Microsoft uses %S to format char strings when using formatting functions expecting wchar_t strings, and vise-versa. It looks like gcc does something similar. I wouldn't be surprised at it being missing from implementations that don't use wchar_t.

**Comment by thinkyhead** [comment]
Back in my day we had only 127 ASCII characters. And we liked it!

**Comment by marcio-ao** [comment]
> Microsoft uses %S to format char strings when using formatting functions expecting wchar_t strings, and vise-versa. It looks like gcc does something similar. I wouldn't be surprised at it being missing from implementations that don't use wchar_t.

[AVR bastardized %S](https://forum.arduino.cc/index.php?topic=293408.0) for reading strings from PROGMEM, which differs from the standards which says "%S" specifies "wchar_t". So while you can pass "PROGMEM const char*" to "sprintf" using "%S" on AVR, GCC issues a warning about it since it is expecting "wchar_t", as per the standards.

My code uses the non-standard AVR "%S" as an optimization, as it avoids having to copy the strings to RAM, and it also turns off the compiler warning that would otherwise come into play.

In a future PR, I'll add more code documentation on this.

**EDIT:** According to [this](http://avr.2057.n7.nabble.com/Printf-S-printing-from-PROGMEM-not-functional-compiler-error-td23020.html), AVRs use of uppercase S is valid according to the standard:

"In general, the C standard reserves lowercase formatting letters for
future standardized conversions, but leaves other characters (so
namely uppercase letters) for "extensions".

Thus, avr-libc's use of %S for progmem strings is fully standards
compliant.  It's GCC here that applies wrong assumptions.  It would be
cool if we could somehow "tune" that in the avr-libc printf()
prototype (to avoid the pointless warning), but I'm not enough of a
GCC expert on that."

**Comment by marcio-ao** [comment]
> Back in my day we had only 127 ASCII characters. And we liked it!

Supporting European languages was hard enough. If anyone asks me to implement Chinese, I'll take up tomato farming instead.

**Pull request merged**
