### PR TITLE
M919 : Chopper Timing

### PR DESCRIPTION
**Pull request by thinkyhead**
The PR #23333 suddenly became corrupted, so this PR is a squashed copy, continuing with some updates to fix parameter handling.

### CODE REVIEW

**Comment by magnificu** [comment]
... and now how can I make commits to this PR?

**Comment by magnificu** [comment]
I think those conditions will create unnecessary updates of the ct struct.
e.g. I1 parameter will do this:
ct = CHOPPER_TIMING_X;
ct = CHOPPER_TIMING_X2 (this struct values will be applied)
```cpp
     #if AXIS_IS_TMC(X) || AXIS_IS_TMC(X2)
        case X_AXIS:
          #if AXIS_IS_TMC(X)
            if (index <= 0) ct = CHOPPER_TIMING_X;
          #endif
          #if AXIS_IS_TMC(X2)
            if (index < 0 || index == 1) ct = CHOPPER_TIMING_X2;
          #endif
          break;
      #endif
```
This should be better.
e.g. I1 parameter will do this:
ct = CHOPPER_TIMING_X2
```cpp
     #if AXIS_IS_TMC(X) || AXIS_IS_TMC(X2)
        case X_AXIS:
          #if AXIS_IS_TMC(X)
            if (index == 0) ct = CHOPPER_TIMING_X;
          #endif
          #if AXIS_IS_TMC(X2)
            if (index == 1) ct = CHOPPER_TIMING_X2;
          #endif
          break;
      #endif
```

**Comment by thinkyhead** [comment]
> how can I make commits to this PR?

You must add my fork as a remote in your working copy, check out the `remake-pr-23333` branch, make new commits, then push a copy of that branch to your fork (i.e., "`origin`"). You can then submit a PR to my `remake-pr-23333` branch, and when I accept your commits they become part of this PR.

Getting this branch into your working copy:
```
git remote add --fetch thinkyhead git@github.com:thinkyhead/Marlin.git
git checkout thinkyhead/remake-pr-23333 -b work-m919-pr-23400
```
Pushing your work:
```
git push --set-upstream origin work-m919-pr-23400
```
At that point you may use GitHub Desktop to start a PR (targeted to `thinkyhead/remake-pr-23333`) with the **Branch > Compare on GitHub** command.

**Comment by magnificu** [comment]
@thinkyhead 
I get an error when compiling
```
Marlin/src/gcode/feature/trinamic/M919.cpp:27:19: error: missing binary operator before token "("
   27 | #if AXIS_COLLISION('I')
      |                   ^
```
If I comment out this if works fine
```cpp
#if AXIS_COLLISION('I')
  #error "M919 parameter collision with axis name."
#endif
```

**Comment by thinkyhead** [comment]
CI and I are not able to reproduce your "missing binary operator" error. Do you see `AXIS_COLLISION` defined in `types.h` ?

**Comment by magnificu** [comment]
Marlin/src/core/types.h does not contain "AXIS_COLLISION"

**Comment by thinkyhead** [comment]
> Marlin/src/core/types.h does not contain "AXIS_COLLISION"

It should!

**Pull request merged**
