### PR TITLE
Fix M503C

### LINKED ISSUE #25501: [BUG] `M503 C` does not write configuration files to SD card.
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When building a firmware with `CONFIGURATION_EMBEDDING` enabled, the configuration of that firmware is supposed to be written to the SD Card when `M503 C` is used.

Currently, no configuration files are written to the SD card.

```
Recv: Cap:CONFIG_EXPORT:1
...
Send: M503 C
Recv: echo:; Linear Units:
Recv: echo:  G21 ; (mm)
...
Send: M22
Recv: echo:SD card released
```

No files are written to the SD card as expected.

### Bug Timeline

_No response_

### Expected behavior

As per documentation:
https://marlinfw.org/docs/gcode/M503.html

[C] 2.0.9.3 `CONFIGURATION_EMBEDDING` | Save the embedded configuration ZIP file to the SD Card or Flash Drive.

### Actual behavior

No files are written.

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

_No response_

### Electronics

_No response_

### Add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by GMagician**
This fixes #25501

I've replicated @ellensp fix suggestion but I had a board reboot due to PROGMEM data source.

Not sure this is the best solution but it works

### CODE REVIEW

**Comment by ellensp** [comment]
Doesn't work on AVR.. file is created of correct length but does not contain correct data.  (on a atmega2560)
Have not  event tried it on stm32...

**Comment by GMagician** [comment]
> Doesn't work on AVR.. file is created or correct length but does not contain correct data.

that's weird. With my board and yours fix suggestions I had a 0 file size + board reboot

Edit: My board is stm32

**Comment by ellensp** [comment]
basically my solution is not correct/complete and this pr based on it is premature. Which is why it was sitting there...

**Comment by GMagician** [comment]
@ellensp as per your wish, but this solve the problem on stm32 and it also should on avr

**Comment by ellensp** [comment]
I just retested this on ramps and it worked fine!!!!!!!

I have no idea why it didn't work for me when it was testing it months ago...

Please reinstate, my bad.

**Comment by GMagician** [comment]
@ellensp not sure you did what I did but I suspect that using MediaFile call you pass the pointer as a standard ram pointer. That's because you got a correct size but wrong contents. Not sure why on stm32 it reboot the board since AFAIK stm32 doesn't have the same flash memory access method used by avr. But as I stated before maybe there is a better way to achieve what I did, it comes in mind to create a new method in MediaFile class that accepts P_STR pointers

**Comment by GMagician** [comment]
> Please reinstate, ...

Are you asking me to reopen PR (Not sure translator did correct job)? Isn't possible to reopen it from github?

Edit: I tryed a new translation and now I get a more "sensed" translation

**Pull request closed without merging**
