### PR TITLE
Define STM32F1 GPIO for the preprocessor

### PR DESCRIPTION
**Pull request by tpruvot**
Allow to fix this kind of problem:

#if PC8 == PB0
   #error "Something weird !"
#endif

cf. https://stackoverflow.com/questions/34677148/why-does-the-c-preprocessor-consider-enum-values-as-equal

### CODE REVIEW

**Comment by tpruvot** [comment]
so, there is one (small) model which could create issues with the 3 last pins, the STM32F103C

which has :
```
enum {
    PA0,PA1,PA2,PA3,PA4,PA5,PA6,PA7, PA8,PA9,PA10,PA11,PA12,PA13,PA14,PA15,
    PB0,PB1,PB2,PB3,PB4,PB5,PB6,PB7, PB8,PB9,PB10,PB11,PB12,PB13,PB14,PB15,
                                                            PC13,PC14,PC15
};
```

**Comment by trouch** [comment]
Was that obvious !
I thought I was missing a pre-compiler trick 😅

**Comment by thinkyhead** [comment]
See `buildroot/share/PlatformIO/variants` for how we handle the more complex cases.

**Comment by thinkyhead** [comment]
…and `HAL_AVR/fastio_AVR.h` plus `HAL_AVR/fastio/` for how we organize variants when there are more than just a few.

**Pull request merged**
