### PR TITLE
Added option for graphical overlay for Z-offset (Resubmission of #7350 and #7586)

### PR DESCRIPTION
**Pull request by marcio-ao**
Resubmision of #7350 and #7586.

I deleted the repo on GitHub and started fresh with a new fork. Hopefully things match up now. Third try is a charm?

### CODE REVIEW

**Comment by thinkyhead** [comment]
Seems solid now, thank you!

**Comment by Tannoo** [comment]
How do I correct the graphics the correct way?

The graphics overlay is only displaying about every other line. When I move the bitmap data to `ultralcd.h`, then all is fine. When it's in the `dogm_bitmaps.h` file, it's all messed up.

**Comment by thinkyhead** [comment]
There should be no difference. The `#include` keyword makes `dogm_bitmaps.h` and `ultralcd.h` form one big blob of text. Perhaps the way it's being drawn is inappropriate, and this only manifests under certain conditions. Compare to other code that draws to the screen.

**Comment by Roxy-3D** [comment]
.h files should not generate code.   We need everything in compliance with that rule.   The whole problem with the ultralcd code is the .h files generate code.   That needs to be fixed.

**Pull request merged**
