### PR TITLE
Update JYERSUI by LCH-77

### PR DESCRIPTION
**Pull request by LCh-77**
This pull request modernizes JYERSUI while respecting the philosophy and code of Jacob.
Some modules were modded by me to be used in the UI, proper authorship is cited.
An enhanced version can be found here: https://github.com/LCh-77/Marlin/tree/bugfix-2.1.x_JYERSUI-Enhanced

- PID plot
- Gcode preview
- Host Action Menu
- Colorize UI
- Junction Deviation
- LED lights control
- Shows boot screen when reset the printer
- Firmware retracts menu
- Off line, on click and live Z-Offset
- Mesh leveling active indicator
- Selectable 115200/250000 baud rate
- Live brightness change
- Support for M75 Filename to print
- Probe settings menu
- Endstop diagnostic
- Screen lock

### CODE REVIEW

**Comment by thisiskeithb** [comment]
It would help to have screenshots of some of these features, particularly “Colorize UI”.

**Comment by LCh-77** [comment]
> It would help to have screenshots of some of these features, particularly “Colorize UI”.

Sorry, the camera of my mobile is really bad, that in particular is not important, just moves to the dwin_defines.h some default UI colors for easy access and change.

**Comment by tititopher68-dev** [comment]
@thisiskeithb @thinkyhead 
WARNING: My Pseudo Lch-77 is mine and it has been usurped! I am immediately reporting to Team Github! Unacceptable!!!!

**Comment by tititopher68-dev** [comment]
@LCh-77 Who are you . URSUPATEURS !!!!!

**Comment by thisiskeithb** [comment]
How are we supposed to know your alternate GitHub accounts were hacked?

**Comment by tititopher68-dev** [comment]
@thisiskeithb Because I am the author of the code from which this PR is taken (95% based on my build v3.0.0a and following)...My build was presented on May 28, 2022 via a Discord channel (https://discord.gg/ZeEUmc2g) and the first video on my work was also made on May 28, 2022 (https://youtu.be/SA1EKvyi9Fw) . The LCh -77 is none other than the cover of a nickname I used LCH77. This Lch-77 is not the author of the modifications. I strongly suspect Mricoc and CRCAu behind all this! Mriscoc had not published the plot.cpp and GcodePreview.cpp on May 28, 2022 since he kept them hidden in pre-compiled libraries.
Anyway, a complaint was filed today with Github and the French authorities against this LCh-77 and Thinkyhead for impersonation, deception, and violation of rights. The whole community around the Ender3V2 has been alerted and it's a big scandal for Marlin! SHAME ON MARLIN....I was warned yesterday by a member of your staff who disagreed with what you did!

Parce que je suis l'auteur  dont est issue ce PR (à 95 % basée sur ma build v3.0.0a et suivantes)...Ma build a été présentée le 28 mai 2022 via un canal Discord (https://discord.gg/ZeEUmc2g) et la première vidéo sur mon travail a été faite aussi le 28 mai 2022 (https://youtu.be/SA1EKvyi9Fw) . Le LCh -77 n'est autre que la reprise d'un pseudo que j'utilisais LCH77. Ce Lch-77 n'est pas l'auteur des modification. Je soupconne très fortement Mricoc et CRCAu derrière tout cela  !Mriscoc n'avait pas publié le 28 mai 2022 les plot.cpp et GcodePreview.cpp puis que il les gardait cacher dans des librairies pré-complilées. 
De toute façon, plainte a été déposée aujourd'hui auprès de Github et des autorités francaises contre ce LCh-77 et Thinkyhead pour usurpation d'identité, tromperie, et violation de droits. Toute la communauté autour de la Ender3V2 a été alertée et c'est un gros scandale pour Marlin ! HONTE A MARLIN....J'ai été prévenu hier par un membre de votre staff en désaccord avec ce que vous avez faits !

**Comment by tititopher68-dev** [comment]
@thisiskeithb

In addition, the opening of this Lch-77 account corresponds to mine. The facts are very very very serious! The Lch-77 Github was created long after May 28, 2022!

De plus l'ouverture de ce compte Lch-77 correspond au mien. Les faits sont très très très grave ! Le Github de Lch-77 a été créé bien après le 28 mai 2022 !

**Comment by tititopher68-dev** [comment]
@thisiskeithb 
I immediately request the removal of this PR is of this commit!

**Comment by thinkyhead** [comment]
What are you on about? Is there still confusion about Marlin GPLv3 licensing? If you distribute a binary, you must also give the recipient the code, and they are free to submit that code if they wish. It is not forbidden by any license. The code received strongly resembles code from @mriscoc and there is nothing particularly innovative in it, if I am TBH.

**Comment by tititopher68-dev** [comment]
> How are we supposed to know your alternate GitHub accounts were hacked?

Parce votre "mentor Thinkyhead" est le complice !

**Comment by thinkyhead** [comment]
> J'accuse!

In my humble opinion, you silly fools are the usurpers and are utterly out of your limited little minds. What do you think you're doing, trying to create private and relicensed versions of a GPLv3 project?

**Comment by tititopher68-dev** [comment]
> What are you on about? Is there still confusion about Marlin GPLv3 licensing? If you distribute a binary, you must also give the recipient the code, and they are free to submit that code if they wish. It is not forbidden by any license. The code received strongly resembles code from @mriscoc and there is nothing particularly innovative in it, if I am TBH.

I am the author ! Tu as supprimé des lignes de codes qui sont les miennes à plein d'endroit, ensuite tu fais toi la confusion et en plus tu ne lis aucunes informations ! les preview et plot.cpp (entre autres) n'étaient pas publiés quand j'ai publié mon propre code le 28 mai 2022 ! OK ! Alors  tu supprimes de toi même ce commit de Lch-77 qui est le pseudo que vous avez utilisé et que j'ai crée en janvier 2022 et je retire ma plainte (qui elle sera instruite, confirmée ce jour).

**Comment by tititopher68-dev** [comment]
@thinkyhead Cela ira en justice ! et je montrerai l'autre côté sombre et prétentieux d'une partie de la Team Marlin. Cela faisait des mois que je ne suivais pas votre Discord et tout le reste. J'ai été averti, il y a une quinzaine de jour et en me demandant d'attendre que cela apparaisse sur ton Github,  par une personne de votre team qui m'a expliqué pas mal de choses sur votre attitude pédante, voir méprisante et sur cette manipulation au sujet de ce PR, détails avec des copies d'écran et d'échanges, etc...le tout transmis aux autorités policières à Paris. En tout cas les preuves que je suis bien l'auteur du code que tu as remanié pour affirmer maintenant ce que tu dis et écris, je les ai ! OK. Tu n'es pas une bonne et belle personne !

**Comment by thinkyhead** [comment]
I am not translating your French. Your behavior is reprehensible, and you should be ashamed.

**Comment by tititopher68-dev** [comment]
@thinkyhead C'est toi qui devrais avoir honte ....exemple ceci :https://github.com/LCh-77/Marlin/commit/457b832799d74bf6be148cd32c71bae146a6b211 est 100% de mes premières publication sur ma branche New_feature, et il y a en a plein comme cela. Je répète, tu supprimes ce commit...Fais ce que tu veux, ne traduit pas je m'en fous...De toute façon, tu peux être aux USA, tu peux toujours être poursuivi avec ce Lch-77 depuis la France.

**Comment by tititopher68-dev** [comment]
@thinkyhead @thisiskeithb ou encore cela : https://github.com/LCh-77/Marlin/commit/2153799a3e383147a38516d91c125248b745dea9 -> 100% my code Ok !!!

**Comment by tititopher68-dev** [comment]
@thinkyhead Si tu n'es pas Lch-77, tu en es très proche et tu le connais fort bien ! Tu peux me menacer mais, comme je te l'ai déjà dit, je ne fais jamais rien sans preuves ! OK....Et cette page est en Direct sur des réseaux sociaux !

**Comment by tititopher68-dev** [comment]
@thinkyhead Très bien ! tu supprimes ce qui ne t'arrange pas ! pas de problème j'ai fait des copies d'écrans et tu es en direct sur Discord !

**Comment by tititopher68-dev** [comment]
@everyone Pour être clair, LCh-77 n'est pas l'auteur du code du contenu publié par @thinkyhead. J'en suis l'auteur. Mon code a été distribué depuis le 17 décembre 2021 depuis la zone de discussion du Github Jyers (sous la référence #1905). Il s'est poursuivi sous la forme public sur cette branche : https://github.com/tititopher68-dev2/Marlin/tree/new_feature et en parallèle sur un Github non-public pour le développement. Lch-77 a rendu public son Github le 5 juin 2022 et il y a repris mon développement (build v3.0.0a) présenté le 28 mai 2022 sur Youtube (https://youtu.be/SA1EKvyi9Fw) et dont les sources ont été publiées sur notre Discord : https://discord.gg/ZeEUmc2g. Les publications de LCh-77 sont toujours postérieures aux miennes et sont copiées sans en respecter l'auteur. @thinkyhead essaie aussi de me faire passer pour un débile. 

To be clear, LCh-77 is not the author of the content code posted by @thinkyhead. I am the author. My code has been distributed since December 17, 2021 from the Github Jyers discussion area (under reference #1905). It continued in public form on this branch: https://github.com/tititopher68-dev2/Marlin/tree/new_feature and in parallel on a non-public Github for development. Lch-77 released its Github on June 5, 2022 and there resumed my development (build v3.0.0a) presented on May 28, 2022 on Youtube (https://youtu.be/SA1EKvyi9Fw) and whose sources were published on our Discord: https://discord.gg/ZeEUmc2g. The publications of LCh-77 are always posterior to mine and are copied without respecting the author. @thinkyhead is also trying to make me look like a moron.

**Comment by technik3D** [comment]
I read the latest comment from @CRCinAU , fellow Australian. I don't share his point of view. The facts quoted are not the reality. I followed this whole story. @CRCinAU  isn't the last to ignite this situation. Besides, who is this LCh-77 that appeared as if by chance? Astonishing and suspicious. Is it Jyers?

**Comment by sjasonsmith** [comment]
> I read the latest comment from @CRCinAU , fellow Australian. I don't share his point of view. The facts quoted are not the reality. I followed this whole story. @CRCinAU isn't the last to ignite this situation. Besides, who is this LCh-77 that appeared as if by chance? Astonishing and suspicious. Is it Jyers?

Also an astonishing coincidence that your GitHub account was created 16 minutes ago.

**Comment by CRCinAU** [comment]
> I read the latest comment from @CRCinAU , fellow Australian. I don't share his point of view. The facts quoted are not the reality. I followed this whole story. @CRCinAU isn't the last to ignite this situation. Besides, who is this LCh-77 that appeared as if by chance? Astonishing and suspicious. Is it Jyers?

You may not agree. That's fine. Multiple contributors to Marlin have agreed on this decision. I offered to update my comment based feedback from contributors, it was generally agreed to be accurate and a quick summary of the facts. A such, the comment stands as a true and accurate account of events.

Lets move past this toxic time and leave it as sorted and look to the future instead of fostering infighting and spreading the toxic traits.

**Comment by LCh-77** [comment]
What happened here? I didn't hack any account, this is my account, I think I didn't do anything wrong. Why is everyone fighting? 
I only took the published code from the other UI and adapted it to be compatible with Jacob code because I don't want the JYERSUI to die. I didn't change the authorship. You can see my repository and the evolution of my code. Please! don't remove JYERSUI!

**Comment by LCh-77** [comment]
> 



> @thisiskeithb @thinkyhead WARNING: My Pseudo Lch-77 is mine and it has been usurped! I am immediately reporting to Team Github! Unacceptable!!!!

That is false! that is my account!

**Comment by LCh-77** [comment]
> @LCh-77 Who are you . URSUPATEURS !!!!! Honte à toi de voler et de t'approprier mon travail. Honte à Marlin de ne pas faire la moindre vérification !!!

Please write in english, I don't know why you wrote that, is not your work, It's my work and others work that I cited.

**Comment by CRCinAU** [comment]
> Please write in english, I don't know why you wrote that, is not your work, It's my work and others work that I cited.

I haven't talked to you, but you may well just be an innocent person that has been caught in this toxic crossfire. You can see the stuff that the Marlin team has had to endure for many months now - which has ultimately brought us to this point.

Please don't take this personally - as it has no reflection on you or your contribution.

**Comment by LCh-77** [comment]
> How are we supposed to know your alternate GitHub accounts were hacked?

No, no, I don't hack any account.

**Pull request merged**
