### PR TITLE
[2.0.x] Bed PID edit & autotune on menu FR proposal

### PR DESCRIPTION
**Pull request by GMagician**
Added possibility to have Bed pid edit and autotune on LCD menu

This is the idea.
If accepted I'll fix configuration.h and update all examples and prepare also 1.1.x PR

### CODE REVIEW

**Comment by GMagician** [comment]
@thinkyhead I'll wait your feedback before consolidate/delete it.
I tested all menu parts but I can't test real execution since I don't have a printer ready yet (I saw led turning on so I think everything works as expected)

**Review by Wackerbarth — CHANGES_REQUESTED** [review]
I'm tried your code and it works as designed.
However, I would suggest a minor change -- Namely, make the allowed range of bed temperatures parametric rather than using constants.

Also, to make it easier to incorporate into my machine, I split the commit into multiple parts.

Please look at Wackerbarth:Bed_PID_Autotune_Menu for the details.

**Comment by Wackerbarth** [comment]
I don't usually utilize the panel to do this type of operation. However, in testing, I make the following observations:

1) The menu structure seems too "flat" with all of the PID elements in the same level.  We might consider pushing the bed parameters into the bed sub-menu and the hotted parameters into a parallel submenu.

2) It is very confusing to have the panel drop back to its "Ready" status soon after the Autotune starts (but long before it completes). I would like to see some type of "Autotune in Progress" display to indicate that the machine is "busy"

3) The default number of cycles for the M303 seems to be too low. It would be good to have a better method to decide that the calculated parameters are "stable", particularly when the "U1" option causes them to be activated before the user has an opportunity to review them.

**Comment by GMagician** [comment]
@Wackerbarth about parametric temperature I'm not so skilled with firmware to address it. I just replicated what is already done for hotends.
About other points I agree down the line:
1) In my printer I have 2 hotends and 1 bed and menu is overpopulated.
    Adding a submenu can be done (and maybe I can do that) but My first doubt is about code added to achieve current goals. I had to "duplicate" some defines and I don't know if there is a cleaner way to do that (I hope in some input from @thinkyhead)
2) I say again, i'm not so skilled (how repetitive I am)
3) Don't know why has been decided to use a little default number for cycles...I usually use 8 to be sure to repeat it more times and get (i hope) a better result

**Comment by AnHardt** [comment]
@GMagician 
Test:
Start autotune with a high amount of repetitions. Watch the temperature graph and the intermediate K-numbers. Write down the K-numbers.
Now start/stop the part cooling fan (or open a window , just alter conditions) and retest. You'll get different values for the Ks.
How many iterations do make sense? When is the improvement by more iterations smaller than the difference by different conditions?

**Comment by Wackerbarth** [comment]
@AnHardt
Your suggested test misses the point. True, the operating environment COULD change, however that is no excuse for terminating the estimation.

I find that successive cycles over-adjust the bias in a damped “ringing” pattern. As long as this variance is decreasing, additional cycles cause the values to converge on appropriate values for the ACTUAL conditions (rather than, as you propose, those for some POSSIBLE conditions).

In practice, I find that this oscillation needs 8-10 cycles before the actual “noise” limits further convergence.

**Comment by AnHardt** [comment]
Right. But conditions are always changing, even during the test. If the environment is not very carefully controlled improving the numbers for one special condition makes no sense.
If we would switch to another K-profile during printing a bridge, with part cooling fan, this would make more sense than, by default testing more iterations.

**Pull request closed without merging**
