### PR TITLE
Add HOST_ACTION_COMMANDS to extended M115 report.

### PR DESCRIPTION
**Pull request by apbarratt**
### Description

M115 provides a report of device capabilities enabled within the Marlin Firmware.  Host software such as Octoprint or Cura can use this information to detect features it can interact with and most importantly, warn users when features are not enabled that may cause issues.

An example of this would be the way Octoprint will present original Ender 3 owners with a warning that their stock firmware has no thermal runaway protection enabled.

Host software such as Octoprint also relies on the passing of Action Command messages from the printer to alert them to pause/cancel events taken on the printer itself.  However, if action commands are disabled in Marlin, there is currently no reliable and trusted way to check for this fact.

An example of this being a problem would be when a user chooses to pause or cancel a print through their printer's firmware run LCD interface, without action commands being sent, Octoprint continues to send Gcode to the printer, instructing it to carry on heating and printing as originally planned.

This PR will add an extra line to the M115 report that host software can begin to check for and warn users that the desired feature may not be enabled.

### Requirements

Printer with interface capable of triggering host action commands.

### Benefits

Allows host software such as octoprint to recognise when host action commands are not enabled and alert the user to any safety or user experience concerns this may address.

### Configurations

Ensure HOST_ACTION_COMMANDS is defined within Configuration_adv.h to see it shown as enabled in the M115 report.  Keep it commented out to see it shown as disabled.

### Related Issues

Unknown.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Once a new item for the `M115` report is accepted, you must also add it to the RepRap Wiki at https://reprap.org/wiki/Firmware_Capabilities_Protocol

CC: @MarlinFirmware/host-software-team

**Comment by apbarratt** [comment]
That makes sense. I'll be sure to do that if it's accepted :)

**Comment by apbarratt** [comment]
I've attempted to add a new section to the wiki to detail this proposed capability.  Unfortunately I simply can't seem to be able to convince the wiki to save my change.

It would have read as follows:

~~~
==Proposed definitions of capabilities==

=====Cap:HOST_ACTION_COMMANDS=====

A pull request exists at the time of writing to add [[G-code#Action_commands|HOST_ACTION_COMMANDS]] as a capability to be reported from the Marlin Firmware.  The pull request id is 21987.

The firmware has HOST_ACTION_COMMANDS enabled.
~~~

**Comment by foosel** [comment]
FWIW, the next version of OctoPrint's bundled FirmwareCheck plugin will support this and show an info message to users if a connection to a printer is initiated that has `HOST_ACTION_COMMANDS` in the capability report, but flagged as disabled (= firmware in principle does support it, but it's disabled by configuration).

image

**Comment by Foxies-CSTL** [comment]
Hi, 
Just a remark because I use this function for the acquisition of deployment and storage of removable probe. This function does not work anymore when the MeatPack plugin is activated on Octoprint and on the firmware. We still have the popup interaction but the printer ignores the acknowledgement and vice versa!
That's it.

**Comment by thinkyhead** [comment]
Thanks for the note, @Foxies-CSTL. It is definitely on point, and also worthy of a bug report of its own. Maybe I can find the issue by a quick glance at the code, but then again it might take a team of forensic experts to find the root gremlin.

**Comment by thinkyhead** [comment]
> can't seem to be able to convince the wiki to save my change.

It often takes two or three attempts, plus checking "Remember me" when logging in.

image

**Comment by thinkyhead** [comment]
Thanks for all the input. It is also good to have host action commands finally documented in a public space, and I'll be sure to keep that section maintained if anything changes.

**Pull request merged**
