### PR TITLE
⚰️ Remove BOARD_FYSETC_SPIDER_KING407

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

When BOARD_FYSETC_SPIDER_KING407 was added (50f79823d25841247d7420da4048b53109cb4488) it did not include a pins file.
With no pins file in over a year, it is highly unlikely this is being used by anybody.

### Benefits

Less code to maintain.

### CODE REVIEW

**Comment by sjasonsmith** [comment]
If @GerogeFu is still around, perhaps he can provide information about why this was never used.

**Comment by ellensp** [comment]
The pins are documented on their wiki, easy enough to add a pins file..

https://wiki.fysetc.com/FYSETC-SPIDER-KING/

**Comment by ellensp** [comment]
The missing file is here https://github.com/FYSETC/FYSETC-SPIDER-KING/blob/main/firmware/Marlin/Marlin/Marlin/src/pins/stm32f4/pins_FYSETC_SPIDER_KING407.h

The pins are also documented on their Wiki
https://wiki.fysetc.com/FYSETC-SPIDER-KING/

**Comment by sjasonsmith** [comment]
> The missing file is here https://github.com/FYSETC/FYSETC-SPIDER-KING/blob/main/firmware/Marlin/Marlin/Marlin/src/pins/stm32f4/pins_FYSETC_SPIDER_KING407.h

So, do we proactively pull that in, or treat it as an impartial addition and remove it? Does the board actually exist? Does anybody care that it is missing if it hasn't been added in over a year?

**Comment by ellensp** [comment]
Well the board is available on aliexpress, so eventually someone will want to put updated marlin on it.
So from my point of view we should pull in the missing pins file, verify it will at least builds, and leave it be.

**Comment by sjasonsmith** [comment]
> Well the board is available on aliexpress, so eventually someone will want to put updated marlin on it. So from my point of view we should pull in the missing pins file, verify it will at least build, and leave it be.

@ellensp do you want to do that? I just ran across this because it interfered with me executing a script to run through _every_ board in boards.ini to test symbol changes. It looked unused from the perspective of the Marlin codebase and I didn't go trying to hunt it down.

**Comment by ellensp** [comment]
@sjasonsmith yes I can do that.  working on it now.

**Comment by sjasonsmith** [comment]
OK, I'll go ahead and close this. Thanks!

**Pull request closed without merging**
