### PR TITLE
SKR E3 (mini/turbo): Enable usage of REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

### PR DESCRIPTION
**Pull request by kad**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER and CR10_STOCKDISPLAY
are in practice same, with small difference it timings for ST7920.
Thus, enabling it for SKR mini E3 and SKR E3 Turbo, where EXP3 wiring
is the same for both of those.

See https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/inc/Conditionals_LCD.h#L221-L230

### Benefits

It will allow to use stock Anycubic Mega Zero LCD with SKR mini MZ board.
It works with even timings for CR10_STOCKDISPLAY on SKR mini MZ and SKR mini E3 v2.0 boards,
but it is not straight forward understandable change that user should do in config while migrating from Anycubic Melzi board configs to SKR mini MZ.

### Configurations

```
#undef CR10_STOCKDISPLAY
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```

and try to build either for `LPC1769` target with `config/examples/Creality/Ender-3/BigTreeTech SKR E3 Turbo/Single Extruder` configs or for `STM32F103RC_btt` with `config/examples/Creality/Ender-3/BigTreeTech SKR Mini E3 2.0`

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I'm not sure this is a great idea since the E3 Turbo & E3 Mini boards only have a single EXP connector.

If users define `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` for these boards, it would allow users to think this LCD is supported without a custom wiring harness, so it'd be better to keep the error message to alert users about the supported controller types.

`REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` may allow users to think they can enable an LCD-based SD card which doesn't exist for `CR10_STOCKDISPLAY`.

**Comment by sjasonsmith** [comment]
I consider `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` to be a display with two EXP1/EXP2 cables, an encoder, and a build-in SD card slot.

If any of those are missing, then the display should not be called a REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER.

Calling this display a RRDFGSC seems no less confusing that calling it a CR10_STOCKDISPLAY. If multiple displays exist with the same pinouts and behavior as the CR10 display, then perhaps a more generic name is needed for that configuration.

**Comment by sjasonsmith** [comment]
@kad Can you provide a link to a web page that has details (or even pictures) of the display you wish to support?

**Comment by thisiskeithb** [comment]
> I consider REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER to be a display with two EXP1/EXP2 cables, an encoder, and a build-in SD card slot.

It can still get a little fuzzy since BigTreeTech TFTs have EXP1/2/3 ports for "Marlin Mode" operation and you use either EXP1+2 or EXP3 depending on the hardware combination and `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`/`CR10_STOCKDISPLAY` setting.

**Comment by sjasonsmith** [comment]
> It can still get a little fuzzy since BigTreeTech TFTs have EXP1/2/3 ports for "Marlin Mode" operation and you use either EXP1+2 or EXP3 depending on the hardware combination and `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`/`CR10_STOCKDISPLAY` setting.

I don't consider that fuzzy at all! It is not a RRDFGSC, it is just capable of emulating one.

**Comment by kad** [comment]
I have Anycubic Mega Zero printer that has Melzi clone kind of board with LCD12864 connected over EXP3 wiring schema.
According to vendor, that is `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`: https://github.com/ANYCUBIC-3D/MEGA_ZERO/blob/master/Configuration.h#L1651

Here is picture of LCD: https://ibb.co/42dM3sD
Here is original Melzi board with `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` working with BTT TFT35 E3 over EXP3 input. https://ibb.co/ZzhM9DD
Here is original LCD connected to SKR mini E3 V2.0 compiled with CR10_STOCKDISPLAY: https://ibb.co/349146r https://ibb.co/fHDff36

As I referenced, https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/inc/Conditionals_LCD.h#L221-L230
both `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and `CR10_STOCKDISPLAY` leads to `#define IS_RRD_FG_SC 1`. And in pins files for Melzi and BTT boards that also expands to defines only for `LCD_PINS_RS`/`LCD_PINS_ENABLE`/`LCD_PINS_D4`, which means `LCD_PINS_D5`-`LCD_PINS_D7` will be not defined/used in that setup.

Naming it somehow different is fine, but just to be specific, there are several SPI GLCD 12864 ST7920 based displays that are using just single data line (D4) and a bit different timings that some vendors call `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and in Creality vicinity is called as `CR10_STOCKDISPLAY`.

**Comment by ellensp** [comment]
I agree with @sjasonsmith 

REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER is a 128x64 lcd + encoder + **sdcard** It needs more than 10 pins. Even just the lcd and encoder is split over the two connectors.
 
CR10_STOCKDISPLAY is a 128x64 lcd + encoder, No sdcard. Ie fits on a single 10 pin connector

Your lcd interface seems to be neither of those. It needs its own name  

reusing REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER for this display would be confusing as anything.

**Comment by kad** [comment]
> CR10_STOCKDISPLAY is a 128x64 lcd + encoder, No sdcard. Ie fits on a single 10 pin connector 
> Your lcd interface seems to be neither of those. It needs its own name
> reusing REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER for this display would be confusing as anything.

I agree, and my initial intention was to generalize from vendor specific `CR10_STOCKDISPLAY` to something that would describe "ST7920 based 128x64 LCD, with encoder, using EXP3 wiring method".

**Comment by kad** [comment]
So, any suggestion for generic name for such "ST7920 based 128x64 LCD, with encoder and beeper, using single 10 pin wiring method" ? Or just update the comment that `CR10_STOCKDISPLAY` should be used in such scenarios?

**Comment by thisiskeithb** [comment]
> So, any suggestion for generic name for such "ST7920 based 128x64 LCD, with encoder and beeper, using single 10 pin wiring method" ? Or just update the comment that `CR10_STOCKDISPLAY` should be used in such scenarios?

Since `CR10_STOCKDISPLAY` works, I'd update the printer config to use that instead. Allowing `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` to be enabled on boards without two EXP connectors/enough pins is just asking for more support tickets.

**Comment by sjasonsmith** [comment]
I agree with just using CR10_STOCKDISPLAY for now.

It could make sense to declare both display types near each other, and have them both resolve to something like `HAS_EXP3_ST7920`, or perhaps even `HAS_EXP3_ULTIPANEL` but I haven't fully thought that through. There are several different flags like this, and I'm not sure which are tied to display alone vs display w/ encoder, buttons, etc.

One real question is whether we will see more consistency on what an "EXP3" pinout actually means. I suppose we may see more displays if the "standard" is "drop-in replacement on an Ender".

**Comment by kad** [comment]
`EXP3` connection style means Beeper (BEEPER_PIN),  Encoder (BTN_EN1,BTN_EN2,BTN_ENC), and ST7920 (LCD_PINS_RS,LCD_PINS_ENABLE,LCD_PINS_D4), +5V, GND and Reset. 

Even `CR10_STOCKDISPLAY` works, it might be not that descriptive name for generic "drop-in" kind of displays that might be used on other printers. 
I briefly looked trough example configs, even some variants of CR-10 are actually stating in configs "#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" (CR-10 S4/CrealityV1, CR-10 S5/CrealityV1,CR-10 V2, CR-10S), and I doubt that some of those actually using SD card on LCD side.

That makes me think, maybe in bunch of other places where configs referencing RRDFGSC are actually referring to variant without SD card? e.g. `Creality/Ender-3/FYSETC Cheetah/BLTouch/Configuration.h`, which is STM32F1 board, with similar connector (according to schematics: https://github.com/FYSETC/FYSETC-Cheetah/blob/master/1.1/Cheetah_Board%20V1.1%20SCH.pdf )

**Comment by thisiskeithb** [comment]
> I briefly looked trough example configs, even some variants of CR-10 are actually stating in configs "#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" (CR-10 S4/CrealityV1, CR-10 S5/CrealityV1,CR-10 V2, CR-10S), and I doubt that some of those actually using SD card on LCD side.

Those use two EXP cables to connect to the motherboard, not one which is why they don’t have `CR10_STOCKDISPLAY` enabled.

**Comment by sjasonsmith** [comment]
I am closing this, as I think we should not change the meaning for the RRDFGSC display.
It seems `CR10_STOCKDISPLAY` already satisfies the needs of this board, and that should just be used.

**Comment by kad** [comment]
@sjasonsmith Well, it partially satisfies, due to `CR10_STOCKDISPLAY` assumed timings (https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/inc/Conditionals_LCD.h#L221-L226):
```
  #define BOARD_ST7920_DELAY_1 DELAY_NS(125)
  #define BOARD_ST7920_DELAY_2 DELAY_NS(125)
  #define BOARD_ST7920_DELAY_3 DELAY_NS(125)
```
it would work for most, but some artefacts might be visible. But I agree about meaning of RRDFGSC, thus I will think and come up with better PR later that would be generic enough and would enable to customize delays.

**Comment by sjasonsmith** [comment]
@kad does it work fine if those timings are commented out in the Conditionals_LCD file?

**Comment by kad** [comment]
I haven't tried to comment those yet, but I noticed that on stm32f1 boards (SKR mini E3 or MZ) compared with Melzi, if using `CR10_STOCKDISPLAY` with such simple LCD there are scenarios that some pixels are not always updated. Sometimes it is noticeable when scrolling fast trough some numbers (e.g. Move Axis X/Y/... menu items positions). My initial suspicion was about those timings, but no good evidences yet on hand. I'm continuing to investigate and will report results later.

**Comment by sjasonsmith** [comment]
Ok, please try commenting them out and see how it behaves. Those timing were there for the old AVR boards. They have caused problems in the past and need to move. Everyone is afraid of breaking existing users so they have stayed there until now.

**Pull request closed without merging**
