### PR TITLE
Update thermistortables for Hisens Thermistor

### PR DESCRIPTION
**Pull request by Fourmi**

### CODE REVIEW

**Comment by Wackerbarth** [comment]
We need an explanation as to WHY the previous values are incorrect.

**Comment by Fourmi** [comment]
Hi Richard ,

My values are correct but too much values it's not good .

Thx 

Envoyé de mon iPhone

**Comment by AnHardt** [comment]
I see where the problem is.
In the old table is one point making the curve unsteady.
hisens thermistor
Likely a typo in the old table and should read:
201.125*OVERSAMPLENR,   170

This unsteadiness results in problems with the PID around that temperature.

The new table is a bit shorter than the old one, but is almost that smooth. -> OK!
The new table is a bit shorter than the old one, this will result in some less loops in analog2temp(). -> OK!
The new table differs about some tenth of a degree from the old one. As we do not know where the original data is from - and the author lost our trust because of the typo anyway - (in my opinion) we could merge this.

We **_could**_ merge it if we agree the error is bad enough to patch the `release` branch.
A PR against the https://github.com/MarlinFirmware/MarlinDev/tree/master is highly welcome.

**Comment by Wackerbarth** [comment]
This is the kind of thing that we would merge into 1.0.x. It doesn't deserve being the cause of a new release, but it should be included.  I'll merge it and patch up both trees. A second merge request isn't necessary.

**Pull request merged**
