### PR TITLE
Hacky Auto Updater for User Supplied Config Files

### PR DESCRIPTION
**Pull request by yash-fn**
### Description
A hacky bash script to auto update user supplied config files. Both config files within Marlin/Marlin folder are rebased against the lastest default config file. The user can then open the files within their favorite mergetool or within VSCode and quickly resolve any conflicts that appear. 

Motivation for this was the number of users who didn't know how to update their config files and were thus afraid to/unwilling to update to the latest marlin because they didn't want to put in the work to update their files. There was this one guy in the discord chat who just refused to learn how to rebase his files and kept complaining/asking others to do it for him. So for people like that just refer them to this tool and then make it their problem to resolve any merge conflicts. Over time, as this script improves, it can encourage people to always use the latest marlin firmware and could reduce the burden on devs dealing with bugs/problems with people using older versions of Marlin. 

### Requirements
None. Just ensure config files are located where they normally are and the script just does the rest on its own. 

### Benefits
+ Encourage Users to use the latest Marlin
+ Reduce burden on devs dealing with user problems running on older versions of Marlin
+ Hopefully can provide a template for command line averse users on how to manually rebase and update their configs. 

The ultimate goal of this tool should be to reduce burden on devs dealing with user problems related to older versions of marlin and for users who don't know how to update their configs. If we can provide a tool that makes it easier to for users to always use the latest Marlin but keep their modifications for things like Bltouch/etc, then mission accomplished. 

### Configurations
Probably best to say this script only works for config files with versions > 2.0.5.0
Untested for prior.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for the efforts. But a shell script is the wrong direction to help people who struggle with basic DIFF tools. Time would be better spent contributing to the "Auto Build Marlin" extension and helping to extend it to do this kind of thing.

**Comment by yash-fn** [comment]
Yeah. That's fair. It was hacky. But you like the idea, right? I will try and figure out how to implement it in the auto build project when I get the time.

**Comment by thinkyhead** [comment]
Ideally we'd have a complete MySQL database of all Marlin configuration options, extended with information about how each option maps from one Marlin version to another. Much of that information is already embodied in `SanityCheck.h`. Once the database is complete we could use that mapping information to convert configurations between different versions of Marlin. The tool would be interactive, so the user can be prompted to resolve ambiguities in the conversion.

Extensions for VSCode are built in HTML5 + CSS + node.js + Electron, and I already have some utilities prepared in the "marlin.js" class to parse configurations, and I am in the process of building an interface to edit the machine geometry that will exercise and demonstrate that class.

**Comment by yash-fn** [comment]
Oh wow. Looks like you've already been giving this some thought with a much a more comprehensive plan. I'll definitely take a look and see if there is anything I can contribute to make it happen.

**Pull request closed without merging**
