### PR TITLE
Infinite loop in manage_heaters when calling safe_delay

### PR DESCRIPTION
**Pull request by slowbro**
### Description

When `safe_delay()` is called, it executes `Temperature::manage_heater()` every 50ms of delay. However, if you call `safe_delay()` inside of `manage_heater()`, or something else does, it creates an infinite loop.

I'm not sure if this is the *best* way to do this, but it seemed better than creating a completely separate servo::move call that calls a different delay.

### Requirements

In #21406, this was caused by `SERVO_MOVE` in manage_heaters() when `CHAMBER_VENT` is enabled.

### Benefits

Fixes an infinite-loop bug.

### Configurations

See related issue.

### Related Issues

 #21406

### CODE REVIEW

**Comment by thinkyhead** [comment]
I reduced it to the minimum re-entry guard on `manage_heater`. It's not intrinsically bad for these methods to recurse in a controlled manner, but if `manage_heater` is making calls that further invoke `safe_delay`, that starts to become a problem and preventing recursion might only hide what is ultimately a spaghetti issue.

**Comment by slowbro** [comment]
Oh, nice. That's a lot cleaner :)

**Comment by thinkyhead** [comment]
I don't have a lot of notes on e297748b2253a8b15fea49cc244f34a537972a94. The rationale for using `safe_delay` in `Servo::move` is clear enough, since this might be a very long delay. But, it is annoying that `manage_heater` is then calling `Servo::move`.

**Comment by slowbro** [comment]
Yeah. I was thinking perhaps giving the servo module an idle task of its own that would manage moving the servos? Then, seemingly, we could control the velocity of the change as well by spreading it over multiple moves/idle calls.

**Comment by thinkyhead** [comment]
Since the chamber vent actually is a part of temperature management, it is appropriate that it is in `manage_heater`, and if the control for this vent is a servo there isn't much we can do about it except to go back to calling `delay` (which adds some risk for watchdog reset during servo / bltouch activities) or accept the need for this re-entry guard to keep everything tidy.

**Pull request merged**
