### PR TITLE
Rcbugfix - DHT Sensor

### PR DESCRIPTION
**Pull request by ghost**
The DHT sensor gives the option of showing the temp and relative humidity in your printing environment. A DHT11, DHT21, or DHT22 sensor and the DHT library listed in the configuration.h file are required.

This PR also has a display script correction that was hanging up the MBL process.

### CODE REVIEW

**Comment by ghost** [comment]
I guess this would have been cleaner if I had deleted the fork and started over. So, sorry for the number of commits. They were trying to clean up things to remove another feature. I guess I was just committing every little change I did instead of waiting until all changes were done.

**Comment by FHeilmann** [comment]
you can squash your commits by rebasing onto your own branch and force pushing afterwards

**Comment by ghost** [comment]
Will I be able to do that with this PR still open?

**Comment by FHeilmann** [comment]
should be possible. this PR tracks your feature branch so if you force push the related commits should update.

**Comment by ghost** [comment]
Ok....well, I've broken my side... lol
This might take me a while to repair.

**Comment by ghost** [comment]
Well.... so far, my GitHub desktop seems to be broken now. I tried to merge to my forked RCBugFix and it didn't like that for some reason... it won't let me undo it. It won't let me choose another branch in my fork. I is broken. I am done with GitHub for a few days.

The code works on my printer. I was just trying to share it. Sharing it has been the BIGGEST headache that still hasn't worked correctly.

So, my printer is running RCBugFix from 12/26/16 plus the RGB_Strip addition, the DHT_Sensor addition, the correction I did for the lcd hang-up, also added the option to auto-save the MBL mesh when it finishes. All of this works just fine.

I am willing to share. But, this just may have to stay local to me because GitHub and I aren't getting along.

**Comment by ghost** [comment]
I will add the full working code to another branch on my GitHub and you guys can do what you want with it, if you want.

**Comment by ghost** [comment]
https://github.com/Tannoo/Marlin.git

`RCBugFix_All_mods` branch.

**Comment by ghost** [comment]
I am re-submitting this now.

**Pull request closed without merging**
