### PR TITLE
Fixed bug: apply backlash compensation when directly translating between steps and position

### PR DESCRIPTION
**Pull request by tombrazier**
### Description

The backlash compensation code adds steps to the steppers. These extra steps are not replicated by functions like `set_current_from_steppers_for_axis()` and `sync_plan_position()`. This can cause subtle position errors.

This PR fixes the all the code in planner.cpp which translates directly between planner position and stepper stepcount. This resolves the issue in higher level functions like `set_current_from_steppers_for_axis()` and `sync_plan_position()`.

Example of the bug in action:
- `BACKLASH_DISTANCE_MM` has a non-zero Z component.
- `FIX_MOUNTED_PROBE`
- `AUTO_BED_LEVELING_BILINEAR`

When running `G29`: in `Probe::probe_at_point()` the Z axis moves downwards until the probe is triggered. The Z position is calculated from the Z stepper's step count. Then the Z axis moves upwards by distance `Z_CLEARANCE_BETWEEN_PROBES`. In this process, the Z axis reverses direction and extra steps are added to the Z stepper motor. Later, in `GcodeSuite::G29()`, `sync_plan_position()` is called and knowledge of the extra steps is discarded, essentially changing the stepper's position of Z=0. Any future call to `Probe::probe_at_point()` will now trigger at a different step count.

You can see this by running `G29` repeatedly. Every time you call it the entire mesh moves upwards or downwards from the last time.

### Requirements

None.

### Benefits

Fixes subtle effects in calibration code.

### Configurations

Enable BACKLASH_COMPENSATION.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Very good work! That was a subtle error, and this is an important feature for a lot of users.

**Comment by tombrazier** [comment]
Thanks. Took about a week to track down. On the plus side I found some others whilst I was at it, so expect some more PRs.

**Comment by InsanityAutomation** [comment]
Good to hear, there were issues reported with G425 when run with non zero values already applied awhile back I never had time to dig into as well. It was also prone to missing the rising edge of the signal on the cube and continuing the motion into the block... Im just getting back into things, so hopefully thats covered in youre list, and I can make it towards the idex stuff again soon.

**Comment by tombrazier** [comment]
@InsanityAutomation I did not have this on my list - which is more about bed leveling issues. But I did wake up this morning thinking that there needs to be an adjustment when setting Backlash::distance_mm, Backlash::correction and Backlash::smoothing_mm. I sort of think this can work properly but haven't fully thought it through. Anyway this might be what is behind G425 with non-zero values.

IDEX (assuming you mean #23325): I think this PR might have fixed it.

**Pull request merged**
