### PR TITLE
SPI Flash Chip W25QXX class + Backup/Restore gcodes

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

As we are using more and more the SPI Flash, I organised a class in `src/libs/`, and create two gcodes, to backup and restore its contents.

I don't if the numbers I choose for the gcodes are good ones... 

### Benefits

* A class to manage SPI Flash
* Users will be able to backup and restore spi flash. It's very important, because the usar could be testing Marlin, but might not want lose their current firmware contents stored in spi flash.

### Related Issues

#18879

### CODE REVIEW

**Comment by thinkyhead** [comment]
The `M993`/`M994` codes are kind of a limited use feature with a number of caveats. It would be better (if it were possible) to capture the serial output of `M503 S0` and write that text to a file. At the moment `M503` writes directly out to serial, but with some additional work all the data being written out to serial during `M503` could be diverted out to a file instead.

**Comment by rhapsodyv** [comment]
> The `M993`/`M994` codes are kind of a limited use feature with a number of caveats. It would be better (if it were possible) to capture the serial output of `M503 S0` and write that text to a file. At the moment `M503` writes directly out to serial, but with some additional work all the data being written out to serial during `M503` could be diverted out to a file instead.

Data in `spi flash` is binary. Will it work fine using serial?

I can add some parameters to `M503` write to a file, and even read the data from spi flash, something like `M503 F filename`... But for me sounds a bit confusing using `M503` "Report Settings" do restore a backup from a file to `spi flash`. 

I can transform `M993/M993` in only one that receive a parameter to backup or restore, and the filename.

Maybe a generic `M505`, to backup and restore any data from/to file: EEPROM / SRAM / SPI FLASH..?

**Comment by rhapsodyv** [comment]
I think the main point here is: we have some gcodes to SD and gcode to eeprom. Now we begin to work with SPI Flash. I think we need a dedicate way to work this new data storage. Maybe not a fresh new way, but it need have its own place in Marlin. As the boards became more powerful, more and more boards will add spi flash.

EEPROM => settings
SPI Flash => fast assets storage
SD Card => gcode files to print, backup media
USB Flash Storage => gcode files to print, backup media

Maybe we need a gcode dedicated to backup/restore things. The code could even backup the rom, isnt? 🤔

**Comment by rhapsodyv** [comment]
Something like:

M993 - Backup/Restore Marlin

M993 F0 filename -> backup SPI Flash to filename
M993 F1 filename -> restore filename backup to SPI Flash

M993 E0 filename -> backup EEPROM to filename
M993 E1 filename -> restore filename backup to EEPROM

M993 R0 filename -> backup ROM to filename

or:

M993 B F filename -> backup SPI Flash to filename
M993 R F filename -> restore filename backup to SPI Flash

M993 B E filename -> backup EEPROM to filename
M993 R E filename -> restore filename backup to EEPROM

M993 B P filename -> backup ROM to filename

**Comment by rhapsodyv** [comment]
@thinkyhead Do you like the backup gcode idea?
Can I do it?

**Comment by thinkyhead** [comment]
I just noticed that we're talking about a 16MB flash size. That's bigger than a lot of old SD cards. I guess that if you wanted to store lots of extra data there, you would need to have some kind of backup / restore of that extra data, or even a little filesystem. So, for that kind of usage a new G-code is a good idea….

**Comment by thinkyhead** [comment]
The problem I have with backup / restore of EEPROM data is that it's "brittle" binary data. The only side effect for Marlin, currently, would be that if you loaded garbage or old data from a backup file the `MarlinSettings` class would treat it as old / bad data and simply ignore / reset the EEPROM in response. It would be good if the data compatibility could be checked before it overwrites the current EEPROM data, if only by comparing against the current version.

But again, there is an open-ended plan to make the EEPROM more structured, so then it would be possible to selectively restore parts of the EEPROM and either convert old data or reset to defaults for out-of-date entries.

In any case, simply saving / restoring the binary data is fairly crude, and maybe it should remain a `MARLIN_DEV_MODE` feature for now.

**Pull request merged**
