### PR TITLE
Fix: Unsupported use of %f in printf

### PR DESCRIPTION
**Pull request by MKS-Sean**
### Description

When using the arduinoststm32 library (robin nano v3.0), using sprintf_P to copy float variables will make an error, but the test in the maple library is normal (robin nano v2.0)

Tested in MKS Robin nano V3.0 motherboard:
Before modification:
image

After modification:
image

### Requirements

Use arduinoststm32 library (MKS Robin nano V3.0 mainboard using it).
Use sprintf_P（buf，PSTR（“%.1f”），float_var）;

### Benefits

LVGL UI can display float type variable parameters normally

### Configurations

default_envs = mks_robin_nano_v3_usb_flash_drive_msc
[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/5931991/Configurations.zip)

### Related Issues

No

### CODE REVIEW

**Comment by X-Ryl669** [comment]
Wouldn't it be easier to set the right linker flags to use the full sprintf version, instead of relying on such painful code?
See [here](https://www.nongnu.org/avr-libc/user-manual/group__avr__stdio.html#gaa3b98c0d17b35642c0f3e4649092b9f1)
Basically, it boils down to adding `-Wl,-u,vfprintf -lprintf_flt -lm` to the linker's command.
Nano v3 is pretty powerful it can support few kB of flash for printing float.

**Comment by rhapsodyv** [comment]
@MKS-Sean Can you take a look if it's working after Scott reviews?

**Comment by thinkyhead** [comment]
@X-Ryl669 — For now Marlin is keen to retain Arduino IDE build support, even for code (such as FSMC LCD) that theoretically might never be compiled and run on an AVR.

**Comment by thinkyhead** [comment]
What *would* be very useful would be a lightweight C++ string class with operator overrides that would turn our ugly string code into something more elegant. The entire codebase would benefit. I wrote my own C++ string class once many moons ago, but there are probably a million examples around that we could use as a starting-point.

Our only caveat is no dynamic allocation. All buffers must be provided by the caller or allocated on the stack. But, given the ubiquity of "string stuff" it wouldn't be the worst thing to add a dedicated buffer for "current string" work, thus making many function stack frames smaller.

**Pull request merged**
