### PR TITLE
Allow overriding of the cold hotend warning.

### PR DESCRIPTION
**Pull request by SilverCory**
### Description

Add a yes no menu to allow bypassing of the cold hotend warning on extrusion manual control

### Benefits

Allows loading/changing filaments whilst the head is cold/warming whilst ensuring the user is aware that the hotend is cold.

### CODE REVIEW

**Comment by SilverCory** [comment]
I tried looking into the rambo test failing however I can't see a cause for the LCD being undefined, could someone point me in the correct direction please?

**Comment by ellensp** [comment]
E_MANUAL     - Number of E steppers for LCD move options
When E_MANUAL is 0 (ie in a cnc example config) the function lcd_move_e is also not defined 
You need to encase your code within a #if E_MANUAL  #endif blocks to remove your code when there is no extruder.

**Comment by thinkyhead** [comment]
Note that this change causes Marlin to become just large enough to exceed the storage on a Melzi board. It would be good to think about optimization, especially for strings and UI.

**Comment by SilverCory** [comment]
That's a shame since I use Melzi :') 

Just curious there was an issue where I couldn't extrude still, I've not had a chance to look into it but I would get to the extrusion submenu and twist the knob to find it still didn't work. Will look into it in a moment

**Pull request merged**
