### PR TITLE
Compact smart_fill_mesh slightly

### PR DESCRIPTION
**Pull request by thinkyhead**
Struct-based procedures are pretty compact.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
It would seem using this technique the code could be compressed to one pair of for() loops and not two.   But it also seems wrong that 3 of the loops count up and only 1 counts down.  It would seem there should be 2 of each direction.

I think this needs to be carefully checked because if 3 loops go one way and 1 loop goes the other way, things are not balanced.  Something is wrong.  (and I'm 4 drinks into a movie...  You are on your own!  At least until the morning.)

**Comment by thinkyhead** [comment]
Well, if you refer to the original code, this is the same ordering. It takes care of all 4 directions, and it is symmetrical when seen from above:
```
x-first
  x-fwd, y-fwd
  x-fwd, y-back
y-first
  y-fwd, x-fwd
  y-fwd, x-back
```

**Comment by thinkyhead** [comment]
> one pair of for() loops

Yes, I see your point.

**Comment by Roxy-3D** [comment]
> Well, if you refer to the original code, this is the same ordering. It takes care of all 4 directions, and it is symmetrical when seen from above:

It is possible the original code had a bug in it...    All of my machines have the Z-Probe in the same location so it is hard to test all permutations.

**Comment by thinkyhead** [comment]
It did have a bug. One of the array indices in one of the loops was wrong.

https://github.com/MarlinFirmware/Marlin/pull/6552/commits/3517154135a8555316b3a877d959493df8118b58#diff-af43b11d24df72f4b1175e4ceedfad9dL1598

**Comment by thinkyhead** [comment]
Compare your smart fill with the bilinear one, inherited from @jcrocholl
who inherited it from… ?who knows where?

https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Marlin_main.cpp#L2648-L2684

It does some averaging to smooth out the data based on what's around it. It also scans from the center outward — which was an interesting loop to make.

**Comment by Roxy-3D** [comment]
Yeah...  That is a bug...  That is the 'starting on the left and looking right' loop.  I think it should be:
```cpp
           ubl.z_values[x][y] = ubl.z_values[x+1][y];  
```
@oldmcg
That 'starting at the center and looking out' version will be valuable for the Delta version of the code.   But for a standard probe setup on a Cartesian machine, I think we want to look from the four edges inward.  That is going to give us good results.

**Comment by oldmcg** [comment]
I'll look at this for delta, was planning to spiral outward from center anyway.  I will leave the cartesian algorithm alone.  

Is code size or data size more important to keep tight?  Can bit-field the mesh indices to 4 bits per index but codegen will be larger.

**Comment by Roxy-3D** [comment]
> Is code size or data size more important to keep tight? Can bit-field the mesh indices to 4 bits per index but codegen will be larger.

Data size is more important.  Any of this can be argued.  But people running Delta's typically will have better electronics.   They will probably have an Atmega-2560 with 256KB of program space.   Also...  when this code is used on a Delta, a very large mesh is probably going to be used.   Probably the full 15x15 for several reasons.   First, many mesh points are off the 'printable radius' and wasted.   But more importantly, the edges of the 'printable radius' are going to have a cup and bowl shape.  So more points closer together is going to help address that issue.

Speed (especially on Delta's) is important.  I don't think I would bit-field the mesh indexes.

**Pull request merged**
