### PR TITLE
Execute gcode commands on stopping print by LCD menu

### PR DESCRIPTION
**Pull request by 7eggert**
(corresponding to github.com/MarlinFirmware/Marlin/pull/12849)

On aborting a print, users rarely desire the nozzle to burn into the print or the build plate, especially with active steppers are holding it in place. This request to change this behavior has been made several times and the users are told to wait for it to be implemented (or Godot to come) while suffering hardware damage.

This is the solution proposed in Issue #12585, but refined. It has **NOT** been tested, just compiled.

Introduce
SD_STOPPED_STEPPERRELEASE (boolean) and
SD_STOPPED_RELEASECOMMAND (String)
to control the behavior of the stop command on the LCD menu.

These config settings are to be made in Config_adv.h

One of the example configs (BQ/Hephestos_2) used G27 P0 as the stop command, I matched the proposed example gcode to say "G27 P2". Otherwise the example is "G91s\nG0 Z5s\nM84 X Y Z E"

### CODE REVIEW

**Comment by skarcha** [comment]
How about execute a default gcode file located in SD card? I think it could be a more flexible solution.

**Comment by 7eggert** [comment]
I like the suggestion: If there is a file called on_stop.gcode, on_pause.gcode, on_sdfinished.gcode, on_usbfinished.gcode …, execute these on encountering these events. You can extend that in many ways.

However,
1) I'm not qualified to make that change
2) Godot might arrive before it's being done
3) A patch with this function may be applied on top of this patch
Therefore I'd rather have this fix as is.

For your suggestion, I imagine you could have a stack of files to print, and have a function:print_file_or_enqueue_P(PSTR(on_stop.gcode), PSTR(SD_STOPPED_RELEASECOMMAND)). As this function might e.g. be called on pause or out-of-filament events, too, you'd need a stack of files being printed. Power might get lost so you need to safe/restore the complete stack. Also: How deep does that stack need to be?

This was an easy fix, your suggestion would need to be looked at by an experienced Marlin developer.

**Comment by marcio-ao** [comment]
@7eggert: We make a similar modification to our own FW (using a GCODE string, not a file from the SD card) so if this were merged, we would use it.

**Comment by MSpencer0** [comment]
I was using the "advanced pause" together with "nozzle park" feature for this.
Select "Pause" which causes the printhead to move into nozzle park position.
And then select "Stop" in the menu.

But for some reason that is not possible anymore in the lates 2.0.x bugfix. But I do not know why.

Another solution could be to run the "nozzle park feature" when a print is stopped/aborted.

**Comment by thinkyhead** [comment]
Supplanted by #13547 — Maintaining @7eggert credit on commits.

**Pull request closed without merging**
