### PR TITLE
Clean up main menu

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Move down custom menu
Move IDEX, debug and case light menus to configuration
Make configuration always available

### CODE REVIEW

**Comment by thinkyhead** [comment]
> Make configuration always available

Kind of dangerous by itself. One of the things this exposes is `G33` delta calibration, which you wouldn't want to do during a print. Also it exposes the `IDEX_menu` which includes parking commands that you wouldn't want to do during a print. Some of the items in the configuration menu are fine, such as the case light options.

I would suggest giving more thought to how these items should be organized before simply exposing the configuration menu during active printing.

**Comment by InsanityAutomation** [comment]
Fair enough, I'll put together a tree of the config menu and put a column for marking what should be hidden while printing. Idex menu is currently exposed, but I agree there are other things in there with potential issues.

**Comment by thinkyhead** [comment]
Oh yeah, IDEX is always on. Well, I've added some more checks to hide items that shouldn't be used during active printing. I'm sure there are more that ought to be hidden, but this is a good start.

**Comment by InsanityAutomation** [comment]
Sounds good, thanks. Chris wants the tree for his guides as well, so I'll get that together regardless. I moved some of these as the home menu was getting cluttered, and the feedback I got on the machine builds we're people wanted the motion config menus back while printing to adjust jerk and acceleation mainly.

**Comment by thinkyhead** [comment]
This needs an update, but it's close to what we have in 1.1.9… http://marlinfw.org/docs/features/lcd_menu.html

**Pull request merged**
