### PR TITLE
Added GPLv3 header to all Marlin files

### PR DESCRIPTION
**Pull request by jbrazio**
Standardization and harmonization.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'm merging this only so I never have to load that huge "Files changed" page again.

**Comment by jbrazio** [comment]
It surely gave more work than it seems at first sight..

**Comment by AnHardt** [comment]
@jbrazio 
I agree. A **proper** license header is very important.
In case of my font files i'm not that happy with your action.

a. Now they have two different license informations. GPL3 and Public Domain. As far i can see GPL is not valid than.
b. For me Public Domain says: 'Do what ever you want'. That includes decreasing the users freedom - but i'm not very happy with this.
c. These files are generated by an other program. If you really want to change them forever, you have to change the generator - not its products.

There is no need to change this back!

**Comment by jbrazio** [comment]
I'm sorry @AnHardt my intent was not to override specific files, that's the reason I kept the original copy(right|left) notices on the files. Marlin itself, as a package, is distributed under GPLv3 this shouldn't invalidate the usage of your font files under the public domain nor re-license them as the original copyright is there.

**Comment by thinkyhead** [comment]
As long as the other license(s) accompanying GPL don't _constrain_ GPL, they are fine. So, for example, you can't mix in a commercial use restriction with GPL. But you can extend additional freedoms, and that is fine.

**Pull request merged**
