### PR TITLE
Add Teensy 4.1 Ethernet support

### PR DESCRIPTION
**Pull request by bilsef**
### Description

Add generic `M552`, `M553`, `M554` to set Ethernet parameters similar to other 3D printer firmware.  Parameters can be saved to EEPROM.

Adds Telnet server for Teensy 4.1 built-in Ethernet, which behaves like second serial port.

### Benefits

Added functionality

### CODE REVIEW

**Comment by ellensp** [comment]
I don't think this should be called ETHERNET_SUPPORT 
This is specific to the Teensy 4.1 so needs a more specific name. 
Otherwise future users will enable this expecting their non Teensy 4.1 Ethernet to work.

**Comment by rhapsodyv** [comment]
> I don't think this should be called ETHERNET_SUPPORT
> This is specific to the Teensy 4.1 so needs a more specific name.
> Otherwise future users will enable this expecting their non Teensy 4.1 Ethernet to work.

Personally I prefer the generic name, plus some sanity checks to warn the user that it is only supported by X.
It’s that... Ethernet could be a very common thing (not that I think it will, but can).

**Comment by ellensp** [comment]
This implementation modifies serial.h, most Ethernet wouldn't need to do this...

**Comment by Gamester17** [comment]
FYI, this type of implementation will likely not quite specific to only Teensy 4.1 in the future as should be same in all that use an NXP i.MX RT series MCU, or at least all i.MX RT series MCUs that have 10/100Mbps Ethernet (i.MX RT1060, i.MX RT1061, i.MX RT1062, i.MX RT1064, i.MX RT1050 and i.MX RT1020):

https://www.nxp.com/products/processors-and-microcontrollers/arm-microcontrollers/i-mx-rt-crossover-mcus:IMX-RT-SERIES

**Comment by ellensp** [comment]
Really? other MPU from the same series use the same ethernet, who would have though it..  What about all the other MPU's which vastly out number this one type? 

Citing two (1 and a wish-list) examples as your case to make it global, is not working for me.

**Comment by thinkyhead** [comment]
I've made some adjustments, the main one being that instead of enabling `ETHERNET_SUPPORT` you should just set `SERIAL_PORT_2` to `-2`, since this implementation was already taking over the role of the second serial port.

**Comment by bilsef** [comment]
@thinkyhead, I tested your changes.  Everything seems to be working except reading the parameters from EEPROM.  It gives this message:
`Error:Field esteppers mismatch.`
I pushed a fix.

**Pull request merged**
