### PR TITLE
Add Selena Compact board

### PR DESCRIPTION
**Pull request by alexxy**
5-axis, high performance, powerful board with Smoothieware opensource firmware. Designed for 3D printer, Laser cutter or CNC mill. Five changed independent drivers on board. Two extruders 3d printer support.

https://github.com/Ales2-k/Selena

Signed-off-by: Alexey Shvetsov <alexxy@gentoo.org>

### CODE REVIEW

**Comment by thinkyhead** [comment]
What specific 3D printer model is the example configuration for?

**Comment by alexxy** [comment]
@thinkyhead its generic config, that can be used as starting point.
Personaly i tested on Prusa i3 like printer (P3Steel)

**Comment by thinkyhead** [comment]
We don't include configurations for **boards**. They are only for specific **machines**.

**Comment by alexxy** [comment]
Ok. In that case configuration can be dropped

**Comment by thinkyhead** [comment]
Looks good! Will merge shortly….

**Pull request merged**
