### PR TITLE
Update language_cz.h

### PR DESCRIPTION
**Pull request by clexpert**
Translate new strings to Czech language.

### CODE REVIEW

**Comment by jbrazio** [comment]
@clexpert do you mind translation also `MSG_BED_Z` ? Thanks.

**Comment by clexpert** [comment]
Done. This message was not added in Czech language file.

**Comment by thinkyhead** [comment]
@clexpert Looks like we have a few more strings that need translation. If you have a moment…

``` cpp
#define MSG_LEVEL_BED_WAITING               "Click to Begin"
#define MSG_LEVEL_BED_DONE                  "Leveling Done!"
#define MSG_LEVEL_BED_CANCEL                "Cancel"
. . .
#define MSG_HOME_OFFSETS_APPLIED            "Offsets applied"
```

**Comment by clexpert** [comment]
@thinkyhead These 4 translations are already included in this commit. And merged by you. Plus MSG_BED_Z.

**Comment by thinkyhead** [comment]
Ah good, I was sending this message to all the language helpers. Guess you were ahead of the curve!

**Pull request merged**
