### PR TITLE
Group all UBL files via a common prefix

### PR DESCRIPTION
**Pull request by thinkyhead**
For Marlin 1.2 files will be grouped in sub-folders. Meanwhile a common prefix helps to group related files together.

|old|new|
|---|---|
|UBL.h|ubl.h|
|UBL_unified_bed_leveling.cpp|ubl.cpp|
|UBL_G29.cpp|ubl_G29.cpp|
|UBL_line_to_destination.cpp|ubl_motion.cpp|

### CODE REVIEW

**Comment by Roxy-3D** [comment]
The reason I did not put UBL_ in front of G26 was I thought Mesh and BiLinear would use it also.

**Comment by thinkyhead** [comment]
Ah, I see. Let me see what that entails.

**Comment by Roxy-3D** [comment]
> Ah, I see. Let me see what that entails.

For starters...   I wonder if we all can switch to the same z_values[][] array?   And maybe the same #define MESH_X_POINTS.    If so...   It should not be too hard to let all three use it.

**Comment by thinkyhead** [comment]
All good, except we have to account for the `BILINEAR_SUBDIVISION` option.

**Comment by Roxy-3D** [comment]
> All good, except we have to account for the BILINEAR_SUBDIVISION option.

I'm ignorant about that...  But if those are just automatically generated mesh points, we can probably just change the loops to recognize there are extra mesh points to plot.

**Comment by thinkyhead** [comment]
> we can probably just change the loops to recognize there are extra mesh points to plot.

The `print_2d_array` function takes parameters to that effect, plus a pointer to an accessor function.

**Comment by Bob-the-Kuhn** [comment]
While you're at it, you could combine MESH_MIN_X , ...  and UBL_MESH_MIN_X, ....  

It also needs to be moved from Configuration_adv.h to the bed leveling section of Configuration.h.

**Comment by Roxy-3D** [comment]
> While you're at it, you could combine MESH_MIN_X , ... and UBL_MESH_MIN_X, ....
> It also need to be moved from Configuration_adv.h to the bed leveling section of Configuration.h.

I agree...   It would be nice if that got changed!

**Comment by thinkyhead** [comment]
It would also be good in the long run if we shored up the `position_is_reachable` function and had more general config options specifying where the bed is located in the coordinate space. Then code could call `position_is_reachable` to see whether a given coordinate is reachable by the probe, or `position_is_within_bed` to see if it's on the bed, etc. Then you'd only have to specify in the config how far inside the bed to probe so you don't hit the bed clips, and that would determine the default bounds.

**Comment by Roxy-3D** [comment]
Agreed on that also.

**Comment by Roxy-3D** [comment]
> All good, except we have to account for the BILINEAR_SUBDIVISION option.

I've been reading about that Catmull-Rom algorithm.   It maybe we don't need to do anything other than print the main mesh points.  The G26 code will draw a line connecting each mesh point with neighboring mesh points.  If that Catmull-Rom routine is working...  The line will just come out with a nice, uniform amount of 'squish' to it across the entire line.   If we wanted, we could put a little hash mark on the line where each of the subdivisions is.   But I'm not even sure that is necessary.   I guess we could get it running with the BiLinear and then decide what else should be done.

**Comment by thinkyhead** [comment]
> maybe we don't need to do anything other than print the main mesh points.

Our version of the algorithm uses a separate and larger array to store the interpolated points, which are generated after probing. Only the original probed grid is saved to EEPROM, since the interpolated grid can be reproduced from it.

**Comment by Roxy-3D** [comment]
Right now...   Without seeing it working...   Just getting the main (real) mesh points plotted is probably going to be enough.   If you got it to plot the BiLinear main mesh, I think you understand the value.

But it would be very straight forward to plot different patterns based on whether it is a main mesh point or a derived one.   Maybe a circle for the main one and a triangle or square for the derived ones.   The user would know exactly what needed to be done to improve the mesh.

**Pull request merged**
