### PR TITLE
Allow ColorUI color customization

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Allow users customize the ColorUI colours.

### Benefits

Happier users?

### Configurations

None

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Woo! It'll be nice to override that blue background 🙂

Should these options be extended to the configs (`Configuration_adv.h`)?

**Comment by rhapsodyv** [comment]
> Woo! It'll be nice to override that blue background 🙂
> 
> Should these options be extended to the configs (`Configuration_adv.h`)?

Yes! I didn't document it there, because is too much options. Maybe we can add a simple paragraph, telling the user to check `tft_color.h` if he wants customize colours.

**Comment by thisiskeithb** [comment]
I keep hearing people say they don't want to make the configs longer, but they are the _configs_. The options can be pushed to `Configuration_adv.h` since it's an "advanced" feature, but we'll see what Scott thinks.

**Comment by ils15** [comment]
I agree
push settings in Configuration_adv.h more reliable e easy to change colors

**Comment by rhapsodyv** [comment]
This are the configs:

```cpp
#define COLOR_BACKGROUND    0x20AC  // #1E156E
#define COLOR_SELECTION_BG    0x9930  // #992380
#define COLOR_WEBSITE_URL     0x03B7
#define COLOR_INACTIVE          COLOR_GREY
#define COLOR_COLD              COLOR_AQUA
#define COLOR_HOTEND            COLOR_SCARLET
#define COLOR_HEATED_BED        COLOR_DARK_ORANGE
#define COLOR_CHAMBER           COLOR_DARK_ORANGE
#define COLOR_FAN               COLOR_AQUA
#define COLOR_AXIS_HOMED        COLOR_WHITE
#define COLOR_AXIS_NOT_HOMED    COLOR_YELLOW
#define COLOR_RATE_100          COLOR_VIVID_GREEN
#define COLOR_RATE_ALTERED      COLOR_YELLOW
#define COLOR_PRINT_TIME        COLOR_AQUA
#define COLOR_PROGRESS_FRAME    COLOR_WHITE
#define COLOR_PROGRESS_BAR      COLOR_BLUE
#define COLOR_PROGRESS_BG       COLOR_BLACK
#define COLOR_STATUS_MESSAGE    COLOR_YELLOW
#define COLOR_CONTROL_ENABLED   COLOR_WHITE
#define COLOR_CONTROL_DISABLED  COLOR_GREY
#define COLOR_CONTROL_CANCEL    COLOR_SCARLET
#define COLOR_CONTROL_CONFIRM   COLOR_VIVID_GREEN
#define COLOR_BUSY              COLOR_SILVER
#define COLOR_MENU_TEXT         COLOR_YELLOW
#define COLOR_MENU_VALUE        COLOR_WHITE
#define COLOR_SLIDER            COLOR_WHITE
#define COLOR_SLIDER_INACTIVE   COLOR_GREY
#define COLOR_UBL               COLOR_WHITE
#define COLOR_TOUCH_CALIBRATION COLOR_WHITE
#define COLOR_KILL_SCREEN_BG    COLOR_MAROON
#define COLOR_KILL_SCREEN_TEXT  COLOR_WHITE
```

**Comment by rhapsodyv** [comment]
This is the color "translator" (from full RGB to RGB565)
https://ee-programming-notepad.blogspot.com/2016/10/16-bit-color-generator-picker.html

**Comment by thinkyhead** [comment]
I'd prefer not to have all those color settings added to all the Configuration files. Instead, please apply `#ifdef` wrappers to them where they live, add a note on the ColorUI LCD configuration option about where to find the name of the colors if they want to override them.

**Comment by thinkyhead** [comment]
Seems to be where it should be already, thanks.

**Pull request merged**
