### PR TITLE
Move Screen Fixes

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

The new move screen for color ui was merged. Now, I have some users are testing it. 

This PR is to fix any issue they are reporting to me.

### Benefits

- Fixes issues for new move screen

### Related Issues

#19386

### CODE REVIEW

**Comment by jmz52** [comment]
@rhapsodyv 
TFT Driver and resolution are more or less independent.
You can use 480x320 screen to display 320x240 UI.
Also you can use `OFFSET_X` and `OFFSET_Y` macros to position small UI on bigger screen

**Comment by rhapsodyv** [comment]
@jmz52 Fixed the sync/font issue. Not the btn are using the normal font. No sync needed.

@thinkyhead: I think it's ready to merge.

**Comment by thinkyhead** [comment]
Note that you can call `defer_status_screen` just once before entering a new screen and it will have the same effect as calling it continuously.

**Comment by rhapsodyv** [comment]
> Note that you can call `defer_status_screen` just once before entering a new screen and it will have the same effect as calling it continuously.

The `move_axis_screen` is called only once, at the first draw. After that, the code only updates the screen parts needed (for example: when moving X, it only updates the square where the X value is located.

**Pull request merged**
