### PR TITLE
Password via G-code and MarlinUI

### PR DESCRIPTION
**Pull request by sherwin-dc**
### Description

A settable passcode for the printer that can configured to ask for the passcode:
 - On startup
 - To access 'Print from Media' Menu
 - After a print from SD card stops or aborts

The number of digits for this passcode can be configured (1 to 9 digits). The passcode can be entered using a rotatory knob.

Note: It seems the touch UI includes a lockscreen, but this should bring the feature to more printers that do not have a touch screen.

### Benefits

The majority of users might not need this. However, it would be useful if the printer is kept in a shared location such as:
 - At home, where the user may not want others (eg small children) to play with he printer's settings.
 - In a work environment (similar to how copier machines have passwords).

This would allow someone to enter their passcode when booting the printer, start a print, and have it automatically lock when the print ends.

### Limitations

This is not meant to be a security feature, but a simple form of Access control.
 The password can be circumvented by:
   - removing it from the Password Settings / EEPROM menu if the printer is unlocked
   - sending remote gcode commands, even if the printer is locked
   - removing the password through the menu while printing
The password is not likely to stop someone who knows their way around a 3D printer.

### Misc

I have tested this on my Ender 3 Pro but I am not sure what kind of LCDs this would work on. This feature makes use of the LCD Menu functions.

Password_screen

### CODE REVIEW

**Comment by sherwin-dc** [comment]
I am quite new to using git so apologies for asking, but how do I remove the Configuration.h and Configuration_adv.h files from the PR? I have tried to rm the files in git but then they show up as deleted with merge conflicts. 

I think that could be the reason why the tests are failing as they are specific to my printer (I only saw this on the marlinfw website later on). If that is the case, how should I include the switches for the feature added?

**Comment by thinkyhead** [comment]
I've cleaned this up a bit and encapsulated the feature in a static class. The code is okay for what it does, but it needs some support at a deeper level to permit putting the machine into a "LOCKED" state where nothing will operate except the password menu and all external host control can also be blocked. To get better support for hosts, a G-code should be added for setting the password, locking the machine, and authenticating from a host.

**Comment by thinkyhead** [comment]
I'll get into testing this soon and do some refinement of the input method and the data storage. A custom input screen for password digits (similar to the `select_screen` stuff) should not be too difficult to put together.

**Comment by sherwin-dc** [comment]
I added 3 new Gcodes M510, M511, M512 for locking, unlocking and setting the password. The way locking the printer works is by blocking all gcode commands from processing (except M511).

I was concerned that it would be possible to use brute force to unlock the printer by sending a gcode file with all password combinations, hence I added options to disable M511 and M512.

This feature should now work without `HAS_LCD_MENU` (though untested)

The user is asked for the password when trying to access the password menu, though I think it would still be possible to remove the password by loading and storing default settings through the menu while the printer is printing (have not tried that myself).

#### M510 Lock Printer
Usage:
```
M510
```
#### M511 Unlock Printer
Usage:
To unlock printer with password 01234:
```
M511 P1234 
```
followed by `M500` to save settings
#### M512 Set/Change/Remove Password
Usage:
To set a password 1234:
```
M512 N1234
```
To change the password from 1234 to 5678:
```
M512 P1234 N5678
```
To remove the password 5678:
```
M512 P1234 N
```
followed by `M500` to save settings

**Comment by sherwin-dc** [comment]
I think the `pow()` function should not be used due to the rounding problem. On the extreme end, I tried setting a 9 digit password using the LCD as `987654321` but the no `987653905` was saved (perhaps because pow() uses floats).

This would still sort of work if only the LCD (or only the host) will always be used to both set the password and unlock the printer, but now if either one (LCD or host) is used to set the password and the other is used to unlock the printer it would not work.

**Comment by thinkyhead** [comment]
Are you saying that `pow(10, n)` and `pow10(n)` cannot be rounded to get the exact power of 10 value? All you need to do is add 0.5 and take the integer part, or the `floor`.

**Comment by AnHardt** [comment]
Without having looked at the problem here deeper.

Single precision float has a mantissa of 23 bit, good for up to 6-7 exact decimal digits. Every decimal digit behind that is noise.

**Comment by sherwin-dc** [comment]
ok, I dont think the problem is with pow(), as outputting pow(10,8) gives the correct value. However, I'm still not getting the value of the password keyed in and not sure what the problem is.

In the latest commit under `Password::digit_entered()` if I add a serial message for debugging:

```
const uint32_t multiplier = LROUND(pow(10, PASSWORD_LENGTH - 1 - digit_no));
SERIAL_ECHOLNPAIR("multiplier is ", multiplier);
value_entry += digit * multiplier;
string[digit_no++] = '0' + digit;
```

and try to set a 9 digit password one digit at a time using the LCD I get the following output:

```
multiplier is 99999968
multiplier is 9999984
multiplier is 1000000
multiplier is 100000
multiplier is 10000
multiplier is 1000
multiplier is 100
multiplier is 10
multiplier is 1
```

However simply outputting `pow(10, PASSWORD_LENGTH - 1 - 0)` gives the correct multiplier. I have tried changing the first line slightly such as using `CEIL()` on or casting to an `int` the second pow() argument but still get the same output as long as `digit_no` is included.

**Comment by AnHardt** [comment]
Often the print routines for printing floats are using tricks like: If the difference to a round decimal value is smaller than one LSB of the mantissa print the round value. For most of us it is disappointing if `Serial.println(3.0 * 1.0/3.0);` is not printing 1 . Especially in Arduino context that is very possible. Checked! It does print 1.00 . Try stupid things like `Serial.println(pow(10,8)+1.0);` resulting in `100000000.00`.
```  
  Serial.println(pow(2,24)-1); // 16777215.00
  Serial.println(pow(2,24));   // 16777216.00
  Serial.println(pow(2,24)+1); // 16777216.00
```
Fact stays - single precision numbers have no exact representation if the mantissa is above 2^23 = 8,388,608. With denormalization pow(2,24) is possible. 
So the formerly used loop - staying in integer, had a chance to be correct, not so the pow() in single precision float.

https://en.wikipedia.org/wiki/Single-precision_floating-point_format

**Comment by sherwin-dc** [comment]
I think in this case it may not be `pow()` thats the problem. It looks like it uses double precision floats.

As for the actual problem, I am not sure why it is happening, or if it can be reproduced on other machines. 

In any case, using the for loop did avoid the problem on my machine. Furthermore, when I tried changing both the `pow()` functions to the loops it reduced the program size by about 700 bytes. Perhaps this is because my mainboard does not have an FPU and more instructions are required to do pow() with floats. So since floats arent needed it would be better to avoid them completely to at least save program memory.

**Comment by AnHardt** [comment]
>  It looks like it uses double precision floats.

It would be an error if the code would require to work in double. The AVRs do not have 'double' just and only 'single precision float'. The code would not work there on.

**Comment by thinkyhead** [comment]
True that floats aren't needed. And if we want to avoid `pow` there is always this trick:
```cpp
#define FIFTH_POWER 5
constexpr long ten_thousand = CAT(10e, DECREMENT(FIFTH_POWER));
```

**Comment by sherwin-dc** [comment]
I changed the `pow()` function to `CAT(1e, PASSWORD_LENGTH)`. If using the LCD to key in the passcode it now divides the multiplier by 10 after each digit entered, so it should be better than the for loop.

I think the only thing left would be the dedicated password input screen, though the code should work fine as it is.

**Comment by charakaSamawry** [comment]
just wondering, would this feature play nicely with the BTT TFTs? using the tft35 v3 with a BTT SKR Mini v2.
I have a  feeling it would need to be implemented on the host firmware before i can enable it in marlin firmware, no?

**Comment by thisiskeithb** [comment]
> just wondering, would this feature play nicely with the BTT TFTs? using the tft35 v3 with a BTT SKR Mini v2.
> I have a feeling it would need to be implemented on the host firmware before i can enable it in marlin firmware, no?

BigTreeTech's TFT firmware would need to be updated to support this feature.

**Comment by charakaSamawry** [comment]
As I thought, thank you.

**Comment by sherwin-dc** [comment]
By the way I noticed the M512 gcode has been changed to use `S` instead of `N` to input the new password.

However the comments in the configuration.h file still reflect `N` being used:

```
  #define PASSWORD_CHANGE_GCODE             // Change the password with M512 P<old> N<new>.
```

**Comment by thisiskeithb** [comment]
> By the way I noticed the M512 gcode has been changed to use `S` instead of `N` to input the new password.
> 
> However the comments in the configuration.h file still reflect `N` being used

Thanks for the heads up! I've put in https://github.com/MarlinFirmware/Marlin/pull/19108 to address this.

**Pull request merged**
