### PR TITLE
STM32: Fix set_pwm_duty for TFT_BACKLIGHT_PWM

### PR DESCRIPTION
**Pull request by tpruvot**
analogWrite() call is required to enable/switch to pwm from off mode (binary/digital)

### CODE REVIEW

**Comment by tpruvot** [comment]
in my case here is my pwm pinmap 
```
  {PA_15, TIM2,   STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_TIM2_PARTIAL_1, 1, 0)}, // TIM2_CH1 Part Fan
  {PD_12, TIM4,   STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_TIM4_ENABLE, 1, 0)}, // TIM4_CH1 TFT Backlight
  {PD_13, TIM4,   STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, AFIO_TIM4_ENABLE, 2, 0)}, // TIM4_CH2 Servo connector
  {NC,    NP,    0}
```

Maybe its possible to check the current AFIO mode of a pin and avoid the call to analogWrite if no change is required....

**Comment by thisiskeithb** [comment]
Related PR causing these issues: https://github.com/MarlinFirmware/Marlin/pull/23048

**Comment by tpruvot** [comment]
i tried pin_function(pin_name, func); instead of analogWrite(pin, v);  but seems not enough....

**Comment by tpruvot** [comment]
arf, AFIO_NONE constant seems not common to all chips...rmm

**Comment by tpruvot** [comment]
To note on my issue, its not the fan but the backlight, and i dont have NEEDS_HARDWARE_PWM defined... nor fast pwm enabled, which means pwm_start is never made...

**Comment by tpruvot** [comment]
so do not merge right now, problem is not AFIO but seems a more general case...

**Comment by tpruvot** [comment]
i tried if (pin == TFT_BACKLIGHT_PIN) set_pwm_frequency(pin, PWM_FREQUENCY);
forcing #define NEEDS_HARDWARE_PWM 1
but no success for now... so i left analogWrite for this case...

**Comment by tpruvot** [comment]
interesting to note i also tried that ... which works the first time but not on sleep wake up...

image

which means the mode was changed to digital "off" by the sleep timeout... need a new analogWrite to put it back to pwm i guess...

**Comment by thisiskeithb** [comment]
What else should we check for after https://github.com/MarlinFirmware/Marlin/pull/23048 was merged? Should that be reverted until after 2.0.9.3?

**Comment by tpruvot** [comment]
i dont think it should be reverted, unless a 2.0.9.3 is planned for this week... may be a good idea to protect timer frequency changes... but maybe some led libs are affected too

**Comment by thisiskeithb** [comment]
> i dont think it should be reverted, unless a 2.0.9.3 is planned for this week...

With the config version change being made already, it always makes me nervous when something like this is merged right after & before a release, especially with how rough some previous releases have been.

**Comment by tpruvot** [comment]
me too lol :p but version change to 2.0.9.2 took at least a month then to be tagged. Need more tests for my special case... imo i need to change the OUT_WRITE(TFT_BACKLIGHT_PIN, LOW); on sleep...

edit: no.. without the OUT_WRITE (using WRITE), its not off...

**Comment by thinkyhead** [comment]
If `set_pwm_duty` was not thoroughly composed as a safe alternative to `analogWrite` for any and all PWM pins, then I'll just revert the pins that don't work with it back to `analogWrite`. I don't want to put special exceptions for certain pin functions into that function. The 'exception' should instead be made based on some testable property of the pin.

**Comment by thinkyhead** [comment]
Let's see if @andrei-moraru has any thoughts on the changes, plus any ideas about making PWM handling more consistent across all pins that are used for PWM output….

**Comment by thinkyhead** [comment]
> the mode was changed to digital "off" by the sleep timeout

If that can occur (even as a consequence of `analogWrite(0)`) then all the affected pins will need to have code added to reset them back to OUTPUT/PWM mode. Importantly, the `set_pwm_duty` method should be as small and fast as possible since it may be called from the Stepper ISR for the laser when starting a new block. So if the fix can be applied without adding more code to `set_pwm_duty` that would be best.

**Comment by tpruvot** [comment]
yep, i will retest but should work like that. That remember me M256 B0 may need a fix too in my config, if i remember right there is default MIN PWM set to 1 instead of 0 somewhere

**Comment by tpruvot** [comment]
ok on CLASSIC_UI, double checking COLOR_UI now.. (edit: ok too)

btw... STM32 framework has the analogWriteFrequency() function meant to set the default pwm frequency used by all future calls of analogWrite(), but.. its global and not per timer as it should be...

**Comment by thinkyhead** [comment]
> STM32 framework has the `analogWriteFrequency()` function 

I wrote a fancy function `set_pwm_frequency_hz` in `HAL/AVR/fastio.cpp` to set any base frequency, specifically for Timer 5 on ATmega. The math used in that function to set the best combination of 'CPU divider' and 'top value' could be extended and applied to any platform.

**Comment by tpruvot** [comment]
yep, the comment was more for the other PR to protect fast pwm frequency changes by libraries or specific user code...

for M256, here is the "problem" which prevent to set brightness to 0

Marlin/src/lcd/marlinui.cpp:107
```
#if HAS_LCD_BRIGHTNESS
  uint8_t MarlinUI::brightness = DEFAULT_LCD_BRIGHTNESS;
  bool MarlinUI::backlight = true;

  void MarlinUI::set_brightness(const uint8_t value) {
    backlight = !!value;
    if (backlight) brightness = constrain(value, LCD_BRIGHTNESS_MIN, LCD_BRIGHTNESS_MAX);
    _set_brightness();
  }
#endif
```

**Comment by thinkyhead** [comment]
Right. The `brightness` variable is not set to 0, but is left intact when that is attempted. So the `_set_brightness` method should be considering the `backlight` flag when setting the PWM value for the pin.

**Comment by tpruvot** [comment]
is that really required to have 2 variables ?

**Comment by andrei-moraru** [comment]
I'm wondering, ideally shouldn't a timer frequency and pin state be something done at initialization time?

All the loop should be trying to do in my mind is update the duty-cycle. Nothing more. Especially when a timer can be used across multiple pins/channels.
- The init code/compile time checks are is in a way better position to guard the timer/setup. When we get to actually switching the pin, we should be in a well-defined, known state:
  - TIM is set and ticking
  - We know its initialized as PWM output pin

I would try and fix the `init` methods on the rest, so that by the time we call `set_pwm_duty` we already know the timer is ticking. Then the behaviour becomes consistent and we make it impossible to change the frequency without `set_pwm_frequency`. Which is way easier to track in the code-base, since it only has 1 purpose. 
- AUTO_FAN feature does that.

Does the use-case of the Backlight require that a pin change state at run-time? (Go from digital -> PWM -> digital?)

Isn't a PWM with a duty-cycle of 0 effectively DIGITAL LOW?

**Comment by tpruvot** [comment]
a PWM with a duty-cycle of 0 is not exactly digital low... there will be an interrupt TICK made "forever" on the SoC but... in power cost/use may not change a lot... pwm real stop is not a good idea neither because delete & alloc will be needed later (on STM32 at least) HardwareTimer instances...

Timer frequency is kept once set (for the running timer) but... indeed analogWrite may reset/change the value on each call... if different or if analogWriteFrequency was used

**Comment by andrei-moraru** [comment]
Wouldn't the timer need to be configured to explicitly interrupt the CPU on overflow?
- For example we run the temperature interrupt at 1khz.
- But for the other timers, there would be no need to interrupt thus no load on the CPU.

I was thinking something like:
```cpp
class MarlinUI {
public:

  MarlinUI() {
    TERN_(HAS_LCD_MENU, currentScreen = status_screen);
    #if HAS_LCD_BRIGHTNESS
      _init_brightness();
    #endif
  }
...
#if HAS_LCD_BRIGHTNESS
  void MarlinUI::_init_brightness() {
    #if PIN_EXISTS(TFT_BACKLIGHT)
      if (PWM_PIN(TFT_BACKLIGHT_PIN)) {
        SET_PWM(P);
        set_pwm_frequency(pin_t(TFT_BACKLIGHT_PIN), 1000); // TODO: Turn me into a variable
      }
    #endif
  }

  void MarlinUI::_set_brightness() {
    #if PIN_EXISTS(TFT_BACKLIGHT)
      if PWM_PIN(TFT_BACKLIGHT_PIN)
        set_pwm_duty(pin_t(TFT_BACKLIGHT_PIN), brightness);
      else
        digitalWrite(pin_t(TFT_BACKLIGHT_PIN), brightness == LCD_BRIGHTNESS_MAX ? HIGH : LOW);
    #endif
  }
#endif
```

But I see a can of worms opening with `FAST_PWM_FAN_FREQUENCY`. The last pin that sets the frequency of the timer would win, unless we start checking that all the wanted frequencies are _compatible_ for that timer at build time.

**Comment by thinkyhead** [comment]
> is that really required to have 2 variables ?

If you want to turn OFF the light and then later turn it back ON at the same brightness it was at before, you do need two variables.

**Comment by thinkyhead** [comment]
> shouldn't a timer frequency and pin state be something done at initialization time?

The rationale given in #23048 is that `analogWrite` stomps on the frequency and resets it back to 1K.

**Comment by tpruvot** [comment]
in my case the fan use another timer, so they can work at different frequencies... but didnt configure hardware FAST PWM for now because i keep a common config with the 2 frameworks and i cant set the TIMER2 alternate pin with the generic maple variant...

Maybe we could add/create a pwmWrite function which double check the timer is free like it was made in set_pwm_frequency and call analogWrite then if its ok...

**Comment by tpruvot** [comment]
in fact i can, both SOFT PWM & FAST PWM are commented in my config, its set in board

**Comment by thinkyhead** [comment]
To help break through the fog it would be a good next commit to add end-of-line comments to the relevant pins with:
- The pin mode and usage
- The timer associated with the pin
- PWM base frequency
- Hardware register
- etc.

…so that we have that information at hand.

And, in general, so much of the data we need within reach is in scattered datasheets, and it would be nice to have something akin to a database – or a literal MySQL db – with only the Marlin-centric data collated and cross-referenced … formatted in pretty rows and columns. At some point I'll have to make a version of `M43` that spits out MySQL "`INSERT`" lines, then see what happens.

**Comment by thisiskeithb** [comment]
> And, in general, so much of the data we need within reach is in scattered datasheets, and it would be nice to have something akin to a database – or a literal MySQL db – with only the Marlin-centric data collated and cross-referenced … formatted in pretty rows and columns.

So it can be tracked: https://github.com/MarlinFirmware/Marlin/issues/23077

**Comment by tpruvot** [comment]
something like that ? https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/PlatformIO/variants/MARLIN_F103VE_LONGER/variant.h#L7

**Pull request merged**
