### PR TITLE
G34 Z-Steppers Auto-Align increased range

### PR DESCRIPTION
**Pull request by sargonphin**
### Description

Extends the range of G34 Z Steppers Auto Align since now some bed probes are able to be very precise. Range goes from 0.01-1.0 to 0.001-1.0. Also added sanity checks for out of range values

### Requirements

Requires a bed probe

### CODE REVIEW

**Comment by sjasonsmith** [comment]
@sargonphin would you mind describing the setup you are using where this became a limitation?

**Comment by sjasonsmith** [comment]
Also, if you're able to update this with the current state of bugfix-2.1.x to resolve the merge conflict that would be great. The change is simple enough that I don't see any reason not to make the change, as long as there are scenarios where this was actually limiting performance.

I would generally imagine that most printers aren't actually accurate enough on their Z axis to benefit from more than 0.01, but feel free to prove me wrong!

**Comment by sargonphin** [comment]
@sjasonsmith Bed probes such as the SuperPINDA can be accurate enough that it almost always achieve accuracies under 0.01mm, being able to set the threshold lower could allow to take the full potential of the sensor. It wouldn't make a big difference in printing as this distance is too small to do anything, but at least such accuracy can be achieved :)

**Comment by InsanityAutomation** [comment]
I agree with the change. @sargonphin just need to rebase on bugfix to get rid of the merge conflict and it should be fine. Can take a look once thats done to be sure it doesnt impact anything.

**Review by InsanityAutomation — APPROVED** [review]

**Pull request merged**
