### PR TITLE
[1.1.x] Shorter Z raise between multiple probes

### PR DESCRIPTION
**Pull request by nightgryphon**
### Description

For some probes like micro switches the full Z clearance raise between probing attempts is not required while bigger Z clearance between probe points is still needed to avoid clamps and other obstacles. The shorter Z raise within multiprobing same point significantly increase probing speed and the whole auto level process.

### Benefits

Significantly increase speed of multiple attempts (fast/slow) probing especially useful for multi point bed leveling

### CODE REVIEW

**Comment by ghost** [comment]
Hi again, that's better :)  
2 little things tho, you need to make PRs to the "bugfix-x.x" branch(es) as they are the "in development" ones, and you messed a bit when you merged upstream into your multiprobe-z branch.  
You might want to squash your 3 commits and rebase so it can be easily edited/cherry picked etc.. ;)

**Comment by nightgryphon** [comment]
Should i close this request and do the new one to do this?

**Comment by fiveangle** [comment]
https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/

[and of course make sure the commit on your own repo reflects the same, most likely with a rebase]

**Comment by nightgryphon** [comment]
Thanks!
I've changed request base. Actually my multiprobe-z-up branch was based on bugfix-1.1.x so now i see only my changes here.
But i can't find how to squash commits :(

**Comment by ghost** [comment]
Hehe, don't worry about squashing them, whoever merges it can squash them at that moment ;)  
If you wanna try here's a quick how to (make a backup first) :  
`git rebase -i HEAD~X` (where X is the number of commits from head you want to rebase)  
 -i means interactive it opens the rebase window in a text editor, from the interactive window, replace "pick" in front of commits by "squash" to squash them with the commit above, then save and exit.  
Now that you squashed your 3 commits in one, check nothing got lost ("git show XYZ" where XYZ is your commit hash) and push the changes : "git push -f" (it will force push, note the -f, in order to replace the unsquashed commits you pushed)  
In your case try "git rebase HEAD~3" and squash your last 2 commits into " Shorter Z up move between multiple probing attempts"

**Pull request merged**
