### PR TITLE
M115 add STM32 device serial number into capability report (Lumen Index PNP)

### PR DESCRIPTION
**Pull request by stuartpittaway**
### Description

This PR adds functionality to the M115 command and STM32 CPU's.  

This PR was requested by the Lumen (Index) PNP project to expose the serial number of the STM32 chip via Marlin M115 for the purposes of asset tracking of physical devices (PNP machine).

This also allows configuration files to be tied to a physical device for automatic setup.

The code changes are wrapped in #IF statements to limit to INDEX_REV03 mobo and STM32F4 chipsets.

### Requirements

Requires INDEX_REV03 and STM32F4

### Benefits

A new "capability" is returned in M115 named "STM32UID" which contains a hex string of the unique serial number of the STM32F4 chip.

### Configurations

Existing configurations for INDEX_REV03 work without change

### Related Issues
None

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This seems like it would conflict with `MACHINE_UUID`:

https://github.com/MarlinFirmware/Marlin/blob/c5af4354498b9c634b397aecfc8034793b724e90/Marlin/Configuration.h#L140-L142

**Comment by stuartpittaway** [comment]
There is definitely overlap with the MACHINE_UUID.  Indeed the MACHINE_UUID could be set dynamically for the INDEX_MOBO - that would be another way to achieve similar results.

The M115 command appeared to be less intrusive and have less far reaching consequences that changing code around the MACHINE_UUID.

**Comment by thinkyhead** [comment]
Maybe it makes the most sense to have the `UUID` get replaced (i.e., automatically generated) using the STM32 UID in the case of the Index Mobo (and other platforms that supply a hardware-defined UUID) when the user has not provided one.

**Comment by thisiskeithb** [comment]
> Maybe it makes the most sense to have the UUID get replaced

That would be the route I'd take. Plus, it'll work with existing host software that can read/expect a `UUID`.

**Comment by stuartpittaway** [comment]
I avoided messing with MACHINE_UUID as that's set at compile vs runtime with the serial number, so a different bunch of changes required, rather than tagging an extra attribute to the M115 command.

I'm happy to change if @thinkyhead wishes this direction instead?

**Pull request merged**
