### PR TITLE
Fix shared PID

### PR DESCRIPTION
**Pull request by GMagician**
Fix shared PID.

Now M500 & M502 only write values to first hotend but PIDRunner use indexed values.
This fix will copy the same value on all hotend and should fix issue #24644

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
On second extruder get nice PID waveforms and controls about the setpoint.  M303 E1 S210 autotune gave similar results to previous autotune runs.

Any other testing I can do?

---

NOTE ON TEST SYSTEM

I configured my single extruder delta system to think it has two extruders.  E0 is the phantom and E1 is real.

**Comment by GMagician** [comment]
> Any other testing I can do?

Try modifing values by LCD

**Comment by thinkyhead** [comment]
I've applied some refactors to centralize a little more of the PID logic in the `Temperature` classes. Some LCD / UI code does direct editing of PID values in memory; so although that still works, it would be best to refactor UI code to use the added accessors and setters.

**Comment by GMagician** [comment]
> it would be best to refactor UI code to use the added accessors and setters.

sorry for stupid question but what should look like the UI code that has to be changed?

**Comment by thinkyhead** [comment]
>  what should look like the UI code that has to be changed?

It should be done in the way that `MarlinUI` does it. Consider `MarlinUI` to be the best reference and the best place for UI standardization.

**Comment by Bob-the-Kuhn** [comment]
> Try modifing values by LCD

I didn't find that option on my 12864 full graphics LCD.  Is there an option to add it?

EDIT: found it - **PID_EDIT_MENU**

**Comment by Bob-the-Kuhn** [comment]
Just tested the latest changes.  All is well:
- second extruder has a nice PID waveform and controls about the setpoint.
- The debug prints show both extruders have the expected (same) PID values.
- M301 E0 ... sets both extruders to the same PID values.
- LCD sets both extruders to the same PID values.

**Comment by Bob-the-Kuhn** [comment]
Just changed my config to **PID_PARAMS_PER_HOTEND**.  All went as expected.
- second extruder has a nice PID waveform and controls about the setpoint.
- The debug prints show both extruders have the expected (different) PID values.
- M301 E0 ... sets first extruder PID values only.
- M301 E1 ... sets second extruder PID values only.
- LCD sets each extruder independently.

**Comment by GMagician** [comment]
thanks @Bob-the-Kuhn for all these tests.

**Comment by GMagician** [comment]
> It should be done in the way that `MarlinUI` does it. Consider `MarlinUI` to be the best reference and the best place for UI standardization.

Sorry but I don't understand what to do...my fault

**Comment by thinkyhead** [comment]
> I didn't find that option on my 12864 full graphics LCD. Is there an option to add it?

The menus for hotend PID editing appear when `BOTH(PIDTEMP, PID_EDIT_MENU)`.

**Comment by thinkyhead** [comment]
> Sorry but I don't understand what to do...my fault

In the menus we want to edit the unscaled values, but then finish up by setting scaled values. So, we sacrifice some SRAM in the build for temporary variables and use those during editing. In general, it's better if the LCD knows less about the internals of Temperature code (and other non-LCD-specific things), so getters and setters are favored when refactoring things like this.
```cpp
#define _PID_EDIT_ITEMS_TMPL(N,T) \
  raw_Ki = T.pid.i(); raw_Kd = T.pid.d(); \
  EDIT_ITEM_FAST_N(float41sign, N, MSG_PID_P_E, &T.pid.Kp, 1, 9990); \
  EDIT_ITEM_FAST_N(float52sign, N, MSG_PID_I_E, &raw_Ki, 0.01f, 9990, []{ apply_PID_i(N); }); \
  EDIT_ITEM_FAST_N(float41sign, N, MSG_PID_D_E, &raw_Kd, 1, 9990, []{ apply_PID_d(N); })
```

**Comment by GMagician** [comment]
Added some getter/setter but I see that dwin/dgus displays needs some work. I may try to address them but unfortunately I don't have any lcd to test with

**Pull request merged**
