### PR TITLE
Add Cartesio mainboard and user Interface

### PR DESCRIPTION
**Pull request by maukcc**
Adding:
- Cartesio mainboard
- Cartesio user Interface
- Example configuration files

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'm re-rolling this against the latest code and squashing all these excess commits. In the process I want to eliminate the extra copies of `dogm_bitmaps.h` and `dogm_lcd_implementation.h`. The `dogm_bitmaps.h` file was easy to patch for `CARTESIO_UI` but I need to know: Do you consider the changes to `dogm_lcd_implementation.h` applicable to all DOGM displays, or just to `CARTESIO_UI`?

**Comment by maukcc** [comment]
Things that are usefull for all dogm_lcd_implementation.h
- Add percentage of SDfile printed
- move time of SDfile printed to the right to make space for percentage of SDfile printed

Things that are not compatible for all dogm_lcd_implementation.h
- position of logo on bootscreen
- position of text on bootscreen

I will change the logo so there will be the marlin logo and next to it the user defined logo (as 1 bmp converted to hex) to give credits where they are due. That will eliminate the positions on bootscreen

**Comment by thinkyhead** [comment]
I forgot to note that you've added a custom boot-screen, and we haven't had a look at the graphic! Would you post an image of the boot screen as it appears on your display?

**Comment by maukcc** [comment]
This is the file I will be using.
It is with the old marlin logo as the new one just does not come out right on a 128x64 display
I made a 128x64 file with the bottom 17 pixels empty for text, this way you do not have to position the logo in the screen with int offx and int offy.
I also gave the 2 text lines on a fixed position and height as this is secondary to the logo

marlin-cartesio-lcd

```
#if ENABLED(SHOW_BOOTSCREEN)

int txt1X = (u8g.getWidth() - (sizeof(STRING_SPLASH_LINE1) - 1) * (DOG_CHAR_WIDTH)) / 2;

u8g.firstPage();
do {
  if (show_bootscreen) {
    u8g.drawBitmapP(0, 0, START_BMPBYTEWIDTH, START_BMPHEIGHT, start_bmp);
    lcd_setFont(FONT_MENU);
    #ifndef STRING_SPLASH_LINE2
      u8g.drawStr(txt1X, u8g.getHeight(), STRING_SPLASH_LINE1);
    #else
      int txt2X = (u8g.getWidth() - (sizeof(STRING_SPLASH_LINE2) - 1) * (DOG_CHAR_WIDTH)) / 2;
      u8g.drawStr(txt1X, u8g.getHeight() - 9, STRING_SPLASH_LINE1);
      u8g.drawStr(txt2X, u8g.getHeight(), STRING_SPLASH_LINE2);
    #endif
  }
} while (u8g.nextPage());

if (show_bootscreen) {
  delay(3000);
  show_bootscreen = false;
}
#endif
```

So let the bitmap be OK, and not try to make code to position the bitmap :)

**Comment by AnHardt** [comment]
Using a small bitmap and centering it was done to save memory.

I don't like the idea of a custom logo on the boot screen at all. It's Marlin!
But giving a possibility for a second logo, maybe on a second bootscreen, would be better then when everyone replaces the Marlin logo with his own. That is contradictinonaly to the memory saving idea, but would be in the responsibility of the customizer.

**Comment by jbrazio** [comment]
I do agree with @AnHardt, we should not ship custom logos.
We could have a bootlogo.h file that if present we would source it and add a second logo screen as Andreas suggested.

**Comment by maukcc** [comment]
No problem. I have taken them out.

**Comment by thinkyhead** [comment]
@AnHardt I'm cleaning up and redoing this PR (as #4053) …… If we wanted to stick the Cartesio custom boot logo into the `example_configurations` folder, would we name it `dogm_custom_bitmaps.h` so that it would replace the root one when someone wanted to use it?

**Comment by AnHardt** [comment]
The idea behind 'Custom Splash Screen #4034' was not to replace the Marlin logo with a custom logo (which i have seen many times), but to give a dedicated way to add a custom logo, so the Marlin logo can remain.
The 'big' Marlin logo i put in `dogm_custom_bitmaps.h` is taught to be an example only.  
My idea would be to put the round shaped logo into  `dogm_custom_bitmaps.h` and that file into the example folder - **if** we want to ship a foreign logo at all.

**Comment by thinkyhead** [comment]
@maukcc I have the Cartesio UI in hand and would like to connect it up to a RAMPS. The cable is a flat ribbon with no crimps or connectors at the other end, so I was wondering if there's an online guide or PDF about on the pinouts and recommended connections. Of course, I can use the pins file here and just figure it out myself, but if there's already something written up then I can follow its advice.

**Comment by maukcc** [comment]
Here is the schematic.

[UI12.pdf](https://github.com/MarlinFirmware/Marlin/files/820468/UI12.pdf)

**Comment by thinkyhead** [comment]
Thank you very much! I'm not very good with going from a schematic, but I'll do research on which pins should connect where and try to wire it up soon.

**Pull request closed without merging**
