### PR TITLE
[2.0] Fix probes configuration url

### PR DESCRIPTION
**Pull request by thinkyhead**
Based on #8241 by @machaj

### CODE REVIEW

**Comment by tcm0116** [comment]
For some reason that I can't figure out, after this PR was merged, checking out bugfix-2.0.x immediately causes got to show that _Marlin/src/config/examples/STM32F103RET6/Configuration.h_ has been modified. At some point, it was acting as if the STM32F103RET6 folder had changed case, but I'm not sure. Any ideas?

**Comment by Tannoo** [comment]
I have the same issue. I cannot get rid of it. I won't let me commit whever changes it says is there and I can't seem to discard them either.
At one point, I discard changes with this file `Marlin/src/config/examples/STM32F103RET6/Configuration.h` and it then comes back with `Marlin/src/config/examples/stm32f103ret6/Configuration.h`.
I discard that and it comes back with `Marlin/src/config/examples/STM32F103RET6/Configuration.h` again.

**Comment by Tannoo** [comment]
I've deleted all my local files and re-cloned... Still the same.
I've tried to recover from a previous backup of that file and still the same.

**Comment by Tannoo** [comment]
I deleted the offending directory and committed the change.
If I try to rebase my branch, it pops up that same file being an uncommitted change.
I aborted the rebase and all is still good.

I restored the directory from a previous backup and committed that change.
The issues are now gone.
If I try to rebase my branch, it pops up that same file being an uncommitted change.
I have to abort the rebase as it will not continue due to this weird issue.

**Comment by tcm0116** [comment]
I think it's because the STM32F103RET6 folder is uppercase in the
respoitory, but somehow ended up as lower case in this commit. If you look
at the changes in this PR, you'll see that it's lower case.

**Pull request merged**
