### PR TITLE
[2.0.x] Update pins for GTM32VB

### PR DESCRIPTION
**Pull request by chepo92**
### Description
Update pins for GTM32VB,  (it has an external connection for LED, cleanup comments and not used pins (came from other STM board file) 

Also adds JTAG Disable (enabling related pins as GPIO) in main.ccp if using this board (Jtag pins are needed as gpio for steppers X and Y and heater0)

### CODE REVIEW

**Comment by thinkyhead** [comment]
Sorry, didn't mean to close this if it was an intentional PR. I thought it might have been a mistake because it makes a mess of the pins file and doesn't have a proper title. Please fix up the formatting and it can be merged when it's ready.

**Comment by chepo92** [comment]
@thinkyhead, I have arranged the mess

**Comment by thinkyhead** [comment]
Please review and decide if the remaining changes are worth keeping.

**Comment by chepo92** [comment]
Sorry I wasn't looking, this PR was important to get the Y axis working but just my changes, not all the mess, I'll come with a new PR soon (If still compatible)

**Pull request closed without merging**
