### PR TITLE
Anycubic Chiron oem LCD support (ExtUI)

### PR DESCRIPTION
**Pull request by marcoburato**
### Description

This adds support to the Anycubic Chiron oem LCD and tweaks the recently merged support for the Anycubic i3 mega oem LCD, so they can coexist and the appropriate one can be chosen via Configuration.h.

### Benefits

- Adds support for the Chiron LCD
- Existing implementation for i3 mega LCD now uses `MarlinSerial` instead of a duplicate serial port implementation
- PIN assignments differ slightly between i3 mega and Chiron (and I expect even more for other printers using the Trigorilla mainboard), so the appropriate PIN definitions are now compiled by defining `ANYCUBIC_I3MEGA` or `ANYCUBIC_CHIRON`

### Related Issues

Merged i3 mega PR: #18655

### CODE REVIEW

**Comment by thinkyhead** [comment]
There aren't any defines of `ANYCUBIC_CHIRON` or `ANYCUBIC_I3MEGA` included. Are these set in the Configuration files?

**Comment by thinkyhead** [comment]
We need to make sure that changes to Trigorilla 1.4 pins won't have a negative effect on the other machines that use the pins file, including the AnyCubic/i3, Anycubic/Kossel, and Anycubic/Kossel Linear Plus.

**Comment by sjasonsmith** [comment]
I can try it on a Kossel tonight

**Comment by thinkyhead** [comment]
If your `FIL_RUNOUT_PIN` was 19, this PR now makes it 4.

**Comment by sjasonsmith** [comment]
@thinkyhead my Kossel code (and the example) already cannot compile without this change. It appears to have broken as part of #18655. I'll try rebasing on top of this, but my hopes are low.

**Comment by sjasonsmith** [comment]
Actually it compiled on top of this. I'll put it on the printer and try a few sanity checks.

**Comment by sjasonsmith** [comment]
OK, with these changes my Anycubic Kossel Linear Plus seems to all be working without me having to modify anything. Apparently whatever had been broken earlier has now been fixed. I didn't print anything, but verified that my LCD, switches, probe, heaters, and motors are working. I'm currently running a G33 calibration and it seems to be proceeding fine.

I don't have a filament sensor on here, so I'm not impacted by that pin changing. The Kossel doesn't come with one out of the box so most users probably don't have them. Since there isn't actually a filament sensor connector I don't personally think there should be a default pin for it at all!

**Comment by sjasonsmith** [comment]
The two Kossel examples build fine also.

**Comment by marcoburato** [comment]
@thinkyhead The Trigorilla mainboard is used in various printer from Anycubic, the problem is that while the board itself has labelled pins for specific things, like endstops, on both the i3 Mega and Chiron they added a PCB stacked on top that routes signals to various physical pins and wired some endstops to AUX connectors.
The result is that pins have a different function than what the standalone Trigorilla board would use them for.

I had a brief discussion on Discord about this and, to support all the effective pin mappings, it seemed the possible routes were to either create new mainboard definitions or use conditional compilation. I went for this second approach because it didn't make much sense to me to create mainboard definitions that would be used on a single printer.

The merged PR for the i3 mega LCD did always #define pins for the i3 mega, I'm not surprised it broke the build for the Kossel. I fixed that in this PR.

In general, my approach was to define pins for the standalone Trigorilla board by default and remap / add more if it's a specific printer.

I will retest on my Chiron this evening.

**Comment by thinkyhead** [comment]
I have a Chiron here and would like to do some testing. Do we have a good set of configuration files for the Chiron? How easy is it to flash new firmware onto the Trigorilla board? I have a spare Trigorilla 1.4 I can do some dry runs on. If the live mesh editing works, along with the other screen functions, it would be great to have a recent firmware installed.

**Comment by marcoburato** [comment]
Here's my configuration: [Chiron_Config.zip](https://github.com/MarlinFirmware/Marlin/files/5021666/Chiron_Config.zip)

My printer has some mods, so you'll need to tweak it slightly. My mods:
- BL-Touch
- Volcano hotend (tuned PID constants)
- TMC2008 drivers

I was planning to commit a config for an OEM printer once this PR had been merged. Maybe you can do that if yours is stock and are making an oem config anyway?

Also, can you confirm that what I've done for `Z2_USE_ENDSTOP` is correct? Instead of repurposing an endstop, I've defined Z2_MIN_PIN in pins_Trigorilla_14.h.

Edit: forgot to say, flashing is easy, it's just a RAMPS essentially. You just plug the USB cable in and Upload from PlatformIO. You might have to force the USB port in platformio.ini if there are other virtual com ports.

**Comment by marcoburato** [comment]
Seems to work fine.

**Pull request merged**
