### PR TITLE
Revert "Make SERVO_ENDSTOP_ANGLES 2-dimensional"

### PR DESCRIPTION
**Pull request by Natealus**
Reverts MarlinFirmware/Marlin#2543

### CODE REVIEW

**Comment by Natealus** [comment]
Hey sorry I didn't mean to post this to main Marlin but to my fork but while its here...the reason I reverted is because it throws compiling errors about constraining a multidimensional array. Something is off in this pull request. I can swap the files back around if you want the error messages.

**Comment by AnHardt** [comment]
@Natealus 
As PR #2543 passed several tests with different configurations (Travis), it's likely your specific configuration what fails. Would you mind to post it?

**Comment by Natealus** [comment]
Sure I posted it to pastebin here: http://pastebin.com/9cXck1xN 
And Configuration_adv.h here:  http://pastebin.com/gA72siDm

**Comment by Natealus** [comment]
Oh and I did have it in the Configuration.h as:

#define SERVO_ENDSTOP_ANGLES {{0,0}, {0,0}, {90,1}} // X,Y,Z Axis Extend and Retract angles 

I just changed it back for the revert in that paste.

**Comment by thinkyhead** [comment]
The proper fix is more likely this…

``` diff
-    const int servo_endstop_angles[][] = SERVO_ENDSTOP_ANGLES;
+    const int servo_endstop_angles[][2] = SERVO_ENDSTOP_ANGLES;
```

**Comment by Natealus** [comment]
@thinkyhead That fixed it compiles fine now. :) I'll go ahead and close this up.

**Pull request closed without merging**
