### PR TITLE
Auto filament change on CHANGEFILAMENT feature. Now you can activate t...

### PR DESCRIPTION
**Pull request by paclema**
...his option that extrude filament until you press the button.
Check an example on a Witbox printer

### CODE REVIEW

**Comment by thinkyhead** [comment]
Please consider applying proper indentation when adding or modifying code, otherwise I will have to fix it myself. https://github.com/MarlinFirmware/Marlin/wiki/Coding-Standards

**Comment by paclema** [comment]
@thinkyhead thank you very much for the directrices! I had not seen it before. I want to contribute but sometimes i don't know how is the better way. I'm applying the rules to this PR.

**Comment by thinkyhead** [comment]
@paclema I should add a note about coding standards to the main README – they were only recently put together, so haven't gotten around to it…

**Comment by paclema** [comment]
Now is it ok @thinkyhead ?

**Comment by thinkyhead** [comment]
It looks clean, but your branch needs a `git rebase` so that it can be merged.

**Comment by AnHardt** [comment]
@paclema 
Consider to use the improved lcd_buzz()(https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/ultralcd.cpp#L1719)

**Comment by paclema** [comment]
@thinkyhead rebase done. @AnHardt we might do another PR for that. Actually, I tested the current M600 and im not sure that lcd_quick_feedback() is the correct way instead lcd_buz() in this case. I need to test more.

**Pull request merged**
