### PR TITLE
Add E_AXIS_HOMING feature

### PR DESCRIPTION
**Pull request by DerAndere1**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

With #define E_AXIS_HOMING defined in
configuration.h, the E-axis can now be controlled similar to XYZ axes:
- support for limit switch,
- support for G-code "G28": auto-home all axes (XYZE) and "G28 E"
  (auto-home E-axis)
- support for enabling software endstops for E-axis by adding
  "#define (MIN|MAX)_SOFTWARE_ENDSTOP_E" to configuration.h

Sanity checks are put into place: Only for cartesian 4 axis robots with 
one limit switch (endstop) per axis, E_AXIS_HOMING can be enabled.
E_AXIS_HOMING has to stay undefined (disabled) for other setups 
(e.g. machines with multiple carriages or multiple 
stepper-drivers per axis or with LINEAR_ADVANCE). 

### Benefits

With these changes, Marlin 2.0.x could be configured for robots with four axes (e.g. liquid handling robots). In those robots, the E-axis stepper motor is repurposed for an application that is different from driving an extruder. The proposed changes allow the needed homing of the E-axis.

### Related Issues

#8519

### CODE REVIEW

**Comment by DerAndere1** [comment]
I added the new options only to the default configuration files. The files in config/examples/ could be modified accordingly after review.  This is my first pull request ever, so bear with me. Can be closed if it is not worth the extra efford needed to maintain the additional amount of code. I will try to maintain my fork then.

**Comment by thinkyhead** [comment]
I don't think we can incorporate this concept into the main Marlin fork in its current form. There is at least one other added-linear-axis concept ahead of this, which is the `HANGPRINTER` that was implemented in 1.1.9 (but not yet in 2.0.x). It also adds a new linear axis, and does so in a much more comprehensive and complete way, without overloading the E axis. There is a lot of overlap with this concept, and I don't think the two can coexist in the same branch.

I definitely encourage you to keep up your fork. And you should definitely pull down the changes which I've applied to clean up your code. You can do this by using the Git console in Github Desktop. You must enter the following commands exactly as shown to pull down the changes I have applied to your branch:
```
git fetch origin
git checkout e_homing_PR
git reset --hard origin/e_homing_PR
```

**Comment by thinkyhead** [comment]
Please don't force-push at this time.

**Comment by thinkyhead** [comment]
Ok, if you'd like to obtain the fixes for this code, you can get them at https://github.com/thinkyhead/Marlin/tree/bf2_e_homing

**Comment by DerAndere1** [comment]
sorry, i saw your coments too late. i will get your cleanups and have a look at the hangprinter concept. thanks alot. I agree that my implementation is incomplete and there might be better approaches. keep up your great work. I will maintain the branch https://github.com/DerAndere1/Marlin/tree/Marlin2ForPipetBot sepearately.

**Comment by DerAndere1** [comment]
@thinkyhead: I incorporated your changes. Thanks.

**Pull request closed without merging**
