### PR TITLE
Fix HAS_FAN macro

### PR DESCRIPTION
**Pull request by 0r31**
Hi,

_HAS_FAN macro doesn't check the right fan pins definitions. It uses an extra underscore symbol that doesn't exist in pins definition files.

The macro :
```C
#define _HAS_FAN(P) (PIN_EXISTS(FAN_##P) //...
```

The fan pins definitions in pins_RAMBO.h for instance:
```C
#define FAN1_PIN            6
#define FAN2_PIN            2
```

Regards,
Orel

### CODE REVIEW

**Comment by boelle** [comment]
@0r31 is there an issue number that this one fix's ?

**Comment by 0r31** [comment]
Hi @boelle ,

I didn't create any issue linked to this PR. Do you want me to check in bug list if there are some related ones?

Regards,
Orel

**Comment by boelle** [comment]
no no, its just normal that an issue and PR are paired

but then again a lot of bugs are also fixed before they make it to the issue list, just like this one

so we are good, but if you have surplus time then i would not mind if you could see if any of the open bug reports could be solved somehow

**Comment by boelle** [comment]
btw... i'm more easy to get hold of on discord, thou not when i sleep :-)

**Comment by GurenWolf** [comment]
I have an Anycubic Kossel Plus with a Bigtreetech SKR 1.3 board and the issue also showed up there. After applying this fix, everything came back to normal.

Just to comment, is there a way to start the second fan at a given nozzle temperature?
This used to be the default behavior on this printer but now I have to turn it on manually.

Maybe another thread for this?

**Comment by 0r31** [comment]
Hi @GurenWolf ,

As far as i understand, there is only one auto fan pin defined per extruder in the current version of the code:

```c
// Auto fans
#define HAS_AUTO_FAN_0 (HOTENDS > 0 && PIN_EXISTS(E0_AUTO_FAN))
#define HAS_AUTO_FAN_1 (HOTENDS > 1 && PIN_EXISTS(E1_AUTO_FAN))
//...
```

So if you have another fan, it might be a manually driven one (with _M106/M107_) unless it shares the same pin at the microcontroller level or unless you directly tweak the code.

Regards,
Orel

**Pull request merged**
