### PR TITLE
Fix JyersUI for LPC176x

### PR DESCRIPTION
**Pull request by tome9111991**
Hello
do not know if I have the permission for this fix

Without the fix i got a error like:
118365360-bcae5780-b59c-11eb-9828-87f45abe1712

here a fix  to get work JyersUI with LPC1769 works well on my SKR E3 Turbo.
got only few warrnings on compile.

**should someone test with stock motherboard**
compiling works with stock board but I don't know if the display is working properly.

thanks to @eohl79

### CODE REVIEW

**Comment by thinkyhead** [comment]
Because your fork was made from the `Jyers/Marlin` fork, we are unable to send changes directly to your branch and this PR. This is a bug in the GitHub platform, still not resolved. So I have sent a PR to your fork at tome9111991/Marlin#1. Please merge that PR to update this PR.

**Comment by tome9111991** [comment]
sorry I'm a github noob ^^
i hope is correct now.
if not you can close this PR you know  what you need to fix.

**Review by tome9111991 — COMMENTED** [review]
```c++
#if HAS_DGUS_LCD
    #define SERIAL_GET_TX_BUFFER_FREE() LCD_SERIAL.available()
  #endif
```
Works with?
DWIN_CREALITY_LCD_JYERSUI


EDIT tested
i got

```
Marlin\src\lcd\e3v2\jyersui\dwin.cpp: In member function 'void Mesh_Settings::Draw_Bed_Mesh(int16_t, uint8_t, uint16_t, uint16_t)':
Marlin\src\lcd\e3v2\jyersui\dwin.cpp:334:16: error: 'SERIAL_GET_TX_BUFFER_FREE' was not declared in this scope; did you mean 'SERIAL_TX_BUFFER_SIZE'?
  334 |         while (SERIAL_GET_TX_BUFFER_FREE()) { // wait for serial to be available without blocking and resetting the MCU
      |                ^~~~~~~~~~Compiling .pio\build\LPC1769\src\src\lcd\e3v2\jyersui\rotary_encoder.cpp.o
~~~~~~Compiling .pio\build\LPC1769\src\src\lcd\extui\ui_api.cpp.o
~~~~~~~~~
      |                SERIAL_TX_BUFFER_SIZE
*** [.pio\build\LPC1769\src\src\lcd\e3v2\jyersui\dwin.cpp.o] Error 1
```

**Comment by thinkyhead** [comment]
What configurations are you using for your testing? Please ZIP those up and attach them to your next reply. This particular part of JyersUI may be possible to do without looking at the amount of space free in the TX buffer, simply by applying a minimum delay and basing it on the LCD-serial port's baud rate.

**Comment by thinkyhead** [comment]
I've posted another PR for you at tome9111991/Marlin#2 which should be more compatible with all platforms and should be able to draw a large mesh without causing a watchdog reset. Please merge and test!

**Comment by tome9111991** [comment]
Compiling works with your fix.
i got still same warrning with my fix
```
w=]
  375 |       sprintf_P(msg, PSTR("Red %s..0..%s Green"), str_1, str_2);
      |                                                          ~
C:\Users\Tommi\.platformio\packages\framework-arduino-lpc176x\cores\arduino/Arduino.h:58:18: note: in definition of macro 'PSTR'
   58 | #define PSTR(v) (v)
      |                  ^
Marlin\src\lcd\e3v2\jyersui\dwin.cpp:375:16: note: 'sprintf' output between 16 and 46 bytes into a destination of size 32
  375 |       sprintf_P(msg, PSTR("Red %s..0..%s Green"), str_1, str_2);
```

btw here my  config
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/7148657/Config.zip)

**Comment by tome9111991** [comment]
Have tested this fix on my printer works well.

1. DWIN_CREALITY_LCD
2. DWIN_CREALITY_LCD_ENHANCED
3.  DWIN_CREALITY_LCD_JYERSUI
4. DWIN_MARLINUI_PORTRAIT

all is working on a SKR E3 Turbo

**Comment by thinkyhead** [comment]
That warning can be ignored, or `Set_Mesh_Viewer_Status` can be altered to eat 46 stack bytes for the message string. Once we have a better string class applied throughout the code those kinds of warnings will be a thing of the past.

**Pull request merged**
