### PR TITLE
Menu Items - Right aligned string & Icons for TFT, Fixed lcd_put_u8str_P method.

### PR DESCRIPTION
**Pull request by lukasradek**
I accidentally closed [the original PR](https://github.com/MarlinFirmware/Marlin/pull/25331) by renaming the branch. This is just a re-PR.

### Sumary
Adds ability for generic and static menu items to show (in addition to their title) right aligned string. Visually similar to Edit items but non editable and can be used with ACTION, SUBMENU etc. I have implemented and tested it for DOGM, HD44780 and TFT lcds. I have implemented a simple fallback for e3v2 and TFTGLCD, but I have no way to test it.

Shows helpful menu icons on `TFT_COLOR_UI `in place of `post_char`. Shows the equivalent icons to HD44780 display. `>` is displayed as "right arrow icon", `LCD_STR_UPLEVEL` is displayed as "back icon".

Fixes return value of function `lcd_uint_t lcd_put_u8str_P(PGM_P const ptpl, const int8_t ind, const char *cstr/*=nullptr*/, FSTR_P const fstr/*=nullptr*/, const lcd_uint_t maxlen/*=LCD_WIDTH*/)` in _/lcd/lcdprint.cpp_.
It should have returned number of outputed characters, but was returning number of remaining characters from given `maxlen `limit. Codebase is adjusted to this change, where it was neccessary.

### Detailed Description of Right aligned strings (RString)
**Marlin/src/lcd/menu/menu_item.h**
Adds the option to print RStrings in "any" ITEM. For **full backward compatibility** it is implemented as a companion macro `ITEM_ADD_RIGHT_ALIGNED_STRING`, that user wraps the desired ITEM in. The mechanism of how the string is passed to the `::draw` methods is similar to substituion (more on that later), which requires the macro to also "clear" the string after the item is printed. Otherwise the string would be printed in the following items as well. That fails when screen change is detected (because the menu function immediatelly returns)... therefore there is a small change in `_MENU_INNER_F` needed, that clears the string if action is detected. _Note: It cannot be cleared only after the `ui.screen_changed` is `true`, because when that happens the item action was already performed (that is what caused `ui.screen_changed == true`) and if that action has drawn some items, it would be too late to clear RString._

**Marlin/src/lcd/menu/menu.cpp and .hpp**
RStrings are implemented the same way as the substitution strings are. Supports only C-strings, since I presume it will be mostly used for dynamic values.

**Marlin/src/lcd/tft/ui_common.cpp
Marlin/src/lcd/HD44780/marlinui_HD44780.cpp
Marlin/src/lcd/dogm/marlinui_DOGM.cpp**
RStrings are implemented in `MenuItem_static::draw` and `MenuItemBase::_draw`, which covers most of the _ITEMs. For the others (like EDIT_ITEM) I don't think it is relevant. (It is specified in the `ITEM_ADD_RIGHT_ALIGNED_STRING `macro's comments.
RStrings always have priority over the menu title. That means the whole RString is always visible and has a single space in front of it. Item title then takes the remaining space.
When item's style is `SS_CENTER`, the RString is omited from the padding calculation intentionally.
(There are also a few other changes in these files... see below)

**Marlin/src/lcd/e3v2/marlinui/ui_common.cpp
Marlin/src/lcd/TFTGLCD/marlinui_TFTGLCD.cpp**
Unfortunatelly I have no way to test these LCDs, so I implemented a simple, hopefully error proof fallback solution. RString is just appended to the title.
It is UNTESTED though and should be fully implemented to match the other LCDs.

### Detailed Description of TFT_COLOR_UI icons
**Marlin/src/lcd/tft/ui_common.cpp**
This UI now displays icons in place where `post_chars` would be on HD44780.
It is implemented for `>` character (e.g. submenus), which displays right arrow icon,
and for `up_level` character (e.g. BACK_ITEM), which displays back icon.

### Detailed Description of Other changes
**In generic items, title uses as much width as possible.**
Since `LCD_WIDTH` is a precious real estate, I modified the `MenuItemBase::_draw` so that if `post_char` is only a single space, it is ignored and item title will use that character. The only "downside" is that submenu symbol `>` can be shown at the same column that other items' titles can be, making the distinction between submenu and other items a little less noticeable. But in most places this makes no difference (most item titles are not that long), but when there is a long title, that one more character can help.
This concerns these files:
Marlin/src/lcd/tft/ui_common.cpp
Marlin/src/lcd/HD44780/marlinui_HD44780.cpp
Marlin/src/lcd/dogm/marlinui_DOGM.cpp

**Return value fix for `lcd_uint_t lcd_put_u8str_P(PGM_P const ptpl, const int8_t ind, const char *cstr/*=nullptr*/, FSTR_P const fstr/*=nullptr*/, const lcd_uint_t maxlen/*=LCD_WIDTH*/)`**
This is the function that handles item title substitution. Documentation (of this function and some of its callers) says that it should `@return the output width (in pixels on GLCD)`, but it did not. I returned the width of unused space of the `maxlen` parameter limit.
I have also manually searched through the codebase, made sure that this change did not break anything and fixed places where it did (mostly `::draw` methods that I was modifying for the other features).
Implementation change concerns this file:
Marlin/src/lcd/lcdprint.cpp
Touch ups where return value was used concerns these:
Marlin/src/lcd/tft/ui_common.cpp
Marlin/src/lcd/HD44780/marlinui_HD44780.cpp
Marlin/src/lcd/dogm/marlinui_DOGM.cpp
Marlin/src/lcd/e3v2/marlinui/ui_common.cpp
Marlin/src/lcd/TFTGLCD/marlinui_TFTGLCD.cpp

### Benefits

**Right aligned strings in Item titles**
are needed for my next [pull request regarding reworked (Assisted) Tramming Wizard](https://github.com/MarlinFirmware/Marlin/pull/25339).
It can be useful in general to display separate non editable value inside menu item title, while not being restricted to EDIT_ITEM's properties (cannot open menus, cannot trigger actions).

**TFT_COLOR_UI icons**
It is nicer looking 🙂. It is also very practical being able to distinguish between SUBMENU and ACTION items.

**Other**
Collapsing `post_char` can help on smaller screens.
Fixed return value makes more sense this way and is consistent with other functions.

### Related Issues

It is a first part of completing [this feature request](https://github.com/MarlinFirmware/Marlin/issues/24448)

### Thousands of words
RStrings and post_char icons working side by side for ACTION items and submenus alike in my [new Tramming Wizard](https://github.com/MarlinFirmware/Marlin/pull/25339).
<p float="left">
  

</p>

### CODE REVIEW

**Comment by thinkyhead** [comment]
Recently while working on the Debug > Endstop Test screen I added an additional jusification option, `SS_FULL`, which preserves the use of a single Value string. For fixed-width font displays like GLCD `SS_FULL` inserts the leftover space between the item Label and Value (whereas `SS_CENTER` inserts half of the free space as padding before the label and the remainder [sometimes] after the value). For screens that use proportional-width fonts, and which have the option to add a string at a given X coordinate in a "draw list" the `SS_FULL` justification just right-justifies the Value string by subtracting its width from the pixel width and drawing at that X position.

So… if this PR is adding the concept of a _second_ RJ String, so we still justify the standard Label and Value with `SS_LEFT` or `SS_CENTER`, and then right-justify the additional RJ String, we can rework it that way. However, if it merely provides a different way to right-justify the Value string, then we can remove that part and just consolidate this to the navigation icon option. In the latter case, we just slide the `SS_FULL` X-coordinate to the left to make room for the icon, and draw the icon (or `post_char`) at the edge.

Anyway, this does need a `git merge bugfix-2.1.x` with the latest code. I can make the attempt, but perhaps it would be better to let you reapply the icon option on top of the new code, and just force-push the final result to the same branch, which will update this PR. (i.e., There is no need to close this PR and create a new one.)

I don't think we need to add a new option to show the navigtion icon. I think it should _always_ appear for sub-menus and for editable items that open a new screen. (Later, we might try editing values in-place without opening a new screen, but for now we'll just keep doing the standard MarlinUI edit screen thing.)

**Comment by thinkyhead** [comment]
By way of example, this is no longer needed:
```cpp
ITEM_ADD_RIGHT_ALIGNED_STRING(
  STATIC_ITEM_F(FPSTR(pgm_read_ptr(&tramming_point_name[tram_target])), SS_LEFT),
  _get_mms_str(tram_target)
);
```
Instead this can now be used:
```cpp
STATIC_ITEM_F(FPSTR(pgm_read_ptr(&tramming_point_name[tram_target])), SS_FULL, _get_mms_str(tram_target));
```
In the current `bugfix-2.1.x` code, only `STATIC_ITEM` and `PSTRING_ITEM` are set up to display a "value" C-string with justification (and `EDIT_ITEM`, which is always right-justifiied). The general approach of adding `itemRAlignedStringC` isn't exactly bad, as it only costs one extra pointer, but the wrapping of menu items to set it is not super elegant, and since we already have methods that are so close to what we want, maybe we can just add a variant of `MenuItemBase::_draw` that takes one more argument and if a standard menu item has the extra argument it will automatically get called.

Pretty much anything that works, but which doesn't increase the code size for *every* regular menu item is what we're after. The `ITEM_ADD_RIGHT_ALIGNED_STRING` approach is very close, but I'm sure we can make it prettier. Also, if no features are enabled that use the Right Aligned string, we should make sure not to even compile it in. Keeping the code and SRAM usage as small as possible is the name of the game.

**Comment by lukasradek** [comment]
Thanks for the comments, I have some thoughts on the changes you requested, so I will look into that and consult later (as stated in the Tramming Wizard PR)... and merge it with the Tramming Wizard. 🙂

**Comment by lukasradek** [comment]
@thinkyhead 

> So… if this PR is adding the concept of a _second_ RJ String, so we still justify the standard Label and Value with `SS_LEFT` or `SS_CENTER`, and then right-justify the additional RJ String, we can rework it that way. However, if it merely provides a different way to right-justify the Value string, then we can remove that part and just consolidate this to the navigation icon option. In the latter case, we just slide the `SS_FULL` X-coordinate to the left to make room for the icon, and draw the icon (or `post_char`) at the edge.

So I have looked into this...I was quite perplexed at first as why I haven't used the Value string (vstr), but I found out.
Value string is only available for `STATIC_ITEM`s. My RAStrings are supported for all `ITEM` types that use `MenuItemBase::draw` method or `MenuItem_static::draw`. That means all except `EditItems` (and possibly `PSTRING`), where it doesn't make sense anyway.

And I need those RAStrings on `ACTION_ITEM`s and `SUBMENU_ITEM`s in order to show user a value and take action on it.

We would either have to modify the remaining "draw" methods to take `SS_LEFT|SS_FULL|SS_CENTER `and `vstr `arguments or just stick with my wrapper macro. It is redundant for `STATIC `items though, so it can be removed for those and the developer would use `SS_FULL `for static items and `ITEM_ADD_RIGHT_ALIGNED_STRING `for others.

I think using ITEM_ADD_RIGHT_ALIGNED_STRING is preferable, since otherwise it would mean changing a lot of method's signatures  
from `MenuItemBase::_draw(const bool sel, const uint8_t row, FSTR_P const fstr, const char pre_char, const char post_char)` 
to `MenuItemBase::_draw(const bool sel, const uint8_t row, FSTR_P const fstr, const char pre_char, const char post_char, const uint8_t style/*=SS_DEFAULT*/, const char *vstr/*=nullptr*/ )`

[I have also posted a full reasoning behind my implementation in this old PR.](https://github.com/MarlinFirmware/Marlin/pull/25331#issuecomment-1416772833)

**Comment by lukasradek** [comment]
I might have a few days to look into this and finish it.
Can I get your opinion @thinkyhead on the matter please, so I can continue.
Do you agree with me that sticking with my existing `ITEM_ADD_RIGHT_ALIGNED_STRING` would be easier than implementing `SS_FULL` and `vstr` for submenu and action items?

**Edit (from my anti-sunk-cost fallacist mindset):**

On the second thought... I can probably implement justification (`SS_FULL`, `SS_LEFT`, `SS_CENTER`, `SS_DEFAULT`) and value strings (`vstr`) for generic items, which would cover ACTION_ and SUBMENU_ items and as a bonus, the whole menu item ecosystem would be unified, since every item would support label, value and justification.

I would probably have to modify the `*_ITEM` macros to support those arguments (which I was scared the most of probably), but since they basically support varargs, it should still be backward compatible.

I am not really sure how to easily fulfill the "_Pretty much anything that works, but which doesn't increase the code size for every regular menu item is what we're after._" and "_Also, if no features are enabled that use the Right Aligned string, we should make sure not to even compile it in._" commets of yours.
1) If I add some logic into the `::_draw` method, does that count as increasing the code size every regular item or does only the code that is the direct result of `_ITEM` macro expansion count?
2) In case of going the SS_FULL path... what is the best way not to compile the code if it is not needed? I can only think of either the developer having to manually set some MACRO flag or set that flag automatically inside the `_ITEM` macro when extra arguments are detected - if that actually can be done easily due to the amount of variation in _ITEM macros.


I am still eager to know you take on this.

**Comment by lukasradek** [comment]
@thinkyhead What is the difference between `STATIC_ITEM` and `PSTRING_ITEM`?

It would be great if Item macros could be named by their use case (static, edit, action,...) without being mixed up with `PSTRING`, which I guess is implementation-based naming. Furthermore now I am able to achieve with `STATIC_ITEM `what used to do with `PSTRING_ITEM` - display 2 individual strings. And I also can see, that `PSTRING_ITEM` internally uses `STATIC_ITEM`'s implementation.

Can `PSTRING_ITEM`s and `STATIC_ITEM`s be consolidated into just `STATIC_ITEM`s?

**Comment by lukasradek** [comment]
So I have reworked the system, which now uses 0 additional static pointers and instead follows the STATIC_ITEM's new styling paradigm.

It is working (needs testing on e3v2 and TFTGLCD, which I do not own), but it needs some cleanup a documentation of the _ITEM macros' syntax.

Per @thinkyhead 's request, I will consolidate this PR with https://github.com/MarlinFirmware/Marlin/pull/25339 and further work will continue there, since it builds on top of this.

**Comment by thinkyhead** [comment]
Moving this work over to #25339

**Pull request closed without merging**
