### PR TITLE
replace Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN 

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Nearly every single user who add a bltouch to their machine blindly enables 
Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN as the internet told them to

Solution replace #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN with

#define PROBE_IS_PLUGGED_INTO PROBE_PORT
or 
#define PROBE_IS_PLUGGED_INTO Z_MIN_PORT

### Requirements

A probe

### Benefits

Probably none, they still wont read it, but gotta try

### Configurations

remove #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
Add define PROBE_IS_PLUGGED_INTO  which can either be PROBE_PORT or Z_MIN_PORT

### Wanted
Thoughts and constructive advice

### CODE REVIEW

**Comment by ellensp** [comment]
Please Note: CI tests fail as Example Configs and Code are mismatched.

**Comment by thisiskeithb** [comment]
What about boards that split servo + probe pins? (SKR 1.4 comes to mind, but I know there are others)

This change will just cause even more confusion.

**Comment by ellensp** [comment]
can change FIVE_PIN_PROBE_PORT to just PROBE_PORT easy enough

**Comment by ellensp** [comment]
it actually same thing, just renamed for clarity and to break users just enabling things blindly.

#define PROBE_IS_PLUGGED_INTO Z_MIN_PORT  == #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
#define PROBE_IS_PLUGGED_INTO PROBE_PORT  == //#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
//#define PROBE_IS_PLUGGED_INTO  (Z_MIN_PORT| PROBE_PORT) == //#define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN

**Comment by ellensp** [comment]
The default in Configuration.h should be //#define PROBE_IS_PLUGGED_INTO undefined 
When a user just enables this they will get the error 
"PROBE_IS_PLUGGED_INTO must be set to either Z_MIN_PORT or PROBE_PORT"

**Comment by thisiskeithb** [comment]
Mimicking `SDCARD_CONNECTION` would probably be a good idea:

https://github.com/MarlinFirmware/Marlin/blob/45cf9973418279984ba511002f77ffb8af93f954/Marlin/Configuration_adv.h#L1680-L1689

**Comment by ellensp** [comment]
updated config description.

**Comment by thinkyhead** [comment]
**Notes:** The `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN` option is meant to apply to more "dumb" boards that don't have a dedicated probe port per se, so the normal assumption is that the probe is plugged into its own (PROBE) pin, either defined by the board or overridden by the config. But, if you want to plug it into the min plug (also the typical case for printers with a Z max endstop) there will not be a `Z_MIN_PROBE_PIN` used – only the `Z_MIN_PIN` will be looked at for Z probe `M119`, `G29`, `G30`, etc. As part of that, by default `G28` homing will also be done with the probe. So, that is the current overall meaning of the option at this time. It is not pretty, but it was arrived at through a progressive series of attempts to wrangle probe pin choice.

We did previously have an opposite option (`Z_MIN_PROBE_ENDSTOP`) but ended up with the current option after #13276.

While I have never been a big fan of the option, of course we want to be careful modifying such a longstanding precedent. So, let's see how it passes the initial review….

**Comment by thinkyhead** [comment]
Note: The default for most boards is still the `Z_MAX_PIN`, sometimes the `X_MAX_PIN`, and not a dedicated "`PROBE_PIN`" per se, so that is one caveat to this proposal. It is not really "Probe Pin vs. Z Min Pin" but "Z Min Pin vs. Next Best Choice."

**Comment by mikemerryguy** [comment]
> 

This is a great idea.  

To add to this you can add a description note.
// #define BLTOUCH 
//Please be advised of wiring your BL(CR)Touch sensor.  Some came with two plugs (3pin and 2 pin) or a single 5 pin plug.
//Some main boards will require changing 5V and GROUND wires as well.
//BE WARNED of this potential mismatch causing potential motherboard and or sensor damage.  
// DO NOT POWER YOUR BOARD / SENSOR UNTIL YOU VERIFY SCHEMATICS 


Granted this is only going to help those that build a firmware and there are a LOT of users who simply download something from a website and flash it without doing the research.

**Comment by ellensp** [comment]
giving up

**Comment by akinilicali** [comment]
This will confuse everyone who is used to the current wording and will not be of much help to the rest. It is only true for a certain range of Creality boards. Frequent changes may affect the learning curve of users. Unless completely confusing, no changes must be done here. If the current explanation in the firmware manual is not adequate, just make it more clear. That's all.

**Pull request closed without merging**
