### PR TITLE
Fix of servo pin on Azteeg X3 Pro to lineup with defaults

### PR DESCRIPTION
**Pull request by Natealus**
Cleaned up pull request since Thinky could push and merge faster lol. Just the pin swap now on mine I just had chosen 47 cause it's right next to the power pins. :)

### CODE REVIEW

**Comment by Natealus** [comment]
For some reason it won't let me just revert the wrong commits. Oi this can be a pain sometimes lol.

**Comment by thinkyhead** [comment]
@Natealus Not once they're pushed to the origin. But, you can create a new branch off of this with `git checkout -b my_feature`, which will relieve some pain, then Publish it using the Github client. Then (or before publishing), you can fetch the latest Development branch afresh with `git fetch upstream; git checkout Development; git merge upstream/Development`. And finally update your feature branch with `git checkout my_feature; git merge Development`.

**Comment by Natealus** [comment]
We'll have to talk about that sometime I was a bit lost as to where I do those command line portions. But I just reforked and cleaned it up. Vwalla new pull. :)

**Comment by thinkyhead** [comment]
@Natealus If you are using a Unix like OS X, or a Linux, then you have a BASH shell and a Terminal application, and you can install packages using a package manager such as the Debian Package Manager (or MacPorts on OS X). It's very useful to have a command-line with proper POSIX implementation for running all the good GNU and other open source software, such as `git`. The commands I cited would be run after you entered the directory where your copy of Marlin is stored (`cd /my/repo/folder`). Your Github desktop application may have an option when you right-click on a repository in the list, which will open up some kind of Terminal with the current directory set to your repo.

**Comment by Natealus** [comment]
Yeah I think I noticed a GitShell I'm guessing for similar functionality in Windows.

**Pull request closed without merging**
