### PR TITLE
[2.0.x] L6470 - add powerSTEP01 support

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
This PR includes all the changes/corrections of PR #13011.  The PR can be killed if this PR is implemented.

This PR adds support for the **powerSTEP01** family of steppers from STmicro.  The **L6480** is a subset of the powerSTEP01.

The code changes are a result of the following differences between the L6470 and the  powerSTEP01/L6480:
- Additional registers
- Register address changes
- Changes to bit locations and definitions

Selection between the two families is done via the **POWER_STEP** flag in **configuration_adv.h**.  This flag is used to select the appropriate code and the correct Arduino_L6470 library header.

See PR #12 for my proposed changes to the Arduino_L6470 library.  The changes that were made are:
- Added additional definitions and #if statements to select the appropriate definitions.
- Changed the Overcurrent Detection threshold and Stall threshold commands to allow for variable numbers of bits and variable "mA per count" constants.
- Created a header/CPP file set for each family.  The only differences between the two sets are several defines.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Squashed, rebased, and added a change to use `L64XX::chain`. See comments on ameyer/Arduino-L6470#12.

**Comment by Bob-the-Kuhn** [comment]
Changed to using subclasses to differentiate the stepper drivers and added the ability to select the slew rate used by the drivers..

Also fixed a bug in the pins_debug for DUE.

**TO DO:**
- @thinkyhead - please enlighten me on the desired method of keeping the linker from throwing an error when the external SPI routines are not present. I can't find your message on the proper method of configuring the L6470 library to do this.  
- Update the configuration files.

**Comment by Bob-the-Kuhn** [comment]
I must have a subconscious hatred of **L64XX::chain**  because, once again, I've undone **L64XX_chain => L64XX::chain** 

Say the word & I'll implement L64XX::chain..

**Comment by Bob-the-Kuhn** [comment]
I think Travis is sick.  I see another PR that filed the STM32F1 test.

I just dropped the "STM32F1R EEPROM_SETTINGS EEPROM_CHITCHAT REPRAP_DISCOUNT_SMART_CONTROLLER SDSUPPORT PAREN_COMMENTS GCODE_MOTION_MODES" options into a fresh copy of 2.0 and it compiled without errors on PlatformIO.  Lots of warnings but no errors.

I didn't find a compatible board listing in Arduino.  Always got the "Oops! Select an STM32F1 board in 'Tools > Board.'" message.

**Comment by thinkyhead** [comment]
> I think Travis is sick.

We'll just have to disable the STM32F1 test for now.

**Comment by Bob-the-Kuhn** [comment]
1. Found another area that didn't get the macros changes

2. Added a second status read  during the init which turns off the powerup/reset undervoltage lockout flags which turns off the ERROR LED on the STMicro eval board.

**Comment by thinkyhead** [comment]
Rebased, squashed, cleaned up…. Almost there……

**Comment by Bob-the-Kuhn** [comment]
Just pushed a partial fix to the compile errors when a L64xx driver is enabled.

Still lots of problems with lshadow.

---

just did a second commit to back out changes that the DIF indicated shouldn't have been there.  I'll do a squash of the two commits to make it easier to understand the changes I intended to make.

---

Just did a rebase and went to do the squash  but I didn't see my first commit from this morning so I quit.  I didn't do a push.

Looks like all of the **Encapsulate L6470_Marlin in a class** changes are there plus my intended changes.

---

The rebase & squash work definitely didn't do what I intended.  Looks like there are now duplicated commits and I don't see my second commit.

As usual, time to ask Scott to fix my GitHub screwups.

**Comment by Bob-the-Kuhn** [comment]
Definitely over my head as to how to fix the lshadow and index_to_axis link errors.



Here's the config I've been using and the error messages:
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/2915179/Configuration.h.txt)
[errors.txt](https://github.com/MarlinFirmware/Marlin/files/2915193/errors.txt)

**Comment by Bob-the-Kuhn** [comment]
> Instead of weak linking functions and requiring certain functions to be defined by clients of the library, it would be better to define typedefs for the needed function signatures and store pointers to those functions inside the class.

I tried to implement this but I didn't get the desired results.  The external SPI functions were always required.  

Is it OK to go back to the "weak" method?  It's the only way I've succeeded at creating a system that:
1. Allows a simple application to use the internal SPI without having to create dummy external SPI routines.
2. Will use external SPI routines if they are available.

**Comment by thinkyhead** [comment]
I'm on top of the errors that came from my last commit. You can take a break at this point.

**Comment by thinkyhead** [comment]
> I tried to implement this but I didn't get the desired results. The external SPI functions were always required.

This is how it is done. The handler pointers can be required arguments of the constructor, or they may be pre-populated to point to empty or smart default methods.
```cpp
#include <iostream>
#include <string>
#include <math.h>

using namespace std;

#define ENDL "\n"

class ClassWithHandlers {
public:
  typedef void (*void_handler_t)();
  typedef void (*arg_handler_t)(const int x);
  typedef int (*get_handler_t)(const int x);

  static void_handler_t void_handler;
  static arg_handler_t arg_handler;
  static get_handler_t get_handler;

  ClassWithHandlers() { }
  ClassWithHandlers(void_handler_t vh, arg_handler_t ah, get_handler_t gh)
    : void_handler(vh)
    , arg_handler(ah)
    , get_handler(gh)
    { }

  static inline void set_void_handler(void_handler_t void_h) { void_handler = void_h; }
  static inline void set_arg_handler(arg_handler_t arg_h) { arg_handler = arg_h; }
  static inline void set_get_handler(get_handler_t get_h) { get_handler = get_h; }

  void call_handlers() {
    if (void_handler) void_handler();
    if (arg_handler) arg_handler(1);
    if (get_handler) {
      int v = get_handler(2);
      cout << "get_handler returned " << v << ENDL;
    }
  }
};

ClassWithHandlers::void_handler_t ClassWithHandlers::void_handler = NULL;
ClassWithHandlers::arg_handler_t ClassWithHandlers::arg_handler = NULL;
ClassWithHandlers::get_handler_t ClassWithHandlers::get_handler = NULL;

void my_void_handler() { cout << "my_void_handler" ENDL; }
void my_arg_handler(const int x) { cout << "my_arg_handler got " << x << ENDL; }
int my_get_handler(const int x) { cout << "my_get_handler got " << x << ENDL; return x * 10; }

int main(int argc, char const *argv[]) {

  ClassWithHandlers myClass;
  cout << "No handlers set..." ENDL;
  myClass.call_handlers();

  myClass.set_void_handler(my_void_handler);
  myClass.set_arg_handler(my_arg_handler);
  myClass.set_get_handler(my_get_handler);
  cout << "All handlers set..." ENDL;
  myClass.call_handlers();

  return 0;
}
```

**Comment by Bob-the-Kuhn** [comment]
Way, **WAY** over my head.  

Even knowing what it does it took me three or four passes to get a handle on what it's doing.

Thanks

**Comment by thinkyhead** [comment]
It's not necessarily the most ideal way to do it. A similar way to do it would be to define a helper class that implements those three methods as stubs, and then instead of supplying three handler pointers you would just need to subclass the stub class and supply one helper object reference. Same general idea, but possibly cleaner. I will try both methods.

**Comment by thinkyhead** [comment]
I've added a `dev_handler_ptrs` branch to the `Arduino-L6470` project which uses the handler pointer method described, and I've added a last commit here that uses the updated branch. I haven't fully tested it yet. As usual…
```
git fetch origin
git checkout powerSTEP01-PR
git reset --hard origin/powerSTEP01-PR
```

**Comment by thinkyhead** [comment]
The helper class method seems to work the best. Under this approach, a base class (`L64XXHelper`) is declared with empty inline placeholder methods. The `L6470_Marlin` class becomes a sub-class of `L64XXHelper` and it implements the methods it needs (`spi_init`, `transfer`…). Because those methods are in the `L6470_Marlin` class they have easy access to methods and data in the class.

Instead of calling `spi_init` on the first stepper object, we just call `L6470_helper.spi_init` directly at the appropriate time.

Some things I noticed which raised questions…
- The `L64XX::init` (e.g., `stepperX.init()`, `stepperY.init()`…) method doesn't seem to be called anywhere. Does it need to be? Is this related to `L64XX::set_pins` not being used (so the SPI is handled by Marlin)?
- The `pin_SCK` on each `L64XX` object signals that SPI is being handled externally (i.e., by Marlin) for that stepper. How does the internal SPI handling differ, so that Marlin needs to handle it? Would it make sense to provide actual working stub methods for `L64XXHelper` based on what Marlin is doing, including code for future ARM platforms as they arise? That would move some of the L64XX code out of Marlin and would be one less thing to maintain in this tree.

**Comment by Bob-the-Kuhn** [comment]
As best I can tell the external SPI routine linkage is not happening.  The disassembly shows no code associated with line 299 in L6470.h (**static inline void set_helper(L64XXHelper & _helper) { helper = _helper;** } nor line 70 in L6470_Marlin.h (**L6470_Marlin() { L64XX::set_helper(*this);**}.  When I follow the program execution, line 446 of **L6470.cpp** immediately returns to the calling routine (without invoking any code).

I used the **dev_helper_class** branch for the L6470 library and the latest code in this PR.

I also made the following changes:
- Compile error - in **L6470_Marlin.h** and **L6470_Marlin.cpp**, argument list for **get_stepper_status** changed from **const L64XX &st** to either **L64XX &st** or **L64XX st**.  I used the latter in my testing.
- Compile warning -  in  **L6470_Marlin.cpp**,  changed **switch (axis)** to **switch ((uint8_t)axis)** - all three places.
- Logic error - in **L6470.h**, changed **typedef uint16_t _pin_t;** to **typedef int16_t _pin_t;**.  **uint16_t**  caused **(pin_SCK < 0)** in line 445 of **L6470.cpp** to always be false which results in it trying to use the internal SPI..

I also changed the code from nothing to  **return 0;**  in all the stubs in **L6470.h** to remove compiler warnings.

**Comment by Bob-the-Kuhn** [comment]
We may have a chicken & egg situation with the **set_helper** function.

As I understand it, **set_helper** can only be called by specifying an instance of L64XX.  That means we'd have to use something like **stepperX.set_helper(pointer);**.   I tried inserting **st.set_helper(pointer);** as the first line of code in **L6470_init_chip** in **stepper_indirection.cpp** but I couldn't create an acceptable pointer.

**Comment by Bob-the-Kuhn** [comment]
**L64XX::init** isn't used by Marlin because it powers up the steppers for a short period.  Since I need to init more items than **L64XX::init** addresses I just grabbed what I needed from **L64XX::init** and put them into the same routine as the Marlin specific inits.  I didn't want to change **L64XX::init** in an effort to keep the library as close to original as possible.

The internal and external SPIs do the same thing.   The issue is speed.  The internal SPIs are limited to digitalWrite & digitalRead because they have to be compatible with any Arduino sketch.  External SPIs can use FASTIO and hardware SPIs.

---

At first glance it looks like the class version isn't backwards compatible with the original Arduino-L6470 library.  Maybe we should just suck the library into Marlin and roll back Arduino-L6470 to it's original intent plus a few bug fixes.  It would make the Marlin code much simpler.

---

I'm seriously worried that the L64xx series offers very little performance improvement over the A4988.  I'll be doing some more testing the middle of the week but right now it doesn't look good.

I'm running a home built CNC machine with a 3D print head on it.  I ended up with 1.5A per phase high inductance steppers.    About 6 months ago I started playing with newer drivers hoping to maintain the A4988 performance but at reduced noise levels.  Even with some really impressive heatsinks, the TMC and DRV drivers couldn't move the steppers as fast as the A4988 at the same microstep settings.  The powerSTEP01 is the only driver I've found that can deliver higher currents than the A4988.  So far the higher current hasn't resulted in any performance improvement.  The only improvement over the A4988 is higher microstep settings but at much lower feed rates.   I made the mistake of hooking up all my steppers which killed my 24V supply.  When the replacement comes in I'll give it another shot.

I expect that I'll end up getting a new 3D printer.  Prices have come down a lot and performance is up compared to what was available 4 years ago.

**Comment by thinkyhead** [comment]
> `set_helper` can only be called by specifying an instance of `L64XX`…

An instance of `L64XXHelper`.

I'll look at how the code is behaving and see if there's a simple fix. The helper may just need to be a pointer instead of a reference (even though they are essentially the same under the hood).

**Comment by Bob-the-Kuhn** [comment]
There's still problems with the new macros in drivers.h.

Right now It seems to treat the L6470, L6480, & powerSTEP01 the same and always call it a L6470.

Tomorrow is a good day to look into this.  Can't seem to keep the various levels of the macros straight.

**Comment by thinkyhead** [comment]
> Right now It seems to treat the L6470, L6480, & powerSTEP01 the same

Which macro are you referring to?

**Comment by thinkyhead** [comment]
The `helper` is now stored as a pointer. See if that helps. The library changes did help fix issues with the two motors synchronized example. I didn't look at the assembler output (yet).
```
git fetch origin
git checkout powerSTEP01-PR
git reset --hard origin/powerSTEP01-PR
```

**Comment by thinkyhead** [comment]
Also rebased, squashed, and updated recently-added configs. Note that the `config` folder is now a sibling of the `buildroot` and `Marlin` folders.

My testing with the `Arduino-L6470` test project gives me hope that the library should work. C++ doesn't allow getting the address of a reference, so I had no (easy) way to check if `helper` (as reference) was changing on the call to `set_helper`. But as a pointer, I was able to confirm it was being changed.

I'm not sure if that was the source of the "all classes behave the same" behavior. As a test we can create instances of `L6470`, `L6480`, and `powerSTEP01` and compare their `constexpr` data members to see if they differ where they should. In my testing, they did differ as long as the object was used explicitly, and not being passed as a `L64XX&` or `L64XX*`.

**Comment by Bob-the-Kuhn** [comment]
What I'm finding is all L64XX steppers are being created as L6470 no matter what is in configuration.h

I played with the class defines in the Arduino-L6470 library to confirm this.

I then started playing with the instantiation code in **stepper_indirection.cpp**.    As best I can tell the values of the xx__DRIVER_TYPE and the drivers (L6470, L6480, powerSTEP01, ...) are all zero when the compiler gets to this code.

**EXAMPLE:**
Configuration.h:  `#define X_DRIVER_TYPE L6470`
stepper_indirection.h:  `95     extern AXIS_CLASS_X stepperX;`
stepper_indirection.cpp:
```
1068  #if AXIS_IS_L64XX(X)
1069    #if  X_DRIVER_TYPE == powerSTEP01
1070      powerSTEP01 stepperX((const int)L6470_CHAIN_SS_PIN);
1071      #warning "X driver type powerSTEP01"
1072    #elif X_DRIVER_TYPE == L6480
1073      L6480 stepperX((const int)L6470_CHAIN_SS_PIN);
1074      #warning "X driver type L6480"
1075    #elif  X_DRIVER_TYPE == L6470
1076      L6470 stepperX((const int)L6470_CHAIN_SS_PIN);
1077      #warning "X driver type L6470"
1078    #endif
1079  #endif
```

result:
```
Marlin\src\module\stepper_indirection.cpp:1071:8: warning: #warning "X driver type powerSTEP01" [-Wcpp]

#warning "X driver type powerSTEP01"
Marlin\src\module\stepper_indirection.cpp:1070:27: error: conflicting declaration 'powerSTEP01 stepperX'

powerSTEP01 stepperX((const int)L6470_CHAIN_SS_PIN);

^

In file included from Marlin\src\module\stepper_indirection.cpp:34:0:

Marlin\src\module\stepper_indirection.h:95:21: error: 'stepperX' has a previous declaration as 'L6470 stepperX'

extern AXIS_CLASS_X stepperX;

^

```


If I change the order of the **`if  X_DRIVER_TYPE ==`** clauses it's always the first one that gets executed and the error messages appear/disappear accordingly.

There's definitely something about the pre-compiler I don't understand.  **stepper_indirection.cpp** pulls in the **.h** file which declares the stepper properly but later in **.cpp** the instantiation is wrong.

**Comment by Bob-the-Kuhn** [comment]
This commit fixed a couple of host screen formatting problems and enabled setting of the slew rate on the L6480/powerSTEP01.  Turns out that register can't be written to if some bits that are set during the chip's internal reset sequence are active.  Clearing those bits requires reading the status register twice after the final config register write.

---

I have one change to the Arduino-L6470 library that shouldn't cause heartburn.  **_pin_t** needs to be **int16_t** rather than **uint16_t** or else the **if (pin_XXX < 0)** tests will always be true.

---

Still had to hard code the external SPI linkage. after your squash & rebase.

I'm looking forward to working on something other than the L6470 code.  The "weak linkage" option is looking better and better.  ☹️

---

I don't understand why but ... I found a cure for the "always uses L6470 values".

Turns out the instantiation is being called correctly by Marlin (drivers.h macros are correct).  What ever class is specified in configuration.h is what is used for the stepper.  The L6470, L6480 and powerSTEP01 driver classes were all using the L64XX values rather than the ones defined in driver classes.  

See the attached for the work around I stumbled across.  I removed the static designations and then set the driver specific values as part of the class instantiation call. The **L6480::** and **powerSTEP01::** parts are required.  

[L6470_mod.zip](https://github.com/MarlinFirmware/Marlin/files/2926771/L6470_mod.zip)

It isn't pretty and it has some test code in it.

**Comment by thinkyhead** [comment]
> The "weak linkage" option is looking better and better.

Not required in C++. In the simplest case, we would just define the `64XXHelper` class with only method declarations, no empty placeholder function bodies. Then it just requires Marlin to actually implement the `64XXHelper` class methods. Also, "weak linking" doesn't mean anything in Arduino-land, because we don't use binary libraries, only sources.

I will go through this and the L64XX library over the next few days and make sure it is compiling to what we want and that it isn't complicated to use.

**Comment by thinkyhead** [comment]
Rebased on the latest `bugfix-2.0.x` to resolve merge conflicts.
```
git fetch origin
git checkout powerSTEP01-PR
git reset --hard origin/powerSTEP01-PR
```

**Comment by Bob-the-Kuhn** [comment]
Just in case it's of any use ...

Here's  the L6470.h file, using the method I stumbled across, made all nice & pretty.  If nothing else it could be a convenient source of nicely formatted lines for the final version.

[L6470 pretty.zip](https://github.com/MarlinFirmware/Marlin/files/2950104/L6470.pretty.zip)

---

I tried using the **L6470 stepperX(stepperZ3(L6470_CHAIN_SS_PIN, L64helper_pointer)** to get the helper linkage but couldn't get past the compiler errors.

I tried that method because, if I remember correctly, the **L64XX::set_helper(this)** in **L6470_Marlin.h** has to be of the form **stepperX.set_helper(this)** to execute during run time.

**Comment by Bob-the-Kuhn** [comment]
For your consideration...

This code is fully functional.  The only thing I want to do is rebase the code.

I reverted back to your handler/pointer code and got it working.  I then removed the helper class from L6470.h and renamed the helper class in L6470_Marlin.h.

Here are the Arduino-L6470 files that go with this code.
[L6470 pointers.zip](https://github.com/MarlinFirmware/Marlin/files/2956298/L6470.pointers.zip)

---


- 90% of the changes are in L6470.h & L6470_Marlin.h
- 9% of the changes are in L6470.cpp & L6470_Marlin.cpp
- Added **set_handlers** function to **L6470_init_chip routine** in **stepper_indirection.cpp**
- All other files just have name changes.

**Comment by Bob-the-Kuhn** [comment]
Just rebased the code and now the Y & Z step pulses are gone when using L64xx drivers and when using A4988 drivers.

~I'll look into it later today.~

UPDATE

Turns out I was running into software endstops.  Looks like they are now always on except if you enable them in configuration.h and then issue a M211 S0 command.

**Comment by Bob-the-Kuhn** [comment]
The Travis test is failing do to the error:  **'class L64XX' has no member named 'set_handlers'**.

I'm pretty sure the reason is Travis is using a different Arduino-L6470 library than required by this PR.

FYI - **G26_MESH_EDITING** is enabled on multiple tests within **megaatmega2560-tests**.  It has been replaced by **G26_MESH_VALIDATION**.

**Comment by thinkyhead** [comment]
I will be offering courses on git usage here in Austin for anyone interested.

**Comment by Bob-the-Kuhn** [comment]
😉  What?!?!  You think that a little education might stop me from writing over your work?

Others have tried to educate me but I've foiled them all!

---

Yes, I'd like to participate.  I'm retired with only Dr. visits on the calendar so I'm pretty open.

Thanks for being so patient.  

Your 3 line set of instructions on how to suck the latest PR code back into my local branch has been very useful.

**Comment by Bob-the-Kuhn** [comment]
I just grabbed the changes since my commit a week ago, fixed the bugs that were introduced and tested the code.  It looks to be 100% functional.

There are two items of note:
- **drivers.h** - I removed the qualifiers on the X2, Y2, Z2 & Z3 macros.  They caused the macros to always evaluate to false no matter what driver was specified for the axis.
- **index_to_axis[][]** - I was getting compiler errors until I simplified the declarations in **L6470_Marlin.h** and **L6470_Marlin.cpp.** I just couldn't find a mod to **L6470_Marlin.cpp.** that resulted in a match to the declaration in the following error message; " error: 'L64XX_Marlin::index_to_axis' has a previous declaration as 'const char* const L64XX_Marlin::index_to_axis [13][3]'"

**Comment by thinkyhead** [comment]
Thanks for slogging through my different theoretical approaches to the L6470 code. If the helper method works, that is fine, and is probably the best approach for Arduino-style libraries.

**Pull request closed without merging**
