### PR TITLE
Enable USE_WATCHDOG by default

### PR DESCRIPTION
**Pull request by thinkyhead**
As suggested by @daid and others, make thermal protection as safe as possible by default.

### CODE REVIEW

**Comment by valdemar4eg** [comment]
Dear all,
Could somebody, please, explain in more details how does WATCHDOG works on  geeetech gt2560 (mix on Andruino Mega 2560)? My printer quite often crushes  in the middle of the print with all heaters on. So I would like to use all safety features available on Marlin. 

These comments in the code are not clear to me.
#ifdef USE_WATCHDOG
// If you have a watchdog reboot in an ArduinoMega2560 then the device will hang forever, as a watchdog reset will leave the watchdog on.
// The "WATCHDOG_RESET_MANUAL" goes around this by not using the hardware reset.
//  However, THIS FEATURE IS UNSAFE!, as it will only work if interrupts are disabled. And the code could hang in an interrupt routine with interrupts disabled.
//#define WATCHDOG_RESET_MANUAL
#endif 

Thank you in advance

**Comment by daid** [comment]
@valdemar4eg Pretty simple, you only use `USE_WATCHDOG` do not use `WATCHDOG_RESET_MANUAL`. That should protect you from leaving the heaters on, IF it is the firmware that is crashing.

`WATCHDOG_RESET_MANUAL` is a pretty bad feature and shouldn't be used. I'm the one that added those warning comments.

**Comment by valdemar4eg** [comment]
Dear Daid,
thanks for the reply. If I will uncomment `#define USE_WATCHDOG` device will hang in the loop but will switch off all outputs and will work normally only if  I will reset the power supply. Am I right?

**Comment by daid** [comment]
@valdemar4eg yes (or it might reboot, depends on which bootloader they put into the chip)

**Comment by thinkyhead** [comment]
Does anyone want to vote against this PR? I originally submitted this thinking it would be extra-helpful for thermal protection, but I realized later actually this is "hang" protection — still pretty helpful as a safety feature, but indirectly. So, does anyone think this _definitely should not_ be enabled by default for any reason?

**Comment by CONSULitAS** [comment]
:+1: 
Safety features have to be enabled by default. Everything else would be grossly negligent (careless in sense of law)!

If somebody decides that this doesn't fit for his printer, he can disable it, but he has to think about the consequences and to care for safety on his own.

So we should add a standard warning comment to this and thermal protection like:

```
// SAFETY FEATURE! Think twice before deactivation and be careful to avoid damage to persons and property.
```

**Comment by thinkyhead** [comment]
@CONSULitAS Your passion has swayed me to your position.

**Pull request merged**
