### PR TITLE
language_de.h: updated translation and minor typos

### PR DESCRIPTION
**Pull request by CONSULitAS**
language_de.h: updated translation and minor typos

@AnHardt Many thanks for the great translation and display work up to now!

### CODE REVIEW

**Comment by AnHardt** [comment]
About 'jerk' versus' Ruck' i had some discussions. Like other concepts in RepRap firmwares 'jerk', for the first time user, needs explanation. While you can find lots of stuff about 'jerk' we then, could not find usable information when searching for 'Ruck'. Even in the German articles mostly the term 'jerk' was used. So we decided for 'jerk'. This may have changed now (6 month later).

**Comment by CONSULitAS** [comment]
@AnHardt I see your point, but I think it is common nonsense in modern Denglish (even in articles of serious publications like c't) to use english words even if there are good german words which are easy to understand.

But I admit that I thought about this point for a while, too. With homen/homing there is no good translation IMHO.

**Comment by AnHardt** [comment]
"Endschalter anfahren" is good but very long and yes, Home is a more fixed therm in the CNC-scene then 'jerk'. No complaints from my side.

**Comment by thinkyhead** [comment]
"Anfangsposition" or "Ausgangsposition" doesn't seem too bad – or is it? While having fun with language, I see in German, the word for "home" crosses with the word for "house." So I get translations like "Rückholhaus" for "Return home." (Hey, look, more "Rück…"). But we could also consider "Ursprung" or other similar terms...

**Pull request merged**
