### PR TITLE
Propose a new syntax to define UI for dgus

### PR DESCRIPTION
**Pull request by yufanyufan**
### Description

A demonstration of new syntax to easily define UI elements.
If this is accepted, I will change the whole implementation to use new syntax.

### Benefits

1. UI design is based ui_api instead of internal variables.
2. UI logic is clear to glance, not hiding under Functions.
3. DGUSScreenHandler can be greatly simplified. it does not rely on switch case to reuse functions.

### CODE REVIEW

**Comment by thinkyhead** [comment]
The methodology is alright, but it might be good to create some pre-defined getters and setters that are already typed, because it seems like it would get tedious having to specify the `<type signatures>` on every usage.

**Comment by yufanyufan** [comment]
Take example:

`
&dgusdisplay.GetVariable<ExtUI::extruder_t, ExtUI::setTargetTemp_celsius, ExtUI::E0>
`

We can make it shorter, by making it a global function and using namespace,

`
&GetVariable<extruder_t, setTargetTemp_celsius, E0>
`

I feel 

`&GetExtruderVariable<setTargetTemp_celsius, E0>
`

 is not too much a simplification.

**Comment by yufanyufan** [comment]
Add syntax sugar, PTAL

`
VPHELPER(VP_T_E0_Set, nullptr, GET_VARIABLE(setTargetTemp_celsius, E0),
                                   SET_VARIABLE(getTargetTemp_celsius, E0))
`

**Comment by thinkyhead** [comment]
Hey, why not? Looks much prettier!

**Pull request merged**
