### PR TITLE
E3V2 Enhanced UI localisation improvements

### PR DESCRIPTION
**Pull request by lefterisgar**
### Description
First of all I wish to all of you a happy and productive new year!

I created this PR in continuation of #23375, in which I have discussed about the need of more standardization of UI messages which are now a bit over the place and hard coded. I have altered the Ender 3 V2 Enhanced UI implementation of @mriscoc to use as many "standard" messages as possible. I have also added many new messages to the language_en.h file.

### Improvements

- Improved code readability (in my opinion)
- The scenario of having multilingual support on the DWIN display will be handled (almost) automatically (at least on the Enhanced UI)

### Related Issues

Although all the changes were made for good, it's possible that I have broken something in the process or what I've done is completely wrong. Please have a look and make sure that the modifications of the language_en.h file don't cause any unintentional problems and adhere to the guidelines of Marlin.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Do accented characters actually draw correctly? I forget if we added a translation layer to convert accented characters into plain ASCII for DWIN displays.

**Comment by thinkyhead** [comment]
I want to bring @mriscoc into the loop to ask about `MenuItemClass` versus `MenuItemPtrClass` and `ADDMENUITEM` versus `ADDMENUITEM_P`…

In Marlin the `_P` suffix is meant to designate `PROGMEM` pointers, while corresponding things without `_P` refer to normal C-style constant things. Meanwhile, the `F()` wrapper, `GET_TEXT_F`, `FSTR_P`, etc., are used in relation to `__FlashStringHelper*`, which is just a convenience wrapper for `PROGMEM` strings so that they can be distinguished from string pointers in method/function signatures.

At this time, all methods which expect `PROGMEM` strings should be using `FSTR_P` as the string argument, with an overload taking `const char *` for the few cases where a composed C string in SRAM should be passed. Methods which previously took `PSTR` directly should be eliminated, since a `PSTR` cannot be distinguished from an SRAM string.

It seems like the constructors and macros I mentioned in the first paragraph are not consistent with this, and may need a careful overhaul to ensure they are following this pattern.

**Comment by mriscoc** [comment]
Hi, the difference between `MenuItemClass` and `MenuItemPtrClass`, is that the later adds a parameter that is a pointer to a variable to be modified trough the menu item.
What could be a better name for `ADDMENUITEM_P`? maybe `ADDMENUITEMPTR`?

**Comment by mriscoc** [comment]
> Do accented characters actually draw correctly? I forget if we added a translation layer to convert accented characters into plain ASCII for DWIN displays.

There is not a translation layer implemented on the Enhanced UI nor in the DWINUI, I'm not sure about the impact of a translation layer in the performance of the UI, It could be implemented in the dwin_api.cpp just before of print a string.

**Comment by thinkyhead** [comment]
> What could be a better name for `ADDMENUITEM_P`? maybe `ADDMENUITEMPTR`?

I had to look closer to realize they are not different on the basis of the string title….

They both call `DWINUI::MenuItemsAdd`, allocating an instance of either `new MenuItemClass` or `new MenuItemPtrClass` with the given arguments. The `MenuItemPtrClass` is generally associated with editable values. So, if it was called "`ADDEDITITEM`," would that be accurate in all cases?

> There is not a translation layer implemented …

So, although the use of the localization pattern makes the code look nicer and sets it up for future improvement, at this time languages with accented characters cannot actually be used. And of course, it will be a long, long time before we can display Greek, Cyrillic, etc.

**Comment by mriscoc** [comment]
> They both call `DWINUI::MenuItemsAdd`, allocating an instance of either `new MenuItemClass` or `new MenuItemPtrClass` with the given arguments. The `MenuItemPtrClass` is generally associated with editable values. So, if it was called "`ADDEDITITEM`," would that be accurate in all cases?
> 
After checking the implementation, I agree that `ADDEDITITEM` could be a good name rather than `ADDMENUITEM_P` I will to use that in the next PR also with some additions.

**Comment by lefterisgar** [comment]
> And of course, it will be a long, long time before we can display Greek, Cyrillic, etc.

As always, I'm late here... My question is what needs to be done in order for support to come? Do new fonts have to be created? Must the DWIN LCD be reflashed? Does it need to be like Creality's implementation of placing Chinese characters into an image file and drawing part of the image to show a specific letter/symbol? I'm sorry if I'm asking obvious stuff but I'm not a skilled dev myself (16) and have no experience with those things.

**Comment by mriscoc** [comment]
@thinkyhead :
After re-check this PR, I have a doubt:
Marlin has a Bed tramming option (ASSISTED_TRAMMING), also has a Leveling bed corners menu (LEVEL_BED_CORNERS). I think that the menu in the Enhanced UI implementation is more like to LEVEL_BED_CORNERS than ASSISTED_TRAMMING and maybe the name of the menu must be "Leveling bed corners"

**Comment by lefterisgar** [comment]
@mriscoc [This](https://github.com/MarlinFirmware/Marlin/pull/23009#issuecomment-950549868) might be of help to you. It was posted on a previous PR I had opened which somewhat included this issue. Also do you happen to know anything about what needs to be done to support Cyryllic, Greek, etc.?

**Comment by mriscoc** [comment]
@lefterisgar please review the labels for the print page, the total print time and remaining time are too large to fit next to the icons. The former labels for the given font size were: 
```cpp
void Draw_Print_Labels() {
  DWINUI::Draw_String( 46, 173, F("Print Time"));
  DWINUI::Draw_String(181, 173, F("Remain"));
}
```
image

**Comment by thinkyhead** [comment]
At this time any references to "corner leveling" that have not been changed to use the term "tramming" or "bed tramming" should be modified.

**Comment by lefterisgar** [comment]
@mriscoc Issue has (hopefully) been fixed. Thanks for letting me know!

**Pull request merged**
