### PR TITLE
fix macro

### PR DESCRIPTION
**Pull request by tonnico**
add some missing backslashs

### CODE REVIEW

**Comment by alexborro** [comment]
Did you find any issue related to this error?
Em 17/03/2015 08:53, "Wurstnase" notifications@github.com escreveu:

**Comment by tonnico** [comment]
No, just reading through the code and find this.

**Comment by alexborro** [comment]
@thinkyhead , could you please check this?? The code is compiling ok and suppose to work fine.. Is that a coding error???

**Comment by AnHardt** [comment]
This is conditional code. When CONFIG_STEPPERS_TOSHIBA is defined compilation fails.

**Pull request merged**
