### PR TITLE
FTDI EVE: Cyrillic font and some minor fixes

### PR DESCRIPTION
**Pull request by LinFor**
### Description

1. Add cyrillic font glyphs for FTDI EVE displays. Currently it contains only russian subset and costs about 27KiB of flash when TOUCH_UI_UTF8_CYRILLIC_CHARSET enabled.
2. Slighlty optimized fonts upload (and other rle-encoded data) by SPI (doesn't send 3-byte address word for each uploaded byte).
3. Slightly reorganized FTDI RAMG fonts adressing to simplify future font additions.
4. bitmap2cpp.py updated to run on python3.
5. Fix draw_text_with_ellipsis() behavior on utf8 strings (incorrect string cutting).
6. Fix longFilename invalidating when UTF_FILENAME_SUPPORT enabled (single zero byte (terminator) converted to non-zero bytes and longFilename considered to exist).

### Benefits

Better user expirience:

### Configurations

TOUCH_UI_UTF8_CYRILLIC_CHARSET

### Related Issues

None found

### CODE REVIEW

**Comment by thinkyhead** [comment]
Maybe we can automate the setting of `TOUCH_UI_UTF8_CYRILLIC_CHARSET` based on the selected language(s). Is this one of the screens currently supporting multi-language? If so, the test is just a little more complex.

**Comment by LinFor** [comment]
> Maybe we can automate the setting of `TOUCH_UI_UTF8_CYRILLIC_CHARSET` based on the selected language(s). Is this one of the screens currently supporting multi-language? If so, the test is just a little more complex.

Yes, it can switch languages on the fly. I will think about how best to do it, since I, for example, prefer to use the English translation (since Russian is sometimes impossible in some places), and at the same time I want to see the file names in my native language.

**Comment by thinkyhead** [comment]
Essentially, if Russian, Ukrainian, etc., are at all possible to be selected then it makes sense to have `TOUCH_UI_UTF8_CYRILLIC_CHARSET` enabled automatically. But also, I guess it makes sense to have a top-level option since it's possible to have file listings that contain Cyrillic characters even though you might not be using any of those languages in the LCD interface.

**Comment by LinFor** [comment]
> Essentially, if Russian, Ukrainian, etc., are at all possible to be selected then it makes sense to have `TOUCH_UI_UTF8_CYRILLIC_CHARSET` enabled automatically. But also, I guess it makes sense to have a top-level option since it's possible to have file listings that contain Cyrillic characters even though you might not be using any of those languages in the LCD interface.

Ok. Some notes to take into account:

- For correct Ukrainian and Belarusian translations support we need some additional glyphs: 4 additional glyphs (І і Ў ў) for Belarusian and 8 glyphs (Ґ ґ Є є І і Ї ї) for Ukrainian. In this case, I have included only the Russian subset of cyrillic (66 glyphs), since even the main block of the Cyrillic alphabet in Unicode consists of 256 glyphs, this would take too much memory. Other Cyrillic languages are generally a mystery to me.
- There are some problems with the rendering of labels on standard controls (now this is seen in particular on the toggle element), this is due to the amazing method of saving memory used by Marcio Teixeira. With this, too, you will have to come up with something.

**Pull request merged**
