### PR TITLE
320x240 LCD portrait mode UI

### PR DESCRIPTION
**Pull request by alexgrach**
### Description

320x240 LCD portrait mode UI.

main
move

### Requirements

MKS Robin Nano, MKS Robin TFT 2,8"

### Benefits

No HW modification is needed for 3D printers with portrait orientation LCD in stock (tested on Kingroon KP3S).
### Configurations

[Configuration_kp3s.zip](https://github.com/MarlinFirmware/Marlin/files/10345386/Configuration_kp3s.zip)

### CODE REVIEW

**Comment by ellensp** [comment]
Is this the best way to implement this?
There is already #define TFT_ROTATE TFT_ROTATE_90, vs defining a new screen size  (not sure if this works at present, but should be made to)

**Comment by alexgrach** [comment]
Are you shure? It should look like this:
`#if TFT_ROTATE == TFT_ROTATE_90 || TFT_ROTATE == TFT_ROTATE_90_MIRROR_X || TFT_ROTATE == TFT_ROTATE_90_MIRROR_Y || TFT_ROTATE == TFT_ROTATE_270 || TFT_ROTATE == TFT_ROTATE_270_MIRROR_X || TFT_ROTATE ==  TFT_ROTATE_270_MIRROR_Y`
Maybe it's better add something simular to DWIN display?
`#define TFT_COLOR_UI_PORTRAIT`

**Comment by crazyfrog1** [comment]
Please post a full build I can compile. I had several errors trying to compile from your build
image

**Comment by alexgrach** [comment]
[bugfix-2.1.x.zip](https://drive.google.com/file/d/17JERa9FuBMikMxL3-hLkkbjATB9G_ol1/view?usp=share_link)

**Comment by SimoneDallaC** [comment]
Hello. This thing you can also have with a tft35?

**Comment by alexgrach** [comment]
Any 320x240 graphical LCD should work.

**Comment by SimoneDallaC** [comment]
Thanks for your answer. Can you help me with some indication to be able to do it also in a tft35?

**Comment by ellensp** [comment]
"Any 320x240 graphical LCD should work."   where the lcd is controlled by Marlin.
This is not applicable to tfts that are running their own firmware that talk serial.

**Comment by thinkyhead** [comment]
@alexgrach — For some reason I cannot merge changes into this PR directly. So, please merge alexgrach/Marlin#1 at your earliest convenience! There are some more changes, likely, from PR #25073 that might also apply to the 240 x 320 portrait display, so please diff/compare your new files with the 320 x 240 versions to see if any other non-yet-applied changes should be applied. Thanks for the submission! Hopefully we will soon consolidate all the common parts of these different-sized displays –maybe in `ui_common.cpp`– and reduce the redundancies of these files.

**Pull request closed without merging**
