### PR TITLE
Fix Return chars output vs not used maxlen

### LINKED ISSUE #26148: [BUG] Character LCD Menus Misaligned
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Some LCD submenus are displayed with misalignment. See photos below.

### Bug Timeline

Started sometime between eca80db and 87231b6

### Expected behavior

Menus displayed correctly.

### Actual behavior

Alignment of menu items is wrong and some menus just look generally messed up. 

Examples:
IMG_9415
IMG_9416
IMG_9417

### Steps to Reproduce

1. Upload latest bugfix
2. Navigate to submenus on LCD
3. Observe incorrect display

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Geeetech A10M

### Electronics

Stock board, stock LCD

### Add-ons

None

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/12263785/Archive.zip)

### PR DESCRIPTION
**Pull request by lukasradek**
### Description

There was an unintentional reinterpretation of return value.
Callee `lcd_put_u8str_P` was returning remainder of maxlen quota while callers returned the same value as number of characters emitted.

Since I feel like returning remainder of maxlen quota was a "hacky" crutch for some pieces of code (so that they don't have to subtract chars emitted from remaining space themselves) and many other methods use the "return chars emitted" paradigm, I have ditched the "return remainder" and adjusted the rest of the codebase where the return value was used.

HD44780, DOGM- adjusted and tested
TFTGLCD - adjusted analogically but NOT tested
TFT, e3v2 - not using return values
extui - not using method

### Requirements

LCD display

### Benefits

Unification of char drawing API
Fixes menu alignment
It also solved some `SS_FULL` styling (probably mostly visual) issues that were caused by the remainder vs emitted confusion and possible character pixel width vs character count confusion (which should be looked at as well).

### Related Issues

Fixes https://github.com/MarlinFirmware/Marlin/issues/26148
Will "conflict" with my https://github.com/MarlinFirmware/Marlin/pull/25619 and https://github.com/MarlinFirmware/Marlin/pull/25339 since I have solved this issue in those as well a few month ago.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Thanks for the fix! 

I have verified that this PR fixes several display/menu alignment issues on a 2004/character/`REPRAP_DISCOUNT_SMART_CONTROLLER`.

Hopefully this makes it in before 2.1.3 😄

**Comment by lukasradek** [comment]
That really should make it before 2.1.3 😁. I guess you are one of those who can actually do it and it is just 4 changes files. 🙂

**Comment by ellensp** [comment]
@lukasradek sadly its pretty much only @thinkyhead that can do this.

**Comment by lukasradek** [comment]
So let's believe 🙂.

**Pull request merged**
