### PR TITLE
Correction of heavy vibration when printing on Delta after #15481

### PR DESCRIPTION
**Pull request by DenisSemenov1970**
### Requirements

Correction of heavy vibration when printing on Delta after #15481 
### Description
In change #15481 not correct replacement instead of !BOTH( JUNCTION_DEVIATION, LIN_ADVANCE) to HAS_CLASSIC_E_JERK.

The code [!BOTH( JUNCTION_DEVIATION, LIN_ADVANCE)] 
is equivalent [!(ENABLED(JUNCTION_DEVIATION) && ENABLED(LIN_ADVANCE)] 
the value is false only if JUNCTION_DEVIATION and LIN_ADVANCE are enabled.

The code [HAS_CLASSIC_E_JERK] is equivalent [ (ENABLED(CLASSIC_JERK) || IS_KINEMATIC) && DISABLED(LIN_ADVANCE)] simply enable only LIN_ADVANCE and the value will be false.
This is incorrect!!!

The code [!HAS_LINEAR_E_JERK] 
is equivalent [!(DISABLED(CLASSIC_JERK) && ENABLED(LIN_ADVANCE))] is the correct replacement.
the value is false only if JUNCTION_DEVIATION(disabled CLASSIC_JERK) and LIN_ADVANCE are enabled.

I made these changes to my copy and the vibrations of my Delta were gone.
Need to fix in the following files:
Marlin\src\gcode\config\M200-M205.cpp line 162 instead of #if HAS_CLASSIC_E_JERK to #if !HAS_LINEAR_E_JERK,
Marlin\src\gcode\config\M92.cpp line 79 instead of #if HAS_CLASSIC_JERK to #if HAS_CLASSIC_JERK && !HAS_LINEAR_E_JERK,
Marlin\Marlin\src\lcd\menu\menu_advanced.cpp line 475 instead of #if HAS_CLASSIC_E_JERK to #if !HAS_LINEAR_E_JERK,
Marlin\Marlin\src\module\configuration_store.cpp lines 2261,2776 and 2794, instead of #if HAS_CLASSIC_E_JERK to #if !HAS_LINEAR_E_JERK.
### Benefits

Fix heavy vibration when printing on Delta with LIN_ADVANCE

### Related Issues

[BUG] Heavy vibrations when printing on delta, SKR1.3 with TMC 2208 UART #15908

### CODE REVIEW

**Comment by GMagician** [comment]
I think you have to start from 2.0.bugfix, not 1.1

**Comment by DenisSemenov1970** [comment]
Sorry This is my first time. Mistaken

**Comment by GMagician** [comment]
> Sorry This is my first time. Mistaken

@DenisSemenov1970 that's ok, don't worry

**Comment by GMagician** [comment]
@DenisSemenov1970 I'm sorry, I wrongly reported 1.1 but you have done something on dev 2.1.
Currently 2.1 is not used, it'll be when 2.0 whill be released.
To start now create a branch from a 2.0 bugfix and reapply your fix to this new branch. Then you may post PR

**Pull request closed without merging**
