### PR TITLE
Added support for Geeetech GT2560 Rev. A and Rev. A+

### PR DESCRIPTION
**Pull request by fonix232**

### CODE REVIEW

**Comment by Maxqia** [comment]
Testing this, the screen seems to not refresh after clicking into a menu, until I move the menu cursor. Don't know if this is an issue with Marlin or just this PR...

**Comment by fonix232** [comment]
Since this PR is supposedly does not touch display refresh at all (I have added some extra lines for display definition made by @galorin in his original code changes, though on my end it refreshes just fine).

**Comment by Maxqia** [comment]
... fixed after rebasing this commit on the latest bugfix-1.1.x branch.

**Comment by dobryj** [comment]
Hi,

I must correct one line in pin configuration.
GT2560 rev A+ need this line (tested with 3Dtouch in servo connector)

#define SERVO0_PIN         11

See to https://www.geeetech.com/Documents/3DTouch%20auto%20leveling%20sensor%20%20User%20Manual%20version2.0.zip

Previous versions using Z-max pin for the servo (with replaced connector). See to referenced document. Untested, I have A+

**Comment by nesalkiN** [comment]
Yeah. With Rev A you use #define SERVO0_PIN         32 if you use the sensor but that could be added by the user. You need to know what you are doing if getting BLTouch to a Rev A board. The original config from Geeetech has SERVO0_PIN 13

**Comment by fonix232** [comment]
All issues should be solved now!

**Comment by deram** [comment]
Is there any chance getting this into 1.1.x releases?

I applied the patches on top of 1.1.3, and built an usable firmware for printer with GT2560A+ board on it.

**Comment by svolpe** [comment]
When will this get  merged in?  I have gotten the Geeetech PRUSA Rev A working but do not want to do a pull request until this one is merged in since my pull request shares some files added by this one

**Comment by Phr3d13** [comment]
+1 asking for this to be merged in.

**Comment by thinkyhead** [comment]
It will get in soon. I'll need to do a once-over to clear up any typos and whitespace issues, plus update the new config files to match updates in the configs since this PR was introduced. That shouldn't take long using a diff tool. Anyhow, expect this to probably be merged later today.

**Comment by thinkyhead** [comment]
Merged at #7442

**Pull request closed without merging**
