### PR TITLE
Update board/teensy comment

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

Fixes mismatched Teensy 4.0/4.1 board names and disables tests with insufficient pin definitions.

### Benefits

Make it possible to build with Teensy 4.1. 

### Configurations

N/A (just CI tests)

### Related Issues

N/A

### CODE REVIEW

**Comment by thinkyhead** [comment]
It was my understanding from comments on the original submission that Teensy 4.0 is not really supportable, at least not for common Marlin applications, and that the pins file we have now only pertains to the 4.1 version which has all the necessary pins. What exactly are the differences between the two boards?

**Comment by sjasonsmith** [comment]
I have no idea. I don’t care one bit about Teensy support. I was just trying to make sure other changes I made did not fail CI for any environments and saw the broken tests sitting there.

Your explanation is the reason I disabled features/tests rather than trying to add pins.

**Comment by thinkyhead** [comment]
I see. I was asking because it seemed like an authoritative move to rename it to `BOARD_TEENSY40_41`. Since it's my understanding that we can't really do Teensy 4.0, I want to be careful not to set up false user expectations.

**Comment by sjasonsmith** [comment]
I didn’t intend that as an authoritative move. It was just mismatched between the files so I picked one. I don’t care which remains. I have no intention of ever using them.

**Comment by sjasonsmith** [comment]
Feel free to just close this if you want. I’m not sure why it went in all broken in the first place, though.

**Pull request merged**
