### PR TITLE
Update ST STM32 platform to version 12.1

### PR DESCRIPTION
**Pull request by margaale**
### Description

Update ststm32 package to version 12.1.

[Release notes](https://github.com/platformio/platform-ststm32/releases/tag/v12.1.0)

### CODE REVIEW

**Comment by ellensp** [comment]
Hasn't common_stm32f1 been crippled enough with upgrading the platform with zero testing?

**Comment by GhostlyCrowd** [comment]
Agreed, Several platforms on STMF1 have had issues since moving from 6.1 to 10 way back in Fall 2020 that are just coming to light now, this should be tested.  I'll test on stm32 hal with my SKR pro this week. Just testing some G26 Hilbert Curve  PR right now and dont want to toss in more possible issues.

**Comment by thisiskeithb** [comment]
> Hasn't common_stm32f1 been crippled enough with upgrading the platform with zero testing?

There was talk of rolling back the last platform updates since they have caused havoc on boards under the STM32F1 HAL, so we’ll see.

**Comment by rhapsodyv** [comment]
According with the release notes, it will not impact us...

**Comment by studiodyne** [comment]
👍  For RUMBA32 F446VET6  🥇

**Comment by thinkyhead** [comment]
The only way that ststm32 12.1 will ever get well-tested against Marlin is if the `bugfix-2.0.x` branch is modified to use it.

I'm open to other ideas how to get quick testing and feedback on new platform releases. Without any feedback about the updated platform — and more than a fortnight between replies — it's too close to a 2.0.8 release to make the switch now. There needs to be a good month or more of testing with a new platform version before it can go into a release.

In future I may be able to put out more frequent releases and maintain a "cutting-edge" branch with less-tested elements, but that takes more work. And over time I've found that the most expeditious way to 'recruit testers' has just been to merge the changes and await the reports.

**Comment by thisiskeithb** [comment]
This PR fixes a non-boot issue with an SKR 2: https://github.com/MarlinFirmware/Marlin/issues/21732

**Comment by Eliminateur** [comment]
i have manually been using 12.1.1 platform since it came out with my STM32F1 platform and so far i've yet to see any issues.
i'm running essentially 2.0.x bugfix.
since 13.0 came out today i'll be building against that as well as the changelog seems to have no impacts either, same as 12.1.1 vs 12.1

**Comment by rhapsodyv** [comment]
@thinkyhead I think we can merge this now.

**Pull request merged**
