### PR TITLE
Add ZRIB support

### PR DESCRIPTION
**Pull request by ghost**
Another try at getting ZRIB support into Marlin. 
There have been other pull requests, but these seem to have lost the interest of their pushers, as change requests required for inclusion have gone unanswered. Let's see if I can make it to the end.

Some points: 
First: I'm not sure if I choose the right number for 'BOARD_ZRIB', I just picked the first following free, but it seems out of sequence with the rest of its brethren.
Second: First pull request, please be gentle, but I am standing by to amend any foul-ups  :)

### CODE REVIEW

**Comment by FATALHERMIT** [comment]
for my defense, i had midterms distracting me from the project,

why does your zmin use the zmax pin, also if you know the pin layouts of the other endstops pin you should configure them with #ifdef . 

the ZRIB board is used by most recent p802 chinese prusa i3 replica with various design variations from single extruder to double extruder. if i were to flash mine with this i would expect it to hit the heatbed since im not using the zmax pin

**Comment by ghost** [comment]
@FATALHERMIT No need to defend yourself, there is only so much time in a day, and midtems seem like a valid use of time :) I've used your patchset as a startingpoint. As for why the zmin/zmax thing, you are right, that is a valid setting for my setup, but as you said, there are many different setups for this board, I've yet to figure out how to make it so generic that it will work for everybody.

**Comment by FATALHERMIT** [comment]
the one im using right now is basically a modified version of the pins_RAMPS.h file i dont have it on this computer but i'll try remember to show it to you once i log onto my main computer

**Comment by fiveangle** [comment]
ZRIB support was added with 911079104e0b68b5189b1cd0372f15295b711b63

Shouldn't this be closed @Hertog99 ?

**Comment by ghost** [comment]
Yes, can be closed

**Pull request closed without merging**
