### PR TITLE
MKS LVGL UI: Fixed changed fan speed

### PR DESCRIPTION
**Pull request by Malderin**
### Description

Fixed changed fan speed. 
After https://github.com/MarlinFirmware/Marlin/pull/21544 found that fan speed "+" is not working

### Benefits

Fixed changed fan speed.

### CODE REVIEW

**Comment by thinkyhead** [comment]
What caused the "+" to not work? Seems a shame to revert all the improved code without ever knowing the cause.

**Comment by Malderin** [comment]
> What caused the "+" to not work? Seems a shame to revert all the improved code without ever knowing the cause.

The reason is not known to me, otherwise I would not offer such a solution.

**Comment by Malderin** [comment]
> What caused the "+" to not work? Seems a shame to revert all the improved code without ever knowing the cause.

Experimented a little. Seem to be:
```cpp
 uint8_t fanPercent = map(thermalManager.fan_speed[0], 0, 255, 0, 100);
```
it works incorrectly.
Replaced with
```cpp
uint8_t fanPercent = thermalManager.fanSpeedPercent(0);
```
Works well.
I also had to replace the line:
```cpp
sprintf_P(public_buf_l, PSTR("%s: %3d%%"), fan_menu.state, (int)map(thermalManager.fan_speed[0], 0, 255, 0, 100));
```
with line:
```cpp
sprintf_P(public_buf_l, PSTR("%s: %3d%%"), fan_menu.state, (int)thermalManager.fanSpeedPercent(0));
```
This is necessary to eliminate the discrepancy between the readings in the fan menu and the main screen. The map() function rounds off the value and therefore in the fan menu it shows, for example, 49% and on the main screen 50%.

**Comment by thinkyhead** [comment]
The rounding should tend to be downwards. Only an exact value of 255 should result in 100% and only an exact value of 100% should come out as 255.

**Comment by Malderin** [comment]
> The rounding should tend to be downwards. Only an exact value of 255 should result in 100% and only an exact value of 100% should come out as 255.

<details><summary>I tried to compile with the latest changes, it doesn't work.</summary>

```
Compiling .pio\build\mks_robin_nano35\src\src\HAL\STM32F1\SPI.cpp.o
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:54:0,
                 from Marlin\src\HAL\STM32F1\HAL.cpp:30:
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h: In function 'constexpr uint8_t percent_to_pwm(uint8_t)':
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h:80:65: error: 'i' was not declared in this scope
 constexpr uint8_t percent_to_pwm(const uint8_t p) { return (int(i) * 255) / 100; }
                                                                 ^
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:54:0,
                 from Marlin\src\HAL\STM32F1\HAL_SPI.cpp:32:
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h: In function 'constexpr uint8_t percent_to_pwm(uint8_t)':
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h:80:65: error: 'i' was not declared in this scope
 constexpr uint8_t percent_to_pwm(const uint8_t p) { return (int(i) * 255) / 100; }
                                                                 ^
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\HAL_SPI.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:54:0,
                 from Marlin\src\HAL\STM32F1\MarlinSerial.cpp:25:
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h: In function 'constexpr uint8_t percent_to_pwm(uint8_t)':
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h:80:65: error: 'i' was not declared in this scope
 constexpr uint8_t percent_to_pwm(const uint8_t p) { return (int(i) * 255) / 100; }
                                                                 ^
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\MarlinSerial.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32F1\../../inc/MarlinConfig.h:54:0,
                 from Marlin\src\HAL\STM32F1\SPI.cpp:43:
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h: In function 'constexpr uint8_t percent_to_pwm(uint8_t)':
Marlin\src\HAL\STM32F1\../../inc/../core/utility.h:80:65: error: 'i' was not declared in this scope
 constexpr uint8_t percent_to_pwm(const uint8_t p) { return (int(i) * 255) / 100; }
                                                                 ^
*** [.pio\build\mks_robin_nano35\src\src\HAL\STM32F1\SPI.cpp.o] Error 1
========================= [FAILED] Took 45.35 seconds =========================
 
Environment       Status    Duration
----------------  --------  ------------
mks_robin_nano35  FAILED    00:00:45.351
==================== 1 failed, 0 succeeded in 00:00:45.351 ====================
```
</details>

**Comment by Malderin** [comment]
> The rounding should tend to be downwards. Only an exact value of 255 should result in 100% and only an exact value of 100% should come out as 255.


After all the changes, the problem persists. In "+" the fan is not regulated, in "-" it is decreased by 2% per press.
And when you press fanPercent = 50, the fan turns on 49%.

**Comment by DmitryAranax** [comment]
You can try this:
Marlin/src/lcd/extui/lib/mks_ui/draw_fan.cpp in routine void event_handler:
replace 
    uint8_t fanPercent = map(thermalManager.fan_speed[0], 0, 255, 0, 100);
with
    uint8_t fanPercent = thermalManager.fanSpeedPercent(0);

replace
    thermalManager.set_fan_speed(0, map(fanPercent, 0, 100, 0, 255));
with 
    thermalManager.set_fan_speed(0, ((uint16_t)map(fanPercent, 0, 100, TERN(FAN_MIN_PWM, FAN_MIN_PWM, 0), TERN(FAN_MAX_PWM, FAN_MAX_PWM, 255))));

in routine void disp_fan_value() {
replace
    sprintf_P(public_buf_l, PSTR("%s: %3d%%"), fan_menu.state, (int)map(thermalManager.fan_speed[0], 0, 255, 0, 100));
with 
    sprintf_P(public_buf_l, PSTR("%s: %3d%%"), fan_menu.state, (int)thermalManager.fanSpeedPercent(0));

Works fine for me.

**Comment by Malderin** [comment]
@DmitryAranax 
In the latest version of the code, "uint8_t fanPercent = map(thermalManager.fan_speed[0], 0, 255, 0, 100);" is already missing and replaced as you suggest.
But the "thermalManager.set_fan_speed(0, ((uint16_t)map(fanPercent, 0, 100, TERN(FAN_MIN_PWM, FAN_MIN_PWM, 0), TERN(FAN_MAX_PWM, FAN_MAX_PWM, 255))));" design still works poorly for me, as I described here:
https://github.com/MarlinFirmware/Marlin/pull/21553#issuecomment-819565946

**Comment by Malderin** [comment]
@thinkyhead , I tested the latest changes, it looks like everything works fine!

**Pull request closed without merging**
