### PR TITLE
Adding a picture of a Marlin

### PR DESCRIPTION
**Pull request by WillHipschman**
It's a Marlin!

### CODE REVIEW

**Comment by Roxy-3D** [comment]
A Clown Fish?

**Comment by Jnesselr** [comment]
I told him about Marlin firmware. He made a joke about Marlin, who is apparently Nemo's dad from finding Nemo. Source: http://disney.wikia.com/wiki/Marlin

I was honestly surprised when he forked and did a full pull request. Also, @Roxy-3D I'm trying to find you on hangouts but I don't recall what your real name is.

**Comment by Roxy-3D** [comment]
OK!  That is funny.    But it would be real easy to take that joke the wrong way.   Especially if he had a bunch of contributions to Smoothieware or something like that!

I'm glad everybody is just having fun!

**Comment by Jnesselr** [comment]
Haha! Maybe Will will get a 3D printer and we can try to get him to be a firmware contributor. :) I mean, if Will has the will, he will do it.

**Pull request closed without merging**
