### PR TITLE
more speed for delta-printer

### PR DESCRIPTION
**Pull request by tonnico**
some good ideas from TESKAn
http://forums.reprap.org/read.php?147,515581

### CODE REVIEW

**Comment by MagoKimbra** [comment]
@Wurstnase I correct it but i do not understand the function...

```
FORCE_INLINE bool prepare_move_delta() {

    float difference[NUM_AXIS];
    float addDistance[NUM_AXIS];
    float fractions[NUM_AXIS];

    for (int8_t i = 0; i < NUM_AXIS; i++) difference[i] = destination[i] - current_position[i];

    float cartesian_mm = sqrt(sq(difference[X_AXIS]) + sq(difference[Y_AXIS]) + sq(difference[Z_AXIS]));
    if (cartesian_mm < 0.000001) { 
      cartesian_mm = abs(difference[E_AXIS]);
      if (cartesian_mm < 0.000001) return false;
    }

    /*
    from TESKAn: http://forums.reprap.org/read.php?147,515581

    float seconds = 6000 * cartesian_mm / feedrate / feedrate_multiplier;
    int steps = max(1, int(delta_segments_per_second * seconds));

    I had a particular problem with this piece of code. So we are using
    feedrate to calculate number of delta segments? This means that for
    different feed rates, we get different accuracy. For example, 1 mm
    at 20 mm/sec has 10 segments, at twice the speed 5 segments and 
    so on. So instead let's use segments per mm so we get some consistency.
    */

    float fTemp = cartesian_mm * 5;
    int steps = (int)fTemp;

    if (steps == 0) {
      steps = 1;
      for (int8_t i=0; i < NUM_AXIS; i++) fractions[i] = difference[i];
    }
    else {
      fTemp = 1 / float(steps);
      for (int8_t i=0; i < NUM_AXIS; i++) fractions[i] = difference[i] * fTemp;
    }

    // For number of steps, for each step add one fraction
    // First, set initial destination to current position
    for (int8_t i=0; i < NUM_AXIS; i++) addDistance[i] = 0.0;

    for (int s = 1; s <= steps; s++) {

      for (int8_t i=0; i < NUM_AXIS; i++) {
        addDistance[i] += fractions[i];
        destination[i] = current_position[i] + addDistance[i];
      }

      calculate_delta(destination);
      #ifdef ENABLE_AUTO_BED_LEVELING
        adjust_delta(destination);
      #endif

      plan_buffer_line(delta[X_AXIS], delta[Y_AXIS], delta[Z_AXIS], destination[E_AXIS], feedrate/60*feedrate_multiplier/100.0, active_extruder);
    }
    return true;
  }
```

**Comment by nophead** [comment]
Note the reason deltas have less segments per mm when running faster is because on 8 bit platforms there is a limit to how many delta calculations you can do per second. So I think the original code was correct in that respect.

**Comment by boelle** [comment]
the travis test failed on this one....

**Comment by tonnico** [comment]
@boelle Right, I shouldn't make a PR after a 36 hours travel with a night on an airplane -.-
@nophead also right, I will make a new PR with some extra options for testing.

**Comment by MagoKimbra** [comment]
Are there any typos, I corrected it and I posted. The version I put it right and I tried it.

**Comment by tonnico** [comment]
@MagoKimbra yes, I will fix this.
Also I will make the old 'per seconds' calculation as a standard and make an option for 'per mm'.

**Comment by MagoKimbra** [comment]
I tweaked so:

```
FORCE_INLINE bool prepare_move_delta() {

    float difference[NUM_AXIS];
    float addDistance[NUM_AXIS];
    float fractions[NUM_AXIS];
    float frfm = feedrate/60*feedrate_multiplier/100.0;

    for (int8_t i = 0; i < NUM_AXIS; i++) difference[i] = destination[i] - current_position[i];

    float cartesian_mm = sqrt(sq(difference[X_AXIS]) + sq(difference[Y_AXIS]) + sq(difference[Z_AXIS]));
    if (cartesian_mm < 0.000001) cartesian_mm = abs(difference[E_AXIS]);
    if (cartesian_mm < 0.000001) return false;

    #if defined(DELTA_SEGMENTS_PER_SECOND) || defined(SCARA_SEGMENTS_PER_SECOND)
      float seconds = 6000 * cartesian_mm / feedrate / feedrate_multiplier;
      int steps = max(1, int(delta_segments_per_second * seconds));
    #else
      float fTemp = cartesian_mm * 5;
      int steps = (int)fTemp;

      if (steps == 0) {
        steps = 1;
        for (int8_t i=0; i < NUM_AXIS; i++) fractions[i] = difference[i];
      }
      else {
        fTemp = 1 / float(steps);
        for (int8_t i=0; i < NUM_AXIS; i++) fractions[i] = difference[i] * fTemp;
      }

      // For number of steps, for each step add one fraction
      // First, set initial destination to current position
      for (int8_t i=0; i < NUM_AXIS; i++) addDistance[i] = 0.0;
    #endif

    for (int s = 1; s <= steps; s++) {

      #if defined(DELTA_SEGMENTS_PER_SECOND) || defined(SCARA_SEGMENTS_PER_SECOND)
        float fraction = float(s) / float(steps);
        for (int8_t i = 0; i < NUM_AXIS; i++)
          destination[i] = current_position[i] + difference[i] * fraction;
      #else
        for (int8_t i=0; i < NUM_AXIS; i++) {
          addDistance[i] += fractions[i];
          destination[i] = current_position[i] + addDistance[i];
        }
      #endif

      //calculate_delta(destination);
      delta[X_AXIS] = sqrt(delta_diagonal_rod_2
                         - sq(delta_tower1_x-destination[X_AXIS])
                         - sq(delta_tower1_y-destination[Y_AXIS])
                         ) + destination[Z_AXIS];
      delta[Y_AXIS] = sqrt(delta_diagonal_rod_2
                         - sq(delta_tower2_x-destination[X_AXIS])
                         - sq(delta_tower2_y-destination[Y_AXIS])
                         ) + destination[Z_AXIS];
      delta[Z_AXIS] = sqrt(delta_diagonal_rod_2
                         - sq(delta_tower3_x-destination[X_AXIS])
                         - sq(delta_tower3_y-destination[Y_AXIS])
                         ) + destination[Z_AXIS];

      //adjust_delta(destination);
      float grid_x = destination[X_AXIS] * AUTOLEVEL_GRID_MULTI;
      if (2.999 < grid_x) grid_x = 2.999;
      else if (-2.999 > grid_x) grid_x = -2.999;

      float grid_y = destination[Y_AXIS] * AUTOLEVEL_GRID_MULTI;
      if (2.999 < grid_y) grid_y = 2.999;
      else if (-2.999 > grid_y) grid_y = -2.999;

      int floor_x = floor(grid_x);
      int floor_y = floor(grid_y);
      float ratio_x = grid_x - floor_x;
      float ratio_y = grid_y - floor_y;
      float z1 = bed_level[floor_x+3][floor_y+3];
      float z2 = bed_level[floor_x+3][floor_y+4];
      float z3 = bed_level[floor_x+4][floor_y+3];
      float z4 = bed_level[floor_x+4][floor_y+4];
      float left = (1-ratio_y)*z1 + ratio_y*z2;
      float right = (1-ratio_y)*z3 + ratio_y*z4;
      float offset = (1-ratio_x)*left + ratio_x*right;

      delta[X_AXIS] += offset;
      delta[Y_AXIS] += offset;
      delta[Z_AXIS] += offset;

      plan_buffer_line(delta[X_AXIS], delta[Y_AXIS], delta[Z_AXIS], destination[E_AXIS], frfm, active_extruder);
    }
    return true;
  }
```

If in configuration.h comment #define DELTA_SEGMENTS_PER_SECOND 200 use new function segment per mm, otherwise use the old function segment per second...
@Wurstnase do you like it?

Edit: in `Conditionals.h` I put this:

```
#ifdef DELTA
  #define AUTOLEVEL_GRID_MULTI 1/AUTOLEVEL_GRID
#endif
```

**Comment by boelle** [comment]
still fails travis build

**Comment by tonnico** [comment]
@MagoKimbra yes, something like this. I will make an update this evening.
@boelle sure, I don't push any new stuff.

**Comment by boelle** [comment]
would it be to much trouble for you to rebase if of the latest dev? if that is ok with you then submit a new pr

**Comment by tonnico** [comment]
@boelle first i've make this working. Anyway, i used the latest dev.
My working:
1. make a PR
2. ask for any improvements
3. if the comments get messed
3.1 make a rebuild of the PR
3.2 close old PR
3.3 make a new PR

**Comment by boelle** [comment]
that is a plan :+1:

**Comment by giutrec** [comment]
I've same problem with arduino mega and full graphics lcd controller (over 100 segment per second) and normal lcd controller (over 140 segment per second) without lcd controller over 180 segment per second...

With Arduino due this problem looks over 800 segment per second (without any lcd) and over 300 segment per second with full graphics lcd controller.

Looks a bad print....
https://drive.google.com/file/d/0B6mn--RUVyiYMDd3dElOMzJJTUU/view?usp=sharing

**Comment by nophead** [comment]
Another point to note the amount of CPU time available to do the delta calculations goes down as the step rate increases due to the extra time spent in the step interrupts. So even a fixed number of segments per second is less than optimum at low speed.

This is worse with higher resolution drivers / motors, so they actually can give worse quality on Deltas at high speeds.

**Comment by tonnico** [comment]
Just to repeat it in my words/thinking. 
It should be better for the quality to have 'per mm' segments?
We could have a 'high speed' option with the old 'per second' and a 'high quality' option with 'per mm' segments?

**Comment by nophead** [comment]
If you have a fixed segments per mm then the speed should be capped so it that it can't exceed segments per second as it it just pauses when you hit that physical limit and makes blobs. I.e. you can't simply ignore the per second limit.

Put another way the segments per second limit always gives the best quality it can at the speed demanded. If you want higher quality than it gives you have to slow down, use faster code or a faster CPU, not simple change the code to segments per mm.

**Comment by tonnico** [comment]
Ok, got you. I have some additional ideas to improve the performance a bit.
I will cancel the 'per mm' idea as it is not that we want. Thanks for clarification.

**Comment by bkubicek** [comment]
no, the printer does not just stop when you have buffer underruns, it slows
down moves according to the buffer fill level. Its the so-called
Buffer-underrun prevention....

Bernhard

**Comment by nophead** [comment]
I have never used a delta but reports in the forums say it stutters when it runs out of CPU time as it full stops between segments because the planner doesn't see them soon enough to blend them.

I don't think it is the same as buffer underrun as the command buffer will be full but the planner queue empty.

**Comment by tonnico** [comment]
Buffer underrun dont work for segmentation moves. With that you have only the first step which runnin the underrun. The next steps will run again at normal speed. So you will see the rough moves.

**Comment by tonnico** [comment]
@AnHardt I could need your help. For more speed we should need to convert the feedrate_multiplier from int to float/100. With that we kill a lot of divisions.
Only for the display we need a value from 10 to 999. Anywhere else we need 0.1 to 9.99. Or the reciprocal of it.
I don't have a clue how to make this in the display part.
Could you please make this part for me and make a PR on my personal feedrate_devel?

**Comment by AnHardt** [comment]
@Wurstnase 
fanspeed is a pretty good example how to do it - 3 digits and a calculation.

**Comment by tonnico** [comment]
@AnHardt Thanks, i will check this.

**Comment by thinkyhead** [comment]
> If you have a fixed segments per mm then the speed should be capped so it that it can't exceed segments per second as it it just pauses when you hit that physical limit and makes blobs. I.e. you can't simply ignore the per second limit.

Is it better to just recommend to users to slow down their feed rate when stuttering happens, or should Marlin include extra code that notices when stuttering will happen and slows down its own feedrate automatically? Ultimately the end-user just wants the best possible results, so if Marlin can work around CPU bound limitations to smooth out its movement, I think that would be a welcome addition.

**Comment by nophead** [comment]
Segments per second is hard limit that can't be exceeded (presumably found by trial an error). Currently you specify the speed and get the highest number of segments it can calculate at that speed. I.e. highest quality possible for the speed requested. You could specify a minimum segment length as well and then cap the speed to achieve that but that might be more confusing and doesn't allow you to simply trade speed and quality by changing the speed.

**Comment by tonnico** [comment]
You could do some dynamical things by comparing OCR1A. But this could also lower the limit.

**Pull request closed without merging**
