### PR TITLE
Always run M500 after G29 on Ender3 V2

### PR DESCRIPTION
**Pull request by otioss**
### Description

Using the Auto Bed Leveling function in Ender 3 V2's menu, the mesh is not saved in EEPROM after the ABL finishes probing the bed. This can be quite confusing for the user. I always used the ABL function in Ender 3 V2 menu, assuming my mesh is saved in EEPROM and the mesh is used in my future prints. Recently I noticed that the ABL is not working as expected and when I checked the code here in dwin.cpp I realized the mesh is not saved. The only way to use the mesh in future prints is to separately do a [save settings] in the menu or issue a M500 separately. This is assuming the user knows the mesh is not saved, which is not obvious at all.  I propose we incorporate saving the mesh after probing as it is not clear to the user if the mesh is saved or not.

### Requirements

DWIN Display on Ender 3 V2 with 32-bit STM32 processor.

### Benefits

Users who are confused by strange behavior of ABL since they assumed by pressing 'Level the bed' in the main menu, the mesh is automatically saved and used in future prints.

### Configurations

None.

### CODE REVIEW

**Comment by CRCinAU** [comment]
This is about the only local patch I've been carrying a long time....

It should however be:
`queue.inject_P(PSTR("G28O\nG29\nM500"));`

If we're already homed, there's not much use in homing again. If the steppers disengage, then we become non-homed again and the G28 will run.

Now that I think about it though, we probably shouldn't do this - but only write the grid to the EEPROM and not every setting in the printer....

**Comment by thinkyhead** [comment]
> only write the grid to the EEPROM and not every setting

I agree. Before this can be merged we'll have to modify Marlin to do this for all leveling systems.

**Comment by otioss** [comment]
> > only write the grid to the EEPROM and not every setting
> 
> I agree. Before this can be merged we'll have to modify Marlin to do this for all leveling systems.

@thinkyhead @CRCinAU  Makes sense. I had a look at *::save* in *modules/settings.cpp*. I think we can make the following piece of code a separate function and design a new gcode command (for example, M505) to save the mesh:

```cpp
      #if ENABLED(MESH_BED_LEVELING)
        static_assert(
          sizeof(mbl.z_values) == (GRID_MAX_POINTS) * sizeof(mbl.z_values[0][0]),
          "MBL Z array is the wrong size."
        );
      #else
        dummyf = 0;
      #endif

      const uint8_t mesh_num_x = TERN(MESH_BED_LEVELING, GRID_MAX_POINTS_X, 3),
                    mesh_num_y = TERN(MESH_BED_LEVELING, GRID_MAX_POINTS_Y, 3);

      EEPROM_WRITE(TERN(MESH_BED_LEVELING, mbl.z_offset, dummyf));
      EEPROM_WRITE(mesh_num_x);
      EEPROM_WRITE(mesh_num_y);

      #if ENABLED(MESH_BED_LEVELING)
        EEPROM_WRITE(mbl.z_values);
      #else
        for (uint8_t q = mesh_num_x * mesh_num_y; q--;) EEPROM_WRITE(dummyf);
      #endif

```

What do you think? If this is the right course of action, please let me know and I will work on a patch.

**Comment by CRCinAU** [comment]
My preference (for the 0.02c its worth) would be to add an option to the G29 command which is then used with something like `parser.seen('W')` - then issuing a `G29 W` would write the results of the probe straight away... W seems to already be used, so maybe try and pick something unused...

It would also need to be wrapped in some `#if` conditions that make sure this only happens if we have a method to store the EEPROM data in the first place.

**Comment by otioss** [comment]
@CRCinAU maybe something like `G29 M` (M for Mesh)? Let's hear from @thinkyhead: Which one is better? `G29 M` or `M505` to save the mesh?

**Comment by thinkyhead** [comment]
You can leave it be. I can attend to the details in `settings.*` and take care of extending the G-codes. There's a major refactor of EEPROM code underway that will allow any setting to be updated without affecting others, so I want to ensure that the solution will fit with the new scheme, and apply it to all leveling systems.

**Comment by Roxy-3D** [comment]
If we are going to automatically save the mesh to EEPROM....    I wonder if we should take the position and document that the mesh is always saved to Mesh Slot #0 ?    There are a couple of reasons why this might make sense.   First, Mesh Slot #0 is always available.  The higher numbers are only available if there is enough EEPROM space.

Also, it might be beneficial to have a 'Temporary Mesh Slot #' area for different types of activities.   If Mesh Slot #0 is discouraged from normal user usage, perhaps the firmware can use it for future calibration type activities.    

And in this mind set,   even if the mesh is always saved to Slot #0, it is easy enough to load it and save it to what ever mesh slot the user really wants it stored.

**Pull request closed without merging**
