### PR TITLE
[2.0.x] CONCEPT - Allow Extruders = 0 and use E0 socket for dual X, Y , Z stepper

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
**CONCEPT - NEEDS DISCUSSION**

----

UPDATE 26 MAR
Reverted the Configuration.h file from NUM_EXRUDERS back to the current EXTRUDERS.  This keeps the user interface the same and allows the Travis tests to pass.

This required a change to **Conditionals_LCD.h** and a rewrite of this PR.

----

Inspired by Issue #10212 

This PR takes a minimalist approach to allowing users to set the number of extruders to zero and to use the E0 socket for dual X, Y or Z steppers.

The meat of this approach is to minimize code change by keeping the current EXTRUDERS value to a minimum of 1.  This is done by adding an EXTRUDERS == 0 section to **Conditionals_LCD.h**.

The EXTRUDERS == 0 section does the following:
1. Sets EXTRUDERS to 1.  This keeps EXTRUDERS to a minimum of 1 which keeps the current code happy.
2. Sets E_STEPPERS to 0.  This makes the E0 socket available for dual X, Y and Z steppers.
3. Ensure motion commands do not move the extruder.  This is done by enabling PREVENT_COLD_EXTRUSION and setting associated definitions.  Without this a G0 E10 command will cause the E0 socket to send steps.
4. Defines the NO_EXTRUDERS flag.

**stepper.cpp** is modified to disable setting extruder direction when NO_EXTRUDERS is defined.  If not done then the E0 socket's direction first gets set to the correct dual stepper direction but then gets set to the extruder direction.

This PR also strips the temperature and fan sections of the LCD status screens when NO_EXTRUDERS is defined.

**Do we need to strip the extruder and temperature items from the submenus?**

----

I'm sure there are other safeguards that could be added to Conditionals_LCD.h.  Just let me know & I'll add them.

----

The diffs are hard to read because I moved some sections around. 

The only code changes to stepper.cpp and the LCD files were the addition of **#ifndef NO_EXTRUDERS** clauses.

In Conditionals_LCD.h the only code change was the addition of the **#if EXTRUDERS == 0** section.  That section needed to appear in the file before the HOTEND section so that a valid value of EXTRUDERS was available to the HOTEND section.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Yeah...    Of course this makes sense.

**Comment by thinkyhead** [comment]
This has of course been attempted many times, and it's a good project for a long weekend. There are many, many places where code needs to be altered to handle `EXTRUDERS == 0`.

To make it easier to see progress, I've altered the Travis CI test so it only does a single build with `EXTRUDERS` set to 0 and the initial block of several options enabled.

Keep attempting to build using your own environment, and once you get a successful build with all the same options enabled in this PR's `.travis.yml`, then we can restore the original `.travis.yml` and see what other code still needs to be altered.

**Comment by thinkyhead** [comment]
This has of course been attempted many times, and it's a good project for a long weekend. There are many, many places where code needs to be altered to handle `EXTRUDERS == 0`.

See #9074, #9091 for two somewhat stale PRs which aim to accomplish the same thing. You may want to start with one of those since they already cover many —if not most— of the needed changes.

---
To make it easier to see progress, I've altered the Travis CI test so it only does a single build with `EXTRUDERS` set to 0 and the initial block of several options enabled.

Keep attempting to build using your own environment, and once you get a successful build with all the same options enabled in this PR's `.travis.yml`, then we can restore the original `.travis.yml` and see what other code still needs to be altered.

**Comment by thinkyhead** [comment]
Duplicate of #9091

**Pull request closed without merging**
