### PR TITLE
change "SD" to "Media"

### PR DESCRIPTION
**Pull request by robbycandra**
We use USB FlashDisk now. 

"SD Init Fail" appeared on the message when the USB fail.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I suppose "FD" is more clear than "USB" as some might think it has to do with the connected PC.

**Comment by robbycandra** [comment]
About "SD/USB" at es language, I just follow previous translation.

**Comment by trengtor** [comment]
> I suppose "FD" is more clear than "USB" as some might think it has to do with the connected PC.

Floppy Disk == FD

ps. Yes, I'm oldfag

**Comment by ellensp** [comment]
FD has another meaning with the 'kids' of today...  http://acronymsandslang.com/definition/5554090/FD-meaning.html

**Comment by robbycandra** [comment]
> FD has another meaning with the 'kids' of today... http://acronymsandslang.com/definition/5554090/FD-meaning.html

Seven Days / Full Day

**Comment by ellensp** [comment]
Basically FD is not clear in the slightest
In-fact I could not guess it till i read back. 
flashdisk? who calls it that? its a USB stick.

**Comment by thisiskeithb** [comment]
UDisk/U-Disk/U Disk is a lot more common, though it uses a few more characters.

**Comment by The-EG** [comment]
And here I was thinking it was 'file device' :laughing:

What was wrong with 'media,' other than not being 2 characters?

**Comment by cp2004** [comment]
Not sure I've ever seen it written as FD before

**Pull request merged**
