### PR TITLE
Update travis to test for ULTRA and DOG LCD options

### PR DESCRIPTION
**Pull request by jbrazio**
Yup, that's it.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Travis testing is now taking over 6 min with these additions. Not bad. But to reduce the duration of the test, we _could_ combine various options together, such as one LCD option plus one or more add-on features (that are compatible). I've done this already in a couple of spots.

**Comment by Blue-Marlin** [comment]
This is redundant and unneeded. The options are already tested with `REPRAP_DISCOUNT_SMART_CONTROLLER` and `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`.

**Comment by jbrazio** [comment]
@Blue-Marlin what's your name ? I prefer to treat people by their names.

Try in your clone of RCBugfix, on the default config, enable only the ULTRA LCD flag. What happens ?

**Comment by Blue-Marlin** [comment]
The same is if i define `REPRAP_DISCOUNT_SMART_CONTROLLER`. I get a error about `manage_manual_move()` not declared.
That means Travis is broken again - not we need an other test.

Call me Blue, or Marlin, or Makaira if you want. This account is anonymous by purpose. (Or ask Roxy or Thinky who i may am.)

**Comment by Blue-Marlin** [comment]
Interesting. Not in today's RCBugFix. There the error only occures with `ULTRA LCD`. ???

**Comment by jbrazio** [comment]
I searched and I don't find anything in the recent blame logs which influences this broken behavior with ULTRA LCD.

I found it out by coincidence when I was defining a Travis test for buzzer and speaker.

**Comment by Blue-Marlin** [comment]
The error makes sense.
`ULTRA_LCD` is the pure display with no buttons, encoders, ... only. (can display the status screen - nothing else)
For `manage_manual_move();` you need a gadget to move in the menus. therefore you need a panel.
`ULTIPANEL` is the base for all panels. So:

``` diff
void lcd_update() {
  #if ENABLED(ULTIPANEL)
    static millis_t return_to_status_ms = 0;
+   manage_manual_move();
  #endif

-  manage_manual_move();
```

**Comment by jbrazio** [comment]
Makes sense your explanation, thanks.
Will you submit that diff as a PR ?

**Comment by Blue-Marlin** [comment]
Sorry. No time for the next 8 -10 hours.

**Comment by thinkyhead** [comment]
> Call me Blue, or Marlin, or Makaira if you want. This account is anonymous by purpose. (Or ask Roxy or Thinky who i may am.)

And we'll tell you how we feel about it too.

**Pull request merged**
