### PR TITLE
Delta: DELTA_HEIGHT, G33 Auto-Calibrate, drop M206/M428, add M665 H

### PR DESCRIPTION
**Pull request by thinkyhead**
Rebase, squash, and adjustment to #6184.

 [(Concise diff)](https://github.com/MarlinFirmware/Marlin/pull/6187/files?w=1)

### CODE REVIEW

**Comment by tiagom62** [comment]
I look forward to this.

**Comment by aphex3k** [comment]
+1

**Comment by LVD-AC** [comment]
> Once I merge your PR into my branch, your new commits will be added to my PR at #6187 

Followed your instructions; did I do it correctly to make PR "Further cleaning thinkyhead/Marlin#24"?

**Comment by thinkyhead** [comment]
@LVD-AC I've brought in two commits from thinkyhead/Marlin#24 and patched that branch. You may want to re-checkout that branch (which has the current `RCBugFix` as its root) and continue from there.

```
git fetch thinkyhead
git checkout thinkyhead/rc_flsun_delta_autocal -b lvd_flsun_more_patches
```

**Comment by LVD-AC** [comment]
Looks OK (just updated some configs)

**Comment by thinkyhead** [comment]
@LVD-AC I've merged in your patches and made some additional changes (some of which are actually needed). Check to make sure everything is copacetic, and we can probably merge this soon.

**Comment by LVD-AC** [comment]
@thinkyhead I don't thing your last 673cb53 EEPROM patch for DELTA_AUTO_CALIBRATION is such a good idea; being able to set the delta height with M665 is not only useful when autocal is enabled but is even more useful for people calibrating manually. So I would leave the tests as it were with "ENABLED(DELTA)" and enable M665 H on all delta's as it was.

Should also change the instances in marlin_main and ultralcd of DISABLED(DELTA_AUTO_CALIBRATION) to DISABLED(DELTA) - My wrong

**Comment by LVD-AC** [comment]
One more bug (dotting the i's)

in the beginning of the G33 routine:

`      const int8_t pp = code_seen('C') ? code_value_int() : DELTA_CALIBRATION_DEFAULT_POINTS,`
instead of code_value_byte - it can be negative (-2)

**Comment by thinkyhead** [comment]
> being able to set the delta height with M665 is not only useful when autocal is enabled but is even more useful for people calibrating manually

The problem is that it piggybacks on `home_offset`, so what you're proposing is that we disable that feature for `DELTA` entirely and replace it with `M665 H`.

**Comment by LVD-AC** [comment]
Indeed. M206 and M428 are typical cartesian commands; like M666 and M665 are typical delta command. Home_offset only makes sense for the Z-axis on delta's anyhow - it adjusts the delta height; so that part is replaced with M665 H. XY home_offsets deform the perceived bed plane and should not be used on delta's; tower angle corrections are used instead to that effect.

**Comment by thinkyhead** [comment]
I'm with you, then.

But I'm looking for the most "friendly" way to have this work as its own thing in the `DELTA` case. Currently the EEPROM code is cautious to keep the storage size down. Options that apply only to `DELTA` aren't stored on a non-Delta, and options applying to Cartesian aren't stored on a Delta or `SCARA`… etc. It is simplest to leave `home_offset` as a three-element array, but we should try to recover the unused 8 bytes.

Meanwhile, it would also be more optimal, performance-wise, to replace the `home_offset` array altogether with a single `home_offset_z` for the `DELTA` case. I would replace direct access to `home_offset[axis]` with a macro, where `HOME_OFFSET(X)` and `HOME_OFFSET(Y)` both evaluate to a literal 0.0, while `HOME_OFFSET(Z)` evaluates to `home_offset_z`. The `M206 Z` command might remain as an alias to `M665 H`. Then `M428` and the LCD "Set Home Offset" menu option would also work.

Anyway, I will see what it entails to go the fully optimal route… If it's too much hassle then we can leave it as-is. If I can get this to work, then also `NO_WORKSPACE_OFFSETS` would be allowed, but it would apply only to `G92`.

**Comment by thinkyhead** [comment]
Ok, so the near-optimal solution still retains the `home_offset` array, but I modified the workspace offset macros to optimize the code throughout. Now `DELTA` can use `NO_WORKSPACE_OFFSETS` and it:
- Drops the `position_shift` array (reverting `G92` behavior), and
- Eliminates overhead for addition of `workspace_offset` to the X and Y axes

**Comment by LVD-AC** [comment]
@thinkyhead : So where do we go from here?

**Comment by thinkyhead** [comment]
@LVD-AC See if everything functions reasonably well, and if you have any additional tweaks to contribute please submit more PRs, as needed.

**Comment by LVD-AC** [comment]
Can you give me the git commands to get the branch with your latest commits into my desktop; I don't seem to be able to find it in order to test it. Still a bit lost in how GitHub works... And on what fork/branch should I be working on and towards what branch should I make further PR's?

**Comment by Bob-the-Kuhn** [comment]
Here's a Windows based write up on PRs for Marlin.  http://marlinfw.org/docs/development/getting_started_pull_requests.html

Ignore the security warning.

**Comment by LVD-AC** [comment]
I followed that guide but I got the old RCBugFix branch in my desktop; deleted everything in my desktop and in the GitHub dir on HD in order to start fresh over, followed the guide again but same result. I can't locate this PR or any of the commits in it. Really lost here...

**Comment by LVD-AC** [comment]
I don't know what I did differently, third time was a charm and worked; thanks...

**Comment by LVD-AC** [comment]
#6381 is this the way to do it?

**Comment by Bob-the-Kuhn** [comment]
Yes, the PR is correct.  Now you need to squash the commits down to one and resolve the conflicts.  That process is under the **Make the PR pretty & sync to main repository** section of the guide.

**Comment by oldmcg** [comment]
This commit added `DELTA_HEIGHT` to replace `MANUAL_Z_HOME_POS`, but `MANUAL_Z_HOME_POS` is now referenced by `#define Z_MAX_POS MANUAL_Z_HOME_POS` before it is defined to be `DELTA_HEIGHT` further down.

**Comment by thinkyhead** [comment]
> the branch with your latest commits into my desktop

Sorry, I've been very busy this week. For future reference, this is how it would be done via git:

First set up a remote and fetch my branches:
```cpp
git remote add thinkyhead git@github.com/thinkyhead/Marlin.git
git fetch thinkyhead
```
Then make a copy of the relevant branch:
```cpp
git checkout thinkyhead/rc_flsun_delta_autocal -b more_flsun_changes
```
Make your modifications, commit changes, then when you're ready to open a PR, just be sure to target `thinkyhead/rc_flsun_delta_autocal` as the destination.

**Comment by thinkyhead** [comment]
> This commit added `DELTA_HEIGHT` to replace `MANUAL_Z_HOME_POS`, but `MANUAL_Z_HOME_POS` is now referenced by `#define Z_MAX_POS MANUAL_Z_HOME_POS` before it is defined to be `DELTA_HEIGHT` further down.

That isn't a problem @oldmcg. In C++, preprocessor macros aren't evaluated until they are actually used in a code context, by which time all the required definitions for substitution will be in place.

**Comment by thinkyhead** [comment]
> "COMBINING ALL THE COMMITS INTO ONE MEANS YOU NO LONGER HAVE THE ABILITY TO REVERT THE NO LONGER EXISTING COMMITS."

@Bob-the-Kuhn Actually, you can recover any commits up until you `git gc`. Just use `git reflog` to find the commit that you want to resurrect, and…
```
git checkout 1454fb39d -b my_recovered_branch
```
Of course, it's also simple to make a copy of the branch before trying to mess with it (y'all!).
Then you can easily bring it back with:
```
git reset --hard my_backup_branch
```

**Comment by Whytehorse** [comment]
I was referred here from another bug. I'm trying to test this out on my delta. I noticed it says the changes have been merged into rcbugfix so I downloaded rcbugfix and I ran G33 but it does nothing. Is this a problem with my config or do I need to download a special branch? I just want to run the autocalibrate.

**Comment by LVD-AC** [comment]
`#define DELTA_AUTO_CALIBRATION` (G33 command) and #define `DELTA_CALIBRATION_MENU` (LCD menu) are commented out by default in the delta exemple configs (exept the Flsun/autocal one).

**Comment by Whytehorse** [comment]
That worked! It improved my autolevel results but I don't understand what's wrong. Here's the g29 results 
Bilinear Leveling Grid:
      0      1      2      3      4      5      6      7      8
 0 -0.566 -0.284 +0.053 -0.072 +0.001 +0.091 +0.246 +0.219 -0.007
 1 -0.316 -0.424 -0.242 -0.150 -0.081 +0.029 +0.120 -0.024 -0.123
 2 -0.284 -0.128 -0.120 -0.173 -0.061 -0.020 +0.054 -0.044 -0.134
 3 -0.340 -0.121 -0.142 -0.139 -0.030 +0.058 +0.042 -0.111 -0.197
 4 -0.188 -0.046 -0.111 -0.090 +0.001 +0.019 +0.019 +0.013 -0.128
 5 -0.069 -0.030 -0.050 -0.020 +0.040 +0.019 -0.004 +0.019 -0.158
 6 -0.035 +0.020 +0.110 +0.062 +0.148 +0.062 +0.090 +0.033 -0.030
 7 +0.130 +0.181 +0.059 +0.082 +0.048 +0.151 +0.136 +0.054 +0.046
 8 +0.278 +0.179 +0.073 +0.007 +0.011 +0.079 +0.027 +0.087 +0.095

Also does G33 save the tower corrections to EEPROM? How about G29? I don't understand how to get more accuracy. Is it G33 A0.01 ? Or do I need to add more points? 

How exactly do these commands work? It's really hard to find documentation...

**Pull request merged**
