### PR TITLE
Beautivy statusscreen

### PR DESCRIPTION
**Pull request by AnHardt**
by shifting things some pixels around.
Before:
picture 121

Then:
picture 122

### CODE REVIEW

**Comment by thinkyhead** [comment]
Very nice. I think my last merge (reducing the size of the menu functions) created a conflict. Should be easy to resolve.

**Comment by AnHardt** [comment]
@thinkyhead 
Saw this before and pulled directly from your branch.
Was there a special reason you did not touch "Y" in the last commit?

**Comment by thinkyhead** [comment]
@AnHardt No particular reason, just passed it over because of PSTR, but right, I see no reason not to change it.

**Comment by AnHardt** [comment]
@thinkyhead 
Yes. Was inconsistent before.

**Pull request merged**
