### PR TITLE
Fix UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in pos…

### PR DESCRIPTION
**Pull request by robbycandra**
Cannot Build on vscode. 
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 79940

SInce this PR : #21321

### CODE REVIEW

**Review by terrencegf — APPROVED** [review]
This fixed my compilation issue in VSCode. Thank you!

**Comment by sjasonsmith** [comment]
I suspect that this will fix some people and break others, depending on which text editors people use and which encodings they save their files in. We clearly have issues with this since things like degree symbols show up all the time in diffs as people switch back and forth between UTF-8 and OS-specific codepage tools.

That said, if we are going to put multi-byte characters in config files it makes sense to standardize on UTF-8 as you have done here.

If (and only if) assuming a UTF-8 encoding creates a bunch of new complaints then it might make sense to attempt UTF-8 first, then fall back to default encoding if it fails.

**Comment by robbycandra** [comment]
Hi. @sjasonsmith 
VSCode uses UTF-8 as a default encoding. 

image

I did not change my editor and Before PR:#21321 I can build without problems.

**Comment by sjasonsmith** [comment]
I reproduced the same thing. It appears to be breaking on this particular comment:

`//#define TOUCH_UI_UTF8_SCANDINAVIAN  // Æ Ð Ø Þ æ ð ø þ`

I didn't initially realize this was impacting everybody. I thought it was just impacting people who had added their own UTF-8 strings into the file.

**Comment by thisiskeithb** [comment]
> VSCode uses UTF-8 as a default encoding.

It’s the default encoding set in the `.editorconfig` file:

https://github.com/MarlinFirmware/Marlin/blob/5f9140cccd31f22897dfe135c681f0888b12e041/.editorconfig#L7-L8

**Pull request merged**
