### PR TITLE
Support for TMC drivers with internal rSense

### PR DESCRIPTION
**Pull request by alextrical**
### Description

"*_INTERNAL_RSENSE" Definition added to Configuration_adv to allow the use of internal rSense resistors on TMC drivers that support the feature. Required for control boards that don't use external sense resistors

### Requirements

A control board with no external Rsense resistor(s), and a TMC driver that has the internal_Rsense feature

### Benefits

Adds support for control boards that do not use external Rsense resistors, with Trinamic control chips that support the feature

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> control boards that do not use external Rsense resistors

Which boards support this feature? We could add a flag to the pins file + sanity check the config.

> with Trinamic control chips that support the feature

Which TMCs support this? A sanity check should be added to alert users of unsupported drivers (along with some form of checking the motherboard).

**Comment by alextrical** [comment]
> Which boards support this feature?

Well, I've just discovered that I was mistaken (and have been for a few months), the board I made this patch for has 2 external 0.11 Ohm resistors, resulting in no know boards currently requiring this PR. Please let me know if you would like me to close this PR.

> Which TMCs support this

Currently I have looked through all the manuals of the TMC drivers supported by Marlin. The drivers that support this feature are the following:
TMC2209
TMC2208
TMC2130
TMC5130

**Comment by thisiskeithb** [comment]
> Well, I've just discovered that I was mistaken (and have been for a few months), the board I made this patch for has 2 external 0.11 Ohm resistors, resulting in no know boards currently requiring this PR. Please let me know if you would like me to close this PR.

Since this feature isn’t implemented on any boards or drivers currently, I don’t think it makes sense to merge.

We can always resurrect the PR if/when an OEM rolls out the feature.

**Comment by teemuatlut** [comment]
> Since this feature isn’t implemented on any boards or drivers currently, I don’t think it makes sense to merge.
> 
> We can always resurrect the PR if/when an OEM rolls out the feature.

I would agree with this.

**Review by teemuatlut — COMMENTED** [review]
> Since this feature isn’t implemented on any boards or drivers currently, I don’t think it makes sense to merge.
> 
> We can always resurrect the PR if/when an OEM rolls out the feature.

I would agree with this.

**Comment by thisiskeithb** [comment]
Closing since this feature isn't needed at the present time. We can always resurrect the PR if/when an OEM implements it.

**Pull request closed without merging**
