### PR TITLE
[1.1.x] Polish language UTF8 

### PR DESCRIPTION
**Pull request by ArturNadolski**
Polish language in UTF8. It's based on English file so up-2-date
It has a lot more sentences translated then old version.
Need some "polishing" but it's good base to start.

### CODE REVIEW

**Comment by boelle** [comment]
you need to push to MarlinFirmware:bugfix-2.0.x instead

**Comment by thinkyhead** [comment]
@ArturNadolski —
If you could repair the broken encoding of `language_pl_utf8.h` then I won't mind merging this change.

**Comment by ArturNadolski** [comment]
My bad. I switched the files while uploading.

**Comment by boelle** [comment]
i changed the base to bugfix 2.0.x instead of bugfix 1.1.x

**Comment by tpruvot** [comment]
no, i think 1.1.x one was broken :p

**Comment by boelle** [comment]
> no, i think 1.1.x one was broken :p

yes but as i understand we only accept PR's to 2.0.x and not 1.1.x

**Comment by tpruvot** [comment]
i think all is utf8 in 2.x

**Comment by boelle** [comment]
yes but i still think PR's should be sent to bugfix 2.0.x and not 2.0

2.0 is just selected default if you dont make a selection

**Comment by boelle** [comment]
look at all other PR's they go to bugfix 2.0.x

**Comment by tpruvot** [comment]
the 2 is ok imo, its just the 1.1 branch file is not properly encoded as utf8

**Comment by ArturNadolski** [comment]
M1.1 is still used by many ppl and my update is for this version.
I will try to prepare update for M2.0 but later.

**Comment by boelle** [comment]
> M1.1 is still used by many ppl

but not updated anymore, 2.0.x is the way forward

**Comment by tpruvot** [comment]
hurry up, 2.0.1 is planned this evening... i think ;) passed the afternoon on french review

**Comment by boelle** [comment]
> hurry up, 2.0.1 is planned this evening... i think ;)

yep, that is what i read on discord, but let's see, there is a bit of timezone difference between europe and US of A

**Comment by boelle** [comment]
@ArturNadolski 

the consensus of the maintainers is that we aren't currently actively working on 1.x anymore, but anyone is still free to do so and submit a fix for a bug or even feature

so should this be changed back to 1.1.x ?

**Comment by ArturNadolski** [comment]
> @ArturNadolski
> 
> the consensus of the maintainers is that we aren't currently actively working on 1.x anymore, but anyone is still free to do so and submit a fix for a bug or even feature
> 
> so should this be changed back to 1.1.x ?

I didn't test it on 2.0 but I just take a look at source and there is Polish translation (I already commit file and pulled request some time ago). At 1.1 brach current Polish translation is very limited and there is no UTF8.
Please marge my files with 1.1 branch.

**Comment by boelle** [comment]
done and sorry for the confusion, is the polish in 2.0.x ok?

**Comment by ArturNadolski** [comment]
> done and sorry for the confusion, is the polish in 2.0.x ok?

I think so. Maybe not 100% complete but very close.

**Comment by GMagician** [comment]
@boelle 
This is what @thinkyhead said:

> If you could repair the broken encoding of language_pl_utf8.h then I won't mind merging this change.

He also change title to address specifically 1.1.x:

> Polish language UTF8 [1.1.x] Polish language UTF8

so he is aware that this was for 1.1.x. I suspect there is an issue on 1.1.x that he likes to be fixed.

Maybe this fix may be an exception applied to bugfix-1.x release

**Comment by thinkyhead** [comment]
> so he is aware that this was for 1.1.x. I suspect there is an issue on 1.1.x that he likes to be fixed.

Yes. I consider the lack of proper UTF8 support for Polish a "missing piece" in the 1.1.x tree, and this PR is an obvious patch to deal with that deficit. So it is exactly the kind of patch I am personally happy to accept for the `bugfix-1.1.x` branch.

*One less unwelcome surprise for Polish users of the 1.1.x patch pile.*

**In general:** Anything that fills in a"missing piece" and doesn't alter the feature-set or config methodology of 1.1.x is acceptable as a patch for the bugfix branch.

**Pull request merged**
