### PR TITLE
[1.1.x] Treat TMC2660 like non-TMC

### PR DESCRIPTION
**Pull request by thinkyhead**
TMC2660 may not be supportable at this time, so for now simply remove them from the `HAS_TRINAMIC` condition and treat them like other non-Trinamic stepper drivers.

Counterpart to #11508

### CODE REVIEW

**Comment by teemuatlut** [comment]
I think it would also be a good idea to modify the stealthchop and stallguard macros.
https://github.com/MarlinFirmware/Marlin/blob/f6ef58f3a7fadeab09e80a142fae2dbf437d0c89/Marlin/Conditionals_post.h#L733-L736

Just don't remove them as they will be expanded again.

**Comment by thinkyhead** [comment]
> I think it would also be a good idea to modify the stealthchop and stallguard macros.

How should they be modified?

**Comment by teemuatlut** [comment]
We can remove the references to `TMC2660` for now. They'll be added back once the time is right.

**Comment by thinkyhead** [comment]
Ah, ok. I see that `HAS_STALLGUARD` mentions 2660, but `HAS_STEALTHCHOP` doesn't.

**Pull request merged**
