### PR TITLE
Solves: #18547 POWER_MONITOR fails to compile

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

POWER_MONITOR_CURRENT and or POWER_MONITOR_VOLTAGE and EEPROM_SETTINGS 

### Description

Setting either of the above two option in Configuration_adv.h results in Marlin not compiling.
Basically the code was not marlin 2 compatible and seemed a little unfinished.
An additional issue was found when EEPROM_SETTINGS where enabled with these settings. 

### Benefits

Marlin compiles correctly if either or both POWER_MONITOR_CURRENT and POWER_MONITOR_VOLTAGE are enabled.

### Related Issues

Issue: https://github.com/MarlinFirmware/Marlin/issues/18547

### CODE REVIEW

**Comment by ellensp** [comment]
Lots of errors, none seem related to my code. Some sort of network error causing 502 errors.

**Comment by ccccmagicboy** [comment]
oops, need some more cleanup?

```
Compiling .pio\build\STM32F103RC_meeb\src\src\module\printcounter.cpp.o
Compiling .pio\build\STM32F103RC_meeb\src\src\module\probe.cpp.o
Marlin\src\module\configuration_store.cpp: In static member function 'static bool MarlinSettings::save()':
Marlin\src\module\configuration_store.cpp:883:46: error: 'power_monitor' was not declared in this scope
         const uint8_t &power_monitor_flags = power_monitor.flags;
                                              ^~~~~~~~~~~~~
Marlin\src\module\configuration_store.cpp:883:46: note: suggested alternative: 'power_monitor_flags'
         const uint8_t &power_monitor_flags = power_monitor.flags;
                                              ^~~~~~~~~~~~~
                                              power_monitor_flags
Marlin\src\module\configuration_store.cpp: In static member function 'static bool MarlinSettings::_load()':
Marlin\src\module\configuration_store.cpp:1746:42: error: 'power_monitor' was not declared in this scope
           uint8_t &power_monitor_flags = power_monitor.flags;
Compiling .pio\build\STM32F103RC_meeb\src\src\module\scara.cpp.o

Marlin\src\module\configuration_store.cpp:1746:42: note: suggested alternative: 'power_monitor_flags'
           uint8_t &power_monitor_flags = power_monitor.flags;
                                          ^~~~~~~~~~~~~
                                          power_monitor_flags
*** [.pio\build\STM32F103RC_meeb\src\src\module\configuration_store.cpp.o] Error 1
```

**Comment by ellensp** [comment]
himm, this is why tests are good. never thought about configuration_store or tried it...  looking

**Comment by ellensp** [comment]
@ccccmagicboy  Found it. Can you try again and confirm?

**Review by sjasonsmith — COMMENTED** [review]
It would be a good idea to add this feature to one of the existing test configurations, to prevent the compile from breaking again in the future.

**Comment by ccccmagicboy** [comment]
@ellensp compile is ok, but the current value needs to match my sensor.

**Pull request merged**
