### PR TITLE
Archim1 Platform.io windows fix.

### PR DESCRIPTION
**Pull request by V1EngineeringInc**
Adding this allows for a successful upload using a windows machine to an Archim1 board using Platform.io in VS Code.

### CODE REVIEW

**Comment by V1EngineeringInc** [comment]
This is related to this previous PR, #17405, for some reason that seemed to have worked then or I did not test it correctly.

**Comment by V1EngineeringInc** [comment]
Ultimachine came through with a stepper timing fix as well but it is a bit more involved and seemed like I should submit it as a separate PR. I am getting some more testers to run it before submitting.

**Comment by sjasonsmith** [comment]
> Ultimachine came through with a stepper timing fix as well but it is a bit more involved and seemed like I should submit it as a separate PR.

Is this currently in a branch you can point me to? I have reworked step timing in the past, and I'd like to see what type of change they have proposed.

**Comment by V1EngineeringInc** [comment]
Well yes and no. I am not all that good with git. Let me try to get my version live and I can share a link. 

I used Jason's previous fix, updated it, and then fixed the platformio.ini with this fix and a few little tweaks. It is, from what he told me' just a TC timing change, but it takes a whole board profile to make it work...above my pay grade. Here is the details and his repo link, https://forum.v1engineering.com/t/crashing-to-blank-lcd-screen-on-archim-board/20971/69?u=vicious1, and here is the test file, until I get the clean version ready for the PR. https://we.tl/t-XFwAJlPQU1

I hope this works for you, please let me know if you see anything that can be changed or if you understand this better maybe you should submit it?

**Comment by sjasonsmith** [comment]
> I hope this works for you, please let me know if you see anything that can be changed or if you understand this better maybe you should submit it?

I don't have any ability to test or debug Archim hardware. Those changes are not at the place in code I expected when you mentioned stepper timing fixes. I am quite surprised that the proper fix would be changing a constant which has been there for 9 years, I suspect that may be more of a workaround that hides the problem, but may have other unintended consequences (such as changing fan PWM rates).

I don't want to derail the topic of this PR though, so we should carry on any discussion elsewhere. I'm on Discord with the same username if you wanted to chat about it there.

**Comment by V1EngineeringInc** [comment]
From what I understand that is just a platform.io fix, this has nothing to do with the arduino side which no longer compiles due to long filenames (I think). 

My last firmware for the arduino side (427? Link if you want it) that still compiles has perfectly functioning steppers but for whatever reason randomly crashes minutes to many hours later. That one only compiles because Ultimachine has built the u8glib into their archim package to get around the long filename issue.

**Comment by V1EngineeringInc** [comment]
Cleaned up version, and a flash ready version of the TC timing(?) fix, https://github.com/V1EngineeringInc/Marlin/tree/Archim1_Pio_timing_fix, if you want to look. I have a confirmation if it working from another user, trying to get a few more.

**Pull request merged**
