### PR TITLE
Add missing translations for German

### PR DESCRIPTION
**Pull request by michos-conradt**
#3352

### CODE REVIEW

**Comment by thinkyhead** [comment]
Probably about as concise as we can get.

**Comment by CONSULitAS** [comment]
see #3431

there are duplicates. e.g. `#define MSG_HEATING_FAILED_LCD`: https://github.com/michos-conradt/Marlin/blob/f3a7a5c99b5768cf3b53902cad149a09d5661329/Marlin/language_de.h#L154

**Comment by thinkyhead** [comment]
Which strings do we prefer? The ones with "Err:" in front or the other (usually shorter) ones?

**Comment by CONSULitAS** [comment]
> The ones with "Err:" in front

it has to pop in your eye

**Comment by michos-conradt** [comment]
I would argue against "Err:" for two reasons:
- It takes valuable space without adding too much value. The descriptions IMO can be phrased such that it's clear something went wrong.
- If we really want to provide a German UI we should try to avoid keeping English terms in. Otherwise it kind of defeats the purpose of translations, right? If at all it should be "Fehler" or the like.

**Comment by thinkyhead** [comment]
I will defer to whatever works best for German users. The `Err:` prefix is not a standard, and the UI should be friendly.

**Pull request merged**
