### PR TITLE
Fix temperature min/max test

### PR DESCRIPTION
**Pull request by thinkyhead**
- Potentially fix issues mentioned at #1227 and #1654 
- Base tests on all thermistors/thermocouples, not just heater 0
- Replace `raw_temp_E_value` with `raw_temp_value[E]`

### CODE REVIEW

**Comment by AnHardt** [comment]
Hello @thinkyhead.
Time top say goodby to Arduino 1.0.6. This one fails to read out temperatures with the older version.
Works with Arduino 1.6.1.
The symptom is random temperatures even with the thermistors.

I suggest reverting this.

**Comment by thinkyhead** [comment]
@AnHardt Have you pinpointed this particular PR as the point where the thermistors & thermocouples start to act up? I'm not sure about the 1.0.6 connection to the problem at hand, since others have reported temperature issues with other versions of Arduino, including 0023. But perhaps I mistake your meaning…?

I have a new PR #1674 that cleans up this PR, but also messes with the reading routine, leading to more frequent polling. I gather that polling should only happen 1/6 of the time, based on the old code. I can _put that part aside_, merge the rest of #1674, and then roll a PR that does a further patch-up, reverting only what needs to be reverted if something specific to this PR can be pinpointed as the cause. I'm reluctant to outright revert, because this PR does address a real issue.

**Comment by AnHardt** [comment]
Yes. when this PR is applied, Arduino 1.0.6 fails to produce working code, while with 1.6.1 all is ok.

Produces a not changing random temperature.

Maybe making other changes will repair it. Try!

**Comment by thinkyhead** [comment]
Sorry to be a PITA, but I'm unable to flash my printer to test temperature code. I see only a couple of changes in this code that might make any difference. First, making `raw_temp_value` into an array, intended to make the code more agnostic about the number of extruders. I'm not sure how that might have a bad effect. **_But:**_ Here's a bug I find in the code, which would only affect you if using `TEMP_SENSOR_1_AS_REDUNDANT`.

```
static unsigned long raw_temp_value[EXTRUDERS] = { 0 };
```

should be

```
static unsigned long raw_temp_value[
  #ifdef TEMP_SENSOR_1_AS_REDUNDANT
    2
  #else 
    EXTRUDERS
  #endif
] = { 0 };
```

**Comment by AnHardt** [comment]
@thinkyhead 
I'll test this later. 8:00 UTC

**Comment by thinkyhead** [comment]
@AnHardt I added that change to #1674, plus the fix for MAX6675 that you found. I moved the code that checks the temperature out of `manage_heaters` and into the ISR along with the others, but I left the code that updates the MAX6675 temperature in `manage_heaters` so it will keep functioning as it should.

**Comment by AnHardt** [comment]
No, no, no, no. The the test cant be in the ISR. ISR starts to test much to early - when MAX is not ready and produces zeros - and the error is trown. Exactly this was the problem.

**Comment by AnHardt** [comment]
Situation is quite unchanged to yesterday. With actual Marlin (commit https://github.com/MarlinFirmware/Marlin/commit/512a0056a99bdb4a86774ef5298c3f514a670534)
Tempreature display is broken for Arduino 1.0.6.
MAX6675 MIN-MAX-test (still-again) broken.

Today i'll hunt with 1.0.6 - to find out whats going wrong.

**Comment by AnHardt** [comment]
Added a SERIAL_ECHO in the ISR.

```
@@ -1386,10 +1386,12 @@ ISR(TIMER0_COMPB_vect) {
       break;
    case MeasureTemp_0:
       #if HAS_TEMP_0
         raw_temp_value[0] += ADC;
       #endif

+  SERIAL_ECHO(raw_temp_value[0]);
+  SERIAL_ECHOLN("!");

     temp_state = PrepareTemp_BED;
     break;
     case PrepareTemp_BED:
     #if HAS_TEMP_BED
```

With 1.6.1 i get 16 times a increasing value - then it begins from start.

> 993!
> 1979!
> 2965!
> 3951!
> 4937!
> 5923!
> 6909!
> 7894!
> 8880!
> 9866!
> 10852!
> 11838!
> 12823!
> 13809!
> 14795!
> 15781!
> 986!
> 1972!
> 2958!

In 1.0.6
The row increases until a MAXERROR is thrown - then starts again

**Comment by AnHardt** [comment]
Some more serial output.
https://gist.github.com/AnHardt/fd15ac63687c7499adf1

**Comment by tonnico** [comment]
That rising part is just the oversampling. Collect 16 values and calculate the temperature. The interesting part is the sd-card error. 
#1634 is completely different.

**Comment by AnHardt** [comment]
@thinkyhead 
 The sd-card error is the normal one when no sd is in the slot.
Until this failure the main-loop is very busy and MAX6675 readings are 0 until then.
Or the other way around - when the sc-code has finished - the temperature readings begin.

More interesting is that with 1.0.6 near to infinite samples are taken.

**Comment by thinkyhead** [comment]
@AnHardt Well if it will be more safe to put the MAX6675 test right after the fetch, I will put it back. It just seems so much nicer when the test code is all in one cozy little place together.

**Comment by AnHardt** [comment]
@thinkyhead 
I'll try to explain again.
It's absolutely essential that the test is not performed before the sensor has a value. The sensor has a value when sc-code is over and the temperature readings begin. As you have seen the interrupt runs a good time before. When the test is in the interrupt it will fail.
The other possibility is to suspend the test in the interrupt until the sensor-values are ready - but this is even more complicated.

**Comment by AnHardt** [comment]
@thinkyhead 
I know this is a ugly one - but works with 1.0.6
https://gist.github.com/AnHardt/6956a69e2a29d6c23994

**Comment by AnHardt** [comment]
@thinkyhead 
All needed info is at hand now. Do You want to make the PR? Or do you want to mess up mine again. :-)

I think the variables i globalized in the last gist can be made static for a block surrounding the function and  the ISR.

{
static int xxx;
void function(){};
ISR(){};
}

**Comment by thinkyhead** [comment]
If that fix works, great, make a PR for it. I'm not sure about the name `minimaxtest`. It sounds like it would do a test.

**Comment by AnHardt** [comment]
As i said before - an ugly one. Shifted other parts of the code before but stayed with the functions name.
copy_raw_valuesISR() is my favorite name now.

**Comment by tonnico** [comment]
set_current_temp_raw() should be more clear. This is in a ISR but not a ISR.

**Comment by AnHardt** [comment]
#1689

**Comment by AnHardt** [comment]
By the way - i'm testing TEMP_SENSOR_1_AS_REDUNDANT

Displays shows temperature of sensor_0.
1. MAX_REDUNDANT_TEMP_SENSOR_DIFF -> statusline " Z" ->serial "Error:nt settings:". Looks like a progmem-string failure.
2. HEATER_0_MINTEMP triggered by TEMP_SENSOR_0 -> death display  -> serial ": Extruder switched off. MINTEMP triggered !"
3. HEATER_1_MINTEMP -> no effect.
4. HEATER_0_MAXTEMP triggered by TEMP_SENSOR_0 - death display -> serial ": Extruder switched off. MAXTEMP triggered !!"
5. HEATER_0_MAXTEMP triggered by TEMP_SENSOR_1 -> no effect.
6. HEATER_1_MAXTEMP -> no effect.

MAX_REDUNDANT_TEMP_SENSOR_DIFF repaid. Messages ok now.

Test are made with the sensors 999 and 998 so failurestate exists during boot-time.
Retested 4. with real sensor -> OK.
Retested 2. with real sensor -> OK.

Result:
Code for TEMP_SENSOR_1_AS_REDUNDANT is OK! (now)

Fix included in #1689.

**Comment by thinkyhead** [comment]
@AnHardt :beers:

**Comment by tonnico** [comment]
What is the difference between

```
function() { do something }
ISR { function() }
```

and

```
ISR { do something }
```

?

**Comment by AnHardt** [comment]
@Wurstnase 
Hopefully there is no functionally difference.
But Arduino 1.0.6 for some reason sees a difference and produces not working code without my change.
Fell free to test.
Or just trust my test at https://gist.github.com/AnHardt/fd15ac63687c7499adf1.

**Comment by thinkyhead** [comment]
It seems that something about the copious use of macros is annoying the compiler. These issues pop up occasionally, producing linker errors usually.

**Pull request merged**
