### PR TITLE
Bugfix-2.0.x my geeetech all in one configuration 

### PR DESCRIPTION
**Pull request by Vertabreak**
Description

This is my all in one configuration for almost all geeetech printers.
Benefits

simply integrated configurations for many printers from geeetech
Related Issues

i have been working on this for about a year and been using it for the same amount of time and nothing is perfect i made adjustments daily but i think its time to submit it.
i will update this from time to time from my fork if your cool with it.

### CODE REVIEW

**Comment by 3Dangel** [comment]
This is great deal! I’ve been using your build since Aug. 
you have saved me tons of time!!!
Again big thank you Vert!

**Comment by Vertabreak** [comment]
your welcome ^^

**Comment by thinkyhead** [comment]
For the purposes of this repo, it will be necessary to split these up into multiple configurations, otherwise they are not maintainable. Since someone has to maintain this configuration, it is best if you host it in your own fork of Marlin.

Note that in the near future we are migrating all custom configurations to a separate repository at [MarlinFirmware/Configurations](https://github.com/MarlinFirmware/Configurations).

**Comment by Vertabreak** [comment]
if any of it is usable in source by all means use it, just trying to give something back.

**Comment by boelle** [comment]
if you split it up in multiple configs we can use it

**Comment by Vertabreak** [comment]
the entire point of it being combined was to save me 100s of hours of time maintaining it and it is ever changing generally tweaked daily it would not be advantageous to me. ultimately the submission was done in attempt to silence the many trolls that demand i submit everything. in the end the configuration was intended only for my personal use and i have been forced in to sharing.

**Comment by boelle** [comment]
its more easy to maintain it here as seperate configs, but you decide

**Comment by Vertabreak** [comment]
it really isn't i make many tiny edits everyday that can effect up to all of the printers in the config.
the ideological differences prevent the submission the config is 100% compatible with source marlin this request has been closed.

**Pull request closed without merging**
