### PR TITLE
[2.0.x] Confirm Before Print SdFile

### PR DESCRIPTION
**Pull request by robbycandra**
### Requirements

Sometimes we choose wrong filename because the "Print form SD" screen lag or by mistake

### Description

This PR add Confirmation menu before printing

### Benefits

In the future. We also can do other function in this confirmation menu.
Like :
- Dimension Check
- Print Estimation Check.
- Display gcode Info
- Variable number of G29 mesh points according to the related file #10547
  ( in the https://github.com/MarlinFirmware/Marlin/milestone/55 )

I think this is very usefull

### CODE REVIEW

**Comment by robbycandra** [comment]
@thinkyhead , Later we can add many file related function in this Print file Confirmation subMenu. But we need to make this submenu first.

**Comment by thinkyhead** [comment]
This came up today, as this does tend to occur sometimes. The method used in this PR unravels the SD card menu item more than is probably needed. And I think the full name should be displayed all at once on this screen, if possible. We've been needing to make a "question, yes-no" screen for a while, so we might want to try implementing that for this use-case.

**Comment by robbycandra** [comment]
Hi @thinkyhead ,

In my own printer i use this format for confirmation sub menu:
-Line1 : Long FIlename, Static Scrolling
-Line2 : Menu Item : "Back"
-Line3 : Menu Item : "Print"

But the code I use is too long and maybe not good enough : 

```

void menu_confirm_sdfile() {
  ui.encoder_direction_menus();
  START_MENU();
  // Line1 : Long FIlename, Static Scrolling
  do{ 
    _skipStatic = true; 
    if (_menuLineNr == _thisItemNr) { 
      if (_skipStatic && encoderLine <= _thisItemNr) { 
        ui.encoderPosition += ENCODER_STEPS_PER_MENU_ITEM; 
        ++encoderLine; 
      } 
      if (ui.should_draw()) 
        //draw_menu_item_static(_lcdLineNr, PLABEL, ## __VA_ARGS__); 
        draw_sd_menu_static(true, _lcdLineNr, PSTR(MSG_CARD_MENU), card,false); 
    } 
    ++_thisItemNr; 
  } while(0);  

  MENU_BACK(MSG_BACK);

  // Line3 : Menu Item : "Print"
  do { 
    _skipStatic = false; 
    if (_menuLineNr == _thisItemNr) { 
      if (encoderLine == _thisItemNr && ui.use_click()) { 
        //_MENU_ITEM_MULTIPLIER_CHECK(USE_MULTIPLIER); 
        MenuItem_sdfile::action(card); 
        if (screen_changed) return; 
      } 
      if (ui.should_draw()) 
        draw_menu_item(encoderLine == _thisItemNr, _lcdLineNr, PSTR("Print"), '>', ' '); 
    } 
    ++_thisItemNr; 
  }while(0);
  END_MENU();
}
```

Should I commit this code ?

**Comment by thinkyhead** [comment]
I have an alternative that puts up a general confirmation screen, in which the entire filename is displayed without scrolling. This is preferred, since filename scrolling may not be enabled. The PR for this implementation is at… #13616

**Comment by camilorodas** [comment]
good night I am developing the same menu but it does not give me the results I want, first the function already defined by marlin to open the file and start printing error, this function is not more than the G code "M24" established in the function cardReader.cpp but when pressing my new option does not answer anything I need your help. Just like I want to print on the screen the name of the selected file. The caught implemented is:

 //This is where the selected file is activated

    void menu_action_sdfile(CardReader& theCard) {
      #if ENABLED(SD_REPRINT_LAST_SELECTED_FILE)
        last_sdfile_encoderPosition = encoderPosition;  // Save which file was selected for later use
      #endif
      lcd_goto_screen(confirm_menu); // go to new menu
         
    //  card.openAndPrintFile(theCard.filename);   comment old code
   // lcd_return_to_status();
   //  lcd_reset_status();
    }

 void cancelar_impresion() {
      
   card.autostart_index = 0;
   lcd_return_to_status();
    }


  void empezar_impresion(CardReader& theCard) {
      
   card.openAndPrintFile(theCard.filename);  run to archive 
    lcd_return_to_status();
     lcd_reset_status();
    }

    void  confirm_menu() {
     START_MENU();
     
     STATIC_ITEM("el archivo seleccionado es:" );
    //Here I want to print the name of the selected file help please!!!

     MENU_ITEM(function, MSG_CONFIRMSD,empezar_impresion );     
     MENU_ITEM(function, MSG_CANCELSD, cancelar_impresion);
 
  
    
      END_MENU();
   
   }

**Comment by robbycandra** [comment]
Latest version of marlin 2.0 already have SD Print Confirmation option which is better than this PR.

**Pull request closed without merging**
