### PR TITLE
Check for misplaced configs on build

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

PlatformIO

### Description

A common issue I see is new users copying example configuration files into the wrong place.
This adds a compile time check to common-dependencies.py that the user has not added config files into either the project root or the config subdirectory, instead of the Marlin subdirectory   

### Benefits

Stops users putting config files into the two most commonly used incorrect places.

### Related Issues

None

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I think this will prevent a lot of user error reports! Or at least make it easy to tell what it wrong when they ask about it.

I prefer the prints if you put the entire message in the exception text. That causes it all to be colored nice and red!
```
	if os.path.isfile(BAD_CONFIG_PATH_1) or os.path.isfile(BAD_CONFIG_ADV_PATH_1):
		err = 'ERROR: Config files found in directory ' + str(env['PROJECT_DIR']) + ' Please move them into the Marlin subdirectory.'
		raise SystemExit(err)
	if os.path.isfile(BAD_CONFIG_PATH_2) or os.path.isfile(BAD_CONFIG_ADV_PATH_2):
		err = 'ERROR: Config files found in directory ' + str(os.path.join(env['PROJECT_DIR'], 'config')) + ' Please move them into the Marlin subdirectory.'
		raise SystemExit(err)
```

image

**Comment by sjasonsmith** [comment]
Lol, we are interleaving our comments between here and Discord. You've already implemented my suggestion!

**Review by sjasonsmith — APPROVED** [review]
Works on Windows. @rhapsodyv said he could try it on Mac.

**Comment by ellensp** [comment]
Just had another one... they put the configuration files into the config directory...

**Comment by thinkyhead** [comment]
Thanks! Every bit helps….

**Pull request merged**
