### PR TITLE
Thermocouple ignore errors

### PR DESCRIPTION
**Pull request by chepo92**
### Description

This adds an option in config_adv to disable the behaviour of killing the printer if a thermocouple (TC) is willingly disconnected, as with a normal thermistor shows -14 or -27 degrees when it is failed or disconnected, and it doesn't trigger a printer kill. This is mostly intended for developing and debugging 

### Benefits
You can test a board that uses thermocouples without the need to have the TC always connected, so the board/printer can live without it 

I needed this option as one MAX6675 had a short to 24v, the IC logic part did survive but its inputs where dead so reading random ADC stuff an I was getting MAX temp error and TC failure, but I was unable to debug as it was instantly killed after boot. 

### Related Issues
None that I have read of

### CODE REVIEW

**Comment by thinkyhead** [comment]
I've moved the option to `temperature.cpp` because it's _that kind of option_.

**Comment by AnHardt** [comment]
Wouldn't have using `BOGUS_TEMPERATURE_GRACE_PERIOD`, or an extension on that for the SPI-temp-sensors, had the same effect for debugging, without enabling the faulty system for ever. 

@thinkyhead 
Please give others a chance to review PRs if not a emergency fix. Merging 3h after appearance is not enough time to have a look (i'm sleeping longer). Especially if you changed a PR give the original author and others at least some more time (24h ?) to look at that. Better would be a rule for not merging your own stuff, to get a second perspective, but for that we don't have enough regular reviewers able and allowed to merge.

**Comment by chepo92** [comment]
Yeah that was kind of fast merging I didn't expect haha

@thinkyhead 
I don't think moving the option to temperature.cpp is a good idea as it is more difficult to find for someone not familiar with the file tree, also i don't see more user configurable options in that file, IMHO, and for the sake of simplicity, all user options should come from the config and config_adv only (as in other firmwares, e.g RRF "only one file to rule everything"), I also put it in config_adv and not config as is something very uncommon to use and is somehow related to thermal protecion section. What do you think?

**Comment by thinkyhead** [comment]
> Please give others a chance to review PRs if not a emergency fix.

I agree that it's a bad idea to expose to general users, so I made it innocuous by moving the option to an obscure (to most) location.

**Pull request merged**
