### PR TITLE
add G38.2 & G38.3 commands to Marlin (issue 4677)

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
It would be nice to add G38.2 & G38.3 commands to Marlin.

This is low priority since it would be primarily used by people using Marlin to run their CNC machines.

See issue #4677 for a discussion on this topic.

Attached are the three files I modified.  The G38 mods are delineated by "G38_2_3" .  These are the same as I uploaded to issue 4677.

  Bob

[Marlin_G38.zip](https://github.com/MarlinFirmware/Marlin/files/470353/Marlin_G38.zip)

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Looks like this pull request may be premature.  I've only tested it against 1.0.2.

I'll add another comment when I've tested it against the latest bug fix branch.

The testing I've done so far has been on 1.0.2 using an AzteegX3pro controller using a probe wired in parallel with the Z_MIN endstop.

**Comment by Bob-the-Kuhn** [comment]
I definitely did this pull request too soon.  Once I figured out how to use the GitHub desktop tool and have tested it using the RCbugfix branch I'll do another pull request.

   Bob

**Comment by thinkyhead** [comment]
You must apply the changes to `RCBugFix` and submit your PR against `RCBugFix`. Be sure to do your work in a new branch that is not named `RCBugFix`.

**Comment by Bob-the-Kuhn** [comment]
Will do

I’ve been wondering around within RCBugFix.  Converting 1.0.2 code to run in the new code base in non-trivial. I see why you weren’t enthusiastic.

**Pull request closed without merging**
