### PR TITLE
Upgrade BigTrees to latest platform ststm32

### LINKED ISSUE #14672: [BUG] BigTreeTech SKR Pro - Broken compilation with new ststm32@5.5.0
platformio.ini
```
[env:BIGTREE_SKR_PRO]
#platform = ststm32
platform = ststm32@5.4.3

```

### PR DESCRIPTION
**Pull request by basilfx**
### Description

Upgrade the `ststm32` platform to the latest version (version 5.6) by making the custom variant of the PlatformIO compatible. I think the other variants can also benefit from this, but I don't own these boards to test.

### Benefits

With this PR, we don't have to pin to an older version of the `ststm32` platform anymore. It is also necessary to make Neopixels work on my board and configuration (with #15274 applied, but without this patch, it boot-loops).

### Related Issues

Fixes #14672. Required for #15274 on the SKR Pro v1.1.

### CODE REVIEW

**Comment by basilfx** [comment]
Variant changes are based on https://github.com/stm32duino/Arduino_Core_STM32/tree/master/variants/BLACK_F407XX. The board definition is based on https://github.com/platformio/platform-ststm32/blob/develop/boards/black_f407vg.json.

**Comment by thinkyhead** [comment]
Great! Anything that moves STM32 forward is most welcome.

**Comment by thinkyhead** [comment]
Looks like there are some bugs in the platform itself…

`BIGTREE_GENERIC_STM32F407_5X/variant.cpp`

```
In file included from /home/travis/.platformio/packages/framework-arduinoststm32/variants/BIGTREE_GENERIC_STM32F407_5X/variant.cpp:31:0:
/home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/pins_arduino.h:24:15: error: expected constructor, destructor, or type conversion before '(' token
 _Static_assert(LastPort <= 0x0F, "PortName must be less than 16");
               ^
/home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/pins_arduino.h:53:15: error: expected constructor, destructor, or type conversion before '(' token
 _Static_assert(NUM_ANALOG_INPUTS <= MAX_ANALOG_INPUTS,
               ^
/home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/pins_arduino.h:55:15: error: expected constructor, destructor, or type conversion before '(' token
 _Static_assert(NUM_ANALOG_FIRST >= NUM_ANALOG_INPUTS,
               ^
/home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/pins_arduino.h:63:14: error: 'uint8_t' does not name a type
 static const uint8_t A0 = PIN_A0;
              ^~~~~~~
/home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/pins_arduino.h:67:14: error: 'uint8_t' does not name a type
 static const uint8_t A1 = PIN_A1;
              ^~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio/build/BIGTREE_BTT002/FrameworkArduinoVariant/variant.cpp.o] Error 1
In file included from /home/travis/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F4xx/Include/stm32f4xx.h:250:0,
                 from /home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/stm32_def.h:16,
                 from /home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/stm32/clock.h:43,
                 from /home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_time.h:23,
                 from /home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring.h:38,
                 from /home/travis/.platformio/packages/framework-arduinoststm32/cores/arduino/Arduino.h:32,
                 from /home/travis/.platformio/packages/framework-arduinoststm32/variants/BIGTREE_GENERIC_STM32F407_5X/PeripheralPins.c:31:
/home/travis/.platformio/packages/framework-arduinoststm32/system/Drivers/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h:46:10: fatal error: stm32f4xx_hal_conf.h: No such file or directory
```

**Comment by tpruvot** [comment]
its broken on another machine, not updated... both need the new ststm32 version in platformio.ini (almost same 407) BIGTREE_BTT002, they share the same board file

**Comment by basilfx** [comment]
@thinkyhead @tpruvot Can you remove the variant in `~/.platformio/packages/framework-arduinoststm32/variants/BIGTREE_GENERIC_STM32F407_5X` and try again? 

The `buildroot/share/PlatformIO/scripts/generic_create_variant.py` script syncs all files from the `buildroot/share/PlatformIO/variants` folder, but doesn't remove any files already there. I think the `stm32f4xx_hal_conf.h` that is not removed, is the conflicting file.

I just double-checked this on a blank Ubuntu 18.04 machine, installed PlatformIO, checked out this branch and compiled it with [this configuration](https://gist.github.com/basilfx/6bd7c4f0109f0481b9f653a8e8fd0d70).

image

**Comment by tpruvot** [comment]
just set that to same version, travis issue is not on the skr pro 
https://github.com/MarlinFirmware/Marlin/blob/ea60d26681fdd64c5cc77bee61929e2545a5e0a1/platformio.ini#L482-L483

**Comment by basilfx** [comment]
@tpruvot Ah, now I understand! Pushed a fix!

**Comment by basilfx** [comment]
I'm also wondering if we could remove the MARLIN_F407VE variant, and replace it by the BLACK_F407XX variant in the ststm32 platform. Then all platforms can go to latest ststm32.

**Comment by tpruvot** [comment]
[env:STM32F407VE_black]
platform = ststm32@5.4.3

if it works with latest ststm32, do it, didnt try

**Comment by tpruvot** [comment]
else for the BIGTREE_BTT002 407VE board file... maybe let users owning it test it first...

**Comment by basilfx** [comment]
Travis is happy now (apart from a problem with DUE that seems unrelated).

I'm 99% confident that the `BIGTREE_BTT002` will work, since it uses the same pin mapping as the `BIGTREE_SKR_PRO`. I don't know any users of that board.

I'll keep `STM32F407VE_black` out of this PR.

**Comment by tpruvot** [comment]
yep, push the commit to show what is changed...

**Comment by basilfx** [comment]
Ah, I was just a few minutes too late to add some additional fixes. Will open another PR to cleanup a few things! Thanks for merging this one already!

**Pull request merged**
