### PR TITLE
M111/M115 Followup

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
Follow up to  
-🔧 CONFIGURE_FILAMENT_CHANGE - Optional M603 (#26613)
-🔪 Options to slim M111, remove M115 (#26603)

with Filament Load and Unload changed so `ENABLED(CONFIGURE_FILAMENT_CHANGE)`,  
functions `setFilLoad` and `setFilUnload` need to be as well.

its currently `ADVANCED_PAUSE_FEATURE`, this **PR** corrects that.

<br>

also,  
with the new `REPORT_CAPABILITIES_GCODE`, I replaced with less wordy `REPORT_CAPABILITIES` and rearrange `@section reporting` **Configuration_adv.h**

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> also,
with the new REPORT_CAPABILITIES_GCODE, I replaced with less wordy REPORT_CAPABILITIES and rearrange @section reporting Configuration_adv.h

Why?

**Comment by classicrocker883** [comment]
> > also,
> > with the new REPORT_CAPABILITIES_GCODE, I replaced with less wordy REPORT_CAPABILITIES and rearrange @section reporting Configuration_adv.h
> 
> Why?

is it not better that way?

**Comment by thisiskeithb** [comment]
> is it not better that way?

It's a lot of config churn with no real benefit. Also, `REPORT_CAPABILITIES_GCODE` describes what it is & is not "wordy".

**Comment by classicrocker883** [comment]
> > is it not better that way?
> 
> It's a lot of config churn with no real benefit. Also, `REPORT_CAPABILITIES_GCODE` describes what it is & is not "wordy".

Occam's razor... K.I.S.S....

**Comment by thinkyhead** [comment]
Thanks for the followup! In addition to things like this, there are also pressing issues, reported bugs, and incomplete PRs that could use more attention. Please consider attending to some of those if you're down to dig into some of the more interesting problems, as it will contribute to lessening our endless workload.

**Pull request merged**
