### PR TITLE
(2.0.x) serious bug G33

### PR DESCRIPTION
**Pull request by LVD-AC**

### CODE REVIEW

**Comment by LVD-AC** [comment]
Fix for issue #8124

**Comment by cdedwards** [comment]
This fixed G33 for me. Thanks.

**Comment by Roxy-3D** [comment]
> This fixed G33 for me. Thanks.

Good news!!!

@lvd-ac    Is there any chance you can do a similar Pull Request for bugfix-v1.1.x ?   I think this problem exists in both branches.

**Comment by cdedwards** [comment]
#8137 addresses 1.1

**Pull request merged**
