### PR TITLE
danish up to date 14/8-16

### PR DESCRIPTION
**Pull request by boelle**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Please only make PRs against `RCBugFix`. Please remove all `#ifdef` blocks around definitions. Only the default language file (`language_en.h`) should have those.

**Comment by boelle** [comment]
it was against bugfix.... but oh well... will update when time allows...

please add note to english about the #ifdef so others will know

**Comment by boelle** [comment]
also i need explanation on line 574

#else

what about that section?

**Comment by Blue-Marlin** [comment]
This `#else` is related to `#if LCD_WIDTH > 19`.
If all your Danish text, in that section, is shorter than 16 chars you may omit dividing in cases.

**Comment by thinkyhead** [comment]
> it was against bugfix.... but oh well... 

I don't think so:

```
boelle  wants to merge 2 commits into MarlinFirmware:RC from unknown repository
```

You must specifically choose `RCBugFix` as the target when creating the PR, or it defaults to the default branch, which is `RC`.

**Pull request closed without merging**
