### PR TITLE
Update features.ini

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
-~~Fill-in missing features gcode.cpp~~
-Fix wrong source
```diff
-OTA_FIRMWARE_UPDATE                    = build_src_filter=+<src/gcode/feature/ota>
+OTA_FIRMWARE_UPDATE                    = build_src_filter=+<src/gcode/ota/M936.cpp>
```
I'm actually curious why some files are named this way:
`M360-M364.cpp`  
`M350_M351.cpp`

some are named with `-` and some with `_`. is that on purpose or is supposed to be one or the other?

I am not sure why these ".cpp" were missing, if it matters or not.

### CODE REVIEW

**Comment by ellensp** [comment]
you dont need to explicitly define the .cpp files if the directory is enough, it will use all .cpp files in that directory.

**Comment by thisiskeithb** [comment]
> you dont need to explicitly define the .cpp files if the directory is enough, it will use all .cpp files in that directory.

Indeed. Most of these changes can be reverted since the folder exclusion is enough / more future-proof.

**Comment by sjasonsmith** [comment]
> M360-M364.cpp
M350_M351.cpp
>
> some are named with - and some with _. is that on purpose or is supposed to be one or the other?
>
> I am not sure why these ".cpp" were missing, if it matters or not.

M360-M364 contained a range of codes: everything from M360 __through__ M364.

M350_M351 just contains two. M350 __and__ M351. Admittedly M350-M351 is also a range, but this is how I interpret it.

**Comment by sjasonsmith** [comment]
@classicrocker883 factoring in the comments from @ellensp and @thisiskeithb, I don't see anything here that we would want to commit.

Is this PR actually fixing broken behavior in any way? If yes, please describe it.

**Comment by ellensp** [comment]
The first post correctly says that OTA_FIRMWARE_UPDATE path is incorrect

In bugfix it is set to

OTA_FIRMWARE_UPDATE                    = build_src_filter=+<src/gcode/feature/ota>

but it should be

OTA_FIRMWARE_UPDATE                    = build_src_filter=+<src/gcode/ota>

ota in not under feature, https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.1.x/Marlin/src/gcode/ota

**Comment by sjasonsmith** [comment]
Thanks @ellensp, I was distracted by all the other changes and didn't see that in diff (because that line moved as well as being changed). I simply overlooked it in the description as I was reading the comments.

@classicrocker883, please revert all the changes here except the change that actually fixes the issue.

**Comment by classicrocker883** [comment]
it is done

**Pull request merged**
