### PR TITLE
Message for every KILL and STOP

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
No more mystery halts & resets

### CODE REVIEW

**Comment by psavva** [comment]
Bob-the-Kuhn, this is something that will help everyone.

**Comment by CONSULitAS** [comment]
transfering the strings to ```language.h``` in ```section // Serial Console Messages (do not translate those!)``` would be great

**Comment by Bob-the-Kuhn** [comment]
Yes, I can move the strings.

Any suggestions on the wording?

I need to double check the one's for the unhomed error.  I know that at G29 will throw an error but it doesn't shut down the printer.  I need to make sure I'm not solving a non-existent problem.

**Comment by Bob-the-Kuhn** [comment]
I've just moved the messages into Language.h

I also print out the last command when the KILL is caused by the inactivity timer.

**Pull request merged**
