### PR TITLE
Automatic versioning for Travis builds

### PR DESCRIPTION
**Pull request by Wackerbarth**
This activates automatic versioning on the Travis CI builds.

Automatic versioning now works on both Mac OS X and Linux.

### CODE REVIEW

**Comment by fmalpartida** [comment]
Ohhh, yes! Nice one.

**Comment by AnHardt** [comment]
@Wackerbarth 
Could you please give us a short description here, how to setup this (again) - or a link.

**Comment by Wackerbarth** [comment]
There are two parts to using this compilation feature.
The first is setting things up to activate the hook script which generates the versioning header.
The second is repository management so that a script can generate an appropriate version number directly from the structure of the repository and without requiring the contents of the repository to be edited.

Here, I will address the first point. If nothing else, using this feature with the included script will generate a unique identifier that references the latest commit in the git repository. That identifier is displayed in the M115 response.

**Installation of the Arduino Build Structure**
I will start by assuming that you have already set up an Arduino environment and that this repository is cloned into the folder within the Sketchbook.

The steps utilized by the Travis CI process show all of the details.
1. Set up and install the hook script in the command path.

```
before_install:
  - mkdir ~/bin
install:
  - mv LinuxAddons/bin/*  ~/bin/
```

In particular, this installs a script `generate_version_header_for_marlin` which will be used later.
_Note: I use a link instead so that any change to the script gets updated automatically. YMMV_ 

**Building a Firmware Image**
2. Checkout the source that you wish to compile.
`git checkout ....`
_Note: It is important that you have pushed this EXACT configuration to a git repository.
The script assumes that it is on github.com. If you place it elsewhere, then alter the script appropriately._
1. Generate the Version header

```
  # change back to home directory for compiling
  - cd $TRAVIS_BUILD_DIR
  - generate_version_header_for_marlin . Marlin/_Version.h
```
1. Activate the correct configuration for the build, for example:

```
  # Delta Config (Mini Kossel)
  - cp Marlin/example_configurations/delta/kossel_mini/Configuration* Marlin/
```
1. Execute the compiler tool, specifying the compiler flag **-DHAS_AUTOMATIC_VERSIONING**

```
  - ino build -m mega2560 --cppflags="-DHAS_AUTOMATIC_VERSIONING -ffunction-sections -fdata-sections -g -Os -w"
```

If you are using the Arduino IDE (version 1.6.3 or later), you can perform steps 3 and 5 automatically by placing code such as the the following, but customized to match your actual installation, in your `platform.local.txt`

```
compiler.cpp.extra_flags=-DHAS_AUTOMATIC_VERSIONING
recipe.hooks.prebuild.pattern=/usr/local/bin/generate_version_header_for_marlin {build.source.path} {build.path}/_Version.h
```

**Distributing Source Archives**
Although I highly recommend that you utilize a public git repository to publish sources, if you intend to distribute the source in the form of an archive, you need to transfer the contents of the generated _Version.h to the Marlin/Default_Version.h file that you distribute so that future builds from this source will reflect the proper references to the version of the source files.

Note that the build date does not reflect the version of source. I can rebuild from some ancient source today. But it will not include any of the recent changes.

**Enjoy**

**Comment by thinkyhead** [comment]
It is all becoming clear… I will add documentation about this to the developers section of the Marlin Firmware wiki soon. I want to make a page giving a general overview of Marlin development, including a whole page on versioning that can be a guide for vendors and others making customized firmware. Your post @Wackerbarth would be very helpful as the basis for that page, if I may copy from it…?

**Comment by Wackerbarth** [comment]
Certainly. That was the exact purpose of my post. 
I've never been a good "technical writer" and am happy to have someone reword things in a manner that is more understandable to someone who is not intimately familiar with the design and code.

**Pull request merged**
