### PR TITLE
Auto-save MBL to eeprom

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
Storing all settings without warning seem not to be a good idea to me.
How about only storing the MBL related things?
If you alter one Configuration.h you have to do it for all (in 'example_configurations').

**Comment by ghost** [comment]
Ok, I am fine with it, but how would I store just the mesh?

**Comment by AnHardt** [comment]
> but how would I store just the mesh?

@Tannoo 
Are you familiar to the concept of functions?
'Divide et impera'!
```
    //
    // Mesh Bed Leveling
    //

    #if ENABLED(MESH_BED_LEVELING)
      // Compile time test that sizeof(mbl.z_values) is as expected
      typedef char c_assert[(sizeof(mbl.z_values) == (MESH_NUM_X_POINTS) * (MESH_NUM_Y_POINTS) * sizeof(dummy)) ? 1 : -1];
      const bool leveling_is_on = TEST(mbl.status, MBL_STATUS_HAS_MESH_BIT);
      const uint8_t mesh_num_x = MESH_NUM_X_POINTS, mesh_num_y = MESH_NUM_Y_POINTS;
      EEPROM_WRITE(leveling_is_on);
      EEPROM_WRITE(mbl.z_offset);
      EEPROM_WRITE(mesh_num_x);
      EEPROM_WRITE(mesh_num_y);
      EEPROM_WRITE(mbl.z_values);
    #else
      // For disabled MBL write a default mesh
      const bool leveling_is_on = false;
      dummy = 0.0f;
      const uint8_t mesh_num_x = 3, mesh_num_y = 3;
      EEPROM_WRITE(leveling_is_on);
      EEPROM_WRITE(dummy); // z_offset
      EEPROM_WRITE(mesh_num_x);
      EEPROM_WRITE(mesh_num_y);
      for (uint8_t q = mesh_num_x * mesh_num_y; q--;) EEPROM_WRITE(dummy);
    #endif // MESH_BED_LEVELING

```

**Comment by ghost** [comment]
Alright...I didn't dig deep enough.

**Comment by manianac** [comment]
Just a small comment, I am strongly against auto-saving anything.  It should be in `M500` with everything else.

**Comment by ghost** [comment]
@manianac, you would have to turn this option ON to use it:

`#define STORE_MBL`

**Comment by ghost** [comment]
Currently, it is issuing an M500 when manual bed leveling is complete.

I am having a hard time with eeprom checksums when just saving the matrix and nothing else. Even when skipping everything not having to do with the bed leveling data. It writes something to eeprom, but when restoring....checksum error.

**Comment by manianac** [comment]
>@manianac, you would have to turn this option ON to use it:
>
>#define STORE_MBL

I understand that, but I'm saying write it similar to the rest of Marlin.  Look at the Bilinear grid, have it save similar to that.

>I am having a hard time with eeprom checksums when just saving the matrix and nothing else. Even when skipping everything not having to do with the bed leveling data. It writes something to eeprom, but when restoring....checksum error.

You shouldn't try to write parts of it, just write the entire thing in `configuration_store.cpp`.  Thinkyhead recently added code to only write whats changed, saving write cycles.

**Comment by ghost** [comment]
Yes....that's was the M500 also writes only what has changed.

I will take a closer look at the bilinear grid.

**Comment by thinkyhead** [comment]
> Yes....that's was the `M500` also writes only what has changed.

Although this is true, I would recommend against the feature proposed in this PR —even as an option— until the EEPROM code is rewritten so features may save their data alone, without saving any other changed data. There are certainly also instances where users want to save their motion settings and so on without also saving their current `G29` grid at the same time.

The problem with this PR is that it has the unintended side-effect of writing everything. To write the grid data alone is actually possible even in the current scheme. After saving the mesh info you need to re-read all the bytes in the EEPROM, generate and then store the new checksum.

**Pull request closed without merging**
