### PR TITLE
Support for Anycubic I3

### PR DESCRIPTION
**Pull request by boelle**
### Requirements

No requirements

### Description

Adds support for Anycubic i3

### Benefits

It's improves, anycubic only releases a .hex file and not the source

### Related Issues

Nothing related

### CODE REVIEW

**Comment by thinkyhead** [comment]
Lowercase filenames won't work on case-sensitive filesystems. Fixing now.

**Comment by boelle** [comment]
upps, must have slipped :-/

**Comment by thinkyhead** [comment]
"Oops" is my middle name.

**Comment by boelle** [comment]
OT: the reason why the re-arm pin file do not have tmc2208 in it, is that because it does not have enough interrupt able pins left? just wanted to hear it "from the man himself" before i decide to go with tmc2130, its a bit a shame since 2208 runs a bit cooler at the same amp's

**Pull request merged**
