### PR TITLE
Fix SDIO for STM32

### PR DESCRIPTION
**Pull request by thinkyhead**
From @GHGiampy at https://github.com/MarlinFirmware/Marlin/issues/24422#issuecomment-1179264392

Followup to #24271 which broke some things.

### CODE REVIEW

**Comment by rhapsodyv** [comment]
Take a look at my comment. We had some F1 Init code that is needed for some boards.

https://github.com/MarlinFirmware/Marlin/issues/22898#issuecomment-1176414096

**Comment by rhapsodyv** [comment]
Or you can just rollback all sdio changes from 24271 keeling only the H7 code that they added…
The old sdio code for f1 and f4 was pretty stable

**Comment by benlye** [comment]
I made a few tests with a Creality v4.2.2 (STM32F1) board and can confirm this looks good.  I can delete files from the SD card using `M30` and the Binary File Transfer protocol can write firmware bin files to the SD card - both these were failing before.

**Comment by GHGiampy** [comment]
Confirmed.
R/W to device is resumed with this PR...
...although the "Media init failed" message remains on the UI when the SD is inserted/removed, but I thinks it's another issue related to the slow USB init implementation.

Thanks.

**Pull request merged**
