### PR TITLE
Fix TMC compile error

### PR DESCRIPTION
**Pull request by Ludy87**
See: https://github.com/MarlinFirmware/Marlin/issues/12966

### CODE REVIEW

**Comment by teemuatlut** [comment]
Not the correct fix.
The issue was introduced by https://github.com/MarlinFirmware/Marlin/commit/52108192d1181da5275ab5edcaff0e0c6495f3a4
@thinkyhead

**Comment by Ludy87** [comment]
what would be correct?

**Comment by teemuatlut** [comment]
What it has been for months.
The recent change to `drivers.h` is what needs to reverted.
A user is asked to define the driver as `TMC2130` (or any of the others) but that no longer means anything.

EDIT: Maybe the new concatenation is supposed to address that.

**Comment by teemuatlut** [comment]
The compile issue can also be solved with
```cpp
  #define ____TMC_CLASS(MODEL, A, I) TMCMarlin<TMC##MODEL##Stepper, A, I>
  #define ___TMC_CLASS(MODEL, A, I) ____TMC_CLASS(MODEL, A, I)
  #define __TMC_CLASS(MODEL, A, I) ___TMC_CLASS(_##MODEL, A, I)
  #define _TMC_CLASS(MODEL, L) __TMC_CLASS(MODEL, L)
  #define TMC_CLASS(ST) _TMC_CLASS(ST##_DRIVER_TYPE, TMC_##ST##_LABEL)
```
Which correctly extracts the underlying numeric ID value for the driver. The main reason for doing all that is I don't want to tie the configuration option to the library class name.

**Comment by Ludy87** [comment]
@teemuatlut 
ok, should I correct the PR?

**Comment by andyman198** [comment]
I've added another issue which probably goes along with this. Using > 1 trinamic driven extruder seems to result in more problems. I can confirm that @teemuatlut your solution above did get me beyond the problems reported in this issue. Thank you both.

**Comment by thinkyhead** [comment]
> The compile issue can also be solved with

Thanks! I was looking to fix that macro but didn't know how.

**Pull request merged**
