### PR TITLE
TFT_COLOR_UI_PORTRAIT

### PR DESCRIPTION
**Pull request by alexgrach**
### Description
TFT_COLOR_UI_PORTRAIT set fix. Tests pass fix.

### Requirements

MKS Robin Nano, MKS Robin TFT 2,8"

### Related Issues
#25207

### CODE REVIEW

**Comment by ellensp** [comment]
Thinkyhead added the changes to Marlin/src/lcd/tft_io/tft_io.h into my pr https://github.com/MarlinFirmware/Marlin/pull/25252 which has been merged. 

BUt not the other change.....

**Comment by alexgrach** [comment]
_CMP doesn't work, but changing to CMP works corrently. Both changes was in #25207, but I've done something wrong I think and they was not included...

**Comment by jmz52** [comment]
https://github.com/MarlinFirmware/Marlin/pull/25279 was merged to bugfix-2.1.x
New portrait orientation check is in [tft_orientation.h#L54](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/lcd/tft_io/tft_orientation.h#L54)
This PR is obsolete and can be closed

**Comment by thisiskeithb** [comment]
Superseded by https://github.com/MarlinFirmware/Marlin/pull/25279

**Pull request closed without merging**
