### PR TITLE
LPC1768 fixes

### PR DESCRIPTION
**Pull request by DrDitto**
Bugfix 2.0.x  Fix all the glitches related with FAST MCU using MKS_MINI_12864 -Recover Custom Boot Screen funtionality -Maker easy to config Fysetc Panels -Enable backlight at startup for Fysetc Neopixel version 

[Config.zip](https://github.com/MarlinFirmware/Marlin/files/3439541/Config.zip)
No special requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

- FIX MKS_MINI_12864 over fast MCU
- Recover custom boot screeen functionality
-Makes easy to config Fysetc RGB Panels
-Enable backlight on startup over Fysetc V2.1

Recover all spected functionality that was broken

All MKS_MINI_12864
[platformio.zip](https://github.com/MarlinFirmware/Marlin/files/3439540/platformio.zip)

### CODE REVIEW

**Comment by jmdearras** [comment]
Any chance of getting MKS_MINI_12864 support on the SKR_MINI_V1.1?

**Review by DrDitto — COMMENTED** [review]
more easy this way

**Comment by DrDitto** [comment]
This fix also works on skr v1.1 beacuse it uses LPC1768

**Comment by thinkyhead** [comment]
This is quite a mess. Please prepare the branch properly before submitting a PR.

**Pull request closed without merging**
