### PR TITLE
Squashed - Removal of PID functional range

### PR DESCRIPTION
**Pull request by thinkyhead**
Cleanup / Squash of #4929

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
=:-(

**Comment by thinkyhead** [comment]
Is that supposed to be feedback? If this should be restored, use your words.

**Comment by Blue-Marlin** [comment]
I invested a day for https://github.com/MarlinFirmware/Marlin/issues/4922#issuecomment-251119138 to show what I can do with PID_FUNCTIONAL_RANGE. Merging this PR without further discussion makes me sad

**Comment by thinkyhead** [comment]
Sorry this got merged too quickly. Let's keep this feature for whomever needs it.

**Pull request merged**
