### PR TITLE
Add MKS_GEN_L_V2 controller support. 2.0 branch

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Add a new controller the MKS_GEN_L_V2. Its basically a RAMPS with a few changes.

Details of this controller can be found here https://github.com/makerbase-mks/MKS-GEN_L/tree/master/hardware/MKS%20Gen_L%20V2.0_001 

### Benefits

Another controller board is supported 

### Related Issues

Feature request #15794

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for the submission!

**Comment by tedead** [comment]
Just a heads up, but when I tried configuring TMC2208s to run in UART I found that I needed to comment out the CS pin assignments as these pins are used for axis RX pins. On the v2.0 board these are the XUART, YUART, ZUART, etc jumpers. The pin assignments added look to be for TMC2130-SPI(HW) and will not work for TMC2208-UART.

**Comment by thinkyhead** [comment]
Did it not work to define them as -1 in your `Configuration_adv.h` file?
```cpp
  /**
   * Override default SPI pins for TMC2130, TMC2160, TMC2660, TMC5130 and TMC5160 drivers here.
   * The default pins can be found in your board's pins file.
   */
  #define X_CS_PIN          -1
  #define Y_CS_PIN          -1
  #define Z_CS_PIN          -1
```

**Comment by tedead** [comment]
I didn't touch that part because I am using the TMC2208. I guess that I could try modifying this but why would I need to define CS pins for this driver? Wouldn't I want to keep these disabled?

  /**
   * Override default SPI pins for TMC2130, TMC2160, TMC2660, TMC5130 and TMC5160 drivers here.
   * The default pins can be found in your board's pins file.
   */
  //#define X_CS_PIN          -1
  //#define Y_CS_PIN          -1
  //#define Z_CS_PIN          -1
  //#define X2_CS_PIN         -1
  //#define Y2_CS_PIN         -1
  //#define Z2_CS_PIN         -1
  //#define Z3_CS_PIN         -1
  //#define E0_CS_PIN         -1
  //#define E1_CS_PIN         -1
  //#define E2_CS_PIN         -1
  //#define E3_CS_PIN         -1
  //#define E4_CS_PIN         -1
  //#define E5_CS_PIN         -1
  //#define E6_CS_PIN         -1
  //#define E7_CS_PIN         -1

**Pull request merged**
