### PR TITLE
Support for RP2040 and BTT SKR Pico (WIP)

### PR DESCRIPTION
**Pull request by thinkyhead**
- Add a new HAL to support RP2040 processor boards.
- Support for a Generic board.
- Support for headless BTT SKR Pico.

### TODO
- Switch to the core at https://github.com/earlephilhower/arduino-pico as the best option
- Eliminate LVGL dependency under headless operation

### CODE REVIEW

**Comment by Lan-Hekary** [comment]
Hello,
Is there any news about when this PR will be merged ?

**Comment by ellensp** [comment]
@Lan-Hekary when its finished!   It is a Work in progress

**Comment by Lan-Hekary** [comment]
Hello again,
I know it's still Work in Progress, I want to help out.

I have a DIY 3D Printer that currently use Ramps1.6 + Arduino Mega
I also have RP Pico laying around and some skill with Electronics and Firmware.

All I need is some guidance on how to test this PR.

if there is a Schematic for the Generic RP2040 Connection to The Motor Drivers, Temp Sensors, Endstops and Outputs that would super helpful.
 
I will make a PCB and test the code and maybe contribute if there is a bug that I can fix.

**Comment by z7ths** [comment]
I have a SKR Pico that I want to test with Marlin but I can't build this. I commented out the missing watchdog issues but get stuck on other parts. Is there some way to get this to build to test?

**Comment by anand-010** [comment]
Is it functional how do i test it?.

**Comment by rondlh** [comment]
Very nice project, I tested it on an MKS THR42 board (CAN Bus toolhead). Most thing work already, but I get stuck when I enable the onboard TMC2209 (serial config mode). There seems to be a conflict in softwareserial, because even the host communication gets lost when doing this. 
If I can get the TMC2209 configured then I will work on establishing a CAN connection between the Monster8 and MKS THR42.

**Comment by jneilliii** [comment]
more boards are coming out with rp2040 chipsets now, would seem that this PR stalled for some reason, would be great to bring it back to life.

**Comment by rondlh** [comment]
> more boards are coming out with rp2040 chipsets now, would seem that this PR stalled for some reason, would be great to bring it back to life.

Yes, I agree, especially as things are almost working. For now I switched to STM32 toolhead boards, like the BTT EBB42 V1.2

**Comment by lint-os** [comment]
How close is this to testing on an actual hardware system?
I've got an SKR pico for a simple 2d plotter style project and would like to test Marlin out.

**Comment by thinkyhead** [comment]
@lint-os — This should now be compiling and running. We definitely need more feedback about how it performs in a real setup. I have a Pico board here but it's just loose and attached to a serial touch screen.

**Comment by lint-os** [comment]
Cool. I will try it out soon.

**Pull request merged**
