### PR TITLE
Optional menu item for Assisted Tramming

### PR DESCRIPTION
**Pull request by qwewer0**
Add the ability to disable/enable `ASSISTED_TRAMMING` menu item.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This one isn’t as big of concern since it doesn’t sit at the top of the main menu list like `ACTION_ON_START`.

**Comment by qwewer0** [comment]
> This one isn’t as big of concern since it doesn’t sit at the top of the main menu list like `ACTION_ON_START`.

@thisiskeithb Yes I know, but it is nice to have the ability to choose to have it in the menus or not.
I use ASSISTED_TRAMMING maybe once in 1-2 weeks, and if I use it that isn't from the menu, so it's more convenient to not have it at all in the menus.

**Comment by ETE-Design** [comment]
@qwewer0 So this make it possible to show info needed on LCD to Tram the bed? With GFX show what way to turn the wheels and how much?

**Comment by qwewer0** [comment]
> @qwewer0 So this make it possible to show info needed on LCD to Tram the bed? With GFX show what way to turn the wheels and how much?

@ETE-Design No. This PR only gives us the option to have the already available Assisted Tramming menu item to be disabled.

**Pull request merged**
