### PR TITLE
README: Removing dead URL to 32bit work

### PR DESCRIPTION
**Pull request by thopiekar**

### CODE REVIEW

**Comment by thinkyhead** [comment]
We don't patch releases. But we'll be sure to fix that in the next release.

**Comment by thopiekar** [comment]
Oh, you mean I sent this change to a wrong branch?
Or how do you mean?

**Comment by thinkyhead** [comment]
Correct. We make patches to the bugfix branches and only later do we push them out as releases. If you feel inclined, redo this PR starting with the `bugfix-1.1.x` (and `bugfix-2.0.x`) branch and be careful to submit it to the same branch you started with.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by thopiekar** [comment]
Alright. I didn't know that. Will try to find time later to redo that.

Thank you for pointing me to the rules how to contribute.

**Pull request closed without merging**
