### PR TITLE
Add preheat for popular material

### PR DESCRIPTION
**Pull request by android444**
Add preheat for:
PET
RUBBER
HIPS
NYLON

### CODE REVIEW

**Comment by android444** [comment]
Why?

**Comment by manianac** [comment]
Why what?

If you mean why did the travis-ci build fail, if you click the Red X it will tell you.

```
language_en.h:165: error: unterminated #ifndef
 #ifndef MSG_PREHEAT_5_SETTINGS
 ^
```

**Comment by android444** [comment]
Why all checks have failed?

**Comment by manianac** [comment]
Click details for the travis CI build or the red X for your commit to see the error.

**Comment by android444** [comment]
Corrected.

**Comment by android444** [comment]
All work properly.
It is not my fault that there are errors in the example files.

use_example_configs Hephestos_2 and other

sam_9591
sam_9592
sam_9593

**Comment by manianac** [comment]
What errors? Also it's not a good idea to enable cooling fan on ABS across the board

**Comment by android444** [comment]
In the first file I changed the original value. In the second file I restored it.

**Comment by manianac** [comment]
👍

**Comment by android444** [comment]
I do not know how to add a new PULL REQUEST :(

**Comment by manianac** [comment]
You've modified an awful lot, including the default configuration file to suit your own printer.  You may have to close this pull request and open another if need be, only modifying whats necessary.

**Comment by android444** [comment]
I'll do it again.
I close.

**Pull request closed without merging**
