### PR TITLE
Rambo FAN_PIN documentation and servo support

### PR DESCRIPTION
**Pull request by Sniffle**
Updated pins reference and servo support.

cross referenced between Rambo 1.1, 1.2, and 1.3

### CODE REVIEW

**Comment by Sniffle** [comment]
Probably a better way to implement this after thinking on it more, would be to add the generic servo ifdef block of code to config_adv.h, and just add the relevant pin info to a comment block under the RAMBo header in Pins.h.

I haven't looked to see if that might break things yet, just thinking on it still.  It would just generalize and clean up servo support some, and still add the general pinout info for the Rambo board as those 6 pins are the most common pins for setting up servo's(22,23,24) and editing fans(2,4,8).

**Comment by stv0g** [comment]
Okay, then we will leave this PR open until you made your thoughts about that alternative implementation.

> [...] for the Rambo board as those 6 pins are the most common pins [...]

What do you mean be 'most common'? Are these pins dedicated for these features? Or just generic IOs?

**Comment by boelle** [comment]
we should also try and hold back on merging to much while fixing bugs?? just a thought

**Comment by Sniffle** [comment]
sorry it's 7 pins

For the fans, you only have 3 fan mosfet drivers, 
header - pin
FAN_0 - 8
FAN_1 - 6
FAN_2 - 2

For the logical servo options, the only other free PWM headers are the extra motor extensions, that use pins 22,23,24
MX1 - 22
MX2 - 23
MX3 - 24

or the single unshared PWM pin on the PWM header and that is pin 5

As to the servo code cleanup, If a board can support a servo, but either has multiple pins or someone makes a pin available somehow, you need a way to be able to define which pin will be used for said servo.

This isn't necessarily a bug, but more of a code cleanup and information insertion for the RAMBo boards which so far it has been very hard to come across due to them being so new.

**Comment by vandarin** [comment]
Personally, I'm using pin 4 (in the PWM-ext block), which is what a forum post recommended. I'll have to check after this print is finished to see if the MX pin block even has headers populated on my board. Either way, I think it's a good idea to list the usable pins in pins.h.

**Comment by Sniffle** [comment]
The reason i didn't list pin 4 is that it shares with PS-On which isn't necessarily used by everyone, but isn't a stand alone pin.

**Comment by vandarin** [comment]
Got it. That makes sense.

**Comment by boelle** [comment]
any words on this one? merge / not merge ....

**Pull request merged**
