### PR TITLE
32-bit Changes on RCBugFix

### PR DESCRIPTION
**Pull request by thinkyhead**
Manually applied relevant changes from #5859 to the current `RCBugFix` branch, dropping regressions. The commits in this PR itemize all changes required to make RCBugFix work in 32-bit. The 
`32-Bit-RCBugFix-new` branch should replace the `32-Bit-RcBugFix` branch after this has been reviewed and merged.

Files that have been moved into the HAL folder have not been compared in detail. But most of these files have changed very little recently. Will compare differences in more detail soon.

### CODE REVIEW

**Comment by p3p** [comment]
Nice, much cleaner, I'l test it out tomorrow. This is probably a good time to ask if you understand the changes to [this](https://github.com/thinkyhead/Marlin/blob/29c02e99b21c2eaddd737fc143a5e07328209277/Marlin/src/HAL/math_32bit.h#L30) line, as far as I can tell the rshift should not be changed from 24 bit unless the precision is changed in [planner.cpp](https://github.com/thinkyhead/Marlin/blob/29c02e99b21c2eaddd737fc143a5e07328209277/Marlin/planner.cpp#L1153) where its multiplied by (1<<24) rather than lshifted. I also don't understand the purpose of the addition. I change it back in my working branch.

**Comment by teemuatlut** [comment]
I was having issues with acceleration ramping until I changed it back to how it's on AVR.
So I too would like to know some background on that one.

**Comment by thinkyhead** [comment]
Should we add this and use it?
```cpp
#define MultiU24X32toH32(intRes, longIn1, longIn2) intRes = ((uint64_t)longIn1 * longIn2 + 0x00800000) >> 24
```

**Comment by thinkyhead** [comment]
> until I changed it back to how it's on AVR

i.e., changed it back to this…?
```cpp
block->acceleration_rate = (long)(accel * 16777216.0 / ((F_CPU) * 0.125)); // * 8.388608
```

**Comment by thinkyhead** [comment]
> as far as I can tell the rshift should not be changed from 24 bit unless the precision is changed in planner.cpp where its multiplied by (1<<24) rather than lshifted

So, should there be a 24-bit shifted value for this case…?
```cpp
#define MultiU32X32toH32(intRes, longIn1, longIn2) intRes = ((uint64_t)longIn1 * longIn2 + 0x80000000) >> 32
#define MultiU32X24toH32(intRes, longIn1, longIn2) intRes = ((uint64_t)longIn1 * longIn2 + 0x00800000) >> 24
```

**Comment by p3p** [comment]
The code in planner.cpp is correct, its the macro that needs the the rshift changed back to 24 for it to work, at the moment its lshifting by 24, then rshifting by 32 and expecting to get the same value back.

**Comment by thinkyhead** [comment]
…or…?
```cpp
block->acceleration_rate = (long)(accel * powf(2, 32) / (HAL_TIMER_RATE));
```

**Comment by p3p** [comment]
That could also work, although I'm unsure if there would be any benefit, and it could cause overflow issues with lots of other code, I cant tell without stepping through it.

**Comment by thinkyhead** [comment]
See if https://github.com/MarlinFirmware/Marlin/pull/5877/commits/c1deeaae6ddbcf22464fe6bd966a2b99f4694b03 works, for now.

**Comment by p3p** [comment]
ah sorry I should have said, I also have no idea what that addition is for, that will just increase the acceleration rate, without informing the planner, It works properly without it.

From [math_AVR.h](https://github.com/thinkyhead/Marlin/blob/c1deeaae6ddbcf22464fe6bd966a2b99f4694b03/Marlin/src/HAL/HAL_AVR/math_AVR.h#L30) it should just be `result = a * b >> 24; ` and the inputs havn't changed.

**Comment by teemuatlut** [comment]
@thinkyhead 
> i.e., changed it back to this…?

I changed the macro. This is what I currently have for Teensies:
```cpp
   math_32bit.h
   #define MultiU32X32toH32(intRes, longIn1, longIn2) (intRes = ((uint64_t)longIn1 * longIn2 + 0x80000000) >> 24)

   planner.cpp
   block->acceleration_rate = (long)(accel * 16777216.0 / HAL_TIMER_RATE);
```

**Comment by p3p** [comment]
@teemuatlut Interesting that you left the addition in, have I missed something?

**Comment by AnHardt** [comment]
I guess the addition is for rounding (It's like adding 0.5 in float). Setting bit 31 for a 24 bit shift is obviously wrong then.

**Comment by teemuatlut** [comment]
@p3p Don't mess with what you cannot understand :P

I just figured it might have something to do with making sure there is a minimum value or something.

**Comment by p3p** [comment]
ahhh thanks @AnHardt that makes a lot of sense, @teemuatlut yea I stepped through the entire planner and stepper ISR a few times to try and understand what had been changed, the 32bit shift was obviously wrong but I couldn't understand the addition. adding (1<<31) before val>>32 should have been clear that it was rounding up. make sure you change yours to (1<<23) like @thinkyhead has above (he obviously understood :) )

**Comment by thinkyhead** [comment]
Ok, so if there are no other issues with this branch, I will merge it, and `git reset` the 32-bit branch to point to it.

**Comment by Roxy-3D** [comment]
Has anybody tried this on a Re-Arm board?   It might be good to know what works on the various 32-Bit boards.

**Comment by p3p** [comment]
It's not so much what works on the individual devices, its whether there is someone to write the HAL layer for that device, Re-Arm is just a LPC1768 with a Arduino breakout, it wouldn't be an issue getting basic RAMPS1.4 features up and running. There is still a lot to do with the HAL Interface though, especially extracting everything Arduino related.

**Comment by p3p** [comment]
Fixed some of the Timer defines to what I think was intended in this [branch](https://github.com/p3p/Marlin/tree/rcbugfix_plus_32bit_defines), ignore the reorder of the inclusions though, that fixes my build but causes errors in the tests.

**Comment by thinkyhead** [comment]
I've made a PR out of it. thinkyhead/Marlin#22

> but causes errors in the tests

So, it builds, but doesn't function properly?

**Comment by p3p** [comment]
No, for my specific config changing the order of inclusions removed redefinition warnings and worked correctly, but it now fails the travis tests.

**Comment by thinkyhead** [comment]
It appears that the `max` and `min` macros are undefined when `Conditionals_POST.h` is included.

**Comment by p3p** [comment]
MarlinConfig.h was included from the HAL header for some reason that I'l figure out later when nothing works, passes the travis tests now though. This is the last change I can really submit for this PR as my further modifications are all specific to my STMF7. This would be easier if I was actually using an Arduino related device. Generalising the separation of the peripheral libraries from Arduino being the main issue now.

**Comment by thinkyhead** [comment]
Travis CI service is currently a little broken and not building. It'll probably come back within the day.

**Comment by psavva** [comment]
Following, let me know if I can help test the Re-Arm board.

**Comment by thinkyhead** [comment]
@psavva I have a Re-Arm on hand but haven't tried flashing it yet. I will probably play around with it over the weekend, but feel free to jump in and try flashing it anytime, see if it can at least run the firmware.

**Comment by Roxy-3D** [comment]
> @psavva I have a Re-Arm on hand but haven't tried flashing it yet. I will probably play around with it over the weekend, but feel free to jump in and try flashing it anytime, see if it can at least run the firmware.

Yes...  And if you can take notes what to do to get the Marlin firmware image loaded into it, that would be helpful too!   It would be great if we could get a 'Core Team' of Re-Arm people bringing their Re-Arm boards up together as a group!

**Comment by brainscan** [comment]
>  It would be great if we could get a 'Core Team' of Re-Arm people bringing their Re-Arm boards up together as a group!

If I get time between feeding twins I'd be up for helping out with Re-Arm testing, it's been sitting here looking pretty for a few weeks but really want to get it working.

**Comment by thinkyhead** [comment]
With that issue patched, I hope that's everything. I tried to be thorough, but it's easy to miss things when the momentum is high. I don't mind merging this with the temporary branch, anyway. After some testing we'll know whether it's ready to supplant the 32-bit branch.

**Pull request merged**
