### PR TITLE
Add support for MKS Robin E3/E3D V1.1 motherboard

### PR DESCRIPTION
**Pull request by mks-viva**
### Requirements

* Add support for MKS Robin E3/E3D V1.1 motherboard

### Description

- Add support for MKS Robin E3/E3D V1.1 motherboard
  - Z_STEP signal chang to PC14
  - Z_DIR signal change to PC15
  - Add support for AT24C32D 4KB EEPROM on th board
  - Optimize USB package design
  - Optimize PCB layout design

- MKS Robin E3/E3D V1.1 hardware: https://github.com/makerbase-mks/MKS-Robin-E3-E3D/tree/ender3-3d-touch/hardware
image

### CODE REVIEW

**Comment by sjasonsmith** [comment]
@thisiskeithb do you have recommendations for this?

My main question is whether the common 1.1 file should be including the 1.0 file, and just making a few adjustments.
There is always a tradeoff between avoiding repetition and details being hard to find across multiple files.

**Comment by thisiskeithb** [comment]
I’ll have to check when I’m back at a computer, but if there were only a few pin changes, then it’d make sense to just include the Robin E3 common file and handle the new boards similarly to how it was done for the BTT SKR Mini E3 V2 in https://github.com/MarlinFirmware/Marlin/pull/18088

Gotta keep it DRY 🙂

**Comment by positron96** [comment]
Hi. As I understand, EEPROM is defined to be 4Kb [here](https://github.com/tharts/Marlin/commit/f7f97632d90496e5e9304232392dd403140d5481#diff-1423cb7fce46951aaae38cecacba1af5a7d36f581c1cde6d6b8465eb396349fbR30). Shouldn't it be 32Kb?

**Comment by ellensp** [comment]
@positron96  AT24C32D 32Kb  b as in bit so /8 bits for 4KB ie bytes

**Comment by positron96** [comment]
@ellensp Ah, stupid me. That's probably why my config with 32 Kb crashed the board.

**Pull request merged**
