### PR TITLE
SD EEPROM: Create eeprom.dat if not found on SD

### PR DESCRIPTION
**Pull request by pinchies**
fix for SD as eeprom - create file if no eeprom.dat file found.

### CODE REVIEW

**Comment by pinchies** [comment]
I didn't have any problems with the root directory thing we discussed, but I found there was no eeprom.dat created automatically if it wasnt present

**Comment by tpruvot** [comment]
seems weird to me, we never had to create it manually...

**Comment by pinchies** [comment]
I didn't either, until the recent builds. I can't figure out why, but 3am me probably was missing something in one of the revisions. It was repeatable for me however, I do think this PR is required.

**Comment by pinchies** [comment]
I now guess I wonder if adding O_CREAT permission to the initial open would make it return a success.......

**Comment by tpruvot** [comment]
I dont see why that could help to store junk and return true

**Comment by pinchies** [comment]
Because if no file is found, the PersistentStore::access_start() aborts the save eeprom process - the same as if no card was detected, so the PersistentStore::access_finish() is never reached, and so the correct file is never created.

But I wonder if adding O_CREAT permission to the initial file.open would achieve the same result. 

Regardless, I'm just sharing my findings after people informed me that they had problems, and I diagnosed the cause. Not sure what the best way to patch this bug is.

**Comment by tpruvot** [comment]
format the sdcard imo, seems an hardware to me

**Comment by pinchies** [comment]
Tried multiple sd cards, formatted, with files or completely blank, multiple printers, checked write switch etc etc. Repeatable.

**Comment by tpruvot** [comment]
so you are saying the eeprom data is reloaded before save ? cant be...

**Comment by tpruvot** [comment]
hmm maybe it is... need to read the shared ocde

**Comment by pinchies** [comment]
I'm not claiming to be able to write C++ code well any better than I can claim to speak french, but I can at least read some of it :-P

**Comment by tpruvot** [comment]
i dont see any abort on access_start failure.. just a serial message warning

**Comment by tpruvot** [comment]
oh i see it now: 
  #define EEPROM_START()          if (!persistentStore.access_start()) { SERIAL_ECHO_MSG("No EEPROM."); return false; } \

**Comment by tpruvot** [comment]
commit fdbc733376

**Comment by tpruvot** [comment]
but its not the right solution.. this commit... you dont have to create the file to fix that... just need to return true

**Comment by tpruvot** [comment]
rmm im currently testing the flash eeprom PR, and maybe my issue is the same one... :p
**edit: no**
```
bool PersistentStore::access_start() {
  firstWrite = true;
  return true;
}
```

**Comment by pinchies** [comment]
Ahhhh, that was the breaking commit! That makes sense now.

**Comment by pinchies** [comment]
tagging #14776

**Comment by tpruvot** [comment]
yep, sorry i made tests recently but was before this change... and i was confused about your issue

**Comment by pinchies** [comment]
I appreciate that you're looking into flash eeprom, would be even nicer to have that working too.

**Comment by tpruvot** [comment]
not won for now, the PR didnt work on any of my 2 different boards.. (skrmini/longer3D)
edit: in fact it worked... on the [skrmini ](https://github.com/tpruvot/Marlin/commit/1bc5c97b95ac3f265b291955ecebb58886613f57)hmm, maybe some hope

else the sd fix to appy: https://github.com/tpruvot/Marlin/commit/b97409d0d212a88687f6c8496a318325aae480c7

**Comment by trouch** [comment]
⚠️ `test_index` isn't initialized to `EEPROM_OFFSET`
But we won't need it anymore once my PR #14829 get merged.

**Comment by pinchies** [comment]
@trouch not sure I understand your comment in relation to this PR

I think that simply returning true is the wrong solution as if there is another failure to open the file we do want it to return false.

**Comment by tpruvot** [comment]
see the other implementations, they return most true by default... doing nothing on start.
if (!card.isDetected()) return false; remains for the common case..

and the write may return false in case of write problem anyway

**Comment by pinchies** [comment]
Fair enough - I guess there’s no need for it to be in an if statement at all then if we don’t care about the returned value being false?

**Comment by yangwenxiong** [comment]
The version I downloaded in July. Don't create eeprom. Dat file.

**Comment by pinchies** [comment]
@yangwenxiong - if you do the top change at this link it should work:
https://github.com/tpruvot/Marlin/commit/b97409d0d212a88687f6c8496a318325aae480c7

**Comment by yangwenxiong** [comment]
> oh i see it now:
> #define EEPROM_START() if (!persistentStore.access_start()) { SERIAL_ECHO_MSG("No EEPROM."); return false; } \

For the MCU of STM32F103xx series, it is necessary to build a file EEPROM.DAT in SD card in advance to simulate EEPROM data storage in SD card.Otherwise it's not gonna work and you're going to have a problem with it,

**Comment by yangwenxiong** [comment]
> > oh i see it now:
> > #define EEPROM_START() if (!persistentStore.access_start()) { SERIAL_ECHO_MSG("No EEPROM."); return false; } \
> 
> For the MCU of STM32F103xx series, it is necessary to build a file EEPROM.DAT in SD card in advance to simulate EEPROM data storage in SD card.Otherwise it's not gonna work and you're going to have a problem with it,

  #define EEPROM_START()          int eeprom_index = EEPROM_OFFSET; persistentStore.access_start()

**Comment by pinchies** [comment]
You don’t need to do that. You do need to change the file containing the access_start()

**Comment by tpruvot** [comment]
This one can be closed now.. (you can delete the branch pinchies:fix-sd-no-file-eeprom @pinchies to do it)

**Comment by pinchies** [comment]
I don’t see the issue fixed yet?

**Comment by tpruvot** [comment]
commit 92c35d14a47a7b333690989f7b749d6385185bd7

**Pull request closed without merging**
