### PR TITLE
M600 cleanup and bugfix

### PR DESCRIPTION
**Pull request by thinkyhead**
- Fix issue with ignored click. (`wait_for_user` must be cleared.)
- Draw M600 heater status as a custom static item
- Show M600 heater status on bottom line — or below, as display allows
- Apply graphical display optimization - only draw heater status in its page/segment
- Add some comments to M600 code
- Group M600 configuration options closer together
- Add `HOTEND_STATUS_ITEM` to draw in the same manner as static/menu items

Future Ideas:
- Click to interrupt M600 load / eject moves.
- After Eject, show "Eject More" / "Insert Now" (since first eject may fail).

### CODE REVIEW

**Comment by ghost** [comment]
>Fix issue with ignored click. (wait_for_user must be cleared.)

Fantastic!! Thank you!

>Draw M600 heater status as a custom static item
Show M600 heater status on bottom line — or below, as display allows
Apply graphical display optimization - only draw heater status in its page/segment

Looks good, but we lost the header on several screens:
Init, Unload, Insert, and Click to heat

With these screens, the header showed for a split second and disappeared:
Heating, Click to load, and Extrude

Resume screen shows the header.

The temp displayed at the bottom line (On my Reprap Full Graphic, off-centered to the right), updated the temp as intended.

**Comment by thinkyhead** [comment]
> Looks good, but we lost the header on several screens:

Graphical display, I presume. Try changing this line in the `HOTEND_STATUS_ITEM` macro…
```diff
-         lcdDrawUpdate = LCDVIEW_CALL_NO_REDRAW; \
+         lcdDrawUpdate = LCDVIEW_CALL_REDRAW_NEXT; \
```

**Comment by ghost** [comment]
Here?
```
        if (_skipStatic && encoderLine <= _thisItemNr) { \
          encoderPosition += ENCODER_STEPS_PER_MENU_ITEM; \
          lcdDrawUpdate = LCDVIEW_CALL_REDRAW_NEXT; \
        } \
        else \
          lcdDrawUpdate = LCDVIEW_CALL_NO_REDRAW; \    <-----
      } \
```

**Comment by ghost** [comment]
If so, wouldn't that defeat the purpose of the if statement?

**Comment by mg0706** [comment]
Guys first time here. Sorry if i put this in the wrong place but:...

Is it possible to change the nozzle temp when you do M600? if not, is there a way to do that or include that on the M600 as a parameter? have you ever think about that? Also i want to thank you guys for your great job.

**Comment by ghost** [comment]
@mg0706: So far, there isn't. The premise, was to shut down the hotend due to user not being available at the timeout after M600 was invoked.

**Comment by ghost** [comment]
@mg0706, I am testing an option to do as you ask. If it works, I will post the changes I did and you will be able to implement it on yours.

**Comment by ghost** [comment]
Ok, in `configuration_adv.h`, add this line:
`  #define FILAMENT_CHANGE_NOZZLE_TEMP  100    // Optional temp to hold instead of shutting down.`
as shown below:
```
  #define FILAMENT_CHANGE_NOZZLE_TIMEOUT 45L  // Turn off nozzle if user doesn't change filament within this time limit in seconds
  #define FILAMENT_CHANGE_NOZZLE_TEMP  100    // Optional temp to hold instead of shutting down.
  #define FILAMENT_CHANGE_NUMBER_OF_ALERT_BEEPS  18L  // Number of alert beeps before printer goes quiet
  #define FILAMENT_CHANGE_NO_STEPPER_TIMEOUT         // Enable to have stepper motors hold position during filament change
                                                     // even if it takes longer than DEFAULT_STEPPER_DEACTIVE_TIME.
```
And in `marlin_main.cpp`, change these lines:
```
      if (current_ms >= nozzle_timeout) {
        if (!nozzle_timed_out) {
          nozzle_timed_out = true; // on nozzle timeout remember the nozzles need to be reheated
          HOTEND_LOOP() thermalManager.setTargetHotend(0, e); // Turn off all the nozzles
          lcd_filament_change_show_message(FILAMENT_CHANGE_MESSAGE_CLICK_TO_HEAT_NOZZLE);
```
to these:
```
      if (current_ms >= nozzle_timeout) {
        if (!nozzle_timed_out) {
          nozzle_timed_out = true; // on nozzle timeout remember the nozzles need to be reheated
          #ifdef FILAMENT_CHANGE_NOZZLE_TEMP 
            HOTEND_LOOP() thermalManager.setTargetHotend(FILAMENT_CHANGE_NOZZLE_TEMP, e); // Set hold temp on all nozzles
          #else 
            HOTEND_LOOP() thermalManager.setTargetHotend(0, e); // Turn off all the nozzles
          #endif
          lcd_filament_change_show_message(FILAMENT_CHANGE_MESSAGE_CLICK_TO_HEAT_NOZZLE);
```
This will allow the option, `FILAMENT_CHANGE_NOZZLE_TEMP`, to be used or not. I have tested it at the 100C with no issues.

**Comment by ghost** [comment]
Or, if this is to be implemented permanently, I would simplify this by setting the option enabled all the time and at 0. And set the hotend(s) to `FILAMENT_CHANGE_NOZZLE_TEMP`. 

Would eliminate the if, else, endif statements.

**Comment by ghost** [comment]
Like so:
```
      if (current_ms >= nozzle_timeout) {
        if (!nozzle_timed_out) {
          nozzle_timed_out = true; // on nozzle timeout remember the nozzles need to be reheated
            HOTEND_LOOP() thermalManager.setTargetHotend(FILAMENT_CHANGE_NOZZLE_TEMP, e); // Set the nozzle temps
          lcd_filament_change_show_message(FILAMENT_CHANGE_MESSAGE_CLICK_TO_HEAT_NOZZLE);
```

**Comment by mg0706** [comment]
Hey Tannoo. Thanks. You just gave a solution for a problem i i just had last night because i was worry to no hear the bit when the M600 kick on while i was sleeping. Thank you. I definitely will implement this.. But my question was about change nozzle temperature when we change filament. Because when we use different filament, not all the time they work fine with the same temp. sample: i have a silver pla that print great at 205 and a black pla that print great at 215. so we use the M600 i was thinking like on the screen shows up something asking if we want to change the temp for the new filament. (sorry, english is not my first language). Thank you again. Thanks for the fast answer and even fast solution for my other issue (worry). I will try that for sure.

**Comment by ghost** [comment]
So, you want to change the nozzle set point for the nozzle heat-up? That's a little trickier.

Maybe that should be setup as a parameter to M600.
M600 Sxxx?

**Comment by mg0706** [comment]
Well that is what i thought first: like M600 c210 or something like that, or show on the screen. whatever it work better and/or faster. Also, i am trying to do what you told me. Add the `#define FILAMENT_CHANGE_NOZZLE_TEMP 100 // Optional temp to hold instead of shutting down.` in `configuration_adv.h` but i can't find any of the thing you showed me, like the:
```cpp
  #define FILAMENT_CHANGE_NOZZLE_TIMEOUT 45L  // Turn off nozzle if user doesn't change filament within this time limit in seconds
  #define FILAMENT_CHANGE_NOZZLE_TEMP  100    // Optional temp to hold instead of shutting down.
  #define FILAMENT_CHANGE_NUMBER_OF_ALERT_BEEPS  18L  // Number of alert beeps before printer goes quiet
  #define FILAMENT_CHANGE_NO_STEPPER_TIMEOUT         // Enable to have stepper motors hold position during filament change
                                                     // even if it takes longer than DEFAULT_STEPPER_DEACTIVE_TIME.
```
 So, i think i have to add all that, right? i am working with rc7 and rc8. i just want to make sure i am no missing anything an d something bad. Thank you again

**Comment by ghost** [comment]
Umm. Ok. What controller are configured for?
Upgrade to the latest RCBugFix. It has it.

If you don't have those other settings, adding them there won't do anything,. You would need the rest of the M600 code.

**Comment by mg0706** [comment]
it is for the REPRAP_DISCOUNT_SMART_CONTROLLER

**Comment by ghost** [comment]
>it is for the REPRAP_DISCOUNT_SMART_CONTROLLER

That is the LCD. What motherboard?

**Comment by mg0706** [comment]
lol. sorry.  it is mks  gen v1.4

**Comment by ghost** [comment]
ok. what motherboard do you have selected in `configuration.h` here:
```
// The following define selects which electronics board you have.
// Please choose the name from boards.h that matches your setup
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_RAMPS_14_EFB
#endif
```

**Comment by mg0706** [comment]
the same you got  there. BOARD_RAMPS_14_EFB

**Comment by ghost** [comment]
ok. If you don't have those other settings, download and setup RCBugFix branch. It will have those settings and the code to support them.
In `configuration_adv.h`, it will look like this:
```cpp
/**
 * Filament Change
 * Experimental filament change support.
 * Adds the GCode M600 for initiating filament change.
 *
 * Requires an LCD display.
 * This feature is required for the default FILAMENT_RUNOUT_SCRIPT.
 */
//#define FILAMENT_CHANGE_FEATURE
#if ENABLED(FILAMENT_CHANGE_FEATURE)
  #define FILAMENT_CHANGE_X_POS 3             // X position of hotend
  #define FILAMENT_CHANGE_Y_POS 3             // Y position of hotend
  #define FILAMENT_CHANGE_Z_ADD 10            // Z addition of hotend (lift)
  #define FILAMENT_CHANGE_XY_FEEDRATE 100     // X and Y axes feedrate in mm/s (also used for delta printers Z axis)
  #define FILAMENT_CHANGE_Z_FEEDRATE 5        // Z axis feedrate in mm/s (not used for delta printers)
  #define FILAMENT_CHANGE_RETRACT_FEEDRATE 60 // Initial retract feedrate in mm/s
  #define FILAMENT_CHANGE_RETRACT_LENGTH 2    // Initial retract in mm
                                              // It is a short retract used immediately after print interrupt before move to filament exchange position
  #define FILAMENT_CHANGE_UNLOAD_FEEDRATE 10  // Unload filament feedrate in mm/s - filament unloading can be fast
  #define FILAMENT_CHANGE_UNLOAD_LENGTH 100   // Unload filament length from hotend in mm
                                              // Longer length for bowden printers to unload filament from whole bowden tube,
                                              // shorter length for printers without bowden to unload filament from extruder only,
                                              // 0 to disable unloading for manual unloading
  #define FILAMENT_CHANGE_LOAD_FEEDRATE 6     // Load filament feedrate in mm/s - filament loading into the bowden tube can be fast
  #define FILAMENT_CHANGE_LOAD_LENGTH 0       // Load filament length over hotend in mm
                                              // Longer length for bowden printers to fast load filament into whole bowden tube over the hotend,
                                              // Short or zero length for printers without bowden where loading is not used
  #define FILAMENT_CHANGE_EXTRUDE_FEEDRATE 3  // Extrude filament feedrate in mm/s - must be slower than load feedrate
  #define FILAMENT_CHANGE_EXTRUDE_LENGTH 50   // Extrude filament length in mm after filament is loaded over the hotend,
                                              // 0 to disable for manual extrusion
                                              // Filament can be extruded repeatedly from the filament exchange menu to fill the hotend,
                                              // or until outcoming filament color is not clear for filament color change
  #define FILAMENT_CHANGE_NOZZLE_TIMEOUT 45L  // Turn off nozzle if user doesn't change filament within this time limit in seconds
  #define FILAMENT_CHANGE_NUMBER_OF_ALERT_BEEPS  5L  // Number of alert beeps before printer goes quiet
  #define FILAMENT_CHANGE_NO_STEPPER_TIMEOUT         // Enable to have stepper motors hold position during filament change
                                                     // even if it takes longer than DEFAULT_STEPPER_DEACTIVE_TIME.
#endif
```

**Comment by ghost** [comment]
I will work on this later (if someone doesn't beat me to it). I have to get to work.

**Comment by ghost** [comment]
Probably should start a new issue for this anyway.

**Comment by mg0706** [comment]
Ok. Thanks. That was the only one i didn't download it. I will do try the rcbugfix. Hope you keep in mind what i said about the nozzle temp change for different filament. Thank you Tannoo for you help and patience.

**Comment by ghost** [comment]
No problem.

**Comment by Tannoo** [comment]
>Graphical display, I presume. Try changing this line in the `HOTEND_STATUS_ITEM` macro…
```
-         lcdDrawUpdate = LCDVIEW_CALL_NO_REDRAW; \
+         lcdDrawUpdate = LCDVIEW_CALL_REDRAW_NEXT; \
```
This worked. It never got corrected it in this PR.

**Comment by thinkyhead** [comment]
Great. I hope to have more time to work on Marlin going forward, now that I have a home.

**Pull request merged**
