### PR TITLE
Add 4th extruder

### PR DESCRIPTION
**Pull request by MagoKimbra**
Add code for 4th extruder....
I hope I have done everything right and not make a mistake ... Forgive me, but the changes are many ...

### CODE REVIEW

**Comment by thinkyhead** [comment]
Good work! I've looked over the changes. They seem correct and the formatting is reasonable. You should revert the changes you made to `Configuration.h` so this PR can be merged, and you might as well lose the changes to `ultralcd.h` also (because we're indenting compiler directives now).

**Comment by MagoKimbra** [comment]
I have to do the reverse of the changes, and put them back without configuration.h e ultralcd.h?
Excuse me, but I would not have misunderstood ..

**Comment by thinkyhead** [comment]
Since there are recent commits to the upstream Development branch, you will need to **rebase** your changes on Development. If you've already set up your **upstream** remote, then from the command line you can use the following commands:

```
cd path/to/Marlin
git fetch upstream
git checkout Development
git merge upstream/Development
git checkout 4th-extruders
git rebase Development
```

Once you've done this you can simply replace `Configuration.h` and `ultralcd.h` with their current counterparts in the MarlinFirmware/Marlin Development branch (download the Marlin zip and just copy them into your repo), then **commit** the changes and **sync** from the Github desktop app. The Pull Request will automatically be updated at that point.

**Comment by ErikZalm** [comment]
You added something to the adc interrupt. This changed the PID_dT.
Can you correct PID_dT?

**Comment by MagoKimbra** [comment]
Sorry ErikZalm i do not understand your request... Please can you be more explicit?

**Comment by ErikZalm** [comment]
You added 2 states to the temperature measurement interrupt.
To correct the PID calculations the PID_dT should be changed.
The PID_dT can now be found in configuration.h (But should be fixed and probably placed in temperature.h)
#define PID_dT ((OVERSAMPLENR \* 10.0)/(F_CPU / 64.0 / 256.0)) //sampling period of the temperature routine
If you change the 10.0 to 12.0 it is ok.

**Comment by MagoKimbra** [comment]
Ops sorry, when i merge my version with Marlin i forgot it...
But thinkyhead say me do not merge configuration.h...
How do I do now?

**Comment by ErikZalm** [comment]
This constant was placed in configuration.h by mistake.
Can you place it in temperature.h And remove it from configuration.h
I think you will need an #undef PID_dT first. (Many people do not update the configuration.h file. They use the old file)

**Comment by Natealus** [comment]
Good work MagoKimbra. Thanks for the updates. I'm going to try to merge the new changes made since release into my firmware and redo my configuration.h to make sure all the recent changes are in. I'm very excited for this new burst of Marlin development. Kudos to all you guys who are contributing and continue to work on this project! :)

**Comment by Natealus** [comment]
Just waiting for it to be verified and merged with development. :+1: :) Sorry I'm new to GitHub so I'm just starting to understand how it all works.

**Comment by thinkyhead** [comment]
All the additions look proper. I can't think of any other extruder-count-related items that you might have missed. So, with some optimism, I will merge this for testing.

**Comment by Natealus** [comment]
Awesome I'm going to download the dev branch and give her a try. Unfortunately I still need to get 3 more cold extruders printed before I can truly try it all. Right now I'm dealing with filament slip and grind issues with my ezstruder. I'm starting to think its a bad design. No way to adjust idler tension.

**Pull request merged**
