### PR TITLE
Longer3D LK1/2 (Alfawise U20/U20+/U30) board support

### PR DESCRIPTION
**Pull request by tpruvot**
note: the .py reloc script allow to flash via the sdcard (and to revert to stock firmwares)

If flashing with a stlink, this .py script should be commented but a chip backup is required to revert.

### CODE REVIEW

**Comment by tpruvot** [comment]
Note: remains some changes in Marlin/src/module/temperature.cpp to include to support open drain fan & heaters

**Comment by tpruvot** [comment]
Second note: the .py reloc script allow to flash via the sdcard (and to revert to stock firmwares)

If flashing with a stlink, this .py script should be commented but a chip backup may be required to revert.

**Comment by tpruvot** [comment]
@thinkyhead this ALFAWISE_UX0 define is a generic one i used to do quick fixes during dev..

maybe something more accurrate to "invert" all basic mosfets could be done... its more an electronic work method but not so unusal to boost heavy mosfets.. well invert is not the right word in this case

**Comment by tpruvot** [comment]
image

**Comment by tpruvot** [comment]
fail: https://travis-ci.org/tpruvot/Marlin/builds/558569071

**Comment by tpruvot** [comment]
hmm, forgot a file look like in the PR.. buildroot/share/PlatformIO/ldscripts/alfawise_Ux0.ld

**Comment by projectshort** [comment]
total noob when it comes to firmware i am more of a mechanical major 
i have had creality printers and updated via th3d but they do not have support for u20 
i already did the wiring with an octocupler but i cannot find and guide to update firmware to have ABL if you can help, that would be amazing 
tia

**Pull request merged**
