### PR TITLE
Fix for #1946

### PR DESCRIPTION
**Pull request by AnHardt**
Syntax error.

### CODE REVIEW

**Comment by AnHardt** [comment]
@Natealus 
Is it this what you intended?

**Comment by Natealus** [comment]
Yeah...I don't know C very well yet but what is the difference there? It accomplishes the same doesn't it? It compiled fine in my setup so I didn't know there was a syntax error.

I just separated that so I could define the temp leds independently of the rest of the LCD stuff. I was trying to isolate things to test performance issues. Usually you wouldn't have that temp stat led without a display but it works either way.

**Comment by Natealus** [comment]
@AnHardt And my setup is with an Azteeg X3 Pro so maybe I fumbled in X3?

**Comment by AnHardt** [comment]
#endif was before #elif. For the error see #1946.

**Comment by Natealus** [comment]
Ahhhh I see, that's my miss. Rookie miss lol.

**Pull request merged**
