### PR TITLE
Rename Wire in eeprom_if_i2c.cpp to fix compile error

### PR DESCRIPTION
**Pull request by ansonl**
### Description

Rename Wire to WireI2C in `eeprom_if_i2c.cpp`. When compile with I2C EEPROM with `#define EEPROM_SETTINGS` enabled for boards like BTT Octopus Pro, compiling `platformio run -e STM32F429ZG_btt_USB`. Variable name `Wire` is reused elsewhere

```
Linking .pio\build\STM32F429ZG_btt_USB\firmware.elf
c:/users/ansonl/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/STM32F429ZG_btt_USB/libbc1/libWire.a(Wire.cpp.o):(.bss.Wire+0x0): multiple definition of `Wire'; .pio/build/STM32F429ZG_btt_USB/src/src/HAL/shared/eeprom_if_i2c.cpp.o:C:\Users\ansonl\development\Marlin-bugfix-2.1.x-octopus/Marlin\src\HAL\shared/eeprom_if_i2c.cpp:36: first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\STM32F429ZG_btt_USB\firmware.elf] Error 1
```

This just renames the Wire variable name to avoid a naming conflict. 

### Requirements

Needs board with I2C EEPROM. 

### Benefits

Marlin will successfully compile when EEPROM storage is enabled. 

### Configurations

[BTT Octopus Pro Configuration_14apr23.zip](https://github.com/MarlinFirmware/Marlin/files/11238103/Configuration_14apr23.zip)

### CODE REVIEW

**Comment by ansonl** [comment]
CI compile fails, but I can only get eeprom_if_i2c.cpp to successfully compile locally after renaming `Wire`. I've tried this on both a Windows and Linux computer. I haven't found where Wire is being redefined yet.

**Comment by thinkyhead** [comment]
No problem compiling here with:
```
opt_set MOTHERBOARD BOARD_BTT_OCTOPUS_PRO_V1_0 SERIAL_PORT 1
opt_enable EEPROM_SETTINGS
mftest -a -n4 -y
```
Dependencies:
```
|-- SlowSoftI2CMaster @ 1.0.0
|-- SlowSoftWire @ 0.0.0+20230418193505 (https://github.com/felias-fogg/SlowSoftWire/archive/master.zip)
|-- IWatchdog @ 1.0.0
|-- SPI @ 1.0
|-- EEPROM @ 2.0.1
|-- SoftwareSerial @ 1.0
|-- Wire @ 1.0
|-- Servo @ 1.1.2
```
You can try resetting your environment by deleting your `.pio` and `$HOME/.platformio/.cache` folders and see if that helps.

**Comment by ansonl** [comment]
I tried emptying the cache and rebuilding and got the same error. 

My dependencies were similar:
```
|-- SlowSoftI2CMaster @ 1.0.0
|-- SlowSoftWire @ 0.0.0+20230419162554
|   |-- SlowSoftI2CMaster @ 1.0.0
|-- IWatchdog @ 1.0.0
|-- SPI @ 1.0
|-- EEPROM @ 2.0.1
|-- SoftwareSerial @ 1.0
|-- Wire @ 1.0
|-- Servo @ 1.1.2
```

`-v` gives me the same error message as before that references `Wire.cpp`. In the `Wire.cpp` file at `.platformio/packages/framework-arduinoststm32/libraries/Wire/src/Wire.cpp`, I think `Wire` is declared as a global variable of type TwoWire. The same global `Wire` declaration is in the Wire.cpp for other platforms. 

```
TwoWire Wire = TwoWire();
```

Wire.h has

```
extern TwoWire Wire;
```

`eeprom_if_i2c.cpp` does not pull in Wire if `SOFT_I2C_EEPROM` is enabled and instead declares the Wire variable after using SlowSoftWire.h. 

```
#if ENABLED(SOFT_I2C_EEPROM)
  #include <SlowSoftWire.h>
  SlowSoftWire Wire = SlowSoftWire(I2C_SDA_PIN, I2C_SCL_PIN, true);
#else
  #include <Wire.h>
#endif
```

Would this be a conflict that may not be caught in due to Wire library being pulled in through some other dependency since Wire is being used somewhere else as seen in the dependencies and build output?

**Comment by thinkyhead** [comment]
It's not at all clear why the conflict exists between your built `libbc1/libWire.a` and `eeprom_if_i2c.cpp.o`. For some reason in your build `SlowSoftWire` is wrongly seeing `SlowSoftI2CMaster` as a dependency, so perhaps this `SlowSoftI2CMaster` inclusion is causing the `<Wire>` library to be statically linked into `libWire.a`.

~~In general, we don't use `.a` prebuilt libraries, so it's also not clear why `libbc1/libWire.a` exists at all. Did you put something into the `lib` (not `libs`) folder within the Marlin sources?~~

Nevermind: I see `.a` files showed up on build.

**Comment by thinkyhead** [comment]
The odd thing is that unless symbols conflict within `eeprom_if_i2c.cpp` the linker shouldn't complain. It implies that both `Wire` and `SlowSoftWire` are being linked to this file. But only one of them should be, not both.

Perhaps you can compress your whole Marlin source package into a ZIP file for comparison, and we'll see if we can reproduce your result and find a proper explanation. I don't like to merge workaround patches without understanding root causes.

**Comment by ansonl** [comment]
Is the source package just the root repo folder once I've tried to compile the project? Or do you need anything from ~/.platformio

**Comment by thinkyhead** [comment]
> Is the source package just the root repo folder once I've tried to compile the project?

If you have a second computer, and you still see the issue when you try to compile a copy of your Marlin Firmware project folder on that computer too, then we only need your firmware package. If, however, you only see the issue on one system, or you only have one system, then it may turn out that we need more.

So you should just send your firmware package first, and if that builds here without issue, then we can get the problematic things from your `$HOME/.platformio` folder as a followup. I presume you've already tried the complete deletion of the `.pio` (and old `.piolibdeps`) folders, but after a build that exhibits the problem the `.pio` folder may also contain clues, so I may ask for that as well.

When we get to the point of checking `.platformio`, then it will be good if you can delete or temporarily move items from your `$HOME/.platformio` folder that we don't need — so you'll just send me the contents that are required to compile and contribute to the problem you're seeing. I can then replace my `.platformio` folder with yours and see what happens.

**Comment by ansonl** [comment]
@thinkyhead I uploaded the archive and messaged you the link on the Marlin Discord.

**Comment by thinkyhead** [comment]
So sure enough, this is a conflict that occurs when `I2C_EEPROM` plus `SOFT_I2C_EEPROM` is used with any other i2c feature. It must have been a rare occurrence up to now. I still find it strange, and I can't find any compiler flag(s) that will prevent the error. It might be that any such flags would produce a larger build, anyway. So this PR seems to be the best solution available. Thanks for bringing the patch!

**Pull request merged**
