### PR TITLE
[2.0.x] TMC2130 support for LPC platform

### PR DESCRIPTION
**Pull request by teemuatlut**
Utilize the new SW SPI implementation in library version 1.1.0 (not currently released yet).
There's a mockup SPI class included but that's mostly for show and for compiling purposes. It might work though. @Bob-the-Kuhn supposedly is working on a proper polished SPI implementation.

~~Default CS pins are located on J5 header. Default SPI pins are on the ETH header.~~
All default pins are in the ETH header.

### CODE REVIEW

**Comment by teemuatlut** [comment]
I don't think the TMC library is finding the Arduino.h file because it resides in Marlin and not in the LPC core.

Compiles fine on my computer.

**Comment by Bob-the-Kuhn** [comment]
I wouldn't call it polished.

The LPC1768 version is working.  Next is AVR.

Here's the API for it:
```c
/**
 * create_logical_spi_channel 
 *
 *   returns logical channel number, -1 if out of channels
 *
 *   spi_channel
 *    1 - hardware controller used for LCD's SD card
 *    2+ - hardware controller, system dependent
 *
 *  cs_pin -  chip select pin, -1 if app will control chip select
 *  cs_polarity - 1 if active high, 0 if active lower_bound
 *  frequency in Hz for the SPI clock
 *  spi_mode - 0-3
 *  SCK (software SPI only)
 *  MOSI (software SPI only)
 *  MISO (software SPI only)
 *
 */

// hardware SPI
int8_t create_logical_spi_channel(int8_t spi_channel, pin_t cs_pin, bool cs_polarity, uint32_t frequency, uint8_t spi_mode);

// software SPI
int8_t create_logical_spi_channel(pin_t SCK, pin_t MOSI, pin_t MISO, pin_t cs, bool cs_polarity, uint32_t frequency, uint8_t spi_mode);

void read(uint8_t channel, uint8_t *buffer, uint32_t length);
uint8_t read(uint8_t channel);

void write(uint8_t channel, const uint8_t *buffer, uint32_t length);
void write(uint8_t channel, uint8_t value);

void transfer(uint8_t channel, const uint8_t *buffer_write, uint8_t *buffer_read, uint32_t length);
uint8_t transfer(uint8_t channel, uint8_t value);

// change SPI frequency for specified channel
void set_frequency(int8_t channel, uint32_t frequency);
```

**Comment by psavva** [comment]
Bob, will this include the beginTransaction and endTransaction method similar to the Arduino implementation?

**Comment by teemuatlut** [comment]
@Bob-the-Kuhn That doesn't look like an API I'll be able to use for something outside Marlin. I don't want to cater to a specific platform when everything else follows Arduino/AVR style.

**Comment by Bob-the-Kuhn** [comment]
@psavva - it originally had beginTransaction and endTransaction but the U8G library doesn't use anything similar.  There are similar calls but they aren't used in at least the one case I converted.  I needed to make it work without those functions so i just dropped them.

@teemuatlut - but, but, ... everything I do is perfect ... it's the world that isn't perfect 😉

Seriously, what API do you envision?  More importantly, how does the system keep the settings for one application distinct from another's?

**Comment by teemuatlut** [comment]
Just parity with the Arduino/Teensy/Due core [SPI class](https://www.arduino.cc/en/Reference/SPI). Nothing more, nothing less.

More specifically I'm looking for methods for
```cpp
uint8_t transfer(uint8_t)
uint16_t transfer(uint16_t)
void begin(void)
You can even add dummies for
void beginTransaction(SPISettings)
void endTransaction()
```
These are all "defined" (in a somewhat loose sense) in the SPIClass included in this PR. But I think the proper way would be that the actual implementation would be in the class methods and then the functions Marlin uses would refer to the SPI class methods. This is how the [Teensy HAL](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_TEENSY35_36/HAL_spi_Teensy.cpp#L81) is done.

Curious, did the U8G library use the setBitOrder or setClockDivider calls? The Arduino reference pages at least advises against using them in new projects.

Maybe this is what you asked, but the way different SPI libraries are differentiated from each other is that each platform has ITS (@thinkyhead) own SPI library. Basically every core has a dedicated library folder that only applies to it alone.

**Comment by p3p** [comment]
@Bob-the-Kuhn The Arduino world isn't perfect that's the issue here ^^ If Arduino supplied us with a single entry point to SPI that every library maker used life would be simple.

@teemuatlut Marlin is not that simple, how do we control the ever increasing multitude of devices that want to transfer data over SPI on arbitrary hardware/software pins without centralising an api to control the channels? what if 2 unrelated devices need to both use the hardware spi .. 

Library developers do not need to use this api, they just need to use the age old system of embedded design of supplying the appropriate functions to implement that override the communication interface. 

Arduino makes simple things easier. .. and Marlin level projects a pain in the arse.

**Comment by teemuatlut** [comment]
> Library developers do not need to use this api

That's just it, I want to use an interface that is common to all platforms! And currently that does not exist for the LPC core that Marlin uses.
It really doesn't matter how you implement the class in the end, as long as it is API compatible with the others. And if you want you can add additional functionality like channel selection with extra class methods. I think that's how the Teensy SPI library accomplishes this.

**Comment by Bob-the-Kuhn** [comment]
If all the SPI users had the same settings then the Arduino system would be adequate.

As an example on the LPC1768 the RepRap Discount Full Graphics LCD uses the hardware SPI at 1MHZ mode 3 while the SD card uses it at 8MHz mode 0.  

The LPC1768 hardware SPI doesn't support bit order so I wasn't planning on supporting it. 

There is a change frequency call.  The SD card uses it.

**Comment by teemuatlut** [comment]
Create SPISettings object variables for each device:
`SPISettings SPI_settings_LCD = SPISettings(1000000, MSBFIRST, SPI_MODE3)`
`SPISettings SPI_settings_SD = SPISettings(8000000, MSBFIRST, SPI_MODE0)`
Call
`SPI.beginTransaction(SPI_settings_LCD)`
`SPI.beginTransaction(SPI_settings_SD)`.

https://www.arduino.cc/en/Reference/SPISettings
"If any of your settings are variables, you may create a SPISettings object to hold the 3 settings. Then you can give the object name to SPI.beginTransaction(). Creating a named SPISettings object may be more efficient when your settings are not constants, especially if the maximum speed is a variable computed or configured, rather than a number you type directly into your sketch."

**Comment by p3p** [comment]
This spi manager interface isn't designed to fix the LPC Core missing an SPI class implementation, that was just my omission back when I was throwing it together because I only used displays and sdcard and neither of those device drivers used the class, it does help performance though on the LPC1768 because of the control it gives us.

It will be impossible to support libraries with this method though, well on platforms we don't control the SPI class anyway. The main part of the manager is the ability to arbitrarily use any hardware, or software ports(using any pin) defined for a Platform, does Arduino supply any api for switching the active SPI port?

**Comment by teemuatlut** [comment]
I don't think the DUE library has any functionality to select the SPI port.
Paul's [Teensy library](https://www.pjrc.com/teensy/td_libs_SPI.html) has methods for selecting the MOSI/MISO/SCK lines.

How do you propose the TMC library should be talking to the drivers if the LPC core wouldn't provide a working SPIClass?

**Comment by p3p** [comment]
Marlin obviously can't expect authors to modify their libraries, so the Arduino SPI class should be there for them to interface with, this manager would need to be for internal use only .. this is why my implementation stalled, (the complications with libraries, AVR compat .. ect). If we could always have control of the SPI class it we could redirect the library to the correct SPI port / software implementation .. but on Arduino platforms we cant do that, I have no idea how to do this properly without control of the interface layer or with the API that Arduino supplies.

**Comment by teemuatlut** [comment]
Could the manager be baked into the LPC SPIClass? Just in a way that if there are no parameters provided (like an external library would call everything), then it would use some default channel. Only Marlin would need to know about the extra features.

**Comment by revilor** [comment]
@teemuatlut Would it be possible to refactor your SPIClass into something like

class SPIInterface {
public:
virtual uint8_t transfer(uint8_t);
virtual uint16_t transfer(uint16_t);
virtual void beginTransaction(SPISettings);
virtual void endTransaction();
...
}

and provide a constructor like

TMC2130(SPIInterface &spi, ...)

This way any user of your library would be able to inject his SPI implementation without the need to modify the library. 

The standard implementation of SPIInterface could just pass all calls through to Arduino SPI. And for Marlin it would be possible to implement SPIInterface using the HAL SPI functions.

**Comment by teemuatlut** [comment]
It would be possible to have the constructor take in an SPI object.
However, if the SPIInterface is declared and defined outside of the library, like by the application (Marlin), how then would the library know about the datatype SPIInterface. It can't have a header include because that's not always available.
It might be possible for the library to declare an abstract interface class that needs to be overriden by the application and that then can be passed as a constructor argument. (Am I close to getting what you mean?)
Or the argument could be of type SPIClass as that is the closest thing to a universal datatype for these. Then the application can (?) use inheritance to modify what it needs to.

Edit: [Slightly](http://marlinfw.org/docs/development/coding_standards.html#language-features) related to using virtual functions. I don't know how well those hold anymore though.

**Comment by revilor** [comment]
> It might be possible for the library to declare an abstract interface class that needs to be overriden by the application and that then can be passed as a constructor argument. (Am I close to getting what you mean?)

@teemuatlut  Yes, that kind of was the idea. Provide a possibility to replace/overwrite the default SPI implementation used by the library with something different if there is a need to.

**Comment by Bob-the-Kuhn** [comment]
Here's the SPI stuff I found in the TMC26xStepper.cpp file:
```
  SPI.setBitOrder(MSBFIRST);
  SPI.setClockDivider(SPI_CLOCK_DIV8);
  SPI.begin();
  SPI.setDataMode(SPI_MODE3);
  SPI.transfer((datagram >> 16) & 0xff);
  AVR specific items like SPCR & SPI_MODE_MASK;
```

The aim of the SPI manager is to route all SPI stuff through it.  To me that would mean it should be invoked if present and if not do the other options.

An option I see is:

a) change all the SPI.xxx to TMC_SPI.xxx

b) change the beginning of TMC26XStepper.cpp to something like this
```
#ifdef SPI_MANAGER
  #include <TMC_SPI.h>
#else
  #if defined(ARDUINO) && ARDUINO >= 100
    #include <Arduino.h>
  #else
    #include <WProgram.h>
  #endif
  #include <SPI.h>
  #define TMC_SPI   SPI
#endif  
```

c) TMC_SPI.h would look something like this (assuming SPI.begin() is only called once)

```
#define SPCR 0
#define SPI_MODE_MASK 0
...

#define TMC_SPI_FREQUENCY 2000000  // haven't looked at what the TMC library wants
#define TMC_SPI_MODE      3 


class TMC_SPI {
  private:
    uint8_t   TMC_SPI_channel; 
  public:
    void setBitOrder(uint8_t MSBFIRST) {} 
    
    void setClockDivider(uint8_t SPI_CLOCK_DIV8) {}
    
    void begin() { 
      // SD card hardware SPI, app controls chip select
      TMC_SPI_channel = HAL::SPI::create_logical_spi_channel(1, -1,-1, TMC_SPI_FREQUENCY, TMC_SPI_MODE ) {
    }  
    void setDataMode(uint8_t SPI_MODE3) {}
    
    void transfer(uint8_t data) {HAL::SPI::write(TMC_SPI_channel, data);
};

```

**Comment by teemuatlut** [comment]
I think the very first assumption you need to make is that you cannot modify the external code.
That TMC260XStepper is quite an old library from 2012.
You also need to remember that Marlin isn't the only thing utilizing these libraries so it's only the LPC core that needs an SPI class.

Also I really don't like naming _anything_ to TMC_SPI. The goal is to make a universally compatible SPI class and not something specific to the TMC drivers.

**Comment by thinkyhead** [comment]
> The goal is to make a universally compatible SPI class and not something specific to the TMC drivers.

Sounds like a perfect job for a wrapper (pass-thru) class with glue code. The wrapper class has the same interfaces on all platforms. And it's best if it conforms to an existing, well-established API (namely, the AVR version of the SPI class, if possible).

**Comment by psavva** [comment]
@teemuatlut, I guess i have to test your branch to confirm if things work? 
https://github.com/teemuatlut/Marlin/tree/LPC_TMC2130?files=1

**Comment by Bob-the-Kuhn** [comment]
I've been able to see a TMC2130 respond (MISO is active) to the power up init sequence using the following change to TMC2130Stepper.cpp:
```
#ifndef SPI_MANAGER
  #ifdef ARDUINO_SAM_ARCHIM
    #include "SW_SPI.h"
    SW_SPI TMC_SPI = SW_SPI(); // Default: MOSI=28, MISO=26, SCK=27
  #else
    #include <SPI.h>
    #define TMC_SPI SPI
  #endif
#else
  #include <TMC_SPI.h>
#endif  
```

I haven't been able to see any communication when using the M906 command.  As far as I can tell the Marlin 2.0.x Mxxx commands for the TMC2130 are seriously screwed up.  It was a major effort just to get M906 to say "hello world".  I'm sure that I don't have the getcurrent & setcurrent linked in properly.

----

> it's only the LPC core that needs an SPI class

For the short term we could do something for the LPC similar to what you've done for the Due.  Converting Marlin to a SPI manager is a long way off so having a LPC SPI class sometime soon makes sense.  

In the long run some type of logical channel system is coming.  The heart of such a system is being able to identify who is wanting to use the common resource.  Since there isn't a system yet in place, the best I can hope for is to have some linkage mechanism that uniquely identifies the user but is generic enough that a future system can use it.  That's the aim of the `#include <TMC_SPI.h>` part in the above.

**Comment by teemuatlut** [comment]
TMC commands in the 2.0.x branch were fixed already.
SW SPI in the library was made available to all platforms.
This PR is capable of initiating and communicating with the drivers. Movements work and all the TMC specific commands work.

@psavva You don't _have_ to but it would be nice for someone to confirm that this works.

**Comment by psavva** [comment]
@teemuatlut, LOL. You know what i mean...

**Comment by psavva** [comment]
@teemuatlut I have compiled without TMC_DEBUG, and it compiled OK.
Next step was to check parameters, so I tried 
M122 
M122 S0 
M122 S1
I only get the Response OK.
No actual debug info.

I then figured that I will need TMC_DEBUG?  I went to enable it, and I cannot compile your branch:
Compiling .pioenvs\LPC1768\src\src\gcode\bedlevel\mbl\G29.o
Marlin\src\feature\tmc_util.cpp: In instantiation of 'void tmc_status(TMC&, TMC_AxisEnum, TMC_debug_enum, float) [with TMC = TMC2130Stepper]':
Marlin\src\feature\tmc_util.cpp:412:71:   required from here
Marlin\src\feature\tmc_util.cpp:379:24: error: second operand to the conditional operator is of type 'void', but the third operand is neither a throw-expression nor of type 'void'

tpwmthrs_val ? SERIAL_ECHO(12650000UL * st.microsteps() / (256 * tpwmthrs_val * spmm)) : SERIAL_CHAR('-');
 
*** [.pioenvs\LPC1768\src\src\feature\tmc_util.o] Error 1


This is the latest branch of:https://github.com/teemuatlut/Marlin/tree/LPC_TMC2130
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/1626184/Configs.zip)

No Changes to PINS or any other file ( I think :) )

**Comment by psavva** [comment]
I changed the line:
`tpwmthrs_val ? SERIAL_ECHO(12650000UL * st.microsteps() / (256 * tpwmthrs_val * spmm)) : SERIAL_CHAR('-');`
to
`tpwmthrs_val ? SERIAL_ECHO(12650000UL * st.microsteps() / (256 * tpwmthrs_val * spmm)) : SERIAL_ECHO('-');`

Then it Compiles.
I'm not sure if that would be the proper solution... Since it will only output -, not knowing if there is a return character intended or not... Anycase, I'll let @teemuatlut decide how to fix that :)

This is the Output after 
M122 S0
M122 S1
M122


17:06:16.058 : N22 M122 S0*81
17:06:16.058 : ok
17:06:18.724 : N23 M122 S1*81
17:06:18.727 : axis:pwm_scale |status_response|
17:06:18.727 : ok
17:06:21.072 : N24 M122*20
17:06:21.073 : X	Y	Z	E0
17:06:21.076 : Enabled		false	false	false	false
17:06:21.078 : Set current	800	800	800	800
17:06:21.088 : RMS current
17:06:21.110 : MAX current	2024.760000	2024.760000	2024.760000	2024.760000
17:06:21.113 : Run current	25/31	25/31	25/31	25/31
17:06:21.116 : Hold current	12/31	12/31	12/31	12/31
17:06:21.134 : CS actual		0/31	0/31	0/31	0/31
17:06:21.151 : PWM scale	0	0	0	0
17:06:21.161 : vsense		0=.325	0=.325	0=.325	0=.325
17:06:21.170 : stealthChop	false	false	false	false
17:06:21.187 : msteps		256	256	256	256
17:06:21.204 : tstep		0	0	0	0
17:06:21.204 : pwm
17:06:21.206 : threshold		0	0	0	0
17:06:21.207 : [mm/s]		-	-	-	-
17:06:21.217 : OT prewarn	false	false	false	false
17:06:21.218 : OT prewarn has
17:06:21.221 : been triggered	false	false	false	false
17:06:21.238 : off time		0	0	0	0
17:06:21.255 : blank time	16	16	16	16
17:06:21.256 : hysterisis
17:06:21.272 : -end		-3	-3	-3	-3
17:06:21.288 : -start		1	1	1	1
17:06:21.290 : Stallguard thrs	0	0	0	0
17:06:21.292 : DRVSTATUS	X	Y	Z	E0
17:06:21.301 : stallguard
17:06:21.318 : sg_result		0	0	0	0
17:06:21.326 : fsactive
17:06:21.334 : stst
17:06:21.342 : olb
17:06:21.349 : ola
17:06:21.358 : s2gb
17:06:21.366 : s2ga
17:06:21.374 : otpw
17:06:21.382 : ot
17:06:21.392 : Driver registers:	X = 0x       0       0:       0       0:       0       0:       0       0
17:06:21.400 : Y = 0x       0       0:       0       0:       0       0:       0       0
17:06:21.408 : Z = 0x       0       0:       0       0:       0       0:       0       0
17:06:21.417 : E0 = 0x       0       0:       0       0:       0       0:       0       0
17:06:21.417 : ok

**Comment by teemuatlut** [comment]
Your drivers are all reporting all zeros. That shouldn't be the case.
Do your steppers move?

**Comment by psavva** [comment]
They're not yet connected.  In have to take it to my dungeon later to test
:)

**Comment by teemuatlut** [comment]
Can you attach an image of your wiring? I'd like to know if the communication error is software or hardware.

**Comment by psavva** [comment]
img_20180112_180224
img_20180112_180239
img_20180112_180216

**Comment by teemuatlut** [comment]
I think your MOSI (gray) and MISO (green) are switched.

**Comment by Bob-the-Kuhn** [comment]
> Sounds like a perfect job for a wrapper (pass-thru) class with glue code. The wrapper class has the same interfaces on all platforms. And it's best if it conforms to an existing, well-established API (namely, the AVR version of the SPI class, if possible).

@thinkyhead - sanity check.  Chris & I are exploring a channel based SPI manager for Marlin.  Does this fit in with your ideas/wishes?

**Comment by Bob-the-Kuhn** [comment]
I just tried the https://github.com/teemuatlut/Marlin/tree/LPC_TMC2130 branch.  I did the M122 S0, M122 S1 and M122 sequence but got no response.

I can see the MISO & MOSI lines toggle on power up and I do see them toggle when I issue M906 X1200.  I didn't see them toggle when I issued the M122 sequence nor when I issued M906.

**Comment by Bob-the-Kuhn** [comment]
☹️ I was using an out of date copy of the TMC2130 library when I was doing my logical channel playing.  

🙂 I'll switch over & do some more playing.

**Comment by teemuatlut** [comment]
M122 should still output something even if the communication wouldn't work. Did you enable `TMC_DEBUG`? I can't believe we still don't have a message for unrecognized M code. There's just an error case if the command is not G, M or T.

**Comment by psavva** [comment]
1st pin on the left of stepper = SDI is MISO = Green which maps to pin P1_08 

#if ENABLED(TMC_USE_SW_SPI)
  #define TMC_SW_MOSI      P1_00  // ETH
  #define TMC_SW_MISO      P1_08  // ETH
  #define TMC_SW_SCK       P1_09  // ETH
#endif
screenshot_20180112-200228_01
screenshot_20180112-200630_01

Looks like have it wired correctly, No?

**Comment by Bob-the-Kuhn** [comment]
RTFM - what a novel concept - still have trouble with that 

TMC_DEBUG did it.  Below is the output.  

```
12:04:09.642 : N15 M122 S0*85
12:04:14.258 : N16 M122 S1*87
12:04:14.259 : axis:pwm_scale |status_response|
12:04:39.371 : N17 M122*20
12:04:39.372 : X
12:04:39.372 : Enabled		false
12:04:39.373 : Set current	800
12:04:39.374 : RMS current
12:04:39.375 : MAX current	1120.950000
12:04:39.376 : Run current	25/31
12:04:39.376 : Hold current	12/31
12:04:39.377 : CS actual		12/31
12:04:39.377 : PWM scale	0
12:04:39.378 : vsense		1=.18
12:04:39.379 : stealthChop	true
12:04:39.379 : msteps		16
12:04:39.380 : tstep		1048575
12:04:39.380 : pwm
12:04:39.380 : threshold		0
12:04:39.381 : [mm/s]		-
12:04:39.381 : OT prewarn	false
12:04:39.382 : OT prewarn has
12:04:39.383 : been triggered	false
12:04:39.384 : off time		5
12:04:39.384 : blank time	24
12:04:39.384 : hysterisis
12:04:39.385 : -end		2
12:04:39.385 : -start		3
12:04:39.386 : Stallguard thrs	0
12:04:39.386 : DRVSTATUS	X
12:04:39.386 : stallguard
12:04:39.387 : sg_result		0
12:04:39.387 : fsactive
12:04:39.388 : stst		X
12:04:39.388 : olb
12:04:39.388 : ola
12:04:39.388 : s2gb
12:04:39.389 : s2ga
12:04:39.389 : otpw
12:04:39.389 : ot
12:04:39.393 : Driver registers:	X = 0x       8       0:       0       C:       0       0:       0       0
```

**Comment by Bob-the-Kuhn** [comment]
SDO goes to MISO, SDI goes to MOSI.  You'll need to swap your defines.

**Comment by teemuatlut** [comment]
That looks about right. Not sure why RMS current is missing though when everything else looks ok.
The S0 or S1 arguments are to enable automatic reporting of PWM_SCALE value.

And as you can see, there's some formatting issue with printing the register raw value. But it's only present on the LPC platform.

**Comment by Bob-the-Kuhn** [comment]
I was surprised that the compiler complained about  SERIAL_CHAR not having the same type as SERIAL_ECHO.  SURPRISE!!!  The compiler was correct.  SERIAL_CHAR(x) boils down to MYSERIAL0.write(x) while SERIAL_ECHO(x) winds up as MYSERIAL0.print(x).

On a conditional it matters.  If it had been If (...) then it wouldn't have.

----

FYI - I tried the TMC_USE_SW_SPI and it works fine.

**Comment by psavva** [comment]
I'll fix it and try again..

**Comment by teemuatlut** [comment]
Ye I had to fix that as well. The echo -> char changes were part of a recent PR that was merged.

I don't know if the "HW" LPC SPI works properly. The SPIClass that is included in this just redirects the calls to the already existing SPI functions. It would be great if it worked as that would allow Marlin to define the SPI calls and achieve better speeds. The SW SPI inside the library just bit bangs using digital writes, but with the upside that it should work for just about any platform.

**Comment by Bob-the-Kuhn** [comment]
I tried it with TMC_USE_SW_SPI enabled & disabled and both worked.

**Comment by psavva** [comment]
@Bob-the-Kuhn @teemuatlut , I now need some help.

I swapped my Mosi/Miso wires on the Ethernet Header.
Now it's Green, Gray, Red

I am still getting 0x00 for all driver statuses...

Driver registers:
X = 0x00:00:00:00
Y = 0x00:00:00:00
Z = 0x00:00:00:00
E0 = 0x00:00:00:00

help?

**Comment by psavva** [comment]
I will first double check my wiring, and try with 1 stepper, and see what happens...  Then try two if one works...

**Comment by psavva** [comment]
I'm not able to get a single stepper working :(
```
22:10:59.095 : N15 M122*22
22:10:59.096 : X
22:10:59.097 : Enabled		false
22:10:59.098 : Set current	800
22:10:59.101 : RMS current
22:10:59.108 : MAX current	2024.760000
22:10:59.109 : Run current	25/31
22:10:59.111 : Hold current	12/31
22:10:59.117 : CS actual		0/31
22:10:59.121 : PWM scale	0
22:10:59.125 : vsense		0=.325
22:10:59.128 : stealthChop	false
22:10:59.132 : msteps		256
22:10:59.137 : tstep		0
22:10:59.137 : pwm
22:10:59.138 : threshold		0
22:10:59.139 : [mm/s]		-
22:10:59.142 : OT prewarn	false
22:10:59.144 : OT prewarn has
22:10:59.145 : been triggered	false
22:10:59.150 : off time		0
22:10:59.155 : blank time	16
22:10:59.156 : hysterisis
22:10:59.160 : -end		-3
22:10:59.165 : -start		1
22:10:59.166 : Stallguard thrs	0
22:10:59.167 : DRVSTATUS	X
22:10:59.170 : stallguard
22:10:59.175 : sg_result		0
22:10:59.177 : fsactive
22:10:59.180 : stst
22:10:59.182 : olb
22:10:59.184 : ola
22:10:59.186 : s2gb
22:10:59.188 : s2ga
22:10:59.191 : otpw
22:10:59.193 : ot
22:10:59.203 : Driver registers:	X = 0x       0       0:       0       0:       0       0:       0       0
22:10:59.203 : ok
22:11:02.567 : N16 M122*21
22:11:02.586 : X
22:11:02.588 : Enabled		false
22:11:02.589 : Set current	800
22:11:02.592 : RMS current
22:11:02.599 : MAX current	2024.760000
22:11:02.601 : Run current	25/31
22:11:02.602 : Hold current	12/31
22:11:02.607 : CS actual		0/31
22:11:02.612 : PWM scale	0
22:11:02.615 : vsense		0=.325
22:11:02.619 : stealthChop	false
22:11:02.623 : msteps		256
22:11:02.628 : tstep		0
22:11:02.628 : pwm
22:11:02.629 : threshold		0
22:11:02.630 : [mm/s]		-
22:11:02.633 : OT prewarn	false
22:11:02.634 : OT prewarn has
22:11:02.636 : been triggered	false
22:11:02.641 : off time		0
22:11:02.646 : blank time	16
22:11:02.647 : hysterisis
22:11:02.651 : -end		-3
22:11:02.655 : -start		1
22:11:02.657 : Stallguard thrs	0
22:11:02.658 : DRVSTATUS	X
22:11:02.661 : stallguard
22:11:02.665 : sg_result		0
22:11:02.668 : fsactive
22:11:02.670 : stst
22:11:02.672 : olb
22:11:02.674 : ola
22:11:02.677 : s2gb
22:11:02.678 : s2ga
22:11:02.681 : otpw
22:11:02.683 : ot
22:11:02.692 : Driver registers:	X = 0x       0       0:       0       0:       0       0:       0       0
22:11:02.692 : ok
```

**Comment by teemuatlut** [comment]
You said that you have the board unattached to a printer because you are just testing for now. Do you have 12V applied to the board? The driver needs this high voltage to function in any manner.

**Comment by psavva** [comment]
USB only... I'll have to then hook it up to 12V power supply as well.. Looks like this is a job for tomorrow :)
@teemuatlut  Thanks for pointing that out.

**Comment by psavva** [comment]
@teemuatlut @thinkyhead 
Given we have had multiple developers confirm that the TMC SPI Implementation is working, I'm proposing that we merge this Pull Request for a broader audience to test and confirm.  

Remember that one change that is needed in order to have the branch compile with TMC_DEBUG Enabled.

```
Marlin\src\feature\tmc_util.cpp:379:24: error: second operand to the conditional operator is of type 'void', but the third operand is neither a throw-expression nor of type 'void'

tpwmthrs_val ? SERIAL_ECHO(12650000UL * st.microsteps() / (256 * tpwmthrs_val * spmm)) : SERIAL_CHAR('-');
```

**Comment by psavva** [comment]
@teemuatlut, Any idea how to fix the travis build?  It's due to the Arduino.h file being included, but cannot be found in travis..

**Comment by teemuatlut** [comment]
It might be the recent change to use the dev version of PIO for Travis.
Maybe the newer version works more like Arduino IDE where `include ""` means from the sketch folders and `include <>` means from the core or libraries.
Maybe it might work if I add this to the library. Maybe.
```cpp
#ifdef ARDUINO
  #include <Arduino.h>
#endif
```
The fact is that it's building fine locally but Travis PIO has trouble with it.

**Comment by teemuatlut** [comment]
I restored the conditional include to the library but it'll take a while before PIO will decide to use that version.

**Comment by psavva** [comment]
@thinkyhead , Travis is now passing, please can you get this merged the soonest possible?

**Comment by psavva** [comment]
I confirm that I have also tested the Software SPI and it's working as expected.
I'm able to control the steppers just fine.

**Comment by thinkyhead** [comment]
> Travis is now passing

Remember, for PRs made ahead of newer changes "passing" is meaningless without a REBASE.

Something merged after this PR was posted was causing errors. Apparently the defines for `MSBFIRST` and `LSBFIRST` are needed for the Trinamic_TMC2130 library, and LPC wasn't defining them. I've added them to LPC `Arduino.h`.

**Comment by Bob-the-Kuhn** [comment]
@teemuatlut  - The TMC software is the only place that has **MSBFIRST** defined as 0.  All the Arduino libraries define it as 1.  Is it a big deal to to change it to the Arduino definition?

**Comment by teemuatlut** [comment]
I had to remove the `MSBFIRST` definition from the library because of Due compatibility. The `#ifndef` I had used doesn't catch the enumerated type that SAM core uses.
So you can change it to 0 or 1 or to an arbitrary number as long as it works for that particular platform and SPI implementation. The TMC library will just compare the argument to what is defined as `MSBFIRST` in the core.
Atm anyway it's defined in two places; `LPC_SPI.h` and (LPC core) `Arduino.h`. Should be safe to remove from the former.

**Comment by Bob-the-Kuhn** [comment]
What about the one in TMC2130Stepper_ID1493\src\source\SW_SPI.h ?

**Comment by teemuatlut** [comment]
[Removed](https://github.com/teemuatlut/TMC2130Stepper/blob/v2.1.4/src/source/SW_SPI.h). Update your library.

**Comment by thinkyhead** [comment]
Updated, thanks!

**Pull request merged**
