### PR TITLE
Remove BTT SKR Mini 512K "RCT6" Environments

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description
As part of the STM32F1 -> STM32 HAL migration, I think it'd be a good idea to remove the 512k "RCT6" environments which allowed users to overflash 256k chips at the potential risk of lockups or other unexplainable (and potentially unsafe) scenarios.

Initial reports (https://github.com/MarlinFirmware/Marlin/pull/15890) were good, but long-term testing has shown these environments to not be stable for everyone.

### Benefits
Safer firmware.

### Related Issues
Probably some in the queue that were related, though most of the headaches come from STM32F1/maple/timer conflicts.

### CODE REVIEW

**Comment by GhostlyCrowd** [comment]
There are legitimate Mini boards out there with 512k RE chips on them,   also Gonna be a lot of people complaining when you give something and then take it away.   the DIP and the Mini V1.2 have RET6 in the wild. 

I think its a better idea just to consider the over provisioning unsupported and discard any bug reports when its in use, since this seems to be your end goal is to not have reports that are relative to overprovisioning.

**Comment by thisiskeithb** [comment]
> There are legitimate Mini boards out there with 512k RE chips on them

This PR doesn’t remove the RE environments, so users can still compile for those boards just as before.


> Gonna be a lot of people complaining when you give something and then take it away

I fully expect that, but this is about safer firmware.

> I think its a better idea just to consider the over provisioning unsupported and discard any bug reports when its in use

We already do, but see my comment above.

**Comment by GhostlyCrowd** [comment]
> This PR doesn’t remove the RE environments, so users can still compile for those boards just as before.

I guess my concern was that 512k is being removed in the new stm32 platform with out the BTT RET6 existing at all.  ellensp's pr didnt include it when he refactored to separate maple from stm32 in the ini.  stmf1.ini only includes RET6 Creality targets, not SKR Mini. Unless im missing it some where.

I see he has a pr  to get some RE stuff back in, Looks like  STM32F103RE_btt and  STM32F103RE_btt_USB (USB mass storage) are not there yet, ill mention it

**Comment by thisiskeithb** [comment]
> I guess my concern was that 512k is being removed in the new stm32 platform with out the BTT RET6 existing at all

The migration is still happening, but that’s outside the scope of this PR.

**Comment by ellensp** [comment]
@GhostlyCrowd no BTT env have been modified. (yet) well not by me..  
Yes the maple env:STM32F103RE vanished, in error (thanks thinkyhead) 
But Im bringing it back in the next PR https://github.com/MarlinFirmware/Marlin/pull/22019

**Comment by GhostlyCrowd** [comment]
> @GhostlyCrowd no BTT env have been modified. (yet)
> Yes the maple env:STM32F103RE vanished, in error (thanks thinkyhead)
> But Im bringing it back in the next PR #22019

I saw, thanks :) 

> The migration is still happening, but that’s outside the scope of this PR.

Right but my concern was existing targets  vanished in the migration so  if we remove 512K now,  people like me for example will be left with out a suitable build target.  Which is why I brought this up here.

Either im missing it entirely or im confused but there is no  STM32F103RE_btt and STM32F103RE_btt_USB  targets in the stm32f1.ini yet only in the maple.

**Comment by thisiskeithb** [comment]
> Either im missing it entirely or im confused but there is no STM32F103RE_btt and STM32F103RE_btt_USB targets in the stm32f1.ini yet only in the maple.

Again, those changes have nothing to do with this PR.

Have you reviewed the changes in this PR? https://github.com/MarlinFirmware/Marlin/pull/22022/files

Please see the PR linked by ellensp for RE fixes.

You can still compile with `STM32F103RE_btt` or `STM32F103RE_btt_usb`:

https://github.com/MarlinFirmware/Marlin/blob/b99411b62b6c21aee64f5d33ef5cbee4b701dc68/ini/stm32f1-maple.ini#L157-L177

**Comment by GhostlyCrowd** [comment]
I can tell you're getting frustrated.....

Going back to the maple platform will reintroduce bugs for me.  Your edits to stm32f1.ini will break the work around of compiling RC 512k for RE target. 

You even say your self...
> Probably some in the queue that were related, though most of the headaches come from STM32F1/maple/timer conflicts.

We have had this conversation before when you have brought this up, and i said I use it, and you said well use the RE platform thats proper, so I have been, until now...

So I guess I hope ellensp works faster then this pr gets merged or i have to revert it 

If youre going to remove 512k targets leave the new stm32f1.ini targets alone untill it gets its missing targets back. 

> This PR doesn’t remove the RE environments, so users can still compile for those boards just as before.

No it removes my only options right now on the current STM32 hal for the SKR with RE

Context: 

I'm not a developer but what I found was the push to get the F1 migrations moving to the STM32 HAL,  I Did the legwork and found out what it was, and now that its happening, its a bit messy to be expected with the migration and separation of platforms. as the man him self "Thinkyhead" says, merging it the best way to have users test it, push it in and see what happens.
The platform renaming is going to PUSH a ton of users with out even knowing to the new platform.  So thats a can of worms in its self aside from alienating some even if you consider them niche or unwanted users. 

So i happily hopped on the bandwagon to test, put the new HAL into production on several units. and then in the home stretch before the dust settles and we have it actually all working as it used to for the platforms its targeting (kind of RE and several others went missing in the platform separation)  My only ability to test the "thing" that solves my issues and got the ball rolling on this you want to pull the rug out from under. 

So how about we don't prune the 2 week old platform target until it at least works like it used to....

**Comment by thisiskeithb** [comment]
Like I said above, this PR doesn’t remove the RE environments. They are still available:

https://github.com/MarlinFirmware/Marlin/blob/b99411b62b6c21aee64f5d33ef5cbee4b701dc68/ini/stm32f1-maple.ini#L157-L177

**Comment by GhostlyCrowd** [comment]
> Like I said above, this PR doesn’t remove the RE environments. They are still available:
> 
> https://github.com/MarlinFirmware/Marlin/blob/b99411b62b6c21aee64f5d33ef5cbee4b701dc68/ini/stm32f1-maple.ini#L157-L177

And like i said i do not want to build on maple for this target. `common_stm32f1.platform` 

Are we missing something here a proper conversation on discord can resolve? 

I've said several times the SKR RE platform does not exist yet on the `common_stm32.platform` so the ONLY resolution is for me to build with the 512k target your pr is looking to remove. we're obviously not understanding each other.  Like i keep saying you suggest you're not going to break anything but that hangs on the factor that your pr is merged after some one actually fixes the missing :STM32F103RE_btt/(_usb) targets in the new platform before this is merged, further more the name changes will force push many to the new HAL with Missing targets and you want to make this further exacerbated by removing more before the new target has its legs?

You're looking to create less unsubstantiated bug reports and in the process are going to create more by pulling the rug out while a platform change is in process a naming change has happened and many will be pushed right onto a new platform. 

Seriously I do not know how better to explain this. I am running out of ways to explain that you are alienating me on this PR.


out of all the insane invalid bug reports this is your focus....
which i might add you said your self  `Related Issues
Probably some in the queue that were related, though most of the headaches come from STM32F1/maple/timer conflicts.`

And you're telling me is "building on maple is still fine" when i say the work around on STM32 is better and your killing it.

**Comment by thinkyhead** [comment]
It sounds like the non-Maple 512K "RCT6" (née "RET6") will need to stick around as an option for these boards. So, I don't think it's a good idea to completely remove them at this time.

But for clarity, maybe the environments need to be named with "E" (512K) instead of "C" (256K). Also, I'm sure no one would mind if the environment names somehow became shorter in the process.

Meanwhile, I went ahead and merged the uncontroversial parts of this PR.

**Comment by thisiskeithb** [comment]
> Meanwhile, I went ahead and merged the uncontroversial parts of this PR.

Thank you!

**Pull request closed without merging**
