### PR TITLE
Fix "unqualified id" warning

### PR DESCRIPTION
**Pull request by thinkyhead**
GCC doesn't like re-casting between abstract types. This PR uses a `union` to get byte-level access to the data structure.

CC: @p3p

### CODE REVIEW

**Comment by p3p** [comment]
I think this is a case of different warning for different c++ standards and/or gcc versions, this PR introduced a warning (array bounds) in the LPC builds where there was no warnings before, the reinterpret cast approach wasn't causing any warnings but I'd only recently refactored away from the unions so it probably doesn't matter either way.

**Comment by thinkyhead** [comment]
The warnings we currently get from the reverted code seem worth some regard. The `Header::data` array is only one byte long, and it is not part of a union, and code is writing past the array bounds. How is it that the code is not incorrect to overflow that buffer?

**Comment by thinkyhead** [comment]
*nevermind* (missed that the header is a union). I will just suppress the warning.

**Comment by p3p** [comment]
Currently trying to finish this (Marlin Binary Protocol) so we don't have to remove it before you release 2.0, can't have people implementing an incomplete standard into things.. I do have it working as a fully binary protocol, (rx and tx) but still need to work around a few things, data lifetime etc, if a packet needs resent it needs to have been buffered somewhere .. memory constraints are a headache as usual.

It is nice having a completely non blocking transport layer to work with though, can transfer a file while streaming data and being able to send "instantaneous" commands at the same time.

**Comment by thinkyhead** [comment]
Memory constraints are always annoying, but there is no substitute. On the positive side, the low-end Melzi boards have an overabundance of RAM.

**Pull request merged**
