### PR TITLE
Use _temp_error() for all errors thrown by different heater sanity check mechanisms

### PR DESCRIPTION
**Pull request by AnHardt**
Now ending in an endless loop.
Tidy up the output format.
We now get:
ERRORTEXT ", system stopped! Heater_ID: " HEATERID

Where ERRORTEXT can be:
"Heating failed"
"Thermal Runaway"
"MAXTEMP triggered"
"MINTEMP triggered"
and soon
"Thermal Jump"

HEATERID can be
0, 1, 2 ,3 , "bed"

This messages are always followed by the common:
"Printer stopped due to errors. Fix the error and use M999 to restart. (Temperature is reset. Set it after restarting)"

### CODE REVIEW

**Comment by AnHardt** [comment]
Addresses mainly the tests ending with 'Heating failed' in #2066.
Ideally you cant come out of this without a reset. 
I hope not to break the serial protocol. 
With the second line the host is informed about the stop, on the common way.

**Comment by thinkyhead** [comment]
We should drop `M999` with this perhaps. The only other condition that has a full Stop() is when a servo probe fails to deploy or stow.

**Comment by scotty1024** [comment]
How about M999 says yo home boy you don't need me anymore and drop the command after a decent interval?

**Comment by clefranc** [comment]
Beginning testing now...

**Comment by clefranc** [comment]
@AnHardt See https://github.com/MarlinFirmware/Marlin/issues/2066 for bed results.

There is something definitely wrong with this PR as the thermal jump is not there anymore for the bed.

I don't know if it's revelent to do hotend tests???

**Comment by AnHardt** [comment]
@clefranc 
Ah, i see what happened.
This PR ( _temp_error()) #2115 only alters the behavior when an error was detected. Since you did not get any errors during last tests, you have not tested it at all.
To see the difference of _temp_error() without #2077, just repeat `Test 8`  (or an other one with  "Heating failed") of you test row.

#2077 (Jumps) is the part where the errors are detected. You need #2115 and #2077 at the same time.
If you try to merge them together you'll get a minor merge conflict. Just add the message for 'Jump' in the new style of #2115.

**Comment by clefranc** [comment]
@AnHardt See https://github.com/MarlinFirmware/Marlin/issues/2066 Test 8.

**Comment by thinkyhead** [comment]
> yo home boy you don't need me anymore

Good general principle for anything that might go away.

**Comment by AnHardt** [comment]
@clefranc 
Thank you for the test.
Conclusion: **If** we detect an error - we are safe now.

**Comment by thinkyhead** [comment]
@scotty1024 Another option for `M999` – Actually reset the board.

```
void (*ResetAVR)(void) = 0; // Reset function is Address 0
ResetAVR();
```

**Pull request merged**
