### PR TITLE
Adjust code in M200

### PR DESCRIPTION
**Pull request by thinkyhead**
Thought I saw a bug, but I see that initialized values aren't reset. So, took the opportunity to make the code a little cleaner.

### CODE REVIEW

**Comment by nophead** [comment]
Why ugly nested preprocessor conditionals and not a simple loop on the number of extruders? Let the compiler unroll it if it is less code straight lined.

**Comment by thinkyhead** [comment]
I would prefer a loop, but there's a feature in the queue that uses new #defines for filament diameter on multiple extruders. After that gets merged we'll be pulling these diameter values from a const array and can use a loop, so perhaps I _will_ make the change now...

**Comment by galexander1** [comment]
The old code isn't broken and doesn't violate our style guide.
Don't fix it.

**Comment by thinkyhead** [comment]
Added some more changes of an inspirational nature.

**Comment by galexander1** [comment]
for (int i = x; i--; )   ?????  clever???

Does it include x?  Does it include 0?  Is it safe for this walk to go
from high to low?  I can answer these questions, but why should I even
ask them?  Am I just an old fuddy duddy?

   for (int i = 0; i < x; i++) !!!! stupid!!

Clever is bad.  Stupid is good.

**Comment by thinkyhead** [comment]
It's awesome. And inspiring! But haha, I will make it more normal looking.

```
for (int i=4; i--;) { printf("%d\n", i); }
```

output:

```
3
2
1
0
```

compare to:

```
for (int i=4; --i;) { printf("%d\n", i); }
```

output:

```
3
2
1
```

**Pull request merged**
