### PR TITLE
Better sanity check for FILAMENT_CHANGE_FEATURE, FILAMENT_RUNOUT_SCRIPT

### PR DESCRIPTION
**Pull request by thinkyhead**
Addressing: #5521

- Catch: `FILAMENT_CHANGE_FEATURE` is enabled without an LCD
- Catch: `FILAMENT_RUNOUT_SCRIPT` contains "`M600`" and then require `FILAMENT_CHANGE_FEATURE`
- Clean up Filament Runout Sensor config comments

### CODE REVIEW

**Comment by manianac** [comment]
Wasn't there a discussion a while back when this feature was implemented to have it not require an LCD?  I could be way off, but I thought there was talk of repurposing a kill button or gcode to allow use of it.

**Comment by thinkyhead** [comment]
It must be on someone's list, but I haven't seen a design proposal. So for now, filament change still requires an LCD.

**Comment by AnHardt** [comment]
@thinkyhead 
```
  CHANGE OPTIONS:
>Resume print
 Extrude more
```
makes a one button solution difficult.

I closed #4099 when i realized it would not work anymore for M600. And to be honest, after ~3 month of waiting for a merge, i lost my patience. Feel free to use my code - i have lost any interest in that feature.

Doing a extrusion until the button is pressed has the risk of extruding the whole spool of filament when the user runs away at the wrong moment - but would make it possible to do M600 with one button. Or you have to implement double or long klicks for the button without sufficient feedback.

**Comment by thinkyhead** [comment]
> after ~3 month of waiting for a merge, i lost my patience

Sorry. I've had a lot going on with this move to Texas.

**Pull request merged**
