### PR TITLE
Delayed U8glib Initialisation

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Marlin have a u8g lib global variable. It will make it run the constructor before any hardware is initialised. It's a problem because u8b lib try to do hardware init and setup right on the constructor!

It breaks STM32. And can break a lot other things, because it's not the right order to run things.

This PR makes the u8g lib initialisation happens only in the first usage, so it will avoid its constructor to run too early.

### Benefits

Should fix u8glib init issues, and other random behaviours/

### Related Issues

#21488 
#21277 
#21417
https://github.com/MarlinFirmware/U8glib-HAL/pull/24

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Thanks! This solves the boot issue I was seeing while testing the BTT STM32F1 to STM32 HAL migration: https://github.com/MarlinFirmware/Marlin/pull/21488#issuecomment-811453815

**Comment by rhapsodyv** [comment]
Tested it and it's fully working.

BTT SKR MINI E3 2.0 + 12864 emulation on a TFT35.

**Comment by adolson** [comment]
(I initially commented this elsewhere, but it was the wrong place - I apologize for that).

After this change, Marlin no longer compiles in Arduino IDE with certain configs (ie: config/examples/Eryone/Thinker SE). I believe the issue comes from the #define REPRAP_DISCOUNT_SMART_CONTROLLER.

Some may say "Arduino IDE is not good enough," but it was compiling Marlin just fine before this commit. If that's really the only solution, is there a non-Microsoft alternative for compiling Marlin? (If I rollback to the previous commit, ecd5ae890f890c4bedd5c913ddba688c3687573d, Marlin compiles in Arduino IDE.)

**Comment by thinkyhead** [comment]
> is there a non-Microsoft alternative for compiling Marlin?

You can always use PlatformIO from the command-line. Marlin includes a script called `mftest` to make it bit easier. I use this command to compile Marlin on any platform with a BASH shell:
```sh
mftest -a
```

Anyway, I will have to look at the compile issue. There may be a simple fix.

**Comment by thinkyhead** [comment]
@adolson — Note that you will need to download the very latest `U8glib-HAL` — version 0.4.4 — if you have not done so already. Otherwise Marlin will not compile in Arduino IDE or in PlatformIO.

**Comment by adolson** [comment]
Thanks, @thinkyhead. I ended up figuring out PlatformIO shortly after posting this comment. It seems faster and more automated, so I'll likely stick with that and my usual code editor, vim. Still, I'll try getting Arduino IDE working again since I was teaching people how to do it that way.

**Comment by pabloandresm** [comment]
Hello,

Sorry to bother here, but since this commit, I receive this compilation error:

Z:\USERTEMP\arduino_build_590861\sketch\src\lcd\dogm\HAL_LCD_class_defines.h: In member function 'void U8GLIB_64128N_2X_HAL::init(pin_t, pin_t, pin_t, pin_t, pin_t)':
Z:\USERTEMP\arduino_build_590861\sketch\src\lcd\dogm\HAL_LCD_class_defines.h:37:13: error: 'init' is not a member of 'U8GLIB'
     U8GLIB::init(&u8g_dev_st7565_64128n_HAL_2x_sw_spi, (uint8_t)sck, (uint8_t)mosi, (uint8_t)cs, (uint8_t)a0, (uint8_t)reset);
             ^~~~

I am compiling using the Arduino IDE, board MEGA2560, and U8glib version 1.19.1 (latest).

I would appreciate some help.
Thanks

**Comment by Vertabreak** [comment]
would suggest using Vscode instead of Arduino.

**Comment by pabloandresm** [comment]
> 
> 
> would suggest using Vscode instead of Arduino.

Sorry, I just can't change my build environment. All versions from 1.x to 2.0.7.2 compiled just fine using Arduino IDE. The 2.0.8.0 cannot be an exception.

**Comment by rhapsodyv** [comment]
@pabloandresm the answer is above your comment: https://github.com/MarlinFirmware/Marlin/pull/21496#issuecomment-826288224

you need to use marlin version of u8g lib, as commented by thinkyhead.

**Comment by Wallby** [comment]
I am getting `error: 'init' is not a member of 'U8GLIB` (i.e. same error as @pabloandresm with U8glib-HAL 0.5.0 (i.e. a more recent version then the suggested 0.4.4).

**Pull request merged**
