### PR TITLE
[2.0.x] Optional heater signal inversion

### PR DESCRIPTION
**Pull request by ktand**
### Description

Not all boards have active high heater signals. This PR enables each heater signal to be optionally inverted by defining:
```cpp
#define HEATER_0_INVERTING true
#define HEATER_1_INVERTING true
```
..and so on.

It also ensures that the heaters are turned off for all heater pins defined even though the number of hotends is less than the number of defined heater pins.

Previously, if the number of heater pins was > than the number of hotends, the unused heaters where left at the value of the pin after reset.

### Benefits

- Marlin can be used on boards with active low heater pins. 
- All heaters pins are set to their off value during initialization

### CODE REVIEW

**Comment by thinkyhead** [comment]
> However, some boards require an active low signal.

If this is an immutable board-based behavior, then it would make more sense to force these options in the appropriate `pins_XXX.h` files.

**Comment by ktand** [comment]
The reason I added it to `Configuration_adv.h` is that there were already definitions to invert the HEATER_BED signal:

```
#if ENABLED(HEPHESTOS2_HEATED_BED_KIT)
  #undef TEMP_SENSOR_BED
  #define TEMP_SENSOR_BED 70
  #define HEATER_BED_INVERTING true
#endif
```
But your comment makes sense so I will remove the definitions from `Configuration_adv.h` and update the PR.

**Comment by ktand** [comment]
Makes sense. I have removed the defintions in Configuration_adv.h. PR has
been updated.

Karl

**Comment by thinkyhead** [comment]
Thanks for the cleanup. Any particular `pins_BOARD.h` files that should force these options to `true`?

**Comment by ktand** [comment]
Yes, I'm working on a **STM32F407** based board that will require heater pin inversion for safety reasons (if 3V3 for CPU goes away heaters will turn off). I will create a PR for the board when everything is verified to be working. But I guess heater signal inversion could be useful for any board if using an external circuit for controlling heater power, controlled by on board mosfets.

board

So far I have the following working:

- Steppers
- Endstops
- Heater outputs
- Fan outputs
- LCD `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`

Left to check:
- TMC2130 in SPI configuration
- SD card

**Comment by thinkyhead** [comment]
Very nice looking board!

**Pull request merged**
