### PR TITLE
Temperature: Don't wait twice

### PR DESCRIPTION
**Pull request by espr14**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Does not make sense to wait twice as long if the temperature is in the window during the first loop.

### Benefits

If I preheat the nozzle before I won't wait. Previously, I had to wait two times longer that with no preheat.

### CODE REVIEW

**Comment by thinkyhead** [comment]
@AnHardt — Do you recall —back in the Neolithic Age— why we extended the wait time for all the heaters during their initial heatup?

**Comment by AnHardt** [comment]
Sorry can't remember to have read or thought about the problem.
But at the time this was programmed we likely had no dedicated preheating.

When having a sluggish heater system, there is a chance to stay a long enough time within the range but nevertheless leave the range upward when crossing the target temperature the first time. Later crossings are usually less steep and have less amplitude. Maybe it was made for this situation.

---

If the suggested change is true, it is also true for the bed and chamber heaters.

**Comment by thinkyhead** [comment]
The extra time is probably useful, but it probably doesn't need to be a full 20 seconds (in the case of the default 10 second residency time). So, instead I've made this apply an extra 1/3 of the configured time, so it will require 13.33 seconds in the case of the default 10s. Impatient users (like me) should reduce the configured times down to something more like 5s, which should be fine for most purposes.

**Comment by MusicJelly** [comment]
Check this commit https://github.com/MarlinFirmware/Marlin/commit/7fde3ed915dd1985aa420a0b009869c7184cef71.

I think that is a wrong commit.

The first_loop will hit only when nozzle is stable and first into the loop. 
Like pause, change filament, or preheat the nozzle before a print task.
At that time. "Wait time" already happened.

I think this commit want skip the wait time.  But the symbol is wrong. It should be '-=', not '+='.

@espr14 is right.  
Please check that. @thinkyhead

**Pull request merged**
