### PR TITLE
Remove 'Media Released' message

### PR DESCRIPTION
**Pull request by mathiasvr**
### Description
I propose to remove the `Media Released` message from the LCD menu, as I find it unnecessary.
The `Attach Media` menu should be sufficient to convey that the media is released.
Also, since it is represented as a menu item and not a status message, some users might find it confusing and think something should happen when clicking it (or that something happens in the background?).

### Benefits
Declutters the LCD menu by removing an item that does nothing.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I agree that the item is kind of strange, but I think it's meant to be the analog for the `ACTION_ITEM(MSG_NO_MEDIA, nullptr)` that applies for auto-detected SD cards (which can't be "released" or "detached" by a menu item). I believe the idea is that if the menu is on-screen when the state of the card changes the screen won't scroll or alter the current item selection (and it allows the status change to be seen).

Try seeing how the menu looks both with and without `SD_DETECT_PIN`, and both with and without an onboard SD card, and see whether it makes sense to eliminate altogether, or just refine.

**Comment by mathiasvr** [comment]
I think it might be fine to have the `MSG_NO_MEDIA ` item for auto-detected SD cards as it is more clear. I would still prefer that the counterpart to that would simply be the `Attach Media` menu and not two items.

Now I noticed that auto-detected SD cards cannot be released but instead has the `MSG_CHANGE_MEDIA` message. Is that necessary? Is it not sufficient to use the refresh item in the Media Menu instead?

**Comment by thinkyhead** [comment]
> MSG_CHANGE_MEDIA

With an `SD_DETECT_PIN` the printer is expected to know that you swapped cards. If you want to force the printer to notice, click the `M21` item labeled as `MSG_CHANGE_MEDIA`. If no card is present then it will reflect that after trying to init it.

**Comment by mathiasvr** [comment]
I think I understand, but would it be a problem to force this check initially when clicking the Media Menu? This way we could remove `MSG_CHANGE_MEDIA` as well. I think this item could actually be even more confusing for some users. Anyway, I'm clearly not a fan of having extra menu items :)

**Comment by thinkyhead** [comment]
If your SD detect pin is working correctly then the SD card in the slot should already be mounted at startup. If no SD detect pin exists, Marlin just tries to mount the card anyway.

**Comment by mathiasvr** [comment]
Unless I'm missing something the MSG_CHANGE_MEDIA is still displayed if the detect pin is working and the card is mounted right? In that case, I don't see much difference. I might have to try it out though.

**Comment by thinkyhead** [comment]
> …noticed that auto-detected SD cards cannot be released…
> Is it not sufficient to use the refresh item in the Media Menu instead?

- If the media is acting up, going into the SD card listing might not work.
- The "Refresh" item is **only** shown when you have **no SD detect** pin (-1).

Years of history behind decisions that are hard to understand on first encounter.

**Comment by mathiasvr** [comment]
Sorry I have to ask, but I have personally moved this line up above the release/change media menu item, because I thought it was nicer:
https://github.com/MarlinFirmware/Marlin/blob/6c8bc4f703f3e2f3aa20096aff1086e0d02d68bb/Marlin/src/lcd/menu/menu_main.cpp#L223

However, this is apparently already the case for condition `!HAS_ENCODER_WHEEL` here:
https://github.com/MarlinFirmware/Marlin/blob/6c8bc4f703f3e2f3aa20096aff1086e0d02d68bb/Marlin/src/lcd/menu/menu_main.cpp#L123

What is the reason that they are handled differently?

**Comment by thinkyhead** [comment]
With an encoder wheel the hardest-to-miss positions in the menu are the top and the bottom.

**Pull request merged**
