### PR TITLE
Remove config for pt100

### PR DESCRIPTION
**Pull request by josefpavlik**
I've removed the configs for thermistor Pt100 connected directly as this configuration is not accurate enough.

### CODE REVIEW

**Comment by manianac** [comment]
I don't know of anyone testing a 1K pullup with the PT100, is it completely unusable?  And why not the PT1000, in theory it should get by fine, I just don't know of anyone to try it.

**Comment by josefpavlik** [comment]
see the discussion on https://github.com/MarlinFirmware/Marlin/issues/2912#issuecomment-268478912

I've made a couple of calc and I've found, that the Pt100 is unusable as the granularity of a/d is one step per 12 celsius. The Pt1000 works fine, makes about 2 degrees per step and I've used it on my printer without problems
.
Well configured Pt100 with amplifier should give about 4 steps per degree, so it's 50 times better as Pt100 connected directly.

**Comment by josefpavlik** [comment]
seems that the Pt100 with pullup can work, so now I'm closing the request, however seems that the table is not good. I'll try to check it.

@bsculley writes: 
 have actually implemented PT100 with device 147. It works better than I imagined it would. The readings fluctuate +/- 5 degrees around the set point, but between thermal inertia in the printhead and the PID it seems ok. I am getting good prints. 
The main problem with the temperature table is that it was providing negative temps (-1/-10) at room temperature and the firmware wouldn’t start the heater. I recalculated the table manually based on the PT100 resistance table. I calculated the voltage across the divider for each temperature (assuming 5v and 4700 ohm pull-up). Then I converted to steps (out of 1024) and finally multiplied by 16. I don’t know where this magic number comes from, but it seems baked into the firmware somewhere.

**Comment by manianac** [comment]
Awesome thanks for the follow-up.  I'm currently using the PT100 with amp, so I was interested if any of this was feasible or not if in some disaster I have to revert.

**Pull request closed without merging**
