### PR TITLE
Added new DGUS LCD UI.

### PR DESCRIPTION
**Pull request by mrv96**
UI source repo: https://github.com/Desuuuu/Marlin

### Description

The pourpose of this PR is to integrate the wonderful work of Desuuu in Marlin. A lot of people with Longer LK4 Pro and similar printers is already using his UI or a fork of its repo.

I think and hope that his work is already mature to be officially integrated in Marlin. As already mentioned his UI is already widely spread.

The scope of modifications is limited to the integration of a new extensible UI library for DWIN T5UID1 touchscreens.
Core functionnality is, by design, left untouched from the upstream.
The touchscreen firmware compatible with this PR is available in this repository: https://github.com/Desuuuu/DGUS-reloaded

Example configurations are available in this repository: https://github.com/Desuuuu/DGUS-reloaded-config

### Requirements

DGUS LCD display T5UID1.

### Benefits

Add a new DGUS LCD UI.

### Configurations

[Configuration_files.zip](https://github.com/MarlinFirmware/Marlin/files/6489986/Configuration_files.zip)

### CODE REVIEW

**Comment by Foxies-CSTL** [comment]
Hello @mrv96, 
Is it compatible with UBL or ABL leveling?

**Comment by mrv96** [comment]
It is surely compatible with ABL.

Since this PR it should be compatible also with UBL: https://github.com/Desuuuu/Marlin/commit/19c7892f21cce5bc713e04ca6dbc4ff803586380
________________________________

**Comment by Foxies-CSTL** [comment]
> It is surely compatible with ABL. Since this PR it should be compatible also with UBL: [Desuuuu@19c7892](https://github.com/Desuuuu/Marlin/commit/19c7892f21cce5bc713e04ca6dbc4ff803586380)


Super!! But I don't have a Creality (Cartesian printer) and should I modify the UI (DWIN) to fit my Delta?

**Comment by mrv96** [comment]
I use this with a Longer3D LK4 Pro, the sprinter itself it is not important. You must flash the UI firmware to use this code. Check the links in the description of this PR
________________________________

**Comment by Foxies-CSTL** [comment]
> I use this with a Longer3D LK4 Pro, the sprinter itself it is not important. You must flash the UI firmware to use this code. Check the links in the description of this PR

Thanks, I will try a Marlin compilation before flashing my screen (T5LC). I have a doubt although it is the same resolution (800x600) and the same screen family (T5). Do you think it is compatible with the T5LC?

Correction!! after researching the type and resolution of the screen, I need to convert your DWIN pack to 480x800 vs 270x480 and the configuration of the image pointers.
Sorry for the inconvenience.

**Comment by mrv96** [comment]
I think that this UI is not compatible with T5L, this is compatible only with T5U
________________________________

**Comment by thinkyhead** [comment]
I would like to make changes, but this PR is not allowing changes. If you see an option on the page, please enable it to "allow edits from maintainers."

**Comment by mrv96** [comment]
@thinkyhead this happens every time that i make a PR to Marlin, but I always enable the option that you have mentioned

image

I don't know how to solve this problem, but I wold be very glad if you can help me to fix this once and for all.

To mitigate this issue I have just invited you as collaborator of my fork.

image

**Comment by thinkyhead** [comment]
> this happens every time that i make a PR to Marlin

Definitely contact GitHub about the issue. I know of one other account that has the same problem, and maybe your accounts both have the same underlying issue.

…and it is probably related to the fact that your fork of Marlin is not named "Marlin" but "Marlin2-LK4-Pro."

**Comment by thinkyhead** [comment]
…and it is probably related to the fact that your fork of Marlin is not named "Marlin" but "Marlin2-LK4-Pro."

**Comment by thinkyhead** [comment]
I have created a support ticket with GitHub about the issue, so hopefully they will solve it once and for all.

**Comment by mrv96** [comment]
Thank you very much. I hope that Github will be able to solve this issue, we'll see.

**Comment by thinkyhead** [comment]
@mrv96 — Would you mind revoking all my privileges on your fork? GitHub support wants me to try editing one of the files under the Files tab to see if that is also not working.

**Comment by mrv96** [comment]
@thinkyhead done. Thank you.

**Comment by thinkyhead** [comment]
Thanks! I've completed testing, so you can re-invite me any time, and I'll continue to work on preparing this PR for merge.

**Comment by mrv96** [comment]
Done. Did GitHub understand what the problem is? Have they solved it? If yes, in theory it wouldn't be necessary to add you as collaborator in my repository right?

**Comment by mrv96** [comment]
Done. I hope GitHub support will be able to understand and fix this issue early.

**Comment by thinkyhead** [comment]
@mrv96, @marcio-cp, @GeoSaffer — The problem seems to only exist with forks of Marlin that were not forked from this repository, but were forked from a fork. There's a field called 'forked-from' which the GitHub servers use to figure out where the parent of a given fork comes from. It appears that the server code is only considering a single level of forking. So, now that GitHub support is clued-in on the problem, perhaps there will be a solution before long.

**Comment by thinkyhead** [comment]
Are there any new enhancements made in recent weeks that should be brought over from the original Desuuuu repository?

**Comment by Desuuuu** [comment]
You might want to look at this commit https://github.com/Desuuuu/Marlin/commit/21aec4427a4caab4d71e708172aa7083dec91f79 I guess.

Small little detail as well, in the comment you added in commit https://github.com/MarlinFirmware/Configurations/commit/a4093def94f3a80d2f24726223a6f4d6c008f6b4, you might wanna point people to the Releases instead, since the compiled binaries for the controls are not present in the source (they're generated using DGUS Tools).

Since this is merged, I'll be leaving my fork as it is from now on and any further development can happen here.

**Comment by mrv96** [comment]
@Desuuuu unfortunately your commit has been released as soon as the PR was merged.

@thinkyhead can you apply the Desuuu suggestions in his last message, or it is necessary to open a new PR?

**Comment by thinkyhead** [comment]
It is always best if we get a PR submission instead of relying on someone eventually finding a comment on a closed PR and following up on it. Everyone is always busy, and by the time someone gets around to it, things may have changed here or there.

**Comment by mrv96** [comment]
Ok. Thank you.

@Desuuuu can you open a PR? Otherwise I'll do it

**Comment by thisiskeithb** [comment]
> Ok. Thank you.
> 
> @Desuuuu can you open a PR? Otherwise I'll do it

It has already been fixed: https://github.com/MarlinFirmware/Marlin/commit/23d10ceccb16e5886a6441a364fcbc08391287fe

**Comment by mrv96** [comment]
Wow, ok. Thank you!

**Comment by thinkyhead** [comment]
Cherry-picked the suggested commit and updated the link. Thanks for the note!

**Pull request merged**
