### PR TITLE
Clean up and finish #5887

### PR DESCRIPTION
**Pull request by thinkyhead**
- Shorten configuration option names
- Use `ENABLED` macro for the option
- Apply new options to all configurations
- Simplify implementation, use `PENDING` macro for reliability
- Apply coding standards (see Wiki)

### CODE REVIEW

**Comment by Roxy-3D** [comment]
@thinkyhead  What tools are you using to change all of those sample configuration.h files?

**Comment by thinkyhead** [comment]
> What tools are you using to change all of those sample `Configuration.h` files?

My text editor (Sublime Text) has global search and replace. So, for example, I can search for:
```cpp
/**
 * Include capabilities in M115 output
 */
//#define EXTENDED_CAPABILITIES_REPORT
```
…and replace it throughout project with…
```cpp
/**
 * Include capabilities in M115 output
 */
//#define EXTENDED_CAPABILITIES_REPORT

/**
 * Double-click the Encoder button on the Status Screen for Z Babystepping.
 */
//#define DOUBLECLICK_FOR_Z_BABYSTEPPING
#define DOUBLECLICK_MAX_INTERVAL 1250   // Maximum interval between clicks, in milliseconds.
                                        // Note: You may need to add extra time to mitigate controller latency.
```
This is made easier by "Use selection for find" and "Use selection for replace"
(usually ctrl-E and ctrl-shift-E in most editors).

**Comment by Roxy-3D** [comment]
> My test editor (Sublime Text) has global search and replace. So, for example, I can search for:

OK!   I need that ability.    I'll need to search and figure out how to get Vim to do that.

**Comment by CONSULitAS** [comment]
@Roxy-3D 

OK, but perhaps first do the same thing i did just a minute ago:

Open https://www.sublimetext.com and watch the demo "video" on the main page. 

Never ever possible with Vim 😄  

@thinkyhead Great hint! 👍

**Comment by thinkyhead** [comment]
> I'll need to search and figure out how to get Vim to do that.

Recommend you use an editor that has "projects" — essentially a list of files and folders which will appear in a sidebar — and which uses modern commands like "Use selection for find" and can select non-contiguous blocks of text for simultaneous editing.

image

**Comment by Roxy-3D** [comment]
@thinkyhead   THANK YOU SO MUCH for cleaning up my mess!   I may not get it 100% correct next time....    But I'll do better!

**Comment by Roxy-3D** [comment]
@CONSULitAS 
> Open https://www.sublimetext.com and watch the demo "video" on the main page.
> Never ever possible with Vim :smile:

I will do that!   I just don't want to switch editors right now.    But if it really is that good, maybe I should???

**Comment by thinkyhead** [comment]
It uses the de-facto standard shortcut keys that all modern text editors use on your platform, so it should be instant to adapt to. I also like Atom, but Sublime Text 3 is faster and has a working search-and-replace.

**Comment by thinkyhead** [comment]
> don't want to switch editors

It uses the de-facto standard shortcut keys that all modern text editors use on your platform, so it should be instant to adapt to. I also like Atom, but Sublime Text 3 is faster and has a working search-and-replace. Atom's global search-and-replace is broken.

**Pull request merged**
