### PR TITLE
[2.0.x] Azteeg X5 Mini WiFi

### PR DESCRIPTION
**Pull request by ModMike**
### Thank You!

A big thank you to all who helped me.  I really appreciate your patience, this is my first time doing anything like this.

### Requirements

Azteeg X5 Mini WiFi controller board

### Description

Added pins file for Azteeg X5 Mini WiFi controller board:  pins_AZTEEG_X5_MINI_WIFI.h

Updated pins_AZTEEG_X5_GT.h to include  F_CPU definition

Updated boards.h to define BOARD_AZTEEG_X5_MINI_WIFI as 1758

Updates pins.h to add pins_AZTEEG_X5_MINI_WIFI.h inclusion in the LPC176x section

Updated default Configuration_adv.h with comment to indicate AZTEEG X5 MINI I2C slave address'

Tested on AZTEEG X5 MINI_WIFI with TMC2224 digipot stepper drivers

X, Y, Z, E0 Homing ... SUCCESS
Fan 0 and Hotend 0 ... SUCCESS
Temp0 ... SUCCESS
Heatbed ... SUCCESS
#define SERIAL_PORT_2 0 @ 115200 (for ESP8266 Web UI) .... SUCCESS

### CODE REVIEW

**Comment by GadgetNutt** [comment]
Hey ModMike.  I have already assigned BOARD_SMOOTHIEBOARD to have 1757 in PR #11488.

**Comment by ModMike** [comment]
Was your request merged?  I guess I can change mine now right?

**Comment by GadgetNutt** [comment]
No, not merged yet

**Comment by ModMike** [comment]
Ok what do i do?  Increment by one?

**Comment by ModMike** [comment]
Just realized I made a mistake anyway.  Will do now.

**Comment by GadgetNutt** [comment]
You know what, I'm not sure.  I guess one of us may have to adjust it depending on who's is merged first.

**Comment by ModMike** [comment]
Kind of what I was thinking but if I increment now, then no issues right?

**Comment by GadgetNutt** [comment]
Sure.  I don't think you need to close your PR.  Just correct the mistake in it.

**Comment by ModMike** [comment]
Ok I made the change to 1758.  I forgot to disable PINS_DEBUGGING, fixed that too.

**Comment by ModMike** [comment]
I do not understand what failed.  My version compiles perfectly.  Any pointers?

**Comment by p3p** [comment]
If you updated PlatformIO it wouldn't, it seems F_CPU is no longer defined automatically when using a custom build script, although it has highlighted the fact we are using F_CPU for delays and 120Mhz boards are being added with it set at 100000000, 

Best solution is to add this to the board files I think otherwise we take the performance hit of detecting it at run-time as with the timers,

```
#ifdef F_CPU
  #undef F_CPU
#endif
#define F_CPU 120000000
```

**Comment by GadgetNutt** [comment]
I don't think you added the elif for pins_AZTEEG_X5_MINI_WIFI.h to the pins.h file.

**Comment by ModMike** [comment]
Just checked and its there

**Comment by ModMike** [comment]
P3P, Is there any "best" place to add it?  At the beginning I guess?  My platform IO is fully updated.

**Comment by GadgetNutt** [comment]
I don't see the pins.h file in your commits.

**Comment by ModMike** [comment]
Timeshell, that's weird, I was sure I had but machine knows best I guess!

P3P, should I still add what you suggested?  I would add that in the boards pin files right?

**Comment by p3p** [comment]
Add it underneath the board name definition, if you click on the red x on the failed commit you can see the build log and that F_CPU is not defined, if you have updated platformio it should be failing for you, it is for me (and travis) on platformio core 3.6.0.

**Comment by GadgetNutt** [comment]
p3p, maybe I'm missing something, but what in his commits requires the F_CPU declaration in the first place?  I added Smoothieboard, the same CPU, without having this issue.  I don't see anything in his commits that is much different from mine apart from the TMC drivers.

**Comment by p3p** [comment]
@timeshell It's not something @ModMike has changed, an update to PlatformIO Core (3.6.0) removed the automatic definition from the build, I'm still investigating the best solution to make sure it is set to the correct value as currently it will always be `100000000` but 120Mhz boards need it to be set to `120000000` so it was always a issue. In the new framework I'm working on it may be best if there is separate builds for each chip.

**Comment by ModMike** [comment]
Ok will do soon.

**Comment by GadgetNutt** [comment]
I'm using PlatformIO on VSCode.  Maybe ModMike's using Atom.  That may be why mine was different because my PlatformIO is also up to date.  Unless it just changed for Travis to 3.6.0 since he last checked my code...

**Comment by p3p** [comment]
Well now I'm questioning the reason for the issue, I looked at what had changed in platformios nxp platform and they've moved where the build parameters are set out of the main build script so i assumed that the custom build scripts no longer got the defaults.

**Comment by p3p** [comment]
Make sure you have updated the "platforms, packages and libraries" as well as core they are separate.

**Comment by GadgetNutt** [comment]
Well #11488 just failed now too.  Guess I'll add the definition.

**Comment by p3p** [comment]
Yea I restarted that test to make sure, PlatformIO has updated since you submitted it but if the build works for you two with everything updated (Core, and platforms) them I'm unsure what is causing it to fail on Linux,

**Comment by GadgetNutt** [comment]
p3p, can you please confirm which file to define the F_CPU?  I understood it to be in the pins_BOARD.h file under the board definition.  I tried that, but it still doesn't like it.

**Comment by p3p** [comment]
The Travis tests will not pass until it is fixed for the Re-ARM board that the tests target, I have a PR for that ready to submit but I'm still wondering why builds are working for you, don't want to patch a symptom instead of the problem.

**Comment by ModMike** [comment]
I updated my PIO and then the compile failed.  I added the statement you provided under the board name in the boards.h file and it compiled.  I do get the following warning though:

```
Compiling .pioenvs/LPC1768/lib6d8/U8glib-HAL_ID1932/clib/u8g_rot.o
.piolibdeps/U8glib-HAL_ID1932/src/clib/u8g_rot.c:48:27: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
u8g_dev_t u8g_dev_rot = { u8g_dev_rot_dummy_fn, NULL, NULL };
^~~~~~~~~~~~~~~~~~~~

.piolibdeps/U8glib-HAL_ID1932/src/clib/u8g_rot.c:48:27: note: (near initialization for 'u8g_dev_rot.dev_fn')
```
I will commit it now.

**Comment by GadgetNutt** [comment]
I don't think that the boards.h is the right place for it.  It will define the F_CPU while defining all the board types which we don't want.  It should be defined under the board definition in the pins_BOARD.h file.

**Comment by GadgetNutt** [comment]
Incidentally, my PlatformIO's last available update for VSCode is from July 26.  It compiles just fine without the F_CPU definition, but I added it anyway and it compiles with it too.

**Comment by p3p** [comment]
@timeshell definitely not using PlatformIO core 3.6.0 and nxplpc platform 3.4.0 then, so I can assume the problem is universal.

**Comment by GadgetNutt** [comment]
@p3p I manually updated to PlatformIO 3.6.0.  It still compiled successfully without the F_CPU declaration.

**Comment by p3p** [comment]
update the nxplpc framework as well (updating platformio does not update frameworks or libraries) as that is what has caused the problem,

**Comment by ModMike** [comment]
Made the change on my side and compiles fine but fails check on commit

**Comment by GadgetNutt** [comment]
@p3p Updated nxplpc framework and now confirm it fails without the F_CPU defined.

**Comment by GadgetNutt** [comment]
@ModMike see p3p comment...

> The Travis tests will not pass until it is fixed for the Re-ARM board that the tests target, I have a PR for that ready to submit but I'm still wondering why builds are working for you, don't want to patch a symptom instead of the problem.

**Comment by ModMike** [comment]
P#P, the only place this works is in boards.h file but it's rejected because of conflicts

**Comment by GadgetNutt** [comment]
You can't put it in boards.h.  See the pins_SMOOTHIEBOARD.h in the PR that was applied yesterday that I did for the Smoothieboard.   Perhaps you need to PR the main branch back to your fork first.

**Comment by ModMike** [comment]
Ok I used your example but it wouldn't compile.  So I updated my Platform IO (everything including Atom) and now I get this:

```
Linking .pioenvs/LPC1768/firmware.elf
arm-none-eabi-g++: fatal error: /Users/Michael/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/l
ib/nano.specs: attempt to rename spec 'link' to already defined spec 'nano_link'
compilation terminated.
*** [.pioenvs/LPC1768/firmware.elf] Error 1
```

**Comment by p3p** [comment]
Your Marlin source is not up to date, I hotfixed the platformio issue by restricting the build to a specific nxplpc platform version. I reported the F_CPU bug to them and it was patched in 3.4.1 now we have this new issue, they always give me nice things to fix but it will build with the current Marlin bugfix-2.0.x.

**Comment by ModMike** [comment]
Ok everything fixed and verified.  Will sync now.

**Comment by ModMike** [comment]
I think everything is fixed.  By the way, whats the easiest way to update my branch from the upstream branch?  Do I have to install a repo locally?

**Comment by p3p** [comment]
In general the work flow I use is to create a fork (as you have) clone that locally then add a new remote called upstream that targets `https://github.com/MarlinFirmware/Marlin`

To get your local repository and fork on github up to date you would 

```
git fetch --all
git checkout bugfix-2.0.x
git pull upstream bugfix-2.0.x
git push
```

Never work directly on the bugfix2.0.x branch, create a new branch for your work.
To update your PR branch after the above:
```
git checkout my_pr_branch
git rebase bugfix-2.0.x
```

You may get merge conflicts at this point that will need resolved, after doing that push the pr branch up to your fork on github. 

```
git push
```

**Comment by GadgetNutt** [comment]
In Windows, Github desktop can be used to sync from Github to your computer.

**Review by GadgetNutt — COMMENTED** [review]
I believe there is a problem in your boards.h file.  It shows you removing the BOARD_SMOOTHIEBOARD and doesn't show the one you are wanting to add.

**Comment by ModMike** [comment]
Yes I messed up the Github, I was using it wrong.  Can I kill this request and just open another one?  I need to setup a repo the right way.  Sorry about all the trouble.

**Comment by GadgetNutt** [comment]
I guess that's your call.

No trouble to me.  Bravo for trying.

**Comment by ModMike** [comment]
I think I mistakenly put back my older boards.h. so I fixed it.  I am a Github virgin and messed everything up.  Next time I will use a proper workflow to avoid these kinds of issues.

**Comment by ModMike** [comment]
I noticed this has not been merged.  Do I need to do anything more?

**Comment by GadgetNutt** [comment]
It will be reviewed by thinkyhead, possibly cleaned up a little an then merged if there are no other issues with it.

**Comment by ModMike** [comment]
Trying to become an adult and use GitHub desktop properly.  I have my fork but when I go to the clone folder, I only see the base branch, not 2.0.x bug fix.   I switch to the proper branch in desktop and still no love.  I've watched 2 hours of videos and been reading for 1.5 hours but can't get anywhere.  Whats the magic recipe? I really need to rebase my fork

Thank you.

**Comment by thinkyhead** [comment]
> Merge branch '1.1.x' into bugfix-2.0.x

Looks like that last merge blew up your PR.

**Comment by ModMike** [comment]
Issues corrected and new PR #11601 opened.

**Pull request closed without merging**
