### PR TITLE
Graphical LCD redraw the next segment sooner

### PR DESCRIPTION
**Pull request by thinkyhead**
Followup to #5239

### CODE REVIEW

**Comment by ghost** [comment]
I've tested this PR, flickering still exists but it's almost suppressed than in case of without this PR.

Video clip:
[](https://www.youtube.com/watch?v=W2zqkLplFcM)

**Comment by AnHardt** [comment]
Did anyone try the latest changes with displays with more then 2 stripes (not St7920)?
Probably not.

**Comment by thinkyhead** [comment]
@AnHardt Sometimes the only way to get "testers," I find, is to merge stuff, put it out there with a new version tag, and then review the flood of feedback (i.e., complaints). We can easily revert this if it's "crap." It's one of the more self-contained concepts.

**Comment by thinkyhead** [comment]
@esenapaj That tiny lag seems reasonably acceptable. How about on longer screens with more scrolling?

Then the question is, is the change worth it? Will it reduce lag in the planner?

**Comment by thinkyhead** [comment]
Reverted.

**Pull request merged**
