### PR TITLE
Various cleanups for recent merges

### PR DESCRIPTION
**Pull request by thinkyhead**
With recent merges several cleanups are required.

#### General cleanup
- Remove trailing whitespace
- Convert tabs to spaces
- Apply coding standards
- Use macros where possible (`sq`, `ELAPSED`, etc.)
- Remove unnecessary comments about `static` qualifiers
  (it applies to _ALL_ headers in all C++ projects in the universe)
- Simplify `BLTOUCH_HEATERS_OFF` code. (#6476) If anything is amiss, simply call `kill`.
- Convert multi-line end-of-line comments to single prefix comments.

### CODE REVIEW

**Comment by thinkyhead** [comment]
# ** Draft **

---

## Bed Probe Configuration

No matter how well you constrain, tighten up, and align the components of your 3D printer, there are bound to be imperfections in alignment that can negatively affect print quality. Among these imperfections, irregularities in bed-nozzle distance is one of the most problematic. If the first layer doesn't adhere to the bed then the rest of the print job is moot.

Marlin includes a "Bed Leveling" feature that compensates for these imperfections by taking measurements of the bed-nozzle distance at 3 or more points and then adjusting the nozzle position throughout the print so that it remains at a consistent distance from the bed.

Marlin allows you to take these bed measurements using nothing but a piece of paper, but for an improved experience the best option is to install a bed probe (also called a "Z probe").

### Bed Probes

Marlin 1.1 supports a wide variety of probe types:

- Simple switch (`FIX_MOUNTED_PROBE`)
- Switch on a servo arm (`Z_ENDSTOP_SERVO_NR`)
- Switch on a solenoid (`SOLENOID_PROBE`)
- Inductive probes (`FIX_MOUNTED_PROBE`)
- BLTouch - and clones (`BLTOUCH`)
- Sled-mounted probe (`Z_PROBE_SLED`)
- Allen-key delta probe (`Z_PROBE_ALLEN_KEY`)
- No probe (`PROBE_MANUALLY`)

### Bed Leveling Methods

Marlin includes various methods of probing and leveling:

- "3-Point" probes a triangle to determine the height and tilt of the bed plane. During printing the nozzle is adjusted in X, Y, and Z, so you can even print on a badly-tilted bed. However, this method requires a very flat and even surface.
- "Linear Grid" probes a square grid (as much as possible on `DELTA`) to determine the height and tilt of the bed. After that it works just the same way as 3-point leveling.
- "Bilinear Grid" probes a grid in the same manner as Linear Grid, but during printing the Z axis is adjusted according to bilinear interpolation between the measured points. This allows the printer to compensate for an uneven surface, 
- "Mesh Bed Leveling" works in the same manner as "Bilinear Grid" but takes different `G29` parameters. (This feature is deprecated and will not be included in future versions of Marlin.)
- "Unified Bed Leveling" is another alternative leveling implementation contributed by Roxy-3D. It includes several extra utilities so you can get more intimate with the details of your bed-nozzle distance.

### Configuration

#### 1. Z Probe Pin

Before configuring any bed probe be sure to read its documentation and the documentation for your electronics. Make sure you know to which pins the probe will be connected. Marlin provides reasonable defaults, but they will not apply to every situation.

In general, on a delta a switch-based probe will be connected to unused the Z-Min endstop pin (if there is one). For machines that have a Z-Min endstop, Marlin assumes you'll connect the probe to the Z-Max pin - since this pin is the least-likely to be used for something else.

- If the probe is connected to the Z-Min pin, enable `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN`.
- If the probe is connected to any other pin, enable `Z_MIN_PROBE_ENDSTOP`.
- If the probe is not connected to the Z-Max pin, you can also set `Z_MIN_PROBE_PIN` to the digital (DIO) pin number where the probe is connected.

#### 2. Probe Type

What kind of probe do you have?

- `FIX_MOUNTED_PROBE`
  Use this option for a fixed switch or inductive probe. This is the option to select if the nozzle itself is used as the probe.
- `Z_ENDSTOP_SERVO_NR`
  Endstop switches are inexpensive, and some printer kits include one or two replacement parts. So one popular probe type mounts an endstop switch on a servo-driven arm. Set this option to `0` for a servo-probe connected to the first servo plug, `1` for the next servo plug, etc. Set the servo's deployed/stowed angles with the `Z_SERVO_ANGLES` setting.
- `SOLENOID_PROBE`
  Select this option for a switch mounted on a solenoid.
- `BLTOUCH`
  The BLTouch by ANTCLABS is a compact probe specifically designed for use on inexpensive 3D printers. It uses a Hall effect sensor to detect the movement of a metal pin that can be magnetically extended and retracted. The BLTouch connects to the servo pins which function to send commands to the probe.
- `Z_PROBE_SLED`
  This option applies to a switch mounted on a "sled" that can be docked to the end of the X axis. The X carriage can pick up this sled, use it to perform probing, and put it back when done.
- `Z_PROBE_ALLEN_KEY`
  This is a popular solution on deltas. A spare Allen key is used with an endstop switch to make a probe that's deployed and stowed by turning the key 90 degrees. You can either deploy and stow the key manually or configure movements that bump the key against some fixed point. Options for this type of probe are included in the delta example configurations that come with Marlin.
- `PROBE_MANUALLY`
  The bed-nozzle distance can be measured without a probe by following a [manual procedure](link). The nozzle moves to each point and pauses. You adjust the Z height so that the nozzle is touching the bed. Once the Z height is adjusted, you tell the machine to go to the next point. Continue until all points are probed. This option can be used with all Auto Bed Leveling options except UBL, which is freestanding.

#### 3. Other Probe Options

- `LCD_BED_LEVELING` provides a guided process to assist with `PROBE_MANUALLY` (or Mesh Bed Leveling). Without this option you must send `G29` to move to the next point and `G1` (or buttons in your host software) to adjust the Z axis.
- `Z_MIN_PROBE_ENDSTOP_INVERTING` should be set to `true` if your probe uses normally-open (NO) switches. Normally-closed switches are recommended because they have the appropriate failsafe state and are less prone to false positives.
- `ENDSTOPPULLUP_ZMIN_PROBE` may be used if you need to _disable_ the endstop pullup for some reason, such as having an external pull-down resistor on a normally-open switch.
- `USE_ZMAX_PLUG` must be enabled if the probe is connected to the Z-Max endstop pin. `USE_ZMIN_PLUG` must be enabled if the probe is connected to the Z-Min endstop pin. _Et cetera_, _et cetera_.

**Comment by Roxy-3D** [comment]
- "Unified Bed Leveling" is an auto bed leveling implementation that combines the best features of all the previous bed leveling solutions and allows them to be used in combination with each other.   The UBL System includes several extra utilities such as the G26 Mesh Validation Tool and the G29 P4 Interactive mesh editing that make it very easy for the user to adapt the system to their printer.

**Comment by thinkyhead** [comment]
Thanks! I will see if I can make that more concise. This is about probes, so the bed leveling synopses are meant to be minimal. No mention of details like `G26` or `G29 P4` is needed for this article.

**Comment by Roxy-3D** [comment]
Yeah...  I understand...  But the Z-Probes serve no purpose without an auto bed leveling system turned on.   Without a bed leveling system, you may as well have a Z-Endstop.

**Comment by thinkyhead** [comment]
I am specifically keeping details about bed leveling to the bare minimum in this article, which is about getting to the point where the probe simply works.

**Comment by Roxy-3D** [comment]
OK...  But your UBL description took 3 lines.   I only made it go to 4 lines.

**Comment by thinkyhead** [comment]
> OK... But

FFS

Next, a section on testing the probe to make sure it functions, and troubleshooting the probe when it doesn't.

**Comment by WheresWaldo** [comment]
To remove the personal pronouns in sentences, perhaps they could be reworded in this manner, meeting the first criteria listed under Configuration cleanup:
> No matter how well constrained, tightened up, and aligned the components of any 3D printer, there are bound to be imperfections in alignment that can negatively affect print quality.

The third paragraph may be rewording in like manner:
> Marlin allows taking these bed measurements using nothing but a piece of paper, but for an improved experience the best option is to install a bed probe (also called a "Z probe").

In a similar vein:
> During printing the nozzle is adjusted in X, Y, and Z, so printing may succeed on a badly-tilted bed. (??? SUCCEED is a suspect word choice)

In the subsequent sections (not an inclusive list):
> Before configuring any bed probe be sure to read all necessary documentation including any for the electronics. Make sure which pins the probe are or will be connected to are properly labeled. 

> Marlin assumes a probe is connected to the Z-Max pin - since this pin is the least-likely to be used for something else.

> If the probe is not connected to the Z-Max pin, Z_MIN_PROBE_PIN must be set to the digital (DIO) pin number where the probe is connected.

> The key can either be deployed and stowed manually or movements configured that bump the key against some fixed point.

**Comment by thinkyhead** [comment]
> To remove the personal pronouns in sentences

Applies to documentation within comments and documentation that gives technical descriptions and instructions. Does not necessarily apply to all website documentation. Particularly, introductory material may be written in a more personalized manner. I'll put together an editorial guide in future. I'm just following principles of technical documentation similar to those I've used in past documentation projects.

**Pull request merged**
