### PR TITLE
Proposal: Configuration as Template

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

When developing in Marlin, we have two main tasks: develop/test in our hardware using our configs and preparing changes to send an official PR.

But, this process is a bit annoying because we need to constantly change branches or stash/unstash our changes in config files to send the PR and test our code. This even leads to wrong commits sometimes :-/

A lot of projects use the a pattern to solve that: have the config as template and `.gitignore` the actual config file. So, the developer can keep their local config file with all their specific changes, and keep the template untouched, simplifying a little the process of test and push.

Maybe you already tried it, maybe you have better ways, but I just want make this proposal to open this topic for discussion.

### Benefits

 - No more back and forth between branches when developing
 - Help to avoid wrong commits
 - Adopt a well know pattern of config files
 - It will keep user configs and the marlin updated configs together side by side, so users can diff and update their config as their will.

### Cons
 - Users that just want fork marlin to keep a pre-configured branch for a specific machine will need to do one more step: force add or un-ignore their configuration files

### CODE REVIEW

**Comment by thisiskeithb** [comment]
How would this work for users that have forks/branches with "ready to run" builds (or simply use git to keep their builds up to date via rebase)?

**Comment by rhapsodyv** [comment]
> How would this work for users that have forks/branches with "ready to run" builds (or simply use git to keep their builds up to date via rebase)?

Users that do a rebase from now, will get their current configuration files rename to _template one. They will have to make a copy:
```
cp Marlin/Configuration_template.h Marlin/Configuration.h
cp Marlin/Configuration_adv_template.h Marlin/Configuration_adv.h
```

If the user wants to keep their Configuration file in their repo, they can add it with `git add -f`, or even remove the gitignore for this files. Their branchs with changed configs will never be a PR branch, so there's no problem to them to do more one modification.

Future rebase/merge will be less trouble too. Because it won't give more conflicts for changes in the Configurations files. 

It's a trade off: non PR branchs will need one more step (copy config and force add it), PR branchs will be a bit easier when developing.

I know that Marlin is a big project. And even it could tried this in the past.

No problem if it be refused. I just to ask about this pattern :-)

**Comment by thisiskeithb** [comment]
> If the user wants to keep their Configuration file in their repo, they can add it with `git add -f`

Can that be done with GitHub Desktop or other GUI-based git clients? Using GitKraken for example, the files won't even show up, even if I wanted to add them to a commit unless I edit the `.gitignore` file.

**Comment by rhapsodyv** [comment]
Talking with @thisiskeithb, he made me thinking about the end user. The 3d printer user that wants marlin in his printer. I was thinking about my (and others dev) workflow.

Now I see don't worth the trouble of simplify a bit the dev life in the exchange of more support and end-user trouble.

If the user download marlin, try compile, and if gives an error, the first thing he will do will be complain and somewhere, instead of read about the instructions.

I'm closing this.

At least it worth the discussion :-) 

Thanks @thisiskeithb!

**Comment by thinkyhead** [comment]
This doesn't appeal to my sensibilities. It means copying files and renaming them to get to the point of compiling, and then the configs that are actually being used aren't going to show up in GitHub Desktop, which is my main diff tool. When people post their configs for testing, my first step is to drop them in place and check the diffs. If only templates are showing up in GD  this means I have to drop them onto the templates also to see the changes….

So in-general I think this would add more complication to my workflow.

**Pull request closed without merging**
