### PR TITLE
Add support for Printrbot Neopixel RGBW strip.

### PR DESCRIPTION
**Pull request by thinkyhead**
Cleanup, tweaks to #7284

- Allow use of Neopixel in conjunction other compatible led types
- Make the startup color cycle an optional feature
- Apply new options to example configurations

---
Connected as described at http://printrbot.com/shop/led-strip/

Based on patch by Kelly Anderson <kelly@xilka.com> at
http://www.xilka.com/printrbot/marlin/1.1.4/20170707/

### CODE REVIEW

**Comment by RalphSch** [comment]
Wouldn't it be better to rename all neopixel strings to WS2812B/SK6812 or something like that because neopixel is only a new brandname of some adafruit products made of the well (and better) known WS2812B/ SK6812 leds? Also http://fastled.io is an better and faster library than the "slow" adafruit one and it supports more than the two led types WS2812B/SK6812.

**Comment by fiveangle** [comment]
And I thought that [Tanno had this all ready to go for all LEDs](https://github.com/MarlinFirmware/Marlin/pull/7284#issuecomment-315161242), just waiting for the re-org after the fabled "code freeze" is lifted and the new layout work is completed ;)

**Comment by RalphSch** [comment]
@fiveangle I thought the same but red nothing about an really active code freeze. I just got mine led strip extension locally running, it's also for WS2812B/SK6812 and the similar ones but I didn't chose the direct way because I wanted cool animations without any noticeable load on the controller itself. Instead of directly addressing all pixels I just send some small calls to the Diamex Digi-Dot-Booster which handles the direct pixel controlling.

**Comment by rjacobs1969** [comment]
Incomplete implementation, the exact led type is hardcoded in Marlin_main.ccp  ( "NEO_GRBW" on line 977) which makes it not working with the far more common NEO_RBG (and 28 other types)

**Comment by Redferne** [comment]
Thanks for this feature! Works great!

**Pull request merged**
