### PR TITLE
[Bugfix-2.0.x] compiling error for BABYSTEP_ZPROBE_OFFSET

### PR DESCRIPTION
**Pull request by Ludy87**
compiling error for BABYSTEP_ZPROBE_OFFSET at disabed THERMAL_PROTECTION_HOTENDS and THERMAL_PROTECTION_BED

https://github.com/MarlinFirmware/Marlin/issues/12399

### CODE REVIEW

**Comment by AnHardt** [comment]
Don't fight the symptoms. Fight the reasons.

There is no logical reason why babystepping needs `THERMAL_PROTECTION_*`.
Babystepping needs the temp-interrupt to clock in the steps, but not the protection.

**Comment by Ludy87** [comment]
okay sorry about that PR

**Comment by Roxy-3D** [comment]
Yeah...  Personally...  I would like to see the interrupts abstracted a little bit more.   The PWM stuff causes some pins to not be usable for things like 'Case Light' because the hardware forces certain timers to be associated with particular output pins.   

And really...   BabyStepping should not be dependent on having Thermal Protection enabled.   

But with all that said...    as usual...   @AnHardt is 100% correct.

**Comment by thinkyhead** [comment]
For AVR, on many setups Timer 5 is generally free. For ARM we have lots of PWM pins. I agree we should have a better API to find free PWM pins and set them up with a range of base frequencies. I did some work on this (playing with Timer 5) and I've got a very nice function to set any frequency and duty cycle on that timer. In the meantime, we can point people to `M43` to see which pins and timers are still available based on their configuration.

**Pull request closed without merging**
