### PR TITLE
Editable filament runout state

### PR DESCRIPTION
**Pull request by robbycandra**
Filament Runout Detector can break easily. Many users replace their filament detector. But in the market, there are two types of filament Detector, normally open and normally closed. 

This PR adds a menu item to change the state indicating filament runout. With this menu, users don't have to reflash the firmware or resolder the limit switch if their new limit switches different from the previous one.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Note that any features with EEPROM storage need to also have a G-code so that the `M503` report can be replayed to restore the complete settings.

**Comment by AnHardt** [comment]
If this is the way to go - how far do we want to go?
Where do we want to draw the line between reconfiguring a system without recompiling and setting up a new system with recompiling?
**For me** the border is changed hardware. So **this** is behind the red line.
If we allow this we also have to allow changing thermistor-types, endstop-polatities, display-types, ... , on the fly.

**Comment by robbycandra** [comment]
This is because many users change their filament detector. So it is very convenient if we make this editable. 

I think the line is between FIX hardware and REPLACEABLE hardware. We won't change configurations for the FIX hardware, but for REPLACEABLE hardware or components, then we can put configurable parameters for it.

For example, we can edit the PID. This is also a configurable parameter for the printer components.

**Comment by thisiskeithb** [comment]
How common are filament sensors really breaking/needing to be replaced? I certainly don’t see it as a common issue in the various 3D printing groups and forums I follow.

**Comment by AnHardt** [comment]
> For example, we can edit the PID. This is also a configurable parameter for the printer components.

That's not a good example because tuning PID for different temperatures and/or different fan adjustments is completely independent from a change in hardware.

Try to find a better example.

But even if you can find one, that does not mean, integrating that, was not already an error.

Obviously we could make much more things 'online' configurable, if we want to.
The real questions are: "Do we want?" and: "Where are the limits?".

Also obvious is, that we have to have a limit. It would not be healthy for code-size and execution-speed if we could change between CORE an DELTA on the fly.

For me that border is 'changed hardware'. Where should it be in your opinion?

**Comment by robbycandra** [comment]
My border is between "Fixed Hardware" and "Replaceable Hardware".
I prefer to say that the filament detector is replaceable Hardware.

Filament detector is only a limit switch with a case. Users can easily unplug the cable and replace it. 
And, this is just an option to change between NO and NC. 
Not changing the hardware from a simple filament detector to a filament motion sensor, or, add/remove the filament detector from the printer. 

Like, re-set PID when we replace the printer cooling fans, or Re-set the brightness when we replace the neopixels. 

But I could be wrong. Therefore, I will accept whatever is deciced.

**Comment by thinkyhead** [comment]
> If this is the way to go - how far do we want to go?

Sure enough. My initial response to this was to reject it because it's another trip down that slippery slide, but I decided to give it a cleanup anyway.

- Once you've replaced a component like this it is unlikely you will replace it again for quite a long time.

- If you do replace NC/NO with its opposite, you now have an EEPROM which, every time it is reset, causes the sensor to trigger wrong, until you repair the polarity with `M412 V` or do a new firmware flash. That's a pretty big _faux-pas_ in the general scheme.

As simple as this is to implement, I agree that it crosses the line until someone decides to make an "everything is a variable" version of Marlin with a `config.g` file like RepRapFirmware.

**Comment by AnHardt** [comment]
> Filament detector is only a limit switch with a case. Users can easily unplug the cable and replace it.
And, this is just an option to change between NO and NC.

The same would be true for simple endstops.

For me the most prominent exchangeable hardware parts near the border are:
* Nozzles with different diameters - luckily most of the aspects are handled by the slicers - the connected length of the nozzle is handled by Marlin.
* Print surfaces for the bed - handled by UBL - but with some good will, these can be called consumables.

**Pull request closed without merging**
