### PR TITLE
Fix manual Y movement on delta (regression).

### PR DESCRIPTION
**Pull request by alhirzel**
regression was caused by MarlinFirmware/MarlinDev@92e798bc19afa3eba608afa21219050a0ef103f7

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
Sorry. This correction is wrong.
We wanted to clip the moves to be inside the printable radius.
For a x-move y is invariable an determines the possible length of the x moves.
So everything seems to be correct as it is..

**Comment by alhirzel** [comment]
You're right; I fixed that error.

**Comment by alhirzel** [comment]
Specifically, the problem was that _lcd_move was acting on the X axis when under the Y menu.

**Comment by Blue-Marlin** [comment]
Ahhh. Now that makes much more sense to me. :+1:

**Pull request merged**
