### PR TITLE
Touch UI additions and bug fixes

### PR DESCRIPTION
**Pull request by marciot**
### Description

- Make strings which are present in the UI localizable.
- Improve accuracy of code for detecting when an SD print is in progress.
- Add a new bed leveling mesh screen:

bed_leveling

### CODE REVIEW

**Comment by thinkyhead** [comment]
The live mesh editing on the Chiron is quite nice. You can modify mesh coordinates while your test grid or bullseye print is underway, and the machine responds instantly. The mesh values are only changed by a small amount so it's nice and gradual, and the results are easy to see in the layer.

The one thing that would help with this is to have an option on-screen to switch between the 3D view and a simple overhead 2D view so it's easier to quickly select the point that the nozzle will be coming around to again soon.

**Comment by thinkyhead** [comment]
Looks very nice, as always. What would I need to do to get all this new hotness working on that old prototype Lulzbot-colored touch screen that I got from you at MRRF in the days of yore? Or should I go for the latest FTDI hardware?

**Comment by marciot** [comment]
> Looks very nice, as always. What would I need to do to get all this new hotness working on that old prototype Lulzbot-colored touch screen that I got from you at MRRF in the days of yore? Or should I go for the latest FTDI hardware?

The hardware you have is fine. It's a FT810 which is the latest chip my code supports. It's been a while since I configured anything for your setup and my memory from that period is basically shot, so you should have asked me questions back then :) However, I think the following settings are what you need:

LCD_HAOYU_FT810CB
TOUCH_UI_800x480

I don't recall which pinmap you need. but I think it is AO_EXP1_DEPRECATED_PINMAP which is not part of the standard Configuration_adv.h, but you can add it. If that does not work, try the other pinmaps.

Good luck and keep social distancing!

**Comment by thinkyhead** [comment]
Remind me to give you a tour of the Ender 3 V2 interface built on DWIN. It looks like a good basis to perhaps start making native Marlin menu support so there's a color option without sacrificing menu items.

**Pull request merged**
