### PR TITLE
Add VORON printer

### PR DESCRIPTION
**Pull request by Ludy87**

### CODE REVIEW

**Comment by swilkens** [comment]
Are these printers sufficiently stable to have their own config? I was under the impression the VORON design was largely self-build (i.e. users might have different motherboards, drivers, stepper motors... etc). On top of that, aren't there various versions of this? 1.5, 1.6, 2.0, 2.1

**Comment by Ludy87** [comment]
I have found a Fork form Marlin 1.1.8 and have this ported

**Comment by simpai** [comment]
this pins are for version 1.x not v2

**Comment by Ludy87** [comment]
@simpai how do you come to the assumption? See reference.

**Comment by simpai** [comment]
voron2 uses 7 steppers. to support 7 steppers it uses two ramps. 

but pins_VORON.h added recently is not for two ramps.

**Comment by Ludy87** [comment]
@simpai, create a PR 😉

**Pull request merged**
