### PR TITLE
Add TEMP_SENSOR_BOARD

### LINKED ISSUE #20175: [FR] Onboard/Motherboard-based Thermistor Support
### Description

Boards like the Einsy Rambo, BTT002, SKR E3 Turbo, and motherboard used in the Eryone ER-20 have an onboard 100K thermistor, but motherboard/onboard thermistors are not natively supported in Marlin.

There's a "hacky" way to get readings where you define the onboard thermistor as a `TEMP_CHAMBER_PIN` which gives you feedback on the LCD & associated thermal protections, but that's not ideal.

### Feature Workflow

1. Support onboard thermistor with something like `TEMP_MOTHERBOARD_PIN`
2. Show temperature over serial and optionally on the LCD
3. Enjoy thermal protections of motherboard-based thermistors!

### PR DESCRIPTION
**Pull request by slowbro**
### Description

Add TEMP_SENSOR_BOARD for motherboards with integrated/onboard temperature sensors, and integrate it with USE_CONTROLLER_FAN.

### Requirements

The only two boards I know of that have an on-board sensor are BOARD_DUE3DOM_MINI and BOARD_BTT_SKR_E3_TURBO, though this doesn't necessarily require an on-board sensor; one could just use a normal thermistor on an available ADC pin.

### Benefits

Previously, users were assigning the onboard sensor to CHAMBER. This adds a dedicated sensor for the sensor, and allows using it for triggering CONTROLLER_FAN.

I added this as separate commits in case the second thing is unwanted; one could just drop that commit.

### Configurations

```h
#define TEMP_BOARD_PIN 11
#define TEMP_SENSOR_BOARD 1

#define USE_CONTROLLER_FAN
#if ENABLED(USE_CONTROLLER_FAN)
  #define CONTROLLER_FAN_PIN 12           // Set a custom pin for the controller fan
  //#define CONTROLLER_FAN_USE_Z_ONLY       // With this option only the Z axis is considered
  //#define CONTROLLER_FAN_IGNORE_Z         // Ignore Z stepper. Useful when stepper timeout is disabled.
  #define CONTROLLERFAN_SPEED_MIN         0 // (0-255) Minimum speed. (If set below this value the fan is turned off.)
  #define CONTROLLERFAN_SPEED_ACTIVE    255 // (0-255) Active speed, used when any motor is enabled
  #define CONTROLLERFAN_SPEED_IDLE        0 // (0-255) Idle speed, used when motors are disabled
  #define CONTROLLERFAN_IDLE_TIME        60 // (seconds) Extra time to keep the fan running after disabling motors

  #define CONTROLLER_FAN_USE_BOARD_TEMP   // Use TEMP_SENSOR_BOARD as a trigger for enabling the controller fan
  #if ENABLED(CONTROLLER_FAN_USE_BOARD_TEMP)
    #define CONTROLLER_FAN_TRIGGER_TEMP  30 // (°C) Enable the fan when the temperature reaches this temperature
  #endif
                                                                                                                                                                                                                                               
  //#define CONTROLLER_FAN_EDITABLE         // Enable M710 configurable settings
  #if ENABLED(CONTROLLER_FAN_EDITABLE)
    #define CONTROLLER_FAN_MENU             // Enable the Controller Fan submenu
  #endif
#endif
```

### Related Issues

Resolves #20175

### CODE REVIEW

**Comment by slowbro** [comment]
Looking again at the FR, I am going to also add temperature protection for this sensor, i.e. MAXTEMP, as it seems users were utilizing that part of TEMP_SENSOR_CHAMBER.

**Comment by thinkyhead** [comment]
At a certain point it might make sense to stop defining specific types of temp sensors with heaters and/or fan control and/or PID control, and start thinking about just allowing users to define any number of general-purpose temperature sensors with associated temperature ranges and/or heaters and/or fan controls. Perhaps we are nearing that point.

**Comment by slowbro** [comment]
Yes, absolutely! That is something that has been on my mind for a bit, and
I hoped to achieve something to that effect in a wholesale cleanup of the
temperature module at some point in the near future. There is a lot of
duplicated code that can easily be genericized and simplified. From the
perspective of the user, more advanced boards simply label the temp inputs
T0, T1, etc anywho - it would align things more with the real world. Plus,
flexibility abound.

I can switch gears to that, instead of adding another define, if you're up
for a big change of that nature. It would rely on some stuff from #22196,
but I could cherry pick from there as needed if that is still held up in
review. Let me know what you think, and if you'd like to outline the goals
of such a project.

**Comment by thisiskeithb** [comment]
The Einsy Rambo has a motherboard thermistor as well. I listed a few in my feature request, but I’ll see what else is out there: https://github.com/MarlinFirmware/Marlin/issues/20175

**Comment by slowbro** [comment]
> The Einsy Rambo has a motherboard thermistor as well. I listed a few in my feature request, but I’ll see what else is out there: #20175

I wasn't able to find one on the Einsy. Looks like the additional ADC pin is used for the Z Probe.

https://github.com/ultimachine/Einsy-Rambo/blob/1.1a/board/Project%20Outputs/Schematic%20Prints_Einsy%20Rambo_1.1a.PDF

I may have missed it, however..

**Comment by thisiskeithb** [comment]
~~It'll be Therm 1, broken out as connector J3 (for some reason), but is the onboard thermistor~~:

<details><summary>some more old/bad info</summary>



 Z Therm, or the probe thermistor, is in the probe connector J15:


Here's the pin: https://github.com/MarlinFirmware/Marlin/blob/ee4c1839d49766f4f62a9ba14cfbcf82b525be57/Marlin/src/pins/rambo/pins_EINSY_RAMBO.h#L118

</details>

**Comment by slowbro** [comment]
Ah, yeah, that's odd that is has a second, with seemingly only the ability to control one extruder heater. I don't see an onboard PTC or anything in the schematics, though.. just seems like an extra temp header. I'll take your word for it, though, since I don't have one on-hand!

**Comment by thinkyhead** [comment]
Apparently, even AVR boards like the Uno have an onboard thermistor, generally considered not very accurate, so I suppose this common ADC device will need to be included as a standard feature. We can see about further generalizing the temperature sensor code as a follow-on to this PR.

**Comment by slowbro** [comment]
I'll resolve the conflicts, one minute.

**Comment by thisiskeithb** [comment]
I need to do some more investigating, but this locks up a BTT002 when enabled.

**Comment by slowbro** [comment]
@thisiskeithb I pored over the code a bit and realized I missed some things in thermistors.h - that may have been causing the hang on setup when it tries to find the proper mintemp/maxtemp. I also went through and fixed up some other things.

**Comment by slowbro** [comment]
rebased on current bugfix-2.0.x & force-pushed to re-start the tests - they had failed due to a github api timeout.

**Review by slowbro — COMMENTED** [review]
LGTM, I like the HID_* changes, much more user-friendly!

**Comment by thisiskeithb** [comment]
@slowbro I'll ping you on Discord, but this still locks up a BTT002 and SKR E3 Turbo when enabled. Does it work on your boards?

**Comment by slowbro** [comment]
@thisiskeithb it was working for me on an SKR V2 when I tested. Let me take a look again with some other boards. I need to get my hands on a BTT002.

**Comment by slowbro** [comment]
OK, I found it. Couple of things; a) a copy-paste error in temeprature.cpp that I missed, and b) I neglected to add the required stuff to Conditionals_post. With those two fixes, it's no longer hanging on my SKR 1.4. #22343

**Pull request merged**
