### PR TITLE
Improve the descriptions for THERMAL_PROTECTION

### PR DESCRIPTION
**Pull request by Blue-Marlin**
Improve the descriptions for THERMAL_PROTECTION

to simplify the decision what to tune for what error in what direction, if you get false positives.

---

~~Any suggestions for further improvements before i begin to change all the other Configs?~~

We permanently get complains about thermal protection is working too good.
~~It's time to relax the parameters a bit.~~

~~Also~~ It seems not to be obvious how to relax the parameters.
So a better description should be provided here.

---

**EDITED**

### CODE REVIEW

**Comment by jbrazio** [comment]
Seems OK to me.
Do you feel confortable relaxing so much the parameters ? Going from `WATCH_TEMP_PERIOD 16` and `WATCH_TEMP_INCREASE 4`  to `60, 5` is a huge difference.

**Comment by Blue-Marlin** [comment]
Yes, i feel comfortable with this numbers.

My alu hotend (12V 40W relative small heater block) heats 240° to 250° in about 10 seconds with the part fan blowing directly onto it.
When i switch the power off the temperature is falling in the same magnitude.
Heating constantly 250° needs about 60% of power.
When heating to 250°, switching off the power, letting the temperature drop to 240° switching power on again it needs about 20 seconds to reach the 240° again and additional 5 s to reach 245°. That's my worst tested scenario.
As i told before the aluhotend has a relative small heaterblock so i suppose there are hotends that need much longer to switch from cooling to heating lets guess 30s. Doubling that for the margin from bad to defect seems to be reasonable  -> 5/60 = 0.0833°/s

2° is relatively cloth to the noise i have seen on that sensors with Marlin so likely we should use an at least doubled temperature difference.

The former slope was 4/16 = 0.25°/s, so the new one is only 3 times less.
The tested machine runs 4/30 without false positives in the last 6 month with a part fan not blowing directly on the heaterblock.

**Comment by thinkyhead** [comment]
I'm not saying 16 seconds isn't at the edge, but we could probably get away with `WATCH_TEMP_PERIOD 30`. Have you seen any printer that takes more than 30 seconds to raise the temperature by 4 degrees?

The other time intervals are already pretty loose, and will only apply to overshoot. If you have a well-tuned hot end and bed, there's no reason the temperature should fall out of hysteresis range for any longer than a couple of seconds.

Sometimes these failures are a helpful warning to the builder that their printer needs more tuning.

**Comment by jbrazio** [comment]
@thinkyhead please have a look at #3167.

**Comment by Blue-Marlin** [comment]
Rebased.
Parameters now unchanged.
Now just improving the texts.
Completed for all configurations.

**Pull request merged**
