### PR TITLE
Customizable redundant temperature sensor assignment

### PR DESCRIPTION
**Pull request by slowbro**
### Description

Modify the redundant temperature sensor code to add more flexibility around what temperature sensor provides the redundant reading (source), and which temperature sensor should be redundant (target). This keeps all existing functionality, like being able to use dual MAX Thermocouple SPI modules for E0 and E1, but greatly improves one's choices in redundant temperature targets in a (hopefully) intuitive way.

I ran tests locally & *almost* all are passing; the few that aren't don't seem related to this. We'll see how CI goes. Additionally, tests will require changes to MarlinFirmware/Configuration - https://github.com/MarlinFirmware/Configurations/pull/517 . Until then, tests can be run against my branch by changing `EXAMPLES=...` in buildroot/bin/use_example_configs to "https://raw.githubusercontent.com/slowbro/Configurations/redundant-temp-sensor/config/examples"

Finally, there are two unrelated patches tacked on to the end of this:
1. Updating COOLING related variables to follow the format of the others.
2. Stop `which` from complaining about not being able to find `gsed` when running tests locally.

### Requirements

Pins defined for the sensor(s) you plan on using; SS/CS defined for MAX TC (as usual).

### Benefits

This change allows users to add redundant sensors for non-hotend sensors, as well as expands the hotend redundancy capability to all 7 hotends. Before you could only make E1 redundant for E0; now you can:

- Provide redundant temperature sensing for any extruder/hotend
- Add temperature sensor redundancy in laser cooling loops
- Add temperature sensor redundancy on beds, helping limit the risk of overheating and fire (#9162)
- Select the most convenient unused sensor, such as with a printer that doesn't have a bed heater
- Find a purpose those empty thermistor ports!

### Configurations

Very few modifications are needed to test, from the base/default Configuration.h. As a minimal test example, this will get you redundant E0 sensors, like TEMP_SENSOR_1_AS_REDUNDANT did. The default configuration of _SOURCE and _TARGET emulates TEMP_SENSOR_1_AS_REDUNDANT as well:

```
#define TEMP_SENSOR_0 5
#define TEMP_SENSOR_REDUNDANT 5

#define TEMP_SENSOR_REDUNDANT_SOURCE     1  // The sensor that will provide the redundant reading.
#define TEMP_SENSOR_REDUNDANT_TARGET     0  // The sensor that we are providing a redundant reading for.
#define TEMP_SENSOR_REDUNDANT_MAX_DIFF  10  // (°C) Temperature difference that will trigger a print abort.

```

and this will get you redundant bed sensors, using TEMP_SENSOR_2 (assuming you have TEMP_2_PIN)...:
```
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_BED 1
#define TEMP_SENSOR_REDUNDANT 1

#define TEMP_SENSOR_REDUNDANT_SOURCE     2  // The sensor that will provide the redundant reading.
#define TEMP_SENSOR_REDUNDANT_TARGET    -1  // The sensor that we are providing a redundant reading for.
#define TEMP_SENSOR_REDUNDANT_MAX_DIFF  10  // (°C) Temperature difference that will trigger a print abort.
```

### Related Issues
Issue #9162
https://github.com/MarlinFirmware/Configurations/pull/517

### CODE REVIEW

**Comment by thinkyhead** [comment]
At first I gawped, but everything looks good! Maybe I'll try to move all that thermistor `Conditionals_*.h` code into a separate header to reduce the number of globally-defined macros.

**Review by slowbro — COMMENTED** [review]
FYI on my linux box (which doesn't have gsed), it still prints the 'error' of not being able to find gsed.

```
[katelyn@h Marlin]$ which gsed sed | head -n1
which: no gsed in (/home/katelyn/bin:/home/katelyn/.rvm/gems/ruby-2.6.5/bin:/home/katelyn/.rvm/gems/ruby-2.6.5@global/bin:/home/katelyn/.rvm/rubies/ruby-2.6.5/bin:/home/katelyn/bin:/home/katelyn/bin:/usr/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda-9.0/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/katelyn/.rvm/bin:/opt/cuda-9.0/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/home/katelyn/.rvm/bin:/opt/cuda-9.0/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin:/home/katelyn/.rvm/bin)
/usr/bin/sed
```

(also, jeez, my PATH is huge)

vs..

```
[katelyn@h Marlin]$ which gsed sed 2>/dev/null | head -n1
/usr/bin/sed
```

I like the double-argument `which`!

**Comment by slowbro** [comment]
> At first I gawped, but everything looks good! Maybe I'll try to move all that thermistor `Conditionals_*.h` code into a separate header to reduce the number of globally-defined macros.

Awesome! Let me know if you'd like help with that!

**Review by slowbro — COMMENTED** [review]
ah.. since it's always expanding TT_REV now with the value of TEMP_SENSOR_*, when a temp sensor is a thermocouple (< 0), it's trying to expand like "REVERSE_TEMP_SENSOR_RANGE_-1"

```
#ifndef TEMP_SENSOR_0_RAW_HI_TEMP
  #if TT_REVRAW(0)
    #define TEMP_SENSOR_0_RAW_HI_TEMP MAX_RAW_THERMISTOR_VALUE
    #define TEMP_SENSOR_0_RAW_LO_TEMP 0
  #else
    #define TEMP_SENSOR_0_RAW_HI_TEMP 0
    #define TEMP_SENSOR_0_RAW_LO_TEMP MAX_RAW_THERMISTOR_VALUE
  #endif
#endif
```

**Comment by slowbro** [comment]
Woot, cheers! :tada:

**Comment by salfter** [comment]
This commit breaks at least one of my printer configs: an AM8 with an SKR 1.4 Turbo and a MAX31865 RTD breakout:

```
In file included from Marlin\src\module\../inc/MarlinConfigPre.h:37,
                 from Marlin\src\module\../inc/MarlinConfig.h:28,
                 from Marlin\src\module\../MarlinCore.h:24,
                 from Marlin\src\module\temperature.cpp:30:
e:\tmp\marlin\marlin\src\core\macros.h:193:48: error: pasting "ENA_" and "(" does not give a valid preprocessing token
  193 | #define _ENA_1(O)           _ISENA(CAT(_IS,CAT(ENA_, O)))
      |                                                ^~~~
e:\tmp\marlin\marlin\src\core\macros.h:184:22: note: in definition of macro '_CAT'
  184 | #define _CAT(a,V...) a##V
      |                      ^
e:\tmp\marlin\marlin\src\core\macros.h:193:44: note: in expansion of macro 'CAT'
  193 | #define _ENA_1(O)           _ISENA(CAT(_IS,CAT(ENA_, O)))
      |                                            ^~~
e:\tmp\marlin\marlin\src\core\macros.h:202:35: note: in expansion of macro '_ENA_1'
  202 | #define TERN_(O,A)          _TERN(_ENA_1(O),,A)     // OPTION ? 'A' : '<nul>'
      |                                   ^~~~~~
Marlin\src\module\temperature.cpp:2090:5: note: in expansion of macro 'TERN_'
 2090 |     TERN_(TEMP_SENSOR_IS_MAX(0, MAX31865), max31865_0.begin(MAX31865_2WIRE)); // MAX31865_2WIRE, MAX31865_3WIRE, MAX31865_4WIRE
      |     ^~~~~
e:\tmp\marlin\marlin\src\core\macros.h:193:48: error: pasting "ENA_" and "(" does not give a valid preprocessing token
  193 | #define _ENA_1(O)           _ISENA(CAT(_IS,CAT(ENA_, O)))
      |                                                ^~~~
e:\tmp\marlin\marlin\src\core\macros.h:184:22: note: in definition of macro '_CAT'
  184 | #define _CAT(a,V...) a##V
      |                      ^
e:\tmp\marlin\marlin\src\core\macros.h:193:44: note: in expansion of macro 'CAT'
  193 | #define _ENA_1(O)           _ISENA(CAT(_IS,CAT(ENA_, O)))
      |                                            ^~~
e:\tmp\marlin\marlin\src\core\macros.h:202:35: note: in expansion of macro '_ENA_1'
  202 | #define TERN_(O,A)          _TERN(_ENA_1(O),,A)     // OPTION ? 'A' : '<nul>'
      |                                   ^~~~~~
Marlin\src\module\temperature.cpp:2091:5: note: in expansion of macro 'TERN_'
 2091 |     TERN_(TEMP_SENSOR_IS_MAX(1, MAX31865), max31865_1.begin(MAX31865_2WIRE));
      |     ^~~~~
Marlin\src\module\temperature.cpp: In member function 'void Temperature::init()':
Marlin\src\module\temperature.cpp:2091:44: error: 'max31865_1' was not declared in this scope; did you mean 'max31865_0'?
 2091 |     TERN_(TEMP_SENSOR_IS_MAX(1, MAX31865), max31865_1.begin(MAX31865_2WIRE));
      |                                            ^~~~~~~~~~
e:\tmp\marlin\marlin\src\core\macros.h:558:26: note: in definition of macro 'THIRD'
  558 | #define THIRD(a,b,c,...) c
      |                          ^
e:\tmp\marlin\marlin\src\core\macros.h:204:29: note: in expansion of macro '___TERN'
  204 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
      |                             ^~~~~~~
e:\tmp\marlin\marlin\src\core\macros.h:203:29: note: in expansion of macro '__TERN'
  203 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
      |                             ^~~~~~
e:\tmp\marlin\marlin\src\core\macros.h:202:29: note: in expansion of macro '_TERN'
  202 | #define TERN_(O,A)          _TERN(_ENA_1(O),,A)     // OPTION ? 'A' : '<nul>'
      |                             ^~~~~
Marlin\src\module\temperature.cpp:2091:5: note: in expansion of macro 'TERN_'
 2091 |     TERN_(TEMP_SENSOR_IS_MAX(1, MAX31865), max31865_1.begin(MAX31865_2WIRE));
      |     ^~~~~
```

**Comment by slowbro** [comment]
I'll take a look. Could you upload your configs so I can test?

**Comment by salfter** [comment]
[marlin-am8-config.zip](https://github.com/MarlinFirmware/Marlin/files/6665936/marlin-am8-config.zip)

**Comment by slowbro** [comment]
@salfter Can you try applying this patch (or cloning my repo) and seeing if it builds for you? I was able to get it to build on my end with LPC1769.

https://github.com/slowbro/Marlin/commit/05ff1f4c8f8872714533402b4103b1e7cd4d32fa

Also, your config seems to be missing some parts that were added in 2.0.9, namely..

https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/Configuration.h#L475
https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/Configuration.h#L499-L519
https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/Configuration_adv.h#L128-L132

These missing sections shouldn't be a problem, but I identified an issue with them missing which was also fixed in the above patch. You may want to diff your configs with the latest and make sure you have all the new sections.

I had some weirdness with the Adafruit MAX31865 library, as well - it kept looking for 'WProgram.h" even though I'm pretty sure I have the newest Arduino stuff installed. Weird. Have you experienced that?

**Comment by salfter** [comment]
> slowbro@05ff1f4

With that patch, the code builds...getting ready to test it.

(By the time I finished writing this, the updated code was on my AM8 and it was warming up to print a calibration cube.  Looks like things are probably OK now.)

> your config seems to be missing some parts

I had reverted to the last commit that worked for me, which was from about a week ago.  I merged all the recent commits just now and those changes showed up in my config.

> I had some weirdness with the Adafruit MAX31865 library, as well - it kept looking for 'WProgram.h"

On LPC176x, there's a line in Adafruit_MAX31865.h that needs to be changed:

```
#if (ARDUINO >= 100)
```

should be

```
#if (ARDUINOLPC >= 100)
```

Otherwise, the build fails.  A more portable fix might look something like this:

```
#if (ARDUINO >= 100 || ARDUINOLPC >= 100)
```

It's not the best-written driver in the world; it has a number of busy waits within that can bring Marlin to a crawl.  That's straying beyond the scope of this thread, though. :)

**Comment by slowbro** [comment]
Yep, that's more or less what I ended up doing. That should probably be fixed. I'll log a ticket about it and see if I can't get around to it. Edit: actually, this was supposed to have been fixed in #20132... investigating more.

I put in PR #22173 that contains the changes above, so this should be fixed in bugfix soon! Thanks for letting me know.

**Comment by qrstu** [comment]
Probably if have posted wrong location. :-( 
--> #22173 #20132
Marlin-bugfix-2.0.x,zip --> 19-JUN-2021 --> Using Marlin 2.0.9

Coding Error --> \Marlin\src\module\temperature.cpp
Sorry, if found some coding error.
Compile not possible when using MAX31855 for HOTEND

Line 2103 Should be --> max31855_0.begin();
Line 2106 Should be --> max31855_1.begin();
Line 2112 Should be --> max6675_0.begin();
Line 2115 Should be --> max6675_1.begin();
Line 2733 Should be --> SERIAL_ECHOPAIR("MAX31855 Fault : (", max_tc_temp & 0x7, ") >> ");

Compiled and tested for
#define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
#define TEMP_SENSOR_0 -3

Hardware SPI --> pins_BTT_SKR_V1_4.h
#define TEMP_0_PIN P0_26
#define MAX31855_CS_PIN TEMP_0_PIN
#define MAX6675_SS_PIN MAX31855_CS_PIN

features.ini
#TEMP_.+_IS_MAX31865                    = Adafruit MAX31865 library@~1.1.0
TEMP_.+_IS_MAX31855                    = https://github.com/GadgetAngel/Adafruit-MAX31855-V1.0.3-Mod-M.git

lpc176x.ini
build_flags       = ${common.build_flags} -DU8G_HAL_LINKS -IMarlin/src/HAL/LPC1768/include -IMarlin/src/HAL/LPC1768/u8g -DLIB_MAX31855=1

Is working with correct temperature ;-)

Could you please adapt this changes, please

Thanks
Regards
Martin

**Comment by slowbro** [comment]
Martin - I'm taking a look now and should have a patch submitted soon.

**Comment by slowbro** [comment]
@qrstu can you please try against this branch? https://github.com/slowbro/Marlin/tree/redundant-temp-fixups-2

I went through and genericized the MAXTC pins because, imo, always having to set `MAX6675_SS_PIN` regardless of the MAX TC type is confusing. You can just set `MAXTC_CS_PIN` now and it should work. You will need to keep your changes to `lpc176x.ini` and `features.ini` if you want to use that repository instead of the Adafruit one - that was discussed somewhere else but I don't recall where.

**Comment by qrstu** [comment]
Hello Katelyen,
I could do some Basic Tests, compile.... 
they are looking Good.
But the pin assignment for thermocouple I couldn‘t Test because i have Not access to the Printer Till Weekend.
I will respond when I did. the Verification/Tests.

Regards 
Martin

Von meinem iPhone gesendet

**Comment by slowbro** [comment]
@qrstu the issues you reported have been solved and fixes merged into bugfix-2.0.x. Thank you!

**Pull request merged**
