### PR TITLE
Adding HMS434 machine

### PR DESCRIPTION
**Pull request by maukcc**
### Description
Adding HMS434 machine
Adding thermistor table as table 1, but with a power supply of 3V3

### CODE REVIEW

**Comment by AnHardt** [comment]
Did you do a reality check?
For thermistors, when comparing resistances, the analog supply voltage should short out of the equation.

**Comment by maukcc** [comment]
> Did you do a reality check?

yes, we have been using this successfully for some time now.

> For thermistors, when comparing resistances, the analog supply voltage should short out of the equation.

No, the analog voltage will change and therefor also the temp readout. The input pin expects a voltage referenced to 5V, but instead gets it referenced to 3V3. In our case the exact voltage is 3.27 resulting in the 3.27:5=0.654 value in the table.

A more elegant way to go about it would be a define for the supply voltage.

**Comment by thinkyhead** [comment]
> No, the analog voltage will change and therefor also the temp readout. The input pin expects a voltage referenced to 5V, but instead gets it referenced to 3V3. In our case the exact voltage is 3.27 resulting in the 3.27:5=0.654 value in the table.

It is peculiar that the board has an ADC referenced to 5V when the only supply voltage available for analog devices is 3.3V. Is this due to the chip itself having 5V logic but it is being mated to a board that is otherwise 3.3V? Too bad we can't flip a switch in the chip to tell it to use 3.3V logic!

**Comment by maukcc** [comment]
Our mainboard supply voltage to external components is 3V3. The processor on the mainboard is a MEGA(for now). We will switch to due in the near future.

**Review by maukcc — COMMENTED** [review]
about f2a1030
Any reason why this is taken out of the example. As we think this is much easier to read.

**Comment by thinkyhead** [comment]
Where is this machine / board advertised and sold? Is it popular?

**Comment by maukcc** [comment]
The board is not sold separately, only within the HMS434 machine:
www.hybridamsystems.com

It is a mainboard that can use a MEGA or Due. The mainboard does not do anything but send signals to a power control board. see: http://hybridamsystems.com/wp-content/uploads/2019/08/IMG_20190817_112330.jpg

**Comment by tpruvot** [comment]
so i tried to use 331 as thermistor to try. and i got that

> 
> In file included from Marlin\src\lcd\menu\menu_info.cpp:31:0:
> Marlin\src\lcd\menu\menu_info.cpp: In function 'void menu_info_thermistors()':
> Marlin\src\lcd\menu\menu_info.cpp:102:22: error: expected ')' before 'THERMISTOR_NAME'
>    STATIC_ITEM("T0: " THERMISTOR_NAME, false, true);
>                       ^
> Marlin\src\lcd\menu\menu.h:330:41: note: in definition of macro 'STATIC_ITEM_P'
>        draw_menu_item_static(_lcdLineNr, PLABEL, ## __VA_ARGS__); \
>                                          ^~~~~~
> Marlin\src\lcd\menu\menu.h:341:47: note: in expansion of macro 'PSTR'
>  #define STATIC_ITEM(LABEL, ...) STATIC_ITEM_P(PSTR(LABEL), ## __VA_ARGS__)
>                                                ^~~~
> Marlin\src\lcd\menu\menu_info.cpp:102:3: note: in expansion of macro 'STATIC_ITEM'
>    STATIC_ITEM("T0: " THERMISTOR_NAME, false, true);
>    ^~~~~~~~~~~
> Marlin\src\lcd\menu\menu.h:330:64: error: expected ')' before ';' token
>        draw_menu_item_static(_lcdLineNr, PLABEL, ## __VA_ARGS__); \
>                                                                 ^
> Marlin\src\lcd\menu\menu.h:341:33: note: in expansion of macro 'STATIC_ITEM_P'
>  #define STATIC_ITEM(LABEL, ...) STATIC_ITEM_P(PSTR(LABEL), ## __VA_ARGS__)
>                                              ^~~~
> Marlin\src\lcd\menu\menu_info.cpp:102:3: note: in expansion of macro 'STATIC_ITEM'
>    STATIC_ITEM("T0: " THERMISTOR_NAME, false, true);
>    ^~~~~~~~~~~
> Marlin\src\lcd\menu\menu.h:330:64: error: expected ')' before ';' token
>        draw_menu_item_static(_lcdLineNr, PLABEL, ## __VA_ARGS__); \

**Comment by tpruvot** [comment]
```
--- a/Marlin/src/lcd/thermistornames.h
+++ b/Marlin/src/lcd/thermistornames.h
@@ -92,6 +92,8 @@
   #define THERMISTOR_NAME "Hephestos 2"
 #elif THERMISTOR_ID == 75
   #define THERMISTOR_NAME "MGB18"
+#elif THERMISTOR_ID == 331
+  #define THERMISTOR_NAME "EPCOS 100K 3.3V"

```

**Pull request merged**
