### PR TITLE
Fix IntelliSense conflicts

### PR DESCRIPTION
**Pull request by robbycandra**
Commit c91451d2 makes Intelisense stuck. 

Reverting the lines that make intelisense stop working.

### CODE REVIEW

**Comment by thinkyhead** [comment]
The filters are needed to prevent VSCode + PlatformIO running the code in these scripts outside of an actual build.

AFAIK IntelliSense shouldn't be interacting with PlatformIO / SCONS at all, so I'm not sure why anything in the `.py` files would make a difference. I'll have to do some experiments to see what's going on and find a replacement for `env.Exit(0)` that doesn't bother IntelliSense.

**Comment by thinkyhead** [comment]
Give this a try and see if the updated approach of simply avoiding `env.Exit(0)` does the trick.

**Comment by robbycandra** [comment]
In my test, Intelisense work for mega, BTT SKR 1.3, BTT SKR 14
NOT working for MKS ROBIN MINI and BTT SKR PRO

**Comment by robbycandra** [comment]
In my test, after second commit, then
- Intelisense works for mega, BTT SKR 1.3, BTT SKR 14
- NOT working for MKS ROBIN MINI and BTT SKR PRO

But without second commit, intelisense works for all board

**Comment by thinkyhead** [comment]
I reckon those targets have more scripts. Probably need to add similar wrappers to all referenced scripts, in case any one is set as the default target.

**Pull request merged**
