### PR TITLE
Add GT2560 v3 support

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Add pins file for GT2560_V3.0 from Prusa code base for Phr3d13 as requested to finish sample configs

### CODE REVIEW

**Comment by Phr3d13** [comment]
@thinkyhead This compiles and I'll be testing it shortly.

**Comment by InsanityAutomation** [comment]
He's probably hibernating a few days after Maker faire!

**Comment by thinkyhead** [comment]
The spacing is quite f*&$ed but I’ll clean it up and review it later today.

**Comment by tcm0116** [comment]
>The spacing is quite f*&$ed but I’ll clean it up and review it later today.

Shall we start calling you Linus?

**Comment by InsanityAutomation** [comment]
@tcm0116 Someone needs to fill the void! :)

**Comment by thinkyhead** [comment]
Offtopic. Anyway, sure, if I start telling people who don't pay attention to Marlin [coding standards](http://marlinfw.org/docs/development/coding_standards.html) and [commit message guidelines](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#git-commit-messages) to go kill themselves, you can call me Linus or whatever you like.

**Pull request merged**
