### PR TITLE
Update marlin_STM32H743Vx.json

### PR DESCRIPTION
**Pull request by JoaquinBerrios**
### Description

Correcting value for f_cpu from 400000000L to 480000000L since this is a 480Mhz CPU, not 400Mhz.

### Requirements

None 

### Benefits

Corrects typo. 

### Configurations

N/A

### Related Issues

None

### CODE REVIEW

**Comment by thisiskeithb** [comment]
The SKR BX with a similar MCU is underclocked as well:

https://github.com/MarlinFirmware/Marlin/blob/5f61a896d99688da64b3bfb557f5d76302b555e7/buildroot/share/PlatformIO/boards/marlin_BTT_SKR_SE_BX.json#L6

Edit: I've updated my BX with the correct MCU speed & it seems to work fine.

**Comment by ellensp** [comment]
@thisiskeithb SKR SE BX V2.0 is under clocked to 400 according to the little documentation I can find.
However the SKR 3 is advertised as 480

**Comment by thisiskeithb** [comment]
> @thisiskeithb SKR SE BX V2.0 is under clocked to 400 according to the little documentation I can find.
> However the SKR 3 is advertised as 480

What documentation? I know I’ve had them fix marketing materials for that MCU/printer in the past, but I don’t see why it should be underclocked here.

**Comment by sl1pkn07** [comment]
743 is 480Mhz following ST datasheet

https://www.st.com/en/microcontrollers-microprocessors/stm32h743-753.html

**Comment by thinkyhead** [comment]
480MHz is also backed up by this line in `variant_MARLIN_STM32H743VX.cpp`…
```cpp
  RCC_OscInitStruct.PLL.PLLP = 2;  // 960Mhz / 2 = 480Mhz
```

**Pull request merged**
