### PR TITLE
Using "LCD for Melzi" Full Graphics Board with Melzi Controller

### PR DESCRIPTION
**Pull request by webliya**
The definition here allows users to select and use "LCD for Melzi" Full Graphics Board with Melzi Controller. 

Configuration.h

//LCD for MELZI
#define LCD_MELZI true
#define ST7920_DELAY_1 DELAY_0_NOP
#define ST7920_DELAY_2 DELAY_3_NOP
#define ST7920_DELAY_3 DELAY_0_NOP

pins_SANGUINOLOLU_11.h

   #endif // !Panelolu2
 
+  #if LCD_MELZI
+	#define LCD_PINS_RS       17
+	#define LCD_PINS_ENABLE   16
+	#define LCD_PINS_D4       11
+	#define BTN_ENC           28
+	#define BTN_EN1           29
+	#define BTN_EN2           30
+  #endif // LCD MELZI
+
   #define SD_DETECT_PIN         -1
 
 #endif // ULTRA_LCD && NEWPANEL

I have tested with 2 different versions of Melzi boards (3 & 4) and all worked.

Can

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Philosophically...  I'm opposed to doing a merge on something that has altered 163 files.  There is no way we can review this for 'correctness'.   There is no way getting an LCD Display to work with the Melzi board requires this many changes....

Can you use the current code base and just add the required changes to get the Melzi board to work with the graphical controller?  And then submit those changes as a Pull Request?

**Comment by fiveangle** [comment]
...and I was under the impression every LCD shipped with Melzi printers was in fact some other LCD and has been working for others ?

https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/pins_SANGUINOLOLU_11.h#L155-L225

**Comment by thinkyhead** [comment]
Sorry, you'll need to re-target this to `bugfix-1.1.x`, otherwise it messes with the Github tools that we use to review PRs, as you can see…

**Comment by thinkyhead** [comment]
> I'm opposed to doing a merge on something that has altered 163 files.

Must be something wrong with the PR…

**Comment by webliya** [comment]
I am not sure if I  use github for PR correctly/ Now I do it again in a
correct way I assume.

On my Github desktop;

1. I forked the Marlin
2. I created a new branch from base1.1x for this change only
3. I commit
4. I created a pull request (LCD for Melzi support #7206)

If this is the correct way please inform. If not please show me the correct
way. Thanks in advance.

Cheers,
Can

**Comment by thinkyhead** [comment]
In the form to create a pull request make sure you are **_targeting_** the `bugfix-1.1.x` branch.

**Comment by Bob-the-Kuhn** [comment]
The Marlin Wiki has a document that goes through all the steps needed to create a pull request against bugfix-1.1.x

http://marlinfw.org/docs/development/getting_started_pull_requests.html

**Comment by thinkyhead** [comment]
…and where the documentation says "`RCBugFix`" think: "`bugfix-1.1.x`"…

**Comment by webliya** [comment]
thnx for all.

**Pull request closed without merging**
