### PR TITLE
M20 L : Long filename SD list

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

SDSUPPORT and a sd card with long paths and filenames.

### Description

Adds define LONG_FILENAME_MEDIA_LIST in Configuration_adv.h to compile in M20 L support. 
Extends M20 gcode with a L parameter that add long paths and filenames to the file list.
Without L parameter M20 is identical to previous versions to ensure software compatibility. 

### Benefits

Allows client software to display short or long names and paths from SD/Media

### Related Issues

Issue #19091

### CODE REVIEW

**Comment by thinkyhead** [comment]
There is a better approach for clients, and I don't know why none of them have followed our guidance on this.

First you get the short listing so that you have the full paths in DOS 8.3 format. You can then can quickly populate your file dialog with the 8.3 names in view. In the background, you then send `M33` to request the long filename for each item that you want to display in long form.

Another thing in this arena that needs to be completed is the JSON-formatted file listing code started in #10610, which will allow the PanelDue to acquire file listings in the manner it prefers, and which will also allow hosts to use the same method if they choose.

**Comment by bitboy85** [comment]
Sad that this feature seems to have reached a dead end. There is a large discussion in the octoprint community why the way you described will NOT be implemented...
https://github.com/OctoPrint/OctoPrint/issues/1600

**Comment by ellensp** [comment]
Please reconsider. this feature is completely optional. All code removed with ifdef. If you don't want to enable it you don't have to activate it.

**Comment by thinkyhead** [comment]
To tell you the truth, while I view more complete longname support as a welcome addition, coding all of these pieces without accidentally making `CardReader` more unstable and RAM-hungry has always been a scary prospect. I guess we have certain luxuries now in 2020 and can take on these more daunting challenges with less fear.

So, anyway, it's a nifty user feature to be able to get a more "readable" file listing, but it's useless from a host point of view until long filenames can be used as the path to start a print job, because there's no way to correlate a long path with a DOS8.3 path. Maybe it should just spit out the inode of each file so hosts can tell Marlin to run a file job by its number.

Because… to be able to start a print job with a long filename path, `GCODE_QUOTED_STRING` might be helpful, then hosts could send a quoted string pathname to print a relative path that starts with a space using the long-name. I expect that locating a file by long-name is going to be a relatively slow operation…. Of course, it can be optimized by looking at the DOS8.3 name and seeing that it is not a plausible match, and so on….

Should be fun to solve!

One way to make the full long listing less verbose would be to have `M20 L S` emit the listing in a shorthand form…. A host could populate a tree of files and folders pretty easily from a compact format something like this…
```
M20> /
/My Long File.gcode 213451
/A lengthy folder name/My Inner File.gcode 963635
//Another Inner File.gcode 534967
//Inner Inner Folder/Two Levels Down.gcode 22544
////Looks Hierarchical.gcode  173451
////Last Two-Level File.gcode 1247267
//Third file in lengthy folder.gcode 84535
/Second root file.gcode 125632
<M20
```

**Comment by Roxy-3D** [comment]
Also...   Please let me add this perspective to the equation.

M20 and all of the SD-Card file name stuff is an abortion.   It is totally outside of the normal G-Code syntax

If we are going to support long file names, let's really handle them.   Including everything from special characters to spaces in the long file name.   Let's also support UFC filenames and what ever unicode things there are.    Let really handle it.

Personally, I think this discussion is bigger than M20 just because the normal G-Code syntax is so oppressive.   If we can find a good way to extend the 'Accepted' G-Code syntax to resolve this issue....   Let's make sure it also allows a lot of flexibility on other G-Codes and their parameters too...   

It may sound like I'm pushing back.   I'm not.   I think G-Code is horribly oppressive.   Can we come up with a good syntax extension that allows the flexibility we need?    This probably is a good test case to work through the issues.

**Comment by thinkyhead** [comment]
That's a reason to appreciate the existence of the DOS8.3 limitation on file paths. Long filenames can use accented characters and may be in any language and any agreed-upon multi-byte format such as UTF-8 or UTF-16, whereas the host/LCD RS2xxx serial interface is theoretically limited to the 7-bit ASCII subset for maximum compatibility. Given the limitations of common serial protocols, the DOS8.3 paths are a reliable shorthand. Long-names should be considered a decoration on top for the benefit of human-readable user interfaces.

We've had `G33` around for a good long time, with the intention that host developers should take advantage of it. But it does require some work to integrate. So maybe they'd prefer an interactive shell with commands like `cd` and `ls` that the firmware actually implements and they can hide "MarlinDOS" behind a pretty UI….

**Comment by Roxy-3D** [comment]
> So maybe they'd prefer an interactive shell with commands like cd and ls that the firmware actually implements and they can hide "MarlinDOS" behind a pretty UI….

Good point...   This is a slippery slope!

**Pull request closed without merging**
