### PR TITLE
User Command (Script) Menu

### PR DESCRIPTION
**Pull request by Tannoo**
User command Menu option.

The menu 'commands / scripts) are configurable in `configuration_adv.h`.
This stemmed from #6857.

### CODE REVIEW

**Comment by Tannoo** [comment]
@batata004, this PR still needs a little tweaking to work as you say. But, for now, you can comment out the other lines in `ultralcd.cpp`:
```
    void _lcd_user_menu() { 
      START_MENU(); 
      MENU_BACK(MSG_MAIN); 
      MENU_ITEM(gcode, USER_DESC_1, PSTR(USER_GCODE_1)); 
      // MENU_ITEM(gcode, USER_DESC_2, PSTR(USER_GCODE_2)); 
      // MENU_ITEM(gcode, USER_DESC_3, PSTR(USER_GCODE_3)); 
      // MENU_ITEM(gcode, USER_DESC_4, PSTR(USER_GCODE_4)); 
      // MENU_ITEM(gcode, USER_DESC_5, PSTR(USER_GCODE_5)); 
      END_MENU(); 
    } 

I will get this sorted in the next day or two so that this will be automatic if you comment out one or more of the options in configuration_adv.h, then those will not show up in the menu.

**Comment by Roxy-3D** [comment]
Perhaps....   (Indenting isn't quite right...)
```cpp
    void _lcd_user_menu() { 
      START_MENU(); 
      MENU_BACK(MSG_MAIN); 
      #ifdef USER_GCODE_1
        MENU_ITEM(gcode, USER_DESC_1, PSTR(USER_GCODE_1)); 
        #ifdef USER_GCODE_2
          MENU_ITEM(gcode, USER_DESC_2, PSTR(USER_GCODE_2)); 
          #ifdef USER_GCODE_3
            MENU_ITEM(gcode, USER_DESC_3, PSTR(USER_GCODE_3)); 
            #ifdef USER_GCODE_4
             MENU_ITEM(gcode, USER_DESC_4, PSTR(USER_GCODE_4)); 
              #ifdef USER_GCODE_5
                MENU_ITEM(gcode, USER_DESC_5, PSTR(USER_GCODE_5)); 
              #endif
            #endif
          #endif
       #endif
      END_MENU(); 
    } 
```

**Comment by Tannoo** [comment]
I was just putting that together.. :)

I'm doing it a little different though.
```
    void _lcd_user_menu() {
      START_MENU();
      MENU_BACK(MSG_MAIN);
      MENU_ITEM(gcode, USER_DESC_1, PSTR(USER_GCODE_1));
      #ifdef USER_DESC_2
        MENU_ITEM(gcode, USER_DESC_2, PSTR(USER_GCODE_2));
      #endif
      #ifdef USER_DESC_3
        MENU_ITEM(gcode, USER_DESC_3, PSTR(USER_GCODE_3));
      #endif
      #ifdef USER_DESC_4
        MENU_ITEM(gcode, USER_DESC_4, PSTR(USER_GCODE_4));
      #endif
      #ifdef USER_DESC_5
        MENU_ITEM(gcode, USER_DESC_5, PSTR(USER_GCODE_5));
      #endif
      END_MENU();
    }

```

**Comment by Tannoo** [comment]
That way, you can have 1 and 4 but not 2, 3, or 5 enabled.

**Comment by Roxy-3D** [comment]
Yes...

**Comment by Tannoo** [comment]
Also:
```
#if ENABLED(CUSTOM_USER_MENUS)
  #define USER_DESC_1 "Home & Info"
  #define USER_GCODE_1 "G28\nM503"

  #define USER_DESC_2 "Second Script"
  #define USER_GCODE_2 "G28\nM503"
  #ifdef USER_DESC_2
    #define USER_GCODE_2 "G28\nM503"
  #endif

  #define USER_DESC_3 "Third Script"
  #define USER_GCODE_3 "G28\nM503"
  #ifdef USER_DESC_3
    #define USER_GCODE_3 "G28\nM503"
  #endif

  #define USER_DESC_4 "Fourth Script"
  #define USER_GCODE_4 "G28\nM503"
  #ifdef USER_DESC_4
    #define USER_GCODE_4 "G28\nM503"
  #endif

  #define USER_DESC_5 "Fifth Script"
  #define USER_GCODE_5 "G28\nM503"
  #ifdef USER_DESC_2
    #define USER_GCODE_5 "G28\nM503"
  #endif
#endif
```

**Comment by Tannoo** [comment]
Also:
```
#if ENABLED(CUSTOM_USER_MENUS)
  #define USER_DESC_1 "Home & Info"
  #define USER_GCODE_1 "G28\nM503"

  #define USER_DESC_2 "Second Script"
  #ifdef USER_DESC_2
    #define USER_GCODE_2 "G28\nM503"
  #endif

  //#define USER_DESC_3 "Third Script"
  #ifdef USER_DESC_3
    #define USER_GCODE_3 "G28\nM503"
  #endif

  //#define USER_DESC_4 "Fourth Script"
  #ifdef USER_DESC_4
    #define USER_GCODE_4 "G28\nM503"
  #endif

  //#define USER_DESC_5 "Fifth Script"
  #ifdef USER_DESC_2
    #define USER_GCODE_5 "G28\nM503"
  #endif
#endif
```

**Comment by Tannoo** [comment]
Now updated to the latest bugfix as of now.

**Comment by Tannoo** [comment]
Any specific default command scripts to use?

I chose to home and display EEPROM info. (No harm done if EEPROM is not enabled)

**Comment by Roxy-3D** [comment]
Let's see...   
- Heat Bed and Nozzle
- Home
- Extrude 10mm of  filament
- ????

There might be an easy way to use the pre-processor to get better titles.   Let's wait for Thinky to add his $.02 to it...

**Comment by Tannoo** [comment]
Maybe change USER_DESC_x to USER_ITEM_x?

**Comment by batata004** [comment]
@Tannoo when you said it was updated to the latest rcbugfix you say your implementation it already merged to the main branch?

**Comment by Tannoo** [comment]
No, I updated the PR.

**Comment by Tannoo** [comment]
I also changed a few things to not show the menu items that are disabled.

**Comment by Roxy-3D** [comment]
> Maybe change USER_DESC_x to USER_ITEM_x?

Or maybe CUSTOM_USER_ITEM_1  ???

And each Examples/Configuration_adv.h file would have to be modified to have the commented out version so it is ready to modify (and enable).

**Comment by Tannoo** [comment]
Oh I know. I haven't got that far yet. I'll get them, I have to take a nap first. Been working all night.

**Comment by Roxy-3D** [comment]
> Oh I know. I haven't got that far yet. I'll get them, I have to take a nap first. Been working all night.

As it turns out...  AstroGrep is super helpful on that.  You can configure it to edit (and go to the line it is displaying).  So you can cut some text to the clipboard.  And then just click on each file's text and insert it.  You can do all of the various Example/Configuration_adv.h files in 5 or 10 minutes.

**Comment by Tannoo** [comment]
Ok... this is not working..

```
char user_lcd_gcode[30];
snprintf_P(user_lcd_gcode, sizeof(user_lcd_gcode), PSTR(USER_GCODE_3), PREHEAT_2_TEMP_BED);
enqueue_and_echo_command(user_lcd_gcode);
```
It formats the string with the correct values, but the output is not being interpreted correctly.

I got around this last time by dropping the use of this entrely and used `MENU_ITEM(gcode....`. And it worked perfectly.

What am I missing?

**Comment by Tannoo** [comment]
Could it be that:
`#define USER_GCODE_3 "M140 S%i\nG28\nG29"`

Needs to be:
`#define USER_GCODE_3 "M140 S%S\nG28\nG29"`?

**Comment by batata004** [comment]
Man, if you can make the code below to work it would be awsome.

`#define USER_GCODE_1 something("M140 S%S\nG28\nG29",PREHEAT_2_TEMP_BED)`

No need to multiple lines to set the USER_GODE (as @Tannoo previous solution that needed at least 3 lines).

**Comment by Tannoo** [comment]
What do you think I am trying to do? I'm at work tonight. Will play with it some more in the morning.

**Comment by Roxy-3D** [comment]
> #define USER_GCODE_3 "M140 S%S\nG28\nG29"?

% capital S is probably not the 'right' answer...

**Comment by batata004** [comment]
thanks man @Tannoo , I know you are doing your best! It was a really big help to implement this custom menus! It is really nice and handful! :)

**Comment by Tannoo** [comment]
Okay, it now works and fully configurable in `configuration_adv.h`.

I ditched the snprintf_P's....just did them in the Menu calls.

**Comment by batata004** [comment]
wow @Tannoo  now it works amazingly easy!

`#define USER_GCODE_2 "M140 S" STRINGIFY(PREHEAT_1_TEMP_BED) "\nM104 S" STRINGIFY(PREHEAT_1_TEMP_HOTEND)`

That's easiest it can get! Thanks a lot, really easy to use and understand! Great contribution my friend!

**Comment by Tannoo** [comment]
Someone else may have to chime in to get the menu clicks to return to the status screen AFTER the gcode has been executed.

I'm still trying to figure that out though.

**Comment by batata004** [comment]
> Someone else may have to chime in to get the menu clicks to return to the status screen.

I would be one to chime on that but not in the bad sense, you already did a good job AND after some random timeout the menu comes back to the status page - no big problem here :) . But why dont you call the function "lcd_return_to_status();" right after the user clicks the option he wants/menu?

**Comment by Tannoo** [comment]
That will then return to the status screen without running the script.
I've tried that.

**Comment by batata004** [comment]
You should call that before running the script. When you helped me to add my own menu changing ultralcd.cpp file (now I dont need that anymore thanks to you) I got to make it work like this:


```
lcd_return_to_status();
enqueue_and_echo_commands_P(PSTR("M140 S105\nG28\nG29"));
```

If you call it before executing the script I think there will be no problem!

**Comment by Tannoo** [comment]
But, that was in it's own function not a MENU_ITEM.

**Comment by batata004** [comment]
Yeap, it was inside its own function. I thought the way you implemented this custom menu thing was like this: you assigned the same function to the click event of all menu entries. Then you would pass a parameter that was the GCODE to be executed. If it was implemented this way you could call the "go back to the status screen" at the top of the function.

Anyway, I think because I didnt do my homework about marlin I will not bother you with my opinions! I dont know anything about marlin code, I was just guessing and I think it's not productive! Anyway, I already downloaded the 3 files you changed and uploaded them to my printer and it works fine!

**Comment by Tannoo** [comment]
>I thought the way you implemented this custom menu thing was like this: you assigned the same function to the click event of all menu entries. Then you would pass a parameter that was the GCODE to be executed and LABEL. If it was implemented this way you could call the "go back to the status screen" at the top of the function.

I did -- BUT, I couldn't get it to run the scripts correctly. So, I ditched them.

**Comment by Roxy-3D** [comment]
@Tannoo   What is wrong?  It sounds like after you give it a user defined command, the LCD Panel doesn't see any more encoder wheel clicks????

That almost sounds like what UBL's G29 does when it activates the flag  has_control_of_lcd_panel.
When that flag is activated...  The LCD Code doesn't get to see any clicks...

**Comment by Tannoo** [comment]
Oh, no... Clicks are seen. But there is only one click allowed when at the user command menu.

Click on a script and it does it.
If I add a return to status if clicked....it returns to the status when clicked, but not run the script.

**Comment by Tannoo** [comment]
`MENU_ITEM(gcode, CUSTOM_USER_ITEM_1, PSTR(USER_GCODE_1 USER_SCRIPT_EXECUTED));`

I cannot seem to add anything to return to the status immediately after the script is executed.

**Comment by Roxy-3D** [comment]
Some of the commands (at the end of the command) tell the LCD code what screen should be active.   Is that what is causing it?

**Comment by Tannoo** [comment]
The `END_MENU`? Dunno.

**Comment by Roxy-3D** [comment]
No...  I don't think so...   END_MENU just provides a final count of how many menu items are in the list:
```cpp
  #define END_MENU() \
    } \
    _countedItems = _thisItemNr; \
    UNUSED(_skipStatic)
```

**Comment by Roxy-3D** [comment]
```cpp
MENU_ITEM(gcode, CUSTOM_USER_ITEM_1, PSTR(USER_GCODE_1 USER_SCRIPT_EXECUTED));
```
> I cannot seem to add anything to return to the status immediately after the script is executed.

 What about adding:
```cpp
 lcd_goto_screen(lcd_status_screen);
```

**Comment by Tannoo** [comment]
What I am looking to do is to return to the status screen as soon as a script has been executed from:

`MENU_ITEM(gcode, CUSTOM_USER_ITEM_1, PSTR(USER_GCODE_1 USER_SCRIPT_EXECUTED));`

How might I get that done?

**Comment by Roxy-3D** [comment]
The big problem is you have enqueued the command.  So you don't know when it is going to be executed.  And you don't really have control when it is running either....

Remember...  Marlin is not multi-threaded...     Or from another perspective...   You have enqueued the command...  But until the command processor gets some time to run, the command won't happen.

**Comment by Tannoo** [comment]
Yes.. Maybe an M command to return to the status screen? That way, it can be added to the script.

But, this also may not be a big deal.

**Comment by Roxy-3D** [comment]
So...   just to be clear....  You want to enque some random string of user specified commands...  And then leave that menu screen still active so you can select a different user specified command,  right?

This would be a total hack...   But you could have a global flag that gets set by your User Defined Menu code that says that menu is active.   And then in void lcd_status_screen()  check that flag and if it is active you do a lcd_goto_screen(your_menu_code_function);

That would always re-activate your menu screen while the user is deciding which user specified commands to do.   And then, when you leave your menu screen...  You deactivate that flag so you don't keep jumping into that screen when you shouldn't do that.

UPDATE:   A better way....

You could call lcd_save_previous_screen() in your custom user menu...  And then in the 
```cpp
 void menu_action_gcode(const char* pgcode) { enqueue_and_echo_commands_P(pgcode); }
```
change it to be:
```cpp
 void menu_action_gcode(const char* pgcode) { 
    enqueue_and_echo_commands_P(pgcode); 
    lcd_goto_previous_menu();
}
```

**Comment by batata004** [comment]
> So... just to be clear.... You want to enque some random string of user specified commands... And then leave that menu screen still active so you can select a different user specified command, right?

@Roxy-3D that's right! But I think the possibility to the user select a different specified command is not the only use case here. I will give a real day example: when I turn on my printer, sometimes I need to run a specific set of commands. Now that @Tannoo implemented this nice custom commands I can select the custom script to be executed and right after that I can go to  -> PRINT FROM CD -> select a file. So I dont need to keep waiting the custom script to be finalized so I can start print.

Being able to use the LCD while the custom script is being executed is usefull cause I dont need to wait all the gcodes to be executed (some of them heat up the bed and it takes a while) to only after that print a file!

I think this is the greates advantage of being able to come back to status screen after a custom script is selected.

**Comment by thinkyhead** [comment]
> I cannot seem to add anything to return to the status immediately after the script is executed.

To do that you'll use a `MENU_ITEM(function, ...)` instead of a `MENU_ITEM(gcode, ...)`.

Define your handlers:
```cpp
#ifdef USER_DESC_1
  void lcd_user_gcode_1() {
    lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR(USER_GCODE_1));
  }
#endif

#ifdef USER_DESC_2
  void lcd_user_gcode_2() {
    lcd_return_to_status();
    enqueue_and_echo_commands_P(PSTR(USER_GCODE_2));
  }
#endif
```
…then use in menu items…
```cpp
#ifdef USER_DESC_1
  MENU_ITEM(function, USER_DESC_1, lcd_user_gcode_1);
#endif
#ifdef USER_DESC_2
  MENU_ITEM(function, USER_DESC_2, lcd_user_gcode_2);
#endif
```
If commands need to include a pause, use `M0`. If moves need to complete, include `M400`.

**Comment by Tannoo** [comment]
>To do that you'll use a MENU_ITEM(function, ...) instead of a MENU_ITEM(gcode, ...).

Yes, I know... but I couldn't get the gcode to execute properly.

**Comment by Tannoo** [comment]
```
char user_lcd_gcode[30];
snprintf_P(user_lcd_gcode, sizeof(user_lcd_gcode), PSTR(USER_GCODE_3), PREHEAT_2_TEMP_BED);
enqueue_and_echo_command(user_lcd_gcode);
```
If I could get this work correctly, then I can got back to the atatus screen easily.

**Comment by Tannoo** [comment]
>If commands need to include a pause, use M0. If moves need to complete, includeM400.

Okay, I will try this again in a little while.

**Comment by Tannoo** [comment]
That worked PERFECT!! Thank you, thank you, thank you, @thinkyhead. Now, why couldn't I get that? It's a mix of the two options I was doing. I will remember that one!

**Comment by Tannoo** [comment]
Give it a try now, @batata004.

**Comment by Tannoo** [comment]
I am done unless someone wants something more from this. I believe this is good.

**Comment by Tannoo** [comment]
Lemme update all the example folders.

**Comment by Tannoo** [comment]
K...done.

**Comment by thinkyhead** [comment]
Patched and ready to merge at #6895

**Comment by batata004** [comment]
wowwww great man!!!! that was fast, in a few days you implemented a really nice and useful feature!!! Thanks a lot guys, congrats to all of you!!!

@thinkyhead could you confirm when it will be merged? And when it happens, will it be merged to oficial stable release or to the rcbugfix version?

**Comment by Tannoo** [comment]
It is now merged into the `bugfix_1.1.x` branch.

**Comment by hussainsail2002** [comment]
Is there a way to use this to create my own assisted leveling sequence ?. I would like the nozzle to stop at specific locations on the print bed.

**Pull request closed without merging**
