### PR TITLE
Proposed fix for #20382 (Unreliable circle detection)

### LINKED ISSUE #20382: [BUG] Unreliable G2/G3 circle detection
### Bug Description
The following G2 - Test on the `bugfix-2.0.x` branch failed (only one circle instead of two):
**G28** X Y
G21
G90
G0 X-3.35 Y-1.02
G2 I3.35 J1.02 F600.00
G0 X-3.35 **Y206.98**
G2 I3.35 J1.02 F600.00
G0 X0 Y0
If Y of the second G0 command will be decreased to Y205.98 or less OR the G28 command is missing it works.. ?!

### Configuration Files
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5647969/Configuration.zip)
Done some modifications for my CNC setup with TMC5160s, sensorless homing and TFT24.

### Steps to Reproduce
1. Run G-Code
2. Check if machine is drawing two circles

**Expected behavior:**
The machine should machine/draw a circle and then move in Y direction and then machine/draw a second circle.

**Actual behavior:**
The machine machines/draws a circle, moves in Y direction and _does not machine/draw the second circle_.

### PR DESCRIPTION
**Pull request by ghost**
### Description

This is a proposed fix for #20382, whereby NEAR_ZERO macro was leading to problems. New logic essentially deletes the NEAR_ZERO requirement because target and position vector should suffice for determination of circle presence (right?) . 

Need @matbhe to please test code to see if his problem resolves. 
 UPDATE: matbhe reports it is working for him. Will mark as ready for review, but others should test/review this before merge just to be sure I didn't make mistake. 
### Benefits

1.) Proposed fix for #20382
2.) only perform expensive atan2 operation if not circle

### Configurations

Default Config will suffice

### Related Issues

#20382

### CODE REVIEW

**Comment by ghost** [comment]
There are now two commits and each one is a different proposed change. The first one attempts to fix the relevant issue but keeps the default behavior the same whereby angular rotation of zero is still assumed to represent a full circle and set accordingly. The second one includes the same fix of removing near_zero requirement but goes further and handles the angular_travel == 0 case differently by keeping it zero. i.e. only way to perform a full circle is when target == current position and if atan2 somehow yields 0 then it is kept zero instead of reset to +-2pi.

**Comment by ghost** [comment]
addendum just adds a return statement to bail when target != position and angle == 0. This means that center point, initial position, and target position all lie on the same line but with center not between the other two points. Either bail or maybe add some logic to replace G2/G3 command with a single G1 command to go straight to target position.

**Comment by ghost** [comment]
@matbhe reports it is working for him with no problems. So looks like this is a viable alternative. Will mark as ready for review so devs and community can review the code and keep what they like.

**Comment by sjasonsmith** [comment]
@yysh12 it looked like you might be planning to make changes based on feedback from @marknn3? What is the status of this?

**Comment by yysh12** [comment]
Yeah. I need to get around to that eventually. Just hadn’t time recently. Also still making my way through Marlin codebase before I can do the line thing. I was thinking that as a short term bugfix to just push what I wrote so far since matbhe said it was working for him and then later we can add those other things including the G1 replacement thing. Alternatively if you would like it all in one patch then mark this has a draft again I can let you guys know once I incorporate all the other stuff as well.

**Comment by DerAndere1** [comment]
> Ideally a straight line to target point in those circumstances would be ideal. I do not yet know enough marlin to know best method to replace with G1 when that happens though.

I guess that is possible with the following function calls as can be found in file G0_G1.cpp:

https://github.com/MarlinFirmware/Marlin/blob/7afd274d0ce9c7149c3edf3bd23aadd28154ccfb/Marlin/src/gcode/motion/G0_G1.cpp#L68 

and

https://github.com/MarlinFirmware/Marlin/blob/7afd274d0ce9c7149c3edf3bd23aadd28154ccfb/Marlin/src/gcode/motion/G0_G1.cpp#L98-L102

**Pull request merged**
