### PR TITLE
Invert E direction of Geeetech A10

### PR DESCRIPTION
**Pull request by tobiasschuerg**
I had to invert the drive extruder of my Geeetech A10.

### CODE REVIEW

**Comment by boelle** [comment]
PR's should go to bugfix 2.0.x, i have changed the base for you

**Comment by boelle** [comment]
@tobiasschuerg 

the consensus of the maintainers is that we aren't currently actively working on 1.x anymore, but anyone is still free to do so and submit a fix for a bug or even feature

so do you want this to go in to 1.1.x or 2.0.x ?

**Comment by boelle** [comment]
you might want to have the config updated in both 2.0.x and 1.1.x

**Comment by tobiasschuerg** [comment]
I'm fine with v2, that's why I created the PR agianst this one ;-)

**Comment by thinkyhead** [comment]
> I had to invert the drive extruder of my Geeetech A10.

Flipping the plug around has the same effect.

**Pull request merged**
