### PR TITLE
Reorder F103RE environments

### PR DESCRIPTION
**Pull request by sl1pkn07**
### Requirements

F103RExx

### Benefits

match F103RC setup

### CODE REVIEW

**Comment by thinkyhead** [comment]
Is `board_upload.maximum_size` removed as obsolete or just not needed?

**Comment by sl1pkn07** [comment]
> Is `board_upload.maximum_size` removed as obsolete or just not needed?

seems not need. because this chip has already 512k (is not like the RC chips, has 256+256hidden)

**Comment by sl1pkn07** [comment]
why you up 

`debug_tool        = stlink`
`upload_protocol   = stlink`

to `[env:STM32F103RE_base]`? i just put in `[env:STM32F103RE_bigtree_USB]` `[env:STM32F103RE_bigtree]` bucause the use of this options is because the actual bootloader not works (upload to chip) with firmwares >256Kb

**Comment by thinkyhead** [comment]
The only environments that inherit from `STM32F103RE_base`  are `STM32F103RE_bigtree` and `STM32F103RE_bigtree_USB`, so I moved those options up to `STM32F103RE_base`.

**Comment by thinkyhead** [comment]
OK. I've added a followup patch to restore the `STM32F103RE` environment (as a simple copy of `STM32F103RE_base`).

**Comment by sl1pkn07** [comment]
ok for me

greetings

**Pull request merged**
