### PR TITLE
Full Feature support for Stock build Anycubic Chiron

### PR DESCRIPTION
**Pull request by SwiftNick**
### Description

This is a full TFT interface for the Chiron using the ExtUI API, configured for use with a factory build Anycubic Chiron, 
with the old style TFT panel. (not the one shipped with Chirons running Anycubic Firmware 1.3.5) 
It has been tested and tweaked over the last few months with the help of a group of other Chiron owners and includes some of the newer Marlin features. The Chiron panel is fixed and wont allow Marlin to display custom messages so this version uses warning beeps, and changes the behaviour of the TFT menus where possible.

Details in the attached PDF.

### Benefits
• Mesh bed Levelling using stock 5 x 5 grid
• Sensor Bed Probing using stock probe
• Enhanced single point adjustment (tap each point twice and the head moves to that point for live adjustment)
• Automatic mesh loading after homing enabled
• Stock Hotend PID tune profile
• Stock Heatbed PID tune profile
• Filament out detection with Marlin filament reload workflow enabled
• Power loss detection and recovery enabled (SD Printing from root folder only,, SOS beep notification on powerup to resume)
• Auto park head on Pause
• Validated temperature error detection (reduces spurious temperature warnings)
• Marlin Linear Advance enabled (preset K=0.8)
• Marlin Junction Deviation (preset to 0.013)
• Live Z axis baby stepping movement from panel during print
• PC style SD card folder navigation

### Configurations
Attached are the configuration files and a PDF explaining how new features work on the Chiron panel.

### Related Issues
Powerloss recovery does require the implementation of PR #16909 which is included here

The full repo for my changes is here https://github.com/SwiftNick/Full-Chiron-Support 

I have been working on this for several months (should have published a long time ago).
The current partial Chiron implementation wont build, and has sanity checks that block support for PowerLoss recovery. 
I have merged the recent changes where possible but some parts of the current Chiron implementation will be replaced by this PR. 
The features here are enabled with #define ANYCUBIC_LCD_CHIRON and  #define EXTENSIBLE_UI

[Marlin 2.0 for the Chiron Feature summary.pdf](https://github.com/MarlinFirmware/Marlin/files/5279478/Marlin.2.0.for.the.Chiron.Feature.summary.pdf)

Configuration files are in the Anycubic\Chiron folder in the Configurations repository

### CODE REVIEW

**Comment by thinkyhead** [comment]
The configurations should not be submitted to this repository. Instead, check out the "Configurations" repository and add your configuration to the `examples` folder.

**Comment by sjasonsmith** [comment]
Once this makes it in and the example config goes into the Configurations repo, that should satisfy #15742.

**Comment by SwiftNick** [comment]
I've submitted PR 225 for the config files to the Configurations\bugfix-2.0.x branch

**Comment by SwiftNick** [comment]
How do you want to handle the Z home power loss recovery?
I notice you have removed the changes for Z homing after power loss.

Without homing Z to Zmin the Chiron power loss recovery will fail. 

It is safe to home the Z axis on the Chiron as long as the front 10cm of the bed is not used for the print.
This is what Anycubic define in their manuals.

So what I did was to add code to the recovery workflow to:

- RaiseZ
- Home X & Y and move to safe Z home position if not 0,0
- Home Z as we are now clear of the print
- Raise Z to the recovery height + POWER_LOSS_ZRAISE

Then continue with standard Marlin recovery 

Until we find a fix for this should I disable power loss recovery in the code?

**Comment by SwiftNick** [comment]
I have refactored to use MarlinSerial instead of 'Serial3' form the Hardware serial library
this was conflicting with the LCD_SERIAL_PORT definition.

Also cleaned up the merged changes to anycubic_chiron_lcd.cpp
This now contains just the EXTUI calls that map to the Chiron implementation.

**Comment by thinkyhead** [comment]
> Without homing Z to Zmin the Chiron power loss recovery will fail.

Maybe we can fix that. Is there something outside of Marlin that causes this?

Any new behavior needs a new option to go along with it so it can be applied selectively. In this case, you want to do a form of safe homing at the front of the bed, which is fine. So, an option like "`POWER_LOSS_HOME_Z`" needs to be added and enabled for the Chiron.

> It is safe to home the Z axis on the Chiron as long as the front 10cm of the bed is not used

I think this is a bad choice by AnyCubic, and if possible we should avoid homing Z at all on power-loss recovery. It would be nice to be able to use the front 10cm of the bed without any special concerns. Wherever possible in Marlin we like to expand on the capabilities of the machine, and this is one thing we can make better instantly and easily.

**Comment by SwiftNick** [comment]
The main issue with the Z axis on the Chiron is the pitch of the lead screw is to course, so when the power is cut the X axis carriage drops. I have no idea why they didn't use a shallower pitch.

**Comment by thinkyhead** [comment]
> so when the power is cut the X axis carriage drops

Hmm! Well, again, it needs to be done as an optional behavior by adding a new option that specifies Z homing on power loss recovery.

**Comment by SwiftNick** [comment]
Will it be sufficient to wrap the z homing changes in an #if ENABLED(ANYCUBIC_LCD_CHIRON) or do you want me to be more specific?
From comments in the original PR for ZHome there were other machines that may want to use the feature, which is why I wrapped the code in  POWER_LOSS_ZHOME option

**Comment by thinkyhead** [comment]
It must be done as described, because we don't want references to specific devices or machines scattered around the general purpose code.

Note also that the `_SELP_N_P` macros are never to be used directly. Those macros simply provide helpers for `SERIAL_ECHOLNPGM`.

**Comment by SwiftNick** [comment]
Ok if there's anything else you want me to tidy up, let me know.

**Comment by thinkyhead** [comment]
It seems just about ready, once the new power-loss-recovery option is added. I'll just throw that in quickly, and then we can enable it in the Chiron example configs.

**Comment by SwiftNick** [comment]
Once it's ready I'll update build, retest and send a copy to my FB group of Chiron testers too.

I have reached out to Anycubic to try and get a copy of the firmware for the new Chiron panel as it seems to be slightly different. 
It would be good to make sure I can support that too, but I wont hold my breath!

**Comment by thinkyhead** [comment]
If the new panel can be installed without a firmware update (according to AnyCubic) then it might be simple plug and play.

**Comment by thinkyhead** [comment]
Some points before this can be merged:

- It would be better to define a flag and modify the trigorilla pins file to define `X_MAX_PIN` as 43 when that flag is set. The pins for power-loss detection should also be moved into the Trigorilla pins file, and there needs to be clarification about the meaning of these pins.

- Please explain why there is a `POWER_LOSS_PIN` defined as 79, but code comments say that the `OUTAGECON_PIN` (58) is the one that goes low on power-loss? Is the `OUTAGECON_PIN` an extra pin that is meant to be connected to an external device, or is it internally connected to 79?

**Comment by SwiftNick** [comment]
Hi Scott,
I've fixed some build issues and a string conversion I missed.
There were a couple of sections needed for power loss recover to restore the z position that I wrapped with POWER_LOSS_RECOVER_ZHOME

During test I've noticed a problem with the PLR file creation, which may be limited to the Trigorilla board.

If there are more than just a few files on the SD card, the controller runs out of power at cardreader.cpp line1159

    if (!recovery.file.open(&root, recovery.filename, read ? O_READ : O_CREAT | O_WRITE | O_TRUNC | O_SYNC))

It seems to take too much power to populate the &root sdFat object in the call to open, unless the SD card is very empty. So the PLR file never gets written to the card.

Is there a way to just force root folder access without reading the rest of the fat on the card?
If not I can add a comment to the guide to warn that the SD file must be clean for power loss recovery to work.

Nick

**Comment by thinkyhead** [comment]
> If not I can add a comment to the guide to warn that the SD file must be clean for power loss recovery to work.

It's possible that we could write a "null" PLR file to the card at the very start of the print, and since the file will already exist it will take much less time to write it when the outage occurs.

**Comment by SwiftNick** [comment]
I can easily reproduce the issue so let me know if you need something tested.

**Comment by SwiftNick** [comment]
> If the new panel can be installed without a firmware update (according to AnyCubic) then it might be simple plug and play.

Just heard back from Anycubic, unfortunately the new panel is different and won't work if you upgrade.

**Comment by gaby64** [comment]
When will Chiron with 1.3.5 LCD be supported?

**Comment by SwiftNick** [comment]
As soon as I can get a new style panel from Anycubic I will add support for it.
They sent me a panel from China, but it was the old type. I was told that the panels share the same part number so they have no idea which version would be shipped...

**Comment by gaby64** [comment]
I have a Chiron with firmware 1.3.5, anything I could do to help?

IMG_20201023_151030

**Comment by billydragon** [comment]
Can we make it work with BLTouch instead of orgiginal Mechanic Probe sensor? I try add BLTouch enabled but not success. Z do not move to need position for probing.

**Comment by billydragon** [comment]
I success config BLTOUCH to work. Thank for your job. I will try bed leveling function later. I love Anycubic Bed mesh editor. After try many new versions of SKR, MKS 32 bits boards. I come back to original Trigorilla for Anycubic Chiron and TFT. Others board work not stable. Too many bugs, hang, wash many time to do it work.

**Comment by goanta** [comment]
@SwiftNick 
Hello, has Anycubic sent a 1.3.5 lcd screen yet? :)
I have the 1.3.5 model as well if there is anything I can do to help.

**Comment by SwiftNick** [comment]
Not yet.
Anycubic kindly shipped me a panel, but it was the old style (they share the same part number).
There is no stock of the new one right now and without a panel to test and develop with I'm a bit stuck!

**Comment by gaby64** [comment]
> Not yet.
> Anycubic kindly shipped me a panel, but it was the old style (they share the same part number).
> There is no stock of the new one right now and without a panel to test and develop with I'm a bit stuck!

is there any way we could test for you?

I have a bus pirate v3 that I never used yet.

**Comment by SwiftNick** [comment]
Not easily,
I need to hook the panel up to a terminal and push buttons and talk to it to figure out the correct responses.
As soon as they can Anycubic will send one.

if you can log the serial coms between the panel and the printer I might be able to make a start.

**Comment by stef-ladefense** [comment]
> Some points before this can be merged:
> 
> * It would be better to define a flag and modify the trigorilla pins file to define `X_MAX_PIN` as 43 when that flag is set. The pins for power-loss detection should also be moved into the Trigorilla pins file, and there needs to be clarification about the meaning of these pins.
> * Please explain why there is a `POWER_LOSS_PIN` defined as 79, but code comments say that the `OUTAGECON_PIN` (58) is the one that goes low on power-loss? Is the `OUTAGECON_PIN` an extra pin that is meant to be connected to an external device, or is it internally connected to 79?

Hello,
can I join you?
I arrived at this post because I had binary size differences between an anycubic mega I3 with a Trigorilla 1.0 card and another AI3M with a Trigorilla 1.1, which is not normal since the only difference is the organization of the "servo" pins which are not in the same order:
D4 D5 D6 D11 D12 for the Trigorilla 1.0
D11 D4 D6 D5 D12 for the Trigorilla 1.1
so having a difference in the size of the binary was for me an inconsistency.
and I finished after analysis of the sources to find that the TRIGORILLA_14 had been added to the cards with access to more than 70 pins ... except when we look at what is the maximum pin accessible to these trigorilla, it is A15 ( D69).

so I don't understand why TRIGORILLA_14 is in the cards list of the pinsDebug.h and pinsDebug_plus_70.h files.

moreover, you quote a pin D58 "OUTAGECON_PIN", similar I do not know anywhere this pin accessible on 8 bits Trigorilla.

here is an excellent recap of the pinout of 8-bit trigorilla
https://cdn.thingiverse.com/assets/32/8c/6d/ab/5b/TriGoRiLLa_PINs.pdf

**Comment by sjasonsmith** [comment]
@stef-ladefense Anycubic loves to create daughter boards which cover all the pins and reassign everything. These boards get very confusing, and for this reason break frequently as everyone tries to update them to work for their own printers.

**Comment by stef-ladefense** [comment]
> @stef-ladefense Anycubic loves to create daughter boards which cover all the pins and reassign everything. These boards get very confusing, and for this reason break frequently as everyone tries to update them to work for their own printers.

these cards are only daughter cards as you say, and which recovers the existing pins of the base cards which they do not move or almost, in any case, no 8 bits trigorilla until now that it is the versions 1.0, 1.1 or even 0.0.2 without the gorilla head does not in any way give access to pins greater than D69

**Comment by sjasonsmith** [comment]
If you have details to help solve it, please post a PR or open a new issue with details. One difficulty with these is that they don’t print version numbers on the boards, and everyone has to guess from pictures and unofficial informations sources.

**Comment by SwiftNick** [comment]
I originally defined the pin defs in the trigorilla pins file, but moved them after reading a comment from Scott about changes to a standard board pin def when a manufacturer does something different with the board.
The Chiron has an outage control pin that is connected to the powerloss pin.
You must set this pin high, then when the power goes out, the normal power loss code takes effect.

The config file I created works fine with the standard factory build Chiron that uses various daughter boards plugged into a Trigorilla board.

I added Trigorilla14 to the pinsDebug_plus_70.h because PINS_DEBUG (M43) wasn't showing all the pins used by the Chiron config. 
Now it does.

**Comment by stef-ladefense** [comment]
> I originally defined the pin defs in the trigorilla pins file, but moved them after reading a comment from Scott about changes to a standard board pin def when a manufacturer does something different with the board.
> The Chiron has an outage control pin that is connected to the powerloss pin.
> You must set this pin high, then when the power goes out, the normal power loss code takes effect.
> 
> The config file I created works fine with the standard factory build Chiron that uses various daughter boards plugged into a Trigorilla board.

alright, so tell me where is that wire of loss of power connected to the trigorrilla that you have, that will advance the story.
you can take a picture too, there are very few pictures of the chiron wiring

**Comment by stef-ladefense** [comment]
> I added Trigorilla14 to the pinsDebug_plus_70.h because PINS_DEBUG (M43) wasn't showing all the pins used by the Chiron config.
> Now it does.

the ATmega2560 have more 70 pins, but not all of them are linked / used by RAMPS 1.4.
physically on the Trigorilla board, no pins greater than D69 are exposed.
other 2560 based cards which expose all the I / O but unfortunately not the 8 bit Trigorilla

**Comment by SwiftNick** [comment]
> alright, so tell me where is that wire of loss of power connected to the trigorrilla that you have, that will advance the story.
you can take a picture too, there are very few pictures of the chiron wiring

When my machine has some down time I will pull it apart to trace the wiring. I haven't been able to locate any full schematics for the Trigorilla.

> the ATmega2560 have more 70 pins, but not all of them are linked / used by RAMPS 1.4.
physically on the Trigorilla board, no pins greater than D69 are exposed.
other 2560 based cards which expose all the I / O but unfortunately not the 8 bit Trigorilla

This was mainly needed to debug the PLR as M43 didn't show the pin defs that are in use but not exposed for external connections.

**Comment by goanta** [comment]
Just so happened that I opened the Chiron recently. Here are some pics if they are needed.

IMG_20201116_141846
IMG_20201115_234533

**Comment by stef-ladefense** [comment]
the chiron has a circuit for detecting the power cut?
if it exists, it is not on D58 since this function is not exposed on the connectors.
it would be nice to know where "OUTAGECON_PIN" is wired

**Comment by SwiftNick** [comment]
> the chiron has a circuit for detecting the power cut?
if it exists, it is not on D58 since this function is not exposed on the connectors.
it would be nice to know where "OUTAGECON_PIN" is wired

Yes it does exist, and it is on 58.
I extracted the info from the original Anycubic 1.3.0 firmware release for the Chiron (see below)

OUTAGECON_PIN 58 and POWER_LOSS_PIN 79 are tied together on the Trigorilla board (would need to remove mine and do a full trace to confirm)
The code sets OUTAGECON_PIN 58 high on start up and it is monitored by POWER_LOSS_PIN 79
When the power goes out, the PLR workflow is triggered just fine.

Setting 58 low disables PLR.

See references for OutageTest in 
https://github.com/ANYCUBIC-3D/ANYCUBIC_CHIRON_V1.3.0/blob/master/Marlin_main.cpp

and line 87 in 
https://github.com/ANYCUBIC-3D/ANYCUBIC_CHIRON_V1.3.0/blob/master/pins_RAMPS.h

I guess they figured out a way to detect power loss without any external connection.

**Comment by stef-ladefense** [comment]
Regarding version 1.30 Chiron Anycubic, the changes are a big bag of noodles.
When we analyze how the recovery works in the event of an outage, that's ugly!
Already Anycubic using G5 as recovery code, code which is already used for something else in the list of Marlin gcodes (G5 - Bézier cubic spline).
They use D58 and D79 internally and declare an INT6 (which corresponds to D79) on the G5 routine.
When we look at the Arduino pin correspondence, it has no digital pin greater than 53. (https://www.arduino.cc/en/Hacking/PinMapping2560) and in fastio_1280.h, D58 corresponds to PF4, physical pin 94 of 2560, D79 corresponds to PE6, physical pin 6 of 2560.

I spent over an hour checking each physical pin on the Trigorilla for consistency and apart from D42 and D43 which are reversed on the screen print, the rest is correct.
So https://cdn.thingiverse.com/assets/32/8c/6d/ab/5b/TriGoRiLLa_PINs.pdf is correct except D42 <> D43.
I couldn't find a physical pin match on the Trigorilla and the D58 and D79!
What appears is that all of these substantive changes are specific to this Anycubic 1.30 version AND CANNOT BE APPLIED IN ANY WAY DIRECTLY TO THE CURRENT BUGFIX 2.0 VERSION BECAUSE NO SPECIFIC RESUME ROUTINES EXIST IN THE MARLIN 2.0 CODE. .
Now I look forward to which pins the AC power end sensor is plugged into so that we have another starting point to analyze the Anycubic source code.

**Comment by SwiftNick** [comment]
Haha yes I thought that too!
It took me quite a while to figure out what they were doing.

Just to be clear,
**There is no 1.3.0 code used in my Chiron implementation at all, it is Marlin 2.0 safe!**
I completely rewrote the interface using the ExtUI API. 
Power loss and filament out workflows use all the standard Marlin 2.0 code and you don't need to inject any special 'G5' commands to make it work. The only new feature that was added, was an option to safely home Z during recovery, which Scott helped put together.

The only thing that is still a little mystifying is the use of pin58 & 79 for power out detection. 
However they have done that, it works on the Chiron.

**Comment by stef-ladefense** [comment]
that's why I'm waiting for your feedback on the connection of this detector, which could therefore be managed by another printer under Trigorilla. a very good thing! and bravo for your work with ExtUI API.
in addition several Anycubic printers share the same screen including the Chiron and the Mega, I think it would be a plus if we think about how to have a core management of these common screens and have an overlay for the particularities.
What do you think ?

**Comment by SwiftNick** [comment]
Thanks!
It took a while to get right but at least now we can just pick a config file and build for the Chiron!
I'll pull my printer apart and figure out how the detection is working.

It would definitely make sense to rationalise the Anycubic panel code.
The basic panel protocol seems fairly standard, but there are subtle differences in the way each machine/panel combo works.
As I only have access to a Chiron, it would need to be a collaborative effort.

Also recently thrown into the mix is the new style panel driven by Anycubic's custom Marlin build labelled v1.3.5.
That works differently too, even when fitted to the same machine... 
My aim here is to get a panel from AC (once they have some spares) then either work out how to automatically detect the panel type, or put in a switch for old/new style panels.

**Comment by stef-ladefense** [comment]
we should set up a collaborative place where to exchange without pollution here.
a github, hold it or mine whatever.
side screen, it would be necessary to be able to put Anycubic in the process to have a screen of each type to test, the list of the commands of these screens, but especially the format of the data to be sent.
I have a list of these commands for the first version of the Mega I3.
knutwurst also did a lot on his side with the blue / yellow screens.
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Types-of-Anycubic-Touchscreens
let's stop working alone.

**Comment by SwiftNick** [comment]
I have the firmware and BMP resources for the new Chiron panel but nothing to put it in!

**Comment by stef-ladefense** [comment]
hey Nick,
I wanted to test YOUR screen management and I changed
// #define ANYCUBIC_LCD_I3MEGA
#define ANYCUBIC_LCD_CHIRON

but I have compilation errors:

Marlin\src\lcd\extui\lib\anycubic_chiron\chiron_tft.cpp: In member function 'void Anycubic::ChironTFT::PanelProcess(uint8_t)':
Marlin\src\lcd\extui\lib\anycubic_chiron\chiron_tft.cpp:815:79: error: 'mmToWholeSteps' was not declared in this scope
                 int16_t steps = mmToWholeSteps(constrain(Zshift,-0.05,0.05), Z);
Marlin\src\lcd\extui\lib\anycubic_chiron\chiron_tft.cpp:819:44: error: 'babystepAxis_steps' was not declared in this scope
                 babystepAxis_steps(steps, Z);

an idea ?

**Comment by SwiftNick** [comment]
You need to enable babysteps in the config file.
It may be better to start with the Chiron config files then make adjustments for your machine.

**Comment by stef-ladefense** [comment]
> Vous devez activer babysteps dans le fichier de configuration.
> Il peut être préférable de commencer avec les fichiers de configuration Chiron puis de faire des ajustements pour votre machine.

it compiles!
where can we exchange without polluting here?

**Comment by SwiftNick** [comment]
You will find me on here
[Chiron FB Group](https://www.facebook.com/groups/2168219426798485/)

**Comment by gaby64** [comment]
is a 1.3.5 panel on the way or should I connect up my buspirate?

the panel uses UART right?

**Comment by ckvsoft** [comment]
> I success config BLTOUCH to work. Thank for your job. I will try bed leveling function later. I love Anycubic Bed mesh editor. After try many new versions of SKR, MKS 32 bits boards. I come back to original Trigorilla for Anycubic Chiron and TFT. Others board work not stable. Too many bugs, hang, wash many time to do it work.

Hallo
Do you use the Trigorilla Board with BLTouch? If yes can you give me the correct configuration.
Thx Chris

**Comment by stef-ladefense** [comment]
> Haha yes I thought that too!
> It took me quite a while to figure out what they were doing.
> 
> Just to be clear,
> **There is no 1.3.0 code used in my Chiron implementation at all, it is Marlin 2.0 safe!**
> I completely rewrote the interface using the ExtUI API.
> Power loss and filament out workflows use all the standard Marlin 2.0 code and you don't need to inject any special 'G5' commands to make it work. The only new feature that was added, was an option to safely home Z during recovery, which Scott helped put together.
> 
> The only thing that is still a little mystifying is the use of pin58 & 79 for power out detection.
> However they have done that, it works on the Chiron.

that's why I'm waiting for your feedback on the connection of this detector, which could therefore be managed by another printer under Trigorilla. a very good thing! and bravo for your work with ExtUI API.
in addition several Anycubic printers share the same screen including the Chiron and the Mega, I think it would be a plus if we think about how to have a core management of these common screens and have an overlay for the particularities.
What do you think ?

**Comment by SwiftNick** [comment]
> Hallo
> Do you use the Trigorilla Board with BLTouch? If yes can you give me the correct configuration.
> Thx Chris

Do you know which ports you have connected the BLTouch to on the Trigorilla?

**Comment by stef-ladefense** [comment]
> > I success config BLTOUCH to work. Thank for your job. I will try bed leveling function later. I love Anycubic Bed mesh editor. After try many new versions of SKR, MKS 32 bits boards. I come back to original Trigorilla for Anycubic Chiron and TFT. Others board work not stable. Too many bugs, hang, wash many time to do it work.
> 
> Hallo
> Do you use the Trigorilla Board with BLTouch? If yes can you give me the correct configuration.
> Thx Chris

search trigorilla bltouch wiring with google

**Comment by ckvsoft** [comment]
> > Hallo
> > Do you use the Trigorilla Board with BLTouch? If yes can you give me the correct configuration.
> > Thx Chris
> 
> Do you know which ports you have connected the BLTouch to on the Trigorilla?

Hi
Yes, but i can't find no configuration.h wit BLTouch for Chiron
Lg Chris

**Comment by ckvsoft** [comment]
> > > I success config BLTOUCH to work. Thank for your job. I will try bed leveling function later. I love Anycubic Bed mesh editor. After try many new versions of SKR, MKS 32 bits boards. I come back to original Trigorilla for Anycubic Chiron and TFT. Others board work not stable. Too many bugs, hang, wash many time to do it work.
> > 
> > 
> > Hallo
> > Do you use the Trigorilla Board with BLTouch? If yes can you give me the correct configuration.
> > Thx Chris
> 
> search trigorilla bltouch wiring with google

Hallo
Hardware and wiring is not the Problem.
Thx Chris

**Comment by SwiftNick** [comment]
> > > > I success config BLTOUCH to work. Thank for your job. I will try bed leveling function later. I love Anycubic Bed mesh editor. After try many new versions of SKR, MKS 32 bits boards. I come back to original Trigorilla for Anycubic Chiron and TFT. Others board work not stable. Too many bugs, hang, wash many time to do it work.
> > > 
> > > 
> > > Hallo
> > > Do you use the Trigorilla Board with BLTouch? If yes can you give me the correct configuration.
> > > Thx Chris
> > 
> > 
> > search trigorilla bltouch wiring with google
> 
> Hallo
> Hardware and wiring is not the Problem.
> Thx Chris

Indeed, but the config needs to define the pins you are using otherwise it wont work.
Nick

**Comment by ckvsoft** [comment]
> > > > > I success config BLTOUCH to work. Thank for your job. I will try bed leveling function later. I love Anycubic Bed mesh editor. After try many new versions of SKR, MKS 32 bits boards. I come back to original Trigorilla for Anycubic Chiron and TFT. Others board work not stable. Too many bugs, hang, wash many time to do it work.
> > > > 
> > > > 
> > > > Hallo
> > > > Do you use the Trigorilla Board with BLTouch? If yes can you give me the correct configuration.
> > > > Thx Chris
> > > 
> > > 
> > > search trigorilla bltouch wiring with google
> > 
> > 
> > Hallo
> > Hardware and wiring is not the Problem.
> > Thx Chris
> 
> Indeed, but the config needs to define the pins you are using otherwise it wont work.
> Nick

Hi
Ah OK. 
trigorilaservopins
I use the Servo Pins 5V, GRD and D11. The other two (black and white) direct on the Original Probe connector near the Hotend
Original BLTouch Version 3.1

That's why I wanted a working Chiron config with BLTouch.
i have no idea where to define what. In pins_TRIGORILLA_14.h, SERVO2_PIN already has the correct one
  #define SERVO2_PIN 11
Only where do I say that in the config?

lg Chris

**Comment by ckvsoft** [comment]
Hi there
So I have now managed that the BLTouch is recognized.
However, the BLTouch does not extend with G28. A G29 is carried out without errors. Did I miss something? Do I have to deactivate the two Z switches?
M503 shows me the set Z offset and also the individual becoming of the points. When starting a print, the offset remains at -14.
Please help. Chris

**Comment by SwiftNick** [comment]
Chris,
The Chiron was designed with separate end stop and probing sensors so the probe will only be deployed for a G29.
If you remove the 2 Z axis sensors, you will need to find a way to synchronise the 2 z motors, otherwise the X beam will get out of level and the printer will be unable to correct it.
My advice would be to use the BL Touch for bed levelling only and leave the Z homing sensors and dual drive as it is.

You need to use the TFT panel to adjust the bed mesh, just check the ALL box and change the Z offset there.
Nick

**Comment by ckvsoft** [comment]
Nick
Thanks for the information. Sorry for my questions. It is the first time I use BLTouch.

I made the settings in the TFT and confirmed with OK. My setting here then resulted in -16.65 these are also displayed with M503. But when I start a print, the nozzle stays too high again. I guess it's the -14 again. I think it has nothing to do with the BLTouch.
LG Chris

**Comment by ckvsoft** [comment]
Hi there
What am I doing wrong?
I reset the EEPROM. Then I go over the TFT to the center point (press twice) then I select all. The display shows -14. I then go down to my value, -16.45, here I can gently pull through my 0.1mm gauge. If I click OK now, the value is saved and the nozzle starts up. Now if I get the axes home and do it again. The nozzle again has a large distance and the value is at -16.45.

When I print now the nozzle does not go down.
But if I carry out leveling (G29) it will be carried out without errors. The nozzle then goes too far down when printing so that it scratches the bed. Can anyone tell me what I'm doing wrong, please?
Thanks Chris

**Comment by gaby64** [comment]
any progress on getting the newer LCD?

**Comment by SwiftNick** [comment]
Sadly no, Anycubic still have no stock.

**Comment by illuminati05** [comment]
The only difference between the old and the new display is the sended code from the display to the board. If this is the problem i have found an solution. The code changes are already done. Hope this helps

See:

https://github.com/dkoch83/Marlin-1.1.9_Anycubic_Chiron/issues/10

**Comment by SwiftNick** [comment]
> The only difference between the old and the new display is the sended code from the display to the board. If this is the problem i have found an solution. The code changes are already done. Hope this helps
> 
> See:
> 
> [dkoch83/Marlin-1.1.9_Anycubic_Chiron#10](https://github.com/dkoch83/Marlin-1.1.9_Anycubic_Chiron/issues/10)

Thanks for that,
I managed to get hold of a panel and have already finished the code to auto detect and support both panel types.
I will be submitting a PR soon, once I've finished testing.
There were quite a few differences in the new panel comms...

**Pull request merged**
