### PR TITLE
Lerdge K typos

### PR DESCRIPTION
**Pull request by tpruvot**
BOGUS_TEMPERATURE_FAILSAFE_OVERRIDE no more exist

### CODE REVIEW

**Comment by tpruvot** [comment]
else, unrelated to this, but i seen some repeated -D__MARLIN_FIRMWARE__ in platformio.ini

**Comment by thinkyhead** [comment]
The `-D__MARLIN_FIRMWARE__` is needed on any build that doesn't include `common.build_flags`, so if it is mixed with that we'll get two.

**Comment by thinkyhead** [comment]
Is it the Malyan M200? I can't get that one to build, actually.

**Comment by tpruvot** [comment]
> Is it the Malyan M200? I can't get that one to build, actually.

yes, nevermind, i missed the fact they dont include the common build flags

**Pull request merged**
