### PR TITLE
[FIX] Fix preheating time

### PR DESCRIPTION
**Pull request by studiodyne**
Repair hotend preating :
Min temp related issue
Preheating not working , need to be fixed (works in 1.1,  'is_preheating' variable is the mintemp detection , but not in 2.0)
Manufacturer requirements are too dangerous, now possible to reduce preheating time to 15s ' minimum'

Thks

### CODE REVIEW

**Comment by thisiskeithb** [comment]
30 seconds is what the manufacturer recommends: https://github.com/MarlinFirmware/Marlin/pull/24803

https://docs.dyzedesign.com/hotends.html#_500-%C2%B0c-thermistor

**Comment by studiodyne** [comment]
Manufacturer don't talk about 2.0 on the website
Manufacturer didn't know that preheating is down since 1.1
Manufacturer never made a fix to make these thermistor compatible with marlin 2.0
Manufacturer is sleeping !
With this thermistor you will always have a  strong heater cartridge ' min 70w ' , and , if you have time , make the experience to power on a 70w heater cartridge during 30 seconds , you will see a sun if not inside the hotend or if something wrong !
Manufacturer and their thermistors , are not ' heater cartridge manufacturer' and , they want to protect the marlin  temperature reading, and not the risk of fire

I have made lot of test , absolutely no errors after 60°
Reach 100° easily with 15 seconds
And always possible to respect the manufacturer value, 30s is always possible

15 seconds if still too much , but is ' reasonnable' 

Trust me !

But , If the communauty want to lock the 30s minimal , I'm ok 👍 
But apply the fix please !

**Comment by thisiskeithb** [comment]
> With this thermistor you will always have a strong heater cartridge ' min 70w ' 

That’s not true. I’ve used this thermistor with a 40W heater cartridge in a V6 hotend with these settings.

**Comment by studiodyne** [comment]
Yes but only for low temp  , impossible to reach more than 270 degrees with 40watts !  and only in preheating , because if you begin extrusion , MINTEMP is triggered

Buy these, you will love ! 
https://fr.aliexpress.com/item/1005004552086198.html?spm=a2g0o.order_list.0.0.24f35e5biZwWAh&gatewayAdapt=glo2fra

**Comment by thisiskeithb** [comment]
> Yes but only for low temp , impossible to reach more than 270 degrees with 40watts

That’s also not true. Heating takes longer, but I can print over 300°C with 40W cartridges in copper heater blocks.

It sounds like you should spend more time tuning heating parameters. I’d also recommend you give `MPCTEMP` a try.

**Comment by studiodyne** [comment]
Planned ! :-) 
Too Long heating , no serious high temp , little feedrate for extrusion , low volume , no fans ..... Permanent risk of temp fails ....No ! 70w is the cure !
I have made a lot of works , by upgrading toolchange (see my PR and try it) , hope thinkyhead will be inspired and will apply my work.
I have made a smart pause (try it) ' maintenance pause ' , hope this will be merged too
Now i'm building my new printer , and MPC is my  next stp

One question : MPC works immediatly or it's an adventure of tweaking ?

**Comment by studiodyne** [comment]
Go , i try it now
  #define MPC_HEATER_POWER { 70.0f, 70.0f  }  ❤️

**Pull request merged**
