### PR TITLE
HAL for Linux

### PR DESCRIPTION
**Pull request by thinkyhead**
Rebased from an earlier PR by @p3p.

Permits Marlin to build and run on Linux under simulation for development purposes.

### CODE REVIEW

**Comment by alexxy** [comment]
May be next step can be migration for FreeRTOS or something similar for 32bit platforms?

**Comment by thinkyhead** [comment]
RTOS doesn't appear to add any value to this application with its AVR-centric code architecture. A complete bottom-up rewrite that uses an RTOS would be possible, and that would be the proper approach. But then it would be a completely new firmware.

**Comment by p3p** [comment]
I mentioned on discord but just noticed you making changes here, I put in a PR against this branch on your fork to fix quite a few issues

**Comment by alexxy** [comment]
> RTOS doesn't appear to add any value to this application with its AVR-centric code architecture. A complete bottom-up rewrite that uses an RTOS would be possible, and that would be the proper approach. But then it would be a completely new firmware.

Yes. It will be some kind of next gen Marlin. But it will allow to use more features from 32bit arm platforms... Seems like most of new hw development became arm based

**Comment by p3p** [comment]
There is little redesigning Marlin on top of an RTOS would help with, the main difficulty in moving features to the 32 bit platforms is 3rd party library support or insufficient abstraction between libraries and Marlin core, every time a library is used a shim should be, one day we will get there.

Marlin has no trouble running as a single thread on an (RT)OS as long as there are still hardware interrupts for things that need them, basically what this port does .. without the hardware interrupts so its only useful for debugging and development.

**Pull request merged**
