### PR TITLE
Clean up EEPROM

### PR DESCRIPTION
**Pull request by thinkyhead**
- Remove unused functions.
- Eschew Arduino style interfaces for custom EEPROM.
- Split up Flash / "wired" in the STM32F4/F7 HAL.
- Consolidate DUE flash-based EEPROM.

References: #17651, #17772

### CODE REVIEW

**Comment by p3p** [comment]
If you are removing `eeprom_init` from the shared `eeprom_read_byte` function you need to make sure that it is being called in the appropriate `PersistentStore::access_start()`, it was needed because there wasn't a "start transfer" function so it was just called every byte.

**Comment by thinkyhead** [comment]
> If you are removing `eeprom_init` from the shared `eeprom_read_byte` function…

Thank you for bringing that to my attention here and on the other issue. I had the vague impression that persistent-store implementations already had this covered, but now I see: I still need to migrate some dangling inits over to `PersistentStore::access_start`.

I've been trying to tread lightly and not modify existing behavior until I had time and space to develop the full picture. I think I'm just about caught up now.

**Comment by thinkyhead** [comment]
It looks like, across the board, the Flash-based EEPROM emulations want to call their `init` method on every read / write. Is this strictly necessary, or were they just implemented following an obsolete pattern?

**Comment by p3p** [comment]
Looks like they are just following the old pattern then adding a flag in the init function so it only actually happens once.

Could only have a quick look, not even sure how the STM32_F4_F7 is handling the flash write buffering without using `access_start()` and `access_finish()` to handle the transaction .. you cant just write bytes to the flash ..

**Comment by thinkyhead** [comment]
> Could only have a quick look, not even sure how the STM32_F4_F7 is handling the flash

Actually I tried to build default with STM32F4 and I couldn't get past it not grokking our serial class names. I think that HAL is fundamentally fakakta.

**Comment by thinkyhead** [comment]
Ok, this is better in-general. The `eeprom_init` function now exists for Marlin's version of the Arduino EEPROM interfaces. And, if Arduino framework EEPROM code is used instead of Marlin's, the "wired" `PersistentStore:access_start` will call it anyway, adding that minor bridge. This is an overall improvement, so will be merged now. But please follow up if one of the patched items here is off the mark.

**Pull request merged**
