### PR TITLE
[PR] Creality Ender 3v2 Extensible_UI support 

### PR DESCRIPTION
**Pull request by mriscoc**
### Description
This Pull request add Creality Ender 3v2 Extensible_UI support to the bugfix-2.0.x branch. 

I use dgus, the example file as first templates. This is a preliminary support and rewrite it for have all the defaults menu and items.

### Requirements
Requires enable the Extensible UI support in config files, sample configuration files are attached.

### Benefits
Enable the use of Extensible UI on the DWIN display of the Creality Ender 3v2. Only single language support is enabled in this release but it uses the language constants of language_en.h file for now.

### Configurations
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6128480/Configuration.zip)

### CODE REVIEW

**Comment by ellensp** [comment]
"// M.A.R.C. Correct Label Max" throughout code?  no thanks.

**Comment by otioss** [comment]
I've heard ExtUI is not suitable for Ender 3 V2's DWIN display. I think it is preferred to use MarlinUI for this printer.

**Comment by thinkyhead** [comment]
Indeed, the ExtUI API is intended as a wrapper for displays that Marlin can't directly control, and which use a light protocol to send values to and from the controller. The Ender 3 V2 display is not suited to an ExtUI wrapper because it is entirely controlled by Marlin through custom code originally provided by Creality3D.

The interface provided by Creality is fine, but very minimal. In order for this display to work fully with Marlin, we need to finish the `MarlinUI` implementation started at #19371. That project needs help to get screen updates working properly. It would be good to get that completed first.

There is also an alternative UI being created, linked from that PR. There's no reason for them to move over to an ExtUI wrapper either. It is simply not appropriate to the display.

**Comment by mriscoc** [comment]
Oh, I was wrong. I did think that Ext UI was equivalent to Marlin UI.

**Comment by mriscoc** [comment]
Please, I have a doubt:
At this code in temperature.cpp:
```cpp
    if (target > GHV(CHAMBER_MAX_TARGET, BED_MAX_TARGET, temp_range[heater_id].maxtemp - HOTEND_OVERSHOOT)) {
      SERIAL_ECHOLNPGM(STR_PID_TEMP_TOO_HIGH);
      TERN_(EXTENSIBLE_UI, ExtUI::onPidTuning(ExtUI::result_t::PID_TEMP_TOO_HIGH));
      return;
    }
```
How MarlinUI get the information about the temperature being too high?
I only see a message sent to the serial interface and to the Extensible_UI.

**Pull request closed without merging**
