### PR TITLE
Add MSG_MOVE_100MM to language_en

### PR DESCRIPTION
**Pull request by hho**
### Description

Create an `MSG_MOVE_100MM` entry in the language_en

### Requirements

None

### Benefits

2.0.9.1 didn't compile for me otherwise, because of the added menu item in #22192 which was missing from the language file

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Looks like https://github.com/MarlinFirmware/Marlin/pull/22165 wasn't merged into `2.0.x` (or it wasn't in the release notes at least).

**Comment by thisiskeithb** [comment]
Related issue: https://github.com/MarlinFirmware/Marlin/issues/22239

**Comment by thisiskeithb** [comment]
@thinkyhead This is still needed in `2.0.x`:

https://github.com/MarlinFirmware/Marlin/blob/5845efe6122c380926127384d9996cc825c5c230/Marlin/src/lcd/language/language_en.h#L281-L284

https://github.com/MarlinFirmware/Marlin/pull/22242 didn't add the actual fix/english translation.

**Comment by ellensp** [comment]
It looks like the updated language_en.h with "PROGMEM Language_Str MSG_MOVE_100MM = _UxGT("Move 100mm");" was missed in 2.0.9.1 release. While the rest of the code and the it, and ru where updated with it. 
It is in bugfix.

**Comment by ellensp** [comment]
@thinkyhead please look at this ASAP. Breaks release 2.0.9.1 for all  LCD users

**Pull request closed without merging**
