### PR TITLE
Added option 'H' to G29 P4.

### PR DESCRIPTION
**Pull request by thinkyhead**
Rebase, squash, tweak of #7124.

- Added `H` to set a nozzle height adjustment to surface of the bed.
- Updated G29 P4 comments to reflect changes.
- Add fixes for #7150

### CODE REVIEW

**Comment by thinkyhead** [comment]
```
* One concept that is important to remember and that
* will make using the Phase 4 command easy to use is this: ...
```

Probably the comments on `unified_bed_leveling::G29` can be reduced by half while gaining clarity. Will approach that in future.

**Comment by thinkyhead** [comment]
```
   * If you have too little clearance and not much plastic was extruded in an area, you want to
   * LOWER the Mesh Point at the location. If you did not get good adhesion, you want to
   * RAISE the Mesh Point at that location.
```
Is that so? Are mesh points stored with their signs reversed? Raising the value of a mesh point in ABL or MBL tells the leveling system that the bed is higher at that point, and so it causes the nozzle to be higher when it crosses that point, opening up more space between the nozzle and the bed. This is exactly the opposite of the comment on UBL's G29. So, just wondering, is UBL reversing the sign of the mesh points for editing…?

**Comment by dot-bob** [comment]
> Is that so? Are mesh points stored with their signs reversed? Raising the value of a mesh point in ABL or MBL tells the leveling system that the bed is higher at that point, and so it causes the nozzle to be higher when it crosses that point, opening up more space between the nozzle and the bed. This is exactly the opposite of the comment on UBL's G29. So, just wondering, is UBL reversing the sign of the mesh points for editing…?

It looks like that comment has been lingering in `ubl_G29.cpp` for a while.  It is just opposite of how you would expect it to behave.  I relocated the entire paragraph as it seemed out of place at the bottom of notes for `G29 P4`.  Perhaps @Roxy-3D will chime in.

**Comment by Roxy-3D** [comment]
That comment is **_WRONG!_**   We need to change that.   (This stuff can get very confusing at times and it is easy to make stupid mistakes!!!)

**Pull request merged**
