### PR TITLE
UBL for RCBugFix — cleanup, rebase, patch

### PR DESCRIPTION
**Pull request by thinkyhead**
Cleanup, rebase, patched #5992 for latest codebase and standards… mostly. It still needs some cleanup and additional work to be completely ready, but it does compile now without error.

[Concise diff](https://github.com/MarlinFirmware/Marlin/pull/6054/files?w=1)

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I've looked at the diff's.  They all look 'reasonable'.  

Can we merge now and clean up anything else as we find the items?   The problem is I can't keep up with all the changes that are happening to RCBugFix.

If so...   It will be much easier for me to concentrate on the issues and get them fixed.  I'm totally overwhelmed by all the conflicts that keep happening.

**Comment by Bob-the-Kuhn** [comment]
Let me know if I can be of any help.

**Comment by thinkyhead** [comment]
It would be best to test this branch thoroughly before merging it. It still needs some more cleanup and changes. First, to resolve the errors some configurations are throwing currently in Travis CI. Then just the rest of the formatting I might have missed.

You should test this branch on your hardware when you have time to see that it functions as it should.

Then, at some point we can discuss the implementation details.

**Comment by Roxy-3D** [comment]
> Let me know if I can be of any help.

THANKS!   Hey...  Can you tell me more about why the entire ultralcd.cpp file was in 'Conflict'?  Do you know what caused that?  What did you do to fix it?

**Comment by thinkyhead** [comment]
Was it in "conflict" or just showing many changes and hard to do merging with?
The problem was that its content got indented by 2 spaces.

**Comment by Bob-the-Kuhn** [comment]
@thinkyhead - right now Travis reports the options it enabled when a test has completed successfully but not when there is an error.  Could you add that to the error out put?

**Comment by thinkyhead** [comment]
> Travis reports the options it enabled when a test has completed successfully but not when there is an error

Actually, it does. The options appear above the error.

**Comment by thinkyhead** [comment]
For example:
```
$ restore_configs
The command "restore_configs" exited with 0.

$ opt_enable NUM_SERVOS Z_ENDSTOP_SERVO_NR Z_SERVO_ANGLES DEACTIVATE_SERVOS_AFTER_MOVE
The command "opt_enable NUM_SERVOS Z_ENDSTOP_SERVO_NR Z_SERVO_ANGLES DEACTIVATE_SERVOS_AFTER_MOVE" exited with 0.

$ build_marlin
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Xlib:  extension "RANDR" missing on display ":1.0".
Initializing packages...
Preparing boards...
Verifying...
sketch/servo.cpp: In member function 'void Servo::move(int)':
servo.cpp:313: error: 'SERVO_DELAY' was not declared in this scope
     delay(SERVO_DELAY);
           ^
exit status 1
'SERVO_DELAY' was not declared in this scope
```

**Comment by Roxy-3D** [comment]
> You should test this branch on your hardware when you have time to see that it functions as it should.

I am more than willing to do this...   But I don't know how to get all of these changes added to the current RCBugFix.   

In theory...  I just put my `Configuration.h` files in the directory and flash my printer's firmware.   But I don't know how to take this Pull Request and mix it with RCBugFix.

**Comment by Roxy-3D** [comment]
> SERVO_DELAY

SERVO_DELAY was always defined with a value...  Even if there was not a servo enabled...   That might be at the root of the problem.   It is no longer always defined.

**Comment by Bob-the-Kuhn** [comment]
Now I'm feeling particularly dense this morning.

I don't see the options for the failing check.  I see the options for the passing check.

And I don't remember what I did to resolve the Ultralcd.cpp conflict.

**Comment by thinkyhead** [comment]
> …I don't know how…

To test this, just download the branch from its page: https://github.com/thinkyhead/Marlin/tree/rc_ubl_renewal

**Comment by Roxy-3D** [comment]
> To test this, just download the branch from its page: 

Doing this now....   Hopefully will be printing in 10 minutes!    :)

**Comment by thinkyhead** [comment]
> I don't know how to take this Pull Request

Github Desktop lets you download my fork as a separate repository, so you can do that if you wish, keep it open in a separate window, and then you can use the "Sync" button to pull down any changes.

The better way is to keep just your single Marlin repository and add a new remote, which you do by typing into Github Desktop's console…
```
git remote add thinkyhead git@github.com:thinkyhead/Marlin.git
git fetch thinkyhead
```
This makes it easier to do things like copy commits from my branch into one of your branches, use `git diff this_branch that_branch | git apply` and other neat tricks.

**Comment by thinkyhead** [comment]
I believe we will be passing Travis shortly….

**Comment by Roxy-3D** [comment]
> Github Desktop lets you download my fork as a separate repository, so you can do that if you wish, keep it open in a separate window, and then you can use the "Sync" button to pull down any changes.

No! No! No!   I'm already overwhelmed....    I've already pulled down a .ZIP file from your page.   I know how to make that work!   It is compiling clean with the default Configuration.h files.    I'm putting my printer's Configuration.h files into the mix right now...

**Comment by Roxy-3D** [comment]
I had all the servo stuff grouped together...   But it is split across the file again???

**Comment by thinkyhead** [comment]
Yoyo. The servo probe items were moved up to the probes section from their old location intentionally. It's the only use of a servo for the majority of users. Particularly `Z_ENDSTOP_SERVO_NR` is not a servo option, but really a probe option.

**Comment by Roxy-3D** [comment]
> Yoyo. The servo probe items were moved up to the probes section from their old location intentionally. It's the only use of a servo for the majority of users.

OK...   That is fine and I tend to agree.   But it would seem ALL of the servo stuff should be together.  Otherwise it gets confusing and users don't realize they have certain options they can use.

**Comment by thinkyhead** [comment]
It's a toss-up, as they both have merits. ~~I suppose, keep the `Z_ENDSTOP_SERVO_NR` option above, but move the angles back down to the lower section.~~

Ah, actually those angles pertain only to the Z probe servo. So again. Those really are probe-only options, not related to the "other" servos. Note that our special extruders also have their own angle options. So really, the servos section shapes up to be for people with special needs anyway.

**Comment by Roxy-3D** [comment]
> It's a toss-up, as they both have merits. I suppose, keep the Z_ENDSTOP_SERVO_NR option above, but move the angles back down to the lower section.

I think it makes sense to have the servo stuff up by the probes because 95% of the time, if a servo is used...  Its with a probe.    I'm just arguing all of the servo stuff should be kept together and not broken apart...

**Comment by thinkyhead** [comment]
Maybe a new name for the "Z servo probe" so it's clearer that it's a probe and it _only just happens_ to use a servo. I kind of like "`DANCING_PROBE`".

**Comment by Roxy-3D** [comment]
> Maybe a new name for the "Z servo probe" so it's clearer that it's a probe and it only just happens to use a servo.

And that's a good example why it is so hard to clean up software.   Just the names that get picked impact the organization of the code.    I prefer longer names like:   Z_PROBE_ON_SERVO   and then maybe assign a servo number to it????    If the #define is not enabled...  well, there is no Z_PROBE_ON_SERVO.


Flashing right now....   Soon...  We will know how good or bad things are...

UBL appears to be alive and well...  It found (and restored) its mesh map.   But I got a heater failure...   I need to relax Configuration_adv.h settings...

ITS PRINTING!!!   And you can see the Z_Correction going back and forth as it crosses mesh lines!  (I have a horrible piece of glass I found at a Dollar store.  You can see bumps and dips in it when you look across it.   But as usual....  This print got perfect adhesion for its first layer!)

Merging this would be very helpful to me!   It will let me focus on bug fixes!

**Review by Roxy-3D — APPROVED** [review]
UBL appears to be alive and well.   It is printing cleanly with UBL applying Z-Corrections.

It is ready to merge!

**Comment by thinkyhead** [comment]
> It is ready to merge!

Wow. I should sleep-deprive more often. I made dozens of typos that I had to fix to get it to compile, so I'm surprised I didn't actually break any logic in the process. But I was trying hard to be careful.

So I haven't looked too hard at all the internals of your UBL project, but it seems to be pretty well-contained. I see there will be a conflict with Repetier Host due to the `N` parameter. We'll have to replace that with another letter.

But, let's merge this now so testers can have at it and you can get more feedback.

**Comment by Bob-the-Kuhn** [comment]
YEAH!!!

And it finally dawns on me the line The line **"opt_enable NUM_SERVOS .... " exited with 0** is just saying it's enabled the options which will then be used in the next **build_marlin** block.

**Comment by Roxy-3D** [comment]
> I see there will be a conflict with Repetier Host due to the N parameter. We'll have to replace that with another letter.

Any of these kind of changes will be easy to make...   I won't be fighting the bigger battle of staying current!    I'll start trying to get the interactive mesh editing working again...   (That is a 'Must Have' feature and half of the value of UBL!)

**Comment by Roxy-3D** [comment]
And Thank You for the assistance Bob!   It really did help a lot.

**Comment by Bob-the-Kuhn** [comment]
My pleasure.

**Comment by ghost** [comment]
So... MBL is broken. It probes, but compensation is not happening.

I can't see a configuration issue.

Is this ya'll's way of saying, "Get your sensor on!"?

**Comment by Bob-the-Kuhn** [comment]
@Roxy-3D  - I got G29 P1 to run.  Attached are the changes I had to do first.

[UBL.txt](https://github.com/MarlinFirmware/Marlin/files/852880/UBL.txt)

**Comment by Bob-the-Kuhn** [comment]
The command sequence is G28, G29 P1, G29 A & I'm in business - right?

Here's a picture of my leveling test setup after doing G29 A and then G0 Y50.  Something really strange happened.  Looks like I'll need to use the BLTouch you sent me!
crash


----

Update 

Something's definitely wrong.  G0 X100 just caused a head crash.  There was a -25mm Z movement plus some X movement when I issued that command.

I've got about an hour to troubleshoot it before I call it a night.

**Comment by Bob-the-Kuhn** [comment]
UBL_line_to_destination doesn't know what to do with negative Z values.  Even if I do a G92 Z0 it still acts as if Z is negative.

What it does is set the variable z0 to a large negative number.  It doesn't help that the fade_scaling_factor_for_Z comes back as 2.

blm.state.z_offset is always coming back a zero.

Why am I getting -Z positions?  Because i'm running dual Z endstops and homing in the + Z direction.  With bilinear that didn't seem to matter.

Both the bilinear and UBL grids has values in them ranging from -22.?? to -20.??.

I need to go back and do bilevel again to refresh my memory.

**Comment by ghost** [comment]
Ok, so... 
`AUTO_BED_LEVELING_UBL` enabled by itself.
Issued `Level Bed` from LCD.
Everything homed and LCD beeped twice.
Nothing is moving and status line on LCD is blank.

**Comment by ghost** [comment]
I then issued `G29 S1` from IDE's serial monitor.
Everything homed and LCD beeped 3 times.
Nothing is moving and status line on LCD is blank.
Serial monitor says `Mesh saved` `Done`.
Really? It didn't probe anything.

**Comment by ghost** [comment]
What am I missing?

**Comment by ghost** [comment]
Now, I have disabled `AUTO_BED_LEVELING_UBL` and enabled `AUTO_BED_LEVELING_BILINEAR`.
Issued `Level Bed` from LCD.
Everything homed.
It traveled to every probe point, but never raised Z. So, every probe point was met by the probe.
It stopped moving at the last probe point and nothing....no beeps, no returning to home. nothing.

**Comment by ghost** [comment]
I forgot to mention that my probe was on a different pin than the Z_MIN. And setup as such.
I have now moved my probe to the Z_MIN_PIN and defined as such.
I still have `AUTO_BED_LEVELING_BILINEAR` enabled.
Issued `Level Bed` from LCD.
All probed just fine this time.
```
Bilinear Leveling Grid:
     0     1     2
 0 -0.08 +0.07 -0.16
 1 -0.02 +0.21 -0.27
 2 +0.06 -0.09 -0.40
```

**Comment by ghost** [comment]
These:
`#define Z_CLEARANCE_DEPLOY_PROBE   1 // Z Clearance for Deploy/Stow`
`#define Z_CLEARANCE_BETWEEN_PROBES  1 // Z Clearance between probe points`
Aren't making any difference.
My probe only needs about 2mm probing point clearances. Well, it's moves ~4mm every time, reguardless of what those are set to.

**Comment by ghost** [comment]
Maybe it has something to do with this `Z_PROBE_OFFSET_FROM_EXTRUDER -4.1`.
Because my nozzle is currently about 9mm from the bed after ABL probing.
So, I am changing the `Z_PROBE_OFFSET_FROM_EXTRUDER` to 4.1.

**Comment by ghost** [comment]
`Z_CLEARANCE_DEPLOY_PROBE 2`
`Z_CLEARANCE_BETWEEN_PROBES 2`
`Z_PROBE_OFFSET_FROM_EXTRUDER 4.1`

The LCD reports Z2 after the probing.
But, it takes a `G0 Z-8.23` to get the nozzle to pass the paper test.
I guess I'll just have to try printing to see what happens because all the numbers are inconsistent and don't make sense. I am worried that it is going to be air printing.

**Comment by ghost** [comment]
Well, that's exactly what happened. Nozzle was printing about 8mm above the bed. hmmm.
That was trying with `Z_PROBE_OFFSET_FROM_EXTRUDER -4.1`

I will try next with `Z_PROBE_OFFSET_FROM_EXTRUDER 4.1`

**Comment by ghost** [comment]
Now, after running `Level Bed` from the LCD, Z position displayed on the LCD is 2.15, although, the nozzle is about 10mm above the bed.
Here goes the print test...

Well, LCD says it was printing at Z0.2, but nozzle is ~8.8 above the bed.
Is the `Z_PROBE_OFFSET_FROM_EXTRUDER` being ignored?

I'm going to set the `Z_PROBE_OFFSET_FROM_EXTRUDER` to `-7.6` and see what happens.
That is because when I lower the nozzle to the bed, the LCD is telling me that I lowered it -7.8.

**Comment by landodragon141** [comment]
I have occasionally had a weird issue like this with ABL. The only way I've been able to fix is to select "Restore Failsafe" from the menu then I re home and run the ABL. I noticed that when its messed up it displays weird characters as the Z height right after it finishes leveling and before it prints.

**Comment by ghost** [comment]
I have done that, I will do it again.

**Comment by ghost** [comment]
Well, you know....this time, it seems to be working. Thank you.

**Comment by ghost** [comment]
Well, at least it's getting to the bed. But, no compensation is happening with ABL even after issuing `M420 S1`.
Does `M420 S1` load a non-existant matrix? Do I have to `G29 S1` first?

I can't get UBL to work. It homes, and stops.

**Comment by ghost** [comment]
This has gotten more complicated than it used to be.

Used to level the bed with G29... M500 and print as many times as you want. No M420 needed.

Now.... G29 and good luck. G29 used to home if not homed. Now, it throws and error saying you need to home first.
LCD level bed homes then probes.... no complaints about not being homed.

**Comment by Bob-the-Kuhn** [comment]
M420 can only display the UBL grid.  UBL enable/disable is broken.  I'll be testing a fix for it later today.

**Comment by nesalkiN** [comment]
I'm having a hard time understanding the options.

>   #define UBL_MESH_INSET 1          // Mesh inset margin on print area
>   #define UBL_MESH_NUM_X_POINTS 10  // Don't use more than 15 points per axis, implementation limited.
>   #define UBL_MESH_NUM_Y_POINTS 10
>   #define UBL_PROBE_PT_1_X 39       // These set the probe locations for when UBL does a 3-Point leveling
>   #define UBL_PROBE_PT_1_Y 180      // of the mesh.
>   #define UBL_PROBE_PT_2_X 39
>   #define UBL_PROBE_PT_2_Y 20
>   #define UBL_PROBE_PT_3_X 180
>   #define UBL_PROBE_PT_3_Y 20

Getting notes about the printer trying to probe outside the bed (with G29 P1) but I don't fully understand how to make it not to try to do that? It compensates when sending G28 and G29 A before printing but it has only probed some of the bed area. (edit: I see https://github.com/MarlinFirmware/Marlin/issues/6068)

It is easy to understand this. ;)

>   #define LEFT_PROBE_BED_POSITION 15
>   #define RIGHT_PROBE_BED_POSITION 190
>   #define FRONT_PROBE_BED_POSITION 10
>   #define BACK_PROBE_BED_POSITION 150

Edit: Btw, getting "Low memory available, stability problems may occur." with UBL enabled. Bed leveling debug option causes lots of errors and won't compile.

**Comment by Bob-the-Kuhn** [comment]
Make these changes to your configuration.h file to fix the probe out of bounds error.
```
  #define UBL_MESH_MIN_X MIN_PROBE_X
  #define UBL_MESH_MAX_X MAX_PROBE_X
  #define UBL_MESH_MIN_Y MIN_PROBE_Y
  #define UBL_MESH_MAX_Y MAX_PROBE_Y
```

Yes, there's lots of cleanup to be done.  I suggest waiting a week before trying UBL.  I expect we'll have most of the problems fixed by tehn.

**Comment by nesalkiN** [comment]
Thanks!

Changed in Configuration_adv.h. Let's see now..

**Comment by nesalkiN** [comment]
Not getting the out of bed problem now but the probe (BLTouch) ends up outside the bed at X0. How do I tweak the position? I have min x at -10 and tried 0. The X offset is 4.
Old config: https://github.com/NiklasOlofsson/Marlin-Main/blob/RCBugFix---RGB_Strip/Marlin/Configuration.h

**Comment by Bob-the-Kuhn** [comment]
If, after hitting the Z_MIN endstop, you need to move the head to the right by 15mm to have the nozzle at X0 on the bed then **#define X_MIN_POS -15** should be in your configuration.h file.

**LEFT_PROBE_BED_POSITION** determines how far to the right of X=0 the **PROBE** will be when it's probing on the left side.  In your case LEFT_PROBE_BED_POSITION should be 0.  

After setting these two items, if your probe is to the left of X0 (M114 should report X-4) then **X_PROBE_OFFSET_FROM_EXTRUDER** is probably off.  If it's to the right and M114 reports something other than X-4 then your value for **UBL_MESH_INSET** is too large.

**Comment by nesalkiN** [comment]
I have measured the offset by marking the bed at nozzle, zeroing and then moving until probe touched the mark a couple of times. I now changed X_MIN_POS to -15 and left to 0. G28 X0 puts the nozzle off bed and X reported as -15. G1 X0 moves the nozzle to 0 (on bed). The out of bed probing was happening at the same place as before, off bed. Changed UBL_MESH_INSET between 0 to 5 and it still probes at the same location outside the bed. Does it use the UBL_MESH_INSET value if I have changed the UBL_MESH_MI* values? I am probably doing something wrong. Need to sleep on it. ;-)

**Comment by thinkyhead** [comment]
@Roxy-3D If you can put the code from your last working UBL up in a window next to the new code and compare them side-by-side, that would be a good way to just ensure that nothing critical was changed, causing undue side-effects.

The other note I wanted to make is that we don't have to use `LCD_CLICKED` any more in the gcode layer. Instead, you just set `wait_for_user = true` and then do `while (wait_for_user)`. The firmware handles clearing the flag when there is an LCD click, or if a `M108` is sent.

**Comment by thinkyhead** [comment]
@Tannoo — I messed with MBL last week, so I probably broke something. I'll do some testing with it, debug as-needed, and get a patch in asap.

**Comment by Bob-the-Kuhn** [comment]
@NiklasOlofsson - please open up a new issue just for your UBL problems.  

Please attach your latest configuration file in the new issue.

**Comment by Roxy-3D** [comment]
Oooops....   I didn't see any of these messages until just now...  I'll answer in the morning.  But the current RCBugFix works fine right up until you decide you want to edit a mesh point.   I know what's wrong.  I can fix that in the morning.    

> The other note I wanted to make is that we don't have to use LCD_CLICKED any more in the gcode layer. 

Yeah...  I'll answer in the morning.  But that LCD_CLICKED is responsible of all of the hackery that UBL has to do to the LCD Panel.   Changing how that works is going to clean up a whole bunch of things.

**Comment by ghost** [comment]
>@Tannoo — I messed with MBL last week, so I probably broke something. I'll do some testing with it, debug as-needed, and get a patch in asap.

FYI - Mesh seems to be created, but not being used with MBL or ABL.

**Comment by ghost** [comment]
I need to get another printer to use for printing.. lol

Using my only printer for the bleeding edge code puts the brakes on printing sometimes.

**Comment by ghost** [comment]
@Bob-the-Kuhn got a fix in (#6068) that worked for me. ABL is working. I will test MBL and UBL.

**Pull request merged**
