### PR TITLE
Handle MAX7219 twisted LED Matrix placement

### PR DESCRIPTION
**Pull request by Roxy-3D**
Currently this only handles the 0 degree and 180 degree rotation.
+/- 90 degrees can be handled next.

### CODE REVIEW

**Comment by thinkyhead** [comment]
How about calling it "`MAX7219_ROTATE_EACH`" and allow it to be set to -90, 0, 90, 180, 270 to indicate how much each individual 8x8 matrix is rotated? Then the main rotate option would apply to the whole kaboodle following after that first adjustment.

**Comment by Roxy-3D** [comment]
Ah....   Would that work?   For 0 degrees and 180 degrees the same line of code works.
But I haven't figured out how to do it for +/- 90 degrees.

> Then the main rotate option would apply to the whole kaboodle following after that first adjustment.

Yes...  That would be GOOD!  How about we start with this...  And when we find a display that has the matrix rotated +/- 90 relative to the In / Out pins (instead of 180 degrees) we can add that logic?

UPDATE:   I think I'm leaning towards we should start with this.   I only have displays that have the LED Matix rotated 0 or 180 degrees.   So...   This probably will handle the bulk of the cases until we find some other weird display.

**Comment by thinkyhead** [comment]
When individual matrixes are flipped, and you turn on the `MAX7219_FLIPPED_IN_OUT` option (with 0 overall rotation), is the final result upside-down?

**Comment by thinkyhead** [comment]
Are the individual matrixes rotated, or just in reverse order?

In other words, when individual matrixes are flipped, and you turn on the `MAX7219_FLIPPED_IN_OUT` option (with 0 overall rotation), is the final result upside-down?

Post photos if it helps to clarify.

**Comment by Roxy-3D** [comment]
The problem is we are using the location of the 5 wire connector to define the 'orientation' of the board.   That works for determining which 8 bit slice of the line we are trying to access.   But some of the units have the 8x8 matrix rotated 180 degrees with respect to the In / Out connectors.   So within an 8-bit slice of the row, we need to invert that direction.  (But it is my belief the rows did get inverted.)

That one line change fixes the problem from what we currently have to make the boards I have work correctly.

I can't post pictures.  My printer is busy until tomorrow morning.

I don't care what we call it...   I just want to be able to set in once in the Configuration_adv.h file and not have to mess with it all the them.

One more thought...  If we added a 2nd #define to handle the flipping of the rows with regard to the In / Out pins...  That would give us the full spectrum.   Either enable one or the other, or both....  And we should be able to handle every case.

**Comment by thinkyhead** [comment]
I think the change should also include the other case for `_LED_UNIT`:
```cpp
#if _ROT == 0 || _ROT == 270
  #define _LED_BIT(Q)   (7 - ((Q) & 0x7))
  #if ENABLED(MAX7219_FLIPPED_IN_OUT)
    #define _LED_UNIT(Q)  ((MAX7219_NUMBER_UNITS - 1 - ((Q) >> 3)) << 3)
  #else
    #define _LED_UNIT(Q)  ((Q) & ~0x7)
  #endif
#else
  #define _LED_BIT(Q)   ((Q) & 0x7)
  #if ENABLED(MAX7219_FLIPPED_IN_OUT)
    #define _LED_UNIT(Q)  ((Q) & ~0x7)
  #else
    #define _LED_UNIT(Q)  ((MAX7219_NUMBER_UNITS - 1 - ((Q) >> 3)) << 3)
  #endif
#endif
```
Or more concisely:
```cpp
#if _ROT == 0 || _ROT == 270
  #define _LED_BIT(Q)   (7 - ((Q) & 0x7))
#else
  #define _LED_BIT(Q)   ((Q) & 0x7)
#endif

#if (_ROT == 0 || _ROT == 270) == ENABLED(MAX7219_FLIPPED_IN_OUT)
  #define _LED_UNIT(Q)  ((MAX7219_NUMBER_UNITS - 1 - ((Q) >> 3)) << 3)
#else
  #define _LED_UNIT(Q)  ((Q) & ~0x7)
#endif
```

**Comment by Roxy-3D** [comment]
How about we make two separate controls?   One to control inverting the rows within a single matrix.   And one to control inverting the columns in a single matrix?

And then all the other logic to control which unit is being referenced based on the rotation still works.
That should handle all the cases.

**Comment by thinkyhead** [comment]
The rotation options applying to the entire set of matrixes together should be enough for a user to set their preferred orientation, once the `MAX7219_FLIPPED_IN_OUT` option is set such that columns 7-8, 15-16, 23-24 (etc.) are adjacent to one another. (The overall effect of `MAX7219_FLIPPED_IN_OUT` is not to "rotate 180" but to reverse the order of the units.)

**Comment by Roxy-3D** [comment]
OK!   I think you may be right.  (This stuff makes my head hurt.)    

That above fix will fix my problem.   

Merge when you are ready!   I'll test in the morning.

**Pull request merged**
