### PR TITLE
Auto Levelling Bed & Z offset from extruder

### PR DESCRIPTION
**Pull request by mattcalavera**
Hy, I notice that the optimal value for parameters "Z_PROBE_OFFSET_FROM_EXTRUDER" 
in Configuration.h (Bed Auto Leveling part)
vary for my prusa i3 hephestos from BQ from material to material, -1.6 for Nylon and ABS and -1.4 for PLA.
It was possible to change it via rotary encoder before or during print?
Or also via GCode in slicer?

It will be very useful, instead of re-upload firmware each time I change material.

Thanks
(I did'nt want to merge nothing... I was not able to open a feature request :) )

### CODE REVIEW

**Comment by Wackerbarth** [comment]
First, submitting a pull request like this is not appropriate. If you are not, at the present time, submitting actual code, open an issue instead.

Next, I have to wonder why you think that the difference in the height of the probe and the nozzle differs when you change material? Are you physically swapping out nozzles?

If, as I suspect, the physical dimensions are not actually changing, but you wish to have a different extruder height for each material, this is the wrong place to be making the adjustment. You should be handling that in your slicer.

**Comment by mattcalavera** [comment]
Thanks for the answer Richard....as you already know, I'm new here on github...

My request is because I print abs and nylon on glass and pla on blue tape over glass, so the offset bed-extruder really change. And for optimal adhesion I'll have to upload modified firmware each time I change material.. I cannot find a similar parameter in cura although....

**Comment by KiteLab** [comment]
If not changed in `Configuration.h`, M851 sets your Z_PROBE_OFFSET on the fly.

M851 Zabs_height

M851 Zother_height

**Comment by Wackerbarth** [comment]
@KiteLab -- Yes that's the way to have multiple values without re-flashing the firmware.

But I don't understand why the tape makes a difference. I would suspect that one of the reasons to do "bed leveling" is to adjust for the different thicknesses of the various bed configurations. Doesn't the probe contact the tape (when present) instead to the glass itself? I would hope that the tape isn't spongy enough to affect the sensing of the top of the surface by enough to affect the initial print layer.

**Comment by mattcalavera** [comment]
The sensor (capacitive) sense aluminium tape sticked under the glass....

I need different offsets because of the tape and because with abs and nylon less offset produce a very well sticked first layer. The same offset with tape and pla produce laterally squished material ruining the print in pla. With provided M instruction in gcode with Cura I think should avoid reflash the fw.

Many thanks and a last question... The offset set with M581 is permanent or work only for the single gcode file?

Inviato da iPhone

**Comment by KiteLab** [comment]
**M851** is forgotten with a reset. You can make the value permanent by storing it in the EEPROM with a M500 (if EEPROM is compiled in).

**Comment by mattcalavera** [comment]
@KiteLab : in configuration.h i have :

  // these are the offsets to the probe relative to the extruder tip (Hotend - Probe)
  #define X_PROBE_OFFSET_FROM_EXTRUDER -30
  #define Y_PROBE_OFFSET_FROM_EXTRUDER -40
  #define Z_PROBE_OFFSET_FROM_EXTRUDER -1.7   

So it is effective the use of M581 in slicer (startGcode section)? 
I can override that setting in Configuration.h for each print?

And here https://github.com/MarlinFirmware/Marlin/wiki/G-Code-in-Marlin I cannot find trace of this M581 command.... :(
Thanks...

**Comment by KiteLab** [comment]
If you don't have the EEPROM activated Marlin will use `Z_PROBE_OFFSET_FROM_EXTRUDER` until you write an other value with **M851**. The next reboot will set `Z_PROBE_OFFSET_FROM_EXTRUDER` from the config again.
If you have the EEPROM activated, a variable is initialized by `Z_PROBE_OFFSET_FROM_EXTRUDER`, then the value from the EEPROM will be stored in that variable. This will be used until you change it with **M851**. To store the new value in the EEPROM use M500.

So every time you put tape on your bed use 'M851 Znew_height', 'M500'.
Every time you remove the tape from your bed use 'M851 Zother_height', 'M500'.

The Mcode for this is configurable. If you really want to use M581 - do it, but it defaults to **M851**.
https://github.com/MarlinFirmware/Marlin/blob/Release/Marlin/Configuration.h#L507

So yes and yes.
**Edited**

**Comment by mattcalavera** [comment]
Thanks @KiteLab 

This morning I try..and m581 definitely don't work. The same value in slicer and after a print, hardcoded in firmware produce very different results, the second is right.

How can I see il my actual firmware does support This instruction? i have Marlin fw modified by bq

**Comment by mattcalavera** [comment]
Sorry..... ;)

I'll try M851 and letto you know....;)

**Comment by KiteLab** [comment]
> and m581 definitely don't work

Even the upper case 'M' is important.

**Comment by mattcalavera** [comment]
@KiteLab 
I add the code you show me for custom M851 command in my Configuration.h.
Then I write fw with Z_OFFSET_FROM_EXTRUDER for ABS (no tape), and then I'm now starting a print in PLA with tape using 
M851 -1.2 ; Offset for PLA & tape
M500;
{question : in Cura these instructions goes before or after the "G28" and "G29" commands?}
in startGCode of Cura....

I'll let you know.... by the way, How can I be sure that my actual Marlin version (which I don't know what it is, I use a BQ marlin version) support this custom Z_OFFSET?
in which file of fw it is written?

Thanks a lot! your help it is very precious for me

**Comment by mattcalavera** [comment]
@KiteLab 
Ok definitely don't work....

Setting written in firmware for Z_OFFSET_FROM_EXTRUDER is effective
while
setting inserted in startGCode with M851 xxx and M500 is NOT effective
I try both before and after G29 command
I also add the 

#define CUSTOM_M_CODES
#ifdef CUSTOM_M_CODES
  #define CUSTOM_M_CODE_SET_Z_PROBE_OFFSET 851
#endif 
 settings that my Configuration.h doesn't had, but still nothing.

?? any help ?? :)

Thanks

**Comment by KiteLab** [comment]
What Marlin version do you use?
Even in the ancient `Release` branch `CUSTOM_M_CODES` is defined in the config.
Or did you copy in a even older Configuration.h? That does not work!

**Comment by KiteLab** [comment]
Sorry i did not read carefully enough. I have absolutely now clue about BQ-Marling. We are here on MarlinFirmwere/Marlin and support exactly that. Please ask BQ.

**Pull request closed without merging**
