### PR TITLE
LCD menu_move: Treat rotational axes in angular degrees

### LINKED ISSUE #24333: [FR] LCD move menu should treat rotary axes in degrees, even in inch mode
### Is your feature request related to a problem? Please describe.

When using the LCD menus, rotational axes (`AXISn_ROTATES` enabled) should be treated using units of angular degrees, even in inch mode. Currently the move menu seems to treat values for all axes as given in length units (depending on inch mode). 

### Are you looking for hardware support?

ZONESTAR_LCD

### Describe the feature you want

- The move menu is probably the most used one and should be improved first. 
- For configuration menus we can document that the user first has to change to metric mode (G21) and enter all values in angular degrees (for rotational axes) or mm (for linear axes)
- improving display UI other than default UI for ZONESTAR_LCD is out of scope for this issue

### Additional context

_No response_

### LINKED ISSUE #26002: Rotary axis option will not compile[BUG] (bug summary)
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Tried to build rotary axis config in the latest (as of 6/20/23) bugfix 2.1.*, 
receive build errors. 
3 standard Cartesian axis X,Y,Z plus 1 rotary axis.(I) -- (A)

error states that J,K,U,V,W are not defined. 

I can build with additional axis if the extra axis is linear, but if enabled "axis_rotates" then the build still looks for all 9 possible axis to be named and defined. 

In motion.cpp the additional axis section for linear axis is written with conditional define statements, but the rotary section is written so that is any exist then they all need to be defines. 

### Bug Timeline

_No response_

### Expected behavior

I built with the 2.1.2.1 release and rotary worked, but for other reasons([probe_target build error](https://github.com/MarlinFirmware/Marlin/issues/25997)) I needed to use bugfix. 

### Actual behavior

compile time error prevents successful build.

### Steps to Reproduce

1. download from marlin source
2. download config examples
3. load the config/examples/linear_axes/RAMPS 5 LINEAR_AXES config files
4. Line 194 should have this
 #ifdef I_DRIVER_TYPE
  #define AXIS4_NAME 'U' // :['A', 'B', 'C', 'U', 'V', 'W']
#endif
#ifdef J_DRIVER_TYPE
  #define AXIS5_NAME 'V' // :['A', 'B', 'C', 'U', 'V', 'W']
#endif
#ifdef K_DRIVER_TYPE
  #define AXIS6_NAME 'C' // :['A', 'B', 'C', 'U', 'V', 'W']
#endif

Change it to this 

#ifdef I_DRIVER_TYPE
  #define AXIS4_NAME 'A' // :['A', 'B', 'C', 'U', 'V', 'W']
  #define AXIS4_ROTATES	// THIS BREAKS THE BUILD		   
#endif
#ifdef J_DRIVER_TYPE
  #define AXIS5_NAME 'B' // :['A', 'B', 'C', 'U', 'V', 'W']
  #define AXIS5_ROTATES	// THIS BREAKS THE BUILD
#endif
#ifdef K_DRIVER_TYPE
  #define AXIS6_NAME 'C' // :['A', 'B', 'C', 'U', 'V', 'W']
#endif

### Version of Marlin Firmware

Marlin-bugfix-2.1.x

### Printer model

_No response_

### Electronics

_No response_

### Add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

_No response_

### LINKED ISSUE #26220: [BUG] 8 Axis on Octopus, no longer compiles
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

8 axis example config no longer builds

### Bug Timeline

Since https://github.com/MarlinFirmware/Marlin/pull/25761

### Expected behavior

It should build

### Actual behavior

it errors with:
```
Marlin/src/HAL/STM32/../../inc/../core/types.h:982:68: error: expected unqualified-id before numeric constant
  982 |       bool LOGICAL_AXIS_LIST(E:1, A:1, B:1, C:1, _I:1, _J:1, _K:1, _U:1, _V:1, _W:1);
      |                                                                    ^~

```

### Steps to Reproduce

1. use Configs https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/linear_axes/Octopus%208%20LINEAR_AXES
2. build
3. see the error

### Version of Marlin Firmware

Bugfix-2.1.x

### Electronics

Octopus

### Additional information & file uploads
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12494655/Configuration.zip)

### LINKED ISSUE #26335: 5 axis with rotation fails to compile.
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

```CPP
Marlin/src/module/motion.cpp:1164:83: error: 'const xyze_pos_t {aka const struct XYZEval<float>}' has no member named 'k'
           distance_sqr = ROTATIONAL_AXIS_GANG(sq(diff.i), + sq(diff.j), + sq(diff.k), + sq(diff.u), + sq(diff.v), + sq(diff.w));
                                                                                   ^
```

### Expected behavior

It should build

### Actual behavior

It has a compile error.

### Steps to Reproduce

1. Download https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/linear_axes/RAMPS%205%20LINEAR_AXES
2. replace default Config files with these configs
3. add   #define AXIS4_ROTATES to Configuration.h 
4. build

### Version of Marlin Firmware

Bugfix-2.1.x

### Electronics

RAMPS

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12874674/Configuration.zip)

Error comes from types.h, it has this code 

```CPP
#if HAS_ROTATIONAL_AXES
  #define ROTATIONAL_AXIS_GANG(V...) GANG_N(ROTATIONAL_AXES, V)
#endif

```

But this define is not called as HAS_ROTATIONAL_AXES is not set yet

#If HAS_ROTATIONAL_AXES is also used in Configuration_adv.h 
But is also not working as it is not set yet.

HAS_ROTATIONAL_AXES is set in inc/Conditionals_post.h to late.

### related
https://github.com/MarlinFirmware/Marlin/issues/26220
https://reprap.org/forum/read.php?146,893571,893596#msg-893596

### PR DESCRIPTION
**Pull request by DerAndere1**
### Description

Without this PR, LCD move menu could not be used for rotational axes, especially in inch mode. 
With this PR,  the LCD move menu treats rotational axes in degrees

### Requirements

`ZONESTAR_LCD`, `I_DRIVER_TYPE ...`, `AXIS4_ROTATES`, `INCH_MODE_SUPPORT`

### Benefits

- No unexpected move distances when moving rotational axes

### Configurations

[Marlin_PR24334_config1.zip](https://github.com/MarlinFirmware/Marlin/files/9033029/Marlin_PR24334_config1.zip)

### Related Issues
- Fix https://github.com/MarlinFirmware/Marlin/issues/24333
- Fix https://github.com/MarlinFirmware/Marlin/issues/26220
- Fix https://github.com/MarlinFirmware/Marlin/issues/26335

### CODE REVIEW

**Comment by DerAndere1** [comment]
EDIT: The following problem is now also fixed:

With these changes, move distances are as expected. but in inch mode (G20), rotational axes are moved slower than expected from the LCD (no problem when sending G-Code or with linear axes). Any ideas what causes this?

**Comment by thinkyhead** [comment]
Note that the `manual_feedrate_mm_s` for a rotational axis should already _actually_ be in degree-per-time units, not mm-per-second. The name has not been changed, but that would be the idea for a rotational axis. i.e., For a rotational axis, Degrees applies wherever Millimeters is usually assumed. If you know the radius to the end of some rotational tool, you could figure out the mm distance and use that, like we do within SCARA kinematics, but that is not formalized. It could be an addendum to feedrate modes, once those are implemented.

**Comment by DerAndere1** [comment]
With your edits, this does not work as intended: when in inch mode, the positions of linear axes shown in the move axis menu are wrong after moving the linear axis via the LCD. Also, when moving rotational axes via the LCD in inch mode, rotational axes move 25.4 times slower than in metric mode.

**Comment by DerAndere1** [comment]
I fixed the regression in the displayed position. To deal with feedrate for rotational axes in inch mode, I guess an alternative would be to introduce a second variable `fr_deg_s` in all motion related code if INCH_MODE_SUPPORT and rotational axes are enabled. IIRC, the current motion system (planner and motion.cpp) uses a single feedrate variable which stores the value that is actually only suitable for linear axes, and later, when it figured out that only rotational axes are involved, corrects for the prematurely applied inch-to-mm conversion factor. See
https://github.com/MarlinFirmware/Marlin/blob/58d1b1be289a6e51a36f8a8b2d24baa59a99e9ff/Marlin/src/module/planner.cpp#L2315

**Comment by DerAndere1** [comment]
The problem is, that for G1/G2/G3 commands, the motion system does not know if the feedrate has to be interpreted in length units or in degrees until line https://github.com/MarlinFirmware/Marlin/blob/58d1b1be289a6e51a36f8a8b2d24baa59a99e9ff/Marlin/src/module/planner.cpp#L2168 . So the parser has to assume the feedrate was given in length units and convert to mm/s, then pass it to the planner as `fr_mm_s`. If we want that `fr_mm_s` in planner.cpp holds the value as expressed in °/s for moves that involve only rotational axes, we would have to give the parser the ability to decide whether a given move command involves any linear axes or not.

**Comment by thinkyhead** [comment]
We should be expressing feedrates in mm/s for all axes in the G-code. Then we do any required math to produce a limited feedrate for all the axes in the move - whatever makes the most sense for the combined move. That final feedrate needs to be determined at the kinematics level. That is how it applies for something like a SCARA. And in the case of a SCARA the feedrate of the rotary axes actually changes throughout the move, as required to maintain the linear feedrate.

When determining the total distance for a move that includes linear axes, plus one or more rotary axes, my suggestion would be to build an initial feedrate based on the linear motions and then apply their speed limits. Then look at how fast the rotary axes are being asked to move at that point, and further limit speed based on their maximum degrees-per-second limits.

If a rotary axis were involved in determining a final toolhead position, then we would need to build kinematics, but for setups with additional anonymous linear / rotary axes, we can only follow the moves and apply their configured limits in a direct per-axis manner.

**Comment by DerAndere1** [comment]
If i unterstand you correctly, This PR in its original form was doing exactly what you proposed for the case of missing kinematics. With the Addition that for moves that involved no linear axis, the feedrate was Not the axis Limit feedrate but the specified feedrate, Interpreted in deg/s. That is what NIST RS274NGC/LinuxCNC in its default state (CANON_XYZ feedreference mode, „trivial kinematics“) calls for. I am in favour of any changes that achieve the same with cleaner code. And yes, i would Love to have an Multi-axis kinematics that allow Tool length compensation and an Option to Interpret feedrate as Surface Speed of the Tool Center Point Along the toolpath.

**Comment by thinkyhead** [comment]
Yeah, I realized later that in the angular case the prior inches-to-mm conversion on input would definitely mess with things. So, that means the feedrate either needs to be un-done later, or skipped on input from the G-code when the move only involves one axis. If it can be skipped right on input, that would be best. It is handled by one particular `GcodeParser` function.

The trickier problem is that the `G1` (and `G0`) feedrate is persistent (or it should be), and so it seems sensible to start implementing the different feedrate modes (inverse time, etc.), along with tool modes. We don't have to get that fancy now, but they will likely help out in future.

For now, it makes the most sense for Marlin to provide a persistent rotary feedrate (stored in degrees/s) and parameters to set/use it. At the most simple, something like `G1 C F1234` – still using the `F` parameter, but the empty `C` parameter tells Marlin to save the feedrate (degrees/minute) for the next time `C` is used – well, whether `C` has a value or not, it would be stored.

It's kind of non-standard to the Marlin idiom, but it's not that major compared to how far some firmwares have pushed G-code standards.

**Comment by DerAndere1** [comment]
Neat idea.

**Comment by DerAndere1** [comment]
This should wait until tombrazier's arc optimizations are merged. Let me know whether I am on the right track with today's commits, or not. So far I made the basics work (two seperate feedrates, ZONESTAR_LCD with MarlinUI, AXIS4_ROTATES, INCH_MODE_SUPPORT)

What works: 
- all manual moves from LCD
- `G1 X1 F500` ; sets linear feedrate to 500 linear units / min
- `G1 U1 F1000` ; for any linear axis U: sets linear feedrate to 1000 linear units / min
- `G1 A1 F180` ; for rotational axis A: sets angular feedrate to 180 ° / min
- `G1 C1 F360` ; for rotational axis C: sets angular feedrate to 360 ° / min
- `G1 X10`; uses previous linear feedrate (here: 1000 linear units / min)
- `G1 A10`; uses previous angular feedrate (here: 360 ° / min)
- `G1 A F360`; for rotational axis A: sets angular feedrate. 
- `G1 C F360`; for rotational axis C: sets angular feedrate. 

Missing: 
- compatibility of rotational axes with z-probe, bed leveling, direct stepping, kinematic printers etc.!!!

**Comment by thinkyhead** [comment]
I merged in the latest bugfix code, moving the `fr_deg_s` argument into the `PlannerHints` structure with the other optional arguments for the planner methods. The followup commit patches a few bit and gets this to the point of compiling, anyway. I'd be curious to see how other CNC / robot software that uses G-code deals with the combination of linear and rotary axes, and see how closely we can follow some established model. And, if established models aren't all that great, to see how much we can improve on them.

**Comment by DerAndere1** [comment]
mach3 seems to be similar to LinuxCNC. Not sure if they track rotational feedrate seperately. Here I found somebody's notes: https://www.machsupport.com/forum/index.php?topic=15032.0 . Haas on the other hand seems go with a single feedrate and interpret feedrate always in length-units per minute, so the operator has to set the correct "axis diameter": https://forums.autodesk.com/t5/fusion-360-manufacture/4th-axis-rotary-problem-every-line-feedrate-and-terribly-slow/td-p/9529361 and https://www.haascnc.com/service/codes-settings.type=setting.machine=mill.value=S34.html .
We should avoid all changes that would complicate implementation of inverse time mode (G93).

**Comment by DerAndere1** [comment]
We are apparently drifting away from the standard (if there is one) with this PR. The LinuxCNC community says that LinuxCNC stores only one feedrate value which is shared for rotational, mixed and linear moves. Every sane user / CAM post processor would add `F` commands before - and after each move that involves only rotational axes.

**Comment by thinkyhead** [comment]
> Every sane user / CAM post processor would add F commands before - and after each move that involves only rotational axes.

In that case the feedrate would be expressed in degrees-per-minute, or potentially radians-per-minute if there is an option to set a "radians units" mode. And, if only rotational axes are involved, the feedrate would need to be not stored, or stored for the next rotate-only move. I'd expect CNC software to distinguish, in itself, whether a move is purely rotational and send any `F` commands as-needed.

Note that some feedrate modes have interesting behaviors and might involve the chaining of `G` commands on the same line ahead of the `G0`/`G1` command. I implemented something like it for a SCARA once, so I'll have to dig that out and bring it into the mix.

I would suggest creating a new Project here focused on full CNC and Laser Cutter implementations, and bring together a group to work on that concertedly. The group would focus on the fundamentals of CNC, such as Drill-and-Peck Cycles, handling Spindle Tool Diameter for inner, center, and outer cuts, Tool Modes, Tool-Changing, Feed Rate Modes, etc., with the aim of making a configuration and interface for Marlin that would work in every way like a professional CNC Router.

**Comment by DerAndere1** [comment]
> In that case the feedrate would be expressed in degrees-per-minute, or potentially radians-per-minute if there is an option to set a "radians units" mode. And, if only rotational axes are involved, the feedrate would need to be not stored, or stored for the next rotate-only move.

To clarify: I confirmed with the LinuxCNC discord that LinuxCNC behaves like this:
```
G94 G90 G21 (feedrate in length units per minute or degrees per minute, absolute positioning, metric length units)
G1 X10 F100 (move linear X axis to absolute pos 10 mm at rate of 100 mm per minute)
G1 A10 F90 (move rotational A axis to 10 deg at rate of 90 deg per minute)
G1 X20 (move linear X axis to absolute pos 20 mm at 90 mm per minute)
```

In addition, [LinuxCNC documentation](http://linuxcnc.org/docs/devel/html/config/ini-config.html) tells us:  In RS274NGC, A-, B- and C- words are always expressed in degrees.

**Comment by DerAndere1** [comment]
Now this works again as I intend on my basic 4 axis setup, with and without rotational axes. Feedrate changes result in update of both internally stored values (fr_deg_s and fr_mm_s). The planner later decides which type of move occurs (purely rotational or not) and picks the appropriate feedrate value.

> I would suggest creating a new Project here focused on full CNC and Laser Cutter implementations, and bring together a group to work on that concertedly

I might revive some of the CNC-related PRs by Domush. We could use those as a basis for discussions with him and others. It seems to be difficult to find people that deal with both, Marlin code AND advanced CNC mills.

**Comment by DerAndere1** [comment]
If we consider rotational axes and inch mode niche features, I can offer to revert to the original simpler solution (https://github.com/DerAndere1/Marlin/tree/rotational_axis_fix) . It is not as complete as this PR in its current state but it requires much less changes as you can see from this diff:
https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.1.x...DerAndere1:Marlin:rotational_axis_fix

**Comment by DerAndere1** [comment]
I think we can close this. https://github.com/MarlinFirmware/Marlin/pull/26174 was merged and is a much easier solution which also works well with my 5 axis inverse kinematics

**Pull request closed without merging**
