### PR TITLE
FLSUN Delta QQS-Pro pins

### PR DESCRIPTION
**Pull request by Foxies-CSTL**
### Requirements

DELTA FLSun QQS-Pro printer with a new Hispeedv1 motherboard with removable drivers.

### Description

FLSun delivers with the latest models of QQS-PRo, a clone of the Mks_Robin_min v2 board which allows drivers to be replaced. This is called HISPEEDv1. I created a new definition of pinouts to support different features.

_MB-FLSun_HiSpeed_
IMG_1968

### Benefits

**Feature Workflow**

Features|Active|Value
  --------|------|-----
  Multi-Config Switch QQS-PRO|True|QQS_Config.h
  Choice of independent E driver from XYZ|Standard-TMC|Ready
  Module Wifi|True|Ready
  ZoffSet ED3v6|-|Ready|
  Extruder TITAN/BMG| Titan|Ready
  BabyStepping|True|Ready
  UI Type|True|Color Marlin|
  TFT Color Selection|True|Classic,Color
  Unified Bed Leveling|True|+53pts
  Filament sensor|True|Ready
  Recovery PowerFailed|True|-
  TMC 220x Soft Serial|UART|Ready
  TMC 2209 Hard Serial|UART|Ready
  Neopixel|Note|Ready

**Note:** For NeoPixel I am using a modified version 2.4.

_MB-HiSpeed UART Serial mode_
IMG_1937
_Function NeoPixel_
Function NeoPixel
_Standard UI_
Standard UI

### Configurations

[pins_FLSUN_HISPEED.zip](https://github.com/MarlinFirmware/Marlin/files/5397415/pins_FLSUN_HISPEED.zip)
[Platformio.zip](https://github.com/MarlinFirmware/Marlin/files/5397416/Platformio.zip)

For compilation under VSC/PIO, I use the modified environment of Robin_nano35 with the script "ms_robin_mini.py" for the binary naming and the script "add_nanolib.py "to reduce its size.
`[env:flsun_hispeed]
platform        = ${common_stm32f1.platform}
extends         = common_stm32f1
board           = genericSTM32F103VE
platform_packages = tool-stm32duino
extra_scripts   = ${common.extra_scripts}
  buildroot/share/PlatformIO/scripts/mks_robin_mini.py
  buildroot/share/PlatformIO/scripts/add_nanolib.py
build_flags     = ${common_stm32f1.build_flags}
  -DMCU_STM32F103VE -DSS_TIMER=4
lib_deps = ${common.lib_deps}
  SoftwareSerialM
  #Adafruit NeoPixel=https://github.com/Foxies-CSTL/NeoPixel-Lib/archive/master.zip`

### Related Issues

This will allow many users of this printer to take the step to the Marlin environment. Different possibilities for users in different hardware and software configurations.

Best regards,

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for the submission! This PR needs some work before it can be merged….

- Please revert all changes to the configuration and version files in this PR.
- Please submit your example configurations to the [Configurations](https://github.com/MarlinFirmware/Configurations) repository, using the `import-2.0.x` branch.

**Comment by Foxies-CSTL** [comment]
>     * Please revert all changes to the configuration and version files in this PR

Ok, I just merged a standard version of the files (Configuration.h and Configuration_adv.h) for the QQS-Pro and I made a Pull Request of these same files to the Configuration repository. That's it?

**Comment by thinkyhead** [comment]
This PR has been rebased and squashed. To get the updated branch into your working copy use the Git console:
```
git fetch origin
git checkout bugfix-2.0.x
git reset --hard origin/bugfix-2.0.x
```

**Comment by Foxies-CSTL** [comment]
Hi, 
Following user feedback, I added a comment section for the UART mode of the TMC220x in serial mode and in hardware mode for the TMC2209.

**Pull request merged**
