### PR TITLE
Use of double precision floating point

### LINKED ISSUE #1321: Use of double precision floating point
I spotted several `double` declarations in the source code.

  - planner.c
  - qr_solver.c
  - Bed Leveling
  - probably more

I propose to eliminate those as far as possible or replace them by single precision `float`'s.

### PR DESCRIPTION
**Pull request by PxT**
Fixes #1321.

Someone who knows avr-gcc well should probably double check that this doesn't break something inadvertently.

### CODE REVIEW

**Comment by nophead** [comment]
Somebody recently stated floats are the same as double on AVR. If so this change is pointless and it makes it harder to port to ARM where double is presumably bigger than float and probably what you would want on a 32 bit platform with plenty of memory. C does all floating point calculations in double anyway.

**Comment by daid** [comment]
@nophead I stated that.

Just to confirm that data:
https://gcc.gnu.org/wiki/avr-gcc#Deviations_from_the_Standard

**Comment by galexander1** [comment]
I don't have a horse in this race, but it seems to me as though randomly
using double in some places and float in others is ... unaesthetic.
Should we, instead, convert all "float" to "double", then?  Or use a
floating_t typedef?

**Comment by daid** [comment]
My knownledge on the x86 platform is, when unsure, use doubles. The only reason to use floats on a PC platform is to safe memory or memory bandwidth. General calculation wise they are just as fast.

However, I do not know how that holds on the commonly used embedded platforms. Some platforms might have accelerators for floats but not for doubles.

But, precision wise, I think floats are more then enough for the scale at which Marlin works.

**Comment by nophead** [comment]
I have never come across a hardware accelerated platform that did floats and not doubles. Since C always calculates in doubles and only uses float for storage it would be pointless hardware unless double equals float as the case for AVR. Even on 16 bit platforms that I have used double has always been bigger than float and all accelerated hardware now uses IEEE standard format I believe.

**Comment by boelle** [comment]
build failed.... please submit a new PR

**Comment by uwehermann** [comment]
@daid

> However, I do not know how that holds on the commonly used embedded platforms. Some platforms might have accelerators for floats but not for doubles.

@nophead

> I have never come across a hardware accelerated platform that did floats and not doubles.

Quick random comment/update on this topic: it's actually a pretty common scenario on some microcontrollers/CPUs to have hardware-accelerated floats but not doubles.

E.g. some devices in the pretty popular STM32F4 series (or pretty much any other ARM Cortex-M4F based microcontrollers) have a floating point unit (FPU) in hardware that can do fast 32-bit float operations (e.g. a simple float multiplication will take just one CPU cycle), but will use slow software-implemented 64-bit double operations. Running double operations will be _significantly_ slower on these microcontrollers.

So if Marlin is ever to be ported to something other than an 8bit microcontroller I suggest to be careful about where double is used instead of float (and for which reasons) since it _will_ have a dramatic effect on precision of course, but unfortunately also on performance on various (common) architectures.

http://www.st.com/web/catalog/mmc/FM141/SC1169/SS1577/LN1806/PF255421
http://infocenter.arm.com/help/topic/com.arm.doc.ddi0439b/BEHJADED.html
https://community.arm.com/docs/DOC-7544

Hope that helps.

**Comment by nophead** [comment]
But I believe the C standard requires all floats to be extended to double in expressions, the same as integral types are all promoted to int, so unless the compiler defines double to be the same size as float I think all code will be slow.

**Comment by daid** [comment]
@uwehermann When you go beyond 8bit, the amount of CPU power available completely blows the 8bit AVR out of the window. So I don't expect any true performance issues in any of the current Marlin code.

**Comment by uwehermann** [comment]
> But I believe the C standard requires all floats to be extended to double in expressions,

Depends on how you write the code, I think. If you say "5.78" it will be a double per default, if you say "5.78f" it'll be a float. Also depends on which functions you invoke, e.g. pow() will do doubles, and powf() will do floats, etc. etc.

**Comment by uwehermann** [comment]
@daid Yup, sure. Just saying, there is a massive difference in float/double performance on those controllers so I suggest being careful to only use doubles where you actually need the precision they provide. With the current firmware it won't be a practical issue of course, until massively more CPU-bound algorithms are to be implemented etc.

**Comment by nophead** [comment]
You can make float literals, store floats and pass them as parameters, same as you can with char but as soon as you write an expression they get promoted to doubles and the maths is done double length, just as it is with char being promoted to int.

**Pull request closed without merging**
