### PR TITLE
Missing FSTR_P in bed corners menu

### PR DESCRIPTION
**Pull request by tpruvot**
Breaks the build without that on STM32 with COLOR_UI and bed tramming enabled

### CODE REVIEW

**Comment by tpruvot** [comment]
image

**Comment by thisiskeithb** [comment]
> or just F(tmp) had to fix a few ones too on my fork https://github.com/tpruvot/Marlin/commit/9c3ebf704cff44a03667a3bebcb0a6520207ec1b

Can you add these fixes as well?

**Comment by tpruvot** [comment]
oh, no, the other ones are not menus present in Marlin, its just to display the configured clock if you want to OC (specific addition in my fork for our "limited" board...)

**Comment by thinkyhead** [comment]
We can't use SRAM-based C-strings for menu titles on AVR, but menu titles automatically get string substitution, so we can just use `SUBMENU_S` to handle the custom move titles.

**Comment by thinkyhead** [comment]
Gotta crash! I'll fix up the rest of the string substitution stuff later today.

**Comment by tpruvot** [comment]
yes, i was about to try to replace some uint8_t* to char * but seems a bit complicated and i dont have an avr board ready to test...

**Comment by thinkyhead** [comment]
Still working on it… Decided to start over and follow a more methodical approach. Should be done later today.

**Pull request closed without merging**
