### PR TITLE
Prepare for IDE1.6

### PR DESCRIPTION
**Pull request by Wackerbarth**
OK, if you won't switch the Travis builds to the Arduino IDE 1.6, at least accept the preparation work so that the rest of us can use it.

This has Ramps/2560 and AT90USB1286 boards defined. Additional board entries are welcome

### CODE REVIEW

**Comment by AnHardt** [comment]
@Wackerbarth 
OK for me if you'd use u8glib v1.17 instead of the old v1.11.

**Comment by Wackerbarth** [comment]
@AnHardt -- The Travis build already does that.
Frankly,that's orthogonal to changing the base IDE.
I'm happy to have us use the "latest and greatest" of every subcomponent unless there is a compelling reason, on a case by case basis, to do otherwise.

**Comment by AnHardt** [comment]
@Wackerbarth 
How about moving u8glib v1.1.7 from ...\Marlin\ArduinoAddons\Arduino_1.0.x\libraries\U8glib
to ...\Marlin\ArduinoAddons\Arduino_1.x.x\libraries\U8glib
and omitting it here completely?

There is an echo in my head: "This code will be in the repository for ever! REBASE, Rebase, rebase, ...ebase, ..."

**Comment by Wackerbarth** [comment]
Rebase -- Yes!  You will notice that I have been tracking "Development" with "dev" so that we can have a cleaner RC branch.  We can also go back farther in time. And we SHOULD clean up thing that change something, then change the same thing again (particularly where something is added and then deleted).

As for the Arduino support and libraries such as U8glib, should they even be in the Marlin repository? I suggest a separate repo would be appropriate.

**Comment by AnHardt** [comment]
@Wackerbarth 
We already discussed the libraries this year. The consensus was to have them on board to avoid conflicts with untested newer versions.

**Comment by Wackerbarth** [comment]
@AnHardt == Not suggesting that they NOT be in a repository associated with Marlin. Just suggesting that it might be a different repository.

**Comment by boelle** [comment]
cant see what this can hurt, and we cant stay in the past forever

**Comment by fmalpartida** [comment]
+1 on this one

**Comment by boelle** [comment]
and we miss you and scott in hangout

2015-06-27 23:09 GMT+02:00 fmalpartida notifications@github.com:

**Pull request merged**
