### PR TITLE
Clarify Delta & SCARA config location

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Configurations have moved, so clarify documentation.

### Benefits

Clearer inline documentation.

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/20402

### CODE REVIEW

**Comment by sjasonsmith** [comment]
These links end up pointing them to the `import-2.0.x` branch, which may or may not be what they want.
Do you have any thoughts how to address that?

**Comment by thisiskeithb** [comment]
> These links end up pointing them to the `import-2.0.x` branch, which may or may not be what they want.
> Do you have any thoughts how to address that?

We could link to the All Branches page instead since configs aren’t released using tags: https://github.com/MarlinFirmware/Configurations/branches/all

**Comment by sjasonsmith** [comment]
That could better than pointing them to import-2.0.x.

**Comment by thisiskeithb** [comment]
> That could better than pointing them to import-2.0.x.

I just pushed a change to point to /all branches.

I'm curious, why are configs released in branches and not tags?

**Pull request merged**
