### PR TITLE
May 2019 update with Marlin

### PR DESCRIPTION
**Pull request by ghost**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### CODE REVIEW

**Comment by ghost** [comment]
Woo

**Comment by boelle** [comment]
no description??? 
image

**Comment by InsanityAutomation** [comment]
@boelle Im assuming he reversed the target and source branch as this is primarily a machine specific config from a slightly dated branch, and he probably wanted to rebase it.

**Comment by boelle** [comment]
yeah, but it looks awfull similar to where one posted a PR with a lot of commits in it and no description, not the same username etc, but still

and then the woo comment? does not make sense if its a private thing and he just wanted to rebase it

@aucoeurngo may we ask what the purpose of this PR is and why you did not make a description?

**Comment by ghost** [comment]
Sorry I just made some big stupid mistakes not realizing I could even
submit to the Marlin official branch.  I was just trying to get my stuff in
order after a long time away...

Please nullify anything I may have inadvertently done.

**Comment by teemuatlut** [comment]
You can just close it yourself and everything will be like it never happened.
No code will make it to upstream without the pull request being accepted (merged) by the owner.

**Pull request closed without merging**
