### PR TITLE
Support FYSETC SPIDER KING407 board

### PR DESCRIPTION
**Pull request by GerogeFu**
Support FYSETC SPIDER KING407 board

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Please enable PINS_DEBUGGING and see if the M43 command gives reasonable results.

I'm concerned that the "analog to digital pin" and "digital to analog pin" routines will be off.  If the first AIN is pin 107 and the last pin is 113 then there can only be 7 AINs.


```
#define NUM_DIGITAL_PINS        114
#define NUM_ANALOG_INPUTS       24
#define NUM_ANALOG_FIRST        107
```

**Comment by Bob-the-Kuhn** [comment]
pins_FYSETC_SPIDER_KING407.h ?

**Comment by GerogeFu** [comment]
> Please enable PINS_DEBUGGING and see if the M43 command gives reasonable results.
> 
> I'm concerned that the "analog to digital pin" and "digital to analog pin" routines will be off. If the first AIN is pin 107 and the last pin is 113 then there can only be 7 AINs.
> 
> ```
> #define NUM_DIGITAL_PINS        114
> #define NUM_ANALOG_INPUTS       24
> #define NUM_ANALOG_FIRST        107
> ```

My mistake, it should be 7

**Comment by GerogeFu** [comment]
> pins_FYSETC_SPIDER_KING407.h ?

Yes, Spider King consist of base board(IO) and core board(MCU). We plan to release several core board, like King407(base on STM32F407), King7xx(base on STM32F7xx)

**Pull request merged**
