### PR TITLE
G29 auto script

### PR DESCRIPTION
**Pull request by tonnico**
short:
this script scans the first few lines from a gcode. If the line between 2 different z are greater than min_g1 this is our first layer. 
On this layer we search the min and max values of X and Y. 
With an offset we write that in a new file.

### CODE REVIEW

**Comment by alexborro** [comment]
What if doing that into the firmware??

**Comment by tonnico** [comment]
This could only work with sd-card.

**Comment by thinkyhead** [comment]
So the idea here is to only probe the area of the bed that the first layer covers? Interesting utility.

**Comment by tonnico** [comment]
@thinkyhead right. I will tweak this next days a little bit more.

Ideas:
minimum area to scan
only read file until it has the first plane and not to a number of max lines
add argparser

**Comment by AnHardt** [comment]
@Wurstnase 
And what is it good for? When test points are more apart its much easier to measure the skew.

**Comment by tonnico** [comment]
@AnHardt We don't live in a perfect world. The bed is not everytime perfectly flat. So why not only scan the part where you are printing? If your part is very small you can add an offset.

I saw some heatbeds which are bigger than 400x400. And they are not perfectly flat. For printing big parts you need a really thick first layer, but for small parts it isn't necessary if you only scan that area.

**Comment by boelle** [comment]
the idea is not that bad... just a shame it only works for sd card printing... but that is what you should do anyway to make sure better prints

**Pull request merged**
