### PR TITLE
Dynamic Tool Migration — Swap extruders on runout

### PR DESCRIPTION
**Pull request by thinkyhead**
Based on #10040 by Steeve Spaggi (or is it Steeve Maïni?)

- LCD menu item and G-code `M606` to migrate anytime.
- Supersedes `FILAMENT_RUNOUT_SCRIPT` while extruders are available.
- Compatible with `FWRETRACT`, preserving the last retraction.
- Compatible with `NOZZLE_PARK_FEATURE`.
- Configure the last usable extruder with `M606 L` or menu item.

The original PR was a bit stale, so this may need updates for newer code, such as `FWRETRACT`. Also needs some sanity-checking and testing with a variety of setups. Could be adapted to some special configurations, such as mixing extruders, automatically changing the mix (e.g., 1,0,0 becomes 0,1,0) when filament runs out.

Needs lots of testing to ensure it works reliably.

### CODE REVIEW

**Comment by thinkyhead** [comment]
This might be of interest to you, @marcio-ao !

**Comment by marcio-ao** [comment]
@thinkyhead: This seems like a useful feature!

**Comment by InsanityAutomation** [comment]
This coupled with your filament run-out stuff would be great. Make fighting the dual v3 a bit more worthwhile.

**Comment by Roxy-3D** [comment]
> This seems like a useful feature!

Agreed.   Hopefully it can be very easy to switch modes.   And maybe even report on the LCD Panel which mode it is in.

I'll use it.

**Comment by thinkyhead** [comment]
One thing this doesn't do is call `tool_change`, so it's really only compatible with `SINGLENOZZLE`. It needs more work to be suitable for any other type of setup. Maybe it can simply call `tool_change` where it currently sets `active_extruder` directly.

**Comment by hussainsail2002** [comment]
@thinkyhead 

just out of curiosity will this work with idex based printers where once one head runs out of filament the other will come in and print ?

**Comment by InsanityAutomation** [comment]
@hussainsail2002 an idex implementation can actually be far simpler than this. The extensions to tool change since this was written handle half of what this was trying to do anyway hence why is was closed. A bit of a different implementation with that in mind has been discussed a few times and is on the ever growing todo list....

**Pull request closed without merging**
