### PR TITLE
Show Total E during print

### PR DESCRIPTION
**Pull request by thinkyhead**
### Description

This PR adds a new configuration option `LCD_SHOW_E_TOTAL` that will cause Marlin to display a running total of the E movement for the current print job in place of the X and Y positions.

The current methodology is to keep an accumulator of E position alterations by `G92` so that the total commanded forward motion can be displayed. At present this method doesn't account for cold or long extrusion prevention, or other events that necessarily alter the E position but don't actually extrude filament. A more step-accurate method to track E could be applied at the planner segment level but this would multiply the feature load and would not match the predicted E motion given in the G-code.

### Benefits

The X and Y positions aren't very useful during a print, so this provides probably the most useful and generic piece of alternative information for the average user.

### Requirements

A character or u8g-supported graphical LCD controller is required.

image

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I like having this on the LCD Panel!    Are you thinking of making it an option on the Graphical LCD Panels too?

**Comment by thinkyhead** [comment]
It currently works with the u8g-supported graphical displays. Later I'll add support for ExtUI displays too. It could also be added for some serial touch displays, but on the message line.

**Comment by thisiskeithb** [comment]
Is the original intention to keep track of used filament during a print? PrusaSlicer's default profiles all have `G92 E0.0` sent before each layer, so that'll reset the counter:

Screen Shot 2019-10-27 at 1 12 04 PM

**Comment by thinkyhead** [comment]
This accounts for `G92` in the manner described.

**Comment by InsanityAutomation** [comment]
This goes a good way towards what Gcreate was using an external device for at ERRF. A few tweaks to allow setting a spool size and density and you can do calculated runout without a sensor by extruded volume....

**Comment by thinkyhead** [comment]
> spool size and density

Unfortunately this initial method is faithful only to the commanded number of mm and doesn't even account for flow percentage. So, the most accurate method will have to use the commanded steps both forward and backward, and be able to ignore motion during pause activities, and so on. Eventually we can do that, but I wanted to make the most low impact method first, and make the more accurate method an extended option.

**Comment by InsanityAutomation** [comment]
@thinkyhead Yeah, definitely a 3 steps ahead thought there. This just puts a stone on the path towards it.

**Comment by thinkyhead** [comment]
The added commit is an attempt at the other approach. It just accumulates E motion in the planner after other factors have been applied. It adds an additional float load-add-store for every segment, but will be exactly correct about the mm moved even if you're changing the flow up and down all the time. However, it does not account for where the motion comes from. So a filament unload/reload will be counted just as much as print moves.

**Comment by InsanityAutomation** [comment]
I would expect that to be the case. I would assume the value to be set before starting a print in the long term goal case after material is loaded.

**Comment by thinkyhead** [comment]
The best method in terms of real accuracy turns out to be at the block level, but the mm is already available, so the added cost is just one float fetch-add-store per block. I just gave it a test and it's good. I'm going to deploy it on all the machines here.

**Comment by thisiskeithb** [comment]
As [I tweeted a little bit ago](https://twitter.com/thisiskeithb/status/1188636693043142656), it works great!

Any chance we can keep the used filament on the screen after the print completes instead of showing the X/Y coordinates?

**Comment by firepower9966** [comment]
Can this also be displayed instead of mixing % Values, when only one extruder is being used 100% for print. This is way more useful.

**Pull request merged**
