### PR TITLE
[2.0.x] Add Smoothieboard pins file

### PR DESCRIPTION
**Pull request by GadgetNutt**
### Description
Added a pins file for Smoothieboard.
pins_SMOOTHIEBOARD.h

Updated boards.h to define BOARD_SMOOTHIEBOARD as 1757

Updates pins.h to add pins_SMOOTHIEBOARD.h inclusion in the LPC176x section

Updated drivers.h to add A5984 stepper driver for Smoothieboard.

Updated Conditionals_post.h to add delay and pulse information about A5984 stepper driver for Smoothieboard.

Updated Configuration.h and Configuration_adv.h with comment details about the A5984 stepper driver for Smoothieboard.

Tested on a Smoothieboard 5xC V1.1 which uses A5984 stepper drivers.

X, Y, Z, E0 Homing ... SUCCESS
Fan 0 and Hotend 0 ... SUCCESS
Temp0 ... SUCCESS
Heatbed ... NOT TESTED YET (SHOULD WORK)
#define SERIAL_PORT_2 0 @ 115200 (for MKS_TFT32) .... SUCCESS
### Benefits

Adds pin support for Smoothieboard V1 and V1.1

### Related Issues

None known.

### CODE REVIEW

**Comment by ModMike** [comment]
Is the onboard SD card usable by Marlin?  I can't get the X5 Mini mounted and suspect is some kind of communication clash with the ESP8266 WEB UI.

**Comment by p3p** [comment]
> Is the onboard SD card usable by Marlin? 

The onboard card is currently reserved for eeprom (although the new flash based system will more then likely be changed to the default) and the usb drive. Marlin has no access to it.

It's on the todo list with the new framework.

**Comment by ModMike** [comment]
What persistentStore.api that was added a few days ago do?

**Comment by p3p** [comment]
Not sure what your question is, but .. yes? if you uncomment `#define FLASH_EEPROM` in `HAL_LPC1768/peristant_store_api.h` Marlin will use the Flash for the EEPROM rather than the sdcard, this will be easier to configure and probably the default in the future.

**Comment by ModMike** [comment]
Ok if I do that and I leave eeprom enabled, will the SD card be available to Marlin?

**Comment by p3p** [comment]
Not yet no, the platform is a work in progress, it was designed for a basic ramps setup on a Re-ARM but is getting more generic.

**Comment by ModMike** [comment]
Alright, last option.  If could care less about eeprom for now, can I disable it and then have Marlin access the SDcard?

**Comment by p3p** [comment]
Sorry I should have been more clear when I said it above, currently there is no way for Marlin to access the  onboard sdcard, but it is been worked on.

I can't walk you through trying this but if you feel adventurous, disable usb initialisation in main.cpp, enable Flash eeprom, and put in the correct SPI pins for the onboard card and it may work.

**Comment by ModMike** [comment]
I do and thank you for the tip!  By the way I am working with a Re-Arm brother, the Azteeg X5 Mini Wifi.

**Comment by ModMike** [comment]
So I gave it the old college try but it's above my pay grade.  I have no choice but to wait.

**Comment by ModMike** [comment]
Are these the files I need to comment out in Main.cpp to disable USB or are there other ones?

#include <usb/usb.h>
#include <usb/usbcfg.h>
#include <usb/usbhw.h>
#include <usb/usbcore.h>

These are the SD card pins.  I used Smoothie as they are "supposed" to be the same.  Does it look right?

#define MISO_PIN     P0_8
#define MOSI_PIN     P0_9
#define SCK_PIN      P0_7
#define SS_PIN       P0_6

**Comment by ModMike** [comment]
Never mind, will open an issue to develop the secret sauce.

**Pull request merged**
