### PR TITLE
MARLIN_SIMULATION_BUILD

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR is the start of the concept for a `MARLIN_SIMULATION_BUILD` option to substitute all hardware functions involving steppers, heaters, and sensors with simulated versions that don't move steppers, set heaters, or read real thermistors.

The LCD and other I/O functions continue to work normally with this type of build.

The stepper ISR continues to run, giving a real-time approximation of movement timing.

TODO:
- Simulated heaters and thermistors that change gradually (but quickly)
- Simulated endstops that trigger in G28 with no delay (but don't otherwise trip).
- Simulate a probe pin (in G29) that triggers at an idealized Z position.
- A monitor to periodically log all the interesting changed values.

### CODE REVIEW

**Comment by jbrazio** [comment]
Scott isn't that exactly the same thing as this ?

ramps

**Comment by thinkyhead** [comment]
I would like to keep my machine as it is. I don't like pulling wires.

**Comment by jbrazio** [comment]
Even a stock Arduino Mega without any shield works as a debug platform with the current RCBugfix.

**Comment by thinkyhead** [comment]
Yes, it's pretty awesome. I like the use of the oscilloscope. Very cool. I wish I had an extra Arduino or two (that are easy to build for) but at the moment the only spare I have is a Teensy (which is tricky to build for). And, what I'd like to do is just flash the board in my printer with Delta code (even though it's not a delta) and run it without having the axes go all nuts, but still be able to trace the changes in coordinates.

**Comment by jbrazio** [comment]
> And, what I'd like to do is just flash the board in my printer with Delta code (even though it's not a delta) and run it without having the axes go all nuts, but still be able to trace the changes in coordinates.

Just power it using the USB cable and leave the power supply off, everything will be functional from inside Marlin doing exactly what you require.

**Comment by petrzjunior** [comment]
@jbrazio Beautiful photo! @clexpert built something similar for me. Just Arduino, RAMPS shield and resistors to simulate hotend temperature. No endstops, nothing. And that's where `FILAMENT_CHANGE_FEATURE` was born. :smile: 
dscn0327

**Comment by thinkyhead** [comment]
> leave the power supply off

All good, but those simulated thermistors always register the same temperature. It would be better if they would simulate a temperature rise when "heating" and a temperature drop when "cooling."

**Pull request closed without merging**
