### PR TITLE
Creality v4 clean up and pin correction. 

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Clean up of Creality V4

1) new users don't have prior knowledge that if they have a Creality V4.2.2 controller they should use BOARD_CREALITY_V4
This causes great confusion. So I have added a BOARD_CREALITY_V422 as a alias for BOARD_CREALITY_V4

2) The creality V4 boards uses SDIO for the sdcard interface. But the pins_CREALITY_V4.h  adds in SPI interface defines.
ONBOARD_SPI_DEVICE and ONBOARD_SD_CS_PIN
These are not needed. 
ONBOARD_SD_CS_PIN is set to PA4, which is the filament run out sensor pin on 4.2.2 and 4.2.7 (and maybe others)

PA4 does not go to any pins of the sdcard socket
confirmed with 3rd party circuit diagram https://github.com/Jyers/Marlin/files/7209579/Creality.4.2.2.-.Schematic.22-9-21.pdf

3) update comments to include STM32F103RC 

4) add STM32F103RC env to BOARD_CREALITY_V423

### Benefits

Less confusion

### CODE REVIEW

**Comment by The-EG** [comment]
Just out of curiosity, what is the:
> a conflict with the filament run out sensor pin

I use a sensor plugged into the J1 port, which would use that pin, on both 4.4.2 and 4.2.7 boards. Is it just a conflict in that it's defined in both places but not actually being used for the SD? Or does it cause actual issues, that I seem to have been lucky enough to avoid?

**Comment by ellensp** [comment]
I don't think its causing any issue, is just a clean up. removes it from pins debugging, and remove some confusion. 
I've cleaned up the description to remove this ambiguity.

**Comment by brunohenriquy** [comment]
@ellensp Also consider changing the comment
// Creality v4.2.2 (STM32F103RE) 
to
// Creality v4.2.2 (STM32F103Rx)

Since now it's used for both RET and RCT
Check this -> https://github.com/MarlinFirmware/Marlin/pull/23599

**Comment by ellensp** [comment]
@brunohenriquy  good idea, but not using Rx, previous examples use "STM32F103RC / STM32F103RE" so I will stick to that convention

**Comment by brunohenriquy** [comment]
> @brunohenriquy good idea, but not using Rx, previous examples use "STM32F103RC / STM32F103RE" so I will stick to that convention

Perfect!

**Comment by brunohenriquy** [comment]
@ellensp
Shouldn't "#define BOARD_CREALITY_V4             4040  // Creality v4.x (STM32F103RE)" also be changed?
Also,  why you skipped "#define BOARD_CREALITY_V423           4042  // Creality v4.2.3 (STM32F103RE)"?

**Comment by ellensp** [comment]
when RC where added they where not added to BOARD_CREALITY_V423,  I don't know why, but i'm not arbitrarily adding it.
I have left thisiskeithb a message regarding this.

**Comment by brunohenriquy** [comment]
> when RC where added they where not added to BOARD_CREALITY_V423, I don't know why, but i'm not arbitrarily adding it. I have left thisiskeithb a message regarding this.

Gotcha! Thank you!

**Comment by thisiskeithb** [comment]
> when RC where added they where not added to BOARD_CREALITY_V423, I don't know why, but i'm not arbitrarily adding it. I have left thisiskeithb a message regarding this.

I reviewed [my PR](https://github.com/MarlinFirmware/Marlin/pull/23599/commits/fda2d0a228f4468911f670e04910ffc4e1d8dd85) again I must have done a find & replace for `env:STM32F103RET6_creality env:STM32F103RET6_creality_xfer env:STM32F103RET6_creality_maple` and the 4.2.3 board didn't have a maple environment, so it wasn't added.

Feel free to add it here.

**Comment by ellensp** [comment]
Added RC build env to CREALITY_V423 and update comments

**Comment by lulol** [comment]
Creality v4.2.2 schematics linked above (22-9-21) has a small bug. [Updated version here](https://github.com/Jyers/Marlin/discussions/814)

Schematic also is available for Creality v4.2.7

**Pull request merged**
