### PR TITLE
Allow USB vendor and product ID to be changed from "Config_adv.h"

### PR DESCRIPTION
**Pull request by marcio-ao**
Allow definition of `USB_DEVICE_VENDOR_ID`, `USB_DEVICE_PRODUCT_ID` and `USB_DEVICE_MANUFACTURE_NAME` from "Configuration_adv.h"

### CODE REVIEW

**Comment by p3p** [comment]
Perhaps the default should be our [openmoko](https://raw.githubusercontent.com/openmoko/openmoko-usb-oui/master/usb_product_ids.psv) id `1D50:6029` USB Serial or `1D50:602A` USB Mass storage, I think `602A` has made it into the linux id list but unfortunately I chose to use the other.

**Comment by marcio-ao** [comment]
@p3p: I set the default to zero as this will cause an error to be generated during compilation.

**Comment by InsanityAutomation** [comment]
Maybe this would go well in the vendor version file as broken out in #14189 with the defaults defined behind it? Not something you typically want exposed to a normal user.

**Comment by marcio-ao** [comment]
@InsanityAutomation: With my [latest clean up of the Lulzbot Marlin 2.0 branch](https://code.alephobjects.com/diffusion/MARLIN/browse/devel/config/examples/AlephObjects/), I began providing "Configuration.h" and "Configuration_adv.h" for all our printers and toolheads, so my thought process about putting the IDs in there was that if a user copied over the appropriate "Configuration_adv.h" they could get the correct vendor ID.

But I suppose on the other hand, if someone is compiling unofficial firmware, then perhaps I don't want it to carry our vendor ID. So maybe it makes sense to have a separate version file, as you suggest -- that would mean they would only get our ID if compiling from our source tree.

Either way, would work for me, I suppose :)

**Comment by InsanityAutomation** [comment]
@marcio-ao I got tired of updating the url, dist date, version strings and all that when merging updates in. Its gotten to where i usually delete the src folder, paste the new one in, and tell git to ignore changes to that file.... I also wanted to generate some of the version string based on options in configuration.h progmatically so it was easy to know the configuration end users were running from the info screen. That made it necessary to move after configuration.h in the include order.

**Comment by marcio-ao** [comment]
@InsanityAutomation: After looking at your PR, I think it would be a suitable replacement for this one if the USB vendor ID stuff was added to the custom version file. Would you be able to modify your PR to include that? If so, I can go ahead and close this one.

**Comment by InsanityAutomation** [comment]
Sure, Ill look at copying over what you have here this afternoon.

**Comment by InsanityAutomation** [comment]
Actually it was just a couple lines so I tossed it in. A couple things to consider.

Right now only the due supports this, and the defines are in the HAL. If the intent is for more platforms to support it, we should probably move them out of the usb_conf.h there into the default version.h file as well so they can be utilized if desired and arent missed when other platforms add support. Any objection to this?

I made the default vendor string the website_url define because that matches what the default is in the usb_conf currently. Seemed reasonable to just use the same define.

**Comment by marcio-ao** [comment]
> Right now only the due supports this, and the defines are in the HAL. If the intent is for more platforms to support it, we should probably move them out of the usb_conf.h there into the default version.h file as well so they can be utilized if desired and arent missed when other platforms add support. Any objection to this?

This is good.

> I made the default vendor string the website_url define because that matches what the default is in the usb_conf currently. Seemed reasonable to just use the same define.

Yes, that's fine.

I'm closing this PR and suggesting @thinkyhead merge https://github.com/MarlinFirmware/Marlin/pull/14189 instead.

**Pull request closed without merging**
