### PR TITLE
UBL Menu System

### PR DESCRIPTION
**Pull request by Tannoo**
```
/**
* UBL System submenu
*
*  Prepare
* - Unified Bed Leveling
*   - Activate UBL
*   - Deactivate UBL
*   - Mesh Storage
*       Memory Slot:
*       Load Bed Mesh
*       Save Bed Mesh
*   - Output Map
*       Map Type:
*       Output Bed Mesh Host / Output Bed Mesh Excel
*   - UBL Tools
*     - Build Mesh
*         Build PLA Mesh
*         Build ABS Mesh
*       - Build Custom Mesh
*           Hotend Temp:
*           Bed Temp:
*           Build Custom Mesh
*       - Build Cold Mesh
*       - Fill-in NANs
*           Fill-in Mesh
*           Smart Fill-in
*         Continue Bed Mesh
*     - Validate Mesh
*         PLA Mesh Validation
*         ABS Mesh Validation
*       - Custom Mesh Validation
*           Hotend Temp:
*           Bed Temp:
*           Validate Mesh
*     - Edit Mesh
*         Edit PLA Mesh
*         Edit ABS Mesh
*       - Edit Custom Mesh
*           Hotend Temp:
*           Bed Temp:
*           Edit Mesh
*       - Adjust Mesh Height
*           Height Amount:
*           Adjust Mesh Height
*     - Mesh Leveling
*         3-Point Mesh Leveling
*       - Grid Mesh Leveling
*           Side points:
*           Level Mesh
*   - Output UBL Info
*/
```

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Have you tested each option?    I'm wondering if this should be merged to go into the 'Golden Master'.

**Comment by Tannoo** [comment]
I have tested that each option passes the commands.
I have not edited any meshes yet. I have run everything else.

Why is travis saying that the BED_MINTEMP and BED_MAXTEMP are not in scope?

I don't have compile errors and can set bed temp on the display between those limits.

**Comment by Roxy-3D** [comment]
> Why is travis saying that the BED_MINTEMP and BED_MAXTEMP are not in scope?
> I don't have compile errors and can set bed temp on the display between those limits.

You don't have compile errors with your configuration.  But Travis checks a million different configurations.   

If you click on:  https://travis-ci.org/MarlinFirmware/Marlin/builds/228527217?utm_source=github_status&utm_medium=notification

You can see the configuration that caused it to barf.
```cpp
The command "opt_enable EEPROM_SETTINGS EEPROM_CHITCHAT M100_FREE_MEMORY_WATCHER M100_FREE_MEMORY_DUMPER M100_FREE_MEMORY_CORRUPTOR INCH_MODE_SUPPORT TEMPERATURE_UNITS_SUPPORT" exited with 0.
9.46s$ build_marlin
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Xlib:  extension "RANDR" missing on display ":1.0".
Initializing packages...
Preparing boards...
Verifying...
sketch/M100_Free_Mem_Chk.cpp: In function 'void dump_free_memory(const uint8_t*, const uint8_t*)':
sketch/M100_Free_Mem_Chk.cpp:124:24: warning: comparison between distinct pointer types 'const uint8_t* {aka const unsigned char*}' and 'char (*)[96]' lacks a cast [-fpermissive]
```
This looks suspicious:
```cpp
'const uint8_t* {aka const unsigned char*}' 
```
Update:  A simple cast would fix that...    Below is the likely problem.

**Comment by Roxy-3D** [comment]
I bet this commit blows up on the same thing....  we will know soon:

https://github.com/MarlinFirmware/Marlin/pull/6559/commits/9890141f7b7f0ac5b827134f0da95ebe9addec7c

**Comment by Roxy-3D** [comment]
More analysis...   Your update did not envision what happens if there is no heated bed.  It is assuming it can  reference things like BED_MINTEMP even if there is no heated bed.   The lines Travis is complaining about need to have #if WATCH_THE_BED wrapped around them.  If there is no heated bed, WATCH_THE_BED won't be defined and the line won't be included in the compilation.

   #define MENU_ITEM_EDIT(type, label, ...) MENU_ITEM(setting_edit_ ## type, label, PSTR(label), ## __VA_ARGS__)
                                            ^
sketch/ultralcd.cpp:1774:7: note: in expansion of macro 'MENU_ITEM_EDIT'
       MENU_ITEM_EDIT(int3, MSG_UBL_CUSTOM_BED_TEMP, &CUSTOM_BED_TEMP, BED_MINTEMP, (BED_MAXTEMP - 5));

**Comment by Tannoo** [comment]
Ok. I might not be able to get that until morning now. At that pesky work thing again.

**Comment by Roxy-3D** [comment]
Can we merge this one too?   If there are any issues...   I'll get them resolved ASAP.

**Comment by Tannoo** [comment]
I put in what you said Roxy. I can't test it atm. I will in the am.
Travis likes it though!

**Comment by 040medien** [comment]
Why Excel? Wouldn't "CSV" or "spreadsheet" be a better, more generic term here?

**Comment by Tannoo** [comment]
I guess CSV would work. Spreadsheet didn't fit on the LCD.

**Comment by Tannoo** [comment]
What about "Delimited"?

**Comment by 040medien** [comment]
I don't think many would understand what that means. What is the delimiter? Comma?

**Comment by Tannoo** [comment]
Yes. I changed it to "CSV".

**Comment by Tannoo** [comment]
I'm guessing that I have to re-submit this against bugfix1.1?

**Comment by Bob-the-Kuhn** [comment]
I did a little playing with it last night.

It'll home the machine when you do a map.  That's surprising.  I don't think it belongs.

Why are you doing a M428?

Are you planning on adding a G29 P2 B ?

----

I screwed up on my last changes to UBL.  

At about line 1060 in UBL_G29 are the "Invalid X location specified" lines.  They should have the X_MIN_POS values rather than the UBL_MESH values.  They should read.
```
    if (!WITHIN(RAW_X_POSITION(x_pos), X_MIN_POS, X_MAX_POS)) {
      SERIAL_PROTOCOLLNPGM("Invalid X location specified.\n");
      err_flag = true;
    }

    if (!WITHIN(RAW_Y_POSITION(y_pos), Y_MIN_POS, Y_MAX_POS)) {
      SERIAL_PROTOCOLLNPGM("Invalid Y location specified.\n");
```

**Comment by Tannoo** [comment]
>It'll home the machine when you do a map. That's surprising. I don't think it belongs.

I agree, and it doesn't. This, (in `ubl_g29.cpp`):
```
    if (!code_seen('N') && axis_unhomed_error(true, true, true))  // Don't allow auto-leveling without homing first
      home_all_axes();
```
doesn't allow it, when sending this command: `PSTR("G29 N O%i"), map_type`.
I doesn't home during the following options:
Activate or deactivate UBL
Mesh Storage operations
Output mesh map operations
Fill-in operations
Adjust Mesh Height operations



>Why are you doing a M428?

That's not in anything I wrote.

>Are you planning on adding a G29 P2 B ?

I didn't have plans, but that's why code evolves.
If you want me to add that, what you like me to name it (as an item to select)?

**Comment by Roxy-3D** [comment]
> It'll home the machine when you do a map. That's surprising. I don't think it belongs.

G29 insists the machine is homed before it does anything for safety reasons.   But maybe we should consider certain things that can be done without the machine being homed.  For example...  displaying a map.   Or even for that matter...  Activating and Deactivating.   

Right now...  The very first thing G29 does is check if the machine is homed.   And if it is not...  It will home the machine.    Maybe we should relax that constraint???

**Comment by Roxy-3D** [comment]
>> Are you planning on adding a G29 P2 B ?

> I didn't have plans, but that's why code evolves.  If you want me to add that, what you like me to name it (as an item to select)? 

That would be **Manual Probe**

**Comment by Tannoo** [comment]
Add it to the Fill-In menu?

**Comment by Roxy-3D** [comment]
> Add it to the Fill-In menu?

I don't understand the question...

**Comment by Tannoo** [comment]
United Bed Leveling > UBL Tool > Build Mesh > Fill-In NANs > Manual Probe - `(G29 P2 B)` 

I ask this because G29 P2:
`Probe areas of the Mesh that can't be automatically handled.`

**Comment by Tannoo** [comment]
Or, should I locate it in the `Build Mesh` menu?

**Comment by Tannoo** [comment]
I am thinking of renaming the 'Fill-in NANs' to 'Fill-in Mesh'.

**Comment by Roxy-3D** [comment]
Yeah...  Fill-in Mesh is better.   And even though its P2,   I would argue it should placed after P3 just because most people will be doing P3.

And United is not correct...  Unified...

**Comment by Tannoo** [comment]
>And United is not correct... Unified...

Yeah....sorry. 

NOTE: It's not in the menu that way, I just made an error in the message.

**Comment by Roxy-3D** [comment]
Not a problem!!!   It is just best to address any error as soon as it is noticed!  That way it doesn't propagate.

**Comment by Bob-the-Kuhn** [comment]
Maybe I was hallucinating.  I can't find my notes on which command it popped up on.  Really strange as the UBL menu code doesn't call that function.  

I'll let you know if I ever see it pop up again.

----

**Manual Probe** -  what a boring name.  How about "Bob's great & glorious idea!!"?

**Comment by Roxy-3D** [comment]
> Manual Probe - what a boring name. How about "Bob's great & glorious idea!!"?

The good news is that won't fit on the LCD Screen.   But there is lots of room in the source file for comments!

**Comment by Tannoo** [comment]
>Maybe I was hallucinating. I can't find my notes on which command it popped up on. Really strange as the UBL menu code doesn't call that function.

Don't feel bad, I've invoked the `Set Home Offsets` a few times when my encoder didn't agree with what was selected on the screen.
I have tried to avoid that by scrolling down to `Set Home Offsets` and then back up to `Unified Bed Leveling`. I haven't had any mishaps since.

**Comment by Tannoo** [comment]
Manual Infill?

**Comment by Bob-the-Kuhn** [comment]
I'm still invoking  `Set Home Offsets` but at least I now know why.

Did some more playing with the menu system.  Right now you have to read the host screen to get the instructions while doing G29 P2.  I've tried to get around that by adding LCD messages to G29 P2.  Mostly OK results except that getting back to the status screen is slow.

Is there a way to immediately go back to the status screen?  

I've tried various combinations of the following in the G29 P2 routines but they all wait for the timeout.
```
LCD_MESSAGEPGM("Place shim & measure");
lcd_status_screen();
lcdDrawUpdate = LCDVIEW_REDRAW_NOW;
lcd_quick_feedback();
```

----

There's a typo in the manual fill in.  It says G28 P2 B right now instead of G29 P2 B

**Comment by Roxy-3D** [comment]
> Is there a way to immediately go back to the status screen?

Yes...  That is very easy.  Just do a:
```cpp
 lcd_goto_screen(lcd_status_screen);
```

I wonder if we could have the manual probe screen update the LCD Panel with a Z-Height number similar to what Z-BabyStepping does?    That would be really nice.   I think you could just copy what G29 does to fine tune the mesh with a G29 P4.  
```cpp
    ubl.save_ubl_active_state_and_disable();
    ubl.has_control_of_lcd_panel = true;
    LCD_MESSAGEPGM("Manual Probe:");
    lcd_implementation_clear();
    lcd_mesh_edit_setup( current_position[Z_AXIS]);   // not sure about this... but something close to this
      do {
        new_z = lcd_mesh_edit();
        idle();
      } while (!ubl_lcd_clicked());
      lcd_return_to_status();
      ubl.has_control_of_lcd_panel = true; 
      const millis_t nxt = millis() + 1500UL;
      while (ubl_lcd_clicked()) { // debounce and watch for abort
        idle();
        if (ELAPSED(millis(), nxt)) {
          lcd_return_to_status();
          //SERIAL_PROTOCOLLNPGM("\nFine Tuning of Mesh Stopped.");
          do_blocking_move_to_z(Z_CLEARANCE_DEPLOY_PROBE);
          LCD_MESSAGEPGM("Mesh Editing Stopped");

          while (ubl_lcd_clicked()) idle();

          goto FINE_TUNE_EXIT;
        }
      }
```

**Comment by Tannoo** [comment]
>It says G28 P2 B right now instead of G29 P2 B

Sorry, corrected.

**Comment by Tannoo** [comment]
>Is there a way to immediately go back to the status screen?

Should I put that in for all of the screens or just a few select ones? Also, as an option, or the default back?

Add this to whatever screen to want the option to return to status:

`MENU_ITEM(submenu, MSG_WATCH, lcd_status_screen);`

**Comment by Roxy-3D** [comment]
Oh...  Maybe I misunderstood Bob's question.   I was thinking he wanted the G29 P2 Manual Probe code to send the LCD Panel back to the Status Screen at the end...

**Comment by Tannoo** [comment]
I did change the 'back' messages to be more consistent with Marlin's menu hierarchy.
I also added a menu item to return to info screen on the deeper menus. (Build, Validate, Edit, Fill-in and mesh height)

**Comment by Tannoo** [comment]
I had broken some things in trying to shrink the code size. Well, I had to un-break it.

I guess evolution can be painful.

**Comment by Bob-the-Kuhn** [comment]
Thanks, Roxy, for the` lcd_goto_screen(lcd_status_screen);` pointer.  It was exactly what I needed.

I've got G29 P2 & G29 P4 working entirely through the LCD.

Next step is to see how G26 & the LCD work together.

I can post what I have in the morning if you wish or I can do it after I'm done with G26.

Now if I could only stop solving non-existent problems ...

**Comment by Tannoo** [comment]
I would like to see what you did.

**Comment by Bob-the-Kuhn** [comment]
I don't think I have write privileges so here's a [link to them](https://www.dropbox.com/s/9vavtsm7wm6pecf/ubl_G29%206%20MAY.zip?dl=0).

@Roxy-3D - I updated the files to yesterday's 1.1.xfixes.  There were deletions of what I thought were useful menu items.  Please verify that the deletions are what you wanted.



----

ubl_G29.cpp

Added in the latest changes from 1.1.xfixes.

Changed the manual probing so that, after doing the business card, the nozzle is Z_CLEARANCE_BETWEEN_PROBES above the BED rather than above the Z=0 point.  Saves a lot of time twisting the encoder.

I had to change height to float so I could the above.

Added LCD messages to the manual probing routines.

In parse G29 limited the repetition count to the maximum grid size.

Corrected the logic for the "Invalid X location ..." locations.


ultralcd.cpp

Added in the latest changes from 1.1.xfixes.  Some of the changes were to delete menus I thought were useful.

Under edit mesh I removed all the temperature related items and replaced them with a couple of simpler ones.  The G29 P4 command doesn't move the nozzle to the bed so having the nozzle or the bed at temperature is not needed.  The new items are FINE TUNE ALL and FINE TUNE CLOSEST.

Under build mesh added INVALIDATE ALL and INVALIDATE CLOSEST menu items.

**Comment by Tannoo** [comment]
Can you PR me here: https://github.com/Tannoo/Marlin/tree/UBL_Menu_System

**Comment by Bob-the-Kuhn** [comment]
I tried but I couldn't fork your repository.

Also, the mesh save menu isn't working.  I'll see what I can do.

----

I see an 'N' in some of your G29 commands.  What is the N for?

**Comment by Roxy-3D** [comment]
> I see an 'N' in some of your G29 commands. What is the N for?

The 'N' turns off the requirement that the printer has been homed before allowing G29 to do any commands.    It really was just for me during development.  It was so I didn't have to home the machine to use simple things like G29 O or G29 W.

**Comment by Tannoo** [comment]
Download a new copy. It all works.

**Comment by Tannoo** [comment]
As I stated earlier: >I had broken some things in trying to shrink the code size. Well, I had to un-break it.

I am now up and I'll get your changes applied....it'll only take a few.

**Comment by Bob-the-Kuhn** [comment]
Here's an updated [ultralcd.cpp](https://www.dropbox.com/s/l6zdee1c8h9ptt9/ultralcd.zip?dl=0) with the load & save fixed.

I finally noticed the menu tree so I updated it with my changed.

I've taken all the "N"s out of the G29 commands.

I developed a different method of appending a variable's value to a G29 command.  And then I noticed the spintf_P version.  I left my version in there just in case it's of any interest.  The spintf_P versions are there in a comment block so switching will be easy.

**Comment by Tannoo** [comment]
>I've taken all the "N"s out of the G29 commands.

Why?

So, you don't mind it homing the printer before outputting the mesh to the serial console?
Or, homing before loading or saving a mesh?
Or, homing before changing the mesh height?

**Comment by Bob-the-Kuhn** [comment]
I thought they were only for Roxy's development system.

I'll gladly put them back in.  Maybe better yet is to figure out how to remove the homing function from everything except the commands that probe.  I think that's the J, P1 & P2 & Z commands.

**Comment by Tannoo** [comment]
>Maybe better yet is to figure out how to remove the homing function from everything except the commands that probe. I think that's the J, P1 & P2 & Z commands.

I agree. I left them in there for now.

This PR is getting stale, I'm going to have to create another one soon. As I can't tell what changes you've done to `ubl_G29.cpp` due to too many differences throughout the whole file.

**Comment by Roxy-3D** [comment]
> I thought they were only for Roxy's development system.

Sorry about that!  I was just trying to give you the history of the 'N' parameter.  As it turns out...  Tannoo found it useful too!     I did take it out of the documentation just because it isn't something most users should be doing.   But the functionality is still in the code.

**Comment by Tannoo** [comment]
>I did take it out of the documentation

Yeah, I was starting to use it before you did that. That's how I found out about it.

**Comment by Tannoo** [comment]
Errors on language file definitions? Really?

**Comment by Tannoo** [comment]
Trying this again. I am getting better at squashing. lol

**Comment by Roxy-3D** [comment]
I wouldn't even get this far...   I would set the directory aside and delete the branch.  I would re-fork and start moving my differences over to the new fork.    Git is so difficult!!!!!

**Comment by Tannoo** [comment]
Yeah, I might do that with the new bugfix1.1 branch, just to get up to date.

**Comment by Bob-the-Kuhn** [comment]
I don't understand why we're getting invalid message names.  Some of the names were in both of the ultralcd.cpp files I posted.  The remainder were in neither.

**Comment by Tannoo** [comment]
I renamed some to try to combat this issue. I am going to re-do it again.

There has to be an invalid character somewhere. I haven't found it.

**Comment by Tannoo** [comment]
```
The command "opt_enable AUTO_BED_LEVELING_UBL UBL_G26_MESH_EDITING ENABLE_LEVELING_FADE_HEIGHT FIX_MOUNTED_PROBE EEPROM_SETTINGS G3D_PANEL" exited with 0.
```
Ok... I am going to change my display to G3D and see about the compiling issues. This is getting old.
I have all the others enabled already.

**Comment by Bob-the-Kuhn** [comment]
Check the files to see if the EOL is correct.  I've had some local compiles go wrong because some of the files had windows EOLs and some had Unix EOLs.

I just enabled all the options and it compiled fine for me.

Are you doing a `git push -f` after the rebase -i has completed?  That's supposed to make sure Travis is using all the files from your repository.

**Comment by Tannoo** [comment]
I didn't squash this time.... it still doesn't like it.

**Comment by Tannoo** [comment]
```
sketch\ultralcd.cpp: In function 'void _lcd_ubl_build_mesh()':

ultralcd.cpp:1909: error: 'lcd_ubl_invalidate' was not declared in this scope

       MENU_ITEM(function, MSG_INVALIDATE_ALL, lcd_ubl_invalidate);

                                               ^

sketch\ultralcd.cpp:266:30: note: in definition of macro '_MENU_ITEM_PART_2'

         menu_action_ ## TYPE(__VA_ARGS__); \

                              ^

sketch\ultralcd.cpp:1909:7: note: in expansion of macro 'MENU_ITEM'

       MENU_ITEM(function, MSG_INVALIDATE_ALL, lcd_ubl_invalidate);

       ^

exit status 1
'lcd_ubl_invalidate' was not declared in this scope
```

This was after enabling G3D panel.
Definite compile errors.

**Comment by Tannoo** [comment]
`'lcd_ubl_invalidate' was not declared in this scope` was a new one.... it should have been `_lcd_ubl_invalidate`

**Comment by Tannoo** [comment]
Got it.... Now, to squash it again.

**Comment by Tannoo** [comment]
This is what I do to squash:
Open git shell. (from git desktop)
git rebase -i HEAD~# <-- Number of commits.
Change all but the top `pick` to `s`, save and close the editor.
Edit the comments for the squash, save and close the editor.
git push origin branch-name --force

And done.

This only works well if I don't "update" from the base.

**Comment by Roxy-3D** [comment]
@Bob-the-Kuhn 
If it works....  If most of the features do the 'right' thing and behave reasonably...   It might be best to merge it.  Otherwise the conflicts are going to kill you.   

Because, even if some small thing needs work...  That can be cleaned up after the fact as long as it doesn't break the rest of the code.   And the fact that this is all UBL related means there are #ifdef AUTO_BED_LEVELING_UBL around all the code any way.  That limits the scope of what it can hurt.

**Comment by Tannoo** [comment]
@Roxy-3D, would you like me to re-do this from bugfix1.1?

I would like to get it 'up to speed', as I can resolve most conflicts while doing that.

**Comment by Roxy-3D** [comment]
Yes...   It should be merged into the bugfix-v1.1.0 branch.    That is the target.

**Comment by Tannoo** [comment]
Ok... it's going to be a new PR.

**Comment by Tannoo** [comment]
Ok... #6637

**Pull request closed without merging**
