### PR TITLE
Fix Ultimainboard hotend fan

### PR DESCRIPTION
**Pull request by svpcom**
Fix Ultimainboard hotend fan control (fan is on PJ6). Solution with PIN 77 doesn't work.

### CODE REVIEW

**Comment by thinkyhead** [comment]
It should work according to `fastio1280.h`…
```cpp
#define DIO77_PIN   PINJ6
#define DIO77_RPORT PINJ
#define DIO77_WPORT PORTJ
#define DIO77_DDR   DDRJ
#define DIO77_PWM   NULL
```

**Comment by svpcom** [comment]
I've tried it on real hardware now

**Comment by boelle** [comment]
@svpcom what was the result of your test?

**Comment by thinkyhead** [comment]
Great. But this is not an acceptable solution. If pin 77 isn't mapping properly, that is what needs solving.

**Comment by svpcom** [comment]
@boell Fan did't rotate. But all works with direct port access solution

**Comment by boelle** [comment]
@svpcom read what @thinkyhead just wrote

**Comment by thinkyhead** [comment]
The pin mapping appears to be in good working order. To get the full functionality you're attempting, you should revert your changes to `temperature.cpp`, then update your config and comment out these lines:
```cpp
//#define E0_AUTO_FAN_PIN -1
//#define E1_AUTO_FAN_PIN -1
//#define E2_AUTO_FAN_PIN -1
```
…then update the pins file with:
```cpp
#define ORIG_E0_AUTO_FAN_PIN 77
#define ORIG_E1_AUTO_FAN_PIN 77
#define ORIG_E2_AUTO_FAN_PIN 77
```

**Comment by svpcom** [comment]
@thinkyhead I've tried it with ``//#define E0_AUTO_FAN_PIN -1`` commented out in Configuration_adv.h

**Comment by thinkyhead** [comment]
Indeed, I have been following this closely.

**Comment by thinkyhead** [comment]
Trust me on this. Start out by changing `SBI(DDRJ, 6)` to `SET_OUTPUT(77)` and you will see it does the same thing. Then replace `SBI(PORTJ, 6); else CBI(PORTJ, 6);` with `WRITE(77, HIGH); else WRITE(77, LOW);` and you'll see that works too. So, if auto fans aren't coming on for you, then something else is going on.

**Comment by svpcom** [comment]
@thinkyhead It seems that this code doesn't work properly with non-pwm output:
``` .c
    uint8_t fanDone = 0;
    for (uint8_t f = 0; f < COUNT(fanPin); f++) {
      const pin_t pin =
        #ifdef ARDUINO
          pgm_read_byte(&fanPin[f])
        #else
          fanPin[f]
        #endif
      ;
      const uint8_t bit = pgm_read_byte(&fanBit[f]);
      if (pin >= 0 && !TEST(fanDone, bit)) {
        uint8_t newFanSpeed = TEST(fanState, bit) ? EXTRUDER_AUTO_FAN_SPEED : 0;
        #if ENABLED(AUTO_POWER_E_FANS)
          autofan_speed[f] = newFanSpeed;
        #endif
        // this idiom allows both digital and PWM fan outputs (see M42 handling).
        digitalWrite(pin, newFanSpeed);
        analogWrite(pin, newFanSpeed);
        SBI(fanDone, bit);
      }
    }
```

**Comment by thinkyhead** [comment]
Try this:
```diff
        digitalWrite(pin, newFanSpeed);
-       analogWrite(pin, newFanSpeed);
+       if (PWM_PIN(pin)) analogWrite(pin, newFanSpeed);

```

**Comment by thinkyhead** [comment]
See if #13298 allows the fans connected to digital pins to work properly.

**Comment by AnHardt** [comment]
> 
```diff
        digitalWrite(pin, newFanSpeed);
-       analogWrite(pin, newFanSpeed);
+       if (PWM_PIN(pin)) analogWrite(pin, newFanSpeed);
```

It's the `digitalWrite(pin, newFanSpeed);` what can't work with Pin 77.  That's based on the Arduino mapping - not on the FastIOs.

**Comment by thinkyhead** [comment]
Indeed. I misunderstood the issue initially to be some quirk of `analogWrite` messing with the write of the digital pin. (e.g., LOW<=127 and HIGH>=128 or LOW<255 HIGH==255). Anyway, the `PWM_PIN` test can't do any harm… can it?

**Pull request closed without merging**
