### PR TITLE
M105 output formatting,

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Since 2.0.9.2 M105 output changed to
T0:17.54 /0.00 T0:17.54 /0.00 T1:20.70 /0.00 @:0 @0:0 @1:0
Previously it was
T:17.54 /0.00 T0:17.54 /0.00 T1:20.70 /0.00 @:0 @0:0 @1:0
This breaks Pronterface  and cura

The standard:
https://reprap.org/wiki/G-code#M105:_Get_Extruder_Temperature reads to me that starting with T0 is only valid with the short form T0:17.54 /0.00 T1:20.70 /0.00 @:0 @0:0 @1:0, not in the longer form.

Reverted M105 output to correct format.

### Requirements

M105

### Benefits

Works as intended with Pronterface and follows the standard.

### Configurations

Requires EXTRUDERS 2 (or more)

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/23504

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'm not seeing any new change that would make a difference. It has been this way for a very, very long time, even in 2017 … way before 2.0.9.2. Are you now using a multi-extruder system, but using a single extruder in the past? Because this is the logic now…
```cpp
    #if HAS_MULTI_HOTEND
      if (e >= 0) SERIAL_CHAR('0' + e);
    #endif
```
…and this is from 2017…
```cpp
    #if HOTENDS > 1
      if (e >= 0) SERIAL_PROTOCOLCHAR('0' + e);
    #endif
```
Is there no version of Pronterface that correctly interprets the output?

**Comment by thinkyhead** [comment]
From the link you posted to "the standard" …
```
ok T:201 B:117
ok T:201 /202 B:117 /120
ok T:201 /202 B:117 /120 C:49.3 /50
ok T:201 /202 T0:110 /110 T1:23 /0 B:117 /120 C:49.3 /50
ok T0:110 /110 T1:23 /0 B:117 /120            <-------------------------------
ok T:20.2 /0.0 B:19.1 /0.0 T0:20.2 /0.0 @:0 B@:0 P:19.8 A:26.4
```

**Comment by ellensp** [comment]
Please look again

since 2.0.9.2 Starts with T0: previously T: 
But T0 is not valid when using long form. (which marlin uses) 

short form T0,T1 only once
long form Active T, T0, T1

**Comment by ellensp** [comment]
Issue occurred when H_NONE was removed.  in #22279 12 Jul 2021

**Comment by thinkyhead** [comment]
Ah, okay, thanks for pointing that out.

**Pull request merged**
