### PR TITLE
Allow canceled behaviour

### PR DESCRIPTION
**Pull request by alvarotorijano**
Please allow to keep the hotend heating up when any print is canceled to avoid clogging.

### CODE REVIEW

**Comment by FHeilmann** [comment]
Check your host software. 

AFAIK Marlin does not disable the heaters on its own when you cancel (except when you reset the board), but the hosts usually disable the heaters once you press cancel (I know octoprint has a cancel script for this)

**Comment by thinkyhead** [comment]
Please submit all pull requests to the `bugfix-1.1.x` branch.

**Comment by thinkyhead** [comment]
@FHeilmann Turning off heaters on print cancel might be a recent change due to a request. Seems there are some who want it one way for safety, and some who want it the other way, for convenience.

**Comment by alvarotorijano** [comment]
anybody knows hot to change it?

**Comment by FHeilmann** [comment]
please state which host software you are using. 

@thinkyhead is there any "cancel" functionality in Marlin even? I thought most hots simply stop sending G-code commands and then send something along the lines of M400 before disabling steppers heaters and fans using appropriate g-codes (at least thats how octoprint does it). If that is the case, this issue has to be resolved in the host software, not marlin.

**Comment by alvarotorijano** [comment]
OK ok guys all of this os for an autonomous printing, even with the gcodes generated with any host this behaviour change has been noticed when I updated the firmware, with the same gcodes used previously. After searching something in configurations i didnt found what I was looking for. I will try to look for it deeper

**Pull request closed without merging**
