### PR TITLE
[2.0] Add platformio support for stm32

### PR DESCRIPTION
**Pull request by alexxy**
Platformio support for stm32
#8183 
Spi need to be fixed

### CODE REVIEW

**Comment by p3p** [comment]
did you intend to use the extra script section of your flag script file?

**Comment by Spawn32** [comment]
Add platformio support for stm32F7 would be a better title, i need it, anyone that can help ?
Have the original STMF7 hal, might be a god starting point... there will be a dev board from my first batch to somone that think they can fix it

**Comment by alexxy** [comment]
@Spawn32 it possible, i only have few Stm32F1 boards... 
@p3p seems like i dont, it's just a mock up for platformio. Currently HAL dont build due to some SPI issues

Another thing is that timer_t already defined in platformio toolchain

```
Compiling .pioenvs/STM32F1/src/src/HAL/HAL_TEENSY35_36/HAL_Teensy.o
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:49:8: error: 'SPISettings' does not name a type
static SPISettings spiConfig;
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp: In function 'void spiInit(uint8_t)':
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:97:35: error: 'SPI_CLOCK_DIV2' was not declared in this scope
case SPI_FULL_SPEED:    clock = SPI_CLOCK_DIV2 ;  break;
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:98:36: error: 'SPI_CLOCK_DIV4' was not declared in this scope
case SPI_HALF_SPEED:    clock =  SPI_CLOCK_DIV4 ; break;
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:99:36: error: 'SPI_CLOCK_DIV8' was not declared in this scope
case SPI_QUARTER_SPEED: clock =  SPI_CLOCK_DIV8 ; break;
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:100:36: error: 'SPI_CLOCK_DIV16' was not declared in this scope
case SPI_EIGHTH_SPEED:  clock =  SPI_CLOCK_DIV16; break;
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:101:37: error: 'SPI_CLOCK_DIV32' was not declared in this scope
case SPI_SPEED_5:       clock =   SPI_CLOCK_DIV32;  break;
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:102:37: error: 'SPI_CLOCK_DIV64' was not declared in this scope
case SPI_SPEED_6:       clock =   SPI_CLOCK_DIV64;  break;
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:106:3: error: 'spiConfig' was not declared in this scope
spiConfig = SPISettings(clock, MSBFIRST, SPI_MODE0);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:106:44: error: 'SPI_MODE0' was not declared in this scope
spiConfig = SPISettings(clock, MSBFIRST, SPI_MODE0);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:106:53: error: 'SPISettings' was not declared in this scope
spiConfig = SPISettings(clock, MSBFIRST, SPI_MODE0);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:107:3: error: 'SPI' was not declared in this scope
SPI.begin();
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp: In function 'uint8_t spiRec()':
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:118:3: error: 'SPI' was not declared in this scope
SPI.beginTransaction(spiConfig);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:118:24: error: 'spiConfig' was not declared in this scope
SPI.beginTransaction(spiConfig);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp: In function 'void spiRead(uint8_t*, uint16_t)':
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:134:3: error: 'SPI' was not declared in this scope
SPI.beginTransaction(spiConfig);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:134:24: error: 'spiConfig' was not declared in this scope
SPI.beginTransaction(spiConfig);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp: In function 'void spiSend(uint8_t)':
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:147:3: error: 'SPI' was not declared in this scope
SPI.beginTransaction(spiConfig);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:147:24: error: 'spiConfig' was not declared in this scope
SPI.beginTransaction(spiConfig);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp: In function 'void spiSendBlock(uint8_t, const uint8_t*)':
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:161:3: error: 'SPI' was not declared in this scope
SPI.beginTransaction(spiConfig);
^
Marlin/src/HAL/HAL_STM32F1/HAL_spi_Stm32f1.cpp:161:24: error: 'spiConfig' was not declared in this scope
SPI.beginTransaction(spiConfig);

```

**Comment by thinkyhead** [comment]
Do we need to rename our local `timer_t` to `hal_timer_t`?

**Comment by alexxy** [comment]
@thinkyhead I think yes. It will not collide with toolchain one

**Comment by thinkyhead** [comment]
Great! I'll have that patched shortly.

**Comment by Spawn32** [comment]
Will the road to a STM32F7 HAL be shorter with this ? :)

**Comment by thinkyhead** [comment]
image

**Comment by Spawn32** [comment]
@alexxy 
I test compiled for the STM32F1 but ended up with the same spi error's as mention'd her, is there a trick to get past them :)

**Comment by karabas** [comment]
I think the most unexpensive way to start with stm32f745 is to buy 20$ flight controller https://ru.aliexpress.com/item/Matek-Systems-PDB-XT60-With-BEC-5V-12V-2oz-Copper-For-RC-Helicopter-Quadcopter-Muliticopter-Drone/32669227955.html?spm=a2g0v.10010108.1000016.1.6fd2ef6bPZHX7b&isOrigTitle=true

**Pull request merged**
