### PR TITLE
lcd: start print confirm. workaround

### PR DESCRIPTION
**Pull request by tpruvot**
the space character in this menu corrupt the display on various
implementations...

Using a "&nbsp;" (ALT+0160) fixes it...

### CODE REVIEW

**Comment by thinkyhead** [comment]
Could this be related at all to the bug in my word-wrapping implementation in `_wrap_string`?

**Comment by tpruvot** [comment]
```
git show b7eeb5b13b Marlin/src/lcd/ultralcd.cpp
```

**Comment by Bergerac56** [comment]
I tested the workaround. On my side, I can confirm that it works

**Comment by tpruvot** [comment]
Your new commit is still eating the "p" of print.. but no more weird char "corruption"

**Comment by thinkyhead** [comment]
That's what I get for copying it over incomplete. The new patches make it much better.

**Pull request closed without merging**
