### PR TITLE
[2.0.x] Add proper MKS BASE 1.4 board defs

### PR DESCRIPTION
**Pull request by AJMartel**
### Requirements

* MKS BASE 1.4

### Description

I have reverse engineered the schematics for the MKS Base 1.4
The pull request defines all exposed pins and identifies pin capability (PWM, Digital, Analog)

### Benefits

As the MKS Base 1.4 board is not open source and its pinout is poorly documented, this should enable developers/tinkers to fully utilize all available pins for after market Mods. 

### Related Issues

This pull request fulfills multiple forum inquiries reference the MKS Base 1.4 board.
Ignore commits not Labeled "Add MKS Base 1.4" (I did not realize they would be added after the pull request)

### CODE REVIEW

**Comment by AJMartel** [comment]
Sorry for making this difficult, the only 2 files changed are:
pins.h 
`#elif MB(MKS_BASE_14)
  #include "pins_MKS_BASE_14.h"       // ATmega2560                                 env:megaatmega2560 ` 
and boards.h
`#define BOARD_MKS_BASE_14       404   // MKS v1.4 A4982 stepper drivers`
and 1 added file with the pin definitions:
pins_MKS_BASE_14.h 

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/2713077/Marlin.zip)

**Comment by Bob-the-Kuhn** [comment]
Maybe you've already covered this …

The endstop definitions in **pins_RAMPS.h** are mostly different than shown in **pins_MKS_BASE_14.h**.  I believe the following needs to be added to **pins_MKS_BASE_14.h** after the RAMPS include:
```
//
// MKS base has different pin assignments for MOST end stops than in pins_RAMPS.h
//
#undef  X_MIN_PIN
#undef  X_MAX_PIN
#undef  Y_MAX_PIN
#undef  Z_MIN_PIN
#define X_MIN_PIN           3 //  2 on RAMPS
#define X_MAX_PIN           2 // 18 on RAMPS
#define Y_MAX_PIN          15 //  3 on RAMPS
#define Z_MIN_PIN          18 // 15 on RAMPS
```

**Comment by AJMartel** [comment]
Bob-the-Kuhn:
I am not sure which variant of the **pins_RAMPS.h** file you are using, in the current file the limit switch pins are defined as:
`//`
`// Limit Switches`
`//`
`#define X_MIN_PIN           3`
`#ifndef X_MAX_PIN`
 ` #define X_MAX_PIN         2`
`#endif`
`#define Y_MIN_PIN          14`
`#define Y_MAX_PIN          15`
`#define Z_MIN_PIN          18`
`#define Z_MAX_PIN          19`
no need to make any changes to **pins_MKS_BASE_14.h**

**Comment by Bob-the-Kuhn** [comment]
You are correct.

**Pull request closed without merging**
