### PR TITLE
CJ-JD Leftover Code Cleanup

### PR DESCRIPTION
**Pull request by qwewer0**
### Description

Leftover Classic Jerk and Junction Deviation code cleanup.

There might be more, but I wasn't able to find any.

### Benefits

Less junk.

### Modification explanation

**Marlin/src/inc/Conditionals_LCD.h**
There is no need to check for `IS_KINEMATIC`:
https://github.com/qwewer0/Marlin/blob/c3350c1945f46c249b37b0431f25b3e197698625/Marlin/src/inc/SanityCheck.h#L1244-L1249

**Marlin/src/inc/SanityCheck.h**
Use `BOTH()` instead.

**Marlin/src/lcd/menu/menu_advanced.cpp, Marlin/src/module/planner.cpp**
Inside `HAS_CLASSIC_JERK` there is no need to check for `HAS_JUNCTION_DEVIATION`:
https://github.com/qwewer0/Marlin/blob/c3350c1945f46c249b37b0431f25b3e197698625/Marlin/src/inc/Conditionals_LCD.h#L948-L952

Removing HAS_DIST_MM_ARG:
**Marlin/src/module/motion.cpp, Marlin/src/module/planner.cpp, Marlin/src/module/planner.h**
`HAS_JUNCTION_DEVIATION` cannot be enabled with `IS_KINEMATIC`:
https://github.com/qwewer0/Marlin/blob/c3350c1945f46c249b37b0431f25b3e197698625/Marlin/src/inc/SanityCheck.h#L1244-L1249

### CODE REVIEW

**Comment by thinkyhead** [comment]
Even when a kinematic machine (delta) is using Junction Deviation it also has "classic jerk" on the E axis at the same time (unless using linear advance). You'll see that `HAS_CLASSIC_E_JERK` is set when you're on a kinematic system, even if classic jerk is not explicitly enabled.

**Comment by qwewer0** [comment]
> Even when a kinematic machine (delta) is using Junction Deviation it also has "classic jerk" on the E axis at the same time (unless using linear advance). You'll see that `HAS_CLASSIC_E_JERK` is set when you're on a kinematic system, even if classic jerk is not explicitly enabled.

Then the sanitycheck is wrong? Because that doesn't allows `HAS_JUNCTION_DEVIATION` (`CLASSIC_JERK` disabled) and `IS_KINEMATIC` to be enabled at the same time:

> Junction deviation is incompatible with kinematic systems.

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/inc/Conditionals_LCD.h#L952-L954
https://github.com/qwewer0/Marlin/blob/bugfix-2.0.x/Marlin/src/inc/SanityCheck.h#L1184-L1189

**Comment by thinkyhead** [comment]
> Then the sanitycheck is wrong?

Yes, it's possible I was hasty in merging #15032.

**Comment by qwewer0** [comment]
> > Then the sanitycheck is wrong?
> 
> Yes, it's possible I was hasty in merging #15032.

Got it 👍 
I will close this then.

**Pull request closed without merging**
