### PR TITLE
add simple prompt for firmware upload destination

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Proposal:

Adding a simple prompt for uploads that asks the user where they want to put the firmware.

Eg

prompt

Why? because nearly every single new user of a stm32 based controller asks the same things.
"I've built the firmware where is it?" Often followed with "I can't find .pio where is it?" because their OS is hiding it.
Followed by, "Why doesn't upload work?"  default upload method being set to stlink when they don't have one.

Currently only on env: STM32F103RE_creality and STM32F103RC_creality. But I would recommend for all env's that default to stlink or jlink where it will upload from sdcard.
  

I've tested this on Linux and on Windows, but needs tested on a Mac 
 
Can probably be cleaned up as my python is weak. 

### Requirements

STM32F103RE_creality or STM32F103RC_creality
Click on upload, and try the directory selector.

### Benefits

Easier for new users

### Configurations

Tested on stock E3V2 Configs

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/24070

### CODE REVIEW

**Comment by ellensp** [comment]
CI Error is not related to this PR

**Comment by thisiskeithb** [comment]
You can also [specify a new default folder for output](https://docs.platformio.org/en/latest/projectconf/section_platformio.html#workspace-dir) in PIO like `/firmware`, but this seems more useful.

Edit: Specifying a `workspace-dir` may still be useful for us since the folder is not hidden by default:
image

**Comment by thisiskeithb** [comment]
Testing the default Ender-3 V2 config with MarlinUI on an Intel Mac running Monterey 12.3.1, I get the following error when trying to use upload:

<details><summary>Expand me!</summary>
<p>

```prolog
[snip]
Indexing .pio/build/STM32F103RE_creality/lib719/libWire.a
Linking .pio/build/STM32F103RE_creality/firmware-20220423-081045.elf
Checking size .pio/build/STM32F103RE_creality/firmware-20220423-081045.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  12.8% (used 8364 bytes from 65536 bytes)
Flash: [===       ]  28.8% (used 150796 bytes from 524288 bytes)
Building .pio/build/STM32F103RE_creality/firmware-20220423-081045.bin
before_upload(["upload"], [".pio/build/STM32F103RE_creality/firmware-20220423-081045.bin"])
2022-04-23 08:11:25.392 Python[19638:566847] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff80d6707fb __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff80d3d1e58 objc_exception_throw + 48
        2   CoreFoundation                      0x00007ff80d699226 -[NSException raise] + 9
        3   AppKit                              0x00007ff80ff79634 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
        4   AppKit                              0x00007ff80ff655e4 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1288
        5   AppKit                              0x00007ff80ff650d6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        6   Tk                                  0x00007ffa2c9b3d9d TkMacOSXMakeRealWindowExist + 610
        7   Tk                                  0x00007ffa2c9b4a21 TkMacOSXUnregisterMacWindow + 795
        8   Tcl                                 0x00007ffa2c83eb44 Tcl_ListMathFuncs + 1765
        9   Tcl                                 0x00007ffa2c83f3b9 Tcl_EvalObjv + 57
        10  _tkinter.cpython-38-darwin.so       0x000000010f3c5860 Tkapp_Call + 480
        11  Python3                             0x000000010e518bb0 method_vectorcall_VARARGS + 272
        12  Python3                             0x000000010e5f454f call_function + 335
        13  Python3                             0x000000010e5f1215 _PyEval_EvalFrameDefault + 28085
        14  Python3                             0x000000010e5f54cf _PyEval_EvalCodeWithName + 3007
        15  Python3                             0x000000010e5101ab _PyFunction_Vectorcall + 235
        16  Python3                             0x000000010e51299c method_vectorcall + 172
        17  Python3                             0x000000010e5f454f call_function + 335
        18  Python3                             0x000000010e5f1239 _PyEval_EvalFrameDefault + 28121
        19  Python3                             0x000000010e5f54cf _PyEval_EvalCodeWithName + 3007
        20  Python3                             0x000000010e5101ab _PyFunction_Vectorcall + 235
        21  Python3                             0x000000010e5f454f call_function + 335
        22  Python3                             0x000000010e5f1389 _PyEval_EvalFrameDefault + 28457
        23  Python3                             0x000000010e5f54cf _PyEval_EvalCodeWithName + 3007
        24  Python3                             0x000000010e5101ab _PyFunction_Vectorcall + 235
        25  Python3                             0x000000010e51299c method_vectorcall + 172
        26  Python3                             0x000000010e5f454f call_function + 335
        27  Python3                             0x000000010e5f1389 _PyEval_EvalFrameDefault + 28457
        28  Python3                             0x000000010e5f54cf _PyEval_EvalCodeWithName + 3007
        29  Python3                             0x000000010e5101ab _PyFunction_Vectorcall + 235
        30  Python3                             0x000000010e50f4e4 _PyObject_FastCallDict + 132
        31  Python3                             0x000000010e510bb3 _PyObject_Call_Prepend + 131
        32  Python3                             0x000000010e56a92a slot_tp_call + 170
        33  Python3                             0x000000010e50fb6c PyObject_Call + 172
        34  Python3                             0x000000010e5f1543 _PyEval_EvalFrameDefault + 28899
        35  Python3                             0x000000010e51003b function_code_fastcall + 171
        36  Python3                             0x000000010e5f454f call_function + 335
        37  Python3                             0x000000010e5f12da _PyEval_EvalFrameDefault + 28282
        38  Python3                             0x000000010e5f54cf _PyEval_EvalCodeWithName + 3007
        39  Python3                             0x000000010e5101ab _PyFunction_Vectorcall + 235
        40  Python3                             0x000000010e50f4e4 _PyObject_FastCallDict + 132
        41  Python3                             0x000000010e510bb3 _PyObject_Call_Prepend + 131
        42  Python3                             0x000000010e56a92a slot_tp_call + 170
        43  Python3                             0x000000010e50fb6c PyObject_Call + 172
        44  Python3                             0x000000010e5f1543 _PyEval_EvalFrameDefault + 28899
        45  Python3                             0x000000010e5f54cf _PyEval_EvalCodeWithName + 3007
        46  Python3                             0x000000010e5101ab _PyFunction_Vectorcall + 235
        47  Python3                             0x000000010e51299c method_vectorcall + 172
        48  Python3                             0x000000010e5f454f call_function + 335
        49  Python3                             0x000000010e5f1239 _PyEval_EvalFrameDefault + 28121
        50  Python3                             0x000000010e51003b function_code_fastcall + 171
        51  Python3                             0x000000010e5f454f call_function + 335
        52  Python3                             0x000000010e5f1239 _PyEval_EvalFrameDefault + 28121
        53  Python3                             0x000000010e51003b function_code_fastcall + 171
        54  Python3                             0x000000010e5f454f call_function + 335
        55  Python3                             0x000000010e5f1215 _PyEval_EvalFrameDefault + 28085
        56  Python3                             0x000000010e51003b function_code_fastcall + 171
        57  Python3                             0x000000010e5f454f call_function + 335
        58  Python3                             0x000000010e5f1215 _PyEval_EvalFrameDefault + 28085
        59  Python3                             0x000000010e51003b function_code_fastcall + 171
        60  Python3                             0x000000010e5f454f call_function + 335
        61  Python3                             0x000000010e5f1215 _PyEval_EvalFrameDefault + 28085
        62  Python3                             0x000000010e51003b function_code_fastcall + 171
        63  Python3                             0x000000010e512a33 method_vectorcall + 323
        64  Python3                             0x000000010e50fa24 PyVectorcall_Call + 100
        65  Python3                             0x000000010e696ecb t_bootstrap + 75
        66  Python3                             0x000000010e6476d9 pythread_wrapper + 25
        67  libsystem_pthread.dylib             0x00007ff80d52f4e1 _pthread_start + 125
        68  libsystem_pthread.dylib             0x00007ff80d52af6b thread_start + 15
)
libc++abi: terminating with uncaught exception of type NSException
============================================== [FAILED] Took 40.93 seconds ==============================================

Environment           Status    Duration
--------------------  --------  ------------
STM32F103RE_creality  FAILED    00:00:40.927
========================================= 1 failed, 0 succeeded in 00:00:40.927 =========================================
The terminal process "platformio 'run', '--target', 'upload'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

</p>
</details>

edit: For anyone without a Mac wanting to help, here's a Github action to test your build using a macOS environment: [test-build-mac.yml.zip](https://github.com/MarlinFirmware/Marlin/files/8547560/test-build-mac.yml.zip)

**Comment by ellensp** [comment]
I have no idea why macs have to be so contrary.
Its python, it should be mostly os independent.
No idea where to even start....

**Comment by thinkyhead** [comment]
Clicking on the line "📁**Built "firmware.hex" at 5:33:57 PM …**" reveals and selects the file in the Explorer / Finder.

image

**Comment by thinkyhead** [comment]
Note: I don't seem to have Tkinter installed in my Python env, which is `$HOME/.platformio/penv/bin/python` (3.10.4) so I get the error…
```
ModuleNotFoundError: No module named '_tkinter':
```

**Comment by CAP1Sup** [comment]
Could you also enable this feature for the other STM32 processors? It would be very convenient, especially for new users.

**Comment by ellensp** [comment]
@CAP1Sup 

"Currently only on env: STM32F103RE_creality and STM32F103RC_creality. But I would recommend for all env's that default to stlink or jlink where it will upload from sdcard."

Ie that is the idea

**Comment by CAP1Sup** [comment]
Why not have the feature enabled for all STM32 boards now? Is there something different with the other boards? Just curious

**Comment by ellensp** [comment]
It doesn't work for everyone yet, its brand new still in testing phase. Be patient

**Comment by CAP1Sup** [comment]
Ran into an error with Python 3... the fileDialog isn't correctly defined when using Python 3. Changing the else (on line 14) statement from:
```		
import tkinter as tk
from tkinter import Tk
```
to 
```		
import tkinter as tk
from tkinter import Tk
from tkinter import filedialog as fileDialog
```

fixes the issue. Had no issues otherwise!

Sorry for pushing, I got a little too excited. Best of luck!

**Comment by ellensp** [comment]
This still does not work on macOS

```
2022-05-22 20:34:58.745 Python[4493:86911] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff80be977fb __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff80bbf8e58 objc_exception_throw + 48
        2   CoreFoundation                      0x00007ff80bec0226 -[NSException raise] + 9
        3   AppKit                              0x00007ff80e7a0634 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
        4   AppKit                              0x00007ff80e78c5e4 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1288
        5   AppKit                              0x00007ff80e78c0d6 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
        6   Tk                                  0x00007ffa2b1dad9d TkMacOSXMakeRealWindowExist + 610
        7   Tk                                  0x00007ffa2b1dba21 TkMacOSXUnregisterMacWindow + 795
        8   Tcl                                 0x00007ffa2b065b44 Tcl_ListMathFuncs + 1765
        9   Tcl                                 0x00007ffa2b0663b9 Tcl_EvalObjv + 57
        10  _tkinter.cpython-38-darwin.so       0x0000000104c16860 Tkapp_Call + 480
        11  Python3                             0x0000000103d69bb0 method_vectorcall_VARARGS + 272
        12  Python3                             0x0000000103e4554f call_function + 335
        13  Python3                             0x0000000103e42215 _PyEval_EvalFrameDefault + 28085
        14  Python3                             0x0000000103e464cf _PyEval_EvalCodeWithName + 3007
        15  Python3                             0x0000000103d611ab _PyFunction_Vectorcall + 235
        16  Python3                             0x0000000103d6399c method_vectorcall + 172
        17  Python3                             0x0000000103e4554f call_function + 335
        18  Python3                             0x0000000103e42239 _PyEval_EvalFrameDefault + 28121
        19  Python3                             0x0000000103e464cf _PyEval_EvalCodeWithName + 3007
        20  Python3                             0x0000000103d611ab _PyFunction_Vectorcall + 235
        21  Python3                             0x0000000103e4554f call_function + 335
        22  Python3                             0x0000000103e42389 _PyEval_EvalFrameDefault + 28457
        23  Python3                             0x0000000103e464cf _PyEval_EvalCodeWithName + 3007
        24  Python3                             0x0000000103d611ab _PyFunction_Vectorcall + 235
        25  Python3                             0x0000000103d6399c method_vectorcall + 172
        26  Python3                             0x0000000103e4554f call_function + 335
        27  Python3                             0x0000000103e42389 _PyEval_EvalFrameDefault + 28457
        28  Python3                             0x0000000103e464cf _PyEval_EvalCodeWithName + 3007
        29  Python3                             0x0000000103d611ab _PyFunction_Vectorcall + 235
        30  Python3                             0x0000000103d604e4 _PyObject_FastCallDict + 132
        31  Python3                             0x0000000103d61bb3 _PyObject_Call_Prepend + 131
        32  Python3                             0x0000000103dbb92a slot_tp_call + 170
        33  Python3                             0x0000000103d60b6c PyObject_Call + 172
        34  Python3                             0x0000000103e42543 _PyEval_EvalFrameDefault + 28899
        35  Python3                             0x0000000103d6103b function_code_fastcall + 171
        36  Python3                             0x0000000103e4554f call_function + 335
        37  Python3                             0x0000000103e422da _PyEval_EvalFrameDefault + 28282
        38  Python3                             0x0000000103e464cf _PyEval_EvalCodeWithName + 3007
        39  Python3                             0x0000000103d611ab _PyFunction_Vectorcall + 235
        40  Python3                             0x0000000103d604e4 _PyObject_FastCallDict + 132
        41  Python3                             0x0000000103d61bb3 _PyObject_Call_Prepend + 131
        42  Python3                             0x0000000103dbb92a slot_tp_call + 170
        43  Python3                             0x0000000103d60b6c PyObject_Call + 172
        44  Python3                             0x0000000103e42543 _PyEval_EvalFrameDefault + 28899
        45  Python3                             0x0000000103e464cf _PyEval_EvalCodeWithName + 3007
        46  Python3                             0x0000000103d611ab _PyFunction_Vectorcall + 235
        47  Python3                             0x0000000103d6399c method_vectorcall + 172
        48  Python3                             0x0000000103e4554f call_function + 335
        49  Python3                             0x0000000103e42239 _PyEval_EvalFrameDefault + 28121
        50  Python3                             0x0000000103d6103b function_code_fastcall + 171
        51  Python3                             0x0000000103e4554f call_function + 335
        52  Python3                             0x0000000103e42239 _PyEval_EvalFrameDefault + 28121
        53  Python3                             0x0000000103d6103b function_code_fastcall + 171
        54  Python3                             0x0000000103e4554f call_function + 335
        55  Python3                             0x0000000103e42215 _PyEval_EvalFrameDefault + 28085
        56  Python3                             0x0000000103d6103b function_code_fastcall + 171
        57  Python3                             0x0000000103e4554f call_function + 335
        58  Python3                             0x0000000103e42215 _PyEval_EvalFrameDefault + 28085
        59  Python3                             0x0000000103d6103b function_code_fastcall + 171
        60  Python3                             0x0000000103e4554f call_function + 335
        61  Python3                             0x0000000103e42215 _PyEval_EvalFrameDefault + 28085
        62  Python3                             0x0000000103d6103b function_code_fastcall + 171
        63  Python3                             0x0000000103d63a33 method_vectorcall + 323
        64  Python3                             0x0000000103d60a24 PyVectorcall_Call + 100
        65  Python3                             0x0000000103ee7ecb t_bootstrap + 75
        66  Python3                             0x0000000103e986d9 pythread_wrapper + 25
        67  libsystem_pthread.dylib             0x00007ff80bd564e1 _pthread_start + 125
        68  libsystem_pthread.dylib             0x00007ff80bd51f6b thread_start + 15
)
libc++abi: terminating with uncaught exception of type NSException
```

**Pull request merged**
