### PR TITLE
Bug in G34_M422.cpp

### PR DESCRIPTION
**Pull request by ghost**
This PR concerns G34 and is a request for some brainstorming.

After testing G34 numerous times to improve BLTouch handling, I came across some problems that had nothing to do with the type of probe.

You can try this yourself only if you have setup DUAL-Z-STEPPERS, of course.

Experiment no. 1: Home ONLY X and Y, not Z. Then G1 Z100. Then G34. Result: Probing failed.

Experiment no. 2: Home X, Y AND Z. Then "un-align" the Z steppers by a rather large amount, like 10mm on one side higher than the other. You can do a G1 Z100 (not important in this scenario). Then G34. Result after the first or second align sequence: Probing failed.

Small deviations are handled admirably, so it is not something totally urgent.

The reason for this behaviour is explained here:

```
        // Probing fails in two cases especially:
        // 1. Z axis is unhomed: z_probe_low_point (probe.cpp:578) is thus -10
        //    If the current Z position is more than 10mm+probe_clearance above the bed, probing will fail
        // 2. If Z axis is homed, it is even worse: z_probe_low_point (probe.cpp:578) is the result
        //    of Z_PROBE_LOW_POINT - Z_PROBE_OFFSET_FROM_EXTRUDER. For example: 0.4
        //
        // In both cases, if the tilt of the bed exceeds this value + probe_clearance ( -10 unhomed, 0.4 homed )
        // there will be a probe failure on the first (tilted downwards to the right) or second (tilted downwards to 
        // the left).
        //
        // This means that the G34 mechanism, which is inherently sound, needs to REQUIRE a Z home in addition to 
        // an XY home, AND THEN to inform probe_pt() that a MUCH lower z_probe_low_point is desired. 
```

How would anyone of you approach this most elegantly?

* Approach the bed cautiously in an endless fashion like in homing?
* Just increase the -10 to, say -100? And force the axis to be unhomed prior to probing? I mean, there is a certain limit to the amount of unalignedness that is physically possible (unless the printer is 2m wide?)
* Ignore, because no one has complained yet?

### CODE REVIEW

**Comment by thinkyhead** [comment]
@TheLongAndOnly may be able to answer some questions.

**Comment by GMagician** [comment]
G34 will not work when Z is far from bed (probing point not really bed) since logic use probing function. This "move" limit while probing was a security action. When I noticed this I thought it was an intent, not a bug.
my 2 cents:
if z homed: 
 a) it can move near probing point and then execute a probe
 **b) execute a "home like" probing**
if not z homed: 
 a) prevent action
 **b) execute a "home like" probing**

**Comment by ghost** [comment]
Thanks for your input. 
I am b)ewitched.
If the bed is upward inclined badly enough the probe will actually scrape the bed when going in that direction. So to be safe a user defined safety height should be climbed before doing the lateral travel. Which also means coming down from quite a big height **carefully**. Why user definable? Well, the printer might be quite big so the possible deviations might be a lot greater than the normal probe vertical freedom. 
So I also favor the Home-like behavior. =b. 

Also I would favor a force home xyz just like it is done for G29

**Comment by GMagician** [comment]
A home will not save you. You will still have a bad included Z before and after home.
With a badly inclined Z my printer I think will refuse to move correctly as well I think but if this may be a problem, just increse raise between probes and that will should solve it

**Comment by ghost** [comment]
Another idea was to not go to the next point immediately (in case the bed goes downhill or uphill too fast) but to iteratively move outward from the home point step by step, correcting as you go. That way the probing logic can remain as it is.

**Comment by ghost** [comment]
Currently to successfully use G34 you must:
1. Use your eyes to manually align all z-steppers as well as possible = small deviation < 5mm or so
2. Then move nozzle down to about max. 10 mm above bed. 
3. Then G34 ok

If 1 or 2 is not done, it's not sure to work. Homing Z makes it worse.

**Comment by GMagician** [comment]
Sure step by step will save you but how much time does it take? ok that if second step confirm a "not too inclined" Z you may skip and go directly to next point, but which printer may move if Z is too much inclined?
In prusa like printers when Z is too much misaligned there is a mechanical clog

**Comment by GMagician** [comment]
@FanDjango points 1 and 2 are tied together. When probing Z should lowers max to:
```c++
const float z_probe_low_point = TEST(axis_known_position, Z_AXIS) ? -zprobe_zoffset + Z_PROBE_LOW_POINT : -10.0;
```

**Comment by ghost** [comment]
Yup, those are the limiting factors I also have identified.

You know what I do on my printer? 

I home then drive up quickly to z-max - 5, then up slooowly to z-max + 5 into the physical stop (bang bang bang) then a home, then G34. 

Works every time.

**Comment by GMagician** [comment]
> I home then drive up quickly to z-max - 5, then up slooowly to z-max + 5 into the physical stop (bang bang bang) then a home, then G34.

it sounds like Prusa Z alignment 

But this should be done with reduced current on stepper otherwise you stress mechanical parts (or break if motors torque is high)

**Comment by TheLongAndOnly** [comment]
Initial intention of G34 was not to fix a totally broken alignment, but fine tune it. I'm using it for my SparkCubeXL with 3 z-steppers. As recommended by @FanDjango, I adjust it manually by hand to even, then run G28 and then G34. My setup stops when an accuracy of 0,02mm is achieved. Badly misaligned spindles put high forces to the steppers.

**Comment by thinkyhead** [comment]
I'd recommend adding the required homing and raise moves so that this is reliable. But if the manual alignment is pretty much always a requirement, then maybe it needs to work as a step-by-step wizard using the LCD and the host prompt features.

**Comment by ghost** [comment]
Ok - the alignement procedure itself works really good. All we need, is two things: to rise up HIGHER before the first and then between probes and ALLOW PROBING DOWN FURTHER.

**RISING UP HIGHER**
This one is an easy change. Since the amount of rise needed depends on the left-right size of the bed, we could assume a max value calculated from the probe points distance to each other and assume a max deviation (incline) of say 5° = about 10%. No need for a parm in config

**ALLOW PROBING DOWN FURTHER**
Best way of implementing that: Add a parameter to the routines in ```probe.cpp``` telling them: "Need to go down further by this value" and then use a value similarly derived as for the rise.

**Comment by ghost** [comment]
Testing some very promising small changes right now. Will publish here soon.

**Comment by ghost** [comment]
Here is a revamped G34, using the best of the previous code by the @TheLongAndOnly.

All of this is for discussion and I appreciate anybody testing this on a 3-stepper system.

1. G34 now unconditionally performs a G28 home for XYZ at the beginning, This then gives the to-be aligned incline a starting point at least, so that a near-endless probe is avoided.
2. Arbitrarily, a maximum incline of 5% (about 10°) is defined, which leads to a maximum z-raise needed to clear the probe from the bed, by taking the distance between the probe points and applying pythagoras. This z-raise is used for the first probe-iteration, in which the real misalignement is not yet 
known.
3. After the first iteration, z-raise is reduced to reflect the actual misalignement, keeping the probe nice and low on its travels - but just above the highest point of the expected misaligned bed.
4. The probe operation itself is given (by way of a new parameter for probe_pt() ) an indication of how much further than normally the probe should be taken downwards *1)
5. The second iteration uses the alignement gain of the first iteration to calculate an optimum amplification (this reflects the geometry of the nozzle carrying axis - the overall length, the distance of the probe points from the steppers) and applies this ampification for ONE correction sequence only. This second optimum iteration brings the alignement close enough in one giant leap to reduce the number of needed further iterations. These once again use the users configured amplification (just like the first iteration). A maximum of 5-6 iterations has been observed even when the mis-alignement was close to the physical maximum allowed by the printer mechanism.

*1) The probe depth indication is at this moment still rudimentary and static - the plan is to do some more analysis to see if this can be made more variable. For now, a value has been chosen that is certain to be large enough.

**Comment by ghost** [comment]
The first version left a few things to be desired - especially the need to modify `probe.cpp` and `probe.h`, a big drawback in my opinion.

_A simple coordinate translation shifts space downward in Z-direction, thereby moving all positions on a bed, that is misaligned by less than the stipulated maximum, reliably into the positive realm._

All subsequent probe operations can then expect to be executed with the bed being encountered before the Z-zero level is passed. The original unchanged probe logic works fine in this context - it handles "early" bed encounters very gracefully, as opposed to "late" encounters miles below zero (in fact it aborts for safety's sake, as we have seen previously).

The other highlights of the first version are still there:

1. G34 now unconditionally performs a G28 home for XYZ at the beginning, This then gives the to-be-aligned incline a starting point at least, so that a near-endless probe is avoided.
2. Arbitrarily, a maximum incline of 5% (about 10°) is defined, which leads to a maximum z-raise needed to clear the probe from the bed, by taking the distance between the probe points and applying pythagoras. This z-raise is used for the first probe-iteration, in which the real misalignement is not yet known. 
3. After the first iteration, z-raise is recalculated to reflect the actual misalignement, keeping the probe nice and low on its travels - but just above the highest point of the expected misaligned bed.
4. The second iteration uses the alignement gain of the first iteration to calculate an optimum amplification (this reflects the geometry of the nozzle carrying axis - the overall length, the distance of the probe points from the steppers) and applies this ampification for ONE correction sequence only. This second optimum iteration brings the alignement close enough in one giant leap to reduce the number of needed further iterations. These once again use the users configured amplification (just like the first iteration). A maximum of 4-6 iterations has been observed even when the mis-alignement was close to the physical maximum allowed by the printer mechanism.

grafik

**Comment by ghost** [comment]
@thinkyhead Do we want G34 in the LCD menus somewhere?

**Comment by thinkyhead** [comment]
I guess it belongs in the menu next to the other calibration options. They are congregating mostly in the Motion sub-menu. But maybe we will make a top-level Calibrate sub-menu to group bed leveling, homing, and things like that.

**Comment by ghost** [comment]
> Do fewer SQRT for Z_TRIPLE_STEPPER_DRIVERS

Nice!

**Comment by GMagician** [comment]
Why did you close it?

**Comment by gloomyandy** [comment]
It would be a pity to lose these changes.

**Pull request closed without merging**
