### PR TITLE
swap Z_MIN and Z_MAX pins pins_TRIGORILLA_PRO.h

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Fixes Issue #21090

### Requirements

BOARD_TRIGORILLA_PRO

### Benefits

Works as expected

### Related Issues

Issue #21090

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Is this correct for *all* printers that use this board? It seems this isn’t this isn’t the first time that someone claimed the trigorolla pins were wrong, but it was just Anycubic adding another variant/daughterboard.

**Comment by ellensp** [comment]
This is for the bare board on it own. no daughterboard. It seems legit.

**Comment by ellensp** [comment]
From https://www.thingiverse.com/thing:4271636  (someone else documenting this board) 
```
FILAMENT1 = PA15
Z- = PA14
Z+ = PA13 (autolevel removable switch un predator)
Y- = PA12
X- = PG10
```

**Comment by rq3** [comment]
I have just spent the past week installing a piezo sensor on my Trigorilla Pro driven Anycubic Predator. My printer is roughly 2 years old, and is currently running Marlin 2.0.7.2. I had no problems with the Z- and Z+ pin definitions, so apparently there are different versions of the Trigorilla Pro.

**Comment by ellensp** [comment]
@rq3 do you have any draughtboards in the system?

**Comment by thinkyhead** [comment]
There are a few configurations in the Configurations repo that refer to this board. If some of them need to have their Z endstops changed so that they aren't affected by this change, then it would be good to get those in now as well.

**Comment by ellensp** [comment]
Configurations$ grep -r BOARD_TRIGORILLA_PRO *
config/examples/delta/Anycubic/Predator/Configuration.h:  #define MOTHERBOARD BOARD_TRIGORILLA_PRO

Only the one that I can see

**Comment by thinkyhead** [comment]
Thanks. When I said "a few" I didn't care if that was exactly right.

I'll try flashing bugfix onto the AnyCubic Chiron and see whether it works or not. If it works as it is without changes, then this can be closed.

**Comment by ellensp** [comment]
I suspect that the issue is that the `pins_TRIGORILLA_PRO.h` file was written for the Anycubic/Predator and not actually for the bare controller.

You may recall it originally had  `X_MAX_PIN` and `Y_MAX_PIN` see https://github.com/MarlinFirmware/Marlin/pull/20801
Changed to `X_STOP` and `Y_STOP` as it should be for a non-specific printer.

**Comment by ellensp** [comment]
So I suggest we wrap the correct board #define z-min and z-max in pins_TRIGORILLA_PRO.h in a  #ifndef  block and add #define Z_MAX_PIN  PA14 and #define Z_MIN_PIN  PA13 to the Anycubic Predator Configuration example file.

**Comment by thinkyhead** [comment]
Just checking the machine with the original firmware as shipped (by "Jolly" and Compiled: Oct 25 2018). The Z_MIN endstop is on the right and Z2_MIN is on the left. Meanwhile, our Chiron configurations have `Z2_USE_ENDSTOP` set to `_XMAX_`.

**Comment by ellensp** [comment]
endstops
I wonder if endstop on the left vs enstops on the right are incorrectly labled?
Can you check if z+ endstop on left 3 pin is connected to z+ on the 8 in

**Comment by thinkyhead** [comment]
Ah… The switching of those pins might have been from me because I swapped in a new board at one point. I'll take a chance and do a Z homing to see whether it stops the correct Z motors when the stops are triggered. The Z endstops are connected to the D42 / D43 headers near EXP1. At the moment my left Z endstop is connected to D42.

**Comment by thinkyhead** [comment]
image

**Comment by ellensp** [comment]
are you using a pro? the pro is stm32f1, ie doesnt use D##

**Comment by thinkyhead** [comment]
Nope. This Chiron did not come with a Pro board.

**Comment by ellensp** [comment]
well this is all about the pro...

**Comment by thinkyhead** [comment]
Added `#ifndef` so, if needed, configs can handle swapped connections.

**Comment by thinkyhead** [comment]
@rq3 — After this change, next time you flash Marlin onto your Predator you might have to add your own pin defines to `Configuration.h`. We'll continue to monitor the situation to see whether swapped Z endstop connections are common.

**Comment by arizonahanson** [comment]
@thinkyhead @ellensp I have a stock Predator, and at least for my board, the correct pinout is Zmax=PA14, Zmin=PA13 (as it was before).  My level sensor is connected to Zmax and one of the 3 stops is connected to Zmin (according to the labels).  I have swapped it back in my Configuration.h since this change - just reporting the info

**Comment by thinkyhead** [comment]
Thanks! 09de17fb59

**Pull request merged**
