### PR TITLE
Fix iss#1492

### PR DESCRIPTION
**Pull request by AnHardt**
Introduced lcd_strlen() and lcd_strlen_P() - for unicode.
Replaced the old functions where necessary.
Reworked language_ru.h.

Speeded up test for zero length string in cardreader.cpp

### CODE REVIEW

**Comment by AnHardt** [comment]
@noprod is satisfied - for now.
My testing with REPRAP_DISCOUNT_SMART_CONTROLLER with  DISPLAY_CHARSET_HD44780_JAPAN and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER showed no faults with languages ru, de and en.
Needs further testing because potentially all displays and all languages are affected.

**Comment by thinkyhead** [comment]
Very clean, and a welcome update. I think this can be readily merged. But we can wait for more testing.

**Comment by AnHardt** [comment]
@thinkyhead 
Please don't mere jet.

**Comment by AnHardt** [comment]
Preparing a test for @nprod where i kicked out LiquidCrystalRus.cpp and LiquidCrystalRus.h.

**Comment by AnHardt** [comment]
Test of
https://github.com/AnHardt/Marlin/tree/rus-remove-extrafiles
is pending.

**Pull request merged**
