### PR TITLE
New filament diameter identifiers

### PR DESCRIPTION
**Pull request by clefranc**
See issue https://github.com/MarlinFirmware/Marlin/issues/1411

### CODE REVIEW

**Comment by AnHardt** [comment]
Are there extruder-hotend combos out there what can work with 1.75 and 3.0 mm filament?
Could it make sense to increase the adjustable range to , lets say, 1 to 4 mm?

**Comment by clefranc** [comment]
@AnHardt
I'm not aware of any universal extruder.

Right now, the LCD is programmed to swing +/- 0.500mm around the defined diameter, and this make no sense, the values get totally screwed up using the LCD and M200 command. It also make no sense to be able to change the filament diameter to any value, then be stuck by +/- .5 in the menu.

I'm going to revoke my pull request to do more tests and resubmit a full LCD filament diameter range from 1.250 to 3.500mm. If you got a filament larger or thinner than this, then change your supplier.

**Comment by AnHardt** [comment]
Or you could misuse MEASURED_UPPER_LIMIT and MEASURED_LOWER_LIMIT defined in Configuration.h in the FILAMENT_SENSOR section to set the limits manualy.
Maybe renaming to FILAMENT_DIAMETER_UPPER_LIMIT ... is adequat.

**Comment by clefranc** [comment]
@AnHardt 
I'm going to resubmit something like this:

// This defines the number of extruders
#define EXTRUDERS 2
// Default filament diameters used for volumetric extrusion,
// also used for the default nominal filament diameter of the filament sensor
#define EXTRUDER_FILAMENT_DIAMETER {3.0, 3.0}
// Maximum and minimum value used to set filament diameters using the LCD and M200 command
#define EXTRUDER_FILAMENT_DIAMETER_MIN {1.25, 1.25}
#define EXTRUDER_FILAMENT_DIAMETER_MAX {3.5, 3.5}

and remove these sensor identifiers:

DEFAULT_NOMINAL_FILAMENT_DIA
MEASURED_UPPER_LIMIT
MEASURED_LOWER_LIMIT

but I'm waiting that Scott finishes its codes for the EEPROM.

**Comment by AnHardt** [comment]
Perfect!

**Comment by thinkyhead** [comment]
@clefranc Thanks for holding off. #1428 is almost ready to merge. After that, you'll be good to go!

**Pull request closed without merging**
