### PR TITLE
Fix mks ts35 on btt skr 1.3 and  1.4

### PR DESCRIPTION
**Pull request by ellensp**
### Description

For some time MKS TS35 V2.0 has not worked on BTT SKR 1.3 or BTT SKR 1.4 (and turbo)

 BTT SKR 1.3 would compile but result in a white screen
 BTT SKR 1.4 would not even compile

This fixes these issues.

### Requirements

MKS TS35 V2.0 with either a BTT SKR 1.3 or a BTT SKR 1.4

TFT_COLOR_UI or TFT_CLASSIC_UI  with or without TOUCH_SCREEN

### Benefits

TFT works

### Related Issues
https://github.com/MarlinFirmware/Marlin/pull/24980
https://github.com/MarlinFirmware/Marlin/pull/26052

### Current Status

```
Skr v1.3 
-----------------------------------------------------------------
|  (with)        |TFT_CLASSIC_UI | TFT_COLOR_UI |  TFT_LVGL_UI  |
-----------------------------------------------------------------
|TOUCH_SCREEN    |   Works       |    Works     | Not Supported*|
-----------------------------------------------------------------
|no TOUCH_SCREEN |   Works       |    Works     | Not Supported*|
-----------------------------------------------------------------

Skr v1.4 
-----------------------------------------------------------------
|  (with)        |TFT_CLASSIC_UI | TFT_COLOR_UI |  TFT_LVGL_UI  |
-----------------------------------------------------------------
|TOUCH_SCREEN    |    Works      |     Works    | Not Supported*|
-----------------------------------------------------------------
|no TOUCH_SCREEN |   Works       |     Works    | Not Supported*|
-----------------------------------------------------------------

Skr v1.4 Turbo
-----------------------------------------------------------------
|  (with)        |TFT_CLASSIC_UI | TFT_COLOR_UI |  TFT_LVGL_UI  |
-----------------------------------------------------------------
|TOUCH_SCREEN    |   Works       |    Works     | Not Supported*|
-----------------------------------------------------------------
|no TOUCH_SCREEN |   Works       |    Works     | Not Supported*|
-----------------------------------------------------------------

* Needs SERIAL_RUNTIME_HOOK but SERIAL_RUNTIME_HOOK is not yet supported for LPC176x.  
```

### CODE REVIEW

**Comment by ellensp** [comment]
anyone got any ideas why having TOUCH_SCREEN disabled on TFT_CLASSIC_UI results in a white screen?

**Comment by thisiskeithb** [comment]
> anyone got any ideas why having TOUCH_SCREEN disabled on TFT_CLASSIC_UI results in a white screen?

The resident SPI TFT expert @jmz52 may know.

**Comment by thinkyhead** [comment]
> anyone got any ideas why having TOUCH_SCREEN disabled on TFT_CLASSIC_UI results in a white screen?

@ellensp — Has it always been this way, or is there a past point in time where it worked? If it once worked then the breaking commit should give some clue as to what changed.

**Comment by jmz52** [comment]
> anyone got any ideas why having TOUCH_SCREEN disabled on TFT_CLASSIC_UI results in a white screen?

Works just fine on my SKR 1.3 with 60cm long cables. Powered from USB.
I am using your code from `fix-mks-ts35-on-btt-skr-1.3-and--1.4` branch with `LPC1768` build environment and 6 changed lines in Configuration.h
```
#define MOTHERBOARD BOARD_BTT_SKR_V1_3
#define CUSTOM_MACHINE_NAME "BTT SKR 1.3"
#define SDSUPPORT
#define MKS_TS35_V2_0
#define NO_CONTROLLER_CUSTOM_WIRING_WARNING
#define TFT_CLASSIC_UI
```

classic_ui_no_touch

**Comment by ellensp** [comment]
Interesting.. I only noticed this when testing on the 1.4 turbo, I didn't recheck the 1.3 as it is same code and env (more or less)...  will check on my 1.3

**Comment by ellensp** [comment]
Have a skr 1.4 on the way to test, I suspect issue is only with the turbo and its faster 1769

**Comment by ellensp** [comment]
Confirmed, only issue remaining is only on skr 1.4 turbo

**Comment by vovodroid** [comment]
Hi,

are you going to add support for `BTT_TFT35_SPI_V1_0` screen?

**Comment by ellensp** [comment]
@vovodroid please look before you post.
 1.3 already has BTT_TFT35_SPI_V1_0 and this PR adds BTT_TFT35_SPI_V1_0 to 1.4

but I do not have access to this display to check anything, or fix anything should it not work.

**Comment by vovodroid** [comment]
> this PR adds BTT_TFT35_SPI_V1_0 to 1.4

It's not compiled for 1.4, that's why I asked.

**Comment by ellensp** [comment]
BTT_TFT35_SPI_V1_0 Will compile now.

**Comment by vovodroid** [comment]
Great, thanks! Actually only latest commit is enough to compile. Is it worth to make PR with it only?

**Comment by ellensp** [comment]
Retested, all working, initial non working was caused by not re-powering the board, soft reset was not enough to clear something in the touch screen when a non touch firmware was uploaded.

**Comment by firepower9966** [comment]
getting white screen on Robin Nano 3.1 with TS35 V2.0 with TFT_COLOR_UI and TOUCH_SCREEN enabled.

**Comment by ellensp** [comment]
@firepower This has zero to do with this pr, which is exclusively for skr v1.3, skr v1.4 and skr v1.4 turbo.

**Comment by jmz52** [comment]
@firepower9966, the problem with your board was caused by https://github.com/MarlinFirmware/Marlin/pull/25784 and it is already being worked at.

**Pull request merged**
