### PR TITLE
Anycubic I3 Mega (AI3M) extensible ui implementation

### PR DESCRIPTION
**Pull request by hub-jba**
### Requirements

* Updated Configuration.h and Configuration_adv.h files should be added to the Marlin config examples repo in this PR: https://github.com/MarlinFirmware/Configurations/pull/154

### Description

This is an implementation of the Anycubic I3 Mega (AI3M) custom TFT code in the Extensible UI (ai_api) approach. It is a port of the code from Derhopp and David Ramiro into Marlin 2.0 extensible UI primitives with an attempt to cut down on any core functionality duplication effectively using the extensible UI API calls and core Marlin features.

### Benefits

Brings proper Marlin 2.0 support to the Anycubic I3 Mega (AI3M)

### Related Issues

N/A

### CODE REVIEW

**Comment by marcoburato** [comment]
So... meanwhile, I wrote an extui module for the Anycubic Chiron TFT. And today I noticed this PR was merged with code for the Anycubic i3 Mega.

AFAIK, the 2 screens are very similar but not quite the same. For instance, the Chiron has a menu entry to perform auto-levelling.

My implementation has a few main differences:
- it uses the existing MarlinSerial class instead of adding a new implementation
- it doesn't add fake SD card files to create an extra menu
- requires AUTO_BED_LEVELING_BILINEAR and FILAMENT_RUNOUT_SENSOR
- it does not (currently) support POWER_LOSS_RECOVERY

All of that said, I reckon it's not worth trying to merge the 2 implementations. There are other models already and there will be more. Trying to unify everything would be more elegant, but it would be a problem to test since a change for a printer LCD could break support for another one and the person changing the code very likely won't have access to all Anycubic printers to test.

So, my suggestion would be to just tweak the configuration #defines to enable the module for the correct LCD.
For instance, I had this code in my Config.h

    //
    // Touch-screen LCD for Anycubic printers
    //
    //#define ANYCUBIC_LCD
    #if ENABLED(ANYCUBIC_LCD)
      #define ANYCUBIC_LCD_CHIRON
      
      #define ANYCUBIC_LCD_SERIAL_PORT 3
    #endif

which could become:

    //
    // Touch-screen LCD for Anycubic printers
    //
    //#define ANYCUBIC_LCD
    #if ENABLED(ANYCUBIC_LCD)
      #define ANYCUBIC_LCD_I3_MEGA
      //#define ANYCUBIC_LCD_CHIRON
      
      #define ANYCUBIC_LCD_SERIAL_PORT 3
    #endif

The only other thing I would consider is to drop the module anycubic_serial and use the existing MarlinSerial class.

Please let me know your thoughts.

**Comment by hub-jba** [comment]
I like the idea of not needing to re-implement the Serial class, I wanted to do that, but just ran out of time.

I agree with you that any attempt to merge the two implementations will probably need the person doing the merge to at least have both printers handy to test on. The test/debug cycle was what killed me the most timewise on this.

I didn't technically implement the code myself though for this, I ported David Ramiro's code (which was based on Derhopp's code) and then cleaned up a few things to make sure the memory use was as low as possible. Thinkyhead made some major changes to the config file to make it one set of configs for both bl touch and non bl touch systems. It would be a small effort to add the Chiron configs to that as well.

How different is your implementation to mine otherwise?

**Comment by marcoburato** [comment]
I've seen other Marlin forks and decided to write my implementation from scratch. So, the code is similar in what it does but it's syntactically different. Other than a few changes to instantiate a new MarlinSerial class, it's basically just 1 file.

I noticed some pins have now been #defined in pins_TRIGORILLA_14.h which is something to revisit as well: while the mainboard has some connectors for specific endstops and other hardware, both the Chiron and i3 Mega have a "hub" PCB mounted on top of the Trigorilla that reroutes some signals. Also, some endstops on the Chiron are wired to AUX connectors. It's a mess, not sure what the best solution is here, but I'd probably allow to override the PIN #defines from Configuration.h.

I was hoping to get some indication from @thinkyhead before doing any more work.

**Comment by hub-jba** [comment]
I recommend jumping on discord and trying to get a convo going there. I made sure to lurk on discord before commencing my port so that my effort wasn't wasted either. It would be easier to coordinate in real time then.

Incidentally, have you by chance found a way to send a user specified dialog box to the tft in your code? It's the single most important feature we need to make pause/resume work properly with the aggressive heater time out in Marlin 2.0

**Comment by marcoburato** [comment]
How would I start the conversation on Discord? There doesn't seem to be a #dev channel. That's why I decided to post here.

Regarding the dialog box, if you mean a way to display an arbitrary string then no, I have not seen that. I used the Anycubic source code as reference. I'm not sure what you're referring to with "aggressive heater time out"?

**Comment by hub-jba** [comment]
Yeah that sucks, was hoping you found a magical option. I even tried sending all the J commands from 21 to 51 to no avail. Then I ran out and gave up.

RE: Aggressive heater timeouts, the standard hotend timeout in Marlin 2 is 45 seconds, on bowden printer with a bowden as long as the AI3m that's just not enough time for a filament runout to unload. So you invariably will get a hotend time out, heat up, and then resume process instead of a standard pause, park and resume process with Marlin 2.0

**Comment by marcoburato** [comment]
So... I merged my work. It's not been easy.

The main problem was that you added pin definitions to pins_TRIGORILLA_14.h for the i3 mega, but they don't apply to all Anycubic printers with a Trigorilla mainboard. In fact, the Trigorilla has pins for X-/X+/Y-/Y+/Z-/Z+ endstops, but on both the i3 mega and Chiron the limit switches are NOT all wired to the expected pins on the mainboard. Some endstops are wired to an AUX connector. Also, there's a "hub" PCB mounted on top of the mainboard which routes some signals to other I/O pins.

After a brief discussion on Discord, I was suggested to add pin definitions to pins_TRIGORILLA_14.h using conditional compilation. So, by defining ANYCUBIC_I3MEGA in Configuration.h you'll get the definitions for the i3 mega and by defining ANYCUBIC_CHIRON it will build using the Chiron pin definitions.

Then, I removed anycubic_serial and used the MarlinSerial class. It was a bit time consuming.

Can you please test my [branch](https://github.com/marcoburato/Marlin/tree/ChironIntegration) with your i3 mega?
Your configuration should mostly work, a couple of tweaks will be needed:

1. Add `#define ANYCUBIC_I3MEGA` after defining `MOTHERBOARD`
2. Set `Z2_USE_ENDSTOP` to -1 (instead of re-purposing an endstop, I directly defined `Z2_MIN_PIN` in pins_TRIGORILLA_14.h)

If I didn't mess anything up, it should work.

**Comment by stef-ladefense** [comment]
Hello,
i have AI3M model S and I found some problems :

the management of the Trigorilla Ver 1.1 card is not used although it is present in Configuration.h, line 2222
#define TRIGORILLA_VERSION (0 or 1)
```
change in pins_TRIGORILLA_14.h line 33
#if MB(TRIGORILLA_14_11) -> #if (TRIGORILLA_VERSION)
```

changing feedrate via screen does not work because feedrate_percentage is forced to 100 in anycubic_tft.cpp
although it is declared in motion.h

```
case 20: { // A20 read printing speed
remove
int16_t feedrate_percentage = 100; 

and add in line 32
#include "../../../../module/motion.h"
```


there is old display bug when there are 3 files on the SD card.
if we advance one step with the down arrow, when we go up with the up arrow, the names are in 8.3 format

I corrected in anycubic_tft.cpp line 378 void AnycubicTFTClass::RenderCurrentFileList() {

```
    SelectedFile[0] = 0;
add ExtUI::FileList currentFileList;	
```

```
      if (SpecialMenu)
        RenderSpecialMenu(selectedNumber);
add   else if (selectedNumber <= currentFileList.count())
        RenderCurrentFolder(selectedNumber);
```


I picked up the real starting melody, still in anycubic_tft.cpp

```
ExtUI::injectCommands_P(PSTR("M300 P200 S2794\nM300 P200 S2093\nM300 P250 S2349\nM300 P250 S2637\nM300 P500 S2349\nM300 P500 S3136\nM300 P750 S3520"));
```

and I add a #define STARTUP_CHIME in the AI3M section of Configuration.h


I added the management of the AI3M model S in Configuration.h

```
//#define I3MEGA_HAS_BLTOUCH
//#define I3MEGA_HAS_TMC2208
add
//#define I3MEGA_IS_S
```

and in //============================== Movement Settings ============================

```
/**
 * Default Axis Steps Per Unit (steps/mm)
 * Override with M92
 *                                      X, Y, Z, E0 [, E1[, E2...]]
 */
#if ENABLED(I3MEGA_IS_S)
 #define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 384 }
#else
 #define DEFAULT_AXIS_STEPS_PER_UNIT   { 80, 80, 400, 96.2 }
#endif
```



I am attaching the modified files that I am using.
[Marlin2.06.stef_ladefense.zip](https://github.com/MarlinFirmware/Marlin/files/5079249/Marlin2.06.stef_ladefense.zip)

**Pull request merged**
