### PR TITLE
Marlin Peltier Logic implementation

### PR DESCRIPTION
**Pull request by pbmgit**
### Description

This change is to introduce Peltier thermoelectric capability (heat and cool) to the "heated bed" function.  This requires a small logic change applying power both for heat and cool.  It is implemented in "bang-bang" mode only (Peltier devices do not do well with PWM). Since power is switched it also requires a direction implementation.  Temperature setting is by standard M140 commands.

This change allows the use of the extensive and relatively inexpensive hardware available for 3D printing to be used in another domain.  In this instance that domain is beer brewing.  In that domain heating is required for mashing and cooling is required for various parts of the brewing cycle.  The process operates both above and below ambient temperature.

The brewing implementation is outside the scope of this request.  This request only implements the temperature control changes and the configuration items to support it.

### Requirements

This change does not require a specific board but it does require an available relay control port

### Benefits

This PR implements logic to set and hold a temperature using a thermoelectric Peltier chip.  This allows temperature regulation both above and below ambient temperature. 

### Configurations

 All configurations (hopefully)

### Related Issues

No Related Issues

### CODE REVIEW

**Comment by pbmgit** [comment]
I don't understand where my form comments went..

<edit> Ah, OK.  Remove the markups that are interpreted as comments

**Comment by thisiskeithb** [comment]
> I don't understand where my form comments went

Anything within `<!--` and `-->` are hidden. I've edited your description to fix it.

**Comment by pbmgit** [comment]
I guess we were editing at the same time.

**Comment by pbmgit** [comment]
I've never done something like this before so I don't know if I went about things in the right way with regard to this submission.  I'm guessing from reading the commit information above that there were other pieces of code that were merged in with my Pull Request to keep it current.

For my curiosity, should I have done something else (e.g. opened an issue) concurrently or ahead of the pull request?  I just don't know the choreography on something like this.

**Comment by thinkyhead** [comment]
PRs sent to `bugfix-2.1.x` need to implement changes on the code as it currently exists in the target (`bugfix-2.1.x`) branch. A quick `git fetch upstream ; git rebase upstream/bugfix-2.1.x` followed by `git push -f` usually does the trick. It can take some practice to get good at rebasing from older dustier code, so for small features simply bringing the code over by hand is sometimes easier.

Different projects will handle pull requests differently. I'm open to pull requests when the implementation is close to complete and when the feature may have some general appeal or use. This feature is sensible to implement as an extension to the bed and it's not very complicated so it can get a quick review. In the future this might be generalized so that one could have a heated bed but also a Peltier used for something else, should the demand arise.

Thanks for the submission! It will get merged pretty soon, just under the wire for the 2.1.3 beta - coming soon.

**Pull request merged**
