### PR TITLE
Ender-5 Profile

### PR DESCRIPTION
**Pull request by rmpel**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

This is a copy of the Ender-3 Profile, renamed to Ender-5, with a new status-screen-logo.
The profile is essentially the same as the Ender-3 (only the max Z-height has changed) as the Ender-5 is technically identical to the Ender-3.
My Ender-5 has not yet arrived, so I did NOT verify on actual hardware, but;
- the mainboard is the same (Creality3D Melzi 1.1.3)
- the bed XY are same (220mm print, 235mm actual)
- the same X-carriage is used; same Hot-end, same, extruder, same steppers, same T2 belt
- the same Y-axis; although the stepper on the 5 is a dual-side stepper; it drives the same T2 belt as the Ender-3, but 2 instead of 1
- the same Z-axis; same stepper, same lead screw
- the same display unit

Apart from the max build height, the only real difference is the form factor; cubic design, bed only moves up/down, the hot-end moves XY.

### Benefits

Support for the newly created Ender-5, that's benefit enough for me :)

### Related Issues

Might be a feature request, I did not look. I ordered an Ender-5 and started assembling the care package to bring the printer up to specs with my Ender-3 :)

### footnote

I hope I'm doing this right. If not, please let me know.
I understand if you would like to wait with this until I tested it out on the actual printer. (expected delivery: 2 weeks)

### CODE REVIEW

**Comment by swilkens** [comment]
I found that the default homing speed was a little high on my Ender-3, I think the same will apply here.

Check here for more information:

https://github.com/MarlinFirmware/Marlin/issues/12074

I also think it's good that you've kept the bed size at 220, the limit switches tend to be in a position where they do not allow the full 235 to be reached.

**Comment by rmpel** [comment]
I forked yesterday, would that not imply the merged 12074 is already present?
I'll check it when I get home.

**Comment by rmpel** [comment]
indeed the improved homing speeds are not yet here.

**Comment by thinkyhead** [comment]
- Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

  See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

- Thanks for your contribution! Unfortunately we are no longer accepting PRs directed to the 1.1.x branches. Please redo this PR starting with the `bugfix-2.0.x` branch and be sure to target `bugfix-2.0.x` when resubmitting the PR.

**Comment by swilkens** [comment]
> indeed the improved homing speeds are not yet here.

It was merged into bugfix-2.0.x only, and also into the Ender-3 profile. We should probably apply this homing speed reduction to all Creality cartesian printers

**Comment by rmpel** [comment]
well, in retrospect I am glad this PR is not accepted;

The Ender-5 is not 100% technically identical to the 3. The 5 uses the same components, but all axes are reversed!!!

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR true
#define INVERT_Y_DIR true
#define INVERT_Z_DIR false

should be

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false
#define INVERT_Y_DIR false
#define INVERT_Z_DIR true


but I will not be sending a pull request again. I will not be testing Marlin 2.0 until released, and considering my assumptions and consequent failure, I will not send a pull request for code that "should work".

When 2.0.0 is mainstream, and the Ender-5 profile is still missing, I will take another stab at it.

**Pull request closed without merging**
