### PR TITLE
[2.0.x] Fix EEPROM CRC

### PR DESCRIPTION
**Pull request by RowanMeara**
#8283 packaged for 2.0.x.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Resolves https://github.com/MarlinFirmware/Marlin/issues/8289

**Comment by Roxy-3D** [comment]
Actually....  I think the bugfix-v2.0.0 was OK.   I'm going to revert this merge.

**Comment by RowanMeara** [comment]
Oops.   I just assumed the files were the same.

**Comment by Roxy-3D** [comment]
You did the right thing making a Pull Request for both branches.   I made a mistake and did not notice that only 1 of the branches had the flaw.

Thank You for the help!

**Comment by tcm0116** [comment]
Are we sure only 1.1.x had the flaw? I'm getting CRC mismatch errors on my LPC1768 board.

**Pull request merged**
