### PR TITLE
[1.1] Add Anet Keypad LCD pins for RAMPS

### PR DESCRIPTION
**Pull request by Augustus22**
Working pin map for Anet LCD display.
Pins 1 and 2 must be swapped on cable.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Please put this into `Conditionals_LCD.h` in the appropriate place…
```cpp
#elif ENABLED(ANET_KEYPAD_LCD)
  #define ENCODER_FEEDRATE_DEADZONE 2
#endif
```

**Comment by Augustus22** [comment]
I only put it in `pins_RAMPS.h` because it was defined in `pins_ANET_10.h`. Would you like me to remove it from both of those locations and put it in `Conditionals_LCD.h` instead?

**Comment by thinkyhead** [comment]
> Would you like me to remove it from both of those locations and put it in Conditionals_LCD.h instead?

Yes, thanks. That's the appropriate place for these kinds of non-pin settings.

**Comment by Augustus22** [comment]
Sorry about the merge. I should have rebased first. I assume you squash commits?

**Comment by thinkyhead** [comment]
> Sorry about the merge. I should have rebased first. I assume you squash commits?

Not a problem. If things get really out of whack, there's always `git diff`!

**Pull request merged**
