### PR TITLE
Queue filament runout script immediatly

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Set filament runout script to queue immediately instead of at the end of the queue following g29 retry and recover. Prevents too many moves completing following runout trigger, especially as buffer sizes are increased for 32 bit boards.

### CODE REVIEW

**Comment by robbycandra** [comment]
I have (to) try this, but this create(s) another problem. I (have) found that sometimes, it create(s) layer shifting. Maybe, sometime(s the)  printer (will) pause between stepper block(s) that have (a) high speed. The result is we can control acceleration and jerk before and after the PAUSE.

**Comment by Roxy-3D** [comment]
Whoa!    Please give more detail about what can cause layer shifts!!!

> The result is we can control acceleration and jerk before and after the PAUSE.

The result is we should control the acceleration and jerk before and after the pause?????

**Comment by InsanityAutomation** [comment]
Every move inside M600 is controlled by the park conditionals, NOZZLE_PARK_XY_FEEDRATE so it should be controlled already. Moving a command to the front of the queue should not have any more or less impact on speed. It can land between the same commands if triggered moments earlier with the way it is currently. I dont see how this could possibly cause a layer shift unless there is a very large issue elsewhere with the queue....

**Comment by Roxy-3D** [comment]
> Every move inside M600 is controlled by...

I agree....   But I really want to hear @robbycandra 's thoughts!

**Comment by InsanityAutomation** [comment]
> 
> 
> > Every move inside M600 is controlled by...
> 
> I agree.... But I really want to hear @robbycandra 's thoughts!

Agreed, whatever observation he (has) had may help get (us) closer to whatever is actually going on!

**Comment by robbycandra** [comment]
P_20190604_174318_vHDR_Auto
I use  gcode.process_subcommands_now_P(PSTR("M25 P \nM24"));
This layer shift happened after return from Pause (M24). 
But I cannot reproduce it.

At that time, the extruder is printing the infill which have speed setting arround 120mm/s. Acceleration is very high. Looks like it move without acceleration, directly goes to 120mm/s.

Is it posibble that  gcode.process_subcommands_now_P() insert the command in the middle of Planner block ? I am not sure but i am affraid the command cut the block without recalculate acceleration.

**Comment by robbycandra** [comment]
More Info: 
I use ABL, with 
```
  #define SEGMENT_LEVELED_MOVES
  #define LEVELED_SEGMENT_LENGTH 5.0
```
Maybe the pause happened bettween this segment.

**Comment by robbycandra** [comment]
event_filament_runout -> (called from) runout.run() -> manage_inactivity() -> idle()

And idle() is called from everywhere... :((
including from planner.cpp and motion.cpp.
I dont think its a good idea to put pause command from idle().
But I can be wrong, please correct me.

**Comment by thinkyhead** [comment]
This method will not work.

In order for a G-code (such as `M600`) to prevent further commands from being run through the command queue, it must be run through the normal G-code queue execution path. If you try to start `M600` actions from this point in the code, it will not block the queue, and will allow other commands to go into the queue and get processed (via any call to `idle`). This is why there may be jerky conflicting moves being attempted at the same time as the runout handling.

The important thing about the current method (using the priority queue) is that it just sets commands to be handled later, and then at the _correct point in the execution flow_ the commands are added to the _end of the command queue_.

To do what you're attempting with the current command architecture, what you really want is some way to insert commands _at the front of the queue_ (and in the right order) instead of at the end.

One approach which should work would be to get rid of the `drain_injected_commands_P` method, which always puts its commands at the end of the queue, and instead have `advance_command_queue` pull commands from the `injected_commands_P` buffer and run them ahead of anything in `command_queue`.

**Comment by InsanityAutomation** [comment]
I'll have to do more digging this weekend. Was a quick thought seeing the g29 injection stuff right below it.

**Comment by thinkyhead** [comment]
It's okay below, because `event_probe_failure` is only called from within the G-code execution path (`G29_with_retry`).

**Comment by robbycandra** [comment]
Thinkyhead, Thanks for good explanation. I will learn more about this.

**Comment by robbycandra** [comment]
Dear all.... 

I already make a function to insert command in front of the queue. 
But after trying, i realize this: 

1.  default BUFFER SIZE for gcode command is 4, this means by insert the command in front of the queue i move advance by 4 gcode comand.

2. default BUFFER SIZE for planner block is 16, this means PAUSE still have to wait for 16 planner block.

**Pull request closed without merging**
