### PR TITLE
Case light g-code M355

### PR DESCRIPTION
**Pull request by stanoba**
Implementation of `M355` G-Code.

See: http://reprap.org/wiki/G-code#M355:_Turn_case_lights_on.2Foff

Supported G-Code:
- `M355 S0` - Case light off
- `M355 S1` - Case light on
- `M355 Sx` - Set case light intensity between 2 and 255

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
Where is the progress?
In your case i have to remember the M-code, in the M42-case i have to remember the pin-number.

**Comment by stanoba** [comment]
Hi Blue-Marlin.
Thanks for your feedback. According [RepRap wiki](http://reprap.org/wiki/G-code#M355:_Turn_case_lights_on.2Foff), G-code M355 is dedicated for case light. What do you think, what is easier? Remeber G-code or combination of G-code and pin number? Beside that, with g-code M42 you can accidently change pin level on different pin than you want. This is initial release of case light code. Next time I'd like to add menu item for the case light.

**Comment by Blue-Marlin** [comment]
Exactly. It will end in a menu item and on a macro button at the host program. A special g-code is not needed.

**Comment by stanoba** [comment]
Are you thinking about something like this?

### `Marlin_main.cpp`:

``` cpp
void setup_case_light() {
   #if HAS_CASE_LIGHT
     #if ENABLED(CASE_LIGHT_DEFAULT_ON)
       OUT_WRITE(CASE_LIGHT_PIN, HIGH);
       bool caselight = true;
     #else
       OUT_WRITE(CASE_LIGHT_PIN, LOW);
       bool caselight = false;
     #endif
   #endif
 }
```

### `ultralcd.cpp`:

``` cpp
    // Switch case light on/off
    //
    #if HAS_CASE_LIGHT
      if (caselight)
        MENU_ITEM(gcode, MSG_SWITCH_CL_OFF, PSTR("M42 P" STRINGIFY(CASE_LIGHT_PIN) " S0"));
      else
        MENU_ITEM(gcode, MSG_SWITCH_CL_ON, PSTR("M42 P" STRINGIFY(CASE_LIGHT_PIN) " S255"));
    #endif //HAS_CASE_LIGHT
```

### `language_en.h`

``` cpp
#ifndef MSG_SWITCH_CL_ON
  #define MSG_SWITCH_CL_ON                    "Switch case light on"
#endif
#ifndef MSG_SWITCH_CL_OFF
  #define MSG_SWITCH_CL_OFF                   "Switch case light off"
#endif
```

**Comment by Blue-Marlin** [comment]
Yes - something like that.

Thinking about it - if would make much sense to me to handle it like the part cooling fans.
And thinking about that, it would make much sense to introduce a common PWMable device including heaters, fans, lights and whatever, opening the possibility for software/hardware pwm to avoid the timer problems. But that is a huge task.

**Comment by stanoba** [comment]
Hi @Blue-Marlin,
I have started thinking about M42 approach more deeply (based on existing power supply routine G-code M80 and M81) and found out that usage of G-code M42 is not enough, because M42 can't control variable for storing case light status, like g-code M80 and M81 does (variable powersupply).
Based on this information, I think that implementation of G-code M355 has a good reason. Beside that it will be more RepRap G-code compatible :)

**Comment by thinkyhead** [comment]
Instead of using the existence of the pin definition to enable this feature, let's use an option flag instead. You can still leave the pin override there, commented-out. The thing is, we now define recommended default pins in the pins files for all features, then we allow the default to be overridden by configurations. (Exceptions exist, but we just haven't gotten around to fixing them yet.)

**Comment by thinkyhead** [comment]
Merged #5133

**Pull request closed without merging**
