### PR TITLE
Remove an iterated #include

### PR DESCRIPTION
**Pull request by ghost**
It's included in Marlin.h.

### CODE REVIEW

**Comment by jbrazio** [comment]
@esenapaj Don't do this, objects shall list their library dependencies on the header file otherwise they are not "self contained".

As a quick example, when we build something like `PersistentStorage` object, it will be the only one with EEPROM access, this means that `<avr/eeprom.h>` could be removed from `Marlin.h` into the new object's header file.. guess what will happen at that time with `PrintCounter` ? :-)

**Comment by ghost** [comment]
I understand that I've stepped into domain that it's beyond my intellect.
I'm ashamed of my ignorance, and I apologize to you.

**Comment by jbrazio** [comment]
Please do not apologize ! It was not my intention to offend you in such way.
You're a great guy doing a great cleanup work, we shall thank you for the effort.

My point was that `<avr/eeprom.h>` was included on `printcounter` by intent and not by mistake.

**Comment by ghost** [comment]
There's no way I get offend.
It seems that I can't tell you exactly what I'd like to say because of my very bad English...
...maybe "understood" caused misunderstanding?
It's necessary that I go to study this and that step by step.

> My point was that <avr/eeprom.h> was included on printcounter by intent and not by mistake.

I understand it definitely.

**Pull request closed without merging**
