### PR TITLE
[2.0] Add new board from Russia

### PR DESCRIPTION
**Pull request by Vynt-1**
begin description http://3dtoday.ru/blogs/svs0724/ruramps4d-ramps-for-adruino-due-the-pilot-shipment-available-for-zack/
I have this Board, and I completely checked out

### CODE REVIEW

**Comment by thinkyhead** [comment]
This will need a little cleanup before merge. Apparently the Unix line endings were replaced with Russian line endings. 😁  I'll look it over and aim to get it merged within the next 24 hours!

**Comment by oysteinkrog** [comment]
This looks like a really great board actually, the price of 3000 RUB is very good!
Is it possible to purchase it?

**Comment by Vynt-1** [comment]
I seem to have fixed pins_RuRAMPS4D.x
Check again please

**Comment by Grogyan** [comment]
This looks like it has address a lot of the short comings of the existing RAMPS 1.4 Defaco standard.
Wondering if the board has a minimum of a 1.5A 5V regulator on it, and if the SPI is accessible for other SPI devices other than the RRD displays?
Motor driver support TMC2130?

**Comment by Vynt-1** [comment]
**oysteinkrog** Oh sure. I do not know for sure if there are still ready-made and verified boards from the developer. I'll ask him :)

**Comment by Vynt-1** [comment]
**Grogyan** The SPI is outputted separately. There is a connector under the Wi-Fi module ESP8266-01. The main board power is from 12 to 30 volts. The output power is 5 and 9 volts. I know for sure that 9V 3A. Of the 9 volts, everything else is done. There is a separate power input for table heating (2 channels). There is a separate input Z-Probe (power 9 volts). There is EPROM. A lot of things are ... The developer is now preparing a detailed technical description. If necessary, I will ask you to write a description in English

**Comment by thinkyhead** [comment]
I've done a rebase and cleanup for merge, organizing the pins in the same order to align with the related (RADDS) pins file, and will merge shortly. Please submit revisions if any pin numbers need to change.

**Comment by Roxy-3D** [comment]
Wow!   This looks like a really nice shield.     Is there a place to order one of these boards?

**Comment by Vynt-1** [comment]
**thinkyhead** Well. Thank you! This is not a complete description. I will report as soon as there are changes and additions.

**to all** All boards have been dismantled, next batch will be ready in December. The developer is preparing to open a website and stores on all known platforms

**Comment by Vynt-1** [comment]
**to all** Temporarily, recording of acquisition board is on this email - svs072477@yandex.ru

**Pull request merged**
