### PR TITLE
DWIN_LCD_PROUI compile errors & orphan code

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
This PR corrects three conditions in dwin.cpp:
- DWIN_LCD_PROUI compile time errors when TEMP_SENSOR_BED being set to 0
- DWIN_LCD_PROUI compile time errors when having a probe, enabling BABYSTEPPING, and NOT enabling BABYSTEP_ZPROBE_OFFSET
- The following line will never be executed because one of the preceeding #elif statements will always be executed:
`MENU_ITEM(ICON_SetHome, MSG_SET_HOME_OFFSETS, onDrawHomeOffset, SetHome);`

**Steps to Reproduce:**
- Enable a probe
- Enable BABYSTEPPING
- Leave TEMP_SENSOR_BED as 0
- Enable DWIN_LCD_PROUI
- Change MOTHERBOARD to a board that supports the DWIN display

Here's a minimal set of config files that demonstrate the problems.
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/10523741/Config.zip)

This PR fixes the issues in #25271

NOTE: I do not have the hardware needed to test this PR.

---

**Changes to fix DWIN_LCD_PROUI compile time errors when TEMP_SENSOR_BED being set to 0**

Add **#if HAS_HEATED_BED** logic in three places:
- old line 1251 -  this one needed to have an ELSE added so that the **thermalManager.wholeDegHotend(0)** would be executed  when a heated bed wasn't present.
- old lines 1495-1501
- old lines 1516-1520

---

**Changes to fix DWIN_LCD_PROUI compile time errors when having a probe, enabling BABYSTEPPING, and NOT enabling BABYSTEP_ZPROBE_OFFSET**

This backs out the changes from PR #25176 on the old line 3327.

The routine onDrawZOffset is only defined when either of the following is true:
- BABYSTEPPING is enabled and a probe is NOT enabled
- BABYSTEPPING is enabled and BABYSTEP_ZPROBE_OFFSET is enabled

The routine onDrawZOffset is only used in this line:
`EDIT_ITEM(ICON_Zoffset, MSG_ZPROBE_ZOFFSET, onDrawZOffset, SetZOffset, &BABY_Z_VAR);`

Currently this line is only compiled when BABYSTEPPING is enabled and a probe is enabled. Prior to PR #25176 it would be executed if either of the following are true:
- BABYSTEPPING is enabled and a probe is NOT enabled
- BABYSTEPPING is enabled and BABYSTEP_ZPROBE_OFFSET is enabled

---

**Changes to allow MENU_ITEM(ICON_SetHome, MSG_SET_HOME_OFFSETS, onDrawHomeOffset, SetHome); to execute**

This backs out the changes from PR #25176 on the old lines 3026, 3028 & 3030.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> NOTE: I do not have the hardware needed to test this PR.

@mriscoc Should be able to.

**Comment by Bob-the-Kuhn** [comment]
Just changed new line 1254 so that it only executes when HMI_value.pidresult isn't equal to PIDTEMP_START.  

This makes it only execute the update under the same conditions as new line 1252.

**Comment by mriscoc** [comment]
> @mriscoc Should be able to.

I'm preparing a PR with the menu items for Linear Advance and Input Shaping. I think that currently I have those issues fixed in my working sources.

**Comment by Bob-the-Kuhn** [comment]
Let me know for sure.  I'll close this PR if that's the case.

**Comment by thinkyhead** [comment]
@mriscoc ; @Bob-the-Kuhn — Are these changes still needed, or is there a pending ProUI update that already has them? If needed, I can put together a PR based on the latest ProUI, rebased on the current state of `bugfix-2.1.x`, so the latest changes can get merged ahead of 2.1.3.

**Comment by mriscoc** [comment]
@thinkyhead the code for ProUI has diverged from the code from my repository, so I need to do some more work to provide a good PR with the latest changes.

**Comment by mriscoc** [comment]
Finally, here is the latest ProUI PR: https://github.com/MarlinFirmware/Marlin/pull/26003

**Pull request closed without merging**
