### PR TITLE
Add G68 and G69 - rotation about an axis

### PR DESCRIPTION
**Pull request by deirdreobyrne**
### Description

G68 and G69 are standard g-codes for rotating around an axis (where the axis is set by G17-G19).

### Question

Should rotations be limited to the XY plane? Rotating in other axes is maybe meant for CNC machines with rotatable tool heads? I've implemented rotations in XZ and YZ, but I since note that creates problems dealing with power recovery.

### Detail

There doesn't appear to be any standards as to how the G68 parameters are interpreted. So parameters A, B and R have been implemented. A and B give the centre of rotation, and R is the angle of rotation in decimal degrees.

When the XY plane is the workspace plane (G17), A is the X coordinate of the centre of rotation, B is the Y coordinate of the centre of rotation, and R is the angle of rotation of the XY axes anti-clockwise as seen from above (+Z)

When the ZX plane is the workspace plane (G18), A is the Z coordinate of the centre of rotation, B is the X coordinate of the centre of rotation, and R is the angle of rotation of the ZX axes anti-clockwise as seen from the front (-Y)

When the YZ plane is the workspace plane (G19), A is the Y coordinate of the centre of rotation, B is the Z coordinate of the centre of rotation, and R is the angle of rotation of the YZ axes anti-clockwise as seen from the right (+X)

When neither A nor B are specified, the current tool head position is used as the centre of the rotation. If one of A or B is specified, the other is set to zero.

Note that when the axis of rotation is different to the position of the tool head, then the position of the tool head will be immediately updated to reflect the fact that it is now in a different coordinate system.

The following g-codes will reset the rotation when they are issued - `G28, G53 to G59, G92`.

### Benefits

G68 has a use in hobbyist double-sided PCB milling, as it is difficult to recreate the precisely correct orientation of the PCB after it has been flipped to the second side.

### CODE REVIEW

**Comment by deirdreobyrne** [comment]
Problem - I forgot about powerloss recovery - the current G68 state isn't saved at powerloss. Going to figure out how powerloss recovery works and fix this ASAP.

Also resetting the rotation when any of G17 - G19 is issued is probably not needed, or a good idea. And resetting before homing is probably a good idea!

**Comment by deirdreobyrne** [comment]
Thinking about it further, and apologies for not having done more thinking before making the PR (this is only my second ever git PR - feedback welcome), I wonder if the rotation should be limited to the XY plane. Rotating in other planes is maybe meant for machines with an independent axis on the tool head of a CNC machine.

(Also note to self - I update current_position from the stepper positions - I should probably just rotate current_position directly, thereby not potentially losing precision in current_position. I'll address that when the above question is resolved).

**Comment by deirdreobyrne** [comment]
Just realised - rotations are supposed to be cumulative.

**Comment by MFlego** [comment]
@deirdreobyrne thank you for implementing this g68.   I have been really interested having g68 in Marlin so I full support this feature.  Are you planning to reopen this PR at any point?  From what I can tell this has not made it into marlin main yet.

**Comment by deirdreobyrne** [comment]
> @deirdreobyrne thank you for implementing this g68. I have been really interested having g68 in Marlin so I full support this feature. Are you planning to reopen this PR at any point? From what I can tell this has not made it into marlin main yet.

I am thinking about it - however it's actually a considerably bigger project than I initially thought. I'll have to refactor the code which translates between machine and world coordinates, because I also have to do things like rewrite bounds checking.

**Comment by waxo62** [comment]
G68 ! Oh, how much I miss this future as I have made a MARLIN driven machine I call MultiBot to use for Milling, Laser, Plasma cutting as well as 3D-printing. G68 for probing a workpice cordinates should make my work so much easier.
It will open a hole new area for using the MARLIN.

**Comment by fedetony** [comment]
I left the implemented code for rotation you can use for G68 and G69 in [here](https://github.com/MarlinFirmware/Marlin/pull/21792#issuecomment-838987548). The vector3.zip file has vector_3 class which includes rotation arbitrary rotation of x,y,z. points.

**Comment by fedetony** [comment]
@deirdreobyrne I Was looking at your code, and thought that maybe you can avoid modifying so much if you set G68 as a GCODE_MOTION_MODES cancel-able with G69, homing between others. Then you do the transformation (rotation ) in the parsed data, and all functions will not need to know the coordinates are being rotated since motion coordinates are just fed as the coordinate value.
Just a thought :)

**Pull request closed without merging**
