### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by luisfcorreia**
Fix one typo and correct a word for proper Portuguese.

### CODE REVIEW

**Comment by Wackerbarth** [comment]
I have applied your correction to the 1.0.x branch.

However, I suspect the same changes should also apply to the 1.1.0-RC and the dev branches.

In trying to apply the change, I encounter some differences

```
<<<<<<< HEAD
#define MSG_DISABLE_STEPPERS                " Desligar motores"
#define MSG_AUTO_HOME                       "Ir para home"
#define MSG_SET_HOME_OFFSETS                "Def. home offsets"
=======
#define MSG_DISABLE_STEPPERS                " Parar motores"
#define MSG_AUTO_HOME                       "Ir para origem"
#define MSG_SET_HOME_OFFSETS                "def. orig. offset"
>>>>>>> 1afcdd6... Minor corrections to Portuguese translations
```

Which versions of the messages are most appropriate for your language?

**Comment by luisfcorreia** [comment]
Let me checkout 1.1-RC branch and correct them as well.

**Comment by luisfcorreia** [comment]
I'm seeing a lot of differences between branches, mostly semantic.

How do you want me to fix them, provide a pull request for each branch normalizing both files?

**Comment by AnHardt** [comment]
The `release` branch is closed for new commits. Adapted this to `1.0.x` in #2699.

**Pull request closed without merging**
