### PR TITLE
Add Trinamic TMC5161 stepper driver support

### PR DESCRIPTION
**Pull request by boelle**
same as 5160 just internal FET's

### Requirements

None

### Description

according to @teemuatlut these are 5160's but with internal FET's, so assuming that its just the description missing to make people aware that they have been supported all along

### Benefits

it lets people know we support TMC5161

### CODE REVIEW

**Comment by boelle** [comment]
https://github.com/MarlinFirmware/Marlin/issues/15730

**Comment by thisiskeithb** [comment]
Will this do anything @teemuatlut? They aren't defined in [drivers.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/core/drivers.h) / setup like 5160s in the code.

**Comment by teemuatlut** [comment]
Likely needs a `#define _TMC5161 5160` alias definition. Maybe some other things as well but I don't have the time to test today.

**Comment by boelle** [comment]
line 81-122 seems easy to change

but not sure what to add after line 49

and to make it worse i cant even test it myself

**Comment by GMagician** [comment]
I read that these chip are not yes sold because they will change (from Trinamics site) sure that final chip release will not break this code?

Edit: 

> This product is not yet in volume production as it will undergo product changes. If you're looking for samples, please contact us directly to discuss the available options.

https://www.trinamic.com/products/integrated-circuits/details/tmc5161/

**Comment by thisiskeithb** [comment]
BigTreeTech TMC5161s are available on Amazon Prime (US) in addition to AliExpress. Fysetc has a set for sale on Ali as well.

**Comment by GMagician** [comment]
> BigTreeTech TMC5161s are available on Amazon Prime (US) in addition to AliExpress and Fysetc has a set for sale on Ali as well.

I'm wondering how can they sell something not in production, all samples?

**Comment by thisiskeithb** [comment]
> I'm wondering how can they sell something not in production, all samples?

It's entirely possible that Trinamic's website needs to be updated.

**Comment by boelle** [comment]
please ping me, unsubscribing as my email is getting filled with non relavant stuff

**Comment by boelle** [comment]
so am i missign anything in the PR?

if so please tell me what and where

**Comment by thinkyhead** [comment]
> so am i missign anything in the PR?

Everything! Look at where, for example, "TMC2209" appears in the code. I'm not going to point out all of them. But clearly and obviously this PR is barely a concept at this stage.

**Comment by Acidice1000** [comment]
I just swapped my TMC5160 for TMC5161 and they still don't work.

**Pull request closed without merging**
