### PR TITLE
Switching toolhead array access protection

### LINKED ISSUE #23980: [BUG] Memory Access problem, solveable by additional sanity check
### Did you test the latest `bugfix-2.0.x` code?

No, but I will test it now!

### Bug Description

There exists no validation for the array size of "SWITCHING_TOOLHEAD_X_POS" in Configuration.h.
With more than two toolheads, this can lead to a memory access problem in tool_change.cpp, line 507 "grabxpos = toolheadposx[new_tool];"
It will query a "random" x position for a toolhead whose index is larger than the array size from configuration.h.
I am not super familiar with the way the sanity checks are done, so am sadly disabled to add a appropriate sanity check myself.
Additionally, Software endstops were enabled, and not regarded during toolhead changes. Which might or might not be on purpose, depending if the parking locations are supposed to be in "printable" area or not by definition. 

### Bug Timeline

_No response_

### Expected behavior

Toolhead E3 does not crash into x boundaries, especially with software endstops enabled

### Actual behavior

With software endstops enabled, changing the toolhead should not cause the toolhead to move to a "random" x position outside of software endstop limits.
During compiletime, it should be checked if there exists a defined parking position for each of the toolheads.

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

2.0.9.3

### Printer model

similar e3d toolchanger system, corexy, 3 toolheads

### Electronics

BOARD_BTT_OCTOPUS_V1_1

### Add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

_No response_

### Host Software

_No response_

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by GMagician**
Should fix #23980

### CODE REVIEW

**Comment by GMagician** [comment]
Can't find out which cnf is used to see why it doesn't compile

**Comment by ellensp** [comment]
In buildroot/tests/BIGTREE_GTR_V1_0 

It uses the bugfix default config then modifies it with
```
restore_configs
opt_set MOTHERBOARD BOARD_BTT_GTR_V1_0 SERIAL_PORT -1 \
        EXTRUDERS 3 TEMP_SENSOR_1 1 TEMP_SENSOR_2 1 \
        SERVO_DELAY '{ 300, 300, 300 }'
opt_enable SWITCHING_TOOLHEAD TOOL_SENSOR
exec_test $1 $2 "BigTreeTech GTR | Switching Toolhead | Tool Sensors" "$3"
```
so it probably needs a `SWITCHING_TOOLHEAD_X_POS '{ 215, 0 ,0}'` added to opt_set

**Review by ellensp — CHANGES_REQUESTED** [review]
Needs a \  on end of the previous line. the opt_set is one line split over several actual lines

**Comment by GMagician** [comment]
Yep, just made quickly and not take too much care of what I've done. Thanks for note

**Pull request merged**
