### PR TITLE
Bugfix 2.0.x Add Mesh Edit Graphics

### PR DESCRIPTION
**Pull request by cdedwards**
define BABYSTEP_ZPROBE_GFX_OVERLAY or define ENABLE_MESH_EDIT_GFX_OVERLAY to enable either of these two features. They are not mutually exclusive.

This is from the following pr by marcio-ao with the addition of adding this to the UBL mesh edit screen.
Addressing #7600 (Fix bug introduced with merge #7593) #7602

### CODE REVIEW

**Comment by GMagician** [comment]
Why have you added "reverse" defines? Graphics can't be correctly drawn using current 'REVERSE define' used for menu/encoder directions?
And other thing, with not to have one option to enable or not additional graph in both areas?
Theoretically if I want graphics...i want it and I think bigger footprint is graphics data itself, code to add it is not too big

**Comment by cdedwards** [comment]
The reverse defines were part of the original PR. All they do is reverse the location of the UP/DOWN CW/CCW graphics.  As for the ENABLE, I'll leave that up to whomever to decide if it should be one or two..

**Comment by GMagician** [comment]
Ah that's ok, I think that 'reverse define' can be removed because up and down real movements are related to how encoder increase or decrease positions. Since this has it own 'reverse define' it can be reused for graphic as well

**Comment by Tannoo** [comment]
This was merged with, #7593, albeit with issues.

**Pull request closed without merging**
