### PR TITLE
Normalized section headers, added some headers, added help URLs for newb...

### PR DESCRIPTION
**Pull request by docdawning**
As I'm a newb to Marlin and 3D Printing I've found this config file particularly rough in a few spots. I've been annoying some people in IRC asking somewhat n00bish questions inspired in part by this config.

I've normalized the section headers and added a few headers too.

I've also added a few help URLs to point others like myself in the right direction.

I think this should help others in to the future. :)

### CODE REVIEW

**Comment by thinkyhead** [comment]
I welcome these changes. Can you apply the same adjustments to each of the `Configuration.h` files in the `example_configurations` subfolders also? (For now we must keep them in sync manually.)

**Comment by docdawning** [comment]
Sure, I'll have a look at it tonight.

**Comment by docdawning** [comment]
Okay, I've made those changes. Now I'm half-way in the mood to entirely refactor this configuration system.. But no.. no...

**Comment by galexander1** [comment]
If you have an idea for an organizing principle for the restructure,
share it...a lot of us want to see a restructure but no single idea has
emerged as a winner.

Come on, you know you want to :)

**Comment by docdawning** [comment]
lol, yeah.. I am tempted. My plan was to try some stuff out on my end and see how it goes. I'm a massive fan of the DRY principle. That is "Don't Repeat Yourself", meaning things are only declared in a single place. I guess a balancing-act is required though.. We must find the intersection of simple to use, DRY and time-realistic. :) Baby-steps for now.

**Comment by AnHardt** [comment]
Maybe a post_configuration.h is god step forward. Ad the moment we define things that are supposed to be changed by the user AND calculate the consequences.
Example:
  #define Z_SAFE_HOMING   // This feature is meant to avoid Z homing with probe outside the bed area.
                          // When defined, it will:
                          // - Allow Z homing only after X and Y homing AND stepper drivers still enabled
                          // - If stepper drivers timeout, it will need X and Y homing again before Z homing
                          // - Position the probe in a defined XY point before Z Homing when homing all axis (G28)
                          // - Block Z homing only when the probe is outside bed area.

  #ifdef Z_SAFE_HOMING

```
#define Z_SAFE_HOMING_X_POINT (X_MAX_LENGTH/2)    // X point for Z homing when homing all axis (G28)
#define Z_SAFE_HOMING_Y_POINT (Y_MAX_LENGTH/2)    // Y point for Z homing when homing all axis (G28)
```

  #endif

Everything in between #ifdef and #endif could go to the post_configuration.h

**Comment by AnHardt** [comment]
A comment like:

//  Overridden if EEPROM activated.

where relevant could be helpful.

**Comment by alexborro** [comment]
What about a configuration tool like Repetier did?
Em 02/02/2015 20:29, "Andreas Hardtung" notifications@github.com escreveu:

**Comment by AnHardt** [comment]
@alexborro Nice!
But would be better if the comments would be left in. The generated files are close to be uneditable.

**Comment by docdawning** [comment]
Yeah, while a configuration GUI is more "user friendly", it can add a ton of complexity as well. I'd hate to hinder Marlin by making a half-working Configuration tool. 

What I have in mind is a base-line config file that declares the defaults for everything. Then users can select machine-specific configuration masks that override the defaults where necessary. 

That's what I have in mind, I'm not yet sure how to implement it. It's been a while since I did much with C and/or C macros.

**Comment by galexander1** [comment]
Last time this came up I recommended putting #ifndef around all of the
defaults.  Like:

#ifdef Z_SAFE_HOMING
  #ifndef Z_SAFE_HOMING_X_POINT
    #define Z_SAFE_HOMING_X_POINT (X_MAX_LENGTH/2)    // X point for Z homing when homing all axis (G28)
  #endif
  #ifndef
    #define Z_SAFE_HOMING_Y_POINT (Y_MAX_LENGTH/2)    // Y point for Z homing when homing all axis (G28)
  #endif
#endif

That way, if they defined Z_SAFE_HOMING but didn't specify the details,
they get the defaults.  They can provide only as much as they want.
That way if someone adds a new feature, they don't have to update every
vendor-provided example configuration to make it generally available.

But someone pointed out last time, that adds a new difficulty...it makes
it hard to be sure exactly which settings are in use.  You could imagine
an end user not understanding that there is an override in something they
#included.

I'm not sure how to weight the old difficulty vs. the new one, but it
would be nice if there was a third way that also addressed the vendor
header problem.

I'd love to steal Linux kernel configurator -- I'd even be willing to do
the labor -- but I have the idea that wouldn't be popular among Windows
users...

Are there assumptions we can make about people who have the Arduino SDK
installed?  Do they all have a host (PC) python interpretter or host C
compiler available?

**Comment by alexborro** [comment]
I think ANY GUI is better than current config way for a regular user, even
the Linux kernel configurator.

I'm not a PC software guy, but I think it is not that difficult to do some
GUI using pyc or java.

Cheers.

Alex.
Em 02/02/2015 21:52, "galexander1" notifications@github.com escreveu:

**Comment by docdawning** [comment]
I respectfully disagree. I think a weak or poor gui could ruin Marlin. A great gui would obviously be a massive boost. I think implementing a good configuration system is a very significant task. I think the macro approach currently used would probably have to be entirely replaced. I think we all want this. I'm thinking some sort of XML-driven configuration schema could serve well. Has anyone here implemented such a system?

**Comment by thinkyhead** [comment]
Keep jamming on this topic, I'm going to merge the PR.

**Pull request merged**
