### PR TITLE
language_pt_PT.h

### PR DESCRIPTION
**Pull request by helderk**
Portuguese European (pt_PT) must have a different translation of Portuguese of Brazil (pt_BR)

### CODE REVIEW

**Comment by thinkyhead** [comment]
I guess we should support both….

**Comment by helderk** [comment]
exact, the old translation think this well for pt_BR, and mine to pt_PT

**Comment by thinkyhead** [comment]
If you can put it together that way and update your pull request, then I can merge this anytime. We love language support!

**Comment by thinkyhead** [comment]
Great, thanks! I've just been cleaning up languages, and I've included your changes in #1427.

**Pull request closed without merging**
