### PR TITLE
Encourage editing of Version strings

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Allow version.h to be included after configuration.h so build version strings can be set based on options by vendors
Allow vendor Version.h file to be included first if exists
Deprecate automatic versioning
Surround values in stock file with ifndef to define any values left out by vendors with defaults

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
Any guess why the due platform doesnt like `#if __has_include("../../Version.h")` ? Seems every other platform was fine...

**Comment by Ludy87** [comment]
create file `buildroot/share/PlatformIO/scripts/DUE_c++17_flag.py`

```py
Import("env")

env.Append(CCFLAGS=["-Wl,-std=c++17"])
```

add line `extra_scripts = pre:buildroot/share/PlatformIO/scripts/DUE_c++17_flag.py` to `[env:DUE]` from `platformio.ini`

```c++
#ifdef __has_include
  #if __has_include("../../Version.h")
    #include "../../Version.h"
  #else
  #endif
#endif
```
See: http://www.open-std.org/pipermail/features/2017-February/000498.html

---
I am not a programmer in Python or C ++

**Comment by InsanityAutomation** [comment]
@Ludy87 For one that breaks this on DUE and another I dont see why the toolset is a different c++ standard between AVR, DUE, and LPC. Every other platform is fine, and they all install the same gcc package. Ill try to see if I can force c++17.

**Comment by thinkyhead** [comment]
`STRING_SPLASH_LINEX` is also needed by the character display.

**Comment by InsanityAutomation** [comment]
I dont understand reverting the changes here https://github.com/MarlinFirmware/Marlin/pull/14141/commits/2e5c5c076bd87a7636b96a27e38cb3a8345f804f

Those defines rely on strings from Version.h so moving them with the rest of the LCD boot screen stuff in Config_Adv allows this to retain the original intention of Vendors like Lulzbot or the way I maintain my branches setting version strings based on options selected in configuration.h.

If those are moved back to configuration.h, the include order needs to be reverted as well.

**Comment by InsanityAutomation** [comment]
Could try gnu++17 instead of c++1y - spec says it should be 1z but that didnt work either. Same error as 17 does.

**Comment by thinkyhead** [comment]
> Those defines rely on strings from Version.h

Well, they can't be inside the block "if GRAPHICAL_LCD". Character LCDs use them too.

> Could try gnu++17 instead of c++1y - spec says it should be 1z but that didnt work either. Same error as 17 does.

Then `__has_include` just may not be possible.

I would prefer to discourage ***everyday users*** from editing the version strings, so I'm dubious about putting `Version.h` right next to the `Configuration` files and making it visible in the Arduino IDE. The original scheme used `inc/_Version.h` and I don't mind keeping it that way, but also having that file in place and getting rid of `USE_AUTOMATIC_VERSIONING`.

**Comment by thinkyhead** [comment]
image

image

image

**Comment by InsanityAutomation** [comment]
FWIW the flag -std=gnu++17 does function for the due platform. I pulled the changes and compiled with this. Ill revise it to keep automatic versioning, update automatic versioning to have the same ifndef's and if you want it hidden from the generic users, I can either omit the root directory Version.h file or tuck the sample elsewhere. The make file sets a default to gnu++11 however it seems that every other framework is overriding to 17 somewhere.

**Comment by tpruvot** [comment]
both ststm32 and mapple force it to gnu++11, we cant override it

**Comment by InsanityAutomation** [comment]
@tpruvot Odd then, this must be defined elsewhere in those platforms as they compiled it fine on travis without any tinkering... Maybe gnu++11 implemented it whereas the c++11 flag didnt?

**Comment by tpruvot** [comment]
tests are limited, bltouch feature is not enabled but im mixing two different issues... see #14177

**Comment by InsanityAutomation** [comment]
@tpruvot This should be active regardless of any flags since it changes some include stuff around right at the start

**Pull request closed without merging**
