### PR TITLE
Don't allow filament change without homing first

### PR DESCRIPTION
**Pull request by ghost**
Reference #7052

Add check for all axis homed and if not, home them. Useful when using M600 on the command line after turning on the printer.

### CODE REVIEW

**Comment by Grogyan** [comment]
Logic doesn't seem right.
If read right, if doing a filament change, homing ALL axes will cause end
effector and/or axis rails to crash into print

**Comment by tcm0116** [comment]
> If read right, if doing a filament change, homing ALL axes will cause end effector and/or axis rails to crash into print

Looks like it will only home if the filament change is command while the printer is not homed, so it shouldn't crash into the print.

**Comment by Roxy-3D** [comment]
> Looks like it will only home if the filament change is command while the printer is not homed, so it shouldn't crash into the print.

Actually...  I'm having second thoughts.   What about the case where the user has turned on 
```cpp
//#define HOME_AFTER_DEACTIVATE  // Require rehoming after steppers are deactivated
```

If they pause the print...   Let the motors time out...  and then decide to do a M600, they could get unexpected behavior.   Maybe we should go with the simple 'return;' instead of trying to help them.   Or at least be sensitive to the HOME_AFTER_DEACTIVATE setting and if that is active, they get a 'return;'

Your thoughts?

**Comment by Tannoo** [comment]
Would known position be better than unhomed?

**Comment by Roxy-3D** [comment]
Maybe...  But the problem is if the stepper motors are deactivated, the user might move the nozzle...   And at that point you don't know where the nozzle is positioned.   And if they have HOME_AFTER_DEACTIVATE the problem becomes what about a print that is partially finished.  Really bad things can happen if you home the machine.   

Although....   It may not matter if M600 does the home or just restarting the print causes it to home in that case.

**Comment by Tannoo** [comment]
I thought M600 didn't let the steppers timeout for that very reason.

**Comment by Tannoo** [comment]
Or has that been changed?

**Comment by Roxy-3D** [comment]
Yes...  But this check to see if the machine needs to be homed is at the very start of M600.   M600 hasn't done anything yet.

**Comment by Tannoo** [comment]
I'm not against it, but will it effect M600 during a print?

**Comment by Grogyan** [comment]
I suggest, rather than Home_All
Just do a Home_X and Home_Y
As these are probably better reference points.

However, this would surely be better later in the function rather than at
the start?

**Comment by tcm0116** [comment]
> I thought M600 didn't let the steppers timeout for that very reason.

If **PAUSE_PARK_NO_STEPPER_TIMEOUT** is enabled, then the steppers won't timeout during M600. 

My suggestion is to make this an optional feature in the **ADVANCED_PAUSE** section in Configuration_adv.h called something like **HOME_BEFORE_FILAMENT_CHANGE**, and then make it require **PAUSE_PARK_NO_STEPPER_TIMEOUT** in SanityCheck.h.

**Comment by Tannoo** [comment]
Oh yeah... that's what's changed.

**Comment by Roxy-3D** [comment]
> My suggestion is to make this an optional feature in the ADVANCED_PAUSE section in Configuration_adv.h called something like HOME_BEFORE_FILAMENT_CHANGE, and then make it require PAUSE_PARK_NO_STEPPER_TIMEOUT in SanityCheck.h.

I think that alleviates my concern.  That is probably a good idea.

**Comment by ghost** [comment]
See #7058

**Pull request merged**
