### PR TITLE
Added new translatable labels.

### PR DESCRIPTION
**Pull request by ivan-galvez**
- Added MSG_END_HOUR and MSG_END_MINUTE labels to all language files.
- Available translations:
  EN, FR, DE, ES, IT, PT, PT-BR.

### CODE REVIEW

**Comment by AnHardt** [comment]
Nice. But serial output is involved.

**Comment by thinkyhead** [comment]
@AnHardt Are the English "hours" and "minutes" really part of the "serial protocol"? Is this protocol documented someplace, and who is depending on it anyway?

**Comment by ivan-galvez** [comment]
bq printers have these labels translated since long time ago and we haven't received any bug reports regarding third party applications problems, though.

**Comment by thinkyhead** [comment]
If it turns out to be an issue, we can leave the serial output as English but leave the LCD message translated. Personally, I would like it better if the end message showed total time in HH:MM format and included the total filament used. With a 16 character wide display this would be at the limit. But the message could blink between total time and total filament used every 2 seconds.

**Pull request merged**
