### PR TITLE
M190 now respects TEMP_HYSTERESIS

### LINKED ISSUE #3441: Bed heating does not stop,
Hi!

I use a prusa 3 clone, Software: MarlinRCDevbugfix (RC5), Checkout last evening around 7 pm in Germany. Before RC5 I used RC3, there were some issues for me (bed levelling) but it worked perfect for me.

Today I had two times the problem the printer would not start printing. 

It stucks and tells me in the Log:
Recv:  T:201.8 /202.0 B:55.4 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:0 @:75 @0:0 @1:75 W:?
Recv:  T:201.8 /202.0 B:55.4 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:0 @:74 @0:0 @1:74 W:?
Recv: echo:busy: processing
Recv:  T:201.8 /202.0 B:55.2 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:0 @:73 @0:0 @1:73 W:?
Recv:  T:201.8 /202.0 B:55.1 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:0 @:73 @0:0 @1:73 W:?
Recv:  T:201.8 /202.0 B:55.1 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:0 @:72 @0:0 @1:72 W:?
Recv:  T:201.8 /202.0 B:54.9 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:0 @:72 @0:0 @1:72 W:?
Recv:  T:202.4 /202.0 B:54.9 /55.0 T0:41.2 /0.0 T1:202.4 /202.0 B@:0 @:57 @0:0 @1:57 W:?
Recv:  T:202.4 /202.0 B:54.7 /55.0 T0:41.2 /0.0 T1:202.4 /202.0 B@:127 @:59 @0:0 @1:59 W:?
Recv:  T:202.4 /202.0 B:54.6 /55.0 T0:41.2 /0.0 T1:202.4 /202.0 B@:127 @:60 @0:0 @1:60 W:?
Recv:  T:202.4 /202.0 B:54.6 /55.0 T0:41.2 /0.0 T1:202.4 /202.0 B@:127 @:60 @0:0 @1:60 W:?
Recv:  T:202.4 /202.0 B:54.6 /55.0 T0:41.2 /0.0 T1:202.4 /202.0 B@:127 @:61 @0:0 @1:61 W:?
Recv:  T:202.4 /202.0 B:54.5 /55.0 T0:41.2 /0.0 T1:202.4 /202.0 B@:127 @:61 @0:0 @1:61 W:?
Recv: echo:busy: processing
Recv:  T:201.8 /202.0 B:54.5 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:127 @:74 @0:0 @1:74 W:?
Recv:  T:201.8 /202.0 B:54.5 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:127 @:75 @0:0 @1:75 W:?
Recv:  T:201.8 /202.0 B:54.6 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:127 @:74 @0:0 @1:74 W:?
Recv:  T:201.8 /202.0 B:54.6 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:127 @:73 @0:0 @1:73 W:?
Recv:  T:201.8 /202.0 B:54.6 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:127 @:72 @0:0 @1:72 W:?
Recv:  T:201.8 /202.0 B:54.9 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:127 @:72 @0:0 @1:72 W:?
Recv:  T:201.8 /202.0 B:54.9 /55.0 T0:41.2 /0.0 T1:201.8 /202.0 B@:127 @:72 @0:0 @1:72 W:?

The print starts with 
G90
M82
M106 S0
M140 S55
M190 S55
M104 S0 T0
M104 S202 T1
M109 S202 T1

and as you cann see all temperature needs are OK (Bed 55°, Extruder 2: 202°). My workaround is: pressing reset, restarting the print-job (octoprint) and the second time it works perfect.

I remember RC4 - I tried this release to, there was the same problem for me: But there has been a bugfix. 

BTW: You all do a very very good work with marlin fw and I appreciate it very much!

Kind regards
Christian

### PR DESCRIPTION
**Pull request by jbrazio**
Fixes #3441, followup #3438.

### CODE REVIEW

**Comment by thinkyhead** [comment]
It's the right idea but the wrong code. The proper code should be…

``` cpp
while (!cancel_heatup && labs(degBed() - degTargetBed()) > TEMP_HYSTERESIS) {
  millis_t now = millis();
  if (now - last_temp_ms > 1000) { //Print Temp Reading every 1 second while heating up.
    last_temp_ms = now;
    print_heaterstates();
    SERIAL_EOL;
  }
  idle();
  refresh_cmd_timeout(); // to prevent stepper_inactive_time from running out
}
```

**Comment by jbrazio** [comment]
Yesterday I had a couple beers, but I did like this because I didn't knew if you wanted to introduce the stabilization period, so this was an adaptation of `M109`.

**Comment by thinkyhead** [comment]
Well, the original code is probably right, now that I think of it. It just waits for the temperature to reach or go over the target, which has always been good enough for the bed. The residency timer stuff (of which `TEMP_HYSTERESIS` is a part) is only meant to apply to `M109`. So I guess this change is actually unnecessary.

**Comment by thinkyhead** [comment]
…unless you are saying that bed heating itself is cutting off due to that setting, preventing it from reaching the target…

**Comment by jbrazio** [comment]
Wait.. let me review what I did last night.

**Comment by jbrazio** [comment]
o.O
Never mind.. you're correct, the logic is reversed !

**Comment by jbrazio** [comment]
I believe we should have a margin of some sort when heating, from the log file the bed temp was always 0.1C before target and that can cause a wait forever situation. Maybe `TEMP_HYSTERESIS` is too much and we should use an hard coded value of 0.5/1C ?

If we simplify thermal management then in the future we could reuse it either we are dealing with an extruder, a bed or environment hot box.

**Comment by thinkyhead** [comment]
@jbrazio Well if the bed temperature is never reaching the target, then there's something amiss with the heating algorithm at the low level. The bed keeps heating until it gets to target temperature, then it stops heating at some point. Is the comparison at the low level to turn on/off the BED_PIN different enough from the target celsius temperature that it actually hovers below and never reaches or goes over? I'll have to take a look at the maths.

Another Q: Could the PID settings be off in a way to cause this?

**Comment by thinkyhead** [comment]
If that stuck bed issue really was due to the temperature never reaching the target, that would be a good job for the `PID_BED_DEBUG` feature. It logs the bed heating in real-time. Maybe it will expose a bug in the PID logic, or show something else about the bed itself.

**Comment by jbrazio** [comment]
OK I understand your point, a proper PID should _always_ reach the target.

**Pull request closed without merging**
