### PR TITLE
[2.0.x] Monitor chamber temperature, with auto fan control.

### PR DESCRIPTION
**Pull request by Lenbok**
[This is a port of #9789 to bugfix-2.0.x. I've given it some testing on my mendel90 with the auto fan temp threshold at 40 and it seems to be working nicely]

This is an initial cut for feedback and testing. There are probably nicer ways of doing some of this.

Chamber temperature is currently reported along with normal hot end and bed temperatures to serial. The format is just like that used for hot end and bed temperatures, but using 'C' prefix. As there is no heater, target is always 0. Is this appropriate, or is there a better way to report chamber temperatures? Octoprint doesn't seem to mind the extra (it just ignores it).

Chamber temperatures are not reported on the LCD in any way.

When auto chamber fan is enabled, it currently just uses the same temperature threshold as the other auto controlled fans. I could imagine you may want the chamber temp set a little lower than the extruder auto fans? (you certainly wouldn't want it higher).

As the chamber temperature is not connected to any heater, it doesn't undergo mintemp/maxtemp monitoring. This would need to change in the future if active chamber heating became a feature.

### CODE REVIEW

**Comment by boelle** [comment]
@Lenbok awesome that this has been added

would be cool if it was reported to LCD and that it could have its own settings for target temp and a fan to stir the air arround a bit

i too have the mendel90 and have this enclosure: 

https://www.thingiverse.com/thing:755654

**Comment by Lenbok** [comment]
@boelle Regarding separating the chamber fan temp threshold from the hotend fan temp threshold, I didn't see much advantage -- I think it doesn't make sense to have chamber fan threshold > hotend fan threshold, and if you want it lower there doesn't seem to be a downside to just lowering the hotend fan threshold appropriately.

LCD would be nice, but things are pretty cramped (at least on my 4x20 LCD). I just glance at the Octoprint terminal output. I would rather have the chamber temp displayed in the octoprint graph than on LCD myself.

(That enclosure is the one I built too -- I really must add a photo to thingiverse)

**Comment by boelle** [comment]
but being able to control the chamber temp would be great right?

i can agree that if fitting a fan for the chamber it would not make much sense to control that seperate

**Comment by Lenbok** [comment]
I don't think you need to continually adjust it during a print like you do with bed and hotend, but it could make sense on a print by print basis (e.g. PLA vs ABS). But the same could be said of the hotend cooling threshold.

Active chamber heating would be nice (e.g. for people in cold environments), but it's a bigger jump up in work (extra heater to control, PID, UI, safety features etc), compared to the itch I needed to scratch :-)

**Comment by boelle** [comment]
i do both abs and pla

could always just add a 2nd extruder and use that to control the chamber, just need to replace the nozzle icon with a chamber like icon

**Comment by Lenbok** [comment]
That is totally the easiest way to be honest. (And us the current support for the cooling side if things get too hot)

**Comment by boelle** [comment]
i'm not a programmer, just venting out idea on how it could be done

but yes there has to be some way of letting out the air if temps get to high, but with pid tune i guess the risk of overshot is minimal

pid tune for the chamber has to allow for slower rise in temp than a hotend

@thinkyhead what do you think? would it be possible to reuse the hotend/extruder heating without **too** much trouble at your end?

**Comment by thinkyhead** [comment]
For this kind of feature you would be balancing a heater and/or fan to keep the temperature within some defined range. With the heater on the opposite side of the chamber from the thermistor, there would be such a long delay between heating and detection I doubt that a PID-loop would work very well. There's also the other components contributing heat, varying with workload, and stirring the air with constant motion. PID loops only work well when you have a consistent thermal mass, a reasonably short feedback cycle, and a predictable heat source.

**Comment by boelle** [comment]
makes sense

as for heating i found a small electrical heater for use in cars

image

**Pull request merged**
