### PR TITLE
Creality3D CR-20 configurations

### PR DESCRIPTION
**Pull request by m0oml**
### Description

Just Added Example Configs for Creality CR-20 and CR-20 Pro no change to main code 

Thanks to all the dev's doing real coding !

Trev

### CODE REVIEW

**Comment by thinkyhead** [comment]
Are users going to be expecting `FILAMENT_RUNOUT_SENSOR` and `POWER_LOSS_RECOVERY` to be standard with these machines?

**Comment by m0oml** [comment]
> Are users going to be expecting `FILAMENT_RUNOUT_SENSOR` and `POWER_LOSS_RECOVERY` to be standard with these machines?
They have no Filament sensor 

They do come with power loss recovery, however it had never worked for me so i didn't include it

**Comment by thisiskeithb** [comment]
The CR-20 Pro has a filament runout sensor.

Edit: I guess it depends on when/where you bought one. Not all of them come with the runout sensor. 🤷‍♂️

**Comment by kaista82** [comment]
@m0oml Thanks for doing this, however I tried flashing my CR-20 with your configuration (hoping to enable BLTouch v3.1 afterwards) but it inverted all the steppers and ran off the top right of the bed immediately, have you got any advice that I could use? it would be much appreciated.

**Comment by thisiskeithb** [comment]
The[ Ender 5](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/config/examples/Creality/Ender-5/Configuration_adv.h#L1809) & [Tarantula Pro](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/config/examples/Tevo/Tarantula%20Pro/Configuration_adv.h#L1805) configs were also updated incorrectly and should be reverted back to `CHOPPER_DEFAULT_24V`.

**Pull request merged**
