### PR TITLE
Bugfix 2.0.x

### PR DESCRIPTION
**Pull request by aznevanchoi**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### CODE REVIEW

**Comment by boelle** [comment]
@aznevanchoi maybe do a description ?? i dont know what this PR is about

correct the first post with a description

**Comment by aznevanchoi** [comment]
sorry about that

**Comment by boelle** [comment]
@aznevanchoi did you submit a PR or did you make a mistake?

anyway please edit description in first post

**Comment by boelle** [comment]
@aznevanchoi so what is this? a PR or ????

**Comment by boelle** [comment]
ahhhhh now i got it, you want to update 1.1.x so it has the same fix's as 2.x ?

**Comment by boelle** [comment]
@aznevanchoi anyways i can see that one check is failing:

image

 and at least these files are in conflict:

image

**Comment by aznevanchoi** [comment]
sorry mistake

**Comment by boelle** [comment]
what is mistake?

**Pull request closed without merging**
