### PR TITLE
G28: simplify code and avoid warning & error with UBL

### LINKED ISSUE #20478: [BUG] RESTORE_LEVELING_AFTER_G28 causes errors and warning in bugfix-2.0.x
### Bug Description

The following combination of commented and uncommented lines causes a failure to compile.

```
#define RESTORE_LEVELING_AFTER_G28
//#define ENABLE_LEVELING_AFTER_G28
```
with the error

Marlin\src\gcode\calibrate\G28.cpp:438:62: error: 'leveling_was_active' was not declared in this scope; did you mean 'leveling_is_valid'?

### Configuration Files

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5696991/Marlin.zip)

### Steps to Reproduce

1.Compile with noted lines commented and uncommented
2.Note failure

**Expected behavior:**

Successful compile

**Actual behavior:**

Error as noted above or possibly sanity check error

#### Additional Information

```
//#define RESTORE_LEVELING_AFTER_G28
#define ENABLE_LEVELING_AFTER_G28
```

Gives the somewhat concerning warning:

Marlin\src\gcode\calibrate\G28.cpp: In static member function 'static void GcodeSuite::G28()':
Marlin\src\gcode\calibrate\G28.cpp:244:16: warning: unused variable 'leveling_restore_state' [-Wunused-variable]
  244 |     const bool leveling_restore_state = ENABLED(ENABLE_LEVELING_AFTER_G28) || TERN0(RESTORE_LEVELING_AFTER_G28, planner.leveling_active);
      |                ^~~~~~~~~~~~~~~~~~~~~~

Commenting out both lines also results in a failure

### PR DESCRIPTION
**Pull request by tpruvot**
defining RESTORE_LEVELING_AFTER_G28 or ENABLE_LEVELING_AFTER_G28 to true/false doesn't make sense.

Rewrite the G28 leveling restoration code to avoid the unused var warning...

In config, just define RESTORE_LEVELING_AFTER_G28 or ENABLE_LEVELING_AFTER_G28, or... none of them

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Related Issue: https://github.com/MarlinFirmware/Marlin/issues/20478

**Comment by tpruvot** [comment]
by the way, if you could define RESTORE_LEVELING_AFTER_G28 in config/examples/Alfawise/U20-bltouch/Configuration.h
tx...

**Comment by thisiskeithb** [comment]
> by the way, if you could define RESTORE_LEVELING_AFTER_G28 in config/examples/Alfawise/U20-bltouch/Configuration.h
> tx...

Feel free to submit a PR to the [Marlin Configurations repo](https://github.com/MarlinFirmware/Configurations) 🙂

**Review by sjasonsmith — APPROVED** [review]

**Comment by ETE-Design** [comment]
@tpruvot Sorry to ask mabye a noob question... But really dosen't make sense for "New" people, so what is the difference of RESTORE_LEVELING_AFTER_G28 and ENABLE_LEVELING_AFTER_G28, think it confuses a lot of people that there are 2 instead of 1 option...

**Comment by tpruvot** [comment]
RESTORE_LEVELING_AFTER_G28 only keep the previous state... need a M420 S1 or G29 A in start gcode so

**Comment by ETE-Design** [comment]
@tpruvot And using only ENABLE_LEVELING_AFTER_G28 does it all so you don't need to add any in your start gcode? Mabye there should be put a text to it then so people know what to enable...
Also ENABLE_LEVELING_AFTER_G28 isen't for UBL then since you have to choose what slot you like to use?

**Comment by tpruvot** [comment]
will not pass days to discuss about that, was not the purpose of the commit, just a warning fix...

**Pull request merged**
