### PR TITLE
Patch for G29 final Z position

### PR DESCRIPTION
**Pull request by thinkyhead**
Include all the necessary pieces to get the final Z position after probing the bed, and add commentary about other possible changes.

### CODE REVIEW

**Comment by paulusjacobus** [comment]
@thinkyhead Please can you add some description to each of the variables like `z_temp` `z_real` so it becomes easier to understand?

**Comment by tonnico** [comment]
With an inductive Sensor we never execute something with `Z_RAISE_AFTER_PROBING` but we can set this in the config. In that case we will get a problem.

**Comment by Natealus** [comment]
Hehe my `Z_RAISE_AFTER_PROBING` has never actually done that movement … it's only screwed with the bed leveling numbers and my manual z height (later is already fixed though). I have since added a 50mm raise and then a return-to-center to my starting G-Code so it accomplishes the intention. I enacted it when my nozzle tore up my kapton tape moving from too low an angle down to 100 micron position starting height. So I decided to let it raise and center first then go to print.

```
G1 Z50 F6000
G1 X0 Y0 F9000
```

**Comment by tonnico** [comment]
Yes, but with that PR it is necessary to set it to 0 in that case to have no issues.

**Comment by AnHardt** [comment]
A dependency on `SERVO_ENDSTOPS` could be the way to go. (https://github.com/MarlinFirmware/Marlin/issues/2412#issuecomment-120712475)

or in `SanityCheck.h`

``` cpp
#ifndef SERVO_ENDSTOPS
  #undef Z_RAISE_AFTER_PROBING
  #define Z_RAISE_AFTER_PROBING 0
  #undef Z_RAISE_BEFORE_PROBING
  #define Z_RAISE_BEFORE_PROBING 0
#endif
```

or making the definition of `Z_RAISE_AFTER_PROBING` and `Z_RAISE_BEFORE_PROBING` dependent on `SERVO_ENDSTOPS` in `Configuration.h`.

Logically these two should be renamed to `MIN_SERVO_ENDSTOPS_DEPLOY_DISTANCE` and `MIN_SERVO_ENDSTOPS_RETRACT_DISTANCE` and moved to the servo (servo-endstop) section.
Cant see the difference now. Both should have the same value. Maybe a per axis setup like the servo-angles makes more sense.

While we are in that area of `Configuration.h` - Defining options for `G28` (Homing) inside the block (and dependent on) for `G29` looks a bit unclean. Should the definition of `Z_RAISE_BEFORE_HOMING` and `Z_SAFE_HOMING` get their own place? Both are pretty independent of ABL and servos.

Uhh. A lot of new ideas. :-)

**Comment by Roxy-3D** [comment]
I hate to further complicate things...   But one of our tests going forward should be that G28 and G29 report similar numbers when they think they have done their work.   If the nozzle is moved to the same location, at the end of both the G28 and G29 the M114 command should report the same thing.  I don't know if this has been resolved with this change, but it is something we should keep an eye on.

The fact that this did not happen in the past caused a lot of support issues.   But not having this be the case also limits future development.   For example, saving the Bed Level Correction Matrix to EEPROM so just a G28 is necessary to start printing is much more problematic to the user.   They can start the printer, it gets the G29 information from EEPROM, but the nozzle is offset too much to use directly.

**Comment by Wackerbarth** [comment]
"G28 and G29 (should) report similar numbers when they think they have done their work." --
I think that we are looking at this from the wrong point of view. All we should care about is that the machine KNOWS where it is at all times (after power up homing) and that it has the appropriate coefficients to convert between coordinate systems.

In particular, consider two separate coordinate systems. I'll call the first the "frame" and the second the "bed" (or "object").

Initially, on power up, we don't KNOW where the nozzle is located. However, by performing a homing sequence, when the mechanism "bumps" the registration switch, we then know the position of the actuator in the "frame" reference.

Additionally, we have some transformation function (in the simplest case, just a linear translation) to convert to the "bed" reference. (When against the limit switch, the X axis is at some configurable, essentially constant, value). If we track EVERY motion, then we know the current position of the nozzle.

The effect of running a G29 is to compute a correction to the transformation. If things are properly calibrated, the G29 would compute zero as the appropriate correction.  However, note that applying this correction DOES NOT MOVE the nozzle. It only changes the manner in which subsequent positions are transformed from the "bed" coordinates to the "frame" coordinates.

If we track the nozzle in "frame" coordinates, actions such as raising the nozzle to provide clearance for probe deployment, or deploying and/or retracting a sled/AllenKey probe do not change the fundamental tracking. As a result, for the purpose of continuing, we really don't care WHERE the nozzle ends up. The important thing is that we have kept track of it and, therefore, KNOW, where it is. From that we can compute the appropriate motion to get to a desired "bed" location to begin printing.

**Comment by thinkyhead** [comment]
> With an inductive Sensor we never execute something with `Z_RAISE_AFTER_PROBING`

I would expect `Z_RAISE_AFTER_PROBING` to be 0 for such setups. Basically the `Z_RAISE_*_PROBING` settings all exist for the same reason – to provide clearance for the probe to deploy (`Z_RAISE_BEFORE_PROBING`), stow (`Z_RAISE_AFTER_PROBING`), and move between probe points (`Z_RAISE_BETWEEN_PROBINGS`).

Admittedly this puts the onus on the user to figure out the best values for all three. For a probe that has no servo (or which raises/lowers the probe straight up/down) the `BEFORE` and `AFTER` values can be 0 – but then there may be inductive probes where a lift before probing helps.

It would be nice if instead we could just have a `PROBE_EXTRA_CLEARANCE` value that just describes how much extra lift is needed for the probe to have room for deploy/stow. Then we could use that value to replace `Z_RAISE_BEFORE_PROBING` and `Z_RAISE_AFTER_PROBING`.

**Comment by thinkyhead** [comment]
> A dependency on `SERVO_ENDSTOPS` could be the way to go.

@AnHardt We can certainly add an additional sanity check in that case, but… perhaps there are non-servo probes (inductors) that benefit from a little extra clearance before beginning the probe…?

Personally, I'm not too fond of `SERVO_ENDSTOPS` as a setting, in part because I have yet to see any XY servo endstops in use, and I'm not too sure Marlin supports them very well. And the name is also confusing because the Z probe isn't necessarily an endstop – it may a totally different switch from the Z endstop. So eventually I would like to do some cleanup of the probes + endstops code to make it clearer.

**Comment by thinkyhead** [comment]
> Should the definition of `Z_RAISE_BEFORE_HOMING` and `Z_SAFE_HOMING` get their own place?

@AnHardt Currently these both depend on `ENABLE_AUTO_BED_LEVELING`, but you're right, they could exist without it, and bed leveling isn't really the primary reason for them. Servo endstops is the reason for them… sort of. But, let's take a look where `Z_RAISE_BEFORE_HOMING` is used now:
- `M401` and `M402` will call `raise_z_for_servo` if `SERVO_ENDSTOPS` exists. The logic in `raise_z_for_servo` is dubious, but it basically tries to move Z by `Z_RAISE_BEFORE_HOMING`.
- If `Z_SAFE_HOMING` is off, a non-delta `G28` (that's homing Z to a min endstop) will use `Z_RAISE_BEFORE_HOMING` _before_ homing XY or Z.
- If `Z_SAFE_HOMING` is on, a non-delta `G28` or `G28 XYZ` will use `Z_RAISE_BEFORE_HOMING` _after_ homing XY, as part of the move to a safe XYZ, before finally homing Z.
- If `Z_SAFE_HOMING` is on, a non-delta `G28 Z`, `G28 XZ`, or `G28 YZ` will use `Z_RAISE_BEFORE_HOMING` before homing Z.

The `Z_SAFE_HOMING` setting implies reliance on `ENABLE_AUTO_BED_LEVELING` because of the handling of `G28 Z`, `G28 XZ`, and `G28 YZ`. If you issue one of these commands when XY are known then there is an additional check to make sure the probe is within the movement region. If the probe is not in a usable position you will get a **Z probe out. bed** error.

**Comment by lrpirlet** [comment]
Please read my answer in #2040

**Pull request merged**
