### PR TITLE
Update Danish language pack

### PR DESCRIPTION
**Pull request by boelle**

### CODE REVIEW

**Comment by jbrazio** [comment]
@boelle please use more descriptive **commit messages** like "Update Danish language pack" or "Initial update of the Danish language pack". Titles we can change/edit but commit messages we cannot.

**Comment by thinkyhead** [comment]
> Titles we can change/edit but commit messages we cannot. 

Well, we _can_ edit commit messages, but we have to make a copy of the branch and submit a new PR to do it.

**Comment by thinkyhead** [comment]
@boelle The Germans did a lot of work, and quite a challenge it was, to reduce string lengths to 18 characters or less, with the most important part of the strings in the first 16 characters, as this is the minimum width of the screen. Ideally, we want to make these LCD display strings 16 characters at the most.

Strings over 20 characters are a complete waste, as we will never display the additional characters (at least not until all LCD messages are scrolling). Characters past 20 are just wasted bytes, so you might as well cut the strings off at 20.

**Comment by Roxy-3D** [comment]
> (at least not until all LCD messages are scrolling)

Yikes!  More CPU cycles to scroll!  At least the Full Graphics Panels won't
need to be scrolling.  Those are the biggest pigs of CPU cycles.

Seriously....   This is yet another example why we need to get the 32-Bit
support in place.   We need the horse power to deal with these kinds of
problems.

**Comment by thinkyhead** [comment]
> need the horse power to deal with these kinds of problems.

It will help. But of course, we might still have to backward-support slower hardware — at least if the 32-bit version is the same code-base as this Marlin. But I expect we will be making a whole separate repo for the 32-bit version.

**Comment by jbrazio** [comment]
> making a whole separate repo for the 32-bit version

IMO we shall decide after refactoring the existing code and looking at the HAL.

**Pull request merged**
