### PR TITLE
Z Clearance rather than Height

### PR DESCRIPTION
**Pull request by thinkyhead**
**Background:** Nozzle-relative "height" settings have turned out to be bothersome for maintainers / user support, as we have to repeatedly explain that they are nozzle-relative (i.e., fixed Z coordinates) rather than a raise over the position of the probe's trigger-point (and so the probe Z offset needs to be added onto the "height"). Moreover, "height" values don't adjust for changes made by `M851`, and this also seems counter-intuitive.

**Solution:** This PR reverts back to the use of "raise" approach, which –quite simply– makes these values relative to the probe trigger-point as set by `M851` and/or the default probe Z distance, and not to the tip of the nozzle. Thus it is much less likely that the values will be set too low, resulting in too small a raise or no raise at all and generating a complaint.

Returning to "raise" options also makes it easier to upgrade from Marlin 1.0.2 and earlier, which have been using "raise" values. So this is one less thing to which end-users will have to pay diligent attention.

**Caveats:** Yes, users with servo probes need to account for the space required to deploy and stow the probe. But that's exactly why the deploy/stow setting exists, and we already sanity-check to ensure that neither of these settings is zero.

The names have been changed to use `Z_CLEARANCE` as the prefix:
### Upgrading from Marlin 1.0.2-1
- `Z_RAISE_BEFORE_PROBING` / `Z_RAISE_AFTER_PROBING` => `Z_CLEARANCE_DEPLOY_PROBE`
- `Z_RAISE_BETWEEN_PROBINGS` => `Z_CLEARANCE_BETWEEN_PROBES`
### Upgrading from Marlin 1.1.0-RC6 (and earlier RCs)
- `Z_RAISE_PROBE_DEPLOY_STOW` => `Z_CLEARANCE_DEPLOY_PROBE`
- `Z_RAISE_BETWEEN_PROBINGS` => `Z_CLEARANCE_BETWEEN_PROBES`
### Upgrading from Marlin 1.1.0-RC7
- `Z_PROBE_DEPLOY_HEIGHT` => `Z_CLEARANCE_DEPLOY_PROBE`
- `Z_PROBE_TRAVEL_HEIGHT` => `Z_CLEARANCE_BETWEEN_PROBES`

Reverting to the `RC6` (and earlier) names is also an option, to ease transition for those who may have been playing along.

### CODE REVIEW

**Comment by lrpirlet** [comment]
@thinkyhead 
I really like the very clear explanation given in this PR... Thanks. 

Move from previous version should be smooth and easy using it. Any way to make changes such as this one, outlined in this PRs, into some sort of documentation easely found?

If not, as soon as this PR is merged and then closed, the doc will be gone... unless there is a github search... I was not able to define a good search that would point this PR :-(

**Comment by thinkyhead** [comment]
> some sort of documentation easely found

If you try to build using a previous configuration the SanityCheck will explicitly tell you what to change. That should do the trick.

**Comment by lrpirlet** [comment]
@thinkyhead

``` C++
 // Minimum heights for the probe to deploy/stow and travel.
  // These values specify the distance from the NOZZLE to the BED.        // These values specify the distance from the NOZZLE to the BED.
  //          //
 -#define Z_PROBE_DEPLOY_HEIGHT 15 // Z position for the probe to deploy/stow        +#define Z_RAISE_DEPLOY_PROBE   10 // Z Raise for Deploy/Stow
 -#define Z_PROBE_TRAVEL_HEIGHT  5 // Z position for travel between points       +#define Z_RAISE_BETWEEN_PROBES  5 // Z Raise between probe points
```

**Comment by lrpirlet** [comment]
@thinkyhead
Are we sure we want to keep the same explanation in the Configuration.h???

I guess that it should read something like 
`These values are the additional (or relative) distance needed to stow or move safely`

**Comment by thinkyhead** [comment]
``` cpp
/**
 * Z probes require clearance when deploying, stowing, and moving between
 * probe points to avoid hitting the bed and other hardware.
 * Servo-mounted probes require extra space for the arm to rotate.
 * Inductive probes need space to keep from triggering early.
 *
 * Use these settings to specify the distance (mm) to raise the probe (or
 * lower the bed). The values set here apply over and above any (negative)
 * probe Z Offset set with Z_PROBE_OFFSET_FROM_EXTRUDER, M851, or the LCD.
 * Only integer values >= 1 are valid here.
 *
 * Example: `M851 Z-5` with a RAISE of 4  =>  9mm from bed to nozzle.
 *     But: `M851 Z+1` with a RAISE of 2  =>  2mm from bed to nozzle.
 */
```

**Pull request merged**
