### PR TITLE
Remove "Cmd:" from messages in BLTouch menu

### PR DESCRIPTION
**Pull request by ghost**
### Description

This removes "Cmd:" from the beginning of the BLTouch Menu items.

### Benefits

This makes the options in the BLTouch menu look nicer and easier to read.

### Related Issues

N/A

### CODE REVIEW

**Comment by thisiskeithb** [comment]
The other language files will need to be updated as well.

**Comment by ghost** [comment]
Hi Keith, I got them all now.

**Comment by ghost** [comment]
Thank you for merging my pull request, sorry I didn't realize it was mentioned in Configuration_adv.h.

**Comment by thinkyhead** [comment]
n/p I always look for loose ends.

**Pull request merged**
