### PR TITLE
Touch Buttons variable repeat delay

### PR DESCRIPTION
**Pull request by robbycandra**
This PR effect the FSMC GRAPHICAL LCD.

If we use FSMC GRAPHICAL LCD. we have touch encoder button. 
For editing value like fan speed / Feedrete, it is convinience if encoder loops fast.
For moving between menu item or moving axis, Fast encoder loop is trouble.

This PR manage delay if touch button pressed by add ui.touch_delay and ui.screen_mode

ui.screen_mode will also usefull for later development of this FSMC GRAPHICAL TFT. Using ui.screen_mode we can activate touch area directly at menu_item location.

### CODE REVIEW

**Comment by robbycandra** [comment]
@tpruvot, check it out.

**Comment by Ludy87** [comment]
please do not change the config files with your settings!

**Comment by robbycandra** [comment]
@Ludy87 , thanks. fixed.

**Comment by thinkyhead** [comment]
I have reduced this down to the essentials since the other screen modes are not yet in play. As we get better native support for higher-resolution displays we can revisit the concept of screen modes. It may be useful for other behaviors in future.

**Pull request merged**
