### PR TITLE
[2.0.x] Malyan M200 LCD support

### PR DESCRIPTION
**Pull request by xC0000005**
This adds support for Malyan M200 LCDs, which are a separate ESP8266 MCU running on Serial1. Most of the commands are simple transations to gcode which are then injected. The exception is print menu support, which requires unique formatting for files and directories.

### CODE REVIEW

**Comment by xC0000005** [comment]
I thought I squashed this correctly so it wouldn't show a zillion commits. I'll re-do this when I figure out how to fix it.

**Comment by xC0000005** [comment]
Reopening since no matter what I do it shows the same history and changed files. Only the MalyanLCD, Configuration.h and ultralcd.h files are meant to be part of this, but there's something odd going on with the case of the readme.

I've tested this on V1 and V2 LCDs with decent results, though I think the print time counter is still wrong.

**Comment by Injineers** [comment]
with this now, can i run the minis Lcd on a ramps? Sorry if I am off base.

**Comment by xC0000005** [comment]
That’s correct. AUX1 on a RAMPS 1.4 board provides 12V and Serial1 access. You want to run a buck converter off of the 12V to convert to 3.3v and power the low side of a 5v to 3.3v level shifter (you’ll need to power the other side from another convenient +5/ source). Then take the cable that connected to the old Mini mainboard, wince, and cut it in half. If you look at the pinouts, you’ll note that the black and red cables (at least on all three of mine) are the opposite of what you expect - black goes to the buck converter’s +, red to the -. Don’t be like me and kill an LCD by wiring it up backwards. From there, TX & RX go to the level shifter, the level shifter’s 5v side goes to Serial1 (AUX1)’s TX & RX.

**Comment by Injineers** [comment]
Nice, Now I just need to take @robin7331 work on the LCD FW & change the UI around...

**Comment by AnHardt** [comment]
> That’s correct. AUX1 on a RAMPS 1.4 board provides 12V and Serial1 access.

12V? 5V!

**Comment by xC0000005** [comment]
You are correct. There’s another that is the 12. Sorry.

**Comment by thinkyhead** [comment]
> Reopening since no matter what I do it shows the same history and changed files.

I'll fix it and push to your branch later today.

**Comment by thinkyhead** [comment]
Unable to update your branch, so I've made a new PR at #9470.

**Comment by xC0000005** [comment]
Perfect, thanks. I’ll go over it. I see now - if I add a config option it needs to be added to all config files. Sorry, I’ll make sure to do that if I add more options.

**Pull request closed without merging**
