### PR TITLE
Fix redraw in SD Card menus

### PR DESCRIPTION
**Pull request by thinkyhead**
Addressing #5335

### CODE REVIEW

**Comment by ghost** [comment]
I've confirmed that "current contents of those lines will still be visible" has been solved with
```
root
├ System Volume Information\ (hidden)
├ test\
│    └ UltimakerRobot_support.gcode
├ test2\
├ test3\
├ test4\
└ Leveling.gcode
```
.
Probably it's all right...

**Comment by thinkyhead** [comment]
@esenapaj Can you also confirm that on regular menu screens (on character display) going from a longer menu to a short menu (are there any <4 lines long?) doesn't leave any residue? I'm thinking I should probably also change `LCDVIEW_CALL_REDRAW_NEXT` to `LCDVIEW_CLEAR_CALL_REDRAW ` in `lcd_goto_screen`.

**Comment by ghost** [comment]
>from a longer menu to a short menu (are there any <4 lines long?)

Like this?
It looks like that it's no problem.

| Enter root of menu | Enter "Prepare" menu | Return to root | Enter "Control" menu | Return to root |
| :-: | :-: | :-: | :-: | :-: |
dscn1784 | dscn1785 | dscn1786 | dscn1787 | dscn1788

**Comment by ghost** [comment]
~~Please wait. I'm seeing broken displaying in SD menu with GLCD now.~~
__Sorry, I tested this with plane RCBugFix mistakenly. Whis this PR, it's no problem.__

**Comment by ghost** [comment]
>I should probably also change to `LCDVIEW_CALL_REDRAW_NEXT` in `lcd_goto_screen`.

It looks like that `LCDVIEW_CALL_REDRAW_NEXT` is already used in `lcd_goto_screen`.
https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/ultralcd.cpp#L414

**Comment by thinkyhead** [comment]
> It looks like that … is already used

Sorry, I was copy-pasting, and I meant to say we should use `LCDVIEW_CLEAR_CALL_REDRAW` instead of `LCDVIEW_CALL_REDRAW_NEXT`. It will only affect character displays.

**Comment by thinkyhead** [comment]
> It looks like that it's no problem.

Ah, well if it's not a problem then…

**Pull request merged**
