### PR TITLE
Add Laser Cutter Air Assist Feature

### PR DESCRIPTION
**Pull request by descipher**
### Description

Add Air Assist Menu and separate M8/M9 trigger.

### Requirements

LCD display, any  2004 or 12864 based. 

### Benefits

Allow users to control a laser based air assist compressor using the menu and gcodes M8/M9 separately from COOLANT_FLOOD when AIR_ASSIST is defined. Simplify users configuration of the feature.

### Configurations

#define LASER_FEATURE
#define AIR_ASSIST
#define AIR_ASSIST_PIN  number
#define AIR_ASSIST_ACTIVE LOW or HIGH

#define REPRAP_DISCOUNT_SMART_CONTROLLER

### CODE REVIEW

**Comment by descipher** [comment]
Re-tested,  passed.

**Comment by descipher** [comment]
Note: Since I added buildroot tests it will expect a pin to be defined for AIR_EVACUATION and AIR_ASSIST.

**Comment by thinkyhead** [comment]
Then the test will need to define the pin too.

**Comment by descipher** [comment]
Submit a PR for it?

**Comment by thinkyhead** [comment]
Done.

**Comment by descipher** [comment]
:) Thanks

**Pull request merged**
