### PR TITLE
Add support for automated building of all configuration from Marlin's Configuration repository

### PR DESCRIPTION
**Pull request by X-Ryl669**
### Description

A very dumb, but I guess useful patch to add 2 scripts for building all the configurations found in [Marlin's Configuration](https://github.com/MarlinFirmware/Configurations) repository.
You'll run it via `buildroot/ci-check/build_all_configs.sh bugfix-2.0.x` and it'll download the configuration repository and start building all config it finds in there.

### Requirements

This requires [this feature request](https://github.com/MarlinFirmware/Configurations/issues/411) to be implemented, since, currently, the configuration repository does not contain the expected platformio environment to use for building the configuration.

### Benefits

Less breakage with new PR in Marlin's firmware, since one could then check that her PR does not break any configuration. 

### Configurations

None

### Related Issues

https://github.com/MarlinFirmware/Configurations/issues/411
#20985 where Victor requested such test.

### CODE REVIEW

**Comment by thinkyhead** [comment]
This is a helpful illustration, but I'm not sure how often it will be useful to build all configs from the top down.

It will, however, be useful to add a GitHub workflow / action to automate the deployment of pre-built binaries for all the examples and post them in a separate branch (in the Configurations repo) for easy access. It's possible to add a workflow / action (to the Configurations repo) which would do the builds on the GitHub servers, and only kick it off with a ping to the server (rather than tying it to a push or a merge).

The idea would be to first make a copy of the deployment branch (e.g., copy `release-2.0.7` to `builds-2.0.7`) and then as each build completes copy the built `firmware.bin` (or `firmware.hex`, etc…) file into the config's folder. That ensures the binary and the configs are together in the same place and easy to compare to the configs alone.

**Comment by X-Ryl669** [comment]
I still have to sort out the mftest script so it's finished. I don't know how far can Github go to run bash script like these. I never set up CI more than the basic "build my stuff and scream upon error".

**Comment by X-Ryl669** [comment]
My initial idea was to ensure that, when doing large codebase refactoring (like the serial stuff, but I'm also preparing a RGB led strip refactoring too), we could run this once before merging. Even if it does not guarantee the new code works, at least it'll avoid the zillion of "don't build for me" issues.

**Comment by thinkyhead** [comment]
It will be a good addition to the script to be able to skip ahead to any configuration so that after you've patched something you'll be able to continue from where you left off.

**Comment by rhapsodyv** [comment]
Add binaries to the repo doesn’t seem a good idea. But maybe we can use GitHub actions artifacts: https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts

**Comment by thinkyhead** [comment]
> Add binaries to the repo doesn’t seem a good idea.

Most succinctly they can be attached to Releases in the Configurations repository.

**Comment by X-Ryl669** [comment]
Maybe it'll be a good idea to display the created temp folder path so the user can jump in to fix stuff that does not build. Also, removing the .git subfolder is not a good idea IMHO, because if the build is failing because of a missing configuration define, then having the .git folder allows to submit a PR directly. You can clone with option `--depth 1` if you want to avoid too much disk space.

If every build works correctly, then removing the temp folder in the end will remove the git subfolder too.

**Comment by X-Ryl669** [comment]
Arg... It does not work. Each time you're calling mktemp, it's generating a new temporary folder so you can't resume the script anymore. You can't `rm -r .git` because it's full of read-only files. `build_example` does not run either.
In fact, `mftest -a` does not work, since it requires `mfinfo` 

I'll open a PR for fixing this.

**Pull request merged**
