### PR TITLE
Use redraw flag for both types of LCD

### PR DESCRIPTION
**Pull request by thinkyhead**
This is an attempt to address #6790

Use the redraw flag that works with both displays.

Please test!

### CODE REVIEW

**Comment by Roxy-3D** [comment]
If it is more than likely this works...   Let's merge it now.   The reason being...  I'm going to do a full regression test on my stuff and if it is in the mix...  It will get well tested.

**Comment by thinkyhead** [comment]
Testing is good! This is harmless, if anything, so…

**Comment by Tannoo** [comment]
I had an issue with UBL editing screen blanking out at different points.
So, I put the `lcdDrawUpdate` back that was removed but changed it to `LCDVIEW_KEEP_REDRAWING`:
```
    float lcd_mesh_edit() {
      lcd_goto_screen(_lcd_mesh_edit_NOP);
      lcdDrawUpdate = LCDVIEW_KEEP_REDRAWING; 
      _lcd_mesh_fine_tune(PSTR("Mesh Editor"));
      return mesh_edit_value;
    }
```
Works fine now.

**Comment by Roxy-3D** [comment]
Tannoo is using a Graphical LCD Panel.

**Comment by thinkyhead** [comment]
@Tannoo That's just weird. Doesn't the call to `lcd_goto_screen` already set `lcdDrawUpdate = LCDVIEW_KEEP_REDRAWING` in the current code? That line in `lcd_mesh_edit ` should have zero effect, unless some code is calling `lcd_mesh_edit` while `current_screen` is _already_ equal to `_lcd_mesh_edit_NOP` — which would be a hackish abuse of the menu system.

The correct way to have an edit screen is to let the menu system handle all the details, setting a flag when it has a value ready for the client, or is ready to return control, not to try and grab hold of the menu system from the outside.

**Comment by Tannoo** [comment]
Ok. I have noticed that it's not completely corrected. The edit screen is flickering while turning the encoder. Something is fighting to control the screen.

**Comment by Tannoo** [comment]
I'm not going to hunt the issue down (most of the time my fixes aren't correct anyway). I was just telling you what I did to help me.

**Comment by thinkyhead** [comment]
The correct way to have an edit screen is to let the menu system handle all the details, setting a flag when it has a value for the client.

**Comment by thinkyhead** [comment]
@Roxy-3D I just added "live editing" for @Bob-the-Kuhn. This extends the menu edit items with callback so they do their callback on every controller event, not just when the value is finalized.

It occurs to me that we can use that to simplify much of the menu system now. For instance, you could show a simple value edit screen for a Z position, and the callback could call back to UBL.
```cpp
MENU_ITEM_EDIT_CALLBACK(int3, MSG_UBL_EDIT_Z,
  &mesh_edit_value, low_value, high_value,
  ubl.mesh_value_edited, true);
```
When an edit value completes, it goes back to the previous menu screen. If needed, that screen would test that a value was just edited and do any finalizing callback to UBL.

**Comment by Roxy-3D** [comment]
Is Bob's code hooked up and working?   It would be helpful to see how a working piece of code sets up the call back, uses it, and then turns it off when done.   Is the call back done at interrupt time?

**Comment by Bob-the-Kuhn** [comment]
Yes, I'm using it in PR #6797.  Works nicely.
```
    extern uint8_t case_light_brightness;
    extern void update_case_light();
    int case_light_brightness_int;

    void level_case_light() {
      case_light_brightness = (uint8_t) case_light_brightness_int;
      update_case_light();
    }
...
        case_light_brightness_int = case_light_brightness;
        MENU_ITEM_EDIT_CALLBACK(int3, MSG_CASE_LIGHT_BRIGHTNESS, &case_light_brightness_int, 0, 255, level_case_light, true);
```

I think I can simplify it by going to this since case_light_brightness & update_case_light() already exist.
```
extern uint8_t case_light_brightness;
extern void update_case_light();
...
MENU_ITEM_EDIT_CALLBACK(int3, MSG_CASE_LIGHT_BRIGHTNESS, &case_light_brightness, 0, 255,update_case_light, true);
```

**Comment by Roxy-3D** [comment]
Great!   I'll review it and see if I can figure out how to transition to it...

**Comment by Tannoo** [comment]
@thinkyhead,

>@Tannoo That's just weird. Doesn't the call to lcd_goto_screen already set lcdDrawUpdate = LCDVIEW_KEEP_REDRAWING in the current code? That line in lcd_mesh_edit should have zero effect, unless some code is calling lcd_mesh_edit while current_screen is already equal to _lcd_mesh_edit_NOP — which would be a hackish abuse of the menu system.
The correct way to have an edit screen is to let the menu system handle all the details, setting a flag when it has a value ready for the client, or is ready to return control, not to try and grab hold of the menu system from the outside.

I understand that.
"Lemme show you something!"  -- Fire Marshal Bill


With this:
```
    float lcd_mesh_edit() {
      lcd_goto_screen(_lcd_mesh_edit_NOP);
      _lcd_mesh_fine_tune(PSTR("Mesh Editor"));
      return mesh_edit_value;
    }
```
https://drive.google.com/open?id=0B560i8PeUNErU2xHZDdNY01zQ1E


With this:
```
    float lcd_mesh_edit() {
      lcd_goto_screen(_lcd_mesh_edit_NOP);
      lcdDrawUpdate = LCDVIEW_KEEP_REDRAWING; 
      _lcd_mesh_fine_tune(PSTR("Mesh Editor"));
      return mesh_edit_value;
    }
```
https://drive.google.com/open?id=0B560i8PeUNErS0dXMVNXYVctbEU

**Comment by Tannoo** [comment]
I didn't have this issue before the LCD and ultralcd mods about a week ago.

**Comment by Tannoo** [comment]
>unless some code is calling lcd_mesh_edit while current_screen is already equal to _lcd_mesh_edit_NOP

That may be the case. I did have that also but took it out.
```
      void _lcd_ubl_map_lcd_edit_cmd() {
        //defer_return_to_status = true;
```
In that function, I am calling `G29 P4` and that, in turn, calls the edit screen.
I have found that it makes no difference on the edit screen refresh if this defer is set or not.

**Comment by Tannoo** [comment]
This is no different:
```
    void _lcd_mesh_edit_NOP() {
      defer_return_to_status = true;
    }
```
And, even if it were set, calling this from another screen should not affect the drawing of it, correct?

**Comment by thinkyhead** [comment]
@Tannoo

I think it's fine to insert a redraw flag if it gets the screen updating. The general issue that had me confused is that there are different approaches being taken, and `lcd_mesh_edit` is an unusual function in the lot that interact with the LCD. Since it's called repeatedly from outside the normal flow of LCD events, the normal order of drawing flags is disrupted. It would be cleaner to write a self-contained LCD screen handler that manages the Z editing and signals back to the `G29` or `G26` procedure when it's done, rather than using the call-and-return method currently employed.

In the long run, a Broadcaster/Listener or "component" system will be much cleaner, while reducing code complexity. A proper LCD API should fix all these draw issues once and for all, so that's near the top of the todo list.

There have been a lot of fixes, but at the moment there are still some little screen issues in `bugfix-1.1.x`. Still, it should be better in some areas. I didn't specifically address this `lcd_mesh_edit` screen issue, but let me know and I will add the `lcdDrawUpdate` if still needed.

**Comment by thinkyhead** [comment]
> This is no different: `void _lcd_mesh_edit_NOP`…

The reason we have a callback system for screens is so that drawing and event handling will take place at the right point in the program flow. The LCD code is written with the expectation that the active screen handler function will deal with encoder events and draw only when signaled or when internally determined. This predictable order allows drawing to be optimized for graphical displays, and so on. In this case that is subverted. `_lcd_mesh_edit_NOP` doesn't handle events and it doesn't draw anything, but only exists to disable the normal menu handler.

The proper implementation avoids these pitfalls because it works within the system instead of trying to subvert it. But it requires thinking differently — not in terms of controlling the LCD, but in terms of signing up to be a client of the LCD.

**Comment by Tannoo** [comment]
Yeah. I had almost forgotten about this.
I put it back on mine due to the edit screen not redrawing most of the time.

I agree that the lcd handling could be better. An LCD "traffic cop" would be beneficial.

Wether or not you add this back into the Marlin base, is up to you.
Apparently, not too many people are complaining about it.

**Pull request merged**
