### PR TITLE
Switching extruder (dondolo) without servo

### PR DESCRIPTION
**Pull request by EvilGremlin**
### Description

Allow flipping dondolo extruder in purely mechanical way, by bumping tollhead into gantry sides. Thought it was already there for ages, but apparently not. 
Maybe even expand for 3+ nozzles/extruders because why not? I can envision selector mechanicas for nearly infinite switching.
Should i add some tests?

P.S.: Config value changes that fail tests included intentionally for now.

### CODE REVIEW

**Review by ansonl — CHANGES_REQUESTED** [review]
@EvilGremlin Should `#define SWITCHING_NOZZLE_MECHANICAL` in Configuration.h actually be `#define MECHANICAL_SWITCHING_NOZZLE`? I'm testing your changes with the corrected wording of `MECHANICAL_SWITCHING_NOZZLE` with a Ultimaker DXU dual mechanical switching extruder/nozzle and it works well so far.

**Comment by EvilGremlin** [comment]
yep, Scott renamed it but forgot conf

**Comment by EvilGremlin** [comment]
I wanted more people to test it and give opinons on config options/descriptions, but i guess we'll have to fix it in post :)

**Comment by ansonl** [comment]
@EvilGremlin I'm waiting on a higher wattage PSU to fully test dual extruder functionality on my printer. 
Using `MECHANICAL_SWITCHING_NOZZLE ` the mechanical switching gcode that I have specified for tool changes work well with the T0/T1 commands. 

I did notice that there doesn't seem to be a way to reset the feedrate/speed of the printer to what it was after the toolchange g-code completes. If the printer was printing with movements at a slower or faster speed and a custom speed is specified in the toolchange g-code, I believe the custom speed will be used for movements after the toolchange until set again in the printing g-code. This affects the other switching methods as well but probably is more important for mechanical switching that uses toolhead movements itself. 

Since many mechanical switchers rely on gravity or springs, too slow or too fast of a movement speed inherited from the printing g-code may lead to a failure to properly switch due to friction (too slow) or mechanical stress (too fast?).

**Comment by EvilGremlin** [comment]
Oh, this is indeed a concern. You can't omit F in toolchange gcode because chances are you print too slow or too fast at a moment. Though usually you'd set up toolchange gcode with feedrate in slicer, and change from menu will use safe default feedrate. I will look into this.

**Comment by ansonl** [comment]
Do you know if there is an option in Cura to set toolchange speed? I couldn't find an option it makes sense since the slicer only calls T0/T1 to initiate the toolchange g-code which it lets the firmware handle. 

I checked a test print with dual extrusion generated by Cura which outputs the below commands before and after toolchange. 
```
G1 X48.45 Y139.1 E108.31521
G0 F5400 X48.65 Y139.1
G1 F1500 E101.81521
G1 F600 Z1.25
G92 E0
T0
G92 E0
M105
M109 S200
M104 T1 S0
G1 F600 Z0.25
```
Cura seems to specify the F for the printing command after the toolchange but I haven't looked into it enough to see if this is just coincidence. I haven't had any issues with varying movement speed for my switching mechanism with the current code which I think is ready for release but future improvement for ability to restore the previous F after toolchange would be a nice to handle all slicers.

**Comment by EvilGremlin** [comment]
No idea, i don't use cura and advise everyone to do so too. Don't it have toolchange gcode script?

**Comment by ansonl** [comment]
Not that I'm aware of, I just specify my 2 toolchange scripts in EVENT_GCODE_TOOLCHANGE_T0 and EVENT_GCODE_TOOLCHANGE_T1

**Comment by EvilGremlin** [comment]
well this is it, write whatever you need there

**Comment by ansonl** [comment]
I looked around some more and in Cura it is possible to set Extruder start gcode and Extruder end gcode for each extruder so it's similar to other slicers.

**Comment by DerAndere1** [comment]
> Do you know if there is an option in Cura to set toolchange speed? I couldn't find an option it makes sense since the slicer only calls T0/T1 to initiate the toolchange g-code which it lets the firmware handle.

IIRC, Marlin uses the feedrate specified by `XY_PROBE_FEEDRATE` (in Configuration.h) during tool changes. this is how it works internally: file tool_change.cpp has the line `REMEMBER(fr, feedrate_mm_s, XY_PROBE_FEEDRATE_MM_S);`

**Comment by DerAndere1** [comment]
I would suggest to change tool_change.cpp
```
      #elif ENABLED(SWITCHING_NOZZLE) && !SWITCHING_NOZZLE_TWO_SERVOS   // Switching Nozzle (single servo)
        // Raise by a configured distance to avoid workpiece, except with
        // SWITCHING_NOZZLE_TWO_SERVOS, as both nozzles will lift instead.
        if (!no_move) {
          const float newz = current_position.z + _MAX(-diff.z, 0.0);

          // Check if Z has space to compensate at least z_offset, and if not, just abort now
          const float maxz = _MIN(TERN(HAS_SOFTWARE_ENDSTOPS, soft_endstop.max.z, Z_MAX_POS), Z_MAX_POS);
          if (newz > maxz) return;

          current_position.z = _MIN(newz + toolchange_settings.z_raise, maxz);
          fast_line_to_current(Z_AXIS);
        }
        move_nozzle_servo(new_tool);
      #endif
```
to this:
```
      #elif ENABLED(SWITCHING_NOZZLE) && !SWITCHING_NOZZLE_TWO_SERVOS   // Switching Nozzle (single servo)
        // Raise by a configured distance to avoid workpiece, except with
        // SWITCHING_NOZZLE_TWO_SERVOS, as both nozzles will lift instead.
        if (!no_move) {
          const float newz = current_position.z + _MAX(-diff.z, 0.0);

          // Check if Z has space to compensate at least z_offset, and if not, just abort now
          const float maxz = _MIN(TERN(HAS_SOFTWARE_ENDSTOPS, soft_endstop.max.z, Z_MAX_POS), Z_MAX_POS);
          if (newz > maxz) return;

          current_position.z = _MIN(newz + toolchange_settings.z_raise, maxz);
          fast_line_to_current(Z_AXIS);
        }
        #if EITHER(MANUAL_SWITCHING_NOZZLE, MANUAL_SWITCHING_EXTRUDER)
          if (ENABLED(EVENT_GCODE_TOOLCHANGE_ALWAYS_RUN) || !no_move) {
            #ifdef EVENT_GCODE_TOOLCHANGE_T0
              if (new_tool == 0)
                gcode.process_subcommands_now(F(EVENT_GCODE_TOOLCHANGE_T0));
            #endif

           #ifdef EVENT_GCODE_TOOLCHANGE_T1
             if (new_tool == 1)
               gcode.process_subcommands_now(F(EVENT_GCODE_TOOLCHANGE_T1));
           #endif
         }
       #else
         move_nozzle_servo(new_tool);
       #endif
```

and change the original section dealing with  EVENT_GCODE_TOOLCHANGE_T# to something like this:
```
#if NONE(MANUAL_SWITCHING_NOZZLE, MANUAL_SWITCHING_EXTRUDER)
  if (ENABLED(EVENT_GCODE_TOOLCHANGE_ALWAYS_RUN) || !no_move) {
    #ifdef EVENT_GCODE_TOOLCHANGE_T0

...

#endif
```

**Comment by ansonl** [comment]
@EvilGremlin @DerAndere1 I modified toolchange.cpp to run the hotend Z offset adjustment after EVENT_GCODE_TOOLCHANGE is executed. I went with this for:
- portability of EVENT_GCODE_TOOLCHANGE gcode to execute in the context of the new hotend
- preserve Z_RAISE functionality
- adjust HOTEND_OFFSET for Z axis only after running EVENT_GCODE_TOOLCHANGE to prevent nozzle crash

EVENT_GCODE_TOOLCHANGE can't be earlier as suggested because the EVENT_GCODE_TOOLCHANGE gcode is written to be executed in the offset of the newly selected hotend. The gcode is executed in the "offset context" of the current hotend. If executed earlier, it uses the previous hotend offsets. With multiple extruders, it would be impossible for a single gcode string in EVENT_GCODE_TOOLCHANGE_T0 to handle all the possible hotend offsets that it could be switched from as seen below:
T1 (offset X19)-> T0 
T2 (offset X5)-> T0 
Even though I only have two extruders, that approach runs into printer bounds issues because the mechanical switch mechanism is at the edge of the printer. If printer X_MAX_POS is 216, my T1 (with offset X19) toolchange gcode will need to operate 19 mm outside of 216 at 216+9=235 to reach the mechanism when executed in T1's offset context where everything is shifted by 19. If T0 toolchange gcode is executed in the previous offset, the printer bounds must be configured outside of actual safe bounds for the toolchange to run and then the printhead will crash in to the side of the printer to adjust for new hotend offsets because the bounds had to be set outside the safe area. 

`#elif ENABLED(SWITCHING_NOZZLE) && !SWITCHING_NOZZLE_TWO_SERVOS   // Switching Nozzle (single servo)` wasn't actually used for MECHANICAL_SWITCHING already and it did not work properly so there is now a new section after it for mechanical switchers.

**Comment by EvilGremlin** [comment]
@DerAndere1 @ansonl added you as collaborators, you should be able to edit this now

**Comment by ansonl** [comment]
I let this patch run on a dual color print overnight and it came out well with a 6mm ooze shield. I think it is ready to merge into the main bugfix branch. Dual extrusion setup was Ultimaker Original+ DXU. 

IMG_7914
IMG_7916
UMO DXU dual extrusion print
IMG_7915
IMG_7917

**Comment by ansonl** [comment]
@thinkyhead Can you please review our changes for adding the mechanical switching nozzle/extruder?

**Comment by garufa01** [comment]
Hello @thinkyhead and  @ansonl , thank you for your effort and for soon merging into the main bugfix branch the Dual extrusion setup to use for the Ultimaker 2+ DXU in my case.

**Comment by ansonl** [comment]
@thinkyhead @thisiskeithb Bumping, do you have any availability to review this PR for merge? 
We can reduce the chance of code branches diverging if this 3 months ready PR is merged into the main branch (I've been using the code changes in 50 dual color prints without fail). This would fix nozzle collision issue #24758 and adds mechanical switching nozzle support. Thanks!

**Comment by thisiskeithb** [comment]
> @thinkyhead @thisiskeithb Bumping, do you have any availability to review this PR for merge?

Merging is up to thinkyhead, so we'll need to wait for him to review the PR.

**Comment by ansonl** [comment]
The toolchange effect seems to be broken in Marlin 2.1.2. I tried testing the commits in this PR https://github.com/MarlinFirmware/Marlin/pull/24553/commits
And something was added to Marlin after the 10/30 commit that causes the toolchange to collide with the gantry limits. I filmed the correct and incorrect toolchange and put the links in a bug #25117

**Comment by ansonl** [comment]
Turns out the problem was the current Marlin stepper.h and stepper.cpp code breaking compatibility with AVR/A4988 steppers. The toolchange part of this PR still works. This PR's latest commit has the mechanical switching extruder/nozzle code and is ready for review for merge into the main bugfix-2.1.x

**Comment by ansonl** [comment]
@thinkyhead Bumping, this PR is tested and ready to merge. Thanks.

**Pull request merged**
