### PR TITLE
Fix too cold in m600

### LINKED ISSUE #19073: [BUG] Filament runout when cold extruder
I faced a situation where printer is starting to print, filament is missing, but hotend is still cold.

Runout script is properly executed but it's aborted with a "hotend cold" error message, this error stop runout handling but the printer start to print.

Cause is 'filament_ran_out' variable, it is set once script commands are enqueued but none check if they are successful or not, then, in this case, M600 is aborted and never executed anymore...

My first approach may be to call a "reset" if M600 is aborted but another is to raise event only when extruder is really moving.

Any hint about the best solution?

### PR DESCRIPTION
**Pull request by GMagician**
Followup recent fixes to fix #19073.

### CODE REVIEW

**Comment by qwewer0** [comment]
I get the following warnings after the latest changes:
```
Marlin\src\feature\pause.cpp: In function 'void resume_print(const float&, const float&, const float&, int8_t, int16_t)':
Marlin\src\feature\pause.cpp:595:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
   if (targetTemp > thermalManager.degTargetHotend(active_extruder))
   ^~
Marlin\src\feature\pause.cpp:599:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     load_filament(slow_load_length, fast_load_length, purge_length, max_beep_count, true, nozzle_timed_out, PAUSE_MODE_SAME DXC_PASS);
```
`this 'if' clause does not guard... [-Wmisleading-indentation]`

**Comment by GMagician** [comment]
@qwewer0 I don't see such warning. Are you using platformIO?

**Comment by GMagician** [comment]
@qwewer0 try now. Not sure about last commit

**Comment by qwewer0** [comment]
No warnings now (at least not related to this), but I think I should have updated everything before opening my mouth...

**Pull request merged**
