### PR TITLE
TMCStepper 0.6.x is now Marlin-compatible

### PR DESCRIPTION
**Pull request by swilkens**
### Description
TMCStepper 0.6.0 released with connection errors on some platforms, release 0.6.1 fixes these issues.

### Benefits
Prevent TMCStepper connection errors on some platforms.

### Related Issues
https://github.com/teemuatlut/TMCStepper/issues/93

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I suggest simply requiring >= 0.6.1, to avoid the possibility of building with 0.6.0, which is broken for many people. This is just my opinion, it's ultimately up to thinkyhead what strictness he wants.

You should also update BIGTREE_SKR_PRO, LPC1768, and LPC1769 to use the same dependencies. The custom fork is no longer needed for the LPC boards, since @p3p's fix was merged into TMCStepper.

**Comment by sjasonsmith** [comment]
Also, a huge benefit of this is that it enables single-pin software serial on AVR.

**Comment by thinkyhead** [comment]
According to discussion on Discord the stepper constructors have been updated for full compatibility with TMCStepper 0.6.x yet.

**Comment by dezodude** [comment]
How do i install/use TMCSteppter 0.6.1?

**Pull request merged**
