### PR TITLE
[2.0.x] Led state on pid tuning

### PR DESCRIPTION
**Pull request by GMagician**
Move code to proper class this to be ready to integrate code for #11962 

I don't have leds so if code is approved it must be tested before merging

### CODE REVIEW

**Comment by thinkyhead** [comment]
Rebased, squashed, cleaned up, repaired, and modernized.

**Comment by thinkyhead** [comment]
The downside to this change is that it permanently eats up 5 more bytes of SRAM than the previous code, which used no SRAM. When it comes to SRAM, every byte counts.

**Comment by thinkyhead** [comment]
4 bytes of SRAM is saved by forcing the caller to keep the starting temp on the stack.

**Comment by GMagician** [comment]
@thinkyhead I was not expecting this to be merged, not right now, It was just an idea to the path I was going on to implement #11962.
My idea evolved to encapsulate into this class all the lighting options (hence change class name), like handling event when printer stops, terminate (that was already done but removed) and maybe also case lighting (don't see right now what this really means).
What do you think?

**Comment by GMagician** [comment]
I messed up my branch...close and open other... sorry

**Comment by GMagician** [comment]
Ok branch restore...sorry again

**Comment by thinkyhead** [comment]
This is coming along well, and it's nifty if it works with `M303` in some regard. I'm not sure what the LED colors should be during the test. I guess they've never been meant to indicate that the nozzle is too hot to touch (red) or at a safe temperature (blue), but rather just the proportion of heating that's been accomplished between the starting temperature and the target. So as long as it makes an interesting light show I suppose it's cool.

Because LED strips are often used as the printer's lighting, I don't think it makes sense to turn the LEDs off at the end of `M303`, but rather to set them back to white or to the same color and intensity they were at before `M303`.

I don't think it should be expanded to `CASE_LIGHT` since that is really meant to be separate from the indicator LEDs and only has a single color (with an optional brightness). An LED strip is already supposed to be used instead of `CASE_LIGHT` when you want configurable colored lighting.

**Comment by GMagician** [comment]
> I'm not sure what the LED colors should be during the test

me too, and since I still don't have any led strip I'm in situation where I can't test anything.
By the way I kept current coloring scheme used for bed and hotend and maybe @ruggb may tell us which best coloring scheme is better during pid

> I don't think it should be expanded to CASE_LIGHT since that is really meant to be separate from the indicator LEDs and only has a single color (with an optional brightness).

But maybe it can be expanded to handle leds when printer is stopped/paused and resumed (M0)
Since it just say "green", " white" or "off".

**Comment by GMagician** [comment]
@thinkyhead I apologize for my usual ignorance, what is the purpose of below reported change?

`#define SHV(S,B,H) do{ if (hotend < 0) S##_bed = B; else S [hotend] = H; }while(0)`

why is 'do while' cycle required and why is required now and not before

**Comment by thinkyhead** [comment]
It's not especially needed here, but just applied as a convention.

**Comment by GMagician** [comment]
@thinkyhead what about code in M0 and `get_sdcard_commands`. One turn off lights and  the other set a green+off? They are part of PRINTER_EVENT_LEDS then I may integrate them here, right?

**Comment by GMagician** [comment]
@thinkyhead am I wrong or you lost `LCD_MESSAGEPGM(MSG_INFO_COMPLETED_PRINTS);` with last modify?

another note about 'restore leds after pid tuning'. I think this can be done by using another SRAM variable (there is already a variable that store last color, only thing to do is enabled it with `PRINTER_EVENT_LEDS` and let it be readable by a INLINE property)
I may change this too if we want to add such variable...

**Comment by thinkyhead** [comment]
When a print completes, a `G31` is sent, and this is supposed to put the total print time on the LCD status line. So overloading the “Completed” message string should not be needed.

**Comment by thinkyhead** [comment]
I’m not sure what the best approach is to restoring LED color. It may not always be in a user-defined state when first saved.

**Comment by GMagician** [comment]
> I’m not sure what the best approach is to restoring LED color. It may not always be in a user-defined state when first saved.

Well I see that set_color may save last programmed color (and on off state) then reusing such code may be helpful. I'm already working on it but there is something I don't understood in led logic and I asked for help in a "issue" request

**Pull request merged**
