### PR TITLE
SKR Pro Neopixel support.

### PR DESCRIPTION
**Pull request by Evg33**
New Neopixel library with STM32 Core support.

### CODE REVIEW

**Comment by GMagician** [comment]
Not sure but new library (I checked SAMD51 one) increase a lot program memory because it adds some table to handle intensity (not sure because I checked some month ago).
I think 8 bits boards don't like it

**Comment by tpruvot** [comment]
please dont merge that like that, you left all the STM32F1 not in tests... but they will fail the same way. And should be optional for tiny flash ones...

**Comment by thinkyhead** [comment]
> …should be optional for tiny flash ones…

What more needs to be done with this PR before it is good?

**Comment by tpruvot** [comment]
just remove the F1 ones, well restore the ignore i mean.. Seems made for "HAL_STM32" not HAL_STM32F1

**Comment by tpruvot** [comment]
STM32F103R_fysetc need ignore, at least, maybe others are correct. mks_robin i guess too

**Comment by tpruvot** [comment]
https://github.com/adafruit/Adafruit_NeoPixel/commit/79a982a590a2c2b58a96790fea0de10b73e10e8e

**Comment by GMagician** [comment]
SAMD51 will benefit of this new library (it will support 400Hz that is currently NOP) but it may add some "jitter" on `millis` function:

> // SAMD51 overclock-compatible timing is only a mild abomination.
  // It uses SysTick for a consistent clock reference regardless of
  // optimization / cache settings.  That's the good news.  The bad news,
  // since SysTick->VAL is a volatile type it's slow to access...and then,
  // with the SysTick interval that Arduino sets up (1 ms), this would
  // require a subtract and MOD operation for gauging elapsed time, and
  // all taken in combination that lacks adequate temporal resolution
  // for NeoPixel timing.  So a kind of horrible thing is done here...
  // since interrupts are turned off anyway and it's generally accepted
  // by now that we're gonna lose track of time in the NeoPixel lib,
  // the SysTick timer is reconfigured for a period matching the NeoPixel
  // bit timing (either 800 or 400 KHz) and we watch SysTick->VAL very
  // closely (just a threshold, no subtract or MOD or anything) and that
  // seems to work just well enough.  When finished, the SysTick
  // peripheral is set back to its original state.

if I'm not wrong this lib will add 512byte of progmem:
`static const uint8_t PROGMEM _NeoPixelSineTable[256] = {`
`static const uint8_t PROGMEM _NeoPixelGammaTable[256] = {`

that in current lib is not defined. So some AVR users may not be so happy

**Comment by tpruvot** [comment]
maybe just do like the fysetc softwareserial... its possible to override a version in F4/F7 envs ?

**Comment by thinkyhead** [comment]
> if I'm not wrong this lib will add 512byte of progmem:

For cards with more than 256MB that's not a big deal. And, if your build is not within 512 bytes of overflowing your mega, then this is not in any way a problem.

**Comment by GMagician** [comment]
Of course not but this has been a problem in the past because a lot of tiny avr users had limited free memory

**Pull request merged**
