### PR TITLE
Fix LCD Menus + DAC compilation

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

Recent stepper DAC refactoring missed a related menu item.

After fixing that, I then had the following error, which is why I modified settings.cpp.:
`Marlin\src\module\settings.cpp:3794:102: error: #elif with no expression`

### Benefits

Allows compiling for boards with LCDs and Stepper DACs.

### Configurations

Configurations were adapted from bug #19216
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/5437092/Configuration.zip)

### Related Issues

#19216

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I have not tested this myself, hopefully @fiveangle can verify it, since it is based on their bug report.

**Comment by fiveangle** [comment]
Fixes resolves compile failure.  Unable to test on printer since it's not near, but based on the fix I don't see it being an issue.

**Comment by 0r31** [comment]
Hi @sjasonsmith ,

I also noticed some issues regarding DAC stuff. I have just created a pull request but i guess it is more convenient for reviewers if i integrate it in yours. Do you agree?

**Comment by sjasonsmith** [comment]
@0r31 mine just fixes a minor compilation issue. If yours is not directly related to my changes, I suggest you just post a new PR.

**Comment by 0r31** [comment]
Understood @sjasonsmith , thanks for your update.

**Pull request merged**
