### PR TITLE
Heating_Sanity_Check for the bed

### PR DESCRIPTION
**Pull request by AnHardt**
Add WATCH_TEMP_BED_PERIOD and WATCH_TEMP_BED_INCREASE to Configuration_adv.h
Modify setTargetBed() to call start_watching_heater_bed()
Use the there local variable current_temperature[} instead of the function degHotend(e) in start_watching_heater() in temperature.cpp
Add the new function start_watching_heater_bed() to temperature.cpp
Add the test to temperature.cpp

This test can detect a not heating heater, or a thermometer failing to detect the rising temperature of the bed.

For the moment the new test is turned off.
You can activate the test by setting WATCH_TEMP_BED_PERIOD != 0

### CODE REVIEW

**Comment by Wackerbarth** [comment]
"You can activate the test by setting WATCH_TEMP_BED_PERIOD != 0"

It is better to avoid using the VALUE of a parameter as the enabler.
Instead, have a separate selector, such as "ENABLE_BED_TEMP_MONITORING" and the "MONITORING_SAMPLING_INTERVAL".

That way a user can enable/disable the feature without having to know a "good" (default) value for the interval.  It also makes for a cleaner configuration description when we can separate the enabling options from the tuning parameters.

**Comment by AnHardt** [comment]
> For the moment the new test is turned off.
> You can activate the test by setting WATCH_TEMP_BED_PERIOD != 0

With emphasis on **For the moment**. As i have only data for 2 beds, it wold be a bit daring to activate it now for all. When we have a bit of experience with his, we can put in a reasonable default value.
Than his will be turned on an off like the identical feature for the extruders with commenting in an out of `#define THERMAL_PROTECTION_BED` in `Configuration.h`

**Comment by Wackerbarth** [comment]
I'm not suggesting that it be activated.  In fact, the default for EVERY feature should be DEACTIVATED.
All I am suggesting is that, from the start, you set things up so that it has the structure as you describe in your reply.  If you don't know any reasonable default value, then set the default to zero, or perhaps even -1 (with a comment indicating that the value is "to be determined" and add something to the sanity checks to alert if someone enables the feature without setting the value.

**Comment by thinkyhead** [comment]
> the default for EVERY feature should be DEACTIVATED

There's a strong consensus that Thermal Protection should be one of the features enabled by default, but of course there should be a wide enough margin so that only the most ridiculously slow heaters can throw false alarms.

**Comment by Wackerbarth** [comment]
Then the option should be DISABLE_THERMAL_PROTECTION

**Comment by thinkyhead** [comment]
> Then the option should be DISABLE_THERMAL_PROTECTION

Longstanding UX conventions hold that options —especially top-level— should be _positive_ (enabling the option enables a feature) rather than _negative_ (enabling an option disables a feature).

**Comment by Wackerbarth** [comment]
"Longstanding UX conventions hold that options —especially top-level— should be positive"
But, also, they should be FALSE by default. --
So "REMOVE_THERMAL_CONSTRAINTS", or such, if you prefer.

**Comment by AnHardt** [comment]
We need a upper test-temperature here.
A typical, a bit low powered, bed:
an_hour_with_the_slow_bed
minute 12-24: heating full power up to 130° in 12 minutes.
minute 24-29: PID with around 75% power.
minute 29: part-fan is switched on.
minute 29-32: bed is cooled down to 100° by the part-fan - heater-power 100%.
minute 32-33: heater switched off to cool down a bit.
minute 33-45: heater full on again to find the max-temp. with fan on.
minute 45: target temp set to a guessed max-temp. of 95°
minute 49: 95° reached. Heater-power was reduced a bit for a short while.
minute 55: Target temp. reduced to 94°.
minute 52-56: after a bit of undershoot the PID begins to work with 90-95%.
minute 56: part-fan switched off.

insight: An average (under powered) bed has a maximum temperature. The slope of the temperature curve will shrink to zero when reaching the maximum temperature.
As we test for the slope, to detect a heater failure, we must define a upper test temperature, to make sure we have some slope to measure.

**Comment by AnHardt** [comment]
Replaced by #2338

**Pull request closed without merging**
