### PR TITLE
Move grace period #define to config file for all hardware types

### PR DESCRIPTION
**Pull request by ghost**
Move the grace period #define to the config file to use on all hardware system types.

The very same ADC software low pass filters are used on all systems and their output's still need the exact same amount of time to converge to it's proper value.

The burning question is, why **_exactly_** is it needed on only the LPC1768 systems. If anyone knows the exact reason then please do share because this doesn't make sense at all ??

Is it possibly because the bootloader passes control over to the main software pretty much immediately on the LPC1768 systems as compared to the AVR bootloader, and so the thermistor filter caps (all system capacitors actually) are still charging up on power up when the main software begins to run ?   .. the AVR bootloader hangs around for a bit looking for possible serial comms, where as the LPC1768 bootloader does a very quick file check on the SD card, and if that firmware update file is not present, control is passed over to the main software there and then (pretty much no delay).

Either way, I think it's a bad idea to rely on that possible cause for this difference, or on any other possible hardware/boot-up differences on any other hardware setups.

Why are we not allowing the main software ADC LPF's time to settle on all systems, is their a bug there on non LPC1768 systems in the software ADC LPF's, are the software ADC  LPF's actually working on say the AVR systems ?

https://github.com/MarlinFirmware/Marlin/issues/14139

### CODE REVIEW

**Comment by gloomyandy** [comment]
I'm pretty sure that the lpc1768 includes additional filtering in either the hal or framework. That may be causing some of this. @p3p should be able to provide more information.

**Comment by p3p** [comment]
> The very same ADC software low pass filters are used on all systems and their output's still need the exact same amount of time to converge to it's proper value.

The LPC176x platform has considerably more filtering than other platforms, we had so much trouble with reports of erratic readings when we initially released support, the LPC176x mcu seems to be very sensitive to bad ground, interference and just bad wiring in general, myself and many others had no problems at all but we have to support the lowest common denominator hence the epic levels of LPF and an extra 23 value Median Filter.

Until the always active thermal protection was activated during boot this caused no issue and was pretty much invisible to users, just an implementation detail in the platform, by the time output started (screen/serial) the filters were normalised.

**Comment by ghost** [comment]
oh ok @p3p. thank you for the info, it's always good to know the causes and reasons for these things.

I still don't know my way round all of Marlin, their is a lot of code to go through. A little shared insight is invaluable when trying to help others with problems.

Thank you again for your reply, helps a great a deal.

**Comment by ghost** [comment]
The chinese have never taken gladly to using good PCB layout practices and proper decoupling/filtering on their cheap as can be boards, which of cause is no doubt the reason for these problems.

**Comment by thinkyhead** [comment]
This is ready to go… except that `THERMAL_PROTECTION_GRACE_PERIOD` is disabled in all example configurations. If we know good values for some boards/MCUs then we should enable this option and set a good value for those example configs.

**Comment by p3p** [comment]
@thinkyhead This setting is required for LPC176x builds only (because of extra filters) and at varying values depending on configuration upto about 4000ms it really needs to be enabled by default for that platform as the symptoms for it being configured wrong (or no thermistors are plugged in) are a seemingly dead board if there is no display, I can't think of any way to offer further feedback than we do but its pretty bad especially as the SKR boards don't even have a status LED.

**Comment by thinkyhead** [comment]
Sounds like it would be a good idea to have something like this…
```cpp
#ifndef THERMAL_PROTECTION_GRACE_PERIOD
  #define THERMAL_PROTECTION_GRACE_PERIOD 3000
#endif
```
…added to the HAL's conditional file which would be included at the right point in `MarlinConfig.h` (so each HAL would get more `Conditionals` files added). And then if a board needs to override, it can do the same thing in its `pins_BOARD.h` file (so the HAL's conditionals file included after the pins file).

And of course, the value set in `Configuration_adv.h` will supersede others.

**Comment by ghost** [comment]
Sounds good, it would give the user the ability to see that their is an option to adjust, because with it being hidden in the HAL file people don't know about it really, so I just thought it better for people to know about the setting and have it a little more easily accessible really.

I don't think it does any real harm to have a little time for ADC filtering bits and bobs to settle on any board really, but yes add it back into the HAL for sure as an added required back up for if the user doesn't define in the config file. A definite must have really now that I have more understanding about the exact reasons.

**Comment by ghost** [comment]
If people use the on-board bed heating MOSFET (not to mention the 5 motor drivers and other heater MOSFETs) then because the chinese don't do proper star type grounding in their PCB ground planes etc, you will get heavy currents circulating around the CPU and its sensitive analogue input pins, plus they don't put filtering caps near the CPU pins, they put them far away (if at all), plus users don't twist or screen their thermistor/sensor/motor wires, and also introduce unexpected grounding loops (easily done though) - all of which is what introduces the noise into the sensor readings.

**Comment by AnHardt** [comment]
How about initialising the extra LPC176x filters to a value between min and max instead of to an extreme?

**Comment by ghost** [comment]
I'm just looking to see if we have access to the HAL's median and low pass filter to pre-fill the buffers with a set value. If we do have access then yes that will solve the problem.

A way round it would be to move the HAL filter into Marlin code (wouldn't make any difference to operation) out of the HAL code and then we'd have the ability to pre-fill the filters.

**Comment by p3p** [comment]
There's currently no interface for initialising the values, The filter implementation is in the framework not the Marlin platform (although templated to allow configuration from Marlin), initialising them to a set (mid) value will will never fix the issue though may make it less common, I've been thinking about detecting a first ADC read filling the buffers with the median of few reads or reading until the value stabilises.

**Comment by ghost** [comment]
Yes I've noticed that.

Why does the framework return a 10-bit value from the 12-bit ADC ? .. it says it's doing it for Marlin

Surly that 12-bit to 10-bit resolution loss should have been done in Marlin and **not** the arduino LPC176x framework (as seen by all platformio projects)?

That's not right. Marlin is fairly insignificant compared to all the other LPC176x projects out there, and many of those projects use nicely designed hardware that isn't noisy like what Marlin uses.

**Comment by doggyfan** [comment]
> I've been thinking about detecting a first ADC read filling the buffers with the median of few reads or reading until the value stabilises.

That sounds like a whole lot more complicated and messy than simply waiting a couple of seconds for the filters to converge.

**Comment by ghost** [comment]
I also see people mentioning the noisy ADC/temperature problem they get on 8-bit boards, but Marlin provides no software filtering for 8-bit boards, just the LPC176x boards.

You could disable the framework LPC176x LPF simple processing and do it in Marlin to use as a general ADC LPF  (used on all platforms), which would also remove the need for the 16x over sampling being done (that can simply be done by not scaling the LPF output by so much (the K-Value)).

That would be a win-win situation, because you then have (**IF** you wanted too) the ability to pre-load the ADC LowpassFilter (single line of code) **and** the 8-bit users and other 32-bit platform users (STM32 etc) benefit from the basic LPF too, and _possibly_ use less CPU cycles for the 8-bit'ers too (no 16 over sampling code required). The median filter can be left in the LPC framework if that does it for you, though why not use that too for other platforms ?

**Comment by AnHardt** [comment]
At the AVRs we do a 16 times oversampling (OVERSAMPLINGNR) - what is a low pass filter.

Cutting down ADC samples from 12 to 10 bits does not really matter - if you need to filter out another ~4 bits  of random.

**Comment by gloomyandy** [comment]
My understanding of the way the LPC framework has been written is that it provides a way for folks to be able to use the vast set of Arduino library routines on the LPC devices. The default Arduino ADC resolution is 10 bits so that is what the LPC implementation provides. If you don't do that then you have to start having LPC specific versions of the Arduino libs (and programs like Marlin). I guess the same applies to the current framework filtering. It is there to try and give the results a similar quality to that provided by an Arduino (though in this case if the additional filtering is causing this issue, then arguably it is failing to make the results match that quality). In theory the more recent Arduino framework versions do allow for things like 12 bit ADCs but I suspect that very little if the library code out there makes use of those features.


Now you may not like this approach and could certainly argue that this sort of thing should be all defined by the HAL. But I suspect that the decision to do things this way were made to allow Marlin to move more easily to a 32bit platform while still supporting the very large numbers of 8 bit controllers. 

I'm not really sure how successful the Marlin HAL really is and I've never really understood the split of functionality between it and the Arduino like frameworks. Perhaps @p3p or @thinkyhead could provide some background on the thought process?

I guess if what you want is a printer firmware optimized for 32bit systems then there are other options out there. Marlin has a lot of existing users that Scott is trying to keep happy and make it easy for them to move forward. Personally I'd argue that too many new features are being added to Marlin and that it would be better to get 2.0 stable and released but that's not my call.

**Comment by ghost** [comment]
> Cutting down ADC samples from 12 to 10 bits does not really matter - if you need to filter out another ~4 bits of random.

mmm you're right about it not making any difference what with the PCB layout techniques used in the cheap printer controller boards.

Our concern wasn't with Marlin using 10-bit, it was with the framework cutting the CPU resolution down to 10-bit to suit Marlin itself.

code snippet from the LPC framework ..
```cpp
  static uint16_t get_result(void) {
    const uint32_t adgdr = LPC_ADC->ADGDR;
    LPC_ADC->ADCR &= ~(1 << (24)); // Stop conversion
    if (adgdr & ADC_OVERRUN) return 0;

    uint16_t data = (adgdr >> 4) & 0xFFF;      // copy the 12bit data value

    if constexpr (ADC_MEDIAN_FILTER_SIZE > 0 || ADC_LOWPASS_K_VALUE > 0) {
      uint8_t adc_channel = (adgdr >> 24) & 0x7; // copy the  3bit used channel

      if constexpr (ADC_MEDIAN_FILTER_SIZE > 0) {
        static MedianFilter median_filter[NUM_ANALOG_INPUTS];
        data = median_filter[adc_channel].update(data);
      }

      if constexpr (ADC_LOWPASS_K_VALUE > 0) {
        static LowpassFilter lowpass_filter[NUM_ANALOG_INPUTS];
        data = lowpass_filter[adc_channel].update(data);
      }
    }

    return ((data >> 2) & 0x3FF);    // return 10bit value as Marlin expects
  }
```

**Comment by ghost** [comment]
> I guess if what you want is a printer firmware optimized for 32bit systems then there are other options out there. Marlin has a lot of existing users that Scott is trying to keep happy and make it easy for them to move forward. Personally I'd argue that too many new features are being added to Marlin and that it would be better to get 2.0 stable and released but that's not my call.

Well we are doing our own version as we go with the various fixes/improvments (am sharing some as we go - as might have been noticed), but we would have thought the rest of the community would have liked to benefit with them added to Marlin?  particularly as we see some of the 8-bit users having noise problems with thermistors on the 8-bit boards (due partly to not very well filtered on board switching 5V regulators).

We've already completely disabled the LowpassFilter in the LPC framework (K_VALUE = 0) for testing with, yet we found no noise problems at all in that state on the LPC SKR boards, ADC readings quite nicely un-noisy, which surprised us. What we did find was that it's the LowpassFilter (with Marlin K = 6) that appears to be causing the boot-up thermal problem people have been having (which the grace period over came). We're not saying to remove the filtering though! .. quite the opposite, we're querying about the filtering not being applied to platforms that actually need it (some of the 8-bit boards) whist it being applied to platforms that don't always appear to need it.

All very interesting choices being made when you start delving deeper into these things. Looking in on a user community of programmers and trying to help out them out is proving quite interesting as compared to our normal non-user side of things shall we say :)

**Comment by p3p** [comment]
> Why does the framework return a 10-bit value from the 12-bit ADC ?

It's what the Arduino API requires, though there is `analogReadResolution` that's in the extended api not the standard one, not sure when that was added.

> That's not right. Marlin is fairly insignificant compared to all the other LPC176x projects out there

My LPC176x Arduino framework was written specifically as a (half arsed) compatibility layer for Marlin, although it is more generalised than it was, it is still not really a general Arduino framework, I'm sure it's not used by any other project they more than likely would use the standard mbed framework that platformio supplies.

> We've already completely disabled the LowpassFilter in the LPC framework (K_VALUE = 0) for testing with, yet we found no noise problems at all in that state on the LPC SKR boards, ADC readings quite nicely un-noisy, which surprised us. 

That's not really surprising the filtering is to catch the edge cases, as I said above I never had any problem with the ADCs, but others reported it becoming completely unusable during printing, this is a hardware issue with their printers that was less of an issue on the more robust AVR 8bit 5v ADC but as usual in Marlin we need to try and work around it with software to maximise compatibility.

> I'm not really sure how successful the Marlin HAL really is and I've never really understood the split of functionality between it and the Arduino like frameworks

@gloomyandy The HAL is to configure hardware (timers etc) to work with Marlin and catch anything that would be platform specific but needs to be controlled from Marlin directly and is not part of the Arduino API (it's not designed for projects like Marlin). The Arduino framework for low level hardware configuration, build chain, compatibility with libraries(sometimes). 

It's not as clean as it should be .. or as originally envisioned, (decoupled from Arduino), but it's what's working.

**Pull request closed without merging**
