### PR TITLE
Add timestamps in M20 (M20 T support)

### PR DESCRIPTION
**Pull request by arekm**
### Description

Add new TIMESTAMP_FILENAME_SUPPORT option which enables timestamps
support in M20 g-code output (M20 T command).

https://reprap.org/wiki/G-code#M20:_List_SD_card

Hex is a combined date and time (date in upper 16 bits of that hex value, time in lower 16 bits). Format it derived from FAT.

Examples
```
Send: M20 T
Recv: Begin file list
Recv: PSUSLO~1.GCO 700001 0x5515758F
Recv: AUTOLE~1.GCO 408 0x551868E7
Recv: 3DBENC~1.GCO 1765458 0x5518B33C
Recv: RECOVE~1.GCO 3912290 0x55195948
Recv: End file list
Recv: ok
```

```
Send: M20 L T
Recv: Begin file list
Recv: PSUSLO~1.GCO 700001 0x5515758F PSU Slotted Cable Tube_0.8n_0.3mm_PETG__16m.gcode
Recv: AUTOLE~1.GCO 408 0x551868E7 autolevel.gcode
Recv: 3DBENC~1.GCO 1765458 0x5518B33C 3dbenchy (1)_0.8n_0.3mm_PETG__39m.gcode
Recv: RECOVE~1.GCO 3912290 0x55195948 recovery.gcode
Recv: End file list
```

(From other firmwares - Prusa fork supports M20 T and implementations are compatible)

### Benefits

User is able to get modification dates for files on sd card.

Octoprint in next major version (1.9.0) will issue M 20 L T by default and will show timestamps in UI:
(screenshot of "Only show files stored on SD")

octo-m20t

### Configurations
Enable in Configuration_adv.h (with optional LONG_FILENAME_HOST_SUPPORT)
```
#define TIMESTAMP_FILENAME_SUPPORT    // Show timestamp for filename in 'M20 T' / 'M20 L T'
```

### Requirements

None.

### Related Issues

https://github.com/OctoPrint/OctoPrint/pull/4610
https://github.com/prusa3d/Prusa-Firmware/pull/3113

### CODE REVIEW

**Comment by thinkyhead** [comment]
I've applied a small refactor combining the ls flags into a bit-mask. Please confirm that it still works with your setup, and if all is well then this can be merged soon.

**Comment by arekm** [comment]
Thanks. Works with that small fix.

No need for ifdefs M20_TIMESTAMP_SUPPORT in printListing() because compiler will optimize out that code if disabled?

**Comment by thinkyhead** [comment]
> compiler will optimize out that code if disabled?

Correct. The other flags have some extra dependencies or I'd've done the same with them.

**Comment by Enemby** [comment]
This merge broke card.ls() behaviour for easythreed firmware configurations. Since card.ls() now has a required argument, it must be updated accordingly.

**Pull request merged**
