### PR TITLE
Revert "fixes"

### PR DESCRIPTION
**Pull request by Phr3d13**
Revert changes made during my last tinkering session that broke temperature reading ability.

### CODE REVIEW

**Comment by Phr3d13** [comment]
I'm not 100% sure if this should be merged/accepted. During more testing (might be my own dev environment) this PR fixes temp readings, but appears to break SDIO enough that SD only seems to be readable/usable during startup. The file list comes up, but crashes the menu as soon as I try to scroll.

**Comment by p3p** [comment]
You made no changes in this PR that should affect anything, other than adding the `MarlinConfig.h` header to a platform header which is generally a bad idea, I remember it caused you a lot of issues before.

**Comment by Phr3d13** [comment]
Without this PR SDIO works, but with it, temps work. Also, without this PR, I get warnings about something being declared external, but with it, I don't get that warning.

**Comment by Phr3d13** [comment]
According to https://github.com/MarlinFirmware/Marlin/issues/12816 and my own testing, this commit fixes one thing for one board, while breaking a bunch of things for other boards and my own. Should there be a Marlin 2.0 "issue" thread just for the stm32f1 HAL?

**Comment by thinkyhead** [comment]
It sounds like the problems you're having are not related to the watchdog reset. Yes, you should file an issue describing the symptoms you see so that there can be a proper investigation.

**Pull request closed without merging**
