### PR TITLE
Power Loss Recovery ISR overwrite Fix

### LINKED ISSUE #26057: [BUG] POWER LOSS RECOVERY extruder squeezes out a lot of filament
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After POWER LOSS RECOVERY hotend and bed heated up, x and axis doing auto home and go back to the place where it finished printing. Then extruder squeezes out a lot of filament and there is a large influx of plastic. After that printer continued his work.

### Bug Timeline

old

### Expected behavior

After PLR extruder does not extrude as much plastic

### Actual behavior

After PLR extruder squeezes out a lot of filament

### Steps to Reproduce

1. Start printing
2. Power off
3. Resume print

### Version of Marlin Firmware

2.1.2.1 hotfix

### Printer model

Creality Ender 3 Pro

### Electronics

SKR Mini E3 v3.0

### Add-ons

_No response_

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11968452/configuration.zip)

### PR DESCRIPTION
**Pull request by ThomasToka**
### Description

This patch fixes the following problems:

- on resume the print restarts from the beginning
- on resume the movements are slow
- on resume the extruder movements are too fast (extruder makes noise)
- on resume the extruder sometimes extrudes a lot of filament on the resume position

background here is that info.current_position (which are for x,y,z,e saved positions) and info.sdpos are overwritten inside of stepper.cpp. This in some situations leads to the mentioned problems on the power loss recovery run. Although there is a try to secure sdpos it is here overwritten and a direct assignment of sdpos directly after load to a new variable that is not overwritten by isr is needed. With this also the current_postions are saved to a new variable that is not overwritten by isr, but only by the load process with the real saved PLR data.

steppper.cpp
```
      #if ENABLED(POWER_LOSS_RECOVERY)
        recovery.info.sdpos = current_block->sdpos;
        recovery.info.current_position = current_block->start_position;
      #endif
```

EDIT: Z Position fixed in second commit. It fully works.

### Requirements
- #define POWER_LOSS_RECOVERY enabled
- for me only reproducable with a mesh >= 7x7, what ever it plays a role. but my 5x5 build do not suffer from this.

### Benefits

Power Loss recovery starts from the resume position and does not restart the print completely.

### Configurations

nothing special needed in configs.

### Related Issues
(https://github.com/MarlinFirmware/Marlin/issues/26057)

### CODE REVIEW

**Comment by ThomasToka** [comment]
Just did a testprint. With the second commit everything is fine again.

No extruder weakness, no resume speed weakness, no restart of the print. Nozzle resumes to the right position and continues the print.

I have even reverted now my "reroute to G27" fix as it works like intended with marlin plain.

**Review by ThomasToka — COMMENTED** [review]
I will do a real world test tomorrow. If this also works i dont mind. Important is that it works. But looking at this the problem with overwriting info.current_position is not solved. Will give you feedback tomorrow..

**Comment by thinkyhead** [comment]
I think we have a slightly more complete solution, which is not to overwrite the `recovery.info.sdpos` field when there is no SD print associated with the block (i.e., `block->sdpos == 0`) so I've applied that solution here for testing. Since it generally prevents Stepper ISR from stepping on `recovery.info` until the ISR actually receives an SD print move command, it will also prevent internal pause moves, etc., from setting `sdpos` to 0 when it should just be left alone.

It would also be possible to put a "`protect`" or "`state`" flag on `recovery.info` which would be set during the initial reboot `check`, but even then we'd still need the changes here to leave `recovery.info` untouched for non-print moves, and that already covers the case for most startup situations.

**Comment by ThomasToka** [comment]
Great. Feedback to come tomorrow. Poked 4days with this. ;)

**Comment by ThomasToka** [comment]
Did you test it with your printer what you have done?

EDIT: Watch next comment. This seems partly ok so far..

Do i understand it right:
```cpp
        const uint32_t sdpos = current_block->sdpos;
        if (sdpos) {
          recovery.info.sdpos = sdpos;
          recovery.info.current_position = current_block->start_position;
        }
```
With this you do: If `sdpos` is non zero update `recovery.info.sdpos = sdpos` and `recovery.info.current_position = current_block->start_position`.

EDIT: Watch next comment. This seems ok so far..

Here you simply cant use `info.current_position.z` as this is the resume position. we need the real position here after the lift of the axis after restart the printer:

```cpp
  // Interpret the saved Z according to flags
  const float z_print = info.current_position.z,
              z_raised = z_print + info.zraise;
```
changed to in my PR:
```cpp
  // Interpret the saved Z according to flags
  const float z_print = current_position.z,
              z_raised = z_print + info.zraise;
```

Doing it exactly like you proposed leads to a non matching z resume position.

I will make further tests now. But at this state it fixes only the first problem.

My proposal fixes everything in every situation.

**Comment by ThomasToka** [comment]
i did some further tests.

it does not overwrite anymore with 0. that is ok. so `sdpos` is always right now. i think with this also the problem is solved that `info.current_position` gets overwritten. as it was a problem when the values were 0, but if `sdpos` is non-zero then `info.current_position` is also non zero. so that matches.
A small log with my change to `current_position.z`:
```
Printer is now online.
echo:Now fresh file: /CUBES/POWERL~1.GCO
File opened: POWERL~1.GCO Size: 243263
File selected
//action:notification powerloss.gcode
echo:enqueueing "M1000"
echo:info.current_position.x 109.839
echo:info.current_position.y 124.264
echo:info.current_position.z 0.300
echo:info.current_position.e 107.308
echo:current_position.z 10.000
echo:info.sdpos16357
echo:Bed Leveling OFF
echo:Fade Height 5.00
//action:notification Bed Heating...
//action:notification Ender-3 S1 Pro Ready.
//action:notification Printing...
//action:notification E1 Heating...
echo:info.current_position.z 0.300
echo:current_position.z 10.000
echo:Invalid mesh.
Error:Failed to enable Bed Leveling
Error:Failed to enable Bed Leveling

echo:Bed Leveling OFF
echo:Fade Height 5.00
//action:notification Printing...
//action:notification E1 Heating...
echo:info.current_position.x 109.839
echo:info.current_position.y 124.264
echo:info.current_position.z 0.300
echo:>>> z_print:10.000current_position.z:10.000
``` 

i have to change to as mentioned

```cpp
  // Interpret the saved Z according to flags
  const float z_print = current_position.z,
              z_raised = z_print + info.zraise;
```

to reach the old z position. without this the axis does not go down.

so technically this fixes this. but i think there is a wording problem "z_print" suggests it is the old printing position. but the axis does not move down if this is set to `info.current_position.z`.

it is later set to `z_now`:
```cpp
    float z_now = info.flag.raised ? z_raised : z_print;
```

…so it is clear that z does not go down. as `z_now` is `z_print`. so the same if `info.current_position.z` is used. (`z_raised` stays unused i think here.)

**Comment by ThomasToka** [comment]
I have changed
```cpp
    float z_now = info.flag.raised ? z_raised : z_print;
```
to
 ```cpp
    float z_now = info.flag.raised ? z_raised : current_position.z;
 ```
 
 and restored 
 ```cpp
   // Interpret the saved Z according to flags
  const float z_print = info.current_position.z,
              z_raised = z_print + info.zraise;
 ```
 
this works also, but the question i have now: what is `z_raised`? is it the actual position AFTER in has been raised and `info.zraise` has been applied? i doubt it should be `info.current_position.z + info.zraise`. Here the "autolift of 10mm" is missing after reboot.

btw: this lift should not happen at all before the nozzle is heated. do you have a hint how to prevent this?

**Comment by ThomasToka** [comment]
a complete session with the last changes:

```
## last plr write

Writing to file: /PLR
Write Job Recovery Info...
valid_head:10 valid_foot:10
current_position: 109.839,124.264,0.300,107.308
feedrate: 2250
zraise: 2.000
home_offset: 0.000,0.000,0.000
filament_size: 0.000
target_temperature: 180
target_temperature_bed: 30
fan_speed: 127
leveling: OFF  fade: 5.000
sd_filename: /CUBES/POWERL~1.GCO
sdpos: 16357
print_job_elapsed: 247
axis_relative: E_MODE_ABS
flag.dryrun: 0
flag.allow_cold_extrusion: 0
flag.volumetric_enabled: 0

## loading settings on printer reboot

Load Job Recovery Info...
valid_head:10 valid_foot:10
current_position: 109.839,124.264,0.300,107.308
feedrate: 2250
zraise: 2.000
home_offset: 0.000,0.000,0.000
filament_size: 0.000
target_temperature: 180
target_temperature_bed: 30
fan_speed: 127
leveling: OFF  fade: 5.000
sd_filename: /CUBES/POWERL~1.GCO
sdpos: 16357
print_job_elapsed: 247
axis_relative: E_MODE_ABS
flag.dryrun: 0
flag.allow_cold_extrusion: 0
flag.volumetric_enabled: 0
---
echo:SD card ok
echo:Invalid mesh.
Printer is now online.

### press continue

echo:Now fresh file: /CUBES/POWERL~1.GCO
File opened: POWERL~1.GCO Size: 243263
File selected
//action:notification powerloss.gcode
echo:enqueueing "M1000"
echo:info.current_position.x 109.839
echo:info.current_position.y 124.264
echo:info.current_position.z 0.300
echo:info.current_position.e 107.308
echo:current_position.z 10.000
echo:info.sdpos 16357
//action:notification Bed Heating...
//action:notification Ender-3 S1 Pro Ready.

## first move to park position:

echo:info.current_position.z 0.300
echo:current_position.z 10.000
echo:>>> z_print:0.300 current_position.z:10.000 info.current_position.z:0.300
//action:notification Printing...
//action:notification E1 Heating...

## continue print

echo:info.current_position.x 109.839
echo:info.current_position.y 124.264
echo:info.current_position.z 0.300
echo:>>> z_print:0.300 current_position.z:0.300 info.current_position.z:0.300
echo:info.current_position.e 107.308
echo:Now fresh file: /CUBES/POWERL~1.GCO
File opened: POWERL~1.GCO Size: 243263
File selected
//action:notification powerloss.gcode
//action:notification powerloss.gcode
//action:resume
//action:prompt_end
//action:prompt_begin Resuming SD
//action:prompt_button Dismiss
//action:prompt_show
//action:notification powerloss.gcode
Write Job Recovery Info...
valid_head:11 valid_foot:11
current_position: 109.839,124.264,0.300,107.308
feedrate: 15000
zraise: 2.000
home_offset: 0.000,0.000,0.000
filament_size: 0.000
target_temperature: 180
target_temperature_bed: 30
fan_speed: 127
leveling: OFF  fade: 5.000
sd_filename: /CUBES/POWERL~1.GCO
sdpos: 16357
print_job_elapsed: 384
axis_relative: E_MODE_ABS
flag.dryrun: 0
flag.allow_cold_extrusion: 0
flag.volumetric_enabled: 0
```

it works. but i think i will secure resume_pos in my fork right after the load of the files. combined with your 0 fix it will be perfectly do what it should without a chance of interference of the isr overwrite that in this state also can happen.
isr can update info.current_position, it should. but it should not update the used positions for the resume. and this i dont know if this is 100% pervented. remember: we had problems with too much squeezed filament. this would not happen if feedrate was 0. it happens when it is set to a arbitary value. probably after the isr updated the value. so for me it is clear: we need to secure the resume_positions as a precaution.

**Comment by ThomasToka** [comment]
There is another problem i am facing in my tests with whatever version i try.

- the first run is correct.
- as of the second run there is a discrepancy between the PLR write and the PLR load. it loses 0.3mm what seems one layer

i see it clearly:

first PLR occurrence:
plr write:
```
current_position: 109.839,124.264,0.300,107.308
```
plr read:
```
current_position: 109.839,124.264,0.300,107.308
```

second and following PLR occurrence:
plr write:
```
current_position: 109.840,109.928,1.200,257.644
```
plr read:
```
current_position: 109.840,109.928,1.500,257.644
```

so the printhead starts 0.3 mm too high as of the second run.

will debug it now right before the write. will find this also ;)

**Comment by ThomasToka** [comment]
i see the increase by 0.30 in the output of plr write if i add a header right above the write:
```cpp
  DEBUG_ECHOLNPGM("info.current_position.z on write: ", info.current_position.z);
  const int16_t ret = file.write(&info, sizeof(info));
```

the plr write output looks then like this:  

```
Writing to file: /PLR
info.current_position.z on write: 2.700
Write Job Recovery Info...
valid_head:93 valid_foot:93
current_position: 125.700,117.230,2.700,362.009
resume_pos: 125.700,117.011,2.700,341.214
feedrate: 3000
zraise: 2.000
home_offset: 0.000,0.000,0.000
filament_size: 0.000
target_temperature: 180
target_temperature_bed: 30
fan_speed: 255
leveling: OFF  fade: 5.000
sd_filename: /CUBES/POWERL~1.GCO
sdpos: 30846
resume_sdpos: 29830
print_job_elapsed: 590
axis_relative: E_MODE_ABS
flag.dryrun: 0
flag.allow_cold_extrusion: 0
flag.volumetric_enabled: 0
---
Writing to file: /PLR
info.current_position.z on write: 3.000
```

the 3.000 is the wrong number that is written. it should be 2.700.

investigating further i think it has todo with the "changed" status.

**Comment by ThomasToka** [comment]
So it happens 'cause the isr updates, then the change is saved although the head is not in the next line.

```
Writing to file: /PLR
info.current_position.z on write org: 7.500
echo:ISR set recovery.info.current_position.z on write org: 7.800
...
echo:ISR set recovery.info.current_position.z on write org: 7.800
info.current_position.z on save org: 7.800
```

you see it clearly when you put in stepper.cpp:

```cpp
        const uint32_t sdpos = current_block->sdpos;
        if (sdpos) {
          recovery.info.sdpos = sdpos;
          recovery.info.current_position = current_block->start_position;
          SERIAL_ECHO_MSG("ISR set recovery.info.current_position.z on write org: ", recovery.info.current_position.z);          
        }
```
and in the save before the write in powerloss.cpp:
```cpp
    DEBUG_ECHOLNPGM("info.current_position.z on save org: ", info.current_position.z);
    write();
```

**Comment by ThomasToka** [comment]
even better visible if you also dump `current_position.z` on the same positions:
```
Writing to file: /PLR
current_position.z on write org: 12.600
info.current_position.z on write org: 12.300
echo:ISR set recovery.info.current_position.z on write org: 12.300
current_position.z on save org: 12.600
info.current_position.z on save org: 12.300
```

**Comment by ThomasToka** [comment]
ok going one step back. to circumvent the 10mm lift on reboot i changed.
```
float z_now = info.flag.raised ? z_raised : current_position.z;
```

and this is the problem. current_position.z is sometimes ahead of the recovery.info.current_position.z depending where it is in the run.

so i now changed it to:
```
float z_now = info.flag.raised ? z_raised : info.current_position.z + 10.000;
```

this fixes the recurring runs.

so back to the question: how to prevent the lift up of the head and heat nozzle first?

EDIT: Doing a real world print now to test the recurring power loss. Lets see if it works in reallife.

EDIT2: Real world test failed. Nozzle started about 5 layers too high. Testing now another approach.

EDIT3: SUCCESS. I added info.zraise to the z_now and now it works.

```
float z_now = info.flag.raised ? z_raised : info.current_position.z + info.zraise + 10.000;
```
So those 5 layers were in real those 2mm from zraise.

dummdidumm me happy. it works. also recurring. over and over ^^

**Comment by thinkyhead** [comment]
> even better visible if you also dump `current_position.z` on the same positions:

The global `current_position` is always ahead of the actual physical machine position, so we can ignore it in relation to PLR. We only care about the position stored in the planner block that gets copied by the stepper ISR into `info.current_position` at the time the block starts to process.

> i see the increase by 0.30 in the output of PLR write if i add a header right above the write:
> So it happens 'cause the isr updates, then the change is saved although the head is not in the next [layer].

It looks like non-SD blocks are still getting a non-zero `sdpos` and this is causing some moves to update `recovery.info` that shouldn't.

I'm not sure if that is the source of the 0.3mm discrepancy. A discrepancy of one layer height should only occur if the power outage occurs at some point close to a layer change.

Anyway, `recovery.cmd_sdpos` is used in `commit_command` by the call to `recovery.commit_sdpos` to set `sdpos` for the current ring buffer command. It should instead be calling a new method, `recovery.commit_sdpos_zero` for non-SD commands. So I think that's the next change to explore.

**Comment by ThomasToka** [comment]
Have done 4 Power loss on this cube Now. Works.

**Comment by ThomasToka** [comment]
IMG_5638

**Comment by ThomasToka** [comment]
I have put up temporary branch with todays fixes. sorry that i for now used my approach to secure the real position readen directly out of the PLR. Maybe we find a better safe approach. but for now i am satisfied that it works as it is in its actual state.

https://github.com/ThomasToka/Marlin/commit/5e7fd52fa756f8d003a1186d1d60b93761d66b8e

**Comment by thinkyhead** [comment]
> Have done 4 Power loss on this cube Now. Works.

Of course that might just be your perfect combination of settings. For any change to this system we have to consider all possible machines and combinations of settings. So I want to make changes gradually, first aiming to fix the original intent, and to make sure the correct values are saved since everything else depends on that.

**Comment by thinkyhead** [comment]
With the latest changes in this PR the `sdpos` field should now be 0 for non-SD commands, and so it should not be updating `info.current_position` when running non-SD planner blocks. That should eliminate the problem of internal commands affecting the PLR file, which may or may not be involved in other issues.

With these changes in place we'll have to do another run (with `DEBUG_POWER_LOSS_RECOVERY` enabled) and get a close look at the details of the whole process. There will be beds that fall when power is lost, and power detection circuits that allow the Z axis to raise before shutting down. So we want to make sure the Z position is properly known, that the resume position is correct, and that the `info` fields capture all the data needed for a good resume.

I have a couple of machines prepared for flashing so I can test this PR along with other recent PRs.

**Comment by ThomasToka** [comment]
> > Have done 4 Power loss on this cube Now. Works.
> 
> Of course that might just be your perfect combination of settings. For any change to this system we have to consider all possible machines and combinations of settings. So I want to make changes gradually, first aiming to fix the original intent, and to make sure the correct values are saved since everything else depends on that.

yes i am with you. thanks for takeing this into your hands. i can only oversee my little world with my machines. its right and important that you who has a wider range of knowledge looks for all possibilities that i dont even know.

will make today a new branch with your latest fixes for my printer and test also and come back with results.

**Comment by ThomasToka** [comment]
i just created for the oversight a new branch with your fixes @thinkyhead and with @ellensp ´s #26367

https://github.com/ThomasToka/Marlin/commits/MARLIN-E3S1PROFORK-BYTT-RELEASE-CODE-v015-dev-powerloss

- it works after i change like mentioned before:

```cpp
float z_now = info.flag.raised ? z_raised : z_print + info.zraise + 10.000;
```

- but what i again see are fast movements, that i have not seen when i secure the variables after PLR load in resume_pos like in my pr

- also see some high feedrates sometimes in the output stream:

```
Writing to file: /PLR
Write Job Recovery Info...
valid_head:192 valid_foot:192
current_position: 111.082,125.879,5.700,574.042
feedrate: 15000
zraise: 2.000
repeat index: 0
home_offset: -2.000,-2.000,0.000
filament_size: 0.000
target_temperature: 215
target_temperature_bed: 80
fan_speed: 255
leveling: OFF  fade: 5.000
sd_filename: /CUBES/PETG/CURA53~3.GCO
sdpos: 46925
print_job_elapsed: 1125
axis_relative: E_MODE_ABS
flag.dryrun: 0
flag.allow_cold_extrusion: 0
flag.volumetric_enabled: 0
```

so i see noticable speed variations on the resume.

**Comment by thinkyhead** [comment]
For another perspective, your change is equivalent to…
```diff
- float z_now = info.flag.raised ? z_raised : z_print;
+ float z_now = z_raised + (info.flag.raised ? 0.0f : 10.0f);
```
Deconstructing this suggested change:
- The `info.flag.raised` flag indicates that `z_raised` is the (expected) current Z position right now, because Z was raised during the power outage. So it makes sense to set `z_now` to `z_raised` in that case.
- For the other case force a 10mm raise now.

The way the existing code is meant to work is to establish:
- `z_print` : is the Z position of the last active print layer.
- `z_raised` : is the raised Z position already done (`BACKUP_POWER_SUPPLY`) or to do just below.
- `z_now` : is the expected current Z position, either raised (`BACKUP_POWER_SUPPLY`) or not yet raised.

In all cases `info.zraise` is expected to be `POWER_LOSS_ZRAISE`, and so `z_raised` is expected to be `z_print + POWER_LOSS_ZRAISE`. Assuming that all our ducks are in a row the following block will do a raise based on how we set `z_raised` and `z_now`:

```cpp
// Does Z need to be raised now? It should be raised before homing XY.
if (z_raised > z_now) {
  z_now = z_raised;
  PROCESS_SUBCOMMANDS_NOW(TS(F("G1F600Z"), p_float_t(z_now, 3)));
}
```
So the question is, why do you need to use `z_raised + 10.0f` to get a raise? What kind of behavior do you see if you set `POWER_LOSS_ZRAISE` to some large value like 5 or 10?

**Comment by ThomasToka** [comment]
- i do not use z_raise in my config. it seems to be default set to two if not set in config.
config:
```
    //#define POWER_LOSS_ZRAISE       2 // (mm) Z axis raise on resume (on power loss with UPS)
```
like visible in the debug output
```
zraise: 2.000
```
- second is: i just went back from what i see what happens to reach the print position.
- on recovery my head lifts 10mm, so i have to add this to z_now, otherwise it prints in the air
- after adding 10 mm i saw that still 2mm are missing. and as i see that info.zraise is 2mm so i added this.

EDIT: 
powerloss.h
```
#ifndef POWER_LOSS_ZRAISE
  #define POWER_LOSS_ZRAISE 2
#endif
```

So if it is 2 when unset it needs to be accounted also. Either remove the default or add it. otherwise it is like it is when its not set that those 2mm are missing.

**Comment by thinkyhead** [comment]
> on recovery my head lifts 10mm, so i have to add this to `z_now`, otherwise it prints in the air

I see. There's a 10mm raise occurring earlier in the startup process, even before `M1000`.

```
echo:enqueueing "M1000"
echo:info.current_position.x 109.839
echo:info.current_position.y 124.264
echo:info.current_position.z 0.300
echo:info.current_position.e 107.308
echo:current_position.z 10.000   <---- Raise occurs before M1000
```

What setting is it that introduces this 10mm raise? I know that some LCD screen implementations might do things ahead of `M1000` when they really should be modifying `M1000` instead. If this is a common need then we'll have to account for it, perhaps by adding a new parameter to `M1000`.

A trick to see an echo of every command that goes to the queue by default at startup…
```diff
- uint8_t marlin_debug_flags = MARLIN_DEBUG_NONE;
+ uint8_t marlin_debug_flags = MARLIN_DEBUG_ECHO;
```

**Comment by ThomasToka** [comment]
> What setting is it that introduces this 10mm raise?

just checked it. it is:
```
#define Z_CLEARANCE_DEPLOY_PROBE    10 // (mm) Z Clearance for Deploy/Stow
```
reduced it to five and the lift was 5.

EDIT:
Conditionals_LCD.h
```
#ifndef Z_CLEARANCE_DEPLOY_PROBE
  #define Z_CLEARANCE_DEPLOY_PROBE 10
#endif
``` 

in probe.h maybe the reason for this?

```
  if (z_raise_wanted) {
    const float zdest = DIFF_TERN(HAS_HOTEND_OFFSET, Z_CLEARANCE_DEPLOY_PROBE, hotend_offset[active_extruder].z);
    if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("Raise Z to ", zdest);
    do_z_clearance(zdest);
  }
```

**Comment by ThomasToka** [comment]
sadly i was not able to fix the open problems with your provided fixes only. 

so i did it like this:
```
 float z_now = info.flag.raised ? z_raised : resume_pos.z + info.zraise + Z_CLEARANCE_DEPLOY_PROBE;
```
my v015 release: https://github.com/ThomasToka/Marlin/commit/e844ba558fab815ff59eace3bd77b813681ea767#diff-b29d174fc22b838f2cd572ca868d1405b9a14a5f81e48548c9706aa185ff81b8

if you have something to test i am willing to try out as the other test branch is still there and i can add things.

**Comment by thinkyhead** [comment]
> in `probe.h` maybe the reason for this?

A quick look at the probe code tells me that this code will only be executed if `set_deployed` is called to deploy the probe while `endstops.z_probe_enabled` is `false`, or to stow the probe while `endstops.z_probe_enabled` is `true`. Neither of these scenarios seems possible. You can check whether `set_deployed` is being called and raising the Z axis by turning on `DEBUG_LEVELING_FEATURE` and making this change:
```diff
- uint8_t marlin_debug_flags = TERN(MARLIN_DEV_MODE, MARLIN_DEBUG_ECHO, MARLIN_DEBUG_NONE);
+ uint8_t marlin_debug_flags = MARLIN_DEBUG_LEVELING;
```

**Comment by thinkyhead** [comment]
Another global search of the code shows the most likely scenario for the `Z_CLEARANCE_DEPLOY_PROBE` raise is that the `probe.deploy` or `probe.stow` is being called before `M1000`, but I have not confirmed. I'll do some deep debugging on PLR with one of my test machines and see if I can sort it out and get this merged tonight.

**Comment by ThomasToka** [comment]
I can only say that i run this in production since i released my v015. meanwhile we are at v023 and users still do filament changes over and over and i had not one complain regarding oozing, fast movements, slow movements, weird behavior or something.
It simply works as intended.

**Comment by thisiskeithb** [comment]
I added a `Needs: Work` label & marked it as draft since:

> additionally i want to say that without my initial commit it is not solved. the additions thinkhead made do not work for me reliably. did not test the last state. but i am sure my fixes in #26365 work and solve all of this.

_Originally posted by @ThomasToka in https://github.com/MarlinFirmware/Marlin/issues/26057#issuecomment-1881756816_

**Comment by thinkyhead** [comment]
>> I added a `Needs: Work` label & marked it as draft since:

But according to the last comment above:
> … i run this in production … [and] … It simply works as intended.

So I assume this PR fixes the main problem of the PLR file being written to when it shouldn't be (i.e., outside of SD printing) and I am prepared to merge it if that is the case.

**Comment by thinkyhead** [comment]
Also: I did one test of Power-Loss with these changes and it worked perfectly (apart from the ooze blob that was left on the print when I turned off the power).

**Comment by ThomasToka** [comment]
I meant my changes in the initial commit.

If i dont use them its the same like before. The sdpos changes dont fix it.

Since then i received not one complain.

Thats what i did in my v015:

https://github.com/ThomasToka/Marlin/commit/08592508d6c7bbaee603d6d80aa9db35c49f11b5#diff-b29d174fc22b838f2cd572ca868d1405b9a14a5f81e48548c9706aa185ff81b8

**Comment by thinkyhead** [comment]
Your original solution is very good and does account for the main issue. I'm probably overthinking it because this feature is so brittle and disjointed.

Going back to the original changes (caching `current_position` and `sdpos` before doing anything else)…. The one thing I hope to change is to grab those values at the top of `PrintJobRecovery::resume` ahead of any `G0`/`G1` rather than allocate globals for the purpose, if that is possible.

I scanned the code to see where `recovery.load()` is called (`recovery.check()`) and then what happens between `recovery.check()` and putting `M1000S` into the command buffer, and I couldn't see where any planner blocks would be created. (We certainly don't *want* to create any planner blocks before we get to `recovery.resume()`!) So it does seem safe to grab those values at the top of `PrintJobRecovery::resume`.

If this works, it will fulfill my obsession with avoiding new globals and it certainly is simpler than all the other `sdpos` rigamarole I was tripping over.

Do you see any issues with this as it is now?

**Comment by ThomasToka** [comment]
Two things i had to implement to make the resume work correctly:

ZRAISE is not defined default in Configuration_adv.h  but set to 2 ifndef in powerloss.h .

```
#ifndef POWER_LOSS_ZRAISE
  #define POWER_LOSS_ZRAISE 2
#endif
```

so you need to account it in z_now.

second thing is Z_CLEARANCE_DEPLOY_PROBE. i have it at 10... and yes my head lifts automatically on power on. that's why i have it also in here otherwise i can´t resume as it takes here Z_CLEARANCE_DEPLOY_PROBE into account.

best would be if the nozzle does not move at all on power recovery cause the nozzle will stick to the filament after it cooled down.. but that i did not intersect yet why and where to change this.

so i did:

```
   float z_now = info.flag.raised ? z_raised : resume_pos.z + info.zraise + Z_CLEARANCE_DEPLOY_PROBE;
```

most important in this PR is the caching of the values that you now have so they are the saved values in every case. without this its more like russian roulette..

**Comment by thinkyhead** [comment]
> so you need to account it in `z_now`.

I've scanned the code a lot, and this is what I can tell you about `POWER_LOSS_ZRAISE`:
- The value of `POWER_LOSS_ZRAISE` (which can be overridden in `Configuration_adv.h`) is saved with the PLR file and is included in the `z_raised` value. (See `PrintJobRecovery::save`).
- Upon resume the bed and hotend heat up and then…
  - The `z_now` value will be `z_raised` if the Z axis raised _before the outage_.
    Otherwise `z_now` will be `z_print`.
  - The Z axis is then raised to `z_raised` (and `z_now = z_raised` so `z_now += POWER_LOSS_ZRAISE`).

> my head lifts automatically on power on

That does not appear to be normal Marlin behavior. I can't account for that raise from looking at the current code. So while we may need to account for your situation by adding `Z_CLEARANCE_DEPLOY_PROBE` somewhere, we can't do it unconditionally.

On my power outage test setup using `bugfix-2.1.x` I have the `Z_CLEARANCE_DEPLOY_PROBE` set to 4, and on that machine there is **no raise on power on** before we get to `recovery.check` and `M1000S` (because there is no probe deployment).

So we need to figure out where that raise is happening on your machine and why. I examined your configurations again and I don't see anything amiss. Your log shows the raise occurs early in the startup process, but it doesn't clearly indicate the source of that raise.

I searched the current Marlin code looking for references to`Z_CLEARANCE_DEPLOY_PROBE` and the only viable candidate for a raise was `Probe::set_deployed`, but why would that be called before recovery? So it's a great mystery.

As you say, the rest of these changes fix the main issue, so I will merge this and you should open a new issue to try to solve the mystery of your probe raise situation.

**Comment by ThomasToka** [comment]
@thinkyhead i am very sorry to say: but that what you have made out of my pr makes the printer simply restart/reset with a G28 after the heatup.

i have to patch this again now in my upcomming v028 to the state i initially did with this pr. it was now demaged in my fork since i followed your way to fix it. it looks like nobody tested this (me included! lol). so i got the first bugreport about 2-4 weeks ago. now on doing my v028 update i verfied that it is broken by this.

**Comment by ThomasToka** [comment]
i removed my comment as it was probably wrong what i said. i looked in a wrong dev branch.
will verify this again if i have more time after my next release.

**Comment by ThomasToka** [comment]
So finally. Today i solved everything and included a own logic.
Dont know if you remember @thinkyhead i first insisted on the fact that zraise was done and the 2mm were added. I was wrong with this. My Problem were the 2mm from Z-offset and 5mm that both came from M402 in my rts_init. M402 does:

https://github.com/MarlinFirmware/Marlin/blob/f8bbabfa3131f6c7abb23d4eb5bdb4f9779393b9/Marlin/src/gcode/probe/M401_M402.cpp#L68

Which resulted in 

https://github.com/MarlinFirmware/Marlin/blob/f8bbabfa3131f6c7abb23d4eb5bdb4f9779393b9/Marlin/src/module/motion.cpp#L1295

Where the probe.offset.z is added.

As my z.offset is -2.03 it matched the default powerloss z_raise and i did not realise what really was going on. Only had luck that my z.offset matched. Lol.

I Now have made:
- removed the M402 from my rts_init
- Adjusted powerloss.cpp z_now to include my plr_raise variable
- changed the behavior of the powerloss resumes G28R0XY to G28R$plr_raiseXY after the heatup of the nozzle
- Made the m402 lift optional eneblable on non powerloss recovery printer boots through my dynamic settings.

nevertheless i fill resume_pos directly after the load from eeprom. If i load it like you in resume it gets overwritten by the isr (or whatever) sometimes. It is not reliable.

Now it works for all my users.

I will remove the debug echos in my next release. With those you see everything ;)

If you want to have a look: 

https://github.com/ThomasToka/Marlin/blob/MARLIN-E3S1PROFORK-BYTT-RELEASE-CODE-v029/Marlin/src/feature/powerloss.cpp

Thank you for your time.

**Pull request merged**
