### PR TITLE
Reverse encoder for displays where turning clockwise decrease values.

### PR DESCRIPTION
**Pull request by epatel**
I am building a new printer and I am using RAMP 1.4 + a 128x64 LCD display from SainSmart.
The encoder direction felt totally wrong so I added this option to be able to change it.

### CODE REVIEW

**Comment by nophead** [comment]
All you need to do to reverse the encoder is swap the pin definitions. They
must be incorrectly defined for your display if clockwise decreases.

**Comment by epatel** [comment]
Got the same as described here. https://www.youtube.com/watch?v=H3wj9l1hvVw
Just wanted it to be easier to fix than Googling etc. Personally I like to minimize changes outside "Configuration.h"

**Comment by nophead** [comment]
Well that video says the pins need swapping. So you added yet another option in the code to compensate for the pins being defined wrong instead of fixings the pins.

**Comment by epatel** [comment]
OK, I understand then that you do not like this. Will remove it.

**Comment by thinkyhead** [comment]
What are the pins supposed to be? I can easily fix the SainSmart definition, if needed.

**Comment by thinkyhead** [comment]
This will soon be resurrected (sort of) as an option to reverse the direction that the menus move when rotating an encoder.

**Comment by silvanobozzo** [comment]
Hey, sirs !!|!
The patches seems to be OK... but only IF written in the opposite way...
What I mean is that the following rows:
if (lastEncoderBits==encrot3) ENC_INC(encoderDiff); 
            else if (lastEncoderBits==encrot1) ENC_DEC(encoderDiff);

MUST be:
if (lastEncoderBits==encrot3) ENC_DEC(encoderDiff); 
            else if (lastEncoderBits==encrot1) ENC_INC(encoderDiff);
INSTEAD !!!
By the way, exactly the same should be for the other three rows ((encrot 1, encrot2 and encrot3)....
By doing this, the patch will work... IF NOT... no9thing happens and the menu shall work in the OPPOSITE way, like before the patch application...
Hope all this could be helpful..
Silvano

QUOTE:::
case encrot0:
            //if(lastEncoderBits==encrot3)
            //    encoderDiff++;
            //else if(lastEncoderBits==encrot1)
            //    encoderDiff--;
            if (lastEncoderBits==encrot3) ENC_DEC(encoderDiff); 
            else if (lastEncoderBits==encrot1) ENC_INC(encoderDiff); 
            break;
        case encrot1:
            //if(lastEncoderBits==encrot0)
            //    encoderDiff++;
            //else if(lastEncoderBits==encrot2)
            //    encoderDiff--;
            if (lastEncoderBits==encrot0) ENC_DEC(encoderDiff); 
            else if (lastEncoderBits==encrot2) ENC_INC(encoderDiff); 
            break;
        case encrot2:
            //if(lastEncoderBits==encrot1)
            //    encoderDiff++;
            //else if(lastEncoderBits==encrot3)
            //    encoderDiff--;
            if (lastEncoderBits==encrot1) ENC_DEC(encoderDiff); 
            else if (lastEncoderBits==encrot3) ENC_INC(encoderDiff);
            break;
        case encrot3:
            //if(lastEncoderBits==encrot2)
            //    encoderDiff++;
            //else if(lastEncoderBits==encrot0)
            //    encoderDiff--;
            if (lastEncoderBits==encrot2) ENC_DEC(encoderDiff); 
            else if (lastEncoderBits==encrot0) ENC_INC(encoderDiff); 
            break;
...UNQUOTE

**Pull request closed without merging**
