### PR TITLE
introduce NO_BED_COOLING option

### PR DESCRIPTION
**Pull request by ohhmm**

### CODE REVIEW

**Comment by jbrazio** [comment]
@iHateInventNames please explain what you indent to introduce with this PR.

**Comment by Blue-Marlin** [comment]
Unneeded. Just don't use the (rare) R parameter.

**Comment by thinkyhead** [comment]
Rare to use the `R` parameter, but yeah somebody out there surely wants to wait for their bed to cool down before continuing.

**Comment by Blue-Marlin** [comment]
And why should someone want to disable that if he has the freedom to chose from 'R' or 'S'?

**Comment by thinkyhead** [comment]
Indeed. And in conclusion, this PR is summarily rejected. Sorry @iHateInventNames but thank you for taking the time to suggest it!

**Comment by ohhmm** [comment]
Slicing software uses the option. Should I edit each generated gcode? What about copy-centers. I'd suggested to make the option default.

**Comment by Blue-Marlin** [comment]
@iHateInventNames 
Would you please be so kind to point us to the slicer who uses `M190 R123` instead of `M190 S123` by default? I'd like to open an issue there.

**Pull request closed without merging**
