### PR TITLE
Add bed in cycle M600

### PR DESCRIPTION
**Pull request by MagoKimbra**
Add bed in cycle M600

### CODE REVIEW

**Comment by Roxy-3D** [comment]
@MagoKimbra  I'm having difficulty understanding why somebody would want to cut power to the heated bed.  At least with PLA and ABS, the user would risk losing adhesion to the bed by cutting power.

**Comment by MagoKimbra** [comment]
The news introduced by @thinkyhead in the patch #5794 is that if after a set time the user does nothing the tw (will switch) off the hotends waiting for you to press a button. I also think it is right (for the firmware to switch) off the bed which then turn (it) on again when even hotends come back on.

**Comment by ghost** [comment]
I'm on the fence about that also.

**Comment by fiveangle** [comment]
#5794 protects from potential damage due to non-standard behavior of unmoving filament in heated HE for extended period causing it to cook, drip, catch on fire, or other.

HB usage model is not the same and disabling HB with the HE during extended pause should cause failed print if calibrated correctly, since cooled HB is supposed to release the print.  Disabling HB during pause **ensures** failed print and precludes user from ever unpausing.

While well-intentioned, I also believe this PR should be rejected.

**Comment by Roxy-3D** [comment]
Just to help the discussion....   Just for the purpose of exploring all possibilities so we really understand the problem...

Would there be any merit to reducing the heat instead of turning it off?   I suspect I could keep good adhesion as low as 45 degrees for PLA.   Would there be benefit to allowing the user to set what temperature they want the bed to wait for the filament change?    (And if we did that...   obviously the user could select 0 degrees if that really made sense to them.)

**Comment by ghost** [comment]
```
#if ENABLED(B) || !ENABLED(B)
  #define QUESTION
#endif
```

**Comment by MagoKimbra** [comment]
You excuse me, this function I had inserted a long time ago at the request of one of my user. But it was a request to turn off all printer after a long wait time, 5 or 10 or 15 minutes.
If you want we can do so after FILAMENT_CHANGE_NOZZLE_TIMEOUT go out only hotend while FILAMENT_CHANGE_PRINTER_OFF after everything is shut down.
This way if the user forgets the filament change if after 10 minutes (example) do not make the thread return you avoid burn everything.
Otherwise we let so that it is better!

**Comment by akaJes** [comment]
As a way to get for the bed its own timeout option(in minutes) and own warm up before nozzle warming as it works at start of printing
And inform user In documentation about posibility of failing and losing adhesion

**Comment by akaJes** [comment]
Next stage of this idea can be hibernation mode similar to wasp https://github.com/MarlinFirmware/Marlin/issues/2085

**Comment by Roxy-3D** [comment]
> This way if the user forgets the filament change if after 10 minutes (example) do not make the thread return you avoid burn everything.

@MagoKimbra   We just added the code to turn off the nozzles after a user defined time out.  And it also beeps for a while to alert the user that a filament change is required.   If the nozzles are turned off, it will re-heat them (and display the temperature of the active nozzle) before continuing.  

https://github.com/MarlinFirmware/Marlin/pull/5794

We can add the bed to the things that get turned off (and back on).   My question is "Does that make sense?" because I'm worried the partially printed part would loose adhesion to the bed.   But if there was a reason to turn off the bed, or maybe even just lower its temperature...   That would be very easy to add to the current code.

**Comment by ghost** [comment]
In an effort to please everyone, what about giving an option to shut the bed down also. I say that because everyone has their own type of adhesion for any given print.
This can also be an option to change from the LCD from one print to the next.

**Comment by Roxy-3D** [comment]
> In an effort to please everyone, what about giving an option to shut the bed down also. I say that because everyone has their own type of adhesion for any given print.

I don't want to (necessarily) turn the bed off.   We can let the user specify what temperature the bed should be held at while waiting for the filament change.   We would have to have some flag values to allow the bed to be held constant.   Maybe the #define FILAMENT_CHANGE_BED_TEMP_WHILE_WAITING -1 is the default and indicates to hold it steady at the current temperature????

@MagoKimbra I hope you don't feel like I'm trying to be difficult!   I just want this all to make sense and be usable!

**Comment by ghost** [comment]
I'd call that good.

**Comment by thinkyhead** [comment]
Kewl!

**Comment by thinkyhead** [comment]
Just patching up M600 code (#5854). Much improved. I'll look at this in the morning.

**Comment by MagoKimbra** [comment]
Ok for me no problem!!!

**Comment by thinkyhead** [comment]
I'm leaning towards rejecting this idea, because cooling the bed is a sure way to ruin a print. Perhaps the bed could go to a lower temperature, but it shouldn't drop more than 20°C or the object is liable to pull loose.

**Comment by ghost** [comment]
>As a way to get for the bed its own timeout option(in minutes) and own warm up before nozzle warming as it works at start of printing
And inform user In documentation about posibility of failing and losing adhesion

What he (@akaJes) said.

**Pull request closed without merging**
