### PR TITLE
Raise Z during 'G28 Z' move if Z_Safe_Homing is enabled

### PR DESCRIPTION
**Pull request by RFBomb**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Z is normally raised before homing X/Y during G28. But if you perform a "G28 Z" (such as when you are adjusting your Z probe with Z_Safe_Homing) there is the potential to drag the nozzle across the bed since the printer does an XY movement before raising Z. 

There were a few ways I wanted to go about doing this check, but this seemed the simplest method to get it done. 

### Benefits

Helps prevent dragging nozzle across the bed when performing "G28 Z" with Z_Safe_Homing enabled if the nozzle is too low. 

### Related Issues

Unsure if related issues exist. I had this issue myself, so I created pull request instead of opening an issue.

### CODE REVIEW

**Comment by RFBomb** [comment]
No idea what the 'PR Bad Target' request means. I think it has to do with me learning pull requests, where I effectively pull-requested my own fork, merged it, then for some reason that showed up as 2 (identical) commits here. 

If you review the code change itself, it is a very small change, so no idea why it would fail.

**Comment by android444** [comment]
You have to do this on MarlinFirmware:bugfix-2.0.x
Bez tytułu

Change in GITHUB DESKTOP to bugfix-2.0.x

Bez tytułu

**Comment by RFBomb** [comment]
@android444  I wasn't sure if that was correct or not, since it showed '40 commits'

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at (or originating from) release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR **starting with the `bugfix-2.0.x` branch** and be careful to target `bugfix-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by thinkyhead** [comment]
The change was simple enough that I was able to apply it directly. Thanks for the patch!

**Pull request closed without merging**
