### PR TITLE
[ExtUI] Rename JUNCTION_DEVIATION to JUNCTION_DEV

### PR DESCRIPTION
**Pull request by robbycandra**
Rename JUNCTION_DEVIATION to JUNCTION_DEV.

Because #define JUNCTION_DEVIATION is already used. Therefore create error: expected unqualified-id.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Missed this one. Thanks for submitting!

**Comment by robbycandra** [comment]
@thinkyhead , you edit this PR but why it is unmerged ?

**Comment by robbycandra** [comment]
> Merge branch 'bugfix-2.0.x' into EXT_UI_Rename_Junction_Deviation_String_Definition
6895532 

Wrong direction ?

**Comment by InsanityAutomation** [comment]
I will have to look but I think he came across the problem in my other pull request dealing with m851 because at one point I had brought these changes in to make sure that it all passed Travis since it was failing on the same errors and then I backed them out to not interfere with this. He saw it in the change history over there, and made the change without noticing this pull request.  So net results are still there!

**Comment by Roxy-3D** [comment]
Translated into English:  

He was making sure his stuff worked with your stuff...  And even though your stuff was not part of what he said to 'Merge!'...    Your stuff was in the History of his stuff and Scott saw it.   It all got pulled in together.

**Comment by thinkyhead** [comment]
Yep. I applied the same fix at some point and had it piggybacked on another PR, but I had called it `JUNC_DEVIATION` instead of `JUNCTION_DEV`. A few PRs were hanging around that still had the old name, causing Travis troubles. I thought maybe my name change had been reverted when I saw this PR too. But, it was just a glitch in the matrix. The fix was already in.

**Pull request closed without merging**
