### PR TITLE
[2.0.x] DUE - add programming capability to native port

### PR DESCRIPTION
**Pull request by ejtagle**
These changes allow the  Native port to be used as a programming port on Arduino DUE and derived designs.

After the initial download via the programming port, the native port can now be used as the programming interface, the host interface and the USB mass storage interface.

~?? **CHECK IF THIS IS ACCURATE**  NOTE - the native port can not reset the board so a manual reset or power up is needed after a download on the native port ??~

This code adds to the native port the Arduino code that results in entering the programming mode  when the port, already open at 1200 bps, is closed.

----

~We've had mixed results on Windows based PCs.  On some PCs the native port functions work beautifully.  On others only the USB mass storage function works on the native port.~

~It's possible that the Windows problems are caused by the LPC1768/Smoothie USB mass storage drivers also being on the machine.~

----

UPDATE 13 MAR 2018

Setting **SERIAL_PORT** in Configuration.h to -1 moves the host interface from the programming port to the native port.

Uploading images via the native port is **NOT as reliable** as on the programming port. Having a minimal image (LCD only enabled) in FLASH may require multiple attempts to download the next image via the native port.  Larger images (LCD & SD card enabled) are fairly reliable.

Uploads via the programming port are very reliable if the native port is not connected to the host computer.  Uploading via the programming port will fail when the native port is cabled up.

Failure is defined as the upload failing to start.  The image in the FLASH is not affected by a failure.

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Definitely a step forward.

It doesn't program via the native port on my machine.

The good news is, if you have both plugged in and do a download which fails, unplugging the native port & doing a download restores functionality.

Any possibility of having host, download and USB mass storage all on one port?

**Comment by ejtagle** [comment]
Hummm... The main problem now is that i already have host, program and USB mass storage running in the native port of the DUE with no issues.
The only thing i have noticed is that when programming using the Native port, the CPU does not reset after the programming. The plash is programmed and verified with no issues, but the reset jumps again to the bootloader...I have no idea why,,,

PD: By using the latest BOSSA utility, the SAM3X programs, verifies and properly resets with no issues. I now suspect this could be caused by a BOSSA bug not corrected on the version that is bundled with Arduino.

Just for reference, what i do:

Download latest BOSSA binaries for your platform:
from http://www.shumatech.com/web/products/bossa

Then 
```
bossac -e -w -v -b -R Marlin.ino.bin
```
Where Marlin.ino.bin is the firmware to flash in bin format

PD2: After a little bit of more testing, even with the latest BOSSA i sometimes have problems and the CPU does not reset, or maybe it is resetting and booting into the bootloader again... This seems to be either a bootloader bug, or something related to the USB stack that does not like to "take over" a running USB interface...

Nevertheless, if you just power down , and then power up, the new firmware will be executed with no issues

**Comment by Bob-the-Kuhn** [comment]
I've re-booted my desktop PC and tried my tablet but can't get Repetier Host nor Pronterface to connect via the native port.

I'm OK with leaving things as they are.  Not good but workable for PC users.

It'd take someone with a lot of Windows, OS, USB & microprocessor knowledge to come up with an elegant solution.  Not too many of those out there.

I'll re-word the title & the description tomorrow & then see what Scott thinks.

**Comment by ejtagle** [comment]
@Bob-the-Kuhn : I tried Pronterface and Repetier Host: On both, after specifying the COM port (connected through Native port), the printer is detected and i can control the printer through their interface. 
As you said, you have already tried your computer, tablet, and none of them work with this.
What i do suspect is a hardware problem on your side, as here i have tried it with 2 different computers , using either USB1.0, USB2.0 and USB3.0 (Win10 64 bits) and no issues so far.
Either cable, USB socket on the Arduino Due, or a faultly SAM3X maybe ?  ... Maybe someone else with another Due could try this and tell us if any problem ? ... 
Because i am unable to reproduce the connectivity problem,The only thing that i can see is that after programming via the native port, the CPU does not properly reset and i have to power it down and then up again to reset it. After that, it works perfectly well. That is the only problem i have ...
The other thing would be to try a 6+ older version of Marlin, one, that does not have the USB stack of Atmel, and see if that fixes the native USB problem or not.
Just for reference, i have tried an small  USB cable (30cm) and a very long one (3m) and no problems with any of these.

**Comment by Bob-the-Kuhn** [comment]
I don't have an older 2.0.x that compiles for DUE & has the USB folder.

I tried it a new DUE with the same results/problems.

I had a devil of a time getting the new DUE to powerup/reset.  I need to do the  [hardware mod](https://arduino.stackexchange.com/questions/48208/arduino-due-not-executing-code-after-power-on) on it.

**Comment by Bob-the-Kuhn** [comment]
Please review the changes I made to the title and description of this PR.

Please comment on the need (or lack of) to reset the board after a download via the native port.

**Comment by ejtagle** [comment]
I agree with the changes to the title.
I am reading about reset sources on SAM3X to figure out if there is a workaround

**Comment by Bob-the-Kuhn** [comment]
Do you do anything in Configuration.h to enable the host interface via the native port?

**Comment by ejtagle** [comment]
First: I think i found the cause of the native port programming not being able to reset the CPU after successful FLASH programming: Seems the RSTC_MR (Reset controller mode register) is reprogrammed by something (perhaps the SAM-BA bootloader, or perhaps a hardware bug/glitch) so it disallows User initiated Resets. This behaviour ONLY happens when the Native port is being used to initiate Flash programming, by invoking the SAM-BA bootloader using a software initiated reset. 
If we use the USB Programming port instead, then the sequence is quite different: The ERASE pin is used (and that is what you fixed in your Arduino) to force a FLASH erase, and then the part is reset, effectively jumping to the SAM-BA bootloader.
The SAM-BA bootloader is what Arduino uses to reprogram FLASH. The last step, after successful FLASH programming is to invoke a User initiated Reset so the part starts executing the new firmware.
BUT, if the bootloader was invoked by the Native port by means of a user initiated reset, then the bootloader inherits or perhaps modifies that RSTC_MR register, and forbids to initiate an extra user initiated reset, thus the bootloader is unable to reset the part.
What i did was, before resetting the part, to reenable user initiated resets, and then jump to the bootloader. It works. This should be implemented as a workaround in the Arduino runtime, but as we are replacing most of the USB stack, i did implement it myself.

Right now Native port programming works for me as expected. So, Programming, Communications (CDC) and MSD are working for me. Please try it yourself, let´s see if that helps with your DUE

**Comment by ejtagle** [comment]
Regarding what i do, set SERIAL_PORT to -1 (-1 means to use the Native port as the communication port). Yes, i know, maybe this is not completely following the standard, but on DUE:
-1 =USB Native Port
0 = USB Programming port (=Hardware USART0 on SAM3X)
1 = Hardware USART1 on SAM3X
2 = Hardware USART2 on SAM3X
3 = Hardware USART3 on SAM3X

**Comment by Bob-the-Kuhn** [comment]
I tried that about 30 minutes ago.  That results in the host and USB mass storage using the native port but I can't download via the native port.

I'll try your updated code.

**Comment by Bob-the-Kuhn** [comment]
The new code does not reset the CPU when the host connects and I can not upload on the native port.

I can disconnect the native port and then upload via the programming port.

There is one strange item.  If the host connects via the native port and then disconnects, the controller goes through reset about 5-10 seconds later.  Nothing strange happens if the host never connects or if the host never disconnects.

I wonder if the native port USB reset routine could just disable all interrupts and then jump directly to the bootloader via the Internal ROM's reset vector at 0x0010 0000, I'll play with that for a bit.

**Comment by ejtagle** [comment]
Yes, there are other ways to force a reset ... But i guess the problem is exactly that: The code that should reset the part is not resetting it. 
## For example, instead of doing, replace the following piece of code in the function resetToBootloader() ##:

 // Reset controller, including pulsing the external Reset line
  RSTC->RSTC_CR =
    RSTC_CR_KEY(RSTC_KEY) |
    RSTC_CR_PROCRST |
    RSTC_CR_PERRST |
    RSTC_CR_EXTRST
    ; 

## With (that does not move the NRST pin... I suspect the problem lies in the NRST pin in your board) ##:

 // Reset controller, including pulsing the external Reset line
  RSTC->RSTC_CR =
    RSTC_CR_KEY(RSTC_KEY) |
    RSTC_CR_PROCRST |
    RSTC_CR_PERRST
    ; 

## Or you can replace it by ##:
`
//Defines so the device can do a self reset
#define SYSRESETREQ    (1<<2)
#define VECTKEY        (0x05fa0000UL)
#define VECTKEY_MASK   (0x0000ffffUL)
#define AIRCR          (* (volatile uint32_t * )0xe000ed0cUL)

// Perform a RESET
AIRCR =(AIRCR & VECTKEY_MASK)| VECTKEY | SYSRESETREQ

## Or finally, If you want to go through the route of jumping ##:

// Restore interrupt table to 0 address
SCB->VTOR = 0;

// Disable all NVIC interrupt sources
NVIC->ICER[0] = 0xFFFFFFFF;
NVIC->ICER[1] = 0xFFFFFFFF;

// Get PC and SP of application region 
uint32_t New_sp  = ((uint32_t*)0)[0];
uint32_t New_pc  = ((uint32_t*)0)[1];

__asm (
				"mov sp, %0\n\t"
				"mov r5, %1\n\t"
				"blx r5\n\t"
				: 							// output
				:"r" (New_sp), "r" (New_pc) // input
				:"r4","r5"					// clobbered register
);

## All of them should work ## ...

**Comment by Bob-the-Kuhn** [comment]
I just looked at your code & I see that you're already playing with the GPNVM bit for FLASH0.  I then looked at the chip after the native port download fails. The Internal ROM is mapped to location 0 and the chip is executing out of the Internal ROM.

I tried changing the GPNVM bits but the best I could do was get the controller to reset & run after a failed download on the native port.

Isn't the USB controller shut down after the RSTC->RSTC_CR command?  If it is then how would the bootloader get any commands via the native port?

**Comment by ejtagle** [comment]
No, the USB controller is not reset. But, the bootloader resets it and reprograms it to act as a CDC device. 
I am sure we can reset to the bootloader, but then the main problem is that the bootloader is unable to reset the part.
The bootloader itself does nothing special to reset the part; Bossac just does the equivalent of

RSTC->RSTC_CR =
RSTC_CR_KEY(RSTC_KEY) |
RSTC_CR_PROCRST |
RSTC_CR_PERRST |
RSTC_CR_EXTRST;

by writing 0x5A00000D to address 0x400E1A00

**Comment by Bob-the-Kuhn** [comment]
Yes, I just was reading about the Internal ROM setting up the native USB port and then looking for programming data from the USB port.

I wonder if I can get a USB analyzer setup on the native port.

**Comment by ejtagle** [comment]
It is strange ... I am pretty sure the problem is the reset 
You can try the following: Connect to the native port, and using any serial terminal, open the COM port in 1200bauds, and close it: This should reset the SAM3X and start execution of the SAM-BA bootloader.
From that point, you can play with the bossac utility: You should notice it works, except for the -R switch

**Comment by ejtagle** [comment]
Well... I got the direct jump to the bootloader thing working... Maybe it could work for you...

**Comment by Bob-the-Kuhn** [comment]
**I AM EMBARRASSED**

☹️

I had failed to compile via Arduino 1.9 beta so I went back to PlatformIO.  All my failed native port uploads have been on PlatformIO.  Now that I have it compiling on 1.9 it DOES upload properly via the native port.

I've found the correct settings for PlatformIO & now it also uploads via the native port.

The only outstanding issue now is the controller resetting 20-25 Seconds after the host disconnects from the native port.  That doesn't happen when the host port is on the programming port.

I'll try your latest code Monday.

I'm really sorry for putting you through so much hell.

**Comment by Bob-the-Kuhn** [comment]
I've verified that the LPC1768 doesn't have the "reset after host disconnects" issue.

**Comment by Bob-the-Kuhn** [comment]
Arduino doesn't like the latest code. Downloading it a second time via the native port, Arduino can't find the upload port.

PlatformIO has no problems downloading it.

Let's abandon this PR.  The current code in 2.0.x works as well as any of these.

I'll open an issue on the Repetier Host disconnect from native port results in reset.

**Comment by ejtagle** [comment]
I'd push the first commit of this PR. Without this PR, the native port can´t be used for programming purposes 👍 .. And that commit mimics what the default arduino USB stack does
According to my investigation, the 1st commit is needed to emulate what arduino does by default when using Arduino CDC USB implementation.
The 2nd commit tends to improve reset when FLASH was successfully programmed using the native port. 
From 3rd commit onwards, probably not required at all.

But, please, dont trust me: Try to program without this PR using the native port and you will see it you just can´t. With the first commit, of this PR, you get the exact realiability of the original Arduino ... No more, no less. I think that is the minimum acceptable 👍

**Comment by Bob-the-Kuhn** [comment]
Agreed - the first commit is the simplest and works as well as the others.

Go ahead and do an interactive rebase and drop the last three commits.

----

>  you get the exact realiability of the original Arduino ... No more, no less.

I've been seeing native port upload fails with both Arduino and PlatformIO.  The fails are "unable to find upload port".

It appears that the bigger the image in the FLASH the more reliable the upload.  See the attached for details.

[uploads.txt](https://github.com/MarlinFirmware/Marlin/files/1809199/uploads.txt)

I haven't seen a fail on the programming port unless the native port is also cabled up.

Looks to me like minimal images can be a problem uploading on the native port but that practical images will be big enough to not be a problem.

**Comment by ejtagle** [comment]
Done

**Pull request merged**
