### PR TITLE
Add example config

### PR DESCRIPTION
**Pull request by Phr3d13**
Add example config for Geeetech's PI3 Pro C

### CODE REVIEW

**Comment by Phr3d13** [comment]
Am I working with the right branch, or should I be using the bugfix 1.1.x? Branch structure has become so confusing.

**Comment by Phr3d13** [comment]
@thinkyhead Should I be making PR's against this branch or the bugfix-1.1.x branch?

**Comment by fiveangle** [comment]
bugfix-1.1.x

**Comment by fiveangle** [comment]
Can you please close this PR and open against bugfix1.1x ?  Alternatively, we have opened up the `bugfix-2.0.x-new-layout` for AVR issues (not just 32-bit), so if you want to test your config against that branch, then submit your change in a PR against `bugfix-2.0.x-new-layout` that one if it all works out, that would probably be best.

**Comment by Phr3d13** [comment]
@fiveangle I have opened a PR against bugfix-1.1.x,  I'll close this one shortly, and when I get home from work, I'll take a look at bugfix-2.0.x-new-layout.

**Comment by Phr3d13** [comment]
Closing this PR

**Pull request closed without merging**
