### PR TITLE
Spindle/Laser pins for RADDS

### PR DESCRIPTION
**Pull request by mjscosta**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

The present pull request adds a new RADDS board variant with support for the laser feature, by remapping some of the original RADDS pins. 

### Benefits

Allows users to use RADDS board with laser feature.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Do you have a link to this laser board's project page? And the laser peripheral?

**Comment by mjscosta** [comment]
I was actually thinking about that, where would it be the official place to document the HW wiring and the details of setting up the board ...

Is there a wiki page on Marlin for those ?

**Comment by thinkyhead** [comment]
The website page on the subject of Laser / Spindle configuration is at http://marlinfw.org/docs/configuration/laser_spindle.html and this can be edited by forking and checking out the https://github.com/MarlinFirmware/MarlinDocumentation repository.

**Comment by thinkyhead** [comment]
No separate board is needed.

**Comment by mjscosta** [comment]
@thinkyhead Thanks!

**Pull request merged**
