### PR TITLE
Updat and move pins_SOVOL_V131.h

### PR DESCRIPTION
**Pull request by ellensp**
### Description

The SOVOL V131 motherboard is basically a clone of the Creality V4 with the addition of TMC UART pins (and a GD32)

Move file to pins/gd32f1

Include Creality_V4 pins and simplify pins_SOVOL_V131

### Requirements

BOARD_SOVOL_V131

### Benefits

Arguably neater.

### Related Issues
https://github.com/MarlinFirmware/Marlin/pull/25267

### CODE REVIEW

**Comment by thinkyhead** [comment]
~~As this GD32F1 processor is intended to be a mostly-compatible clone of STM32F1, and we are still building with the ST-Micro reference platform, I'm not sure we need to move GD32F1 into a separate folder, as if it represented a different MCU family. But, what other distinctions are there for GD32 that could make them worthy of their own separate category?~~

**Comment by thinkyhead** [comment]
Hmm, I see we're already doing that for `BOARD_TRIGORILLA_V006`. I guess we'll carry on, then!

**Comment by ellensp** [comment]
This new e_error doesn't seem to make sense

```
  #error "SOVOL V131 only supports 1 hotend / E-stepper."
  #define E_ERROR 1

```
Is E_ERROR ever set? it is after an #error which stops pre-processing

**Comment by thinkyhead** [comment]
> This new e_error doesn't seem to make sense

It's set in order to suppress a second `#error` message that would potentially be confusing…
```cpp
#if !E_ERROR && (HAS_MULTI_HOTEND || E_STEPPERS > 1)
  #error "Creality v4 only supports 1 hotend / E stepper."
#endif
```
Preprocessing isn't actually stopped by `#error`. It's stopped by a certain number of `#error` as set by `-fmax-errors=5`.

This can be demonstrated with:
```cpp
#define BLAH

#if ENABLED(BLAH)
  #error "ERROR TEST 1"
  #define DID_ERROR 1
#endif

#if !DID_ERROR && ENABLED(BLAH)
  #error "ERROR TEST 2"
#endif
```

**Pull request merged**
