### PR TITLE
Update language_de.h

### PR DESCRIPTION
**Pull request by Kaibob2**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Just ran the script to see if any more are needed, and…
```sh
$ buildroot/share/scripts/findMissingTranslations.sh de
Building list of missing strings...
MSG_ADVANCE_K                       : de
MSG_DELTA_AUTO_CALIBRATE            : de
MSG_DELTA_HEIGHT_CALIBRATE          : de
MSG_FREE_XY                         : de
MSG_MOVING                          : de
```

**Comment by Kaibob2** [comment]
These were exactly my problems. I tried to find the context in ultralcd.cpp but this led to nothing because of  my lag of a delta printer. 
So I just tried to maintain the meaning from `language_en.h`.
@thinkyhead Maybe it should just be merged and we'll see if someone (german with a delta) has a better idea for it.

**Comment by Roxy-3D** [comment]
> @thinkyhead Maybe it should just be merged and we'll see if someone (german with a delta) has a better idea for it.

I think @thinkyhead will be looking at this tonight.   I reviewed all of the other language Pull Requests and felt comfortable merging them.   But I'll leave this one for Thinky to do.    I tend to agree that even if it needs a few small tweaks...  Merging it gets us closer to where it should be.

**Comment by thinkyhead** [comment]
Looks good. In future we can make more allowance for those (likely quite rare) 16 character wide displays.

**Comment by thinkyhead** [comment]
> So far the messages read OK, but I have problems getting the context for the delta messages:
`MSG_FREE_XY`: Does it Mean Marlin will move the print head to a middle position (=away from max/min X/Y position) automatical?
`MSG_DELTA_AUTO_CALIBRATE`: The translation has the meaning of auto calibration, but I have no idea what gets autocalibrated here - I have no delta.
`MSG_DELTA_HEIGHT_CALIBRATE`: Is it for entering a value in the menu or will it execute a probing function like sending `G28 Z`?

@Sebastianv650 A quick search of the code reveals…

- Menu item `MSG_FREE_XY` moves the effector down below the "danger zone" so that XY movement may be done.
- Menu item `MSG_DELTA_AUTO_CALIBRATE` sends `G33 C0` to start the auto calibration procedure with `DELTA_CALIBRATION_DEFAULT_POINTS`.
- Menu item `MSG_DELTA_HEIGHT_CALIBRATE` sends `G33 C1` to start the auto calibration procedure for height.

**Comment by Sebastianv650** [comment]
- Menu item `MSG_FREE_XY` moves the effector down below the "danger zone" so that XY movement may be done.
In this case, "Abstand XY" is not a very helpful text. From a technical viewpoint, I would name this "Z-Achse Freifahren", but I'm afraid this wouldn't be more clear to 90% of the people out there. But maybe this is still better than "Abstand XY".
- Menu item MSG_DELTA_AUTO_CALIBRATE sends G33 C0 to start the auto calibration procedure with DELTA_CALIBRATION_DEFAULT_POINTS.
Then the translation is OK.
- Menu item MSG_DELTA_HEIGHT_CALIBRATE sends G33 C1 to start the auto calibration procedure for height.
Then "Delta Höhe setzen" is not good in my opinion. It has more the meaning of entering a number, like "set the nozzle temperature to 200°C". "Delta Höhe kalibrieren" would be much better, or even without the word "Delta" as there is no other height calibration option on a delta I guess.

**Pull request merged**
