### PR TITLE
Refactored structure of `Configuration.h` and `Configuration_adv.h`

### PR DESCRIPTION
**Pull request by neilbalch**
As described in #17468, I seek to improve the layout of the user-facing `Configuration.h` and `Configuration_adv.h` files to make them more intuitive, especially given the move to VSCode/Atom editors with code folding support.

A refactored `Configuration_adv.h` file is currently in the pipeline, but `Configuration.h` is now available for peer-review.

### CODE REVIEW

**Comment by neilbalch** [comment]
Again, sorry for the double-PR. @Roxy-3D, what do you think so far?

**Review by grauerfuchs — CHANGES_REQUESTED** [review]
Check your changes to platformio.ini against the latest version, please. A number of the edits listed here are reverting approved commits. For instance, the references to the SailfishRGB_LED library were removed because the library is no longer in use. It also looks like some of the dependencies have been reverted to older versions as well.

**Comment by neilbalch** [comment]
Oh, sorry! I'll fix that.

**Comment by neilbalch** [comment]
Got it, @grauerfuchs! Really sorry about that; must have come in when I performed my rebase on the `MarlinFirmware:bugfix-2.0.x` branch. My rebasing and merging skills leave something to be desired, admittedly.

But. more importantly, what do you think about my restructuring ideas?

**Comment by grauerfuchs** [comment]
No worries. It was caught, and that's part of the benefit of open source.

Related, I've noticed that the VSCode platform doesn't always do what we expect when it comes to Git integration. I've had to wipe out my code tree and start from checkout a number of times to eliminate unrecoverable issues it caused.

**Comment by neilbalch** [comment]
Oh, That's interesting, I haven't seen that yet. I wasn't using VSCode's git integration, instead opting for the WSL command line  termainal window.

**Comment by grauerfuchs** [comment]
Ah. Still, no worries. Git is such a flexible platform that the learning curve can get pretty high in unexpected places. Lots of things to keep in mind. I suspect I'm always going to consider myself a beginner when it comes to the platform. There's probably a way to find and fix everything that can happen, but finding it is the trouble.

**Comment by neilbalch** [comment]
No kidding! It took a while to find [this SO post](https://stackoverflow.com/questions/39401290/how-to-keep-only-head-changes-in-a-git-rebase) which saved my bacon to make the rebase for this PR work properly!

Also, this PR is no longer a draft; I just pushed my edits to `Configuration_adv.h`. What do you think? 😄

**Comment by grauerfuchs** [comment]
I like the idea of making it more easily navigable from within the various environments people will use; However, some of the markers were in there for reasons of which I am not aware. It's quite possible that they were for other IDEs. I'm afraid that the limit of my IDE inline documentation/integration/navigation coding comes from the programming of IntelliSense features for Visual Studio (Professional), so I doubt I'd be much help in determining how beneficial it would be for this project. I suspect this one will be entirely up to the maintainers.

**Comment by neilbalch** [comment]
I'm not sure what the application of the `@section` markers are, which I think you are talking about, but the way they were placed would no longer make sense under my reorganization anyway.

The only reference to `@section` markers is [this SO post](https://stackoverflow.com/questions/29070456/laravel-difference-between-yield-and-section) about the Laravel PHP web framework. `@section` also [follows the same pattern as Java doc annotations, but isn't one of the official ones](https://www.tutorialspoint.com/java/java_documentation.htm)...

**Comment by neilbalch** [comment]
^ From rebase onto current `bugfix-2.0.x` branch.

**Comment by thinkyhead** [comment]
Sorry to be a naysayer, but I have to say "nay" to the added noise and added failure-points in the configurations.

The priority is to make a proper configuration tool and conceal the details of the configurations, and I would much rather focus on that effort than keep "rearranging the deck chairs on the Titanic."

**Comment by neilbalch** [comment]
Understandable; sorry to hear that. Is there any way I can help with that effort, @thinkyhead ?

**Comment by thinkyhead** [comment]
This particular job needs someone with Javascript / HTML5 skills who can quickly grasp new APIs and environments. The basics are done so that changes to form fields immediately apply to the config files, and now I just have to build several configuration panels.

Aside from having partners in development, the main thing that helps that progress is for issues to get solved by other smart people, because dealing with lingering issues and users asking me directly for help with their BLTouch probes tends to distract me from these higher goals.

**Comment by neilbalch** [comment]
Actually, once I think about what you said a little more, @thinkyhead, I'm confused.

Aside from a reordering of settings in the configuration files and the introduction of preprocessor directives which [GCC flat out ignores](https://stackoverflow.com/questions/12894454/how-to-remove-gcc-warning-on-pragma-region), nothing was changed about the functionality of the configuration file. They should perform the exact same set of functions exactly the same as the old ones, just with an appearance I think is more intuitive.

And what's to say that the functional configurations for existing printers need to be ported at all? Of course, it would be _good_ to have them follow the same style as the default set, but I'm not sure that is a necessity for the project. I agree that porting them over would be a monumental effort in monotonous refactoring work and QC, so is it really that necessary? I think that having the default config look nice would help people like me understand what they're working with.

I understand that the priority is (and rightly should be) to develop a more clean user-facing UI for printer configuration, but from what I can now see that effort still has a lot of work to complete before it's ready for use by the general public and can deal with the myriad cool and interesting options in Marlin. Your good idea to have a virtual model of the printer next to the configurator which updates in appearance with changes to the configuration looks to me to be a sizeable task in of itself. I still think that this would be a good interim solution to improve the situation while the proper configurator is in development.

Assuming that I'm understanding your concerns properly, I just don't see how this exacerbates an existing problem. I think it's a step in the correct direction while the far more polished interface isn't yet complete.

**Comment by Roxy-3D** [comment]
Personally...   I like the big blocks that tell us what is in a particular section:

//==============================================================
//======================= What is in this area ==========================
//==============================================================

But now they are all gone.    The whole purpose of this exercise is to promote a discussion.   What do other people think.   (Not me...  Not you...  Not Thinky)     What is actually helpful to the user base?    

What ever the user base wants, we can migrate towards that.   But let's make sure it really is something that is helpful and most users want.

**Comment by neilbalch** [comment]
I'd love to help figure out what it is the user base wants, but I'm not sure how that would happen.

**Comment by lrpirlet** [comment]
Well, here is my 2 cents...

I have been following marlin and updating my firmware from version 1.1...

I kindly request that the change for the configuration files do stay small enough so that a tool that visualize the difference between my old and the new configuration is able to keep in track… 
Please observe the **files changed** above… you'll need to manualy act to display the differences… and the difference does NOT align at all... the 'old variable' is not facing the 'new variable'

My experience is that when someone move ONE variable more than about 45 lines appart (that is one screen lenght) or worse move it from configuration to configuration_adv, (not to tell when that variable gets a 'better' name and move far away)… I lose a lot of time, and patience, hunting that variable... 

Adding comments like "this is the section to define your temperature sensor" is ok because it helps see that there is some organization… Propose a "better" layout for the config files that makes comparison useless is to be banned (in my opinion)…

Of course, if we have a really better layout, tied with a major revision… I'll cope with it, cause a major revision implies a switch of thinking ( Yes I went from 1.xyz to 2.uvw and I then examined each and every variable as part of the effort to understand the new layout of the sources files…)

Again, my 2 cents :-)

**Comment by thinkyhead** [comment]
My emphasis is to keep working on "Auto Build Marlin" and –within the very tool we're using to build the firmware– provide a complete UI for configuration so that the text files themselves become less important. With the configurations encapsulated as data structures, we will then be able to churn out the config files (and/or just the enabled settings) in all kinds of formats.

As the project develops it will be easier for others to contribute and help get the UI completed, but I need to put in more time to get the underpinnings completed.

Of course this tool will include quick access to example configs, automated upgrade of configs from older versions of Marlin, and so on.

**Comment by Roxy-3D** [comment]
> I'd love to help figure out what it is the user base wants, but I'm not sure how that would happen.

It happens in a discussion (like this) where everybody that has an opinion can contribute their thoughts.

Most of the major changes that needed to be done, have now been done to the Configuration.h files.   But there may be things we can do to make this or that better.    And one of the important things to learn (and understand) is what can we do to be 'Future Safe' so that it is easier for users to stay current.

**Pull request closed without merging**
