### PR TITLE
Fix multiple issues with 8 extruders

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

Building with 8 extruders encountered multiple build failures.

I've fixed the issues encountered, while enabling 8 extruders in `pins.h` and the GTR pins file.

Caveats:
1. I don't actually have a GTR yet, or anything with 11 stepper drivers to test with
2. I'm not sure if there was a reason for commenting out pins in the GTR pins file, other than `pins.h` only allowing 6 extruders.
3. I have no idea if 8 extruders actually works, or if swaths of code might be missing somewhere.

I added tests both for 8 extruders as well as 3Z + 6E, to make sure the pin definition changes didn't break triple-Z builds.

### Benefits

Enables compiling with 8 steppers. There are likely still other issues, but this opens the door for people to begin trying it.

### Related Issues

None found.

### CODE REVIEW

**Comment by sjasonsmith** [comment]
These tests built fine for me locally, but I ran them from Windows, and _maybe_ with a different STM32 framework. I'll see if I can reproduce this failure on my end and post an update.

**Comment by sjasonsmith** [comment]
The build is failing due to framework-arduinoststm32@=4.10800.200207. I could force it to use an older version, but I'm looking to see if there is a fix for the problem.

**Comment by sjasonsmith** [comment]
I went ahead and prevented updating that framework dependency to 4.0. That had already been done for other STM32 boards using the same HAL, so it makes sense for the GTR to use the same restriction.

**Comment by thisiskeithb** [comment]
> I don't actually have a GTR yet, or anything with 11 stepper drivers to test with

@sjasonsmith: Can you put one to use? I have an extra one with M5 daughterboard I could ship to you if you're in the US.

**Comment by sjasonsmith** [comment]
> > I don't actually have a GTR yet, or anything with 11 stepper drivers to test with
> 
> @sjasonsmith: Can you put one to use? I have an extra one with M5 daughterboard I could ship to you if you're in the US.

I have one on the way, supposedly. It didn’t get shipped before the holiday, so it only shipped about a week ago.

**Pull request merged**
