### PR TITLE
Fix Classic UI for BX

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

I don't know why anyone would use it, but it seems @thisiskeithb like it :-p

I impressed how well our TFT base works. It upscaled to 6x times and even touch works very precise!

### Requirements

Biqu BX

### Benefits

The real benefit is keep all TFT working as intended.

### Configurations

Biqu BX from examples with TFT_CLASSIC_UI

IMG_4512

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> I don't know why anyone would use it, but it seems @thisiskeithb like it :-p

Much appreciated! Maybe someone wants see their UI from across the room 🙂

**Comment by thinkyhead** [comment]
I would like that mode better if we could register drags (and update the screen rapidly) but arrow navigation works ok. Marlin might do something different when it is paired with a rotary encoder.

Anyway, very cool. Thanks!

**Comment by thinkyhead** [comment]
I converted the SWD comment to an option `SWD_DEBUG` that will leave the needed pins unused. That could be applied to other boards with a similar setup.

**Comment by thisiskeithb** [comment]
> I would like that mode better if we could register drags (and update the screen rapidly) but arrow navigation works ok.

The BX TFT in particular does multi-touch, so it is certainly possible to do cool things with it.

**Pull request merged**
