### PR TITLE
Automatic tool migration on runout

### PR DESCRIPTION
**Pull request by studiodyne**
- Needs better translations
- Needs testing

## Advanced Tool change features 
New options for tool changing and tool migration, which transfers settings to another tool to continue the print. Useful to change filament color without interruption, switch spools automatically on filament runout, switch to a different nozzle on an extruder jam, etc.

## Adds

- Tool migration
- Single axis move for parking
- Optional Z raise before / after 'swap retraction'
- Tool change init before swap _(uses **prime** speed for all distances (swap and prime) on the **first** swap, because the firmware cannot recover an extruder not previously retracted/primed/initialized and can break filament if too close)_
- Auto prime starting tool _(Prime the first extruder that starts a print. Must be enabled via G-code before printing to avoid false priming on a host connect that sends `T0` on boot).
- Fan cooling time and speed + retract to avoid ooze / stringing while cooling and ensure better wipe.

### Adds
- Recover feedrate (slow is better with most singlenozzle)
- Extra resume length (fine tune length for better restart)
- G-code priming, to prime an extruder before printing
- G-code disabling of parking and z raise
- `M217` parameters for new options
- …and more.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Rebased and squashed. To update your working copy use Git Console and the following commands:
```
git fetch origin
git checkout ToolMigration
git reset --hard origin/ToolMigration
```

**Comment by studiodyne** [comment]
#### FIRST BUG
```cpp
if (!toolchange_extruder_ready[new_tool])
  unscaled_e_move(0, MMM_TO_MMS(toolchange_settings.prime_speed)); // planner init
```

This is an old bug of marlin , very old , the first extrusion command after a tool change doesn't respect `feedrate_mm_s`
I don't know how to fix , but i know in printing situation there is always a movement before extrusion and it's why this bug never revealed
the bug works on all gear movement ' fw retract too'
I write this line to solve the feedrate initialisation of the planner , if not , planner put the max or the old 

#### SECOND bug
I have opened an issue about it , the false z resuming of the tool change process ' tomorow i wil make a video'

#### THIRD BUG
If you adjust the temp by lcd to fine tune the printing , when migrate , the migration will use the temp before the manual adjustement
Please can you find a idea , to keep the current selected temperature

Thks for working on my feature , i'm really happy to see you have reduce my 25 lines migration menu by 5 lines lol !

**Comment by thinkyhead** [comment]
> I write this line to solve the feedrate initialisation of the planner , if not , planner put the max or the old

It would be good to know the reason. If you have a short G-code script that manifests the bug, I can add logging to try to follow what is happening. And then instead of calling `unscaled_e_move` to "fix" the problem maybe only one line inside of `unscaled_e_move` needs to be used.

**Comment by studiodyne** [comment]
@thinkyhead 
- Impossible to compile , casting type 'signed/not signed' problem here
```cpp
      // Auto mode ON/OFF
      EDIT_ITEM(int3, MSG_TOOL_MIGRATION_END, &migration.last, 0, EXTRUDERS - 1);
```
i have defined temporary  
```cpp
      // Auto mode ON/OFF
      EDIT_ITEM(uint8, MSG_TOOL_MIGRATION_END, &migration.last, 0, EXTRUDERS - 1);
```
- ON LCD , when clic to migrate  printer stop , impossible to go out of the menu,  not on gcode that works fine. `lcd_enqueue_one_now(cmd)` have a problem

- I have posted the video of the bug , in the issue opened [17229](https://github.com/MarlinFirmware/Marlin/issues/17229)

**Comment by thinkyhead** [comment]
> ON LCD , when clic to migrate printer stop , impossible to go out of the menu, not on gcode that works fine. `lcd_enqueue_one_now(cmd)` have a problem

Does it get stuck in a loop and ignore buttons?
Does the knob do anything when the menu is in this condition?

**Comment by studiodyne** [comment]
> Does it get stuck in a loop and ignore buttons?
Does the knob do anything when the menu is in this condition?Does it get stuck in a loop and ignore buttons?
Does the knob do anything when the menu is in this condition?

**Comment by studiodyne** [comment]
News:
Since creation of 'unscaled_move' , I can't repoduce the bug of ' bad feedrate ' , I have all tried , impossible to give you some gcode to see this. I use this code every day , i will test it ' with ' and ' without '  planner feedrate initialisation  and i will inform you If i have found a way to reproduce this issue .

**Comment by studiodyne** [comment]
> 
> 
> > ON LCD , when clic to migrate printer stop , impossible to go out of the menu, not on gcode that works fine. `lcd_enqueue_one_now(cmd)` have a problem
> 
> Does it get stuck in a loop and ignore buttons?
> Does the knob do anything when the menu is in this condition?

The program is not dead , but blocked in the menu , the knob make rotary animation but nothing happen on click , the head stop , no retract or nothing else '
`lcd_enqueue_one_now(cmd)` have a problem

**Comment by studiodyne** [comment]
> 
> 
> News:
> Since creation of 'unscaled_move' , I can't repoduce the bug of ' bad feedrate ' , I have all tried , impossible to give you some gcode to see this. I use this code every day , i will test it ' with ' and ' without ' planner feedrate initialisation and i will inform you If i have found a way to reproduce this issue .

Not sure the bug has disappear , i wi

**Comment by studiodyne** [comment]
@thinkyhead 

BIG ISSUE :lcd_enqueue_one_now have serious problem on all the marlin firmware
All command enqueued by lcd_enqueue_now , freeze the printer  while SD PRINTING

- If i use ' change filament ' or ' tool migration ' in the lcd menu , all is ok
- if i use ' change filament ' or ' tool migration ' or anything that use 'lcd_enqueue_now'  while **sd printing** , the printer FREEZE ' 

Please HELP

For help: In my repository , i have V6 release  and no bug on it , it's not an old version of bugfix ' a few weeks max ' , you can compare

**Comment by thinkyhead** [comment]
> BIG ISSUE :lcd_enqueue_one_now have serious problem on all the marlin firmware

If it is not reported as a separate issue then no one will fix it.

**Comment by studiodyne** [comment]
> 
> 
> > BIG ISSUE :lcd_enqueue_one_now have serious problem on all the marlin firmware
> 
> If it is not reported as a separate issue then no one will fix it.

@thinkyhead 
There is a report of an SD FREEZE issue [17401](https://github.com/MarlinFirmware/Marlin/issues/17401). May be the same issue
Bug is now confirmed by another one
Works on my 2020 03 19 just before the commit of SD FINISH
Impossible to play with migration if LCD commands are down
thks

**Comment by studiodyne** [comment]
@thinkyhead , i have tested this , and some corruption or abberation , fan doesn't start , and the worst is ' all_axes_homed() ' always false after homing and ' of course ' no swap/no park
Need cleaning/rebasing or issue ?
I will test tomorrow the latest changes and i will see if all is right

**Comment by thinkyhead** [comment]
Rebased and brought up to date…
```
git fetch origin
git checkout ToolMigration
git reset --hard origin/ToolMigration
```

**Comment by studiodyne** [comment]
added
- M217 report of V (Value of the activation of FIRST INIT)
- Cleaned/simplified tool_change_prime function
- Some light modifications about homed/not homed in tool change cpp

**Pull request merged**
