### PR TITLE
HAL preview

### PR DESCRIPTION
**Pull request by bobc**
**== Work In Progress ==**

**NB Not tested!**

Here is first part of HAL. The goal of this PR is to get a clean and complete as possible HAL implementation for AVR and Due targets.

## General Principles

All code that is CPU specific (generally any code that refers to an SFR), should be in the HAL folder for that target. 
All application code (in top level folder) should not refer specifically to any target, and should not have sequences of #if AVR .. #elif SAM3x #elif STMF32 etc.
Pin usage is generally *not* part of the HAL, that stays in pins_xxx, except where pin usage has special handling for a target CPU (e.g. SPI).

Subfolders are used to separate HAL targets, this feature is supported by Arduino IDE but subfolders must be in "src".

Note: this PR includes Due support from https://github.com/esenapaj/Marlin which I have re-factored.

If there are any copyright attributions that need adding, please let me know.

## Building

Code compiles for AVR and Due using Arduino IDE v 1.6.13 with packages:
-  Arduino AVR Boads 1.6.15
-  Arduino SAM Boards 1.6.7

Code compiles for Due using Eclipse Mars and Jantje Arduino plugin v3.0.0

To build for AVR targets ARCH_ARDUINO_AVR must be defined
To build for Due targets, ARCH_ARDUINO_SAM must be defined

In Arduino IDE, both of these flags are automatically defined when user selects appropriate target, no other config is necessary. The users must still select the board type as required in Configuration.h

## Files that still need work:

- [ ] endstop_interrupts.h
- [ ] pinsDebug.h
- [ ] printcounter.h
- [ ] Sd2Card.h
- [ ] servo.h
- [ ] stepper.h
- [ ] servo.cpp
- [ ] stepper.cpp
- [ ] temperature.cpp

## Verification tasks

- [x] Build using Arduino IDE
- [x] Build using Eclipse
- [ ] Build using PlatformIO

- [ ] Regression test on AVR targets
- [ ] Test on Due/RADDS
- [ ] Test on Due/RAMPS_FD

## Further tasks

- [ ] Consider requirements for other targets : LPC1768, STMF32F ?

### CODE REVIEW

**Comment by bobc** [comment]
@Roxy-3D Maybe we should wait a bit before merging to see if anyone has comments?

**Comment by Roxy-3D** [comment]
OK...   it should be reverted now.   I think everybody understands the initial code to get up and limping along is going to be a little bit rough.   There will be people (myself included) following behind you making things cleaner.   We can proceed any way you are comfortable.   But my preference would be we don't do things that slow you down. 

I'll be reviewing all the changes so far later today!

**Comment by AnHardt** [comment]
About `endstop_interrupts.h`.

The DUE, like all the ARM processors has no `Pin Change Interrupts`. It does not need them because it has `External Interrupts` on all pins. For the Atmels the macros:
```
digitalPinToPCICR(p)
digitalPinToPCICRbit(p)
digitalPinToPCMSK(p)
digitalPinToPCMSKbit(p)
```
are defined in `arduino_pins.h` - not so for the DUE.

Since these macros are directly related to pins i suggest to add them in `fastio_Due.h`
```diff
@@ -54,6 +54,12 @@
 #define GET_OUTPUT(IO)
 
 /// check if pin is an timer
 #define GET_TIMER(IO)
 
+
+//// dummy functions for, on ARMS, not existing Pin Change Interrupts
+#define digitalPinToPCICR(p) NULL
+#define digitalPinToPCICRbit(p) 0
+#define digitalPinToPCMSK(p) NULL
+#define digitalPinToPCMSKbit(p) 0
 #endif	/* _FASTIO_DUE_H */
```
And in `endstop_interrupts.h`
```diff
@@ -75,13 +75,15 @@
 volatile uint8_t e_hit = 0; // Different from 0 when the endstops shall be tested in detail.
                             // Must be reset to 0 by the test function when the tests are finished.
 
 // Install Pin change interrupt for a pin. Can be called multiple times.
 void pciSetup(byte pin) {
-  *digitalPinToPCMSK(pin) |= bit (digitalPinToPCMSKbit(pin));  // enable pin
-  PCIFR  |= bit (digitalPinToPCICRbit(pin)); // clear any outstanding interrupt
-  PCICR  |= bit (digitalPinToPCICRbit(pin)); // enable interrupt for the group
+  #if defined(PCIFR) && defined(PCICR)
+    *digitalPinToPCMSK(pin) |= bit (digitalPinToPCMSKbit(pin));  // enable pin
+    PCIFR  |= bit (digitalPinToPCICRbit(pin)); // clear any outstanding interrupt
+    PCICR  |= bit (digitalPinToPCICRbit(pin)); // enable interrupt for the group
+  #else
+    UNUSED(pin);
+  #endif
 }
 
 // This is what is really done inside the interrupts.
 FORCE_INLINE void endstop_ISR_worker( void ) {
   e_hit = 2; // Because the detection of a e-stop hit has a 1 step debouncer it has to be called at least twice.
```

These macros should never be used by the ARMs because the first part here always succeeds
```
    #if (digitalPinToInterrupt(X_MAX_PIN) != NOT_AN_INTERRUPT) // if pin has an external interrupt
      attachInterrupt(digitalPinToInterrupt(X_MAX_PIN), endstop_ISR, CHANGE); // assign it
    #else
      // Not all used endstop/probe -pins can raise interrupts. Please deactivate ENDSTOP_INTERRUPTS or change the pin configuration!
      static_assert(digitalPinToPCICR(X_MAX_PIN) != NULL, "X_MAX_PIN is not interrupt-capable"); // if pin has no pin change interrupt - error
      pciSetup(X_MAX_PIN);                                                            // assign it
    #endif
```

**Comment by bobc** [comment]
Thanks, I'll look into that.

**Comment by bobc** [comment]
Is there a way to re-open this PR?

**Comment by Roxy-3D** [comment]
Do mean 'Revert' it?   I thought I did back it out.   I think we better let @thinkyhead clean up the mess I made!    

I went to the 'Closed' PR's and checked its box and then said mark it as 'Open'.   But it won't switch to being Open.      

The first answer at this page seems to say it can not be re-opened:    http://stackoverflow.com/questions/12674304/github-reopening-a-merged-pull-request

My apologies bobc !   I certainly am not trying to make extra work for you!

I also found this:  https://github.com/isaacs/github/issues/361#issuecomment-219088644

> Workaround. Pushed the branch (oops its not on the same commit). Steps to get PR reopened.

- Delete the branch using the button in the GitHub PR.
- Move the branch back to where the last PR sha is locally.
- Push the branch again.
- Reopen the PR.
- Now rebase and what not to your hearts content.
- It's a bit tedious, but it will get you to the desired outcome.

**Comment by thinkyhead** [comment]
@bobc If you haven't already looked at the branch by @esenapaj for Duo, [I highly recommend it.](https://github.com/esenapaj/Marlin/tree/Duo) The stuff that @AnHardt describes is covered pretty well by his `HAL.h` and changes to `fastio.h`.

I've submitted [a few changes](https://github.com/esenapaj/Marlin/pull/175/files) to reduce the need for too many conditional blocks throughout the code. We should prefer using macros that allow us to keep the code more unified and readable where we can.

**Comment by bobc** [comment]
Yes, I am picking up from @esenapaj branch - some great stuff there!

I think I can fix up 32-Bit-RCBugFix and re-open this PR, but only if I do a force-push on 32-Bit-RCBugFix - is that OK?

**Comment by thinkyhead** [comment]
I think you'll need to create a brand new PR due to the branch mangling that was done. This issue doesn't even appear as a PR anymore. You'll need to fetch the new `32-Bit-RCBugFix` branch and rebase your changes on it beforehand.

**Comment by bobc** [comment]
Ok, I think I got it, let's all continue with #5357

**Pull request merged**
