### PR TITLE
General cleanup, mostly MKS UI

### PR DESCRIPTION
**Pull request by thinkyhead**
Gathering changes from #19812 that are unrelated to the new Web GUI to make that PR more simplified.

- Used `#include <lv_conf.h>` for external header.
- Applied `ZERO` macro where possible.
- Fixed some indentation and spacing.
- Tweaked code for readability and conciseness.

### CODE REVIEW

**Comment by rhapsodyv** [comment]
> Removed #include "lv_conf.h" referencing non-existent header.

This header is inside the MKS LVGL repo..... It has the LVGL configs.

**Comment by thinkyhead** [comment]
> This header is inside the MKS LVGL repo..... It has the LVGL configs.

Must this header be added into Marlin before it can be located, or is it found automagically?

**Comment by rhapsodyv** [comment]
> > This header is inside the MKS LVGL repo..... It has the LVGL configs.
> 
> Must this header be added into Marlin before it can be located, or is it found automagically?

It's in the same folder as <lvgl.h>

Explaining: LVGL needs a configuration header, like Marlin. MKS forked LVGL, changed a few things, and added that header to their repo, fully configured for their UI. So, "lv_conf.h" is provided by the lvgl library, pointed by the marlin feature.

This header contains macros with configs. Removing the marlin include can break anything? I don't know, we need to test, as include order is something sensible to macros....

**Comment by rhapsodyv** [comment]
Yes, I added tests for LVGL in `mks_robin_nano35`. But just flashing and testing to see if removing that lv_conf.h include break anything, as it's just a macro file, and without that some defaults would be chosen instead of the configs... But, it could be already been included by the lvgl files... I don't know... needs testing....

**Comment by thisiskeithb** [comment]
I have an MKS Robin Nano 1.2 & 2.0 that I can flash here for testing as well.

**Comment by rhapsodyv** [comment]
> I have an MKS Robin Nano 1.2 & 2.0 that I can flash here for testing as well.

It would be good. I cannot test today. Maybe later tonight.

**Pull request merged**
