### PR TITLE
Add zonestar/anet LCD for SKR mini E3

### PR DESCRIPTION
**Pull request by danandrei96**
### Description

Add option for the Zonestar/Anet LCD controller on the SKR mini E3 board by adding the required pins to the pins file and initialising the ADC for the ADC_KEYPAD_PIN in HAL.cpp

### Benefits
Allows using the default Zonestar/Anet A8 LCD with the BTT SKR mini E3 with minimal changes to the LCD (Must convert to 3.3V)

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Can you add a warning about damaging your LCD if connected to 5V?

**Comment by danandrei96** [comment]
> Can you add a warning about damaging your LCD if connected to 5V?

Hi! Added warning about damaging the board if connecting to 5V from the LCD.
Also fixed a small mistake from earlier

Should be good to go now

**Comment by thisiskeithb** [comment]
I mean something a little more in the user's face in the pins file since this can lead to hardware damage by saying the LCD is supported:

```cpp
#if ENABLED(ZONESTAR_LCD)
 #error "CONNECTING 5V WILL DAMAGE YOUR LCD. Comment out this line to continue."
#endif
```

Is there a link to the full mod? That might be useful to include as well. We can't stop people from plugging in the LCD ahead of time, but at least it'll stop the compiling process to make sure the user knows the potential issue.

**Comment by danandrei96** [comment]
> I mean something a little more in the user's face in the pins file since this can lead to hardware damage by saying the LCD is supported:
> 
> ```c++
> #if ENABLED(ZONESTAR_LCD)
>  #error "CONNECTING 5V WILL DAMAGE YOUR LCD. Comment out this line to continue."
> #endif
> ```
> 
> Is there a link to the full mod? That might be useful to include as well. We can't stop people from plugging in the LCD ahead of time, but at least it'll stop the compiling process to make sure the user knows the potential issue.

That's a very good idea. Sorry, it's the first time I contribute so wasn't sure what the best way to add the warning is.
I actually made a youtube video documenting using the SKR board on the Anet A8 a while ago, which includes an explanation of the mod. I also added some instructions to my thingiverse page for the SKR mini E3 mouting also, so could maybe include the url [https://www.thingiverse.com/thing:3784828](url)

**Pull request merged**
