### PR TITLE
Undefine code for G2/3 for DELTA & SCARA

### PR DESCRIPTION
**Pull request by AnHardt**
Until the G2/3 code works for deltas, scaras deactivating it will save space and prevents from potentially dangerous moves.

### CODE REVIEW

**Comment by AnHardt** [comment]
Temporary fix for #2371.

**Comment by taalabash** [comment]
A smart temporary fix to privent hitting the bed by the extruder if we don't shut the printer off when it reach a g2/g3 code

**Comment by AnHardt** [comment]
Extended the fix a bit.
Now stopping the print when G2/3 was seen, but not implemented. The part can not be printed without G2/3 - is ruined anyway.

**Comment by thinkyhead** [comment]
> Rather than testing to see if either SCARA or DELTA is defined, would it not be better to have a property `IMPLEMENTS_ARC_TRAVEL`

This would be fine, but I think it should be added to `Conditionals.h` and just make it an alias for `!defined(DELTA) && !defined(SCARA)` since it will never be a formal configuration option and hopefully will be able to go away soon.

**Comment by Wackerbarth** [comment]
@thinkyhead - "added to Conditionals.h" 
 I agree. It is quite appropriate to handle many conditions in this manner.

The point being that the condition that affects the code is the "HAS_WHATEVER_PROPERTY" rather than "IS_PARTICULAR_DEVICE".

By convention, you are supplying the
 "IS_PARTICULAR_DEVICE" implies "HAS_WHATEVER_PROPERTY"
 in the Conditionals.h file.

However, within that file, I would prefer to see us use your ENABLED/DISABLED macros and not have constructs such as "!defined(DELTA) && !defined(SCARA)"

**Comment by thinkyhead** [comment]
> within that file, I would prefer to see us use your ENABLED/DISABLED macros

I need to (a) re-roll the PR for that and (b) get it tested quickly so it can be merged. It's such a sweeping change. I've been over it a lot, fixed what I could find, and don't see any mistakes remaining, but I have been hesitant to merge it until more eyes have scanned the changes for typos.

**Comment by Wackerbarth** [comment]
@thinkyhead -- It we split the introduction of ENABLED into 2 parts, We can, trivially, and with minimal risk, define the macros. They can then be used by new features. As the second part, existing features can be converted, piece by piece, as we have the opportunity to examine each one.

**Comment by AnHardt** [comment]
As we are closer to have G2/G3 working on deltas closing this for now.

**Pull request closed without merging**
