### PR TITLE
Implement CRC16, develop mesh allocation table

### PR DESCRIPTION
**Pull request by thinkyhead**
Rebase and some tweaks to #6616

----

 - Add crc16 utility function
 - Implement CRC16 for config store, remove old checksum, increment layout version
 - Move UBL mesh store/load to MarlinSettings; increment UBL_VERSION
 - Begin to lay out MAT structure, prototype functions, etc.
 - Rename ubl.state.eeprom_storage_slot to .storage_slot
 - Misc. optimization
 - Cleanup/standardize/improve some messages

This is a work in progress!

### CODE REVIEW

**Comment by bgort** [comment]
Thanks.  Will try to finish this up this week -- still out of town, but back tomorrow.

Going to try to get the MAT implemented and maybe even flesh out the store/retrieve for other leveling systems, so we can save some EEPROM and they can all coexist.

**Comment by thinkyhead** [comment]
@bgort ~~Actually, there were enough changes to `ubl_G29.cpp` today that this is pretty bodged-up. I'm pretty good at rebasing and resolving merge conflicts, but `g29_what_command` was changed, among other things, and that is one of the bigger parts of this PR. So, it would be better if you tried rebuilding the PR based on the latest code.~~

**Comment by thinkyhead** [comment]
Nevermind, got it!

**Review by Roxy-3D — APPROVED** [review]
So far...  everything looks reasonable...

**Comment by bgort** [comment]
I was nowhere close to ready to implement/merge this, but okay...

EDIT:  Yeah, something doesn't work - the crc fails so stored settings can't be loaded.  As I'd mentioned in the original PR, this hadn't actually been tested.  I'll look into this now.

**Comment by bgort** [comment]
Fixed the borken CRC that was preventing saving/loading in #6772.

Going to look into finishing what I had started now.

**Pull request merged**
