### PR TITLE
Fix bed thermal runaway protection

### PR DESCRIPTION
**Pull request by clefranc**
Fixes a bug found by @ruggb in Release affecting bed thermal runaway protection.

https://github.com/MarlinFirmware/Marlin/issues/2623
https://github.com/MarlinFirmware/MarlinDev/issues/204

### CODE REVIEW

**Comment by clefranc** [comment]
I don't like these fix, do I need to redo them for a cleaner PR?

**Comment by KiteLab** [comment]
@clefranc 
Do you see any advantage of your (this) PR compared to #2266 and #2284?

**Comment by clefranc** [comment]
No, it's the same correction (mine still needs a fix for missing `defined`parenthesis).

It's just that it's not in `Release` anymore, nor 1.0.1, 1.0.2 and 1.0.2-1. Should at least be re-applied to `Release`.

**Comment by Wackerbarth** [comment]
No! It is not a part of "Release". It IS a part of "1.0.x" and therefore will be a part of 1.0.3 if we ever release such.
"Release" points to the code of 1.0.2-1 and will soon point to 1.1.0.

**Pull request closed without merging**
