### PR TITLE
Send action command on M600 to pause streaming service such as octoprint

### PR DESCRIPTION
**Pull request by silentninja1**

### CODE REVIEW

**Comment by silentninja1** [comment]
I was hesitant to add an auto resume, but if desired I could add a config define for action on pause, same as action on kill, as well as an action on resume and if its commented out don't auto resume.

**Comment by thinkyhead** [comment]
PRs need to be based on `bugfix-1.1.x` and should be targeted at that branch. The `1.1.x` branch is for releases only. Please start with a new branch based on `bugfix-1.1.x`, apply your changes to that, and re-submit your PR.

In the process, please make this behavior optional and disabled by default.

**Comment by silentninja1** [comment]
Sounds good. I'll get it in tomorrow. Thanks.

**Comment by silentninja1** [comment]
See Pull #8849

**Pull request closed without merging**
