### PR TITLE
Fysetc Cheetah updates

### PR DESCRIPTION
**Pull request by GerogeFu**
Update platformio.ini to support FYSETC cheetah v1.2 software serial
update FYSETC CHEETAH V12 pins
update FYSETC cheetah v1.2 config example
change TMCStepper lib deps to git address to get the lastest update

### CODE REVIEW

**Comment by teemuatlut** [comment]
Do not use direct git links as it completely bypasses any version control.
I'd rather you request a new release tag if you need a specific commit to accessed by Marlin users.

**Comment by sl1pkn07** [comment]
some deps in the platformio.ini have already direct git links

**Comment by p3p** [comment]
They are not supposed to, @thinkyhead forgets that using them forces windows users to install git as it becomes a build dependency, they should use github zip links even though it makes updating them slightly more difficult. 

Need to remember and go though and clean them up.

**Comment by teemuatlut** [comment]
If you use just the name of the library from the PIO database, it's smart enough to download the lib using the proper method even if you don't have git installed.

**Comment by p3p** [comment]
@teemuatlut sorry, yes if the libraries are available through the platformio library manager that should always be used, my comment was only for the libraries needed to be downloaded from an external source.

**Comment by thinkyhead** [comment]
> They are not supposed to, @thinkyhead forgets that using them forces windows users to install git as it becomes a build dependency, they should use github zip links even though it makes updating them slightly more difficult.

@thinkyhead is the person who originated using and promoting the use of `.zip` links because they bypass the need to have git installed. He must have missed some `.git` links that slipped through during fast and furious HAL development. Please fix them as you find them.

**Comment by p3p** [comment]
> @thinkyhead is the person who originated using and promoting the use of .zip links

Doesn't mean I can't poke you for merging PRs that don't use them :wink:

As a side note using the `Lib Name=https://github.com/lib/archive/master.zip` syntax helps not having lots of libraries called master. I seem to remember I had issues with due when I tried to roll that change out so only use it on the LPC builds.

**Comment by thinkyhead** [comment]
> As a side note using the Lib Name=https://github.com/lib/archive/master.zip syntax helps not having lots of libraries called master. I seem to remember I had issues with due when I tried to roll that change out so only use it on the LPC builds.

Yep. So as I'm off to bed, someone will hopefully gather together the commit IDs of the heads of all those repos for us.

**Pull request merged**
