### PR TITLE
[2.0.x] Implement Due Fast I/O macros

### PR DESCRIPTION
**Pull request by thinkyhead**
Addressing #11141

Implement `GET_INPUT`, `GET_OUTPUT`, `GET_TIMER` for Due.

### CODE REVIEW

**Comment by ejtagle** [comment]
@thinkyhead : This patch is wrong:

```
inline bool _pin_is_output(const int p) {
  const uint8_t pbit = digitalPinToBitMask(p), pport = digitalPinToPort(p);
  const volatile uint8_t *pmodereg = portModeRegister(pport);
  return !!(*pmodereg & pbit);
}
```

First, on SAM3X, digitalPinToBitMask() returns a uint32_t  (because ports are 32 bits)
digitalPinToPort() returns a Pio* type

portModeRegister(), is not exported at all (its definition is commented out in arduino_due_x\variant.h

I´d suggest the following definitions
```
// check if pin is an input
#define _GET_INPUT(IO) ((g_APinDescription[IO].pPort->PIO_OSR & g_APinDescription[IO].ulPin) == 0)

// check if pin is an output
#define _GET_INPUT(IO) ((g_APinDescription[IO].pPort->PIO_OSR & g_APinDescription[IO].ulPin) != 0)

// Check if pin can be used as an "analog" output
// check if pin is a timer
#define _GET_TIMER(IO) \ 
((g_APinDescription[IO].ulPinAttribute & PIN_ATTR_ANALOG) == PIN_ATTR_ANALOG || \
(g_APinDescription[IO].ulPinAttribute & PIN_ATTR_PWM) == PIN_ATTR_PWM || \
(g_APinDescription[IO].ulPinAttribute & PIN_ATTR_TIMER) == PIN_ATTR_TIMER)
```

You can replace, if you want
```g_APinDescription[IO].pPort``` by ```digitalPinToPort(IO) ```
and
```g_APinDescription[IO].ulPin``` by ```digitalPinToBitMask(IO)```

**Comment by thinkyhead** [comment]
Trial-and-error…

**Comment by ejtagle** [comment]
I have checked against the SAM3X headers and datasheet, and it should work, but did not try to compile it... ;)

**Comment by ejtagle** [comment]
digitalPinHasPWM() is properly defined on variant.h for SAM3X, but i have no idea of its meaning, as analogWrite is not using it. It uses the condition i posted to check if a pin is PWM (or analog output) capable ...

Edit: I do suspect digitalPinHasPWM() will work. It excludes the DAC pins (yes, the SAM3X has analog voltage output capabilities, but no board is using them)

**Comment by thinkyhead** [comment]
Well, it's compiling ok. I reduced `GET_TIMER` down to the minimum…
```cpp
#define GET_TIMER(IO) ((g_APinDescription[IO].ulPinAttribute & PIN_ATTR_TIMER) == PIN_ATTR_TIMER)
```

**Comment by ejtagle** [comment]
To be honest, i am not sure if reducing GET_TIMER is correct or not

As far as I understand you should include 2 conditions:PIN_ATTR_PWM  and PIN_ATTR_TIMER.

The reason is that, on SAM3X, some pins can be toggled using HW with a timer, and others with HW PWM. analogWrite() supports both ways, and that should give extra flexibility on the pins that can be used to control the speed of a fan.

**Comment by ejtagle** [comment]
And there are still 

`g_APinDescription[IO].pPort` by `digitalPinToPort(IO)`
and
`g_APinDescription[IO].ulPin` by `digitalPinToBitMask(IO)`

`digitalPinToPort()` and `digitalPinToBitMask()` are macros, so feel free to change all of them ;)

**Comment by ejtagle** [comment]
Just for reference, this is what is contained in the SAM3X headers:
```
/*----------------------------------------------------------------------------
 *        Pins
 *----------------------------------------------------------------------------*/

// Number of pins defined in PinDescription array
#define PINS_COUNT           (79u)
#define NUM_DIGITAL_PINS     (66u)
#define NUM_ANALOG_INPUTS    (12u)
#define analogInputToDigitalPin(p)  ((p < 12u) ? (p) + 54u : -1)

#define digitalPinToPort(P)        ( g_APinDescription[P].pPort )
#define digitalPinToBitMask(P)     ( g_APinDescription[P].ulPin )
//#define analogInPinToBit(P)        ( )
#define portOutputRegister(port)   ( &(port->PIO_ODSR) )
#define portInputRegister(port)    ( &(port->PIO_PDSR) )
#define digitalPinHasPWM(P)        ( g_APinDescription[P].ulPWMChannel != NOT_ON_PWM || g_APinDescription[P].ulTCChannel != NOT_ON_TIMER )

/*
 * portModeRegister(..) should return a register to set pin mode
 * INPUT or OUTPUT by setting the corresponding bit to 0 or 1.
 * Unfortunately on SAM architecture the PIO_OSR register is
 * read-only and can be set only through the enable/disable registers
 * pair PIO_OER/PIO_ODR.
 */
// #define portModeRegister(port)   ( &(port->PIO_OSR) )

/*
 * digitalPinToTimer(..) is AVR-specific and is not defined for SAM
 * architecture. If you need to check if a pin supports PWM you must
 * use digitalPinHasPWM(..).
 *
 * https://github.com/arduino/Arduino/issues/1833
 */
// #define digitalPinToTimer(P)

// Interrupts
#define digitalPinToInterrupt(p)  ((p) < NUM_DIGITAL_PINS ? (p) : -1)
 
```

**Comment by thinkyhead** [comment]
Thanks for the pointers!

**Pull request merged**
