### PR TITLE
SKR E3 Mini V2.0 Fan Bug Fix

### PR DESCRIPTION
**Pull request by bryanhunwardsen**
Description
bugfix-2.0.x (as of 2021-02-13) breaks part cooling fan operation for the SKR E3 Mini 2.0 as such: commands that affect fan state (i.e. M106 P0 S255) have no effect from gcode, octoprint, attached lcd, until/unless any (unrelated) menu action if performed from an attached lcd interface, at which time the fan will enact the correct defined state properly, but will not respond to further state changes until additional menu input happens post state change.

I searched and found the following reddit thread with several user descriptions of the same error:
https://www.reddit.com/r/BIGTREETECH/comments/idyfuq/skr_mini_e3_v20_fan_problem/
Culminating in a user saying that flashing the (BTT) current version resolves the issue.

I went to the BTT repo for this board and found the most recent commit references "fan bug", searching the commit the only changes i could find that would possibly impact fan performance was a (running delta) in the platformio.ini board definitions.

I merged the (running) changes for this block of code/config into my existing local bugfix (vanilla marlin not btt), recompiled, flashed, and the fan now performs as expected.

Requirements
This change is made at a more generic level than this specific board, but I have tested it as necessary for the BTT SKR Mini E3 V2.0 in combination with the BTT TFT35 v3.0 (in emulation mode). I can only assume based on the number of impacted users from the reddit thread, that it extends beyond the/my choice of input screen attached to the board. I have no insight into its impacts on boards that inherit from this block of config, or how it might be implemented for this specific board to minimize side effects to similar boards.

Benefits
Parts Cooling Fan function is restored to expected operational behavior on the listed board for all source of fan state changes.

Configurations
My cfg and cfg_adv are attached but there are no specific changes in them that relate to the fan bug issue, only in that they have the necessary changes to mate with the referenced board/display.
[FanBugCfgs.zip](https://github.com/MarlinFirmware/Marlin/files/5978995/FanBugCfgs.zip)

Also please see the relevant BTT commit as needed:
bigtreetech/BIGTREETECH-SKR-mini-E3@1fc9de3

Related Issues
Fixes a bug.

### CODE REVIEW

**Comment by ellensp** [comment]
380 files changes, I don't think so... something very wrong here.This is normally caused by editing non bugfix branch and creating a PR against bugfix.  You need to start with bugfix.

**Comment by bryanhunwardsen** [comment]
Will do, thank you, I thought it was on bugfix

**Comment by thisiskeithb** [comment]
It’s difficult to tell, but this sounds similar to the speaker / general timer conflicts on the SKR Mini E3 boards (see https://github.com/MarlinFirmware/Marlin/issues/18203), but I’m not sure it should apply outside of those specific boards.

If you have `SPEAKER` enabled, disable it.

**Comment by thinkyhead** [comment]
The PR was created from the `2.0.x` branch instead of the `bugfix-2.0.x` branch. I have rebased it.

**Comment by thisiskeithb** [comment]
With this change, won’t TONE and Software Serial share timer 8? See https://github.com/MarlinFirmware/Marlin/issues/18203#issuecomment-639276317

**Comment by thinkyhead** [comment]
Does adding `-DTONE_TIMER=4` result in Timer 8 being used? We'll need to add a comment to clarify this.

**Comment by CRCinAU** [comment]
I've got one of these boards if you need something tested? (If you don't have one yourself?)

**Comment by thisiskeithb** [comment]
> Does adding `-DTONE_TIMER=4` result in Timer 8 being used? We'll need to add a comment to clarify this.

Sorry, I meant 4:

1 - Used for Fan PWM
2 - Temperature ISR
3 - Disabled because its pins are used by the SD slot. This might not truly be necessary, but it is what happens today.
4 - Software Serial (Needed for Mini E3 1.2 and E3 DIP boards)
5 - Step ISR
6 - Basic Timer (Currently unusable)
7 - Basic Timer (Unusable by most libraries, but might be used by something
8 - Servo / BLTouch

**Review by BROSVORN — APPROVED** [review]

**Review by BROSVORN — APPROVED** [review]

**Comment by thisiskeithb** [comment]
There are likely still conflicts going on with this PR (on the SKR Mini E3 1.2 at least).

See https://github.com/MarlinFirmware/Marlin/issues/18203#issuecomment-779225468

**Comment by rhapsodyv** [comment]
`-DHAVE_SW_SERIAL  -DTONE_CHANNEL=4 -DTONE_TIMER=4` are being added to *all* F1 boards. Is that right? 🤔

**Comment by thisiskeithb** [comment]
> `-DHAVE_SW_SERIAL -DTONE_CHANNEL=4 -DTONE_TIMER=4` are being added to _all_ F1 boards. Is that right? 🤔

Good catch.

There's also still the main issue of Timer 4 conflicting for software serial on the SKR Mini E3 1.2 & DIP boards.

**Comment by thinkyhead** [comment]
So… It sounds like assuming Timer 4 Channel 4 is always free for use by the Tone class is a bad idea. It would be good to add comments to the pins files about which timers / channels are used up and which are free for other uses. We constantly need to reference this data, but it's tedious to dig out of datasheets and platform headers.

**Comment by p3p** [comment]
>  It would be good to add comments to the pins files about which timers / channels are used up and which are free for other uses

If there are board specific framework definitions needing to be passed in the build flags, we do have `BOARD_CUSTOM_BUILD_FLAGS` added for that which is usable in the pins file, although if it is really for all boards in that platformio env then that is the right place for it.

**Comment by thinkyhead** [comment]
~~At the moment any `BOARD_CUSTOM_BUILD_FLAGS` defined by pins files are not being picked up by any build script, and no `BOARD_CUSTOM_BUILD_FLAGS` are currently associated with any feature.~~

In any case, I feel it would be best to add custom build flags at a lower stage that will be easier to port to Arduino IDE (as it matures) and other embedded build systems, so I would recommend simply adding a new `env` entry in `platformio.ini` for any board that needs extra build flags (and if later we need to add build flags in `common-dependencies-post.py based on features it should use a different name).

**Comment by thinkyhead** [comment]
Ah, there it is. The script is picking it up from the list of *all defines* picked up from a pre-compile and shunted into `MARLIN_FEATURES`.

**Comment by p3p** [comment]
It is used for SKR V1.4 to configure the correct pins for the UART, polluting platformio.ini with extra envs that only needed small tweaks to the platform build definitions seems like a bad idea.

**Comment by thinkyhead** [comment]
With happy acceptance that `BOARD_CUSTOM_BUILD_FLAGS` is here to stay, I'd like to return to the original question of how widely this change is safe to apply. From discussion so far, it seems clear that this shouldn't be merged exactly as it is. So, which of the `pins_MYBOARD.h` files do we know should certainly get these added build flags?

**Comment by rhapsodyv** [comment]
Analysis and conclusion: 

Maple code at `STM32F1/cores/maple/tone.cpp` have this:
```cpp
#ifdef STM32_HIGH_DENSITY
// define default timer and channel
        #ifndef TONE_TIMER
        #define TONE_TIMER 8
        #endif
        #ifndef TONE_CHANNEL
        #define TONE_CHANNEL 4
        #endif
#else
        // define default timer and channel
        #ifndef TONE_TIMER
        #define TONE_TIMER 4
        #endif
        #ifndef TONE_CHANNEL
        #define TONE_CHANNEL 4
        #endif
#endif
```
`STM32_HIGH_DENSITY` is defined by maple when mcu is:
```cpp
#elif defined(MCU_STM32F103RC)
#elif defined(MCU_STM32F103RD) || defined(MCU_STM32F103RE)
#elif defined(MCU_STM32F103VC)
#elif defined(MCU_STM32F103VD) || defined(MCU_STM32F103VE)
#elif defined(MCU_STM32F103ZC)
#elif defined(MCU_STM32F103ZD) || defined(MCU_STM32F103ZE)
```
BTT_SKR_MINI_E3 is STM32F103RC, so it get default `#define TONE_TIMER 8` and `#define TONE_CHANNEL 4`.

If we look at the https://github.com/MarlinFirmware/Marlin/blob/03a41021def9513d4a77caf3c82a0733b7686193/Marlin/src/HAL/STM32F1/timers.h#L61, we will see a comment there aware by lib maple tone timer selection, **and ALL marlin F1 timers were done with maple defaults in mind...**

FAN0 on SKR MINI E3 V2 uses `PC6`, that is linked to `timer8` and FAN1 is on `PC7` that is on `timer8` too. This is related to all `STM32F103R` mcu.

So, yes, tone on timer 8 will conflict with fan on PC6 and PC7. **But it will only happens when the board uses a fan PIN that conflicts with other times**. For example: SKR Mini E3 V1 will use `PA8` for FAN0, that uses timer 1, so it will not conflict with tone timer.

**The conclusion is: Surely we can have more boards with this problem, but, as pins vary from board to board, we can't apply this change for every F1 board. It may break more things than fix.**

**My recommendation is for change only this board. Maybe change env for this board. But not all F1.**

And one final question: did you try enabled `FAN_SOFT_PWM`? I didn't test it, but in the code there're 3 methods of fan pwm: fast, soft and "analog" (default). Fast and analog will surely conflict, because fast explicit use the timer of the pin and analog will change the pin function. But `FAN_SOFT_PWM` seems that don't change anything... Maybe it fix the issue... @bryanhunwardsen  can you test it?

**Comment by arcreigh** [comment]
Hello all! I tested this out with my SKR mini e3 v2 board, there are several confusing things about these fan headers,

I believe the naming of the pins is actually reversed. With the current bugfix build and this patch installed the behavior of the parts cooling fan seems to be what the case fan should be. PC7 should be the parts cooling fan according to the BTT documentation. Looking at the pins configuration this is the case. HOWEVER I believe that the silkscreening and or documentation is incorrect. 

Expected behavior is that when the steppers are engaged the case fan is on. 
Current behavior is that the parts cooling fan is on when steppers are engaged. 
Case fan is controllable w/ m106 p0 s255 / m106 / m107 
Part cooling fan is not controllable with any p index and is only on while steppers are. 
While I could swap my cables so that part cooling is on fan0 and case is on fan1 that strays from the documented operation. 

I think the pinning in marlin is inverted from what it should be in addition to this proposed change.

I understand that this particular PR is for a small fix in the platform.io file however I believe there needs to be a deeper look taken into the skr mini e3 boards fan control, I am not sure if the parts and controller fan are supposed to both be able to be controlled by m106 but at current they are not.

**Comment by thisiskeithb** [comment]
> Maybe change env for this board. But not all F1.

We’d probably need yet another set of BigTreeTech `STM32F103RC_btt*` environments (even if they use `extends`) since multiple boards share those four base environments.

**Comment by thinkyhead** [comment]
I've modified this so it will only affect the one board, using:
```cpp
#define BOARD_CUSTOM_BUILD_FLAGS -std=gnu++14 -DHAVE_SW_SERIAL -DTONE_CHANNEL=4 -DTONE_TIMER=4
```
Are all of these additional flags needed?

**Pull request merged**
