### PR TITLE
Fix DWIN Enhanced Tune menu during homing

### PR DESCRIPTION
**Pull request by mriscoc**
If the user is editing a value on Tune menu and an auto home popup is shown, the menu Tune freeze in a value editor after auto home popup closes.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Does this also affect the `crealityui` or `jyersui`?

**Comment by thinkyhead** [comment]
Quick sanity check on `DWIN_ICON_Show` as I'm consolidating some common code…

This is what is in the `enhanced` version:
```cpp
inline void DWIN_ICON_Show(uint8_t libID, uint8_t picID, uint16_t x, uint16_t y) {
  DWIN_ICON_Show(0, 0, 1, libID, picID, x, y);
}
```
…which just sets the `BFI` flag for this:
```cpp
DWIN_Byte(i, IBD%2<<7 | BIR%2<<6 | BFI%2<<5 | libID);  // i.e., 0x20 | libID
```
Meanwhile, all the other e3v2 implementations do the equivalent of…
```cpp
DWIN_ICON_Show(1, 0, 0, libID, picID, x, y);
```
…since they have this:
```cpp
 DWIN_Byte(i, 0x80 | libID);
```
Is this something that I got wrong in doing cleanup of your original PR, or is `BFI` (enhanced background filtering) actually preferred?

**Comment by mriscoc** [comment]
> Does this also affect the `crealityui` or `jyersui`?

My PR, only Enhanced version

**Comment by mriscoc** [comment]
> Quick sanity check on `DWIN_ICON_Show` as I'm consolidating some common code…
> 
> This is what is in the `enhanced` version:
> 
> ```c++
> inline void DWIN_ICON_Show(uint8_t libID, uint8_t picID, uint16_t x, uint16_t y) {
>   DWIN_ICON_Show(0, 0, 1, libID, picID, x, y);
> }
> ```
> 
> …which just sets the `BFI` flag for this:
> 
> ```c++
> DWIN_Byte(i, IBD%2<<7 | BIR%2<<6 | BFI%2<<5 | libID);  // i.e., 0x20 | libID
> ```
> 
> Meanwhile, all the other e3v2 implementations do the equivalent of…
> 
> ```c++
> DWIN_ICON_Show(1, 0, 0, libID, picID, x, y);
> ```
> 
> …since they have this:
> 
> ```c++
>  DWIN_Byte(i, 0x80 | libID);
> ```
> 
> Is this something that I got wrong in doing cleanup of your original PR, or is `BFI` (enhanced background filtering) actually preferred?

That is because Enhanced version use transparent background icons to adapt them better to the color themes.

**Pull request merged**
