### PR TITLE
Macros to optimize away float + 0.0

### PR DESCRIPTION
**Pull request by ramiropolla**
### Description

Using TERN0() for math is not a good idea. In the case of floats, it
might make the compiler emit code for adding/subtracting 0.0f.

### Benefits

It saves a few bytes and a few cycles by not emitting pointless float math code.

### Downsides

It makes the code look less clean though :/

### CODE REVIEW

**Comment by thinkyhead** [comment]
I see that FP standards require it because -0.0 has a different sign from +0.0. Apparently this would also do the trick:
```diff
- x = y + TERN0(OPTION, value);
+ x = y - -TERN0(OPTION, value);
```
…because -0 (int) promotes to +0.0f. But that's not very clear either!

**Comment by thinkyhead** [comment]
The simpler optimization is to add the `-fno-signed-zeros` compile flag, but we cannot easily enforce that for Arduino IDE so these macros are still needed to cover that case.

**Comment by thinkyhead** [comment]
For `mftest -tmega -n1 -y` the build size goes down significantly by adding `-fno-signed-zeros -ffinite-math-only`:
```
Before:

RAM:   [========  ]  81.3% (used 6663 bytes from 8192 bytes)
Flash: [========= ]  88.7% (used 225192 bytes from 253952 bytes)

With compile flags -fno-signed-zeros -ffinite-math-only ...

RAM:   [========  ]  81.5% (used 6675 bytes from 8192 bytes)
Flash: [========= ]  87.3% (used 221684 bytes from 253952 bytes)

Result:
  - Flash usage goes down by a significant 3508 bytes
  - SRAM usage goes up by a mysterious 12 bytes
```

**Comment by thinkyhead** [comment]
Unfortunately it looks like `-ffinite-math-only` would require us to replace `NAN` and `isnan` with our own custom versions. But on the bright side that may be its only meaningful side-effect vis-à-vis Marlin.

**Comment by ramiropolla** [comment]
Thanks! Good catch on the `-fno-signed-zeros -ffinite-math-only` and nan code too (even if it's for some later point in time).

**Pull request merged**
