### PR TITLE
[2.0.x] TMC2130: MSLUT/Linearity Correction

### PR DESCRIPTION
**Pull request by frech-tech**
Hey,

I implemented the MSLUT (Microstepping LookUpTable) for the TMC2130 analog to the Prusa Linearity Correction. I also improved the Prusa Code and put some GCode to set the new MSLUT Table. 
See: set tmc2130_set_wave in stepper.indirection.cpp. 

Should we implement this into Marlin?

PS: There are also some changes to the TMC lib. I also created a request there.

### CODE REVIEW

**Comment by teemuatlut** [comment]
I'd like to ask what's the end goal for the user here?
Prusa Research can tinker with the microstepping table because their hardware is very clearly defined and common for all their machines. They can scope out their motors and make the very fine adjustments they see fit.
We can't do that. We need to support as many printers and their motors as we can, and we can't take a look at how the changes affect each setup. How would the user verify the changes?
If there is that one user who would like to tune their hardware at this level, we essentially have the capability through the `TMC_ADV` macro which allows for any setting to be applied.

If we would want to have this level of tuning available to the end user, I think it would be better to have few easy to use preset tables for the user to choose from and to have an outside sketch (included in the library or at a user repository) to test with. Something similar to what I did with tuning the chopper frequency. But again the question is what is the actual tangible difference to be made?

I also think we shouldn't have the new gcodes added here. All the chopper timing settings and stealthChop parameters I think should be values set once at boot time. Not anything and everything needs to be integrated into Marlin itself. And not everything needs to be live adjustable.

**Comment by oysteinkrog** [comment]
Even for the Prusa i3, users have to do the linearity correction test print if they want to calibrate their printer perfectly :)
I think this is great, now all Marlin users can do the same.

**Comment by thinkyhead** [comment]
This PR needs some updates before it may be considered:

- Don't include your modifications to the configuration files.
- Don't include `_Bootscreen.h`.
- The `Calibration` folder should be moved to `buildroot/share/calibrate` or removed.
- The indentation in `M93x.cpp`, `M94x.cpp`, and `gcode.cpp` needs fixing.
- Unrelated changes pertaining to MAX31865 should be removed.
- Formatting in `stepper_indirection.cpp` is inconsistent with Marlin standards.
- Backslashes at the top of `tmc2130_init` should be removed.
- Unrelated changes to `pins.h` and `pins_*.h` should be removed.

**Comment by thinkyhead** [comment]
Although mentioned and used throughout the code, `TMC_CHOP_CALIBRATION` is never defined.

**Comment by thinkyhead** [comment]
Rebased, squashed, cleaned up…

**Comment by thinkyhead** [comment]
Is there any love for this addition yet?

**Comment by comps** [comment]
For what it's worth, I believe things that vary across multiple prints or printer environments (ie. office working hours) should be runtime-configurable. Anything else doesn't need to.

As such, it would be useful to have spreadCycle / stealthChop / hybrid switch adjustable during runtime (if possible), but parameters specific to the stepper motors that are of the tune-and-forget nature are not really useful beyond the initial tuning (unless there are printers with hot-swappable motors).

What I'd rather have is a ready-made Arduino sketch / PlatformIO program that would guide me through fine tuning of the hardware and get me the thresholds and timings I need for Marlin.
Something [like this](https://github.com/teemuatlut/TMCStepper/blob/master/examples/Calibrate_spreadCycle/Calibrate_spreadCycle.ino) or [this](https://github.com/teemuatlut/TMCStepper/blob/master/examples/Live_tune/Live_tune.ino).

True, it's a gray area - see ie. "M906: TMC Motor Current", which I don't think it's necessary, but it's convenient for most people who don't want to go through the fine tuning.

Similarly, it's questionable whether we should just let the user call TMC library functions via `TMC_ADV()` or abstract the functionality into Marlin "features" like any of the M-codes proposed or @teemuatlut 's "unreleased" `CHOPPER_TIMING` or `ADAPTIVE_CURRENT`.
Personally, I'd rather just call the library (given semi-stable API) if the feature doesn't integrate further into the (Marlin) codebase. If it does (`SENSORLESS_HOMING`), then it's fairly justified as anything else would be a big hack.

Though, again, gray areas ...

**Comment by thinkyhead** [comment]
@teemuatlut — Now that we're using `TMCStepper` should we keep this PR up to date for potential future use?

**Comment by teemuatlut** [comment]
I still think we don't need this. Most users don't have the knowledge to start tuning these settings and those that do, can accomplish the same thing with `TMC_ADV`.
Just about all the new commands are of type "set it and forget it". The only thing of value I see is the ability to turn stealthChop on and off. But that feature I'm looking to integrate with the LCD and there needs to be some additional chopper mode tracking when using sensorless homing.

**Pull request closed without merging**
