### PR TITLE
Try to remove the time lag by reducing the LCD update rate.

### PR DESCRIPTION
**Pull request by yhfudev**
This patch is trying to reduce the time lags caused by the internal U8GLIB update loop,
by splitting the U8G firstPage()/nextPage() in the main loop to several calls.
but bug exists, there's un-updated half screen when switching screen.

@thinkyhead
Can you please test it, because I don't have the delta hardware? The main loop may faster than previous, but the LCD update rates is reduced.

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
Why not simply changing `LCD_UPDATE_INTERVAL` in `ultralcd.h`?

**Comment by yhfudev** [comment]
Because the time of the firstPage()/nextPage() may cause others task delayed. For example, the LCD firstPage()/nextPage()  loop cost 500ms,  while one task needs run once per 100ms, it will cause the task delay 400ms once LCD task run, even the LCD is executed once per hour, even the main loop runs in very fast speed (i.e. loop() runs in 5ms for most time);

This patch splits the firstPage()/nextPage() loop to multiple times, to alleviate this type impact.

**Comment by thinkyhead** [comment]
> the LCD firstPage()/nextPage() loop cost 500ms

Actually, if the stepper ISR needs to interrupt at any point while interrupts are enabled, it will. Including in-between updating screen halves. Breaking up the loop doesn't necessarily open up more time for the interrupt to occur.

> Can you please test it, because I don't have the delta hardware?

I'm literally 1000 miles from any of my 3D printers, sorry.

The reason the half-screen is visible is because controller events are processed in every screen update call. So the screen change occurs after the first half-screen update. You'll need to be more clever. I've done this before. You'll need to add a `next_screen` variable and have the screen handlers set that instead of setting `currentScreen` directly. Then, only after the draw loop is done, copy `next_screen` into `currentScreen`.

Using `LCDVIEW_U8G_CONTINUE` probably isn't exactly going to work either. The handlers will set `lcdDrawUpdate` to something else whenever they process a controller event. You'll have to use a different flag, methinks.

No guarantee that screens will be drawn in only two parts, either. Some may want to be drawn in 3 or 4 iterations.

A more comprehensive solution will need to ensure that screen transitions only occur between full screens, but preserve the ability to process controller events on every call.

**Comment by yhfudev** [comment]
There's no problem if the lcdDrawUpdate is set to something else other than LCDVIEW_U8G_CONTINUE, the system will back to u8g.firstPage() which is desired so that the u8g can start from the begin to draw the new screen.

@thinkyhead
Can you please describe the details of the time issue you mentioned in the https://github.com/MarlinFirmware/Marlin/pull/4747#issuecomment-244603664
How to reproduce the issue?

**Comment by thinkyhead** [comment]
> details of the time issue you mentioned
> "There's definitely a time issue."

All I meant by this is that we know the display update requires a lot of time, and that we're at the edge of what a Mega2560 can handle when combining Delta calculations with a graphical display. So we need to do all we can to reduce that load.

I recently added an option called `DELTA_FAST_SQRT` that I hope will improve delta performance, but it has not been tested or profiled yet. I'm hoping the new algorithm will be fast enough to make a noticeable difference.

``` cpp
#if ENABLED(DELTA_FAST_SQRT)
  /**
   * Fast inverse sqrt from Quake III Arena
   * See: https://en.wikipedia.org/wiki/Fast_inverse_square_root
   */
  float Q_rsqrt(float number) {
    long i;
    float x2, y;
    const float threehalfs = 1.5f;
    x2 = number * 0.5f;
    y  = number;
    i  = * ( long * ) &y;                       // evil floating point bit level hacking
    i  = 0x5f3759df - ( i >> 1 );               // what the f***?
    y  = * ( float * ) &i;
    y  *= ( threehalfs - ( x2 * sq(y) ) );   // 1st iteration
    // y  *= ( threehalfs - ( x2 * sq(y) ) );   // 2nd iteration, this can be removed
    return y;
  }

  #define _SQRT(n) (1.0f / Q_rsqrt(n))

#else

  #define _SQRT(n) sqrt(n)

#endif
```

**Comment by thinkyhead** [comment]
> There's no problem … the system will back to `u8g.firstPage()`

Ah, I see. But right now… It still only draws the bottom half when the screen changes?

**Comment by Sebastianv650** [comment]
I did some testing with this PR:
It works in the main screen, but draws only the lower half when I enter the menu. If the encoder is rotated, the menu "picture" gets completed.
Maybe a function called during the menu entry overwrites lcdDrawUpdate that should be LCDVIEW_U8G_CONTINUE with a new value, therefore always only the of statement

``` cpp
if (lcdDrawUpdate != LCDVIEW_U8G_CONTINUE) {
    pre_action = (enum LCDViewAction) lcdDrawUpdate;
    dot_color = 1 - dot_color;
    u8g.firstPage();
}
```

is called.

**Comment by Sebastianv650** [comment]
Got it, lcdDrawUpdate was realy overwritten by other handlers. I want to do some more tests tomorow before I create the PR, but the concept is definitly working. Let's see if it's fast enough to replace the block LCD on short moves thing..

**Comment by Sebastianv650** [comment]
Good decision to do some tests before starting the PR..
My change works nearly like this PR. If the display is redrawn after 1s, do only the first page. In the next loop (100ms later), to the next page if there is any.
But in fact, this behaves worse than the original draw all pages at once thing. It stutters like hell with my test-gcode. No idea why, maybe checking for nextPage() takes so much extra time?

The LCD draw thing is a beast in any case. I did different approaches that should all do the same thing, but most of them was leading to a corruped display content. Maybe u8glib is very sensitive to timing, how often which thing is called, I have no idea..

**Comment by Sebastianv650** [comment]
Wow, a u8g.nextPage() takes 16.5ms! :flushed: A CURRENTSCREEN() is 21.1ms. ~~So on a LCD like mine with 2 pages, we can speed up the LCD redraw by 25% by only replacing while u8g.nextPage() with a for loop - we just have no know how many pages the LCD is using in advance.~~ Ignore this stupid entry..

**Comment by Blue-Marlin** [comment]
During 'nextPage()' the data is transferred from the screen buffer to the display. That's the pace where we try to fight every 'nop'.

**Comment by olikraus** [comment]
u8g.nextPage() indeed only transfers the page buffer to the GLCD. 
I had studied the code here for a while. One cause of the half screen bug might be, that the content, which is drawn by CURRENTSCREEN() has changed, but the picture loop is not restarted. 
It is important here to reset lcdDrawUpdate is such a why that the u8g.firstPage() is reexecuted as soon as CURRENTSCREEN() would produce a different screen.
U8glib should not be sensitive to timing, but it requires that the same graphics commands are sent for all the iterations of the first/next loop.

**Comment by olikraus** [comment]
ok, I might be wrong, but in ultralcd.cpp in line 374 along with changing the screen, also lcdDrawUpdate is assignged:

```
      currentScreen = screen;
      lcdDrawUpdate = LCDVIEW_CLEAR_CALL_REDRAW;
```

However, the update of lcdDrawUpdate is missing after lines 2278 and 2282.  
So I guess, that the insertion of 

```
      lcdDrawUpdate = LCDVIEW_CLEAR_CALL_REDRAW;
```

in lines 2279 and 2283 will fix the half screen bug.

**Comment by yhfudev** [comment]
The half-screen problem still exists after placing "lcdDrawUpdate = LCDVIEW_CLEAR_CALL_REDRAW;" in every where the currentScreen updated.
I tested the patch today, ~~and suspect that the half-screen problem may be caused by U8G~~.

Here's my code:

``` C++
  ...

  if (ELAPSED(ms, next_lcd_update_ms)) {

// I added the traces
SERIAL_ECHOPAIR("\n ms time : ", ms);
SERIAL_ECHOPAIR("\n next_lcd_update_ms time : ", next_lcd_update_ms);

// I move the line
// next_lcd_update_ms = ms + LCD_UPDATE_INTERVAL;
// to the end of this if statement to continue the u8g update loop
  ...

      #if ENABLED(DOGLCD)  // Changes due to different driver architecture of the DOGM display
      static enum LCDViewAction pre_action = LCDVIEW_NONE;
      static int8_t dot_color = 0;
        if (lcdDrawUpdate != LCDVIEW_U8G_CONTINUE) {
          SERIAL_ECHOPAIR("\nold lcdDrawUpdate : ", lcdDrawUpdate);
          pre_action = (enum LCDViewAction) lcdDrawUpdate;
          dot_color = 1 - dot_color;
          u8g.firstPage();
        }
          SERIAL_ECHOPAIR("\nu8g draw page, lcd= ", lcdDrawUpdate);
          lcd_setFont(FONT_MENU);
          u8g.setPrintPos(125, 0);
          u8g.setColorIndex(dot_color); // Set color for the alive dot
          u8g.drawPixel(127, 63); // draw alive dot
          u8g.setColorIndex(1); // black on white
          CURRENTSCREEN();
        if (u8g.nextPage()) {
           lcdDrawUpdate = LCDVIEW_U8G_CONTINUE;
           SERIAL_ECHOPAIR("\nu8g lcdDrawUpdate : ", lcdDrawUpdate);
        } else {
           lcdDrawUpdate = pre_action;
           SERIAL_ECHOPAIR("\nrestore lcdDrawUpdate : ", lcdDrawUpdate);
        }
      #else
        CURRENTSCREEN();
      #endif
      ...

    // don't update the time until the u8g update loop finished.
    if (lcdDrawUpdate != LCDVIEW_U8G_CONTINUE) {
      next_lcd_update_ms = ms + LCD_UPDATE_INTERVAL;
    }
  }
}


```

Here's the trace when I pressed the button and the screen switched to menu and only half of the screen were updated:

```
 ms time : 7634
 next_lcd_update_ms time : 7634
 ms time : 7734
 next_lcd_update_ms time : 7734
 ms time : 7843
 next_lcd_update_ms time : 7834
old lcdDrawUpdate : 1
u8g draw page, lcd= 1
u8g lcdDrawUpdate : 5
 ms time : 7885
 next_lcd_update_ms time : 7834
u8g draw page, lcd= 5
restore lcdDrawUpdate : 1
 ms time : 7985
 next_lcd_update_ms time : 7985
 ms time : 8085
 next_lcd_update_ms time : 8085
 ms time : 8185
 next_lcd_update_ms time : 8185
```
1. The code flow entered to the u8g update block at time 7843,
   and called u8g.firstPage() and CURRENTSCREEN()
2. At time 7885, it called CURRENTSCREEN() and restored the lcdDrawUpdate

So it called the u8g block two times to finish the menu screen update which is similar to what it did in "status screen".

**Comment by olikraus** [comment]
maybe i missed this, but:
1) Which half screen is drawn? The upper or the lower half?
2) What is displayed on the part which not draw? Is it just empty?

**Comment by olikraus** [comment]
Regarding the trace: I still think the problem is caused by a sudden change of CURRENTSCREEN. Can you print the function pre behind CURRENTSCREEN.

**Comment by yhfudev** [comment]
halfscreen

**Comment by olikraus** [comment]
It basically confirms my assumption, that the value of currentScreen changes without resetting lcdDrawUpdate().

Can you log also the pointer value of currentScreen? Also the value before you press the button would be required.

**Comment by yhfudev** [comment]
@olikraus You're right, the variable currentScreen is changed in CURRENTSCREEN(). I fixed it and it works now.

**Comment by thinkyhead** [comment]
I've rebased, squashed, and tweaked this at #5239. @yhfudev is it working well now?

**Pull request closed without merging**
