### PR TITLE
Separate Z_PROBE_ALLEN_KEY from MECHANICAL_PROBE

### PR DESCRIPTION
**Pull request by ghost**
Separate Z_PROBE_ALLEN_KEY from MECHANICAL_PROBE

This PR separate conglutinated `Z_PROBE_ALLEN_KEY` and `MECHANICAL_PROBE`.
I hope that This PR will settle confusion about vanishing of Allen Key
in discussion in PR #3672(Cleanup and consolidate probe conditionals for clarity).
Cause of confusion is my [thoughtless implementation for `MECHANICAL_PROBE`](https://github.com/MarlinFirmware/Marlin/pull/3491/files).
I'm regretting what I’ve done.

 And, This PR add stowing process to `Gcode_G29()` for the `MECHANICAL_PROBE`.

### CODE REVIEW

**Comment by jbrazio** [comment]
I would prefer to keep it as is a just update the documentation.

**Comment by Roxy-3D** [comment]
After we go Golden with a Release Candidate...  We should consider renaming the Allen Key stuff.   We need a name for a probe that is deployed and retracted with a special path of movement.   And many Allen Key probes would be in that class.

**Comment by Blue-Marlin** [comment]
@Roxy-3DPrintBoard 
All probes need a longer or shorter path and some special actions to deploy/stow. The trick is to squeeze _all_ that actions into deploy/stow() so the rest of Marlin has not to think about different probes but handles a _universal_ probe.

**Comment by thinkyhead** [comment]
@esenapaj

This PR would change behavior in some places, I think. I believe there is some code that relies on `MECHANICAL_PROBE` being set, even when using `Z_PROBE_ALLEN_KEY`. Or, do you know of some code blocks where `MECHANICAL_PROBE` **_should not_** be enabled, but where `Z_PROBE_ALLEN_KEY` _**should be**_ enabled?

**Comment by Roxy-3D** [comment]
> All probes need a longer or shorter path and some special actions to deploy/stow. The trick is to squeeze all that actions into deploy/stow() so the rest of Marlin has not to think about different probes but handles a universal probe.

OK.   That is a good way to think about it.   Especially if some probes need a NULL movement (like induction probes) to be deployed.  In that case we want to design such that a given probe type is always allowed to move around to deploy and retract.

After we go Golden, we should also discuss if MECHANICAL_PROBE is a good name.  It would seem MANUALLY_DEPLOYED would be a lot clearer.

**Comment by thinkyhead** [comment]
> After we go Golden, we should also discuss if MECHANICAL_PROBE is a good name. It would seem MANUALLY_DEPLOYED would be a lot clearer.

Are these equivalent concepts? There are probes that should pause at the start to ask you to deploy them, and then there are probes which are attached to the nozzle, which don't need deployment or stowage, but also don't need to pause for manual deployment or stowing.

> squeeze all that actions into deploy/stow

Yes. In all cases, "deploy" should at least mean "enable the probe" (the software flag for it).

**Comment by Blue-Marlin** [comment]
https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/Marlin_main.cpp#L3233

is the only place where the definition of `MECHANICAL_PROBE` is _used_.

The history is

```
-    #elif ENABLED(Z_PROBE_ALLEN_KEY) || (ENABLED(DELTA) && SERVO_LEVELING)
+    #elif ENABLED(MECHANICAL_PROBE) || (ENABLED(DELTA) && SERVO_LEVELING)
```

`MECHANICAL_PROBE` should do exactly the same as `FIX_MOUNTED_PROBE` was ought for. It should do nothing but calling `endstops.enable_z_probe()` when deployed and calling `endstops.enable_z_probe(false)` when stowed.

```
     #if ENABLED(Z_PROBE_SLED)
       dock_sled(false); // engage (un-dock) the Z probe
-    #elif ENABLED(MECHANICAL_PROBE) || (ENABLED(DELTA) && SERVO_LEVELING)
+    #endif
-      deploy_z_probe();
+    deploy_z_probe();
-    #endif
```

should be save here. All probes need to be activated. Those not having a special action in `deploy_z_probe()` are just activated. Activating twice does not matter. I guess that was missed for `FIX_MOUNTED_PROBE` and was the reason for introducing `MECHANICAL_PROBE`.

On the other side i'm not sure if a `MECHANICAL_PROBE` is always (ever?) deactivated.

**Comment by Roxy-3D** [comment]
> On the other side i'm not sure if a MECHANICAL_PROBE is always (ever?) deactivated.

On my lame Geeetech Delta printer...  Its Allen Key probe is Manually deployed.  It can not be deployed by sweeping through a certain path.   I have to manually rotate it and let it drop.   At the end of probing, I have to manually stow it.

**Comment by Blue-Marlin** [comment]
@Roxy-3DPrintBoard 
I'm talking about `endstops.enable_z_probe()`. Switching on/off the probe-test in the stepper IRQ.
That has also be done for your probe. Especially for a Allen key Probe. Deactivating makes sense because of its being triggered when stowed. #3717 looks as if `ENDSTOPS_ONLY_FOR_HOMING` is not active and there is a timing problem. For `Z_PROBE_ALLEN_KEY` the `endstops.enable_z_probe(false)` is likely too late in `stow_z_probe()`. It looks as if the z-min-endstop is triggered when the probe touches the thingy to push the probe back.

**Comment by ghost** [comment]
@thinkyhead 
 I believe this PR doesn't change any behavior.
Because essence of implementation of `MECHANICAL_PROBE` is [changing only one line in Marlin_main.cpp](https://github.com/MarlinFirmware/Marlin/pull/3491/files#diff-1cb08de130a6ece2d1b5b9c37bcfef48).

---
- [Before implementation of `MECHANICAL_PROBE`](https://github.com/MarlinFirmware/Marlin/pull/3491/files#diff-1cb08de130a6ece2d1b5b9c37bcfef48L3100)

``` cpp
    #if ENABLED(Z_PROBE_SLED)
      dock_sled(false); // engage (un-dock) the Z probe
    #elif ENABLED(Z_PROBE_ALLEN_KEY) || (ENABLED(DELTA) && SERVO_LEVELING)
      deploy_z_probe();
    #endif
```

When `Z_PROBE_ALLEN_KEY` enabled -> `deploy_z_probe();`

---
- [Implementation of `MECHANICAL_PROBE`](https://github.com/MarlinFirmware/Marlin/pull/3491/files#diff-1cb08de130a6ece2d1b5b9c37bcfef48R3100)

``` cpp
  #if ENABLED(Z_PROBE_ALLEN_KEY)
    #define MECHANICAL_PROBE
  #endif
```

``` cpp
    #if ENABLED(Z_PROBE_SLED)
      dock_sled(false); // engage (un-dock) the Z probe
    #elif ENABLED(MECHANICAL_PROBE) || (ENABLED(DELTA) && SERVO_LEVELING)
      deploy_z_probe();
    #endif
```

When `Z_PROBE_ALLEN_KEY` enabled -> `deploy_z_probe();`
When `MECHANICAL_PROBE` enabled -> `deploy_z_probe();`

---
- [This PR](https://github.com/MarlinFirmware/Marlin/pull/3725/files#diff-1cb08de130a6ece2d1b5b9c37bcfef48R3237)

``` cpp
    #if ENABLED(Z_PROBE_SLED)
      dock_sled(false); // engage (un-dock) the Z probe
    #elif ENABLED(MECHANICAL_PROBE) || ENABLED(Z_PROBE_ALLEN_KEY) || (ENABLED(DELTA) && SERVO_LEVELING)
      deploy_z_probe();
    #endif
```

When `Z_PROBE_ALLEN_KEY` enabled -> `deploy_z_probe();`
When `MECHANICAL_PROBE` enabled -> `deploy_z_probe();`

---

And, I tested `MECHANICAL_PROBE` of this PR with my delta before submitting this PR.

**Comment by thinkyhead** [comment]
Brain fuzz prevents me from dealing with this now. Tomorrow, after needed sleep….

**Comment by ghost** [comment]
@thinkyhead 

> do you know of some code blocks where MECHANICAL_PROBE should not be enabled, but where Z_PROBE_ALLEN_KEY should be enabled?

I think those that those are as below.
But perhaps my knowledge is wrong.
Because my coding skill is poor, my knowledge about Marlin is poor too...

| `Gcode_G28()` and `homeaxis()` | `Gcode_G29()` |
| :-: | :-: |
| ver1.0 | ver2.1 |
| gcode_g28_and_homeaxis | gcode_g29 |

| `deploy_z_probe()` | `stow_z_probe()` | `dock_sled()` |
| :-: | :-: | :-: |
| ver1.6 | ver1.5 | ver1.0 |
| deploy_z_probe | stow_z_probe | dock_sled |

**Comment by ghost** [comment]
@jbrazio 

> I would prefer to keep it as is a just update the documentation.

Excuse me, I can't grasp the intent of that comment because my poor skill of English.
What should I do?

**Comment by thinkyhead** [comment]
Let me take a look closer at these flow-charts (nice!) and then I will comment further.

I do expect the code to improve (in 1.1.1 and up) so that the flow is clearer. As others have suggested, the `deploy_probe` and `stow_probe` functions can probably contain all the logic for deploy and stow. Right now this logic is distributed in a few places. Also we will be most likely make a unified class to do probing of all kinds, because (for example) the "manual bed leveling" way of measuring Z is **just another way to probe**, when you add it up.  Flowcharts like these will be very helpful to the process.

**Comment by jbrazio** [comment]
This is a tricky subject, does it worth to mess with it near the end of the RC cycle ?
BTW, as usual, great work @esenapaj !

**Comment by thinkyhead** [comment]
> worth to mess with it near the end of the RC cycle?

If it's a bug or "causing" bed crashes, then perhaps so. But I did try to emphasize that we should hold off on any real reform until 1.1.1.

**Comment by ghost** [comment]
I realized that current implementation of `MECHANICAL_PROBE` hasn't stowing process.
Thus I examined and tested few plans, then I've added code for stowing process into the lower part of `Gcode_G29()` that it's a junction of all probes. 
This implementation isn't smart, but I think it's simple and safety.
And, I've reflected this change to flowchart of `Gcode_G29()` and `stow_z_probe()`.

**Comment by ghost** [comment]
@Blue-Marlin
I'm understanding meaning of your comment gradually.
It seems that a routine of the `FIX_MOUNTED_PROBE` in `Gcode_G29()` of current official Marlin isn't only doesn't call `deploy_z_probe()` but also doesn't call `stow_z_probe()`.
Thus I created experimental branch, and I added deploying and stowing process to routine of the `FIX_MOUNTED_PROBE` in `Gcode_G29()`.
It has enabled to support "mechanical probe" by `FIX_MOUNTED_PROBE`.
I confirmed it by test with my delta which has "mechanical probe".
I think that the `MECHANICAL_PROBE` can be united with the `FIX_MOUNTED_PROBE` in the not too distant future.

link to the experimental PR and changed flowchart of experiment are below.
[Experimental PR](https://github.com/esenapaj/Marlin/pull/136)

Flowchart

| `Gcode_G28()` and `homeaxis()` | `Gcode_G29()` |
| :-: | :-: |
| ver1.0-ex | ver2.0-ex |
| gcode_g28_and_homeaxis-ex | gcode_g29-ex |

| `deploy_z_probe()` | `stow_z_probe()` |
| :-: | :-: |
| ver1.6-ex | ver1.5-ex |
| deploy_z_probe-ex | stow_z_probe-ex |

**Comment by thinkyhead** [comment]
For my own comprehension, I might need to turn these flowcharts into simple lists of actions, one for each probe type. Then compare those lists to **what we want** to happen. And then get straight in my head the differences between probe types. Because from my understanding the `FIX_MOUNTED_PROBE` is not the same as the `MECHANICAL_PROBE` (this is news to me if they are the same thing). And if `Z_PROBE_ALLEN_KEY` is not (mostly) a `MECHANICAL_PROBE` then I need to see it spelled out how they differ in terms of their action.

How about we produce a nice concise design description for each one? For example:

#### `SERVO_PROBE`

**Z Homing:**
- Raise Z axis to make room for servo
- Deploy the servo arm
- Logically enable the probe switch (a physical endstop switch or pushbutton)
- Perform a "fast probe" with the Z axis
- Perform a "slow probe" (bump) with the Z axis
- Logically disable the probe switch
- Raise Z axis to make room for servo
- Stow the servo arm
- Move Z back down to "zero"
- Call `set_axis_is_at_home(Z_AXIS)` to set Z to the home position for Z

**Z Probing:**
- Raise Z based on preferred "before probing" value
- Move to a probe point
- Raise Z axis (if needed) to make room for servo
- Deploy the servo arm
- (1) Logically enable the probe switch (a physical endstop switch or pushbutton)
- Perform a "fast probe" with the Z axis
- Perform a "slow probe" (bump) with the Z axis (if desired)
- Logically disable the probe switch
- Store the Z position for the point (for plane calculation)
- Raise the Z axis in prep to move
- Optionally:
  - Raise Z axis additionally to make room for servo
  - Stow the servo arm
- Move to the next point
- Optionally:
  - Raise Z axis (if needed) to make room for servo
  - Deploy the servo arm
- Loop back to (1) for the rest of the points
- Raise Z axis to make room for servo
- Stow the servo arm
- Apply the saved points to the bed leveling equation

Then we can use these descriptions to ensure that every probe type is following the correct path. And we can probably use it to define some distinct stages for each of these processes (homing, leveling).

**Comment by thinkyhead** [comment]
Apparently this needs a rebase now.

@esenapaj I'm getting to know this portable oscilloscope. It's quite a nice "piece of kit." And it's open source too… That's the spirit!

**Comment by ghost** [comment]
Hum, it seems that deploying process was added to routine of the `FIX_MOUNTED_PROBE` by official commit.
I've reflected that change to flowchart of `Gcode_G29()`, and I've rebased this PR.

Anyway, sequences of probes are still chaotic zone for me...

@thinkyhead
I'm glad that you liked it.

**Comment by thinkyhead** [comment]
How much testing is this getting, and how much confidence is there in these changes? I'm hesitant to merge this PR unless I know it won't have side-effects. But I don't see enough real testing feedback yet.

**Comment by ghost** [comment]
> How much testing is this getting

The total count of test is four times until yesterday.
Today, I did over four times for recording logs and taking videos.
Therefore total count of test is over eight times until today.

Configs:
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/266676/Configuration.txt)
[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/266675/Configuration_adv.txt)

Commands from Repetier-Host:
(notes: many `g0` commands are test for gap between nozzle and bed) 

```
m502
m500
g28
g29
g0 f1000 x0 y0 z0
g0 f1000 x0 y75 z0
g0 f1000 x64.95 y37.5 z0
g0 f1000 x64.95 y-37.5 z0
g0 f1000 x0 y-75 z0
g0 f1000 x-64.95 y-37.5 z0
g0 f1000 x-64.95 y37.5 z0
g0 f1000 x0 y75 z0
g0 f1000 x64.95 y-37.5 z0
g0 f1000 x-64.95 y-37.5 z0
g0 f1000 x0 y75 z0
g0 f1000 x0 y-75 z0
g0 f1000 x-64.95 y37.5 z0
g0 f1000 x64.95 y37.5 z0 
g0 f1000 x0 y-75 z0
g0 f1000 x-64.95 y-37.5 z0
g0 f1000 x64.95 y37.5 z0
g0 f1000 x64.95 y-37.5 z0
g0 f1000 x-64.95 y37.5 z0
g0 f1000 x0 y0 z0
```

Log (with this PR):

```
21:48:28.065 : N57 M502*22
21:48:28.068 : echo:Hardcoded Default Settings Loaded
21:48:31.296 : N59 M500*26
21:48:32.410 : echo:Settings Stored (425 bytes)
21:48:34.520 : N61 G28*36
21:48:36.285 : X:0.00 Y:0.00 Z:338.00 E:0.00 Count X: 106687 Y:106687 Z:106687
21:48:39.007 : N63 G29*39
21:48:39.012 : G29 Auto Bed Leveling
21:49:15.895 : -0.75 -0.61 -0.52 -0.51 -0.50 -0.49 -0.48
21:49:15.899 : -0.72 -0.56 -0.45 -0.40 -0.38 -0.37 -0.36
21:49:15.899 : -0.66 -0.52 -0.38 -0.28 -0.26 -0.24 -0.26
21:49:15.903 : -0.52 -0.42 -0.31 -0.23 -0.19 -0.16 -0.15
21:49:15.903 : -0.49 -0.38 -0.26 -0.19 -0.13 -0.09 -0.09
21:49:15.907 : -0.44 -0.34 -0.25 -0.16 -0.10 -0.02 0.00
21:49:15.907 : -0.39 -0.31 -0.26 -0.16 -0.08 0.01 0.09
21:49:17.665 : X:14.00 Y:46.00 Z:49.18 E:0.00 Count X: 44016 Y:46613 Z:52083
21:49:22.078 : N74 G0 X0 Y0 Z0 F1000*54
21:49:22.078 : N75 G0 X0 Y75 Z0 F1000*5
21:49:22.078 : N76 G0 X64.95 Y37.5 Z0 F1000*65
21:49:22.078 : N77 G0 X64.95 Y-37.5 Z0 F1000*39
21:49:26.482 : N78 G0 X0 Y-75 Z0 F1000*37
21:49:29.967 : N79 G0 X-64.95 Y-37.5 Z0 F1000*4
21:49:36.402 : N80 G0 X-64.95 Y37.5 Z0 F1000*47
21:49:36.402 : N81 G0 X0 Y75 Z0 F1000*14
21:49:42.750 : N82 G0 X64.95 Y-37.5 Z0 F1000*45
21:49:45.938 : N83 G0 X-64.95 Y-37.5 Z0 F1000*1
21:49:45.938 : N84 G0 X0 Y75 Z0 F1000*11
21:49:49.104 : N85 G0 X0 Y-75 Z0 F1000*39
21:49:54.760 : N86 G0 X-64.95 Y37.5 Z0 F1000*41
21:50:00.457 : N87 G0 X64.95 Y37.5 Z0 F1000*79
21:50:06.150 : N88 G0 X0 Y-75 Z0 F1000*42
21:50:19.531 : N89 G0 X-64.95 Y-37.5 Z0 F1000*11
21:50:19.531 : N90 G0 X64.95 Y37.5 Z0 F1000*3
21:50:32.092 : N91 G0 X64.95 Y-37.5 Z0 F1000*47
21:50:35.356 : N92 G0 X-64.95 Y37.5 Z0 F1000*44
21:50:35.356 : N93 G0 X0 Y0 Z0 F1000*63
```

Log (without this PR):

```
23:22:26.331 : N19 M502*28
23:22:26.334 : echo:Hardcoded Default Settings Loaded
23:22:31.210 : N22 M500*22
23:22:32.323 : echo:Settings Stored (425 bytes)
23:24:21.245 : N59 G28*47
23:24:24.418 : N61 G29*37
23:24:26.562 : X:0.00 Y:0.00 Z:338.00 E:0.00 Count X: 106687 Y:106687 Z:106687
23:24:26.564 : G29 Auto Bed Leveling
23:25:03.456 : -0.69 -0.56 -0.49 -0.46 -0.47 -0.47 -0.47
23:25:03.456 : -0.68 -0.52 -0.42 -0.36 -0.35 -0.35 -0.36
23:25:03.460 : -0.61 -0.48 -0.35 -0.26 -0.23 -0.23 -0.24
23:25:03.460 : -0.49 -0.39 -0.29 -0.21 -0.17 -0.14 -0.13
23:25:03.465 : -0.45 -0.35 -0.25 -0.17 -0.11 -0.07 -0.06
23:25:03.465 : -0.42 -0.32 -0.22 -0.14 -0.07 -0.02 0.03
23:25:03.468 : -0.38 -0.28 -0.22 -0.13 -0.05 0.02 0.10
23:25:05.226 : X:14.00 Y:46.00 Z:49.20 E:0.00 Count X: 44020 Y:46617 Z:52087
23:25:06.880 : N74 G0 X0 Y0 Z0 F1000*54
23:25:06.880 : N75 G0 X0 Y75 Z0 F1000*5
23:25:06.880 : N76 G0 X64.95 Y37.5 Z0 F1000*65
23:25:06.880 : N77 G0 X64.95 Y-37.5 Z0 F1000*39
23:25:11.304 : N78 G0 X0 Y-75 Z0 F1000*37
23:25:14.789 : N79 G0 X-64.95 Y-37.5 Z0 F1000*4
23:25:21.219 : N80 G0 X-64.95 Y37.5 Z0 F1000*47
23:25:21.219 : N81 G0 X0 Y75 Z0 F1000*14
23:25:27.569 : N82 G0 X64.95 Y-37.5 Z0 F1000*45
23:25:30.755 : N83 G0 X-64.95 Y-37.5 Z0 F1000*1
23:25:30.755 : N84 G0 X0 Y75 Z0 F1000*11
23:25:33.925 : N85 G0 X0 Y-75 Z0 F1000*39
23:25:39.577 : N86 G0 X-64.95 Y37.5 Z0 F1000*41
23:25:45.278 : N87 G0 X64.95 Y37.5 Z0 F1000*79
23:25:50.968 : N88 G0 X0 Y-75 Z0 F1000*42
23:26:04.347 : N89 G0 X-64.95 Y-37.5 Z0 F1000*11
23:26:04.347 : N90 G0 X64.95 Y37.5 Z0 F1000*3
23:26:16.906 : N91 G0 X64.95 Y-37.5 Z0 F1000*47
23:26:20.169 : N92 G0 X-64.95 Y37.5 Z0 F1000*44
23:26:20.169 : N93 G0 X0 Y0 Z0 F1000*63
```

Video clips:

| with this PR | without this PR |
| --- | --- |
| [](https://www.youtube.com/watch?v=VIqr3_O4g1Y) | [](https://www.youtube.com/watch?v=sqoW58YCy-s) |

> how much confidence is there in these changes?

It's difficult to express quantitatively, but when I try to express,
about "[Separate Z_PROBE_ALLEN_KEY from MECHANICAL_PROBE](https://github.com/MarlinFirmware/Marlin/pull/3725/commits/e2b87f6c85ae30d1d980902e013895c9a6a55f65)" in this PR, it's "believe".
It's very simple. I expressed it in [recent comment](https://github.com/MarlinFirmware/Marlin/pull/3725#issuecomment-218325088).

About "[Add stowing process for MECHANICAL_PROBE](https://github.com/MarlinFirmware/Marlin/pull/3725/commits/95f30529a68621f5f1735afaacea090f8cb50996)" in This PR,
it's "It doesn't appear to be any side effects".
Added codes are only 3 lines, and it's only compiled with `MECHANICAL_PROBE`.

``` cpp
    #if ENABLED(MECHANICAL_PROBE)
      stow_z_probe();
    #endif
```

To see the [actual code](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Marlin_main.cpp#L1788) and [flowchart](https://cloud.githubusercontent.com/assets/15308844/15219341/56792b02-189e-11e6-8c47-9d7ebd129006.png) of `stow_z_probe()`,
`MECHANICAL_PROBE` only call the `enable_z_probe(false)` within `stow_z_probe()`,
and `enable_z_probe()` only turned on and off a flag (`bool z_probe_enabled`)(, I think).
And why mechanical probe was operating normally while lacking the process of `stow_z_probe()` until now,
because mechanical probe doesn't perform any physical deploying and stowing,
therefore we had no real harm even while it remained deploying logically after `G29`.

But attention must be paid to,
these "confidence" and "opinion" are "confidence" and "opinion" by the beginner,
those aren't equivalence with "confidence" and "opinion" by the expert.

> I'm hesitant to merge this PR unless I know it won't have side-effects.

If development team of Marlin can't tell the judge about the validity and safety of this PR,
I hope that this PR is neglected until 1.1.0 final release, or this PR is rejected.
I know that development team of Marlin doesn't want any change other than bug fixes and cleanup towards 1.1.0 final release,
and I totally agree with that.
To begin with why I've submitted this PR, it's for make calm about controversy of "`Z_PROBE_ALLEN_KEY` and `MECHANICAL_PROBE`".
Therefore If development team of Marlin tolerate about conglutinated `Z_PROBE_ALLEN_KEY` and `MECHANICAL_PROBE` for the time being,
a necessity of this PR is almost not.
Rather, I can rest assured better that it's not merged than merged.
Because if this PR isn't merged,
I can be to zero to ensure the possibility of charging a bomb to 1.1.0 final without knowing I've with it.

**Comment by ghost** [comment]
Oh, practice note is being linked...

**Comment by jbrazio** [comment]
@esenapaj from a user perspective what will be the difference on the config file ?

**Comment by ghost** [comment]
@jbrazio
I had just want to say "From a user perspective, it's not changed anything.",
But I've realized a existence of bug in current official(plain) Marlin just now by your question.

On current official Marlin,
If you enable both `MECHANICAL_PROBE` and `Z_PROBE_ALLEN_KEY` and try to compile, SanityCheck doesn't cause error.
This is very easy test.

On the one hand, with this PR, SanityCheck cause error precisely.
Because this PR separate `Z_PROBE_ALLEN_KEY` from `MECHANICAL_PROBE` definitely.
Even if this PR is rejected, above bug in current official Marlin should be fixed at least.

And sorry, I'm going to sleep from now...

**Comment by jbrazio** [comment]
You have my merge vote.

**Comment by thinkyhead** [comment]
> total count of test is over eight times until today

Excellent. Also thinking of a variety of setups. But hey, it's looking pretty good so far! It will certainly get more testing if it's merged, eh…?

**Pull request merged**
