### PR TITLE
CHAMBER integration to GLCD

### PR DESCRIPTION
**Pull request by Ludy87**
<del>Don't MERGE</del>

Tests

---

<details><summary>disable `STATUS_COMBINE_HEATERS` and with(out) `CUSTOM_STATUS_SCREEN_IMAGE`</summary>

disable `STATUS_COMBINE_HEATERS` and with(out) `CUSTOM_STATUS_SCREEN_IMAGE`

* [x] 1 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 1 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 1 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 1 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [ ] 6 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN -> untested
* [ ] 6 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN -> untested
* [ ] 6 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN -> untested
* [ ] 6 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN -> untested
* [ ] 6 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN -> untested
* [ ] 6 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN -> untested
* [ ] 6 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN -> untested
* [ ] 6 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN -> untested

</details>

-----

<details>
  <summary>enabled `STATUS_COMBINE_HEATERS` and with(out) `CUSTOM_STATUS_SCREEN_IMAGE`</summary>

enabled `STATUS_COMBINE_HEATERS` and with(out) `CUSTOM_STATUS_SCREEN_IMAGE`

* [x] 1 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 1 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 1 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 1 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 1 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 2 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 2 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 3 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 3 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 4 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 4 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN
* [x] 5 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN
* [x] 5 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN
* [x] 6 EXTRUDERS, 0 BED, 0 CHAMBER, 1 FAN -> untested
* [x] 6 EXTRUDERS, 1 BED, 1 CHAMBER, 1 FAN -> untested
* [x] 6 EXTRUDERS, 1 BED, 0 CHAMBER, 1 FAN -> untested
* [x] 6 EXTRUDERS, 0 BED, 1 CHAMBER, 1 FAN -> untested
* [x] 6 EXTRUDERS, 0 BED, 0 CHAMBER, 0 FAN -> untested
* [x] 6 EXTRUDERS, 1 BED, 1 CHAMBER, 0 FAN -> untested
* [x] 6 EXTRUDERS, 1 BED, 0 CHAMBER, 0 FAN -> untested
* [x] 6 EXTRUDERS, 0 BED, 1 CHAMBER, 0 FAN -> untested

</details>

The HOTENDS are displayed first, followed by the HOTBED, CHAMBER and finally the FAN

### CODE REVIEW

**Comment by boelle** [comment]
I see you are doing a lot of work on this, a big thank you for that

i want to enable the chamber option but i wonder if i can use the bed to heat up the chamber?

image

of course this will take some time but that is fine with me, you just die early from stress :-D

**Comment by Ludy87** [comment]
I do not know if it makes sense to use the BED as a CHAMBER heater.

The sensor for the temperature of the bed is attached to the bed and thus can only measure this temperature.

CHAMBER heating should be a self-contained system, or am I wrong?

**Comment by boelle** [comment]
i will of course attach a sensor that messure the chamber of my home brew printer (look at pic posted above) 

its more the source for the heating of the chamber i'm thinking about

**Comment by Ludy87** [comment]
I have not thought about that yet, but the one who implemented it.

**Comment by boelle** [comment]
i use the ramps/re-arm combo, i guess i could start with adding the temp sensor and check if my bed is even able to raise the chamber temp enough to make sense of it

**Comment by AnHardt** [comment]
Bed an extruders do heat the chamber.
If the, from them, produced heat is enough to reach the wanted chamber temperature, or too much, decides upon if you need a chamber heater or cooler or both.
Depends mostly upon the isolation of the chamber and the targeted temperatures and offcause upon the print temperatures of bed and nozzle.

**Comment by Ludy87** [comment]
first and second steps - done

1. add/change CHAMBER implementation
2.1. add EXTRUDER 5
2.2. STATUS_COMBINE_HEATERS adaptation

----

next steps: clean up and custom Logo adaptation

**Comment by Ludy87** [comment]
@thinkyhead  I hope I did not miss anything.

@tpruvot and @marcio-ao can conflict with `EXTENSIBLE_UI`?

**Comment by Christophegriffo** [comment]
Salut , cela fonctionne avec un fysetc, je ni arrive pas comment faire ?
Merci

**Comment by Ludy87** [comment]
@Christophegriffo

I dont understand what you want?!

**Comment by InsanityAutomation** [comment]
> @tpruvot and @marcio-ao can conflict with `EXTENSIBLE_UI`?

I dont see anything here that would impact ExtUI as it doesnt use any of these functions.

**Comment by Ludy87** [comment]
I was idiot with the thoughts elsewhere 😅

**Comment by boelle** [comment]
i just removed the dont merge label

i will test it out as soon it's merged, but how do i tell what temp sensor is for the chamber? i can only find the config for the type of sensor

maybe it missed it in the re-arm pins file?

**Comment by Ludy87** [comment]
@boelle You can also buy the temperature sensors individually, which are also suitable for the BED or HOTEND.
So you can use the already implemented sensors.

For the pin assignment you need a free analog pin

**Comment by boelle** [comment]
that is not my "problem"

where do i tell it what pins the chamber sensor is on?

**Comment by Ludy87** [comment]
define TEMP_CHAMBER_PIN in your pin_*.h

Heater_PIN:
https://github.com/MarlinFirmware/Marlin/blob/318356b6bc7c18e2814817673541c4b3767532d4/Marlin/Configuration_adv.h#L112

**Comment by boelle** [comment]
odd, its not there in the pins_ramps_re_arm.h

which board could i copy from?

**Comment by boelle** [comment]
its not in normal ramps either

**Comment by Ludy87** [comment]
https://github.com/MarlinFirmware/Marlin/blob/318356b6bc7c18e2814817673541c4b3767532d4/Marlin/src/pins/ramps/pins_RUMBA.h#L123

https://github.com/MarlinFirmware/Marlin/blob/318356b6bc7c18e2814817673541c4b3767532d4/Marlin/src/pins/ramps/pins_TT_OSCAR.h#L177

https://github.com/MarlinFirmware/Marlin/blob/318356b6bc7c18e2814817673541c4b3767532d4/Marlin/src/pins/stm32/pins_BLACK_STM32F407VE.h#L91

**Comment by InsanityAutomation** [comment]
There just are not any machines that have a chamber heater stock with any of the standard pin files. So it's something that you can reasonably be expected to define yourself in the configuration file.

**Comment by boelle** [comment]
oki doke :-) 
 i added #define TEMP_CHAMBER_PIN   TEMP_1_PIN // A2 (T2)

chamber sensor is connected to T2 on the ramps board

going to be fun to see how much heat the bed and extruder does add to the chamber

**Comment by Christophegriffo** [comment]
Je voulais savoir si l'affichage de la chambre fonctionnait avec ce matériel
 LCD: https://wiki.fysetc.com/Mini12864_Panel/ 
J'ai le model V2.1.
Carte: bigtreetech mks 1.3
Je pense pas encore en fonction.

**Comment by Ludy87** [comment]
@Christophegriffo Test it and you will see it

**Comment by Christophegriffo** [comment]
@Ludy87 ok je vois les températures. Le dernier problème : elles sont affichées (superposé) sur l'icône du bed. 
Merci

**Comment by Ludy87** [comment]
@Christophegriffo
But you have the BRANCH used by me, right?

**Comment by Christophegriffo** [comment]
@Ludy87 ok je vois les températures. Le dernier problème : elles sont affichées (superposé) sur l'icône du bed. 
Merci

**Comment by Christophegriffo** [comment]
@Ludy87 j'ai utilisé la v2.0 de hier 08.30.2019

**Comment by Ludy87** [comment]
Dieser Branch von mir https://github.com/Ludy87/Marlin/tree/bf2_chamber

http://github.com/Ludy87/Marlin/archive/bf2_chamber.zip

**Comment by thinkyhead** [comment]
This seems to break the intent of `STATUS_COMBINE_HEATERS`. When that option is enabled, the chamber graphic should be included in the single header image which includes all the nozzles and the bed. The purpose of `STATUS_COMBINE_HEATERS` is to reduce the number of draw calls so that the graphical display requires as little time to draw as possible. It is an optimization option which results in only 2 draw calls (header+fan) instead of 4 or more (logo+nozzle+nozzle+bed+fan).

**Comment by Ludy87** [comment]
Then should CHAMBER displace the FAN from the display?

**Comment by Christophegriffo** [comment]
J'aime l'affichage actuel.  Il faudrait juste modifier les icônes pour les avoir plus jolie.
Grand merci a ludy87

**Comment by Ludy87** [comment]
The beauty is in the eye of the beholder, because you have to talk to the community.

**Comment by Christophegriffo** [comment]
Comment modifier les icônes ça fonctionne pas quand j'active STATUS_ALT_BED_BITMAP et STATUS_ALT_FAN_BITMAP les icônes sont pas top jolie

**Comment by Ludy87** [comment]
Can not I confirm, can you take a picture of it?

**Comment by Christophegriffo** [comment]
Oui,  mais je ne c'est pas comment partager des photos sur github. je suis dans le groupe Marlinfirmware sur Facebook je peu y partager des photos et vidéos.
Il faudrait un mélange de Marlin de toi et drditto qui gère mieux le fysetc et le _bootscreen et ta version qui gère la chambre (je mets la sonde sur les tmc pour avoir les ~température) 
Désolé je ne parle pas anglais 🤔

**Comment by Ludy87** [comment]
Dann sende den Link zur Gruppe, wo das Bild zusehen ist.

**Comment by Christophegriffo** [comment]
@ludy87 salut, avec ta dernière modification de fichier dogm_Statusscreen.h tout est ok.
Merci

**Comment by GMagician** [comment]
> The purpose of STATUS_COMBINE_HEATERS is to reduce the number of draw ...

I'm wondering if, in the future, a chamber cooling function needs to be done and if it will, this statement is still valid. I don't have a chamber till now but I think that, while heating may be simply done by bed itself, once temp is reached and chamber is properly "sealed" temp inside will tend to reach bed temp (100° if bed is set for ABS and it has enough power to increase temp to a bigger volume).
In that case a cooling system is needed to keep a maybe 40°, I suppose, since electronic and or stepper may not support a more then 70°. Also printer parts, if made in PLA, may no like more then 40° (70/80 PETG and so on)...

**Comment by boelle** [comment]
image

is there a reason why there are 16 steps left?

**Comment by Ludy87** [comment]
This is the missing test with 6 EXTRUDER

**Comment by boelle** [comment]
:-) going to be a good addition when its gets the thumbs up from @thinkyhead

**Comment by Christophegriffo** [comment]
Il reste quelques bug avec le lcd fysetc
On ne voit pas le boot animé les neopixel s'allume après . Et pas bien compris ou pas fonctionnelle 
  // Utilisez une seule LED Neopixel pour un éclairage statique (en arrière-plan)
Sinon pour les icônes et la chambre tous est ok

**Comment by Ludy87** [comment]
the boot screen has nothing to do with the status screen

**Comment by thinkyhead** [comment]
Ok, my fingers are crossed merging this! If anything gets unintentionally borked by this PR let's fix it up quickly… as usual. No major worries. We have a week or two before the first RC release… If the STM32F4/F7 gods are with us.

**Pull request merged**
