### PR TITLE
Compiling errors with 4 Extruders defined and Viki 2 Implementation

### PR DESCRIPTION
**Pull request by Natealus**
Here were a few changes that I had to make/add lines for the 4th hotend.
A compiling problem in the temperature.cpp and missing lines in
configuration.h and configuration_adv.h. I added these lines in all of
the example configs too.

### CODE REVIEW

**Comment by Natealus** [comment]
I must've missed something and double committed into this same pull. I can't find how to remove the Viki 2 commit into it's own pull request but oh well. 

I've insert the define and pointer entries for the Viki 2 and miniViki from Panucatt in all of the example configs and main config. With these additions and with pins done in the old single pin.h style...I was able to get the display working fine save for needing to turn Delta Segments per Second down. But that's a common graphics lcd issue being looked into right now.

I need assistance in understanding how the new divided pins files fit together because my previous attempts at trying to get it to work appropriately didn't seem successful. This originally came from trying
to find out how to swap the XYZ Min and Max Endstop pins in the Azteeg X3 Pro. It only comes with one set of connectors and they're Min Endstops. My previous experience didn't turn out well trying to tell the firmware to home to the Min Endstops so the best solution I found was to swap the pins in the firmware. If I'm missing a conflict with a setup other than delta please let me know, but it makes sense in my setup.

**Comment by thinkyhead** [comment]
The changes are good. I noticed yesterday that we needed to add another `TEMP_SENSOR`..... I'm not sure if the change in `temperature.cpp` is complete. It should check to make sure it's not the same as 0, 1, or 2.

**Comment by Natealus** [comment]
I see, so a couple additional lines to check the other two as well? I think I tried that before and it didn't compile but I'll give it a go. The 3rd one only specifies the 2nd temp as well so I thought it was following suite.

**Comment by Natealus** [comment]
All compiles well and I also found another missing line for INVERT_E3_DIR. Added that to all the example configs too. Completed the lines in the temperature.cpp file.

**Comment by thinkyhead** [comment]
Don't forget, in `temperature.cpp` lines 139-141 each need an additional element. And all the `ARRAY_BY_EXTRUDERS(0,0,0,0)` can be changed to `{ 0 }` if we like, because the compiler will set the rest to 0, but that's optional. I was also going to move the `ARRAY_BY_EXTRUDERS` declaration to a new file, `utilities.h` and `#include` it in `Marlin.cpp` and `temperature.cpp` – the only files that need these macros. But maybe it would be better to just drop it into `Marlin.h`.

**Comment by thinkyhead** [comment]
I'm going to go for it with moving all the logic in `process_commands` into handler functions, so be prepared in case of strange behavior. It will need to be closely watched. Your PR actually has no conflicts with mine, so you should be able to do a clean merge after this change. I want to get it in now before too may changes come along to `Marlin.cpp` that I need to shuffle into the correct spots.

**Comment by Natealus** [comment]
Slightly above my head there Thinky but I'll try to follow along and see what you mean. Get back to you after I look at the code.

After looking at it I think I get what you want to do. Doesn't seem like it would mess things up just executing in a different file.

**Comment by Natealus** [comment]
That whole section you referenced is if PIDtemp is defined...I don't see where you see the ARRAY_BY_EXTRUDERS(0,0,0,0)?

#ifdef PIDTEMP
#ifdef PID_PARAMS_PER_EXTRUDER
  float Kp[EXTRUDERS] = ARRAY_BY_EXTRUDERS(DEFAULT_Kp, DEFAULT_Kp, DEFAULT_Kp);
  float Ki[EXTRUDERS] = ARRAY_BY_EXTRUDERS(DEFAULT_Ki_PID_dT, DEFAULT_Ki_PID_dT, DEFAULT_Ki*PID_dT);
  float Kd[EXTRUDERS] = ARRAY_BY_EXTRUDERS(DEFAULT_Kd / PID_dT, DEFAULT_Kd / PID_dT, DEFAULT_Kd / PID_dT);
  #ifdef PID_ADD_EXTRUSION_RATE
    float Kc[EXTRUDERS] = ARRAY_BY_EXTRUDERS(DEFAULT_Kc, DEFAULT_Kc, DEFAULT_Kc);
  #endif // PID_ADD_EXTRUSION_RATE
#else //PID_PARAMS_PER_EXTRUDER
  float Kp = DEFAULT_Kp;
  float Ki = DEFAULT_Ki \* PID_dT;
  float Kd = DEFAULT_Kd / PID_dT;
  #ifdef PID_ADD_EXTRUSION_RATE
    float Kc = DEFAULT_Kc;
  #endif // PID_ADD_EXTRUSION_RATE
#endif // PID_PARAMS_PER_EXTRUDER
#endif //PIDTEMP

Or are you talking about a post compile log that shows that? Cause I didnt set the config up all the way with PID settings and such cause I was trying to leave everything at the defaults for the commit.

**Comment by thinkyhead** [comment]
https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/temperature.cpp#L158 and https://github.com/MarlinFirmware/Marlin/blob/Development/Marlin/temperature.cpp#L178-L179

**Comment by Natealus** [comment]
Ah I see what you mean I was looking at the wrong section. Yeah tis true that max temps and as such min temps would all be uniform given you're using all of the same hotends. I can't think of a reason people would throw kinks in the link by using odd hotends. Are you doing that or did you want me to do that in this pull?

**Comment by thinkyhead** [comment]
You can totally do that in your pull. That is, you should make the changes in `temperature.cpp` but don't bother making `ARRAY_BY_EXTRUDERS` available elsewhere. I will do that later in the week.

**Comment by Natealus** [comment]
Alrighty I did see what you meant by the pid settings that needed an additional element for the 4th hotend. I'm about to push the temperature.cpp fix and was that all we wanted for this pull?

Note 2 I tried changing from (0,0,0,0) to { 0 } it caused an error saying it expected ; or , before that sort of function. I really need to take a coding course. It intrigues me. :)

**Comment by thinkyhead** [comment]
Was that `{ 0 };` with the semicolon at the end? (Assignment statements that end with `}` need a semicolon.) The PR looks good now, one last look-over before I merge....

**Comment by Natealus** [comment]
Think I had a space with it like { 0 } ; that could've been the issue. I also want to make another with pins for different boards. But I need help understanding how that hierarchy works. I tried changing XYZ Min and Max pins just for the Azteeg X3 Pro but it didnt seem to take unless I did it in Ramps 1.3 pins.

**Comment by thinkyhead** [comment]
@Natealus The defines in `pins_AZTEEG_X3_PRO.h` should override those in `pins_RAMPS_13.h` so I'm not sure why that's not working. If you do a test, removing them from `pins_RAMPS_13.h` but adding them to `pins_AZTEEG_X3_PRO.h` does _that_ work?

**Comment by Natealus** [comment]
I didn't directly try that but it seemed since those pins were already defined and the X3 Pro calls the Ramps 1.3 pins...when I define them also in the pins_AZTEEG_X3_PRO.h they dont seem to take. I noticed that all the pins defined in the X3 Pro file were not duplicates of any of the previous pins defined in pins_RAMPS_13.h . How do we get around that?

**Comment by thinkyhead** [comment]
@Natealus Hmm. Well we have some instances where pins are intentionally overridden to set them back to -1 in the main `pins.h` file, and presumably those work. But I have heard it said that the compiler is not supposed to override a previous `#define` without `#undef`. But just in my testing, adding defines to see how they behave, the compiler does override without `#undef`. So... maybe try adding `#undef` before the redefines.

**Comment by Natealus** [comment]
so I could do...?
#blah blah rest of lines in pin file
#undef X_MIN_PIN
#define X_MIN_PIN (number)

**Comment by thinkyhead** [comment]
Ya, try that and see if it makes any diff.

**Comment by Natealus** [comment]
Sorry been gone a few days I'm going to start working on it with a fresh fork of the firmware.

**Comment by thinkyhead** [comment]
@Natealus I recently updated RAMPS-related pins files, continuing to assume that #defines can be overridden later (the compiler complains but allows it). I went forward with this change with some confidence, because this assumption is made in several places throughout the Marlin codebase.

**Comment by Natealus** [comment]
Sorry I still haven't done the pin work on this yet. I've been a little busy calibrating but I'm going to work on this soon.

**Comment by Natealus** [comment]
@thinkyhead Bingo I added a paragraph of undefs for all the endstop pins and swapped them in the azteeg x3 pro pins file. Worked like a charm. Previously I had to swap the Ramps 13 pins in order to swap min and max endstop pins. On the X3 Pro it only comes with min stop pins installed for some reason. I've ordered some 3 pin headers from china so next week hopefully, I'll be able to install the other 3 headers and get my Z probe system going :D

**Comment by thinkyhead** [comment]
@Natealus So what does your `pins_AZTEEG_X3_PRO.h` file look like now? I will have to play around with compiling for that board.

**Comment by Natealus** [comment]
So now it just has the addition at the top and I think heater 2 was -1 before...which obviously doesnt work for a 4 heat setup. For someone who buys an Azteeg X3 Pro I wouldn't think they would put the hotend cooler on HE 2. Physical Hotend connectors 1-4 are my heaters and 5 is the controller fan and 6 is the hotend water pump and 7 is the part fan (which I'm not using cause I'm printing ABS and reworking my own design to take town its footprint.) I'm not sure I've seen one before but you could technically control 5 hotends and extruders with it. In that case it'd make more sense for them to be HE 6, 7, and 8. Or maybe I'll do that anyways lol

```
/**
 * AZTEEG_X3_PRO (Arduino Mega) pin assignments
 */

#include "pins_RAMPS_13.h"

#define FAN_PIN            -1 // (Sprinter config)
#define BEEPER             33

#undef X_MIN_PIN
#undef X_MAX_PIN
#undef Y_MIN_PIN
#undef Y_MAX_PIN
#undef Z_MIN_PIN
#undef Z_MAX_PIN

#define X_MIN_PIN           2
#define X_MAX_PIN           3
#define Y_MIN_PIN          15
#define Y_MAX_PIN          14
#define Z_MIN_PIN          19
#define Z_MAX_PIN          18

#define E2_STEP_PIN        23
#define E2_DIR_PIN         25
#define E2_ENABLE_PIN      40

#define E3_STEP_PIN        27
#define E3_DIR_PIN         29
#define E3_ENABLE_PIN      41

#define E4_STEP_PIN        43
#define E4_DIR_PIN         37
#define E4_ENABLE_PIN      42

#define HEATER_1_PIN        9
#define HEATER_2_PIN       16
#define HEATER_3_PIN       17
#define HEATER_4_PIN        4
#define HEATER_5_PIN        5
#define HEATER_6_PIN        6
#define HEATER_7_PIN       11

#define TEMP_2_PIN         12   // ANALOG NUMBERING
#define TEMP_3_PIN         11   // ANALOG NUMBERING
#define TEMP_4_PIN         10   // ANALOG NUMBERING
#define TC1                 4   // ANALOG NUMBERING Thermo couple on Azteeg X3Pro
#define TC2                 5   // ANALOG NUMBERING Thermo couple on Azteeg X3Pro
```

**Comment by thinkyhead** [comment]
It's interesting that the compiler is requiring `#undef` in these cases. The Arduino **gcc** compiler issues warnings but seems to allow overrides of any kind. However, the standard behavior of **gcc** is to only allow overrides that are _effectively the same_, and throw an error if a macro is redefined with a different effective value. Check to see if the following code compiles in Arduino:

```
#define THING_TO_OVERRIDE_1 1111
#define THING_TO_OVERRIDE_1 1
#if THING_TO_OVERRIDE_1 == 1111
  #error Could not override THING_TO_OVERRIDE_1
#endif
#define THING_TO_OVERRIDE_2 2222
#undef THING_TO_OVERRIDE_2
#define THING_TO_OVERRIDE_2 2
#if THING_TO_OVERRIDE_2 == 2222
  #error Could not override THING_TO_OVERRIDE_2
#endif
```

**Comment by Natealus** [comment]
Well it compiles fine in IDE, but when I added the pins a while ago in the new pins file that were already defined in the included Ramps_13 board, they just...didn't take effect. When trying it recently, I #undef the endstop min max pins and it did happen to work. I haven't tried it the other way recently maybe you guys made a change that fixed that?

**Comment by thinkyhead** [comment]
@Natealus Hoping to find some pattern so it will always work. We'll need a lot of #undef if it turns out this is a common problem.

**Comment by Natealus** [comment]
@thinkyhead Well it seems similar to what's happening now with all the elifs and stuff like that. If we didn't have those else commands in there we'd probably be undefining alot more. But as you get further in the hierarchy and into the specific board like the azteeg x3 pro, it seems like it handles redefining a little differently.

I haven't put the LCD pins in yet, I haven't been using it cause I was getting pretty smooth printing. I just did a large print last night though on a recent dev download that...overall looks good but there's little bumps all over it where the printer is stuttering again at the same 165 segments per sec that I had it on before.

Were there recent changes to the system that handles the movements/stepper motors/delta kinematics during printing?

**Comment by thinkyhead** [comment]
@Natealus I'm on the verge of accepting that we should follow the broader C++ standard, which means placing an `#undef` in front of every `#define` in the `pins_MYBOARD.h` files, and anywhere else that something might get redefined.

I'm not aware of any recent changes that would have a negative effect on print speed. The `stepper.cpp` file was cleaned up a bit, but nothing should have been altered in the way it functions. We've also had some updates to the `temperature.cpp` code, but again nothing that should change behavior or affect speed.

I wish we had better diagnostics to solve such issues. If you are able to narrow down some contributing factor, please report.

**Comment by Natealus** [comment]
@thinkyhead Will do but I'm coming to realize the sad fact that ATMega 2560 is only 16mhz...would this code work on an ARM based board or would it have to be rewritten? I'm sure this board would work fine if I was running a square carriage style printer but might need more juice to run a delta smoothly AND accurately AND quickly lol.

**Comment by thinkyhead** [comment]
@Natealus There are some in-between boards that will run the existing code and yet are faster. I wouldn't mind having one myself, even though I don't have a (completed) delta. Faster boards just produce better movement overall.

**Comment by Natealus** [comment]
Yup definitely what I'm looking for. Deltas are nifty and large on the build but I can see how it could cause more calculations to work vs other types of printers. Are there any other types like that or are deltas just a special case? I'm looking at a Duet with expansion board. Based off Arduino Due. I'm guessing that's one of those in-betweeners? So I guess that begs the question...is it the bootloader that determines the code compatibility?

**Comment by thinkyhead** [comment]
@Natealus The extra calculations, whether for Delta, or even for bed leveling compensation during printing, can be taxing on our meager 2560s.

Code compatibility could be accomplished in a few ways, even using emulation. But of course they also have the option to compile the same code for the new architecture transparently, as long as the hardware interfaces are the same on the back-end, and the pins are 1:1 compatible.

**Comment by Natealus** [comment]
@thinkyhead Yeah so I was wondering if it really was that simple...and all we would have to do is add a new pin file for the ARM Duet. I like the code and the work we're doing here. I'm not so sure about alot of these other ports I'm looking at they seem to have all sorts of issues we passed by months ago. Course other features like networking and such. But Marlin seems to work quite well. Hard to break from it hehe. :)

**Comment by thinkyhead** [comment]
#626 has a lot of discussion about the ARM / Due port. Not as easy as one would hope. But there is this board called the Arduino Zero that's _maybe_ going to come out someday…

**Pull request merged**
