### PR TITLE
Set laser/spindle PWM to lowest speed on M5

### PR DESCRIPTION
**Pull request by ghost**
Needed for laser/spindle controller which lacks dedicated Enable pin and is only controlled by PWM output

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for the patch, but we can't accept PRs targeted to the release branch. Please re-do this PR, targeting the `bugfix-1.1.x` and `bugfix-2.0.x` branches.

**Comment by thinkyhead** [comment]
As a small PR I took care of it for ya!

**Comment by ghost** [comment]
Thank you!
A couple of questions, if you don't mind
If I want to implement a new feature, not a bugfix, what branch should I push to?
Say, right now I want to make a spindle/laser power control from LCD menu. And I cannot decide what submenu should it be put to, Control or Prepare? Are there any guidelines on that?

**Comment by thinkyhead** [comment]
> If I want to implement a new feature, not a bugfix, what branch should I push to?

Build on `bugfix-2.0.x` from now on.

> Control or Prepare?

Prepare is for pre-printing stuff. The Prepare menu goes away during printing. The Control menu is for tuning settings. The Tune menu is for making changes during printing, and only appears when printing is active.

**Pull request closed without merging**
