### PR TITLE
UMBoard 2.1.4 hidden PJ6 hack

### PR DESCRIPTION
**Pull request by soimy**
### Description

According to the schematic from Ultimaker mainboard v2.1.4, Ultimaker2's extruder cooling fan is actually controlled by Mega2560's PJ6 pin which is hidden from IO. There is currently no easy way to access it from `fastio_avr` `_WRITE()` as far as I know.

So I added an extra tag called `ULTIMAIN_HIDDEN_PJ6` in `pin_ULTIMAIN_V2.h`, and do some hack in temperature loop. 

### Benefits

After this Ultimaker2 can actually have extruder auto fan feature from its J34 plug.

### Related Issues

None.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Can you test to see if `E0_AUTO_FAN_PIN 77` works? Marlin has some "synthetic" pins and 77 is the one that corresponds to J6.

**Comment by AnHardt** [comment]
The pins do exist on the processor - just not on the Arduino Mega connectors.

**Comment by soimy** [comment]
OK, I'll check pin 77 when I can get my hands on the printer tomorrow.

**Comment by soimy** [comment]
Pin 77 actually working!!
So I think I should revert these hack and redefine `E0_AUTO_FAN_PIN 77` in `pin_ULTIMAIN_V2.h`

**Comment by thinkyhead** [comment]
> So I think I should revert these hack and redefine E0_AUTO_FAN_PIN 77 in pin_ULTIMAIN_V2.h

Since `ORIG_E0_AUTO_FAN_PIN` is already defined as 77, in `Configuration_adv.h` you can just comment out the line…
```diff
- #define E0_AUTO_FAN_PIN -1
+ //#define E0_AUTO_FAN_PIN -1
```

**Pull request closed without merging**
