### PR TITLE
Bootscreen Hitachi

### PR DESCRIPTION
**Pull request by AnHardt**
picture 140
https://youtu.be/Mv327oQ7HqI
https://youtu.be/aGwt64Uy-Ms

Needed a bit of fun programming today. Inspired by https://github.com/MarlinFirmware/Marlin/issues/2541#issuecomment-126610127 i remembered that the Hitachi displays don't have a boot-screen.

There is not very much space on the small displays - so decided for scrolling and sequencing the strings.

Boot-screen for the character displays
  When SHOW_BOOTSCREEN is on uses about additional 742 bytes of progmem and 32 bytes of RAM.
  For that configurable.

Make boot-screen configurable for the graphic displays
  When SHOW_BOOTSCREEN is off saves about 473 bytes of progmem and 28 bytes of RAM.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Very nice. I really like the approximation of the logo. I see that **marlinfirmware.o** is all that will fit on 16-wide displays. Is that the only place it needs to scroll? If that's the case, maybe on tiny screens we can use [**ow.ly/QlYoI**](http://ow.ly/QlYoI) instead.

**Comment by eboston** [comment]
What about registering the domain name marlinfw.org?  It's available.  :)

**Comment by thinkyhead** [comment]
@eboston Totally. That's much nicer than ow.ly.

**Comment by AnHardt** [comment]
@thinkyhead 
As configured now the URL is the only string that is too long.
But STRING_SPLASH_LINE1 and STRING_SPLASH_LINE2 are relativity easy user changeable - in the config.

If someone prefers to have `SHOW_BOOTSCREEN` disabled by default, i simply have to upload a ready commit.

**Comment by thinkyhead** [comment]
@AnHardt Should `SHOW_BOOTSCREEN` be extended to apply to the graphical display also?

**Comment by AnHardt** [comment]
@thinkyhead 
SHOW_BOOTSCREEN for the full graphic displays is already in this PR. See: commit 2. https://github.com/AnHardt/Marlin_O/commit/daf8af958e6e7b89b46f5e4bbb06bb9c800ad27f
Sorry - that's not obvious because of some tab hunting, and shifting the delay.

**Comment by AnHardt** [comment]
Replaced by:
https://github.com/MarlinFirmware/MarlinDev/pull/13

**Pull request closed without merging**
