### PR TITLE
Support FYSETC_MINI_12864_PANEL

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR makes the needed changes to support the FYSETC Mini 12864 Panel controller. It is just the basic scaffolding to support this device, and may not be in working order yet. More testing and development is needed.

### CODE REVIEW

**Comment by bipsendk** [comment]
I have working pins files for BIGTREE SKR V1.3 and FYSETC F6 .. Some minor adjustments might be needed in other files (depending on naming of the display type)

**Comment by bipsendk** [comment]
A couple of comments/considerations:
For the RGB version of the Fysetc MINI 12864, some color will need to be applied after reset (or startup) - otherwise the screen will be hard to read (especially the one with "white" text on black background). Being able to set a startup-color would be desirable.

Also - if using PRINTER_EVENT_LEDS, it will not be optimal to turn off the LED after the print has finished - which makes the screen practically unreadable.

I can test the display on both SKR v1.3 and Fysetc F6 ... Let me know if any input/feedback is required.
I have attached my test pins files for the two boards.
[pins_FYSETC_F6_13.h.txt](https://github.com/MarlinFirmware/Marlin/files/3015130/pins_FYSETC_F6_13.h.txt)
[pins_BIGTREE_SKR_V1.3.h.txt](https://github.com/MarlinFirmware/Marlin/files/3015132/pins_BIGTREE_SKR_V1.3.h.txt)

**Comment by thinkyhead** [comment]
Thanks for the info and pins. I'll check them over soon and pass it on to my helpful test crew!

**Comment by bipsendk** [comment]
I wonder if a sanity-check should be made on LED_COLOR_PRESETS and LED_USER_PRESET_STARTUP   - because if the display is of type B, and there is no backlight from any RGB led - it is extremely hard to read.

**Comment by thinkyhead** [comment]
For this display we'll make sure the backlight LED is turned on and if its color or brightness can be altered, that this will be available, if desired.

**Comment by bipsendk** [comment]
By the way - added some minor changes to Conditionals_LCD.h as well... Attached here...
[Conditionals_LCD.h.txt](https://github.com/MarlinFirmware/Marlin/files/3026904/Conditionals_LCD.h.txt)

**Comment by bipsendk** [comment]
Not sure, that I attached the right pins file for the F6 board... Here is the right one,...


[pins_FYSETC_F6_13.h.txt](https://github.com/MarlinFirmware/Marlin/files/3028036/pins_FYSETC_F6_13.h.txt)

**Comment by bipsendk** [comment]
Found out a couple of colors are way off with this display... Minor tweaks needed to Marlin/src/feature/leds/leds.h ...
[leds.h.txt](https://github.com/MarlinFirmware/Marlin/files/3032738/leds.h.txt)

**Comment by thinkyhead** [comment]
Thank you for the contributions. I'll incorporate them very soon and get this back into happy shape. Chris Russell of Practical Printing also pointed out [this article](https://wiki.fysetc.com/Mini12864_Panel/?fbclid=IwAR1FyjuNdVOOy9_xzky3qqo_WeM5h-4gpRnnWhQr_O1Ef3h0AFnFXmCehK8) which outlines the needed steps to get the display working with 1.1.8.

**Comment by thinkyhead** [comment]
This should be in working order now. Everything is on par with your notes and the linked article. Please test to see if this is working well, and take special note of whether contrast is functioning correctly. Another tester was having trouble with that.

**Comment by BerndKuhrmann** [comment]
The change broke the support of MKS_MINI_12864 at least on bugfix-2.0.x. The screen remains white.

**Comment by Bob-the-Kuhn** [comment]
@BerndKuhrmann - what controller are you using?

This display uses a non-standard pinout.  Most non-RAMPs based controllers will need changes to their pins_YOUR_BOARD.h file to support it.

On my RAMPS_FD_V1 I made the following change:
FROM
```
  #if ENABLED(MINIPANEL)
    #define DOGLCD_CS      25
    #define DOGLCD_A0      27
  #endif
```

TO
```
  #if ENABLED(FYSETC_MINI_12864)
    #define DOGLCD_CS      LCD_PINS_ENABLE
    #define DOGLCD_A0      LCD_PINS_RS
  #elif ENABLED(MINIPANEL)
    #define DOGLCD_CS      25
    #define DOGLCD_A0      27
  #endif
```

**Comment by thinkyhead** [comment]
I can't see anything obvious in this PR affecting `MKS_MINI_12864`. All the pin assignments appear to be exactly the same, at least.

**Pull request merged**
