### PR TITLE
If an sd card is removed using the UI and NO_SD_DETECT is enabled, just refresh the UI

### PR DESCRIPTION
**Pull request by SaschaKP**
### Description

If an sd card is removed using the menu the ui won't be updated, just update the menu if the flag NO_SD_DETECT is enabled.

### Requirements

NO_SD_DETECT must be enabled for this change to take effect

### Benefits

after removing a card with the ui, the ui itself will be updated with the new state, instead of having to move the cursor or change the page to view the ui update with the card removed information

### CODE REVIEW

**Comment by SaschaKP** [comment]
Hello, sincerely I don't know why the test will fail, but anyway this is only for a narrow number of people that own some printers with a possibly broken sd_card detection, using the ui won't update the status of the card when it is removed, but will update it's status if you select "attach sd card" from the menu, so I just inserted an #if ENABLED(NO_SD_DETECT) with the ui.refresh() directly emulating the behaviour of card.mount().

**Comment by thisiskeithb** [comment]
> Hello, sincerely I don't know why the test will fail

https://github.com/MarlinFirmware/Marlin/pull/26339 needs to be merged for CI tests to work.

**Comment by SaschaKP** [comment]
Done, thanks for the advice @thisiskeithb

**Comment by thisiskeithb** [comment]
You shouldn’t merge pending PRs into other pending PRs. I meant that we’re waiting for my PR to be merged into the main code base first.

**Comment by SaschaKP** [comment]
D'oh

**Comment by thisiskeithb** [comment]
I can't seem to edit this PR, but you'll need to drop/revert those changes & just push the commit to fix the SD UI refresh bug.

**Comment by thinkyhead** [comment]
Since it can't be edited for one reason or another and is very simple, I've moved it over to #26366.

**Pull request closed without merging**
