### PR TITLE
fix build with and without TOUCH_BUTTONS...

### PR DESCRIPTION
**Pull request by tpruvot**
follows #14900

### CODE REVIEW

**Comment by robbycandra** [comment]
I am thinking about devide the touch area into 4x4 region. And we can use touch area / ICON area like MKS TFT / BigTree TFT.

**Comment by tpruvot** [comment]
> I am thinking about devide the touch area into 4x4 region. And we can use touch area / ICON area like MKS TFT / BigTree TFT.

do you have some picture ?

**Comment by McVillano** [comment]
Resting here to see if the PR suceeds!

**Comment by robbycandra** [comment]
> do you have some picture ?

something like this;
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware 

Only need to combine or connect it with marlin.

**Comment by McVillano** [comment]
Solved here!

**Pull request merged**
