### PR TITLE
Option to use raw digipot values

### PR DESCRIPTION
**Pull request by grauerfuchs**
For machines with the MCP4018 digipot controller (i.e. Mightyboard)

The existing driver hard-codes the current calculations for the A4988 stepper driver. This is fine on stock machines, but users must fudge the numbers if they use a different type of stepper driver on one or more axes. 

Usage:
Defining the new `MCP4018_USE_RAW_VALUES` config option will enable use of the `DIGIPOT_MOTOR_CURRENT` config option values rather than `DIGIPOT_I2C_MOTOR_CURRENTS`, and M907 will accept raw wiper values (0-127) on all channels. 

Testing:
This code is now running on both of my FFCP machines with TMC2100s on X and Y and the original steppers on Z, A, and B. The TMC2100 driver modules in use are designed specifically for drop-in compatibility on the Mightyboard, including use of the digipot for setting Vref.

### CODE REVIEW

**Comment by tharts** [comment]
This change seems to break building for MKS Sbase (LPC1768) if mcp4451 is uncommented. Sanity check complains about missing pins definitions which wasn't the case before.
Digipots worked with the previous version when the option digipot_i2c was uncommented.

**Comment by thinkyhead** [comment]
Patched! Apparently MKS SBASE is special and provides its own interface. Others will still need these pins.

**Comment by tixenre** [comment]
> This change seems to break building for MKS Sbase (LPC1768) if mcp4451 is uncommented. Sanity check complains about missing pins definitions which wasn't the case before.
Digipots worked with the previous version when the option digipot_i2c was uncommented.

I'm having the same issue building for Smoothieboard (LPC1769) if mcp4451 on Marlin 2.06
#error "DIGIPOT_MCP4018/4451 requires DIGIPOTS_I2C_SDA_* pins to be defined."

**Comment by thinkyhead** [comment]
Comment out the `#error` line and see if it can build.

**Pull request merged**
