### PR TITLE
Remove USE_RAW_KINEMATIC

### PR DESCRIPTION
**Pull request by robbycandra**
I found that there are no #define USE_RAW_KINEMATICS

So better delete any conditional code using #if ENABLED(USE_RAW_KINEMATICS)

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
As far as i can remember `USE_RAW_KINEMATICS` was meaned as a debug helper - not for the general public. So - if you don't know what it does - don't touch it - but keep it in.

**Comment by robbycandra** [comment]
If it must be kept, then better put some comment to explain the purpose of USE_RAW_KINEMATICS.
Cause i also can't find any commented //#define USE_RAW_KINEMATICS.

**Comment by thinkyhead** [comment]
Hi @robbycandra — and thanks for bringing your contributions. This one points out a work-in-progress to optimize delta/scara kinematics that has stalled a little.

`USE_RAW_KINEMATICS` is a "hidden option" for development-purposes (there are a few others). The effect of this one is to do maths for delta in "raw coordinates" in the kinematic planner routines — the ones that turn single linear moves into lots of smaller moves for the benefit of non-linear kinematics, as on Delta and SCARA. This saves 6 float subtract operations per delta calculation, which saves many hundreds of cycles per linear movement.

My hope in starting on this behavior was (is?) to replace the maths in these functions eventually with the "raw" maths and speed up processing, particularly for delta. But actually, I recently added an option called `NO_WORKSPACE_OFFSETS` that accomplishes the same thing, at the expense of (a) not being able to use `home_offset` and (b) having `G92` behave like it does in Marlin 1.0.2 (where `G92` interacts badly with software endstops).

I think that `NO_WORKSPACE_OFFSETS` is probably sufficient for most delta users, so perhaps, just maybe the `USE_RAW_KINEMATICS` option could go away. It's definitely not SCARA-compatible at this time.

Perhaps the best approach in completing this concept for delta/scara would be to change the kinematics functions so they take "raw" positions (workspace offsets removed). Then all the code that uses them can be adjusted to conform — removing the workspace offsets beforehand, however is appropriate to each one.

**Comment by thinkyhead** [comment]
@robbycandra PS — Please submit PRs to the `RCBugFix` branch. This one will be closed for safety.

**Pull request closed without merging**
