### PR TITLE
Fix auto power for chamber fan

### PR DESCRIPTION
**Pull request by timmmoore**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Looks like auto chamber fan uses auto power chamber fan defines to include chamberfan_speed variable. So configuring auto chamber fan generates a compiler error.
This fixes the use of defines for chamberfan_speed for auto chamber fan

### Benefits

Configing auto chamber fan without auto power chamber fan has a compiler error.
Auto power chamber fan doesn't use chamberfan_speed so #if uses wrong define.

The auto chamber power check is separate at line 102 in power.cpp and doesn't use chamberfan_speed variable

### Related Issues

Should fix issues 14849

### CODE REVIEW

**Comment by timmmoore** [comment]
I guess I am missing something, checkExtruderAutoFans is only enabled with a pin controlled fan: extruder or chamber so why check AUTO_POWER_CHAMBER_FAN which is for PSU controlled fan?

**Comment by thinkyhead** [comment]
The only purpose of tracking the fan speed values is to know whether or not the external PSU needs to be turned on under the auto-power feature. This applies to a PSU that is shared by all 12V (and/or 24V) components.

**Comment by thinkyhead** [comment]
> AUTO_POWER_CHAMBER_FAN which is for PSU controlled fan?

If you look at the current implementation, you will see that all the components share a single PSU. There is no option to have the chamber fan be turned on and off by turning a PSU on and off, except by the common method of assigning a digital pin as the chamber fan pin. If a digital pin is assigned, then the fan will be turned on at full speed only, but it is still keyed to the thermistor.

`AUTO_POWER_CHAMBER_FAN` is a sub-option of `AUTO_POWER_CONTROL` which pertains to a single PSU shared by all components.

**Comment by timmmoore** [comment]
ok, the way I looked at it was you could do 2 things with the chamber fan
1. Connect to PSU so it turned on/off with the PSU if you had a controlled PSU - the info in configuration PSU controlled section configured this
2. Connect a pin to chamber fan - the info in configuration_adv configured this.
The extruder and controller fans also have the same 2 configurations and work that way - or I have found they do if you config each separately. Since there is only 1 control for PSU, the PSU turns off only if all fans should be off or on if 1 fan should be on.
Where the fan per pin allows each fan to be controlled separately.

**Pull request merged**
