### PR TITLE
Unify M421

### PR DESCRIPTION
**Pull request by thinkyhead**
The spirit of the law is more important than the letter of the law.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
This looks like this collapses all the different flavors of M421 to one code block?   

Would it make sense to alter the original Mesh Bed Leveling to be consistent with everything else and change
```cpp
static float  z_values[GRID_MAX_POINTS_Y][GRID_MAX_POINTS_X];
```
to
```cpp
static float  z_values[GRID_MAX_POINTS_X][GRID_MAX_POINTS_Y]
```

**Comment by thinkyhead** [comment]
> Would it make sense to alter the original Mesh Bed Leveling to be consistent with everything else and change…

Either that, or change the others. There's a minor advantage to having `y` as the first dimension in the array. Mainly, if there's a loop like this to invalidate points…
```cpp
for (y = 0; y < GRID_MAX_POINTS_X; ++y)
  for (x = 0; x < GRID_MAX_POINTS_X; ++x)
    z_values[y][x] = NAN;
```
…theoretically it should run slightly faster because it writes to successive RAM addresses.

----
**EDIT: _Ah, I see we always do `x` as the outer loop. So it would be ok to change MBL._**

**Comment by Roxy-3D** [comment]
> Aha… Well, I see we always do x as the outer loop. So I'll change MBL!

Thanks...   I'm definitely in the camp that prefers the programmers have a very easy time understanding the constructs!   I kept typing things backwards and decided to change things.  I suspect that problem happens to others also.

**Comment by thinkyhead** [comment]
Check out how few changes were needed in that commit. Easy peasy.

**Comment by Roxy-3D** [comment]
Yeah...  it is pretty straight forward.      So with this all of the mesh bed leveling schemes are using the first subscript for x and the second one for y.   That is a good thing....

Next on the list...   Get the array names the same.   That will allow us to collapse code and make the things like the mesh map common between the various schemes.   Maybe things like mesh editing too!

**Comment by thinkyhead** [comment]
> Next on the list... Get the array names the same.

I'd vote to wait for 1.2 before this reform and aim to get all bed leveling into C++ classes following a common naming convention. The concept of "protocols" would generally be used here in those languages that support them.

**Pull request merged**
