### PR TITLE
Add Dagoma Disco Ultima Pins, Thermistor, and Config

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Adds support for Dagoma Ultima printer.

Stock features not implemented : 
Wifi Printing

Stock machine opened second serial stream to wifi module to allow a command stream to print over the air.

Push button to trigger filament change

Pin 32 was tied to trigger M600; Perhaps we can look at a function to trigger a macro from a pushbutton.

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
Jahitian on discord fought through most of the debug. Original source also had some odd Delta code as well and modifications to the run-out routines but most of that looks obsolete.

**Comment by thinkyhead** [comment]
**Pro Tip:** Marlin knows what to do if the pins file only defines `X_STOP_PIN`, `Y_STOP_PIN`, `Z_STOP_PIN`. (And even better now.) So when there are only three plugs, we only need to define those three. The actual meaning of the "stop" pins is decided in `pins.h` based on which directions the axes are homing.

**Comment by thinkyhead** [comment]
> Pin 32 was tied to trigger M600; Perhaps we can look at a function to trigger a macro from a pushbutton.

For something like that, I'm fine to let vendors hack it into the LCD code themselves. It does not need to be an exposed option. Anyway, I would put that on the 2.1 Milestone list.

At this time, aim to put anything nonessential on the 2.1 milestone list. As summer looms, we are going into overdrive and pushing on to fulfill the **Marlin 2.0 RC1** milestone. I'll post a new issue with a TODO list soon. That TODO list will show up on the Milestones page with percentage progress based on number of items checked off. I'm sure I will need help filling out the list!

**Comment by tpruvot** [comment]
the last commit of this series is breaking travis

**Comment by InsanityAutomation** [comment]
> 
> 
> > Pin 32 was tied to trigger M600; Perhaps we can look at a function to trigger a macro from a pushbutton.
> 
> For something like that, I'm fine to let vendors hack it into the LCD code themselves. It does not need to be an exposed option. Anyway, I would put that on the 2.1 Milestone list.
> 
> At this time, aim to put anything nonessential on the 2.1 milestone list. As summer looms, we are going into overdrive and pushing on to fulfill the **Marlin 2.0 RC1** milestone. I'll post a new issue with a TODO list soon. That TODO list will show up on the Milestones page with percentage progress based on number of items checked off. I'm sure I will need help filling out the list!

Can you make another todo list just to keep a clean list of items we agree to push towards 2.1 so they dont get lost / forgotten and users who requested them dont think theyre ignored?

**Pull request merged**
