### PR TITLE
fix : correct pins for Ender 2 display, add BTN_ENC

### PR DESCRIPTION
**Pull request by greppp**
# Description

Resolving #15624

Fixing Ender 2 stock LCD pinout for use with SKR V1.3 Boards. Previous wrong pinout caused the screen to stay blank.

**Reference :**
(Board pinout) https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/blob/master/BTT%20SKR%20V1.3/hardware/SKR-V1.3-PIN.pdf

I used tested pinout from https://github.com/MarlinFirmware/Marlin/issues/15624#issuecomment-545207820, and used tip from https://github.com/MarlinFirmware/Marlin/pull/15997 to add the missing pin BTN_ENC.

### Benefits

This PR fixes two minor issues with the Ender 2 screen when hooked up to an SKR V1.3.

### Related Issues

#15624

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Does a real MKS Mini 12864 work with this change? The Ender-2 has `MKS_MINI_12864` defined, but it's not an actual/standalone [MKS Mini 12864 LCD](https://reprap.org/wiki/MKS_MINI_12864).

Edit: I have the hardware to test with, but can't test this PR until tomorrow.

**Comment by thinkyhead** [comment]
If it needs it we can add a new LCD designation, but maybe by chance some of these single-cable LCDs that come with Creality3D machines are equivalent to a "`CR10_STOCKDISPLAY`"…?

**Comment by thisiskeithb** [comment]
I've confirmed that this change breaks compatibility with a real MKS Mini 12864 LCD.
 
> If it needs it we can add a new LCD designation

I'm not sure there are enough cases where it's necessary. The Ender-2 is the only machine I'm familiar with that is defined this way.

> but maybe by chance some of these single-cable LCDs that come with Creality3D machines are equivalent to a "`CR10_STOCKDISPLAY`"…?

Again, I think it's just an issue with how the Ender-2 LCD is defined. It's more of a custom `MINIPANEL` with add ons like an encoder.

**Comment by thinkyhead** [comment]
> I'm not sure there are enough cases where it's necessary.

While I agree in principle and I want to keep defines to a minimum, we already have a small stable of displays that are one-offs or only paired with certain boards, so it wouldn't be too weird. I'll apply that approach because it's the simplest, if crudest, approach.

**Comment by thinkyhead** [comment]
I've restored the previous `MKS_MINI_12864` pins to retain compatibility with that display.

**Pull request merged**
