### PR TITLE
[AVR] Let laser use some servo timers when they're not used

### LINKED ISSUE #18973: [BUG] 2.0.5.3 Laser & servo (Bltouch) error in sanity check
### Bug Description

I'm configuring a Creality CR10S (mega 2560 board) with TTL laser, Bltouch and filament runout sensor, 
I can't figure out a wiring for everything that also compiles, I don't want to make any change to wiring every time i have to change to laser or 3D printing, so I want a dedicated pin for everything.
I have assigned in pin_RAMPS and RAMPS_creality:  
- Laser to pin 2 (PWM), 
- Bltouch servo to pin 11 (default Servo0 pin), and switch/sensor is pin 19 (Z max), 
- Moved runout to pin 15 (Y Max) (by default it is pin 2)

Also: 
- Enabled BL touch, set BLtouch pin to pin 19 
- Eabled Laser 
- Enabled filament runout detect
- Set num_servos to 1 

After changing the confings and start compiling I get a sanity check error: "Counter/Timer for SPINDLE_LASER_PWM_PIN is used by the servo system", so far i have read, enabling Bltouch enables servos and only leaves timer "A" pins unavailable, but pin 2 is on TIMER3B, 

Sanity check line is doing: 
#elif NUM_SERVOS > 0 && (WITHIN(SPINDLE_LASER_PWM_PIN, 2, 3) || SPINDLE_LASER_PWM_PIN == 5)
  #error "Counter/Timer for SPINDLE_LASER_PWM_PIN is used by the servo system."

I think maybe it's not doing the check correctly, as far as I understand the laser and servo [configuration](https://marlinfw.org/docs/configuration/laser_spindle.html) working and [conditionals](https://github.com/MarlinFirmware/Marlin/blob/92076c65601de5fdfe0facf32dd60c57aab05747/Marlin/src/inc/Conditionals_post.h), [servo.cpp](https://github.com/MarlinFirmware/Marlin/blob/92076c65601de5fdfe0facf32dd60c57aab05747/Marlin/src/HAL/AVR/Servo.cpp) and [servoTimers.h](https://github.com/MarlinFirmware/Marlin/blob/92076c65601de5fdfe0facf32dd60c57aab05747/Marlin/src/HAL/AVR/ServoTimers.h)

, enabling certain number of servos should occupy a timer ¿"A"? and it's related pin and leave the rest of pins and timers for other uses, i.e. 
- with NUM_SERVOS = 0 no servo is enabled
- with NUM_SERVOS = 1 only SERVO0_PIN is used (in ramps, it would be pin 11, attached to TIMER1A )
- with NUM_SERVOS = 2  SERVO0_PIN and SERVO1_PIN  are used (in ramps, it would add the use of pin 6, attached to TIMER4A)
- with NUM_SERVOS = 3  SERVO0_PIN, SERVO1_PIN and SERVO2_PIN  are used (in ramps, it would add the use of pin 5, attached to TIMER3A)
- with NUM_SERVOS = 4  SERVO0_PIN, SERVO1_PIN, SERVO2_PIN, SERVO3_PIN  are used (in ramps, it would add the use of pin 4, attached to TIMER0B)

Pin 2 and 3 are related to TIMER3B and TIMER3C, so it should not be a problem to even set any NUM_SERVOS > 0 , and use them for PWM, or is it ?, moreover I only need servo 0 for the BLtouch so I'm not even using Timer 3 for servos

Sorry for the length of the issue, any advice or comment would be apreciated

 

### My Configurations
I attach my configs and ramps/creality pins assignment 
[ramps.zip](https://github.com/MarlinFirmware/Marlin/files/5048623/ramps.zip)

### Steps to Reproduce

1. Explained in the description

**Expected behavior:** Compiles flawlessly

**Actual behavior:** sanity check error

#### Additional Information
I'm going to disable the sanity check line to see what happens, at least it allowed me to compile (will test if it works)

### PR DESCRIPTION
**Pull request by GMagician**
Relax sanity check when, in some custom configurastions, servo timer is freed

Fix #18973

### CODE REVIEW

**Comment by GMagician** [comment]
Added auto release timer resources

**Review by chepo92 — COMMENTED** [review]
What about: 
#if NUM_SERVOS > 0  
   #define _useTimer3
#if NUM_SERVOS > SERVOS_PER_TIMER
   #define _useTimer4

**Comment by GMagician** [comment]
AFAIK now (#19025) it uses timer 4. Not used by laser.  When servos are 0 HAS_SERVOS is false and nothing is used

**Comment by chepo92** [comment]
> AFAIK now (#19025) it uses timer 4. 

Not yet merged :D

> Not used by laser. When servos are 0 HAS_SERVOS is false and nothing is used

I think that is not always true for some boards, in the case that you have a Laser & BLtouch, as the later includes the servo file and messes everything, ( related to #18973 )

**Comment by GMagician** [comment]
That's ok about bl-touch and laser. But bltouch needs servo code so a timer is also needed to properly generate pwm.

Then:
0 servos used : no timers used (laser available)
1-12 servos used: only timer 4 used (laser available)
13-24 servos used: timer 4 and 3 used (no laser)

I think that once merged #19025 you have solved all your problem

**Pull request merged**
