### PR TITLE
Update language_nl.h

### PR DESCRIPTION
**Pull request by paulusjacobus**
Added these messages with Dutch translation

``` cpp
#define MSG_BED_Z
#define MSG_A_TRAVEL
#define MSG_HEATING_FAILED_LCD
#define MSG_ERR_REDUNDANT_TEMP
#define MSG_THERMAL_RUNAWAY
#define MSG_ERR_MAXTEMP
#define MSG_ERR_MINTEMP
#define MSG_ERR_MAXTEMP_BED
#define MSG_ERR_MINTEMP_BED
#define MSG_HEATING
#define MSG_HEATING_COMPLETE
#define MSG_BED_HEATING
#define MSG_BED_DONE
```

### CODE REVIEW

**Comment by jbrazio** [comment]
@paulusjacobus thank you for submitting the PR but you should submit it against `MarlinFirmware:RCBugFix` instead of `MarlinFirmware:RC`, please reference also somewhere on the description of the PR "Closes #3359".

**Comment by paulusjacobus** [comment]
Okay will do

**Comment by jbrazio** [comment]
When possible close this PR as it was superseded by #3371.

**Comment by paulusjacobus** [comment]
Hi @Jbrazio how do I close the PR? Do I do that within my fork?

**Comment by paulusjacobus** [comment]
Superceeded by #3371

**Comment by paulusjacobus** [comment]
Just managed to find the function to close PR (just a button under the PR
duh)

**Pull request closed without merging**
