### PR TITLE
Extruder with Dual Stepper Drivers

### PR DESCRIPTION
**Pull request by boelle**
EXPERIMENTAL code to drive a second extruder (E1) identically to the first (E0)
For setups with push-pull extruder motors and similar.
Thanks to Bo Herrmannsen & Marlin Discord

Pasted in by Alex Gibson (Edumaker) 20210321

### CODE REVIEW

**Comment by boelle** [comment]
is tihs one better?

**Comment by boelle** [comment]
need to add this to pins.h but the files look different in 2.0.x and bugfix so i cant figure where to add

```
/**
* Dual Extruder Stepper Driver
*
* EXPERIMENTAL code to drive a second extruder (E1) identically to the first (E0)
* For setups with push-pull extruder motors and similar.
* Thanks to Bo Herrmannsen & Marlin Discord 
*
* Pasted in by Alex Gibson (Edumaker) 20210321
*/

#if ENABLED(E_DUAL_STEPPER_DRIVERS)    
  #ifndef E2_STEP_PIN
    #define E2_STEP_PIN   _EPIN(E2_E_INDEX, STEP)
    #define E2_DIR_PIN    _EPIN(E2_E_INDEX, DIR)
    #define E2_ENABLE_PIN _EPIN(E2_E_INDEX, ENABLE)
    #if E2_E_INDEX >= MAX_EXTRUDERS || !PIN_EXISTS(E2_STEP)
      #error "No E stepper plug left for E2!"
    #endif
  #endif
  #ifndef E2_MS1_PIN
    #define E2_MS1_PIN    _EPIN(E2_E_INDEX, MS1)
  #endif
  #ifndef E2_MS2_PIN
    #define E2_MS2_PIN    _EPIN(E2_E_INDEX, MS2)
  #endif
  #ifndef E2_MS3_PIN
    #define E2_MS3_PIN    _EPIN(E2_E_INDEX, MS3)
  #endif
  #if AXIS_HAS_SPI(E2) && !defined(E2_CS_PIN)
    #define E2_CS_PIN     _EPIN(E2_E_INDEX, CS)
  #endif
  #if AXIS_HAS_UART(E2)
    #ifndef E2_SERIAL_TX_PIN
      #define E2_SERIAL_TX_PIN _EPIN(E2_E_INDEX, SERIAL_TX)
    #endif
    #ifndef E2_SERIAL_RX_PIN
      #define E2_SERIAL_RX_PIN _EPIN(E2_E_INDEX, SERIAL_RX)
    #endif
  #endif
```

**Comment by boelle** [comment]
@thisiskeithb all 3 files are now complete, should not need more work

its currently being tested on a clay printer where one stepper push'es the clay to the extruder and one does the actual printing/extruding.

**Comment by boelle** [comment]
we lost a few endif's and corrected those

**Comment by Roxy-3D** [comment]
I don't think we need the names in the code.  The merge history provides a record of who submitted the additional code.

**Comment by boelle** [comment]
> names in the code
 
names removed

**Comment by boelle** [comment]
i think i have switched arround things... what goes in stepper.cpp should have been in Configuration_adv.h and the other way round
at least that is what my head tells me

image
image

q is then if i got pins_postprocess.h right?

i asked this on discord also but no reply yet

**Comment by thinkyhead** [comment]
I believe I've got the right implementation here for you under the current codebase. Have Alex give it a test on his Dual E setup to make sure it works properly.

**Comment by edumaker-limited** [comment]
> I believe I've got the right implementation here for you under the current codebase. Have Alex give it a test on his Dual E setup to make sure it works properly.

Fantastic, we are on the testing now - the student group on the clay extruder and me on a test bed printer.

**Pull request merged**
