### PR TITLE
Added implementation for Huanyang VFD H2x spindles

### PR DESCRIPTION
**Pull request by atlaste**
### Requirements

This is an implementation for VFD's driven by H2x (H2A/H2B/H2C) spindles using the RS485 protocol. To test, you need one of these and a MAX485.

### Description

The purpose of this is to support more advanced spindles. Best way to use these is by using bidirectional communication, for which RS485 (modbus) is the normal channel.

Other modbus driven VFD's can also benefit from this implementation, as the timings of these are probably the same (but the commands are NOT). 

The code and why you want this on a spindle are well documented in the accompanying MD document (in DOCS)

### Notes!

Note that I added a working configuration.h / configuration_adv.h along with the implementation; you probably don't want to merge this along with the pull request. 

### Benefits

Spindle control through RS485.

### Related Issues

Dunno.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by noo-shell** [comment]
Would you recommend an RS485 adapter for MKS or SKR?

**Comment by atlaste** [comment]
I would recommend rs485 for any vfd driven spindle. 

But... when this pr was dropped (for good reasons) i basically had to rewrite it when moving to the devt branche... That was far from trivial with all the changes that were added, and eventually i just gave up. As a result, i moved to Grbl_Esp32, which now has rs485/vfd support.

**Comment by noo-shell** [comment]
> I would recommend rs485 for any vfd driven spindle.

I meant rs485 adapter for the SKR or MKS control board.
It's about adapter input not output.

**Comment by atlaste** [comment]
@kamilj I wouldn't know. I think RS485 is the only sane choice for VFD's, because it's bidirectional and VFD's are normally connected to very strong spindles, which means error handling is quite important. You don't want things to go wrong there. I don't care what board is underneath.

As for other purposes of RS485, it depends on the purpose, and it certainly has nothing to do with this pull request / code.

**Comment by noo-shell** [comment]
@atlaste I keep my fingers crossed for you to add this code to the main branch.

**Pull request closed without merging**
