### PR TITLE
Cancel Individual Objects

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR adds an `M486` G-code as a technique to both identify and cancel objects during a multi-object print job.

- `M486 Tn` resets the state and sets the number of objects.
   (Basic reset occurs automatically upon "starting a new print job.")
- `M486 Sn` is used to set the index of the current object.
   (The object count may increase in response to this.)
- `M486 S-1` is used to indicate a non-print object such as a brim or purge tower.
- `M486 Pn` is used to cancel an object by index.
- `M486 C` is used to cancel the current object.
- `M486 Un` is used to un-cancel an object by index.
  (Only useful before the layer gets skipped)

Based on work by @paukstelis and previewed at ERRF2019.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
M86?    That is both funny and an easy to remember number!

**Comment by LinFor** [comment]
Seems that M86 already used for other purposes in Prusa-Firmware fork: https://github.com/prusa3d/Prusa-Firmware/blob/5a4126e00c375bb2cd9839fdcb861ba725d01d87/Firmware/Marlin_main.cpp#L3386

**Comment by LinFor** [comment]
Made simple Cura post-processing script to mark objects with these rules: https://github.com/LinFor/Cura/blob/e-bot/plugins/PostProcessingPlugin/scripts/MarlinObjectsMarking.py

**Comment by Roxy-3D** [comment]
> Seems that M86 already used for other purposes in Prusa-Firmware fork:

It would appear it is already documented as being in use by Marlin:
 
https://reprap.org/wiki/G-code#M86:_Cancel_Object

A big effort is expended to make sure we don't step on already established GCodes and MCodes.   But other developers need to make some effort too.   They need to document their usage of anything new because it is impossible to try to hunt down every version of firmware and do a check.

**Comment by thinkyhead** [comment]
To avoid collision this can be changed to `M486`….

**Comment by thinkyhead** [comment]
I have added Prusa to the list of firmwares that shows up on the RepRap G-code wiki page…
image

**Comment by paukstelis** [comment]
Minor point for the Wiki: `M486 S4  ; Indicate that the 4th object is starting now` should probably be `5th object`. Or maybe just object at index 4.

**Comment by thinkyhead** [comment]
After #15593 I'll have a tweak for the menu so it can show itemized items without the extra customization lines. I have not yet given this a proper test, so I will do some of that this afternoon.

**Pull request merged**
