### PR TITLE
`int` in place of `bool` saves several K of PROGMEM

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR is for demonstration purposes, and still needs to be tested for its performance benefits. However, on my i3 with character display, sd card, mesh bed leveling, and a few other features enabled, this small change resulted in a PROGMEM savings of 19K, at an additional cost of 28 bytes of SRAM.

- Added `typdef unsigned int BOOL` to `types.h`
- All instances of `bool` have been replaced by `BOOL`

### CODE REVIEW

**Comment by Roxy-3D** [comment]
> Added typedef unsigned int BOOL to types.h

I bet doing
```cpp
typedef unsigned char BOOL
```
will not be worse and very likely will be better.

**Comment by thinkyhead** [comment]
I've been trying to reproduce my previous result, and I get the feeling I must have been mistaken. I keep getting a build 3K larger now.

**Comment by Roxy-3D** [comment]
> this small change resulted in a PROGMEM savings of 19K,

> I've been trying to reproduce my previous result, and I get the feeling I must have been mistaken. I keep getting a build 3K larger now.

The 19 KB is suspicious.   If we were going to save even 4 or 5 bytes per evaluation of a boolean, that would imply we have thousands and thousands of references to bool.   And we don't have anywhere near that amount.

**Comment by thinkyhead** [comment]
My original question was merely "are bools faster than bit set/clear/test?" and then I got sidetracked checking whether AVR processors are doing foolish things with `bool`, like extending them to 16 bits when putting them on the stack or otherwise adding overhead.

Apparently not!

I'm still wondering about those bit tests though. Just looking to recover a few meager cycles in the stepper ISR, of course.

**Pull request closed without merging**
