### PR TITLE
[2.0.x]Add Silver Gate board

### PR DESCRIPTION
**Pull request by android444**

### CODE REVIEW

**Comment by teemuatlut** [comment]
Is this like a board you're planning on selling on a larger scale?

**Comment by android444** [comment]
You want to buy?
Several pcb sold.

**Comment by android444** [comment]
What is wrong?

**Comment by thinkyhead** [comment]
This PR is stale and will need to be recreated, or it can rebased from the command-line and force-pushed if you know that procedure. BE sure to start with the latest `bugfix-2.0.x`.

**Comment by android444** [comment]
This PR was added to the latest 2.0 bugfix.

Do I have to do it again?

**Comment by thinkyhead** [comment]
> Do I have to do it again?

It will need to be recreated, or it can rebased from the command-line and force-pushed if you know that procedure.

**Comment by android444** [comment]
I'll close this PR and get a new one.

**Comment by android444** [comment]
Add new PR.

**Pull request closed without merging**
