### PR TITLE
Add creality board v4.2.5, found on CR200B printer

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Add creality board v4.2.5, found on CR200B printer

### CODE REVIEW

**Comment by G-Pereira** [comment]
This is great news for me but is there any LCD files that go along with this? Maybe is there any printer that shares the same screen model specifically?

**Comment by rhapsodyv** [comment]
> This is great news for me but is there any LCD files that go along with this? Maybe is there any printer that shares the same screen model specifically?

Working on it… 
It already works with a 12864 lcd, but I’m working to bring the TFT support of it too.

E7F5D3BF-4D02-4DF3-B971-AB1B7B61B618

**Comment by G-Pereira** [comment]
awesome! Thank you for your contributions!

**Comment by kazuimis** [comment]
Is there any updates on this? 🤓

**Pull request merged**
