### PR TITLE
Enable LCD_PIN_RESET if it exists

### PR DESCRIPTION
**Pull request by thinkyhead**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Intended to be a clean version of #2016 but my fork was screwed up by recent unfortunate changes to Marlin Development branch. I might need to delete my fork and start over.

**Comment by Wackerbarth** [comment]
@thinkyhead - You are creating the branch issues because you MERGED the new Development into your existing branch.  Don't do it that way. Pick a clean root for Development (that is NOT on your history path) and rebase to it.

**Comment by thinkyhead** [comment]
> You are creating the branch issues because you MERGED the new Development into your existing branch. Don't do it that way.

I would like to throw out my Development branch and start over.

**Comment by thinkyhead** [comment]
#2375

**Comment by Wackerbarth** [comment]
@thinkyhead - So, what's stopping you?  You have a branch or tag for each feature that is still "open".
Just delete your "Development". Rebase each of the "open" branches to upstream (MarlinFirmware) Development.

**Comment by thinkyhead** [comment]
> So, what's stopping you?

Nothing except uncertainty. So in fact I did replace it mere seconds after writing my comment.

**Pull request closed without merging**
