### PR TITLE
STEVAL_3DP001V1: Fix missing file & onboard SD with STM32 soft SPI

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
Changes:
1) Add a soft SPI to the STM32 HAL.  This will allow accessing the on-board SD cards via SPI on the STM32F4xx and the STM32F7xx boards.
2) Change the **pins_STEVAL_3DP001V1.h** file so that the on-board SD card is available (via SPI) when **SDSUPPORT** is enabled.
3) Add required file **variant.cpp** - can't compile without it

This has been tested on a STEVAL_3DP001V1 board.

---

Also enabling the IWDT module for the STEVAL_3DP001V1 variant.

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Bugfix-2.0.x will fully support your board once PR #16579 is merged.  

The only items not supported are:
- WIFI module 
- More than one bed thermistor (a Marlin limitation)
- USB memory stick 

I've been able to connect my browser to the WIFI (that was a pain) but I have not been able to figure out how to make the UART interface functional.

**Comment by Bob-the-Kuhn** [comment]
@fradaxx found a bug in the M906 command.

Changes:
- Changed the overview to state that for a L6474 it sets the TVAL current (4A max) and on the others it sets the KVAL_HOLD register (0-255) and removed non-applicable items. 
- Changed the L6470_SET_KVAL_HOLD macro to set the TVAL current if the stepper is a L6474
- Changed the value used from byte to int
- Corrected the Vs_compensation formatting on the L6474 to match the other L64xx types.

**Comment by thinkyhead** [comment]
@Bob-the-Kuhn — Is there a "Allow edits by maintainers" checkbox on the right side of this page when you view it? If so, could you check that box? I'm not sure why, but lately new PRs are non-editable by default.

**Comment by thinkyhead** [comment]
Nothing too tricky here, so I merged it directly. Closing.

**Comment by Bob-the-Kuhn** [comment]
~Please don't merge this PR yet.  I may have another feature to add.~

Too late.

If this materializes then I'll do another PR.

**Pull request closed without merging**
