### PR TITLE
FT_MOTION menu : more consistency in LCD ft_motion menu, add zeta and vtol to menu

### PR DESCRIPTION
**Pull request by narno2202**
### Description
For now, all the items are shown in FT_MOTION menu whether options are enabled or not.
With this PR, depending of the  selected option, only editable items are shown.

### Benefits

More consistency in LCD ft_motion menu

### Some pics
Taken from Marlin Simulator
Menu-onMenu-off
Menu-ModeOnMenu-LinearAdv
Menu_DF_ModeOnMenu_DF_ModeOff

### CODE REVIEW

**Comment by lukasradek** [comment]
In screenshots, you can also see a bug where "submenu arrow" is drawn over text in EDIT_ITEM.
This PR fixes it - https://github.com/MarlinFirmware/Marlin/pull/26073

**Comment by danbrianwhite** [comment]
I also noticed the menu is not available during print.

Can it be enabled to work during a print since you can send gcode to update the values during the print? Or is that a complex issue?

**Comment by narno2202** [comment]
@danbrianwhite , this is the same with input shaping in standard motion system. It's probably not so complex, the submednu as to be added in `menu_tune.cpp`. But is it really necessary?

**Comment by danbrianwhite** [comment]
Probably not necessary. It can be helpful to tone manually on demand during
a print. However, most people will likely never use it that way.

**Comment by thinkyhead** [comment]
Changing some parameters during a print is potentially dangerous. The G-code that handles these changes does some extra checks and callbacks in response to parameters changing, which could be reproduced in the menus, but before we go there it would be good to get FT Motion completed and stable first.

**Comment by narno2202** [comment]
I also think that parameters must not be  available during a print, which is currently the case. Perhaps only disabling shaping or ft_motion could be allowed. @thinkyhead, did you see @danbrianwhite comment on FT_MOTION with his corexy printer ?

**Pull request merged**
