### PR TITLE
Remove the hotbed icon from the status screen

### PR DESCRIPTION
**Pull request by jbrazio**
Remove the hotbed icon from the status screen when `HAS_TEMP_BED` is false.

Before:
old1

After:
new1

### CODE REVIEW

**Comment by AnHardt** [comment]
Looks really nice.

But seeing all that 0x00 in the graphics arrays i'm reminded how inefficient this is. At first we store all the zeros in the memory, later we draw all of them - which is time consuming.

Splitting the 'big' heater graphic into several small, on a per heater basis and drawing only the needed is much more efficient. (https://github.com/AnHardt/Marlin/pull/13/commits/b775af25d4afbb6c8ba164b9ec8245a287b1fe57 Sorry outdated)

**Comment by jbrazio** [comment]
I thought this was like this to avoid calls to the draw function in order to be more efficient.

**Comment by AnHardt** [comment]
@jbrazio 
I admit, i have not benchmarked that. But from following the code for `drawBitmapP()` in u8glib i know the overhead for calling the function is minimal compared to the amount of work that has to be done for setting a single pixel, even if it is a zero.  
If i read my measurement, from then, correct, omitting the complete extruder/bed/fan graphic saved ~10ms/s. Drawing a single device needed ~3ms/s. Other improvements saved a bit (2-3ms/s). For drawing 2 extruders, bed and fan there was still a tiny improvement. With 3 extruders, bed and fan i expect a penalty of ~1-2ms/s compared to the original time.
The limit to display not more than 3 extruders is due to using 4 chars per temperature (21/4 = 5.25). If we want to alternate between bed and fan to make room for a 4th extruder  we'd need an other of the big graphics, while with the small, separated graphics the memory usage w'd increase only by 1/5. If we, one day, try to support a chamber temperature i'd suggest to display [active extruder, other extruders (alternating), bed, chamber, fan]. Do  you see the memory problem?

**Comment by AnHardt** [comment]
However. This PR is ok for now. Splitting the graphics is more a thing for after 1.1.0.

**Comment by jbrazio** [comment]
Not only splitting.. but take synergy of refractoring as an object to maybe do a rewrite from scratch ?

**Pull request merged**
