### PR TITLE
MPC differential tuning bug fixes

### LINKED ISSUE #27181: [BUG] M306 T produces negative responsiveness value
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Having installed a new, original E3D Revo 12v hotend I ran M306 and got the below values:

`:Recv: MPC Autotune finished! Put the constants below into Configuration.h
Recv: MPC_BLOCK_HEAT_CAPACITY 9.36
Recv: **MPC_SENSOR_RESPONSIVENESS -0.9229**
Recv: MPC_AMBIENT_XFER_COEFF 0.0525
Recv: MPC_AMBIENT_XFER_COEFF_FAN255 0.0884`

The negative responsiveness value led to a thermal runaway issue until I realized what was happening and removed the minus sign.

### Bug Timeline

With a new E3D Revo.

### Expected behavior

Normal values

### Actual behavior

Recv: **MPC_SENSOR_RESPONSIVENESS -0.9229**

### Steps to Reproduce

T1 (it's a dual system)
M306 T

### Version of Marlin Firmware

2.1.2.3

### Printer model

Custom coreXY Hypercube

### Electronics

SKR 3

### LCD/Controller

BTT-12864

### Other add-ons

_No response_

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin.zip](https://github.com/user-attachments/files/15858901/Marlin.zip)

### LINKED ISSUE #27253: [BUG] Wrong MPC settings can cause thermal runaway
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I already reported this in #27236, but no response there and I think this issue needs attention.

Because of #27236 all my MPC settings were set to 0, which causes a thermal runaway of the hotend, the heater keeps heating 100% while the target temp is not changed (still set to 0). I use a ceramic heater which did not survive this, even though I have thermal protection enabled.

### Bug Timeline

Introduction of MPC (I guess)

### Expected behavior

MPC doesn't allow bad values, to prevent a thermal runaway.

### Actual behavior

Hotend thermal runaway (broken ceramic heater)

### Steps to Reproduce

1. Set all MPC parameters to 0, and save them with M500
2. Restart the printer and monitor the hotend temperature
3. Switch the printer off asap when you see the heater start heating or unplug the hotend heater
RECOVERY: Run M502, M500 and restart the printer

### Version of Marlin Firmware

Latest bugfix July 2024

### Printer model

Custom

### Electronics

MKS Monster8 V1.0

### LCD/Controller

BTT TFT35 V3.0

### Other add-ons

BTT EBB42 V1.2

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

I suggest to set some limits to the MPC parameters where needed.
I guess all values should be positive, and MPC_HEATER_POWER should have a minimum value (10?).
Setting some values to 0 might cause a divide by 0 issue, causing unpredictable results.

[Configuration_adv.zip](https://github.com/user-attachments/files/16140443/Configuration_adv.zip)

### PR DESCRIPTION
**Pull request by tombrazier**
### Description

This PR fixes several problems with the MPC differential tuning method.

- Moved option to enable MPC debugging to `Configuration.h`.
- Fixed derivative calculation (was delta temp * delta time, should have been delta temp / delta time, worked anyway because delta time happened to be 1).
- Fixed time calculation for when maximum rate is observed. The return value of `get_elapsed_heating_time()` was not yet initialised at the point where it was being called.
- Fixed call to `tuner.get_time_fastest())` which should have been `tuner.get_temp_fastest())`. (See equation 17 at https://marlinfw.org/docs/features/model_predictive_control.html.)
- Added a second check for nonsensical `MPC_BLOCK_HEAT_CAPACITY` and `MPC_SENSOR_RESPONSIVENESS` values after the "Refining estimates..." step. This could happen when using the automatic tuning method which attempts an asymptotic tune and then falls back to differential if the results don't make sense. See #27181.

### Requirements

Enable `MPCTEMP`.

### Benefits

Differential tuning now works and it is more likely that the automatic tuning method will fall back to differential tuning when needed. In particular this should make `M306 T` work seamlessly for Revo hotends.

### Configurations

Enable `MPCTEMP`.

### Related Issues

- #27181
-  #27253

### CODE REVIEW

**Comment by tombrazier** [comment]
Build error related to FT_MOTION, not this PR.

**Comment by thisiskeithb** [comment]
> Build error related to FT_MOTION, not this PR.

Breaking changes were reverted in https://github.com/MarlinFirmware/Marlin/commit/ade05c045ef13f0f8a557ef0588a6ac6a80a1ab1, so merge in the latest `bugfix-2.1.x` or rebase your PR & force-push changes.

**Comment by thinkyhead** [comment]
> Breaking changes were reverted…

NOTE: A PR doesn't need to be updated if its changes don't overlap with changes to `bugfix-2.1.x`. The CI tests are done by merging the changes from the PR onto the _current_ `bugfix-2.1.x` _at the time the tests are initiated_. If the `bugfix-2.1.x` branch has a compile error and then it is fixed, you don't have to take extra steps to update your branch if there are no conflicting changes; just re-run the tests.

**Comment by thisiskeithb** [comment]
> just re-run the tests.

That only works if you have proper repo permissions, so merging in the latest changes works universally for everyone.

**Comment by thinkyhead** [comment]
Hmm, where did we put that "re-run yer own bloody PR's tests" permission? That seems like something we should have.

**Pull request merged**
