### PR TITLE
Enhanced routines for DWIN display on Ender3v2

### PR DESCRIPTION
**Pull request by mriscoc**
### Description
This pull request add many improvements to the Ender3v2 DWIN display:  

- Enhanced support for print from host (M73-M77)
- Show error popup on kill conditions
- GUI support for advanced pause feature
- Enhanced status messages
- Enhanced popups for PID, homing and leveling
- Reboot screen for M997
- Flow control on Motion and Tune menu
- Change filament item on Tune menu
- Filament management on Prepare menu
- Manual leveling assistant
- Manual mesh assistant
- Display brightness control
- Sound enabling control
- Allows to use the probe (BLTouch) for Bed Tramming
- Filament settings menu, with load and unload length, active sensor, etc.
- Hotend PID settings menu
- Bed PID Settings menu
- Z-offset wizard menu
- Editable display items color
- Simple lock screen
- New menu subsystem

**Enhanced DWIN library**
* New string and numeric overloaded functions
* Drawing functions with graphic cursor implementation
* Draw image with transparent background
* Write Image data to Display SRAM
* Write data to Display Flash
* Draw Image from SRAM
* QR generator

### Requirements

Ender3v2 with DWIN display

### Benefits

Because the Ender3v2 do not has a standard LCD display, many status and process messages cannot be displayed on their screen. This pull request tries to allows to display some of that process, how the ability of change filament with purge, make a manual leveling, show the PID process, show the error on kill, etc. Add important support for printing from a host as Octoprint.
Also, many new functions have been added to the DWIN library to enhance the graphic drawing on the display.

### Configurations

[Configuration_Ender3v2.zip](https://github.com/MarlinFirmware/Marlin/files/6912413/Configuration_Ender3v2.zip)

### CODE REVIEW

**Comment by thinkyhead** [comment]
Perhaps you can help to adapt elements of this fork: https://github.com/smith3d/Jyers_Marlin which is described in this video: https://www.youtube.com/watch?v=EY87ai3-IXo 

There seem to be a lot of coders messing around with this display because it's accessible, and this is resulting in fragmentation, so it is hard to decide what should end up being the "official" user interface that gets included here in the main branch.

Meanwhile, there is still  #19371 in progress. It needs to be debugged and then completed, but as soon as that's sorted we will have all Marlin menus and screens, and translation to all the languages, assuming we can install the needed fonts onto the screen.

**Comment by mriscoc** [comment]
> Perhaps you can help to adapt elements of this fork: https://github.com/smith3d/Jyers_Marlin which is described in this video: https://www.youtube.com/watch?v=EY87ai3-IXo
> 
> There seem to be a lot of coders messing around with this display because it's accessible, and this is resulting in fragmentation, so it is hard to decide what should end up being the "official" user interface that gets included here in the main branch.
> 
> Meanwhile, there is still #19371 in progress. It needs to be debugged and then completed, but as soon as that's sorted we will have all Marlin menus and screens, and translation to all the languages, assuming we can install the needed fonts onto the screen.

I do not use Extensible UI because you recommended do not follow this way here [#21328](https://github.com/MarlinFirmware/Marlin/pull/21328) also I'm porting features from my [fork](https://github.com/mriscoc/Marlin_Ender3v2/releases) to upstream. I'm trying to follow the structure of the original Creality DWIN code, and make it compatible with MarlinUI as far as possible.

**Comment by thinkyhead** [comment]
> I do not use Extensible UI because you recommended do not follow this way here

That is sensible. I'm not sure that the fork I linked is _really_ using Extensible UI to any great degree, since the screen is not capable of sending or receiving any commands over the serial port. The code could most likely be ported over without trying to shunt it into the ExtUI API.

**Comment by mriscoc** [comment]
Hi, @thinkyhead, I see this change 
```
-- DWIN_Stop_Print());
++ DWIN_Print_Finished());
```
I think that the name DWIN_Stop_Print is better because it is also called when you press the stop button on the display and also the stop print button on the host. That is, the print was not necessarily finished, it could have been aborted. 

Regards

**Comment by mriscoc** [comment]
Hi, @thinkyhead, I see this change 
```
-- DWIN_Stop_Print());
++ DWIN_Print_Finished());
```
I think that the name Stop_Print is better because it is called when you press the stop button on the display and also the stop print button on the host. That is, the print was not necessarily finished, it could have been aborted.

**Comment by thinkyhead** [comment]
It isn't a function that stops the print, so I changed the name to reflect that it is more like `ExtUI::onPrintFinished` and that it is called under the same circumstance (when the Ender 3 v2 support code –as implemented– presumes that the print has finished) so that the display can update itself. It is also called from `M77`, which is a potential indication that the host has reached the end of a print job. So in both cases the intent is to inform the display that the print job has ceased.

**Comment by thinkyhead** [comment]
In the interest of bringing this custom DWIN code into some compliance with the rest of Marlin, let's look at the `Draw_ManualLev_Menu`. This is not actually "Manual Leveling" as mistranslated by Creality. It is actually "Bed Tramming." It can be enabled or disabled, and it is user-configurable to use more points and to get names of the points from the configuration. There are probably other items like it. I will fix up this one. If you see any others, feel free to bring them into the fold.

Of course, I will also continue to work on #19371 with the aim of providing the full menu system to this display so that it provides a consistent system that gains functions at the same time as all `MarlinUI` displays. Once that PR is completed we'll finally have a HMI/DWIN/DGUS display with the full menu system and complete language support, and we can move on to the next HMI/DWIN/DGUS display needing a `MarlinUI` implementation.

**Comment by mriscoc** [comment]
Please revert this change in dwin_lcd.cpp:
```
-    b=sqrt(r*r-a*a);
+    b = HYPOT(r, a);
```
b is a side; it is not the hypotenuse.
regards.

**Comment by thinkyhead** [comment]
You can of course make changes to your own branch and push the commits to update this PR.

**Comment by mriscoc** [comment]
> You can of course make changes to your own branch and push the commits to update this PR.

I know, but I was thinking that could be not very kind if I reverted your changes without explain.

**Comment by thinkyhead** [comment]
No worries. The change in this case would surely explain itself.

**Comment by thinkyhead** [comment]
Did a merge and final cleanup. If nothing is terribly broken then this can be merged soon for wider testing.

**Comment by mriscoc** [comment]
> Did a merge and final cleanup. If nothing is terribly broken then this can be merged soon for wider testing.

What is the difference / improve between DWIN_StatusChanged and DWIN_StatusChanged_P ?

**Comment by thinkyhead** [comment]
> What is the difference / improve of `DWIN_StatusChanged` and `DWIN_StatusChanged_P` ?

If someone wants to use this DWIN display with an AVR board we must ensure that `PROGMEM` strings are used, and these strings require special accessors because their memory addresses are located in Flash. Those who have been working on the Creality DWIN code up to now have been assuming that it will only ever be deployed on 32-bit platforms with no special accessors. But AVR is not dead! So in Marlin we are trying to be considerate of that architecture.

**Comment by mriscoc** [comment]
> Did a merge and final cleanup. If nothing is terribly broken then this can be merged soon for wider testing.

What is the difference / improve of DWIN_StatusUpdate and 

> > What is the difference / improve of `DWIN_StatusChanged` and `DWIN_StatusChanged_P` ?
> 
> If someone wants to use this DWIN display with an AVR board we must ensure that `PROGMEM` strings are used, and these strings require special accessors because their memory addresses are located in Flash. Those who have been working on the Creality DWIN code up to now have been assuming that it will only ever be deployed on 32-bit platforms with no special accessors. But AVR is not dead! So in Marlin we are trying to be considerate of that architecture.

Oh I see, Thank you.

**Comment by CRCinAU** [comment]
> There seem to be a lot of coders messing around with this display because it's accessible, and this is resulting in fragmentation

I have been warning various parties about this from day #1. Over many months, very little has been upstreamed into Marlin, so I applaud @mriscoc for this work on getting the code into Marlin - as eventually, the forks get too far apart and too difficult to keep in sync.

This can be seen already with the Jyers fork:
image

It would be much better to combine efforts than the existing paths of everybody going their own way - as eventually, everyone's fork gets too far to bring back - no matter the intentions.

**Comment by mriscoc** [comment]
> > There seem to be a lot of coders messing around with this display because it's accessible, and this is resulting in fragmentation
> 
> I have been warning various parties about this from day #1. Over many months, very little has been upstreamed into Marlin, so I applaud @mriscoc for this work on getting the code into Marlin - as eventually, the forks get too far apart and too difficult to keep in sync.
> 
> This can be seen already with the Jyers fork:
> image
> 
> It would be much better to combine efforts than the existing paths of everybody going their own way - as eventually, everyone's fork gets too far to bring back - no matter the intentions.

Thank you. I'm happy to contribute.

**Comment by thinkyhead** [comment]
I did a quick rebase of the Jyers fork on top of the current `bugfix-2.0.x` code to see how many changes are required. Of course, it is quite different from this PR and the current bugfix code, but it probably contains all the functions that this PR has. The simplest way to compare is to flash each one and look at the user interface in action, trying out all the functions, and if anything is missing or incomplete compared to the other, then bring over the implementation.

One of the main things blocking me from merging some final result is that I expect they both have incomplete Chinese support, and I think it's important for us to give consideration to the Chinese user who wishes to upgrade to the most recent and bug-free version of Marlin with the reasonable expectation that Chinese will continue to be supported.

In the long run, I very much want to get Chinese (plus Western and Vietnamese-Accented, Greek, and Cyrillic) fonts installed and be able to simply use the existing UTF strings to draw menus. This would eliminate the requirement to use images. But I suspect this is not easy, otherwise Creality3D would have done it already.

I've got to put in time today to plough through the current PRs, as usual, but hopefully tonight I will have energy remaining to dive back into the MarlinUI-for-E3V2 pull request and explore the limits of what this particular HMI/DWIN can do.

**Comment by CRCinAU** [comment]
@thinkyhead I believe that if a chinese translation is required that whoever wants that should step up to implement it.

Given that this work has been a lot of effort, I don't believe it should be hampered by an incomplete Chinese translation. It doesn't make sense to me to penalise the thousands of users of DWIN printers because of the lack of Chinese.

Functionality wise, this PR will bring the printer up to the standard we would have expected it to ship with - which is far from what it has been in the past. Further improvements can be made via PRs of interested parties - and for example the Chinese translation doesn't come forwards, then I don't believe we should be burdening the community with supporting it.

**Comment by Jyers** [comment]
@thinkyhead Very well put. It means a lot to know that you actually took the time and were interested in my fork. My long term goal has always been to get it upstream, but I've always been worried of the feasibility of this considering it is a complete rewrite.

I rewrote the code with the goal of making it much easier to understand and develop for, but have never been certain if my format would fly upstream. If you take a look at my dwin code and think it is an improvement over the current dwin implementation I would happily get a PR going. My goal is just to make development for DWIN easier and more accessible, so if you think that it's ready to be brought to the main repo and would improve development for you and other contributors I would be happy to get started with that process.

**Comment by mriscoc** [comment]
> @thinkyhead Very well put. It means a lot to know that you actually took the time and were interested in my fork. My long term goal has always been to get it upstream, but I've always been worried of the feasibility of this considering it is a complete rewrite.
> 
> I rewrote the code with the goal of making it much easier to understand and develop for, but have never been certain if my format would fly upstream. If you take a look at my dwin code and think it is an improvement over the current dwin implementation I would happily get a PR going. My goal is just to make development for DWIN easier and more accessible, so if you think that it's ready to be brought to the main repo and would improve development for you and other contributors I would be happy to get started with that process.

Maybe is better idea that you post your PR and wait to be merged. I post my PR's sometimes are accepted, sometimes no, for example this https://github.com/MarlinFirmware/Marlin/pull/21679 and this https://github.com/MarlinFirmware/Marlin/pull/21328 were rejected, and I understand that is better to do a step-by-step PR.

**Comment by CRCinAU** [comment]
@thinkyhead Just trying to get some idea on what the plan is for this PR... It's been on the table for over 2 months now - and given the very limited state of current DWIN stuff, it's very much a highly anticipated PR...

**Comment by thinkyhead** [comment]
@CRCinAU — We cannot merge both this PR and the work by @Jyers. But, I want to keep this around so that after Jyers is merged elements of this can be moved over to fill in any gaps.

I started on a merge of the @Jyers code a couple of weeks ago, but the sheer volume of Pull Requests recently has prevented me from getting back to that task. Good help is hard to find, and since no one has made any effort to submit a PR to merge in Jyers' work, you will just have to continue waiting on little old me.

**Comment by Jyers** [comment]
@thinkyhead Perhaps I would be a good candidate to help concidering the situation :)

If you email me at Jyers.Marlin@gmail.com we can discuss the PR and see how I can best help to get it done.

**Comment by thinkyhead** [comment]
@Jyers — Ok, I've sent you an email giving a basic outline on how to proceed.

**Comment by thinkyhead** [comment]
Rather than trying to merge this E3V2 implementation with the Jyers implementation (as they are very different) it will be simplest to merge them both as separate options for a while and gradually bring them together over the next couple of years. This PR is the simpler of the two, so it could be merged first as the replacement for Creality's UI. However, there are a couple of things needed to make this more complete…
- In the current code, long filenames in the file selector will scroll to show more of the name. But that seems to have gotten broken in this PR, or maybe at some other point. Filename scrolling is working properly in the Jyers version.
- Most of the menu item titles are antialiased text images, but the newly-added titles are plain text. I would like to make them consistent, either by adding more titles to the appropriate JPG or by not using images for English. When images are not used, more Western languages can be supported in the language selection, handled automatically by the `GET_TEXT` macro.
- Chinese is mostly complete, so it is tantalizing to fill in the missing titles. We could use some help from someone who knows Chinese to finish them, or we could attempt to do it ourselves by referring to the `language_zh-CN.h` / `language_zh-TW.h` files and Google Translate.

I hope to be able to create a completely unified `DWIN_SET` that can be used for this PR, the JyersUI, and MarlinUI, so that we only have to flash the screen once and then we can more easily switch between them. So, the icons for the MarlinUI version would have Icon IDs higher than the Icon IDs in the standard `DWIN_SET` that we now use.

As for multi-language support… It should be possible to create a menu title image for each language, so if someone wanted Japanese, they would only have to put a different JPG into the `DWIN_SET`, re-flash the screen, and all the menu items would be Japanese. Of course, for long-term viability it would be best to write a Python script that uses ImageMagick to generate a JPG for each language, also printing out the code to draw the menu title. Or, better, we could put all the menu titles into ICO files with matching icon IDs, so coordinates wouldn't need to be known in the code.

It would be interesting to see, ahead of time, if menu titles can be readily converted into ICO, or if it's a major hassle. We already have scripts to convert images into ICO files (linked from the MarlinUI PR), so those would be applied in concert with a new Python script that generated the JPG files for the titles.

**Comment by mriscoc** [comment]
> Rather than trying to merge this E3V2 implementation with the Jyers implementation (as they are very different) it will be simplest to merge them both as separate options for a while and gradually bring them together over the next couple of years. This PR is the simpler of the two, so it could be merged first as the replacement for Creality's UI. However, there are a couple of things needed to make this more complete…

I agree, also, I'm experimenting with a menu system based in this PR, I hope to have it implemented soon.

> 
> * In the current code, long filenames in the file selector will scroll to show more of the name. But that seems to have gotten broken in this PR, or maybe at some other point. Filename scrolling is working properly in the Jyers version.

I will check, it was working before with #define LONG_FILENAME_HOST_SUPPORT and #define SCROLL_LONG_FILENAMES.

> * Most of the menu item titles are antialiased text images, but the newly-added titles are plain text. I would like to make them consistent, either by adding more titles to the appropriate JPG or by not using images for English. When images are not used, more Western languages can be supported in the language selection, handled automatically by the `GET_TEXT` macro.
> * Chinese is mostly complete, so it is tantalizing to fill in the missing titles. We could use some help from someone who knows Chinese to finish them, or we could attempt to do it ourselves by referring to the `language_zh-CN.h` / `language_zh-TW.h` files and Google Translate.
> 

Yes, this implementation has only support for Chinese text images from the original assets, if a more complete text image is supplied, I could add the support for the missing items. For English maybe is better to use #define USE_STRING_TITLES.

**Comment by thinkyhead** [comment]
> … `SCROLL_LONG_FILENAMES` …

Hmm, actually I didn't check whether that was enabled. I'll make sure it's turned on in the examples, and in my test configs!

**Comment by thinkyhead** [comment]
You may want to leave out references to `IS_DWIN_MARLINUI` because that feature is not merged yet, and there is no way that it could be sharing any of the files being added in this PR until afterward. Which implies that the MarlinUI feature must be merged before this gets merged, so that it will be possible to sort out afterwards in this PR.

**Comment by thinkyhead** [comment]
The use of `namespace` over `class` is slightly controversial. Generally the best thing about a `namespace` is that it provides one of the simpler ways to do overrides without needing to create a `class`. See the language files, for example. But, if this type of override is not actually being used, then the use of a `namespace` becomes kind of superfluous, and a `class` or `class` template may be the better choice because it also provides access specifiers and other useful constructs.

You will note that in my updates to the JyersUI pull request that I modified the class to make it completely `static`, which is generally the way I've been doing singletons in the Marlin codebase, and I don't see any reason why we would not also implement this as a singleton class, with an eye towards making a good base class that all these implementations can eventually share, with each one having its own sub-class for the methods where they are differentiated.

But what do you think? What are the advantages you see in using a `namespace` instead of a `class`?

**Comment by mriscoc** [comment]
> But what do you think? What are the advantages you see in using a `namespace` instead of a `class`?

DWINUI is mainly static, it is not necessary to create additional or derivate objects of it because it is basically a library with variables and functions grouped. I use it only for create a group of identifiers where could be possible add more elements across translation units.
On the contrary, menu and menu items are classes because I need to create derivate objects from them, for example in my test implementation, I can to create menus by this code:

```cpp
void onDrawMenuItem(MenuItemClass* menuitem, int8_t line) {
  if (menuitem->icon) DWINUI::Draw_Icon(menuitem->icon, ICOX, MBASE(line) - 3);
  if (menuitem->caption) DWINUI::Draw_String(LBLX, MBASE(line) - 1, menuitem->caption);
  DWIN_Draw_HLine(HMI_data.SplitLine_Color, 16, MYPOS(line + 1), 240);
}

void onDrawSubMenu(MenuItemClass* menuitem, int8_t line) {
  onDrawMenuItem(menuitem, line);
  DWINUI::Draw_Icon(ICON_More, VALX + 10, MBASE(line) - 3);
}

void Back_Test1() {
  Draw_Control_Menu();
}
void Goto_Test2() {
  Draw_TestMenu2();
}
void ResetPrinter() {
  gcode.process_subcommands_now_P(PSTR("M997"));
}
void Back_Test2() {
  Draw_TestMenu();
}

MenuClass *TestMenu = nullptr;
void Draw_TestMenu() {
  if (TestMenu == nullptr) TestMenu = new MenuClass("Prueba");
  if (CurrentMenu != TestMenu) {
    DWINUI::MenuItemsPrepare(7);
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_Back, GET_TEXT(MSG_BUTTON_BACK), onDrawMenuItem, Back_Test1));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffY, "Reset Printer", onDrawMenuItem, ResetPrinter));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffY, "Dummy1", onDrawMenuItem, nullptr));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffY, "Dummy2", onDrawMenuItem, nullptr));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffY, "Dummy3", onDrawMenuItem, nullptr));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffZ, "Dummy4", onDrawMenuItem, nullptr));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffX, "Goto Test2", onDrawSubMenu, Goto_Test2));
  }
  CurrentMenu = TestMenu;
  TestMenu->Draw();
}

MenuClass *TestMenu2 = nullptr;
void Draw_TestMenu2() {
  if (TestMenu2 == nullptr) TestMenu2 = new MenuClass("Prueba 2");
  if (CurrentMenu != TestMenu2) {
    DWINUI::MenuItemsPrepare(4);
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_Back, GET_TEXT(MSG_BUTTON_BACK), onDrawMenuItem, Back_Test2));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffX, "Goto Advset menu", onDrawMenuItem, Back_Test1));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffY, "Dummy5", onDrawMenuItem, nullptr));
    DWINUI::MenuItemsAdd(new MenuItemClass(ICON_HomeOffY, "Dummy6", onDrawMenuItem, nullptr));
  }
  CurrentMenu = TestMenu2;
  TestMenu2->Draw();
}

void HMI_Menu() {
  ENCODER_DiffState encoder_diffState = get_encoder_state();
  if (encoder_diffState == ENCODER_DIFF_NO) return;
  if (encoder_diffState == ENCODER_DIFF_ENTER) {
    if (CurrentMenu != nullptr) CurrentMenu->onClick();
  } else if (CurrentMenu != nullptr) CurrentMenu->onScroll(encoder_diffState == ENCODER_DIFF_CW);
}
```

The menu scrolling and item redrawing are automatic. Now is too easy add menus and menu elements and we only need to concentrate on functionality and not in the drawing. The menu items are only valid while the menu is on the screen and they are discarded when there is a menu change, this is done to have the lower impact on memory as possible.

**Comment by thinkyhead** [comment]
One of the other reasons that I picked all-static `class` for making singletons was for the syntactic sugar — namely the ability to call its methods using dot-notation instead of double-colon.

e.g., `endstops.report_states()` instead of `Endstops::report_states()`.

I know it's a minor thing, and not widely customary, but I was concerned that the code would descend into chains of namespaces, as in `HAL::Driver::SPI::init()`, and lose its "informal" flavor.

**Comment by thinkyhead** [comment]
Note that except for special cases, we have also assiduously avoided the use of `new`, `malloc`, or any other code that allocates objects at runtime in the heap. It would be a break with longstanding custom to start using the heap in Marlin, inviting memory fragmentation, and limiting its deployment on AVR boards.

**Comment by thinkyhead** [comment]
…That said, I have been a defender of `malloc` / `new` in the past (for `SDCARD_SORT_ALPHA`), my justification being that I could "guarantee" that all things allocated would definitely be freed as soon as they were done being used, and that no allocation or freeing of memory would occur during an active print job. Still, at that time I was met with some pretty strong resistance, so I made it an optional behavior, using static or stack-based buffers by default.

**Comment by mriscoc** [comment]
> > … `SCROLL_LONG_FILENAMES` …
> 
> Hmm, actually I didn't check whether that was enabled. I'll make sure it's turned on in the examples, and in my test configs!

I updated the config files that I use to do the test. Them have enabled the features I use.

**Comment by mriscoc** [comment]
I think that is a good idea to leave libraries as namespaces because then are easily extensible and they are static by nature. Of course, is a bad thing to get a very nested library as `HAL::Driver::SPI::init()`.
I was thinking about of the use of `new` but I think that, in this case, justify his use, because that allows the use of memory efficient code, anyway, I changed the menu items creation to a macro in advance for any change on the future.

Maybe this PR could be merged as a DWINUI and not as Creality. The original Creality code was a headache to extend.

**Comment by thinkyhead** [comment]
> Maybe this PR could be merged as a DWINUI and not as Creality. The original Creality code was a headache to extend.

Well, this would be replacing Creality altogether in the final summation. So, at first there would be this, plus JyersUI, plus MarlinUI. And then, after this and JyersUI are merged, there will only be so-called "CrealityUI" following their original general style, and "MarlinUI" which acts like the DOGLCD / HD44780.

At the moment I'm only keeping these three UI styles separate so that they can be developed and tested within their own idioms. I don't think Jyers will be doing any more revisions on #22422, so really this PR and that one could be brought together into a complete hybrid at any time.

**Comment by mriscoc** [comment]
@thinkyhead, the dwin.cpp implements a menu to do a bed tramming without has a probe, that menu uses labels from the ASSISTED_TRAMMING section of the Configuration_adv.h file, then in the manual mesh version of my configuration files, I enable ASSISTED_TRAMMING to be able to get those labels. I need to disable G35 because that gcode uses a probe, that is the reason why I put the "&&  HAS_BED_PROBE" to the gcode G35. Your removing of that requirement in your commit:  https://github.com/MarlinFirmware/Marlin/pull/21942/commits/f69fddbc78da9ec340a2cb53d3237cc7af6a23c0 cause an error when I compile the firmware without probe and ASSISTED_TRAMMING enabled.

**Comment by thinkyhead** [comment]
Please refrain from adding more commits until I have finished the merge. This is a very meticulous task which I've been engaged in for 3 hours already, and it may a few more hours. Once I have it finished, I will be reverting back to 
728f145 and redoing the merge so that it will be cleaner.

**Comment by mriscoc** [comment]
> Please refrain from adding more commits until I have finished the merge. This is a very meticulous task which I've been engaged in for 3 hours already, and it may a few more hours. Once I have it finished, I will be reverting back to
> [728f145](https://github.com/MarlinFirmware/Marlin/commit/728f14574e637324d7023484935a5216d0f0aeb2) and redoing the merge so that it will be cleaner.

Ok, sorry. Tell me if I can help in something.

**Comment by thinkyhead** [comment]
I note a minor problem with this construction…
```cpp
void Draw_Move_Menu() {
  checkkey = Menu;
  if (MoveMenu == nullptr) {
    MoveMenu = HMI_IsChinese() ? new MenuClass(1, 192, 1, 233, 14) : new MenuClass(GET_TEXT(MSG_MOVE_AXIS));
  }
```
The user can change the language on the fly. So whenever the language changes, all menu globals that are not equal to `nullptr` need to have `delete` called on them, and then they need to be set to `nullptr`, otherwise the language won't change, and/or the objects will leak.

**Comment by mriscoc** [comment]
> I note a minor problem with this construction…
> 
> ```c++
> void Draw_Move_Menu() {
>   checkkey = Menu;
>   if (MoveMenu == nullptr) {
>     MoveMenu = HMI_IsChinese() ? new MenuClass(1, 192, 1, 233, 14) : new MenuClass(GET_TEXT(MSG_MOVE_AXIS));
>   }
> ```
> 
> The user can change the language on the fly. So whenever the language changes, all menu globals that are not equal to `nullptr` need to have `delete` called on them, and then they need to be set to `nullptr`, otherwise the language won't change, and/or the objects will leak.

See the implementation of SetLanguage
```c++
void SetLanguage() {
  HMI_ToggleLanguage();
  CurrentMenu = nullptr;  // Invalidate menu to full redraw
  Draw_Prepare_Menu();
}
```

**Comment by mriscoc** [comment]
Hi, I have some fixes, can I continue with the commits?

**Comment by thinkyhead** [comment]
> `CurrentMenu = nullptr`

That won't do it. As pointed out, ~~every~~ most `MenuClass` instances are being created only once, with whatever language happens to be set at the time the menu is first displayed.

> Hi, I have some fixes, can I continue with the commits?

Not at the moment. I'm just now patching all the menu titles so they use the correct image coordinates for the unified `DWIN_SET`, and adding "TODO" comments to the titles that don't yet exist.

**Comment by thinkyhead** [comment]
Ok, I'm done messing about. Hopefully the changes don't generate too many merge conflicts for you.

**Comment by mriscoc** [comment]
> I note a minor problem with this construction…
> 
> ```c++
> void Draw_Move_Menu() {
>   checkkey = Menu;
>   if (MoveMenu == nullptr) {
>     MoveMenu = HMI_IsChinese() ? new MenuClass(1, 192, 1, 233, 14) : new MenuClass(GET_TEXT(MSG_MOVE_AXIS));
>   }
> ```
> 
> The user can change the language on the fly. So whenever the language changes, all menu globals that are not equal to `nullptr` need to have `delete` called on them, and then they need to be set to `nullptr`, otherwise the language won't change, and/or the objects will leak.

You are right, I had other implementation for the titles, it will be there on the next commit.

**Comment by mriscoc** [comment]
> Ok, I'm done messing about. Hopefully the changes don't generate too many merge conflicts for you.

ok thanks, get down to work ...

**Comment by mriscoc** [comment]
I wanted to update the list of changes but I can't see my commits made before of August 20.

**Comment by thinkyhead** [comment]
This PR has been relocated and rebased a few times since it was first introduced. If you'd like to reorganize commits by theme, you can rework the whole thing by using `git reset --soft`, creating all new commits, and then force-pushing the result with `git push -f`. If it would help, I can rebase this on the latest `bugfix-2.0.x`, naively create a series of commits by theme, and force-push the result as a starting point for your own reorganization.

**Comment by CRCinAU** [comment]
Great work to all involved in this PR :)

**Comment by mriscoc** [comment]
Thank you for all the support!

**Comment by CRCinAU** [comment]
Looks like there may be a bug with this merge:

```
Marlin/src/lcd/e3v2/enhanced/dwin.cpp: In function 'void DWIN_Popup_FilamentPurge()':
Marlin/src/lcd/e3v2/enhanced/dwin.cpp:1920:5: error: 'pause_menu_response' was not declared in this scope
 1920 |     pause_menu_response = PAUSE_RESPONSE_WAIT_FOR;
      |     ^~~~~~~~~~~~~~~~~~~
Marlin/src/lcd/e3v2/enhanced/dwin.cpp:1920:27: error: 'PAUSE_RESPONSE_WAIT_FOR' was not declared in this scope
 1920 |     pause_menu_response = PAUSE_RESPONSE_WAIT_FOR;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~
Marlin/src/lcd/e3v2/enhanced/dwin.cpp: In function 'void HMI_FilamentPurge()':
Marlin/src/lcd/e3v2/enhanced/dwin.cpp:1933:9: error: 'pause_menu_response' was not declared in this scope
 1933 |         pause_menu_response = PAUSE_RESPONSE_EXTRUDE_MORE;  // "Purge More" button
      |         ^~~~~~~~~~~~~~~~~~~
Marlin/src/lcd/e3v2/enhanced/dwin.cpp:1933:31: error: 'PAUSE_RESPONSE_EXTRUDE_MORE' was not declared in this scope
 1933 |         pause_menu_response = PAUSE_RESPONSE_EXTRUDE_MORE;  // "Purge More" button
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Marlin/src/lcd/e3v2/enhanced/dwin.cpp:1936:9: error: 'pause_menu_response' was not declared in this scope
 1936 |         pause_menu_response = PAUSE_RESPONSE_RESUME_PRINT;  // "Continue" button
      |         ^~~~~~~~~~~~~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio/build/STM32F103RET6_creality/src/src/lcd/e3v2/enhanced/dwin.cpp.o] Error 1
```

**Comment by CRCinAU** [comment]
Ok - managed to track this down...

When `NOZZLE_PARK_FEATURE` and `ADVANCED_PAUSE_FEATURE` are enabled, the above compilation error occurs.

**Comment by CRCinAU** [comment]
@ellensp just figured out the problem with this - I guess a patch will be coming soon.

**Comment by electronicm** [comment]
@mriscoc 
Is there any way to display the print status screen by command?

For example, when I print via USB, the default screen is displayed all the time.
At this point, it would be great if I could activate the status screen to see the related infos.

**Comment by mriscoc** [comment]
> @mriscoc
> Is there any way to display the print status screen by command?
> 
> For example, when I print via USB, the default screen is displayed all the time.
> At this point, it would be great if I could activate the status screen to see the related infos.

Please, follow this guide: https://github.com/mriscoc/Marlin_Ender3v2/wiki/Octoprint

**Comment by electronicm** [comment]
> Please follow this guide: https://github.com/mriscoc/Marlin_Ender3v2/wiki/Octoprint

Brilliant!


But now I run into the next problem.
`LCD_SET_PROGRESS_MANUALLY` cannot be set with `DWIN_CREALITY_LCD_ENHANCED` and `M73` is not available.

In reverse order:

- `Marlin\Configuration_adv.h` line 1284-1302
```
#if HAS_DISPLAY
[...]
 #define LCD_SET_PROGRESS_MANUALLY
```

- `Marlin\src\inc\Conditionals_LCD.h` line 517-519
```
#if ANY(HAS_WIRED_LCD, EXTENSIBLE_UI, DWIN_CREALITY_LCD_JYERSUI)
  #define HAS_DISPLAY 1
#endif
```

So I need to add the following to `Configuration_adv.h` to make `M73` work:
```
#if ENABLED(DWIN_CREALITY_LCD_ENHANCED)
  // Display XY with one decimal place on the info screen, if possible
  #define LCD_DECIMAL_SMALL_XY

  // Add an 'M73' G-code to set the current percentage
  #define LCD_SET_PROGRESS_MANUALLY
#endif
```

BTW: 
- `LCD_DECIMAL_SMALL_XY` should be enforced by sanity check to match configuration and functionality.
- Longer status texts are not scrolled and `STATUS_MESSAGE_SCROLLING` leads to the following errors during compilation:
```
Marlinsrc\lcd\marlinui.cpp:1501:34: error: 'utf8_strlen' was not declared in this section
 1501 | if (status_scroll_offset < utf8_strlen(status_message))
      | ^~~~~~~~~~~
Marlinsrclcdmarlinui.cpp: In static member function 'static char* MarlinUI::status_and_len(uint8_t&)':
Marlinsrclcd\marlinui.cpp:1509:13: error: 'utf8_strlen' was not declared in this scope
 1509 | len = utf8_strlen(out);
      | ^~~~~~~~~~~
*** [.pio\build\STM32F103RET6_creality\src\src\lcd\marlinui.cpp.o] error 1
```

**Comment by mriscoc** [comment]
> > Please follow this guide: https://github.com/mriscoc/Marlin_Ender3v2/wiki/Octoprint
> 
> Brilliant!
> 
> But now I run into the next problem.
> `LCD_SET_PROGRESS_MANUALLY` cannot be set with `DWIN_CREALITY_LCD_ENHANCED` and `M73` is not available.
> 
I have some configuration files that you can use as examples here: 
https://github.com/mriscoc/Marlin_Ender3v2/tree/Ender3v2-Released/configurations
https://github.com/mriscoc/Marlin_Ender3v2/releases/latest

**Pull request merged**
