### PR TITLE
[bugfix-2.0.x] Fix minor compilation errors in specific configurations

### PR DESCRIPTION
**Pull request by marciot**
Two minor compilation errors that crop up in very specific configurations (and probably don't affect anyone other than me!)

- Fix compilation error when using Makefile by adding guard for STM32F1 code
- Fix compilation error when compiling touch UI for bio printer.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I needed to add a newline to the end of `MarlinSerial.cpp`, but as this was not editable I did the edits in Sublime Text, committed and rebased from the Terminal, merged the changes directly to bugfix, and wrote this informative note.

**Comment by marciot** [comment]
@thinkyhead: Why was it not editable? I didn't do anything different from what I normally do.

**Comment by thinkyhead** [comment]
For some reason none of your recent PRs have been editable. 🤷‍♂️

**Comment by marciot** [comment]
@thinkyhead: Okay. Thanks for the heads up. I'll see if I can find out what's up. That was not intentional.

**Comment by thisiskeithb** [comment]
@marciot Just make sure the box at the bottom of your description is checked when you create a PR:
image

**Comment by marciot** [comment]
@thisiskeithb: But I’ve been doing it for years without having to change anything. Maybe the default changed?

**Comment by thinkyhead** [comment]
I'd say clear your cookies, but that's a hassle. Assume it's just a glitch in the matrix.

**Comment by marciot** [comment]
@thinkyhead: Ha, ha. This whole year has been a glitch in the Matrix. I think the Matrix needs to be rebooted.

**Pull request closed without merging**
