### PR TITLE
Add more DWIN Commands and expand documentation

### PR DESCRIPTION
**Pull request by enigmaquip**
### Description

Adds the draw point command and the start of the icon animation command, example in action on youtube video
Also added some more documentation to current commands

https://youtu.be/v2A6AQwtO6o

### Benefits

Increases the dwin command set available to us for use with Marlin

### Configurations

[dwin.zip](https://github.com/MarlinFirmware/Marlin/files/5220879/dwin.zip)
Contains 4.ICO if you would like to test the animation fuction, this will need to be flashed to the DWIN using the onboard SD slot, includes images 0-13 for the animation. 
Example used in video
`DWIN_ICON_Animation(1, true, 4, 0, 13, 145, 246, 10);`

### CODE REVIEW

**Comment by enigmaquip** [comment]
DWIN_Draw_IntValue, DWIN_Draw_FloatValue, DWIN_Draw_Signed_Float could all be simplified down to a single function it seems like, dwin documentation calls the function 'Data Variables' and allows you to set a flag signifying signed/unsigned, you can see int/float functions are sending the same command to the dwin

**Comment by rhapsodyv** [comment]
Where do we can find the command documentation?

**Comment by enigmaquip** [comment]
We should be able to add our own icon set to the DWIN without requiring the user to take apart the screen and flash it manually based on the memory functions.
We also should be able to do this while still leaving the Creality Set intact.
16 x 32 KB pages
Boot on pg 0, English on pg 1, Japanese on pg 2
The creality icon set starts on pg 9, but since icon sets can span multiple pages it fills up til pg 15
This leaves us pg 3-8 to add another icon set

**Comment by enigmaquip** [comment]
> Where do we can find the command documentation?

Search for T5UIC1 Kernel Application Guide

The dwin site has an older version of the guide (v1.2)
http://dwin.com.cn/service/en/file/id/13

attached here 
[T5UIC1 Kernel Application Guide.pdf](https://github.com/MarlinFirmware/Marlin/files/5221142/T5UIC1.Kernel.Application.Guide.pdf)

I found a v2.0 guide only in Chinese 
attached here 
[要实现的功能和开发指南.pdf](https://github.com/MarlinFirmware/Marlin/files/5221165/default.pdf)

that I've been using google translate on to add these functions
https://translate.google.com/translate?hl=en&sl=zh-CN&u=http://project.21ic.com/project/downloadAttachment%3Fattach_id%3D2274&prev=search&pto=aue

**Pull request merged**
