### PR TITLE
[Bugfix-1.1.x] missing quotation marks

### PR DESCRIPTION
**Pull request by Ludy87**

### CODE REVIEW

**Comment by boelle** [comment]
you should send pr to Bugfix-2.0.x

this is where things happen these days

**Comment by Ludy87** [comment]
@boelle das würde keinen Sinn machen, der Fehler ist in der bugfix-1.1.x

**Comment by boelle** [comment]
Nein, du hast recht

Viele Leute vergessen einfach, dass Bugfix-2.0.x sowohl 8-Bit als auch 32-Bit ist

**Comment by thinkyhead** [comment]
@boelle — It is better if you write no comments rather than incorrect comments on PRs.

**Comment by boelle** [comment]
i see nothing wrong, but then again you could have told me on discord and i could have removed the comments

**Comment by Ludy87** [comment]
It's all right.😊 Everyone can make a mistake.

**Pull request merged**
