### PR TITLE
fix AVR PWM, follow up to 25005

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Issue https://github.com/MarlinFirmware/Marlin/issues/25018 reported that simple PWM of LEDS was no longer working on AVR  (only full on works, or its off) 

Git bisect shows it stopped working with https://github.com/MarlinFirmware/Marlin/commit/e3e07354d5ff98293f87d532fdd1c384d8e0b2e2

Current code only works is you have FAST_PWM_FAN enabled.

Corrected a few variable types. It now works as expected with and without FAST_PWM_FAN

### Requirements

An eg only.
Stock config + 
#define RGBW_LED
#define RGB_LED_R_PIN 5
#define RGB_LED_G_PIN 4
#define RGB_LED_B_PIN 6
#define RGB_LED_W_PIN 44

### Benefits

M150 PWM of these LED pins work again
M106 with and without FAST_PWM_FAN and FAST_PWM_FAN_FREQUENCY 122 works as expected

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/25018
https://github.com/MarlinFirmware/Marlin/pull/25005

### CODE REVIEW

**Comment by ellensp** [comment]
this breaks https://github.com/MarlinFirmware/Marlin/pull/25005 again

**Comment by ellensp** [comment]
Tested fan control (M106) and pwm led control (M150), with and without FAST_PWM_FAN
Now works as expected

**Comment by dot-bob** [comment]
I can confirm this fixes the regression that breaks PWM on the AVR HAL.  I have verified the fix on my ULTIMAIN_2 and RUMBA platforms.

The issue was caused by commit e3e07354d5ff98293f87d532fdd1c384d8e0b2e2 #25005

**Comment by ellensp** [comment]
@thinkyhead please merge, PWM is broken on all AVR devices at present.

**Comment by marciot** [comment]
@ellensp: We seem to be butting heads with each other. I am maintaining some firmware for LulzBot printers and it had noticed that PWM fan control had stopped working on those particular builds. I traced it down to a series of changes that happened around January 10th last year. I found that restoring the code to what it was prior fixed the problem. The entire process is documented here:

https://github.com/MarlinFirmware/Marlin/pull/25005

However, this PR effectively reintroduces code which I know was problematic. I do not know exactly what is happening, but I thought I would bring the problem to your attention as the only way to really make progress with this is to find some code that works for both of us.

**Comment by marciot** [comment]
@ellensp: So it seems like the new code does in fact generate a PWM signal, which is good, but it does seem to generate a different waveform than the original waveform which was known to be good on the fans used by LulzBot printers.

This is what it looks like prior to this PR:

IMG_2173

While this is what it looks like after this PR:

IMG_2172

So it appears as if the frequency may have increased by quite a bit relative to what it was before.

**Comment by marciot** [comment]
So in my `Configuration_adv.h`, I have the frequency set as follows:

```
#define FAST_PWM_FAN_FREQUENCY 122
```

I'm very much inexperienced in using scopes for actual measurements (I usually only use them to get a rough sense of what signals look like), and I also have no idea whether this vintage scope is accurate, but I believe that it is showing me a 57Hz signal prior to the commit, and a 200Hz signal after.

**Comment by ellensp** [comment]
@marciot Please read and comment. See if you agree with what I see

Confirmed.. freq is not as desired, but is what I expect from reading the code

What I see at present

With FAST_PWM_FAN disabled you get a 1kHz PWM signal as expected
With FAST_PWM_FAN enabled but  FAST_PWM_FAN_FREQUENCY not explicitly set then marlin uses

FAST_PWM_FAN_FREQUENCY =   ((F_CPU) / (2 * 255 * 1)) 
ie 16000000L / 510 =  31372.5  on a 16mhz avr.

This set frequency to 31.25kHz   as expected
 
Now the problematic one

You say you want 122kHz, but from the code point of view you requested 122Hz

Ie With FAST_PWM_FAN enabled and FAST_PWM_FAN_FREQUENCY set to 122 you get 122Hz  as I would expect.


So from my point of view you should be requesting FAST_PWM_FAN_FREQUENCY 122000U
This does not work yet. but this can be worked on.

 Thoughts?

**Comment by marciot** [comment]
@ellensp: You seem to have misunderstood. I want the frequency to be 122Hz, not 122KHz. This decision was done several years ago and I do not recall why FAST_PWM was used to set a super slow frequency, as opposed to its intended use of setting a faster frequency. IIRC, the reason for the change was that certain types of brushless fans were failing with the default frequency of 31.25kHz, as they needed a much slower PWM frequency to operate.

In retrospect, it is possible that the correct solution was to not use FAST_PWM_FAN at all, but instead, I must have set the FAST_PWM_FAN_FREQUENCY to 122 and verified it was giving me an acceptably slow PWM signal. Whether this is a practical necessity or not I do not know, but I do know that between January last year and today, the PWM code was changed quite a bit and it introduced problems. With this PR, it seems like PWM is again operating, but as you can see from the oscilloscope traces, the frequency has changed.

The question is, is this behavior incorrect (i.e. the frequency was incorrect before), or is it intended (the frequency is correct now whereas it was not before).

**Comment by ellensp** [comment]
using current bugfix with this PR applied
when you set FAST_PWM_FAN enabled and FAST_PWM_FAN_FREQUENCY set to 122 you get 122Hz on the fan pin.
Verified on my scope

I'm failing to see the issue
 
Screenshot from 2022-12-12 14-53-41

Results on scope

IMG_20221212_145633

**Comment by ellensp** [comment]
If I use commit 1cd6bf7ef5b5a38a7809dfc5d931e8e003da7d22 ie just prior to this PR being merged
Same Marlin settings
The frequency is wrong at 30.49Hz

Ie


IMG_20221212_151436

**Comment by marciot** [comment]
@ellensp: Nothing necessarily wrong. I just was concerned that there was a significant change in behavior. I trust your measurement is better than mine, and as it is giving a correct reading on your scope, it must have been incorrect before. Let's call this good for now. Thank you for verifying.

**Pull request merged**
