### PR TITLE
Followup to "no status for serial::write"

### PR DESCRIPTION
**Pull request by ellensp**
### Description

#21567 broke meatpack
code now compiles.

### Requirements

MEATPACK_ON_SERIAL_PORT_1
SERIAL_PORT_2  (to expose second bug) 

### Benefits

Compiles as expected

### Related Issues
https://github.com/MarlinFirmware/Marlin/pull/21567

### CODE REVIEW

**Comment by ellensp** [comment]
This has been tested by CRCinAU, But I would really like this to be tested a lot more.
I don't wish to be responsible for another round of broken serial code....

**Comment by ellensp** [comment]
This has been tested by CRCinAU, But I would really like this to be tested a lot more.
I don't wish to be responsible for another round of broken serial code...

**Comment by X-Ryl669** [comment]
I don't think it's the right fix here. There are platform that use `size_t write` and other that only use `void write` so the most common denominator is `size_t write` not `void write`. It's more likely that a `void write` should be changed to a `size_t write` than the other way around.

**Comment by X-Ryl669** [comment]
I don't think it's the right fix here. There are platform that use `size_t write` and other that only use `void write` so the most common denominator is `size_t write` not `void write`. It's more likely that a `void write` should be changed to a `size_t write` than the other way around.

**Comment by ellensp** [comment]
The point of 21567 "serial: remove return value on write()"

**Comment by X-Ryl669** [comment]
If the return value is not used anywhere and it doesn't break any platform, than I'm ok for it.

**Comment by thinkyhead** [comment]
Thanks, as always, for the completionism. If nothing in Marlin cares about a bad write to serial, then it's fine to remove it everywhere. In future it can always be added back if something vitally needs to respond to a bad serial write.

**Pull request merged**
