### PR TITLE
🌐 Update Polish language

### PR DESCRIPTION
**Pull request by blazewicz**
First commit syncs Polish translation file with English one, before that I couldn't really see what was translated and what was not. I also commented out any 1:1 overrides which would potentially block future changes introduced to English translation for users using this translation.

Then I added some new translations in places where I could guess with decent certainty what it should say without further inspecting the context.

I left out remaining untranslated entries in comments for a reference for future contributors.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by thinkyhead** [comment]
I went ahead and rebased this on your behalf. To get the changes in your working copy you can use the Git console:
```
git fetch origin
git checkout update-language-pl
git reset --hard origin/update-language-pl
```

**Comment by blazewicz** [comment]
> Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the bugfix-2.0.x branch and be careful to target bugfix-2.0.x when resubmitting the PR.

My fault, I didn't read the guide and went straight to main branch, sorry!

I've rebased my commits onto `bugfix-2.0.x`. You squashed them together, would you prefer it this way? I made two so refactor and actual language update go separately, but its your call :)

> It may help to set your fork's default branch to bugfix-2.0.x.

I will :)

**Comment by thinkyhead** [comment]
We usually squash PRs down to one commit, and the final result here looks good. Thanks again!

**Pull request merged**
