### PR TITLE
Add Panowin Cutlass / Bardo V1.x Motherboards (Panowin F1 & Kodama Trinus)

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Add Panowin V?.? & Kodama Bardo V1.x motherboard support as found in the Panowin F1 & Kodama Trinus.

Ported from https://github.com/sambuls/MarlinOnTrinus. h/t to @sambuls for tracking down these pins!

| Panowin V?.? | Kodama Bardo V1.x |
| :------------: | :------------------: |
| Panowin V?.?<br/> Source: https://redd.it/jc2s9r | Kodama Bardo V1.x<br /> Source: https://redd.it/12hhy0r |

_**Note: No LCD or SD card support at this time.**_

### Benefits

Panowin F1 & Kodama Trinus printers will be supported.

### Configurations

TBD - I'll port the 1.1.7 config over & submit it to the Configurations repo later.

### Related Issues

None. Fell down a rabbit hole while browsing reddit last night.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Do we know what the LCD, AUX1 and AUX2 pins are? We should define those and then we can also define an EXP1 header based on the most likely mapping for GLCD/12864 displays.

**Comment by thisiskeithb** [comment]
> Do we know what the LCD, AUX1 and AUX2 pins are? We should define those and then we can also define an EXP1 header based on the most likely mapping for GLCD/12864 displays.

No. And from what I’ve found, previous attempts have failed.

I don’t have these boards, so I won’t be able to test them either.

**Comment by thinkyhead** [comment]
Here's the back of the Panowin (K) board. Labeled "Panowin Cutlass V6.1"

Panowin-Back

**Comment by thinkyhead** [comment]
> I don’t have these boards, so I won’t be able to test them either.

I can go ahead and poke at the Cutlass unknown pins with `M43`….

**Comment by ellensp** [comment]
Huh?  there is no exp like ports on these controllers
Lcd port is Serial 4pin (5V, GND, TXD, RXX), for LCD panel   (according to their discription on via way backmachine https://asia.kodama3d.com/collections/add-ons/products/bardo-pcb?variant=31262407196708

**Comment by thisiskeithb** [comment]
> Huh? there is no exp like ports on these controllers

Yeah, it doesn’t make sense to force our EXP PIN numbering scheme here.

**Comment by thisiskeithb** [comment]
> Here's the back of the Panowin (K) board. Labeled "Panowin Cutlass V6.1"

Since you have a board model name, that’d be good to add so it’s not just “Panowin”. I can push a commit once I’m back at a computer.

**Comment by thinkyhead** [comment]
> Huh? there is no exp like ports on these controllers

The general idea is that when someone _really_ wants to connect a simple character or GLCD they only need to find enough GPIO pins to make the MISO/SCK connections, and then the micro-controller can send the necessary data over those pins using good old software SPI. Rather than simply leave the pin determination completely up to the user, we can offer a default suggestion. Although pins TX0/RX0/TX1/RX1/etc. can be used as serial through their associated UARTs, they may also be used for GPIO if desired.

**Comment by thinkyhead** [comment]
I see there are a number of boards which define pins with numbers over 69, and some with pin numbers over 85, but which are not using a variant that defines `NUM_DIGITAL_PINS`, and/or are not included in this block in  `pinsDebug.h`… 

```cpp
#if MB(BQ_ZUM_MEGA_3D, MIGHTYBOARD_REVE, MINIRAMBO, SCOOVO_X9H, TRIGORILLA_14)
  #define AVR_ATmega2560_FAMILY_PLUS_70 1
#endif
```
…and this block in  `pinsDebug_plus_70.h` … 
```cpp
#if MB(BQ_ZUM_MEGA_3D, MINIRAMBO, SCOOVO_X9H, TRIGORILLA_14)
  #undef NUM_DIGITAL_PINS
  #define NUM_DIGITAL_PINS            85
#elif MB(MIGHTYBOARD_REVE)
  #undef NUM_DIGITAL_PINS
  #define NUM_DIGITAL_PINS            80
#endif
```
So, we should have a look at that and ensure that all the boards with extended pins are fixed. This will ensure the proper functioning of `M42` and `M43` for these boards. It may be enough to change some `env:mega2560` in `pins.h` to `env:mega2560ext` but some of the boards with extra pins are `env:rambo`.

**Comment by ellensp** [comment]
Platformio has a board reprap_rambo  https://docs.platformio.org/en/latest/boards/atmelavr/reprap_rambo.html 
Thus rambo env uses it.

**Comment by thinkyhead** [comment]
> Thus rambo env uses it.

- What value does it give to `NUM_DIGITAL_PINS`?
- Do all RAMBo boards defined by that package have 70 GPIO pins, or can it define more?
- Is there a compiler `-D` flag that we can set to tell `reprap_rambo` that pins are extended?
- Is our special handling of `MINIRAMBO` and `SCOOVO_X9H` (rambo boards) still needed in `pinsDebug*.h`?
- Do any more of our boards currently using `env:mega2560` need to be changed to `env:mega2560ext`?
- Are our current workarounds needed due to limitations of Arduino IDE?

**Pull request merged**
