### PR TITLE
Disable STM32 Servo output while updating NeoPixels

### LINKED ISSUE #19887: BLTouch unreliable when used with NeoPixels (BTT GTR 1.0)
### Bug Description

BLTouch does not deploy when starting to print. 

### My Configurations

Board is BTT GTR 1.0, Marlin 2.0.7.2, BLTouch 3.1.
BLTouch was connected to the BLTouch port on the board.

### Steps to Reproduce

1. Start printing by heating bed and nozzles with commands M109 and/or M190. 
2. Head moves to Z-homing position.
3. BLtouch does not deploy and head crashes to the bed.

**Expected behavior:** [What you expect to happen]

1. Start printing by heating bed and nozzles with commands M109 and/or M190. 
2. Head moves to Z-homing position.
3. BLtouch deploys and printing starts.

**Actual behavior:** [What actually happens]

1. Start printing by heating bed and nozzles with commands M109 and/or M190. 
2. Head moves to Z-homing position.
3. BLtouch does not deploy and head crashes to the bed.

#### Additional Information

PWM signal goes high level and stays there for the BLtouch right away when I send heating command (M109 or M190) and after that BLtouch does not deploy for Z-homing. It happens only when bed or head is heating up alone or together. It does not happen when they are cooling down.
 Commands M104 or M140 does not have this problem and Z-homing (G28) alone works fine.

For preventing a head to crash to the bed every time when this happens, I modified the "deploy_proc(){" code to brake if PWM pin stays high level by adding "|| extDigitalRead(SERVO0_PIN) == 1) {"  to both " if (_deploy_query_alarm(){" statements.

================================================
bool BLTouch::deploy_proc() {
  // Do a DEPLOY
  if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("BLTouch DEPLOY requested");

  // Attempt to DEPLOY, wait for DEPLOY_DELAY or ALARM
  **if (_deploy_query_alarm() || extDigitalRead(SERVO0_PIN) == 1) {**
    // The deploy might have failed or the probe is already triggered (nozzle too low?)
    if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("BLTouch ALARM or TRIGGER after DEPLOY, recovering");

    clear();                               // Get the probe into start condition

    // Last attempt to DEPLOY
   **if (_deploy_query_alarm() || extDigitalRead(SERVO0_PIN) == 1) {**

      // The deploy might have failed or the probe is actually triggered (nozzle too low?) again
      if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("BLTouch Recovery Failed");

      SERIAL_ERROR_MSG(STR_STOP_BLTOUCH);  // Tell the user something is wrong, needs action
      stop();                              // but it's not too bad, no need to kill, allow restart

      return true;                         // Tell our caller we goofed in case he cares to know
    }
 }

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5434006/Configuration_adv.zip)

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

When updating NeoPixels from an STM32 device, interrupts may be disabled long enough to interfere with proper Servo PWM operation. When this occurs the PWM signal never returns when interrupts are re-enabled, causing BLTouch failure and bed crashes.

This mirrors the change which was used when writing to flash in the STM32 HAL, which caused the same BLTouch issues.

In the referenced bug report, the user's 96 pixels require 3.84 milliseconds to update.

### Benefits

Prevents complete Servo output failure on STM32 boards due to slow NeoPixel updates.
In the configuration attached below, the board has 96 pixels requiring 3.84 milliseconds to update.

### Configurations

[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5468158/Configuration_adv.zip)

### Related Issues

#19887

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I don't completely love this solution, but it seems less bad than leaving it how it is. This is an extremely long strand of NeoPixels, but even a much smaller one could have probably caused the BLTouch failures reported in the referenced bug report.

@muistiloppu, would you mind re-testing with my final modifications, to make sure it still works for you?

**Comment by sjasonsmith** [comment]
I changed this to a draft. @rhapsodyv and I have been talking about a different way to solve this that deserves some experiments.

Allowing NeoPixels to disable interrupts this long contributes to many issues. As an example, you could lose over 40 bytes of serial data at 115200, unless the framework is using DMA for serial data.

**Comment by muistiloppu** [comment]
I got now some time to test this BUG19887 version and looks like it is working fine. It has that 24 ms high pulse and low level gaps some times, but no any failures.
  I think to use DMA is good idea. Marlin code is starting to have lot of real time tasks and to get all tasks to work in timely manner is going to be big challenge.

**Comment by sjasonsmith** [comment]
Early experiments show the other idea just might work. I’ll leave this open for now, but it will most likely be discarded once I have something better.

**Comment by sjasonsmith** [comment]
@thinkyhead my initial alternative solution didn't work, so it might be worth putting this in as a stop-gap.

I'm still pursuing some more complete solutions that involve using STM32 DMA and a timer for NeoPixel control, but it will take some time to figure out.

**Comment by muistiloppu** [comment]
This latest fix has been now working well without any BLTouch failures.

**Comment by xC0000005** [comment]
> @thinkyhead my initial alternative solution didn't work, so it might be worth putting this in as a stop-gap.
> 
> I'm still pursuing some more complete solutions that involve using STM32 DMA and a timer for NeoPixel control, but it will take some time to figure out.

I had a draft PR in the arduino core that I never asked to be merged that was for doing exactly this. It made no sense for sketches to be registering hard function references for DMA handlers, I thought. The DMA solution was relatively functional on F1 and F4 but I couldn't get it to work on the F0 boards (Malyan M200, no surprise).  I'll be interested to see what you come up with.

**Comment by sjasonsmith** [comment]
I'm not really comfortable merging this one without @thinkyhead approving of the general approach.

**Pull request merged**
