### PR TITLE
HAL compatible pinsDebug 

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
Re-ARM code has been tested.  

AVR code has been tested in bugfix_1.1.x but not yet in bugfix_2.0.x.

Sanitycheck changes will be added tomorrow.

----

1) moved all cpu specific items to files in the low level HAL directory for that CPU (pinDebug_Re-ARM.h & pinsDebug_AVR_8_bit.h)

2) added pinsDebug.h to the top level directory

3) modified HAL_pinsDebug.h to select the correct support file for the selected CPU

4) Patched sanitycheck to stop throwing false errors.  A long term solution will need to be found.

5) misc changes & bug fixes
updated pinsDebug_list.h
arduino.cpp - included macros.h to fix a missing definition
pinmap_re-arm.h - removed a duplicated line.
pinmapping.h - changed from "ENABLED" to "defined" to fix a compile error

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
I've just added the code/files to split CPU specific sections of SanityCheck off to the four HAL directories.

Added a PWM capable check to the Re-ARM pin map.

Also removed the need for two INCLUDEs in pinsDebug.h.

----

I'll wait until Chris & Scott say it's OK before merging this PR.

**Comment by Bob-the-Kuhn** [comment]
Just updated the pins_RAMPS_RE_ARM.h file with all the PR #7381 changes.

I was concerned that we'd end up switching to a older version of this file, depending on which PR gets merged first.

**Comment by Bob-the-Kuhn** [comment]
These changes have been merged in under PR #7401.

**Comment by Roxy-3D** [comment]
> These changes have been merged in under PR #7401.

Should we close this one?

**Pull request closed without merging**
