### PR TITLE
Fix MKS Gen L V1.0 MOSFET & FAN Pinmap (Artillery)

### PR DESCRIPTION
**Pull request by Nomis-97**
Correction of the MOSFET control pins
Heating Hotend, Hotbed working again

### Description

Previous pinmap:

* MOSFET_A_PIN = H6 (signal HEATER_FAN)
* MOSFET_B_PIN = H5 (signal HEATER_BED)
* MOSFET_C_PIN = B4 (signal HEATER_E0)
* FAN0_PIN = H4 (signal HEATER_E1) 

New pinmap:

* MOSFET_A_PIN = B4 (signal HEATER_E0)
* MOSFET_B_PIN = H4 (signal HEATER_E1)
* MOSFET_C_PIN = H5 (signal HEATER_BED)
* FAN0_PIN = H6 (signal HEATER_FAN) 

=> correct according to Schematic

### Requirements

MKS Gen L V1.0

### Benefits

Correction of the MOSFET control pins
Heating Hotend, Hotbed working again

### Related Issues

- https://github.com/MarlinFirmware/Marlin/issues/23478

Agreement with: quiret

### CODE REVIEW

**Comment by ellensp** [comment]
### Related https://github.com/MarlinFirmware/Marlin/pull/25567

**Comment by quiret** [comment]
Thank you @Nomis-97 for helping in the clean-up of pin definitions. Consolidation work is good. You told me that the changes have been tested and work fine on the mentioned HW. I hope that more work will be done by matching the pin definitions to the schematics.

**Comment by thinkyhead** [comment]
Thanks! We want to ensure that the best choice MOSFET pins are assigned for different "layouts" — situations with differing combinations of Bed, Hotend (Extruder), Fan… – which have historically been built around the RAMPS mapping. Hopefully this resolves that particular problem for MKS Gen-L.

**Comment by thisiskeithb** [comment]
MKS' Gen-L schematic is incorrect. I traced the pins to the MCU and the pins diagram is correct: https://github.com/MarlinFirmware/Marlin/issues/26971#issuecomment-2058180909

**Pull request merged**
