### PR TITLE
Fix for serials available on SKR-Pro 1.1

### PR DESCRIPTION
**Pull request by LinoBarreca**
### Description

Fixes serials available on SKR-Pro

### Benefits

Fixes 16376

### Related Issues
#16376

### CODE REVIEW

**Comment by LinoBarreca** [comment]
@thinkyhead please merge this so @boelle can close #16376 
I also added a comment to discourage user changing things they don't really understand (as they did in #16300 and #16158 )

**Comment by LinoBarreca** [comment]
@boelle do you know why they switched from travis to github checks? here we have lots of transient errors that halt the build although there's nothing wrong....and we can't ask to "redo" the build manually (on Travis we can)

**Comment by boelle** [comment]
nope that would be @thinkyhead 's department

**Comment by thinkyhead** [comment]
> do you know why they switched from travis to github checks?

Improved speed, simplicity, and convenience. Hopefully there will be fewer transient errors as they work out the kinks in the workflow system.

**Comment by LinoBarreca** [comment]
> 
> 
> > do you know why they switched from travis to github checks?
> 
> Improved speed, simplicity, and convenience. Hopefully there will be fewer transient errors as they work out the kinks in the workflow system.

actually it seems there's something wrong with their system and the 407ve_black.
ffe1597 passed c3f9c96 failed... after a few minutes...now it keeps failing both here and for @InsanityAutomation 's PR

**Comment by thinkyhead** [comment]
> actually it seems there's something wrong with their system and the 407ve_black.

The specific problem is that the new `framework-arduinoststm32` version `4.10700.200103` is incompatible with this line in `buildroot/share/PlatformIO/boards/blackSTM32F407VET6.json`:
```
"ldscript": "stm32f407xe.ld",
```
For now I've just forced the environment to use the previous version of the framework until we sort out the necessary changes for `4.10700.200103`.

**Comment by tpruvot** [comment]
<4.10700.200103 so maybe ?

**Comment by thinkyhead** [comment]
I'm wondering if just using the comparison "<4" would work. I assume the dots always indicate the next minor part.

**Comment by tpruvot** [comment]
yea or that... but if its only the latest which breaks... unsure what was the previous... ststm32 v6.0 was released a week ago if i remember right... and was ok

**Comment by LinoBarreca** [comment]
5.7.0 was working before. I adapted it myself

**Comment by LinoBarreca** [comment]
But today I did a few build with 6.0.0 and it worked (look at the details of the green checkmark above)

**Comment by tpruvot** [comment]
yes, framework-arduinoststm32 is one of the sub frameworks of ststm32... older chips like the F1 use another one. I guess they didnt force a specific version in the main framework release

**Pull request merged**
