### PR TITLE
TMC SPI daisy chain support (experimental)

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
This PR adds SPI daisy chain support for the TMC devices.

This PR is the compaion to the TMC library [PR #66](https://github.com/teemuatlut/TMCStepper/pull/66).

The daisy chain routines are based on the L6470 daisy chain routines.

There are only a couple of Marlin changes needed to support TMC SPI daisy chain:
- **Configuration_adv.h** - add daisy chain specific defines
- **stepper_indirection.cpp** - add daisy chain definition section

The code changes have been tested on a modified RAMPS-FD V2 using TMC2130 and TMC5160 drivers in one and four driver chains. Only the soft SPI mode was tested.

---

**TO DO**

- Wait for TMC library [PR #66](https://github.com/teemuatlut/TMCStepper/pull/66) to be merged and then modify this PR as needed.
- Look at the use of macros to simplify the **stepper_indirection.cpp** changes.  The first parameter in the `set_chain_info(1, X_CHAIN_POS)` is an arbitrary 8 bit number that is unique to each driver/axis. Using something like an enum may be the way to go.
- Look at adding a TMC_CHAIN_CS define so that the rule of using just a single chip select is automatically enforced.  This would require a change to TMC library [PR #66](https://github.com/teemuatlut/TMCStepper/pull/66).

### CODE REVIEW

**Comment by GMagician** [comment]
sorry for this OT.
I know you are waiting for a ruramps as I do (no answer from vendor so I've open a complaint with paypal). Since I think I'll never get it I'm looking for a replacement for my grand central M4. Ramps FD should be compatible but V2 is almost impossible to find (maybe project has not been terminated yet). Where did you get yours?

**Comment by thinkyhead** [comment]
Very nice. We will have to do a page on the Marlin website on all the fun and interesting ways to set up TMC drivers. Or, at least link to some helpful videos….

**Comment by thinkyhead** [comment]
Can some steppers be included in the chain, while others are not included? (It looks like the code is set up to do all-or-nothing at the moment.)

**Comment by Bob-the-Kuhn** [comment]
All the SPI steppers are assumed to be in the daisy chain.  Non SPI steppers are not affected.

**Comment by Bob-the-Kuhn** [comment]
@gmagician - I did the same thing with PayPal.

There is some hope on the RuRamps.  The order page for the more expensive version went from "Available for pre-order" to "Available on backorder" in the last 1-2 weeks so there is some life.

I got my FD V2.1 units from taobao.com.  Specifically from 'yu yongfeng' <sylyyf2009@hotmail.com>

Dealing with taobao.com is a **REAL PAIN**.  If you know someone who can opperate in "simplified Chinese" then go through that person.
- The site is setup for the Chinese market.  Google Chrome and Microsoft edge only translate part of the web pages.  I switch back & forth between the two as some pages work better in one than the other.  I also often copy the Chinese characters and paste them into a translation website.  I also often have to guess and click on a label and see what happens.
- Shipping out of China requires paying for the goods and then later paying for an expediter/shipper.  
- My last order (April) ran into a site/system setup issue.  The site said that the FD V2.1 couldn't ship to the USA but directly contacting the vendor resulted in a work around.  Since you are in Italy you may not have this issue.
- The nice thing about taobao.com is when you click on "contact vendor" you are immediately put into a chat with the vendor.  No middle men or email delays.

Sorry I can't provide a direct link to the product page.  Taobao.com has changed the login process and I can't get into it anymore.

**Comment by GMagician** [comment]
@Bob-the-Kuhn

> went from "Available for pre-order" to "Available on backorder"

on july it was already in backorder. My problem is lack of communication. I sent various mails about send date or probable send date, no answer at all.
I opened a complaint with paypal (20 days with no answer)
I opened a claim and 2nd september is last valid date. No answer at the moment so I think I'll be refunded by paypal.

My big problem is lack of valid shield for due/AGCM4. Let a ramp run is a panic, ramps fd is dangerous. I find myself with a powerful board with no wheels

**Comment by Bob-the-Kuhn** [comment]
I had the same experience with RuRamps.  July - I'll believe that.  I was struggling to remember when I noticed the change.

I share your sentiment about a good shield for the DUE.  I had resisted ordering the RuRamps for a long time because I didn't like the idea of paying 2X-3X for the shield as for the CPU board.

I also tried the Ramps 1.6+ but the thermal inputs are tied to non-ADC pins.

You can also convert an FD V1 to a V2.  After following the online instructions I also made these mods:
- I found the thermal inputs were off by 5-10mV which is huge on a PT100.  I ended up adding a heavy ground wire to the thermal connector and running wires directly from the thermal connector to the ADC pins on the inter-board connector (which bypasses the 4.7K series resistors but keeps the 4.7K pullups).  
- I'm running a 24V system.  The 12V regulator was overheating so I removed it and connected a cheap 12V DC-DC to the 12V AUX connector and left the JP102 jumper/selector completely open.
- I also connected a 5V DC-DC which meant adding a connector.  I don't remember why.

**Comment by thinkyhead** [comment]
I've reverted the errant commit causing compile errors. There is no need to pile on with attempts to patch outside issues within this PR to get it to pass.

I've also rebased this PR and will be merging it once it passes Travis.

**Comment by Bob-the-Kuhn** [comment]
I've tested this code on a six chain TMC5160 system and everything works.

**Comment by GMagician** [comment]
[OT] @Bob-the-Kuhn about ruramps, I got some news (not really news but they are to me), it seems that last batch of boards sent from producer to Europe have been blocked by custom (I think due to embargo) so I think he can't send anymore (but no exucuse about his silence).
I got these from facebook, MK4due
Today paypal has refounded me.

**Comment by sl1pkn07** [comment]
~~~
+++ b/Marlin/Configuration_adv.h
@@ -1732,7 +1732,7 @@
     #define X_CURRENT     750  // (mA) RMS current. Multiply by 1.414 for peak current.
     #define X_MICROSTEPS   16  // 0..256
     #define X_RSENSE     0.11
-    #define X_CHAIN_POS     0  // 0 - Not chained, 1 - MCU MOSI connected, 2 - next in chain, ...
+    #define X_CHAIN_POS     3  // 0 - Not chained, 1 - MCU MOSI connected, 2 - next in chain, ...
   #endif
 
   #if AXIS_IS_TMC(X2)
@@ -1746,7 +1746,7 @@
     #define Y_CURRENT     800
     #define Y_MICROSTEPS   16
     #define Y_RSENSE     0.11
-    #define Y_CHAIN_POS     0
+    #define Y_CHAIN_POS     2
   #endif
 
   #if AXIS_IS_TMC(Y2)
@@ -1760,7 +1760,7 @@
     #define Z_CURRENT     850
     #define Z_MICROSTEPS   16
     #define Z_RSENSE     0.11
-    #define Z_CHAIN_POS     0
+    #define Z_CHAIN_POS     1
   #endif
 
   #if AXIS_IS_TMC(Z2)
@@ -1781,7 +1781,7 @@
     #define E0_CURRENT    500
     #define E0_MICROSTEPS  16
     #define E0_RSENSE    0.11
-    #define E0_CHAIN_POS    0
+    #define E0_CHAIN_POS    4
   #endif
 
   #if AXIS_IS_TMC(E1)
@@ -1823,14 +1823,14 @@
    * Override default SPI pins for TMC2130, TMC2160, TMC2660, TMC5130 and TMC5160 drivers here.
    * The default pins can be found in your board's pins file.
    */
-  //#define X_CS_PIN          -1
-  //#define Y_CS_PIN          -1
-  //#define Z_CS_PIN          -1
+  #define X_CS_PIN            P1_15
+  #define Y_CS_PIN            P1_15
+  #define Z_CS_PIN            P1_15
   //#define X2_CS_PIN         -1
   //#define Y2_CS_PIN         -1
   //#define Z2_CS_PIN         -1
   //#define Z3_CS_PIN         -1
-  //#define E0_CS_PIN         -1
+  #define E0_CS_PIN           P1_15
   //#define E1_CS_PIN         -1
   //#define E2_CS_PIN         -1
   //#define E3_CS_PIN         -1
@@ -1847,6 +1847,8 @@
   //#define TMC_SW_MISO       -1
   //#define TMC_SW_SCK        -1
 
+  #define TMC_USE_CHAIN     // All active xx_CS_PIN defines must be set the same to use SPI daisy chain
+
   /**
    * Four TMC2209 drivers can use the same HW/SW serial port with hardware configured addresses.
    * Set the address using jumpers on pins MS1 and MS2.
diff --git a/platformio.ini b/platformio.ini
index bb902d9f5..e2ea28a6d 100644
--- a/platformio.ini
+++ b/platformio.ini
@@ -168,7 +168,7 @@ lib_deps          =
   Servo
   LiquidCrystal
   U8glib-HAL=https://github.com/MarlinFirmware/U8glib-HAL/archive/bugfix.zip
-  TMCStepper@<1.0.0
+  TMCStepper=https://github.com/teemuatlut/TMCStepper/archive/master.zip
   Adafruit NeoPixel=https://github.com/p3p/Adafruit_NeoPixel/archive/master.zip
   SailfishLCD=https://github.com/mikeshub/SailfishLCD/archive/master.zip
~~~
=
~~~
└───╼  pio run -j1
Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/master.zip; framework: arduino; board: nxp_lpc1768)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1768.html
PLATFORM: NXP Arduino LPC176x 0.0.2 > NXP LPC1768
HARDWARE: LPC1768 100MHz, 31.80KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES: toolchain-gccarmnoneeabi 1.80201.181221 (8.2.1), framework-arduino-lpc176x 0.1.3
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Found 6 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0
|-- <LiquidCrystal> 1.0.0
|-- <U8glib-HAL> 0.4.1
|-- <TMCStepper> 0.5.0
|-- <Adafruit NeoPixel> 1.2.4
|-- <SailfishLCD>
Compiling .pio/build/LPC1768/src/src/module/stepper/trinamic.cpp.o
In file included from Marlin/src/module/stepper/../../inc/MarlinConfigPre.h:44,
                 from Marlin/src/module/stepper/../../inc/MarlinConfig.h:28,
                 from Marlin/src/module/stepper/trinamic.cpp:28:
Marlin/src/module/stepper/../../inc/Conditionals_adv.h:135: warning: "TMC_USE_CHAIN" redefined
 #define TMC_USE_CHAIN (X_CHAIN_POS||Y_CHAIN_POS||Z_CHAIN_POS||X2_CHAIN_POS||Y2_CHAIN_POS||Z2_CHAIN_POS||Z3_CHAIN_POS||E0_CHAIN_POS||E1_CHAIN_POS||E2_CHAIN_POS||E3_CHAIN_POS||E4_CHAIN_POS||E5_CHAIN_POS)
 
In file included from Marlin/src/module/stepper/../../inc/MarlinConfigPre.h:42,
                 from Marlin/src/module/stepper/../../inc/MarlinConfig.h:28,
                 from Marlin/src/module/stepper/trinamic.cpp:28:
Marlin/src/module/stepper/../../inc/../../Configuration_adv.h:1850: note: this is the location of the previous definition
   #define TMC_USE_CHAIN     // All active xx_CS_PIN defines must be set the same to use SPI daisy chain
 
Marlin/src/module/stepper/trinamic.cpp: In function 'void reset_trinamic_drivers()':
Marlin/src/module/stepper/trinamic.cpp:659:45: error: 'class TMCMarlin<TMC2130Stepper, 'X', '0', (AxisEnum)0>' has no member named 'set_chain_info'
     #define __TMC_CHAIN(Q,V) do{ stepper##Q.set_chain_info(Q,V); }while(0)
                                             ^~~~~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:663:7: note: in expansion of macro '__TMC_CHAIN'
       __TMC_CHAIN(X, 0);
       ^~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:659:45: error: 'class TMCMarlin<TMC2130Stepper, 'Y', '0', (AxisEnum)1>' has no member named 'set_chain_info'
     #define __TMC_CHAIN(Q,V) do{ stepper##Q.set_chain_info(Q,V); }while(0)
                                             ^~~~~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:669:7: note: in expansion of macro '__TMC_CHAIN'
       __TMC_CHAIN(Y, 0);
       ^~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:659:45: error: 'class TMCMarlin<TMC2130Stepper, 'Z', '0', (AxisEnum)2>' has no member named 'set_chain_info'
     #define __TMC_CHAIN(Q,V) do{ stepper##Q.set_chain_info(Q,V); }while(0)
                                             ^~~~~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:675:7: note: in expansion of macro '__TMC_CHAIN'
       __TMC_CHAIN(Z, 0);
       ^~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:659:45: error: 'class TMCMarlin<TMC2130Stepper, 'E', '0', (AxisEnum)3>' has no member named 'set_chain_info'
     #define __TMC_CHAIN(Q,V) do{ stepper##Q.set_chain_info(Q,V); }while(0)
                                             ^~~~~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:684:7: note: in expansion of macro '__TMC_CHAIN'
       __TMC_CHAIN(E0, 0);
       ^~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:659:45: error: 'class TMCMarlin<TMC2130Stepper, 'X', '0', (AxisEnum)0>' has no member named 'set_chain_info'
     #define __TMC_CHAIN(Q,V) do{ stepper##Q.set_chain_info(Q,V); }while(0)
                                             ^~~~~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:660:27: note: in expansion of macro '__TMC_CHAIN'
     #define _TMC_CHAIN(Q) __TMC_CHAIN(Q, Q##_CHAIN_POS)
                           ^~~~~~~~~~~
Marlin/src/module/stepper/trinamic.cpp:703:7: note: in expansion of macro '_TMC_CHAIN'
       _TMC_CHAIN(X);
       ^~~~~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio/build/LPC1768/src/src/module/stepper/trinamic.cpp.o] Error 1
~~~

i'm missing something? i need apply https://github.com/MarlinFirmware/Marlin/pull/15179?

greetings

**Pull request merged**
