### PR TITLE
Refactor auto#.g, add NO_SD_AUTOSTART option

### PR DESCRIPTION
**Pull request by thinkyhead**
**Background:** The auto-start file procedure is failing because it keeps re-starting the file. Changes are needed to prevent this behavior.

**Solution:** Don't call `checkautostart()` from `loop()`. Instead only call the auto-start procedure once at the end of `setup()` and then again only upon completion of an SD file print. The continuation in `M1001.cpp` occurs ahead of other print completion behaviors, which are deferred until after the last auto file.

References: #19296 @Zumili, #20064 @qwewer0

### CODE REVIEW

**Comment by qwewer0** [comment]
Here is what is happens for me with these changes:

- **auto0.g**: Printer starts -> (LCD shows AUTO0.G) auto0.g runs -> Steppers doesn't get disabled -> Print job still active -> Can't start new print job after Stop Print

**Comment by thinkyhead** [comment]
Still experimenting… It now does the print completion a little differently. I'll give it a more thorough test in the morning.

**Comment by qwewer0** [comment]
Now:
- **auto0.g**: Printer starts -> (LCD shows AUTO0.G) auto0.g doesn't runs (no stepper is engaged) -> Print job still active -> Can't start new print job after Stop Print

**Comment by qwewer0** [comment]
@thinkyhead Should I wait with testing until you say so?

**Comment by Zumili** [comment]
I just had a look and it seems, that there is a problem with the **bool CardReader::fileExists(const char * const path)** function.
I have 5 files on root of the SD card in the following order: _auto4.g auto3.g auto2.g auto1.g auto0.g_

If _card.filename is set to: "auto3.g"_ and is feed to fileExists(filename) it changes the _card.filename_ to _auto0.g_.
Notice, that _auto0.g_ has the file-index 0. It seems, that adding a **"/"** at the beginning of the filename will help. So if I call _fileExists("/auto3.g");_ the filename gets set to _auto3.g_ and not to _auto0.g_

**Comment by thinkyhead** [comment]
> If `card.filename` is set to: "`auto3.g`" and is [fed] to `fileExists(filename)` it changes the `card.filename` to `auto0.g`…

It probably changes it to the name of the newest file on the disk, not specifically "`auto0.g`."

Your analysis makes sense. I haven't really given `fileExists` the full testing and fix-up it deserves, and it has side-effects. I'm diving into SD file stuff tonight, so I should have it sorted out soon.

**Pull request merged**
