### PR TITLE
when mmu2 need load more, move E_AXIS

### PR DESCRIPTION
**Pull request by Fbn-lab**
### Description
when mmu need load in nozzle, move E_AXIS receive filament . reduce noise and fewer chances for bugs
### Requirements
you need a prusa mmu

### Configurations
#define MMU_MODEL PRUSA_MMU2 
[Marlin_conf.zip](https://github.com/MarlinFirmware/Marlin/files/9539508/Marlin_conf.zip)

### Related Issues

[mmu(Marlin_src_feature_mmu).zip](https://github.com/MarlinFirmware/Marlin/files/9539503/mmu.Marlin_src_feature_mmu.zip)

### CODE REVIEW

**Comment by ellensp** [comment]
https://marlinfw.org/docs/development/coding_standards.html
"All block elements should increase the indentation level, including #if blocks and other non-brace compiler blocks:"

**Comment by ellensp** [comment]
Also look at Brace-style
if (...) {   
not
if (...) 
{

**Comment by fBn0523** [comment]
@[ellensp](https://github.com/ellensp)
 I change the code. now,it will be ok

**Comment by Fbn-lab** [comment]
@[ellensp](https://github.com/ellensp)
I've changed the code
now it's done

**Pull request merged**
