### PR TITLE
Backlash Compensation for COREnn

### PR DESCRIPTION
**Pull request by palladin82**
Changed some lines for COREXY AXIS backlash correction...
Also needed to make changes menu_backlash.cpp, comment lines if(AXIS_CAN_CALIBRATE(A)) and if(AXIS_CAN_CALIBRATE(B))
Add definition BACKLASH_COREXY in config

### CODE REVIEW

**Comment by thinkyhead** [comment]
I renamed the option `CORE_BACKLASH` and modified code to cover all forms of Core kinematics. The configuration option was never included in the config files, but I think it can probably be removed. The modified behavior should apply whenever using backlash compensation with Core kinematics.

**Comment by palladin82** [comment]
Please link issue [https://github.com/MarlinFirmware/Marlin/issues/18444](https://github.com/MarlinFirmware/Marlin/issues/18444)

And also need to do changes to Marlin/src/lcd/menu/menu_backlash.cpp

```
  #if DISABLED(CORE_BACKLASH) || ENABLED(MARKFORGED_XY)
    if (AXIS_CAN_CALIBRATE(A)) EDIT_BACKLASH_DISTANCE(A);
    if (AXIS_CAN_CALIBRATE(B)) EDIT_BACKLASH_DISTANCE(B);
    if (AXIS_CAN_CALIBRATE(C)) EDIT_BACKLASH_DISTANCE(C);  
  #endif
```

**Comment by palladin82** [comment]
Tested, works as described...
It is necessary to improve the functionality of the influence on the second belt-dependent axis.

**Comment by rado79** [comment]
Tested. LPC1768 CoreXY compile error - SanityCheck: BACKLASH_COMPENSATION can only apply to z axis with your CORE system."

**Comment by rado79** [comment]
> Tested. LPC1768 CoreXY compile error - SanityCheck: BACKLASH_COMPENSATION can only apply to z axis with your CORE system."

compiles with #define BACKLASH_DISTANCE_MM { 0, 0, 0 }
works with editing settings in the menu

compile error with #define BACKLASH_DISTANCE_MM { 0.02, 0.02, 0 }

// Backlash Compensation
// Adds extra movement to axes on direction-changes to account for backlash.
//
#define BACKLASH_COMPENSATION
#if ENABLED(BACKLASH_COMPENSATION)
  // Define values for backlash distance and correction.
  // If BACKLASH_GCODE is enabled these values are the defaults.
  #define BACKLASH_DISTANCE_MM { 0, 0, 0 } // (mm)
  #define BACKLASH_CORRECTION    0.0       // 0.0 = no correction; 1.0 = full correction

  // Add steps for motor direction changes on CORE kinematics
  #define CORE_BACKLASH

**Comment by palladin82** [comment]
need to do changed Marlin/src/inc/SanityCheck.h:

```
....
#elif IS_CORE
    constexpr float backlash_arr[] = BACKLASH_DISTANCE_MM;
    #ifndef CORE_BACKLASH 
      static_assert(!backlash_arr[CORE_AXIS_1] && !backlash_arr[CORE_AXIS_2],
                  "BACKLASH_COMPENSATION can only apply to " STRINGIFY(NORMAL_AXIS) " with your CORE system.");
    #endif
....
```

**Comment by palladin82** [comment]
[https://github.com/MarlinFirmware/Marlin/pull/21731](https://github.com/MarlinFirmware/Marlin/pull/21731)

**Comment by RocksaltX** [comment]
M425 not working properly with this? Seems when sending M425 XY values are not displayed and M425 X<value> Y<value> does not save to eprom. If in marlin mode and using the backlash menu it works.

**Comment by niklasber** [comment]
When using coreXY backlash does it work axis wise or motor wise? What I mean is: Adjusting the x-backlash, does that correct the steps so the movement along the x axis changes or does it correct the steps the motor connected to x makes?

**Comment by palladin82** [comment]
It's correcting motor movement when direction changes, by adding or subtracting steps.

**Comment by niklasber** [comment]
I know, sorry my question wasn't worded understandable I guess.
When giving an x-backlash correction, does the algorithm adjust the steps of both motors in coreXY so the correction along the x-axis is right or does that mean the correction of steps is only used for the motor connected to x? 
When I adjust the values for x and y like I need, my 45 degrees infill starts to print in s-lines because the motor not moving corrects some steps forth and back.

**Comment by palladin82** [comment]
Oh, I understand. No it's not compensate backlash on second axis, there is a limitation in step planer, and I can't do this, some code with this function is commented, because not works.

````

switch (axis) {
             case CORE_AXIS_1:
               //block->steps[CORE_AXIS_2] += influence_distance_mm[axis] * planner.settings.axis_steps_per_mm[CORE_AXIS_2];
               //SERIAL_ECHOLNPAIR("CORE_AXIS_1 dir change. distance=", distance_mm[axis], " r.err=", residual_error[axis],
               //  " da=", da, " db=", db, " block->steps[axis]=", block->steps[axis], " err_corr=", error_correction);
               break;
             case CORE_AXIS_2:
               //block->steps[CORE_AXIS_1] += influence_distance_mm[axis] * planner.settings.axis_steps_per_mm[CORE_AXIS_1];;
               //SERIAL_ECHOLNPAIR("CORE_AXIS_2 dir change. distance=", distance_mm[axis], " r.err=", residual_error[axis],
               //  " da=", da, " db=", db, " block->steps[axis]=", block->steps[axis], " err_corr=", error_correction);
               break;
             case NORMAL_AXIS: break;
           }

````

**Pull request merged**
