### PR TITLE
Lin advance timing patch

### LINKED ISSUE #4114: Retract / prime problems with enabled LIN_ADVANCE
I got some response from Lulzbot TAZ users who are using my pressure advance feature. I can reproduce the issue, but I have no idea where it comes from at the moment:
- With FW retract (default prime speed = 8mm/s) or no retracts, the print is good.
-  With normal retract (Speeds tested between 20-35mm/s), the first ~2mm of the line are missing.
- With normal retract speed at 8mm/s, the print is good again.
- With FW retract prime speed = 20mm/s the line start isn't perfect, but not missing.
- Note that during retract/prime movements the pressure adjustment calculations are not active. The only difference to disabled LIN_ADVANCE is the seperate extruder ISR then.

The question are:
- How is it possible that we get different results between FW and normal retracts at the same prime speed? I thought the FW retract/prime movment ends up in the same action as a G1 E move?
- Why there is a difference between the separate extruder ISR and the stock one?

I will do some further analysis, but I'm not sad if somebody has some hints ;-)

Edit: Small update, a `G4 P300` short wait after each normal prime event (at 20mm/s) heals the problem. 100ms wait or a `M400` doesn't work. Hm..

### PR DESCRIPTION
**Pull request by Sebastianv650**
Fixes #4114. Forgot to keep track of the step_loops value inside the estepper ISR..

Edit: No idea why it shows 3 Commits - I'm not smart enough for GitHub.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'm just following up in this manner…

```
git fetch sebastian    ;# already had this set up
git checkout sebastian/LIN_ADVANCE-timing-patch -b rc_lin_timing_patch
git rebase RCBugFix    ;# use my up-to-date local as new base
git rebase -i RCBugFix ;# squash commits (but none needed after rebase)
mfpr                   ;# script to make a new PR
```

Looks like all you need to do to bring this PR up to date is actually…

```
git fetch upstream
git rebase upstream/RCBugFix
git push -f
```

**Comment by thinkyhead** [comment]
I thought, for some reason, that step loops had been made obsolete by the variable stepper ISR timing. I guess not!

Q: This should also apply to regular `ADVANCE` extrusion, correct?

**Comment by Sebastianv650** [comment]
Yes, that's also true for ADVANCE.
At some point the timer resolution isn't sufficient, meaning eISRrate is approaching 0. I guess it will also block other things if an isr is fired at 20khz for example.

**Comment by thinkyhead** [comment]
We do have to be cautious about those ISRs. And always remember the maxim, "To make it go faster, make it do less."

**Pull request closed without merging**
