### PR TITLE
Change HAL_PATH macro for easier HAL relocation

### PR DESCRIPTION
**Pull request by thinkyhead**
It might be possible to build the HAL as a library or do other tricks to reduce compile time, so I've started to experiment with that a bit. This PR simply modifies the `HAL_PATH` macro so that "`/HAL`" doesn't need to be included in the first argument; only the relative part, such as `../../..`.

In the process, I discovered that the ESP3DLib depends on `HAL_PATH` in its current form. So an additional PR has been submitted at luc-github/ESP3DLib#68 to allow Marlin to tell the library where to find things, while falling back to the existing method for older versions of Marlin. This should future-proof ESP3DLib and allow for Marlin to be built with tools that don't place dependencies at a location where `../../../../../Marlin/src` reaches the project root.

### CODE REVIEW

**Comment by luc-github** [comment]
this PR seems breaking compilation now for esp3dlib:
image

Today people revert Marlin commits to make it work  

the path given by `${platformio.src_dir}/src` is in my case `E:Marlin-bugfix-2.1.xMarlin/src`
but it miss `/` should be :  `E:/Marlin-bugfix-2.1.x/Marlin/src` so path is incorrect and include is not found I did not see where the variable ${platformio.src_dir} is expanded


Is there anything that must be enabled with latest bugfix make the path correct and so to make compilation pass again ?

**Comment by ellensp** [comment]
@luc-github please read https://github.com/MarlinFirmware/Marlin/issues/25767

**Comment by luc-github** [comment]
the issue is not same 
Here the issue is due to window environment that expand variable to `-DSRCHOME=E:\Marlin-bugfix-2.1.x\Marlin/src`
and used as it is, the `\` are not taken in account later, giving `-DSRCHOME=E:Marlin-bugfix-2.1.xMarlin/src` which is wrong

On line:
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/buildroot/share/PlatformIO/scripts/common-dependencies.py#L82
changing : `add_to_feat_cnf(feature, key[1])`
to
`add_to_feat_cnf(feature, key[1].replace('\\','/'))` 
to avoid the usage of `\` in path, solve the issue, and path under windows is now correct, and so compilation succeed
`-DSRCHOME=E:/Marlin-bugfix-2.1.x/Marlin/src`

**Comment by thinkyhead** [comment]
Thanks for the note! I'll go ahead and make that script change first thing in the morning.

**Pull request merged**
