### PR TITLE
Fix DUE HAL serial defines

### PR DESCRIPTION
**Pull request by boelle**
### Requirements

none

### Description

according to @Roman-RV78 this should solve a connect issue with NodeMcu to Serial 3

### Benefits

allow a NodeMcu to connect to Serial 3

### CODE REVIEW

**Comment by boelle** [comment]
hmm @thinkyhead any idea why this fails? i did before i rebased at my end

**Comment by thinkyhead** [comment]
The error message points the way to the fix:
image

**Comment by Evg33** [comment]
DUE_USB not available via usb now :(
default_envs = DUE_USB

```
#define MOTHERBOARD BOARD_RURAMPS4D_13
#define SERIAL_PORT -1
#define SERIAL_PORT_2 1
#define BAUDRATE 250000

```

**Comment by Evg33** [comment]
```
#if SERIAL_PORT == -1
//  #define MYSERIAL0 Serial1
  #define MYSERIAL0 SerialUSB
...
  #if SERIAL_PORT_2 == -1
//    #define MYSERIAL1 Serial1
    #define MYSERIAL1 SerialUSB

```

**Comment by Evg33** [comment]
If I change file \Marlin\src\HAL\HAL_DUE\HAL.h  like this, then it works

```
#if SERIAL_PORT == -1
  //#define MYSERIAL0 Serial1
  #define MYSERIAL0 customizedSerial1

```

And review this please:
```  #if SERIAL_PORT_2 == -1
    #define MYSERIAL1 Serial1
```

**Pull request merged**
