### PR TITLE
Sanity check to prevent Home offset use with a probe

### PR DESCRIPTION
**Pull request by Vertabreak**
Home offsets do not account for probe offsets so it should not be allowed to be used with a probe to prevent issues.
This was tested on my A20T with a 3dtouch that has a x_min_pos -1 and y_min_pos -7 for the test these where set to 0.
Using home offsets i set the front left corner of my build plate with home offsets and attempted to build a mesh.
When the probe got near the edge of the bed it probes off the bed and results in system halt.
Given the behavior it would be possible to damage the probe or print head in some situations by hitting the frame or bed in a place it should not.

### CODE REVIEW

**Comment by Vertabreak** [comment]
alternatively we could change it so that it does properly account for the probe offsets but it has been this way for a very long time noted this issue years ago and it still tests with the same results today. with some further testing i have found that if probe offset = 0 then it miss calculated and probed off the bed but when i set it to say 0.1 it didn't probe off the bed it just skipped the entire row on both sides of that axis. setting offset to -0.1 it went back to probing off the bed running more tests. setting probe offset to -1 still probing off the bed. its like calculations are inverted on the y axis or something given the behavior.

**Comment by thisiskeithb** [comment]
Does the issue only manifest itself if you change the home offset during runtime? Almost every one of my printers have a probe & home X/Y off the build plate without issue.

**Comment by Vertabreak** [comment]
normally i use x_min_pos & y_min_pos to shift the build area over to line up with the build plate. 
but it has come to my attention that many think you can use home offsets to do the same thing.
any time i have tested attempting this it cant be done in any viable way.
i could provide video examples of tests if needed.
having the feature enabled does not break anything its only if you make use of it.
the example case given is normally i have a x min pos -1 and y min pos -7 if i set these to 0 and then attempt to use M206/M428 to set the home offset to the corner of the plate it does not work correctly.
i have tested and retested this many times over the years and at no point has it ever properly worked with a probe installed on any of my machines.

**Comment by Vertabreak** [comment]
https://youtu.be/VIIjHVx_sg4
video displaying the issue with home offsets.

**Comment by thisiskeithb** [comment]
I thought this was fixed in https://github.com/MarlinFirmware/Marlin/pull/19423, but I’ll run some tests here.

**Comment by Vertabreak** [comment]
if it can be gotten working correctly this sanity check would not be needed but i have never known it to function correctly with a probe.

**Comment by thinkyhead** [comment]
There is no reason to assume incompatibility. A proper fix would be better, and probably better documentation about the home offset. It is important to understand what it was originally designed to do, how it has changed since Marlin 1.0, and what it is useful for now.

**Comment by DerAndere1** [comment]
Detailed reasoning about early stages of M206 development can be found in the commit message of https://github.com/MarlinFirmware/Marlin/commit/957e966d2d5fb1884adb1f982ad01d39d547eb36 . 
Functionality of M206 was changed later in commit https://github.com/MarlinFirmware/Marlin/commit/8e5099fa0c3b35dea76941ff2de1fce08a6372c3 by making it update software endstops

**Pull request closed without merging**
