### PR TITLE
Replace MIN# / MAX# with variadic MIN / MAX

### PR DESCRIPTION
**Pull request by dgrat**
The _cpluplus check macro seems unnecessary for me and therefore the macro definitions too. 
If desired I could replace all macros with templates, but I am not sure if it fits to the rest of the project code :)

### CODE REVIEW

**Comment by thinkyhead** [comment]
> he _cpluplus check macro seems unnecessary for me

This breaks compilation of `.c` files, most obviously when building for LPC1768. The conditionals that define these depending on whether `macros.h` is being included from a `.c` or `.cpp` file need to be retained.

**Comment by thinkyhead** [comment]
Unless we can come up with variadic macros to accommodate compiling `macros.h` from `.c` files, this PR will have to be rejected.

**Comment by ejtagle** [comment]
@thinkyhead : Look here: https://stackoverflow.com/questions/824639/variadic-recursive-preprocessor-macros-is-it-possible , the answer with 35 votes is basically what you want to achieve .... 👍

**Comment by thinkyhead** [comment]
Yeah, saw that. It's a little more complicated than we usually like. The code using the macros ends up simpler, but the macros themselves a bit messier. And then we also have to use `MAX_OF_N` instead of just `MAX` throughout.

We also have the problem that the CMSIS headers define their own `MIN` / `MAX` macros, and I'm not sure that we should modify anything inside the CMSIS folder.

**Comment by ejtagle** [comment]
Well, right now we probably have that problem ... ;) : The CMSIS headers define MIN/MAX, then we use C++ templates to "redefine" MIN/MAX...

I will always suggest to NEVER include such system headers in Marlin, except in the HAL cpp files themselves

The main reason is that you actually NEVER want to use CMSIS defined macros outside of the HAL, because CMSIS is not always available/used. And having differing macros (that we do not control) for different platforms leads to completely unpredictable results (you actually don´t know the promotions being made inside CMSIS MAX/MIN , if they promote to signed/unsigned/dont promote, reevaluate arguments multiple times...

**Comment by dgrat** [comment]
Ah the ARM embedded library :) I will try to find a solution this evening. I feel that having one template and one macro definition is not so elegant. My aim was it to remove one of them.

**Comment by thinkyhead** [comment]
> My aim was it to remove one of them.

Whatever the solution is, under the current codebase it must be C-compatible, not just C++, because we cannot force `.c` files to be compiled as `.cpp`, and because of where `macros.h` is included in various headers, the macros we define do end up being used by some `.c` files outside of Marlin.

Again, I'm dubious about modifying CMSIS files, but the first thing I would've tried was to put `#include "macros.h"` where the MIN/MAX macros are currently defined in the CMSIS headers. **(EDIT: This didn't work, so some of `macros.h` would need to be in a separate file.)**

Ultimately, it may be better to avoid overloading `MIN`/`MAX` and use unique names for all the Marlin-specific code. However, if we can preserve these names without conflicting with other definitions, that would be most welcome.

**Comment by thinkyhead** [comment]
So as it turns out, `extern "C++"` does work, forcing C++ compilation on these (when included within an `extern "C"` linkage within a `.cpp` file). I also split off `MIN` and `MAX` into a separate file so it could be included in `lpc_types.h` within `CMSIS` for the LPC1768 platform.

**Pull request merged**
