### PR TITLE
Adjust GTR PeripheralPins to avoid timer conflicts

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

The GTR PeripheralPins.c and variant.h files were largely copied from the SKR Pro.

The pin assignments for fans and heaters differs significantly between these two boards, especially when considering the expansion board for the GTR.

This change allocates pins for all heaters and fans supported by this board, and consolidates them onto as few timers as possible. Along with this, the TONE timer was adjusted to avoid conflicts in Timer2 with heater pins.

### Benefits

Allows use of all fan and heater pins for PWM, without causing timer conflicts. In addition two pins on the ESP header and the Servo output pin are enabled for hardware PWM.

All other pins are disabled. If people complain about pins losing PWM capabilities we may have to revisit this again.

### Configurations
This configuration previously caused problems because the HEATER1 pin is specified as the Controller Fan pin, and that collided with the timer used for BLTouch control. This prevented the BLTouch from responding to commands.
[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5144586/Marlin.zip)

### Related Issues

No issue was created. This was discovered through discussion with @AdamV3D on Discord.

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I tested the following pins on my bench. I have not tested beyond this.
- BLTouch Functionality
- SPEAKER functionality (RepRapDiscount Full Graphics Display)
- CONTROLLER_FAN when mapped to Heater1
- FAN1-FAN6

I do **not** have this board in a printer. It would be great if @AdamV3D or other GTR users could try this and report back their results. Even if you were not already having PWM issues, I would like greater confidence that I am not breaking existing users.

**Comment by thisiskeithb** [comment]
I posted this in the BigTreeTech GTR group as well, so hopefully we can get this tested on real hardware configs.

**Comment by AdamV3D** [comment]
I've loaded up onto my completed machine. One observation, there is a light on the PCB turning on which didn't before, light blue, near where the wifi would go.

Everything seems to be working exactly as expected. Sadly my hemera gear just cracked as I was loading filament so that's going to put a bit of a delay on more testing. Hopefully I can get another shipped soon.

**Comment by sjasonsmith** [comment]
> One observation, there is a light on the PCB turning on which didn't before, light blue, near where the wifi would go.

@AdamV3D thanks for testing this! If the LED is D11 that is the light that tells you whether an SD card is inserted.

I don't see any other LEDs near the WIFI connector. If it is something else please post a picture.

**Comment by AdamV3D** [comment]
Got a replacement Hemera so done some more testing. Yes, light blue is definitely the micro sd card slot.

Having an issue with everything just stopping mid print. Seems like the serial interface is going to sleep or something, it just stops sending gcode so heaters stay on but all motion stops. Not sure if this is related but thought i'd mention it just in case it is.

Edit: little bit of research tells me that loss of communication is separate issue and that's the only problem i'm having so thumbs up for the pins changes.

**Pull request merged**
