### PR TITLE
add support for SKR V1.4

### PR DESCRIPTION
**Pull request by Msq001**
### Description
* add new board [BTT SKR V1.4](https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/tree/master/BTT%20SKR%20V1.4)

### Benefits

*  leads out the IIC and Neopixel port
*  added serial wifi interface (ESP3D)

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Looking forward to the SKR 1.4 ~~Pro~~ Turbo 🙂 Looks like it'll have an `LPC1769` mcu?

**Comment by Msq001** [comment]
> Looking forward to the SKR 1.4 Pro  Looks like it'll have an `LPC1769` mcu?

yeah,  The difference between` SKR V1.4 Pro` and `SKR V1.4` is only the MCU LPC1769(V1.4 Pro) and LPC1768(V1.4)

**Comment by thinkyhead** [comment]
@Msq001 — Can you make this PR "editable by maintainers," please? There should be a checkbox on the right side of this page someplace….

**Comment by Msq001** [comment]
@thinkyhead sorry, the option was not found in this PR, so I close this PR,  and reopen in #16236 , It has already enabled "allow edits from maintainers"

**Pull request closed without merging**
