### PR TITLE
Update MKS Robin E3D and E3 pins Definition

### PR DESCRIPTION
**Pull request by ils15**
Hi, i realize MKS robin nano pins definition is outdated in your last stable marlin
send files in a issue https://github.com/MarlinFirmware/Marlin/issues/18804
and PR here to update bugfix branch

thanks

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Both boards share many of the same pins, so they have been consolidated to make updating them easier:

- [pins_MKS_ROBIN_E3.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_E3.h)
- [pins_MKS_ROBIN_E3D.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_E3D.h)
- [pins_MKS_ROBIN_E3_common.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32f1/pins_MKS_ROBIN_E3_common.h)

**Comment by ils15** [comment]
a saw it and close pull request
thanks

**Comment by thisiskeithb** [comment]
No worries. I was just posting this information for anyone checking out closed Issues or PRs that weren't resolved/merged.

**Comment by ils15** [comment]
great. Mks insert Wifi option in LVGL
but doesnt PR to Marlin

check it


https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware/commit/0804decdfcd45b50207973e683c3b1af653dd447

**Comment by thisiskeithb** [comment]
Yep! I'm working with them and it will come eventually 🙂

**Comment by ils15** [comment]
i believe the best way is unify develop
they still using old LVGL structure (with mks_fonts /mks_pics)
new one asset folder...
i take some features in her marlin version, like rotate screen and wifi
but i prefer to use official marlin
they share the same now
i believe a fork with a official marlin is more suitable for now

**Pull request closed without merging**
