### PR TITLE
[2.0.x] Extruders = 0 make all Stepper available for X,Y,Z

### PR DESCRIPTION
**Pull request by fabtopia**
Contains conditions and a little logic so Marlin can be configured without any extruder/hot end so all steppers can be used for X,Y,Z axis. This is useful for CNC and laser project.

[Concise Diff](9091/files?w=1)

### CODE REVIEW

**Comment by lacklustrlabs** [comment]
I see a few over specified #if conditions, for example:
```
#if ENABLED(PIDTEMP) && HOTENDS > 0
#if HAS_THERMALLY_PROTECTED_BED && HOTENDS > 0
#if HAS_TEMP_HOTEND && HOTENDS > 0
``` 
Wouldn't it be better to lock down those conditions in SanityCheck.h? 
E.g If `HAS_TEMP_HOTEND` is 'true' then you already know that `HOTENDS >` 0 is (or should be) true.

**Comment by lacklustrlabs** [comment]
I see a few over specified #if conditions, for example:
```
#if ENABLED(PIDTEMP) && HOTENDS > 0
#if HAS_TEMP_HOTEND && HOTENDS > 0
``` 
Wouldn't it be better to lock those conditions down with an assert in SanityCheck.h? 
E.g If `HAS_TEMP_HOTEND` is 'true' then you already know that `HOTENDS>0` is 'true'.

**Comment by fabtopia** [comment]
@lacklustrlabs I'm not a super programmer and not completely into the code of marlin. I made this partly by try and error. I also saw double variables (EXTRUDERS and E_STEPPER for example) for so far I can see, but as I said. I do not oversee the code of marlin completely. So i'm always open for suggestions. As long as this feature is gona make it into the next version.

**Comment by lacklustrlabs** [comment]
@fabtopia I'm new to Maple as well. I was just about to start to look into the code base to figure out how to do exactly the same thing you did. Now I don't have to, thank you.

**Comment by jimhiggs** [comment]
I was following this, don't really understand all the force_push stuff. Is this concept going to happen or has it been dropped?

**Comment by thinkyhead** [comment]
The work required simply to support zero extruders is vast and sweeping, and will require many PRs over a long period of time. This cannot be considered a complete PR, and it is far out of date. Anyone who wants to apply a change here or there to move Marlin towards allowing zero extruders should please feel free to do so. Once all needed changes are applied Marlin will then be able to build with no extruder tools.

**Comment by jimhiggs** [comment]
Ok, Thanks for the update. I am going to be using it for a MPCNC on a ramps, I will just use the fix detailed on the V1engineering site until such time as it does. Big fan of marlin, use 2.0 on my reprap cubex duo mod and love it. Thanks for all your work.

**Pull request closed without merging**
