### PR TITLE
fixes #22168 Two 128x64 lcd hotend icon related issues

### LINKED ISSUE #22168: [BUG] Compile error for numberless, non-animated, non-inverted lcd hotends
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When hotends are configured to be numberless, not animated and not inverted, marlin fails compilation.

### Bug Timeline

_No response_

### Expected behavior

Marlin should compile.

### Actual behavior

This specific combination of settings is not covered in the Compile Macros and Marlin compilation fails with error:
```
In file included from Marlin/src/lcd/dogm/../../inc/MarlinConfigPre.h:37:0,
                 from Marlin/src/lcd/dogm/status_screen_DOGM.cpp:28:
Marlin/src/lcd/dogm/status_screen_DOGM.cpp: In function 'void _draw_hotend_status(heater_id_t, bool)':
Marlin/src/lcd/dogm/status_screen_DOGM.cpp:249:26: error: 'status_hotend1_a_bmp' was not declared in this scope
       #define OFF_BMP(N) status_hotend##N##_a_bmp
                          ^
```

### Steps to Reproduce

1. Enable LCD
2. Enable `STATUS_HOTEND_NUMBERLESS`
3. Disable `STATUS_HOTEND_INVERTED`
4. Disable `STATUS_HOTEND_ANIM`
5. Try to compile, marlin tries to get the numbered hotend images but they don't exist

### Version of Marlin Firmware

2.0.9

### Printer model

_No response_

### Electronics

_No response_

### Add-ons

_No response_

### Your Slicer

_No response_

### Host Software

_No response_

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by ellensp**
### Description

For the 128x64 lcd there are 3 defines that change the behavior of the extruder icon
STATUS_HOTEND_NUMBERLESS
STATUS_HOTEND_INVERTED
STATUS_HOTEND_ANIM 

STATUS_HOTEND_NUMBERLESS is only useful when EXTRUDERS is > 1 

With all 3 defines disabled the icon disappears. I don't believe this was the intent.  Now you get a static icon.

with the following combination 
Enable STATUS_HOTEND_NUMBERLESS
Disable STATUS_HOTEND_INVERTED
Disable STATUS_HOTEND_ANIM

Marlin fails to compile, see https://github.com/MarlinFirmware/Marlin/issues/22168
This has also been corrected

### Requirements

a 128x64 LCD test with either  EXTRUDER = 1 and EXTRUDERS  > 1
All combinations of enabling and disabling the following. 
STATUS_HOTEND_NUMBERLESS
STATUS_HOTEND_INVERTED
STATUS_HOTEND_ANIM

### Benefits

STATUS_HOTEND_* defines work as expected

### Related Issues
Issue https://github.com/MarlinFirmware/Marlin/issues/22168

### Notes
I would really like someone to double check this. To many combinations. But I think I've gotten it corrected.

### CODE REVIEW

**Comment by thinkyhead** [comment]
> STATUS_HOTEND_NUMBERLESS is only useful when EXTRUDERS is > 1

Yep. Otherwise, it is simply ignored (i.e., it is always in effect).

**Comment by thinkyhead** [comment]
> STATUS_HOTEND_INVERTED

Is this actually a good thing? I know someone wanted inverted hotend graphics at some point for the animated indication of heating. But is the hollow graphic preferable in other circumstances? The solid nozzle graphic barely looks like a nozzle, and the hollow nozzle graphic in the absence of the solid one is even less clear.

**Comment by ellensp** [comment]
I just think its a personal preference.

**Comment by thinkyhead** [comment]
Hmm, sure enough. It may have been better to have never given users the new option in the first place, as it only gives rise to a new caprice!

**Pull request merged**
