### PR TITLE
Add NOZZLE_TO_PROBE_OFFSET_Z_POSITIVE

### LINKED ISSUE #20411: [BUG] No longer possible to have a probe which triggers above the nozzle
Using latest bugfix 2.x

From Sanity check 
static_assert(sanity_nozzle_to_probe_offset.z <= 0.25,
                "Are you sure your Probe triggers above the nozzle? Set a negative Z value in the NOZZLE_TO_PROBE_OFFSET.");

Yes I am sure my probe triggers above the nozzle.  This would be true with any configuration where the nozzle moves out of the way to expose a probe which is above the nozzle height.  Forcing users into specific probe configurations seems counter productive. Im all up for a warning or notice in this regard, but not a compilation error. 

For the moment, I have commented the offending line in  SanityCheck.h

and relevant settings from configuration.h
#define NOZZLE_TO_PROBE_OFFSET { 0, 0, 7.0 } //My nozzle is 7mm lower than my probe.

### PR DESCRIPTION
**Pull request by swissnorp**
### Description

Allow a positive value for z offset from nozzle to probe.
This is no more possible since: Commit https://github.com/MarlinFirmware/Marlin/commit/649965ae32eca5140ea66d1265a69576e2a2c669

From my pull request: PR https://github.com/MarlinFirmware/Marlin/pull/20239

### Benefits

It allows to have a positive value for `Z` in `NOZZLE_TO_PROBE_OFFSET` but `NOZZLE_TO_PROBE_OFFSET_Z_POSITIVE` must be enalbed.

It fixes compiling for ZYYX printer (https://github.com/MarlinFirmware/Marlin/pull/20239#issuecomment-736557896).
But it also forces users of a CR-6 SE, FLSUN, Kossel or similar probing mechanism to enable `NOZZLE_TO_PROBE_OFFSET_Z_POSITIVE`.

### Configurations

Niente

### Related Issues

Sort of: https://github.com/MarlinFirmware/Marlin/pull/20239#issuecomment-736557896

### CODE REVIEW

**Comment by ohrn** [comment]
Thanks! That was quick.

With this patch I can successfully build with a positive offset for the ZYYX.

I also gave the Z probe offset wizard a try and it promptly smashed the nozzle into the build plate. :disappointed: 

I'll investigate a bit more and write a more detailed bug report on that.

**Comment by thinkyhead** [comment]
Have you enabled `NOZZLE_AS_PROBE`? The only probes that trigger in the positive direction that we are aware of use the nozzle itself as the probe. Otherwise the nozzle would be pressing on the bed and throwing off the probe.

**Comment by swissnorp** [comment]
@thinkyhead
I think it has a recess for the nozzle to dive below Z0 and triggering an endstop mounted to the extruder carriage. Crazy and highly uncomon. https://www.zyyxlabs.com/product/zyyx-pro-campaign/

@ohrn
Could you provide your configuration.h and your configuration_adv.h please? So i could help you better and understand your printer.

As Inderstand so far, if you want to use the wizard you must do the following steps:

- Define a `NOZZLE_TO_PROBE_OFFSET` for X and Y.
- _Important_: Add up those values to your `Z_SAFE_HOMING_X_POINT / Z_SAFE_HOMING_Y_POINT`.
- If you want to use a different Z offset for the wizard (i dont recommend it): Define a positive value for `PROBE_OFFSET_WIZARD_START_Z`.

**Comment by ohrn** [comment]
@swissnorp

So the problem is in prepare_for_probe_offset_wizard(), it first probes the build plate at PROBE_OFFSET_WIZARD_XY_POS this leaves the nozzle recessed below the build plate at Z=-3.

It then attempts to move the nozzle tip above the probe point, using a horizontal move, this makes the nozzle smash sideways into the build plate. On machines that use nozzle as probe I guess it would drag the nozzle across plate, also not very nice.

My suggested fix is to add a call to z_clearance_move() like so: ohrn/Marlin@7616fac1b4

It might be unnecessary on printers with a negative z-offset, on the other hand there might be clips or other obstructions as indicated by Z_HOMING_HEIGHT. Better safe than sorry?

**Comment by ohrn** [comment]
@thinkyhead

If you check the pictures of the ZYYX+ version https://www.zyyxlabs.com/zyyx-plus/ you can clearly see the cutouts in the build plate that the nozzle lowers into.

I didn't find any decent pics of the actual switch assembly on the print head, but I can post some pics of my machine if anyone is curious.

**Comment by swissnorp** [comment]
> 
> 
> @swissnorp
> 
> So the problem is in prepare_for_probe_offset_wizard(), it first probes the build plate at PROBE_OFFSET_WIZARD_XY_POS this leaves the nozzle recessed below the build plate at Z=-3.
> 
> It then attempts to move the nozzle tip above the probe point, using a horizontal move, this makes the nozzle smash sideways into the build plate. On machines that use nozzle as probe I guess it would drag the nozzle across plate, also not very nice.
> 

> It might be unnecessary on printers with a negative z-offset, on the other hand there might be clips or other obstructions as indicated by Z_HOMING_HEIGHT. Better safe than sorry?

Well Sorry 😅 , thats bugfix

> My suggested fix is to add a call to z_clearance_move() like so: [ohrn/Marlin@7616fac](https://github.com/ohrn/Marlin/commit/7616fac1b4)
> 
If there should be a  clearance move, than it should be done in `z_offset_ref = probe.probe_at_point(wizard_pos, PROBE_PT_`**`RAISE`**`, 0, true);`
We may could add an `if probe.offset.z >=0` to set `PROBE_PT_RAISE` instead of `PROBE_PT_STOW`.


I aks you to upload your configuration files. It would be alot easier!
I will need to see how the probe is set! I also will look up configs of printers with a pushing nozzle triggering a switch.

Is there any reference for configuring Marlin for a ZYYX printer?

Good Night, norp

**Comment by ohrn** [comment]
> > My suggested fix is to add a call to z_clearance_move() like so: [ohrn/Marlin@7616fac](https://github.com/ohrn/Marlin/commit/7616fac1b4)
> 
> If there should be a clearance move, than it should be done in `z_offset_ref = probe.probe_at_point(wizard_pos, PROBE_PT_`**`RAISE`**`, 0, true);`
> We may could add an `if probe.offset.z >=0` to set `PROBE_PT_RAISE` instead of `PROBE_PT_STOW`.
> 

I'm a complete newbie at the inner workings of Marlin, why is PROBE_PT_STOW and PROBE_PT_RAISE mutually exclusive? I think it would be useful to do both.

The probe (if there is one) should be stowed as probing is now complete, it's not needed any more. At the same time the nozzle should be raised to avoid obstructions, like bulldog clips on a "normal" printer or because it's below or touching the plate (on a ZYYX or nozzle as probe), before moving it around the build plate.

Doing `z_offset_ref = probe.probe_at_point(wizard_pos, probe.offset.z >=0 ? PROBE_PT_RAISE : PROBE_PT_STOW, 0, true);` would solve my problem just fine, but it feels like an unsatisfactory fix to me.

> I aks you to upload your configuration files. It would be alot easier!
> I will need to see how the probe is set! I also will look up configs of printers with a pushing nozzle triggering a switch.
> 

I have pushed my config to ohrn/Marlin@1b15364171 Be warned that it's a bit of a mess, I've been experimenting with just about every option there is and also with multiple boards from MKS.

> Is there any reference for configuring Marlin for a ZYYX printer?
> 

Not as far as I'm aware, the printer originally comes with a board running Sailfish firmware. I've replaced it and worked out a config for Marlin.

> Good Night, norp

Good night! Thanks again for taking an interest in my issues.

Regards,
Fredrik

**Comment by thinkyhead** [comment]
The ZYYX presents an interesting situation. Is it using 4-point linear leveling (ABL LINEAR) to produce a flat plane? It looks like the code would have to be modified if you wanted to also use the probe for homing, or to probe a mesh. Although, UBL could combine these functions to get a refined tilted mesh.

I think the sanity checks are draconian and I would describe them as "probative" (no pun intended) to find out if there was some unusual use case. Since there is a use case, I think it's safe to simply remove the `#error` messages and / or replace them with a general warning.

**Comment by ohrn** [comment]
@thinkyhead

> The ZYYX presents an interesting situation. Is it using 4-point linear leveling (ABL LINEAR) to produce a flat plane? It looks like the code would have to be modified if you wanted to also use the probe for homing, or to probe a mesh. Although, UBL could combine these functions to get a refined tilted mesh.
> 
Yes, something like that. The build plate has 4 notches but the original firmware only uses 3 points to measure a flat plane, it also allows manual input of a few offsets in a 2x2 mesh.

As the build plate is removable (held by magnets) using UBL and the 3-point mesh tilting would be perfect for this printer. Probe the mesh once (by attaching a temporary extension to the switch probe) and store it. Then, whenever the plate has been removed and reinserted (or perhaps even before each print), adjust the mesh using a 3-point measurement in the notches to compensate for any movement of the plate.

However I can't seem to be able to wrap my head around how the 3-point adjustment is supposed to work. I don't understand the starting point it uses when rotating the mesh. It does not seem to be based on the difference between the last 3-point measurement and the current one, which means the mesh ends up tilted all wrong for me.

But I digress, where would be a good forum to ask support questions about UBL?

**Comment by thisiskeithb** [comment]
> But I digress, where would be a good forum to ask support questions about UBL?

[The Marlin Discord server](https://discord.gg/n5NJ59y).

**Comment by sjasonsmith** [comment]
@c3D-Dan has reported this being a problem as well. It seems they have a nozzle which physically moves to allow for probing, with a +7.0 Z offset.

Given that this has broken previously working configurations, I think it seems prudent to simply allow positive offsets, and people have to be responsible for setting an appropriate `Z_CLEARANCE_BETWEEN_PROBES` for their printer.

I am not even sure if it is appropriate to test that the clearance is greater than the offset, since in the case of a moving nozzle you probably don't need or even want that much clearance. You would only need it when stowing.

**Comment by sjasonsmith** [comment]
@swissnorp I am putting this in with much of your intended changes removed, along with the sanity checks from your previous PR. I know this isn't what you wanted, but there seems to be a small but growing list of impacted people.

Yes, this means that people can misconfigure things. We do have better instructions now with the updated comments, but they will surely be ignored at times. I hope we can learn from future bug reports and continue to harden things, but with the new knowledge of these less common use cases.

**Pull request merged**
