### PR TITLE
MKS Robin 2 (STM32F407ZE) support

### PR DESCRIPTION
**Pull request by shitcreek**
taken from https://github.com/makerbase-mks/MKS-Robin/tree/master/MKS%20Robin2/firmware/Marlin2.0-MKS-Robin2

NEED testing.

https://github.com/MarlinFirmware/Marlin/issues/16267

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Adding configs to the MKS example folder would probably help with these Robin boards since they have a tethered TFT and need things like `FSMC_GRAPHICAL_TFT`, `TOUCH_BUTTONS`, and `XPT2046_*` calibration settings or they won't work properly.

I'll add it to my list of configs to import if they don't make it in with this PR.

**Comment by tpruvot** [comment]
the TFT sold with this board is a ILI9488 480x320 which is kinda different from currently supported ones. That will require a new upscaling (3x) unit to be supported like the 320x240 ones (2x)

else.. i'm not sure any F4 chip can handle the FSMC bus in current marlin 2.0

But... there are others displays connectable on this board, like the serial tfts

**Comment by INNO-3D** [comment]
Hi, How can I compile the MKS Robin2  ??? 
I always recive this error :
  AssertionError: :
  File "C:\Users\...\.platformio\penv\Lib\site-packages\platformio\builder\main.py", line 166:
    env.SConscript(item, exports="env")

with this firmware :
https://github.com/makerbase-mks/MKS-Robin/tree/master/MKS%20Robin2/firmware

**Comment by thisiskeithb** [comment]
@INNO-3D: You'll need to post in Makerbase's issue queue since it's their fork of Marlin.

**Comment by INNO-3D** [comment]
I'm new, how can post en issue en Makerbase ?

**Comment by thisiskeithb** [comment]
Click on the green “New” button: https://github.com/makerbase-mks/MKS-Robin/issues

**Comment by thinkyhead** [comment]
I have an MKS Robin 2.4 with an STM32F103ZET6 chip. What `MOTHERBOARD` should I use?

**Comment by thisiskeithb** [comment]
> I have an MKS Robin 2.4 with an STM32F103ZET6 chip. What `MOTHERBOARD` should I use?

`BOARD_MKS_ROBIN2`

**Pull request merged**
