### PR TITLE
add Lulzbot TAZ4 example configuration

### PR DESCRIPTION
**Pull request by sorki**
Adds support for Lulzbot TAZ4.

Diffs against standard config files:

http://48.io/~rmarko/dev/Configuration.h.diff
http://48.io/~rmarko/dev/Configuration_adv.h.diff

Known issues:
- Buzzer not working (not sure where's the problem, pin seems to be correct)
- ~~ENCODER_PULSES/STEPS needs tweaking (will try to fix this later today and update PR)~~

### CODE REVIEW

**Comment by sorki** [comment]
Buzzer issue investigation:
- buzzer is connected to pin 79 (PJ7) which has no additional functionality (http://reprap.org/wiki/Rambo_development)
- tone seems to require PWMable pin to work

Using simple WRITE(HIGH/LOW) it starts working, diff:

``` diff
diff --git a/Marlin/buzzer.cpp b/Marlin/buzzer.cpp
index e52f2fb..0b828dd 100644
--- a/Marlin/buzzer.cpp
+++ b/Marlin/buzzer.cpp
@@ -9,8 +9,9 @@
         lcd_buzz(duration, freq);
       #elif defined(BEEPER) && BEEPER >= 0 // on-board buzzers have no further condition
         SET_OUTPUT(BEEPER);
-        tone(BEEPER, freq, duration);
+        WRITE(BEEPER, HIGH);
         delay(duration);
+        WRITE(BEEPER, LOW);
       #else
         delay(duration);
       #endif
```

I think this deserves separate issue on handling non-PWMable pins with buzzer. This PR is good to go though.

**Comment by AnHardt** [comment]
@sorki 
About the Buzzer problems.
If you can really hear a sound with the code above, we have to differentiate some cases.

a.) If we have a buzzer, or a speaker.
b.) If we have a PWMable pin, or not.

Speakers require ether 
tone(), what requires a PWMable pin, or a
loop where the pin is switched on an off.

Sadly it's not very well documented if a panel uses a buzzer or a speaker.
The optical difference between a piezo-buzzer and a piezo-speaker is not more then the partnumber.

**Comment by thinkyhead** [comment]
Does this need any update, or does #2513 fix the buzzer issue?

**Comment by thinkyhead** [comment]
@sorki There have been some small tweaks to the configurations, so you might want to compare and do a quick update. Otherwise these look good to me.

**Comment by sorki** [comment]
I'll get back to this next week, sorry.

**Pull request closed without merging**
