### PR TITLE
Bugfix 1.1.x

### PR DESCRIPTION
**Pull request by Sangoku**
### Requirements

* Can`t commit to your branch

### Description

Wanted to add USE_CONTROLLER_FAN PWM controll so you can tune down the mosfets

### Benefits

New feature
just add this to config file:
+ line 199 in Configuration_adv.h
#define USE_CONTROLLER_FAN   
#if ENABLED(USE_CONTROLLER_FAN)
  #define CONTROLLER_FAN_PIN 6        // Set a custom pin for the controller fan
  #define CONTROLLERFAN_SECS 60          // Duration in seconds for the fan to run after all motors are disabled
  #define CONTROLLERFAN_SPEED 80        // 255 == full speed
  #define HAS_CONTROLLER_FAN true;
#endif

And in temperature.cpp 

#if HAS_CONTROLLER_FAN
    SET_OUTPUT(CONTROLLER_FAN_PIN);
    #if ENABLED(FAST_PWM_FAN)
      setPwmFrequency(CONTROLLER_FAN_PIN, 1); // No prescaling. Pwm frequency = F_CPU/256/8
    #endif
  #endif

ps. would apriciate it if i could contribute to this great project 👯‍♂️

### CODE REVIEW

**Comment by thinkyhead** [comment]
This isn't how it works. Currently `1.1.x` is end-of-life and we aren't taking any pull requests for that branch. Please only submit to `bugfix-2.0.x` going forward.

**Comment by stef-ladefense** [comment]
it's a shame not to continue to maintain a version 1.1 that works on 100% of the printers that it uses when we can not even compile version 2.0 from one week to another

**Comment by AnHardt** [comment]
If 1.1 works for you - just use it. We'll not delete it.

**Comment by thinkyhead** [comment]
The open source nature of Marlin may be giving the false impression that 2.0 is "out there." But it's simply not a version for everybody. It's under heavy development, highly experimental, and it's not even tagged as an "alpha" version yet. And, as you can see this PR was clearly created by mistake.

**Pull request closed without merging**
