### PR TITLE
Refactoring work on FTDI EVE Touch Screen

### PR DESCRIPTION
**Pull request by marciot**
- It is now far easier to add and remove screens to the UI
  - Whether an include exists in "screen.h" now controls whether screens are compiled in
- Put each screen's data and implementation together in a header file.
- "screen_data.h" and "screen.cpp" are now much easier to maintain.

### CODE REVIEW

**Comment by thinkyhead** [comment]
It looks very nice. Unfortunately your PR is (as usual) not editable and it needs basic repairs to whitespace. Are you able to make the PR editable so that it can be fixed up and prepared for merge? I would prefer to patch this in the usual way and let it get tested by CI and reviewed. It takes longer for me to work around these non-editable PRs and merge the changes manually.

**Comment by thinkyhead** [comment]
See drunken-octopus/drunken-octopus-marlin#31 for the automated changes….

**Comment by marciot** [comment]
> It looks very nice. Unfortunately your PR is (as usual) not editable and it needs basic repairs to whitespace. Are you able to make the PR editable so that it can be fixed up and prepared for merge? I would prefer to patch this in the usual way and let it get tested by CI and reviewed. It takes longer for me to work around these non-editable PRs and merge the changes manually.

This is still a github issue. I am unable to mark PRs as editable since my fork got moved from my personal account to an organizational account. I still have not found a workaround.

**Comment by marciot** [comment]
@thinkyhead: A while back I sent you an invite to join the organization, but you never accepted. Perhaps that would allow you to edit. I will renew the invitation.

**Comment by thinkyhead** [comment]
> I will renew the invitation.

That might work! I'll keep a close check on my email.

**Comment by marciot** [comment]
> > I will renew the invitation.
> 
> That might work! I'll keep a close check on my email.

@thinkyhead: You should have the e-mail already. Did you get it?

**Comment by thinkyhead** [comment]
> You should have the e-mail already. Did you get it?

Ah, yes. I got it now, thanks!

**Comment by thinkyhead** [comment]
…but GitHub still wouldn't allow me to push changes to this PR. Now that I'm in the organization I can possibly make changes directly to the branch if I check it out again, or if I check it out directly rather than through the PR. Or, even though I'm now a member you might still have to add me and give me "write" access to the specific repository.

Anyhow, in the meantime I've gone ahead and merged these changes directly.

**Comment by marciot** [comment]
> …but GitHub still wouldn't allow me to push changes to this PR. Now that I'm in the organization I can possibly make changes directly to the branch if I check it out again, or if I check it out directly rather than through the PR. Or, even though I'm now a member you might still have to add me and give me "write" access to the specific repository.
> 
> Anyhow, in the meantime I've gone ahead and merged these changes directly.

@thinkyhead: I feel your pain. A lot of things are behaving sub-optimally since I moved the repo to the organization. Like when I try to do a PR, it always gives me a timeout with a unicorn error page. I have to manually go to the Marlin repo and select which branches for fork. I'm not sure why so many things are broken -- maybe something got borked in the transition and I need to delete this repo and start it again.

I'll give you write access to see if it helps.

**Pull request closed without merging**
