### PR TITLE
[2.0.x] Remove STM32 board specific delays

### PR DESCRIPTION
**Pull request by ktand**
### Remove STM32 board specific delays and replace with delays for all HAL_STM32 boards.

`ultralcd_st7920_u8glib_rrd_AVR.cpp` currently has delay definitions for two STM32 boards, REMRAM and ARMED. Compiling for any other STM32 board will fail with an error:

"No valid condition for delays in 'ultralcd_st7920_u8glib_rrd_AVR.h'"

This PR replaces the board specific delay defines with generic defines for all boards using the HAL_STM32.

### Related Issues

#12234

### CODE REVIEW

**Comment by AnHardt** [comment]
Either these STM32s are super duper hyper slow (slower than  AVRs) in setting pins or they will need real (different from 0) delays.

**Comment by ktand** [comment]
Working fine here with zero delays, so it must be the pins then 😀

**Comment by p3p** [comment]
Well the more generic the code the slower it is I guess, and the STM32 platforms seem to use the (usually slow) Arduino methods in the HAL FastIO api which is supposed to be .. fast, so it completely depends on the upstream implementations performance.

**Comment by AnHardt** [comment]
So about any trick we used to bypass Aruiono and finding special, faster solutions for the AVRs has to be redone for the STs. to make them equally fast as the AVRs? :-(
I'll make some tests.

**Comment by AnHardt** [comment]
[Oh god!](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_STM32/fastio_STM32.h#L32_L33)

**Comment by thinkyhead** [comment]
> Oh god!

Yep, looks like STM32 FastIO isn't doing any fast I/O.

**Comment by hasenbanck** [comment]
Cross referencing the issue of GPIO performance in the STM32 core 
https://github.com/stm32duino/Arduino_Core_STM32/issues/274

**Comment by ktand** [comment]
FYI, I have submitted a PR for faster IO access. Your feedback is welcome!

https://github.com/MarlinFirmware/Marlin/pull/12276

**Pull request merged**
