### PR TITLE
Load settings after showing bootscreen

### PR DESCRIPTION
**Pull request by dbuezas**
### Description

In my I2C LCD, the screen shows noise for a couple of seconds when powered on. This is because the LCD is turned on but nothing is drawn until the eeprom settings are loaded (which takes a couple of seconds).

Showing the bootscreen before loading eeprom solves this glitch and it also reduces total load time, since the boot animation can run concurrently with the eeprom read.

### CODE REVIEW

**Comment by ellensp** [comment]
What about lcds that have a settable contrast and brightness in eeprom?

```
  //
  // HAS_LCD_CONTRAST
  //
  uint8_t lcd_contrast;                                 // M250 C

  //
  // HAS_LCD_BRIGHTNESS
  //
  uint8_t lcd_brightness;                               // M256 B

```

**Comment by dbuezas** [comment]
At least in my screen it gets corrected right after. It is still a lot better than before, let me make a video

**Comment by ellensp** [comment]
Im concerned about everyone screen, not just yours.

For some this will result in a non visible or overly bright boot screen

**Comment by dbuezas** [comment]
If you turn on the sound, you can also hear the probe doing it startup routine (automatic when power is turned on), and one can also see that the screen finishes loading quicker.

## Before

https://github.com/MarlinFirmware/Marlin/assets/777196/92f48292-f073-4c1b-8f02-62905574d087


## After

https://github.com/MarlinFirmware/Marlin/assets/777196/5c2ffcd1-9bd8-4c23-a111-ef92e27cfcc7

**Comment by dbuezas** [comment]
> Im concerned about everyone screen, not just yours.

Good point, I didn't see any reasons for concern myself, but I also only know my machine so happy to hear feedback.
I was hoping the improvement may generalise to others, but understand that may not be the case.

**Comment by thisiskeithb** [comment]
> What about lcds that have a settable contrast and brightness in eeprom?

That's the exact thing I was going to mention as well. If the user's preferred values are stored in EEPROM, then this PR is a step backward for them.

**Comment by dbuezas** [comment]
Do other LCDs also show noise at startup?
Maybe it would be best to add a call to paint a blank screen right ~~before~~ after initing the LCD to clear the ram.

**Comment by thisiskeithb** [comment]
> Do other LCDs also show noise at startup?

Some do, some don't.

**Comment by thinkyhead** [comment]
> Maybe it would be best to add a call to paint a blank screen right ~before~ after initing the LCD to clear the ram.

See if adding a call to `clear_lcd()` at the end of `MarlinUI::init_lcd` eliminates the noise.

Some LCDs have a shared SPI with the SD card, and this can sometimes generate extra noise, but it could also be something like a floating pin. Earlier initialization of all pin modes could fix it, but in the meantime a quick clear after init might be enough.

**Comment by ellensp** [comment]
An option might be to read just the lcd settings form the eeprom before the boot screen when required, then the full eeprom read later

**Comment by dbuezas** [comment]
> See if adding a call to clear_lcd() at the end of MarlinUI::init_lcd eliminates the noise.

I tried that and unfortunately it had no effect, looking closer, DOGM implementation is a noop `void MarlinUI::clear_lcd() { } // Automatically cleared by Picture Loop`

**Comment by dbuezas** [comment]
> An option might be to read just the lcd settings form the eeprom before the boot screen when required, then the full eeprom read later

Since the eeprom is not indexed, we'd need to run all the load routines to increment the address to the right one.

I think clearing the screen first would be a good compromise: eeprom read won't happen in parallel to the bootscreen animation, but at least no noise. The issue is that not all LCDs implement the clear_lcd function.

I do wonder if having the default brightness/contrast for a couple of seconds is worse than spending the same time with a garbled screen. The latter looks very ugly/broken (and also runs with default brightness/contrast).

**Comment by dbuezas** [comment]
Another easy fix could be to immediately send the lcd to sleep while the eeprom is read, and wake it up right after, although I don't know if all lcds will take configurations while asleep. Anybody knows?

**Comment by thisiskeithb** [comment]
> I do wonder if having the default brightness/contrast for a couple of seconds is worse than spending the same time with a garbled screen. The latter looks very ugly/broken (and also runs with default brightness/contrast).

While both are bugs and only visible briefly during the boot process, potential garbage on the LCD (with proper brightness & contrast) is better than a screen without a visible bootscreen/screens.

> Another easy fix could be to immediately send the lcd to sleep while the eeprom is read, and wake it up right after, although I don't know if all lcds will take configurations while asleep. Anybody knows?

Most displays don't support the sleep feature and display sleep is disabled by default.

**Comment by dbuezas** [comment]
I see.

> potential garbage on the LCD (with proper brightness & contrast) 

Actually in my display the garbage is shown at whatever default contrast/brightness the lcd has.

**Comment by thinkyhead** [comment]
How about the commits I just added: do these help?

**Comment by dbuezas** [comment]
> How about the commits I just added: do these help?

No more noise, but the boot animation is also gone

**Comment by dbuezas** [comment]
Note: I have a zero bootscreen timeout so eeprom loading ends almost at the same time as the animation and I get the snappiest boot.

```cpp
    #define BOOTSCREEN_TIMEOUT 0
    #define BOOT_MARLIN_LOGO_ANIMATED
```

Trying with 2000 now to check if only the animation is gone or also the bootscreen

**Comment by dbuezas** [comment]
Disabling boot animation doesn't bring back the boot screen either

**Comment by thinkyhead** [comment]
Any difference noted by moving the `clear_lcd()` call to different points within `MarlinUI::init_lcd` ?

**Comment by thinkyhead** [comment]
On a related note, does the noise always appear on your particular LCD regardless of how large you set the `ST7920_DELAY_1`/`2`/`3` values to be? At the extreme, some boards will set these as high as `250`, `250`, `250` just to work around their innate noise.

**Comment by thinkyhead** [comment]
I moved the call to `MarlinUI::init` after the call to `init_lcd()`, so all LCDs will get cleared immediately after device init.

**Comment by thinkyhead** [comment]
i2c!

**Comment by thinkyhead** [comment]
We'll get this right eventually. Some displays like to clear the background before drawing, so that's the added method that displays can implement according to need. If a display doesn't need to clear, or shouldn't clear in this case (due to u8g paging) then the method will just be empty and clearing will occur as part of the next draw. Displays that always clear themselves before drawing end up calling through to `clear_lcd` as before.

**Comment by thinkyhead** [comment]
I don't see anything particularly troublesome happening if we load (or potentially reset and save) settings from EEPROM *after* the "wired LCD" bootscreen is displayed, so that change is restored for additional testing.

ExtUI displays will call `onSettingsLoaded` after EEPROM load, which may send additional data to the display. It doesn't appear this is problematic for any particular display, but it's something to consider since most features aren't initialized at that point during `setup()`.

**Comment by ellensp** [comment]
"Since the eeprom is not indexed, we'd need to run all the load routines to increment the address to the right one."

No... just needs a bit of creativity...

eg
```DIFF
diff --git a/Marlin/src/MarlinCore.cpp b/Marlin/src/MarlinCore.cpp
index 63e20842bb..7d48f54fbb 100644
--- a/Marlin/src/MarlinCore.cpp
+++ b/Marlin/src/MarlinCore.cpp
@@ -1334,14 +1334,15 @@ void setup() {
     SETUP_RUN(card.mount());          // Mount media with settings before first_load
   #endif
 
-  SETUP_RUN(settings.first_load());   // Load data from EEPROM if available (or use defaults)
-                                      // This also updates variables in the planner, elsewhere
-
   #if ALL(HAS_WIRED_LCD, SHOW_BOOTSCREEN)
+    SETUP_RUN(settings.lcd_load());
     SETUP_RUN(ui.show_bootscreen());
     const millis_t bootscreen_ms = millis();
   #endif
 
+  SETUP_RUN(settings.first_load());   // Load data from EEPROM if available (or use defaults)
+                                      // This also updates variables in the planner, elsewhere
+
   #if ENABLED(PROBE_TARE)
     SETUP_RUN(probe.tare_init());
   #endif
diff --git a/Marlin/src/module/settings.cpp b/Marlin/src/module/settings.cpp
index a9f2f888bf..e95978536e 100644
--- a/Marlin/src/module/settings.cpp
+++ b/Marlin/src/module/settings.cpp
@@ -2967,6 +2967,22 @@ void MarlinSettings::postprocess() {
     return (err == ERR_EEPROM_NOERR);
   }
 
+  void MarlinSettings::load_contrast() {
+        EEPROM_START(EEPROM_OFFSET+offsetof(SettingsData,lcd_contrast));
+        uint8_t lcd_contrast;
+        EEPROM_READ(lcd_contrast);
+        //DEBUG_ECHOLNPGM("LCD Contrast: ", lcd_contrast);
+        TERN_(HAS_LCD_CONTRAST, ui.contrast = lcd_contrast);
+  }
+
+  void MarlinSettings::load_brightness() {
+        EEPROM_START(EEPROM_OFFSET+offsetof(SettingsData,lcd_brightness));
+        uint8_t lcd_brightness;
+        EEPROM_READ(lcd_brightness);
+        //DEBUG_ECHOLNPGM("LCD Brightness: ", lcd_brightness);
+        TERN_(HAS_LCD_BRIGHTNESS, ui.brightness = lcd_brightness);
+  }
+
   bool MarlinSettings::load() {
     if (validate()) {
       const EEPROM_Error err = _load();
diff --git a/Marlin/src/module/settings.h b/Marlin/src/module/settings.h
index b7c5210db5..e737ba3da3 100644
--- a/Marlin/src/module/settings.h
+++ b/Marlin/src/module/settings.h
@@ -64,6 +64,8 @@ class MarlinSettings {
     #if ENABLED(EEPROM_SETTINGS)
 
       static bool load();      // Return 'true' if data was loaded ok
+      static void load_contrast();
+      static void load_brightness();
       static bool validate();  // Return 'true' if EEPROM data is ok
 
       static void first_load() {
@@ -71,6 +73,11 @@ class MarlinSettings {
         if (!loaded && load()) loaded = true;
       }
 
+      static void lcd_load() {
+       TERN_(HAS_LCD_CONTRAST,load_contrast());
+       TERN_(HAS_LCD_BRIGHTNESS,load_brightness());
+      }
+
       #if ENABLED(AUTO_BED_LEVELING_UBL) // Eventually make these available if any leveling system
                                          // That can store is enabled
         static uint16_t meshes_start_index();
```

This is just a draft
lcd_load should probably check eeprom version number first before loading other data from  eeprom

**Comment by dbuezas** [comment]
@thinkyhead Just tested head (https://github.com/MarlinFirmware/Marlin/pull/27199/commits/142cecf40b81e7be4b7fb58ce60858b648dfe41f) and I still have no boot animation or screen

**Comment by dbuezas** [comment]
@ellensp I think your solution is the best one.

In your patch you forgot calling `ui.refresh_contrast()` and `ui.refresh_brightness()`, so the effect was exactly the same as my original change (boot screen started with default contrast and was corrected when all settings are loaded).

I made a branch based on your patch that adds the settings version check and the calls to `ui.refresh_xxx` and it works great:
* Startup is snappy (boot animation loads earlier and runs in parallel with the full eeprom read. The printer is ready to go earlier than in bugfix)
* No noise screen on power cycles
* Stored contrast/brightness are applied correctly from the first frame.

Here's the commit: https://github.com/MarlinFirmware/Marlin/commit/fa1cc762257b8b514330b590f880c7066abe1b35

@thinkyhead Please let me know if I should open another PR with that, force push on this one, ...

**Comment by thinkyhead** [comment]
What happens when `MarlinSettings::load_contrast` is called for an incompatible or uninitialized EEPROM? That case should be handled.

We have an ongoing **Project** to rework the EEPROM so that each feature defines its settings with an ID, version, and datasize, and each gets its own checksum and localized handling. So I hesitate to implement that as a special case when we'll be ripping out this code imminently for **Features**.

Perhaps this is a good moment to dive into that EEPROM rework Project and git 'er done….

**Comment by ellensp** [comment]
This is why it checks for the current eeprom version string. so its not uninitialized or wrong version.  It can of course still have invalid data or corruption, but to check the checksum and your back to slow screen start due to having to read all the eeprom.

**Comment by thisiskeithb** [comment]
> Perhaps this is a good moment to dive into that EEPROM rework Project and git 'er done….

Let's get `2.1.3` out first 😄

**Comment by dbuezas** [comment]
> What happens when MarlinSettings::load_contrast is called for an incompatible or uninitialized EEPROM? 

If the version check doesn't pass then nothing happens.

I guess the worse that can happen is that the eeprom is corrupted and the lcd contrast is initialized to zero.

**Comment by ellensp** [comment]
If eeprom version doesn't match we could default to LCD_CONTRAST_DEFAULT  and LCD_BRIGHTNESS_DEFAULT  

Same as in settings.cpp

```
  //
  // LCD Contrast
  //
  TERN_(HAS_LCD_CONTRAST, ui.contrast = LCD_CONTRAST_DEFAULT);

  //
  // LCD Brightness
  //
  TERN_(HAS_LCD_BRIGHTNESS, ui.brightness = LCD_BRIGHTNESS_DEFAULT);

```

**Comment by dbuezas** [comment]
I think it is already initialized to that, but we could reset them to default if the crc doesn't match later in the full eeprom read. Then the only side effect a corrupted eeprom would have is a couple of seconds with random contrast

**Comment by thinkyhead** [comment]
In adapting the suggested changes I did apply the defaults for the case where the EEPROM version is incorrect, and I made the new code block conditional on having early-settable brightness or contrast.

For the moment I removed the `clear_lcd` refactor so the early init of brightness and contrast can be tested in isolation, but there is no harm in having some extra clear at boot time. The only drawback to all our extra startup details is that the baseline build size for common peripherals continues to expand….

**Comment by dbuezas** [comment]
Thanks @thinkyhead, it's a very tricky balance indeed.

**Comment by thinkyhead** [comment]
Thanks everyone for bringing your best stuff. Every day in every way we're getting better and better.

**Comment by ellensp** [comment]
Looks great, I have no issue with this anymore, this should keep everyone happy.

**Comment by thisiskeithb** [comment]
Using current `bugfix-2.1.x` (9240ec8) / after recent LCD changes, part of the custom bootscreen is now missing:

image

<br/>

<br/>

Adding changes from this PR doesn't fix it.

If I revert 1f9fc66, then the bootscreen looks normal again.

edit: While working on another issue with an MKS Eagle with `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`, there are *no* bootscreens and the LCD doesn't display anything until the main status screen is ready.

**Comment by thinkyhead** [comment]
> If I revert … then the bootscreen looks normal again.

Sounds like the clearing of the screen is leaving the color set to 0 and this is unexpected. Perhaps U8G always sets the color to 1 at initialization and that was taken for granted by boot screen drawing. If that be the case, the solution might just be to put `u8g.setColorIndex(1)` at the end of `MarlinUI::clear_lcd` for DOGM.

**Comment by thijstriemstra** [comment]
thanks for fixing this annoying glitch, can confirm it's fixed with mini1284 display. 

Before picture: image

After: properly shows black screen followed by boot image and menu.

**Comment by thisiskeithb** [comment]
This PR created a new bug:

- https://github.com/MarlinFirmware/Marlin/issues/27236

...which can lead to some extremely unsafe behaviors:

- https://github.com/MarlinFirmware/Marlin/issues/27253

**Comment by dbuezas** [comment]
I think the bug is here https://github.com/MarlinFirmware/Marlin/pull/27199/files#diff-3b2c0da2300fa99c611618bb2d1a9f7e81edb092aac5d49c83a6d9068561838cR1826
Probably part of of this commit [Use EEPROM_Error](https://github.com/MarlinFirmware/Marlin/pull/27199/commits/e7f1d96cdfa6d8a77bd862135741e96d29f0980d)

It looks like it shouldn't return the error in this case, it should only set the eeprom_error variable and continue (I assume the settings are reset later in that fn)

It should only return early if ERR_EEPROM_NOPROM, in which case it used to return ERR_EEPROM_NOERR

I believe the fix is to change, 
```cpp
    if (check == ERR_EEPROM_VERSION) return eeprom_error;
```

to 
```cpp
   if (check == ERR_EEPROM_NOPROM) return ERR_EEPROM_NOERR;
```

to match behaviour before that commit

**Comment by ellensp** [comment]
similar conclusion I just came to https://github.com/MarlinFirmware/Marlin/issues/27236#issuecomment-2217671913 only to find this saying the same thing

**Comment by thisiskeithb** [comment]
Both https://github.com/MarlinFirmware/Marlin/pull/27199#issuecomment-2217460127 & https://github.com/MarlinFirmware/Marlin/issues/27236#issuecomment-2217671913 work.

**Pull request merged**
