### PR TITLE
Fix M112

### PR DESCRIPTION
**Pull request by Vertabreak**
should close a few issues. 
this makes M112 do what the wiki says it should do.
disables steppers & heaters & kills the printer.
before it only killed the printer and heaters.

### CODE REVIEW

**Comment by boelle** [comment]
#14863
#14599

**Comment by sjasonsmith** [comment]
I'm not sure this is the correct fix.

With the new code, all steppers are disabled when when `steppers_off` is false, which seems incorrect. In addition to stopping all steppers on M112, it will also kill them all from a watchdog expiration (the only the caller to `minkill`).

If stopping all steppers on watchdog expiration is desirable, then the `steppers_off` serves no purpose, and a little more cleanup would be warranted to remove it. Someone else will need to chime in to say whether changing the behavior on watchdog reset is desired.

Assuming that the `steppers_off` argument is wanted, then I think the problem is in `temperature.cpp: Temperature::manage_heater`. When `killed_by_M112` is true this calls `kill()`, which does not set `steppers_off`. It should probably instead call  `kill(null_ptr, null_ptr, true)`. This should fix the M112 issue without changing the watchdog behavior.

**Comment by Vertabreak** [comment]
if there is a better way by all means @boelle asked me to have a look i did.
tested the issue it was disabling just E so i flipped them and then it functioned the way it was described.

**Comment by sjasonsmith** [comment]
Looking at the code more closely, I think the original code probably worked correctly if EMERGENCY_PARSER is disabled, and incorrectly if EMERGENCY_PARSER is enabled. That is now switched, so it fixed one case, but likely broke the other.

Without EMERGENCY_PARSER, M112 does the following:
`kill(PSTR("M112 Shutdown"), nullptr, true);`

With EMERGENCY_PARSER enabled, it behaves differently:
1. Set `killed_by_M112 = true`
2. Wait for temperature.cpp to pick up `killed_by_M112`
3. Call `kill();`

To fix this, I think you just need to do the following:
1. Revert the change from this file
2. Modify `Temperature::manage_heater()` to call `kill` the same way it is called by the "normal" MM12 command (`kill(PSTR("M112 Shutdown"), nullptr, true);`)

**Comment by sjasonsmith** [comment]
Based on my comments @Vertabreak tested both with and without EMERGENCY_PARSER, and sees the same behavior in both cases. I am currently confused why this is, since M112() clearly calls kill() differently than Temperature::manage_heater does.

I am going to try it out on one of my printers and try to figure out how to reconcile what I am reading in code with what the printer actually does.

**Comment by sjasonsmith** [comment]
So I've lost a little more hair over this one.

As it turns out, there are three different places that M112 is processed.

1. EMERGENCY_PARSER Enabled over serial - does not pass `steppers_off`, and was fixed by @Vertabreak's change
2. EMERGENCY_PARSER Disabled over serial - does not pass `steppers_off`, and was fixed by @Vertabreak's change
3. "Normal" M112() command, used when printing from SD - passes `steppers_off=true`. I thought @Vertabreak's change might invert that behavior, but it always disabled my steppers, no matter what I have tried (probably more to do with finishing my one-line file than the actual M112). At this point I think the fix in this PR is incorrect  in this case, but this case is also pretty absurd.

It took a while to realize that both numbers 2/3 above existed.

**I still think this change will cause new behavior when the watchdog expires. If that is ok, we should just strip out this 'steppers_off' stuff and simplify the code.**

**Comment by thinkyhead** [comment]
It looks to me like this is the only fix needed:
```diff
-         if (strcmp(command, "M112") == 0) kill();
+         if (strcmp(command, "M112") == 0) kill(PSTR("M112 Shutdown"), nullptr, true);
```

**Pull request closed without merging**
