### PR TITLE
[2.0.x] Remote streamer fixes for G29_RETRY_AND_RECOVER (#12982)

### PR DESCRIPTION
**Pull request by marcio-ao**
- Follow up to "Remote streamer improvements (#12982)"
- Fix compilation error when using G29_RETRY_AND_RECOVER
- Added host_action_probe_failure() and host_action_probe_recover() in line with other actions
- Renamed G29_ACTION_ON_RECOVER to ACTION_ON_G29_RECOVER
- Renamed G29_ACTION_ON_FAILURE to ACTION_ON_G29_FAILURE

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
@marcio-ao Any issue if I bring these changes into #13039 instead? If you look over there, I took the action commands out of configuration_adv.h and defined the "standards". Id like to do the same with these. As a side note, id like to change the filament runout action definition to simply be "reason" and extend the pause action with the pause reason. It shouldn't make a change in what you see, but it should prevent fragmentation of the definitions. Any objection?

**Comment by marcio-ao** [comment]
@InsanityAutomation: No objections. The purpose of this PR was simply to make it resemble the work you had already done elsewhere, but if you're still changing things, that's fine :)

**Comment by InsanityAutomation** [comment]
@marcio-ao some if it, like adding the helper functions here, was actually @thinkyhead making changes under my changes so that part at least is his. Easy enough though, ill get these parts pulled over and matching then ping you when its up so we can make sure i didnt miss anything and kill this one.

**Comment by InsanityAutomation** [comment]
@marcio-ao that should cover this at least - Also, can you define the actions you expect the host  to take, if any aside from showing a prompt, when these are received so we can update the reprap wiki with full documentation on the defined commands? This past week or so we have been trying to ensure all parties have a full understanding of everything in use right now. If these are synonymous with the prompt commands, Ill either add a standard prompt around it, or if youre solution supports prompts they can be replaced.

**Comment by marcio-ao** [comment]
@InsanityAutomation: At the moment, on probe_failure, Cura will simply pop up an alert and stop the print. On probe_recover,  it will simply let the user know it the printer is rewiping.
In the case of filament_runout, Cura pauses the print.

**Comment by InsanityAutomation** [comment]
Ok, then failure should be combined with the cancel action command with the probe_failure reason string added, and probe_recover should be combined with a normal prompt dialog.

Do you have support for the cancel action command in your cura branch atm?

**Comment by marcio-ao** [comment]
@InsanityAutomation: No, cancel is not supported. To be honest, at this point I will probably end up tweaking our FW to do what it has always done before, as we need to maintain compatibility with prior firmwares, at least until Marlin 2.0 is released and we can transition all the printers to it.

**Comment by InsanityAutomation** [comment]
Ok, just added the dialogs and cancel next to those for support with standard definition. Still need to modify the functions to take a reason argument and print it, then ill go around adding those where it makes sense.

**Comment by marcio-ao** [comment]
> failure should be combined with the cancel action command with the probe_failure reason string added
> probe_recover should be combined with a normal prompt dialog.

I'm not sure I agree with your approach. What if the desired response to a probe failure is not a cancellation and the desired behavior for a probe fail is something other than a dialog box? I believe Marlin should tell the host what *has happened* and let the host decide what *the behavior* should be.

You are turning it around and having Marlin tell the host what to do in those cases.

**Comment by InsanityAutomation** [comment]
@marcio-ao The prompt I configured for rewiping is nothing but a message, and doesn't replace the defined action. Its is informational to tell the host what has happened as you said. I have no response actions defined for this, and its just a dialog shown.

For the failed, im not sure I get the difference between what its doing now and adding the command equivalent octoprint supports.

**Comment by InsanityAutomation** [comment]
@marcio-ao That said, I could prompt on failure if kill on failure is not set for retry or abort and process that response to either re enqueue G29 or send cancel. That doesnt do anything different on the cura side since you dont support cancel and are already stopped on the failed response though.

**Comment by marcio-ao** [comment]
> For the failed, im not sure I get the difference between what its doing now and adding the command equivalent octoprint supports.

The difference is the difference between an event and a behavior. I believe Marlin should tell the host what has happened (an event), not tell it what to do (a behavior).

When a filament runs out, I believe that condition should be indicated to the host, but it should not dictate a behavior (pausing the print).

Similarly, if a probe fails, I believe that condition should be indicated to the host (an event), but it should not dictate a behavior (cancelling the print).

While in these simple cases it does not make much difference, I think it is important to make clear who is in control. If the host is printing, it should be in control of what Marlin does, not the opposite way around. I think by conflating events with behaviors risks making things less flexible in the future.

**Comment by InsanityAutomation** [comment]
@marcio-ao Considering the typical action here is kill, which forces a full stop regardless of if the host is in control, requesting a graceful stop is still preferred. From the host side, if they choose to ignore it when the reason code is probing_failed thats still up to them and doesnt force anything. 

Setting a busy state here and blocking for a prompt response is one method of containing it prior to calling kill, but an LCD dialog would also be necessary to get out of the held state. In this case its a machine failure and there should be a degree of control on both sides of what can occur for safety sake.

Same with my though of setting the host printing pause action to a non-parking M25 as all that does in this scenario is pause timers and show prompts, and all gcode will still be executed normally. It simply ensures compatibility with the discussion with @foosel and @repetier and still does not prevent the host from making all decisions as it desires.

**Comment by marcio-ao** [comment]
> That said, I could prompt on failure if kill on failure is not set for retry or abort and process that response to either re enqueue G29 or send cancel.

I appreciate what you are trying to do, but I think this is placing the intelligence in the wrong place. It is dangerous for Marlin to make assumptions about what the host may want to do and how it may make sense to do it.

The reason I have a differing opinion on this is because a similar problem exists with the UltraLCD code. In things like the filament change, Marlin is executing all sorts of complex logic. I had to bypass all of that in our touch UI code because the existing logic simply didn't map all that well to a touch UI.

The exact same problem will crop up if you make Marlin control the host. You will need to anticipate all future use cases and things can get convoluted if you make the wrong choices. This is why I think it is best to keep it as simple as possible and simply reports events, while leaving behavior up to the host.

**Comment by InsanityAutomation** [comment]
@marcio-ao Thats a big part of why the current work is removing the LCD dependency on M600 and allowing a gcode method to control the actions back. This should greatly alleviate that situation, especially with M876 in the emergency parser to handle responses to blocking situations.

**Comment by InsanityAutomation** [comment]
@marcio-ao I should probably also note that the only places im putting in prompts with options and responses is where the machine already blocks the host. Im trying to better handle whats already there, and create paths forward that dont necessarily need more of it. 

Im only in support of the machine telling the host what to do in error scenarios where it is not really safe to continue. For example, TMC drivers with uart/spi can report when theyve been shutdown either by thermal overload or stallguard. In this case, those axis cant physically move and still pumping material out the hotend is a recipe for damage. Machine telling the host to stop (either pause or cancel if the situation cant be resolved) should be expected. For safety sake, here I would set a busy state, when overheat condition is gone, allow the user to attempt a recover action (predefined, but probably something like raise 5mm, home xy, return to expected position) and resume if successful or just cancel.

In what I consider safety scenarios, im inclined to expect both sides to attempt safe handling in some fashion.

**Comment by marcio-ao** [comment]
> From the host side, if they choose to ignore it when the reason code is probing_failed thats still up to them and doesnt force anything.

Ahhh, but this is the sort of ambiguity that can eventually bite you in the... uh... extruder. When Marlin is telling the host to do something, then there should not be any possibility that its optional, because this means Marlin is expecting the action to happen. If you acknowledge that the host is free to do whatever it wants, then it's a hint that you shouldn't be telling it _what to do_ in the first place, but rather telling it _what has happened_ so it can decide how to act.

There is a lot of work related to such things in the world of GUI design. It is rather common in the design of such APIs to make a clear distinction between events and event handlers. An event tells what has happened, but the event handler is up to the user. I am merely proposing that Marlin has a similar division. There are events (filament_run_out, probe_failed), but the host should be free to decide what to do in such cases.

That said, it is okay for there to be non-event things, in the case that Marlin *really* needs to tell the host exactly what to do. The dialog boxes you speak of are an example of this, they are more akin to a remote procedure call, an explicit request for the host to do something.

Perhaps there needs to be a clear distinction between the two. There could be "//event:" and "//action:". An "//event:" means that something happened and Marlin is deferring to the host on what should happen. An "//action:" is a specific request that the host do something.

Perhaps the way it could work is that "//event:" is always sent, but if ACTION_ON_FILAMENT_RUNOUT is #defined to "cancel", then Marlin will send that "//action:" as well.

**Comment by InsanityAutomation** [comment]
@marcio-ao From the host side, the prompt is still an action to take but I see youre point. There is no distinction between a plain informational prompt and one which can send responses. Right now, the only two places I have cancel is the LCD stop button (user explicitly picked and and we explicitly want to send that to the host) and with the probing failed. I will likely add it to the messages around KILL called as well, but thats just for consistency.

As for marlin expecting the action to happen, currently there is no real assumption it has done anything anywhere. If the host doesnt support the prompt actions, then its still blocking until resolved from the lcd like normal on M600 and M125. Anything else but cancel is just showing a message. Its requesting the action, but not necessarily reliant on it occurring. Cancel might be the only one of the commands to consider enforcing, but the only way to reliably do so is with kill, or an M876 response to acknowledge, remove the busy state, and just purge the queue. Digging that far down the rabbit hole is beyond the intention this week :)

**Comment by marcio-ao** [comment]
@InsanityAutomation: Let me propose a compromise. I can always edit code and modify our FW in whatever way makes sense for us, so the one thing that would be tremendously helpful is that if in the Marlin code, there were functions corresponding to each event that I could easily edit. In Marlin.cpp, there  currently are the following functions:

#if HAS_ACTION_COMMANDS

  void host_action(const char * const pstr, const bool eol=true) {
    SERIAL_ECHOPGM("//action:");
    serialprintPGM(pstr);
    if (eol) SERIAL_EOL();
  }

```
#if HAS_ACTION_COMMANDS
  void host_action(const char * const pstr, const bool eol=true) {
    SERIAL_ECHOPGM("//action:");
    serialprintPGM(pstr);
    if (eol) SERIAL_EOL();
  }

  #ifdef ACTION_ON_KILL
    void host_action_kill() { host_action(PSTR(ACTION_ON_KILL)); }
  #endif
  #ifdef ACTION_ON_PAUSE
    void host_action_pause() { host_action(PSTR(ACTION_ON_PAUSE)); }
  #endif
  #ifdef ACTION_ON_PAUSED
    void host_action_paused() { host_action(PSTR(ACTION_ON_PAUSED)); }
  #endif
  #ifdef ACTION_ON_RESUME
    void host_action_resume() { host_action(PSTR(ACTION_ON_RESUME)); }
  #endif
  #ifdef ACTION_ON_RESUMED
    void host_action_resumed() { host_action(PSTR(ACTION_ON_RESUMED)); }
  #endif
  #ifdef ACTION_ON_CANCEL
    void host_action_cancel() { host_action(PSTR(ACTION_ON_CANCEL)); }
  #endif
  #ifdef ACTION_ON_FILAMENT_RUNOUT
    void host_action_filament_runout(const bool eol/*=true*/) { host_action(PSTR(ACTION_ON_FILAMENT_RUNOUT), eol); }
  #endif
  #ifdef ACTION_ON_G29_FAILURE
    void host_action_probe_failure() { host_action(PSTR(ACTION_ON_G29_FAILURE)); }
  #endif
  #ifdef ACTION_ON_G29_RECOVER
    void host_action_probe_recover() { host_action(PSTR(ACTION_ON_G29_RECOVER)); }
  #endif
#endif // HAS_ACTION_COMMANDS
```

Instead, why not make the last few function event handlers and make them always present. In the case in which an action is defined, they trigger an appropriate action:

```
  #if HAS_ACTION_COMMANDS
    void host_action(const char * const pstr, const bool eol=true) {
      SERIAL_ECHOPGM("//action:");
      serialprintPGM(pstr);
      if (eol) SERIAL_EOL();
    }

    #ifdef ACTION_ON_KILL
      void host_action_kill() { host_action(PSTR(ACTION_ON_KILL)); }
    #endif
    #ifdef ACTION_ON_PAUSE
      void host_action_pause() { host_action(PSTR(ACTION_ON_PAUSE)); }
    #endif
    #ifdef ACTION_ON_PAUSED
      void host_action_paused() { host_action(PSTR(ACTION_ON_PAUSED)); }
    #endif
    #ifdef ACTION_ON_RESUME
      void host_action_resume() { host_action(PSTR(ACTION_ON_RESUME)); }
    #endif
    #ifdef ACTION_ON_RESUMED
      void host_action_resumed() { host_action(PSTR(ACTION_ON_RESUMED)); }
    #endif
    #ifdef ACTION_ON_CANCEL
      void host_action_cancel() { host_action(PSTR(ACTION_ON_CANCEL)); }
    #endif
  #endif
  
  void event_filament_runout() {
    #ifdef ACTION_ON_G29_FAILURE
      host_action(PSTR(ACTION_ON_FILAMENT_RUNOUT), eol);
    #endif
  }
 
  void event_probe_failure() {
    #ifdef ACTION_ON_G29_FAILURE
      host_action(PSTR(ACTION_ON_G29_FAILURE)); }
    #endif
  }
  
  void event_probe_recover() {
    #ifdef ACTION_ON_G29_RECOVER
      host_action(PSTR(ACTION_ON_G29_RECOVER));
    #endif
  }
```

The nice thing about this is that it makes it easy for anyone to modify the code if they don't like the action that is being called by default.

**Comment by InsanityAutomation** [comment]
I can also surround the default action outputs with ifndef so overloading them is simple. In this case, you could replace cancel with a prompt or something of that nature. 

I'm fine with the above as well, and I'll add that in along with the appropriate feature preprocessor checks on each.

**Comment by marcio-ao** [comment]
> I'm fine with the above as well, and I'll add that in along with the appropriate feature preprocessor checks on each.

Cool. I like that. I think as long as the code is easy to modify, there is really no reason to try to come up with a solution for all the different use cases up front.

Thanks for listening to all my feedback on this, I do appreciate all the work you've been doing!

**Comment by InsanityAutomation** [comment]
@marcio-ap np, it is very difficult to make things works seamlessly from both ends and as expected at all times! Dealing with the lock the LCD has had on things is definitely the most complex part. Anywhere else it's informational only really, an event trigger as you said.

Btw, have you tried adaptive fan slowing on your Aerostruder tool heads yet? Should be useful there!

**Comment by marcio-ao** [comment]
> Btw, have you tried adaptive fan slowing on your Aerostruder tool heads yet? Should be useful there!

I've enabled it in my 2.0.0 branch. Haven't tested it specifically, but no complaints from anyone, so that's good!

**Comment by marcio-ao** [comment]
> np, it is very difficult to make things works seamlessly from both ends and as expected at all times!

Writing serial code that works with Marlin is really difficult, when you throw in serial buffers, serial errors, lost command acknowledgements, emergency vs. regular commands, etc. I really wished Marlin shipped with its own "reference implementation" in Python that dealt with all this and was generic enough that it could be used for the various hosts out there with little modification. Good documentation is one thing, but working code would be even better.

**Comment by InsanityAutomation** [comment]
@marcio-ao The other PR is updated, if you dont have any issues with this portion, we can move discussion on the remaining bit of filament runout handling there and close this. I think thats the last thing im concerned with breaking your stuff with!

**Comment by marcio-ao** [comment]
@InsanityAutomation: Closing this in favor of your other PR.

**Pull request closed without merging**
