### PR TITLE
Add option ABORT_ON_SOFTWARE_ENDSTOP

### PR DESCRIPTION
**Pull request by DerAndere1**
### Description

optionally, allow to abort printing on moves beyond software endstops.

- M211 S1 H1  enables aborting on software endstop (requires ABORT_ON_SOFTWARE_ENDSTOP. 
- M211 S1 H0 disables the feature and restores default behaviour (just clamps movement to the software endstops)

### Requirements

- [MIN/MAX]_SOFTWARE_ENDSTOPS enabled
- [MIN/MAX]_SOFTWARE_ENDSTOP__n_ for at least one axis enabled
 
### Benefits

- Allows the user of more dangerous or more expensive machines to abort machining when software endstops are reached. 
- Abort on software endstops reduces waste

### Configurations

- `[MIN/MAX]_SOFTWARE_ENDSTOPS` enabled
- `[MIN/MAX]_SOFTWARE_ENDSTOP_*` for at least one axis enabled
- `ABORT_ON_SOFTWARE_ENDSTOP` enabled

### Related Issues

Discussed on discord

### CODE REVIEW

**Comment by EvilGremlin** [comment]
This is pointless, moves beyond software endstops are already impossible, this is whole point of them existing.

**Comment by DerAndere1** [comment]
I think on multi axis machines there can be collisions with the work piece if movement of rotational axes is clamped. There may even be situations where 3 axis mills collide with the work piece if the Z axis is clamped.

**Comment by thinkyhead** [comment]
I once added a loud beep (on a SCARA robot) to alert users when any unreachable coordinate was seen by `get_destination_from_command`, and that was handy for development. This is the kind of thing you'd really want to scan the whole G-code file in advance to check, so the user doesn't waste time on 90% of a print before some illegal coordinate arrives and aborts the print.

**Comment by DerAndere1** [comment]
Understood. Users that want this feature can have a look at my fork. Alternatively, users can solely rely on hardware limit switches by enabling `ENDSTOPS_ALWAYS_ON_DEFAULT` and disabling `(MIN/MAX)_SOFTWARE_ENDSTOPS`.

**Pull request closed without merging**
