### PR TITLE
add stm32 env to STM32F103RET6_creality 

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Add STM32F103RET6_creality_stm32 env

### Benefits

upgrading to stm32duino

### Configurations

Configuration files I used in test build
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6565768/Configuration.zip)

### CODE REVIEW

**Comment by ellensp** [comment]
Firmware doesnt work at all, as expected at this early stage. 
The question is how to move forward from here

**Comment by ellensp** [comment]
Controler board now boots and initalises serial ports (including LCD)  can now test fuctionality

**Comment by ellensp** [comment]
Seems to be working as exected

**Comment by ellensp** [comment]
2 hour 5 min test print, printed fine. No issues.  Good to go in my view.

**Comment by The-EG** [comment]
Saw this mentioned in Discord and gave it a go on my v4.2.7 board. 

Appears to work fine and as an added bonus, my lcd buzzer seems to be less distorted and the binary is over 20kb *smaller*.

edit:

Some specific config details:
 - UBL with manual probe
 - filament runout sensor
 - adjusted PWM settings for my part cooling fans (tested - working properly)

**Comment by thinkyhead** [comment]
Since we're phasing out the STM32F1 HAL and want to gauge our progress, I took the liberty to put "`_maple`" on the end of the Maple-based environments instead of adding "`_stm32`" to the new environments and to separate the remaining Maple-based environments into a new `ini` file.

**Comment by ellensp** [comment]
The maple split lost maple env:STM32F103RE

```
# STM32F103RE
#
[env:STM32F103RE]
platform          = ${common_stm32f1.platform}
extends           = common_stm32f1
board             = genericSTM32F103RE
monitor_speed     = 115200

```

**Comment by ellensp** [comment]
Something has gone wrong with the maple split
eg 
```CPP
#include "stm32f1/pins_BTT_SKR_MINI_V1_1.h" // STM32F1 
env:STM32F103RC_btt_stm32                  =>  env:STM32F103RC_btt
env:STM32F103RC_btt_512K_stm32             =>  env:STM32F103RC_btt_512K
env:STM32F103RC_btt_USB_stm32              =>  (valished) env:STM32F103RC_btt_USB     
env:STM32F103RC_btt_512K_USB_stm32         =>  (valished) env:STM32F103RC_btt_512K_USB
env:STM32F103RC_btt                        =>  env:STM32F103RC_btt_maple 
env:STM32F103RC_btt_512K                   =>  env:STM32F103RC_btt_512K_maple
env:STM32F103RC_btt_USB                    =>  env:STM32F103RC_btt_USB_maple 
env:STM32F103RC_btt_512K_USB               =>  env:STM32F103RC_btt_512K_USB_maple
```

**Comment by ellensp** [comment]
I see that env:STM32F103RC_btt_USB and env:STM32F103RC_btt_512K_USB dont compile, this is probably why

**Comment by GhostlyCrowd** [comment]
> I see that env:STM32F103RC_btt_USB and env:STM32F103RC_btt_512K_USB dont compile, this is probably why

the usb has to be fixed its mentioned here https://github.com/MarlinFirmware/Marlin/pull/21488#issuecomment-812658589 why its not working at the moment.

**Comment by ellensp** [comment]
yes, waiting on https://github.com/MarlinFirmware/Marlin/pull/22025

**Pull request merged**
