### PR TITLE
Add option to reset print statistics in prepare menu

### PR DESCRIPTION
**Pull request by Kaibob2**

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'm inclined to agree. I don't think we want to include this, sorry! And in future, if you wish to contribute, please pay attention to code formatting, indentation, etc.

**Comment by Kaibob2** [comment]
Ok, i see, this makes perfect sense. I will keep it in my branch as long as i'm testing. As soon as the Printer and the firmware is in perfect condition i will delete it it too to avoid resetting it by accident. Sorry for coming up with this.

**Comment by thinkyhead** [comment]
Appreciated! Just not in line with our mysterious plans…

**Comment by jbrazio** [comment]
> "S78" is thought as a kind of pin-code - to protect from resetting the counters by someone not knowing the code.
> A menu item ruins that concept.

@Blue-Marlin is right, I made it as a "safe code".

**Pull request closed without merging**
