### PR TITLE
Enable bed thermistor as a default option

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Enable bed thermistor as a default option now that heated beds are standard & non-heated are rare.

The `Temporarily set "fail-fast: false" for testing` commit should be reverted, but is there to show that `DUE` and `mega2560` tests are failing for odd reasons. Hopefully someone smarter than me can identify why these two tests are failing.

Edit: I'm guessing https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/default has to also be updated because of the `restore_configs` step?

[`DUE` test failure message](https://github.com/MarlinFirmware/Marlin/actions/runs/5107203117/jobs/9179897708#step:7:154):

```prolog
Marlin/src/module/temperature.cpp:3500:31: error: 'temp_bed' was not declared in this scope
   TERN_(HAS_TEMP_ADC_BED,     temp_bed.update());
```

[`mega2560` test failure message](https://github.com/MarlinFirmware/Marlin/actions/runs/5107203117/jobs/9179897216#step:7:93):
```prolog
Marlin/src/HAL/AVR/../../inc/SanityCheck.h:1847:6: error: #error "REDUNDANT_PART_COOLING_FAN requires a board with at least two PWM fans."
```

### Benefits

Should cut down on the amount of questions we receive about the bed heater not showing on new builds.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Minor caveat: It increases the default build size by 2.4K.

**Comment by thisiskeithb** [comment]
The [`Temporarily set "fail-fast: false" for testing`](https://github.com/MarlinFirmware/Marlin/pull/25895/commits/8118137f8d44978b6e1fe72b874c114afe7608ec) commit has been reverted since only `DUE` is failing now.

**Comment by thinkyhead** [comment]
- First test (with `REDUNDANT_PART_COOLING_FAN`) failed because the Azteeg X3 pins file allocates fan pins based on the existence of a heated bed.
- Second test (DUE) failed because it was a test specifically expecting no heated bed ("EFF").

**Comment by thisiskeithb** [comment]
Got it.

Do you need a PR for the Configurations repo to update the default config over there?

**Comment by thinkyhead** [comment]
> Do you need a PR for the Configurations repo to update the default config over there?

If you wish. Otherwise I would add it myself. The default is originally based on a generic 3D printer resembling an original Ultimaker. In general, it is hoped to keep the default configuration small and have it apply to a minimal 3D printer. Historically, the cheapest and simplest hobbyist printers have been those using a cheap glass unheated bed. The other thing that is nice about the default not having a heated bed is that when you compare any config to the default, the heated bed sensor line is highlighted, so it is easily seen that the config has a heated bed. Now this line will only be highlighted if the bed thermistor is not 1, which is not as consistent as not 0. So, I'm not sure this specific configuration change to sensor 1 is truly essential.

**Comment by thisiskeithb** [comment]
Nostalgia is fun, but continuing to update the default config for modern printers & having fewer repeat support questions would be nice. I'll prep a PR.

**Pull request merged**
