### PR TITLE
[2.0.x] G33 kinematic auto tune factors

### PR DESCRIPTION
**Pull request by LVD-AC**
•updated convergence matrices
•kinematic auto tune scaling parameters
•raw calibration independent of Z-offset
•Z-offset calibration with G33 P-1 and G33 Zn.nn

### CODE REVIEW

**Comment by LVD-AC** [comment]
Leave a comment

**Comment by LVD-AC** [comment]
Leave a comment

**Comment by cdedwards** [comment]
just found this. bedlevel.h needs to be included in G33.cpp in order for it to compile. I'll test it out tomorrow. I like that there is a auto test for the probe. Not sure if I can use it or not, since I have a IR probe.

**Comment by cdedwards** [comment]
so far so good.  I re-downloaded the pr and am running a print right now with the values it picked yesterday with the old version. G33 P-1 however is a problem for me at least. it seems that the probe lifts 10mm up from the bed, and then we are supposed to lower the nozzle to touchdown on a piece of paper. Ok in theory, but my nozzle would not drop all the way down to the bed. I was aprox 2mm above it which is what my probe height is from the bed. 2.09mm. I have a IR sensor which is above the nozzle.

As soon as this print finishes, I'll run a G33 P10 and play around a little. I had to increase the M665 H value yesterday, but it was only a small amount.

**Comment by AnHardt** [comment]
@cdedwards 
Retink!
What matters is not the position of the sensor. What matters is the position of its trigger point. For sure this is below of your nozzle tip - else it could not trigger without drilling the nozzle into your bed.

@LVD-AC 
Is there a deeper sense in permanently closing and opening your PR? There are people receiving an e.mail, each time you do this.

**Comment by cdedwards** [comment]
@AnHardt I agree. however when G33 P-1 is used, it finds the trigger height by probing the bed, then raises up 10mm and waits for the user to dial in a height. I can not reach the bed as it's too far away or something. I get to about 2mm above the bed and it will not go any further. when I raise the nozzle at this point and try to go down more, it still will not and at this point the numbers are useless. They end up completely wrong.

**Comment by LVD-AC** [comment]
@AnHardt work in progress; just testing if it passes compile tests.

@cdedwards Only thing I can think off is your z-offset must be set initially quit off in Configuration.h; you should have it set to a negative number with an IR probe.

**Comment by cdedwards** [comment]
my M851 is set for -2.09. Near as I can tell, we probe the bed, raise upto Z_CLEARANCE_BETWEEN_PROBES which I have modified to 5mm from 10mm. nozzle is now 5mm above bed in theory. When I adjust the nozzIe down, it only goes as far as the Offset and then stops. I can rotate the values lower, but the nozzle will not move at all.  I also  attempted increasing this value to 15mm as well..

**Comment by LVD-AC** [comment]
@cdedwards This is very helpful. Got it... The probe triggers and puts the downwards motion to halt. I'll have a look where exactly I need to disable the end-stop detection to be able to go below the trigger point. Keep you posted.

**Comment by thinkyhead** [comment]
Software endstops don't apply when doing general motion within Marlin. They only apply to G-code movement commands. So the downward movement function call in `G33` simply has a bug. Or endstops have been left enabled and the probe is triggering, halting motion.

**Comment by LVD-AC** [comment]
@cdedwards  This will probably fix it

**Comment by LVD-AC** [comment]
@thinkyhead My effector didn't move down either when I triggered my probe with my finger. Adding `endstops.enable_z_probe(false)` just before the manual probe seems to have fixed that. Manual probes didn't have that problem in the past since they were only used on deltas without a probe that could be triggered.

**Comment by cdedwards** [comment]
// calculate factors
      if (_Zo_calibration) {
      #if HAS_BED_PROBE
        STOW_PROBE();
        endstops.enable_z_probe(false);
        z_shift = lcd_probe_pt(0, 0) - z_at_pt[CEN];
        endstops.enable_z_probe(true);
      #else
        z_shift = 0.0;
      #endif
    }

this was the only change made? it makes it easier since I don't know my way around git very well. I'm not sure how to re-pull a pr and then apply only the change I need to make

**Comment by LVD-AC** [comment]
Also added z-offset calibration to the lcd-menu

**Pull request closed without merging**
