### PR TITLE
Define more GT2560 fan pins

### PR DESCRIPTION
**Pull request by Vertabreak**
Define three FAN pins for GT2560.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
They were disabled in PR #13036, but no reason was given.

**Comment by Vertabreak** [comment]
so can we turn them back on then?

**Comment by shitcreek** [comment]
Let's ask @ratmole

**Comment by Vertabreak** [comment]
i have several users that make use of these pins on there GT2560V3 boards it just seems strange they would be turned off.

**Comment by shitcreek** [comment]
They weren't there before. @ratmole added them but, I guess, kept them disabled out of fear of conflicts.

**Comment by Vertabreak** [comment]
i have them enabled on both my A10 & A10M right now with zero conflict.

**Comment by shitcreek** [comment]
I understand. I'm just speculating the reasoning behind it. I'm in favor of enabling as those pins are clearly not  set to anything else in the pin file.

**Comment by Vertabreak** [comment]
just making it clear that i did verify it did not make anything explode on my own hardware.

**Comment by thinkyhead** [comment]
It may be that the current machines that ship with the GT2560 aren't using the other fans. By not defining the pins, the code ends up slightly smaller, without any reference to the unused fans. But it has been customary in Marlin to define all fan pins and compile in code for them even if they are not used.

**Comment by ratmole** [comment]
> Let's ask @ratmole

had them disabled because they where not used on my printer  :)

**Pull request merged**
