### PR TITLE
MBL: Disable sw endstops instead of altering Z

### PR DESCRIPTION
**Pull request by thinkyhead**
[Concise diff](https://github.com/MarlinFirmware/Marlin/pull/6031/files?w=1)

This PR removes the code from Mesh Bed Leveling which alters the Z position to work around software endstops. Instead, software endstops are simply disabled before and after each probe point's manual Z adjustment so that there is total freedom of movement.

Reference: https://github.com/MarlinFirmware/Marlin/issues/5885#issuecomment-284351106

### CODE REVIEW

**Comment by thinkyhead** [comment]
@epatel Please review and comment on this modification to MBL (after it passes Travis CI).

**Comment by epatel** [comment]
Sorry, I have no comments. Rather due to I am not familiar with the overall code anymore, and I can't say if things are put in or removed as required. Good luck to the testers!

**Comment by teemuatlut** [comment]
@thinkyhead  I was going to do a PR about this but I might as well post about it here.
The "soft_endstops_enabled" variable that you are also using in this PR, isn't actually used in anywhere else other than in _lcd_mode_xyz. So even after S211 S0, you can't go under XYZ_POS_MIN with gcode alone.

The variable is used only in three files;
Marlin.h where it is declared,
in Marlin_main.cpp where it is initialized, and then set and printed by M211
and finally in ultralcd.cpp where it bounds the movement from the lcd encoder.

So I suspect that there should be an additional check against the variable in clamp_to_software_endstops method. Or is the M211 command intentionally for LCD use only?

**Comment by thinkyhead** [comment]
@teemuatlut Good catch! I totally missed that somewhat important detail in #4667. This PR will fix that now.

**Comment by thinkyhead** [comment]
> not familiar with the overall code

@epatel It's pretty much the same, with some stylistic adjustments. A global search of `MESH_BED_LEVELING` would reveal all the interesting bits. I was hoping to get some commentary on the specific code changes in this PR, in case something was being removed which is subtly vital.

Anyway, the upcoming "`PROBE_MANUALLY`" option will remove the need to have a separate `MESH_BED_LEVELING` because the BILINEAR version of ABL does exactly the same as MBL, but is also delta-compatible and can probe only in a sub-region of the bed, if desired. Then there's a point where Roxy's UBL work will supplant the current leveling.

**Pull request merged**
