### PR TITLE
[1.1.x] Fix Z discrepancy with Tool-Change

### PR DESCRIPTION
**Pull request by thinkyhead**
Addressing #10130, #10200, #10202
[Concise Diff](10243/files?w=1)

**Background:** Some procedures need to either raise and lower Z or make corrections to the current position as part of their operation. This includes tool change when there are hotend offsets, `G10`/`G11` when there's a Z Hop value set, and so on. Under normal circumstances the existing approaches work, but when bed leveling and/or Z Fade are enabled these procedures can lead to discrepancies, which can accumulate to make objects the wrong size and potentially shift XY position.

In the Tool Change procedure we've customarily dealt with the issue by figuring out the discrepancy and then compensating for it. Unfortunately this no longer works in all cases due to differences in implementation applied at the higher level, specifically for UBL.

The Z hop in `G10`/`G11` has a related problem, but this is caused by their use of "spoofing" to do the Z movement while retaining the same logical Z position. When Z fade is enabled, this results in different amounts of adjustment for the raise-up compared to the lower-back-down.

**Tool-change Solution:** While it may be possible to add extra cases in Tool Change for UBL, it makes more sense to simplify the code by taking advantage of the newer `set_bed_leveling_enabled` code to just disable leveling prior to the procedure, then restore bed leveling at the right time at the end of the procedure. So that's what this PR attempts.

**Z Hop Solution:** It might work to disable leveling in `G10` and then restore it in `G11` but with a very tilted plane this would cause obvious problems. It's preferable to keep leveling enabled. So this PR tries making the Z raise symmetric to the Z lower. It still uses spoofing, but it spoofs the position only after the hop for the `G10` and spoofs the position before the lower down for `G11`. Maybe this leads to the same proportion of leveling adjustment being applied in both cases.

Also:
- Split up `tool_change` into smaller functions for different setups

Counterpart to #10257

### CODE REVIEW

**Comment by alexxy** [comment]
Any chances for this change for 2.0.x?

**Comment by thinkyhead** [comment]
> Any chances for this change for 2.0.x?

Once it is confirmed to fix the issue, then of course!

**Comment by thinkyhead** [comment]
@alexxy — If you want to give it a test, I've pre-rolled the update at #10257 (https://github.com/thinkyhead/Marlin/archive/bf2_tool_change_debug.zip).

**Comment by thinkyhead** [comment]
While this isn't perfect, it is apparently better, so I will merge to see whether general bugfix testers end up uncovering any unwanted side-effects.

**Pull request merged**
