### PR TITLE
handle lib_ignore for features

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

handle lib_ignore for features

#18699

### CODE REVIEW

**Comment by thinkyhead** [comment]
Experimenting with `lib_ldf_mode`…

With `lib_ldf_mode  = off` I have to explicitly specify `SPI` in `[common]` : `lib_deps`, and then there are other headers that are not downloaded, such as `FS.h` which belongs to `ESP Async WebServer` but which is not apparently in any manifest.

So, while that option can work, it means adding all the items that are now found in the dependency graph, but which are not explicitly specified with each library.

**Comment by thinkyhead** [comment]
If you try building the esp32 test (e.g., with `mftest esp32 1 -y`) with `ESP3D_WIFISUPPORT` enabled (and the `(ESP32_)?` typo in `[features]` fixed) you might see what I am seeing:

~~The `ESP3DLib` is specified as a dependency, but then the script ends up also adding it to the `lib_ignore` array.~~

~~If it is not already doing so, the code should check the `lib_deps` list that came from `[features]` and avoid adding anything to `lib_ignore` that explicitly appears in that list.~~

**Comment by thinkyhead** [comment]
Nevermind… I hit undo one too many times and the `(ESP32_)?` typo returned.

**Comment by rhapsodyv** [comment]
> With lib_ldf_mode = off I have to explicitly specify SPI in [common] : lib_deps, and then there are other headers that are not downloaded, such as FS.h which belongs to ESP Async WebServer but which is not apparently in any manifest.

I think off is too strict. I was about to write that we may not know everything its doing for us. But, is not a bad idea to be very strict about dependencies, to keep track of everything. Its just more work.

Besides that, we may need to turn LDF on, when we begin to use the private static libs in `Marlin/lib`, as that test I did with `mks_ui` folder. 

Right now, I think we don't need. But sooner or later, we will have too much files, and we will need separate some folders in static libs, to not break the linker.

> If it is not already doing so, the code should check the `lib_deps` list that came from `[features]` and avoid adding anything to `lib_ignore` that explicitly appears in that list.

The code get all the `env.lib_deps` and all known libs from features, transform to a `set`, do a `diff` operation and append the results to lib_ignore.

**Comment by thinkyhead** [comment]
I'm just setting `lib_ldf_mode` to `off` so I can observe how badly it fails in CI.

**Comment by rhapsodyv** [comment]
> I'm just setting `lib_ldf_mode` to `off` so I can observe how badly it fails in CI.

The `FS.h` header is in `~/.platformio/packages/framework-arduinoespressif32/libraries/FS`.... So, it means that with lib_ldf_mode=off, platformio don't search for deps even in the `lib` folder of the current espressif32!

It don't affect just our libs.

**Comment by rhapsodyv** [comment]
The test I did with mks_ui as a private lib, I found their declared dependencies are ignored, so they rely just on LDF to know each other.

And now, looking more deeply in the platformio packages, seems that they are just a collection of private libs...... And, as I discovered before, private libs just know each other by using LDF...

So, no, we can't disable LDF :-/ ... the platformio packages will not work..

**Pull request merged**
