### PR TITLE
Adds PWM capability to ESP32 I2S expander pins.

### PR DESCRIPTION
**Pull request by HoverClub**
### Description
Adds synchronised PWM capability to the ESP32 I2S expander.   

On ESP32 I2S expanders stepper drive signals are double-buffered (DMA buffers + I2S FIFO buffer) so they don't appear at the stepper driver inputs for up to 32mSecs after they are changed in software.  Any laser (or other device), connected to a CPU pin, won't be synchronised to the step signal (it "sees" the signal 32mS before the stepper driver does).  This solution allows PWM signals on the I2S expander pins by using software (on a separate task)  PWM.

Any number of expander pins can now use step-sync'ed PWM.

### Requirements
ESP32 with I2S expander.  Laser PWM pin (and ENA) must be on an expander output pin. 
  
### Benefits
Main advantage is that PWM is now accurately (4uS) sync'ed with stepper movement - essential when using a laser or any other PWM hardware that needs to be synchronised to movement.

### Configurations
The PWM frequency chosen (eg ```SPINDLE_LASER_FREQUENCY```)  will determine the PWM resolution (duty steps).  The default 2500Hz gives 0-100 resolution, 977Hz = 0-255, etc.  Formula is (250000 / SPINDLE_LASER_FREQUENCY) = resolution.

Most ESP32 boards have spare expander outputs available (either unused hardware functions or spare pins) that can be used for laser PWM control.  If a laser ENA signal is required in addition to laser PWM then both must be allocated to an expander pin to ensure they are sync'ed to each other as well as the step pulses (in any case, if only ENA is required it should be on the expander by default to guarantee sync).  

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/24096

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks good! I applied a number of style tweaks and other cleanup, so please confirm that nothing has been børken by these changes.

**Comment by HoverClub** [comment]
Thanks Scott.  It all works as it should with the tweaks/changes.

**Comment by matsala** [comment]
I never used github before. If there is any better way to do, thanks for telling me : where to post, how ...

I quickly asked on Discord [bug-repots]. But do not find a better place than here, to have at least some interested people regarding the subject (but I think the conversation should not be here).


I think I have a way to resolve the synchronised problem. For any IO / pwm / ... with just a Timer (in fact it would be able to sync any "action" that needs to).
=> faster/real PWM, lower CPU usage, and for hardware not having any more I2S pins

The main idea is to synchronize the I2S steam, to a simple running Timer (could be just starting both at the same time ?).
And keep a correspondence between current I2S "serial Clock" / "latched signal", and the current timer value.

When pushing new datas to I2S, keeping track of the last staked I2S_IO "anticipated time" the IO will really be latched.
If a new normal gpio needs to be pushed just after the last staked I2S IO, add a "planned in time IO" triggered by the Timer.

A list/stack of the actions to do would be enough. With the corresponding interrupt planned on the Timer.
Each execution of the Interrupt, plan the next action with the planned interrupt from the next element from the list (not sure it is clear ?)

Timer : could be any timer that has a continuous running time of at least staked I2S max time (at least 30ms ?). And fast enough regarding the precision needs.

**Comment by HoverClub** [comment]
Interesting suggestion!  However, the timing on the ESP32 implementation is driven by the I2S buffer swap (everything is sync'ed to a 4usec resolution) - there is no stepper interrupt running.   Adding other interrupts will cause WiFi issues.  In theory, ALL port switching could be fairly easily  sync'ed to the I2S output simply by disabling all I2S bufferring (it re-sends last data if FIFO is empty - as is done on FluidNC I2S_STATIC mode) BUT we are back to using stepper interrupts again.

Things would also be more difficult sync'ing CPU hardware peripherals though as each has its' own buffering and can be dependent on external devices (SPI, etc.) and, of course, sometimes sync'ing to other hardware isn't required anyway.


I tried a few options here: https://github.com/MarlinFirmware/Marlin/issues/24096#top

**Comment by matsala** [comment]
I stepped into #24096 at first ! (I have already read it all, but I could not comment as it is closed)

Lets stay with only PWM (as it is the first reason).

I have understood how works the "I2S stepper" : you feed memory so that all IOs are defined in 4us time slots.
The Idea I have is exactly based on that : if from the beginning you have pushed 1000 IOs timeslots, you know time is 4000us from the start of the Timer => if you want an event at that time, you need to do it at exactly 4000us.

I really think it should be kept how the "Steps" are generated.
For steps, for each stepper motor, signal switching event can be up to 250khz (by design in Marlin).
If you do drive IO using ISR, you will flood the ISR !
But what I propose is for "other signals" than Steps. They are no way of switching that much ! I do not know exactly for laser, but I would say at max 100/s ?

Regarding the RF, normally there should be a max time for interrupts. For BLE (bluetooth) I think it is about 50us for the IC I use. In the case of ESP32 I do not know ..., I imagine it should be of the same order (i think even more than 50us for wifi). It would be very strange to completely forbid high level of interrupts.

In our case, setting one/two registers for PWM should be a very short interrupt ! (less than 1us ?).

**Comment by HoverClub** [comment]
OK - I think I understand.  The problem I found is that data put into the I2S buffers isn't sync'ed to real time  (you can't know how much data remains in the buffer).    In other words, you couldn't calculate how long you need to wait before changing the PWM hardware so that it sync's with the correct data that is in the I2S buffer.   It's async input because of the random'ish nature of the RTOS task switcher.

**Comment by matsala** [comment]
The filling of buffers is not important, if I2S buffers never stop having data / never are empty. But maybe I missed something, and buffers are not always filled ? Or at least filled in known runs ?

The reference time is the same for all the peripherals. Any peripheral, so any Timer, and the I2S peripheral share the same Clock.
If the peripheral's reference in time is synchronised one time, they keep synchronised after that.

There are many other ways (synchronisation may be better using other ways), but the simplest way to be in sync, is just to start Timer and I2S peripheral at the same time.
Let's say the Time exactly works at the same 4us time slots. The timer is exactly a counter of time slots.
So you know the 300 time slot will be exactly done at Timer 300. So if you want to do anything at Timer 300, you can use the timer to trig the action to do the task.

How I imagine things works  : 
  - read one line G-code (we will suppose it takes more than 32ms)
  - generating the first datas of the I2S data stream to fill buffers
  - Start I2S and the Timer (you have 32ms to add some more data before buffers are empty)
  - generating the rest of data stream
    - keep on : filling / "waiting when buffers are full"
 (you can have up to 32ms to add some more data before buffers are empty)
  - read one line G-code (corresponding to a PWM on normal IO)
  - postpone the PWM to Time = last time slot + 1
  (you do not really know when it will be because of the buffers, but you know when relative to I2S data => hear just after the last stacked data)
  - read one line G-code 
  - continue ...

**Comment by HoverClub** [comment]
OK.  The buffers are filled  with duplicate (last) data if no "new" data is available - they can never be empty (`stepperTask()`).   I2S output streaming is continuous (4uSecs per word).  Input streaming (buffer filling)  isn't continuous and only happens when buffer space AND when  RTOS task switching allows time (asynchronous times).  You see occasional bursts of buffer writes as it re-fills after task switching delays (and, obviously, gaps where no buffer writes happen at all for several mSecs).   A timer can't tell you when, in the output stream, any data you write to the buffer will appear.  Unless you know how much space is in the buffer at that point in time (bufferSize - space * 4usecs is the current delay to the output).  With that data you can then calculate when to activate a PWM signal in the future to sync with the I2S output. 

If you are suggesting timing from the first  buffer data written then that may or may not work as the I2S interface starts transmitting as soon as enabled (no data has been written to buffer.  You don't know where in the buffer the first real data is written (and the position determines how long before it appears on the output).

Apologies if I'm misunderstanding what you are suggesting.

**Comment by matsala** [comment]
I understand it the same way for the filling : Rtos interrupts,
asynchronous, bursts and stops ...

There will certainly be modifications to do to have the synchronisation.
Especially at start/Enable of the peripherals.
It is certainly possible to fill buffers before starting the I2S peripheral
(with just init value is OK). Just need to count all stacked data. And make
sure when started, it is never empty, and keep counting the stacked data.

Let's say the Time exactly works at the same 4us as time slots.
=> The timer is exactly a counter of the time slots being on IOs (same
number we count in software for stacked data)

If we manage to start Timer and I2S at the same time : Timer value = I2S
data number on IOs
If you are OK with this affirmation, it is the most important thing to keep
in mind.

Any data we stack, we can have its "count number" from the start of
peripherals. And we know, this number corresponds to the Timer value when
it will be on IOs (both are equal).
The Timer value gives exactly the "I2S data number on IO", we can know the
exact "I2S data number on IO" just by reading the current Timer register.
The data filled in the buffers are stacked ahead of the current time. Last
stacked data in the buffers will be in several ms compared to the current
Timer register.

I may have found why we do not manage to understand each other on the Timer
part.

I am hardware oriented at the physical peripheral (do very little software,
and not good at).
At the software level, most of the time we postpone interrupts relatively
to now.
But how it is done at the lower level is : Int wanted time = current timer
+ waiting time
But there we already know the "Int wanted time", as we want the interrupt
to be juste after the "last stacked data number" : so we do not need
current time value.

In fact I was wrong, we can have the waiting time.
We can have the current IO data number, just reading the current timer
register. And so calculate the waiting time.
   - int wanted time = "last stacked data number" + 1  (whan it to happen
just after)
   - current data number on IO = current timer value
Waiting time = left data in buffers = ( "last stacked data number" + 1 ) -
current timer value

But we would need to ENTER_CRITICAL so that calculation can not be
interrupted.
And for : recalculating a value we already have.


Le lun. 21 nov. 2022 à 21:20, John Robertson ***@***.***> a
écrit :

**Comment by matsala** [comment]
I think you wanted the number of data in the buffer in #24096
<https://github.com/MarlinFirmware/Marlin/issues/24096> to calculate time.
And in fact with the timer as described, we have it : last staked data
number (counting stacked data), and current number of the data on IOs (with
the Timer).
The difference gives left data in buffers.

**Comment by matsala** [comment]
As we suggested to me on Discord, I have made the Feature Request #25011

**Comment by HoverClub** [comment]
I understand the theory it's just the implementation that might be difficult.  First problem is the size of the buffer counter - it's  almost limitless (a printer could be running for weeks or more with the I2S interface operating all of the time),  One solution to that issue could be to re-sync the counter to the timer every time the buffer is full (an `else` in the `StepperTask` function in I2S.cpp when it checks for buffer space).  The buffer will be full more often then not full as the `StepperTask` function will fill it rapidly between step pulse edges.  When full you know that the next value added to the buffer will appear at the output exactly `bufferSize * 4usecs` later.

The 2nd issue is the number of timed interrupt events required - a laser PWM value, for example, is calculated every stepper pulse so, in theory, could change every 4uSecs - you may need to buffer/stack a very large number of timed interrupt 'events'. 


Yet another, maybe simpler, option would be to use a circular buffer to store the hardware port values you want sync'ed with the I2S data.  This new buffer would be the same length as the I2S buffer.  The buffer read pointer would be incremented by a 4uS timer and the value read used to set the "delayed" IO pins.  The buffer and read pointer would "mirror" exactly the hardware I2S output stream.   The write pointer would increment every time the I2S buffer is written to (and the delayed IO value also saved).  The write pointer would be initialised the first time the buffer is full so that it is exactly `bufferSize` "behind" the read pointer (the read pointer would be +1 the write pointer - the opposite of how a buffer normally works!).  The read pointer would remain exactly in sync with the I2S output and the write pointer in sync with the I2S buffer write events (variable timing).  Unless the I2S buffer gets emptied (theoretically impossible - even so, they could be re-synced on every I2S buffer full condition as described above).  The buffer is pretty large but smaller than an "interrupt event" buffer would need to be that would need to save a time and an IO state in each location. There is probably already a timer available running at 4us or less, and no additional interrupt would be required (and no large counters either).  I did try something similar some time ago but didn't sync the buffer read to a 4uS timer - the important part! 

_edit_
On further reflection there is a flaw in both schemes as they rely on a timer interrupt to update the delayed IO data.  Unfortunately interrupt latency is not consistent enough in a system like this - the task switcher latency alone can be 20uS or more delay to interrupt response times.  That would be too long for some IO events (laser PWM on a high speed raster machine for example).

**Comment by matsala** [comment]
Wouldn't it make more sense to use the new thread I have made ? For any other interested persons.
I have re-explained better in it.


I respond to your here, it makes no sense to do it over there for a response point by point.

First paragraph :
The limitation of a Timer, is max time you want to postpone. We know max possible postponed time is 32ms (I2S buffer).
Just need to make a modulo : "Data Number" % "size of the Timer" for the Interrupt Time.
Should be very easy, having a Timer power of two.

Second paragraph on the number of interrupts :
With PWM done with the expander, max steps per PWM is 100 * at 2500 Hz = 250 000 hz (4us timeslots).
So in fact, as done it makes a min interrupt every 400us (if changed every new PWM => very unlikely)

Third :
I do not know how works the I2S PWM module :
- PWM DMA can be triggered with a timer ?
- Or triggered automatically when one PWM is done ?
=> If it is the case, yes it should be possible to work as the I2S => staking data with DMA. Just needing to be synchronised at Start.

Edit paragraph :
- 20us compared to the original possible 32ms jitter is very small
- Or even compared to the I2S PWM of 400us
- If the 20us are consistent, it is even possible to remove the anticipated offset time from the Interrupt time, to have intended action taking place at the good timing

**Pull request merged**
