### PR TITLE
Enable contrast via LCD_CONTRAST_INIT

### PR DESCRIPTION
**Pull request by tpruvot**
There is no more the menu setting since commit dfcd43748649295cf1cc6da5ba68eb5a1cf2aa42
and the screen is now almost black...

Unfortunately this issue caused a side effect, M500 will save a "0" value which make it fully black.
So after applying this patch, users will need to do M502 + M500 via serial...

### CODE REVIEW

**Comment by thinkyhead** [comment]
The old assumption was that any displays that defined a default contrast would init contrast and provide a menu item. That was recently changed back to the old old code, which relies on every display being named explicitly, since there was some question.

In fact, the decision about whether a display has a default contrast (and therefore an adjustable one) should be deferred until `Conditionals_post.h` so that pins files have a chance to override it.

That change will be made soon.

**Comment by tpruvot** [comment]
maybe the config should avoid to set 0 if not enabled also ? maybe more a 127 ?

**Comment by thinkyhead** [comment]
> maybe the config should avoid to set 0 if not enabled also ? maybe more a 127 ?

No config sets `DEFAULT_LCD_CONTRAST` (unless the user adds it). I've added a commit to allow `DEFAULT_LCD_CONTRAST` to be overridden, but using a different define to indicate that an LCD has adjustable contrast.

**Comment by tpruvot** [comment]
i meant in Marlin/src/module/configuration_store.cpp

```cpp
    //
    // LCD Contrast
    //
    {
      _FIELD_TEST(lcd_contrast);

      const int16_t lcd_contrast =
        #if HAS_LCD_CONTRAST
          ui.contrast
        #else
          32
        #endif
      ;
      EEPROM_WRITE(lcd_contrast);
    }
```

its 32 in fact, not 0

**Comment by thinkyhead** [comment]
This should work for all displays that have adjustable contrast. If there are some that should not have a contrast menu, but which nevertheless should have a contrast init, then we will have to look at that.

**Comment by tpruvot** [comment]
tx...

**Pull request merged**
