### PR TITLE
Add support for high temperature thermistors

### PR DESCRIPTION
**Pull request by JeanSebastienCarrier-Dyze**
This is a follow up of : https://github.com/MarlinFirmware/Marlin/pull/2915

As discussed, I moved most of the preheating setup in setTargetHotend,
Both MILLISECONDS_PREHEAT_TIME  and MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED have been added to Configuration.h, and their value set to zero by default (meaning the feature is off by default). I did my best to explain what both variable are used for in the comments.
Added the thermistor table for high temperature thermistors in thermistors.h

### CODE REVIEW

**Comment by JeanSebastienCarrier-Dyze** [comment]
After discussion with AnHard, will submit pull request to marlinDev instead

**Comment by MrExo3D** [comment]
When can Dyze support be added to the current RC5bugfix?

**Comment by thinkyhead** [comment]
@adamfilip A couple of weeks ago, this might have made it into the 1.1.0 release., but we've frozen features and are not accepting any new hardware support today.

**Comment by JeanSebastienCarrier-Dyze** [comment]
I opened a pull request on MarlinDev sometimes ago in order to add the high temperature thermistor support to the dev branch, and hopefully make that available in a future release. https://github.com/MarlinFirmware/MarlinDev/pull/374

I'm not too sure how the the pull request process works, but if there is anything I can do to make reviewing or integrating my changes easier, feel free to ask. I'm also available if my code needs some reworking

**Comment by jbrazio** [comment]
MarlinDev has been on hold for a bit, all efforts have been concentrated on the RC cycle here, our expectation is to release RC6 as the last one for the cycle. After this MarlinDev will receive all our attention.

**Pull request closed without merging**
