### PR TITLE
Replace untilted_stepper_position with planner.unapply_leveling, use in set_current_from_steppers_for_axis

### PR DESCRIPTION
**Pull request by thinkyhead**
Like the title says…

### CODE REVIEW

**Review by jouirau — COMMENTED** [review]
I am currently working on a SCARA robot that is _not_ Morgan based (ie no Theta + Psi on the 'Y' arm)

I would argue that there are three types of arms in the SCARA family: Morgan, LeftArm, RightArm. The kinematics are almost identical - just the theta + psi change, and the direction of the stepper drives.

My comment on the latest update is that the older IS_SCARA test may be more representative of the family than ENABLED(MORGAN_SCARA) . Nearly all of the code works fine for all SCARA types with a few exceptions.

For example with setting the scaling factor in lcd_control_motion_menu() in ultralcd.cpp I think the IS_SCARA is better than ENABLED(MORGAN_SCARA), as the scaling factor applies to all the SCARA types not just the Morgan.

One place where it makes sense to me to check for MORGAN_SCARA is the Theta + Psi in the procedure inverse_kinematics():

#if MORGAN_SCARA
delta[B_AXIS] = DEGREES(THETA + PSI);  // equal to sub arm angle (inverted motor)
#else // all other 'normal' SCARA
delta[B_AXIS] = DEGREES(PSI);  // equal to sub arm angle (inverted motor)
#endif 

Overall I am really liking the SCARA support in this firmware. Marlin has been working superbly on my SCARA machine (with a few minor tweaks)  G2 & G3 also seem to work fine (more testing required).  Your current efforts to make more sense of the logical versus physical position stuff are highly welcomed. Thank you!

**Comment by thinkyhead** [comment]
@jouirau Can you describe what `axis_scaling` is all about? I'm writing the firmware for the [MakerArm](http://makerarm.com/), and I haven't been planning to use it.

I do however have it working with both left and right arm kinematics, with the ability to switch between them.

**Comment by jouirau** [comment]
@thinkyhead I have not used the scale factor yet.  I assume that it is a way of tweaking the ratio of the stepper motor steps to the number of degrees moved on the fly.   It does not seem to be that different in effect to tweaking the XStepsMM/YStepsMM.  My immediate question is whether this is a logical or physical tweak. IE is it the scaling for the A and B arm steppers or is it the logical scale of the x and y axis?  Do you know the intent of the original inclusion of these scale options?  

At some point more descriptive menu items might be needed for SCARA.  Thing like 'A steps/degree' instead of 'X steps/mm'  and 'AScaleFactor' instead of 'XScaleFactor' to move away from the slightly misleading use of X and Y in the SCARA situation. (unless the XScale factor is actually meant to be the logical scale...)

The point I was trying to make was if there is a need for a 'scaling factor' then it should probably apply to all types of SCARA not just the Morgan. 

More generally I am arguing that the IS_SCARA test or ENABLED(SCARA) should be used for most of the SCARA related stuff instead of ENABLED(MORGAN_SCARA) to reflect the overall similarities of the SCARA family.  And then use ENABLED(MORGAN_SCARA) for the few very specific Morgan related differences.

**Comment by thinkyhead** [comment]
The `axis_scaling` factors are unnecessary, obsolete, and the idea is bankrupt. According to the source code comments, these exist to adjust the "build size." Well, you can't do that! If one wants to build something at a different size, one must scale it in the modeling software or in the slicer. Otherwise you just create gaps between the extruded lines.

The firmware cannot make something bigger or smaller merely by scaling the XY (cartesian) coordinates, which is what these factors attempt to do. If someone's custom build needs tweaking due to being scaled up from the Morgan (or other SCARA) build plans, it must be done through configuration.

If the idea is to scale for the sake of using a pen or paintbrush, well, again, that is not limited to SCARA. And again, it should be done in the slicer or Inkscape plugin export feature, not in the firmware.

**Comment by thinkyhead** [comment]
> More generally I am arguing that the IS_SCARA test or ENABLED(SCARA) should be used

The items enabled specifically for `MORGAN_SCARA` are things which do not apply to the only other current option, which is `MAKERARM_SCARA`.

I suppose it could be `#if IS_SCARA && DISABLED(MAKERARM_SCARA)` but for now I'm keeping it cleaner.

You'll note that I haven't added the kinematics and other MakerArm-specific changes. It's just hinting at things to come. I'm not entirely free to release the code just yet because the machine is still in development, but no one has this robot yet anyway.

**Comment by jouirau** [comment]
Good points!  So in fact the two scale menu items can be deleted along with
the two related msg defines in language_en and any related scaling code.
Will you add this to your current cleanup, or would you like me to do it?

PS - impressed that you have both leftArm and rightArm working!  I am
waiting on some hardware to arrive before I attempt that.

**Comment by thinkyhead** [comment]
> impressed that you have both leftArm and rightArm working!

If you have (or can download) [OpenSCAD](http://www.openscad.org/downloads.html), then you should download my gist demonstrating [Ambidextrous SCARA Kinematics](https://gist.github.com/thinkyhead/85a4847ae1fc5aa0d21e807fa26bf3c5). I note that the equations are similar —but not identical— to the kinematics from the SCARA code. I did a lot of messing around to arrive at the functions that worked best. Use the OpenSCAD "Animation" panel to see it in all of its circular glory.

**Comment by thinkyhead** [comment]
> the two scale menu items can be deleted

I'll do that in a separate PR after this one, which seems finally to be in good shape.
At least, it's passing Travis.

**Pull request merged**
