### PR TITLE
Add extra corner leveling margin options

### PR DESCRIPTION
**Pull request by thinkyhead**
Resurrection of #16480 by @Vertabreak, checked over and ready to merge.

### CODE REVIEW

**Comment by Vertabreak** [comment]
my original PR was a bit of a mess i hope it gets cleaned up before being merged. 
i ran it on my printer it did function but my code tends to be the quick n dirty kind.

**Comment by thinkyhead** [comment]
I'm having fun with it. Even the simplest PRs can lead to interesting things sometimes.

**Comment by Vertabreak** [comment]
the person that requested it seem to have use for it and i can see instances where it would be nice to be able to set where each corner is. Ive been reluctant to post any PR's lately been kinda out of it.

**Comment by Vertabreak** [comment]
already looks way better then the way i did it.

**Pull request merged**
