### PR TITLE
Make X axis optional (WIP)

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Add support for making X optional also (so having only an Extruder is a possibility.)

### Benefits

More modularity, smaller code for extruder-only projects.

### CODE REVIEW

**Comment by ellensp** [comment]
I've done all the obvious code, now i'm stuck in "macro hell"

Can anyone lend a brain to assist?

**Comment by thinkyhead** [comment]
I believe this is essentially impossible given the current Marlin architecture. As a basic point, the type `XYZval` and all the types that derive from it become empty. An empty type that occupies no memory can't be allocated or referenced, so all kinds of core Marlin code becomes broken. There is a fundamental assumption that there will be at least one linear axis, and the number of conditional changes throughout the code to drop that assumption is simply overwhelming.

**Comment by thinkyhead** [comment]
…or maybe…. Apparently a zero-length array is possible, and maybe empty structs. At any rate, it's now compiling, so that's a pleasant surprise.

**Comment by ellensp** [comment]
just talking a look at it now, complies, uploads, responds to gcode ...   I need to find an extruder I can play with...

**Comment by thisiskeithb** [comment]
Some hacky stuff was done to the BTT EBB42 pins in https://github.com/MarlinFirmware/Marlin/pull/24964 to make Marlin compile without an x/y/z axis, so that should probably get cleaned up here as well:

https://github.com/MarlinFirmware/Marlin/blob/d3527f5de42f087bfe313aa475b0bf5d07559fed/Marlin/src/pins/stm32g0/pins_BTT_EBB42_V1_1.h#L80-L93

**Comment by ellensp** [comment]
@thisiskeithb that is part of the plan, but a sperate pr

**Comment by alextrical** [comment]
> as done to the BTT EBB42 pins in #24964 to make Marlin compile without an x/y/z axis, so that should probably get cleaned up here as well:
> 
> [](https://github.com/MarlinFirmware/Marlin/blob/d3527f5de42f087bfe313aa475b0bf5d07559fed/Marlin/src/pins/stm32g0/pins_BTT_EBB42_V1_1.h#L80-L93)

Apologies for that, But this PR is the ideal solution to allow that to be cleanly implemented. I needed the Pins to be available for a rotary encoder on a heavily crippled board

**Comment by alextrical** [comment]
Im not sure how to append changes to this draft PR, but another change that should be added to this should be in SanityCheck.h
```
-#elif !defined(X_BED_SIZE) || !defined(Y_BED_SIZE)
+#elif (HAS_X_AXIS && !defined(X_BED_SIZE)) || (HAS_Y_AXIS && !defined(Y_BED_SIZE))
```

**Comment by alextrical** [comment]
Im not sure how to colaborate on a Pull request, so hopefuly its OK with small fixes, to list the file and lines that have issues.
When compiling with a TMC based stepper (TMC2209), there looks to be an issue with ```identifier "SP_X_STR" undefined``` A "#if HAS_X_AXIS" would fix the issue :)

https://github.com/MarlinFirmware/Marlin/blob/f3f7b1e7e337f9590b7805651969ae88b58a903f/Marlin/src/gcode/feature/trinamic/M569.cpp#L197-L207

**Comment by The-EG** [comment]
@alextrical You can also submit a PR to their fork repo targeting the branch that this PR is based on (ie. `mkae-X-optional`). They can then close/merge it in on their side and it will appear here too.

edit: that's probably the best approach for large/multiple changes.

**Comment by alextrical** [comment]
Fix for 0 kinematics (Flash?) EEPROM has been submitted https://github.com/MarlinFirmware/Marlin/commit/c7d4c95d9e2225118d67f7998b67b9dbe6fa9af7

Edit: removed PR for changes, the firmware compiles but does not run when Flash EEPROM is used on a STM32G0B1CB. Need to figure out what's causing it to not enter a working state (no display, serial or Heartbeat LED)

**Comment by thinkyhead** [comment]
> Fix for 0 kinematics (Flash?) EEPROM has been submitted

@alextrical — Where exactly was it submitted?
image

**Comment by thinkyhead** [comment]
> Im not sure how to colaborate on a Pull request

@alextrical — Check out the branch that this PR is based on, linked at the top of this page where it says "`ellensp:mkae-X-optional`" then submit a PR to ellensp's fork targeting the branch "mkae-X-optional". When ellensp merges your PR to his branch, it will be added to this PR.

See GitHub's very through help section for more information about contributing to existing PRs.

**Comment by ellensp** [comment]
PR against my branch merged. hope I did that right, I've never actually merged anything before.

**Comment by ellensp** [comment]
what else needs done here?

**Comment by WMFTG** [comment]
> Where exactly was it submitted?

@thinkyhead  Sorry I found that there was an issue and tried to roll back the PR, it caused an issue that prevented the board from running code when Virtual EEPROM was enabled, presumably caused by memory locations

**Comment by alextrical** [comment]
> > Fix for 0 kinematics (Flash?) EEPROM has been submitted
> 
> @alextrical — Where exactly was it submitted? image

@thinkyhead  Sorry I found that there was an issue and tried to roll back the PR, it caused an issue that prevented the board from running code when Virtual EEPROM was enabled, presumably caused by memory locations.
Most likely it was this branch https://github.com/alextrical/Marlin/tree/Make-x-optional-eeprom-fix

**Comment by thinkyhead** [comment]
> what else needs done here?

As PRs go this one is a biggie! I was holding it until after 2.1.3, which was anticipated to happen a lot sooner. I've merged to bring it up to date, so now it should be tested again to make sure all the basic functions work when there's only an extruder and nothing else. That includes the EEPROM, to see whether the comment above still applies.

I don't anticipate any major troubles with this PR generally, but it does continue to lean into the old ways. Once this next release is out the door (and patched up in a followup minor release), we should look at refactoring more in the direction of templates, compiler dead-code stripping, and so on. It would be neat to get more formal object classes like `Motor` and `Fan` and so on to better encapsulate common components. Working on Fixed-Time Motion got me looking at the motion code more closely, and I believe we can make it a lot more concise, but it might be a little daunting at first.

I do want to get 2.1.3 released soon. I just have to re-test the probing and `G34` behavior, fix up Fixed-Time Motion as much as possible, and then do a couple of test prints to make sure there are no unexpected instabilities. At the very least, I want 2.1.3 to be an improvement over 2.1.2, effectively addressing all reported issues, and at the moment I'm cautiously optimistic.

**Comment by rondlh** [comment]
I suspect this update gives me a considerable lack of response to G0/G1 commands, which turns out is bad for the print quality.
G28 works, but afterwards there is no response anymore to anything (e.a. M119) but temp reporting continues.

**Comment by vosk** [comment]
Hello all, I believe this or the previous PR in the series broke the backlash menu for XYZE printers, HAS_A_AXIS is now undefined in _CAN_CALI(A) used in menu_backlash.cpp. Since this is WIP apparently, feel free to ignore. Otherwise adding another 3 clauses for X Y Z  ( A B ...) looks an obvious quickfix.
EDIT: This may be the actual cause:
https://github.com/MarlinFirmware/Marlin/commit/4233e4864f0c621612ce35a9b6ca882312e3aa4d#diff-d815bc244111b340f481976e8586e14084caeb10c74192a35a5bba39c0b7d0a1

**Comment by xxxajk** [comment]
For laser, Z is optional (which my table is manual Z adjustment).
You might be able to find some clues as to what I did to fix things to get them right in my own branch, but I need to update it in sync with the current branch...

**Pull request merged**
