### PR TITLE
Creality dwin test

### PR DESCRIPTION
**Pull request by redneck30333**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
@InsanityAutomation People [REALLY want this in Marlin](https://github.com/MarlinFirmware/Marlin/pulls?utf8=%E2%9C%93&q=is%3Apr+Creality+dwin). lol.

**Comment by InsanityAutomation** [comment]
Yeah, I need to finish the EXTui port but I've been way too busy....

**Comment by boelle** [comment]
i vote to close this one, its more or less the same deal but just a new user that has just signed up with github

same missing description and then the PR is against 1.1.x and not 2.0.x

**Comment by boelle** [comment]
@redneck30333 it does not help you at all keeping creating a new username and do this over and over

we know this has been going on for a long time: https://github.com/MarlinFirmware/Marlin/pulls?utf8=%E2%9C%93&q=is%3Apr+Creality+dwin

please stop wasting our time with repeating this

**Pull request closed without merging**
