### PR TITLE
Ensure TMC + LIN_ADVANCE pulse length

### PR DESCRIPTION
**Pull request by ManuelMcLure**
### Description

Make sure that if any extruder is a TMC driver, the minimum pulse length is honored. If ``SQUARE_WAVE_STEPPING`` is not enabled or this is a standalone driver (which don't support ``SQUARE_WAVE_STEPPING``) set ``MINIMUM_STEPPER_PULSE`` to 1 instead of the TMC default of 0.

### Benefits

This is a FAQ in the support channels - people switch to a TMC on their extruder and get no extrusion with ``LIN_ADVANCE`` enabled.

### Related Issues

#15761

### CODE REVIEW

**Comment by ManuelMcLure** [comment]
There’s another option for non-standalone drivers which is to enable ``SQUARE_WAVE_STEPPING`` instead of setting the pulse length, but I took this option as being safer.

**Review by psavva — COMMENTED** [review]
This fix will not work if MINIMUM_STEPPER_PULSE is configured in the config files...

You may need to change the logic to check if not defined or defined as zero... 

If it is defined as zero, the new conditional will not be executed, giving the same behavior with the same config...

**Comment by ManuelMcLure** [comment]
I'm assuming that if ``MINIMUM_STEPPER_PULSE`` was explicitly set to 0 the user does not want it overridden. This is just a fix to avoid problems with the default configuration files.

**Comment by psavva** [comment]
The issue is that the recommendation for TMC is to set it to zero.  Having also defined LIN_ADVANCE, the extruder don't work.

If a conditional is set like it is here, it simply won't work when users follow the recommendation, and cannot extrude...

I recommend implementing a sanity check in this case, which will resolve the issue under all user cases, not just when minimum pulse is not defined.

**Comment by ManuelMcLure** [comment]
I don't think we should override values set specifically by the user. We can change the comment with the recommendation to say that if LA is turned on the default should be 1, but I disagree that this is a large problem. Most people will just uncomment the default line and get 2. If they specifically go to the effort of changing the value of ``MINIMUM_STEPPER_PULSE`` to 0 we shouldn't change it.

**Comment by thisiskeithb** [comment]
> There’s another option for non-standalone drivers which is to enable SQUARE_WAVE_STEPPING instead of setting the pulse length, but I took this option as being safer.

I can't say I've heard of a bad result enabling `SQUARE_WAVE_STEPPING`, but it's also still fairly new.

In my SKR 1.3/TMC5160/Linear Advance build with `SQUARE_WAVE_STEPPING` enabled, I no longer have to increase (or enable) a custom `MINIMUM_STEPPER_PULSE`.

**Comment by ManuelMcLure** [comment]
This PR checks whether ``SQUARE_WAVE_STEPPING`` is enabled and doesn't override ``MINIMUM_STEPPER_PULSE`` if it is (unless the extruder is a standalone TMC since we can't use ``SQUARE_WAVE_STEPPING`` on those).

**Comment by teemuatlut** [comment]
> I don't think we should override values set specifically by the user.

^

**Comment by psavva** [comment]
Perhaps just a sanity check then.

If Trinamic and Lin Advance and not ( Stepper Pulse > 0 or Square Wave Stepping) then raise a error

**Comment by psavva** [comment]
@thinkyhead any suggestions on this one?

**Comment by thinkyhead** [comment]
Sanity-check is always the most user-aware route, and is fine for a first approach.

**Comment by ManuelMcLure** [comment]
I've added a sanity check in case a bad value for ``MINIMUM_STEPPER_PULSE`` was explicitly set.

**Pull request merged**
