### PR TITLE
Fix freeze pin logic

### PR DESCRIPTION
**Pull request by GMagician**
Fix bug introduced by #23994

Need to be tested, I don't have freeze pin

### CODE REVIEW

**Comment by GMagician** [comment]
Compile failure seems not related to PR content.

**Comment by thinkyhead** [comment]
Very strange. I had already changed it to `stepper.frozen = READ(FREEZE_PIN) == FREEZE_STATE` but must've forgotten to push it.

**Comment by thinkyhead** [comment]
> Compile failure seems not related to PR content.

Apparently a spurious external library issue, and now compiles fine.

**Comment by GMagician** [comment]
it seems there is some wrong comment left..

>  * Specified pin has pullup and connecting to ground will instantly pause motion.

**Pull request merged**
