### PR TITLE
Full Move Screen for Color UI

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

A screen for new color ui that allows moving all axis, without going back and forth between screens. Works with touch. 

Tasks:
- [x] Draw Screen
- [x] Select Tool
- [x] Auto Home
- [x] Move Axis
- [x] Z Offset
- [x] Babystep Support (z axis now)
- [x] While Printing show Baby Step (if enabled)
- [x] Handle move "cases" (delta, max, min, etc)
- [x] Disable steppers
~320x240 screen~ (I will do it other time, as I don't have a 320x240 screen yet)

### Benefits

- Advanced screen for touch users

### Configurations

Just use the new color ui

### Related Issues

#18130 

Preview:
Accessed from:
IMG_0007

New Screen:
IMG_0028

While printing if baby stepping is enabled:
IMG_0025

### CODE REVIEW

**Comment by jmz52** [comment]
It is a bit too late, but still a feedback on this.
I see two issues with drawBtn() functionality.
First - the whole idea of new UI implementation is to make is drawn in background to make sure it does not affect Marlin performance too much. The tft.queue.sync() should not be used in regular situations, as it will be too time consuming for larger screens especially on SPI interface.

Second - current queue implementation was made with an idea to (eventually) offload queue processing to smart screen.
Compact queue buffer can be send for processing to smart screen over any interface, including UART. This will greatly increase number of supported devices. The font manipulation in drawBtn() makes this 'off-site queue processing' too complex to implement - external device should not be aware about current UI screen.
I would suggest to use icons instead of font manipulation.

**Comment by rhapsodyv** [comment]
@jmz52 never is too late! Thanks for your review!

I used the sync, because I wanted to change fonts, and the current ADD_TEXT don't support font option. As I will work again in this screen to add support for 320x240 (when I receive the screen I ordered), I just kept it this way. But your concerns is true e very right.

We have 3 options:

1) Icons.
2) If I just use the default font, I will not need to do any sync, so it will "fix" those problems too
3) We can make ADD_TEXT receive the font to use. I think in the future, when we have that 'off-site queue processing', the ADD_TEXT command will not be so heavy or complex by just having a font option. For example: DWIN (uart) accept font size in their text command.

I don't like (1), because it will increase the size of the flash (at least by now). It may reduce the UI compatibility.

(3) is my preferred, as it gives us more flexibility. 

(2) will just work fine, and I don't think the screen will be so different.

**Comment by Miraculix200** [comment]
When I touch the OFF button in this screen, the display doesn't react anymore

**Comment by rhapsodyv** [comment]
> When I touch the OFF button in this screen, the display doesn't react anymore

OFF or Home? The home was fixed here: #19426 . I'm waiting more feedbacks to mark the PR ready.

**Comment by Miraculix200** [comment]
Yes, nevermind. It was the Home button.

**Comment by Foxies-CSTL** [comment]
Hi,
I have an MKS Robin TFT V2.0 (320x240) on my Delta QQS-Pro printer. I have been using it with UI Marlin Color for 1 month now and the feedback on its use is very good. There was just a bug on the validation of an action in UBL mode (deploy / stow Zprobe) which has been fixed. The only thing left is some lack of operation results on the screen.
eg: Value of the result of an M48 probe test.
I am using the MKS_ROBIN_TFT28 / 32 driver.
Here is my feedback. Best regards.
IMG_1833
IMG_1830

**Pull request merged**
