### PR TITLE
[1.1.x] BLTouch V3.0 and 3.1

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Parity with 2.0.x for BLTouch

I have not had a chance to run this on hardware yet but everything builds. Please test vigorously.

@fandjango @thinkyhead @Roxy-3D

### CODE REVIEW

**Comment by tpruvot** [comment]
Current code in 2.x is not good, and 1.1 is supposed to stay as is. A PR not even tested ???

**Comment by InsanityAutomation** [comment]
> Current code in 2.x is not good, and 1.1 is supposed to stay as is. A PR not even tested ???

This one is a bit outside the norm. Paris at antclabs had requested changes for 3.1 in the 1.1.x branch via email and there was some discussion there with thinkyhead, Roxy, bob-the-khun, fandjango and myself. I had time to backport it but didn't have time to test anything. This puts it in a space most of that list can change anything needed I may have missed, and Paris can get the code to test on their end. This will definitely not be merged without testing from several involved parties

**Comment by Roxy-3D** [comment]
> Current code in 2.x is not good, and 1.1 is supposed to stay as is. A PR not even tested ???

This is a special case.  We are treating the BL-Touch v3.x code updates as a 'bug fix'.   While the BL-Touch code that was in v1.1.9 worked, when BL-Touch  v3.x came out the code no longer functioned.   So, without some adjustments, nobody buying a new BL-Touch would be able to use the v1.1.9 branch.

**Comment by trouch** [comment]
>  So, without some adjustments, nobody buying a new BL-Touch would be able to use the v1.1.9 branch.

This statement is true with any other new hardware that has non backward compatible design change. People should upgrade to software with proper support for their new hardware. As an example, what about TMC2209 and 5160 ? Maybe Trinamic would support Marlin as much as Antclabs to get them back ported into 1.1.x branch ;-)

**Comment by InsanityAutomation** [comment]
> 
> 
> > So, without some adjustments, nobody buying a new BL-Touch would be able to use the v1.1.9 branch.
> 
> This statement is true with any other new hardware that has non backward compatible design change. People should upgrade to software with proper support for their new hardware. As an example, what about TMC2209 and 5160 ? Maybe Trinamic would support Marlin as much as Antclabs to get them back ported into 1.1.x branch ;-)

The difference is users will buy a generic bltouch with no idea of version until its too late. Drivers you know exactly what youre getting. Older revisions are no longer available anywhere. This is more to cover for the accidental surprise.

**Comment by trouch** [comment]
> The difference is users will buy a generic bltouch with no idea of version until its too late

Aw, yeah I admit buying a BLTouch can be a nightmare 😅

**Comment by InsanityAutomation** [comment]
Hurrah! travis was just a couple easy fixes! Probably good to keep it where it can build just in case anything else comes up prior to 2.0 hitting a release.

**Comment by thinkyhead** [comment]
Thanks for the back-port. It will be merged shortly.

Note that the commit log is kind of a nightmare. Perhaps in future you will be kind enough to do a rebase and squash or rebuild the commits from scratch before submitting your PR…? With so many issues and PRs coming in every day, this will save the maintainers a lot of headaches.

**Comment by InsanityAutomation** [comment]
> 
> 
> Thanks for the back-port. It will be merged shortly.
> 
> Note that the commit log is kind of a nightmare. Perhaps in future you will be kind enough to do a rebase and squash or rebuild the commits from scratch before submitting your PR…? With so many issues and PRs coming in every day, this will save the maintainers a lot of headaches.

I saw how messed up the history got and figured this will probably be my last push to 1.1.x. If I ever end up doing another one, ill fix my branch first.

**Comment by reloxx13** [comment]
i would like to suggest a 1.1.10 release with the bltouch v3 fixed.
pls think about it, alot users which buy a bltouch will get the v3 now and they are using the release download 1.1.9 (this is what i see on fb groups).

**Comment by bogaskilop** [comment]
Hi all recently i get  4 bltouches  for new printers and all of them are  bltouch v3.1  so now i'm looking for configuration of those bltouches  and at configuration_adv.h  in marlin 1.1.9  bug-fix there are few additional settings  and is there any guide step by step how to use those new bltouch probes with marlin 1.1.x bug-fix  ? 

I do not understund those options and i dont want to fry my bltouches :

```cpp
#if ENABLED(BLTOUCH)
  /**
   * Either: Use the defaults (recommended) or: For special purposes, use the following DEFINES
   * Do not activate settings that the probe might not understand. Clones might misunderstand
   * advanced commands.
   *
   * Note: If the probe is not deploying, check a "Cmd: Reset" and "Cmd: Self-Test" and then
   *       check the wiring of the BROWN, RED and ORANGE wires.
   *
   * Note: If the trigger signal of your probe is not being recognized, it has been very often
   *       because the BLACK and WHITE wires needed to be swapped. They are not "interchangeable"
   *       like they would be with a real switch. So please check the wiring first.
   *
   * Settings for all BLTouch and clone probes:
   */

  // Safety: The probe needs time to recognize the command.
  //         Minimum command delay (ms). Enable and increase if needed.
  //#define BLTOUCH_DELAY 500

  /**
   * Settings for BLTOUCH Classic 1.2, 1.3 or BLTouch Smart 1.0, 2.0, 2.2, 3.0, 3.1, and most clones:
   */

  // Feature: Switch into SW mode after a deploy. It makes the output pulse longer. Can be useful
  //          in special cases, like noisy or filtered input configurations.
  //#define BLTOUCH_FORCE_SW_MODE

  /**
   * Settings for BLTouch Smart 3.0 and 3.1
   * Summary:
   *   - Voltage modes: 5V and OD (open drain - "logic voltage free") output modes
   *   - High-Speed mode
   *   - Disable LCD voltage options
   */

  /**
   * Danger: Don't activate 5V mode unless attached to a 5V-tolerant controller!
   * V3.0 or 3.1: Set default mode to 5V mode at Marlin startup.
   * If disabled, OD mode is the hard-coded default on 3.0
   * On startup, Marlin will compare its eeprom to this vale. If the selected mode
   * differs, a mode set eeprom write will be completed at initialization.
   * Use the option below to force an eeprom write to a V3.1 probe regardless.
   */
  //#define BLTOUCH_SET_5V_MODE

  /**
   * Safety: Activate if connecting a probe with an unknown voltage mode.
   * V3.0: Set a probe into mode selected above at Marlin startup. Required for 5V mode on 3.0
   * V3.1: Force a probe with unknown mode into selected mode at Marlin startup ( = Probe EEPROM write )
   * To preserve the life of the probe, use this once then turn it off and re-flash.
   */
  //#define BLTOUCH_FORCE_MODE_SET

  // Safety: Enable voltage mode settings in the LCD menu.
  //#define BLTOUCH_LCD_VOLTAGE_MENU

#endif // BLTOUCH
```

so how should I set those options  ?

**Comment by thinkyhead** [comment]
@bogaskilop

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://discuss.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

**Comment by AnHardt** [comment]
As always - it depends.
Impossible to answer without information about the board - if it's 5V tolerant or not, ++.

**Pull request merged**
