### PR TITLE
Touch ui ftdi eve fixes

### PR DESCRIPTION
**Pull request by sl1pkn07**
Fix little typos and back to use default `PWM_HZ` since the brightness dim is disabled for Fysetc TFT81050, this not need anymore. also `0x2710` can damage the backlight in this panel (due @RudolphRiedel recomendations in https://github.com/MarlinFirmware/Marlin/pull/17644#issuecomment-618010274. seems is a hardware limitation)

### CODE REVIEW

**Comment by RudolphRiedel** [comment]
What about this:
screen_data.InterfaceSettingsScreen.brightness = constrain((value * 128UL) / 0xFFFF, 1, 11);

I have not tested it but it looks to me like this limits the value to a range from 1....11 which is completely broken.

**Comment by sl1pkn07** [comment]
is one of things i not touch because idk how code it, also i disable the dim for my panel so i can't test

@thinkyhead ?

**Comment by RudolphRiedel** [comment]
As I wrote, just go with:
screen_data.InterfaceSettingsScreen.brightness = max(11, (value * 128UL) / 0xFFFF);

I tried it and it works, 11 is low enough for my display as well.
I really do not know why my line with the "max(1, (value * 128UL) / 0xFFFF);" got replaced so fast.

I tried the other line now and as I expected it is not working, I can not even change the value between 1 and 11, the slider is just limited to 11.

**Comment by sl1pkn07** [comment]
done

**Comment by thinkyhead** [comment]
Thanks for the corrections. I changed code according to answers to my questions and comparing code from two sources. Apparently I was mistaken to believe that the brightness should range between 1 and 11.

**Pull request merged**
