### PR TITLE
Support FYSETC Spider board

### PR DESCRIPTION
**Pull request by GerogeFu**
Support FYSETC Spider board

### CODE REVIEW

**Comment by ellensp** [comment]
shouldn't new files be Copyright (c) 2021 ? ie pins_FYSETC_SPIDER.h

**Comment by Adi146** [comment]
you are always checking HEATER_0_PINs not HEATER_1_PIN or BED. So e.g. HEATER_BED_PIN will never be defined if you define HEATER_0_PIN

**Comment by thisiskeithb** [comment]
> you are always checking HEATER_0_PINs not HEATER_1_PIN or BED. So e.g. HEATER_BED_PIN will never be defined if you define HEATER_0_PIN

See https://github.com/MarlinFirmware/Marlin/pull/21483

**Comment by GerogeFu** [comment]
Thanks guys for these fixs.

**Comment by GerogeFu** [comment]
Oh , i found another issue , here https://github.com/MarlinFirmware/Marlin/pull/21578/commits/b1887d1806b7491b22d3186172a806c646785811

**Pull request merged**
