### PR TITLE
Lcd interactive mesh edit refinements

### PR DESCRIPTION
**Pull request by Tannoo**
[Easier Diff](https://github.com/MarlinFirmware/Marlin/pull/7077/files?w=1)

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looking like a cool set of changes. Have you also taken a look at #5441 which adds an extra layer of optimization to the LCD support? It optimizes for size, and performance should be noticeably improved too because the utf-mapper conversion is done on all the strings in advance, not at runtime. It reduces the number of language files, because only UTF-8 language files are needed.

IT would be good to get that thing done and merged too, but it doesn't have to be before Marlin 1.2/2.0.

**Comment by Tannoo** [comment]
I did not see that PR. This project has been in the works for at least a month and I was just trying to keep the branch up to date along with getting it working.

This PR was to polish it up some more.

**Comment by thinkyhead** [comment]
The `.h` files included in `ultralcd.cpp` were not intended to be split out, per se, but were designed to add onto `ultralcd.cpp`. They are all basically `.cpp` files with `.h` extensions so they won't be compiled unless included.

The design intent of using these several `.h` files was (I surmise) to mimic in a C-like way a pair of subclasses, each implementing a set of pure virtual functions in the root class. (This is called a "protocol" in languages like Objective-C — a promise to implement some methods.)

Anyway, instead of trying to "clean up" the `.h` files never intended to be used as separate compilation units (`.cpp` files), let's skip this ugly stepsister phase and commit to implementing ultralcd as a singleton class, in emulation of the other singletons. Then all function signatures will be in `ultralcd.h`, and the class methods can either be divided by category into separate `.cpp` files, and/or the DOGM/HD44780 methods can be implemented in a `friend` class to `class ultralcd`.

Maybe it will still be kind of ugly, but I think it will be a good start on seeing the internal organization of these many lcd functions, and getting a start on simplifying them, cutting waste, and making a more standard API for LCD-command handler interaction.

To save a lot of work, the menu handlers should remain regular functions. Eventually the screen and menu handlers might be better done as a separate class, since screen handlers have common special needs. Anyway, I guess this starts to get into the weeds of the LCD API redesign, which for expediency needs to wait till 2.0 — because there just aren't enough hours in the day, alas.

----

P.S. I broke your PR when resolving conflicts. I resolved the conflicts correctly, but you need to add `const bool blink` as an argument to `lcd_implementation_status_message()` because that patch (#7071) was made recently, after this PR's branch was started.

**Comment by Tannoo** [comment]
Yeah, I ran into that also, plus Roxy was working on this one. I made another branch based on this one and worked through the conflicts...and got #7086 PR. The 7086 compiles fine, but the coordinate numbers are blank when the custom user scripts are enabled. My IDE doesn't complain, but Travis does.

**Comment by Tannoo** [comment]
I'm currently at work so, I can't do much until at least morning.

**Comment by Tannoo** [comment]
>you need to add const bool blink as an argument to lcd_implementation_status_message() because that patch (#7071) was made recently, after this PR's branch was started.

I can do that instead, if that is what you prefer.

**Comment by Tannoo** [comment]
Done, but it's not compiling.

**Comment by thinkyhead** [comment]
> Done, but it's not compiling.

Looks a conditional in the new LCD code is out of wack:
```
sketch/ultralcd_impl_HD44780.cpp: In function 'void lcd_set_custom_characters()':
ultralcd_impl_HD44780.cpp:335: error: 'LCD_BEDTEMP_CHAR' was not declared in this scope
   createChar_P(LCD_BEDTEMP_CHAR, bedTemp);
```
https://travis-ci.org/MarlinFirmware/Marlin/builds/244530873?utm_source=github_status&utm_medium=notification

Just follow the bouncing Travis — it'll tell you what needs fixing.

**Comment by Tannoo** [comment]
FYI:

>The 7086 compiles fine, but the coordinate numbers are blank when the custom user scripts are enabled. My IDE doesn't complain, but Travis does.

Whatever the changes were over the last several merges.... This is now fixed. The coordinate numbers are back on the status screen when CUSTOM_USER_MENUS is enabled.

**Comment by Tannoo** [comment]
>Just follow the bouncing Travis — it'll tell you what needs fixing.

haha... yes. Easier said than done sometimes. I will track it down later.

**Comment by Tannoo** [comment]
And, I have followed it earlier this morning. I found that `LCD_BEDTEMP_CHAR` and a few others that Travis complained about, were declared in `conditionals_LCD.h`. AND `conditionals_LCD.h` was already included in `ultralcd_impl_HD44780.cpp`.

So, I slowly put it away for now.

**Comment by thinkyhead** [comment]
True. Nothing should need to include `Conditionals_LCD.h` since `MarlinConfig.h` takes care of that. Anyway, I'm off to work now, but will be around later to scan the endless queue and see how things are shaping up.

**Pull request closed without merging**
