### PR TITLE
New Configuration file layout

### PR DESCRIPTION
**Pull request by Wackerbarth**
This neutralizes the sources tree and prepares for the deletion of the unused docmenting clutter in EVERY Configuration file.

Before we actually strip out all of the unused parts, we should establish a template that shows a standardized form for each of the entries.

The primary change that will be initially noticed is that, just as the Travis build (and anyone not using the default configuration) has been doing for some time, each user will have to select an appropriate set of Configuration files for his build.

Additional comments to help direct the user are welcome.

### CODE REVIEW

**Comment by clefranc** [comment]
@Wackerbarth I've just tried your https://github.com/Wackerbarth/Marlin/tree/TestNewConfigurationFiles. Let's say it's a little confusing from a new user perspective. In my case, I'm accustomed to copy configuration files from the example_configurations folder, not a big deal.

For someone using the Arduino IDE for the first time, downloading and using this new configuration scheme is not intuitive as before. If you hit the compile button right away, the compiler just hang... I expected to get an error message, something to guide you, but nothing shows up.

If this will now be mandatory to copy configuration files from within folders, then perhaps indicate the proper way to build Marlin in the first tab of the IDE (the Marlin.ino, the one that nobody never read). This will give a good starting point.

Or maybe I have not grasped the scope of your restructuration.

**Comment by Wackerbarth** [comment]
I am surprised that you do not get the error when you compile.
As you will note if you inspect the "installed" Configuration.h file, it has a #error as the body of the file.

The suggestion of placing additional instructions in the .ino (as well as README files, etc. is a good one.

My intention is to get this structure in place so that we can also begin cleaning up to individual files.

Right now, there is so much "chaff" that you cannot really understand the important stuff.

**Comment by clefranc** [comment]
@Wackerbarth I saw your configuration placeholders, and I was expecting an error message too, instead, I get this:

```
Using library Wire in folder: C:\Users\Christian\AppData\Roaming\Arduino15\packages\arduino\hardware\avr\1.6.2\libraries\Wire 
Using library U8glib in folder: C:\Program Files (x86)\Arduino\libraries\U8glib (legacy)
Using library LiquidCrystal in folder: C:\Program Files (x86)\Arduino\libraries\LiquidCrystal 
Using library SPI in folder: C:\Users\Christian\AppData\Roaming\Arduino15\packages\arduino\hardware\avr\1.6.2\libraries\SPI 

C:\Users\Christian\AppData\Roaming\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino2/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10604 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -IC:\Users\Christian\AppData\Roaming\Arduino15\packages\arduino\hardware\avr\1.6.2\cores\arduino -IC:\Users\Christian\AppData\Roaming\Arduino15\packages\arduino\hardware\avr\1.6.2\variants\mega -IC:\Users\Christian\AppData\Roaming\Arduino15\packages\arduino\hardware\avr\1.6.2\libraries\Wire -IC:\Program Files (x86)\Arduino\libraries\U8glib -IC:\Program Files (x86)\Arduino\libraries\LiquidCrystal\src -IC:\Users\Christian\AppData\Roaming\Arduino15\packages\arduino\hardware\avr\1.6.2\libraries\SPI C:\Users\CHRIST~1\AppData\Local\Temp\build1141509824924517133.tmp\blinkm.cpp -o C:\Users\CHRIST~1\AppData\Local\Temp\build1141509824924517133.tmp\blinkm.cpp.o 
```

After that, the Verify/Compile icon of the IDE just stay lit (1.6.4).

I agree that simplifying the process of configuring a printer (custom or commercial) need improvements. The escalation of error messages (from configuration, conditionals, sanity and others) should be a relatively good starting point, if implemented properly.

I've read a discussion some months ago, about configuration overrides, like having default config files, but we just put the defines we need in a _simplified configuration file_ for our customized printer. Is your proposal can do this? Sorry for not understanding clearly your PR or introducing irrevelant comments.

**Comment by Wackerbarth** [comment]
Compared to what was there last week, I haven't really changed anything.  For distribution with your printer, IMHO, you should provide, in our examples folder, the exact files that you want your users to use.
It would also make sense for you to install a copy of those files in place of my placeholder files.
Hopefully, that would mean that your customized source is just one simple commit tacked onto our release. (And would be just a "cherry pick" or "rebase" away from moving to the next release).

Now, because I think it is easier to understand, and certainly makes our testing of options clearer, I recommend that you use an Options.h file to include the optional components.

It is my intention to move toward a scheme that utilizes the build hook mechanism that I added to the Arduino IDE to allow the build process to do the copy operation based on a menu selection.

But those are just refinements that are not essential.

**Comment by Wackerbarth** [comment]
When I try it on my Mac OS X version, I get the expected error behavior.

```
Using library Wire in folder: /Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire 
Using library LiquidCrystal in folder: /Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/libraries/LiquidCrystal 
Using library SPI in folder: /Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI 

/Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10605 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I/Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/hardware/arduino/avr/variants/mega -I/Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire -I/Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/libraries/LiquidCrystal/src -I/Users/Projects/Arduino/build/macosx/work/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/SPI /var/folders/qq/sc5wp5896yg_3xm169_4fw040000gn/T/build1502937009755409381.tmp/blinkm.cpp -o /var/folders/qq/sc5wp5896yg_3xm169_4fw040000gn/T/build1502937009755409381.tmp/blinkm.cpp.o 
In file included from /var/folders/qq/sc5wp5896yg_3xm169_4fw040000gn/T/build1502937009755409381.tmp/Marlin.h:22:0,
                 from /var/folders/qq/sc5wp5896yg_3xm169_4fw040000gn/T/build1502937009755409381.tmp/blinkm.cpp:5:
/var/folders/qq/sc5wp5896yg_3xm169_4fw040000gn/T/build1502937009755409381.tmp/Configuration.h:3:2: error: #error You must install configuration files to match your printer
 #error You must install configuration files to match your printer
  ^
In file included from /var/folders/qq/sc5wp5896yg_3xm169_4fw040000gn/T/build1502937009755409381.tmp/Marlin.h:23:0,
                 from 
```

etc.

But, I do think that your suggestion to put some instructions at the very top of the Marlin.ino is a good idea.

**Comment by Wackerbarth** [comment]
#2269 now provides this code, and more

**Pull request closed without merging**
