### PR TITLE
Fix TouchMI probe movement (left side)

### PR DESCRIPTION
**Pull request by Fourmi**

### CODE REVIEW

**Comment by tpruvot** [comment]
??? no explanation ?

**Comment by Fourmi** [comment]
Explanation it's on the title of PR sorry.
Fix: remove useless move when TouchMI probe is on the left X carriage because G28 deploy probe

**Comment by tpruvot** [comment]
Ok sorry, i asked to follow a bit... users may ask why that was changed...

**Comment by Fourmi** [comment]
No problem Tanguy, thx for your job :)

**Pull request merged**
