### PR TITLE
Fix missing temp_error declarations

### PR DESCRIPTION
**Pull request by thinkyhead**
- Fix for #1591 replacing #1595

### CODE REVIEW

**Comment by AnHardt** [comment]
@thinkyhead 
Not bad!
But why inline in 'inline void _temp_error'? The decision is already made - well stop the print due to an error. We are not in a hurry anymore. Why not saving some bytes?

**Comment by AnHardt** [comment]
Sorry. Made not mad.

**Comment by Grogyan** [comment]
Missing changes from #1595 which fixes #1591

**Comment by AnHardt** [comment]
@Grogyan 
Don't worry. Should have the same effect.

**Comment by Grogyan** [comment]
Tried to compile it yesterday for the MAX6675 after the merge of #1598 but it did not, until I manually made the changes from #1595

**Comment by AnHardt** [comment]
@Grogyan 
??? #1598 compiles for me.

**Comment by thinkyhead** [comment]
This does the trick. #1595 had the right idea, but the wrong implementation. The functions only need to appear before the code that calls them, and we don't need to expose these functions in the header file. This PR also takes the opportunity to consolidate the redundant code shared by these functions.

**Comment by Grogyan** [comment]
Compiles ok for me now

**Pull request merged**
