### PR TITLE
Optional Large/Fullscreen Bootscreen for TFT_COLOR_UI

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Allow users to enable large/fullscreen bootscreen for `TFT_COLOR_UI`. Due to the large file size, this cannot be enabled by default for all boards with 480x320 TFTs.

320x240 had the fullscreen bootscreen enabled by default, but was changed to the smaller bootscreen for consistency. This can easily be reverted if we want to retain the large bootscreen on those screens.

Tested on an Anet ET5X with Anet TFT35 & TFT28.

### Benefits

- 480x320 TFTs can now use the large bootscreen by disabling `BOOT_MARLIN_LOGO_SMALL`.
-  Lower flash usage on all boards since the smaller bootscreen is now enabled by default.

### Configurations

[Any of the default ET4/5 configs](https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Anet).

### Related Issues

None.

### CODE REVIEW

**Review by rhapsodyv — APPROVED** [review]

**Comment by thisiskeithb** [comment]
@rhapsodyv asked me this on Discord, so I thought I'd explain it here too:

I had to move the URL text location up 20px on the 480x320 resolution because text overlapped the horizon line on the large Marlin bootscreen, so now it matches the 320x240 large bootscreen location.

To simplify things, the URL text Y location could be used for the smaller bootscreen(s). Otherwise, the URL text is displayed 1/2 way between the bottom of the small bootscreen & bottom of the screen:

480x320 fullscreen example:


480x320 smaller bootscreen example:

**Comment by thinkyhead** [comment]
I've tweaked the code to center the URL horizontally.

**Comment by rhapsodyv** [comment]
Using `BOOT_MARLIN_LOGO_SMALL` this way will break every build for TFT now on...

Old graphical lcd have different defaults from the Color UI.

For old graphical lcd we use big as default. So we have a option to use the small logo.

For color ui, we can't use big as default, as the big image only fits on big F4 boards. So, for Color UI, the default should be SMALL.

But how we will make different defaults using only one option?
Maybe adding a #if on the config?! I don't know if it will work well...

For that reason that @thisiskeithb added a new option just for Color UI.

**Comment by thinkyhead** [comment]
I've already updated the configs repository so that `BOOT_MARLIN_LOGO_SMALL` is enabled by default (for all displays), so it will only affect cutting-edge users who try to use old configs, until they update them to the newest layout.

**Comment by tpruvot** [comment]
hmm side effect maybe, but i had to do that to use a normal one on 128x64 upscaled dogm

https://github.com/tpruvot/Marlin/commit/79543d0ecd503cda87d0ff914e14f17dc999fab8

HAS_MARLINUI_U8GLIB is maybe not the right constant to check

**Comment by thisiskeithb** [comment]
> hmm side effect maybe, but i had to do that to use a normal one on 128x64 upscaled dogm
> 
> [tpruvot@79543d0](https://github.com/tpruvot/Marlin/commit/79543d0ecd503cda87d0ff914e14f17dc999fab8)
> 
> HAS_MARLINUI_U8GLIB is maybe not the right constant to check

There's `TFT_SCALED_DOGLCD`:

https://github.com/MarlinFirmware/Marlin/blob/a8c361c93bdda3110d147c5f47f96f57298c0a13/Marlin/Configuration_adv.h#L1596-L1606

**Comment by tpruvot** [comment]
no, well TFT_CLASSIC_UI is same, but its the reverse, its not needed for this UI... big one is only a few bytes bigger

**Comment by thisiskeithb** [comment]
> no, well TFT_CLASSIC_UI is same, but its the reverse, its not needed for this UI... big one is only a few bytes bigger

They're the same because of:
https://github.com/MarlinFirmware/Marlin/blob/a8c361c93bdda3110d147c5f47f96f57298c0a13/Marlin/src/inc/Conditionals_LCD.h#L325-L328

I was surprised to see the small bootscreen made the standard for _everything_, but that wasn't part of my original commits 🙂

I was about to put in a PR to include `TFT_SCALED_DOGLCD` as part of the check.

**Comment by tpruvot** [comment]
yep avoid this "internal" one... may not be testable/set in the Configuration_adv.h ... i think this #if TFT_SCALED_DOGLCD in config should be replaced by #if TFT_CLASSIC_UI .. but its not our problem there :p

**Comment by thisiskeithb** [comment]
> yep avoid this "internal" one... may not be testable/set in the Configuration_adv.h ...

I just tested it and `TFT_SCALED_DOGLCD` works. I'll put in a PR shortly.

**Comment by tpruvot** [comment]
yep seems to works ive custom colors but... rmm well, do as you want :p

**Comment by thisiskeithb** [comment]
> yep seems to works ive custom colors but... rmm well, do as you want :p

Might as well keep with `TFT_SCALED_DOGLCD` since it's already used in the config 🙂 

See https://github.com/MarlinFirmware/Marlin/pull/20583 for the fix.

**Pull request merged**
