### PR TITLE
Marlin + smart Back-Up

### PR DESCRIPTION
**Pull request by recmaster1**
Hello,
3D printer spend a lot of time to make some detail. During this period a power cut could happend. This period can be along time. The power of Back-up is low, but it smart. Back-up can manage of 3d printer via USB. The main idea is how to make a soft freeze and continue operations of 3d printer by back-up?

### CODE REVIEW

**Comment by thinkyhead** [comment]
@recmaster1 Did you mean to target `RCBugFix` with this PR? Please resubmit whenever you like.

**Comment by recmaster1** [comment]
Why you close my request? Isnt it a area to requests to new functionality?

**Comment by recmaster1** [comment]
Why you close my request? Isnt it a area to requests to new functionality?

> Пятница,  2 сентября 2016, 7:58 +03:00 от Scott Lahteine notifications@github.com:
> 
> Closed  #4746 .
> —
> You are receiving this because you were mentioned.
> Reply to this email directly,  view it on GitHub , or  mute the thread .



**Comment by Blue-Marlin** [comment]
If you do not want to contribute code please use https://github.com/MarlinFirmware/Marlin/issues not https://github.com/MarlinFirmware/Marlin/pulls. We can't find your code in this PR. Pleas try to be a bit more verbose about what you want.

**Comment by thinkyhead** [comment]
This feature has already been requested many times.
Someone might implement it someday, time willing.
I will keep this closed but mark it as a duplicate.

As mentioned, if you didn't intend to submit code, then you need to post an issue, not a Pull Request. Because we will simply close nonsensical pull requests.

**Comment by recmaster1** [comment]
Ok, clear )

**Pull request closed without merging**
