### PR TITLE
M118 echo to serial

### PR DESCRIPTION
**Pull request by thinkyhead**
Applied changes to #7162 for merge

http://reprap.org/wiki/G-code#M118:_Echo_message_on_host

### CODE REVIEW

**Comment by benlye** [comment]
Cool.  Let me check that adding `echo:` doesn't interfere with `// action:command` commands.

On the other hand, if the user wants the output to be echoed in Repetier Host, perhaps they could add `echo:` themselves, like `M118 echo: Some text to output`?

**Comment by benlye** [comment]
@thinkyhead, this doesn't do what I wanted because action commands __aren't__ parsed if they start `echo:`

Can you remove `SERIAL_ECHO_START();` and leave it up to the user to put in the `echo:` if they want the output to be echoed in Repetier?

**Comment by thinkyhead** [comment]
No problem. Do you need the double slashes appended automatically?

**Comment by benlye** [comment]
No, happy to add those myself in my M118 commands.

**Comment by thinkyhead** [comment]
How about this addition: `M118 A` will prepend double-slash, and `M118 E` will prepend `echo:`?

**Comment by benlye** [comment]
> How about this addition: `M118 A` will prepend double-slash, and `M118 E` will prepend echo:?

Not sure - seems like we might be over-thinking it now.  Why not just let it send whatever string follows `M118` and leave getting the syntax right for the use case up to the end-user?

**Comment by thinkyhead** [comment]
Fair enough, though I might add the parameters too as a point of self-documentation for the G-code.

**Comment by benlye** [comment]
Sounds good to me.

**Pull request merged**
