### PR TITLE
Fix readme dev repository link

### PR DESCRIPTION
**Pull request by GMagician**

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I’ll paste this from my other comment:

@thinkyhead The readmes between `bugfix-2.0.x` and `2.0.x` don't match, so where do we make the change?

The readme in [`2.0.x`](https://github.com/MarlinFirmware/Marlin/blob/4c261313eec206280e1c1163563e9fe62a89ea96/README.md) has a link to "Submit New Features to the ([dev-2.0.x](https://github.com/MarlinFirmware/Marlin/tree/dev-2.0.x)) branch", but that branch doesn't exist:
https://github.com/MarlinFirmware/Marlin/blob/4c261313eec206280e1c1163563e9fe62a89ea96/README.md#L42-L47

The readme in [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/blob/f64649933f3a2195df7a2bd3ec95ab6ed3885975/README.md) doesn't have that section of text, so there's nothing to fix/change there:
https://github.com/MarlinFirmware/Marlin/blob/f64649933f3a2195df7a2bd3ec95ab6ed3885975/README.md#L54-L60

Should these be synced back up?

**Comment by thinkyhead** [comment]
Guaranteed to work:
```
git fetch upstream
git checkout upstream/2.0.x -b my_changes_PR
```

**Comment by GMagician** [comment]
@thinkyhead,  I'm confused....
As stated by @thisiskeithb (and by me on previous PR) readme.md in bugfix-2.0.x is different from 2.0.x so this fix can't be done in bugfix-2.0.x but only in 2.x.
Then or we merge 2.x readme into bugfix-2.0.x  (I'm not the one that can decide) or we have to modify 2.x...why just close PR without asking or clarifying?

Edit:
I don't understand what's the purpose of:
```c++
git fetch upstream
git checkout upstream/2.0.x -b my_changes_PR
```

**Comment by GMagician** [comment]
@thisiskeithb and @thinkyhead what's happening here? I made a change just to 1 file and now I see 8 modified files, something wrong with my repo?

**Pull request closed without merging**
