### PR TITLE
Fix Issue/Feature Request Templates

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Issues/Feature Requests no longer work and it while may be a temporary GitHub glitch, @ellensp found these warnings when looking at the templates:

<p align="center"></p>

### Requirements

GitHub

### Benefits

May fix Issue/Feature Requests not showing up, but if not, the `issue_body` lines should probably be removed anyway.

### Configurations

N/A

### Related Issues

N/A. Discussed on Discord.

### CODE REVIEW

**Comment by cp2004** [comment]
It looks like issue_body was removed. This is what was changed at OctoPrint:

https://github.com/OctoPrint/OctoPrint/pull/4081

**Comment by thisiskeithb** [comment]
> It looks like issue_body was removed. This is what was changed at OctoPrint

Hmm. There was also a recent change to remove the `title` key: https://github.com/OctoPrint/OctoPrint/commits/master/.github/ISSUE_TEMPLATE/bug_report.yml

**Comment by cp2004** [comment]
That one was because GitHub broke something their end, it wouldn't recognize empty title strings. You should be fine where there's something in the field.

**Comment by thisiskeithb** [comment]
Closing since Scott committed the fix directly: https://github.com/MarlinFirmware/Marlin/commit/392d01555d8f4ae85cf7194d41f21b84938d71cb

**Pull request closed without merging**
