### PR TITLE
[2.0.x] Different NEOPIXEL types

### PR DESCRIPTION
**Pull request by thinkyhead**
Derived from #7849, #7918 for 1.1.x, edited to allow Neopixel to coexist with other LED options.

----
Same as #7728 but for 2.0.x,
Lot of cleanup and remove references in whole code to other "LED files" than leds.h. Now will be much easier to add next drivers/libraries. e.g. FastLED. But bad news, currently FastLED is suporting only RGB devices (no RGBW)

### CODE REVIEW

**Comment by Tannoo** [comment]
Any chance of moving the NEOPIXEL_PIN to the pins files?
Since they are different for every board.

**Comment by AnHardt** [comment]
@Tannoo 
Do you know any board where a NEOPIXEL is on board, or has a dedicated connector?
As long as the answer is no - Configuration.h is the right place for the pin definition.

**Comment by Tannoo** [comment]
Ok. Is that the same for the filament runout sensor?

**Comment by AnHardt** [comment]
I think so.
Despite the new Prusa has one.
But that could have a example configuration. The board is more universal then the machine.

**Comment by Tannoo** [comment]
I am only asking.. as the discription is making notes of different board pins. And pin 4 as deault, conflicts with ramps filament runout sensor that is also pin 4.

**Comment by Tannoo** [comment]
This can cause issues with new users.

**Comment by SCiunczyk** [comment]
@thinkyhead I'm afraid I can't compile this version now :-( (with NEOPIXEL).

first problem: the NEO_WHITE should be as LED_WHITE defined of four components (there is no default parameters in neopixel_set_led_color)

```
Marlin\src\feature\leds\leds.cpp:39:42: error: too few arguments to function 'bool neopixel_set_led_color(uint8_t, uint8_t,
 uint8_t, uint8_t, uint8_t)'
neopixel_set_led_color(NEO_WHITE, p);
```
second problem:
```
Marlin\src\gcode\temperature\M104_M109.cpp: In static member function 'static void GcodeSuite::M109()':
Marlin\src\gcode\temperature\M104_M109.cpp:233:51: error: 'set_neopixel_color' was not declared in this scope
set_neopixel_color(pixels.Color(NEO_WHITE));
```
IMHO this is redundant because function set_led_color calls set_neopixel_color inside. And there is no reason to treat neopixel different from others and include calls to neopixel directly inside firmware code. 

Maybe just define function set_led_white() in leds.h/c and inside this function manage all types of WHITEness.

I like the idea to have only one place to manage all types of leds.

**Pull request merged**
