### PR TITLE
Add Ender-5 Pro config

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

The Ender-5 Pro is nearly identical to the Ender-5 firmware-wise, but Creality has switched to a new leadscrew that keeps the bed in place when power is cut. ~~This config will use the Ender-5's status screen until I can get someone to send me a closeup picture of the "Pro" version since this firmware isn't available from Crealtiy.~~

Ender-5 Pro status screen has been added thanks to the photo from @looxonline:

image

### Benefits

Prints are no longer half as tall.

### Related Issues

None.

### CODE REVIEW

**Comment by looxonline** [comment]
I'll snap a shot in the morning and upload it.

**Comment by thisiskeithb** [comment]
> I'll snap a shot in the morning and upload it.

Based on the Ender-3 Pro, I'm guessing it'll look something like:
image

**Comment by looxonline** [comment]
EA545FA3-AC8E-4F74-90BD-2BA631EE02C8

**Comment by thisiskeithb** [comment]
Thanks @looxonline! I've updated the PR with the new status screen.

**Comment by lpla** [comment]
Hi. I have an Ender-5 with the upgrade kit from Creality (so, theoretically, now an Ender-5 Pro). Could you @thisiskeithb post pictures of this different Z axis leadscrew? I would like to know all differences between the stock Ender-5 and Pro version out of the 1M Capricorn Tubing+Silent Board+Metal Extruder upgrade pack.

EDIT: from what I see here, it has the same leadscrew for Z axis that I got with my Ender-5: https://youtu.be/yhRKsGrsxh8?t=99

But in this video, the leadscrew is different: https://youtu.be/Mptzj0Owomw?t=337

Is the second one the one you are referring to? Also, does it need to specify different steps than the Ender-5 in Marlin like in this kind of leadscrew?: https://youtu.be/lBpXHWJG7aM?t=696

EDIT2: Okay, after carefully watching the last video I posted and some other forum posts, seems like the Ender-5 Pro has a 4mm lead Z-axis leadscrew (with anti-backslash) given that you needed to double all stepper values to print correctly (not 'half as tall'). The reduction from the 8mm lead in the Ender-5 to the 4mm lead in the Ender-5 Pro is what prevents bed dropping/falling: https://3dprinting.stackexchange.com/questions/4031/would-using-a-leadscrew-with-1-or-2-mm-lead-en-lieu-of-8-mm-result-in-a-better

Maybe it should be also interesting to create an "Ender-5 2mm lead" config file with Ender-5 Pro values doubled, more or less with the values from the last video I posted from Kersey Fabrications, as it looks like a good cheap mod for the Ender-5 (or even Ender-5 Pro) given the incremented Z-axis precision and better bed dropping prevention.

Could anyone confirm this information?

**Comment by lpla** [comment]
Looks like also new Ender 5 sold units have this new leadscrew too. See TH3D comment:

https://github.com/houseofbugs/TH3D-Unified-U1.R2/blob/cd023ff4a13f436264d55dd5e01bffc03284743e/TH3DUF_R2/Configuration.h#L421

**Pull request merged**
