### PR TITLE
New AVR internals to combat the AVR Pin Peripheral Conflict

### PR DESCRIPTION
**Pull request by quiret**
### Description

titlecard_small

Watch the video: https://www.youtube.com/watch?v=jMgCvRXkexk

The AVR has peripheral functions whose mapping to pins is fixed (the alternate pin functions). When trying to use AVR pins for GPIO purposes that are currently driven by AVR peripherals (enabled bits in HW registers as shown by the TRM Overriding Signals tables) the process will fail (unable to turn off annoying beeper). This problem is hard to manage and with this PR I want to provide a runtime solution: the new AVR internals with the _ATmega_savePinAlternates and _ATmega_restorePinAlternates functions! A database of pins along with their alternate functions for each AVR MCU family has been created. This allows the program to know what conflicts may exist and disable the conflicting peripherals, allowing for GPIO use without conflict.

Here is an example code:

```
// 1) save any potentially conflicting peripheral state
// 2) disable conflicting peripherals
pin_dev_state_t _saved_beeper = _ATmega_savePinAlternates( { BEEPER_PIN } );

// 3) use the GPIO pin
OUT_WRITE(BEEPER_PIN, HIGH); delay(500);
OUT_WRITE(BEEPER_PIN, LOW); delay(1000);

// 4) restore the conflicting peripheral state
_ATmega_restorePinAlternates( { BEEPER_PIN }, _saved_beeper );
```

In this code the BEEPER_PIN is safely used because peripherals possibly assigned to it are disabled for the duration we want to use the beeper for.

I have made a small change to the AVR HAL to add a beepfix at boot. The problem (on the GT2560) could root in unclean operation of bootloaders or redundant activation of peripherals (USART).

### Benefits

Solid ways to combat the AVR Pin Peripheral Conflict.

### Related Issues

https://github.com/MarlinFirmware/Marlin/pull/24911 (depends on this PR)

### CODE REVIEW

**Comment by quiret** [comment]
Looks like I forgot one TRM implementation (__AVR_ATmega644P__). I will get that done next week.

**Comment by quiret** [comment]
Alright. The missing TRM has been implemented. I did my best mapping the entire HW spectrum of AVR MCUs into proper C++ views. Please consider taking those internals as replacement for the old & hacky original toolchain things!

**Comment by thinkyhead** [comment]
Since AVR boards have the least amount of Flash and SRAM, anything that might increase the build size is disabled by default and only enabled where necessary on boards with adequate space. This feature uses 2KB of Flash and almost 100 bytes of SRAM, so I made sure it is disabled by default, only enabled with the `HAL_AVR_DIRTY_INIT` flag. I see, however, that the `HAL_AVR_DIRTY_INIT` flag might only apply to `_ATmega_resetperipherals` so we might need to choose another option name to enable this code.

I haven't personally encountered an AVR board that leaves the beeper enabled, but I have had some LPC176x and STM32-based boards that beep at a low level on startup, only turning off the beeper when they get to `setup()`. In general, we haven't had to deal with "alternate functions" since we take over the hardware and timers. And, in Marlin we don't need to use both GPIO and alternate functions on the same pin, so there is not a specific need to save and restore the flags that invoke alternate functions vs. GPIO. Ultimately, we just need to get the hardware into a "clean" state at startup so that pins are not doing Hardware-PWM or Timer/Change ISR unless we specify those.

Given our modest requirements, is there some way to get (for example) the `BEEPER_PIN` state initialized properly at startup without requiring 2KB of additional code that is mostly unused? And, are there some build flags we can set so that AVR ArduinoCore is not redundantly initializing peripherals with bad assumptions?

**Comment by quiret** [comment]
> Since AVR boards have the least amount of Flash and SRAM, anything that might increase the build size is disabled by default and only enabled where necessary on boards with adequate space. This feature uses 2KB of Flash and almost 100 bytes of SRAM, so I made sure it is disabled by default, only enabled with the `HAL_AVR_DIRTY_INIT` flag. I see, however, that the `HAL_AVR_DIRTY_INIT` flag might only apply to `_ATmega_resetperipherals` so we might need to choose another option name to enable this code.

The HAL_AVR_DIRTY_INIT feature is designed to combat weird bootloaders that do not cleanly transfer device state to the running AVR application. The bootloader can include functionality to flash firmware from serial peripherals, using extended hardware features, so the peripheral states can be in a random state at Marlin launch. The inclusion of this function _ATmega_resetperipherals ensures that device state is equal to the one specified by the technical reference manuals. I strongly encourage a proper Marlin device state.

> (...) Ultimately, we just need to get the hardware into a "clean" state at startup so that pins are not doing Hardware-PWM or Timer/Change ISR unless we specify those.

I object to that. Developers usually are lazy and their mindset usually is to set their state and work with peripherals. And usually the cleanup is forgotten in their libraries. On the AVR this problem is greater than on other boards specifically because the Pin Peripheral Conflict exists. On other boards it does not exist because you can MUX individual pins out of peripheral activity.

> but I have had some LPC176x and STM32-based boards that beep at a low level on startup, only turning off the beeper when they get to setup()

What you are describing appears to be weird bootloader design, assuming a correctly designed Marlin base code. This can only be fixed by performing a clean reset of device state a'la _ATmega_resetperipherals at Marlin launch. Unfortunately this problem persists on all architectures due to no control over the bootloader. You have to acknowledge this reality and provide a means to clean-up device state once Marlin takes over control after the bootloader!

> Given our modest requirements, is there some way to get (for example) the `BEEPER_PIN` state initialized properly at startup without requiring 2KB of additional code that is mostly unused?

Conceptually the call to _ATmega_digitalWrite should not take that much space. It sounds like a compiler code-generation issue. I will investigate the source of this problem and minimize the code size as much as possible. Thank you for providing your guidance, especially the "least-firmwarebinary-size-increase" mantra. I want to make sure that code-size is optimized and not inlining-speed.

> And, are there some build flags we can set so that AVR ArduinoCore is not redundantly initializing peripherals with bad assumptions?

I would like to not fix all dependencies of AVR libraries because that code is old and such as that has design flaws like that. To prevent the necessity perfect old code I provide solutions that work for our purposes all the time. I think you make a good point that if there is no such flaw detected on a board certain optimizations can be applied by the use of preprocessor configurations to avoid firmware size increase. But by default I want to recommend those safety enhancements, to promote a more robust Marlin firmware. **Since you have not detected this problem yourself it should show how important the input from individual experts should be to you.**

**Comment by quiret** [comment]
I am sorry but I have decided to halt my activities on this PR for an indetermined amount of time. You are free to decide whether to continue it yourself. Thank you to the Marlin firmware community for providing this interesting playing ground for testing my ideas and vision. I hope that Marlin will continue to go towards the best 3D printing solution! Hopefully my ideas have inspired you on how to continue this software!

**Pull request merged**
