### PR TITLE
M166 Gradients, LCD Menu for 2-channel Mixer (Geeetech A10M/A20M)

### PR DESCRIPTION
**Pull request by thinkyhead**
This is a port of the Mixing and Gradient features from the [Geeetech fork of Marlin](https://github.com/Geeetech3D/Prusa_I3_3Dprinter/tree/master) with several changes to be more generalized and make use of the latest supporting code.

Some aspects of this feature require a mixing extruder with 2 channels, since this allows the current mix to be displayed on the Status Screen in only ~10 characters, and for mix proportions to be determined automatically.

A mix editing screen is provided for 3-channels or more. The mix is normalized when editing is complete. This can be tested with 2 channels by setting `CHANNEL_MIX_EDITING` to 1.

```
M166: Set a simple gradient mix for a two-component mixer
      based on the Geeetech A10M implementation by Jone Liu.

  S[bool]  - Enable / disable gradients
  A[float] - Starting Z for the gradient
  Z[float] - Ending Z for the gradient. (Must be greater than the starting Z.)
  I[index] - V-Tool to use as the starting mix.
  J[index] - V-Tool to use as the ending mix.

Example: M166 S1 A0 Z20 I0 J1
```

### CODE REVIEW

**Comment by AnHardt** [comment]
Please give me some time to read an understand this.

Are you targeting to some kind of compatibility to Geeetech, or are you open for different concepts?

**Comment by thinkyhead** [comment]
> Are you targeting to some kind of compatibility to Geeetech, or are you open for different concepts?

This is not exactly like the Geeetech implementation, since this uses virtual tools as the start and end mixes for the active gradient. While the Geeetech implementation only considers two-channel mixing, this version will allow for gradients that incorporate 3 or more mixing channels.

The basic methodology is the same. When the gradient is active the color is entirely controlled by the gradient settings. The amount of gradient is applied proportionally between the starting and ending Z heights. When the gradient is active, the color mix is replaced with `mixer.gradient.color`, and the `mixer.gradient.color` is continually updated as the Z coordinate changes. For two-channel mixing, the current value of the gradient mix is displayed on the LCD. (For 3-channels and above, we might show the percentage progress of the gradient region.)

**Comment by AnHardt** [comment]
How about, instead of switching the gradient on/off with `M166 S[bool]` storing the actual blend in a third, quite normal, virtual tool. Then the gradient mix can simply be selected with `T[index] like any other mix. Your internal on/off-flag, where you have to calculate the blend, is then determined by: being at the right height-band and blend-tool selected. 
Blending the two virtual tools and renormalizing the mix is a quite expensive operation. It's worth to think about how often this needs to be done.
If the colour we see, coming out of the nozzle, would change immediately when we change the v-tool, we would not need a prime-tower for getting crisp color changes. We'd have to correct the mix on a per z-step base. Since we don't have vertical print moves we can forget about that.
Currently you are updating per block. Alternatives could be to update per g-code changing Z, eliminating z-hops caused by autoretrat and the updates for subdivided moves.
An other possibility is to update N times a second, but most natural for the problem seems to be to update **per amount of extruded material** (e-steps). Because of the lowpass properties of the mixer algorithm and the nozzles inner volume a high frequent (in the e-step domain) change of colors does not make any sense.
As far as i see we have to update the blend when:
* at every change to the 'blend-tool'
and on a regular base when using it
* not during a z-hop
* not during a retract
* in the right height-band
* after N < steps extruded since the last update
* delta Z is big enough to make a change in the blend (can be precalculated)
* the forgotten conditions

**Comment by thinkyhead** [comment]
The aim here is to essentially reproduce the Geeetech implementation, and then incrementally improve it. Gradients are not intended to be very accurate or to use a prime tower. They are simply a "special effect" option with limited utility.

I don't favor having gradients as virtual tools. This is meant to be a per-print special-effect and doesn't need to be built into anything very comprehensive. There only needs to be a single gradient known at once, and then it can be thrown away. I have no expectation that slicers will formally support this gimmicky feature.

**Comment by thinkyhead** [comment]
I've added an extra check so the gradient will only update when Z changes. The normalization of the gradient mix doesn't take too much processing, in any event, and is slightly optimized over the main `normalize` method.

The aim here is to initially reproduce the Geeetech implementation so that A10M/A20M users can upgrade, and then incrementally improve this stuff. Only 2 channels are currently supported for some elements.

Gradients are not intended to be very accurate or to use a prime tower. They are simply a "special effect" option with limited utility.

I don't favor having gradients as virtual tools right now. The Geeetech implementation is a per-print special-effect and doesn't need to be built into anything very comprehensive. There only needs to be a single gradient known at once, and then it can be thrown away.

Later, it will make sense to add gradient virtual tools, which would cause slicers to consider the color change when calculating the wipe tower. For the moment, I'm just trying to get this first implementation functional and familiar to A10M/A20M users (and move on from 1.1.8).

**Comment by fishcu** [comment]
Could I request another parameter `G` which controls the bend of the mixing curve? This would be nice since material mixing and color mixing rarely behaves linearly.
`G[float] - Gamma value for mixing ratio curve`

The calculation would be as follows, assuming 0 <= `ratio` <= 1:
`ratio_gamma_corrected = pow(ratio, gamma)`

Visualization of some "gamma curves" are produced here: https://www.wolframalpha.com/input/?i=plot+y+%3D+x%5Eg+for+g%3D%7B0.6,+0.8,+1.0,+1.2,+1.4%7D+for+0+%3C%3D+x+%3C%3D+1

**Comment by fishcu** [comment]
Screenshot for reference: 
image

**Comment by fishcu** [comment]
If `pow` is not available, a possible implementation would be a bilinear interpolation of LUTs that store `y[x][gamma]` in some discretization (e.g., x = 0.0, 0.1, 0.2, ..., 1.0 and similarly for gamma).

**Comment by thinkyhead** [comment]
I can see why that might be of use. You can vaguely approximate it now using multiple gradients, inserted at the appropriate layers. Anyway, after this is merged, you should experiment with your idea and see what kind of results you get. I have to move on to other tasks after this is merged and won't be able to get back to gradients and mixing for a few weeks.

**Comment by fishcu** [comment]
@thinkyhead thank you for the great work!
Is the merged version fully compatible with the A10M?

**Comment by e-Mole** [comment]
@thinkyhead Great work! Mixing works very well with sending mix factors or virtual tools.

I have a problem with the gradient mixer using M166. If I use M166 S1 from console I always get "Gradient Mix OFF" in log and no gradient is mixing (same behavior from the menu).

My config:

> #define MIXING_EXTRUDER
> #if ENABLED(MIXING_EXTRUDER)
>   #define MIXING_STEPPERS 2        // Number of steppers in your mixing extruder
>   #define MIXING_VIRTUAL_TOOLS 16  // Use the Virtual Tool method with M163 and M164
>   #define DIRECT_MIXING_IN_G1    // Allow ABCDHI mix factors in G1 movement commands
>   #define GRADIENT_MIX           // Support for gradient mixing with M166 and LCD
>   #if ENABLED(GRADIENT_MIX)
>     #define GRADIENT_VTOOL       // Add M166 T to use a V-tool index as a Gradient alias
>   #endif
> #endif

My tests:

> M166 S1 - result "Gradient Mix OFF"
> M166 S1 - result "Gradient Mix OFF"
> M166 A0 Z40 I2 J3 S1 - result "Gradient Mix OFF"
>  M166 T5 - result "Gradient Mix OFF"

Is there anything else to configure in the configuration files, or is it an bug?
Thanks!

**Pull request merged**
