### PR TITLE
Created a test case for CNC/Full Sized Rambo

### PR DESCRIPTION
**Pull request by jeffeb3**
Test case based on V1Engineering's CNC Dual Endstop Rambo configuration.

### Requirements

Marlin's build tests should include a CNC configuration that includes a combination of CNC features.

### Description

The V1Engineering CNC machines use a common set of features.

In an effort to keep those features from rotting with small errors, I've created a test configuration that should exercise the biggest features. I've excluded features that are probably tested elsewhere (_Bootscreen.h, Versions, etc.), but included features V1Engineering (@Allted) has included for CNC work.

### Benefits

Benefits of tests are well known. This test is quite orthogonal to many of the 3D printing and board tests that currently exist.

### Related Issues

#16108: This error is what keeps this CI test from passing. Once that is merged, this will pass.
Recreated from #16120, because I should have made it point to bugfix-2.0.x

### CODE REVIEW

**Comment by dseven** [comment]
Looks like CI has been failing on rambo since this merged.... https://travis-ci.org/MarlinFirmware/Marlin/pull_requests?utm_medium=notification&utm_source=github_status

**Comment by jeffeb3** [comment]
It was passing before it was merged. Was there another change that broke it after this PR passed it's test?

**Comment by jeffeb3** [comment]
As a shortcut. This seems to be the main issue:

```
In file included from Marlin/src/feature/../inc/../HAL/./HAL_AVR/HAL.h:23:0,
                 from Marlin/src/feature/../inc/../HAL/HAL.h:26,
                 from Marlin/src/feature/../inc/MarlinConfig.h:30,
                 from Marlin/src/feature/tmc_util.cpp:23:
Marlin/src/feature/../inc/../HAL/./HAL_AVR/fastio.h:81:35: error: pasting "DIO" and "-" does not give a valid preprocessing token
 #define _SET_OUTPUT(IO)       SBI(DIO ## IO ## _DDR, DIO ## IO ## _PIN)
                                   ^
Marlin/src/feature/../inc/../HAL/./HAL_AVR/fastio.h:101:31: note: in expansion of macro '_SET_OUTPUT'
 #define SET_OUTPUT(IO)        _SET_OUTPUT(IO)
                               ^
Marlin/src/feature/../inc/../HAL/./HAL_AVR/fastio.h:108:35: note: in expansion of macro 'SET_OUTPUT'
 #define OUT_WRITE(IO,V)       do{ SET_OUTPUT(IO); WRITE(IO,V); }while(0)
                                   ^
Marlin/src/feature/tmc_util.cpp:1056:26: note: in expansion of macro 'OUT_WRITE'
   #define SET_CS_PIN(st) OUT_WRITE(st##_CS_PIN, HIGH)
                          ^
Marlin/src/feature/tmc_util.cpp:1059:7: note: in expansion of macro 'SET_CS_PIN'
       SET_CS_PIN(X);
       ^
```
I'm not sure why the rambo is building anything in TMC. Or why it's trying to set the CS pin.

**Comment by jeffeb3** [comment]
Looks like the `restore_configs` disappeared. I put it back in this PR: #16206

**Pull request merged**
