### PR TITLE
Oscar (by Thinknthings of Korea) board support

### PR DESCRIPTION
**Pull request by neorex**
Add Oscar board.
Oscar is a board that supports 5 extruders and was developed by Thingnthinks of Korea

### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Add Oscar board.
Oscar is a board that supports 5 extruders and was developed by Thinknthings of Korea

### Benefits

Add Oscar board.

### CODE REVIEW

**Comment by AnHardt** [comment]
Do you have a link to the boards (ideally open source) description, or manual, or where to by, or any additional information.

What makes them think the world would need another 5-driver 8-bit board?

**Comment by marcio-ao** [comment]
5 driver or 5 extruders?

5 drivers... meh.
5 extruders... :O

**Comment by neorex** [comment]
8 drivers. so you can use 5 extruders with this board

**Comment by marcio-ao** [comment]
Please provide link. We might be interested :)

**Comment by thisiskeithb** [comment]
Yes, more info would be great!

**Pull request merged**
