### PR TITLE
Cleanup after some direct commits

### PR DESCRIPTION
**Pull request by thinkyhead**
If the code is temporary, please disregard this PR.
Otherwise, here's your basic code-formatting followup to https://github.com/MarlinFirmware/Marlin/commit/5e97265

- Add `hex_address` and `print_hex_address` functions.
- Apply formatting, `const`, etc. in various places

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I crossed over most of the changes from the earlier Pull Request.  (Next time I do a Pull Request they should show up.)  I'll get these moved over in the morning.

But this one has more changes.    I'm not sure about this...  I'm not sure when this causes a pointer to program memory and when it just indicates the pointer is referencing something that doesn't change:
```cpp
void M100_dump_routine(const char * const title, const char *start, const char *end);
```
Does a "const char * const title" automatically put the quoted string into program memory?

One more question:  Why is the title talking about 'Direct Commits' ?  I thought a 'Direct Commit' was using the web browser to edit the file directly on GitHub?  I didn't do that.  I made a squashed Pull Request even though the web browser approach would have been easier.

**Comment by thinkyhead** [comment]
> Does a "`const char * const title`" automatically put the quoted string into program memory?

`const char *` and `char * const` have no bearing on whether something is in program memory or not. They are merely cues to the compiler to throw errors if code tries to modify the data (in the first case) or the pointer (in the second case).

So when you see `const char * const` just think "a pointer that will not be changed (`char * const`), pointing to some character data that will not be changed (`const char *`)."

To force strings or other data to reside in program memory, we use the `PROGMEM` macro or the `PSTR` string wrapper macro. Arduino also defines `F()` for fancy string handling as an alternative to `PSTR`.

Code that deals with `PSTR`, you will notice, always calls special accessor functions such as `pgm_read_word`. Since `PSTR` are always static data in flash memory they should never be treated like regular pointers. Hence it's a good idea to use `const char *` to tell the compiler to flag any code that wants to write to some `PROGMEM` string data. And usually `const char * const` is what you want, unless the passed pointer will be modified in the function (for example `char c = *ptr++;`).

**Comment by thinkyhead** [comment]
> I made a squashed Pull Request even though the web browser approach would have been easier.

If you squashed the commits directly in the main fork, the commit ID will have changed and any association with a PR will be broken. You should therefore squash all commits in a PR prior to merging the PR and assiduously avoid rewriting the commit history in the main fork.

**Comment by thinkyhead** [comment]
> I'll get these moved over in the morning.

If you go ahead and merge those changes which overlap with these, I can attempt to rebase this on top of the updated `RCBugFix`, or more likely I will have to reconstitute many of these changes from a diff. In any case, it will be easier if you apply your changes first, and then I can follow up with this set of changes and any further cleanup that may be needed.

**Comment by Roxy-3D** [comment]
>> I made a squashed Pull Request even though the web browser approach would have been easier.

>If you squashed the commits directly in the main fork, the commit ID will have changed and any association with a PR will be broken. You should therefore squash all commits in a PR prior to merging the PR and assiduously avoid rewriting the commit history in the main fork.

No...  What happened is I ended up with a bunch of conflicts during the squash that I could not resolve.   So I set the directory aside on my laptop.  I re-forked, and applied the changes from the saved directory.  I made a new Pull Request (which by definition was 'squashed' because I only did one commit) and I hurried up and merged it before any new conflicts showed up.   I've only been trying to squash things against my fork.  I have not been trying to 'squash' anything in MarlinFirmware/Marlin.  

> You should therefore squash all commits in a PR prior to merging the PR and assiduously avoid rewriting the commit history in the main fork.

Yes.  This is one part I do understand!

**Comment by Roxy-3D** [comment]
> To force strings or other data to reside in program memory, we use the PROGMEM macro or the PSTR string wrapper macro. Arduino also defines F() for fancy string handling as an alternative to PSTR.

> Code that deals with PSTR, you will notice, always calls special accessor functions such as pgm_read_word. Since PSTR are always static data in flash memory they should never be treated like regular pointers. Hence it's a good idea to use const char * to tell the compiler to flag any code that wants to write to some PROGMEM string data. And usually const char * const is what you want, unless the passed pointer will be modified in the function (for example char c = *ptr++;).

OK.   That is helpful.   What would be really helpful is a cheat sheet showing the declaration **and** usage of RAM versus PROGMEM for various different constructs.    Right now...   I'm thinking of trying to save 120 bytes (15 x 4 x 2) of RAM by moving the 
```cpp
    for (uint8_t i = 0; i < COUNT(mesh_index_to_xpos); i++)
      mesh_index_to_xpos[i] = UBL_MESH_MIN_X + i * (MESH_X_DIST);
    for (uint8_t i = 0; i < COUNT(mesh_index_to_ypos); i++)
      mesh_index_to_ypos[i] = UBL_MESH_MIN_Y + i * (MESH_Y_DIST);
```
mesh_index_to_x/ypos[] arrays to program memory.   From what you said up above and from doing some searches of the code, I'm thinking it will be something like:
```cpp
const float mesh_index_to_xpos[] PROGMEM = {(UBL_MESH_MIN_X)+0*(MESH_X_DIST), (UBL_MESH_MIN_X)+1*(MESH_X_DIST), (UBL_MESH_MIN_X)+2*(MESH_X_DIST), (UBL_MESH_MIN_X)+3*(MESH_X_DIST), (UBL_MESH_MIN_X)+4*(MESH_X_DIST), etc };
```

**Comment by thinkyhead** [comment]
You can move the array to `PROGMEM`, but reading it will be slower because you have to use special accessor functions. It is most optimal to just let them be allocated in SRAM.

**Comment by thinkyhead** [comment]
You can move the array to `PROGMEM`, but reading it will be slower because you have to use special accessor functions. It is most optimal to just let them be allocated in SRAM.

> I ended up with a bunch of conflicts during the squash that I could not resolve.

I got a new microphone and wireless headphones so I can make a proper video on mastering git. I'll work on that over the next couple of days and try to give more thorough and orderly coverage of the main points that I did off-the-cuff in my prior videos.

**Comment by Roxy-3D** [comment]
> You can move the array to PROGMEM, but reading it will be slower because you have to use special accessor functions. It is most optimal to just let them be allocated in SRAM.

Yes.  Agreed.  But they are hardly ever accessed.  And I can change the `ubl_motion.cpp` and `ubl.h` file to further optimize their use. Given how low memory is causing data corruption issues, it might be worth while to save 120 bytes of RAM.

> I got a new microphone and wireless headphones so I can make a proper video on mastering git. I'll work on that over the next couple of days

I'll definately watch it when it shows up.    The conflicts do make a little bit of extra work.   But they aren't that bad because I only need to update things every 4 or 5 days now (when another big block of code is working and debugged).   So, by pulling down the latest and moving my new stuff on top of it, I can brute force resolve the conflicts.

And mostly...  Right now I'm just doing stuff within my code.   So the conflicts are pretty easy to resolve using a Visual Diff program.

**Comment by stigjoergensen** [comment]
I think that would be very useful...

This is one of the reasons i havnt tried so much yet - the git thing is a bit scary for now..

So i for one will look forward to watch it, or the series ;)

**Comment by thinkyhead** [comment]
> the git thing is a bit scary for now

I grew weary of being intimidated by Git and did a bunch of online tutorials till I was sure I grok'ed it.

**Comment by thinkyhead** [comment]
> The conflicts do make a little bit of extra work.

Indeed! Sometimes there are just too many conflicting changes to resolve without going blind, so it's pretty often necessary use a diff tool and sometimes to re-apply them line by line. This is more common on very active code, of course, and becomes a lot easier as code stabilizes.

**Comment by thinkyhead** [comment]
> But they are hardly ever accessed.

Oh, cool. Is one of your optimizations that `mesh_index_to_xpos[]` and `mesh_index_to_ypos[]` arrays are only accessed when the nozzle crosses into a new mesh region?

> The conflicts do make a little bit of extra work.

Indeed! Sometimes there are just too many conflicting changes to resolve without going blind, so it's pretty often necessary use a diff tool and sometimes to re-apply them line by line. This is more common on very active code, of course, and becomes a lot easier as code stabilizes.

> the git thing is a bit scary for now

I grew weary of being intimidated by Git and did a bunch of online tutorials till I was sure I grok'ed it.

**Comment by Roxy-3D** [comment]
>> But they are hardly ever accessed.

>Oh, cool. Is one of your optimizations that mesh_index_to_xpos[] and mesh_index_to_ypos[] arrays are only accessed when the nozzle crosses into a new mesh region?

Yes.   There are just a couple of key facts to understand and then everything becomes clear and it is easy to understand why the ubl_motion.cpp file is less expensive computationally.   First.  it figures out the direction of the movement.  And it doesn't forget about that so it doesn't have to be recalculated again and again.  The recursive version is particularly bad that way.   It is always trying to figure out which way it is going.

Once it knows the direction of travel, it needs to figure out which mesh line it is going to hit as it leaves the cell.   Once it knows that, it can do a simple linear interpolation to find the correction value along that line.  The other mesh_buffer_line() routines did the simple and generic technique which was a bi-linear interpolation with more than twice as many floating point operations.

From the location where it is leaving the first mesh cell, it figures out which mesh line it is going to cross when it leaves the next cell.  It once again does a linear instead of bi-linear interpolation to get the required Z correction.  And the process repeats until the nozzle is not going to be leaving the current cell.  At that point you are stuck and have to do a full blown bi-linear interpolation.  But you only do that on the very final movement.

And there are a couple of special cases it checks for.  If the line is staying within an X or Y row or column, it can do the same thing, but faster.

But anyway...  That is a long explanation why it does not need to access those arrays very often.   And with a little shift of logic, we can keep those mesh line values around so they are only retrieved once per cell and we save 120 bytes of RAM.

**Comment by thinkyhead** [comment]
Some of those heuristics may be wasted in the case of many short moves, and of course in the case of kinematic systems. For long, straight moves I'm sure they optimize a lot. It's always a question of whether the extra overhead of up-front heuristics is worth the effort in-practice and in all situations. I think it's smart to remember which grid box you're within, but I think sometimes the code to avoid the cost of a multiply/lookup might sometimes cost more than simply doing the multiply/lookup.

Meanwhile, the grid PROGMEM optimization you're thinking about makes sense if the probing grid will always be the same (perhaps that can be an option), but if we want to continue to allow probing in sub-regions (as we do with bilinear leveling) then the calculated points for the probed grid will need to be able to be in SRAM.

**Comment by thinkyhead** [comment]
I need to merge these changes to move forward on other PRs. If you have a branch with additional changes needing a fix-up after this, let me know and I will produce a new branch for you containing a combination of all changes.

**Comment by Roxy-3D** [comment]
> Some of those heuristics may be wasted in the case of many short moves, and of course in the case of kinematic systems. For long, straight moves I'm sure they optimize a lot. It's always a question of whether the extra overhead of up-front heuristics is worth the effort in-practice and in all situations.  

Yes...  I thought long and hard about that.   But as it turns out...  you have to do some of the calculations to know where you are and which direction you are moving anyway.   So...  The only question at that point is "Are you leaving the cell?"    The point is...  once you know the direction of travel, it is very quick to know if you are staying within the same column or row.   And in fact, that happens a huge amount of time just because many moves are short.  If the path leaves one cell to go to the next cell...  That counts as staying within the same row or column.  And you save a lot on the floating point calculations.

> Meanwhile, the grid PROGMEM optimization you're thinking about makes sense if the probing grid will always be the same (perhaps that can be an option), but if we want to continue to allow probing in sub-regions (as we do with bilinear leveling) then the calculated points for the probed grid will need to be able to be in SRAM.

Well...   The philosophy is a little bit different than that...   The probing is just done once at the start.   From then on, if you notice an area that does not have perfect adhesion you just move the nozzle to that location and do a G29 P4 R and edit the various mesh points up or down.   And then re-save the mesh.

> I need to merge these changes to move forward on other PRs. If you have a branch with additional changes needing a fix-up after this, let me know and I will produce a new branch for you containing a combination of all changes.

Go ahead and merge...   I'll sync up in a day or two and hopefully the Fade Height stuff will be updated at that point also.

**Pull request merged**
