### PR TITLE
[2.0.x] Add support for power loss detect pin

### PR DESCRIPTION
**Pull request by thinkyhead**
Extend SD-based power-loss recovery with support for a power-loss detect pin.

The circuit supported by this code should detect power-loss early and provide enough time and/or current for the SD card to successfully complete a write of the power-loss recovery file. The pin state for power-loss can be set as `HIGH` or `LOW`.

Counterpart to #11305

### CODE REVIEW

**Comment by valerionew** [comment]
If enough power is provided to the printer, would it be possible to finish the current command, move the head to a known point (fixed, maybe the origin?) and only then shutdown the printer? Or even wait for the extruder to cool down. 

I'm thinking specially to delta printers, where, when power is removed, the extruder may fall into the print, melting everything and ruining the print

**Comment by thinkyhead** [comment]
> If enough power is provided to the printer…

To do all that requires a lot of capacitance. Try using a super-capacitor.

**Comment by valerionew** [comment]
> To do all that requires a lot of capacitance. Try using a super-capacitor.

I was thinking to a small lead-acid battery. But that's besides the point, i can handle the electronics part. But can the firmware do that?

**Comment by thinkyhead** [comment]
Currently Marlin will only write the data to the SD card and halt. Additional code would be needed to get user-defined G-code to run in response to power-loss.

**Comment by valerionew** [comment]
I can contribute as OSHW a simple board to detect the power loss and provide enough power to finish the current command, save everything, raise the nozzle (or lower the print) and move it to a parking position. 

Should i open an issue asking someone to implement this in the firmware? I'd try to do it myself, but i'm a bit clumsy with the software side of things.

**Comment by thinkyhead** [comment]
Power-Loss Recovery needs an overhaul, and it's near the top of my list. I'll try to add an option for custom G-code to perform on power-loss during that process.

**Pull request merged**
