### PR TITLE
LPC176x NeoPixel Support

### PR DESCRIPTION
**Pull request by p3p**
### Description

Adds my LPC176x compatible fork of the Adafruit NeoPixel library to LPC envs in platformio.ini, update tests.

### CODE REVIEW

**Comment by J-charles-C** [comment]
I,

Thanks for your Job.

I have Rearm + Ramps.

When i build the commit, i have an error message with Neopixel uncomment or not.

`.piolibdeps/Adafruit NeoPixel/Adafruit_NeoPixel.cpp: In member function 'void Adafruit_NeoPixel::show()':
.piolibdeps/Adafruit NeoPixel/Adafruit_NeoPixel.cpp:153:3: error: 'noInterrupts' was not declared in this scope
noInterrupts(); // Need 100% focus on instruction timing
^~~~~~~~~~~~
.piolibdeps/Adafruit NeoPixel/Adafruit_NeoPixel.cpp:153:3: note: suggested alternative: 'detachInterrupt'
noInterrupts(); // Need 100% focus on instruction timing
^~~~~~~~~~~~
detachInterrupt
.piolibdeps/Adafruit NeoPixel/Adafruit_NeoPixel.cpp:2037:3: error: 'interrupts' was not declared in this scope
interrupts();
^~~~~~~~~~
.piolibdeps/Adafruit NeoPixel/Adafruit_NeoPixel.cpp:2037:3: note: suggested alternative: 'intptr_t'
interrupts();
^~~~~~~~~~
intptr_t
Compiling .pioenvs/LPC1768/CMSIS/driver/lpc17xx_gpio.c.o
Compiling .pioenvs/LPC1768/CMSIS/driver/lpc17xx_i2c.c.o
*** [.pioenvs/LPC1768/libf1d/Adafruit NeoPixel/Adafruit_NeoPixel.cpp.o] Error 1`

Best


[Archive.zip](https://github.com/MarlinFirmware/Marlin/files/2939846/Archive.zip)

**Comment by p3p** [comment]
Make sure you update platformio libraries and frameworks, it needs `framework-arduino-lpc176x @ 0.1.1`

**Comment by J-charles-C** [comment]
I,

Sorry il don't understand. I have the latest commit. How i can update my library ?

thanks

**Comment by p3p** [comment]
Depends how you use PlatformIO to build Marlin.

Terminal: 
`platformio update` or `pio update`

Atom: 
Click the PlatformIO menu then select `Update platforms, packages and libraries`

Visual Studio Code: 
Click the Platform IO symbol (Alien head) on the left menu bar, in Quick access Menu click on `Updates -> Update All`

**Comment by J-charles-C** [comment]
I,

Many thanks, i'm a Noob !!

I test tomorrow with Neopixel.

best

**Comment by jmdearras** [comment]
> Make sure you update platformio libraries and frameworks, it needs `framework-arduino-lpc176x @ 0.1.1`

I had the same issue. and that fixed it.  Thought I was on the latest.  :)

**Pull request merged**
