### PR TITLE
Example Configuration for K8200: comments/URL/readme

### PR DESCRIPTION
**Pull request by CONSULitAS**
example_configurations\K8200\Configuration.h:
- add machine specific header
- change STRING_URL to K8200 fork (@thinkyhead: What do you think?)

example_configurations\K8200\readme.md:
- updated documentation
- added URLs and links

### CODE REVIEW

**Comment by CONSULitAS** [comment]
@thinkyhead should we add headers to all sample configs like that?

**Comment by thinkyhead** [comment]
@CONSULitAS Yes, I favor documentation headings like that on the config files, including the author names, if applicable - the Github nicks of their caretakers.

Well, interestingly, `STRING_URL` is not used anywhere, so I think we can remove it. The right place for that setting is `FIRMWARE_URL`. That should  always be a link to a Github fork of Marlin, if there is one, or the download page for the vendor, if they have one. If neither of those exist, then it should just revert to the default – this repo.

**Comment by CONSULitAS** [comment]
@thinkyhead update should correct merge conflicts and STRING_URL removed, FIRMWARE_URL to come with other PR later

**Comment by CONSULitAS** [comment]
@thinkyhead @boelle Why is "Hardware Support" now "On Hold During Bugfix"?
- How should we test without hardware support?
- If there are only example files are changed, no productive code will be broken.
- Instead of this I try to keep the config in sync, so the bugfix release can be tested by as much people as possible.
- The longer this is pending we will have more merge conflicts. Annoying to get rid of them.

Thanks in advance

a caretaker :-)

**Comment by thinkyhead** [comment]
"On Hold" is kind of informal and discretionary. Language support, hardware support, and innocuous changes that are concise are not being completely held up. But significant new features are.

**Pull request merged**
