### PR TITLE
Fix: set digipot mcp4018 Vrefmax to 1.666V

### PR DESCRIPTION
**Pull request by stawel**
Hi, 
I've fixed a bug regarding the maximum possible output voltage o the mcp4018 digipot,
I also corrected the wt150 example configuration accordingly.

Best Regards
Paweł Stawicki

### CODE REVIEW

**Comment by dot-bob** [comment]
The max voltage that the MCP4018 digipot can be set to on most boards is 5V not 1.66V.  Do people run it this high, no.  But changing this value will throw off the calculation of the correct current.

**Comment by thinkyhead** [comment]
How much of this should we keep?

Note that any changes made to `Configuration.h` or `Configuration_adv.h` must also be applied to all the `example_configurations` versions.

**Comment by stawel** [comment]
@dot-bob 
> The max voltage that the MCP4018 digipot can be set to on most boards is 5V not 1.66V.

That is what I also thought when I wrote this code a while a go,
but according to the mightyboard rev E schematics (and my wt150 clone)
https://github.com/sciguy14/HelioWatcher/blob/master/HelioWatcher%20Circuit/MakerBot%20MightyBoard%20REVE%20Schematic.pdf

there is a R34=10K Ohm resistor in series with the digipot (digipot has 5kOhm),
that is why the maximum Vref voltage is 1.66V (at least on rev E).

**Comment by dot-bob** [comment]
You're right, for some reason overlooked the 10K resistor.  The calculation of current looks to be based off the equations in the data sheet for the A4988.  I think `#define DIGIPOT_A4988_Rsx 0.250` might as well be incorrect as the A4988 Pololu drivers either use 0.05 ohm or 0.068 ohm sense resistors See: https://www.pololu.com/product/1182

**Comment by stawel** [comment]
The Rsx = 0.250 Ohms is from my wt150 printer:

Image

Hm..
all those values are only used to calculate DIGIPOT_A4988_FACTOR,
maybe this should be configurable from Configuration_adv.h?
(with a slightly different name: DIGIPOT_MCP4018_CURRENT_FACTOR perhaps?)

**Comment by dot-bob** [comment]
It might not hurt.  It seems newer drivers are adopting a lower value sense resistor to allow increased current.  I have 0.05ohm drivers, and a set of 0.1ohm drivers.  I wonder if it would also pay to also have the #define DIGIPOT_A4988_Vrefmax in the configuration_adv.h as well.  The mightyboard REV G uses a 7.5Kohm resistor and some clones appear to use the 10K digipot.

**Comment by thinkyhead** [comment]
So… with conflicts now resolved this _could_ be added to Marlin. Is the consensus now that this PR is correct? If so, I just need to do one more cleanup and rebase and then I will merge the changes.

**Comment by thinkyhead** [comment]
Ready to merge at #7119

**Pull request closed without merging**
