### PR TITLE
Use parser.seenval, add shorthand functions

### PR DESCRIPTION
**Pull request by thinkyhead**
Improvements to the G-code parser.
- Add parser shorthand functions to get a parameter (or default value).
- Use `parser.seenval` for cases where a value is required.
- Patch some spacing, comments

### CODE REVIEW

**Comment by Gustavo314** [comment]
Hi, does this improvements to the G-code parser solve the problem when you don't have for example G1?
G1 X100 Y100
X200 
So it takes X200 like G1 X200?
(I am using 1.1.0 RC8 until now)

**Comment by Roxy-3D** [comment]
Are you thinking the line with just X200 should invoke the last GCode command (G1) to process it?

If that is in the GCode specification...  That would seem totally bogus.   I really don't think a line like X200 all by itself should do any thing at all.

**Comment by Gustavo314** [comment]
@Roxy-3D I am using ArtCam to generate de gcode and all formats I've tried have some lines with no "g" at the beginning of them. 
I didn't tried with all the formats the software have. There are tons...

**Comment by thinkyhead** [comment]
@Gustavo314 Marlin implements a non-modal variant of G-code, so it doesn't cache the last G-code sent. This is somewhat of a "safety feature" because print jobs can be paused without the firmware or host being aware, and requiring a primary code like "G", "M", or "T" ensures more predictable results. This isn't wasteful outside of SD printing, since host-generated G-code lines will be complete, for safety, and don't pile up in normal usage.

As CNC features become more common in the main fork it's possible that a modal G-code variant may be supported as an option or an operation mode. Slicers usually include a few G-code dialects, including "Marlin 1.0" protocol, and Marlin can be extended to implement other protocols, as they gain in popularity. There is a proposal, for example, to handle `C` "chunks" which are sort of like pre-built planner blocks.

If you want to implement the modal idea yourself, it shouldn't be too difficult. Create a `static char lastG` to hold the last `G` code value. Then, treat any unknown primary letter codes (or a short list, like `X`, `Y`, `Z`, `E`, `F`) as the last `G` code given. You can then post-process your G-code to make them shorter by 3 characters per movement line, and likely improve print performance a little bit.

**Pull request merged**
