### PR TITLE
Update advanced pause feature info

### PR DESCRIPTION
**Pull request by charlespick**
### Description
This updates the comments in Configuration_adv.h explaining the requirements for enabling `ADVANCED_PAUSE_FEATURE` to more accurately reflect the build checks performed in SanityCheck.h. 

### Benefits
This makes configuring the `ADVANCED_PAUSE_FEATURE` more clear to new users of the feature

### Configurations
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/6437224/configs.zip)

### Related Issues
Removes the need for #21816

### CODE REVIEW

**Comment by digant73** [comment]
it requires LCD or both EMERGENCY_PARSER and HOST_PROMPT_SUPPORT ( #21671)

**Comment by charlespick** [comment]
Huh, I was able to get it to compile without host prompt support

**Comment by digant73** [comment]
Yes, but without an LCD the user iinteraction can be provided through prompt feature so it must be enabled

**Comment by charlespick** [comment]
Do you think SanityCheck should be updated to reflect that?

**Comment by digant73** [comment]
I thinks so. SanityCheck should provide an error if a feature requiring user interaction cannot be satisfied in vase the interaction cannot be provided

**Comment by thinkyhead** [comment]
`M108` can be used from a console if host prompts are not enabled. The `M108` acts like a 'continue' button.

**Pull request merged**
