### PR TITLE
Enables the use of SoC internal temperature sensor as TEMP_SENSOR_BOARD and provides a default implementation for the STM32 HAL

### PR DESCRIPTION
**Pull request by jefflessard**
### Description

Enables the use of SoC internal temperature sensor as TEMP_SENSOR_BOARD and provides a default implementation for the STM32 HAL

`#define TEMP_SENSOR_BOARD -1000`
Now enables use of the chip internal temperature sensor

The use of the chip internal temperature sensor is to measure the silicon temperature.
It is in NO WAY meant to be an accurate reading of the ambient temperature.
-1000 can only be used with TEMP_SENSOR_BOARD.
 
Requires TEMP_INTERNAL_SENSOR(RAW) macro to convert the ADC value of the TEMP_BOARD_PIN to the temperature.
HAL\STM32\internal_temp.h provides this macro for STM32 HAL using ATEMP pin and the specs of various STM32 chips.
Therefore, defining TEMP_SENSOR_BOARD -1000 on stm32_variant boards is the only step required to use the internal sensor of the STM32. 

### Requirements

No requirements.

Defining TEMP_INTERNAL_SENSOR(RAW) macro is not required unless using `#define TEMP_SENSOR_BOARD -1000`
STM32 HAL default implementation provided but won't affect other HALs if not implemented.

### Benefits

Enables to use of SoC internal temperature sensor to monitor board temperature.

### Configurations

No configurations required

### Related Issues

N/A

### CODE REVIEW

**Comment by jefflessard** [comment]
Rebase of my PR branch brought unwanted commits to this pull request. I will close and eventually resubmit it.

**Comment by thinkyhead** [comment]
Did this ever get re-submitted? Is it still needed with the latest bugfix code?

**Comment by thisiskeithb** [comment]
> Did this ever get re-submitted?

Nope.

> Is it still needed with the latest bugfix code?

It's not "needed", but would be nice to have!

**Comment by GMagician** [comment]
I may try to rebuild it if there is some interest in it

**Comment by thisiskeithb** [comment]
> I may try to rebuild it if there is some interest in it

Please do! Using the SoC temperature for boards without an onboard thermistor (i.e. most), would be slick.

**Comment by GMagician** [comment]
@thinkyhead / @thisiskeithb

As you know is there any way to properly detect any chip in (eg) STM32F07xxx family?

Some chips seems to have different registers/slope inside the same family

**Pull request closed without merging**
