### PR TITLE
Support new TMC drivers

### PR DESCRIPTION
**Pull request by teemuatlut**
### Add support for TMC2160, TMC5130 and TMC5160 drivers
As the release of TMC2160 is getting closer, it would be good for there to be an actual firmware early adopters can use.
I've personally tested the TMC5160 drivers but 2160 should be analogous.
My prototype drivers didn't have a diag pin for sensorless homing but I believe that was remedied in later revisions. This also lead me to implement SPI endstops that don't require the wire, but that feature is coming a bit later.
There are no products using the TMC5130 that I'm aware of. Outside of TRAMS. This PR does **not** mean TRAMS is now supported!

---

### Split RSENSE settings for each driver
I foresee there being an increase in users who run mixed setups with maybe their older TMC2130 drivers getting upgraded to TMC2160 but only for X and Y for example. These drivers don't necessarily have the same sense resistor values so we'll make it easier to properly configure these new setups.

---

It's all a bit "late-beta" for now but at least this brings preliminary support for a wider user base.

The build will fail until PIO finds out about a new release with the library.

### CODE REVIEW

**Comment by kAdonis** [comment]
This is the PR I was waiting for, Thank you!
image
It seems like the new drivers dont like SW SPI. Compiles fine with HW SPI for RAMPS/Re-Arm
I am using TMCStepper library 0.3.0
I would prefer to use SW SPI, so I dont  need to solder cables to the HW SPI Pins on my Re-Arm

**Comment by teemuatlut** [comment]
Ah yes true. Looks like it's time for 0.3.1 then. As soon as I sort out my network issues (throws money at screen).

**Comment by comps** [comment]
Would it make sense for the `*_RSENSE` defines to use pre-defined values like `TMC2130_RSENSE`, similar to `CHOPPER_DEFAULT_12V`? .. I imagine most people will want to (at most) switch the driver types, not use a custom external resistor.
(Alternatively, define it elsewhere based on `*_DRIVER_TYPE` and allow override here.)

**Comment by teemuatlut** [comment]
It would if all driver implementations would use the same values.
The 0.11 is typical for the SilentStepStick series but Ultimachine Archim2.0 and Einsy have their own.
The sense resistor value is not tied to the driver IC model, but what the designer of the board specified.

We would have to define presets like `RSENSE_WATTEROTT_TMC2130` and `RSENSE_FYSETC_TMC2130`. I'm not yet sure I want to go that particular route but it would be good if the user didn't have to know a detail like that.

**Comment by teemuatlut** [comment]
Library version v0.3.1 is now released ([diff](https://github.com/teemuatlut/TMCStepper/compare/v0.3.0..v0.3.1)).
New constructors and added support for TMC5161.

**Comment by thinkyhead** [comment]
Squashed and rebased…
```
git fetch origin
git checkout new_tmc_drivers
git reset --hard origin/new_tmc_drivers
```

**Pull request merged**
