### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by qwewer0**
- Removed double spaces before comment.
- Aligned some comments.
- Aligned some values.
- Changed remaining mm/m to mm/min.
- Converted remaining mm/min values to (x*60) format.

### CODE REVIEW

**Comment by charakaSamawry** [comment]
I think you meant 'aligned', as its correctly spelt.
And, you mean to say 'remaining' instead of remained im pretty sure, ie. 'Changed remaining mm/m to mm/min' 
not picking hairs just clarification cos i got confused for a moment there lol. Maybe english isnt your first language, it is my only language... lol

**Comment by thisiskeithb** [comment]
In my opinion, the extra spacing helped separate the comments from the defines, and it feels too crammed together now.

**Comment by qwewer0** [comment]
@thisiskeithb Most of the comment had only a single space in front of them, so my understanding was that the single space is the original/default way to do it, but if more people would say that it is better with two spaces (I too think that with two spaces it is easier to read), then I will gladly make the changes.

Edit: The "two space" change would result in 1k+ changes outside of Configuration.h and Configuration_adv.h.

**Comment by thinkyhead** [comment]
The general idea of cleanup is good, but it would be better to do this in small increments as part of other updates over several weeks or months. Applying such a large volume of changes to the Configurations repository all at once would take at least a couple of hours of intensive effort, and I need to budget my time better.

**Pull request closed without merging**
