### PR TITLE
TFT: add some wakeup events, on pause msg & sd reprint

### PR DESCRIPTION
**Pull request by tpruvot**
Generally not really buggy but may cause some refresh/partial draw issues without those.

May need a few others...

### CODE REVIEW

**Comment by tpruvot** [comment]
there is maybe a better way, like in ui.set_status_P() which is LCD_MESSAGEPGM, i need to do more real use tests

**Comment by thinkyhead** [comment]
If you want to wake up the display whenever the status message changes, you can add code to `MarlinUI::finish_status`. But some hosts may have behavior or plugins that send `M117` a lot, or some slicers may insert a lot of `M117` commands. It might also make sense to wake up the screen in `MarlinUI::goto_screen` which would indicate some alert or interactive screen is being displayed. It would also handle the case where the SD file was reselected after a print job.

**Comment by tpruvot** [comment]
yep or maybe on defer_status_screen() which means we are "locked/paused" in some dialog... goto_screen() may have a timeout in general...

Well its already better with these few changes, but this SD_REPRINT_LAST_SELECTED_FILE behavior breaks a bit the logic to auto sleep once the print is done... with this PR it will never sleep because there is no timeout on this sd menu...
But user is free to avoid this option also. A very long menu timeout could "fix" that else, like 15/30mn

**Comment by thinkyhead** [comment]
> For `defer_status_screen` you would typically want to disable the screen backlight timeout, but the user will usually be interacting with the controller at that point, so it's probably not vital.

**Pull request merged**
