### PR TITLE
[1.1.x] z_offset

### PR DESCRIPTION
**Pull request by LVD-AC**

### CODE REVIEW

**Comment by LVD-AC** [comment]
Fix for #8380

**Comment by stuartmp** [comment]
Nice.... Looks great... I will give this a go and give you some feedback. Thank you the work you have done here. Much appreciated.  Lets hope that they merge it into the release branch too.

**Review by thinkyhead — CHANGES_REQUESTED** [review]
I'm leaning towards rejecting this, as it balloons the code size for users with no probe, with no added benefit. If you have no probe, there should be no `zprobe_zoffset` and no `M851` command.

**Comment by stuartmp** [comment]
Hi Scott that's for looking in this....  I really appreciate it as I'm not really sure what the best solution is.

All I would like is the LCD display to show me what the current Z_offset is.

I am happy if I cannot adjust it on screen.

All I really need and what I think would be handy for other users is the ability to at least see what the current z-offset value is as most slicers can set this before a print or the user may set it from the command line. 

I understand what you are saying about memory space and maybe this could be a good compromise. hopefully just displaying the z offset value won't take up that much memory.

What do you think?

**Comment by stuartmp** [comment]
Hi Luc Van, Tonight I merged and updated my branch with your code but I don't see any adjustment in my z offset when I run a M503 command. 

I do see the z offset option in the motion menu and I can scroll my adjustment wheel and the values on screen do change but I don't see any adjustment happening.

If you can please explain how the adjustment of the z offset is meant to function that would be awesome

Thanks again for your time working on this feature.

**Comment by LVD-AC** [comment]
@stuartmp if you have no probe there is no z_offset in Marlin, so nothing to show on the screen; but with this PR you can set the z_offset with M851 Zx.xx followed by M500 or on the LCD-screen motion menu z_offset followed by store to EEPROM. Check with M503 : at the end M851 and the Marlin z_offset are displayed.

But now I see what you want, you want the z-offset from the slicer program to be displayed on the LCD. Different software, different thing. However setting a z_offset in marlin does not require re-slicing and as such is a much handier option then setting a z_offset in the slicer config. But z_offset in the slicer and z_offset in Marlin FW are 2 completely different things (that do the same thing). Use one or the other; using both is just confusing.

**Comment by LVD-AC** [comment]
@thinkyhead 
What about this approach; delta users without a probe can choose if they want the functionality of setting an additional (non probe related) Z_offset or not; they will only have the extra code when explicitly chosen.

**Edit: I just enabled M851 and LCD menu for all Deltas; leave as it was for Cartesians.**

**Comment by stuartmp** [comment]
"""with this PR you can set the z_offset on the LCD-screen motion menu z_offset followed by store to EEPROM. Check with M503 : and the Marlin z_offset are displayed."""

This is what I did and would be happy with.
But the z offset was not saved

**Comment by stuartmp** [comment]
@thinkyhead that functionality sounds fine to me

**Comment by stuartmp** [comment]
@LVD-AC I apologize... I just checked using my laptop and I can see when typing M503 that the setting is being saved buy under M851 Z-probe offset. Not M206 Home offsets... I would have thought that I needed it to be saved under M206 as I have no z probe... but maybe it works slightly different.... nevertheless I have set the z offset value to 3mm but see no change in my z offset for my extruder nozzle and this is the functionally that I need. Please let me know if I am doing something wrong or if we need to change something else. 

I can see that you have just tweaked the code again... have not had time to try it but will this solve my problem?

**Comment by LVD-AC** [comment]
M206 is (should be) disabled on deltas by default! That command works only on Cartesians.
And you need to home before a z_offset change takes effect.

PS: in the new version uncomment `//#define ADDITIONAL_Z_OFFSET` in Coniguration.h

**Comment by stuartmp** [comment]
I have a Cartesian printer. I did try homing first but I saw no change
in my z offset
I will try the latest version and report back.

Have you personally tested it? 

----- Original Message -----

**Comment by LVD-AC** [comment]
It works fine on my delta. The new version will not work on Cartesians. `#define ADDITIONAL_Z_OFFSET` is missing from the Configuration.h exemple files.

**Comment by stuartmp** [comment]
Thanks for the response.... So once I merge your latest commit with
the bugfix version and add #define ADDITIONAL_Z_OFFSET to my
Configuration.h file it should work on my Cartesian machine?

----- Original Message -----

**Comment by stuartmp** [comment]
Ok done that.... still not working... I think that I need it to change M206 not M851... can this be done?

**Comment by LVD-AC** [comment]
What is not working? Can't you set the z_offset with M851, with LCD screen?

**Comment by stuartmp** [comment]
Yes I can set the z offset on the LCD screen and it changes the z offset distance when I look at M503 on command my laptop but it does not change the printing height of the extruder nozzle. I usually use M206 to achieve what I am after... Please advise...

**Comment by stuartmp** [comment]
I think that I need to change

`  /**
     * Probe Offset
     */
    #if HAS_Z_OFFSET
      if (!forReplay) {
        CONFIG_ECHO_START;
        SERIAL_ECHOLNPGM("Z-Probe Offset (mm):");
      }
      CONFIG_ECHO_START;
      SERIAL_ECHOLNPAIR("  M851 Z", LINEAR_UNIT(zprobe_zoffset));
    #endif`

To 

`  /**
     * Probe Offset
     */
    #if HAS_Z_OFFSET
      if (!forReplay) {
        CONFIG_ECHO_START;
        SERIAL_ECHOLNPGM("Z-Probe Offset (mm):");
      }
      CONFIG_ECHO_START;
      SERIAL_ECHOLNPAIR("  M206 Z", LINEAR_UNIT(zprobe_zoffset));
    #endif`

**Comment by LVD-AC** [comment]
Are you saying when you change the z_offset do G28, G1 Z5 it goes to the same height as before?

**Comment by stuartmp** [comment]
Current yes that's what is happening 

On 16 November 2017 6:32:21 PM AEST, Luc Van Daele <notifications@github.com> wrote:
>Are you saying when you change the z_offset do G28, G1 Z0 it goes to
>the same height as before?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/pull/8422#issuecomment-344851080

-- 
Sent from my Android device

**Comment by stuartmp** [comment]
SENT: M503
READ: echo:  G21    ; Units in mm
G21    ; Units in mm
READ: echo:  M149 C ; Units in Celsius
M149 C ; Units in Celsius
READ: 
READ: echo:Filament settings: Disabled
Filament settings: Disabled
READ: echo:  M200 D1.75
M200 D1.75
READ: echo:  M200 D0
M200 D0
READ: echo:Steps per unit:
Steps per unit:
READ: echo:  M92 X80.00 Y80.00 Z400.00 E105.00
M92 X80.00 Y80.00 Z400.00 E105.00
READ: echo:Maximum feedrates (units/s):
Maximum feedrates (units/s):
READ: echo:  M203 X500.00 Y500.00 Z15.00 E70.00
M203 X500.00 Y500.00 Z15.00 E70.00
READ: echo:Maximum Acceleration (units/s2):
Maximum Acceleration (units/s2):
READ: echo:  M201 X1000 Y600 Z100 E5000
M201 X1000 Y600 Z100 E5000
READ: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
READ: echo:  M204 P1000.00 R500.00 T1000.00
M204 P1000.00 R500.00 T1000.00
READ: echo:Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
Advanced: S<min_feedrate> T<min_travel_feedrate> B<min_segment_time_us> X<max_xy_jerk> Z<max_z_jerk> E<max_e_jerk>
READ: echo:  M205 S0.00 T0.00 B20000 X15.00 Y10.00 Z2.70 E5.00
M205 S0.00 T0.00 B20000 X15.00 Y10.00 Z2.70 E5.00
READ: echo:Home offset:
Home offset:
READ: echo:  M206 X0.00 Y0.00 Z0.00
M206 X0.00 Y0.00 Z0.00
READ: echo:Material heatup parameters:
Material heatup parameters:
READ: echo:  M145 S0 H205 B63 F0
M145 S0 H205 B63 F0
READ: echo:  M145 S1 H245 B75 F0
M145 S1 H245 B75 F0
READ: echo:PID settings:
PID settings:
READ: echo:  M301 P31.49 I3.00 D82.54
M301 P31.49 I3.00 D82.54
READ: echo:  M304 P599.33 I118.00 D761.00
M304 P599.33 I118.00 D761.00
READ: echo:Z-Probe Offset (mm):
Z-Probe Offset (mm):
READ: echo:  M206 Z4.50
M206 Z4.50
READ: echo:Linear Advance:
Linear Advance:
READ: echo:  M900 K400.00 R0.00
M900 K400.00 R0.00
READ: ok
SENT: M105
READ: ok T:27.73 /0.00 B:30.67 /0.00 @:0 B@:0
Disconnected.


OK my full M503 log is above

Normally my z offset is shown on this line
**Home offset:
READ: echo:  M206 X0.00 Y0.00 Z0.00
M206 X0.00 Y0.00 Z0.00**

But currently it is showing up on this line

READ: echo:Z-Probe Offset (mm):
**Z-Probe Offset (mm):
READ: echo:  M206 Z4.50
M206 Z4.50**

I did try changing the code below, but it still did not work

 #if HAS_Z_OFFSET
      if (!forReplay) {
        CONFIG_ECHO_START;
        SERIAL_ECHOLNPGM("Z-Probe Offset (mm):");
      }
      CONFIG_ECHO_START;
      //SERIAL_ECHOLNPAIR("  M851 Z", LINEAR_UNIT(zprobe_zoffset));
	  SERIAL_ECHOLNPAIR("  M206 Z", LINEAR_UNIT(zprobe_zoffset));
    #endif

**Comment by LVD-AC** [comment]
> Normally my z offset is shown on this line
> Home offset:
> 
No it doesn't! It clearly states 'Home offset'

I'm gonna leave this discussion for what it is. It's becoming clear to me that people with Cartesian printers do not use the z_offset from M851 to tweak their 1st layer right, but use the z part of home_offset from M206 instead. So @thinkyhead is right that this PR is pretty useless for Cartesian printers.

However for Delta users it makes sense; delta's do not have M206, they rely on M851 to tweak the print height of the 1st layer (probe or no probe). So that is what this PR does, it enables M851 and the LCD-menu for delta's without a probe. (tested and it works as expected)

The original issue #8380 should read "Display home_offsets on status bar" quite another issue only for Cartesian printers. Not my turf...

**Comment by stuartmp** [comment]
Ok... well thanks for your efforts.
Still don't understand why if I change that line from M851 to M206 .... I would have thought that M206 would be M206 across the board not just for the z probe offset. Just doesn't make sense.

**Comment by Sineos** [comment]
> I'm gonna leave this discussion for what it is. It's becoming clear to me that people with Cartesian printers do not use the z_offset from M851 to tweak their 1st layer right, but use the z part of home_offset from M206 instead. So @thinkyhead is right that this PR is pretty useless for Cartesian printers.

From my limited knowledge this doesn't sound right. M206 is defining an axes coordinate systems and should probably not be used to tweak nozzle offsets. 
And even if I have no probe, being able to babystep the nozzle while printing the brim or fine tune my crappy z-endstop with M851 sounds like a nice addition. Or maybe I just don't get this pull request :-p

Edit: I do have an Cartesian printer

**Comment by LVD-AC** [comment]
@stuartmp 
> Z-Probe Offset (mm):
>  READ: echo: **M206** Z4.50
>  **M206** Z4.50

you just changed to print the phrase "M206" on the screen instead of "M851", what else did you expect?

**Comment by stuartmp** [comment]
You sound like your getting upset....
Sorry if this is the case....
I am only new to the marlin firmware and don't know all the details of how it works.

I have however been programming for many years....

My logic there was as, M851 was not working for me. So if I could find where the firmware actually issues the M851  command and change it to M206 maybe it would work. I didn't know that was a print phrase to screen statement.

Without upsetting you further do you know where the actual M851 command is given to the firmware to actually change the z offset as I can't find that location in the code.



On 16 November 2017 10:30:09 PM AEST, Luc Van Daele <notifications@github.com> wrote:
>> Z-Probe Offset (mm):
>>  READ: echo: **M206** Z4.50
>>  **M206** Z4.50
>
>you just changed to print the phrase "M206" on the screen instead of
>"M851", what else did you expect?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarlinFirmware/Marlin/pull/8422#issuecomment-344908962

-- 
Sent from my Android device

**Comment by LVD-AC** [comment]
I can only blame René Descartes for this; he's French. 🖖

**Comment by LVD-AC** [comment]
> Yes I can set the z offset on the LCD screen and it changes the z offset distance when I look at M503 on command my laptop but it does not change the printing height of the extruder nozzle. I usually use M206 to achieve what I am after... Please advise...

Having the same problem now on delta machines; see #8497. I think M851 was intended to have only effect in some fancy bed levelling stuff, but outside G29 it is designed to do... nothing. A bit like Monty Python's machine that goes 'ping'.

No point in enabling for non-probe machines a command and LCD menu that do nothing.

**Pull request closed without merging**
