### PR TITLE
More flexible Probe Temperature Compensation

### PR DESCRIPTION
**Pull request by tombrazier**
### Description
#17092 requests probe temperature compensation for a situation with bed and extruder temperature sensors but no probe temperature sensor. It also requests the ability to set the calibration values in the firmware via configuration macros.

This PR modifies the probe temperature compensation feature so that it will work with any combination of probe, bed and extruder temperature sensors and it also allows default configuration values to be stored in Configuration_adv.h.

Along the way, this PR also fixes several bugs and cleans up the code (where "clean" = what I think is clean - I hope others agree! :pleading_face:).

Bug fixes aside, this update maintains backwards compatibility. With the default config values, a printer will behave in the same way as before.

The changes are divided into a lot of small commits, each of which is (hopefully) easy to follow.

The initial commits all pave the way for the actual feature:

- 2eae300 removes an unused config macro and moves the macros which configure G76 into one place.
- 804902f, 9e74b61, aa7a9f9, 6cb2d05, 755004c: originally this feature's configuration was in constexpr variables in `src/feature/probe_temp_comp.h`. Later some of these constexpr variables became initialised from macro values on `Configuration_adv.h`. These commits just move all the config into macros in `Configuration_adv.h` and remove the (now unneccesary) constexr variables.
- 64edadf removes several cached calculations which need not be cached.
- 4003c15 removes a duplicate comment which has ended up in the wrong place.
- 0a76fc4 removes a bug where a hard coded enum value was used where the function's parameter should have been used.
- c409cde M192 (wait for probe temperature) was enabled if temperature compensation was enabled. Indirectly this meant that it was available if there was a probe temperature sensor. It is now just directly dependent on the sensor.

The actual changes for this FR are:
- f39ef63, ae064a5 and e618394: Pretty much all just about putting #if clauses around code so that the code sections for probe, bed and extruder temperature compensation can be individually enabled.
- 6dac58e: Allow default values for Z offset calibration data to be placed in `Configuration_adv.h`.
- 58deb78: Add reset to default M502 code. The documentation says this exists but it doesn't. It is not in commit a338dce83f6f3b3348a8422ad8acd7b81cc1cefe where this feature was added to `configuration_store.cpp` and which as committed at the same time as the comment in the docs about M502. I think it just got missed out.

Finally, from testing the following changes:
- 144bc97 allows G76 to work even if the probe is not used for Z homing (which works fine) and also removes a run-time check that is already covered by compile-time checks.
- 148bb1d stops the G76 bed calibration from unnecessarily taking more measurements than can be stored.
- 1de20b1 and 4dc2759 relax a check which required 3 measurements to be made. Only 1 measurement is needed to get enough data points for linear interpolation/extrapolation. (A "measurement" means a Z delta is calculated over a start and end temperature.)
- 52fe885 resolves three off by one errors when extrapolating to fill in unreachable temperatures. calib_idx at this point in the code is the index for the next entry into data[] and the temperature it relates to is `start_temp + (calib_idx + 1) * res_temp`.
 
### Requirements

A Z probe and at least one temperature sensor for probe, bed or extruder.

### Benefits

Probe temperature compensation is more flexible and configurable and works better. See above.

### Configurations

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/7429035/configs.zip)

### Related Issues

FR #17092

### CODE REVIEW

**Comment by tombrazier** [comment]
I hope that all makes sense. I have tried to make it as clear as possible.

**Comment by tombrazier** [comment]
thinkyhead commenting out `#define USE_TEMP_PROBE_COMPENSATION` and `#define USE_TEMP_BED_COMPENSATION` will change the default behavior because `PROBE_TEMP_COMPENSATION` was previously enabled by default for probe and bed sensors. Is that your intention? If so I think it makes sense because the default offsets were all zero anyway and so had no effect.

**Comment by thinkyhead** [comment]
Yes, I'm intentionally allowing a probe to have a temperature sensor and the use of `M192` without PTC.

**Comment by tombrazier** [comment]
I have submitted associated PRs for the documentation and configuration projects. Can easily update and push the config changes you have made if you like. That should fix the BIGTREE_BTT002 error I think.

**Comment by thinkyhead** [comment]
There's more to do here, so I'll be back in about 8 hours to continue on it….

**Comment by tombrazier** [comment]
Further ideas for refactoring when you get back:
- Mia culpa,  ProbeTempComp::reset_to_default() has an open brace on the next line (hard habit to break!).
- The word "measurements" doesn't really fit. It's really offsets that are being stored. The number of measurements = number of offsets + 1.
- Since users are going to need to change their config anyway, USE\_TEMP\_\*\_COMPENSATION could perhaps change to something like PROBE\_\*\_TEMP_COMPENSATION.
- And [PBE]TC\_SAMPLE\_\* to [PBE]\_CURVE\_\*.
- G76_M871.cpp has a large comment section at the top which is already covered in https://marlinfw.org/docs/features/probe_temp_compensation.html and https://marlinfw.org/docs/gcode/G076.html.

**Comment by thisiskeithb** [comment]
Do I need to submit a PR to reenable PTC on the Prusa MK3 configs? They’re disabled now by default with these changes.

**Comment by thinkyhead** [comment]
> Do I need to submit a PR to reenable PTC on the Prusa MK3 configs?

It's early enough in this refactor that it can simply be adjusted without formalities.

**Comment by tombrazier** [comment]
Further suggestions:
- Rename the TSI_EXT enum value to TSI_HOTEND.
- Instead of silently disabling PTC options for non-existent sensors in Conditionals_adv.h, raise an error in SanityCheck.h.
- Add sanity checks about renaming the PTC_SAMPLE_* macros.

**Comment by tombrazier** [comment]
Another question: since the Prusa example config enables PTC by default, should we also populate PTC_SAMPLE_PROBE_VALUES and PTC_SAMPLE_BED_VALUES? We have data in the table at the bottom of https://marlinfw.org/docs/features/probe_temp_compensation.html.

Those calibration values are pretty much linear, so this config would do it:
```cpp
  #if ENABLED(PTC_PROBE)
    // Probe temperature calibration generates a table of values starting at PTC_SAMPLE_PROBE_START
    // (e.g., 30), in steps of PTC_SAMPLE_PROBE_RES (e.g., 5) with PTC_SAMPLE_PROBE_COUNT (e.g., 10) samples.
    #define PTC_SAMPLE_PROBE_START   30    // (°C)
    #define PTC_SAMPLE_PROBE_RES     50    // (°C)
    #define PTC_SAMPLE_PROBE_COUNT    1
    #define PTC_SAMPLE_PROBE_VALUES  { -150 } // (µm) Z adjustments per sample
  #endif

  #if ENABLED(PTC_BED)
    // Bed temperature calibration builds a similar table.
    #define PTC_SAMPLE_BED_START     60    // (°C)
    #define PTC_SAMPLE_BED_RES       50    // (°C)
    #define PTC_SAMPLE_BED_COUNT      1
    #define PTC_SAMPLE_BED_VALUES    { 55 } // (µm) Z adjustments per sample
  #endif
```

Excuse the question if the answer is an obvious "no". I am still learning the Marlin way of doing things.

But if the answer is "yes" then I also have data for the extruder based on my E3D V6 clone which I expect would have the same behaviour as the genuine part because it comes down to the physical expansion properties of a specifically shaped chunk of aluminium. That would be:
```cpp
#define PTC_HOTEND   // Compensate based on hotend temperature

...

  #if ENABLED(PTC_HOTEND)
    // Note: There is no automatic calibration for the hotend. Use M871.
    #define PTC_SAMPLE_HOTEND_START 180    // (°C)
    #define PTC_SAMPLE_HOTEND_RES   100    // (°C)
    #define PTC_SAMPLE_HOTEND_COUNT   1
    #define PTC_SAMPLE_HOTEND_VALUES { -41 } // (µm) Z adjustments per sample
  #endif
```

**Comment by thinkyhead** [comment]
> …should we also populate… ?

Any changes needed / useful for a specific configuration can be submitted as a PR to the Configurations repo (`import-2.0.x` branch), now that the options are settled.

**Comment by thisiskeithb** [comment]
I have a genuine MK3S/+ and several genuine V6 hotends and can verify results as well.

**Comment by tombrazier** [comment]
> can verify results as well

@thisiskeithb shall I leave it to you to submit a PR then?

**Comment by thisiskeithb** [comment]
Why is `PTC_PROBE_POS` in the config twice?

https://github.com/MarlinFirmware/Marlin/blob/6af344c19329b51307d38463c4912651ac1dcdaa/Marlin/Configuration_adv.h#L2041-L2043

**Comment by tombrazier** [comment]
The commented out one is an example config that was originally in probe_temp_comp.h. It goes all the way back to the following in the original commit for the feature:

```
    // Where to park nozzle to wait for probe cooldown
    static constexpr float park_point_x = PTC_PARK_POS_X,
                           park_point_y = PTC_PARK_POS_Y,
                           park_point_z = PTC_PARK_POS_Z,
                           // XY coordinates of nozzle for probing the bed
                           measure_point_x     = PTC_PROBE_POS_X,   // Coordinates to probe
                           measure_point_y     = PTC_PROBE_POS_Y;
                           //measure_point_x     = 12.0f,           // Coordinates to probe on MK52 magnetic heatbed
                           //measure_point_y     =  7.3f;
```
I moved it into Configuration_adv.h reasoning that if it made sense to have it anywhere then this was the place for it, not the feature header file.

**Pull request merged**
