### PR TITLE
🔧 Sanity check BIQU MicroProbe and FT_MOTION

### PR DESCRIPTION
**Pull request by narno2202**
### Description

 Currently Z homing is impossible with a BIQU MicroProbe when `FT_MOTION` is enabled. You have to disable `FT_MOTION` with `M493 S0` in order to home the Z axis.

After some investigations, homing is fine when `ENDSTOP_INTERRUPTS_FEATURE` is enabled on a compatible motherboard.

Add a comment in `Configutation.h` in "BIQU MicroProbe" section and a test in `SanityCheck.h ` when `FT_MOTION` is enabled with this probe.

### Requirements

Motherboard with interrupt capable endstop pins.

### Benefits

MicroProbe works as expected

### Related Issues

None

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Interesting. That's going to preclude most (all?) LPC-based boards if they have a MicroProbe and want to use `FT_MOTION`.

**Comment by thisiskeithb** [comment]
> You have to disable `FT_MOTION` with `M493 S0` in order to home the Z axis.

What about disabling `FT_MOTION` (and `INPUT_SHAPING_Z`) automatically as standard procedure for all Z homing with a probe? This would remove the `ENDSTOP_INTERRUPTS_FEATURE` requirement & allow a MicroProbe and `FT_MOTION` to work on every board.

**Comment by narno2202** [comment]
In my mind,  the best is to get `FT_MOTION` to work with all kinds of probes without disabling anything. But it could be a workaround if no solution is found with board without interrupt feature (I write a code but I need to test it).

**Comment by thisiskeithb** [comment]
> In my mind, the best is to get FT_MOTION to work with all kinds of probes without disabling anything.

There's no reason why you need Input Shaping or FT Motion during homing moves, so it's perfectly reasonable to temporarily disable them in order to home/calibrate the machine.

**Comment by narno2202** [comment]
Regarding `FT_MOTION`, it's simply a motion system with optional input shaping. If it's intended to become the default motion system, everything should work without workaround.

**Comment by thinkyhead** [comment]
Be sure to CC: to @ulendoalex for all issues related to FT Motion since Ulendo has a vested interested for everything to work seamlessly with this new motion system. Breakage of homing or probing with FT Motion enabled indicates a bug still exists somewhere in the design.

**Comment by narno2202** [comment]
@thinkyhead , @ulendoalex , @thisiskeithb , currently on my printer (MKS Monster 8 V1 and TMC2226), Z axis homing with `FT_MOTION` enabled works out of the box with mechanical endstop,  BLTouch, CRTouch or SMARTTouch.
For a Biqu Microprobe V2, I need to remove the diag pin jumpers for the Z axis for a correct Z homing when `FT_MOTION` is disabled. With `FT_MOTION` enabled for now, `ENDSTOP_INTERRUPTS_FEATURE` is mandatory, to correctly home the Z axis.
It will be of interest to have feedback with other probes as the failure is perhaps related to the hardware conception of the Biqu Microprobe.

**Comment by thisiskeithb** [comment]
> I need to remove the diag pin jumpers for the Z axis for a correct Z homing when FT_MOTION is disabled.

DIAG jumpers should be removed for any axis that you are not using sensorless homing/probing on (included all E-related axis), so that's not a new requirement.

**Comment by narno2202** [comment]
I know that, but I forgot to remove them when I change my motherboard but everything was working fine with the jumpers in place (even Z axis homing).
I made other tests, but everything fail. For now the best solution is to enable `ENDSTOP_INTERRUPTS_FEATURE`.

**Pull request merged**
