### PR TITLE
Controller fan improvements - With additional idle speed and persistent settings. 

### PR DESCRIPTION
**Pull request by GeminiServer**
With adjustable idle speed and motor on speed.
Ability to set and change controller fan speed settings via lcd settings menu and or gcode. Was not sure how to select the correct gcode number. So i just used the free M710! Feel free to give me feedbacks. 

### Benefits

The user is able to set and define controller fan speed within the menu and are able  to define the idle speed of the controller fan, to reduce noise and can also define the fan speed if stepper motors on. 

This is an improvement of the existing feature with ability to also set the idle speed. 

### Related Issues

No related issues.

### CODE REVIEW

**Comment by hamster65** [comment]
Would it be possible to add options to select when the controller fan should be active?
For example, I need the fan for the stepper controllers. but not for the bed mosfet (which stays cold without any fan). So whenever the printer is heating up, which takes some time for my machine, the controller fan could stay off.

**Comment by GeminiServer** [comment]
> Would it be possible to add options to select when the controller fan should be active?
> For example, I need the fan for the stepper controllers. but not for the bed mosfet (which stays cold without any fan). So whenever the printer is heating up, which takes some time for my machine, the controller fan could stay off.

Yes. It can be conditionally defined/implemented in the code/menu. When the fan should start or not. 
But you can go and set the controller fan speed via gcode. I.e.: before print process, while bed is heating set it to off or what speed you want/need. In this way you can define when the controller fan should start or not. Just try it out. Other whise i can surely expand the functionality of the controller fan settings. 

Here the gcode examples:
```cpp
/**
   * M710: Set controller fan settings
   * You can set all parameters separate or together.
   * Examples:
   *   M710                   ; Return current Settings
   *   M710 S0                ; Turn off Controller Fan
   *   M710 I255              ; Set Fan Idle Speed Setting
   *   M710 R                 ; Reset settings to defaults
   *   M710 S255              ; Set controller Fan speed setting to 100%
   *   M710 I255 A0           ; Set Fan idle speed setting and AutoMode off
   *   M710 S255              ; Set controller Fan speed setting to 100%
   *   M710 I127 A1 S255 D160 ; Set controller Fan idle speed 50%, AutoMode On, Fan speed 100%, duration to 160 Secs
   *
  */
```

**Comment by thinkyhead** [comment]
Although `M710` is documented in the RepRap wiki as "erase EEPROM and reset board" it is not used by any firmware. So it is fair to repurpose this G-code.

**Comment by thinkyhead** [comment]
Added to the wiki at https://reprap.org/wiki/G-code#M710:_Controller_Fan_settings

**Comment by BastR** [comment]
This commit broke compilation. (tested on 2 SKR PRO)

If CONTROLLER_FAN_EDITABLE is commented, I can't compile:
Capture d’écran 2020-03-20 à 09 47 58

If CONTROLLER_FAN_EDITABLE is uncommented, I can compile without uses

**Comment by GeminiServer** [comment]
const reference to a constexpr object
This should fixed it: 
image

**Comment by BastR** [comment]
@GeminiServer it works, thanks you

**Comment by kkosa1** [comment]
Could this also be applied to extruder fan ?  (#15362)

Re: [MarlinFirmware/Marlin] [BUG] Changing EXTRUDER_AUTO_FAN_SPEED to something else but 255 makes the build fail unexpectedly (#15362)

running on BTT SKR PRO.

________________________________

**Comment by Conti93** [comment]
This broke fan ramp down when only Z drivers are in use (or I misconfigured it?), tried now with latest build but the fan stays at max speed even when only my Z driver is on:
image

On 2.0.5 it was configured this way and working right (fan slows down when X, Y and E drivers shuts down after inactivity timeout):
image

**Pull request merged**
