### PR TITLE
[2.0.x] Initial Archim1 Marlin 2.0 changes

### PR DESCRIPTION
**Pull request by Allted**
### Description

Initial Ultimachine Archim1 board changes and pins file for Marlin 2.0.x. The Archim1 is 32bit with DRV8825 drivers. Digital micro-stepping and PWM current control. Tonokip got it working I just updated it to the current bugfix.

### Benefits

Initial Marlin 2.0.x Pull Request. This includes pinouts, USB, and LCD settings / timings.

### Related Issues
As far as I can tell everything is functional other than the Marlin default PWM grouping of the XY and E1-4 current PWM. Still fully functional just not able to set each driver individually.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Rebased, squashed, and brought up to date. To get the fixed up branch:
```
git fetch origin
git checkout bugfix-2.0.x-Archim1
git reset --hard origin/bugfix-2.0.x-Archim1
```

**Comment by Allted** [comment]
Thanks. Everything checks out of what I have tested with this version. Apologies for not having is squished, still learning. 

There is a little blip on the file screen of a full graphic LCD, u8glib type, if you scroll past the last file but everything still reads and is select-able.

**Comment by thinkyhead** [comment]
> There is a little blip on the file screen of a full graphic LCD, u8glib type, if you scroll past the last file but everything still reads and is select-able.

Is that only with the Archim One, or a general issue? I just did a big menu cleanup, so I wouldn't be surprised if a glitch or two snuck in.

**Comment by Allted** [comment]
I do not see the blip in any of the other boards I have here. I will try again with a different screen and SD card just to be certain. It selected the file and ran fine, just glitched if I went past the last file.

**Comment by Allted** [comment]
I just tried a few things and, #define SPI_SPEED SPI_HALF_SPEED, in config .h seems to fix it. Sorry, I should have tried that earlier.

**Comment by thinkyhead** [comment]
I modified the Makefile for Archim 1 also. I believe I got it right, as the build options for both Archim boards seem to be the same.

**Comment by Allted** [comment]
Okay it looks great! The Archim1 Configs are spot on.
#define MINIMUM_STEPPER_PULSE 2 in configuration_adv might be redundant but, you would know better than me.

I don't have much time on the Archim2 but I think it also needs,
#define SERIAL_PORT -1
#define SPI_SPEED SPI_HALF_SPEED

I appreciate the time you are spending on this. I had hoped I was a little closer and it wouldn't take this much of your time. Thanks again.

**Pull request merged**
