### PR TITLE
Bugfix 2.0.x FIx pins_BIQU_SKR_V1.1.h  in order to fix the blank screen generated by the latest version using MKS_MINI_12864  V1 and V2

### PR DESCRIPTION
**Pull request by DrDitto**
### Requirements
       Fix the problem of Blank Screen on BIQU_SKR_V1_1 using MKS_MINI_12864 with latest Version of 
      Firmware 
### Description
        Using latest version of the firmware cause a blank screee due a bad pin definitions
The suggested change requires to delete lines from 84 to 161at  pins_BIQU_SKR_V1.1.h and add this new ones
/**
 * LCD / Controller
 *
 * As of 20 JAN 2019 only the REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER display has
 * been tested with these settings. It can be connected to the SKR using standard cables
 * via the EXP1 and EXP2 ports. Other displays may need a custom cable and/or changes to
 * the pins defined below.
 *
 * The SD card on the LCD controller uses the same SPI signals as the LCD, resulting in
 * garbage/lines on the LCD display during SD card access. The LCD code mitigates this
 * by redrawing the screen after SD card accesses.
 */

 /*
 |               _____                                             _____
 |           NC | · · | GND                                    5V | · · | GND
 |        RESET | · · | 1.31(SD_DETECT)             (LCD_D7) 1.23 |     | 1.22 (LCD_D6)
 |   (MOSI)0.18 | · · | 3.25(BTN_EN2)               (LCD_D5) 1.21 | · · | 1.15 (LCD_D4)
 |  (SD_SS)1.23 | · · | 3.26(BTN_EN1)               (LCD_RS) 0.16 | · · | 1.18 (LCD_EN)
 |    (SCK)0.15 | · · | 0.17(MISO)                 (BTN_ENC) 2.11 | · · | 1.30 (BEEPER)
 |               ￣￣                                               ￣￣
 |               EXP2                                              EXP1
 */

 //
 #if ENABLED(ULTRA_LCD)
   #define BEEPER_PIN       P1_30   // (37) not 5V tolerant
   #define BTN_ENC          P2_11   // (58) open-drain

   #if ENABLED(CR10_STOCKDISPLAY)
     #define LCD_PINS_RS    P0_16

     #define BTN_EN1        P3_26
     #define BTN_EN2        P3_25

     #define LCD_PINS_ENABLE P0_18
     #define LCD_PINS_D4     P0_15

   #else
     #define LCD_PINS_RS    P0_16

     #define BTN_EN1        P3_26   // (31) J3-2 & AUX-4
     #define BTN_EN2        P3_25   // (33) J3-4 & AUX-4

     #define LCD_PINS_ENABLE P0_18
     #define LCD_PINS_D4     P0_15

     #define LCD_SDSS       P1_23   // (16) J3-7 & AUX-4
     #define SD_DETECT_PIN  P1_31   // (49) (NOT 5V tolerant)
     #if ENABLED(MKS_MINI_12864)
        #define DOGLCD_CS  P0_16
        #define DOGLCD_A0  P2_06
        #ifdef DEFAULT_LCD_CONTRAST
          #undef DEFAULT_LCD_CONTRAST
          #define DEFAULT_LCD_CONTRAST 160
        #endif
     #endif
     #if ENABLED(FYSETC_MINI_12864)
        #if EITHER(FYSETC_MINI_12864_1_2, FYSETC_MINI_12864_2_0)
            #ifndef RGB_LED_R_PIN
	            #define RGB_LED_R_PIN P1_21
	          #endif
	          #ifndef RGB_LED_G_PIN
	            #define RGB_LED_G_PIN P1_22
	          #endif
	          #ifndef RGB_LED_B_PIN
	            #define RGB_LED_B_PIN P1_23
	          #endif
        #elif ENABLED(FYSETC_MINI_12864_2_1)
            #define NEOPIXEL_PIN    P1_21
        #endif
     #endif
     #if ENABLED(ULTIPANEL)
       #define LCD_PINS_D5 P1_21
       #define LCD_PINS_D6 P1_22
       #define LCD_PINS_D7 P1_23
     #endif
   #endif
 #endif // ULTRA_LCD

 //
 // SD Support
 //

 #if !ANY(LPC_SD_LCD, LPC_SD_ONBOARD, LPC_SD_CUSTOM_CABLE)
   #undef USB_SD_DISABLED
   #define USB_SD_ONBOARD
   #define LPC_SD_LCD
 #endif

 #if ENABLED(LPC_SD_LCD)

   #define SCK_PIN          P0_15
   #define MISO_PIN         P0_17
   #define MOSI_PIN         P0_18
   #define SS_PIN           P0_16   // Chip select for SD card used by Marlin
   #define ONBOARD_SD_CS    P0_06   // Chip select for "System" SD card

 #elif ENABLED(LPC_SD_ONBOARD)

   #if ENABLED(USB_SD_ONBOARD)
     // When sharing the SD card with a PC we want the menu options to
     // mount/unmount the card and refresh it. So we disable card detect.
     #define SHARED_SD_CARD
     #undef SD_DETECT_PIN
     //#define SD_DETECT_PIN  P0_27   // (57) open-drain
   #endif

   #define SCK_PIN          P0_07
   #define MISO_PIN         P0_08
   #define MOSI_PIN         P0_09
   #define SS_PIN           P0_06   // Chip select for SD card used by Marlin
   #define ONBOARD_SD_CS    P0_06   // Chip select for "System" SD card

 #endif

  /**
   * Special pins
   *   P1_30  (37) (NOT 5V tolerant)
   *   P1_31  (49) (NOT 5V tolerant)
   *   P0_27  (57) (Open collector)
   *   P0_28  (58) (Open collector)
   */

### Benefits
       Mantain the campatibility of firmware if user has the BIQU_SKR_V1_1 and MKS_MINI_12864 configuration

Enable user to accces the latest firmware if they Hardware is  BIQU_SKR_V1_1 and MKS_MINI_12864

### CODE REVIEW

**Comment by gloomyandy** [comment]
Not really sure what is going on here. You may be better off closing this PR and starting again. If you are not familiar with the process for creating a PR for Marlin the details are here: http://marlinfw.org/docs/development/getting_started_pull_requests.html

Also there seem to be a large number of changes to the file and to definitions that are nothing to do with the MKS_MINI_12864 display. Have you tested these changes with the other displays mentioned? In particular there are references to pins P1_21 and P1_22 are these pins connected to any headers on the V1.1 board?

You have also changed the default SD card access to force it to use the LCD SD card reader in all cases (the previous default was to use the SD reader on the main board). This will cause problems for existing users (they may not even have an LCD, never mind a reader on it). 

It may be better if you can just identify the minimum changes needed to make the MKS_MINI_12864 work with this board.

**Comment by GMagician** [comment]
@DrDitto you have to redirect this to bugfix2 branch, now is 1.1

**Comment by gloomyandy** [comment]
Following on from a conversation on Marlin it looks like hardware changes are needed to route pins P1_21 and P1_22 to the LCD headers. I think this PR should be updated to make it clear that this is the case (and which displays need this hardware modification). Otherwise we will get folks assuming that displays that need these pins will work with this board.

**Comment by gloomyandy** [comment]
It also looks to me like the chip select pin being used for the LCD SD card reader is wrong. It looks like much of this is a copy and paste from the V1.3 pins file, but the CS is different on that board. I'm pretty sure the original value was correct. What displays have you tested with and have you checked that the SD card works on them?

**Comment by gloomyandy** [comment]
Looking again at this PR the pins diagram for the headers has a mistake in it on EXP1 it shows pin P1_15 going to D4 I think this should be P0_15 (SCK) as shown in the V1.1 schematic. The diagram also shows pins P1_21, P1_22 and P1_23 going to EXP1, none of those connections are there by default and would require additional wiring, the diagram should really indicate that this is the case. 

You also have pin P1_23 being used for LEDS for one of the displays and for LCD_PINS_D7 but P1_23 has already been defined as SD_SS so at the very least you will get a warning and you may also find that the onboard SD card reader now no longer works.

I'm trying to understand why these changes are needed. There are already pins defined for an MKS_MINI_12864 display in the pins file. But to use them hardware changes will be needed. My understanding is that these definitions did not work for you, but was that simply because you have made a different set of hardware modifications? It looks to me like the settings in the existing pins file would work fine with the matching hardware mods.

**Comment by DrDitto** [comment]
My mistake. This chane Is not required..
Mu Jumper cables was inverted

**Pull request closed without merging**
