### PR TITLE
[2.0.x] Followup to IDEX changes

### PR DESCRIPTION
**Pull request by thinkyhead**
Cleanups and tweaks to IDEX changes from #11690 by @Roxy-3D.

[(Concise Diff)](11707/files?w=1)

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I'll load it in the next day or so and see if everything still works.   The G1 X100 is important at the end of the enqueued LCD commands.   So I put those back in.

**Comment by thinkyhead** [comment]
The reason I removed `G1 X100` is that it's a fixed value. If the intention is to move to the middle or to some percentage of the X width, then let's base this value on the bed size. If it's just needed as a trick to un-park, then any X value at all should work. And, perhaps the value should be different for T0 versus T1…?

**Comment by Roxy-3D** [comment]
>  If the intention is to move to the middle or to some percentage of the X width, then let's base this value on the bed size. If it's just needed as a trick to un-park, then any X value at all should work. 

OK!  Let's do that!   I tried to use STRINGIFY and other things to get the text generated.   But I wasn't able to get that to work.    Tie idea is to center both nozzles in their own area, much like homing a single nozzle in the center of the bed.

On that other mode I was working on, I did try just jogging the nozzle .001mm but the planner didn't do anything with that movement.

> And, perhaps the value should be different for T0 versus T1…?

Probably it should be.   If you can add the #define's to encode this...   I'll get it tested.   I just wasn't that far yet.   I didn't want to use sprintf() to generate the text.   I wanted the compiler to generate the text so it could be put into program memory.

**Comment by Roxy-3D** [comment]
Let's go ahead and merge...   All of the changes are in the IDEX code blocks, so there is low risk to the 'normal' users.    Right now, I'm looking to get the filament run out detection working for IDEX.   (The problem being...  The filament can run out on nozzle 1 with nozzle 0 active.  And if only that was the main issue.   The problem is where to park nozzles so they don't hit each other.)

As soon as it is merged...   I'll test everything here...   and then use that as a base to get the filament runout stuff in place.

**Comment by thinkyhead** [comment]
> Let's do that! I tried to use `STRINGIFY` and other things to get the text generated.

Yeah, that's because `STRINGIFY` just takes the text of a `#define` and sticks quotes around it. If the define is "100" then you'll get that. If the `#define` is "MIN_X_POS + 100" you'll get that literal string.

The simplest solution here would be to make a custom internal-only G-code that moves X to the desired position based on which tool is selected and replace `G1 X100` with that G-code.

**Comment by Roxy-3D** [comment]
> The simplest solution here would be to make a custom internal-only G-code that moves X to the desired position based on which tool is selected and replace G1 X100 with that G-code.

Well...   If that is the case...  I'll just do a sprintf() in the next version and have it print the right location to go to.   And that makes it easy to take a user specified position and do something reasonable with it.

I'll test the merged code over the next few days.   But I probably won't get to it tomorrow.   

Thank You!

**Comment by thinkyhead** [comment]
>  I'll just do a sprintf() in the next version

The trouble with that is that `enqueue_and_echo_commands_P` only takes a PSTRing. And there's no option to use an SRAM-based string to build a queue of commands. So, if you want a command like `G1 X<pos>` to be enqueued at the right point, after the other commands, there's no method to do that outside of my suggestion above.

So, the easiest solution really is to make a hidden internal G-code, such as `G1001` and within the corresponding `GcodeSuite::G1001` queue up a planner move to the desired X position for the current tool.

**Comment by Roxy-3D** [comment]
Shouldn't we have an enqueue_and_echo_commands() [without the _P] so we can do things from strings constructed in RAM?    

At any rate...  I'll figure out something simple and small.  I understand what you are saying.

**Comment by thinkyhead** [comment]
> Shouldn't we have an `enqueue_and_echo_commands()` [without the `_P`] so we can do things from strings constructed in RAM?

It could be done, but so far hasn't been needed. Check out how the high-priority immediate command queue works, then simply construct a second immediate command queue plus queue processor that takes SRAM strings. Since the constructed string can't be on the stack, we'll need to pre-allocate a `static` character array to hold the SRAM-based command list.

**Pull request merged**
