### PR TITLE
Fixing display rotation for ili9488 after #19010

### PR DESCRIPTION
**Pull request by TheNitek**
### Description

After #19010 the rotation of the ili9488 doesn't match the rotation of the touch screen (if button is down left, touch area is on the top right).
I guess the same applys for st7796, but I am not sure and don't own hardware to test.

### Benefits

Fixes rotation, so it matches the touch screen again

### Related Issues

Caused by #19010

### CODE REVIEW

**Comment by mmajoor** [comment]
You can 'rotate' the touch screen by 'negating' the calibration and offset settings.
#define XPT2046_X_CALIBRATION
#define XPT2046_Y_CALIBRATION
#define XPT2046_X_OFFSET
#define XPT2046_Y_OFFSET

which are typically defined in configuration.h

**Comment by TheNitek** [comment]
What do you mean by negating? If have them set and the worked fine before #19010

My current settings:

  #define XPT2046_X_CALIBRATION 12316
  #define XPT2046_Y_CALIBRATION -8981
  #define XPT2046_X_OFFSET        -43
  #define XPT2046_Y_OFFSET        257

**Comment by thisiskeithb** [comment]
Tagging @tpruvot for review. Do these changes affect the TFTs you’re using?

**Comment by tpruvot** [comment]
not anymore, no... negating = reverse the sign of XPT2046_X_CALIBRATION and/or XPT2046_Y_CALIBRATION to mirror the touch

**Comment by mmajoor** [comment]
With 'negating' I mean changing the sign:
#define XPT2046_X_CALIBRATION 12316   --> -12316
#define XPT2046_Y_CALIBRATION -8981   -->  8981
#define XPT2046_X_OFFSET -43  --> 43
#define XPT2046_Y_OFFSET 257  --> -257

Or, maybe doing a touch calibration (TOUCH_SCREEN_CALIBRATION) also does the job.

**Comment by rhapsodyv** [comment]
I'm doing a refactoring in all TFT code for Emulated DOGM, Color UI and LVGL. I'm working now in "merging" all those init codes in a unique class, to remove repeated code and duplicated bugs.

**Comment by rhapsodyv** [comment]
With this refactoring, almost all options will be available for all Ui:

- tft interface
- tft resolution 
- tft driver
- tft rotation 
- tft mirror x or y
- tft type: color ui, classic ui or lvgl ui

**Comment by TheNitek** [comment]
I will wait fir the refactoring then.

**Pull request closed without merging**
