### PR TITLE
Touch screen calibration loop/stuck fix

### PR DESCRIPTION
**Pull request by quiret**
### Description

During my extensive HAL SPI rework testing using many boards and my trusty TS35 SPI TFT touch-screen I often encountered the bug where I was stuck unable to calibrate the touch screen. This was because the algorithm determined a failure in the first calibration fail prompting a retry. But that second cycle could not be completed due to a software model bug. This fixes the bug.

### Requirements

Touch Screen compatible with Marlin

### Benefits

Less frustrating touch-screen experience for Marlin users

### Related Issues

https://github.com/MarlinFirmware/Marlin/pull/24911

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Related PR:
- https://github.com/MarlinFirmware/Marlin/pull/25298

**Comment by quiret** [comment]
I am sorry but I have decided to halt my activities on this PR for an indetermined amount of time. You are free to decide whether to continue it yourself. Thank you to the Marlin firmware community for providing this interesting playing ground for testing my ideas and vision. I hope that Marlin will continue to go towards the best 3D printing solution! Hopefully my ideas have inspired you on how to continue this software!

**Comment by thinkyhead** [comment]
> Hopefully my ideas have inspired you on how to continue this software!

Thank you for visiting our busy workshop. Come by any time!

**Comment by thinkyhead** [comment]
Resetting to `CALIBRATION_NONE` on failure should have the same effect and should be okay with the other pending update, assuming that a failure very quickly goes back to the start.

**Pull request merged**
