### PR TITLE
Enable malyan lcd in M200 example configuration

### PR DESCRIPTION
**Pull request by xC0000005**
Malyan LCD Support should be enabled for M200 configuration. This PR also adds a sanity check for enabling MALYAN_LCD without also enabling SDSUPPORT.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I made sure to edit `malyanlcd.cpp` so `SDSUPPORT` can be disabled with Malyan LCD, in case it's needed for troubleshooting or just to leave out the SD code. We're pretty explicit now about the fact that you must enable `SDSUPPORT` to use SD cards, and we do want to allow it to be disabled without needing to edit out sanity-checks. So the comment "This requires SDSUPPORT to be enabled" is just outdated.

**Comment by xC0000005** [comment]
Thank you, that makes sense.

**Comment by thinkyhead** [comment]
> Remove no longer relevant comment.

What are you trying to change with that last commit?

**Comment by xC0000005** [comment]
I accidentally changed another file while trying to remove a comment, and undid it. I’m getting better at GIT but cleaning up commit history is something I’m still working on.

**Pull request merged**
