### PR TITLE
M600 can power down nozzles if filament change takes too long

### PR DESCRIPTION
**Pull request by Roxy-3D**
Bug fix for the M600 Filament Change command.  

Without these changes, the Filament Change code (especially if triggered by an 'End of Filament' sensor) fails to turn off the nozzle after a period of time.    If the user is not near the machine, this can cause the filament to retract and the remaining filament in the nozzle to 'cook' until it jams or destroys the nozzle.

These changes allow the user to specify a 'safe time' after which the nozzle will cool down.   If the nozzle cools down, the user can click the encoder wheel to start the re-heat process so the new filament can be inserted.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
@Tannoo   I wonder if we should specify which nozzle is active and being heated?   Maybe something like:
```cpp 
Nozzle: 2    185 / 205   
```   
And if so...   The heatup loop would naturally display which ever nozzle was causing it to wait.  It would get to a nozzle that is not up to temperature and complain about it.  (All nozzles would be heating, but which ever one is the first found that fails to meet the desired temperature would get the message.)

**Comment by ghost** [comment]
That would be good for multi-hotend setups.

**Comment by ghost** [comment]
Testing now.. Got it.

I did it like this:

`Nozzle X Temp: XXX`
`Nozzle X On: XXX`
`Nozzle X Off: XXX`

Not enough room to show set point also.

**Comment by Roxy-3D** [comment]
> Not enough room to show set point also.

Especially on the 4x20 displays...   We could use an extra line if needed?   But instead of Temp:, On:, and Off wouldn't it be clear to the user if we did 185/205  ?  I might not understand what you mean.   But the example:
```cpp
Nozzle: 2  185/205 
```
That all fits on a 20 character line???

**Comment by ghost** [comment]
If that is exactly how you want it displayed, ok.

**Comment by Roxy-3D** [comment]
> If that is exactly how you want it displayed, ok.

Yes.   It is mostly because of what has already been done.   Right now, that is the format for Temperature on the various LCD Panels.   That format will cause less confusion.     People will see the two numbers and it will be obvious to them what it means.  (Especially since nozzle temperature needs to be 'correct' in order to perform a filament change.)

**Comment by ghost** [comment]
Alright...no objections. I'm just having a hard time creating it or even finding the previous implementation. Point me in the right direction?

**Comment by Roxy-3D** [comment]
> Alright...no objections. I'm just having a hard time creating it or even finding the previous implementation. Point me in the right direction?

I did not mean there was a previous version of M600 that did this.    What I meant was the normal 'Status Screen' already displays the numbers that way.    On the 20x4 displays it shows:
```cpp
| 198/205  H 21/60
```
(The | and H are special characters.  In the text above | is a thermometer symbol.  If you choose to include the thermometer symbol, you should be able to encode that the same way the code displays it on the status screen)

**Comment by ghost** [comment]
I understand and I have been searching and trying. I just haven't found what works yet.
I used to have the Discount Smart Controller and I remember what your are talking about. I've just been hard pressed to find where it draws that line for the temps.

**Comment by ghost** [comment]
It looks like it's in this function somehow:

```
FORCE_INLINE void _draw_heater_status(const uint8_t x, const int8_t heater) {
  #if HAS_TEMP_BED
    bool isBed = heater < 0;
  #else
    const bool isBed = false;
  #endif

  if (PAGE_UNDER(7))
    _draw_centered_temp((isBed ? thermalManager.degTargetBed() : thermalManager.degTargetHotend(heater)) + 0.5, x, 7);

  if (PAGE_CONTAINS(21, 28))
    _draw_centered_temp((isBed ? thermalManager.degBed() : thermalManager.degHotend(heater)) + 0.5, x, 28);

  if (PAGE_CONTAINS(17, 20)) {
    const uint8_t h = isBed ? 7 : 8,
                  y = isBed ? 18 : 17;
    if (isBed ? thermalManager.isHeatingBed() : thermalManager.isHeatingHotend(heater)) {
      u8g.setColorIndex(0); // white on black
      u8g.drawBox(x + h, y, 2, 2);
      u8g.setColorIndex(1); // black on white
    }
    else {
      u8g.drawBox(x + h, y, 2, 2);
    }
  }
}
```

**Comment by Roxy-3D** [comment]
Some of the LCD code is cryptic.   I do know the Thermometer symbol is a 'Special Character' that is defined by a bit map.  I've never actually done anything with it directly.  How about we do this:   

If you can get the LCD to display:     Nozzle: 2  185/205     (or what ever numbers are appropriate, but in that format)

Using that...   I'll figure out how to get the little Thermometer symbol to be right in front of the 185.

**Comment by ghost** [comment]
`Nozzle: 2 185/205` is what I'm trying for. I'm not attempting special characters yet. lol

**Comment by Roxy-3D** [comment]
Oh!   OK!   This code only exists in the ..\Marlin\ultralcd_impl_DOGM.h file.   Which implies any changes you make will only affect the firmware if the DOGM hardware is in use.    

Also...   When I compare the 
```cpp
static void lcd_implementation_status_screen() {}
```
code in the ultralcd_impl_HD44780.h file I find this (which isn't in the ..\Marlin\ultralcd_impl_DOGM.h file):
```cpp
    LCD_TEMP(thermalManager.degHotend(0), thermalManager.degTargetHotend(0), LCD_STR_THERMOMETER[0]);
```
with LCD_TEMP() defined as
```cpp
  #define LCD_TEMP_ONLY(T1,T2) \
    lcd.print(itostr3(T1 + 0.5)); \
    lcd.print('/'); \
    lcd.print(itostr3left(T2 + 0.5))

  #define LCD_TEMP(T1,T2,PREFIX) \
    lcd.print(PREFIX); \
    LCD_TEMP_ONLY(T1,T2); \
    lcd_printPGM(PSTR(LCD_STR_DEGREE " ")); \
    if (T2 < 10) lcd.print(' ')
```
My guess is we can modify the various Filament Change Screen definitions referenced in:
```cpp
    void lcd_filament_change_show_message(const FilamentChangeMessage message) {
      switch (message) {
        case FILAMENT_CHANGE_MESSAGE_INIT:
          defer_return_to_status = true;
          lcd_goto_screen(lcd_filament_change_init_message);
          break;
        case FILAMENT_CHANGE_MESSAGE_UNLOAD:
          lcd_goto_screen(lcd_filament_change_unload_message);
          break;
        case FILAMENT_CHANGE_MESSAGE_INSERT:
          lcd_goto_screen(lcd_filament_change_insert_message);
          break;
        case FILAMENT_CHANGE_MESSAGE_LOAD:
          lcd_goto_screen(lcd_filament_change_load_message);
          break;
        case FILAMENT_CHANGE_MESSAGE_EXTRUDE:
          lcd_goto_screen(lcd_filament_change_extrude_message);
          break;
        case FILAMENT_CHANGE_MESSAGE_CLICK_TO_HEAT_NOZZLE:
          lcdDrawUpdate = LCDVIEW_CALL_REDRAW_NEXT;
          lcd_goto_screen(lcd_filament_change_heat_nozzle);
          break;
        case FILAMENT_CHANGE_MESSAGE_WAIT_FOR_NOZZLES_TO_HEAT:
          lcdDrawUpdate = LCDVIEW_CALL_REDRAW_NEXT;
          lcd_goto_screen(lcd_filament_change_wait_for_nozzles_to_heat);
          break;
        case FILAMENT_CHANGE_MESSAGE_OPTION:
          filament_change_menu_response = FILAMENT_CHANGE_RESPONSE_WAIT_FOR;
          lcd_goto_screen(lcd_filament_change_option_menu);
          break;
        case FILAMENT_CHANGE_MESSAGE_RESUME:
          lcd_goto_screen(lcd_filament_change_resume_message);
          break;
        case FILAMENT_CHANGE_MESSAGE_STATUS:
          lcd_return_to_status();
          break;
      }
    }
``` 
to make use of the lower level  lcd.print() calls that those macros use.    And it would appear to me that if we do a
```cpp
    lcd.print(LCD_STR_THERMOMETER[0]); 
```
we print a Thermometer symbol on the 20x4 non-graphics displays.   We will probably need some conditional code to turn that off if there is a graphics display and figure out what actually puts the thermometer on the LCD display for Graphics displays.   (or maybe we omit that for now...)

**Comment by ghost** [comment]
Ok... my brain is getting scrambled on this. Everything I try is giving me compile errors and I can't seem to make the compiler happy.
I had another way to make something work for my display, but I stopped with that because it wouldn't work for other displays.

**Comment by Roxy-3D** [comment]
> Ok... my brain is getting scrambled on this. Everything I try is giving me compile errors and I can't seem to make the compiler happy.   I had another way to make something work for my display, but I stopped with that because it wouldn't work for other displays.

I understand...   If you can get it working how you want it for your display...   I'll cross it over to the other displays.

**Comment by ghost** [comment]
Ok. Well, that didn't take NEAR as long as it did the first time. ;)

```
    void lcd_filament_change_heat_nozzle() {
      START_SCREEN();
      STATIC_ITEM(MSG_FILAMENT_CHANGE_HEADER, true, true);
      STATIC_ITEM(MSG_FILAMENT_CHANGE_INSERT_1);
      #ifdef MSG_FILAMENT_CHANGE_INSERT_2
        STATIC_ITEM(MSG_FILAMENT_CHANGE_INSERT_2);
      #endif
      #ifdef MSG_FILAMENT_CHANGE_INSERT_3
        STATIC_ITEM(MSG_FILAMENT_CHANGE_INSERT_3);
      #endif
      STATIC_ITEM(MSG_FILAMENT_CHANGE_NOZZLE STRINGIFY(HOTENDS), false, true);
      u8g.setPrintPos(72, 60);
      u8g.print(itostr3(thermalManager.degHotend(active_extruder)));
      u8g.print('/');
      u8g.print(itostr3(thermalManager.degTargetHotend(active_extruder)));
      END_SCREEN();
    }
```
I did this to these functions:
`lcd_filament_change_init_message()`
`lcd_filament_change_unload_message()`
`lcd_filament_change_wait_for_nozzles_to_heat()`
`lcd_filament_change_heat_nozzle()`
`lcd_filament_change_insert_message()`
`lcd_filament_change_load_message()`
`lcd_filament_change_extrude_message()`

wait for start

insert nozzle off

**Comment by Roxy-3D** [comment]
That looks very nice!    But I have a question.  (It maybe you just snapped the picture at a time that is misleading me!)   On the last picture, do we need an extra phase (or message)?   What I'm wondering is this:  We can't be telling users to insert the filament if the temperature of the nozzle is 0.   Should that screen say "Press button to heat nozzle to continue..." ?   And then have a follow up screen that says "Insert filament and press button to continue..." when the temperature is sufficient?

Also...  May I ask you to add the changes to this Pull Request?   I'll see if I can get all that text to fit on the 20x4 displays!

**Comment by ghost** [comment]
Yeah... Detail...details. Geez. ;)
I am at work now, so it might not be until morning now.

**Comment by Tannoo** [comment]
I can insert the filament down to the nozzle. Click, and it will heat then extrude.

**Comment by ghost** [comment]
But, we can do as you say. Message to say: "Click to heat nozzle".
Then, once it's heated: "Insert filament and click to continue.."

**Comment by Roxy-3D** [comment]
> I can insert the filament down to the nozzle. Click, and it will heat then extrude.

I know on my machines, I have to have the heat on to slide the filament down the pathway to the nozzle.   I'm not sure, but I think when the filament is pulled out, it leaves some residue in the pathway.  If the heat is on, I can push that residue into the nozzle and it melts and moves out of the way as I push the filament back in.  But if the heat is not on, I can only get the filament a little of the way towards the nozzle.

If you don't feel like changing it...  I can do that when I'm setting it up for the 20x4 displays.   I would just add an extra screen or change where the clicks happen.   (I'm not sure what has to be done without working through it step by step.)

**Comment by ghost** [comment]
Please don't get me wrong, I am not trying to create any heat here. (Punn intended)

I have no issue with the way it is, or with the way you would like it. I'm willing to change it, but am unable to atm.

**Comment by Roxy-3D** [comment]
> Please don't get me wrong, I am not trying to create any heat here. (Punn intended)

No!  I understand that!

> I have no issue with the way it is, or with the way you would like it. I'm willing to change it, but am unable to atm.

I am very appreciative for what you have done.   I don't want it to feel like I'm dictating how things should be.   I understand you are doing this work because you have a very specific need for it.   What I'm trying to say is "I'll take what ever work you can and feel like doing."    And the fact you don't have a 20x4 display means it is very difficult for you to do that side of the work anyway.   

Thanks for your help!!!

**Comment by ghost** [comment]
Np. I don't mind. But sometimes my mind turns to mush. Lol

**Comment by Tannoo** [comment]
I don't know how to declare a library that is included.
It compiles and runs just fine (earlier pics). Just Travis doesn't like it.

**Comment by Roxy-3D** [comment]
I'm not sure what is going on with Travis.   But it would appear when Travis does the compile, the u8g object is not defined yet.  That is why it gets this error message:
```cpp
sketch/ultralcd.cpp: In function 'void lcd_filament_change_init_message()':
ultralcd.cpp:2484: error: 'u8g' was not declared in this scope
       u8g.setPrintPos(72, 60);
       ^
sketch/ultralcd.cpp: In function 'void lcd_filament_change_unload_message()':
ultralcd.cpp:2503: error: 'u8g' was not declared in this scope
       u8g.setPrintPos(72, 60);
       ^
sketch/ultralcd.cpp: In function 'void lcd_filament_change_wait_for_nozzles_to_heat()':
...
exit status 1
'u8g' was not declared in this scope
The command "build_marlin" exited with 1.
$ restore_configs
```
It is strange it compiles and links on your build machine but it fails the Travis checks.   One thing I noticed is an inconsistent reference to the u8glib.h include.   Some places it is referenced with a "u8glib.h" and in other places it is used as <u8glib.h>      I wonder if the Travis paths are different than the Arduino paths?

But anyway....   The u8g object is declared in utility/u8g.h    And...  the Travis compile is claiming it is not declared.      Probably the thing to do is start fresh with the last Travis build that succeeded, and then just make those changes that trigger the first Travis failure.    

Without understanding the root cause of the failure...  There are a couple of things I would try.   One idea might be to move those functions to the bottom of the ultralcd.cpp file and see if things pass Travis.  I kind of doubt that will do it because it is complaining about the u8g object not being declared.   However, it might just work because the kill_screen() function uses the u8g. object.    But only if DOGLCD is declared.     Did you enable DOGLCD ????
```cpp
void kill_screen(const char* lcd_msg) {
  lcd_init();
  lcd_setalertstatuspgm(lcd_msg);
  #if ENABLED(DOGLCD)
    u8g.firstPage();
    do {
      lcd_kill_screen();
    } while (u8g.nextPage());
  #else
    lcd_kill_screen();
  #endif
}
```

**Comment by ghost** [comment]
DOGM is defined in configuration.h.

I moved all of the ug8 library calls out of `ultralcd.cpp` and into `ultralcd_impl_DOGM.h`

Still no good. But says that `lcd_impletmentation_hotend_status()` is not declared. So, I declared it. Nope.

**Comment by ghost** [comment]
Now, it is undefined reference. HELP! I'm snowballing here.

Before I declaired `lcd_impletmentation_hotend_status()` in `ultralcd.cpp`, it compiled and runs just as good as before I moved the u8g calls. I don't think declairing that will compile. I am not with the pr(i)nter until morning again.

**Comment by ghost** [comment]
Travis was fine before I put the u8g calls in for the hotend temps.

**Comment by Roxy-3D** [comment]
And one more thing....    I'm not an expert at the ultralcd.cpp module.   But I think the u8g object is only used for the graphics display.   If that is true, it might make the problem simpler to understand and fix.   If we can get the code to compile clean for the 20x4 LCD display, we will know we are fighting a Graphics Display problem.    

It might be worth turning off the graphics display and only mess with the ULTIPANEL LCD at first.   And once that works OK, start fighting the Graphics panel problems.   (I'm also not a Travis expert.   But in order for the ultralcd.cpp code to be compiled, the Travis code must be turning on LCD Panel code.   And in the case we are fighting, it is turning on the Graphics Panel #define's.)

**Comment by ghost** [comment]
I have another idea to fix travis, but to much to do on my phone. Will have to wait til I get to computer.

**Comment by Roxy-3D** [comment]
Is it because of a spelling mistake?  You have a 't' in there that might not be your forward declaration:    lcd_imple t mentation_hotend_status();
```cpp
Preparing boards...
Verifying...
sketch/ultralcd.cpp: In function 'void lcd_filament_change_init_message()':
ultralcd.cpp:2484: error: 'lcd_impletmentation_hotend_status' was not declared in this scope
       lcd_impletmentation_hotend_status();
```

**Comment by ghost** [comment]
I can't see that being an issue because it was misspelled the exact same way in the `ultralcd_impl_DOGM.h` file.
I am able to get PR against your RCBugFix now. I created a branch called `Filament-change-shutdown`. So, I have a PR for ya.

**Comment by ghost** [comment]
I don't get it. Does Travis use an old version of the compiler? My Arudino 1.8.0 doesn't fuss. It compiles and the printer runs it. No issues here.

**Comment by ghost** [comment]
I'll try an older version of the Arduino IDE and see if I can get the same error.
I see that Travis uses 1.6.10.
Tried 1.6.12 and no issues.
I'll try to get 1.6.10 and see about that. -- No issues with 1.6.10.

**Comment by ghost** [comment]
undefined reference to `lcd_implementation_hotend_status()`.  Hmmmm

**Comment by ghost** [comment]
I've concluded that Travis doesn't like me.

**Comment by Roxy-3D** [comment]
I think the logical thing to try is to #define something in each of the header files (with the same name) that prints things to the LCD Display.    In the ultralcd_st7920_u8glib_rrd.h file it can reference the u8g object.  Probably it can be #define'd to use u8g.print();    In the ultralcd_implementation_hitachi_HD44780.h the #define can probably reference lcd.print();    

And then in ultralcd.cpp you would just use the same name to print stuff but because of which header file is being pulled in, one or the other would get used.

Does what I'm suggesting make sense?    If you want to switch gears, the offer still stands.  If you get it so it compiles clean and loads into your board and does things how you want it...   I'll fight with it to make it work on the 20x4 LCD Displays.

**Comment by ghost** [comment]
I'll stab that in there. Do you think Travis is not liking it because it doesn't exist for the other display?

**Comment by ghost** [comment]
That was it! Now, still had an error, but it passed? Removed the declaration in `ultralcd.h`.

**Comment by ghost** [comment]
Online editor blows.

**Comment by ghost** [comment]
Maybe I will get the RepRap Discount Controller, install it and test.

**Comment by ghost** [comment]
It all compiles, loads, and runs just fine for me. Travis is even happy with just a generic function for the 20x4's!

**Comment by Roxy-3D** [comment]
Great!   Isn't software fun!  :)     Are we ready for some testing?    Should we do some sanity checks prior to trying to get it better tested?

**Comment by ghost** [comment]
Please check and adjust the 20x4 display first. I only threw some numbers in there as a guess. Not tested yet. Sanity checks are good. But aren't they already there for the filament change and LCD requirement?

**Comment by ghost** [comment]
I had also changed too cold screen to show the min extrude temp and the current temp/set point at the bottom of the screen (on my display). Should also remove the menu item of filament change when the nozzle is too cold. That's a whole other thing, but should be easy to implement.

**Comment by Roxy-3D** [comment]
> The only Sanity checks are good. But aren't they already there for the filament change and LCD requirement?

I meant have a few other people load up the code and verify it works on their machines as expected.  (I didn't mean putting and new code to detect issues in the Sanity.cpp file.)

**Comment by ghost** [comment]
That's ok for the graphic displays. But, do you want to get the 20x4 displays to display properly before that?

**Comment by Roxy-3D** [comment]
> I had also changed too cold screen to show the min extrude temp and the current temp/set point at the bottom of the screen (on my display). 

OK

> Should also remove the menu item of filament change when the nozzle is too cold. That's a whole other thing, but should be easy to implement.

I wonder if it would be better to put a 'Warm Up' loop at the start of the M600 to handle this case?   The problem is we don't know what temperature is appropriate.    For now, the 'Right' answer might be to bail out (at the top) of the M600 if the nozzle is below the 'Cold Extrusion' temperature.  (Also, remember...  we have to gracefully handle the non-LCD initiated M600.  If the M600 is coming from PronterFace, it doesn't matter if we remove it from the LCD Menu)    Your thoughts?

**Comment by ghost** [comment]
I was only thinking of removing the menu item in the Prepare menu if it is too cold. The actual toocold screen will still be there for an M600 command when too cold. The cold extrusion temp is already specified in `configuration.h`.

Not a big deal. I found that this works (`ultralcd.cpp`):
```
      #if ENABLED(FILAMENT_CHANGE_FEATURE)
        if (!thermalManager.tooColdToExtrude(active_extruder))
          MENU_ITEM(function, MSG_FILAMENTCHANGE, lcd_enqueue_filament_change);
      #endif
```

**Comment by Roxy-3D** [comment]
Let me know when you get all of your changes in...   (No hurry!)    

When you think you have it all wrapped up and are ready to tie a bow ribbon on it, please speak up.

I'll give it a quick test on an 20x4 LCD screen....   And once that works...  I'm going to start moving it to the UBL branch.    ThinkyHead will be back at it in a few days.    I think I'll let ThinkyHead do the merge into the RCBugFix branch just because I don't want to complicate what he has going.

**Comment by ghost** [comment]
Okay. I'm done and Travis happy.

**Comment by Roxy-3D** [comment]
I've got a couple of items I want to get done.   One is to bring up RC-8 on my gMax printer and get it fully tuned.   I think I'm going to use this branch to do that and include #5729 as the base line.

If and when that is operating well, I'm going to start crossing the UBL code over to it.   And when that is up and running, it will form the new base line for the devel-ubl branch.    The problem (from your point of view) with this approach is until the new base line for UBL is working...  I won't be checking it out on 20x4 displays.   But really...  that isn't a big problem.   If the filament change works with the Graphics LCD Displays...  It won't be very hard to convince it to work with the 20x4 displays.  It will just be a slight delay.

As soon as the the UBL base line is working...  I have two 20x4 LCD Display printers to bring up using the code.  If there is a problem with 20x4 LCD's...   I'll see it and get it fixed.

**Comment by ghost** [comment]
Ok. In the mean time. I am running it in my printer full time (along with other things). I like it.

**Comment by ghost** [comment]
I do want to thank you, @Roxy-3D. You have been a big help with this as well as being patient with me.

**Comment by Roxy-3D** [comment]
> I do want to thank you

You are very welcome!

**Comment by Roxy-3D** [comment]
OK!   We need a number of people to load this Pull Request and test it.   There was a lot of chaos because the changes got put into two different branches and needed to be merged.

**Comment by Roxy-3D** [comment]
I had to mess with the 
```cpp
static void lcd_implementation_hotend_status() {
  u8g.setPrintPos(50, 60);
  lcd_print( (char) '0'+active_extruder );
  lcd_print( ' ' ); 
  lcd_print( ' ' ); 
  lcd_print(itostr3(thermalManager.degHotend(active_extruder)));
  lcd_print('/');
  lcd_print(itostr3(thermalManager.degTargetHotend(active_extruder)));
}
```
to get the nozzle number onto the Graphics LCD screen.   And there were corresponding changes to ultralcd.cpp to eliminate all the lines that looked like:
```cpp
     STATIC_ITEM(MSG_FILAMENT_CHANGE_NOZZLE, false, true);
```
To strip the STRINGIFY(HOTENDS) out of the function call.

**Comment by ghost** [comment]
M'kay, m'kay.

**Comment by ghost** [comment]
I tested this branch and it works fine on this end.

**Comment by ghost** [comment]
Esthetics: Can you move the `Nozzle:0  xxx/xxx` closer to center?

**Comment by Tannoo** [comment]
Curiosity: Wouldn't the u8g.print be faster than calling another function (lcd_print())?

**Comment by Roxy-3D** [comment]
> Esthetics: Can you move the Nozzle:0 xxx/xxx closer to center?

I shifted the Nozzle Temperature message 8 pixels to the right.   That looks pretty close to centered.

But we seem to still have that double click at the very end....   I don't know what is causing that.

**Comment by ghost** [comment]
I don't have that issue anymore. I click once before the nozzle shuts down and it starts extruding. No need to click again.

**Comment by Roxy-3D** [comment]
I'm needing to click twice at the very end...   It isn't that big of a deal...   But it doesn't make sense to me.

**Comment by ghost** [comment]
That was fixed with line 7434 in `marlin_main.cpp`.

**Comment by ghost** [comment]
I'll try it again after this print that I have running.

**Comment by ghost** [comment]
>I'm needing to click twice at the very end

After loading, heating, or extruding?

**Comment by Roxy-3D** [comment]
At the Extrude more or Continue Print screen.

**Comment by ghost** [comment]
Ok....I tried it during this print and yes, that is a new issue. It wasn't there before. OR... maybe I just didn't notice it before because I can't find any previous builds that are different enough to cause it.

**Comment by Roxy-3D** [comment]
Well...   I'll find the cause soon enough...    I'm moving the UBL code base to RC-8's RCBugFix.   And I figured I'ld include the updated M600 just to get some more test time on it.   The UBL code takes over the Encoder Wheel (and LCD Display) at certain points.   So I'm going to be messing around with the button debouncing any way. 

What ever is causing that...    I'll find it.   But it isn't a super high priority.   It might take a couple of weeks to  figure it out and clean up the problem.   Also...   It is very possible it doesn't happen on 20x4 LCD Displays.   I won't know that until I try to bring up one of my older printers with the new UBL code base.   

If you find the cause...  Be sure to holler and let people know!  But for the next couple of weeks...  People can press the Encoder Wheel twice at the end of the M600.   And there will be a bug fix soon enough for them!  I don't think this keeps us from merging the Pull Request.

**Comment by ghost** [comment]
I have a RepRap Discount LCD display in the mail. So, I will be able to test that when it gets here.

**Comment by thinkyhead** [comment]
Doing a little `git rebase -i` to squash this down…
```
git rebase -i RCBugFix

...

pick 0e60411a3 Nozzle shutdown during M600
f a3d9be7d8 Nozzle shutdown during M600   
f d4a93f12e Nozzle shutdown during M600   
f 82ac90374 Nozzle shutdown during M600   
f 95a560dd0 fix botched edit   
pick 9236c5a21 Don't let compiler complain about integer overflow
pick 32784cfb8 Show nozzle temperature while heating nozzle
f ab8dab9da Show nozzle temperature while heating during M600   
f c44aff6ee Make M600 show nozzle temp while heating   
pick bfcc26bf5 Display active extruder during M600 instead of extruder 0
pick c207ec177 Try to get Travis happy
f f81cc6a40 Fix botched edit that confuses Travis   
f 19d5bddb6 Undo change to try to make Travis happy   
pick 8efdf3dc6 Change wording...
pick 568492ce9 Add Tannoo's new Filament Change Messages
f 3b2ddae8c One more Tannoo message added!   
f db37445be Switch over to Tannoo's symbolic text names   
pick e7556d4f1 Update Readme
pick cedb1f667 Update Marlin_main.cpp
pick d752bcb12 Show temp on more filament change screens
pick 959b56a7b Show Active Nozzle Temp
pick a9f4171ad A few subtle screen changes.. ;)
pick 8d0f4d4f9 Update ultralcd.cpp
f aaa396a54 Update ultralcd.cpp   
pick f93ba3ce1 Trying to make Travis happy
f aa5b8b032 Travis correction?   
f 1366dc85f Undoing last commit   
f abcbfda47 See if this helps   
f bd355dee8 Maybe Travis will like this?   
pick f3ce0ce7a Cleanup and toocold menu change (#3)
pick 689cb28aa Changes for Travis (#4)
f 136fc586a Declaration for Travis (#5)   
f e0df23460 Travis Happy Yet (#6)   
f 19b459554 Travis Happy Yet (#7)   
pick 9a221e595 Update ultralcd.h
f 06c4d69cd Update ultralcd.h   
f 22b00f45d Update ultralcd.h   
pick 01e3e3c89 Remove Filament Change from Prepare Menu if too cold
pick aaca9433c Update M119
pick e515a785d Beep timeout cleanup
pick 7cd048fae Missed a configuration setting.
pick be8f35604 Move Tannoo's changes to RCBugFix
f 25cb85da0 moving stuff over from RC branch   
f 71d9525ee move changes from RC to RCBugFix   
f a1fdd0e3e Move a definition from RC to RCBugFix   
pick df30043a3 Safer defaults for Filament Change
pick f3d3690de M600 will now display nozzle number on Graphics LCD's
f f261f1da4 Make M600 display correct active nozzle number   
r 8fd794adc Better center Hotend Status message   
f 28af8e160 Better center Nozzle Temp message   
f 2d9528d9c More tweaking to get message centered nicely
```

**Comment by thinkyhead** [comment]
Superseded by #5794. Please test and confirm it still functions as designed.

**Pull request closed without merging**
