### PR TITLE
SAMD51: Update LCD pins

### PR DESCRIPTION
**Pull request by GMagician**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Where did the original pins come from in the first place? Was throwing of dice involved?

**Comment by GMagician** [comment]
I answer a message I got from you...ruramps4d pins are a mess, there is an image on internet with some pins, but for version 1.1 (there is used also pin 54?!? and has also duplicated pins), add the fact that analog pins are mapped to different digital in AGCM4 and that I don't have shield in my hands (and I think I'll never have...it's almost 1 month I'm waiting it to be sent and seller doesn't answer to mails, I open a report with paypal so I hope to have back my money)...by the way, any suggestion for a good shield for due?

**Comment by thinkyhead** [comment]
I'm not surprised the information is scarce, being on the other side of the Iron Curtain.

**Comment by thinkyhead** [comment]
> a good shield for due?

I hear various complaints about Due shields, but they all seem reasonably good to me. Check reviews, especially anything by **Alex Kenis** on YouTube. If he reviewed these kinds of shields, it will be very thorough.

**Comment by GMagician** [comment]
> I hear various complaints about Due shields

How can be due the most Marlin used platform...without a shield? I'm astonished

**Pull request merged**
