### PR TITLE
Fix continuous Z raise

### PR DESCRIPTION
**Pull request by GMagician**
This will fix the continuos z raise when safe_homing and X or Y has no known position

Depending on "mainteiners" choice it is also possible to prevent Z raise and send serial message. Let me know prefered solution

### CODE REVIEW

**Comment by sjasonsmith** [comment]
Is this in response to any open issues? There is at least one open that this might resolve, or should at least test with the change.

I want to go back and find the issue that caused me to introduce this problem in the first place, to make sure we haven’t reverted back to old problems. I’ll find it a little later this morning and reply again.

**Comment by GMagician** [comment]
@sjasonsmith not issue for it. I faced it on my printer and it was a long time I wanted to fix.
When you have Z_SAFE_HOME and you ask for home Z, it will home X, Y and finally Z but once you have done it and wait for stepper to turn off, when you ask to home Z Marlin will raise Z and echo a message to home X & Y first. If you ask home again it will raise Z other time.
It's not really a "continuos" move it's just a "continuos move as soon as you ask for home Z".

**Comment by sjasonsmith** [comment]
Unfortunately I cannot find the currently open issue. It might be related to probe settings and not this anyway.

This is the issue I was fixing when I accidentally introduced the issue you are fixing:
https://github.com/MarlinFirmware/Marlin/issues/15827

And this was the original pull request:
https://github.com/MarlinFirmware/Marlin/pull/15859

My change was intended to prevent bed damage if motors were disabled, and the nozzle fell to the bed. I only later discovered this "Repeated Raise" issue I had introduced.

We should test to make sure that problem is still solved. I am willing to help do that, but will probably not have time until tomorrow.

**Comment by GMagician** [comment]
This fix will not hurt that because it will force X & Y home when they are not homed (as before) or have not known position (before it raised Z and signal error)

**Comment by GMagician** [comment]
...and forgot...z will always raise, as before

**Comment by GMagician** [comment]
what I can't fix is that if you home X or Y multiple times.....it will always raise Z before

**Comment by sjasonsmith** [comment]
The complaints I received were that people would home X and Y separately, and each would cause a Z raise.
I thought that was what you were fixing here, but perhaps not. There have been other changes to the homing code recently, so it seems you may be addressing a different annoyance.

**Comment by GMagician** [comment]
Yes my solution is for something different....

**Comment by thinkyhead** [comment]
It might be good to isolate the concept of Z Raise into its own function. When a probe needs clearance, whether for homing or for probing, Z should only raise if it is not already known to be above the clearance height. So in all cases we check if the Z axis position is "known" — homed, at least, and Z steppers still enabled — and only do a "prudent raise" above the current position when Z is unknown.

```cpp
void do_z_clearance(const float &zclear, const bool z_known, const bool raise_on_unknown=true, const bool lower_allowed=false) {
  const bool rel = raise_on_unknown && !z_known;
  float zdest = zclear + (rel ? current_position.z : 0.0f);
  if (!lower_allowed) NOLESS(zdest, current_position.z);
  do_blocking_move_to_z(zdest);
}

do_z_clearance(Z_CLEARANCE_BETWEEN_PROBES, TEST(axis_known_position, Z_AXIS));
```

**Comment by thinkyhead** [comment]
> The complaints I received were that people would home X and Y separately, and each would cause a Z raise.

When Z is unknown, that will cause Z to raise for individual X homing and Y homing. The amount of raise in that case will depend on `Z_HOMING_HEIGHT`. This is more or less unavoidable. Instead of homing X and Y separately, `G28 XY` should be used to get only a single raise of Z.

**Comment by thinkyhead** [comment]
> This will fix the continuos z raise when safe_homing and X or Y has no known position

If your XY steppers are getting disabled frequently and this safety feature is problematic, the correct solution is to disable the `HOME_AFTER_DEACTIVATE` option. That setting is forcing re-homing of axes to be required whenever those steppers are disabled. Unfortunately there is currently no option to turn this behavior on and off at runtime.

One way to deal with the Z-raise-too-much issue would be to alter the way Z homing works a bit, so that Z is zeroed out as the very first step whenever Z is being homed towards the bed. Then, at the same time the `axis_known_position.z` flag is set so that all Z probe raise moves are absolute (relative to whatever Z=0 happens to be right now).

**Comment by GMagician** [comment]
What I did is just automate the thing. Now Marlin will ask you to home X & Y before homing Z. Now that you highlighted this, X & Y don't really need to be homed and Z can freely home even if X & Y have no known pos, otherwise one should activate the option.Probably the fix will be just remove the message.

Edit: please note that this fix is not intended to prevent z raise when homing all but Z. It's meant to prevent z raise each time home Z is required but no X & Y have known position

**Comment by GMagician** [comment]
@thinkyhead I saw now your PR to address this. You added `if (axis_unhomed_error(_BV(X_AXIS) | _BV(Y_AXIS))) return;` but this is not required since, at the beginning of G28, you have:
```c++
  needX = homeZ && TERN0(Z_SAFE_HOMING, axes_need_homing(_BV(X_AXIS))),
  needY = homeZ && TERN0(Z_SAFE_HOMING, axes_need_homing(_BV(Y_AXIS))),
```

then in such case you force a X and/or Y homing before. When you are here they are homed. The "bad" behaviour was when X & Y had "unknown position". In such case needX/Y was false but test in `home_z_safely` gave error

**Comment by thinkyhead** [comment]
> You added…

Well, I re-phrased the original error-check since `axis_unhomed_error` gives good enough serial feedback.

> …this is not required since, at the beginning of `G28`, you have…

The `home_z_safely` function is only called from one place today, so the test was never expected to fail and return (unless there was an issue). For safety (and to catch bugs) `home_z_safely` has that small guard at the beginning. It was useful to spawn this report, and it will be useful if the method is ever called from someplace else in the future.

> The "bad" behaviour was when X & Y had "unknown position"

That should now be solved, because `axis_unhomed_error` also uses `axes_need_homing` to do its test.

**Pull request closed without merging**
