### PR TITLE
 Fix the problem of Blank Screen on BIQU_SKR_V1_1 using MKS_MINI_12864 with latest Version of    Firmware 

### PR DESCRIPTION
**Pull request by DrDitto**
### Requirements

   Using latest version of the firmware cause a blank screee due a bad pin definitions
The suggested change requires to delete lines from 84 to 161at pins_BIQU_SKR_V1.1.h and add this new ones

/**### Description

### CODE REVIEW

**Comment by gloomyandy** [comment]
You are trying to merge commits from a 1.1.x branch into 2.0.x. Here are the instructions for creating a Marlin pull request: http://marlinfw.org/docs/development/getting_started_pull_requests.html

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we are no longer accepting PRs directed to the 1.1.x branch. Please redo this PR starting with the `bugfix-2.0.x` branch and be sure to target `bugfix-2.0.x` when resubmitting the PR.

**Comment by DrDitto** [comment]
I am sorry, I am new at the comuniti and does not kown how to fill the pull request
May you guide me ?

**Comment by gloomyandy** [comment]
@DrDitto See the guide http://marlinfw.org/docs/development/getting_started_pull_requests.html also please see my comments on your previous PR. Some of your proposed changes seems to be using the wrong pins.

**Pull request closed without merging**
