### PR TITLE
[2.0.x] fix home endstop bug

### PR DESCRIPTION
**Pull request by GMagician**
#11894 fix.

### CODE REVIEW

**Comment by GMagician** [comment]
@thinkyhead do you know something about https://github.com/MarlinFirmware/Marlin/issues/11894#issuecomment-423808806 ?
I know for sure this is used by G38 that on exit calls `not_homing` hence no issues, but doesn't G38 need endstops check when globally enabled?

**Comment by thinkyhead** [comment]
The move abort is always handled in `endstops.update()`. It's either called at the top or it's called a little further on, since some extra states need to be updated.
```cpp
// Check endstops - Could be called from Temperature ISR!
void Endstops::update() {

  #if DISABLED(ENDSTOP_NOISE_FILTER)
    if (!abort_enabled()) return;
  #endif
  . . .
  #if ENABLED(ENDSTOP_NOISE_FILTER)
    if (!abort_enabled()) return;
  #endif
  . . .
}
```

**Comment by thinkyhead** [comment]
`G38` isn't specified to check anything except the probe, just as probing down to the bed with `G30` only checks the Z probe and not the endstops.

**Comment by thinkyhead** [comment]
I think this PR is sensible, and seems safe to merge… for beta testing.

**Comment by GMagician** [comment]
> G38 isn't specified to check anything except the probe, just as probing down to the bed with G30 only checks the Z probe and not the endstops.

Not sure to understand but because of
```cpp
#if DISABLED(ENDSTOP_NOISE_FILTER)
    if (!abort_enabled()) return;
  #endif
```
in the begin of `endstops.update()` and since G38 call `endstops.enable(false)` then endstop are bypassed even if globally enabled

**Review by GMagician — COMMENTED** [review]
There was a reason because I splitted in two lines. count = 0 is for interrupt to stop updating validated_line. Then I 0 validated.
Not sure this sequence now will keep correct order (I think that you have to revert variable but maybe is compiler dependant)

**Comment by GMagician** [comment]
@thinkyhead I think I messed up with messages. Above is related to your 3bcac39.
As stated above I reset first variable so that interrupt will not update second one (`validated_live`). If order is not correct `validated_live` may be reinitialized by interrupt (poll method in temperature isr) and this will not be good

**Pull request merged**
