### PR TITLE
Option to reset EEPROM on first run

### PR DESCRIPTION
**Pull request by ellensp**
### Description

One user issue we get constantly Is users updating their firmware and not refreshing their EEPROM contents to match the new firmware. At present if they are using the same eeprom version Marlin does not catch this and the user gets confused that their new settings in the configuration files are not working.

This attempts to solve this issue.

Adds the new Config option EEPROM_CHECK_BUILD_COUNT (recommend this is enabled by default) 

The option  extends the EEPROM version from eg "V86" to "V86.4" where the 4 is the firmware build count. 
The build count Increases each and every build  (pltfomioio only) 

On a version mismatch Marlin loads the defaults settings from firmware. 
Thus the user is never left in a situation where they have updated their firmware and it is still using the old settings from EEPROM

Example:
```
> echo:EEPROM version mismatch (EEPROM=V86.1 Marlin=V86.4)
> echo:Hardcoded Default Settings Loaded
```

### Requirements

#define EEPROM_SETTINGS
#define EEPROM_CHECK_BUILD_COUNT

### Benefits

Stops the # 1 cause of user confusion. 

### Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/7672263/Configuration.zip)

### Related
Latest example to of this issue that was reported as a bug https://github.com/MarlinFirmware/Marlin/issues/23328

### CODE REVIEW

**Comment by ellensp** [comment]
Thoughts? Constructive criticism?

**Comment by thinkyhead** [comment]
How many bug reports in recent versions of Marlin are simply solved by M502 M500 ?

The current mechanisms of validating the EEPROM datasize and checksum — then giving users the option to reset the EEPROM on errors — seems sufficient to me. If users don't have an LCD, the factory defaults are still loaded transparently. We don't necessarily want every new build to require an EEPROM reset.

**Comment by ellensp** [comment]
Most people do not use EEPROM for how it was intended, most only use it to store bed mesh data. Thus they get very confused when previous setting are still there

**Comment by The-EG** [comment]
If you search the Discord for 'M502' I think you'll see that the confusion around when it's needed happens pretty frequently. 

The questions tend to come up in the form of 'I updated some setting in Configuration.h but nothing changed.'

**Comment by mriscoc** [comment]
I think this is a good idea, I have had error reports because the user forgot to load defaults and save settings, I had to modify the EEPROM version to force to clear the EEPROM after flashing the firmware.

**Comment by ellensp** [comment]
I originally started with something like `strhash32(__DATE__ __TIME__);` 
But the way platformio caches .o data __DATE__ and __TIME__ are not updated every build.
I had to force ably remove the settings.cpp.o using buildroot/share/PlatformIO/scripts/preflight-checks.py in the same way you did with warnings.cpp.o   Which I didn't like...   
So I simplified to a increasing byte in an include. As platform notices the file change.

**Comment by thinkyhead** [comment]
> … I originally started with something like `strhash32(__DATE__ __TIME__)` …

I prefer this because it is slightly less dependent on PlatformIO, whereas the previous method would prevent a successful compile in Arduino IDE with the new option enabled.

**Comment by ellensp** [comment]
"would prevent a successful compile in Arduino IDE with the new option enabled."  I fail to see how this is a bad thing :) 
Anything to force users away from arduino ide....

**Comment by Sonicboom247** [comment]
Brilliant, especially in my case #23244 where the TFT might be stuck and therefore not able to send a reset via TFT or any slicer.  fingers crossed this addresses that issue and all the other 12864 issues popping up.

**Comment by patoberli** [comment]
One question to this change, does that mean my ABL Z-Offset will be reset after every firmware update and I have to either correctly add it into my custom firmware build somewhere or somehow remember to set it again after every update?
If the second, then this might cause some confusion for a while. Maybe add a "Settings reset" message to the screen when updating the firmware?

**Pull request merged**
