### PR TITLE
Added warning for number of axis limit

### PR DESCRIPTION
**Pull request by maxabrahamsson**
In regards to following issue;
https://github.com/MarlinFirmware/Marlin/issues/2743

I also saw people on forums, trying to adjust seperate extruders by changing values here.

It is good to have this warning here.

### CODE REVIEW

**Comment by AnHardt** [comment]
@MarlinFirmware/collaborators 
On what branches should this be applied - if any?

Do you see any chance for implementing more the 4 axes soon?

**Comment by AnHardt** [comment]
At least for the `release` branch this comment makes perfect sense to me.

**Comment by maxabrahamsson** [comment]
There is chance for more than 4 axes implementation. It shouldn't be too difficult to implement.

Yes, I agree it will be enough if added to release branch.

**Comment by Roxy-3D** [comment]
> At least for the release branch this comment makes perfect sense to me.

Is this a mis-typing on the keyboard?   It would seem to me the Development Branch is the correct place to do this first???   And once it is working there, if there is enough demand for it, it would get moved to a Release branch.   

It may be we need to correct my thinking.  But the way I'm currently thinking is only low risk bug fixes get added to the Release Branches.  Anything complicated goes into the Development branch and gets fully shaken out over there.   Periodically, we may want to move a feature from the Development branch to the Release branch.  But a more likely way is when the Development branch gets promoted to Release Candidate.

If this thinking has issues, please help me get the thinking correct.

**Comment by maxabrahamsson** [comment]
Hi @Roxy-3DPrintBoard,

This is only documentation (code comment) change to warn users about already existing configuration.

So it does not effect any code functionality, but rather serves as a clarification to the users. 

It can be removed, once implementation is in place. Otherwise, as it is now, that part of configuration is creating frustration for users. 

Because changing the value, does not effect anything. The value is not used in the code. If it was planned to be used later on, at a further release. It shouldnt have been here in first place. But this warning can mitigate the problem of frustration caused to users.

**Comment by Roxy-3D** [comment]
Ah!!!!  Thank You for helping me understand.

**Pull request closed without merging**
