### PR TITLE
Fix UBL mesh editing

### PR DESCRIPTION
**Pull request by filippor**
fix move on ubl mesh edit
x_plot , y_plot can be negative when move backward (see _lcd_ubl_output_map_lcd  when step_scaler <0)

planner.quick_stop();  cause crazy moviment out of working area on my configuration

### CODE REVIEW

**Comment by filippor** [comment]
to fix crazy movment  how can I create a critical section?
void Planner::quick_stop() {

  // Remove all the queued blocks. Note that this function is NOT
  // called from the Stepper ISR, so we must consider tail as readonly!
  // that is why we set head to tail - But there is a race condition that
  // must be handled: The tail could change between the read and the assignment
  // so this must be enclosed in a critical section

**Comment by GMagician** [comment]
by disabling interrupts, some macro are still defined: `CRITICAL_SECTION_START` and `CRITICAL_SECTION_END`, these must be called before (START) and after (END) code that needs to be inside a critical section

**Comment by filippor** [comment]
I tried with critical section but i makes Marlin freeze
I removed _lcd_hard_stop and do nothing if planner.movesplanned()
i think is  safer

**Comment by GMagician** [comment]
Not sure what/why `planner.movesplanned` is used there but I think that if it's present there is for sure a reason...

~~EDIT: `movesplanned` checks if some movement may be added into queue...if error raise it means that there is no space for any other movement to be enqueued. That's not good~~

**Comment by filippor** [comment]
Before my change when planner.movesplanned calls Planner::quick_stop()  that if I understand correctly clear the buffer

Now the function return without making changes and planning move it is not ideal but it works

The current does not work for my delta printer.

**Comment by thinkyhead** [comment]
I've been looking at the menu code and whether this is the best approach. I need to install UBL on a printer and play around with the mesh editing interface, refine it until the behavior is consistent with expectations. Namely:
- Select a mesh point on the screen with the wheel
- Click to select a point and move the nozzle to it
- Allow the selection of another mesh point during the move
- If another point is clicked, queue a move to the that point too
- If you click the point already selected, go to the edit screen…
- (Editing is delayed until the mesh move completes)

**Comment by thinkyhead** [comment]
I've tried a different approach here. It uses `ui.synchronize` to prevent interaction until a move is done. See if it works for you. I'll be testing this after dinner.

**Comment by filippor** [comment]
I test this patch and when enter in mesh edit te printer restart. Ill try to find the problem

**Comment by thinkyhead** [comment]
I think that in order to use the `ui.synchronize` method the rest of the code has to be structured to go with it. At some point in future I want to standardize our native LCD API to support color DWIN / DGUS displays with encoders. The Ender 3 v2 code contains DWIN code that provides a great guide on how to draw on these displays.

Anyway, I'll clean this up and merge it, and I'll revisit again during the next LCD code scrub.

**Comment by filippor** [comment]
Now it works thanks

**Pull request merged**
