### PR TITLE
[2.0.x] Cleanup unused options

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by thinkyhead** [comment]
This change appears to be incompatible with the version of PlatformIO we use for Travis CI.

```
Warning! Ignore unknown `build_dir` option from `[platformio]` section
```

The .travis.yml file installs PlatformIO like so:
```yml
install:
  - pip install -U platformio
```

**Comment by ivankravets** [comment]
There are 3 options:

1. You can ignore this warning and it will be automatically fixed with upcoming PIO Core 3.5.1
2. Switch to PIO Core@dev via 
```
- pip install -U platformio
- platformio upgrade --dev
```
3. Wait for PIO Core 3.5.1 release and merge this PR :)

**Comment by thinkyhead** [comment]
Aha, suddenly it's working. Looks like Travis may be getting the newer core now. But it still gives us
```
There are the new updates for platforms (teensy)
Please update them via `platformio platform update` command.
```
I suppose we can add that line to Travis CI. But I wonder why it wouldn't be downloading the current one already.

**Comment by ivankravets** [comment]
> I suppose we can add that line to Travis CI.

See https://github.com/MarlinFirmware/Marlin/pull/9124

This command will revalidate cached libs and packages.

**Pull request merged**
