### PR TITLE
Distinguish between analog/digital auto fans

### PR DESCRIPTION
**Pull request by thinkyhead**
According to #13296 extruder auto fans connected to digital pins might not be getting enabled. This PR attempts to remedy the issue by only writing digital HIGH/LOW to the non-PWM pins, and only writing the 'analog' values to PWM pins.

### CODE REVIEW

**Comment by svpcom** [comment]
@thinkyhead  ``digitalWrite(pin, newFanSpeed)`` will not work with Pin 77. That's based on the Arduino mapping - not on the FastIOs.

**Comment by p3p** [comment]
As some pins will require FastIO we should probably make sure the Aduino IO functions are never used within Marlin.

**Comment by AnHardt** [comment]
The FastIO-macros (at least for the AVRs) can't handle variables. They are fast, because they have all needed information at compile time. For that, there are still a few exceptions.

**Comment by p3p** [comment]
I shouldn't talk about parts of Marlin I only have cursory knowledge of, must be the Due platform I remember the variable version of the FastIO macros from.

We should make all the pins supported in FastIO work for all features if possible, well at least for digital write, or it will be confusing having restrictions on some pins for some features.

**Comment by thinkyhead** [comment]
Ah right, `digitalWrite` depends on the pin mapping in the platform. As mentioned, we don't have a way to use the fastIO `READ` / `WRITE` macros with variables. But since in this case the variables are just a table of constants, we can simply convert that table into a (probably simpler) `switch` statement using the fastIO macros.

**Comment by thinkyhead** [comment]
> We should make all the pins supported in FastIO work for all features if possible

As long as the pin number is known at compile time we can use the fastIO macros and the so-called "Logical" pin-mapping, where as far as possible the pin number exactly identifies with a corresponding digital pin number. The pin mapping of 77 to J6 was always there, but it applies only to usage with fastIO macros. Thus, this change is necessary to adapt the auto fan code to our proper digital pin handling.

Now, the same will end up being true for `M42`, since it, too, takes a pin number as a variable argument. For platforms that need to use these extended fastIO pin mappings, `M42` will need to include a big switch statement just as I've done here (avoiding the need to build a pin mapping table for AVR like we have for some ARMs).

**Pull request merged**
