### PR TITLE
fix slow screen updates issue 24298

### PR DESCRIPTION
**Pull request by ellensp**
### Description

After commit https://github.com/MarlinFirmware/Marlin/commit/15b6159f6af740f17db2dc8815697759c714cc12 Date: Mon May 23 09:13:17 2022 +0700
LCD screen update is extremely slow when SDCARD is not inserted on powerup

This only seems to effect slots that don't have a SD_DETECT_PIN

Added an #ie block to disable the part of the commit that is causing the issue when no SD_DETECT_PIN is present

### Requirements

SDSUPPORT
sd card slot that does not use SD_DETECT_PIN
REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER (or other display that take a fair amount of cpu cycles) 

### Benefits

Works as expected

### Configurations
Example Config scan be found in the related issues 

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/24298
https://github.com/MarlinFirmware/Marlin/issues/24301
and maybe https://github.com/MarlinFirmware/Marlin/issues/24252

### CODE REVIEW

**Comment by ne0nex** [comment]
this will likely resolve my issue too: https://github.com/MarlinFirmware/Marlin/issues/24293 

I'll pull and patch mine when I'm done with my current print job.

**Comment by lipewww** [comment]
The new bugfix has this, but how can I use my sd card? I'm not able to use it

**Comment by Foxies-CSTL** [comment]
Hello,
The problem has moved to accessing files on the SD card.

I had the slow problem after flashing a new firmware (bugfix 2.0.10) with a TFT32 and TFT35 (FMSC) screen in TFT_COLOR_UI mode on a mobo Hispeedv1 and on a Nanov1.2/1.3. 
Octoprint was showing me access errors when the card was not there. After a few minutes, I put the SD card back in and the screen was back to normal and so was the access to the files. I could print.

After flash with no SD.
image

I did some tests after updating the PR24298, the screen does not freeze anymore but when accessing the media, there is nothing and when refreshing the list several times (line "refresh"), there is a reboot of the machine. I have removed the associated options like "UTF_FILENAME_SUPPORT", "SDCARD_SORT_ALPHA", "SD_REPRINT_LAST_SELECTED_FILE" but without success. Before the PR I could print via the SD card, now I can't.

Defintion_pins HiSpeed.
image

Thanks in advance.
Note: no problem with 2.0.9.3

**Comment by thisiskeithb** [comment]
@Foxies-CSTL See https://github.com/MarlinFirmware/Marlin/pull/24319

**Comment by Foxies-CSTL** [comment]
> @Foxies-CSTL See #24319

Same issue after the update to 2.0.9.4 (reboot if I leave the SD card) After reboot and reinsertion of the SD card, the reading is not done unless I leave it in place after a few minutes but it is very random.
Note: I'm going to update my repository to 2.1 and bugfix 2.1. 
Note2: Same issue with bugfix2.1 + PR24319

**Pull request merged**
