### PR TITLE
Instant Freeze/Resume Function

### PR DESCRIPTION
**Pull request by vector76**
### Description

This update adds the option for a "freeze" button which instantly halts motion without waiting for the queue to be depleted. However, unlike an emergency stop it does not clear the motion queue or disengage the motors, and releasing the freeze button allows the motion to seamlessly resume.

This function does not respect acceleration and simply halts step generation. The stepper ISR "attempts" to move but generates no steps and ends up stuck at the same location within the current block.

### Benefits

Perhaps no use for 3D printing but manual E-stop can be useful for CNC applications.
https://youtu.be/u3b3XAOUDz0

### CODE REVIEW

**Comment by thinkyhead** [comment]
Instant stop from 60mm/s to zero is going to lose steps, and instant start at that speed will also lose steps. Both can be potentially damaging to hardware. TMC driver models that have StandStill detection will go into shutdown and must be reset. It is not likely in most cases that a job could be resumed after stopping with this method.

**Comment by vector76** [comment]
Yes is true that stopping or starting at high speed will skip steps and fail to faithfully resume.

I need to learn more about TMC StandStill detection to speak to that.

This is intended for sudden unplanned stops that must stop immediately, i.e. emergency stops.  If a stop is planned, then M00 is much better.  If it need not stop immediately, (and if not playing from SD card) then the gcode sender can implement pause and it will stop when the queue is depleted.

Sometimes a CNC machine needs an immediate emergency stop and de-energizing steppers could allow the spindle to drop.  The spindle doesn't tend to stop instantly when the power is cut and dropping the spindle could be bad.  It is possible for M112 to jump the queue, but it is a full shutdown.  There is currently no way I know of to stop motion instantly and keep the motors energized.

Another scenario is if mid-job you observe there is say a clamp in the way or something.  It is worth taking a chance that freeze/resume might lose steps if the alternative is reaching into the tool path and trying to remove the clamp before the spindle reaches it.

**Comment by AnHardt** [comment]
It seems to be possible to make [deaccelerated fast stops](https://github.com/AnHardt/Marlin/issues/87) work. But it's a huge task.

**Comment by vector76** [comment]
Another possibility that is perhaps less of a monster would be if there were some instantaneous feedrate adjustment.  This would be somewhat like M220 but applies instantaneously including what's already in the planner, not just for new blocks.  The implementation would need to be closer to the ISR level instead of applying the factor to movements before they go into the planner.  I have not looked at it but such a function seems plausible.  A feedrate adjustment mechanism that just dilates time would not respect the same acceleration limits, but if the feedrate is only ever decreased it should be safe.  And the feedrate adjustment must not change by large sudden amounts too.

Then decelerated stops could be implemented by taking advantage of this instantaneous feedrate adjustment, scheduling a feedrate adjustment ramp down to zero to stop and to restart, ramp back up to 100%.

Such a feature is still more than I am prepared to take on, but it seems plausible.

**Comment by GMagician** [comment]
As written in #19253 usually industrial machines have a stop/hold function, but it's a ramped stop (and it continues to interpolate during ramp down). It should look like slowing down feedrate down to 0 using current acceleration slope down

**Comment by fedetony** [comment]
please see my solution under #19253

**Comment by vector76** [comment]
@fedetony Interesting.  I was not aware of stepper.suspend() or the underlying DISABLE_STEPPER_DRIVER_INTERRUPT() so that is interesting and perhaps (probably) better my approach of quitting early from pulse_phase_isr().

It seems it would still suffer from the instantaneous halt that does not respect acceleration.

I too wish there were a means to get the current actual position instead of the queued position, which it looks like you have attempted.  I am in support of that feature, although tbh I haven't looked at that part of your implementation.

**Comment by fedetony** [comment]
@vector76 To my knowledge the position is correct. The function I wrote uses the stepper count values, and recalculates the position not changing/rewriting the global variables (`current_position`). They could be used as Raw, but the positions are altered with offsets and leveling which are applied to the stepper counts when recalculated with the `.aslogical()`. So in the end what my function is doing is reading the stepper count , recalculating and printing to the serial. The function is called actively in the `keep_alive` function busy state, and I've altered the timing for it to be reported more often by adding a divider to the time interrupt.

Respect to the pause, yes in my implementation is instant, and you may loose steps if your movement is too fast and your machine has inertia. There is a possibility to trigger the desceleration t1/t2 of the stepper, yet maybe you need to restate the buffer after. Basically is to trigger a deceleration before the `stepper.suspend()` in the process here:
```
/**
 * Timer calculations informed by the 'RepRap cartesian firmware' by Zack Smith
 * and Philipp Tiefenbacher.
 */

/**
 *         __________________________
 *        /|                        |\     _________________         ^
 *       / |                        | \   /|               |\        |
 *      /  |                        |  \ / |               | \       s
 *     /   |                        |   |  |               |  \      p
 *    /    |                        |   |  |               |   \     e
 *   +-----+------------------------+---+--+---------------+----+    e
 *   |               BLOCK 1            |      BLOCK 2          |    d
 *
 *                           time ----->
 *
 *  The trapezoid is the shape the speed curve over time. It starts at block->initial_rate, accelerates
 *  first block->accelerate_until step_events_completed, then keeps going at constant speed until
 *  step_events_completed reaches block->decelerate_after after which it decelerates until the trapezoid generator is reset.
 *  The slope of acceleration is calculated using v = u + at where t is the accumulated timer values of the steps so far.
 */
```
the `decelerate_after` variable uses the counter of the stepper to decelarate. You need to calculate how in many steps you need to stop with respect to your current speed. Pass the instant step value and wait until the count reaches the calculated value to call `stepper.suspend()`.

Hope it helps :)

**Comment by mron** [comment]
I was working on this a few months ago. I was able to get a rapid ramp down working. The system ramped down using the max accel value for each axis. I focused on CNC, so no extruders. What stopped me was the planner. I couldn't figure put how to insert a new destination from the stopped/current point and plan new moves from there. I'm going to try again if no one has done this.

**Comment by mron** [comment]
I notice in the HAL section there is a LINUX setup. What is this for?

**Comment by ellensp** [comment]
> I notice in the HAL section there is a LINUX setup. What is this for?

You can build marlin for linux...  no IO, not very useful but
is also used in the experimental simulator https://github.com/p3p/Marlin/tree/pr_linux_cleanup which is good for debugging non hardware specific code. Join the Marlin Discord to learn more.

**Comment by mron** [comment]
Thanks! I’ve downloaded it. I’m not familiar with Discord. I’ll head there now.

**Pull request merged**
