### PR TITLE
Add support for MKS Robin E3 and E3D to Marlin2.x.x

### PR DESCRIPTION
**Pull request by mks-viva**
### Requirements
Add support for MKS Robin E3 / E3D board to Marlin2.x.x.

### Description
- MKS Robin E3 and E3D use STM32F103RCT6
- MKS Robin E3 is integrated TMC2209 UART mode.
- MKS Robin E3D is replaceable drive interface.

### Benefits
Users can easily use the latest Marlin firmware on this motherboard

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by thinkyhead** [comment]
I've rebased this onto `bugfix-2.0.x` so it can be merged. After this has been merged you may want to repair your `2.0.x` working copy. To do this you will need to open the Git Console and use the following commands:
```
git fetch upstream
git checkout 2.0.x
git reset --hard upstream/2.0.x
git push -f
```

**Comment by thinkyhead** [comment]
Overall, looks good! I'll merge it shortly….

**Comment by mks-viva** [comment]
OK, thanks for your tips, I will pay attention to this detail

**Pull request merged**
