### PR TITLE
ststm32 update from 10.0 to 11.0

### PR DESCRIPTION
**Pull request by jbuck2005**
### Description

platformio has updated their ststm32 environment from 10.0 to 11.0
this change leverages the update

### Requirements

applies to STM32 boards

### Benefits

Allows the user of the most current pio environment

### CODE REVIEW

**Comment by X-Ryl669** [comment]
Did you check it does not break any feature on your printer? What is your printer board ?

**Comment by jbuck2005** [comment]
> 
> 
> Did you check it does not break any feature on your printer? What is your printer board ?

Absolutely!!

I only discovered this change because I went to compile my latest firmware and was surprised to see platformio use version 10 of the STM environment despite my having updated it to 11.0 minutes earlier.

I can say with certainty that this worked for my firmware build. Did not break a thing. Creality Ender 3 with 4.2.2 board.

**Comment by jbuck2005** [comment]
This was tested and works for Creality Ender 3 with 4.2.2 board.
Anyone else in the STM build environment care to test this? [I sincerely do not expect any issues]

**Comment by tpruvot** [comment]
dont change the F1 default, they removed maple framework support in 11.0... only STM32 env so...

but some F1 boards can use the STM32 env too, just not the STM32F1 env which is maple one

**Comment by rhapsodyv** [comment]
> dont change the F1 default, they removed maple framework support in 11.0... only STM32 env so...
> 
> but some F1 boards can use the STM32 env too, just not the F1 which is maple one

If maple were removed on 11.0, soon we will have a problem....

**Comment by tpruvot** [comment]
no... STM32 env is there for the 11.0+ STM32F1 env is... "legacy"

**Comment by rhapsodyv** [comment]
> no... STM32 env is there for the 11.0+

I know. I'm just predicting future issues for maple incompatible or not being downloaded by PIO anymore.... :-(

**Comment by tpruvot** [comment]
no... pio component version is made for that. Its why it should not be changed here (for the common F1)

**Comment by X-Ryl669** [comment]
We don't want to be shy here. It's just that there is a WIP for removing the STM32F1 HAL using libmaple to use common STM32 HAL instead. Updating stm32 version will happen later.

**Comment by X-Ryl669** [comment]
Seems like it's not that simple see #20982. ststm32 does not define F_CPU as a constant, so it breaks waiting of small delay.
I've opened #21051 for this issue. I don't know what will break next.

**Pull request merged**
