### PR TITLE
Updated BIQU SKR V1.1 pins file, with TMC2130 configuration options

### PR DESCRIPTION
**Pull request by gloomyandy**
Removed references to the ReARM, deleted displays that have not been tested. Added TMC2130 configuration options. Cleanup spacing etc.

### Description
Removed references to the ReARM, deleted displays that have not been tested. Added TMC2130 configuration options. Cleanup spacing etc.

### Benefits

New file has tested display configuration and various tested configuration options for support of TMC2130 drivers.

### Related Issues
This file is the result of discussions and tests found in this issue:
https://github.com/MarlinFirmware/Marlin/issues/12632

### CODE REVIEW

**Comment by jmdearras** [comment]
MKS-MINI-12864 works with a couple of PCB jumpers and pin changes.

**Comment by jmdearras** [comment]
This removed MKS_Mini_12864 functionality.  :(

**Comment by gloomyandy** [comment]
@jmdearras What MKS_Mini_12864 functionality are you referring to? As far as I can tell no verified pin settings for that display were ever committed to the main Marlin repository. Can you provide the details of a working solution?

**Comment by jmdearras** [comment]
added:
```cpp
//
// MKS MINI12864 with graphic controller and SD support
// http://reprap.org/wiki/MKS_MINI_12864
//
#define MKS_MINI_12864
#if ENABLED(MKS_MINI_12864)
  #if (MOTHERBOARD == BOARD_BIQU_SKR_V1_1)
    #define DOGLCD_CS          P2_06 //P0_26   // (63) J5-3 & AUX-2
    #define DOGLCD_A0          P0_16 //P2_06   // (59) J3-8 & AUX-2
  #endif
#endif
```
to my `config.h` file, takes care of it.  It does require 2 jumpers on the PCB, but works fine.

**Comment by jmdearras** [comment]
image

**Comment by jmdearras** [comment]
Also, the pins file has to be set for lcd sd card.  I am not suggesting adding this to the project, v1.2 is being released soon to address these and other issues. But just FYI, this display can be made to work well.

**Comment by gloomyandy** [comment]
@jmdearras do you only need to set the lcd sd card if you want to use the SD card built into the LCD or are you saying that the display etc. does not work if you do not set that?

**Comment by jmdearras** [comment]
it does not work unless you set that.  I did not research why, it's the way I want it, anyway.

**Pull request merged**
