### PR TITLE
ReprapWorld Ultratronics Pro 1.0 Support

### PR DESCRIPTION
**Pull request by thinkyhead**
As requested in #5016
- Add board define `BOARD_ULTRATRONICS`
- Add pins file `pins_ULTRATRONICS.h`

Marlin still only supports a single thermocouple.

### CODE REVIEW

**Comment by ghost** [comment]
Well, [Ultratronics](https://reprapworld.com/products/electronics/ultratronics/ultratronics_pro_v1_0/) is **32-bit Atmega SAM3X8E** board (Arduino Due compatible)...

**Comment by thinkyhead** [comment]
Ah, of course. The requester pointed me to the MK4Due branch but I missed it.
So… this will have to wait until 1.2.x I guess!

**Comment by thinkyhead** [comment]
@esenapaj @bobc Should we include this board in the 32-bit pile?

And, should we give a new range of numbers to 32-bit board in the `boards.h` file? Maybe number them starting from 1000, or something like that, as a clue that they are different?

**Comment by bobc** [comment]
Sure, we can add Ultratronics to 32-bit-BugFix. I have adopted 32 bit board numbering from @esenapaj which has 32bit board numbers starting at 1411.

**Comment by thinkyhead** [comment]
1411? That's an interesting choice.

**Comment by ghost** [comment]
>Should we include this board in the 32-bit pile?

Yes of course, but this board has quad thermocouple (MAX31855) and LAN port that it's function not found in official Marlin at present,
and there seems to be some confusion in the information provided by the board maker and the actual pin connection,
https://github.com/MagoKimbra/MK4duo/commit/790460808d44261837e26713edff9852a2b00964#commitcomment-19952757
https://github.com/MagoKimbra/MK4duo/pull/14

and needs something of special initialization,
https://github.com/MagoKimbra/MK4duo/pull/12

therefore I was thinking about supporting this board carefully without hurry.
(I planned that at least I support this board after implementation of [multi-thermocouple](https://github.com/MarlinFirmware/Marlin/issues/5046#issuecomment-257153841) successfully, but it's temporarily stopped because [I brew up it](https://github.com/MarlinFirmware/Marlin/issues/5046#issuecomment-261924469)).

>should we give a new range of numbers to 32-bit board in the `boards.h` file?

I'll leave it to development team of Marlin.
I gave the 1000th generation to the board of the due system because I simply wanted to put those boards together.
You can change the number attachment any number of later, because there is no change from the user's point of view.
It may be divided for each architecture, or it may be alphabetically sorted.

**Comment by ghost** [comment]
>1411? That's an interesting choice.

It has no particular meaning.
When I received a support request from the [DUE3DOM](http://fabrykator.pl/seasidecustoms/due3dom-elektronika-32bit-dla-drukarek-3d/) user group, I simply added 1000 to the board number they presented.
https://github.com/esenapaj/Marlin/issues/146

**Comment by thinkyhead** [comment]
> seems to be some confusion in the information provided by the board maker and the actual pin connection

Sounds like a great use case for `M43`. 😄

**Comment by thinkyhead** [comment]
> I simply added 1000 to the board number they presented.

Makes sense. With this board, I took 705 (the next RepRapWorld ID in sequence) and added 1000 to it.

**Pull request closed without merging**
