### PR TITLE
Followups for I2C_POSITION_ENCODERS

### PR DESCRIPTION
**Pull request by thinkyhead**
- Changes for `I2C_POSITION_ENCODERS` by @bgort
  - Make the class a static singleton
  - Apply coding standards
  - Apply `const` to all invariant vars
  - Replace `M864 N` with `M864 S`
  - Use `int8_t` for `idx` arguments for cleaner code

View the [Concise Diff](7007/files?w=1) to hide white-space changes.

### CODE REVIEW

**Comment by bgort** [comment]
Yeah, now I better understand the frustration I've seen from others.  I'm in the middle of making changes myself and you just stomped on what I'm doing and wasted my time.

Also, I2CPositionEncoder can't be static, as there are multiple instances.

I think I'll allocate my time elsewhere for a while.

**Comment by thinkyhead** [comment]
I haven't committed anything yet…

**Comment by bgort** [comment]
Irrelevant.  I'm not interested in having you dictate how things will be, changing everything to suit yourself, etc.

Surely there are things that can be improved on in my PR - I'm aware of most of them - but just going around making wholesale changes to things you aren't using, can't use, have hardly looked at, etc. because you feel like it isn't right.

I've seen Roxy say the same thing, so don't think this is just me being unreasonable.  

If this is how you're going to do things, I'll spend my valuable time elsewhere.

**Comment by bgort** [comment]
Also - and I don't intend for this to seem/feel punitive - I should add that it seems like more often than not, you break things when you do this.  Others then have to go around behind you cleaning up the mess you made, because you apparently can't be bothered to test after gutting things.  A few things yesterday were broken.  Assuming you merge this, you just broke I2CPositionEncoder because you assumed there was only one instance and that it could be static, etc.  I've spent 4-5 hours fixing things you've broken - things that could have not been broken had you bothered to test even once.

I don't like wasting my time anymore than anyone else does.

**Comment by thinkyhead** [comment]
> Assuming you merge this,

Best not to assume….

Like it or not, I'm the gatekeeper. The changes I'm making are quite straightforward. Understand, once you put code into this repository it's not yours anymore.

> I've spent 4-5 hours fixing things you've broken

Multiply the frustration you feel as a single contributor by 100 and you may begin to understand mine as a gatekeeper, fixing everyone's stuff all day. Of course, you feel what you feel, and that's all you would be aware of, understandably.

**Comment by bgort** [comment]
Okay - good luck with your project, then.

**Comment by thinkyhead** [comment]
Cheers. Thanks for your contributions. You will be missed.

**Comment by thinkyhead** [comment]
I'd respond to your criticism (some valid, some overwrought) in more detail, but I have a lot to do today. My apologies for occasionally breaking things. Lately the rate of change has been far higher and harder to keep up with, and I have made more careless errors than I usually would. I'd say that I make about a tenth as many errors as I actually fix, so it all comes out in the wash. I have great faith that my mistakes will be quickly caught. Anyway, I have about 500 unread issues to read through, so it's a good thing I have more patience than the average bear. I've fled from the project once already, but am determined to stick it out even though I'm the natural magnet for everyone's annoyance.

**Comment by Roxy-3D** [comment]
@bgort   Please don't leave.     There is a simple answer that will help a lot.    

Let's all just agree we do this:

If code is checked in from somebody that is careful and tests their stuff...   Just leave it be for a week or two.   Let it age for a week or two.   The person that checked it in is still working on it.    And even though everybody has different coding preferences, it doesn't matter if this debugged and tested code has some extra white space in it.   It doesn't matter if it doesn't have a const qualifier on something.   

Just leave it be so the person that is working on that section of the code base doesn't have everything scrambled.    

Just doing that would help the other developers a **_HUGE_** amount.   And it hurts nobody.

**Comment by thinkyhead** [comment]
The **I2CPositionEncoder** change was merged too soon, and that seems to the main source of @bgort's frustration. Because, like it or not, once something is merged, I will immediately pounce on it to fix all existing issues. Had it been held longer, I would have pounced on those issues while it was still in development. It would have been a good chance to educate @bgort on some of our coding standards, the benefit of singletons, and so on....

As for me, you have seen that I do hold off any of my **_major_** PRs for weeks until they are reviewed, assign reviewers, assign labels, and discuss things in detail with developers to help them along. However, we don't always have enough reviewers around with all the relevant equipment, so eventually things get merged with the aim of getting them more widely tested. This stuff we try to relegate to bugfix only….

I'm sorry that @bgort sees me in my privileged position as a hypocrite. Regardless of my caution or carelessness, I will probably always have to deal with more complaints every day simply because I apply 10 times as many changes as anyone else does.

**Comment by Roxy-3D** [comment]
> As for me, you have seen that I do hold off any of my major PRs for weeks until they are reviewed, assign reviewers, assign labels, and discuss things in detail with developers to help them along. However, we don't always have enough reviewers around with all the relevant equipment, 

Yes.  That is how it should be.    And you can do that because nobody else is making millions of changes everywhere else in the code base.   But we can't do that because letting any piece of code sit for more than a few hours will cause it to pick up conflicts.

Also...  It is a fact my Git skills are not good enough to recover from a conflict.  I have to start all over.  Conflicts don't scare the more experienced Git users.   But they are a dead end for me.  I have to start all over.

**Comment by thinkyhead** [comment]
Merge/rebase conflicts are a fact of life. A version control system is no substitute for coordination and communication.

As noted, I have not merged anything yet. If @bgort has additional changes to supply, he can simply tell me so. I would respond by waiting for him to submit his new PR with changes, then I would submit my changes to his PR by way of its base branch.

I understand why he fears I'll merge these changes quickly — because I'm damn fast — but if he catches me in time there's nothing to worry about.

My general assumption is that when someone merges something, they must believe it's finished, and therefore it's fair game to start fixing it. If they want to keep refining without any interference, that's what their personal forks and still-open PRs are for.

**Comment by bgort** [comment]
> I'd respond to your criticism (some valid, some overwrought) in more detail, but I have a lot to do today. 

Fair enough - I have things to do today too, and I'm already well over my 'Marlin allocation' - but I would like to point out that the only thing I've said that I intended as actual criticism is that you break things because you can't be bothered to test (or sometimes even hit the 'Compile' button) before merging.  That's just ridiculous and disrespectful in a project like this, where you have so many users using, and other developers that are actively working against, the same branch.

The rest is just how I feel about what's going on, and that I don't care for feeling like this is -your- project and not others'.  I now acutely feel Roxy's 'pain' from a few weeks ago when she was upset over changes you'd made to her code; at the time I only vaguely got it - now I feel it.  (Sorry to use you as an example, Roxy.)

> and you may begin to understand mine as a gatekeeper

Has someone declared you the gatekeeper, or is that just a role you've assigned to yourself?  Serious question.  Just want to understand.  Obviously you do -a lot- of work on the project - no one could or would, I hope, try to take that away from you - but does that make you 'in charge' ?

> The I2CPositionEncoder change was merged too soon, and that seems to the main source of @bgort's frustration.

No, that isn't the source of my frustration at all, and that's a ridiculous suggestion.  First, I don't think it's been merged too early.  Second, as any school child can see, my problem is with -your- changes and how you've handled that -you- think it was merged too soon.  Nothing else.

>Understand, once you put code into this repository it's not yours anymore.

To be clear, I don't expect that I'll 'own' the code I produce or that it won't ever be changed (nor have I ever felt that way).

> I'm sorry that @bgort sees me in my privileged position as a hypocrite. Regardless of my caution or carelessness, ...

Did I call you a hypocrite?  I do think that in some ways you are, but my issue here is that you feel it's okay to behave the way that you are, to gut someone's work in progress and waste their time, etc., all because you don't like something, even though there's virtually no chance that what you're changing/doing matters to anyone except the developer and (hopefully) a small number of testers (as in this case).  It's just a matter of being respectful of others' time, their contributions, etc.

To be clear, I wouldn't care a bit if you came back a month later and changed a bunch of things around to your liking, as long as you don't break them.

No insult intended, but I suspect managing creative people and processes outside of yourself isn't something you have a whole lot of experience with.

> I understand why he fears I'll make these changes quickly — because I'm damn fast

This must be some kind of joke or tongue-in-cheek remark.  Otherwise it's absurd.

-------

> @bgort Please don't leave. There is a simple answer that will help a lot.  Let's all just agree we do this: ...

That's all fine with me, Roxy.  I don't go around changing everyone's code while they're in the middle of working on it, and wouldn't, because I consider doing something like that disrespectful.

However, I think there are a number of bigger issues that need to be sorted out.  The biggest of which is that @thinkyhead considers this his project, not a group project.  To be clear, I think it's a great project .. and if it's his, so be it - great job, @thinkhead - but I can't spend my time on something if I'm not an actual part of it, and if someone is going to come along and criticize my contributions, gut them, etc. while I'm still working on them, that doesn't work for me.  Generally, I'm not interested in feeling like I'm working -for- someone on their project, or even working on someone else's project.

Another issue is that - and I don't know if you read my comments in the other thread - but I suspect/believe @thinkyhead wants to turn 'Marlin' or 'Marlin-related' into a job/living (and already is to some extent), and that's not something I'm comfortable supporting with my time/efforts/energies.  It's fine to make money using an open source project as a part of your business, but to me, to control a project like this in the way he is and then also make money off of the contributions of others rankles.  This can be cleared up easily, and if I'm wrong I'm wrong, of course - I will absolutely admit that, and will even apologize in advance if any offense is taken (even though it isn't intended) - but that's how it feels/I feel right now.  I think I think this mainly because I don't have another explanation for the territoriality and other behaviors I'm seeing at the moment.

Anyway...  I do have -a lot- to do today, so please don't take any further lack of response from me as concordance/acceptance, or as anything other than that I'm busy and haven't had time..

**Comment by thinkyhead** [comment]
@bgort It sounds like you want to get into a political debate, but I would really much rather just deal with the technical issues of the project and continue to refine those processes. That will go a longer way towards solving the issues you are concerned about without getting into all this other mess.

As for how I ended up in this position, it comes down to a long discussion that I had with Erik van der Zalm when I was making noise about leaving the project. Plus, no one else wants the job.

**Comment by oysteinkrog** [comment]
@bgort as a pretty impartial outsider here I would like to say that I understand that your frustration, but I kind of agree with thinkyhead in that once something is merged, it should be ok for other people to clean it up or improve it, and especially if it goes through the PR process.

I don't think thinkyhead has a higher breakage percentage than anyone else, it's just that he does a lot of work on the project.

Thinkyhead is doing an amazing job at ensuring the overall code quality of the project is kept to a high standard, and that is truly a thankless job.

Maybe it is a good idea to create some rules for the project to make everyone aware of (if not in agreement) how things work, or should work?

**Comment by Roxy-3D** [comment]
>>> @bgort Please don't leave. There is a simple answer that will help a lot. Let's all just agree we do this: ...

>> That's all fine with me, Roxy. I don't go around changing everyone's code while they're in the middle of working on it, and wouldn't, because I consider doing something like that disrespectful.

> It sounds like you want to get into a political debate, but I would really much rather just deal with the technical issues of the project and continue to refine those processes. 

This is **_VERY_** technical and not political.   This is at the core of how technical people want to work in collaborative projects.  It is very disruptive to have millions of surface level changes made while the author is trying to hold the entire piece of code in their head so they can work on it and improve it.  All of those surface level changes (white space...  const qualifiers...  ternary operators...  name changes...   type changes (from int16_t to int8_t) etc...  can be done later.   AFTER everything has settled down and baked for a while.

This one change won't address all of bgort's issues.  But it would make a serious dent in them.

**Comment by bgort** [comment]
> It sounds like you want to get into a political debate, ...

Nothing I said was meant to be political in the slightest, but maybe you'd rather deflect or avoid what I said by mislabeling/mischaracterizing, rather than actually address any of it?  If it's just that you're too busy, I certainly understand.  But otherwise....

Generally, just to clarify, the reason I said something here is because what you're doing (generally) is, in my view, unnecessary, disrespectful, and wrong.  And it's not just me who feels this way; I've seen it done to others who have said nothing, and I've seen it done to others who have been pretty upset.  It's not like this is a one-off.  You would do much better if you were to, as they say, 'cool it' some.

All of that aside, I do think that the issues I raised (the ones I believe you prefer to categorize as 'political') are real ones, and that other developers deserve to be informed of your intentions/goals for the project, that you consider it 'yours', what your standards are, etc.  

In my view, it's only fair that everyone know these things prior to spending their time on your project.  Ownership, rules, etc. might not matter to someone just using the code, spending 5 minutes improving a small feature, etc., but it does matter to those of us spending money (I just bought position encoders, I'm in the process of buying a $1k laser triangulation sensor to integrate partly because I want it, and because I thought it would be cool and helpful to the community) and sometimes-massive amounts of time making things better.  If you can't or won't clarify that this isn't -your- project, that you'll stop stepping on others, etc., I'll just leave you to implement things the way you want, ensure everything is to your standards at all times (even before things are finished), etc.  I know my contributions have been small relative to yours, thus far, and so I'm sure it doesn't hurt much if I go off on my way.

I guess one final thought:  I might have thought differently about spending my time on your project had things been clearer to me from the beginning.  I'm sure you're not trying to mislead anyone, and it's probably my fault for not asking, but a simple statement - maybe in the README.md - like 'This open-source project belongs to @thinkyhead, and any changes must meet his standards, which are not clearly defined and may change from time-to-time.  This isn't a true open-source collaboration, but a development effort led by him, with labor freely contributed by others.', or something like that, would probably help people recognize how things are, so they can make an informed decision about whether to participate.  Call that unsolicited advice, or whatever, I guess.

-----

>@bgort as a pretty impartial outsider here I would like to say that I understand that your frustration, but I kind of agree with thinkyhead in that once something is merged, it should be ok for other people to clean it up or improve it, and especially if it goes through the PR process.

Thank you for taking the time to share your feelings.  I actually agree with that, generally.  Things that are contributed are and should be 'fair game'.  In this case, the problem isn't so much that what I contributed was changed -- it needed to be changed and still needs to be changed, well beyond what @thinkyhead did -- it was why it was done, how it was done, the timing of it, and how those things are related to the bigger issues that I outlined above (which have seemingly been dismissed as 'political').  Others have felt similarly in similar circumstances (this happens semi-regularly, from what I can tell), and because there's no good reason for it now or then, it's not something I can understand or accept.  My time is valuable and I just don't have it to spare if my work is going to be 'pounced' on, torn apart, and in this case broken, before I can even really finish it.  Maybe I shouldn't have merged as soon as I did, but I felt/feel it was 'good enough' for initial inclusion, I wanted to make it easier for others to test and contribute, thinky had already commented on it a handful of times and there was no communication that he wanted to wait, etc.  I've already said most of this, so will stop repeating myself.

> Thinkyhead is doing an amazing job at ensuring the overall code quality of the project is kept to a high standard, and that is truly a thankless job.

I further agree that @thinkyhead has done a great job, overall.  He's just missing some critical project management and leadership skills, I think.  Hopefully he considers this a learning moment, rather than just 'griping to be dismissed.' (And I mean that in the same way that he meant I needed to be educated on the 'Marlin way', with due respect, I'm sure.)

> Maybe it is a good idea to create some rules for the project to make everyone aware of (if not in agreement) how things work, or should work?

I think rules would be a great idea for the organization, and I certainly would have agreed to whatever made sense.  In fact, I suggested that we needed rules and more structure on a few occasions, myself, including that all significant PRs should be reviewed/signed off on by someone else prior to merge.

Anyway, unless changes are going to be made (which doesn't seem likely), I do feel it's best I move on, as this isn't going to be a good creative outlet for me (for the reasons I gave above, earlier in the day, and others).  I'll probably end up just forking and working on my own little 3D-printing-related projects on my own terms.  I do wish everyone the best of luck and such, of course, and I apologize if I offended anywhere.  Has been fun!

**Comment by bgort** [comment]
A few final comments:

>This is VERY technical and not political. This is at the core of how technical people want to work in collaborative projects. It is very disruptive to have millions of surface level changes made while the author is trying to hold the entire piece of code in their head so they can work on it and improve it. All of those surface level changes (white space... const qualifiers... ternary operators... name changes... type changes (from int16_t to int8_t) etc... can be done later. AFTER everything has settled down and baked for a while.

Agreed entirely.  Looking through the 'improvements' in this PR, there's virtually nothing functionally meaningful about any of them; I guess they just look prettier?  Except, I guess there was the breaking change of making the encoder class static (before it was unbroken in response to my complaining) ..

To be clear, I would have made most if not all of these 'style' changes myself when I was -actually- finished with everything, because even though I don't personally care for Marlin/thinkyhead-style, I try to adhere to it for the sake of consistency.

> This one change won't address all of bgort's issues. But it would make a serious dent in them.

No, it won't, but it would absolutely help.  Though, really, it shouldn't be necessary -- it's common sense that you don't mess with someone's work when it's clear they're still in the middle of it (which I did make clear in the PR, several times).  About the only reasonable exception I can think of is that there are some exigent circumstances, like the work broke something else, or there was some major issue, which /wasn't/ the case here...

**Comment by thinkyhead** [comment]
There are a dozen or more topics being discussed. Let me see if I can take them a little at a time…

> I don't personally care for Marlin/thinkyhead-style, I try to adhere to it for the sake of consistency

All things are up for discussion. Don't keep presuming everything that came before you is written in stone. If you have reforms that you want to institute, we have pages on the website specifically for coding standards and for contribution guidelines that you are free to join in on refining. The coding standards are largely based on the dominant coding style as it existed before the coding standards were drawn up.

**Comment by thinkyhead** [comment]
> Looking through the 'improvements' in this PR, there's virtually nothing functionally meaningful about any of them

I know that! And it still isn't f*cking merged yet.

> I guess they just look prettier?

Yeah. That's all. Just prettier. It's all just a lot of blegh that I do to annoy you.

How about just asking me about specific changes that have you scratching your head, instead of taking an insulting tone and assuming they're all just masturbation?

**Comment by thinkyhead** [comment]
> the problem isn't so much that what I contributed was changed -- it needed to be changed and still needs to be changed, well beyond what @thinkyhead did -- it was why it was done, how it was done,

**HOW it was done** was I made a PR and put your name in it so you'd see it, and as I keep mentioning, it still hasn't been merged yet, so what is your beef with **HOW it was done**?

**Comment by thinkyhead** [comment]
> Maybe it is a good idea to create some rules for the project

I am working on those pages on the website and trying to expand them based on recent discussions. They are open for anyone to contribute. Please offer your suggestions in the [MarlinDocumentation](https://github.com/MarlinFirmware/MarlinDocumentation/issues) project issue queue.

**Comment by thinkyhead** [comment]
> it seems like more often than not, you break things when you do this

It seems like in this instance I put your name on the PR and put up these changes for you to offer feedback, and you offered a correction and I made that correction.

Please give this a careful review when you have time to make sure I haven't broken anything.

**Comment by thinkyhead** [comment]
> it's common sense that you don't mess with someone's work when it's clear they're still in the middle of it

Still haven't merged the PR.

I made it specifically for your benefit, as an "Exhibit A," because it's usually quicker than trying to itemize every needed change. I hoped and expected there would be discussion about the merits (or non-merits) of this exhibit.

**Comment by thinkyhead** [comment]
I have spliced the unrelated changes into another PR, so this is now more clean — only related to the new I2c encoder class. Please apply comments about the code in the Files view, and I will try to justify the changes I have suggested here.

**Comment by thinkyhead** [comment]
> He's just missing some critical project management and leadership skills, I think.

I'm not the "project manager," but let's pretend for a moment that I am, and I'll tell you what's up.

Right now, I very much want to **_halt new development_** and focus on
- fixing bugs
- getting everything up to standard, and
- polishing the existing code.

I want to see some proper APIs developed for high-level motion, for the LCD, and so on. I am champing at the bit to migrate Marlin to a proper file hierarchy and start integrating the HAL.

Now, for the most part these tasks will have to be done by me and me alone, because, for one, I've already done a file reorganization and can accomplish it pretty quickly. And, generally speaking, no one else has a complete enough high level view of the whole codebase to undertake these tasks.

So, if there is anything that I would want to dictate right now, it would be: Everyone just stop with the new additions now and join me in cleanup, bug fixing, and in managing the pile of PRs that we already have, and which need to be refreshed. Help me write documentation!

If we can just get the project to HALT for a little while, I would very much like to get that 1.2 hierarchical file organization done and published as Marlin 1.2.0 as soon as possible.

So who's with me? Join me on [Google Hangouts](https://hangouts.google.com/) and let's discuss!

**Comment by Roxy-3D** [comment]
> So, if there is anything that I would want to dictate right now, it would be: Everyone just stop with the new additions now and join me in cleanup, bug fixing, and in managing the pile of PRs that we already have, and which need to be refreshed.

> If we can just get the project to HALT for a little while, I would very much like to get that 1.2 hierarchical file organization done and published as Marlin 1.2.0 as soon as possible.

We can do that.   Let's give people a little bit of time to finish up what ever is out standing.   A few more days to work through what ever needs to be tweaked so it can be merged in.   And then we freeze for a week.   Something like:

- Please finish up anything currently in flight and submit a PR by next Friday.
- If there are problems, the author gets notification and has a few more days to clean things up.  Say June 20th.
- During the period of "No more new PR's" until the freeze, it would be wise to really, truely operate in the 'Bug Fix Only!!!' mode.  NO CHANGES UNLESS they are simple and clearly fix a bug.
-  A few days after that everything is locked down until the new folder and file layout comes out the other end of the pipeline.   We might say we expect to see that in 5 or 6 days, but budget 2 weeks.

**Comment by thinkyhead** [comment]
> freeze for a week

I only wish we had some way to broadcast it, like making the project pages turn yellow or something!

**Comment by Roxy-3D** [comment]
We can put it at the top of the Readme.md file.  And we can make an active issue (and Pull Request) that clearly spells out the expected time line and where things are at the moment.   If the issue and Pull Request got updated daily with the current status, it would stay at the top and people would see it.

And part of the thinking on saying 
- During the period of "No more new PR's" until the freeze, it would be wise to really, truly operate in the 'Bug Fix Only!!!' mode. NO CHANGES UNLESS they are simple and clearly fix a bug.

Is this guarantees people have something pretty solid and stable to use while they wait for something to appear at the other end of the pipe line.

**Comment by bgort** [comment]
> All things are up for discussion. Don't keep presuming everything that came before you is written in stone. If you have reforms that you want to institute, we have pages on the website specifically for coding standards and for contribution guidelines that you are free to join in on refining. The coding standards are largely based on the dominant coding style as it existed before the coding standards were drawn up.

No one would reasonably assume they could change the coding style that you go around enforcing on everyone.  And I wasn't complaining about the style so much as just making the point that others care about consistency, too.  It's not just you.  If I didn't apply all of the coding standards, it's for a reason -- in this case it's that I wasn't.  done.

>> Looking through the 'improvements' in this PR, there's virtually nothing functionally meaningful about any of them

>I know that! And it still isn't f*cking merged yet.

The whole point is that there's no need to make functionally meaningless changes when it screws up  others' WIP.  I had a bunch of pending changes, including the things you had requested, that conflict with your entirely-unnecessary PR.  I'm not into going around resolving conflicts, dealing with this kind of crap, etc. when it's not necessary.

>>I guess they just look prettier?

>Yeah. That's all. Just prettier. It's all just a lot of blegh that I do to annoy you.  How about just asking me about specific changes that have you scratching your head, instead of taking an insulting tone and assuming they're all just masturbation?

I don't need you to explain any of your (admittedly) ENTIRELY-UNNECESSARY-AT-THIS-TIME changes to me, but thanks.  I know what they all are and would have made most of them myself eventually.  Actually, your tone here is insulting.  You're suggesting I don't know what they are or why they were made?  You must think very highly of yourself, and that others are stupid.

Anyway, as I've /already said/ - the changes you made were clearly necessary at some point to maintain style consistency, but that you're making them now against what's clearly work-in-progress in what appears to be some fit of 'that's-not-how-i-want-it' is pretty damn annoying, generally, and especially when it's made clear others are working on the same things.

> HOW it was done was I made a PR and put your name in it so you'd see it, and as I keep mentioning, it still hasn't been merged yet, so what is your beef with HOW it was done?

How it was done?  You went around changing how-many? lines in ways that didn't actually accomplish anything virtually immediately after I merged a working PR, simply because you felt like it, and breaking things in the process.  That you 'didn't merge the PR' is irrelevant, as you would have merged it if I hadn't said something, and then it would have been broken for no reason, as you didn't have any business making changes to that portion of the codebase right now to begin with.  My job isn't to go around fixing things that you broke needlessly, and you shouldn't be messing with things that you aren't involved in, don't use, can't use, etc. for no good reason.  As Roxy said, and as I've already agreed is fine with me, once something is stable and fully baked, have at it.  Until then, it should be left alone.

----

Anyway, seriously:  I'm done.  You've ignored more-or-less-wholesale all the actual, substantive issues I had, focused on petty nothings, and refused to see what upset me in an exceedingly-and-probably-intentionally obtuse manner.  At this point I just don't like you, and we're past the point of no return.  No need to respond further.   Best of luck, etc.

**Comment by thinkyhead** [comment]
> No one would reasonably assume they could change the coding style that you go around enforcing on everyone.

Ok, well I stopped reading after this sentence, so I guess you failed to make your point.

**Comment by emartinez167** [comment]
Thank you!
Spark by Readdle

**Comment by emartinez167** [comment]
Sorry for that.... I clicked the wrong button...

**Comment by fiveangle** [comment]
rough to see

looks like 2 very stressed individuals who both are feeling under appreciated (rightfully so since this is crux of wild west open source after all, where everyone's just trying to build cool stuff that can't be done by one human being)

Sidebar: @Roxy-3D and @bgort - it's no substitute for truly digging into the bowels of git i'm sure, but some tools definitely make conflict resolution MUCH easier.  There's a slew of them, but by far the favorite of this relative newb is GitKraken.  Expand for a view of just it's conflict resolution screen.

gitkraken

It also clearly marksup source with the conflict blocks so they are immediately visible if you use an external conflict resolution program.  There are some great tips on git CR here:

https://developer.atlassian.com/blog/2015/12/tips-tools-to-solve-git-conflicts/

If there are better clients out there I'm not aware of any. I've tried most and this one is darn good for managing the githubosphere with relative ease.  Just a half hour or so of watching some of the intro videos and the investment pays off.  Less gitting, more coding :)

**Comment by thinkyhead** [comment]
Diggy daggy do, indeed. Anyone wants me to hold on changes when working on features, please just ask. No need to presume impending disaster. And, changes can always be rolled back if they are inconvenient. More than happy to accommodate the inspired developer.

**Pull request merged**
