### PR TITLE
Rename Macro Definition. Use feedrate instead of speed.. and some other

### PR DESCRIPTION
**Pull request by robbycandra**
Rename List : 
```cpp
#elif defined(MPE_FAST_SPEED)
  #error "MPE_FAST_SPEED is now MPE_FAST_FEEDRATE."
#elif defined(MPE_SLOW_SPEED)
  #error "MPE_SLOW_SPEED is now MPE_SLOW_FEEDRATE."

#elif defined(EXTRUDER_RUNOUT_SPEED)
  #error "EXTRUDER_RUNOUT_SPEED is now EXTRUDER_RUNOUT_FEEDRATE."

#elif defined(MINIMUM_PLANNER_SPEED)
  #error "MINIMUM_PLANNER_SPEED is now MINIMUM_PLANNER_FEEDRATE."

#elif defined(TOOLCHANGE_FS_RETRACT_SPEED)
  #error "TOOLCHANGE_FS_RETRACT_SPEED is now TOOLCHANGE_FS_RETRACT_FEEDRATE."
#elif defined(TOOLCHANGE_FS_UNRETRACT_SPEED)
  #error "TOOLCHANGE_FS_UNRETRACT_SPEED is now TOOLCHANGE_FS_UNRETRACT_FEEDRATE."
#elif defined(TOOLCHANGE_FS_PRIME_SPEED)
  #error "TOOLCHANGE_FS_PRIME_SPEED is now TOOLCHANGE_FS_PRIME_FEEDRATE."
#elif defined(TOOLCHANGE_FS_WIPE_RETRACT)
  #error "TOOLCHANGE_FS_WIPE_RETRACT is now TOOLCHANGE_FS_WIPE_RETRACT_LENGTH."

#elif defined(DEFAULT_MINIMUMFEEDRATE)
  #error "DEFAULT_MINIMUMFEEDRATE is now DEFAULT_MINIMUM_FEEDRATE."
#elif defined(DEFAULT_MINTRAVELFEEDRATE)
  #error "DEFAULT_MINTRAVELFEEDRATE is now DEFAULT_MIN_TRAVEL_FEEDRATE."
#elif defined(DEFAULT_MINSEGMENTTIME)
  #error "DEFAULT_MINSEGMENTTIME is now DEFAULT_MIN_SEGMENT_TIME."
```

### CODE REVIEW

**Comment by robbycandra** [comment]
Yes... I know this will not pass the check. 
At least, I have already made a list.

**Comment by ellensp** [comment]
This will break every single configuration file that currently exists. 
That is just cruel USER torture.

Needs a config file version number update..

**Comment by robbycandra** [comment]
Yes... not easy for USER. 
But for developers, it helps to find any constant which affects Feedrate. 

except for  

```cpp
#define TOOLCHANGE_FS_WIPE_RETRACT         0  // (mm/min) Retract before cooling for less stringing, better wipe, etc.'
change to 
'#define TOOLCHANGE_FS_WIPE_RETRACT_LENGTH      0  // (mm) Retract before cooling for less stringing, better wipe, etc.
```

at least the comment is wrong and confusing.

**Comment by descipher** [comment]
-1

**Comment by robbycandra** [comment]
> This will break every single configuration file that currently exists. That is just cruel USER torture.
> 
> Needs a config file version number update..

It would be crueler if we change all the units of feedrate to mm/s or mm/m.... but better. :)

**Pull request closed without merging**
