### PR TITLE
align indent for temp residency, window & hysteresis

### PR DESCRIPTION
**Pull request by StuSerious**
### Description:
Good morning, noticed they weren't spaced out all the same and it bothered me enough to try and fix it, I hope it's OK style-wise!
This is a bit light but for my first PR I figured I'd take it easy 😄
(I hope its not useless.. I don't want to generate clutter)

### Requirements
This PR has no specific requirements!

### Benefits
Symmetry!

### Configurations
This PR doesn't require special configurations!

### Related Issues
This PR has no related Issues!

Thanks a lot for your time!
~Ste

### CODE REVIEW

**Comment by qwewer0** [comment]
If we are at it, could you do it the right way? So the digit places are aligned. (and the comments too...)
e.g.
https://github.com/MarlinFirmware/Marlin/blob/6e1024737d0f74cdc7aed99a9275e071283fe4b7/Marlin/Configuration.h#L223-L226

**Comment by StuSerious** [comment]
Thanks quwwer0 for pointing out my mistake 🙇🏼 
Are all numerical values indexed to the right? I see that some are and some aren't, I could take a look at that too! ;)

**Comment by qwewer0** [comment]
> Thanks quwwer0 for pointing out my mistake 🙇🏼
> Are all numerical values indexed to the right? I see that some are and some aren't, I could take a look at that too! ;)

It is best to align to the decimal point, but we don't always notice if it isn't that way.

Thanks for the quick fix.

**Comment by thinkyhead** [comment]
Thanks! Can you also apply this change to all configurations at MarlinFirmware/Configurations repository `import-2.0.x` branch and submit a PR there? It should be pretty quick with a few regex search-and-replaces.

**Comment by StuSerious** [comment]
Been a busy weekend, but I have time now finally!

> It is best to align to the decimal point, but we don't always notice if it isn't that way.

Aight, thanks for the tip! If there's a reference on comment stile and spacing I could do a sweep of conf.h & conf_adv.h and enforce it!

> Thanks! Can you also apply this change to all configurations at MarlinFirmware/Configurations repository import-2.0.x branch and submit a PR there? It should be pretty quick with a few regex search-and-replaces.

Yessir! I'm on it!

**Comment by StuSerious** [comment]
update: finishing up https://github.com/MarlinFirmware/Configurations/pull/437

**Pull request merged**
