### PR TITLE
[2.0.x] HAL for STM32F1

### PR DESCRIPTION
**Pull request by thinkyhead**
Cleanup of #7764 ready for merge

### CODE REVIEW

**Comment by Phr3d13** [comment]
I have been waiting for this! My GTM32Pro board uses this chip. How does one go about reverse-engineering pins?

**Comment by thinkyhead** [comment]
> How does one go about reverse-engineering pins?

With a bare-bones Marlin install on your board, plus `PINS_DEBUGGING` enabled, you can use `M43 W` to watch all pins for changes. Then, ground or connect to a 5V pin to a pin you want to know, and Marlin will spit out to serial the DIO number of the pin that changed.

(This assumes that the `pinsDebug` code is working properly for your platform.)

**Comment by Phr3d13** [comment]
As soon as I get some free time, I'll have a go at it, thank you.

**Comment by alexxy** [comment]
So there are some chances for boards like mks robin?

**Comment by Roxy-3D** [comment]
Yes...   And Tannoo has even done some preliminary work with regard to the touch screen.   But it will take time to get everything going.

**Comment by victorpv** [comment]
I haven't tested if pindebugging works in this HAL, it's still very preliminary, but I will check and add if any code is missing for that.
You can also try to trace the schematic using a multimeter, just make sure nothing is connected and your multimeter uses a low voltage, which it should.

**Comment by alexxy** [comment]
Ok. I have some stm32 dev boards and may add some steppers to them. How to build this HAL with tools like PlatformIO or may be arduino?

**Comment by victorpv** [comment]
@alexxy this uses the stm32 core from https://github.com/rogerclarkmelbourne/Arduino_STM32
I am using Sloeber, but platformio should work, and Arduino IDE too.
I have only used platformio with the re-arm, so I'm a total newbie with it and can't give much advise on how to use it.
With arduino IDE it should work by just downloading that core to your hardware folder, selecting the board, and compiling. I will try Arduino when I get a chance and try to add some instructions. If you get to compile it with either and can write your steps, that would be a nice addition to the readme in that HAL.

**Comment by Spawn32** [comment]
@victorpv 
Have you been able to get sd card working on you hal implementation?
in my case it must be software spi since i dont have the sdcard on a SDIO port on my STM32F7.

And how is your pinsdebug coming along ? 😃

**Comment by victorpv** [comment]
I think replied in another thread, but have been away from Marlin development a few weeks now. I need to send a PR for the latest changes I did in the code, currently on my fork, but I did changes to the timers code to speed up processing. I have not had time to look at pinsdebug :(

I ran Marlin and printed successfully in a Chitu3d board. Now need to test with thermocouple because the owner has a thermocouple for his hotend, and I only used thermistors (with ADC), so that and the LCD are the next target.
xC000005 tested the SD card and worked fine. I haven't even wired mine yet, but based on his test it should work just fine.
I have designed and produced my own custom board to testing and for the fun of it. Thinking on starting a Kickstart campaign to see if there is enough interest to refine it and mass produce it for a low cost, but given how dirty cheaps this MCUs are, and STM board should be cheap to produce, and get all the features the community wants. In mine I have direct drive of 6 steppers (for 3 color mixing, but have pins for up to 8 or more steppers), 4 ADC inputs, 3 high power mosfet, 1 low power one, LCD, SDCard in lcd panel, SDcard on board, connector for ESP01 module (tested and working with Esp3d firmware), 4 endstops IO (can be used for output too), and about 20 pins broken out to a couple of connectors to test anything else I can think off (laser, proximity sensor...)

**Comment by victorpv** [comment]
Just ot mention the LCD and SDCard seem to work. Still need to iron out some artifacts, I think it's because the MCU is a bit too fast for the LCD panel, but I can go thru the menus, and start an SDCard print.

**Comment by Spawn32** [comment]
Very nice victor :) 
Going to make a "M" code to enable programming mode and flashing from the MCU to a ESP8266, got the STM32F7 to communicate with it last night :) (the coming multi host branch is nice).

Can not get the sd card to work, you are just using SPI ? or is your sd card connected to the real SDIO port of the MCU ?

Waiting for a SPI / logic analyzer to figure out whats going wrong, this might be a difference between the official hal you are using and the STMGeneric..

That reminds me, will have to order one of those "normal" LCD panels, i only have the MKS TFT 3.2 and that works as long as it has a serial port :)

**Comment by victorpv** [comment]
there is an M997 in reprap for Duet, I was having a look last night. I was looking at it to find the ESP programming protocol, it's there if you need to find it.
I am using SPI, if you are using long cables the speed may be a problem, perhaps slowing it down helps?
I have only used the SDIO with sdcard connectors soldered directly on the board, haven't tried with long cables.
In Marlin the current code only allows for SPI, if you want to use SDIO, you need to replace the low level driver. I have thought on that, but didn't start yet. Marlin uses a fairly old version of the sdcard library from Bill Greyman that doesn't include any SDIO support from what I saw when I looked at it.

**Comment by victorpv** [comment]
BTW I have 2 cards, one in SDIO on board, one in SPI in the LCD panel. I haven't started with the SDIO one, but is in my plans for later.

**Comment by Spawn32** [comment]
It's a onboard sd card connector so no wires, have tested speeds from 0.4mhz up to 10mhz on the spi clk, cards from 2gb up to 32gb, always the same vol ini error... have verified the actual spi speed with my scoop..

Will have a look at the M997, thanks for the tip :)




Started out looking at Criss Bars picoprint, and then i just went bananas.
Notice the Pi Zero W connector in the middle, nice for octoprint, stolen from Prusa MK3 :)

**Comment by victorpv** [comment]
So it's onboard but connected to SPI, port 1? not sure what else you can try other than connecting a logic analyzer, perhaps there is a short or a cut track in one of the signals?
Did you also try different sdcards? since the library is old, may not be very compatible with new large cards.

**Comment by victorpv** [comment]
Nice board.
You can see some pictures of my board here, and a review of the place I ordered the pcbs from:
http://www.stm32duino.com/viewtopic.php?f=45&t=2907
If you don't know them and decide to use them, you can join using my link, it's in that post, gives me some credit to continue paying for PCB revisions ;)
I thought on using L6740 on SPI, but decided I to go with pololu steppers to be more flexible. My main goal was to get a board with 6 steppers with an STM for my own use, but be a bit flexible in case I want to either release it free, or kickstart, or kickstart then release the final design as the Re-ARM did.
Yours remind me a lot of STM's own reference board.

**Comment by Spawn32** [comment]
Looks very nice Victor :)
A bit funny, i used AllPcb as well :)

Order'd 10 test pcb's. got 13, order'd solder past stencil for the component side, got one for both sides (have a few component's on the back that they probably noticed).

Seems like a very good company, will keep on using them :)

The main power connector on my board is from ST's ref design, can deliver more current and not so flimsy as the one's normally used :)

**Comment by victorpv** [comment]
I took their idea for esd and overvoltage protection in the ADC and endstop pins ;) but used a different IC.
That board is crammed pretty bad cause I wanted it to fit as many things as possible in 100x100 to test the HAL. Like your idea for the power regulator. I used a 7805 but heats up a bit too much for my taste.  I plan to include a switching regulator on board for the next revision, but may go your route.

**Comment by Spawn32** [comment]
The DC/DC buck controller chip in the middel of the regulator board cost's twice as much at digikey as the whole power board with the same chip from alixpress, LOL

Used them in my drone's earlier..

Can handel up to 3amp if you add a heatsink, volt is also adjustable...

**Comment by Spawn32** [comment]
Haha, decided to have a last go at the sd card before waiting for the SPI analyser, was a short between CS and MOSI, i use on of those sd card connectors that has all the soldering points in the middle an almost not visible, have check them before without seeing, but was shorted :)

So no more "vol init error", now i get "Error:openRoot failed" so at least it's now seeing the card, nice :)

**Comment by victorpv** [comment]
Was just writing to advise to check CS, when you posted that.

**Comment by victorpv** [comment]
Was looking at something else, and saw this line to set the sdcard init speed, in sdfatconfig.h:
#define SPI_SD_INIT_RATE 5

If I remember right the init speed must be 400Khz, so make sure in your HAL the SPI clock is set accordingly to get the right speed. I had not paid attention in the F1 and works fine, but you are running a  faster MCU and the SPI may be going to fast during init.

**Comment by Spawn32** [comment]
yup, measured init to 400khz..

@Roxy-3D or @thinkyhead is there any known limitations to the current sd card implementation in Marlin for on board sd card / spi  ?

Using a 2gb card i get:
Formatted as Fat32 = vol init error
Formatted as old type Fat = SD card ok

If i try anything over 2gb in size i get vol init error with both Fat and Fat32

**Comment by Bob-the-Kuhn** [comment]
I'm pretty sure that the Marlin SD card software can handle just a single 32G volume.  I know that 64G is too big, 8G works and only one volume is available if an SD card has more than one volume.

**Comment by Bob-the-Kuhn** [comment]
SPI_SD_INIT_RATE 5 results in 250KHz SPI clock.

**Comment by Bob-the-Kuhn** [comment]
The Marlin SD software starts at the 250KHz rate and kicks it up to the configured rate if it determines the card can handle it.

The file HAL_spi.cpp in the HAL_LPC1768 directory has both soft & hard SPI implementations that work.

**Comment by Spawn32** [comment]
Thanks @Bob-the-Kuhn very nice to have the "facts" of what it can handel, speed 5 gives me 400khz on the stm32f7, tested speed 6 but didn't help.

there is probably more problems:

echo:SD card ok  // then i do a M20
Begin file list
echo:Cannot open subdir SYSTEM~1
End file list
ok

I know i read somewhere about the exact same problem, wouldn't accept cards bigger than 2gb, was a "uint" problem, but cant find back the info :)

will have a look at the 1768 spi and see if i missed something, thanks :)

**Comment by Bob-the-Kuhn** [comment]
You're 99% of the way there.  Marlin has recognized the card and is trying to read files from it.

The low speed SPI part is working.  Maybe the faster SPI speed(s) have a problem.

Try `#define SPI_SPEED SPI_SPEED_6` & see if it'll list the files.

**Pull request merged**
