### PR TITLE
Refactoring DGUS screens code

### PR DESCRIPTION
**Pull request by Desuuuu**
### Description

This PR aims to tidy up DGUS code by re-arranging and refactoring it.

Here are the main changes:
* Splitting the two classes in DGUSDisplay.cpp/.h into separate files.
* Moving display-specific files into separate folders.
* Changing the `VPHELPER` defines which were calling sizeof on pointers. As a result, I re-added the size check in `DGUSDisplay::ProcessRx`.

Functionality should be unchanged after these changes.

@GerogeFu maybe you could take a look at this considering you've been working on this code recently.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I've done a rebase and squash to resolve conflicts. I merged the "DUGS" / "DGUS" patch earlier so that we can focus on the other changes here. To update your working copy use the Git console and type the following commands:
```
git fetch origin
git checkout dgus-refactor
git reset --hard origin/dgus-refactor
```

**Comment by GerogeFu** [comment]
I will check. Give me some time.

**Comment by Desuuuu** [comment]
I added a few useful functions for the screen in my last commit. They're documented in the T5UID1 guide (there's a copy available [here](https://github.com/juliandroid/DWIN_CR_10s_Pro/blob/master/tools/T5UID1%20Application%20Guide.pdf)).

**Comment by GerogeFu** [comment]
Compilation not finished , link errors happened . But not the DGUS code part cause this. Maybe my pio or vscode cause that. I need time to check . It can't find <Servo.h> file for me. Weird. I am testing FYSETC S6 . Or you can try to compile to see if it's only my issue.

**Comment by Desuuuu** [comment]
Compilation succeeds for me on the latest version of this branch with [the example FYSETC S6](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/FYSETC/S6) (with `DGUS_LCD_UI_FYSETC` defined) and the FYSETC_S6 PIO environment.

Do you have anything special in your configuration?

**Comment by GerogeFu** [comment]
Forget about the compilation. My git cause issue .And i check and test with S6 board. I think the code is good.

**Comment by Desuuuu** [comment]
I added two more functions to control the state of touch controls.

It can be useful for example when you have a touch control with a click sound over a button that can be disabled/hidden.

**Comment by ModMike** [comment]
I have been waiting for this for a long time. This was the last piece in fully upgrading A creatbot to Marlin 2.0.

What DGUS interface do we use? ADVi3++?

**Comment by thinkyhead** [comment]
The DGUS code has been significantly restructured, so the changes in this PR will need to be reexamined in light of the latest code. It might be a bit of a manual process, but it would be good to know what we have covered already versus what gaps this PR still fills in.

**Comment by Desuuuu** [comment]
I do think that's the best way to go.

The current DGUS code would probably benefit from some re-organization at least (which was the point of this PR pretty much).

I'm not really working on this anymore though so if anyone wants to pick this up, feel free to do so. If there's a need for this, I might pick it up later, provided I find the time and motivation.

**Pull request closed without merging**
