### PR TITLE
Add Duet Smart Effector support

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
This PR adds the M672 command which sets/resets the sensitivity of the Duet Smart Effector.

See the M672.cpp file for details.

NOTE - the format of the Marlin version of the M672 command is different than shown in the [Duet Smart Effector documentation](https://duet3d.dozuki.com/Wiki/Smart_effector_and_carriage_adapters_for_delta_printer).  The Marlin parser can't handle the Duet version so the Marlin version is simplified and more user friendly.

### CODE REVIEW

**Review by Bob-the-Kuhn — COMMENTED** [review]
**M672_MOD_PIN** to **SMART_EFFECTOR_PIN** change

1) only partially implemented.
2) suggest pin name be **SMART_EFFECTOR_MOD_PIN** as the DUET documentation calls this pin **MOD**

**Comment by Bob-the-Kuhn** [comment]
See [PR #10](https://github.com/MarlinFirmware/Configurations/pull/10) and [PR #11](https://github.com/MarlinFirmware/Configurations/pull/11) for changes to the default and example configurations.

**Comment by Bob-the-Kuhn** [comment]
Don't merge until the **configure_i2c** compile bug introduced by PR #16584 has been fixed.  I can't test until that happens.

**Comment by Bob-the-Kuhn** [comment]
I've been able to test the code.  It works properly.

Please merge.

**Comment by thinkyhead** [comment]
Looks good, thanks!

**Pull request merged**
