### PR TITLE
🚸 Revert M206 Home Offset behavior

### PR DESCRIPTION
**Pull request by thinkyhead**
Change the `M206` / `M428` `home_offset` back to its old classic behavior, acting as an offset to the homing position on `G28` and not as an element of the workspace offset. In the first commit a `home_offset` change from `M206`, `M428`, or editing on the LCD only takes effect on the next `G28` instead of affecting the native position immediately.

Caveats:
- This command causes the native machine space to change, therefore any leveling data saved to EEPROM will become invalid, in contravention to current documentation which states that it will remain valid. At present there is no facility to account for this, such as selectively rewriting the mesh and EEPROM.

### CODE REVIEW

**Comment by ThomasToka** [comment]
Generally it works half yet.

I have

x_min_pos = -2
y_min_pos = -2

in the configuration.h.

Some minor tweaks are needed it think.

intially after installation x_min_pos and y_min_pos is not populated to the M206 output

```
Send: M206
Recv:   M206 X0.00 Y0.00 Z0.00
```

Then setting it:

```
Send: M206 X-3 Y-2
Recv: X:-2.00 Y:-2.00 Z:0.00 E:0.00 Count X:-159 Y:-159 Z:0
```

save:
```
Send: M500
Recv: echo:Settings Stored (719 bytes; crc 47159)
Recv: //action:notification Settings Stored
Recv: //action:notification Settings Stored
```

check:
```
Send: M206
Recv:   M206 X-3.00 Y-2.00 Z0.00
```

home g28xy:
```
Recv: echo:enqueueing "G28 X Y"
[...]
Recv: X:-5.00 Y:-4.00 Z:6.90 E:0.00 Count X:-398 Y:-318 Z:2760 <--- thats wrong
```

display also shows x -5 and y -4.

m114 also:

```
Send: M114
Recv: X:-5.00 Y:-4.00 Z:6.90 E:0.00 Count X:-398 Y:-318 Z:2760
```

i have created a own branch for the tests with my release code. but should work like stock marlin here..

https://github.com/ThomasToka/Marlin/commit/9839062bd73dcfe3da6e8ad40bb3c88bdeaa4cd1

**Comment by thinkyhead** [comment]
> x_min_pos = -2 y_min_pos = -2

After a moment's thought I rejected the concept of making those settings the seeds of `M206`. The `M206` offset applies to the endstops as part of `G28`, and the endstop might be the one on the right, in which case the `X_MIN_POS` is not properly related to `M206` but is just the left physical limit.

**Comment by InsanityAutomation** [comment]
> Caveats:
> 
>     * This command causes the native machine space to change, therefore any leveling data saved to EEPROM will become invalid, in contravention to current documentation which states that it will remain valid. At present there is no facility to account for this, such as selectively rewriting the mesh and EEPROM.

I don't agree that this is a caveat. M206 is adjusting the nozzle back to an expected position after a change, therefore the mesh data shifting would be the cause of the issue expected here. M206 should be set to get the nozzle 0,0 to match the front left corner of the plate after changing a hotend mount or endstop, or any other repair, therefore the mesh relating to the bed position has no reason to change.

**Comment by thinkyhead** [comment]
> `M206` should be set to get the nozzle 0,0 to match the front left corner of the plate after changing a hotend mount or endstop, or any other repair

That is not guaranteed, and users might choose to use `M206` for other things, which is not uncommon. There is no way to check for the change matching up in that way, so any change to `M206` can only be assumed to be untrustworthy. And, if we plan to extend this PR so that it changes the current position immediately in response to `M206` without waiting for the next `G28`, then obviously in that case the existing mesh data relates to an outdated position.

**Comment by ThomasToka** [comment]
Today i integrated it.

What i have seen is that it works es (nearly fully) as expected when i set:

`#define NO_WORKSPACE_OFFSETS`

What i have seen:

When X_MIN_POS and Y_MIN_POS are set in config to a non zero default the values set with M206 add up to them.

X_MIN_POS=-2
Y_MIN_POS=-2

```
Send: M206 X-3.5 Y-2.5
Recv:   M206 X-2.00 Y-2.00 Z0.00
```

will be then shown on M206 as:
```
Send: M206
Recv:   M206 X-5.50 Y-2.00 Z4.50
```

and also the endstop position on home will be X-5.5 and Y=-4.5.

expected would be that M206 if X_MIN_POS and/or Y_MIN_POS are set to non Zero values overwrites them and does not add up.

If X_MIN_POS=0 and Y_MIN_POS=0
```
Send: M206 X-2 Y-2
Recv:   M206 X0.00 Y0.00 Z0.00
```

then it works
```
Send: M206
Recv:   M206 X-2.00 Y-2.00 Z0.00
```

```
Send: M206 X-3 Y-4
Recv: X:-2.00 Y:-2.00 Z:0.00 E:0.00 Count X:-159 Y:-159 Z:0
```

```
Send: M206
Recv:   M206 X-3.00 Y-4.00 Z0.00
```

**Pull request merged**
