### PR TITLE
NUM_AXES usage fix on 2.0.x branch

### PR DESCRIPTION
**Pull request by moonglow**
`NUM_AXES` automatically defined only on 2.1.x branch. Also this define is not used by any other files, looks like it was added by  accidentally to that branch. 

I also wants to notice what original code looks illogical ( IMHO), why we need to choose MAX value if we can't use invalid I2C channel index.
original:
```C
for (uint8_t i = E_AXIS + 1; i < _MAX(DIGIPOT_I2C_NUM_CHANNELS, (NUM_AXES + 3)); i++)
if (parser.seenval('B' + i - (E_AXIS + 1))) digipot_i2c.set_current(i, parser.value_float());
```

### CODE REVIEW

**Comment by DerAndere1** [comment]
Author of the buggy code here. I think my intention with the original code was to ensure that only  parameter names B, C, D are used for setting currents of extra extruders, even if `DIGIPOT_I2C_NUM_CHANNELS` offers more channels. You may try something like the following for bugfix-2.0.x and bugfix-2.1.x: 
```cpp
for (uint8_t i = E_AXIS + 1; i < _MIN(DIGIPOT_I2C_NUM_CHANNELS, (E_AXIS + 4)); i++)
  if (parser.seenval('B' + i - (E_AXIS + 1))) digipot_i2c.set_current(i, parser.value_float());
```
or the equivalent 
```cpp
for (uint8_t i = E1_AXIS; i < _MIN(DIGIPOT_I2C_NUM_CHANNELS, (E1_AXIS + 3)); i++)
  if (parser.seenval('B' + i - E1_AXIS)) digipot_i2c.set_current(i, parser.value_float());
```

**Comment by moonglow** [comment]
Hi @DerAndere1 !

I2C channels maps to AXES with such way:

| DIGIPOT I2C CHANNEL       | AXES |
| ----------- | ----------- |
| 0   | X       |
| 1   | Y       |
| 1   | Y       |
| 1   | Y       |
| 1   | Y       |


Hm.. you solution is better ( it will not use undefined I2C channels ), but it not an equivalent:

Your first version will map:

**Comment by moonglow** [comment]
Hi @DerAndere1 !

Thanx for response!

I2C channels [maps](https://marlinfw.org/docs/gcode/M907.html) to AXES with such way:

| DIGIPOT I2C CHANNEL| AXES | SYMBOL |
| ----------- | ----------- | ----------- |
| 0   | X       | X |
| 1   | Y       | Y |
| 2   | Z       | Z |
| 3   | E0      | E |
| 4   | E1      | B |
| 5   | E2      | C |
| 6   | E3      | D |


Hm.. you solution is better ( it will not use undefined I2C channels ), but it not looks like equivalent solution:

`E_AXIS = E0_AXIS = 3`

Your first version will map ( looks correct ):
```
4 - B
5 - C
6 - D
```

But second version will map it ( looks incorrect ):
```
3 - B
4 - C
5 - D
```

Maybe change it to something like that ( without 'magic' constant ) ?:
```C
    #if E_STEPPERS >= 2
      for (uint8_t i = E_AXIS + 1; i < _MIN(DIGIPOT_I2C_NUM_CHANNELS, (E_AXIS+E_STEPPERS)); i++)
        if (parser.seenval('B' + i - (E_AXIS + 1))) digipot_i2c.set_current(i, parser.value_float());
    #endif
```

**Comment by DerAndere1** [comment]
With the latest state of this PR, when you have `DIGIPOT_I2C_NUM_CHANNELS 8` and `NUM_AXES 3`and `EXTRUDERS 5` and `MOTOR_CURRENT_COUNT 8` you will get this mapping:
```
axis - cammand parameter
E1 - B
E2 - C
E3 - D
E4 - E // conflict: M907 E... will always set currents for E4 and E0
```

**Comment by thinkyhead** [comment]
> With the latest state of this PR

Aha, that is why the +3 was in there…. Ok, yes, so it should be limited to the original first three only, but later should probably use an index parameter. It is following a legacy pattern for consistency with the jabberwocky.

**Pull request merged**
