### PR TITLE
Add string classes

### PR DESCRIPTION
**Pull request by X-Ryl669**
### Description

Adding a read/write and read only string classes for... string manipulation.
There are 2 classes here with the exact same interface, SString which is a static string class and DString which is a dynamic string class. 

The former use a buffer that's stack (pre)allocated (so it can't resize dynamically), while the latter use a stack like allocator (see documentation for description).

Allow this kind of code:
```cpp
template <typename T>
void testFunc() // Because I'm too lazy to write the same code twice
{
   T test;
   test += "Try ";
   test += 1;
   test += ' ';
   test += ": Here=>";
   test += 3.1415926535;


   printf("%s\n", (const char*)test);
   printf("%s\n", test != "Bob" ? "true": "false");
   printf("%s\n", test == "Try 1 : Here=>3.14" ? "true": "false");

   for (int i = 0; i < 256; i++) test+= '_'; // Check it's asserting false when overflowing and not crashing
}


int main(int argc, char ** argv)
{
   printf("SString...\n");
   testFunc< SString<256> >();
   printf("DString...\n");
   testFunc< DString >();
   return 0;
}
```

There's also a ROString class that's using fluent interface for string/text manipulation.
Instead of such code:
```cpp
      char *pos = nullptr;
      for (uint8_t f = 0; f < folderdepth; f++)
        pos = strchr(currentfoldername, '/');

      *(pos + 1) = '\0';
```
You can use this code:
```cpp
      ROString folder(currentfoldername);
      currentfoldername[folder.reverseFind('/')] = 0;
```
There are many useful functions like `upToFirst`, `fromFirst`, `upToLast`, etc... They are all fluent, so it makes the intend obvious:
```cpp
    ROString path(...);
    ROString filename = path.fromLast("/");
// or
   ROString gCodeCMD("M150 U212 R120");
   ROString command = gCodeCMD.splitFrom(" "); // returns the part before the split and modify the object
   ROString someArgument = gCodeCMD.fromFirst("U").splitFrom(" ");
```

### Requirements

Nothing special

### Benefits

Code legibility. I haven't replaced all the strcpy/strcat in the code right now but most of them.
There's still the MKS's wifi code that's awful.
We'll be able to remove all the various functions used to convert number to string, and have a common intuitive interface to use.

### Tests
See this [godbolt](https://godbolt.org/z/hxxWM1r95) and this [one](https://godbolt.org/z/xe1rK8qbx) for ROString 

## Not for 2.0.8 release

### CODE REVIEW

**Comment by ejtagle** [comment]
@X-Ryl669 : Of course, if you are willing to open this can of worms, i'd suggest to implement a constexpr string. This would allow compile time concatenation/parsing/formatting of constant strings, and, with some effort, you could avoid the usage of dynamic memory (how..? ... Think about a linked list of strings/parsers to call to "print" ... You can, with some careful planning, avoid dynamic allocations, that are NO-NO under embedded microcontroller environments, specifically AVR ... ;)

Just for inspiration: https://gist.github.com/dsanders11/8951887
And https://github.com/boostcon/cppnow_presentations_2012/blob/master/wed/schurr_cpp11_tools_for_class_authors.pdf?raw=true

**Comment by X-Ryl669** [comment]
@ejtagle I've started this work [here](https://github.com/MarlinFirmware/Marlin/pull/21355). It's just that there isn't too much place in the code where a constexpr would save something (see the linked PR for a list).

In the end, it just focused the spotlight on code that can/should be rewritten not to use string at first.

**Comment by X-Ryl669** [comment]
The SString version is a kind of mix of compile time string and runtime string. 
The allocation is stack based, so you don't have to use malloc/realloc/free (which, as you said is a no-no except for few platforms), but you can concat with runtime data.

**Comment by rhapsodyv** [comment]
IMHO

I think you should not start changing every single place. It's the recipe to disaster and instability.

Choose a single feature ** **that you can full test** ** and change just it to use your new classes. Then, after everything works, just let it be merged and work on the next feature.

Starting changing every piece of the code that doesn't have any automated test is a very fast way to burn everything. Please, don't do it.

**Comment by X-Ryl669** [comment]
> I think you should not start changing every single place. It's the recipe to disaster and instability.

Yes. That's a draft. The main issue here is that everything is a spaghetti code here. If you pull one, you've to pull everything.
**Don't use this code as is, it's not tested yet**.

**Comment by X-Ryl669** [comment]
As a side note, I've written a lot of godbolt to test some code. Maybe it's time to think about automated subcode testing (not just building) ?

**Comment by rhapsodyv** [comment]
> **Don't use this code as is, it's not tested yet**.

The main issue is that we can't test everything. It's nearly impossible. We are talking about different hardware, different setups, different usages.

The best we can do is to choose a part that we can fully test and rewrite it, isolated from the rest. Then merge, and go to the next part. After 3 or 4 parts merged, we gain more confidence to move further.

The worst, is that this type of refactor generate subtle and random bugs, that are hard to find and takes a lot of effort and hours to track and fix. 
We aren't so many here investing time to track those issues... 

Doing this way will potentially makes marlin randomly broken for months.

And can and should refactor and improve the code. But we need try to do it in a well planned way.

**Comment by rhapsodyv** [comment]
> As a side note, I've written a lot of godbolt to test some code. Maybe it's time to think about automated subcode testing (not just building) ?

I’m not too much concerned about your new code. But with the rewrites to use the new classes that can potentially change the behaviors and generate random issues.

**Comment by rhapsodyv** [comment]
Why keep changing more and more code to use this classes?

Why not make one module (like parser) working 100% with the new classes, merge, then wait some time to test, and after that, continue the work?

Changing all at once may lead to a total disaster.

**Comment by thinkyhead** [comment]
> Why keep changing more and more code to use this classes?

Who said it will all be merged at once? Someone has to merge from `bugfix-2.0.x` occasionally to keep the PR fresh, and if the original creator has lost interest then it falls to me.

**Comment by X-Ryl669** [comment]
No, I haven't lost interest, far from that. I've lost free time in the current period (a lot of work to finish and deliver and less free time for the cool stuff).

I'll be back as soon as possible and resume this work. We (Victor and I) kind of agreed on splitting this with more tests of the internal string manipulation code in Marlin, so I bootstrapped on the unit test PR instead. 

So, I'd say, the order to merge would be the Unit testing stuff first (since it won't interfere with Marlin's work), then the string changes once they are *individually* tested.

**Pull request closed without merging**
