### PR TITLE
Fixed BUTTON_PRESSED() macro calls in buttons.h

### PR DESCRIPTION
**Pull request by Mekadrom**
Hello, this is my first pull request for Marlin.

### Description

While attempting to write a configuration for the Dreammaker Overlord Pro, I stumbled into this problem upon updating from the base repository from whatever code stream I had locally. This prevents compilation when using the configuration required for the Overlord Pro, and possibly other printers.

### Requirements

I found that this compilation error occurs when setting these two flags, but there may be other configurations that hit the same precompiler directives:

- `#define MOTHERBOARD BOARD_OVERLORD`
- `#define OVERLORD_OLED`

Upon setting these flags, the following compilation errors are seen:
```In file included from Marlin\src\lcd\marlinui.h:28:0,
                 from Marlin\src\lcd\marlinui.cpp:40:
Marlin\src\lcd\marlinui.cpp: In static member function 'static void MarlinUI::update_buttons()':
Marlin\src\lcd\buttons.h:166:29: error: '_BUTTON_PRESSED_DOWN' was not declared in this scope
 #define BUTTON_PRESSED(BN) (_BUTTON_PRESSED_##BN)
                             ^
Marlin\src\lcd\marlinui.cpp:1315:22: note: in expansion of macro 'BUTTON_PRESSED'
             else if (BUTTON_PRESSED(DOWN)) {
                      ^~~~~~~~~~~~~~
Marlin\src\lcd\buttons.h:166:29: note: suggested alternative: '_BUTTON_PRESSED_DWN'
 #define BUTTON_PRESSED(BN) (_BUTTON_PRESSED_##BN)
                             ^
Marlin\src\lcd\marlinui.cpp:1315:22: note: in expansion of macro 'BUTTON_PRESSED'
             else if (BUTTON_PRESSED(DOWN)) {
                      ^~~~~~~~~~~~~~
Marlin\src\lcd\buttons.h:166:29: error: '_BUTTON_PRESSED_LEFT' was not declared in this scope
 #define BUTTON_PRESSED(BN) (_BUTTON_PRESSED_##BN)
                             ^
Marlin\src\lcd\marlinui.cpp:1319:22: note: in expansion of macro 'BUTTON_PRESSED'
             else if (BUTTON_PRESSED(LEFT)) {
                      ^~~~~~~~~~~~~~
Marlin\src\lcd\buttons.h:166:29: note: suggested alternative: '_BUTTON_PRESSED_LFT'
 #define BUTTON_PRESSED(BN) (_BUTTON_PRESSED_##BN)
             else if (BUTTON_PRESSED(LEFT)) {
                      ^~~~~~~~~~~~~~
Marlin\src\lcd\buttons.h:166:29: error: '_BUTTON_PRESSED_RIGHTT' was not declared in this scope
 #define BUTTON_PRESSED(BN) (_BUTTON_PRESSED_##BN)
                             ^
Marlin\src\lcd\marlinui.cpp:1323:22: note: in expansion of macro 'BUTTON_PRESSED'
             else if (BUTTON_PRESSED(RIGHTT)) {
                      ^~~~~~~~~~~~~~
Marlin\src\lcd\buttons.h:166:29: note: suggested alternative: '_BUTTON_PRESSED_RT'
 #define BUTTON_PRESSED(BN) (_BUTTON_PRESSED_##BN)
                             ^
Marlin\src\lcd\marlinui.cpp:1323:22: note: in expansion of macro 'BUTTON_PRESSED'
             else if (BUTTON_PRESSED(RIGHTT)) {
                      ^~~~~~~~~~~~~~
*** [.pio\build\mega2560\src\src\lcd\marlinui.cpp.o] Error 1
```

### Benefits

This allows further development for the Overlord printers and potentially any other paths that hit this piece of code that might have been left unchanged whenever LEFT was renamed to LFT, DOWN to DWN and RIGHT to RT.

### Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/9885511/Configuration.zip)

### Related Issues

I did not open a related issue for this bug as it is pretty minor and its impact is probably just me.

### CODE REVIEW

**Comment by ellensp** [comment]
This was deliberately changed 10 days ago https://github.com/MarlinFirmware/Marlin/pull/24878
from short to full names... 

probably need a different fix vs reversing it

**Comment by Mekadrom** [comment]
> This was deliberately changed 10 days ago #24878 from short to full names...
> 
> probably need a different fix vs reversing it

Are there two different definitions for the BUTTON_PRESSED macro then? Only other thing I can think is that when both of these flags are set, the regular BUTTON_PRESS macro calls are replaced with the old ones.

**Comment by ellensp** [comment]
eg
```DIFF
diff --git a/Marlin/src/lcd/buttons.h b/Marlin/src/lcd/buttons.h
index cb6348dc2d..67b7aa3944 100644
--- a/Marlin/src/lcd/buttons.h
+++ b/Marlin/src/lcd/buttons.h
@@ -191,19 +191,19 @@
   #define _BUTTON_PRESSED_UP false
 #endif
 #if BUTTON_EXISTS(DOWN)
-  #define _BUTTON_PRESSED_DWN _BUTTON_PRESSED(DOWN)
+  #define _BUTTON_PRESSED_DOWN _BUTTON_PRESSED(DOWN)
 #else
-  #define _BUTTON_PRESSED_DWN false
+  #define _BUTTON_PRESSED_DOWN false
 #endif
 #if BUTTON_EXISTS(LEFT)
-  #define _BUTTON_PRESSED_LFT _BUTTON_PRESSED(LEFT)
+  #define _BUTTON_PRESSED_LEFT _BUTTON_PRESSED(LEFT)
 #else
-  #define _BUTTON_PRESSED_LFT false
+  #define _BUTTON_PRESSED_LEFT false
 #endif
 #if BUTTON_EXISTS(RIGHT)
-  #define _BUTTON_PRESSED_RT _BUTTON_PRESSED(RIGHT)
+  #define _BUTTON_PRESSED_RIGHT _BUTTON_PRESSED(RIGHT)
 #else
-  #define _BUTTON_PRESSED_RT false
+  #define _BUTTON_PRESSED_RIGHT false
 #endif
 #if BUTTON_EXISTS(BACK)
   #define _BUTTON_PRESSED_BACK _BUTTON_PRESSED(BACK)
```

**Comment by Mekadrom** [comment]
That makes a lot more sense, thanks. Also, my initial closing of this Pr was a misclick on my phone, so I'll reopen and update it with that change if that's okay.

**Pull request merged**
