### PR TITLE
[2.0.x] AnyCubic Kossel Configuration

### PR DESCRIPTION
**Pull request by brandstaetter**
### Description

This adds a sample configuration for delta/ANYCUBIC/Kossel with many features of Marlin 2 enabled. Might need future refinements to make it foolproof (I rammed my hotend into the bed during testing) but it offers so much more than the old default firmware that is based on 1.1.0 published in https://github.com/ANYCUBIC-3D/ANYCUBIC_Kossel_Source_Code/tree/master/ANYCUBIC_Kossel_Beta2

### Benefits

Big improvements regarding user-friendlyness and configurability without needing to flash the firmware all the time on an ANYCUBIC Kossel, and it also supports Autocalibration and Autoleveling

### Related Issues

N/A

### CODE REVIEW

**Comment by thinkyhead** [comment]
Perhaps @anycubic-3d would like to review this…?

**Comment by brandstaetter** [comment]
Oh great, I totally overlooked #11356 and did all my changes by myself. I'll check what I can unify

**Comment by thinkyhead** [comment]
To update your working copy of this branch, from the Git console…
```
git fetch origin
git checkout bugfix-2.0.x
git reset --hard origin/bugfix-2.0.x
```
…then add new commits and push them to update this PR.

**Comment by brandstaetter** [comment]
Will be merged into #11730

**Pull request closed without merging**
