### PR TITLE
Advance absolute

### PR DESCRIPTION
**Pull request by thinkyhead**
This looks pretty good @Sebastianv650!

Just leaving this here for consideration, where it's easier to see.

Reference: MarlinFirmware/MarlinDev#402

### CODE REVIEW

**Comment by jbrazio** [comment]
Too pity this is not yet an object.. :-P

**Comment by thinkyhead** [comment]
It also needs more work to be compatible with multiple extruders (and mixing extruders).

**Comment by Sebastianv650** [comment]
Maybe I find the time today to start another try to "decrypt" all the related macros and understand their way of working, than the multiple extruder thing should be done.
Mixing extruders is a different thing, I think the whole steppper.cpp can't do that at the moment?

@jbrazio: An extra object for 10 code lines on a µC that starts stuttering when there is only 1 more integer division..? Beside that, I don't see this function as an object. It should be a method of an "extruder" object if you realy want to do that..

**Comment by Sebastianv650** [comment]
Now it should play nice with multiple extruders. I only need a volunteer with more extruder to test it ;)

**Comment by jbrazio** [comment]
@Sebastianv650 you must start paying more attention to the direction Marlin is going. Nevertheless the idea that using objects makes the source code slower is nonsense, it all depends of the "stupidity" of the coder. A real stupid one can even make ASM code slow. ;-)

At the end of day great feature and great work, congrats !

**Comment by Sebastianv650** [comment]
OK, I see I have to dive into this new code as soon as I find some time. I'm blocked until next week, but I will create a mixing compatible version then as soon as I understand your changes.

**Comment by thinkyhead** [comment]
I believe this is now superseded by #3676. So this exhibit is no longer needed here.

**Pull request closed without merging**
