### PR TITLE
[1.1.x] Prepare for Galvanometer and SLA printing

### PR DESCRIPTION
**Pull request by thinkyhead**
Rebase and squash of #6913 by @marcelogaio

- [x] Allows compile of the code with `EXTRUDERS` 0, no detected `HOTEND`, `TEMP_SENSOR_0` 0
- [x] Adds the basic example_configuration files for a new printer profile (SLA_Galvo)
- [x] Fixes some incomplete IF blocks for `E_MANUAL > 1` and `HOTENDS > 1`
- [x] Adds library for MCP4725 12-bit I2C DAC driver

Due to whitespace changes, it's better to view the [Concise Diff](6977/files?w=1).

Still needs:
- [ ] Move galvos kinematically in response to XY motion commands.
- [ ] Combine galvos with laser for full SLA printing control.

### CODE REVIEW

**Comment by thinkyhead** [comment]
@marcelogaio What should we do with the `tool_change` and `Tn` G-code? Is there a useful reason for doing a tool-change on an SLA machine, and what would it be changing?

**Comment by marcelogaio** [comment]
@thinkyhead I can't imagine why a tool_change would be needed on an SLA... It should be disabled.

**Comment by marcelogaio** [comment]
I just saw the build failed. We should take care of a couple of array initialisations which asume EXTRUDER is 1.

**Comment by thinkyhead** [comment]
I'll make sure it passes Travis… at least…

**Comment by marcelogaio** [comment]
@thinkyhead I cloned the marcelo_redo branch, and I am looking into it.
Apart from the changes to `temperature.h`, I am looking at some changes needed in `Marlin_main.cpp`.

Question: would it be a good idea to put a whole function related to `HOTENDS` or `EXTRUDERS` (for example "`inline void gcode_M109() {....`" inside an "`#if`" block?

**Comment by thinkyhead** [comment]
> Question: would it be a good idea to put a whole function related to HOTENDS or EXTRUDERS (for example "inline void gcode_M109() {...." inside an "#if" block?

That's the kind of thing that allowing EXTRUDERS 0 necessitates, which is why no one has pursued it before now. Best of luck finding all the points where code must be wrapped in conditionals.

You'll most likely want to start from this branch if you have changes to add. However, I'm still resolving compiler complaints and following up where conditionals need to be added, so take a break until this is done.

**Comment by thinkyhead** [comment]
Travis just keeps telling me the next thing needing fixing…. Eventually it will be "perfect."

**Comment by thinkyhead** [comment]
@marcelogaio It now compiles. See if it functions at all.

**Comment by thinkyhead** [comment]
@marcelogaio It should now compile. See if it functions with a real galvo.

**Comment by thinkyhead** [comment]
@marcelogaio Wow, it really does compile, finally. I hope it works!

**Comment by marcelogaio** [comment]
@thinkyhead Correct me if I am wrong: `stepper_dac` gives Marlin the ability of using a DAC through I2C port instead of the steppers, for some/all axis...

**Comment by thinkyhead** [comment]
> stepper_dac gives Marlin the ability of using a DAC through I2C port instead of the steppers

It allows you to set the stepper driver motor currents through the i2c interface, and applies to any stepper drivers that include an i2c-based DAC

**Comment by thinkyhead** [comment]
As Marlin 2.0.x looms on the horizon I'm looking to merge this soon and apply it to the Marlin 2.0.x codebase also. I've just rebased it to make sure it's up to date and testable. Is is possible to test this and determine that it works?

**Comment by thinkyhead** [comment]
The next pieces needed are the most important ones:
- Move X and Y galvos in response to motion commands.
- Combine galvos and laser to for full SLA printing control.

**Comment by Blacksheep70** [comment]
I don't see the need for the temperature in a SLA printer. So I suggest to exclude the stuff

`temperature.cpp:895: error: no 'float Temperature::analog2temp(int, uint8_t)' member function declared in class 'Temperature'
 float Temperature::analog2temp(const int raw, const uint8_t e) {
                                                              ^
exit status 1
no 'float Temperature::analog2temp(int, uint8_t)' member function declared in class 'Temperature'`

In a SLA printer you have just a Z-Axis and the galvo to control the laser. Maybe an additional servo / stepper to control the vat to prevent the print from sucking at the bottom.

But there is no extruder or bedheating that would need to measure the temps

**Comment by thinkyhead** [comment]
> So I suggest to exclude the stuff

Yep. There's a pile of changes required that someone with truly strong determination would have to apply across the entire codebase.

**Comment by nesquik011** [comment]
i am lost so does it support Galvanometer or no ! ?  and if not  may you check that system and try to put it in  or work on it   


https://www.youtube.com/watch?v=hbFObc3SvLU

**Comment by AnHardt** [comment]
> does it support Galvanometer or no ! ? 

**No !**

**Comment by nesquik011** [comment]
What about 2 steppers as shown in the video

On Aug 14, 2018, at 5:34 PM, AnHardt <notifications@github.com<mailto:notifications@github.com>> wrote:


does it support Galvanometer or no ! ?

No !

**Comment by AnHardt** [comment]
> What about 2 steppers as shown in the video

Even that - currently **not** ! 
At least not MarlinFirmware/Marlin. You may try one of @marcelogaio 's Marlin branches. He at least seems to have such hardware and tried to integrate it.

**Comment by nesquik011** [comment]
https://github.com/marcelogaio/Marlin   @AnHardt   is thats the link ?  if so i cant find wiki  plus he didnt metion Galvanometer  or 2 mirrors xy axis  hard ware or what board should i buy or anything

**Comment by nesquik011** [comment]
SOMEONE  please respond what kind of hardware do I need and how to connect them  there is no wiki for that

**Comment by thinkyhead** [comment]
At this point Marlin 1.1.x is end-of-life, so this PR will need to be re-done starting from `bugfix-2.0.x` and targeting that branch. Sorry for the inconvenience!

**Comment by DongNT8** [comment]
dear all
i need schematic PIN I2C BOARD_RAMPS_14_EFB connect DAC DAC_MCP4725
thanks.

**Pull request closed without merging**
