### PR TITLE
Default DELAY_NS to round up.

### PR DESCRIPTION
**Pull request by descipher**
### Description

This PR addresses an accepted normal behavior with the delay call DELAY_NS() macro.
The writer normally expects the delay minimum to be met. Currently DELAY_NS() defaults to round down as a result of casting from float to unsigned integer. This PR also adds optional conditions DELAY_NS_ROUND_DOWN and DELAY_NS_ROUND_CLOSEST to allow for cases where the original behavior is appropriate. No special cases are known to need the options as of the time of this PR.

### Requirements

Testing current known issues on shorter than desired delays involves defining any ST7920 LCD such as
```cpp
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
```
### Benefits

LCD timing fixes for a large group of ST7920 based displays which will fail with a recent platformio avr-gcc version updating with optimization improvements.

### Configurations
Default with `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6259853/Configuration.zip)

### Related Issues

#21264 #21495
```cpp
#elif F_CPU == 16000000
  #define CPU_ST7920_DELAY_1 DELAY_NS(0)
  #define CPU_ST7920_DELAY_2 DELAY_NS(0)
  #define CPU_ST7920_DELAY_3 DELAY_NS(63)

#define DELAY_NS(x) DELAY_CYCLES((x) * ((F_CPU) / 1000000UL) / 1000UL)
```
```
11 98         cbi 0x02, 1 ; 2     62.5ns  SCLK LOW
90 91 02 01   lds r25, 0x0102     62.5ns
87 fd         sbrc  r24, 7        62.5ns
90 95         com r25             62.5ns
91 70         andi  r25, 0x01 ; 1 62.5ns
90 93 00 01   sts 0x0100, r25     62.5ns
11 9a         sbi 0x02, 1 ; 2     62.5ns  SCLK HIGH total of 375ns, does not meet the 400ns min spec
00 00         nop                 62.5ns
11 98         cbi 0x02, 1 ; 2     62.5ns  SCLK LOW needs 200ns after a SCLK HIGH, got 125ns
90 91 02 01   lds r25, 0x0102     62.5ns
86 fd         sbrc  r24, 6        62.5ns
90 95         com r25             62.5ns
91 70         andi  r25, 0x01 ; 1 62.5ns
90 93 00 01   sts 0x0100, r25     62.5ns
11 9a         sbi 0x02, 1 ; 2     62.5ns  SCLK HIGH 375ns
00 00         nop                 62.5ns
11 98         cbi 0x02, 1 ; 2
90 91 02 01   lds r25, 0x0102
85 fd         sbrc  r24, 5
90 95         com r25
91 70         andi  r25, 0x01 ; 1
90 93 00 01   sts 0x0100, r25
11 9a         sbi 0x02, 1 ; 2
00 00         nop
```

### CODE REVIEW

**Comment by XDA-Bam** [comment]
Having such a critical function change its default behaviour seems like a risky move. I get that the recent compiler switch did exactly that under some circumstances (e.g. display timings). But delays touch much more than just display timings. Why not keep the default as round down and introduce `DELAY_ROUND_UP` and `DELAY_ROUND_CLOSEST` as alternatives?

Then, we can still change all delays relevant to LCD timings by manually switching them over to `DELAY_ROUND_UP`, if that should be necessary.

**Comment by descipher** [comment]
> Having such a critical function change its default behaviour seems like a risky move. I get that the recent compiler switch did exactly that under some circumstances (e.g. display timings). But delays touch much more than just display timings. Why not keep the default as round down and introduce `DELAY_ROUND_UP` and `DELAY_ROUND_CLOSEST` as alternatives?
> 
> Then, we can still change all delays relevant to LCD timings by manually switching them over to `DELAY_ROUND_UP`, if that should be necessary.

Yes that's a safer default. This will need lots of testing as expected.

**Comment by descipher** [comment]
Should be lot's of discussion anyway, I can only test a limited number of boards. But this effort is to follow what the avr-libc default is. It's very unlikely that a small additional delay is going to be worse than a shorter delay based on what's defined for ST7920 delays on AVR's.

**Comment by descipher** [comment]
There are 5 non ST7920 AVR based uses of DELAY_NS()
The only call that may be of some concern is this:
```cpp
#if MINIMUM_STEPPER_PRE_DIR_DELAY > 0
  #define DIR_WAIT_BEFORE() DELAY_NS(MINIMUM_STEPPER_PRE_DIR_DELAY) // <- it's set to 200ns which is actually now 188
#else
  #define DIR_WAIT_BEFORE()
#endif
```
Negative effect = +62.5ns, 
I have no observable behavior change with my printer testing.

Then there is this one .. lol , it needs 100ns based on the spec sheet, but its getting 62.5ns.
```cpp
    #if NO_THERMO_TEMPS
      MAX6675_WRITE(LOW);  // enable TT_MAX6675
      DELAY_NS(100);       // Ensure 100ns delay
    #endif
```
Other than those there does not appear to be cause for concern.

**Comment by thinkyhead** [comment]
In cleanup I tweaked the macros to skip using `float` — even though 99.9% of the time these will be calculated at compile-time — because they come out a little neater. Presumably a "`ceil`" that can handle as little as 0.001 remainder should be okay.

**Comment by descipher** [comment]
Looks even better with adding math deps! Thanks.

**Pull request merged**
