### PR TITLE
Adafruit Grand Central M4

### PR DESCRIPTION
**Pull request by GMagician**
Here is my first attempt to integrate AGCM4 board into Marlin.

I posted this just to see how far is this code from "good" to be added.

At present I don't have any shield so I can't test some things so I'll try to list here what it seems to work:
- EEprom using SoC SmartEEprom feature
- OnBoard SD (block transfer use DMA inside library)
- Digital I/O (+ soft PWM)
- Analog I/O (temperatures reading) using DMA
- USB serial
- Debug pins
- M100
What's not tested but may work:
- serial via UART
- SPI connected device when SD is not "onboard"
What's not implemented:
- Fast PWM
- Soft SPI
- Emergency parser
- LCD
- Servo

Things I don't like but I can't solve...dynamic memory allocation
USB and DMA use memory allocation. DMA uses also interrupts (low priority but isr disable all interrupts)
In my previous implementation I optimized DMA for ADC but I realized after all my work that SPI was not working because of this (not a good use of DMA in spi block transfer since it waits till end of DMA before exit function). I opted to use library DMA handling to preserve the use of DMA for other future purposes.

Finally, I prepared pin for RuRamps4d, this shield has a limit on sd detection when used lcd sd. Such pin is used by SPI itself (MOSI) to use it cable must be patched to avoid shortcircuit.
Ramps-FD should be fully compatible but V1 is "dangerous" and AFAIK v2 is not on the wild

Waiting for feedback

### CODE REVIEW

**Comment by GMagician** [comment]
I forgot.. to use On SoC Eeprom, some Soc programmig is required. EEprom size may be programmed but sold boards have set  its size to 0.
Here is a link to a sketch ready to reprogram size: https://github.com/GMagician/SAMD51-SmartEEprom-Activator
It must be uploaded and using a console (eg arduino ide console) type 'SetSize nnnn' to set size.
Once set Marlin may be uploaded and EEprom will be used only when no other EEprom is available (eg on shield eeprom)

**Comment by thisiskeithb** [comment]
Oops. You edited the default configs in the /Marlin folder. Those changes should be in a subfolder of /config/examples/ instead.

**Comment by GMagician** [comment]
> Oops. You edited the default configs in the /Marlin folder. Those changes should be in a subfolder of the /config/examples/ instead.

You're right, this was my config to test...default must be restored before merge. There is no "default board" so I don't know if any "example" must be done at all

**Comment by thisiskeithb** [comment]
MKS/Makerbase and FYSETC have some configs for their standalone boards, but I don't think example configs are required if the `MOTHERBOARD` define is the only change to get a board up and running.

**Comment by GMagician** [comment]
Last forced push restore default config files

**Comment by thisiskeithb** [comment]
> I forgot.. to use On SoC Eeprom, some Soc programmig is required. EEprom size may be programmed but sold boards have set its size to 0.
> Here is a link to a sketch ready to reprogram size: https://github.com/GMagician/SAMD51-SmartEEprom-Activator
> It must be uploaded and using a console (eg arduino ide console) type 'SetSize nnnn' to change it.
> Once set Marlin may be uploaded and EEprom will be used only when no other EEprom is available (eg on shield eeprom)

It may be helpful to include an example config/folder with a readme explaining this.

**Comment by GMagician** [comment]
> It may be helpful to include an example config/folder with a readme explaining this.

When installed sketch will display in console help to properly use it...
By the way just type 'SetSize 2048' on console to get 2Kb eeprom size

**Comment by thinkyhead** [comment]
I added a `#warning` about the SmartEEPROM. Please review the last commit to see if it makes sense.

**Comment by GMagician** [comment]
> I added a #warning about the SmartEEPROM

SmartEEprom is not used when SPI or IC2 eeprom is enabled, hence this warning should be dependent on them.
By the way even if on board eeprom is enable, it will report 0 size and user will get such information...or not?
Surely this warning may help somebody and may annoy others (have to change sanity and keep a custom version of it)

**Comment by thinkyhead** [comment]
Another option is to make an example config for the board and put an `#error` in there as a reminder, which must be un-commented to continue. What we mainly want to prevent is a lot of people running to support, so really any method of making the user fully aware of requirements will work.

**Comment by GMagician** [comment]
> What we mainly want to prevent is a lot of people running to support

I understand. Warning may be valid for such purpose

**Pull request merged**
