### PR TITLE
Tevo Michelangelo configuration

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Initial Tevo Michelangelo config ported & updated from [Tevo's Michelangelo repo](https://github.com/tevo3d/Tevo-Michelangelo).

### Related Issues

None.

Also, the original bootscreen was recreated from scratch based on video/review screenshots & cleaned up:
tevo-michelangelo-bootscreen

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I'm re-creating the custom bootscreen based on [video/review screenshots](https://i.imgur.com/wM07Yx3.png) (it's not in Tevo's Michelangelo repo), so I'll update the PR once I'm done with my custom pixel art 🤣

**Comment by thisiskeithb** [comment]
```
exit status 1
/var/folders/tz/prll45qj47q__g_g5t2mmw4m0000gn/T/arduino_build_77917/sketch/src/lcd/dogm/ultralcd_DOGM.cpp: In function 'void draw_custom_bootscreen(const u8g_pgm_uint8_t*, bool)':
/var/folders/tz/prll45qj47q__g_g5t2mmw4m0000gn/T/arduino_build_77917/sketch/src/lcd/dogm/ultralcd_DOGM.cpp:111:87: warning: large integer implicitly truncated to unsigned type [-Woverflow]
                            top = (LCD_PIXEL_HEIGHT - (CUSTOM_BOOTSCREEN_BMPHEIGHT)) / 2;
```

It looks like the bootscreen is causing compiling issues which is likely related to https://github.com/MarlinFirmware/MarlinDocumentation/issues/233.

**Comment by thinkyhead** [comment]
> It looks like the bootscreen is causing compiling issues…

Seems like it's being over-cautious. We know all these values will be less than 256 for `u8g_uint_t`. Guaranteed:
- `0 < CUSTOM_BOOTSCREEN_BMPWIDTH <= 128`
- `0 < CUSTOM_BOOTSCREEN_BMPHEIGHT <= 64`
- `0 < LCD_PIXEL_WIDTH <= 128` (DOGM always 128)
- `0 < LCD_PIXEL_HEIGHT <= 64` (DOGM always 64)

If for some reason a bitmap's width is incorrect, the calculated height could end up too large, giving that warning. An explicit cast can be used to suppress the warning.

**Comment by thisiskeithb** [comment]
I pulled down the updated `_Bootscreen.h` and `ultralcd_DOGM.cpp` changes and while it compiles fine, the bootscreen is garbled:


> If for some reason a bitmap's width is incorrect, the calculated height could end up too large, giving that warning.

I just verified the bitmap size within Photoshop as well as the exported image & it is indeed 128x64 pixels. I've attached it just in case I'm missing something: [tevo-michelangelo.bmp.zip](https://github.com/MarlinFirmware/Marlin/files/3401737/tevo-michelangelo.bmp.zip)

If losing a bootscreen is the only thing stopping this config from being merged, I think it'd be OK to drop for now since I can always add it later.

**Comment by thisiskeithb** [comment]
The issue was this line:

```c++
#define CUSTOM_BOOTSCREEN_BMPWIDTH  120
```

It should be 128:



This PR should be ready to merge now!

**Comment by thinkyhead** [comment]
Thanks! It surprises me how many popular machines that run Marlin we have not filled in.

**Pull request merged**
