### PR TITLE
MAX7219 followup

### PR DESCRIPTION
**Pull request by thinkyhead**
Followup to #7563

- Apply coding standards, fix spacing, formatting, spelling
- Use bitwise macros where possible
- Use FastIO `WRITE` for `digitalWrite`, `SET_OUTPUT` for `pinMode`
- Fix `Max7219DebugLEDs.h` header file include conditionals
- Use shorter link to eBay listing
- Apply Marlin conventions to pin names
- Add new options to the main `Configuration_adv.h` file
- Reduce verbosity where possible

### CODE REVIEW

**Comment by Roxy-3D** [comment]
All good!  Even the ternary operators.

**Comment by thinkyhead** [comment]
All those trips to Burning Man have clearly infected my code style.

**Comment by Roxy-3D** [comment]
There are problems....  Let's not merge the changes until I get everything fixed....

**Comment by thinkyhead** [comment]
Of course. Please advise what needs fixin'.

**Comment by Roxy-3D** [comment]
uint's don't work for this:
```cpp
  void Max7219_init() {
    int8_t i, x, y;
...
    for (x = 7; x >= 0; x--) {
      for (y = 0; y <= 7; y++) {
        Max7219_LED_Off(x, y);
        delay(2);
      }
    }
  }
```
#if ENABLED() doesn't  generate any code if the argument has a value.  It only works if the argument is a #define with no value
```cpp
  void Max7219_idle_tasks() {
    #if ENABLED(MAX7219_DEBUG_PRINTER_ALIVE)
    #endif

    #ifdef ENABLED(MAX7219_DEBUG_STEPPER_HEAD)
    #endif

    #ifdef ENABLED(MAX7219_DEBUG_STEPPER_TAIL)
    #endif

    #ifdef MAX7219_DEBUG_STEPPER_QUEUE
    #endif
  }
```
And I don't know what is wrong with the replacement code, but nothing worked until this function was restored:
```cpp
  void Max7219_PutByte(uint8_t data) {
    uint8_t i = 8;
      while(i > 0) {
        digitalWrite( MAX7219_CLK_PIN, LOW);  // tick
        if (data & 0x80)                      // check bit
          digitalWrite(MAX7219_DIN_PIN,HIGH); // send 1
        else
          digitalWrite(MAX7219_DIN_PIN,LOW);  // send 0
        digitalWrite(MAX7219_CLK_PIN, HIGH);  // tock
        data = data << 0x01;
        --i;                                  // move to lesser bit
    }
  }
```
The non-working replacement code is:
```cpp
  void Max7219_PutByte(uint8_t data) {
    for (uint8_t i = 8; --i;) {
      WRITE(MAX7219_CLK_PIN, LOW);       // tick
      WRITE(MAX7219_DIN_PIN, data & 0x80 ? HIGH : LOW);  // send 1 or 0 based on data bit
      WRITE(MAX7219_CLK_PIN, HIGH);      // tock
      data <<= 1;
    }
  }
```
I don't see the problem...   But it does not work.   I don't know why.   But with that said, the code that uses digitalWrite() does work.

With the exception of the MAX7219_DEBUG_PRINTER_ALIVE feature, the sub-functions within the Max7219_idle_tasks() function do not work.   Each option has some problem that makes it not show up on the display.  But restoring the previous function gets them all back:
```cpp
  void Max7219_idle_tasks() {
    #ifdef MAX7219_DEBUG_PRINTER_ALIVE
      static int debug_cnt = 0;
      if (debug_cnt++ > 100) {
        Max7219_LED_Toggle(7, 7);
        debug_cnt = 0;
      }
    #endif

    #ifdef MAX7219_DEBUG_STEPPER_HEAD
      Max7219_Clear_Row(MAX7219_DEBUG_STEPPER_HEAD);
      Max7219_Clear_Row(MAX7219_DEBUG_STEPPER_HEAD + 1);
      if ( planner.block_buffer_head < 8)
        Max7219_LED_On( planner.block_buffer_head, MAX7219_DEBUG_STEPPER_HEAD);
      else
        Max7219_LED_On( planner.block_buffer_head-8, MAX7219_DEBUG_STEPPER_HEAD+1);
    #endif

    #ifdef MAX7219_DEBUG_STEPPER_TAIL
      Max7219_Clear_Row(MAX7219_DEBUG_STEPPER_TAIL);
      Max7219_Clear_Row(MAX7219_DEBUG_STEPPER_TAIL + 1);
      if ( planner.block_buffer_tail < 8)
        Max7219_LED_On( planner.block_buffer_tail, MAX7219_DEBUG_STEPPER_TAIL );
      else
        Max7219_LED_On( planner.block_buffer_tail-8, MAX7219_DEBUG_STEPPER_TAIL+1 );
    #endif

    #ifdef MAX7219_DEBUG_STEPPER_QUEUE
      static int16_t last_depth=0, current_depth;
      uint8_t i;
      current_depth = planner.block_buffer_head - planner.block_buffer_tail;
      if (current_depth != last_depth) {  // usually, no update will be needed.

        if ( current_depth < 0 )
          current_depth += BLOCK_BUFFER_SIZE;

        if ( current_depth >= BLOCK_BUFFER_SIZE )
          current_depth = BLOCK_BUFFER_SIZE;

        if ( current_depth > 16 )         // if the BLOCK_BUFFER_SIZE is greater than 16 two lines
          current_depth = 16;             // of LED's is enough to see if the buffer is draining

        if ( current_depth < last_depth )
          for(i=current_depth; i<=last_depth; i++) {   // clear the highest order LED's
            if ( i & 1)
              Max7219_LED_Off(i>>1, MAX7219_DEBUG_STEPPER_QUEUE+1);
            else
              Max7219_LED_Off(i>>1, MAX7219_DEBUG_STEPPER_QUEUE+0);
          }
        else
          for(i=last_depth; i<=current_depth; i++) {   // light up the highest order LED's
            if ( i & 1)
              Max7219_LED_On(i>>1, MAX7219_DEBUG_STEPPER_QUEUE+1);
            else
              Max7219_LED_On(i>>1, MAX7219_DEBUG_STEPPER_QUEUE+0);
          }

        last_depth = current_depth;
      }
    #endif
  }
```

**Comment by thinkyhead** [comment]
Awesome possum. I also noticed this weird line:
```cpp
    Max7219(max7219_reg_intensity, 0x01 & 0x0F); // the first 0x0F is the value you can set
```
0x01 & 0x0F will always be 0x1. Maybe that's just a convention of using the `max7219_reg_intensity` option…?

**Comment by thinkyhead** [comment]
> I don't see the problem... But it does not work. I don't know why. But with that said, the code that uses digitalWrite() does work.

`digitalWrite` is much slower, so it's possible that there needs to be a particular delay between `WRITE(MAX7219_CLK_PIN, LOW)` and `WRITE(MAX7219_CLK_PIN, HIGH)`. I'm looking at the MAX7219 spec sheet.

**Comment by Roxy-3D** [comment]
Yes...  That is from the Max7219 sample library.  They always turned the display on at full brightness, but  the 0x0f is to force what ever value the person used to be within range....   We can just put it at 0x01.

**Comment by Roxy-3D** [comment]
I'll try it with delays right now....   I'll know if that helps in a 3 or 4 minutes.

No...  Somehow...  This code is **_NOT_** equivilent...   The LED's end up in a chaotic state.  And 3x 10ms  delays should be excessive:
```cpp
  void Max7219_PutByte(uint8_t data) {
    for (uint8_t i = 8; --i;) {
      WRITE(MAX7219_CLK_PIN, LOW);       // tick
      delay(10);
      WRITE(MAX7219_DIN_PIN, data & 0x80 ? HIGH : LOW);  // send 1 or 0 based on data bit
      delay(10);
      WRITE(MAX7219_CLK_PIN, HIGH);      // tock
      delay(10);
      data <<= 1;
    }
  }
```

**Comment by thinkyhead** [comment]
I think I'll order one of those boards. I'm enjoying adding lights and other realtime indicators.

**Comment by Roxy-3D** [comment]
The boards are designed to be cascaded...  Other than it burns more CPU cycles...  you can just make a big string of them.    But the thing is, these boards really are helpful because it gives you lots of LED's to light up when different things happen.   So even without an In Circuit Emulator...  You can get a lot of information about what is happening.

**Comment by thinkyhead** [comment]
Nice! I see from the spec sheet there is some timing to consider. I'm not sure what the length of a "clock cycle" is on this chip.
```
For the MAX7219, serial data at DIN, sent in 16-bit
packets, is shifted into the internal 16-bit shift register
with each rising edge of CLK regardless of the state of
LOAD. For the MAX7221, CS must be low to clock data
in or out. The data is then latched into either the digit or
control registers on the rising edge of LOAD/CS.
LOAD/CS must go high concurrently with or after the
16th rising clock edge, but before the next rising clock
edge or data will be lost. Data at DIN is propagated
through the shift register and appears at DOUT 16.5
clock cycles later. Data is clocked out on the falling
edge of CLK. Data bits are labeled D0–D15 (Table 1).
D8–D11 contain the register address. D0–D7 contain
the data, and D12–D15 are “don’t care” bits. The first
received is D15, the most significant bit (MSB).
```

**Comment by Roxy-3D** [comment]
Yeah...  but 10ms   (or actually 20 ms because there are two of those delays before the clock toggles...) should be plenty.   And all of that clocked out stuff is talking about driving a 2nd matrix.   Which isn't happening right now.

**Comment by thinkyhead** [comment]
Righto. I see that the CLK pin frequency is what determines the length of a cycle. Also…
```
Serial-Clock Input. 10MHz maximum rate. On CLK’s rising edge, data is shifted into the internal
shift register. On CLK’s falling edge, data is clocked out of DOUT. On the MAX7221, the
CLK input is active only while CS is low.
```
I'm going out on a limb and guessing most Arduinos will tend to drive it at 8MHz.

So, probably two `nop` lines count as one cycle. A delay of 16.5 cycles (inferring from the time required to pass each bit from DIN to DOUT) would correspond to 33 AVR (`nop`) cycles, or 33/16000000 seconds. With such a short pulse time, it seems like even a single `delay(1)` might be enough to make it work. But maybe the real delay time does need to be longer.

**Comment by thinkyhead** [comment]
> for (x = 7; x >= 0; x--) {

Fixed.

>  #if ENABLED(MAX7219_DEBUG_PRINTER_ALIVE)

Hmm… I changed those lines yesterday to use `#ifdef`. The `ALIVE` option is a switch. I'm not sure where `#ifdef ENABLED(...)` is coming from.

> nothing worked until this function was restored

I've added delays which we can tweak until the minimum required values are found.

> With the exception of the MAX7219_DEBUG_PRINTER_ALIVE feature, the sub-functions within the Max7219_idle_tasks() function do not work.

Given the other outmoded lines, you might be looking at older code. Can you confirm this is still the case with the latest code in this PR's branch (also with added delays)? (Although I'm patching this PR, I keep rebasing it to keep it down to only a few commits.)

**Comment by thinkyhead** [comment]
Just fixed a silly bug in PutByte. Should be better now. Might not even need the delays!

**Comment by p3p** [comment]
I wrote a driver for arbitrary arrays of these things long ago with scrolling text and animation support, they are fun to play with.

**Comment by Roxy-3D** [comment]
I'll try the latest version in the morning...    And if it works, I'll move it all to the 32-bit branch.   That is the real reason behind doing this.

**Comment by Roxy-3D** [comment]
> I wrote a driver for arbitrary arrays of these things long ago with scrolling text and animation support, they are fun to play with.

Yeah...   I was trying to do fonts with decending letter things....  But 8x8 is hard to do good looking decenders.

**Comment by Roxy-3D** [comment]
> I'll try the latest version in the morning... And if it works, I'll move it all to the 32-bit branch. That is the real reason behind doing this.

**_Harvey Update:_** 
It will be several days before I can do anything on this.   Everything is flooded, and power is out.   But the worst part of it all is the internet is gone.   Aaaarrrgh.....

**Comment by thinkyhead** [comment]
> And if it works, I'll move it all to the 32-bit branch. That is the real reason behind doing this.

You can skip that step. All new code will get merged into the 32-bit branch when I rebase the `bugfix-2.0.x` branch onto the latest `bugfix-1.1.x` branch. Of course, if you want to test it in a copy, that'll work. It just shouldn't be merged directly into `bugfix-2.0.x` if it's also in `bugfix-1.1.x`.

**Comment by thinkyhead** [comment]
> I wrote a driver for arbitrary arrays of these things long ago with scrolling text and animation support, they are fun to play with.

Nice. I guess an uppercase-only font, plus numbers and some punctuation is only about 300 bytes, so it's not too expensive either.

**Pull request merged**
