### PR TITLE
ignore visual studio files

### PR DESCRIPTION
**Pull request by robbycandra**
Ignore Visual Studio files

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks! Good addition.

**Comment by thinkyhead** [comment]
Oops. Reverting, because it was targeted at the wrong branch. Please submit PRs to `RCBugFix`.

**Comment by robbycandra** [comment]
Hi @thinkyhead, already submit new PR on gitignore and USE_RAW_KINEMATICS.
Sorry for wrong branch.

OOT: Do you plan to develop Marlin for arduino Duo ?

**Comment by thinkyhead** [comment]
> Do you plan to develop Marlin for arduino Duo?

Yes! As part of the 1.2.x effort. We started a 32-bit branch already (`32-Bit-RCBugFix-new`), which I'm periodically rebasing to keep in sync.

**Pull request merged**
