### PR TITLE
Add Tronxy v10

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Add basic support for BOARD_TRONXY_V10 
Code extracted from https://drive.google.com/file/d/1nsQXs2d6fvkILCa064XXZ7pKlgU7IdhZ/view?usp=sharing and modified

### Requirements

#define MOTHERBOARD BOARD_TRONXY_V10

### Benefits

Board is now supported

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/23761

### Notes:
This has now had basic functionality tested

### CODE REVIEW

**Comment by thinkyhead** [comment]
Brought pins up to date and cleaned up the variant. Please re-check. There are a few pins defined in the file which are not used anywhere in Marlin, so we may be able to remove those.

**Comment by ellensp** [comment]
Board has a Z2 plug, not a E3 plug Which is why I left it as

```
#if NUM_Z_STEPPERS > 1
  #define Z2_ENABLE_PIN                     PF7
  #define Z2_STEP_PIN                       PF6
  #define Z2_DIR_PIN                        PF4
#elif EXTRUDERS > 2
  #define E2_ENABLE_PIN                     PF7
  #define E2_STEP_PIN                       PF6
  #define E2_DIR_PIN                        PF4
#endif
```

https://i0.wp.com/bangshaboodle.com/wp-content/uploads/2022/04/29665-l6hdk6.jpg

**Comment by ellensp** [comment]
Why did you flip "variant": "MARLIN_TRONXY_STM32f446Z" to "variant": "MARLIN_F446Zx_TRONXY" ?
If you search for example variants you find
    "variant": "MARLIN_BIGTREE_OCTOPUS_V1"
    "variant": "MARLIN_BTT_SKR_SE_BX"
    "variant": "MARLIN_BIGTREE_OCTOPUS_PRO_V1_F429"
    "variant": "MARLIN_BIGTREE_SKR_PRO_11"
    "variant": "MARLIN_BIGTREE_BTT002"
    "variant": "MARLIN_CREALITY_STM32F401RC"
    "variant": "MARLIN_BIGTREE_BTT002"
    "variant": "MARLIN_BIGTREE_GTR_V1"
    "variant": "MARLIN_FYSETC_CHEETAH_V20"
    "variant": "MARLIN_FYSETC_S6"

the ones that have company names are always the second keyword, now you want it to be the third?

same with env name
you switched up env:tronxy_stm32f446 to be env:STM32F446_tronxy  why?

more examples 
stm32f4.ini:[env:BIGTREE_SKR_2_F429_USB_debug]
stm32f4.ini:[env:BIGTREE_OCTOPUS_V1]
stm32f4.ini:[env:BIGTREE_OCTOPUS_V1_USB]
stm32f4.ini:[env:BIGTREE_OCTOPUS_PRO_V1_F429]
stm32f4.ini:[env:BIGTREE_OCTOPUS_PRO_V1_F429_USB]
stm32f4.ini:[env:mks_robin_pro2]
stm32f4.ini:[env:mks_robin_nano_v3]
stm32f4.ini:[env:mks_robin_nano_v3_usb_flash_drive]
stm32f4.ini:[env:mks_robin_nano_v3_usb_flash_drive_msc]
stm32f4.ini:[env:mks_robin_nano_v3_1]

all company name then board name

**Comment by thinkyhead** [comment]
> Why did you flip "variant": "MARLIN_TRONXY_STM32f446Z" to "variant": "MARLIN_F446Zx_TRONXY" ?

Either we are gradually in the process of preferring this format, or we are not. More recent changes seem to be going in this direction. Other than making it perhaps easier to sift through the enormous list of environments under the PlatformIO sidebar interface, what is the special advantage of putting the make/model name ahead of the processor variant? Personally, when looking an envs / variants list alphabetically, I like related processors from different vendors to appear next to one another, rather than unrelated processors from the same vendor to be next to one another.

**Comment by ellensp** [comment]
I personally think the naming convention body, branch then specific  makes much more sense.

body being Marlin
branch being manufacturer
specific the board

**Comment by pessimism** [comment]
I have an X5SA-PRO with this new Tronxy board and am willing to work with you to complete whatever pre-merge testing is needed.

**Comment by ellensp** [comment]
@pessimism you need try this and check all basic functions

Compile this and upload it (do not expect the lcd to work, it wont)

do the endstops work?  (check with M119)
does it read room temperature (M105) If you warm the hotend say with a hair dryer, does the temperature rise? 
does heating work?  
do the fan work?
does each axes work?  

These are the first stages...

**Comment by MrFrickinFixit** [comment]
I have an X5SA with this board as well. It was sent to me as a replacement for the CXY-V6-191017 board. Not my printer is dead in the water because of their firmware incompatibility with my printer mods like a BLTouch. I tried to compile ellensp's firmware that was shared. 

Getting this error at compile.  `d:/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: Marlin/Tronxy\libTronxy.a(Tronxy.cpp.o): in function `EXTI1_IRQHandler':
F:\YSZ\work\3Marlin-2.0.9.2/Marlin\Tronxy/Tronxy.cpp:461: multiple definition of `EXTI1_IRQHandler'; .pio/build/tronxy_stm32f446/SrcWrapper/src/stm32/interrupt.cpp.o:D:\.platformio\packages\framework-arduinoststm32\libraries\SrcWrapper\src\stm32/interrupt.cpp:339: first defined here`

**Comment by MrFrickinFixit** [comment]
> @pessimism you need try this and check all basic functions
> 
> Compile this and upload it (do not expect the lcd to work, it wont)
> 
> do the endstops work? (check with M119) does it read room temperature (M105) If you warm the hotend say with a hair dryer, does the temperature rise? does heating work? do the fan work? does each axes work?
> 
> These are the first stages...

I have an X5SA with this board in it. I've tried compiling your branch, but I get errors regarding the display. Using #define TFT_TRONXY_X5SA and #define TFT_COLOR_UI, which worked with the previous board.

**Comment by ellensp** [comment]
@MrFrickinFixit This is motherboard support only, there is zero support for the display!
disable the display.

**Comment by MrFrickinFixit** [comment]
> @MrFrickinFixit This is motherboard support only, there is zero support for the display! disable the display.

Not a problem. Will do.

**Comment by MrFrickinFixit** [comment]
> @pessimism you need try this and check all basic functions
> 
> Compile this and upload it (do not expect the lcd to work, it wont)
> 
> do the endstops work? (check with M119) does it read room temperature (M105) If you warm the hotend say with a hair dryer, does the temperature rise? does heating work? do the fan work? does each axes work?
> 
> These are the first stages...

Disabled the display. 
Compile - good. 
End stops - good. 
Hot end and bed temps - good. 
Hot end and part cooling fans - good.
Movement on all axes - good. 

I have Octoprint connected so I can get reports through the console.

**Comment by MrFrickinFixit** [comment]
I misread the state of the Z_MIN pin as it was scrolling by and did a double check on the end stops. X and Y were good, Z was not.
In the pins file line 102 I changed `#define Z_STOP_PIN                        PC13` to `#define Z_MIN_PIN                         PE3`. Now the Z_MIN works.

**Comment by ellensp** [comment]
@MrFrickinFixit can you take a clear high res image of the board?  as all I can find are low and out of focus

Also the pin should be what is labeled as z endstop on the pcb, not just what they plug it in to...
So can you confirm which plugs are PE3 and PC13 

(the pins files was from tronxy...)

**Comment by MrFrickinFixit** [comment]
> @MrFrickinFixit can you take a clear high res image of the board? as all I can find are low and out of focus
> 
> Also the pin should be what is labeled as z endstop on the pcb, not just what they plug it in to... So can you confirm which plugs are PE3 and PC13
> 
> (the pins files was from tronxy...)

I can take a high-res image, but it will be a little while. I think I see the problem though. There are multiple versions of the v10 board and the v6 board, all very similar and using the 446 MCU. It looks as if Tronxy just makes changes to the board depending on the printer that the board is going in. The source you shared via Google drive, the pins file is calling it `#define Z_MIN_PIN PE3`. Please see the link. [https://www.tronxy3d.com/products/tronxy-silent-mainboard-with-wire-cable-for-d01-plus-xy-3-pro-v2?variant=43281705500916](url) Some versions of the board use the ribbon cable and some use a header depending on architecture. Mine uses the large ribbon cable connection. The X5SA series CoreXY machines connect the hardware up top to a daughter board, which is connected to the mainboard via ribbon cable.

**Comment by ellensp** [comment]
Yea that is tiny, you can not even read any connector labels. And that is a v6, not a v10

**Comment by MrFrickinFixit** [comment]
> Yea that is tiny, you can not even read any connector labels. And that is a v6, not a v10

Have you looked here? `https://tronxy.fandom.com/wiki/TronXY_Mainboard_Documentation#TronXY_CXYV6-191121/CXYV10-20210309_(STM32F446_based)` Looking at my old board it's defined as ZSTOP in the same location.

**Comment by thinkyhead** [comment]
I did a little merge and cleanup. Do you still need to verify some pins, sort out the meaning of `THROAT_FAN 2`, or anything else before this is merged?

**Comment by ellensp** [comment]
Still trying to ascertain which io pin is actually on Z endstop   it is  either PE3 and PC13

Ie is the testers machine actually using z endstop plug for z endstop (in which case it is PE3) 

Of is the machine just using a different port ?

**Comment by MrFrickinFixit** [comment]
> Still trying to ascertain which io pin is actually on Z endstop it is either PE3 and PC13
> 
> Ie is the testers machine actually using z endstop plug for z endstop (in which case it is PE3)
> 
> Of is the machine just using a different port ?

I can tell you for certain that on my printer nothing is plugged into the ZSTOP header. The ZSTOP, which is also the bed probe Z_MIN is connected to the board via the 30pin ribbon cable. As I said, I think they have different versions based on architecture.

**Comment by ellensp** [comment]
https://user-images.githubusercontent.com/24321717/154693985-d0d17d6f-27cb-4f21-8c3e-63d8bda381c1.jpg 
Shows that the z endstop is infact PC13 and PE3 is the probe,

@MrFrickinFixit Your printer seems to be using the probe port. for homing z, im updateing so you can override pins file for
Z_MIN_PROBE_PIN and Z_STOP_PIN in Configuration.h

**Comment by MrFrickinFixit** [comment]
> https://user-images.githubusercontent.com/24321717/154693985-d0d17d6f-27cb-4f21-8c3e-63d8bda381c1.jpg Shows that the z endstop is infact PC13 and PE3 is the probe,
> 
> @MrFrickinFixit Your printer seems to be using the probe port. for homing z, im updateing so you can override pins file for Z_MIN_PROBE_PIN and Z_STOP_PIN in Configuration.h

Ah! That makes perfect sense. Thanks for clarifying.

**Comment by ellensp** [comment]
@thinkyhead This is good to go.

**Comment by 2-k** [comment]
I got it, my final problem was I had spaces in the folder names. I commented out the exit1 error then used the core_dir command from the original TronXY files and finally put everything onto D: drive. Apparently my other errors where ghost from not using single word folder names.

src_dir      = Marlin
core_dir     = D:/.platformio // worked after adding this and putting Marlin folder on D:
boards_dir   = buildroot/share/PlatformIO/boards

New I was just overlooking something simple. Now after years all my Tron XY printers can finally have a smart filament sensor.

Thank you much appreciated.

**Pull request merged**
