### PR TITLE
[1.1.x] Fix bad font reduction issue

### PR DESCRIPTION
**Pull request by GMagician**
Languages that need extended letters on AVR are bypassed because of `LANGUAGE_EN_H`.
This will fix such issue

### CODE REVIEW

**Comment by thinkyhead** [comment]
Are you sure this is actually an issue? The only thing this seems to do is provide a language `.h` file with the `#ifndef` clause removed from the start. The only difference being that the file could be included more than once from the same source.

Clearly you need to provide a better explanation of the problem.

**Comment by GMagician** [comment]
Yes is an issue, in Italian I can't see any accented letter. 
The cause is that english language is added always as a fallback language but include define LANGUAGE_EN_H. Such define will activate font reduction (see #8095).
My idea is that fallback include has only messages and English contains only define

**Comment by GMagician** [comment]
In #8095 the define set 'not_extended_ISO10646_1_5x7' to true and on __AVR__ systems it will use reduced font

**Comment by GMagician** [comment]
Note that fallback_language, even if included more than once doesn't do anything (messages are not redefined). Maybe contents may be enclosed by an #ifndef fallback_language

**Comment by GMagician** [comment]
For a better fix maybe in English can be removed also '#include fallback' since this is done by default

**Comment by AnHardt** [comment]
You are right.
The limitation to AVR systems is wrong (function is system independent but saving memory makes most sense for AVRs),
as well as the criteria the decision is made on, is suboptimal.
I'll try to prepare a decision based on the use of the mapper.

**Comment by GMagician** [comment]
@AnHardt  have I to close these PR?

**Comment by GMagician** [comment]
@AnHardt I checked some languages.
Strange that _ES doesn't use such mapper because as I know Spanish uses so many accented letters.
Also Catalan uses accented letters but are not used in translation even if mapper is defined.
Finally I don't know anything about Galician but I think it is another Spanish language and also that should use accented letters (but not present in translation)

**Comment by GMagician** [comment]
While waiting for a definitive fix I posted something better

**Comment by AnHardt** [comment]
An immediate fix is needed right now.
Go for it.
It works.
What i am currently trying looks more like a major rework of the font/language system - so will last a while.

**Comment by thinkyhead** [comment]
> Such define will activate font reduction

Then the method of invoking "font reduction" is incorrect, and I shouldn't have merged it without a fix. Sorry! One thing it could do is to look only at the primary language, since English is always included. However since some languages have hyphens in the name this can't be done easily with preprocessor directives. I will take a stab at fixing this without needing to have a "fallback."

**Comment by thinkyhead** [comment]
Try this simple change and see if it works for you…
```cpp
#define en 1234

#define not_extended_ISO10646_1_5x7 (LCD_LANGUAGE == en \
                                  || defined(LANGUAGE_AN_H) \
                                  || defined(LANGUAGE_ES_H) \
                                  || defined(LANGUAGE_EU_H) \
                                  || defined(LANGUAGE_FR_H) \
                                  || defined(LANGUAGE_GL_H) \
                                  || defined(LANGUAGE_NL_H) \
                                  || defined(LANGUAGE_PL_HD44780_H) \
                                  || defined(LANGUAGE_PT_H) \
                                  || defined(LANGUAGE_PT_BR_H))
```
…or…
```cpp
#define an 1234
#define en 1234
#define es 1234
#define eu 1234
#define fr 1234
#define gl 1234
#define nl 1234
#define pt 1234

#define not_extended_ISO10646_1_5x7 (LCD_LANGUAGE == 1234 \
                                  || defined(LANGUAGE_PL_HD44780_H) \
                                  || defined(LANGUAGE_PT_BR_H))
```

**Comment by GMagician** [comment]
@thinkyhead English is a fallback language and I think it's a good solution for incomplete languages, also dotnet does something similar (N.B. is fallback because it is always included after every other language in "language.h").
In original code you had "language_en.h" included twice, because of EN define and because it is also fallback language (ok you have ifndef at start of .h that resolve any issue).
I think that having a new file for fallback_language and an empty english header can be left also when a final solution has been found.

**Pull request closed without merging**
