### PR TITLE
[2.0.x] Allow override of RAMPS CS Pins

### PR DESCRIPTION
**Pull request by thinkyhead**
Based on #9281 by @floyd871

### CODE REVIEW

**Comment by tcm0116** [comment]
I think this should be included in most, if not all, of the pins files. In fact, it would be great if this was done for all of the pins that aren't hard-wired in a board, such as filament run-out.

**Comment by psavva** [comment]
Just for my understanding, in which use-case could the pin be defined prior to the pins file being executed?

I'm obviously missing something here

**Comment by tcm0116** [comment]
If the user defines a pin in the configuration files, then it will be
defined before the pins file.

**Comment by thinkyhead** [comment]
@psavva 
```cpp
#ifndef MARLIN_CONFIG_H
#define MARLIN_CONFIG_H

#include "fastio.h"
#include "macros.h"
#include "boards.h"
#include "Version.h"
#include "Configuration.h"
#include "Conditionals_LCD.h"
#include "Configuration_adv.h"
#include "pins.h"
#ifndef USBCON
  #define HardwareSerial_h // trick to disable the standard HWserial
#endif
#include "Arduino.h"
#include "Conditionals_post.h"
#include "SanityCheck.h"

#endif // MARLIN_CONFIG_H
```

**Pull request merged**
