### PR TITLE
G34 stepper locks

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Allow locking/unlocking individual steppers when multiple z steppers exist for manual movements.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Can you detail how it changes `G34` / `M422` and outline the new usage for the reader? The descriptions you supply may also be used in the website documentation. Thanks!

**Comment by sjasonsmith** [comment]
I'm having a little trouble understanding how to use it.

I see that I would use something like `G34 Z1` to lock and/or unlock Z1, but how do I tell it whether it is locked or unlocked?

I suppose I see two different workflows people might want with this:

- Lock only one motor
- Lock all motors except one

**Comment by sjasonsmith** [comment]
> but how do I tell it whether it is locked or unlocked?

I see, there is an `S` argument that isn't listed at the top of the G34 changes.

Lock only one motor (might be inverted?)
`G34 Z3 S1`

Lock all but one motor
```
G34 Z1 S1
G34 Z2 S1
G34 Z4 S1
```

Maybe it would make sense to expand L to allow both enabling and disabling all motors.

**Comment by thinkyhead** [comment]
I tweaked it so that you can send `L` followed by a `Z` parameter on the same line. The meaning of `L` is unlock, so you'd be just specifying a single axis to lock. Since most of the time you probably want the opposite — all axes locked with one free — it might do to expand `L` so that `L0` means unlock all and `L1` (or `L` by itself) means "lock all." And then your `Zn` indicates the reverse of that.

**Pull request merged**
