### PR TITLE
Configurable Max Accel, Max Feedrate, Max Jerk edit limits

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Allow defining maximum limits that Gcode cannot override for protection against damaging machines from invalid slicer settings. Sets limits on M201 - M205 where applicable.

Todo : Finish LCD Menus to work through callback functions

### CODE REVIEW

**Comment by robbycandra** [comment]
100 files change...

**Comment by InsanityAutomation** [comment]
Almost all config files...

**Comment by gloomyandy** [comment]
This PR seems to contain a bunch of BLTouch settings as well as the ones for the actual clamping, should it?

**Comment by InsanityAutomation** [comment]
Nope it shouldn't, vscode apparently kept a file changing branches! Saw it earlier but just got around to opening it on my laptop to fix....

**Comment by robbycandra** [comment]
Vscode is dangeruous.if we edit files and changing branch. Maybe we need to save all open files first before change branch.

**Comment by InsanityAutomation** [comment]
Yeah, I ran into a couple issues recovering a few things after git got screwed up following a battery empty / machine shutdown scenario on my laptop.... Itll be another year before it happens again lol Only reason I didnt spot it before pushing is it was midnight lol

**Comment by thinkyhead** [comment]
I don't favor having an option that makes a core command, `M201`, behave differently on different machines. Inheritors of hand-me-down printers would have no clue as to the behavior they should expect from `M201`, and that's a problem. One of the principles we try to follow in this project is to make certain that commands behave predictably from one machine to another _inasmuch as this is possible_. So I am very resistant to a change like this which only muddies the waters on the behavior of a fundamental command.

This is related to another Marlin principle: The firmware should be an obedient servant, and should not try to mitigate every possible mistake that a user or a slicer could make. We are justified to try to prevent too high a temperature for safety, but trying to prevent too high a max acceleration being set is drifting into interference territory.

**Comment by InsanityAutomation** [comment]
Any thoughts at least on setting them to very high default values and leaving it always on? For example we could try by default set them to the data type max to just prevent and overrun. The scenario im looking at here is where a slicer's default setting was to override firmware values with a number 10x too high. Vendor stock being 1.1.6, it just ignored M201 altogether. They update to anything newer and all of a sudden layer shifts and chewed up belts.

I agree machine should do what its told, but it should be within sane limits. If I asked my 1500 pickup truck to go from 0-60 in 3s, it would destroy itself if the ecu didnt limit acceleration and control shifting. But I could achieve that in a mazaratti.

**Comment by Versus3D** [comment]
I agree with InsanityAutomation. I just the other day in fact I accidentally set my slicer to 1000mms instead of 100. My printer has no "limit" set by the firmware, so when I hit print and walked away I heard a crazy sound, came running back in and saw my extruder and hot end nearly shooting off the rails because they were actually trying to move that fast. 

Limits aren't a bad thing when they can prevent accidental issues such as this.

**Comment by InsanityAutomation** [comment]
@Versus3D At the moment this doesn't touch feedrate, but that and jerk / junction deviation values would have been next. Your issue does match the extra 0 issue that inspired this though.

**Comment by robbycandra** [comment]
About this, I agree with @InsanityAutomation. Like Temperature, position and motion also have limit.

**Comment by robbycandra** [comment]
Or maybe we can give warning/confirmation screen, if user set huge value for accell. This will solve the problem too.

**Comment by Roxy-3D** [comment]
> This is related to another Marlin principle: The firmware should be an obedient servant, and should not try to mitigate every possible mistake that a user or a slicer could make. We are justified to try to prevent too high a temperature for safety, but trying to prevent too high a max acceleration being set is drifting into interference territory.

In general, I think there is broad agreement with this principle.   But there is another set of facts that should be considered.    It is my belief that 95+% of the people we see on GitHub and Discord are individuals that are 'playing' with their printers.  The people we see on GitHub and Discord are not representative to the 'real Marlin user base'.    It is my belief that 95+% of the RepRap machines with Marlin on them were made by a company and sold 'into the wild'.   We don't see the bulk of these Marlin users on GitHub or Discord.  We only see the individuals that are tweaking things on their printers.

Companies that ship machines that use Marlin as the controlling firmware have a legitimate need to control some limits.    It is fine for us as Developers to say "The machine should be a faithful servant and do what ever it is told to do."    But from a company's point of view, they need to limit some of the craziness that users put the machines through.   Just from a Customer Support perspective, it makes sense to allow the company to specify some limits that can't be breached.   If the Design Team at the company *KNOWS* a number can't be breached, it would seem advantageous to respect that number.

In slightly different words:   I think 95+% of the Marlin machines are sold to users by companies.  Companies are the 'real customer' of Marlin.   And this #define MAX_ACCELERATION_LIMIT is a simple change that helps companies give better support to their customers.

PS.  I think it would be beneficial to set the MAX_ACCELERATION_LIMIT values specified in each example Configuration.h file according to a formula.   Perhaps those values should all be 2x the DEFAULT_MAX_ACCELERATION values and default to 'not enabled'.

PSS.   Probably M503 should display the MAX_ACCELERATION_LIMIT values.

**Comment by Versus3D** [comment]
Exactly Roxy-3D

I worked for a 3D Printer distributor for quite a while, and to imagine the amount of people that would either destroy their machines, or actually injure themselves without these kinds of safety limits in place kind of scares me a little.

**Comment by robbycandra** [comment]
From 95% of the user, 50% more is young people, know nothing about printer, and like to try and play with menu from LCD. They don't want to print slow and want to make the printer run faster and faster. 

After print fast, and see that the result is not good and the printer is damage, they said to the seller that the printer is broken. 

This happened sometime. Mostly on Anet A8 buyer.

**Comment by Roxy-3D** [comment]
I think this topic deserves more consideration before we close or merge it....

Let's re-open this for a little while and see if we can come to consensus.

**Comment by InsanityAutomation** [comment]
As this was opened back up, I will lay out what my complete intention was.
For accel, feedrate, and jerk if enabled, set default maximum to data size limit to prevent crash. 
With cap enabled but not manually defined use 2x configuration.h define. 
For junction deviation, cap value at .5 as all documentation ive been over essentially states it is not applicable to use a value above this.

Given how much config files and such have changed ill likely start over from a fresh copy if direction is agreed upon. I dont want to waste more time if its just going to get closed again. Regardless this will most likely be implemented and maintained in a few of my branches as it is a source of a high volume of support requests to vendors.

**Comment by InsanityAutomation** [comment]
In doing some more digging,  
This definition : uint32_t max_acceleration_mm_per_s2 
however every other related setting is a float. Its assignment returns a float. Its use in ext_ui functions all take and return floats. Any opposition to changing the type to match everything else around it?

**Comment by AnHardt** [comment]
Crap.
Thinking further in that direction will bring us g-codes for adjusting the limits. Next step after that will be the limits for adjusting the limits.
Makes absolutely no sense to me.

Better remove the g-codes for adjusting acc, jerk, ... for noobs.
Make a kind of reduced USERMODE for people who don't have to make a initial setup of a machine.

**Comment by InsanityAutomation** [comment]
> Crap.
> Thinking further in that direction will bring us g-codes for adjusting the limits. Next step after that will be the limits for adjusting the limits.
> Makes absolutely no sense to me.
> 
> Better remove the g-codes for adjusting acc, jerk, ... for noobs.
> Make a kind of reduced USERMODE for people who don't have to make a initial setup of a machine.

We already have limits and gcode for setting them (M200-205) but the issue comes around when theyre set to unreasonable values by bad default slicer settings (heres looking right at cura again....). Disabling those gcodes is one option. Personally, I think a machine should ship with conservative values, allow you to set them faster but cap you at a hard coded limit to prevent damage. If the users is advanced enough to know they can go beyond it, they can modify the define and go beyond themselves.

**Comment by InsanityAutomation** [comment]
Id like to explain some of the backing thought process here that ive had in discussion with individuals but may not all be apparent here.

The industry at this point as a whole has moved more from hobbyists and tinkerers making things in a basement to more of a consumer audience. Most Marlin installs are now by printer manufacturers. Most users have very little technical background on these machines and configuration. This is a drastic change from years ago when most of us started printing and it was all technical enthusiasts.

That said, in order to support the current user base, things need to be considered from the prospective of a consumer product, where manufacturers have legitimate concerns about warranties and support. While some risks are inherent to the process, others can be mitigated. 

In this case, we are attempting to address an issue that causes an extremely large number of support requests to the distributors who I work with. In many cases, these users have updated to newer firmware specifically to install products sold by these vendors, or have had a newer version than the manufacturer originally ships installed with pre-installed product for the machine. The original manufacturer builds completely removed and ignored M200-M205. The compiled limit was it. However these same manufacturers tend to avoid enabling thermal runaway so conscientious vendors aim to update to current firmware builds to enable these safety features. Now they have builds supporting overriding safe motion limits in the wild.

Couple this with many slicer bugs which we have seen over the last year, such as the Cura Creality profiles which set jerk and acceleration to 10x manufacturer defaults with slicer control enabled but the options visibility turned off as well as the aforementioned lightspeed feedrate, and you can picture the actual cost to many of these businesses.

The time of assuming all users of these machines are technical enthusiasts and will be able to understand what is happening is well behind us at this point. In the case above, several who I have worked with have been flooded with constant support requests on layer shift issues primarily in the heavy Y axis. Couple this with the large thread we have been tracking and the water just gets very muddy as we try to narrow that down. Many have wound up in that thread simply to have found that their jerk or acceleration was sat way too high, in several cases by the exact cura profile issue mentioned above.

**Comment by InsanityAutomation** [comment]
Bumped to a more complete version with acceleration, feedrate, and jerk. Ill get junction deviation soon enough and I still need to do the menus then update the default configs. At least a more complete look at end goal of direction.

**Comment by InsanityAutomation** [comment]
Having glanced at this in extui, i think ill make a planner method for setting these values then call it from the gcode, lcd, and extui. Change for another day though...

**Comment by Roxy-3D** [comment]
I think I'm supportive of the ideas expressed here.   (Including the ones that are concerned about additional complexity and concern it is a slippery slope.   We may next have people pushing for limits to how much the limits can be adjusted!!!).

Can some of these concerns be addressed by moving the added complexity to Configuration_adv.h ?   I'm kind of thinking this logic doesn't need to be in Configuration.h.
```
//#define MAX_FEEDRATE_CAP // Define limit that M203 cannot exceed as 2x default
#if ENABLED(MAX_FEEDRATE_CAP)
  //#define MAX_FEEDRATE_MANUAL { 600, 600, 10, 50 } // Overide default limits with manual values
#endif

...

  //#define MAX_JERK_CAP // Define limit that M205 cannot exceed as 2x default
  #if ENABLED(MAX_JERK_CAP)
    //#define MAX_JERK_MANUAL { 20, 20, .6, 10 } // Overide default limits with manual values
  #endif

```
Perhaps it is best moved to Configuration_adv.h and we just add some comments to the values in Configuration.h to alert people that more granular control is possible in Configuration_adv.h ???   And possibly, if we did go that route we should add more descriptive comments to the Configuration_adv.h code to express the idea that we are trying to help the machine manufacturer's support issues by letting them limit how crazy their machines can be told to behave.

**Comment by gloomyandy** [comment]
I'm a little confused as to what the purpose of these limits are. If they are there to prevent malicious (or playful) abuse in education situations then why would you then allow the limits to be changed via the UI or gcode? Same really goes for manufacturer limits, why would you allow users to easily change them? 

In my view if we are going to have limits they should be baked into the firmware (and only changeable via the config files), no storing them in eeprom, no changing them via gcode or the UI. I would make it possible to find out what the limits are by gcode (and possibly the UI). If you allow the limits to be changed it is probably only a matter of time before slicers add code to change the limits and you are back to the problem you are trying to solve.

**Comment by InsanityAutomation** [comment]
@gloomyandy What youre describing is the current state of things. Currently you set a default max and the menu can overide jerk to 990 and accel / feedrate to 99000. Gcode commands have no limit on setting the maximum. These commands are always there with no way to turn them off and may slicer defaults do override them.

The intent here is to clamp by how much those limits can be changed. A manufacturer could then in theory ship a machine with slow settings set as the default that will work for everything but allow it to be overridden only up to the point that it wont damage the machine. 

The ability to set them somewhat has been present for awhile, and to @thinkyhead 's comment above I don't necessarily want to completely remove that as some vendors do now. This is the balance between what youre saying as set only in config files vs maintaining current expectation of function.

**Comment by gloomyandy** [comment]
@InsanityAutomation perhaps I have misunderstood, I got the impression that you were talking about adding UI to allow the clamp settings to be change. It is that that does not make sense to me (either via the UI or via gcode).

**Comment by InsanityAutomation** [comment]
Nope, just having the menus use the setter in the planner like the gcode and extui instead of calculating the limit all on their own to avoid someone accidentally changing logic differently between them later!

**Review by gloomyandy — COMMENTED** [review]
I'm a little confused, are these changes om the correct branch (they look like good changes, just not sure what they have to do with clamping limits and would not want them to get lost).

**Comment by InsanityAutomation** [comment]
@gloomyandy the one bltouch file changed before was a wrong button (incoming vs current) during rebase.

**Comment by OneOfEleven** [comment]
Cura certainly does have problems of it's own (and should also be fixed) as with others it's doing the same for me - passing extreme GCode parameters to Marlin, and Marlin does not react in a safe or proper manner to these extreme parameters, it should not bomb out, crash, reboot or damage it's machine, but unfortunately that's exactly what it is doing :(

Cura aside, Marlin really needs to protect itself and it's machine from such situations. Just some simple sanity checks on the GCode params I'm sure is all that's needed.

How a coders firmware (commercial or otherwise) reacts to unexpected user input shows up their understanding of user interfacing and coding experience.

**Comment by Roxy-3D** [comment]
Can I get a tally of people's opinions?    I would like to know who has an objection to providing a way for a vendor to clamp Acceleration, Feedrate and Jerk to specified limits.    And I would appreciate knowing the concern.

I need help understanding why this doesn't make sense.

**Comment by p3p** [comment]
There is no reason this doesn't make sense as a safety feature, when I first used Marlin I thought that the max settings in the config protected again hosts trying to go too fast. It was fun finding out that wasn't the case.

**Comment by extesy** [comment]
Being an optional safety feature I can't see why there can be any doubt about it. Don't want it - don't enable it. But it's great to have it as an option to prevent users from accidentally shooting themselves in the foot, especially given that Cura sometimes have bugs that result in light speed numbers.

**Comment by AnHardt** [comment]
How about a somewhat lighter version, without additional configuration?

'**F**' could be limited to the fastest possible speed calculateble from DEFAULT_MAX_FEEDRATE or its RAM equivalent. SQRT(SQ(x) + SQ(y) + SQ(z) + SQ(max(e))).
**Jerk**s could be limited to DEFAULT_MAX_FEEDRATEs components. Additionally one could check against not starting with double/quad-stepping.

**Comment by InsanityAutomation** [comment]
@AnHardt thinky didnt want anything to change expected behavior unless explicitly enabled, so this was the balance between.

**Comment by Roxy-3D** [comment]
@AnHardt    

> 'F' could be limited to the fastest possible speed calculateble from DEFAULT_MAX_FEEDRATE or its RAM equivalent. SQRT(SQ(x) + SQ(y) + SQ(z) + SQ(max(e))).

Are you proposing a change in the GCode syntax?      I may be seeing something you are not saying.
But it would be interesting to allow a shift in the GCode syntax to something like:

G1 X123.45 Y234.12 F      

And if the value for F is not specified, we use SQRT(SQ(x) + SQ(y) + SQ(z) + SQ(max(e)))

If we had something like this,  Cura and Slic3r would have a safe way to make maximum speed moves.

**Comment by DarkAlchy** [comment]
@Roxy-3D  thisiskeithb posted on my issue ( #14930) this thread as DEFAULT_MAX_FEEDRATE always capped the maximum and life was good then I went to 2.0 and had 3 days from Hades trying to track down what was happening with my new SKR V1.3 controller.  After digging I brought this up but it was ignored and that was it was no longer obeying my max feed rate set in Marlin but always did before and does on Repetier.  I dug last night and sure enough it ignores the max now so 4 days in purgatory due to this change (had been around since beta in 2012 in Marlin).

I vote (makes logical sense in my mind) that you set a master cap of speed in the controller so if a user put a million mm/s for Z they don't get frustrated when the motors whine or do worse.  Same with all DEFAULT maxes in the configuration.h.

**Comment by Roxy-3D** [comment]
@DarkAlchy    Thank You for your comments...    (and vote....)

**Comment by InsanityAutomation** [comment]
Rebased this one too. Menus all clamp based on the limits, so callback there isnt necessary. Ill leave it as for now. Any additional comments here @thinkyhead ?

**Comment by Roxy-3D** [comment]
I believe it is time to merge this....   It is my belief Marlin's manufacturing partners need this capability.  

Please make a convincing argument ASAP if there is a reason not to do this.

**Comment by gloomyandy** [comment]
Can someone perhaps summarise what the current state of the code is? I assume that there are new defines that can be used to set a limit on various parameters and that gcode operations (and menu operations) can not set values that exceed these values? A few questions....
1. Is there anyway to override these settings (other than rebuilding with new ones)?
2. Is there any sort of feedback if a limit is exceeded?
3. If using the menu does the value just stop increasing or does it look like you have set a new (bigger) value but the value is silently clamped?
4. If you set a value above the clamp using say gcode and then save to eeprom what value is saved (the clamped value or the value actually set)? Also if there is an old value in eeprom that is above the clamp will the clamp be applied to that?
5. Is there a list of the values that are clamped.
6. What are the "default" settings?

I know I could go read the code to get all of the above, but a) I'm being lazy, b) I think it is useful to hear a description of how they are supposed to work c) I think such a description would form a useful basis for the documentation of the feature.

**Comment by InsanityAutomation** [comment]
> 
> 
> Can someone perhaps summarise what the current state of the code is? I assume that there are new defines that can be used to set a limit on various parameters and that gcode operations (and menu operations) can not set values that exceed these values? A few questions....
> 
>     1. Is there anyway to override these settings (other than rebuilding with new ones)?
No, thats the primary purpose.
> 
>     2. Is there any sort of feedback if a limit is exceeded?
From G-Code, no just clamped
> 
>     3. If using the menu does the value just stop increasing or does it look like you have set a new (bigger) value but the value is silently clamped?
Menu limits are adjusted to these limits, so it will stop when it cant go any higher.
> 
>     4. If you set a value above the clamp using say gcode and then save to eeprom what value is saved (the clamped value or the value actually set)? Also if there is an old value in eeprom that is above the clamp will the clamp be applied to that?
Setting a value by gcode will be clamped so no way to get it in there. Most likely this will be merged next to one of the other PR's above that changes the eeprom version so the fringe case of loading old unclamped eeprom data will likely not exist for long if at all.
> 
>     5. Is there a list of the values that are clamped.
> 
Feedrate, Jerk, accel/decel
>     6. What are the "default" settings?
2x default value from config, or manually define limit.
> 
> 
> I know I could go read the code to get all of the above, but a) I'm being lazy, b) I think it is useful to hear a description of how they are supposed to work c) I think such a description would form a useful basis for the documentation of the feature.

Also important to note if you dont enable the absolute limit it wont do anything. Current limit allowing values of 99,999 in the menus will remain.

**Comment by gloomyandy** [comment]
@InsanityAutomation perfect thanks. All makes sense to me. One final question...
7. Is there any way to obtain a report of the clamp values via gcode?

**Comment by InsanityAutomation** [comment]
> 
> 
> @InsanityAutomation perfect thanks. All makes sense to me. One final question...
> 7. Is there any way to obtain a report of the clamp values via gcode?

Included in M115 capabilities report

**Comment by Roxy-3D** [comment]
AND...   Now Travis is happy with the Pull Request because the STM32F1 code is fixed again!

**Comment by Roxy-3D** [comment]
I think we need a Pull Request for https://github.com/MarlinFirmware/Marlin/tree/dev-2.1.x also.

We probably want to keep the two branches synchronized.

**Comment by InsanityAutomation** [comment]
> 
> 
> I think we need a Pull Request for https://github.com/MarlinFirmware/Marlin/tree/dev-2.1.x also.
> 
> We probably want to keep the two branches synchronized.

Thats already 2 weeks behind and needs a catchup / rebase probably regardless.

**Comment by Roxy-3D** [comment]
The https://github.com/MarlinFirmware/Marlin/tree/dev-2.1.x version has been merged.   Anybody interested in giving feedback on the concept or code can try it in that branch.      And depending on how fast v2.0.0 stabilizes, it may make it into the v2.0.0 release.

**Comment by DarkAlchy** [comment]
Btw, I now know why I had sudden troubles with this because I had switched to S3D that allows me to set a Z speed and now I am back to slic3r (Prusa Slicer) and it set my travel_speed to 130mm/s.  I went looking at my gcode as I am setting up the printer and OMG it was doing all Z moves at F7800.  I smh and to test I threw all travel moves to 30mm/s and bingo there it became F1800.  This explains it as when I used to run Slic3r my Marlin had it capped, as did Repetier, but under 2.0 it doesn't.  Anyone who uses Slic3r, or Prusa Slicer will have a rude awakening but luckily this is being merged and the issue will go away.  I will be without the Internet for 3+ months so will have to check back in on the progress when I can.

At least now I have solved it.

**Comment by thinkyhead** [comment]
Rebased, squashed, and modernized. I still have some typos to fix, no doubt.
```
git fetch origin
git checkout AccelClamping
git reset --hard origin/AccelClamping
```

**Comment by DarkAlchy** [comment]
Any idea on when this will be released officially?

**Comment by reloxx13** [comment]
is it on purpose that some have a lower max feedrate as default max feedrate?

e.g.
Default 15
Hardcoded 10

grafik

**Comment by InsanityAutomation** [comment]
@reloxx13 We didnt set defaults for every config, just a single global default. It shouldnt be changed from the standard unless enabled.

**Pull request merged**
