### PR TITLE
Disable software endstops while doing UBL fine tuning

### PR DESCRIPTION
**Pull request by earlephilhower**
### Description

When doing manual fine tuning using UBL, there are often mesh areas with negative Zs (at least on my delta).  The existing fine tune algorithm does a travel to the negative Z properly, but when it polls the LCD the software endstops engage and immediately slam the Z up to 0 on each encoder poll.  Then on the next pass thru the polling, UBL moves back to the proper negative Z and the process repeats.

This up and down can repeat tens of time each second, turning the printer into a jackhammer and making the fine tune adjustment of negative Z meshes almost impossible.

This patch uses M211 S0/S1 to disable/re-enable software endstops during each manual fine tune probe, avoiding the bouncing.
    
### Benefits

Makes UBL fine-tuning with negative Z mesh points possible without manually needing to enable/disable endstops from outside the LCD menus.

### Configurations

* Any configuration with `HAS_SOFTWARE_ENDSTOPS` (i.e. deltas) can be used to test/build.

### Related Issues

none

### CODE REVIEW

**Comment by Roxy-3D** [comment]
In general...   Software Z-EndStops should not be enabled with any of the mesh bed leveling systems.   Certainly, that is true for UBL.     What you have done probably makes sense and will help.    But it won't help the case where during normal printing the Z-Height correction decides the nozzle needs to go a little bit negative.

I would like to encourage you to add a sanity check to this Pull Request to check if software EndStops are enabled for the Z-Axis and if so warn the user that is inappropriate.    Either that or add a few lines of code to defeat the software Z-EndStop in the planner if UBL is active.

**Comment by earlephilhower** [comment]
Thanks for the information.  I'll see about adding that sanity check.

About the correction during printing, though, I'm actually not finding that to be the case if I understand your concern properly.  If the gcode never drops below `Z0`, then the mesh bed adjustment negative seems to work fine with software endstops enabled.  I'm really not familiar with the code path (Marlin "just works" so I never looked), but maybe this has to do with the difference between raw/mesh adjusted Z values, and the fact that with the fine tuning we are using raw Z in LCD fine tune mode?

**Comment by Roxy-3D** [comment]
image

A lot has changed since UBL was written.   The usage of MIN_SOFTWARE_ENDSTOP_Z has been collapsed down to just a few places.   It should not be too hard to defeat the Z-Axis being set to 0  if both UBL is active and Z is less than 0.    It may make sense to leave the software endstops active if UBL is turned off...      All 4 of those .cpp files use the same logic:
```
        case Z_AXIS:
          TERN_(MIN_SOFTWARE_ENDSTOP_Z, min = soft_endstop.min.z);
```
If this was changed to something like:
```
        case Z_AXIS:
          #if ENABLED(AUTO_BED_LEVELING_UBL)       
          if ( !planner.leveling_active )                            //allow Z-Height correction to take nozzle slightly below 0.00 mm
          #endif
          TERN_(MIN_SOFTWARE_ENDSTOP_Z, min = soft_endstop.min.z);
```
And of course...  with that type of change, your patches would still help in the case UBL is not active and the person is trying to configure (edit) the mesh.   And with this approach, no sanity check would be needed because the code would adapt to whether UBL was active or not.

**Comment by earlephilhower** [comment]
Thanks for the very detailed info, @Roxy-3D, it's appreciated.  I'll go back and see about reworking it as you suggested.

**Comment by thinkyhead** [comment]
Seems to me that soft endstops should not be applied to internal moves, but only to moves that come through `G0`, `G1`, `G2`, `G3`, `G5` G-code commands. Usually the internal moves are sensible, plus the soft endstops could be set to anything at all, and that could be a real bother for internal procedures.

**Comment by Roxy-3D** [comment]
> Seems to me that soft endstops should not be applied to internal moves, but only to moves that come through G0, G1, G2, G3, G5 G-code commands.

Taking this approach would solve (or eliminate) many problems.   If the software endstops are checked (and corrected) at the G0, G1, G2, G3, G5 level...   but the bed leveling software is allowed to correct slightly below 0.000 mm that resolves a lot of issues.

**Comment by thinkyhead** [comment]
I think that the issue being addressed here in this PR is that the manual movement on the LCD takes account of software endstops. That should get its own flag so that when UBL, etc. wants to use it there won't be any limits on Z.

**Comment by Roxy-3D** [comment]
> I think that the issue being addressed here in this PR is that the manual movement on the LCD takes account of software endstops. That should get its own flag so that when UBL, etc. wants to use it there won't be any limits on Z.

Agreed.   But it is almost trivial to fix this on-going issue for all the mesh based bed leveling systems.    What if we made the changes I suggested here https://github.com/MarlinFirmware/Marlin/pull/19681#issuecomment-706611221  but do two more things.   First we do it for any mesh bed leveling system and not just UBL.    And the other thing we do is maybe add a limit to how much we relax the check for going below the minimum level.   I think .5 mm below the minimum level (due to Z-Height correction) would offer a lot of protection.   Most printers won't hurt themselves too much if they try to go .5mm below the Z software endstop.

**Comment by Roxy-3D** [comment]
I like what you did here and the corresponding usage of it:

  #define SET_SOFT_ENDSTOP_LOOSE(loose) (soft_endstop._loose = loose)

**Comment by annhan** [comment]
if you don't enable ```HAS_SOFTWARE_ENDSTOPS``` , your build will return errors
```c
Compiling .pio\build\DUE_USB\src\src\gcode\control\M350_M351.cpp.o
Compiling .pio\build\DUE_USB\src\src\gcode\control\M400.cpp.o
Marlin\src\gcode\calibrate\G28.cpp:269:31: error: macro "SET_SOFT_ENDSTOP_LOOSE" passed 1 arguments, but takes just 0
   SET_SOFT_ENDSTOP_LOOSE(false);  // Reset a leftover 'loose' motion state
                               ^
Marlin\src\gcode\calibrate\G28.cpp: In static member function 'static void GcodeSuite::G28()':
Marlin\src\gcode\calibrate\G28.cpp:269:3: error: 'SET_SOFT_ENDSTOP_LOOSE' was not declared in this scope
   SET_SOFT_ENDSTOP_LOOSE(false);  // Reset a leftover 'loose' motion state
   ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by annhan** [comment]
change
```#define SET_SOFT_ENDSTOP_LOOSE()    NOOP```
to
```#define SET_SOFT_ENDSTOP_LOOSE(loose)    NOOP```
is a temporary solution for me

**Comment by Roxy-3D** [comment]
I'm sure its in there somewhere...   But I didn't see where 
```
#define SET_SOFT_ENDSTOP_LOOSE(loose) (soft_endstop._loose = loose)
```
causes the software endstop check to be 'looser'.

**Comment by annhan** [comment]
in motion.h file 
[line 203](https://github.com/MarlinFirmware/Marlin/blob/87b07d6f2f8ca25e59e2a8751afd79b0b80b22ba/Marlin/src/module/motion.h#L201)
and 
[line 186](https://github.com/MarlinFirmware/Marlin/blob/87b07d6f2f8ca25e59e2a8751afd79b0b80b22ba/Marlin/src/module/motion.h#L186)

**Comment by Roxy-3D** [comment]
No...   in order for the Software Endstops to work, the current axis position needs to be compared against some number.   And that comparison determines if the position is past the endstop.    But if the enstop is 'loose'...   The comparison should probably have some slop added into it.   The axis would be allowed to go a little bit past the endstop and still not trigger it.

I don't see that code anywhere...

**Pull request merged**
