### PR TITLE
Bugfix 1.1.x Extruders = 0 make all Stepper available for X,Y,Z

### PR DESCRIPTION
**Pull request by fabtopia**
Contains conditions and a little logic so Marlin can be configured without any extruder/hot end so all steppers can be used for X,Y,Z axis. This is useful for CNC and laser project.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Please repair this PR. You can rebase it onto the current `bugfix-1.1.x`, or if you don't know how to do that, start over with a fresh copy of the latest `bugfix-1.1.x` and apply your changes to the new branch.

**Comment by thinkyhead** [comment]
@fabtopia This PR was messed up. It was apparently based on some old `1.1.x` instead of `bugfix-1.1.x`. All PRs must start with a current copy of `bugfix-1.1.x` or `bugfix-2.0.x`.

As for the content of the PR, we've actually got most of this already —in a more complete form— in PR #6977. 

So what I've done is added more changes from that PR to a copy of your branch, and in a moment I will replace your branch with this rebased, squashed, and updated version. It includes some temporary changes to Travis CI to test `EXTRUDERS 0` so we can see whether there's more to do.

You should get the new branch onto your computer by using the command-line version of git, which should be accessible from your Github Desktop client. You'll need to do this to get the latest changes into your working copy:

```sh
git fetch origin
git checkout bugfix-1.1.x-NoExtruder
git reset --hard origin/bugfix-1.1.x-NoExtruder
```

**Comment by fabtopia** [comment]
@thinkyhead: Please help with the remaining errors
And please take a look at the condition "const bool inf_normalized_flag = (isinf(e_normalized_dist) != 0)" in ubl_motion.cpp. I Think is best to say if zero extruders this is true, but i'm not sure.
How to deal with DAC_STEPPER_CURRENT and Zero Extruder, i don't know. Should there be a new DAC_CHANNELS 4 be defined at pins_*.h level or...

**Comment by fabtopia** [comment]
@thinkyhead and others
I think it's your (and others) turn now...

I had to deal with a watchdog when define extruders 0 and making an G0/G1 movement. the temperature::ISR was not re-enabled. When I put in a heater bead or define HOTENDS 1 instead of HOTENDS EXTRUDERS //Zero the normal line works fine. I think is a timing problem.

My Sollution (at stepper.cpp); Change:
#define _ENABLE_ISRs() do { cli(); if (thermalManager.in_temp_isr) CBI(TIMSK0, OCIE0B); else SBI(TIMSK0, OCIE0B);
into:
#define _ENABLE_ISRs() { cli(); SBI(TIMSK0, OCIE0B); ENABLE_STEPPER_DRIVER_INTERRUPT(); } 

So take a good look at it before release.

The remaining errors are SanityChecks

If this is good (enough) then I will re-do the 2.0 version and add the same conditions

**Comment by fabtopia** [comment]
There is still a problem with using the E0. Movements forward are oke, but backwards result in E0 still going forward. Steppers on E1 does not have this problem.

**Comment by thinkyhead** [comment]
There's still a lot to be done. It's not as easy as it used to be to allow EXTRUDERS 0. Unfortunately for this PR it is a very low priority right now, as we are seeking to do a worthy 1.1.9 release and get 2.0 out as soon as humanly possible. We'll revisit this when we are back on a new feature track.

**Comment by fabtopia** [comment]
That's oke. I have a working version and testing it now. @thinkyhead What's the best way to keep up with the other improvements. At the moment is already has some conflicts.

**Comment by thinkyhead** [comment]
> What's the best way to keep up with the other improvements.

```
git fetch upstream
git checkout my_working_branch
git rebase upstream/bugfix-1.1.x
```
Do this once a day and the number of conflicts you encounter will be greatly minimized.

It can also help to combine ("squash") multiple commits together, so there are fewer interruptions in the rebase for fixups.

**Comment by thinkyhead** [comment]
At this point Marlin 1.1.x is end-of-life, so we'll just focus on the PR targeting `bugfix-2.0.x`, which certainly needs a refresh at this time.

**Pull request closed without merging**
