### PR TITLE
Fix of M106 with SINGLENOZZLE (#24065)

### PR DESCRIPTION
**Pull request by Graylag-PD**
### Description

This fixes an issue for `SINGLENOZZLE,` that using `NUM_M106_FANS` it is possible to define more than one fan, but only FAN0 is controllable. After change it is possible to use as many independent M106 fans as desired, while still defaulting M106 without P parameter to FAN0. Functionality of M106 without P parameter is unchanged, Functionality of M106 with P parameter is slightly altered - M106 before always controlled FAN0 regardless of P parameter. M106 after controls specific fan as defined by P as expected.  

Change in M106_M107.cpp does:
a) hardcodes FAN0 as default fan when no P parameter is used (this was effectively done by line in temperature.cpp)
b) removes fan limit to number of extruders

Change in temperature.cpp removes superfluous line, whose function is superseeded by hardcoding in M106_M107.cpp (and this line was producing weird results anyway)

### Requirements

`SINGLENOZZLE`; `NUM_M106_FANS` > 1

### Benefits

Fix of strange behaviour of fans when `SINGLENOZZLE` is defined (see BR #24065)

### Configurations

none

### Related Issues

#24065

### CODE REVIEW

**Comment by thinkyhead** [comment]
Refer to #13038 for the reason `active_extruder` is used instead of 0. From a cursory inspection, it seems quite possible that code in `Temperature::set_fan_speed` is using the provided `active_extruder` value for the benefit of `SINGLENOZZLE_STANDBY_FAN` logic. We'll need to double-check with @InsanityAutomation whether the change from that earlier PR is still relevant, and look more carefully at the implications of the proposed change here.

**Comment by InsanityAutomation** [comment]
The behavior was defined as following the typical paradigm of M106 fans being assumed part cooling fans. It functions through this case, however the OP wants arbitrary fan functions (chamber exhaust etc) as well at higher number fans than tools exist.

I dont mind a change in the paradigm as long as its a conscious decision, as we will need to review and be more cautious about assignment in the future. In that case I would suggest revising comments around NUM_M106_FANS and the gcode page as well in conjunction to be explicit.

Another option of course is to be more explicit about M106 as part cooler fans and define a new code / menu items for arbitrary fans, and bring chamber / controller fans etc underneath it.

Regardless, my point is needs a little thought and decision on direction.

**Comment by Graylag-PD** [comment]
I would like this shift in paradigm as we discussed in #24065, but at same time I am not insisting on it. In fact, I have proposed alternate solution for control of arbitrary fans based on what @InsanityAutomation recommended, see #24181 
This PR is not about this change of paradigm, it is independent on it and just fixes illogical behaviour of Marlin which lets you define arbitrary number of fans, but does not let you control it. Which is issue for for example `CHAMBER_FAN`, which is built around repurposed M106 fan.
To fix this illogical behaviour, Marlin should either not allow you to define arbitrary number of fans (for example by sanity check saying that not more than 1 `NUM_M106_FANS` is allowed for `SINGLENOZZLE`), or remove artificial blocking points that prevent control of those fans. This PR is about later.

I have not considered  `SINGLENOZZLE_STANDBY_FAN` that @thinkyhead mentioned and I admit it may be an issue which would require rework of this PR. Just please consider it with open mind (and @InsanityAutomation, sorry, I know I can be annoying at some times)

**Comment by thinkyhead** [comment]
Let's revisit this after completion of the Fan Class refactor in #24092 – which should be in more complete shape pretty soon.

**Pull request closed without merging**
