### PR TITLE
HC32: Update Clock Configuration

### PR DESCRIPTION
**Pull request by shadow578**
### Description

Undoes some changes made in in https://github.com/MarlinFirmware/Marlin/pull/27086 and updates some comments to reflect the clock architecture on HC32.
Also see https://github.com/MarlinFirmware/Marlin/pull/27086#issuecomment-2114226005.

With feedback in comments, this PR now also includes a more general overhaul of the HC32 HAL's clock configuration.

#### HC32 Clock Architecture

This part is meant to provide a high-level overview of the clock architecture used in the HC32 HAL, and how it is configured in Marlin.

In the HC32 HAL, all clocks are derived from the `MPLL-P` clock, divided by a fixed divider.

First, the MPLL input clock is set to one of three sources:
1. External XTAL @ 8 MHz (if `BOARD_XTAL_FREQUENCY` == 8 MHz)
2. External XTAL @ 16 MHz (if `BOARD_XTAL_FREQUENCY` == 16 MHz)
3. Internal high-speed RC oscillator (HRC) @ 16 MHz (if neither 1 nor 2)

The MPLL then locks onto the input clock divided by an internal division factor `M`. 
The resulting clock is then multiplied by internal factor `N`, before beign divided by factors `P`, `Q` and `R` to create the equally named output clocks (`MPLL-P`, `MPLL-Q` and `MPLL-R`).
`MPLL-Q` and `MPLL-R` are not used by the HC32 HAL, so can be ignored.
These values are configured in the `pllConf` struct.

(Final `MPLL-P` output clock is calculated as $ f_{P} = \frac{\frac{f_{in}}{M} * N}{P} $.)

The `MPLL-P` clock is then divided by the dividers configured in the `sysClkConf` struct to get the final output clocks. 
For example, `HCLK = MPLL-P / 1` and `PCLK2 = MPLL-P / 8`.

To ensure all clocks are valid, they are verified using the `assert_system_clocks_valid` function (when available).

See Fig. A for a marked up clock system block diagram highlighting the path of the various clocks used in the HC32 HAL. 
Also consider referencing Section 4.2.1 of [the HC32F460 Reference Manual](https://github.com/shadow578/hc32f460-documentation-and-sdk/blob/main/page-dump-new/documentation/reference%20manual/en/NATIVE_HC32F460_F45x_A460SeriesReferenceManual_Rev1.5.pdf) if more information is needed. 

### Requirements

HC32-based printer

### Benefits

Updates documentation for HC32 HAL clock configuration.

### Configurations

N/A

### Related Issues

N/A

### Attachments

| clks |
|-|
| Fig. A: Clock System Block Diagram |

### CODE REVIEW

**Comment by thinkyhead** [comment]
Did you mean to revert all these changes?

Organizationally it makes more sense to use the `F_CPU` defined in the header in place of `200000000` wherever possible, rather than have `F_CPU` simply reflect a constant value used elsewhere, as this more easily allows changing the clock base in one location. In the same regard, using `F_CPU / 4` makes sense because `50000000` is based on the constant `F_CPU` with a clock divider of 4.

If for some reason this defined `F_CPU` is not seen by `HAL/HC32/sysclock.cpp` we just need to add `#include "app_config.h"` there.

**Comment by thinkyhead** [comment]
I see… Since `F_CPU` is not the "master value" but there is a common clock value on which the others are based, we should define that at least, and then define the others in terms of that. We would call it `F_HCLK` (or something even more specific)…
```cpp
#define F_HCLK 200000000 // 200MHz HCLK
#define F_CPU F_HCLK
```

**Comment by thinkyhead** [comment]
I pushed a commit with what makes sense to me, but of course please apply corrections and clarifications. It's interesting that HC32 clock frequency is so configurable, and it will be cool to be able to change the clock speed by changing a single define.

**Comment by shadow578** [comment]
> We would call it F_HCLK (or something even more specific)…

> it will be cool to be able to change the clock speed by changing a single define.

I think i've got an idea how most of the clock configuration can be handled automagically at compile time, with validation and everything. 
Making it a single define is probably not viable tho... 
So i'd set it up so each of the clocks can be set to a target frequency individually, and the dividers are then calculated and checked automatically.

PLL config seems a bit daunting to make automatic, so i'll put that off for now :D

I'll push a commit tomorrow, gotta test this first.

---

>  It's interesting that HC32 clock frequency is so configurable

Yeah, it's kinda weird how capable and configurable this MCU actually is. 
When i first started, i thought of it as a STM32 clone. 
But as i get more familiar with this chip, i really don't think it's just a clone... 
Like, STM32 doesn't have freely configurable interrupt vectors, and also not multiple DMA and ADC units, basically fullly muxed GPIO, and USB (at least i think so).

But then there's also some really weird additions, like two independent watchdog timers...

Anyway, it's a really interesting if not weird chip

**Comment by thinkyhead** [comment]
Thanks for the feedback, looking forward to your update!

**Comment by shadow578** [comment]
So, i've pushed a commit to automatically handle everything related to the clock configuration using defines in `sysclock.h`. 
Right now, everything is derived from `F_HCLK`, but this system is fairly flexible so a different 'main' clock could also be chosen.

PLL config was indeed fairly daunting, but i did manage to pull it off - at least kind of.
When including the `M` input division factor in the PLL calculations, the call `constexpr stc_clk_mpll_cfg_t pllConf = get_mpll_config(mpll_input_clock, F_SYSTEM_CLOCK);` shows as an error in vscode. 
Compiling does seem to work tho...

Maybe someone whos a bit more skilled in C++ could take a look ?

**Comment by shadow578** [comment]
Ok, after taking another look at this i've managed to simplify the constexpr `get_mpll_config` function so it no longer causes the error. 

I haven't yet tested this tho. On paper this should work, but i'll test later today and comment back.

**Comment by shadow578** [comment]
> I haven't yet tested this tho. On paper this should work, but i'll test later today and comment back.

Ok, just tested it and it does indeed work as expected. 
Imo this should be ready to merge now.


<details>
<summary>Clock Dump w/ 8 MHz XTAL</summary>

-- clocks dump --
SYS=200000000
HCLK=200000000
PCLK0=100000000
PCLK1=50000000
PCLK2=25000000
PCLK3=25000000
PCLK4=100000000
EXCLK=100000000
F_CPU=200000000
SYSCLK=MPLL,XTAL
P=2
Q=2
R=2
N=50
M=1

</details>

**Comment by shadow578** [comment]
Hi @thisiskeithb ,

is there anything preventing this PR from getting merged? Anything i can do?

**Comment by thisiskeithb** [comment]
> is there anything preventing this PR from getting merged? Anything i can do?

I’m not sure. Merging is up to thinkyhead.

**Comment by shadow578** [comment]
@thinkyhead is there anything preventhing the PR from getting merged?

**Comment by thinkyhead** [comment]
Hey ho. Only thing holding this up is me! I'll resolve the conflicts and do a quick review and should have this merged forthwith. Makes sense to get this out as part of 2.1.3 - for the people!

**Pull request merged**
