### PR TITLE
[2.0] Add SERIAL_PORT -1 option for configurators

### PR DESCRIPTION
**Pull request by thinkyhead**
Ref: #8213

The serial port for MKS SBASE should be -1 by default. This will apply to _some_ other 32-bit boards as well. Along with #8148 this expands the serial port options for 32-bit boards.

To do:
- Add a sanity-check to prevent boards that don't have a -1 serial port from using it
- Sanity check to ensure -1 for boards that must use it

### CODE REVIEW

**Comment by tcm0116** [comment]
What's with the ultralcd.cpp file added to the commit? Also, I don't see SanityCheck.h in the commit.

By the way, not all 32-bit boards will use the USB port. I have an LPC1768-based board that for whatever reason decided to use UART0 via a USB-to-UART bridge, and did not provide access to the USB port. As such, forcing me to use the USB port would break my ability to interface with my board. (Note that I'm guessing which boards you're going to ensure are using -1 since SanityCheck.h is missing from the commit).

**Comment by thinkyhead** [comment]
> What's with the ultralcd.cpp file added to the commit?

Fell in.

>  I don't see SanityCheck.h in the commit.

I haven't determined what kind of check to apply yet. Need more feedback on the best approach.

> not all 32-bit boards will use the USB port

Right. When I said "other" (not "all") I meant "_some_ other." Clarified.

**Comment by victorpv** [comment]
I don't know why this commit would be needed. I have successfully printed with both the USB port and USART1 without the changes here, in STM32F103VET6 and STM32F103ZET6. The RET is pretty much the same with less pins, but no difference as far as USART and USB.

**Comment by victorpv** [comment]
And now that I remember, the SBASE uses the LPC1768, not the STM32. So I can't comment on whether the SBASE needs that -1 added.
There are other MKS boards based in stm32f1 MCUs though. Re-reading the subject line I wonder if you were just listing different boards.
Well for the RET6 we don't need this change. Likely doesn't hurt anyway.
I'll try to update my local copy and test it.

**Comment by thinkyhead** [comment]
Good to know that it won't be needed for the STM32's. So far the only one I can be relatively certain about thanks to user feedback is the MKS SBASE, so I'll limit this PR to that one board.

…and X5GT perhaps…?

**Comment by tcm0116** [comment]
The MKS SBASE can be controlled via the USB port or the UART. @Spawn32 can
confirm.

**Comment by thinkyhead** [comment]
Excellent. So what makes the best choice — USB (`SERIAL_PORT` for AVR is `0`, for MKS-BASE is `-1`) for all boards by default, and leave in the `-1` option for the configurator? Is my change to the description sensible? I'd like to resolve #8213.

**Comment by tcm0116** [comment]
This is why I started working on the SECONDARY_SERIAL_PORT. By defaulting
it to -1, it will automatically enable both the UART and USB on controllers
that have both, but be ignored by controllers that only have a UART. This
would eliminate any need for a sanity check or any other type of automatic
configuration.

**Comment by thinkyhead** [comment]
@tcm0116 Would you say that your PR obviates the need for this one?

The only caveat I have with `SECONDARY_SERIAL_PORT` is that it balloons the binary size, especially when extra debugging is enabled. If you can ensure that the serial objects will be called by reference instead of by pointer, I'd merge it right away.

As for the new option name, I think `SERIAL_PORT_2` might be better. That way the next one we add can be `SERIAL_PORT_3` instead of `TERTIARY_SERIAL_PORT`.

**Comment by thinkyhead** [comment]
@tcm0116 Would you say that your PR obviates the need for this one?

The only caveat I have with `SECONDARY_SERIAL_PORT` is that it balloons the binary size, especially when extra debugging is enabled. If you can ensure that the serial ports will be called by reference instead of by pointer, I'd merge it right away.

As for the new option name, I think `SERIAL_PORT_2` might be better. That way the next one we add can be `SERIAL_PORT_3` instead of `TERTIARY_SERIAL_PORT`.

**Comment by tcm0116** [comment]
I think it will, but it's not ready for prime time. I'm going to try and
work on it this weekend and see how far I can get with the actual
processing of commands from multiple hosts. Making it where it doesn't
affect the binary size with only a single serial port is going to be the
biggest challenge, but is something I'm committed to.

**Comment by thinkyhead** [comment]
C++ may allow the creation an array of real objects, not just pointers. I haven't played too much with objects and references lately, but see if this kind of thing works…
```cpp
MySerial Serial1;
MyOtherSerial Serial2;
SerialFacadeBase serials[2] = { Serial1, Serial2 };

serials[1].print("Hello World");
```

**Comment by tcm0116** [comment]
That won't work since only concrete classes can be instantiated. I'm going
to eliminate the SerialFacade class since it will do nothing but cause
bloat in a single port situation. I have some ideas of how to handle it
another way. There might be a few bytes added here and there to support the
framework of multiple ports, but I think it will be acceptable.

**Comment by thinkyhead** [comment]
For Marlin we should use _plastic_ classes until we get a proper _concrete_ extruder.

**Comment by victorpv** [comment]
Oh crap, do I need to buy more parts now for another extruder? this is never ending...

**Pull request merged**
