### PR TITLE
🔨M154 Auto-report the real position

### PR DESCRIPTION
**Pull request by TheSnowfield**
### Description

Improve auto position reporting command M154.
```c
/**
 * Auto-report position with M154 S<seconds>
 */
//#define AUTO_REPORT_POSITION
#if ENABLED(AUTO_REPORT_POSITION)
  //#define AUTO_REPORT_REAL_POSITION // Auto-report the real position
#endif
```

### Benefits

Append the `AUTO_REPORT_REAL_POSITION` flag to enable real position auto-reporting ability for M154.

### CODE REVIEW

**Comment by sarvenn** [comment]
What is the difference of benefit?

**Comment by TheSnowfield** [comment]
> What is the difference of benefit?

Previously, M154 doesn't support reporting the real position but M114 can.

So this PR provides an enhancement feature of M154. After uncommenting `#define AUTO_REPORT_REAL_POSITION` line, 
we can track the real stepper position when Marlin works on the step without sending M114 command, and turning off this macro can keep the forward compatibility.

`AUTO_REPORT_REAL_POSITION` macro affects here:
```c
#if ENABLED(AUTO_REPORT_POSITION)
  #include "../libs/autoreport.h"
  struct PositionReport { static void report() {
    #if ENABLED(AUTO_REPORT_REAL_POSITION)
      report_real_position();
    #else
      report_current_position_projected();
    #endif
    }
  };
  extern AutoReporter<PositionReport> position_auto_reporter;
#endif
```

**Comment by thinkyhead** [comment]
More like "recent position" amirite?

**Comment by sarvenn** [comment]
So M114_DETAIL and M154 AUTO_REPORT_REAL_POSITION should not be enabled at the same time, am I understood it right?
I'm using BTT TFT E3 V3 screen and it requires to enable these parameters:
AUTO_REPORT_POSITION (in Configuration_adv.h)
EXTENDED_CAPABILITIES_REPORT (in Configuration_adv.h)
M115_GEOMETRY_REPORT (in Configuration_adv.h)
M114_DETAIL (in Configuration_adv.h)

So, I'm wondering if I should also enable not the AUTO_REPORT_REAL_POSITION parameter under AUTO_REPORT_POSITION?

**Comment by TheSnowfield** [comment]
> So, I'm wondering if I should also enable not the AUTO_REPORT_REAL_POSITION parameter under AUTO_REPORT_POSITION?

I guess it's no conflict between M114_DETAIL and AUTO_REPORT_REAL_POSITION, they should be compatible.
If you thought AUTO_REPORT_REAL_POSITION is unnecessary on your board, you can disable it.

**Pull request merged**
