### PR TITLE
Add Mellow Fly E3 Pro V3

### PR DESCRIPTION
**Pull request by IoakeimSogiakas**
this is a work in progress the environment is wrong

### CODE REVIEW

**Comment by thisiskeithb** [comment]
"Fly E3 Pro V3" is listed on the board & [Mellow's GitHub repo](https://github.com/Mellow-3D/Fly-E3-Pro-v3/tree/main), so that is probably the name to go with:

**Comment by IoakeimSogiakas** [comment]
OK

**Comment by thisiskeithb** [comment]
As discussed on Discord, we still need the variant files for this board before it can be added. You mentioned that you no longer have one to test and as far as I know, no one else on the Marlin team has one either, so we have no way to confirm that the pending variant files will work.

**Comment by IoakeimSogiakas** [comment]
Yes that is true if manage to acquire said board I will try to finally find the correct environment

**Comment by IoakeimSogiakas** [comment]
Thanks for all the help

**Comment by thinkyhead** [comment]
I just received a donated Fly Mellow Super 5 Pro. I don't know how similar these Fly Mellow boards are, but it should be good for general testing. It has the STM32H723-VGT6 MCU.

**Comment by thinkyhead** [comment]
According to Klipper config "should be compiled for the STM32F407 with a 32KiB bootloader" so it's perhaps a fairly generic STM32F4. Klipper seems to be agnostic for build purposes as to the specific total amount of Flash and RAM on the board, but it would be worth looking closer at the Klipper build system to see how that all works.

**Comment by IoakeimSogiakas** [comment]
Nice! Have fun. Unfortunately I don't think I can be much of help 😭

**Comment by ellensp** [comment]
replaced with https://github.com/MarlinFirmware/Marlin/pull/26214

**Pull request closed without merging**
