### PR TITLE
[bugfix-1.1.x] Update russian language 28 Feb 2018

### PR DESCRIPTION
**Pull request by anton-piliugin**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Perfect! Thank you very much for the update!

**Comment by anton-piliugin** [comment]
Is this (bugfix-1.1.x) language files different from 2.x version?

**Comment by thinkyhead** [comment]
Identical, so I've already merged that as well.

**Comment by anton-piliugin** [comment]
Great!

**Comment by thinkyhead** [comment]
Мы не могли бы сделать это без тебя!

**Pull request merged**
