### PR TITLE
[2.0.x] Bring NEOPIXEL_LED into parity with 1.1.x

### PR DESCRIPTION
**Pull request by thinkyhead**
Followup to #7919 rolling back attempted cleverness.

### CODE REVIEW

**Comment by SCiunczyk** [comment]
In my changes to version 2.0.x my intention was to avoid spreading the "#if ENABLED(NEOPIXEL LED)" over so many source files keeping them as clean and simple as possible. But of course you are the Master.

**Comment by thinkyhead** [comment]
Ah, sorry @SCiunczyk — I totally missed your PR. My aim here was to have the code exactly match the 1.1.x code so that there's no confusion in future. But of course, I'd much rather that we were all onto the 2.0. branch only…… Soon, I hope! So, I'll compare and see where you've improved things, then back-port those to 1.1.x.

**Comment by Tannoo** [comment]
I had issues compiling with this... I got it working on my end.
I am egerly awaiting a real fix.

**Comment by Tannoo** [comment]
But, maybe I had a little too much coffee. Maybe I'll just keep quiet.

**Comment by SCiunczyk** [comment]
No you haven't, those errors are our old friends.... hi hi hi fixed in 
my PR #8089 unfortunately @thinkyhead bring them back to live ;-) we 
need stronger repellent for this bugs I think.


W dniu 27.10.2017 o 14:07, Tannoo pisze:

**Comment by SCiunczyk** [comment]
I was wrong, after fresh fork and clone of `bugfix-2.0.x` I can compile without problems. Anyway I still have my littel changes and will keep them saved on side, but let's wait for 2.0 release. Supermegaextrafancy Neopixel support it's not so important stuff right now ;-)

**Pull request merged**
