### PR TITLE
Show volumetric multiplier using M503 command

### PR DESCRIPTION
**Pull request by clefranc**
- Adds volumetric multiplier info to the print settings command into M200
  section.
- This PR shows that the volumetric multiplier is not updated while
  using the filament LCD menu.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Not sure that this should be appended at the end inside braces, in case it gives the impression that `M200 M<vm>` is a legal option. Maybe parentheses instead...?

```
M220 D3  (volumetric multiplier = 0.992)
M220 T1 D3  (volumetric multiplier = 1.12)
```

**Comment by clefranc** [comment]
@thinkyhead I don't think this PR will be very useful in the long term, I've done it just to show what I think is a bug:

This PR shows that the volumetric multiplier is not updated while using the filament LCD menu.

When modifying the filament diameter in the LCD menu, the volumetric multiplier is updated only when volumetric is switch off/on (LCD menu). The M503 shows this behavior.

When using the M200 command, the multiplier is updated fine.

**Comment by thinkyhead** [comment]
Weird, and seems like it must be related to #1460.

**Comment by clefranc** [comment]
Not needed anymore with https://github.com/MarlinFirmware/Marlin/pull/1526

**Pull request closed without merging**
