### PR TITLE
PIO 4 strict parser fix

### PR DESCRIPTION
**Pull request by GMagician**
~~Not sure if old value 1 is really 'chain'~~
Confirmed 1 is chain. It's also default so it could be removed

### CODE REVIEW

**Comment by sl1pkn07** [comment]
https://github.com/MarlinFirmware/Marlin/issues/14570 related

please change also default_envs instead of env_default

greetings

**Comment by GMagician** [comment]
> please change also default_envs instead of env_default

default_envs was already been changed and reverted.
PIO should also be changed to use 3.0 and not 2.7 so I think full 4.0 support will be postponed

**Comment by sl1pkn07** [comment]
PIO 4.0 is released days ago and is installed by default with the PIO VScode and PIO Atom IDE (now deprecated in favour of VScoode). 

posponed is not a option

**Comment by GMagician** [comment]
note that env_default will be dropped on next PIO version, this is what warning says, so I suppose it will work till > 4.0.
Since I don't know why it was reverted I'm not in the position to PR it again

**Comment by sl1pkn07** [comment]
more than drop, is not use with vscode IDE. but is still used if use PIO from CLI 

example:

~~~bash
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/Creality Ender 3/Marlin]|
└───╼  cat platformio.ini |grep default_envs
default_envs = LPC1768
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/Creality Ender 3/Marlin]|
└───╼  pio --version
PlatformIO, version 4.0.0
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/Creality Ender 3/Marlin]|
└───╼  pio run
Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/master.zip; framework: arduino; board: nxp_lpc1768)
--snip--
~~~

**Comment by pfeerick** [comment]
It'll still work on PIOv4 regardless where you run it from... as the VSCode/Atom extensions are only an interface between the editor and the PlatformIO CLI anyway. If you use depreciated syntax that's being phased out, you'll just a warning like

```
Warning! `env_default` configuration option in section [platformio] is deprecated and will be removed in the next release! Please use `default_envs` instead.
```

until the setting *is* phased out, and it becomes an error. So it's just a polite reminder that things have changed, and you might want to fix things up before they become errors. 

It's probably worth having a look at the [3 -> 4 Migration Guide](https://docs.platformio.org/en/latest/migration.html) to see if there is anything major that needs to be changed before 'supporting' PIOv4. 

As AFAIK, PIO works just fine with Python 2.7 still (or is for me on Windows and Linux), so that shouldn't be an issue, but once all the kinks are fixed in the Python3 support, it should work in a Python3 environment without any issues. It seems there are still some teething issues around getting it working in a Python3 only environment still.

**Pull request merged**
