### PR TITLE
Fix: Debug Memory Dump size

### PR DESCRIPTION
**Pull request by robbycandra**
Fix Debug Memory Dump size

### CODE REVIEW

**Comment by robbycandra** [comment]
Second commit fix compile error if enable M100_FREE_MEMORY_WATCHER, but disable M100_FREE_MEMORY_DUMPER.

**Comment by Roxy-3D** [comment]
~~~
-    #if ENABLED(M100_FREE_MEMORY_WATCHER)
+    #if ENABLED(M100_FREE_MEMORY_DUMPER)
~~~

Let's not change the option's name until it is working for everybody.    And if the option's name changes, there needs to be corresponding change in all the example Configuration.h files.

**Comment by robbycandra** [comment]
Hi @Roxy-3D ,

Its not changing the option name. 

M100_dump_routine declared if M100_FREE_MEMORY_DUMPER defined

```
#if ENABLED(M100_FREE_MEMORY_DUMPER)
 ...
  inline void dump_free_memory(const char *ptr, const char *sp) {
  void M100_dump_routine(PGM_P const title, const char *start, const char *end) {
... 
#endif // M100_FREE_MEMORY_DUMPER
```

Therefore 

if we define M100_FREE_MEMORY_WATCHER but not define M100_FREE_MEMORY_DUMPER, we will have compile error. 

This code below is from M100.cpp

```
#define M100_FREE_MEMORY_DUMPER     // Enable for the `M100 D` Dump sub-command
#define M100_FREE_MEMORY_CORRUPTOR  // Enable for the `M100 C` Corrupt sub-command
```

**Comment by Roxy-3D** [comment]
> Therefore
> if we define M100_FREE_MEMORY_WATCHER but not define M100_FREE_MEMORY_DUMPER, we will have compile error.

My Mistake!   Perhaps we should add a Sanity Check to catch this configuration error?  Does this compile in the 32-bit world now?

**Comment by robbycandra** [comment]
I never try on 32-bit. :(

**Comment by ghost** [comment]
For LPC1768 I can confirm the compiler error and the needed commit [70a8f2b](https://github.com/MarlinFirmware/Marlin/pull/13957/commits/70a8f2b599ba14723bcd1a7e446d693ea46083a3)

**Comment by Roxy-3D** [comment]
Thanks FanDjango!

**Pull request merged**
