### PR TITLE
USB Mass Storage Implementation / CDC with HW flow control and misc fixes and improvements for Arduino DUE/RE-ARM based boards

### PR DESCRIPTION
**Pull request by ejtagle**
Well, this patchset does some very interesting and requested things for Arduino DUE:
-Improves the SW SPI even further, now we actually reach 12mhz on the SPI clock, and that improves SD card transfer speeds to about 600kbytes/second. This is very desirable, so we can access the SD as an external disk drive
-Fixes the timing of the ST7290 so it works on RE-ARM boards and also on RAMPS4DUE (Thanks @Bergerac56 for testing this!! )
-Implements a new USB CDC device with USB native flow control. No more overruns should be possible
-Implemented CRC7 checks on SDcard commands and also several improvements there, including backports of fixes from the latest SdFat library.
-Now the Sd2Card also switches speed on SW SPI implementations properly (this is required for proper implementation of the last feature of this patch)
-Finally, we also implement a USB MSD (external disk), so when you plug the native usb port of the DUE to your PC, you will get the SD card reflected as an external storage device. Transfer speeds are about 600kbytes/per second

@thinkyhead : Some files (*.c and *.h on the usb subfolder i added) came from ATMELs ASF SDK. I isolated the required files from the mess the ASF source code is, modified them to be able to compile them under Arduino environment and runtime, (Arduino runtime is quite old, so the files had to be modified... but i tried to keep modifications as small as possible. That is the reason i didn't reformat them. Hope you'll understand)

### CODE REVIEW

**Comment by psavva** [comment]
@teemuatlut, does this help with the interfacing with your TMC Library on the Re-Arm using PlatformIO?

**Comment by teemuatlut** [comment]
The SPI changes seem to be for DUE, so that wouldn't do anything. The main requirement fir Re-Arm was having a file that implements a SPI class with the few methods that are needed for communication. I'm not sure if that was solved already.

**Comment by tig33r** [comment]
Still not solved for mks sbase lpc176x.

**Comment by ejtagle** [comment]
Just a comment: The Software SPI functionality that i have implemented is hardware agnostic. It only requires an ARM based CPU, so it could be ported to LPC if needed

**Comment by tig33r** [comment]
The problem with TMC library exist because spi commands for arduino based boards are different than for lpc176x I guess. Somebody have to adjust it. Correct me somebody if I am not right.

**Comment by alexborro** [comment]
Nice job. 
Just a strong recommendation: *always* split different features/fixes in more PRs. Each feature or fix must be integrated in a individual PR. 
Cheers. 

Alex.

**Comment by ejtagle** [comment]
@alexborro : I know ... But it makes it much harder and slower to push related fixes: Each one depends on the previous one, and without looking at them globally, the need of each PR is lost.
I consider the Due HAL a monotonic thing, that is why i just opened one PR for this complete patchset.

**Comment by Bob-the-Kuhn** [comment]
@ejtagle - please take a look at PR #8860.  It implements the Reprap Discount Full Graphic Smart Controller in a different manner.  

The reasons I like this approach are:
a) allows selection of the LCD pins the same as for other controllers
b) similar to LPC1768 (common device driver with com drivers specific to each CPU)

I've tested it on my RAMPS-FD V1

----

Thanks for your work on Due.  I'm going to resurrect my printer using the Due.

----

I like your __delay_4cycles routine.  Seems to be less affected by compiler optimization which makes it easier to get the timing in the right area.

**Comment by Bob-the-Kuhn** [comment]
I remember the other thing I wanted to ask.

I'm using Platformio and it complains about the TMC26xx drivers.  How do you get around that?

**Comment by ejtagle** [comment]
@Bob-the-Kuhn I'll test it. The only problem that could happen here is that RE-ARM also uses this driver, and we had to increase DELAY_NS() from 500 to 700 , giving an SPI clock of 700khz. I can't test the RE-ARM version

The __delay_4cycles is cycle accurate on cortex m3 and cortex m4. And i think it could be shared between all ARM based boards...

Not using PlatformIO. There are problems with the TMC26xx ,,, probably we need to ifdef them appropiately...

**Comment by Bob-the-Kuhn** [comment]
RE-Arm isn't affected by my change so testing isn't needed.

I need to adjust the timing on my PR.  I see a 1 big shift randomly on the display.

**Comment by ejtagle** [comment]
I am working on this also. Display is not initialized properly with your patch, and i do suspect a timing or an initialization sequence problem that is incompatible with some displays, not all of them...

I do share the idea of unification, but we must find out the problems with the native u8glib driver first

**Comment by Spawn32** [comment]
nice to see work being done to a USB Mass Storage Implementation, great work @ejtagle  :)

**Comment by ejtagle** [comment]
This is ready to be merged. It is working. What we are talking about with @Bob-the-Kuhn is then, after this patch is applied, to replace a different part (Graphics LCD interfase) with a generic one that also works for LPC and DUE

**Comment by psavva** [comment]
And I would be eternally grateful if the TMC drivers SPI Interface could also be made to work with the LPC chips :)

**Comment by Bob-the-Kuhn** [comment]
@psavva - see issue #8334.  Looks like tcm0116's comment on Nov 9 will work with the current TMC2130.

**Comment by fiveangle** [comment]
This change breaks all teensy20pp targets - see #8898

**Comment by thinkyhead** [comment]
Resolved with #9069

**Pull request merged**
