### PR TITLE
Adjust runout distance menu edit if FILAMENT_MOTION_SENSOR enabled.

### PR DESCRIPTION
**Pull request by vovodroid**
When FILAMENT_MOTION_SENSOR is enabled increase runout edit precision to 0.1mm and reduce maximum to 10mm.

### CODE REVIEW

**Comment by robherc** [comment]
Why would this be seen as an improvement? Most filament runout sensors will be much more than 10mm away from the extruder (extremely frequently more than 100mm), and whether you stop 0.1mm away from the absolute end of the filament, or 1.5mm, makes very little difference in "the grand scheme."

**Comment by vovodroid** [comment]
If you have filament motion sensor, you would like to stop printing ASAP.

**Comment by robherc** [comment]
> If you have filament motion sensor, you would like to stop printing ASAP.

In that case, you have no need for any distance measurement, because you're trying to "stop right now."

I think the *intent* of the runout distance is for those of us who would prefer to know the filament is running out while there's still time to prep the next spool before the printer runs out; but then have the printer auto-pause before it ruins the print, if we haven't manually changed it yet.

**Comment by vovodroid** [comment]
Morion sensor could have some reporting delay, i.e. there is delay between actual motion and detection, so you need some tolerance. Anyway Marlin has only one distance, and you can't set large for runout and small for morion.Look at BTT SFS documentation for example.

**Comment by robherc** [comment]
Ok, so if using a motion-detector, just set length to 1mm and be done, if that is your worry.
Or is there some other concern here?

**Comment by vovodroid** [comment]
Exactly. And if you need distance about 1-2mm it's better to have precision like 0.1 and also small range.

**Comment by robherc** [comment]
but you said you have no ability to use the precision (so no benefit), and by reducing the range you would completely destroy a very useful feature for everyone with microswitch runout sensors (so major detriment).

**Comment by vovodroid** [comment]
I reduce range only if motion sensor is enabled. For runout sensor nothing changes.

**Comment by robherc** [comment]
Ok, the new change is fine for my purposes. 
Idk how everyone else who uses motion sensors will respond, because I would expect some of them to prefer higher lengths too, but I can't speak for them necessarily.

**Comment by vovodroid** [comment]
> I would expect some of them to prefer higher lengths too

Currently I use 2.4mm. I started from 2.0, and increased it due to false detection.

**Comment by robherc** [comment]
> Currently I use 2.4mm. I started from 2.0, and increased it due to false detection.
...so this length is being used as the amount of filament-travel between "clicks" on the fil. motion detector...seems like that should be an entirely different variable.

**Comment by vovodroid** [comment]
> this length is being used as the amount of filament-travel between "clicks" on the fil. motion detector

Exactly

>seems like that should be an entirely different variable.

Yes, but it's another issue.

**Pull request merged**
