### PR TITLE
Fix Spelling Mistake in UBL's Mesh Status

### PR DESCRIPTION
**Pull request by Roxy-3D**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Extra commits fell into this PR. Is this repo acting up again?

**Comment by Roxy-3D** [comment]
> Extra commits fell into this PR. Is this repo acting up again?

This was done using GitHub-DeskTop.    If I delete my copy of the repository and re-fork, I can start fresh.    But there doesn't seem to be a way to take your local repository and start a Pull Request at a particular point in time.  (Like after the last Pull Request)    At least...  I haven't figured it out yet.

I did try doing those 'Tip of the Day' commands but they mangled my repository on my laptop.   I think I was supposed to create a new directory and change-dir into it.   I'm not sure what went wrong, but what I ended up with wasn't usable.

If you look...  The first commit was turned into a Pull Request and merged.   The second commit was turned into a Pull Request and merged.   And this is the third one.   For some reason...  Even though the previous stuff has been merged and a Sync done, it still wants to add that to the pull request.

How big of a problem are these extra commits being tacked on?   If they are a serious problem, I can delete my repository, re-fork, re-clone for each Pull Request.   But if it is just a little bit of noise that can be ignored, it might be better to only delete, re-fork, re-clone every 3 or 4 Pull Requests.   The one good thing is all of those commits deal with related topics.   But they are logically separate.   Your thoughts?

**Comment by ghost** [comment]
>take your local repository and start a Pull Request at a particular point in time. (Like after the last Pull Request)

- Click `Sync` to ensure that all is up to date.
- At the top of the desktop, select the `MarlinFirmware/RCBugFix` branch
- Click the fork icon to the left of that and type in a name for the new branch. (You can also select here what branch to fork from, in case you missed the previous step.)
- Make your changes
- Click Pull Request at the top right.

Does that do what you want?
It will create a branch after the last merge, not the last PR.

**Comment by ghost** [comment]
>I did try doing those 'Tip of the Day' commands but they mangled my repository on my laptop. I think I was supposed to create a new directory and change-dir into it. I'm not sure what went wrong, but what I ended up with wasn't usable.

I have the same trouble trying to squash.

**Comment by Tannoo** [comment]
@thinkyhead, I got this after executing `git rebase -i HEAD~7`:
```
~\Documents\GitHub\Tanno\Marlin-Main [RCBugFix---DHT ≡]> git rebase -i HEAD~7
Successfully rebased and updated refs/heads/RCBugFix---DHT.
~\Documents\GitHub\Tanno\Marlin-Main [RCBugFix---DHT ↓88 ↑59]>
```
What do I do now?

**Comment by Roxy-3D** [comment]
> I have the same trouble trying to squash.

I was able to squash every time I tried it using @Bob-the-Kuhn 's directions.   But I did run into some conflicts a few of those times.

**Comment by Roxy-3D** [comment]
> - Click Sync to ensure that all is up to date.
> - At the top of the desktop, select the MarlinFirmware/RCBugFix branch
> - Click the fork icon to the left of that and type in a name for the new branch. (You can also select here > what branch to fork from, in case you missed the previous step.)
> - Make your changes
> - Click Pull Request at the top right.
> - Does that do what you want?
> - It will create a branch after the last merge, not the last PR.

OK...   I will try that!   And I'm guessing I will need to give the branch a new name because there will already be a branch with the RCBugFix name, right?    And I'm guessing that to create a pull request, I'll have to specify more stuff somewhere.    Can you clear this up for me:  I've been creating the pull requests from the GitHub web page for my repository.   If I create a new branch, would I do it from the new branch's web page?

**Comment by ghost** [comment]
Yes...new name based on the PR you want to submit.
The branch will be created from the desktop.
The PR will be created from the desktop also.

**Comment by ghost** [comment]
I did the power_supply_0, PR from the desktop. As just about all of my PR's.

**Comment by ghost** [comment]
Choose a name that makes since to you. Like RCBugFix---UBL.
That will be just the branch name not the name of the PR.

**Comment by Roxy-3D** [comment]
> Choose a name that makes since to you. Like RCBugFix---UBL.

I'm sure it won't go smoothly...   I'll back up the whole directory before I start pressing buttons!

**Comment by ghost** [comment]
That's the easy part for me.
I just broke my local copy of my repo trying to squash one branch. Nothing will sync now. So, I have to delete all of the local files and re-clone again.

All back to where it was now.

**Comment by Roxy-3D** [comment]
> I just broke my local copy of my repo trying to squash one branch. Nothing will sync now. So, I have to delete all of the local files and re-clone again.

I followed the squash directions in Bob's dissertation.   That works.   But, the brute force method works too.   You set the directory aside in a safe place.  You delete your repository on GitHub.  You re-fork.  And then you just do visual diff of all the changes that appear between the two directories and get your changes into the new clone.    It shouldn't be that hard...   But that does work.

**Comment by ghost** [comment]
LOL! That's what I was going to do (kind of) when everything stops changing with the wind. ;P
Does that keep with the current PR's?
I was just going to close the current and create another PR (using the same method I told you).

**Comment by ghost** [comment]
The brute force squash of 59 commits was giving me soo many conficts. I can resolve conflicts in the desktop, but unsure where to correct conflicts that the rebase gives me.

A lot of the commits are just updating from RCBugFix.

**Comment by Roxy-3D** [comment]
That is where doing the visual diff of the two directories might make sense.  You start with the current, already merged stuff.   And then just decide what to do about each and every difference.  I don't like the way Git litters the source file with all that <<<<<<HEAD and what ever markers.   I don't want them messing with my source files.

**Comment by ghost** [comment]
It does that when there is a conflict to resolve.

**Comment by ghost** [comment]
Select RCBugFix branch.
github 4_3_2017 4_00_28 pm

Create new branch.
github 4_3_2017 4_02_36 pm
github 4_3_2017 4_03_02 pm

Compare against RCBugFix.
github 4_3_2017 4_03_22 pm

Make your changes.
github 4_3_2017 4_12_00 pm

Commit and sync.
github 4_3_2017 4_19_01 pm

Create PR.
github 4_3_2017 4_19_34 pm

**Comment by Roxy-3D** [comment]
Yes, but you are pointing right at github.com/MarlinFirmware/Marlin, right?   I don't want to create a new branch there.   I only want the new branch in my GitHub area.

**Comment by ghost** [comment]
No. It created the branch in my repo FROM `MarlinFirmware/RCBugFix`.

**Comment by ghost** [comment]
I can't show you more atm... I am at work now.

**Comment by Roxy-3D** [comment]
> I can't show you more atm... I am at work now.

Not a problem...   This is enough I should be able to go through each step and figure things out.  This was very helpful!

UPDATE:  Actually... I meant to say:  This will be very helpful!  Until I need to make another Pull Request, I won't go through the steps.  But I will follow this path on the next one.

**Comment by thinkyhead** [comment]
Working on those videos now in earnest.

**Pull request merged**
