### PR TITLE
Wrangle RAMPS variants and derivatives

### PR DESCRIPTION
**Pull request by thinkyhead**
Addressing https://github.com/MarlinFirmware/Marlin/issues/2071#issuecomment-236087385

**Background:** For generic RAMPS boards we can specify EFF, EFB, or EEB to assign specific functions to the high power PWM outputs. However, we don't provide this option for RAMPS derivatives. Thus, for boards like Azteeg X3, it takes some extra finagling to reassign the power outputs to other than their specified purpose.

**Solution:** This PR consolidates the assignment of the high voltage outputs by pre-assigning the pins for these connectors as `RAMPS_D8_PIN`, etc., and then assigning the specific power outputs based on the selected RAMPS variant.

This PR required also:
- Drop `pins_RAMPS_13_EFB.h` and `pins_RAMPS_14_EFB.h`
- Pre-assign `IS_RAMPS_XXX` defines in `pins.h`
- Use `IS_RAMPS_XXX` defines in `pins_RAMPS.h`
- Provide a fallback for heaters/fans on RAMPS derivatives
- Assign `HI_VOLT_PIN_D` on boards with an extra output

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
Could this be a good idea for all RAMPS based boards, or will this result in lots of support questions?

**Comment by jbrazio** [comment]
**My comment is not specific for this PR is just an POV and a open question for people to discuss.**

How far do we want to complicate things ?
All of them are glue logic which is sorted out at compile time.
IMO there is no added value of spaghetti `#include` over complicating them when we got no runtime added value.

**Comment by thinkyhead** [comment]
> Could this be a good idea for all RAMPS based boards

It would seem to make sense.

**Comment by thinkyhead** [comment]
> How far do we want to complicate things?

We are moving in the direction of simplifying things from the user perspective. Sometimes this means doing extra work behind the scenes. In the process we try to keep things organized for contributors and maintain consistency.

In the process of evolution there comes first a stage of **elaboration**. Through this process we address the weaknesses of the system, often in a very patch-up manner. But from this process we begin to see patterns, and then follows a process of **revision** where we utilize those patterns. Marlin has gone through many such cycles.

**Comment by thinkyhead** [comment]
> IMO there is no added value of spaghetti #include over-complicating them when we got no runtime added value.

Obviously doesn't apply to this PR. By all means, when you see something getting overcomplicated, aim to simplify it. But not so simple that it misses the nuances.

**Comment by thinkyhead** [comment]
I noticed one odd detail while putting this together. The "EFF" variant of RAMPS assigns the `HEATER_0_PIN` and `FAN1_PIN` in reverse to all the other RAMPS arrangements. I would change it, but it would be bad for those with existing EFF setups wired in this way. This is what @moo1426 is pointing out in #4462.

**Comment by Blue-Marlin** [comment]
Actually these pins have the capability to handle high currents. That's the key feature to drive a heater. Voltage is secondary - helps to drive a high current true the heaters resistance.

**Comment by thinkyhead** [comment]
Just naming them after the RAMPS pins, D8-D10.

**Pull request merged**
