### PR TITLE
PR for #2357

### LINKED ISSUE #2357: Z home offset not working (M206)
Similair to #1936.

My mendel90 homes upward to top endswitch at approximately 190mm above the bed (measured from nozle to bed.

I replaced parts of the bed, now it is 190.something. (190.2 to 190.5 I think)

Instead of changing configuration.h and reuploading firmware I thought about using M206 to set a home offset for Z. This does not work.

So, I got the newest "dev" branch (https://github.com/Lukelectro/Marlin/tree/Development)
It still does not work.

Here is what I did and what I expected:
- Homed Z (to top): `G28 Z`
- After home, `M114` says Z is at 190. That is correct.
- Go to `Z0`: `G1 Z0`
- Report: `M114` confirms `Z0`. Head is above the bed by approx. 0.2mm
- `M206 Z0.5` (set home offset)
- `G28 Z` to home Z again. `M114` now reports 190.5 after home so that should be right, thats what I expected. 
- `G1 Z1` to stay clear for sure, then down in small steps using the buttons in the gui.

Some 0.2mm to 0.5mm above the bed the head won't go down any further. That's not what I expected.
M114 reports Z at 0.5mm. So there should be room to go down further... Lets be bold: `G1 Z0`. Printer does not move. That's strange.

Does anybody else have a printer homing to top and the same issue?

(I will try to fix this one too, instead of only reporting it :))

### PR DESCRIPTION
**Pull request by Lukelectro**
Attempt to fix #2357

This is my first pull request so I will probably learn something. (AKA guaranteed too include mistakes)

Should only include https://github.com/MarlinFirmware/Marlin/commit/a321f31f84b666070b24dbdf9351c1312c086651 but I do not yet know how to only include certain commits. (Should I make a special branch for each PR? Please tell me.)

Code includes comments that should clarify what I changed and why.

### CODE REVIEW

**Comment by Wackerbarth** [comment]
@Lukelectro -- Some comments on forming your pull request.
When you have some feature/patch to propose, you should do the following:
(1) Update (pull) your repository to include the latest version of the branch that you are proposing to change (MarlinFirmware:Development)
(2) Create a new branch, with an appropriate name that can be associated with the feature (LCD_Z_INVERSION), starting from the Development commit above.
(3) Rebase and/or cherry-pick the changes that apply to your change (In this case commit a321f31).
(4) Checkout, compile, and test this change.
(5) Push the branch to your github account
(6) Make the pull request on MarlinFirmware

I see that the Travis run failed. That is because you have a non-default processor defined in some of those "extra" commits that got included.

If you follow the procedure that I outlined above, you should be able to push a new version of your proposal. However, since you used "Development" as the branch, you may find it easier to close this PR and open another referencing a new branch name (your choice)

**Comment by boelle** [comment]
the build failed, please rebase on latest devlopment

**Comment by Lukelectro** [comment]
Working on it. Will open a new PR with a better branch name.

**Comment by Lukelectro** [comment]
And now of course the "new" version I based it on is no longer new. I think I'll test the new new version first before making changes to it. (Haven't been working on the software of my printer for a while.)

**Comment by boelle** [comment]
also post PR's to https://github.com/MarlinFirmware/MarlinDev

**Comment by boelle** [comment]
we started a new repo for all dev work... and this one seems to be one of the most important issues to get fixed first... ie homing and leveling issues

**Pull request closed without merging**
