### PR TITLE
Fysetc Cheetah foundations

### PR DESCRIPTION
**Pull request by trouch**
### Requirements

- A Fysetc Cheetah Board https://wiki.fysetc.com/Cheetah_Board/
- Up to date PlatformIO env and dependencies
- Use provided sample configuration or manually set minimal macros:
  - `#define SERIAL_PORT 1`
  - `#define MOTHERBOARD BOARD_FYSETC_CHEETAH`
  - `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
  - `#define SDSUPPORT`
- Use `fysetc_CHEETAH` PlatformIO env/task

### Description

This PR serves as a base to merge https://github.com/FYSETC/Marlin-2.0.x-FYSETC upstream.
I've resolved git conflicts and few runtime ones that I noticed by digging (TMC2209 hooks), cleaned up unused code with the build, and minimized upstream changes as much as possible.

There are some changes I'm not sure if they are required or not, that I merged into a separate branch, see https://github.com/trouch/Marlin/commit/c68291c1969019387e0fa9bfa5889c647c42e58c

So far the Cheetah firmware builds properly, but unfortunately I don't have a Cheetah board yet to test, couple are on their way. 

AIO one doesn't compile, but it doesn't either by using Fysetc branch.

### Benefits

Adds a real STM32F103 based board support. 

### Related Issues

None AFAIK.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Squashed, rebased, updated configs, cleaned up, etc. To get the fixed branch in your working copy open the Git Console and issue the following commands:
```
git checkout integration/fysetc
git fetch origin
git reset --hard origin/integration/fysetc
```

**Comment by 3DSmitty** [comment]
Wow I have to say the AIO II V3.1 is very cool. True meaning to all-in-one!!!

**Comment by thinkyhead** [comment]
Please follow up with additional PRs if more changes are needed.

**Comment by thisiskeithb** [comment]
Why would you use `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` instead of `CR10_STOCKDISPLAY`?

**Comment by trouch** [comment]
> Why would you use `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` instead of `CR10_STOCKDISPLAY`?

I was wondering the same, not sure why Fysetc uses that. Probably because their pins_ file wasn't complete to cover all the variants. I'm waiting for feedback from them or to test it on a board myself.

**Comment by thisiskeithb** [comment]
Ahh, yes. I didn't check out the pins file. It looks like that can be updated to include support for more LCD types.

**Comment by paulpenney** [comment]
Any updates on this board? Currently the two major issues are that the EEPROM writing to flash does not seem to work, and that the sensorless homing using the TMC2209's isn't working either.

**Comment by Christopher-Dom** [comment]
Hey guys,
Any progress for the TMC2209 sensorless homing?

**Pull request merged**
