### PR TITLE
Borrow from Ultimaker to fix MAX6675 SPI conflict

### PR DESCRIPTION
**Pull request by thinkyhead**
Changes to temperature.cpp from @daid Ultimaker fork, to address issues #1226, #1227, et. al. Based on https://github.com/Ultimaker/Ultimaker2Marlin/commit/91c64e356348decee934b816269a25e7c42e8071

### CODE REVIEW

**Comment by daid** [comment]
Note that this does move the temperature sensor safety out of the interrupt. Which is fine as long as the watchdog is enabled (which I recommend anyhow, as the advantages outweigh the disadvantage by a long shot)

**Comment by Grogyan** [comment]
I'll try this out later this weekend.
Little bit busy right now.
Looks promising

Cheers

**Comment by thinkyhead** [comment]
If this requires WATCHDOG to work, then we might want to make WATCHDOG a requirement when MAX6675 is enabled.

**Comment by daid** [comment]
It does not require it to work. But the watchdog is good added safety.

**Comment by thinkyhead** [comment]
Merging this for testing purposes. I don't foresee any problems, but keeping this issue in my notification queue for feedback.

**Pull request merged**
