### PR TITLE
Games, for fun (and stress-testing)

### PR DESCRIPTION
**Pull request by thinkyhead**
Some badly-implemented mini-games for the people. Some frivolity ahead of MRRF 2019.

### CODE REVIEW

**Comment by AnHardt** [comment]
I hoped we'd have the 1st of April.
But no.  =:-o

**Comment by thinkyhead** [comment]
It's such a parody (and meta-parody) regardless of the date, so I decided to put it out early.

**Comment by marcio-ao** [comment]
@thinkyhead: Oh man, can't wait to try this! Now I guess we have to add games for our color LCD...

**Comment by marcio-ao** [comment]
@thinkyhead: This. is. awesome.

I get a compile error with the maze one, but the others work great on our Mini 2! With the Maze, I get the following error:

```
In file included from src/lcd/menu/menu_game.cpp:27:0:
src/lcd/menu/menu_game.cpp: In function ‘void menu_game()’:
src/lcd/menu/menu_game.cpp:1024:36: error: ‘lcd_goto_maze’ was not declared in this scope
       MENU_ITEM(submenu, MSG_MAZE, lcd_goto_maze);
                                    ^
src/lcd/menu/menu.h:276:45: note: in definition of macro ‘_MENU_ITEM_VARIANT_P’
         MenuItem_##TYPE ::action ## VARIANT(__VA_ARGS__); \
                                             ^
src/lcd/menu/menu_game.cpp:1024:7: note: in expansion of macro ‘MENU_ITEM’
       MENU_ITEM(submenu, MSG_MAZE, lcd_goto_maze);
       ^
```

I'll try tracking this down.

**Comment by marcio-ao** [comment]
I guess the maze isn't implemented? Maybe that's the April fools joke?

**Comment by marcio-ao** [comment]
> Some badly-implemented mini-games for the people.

These games are perfect! They work great! Not sure what is badly implemented about them...

**Comment by thinkyhead** [comment]
I'm glad you like them and they aren't broken. The maze game is still under development.

**Comment by psavva** [comment]
LOL, I'll be trying this out :)
If you can play a game while waiting for a print to finish would be cool :P

**Comment by marcio-ao** [comment]
> If you can play a game while waiting for a print to finish would be cool :P

In "hard" mode, a "Game Over" means your print stops and you can't recover it :)

**Comment by Roxy-3D** [comment]
Is the Maze being worked on?    That is the one I want to see working!

**Comment by marcio-ao** [comment]
> Is the Maze being worked on? That is the one I want to see working!

Is it 3D like Doom? :)

**Comment by marcio-ao** [comment]
@thinkyhead:

https://www.reddit.com/r/3Dprinting/comments/crtqkk/this_video_games_machine_called_the_lulzbot_taz/

**Pull request merged**
