### PR TITLE
LVGL G-Code preview, compatibility with old versions of MKS Wifi Cura Plugin

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

This PR fixes an issue that can could hang a board if g-code preview is generated by an old version of the MKS Wifi Cura Plugin.

### Related Issues

#20564 
#19914

### CODE REVIEW

**Comment by X-Ryl669** [comment]
You still need to zoom the picture (since what you get from file is 50x50 and what LVGL requires is 100x100). You'll need to copy all pixels horizontally twice, and recall each line twice (if you seek, it does not work). In the end, this PR still does not work (try with the attached gcode from the bug). I'll try to capture the resulting picture of it tomorrow if it works.

BTW, look at my fix, you'll find the zooming code to reuse (but you'll still need to deal with seeking backward to re-read the same line to zoom vertically).

**Comment by rhapsodyv** [comment]
There's no need to rewrite anything or waste time, or add zoom for small images..... all about 50x50 is just compatibility with older version of the MKS Wifi Cura plugin.

New versions (for a while) already save it at 100x100. https://github.com/makerbase-mks/mks-wifi-plugin/blob/87df6145129c39b1a1a4725bc33b44591b60314f/MKSWifiPlugin/SaveOutputDevice.py#L127

Update your plugin and be happy.

**Comment by rhapsodyv** [comment]
In fact, MKS Wifi Cura plugin is saving a 100x100 image for 10 months already!!!

**Comment by rhapsodyv** [comment]
He is your file, fully working.image

**Comment by X-Ryl669** [comment]
I've installed the cura plugin from the Ultimaker store in october. I don't know what version it is, but it has this line in `~/cura/4.8/plugins/MKSWifiPlugin/MKSWifiPlugin/SaveOutputDevice.py`:
```
if image and utils.printer_supports_screenshots(global_container_stack.getName()):
                save_file.write(utils.add_screenshot(image, 100, 100, ";simage:"))
                save_file.write(utils.add_screenshot(image, 200, 200, ";;gimage:"))
                save_file.write("\r")
            else:
                Logger.log("d", "Skipping screenshot in SaveOutputDevice.py")
```
So I really don't understand how I could have received 50x50 pictures. I'm not inventing the files, you can see them as I've copied them. I'll try to slice more files to see if it still create such small pictures.
In your screenshot, it's not fully working, it's only 1 quarter of the expected picture, yet, if the code is simpler, and the 50x50 pictures are not being generated anymore, I'm all ok for it.

**Comment by rhapsodyv** [comment]
Probably you have files generated from a old version, or an installation issue.

> In your screenshot, it's not fully working, it's only 1 quarter of the expected picture, yet, if the code is simpler, and the 50x50 pictures are not being generated anymore, I'm all ok for it.

Afff.... 50x50 is 1/4 of 100x100........... The image is correct. It's loading the 50x50 picture and showing it as a 50x50 picture. As I said, there's no reason to do anything more than just show it, as all other previews are being generated as 100x100 for months...

**Comment by X-Ryl669** [comment]
Indeed, I had the MKSWIFIPlugin v1.0.7 and after updating to v1.1.2, the preview size is increased. Please notice that this version only appeared on the Cura's Marketplace the 4th of december.

**Pull request merged**
