### PR TITLE
Fix Individual Axis Homing / 4520a51 Followup

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

As pointed out in https://github.com/MarlinFirmware/Marlin/issues/24423, an erroneous `G28X` is used instead of `G28` in the "Use MAP for home axis items" refactor / 4520a51 which causes X to always be homed before the selected axis.

### Requirements

Config with an LCD

### Benefits

Homing an individual axis will work correctly again.

### Related Issues

- https://github.com/MarlinFirmware/Marlin/issues/24423

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Also: Through all these recent MAP macros/axis changes, when `MOVE_Z_WHEN_IDLE` is enabled, the LCD says "Move Y" instead of "Move Z", yet Z moves correctly. There are probably other spots within Marlin that now display the wrong axis as well, but I haven't tested them all (and don't really have a good way to do so).

**Comment by Foxies-CSTL** [comment]
> There are probably other spots within Marlin that now display the wrong axis as well, but I haven't tested them all (and don't really have a good way to do so).

Hi,
There is also an error in the Z_Offset wizard that shows the label "X" in the offset adjustment. 
Last BugFix of 29/06 with this PR24425 merged.

**Comment by thisiskeithb** [comment]
> Hi, There is also an error in the Z_Offset wizard that shows the label "X" in the offset adjustment. Last BugFix of 29/06 with this PR24425 merged.

https://github.com/MarlinFirmware/Marlin/issues/24418

**Comment by Foxies-CSTL** [comment]
> #24418

Sorry, I did not see it

**Comment by thisiskeithb** [comment]
> Sorry, I did not see it

I just reopened it. 👍

**Pull request merged**
