### PR TITLE
2.0.x - Idex match119

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Merge changes that made it into 1.1.9 but not 2.0.X

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Are both branches similar now?    
Can you predict what the printer's behavior would be without these changes?

**Comment by InsanityAutomation** [comment]
Yup, both match. Before the ultralcd.cpp change a manual x move always moved x1 while updating the position of active_extruder making bad things happen. Ubl_G29.cpp causes rapid tool change calls that can crash.

**Comment by Roxy-3D** [comment]
>  Ubl_G29.cpp causes rapid tool change calls that can crash.

Did you mean:

>  Ubl_G29.cpp **caused** rapid tool change calls that can crash.

And that is fixed now too?   (I have my fingers crossed!!!)

**Comment by InsanityAutomation** [comment]
Yeah, I still need to get the z position loss referenced in the other open issue, I was able to reproduce it last night. I'll be back after that tonight, fighting Fanuc robots with torque guns today!

**Comment by Roxy-3D** [comment]
@InsanityAutomation    Can you post your IDEX Configuration.h and Configuration_adv.h files?
I want to compare mine against yours.    As much as possible...  I would like to be running in the same configuration as you.

**Comment by InsanityAutomation** [comment]
https://github.com/InsanityAutomation/Marlin/tree/TM_Trex2+_2.0.x Heres where I keep my active stuff. Did you get ahold of Chris's shop Trex?

**Comment by Roxy-3D** [comment]
No...   I think he is using it too much to give up right now.

**Pull request merged**
