### PR TITLE
Update Sensorless Homing Sanity Check for 9-Axis

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Title.

### Related Issues

Reported on Discord.

### CODE REVIEW

**Comment by alfskaar** [comment]
#define SENSORLESS_HOMING
#define I_STALL_SENSITIVITY  8

M911-M914.cpp
output
unused variable 'index' [-Wunused-variable]

I think more files need to be updated.

**Comment by thisiskeithb** [comment]
> unused variable 'index' [-Wunused-variable]

You can ignore that warning for now.

**Comment by alfskaar** [comment]
I have tested SENSORLESS_HOMING on I=A it doesn’t work. I have in the beginning tested SENSORLESS_HOMING on Z and it did work so something have to be off I have looked at the TMC status and everything looks ok to me so it have to be bug in code still. I will just use end stop for now. 
home A
A moves 2mm about and stop.

home A
I have sett the bump
#define SENSORLESS_BACKOFF_MM  { 2, 2, 2, 0 }
Now it doesn’t move at all so something is not right.

**Comment by alfskaar** [comment]
<details><summary>Log Output</summary>

```
Connecting...
ok T:20.67 /0.00 B:21.04 /0.00 T0:20.67 /0.00 T1:-15.00 /0.00 @:0 B@:0 @0:0 @1:0
Printer is now online.
>>>m122
SENDING:M122; M43
		X	Y	Z	Z2	Z3	I	E	E1
Address		0	0	0	0	0	0	0	0
Enabled		false	false	false	false	false	false	false	false
Set current	800	800	800	800	800	800	800	800
RMS current	795	795	795	795	795	795	795	795
MAX current	1121	1121	1121	1121	1121	1121	1121	1121
Run current	25/31	25/31	25/31	25/31	25/31	25/31	25/31	25/31
Hold current	12/31	12/31	12/31	12/31	12/31	12/31	12/31	12/31
CS actual	12/31	12/31	12/31	12/31	12/31	12/31	12/31	12/31
PWM scale
vsense		1=.18	1=.18	1=.18	1=.18	1=.18	1=.18	1=.18	1=.18
stealthChop	true	true	true	true	true	true	true	true
msteps		16	16	16	16	16	16	16	16
interp		true	true	true	true	true	true	true	true
tstep		max	max	max	max	max	max	max	max
PWM thresh.
[mm/s]
OT prewarn	false	false	false	false	false	false	false	false
triggered
 OTP		false	false	false	false	false	false	false	false
pwm scale sum	14	14	13	21	21	46	14	14
pwm scale auto	0	0	0	0	1	3	0	0
pwm offset auto	36	36	32	54	50	107	36	36
pwm grad auto	14	14	14	26	26	14	14	14
off time	3	3	3	3	3	3	3	3
blank time	24	24	24	24	24	24	24	24
hysteresis
 -end		-1	-1	-1	-1	-1	-1	-1	-1
 -start		1	1	1	1	1	1	1	1
Stallguard thrs	0	0	0	0	0	128	0	0
uStep count	40	40	40	1000	1000	488	40	1000
DRVSTATUS	X	Y	Z	Z2	Z3	I	E	E1
sg_result	0	0	134	46	46	46	0	0
stst
olb
ola
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
		X	0xC0:0C:00:00
		Y	0xC0:0C:00:00
		Z	0xC0:0C:00:00
		Z2	0xC0:0C:00:00
		Z3	0xC0:0C:00:00
		I	0xC0:0C:00:00
		E	0xC0:0C:00:00
		E1	0xC0:0C:00:00
Testing X connection... OK
Testing Y connection... OK
Testing Z connection... OK
Testing Z2 connection... OK
Testing Z3 connection... OK
Testing I connection... OK
Testing E connection... OK
Testing E1 connection... OK
```
</details>

**Comment by alfskaar** [comment]
<details><summary>M43 Output</summary>

```
Connecting...
ok T:20.75 /0.00 B:21.05 /0.00 T0:20.75 /0.00 T1:-15.00 /0.00 @:0 B@:0 @0:0 @1:0
Printer is now online.
>>>m43
SENDING:M43
PIN: PA0         M42 P0           Z2_ENABLE_PIN                          protected
PIN: PA1         M42 P1           HEATER_BED_PIN                         protected
PIN: PA2         M42 P2           HEATER_0_PIN                           protected
PIN: PA3         M42 P3           HEATER_1_PIN                           protected
PIN: PA4         M42 P4           SDSS                                   Output = 1
PIN: PA5         M42 P5           DOGLCD_SCK                             Alt Function: 5  - SPI1/SPI2
PIN: PA6         M42 P6           <unused/unknown>                       Alt Function: 5  - SPI1/SPI2
PIN: PA7         M42 P7           DOGLCD_MOSI                            Alt Function: 5  - SPI1/SPI2
PIN: PA8         M42 P8           FAN_PIN                                protected
PIN: PA9         M42 P9           <unused/unknown>                       Input  = 1
PIN: PA10        M42 P10          <unused/unknown>                       Input  = 1
PIN: PA11        M42 P11          <unused/unknown>                       Alt Function: 10 - OTG
PIN: PA12        M42 P12          <unused/unknown>                       Alt Function: 10 - OTG
PIN: PA13        M42 P13          LED_PIN                                Output = 0
PIN: PA14        M42 P14          I_DIR_PIN                              protected
PIN: PA15        M42 P15          <unused/unknown>                       Alt Function: 0  - system (misc. I/O)
PIN: PB0         M42 P16          <unused/unknown>                       Input  = 0
PIN: PB1         M42 P17          BTN_EN1                                Input  = 0
PIN: PB2         M42 P18          BTN_EN2                                Input  = 0
PIN: PB3         M42 P19          <unused/unknown>                       Alt Function: 0  - system (misc. I/O)
PIN: PB4         M42 P20          <unused/unknown>                       Alt Function: 0  - system (misc. I/O)
PIN: PB5         M42 P21          <unused/unknown>                       Input  = 1
PIN: PB6         M42 P22          SERVO0_PIN                             Output = 0
PIN: PB7         M42 P23          Z_MIN_PROBE_PIN                        protected
PIN: PB8         M42 P24          I2C_SCL_PIN                            Alt Function: 4  - I2C1..3
PIN: PB9         M42 P25          I2C_SDA_PIN                            Alt Function: 4  - I2C1..3
PIN: PB10        M42 P26          HEATER_2_PIN                           Output = 0
PIN: PB11        M42 P27          HEATER_3_PIN                           Output = 0
PIN: PB12        M42 P28          <unused/unknown>                       Input  = 1
PIN: PB13        M42 P29          <unused/unknown>                       Input  = 1
PIN: PB14        M42 P30          <unused/unknown>                       Input  = 1
PIN: PB15        M42 P31          <unused/unknown>                       Input  = 1
PIN: PC0         M42 P32          POWER_LOSS_PIN                         Input  = 1
PIN: PC1         M42 P33          Z2_DIR_PIN                             protected
PIN: PC2         M42 P34          <unused/unknown>                       Input  = 1
PIN: PC3         M42 P35          <unused/unknown>                       Input  = 1
PIN: PC4         M42 P36          X_SERIAL_TX_PIN                        Output = 1
.                                 X_SERIAL_RX_PIN                        Output = 1
PIN: PC5         M42 P37          <unused/unknown>                       Input  = 1
PIN: PC6         M42 P38          Z_SERIAL_TX_PIN                        Output = 1
.                                 Z_SERIAL_RX_PIN                        Output = 1
PIN: PC7         M42 P39          Z2_CS_PIN                              Output = 1
.                                 Z2_SERIAL_TX_PIN                       Output = 1
.                                 Z2_SERIAL_RX_PIN                       Output = 1
PIN: PC8         M42 P40          <unused/unknown>                       Alt Function: 12 - FSMC, SDIO, OTG
PIN: PC9         M42 P41          <unused/unknown>                       Alt Function: 12 - FSMC, SDIO, OTG
PIN: PC10        M42 P42          <unused/unknown>                       Alt Function: 12 - FSMC, SDIO, OTG
PIN: PC11        M42 P43          <unused/unknown>                       Alt Function: 12 - FSMC, SDIO, OTG
PIN: PC12        M42 P44          <unused/unknown>                       Alt Function: 12 - FSMC, SDIO, OTG
PIN: PC13        M42 P45          E1_STEP_PIN                            protected
PIN: PC14        M42 P46          <unused/unknown>                       Input  = 1
PIN: PC15        M42 P47          SD_DETECT_PIN                          Input  = 1
PIN: PD0         M42 P48          <unused/unknown>                       Input  = 1
PIN: PD1         M42 P49          <unused/unknown>                       Input  = 1
PIN: PD2         M42 P50          <unused/unknown>                       Alt Function: 12 - FSMC, SDIO, OTG
PIN: PD3         M42 P51          I_SERIAL_TX_PIN                        Output = 1
.                                 I_SERIAL_RX_PIN                        Output = 1
.                                 I_SERIAL_TX_PIN                        Output = 1
.                                 I_SERIAL_RX_PIN                        Output = 1
PIN: PD4         M42 P52          E2_ENABLE_PIN                          protected
.                                 Z3_ENABLE_PIN                          protected
PIN: PD5         M42 P53          <unused/unknown>                       Input  = 1
PIN: PD6         M42 P54          <unused/unknown>                       Input  = 1
PIN: PD7         M42 P55          ESP_WIFI_MODULE_GPIO0_PIN              Output = 1
PIN: PD8         M42 P56          <unused/unknown>                       Alt Function: 7  - USART1..3
PIN: PD9         M42 P57          <unused/unknown>                       Alt Function: 7  - USART1..3
PIN: PD10        M42 P58          <unused/unknown>                       Input  = 1
PIN: PD11        M42 P59          Y_SERIAL_TX_PIN                        Output = 1
.                                 Y_SERIAL_RX_PIN                        Output = 1
PIN: PD12        M42 P60          FAN2_PIN                               protected
PIN: PD13        M42 P61          FAN3_PIN                               protected
PIN: PD14        M42 P62          FAN4_PIN                               protected
PIN: PD15        M42 P63          FAN5_PIN                               protected
PIN: PE0         M42 P64          I_ENABLE_PIN                           protected
PIN: PE1         M42 P65          E2_CS_PIN                              Output = 1
.                                 Z3_SERIAL_TX_PIN                       Output = 1
.                                 Z3_SERIAL_RX_PIN                       Output = 1
.                                 E2_SERIAL_TX_PIN                       Output = 1
.                                 E2_SERIAL_RX_PIN                       Output = 1
PIN: PE2         M42 P66          E2_STEP_PIN                            protected
.                                 Z3_STEP_PIN                            protected
PIN: PE3         M42 P67          E2_DIR_PIN                             protected
.                                 Z3_DIR_PIN                             protected
PIN: PE4         M42 P68          E1_SERIAL_TX_PIN                       Output = 1
.                                 E1_SERIAL_RX_PIN                       Output = 1
PIN: PE5         M42 P69          FAN1_PIN                               protected
PIN: PE6         M42 P70          I_STEP_PIN                             protected
PIN: PE7         M42 P71          BTN_ENC                                Input  = 1
PIN: PE8         M42 P72          BEEPER_PIN                             Output = 0
PIN: PE9         M42 P73          DOGLCD_CS                              Output = 1
.                                 LCD_PINS_ENABLE                        Output = 1
PIN: PE10        M42 P74          DOGLCD_A0                              Output = 1
.                                 LCD_PINS_RS                            Output = 1
PIN: PE11        M42 P75          <unused/unknown>                       Input  = 1
PIN: PE12        M42 P76          LCD_RESET_PIN                          Output = 1
.                                 LCD_PINS_D4                            Output = 1
PIN: PE13        M42 P77          LCD_PINS_D5                            Output = 0
.                                 NEOPIXEL_PIN                           Output = 0
PIN: PE14        M42 P78          LCD_PINS_D6                            Input  = 1
PIN: PE15        M42 P79          LCD_PINS_D7                            Input  = 1
PIN: PF0         M42 P80          E1_DIR_PIN                             protected
PIN: PF1         M42 P81          E1_ENABLE_PIN                          protected
PIN: PF2         M42 P82          E0_SERIAL_TX_PIN                       Output = 1
.                                 E0_SERIAL_RX_PIN                       Output = 1
PIN: PF3         M42 P83          <unused/unknown>   Analog in =     0   Input  = 0
PIN: PF4         M42 P84          <unused/unknown>   Analog in =     0   Input  = 0
PIN: PF5         M42 P85          <unused/unknown>   Analog in =     0   Input  = 0
PIN: PF6         M42 P86          <unused/unknown>                       Input  = 1
PIN: PF7         M42 P87          <unused/unknown>                       Input  = 1
PIN: PF8         M42 P88          <unused/unknown>                       Input  = 1
PIN: PF9         M42 P89          E0_STEP_PIN                            protected
PIN: PF10        M42 P90          E0_DIR_PIN                             protected
PIN: PF11        M42 P91          Z_STEP_PIN                             protected
PIN: PF12        M42 P92          X_DIR_PIN                              protected
PIN: PF13        M42 P93          X_STEP_PIN                             protected
PIN: PF14        M42 P94          X_ENABLE_PIN                           protected
PIN: PF15        M42 P95          Y_ENABLE_PIN                           protected
PIN: PG0         M42 P96          Y_STEP_PIN                             protected
PIN: PG1         M42 P97          Y_DIR_PIN                              protected
PIN: PG2         M42 P98          E0_ENABLE_PIN                          protected
PIN: PG3         M42 P99          Z_DIR_PIN                              protected
PIN: PG4         M42 P100         Z2_STEP_PIN                            protected
PIN: PG5         M42 P101         Z_ENABLE_PIN                           protected
PIN: PG6         M42 P102         X_MAX_PIN                              protected
.                                 X_DIAG_PIN                             protected
.                                 X_STOP_PIN                             protected
PIN: PG7         M42 P103         ESP_WIFI_MODULE_RESET_PIN              Output = 1
PIN: PG8         M42 P104         ESP_WIFI_MODULE_ENABLE_PIN             Output = 1
PIN: PG9         M42 P105         Y_MAX_PIN                              protected
.                                 Y_DIAG_PIN                             protected
.                                 Y_STOP_PIN                             protected
PIN: PG10        M42 P106         Z_DIAG_PIN                             Input  = 1
PIN: PG11        M42 P107         Z2_DIAG_PIN                            Input  = 1
PIN: PG12        M42 P108         FIL_RUNOUT_PIN                         Input  = 0
.                                 E0_DIAG_PIN                            Input  = 0
PIN: PG13        M42 P109         FIL_RUNOUT2_PIN                        Input  = 1
.                                 E1_DIAG_PIN                            Input  = 1
PIN: PG14        M42 P110         FIL_RUNOUT3_PIN                        Input  = 1
.                                 E2_DIAG_PIN                            Input  = 1
PIN: PG15        M42 P111         I_MIN_PIN                              protected
.                                 I_STOP_PIN                             protected
```
</details>

**Comment by thisiskeithb** [comment]
> I have tested SENSORLESS_HOMING on I=A it doesn’t work.

That's outside the scope of this PR since all I did was update the sanity check to allow sensorless homing on all axis.

Please open a proper [Bug Report](https://github.com/MarlinFirmware/Marlin/issues/new/choose) to report this issue.

**Comment by alfskaar** [comment]
I will do that when this is fixed "unused variable 'index' [-Wunused-variable]" this shod be inside the scope I believe.

**Comment by thisiskeithb** [comment]
Unused variables are fine. As I said above, you can ignore it.

**Comment by alfskaar** [comment]
I got it to work. :-) A and B had to re do all the diag pins

**Comment by alfskaar** [comment]
#define QUICK_HOME

And try to build it.

G28.cpp
label "homeY" was referenced but not defined
label "homeZ" was referenced but not defined
label "homeI" was referenced but not defined
label "homeJ" was referenced but not defined
label "homeK" was referenced but not defined
label "homeU" was referenced but not defined
label "homeV" was referenced but not defined
label "homeW" was referenced but not defined

unused variable 'stealth_states' [-Wunused-variable]

**Comment by thisiskeithb** [comment]
@alfskaar Please file a proper bug report. This is not the correct place to report build errors/warnings.

**Comment by alfskaar** [comment]
Yes but to do that I need to be able to reproduce it and now it just magically disappeared all errors/warnings. ;-)

**Pull request merged**
