### PR TITLE
#include "language_en.h" before the national language in language.h

### PR DESCRIPTION
**Pull request by AnHardt**
pros:  May decrease the workload for feature developers. They may omit to
update all the language files but "language_en.h". When loading _en
first, all new features give some display, but the new in English.

cons: May throw some additional warnings about redefinition during compile.

### CODE REVIEW

**Comment by galexander1** [comment]
I am not opposed to the idea of falling back to EN if the string isn't
available in a specific language.  However, if that's the approach, it
needs to be accomplished with something like #ifndef or #undef.
Non-identical re-defines are forbidden by the ANSI standard.

**Comment by AnHardt** [comment]
@galexander1 
So including the national languages first and a #ifndef #endif combo around every #define in language_en.h would be ok for ANSI?
A solution i could live with.

**Comment by AnHardt** [comment]
Done.

**Comment by galexander1** [comment]
Yeah, it looks good to me, and I have no objection to it.

Out of curiosity, is it solving a problem?  The downside is that this
might "sweep under the rug" missing #defines that maybe ideally would
attract translation attention?  Is there some language that currently
doesn't compile because it's missing #defines?

**Comment by thinkyhead** [comment]
In the past, languages were all in one file, so mistakes were more common. With the files now separated, side-by-side comparison is far easier. The approach in the past has been to add every new language define to every language, but first only in English. There should not be any cases where language defines are simply left out, and if there are, we should catch that in the pull requests. This change doesn't really solve a problem, and it creates a new one by adding more burden to translators and breaking the symmetry between the language files. And personally I think Dutch should be the default!

**Comment by AnHardt** [comment]
@galexander1  & @thinkyhead 
My idea was to put new string only in the _en.h file to save work. Now we are putting our new strings into all the language files - but untranslated - maybe with exceptions. In both cases a potential translator will see the untranslated English word and may decide to translate it. He will lock up the definition in _en.h and will add it in his language file. But there may be definitions like MSG_X, where translation for almost no one makes sense but the Japanese who may have their own sign for "X".
Maybe this will simplifie the use of definitions instead of literals and can avoid things like in #1482.

**Comment by thinkyhead** [comment]
I have a Japanese Kana patch pending that I found as a Thingiverse thing (and surely a git repo), so we'll see how that fits the paradigm.

If there are strings that are guaranteed not to need translation, we could add them to `language.h` along with the serial messages (which are only invariant because host software may rely on matching strings). Personally, I like the parallelism between the various language files that are being maintained, and I think it is a good thing to require developers to add new strings to all the language files (and to translate them on their own, if they can). Now what we will have is, users will only add English and one of the collabs (probably me) will see this, step up, and add the new strings to the rest of the files because… _"WTF contributor??"_.

As for #1482, that is not currently problematic assuming no one needs to rearrange the position of these add-ons, but of course I understand the concern. Those literals should also be in all the language files (or `language.h`). For now (and likely forever) they will just be identical. If a patch comes along in the future that runs up against that I will be surprised. But perhaps Esperanto, Interlingus, and Klingon will soon be submitted....

**Comment by AnHardt** [comment]
I just can't see the why the language files have to be synchronous.

**Comment by thinkyhead** [comment]
Okay, I give, I give! This will work for now. But it would be nice for this to be a simpler maintenance issue, where the language files are _generated_ (e.g., from a database) instead of hand-edited. I would rather we look more in that direction, in the long run. Since I am building a Configurator, I may look at adding language support to it in some manner...

**Comment by tommil** [comment]
I think this makes the side by side comparison harder now that you have all these #ifndef lines in language_en.h. but I guess this works for now.

**Comment by thinkyhead** [comment]
@tommil Yes, it does! But some jokers just don't care. The trade-off is we can now be lazy and only add new language strings to the English language file. Leave it to the peasants who don't speak English to add it to their own language files, when they have time off from the milking and ploughing.

**Pull request merged**
