### PR TITLE
Move Sd library out into library

### PR DESCRIPTION
**Pull request by odewdney**
https://github.com/MarlinFirmware/Marlin/issues/1232

We will see how the CI handles the library inclusion...

### CODE REVIEW

**Comment by galexander1** [comment]
This seems to cause a variety of trouble, so I reverted it.  There wasn't any discussion, and I don't know what motivated it, or why it was merged...  So I hope I'm not stepping on any toes!

**Comment by galexander1** [comment]
In hindsight maybe it would have been best to fix the problems with this pull request instead of reverting it?  Sorry if I just made things worse..  I just would have liked to see some suggestion of what the end state was supposed to be, instead of leaving everyone second-guessing where the library was supposed to come from.

**Comment by odewdney** [comment]
The issue was discussed by others in the issue refernced above. This was really phase 1, make it a library, phase 2 would be to align the source to make switching in the current SdFat lbrary possible, and phase 3 would be actually switching. Its a pity that the Arduino GUI doesnt have a concept of project local libraries. What trouble were you having?

**Comment by bkubicek** [comment]
as much as i like libraries, this is not a good move at all. A normal user
does not know how to add an arduino library. he will assume that if he
downloads marlin and compiles it, everything will work.
The only acceptable way of having this is if there is a marlin subfolder
that is automatically included in compilation.

Bernhard

**Comment by whosawhatsis** [comment]
It seems like preprocessor code should be able to detect whether the referenced libraries are available, and throw an error that explains how to install the libraries if they are not found. There are already several libraries and hardware files that need to be installed for certain configurations. We should be consistent about installing the libraries or including them as Marlin files, and given that the list of files is already to big to see them all in the IDE, I'd lean towards libraries where it makes sense to do so. Also, the hardware files can't be included as local files, so some things do need to be installed for those boards.

**Comment by bkubicek** [comment]
no, a throwing of an error is not acceptable. It will give bad reputation
to marlin, as you need to install and fuddle around and so on. thats not an
option.

Bernhard

**Comment by bkubicek** [comment]
also, the boards where you need to fuddle around are in my world a tiny
minority.

Bernhard

**Comment by whosawhatsis** [comment]
The every board based on the the ATmega664P/1284P (Sanguinololu, Melzi, and other derivatives), AT90USB1286/7 (Teensylu, Printrboard, etc., which also require the teensy add-ons that are not included with Marlin), and RAMBO all need hardware files installed. Combined, those boards must make up around half of the market.

Marlin will already throw a compile error if libraries are not found, I'm just suggesting writing something that would give a more helpful error message, explaining the installation procedure. If that's not acceptable, then all of the other libraries included with Marlin (LiquidCrystal, SPI, and U8glib) should be moved into its own code as well.

**Comment by boelle** [comment]
make it simple... dead simple... one folder for each board with all required files and libs needed...

of course when a lib is updated our folder must be updated too... 

it makes it very simple for the user... they can just look for their board and bingo they have all the files they need in one place...

**Comment by Grogyan** [comment]
That may seem simple,  but it it will lead to more confusion.

After muddling around with SPI issues, what I can see is that the whole SD
implementation as is is really ugly. The whole thing will need to be
redone,  possibly as a separate library for the Marlin firmware project.

Even with notepad++ it is difficult to see what is going on.

**Comment by daid** [comment]
I'm with @bkubicek on this one. Compiling Marlin should be easy.

Also, I like the fact that we can do Marlin specific tweaks to the SD library. For targets with such limited space as the AVR, there usually is no "one size fits all" solution.

**Comment by odewdney** [comment]
I dont see many commits to the Sd files. Would it not be better to use an actively supported library like https://github.com/greiman/SdFat with all its fixes?

As said elsewhere, move beyond a simple compile requires other libraries already. I have updated my branch with a suitable comment like the other comments about libraries in the LCD config section....

Maybe i should be submitting patches against the Arduino GUI for better library management :)

**Comment by galexander1** [comment]
I am drawn to the argument that this is an embedded platform and we have
to give up generic coding dreams.  If we depend on an external sd library
and they decide to add a new feature because "it only takes 1kB of extra
code memory", that's eventually going to be a pain for some Marlin user.
Probably a bigger pain than what developers face with the status quo
where any desired upgrades/bug fixes have to be integrated by hand.

At any rate, if we do switch to an external library dependency, I would
personally like to see the details of that migration path worked out
before we do any merges...

**Comment by alexborro** [comment]
Upgrading and installing a new library it's easy for developers like us.

For the end user, coping some files from Marlin to arduino library folder
may be a pain in the...

Actually setting up the configuration files is already way complicated to
single users...

Let's keep it simple..

Cheers.

Alex.
Em 16/01/2015 10:53, "galexander1" notifications@github.com escreveu:

**Comment by boelle** [comment]
can agree on simple.... now we just need some coders that can fix issues... we still have to little

**Comment by thinkyhead** [comment]
It's too soon for this. For one thing, the SDFat included with Marlin is patched and customized. Also, we need to use the SDFat Beta branch because it has long filename support. I've been working on this some, and there are a lot of little details to work out.

**Comment by grob6000** [comment]
Just a thought - how are we going to create a 'stable' release if we can't guarantee the version of the external libraries? If one is updated and creates a bug in stable Marlin, we have an immediate problem. If we leave an old (but known working) version in the stable branch, if we update it as a PR in the development branch then such a bug would be much more manageable, right?

How about we include in Marlin everything that doesn't come standard with the arduino IDE for now?

I'm not comfortable with changing the design of Marlin because of a cosmetic problem with the arduino IDE. That's just not right! :)

**Comment by nophead** [comment]
There is nothing standard about what comes with the IDE. It keeps changing
in incompatible ways and breaking things.

**Comment by whosawhatsis** [comment]
First, I don't think anyone's suggesting requiring users to download a separate library. All the libraries that Marlin currently needs are included with it, and the suggestion is to turn the SD card stuff back into one of those, so an update in the original library's repo would not affect Marlin until someone copied those changes into this one, at which point they would presumably test the new version.

Also, a stable release is one that doesn't change often, not (necessarily) one that doesn't crash.

There has been a lot of push-back from collaborators on the idea of turning SD support (back) into a library. Personally, I don't really care which way it goes, but I think that the other libraries we use (u8glib, for instance) should be treated the same.

**Comment by alexborro** [comment]
I think we are running in circles here. This is a discussion with no
immediate/crucial results. There are a lot of other topics to spend some
effort that will bring good results to Marlin.

Actually I think other libraries like u8glib should be included in Marlin
(like SDFat) so user don't need to copy them to libraries folder. I mean,
the opposite way proposed here to SDFat.

Cheers.

Alex.

2015-01-21 1:26 GMT-02:00 whosawhatsis notifications@github.com:

> First, I don't think anyone's suggesting requiring users to download a
> separate library. All the libraries that Marlin currently needs are
> included with it, and the suggestion is to turn the SD card stuff back into
> one of those, so an update in the original library's repo would not affect
> Marlin until someone copied those changes into this one, at which point
> they would presumably test the new version.
> 
> Also, a stable release is one that doesn't change often, not (necessarily)
> one that doesn't crash.
> 
> There has been a lot of push-back from collaborators on the idea of
> turning SD support (back) into a library. Personally, I don't really care
> which way it goes, but I think that the other libraries we use (u8glib, for
> instance) should be treated the same.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/pull/1357#issuecomment-70778715
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by ErikZalm** [comment]
Do not move the SDfat to a library.
It is to risky and no gain.
If everything is stable again, And we have a proper testing and stable branch we can look at it again.
It is not something we should do now.

**Pull request merged**
