### PR TITLE
Fix z<= delta_clip_start_height

### PR DESCRIPTION
**Pull request by MagoKimbra**
I do not know if I made a mistake in copying it in my fw, but it seems to me that the error there is. Scott can you confirm?

### CODE REVIEW

**Comment by AnHardt** [comment]
The general concept for `do_blocking_move_to()` is:

* If target is above start - first raise then move xy.
* If target is below start - first move xy then lower.

For deltas we have more cases because there is an area at the top where the outer xy positions can't be reached because one, or more, carriages would have to be above the endstop.

* If we are in the top zone and the target is also in the top zone we can not do very much against leaving the allowed volume. But if the start and the target are in the allowed volume we can not cross the forbidden volume when we use a 'uninterpolated_move'. Due to the bowl shape of this kind of move, even when both points are right at the border the move will follow the border. A 'interpolated_move' would try to do a straight line and would collide.
* If we are in the top zone and the target is below - leave the top zone downwards - then continue as if it would be a normal printer. This ensures all xys can be reached without crossing the forbidden volume. Here we likely could do a 'uninterpolated_move' to xy at ` delta_clip_start_height`. 

A direct move from the top zone to a place near the bed is not wanted. At least the last part has to be z-only. When a endstop or probe triggers during a not z-only move the coordinate systems becomes out of sync. Using 'interpolated_moves' when probing is bad, even if downward only, because for every remaining interpolated part of the move the endstop/probe will need one step to stop the (partial) move.

So, for me, everything is as it should be.

If `do_blocking_move_to()` now works as it should, we __could__ drop the move to [0,0,delta_clip_start_height] at the end of homing. But i think it's good to remember the users to the fact, they can't go everywhere above this point.

**Comment by MagoKimbra** [comment]
Yes I agree. But if this happens DELTA_HOME_TO_SAFE_ZONE is deactivated.
Home Delta remains in the position of max.
G29
Begin to make the first probe that my case is -60 -60 therefore the command
```
do_blocking_move_to_xy (-60, -60)
```
At this point  Z = current_position [Z_AXIS].
Now let's examine the routine.
```
if (current_position [Z_AXIS]> delta_clip_start_height) = true go ahead
if (z> delta_clip_start_height) that's true, and then goes on
destination [X_AXIS] = x; // Move directly (uninterpolated)
destination [Y_AXIS] = y;
destination [Z_AXIS] = z;
prepare_uninterpolated_move_to_destination ();
```
In this way moves of X and Y in the danger zone and should not be.
In fact if I put
```
if (z <= delta_clip_start_height)
```
I get that first falls below the danger zone with
```
else {
destination [Z_AXIS] = delta_clip_start_height;
prepare_uninterpolated_move_to_destination ();
```
and then moves of X and Y.

**Comment by AnHardt** [comment]
> if (z> delta_clip_start_height) that's true, and then goes on

Sorry. I can't see that.
z is the destination. delta_clip_start_height is the height we are above (we tested that right before).
So if the destination (z) is above (>) the level go direct.
And if z is not above use the else way (go down).

Sorry, i have no delta to test with.

**Comment by MagoKimbra** [comment]
Yes, but in the delta it is home Z MAX.
So when it is in home and move only X and Y, Z is greater than delta_clip_start_height
and it moves the axes X and Y.

**Comment by thinkyhead** [comment]
I see what you mean, @MagoKimbra.

The intention of `if (z> delta_clip_start_height)` in `do_blocking_move_to` was to allow moves that will be staying in the upper area to proceed, but moves that should go lower will first move Z below.

So in fact, with a DELTA it's incorrect to use `do_blocking_move_to_xy`, especially if you really intend to move lower on the next move.

Instead the correct way to use it is to call `do_blocking_move_to(x, y, z)`, passing the Z below the upper area that you want to move to. The `do_blocking_move_to` function was actually intended only to be used by `G29`, but it's being used now anywhere that its behavior is wanted.

I see what you're pointing out — that in the first "move to probe point" the Z hasn't been moved down yet. So, we really ought to have `G29` at least move down below the safe height before starting the probe, especially as this is not guaranteed — and that includes when `DELTA_HOME_TO_SAFE_ZONE` is enabled. One could still move Z up before starting `G29`.

So I propose to add to `G29`:
```cpp
#if ENABLED(DELTA)
  if (current_position[Z_AXIS] > delta_clip_start_height)
    do_blocking_move_to_z(delta_clip_start_height);
#endif
```
just before:
```cpp
// Deploy the probe. Probe will raise if needed.
if (DEPLOY_PROBE()) return;
```

**Comment by AnHardt** [comment]
Ahh. Now i see.
```
do_blocking_move_to_xy (-60, -60)
```
does not alter z. Not a good idea to call this at [0,0,z-max].
But also not a good idea to alter this if. Else we cant move [-10, -10, delta_clip_start_height+1]-[10, 10, delta_clip_start_height+1].

Maybe we have to extend `do_blocking_move_to_xy()`  instead of changing `do_blocking_move_to()`?

Or - maybe, the assumption - there are cases where we don't want to leave the danger zone, is wrong.
If we always want to leave
```diff
@@ -1597,27 +1597,17 @@ void do_blocking_move_to(const float &x, const float &y, const float &z, const f
       if (DEBUGGING(LEVELING)) DEBUG_POS("set_destination_to_current", destination);
     #endif
 
     // when in the danger zone
     if (current_position[Z_AXIS] > delta_clip_start_height) {
-      if (z > delta_clip_start_height) {   // staying in the danger zone
-        destination[X_AXIS] = x;           // move directly (uninterpolated)
-        destination[Y_AXIS] = y;
-        destination[Z_AXIS] = z;
-        prepare_uninterpolated_move_to_destination(); // set_current_to_destination
-        #if ENABLED(DEBUG_LEVELING_FEATURE)
-          if (DEBUGGING(LEVELING)) DEBUG_POS("danger zone move", current_position);
-        #endif
-        return;
-      }
-      else {
-        destination[Z_AXIS] = delta_clip_start_height;
-        prepare_uninterpolated_move_to_destination(); // set_current_to_destination
-        #if ENABLED(DEBUG_LEVELING_FEATURE)
-          if (DEBUGGING(LEVELING)) DEBUG_POS("zone border move", current_position);
-        #endif
-      }
+      destination[X_AXIS] = x;           // move directly (uninterpolated)
+      destination[Y_AXIS] = y;
+      destination[Z_AXIS] = delta_clip_start_height;
+      prepare_uninterpolated_move_to_destination(); // set_current_to_destination
+      #if ENABLED(DEBUG_LEVELING_FEATURE)
+        if (DEBUGGING(LEVELING)) DEBUG_POS("zone border move", current_position);
+      #endif
     }
 
     if (z > current_position[Z_AXIS]) {    // raising?
       destination[Z_AXIS] = z;
       prepare_uninterpolated_move_to_destination();   // set_current_to_destination
```
should be save.

**Comment by thinkyhead** [comment]
Actually I like your idea, @AnHardt. It makes sure that moves when in the home position might still work, whereas a direct move could get out-of-sync in the towers.

**Comment by thinkyhead** [comment]
> should be safe.

~~Actually I like your idea, @AnHardt. It makes sure that moves when in the home position might still work, whereas a direct move could get out-of-sync in the towers.~~

Oops. On second thought, x=60, y=60, z=homeZ would not work in that case. (i.e., `do_blocking_move_to_xy(60, 60)` will still need to have had Z lowered before calling it.).

**Comment by thinkyhead** [comment]
The other thing is, `do_blocking_move_to_xy` was only used once at one point. So it's probably not as general-use as we would like (for delta) so we should avoid it, or keep in mind that it has this quirk of allowing a move anywhere.

**Comment by AnHardt** [comment]
>  x=60, y=60, z=homeZ

is never a legal move (at least one carriage above its endstop).

I guess we can really reduce the question to: "Are there meaningful targets, for 'automated' moves, in the top volume, other than home"

**Comment by MagoKimbra** [comment]
You are really super people!!!

**Comment by thinkyhead** [comment]
Patched the two problematic uses of XY movement with #5454.

**Pull request closed without merging**
