### PR TITLE
E3V2 DWIN Enhanced UI added caselight and led menu

### PR DESCRIPTION
**Pull request by GHGiampy**
### Description
This PR add case light and led color menu for dwin enhanced ui to Ender 3 V2

Case light:
The menu is a child of the 'Control' menu.
If the case light doesn't support brightness, only a checkbox item (on/off) is presented.
If the case light supports brightness, a submenu with a checkbox item (on/off) and brightness level (0-255) is presented.

Led color:
The menu is a child of the 'Control' menu.
A submenu with a checkbox item (on/off) and RGB components level (0-255) is presented, based on the idea of @mriscoc (thanks)
If the led isn't multicolor, only the checkbox item (on/off) is presented.

If both menu are enabled and `CASE_LIGHT_USE_NEOPIXEL` is defined, only the checkbox in the case light menu will be shown.
The menu are also available in the 'Tune' section.

### Requirements

Ender 3 V2 or DWIN UI printer

### Benefits

Add the case light menu for dwin enhanced ui
Add the led color menu for dwin enhanced ui

### Configurations

For case light menu:
Enable `CASE_LIGHT_ENABLE`
Enable `CASE_LIGHT_MENU` inside the previous define
in 'Configuration_adv.h'

For led color menu:
Enable `DWIN_CREALITY_LCD_ENHANCED`
Add a `#define LED_CONTROL_MENU` inside the block
```
#if EITHER(HAS_DISPLAY, DWIN_CREALITY_LCD_ENHANCED)
  ...
  #define LED_CONTROL_MENU
  ...
#endif
```
and define the led pin or use `CASE_LIGHT_USE_NEOPIXEL`
in 'Configuration_adv.h'

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks good! One more review in the morning and probably merge shortly after.

**Comment by GHGiampy** [comment]
Thank you!

**Comment by GHGiampy** [comment]
I confirm that with Creality environment it compiles without errors, but I also see a lot of re-defines that prevent some tests from completing. I suppose more rework is needed before it can be merged or is there something I need to do?

**Comment by thisiskeithb** [comment]
@GHGiampy: This PR causes configs that use Fysetc Mini 12864 2.1, MKS Mini 12864 V3, or BTT Mini 12864 V1 to fail since they require `NEO_GRB`, but this PR now expects `NEO_RGB` which is not a valid config option:

https://github.com/MarlinFirmware/Marlin/blob/fc50018b06285bc5c28288530df38f1d6724eaa0/Marlin/Configuration.h#L3047-L3051

What was the reason for that change?

**Comment by GHGiampy** [comment]
Looking here...
https://github.com/MarlinFirmware/Marlin/blame/fc50018b06285bc5c28288530df38f1d6724eaa0/Marlin/Configuration.h#L3047-L3051
the config.h file has never been modified, at least until 11 months ago.

Some changes were applied to `Conditionals_LCD.h` and `SanityCheck.h` and other files by @thinkyhead, here
https://github.com/MarlinFirmware/Marlin/pull/23590/files
Searching for `FYSETC_MINI_12864_2_1` I see that for the FYSETC_MINI_12864_2_1 board the `NEOPIXEL_TYPE` was forced to `NEO_RGB`...I don't know if thinkyhead did some refactor/clean up loosing some flag for these boards.

**Comment by thisiskeithb** [comment]
@thinkyhead Should these changes be reverted or should the new `NEOPIXEL_TYPE` be added to configs?

**Comment by thisiskeithb** [comment]
I put in a PR to partially revert the `NEO_GRB` -> `NEO_RGB` changes: https://github.com/MarlinFirmware/Marlin/pull/24011

**Pull request merged**
