### PR TITLE
Parity with MarlinDev/master PRs

### PR DESCRIPTION
**Pull request by thinkyhead**
Here's a compendium of commits —suitable for cherry-picking for RC— which will bring near-parity with the latest PRs for `MarlinDev/master`. Bug fixes, formatting, and code-tweaks are included.

If reviewers don't mind cherry-picking (in case one or more of these looks wonky), I find it preferable to do a single PR rather than 12 for RC, since we want pretty frequent patches for RC to keep the interest going, and because it takes so much #%&$\* time to make PRs. :smiling_imp: I think these are all pretty solid and self-evident fixes. They should be easy to do in order. If the "N" patch, #2315 patch, and `gcode_M221` patch pass testing on dev they should be good-to-go here as well.

HTH!

### CODE REVIEW

**Comment by Roxy-3D** [comment]
@ThinkyHead   Are you suggesting we update the current Release Candidate to one with these applied to it?     I'm currently trying to bring up my new printer with the current Release Candidate.  I haven't printed anything yet, but so far everything looks 'reasonable'  but I did find an inconsistent behavior.  code_has_value() currently requires the value to have no space between it and the GCode.   I added 2 lines of code to make it behave better.   This might be added to your set of changes:

```
bool code_has_value() {
  int i = 1;
  char c = seen_pointer[i];

  while (c == ' ')      // skip past any white space between GCode and number
     c = seen_pointer[++i];
```

**Comment by AnHardt** [comment]
Travis finds this

```
Marlin_main.cpp.o: In function `setup':
Marlin_main.cpp:682: undefined reference to `watchdog_init()'
collect2: error: ld returned 1 exit status
Error compiling.
```

https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Marlin_main.cpp#L684
A possible fix looks like 

```
#if ENABLED(USE_WATCHDOG)
  watchdog_init();
#endif
```

When that is cleaned out compilation fails when a display (REPRAP_DISCOUNT_SMART_CONTROLLER) is defined.
See: https://github.com/MarlinFirmware/MarlinDev/pull/241#issuecomment-148234975

**Comment by thinkyhead** [comment]
This should be all patched up and passing now. The companion patch for #2315 has also been fixed over at MarlinFirmware/MarlinDev#241. (Doing every patch twice is a good way to get to know Git!)

@Roxy-3DPrintBoard I hope you will merge all these patches if they prove stable. I'm trying to ensure that any bugs found by users in the RC tagged releases are also getting patched in the Dev branch, and that any bugs found in the dev branch during this period are also patched in the RCBugFix branch for RC3, RC4, etc., so that the final 1.1.0 release will have as few existing issues as possible.

In this PR the commits f54b66d, fd30a7b, b1e8b00, 594fb5f are bug-fixes. The others are general code styling and cleanup.

I wasn't aware that it was legal G-Code to include spaces between a code and its value. Marlin up to now has not made any allowance for them. Mulling it over, I think your suggested change is probably fine, since codes are only allowed to have numerical values or no values. It will allow us to type more sloppy commands into the console, e.g., `M104 S 180`…

**Comment by Roxy-3D** [comment]
> In this PR the commits f54b66d, fd30a7b, b1e8b00, 594fb5f are bug-fixes. The others are general code styling and cleanup.

I have a quick question:  Do we want to merge these commits to RC-2 ?   Shouldn't RC-2 stay frozen as what ever it is?   Perhaps this is handled by just keeping the RC-2 Tag pointing at the same place and when we get enough bug fixes merged into RC-2 we create an RC-3 Tag pointing to that?

Update:   I know the answer!  These need to be applied against RCBugFix!

**Comment by AnHardt** [comment]
@Roxy-3DPrintBoard 
For me it would make most sense to merge some fixes to the `RCBugFix` branch to make them better testable for a larger audience then in the separate branches of the users. After collecting some commits we should merge them to the `RC` branch and make a new label there.

**Comment by Roxy-3D** [comment]
Agreed!   I didn't realize there was an RCBugFix branch already present.

**Comment by Roxy-3D** [comment]
@Thinkyhead  Hey Scott! I'm certainly not ignoring you...   I just can't
get to your stuff!  GitHub is causing problems and I'm tied up trying to
get my new printer going.

**Pull request merged**
