### PR TITLE
4.3" Screen (480x272) support for Color UI

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Make color ui support 480x272 screen resolution, for 4.3" screens.

### Benefits

More users will be able to use color ui. 
Sapphire Plus use this screen.

### CODE REVIEW

**Comment by ils15** [comment]
*BlueR Plus

**Comment by thinkyhead** [comment]
It all seems sensible. What else remains to be done?

**Comment by rhapsodyv** [comment]
> It all seems sensible. What else remains to be done?

MKS is testing it for us. But we didn't finished the tests yet. Just it. This night (morning for MKS), we may finish it.  ( I don't have this screen...)

**Comment by sjasonsmith** [comment]
Any update on this? Have they tested enough to pull this in?

**Comment by rhapsodyv** [comment]
The screen is 100%. Just the touch isn't working yet. But they couldn't test it again. I will ask for more tests this week.

**Comment by jayden-jw** [comment]
Any update on this?

**Comment by rhapsodyv** [comment]
> Any update on this?

Yes, I need someone to test it for me. I don't have this screen.

**Comment by jayden-jw** [comment]
Tested, 
after the touch calibration done, the screen won't reponse to any touch.

**Comment by rhapsodyv** [comment]
> after the touch calibration done, the screen won't reponse to any touch.

Can you do the touch calibration again, but now keep the serial connected and send me the values that marlin will print after the calibration happen?
Which board are you using? nano v2? Nano v1.2?

You said something about rotation. The screen is rotated 180?

**Comment by jayden-jw** [comment]
Running on nano v1. 2 and screen rotated 180

Here is the m995 output
Touch_calibration_x -2745958
Touch_calibration_y 27656192
Touch_offset_x 11425
Touch_offset_y -12233
Touch_orientation touch_potrait

Everytime I run m995 the output values are very different can be from negetive to positive... Orientation is always portrait.

**Comment by rhapsodyv** [comment]
Can you open `Marlin/src/pins/stm32f1/pins_MKS_ROBIN_NANO.h` and comment that 2 lines:
```
  #define TOUCH_BUTTONS_HW_SPI
  #define TOUCH_BUTTONS_HW_SPI_DEVICE          2
```
Line 199 and 200. Comment it and try again, if you can.
Commented lines:
```
//  #define TOUCH_BUTTONS_HW_SPI
//  #define TOUCH_BUTTONS_HW_SPI_DEVICE          2
```

**Comment by rhapsodyv** [comment]
We can chat on discord too.

**Comment by jayden-jw** [comment]
Commented that 2 lines but still doesn't work.
Can I have your discord name?

**Comment by rhapsodyv** [comment]
Same nick. `rhapsodyv#9981`

**Comment by rhapsodyv** [comment]
I found and fixed the touch issue! 🥳

**Comment by thisiskeithb** [comment]
Per our discussion on Discord, I've tested the new `TOUCH_SCREEN_CALIBRATION` code from this PR on an Anet ET5X and it now works!

So these lines can be removed from the ET4 pins file:

https://github.com/MarlinFirmware/Marlin/blob/e2480d40d138aa822f59ac1b317d539238b77a3e/Marlin/src/pins/stm32f4/pins_ANET_ET4.h#L158-L161

**Comment by jayden-jw** [comment]
With the new fixes, I have tested it with tft43 and confirmed it's working correctly, thanks.

**Comment by rhapsodyv** [comment]
With this done, someone could add a Bluer Plus Configuration example. Anyone??

**Comment by jayden-jw** [comment]
> With this done, someone could add a Bluer Plus Configuration example. Anyone??

I will make 1 later

**Comment by Snapperjagger** [comment]
@rhapsodyv still need a configuration for Bluer Plus?

**Comment by dufduf-one** [comment]
hello world!

I have tested on BLUER PLUS and have changed the touch `calibration_points` value on BUTTON from Y -31 to Y -71

in `SanityCheck.h`…
```cpp
#if HAS_TFT_LVGL_UI && NONE(TFT_RES_480x320, TFT_RES_480x272)
  #error "(FMSC|SPI)TFT_LVGL_UI requires TFT_RES_480x320 or TFT_RES_480x272 ."
#endif
```

in draw_ui.h
```
 the TFT_HEIGHT        272 // ,   all "" PARA_UI_POS_Y "oldvalue" / 320 x 272 
```

and finally I changed the `calibration_points` value to -31.

**Comment by ils15** [comment]
> hello world !
> i have teste on BLUER PLUS and i have change the touchs calibration_points value on BOTTON like y -31 to Y -71
> on SanityCheck.h
> #if HAS_TFT_LVGL_UI && NONE(TFT_RES_480x320, TFT_RES_480x272)
> #error "(FMSC|SPI)TFT_LVGL_UI requires TFT_RES_480x320 or TFT_RES_480x272 ."
> #endif
> on draw_ui.h
> the TFT_HEIGHT 272 , all "" PARA_UI_POS_Y "oldvalue" / 320 x 272
> 
> and finally i have resrite the calibration_points value to -31

Please see this

https://github.com/MarlinFirmware/Configurations/pull/391

**Comment by dufduf-one** [comment]
> S’il vous plaît voir cela
> 
> [MarlinFirmware/Configurations#391](https://github.com/MarlinFirmware/Configurations/pull/391)

hello, 
with TFT_COLOR_UI all is good, but with TFT_LVGL_UI , i have not solved

image

TOUCH_SCREEN_CALIBRATION, works great on boot


image

and in final the is what i have

image



image

the chassie opening to the BLEUR PLUS are small for the full size TFT43, i have change the offset screem

**Comment by Lester3DGadgets** [comment]
looks like the touch is rotated and flipped on MKS_UI

**Comment by rhapsodyv** [comment]
> looks like the touch is rotated and flipped on MKS_UI

We didn't add support for lvgl ui yet. But you can just run the touch calibration using M995.

**Comment by jayden-jw** [comment]
I have test on MKS_UI too, the M995 will start the calibration, but after the calibration finished the touch wont register on the right spot, it seems mirrored just like previously on Color UI before the merge.

**Comment by dufduf-one** [comment]
https://github.com/MarlinFirmware/Marlin/pull/20334#issuecomment-768062207

yes  i have the same thinking and i have teste the bought orientation of thouch ""portrait "and "landscape"".

maybe it is the first label make mistake ?

image

**Pull request merged**
