### PR TITLE
Changed type to HAL_TIMER_TYPE for platforms with 16bit timers.

### PR DESCRIPTION
**Pull request by victorpv**
Needed for STM32F1

### CODE REVIEW

**Comment by tcm0116** [comment]
You should go ahead and update `adv_rate` in stepper.cpp:

```
  FORCE_INLINE HAL_TIMER_TYPE adv_rate(const int steps, const HAL_TIMER_TYPE timer, const uint8_t loops) {
    if (steps) {
      const HAL_TIMER_TYPE rate = (timer * loops) / abs(steps);
      //return constrain(rate, 1, ADV_NEVER - 1)
      return rate ? rate : 1;
    }
    return ADV_NEVER;
  }
```

Additionally, `Stepper::acceleration_time` and `Stepper::deceleration_time` should also be defined as `HAL_TIMER_TYPE`.

**Comment by Roxy-3D** [comment]
Should we also modify timer's type:  https://github.com/MarlinFirmware/Marlin/issues/7076#issuecomment-332659282
```cpp
 -  FORCE_INLINE uint16_t adv_rate(const int steps, const uint16_t timer, const uint8_t loops) {
 +  FORCE_INLINE HAL_TIMER_TYPE adv_rate(const int steps, const uint16_t timer, const uint8_t loops) {
      if (steps) {
 -      const uint16_t rate = (timer * loops) / abs(steps);
 +      const HAL_TIMER_TYPE rate = (timer * loops) / abs(steps);
        //return constrain(rate, 1, ADV_NEVER - 1)
        return rate ? rate : 1;
      }
```

**Comment by victorpv** [comment]
Didn't have time today to test more, but as soon as I can test those changes too I will add them to this PR.
Let's keep the PR unmerged until then.

**Comment by simon-jouet** [comment]
We should also change the pulse_start and the typecast when delaying between pulses

```diff
diff --git a/Marlin/src/module/stepper.cpp b/Marlin/src/module/stepper.cpp
index 1419b9610..66dd966f8 100644
--- a/Marlin/src/module/stepper.cpp
+++ b/Marlin/src/module/stepper.cpp
@@ -574,7 +574,7 @@ void Stepper::isr() {
      * 10µs = 160 or 200 cycles.
      */
     #if EXTRA_CYCLES_XYZE > 20
-      uint32_t pulse_start = HAL_timer_get_current_count(STEP_TIMER_NUM);
+      HAL_TIMER_TYPE pulse_start = HAL_timer_get_current_count(STEP_TIMER_NUM);
     #endif

     #if HAS_X_STEP
@@ -606,7 +606,7 @@ void Stepper::isr() {

     // For minimum pulse time wait before stopping pulses
     #if EXTRA_CYCLES_XYZE > 20
-      while (EXTRA_CYCLES_XYZE > (uint32_t)(HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start) * (STEPPER_TIMER_PRESCALE)) { /* nada */ }
+      while (EXTRA_CYCLES_XYZE > (HAL_TIMER_TYPE)(HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start) * (STEPPER_TIMER_PRESCALE)) { /* nada */ }
       pulse_start = HAL_timer_get_current_count(STEP_TIMER_NUM);
     #elif EXTRA_CYCLES_XYZE > 0
       DELAY_NOPS(EXTRA_CYCLES_XYZE);
```

**Comment by victorpv** [comment]
Agreed, I have done most of those changes and tested with the F1 HAL while checking stepper pulses with a digital analyzer.
I'll try to review and submit all my changes. The way I did, values that have to do with rates are uint32_t, and the values that either read or written to the timer counter are HAL_TIMER_TYPE.

I'll try to review and update later today.

**Comment by thinkyhead** [comment]
Currently this PR doesn't make any changes. When it's ready, let us know!

**Comment by victorpv** [comment]
I have added several more type changes as tested by me with the F1 HAL. I haven't yet tested the changes from @simon-jouet together with mine,  but I agreed with those and will test them as soon as possible.
I'm adding those 2 changes to this PR, if someone else has some time to test in other platforms it would be great so we finish with this issue.

EDIT:
Actually thinking about it, I'm not sure about the second change. Since we are multiplying the timer count by the prescale value, that would result in a large number, and I don't see a reason to restrict that to the HAL_TIMER_TYPE since it is not used to read or load a value to/from the timer count register.
```
     // For minimum pulse time wait before stopping pulses
     #if EXTRA_CYCLES_XYZE > 20
-      while (EXTRA_CYCLES_XYZE > (uint32_t)(HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start) * (STEPPER_TIMER_PRESCALE)) { /* nada */ }
+      while (EXTRA_CYCLES_XYZE > (HAL_TIMER_TYPE)(HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start) * (STEPPER_TIMER_PRESCALE)) { /* nada */ }
       pulse_start = HAL_timer_get_current_count(STEP_TIMER_NUM);
     #elif EXTRA_CYCLES_XYZE > 0
       DELAY_NOPS(EXTRA_CYCLES_XYZE);
```

Opinions on that one?

**Comment by simon-jouet** [comment]
The changes I suggested are based on the requirements for the ESP32, the value of HAL_TIMER_TYPE for me is 64 bits so it ends up being bigger, but yes in cases where HAL_TIMER_TYPE is a 16 bit value then this might cause problems ...

**Comment by victorpv** [comment]
Hmmm, in the ESP32 at what frequency is the timer counting?
Most platforms are using prescalers, in the STM32 I am bringing the timer frequency to 2Mhz, although have experimented with 1 to 8Mhz.
I wonder how long takes that 64 timer to overflow...
But yeah with a 64bit timer a uin32_t may not be enough.
One other thing I do in the STM32 is reset the count each time the compare triggers an interrupt. I do that because the Compare will trigger if the compare value is smaller or equal to the Timer count, so if I add to the Compare value to the point it would overflow, then the ISR could trigger right away without waiting for the count to roll up and match. Resetting the count I never have to worry whether the compare will be larger or smaller than the current count, will always be larger.

What can we do to avoid problems on all platforms with that one then?
We may need to read more thru the code, but I perhaps EXTRA_CYCLES_XYZE  never takes large values.

**Comment by p3p** [comment]
@victorpv LPC1768 doesn't use a prescaler either, timers run at 25MHz, about 3 mins between steps to overflow uint32_t, a high frequency stepper timer improves the resolution and velocity accuracy, also the reason we don't reset the count in other platforms when match is set is the time already taken in the ISR needs to be taken into account, the only time count should be reset is on stepper ISR trigger otherwise it itroduces error into the stepper pulse train.

I was actually just looking at what type that cast should be because of a bug if MINIMUM_STEPPER_PULSE is set, it opens up a few code paths that still use TCNT0 directly. In theory of course because we are multiplying a value of HAL_TIMER_TYPE we should promote the type for the result ..

edit
> also the reason we don't reset the count in other platforms when match is set is the time already taken in the ISR needs to be taken into account

Ignore that part, think I misunderstood you

**Comment by victorpv** [comment]
If we use uint64_t in all platforms it may cause a small penalty in performance, but I would think all 32bit platforms can live with it, it's just a single multiplication, and that would solve the problem with both larger and smaller timer types.
We can set a type for 32bits, and another for AVR to not penalize the AVR.

But does anyone know in practice what are valid values of EXTRA_CYCLES_XYZE ?
If the range of values is very small, then perhaps we can find a different solution.

**Comment by bobc** [comment]
I'm surprised if we really need a 64 bit here. How did we ever manage with 16 bits?

Again it seems we are proposing to accommodate a particular feature of one faster platform by penalising slower platforms. That is the wrong compromise. The ESP32 has a 240MHz CPU, at least twice as fast as all the other 32 bit platforms. If anything should be taking a performance hit, it should be the ESP32 platform.

**Comment by p3p** [comment]
@victorpv EXTRA_CYCLES_xxx are just timer deltas to adjust the length of a pulses, they should never be large values 

@bobc the cast to uint32_t is because of the multiply(?),  in theory we should promote on 32 bit platforms to uint64_t (and if the timer is 64 bit well you get the idea), although I never did understand why STEPPER_TIMER_PRESCALE was a double..

This is all pointless though you are never going to overflow a uint32_t with a timer delta .. 20 seconds at 250Mhz, that's a long stepper pulse.

**Comment by victorpv** [comment]
Let's see if someone can confirm this. 
First, this line defines EXTRA_CYCLES_XYZE :
`#define EXTRA_CYCLES_XYZE (STEP_PULSE_CYCLES - (CYCLES_EATEN_XYZE))`
That can vary from 0 to any number of (uS * pulses_per_microsecond).
Default is 0, but let's say there is a stepper that needs a minimum pulse or N uS, then that would be set accordingly.
So it's not going to take large values, few uS at max, and with a timer at 240Mhz, a uint16 could count up to 136uS, that's a long pulse.

Second, we have several math operations, and the type is only applied to the last one:
`while (EXTRA_CYCLES_XYZE > (uint32_t)(HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start) * (STEPPER_TIMER_PRESCALE)) { /* nada */ }`

First this one, it's to calculate how many timer tics between now and when the ISR was initally called:
`HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start`
The ISR is meant to run fast, so that shouldn't hold a large value. If it does, then we have larger problems than the final type cast.
In my SMT32 at 72Mhz it completes in 8uS or less. 
8uS at 240 pulses per uS is 1290, so that fits just fine in uint16_t. So if the ISR in the ESP32 took the same 8uS, that number would be 1290, but I can only imagine the ISR should take even less at 240Mhz.


Then the result of that, is multiplied by STEPPER_TIMER_PRESCALE. If the timer was runing with no prescaler, that should be 1, so 1290*1.
If I was running with a prescaler (I do in the STM), then the STEPPER_TIMER_PRESCALE would be larger than 1, but the timer in return would be running slower, so this: (HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start) would be smaller proportionally.

So at the end of the day, the faster the timer, the larger the number, and the slower the MCU, the larger the number, but since normally a faster timer will be used in a faster MCU, they cancel, and the number should never end up being too large unless your ISR takes forever to complete.

If I use my STM32F1 as example, and run the timer at 2Mhz (36 prescaler)
`HAL_timer_get_current_count(STEP_TIMER_NUM) - pulse_start`
This would be 8uS of timer count at 2Mhz, thats 16.
16 * STEPPER_TIMER_PRESCALE = 16 * 36 = 576.

If I run with no prescaler in the timer (STEPPER_TIMER_PRESCALE = 1):
8uS at 72Mhz  = 576
576 * STEPPER_TIMER_PRESCALE = 576 * 1 = 576

The ISR will take longer depending what's doing, but still as Bobc pointed out, we should get away with a much smaller type.

So then what, set is a fixed type to uint32 or uint16, or set it to HAL_TIMER_TYPE?
Both should work from what I can see.

If anyone thinks my thought process had any flaw, let me know.

EDIT: To clarify, in the HAL branch it's currently uint32_t and Simon suggested using HAL_TIMER_TYPE.
In the main branch, for the AVR, it's a uint32_t:
https://github.com/MarlinFirmware/Marlin/blob/f6f881f5ed954bc2f44ca64895b6af99e74265a2/Marlin/stepper.cpp#L610

**Comment by p3p** [comment]
@victorpv That's what I said, well.. without the explanation, HAL_TIMER_TYPE should always be more than enough (as should leaving it as uint32_t).

**Comment by AnHardt** [comment]
For fast enough prozessors the concept of busy waiting is crap anyway.
Call the stepper-ISR twice as often, for the double amount of half-steps, In the even ones set the step-pin and in the od once reset the step-pin. this will result in much better pulses, even when time is recalculated for every half-step, cloth to a 50/50 duty cycle.
ADVANCE and Babystepping will make things much more complicated; But maybe someone has an idea.

**Comment by p3p** [comment]
@AnHardt As Marlin 2 matures the aim is to introduce more optimisations using features available with the more advanced processors, but the initial step is feature parity using as much shared code as possible. We do know that a lot can be done more efficiently if we rewrite parts specifically.

**Comment by victorpv** [comment]
So is everyone happy to merge these changes?

**Comment by thinkyhead** [comment]
For purposes of conflict resolution, I have a question:
Is `timer_t` being replaced by `uint32_t` intentionally as part of this PR, or should it be left as `timer_t` (which comes from a recent change)?

**Comment by victorpv** [comment]
@thinkyhead ~~the aim of this PR was to use timer_t for variables that hold a value read from or to be written to the timer, while using uint32_t for other variables like speeds or rates
Where you referering to all the changes in general in this PR, or just a particular line?~~
Ok I see what you meant. This PR was sent weeks ago, when timer_t was not used yet. Keep this PR open but not merged and I will go thru the current code and see if the current version has all the changes needed already. 
I just merged the current changes in stepper.cpp, there are only 3 instances where HAL_TIMER_TYPE was not used in the current stepper.cpp but should be since they hold timer counter values.
I will retest later when at home.
If everyone else can review and give their opinions in the changes left would be appreciated.

**Comment by thinkyhead** [comment]
Using Merge on existing PRs is contraindicated. Instead, `git rebase` is more appropriate. Unfortunately the Github Desktop software doesn't provide this capability. It must be done from the command-line.

**Comment by thinkyhead** [comment]
Whenever this is ready I'll be most gratified to merge it into the codebase.

**Comment by victorpv** [comment]
Would it be easier if we send this as a new PR from the current stepper code? I'm not so experienced with Github and probably would be able to rebase it right.

**Comment by thinkyhead** [comment]
I think this is obviated by other PRs that applied a `typedef` of `timer_t` to more items, and then a second PR that renames that to `hal_timer_t` to prevent PlatformIO name collision. Take a look at the 2.0.x code in an hour or so and it should have all updates applied.

**Pull request closed without merging**
