### PR TITLE
Input shaping for Z axis

### LINKED ISSUE #26474: [FR] Support for Z-Axis Input Shaping
### Is your feature request related to a problem? Please describe.

Currently Marlin does not offer accelerometer support in regards to Input Shaping. As described here https://3dprinting.stackexchange.com/questions/21660/how-to-physically-wire-a-adxl345-accelerometer-for-input-shaping-resonance-co and here https://3dprinting.stackexchange.com/questions/21662/does-marlin-input-shaping-compensate-vibration-on-all-x-y-and-z-axes and on many other sites.

However, I think that the KUSBA (https://github.com/xbst/KUSBA) USB accelerometer (or similar USB device) **connected to the printer host** is the most accessible (plug-and-play) way to bring Input Shaping to most Marlin printer users. This is why I created an issue in the repo of OctoPrint (a host) and not the Marlin repo here: https://github.com/OctoPrint/OctoPrint/issues/4912.

However, Marlin needs to support it and as far as I know it only supports Input Shaping for the X and Y axes (https://marlinfw.org/docs/gcode/M593.html).

Ideally, I would like to hook up two KUSBA devices to my Raspberry Pi, in combination with Ender 3 V2, one on the extruder (for Z and Y axes) and one under the bed (for Y axis). However, even if OctoPrint implements support, Marlin does not support Z-axis Input Shaping.

The concept is also shown here: https://youtu.be/aHQju3e2guE?si=5G1lpCHiF9wL1aOF&t=1402.

### Are you looking for hardware support?

_No response_

### Describe the feature you want

Support for Z-Axis Input Shaping in the M593 G-code.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JonBr306**
### Description

Extended ZV input shaping so it can be done in the Z axis enabling certain types of kinematics (Delta, CoreXZ and CoreYZ) to use ZV input shaping now. Some cartesian machines may also benefit from this.

### Requirements

Input shaping enabled.

### Benefits

Z Axis can now be input shaped.

### Configurations

Enable `INPUT_SHAPING_Z`

### Related Issues

- #26474

### CODE REVIEW

**Review by tombrazier — APPROVED** [review]
I am happy with these changes. @JonBr306 collaborated with me and I have reviewed everything and done some testing. More testing would be desirable from those with printers that will most benefit like deltas and core*z.

**Comment by thinkyhead** [comment]
This is great work and perfectly maintains the quirky Marlin style for the added macros. Merging shortly!

**Comment by dbuezas** [comment]
A bit late to the party but I started tuning it and got some results.

Here's my procedure on a modernised Ultimaker 2.

## 1. Rough frequency tuning

* Set zjerk and acceleration fairly high
* Setting **zhop:normal** to `0.2mm` in Orca Slicer
* Print some parallel lines 
* Measure the spacing of the bumps
* `frequency = first_layer_speed / bump_distance`. In my case I got 22Hz

## 2. Rough damping factor tuning

* Configure **zhop:normal** and then **print sequence: by object** in orca slicer
* In **printing by object G-Code***: `M593 D{current_object_idx/49.0} F22 Z` 
* Printed this pattern: 
image
* Found the one that looked best. It was D0.05

## 3. Final frequency tuning
* Same as damping but now with `M593 D0.05 F{20+current_object_idx/49.0*4} Z`
* The 18th from the bottom looked best (almost perfect!). 
image
* Found the one that looked best. It was 21Hz

## Final Damping tuning.

* Repeated the process with `M593 D{current_object_idx/100.0} F21 Z`
* Found the best. It was D0.03


## Before and after

image

The bottom half with Z input shaping disabled, top half with it enabled and fine tuned. I'm very impressed!
This is a single layer, if this was a wall, the bouncing would have compounded. FANTASTIC WORK!

**Comment by dbuezas** [comment]
By the way, this effect was made obvious by having high zjerk, zaccel and zhop, which I can now keep as defaults. I believe this explains the elusive and sporadic holes in some places I had given up on fixing.
Also I always printed stuff as close as possible to the back of the machine to avoid bouncing. I think it will be less of an issue now.

**Comment by tombrazier** [comment]
Fantastic results.

**Comment by dbuezas** [comment]
I just realised This has improved my z-seams too!

**Comment by tombrazier** [comment]
> I just realised This has improved my z-seams too!

That sounds interesting but I don't know what you mean by z-seams. Could you elaborate?

**Comment by dbuezas** [comment]
Given that your contributions include input shaping and lots of LA improvements, I bet you have optimised quality so much that you forgot what they were :) 

I mean these: (not my image)
image

I assume the bouncing was making the beginning of extrusions (e.g on layer changes) uglier.

**Comment by tombrazier** [comment]
Oh, I wondered if that was what you meant but couldn't think why Z input shaping would help. But it's pretty obvious from that picture that the bounce is causing the narrow then wide print path. What a great additional benefit.

**Comment by dbuezas** [comment]
Exactly. The image is not mine, I should make a print myself with and without IS z enabled. It wasn't consistently terrible because I had my z accel and jerk so low, to reduce the bouncing.

**Comment by ant0nyk1ng** [comment]
@dbuezas is it possible to get your config files. I have a new large Delta build and I would like to try this out.

**Comment by thisiskeithb** [comment]
> is it possible to get your config files. I have a new large Delta build and I would like to try this out.

@ant0nyk1ng: An Ultimaker 2 will have very different values than a delta. Values will also vary from identical machine to identical machine.

Since this PR is merged, grab the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) and enable `INPUT_SHAPING_X`, `INPUT_SHAPING_Y`, & `INPUT_SHAPING_Z` (all three are required for deltas) and then tune to your machine.

Hop on our [Discord server](https://discord.gg/n5NJ59y) if you need further help.

**Comment by ant0nyk1ng** [comment]
> > is it possible to get your config files. I have a new large Delta build and I would like to try this out.
> 
> @ant0nyk1ng: An Ultimaker 2 will have very different values than a delta. Values will also vary from identical machine to identical machine.
> 
> Since this PR is merged, grab the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) and enable `INPUT_SHAPING_X`, `INPUT_SHAPING_Y`, & `INPUT_SHAPING_Z` (all three are required for deltas) and then tune to your machine.
> 
> Hop on our [Discord server](https://discord.gg/n5NJ59y) if you need further help.

Ok cool I will... I was interested to see his "high jerk" values and you just answered the other "all three are required for deltas" but yeah I totally missed the fact he was using a Ultimaker.

**Comment by JayceeB1** [comment]
@dbuezas Fanstastic! Please can you share your pattern or explain how you made it? just a simple rectangle sized using line width? Or just simple plain gcode for the lines?

I'd like to test that on my corexy :)

**Comment by dbuezas** [comment]
@JayceeB1 I thought I had uploaded the pattern. It is just horizontal lines, 0.4mm width and separated by 0.4mm. then I enabled z hop and increased z accel and jerk to force it to bounce. If I recall correctly, I just updated input shaping parameters while the machine ran

**Pull request merged**
