### PR TITLE
Auto M851: Set Z-Probe Offset (quick nozzle swap)

### PR DESCRIPTION
**Pull request by engmaster**
Hi everyone,
First of all, I'd like to say big thanks to authors for this wonderful firmware.

I have one ideia to improve the nozzle swap. In the future, this idea will help identify the position of tools on CNC machines using this firmware.

This implementation will require 2 sensors (endstops) for positioning the nozzle and leveling sensor.
See the image:
automatic z-offset height

### CODE REVIEW

**Comment by thinkyhead** [comment]
Indeed, this sort of thing can work. However, the trend is moving away from these kinds of solutions and towards more accurate probes, which continue to drop in price. Unless the probe is being altered a lot, setting the Z offset should be an infrequent or even one-time procedure, and it's pretty easy to do manually. We also now include an option to set the probe Z offset during babystepping, so fine adjustments are easier to make and save.

**Comment by engmaster** [comment]
I've been changing the nozzle diameter about 5~8 times a week, every week. So I've been thinking of a way to automate configuration at every nozzle change, maybe this could help us never set this distance again. The firmware will check every time requested.. including the first time configuration.

**Comment by engmaster** [comment]
If many people use frequent nozzle swap like me, maybe this idea can be valid. But it would also be good to think of people who do not change the nozzle diameter because of the work of reconfiguring.
With larger nozzle diameters, we have a more faster prints in large parts.. and i love it when the layer height if not a priority.

**Comment by pyr0ball** [comment]
An interesting possible option might be to use a conductive circuit. A positive lead would be attached to the hotend, and the negative lead connected to the off-bed pad, allowing you to get an exact measure of when the nozzle actually touches the surface. Only issue I can see here is a gunked up nozzle getting insulated by extra filament stuck to it over time, but as long as the nozzle is kept relatively clean, this might be a good option

**Comment by engmaster** [comment]
I see as a good solution, we do not yet have sensors dedicated to this procedure .. but with the start of development and support in firmware, anything is possible.
It could be added to the experimental procedures.

**Comment by studiodyne** [comment]
The better solution is mine , and it need just a paper

- Go to control menu , and set a big offset  value like 5 mm ' to go down as you want '
- G28 z
- and go to lcd zmove , go down ... when the paper is locked under the nozzle, you have the value on the lcd 
- Return to control menu and set the value and it's perfect , no code , no mechanical , and 'human verified'

👍 
But this swap , automatised , i love the idea , because in reality , i make the test two times and , circulate between menus is not a good game

**Comment by fiveangle** [comment]
Lulzbot uses such a method, but they also have a thoroughly tested hardware for their heating/wiping mechanism and custom trigger pads on each corner outside the bed (similar to allen key, but in reverse where the nozzle tip triggers the pad).  All the logic is already there in Marlin for using such a probe mechanism as well as wiper: you just need to build all that stuff and tweak all the parameters to make it work for your custom HW.

**Comment by fiveangle** [comment]
It looks like this doesn't get implemented for native USB MCUs (like AT90USB) but wouldn't this be an improvement for large transfers like SD, even for those MCUs since the alternative is ping-pong ?

**Comment by thinkyhead** [comment]
Sorry, this PR got trounced (not actually merged) by the most recent 1.1.x branch update. Maybe this PR was targeting the 1.1.x branch, and that's why it got "merged". However, the changes in this PR are not in fact merged, so you'll need to create a new PR based on the current `bugfix-1.1.x` branch to proceed.

**Pull request merged**
