### PR TITLE
Add active extruder indicator for DOGM UI LCD 

### PR DESCRIPTION
**Pull request by ansonl**
### Description

Adds an arrow on the LCD indicating the firmware active extruder on DOGM LCD UI, improving accessibility and safety on multi extruder printers. 

image

### Requirements

DOGM LCD

### Benefits

This provided visual feedback to the user on the active extruder on the info screen. This will assist the user in determining faults and whether the printer's physical active extruder matches the firmware active extruder. 

### Configurations

Needs multi extruder printer with 2+ hotends

### Related Issues

This is related to but not dependent on #26151 which returns the firmware active extruder over Serial for the `T` command.

### CODE REVIEW

**Comment by DerAndere1** [comment]
does this work for 5+ hotends? For those cases, it might be reasonable to just display one hotend icon with the tool index (hotend index) of the active hotend.

**Comment by ansonl** [comment]
@DerAndere1 Yes it will display the arrow to the left of the active extruder icon only when `STATUS_COMBINE_HEATERS` is disabled and `HAS_MULTI_EXTRUDER` is true.

**Comment by ansonl** [comment]
@thinkyhead Can we merge this UI improvement before 2.1.3? I assume you're busy with ERRF coming up, so I can follow up on this PR later, too.

**Comment by ansonl** [comment]
@thinkyhead Do you suggest any changes for this feature? It is ready to merge.

**Comment by radek8** [comment]
I have a printer with 2 extruders.
I can't compile the new FW after merging your edit.
I am getting the following error :

image

image

**Comment by thisiskeithb** [comment]
This does not work when `STATUS_HOTEND_NUMBERLESS` is enabled.

**Pull request merged**
