### PR TITLE
Fix for setting offset from tune menu (ender 3 v2)

### PR DESCRIPTION
**Pull request by cosmoderp**
### Description

When `#if HAS_BED_PROBE` it would skip setting babysteps due to `#elif` instead of rather having a nested if. 

### Benefits

This lets users set the Z offset while printing.

### Configurations

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5215071/Marlin.zip)

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/18787

### CODE REVIEW

**Comment by cosmoderp** [comment]
The latest commits reverted this back but people want this fix.  They have been asking me all the time about it.  The only issue you might have is that it might need an extra else to account for people that define `BABYSTEP_ZPROBE_OFFSET`

**Comment by thinkyhead** [comment]
Your patch is incorrect. Wait until this has been fixed up a bit and then give it another test.

**Comment by thinkyhead** [comment]
Ok, at this point it seems like all the pieces are in their proper place, and I've added live Z adjustment, so that should be interesting. Please confirm that it works according to the settings, whether there is a probe enabled or not. I can test the configuration with no probe on this V2 and see whether `BABYSTEPPING` is behaving the way it should, but I don't yet have a probe installed for testing the probe offset behavior. Be sure to enable `BABYSTEP_ALWAYS_AVAILABLE` if you want to be able to do babystepping before printing.

**Comment by cosmoderp** [comment]
Well I can already tell something is wrong with this part in the code:
```
#define TUNE_CASE_SPEED 1
#define TUNE_CASE_TEMP (TUNE_CASE_SPEED + ENABLED(HAS_HOTEND))
#define TUNE_CASE_BED  (TUNE_CASE_TEMP + ENABLED(HAS_HEATED_BED))
#define TUNE_CASE_FAN  (TUNE_CASE_BED + ENABLED(HAS_FAN))
#define TUNE_CASE_ZOFF (TUNE_CASE_FAN + ENABLED(HAS_ZOFFSET_ITEM))
#define TUNE_CASE_TOTAL TUNE_CASE_ZOFF
```

this breaks the menu to be one short ... well at least the tune and move menu that I have checked so far
so with this in place you cant access the zoffset menu at all because its defaulting to 4
gona try to change the number back to 5 as it was to test this fix

**Comment by cosmoderp** [comment]
after having changing the number to 6 it let me access that part of the menu.  It did not babystep at all.  only changes the zoffset,

I think its just that the menu relies on back as an additional entry.  Which could be fixed with 
`if (select_tune.inc(TUNE_CASE_TOTAL + 1)) {` for example to account for the back button

**Comment by thinkyhead** [comment]
> to account for the back button

Thanks! I was wondering if the "Back" item needed to be accounted for.

**Comment by DasSmeagle** [comment]
What is the status of this fix? I am using Build 2.0.8.2. I see, I cannot change z-offset on my Ender-3 V2 (with DWIN). I cannot see babysteps in Tune. I can set the z-offest in tune or in normal menu, but I have to Auto-Home to make it really change something.

**Pull request merged**
