### PR TITLE
Fix chamber heater define names (#13597)

### PR DESCRIPTION
**Pull request by the-real-orca**
### Description
Fixing compiler issues with heated chamber:

There were some mismatches in the defines related to chamber heating:
- CHAMBER_HEATER_PIN -> HEATER_CHAMBER_PIN
- CHAMBER_HYSTERESIS -> TEMP_CHAMBER_HYSTERESIS

Additionally I added chamber output data to `getHeaterPower()`

### Related Issues
[BUG] [bugfix-2.0.x] CHAMBER_HEATER_PIN compile error #13597

### CODE REVIEW

**Comment by thinkyhead** [comment]
Sure you were using good reference? `TEMP_CHAMBER_HYSTERESIS` is the current name.

**Comment by thinkyhead** [comment]
Thanks for the fixes. Additionally, I've gathered all the heated chamber settings together and moved them to `Configuration_adv.h`

**Comment by thinkyhead** [comment]
…and removed references to `PIDTEMPCHAMBER` since this won't be added.

**Comment by InsanityAutomation** [comment]
Any reason you dont want to PID control the chamber? Given the timing differences here that can create some pretty big overshoots without it.

**Comment by thinkyhead** [comment]
Because it requires changes all over the place, and we have more pressing issues. If there is a time to add chamber PID, now is not that time!

**Comment by InsanityAutomation** [comment]
@thinkyhead Sounds good, I didnt interpret that as an "at this time" type statement. When I get around to it I want to add some of the safeties I do for automotive customers to this area as well (heater element monitoring aside from process sensor for example).

**Pull request merged**
