### PR TITLE
Update langage_fr.h

### PR DESCRIPTION
**Pull request by spilz87**
delete accents which are not displayed correctly on LCD screen
change "Interrompre impr." by "Pause impr." more explicite in french
change "Contrôler" by "Config/Ctrl" more explicite

### CODE REVIEW

**Comment by gege2b** [comment]
Doesn't the new system  used for translation ( the _UxGT() macro) take care of accentuated characters ? #5501 ( cc @thinkyhead )

Accents was merged against RC on d1ed28d498d5236866ed9aa6ad2b5f5e849df5b5 but without the macro, maybe this is why they're not correctly displayed on your printer?

I Agree on "pause impr." string, but I don't find "config/ctrl" is more explicit

**Comment by AnHardt** [comment]
@spilz87 
You are using a char based display?

@gege2b 
The _UxGT() macro is currently empty. It's only a preparation for a further step. Even this next step (i don't see that in the near future - not much interest by the interested party's - still much to do and not much time for Marlin) will not enable character base displays to show all accentuated symbols - what they can display is in their character ROM - hardware dependent.

Instead of changing language files forth and back you have to diversificate. Ether in a utf8 enabled file and an other, or in a unified file with 
```
#if ENABLED(DOGLCD)
  #define MSG_SPEED                         "Velocità"
#else
  #define MSG_SPEED                         "Velocita"
#endif
```

**Comment by spilz87** [comment]
If I can have accent, I will like it :) but it does not work on the LCD. Do I need to add an other library ?

For me : "controler" mean be able to change the consigne like bed temperature 
But it's not explicite for me that we can find parametters like PID value, it's more a "configuration"
That's why I find more explicit to have both

**Comment by spilz87** [comment]
I use both display :
4 lines characters 
Full screen display 128x64
Actually I use the full screen and I get the issue

**Comment by AnHardt** [comment]
On a graphical display (128x64) you should be able to see http://www.utf8-zeichentabelle.de/unicode-utf8-table.pl. If not, there is a bug somewhere - likely in the 'language_fr.h' file. On the normal 20x4 char based displays you usually can display https://www.sparkfun.com/datasheets/LCD/HD44780.pdf page 17.

**Comment by AnHardt** [comment]
Add
```
#define MAPPER_C2C3
```
near
```
#define DISPLAY_CHARSET_ISO10646_1
```

**Comment by spilz87** [comment]
Your solution works 
Thanks
An other error : 
MSG_TEMPERATURE -> Température (é not z)

**Comment by AnHardt** [comment]
I prefer languages in this order:
C
German
C++
English
...

French is about at the mid of my list, right before languages with only strange symbols.
So correcting French will be your part.

**Comment by spilz87** [comment]
It's ok for me if I can help
But it the first time i do it in a project like this.
What I should do ? Close this request and open a new one ?
And what about part that people are not agree with (like control) ? 
Regards

**Comment by AnHardt** [comment]
If you ask me -
Close this PR.
Make it work on both of your displays.
About language details - discuss with others (father, son, wife, neighbor, others here) until you are sure what to do and have good arguments for your version.
Submit an other PR.

**Comment by spilz87** [comment]
Ok thanks

**Comment by gege2b** [comment]
@spilz87 I will correct the typo on "température" (my fault ^_^)
edit : in fact, it wasn't my typo. It's already fixed in RCBugFix :)

@AnHardt does I need to add the #define MAPPER_C2C3 as well ? or is this only to fix this particular issue ?

**Comment by AnHardt** [comment]
If you want accented symbols on the graphic screens the mapper is necessary. It will have no bad effect on the char based displays.

> Make it work on both of your displays. 

includes testing.

**Comment by gege2b** [comment]
OK I will add this on my next batch of translation then

**Pull request closed without merging**
