### PR TITLE
Add PROBE_MANUALLY — ABL without a probe

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR extends all forms of ABL with a manual probing option by simply adding a new type of probe, `PROBE_MANUALLY`, which indicates that there is no physical probe.

Following a simpler pattern than MBL, you simply use `G29` to start and `G29` to move to the next point. Repeat `G29` until the grid is complete. (If it proves "safer" to have a flag for continuing a leveling procedure, then I suggest `G29 C` for continue.)

Use `G29 J` to _Jettison_ the current leveling grid. `G29 W Xnn Ynn Znn` is used to Write a probe point.

LCD support is not yet implemented, but `MANUAL_BED_LEVELING` is renamed to `LCD_BED_LEVELING` and `MANUAL_PROBE_Z_RANGE` is renamed to `LCD_PROBE_Z_RANGE`. LCD support will follow the pattern of `M600`, updating the display from `gcode_G29`, except during manual Z adjustment, for which I'll implement a standardized Z-adjust screen.

Once LCD support is added this feature renders `MESH_BED_LEVELING` obsolete.

[Concise diff](https://github.com/MarlinFirmware/Marlin/pull/6050/files)

### CODE REVIEW

**Comment by Roxy-3D** [comment]
@thinkyhead   Please take a look at this code (Cut  & Pasted from UBL_G29.cpp).    Manually probing sucks.   But if you don't have a probe...  This code really does work.   My suggestion is we use this as a starting point and find ways to improve it.    I'm thinking we should Cut this out of UBL_G29.cpp and make it its own file that can be included if #define MANUAL_PROBE is enabled.

The user can watch both the LCD Display and the nozzle to determine when the 'position' is correct.   It is a total nuisance to use.   But it does work!

<details><summary>Code Sample</summary>

```cpp
void manually_probe_remaining_mesh( float X_Pos, float Y_Pos, float z_clearance, float card_thickness, bool do_mesh_map ) {
struct mesh_index_pair location;
float last_x, last_y, dx, dy;
float xProbe, yProbe, measured_z;
unsigned long cnt;

    UBL_has_control_of_LCD_Panel++;
    last_x = -9999.99;
    last_y = -9999.99;
    save_UBL_active_state_and_disable();	 // we don't do bed level correction because we want the raw data when we probe
    do_blocking_move_to_z( z_clearance );     
    do_blocking_move_to_xy( X_Pos, Y_Pos );

    do {
	if ( do_mesh_map )
    		blm.display_map(1);

	location = find_closest_mesh_point_of_type( INVALID, X_Pos,  Y_Pos, 0, NULL);	// The '0' says we want to use the nozzle's position
											// It doesn't matter if the probe can not reach the 
											// NAN location.  This is a manual probe.
    	if (location.x_index<0 && location.y_index<0 ) 
		continue;

	xProbe = blm.map_x_index_to_bed_location(location.x_index); 
	yProbe = blm.map_y_index_to_bed_location(location.y_index);
	if ( xProbe<X_MIN_POS || xProbe>X_MAX_POS || yProbe<Y_MIN_POS || yProbe>Y_MAX_POS)  {
		SERIAL_PROTOCOLLNPGM("?Error: Attempt to probe off the bed.");
		UBL_has_control_of_LCD_Panel = 0;
		goto LEAVE;
	}

	dx = xProbe - last_x;
	dy = yProbe - last_y;

        if ( sqrt(dx*dx+dy*dy) < BIG_RAISE_NOT_NEEDED ) 
		do_blocking_move_to_z( current_position[Z_AXIS] + SIZE_OF_LITTLE_RAISE );
	else 
		do_blocking_move_to_z(z_clearance);

	last_x = xProbe;
	last_y = yProbe;
	do_blocking_move_to_xy( xProbe, yProbe );

	while (!G29_lcd_clicked() ) { 		// we need the loop to move the nozzle based on the encoder wheel here!
		idle();
		if ( G29_encoderDiff != 0) {
			float new_z;					
			// We define a new variable so we can know ahead of time where we are trying to go.
			// The reason is we want G29_encoderDiff cleared so an interrupt can update it even before the move 
			// is complete.  (So the dial feels responsive to user)
			new_z = current_position[Z_AXIS]+((float) G29_encoderDiff)/100.0;
			G29_encoderDiff = 0;			
			do_blocking_move_to_z( new_z );
		}	
	}

	cnt = millis();
	while ( G29_lcd_clicked() ) { 		// debounce and watch for abort
		idle();
		if (millis()-cnt > 1500L ) {
			SERIAL_PROTOCOLLNPGM("\nMesh only partially populated.");
			do_blocking_move_to_z(Z_RAISE_PROBE_DEPLOY_STOW);     
			lcd_quick_feedback();
			while ( G29_lcd_clicked() )  	
				idle();
			UBL_has_control_of_LCD_Panel = 0;
   			restore_UBL_active_state_and_leave();
			return;
		}
	}

	z_values[location.x_index][location.y_index] = current_position[Z_AXIS] - card_thickness;
	if (G29_Verbose_Level > 2) {
		SERIAL_PROTOCOL("Mesh Point Measured at: ");
		SERIAL_PROTOCOL_F( z_values[location.x_index][location.y_index], 6 );
		SERIAL_PROTOCOL("\n");
	}
    } while (location.x_index>=0 && location.y_index>=0 );

    if ( do_mesh_map )
   	blm.display_map(1);
LEAVE:
    restore_UBL_active_state_and_leave();
    do_blocking_move_to_z(Z_RAISE_PROBE_DEPLOY_STOW);     
    do_blocking_move_to_xy(X_Pos, Y_Pos);     
}
```
</details>

**Comment by thinkyhead** [comment]
The method I'm putting together at the moment is pretty clean. The `gcode_G29` code doesn't take control of the LCD or require it. So you can do a host-controlled procedure without LCD involvement similar to the way MBL works (in this case, just `G29` called repeatedly). It works with `LINEAR`, `BILINEAR`, and `3POINT`.

For the LCD "Level Bed" command I just extended the MBL version of the LCD menus. The `PROBE_MANUALLY` version is agnostic about which kind of (ABL) leveling is enabled. All the code does is call `G29` on each click, returning to the adjust-Z screen until done. The code should work with any new leveling without change, as long as the method is implemented as an extension to ABL (or follows the same pattern).

**Comment by Roxy-3D** [comment]
> All the code does is call G29 on each click, returning to the adjust-Z screen until done. The code should work with any new leveling without change, as long as the method is implemented as an extension to ABL (or follows the same pattern).

OK...   But if we included an extra #define option that says to actually move (and reposition) the nozzle during manual probing, the user can watch the nozzle lower and get closer to the glass.    That is done in the UBL version Cut & Pasted above (and at least so far...  I don't see it in you code).    Having the nozzle move is nice because you can get your eyes level with the glass and look across it and say "I've got the nozzle at the 'correct' height for this location."

**Comment by thinkyhead** [comment]
> Having the nozzle move is nice because you can get your eyes level with the glass and look across it and say "I've got the nozzle at the 'correct' height for this location."

Yep. That's how it works. It actually moves the nozzle during manual probing. (How else??)

**Comment by Roxy-3D** [comment]
OK...  One more question...    Can a Manual Probe Type co-exist with a normal (or servo driven) probe type?   This would be very useful for the case where the normal probe can not reach locations because of the `?_OFFSET_FROM_EXTRUDER` numbers.   It may be the normal probe is used for most measurements but the manual probe can be used for the areas that can not be reached by that probe.

**Comment by thinkyhead** [comment]
> Can a Manual Probe Type co-exist with a normal (or servo driven) probe type?

Not at this time. It's a separate type of probe, and alters the behavior of `G29` similarly to MBL.

**Comment by Roxy-3D** [comment]
>> Can a Manual Probe Type co-exist with a normal (or servo driven) probe type?

> Not at this time. It's a separate type of probe, and alters the behavior of G29 similarly to MBL.

The reason for the question is I was hoping to be able to remove the manual probe function for UBL.  If there was a general purpose version available I could drop 100 lines of code.

**Comment by thinkyhead** [comment]
> If there was a general purpose version available I could drop 100 lines of code.

It will come together, but perhaps not till 1.1.1. The BILINEAR, MBL, and UBL leveling all have a lot in common. Except of course, we can't tilt our meshes…. yet.

**Pull request merged**
