### PR TITLE
Add autotemp capabilities to M104

### PR DESCRIPTION
**Pull request by FHeilmann**
This allows M104 to pass the F and B parameters to set autotemp parameters similar to M109

### CODE REVIEW

**Comment by FHeilmann** [comment]
One could also avoid code duplication and create a single "autotemp_M109M104()" function

**Comment by thinkyhead** [comment]
Yes. I would recommend renaming `autotemp_M109` to `autotemp_M104_M109` instead, and keeping just the one method.

**Comment by thinkyhead** [comment]
Thanks! Squashed and will merge #5238 shortly….

**Comment by FHeilmann** [comment]
While I'm thinking about it. Is autotemp capable of dealing with multiple extruders? Like having separate min/max/factor values for each extruder and setting the temperatures accordingly?

**Comment by thinkyhead** [comment]
Extruders are still expected to be near-identical in the current Marlin. We don't yet even allow them to have differing steps-per-mm (etc.) values. The issue is that as more indirection is introduced, the more this slows down planner/stepper operations, which are already pushing their performance limits.

**Pull request closed without merging**
