### PR TITLE
M20 with file size

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
M20 L1 will list the size in addition to the file name.  Repetier Host seems to be happy with it.

No effort at optimization.

Still has the creation & last modify dates as an option. 

Per issue #4733

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Per @foosel , other firmwares just output the filename, then a space and then the file size in bytes when printing a directory.  No options, no arguments, just the M20 command by itself.

This commit implements the above.

I have a local copy of the M20 L1 flavor just in case the team decides differently.

**Comment by Roxy-3D** [comment]
This is unrelated to this Pull Request.   But it would be nice if we could figure out how to display the long filenames better on the LCD Panel.   It's not too big of a deal for me because I typically don't have very many GCode files on the SD-memory card.   But some people do and it is hard for them to pick the right file.

It would be nice if the 'real' name was visible instead of the contorted 8.3 name.  And it would be nice if the whole name could be seen (including the extension) instead of the first part of the name.

**Comment by thinkyhead** [comment]
Ready to merge at #6325

**Comment by thinkyhead** [comment]
> long filenames better on the LCD Panel

Currently the first 20 characters of the long filename are shown on the LCD when a print starts.
```cpp
lcd_setstatus(longFilename[0] ? longFilename : fname);
```

In some forks of Marlin the authors have used a function that scrolls the status line one character left (about twice per second) to reveal the rest of a longer status line message, pausing a little longer at the end of the message. That could be added to the main branch, and would be a welcome addition. It just has to interact nicely with the other features that blink the status line (progress bar, filament width, etc.). The switch to the other state should be delayed until after the scrolling completes.

> It would be nice if the 'real' name was visible instead of the contorted 8.3 name.

The `M33` command (`LONG_FILENAME_HOST_SUPPORT`) was created in case hosts wanted to use it. The idea would be to first get the short-name file listing and, for example, display it in a file dialog. Then, in a separate thread the host would send `M33` with the full path of each long-name it wanted to display. As each long filename arrived the host would replace the short name in the file dialog with the long name.

The reason being, you do need the full path to open files through GCode anyway, and the DOS 8.3 formatted paths come through the serial connection more quickly. So a host-implemented file dialog can start to be useful as soon as the `M20` listing arrives, then "pretty up" the display afterward.

**Comment by Bob-the-Kuhn** [comment]
Could you point us to one of those implementations?

**Comment by thinkyhead** [comment]
The Prusa MK2 branch has this tweak, I believe.

**Pull request closed without merging**
