### PR TITLE
add tmc2240 config

### PR DESCRIPTION
**Pull request by ghost**
### Description

We have designed a new driver, TMC2240, and we have adapted it to the MKS motherboard (of course, other motherboards can also be matched, as long as the pins correspond.). Through comparing it with 2209, we found that it has better performance in high-speed printing, and it does not cause significant power loss at high speeds, and has better torque, making it very suitable for machines that require high-speed printing. We have adapted Marlin and made it a standalone library for use.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Thanks for your contribution! 

TMC2240 support is being added in https://github.com/MarlinFirmware/Marlin/pull/25974

**Comment by dbuezas** [comment]
@thisiskeithb Since the other PR is stale (and doesn't work), could it be worth picking this one up which is apparently working?

**Comment by thisiskeithb** [comment]
> Since the other PR is stale (and doesn't work), could it be worth picking this one up which is apparently working?

The other PR was updated 10 hours ago, so I’d hardly call that stale. It’s also more complete / in line with current Marlin standards, so development & discussions should continue over there.

**Comment by dbuezas** [comment]
I see. The commit's dates are from 2024 so I assumed it was just an automated rebase pr branches job

**Pull request closed without merging**
