### PR TITLE
Fix the codebase

### PR DESCRIPTION
**Pull request by thinkyhead**
- Get rid of `EITHER` and `BOTH` because the existence of redundant macros scares away would-be contributors.

### CODE REVIEW

**Comment by EvilGremlin** [comment]
ALL and NONE should stay i think

**Comment by thinkyhead** [comment]
> `ALL` and `NONE` should stay i think

Yes, I came to the same conclusion pretty quickly.

**Comment by Roxy-3D** [comment]
For me the big problem with EITHER is it kind of sounds like it needs one, and only one of the conditions to be satisfied in order to be true.   EITHER kind of sounds like just one can true.   ANY doesn't cause those kind of questions to come up.

**Comment by mriscoc** [comment]
> For me the big problem with EITHER is it kind of sounds like it needs one, and only one of the conditions to be satisfied in order to be true.

I always thought the same.

**Pull request merged**
