### PR TITLE
Fix Endstop Test Menu

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

As noted in https://github.com/MarlinFirmware/Marlin/pull/26326#issuecomment-1760378301, there are now quotes around axis Min/Max strings, so this PR removes those. I also noticed that the last character was cut off of the filament runout state (PRESENT = PRESEN and out = ou), so I fixed that. There's likely a better fix than just adding a blank space, but it works.

#### Before

image

#### After

image

### Requirements

Any `HAS_MARLINUI_MENU` config with `LCD_ENDSTOP_TEST` enabled.

### Benefits

Cleaner Endstop Test menu.

### Configurations

Any `HAS_MARLINUI_MENU` config with `LCD_ENDSTOP_TEST` enabled.

### Related Issues

- https://github.com/MarlinFirmware/Marlin/pull/26326#issuecomment-1760378301

### CODE REVIEW

**Comment by thisiskeithb** [comment]
CI failures are not related to this PR. Looks like they started with e7e77d9612253cf7106cfc9e69f69e52f4083294 from earlier today and d695e5f7bc409bc3d8ede798db5205c2c6a162f1 is also causing issues.

**Comment by thijstriemstra** [comment]
Thanks! If we'd want to take this even further; my CNC uses X, X2, Y, Y2, Z so it shows up like:

```
X Min:
X2 Min:
Y Min:
Y2 Min:
```

Would be nice to align them with an extra space if needed, eg:

```
X  Min:
X2 Min:
Y  Min:
Y2 Min:
```

And to be honest, the `:` is maybe not even needed, saving space for extra char?

```
X  Min      open
X2 Min      open
Y  Min      open
Y2 Min      open
```

**Comment by thisiskeithb** [comment]
> Would be nice to align them with an extra space if needed, eg:

I'm not sure we have a macro for that.

> And to be honest, the : is maybe not even needed, saving space for extra char?

We're not cramped for space and use colons elsewhere in the UI, so I think they're fine.

**Comment by ellensp** [comment]
```CPP
  #define STOP_ITEM(A,I,M,L) TERN(HAS_##A##I##_##M##_STATE, _STOP_ITEM, _IF_1_ELSE)(STRINGIFY(A) TERN(I," ",STRINGIFY(I)) " " STRINGIFY(L), A##I##_##M)
```
should auto add a space, but will always say "X<space:<space>Min"  when if there is no X2,Y2 etc

**Comment by ellensp** [comment]
```CPP
  #define NEEDS_SPACE TERN0(HAS_X2_MIN_STATE,1) || TERN0(HAS_X2_MAX_STATE,1) || TERN0(HAS_Y2_MIN_STATE,1) || TERN0(HAS_Y2_MAX_STATE,1) || TERN0(HAS_Z2_MIN_STATE,1) || TERN0(HAS_Z2_MAX_STATE,1) || TERN0(HAS_Z3_MIN_STATE,1) || TERN0(HAS_Z3_MAX_STATE,1) || TERN0(HAS_Z4_MIN_STATE,1) || TERN0(HAS_Z4_MAX_STATE,1)
  #define STOP_ITEM(A,I,M,L) TERN(HAS_##A##I##_##M##_STATE, _STOP_ITEM, _IF_1_ELSE)(STRINGIFY(A) TERN(NEEDS_SPACE,TERN(I," ",STRINGIFY(I)),STRINGIFY(I)) " " STRINGIFY(L), A##I##_##M)
```

should do it and only add the extra space if there is a 2 char endstop

NEEDS_SPACE could probably be shorted with another macro...

**Comment by thisiskeithb** [comment]
@thijstriemstra: Give this PR a try. With @ellensp's suggestion, it should now align endstop names.

**Comment by thijstriemstra** [comment]
@thisiskeithb looks 👍🏻 with `BTT_MINI_12864`

image

> We're not cramped for space and use colons elsewhere in the UI, so I think they're fine.

Agreed.

One last nitpick: why is "open" lowercase? It'll probably look better if it's also capitalized like the others. Large text also helps when viewing screen from a distance.

**Review by thijstriemstra — APPROVED** [review]

**Comment by thisiskeithb** [comment]
> One last nitpick: why is "open" lowercase? It'll probably look better if it's also capitalized like the others. Large text also helps when viewing screen from a distance.

I think it just followed the [`M119` format](https://marlinfw.org/docs/gcode/M119.html). I don’t know why it’s that way.

**Comment by thijstriemstra** [comment]
> I think it just followed the [M119 format](https://marlinfw.org/docs/gcode/M119.html). I don’t know why it’s that way.

Then it's fine like this, cheers.

**Comment by ellensp** [comment]
Updated version, made it a bit easier to read, and reduced the very long NEEDS_SPACE macro with _NEEDS_SPACE

```CPP
  #define _NEEDS_SPACE(N) TERN0(HAS_##N##_MIN_STATE,1) || TERN0(HAS_##N##_MAX_STATE,1)
  #define NEEDS_SPACE _NEEDS_SPACE(X2) || _NEEDS_SPACE(Y2) || _NEEDS_SPACE(Z2)
  #define STOP_ITEM(A,I,M,L) TERN(HAS_##A##I##_##M##_STATE, _STOP_ITEM, _IF_1_ELSE)(STRINGIFY(A) TERN(I, TERN(NEEDS_SPACE, " ", ""), STRINGIFY(I)) " " STRINGIFY(L), A##I##_##M)

```

Also dropped looking at Z3 and Z4 in the NEEDS_SPACE macro as Z2 is enough, can't have Z3 or Z4 without Z2

**Comment by thisiskeithb** [comment]
> Updated version, made it a bit easier to read, and reduced the very long NEEDS_SPACE macro with _NEEDS_SPACE

Squashed and force-pushed this update.

**Comment by thinkyhead** [comment]
I went ahead and fixed the macro usage, with a more explicit expansion of space or empty string based on the empty or non-empty index parameter. I haven't tested it yet, but the use of the `THIRD` macro *looks* right to me!

**Comment by ellensp** [comment]
indenting space no longer works...  after this change

**Comment by ellensp** [comment]
Works as expected now

**Comment by ellensp** [comment]
looks good

**Comment by thinkyhead** [comment]
> Works as expected after expansion.

If the strings here need the extra spaces to properly appear at the right edge of the screen then there might be a more general problem with `SS_FULL` alignment in the implementation of `MenuItem_static::draw`. Maybe an extra space is being inserted in the middle.
```cpp
PSTRING_ITEM_N_P(
  N-1,
  MSG_FILAMENT_EN,
  (READ(FIL_RUNOUT##N##_PIN) != FIL_RUNOUT##N##_STATE) ? PSTR("PRESENT ") : PSTR("out "),
  SS_FULL
);
```

**Comment by ellensp** [comment]
Can we have some case standardization?
filament status is PRESENT or out 
Endstops are  TRIGERED or open

**Comment by ellensp** [comment]
filament spacing looks fine
out
present

**Comment by thisiskeithb** [comment]
> filament spacing looks fine

Is that with the PR as it stands now (with the extra space at the end) or did you remove it?

**Comment by ellensp** [comment]
That is 

  #define FIL_ITEM(N) PSTRING_ITEM_N_P(N-1, MSG_FILAMENT_EN, (READ(FIL_RUNOUT##N##_PIN) != FIL_RUNOUT##N##_STATE) ? PSTR("PRESENT ") : PSTR("out "), SS_FULL);

space after string

Without the space the T or t  is missing (cut off) 

cut

so yes, some sort of spacing issue going on to require extra space at end of string

**Comment by thinkyhead** [comment]
The padding needs to take label expansion into account. For example, "`Filament *`" with length 10 might expand to "`Filament E2`" with length 11. For now I just added logic to look for the difference in expanded label length and adjust the padding accordingly.

**Comment by thijstriemstra** [comment]
I'm impressed how you people tackled this problem, and almost feel sorry by sucking up time away from other features with my feedback 😸 The endstop debug menu is a really useful feature though and was in need of some tlc.

**Comment by thinkyhead** [comment]
> I'm impressed how you people tackled this problem, and almost feel sorry by sucking up time away from other features with my feedback 😸 The endstop debug menu is a really useful feature though and was in need of some tlc.

No worries, it's important for us to squash every bug, large or small. Broken user experience deserves some priority attention.

**Comment by thisiskeithb** [comment]
All of those later changes ended up causing issues with spacing elsewhere:

image

Bug filed:
- https://github.com/MarlinFirmware/Marlin/issues/26413

**Pull request merged**
