### PR TITLE
Fix do_z_clearance in g28.cpp and prevent multiple rise

### PR DESCRIPTION
**Pull request by swissnorp**
### Description

**1.  Change do_z_clearance(...) in G28.cpp:**
  - true is not always the case.  If position is higher than Z_HOMING_HEIGHT and the bed drops because of disabled steppers, there will be no z-clearance move!
  - to prevent it from multiple rise if axis_known_position is false, there is set a flag to true if a rise was done

**2. Change "DISABLE_AXIS_Z() do{..." in indirection.h** 
  - reset the flag for do_z_clearance(...) in G28.cpp when z-stepper is disabled

**3. Add the flag z_rise_flag in motion.h and motion.cpp as a bool.**

### Benefits

1. No more scratching over the bed when homing after steppers have been disabled and nozzle has dropped.

2. No more multiple z-rise when homing axes individualy before z has known state.

### Related Issues

No Issues related so far but i kindly ask to revert the following commits:
  - https://github.com/MarlinFirmware/Marlin/commit/121cd42c41f3208327c93d84fa32a95f27dde227 (Main Branch)
  - https://github.com/MarlinFirmware/Marlin/commit/73ce80af3a3f8415a7c3f7f5551b429d58019a05 (Bugfix Branch)

Sort of related to:
  - https://github.com/MarlinFirmware/Marlin/pull/18842

### CODE REVIEW

**Comment by thinkyhead** [comment]
> the bed drops because of disabled steppers

If this is possible, the best solution would be to set the Z position to `Z_MAX_POS` every time the Z stepper powers off on such machines.

**Comment by swissnorp** [comment]
> 
> 
> > the bed drops because of disabled steppers
> 
> If this is possible, the best solution would be to set the Z position to `Z_MAX_POS` every time the Z stepper powers off on such machines.

I Changed the Pull Request.

Thats an elegant an simple solution you suggested... But I took `Z_MIN_POS` because the nozzle dropps and not the bed.

**Comment by XDA-Bam** [comment]
>
> I Changed the Pull Request.
> 
> Thats an elegant an simple solution you suggested... But I took `Z_MIN_POS` because the nozzle dropps and not the bed.

That depends on the printer design, doesn't it? On a typical cartesian, the nozzle coud drop. On a typical CoreXY, the bed could drop. Do we need an alternative `#define DROPPING_BED ` option to cover both cases?

**Comment by swissnorp** [comment]
`#define DROPPING_BED` should not be needed because it does not need a rise of the z axis.. respective its covered by `UNKNOWN_Z_NO_RAISE`

**Comment by swissnorp** [comment]
Something is wrong.. when testing it the nozzle crashes into the bed... does it have something to do with the planner?

**Comment by thinkyhead** [comment]
It does. You can't just modify the `current_position` without calling something like `line_to_current_position` or —as needed in this case— `planner.sync_plan_position`.

**Comment by GMagician** [comment]
I'm trying to figure out how this works. I can't see where axis_active.? is set to false... Any hint?

Edit: I renamed variable and compiled.. It seems they are never set to false...

**Pull request merged**
