### PR TITLE
fix #include errors detected.

### PR DESCRIPTION
**Pull request by Vertabreak**
fix #include errors detected. Please update your includePath. Squigges are disabled for this translation unit
cannot open source file "U8glib.h"

using a config that makes use of u8glib you can see this minor change makes the include warning disappear.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Do you have a link to the specific config that causes this error? Or build method?

I just tried compiling several u8glib-based configs based on the latest `bugfix-2.0.x` using VSCode 1.56.0 + PIO 5.1.1 and none of the configs error out or even have that warning.

Doesn't the `<>` around `<lib-name>` signify that it's external? Maybe that's throwing off some VSCode installs?

**Comment by Vertabreak** [comment]
the A10/A20 mixing series throw the error without the change.
these being the configs i use that presents the error.

https://github.com/Vertabreak/Vert-Marlin/tree/vert-bugfix-2.0.x-a10m-testing
https://github.com/Vertabreak/Vert-Marlin/tree/vert-bugfix-2.0.x-a10t-testing
image
https://github.com/Vertabreak/Vert-Marlin/tree/vert-bugfix-2.0.x-a20m-testing
https://github.com/Vertabreak/Vert-Marlin/tree/vert-bugfix-2.0.x-a20t-testing
image

**Comment by thisiskeithb** [comment]
> the A20 series throw the error without the change.
> these being the configs i use that presents the error.
> https://github.com/Vertabreak/Vert-Marlin/tree/vert-bugfix-2.0.x-a20-testing
> https://github.com/Vertabreak/Vert-Marlin/tree/vert-bugfix-2.0.x-a20m-testing
> https://github.com/Vertabreak/Vert-Marlin/tree/vert-bugfix-2.0.x-a20t-testing

I grabbed the first one and it compiles with zero warnings or errors:

```prolog
Indexing .pio/build/mega2560/libd5a/libU8glib-HAL.a
Linking .pio/build/mega2560/firmware.elf
Checking size .pio/build/mega2560/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [======    ]  61.0% (used 4995 bytes from 8192 bytes)
Flash: [========  ]  78.0% (used 198096 bytes from 253952 bytes)
Building .pio/build/mega2560/firmware.hex
=================================== [SUCCESS] Took 22.60 seconds ===================================

Environment    Status    Duration
-------------  --------  ------------
mega2560       SUCCESS   00:00:22.595
==================================== 1 succeeded in 00:00:22.595 ====================================

Terminal will be reused by tasks, press any key to close it.
```

Does this happen on more than one system?

**Comment by Vertabreak** [comment]
the not mixing versions don't present the issue i had already corrected the message.
and here is with the fix, seems to effect all mixing enabled configs.
image
image

**Comment by thisiskeithb** [comment]
Same with the mixing configs. I can't get them to error or throw warnings:

```prolog
Indexing .pio/build/mega2560/lib291/libU8glib-HAL.a
Linking .pio/build/mega2560/firmware.elf
Checking size .pio/build/mega2560/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=======   ]  73.4% (used 6012 bytes from 8192 bytes)
Flash: [========= ]  87.0% (used 221012 bytes from 253952 bytes)
Building .pio/build/mega2560/firmware.hex
=============================== [SUCCESS] Took 23.87 seconds ===============================

Environment    Status    Duration
-------------  --------  ------------
mega2560       SUCCESS   00:00:23.873
================================ 1 succeeded in 00:00:23.873 ================================

Terminal will be reused by tasks, press any key to close it.
```

**Comment by thisiskeithb** [comment]
Talking more with Vert on Discord, this issue shows up as a "Problem", but the library is still correctly included when wrapped in `<>` instead of `""`, so I'm not sure this is the correct "fix".

**Comment by Vertabreak** [comment]
all of the mixing enabled printers i maintain a branch for present with the missing include warning until i change <> to "" on the include. i have checked this on all 5 computers i have at my disposal all of them present the missing include. even if it does not effect everyone there seems to be no negative impact to correcting it.
image

**Comment by thinkyhead** [comment]
Unable to reproduce, using PlatformIO 5.1.1,  Atmel AVR 3.1.0, Arduino AVR Framework 5.1.0, Toochain 1.50400.190710 (5.4.0), and U8glib-HAL 0.4.4.

**Pull request closed without merging**
