### PR TITLE
[1.1.x] Different NEOPIXEL types

### PR DESCRIPTION
**Pull request by SCiunczyk**
I have the simple RGB NEOPIXEL LED strip based on latest WS2812B driver. With minor changes to the code this LED strip is fully supported. Adafruit NeoPixel library has all support included.

I have the 60 LEDs/m strip and full brightness is too intensive in my quite dark workshop. So I added the two things

    #define NEOPIXEL_BRIGHTNESS 255 - default start-up brightness for the strip
    P parameter to M150 "M" code to set brightness (similar to M355)

And the last thing. I have 600W bed heater - from zero to 100C runs in 30-40 seconds. So if I have sequential LED changes on my 40 LED strip, there is no chance to observe the nice blue to violet transition ;-). Next setup parameter was added to configuration.h #define NEOPIXEL_ISSEQ.

==
Changes to NEOPIXEL LED strips service
- Support for different NEOPIXEL as defined in Adafruit_NeoPixel.h
- ability to setup startup  brigtness
- ability to define sequential/nonsequential transition of color change during heating-up
- additional parameter to M150 <P>brightness

### CODE REVIEW

**Comment by fiveangle** [comment]
I'm probably dense, but I'm still struggling with the sequence feature: is it intended to turn the LEDs into a linear "meter" of the analog input, lighting additional LEDs as the input increases, and without the feature only the LED color changes across all the LEDs based on the analog input ?  If so, that's awesome – in that case, would NEOPIXEL_LINEAR_SEQUENCE or NEOPIXEL_SEQUENCE_LINEARLY charicterize what you're going for any better ?  If not, perhaps just adding the underscore,  "IS_…" would help ?

Thanks for this cool addition :)

**Comment by SCiunczyk** [comment]
I just used the original variable name from function:  
```
  void set_led_color(
    const uint8_t r, const uint8_t g, const uint8_t b
      #if ENABLED(RGBW_LED) || ENABLED(NEOPIXEL_RGBW_LED)
        , const uint8_t w = 0
        #if ENABLED(NEOPIXEL_RGBW_LED)
          , bool isSequence = false
        #endif
      #endif
  ) {
```
Have you seen the standard behaviour currently existing ? For "non NEOPIXEL" and NEOPIXEL strips ? If not I can explain how it works now and why I think that parameter will be nice to have. Of course I can change the parameter name but have to be sure ... not only one Configuration.h file to touch ;-)

This is no related to analogue/digital input.

**Comment by Tannoo** [comment]
There is also NEO_RGB AND NEO_RGBW.

**Comment by Tannoo** [comment]
>the sequence feature: is it intended to turn the LEDs into a linear "meter" of the analog input, lighting additional LEDs as the input increases, and without the feature only the LED color changes across all the LEDs based on the analog input ?

Exactly that.

**Comment by Tannoo** [comment]
I was thinking of changing the `NEOPIXEL_RGBW_LED` to just `NEOPIXEL_LEDS` and having different options for the types.

**Comment by Tannoo** [comment]
And another option for the number of pixels.

**Comment by SCiunczyk** [comment]
That was my first thought. But with my first PR I didnt wanna be so revolutionary ;-)

I can make this changes but let first agree about names of constants in Configuration.h. Maybe:

```
// Support for Adafruit Neopixel LED driver
#define NEOPIXEL_LED
#if ENABLED(NEOPIXEL_LED)
  #define NEOPIXEL_PIN    4        // LED driving pin on motherboard 4 => D4 (EXP2-5 on Printrboard) / 30 => PC7 (EXP3-13 on Rumba)
  #define NEOPIXEL_PIXELS 30       // Number of LEDs on strip
  #define NEOPIXEL_TYPE NEO_GRBW   // NEO_GRBW / NEO_GRB - four/three channel driver type (definned in Adafruit_NeoPixel.h)
  #define NEOPIXEL_IS_SEQUENTIAL   // Sequent display for temperature change - LED by LED. Comment out for all LED change at time
  #define NEOPIXEL_BRIGHTNESS 127  // Initial brightness 0-255
  #define NEOPIXEL_STARTUP_TEST    // Cycle through colors at startup
#endif
```
IMHO Separate option for number of pixels is redundant. The type specifies clearly it there is three/four pixels. [EDIT] Never mind was my misunderstand of "pixels"

Across the code there is only one purpose to have information about number of pixels - to light white colour. Not only in NEOPIXEL, but on others as well. I mean the construction:

```
#if ENABLED(SOMETHING_WITH_RGBW)
  set_colour(0, 0, 0, 255)
#else
  set_colour(255, 255, 255)
#endif
```

We can use macro definition
```
#if ENABLED(RGB_LED) || 
    NEOPIXEL_TYPE==NEO_RGB || 
    NEOPIXEL_TYPE==NEO_RBG || 
    NEOPIXEL_TYPE==NEO_GRB ||   
    NEOPIXEL_TYPE==NEO_GBR || 
    NEOPIXEL_TYPE==NEO_BRG || 
    NEOPIXEL_TYPE==NEO_BGR

  #define LED_WHITE 255, 255, 255
#else
  #define LED_WHITE 0, 0, 0, 255
#endif
```

then use: **set_colour(LED_WHITE)** when necessary?

**Comment by Tannoo** [comment]
>Across the code there is only one purpose to have information about number of pixels - to light white colour.

Really? Because if the number of Neopixels is lower than the string in use, it will only light the number of pixels specified. This also applies to the non white variants.

**Comment by SCiunczyk** [comment]
Are we talking about this same pixels ? I mean pixels - colours RGB or RGBW - 3/4

**Comment by SCiunczyk** [comment]
OK I see my fault

**Comment by SCiunczyk** [comment]
But there is already that parameter.

**Comment by Tannoo** [comment]
I see that... either I missed it, or was not there yesterday. Hmmm.

**Comment by SCiunczyk** [comment]
it was in version 1.1.5 (one week I think).

**Comment by Tannoo** [comment]
I may have just been out of focus... especially trying to learn the new layout.

**Comment by SCiunczyk** [comment]
My intention was to allow disabling of sequent change of pixels, because on my printer with 600W heated bed the whole heating process is lest than two minutes. I have 43 pixels in my strip. Change of colour is made every second so practically I have only two turns full of LED lighting until heating is finished. And it quite looks strange. Not cool ;-)

**Comment by SCiunczyk** [comment]
Should I Stay or Should I Go  .... with changes suggested by @Tannoo ? ;-)

**Comment by RalphSch** [comment]
Wouldn't it be better (as already mentioned multiple times in the FR/PR for adding Neopixel support and many other FR/PR for other led stripes types) to get rid of the brandname Neopixel (it's just a confusing advertisement) and the really bad and slow Adafruit library instead of extending that crap more and more?
Better use FastLED library and find a name which clearly suggests, that it simply supports nearly every bus type led stripe instead of only the overpriced Adafruit ones.
https://github.com/FastLED/FastLED

**Comment by SCiunczyk** [comment]
You are absolutely right @RalphSch . Just do it!

**Comment by RalphSch** [comment]
It was already done and ready for merge, just search for WS2812 or Neopixel through the issues.

@Tannoo do you still have your code from Tannoo:RGB_Printer_Events? Maybe we could reactivate your work because Marlin 2.0 is out and the given adafruit led stripes code get more and more ugly with every extension to it.

**Comment by SCiunczyk** [comment]
I wonder why it wasn't merged before?

**Comment by RalphSch** [comment]
It was ready to go, it was just waiting for the 2.0 code freeze (if I remember right) ... then someone came with this new Neopixel PR #7284 / #7340 which was quickly merged without regarding all the comments about the already given, nicer and better solution, which just was on hold and waiting. This Neopixel PR also broke my own code for the digidot-booster support, which is like an external led stripe accelerator to keep the needed communication overhead very small and the code for very cool effects very clean and simple, because I also wanted to wait for the Marlin 2.0 code freeze :\ .... but I also didn't had any more motivations to invest more work before Marlin 2.0 is out.
@Tannoo I just red #7390 , so there is still some work in progress for your led stripes implementation and it's not buried?

**Comment by SCiunczyk** [comment]
OK I understand, But I'm a innocent simple guy who have simple WS2812B (RGB) strip and I want it working on my printer :-) Seems I entered in to middle of "nuclear war"....

**Comment by RalphSch** [comment]
Ah, it isn't ;) Just wanted to push this topic a little bit because you also got to the point that the neopixel implementation needs a little bit tweaking. I also like your brightness and startup brightness feature :)

**Comment by SCiunczyk** [comment]
... and my tweak move hardcoded LED_RGBW to Configuration.h NEOPIXEL_TYPE - this open more types. 

But I agree with you that lighting feature (case, frame, head, spindle etc) should be cleaned and maybe moved out of  Marlin_main.cpp to separate file.

**Comment by Tannoo** [comment]
Well, I likely have it somewhere... it had been forgotten and when the neopixel lib was added... I just went with the flow. I am still getting things to work like I had it on my printer.

**Comment by Tannoo** [comment]
The new layout threw all of the printer events I had into a tailspin. Lol

**Comment by fiveangle** [comment]
Yeah, @Tannoo - didn't you have a WS2812B library that was written generically to support all the variants and used FastLed that you were going to drop as mentioned in https://github.com/MarlinFirmware/Marlin/issues/7271 ?    Would be good to maybe compare/compare to what @SCiunczyk has done here :)

**Comment by Tannoo** [comment]
I didn't write any library. The fastLED library was used.

I have backups of that in use, but don't keep it up to date.

I have since dropped it to move forward with what is here.
I have also deleted that branch. As things have changed drastically lately. I now have a `My_AVR` and `My_Re-ARM` branches.

Here is a backup of that was current at the time and has that fasLED library integration. Take a look.
https://drive.google.com/open?id=0B560i8PeUNErNzlrUFpQVVNhOTA

**Comment by Tannoo** [comment]
The latest that I have been working on is `My_new_AVR` branch.

**Comment by Tannoo** [comment]
I've applied this PR to my `bugfix-2.0.x`. Maybe I missed something, but the P parameter does nothing and the `NEOPIXEL_BRIGHTNESS` doesn't seem to work.

But, all the original `M150` commands still work just fine.

**Comment by Tannoo** [comment]
Although, I did leave out the `LED_WHITE` stuff.

**Comment by SCiunczyk** [comment]
> I've applied this PR to my bugfix-2.0.x. Maybe I missed something, but the P parameter does nothing and the NEOPIXEL_BRIGHTNESS doesn't seem to work.

The command M150 Pxxx visually does nothing. Only change the brightness parameter of pixels object. Please try with some color e.g. M150 R2255 P100 then M150 R255 P10. My idea was to allow lower level of white used by firmware because in code its always set full 255, 255, 255 (or 0,0,0,255). And on my printer in dark room was to bright. (43 pixels strip)

changes in function for initial brightness
```
void setup_neopixel() {
-      pixels.setBrightness(255); // 0 - 255 range
+      pixels.setBrightness(NEOPIXEL_BRIGHTNESS); // 0 - 255 range
```
and added parameter to: set_led_color
```
  void set_led_color(
     const uint8_t r, const uint8_t g, const uint8_t b
-      #if ENABLED(RGBW_LED) || ENABLED(NEOPIXEL_RGBW_LED)
+      #if ENABLED(RGBW_LED) || ENABLED(NEOPIXEL_LED)
         , const uint8_t w = 0
-        #if ENABLED(NEOPIXEL_RGBW_LED)
+        #if ENABLED(NEOPIXEL_LED)
+          , const uint8_t p = NEOPIXEL_BRIGHTNESS
           , bool isSequence = false
```

**Comment by Tannoo** [comment]
Well, `M150 R127` works just fine. But `M150 R255 P127`, `M150 R255 P10` does nothing. It's still on full Red.

But `M150 R` also sets them full bright.

**Comment by SCiunczyk** [comment]
Strange. Take a look into construction used by me in M150 code. If P is is without number it used 255 but if is omitted at all used pixels.getBrightness()

**Comment by SCiunczyk** [comment]
could you please send sequence:
M150 R255 P10
M150 U255 P10
M150 U255 P255
and tell me the results ?

**Comment by SCiunczyk** [comment]
wrong ;-) the sequence:

M150 R255 P10
M150 U255      ; green should use brightness from previous command
M150 U255 P255

**Comment by Tannoo** [comment]
M150 R255 P10 >>> Full Red
M150 U255       >>> Full Green
M150 U255 P255 >>> Full Green

**Comment by Tannoo** [comment]
I am not worried at all about the P function not working. I would just remove it. Because R127 or R10 works just fine. And it currently works with all of the supported types of LEDs that Marlin supports.

**Comment by SCiunczyk** [comment]
But its working on my version. Can I take a look at you code ? Without brightness regulation you always have full power white color. At the end of print is call set_color(255, 255, 255). 
I using PRINTER_EVENT_LEDS parameter.

**Comment by Tannoo** [comment]
I believe you. I did NOT include the white command macro.

Would that be why?

**Comment by SCiunczyk** [comment]
I don't think so. But have you include changes I mentioned in https://github.com/MarlinFirmware/Marlin/pull/7728#issuecomment-332423038 ?

**Comment by Tannoo** [comment]
Here is the current branch that I have that in: [My_new_AVR](https://github.com/Tannoo/Marlin/tree/My_new_AVR)

**Comment by SCiunczyk** [comment]
All clear now.
in src/feature/leds/neopixel.cpp
```
bool neopixel_set_led_color(const uint8_t r, const uint8_t g, const uint8_t b, const uint8_t w, const bool isSequence) {
  const uint32_t color = pixels.Color(r, g, b, w);
  const uint8_t p = NEOPIXEL_BRIGHTNESS;
  static uint16_t nextLed = 0;
  pixels.setBrightness(p);
  if (!isSequence)
    set_neopixel_color(color);
  else {
    pixels.setPixelColor(nextLed, color);
    pixels.show();
    if (++nextLed >= pixels.numPixels()) nextLed = 0;
    return true;
  }
  return false;
}
```
p is defined as const, but should be a parameter, then call in function set_led_color from src/feature/leds/leds.cpp should pass this parameter in line 45.

**Comment by SCiunczyk** [comment]
I'm thinking about little different behaviour of P parameter in M150. Don't change the RGBW values when there is P parameter alone. Only change the brightness keeping colours untouched. This will be more natural to the user.

**Comment by RalphSch** [comment]
I'm glad I got you guys working together on this :) I can help with testing SK6812 and WS2812B types on 8bit and also the 32bit Due (but it's not fully functional with Marlin 2.0 at the moment). If we have a clean and common base for all of the led types supported by FastLed then I will continue with the digidotbooster which provides simple and fast pixel addressing and thus allowing crazy effects even combined with printer states. It would be cool to get some kind of effect collection which is easy to use in the code and even with gcodes. Because the 32bit hardware is fast enough (maybe also the 8bit ones when using FastLed library) this effects could also get played by the controller directly instead of using the digidotbooster module.

**Comment by Tannoo** [comment]
I changed
`const uint8_t p = NEOPIXEL_BRIGHTNESS;`
to
`uint8_t p = NEOPIXEL_BRIGHTNESS;`
and no change... the `P` parameter does nothing.

**Comment by SCiunczyk** [comment]
Hi @Tannoo sorry for late answer I was in my marina to catch this season last sun beams on my yacht ;-)

You have to change the function parameters:

in neopixel.h:
```
bool neopixel_set_led_color(const uint8_t r, const uint8_t g, const uint8_t b, const uint8_t w, const uint8_t p, const bool isSequence);
```
in neopixel.cpp:

```
bool neopixel_set_led_color(const uint8_t r, const uint8_t g, const uint8_t b, const uint8_t w, const uint8_t p, const bool isSequence) {
  const uint32_t color = pixels.Color(r, g, b, w);
uint8_t p = NEOPIXEL_BRIGHTNESS; <<<--- remove this

```
and in leds.cpp:
```
  #if ENABLED(NEOPIXEL_LED)
    if (neopixel_set_led_color(r, g, b, w, p, isSequence))
      return;
#endif
```

**Comment by thinkyhead** [comment]
If everyone is satisfied with the changes, then there are just some general style things needing tweaking and they can get merged into 1.1.x and 2.0.x. I can't wait to put more flashing lights on my 3D printers!

@SCiunczyk See my comments on #7849 for the needed changes. Thanks!

**Comment by SCiunczyk** [comment]
@thinkyhead just a second, I have to get my morning caffeine fuel to start thinking ;-)

**Comment by thinkyhead** [comment]
…just as I am off to bed… Thanks for doing both 1.1 and 2.0. It's a load off!

**Pull request closed without merging**
