### PR TITLE
Add laser control menu for non-pwm lasers

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Adds LCD menu for laser on / off when spindle laser is configured without PWM

### CODE REVIEW

**Comment by rmoravcik** [comment]
Where is the definition of MSG_LASER_MENU string? I cannot find it.

**Comment by InsanityAutomation** [comment]
Src/LCD/language/language_en.h

**Comment by rmoravcik** [comment]
> Src/LCD/language/language_en.h

@InsanityAutomation Are you sure MSG_LASER_MENU isn't missing? I'm was trying to prepare an updated slovak translation and I'm not able to find the definition anywhere...

```
morgan@moravcikpc:~/Projekty/Marlin/Marlin-bugfix-2.0.x$ grep -R MSG_LASER_MENU *
Marlin/src/lcd/menu/menu_temperature.cpp:    MENU_ITEM(submenu, MSG_LASER_MENU, menu_spindle_laser);
morgan@moravcikpc:~/Projekty/Marlin/Marlin-bugfix-2.0.x$ 
```

**Comment by InsanityAutomation** [comment]
Just checked and it looked like as Scott was adding the pwm stuff to my original non pwm only code that message got chopped off somewhere between our changes. I'll put in a follow-up PR shortly to put that message back.

**Pull request merged**
