### PR TITLE
Correct E0 pins for Creality 4.3.1 board

### PR DESCRIPTION
**Pull request by thinkyhead**
As originally posted in #22703 by @Chicos123, with corrections according to [this spreadsheet](https://docs.google.com/spreadsheets/d/1DYhh9fwLnvZzuNvMoBen9Dl68KN-4TWkbO94lJ4iwe4/edit#gid=0).

### CODE REVIEW

**Comment by Chikorita0964** [comment]
i gave firmware someone for test, just now
he has ENDER 3 v2 4.3.1 board(original board, not replaced)
that board are X,Y  pins switched

```
name | 4.3.1
-----|-------------
PC2  | X_STEP_PIN
PB9  | X_DIR_PIN
PB8  | Y_STEP_PIN
PB7  | Y_DIR_PIN
```

Some of 4.3.1 boards have different variations?
```
name | 4.3.1_a
-----|-------------
PB8  | X_STEP_PIN
PB7  | X_DIR_PIN
PC2  | Y_STEP_PIN
PB9  | Y_DIR_PIN

name | 4.3.1_b
-----|-------------
PB8  | X_STEP_PIN
PB7  | X_DIR_PIN
PC2  | Y_STEP_PIN
PB9  | Y_DIR_PIN
PB3  | E0_STEP_PIN
PB4  | E0_DIR_PIN

name | 4.3.1_c
-----|-------------
PC2  | X_STEP_PIN
PB9  | X_DIR_PIN
PB8  | Y_STEP_PIN
PB7  | Y_DIR_PIN
PB3  | E0_STEP_PIN
PB4  | E0_DIR_PIN

name | 4.3.1_d
-----|-------------
PC2  | X_STEP_PIN
PB9  | X_DIR_PIN
PB8  | Y_STEP_PIN
PB7  | Y_DIR_PIN

```

**Comment by ellensp** [comment]
Ender 3 v2 comes with V4.2.2 or V4.2.7's  Never seen one with a V4.3.1... 

Though its creality, they like to change things without telling anyone!

Your "4.3.1_d" is the same as a V4.2.2 pins  Malin/src/pins/stm32f1/pins_CREALITY_V4.h   BOARD_CREALITY_V4 

It is possible the  4.3.1 X and Y are swapped. The Pins were derived from `firmware.bin` for a core X, Y, so there was no real X or Y.  It is working on the the original ender 6 corexy machines

Its also quite possible that Creality are sticking the wrong steppers in the wrong board plugs and just correcting for it in firmware.

**Comment by thinkyhead** [comment]
Well, I guess the simplest thing to do is to add more board IDs, since that is the obvious distinction.

**Comment by thinkyhead** [comment]
@Chicos123 — I've updated the pins based on your itemized pins list, so hopefully it is now correct. Where did you find that information?

**Comment by thinkyhead** [comment]
This PR is stalled awaiting corroboration, confirmation, and references.

**Pull request merged**
