### PR TITLE
Dual Extruder Stepper Driver

### PR DESCRIPTION
**Pull request by boelle**
EXPERIMENTAL code to drive a second extruder (E1) identically to the first (E0)
For setups with push-pull extruder motors and similar.
Thanks to Bo Herrmannsen & Marlin Discord

Pasted in by Alex Gibson (Edumaker) 20210321

### CODE REVIEW

**Comment by boelle** [comment]
if i pick bugfix 2.0.x as base it shows more than the 3 files i want to merge

**Comment by thisiskeithb** [comment]
Your patch starts from `2.0.x`, but you need to start your patch from `bugfix-2.0.x` and then target the `bugfix-2.0.x` branch when you create your PR.

---

Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `bugfix-2.0.x`.

See Marlin's [Contributing Code with Pull Requests](http://marlinfw.org/docs/development/getting_started_pull_requests.html) guide for full instructions.

**Comment by thisiskeithb** [comment]
The link in my reply above walks you through setting everything up.

**Comment by boelle** [comment]
just made a new PR, hope its better
this is a one off PR that i do for someone else so i dont have any tools installed other than github web

still need to figure out where to add my edits to pins.h as the files do not look the same at all

**Pull request closed without merging**
