### PR TITLE
Tm trex2+ 2.0.x

### PR DESCRIPTION
**Pull request by lenain31**
is not possible to flash this when activated trex3 define X_DRV8825 
#define Y_DRV8825 
#define Z_DRV8825 
#define E_LV8729 
files configuration.h

 // If you have a trex 3, stock is this option plus 2208 on all axis. None in spreadcycle.
#define TREX3

//#define X_2208
//#define X_Spreadcycle
//#define Y_2208 // Highly recommended as large prints with high mass can cause layer shifts with stealthchop at high speed
//#define Y_Spreadcycle
//#define Y_4988 // Some machines shipped with 4988 drivers across the board. Set this if you arent sure what you have and all the drivers look identical
//#define Z_2208 // NOT Recommended! Dual stepper current draw is above the recommended limit for this driver
//#define Z_4988 // Some machines shipped with 4988 drivers across the board. Set this if you arent sure what you have and all the drivers look identical
//#define Y_Spreadcycle
//#define E_2208 // Not Recommended! Stealthchop mode faults with linear advance
//#define E_Spreadcycle

#define BedAC

#define tallVersion

/*
 * Enables a filament sensor plugged into the laser pin. Disables the laser
 */
//#define FilamentSensor // Standard older TM3D runout sensor
//#define lerdgeFilSensor // Newer inverted logic TM3D Runout Sensor

//////////////////////////////////DO not edit below here unless you know what youre doing!  //////////////////////////////////

#if ENABLED(TREX3)
  #define X_DRV8825
  #define Y_DRV8825
  #define Z_DRV8825
  #define E_LV8729
  #define FilamentSensor

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
Firstoff, a pull request is not the best route to ask a question on this branch, Best to use the issues page on the branch itself.

Second, factory option will override the setting at the moment, but I can change that this weekend so an explicit drv8825 overrides the trex3 factory driver settings.

**Comment by lenain31** [comment]
Escuse me What do you think about tmc2208 is not good for the Stepper of T-rex3?If is possible drv8825 for y X and Z 👍

Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., déc. 20, 2018 à 18:50, InsanityAutomation<notifications@github.com> a écrit :   
Firstoff, a pull request is not the best route to ask a question on this branch, Best to use the issues page on the branch itself.

Second, factory option will override the setting at the moment, but I can change that this weekend so an explicit drv8825 overrides the trex3 factory driver settings.

**Comment by InsanityAutomation** [comment]
For Z, the TMC2208 isnt rated for the max current the dual steppers can draw even with forced air cooling. The stock mode of stealthchop is also a bit too low torque for Z or Y in my opinion on a Cartesian machine. For E, its prevents linear advance from being usable as it puts the driver in shutdown.

As for that branch's actual driver support, currently I only intend to support options that left the factory so I likely wont have it configured for 8825 on X or Y, as they have always been 4988, but if you remove J3 it will function identically to the 4988 and work fine with those options.

**Comment by lenain31** [comment]
OK, thanksI put in E LV8729.And if I understand correctly in x y and z I can put the DRV8825 if I remove the jumper MS3 is that it?I also plan to put engine with a step angle of 0.9 instead of 1.8 thank you for the information it's very nice of you
Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., déc. 20, 2018 à 20:54, InsanityAutomation<notifications@github.com> a écrit :   
For Z, the TMC2208 isnt rated for the max current the dual steppers can draw even with forced air cooling. The stock mode of stealthchop is also a bit too low torque for Z or Y in my opinion on a Cartesian machine. For E, its prevents linear advance from being usable as it puts the driver in shutdown.

As for that branch's actual driver support, currently I only intend to support options that left the factory so I likely wont have it configured for 8825 on X or Y, as they have always been 4988, but if you remove J3 it will function identically to the 4988 and work fine with those options.

**Comment by Roxy-3D** [comment]
This pull request has 1600+ files modified.   Can you do a fresh a fork, and move the required changes into it?

**Comment by Roxy-3D** [comment]
> Firstoff, a pull request is not the best route to ask a question on this branch, Best to use the issues page on the branch itself.

Agreed.   And a Pull Request with 1600+ files modified won't be accepted anyway....

I'll leave this open until we get an issue or Pull Request in place to shift the discussion.

**Comment by InsanityAutomation** [comment]
@Roxy-3D There are no changes that would be pushed back towards anything here. Hes asking for a couple changes in the automatic setup defines used in the top of this branch, and its enormous because its a 2.0 branch pointed at 1.1 :)

**Comment by Roxy-3D** [comment]
OK...  I'll close it....     I'll assume you know what tweaks make sense and will keep tract of them...

**Pull request closed without merging**
