### PR TITLE
Add MINGDA D2 D301 v1.0 board

### PR DESCRIPTION
**Pull request by lscarneiro**
### Description

- This PR adds support for Mingda D2 D301 v1.0 board (aka DZ301 v1.0) that may also support Mingda Rock 3 Pro printers.
It uses a STM32F103ZET6 chip, with USB, SD Card Reader and a 3.5" TFT touchscreen (connected to the board via flat cable).

- The manufacturer uses a very old `bugfix-2.0.x` version of Marlin, and does not offer it on GitHub as a fork, which makes it harder to update to current `bugfix-2.1.x` Vanilla Marin.

- I was able to patch this working version by patching together some of the [source code from the manufacturer](https://www.3dmingda.cc/uploads/soft/20210402/Marlin%20source.rar) and also a lot of help from [marcellodum's fork from Marlin](https://github.com/marcellodum/marlin-mingda-md-d301).

- I was able to first build it with Maple because it was what those sources used, but considering it's deprecated by Marlin, I tried my best to find a way to build it using the current architecture, which took me quite a lot of trial and error because I'm not an embedded software developer. Anyways, I hope this can get merged in hopes of helping folks over Issue #21981 (me included).

- I'm already using it daily, and so far couldn't find issues yet.

- I stuck with D301 instead of DZ301 because most info online is found by searching `D301`

- The manufacturer used some homemade `EXTENSIBLE_UI` screen template that neither I or @marcellodum was able to port for modern Marlin, but can definitely be investigated on their source code linked above.

### Requirements

- An DZ301 v1.0 board:
  
image

### Benefits

- This will help some Mingda D2 (and maybe some Mingda Rock 3 PRO) owners be able to use up-to-date Marlin with their printer

### Configurations

I'm using these [Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/12888917/Configurations.zip) to make it work:
```c++
# Configuration.h
# ...
#define TFT_GENERIC
#if ENABLED(TFT_GENERIC)
  #define TFT_DRIVER ILI9488

  // Interface. Enable one of the following options:
  #define TFT_INTERFACE_FSMC

  // TFT Resolution. Enable one of the following options:
  #define TFT_RES_480x320
#endif
# ...
```

### Related Issues

- #21981

### CODE REVIEW

**Comment by lscarneiro** [comment]
Is there a way to restart the CI tests on this PR? It seems that the failure was unrelated to those changes...

**Comment by thisiskeithb** [comment]
> Is there a way to restart the CI tests on this PR? It seems that the failure was unrelated to those changes...

Merge latest `bugfix-2.1.x` changes in or CI will fail the same way.

**Comment by lscarneiro** [comment]
What is needed for this PR to be merged?

I'm not trying to rush things, just trying to understand how I can help, if I can at all ofc.

**Comment by thinkyhead** [comment]
> What is needed for this PR to be merged?

The more that you test and make adjustments based on your testing, the closer a PR will be to being complete and trusted. We'll just make adjustments to code formatting and style to fit the Marlin idiom, fix any bugs that we are able to see, and after a last pass at cleanup a PR will be pretty much ready to go.

**Comment by MrHenker27** [comment]
I neee a working configuration. I have a D2. Visual Studio make soweit errors.

Greets

**Comment by lscarneiro** [comment]
> I neee a working configuration. I have a D2. Visual Studio make soweit errors.
> 
> Greets

You can try with the one I attached to the PR

Look for ”Configurations.zip” here in this PR

**Comment by MrHenker27** [comment]
Okay, heute konnte ich die Source kompilieren. Scheinbar wurden zwischen vorgestern und heute nochmal Änderungen vorgenommen
Leider das selbe Problem wie immer: Y stepper stirbt einfach. Ich konnte das Problem beheben, als ich ihn auf 400mA 

Was nicht geht ist Babystepping. Dann resettet der Drucker wenn man auf OK klickt. 

Okay, today I was able to compile the source. Apparently some changes were made between the day before yesterday and today
Unfortunately the same problem as always: Y stepper just dies. I was able to solve the problem when I set it to 400mA 

What does not work is babystepping. Then the printer resets when you click on OK.

**Comment by lscarneiro** [comment]
I updated my own repo with the current vanilla `bugfix-2.1.x` branch and it seems to compile just fine and move X, Y and Z as expected, is your D2 stock @MrHenker27?

You can compare your `Configuration.h` and `Configuration_adv.h` against mine, here:
- [Configuration.h](https://github.com/lscarneiro/Marlin/blob/mingda-personal-config/Marlin/Configuration.h)
- [Configuration_adv.h](https://github.com/lscarneiro/Marlin/blob/mingda-personal-config/Marlin/Configuration_adv.h)

You can maybe download those two from the links above and do a side-by-side comparison against yours using VSCode or any other tool that works best for you.

**Comment by MrHenker27** [comment]
geändert.
BLTouch, NEOPixel LED und Temperaturgesteuerter Lüfter für das Hotend.

Das mit dem Y Stepper haben andere aber auch. Als wir damalös die 2.0.9.3 gebaut haben kam noch dazu das der E Stepper einfach auch ab und an gestorben ist. Den Y Stepper konnten wir ja mit der Stromstärke am weitermachen überreden.

Geht bei dir auch banbysteps ? Ich kann sonst nicht mein Z Offset ermitteln.

Ich teste morgen abend mal deine Config

changed.
BLTouch, NEOPixel LED and temperature-controlled fan for the hotend.

But others have the same thing with the Y stepper. When we built the 2.0.9.3 back then, the E stepper also died from time to time. We were able to persuade the Y stepper to continue with the current.

Do you also have banbysteps? Otherwise I can't determine my Z offset.

I'll test your config tomorrow evening

**Comment by lscarneiro** [comment]
be sure to test with **both files**, just in case.

I think 400 is too low current for this TMC2208 drives and stepper motor combination, even the "Original Mingda" firmware source code uses at least 800.

I do have baby-stepping enabled but in general I "zero" my Z out using the springs on the bed, so my `M206` is zeroed

**Comment by kyon03** [comment]
nice I just forgotten this mingda printer of mine, but now I will rebuild it will test the config of yours :)

**Pull request merged**
