### PR TITLE
Force unique thermistor ID for SoC temperature sensor

### PR DESCRIPTION
**Pull request by GMagician**

### CODE REVIEW

**Comment by GMagician** [comment]
I think it's better to be explicit to avoid misunderstanding

**Comment by EvilGremlin** [comment]
I think it'd be better as `USE_MCU_TEMP_SENSOR true` or another numeric value for TEMP_SENSOR_BOARD

**Comment by GMagician** [comment]
> I think it'd be better as `USE_MCU_TEMP_SENSOR true` or another numeric value for TEMP_SENSOR_BOARD

Yep, this was a question I posted (to use a on off option) but I got no answer

**Comment by thisiskeithb** [comment]
I get why it was done this way originally, but since there’s no thermistor value to be set, another option is to leave `TEMP_SENSOR_SOC` commented out (with no `0` value) and then users would uncomment it like they do for other features.

**Comment by GMagician** [comment]
> I get why it was done this way originally, but since there’s no thermistor value to be set, another option is to leave `TEMP_SENSOR_SOC` commented out (with no `0` value) and then users would uncomment it like they do for other features.

yep, this may be another solution but it must be checked if all logic properly handle the "only definition" or not. I need to check. Let me know what is the most correctly way of enabling it and I'll go to address it.

**Comment by GMagician** [comment]
> I get why it was done this way originally, but since there’s no thermistor value to be set, another option is to leave `TEMP_SENSOR_SOC` commented out (with no `0` value) and then users would uncomment it like they do for other features.

@thisiskeithb: just define it will break other code that enable logic, I chose to use a unique ID for SoC sensor.

**Pull request merged**
