### PR TITLE
ADD MKS SGen support

### PR DESCRIPTION
**Pull request by timh0r**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Add support for MKS SGen board, based on SBase with LPC1779 and without drivers

### Benefits

Simplify life of SGen owners

### Related Issues

none

### CODE REVIEW

**Comment by thinkyhead** [comment]
SGEN and SBASE differ only slightly. So I have re-done the MKS_SGEN pins file so that it only applies the differences from MKS_SBASE. This approach helps us to see the family relationships between boards.

**Comment by timh0r** [comment]
I really like what you did there ! thanks for reworking it. And sorry for my config file there, i don't get how i mixed them

**Comment by thinkyhead** [comment]
n/p — Making PRs ready is part of the job!

**Comment by Kyosuke33** [comment]
Hello, i don't know if it's here i can ask something or talk about a problem with Marlin 2.0 on my MKS SGen, but i ask and if it's not the good place plz delete or telle me where i can find my answer.

I just build a MKS Sgen with Marlin 2.0 and put it in py printer. My problem is the wiring of the hotend fan. I don't like to directly connect it to the power supply.

So i try to do the same thing as my MKS Gen L, use the E2 port to connect the E1 fan.

I put the pin number on this line "#define E1_AUTO_FAN_PIN P2_6", but when my hotend is 50°, the fan don't start.

On the BigTreeTech SKR 1.3 there is this 

#if HOTENDS == 1
  #define FAN1_PIN         P2_04
#else
  #define HEATER_1_PIN     P2_04

but not on the MKS Sgen Board.

This is a known problem or there is something to do ?

Thank you.

**Pull request merged**
