### PR TITLE
Add options to remove M111 and options to remove M115

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Eke out out a few more bytes for those really short on flash space.
added new configuration_adv,h option DEBUG_LEVEL_GCODE,  disable DEBUG_LEVEL_GCODE to completely remove M111 from Marlin
Saves ~234 bytes of FLASH on a 8 bit systems

added new configuration_adv,h option REPORT_CAPABILITIES_GCODE,  disable REPORT_CAPABILITIES_GCODE to completely remove M115 from Marlin
Saves ~1150 bytes of FLASH on a 8 bit system

### Requirements

The desire to remove gcode M111 or M115

### Benefits

Saves a few bytes

### Configurations

New Configuration_adv.h option.

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/26587 but is still not sufficient

### CODE REVIEW

**Comment by trivalik** [comment]
For me it saved 366 bytes, dump up.

By updating in serial.h:

```
#if ENABLED(DEBUG_LEVEL_GCODE)
  #define DEBUGGING(F) (marlin_debug_flags & (MARLIN_DEBUG_## F))
#else
  #define DEBUGGING(F) false
#endif
```

saves additional 6 bytes.

**Comment by thinkyhead** [comment]
It seems like even with other `M111` capabilities disabled you might still want `M111 S8` which effectively turns off the extruder.

**Comment by trivalik** [comment]
@thinkyhead  is this answer related to my suggested code changes?

**Comment by thinkyhead** [comment]
> is this answer related to my suggested code changes

The full compliment of changes removing `M111` altogether would be even more than you suggested, and I would've followed up with those if `M111` was going to be removed completely. But I opted to keep a minimal `M111` around to retain "dry-run" mode. The "dry run" flag should stick around as long as there is a tool (extruder, laser, spindle…) since it is more part of machine "behavior" than the other flags.

As these two new options are for situations where you're building custom machine, or as "last resort" methods to reduce the build size when you've run out of flash space, we don't need to sweat them too much. But it's good to be thinking about these kinds of slimming options, as the base build tends to increase in size from version to version.

**Pull request merged**
