### PR TITLE
Supporting REPRAP_DISCOUNT_SMART_CONTROLLER

### PR DESCRIPTION
**Pull request by fduraibi**
Adding support for the REPRAP_DISCOUNT_SMART_CONTROLLER LCD module with the Ramps 1.4 Plus board

### Description

The current code only supports the REPRAPWORLD_GRAPHICAL_LCD (LCD12864) and doesn't support the REPRAP_DISCOUNT_SMART_CONTROLLER (LCD2004). 
This PR, which I have tested and currently running on my printer, fixes the issue by assigning the right pins to the board. I have also updated the comment field with the Pin-out of the boards connectors EXP1 and EXP2. 

### Benefits
Fixes the pins for the LCD board `REPRAP_DISCOUNT_SMART_CONTROLLER` when used with the RAMPS 1.4 Plus

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/23501

### Images

This image shows the board pin-out:

LCD_Interface

The LCD pin mapping:

LCD2004_IO_Ports

### CODE REVIEW

**Comment by ellensp** [comment]
Define all the  EXP PINs for your board befor the include and remove the LCD definitions.
Than all lcd definitions in ramps also works for the ramps plus

**Comment by fduraibi** [comment]
@ellensp That is what I did [here](https://github.com/MarlinFirmware/Marlin/issues/23501) but I wasn't sure if would break other setups. But what you are suggesting makes sense.

**Comment by fduraibi** [comment]
@ellensp Done

**Comment by ellensp** [comment]
Looks good.

**Pull request merged**
