### PR TITLE
Update MKS Robin family python script to python3

### PR DESCRIPTION
**Pull request by robbycandra**
Last night my Platform IO update the python to python3.
Therefore i need to update the python script for MKS Robin family.

I dont know if the update have happened in all PlatformIO user or not. But I make PR if there are someone need to compile their code.

### CODE REVIEW

**Comment by tpruvot** [comment]
there was #15523 for that too.. but

**Comment by tpruvot** [comment]
your code doesnt work on python 2... hexdump -C .pio/build/mks_robin/Robin.bin | more


> 0000110  c1 8b 00 08 d9 8b 00 08  49 88 00 08 55 88 00 08  |........I...U...|
> 00000120  e9 7c 00 08 f9 7c 00 08  09 7d 00 08 19 7d 00 08  |.|...|...}...}..|
> 00000130  10 b5 05 4c 23 78 33 b9  04 4b 13 b1 04 48 af f3  |...L#x3..K...H..|
> 00000140  5b 31 36 33 5d 5b 36 31  5d 5b 31 37 32 5d 5b 34  |[163][61][172][4|
> 00000150  36 5d 5b 39 38 5d 5b 39  37 5d 5b 31 37 31 5d 5b  |6][98][97][171][|
> 00000160  34 38 5d 5b 31 34 38 5d  5b 31 34 34 5d 5b 34 35  |48][148][144][45|
> 00000170  5d 5b 32 34 30 5d 5b 32  31 30 5d 5b 31 39 36 5d  |][240][210][196]|
> 00000180  5b 31 35 35 5d 5b 33 30  5d 5b 39 34 5d 5b 32 32  |[155][30][94][22|
> 00000190  34 5d 5b 32 32 34 5d 5b  35 39 5d 5b 36 36 5d 5b  |4][224][59][66][|
>

**Comment by robbycandra** [comment]
@tpruvot , thanks. 
Sorry, I didn't see there is a PR about this.

**Comment by tpruvot** [comment]
Tested here with python 3 to see data at offset 0x0140 : https://travis-ci.org/tpruvot/Marlin/jobs/597403484

**Pull request closed without merging**
