### PR TITLE
X-Axis twist compensation: Calibration Wizard

### PR DESCRIPTION
**Pull request by Giuseppe499**
### Description

I added a feature called X_AXIS_TWIST_COMPENSATION that adds a calibration procedure to compensate for a twist in the X-axis. This procedure is accessible in the menu "Configuration->Advanced Settings->Probe Offsets->X-Twist Wizard". I added this feature to compensate in the firmware for a twisted X-axis as discussed in this issue #22791 and in this pull request #23167. This should also fix this issues #11234, #12349, #15206, #15753, #18591.

### Requirements

This PR requires an automatic bed leveling probe and an LCD to show menus. To test if it works you should also have a twisted X-axis on a 3d printer of your choice (I can suggest you a Tronxy X8 ;) )

### Benefits

I added this feature to compensate in the firmware for a twisted X-axis as discussed in this issue #22791 and in this pull request #23167. This should also fix this issues #11234, #12349, #15206, #15753, #18591.

### Configurations

Just enable X_AXIS_TWIST_COMPENSATION in Configuration_adv.h and AUTO_BED_LEVELING_BILINEAR in Configuration.h. As stated before you should also have an LCD enabled to show the menus and an automatic bed leveling probe.

### Related Issues

#22791, #11234, #12349, #15206, #15753, #18591.

### CODE REVIEW

**Comment by Giuseppe499** [comment]
Hi @Roxy-3D,

I have implemented the calibration procedure as proposed in PR #23167. I think this should answer all your concerns, but let me know if I missed something.

I just have a problem with the current code. I needed a `lerp()` function but couldn't find a macro or other implementation in Marlin, so I added a `lerp()` function in `x_axis_twist_compensation.cpp`. I'm pretty sure this isn't the right place for such a generic function, so where should I put the lerp () function?

**Comment by Roxy-3D** [comment]
Thank You for the Pull Request!!!   I only skimmed it, but I will look at it in more detail over the next few days.   I'll probably want to duplicate some of the functionality you added for the case where the user has enabled UBL.

> I just have a problem with the current code. I needed a lerp() function but couldn't find a macro or other implementation in Marlin, so I added a lerp() function in x_axis_twist_compensation.cpp. I'm pretty sure this isn't the right place for such a generic function, so where should I put the lerp () function?

Probably this is an OK choice for now.   Thinky is pretty good about migrating things to a better file location.   But for the mean time, this is the place where it is used, so it can live here.     The thing that has me scratching my head is we use linear interpolation all over the place inside the various mesh bed leveling schemes.   Probably what we should do is decide where this function should live and comb through all the bed leveling code and change that to make use of this function.   (And probably, this will end up as a macro, or at least as an inline function, but it is too early to make that guess.)  But all that extra bed leveling clean up is independent of this effort.

**Comment by Roxy-3D** [comment]
I don't have a printer available to check things out on.  Mostly, I think it is very important that this is very intuitive and easy for somebody to use.    Unfortunately, I don't have a way to load it and make any suggestions.    So if @thinkyhead doesn't have any objections about the coding style...   I'm OK with the merge.      

I'll expand it to cover the UBL case when I have a printer handy.

**Comment by Giuseppe499** [comment]
Hi @Roxy-3D,

I've made some minor changes in the code: I've changed a line in the code because there was a small mistake, and I changed how the z-offset is converted into a string for the menu.

> So if @thinkyhead doesn't have any objections about the coding style... I'm OK with the merge.

Good, I'll wait for @thinkyhead.

> I'll expand it to cover the UBL case when I have a printer handy.

Nice, so this will be useful for more users too!

**Comment by Roxy-3D** [comment]
Hey!   A quick question here.    Why don't we have a Y twist problem?   The answer probably is the Prusa design has the carriage moving on the X Axis.   And most cartesian printers follow that convention.    But here is the question:  Should we consider a different name for this so it is more generic and still makes sense if the user has a carriage that moves on the Y axis?

And maybe we should have a Configuration_Adv.h setting that says which axis the twist compensation is being performed on.   The default would obviously be X, but it is pretty easy to envision a printer that needs it on the Y axis.

**Comment by Giuseppe499** [comment]
Hi @Roxy-3D ,

> Should we consider a different name for this so it is more generic and still makes sense if the user has a carriage that moves on the Y axis?

I also thought about this when I was writing the code. The reason we don't have a Y-twist problem is, as you said, because almost all cartesian printers have the carriage moving on the X-axis.

I didn't extend this feature for a generic axis because I didn't find an issue mentioning a Y-twist problem.

If you want we can extend this feature for the Y-axis too. This should cover all possible cartesian printers, unless someone for unknown reasons decides to swap the Z-axis with the X-axis 😅

**Comment by Roxy-3D** [comment]
> If you want we can extend this feature for the Y-axis too. This should cover all possible cartesian printers, 

Yes...     I think we should do this.   If it is just a few lines of code, lets do it.   And we probably should add a Configuration_adv.h setting that specifies which axis is being corrected.

**Comment by thinkyhead** [comment]
- The "twist" problem has to do with the probe being separate from the nozzle, so the X gantry is the only one we expect to be affected.
- There are no common setups where the X carriage is mounted directly on a Y gantry (i.e., where X and Y axes are swapped). And a "twisted bed" that throws off the probe orientation is not something to be expected.
- Arbitrary rotation of a model in the Z plane around some XY point is straightforward maths, but adds a lot of overhead for the `sin` and `cos` calls.
- With the nozzle offset in mind, this feature should be disallowed for setups where the nozzle is the probe, since there can be no discrepancies in that case.

**Comment by Giuseppe499** [comment]
> * The "twist" problem has to do with the probe being separate from the nozzle, so the X gantry is the only one we expect to be affected.
> 
> * There are no common setups where the X carriage is mounted directly on a Y gantry (i.e., where X and Y axes are swapped). And a "twisted bed" that throws off the probe orientation is not something to be expected.
> 

You're right. In fact, I don't think that there is someone interested in this feature for the Y-axis. I would extend this feature only if you that are maintaining Marlin tell me that this generalization is needed for the merge.

>* Arbitrary rotation of a model in the Z plane around some XY point is straightforward maths, but adds a lot of overhead for the `sin` and `cos` calls.

I don't understand what this sentence refers to. Could you explain it? If you are referring to the generalization for the Y-axis, I don't need any trigonometric function to do that.

>* With the nozzle offset in mind, this feature should be disallowed for setups where the nozzle is the probe, since there can be no discrepancies in that case.

Yes, you're right. Should we add a check somewhere in the configurations or somewhere else to be sure that this feature is not used when not needed?

**Comment by thinkyhead** [comment]
> I don't need any trigonometric function to do that.

Yeah, I mentioned rotation around the Z axis in case that might be needed to do a "Y twist" — so it's not relevant to this PR. And anyway, even if `sin` / `cos` calculation were needed to do rotation, those calculations would only be needed once.

**Comment by ETE-Design** [comment]
@thinkyhead Is it also made for UBL already, or only Billinear for now?

**Comment by Roxy-3D** [comment]
> Is it also made for UBL already, or only Billinear for now?

It would be best to have the feature support both Bilinear and UBL.

**Comment by ETE-Design** [comment]
@Roxy-3D So it is not done yet?

**Comment by thisiskeithb** [comment]
> So it is not done yet?

This feature is merged and works with Bilinear.

**Comment by ETE-Design** [comment]
@thisiskeithb So it won't work with UBL for now right?

**Comment by thisiskeithb** [comment]
> So it won't work with UBL for now right?

This feature will not be available unless you use Bilinear:

https://github.com/MarlinFirmware/Marlin/blob/e65c12cf96a226019a7456099078ee5cb03f9a49/Marlin/Configuration_adv.h#L1300-L1303

**Comment by gordo3di** [comment]
Thank you guys SO MUCH for this!! I have been pulling my hair out over the years on why the leveling was sometimes off and I never really considered a twist could be the culprit, especially to this degree.

I just tested this on a gMax 2 pro which has an 18"+ wide bed and I purposefully put a severe twist in the axis to test. Before the wizard the right side was almost 3mm higher than the left (when printing). After running the wizard and re bed leveling it's perfect. I noticed if I ran the wizard after bed leveling it didn't apply to the existing mesh.

Next will be working with bigtreetech to implement this on their touch screen. Is there a gcode that works with this wizard or is it just built into marlin? Thanks again.

**Comment by ETE-Design** [comment]
@gordo3di Would be great if this feature also would be made for UBL

**Comment by Giuseppe499** [comment]
>Is there a gcode that works with this wizard or is it just built into marlin?

Hi, at the moment it is just built into marlin. I think that a gcode implementation for this feature could be useful, but I don't know if the maintainers are interested in this. 

> Thank you guys SO MUCH for this!!

I'm really happy that this feature can now solve this issue not only for me but for everyone using Marlin. Thanks to all the people that maintain Marlin and that helped me to add this feature!

**Comment by gordo3di** [comment]
So we ran into a slight bug. It seems if we install new firmware or reset the eeprom and don't run the x axis twist compensation, the bed level matrix is all zeros. This is difficult because most people wouldn't know or remember to run it first. Otherwise it runs great. At first I said "no way out bed is that flat 😅"

My guess is if there is no data stored for the x axis twist compensation, it should assume no twist but instead it's getting an error or something. I've been going over the code and most is above my head but my guess is we need some sort of check to happen in the Marlin/src/feature/bedlevel/abl/x_twist.cpp file where it says:

```
float XATC::spacing, XATC::start;
xatc_points_t XATC::z_values;

```

Anyone else had this issue? We've tried it on several printers with the same problem.

IMG_20220208_171359

**Comment by Giuseppe499** [comment]
Hi @gordo3di,

This issue also happens to me since the [Marlin 2.0.9.3 release](https://github.com/MarlinFirmware/Marlin/releases/tag/2.0.9.3), but when I was adding this feature on the bugfix branch I never noticed it. 

I haven't had time to properly investigate this bug, so I didn't add an issue here on GitHub. If you want, you can add an issue, otherwise I will add one when I can. I think next week I will have time to take a look at this, if I make some progress I will update on the appropriate issue page.

**Comment by gordo3di** [comment]
@Giuseppe499 Thank you for looking into this. So far it's an amazing feature.

I can add this issue and reference this thread if it makes things easier.

**Comment by Giuseppe499** [comment]
Hi @gordo3di,

I've opened a PR (#23743) that should fix the issue that you reported.

When I was investigating the bug that you reported, I found another bug that causes the settings for this feature to not be stored in EEPROM. For this new bug, I have opened this issue #23744. If you have time, could you check if this bug also happens on your printer? I also uploaded a PR (#23745) to fix this issue, so if you also have this bug, you can check if it is fixed by PR #23745.

Thank you in advance

**Comment by gordo3di** [comment]
@Giuseppe499 

Perfect. Not sure if you saw my other message but I kinda of came up with the same solution for the NaN only mine was mainly just to test my theory. I also noticed the value not storing "sometimes" because I could check it with M503 after i uncommented those lines. I see what you did with the EEPROM stuff and I'll test it out right now.

**Comment by gordo3di** [comment]
@Giuseppe499 @thinkyhead 

Ok so far I noticed the x-axis twist compensation values will not automatically save to memory once the wizard is complete. You have to go to "save settings" to save them. I checked this by turning off the printer after the wizard and running M503 and the values were all zero (we use 4 points). Possibly something is missing in the menu_x_twist.cpp file in step 9 since I don't see it save anywhere.

```
//
// Step 9: X Axis Twist Compensation Wizard is finished.
//
void xatc_wizard_done() {
  if (!ui.wait_for_move) {
    xatc.print_points();
    set_bed_leveling_enabled(leveling_was_active);
    SET_SOFT_ENDSTOP_LOOSE(false);
    ui.goto_screen(menu_advanced_settings);
  }
  if (ui.should_draw())
    MenuItem_static::draw(LCD_HEIGHT >= 4, GET_TEXT(MSG_XATC_DONE));
  ui.refresh(LCDVIEW_CALL_REDRAW_NEXT);
}

void xatc_wizard_goto_next_point();
```

Starting a 16" wide print (12 point x 12 point bed leveling).

First test:

I reset the EEPROM and DIDN'T run the x-axis twist wizard, then confirmed all values for the twist compensation were zero. The bed leveling ran fine and the mesh saved just fine (no longer all zeros). This was done on a printer where the x-axis was purposefully twisted so the mesh would purposefully be incorrect. The print came out as expected and the bed level mesh was higher by 1.5mm on one side. Again all expected.

For the 2nd test:

I ran the x axis twist wizard and saved the values using "save settings". Then I leveled the bed and confirmed both the bed level mesh and the x-axis twist values were all saved to memory just fine. Ran the large print and it looks like the x axis compensation is working perfectly and the print is very flat (i'd say within 0.01mm to 0.02mm across 16").

I'd say this fixed our bug!

x axis compensation

**Comment by ETE-Design** [comment]
@Giuseppe499 @gordo3di Could you also make it work with UBL? :-)

**Comment by thisiskeithb** [comment]
@ETE-Design: Please open a feature request instead of asking for UBL support everywhere.

Thank you.

**Comment by gordo3di** [comment]
@Giuseppe499 

I added the save feature. Thing is I'm terrible at figuring out github pull requests but I modified menu_x_twist.cpp to add step 9 to save values to memory. Then step 10 is the final.

```

//
// Step 9: Ask the user if he wants to save the compensation values
//
void xatc_wizard_save_values() {
  //gCreate Added save option
  MenuItem_confirm::select_screen(
      GET_TEXT(MSG_YES), GET_TEXT(MSG_NO)
    , []{
        queue.enqueue_now(F("M500"));
        ui.goto_screen(xatc_wizard_done);
      }
    , xatc_wizard_done
    , GET_TEXT(MSG_XATC_SAVE)
  );
}

//
// Step 8: Ask the user if he wants to update the z-offset of the probe
//

void xatc_wizard_update_z_offset() {  
  MenuItem_confirm::select_screen(
      GET_TEXT(MSG_YES), GET_TEXT(MSG_NO)
    , []{
        probe.offset.z = z_offset;
        ui.goto_screen(xatc_wizard_save_values);
      }
    , xatc_wizard_save_values
    , GET_TEXT(MSG_XATC_UPDATE_Z_OFFSET)
    , ftostr42_52(z_offset), PSTR("?")
  );
}

```

Also modified the language file to add the save message.

```
  LSTR MSG_XATC_UPDATE_Z_OFFSET           = _UxGT("Update Probe Z-Offset to ");
  LSTR MSG_XATC_SAVE                      = _UxGT("Save X-Twist Values ");
```

Let me know your thoughts? I tested it and it seems to work great.

**Comment by tombrazier** [comment]
@Giuseppe499 @Roxy-3D Any reason not to move `PLUS_TERN0(X_AXIS_TWIST_COMPENSATION, xatc.compensation(abl.probePos));` into `probe.probe_at_point()`? Then this feature will work with UBL, LINEAR and 3POINT as well as tramming wizard and more.

It just needs a guard to turn the feature off when the wizard is calling `probe.probe_at_point()`.

#23764 does the same for probe temperature compensation and #23047 explores all the affected features.

**Comment by tombrazier** [comment]
I have submitted at PR #23828. Comments?

@ETE-Design fancy testing it with UBL?

**Comment by ETE-Design** [comment]
@tombrazier Tha't was fast, already merged :-) Thanks for making it possible for UBL also... Another thing, would this also be an easy to add this feature "#23667" to Marlin?

**Comment by tombrazier** [comment]
@ETE-Design Not an area of the code I particularly know, I'm afraid.

**Comment by Feuerstein87** [comment]
> So we ran into a slight bug. It seems if we install new firmware or reset the eeprom and don't run the x axis twist compensation, the bed level matrix is all zeros. This is difficult because most people wouldn't know or remember to run it first. Otherwise it runs great. At first I said "no way out bed is that flat 😅"
> 
> My guess is if there is no data stored for the x axis twist compensation, it should assume no twist but instead it's getting an error or something. I've been going over the code and most is above my head but my guess is we need some sort of check to happen in the Marlin/src/feature/bedlevel/abl/x_twist.cpp file where it says:
> 
> ```
> float XATC::spacing, XATC::start;
> xatc_points_t XATC::z_values;
> ```
> 
> Anyone else had this issue? We've tried it on several printers with the same problem.
> 
> IMG_20220208_171359

how can i use the XATC with a btt TFT 35?

**Pull request merged**
