### PR TITLE
UBL_DELTA fix incomplete array copy and fix undefined DELTA_PROBEABLE_RADIUS

### PR DESCRIPTION
**Pull request by oldmcg**
#6741 auto define DELTA_PROBEABLE_RADIUS for UBL_DELTA if not user-defined 
#6753 fix incorrect array copy using COPY macro with array parameter

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Well...  I think the DELTA_PROBEABLE_RADIUS is taken care of.   I fixed it in the Configuration.h files and you have a fall back if it isn't defined in  Conditionals_post.h

**Comment by oldmcg** [comment]
Thanks -- the correct place to fix it IS in configuration.h, and there are probably some other UBL_DELTA defaults that should be addressed in there as well.

**Comment by Roxy-3D** [comment]
Yeah...  I didn't mess with anything but the DELTA_PROBEABLE_RADIUS.   It was in the wrong place in the sample files...

**Comment by oldmcg** [comment]
DELTA_PROBEABLE_RADIUS is an artifact unrelated to DELTA_UBL, but easier to #define it than to #ifdef around it in M48.

**Comment by oldmcg** [comment]
How do we add a travis build test for UBL_DELTA?

**Comment by Roxy-3D** [comment]
I believe those are in a .yml file.   If you look at last night's Pull Requests...  Scott merged some extra Delta and UBL configurations into the test suite.   I don't remember...  But I think we might want a test that turns on M48 for Delta's with UBL activated.

**Comment by Maglin** [comment]
Does this mean to start over with a fresh Configuration.h?  I'll just do that just to be safe.

**Comment by Roxy-3D** [comment]
> Does this mean to start over with a fresh Configuration.h? I'll just do that just to be safe.

You should use a visual diff program...   And you will be able to see any differences between the new and old files.   At that point, you just move over what ever setting you want to keep...    The only thing that changed was where DELTA_PROBE-ABLE_RADIUS was defined so that M48 would work.

**Comment by Maglin** [comment]
@Roxy-3D I had just done that.  LoL.  I've used notepad++ for years and why I've been doing this through the IDE I can't say.  But It's uploaded and starting again.

**Pull request merged**
