### PR TITLE
Fix OpenBLT encode, expand build envs for clarity

### PR DESCRIPTION
**Pull request by EvilGremlin**
Fixed encrypt stuff broken by #24391 
Added second non-bootloader envs, for clarity sake
Fixed script message
Renamed to encode for clarity because no crypto algorithm involved

### CODE REVIEW

**Comment by thisiskeithb** [comment]
The `Anet_ET4` environment should also be added for these boards so ABM picks them up: 

https://github.com/MarlinFirmware/Marlin/blob/fc287b44da27d435e588f7d83ae61dcb4e929a5b/Marlin/src/pins/pins.h#L680-L683

**Comment by thisiskeithb** [comment]
I’d suggest renaming this to `Anet_ET4_No_Bootloader` so it’s clearer for users.

**Comment by EvilGremlin** [comment]
For autobuild users you mean? Then we need to rename at least half envs :)

**Comment by thisiskeithb** [comment]
> For autobuild users you mean? Then we need to rename at least half envs :)

Sure. But this already has an environment (the default one) that uses OpenBLT. Users might think they need the "plain" one instead since OpenBLT is not common.

**Comment by thisiskeithb** [comment]
Since the Anet environment was renamed, it should have been added to renamed.ini: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/ini/renamed.ini

**Pull request merged**
