### PR TITLE
M119 "open" means "NOT TRIGGERED"

### PR DESCRIPTION
**Pull request by ghost**
LOW PRIO - DONT MERGE - DISCUSSION IN PROGRESS

When using M119, the current status of the endstops will be output:
For example:
```
M119
Reporting endstop status
x_min: open
y_min: open
z_min: TRIGGERED
filament: TRIGGERED
ok P63 B3
```

The following two constructs take care of the possibility that the endstop may or may not be inverting:
```
#define ES_REPORT(S) print_es_state(READ(S##_PIN) != S##_ENDSTOP_INVERTING, PSTR(MSG_##S))
```
and
```
print_es_state(READ(Z_MIN_PROBE_PIN) != Z_MIN_PROBE_ENDSTOP_INVERTING, PSTR(MSG_Z_PROBE));
```
This means that the output "TRIGGERED" actually means "pin is high" or "pin is low" depending on the wiring and correct setup of the ...ENDSTOP_INVERTING defines.

Ouput of "open" means "pin is low" or "pin is high", once again depending on the same as stated before.

But "open" is a misnomer and confuses. See #14346

So this kind of output would be better:

```
M119
Reporting endstop status
x_min: NOT TRIGGERED
y_min: NOT TRIGGERED
z_min: TRIGGERED
filament: TRIGGERED
ok P63 B3
```

### CODE REVIEW

**Comment by AnHardt** [comment]
We could also use 0/1, H/L, true/false, On/Off, open/closed triggered/ not triggered or any pair like that. That's all the same.
But can we find words describing the difference between the effective logical state of the detector (what we actually try to display), the level the pin has and the physical state of the switch/transistor in the detector, what all can be different?

touched / untouched ? (in German - berührt / unberührt)

Suggestions please!

**Comment by ghost** [comment]
Since we give the opportunity to define an inversion that is done after reading the pin:

We should either use M119 to **faithfully report the original TRUE** value of the pin as 0/1 or LOW/HIGH 

or

We should use M119 to **report our interpretation of the users intent, taking the inversion into account** as TRIGGER and NOT TRIGGER.

but we should not mix the two, like with "open/TRIGGERED"

**Comment by ghost** [comment]
Of course, something like this is maybe more useful:

```
M119
Reporting endstop status
Pin       Level  Invert   Meaning
x_min:      1      Y      NOT TRIGGERED
y_min:      0      N      NOT TRIGGERED
z_min:      1      N      BLTOUCH-STOWED
filament:   1      N      PRESENT
```
How many code bytes are we prepared to give to this? 32-bit machines no sweat, but AVR?

**Comment by InsanityAutomation** [comment]
For filament I completely agree with changing it to present / not present. Ive had to explain that to many users. Bltouch swapping text is a question.

**Comment by ghost** [comment]
Just wanted to reference this one to check up on also: #14396

**Comment by ghost** [comment]
Looks like this now:
```
Reporting endstop status
ENDSTOP PIN INV  MEANING
X_MIN  : 0 / N = NOT TRIGGERED
Y_MIN  : 1 / Y = NOT TRIGGERED
Z_PROBE: 1 / N = PIN UP
RUNOUT : 1 / Y = NOT TRIGGERED
RUNOUT2: 1 / Y = NOT TRIGGERED
RUNOUT3: 1 / Y = NOT TRIGGERED
```

**Comment by AnHardt** [comment]
> Z_PROBE: 1 / N = PIN UP

For most probes not appliable.

**Comment by ghost** [comment]
@AnHardt 
```
  #if HAS_Z_MIN
    #if ENABLED(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN)
      #if ENABLED(BLTOUCH)
        print_es_state(READ(Z_MIN_PIN), Z_MIN_PROBE_ENDSTOP_INVERTING, PSTR(MSG_ENDSTOP_M1_BLTOUCH), PSTR(MSG_ENDSTOP_M0_BLTOUCH), PSTR(MSG_Z_PROBE));
      #else
        print_es_state(READ(Z_MIN_PIN), Z_MIN_PROBE_ENDSTOP_INVERTING, PSTR(MSG_ENDSTOP_HIT), PSTR(MSG_ENDSTOP_NOHIT), PSTR(MSG_Z_PROBE));
      #endif
    #else
      ES_REPORT(Z_MIN);
```
But for BLTOUCH, it is.

**Comment by ghost** [comment]
Code still needs to be cleaned up and some more double checking, of course, because I've only got it working on LPC1768 and my config right now. Does not compile yet on AVR, for example.

**Comment by AnHardt** [comment]
Oh!
'HIT / NOT HIT' is nice. This pair pretty well meets my intentions when i suggested 'touched / untouched', just shorter, better, even more pregnant. (German translation would be the same :-) )

**Comment by ghost** [comment]
Newest version looks like this:
```
M119
Reporting endstop status
ENDSTOP PIN INV  MEANING
X_MIN  : 0 / N = NOT TRIGGERED
Y_MIN  : 1 / Y = NOT TRIGGERED
Z_PROBE: 1 / N = PIN UP
RUNOUT : 1 / Y = NO FILAMENT
ok P63 B3
M119
Reporting endstop status
ENDSTOP PIN INV  MEANING
X_MIN  : 0 / N = NOT TRIGGERED
Y_MIN  : 1 / Y = NOT TRIGGERED
Z_PROBE: 1 / N = PIN UP
RUNOUT : 0 / Y = FILAMENT OK
```

**Comment by thinkyhead** [comment]
If you want to make a fancy report option, great. But you can't change the default output.

**Comment by ghost** [comment]
Argh, of course.
Well, I don't see any huge discussion here or enthusiasm for this. It was only #14346 that prompted this. I guess most of us, myself included, have no problems configuring our endstops and interpreting the output of the current M119. In one of the opening comments I mentioned doubts about spending code bytes on suchlike. If there is no disagreement, I will just close it.

**Comment by thinkyhead** [comment]
I've been meaning to make an LCD menu item that will show the endstop states in real-time. It would be useful for setup and testing. For now, we just use `M43` for that.

**Pull request closed without merging**
