### PR TITLE
[2.0.x] Add LCD_SOFTWARE_SPI option

### PR DESCRIPTION
**Pull request by WojciechBednarski**
Add generalized Software SPI support for LCDs.
Initially implement for `MKS_MINI_12864` and `MINIPANEL`.

Also:
- Add `MINIPANEL` pins for DUE3DOM boards

### CODE REVIEW

**Comment by WojciechBednarski** [comment]
Sorry thinkyhead, now I see that my editor messed up few indents. I'm new to git and I'm not sure how I can change it without making new pull-request.

**Comment by fiveangle** [comment]
So I'm confused... I too thought that `MINIPANEL `define was used when installing the `MKS_MINI_12864 `(and it does seem that way based on my experience).   However, recently the `MKS_MINI_12864 `panel was also introduced.  Is there a difference between the two ?

**Comment by WojciechBednarski** [comment]
@fiveangle Well, I'm not sure about the differences. To be honest the only mention about that panel I can find is here: http://reprap.org/wiki/Mini_panel ,but there are no pinouts or anything. Main difference I can see is lack of SD card reader. 

MKS mini 12864 I'm using for some time now together with due3dom mini board, and it work's with pinout provided with SW-SPI, that's why I pushed that commit, so I don't need to change it manually every time I update firmware:) Unfortunately there are big problems with 32 bit boards and having this display and card reader together at HW-SPI line.

**Comment by fiveangle** [comment]
Have you read the same page on the MKS_MINI_12864:
http://reprap.org/wiki/MKS_MINI_12864

> Marlin Configuration
> 
> The following assumes:
> a) A mega2560 CPU
> b) RAMPS 1.4 shield
> c) The MKS MINI 12864 LCD controller is plugged into the Smart Adapter (the card used to 
>    interface to the RepRapDiscount Full Graphic Smart Controller).
> 1.In Configuration.h enable `MINIPANEL`.
> 2.In pins_RAMPS.h use these defines.
> ...

In short, they should be the same so adding another config for the same HW design seems a bit gratuitous and ripe for even more confusion.  I agree that MINIPANEL seems to not be readily available any longer, but that doesn't seem to be a very compelling reason to change the config name when everyone is already used to the old MINIPANEL moniker.

It's just complicating/confusing matters, since those pin files that support MINIPANEL now either have to replicate the config to handle the MKS_MINI_12864 config as well (beyond what you are doing for Due).  If someone comes along and wants to implement the MKS variant, they will not think the MINIPANEL config in their pins* will work and it will cause more not-very-useful churn.

I mentioned this when your original config for MKS_MINI_12864 was submitted but it was missed or ignored (which can happen).  But I think the differences should be either identified and called out, or the MKS_MINI_1286 be reverted to just use the MINIPANEL config as it had been.

-=dave

**Comment by WojciechBednarski** [comment]
I totally agree with you @fiveangle , for what it's worth I think that changing comment for minipanel to also include MKS MINI12864 in the description would be sufficient. But I didn't want to remove the part, which maybe got there for a reason by somebody much more important here than me:) Anyway I think that commits to pinouts for due3dom(/mini) can be merged, whatever whoever want's to do with `MKS_MINI_12864`

**Comment by thinkyhead** [comment]
The question is, does `MINIPANEL` alone support this SW SPI feature, or is it something that would only be available on MKS MINI12864? If MKS MINI12864 is overall identical to `MINIPANEL` then I would agree eliminating `MKS_MINI_12864` and adding a comment to `MINIPANEL` would be one acceptable way to go.

**Comment by WojciechBednarski** [comment]
@thinkyhead I can't tell for sure, as I don't have that depracated mini display (and tbh I don't see if it is anywhere available), but it has the same LCD driver. 
Even more, I think that for that `MINIPANEL` is is even easier to make a SW-SPI connection, because it lacks the SD card, so no soldering would be required. The main point of making `MKS MINI12864` on SW-SPI is to separate card reader HW-SPI from display SPI, and here we have nothing to separate.

//EDIT: The only actual issue can be the pinout of standard pins (encoder, buzzer, buttons). I can't find what is the pinout for `MINIPANEL` apart from that it uses AUX2+3 at RAMPS board...

**Comment by fiveangle** [comment]
@GarrethX - I did a quick look through my notes when I was implementing this the MKS panel early last year (with Bob's great help) and realise why `MINIPANEL` has been used for it: it's because all the sellers of it reference a doc that explains how to modify Marlin 1.0 to add support, by tweaking the existing MINIPANEL definition.  Ideally, the MKS_MINI_12864 define would have been added that included the SD card stuff (which the MINIPANEL i guess doesn't have) and then included the MINIPANEL defines are part of it, so that any updates to MINIPANEL would roll up into MKS_MINI_128674.  But alas, that ship has sailed.

Since it's a bit of a mess already, would it make sense to rip out all the `MKS_MINI_12864` stuff and incorporate it into `MINIPANEL` (if the HW SPI feature for the MKS version can exist alongside the standard MINIPANEL config without affecting it, which it sounds like it should be able to do) ?

In bugfix 2.0 these are the boards that currently have MINIPANEL configs:

```
Searching 630 files for "MINIPANEL" (regex)

C:\dev\git\Marlin\Marlin\src\inc\Conditionals_LCD.h:
  144:   #define MINIPANEL
  148: #if ENABLED(MAKRPANEL) || ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\inc\SanityCheck.h:
 1376:   #if ENABLED(MINIPANEL) && DISABLED(MKS_MINI_12864)

C:\dev\git\Marlin\Marlin\src\lcd\ultralcd_impl_DOGM.h:
  214: #elif ENABLED(MINIPANEL)
  215:   // The MINIPanel display
  357:   #if DISABLED(MINIPANEL) // setContrast not working for Mini Panel

C:\dev\git\Marlin\Marlin\src\pins\pins_BEAST.h:
  228:     #elif ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_CHITU3D.h:
  227:     #elif ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_MEGACONTROLLER.h:
  135: #if ENABLED(MINIPANEL)
  155: #endif // MINIPANEL

C:\dev\git\Marlin\Marlin\src\pins\pins_MELZI_CREALITY.h:
   62: #if ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_PRINTRBOARD_REVF.h:
  224:   #elif ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_RAMPS.h:
  270:       && (ENABLED(PANEL_ONE) || ENABLED(VIKI2) || ENABLED(miniVIKI) || ENABLED(MINIPANEL) || ENABLED(REPRAPWORLD_KEYPAD)))  // try to use AUX 2
  284:       && (ENABLED(PANEL_ONE) || ENABLED(VIKI2) || ENABLED(miniVIKI) || ENABLED(MINIPANEL) || ENABLED(REPRAPWORLD_KEYPAD)))  // try to use AUX 2
  484:     #elif ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_RAMPS_DUO.h:
   98:     #elif ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_RAMPS_RE_ARM.h:
  297:   #if ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_STM32F1R.h:
  221:     #elif ENABLED(MINIPANEL)

C:\dev\git\Marlin\Marlin\src\pins\pins_STM3R_MINI.h:
  231:     #elif ENABLED(MINIPANEL)

19 matches across 13 files
```

A more disruptive solution would be to change name of MINIPANEL to something like MINIPANEL_CLASSIC then put your MKS_MINI_12864 wrapper stuff around that with the SPI fixes and anything else required, then add a SantityCheck.h check that warns "MINIPANEL has been replaced by MINIPANEL_CLASSIC (for classic MINIPANEL that does not included SD reader) and MKS_MINI_12864.  Please update your LCD based on which panel you have."

Or something like that.   Neither is ideal so I don't have strong opinion either way (although I'm sure others must ;)

-=dave

**Comment by WojciechBednarski** [comment]
@fiveangle 

I took a look at pins for rumba as thats most popular and I guess that pinouts for it _should_ be tested:

```
     #elif ENABLED(MKS_MINI_12864)  // Added in Marlin 1.1.6

      #define DOGLCD_A0         27
      #define DOGLCD_CS         25

      // GLCD features
      //#define LCD_CONTRAST   190
      // Uncomment screen orientation
      //#define LCD_SCREEN_ROT_90
      //#define LCD_SCREEN_ROT_180
      //#define LCD_SCREEN_ROT_270

      #define BEEPER_PIN        37
      // not connected to a pin
      #define LCD_BACKLIGHT_PIN 65 // backlight LED on A11/D65

      #define BTN_EN1           31
      #define BTN_EN2           33
      #define BTN_ENC           35

      #define SDSS              53
      #define SD_DETECT_PIN     49
      #define KILL_PIN          64

    #elif ENABLED(MINIPANEL)

      #define BEEPER_PIN        42
      // not connected to a pin
      #define LCD_BACKLIGHT_PIN 65 // backlight LED on A11/D65

      #define DOGLCD_A0         44
      #define DOGLCD_CS         66

      // GLCD features
      //#define LCD_CONTRAST   190
      // Uncomment screen orientation
      //#define LCD_SCREEN_ROT_90
      //#define LCD_SCREEN_ROT_180
      //#define LCD_SCREEN_ROT_270

      #define BTN_EN1           40
      #define BTN_EN2           63
      #define BTN_ENC           59

      #define SDSS              53
      #define SD_DETECT_PIN     49
      #define KILL_PIN          64
```

So they are completely different, that's why I guess we've got two separate defines in the config. Judging by this, I think that keeping both defines makes some sense.

But in this case this conditional make less sense:
```
#elif ENABLED(MKS_MINI_12864)
  #define MINIPANEL
```
Because if we use different pinouts at (let me risk that statement) on the most popular reprap mainboard, then why complicate things up by conditionaling them together? 

I tend to think that since these displays are different we could modify `ultralcd_impl_DOGM.h` to something like that:
```
#elif (ENABLED(MINIPANEL) || ENABLED(MKS_MINI_12864))
  // The MINIPanel display
    //U8GLIB_MINI12864 u8g(DOGLCD_CS, DOGLCD_A0);  // 8 stripes
	#ifdef MINI_12864_SW_SPI
		U8GLIB_MINI12864_2X u8g(DOGLCD_SCK,DOGLCD_MOSI,DOGLCD_CS, DOGLCD_A0,U8G_PIN_NONE);
	#else
		U8GLIB_MINI12864_2X u8g(DOGLCD_CS, DOGLCD_A0); // 4 stripes
	#endif
```
and remove that rather ugly conditional which keeps both displays enabled.

Also later, when the "classic" minipanel gets so deprecated, that it will be safe to remove, then there will be slightly less changes to be made.

**Comment by fiveangle** [comment]
I doubt any panel will be removed: ever 😝 

Regarding what to do, I think you and everyone else who looks at these suffer from the same folly: assuming that whatever someone did before was correct ;)  The last submission this I think I remember the person tried to claim that the `MKS_MINI_12864` did not have the EXP headers simply swapped 180 deg and submitted a PR with all the pins remapped 180-deg, until they realized they could not remap VCC and GND, so closed their PR  😁 

There is a lot of cruft around these panels (MINI, 12964, OLED).  How best to deal with it is a factor of how much effort one wants to put into mapping the rabbit hole then re-publishing the map :)
I was trying to squash all the frustration and confusion that *continually* comes up from people trying to use these MKS panels.

But I think you're right that completely separating it from MINIPANEL and just replicating all the necessary parts is best.  At least any existing users will still have their config, and new users may get SD support, at the small expense of minor level of duplicated code in Marlin.

As a test, let me know when you feel you have your PR complete and I will test my Printrboard RevF by switching from MINIPANEL to MKS_MINI_12864 and confirming it works.  The external SD never did work, so with your final PR it theoretically should ?

-=dvae

**Comment by WojciechBednarski** [comment]
Ok, please take a look if that is satisfying, I made some changes as we spoke.

I'm honestly suprised that you had problems with that display on 8bit CPU. From my tests I had no problems when I was playing with some old rumba board. 
From my perspective:
8bit boards -> u8glib1 -> HW and SW spi works
32bit boards -> u8glib1 -> only SW spi works
8/32bit boards -> u8glib2 -> HW and SW spi works

I think that with your board the pinouts has to be revised... I looked at the schematics of Printrboard and I'm a little bit confused about the headers, because on EXP1 and EXP2 you don't have HW-SPI pins. So if you connected MKS MINI to EXP1 and EXP2, you had to use SW-SPI, but is SD-card working on SW-SPI in Marlin? That I didn't test and quite honestly I have no possibility to do that...

Take a look below at my modification to have it running on due3dom mini and SW-SPI, maybe this will give some insight (sorry for hand drawing:) ):

mini12864-photo
mini12864-schematic

**Comment by WojciechBednarski** [comment]
I didn't notice that Mr. Travis didn't like me, can I do something about it? Never used it before.

**Comment by AnHardt** [comment]
Just a temporary internal Travis problem. Rebuild worked.

**Comment by fiveangle** [comment]
Will try to test soon.

**Comment by thinkyhead** [comment]
Feeling mergeable yet?

**Comment by fiveangle** [comment]
I ran into other compile issues preventing me getting to this.  I don't want to hold things up so I can keep testing this on my todo list (when compile is no longer broken) and circle back in case there is a problem.  Whatever works for you guys.  It would be nice to have this cleaned up for all.  It was a headache when I first had to unwind how to get this panel to work.

**Comment by WojciechBednarski** [comment]
Changes I've made are not running deep inside the code, I guess it's just a minor cleanup, which should not affect legacy mini 12864 boards, but adds another possibility for a little bit more advanced people who are not afraid of soldering iron and need such change for 32bit boards:) 
From this commit it will be possible to add proper pinouts for mks_mini12864 for various boards providing, that other users will get a feedback without breaking legacy mini12864. 

I'm glad you guys have put your time into this, because I know you have much more important stuff to work on. Thank you!

**Comment by thinkyhead** [comment]
I'll aim to get this merged tonight. I'll post if I have any questions.

**Comment by thinkyhead** [comment]
I'm beginning to think it might be good (better?) to have a general `LCD_SOFTWARE_SPI` option that could apply to more than one type of LCD. I see we also have `TMC_USE_SW_SPI` for Trinamic stepper drivers. Would the SW SPI pins be the same for both the LCD and the TMC drivers?

**Comment by WojciechBednarski** [comment]
@thinkyhead Well, theoretically it can be, but with SW SPI it doesn't need to be. 
However my concern would be that you'd have to assure correct Chip Select synchronization, because obviously we can't talk to two devices at the same time.
`LCD_SOFTWARE_SPI` sounds good, and it could be used with all other SPI displays.

**Comment by thinkyhead** [comment]
> Chip Select synchronization

I don't think that's a huge concern with our single-threaded architecture. We pull the CS line at the start of sending data to any device, and there should be nothing at this time (such as an interrupt) that can come along to alter the CS line in the middle of communication. When we integrate TMC5130 support –which will be using SPI for all motor control– we can ensure that it has its own separate MOSI/MISO/CS.

**Comment by thinkyhead** [comment]
> `LCD_SOFTWARE_SPI` sounds good, and it could be used with all other SPI displays.

I've renamed the option to `LCD_SOFTWARE_SPI` and placed the option in `Configuration_adv.h` in the LCD section. For now it sanity checks for `MINIPANEL` or `MKS_MINI_12864`. That can be changed when the option is implemented for more displays.

**Comment by Bob-the-Kuhn** [comment]
I'm really sorry for coming so late to this discussion.

I get really nervous when I see mention of another LCD software SPI.

I had forgotten that the MKS mini12864 uses one SPI for both the LCD & the SD card.

The VIKI2 style ST7565 LCDs also share a single SPI.  On that one I've just modified the 1.1.x driver to use the SD card's hardware SPI.  This is possible because the ST7565 can run at the SD card's max rate of 8 MHz.  The 2.0.x branch also uses a hardware SPI driver for the VIKI2 display.

The only other shared SPI I know of is the ST7920 based RepRap Full Graphic on the RE_ARM card.  This one has to use a software SPI because the ST7920 can't run at the SD card rates.

Please give me a day or two before merging so I can investigate this further. 

To be honest I'm not understanding the reason for this PR.  What's the current Marlin doing or not doing that is causing problems?

I'm not implying that this isn't a good solution.  I'm just saying I don't know what the value add is for this PR.

The other thing is we had a change to the 2.0.x SPI software a week or so ago.  It mostly affects the LP1768 platform but it also touched all the other platforms.

**Comment by thinkyhead** [comment]
> What's the current Marlin doing or not doing that is causing problems?

I can't say whether this PR is meant to address a problem, but maybe just a hole. With this PR (extended a bit more) any LCD can theoretically be moved to a separate SPI bus.

The current condition being used to choose between HW and SW is whether `LCD_SOFTWARE_SPI` is enabled, but perhaps it should use `defined(DOGLCD_SCK) && defined(DOGLCD_MOSI)` instead as a more general way of choosing which U8G initializer to apply.

**Comment by WojciechBednarski** [comment]
@Bob-the-Kuhn 
> What's the current Marlin doing or not doing that is causing problems?

For MKS mini12864 and arduino due and u8glib v1 and HW SPI this display is not working, and PR addresses that issue (with necessary hardware modification mentioned few posts earlier). For any other combination it works (8 bit boards AND/OR u8glib2 AND/OR SW SPI), but at SW SPI I had card reader problems.

Unfortunately it's out of me league to fix or at least determine problem with u8glib v1 and arduino due and HW SPI. But PR is my workaround which I'm using on daily basis successfully. 

Moreover this PR addresses a small issue that MKS mini12864 and legacy mini12864 are using different pinouts, so I suggested separating them in pins files.

**Comment by Bob-the-Kuhn** [comment]
> mini12864 and arduino due

I have a Due and a mini12864.  I'll see what I can come up with.

**Comment by Bob-the-Kuhn** [comment]
The Due hardware SPI and the MINIPANEL hard2ware SPI are not getting along.

As a short term work around put them both into software SPI mode by doing the following.

In **ultralcd_impl_DOGM.h** after **#elif ENABLED(MINIPANEL)** 
1. comment out **U8GLIB_MINI12864_2X u8g(DOGLCD_CS, DOGLCD_A0); // 4 stripes** 
2. add **U8GLIB_MINI12864_2X u8g(SCK_PIN, MOSI_PIN, DOGLCD_CS, DOGLCD_A0); // 4 stripes SW-SPI**  

In **HAL_spi_Due.cpp**
1. comment out **#if ENABLED(SOFTWARE_SPI)**
2. add **#if 1**

**Comment by Bob-the-Kuhn** [comment]
@ejtagle - need to get your ideas on this one.

The ST7565 (VIKI2) & MKS MINI12864 displays all use the same SPI for the LCD & SD card sections.

As far as I can tell the code in **HAL_spi_Due.cpp** isn't easily modified to accommodate these displays.

The easiest way is to use the Due soft SPI for the SD card and the U8G soft SPI driver for the LCD.  But that apparently means we loose DAC and EEPROM support for the ALLIGATOR mother board.

I've done some playing with the hardware SPIs.  The good news is that these LCDs can run at the SD card speeds which might make initialization simpler.  The bad news is the  **HAL_spi_Due.cpp** code sets up the SPI controller in a mode that isn't compatible with the U8G hardware code.  On power up the LCD splash screen comes up normally and then the SD card is read and then five seconds later it re-boots.

We could replace the **HAL_spi_Due.cpp** hardware code with code similar to the U8G hardware code but then we'd be loosing those functions again.

**Comment by WojciechBednarski** [comment]
@Bob-the-Kuhn now you see the reason of the PR;)

If you see my post from 3 Jan, there is the hardware modification I made to this display. With this, and this PR I've got a working setup consisting of:
Arduino Due3dom Mini + Arduino Due + HW SPI card reader + EEPROM + SW SPI Display. 

Sometimes I get artifacts on the display, halves are swapped, but it's not affecting the print itself (I'm not sure if thats software or hardware fault).

**Comment by Bob-the-Kuhn** [comment]
@GarrethX , @ejtagle  - please take a look at the attached file.

[HAL_spi_Due.zip](https://github.com/MarlinFirmware/Marlin/files/1746612/HAL_spi_Due.zip)

This file preserves the Alligator specific SPI routines and adds U8G compatible routines. The soft SPI changes removed the SDSS control (Marlin usually expects the calling routine to control the SPI select).  The hard SPI changes was the addition of U8G style code.

I've tested it with a VIKI2 display.  The soft SPI works perfectly but the hard SPI VIKI U8G driver appears to have a problem with the splash screen..

I still need to verify the hard SPI baud rates.

My Platformio has crashed so I need to re-install it & Atom.  It'll be bed time before it's running again so I'll finish working on it tomorrow.

**Comment by WojciechBednarski** [comment]
Your file makes changes to HW spi or SW spi or both? Because I'm lost. 
I loaded your file and SW spi still works, I have no easy way to test HW Spi as only have the display modified as mentioned above. If I would like to try that with lower or faster SW SPI speed where I should modify your file?

**Comment by Bob-the-Kuhn** [comment]
LCD software SPI speed is set in the U8G com driver.  It's the one that actually drives SCK & MOSI.  It's running at about 2.5MHz.

SD card speed is set in Configuration.h.  It starts out slow (about 380KHz) and then jumps to the speed set by SPI_SPEED if the SD card can support it.  SPI_SPEED defaults to about 8 MHz.  SPI_HALF_SPEED gives you about 4MHZ, ...

The DUE code uses the hardware SPI if SDSS is the usual definition.

In your case the SD card is using the hardware SPI.  I expect that you're using something like `U8GLIB_64128N_2X_HAL u8g(53 /* DOGLCD_SCK */, 51 /* DOGLCD_MOSI */, DOGLCD_CS, DOGLCD_A0);` which means the U8G soft SPI is driving the four lines.

I've actually modified both DUE SPIs.  

The current DUE SPIs are channel oriented and aimed at the Alligator motherboard.  For the software SPI I kept it intact and added a conditional compile section that has U8G compatible calls.  All that amounted to was removing the slave select commands.  For the hardware SPI I actually added a second hardware SPI.  Conditional compiles guarantee that only one is ever used.  The new section uses the U8G com driver code.

**Comment by Bob-the-Kuhn** [comment]
@GarrethX , @ejtagle - I just realized that my changes basically throws away the USB mass storage capability.

I need to do a total re-think of how to accomplish this.  I expect that I'll add DUE specific U8G com drivers and add a channel for the LCD.  I'm 99% sure this'll work for the hardware SPI.  I'm not sure what to do for the software SPI.

**Comment by ejtagle** [comment]
@Bob-the-Kuhn : The software SPI routines (the assembler ones) do not move the SS pin at all. So, the only thing you should keep in mind would be to make sure spiBegin() works for the SD card. If it does, then USB mass storage should also work.
I suggest to use something along the lines:
void spiBeginEx(int channel)
Where you set the channel to use (the SS pin to use, either SDCard, LCD or whatever SPI device to address)

**Comment by Bob-the-Kuhn** [comment]
What I'd like to do is remove the SS pin control by both the hardware & software SPIs.  That'll allow the calling routine to control the SS pin.

The problem with having the hardware SPI control the SS pin is that we don't know ahead of time what the SS pin will be for the LCD.

How do you set up a channel to not control the SS pin?

**Comment by ejtagle** [comment]
In the software SPI implementation, just remove the WRITE(SS_PIN,,,, calls.
On the hardware SPI side, it is also easy: Section 32.8.2 of SAM3X datasheet contains the definition of the SPI_MR register.  The PCS field (bits 16 to 19), the PS field (bit 1) and the PCSDEC (bit2) are what we need to change.
According to the flow diagram of page 32.7.3.2, if you set PS=0, then the PCS fields reflect the state of the lines SS0-SS3 when a byte is transmitted. The PCS field can be changed on the fly, so there is no need to know the SS pin to use at configuration time. All what you need to do is to make sure the interface is Idle before changing those fields (SPI_SR.TXEMPTY =1). You can change those fields just before sending the byte to transfer.
I would do:
PCSDEC = 1 (so SAM3X does not filter combinations of PCS fields as invalid, 
PCS: The line or lines to set to 0 when sending info
PS=0 so there is no translation and PCS is directly output to the 4 chipselects

If want you want is to repurpose SS pins, then you can easily do so by programming the pin multiplexer to a different peripheral. Figures 31.3, and table 32-2

**Comment by Bob-the-Kuhn** [comment]
@GarrethX , @ejtagle - Here's a rough working copy that allows the VIKI2 & SD card to use the hardware SPI on Due.  

Please see if it works for you.

I'm particularly interested in knowing if it breaks the USB mass storage function.

https://www.dropbox.com/s/46oosbu53wq7kf7/Marlin-Bob-2.zip?dl=0

**Comment by Bob-the-Kuhn** [comment]
I'll add MKS MINI12864 support later tonight.

**Comment by Bob-the-Kuhn** [comment]
This is the MKS MINI12864 version.

https://www.dropbox.com/s/s1ixhbq5t6o67cu/Marlin-Bob-2_MKS_MINI12864.zip?dl=0

**Comment by WojciechBednarski** [comment]
As for my initial testing with PR #9961 HW spi can work, so this PR could be only partially implemented. We need further testing of HW SPI, however I still opt in for splitting legacy MINIPANEL from MINI12864, because pinouts for them are different as I shown few posts above, and I would still like to see updated pins file for those panels in due3dom/due3dom mini files.

**Comment by ejtagle** [comment]
I assume that pull #9961 made this pull request obsolete. But, just for reference, there is nothing preventing the HW SPI to be reprogrammed on the fly. It could even be possible to switch SPI speeds on the fly, and it will work with no issues at all if done with the SPI controller is idle (SPI_SR.TXEMPTY =1) then you are free to reprogram the SPI clock polarity, edge, and speed.

**Comment by WojciechBednarski** [comment]
> I assume that pull #9961 made this pull request obsolete.

I agree:) Now HW Spi works like a charm, no need to bother with SW SPI for now:)

**Pull request closed without merging**
