### PR TITLE
Update and change Japanese translation

### PR DESCRIPTION
**Pull request by ghost**
Update and change Japanese translation

This is completely retaken version of the previous my PR #3550.

・Follow-up the PR #3411(Update Readme.fonts about Kana), Remove "who really..." strings. I had forgotten it.
・Add readable translated strings in comment
・Add Japanese translation.

```
  MSG_LCD_ENDSTOPS "エンドストップ"
```

  (utf8 version only. Because non-utf8 version ("ｴﾝﾄﾞｽﾄｯﾌﾟ") over 8 characters)

・Change translation.

```
  MSG_ACC "カソクド mm/s^2" -> "カソクド mm/s2"
  MSG_ACC "\xb6\xbf\xb8\xc4\xde mm/s^2" ("ｶｿｸﾄﾞ mm/s^2") -> "\xb6\xbf\xb8\xc4\xde mm/s2" ("ｶｿｸﾄﾞ mm/s2")
```

### CODE REVIEW

**Comment by jbrazio** [comment]
ありがとうございました

**Comment by Blue-Marlin** [comment]
Please don't touch German. 
You can not know about what we accepted as a "technical term" and what we forgot to translate. 
Since the last offensive to add some therms at least 5 native Germans looked into this file. We did not agree in all points, but non of us has seen any need for further changes, at least not enough to make an other PR. 

Please don't try to patronise the natives.

**Comment by ghost** [comment]
@Blue-Marlin

> You can not know what we accepted as a "technical term" and what we forgot to translate. 

I concerned it before retaking, but I followed [the shown rule](https://github.com/MarlinFirmware/Marlin/pull/3550#discussion_r60060141).
I apologize for bother you.

@jbrazio
I think  rule(process?) of translation needs improvement.
Anyway, I revert all of changes except Japanese, thereafter I reopen this PR.

**Comment by Blue-Marlin** [comment]
The rule as it self seems to be ok, but you can't reverse it.
If you don't follow the rule, things like https://github.com/MarlinFirmware/Marlin/pull/3560/files happen - you have to change 20+ files for an, in almost all, languages untranslated string, just to change the case.

**Comment by jbrazio** [comment]
@Blue-Marlin I asked @esenapaj to remove all the English directives from the language files, that's the reason why you saw edits to the DE lang file. This has some reasoning behind, why should a DE lang file be overriding the a default EN directive with exactly the same phrase ?

@esenapaj you reverted the edits to all lang files but do you still keep that in any local branch ?

**Comment by thinkyhead** [comment]
I'm sure we could update that language-checking script to also flag strings in other language files that match the `language_en.h` strings. I was just messing with a technique recently to find all the items in one list that coincide with another list. The key command to use is `comm -23`…

``` bash
comm -23 \
  <(git branch --all | sed 's/^[\* ] //' | grep origin/ | grep -v "\->" | awk '{ print $1; }' | sed 's/remotes\/origin\///') \
  <(git branch --all | sed 's/^[\* ] //' | grep -v remotes/ | awk '{ print $1; }') \
  | awk '{ print "git branch -d -r origin/" $1; }'
```

**Comment by jbrazio** [comment]
We discussed that in the past Scott, but actually I would prefer not to duplicate `#defines` that don't really need to be duplicated. If in all languages the translation for `MSG_PID_P` is "PID-P" why should we have one `#define MSG_PID_P` per language file ? We just need to set it on the default one (EN) as all the other ones will inherit it.

I was unaware of `comm` ! This makes my script so much easier..

**Comment by thinkyhead** [comment]
> actually I would prefer not to duplicate `#defines` that don't really need to be duplicated

I have a thing for keeping parallelism between the language files. I would like it if all lines were in the same order too. This way everyone can look at their own language file and see the complete set — even if they happen to be the same as English. Then some lazy programmer like me can switch tabs back and forth between language files in his text editor and watch the lines dance, but not up and down...

**Pull request merged**
