### PR TITLE
Add steps_per_unit for multiple extruders

### PR DESCRIPTION
**Pull request by MagoKimbra**
Step, Feedrate and accelerate for each Extruder.

I did not put the part for the display ..

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks good! Travis is choking on installing the u8glib. We might need to rewrite the `.travis.yml` going forward, but I will check with other AVR-based github projects and see.

**Comment by thinkyhead** [comment]
Yes, to complete this we'll need to modify the `configuration_store.cpp` and bump the EEPROM version. Also, to keep the code optimal we'll want to make the feature optional, and only include the extra additions and calls for parameters when there's actually more than 1 extruder. I'll try to whip together some macros, etc., and get it in shape over the next few days.

**Review by thinkyhead — COMMENTED** [review]
To complete this we might need to bump the EEPROM version up. The general idea in the EEPROM is to store placeholders where values might end up. So if there could be 4 extruders, we should write 4 values, even if there's only 1 extruder, filling the empty slots with sane defaults, perhaps copied from the last value in the arrays.

Also, to keep the code optimal —especially the planner and stepper ISR— we'll want to make the feature optional, and only append the extra additions and calls for parameters when there's actually more than 1 extruder. I'll try to whip together some macros, etc., and get it in shape over the next few days.

**Comment by thinkyhead** [comment]
If you rebase this on the current `RCBugFix` it will fix the broken Travis testing. There's a problem with the u8glib download from arduino.cc so I switched to downloading it fro Github.

**Comment by boelle** [comment]
@MagoKimbra could you rebase this one on latest RCBugfix??

**Comment by thinkyhead** [comment]
@MagoKimbra is pretty busy, and this needs more careful attention anyway because of all the new extruder types. I'll do my best to make a more thorough version of this as time allows.

**Comment by Kaibob2** [comment]
Without making any stress here I would greatly appreciate a progress on this. As my printer becomes more and more a near perfect state I ran into the "different steps per extruder" a few days ago. The "ABS extruder"  requires 5 steps more than the "PLA extruder" . Currently I alter the steps via Startcode but a hardcoded value would be nicer.

**Comment by thinkyhead** [comment]
> Currently I alter the steps via Startcode

That is the supported methodology at this time. This is a non-trivial change requiring more testing time than we have available ahead of RC8. I will work on it as time allows, but the next month has me chasing a lot of tasks.

**Comment by thinkyhead** [comment]
Superseded by #5371.

**Pull request closed without merging**
