### PR TITLE
🩹 Fix missing _lcd_toggle_bed_leveling

### PR DESCRIPTION
**Pull request by thinkyhead**
- Fix missing _lcd_toggle_bed_leveling
- Update helper scripts for Darwin compatibility

### CODE REVIEW

**Comment by CRCinAU** [comment]
Dumb question - is this the same as https://github.com/MarlinFirmware/Marlin/pull/27421 ?

**Comment by thinkyhead** [comment]
> Dumb question - is this the same as #27421 ?

Taking notes in the form of code, it looks like I forgot with the new probe+leveling menu that I need to include the callback to toggle leveling anytime bed leveling exists at all, so I removed all the old conditions.

Should we remove the ability to toggle leveling only as part of `SLIM_LCD_MENUS`? My first reaction is it's probably not a big enough savings to include with `SLIM_LCD_MENUS` and users might expect it to be there even in that case. What do you think?

**Comment by CRCinAU** [comment]
I'm not exactly sure. I haven't had the time to have my head in Marlin-space for a while.

I guess the baptism by fire will be if the previously working build configurations still build and we have enough space for previously working configs in those space-limited environments.

I'll check back in after a few days builds if there's any previously working builds that no longer work.

**Comment by CRCinAU** [comment]
It seems like a couple of previously working builds using the `melzi_optimized` platform are now over storage capacity...

```
RAM:   [===       ]  31.2% (used 5109 bytes from 16384 bytes)
Flash: [==========]  101.8% (used 129226 bytes from 126976 bytes)
```

Prior to this breakage, this build was working.

I've also noticed that the STM32F401RC_creality platform also gets the same compile error:
```
Marlin/src/inc/Warnings.cpp:130:6: warning: #warning "Note: Auto-assigned LCD_SERIAL_PORT. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)" [-Wcpp]
  130 |     #warning "Note: Auto-assigned LCD_SERIAL_PORT. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)"
      |      ^~~~~~~
In file included from Marlin/src/lcd/menu/menu_probe_level.cpp:31:
Marlin/src/lcd/menu/menu_probe_level.cpp: In function 'void menu_edit_mesh()':
Marlin/src/lcd/menu/menu_probe_level.cpp:227:80: error: 'LCD_PROBE_Z_RANGE' was not declared in this scope
  227 |     EDIT_ITEM_FAST(float43, MSG_MESH_EDIT_Z, &bedlevel.z_values[xind][yind], -(LCD_PROBE_Z_RANGE) * 0.5, (LCD_PROBE_Z_RANGE) * 0.5, refresh_planner);
      |                                                                                ^~~~~~~~~~~~~~~~~
Marlin/src/lcd/menu/menu_item.h:290:39: note: in definition of macro '_MENU_INNER_F'
  290 |     MenuItem_##TYPE::action(flabel, ##V);                      \
      |                                       ^
Marlin/src/lcd/menu/menu_item.h:482:61: note: in expansion of macro '_MENU_ITEM_F'
  482 | #define EDIT_ITEM_FAST_F(TYPE, FLABEL, V...)                _MENU_ITEM_F(TYPE, true, FLABEL, ##V)
      |                                                             ^~~~~~~~~~~~
Marlin/src/lcd/menu/menu_item.h:483:57: note: in expansion of macro 'EDIT_ITEM_FAST_F'
  483 | #define EDIT_ITEM_FAST(TYPE, LABEL, V...)               EDIT_ITEM_FAST_F(TYPE, GET_TEXT_F(LABEL), ##V)
      |                                                         ^~~~~~~~~~~~~~~~
Marlin/src/lcd/menu/menu_probe_level.cpp:227:5: note: in expansion of macro 'EDIT_ITEM_FAST'
  227 |     EDIT_ITEM_FAST(float43, MSG_MESH_EDIT_Z, &bedlevel.z_values[xind][yind], -(LCD_PROBE_Z_RANGE) * 0.5, (LCD_PROBE_Z_RANGE) * 0.5, refresh_planner);
      |     ^~~~~~~~~~~~~~
Marlin/src/lcd/menu/menu_probe_level.cpp:227:80: error: 'LCD_PROBE_Z_RANGE' was not declared in this scope
  227 |     EDIT_ITEM_FAST(float43, MSG_MESH_EDIT_Z, &bedlevel.z_values[xind][yind], -(LCD_PROBE_Z_RANGE) * 0.5, (LCD_PROBE_Z_RANGE) * 0.5, refresh_planner);
      |                                                                                ^~~~~~~~~~~~~~~~~
Marlin/src/lcd/menu/menu_item.h:296:45: note: in definition of macro '_MENU_INNER_F'
  296 |       (HIGHLIGHTED(), _lcdLineNr, flabel, ##V);                \
      |                                             ^
Marlin/src/lcd/menu/menu_item.h:482:61: note: in expansion of macro '_MENU_ITEM_F'
  482 | #define EDIT_ITEM_FAST_F(TYPE, FLABEL, V...)                _MENU_ITEM_F(TYPE, true, FLABEL, ##V)
      |                                                             ^~~~~~~~~~~~
Marlin/src/lcd/menu/menu_item.h:483:57: note: in expansion of macro 'EDIT_ITEM_FAST_F'
  483 | #define EDIT_ITEM_FAST(TYPE, LABEL, V...)               EDIT_ITEM_FAST_F(TYPE, GET_TEXT_F(LABEL), ##V)
      |                                                         ^~~~~~~~~~~~~~~~
Marlin/src/lcd/menu/menu_probe_level.cpp:227:5: note: in expansion of macro 'EDIT_ITEM_FAST'
  227 |     EDIT_ITEM_FAST(float43, MSG_MESH_EDIT_Z, &bedlevel.z_values[xind][yind], -(LCD_PROBE_Z_RANGE) * 0.5, (LCD_PROBE_Z_RANGE) * 0.5, refresh_planner);
      |     ^~~~~~~~~~~~~~
*** [.pio/build/STM32F401RC_creality/src/src/lcd/menu/menu_probe_level.cpp.o] Error 1
========================= [FAILED] Took 30.16 seconds =========================
Environment           Status    Duration
--------------------  --------  ------------
STM32F401RC_creality  FAILED    00:00:30.164
==================== 1 failed, 0 succeeded in 00:00:30.164 ====================
```

**Comment by ellensp** [comment]
that is why my pr removed the feature with SLIM_LCD_MENUS enabled, vs this pr which made the feature work....

**Pull request merged**
