### PR TITLE
[1.1.x] Update russian language 27 February 2017

### PR DESCRIPTION
**Pull request by anton-piliugin**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Sorry, but we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases.

Normally we would say: "Please redo this PR starting with the `bugfix-1.1.x` (and `bugfix-2.0.x`) branch and be careful to submit it to the same branch you started with," but I will fix this up on your behalf and merge it directly.

Be sure to read http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions on PRs if you plan to make future contributions.

Thanks!

**Comment by thinkyhead** [comment]
I notice that you must have begun with the 1.1.x branch, which is now a bit out of date. There have been some changes since that release, so after I merge your update you may want to re-check the bugfix branches and make sure that nothing was missed. Thanks again!

**Comment by anton-piliugin** [comment]
Should i make a new pull request on bugfix-1.1.x?

**Comment by thinkyhead** [comment]
Only if you have something ready. I'm just about done cleaning up this one, actually, and was going to try pushing it back into this PR… Let me push it back here (and to your branch) and then you can look it over and see if anything's missing. Unfortunately the language-check script is currently broken or I could just throw out a list of needed translations…

**Comment by thinkyhead** [comment]
Note that `MSG_FILAMENT_CHANGE_OPTION_EXTRUDE` is now `MSG_FILAMENT_CHANGE_OPTION_PURGE`.

**Comment by anton-piliugin** [comment]
It's not too easy to compare the language_en.h file with translation because it has if statements, it will be better to think about the way how to make it easier or I just don't understand how to do it

**Comment by anton-piliugin** [comment]
Do we still have to limit MSG_LCD_ENDSTOPS by 8 chars?

**Comment by thinkyhead** [comment]
I believe that limit still applies.

Here's English with all the #ifdef and #endif removed…

**Comment by thinkyhead** [comment]
Hold on. Don't use that old English. Wrong version.

**Comment by thinkyhead** [comment]
[language_en.txt](https://github.com/MarlinFirmware/Marlin/files/1765863/language_en.txt)

**Comment by thinkyhead** [comment]
That should be easier to compare side-by-side.

**Comment by anton-piliugin** [comment]
Thank you!

**Comment by thinkyhead** [comment]
I'll just close this. I'm about to fall asleep… I'll review the new PR after some rest. Thanks again!

**Comment by thinkyhead** [comment]
@anton-piliugin — Ah, the script does work after all…

```
% ./buildroot/share/scripts/findMissingTranslations.sh ru

Building list of missing strings...
MSG_CONTROL_RETRACT_RECOVER_SWAPF   : ru
MSG_CUSTOM_LEDS                     : ru
MSG_DELTA_DIAG_ROD                  : ru
MSG_DELTA_HEIGHT                    : ru
MSG_DELTA_RADIUS                    : ru
MSG_ERR_HOMING_FAILED               : ru
MSG_ERR_PROBING_FAILED              : ru
MSG_EXTRA_FAN_SPEED                 : ru
MSG_FILAMENTLOAD                    : ru
MSG_FILAMENTUNLOAD                  : ru
MSG_FILAMENTUNLOAD_ALL              : ru
MSG_FILAMENT_CHANGE_HEADER_LOAD     : ru
MSG_FILAMENT_CHANGE_HEADER_UNLOAD   : ru
MSG_FILAMENT_CHANGE_OPTION_PURGE    : ru
MSG_FILAMENT_CHANGE_PURGE_1         : ru
MSG_FILAMENT_LOAD                   : ru
MSG_FILAMENT_UNLOAD                 : ru
MSG_INTENSITY_B                     : ru
MSG_INTENSITY_G                     : ru
MSG_INTENSITY_R                     : ru
MSG_INTENSITY_W                     : ru
MSG_LEDS_OFF                        : ru
MSG_LEDS_ON                         : ru
MSG_LED_BRIGHTNESS                  : ru
MSG_LED_CONTROL                     : ru
MSG_LED_PRESETS                     : ru
MSG_LEVEL_CORNERS                   : ru
MSG_M600_TOO_COLD                   : ru
MSG_MESH_LOADED                     : ru
MSG_MESH_SAVED                      : ru
MSG_NEXT_CORNER                     : ru
MSG_NO_STORAGE                      : ru
MSG_SET_LEDS_BLUE                   : ru
MSG_SET_LEDS_DEFAULT                : ru
MSG_SET_LEDS_GREEN                  : ru
MSG_SET_LEDS_INDIGO                 : ru
MSG_SET_LEDS_ORANGE                 : ru
MSG_SET_LEDS_RED                    : ru
MSG_SET_LEDS_VIOLET                 : ru
MSG_SET_LEDS_WHITE                  : ru
MSG_SET_LEDS_YELLOW                 : ru
MSG_SKEW_FACTOR                     : ru
MSG_THERMAL_RUNAWAY_BED             : ru
```

**Pull request closed without merging**
