### PR TITLE
Updated Finnish language file

### PR DESCRIPTION
**Pull request by tommil**
Translated and corrected translations.

### CODE REVIEW

**Comment by AnHardt** [comment]
@tommil 
Nice to see you used some of the new features. :-)
But I don't understand why you are using STR_Oe and \344 side by side.
I suppose you have a graphic display and want to see an 'ä' like character. In this case you could use STR_ae. The advantage would be that on char-based displays ( DISPLAY_CHARSET_HD44780_JAPAN ) a similar sign will show - not an 'µ'-like.

**Comment by tommil** [comment]
I didn't see \XXX character for letter ö. the word is lämpötila. 

in language.h there is. 

```
#define STR_Ae "\304"               // 'Ä' U8glib
#define STR_ae "\344"               // 'ä'
#define STR_Oe "\326"               // 'Ö'
#define STR_oe STR_Oe               // 'ö'
#define STR_Ue "\334"               // 'Ü'
#define STR_ue STR_Ue               // 'ü'
#define STR_sz "\337"               // 'ß'
#define STR_h2 "\262"               // '²'
#define STR_h3 "\263"               // '³'
#define STR_Deg "\260"              // '°'
#define STR_THERMOMETER "\377"
```

or is the correct one \204 ?

**Comment by AnHardt** [comment]
@tommil 
You have a pull request to your branch. 
changed STR_Oe to STR_oe and /344 to STR_ae

STR_Oe will show a 'Ö' best approximation on all displays.
STR_oe will show a 'ö' best approximation on all displays.

STR_ae will show the best approximation to 'ä' and not 'µ' the the hitachi displays with Japaneses charset what are so common.

Ah. I forgot to tell you that you can see a little thermometer when you replace \002 with STR_THERMOMETER when you have a graphic display

**Comment by thinkyhead** [comment]
@AnHardt Duh! I just realized I can do that. Contribute to someone else's PR by checking out their branch. Whoa. I bet I can even check it out as a remote into my own fork's local copy... Man, git is really cool.

**Comment by tommil** [comment]
There is a error in language.h. There is this define there: 

```
#define STR_oe STR_Oe               // 'ö'
```

And I think this replaces ö with Ö. And that look bit funny in the menu. 

marlin_menu

**Comment by AnHardt** [comment]
The error is not in language.h but in the used charset. There is no 'ö'. 

Where the ö used to be (/366 = 0xf6) in this font is a symbol for the right lower part of a giant thermometer. For that, on this type of display, is ' #define STR_oe STR_Oe', because we have an 'Ö' what is the best approximation. On other displays we have no 'Ö' there this is replaced by a 'ö'.

**Comment by AnHardt** [comment]
A question to the experts. Is this giant thermometer in use anywhere? Or is it e relic from the times before the extruders where drawn?

**Comment by thinkyhead** [comment]
@AnHardt For the non-graphical LCD I already patched the code so the special characters can be changed per-screen. Perhaps the same kind of thing can be done with the display in-question.

**Comment by thinkyhead** [comment]
Looking good. I'm sure, better than the previous. Merging...

**Pull request merged**
