### PR TITLE
Update MKS TinyBee ADC Reference Voltage

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Update MKS TinyBee ADC reference voltage

### Requirements

MKS TinyBee

### Benefits

Correct / Improved temperature readings

### Related Issues

- https://github.com/MarlinFirmware/Marlin/issues/24142#issuecomment-1171231707

### CODE REVIEW

**Comment by thisiskeithb** [comment]
~~> Failing after 31s — Run All Tests (Index_Mobo_Rev03)~~

~~I'm waiting on confirmation in https://github.com/MarlinFirmware/Configurations/pull/766#issuecomment-1171261641 to properly rename the related "Index" CI test/motherboard/pins files. From what I can tell from their website, the proper manufacturer is Opulo, model is LumenPnP, and motherboard is REV3.~~

There are now pending PRs to complete this rename.

The other failing CI test was due to moving Creality configs around.

**Comment by ellensp** [comment]
you could remove it from tests for now... 

https://github.com/MarlinFirmware/Marlin/pull/24431/commits/956e14b8cae42a9d659ed29827a90ef7c0bf5064

Add it back in when details are known.

**Comment by thisiskeithb** [comment]
> you could remove it from tests for now...

Done...for now. I have a PR with Opulo LumenPnP changes staged locally until the OP in https://github.com/MarlinFirmware/Configurations/pull/766#issuecomment-1171261641 replies.

**Comment by thisiskeithb** [comment]
I dropped the https://github.com/MarlinFirmware/Marlin/pull/24432/commits/d4e051a1d88d130c2bced9126c3fc0b7c2c313b0 commit since CI tests have more issues than just the Index/Opulo test.

**Pull request merged**
