### PR TITLE
Cleanup the buildroot

### PR DESCRIPTION
**Pull request by jbrazio**
> It has to start somewhere.
> It has to start sometime.
> What better place than here ?
> What better time than now ?

_-- Guerilla Radio, Rage Against the Machine._

Let's give the step forward, this PR cleans unmaintained build methods, it also addresses #3468 by removing the unused Arduino cores. Complete change list:
- Update Arduino core to 1.6.8
- Removed PlatformIOAddons
- Moved LinuxAddons to buildroot/bin
- Removed ArduinoAddons
- Removed duplicate license file Documentation\COPYING.md 
- Moved .astylerc to buildroot/etc
- Updates travis for the new buildroot environment

### CODE REVIEW

**Comment by marobol** [comment]
hi, i have a bug in RC6 last version, in the display menu, i can´t calibrate Delta point how was make in old version. and with priin a big piece , i see that the MKS 1.4 board make a reset, and stop printer like a reset with power on.
please can you help me with this?

**Comment by jbrazio** [comment]
@marobol do you care to open a new issue with your problem, that way it's far better to have a followup from the Marlin dev team. Thanks in advance.

**Comment by jbrazio** [comment]
I have build a list of "supported" boards which means boards that are listed in `boards.h`, for each board I found which are the micro-controller restrictions, required Arduino core and some miscellaneous notes.

You may see the information here: https://goo.gl/gFpujH
Remember this is a **work in progress**.

**Comment by thinkyhead** [comment]
Will this affect users who would like to flout the Arduino 1.5.x requirement and build on Linux with an older tool-set anyway?

**Comment by jbrazio** [comment]
No.. actually those users will always need to comment the `#error` directive otherwise they will never compile with an old IDE. The good news is that people _do upgrade_ their Arduino IDE, you'll be able to see this once I publish the results of the survey.

**Pull request merged**
