### PR TITLE
Add hidden option to output Bilinear grids in JSON

### PR DESCRIPTION
**Pull request by thinkyhead**
Enabling the hidden option `SCAD_MESH_OUTPUT` will cause the bilinear and MBL meshes to be printed in JSON format. For example:
```scad
measured_z = [
  [ -4.20, -4.13, -4.09, -4.03, -4.19 ],
  [ -4.16, -4.25, -4.27, -4.25, -4.08 ],
  [ -4.13, -4.26, -4.39, -4.31, -4.18 ],
  [ -4.09, -4.20, -4.26, -4.21, -4.18 ],
  [ -4.13, -3.99, -4.03, -4.06, -4.32 ]
];
```
The output of `G29` can then be pasted into this OpenSCAD visualizer script:

[/buildroot/share/scripts/MarlinMesh.scad](https://github.com/thinkyhead/Marlin/blob/rc_marlin_scad_mesh/buildroot/share/scripts/MarlinMesh.scad)

…and be viewed in OpenSCAD, with animated scaling. This is useful for anyone curious to see what the topography of the bed looks like graphically.

image

### CODE REVIEW

**Comment by hpo14** [comment]
i like this !! pretty good

**Comment by thinkyhead** [comment]
Host software could display mesh information graphically if they want, even without any JSON version. `M420` has been extended to print the leveling mesh or compensation matrix.

**Comment by Roxy-3D** [comment]
@thinkyhead    A week or two ago I added a special Topology Map command to UBL to output the data in a form that could be easily cut and pasted into Excel.   And it can generate a very similar map as what you have here.   Is this superior to the Excel version?   If so...  Maybe I should migrate to this format.   

But either way, it might be best for Marlin to always do the topology maps the same way?   Your thoughts?

**Comment by thinkyhead** [comment]
OpenSCAD is a popular open source tool in the RepRap and IoT scene, and there are a couple of web-based versions, as well (though they may not run the included script exactly as it is). There are probably several tools which can display a 2D grid applying bilinear interpolation. It's helpful that we can include one that runs on free software.

Actually, current versions of OpenSCAD can't handle more than 2 levels of tesselation with the given code, so in future I want to re-write it in Javascript. Then it can be included as one of the tools on the Marlin website. (We can put up calculators there too, and other such things.)

**Comment by Roxy-3D** [comment]
> Actually, current versions of OpenSCAD can't handle more than 2 levels of tesselation with the given code, so in future I want to re-write it in Javascript. Then it can be included as one of the tools on the Marlin website. (We can put up calculators there too, and other such things.)

I use OpenScad all the time!   It is great!   But... there is something called OpenJScad now.  It is pretty much backward compatible to almost all OpenScad code.   But the good thing about it is you can actually use variables in it.  Its got other good stuff too.  But the legitimate variable thing is the thing I noticed.

I haven't used it other than just to dabble with one day.   But I believe the J in the middle comes from the fact it is written in Java.   You might want to take a quick look at it.  It may do the things you want to see OpenScad to do!

**Comment by thinkyhead** [comment]
> always do the topology maps the same way?

For this PR I switched MBL to use the same `print_2d_array` function that was originally written for the `BILINEAR_SUBDIVISION` stuff. UBL could also use that function, and then the output will be consistent for all forms of mesh leveling. The output format could be determined by a parameter to `M420`, with a default setting. Spreadsheet-friendly output might be `M420 V C`. (`C` for visi**C**alc.)

We also have a request to output the grid in a visual order based on how the user's bed is aligned (i.e., if it homes to 0,0 in the back-right corner), which I support for readability. But there should be some marker so that hosts could use to determine the correct ordering if that's the output format. Or, we just always have hosts use `M420 V J` (e.g., for **J**SON format).

I've added `LEVELING_DATA` as a capability that hosts can look for if they want to display a leveling mesh or plane.

**Comment by Roxy-3D** [comment]
> UBL could also use that function, and then the output will be consistent for all forms of mesh leveling. The output format could be determined by a parameter to M420, with a default setting.

I'll take a look at converting over when things slow down.   I agree it would be nice to all use a common routine.     But I'll be trying to get Grid Based leveling (tilting) of the mesh going for the next 3 or 4 days...   UBL needs a function it can just call to display the map.   I'll probably need to warm over M420 so it calls a support function just so I have things in a form I can re-use.

**Comment by thinkyhead** [comment]
I like OpenJSCAD. I'm sure I can massage the OpenSCAD script to work in that environment. I believe it's written entirely in Javascript, using only the 3D capabilities of the browser. Just goes to show how Javascript is the new BASIC… only much better.

**Comment by Roxy-3D** [comment]
Would it make sense to have M420 be able to do both the ~~OpenScad~~ JSON version and the Excel version?

**Comment by Bob-the-Kuhn** [comment]
I don't see a reason to hide this option.  

The users will find out about it and start asking questions.  It'll save us time in the long run if we just document it immediately.

**Comment by thinkyhead** [comment]
I do consider this esoteric and debug-related enough to leave as a hidden option at this time. I don't savor the way it would be included in the configurations — namely, as the first leveling-related option to go into `Configuration_adv.h` (because, I feel, something referring to "OpenSCAD" doesn't belong in the main config).

When, or if, we choose to have a few different output options, then I'd welcome a single `DEFAULT_MESH_OUTPUT` setting with `SCAD` as one of its legal values. But I don't want to start down the road of having a group of of these.

The reason I've included the capability report flag is that we already have mesh output at this time that hosts could interpret.

**Comment by Roxy-3D** [comment]
Yeah...  I understand that logic!   The interesting thing is people started posting the graphical version of their bed's topographical map even without having the option available to make it easy to do.    So...  some people definitely will use it.

**Comment by Tannoo** [comment]
>When, or if, we choose to have a few different output options

Shouldn't that be, "When, or if, _I_ choose to have a few different output options" ?

**Comment by thinkyhead** [comment]
Yes indeed. Sorry about that!

**Pull request merged**
