### PR TITLE
Add ESP3DLib idletask entry point

### PR DESCRIPTION
**Pull request by luc-github**
### Requirements
None
### Description
Add entry point for ESP3DLib in ESP32 HAL_idletask()

### Benefits

Allows  to do actions when in main loop, like to know when Marlin setup is finished to display IP of device 

### Related Issues

No issue, just enhancement

### CODE REVIEW

**Comment by luc-github** [comment]
Error seems not related to this PR

**Comment by tpruvot** [comment]
strange, i dont see any reference to esp3dlib in HAL_ESP32/HAL.cpp nor HAL.h

but i see them in my repo...  git grep esp3dlib
```
Marlin/src/HAL/HAL_ESP32/HAL.cpp:82:      return esp3dlib.parse(command_ptr);
Marlin/src/HAL/HAL_ESP32/HAL.cpp:96:    esp3dlib.init();
Marlin/src/HAL/HAL_ESP32/HAL.h:44:  #include "esp3dlib.h"
```

**Comment by luc-github** [comment]
@tpruvot sorry what do you mean ?
all ref are in HAL_ESP32
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_ESP32/HAL.h#L44
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_ESP32/HAL.cpp#L96

**Comment by tpruvot** [comment]
when you click here, to see your commit changes...

**Comment by luc-github** [comment]
@tpruvot this PR add a missing entry point in  ESP32 HAL, in _idletask() function, the others entry points are already there in Marlin (https://github.com/MarlinFirmware/Marlin/pull/16515) , sorry,  I am not sure to understand your problem

**Comment by vivian-ng** [comment]
@luc-github I received errors:
```
.pio/libdeps/esp32/ESP3DLib/src/../../../../../Marlin/src/lcd/dogm/u8g_fontutf8.h:11:20: fatal error: U8glib.h: No such file or directory
```

It seems that using
```
#include MARLIN_PATH(lcd/ultralcd.h)
```
doesn't allow the eventual `u8g_fontutf8.h` to properly include `#include <U8glib.h>`.

I had to add
```
#include <U8glib.h>
```
to espcom.cpp in order to get it to compile.

**Comment by luc-github** [comment]
@vivian-ng please open issue in ESP3DLib
I tested only with oled128x64 and without display, so I may missed some condition

**Pull request merged**
