### PR TITLE
Improved DWIN LCD Code

### PR DESCRIPTION
**Pull request by Jyers**
This PR is based on my [Marlin fork for the Ender 3 V2](https://github.com/Jyers/Marlin), focused on rewriting the DWIN code to improve readability, development, and function. It includes significantly simplified menu, popup, and print screen handling. As well as a plethora of new features to bring the lcd more in line with other Marlin display implementations. These improvements result in a vast improvement in effort required to add new items and features to the menu, with everything laid out in a sensible and easy to grasp manner.

Features include, but are not limited to:

* 4 corner leveling menu with probe assisted functionality
* Z offset menu with live z axis movement
* Improved preheat menu with support for all 5 Marlin presets
* Change filament menu allowing for easy loading, unloading, and full guided M600
* Advanced option menu for marlin settings such as load length, PLR, runout options
* Visual menu for added display color customization and brightness control
* Leveling menu with mesh viewer, manual tuning, and leveling settings.
* Support for Manual Mesh(bilinear, probe manually), UBL, and Bilinear Leveling
* Added Popups for printer errors and UI dialogs
* Added octoprint support for showing print screen and progress
* M117 message bar for host info and printer dialogs
* PID tuning, probe testing, and many more...

For more information, feel free to check out the [github wiki](https://github.com/Jyers/Marlin/wiki) on my repo. It's a tad out of date, but gives a good sense of the project.

### CODE REVIEW

**Comment by tititopher68-dev** [comment]
@Jyers @thinkyhead 
Hello,
 I make a small remark on the use of GET_TEXT with a DWIN screen.  I'm starting to get to know him well and there are going to be some concerns.  DWIN screens are very limited with fonts.  The accented characters cannot be managed which will generate translation problems.  Then the use of jpg is just as limited due to the organization of the EEprom.
 In order to limit the number of speakers, I will send the details of all this and possible improvements directly to @Jyers who will modify its PR according to the relevance of the proposals.

**Comment by thinkyhead** [comment]
> DWIN screens are very limited with fonts

It may be possible for non-Western languages to make "fake" fixed-width fonts that are actually just bitmaps, and add mappings for the required characters. Note that the menu titles are already JPG images in most cases, which was necessary to support Chinese out of the box, so really we would only need to make a separate menu-titles bitmap for each language. Since there is limited space for bitmaps the user would have to re-flash the `DWIN_SET` with only the language(s) that they want to use.

**Comment by thinkyhead** [comment]
The use of `namespace` over `class` is slightly controversial. Generally the best thing about a `namespace` is that it provides one of the simpler ways to do overrides without needing to create a `class`. See the language files, for example. But, if this type of override is not actually being used, then the use of a `namespace` becomes kind of superfluous, and a `class` or `class` template may be the better choice because it also provides access specifiers and other useful constructs.

You will note that in my updates to the JyersUI pull request that I modified the class to make it completely `static`, which is generally the way I've been doing singletons in the Marlin codebase, and I don't see any reason why we would not also implement this as a singleton class, with an eye towards making a good base class that all these implementations can eventually share, with each one having its own sub-class for the methods where they are differentiated.

But what do you think? What are the advantages you see in using a `namespace` instead of a `class`?

**Comment by GhostlyCrowd** [comment]
this does not compile for me. 

<details><summary>Log Output</summary>

```
Marlin\src\lcd\e3v2\jyersui\dwin.cpp: In member function 'void Mesh_Settings::manual_value_update(bool)':
Marlin\src\lcd\e3v2\jyersui\dwin.cpp:197:9: error: 'gcode' was not declared in this scope
  197 |         gcode.process_subcommands_now_P(cmd);
      |         ^~~~~


Marlin\src\lcd\e3v2\jyersui\dwin.cpp: In member function 'void Mesh_Settings::manual_move(bool)':
Marlin\src\lcd\e3v2\jyersui\dwin.cpp:274:9: error: 'gcode' was not declared in this scope
  274 |         gcode.process_subcommands_now_P(cmd);
      |         ^~~~~


Marlin\src\lcd\e3v2\jyersui\dwin.cpp: In member function 'void Mesh_Settings::Draw_Bed_Mesh(int16_t, uint8_t, uint16_t, uint16_t)':
Marlin\src\lcd\e3v2\jyersui\dwin.cpp:335:11: error: 'gcode' was not declared in this scope
  335 |           gcode.process_subcommands_now_P("G4 P10");
      |           ^~~~~


Marlin\src\lcd\e3v2\jyersui\dwin.cpp:340:11: error: 'gcode' was not declared in this scope
  340 |           gcode.process_subcommands_now_P("G4 P10");  // still fails without additional delay...
      |           ^~~~~


Marlin\src\lcd\e3v2\jyersui\dwin.cpp: In static member function 'static void CrealityDWINClass::Menu_Item_Handler(uint8_t, uint8_t, bool)':
Marlin\src\lcd\e3v2\jyersui\dwin.cpp:1054:15: error: 'gcode' was not declared in this scope
 1054 |               gcode.home_all_axes(true);
      |               ^~~~~


compilation terminated due to -fmax-errors=5.
*** [.pio\build\STM32F103RE_btt_USB\src\src\lcd\e3v2\jyersui\dwin.cpp.o] Error 1


Marlin\src\lcd\e3v2\jyersui\rotary_encoder.cpp: In function 'ENCODER_DiffState Encoder_ReceiveAnalyze()':
Marlin\src\lcd\e3v2\jyersui\rotary_encoder.cpp:148:39: error: 'ENCODER_5X_STEPS_PER_SEC' was not declared in this scope; did you mean 'ENCODER_10X_STEPS_PER_SEC'?
  148 |           else if (encoderStepRate >= ENCODER_5X_STEPS_PER_SEC)   encoderMultiplier = 5;
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                       ENCODER_10X_STEPS_PER_SEC
*** [.pio\build\STM32F103RE_btt_USB\src\src\lcd\e3v2\jyersui\rotary_encoder.cpp.o] Error 1
```
</details>

**Pull request merged**
