### PR TITLE
Danish update (18 Aug 2016)

### PR DESCRIPTION
**Pull request by thinkyhead**
Quick and easy cleanup of #4629

This needs some additional repair. All strings over 20 characters must be reduced.

### CODE REVIEW

**Comment by boelle** [comment]
will give it a look

are there an easy way to catch those besides counting them?

mind you working on windows

**Comment by thinkyhead** [comment]
> are there an easy way to catch those besides counting them?

Yes and no. You still have to count them, but to make it easier, in your text editor place a 20-character "ruler" above the string(s) you're editing:

```
12345678901234567890
Tryk for at starte b|ed level
Sæt forskyding af ho|me
Forskydninger af hom|e pos. er tilføjet
```

**Comment by boelle** [comment]
ahh... or low tech with a but of tape and a mark on it...

will try and see if i cant get it done during weekend.... what to do if a string cant be reduced enough without it loosing its meaning completely?

**Comment by boelle** [comment]
have put a bit of sticky tape on the screen and made a mark for 20 chrs

can i get push access to rc_boelle_danish_update ? just so i can edit direct and put it to rest?

**Comment by thinkyhead** [comment]
> push access to rc_boelle_danish_update

You can just clone the branch, make changes, and submit a PR to my fork.
Read Github's documentation on the topic.

Alternatively, just post your suggested changes below.

**Comment by boelle** [comment]
```
#define MSG_HEATING_FAILED_LCD              "Opvarmning mislykkedes"
```

change to 

``` cpp
#define MSG_HEATING_FAILED_LCD              "Opvarmning fejlet"
```

will edit this one in random order as i figure a way to shorten them

``` cpp
#define MSG_ERR_MAXTEMP_BED                 "Fejl: Maks Plsde temp
```

change to

``` cpp
#define MSG_ERR_MAXTEMP_BED                 "Fejl: Maks Plade temp"
```

typo on that one

``` cpp
#define MSG_HOME_OFFSETS_APPLIED            "Forskydninger af home pos. er tilføjet"
```

change to

``` cpp
#define MSG_HOME_OFFSETS_APPLIED            "Forsk. af home pos. er tilføjet"
```

not sure if short enough but as close i can get without it becomes a drunk mans random rambling

``` cpp
#define MSG_SET_HOME_OFFSETS                "Sæt forskyding af home"
```

change to

``` cpp
#define MSG_SET_HOME_OFFSETS                "Sæt forsk. af home"
```

``` cpp
#define MSG_LEVEL_BED_WAITING               "Tryk for at starte bed level"
```

i cant figure this last one.... one way to do it is to omit the part of the sentence that says " push to " and simple let it say "Start bed level"..... which will be the same in both english and danish

**Comment by thinkyhead** [comment]
> i cant figure this last one

May I suggest "**`Et klik vil begynde`**" or "**`Tryk for at starte`**" or even "**`Klik når du er klar`**"

**Comment by thinkyhead** [comment]
``` cpp
//                                           12345678901234567890
#define MSG_HOME_OFFSETS_APPLIED            "Forsk. af home pos. er tilføjet"
```

This is shorter, but maybe it is terrible Danish…?

``` cpp
//                                           12345678901234567890
#define MSG_HOME_OFFSETS_APPLIED            "Forsk. er nu aktiv"
```

**Comment by thinkyhead** [comment]
Something like this would be fine for these errors, and closer to the Engelsk.

``` cpp
#define MSG_ERR_MAXTEMP                     "Fejl: MAKSTEMP"
#define MSG_ERR_MINTEMP                     "Fejl: MINTEMP"
#define MSG_ERR_MAXTEMP_BED                 "Fejl: MAKSTEMP PLADE"
#define MSG_ERR_MINTEMP_BED                 "Fejl: MINTEMP PLADE"
```

**Comment by boelle** [comment]
i can put a vote for "Klik når du er klar"

**Comment by boelle** [comment]
> This is shorter, but maybe it is terrible Danish…?
> 
> //                                           12345678901234567890
> #define MSG_HOME_OFFSETS_APPLIED            "Forsk. er nu aktiv"

no it can make do

**Comment by boelle** [comment]
> Something like this would be fine for these errors, and closer to the Engelsk.
> 
> #define MSG_ERR_MAXTEMP                     "Fejl: MAKSTEMP"
> #define MSG_ERR_MINTEMP                     "Fejl: MINTEMP"
> #define MSG_ERR_MAXTEMP_BED                 "Fejl: MAKSTEMP PLADE"
> #define MSG_ERR_MINTEMP_BED                 "Fejl: MINTEMP PLADE"

these can do fine too

**Pull request merged**
