### PR TITLE
maximum stepper rate is too small for LV8729

### PR DESCRIPTION
**Pull request by chai-md**
### Requirements
Using LV8729 stepper driver, MAXIMUM_STEPPER_RATE is modified 130000 to 800000.

### Description
Using LV8729 stepper driver, MAXIMUM_STEPPER_RATE is too small value.

For example, 0.9 degree stepper, 20T GT2 pulley, 1/128 microsteps, 500mm/s, MAXIMUM_STEPPER_RATE is up to 640000.  But that is not too large value for 32-bit controller boards.

### Benefits
High resolution microsteps of LV8729 will be usable with 32-bit controller boards.

### CODE REVIEW

**Comment by p3p** [comment]
> MAXIMUM_STEPPER_RATE is up to 640000. But that is not too large value for 32-bit controller boards.

LV8729 has a MINIMUM_STEPPER_PULSE of 1us, so in a perfect world discounting overhead with quad stepping that's 8us per ISR, the mcu needs time to do other stuff, lets say 4us to be optimistic, that's a MAXIMUM_STEPPER_RATE of 333K, 32bit isn't a magic bullet.

(this is 4am maths, so .. yea)

**Comment by chai-md** [comment]
But 1/128 microsteps and 650000 works now with SKR V1.3, LPC1768 100MHz Cortex-M3.
I don't know why it works.

**Comment by p3p** [comment]
You are running the MCU at 100% load, it may work some of the time depending on timing, but the MCU needs time to do other things and creating steps takes priority blocking those things.
sig

This shows an LPC176x trying to generate a 640K steps/s for a feedrate of 400mm/s actual result is an inconsistent  448K steps/s, resulting in an actual feedrate of 280mm/s and this leaves no time for communications or other utility functions meaning the MCU may not act correctly.

The default maximums may leave some room for them to be increased under some circumstances but this is left to the individual users discretion, in general I recommend using the lowest micro stepping setting you can, you will probably see little/no difference in print quality.

**Comment by chai-md** [comment]
Thanks for your detailed description.
I'll look for a reason for lost steps some other way, because higher maximum stepper rate solved losing steps in my case.

**Comment by thinkyhead** [comment]
Keep us posted. I would be interested to know the main cause of your issue.

**Comment by chai-md** [comment]
I guessed below;

MIN_STEPPER_PULSE_CYCLES is too large in this case.
In default settings of LV8729 with LPC1768, MIN_STEPPER_PULSE_CYCLES is 769.
I think that would be too large, then making too long blocking time for other steps.

I redefined MIN_STEPPER_PULSE_CYCLES to 50, 500ns from LV8729 data sheet,
and MAXIMUM_STEPPER_RATE to 200000.

I'm free from losing steps now.

**Pull request closed without merging**
