### PR TITLE
Fix G29 starting height on DELTA

### PR DESCRIPTION
**Pull request by thinkyhead**
Addressing #5450

### CODE REVIEW

**Comment by AnHardt** [comment]
I don't think this is the way to go. Would need the same handling for G30, M48, ...

**Comment by MagoKimbra** [comment]
I agree with AnHardt. In theory DELTA_HOME_TO_SAFE_ZONE it should be activated by default and always, but many have asked me the opportunity to be able to print beyond the danger zone. If print this for example http://www.thingiverse.com/thing:1913982 few millimeters above the danger zone is possible, but if I do the home after printing risk of going on the piece ...
So in my opinion it would be that if DELTA_HOME_TO_SAFE_ZONE is disabled, any movement except for G28 before everything goes below the danger zone and then does the rest.
Sorry for my bad english!!!

**Comment by AnHardt** [comment]
"Homing" with a part on the bed is always an error - not only for deltas. G28 is not a goto somewhere. Use G0/G1 instead.

If you put out the native English speakers, you English seems to be above average here.
I know, mine is suffering from my German. Even there i tend to too long and complicated sentences.
Just try to express your self.

(In almost all case where we do not understand the questions, or the answers, or we can't distinguish the one from the other - it does not make a difference if the writer is a native English speaker, or not. Mostly then, the writers don't give us enough context to make them understandable - they don't write about the things they want to write about. "Bedleveling does not work" is only slightly better than "My printer does not work", but leaves still open it he tries to unwrinkle the crumbled blanket on the place he sleeps. :-) )

**Comment by landodragon141** [comment]
@MagoKimbra I'll second @AnHardt  on that. I'm a native english speaker and even I fail to communicate :P

**Comment by thinkyhead** [comment]
> I don't think this is the way to go. Would need the same handling for G30, M48, ...

I think we may have to go that way.

We can't simply remove `if (z > delta_clip_start_height)` (always move down below `delta_clip_start_height`). The next block of code moves Z back up again (because the passed Z is higher than the current position).

Since this and its related functions serve a special purpose, they just have to be used with full cognizance of their side-effects.

One alternative might be to have `do_probe_raise` always move to the requested height, instead of only moving if it needs to move higher, as it does now.

> In theory `DELTA_HOME_TO_SAFE_ZONE` it should be activated by default.

Yes, it's helpful. But of course one could still move to the top with `G0` or `G1` afterward. And then you're back to the same problem. So, moving down when specifically needed seems like the best idea.

For the manual-move situation (and with `G` commands, if we want), we can try to constrain movement, just as we currently do with cartesian movement. If the move is above the safe zone, we can do `inverse_kinematics` to get the destination tower positions, constrain them down below the top, then use `forward_kinematics` to get the constrained cartesian position.

**Comment by thinkyhead** [comment]
So… It now lowers if needed in `probe_pt`, and in `Nozzle::clean`. I've audited all the places where `do_blocking_move_to` and related functions are called, and these are the only two places where it isn't already lowered or otherwise safe.

**Pull request merged**
