### PR TITLE
FYSETC S6 small bootloader target

### PR DESCRIPTION
**Pull request by GerogeFu**
Change FYSETC S6 boot address to 0x8000 to save flash room. The new bootloader is here : https://github.com/FYSETC/FYSETC-S6/tree/main/bootloader

### CODE REVIEW

**Comment by thisiskeithb** [comment]
It may be a better idea to extend the original environment with the new offset address so users who can't/won't update their bootloader can still use Marlin with their board.

**Comment by thinkyhead** [comment]
Indeed. We have to support the board as-shipped, and then if there is an alternative bootloader we must provide the link to it and the alternative environment for its use.

**Comment by GerogeFu** [comment]
Does that mean, i need to provide another variant as we need to change ldscript?

**Comment by thinkyhead** [comment]
There must be an environment that builds Marlin for the stock board. For an alternative board version or a board "modified" by flashing a different bootloader we must provide a second environment clearly named to make it clear that it is non-standard. We cannot simply dispose of the environment for the stock board. If that requires multiple ldscript files, then it requires multiple ldscript files.

**Comment by thinkyhead** [comment]
The added script `buildroot/share/PlatformIO/scripts/stm32_bootloader.py` should take care of the relocation. However, the `marlin_fysetc_s6.json` file describes the `upload` like this:
```json
  "upload": {
    "maximum_ram_size": 131072,
    "maximum_size": 524288,
    ". . ."
  }
```
Presumably the `maximum_size` should be decreased by 64K or by 32K depending on the bootloader size.

… but maybe the `maximum_size` refers to the total potential flash size when there is no bootloader.

**Comment by GerogeFu** [comment]
What about i add the following compile warning to pins_FYSETC_S6 ?

**Comment by GerogeFu** [comment]
I had a test of env:FYSETC_S6_8000, it does not work, but i don't know why. I try to print LD_FLASH_OFFSET in buildroot/share/PlatformIO/scripts/stm32_bootloader.py  with
print("offset is %s" % LD_FLASH_OFFSET)
And it is 0x8000. Can you take a look? @thinkyhead

**Comment by GerogeFu** [comment]
What about this, for env `FYSETC_S6`, we use the framework variant , the ldscript is 0x10000, so it won't change anything, and for env `FYSETC_S6_8000` we use the variants in marlin, we change the ld address to 0x8000 there. So it will be:
```
#
# FYSETC S6 (STM32F446VET6 ARM Cortex-M4)
#
[env:FYSETC_S6]
platform          = ${common_stm32.platform}
extends           = common_stm32
platform_packages = tool-stm32duino
board             = fysetc_s6
build_flags       = ${common_stm32.build_flags}
  -DVECT_TAB_OFFSET=0x10000
  -DHAL_PCD_MODULE_ENABLED
extra_scripts     = ${common.extra_scripts}
debug_tool        = stlink
upload_protocol   = dfu
upload_command    = dfu-util -a 0 -s 0x08010000:leave -D "$SOURCE"

#
# FYSETC S6 8000(STM32F446VET6 ARM Cortex-M4)
# This env is for new bootloader, check it here: https://github.com/FYSETC/FYSETC-S6/tree/main/bootloader
#
[env:FYSETC_S6_8000]
platform          = ${common_stm32.platform}
extends           = common_stm32
platform_packages = tool-stm32duino
board             = marlin_fysetc_s6
build_flags       = ${common_stm32.build_flags}
  -DVECT_TAB_OFFSET=0x8000
  -DHAL_PCD_MODULE_ENABLED
extra_scripts     = ${common.extra_scripts}
  pre:buildroot/share/PlatformIO/scripts/generic_create_variant.py
debug_tool        = stlink
upload_protocol   = dfu
upload_command    = dfu-util -a 0 -s 0x08008000:leave -D "$SOURCE"
```
Like i do here : https://github.com/FYSETC/FYSETC-S6/blob/main/firmware/Marlin/platformio.ini

**Comment by GMagician** [comment]
@GerogeFu Has anyone tryed to upload boot 0x8000 and marlin env_8000 with vscode? I tryed and board doesn't startup.
If I upload Marlin precompiled on fysetc github, loaded with stcube, it works.

**Comment by kyon03** [comment]
looking forward i dont know mine was same issue after flashing the compiled firmware mine also doesn't start up cant detect by the usb aft flash also cannot read by TFT28

**Pull request merged**
