### PR TITLE
Added calculation of difference between auto-corrected bed level plane and measure topology.

### PR DESCRIPTION
**Pull request by CptanPanic**
For Issue #1978

When using G29 with T option, it will print this out also.

### CODE REVIEW

**Comment by boelle** [comment]
the build failed, please rebase on latest devlopment

**Comment by CptanPanic** [comment]
I will redo this weekend.

**Comment by tonnico** [comment]
It's again a travis issue. Not an issue of this PR.
Anyone know what happend with that Marlin.pde?
@MarlinFirmware/collaborators

**Comment by AnHardt** [comment]
`Marlin.pde` is not in the repository anymore, so deleting it failes.
Since last weekend we have an other, not ino based `.travis.yml`. This is not updated here. Can't find the 1.1 label - branch is not up to date.

**Pull request closed without merging**
