### PR TITLE
Remove STM32H723VET6-based Octopus Max EZ

### LINKED ISSUE #25922: [BUG] Octopus Max EZ V1.0  wont build with env:STM32H723Vx_btt
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

BTT_OCTOPUS_MAX_EZ_V1_0  lists these two env: STM32H723Vx_btt and STM32H743Vx_btt
STM32H743Vx_btt builds fine
But STM32H723Vx_btt will not

### Bug Timeline

Unknown

### Expected behavior

It should build or if option is not valid it should be removed 

### Actual behavior

It errors with

```
Marlin/src/inc/../pins/stm32h7/pins_BTT_OCTOPUS_MAX_EZ.h:56:45: error: 'PF0' was not declared in this scope; did you mean 'PF_0'?
   56 | #define X_DIAG_PIN                          PF0   // M1-STOP

```
Port F pins are not defined in this varient

### Steps to Reproduce

1. #define MOTHERBOARD BOARD_BTT_OCTOPUS_MAX_EZ_V1_0
2. #define SERIAL_PORT -1
3. default_envs = STM32H723Vx_btt
4. build and watch it fail

### Version of Marlin Firmware

Bugfix-2.1.x

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

I confirmed with BigTreeTech today that the Octopus Max EZ only ships with an STM32H723ZET6 MCU since it needs >100 pins for GPIO.

Resolves #25922

### Related Issues

- #25922
- #25921

### CODE REVIEW

**Comment by ellensp** [comment]
This means that  'split env STM32H723Vx into E and G' created a variant STM32H723VE that  not used.

**Comment by thisiskeithb** [comment]
> This means that 'split env STM32H723Vx into E and G' created a variant STM32H723VE that not used.

It's been removed.

**Comment by thinkyhead** [comment]
Maybe one more change is needed. The `env:STM32H723Zx_btt` is actually specifically a 512K STM32H723ZE, never a 1024K STM32H723ZG.

**Comment by thinkyhead** [comment]
…and the `env:STM32H743Vx_btt` is specifically a 2048K STM32H743VIT6, never a different model of STM32H743Vx.

**Comment by thinkyhead** [comment]
I went ahead and made more specific environment entries for those MCUs.

I also did a quick check to see if there were any unused `boards/*.json` files and it looks like `marlin_CREALITY_STM32F401RC.json` is not used anywhere, although `env:STM32F401RC_creality` refers to `board_build.variant = MARLIN_CREALITY_STM32F401RC` (the variant to which that JSON file also refers). I wonder if there was ever an intention to use  `board = marlin_CREALITY_STM32F401RC`. It doesn't seem to contain anything vital, so probably it has been obsolete for a while.

Anyway, I'll just leave that note here for posterity.

**Pull request merged**
