### PR TITLE
[1.1.x] Fix Homing/UBL

### PR DESCRIPTION
**Pull request by smoki3**
This fixes the homing and leveling issue:

https://github.com/MarlinFirmware/Marlin/issues/11562

thanks to @dmitry-kutergin

same for 2.0.x : 
https://github.com/MarlinFirmware/Marlin/pull/11566

### CODE REVIEW

**Comment by Roxy-3D** [comment]
THANK YOU!!!

**Comment by thinkyhead** [comment]
Careful! This got merged to `1.1.x` instead of `bugfix-1.1.x`.

**Comment by smoki3** [comment]
Yes because 1.1.x also have the bug...

**Comment by thinkyhead** [comment]
We do not accept PRs directed at `1.1.x`. They must go to `bugfix-1.1.x`. Changes only go to `1.1.x` on formal version releases.

And… `1.1.x` is now end-of-life. All patches and future development should only go to `bugfix-2.0.x`.

**Comment by smoki3** [comment]
Sorry for thst. I just hought we need this hotfix on the stable branch to make the final release working.

**Comment by thinkyhead** [comment]
> Sorry for thst. I just hought we need this hotfix on the stable branch to make the final release working.

It's the right idea, but it will get applied from the bugfix branch at a later time, along with a few others.

**Pull request merged**
