### PR TITLE
[2.0.x] Editable servo angles

### PR DESCRIPTION
**Pull request by Freeviv**
Servo angle were hard-coded in Configuration.h. This change will allow the user to change angles without recompiling the firmware.  
This PR is related to #8838.

### CODE REVIEW

**Comment by TheSFReader** [comment]
Seems to me there are problems with the way some indexes are used. 

+ `uint8_t servo_angle[2*4];`  -> Why used a fixed size ?
-> `uint8_t servo_angle[2*NUM_SERVOS];`

```cpp
#define STOW_Z_SERVO() MOVE_SERVO(Z_PROBE_SERVO_NR, servo_angle[Z_PROBE_SERVO_NR + 1])
```
should be
```cpp
#define STOW_Z_SERVO() MOVE_SERVO(Z_PROBE_SERVO_NR, servo_angle[Z_PROBE_SERVO_NR * 2 + 1])
```
(ditto for the switching nozzle servo) and other uses of the servo_angle array.

If possible, I'd suggest using a bidimensional array instead of a linear one.

**Comment by Freeviv** [comment]
I used a fixed size array as suggested [here](https://github.com/MarlinFirmware/Marlin/issues/8838#issuecomment-352791173) but it also didn't feel right for me.
The array accesses should be fixed now.

**Comment by TheSFReader** [comment]
Can't check, but WAY cleaner !

**Comment by thinkyhead** [comment]
Various fixes applied:
- Make this an optional feature
- Make the angles array `uint16_t` (instead of `uint8_t`)
- Store placeholders in EEPROM if the feature is disabled
- Only list used servos in settings report for servo angles
- Account for dual switching extruders `SWITCHING_EXTRUDER_E23_SERVO_NR`
- Fix a `SWITCHING_NOZZLE` servo angle bug in `tool_change.cpp`

**Pull request merged**
