### PR TITLE
Serial message options

### PR DESCRIPTION
**Pull request by legend069**
#### `Configuration.h`
```cpp
//#define PROBING_GRID_MESSAGE        // Always report "Probing point #/#" to G29 / M48, ignoring the 'V' parameter.
//#define NO_HEATING_MESSAGES         // Suppress "Heating" messages at the start of heating.
//#define HOMING_COMPLETE_MESSAGE     // Reply "Homing complete." (before "ok") after G28.
```

#### `Configuration_adv.h`
```cpp
#define CUSTOM_MENU_MAIN // i find the custom g code commands i've added super helpful when setting the nozzle to probe offset for Z
having it navigated all the the one menu saves me alot of time
```

#### `G28.cpp`, `temperature.cpp`, `G29.cpp`, `M48.cpp`…
- `HOMING_COMPLETE_MESSAGE` - i like to see when it finishes homing.
- `NO_HEATING_MESSAGES` - these can get anoyying to see in octoprints terminal/ and seeing them show up in the LCD.
- `PROBING_GRID_MESSAGE` - handy to see when you run g29 to see how far it is getting.

#### `menu_main.cpp`
- edited arrangement of SD card 

### Requirements

LCD = cr10 stock display
board = btt_skr_mini_e3_v2

i'm unsure if the SD card Bug i've got is for the same board too

#### `Configuration_adv.h`
- easier z_offset adjustment - all in 1 menu !, no more navigation though motion, home z, save to eeprom, adjust z offset

#### `menu_main.cpp`
- SD card bug. Originally selecting "change media" with lcd did nothing. Now it releases the SD card as it should, messages show up as expected.

#### `G28.cpp`, `temperature.cpp`, `G29.cpp`, `M48.cpp`
0 - Files edited to be able to see messages if wanted/unwanted.

### Related Issues

#21841

- can be solved with custom menu or "start/end g code"

### CODE REVIEW

**Comment by legend069** [comment]
https://github.com/MarlinFirmware/Marlin/pull/21936

my files submitted are from branch 2.0.8

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs originating from an a different branch. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by thinkyhead** [comment]
Please test the [`bugfix-2.0.x` branch](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip) to see where it stands. If the problem has been resolved then we can close this PR. If the issue isn't resolved yet, then we can proceed to experiment further.

**Comment by thinkyhead** [comment]
@discip — yes, same behavior.

**Comment by discip** [comment]
@thinkyhead
Great!
Thanks!

**Comment by thinkyhead** [comment]
I think we'll just continue to work on standardization of behavior and not add so many customizations, so that hosts will get what they expect and the behavior of the firmware can be assumed by looking at the version number. For those who might want these kinds of changes to the serial output, clearly it is easy to accomplish. We don't need to add new options.

**Comment by legend069** [comment]
> 
> 
> I think we'll just continue to work on standardization of behavior and not add so many customizations, so that hosts will get what they expect and the behavior of the firmware can be assumed by looking at the version number. For those who might want these kinds of changes to the serial output, clearly it is easy to accomplish. We don't need to add new options.

Hi Tinkhead @thinkyhead 

i've recently changed the m48 g code to send the results to the host in a notification
is this a worthy contrition ?

**Pull request closed without merging**
