### PR TITLE
Break out gcode handlers - part 1

### PR DESCRIPTION
**Pull request by thinkyhead**
This begins the process of breaking out GCode handlers into separate functions, tested and found to add nothing to compiled code size or incur extra overhead, while improving readability and maintainability of code.
- Affects only Marlin_main.cpp
- Moved G0, G1, G2, G3, G4, G10, G11, G28, G29, G30, G92 into their own handler functions
- Applied coding standards to new additions and some of the staler lines

### CODE REVIEW

**Comment by whosawhatsis** [comment]
I like the idea, though I would have named the functions based on what they do, not what code triggers them. If properly written, these functions should be reusable, and some of them will call others.

**Comment by galexander1** [comment]
Lots of comments. :) I'm very excited someone is doing this!!

Before I get into the nitpicks, point of order: I think this is
absolutely the sort of change we cannot merge until we tag a stable
branch.  If we just tag a stable at the current development HEAD, and
then merge this exactly as is, I think we will be ahead in the long run
just because it will "break the ice", so to speak.

gcode_Gx() is a great name for the functions.  They will _not_ be
reusable, no point pretending otherwise.  A reusable movement function
would get its destination from parameters or a global variable, but
gcode_G0_G1() gets its destination from the G-code parser (code_seen()
etc).  If gcode_G0_G1() eventually becomes a super-simple wrapper for a
different reusable movement function, we might consider moving it back
into the big switch() statement, or we might just leave it as a tiny
wrapper...

gcode_Gx() functions should be marked static and/or inline, so that if
the compiler decides to inline them, it will not need to keep an
additional out-of-line copy.

I don't understand why there are a bunch of commits to just move things
around...various diffing tools will have different deficits but that is
no reason to change the code.

Moving local variables to local scopes -- commit 95beef4 -- yeah!!  This
is the sort of cleanup that I think actually makes a big difference in
readability!!  That is the yummy fruit we get to eat after we refactor!
Now everyone who changes this code in the future will immediately know
whether it is safe to overwrite these variables.

commit 9f68251 ("tweak") still rubs me the wrong way - don't reformat
unless you're actually going to solve a problem in that part of the code.

commit 086dd45 ("smaller code, speed doesn't matter") is a good example
why it may be a bad idea to gratuitously touch code you aren't going to
fix...it actually changes the behavior:
-  for (int i = 0; i < NUM_AXIS; i++) {
-    destination[i] = current_position[i];
-  }
-  for (int i = X_AXIS; i <= Z_AXIS; i++) destination[i] = current_position[i];

The original for loop went from 0 to 3, while the new for loop goes from
0 to 2!  I.e., the change causes it to drop the extruder axis.  If that's
on purpose then it deserves a better commit message.

Also, this is why we need a style guide _before_ doing style commits.  If
it is useful to make style commits to Marlin, then you will make this
commit (because one-line for loops are easy to read), and then I will
make the opposite commit (because if/for/while should always have {}),
and the resulting code churn will introduce typos and merge fails for no
benefit whatsoever.  The point of a style guide is so we always move
consistently in a single direction, rather than just in whatever seems
like a good direction to a given coder.

Additionally, it doesn't solve the actual problem.
I think the interactions with the planner should come down to just a
couple idioms:
   movement (i.e., G0): blocking or not, limit switch or not, before or
      after delta/corexy translation
   set current position (i.e., G92): before or after delta/corexy
      translation
But if you look at the code, there are a bunch of inconsistent idioms
for interacting with the planner.  plan_set_position() is almost always
called with the same arguments, the destination/current_position arrays
are manually copied to eachother, and so on.  So I think what needs to
happen is someone needs to sit down and read the code, actually
understand why it is done the way it is done.  Then come up with a real
list of the base idioms for interacting with the planner, and then come
up with a better set of functions or #defines to accomplish that.

I just think if we aren't going to do that, then style changes in planner
interface code are nothing but an opportunity to introduce a typo.

And just a side note about git: the per-commit checkin message is a
religious ritual that cleanses the soul.  If you can't think of any
better justification for your commit than "tweak, tweak", then don't
commit it.  It's really 4 separate meaningless style issues in 3 separate
areas of the code.  It should probably be 4 commits, or preferably 0
commits.

Ideally, each commit only does one thing, even if it is a big thing.
Once we have a style guide, I could imagine a monster commit "make all
for loops have consistent use of {}", and another monster commit "make
indentation consistent."  If your mission for the day is to fix up
whitespace, it's a bad idea to change arithmetic while you're doing it.
I agree that changing "+= (-1)_x" to "-= x" is probably both innocent and
clear, but if we happen to be wrong and it introduces a bug for someone,
they sure will be upset to track down the gratuitous change to the middle
of some totally unrelated style commit.  It's just very hard to be sure
-- while you are skimming by -- if an awkward arithmetic expression is
poor style on the part of the original author, or if it is a
carefully-balanced hack.  Especially in embedded development.  I don't
*think_ that gcc would generate crap code for -= and brilliant code for
+= of a negative constant, but in some embedded instruction sets, that is
exactly the sort of thing that can happen.  And if I'm not going to
investigate that question, I don't think I should be changing the
arithmetic expressions....

I.e., if it ain't broke don't fix it.  But I'm really glad someone is
approaching the refactor!!!

**Comment by thinkyhead** [comment]
I was playing around with the diff'er to see whether it could look clearer. In the end I think it's fine as it turns out. It interleaves the new functions with the old process_commands function, and that's interesting.

I certainly agree that a change like this seems large and deserves much review, but it's almost mechanical, moving the exact code into a separate function and doing a little cleanup. Rinse. Repeat. So I hope that others will look at the original code and compare to the new code and make sure that it's not screwed up in some way by a typo or something. In every sense it should look and behave just like the original (with some _improvements_ of course).

I did compile an earlier version of this code, just moving a couple g-code handlers into functions without any changes, and compared its size to the original code size – and they were identical. So it appears that the compiler is in fact inlining these functions.

**Comment by oysteinkrog** [comment]
@thinkyhead I think you are doing a lot of nice work, but it would be very nice if you could clean up your branches/PR's before merging.
Please rebase and squash commits!
Each commit should represent a clear and atomic change, and each commit _must_ have a proper message.
All these silly commit messages is making it very hard for other people to review your changes.

**Comment by thinkyhead** [comment]
@oysteinkrog I'm doing my best to merge and rebase. I would definitely be most happy to have a single commit with all the changes together. How can I do that?

**Comment by thinkyhead** [comment]
n/m I'm reading up on using **--interactive** mode to squash commits....

**Comment by thinkyhead** [comment]
#1451

**Comment by thinkyhead** [comment]
@whosawhatsis Though maybe not in Marlin (yet), I do kind of like the idea of exposing GCode as an API (even though it's an interpreted code) and making the interfaces correspond to the arguments that they can take, with "no-arg" defaults. And, since no overhead is really incurred, also making "alias" functions with names corresponding to behavior. I see this breaking out of gcodes into their own functions as merely the first organizational step.

**Comment by bkubicek** [comment]
it would be good if the gcode functions were to be declared INLINE ...

Bernhard

**Comment by thinkyhead** [comment]
Inlined the handlers, and updated the code so they are called only in one place... #1451

**Pull request closed without merging**
