### PR TITLE
Brings MKS Robin Lite and MKS Robin Lite2 boards support into Marlin2.0

### PR DESCRIPTION
**Pull request by MS1987**
### Requirements

* Brings  MKS Robin Lite and MKS Robin Lite2(STM32F103RCT6) boards support into Marlin2.0. 

### Description

Initial MKS Robin Lite and MKS Robin Lite2 (STM32F103RCT6) support brought over from Makerbase's [Robin Lite repo](https://github.com/makerbase-mks/MKS-Robin/tree/master/MKS%20Robin%20Lite) and [Robin Lite2 repo](https://github.com/makerbase-mks/MKS-Robin/tree/master/MKS%20Robin%20Lite2)

### Benefits

Brings  MKS Robin Lite and MKS Robin Lite2(STM32F103RCT6) boards support into Marlin2.0.

### Related Issues

None

### CODE REVIEW

**Comment by extesy** [comment]
@MS1987 Your PR merges entire 1.1.x branch into the new 2.0.x branch. They are not compatible, you can't do this merge.

**Comment by MS1987** [comment]
Wrong operation .

**Comment by thisiskeithb** [comment]
@MS1987: I put in an updated PR (https://github.com/MarlinFirmware/Marlin/pull/14729) that only merges the appropriate changes into `bugfix-2.0.x`.

**Comment by MS1987** [comment]
@thisiskeithb , thank you for making corrections.

**Pull request closed without merging**
