### PR TITLE
Error: Return to last code

### PR DESCRIPTION
**Pull request by Fourmi**
When you make a G29, after the G28, the probe stow & can't activate to X MIN POS, so need to return on the last code .

### CODE REVIEW

**Comment by robbycandra** [comment]
This PR have no file changed (?)

**Comment by Fourmi** [comment]
Hi,
Mistake on last PR, i change some code but it's wrong & not good, I handed the old code

**Comment by thinkyhead** [comment]
If you fix your work branch and use `git push -f origin` it will update this PR.

**Comment by tpruvot** [comment]
you want to do a git revert of the last TouchMi commit ?

**Comment by tpruvot** [comment]
So i will answer for him.. Yes its what he want.. the required G28 before G29 deploy the probe outside of the bed... and may "break" the pin on the bed edge... 

Personally i dont understand how a magnet can work on the left with this endstop on the left too. Unless the Z was moved up before...

**Comment by Fourmi** [comment]
No it's not exactly that, The G28 retracts the PIN each time and when we do a G29, we need to have the sensor activated and with the modification it does not do this action anymore.
No problem with the magnet on the left side, just need an offset of -5mm so that the X carriage does not come back in print.
That's how it needs to be configured

**Pull request closed without merging**
