### PR TITLE
Shutdown heaters and fan on Stop SD Print

### PR DESCRIPTION
**Pull request by tcm0116**
Extracted from #6407

### CODE REVIEW

**Comment by thinkyhead** [comment]
Note that this now causes Marlin to skip calling `thermalManager.autotempShutdown()` and leaves `autotemp_enabled` still set.

Side note: I wonder why `thermalManager.autotempShutdown()` is called in `gcode_M31`…. I believe it should only be called when a print completes, but "`M31`" may be used at any time.

**Comment by tcm0116** [comment]
Would it make sense to call `thermalManager.autotempShutdown()` from within `thermalManager.disable_all_heaters()`?

**Comment by thinkyhead** [comment]
Perhaps so. At least, it makes more sense than calling it from `M31`.

**Comment by tcm0116** [comment]
I had a look through the code, and `thermalManager.disable_all_heaters()` is currently only called when a print is ended for various reasons. I suppose it could be possible to disable the heaters during a print for some reason (pause, filament change, BLTouch probe), which might inadvertently disable auto temperature. Those examples currently use different methods to turn off the heaters, but it's feasible that some new feature could be added that calls `thermalManager.disable_all_heaters()`.

Another option could be to require that auto temperature be explicitly turned off on a similar manner to how the flow rate adjustment in the tune menu doesn't get reset when the print ends. However, there may be some issues with leaving auto temperature enabled that I'm not aware of.

**Comment by thinkyhead** [comment]
I'm pulling the trigger and moving it into `disable_all_heaters`, damn the torpedoes.

**Comment by thinkyhead** [comment]
Will merge shortly at #6567

**Pull request closed without merging**
