### PR TITLE
Don't allow stepper ISRs inside temperature ISR

### PR DESCRIPTION
**Pull request by Sebastianv650**
Don't allow stepper ISRs inside temperature ISR any more, therefore reducing complexity. Therefore also the flag indicating if a temp. ISR is running can be removed because the stepper ISR can't re-enable it anymore and therefore no re-entry is possible.

If this ISR interaction is the cause of some freezing issues we see, this should solve them.

Keep in mind that especially at high step rates on our 16MHz hardware, the stepper pulses will not be distributed perfectly in time because the temperature ISR can delay them up to 20µs.

See also #5946

### CODE REVIEW

**Comment by thinkyhead** [comment]
I think only the babystepping code probably needs to be protected. But this measure would be a good way to isolate the potential issue. We should have users test this branch soon.

Before that we should have them run `RCBugFix` again. I've just found and patched a bug in acceleration / speed limit code that would have affected all configurations (#5971) in unpredictable ways (due to reading the `max_acceleration_steps_per_s2` value for E1-E3 from the wrong place). The "fix" for another issue was to enable `DISTINCT_E_FACTORS`, and this clued me in to look for instances of remiss. There were no other such issues found in my search, so hopefully that PR clears up at least one very subtle and bad bug. Was it related to random freezing? Only another round of testing will tell.

**Comment by p3p** [comment]
Something that you might want to consider is how you can make the ISRs work when you have priorities, small sections of critical area are fine but in general you should never disable all interrupts on ARM (as far as I know, I'm most definitely not an expert), having an ISR that is generally much higher priority (stepper) not interrupt a lower priority (temp) under specific circumstances complicates matters. I'm not fond of the overlap of responsibilities that having babystepping in the temp ISR brings up but I understand it was a necessary part of the implementation.

**Comment by Roxy-3D** [comment]
> Something that you might want to consider is how you can make the ISRs work when you have priorities, small sections of critical area are fine but in general you should never disable all interrupts on ARM 

ARM processors run at a much higher clock rate.    Philosophically, we can debate how things should be.   But for a first implementation, it should be safe to just translate the current implementation over to 32-bits and trust that it will work.    (What ever delays the critical sections with interrupts disabled will shrink because of the higher clock rate.   How ever bad the problem is...  It will be less on ARM.)

I fully expect the ARM HAL will eventually leave all interrupts enabled and let them be fully nested.   But for now...   the extra speed of the ARM processors should keep us out of trouble.

> (as far as I know, I'm most definitely not an expert), having an ISR that is generally much higher priority (stepper) not interrupt a lower priority (temp) under specific circumstances complicates matters. I'm not fond of the overlap of responsibilities that having babystepping in the temp ISR brings up but I understand it was a necessary part of the implementation.

Agreed...   But higher processing power covers a multitude of sins.   I suspect the way baby steps are injected will be different (and more cleanly) on the ARM processors once we get that up and running smoothly.   But for now, it is what it is.

**Comment by p3p** [comment]
@Roxy-3D I don't disagree with you, yes we can hide a lot with power and keeping things efficient on AVR is more important to you. I was just having issues with my ARM build locking up and behaving oddly with the new ISRs and had to disable the cli and sei calls, which ofc is bad if they are being used elsewhere for critical sections. My comment was more just a hint that we are building on ARM now so it's something that could be considered. 

> I suspect the way baby steps are injected will be different (and more cleanly) on the ARM processors

That is of course an option although in general the code path for both ARM and AVR are being kept as close as possible, The HAL layer should only abstracts the hardware as the more divergent the builds the harder this will be to maintain. 

> on the ARM processors once we get that up and running smoothly

I've been running 32bit Marlin for a few months now and one thing it definitely is, is smooth. ;)

**Comment by Roxy-3D** [comment]
>  I don't disagree with you, yes we can hide a lot with power and keeping things efficient on AVR is more important to you. I was just having issues with my ARM build locking up and behaving oddly with the new ISRs and had to disable the cli and sei calls, which ofc is bad if they are being used elsewhere for critical sections. 

Yes...  This is important information!

**Comment by bamkrs** [comment]
I'm looking forward to test this branch this evening. Maybee it solves my temperature measurement spikes. And Im a Fan of uninterrupted Interrupts :)

**Comment by thinkyhead** [comment]
It's been up for a while, and have there been many calls for this patch in that time? Are we seeing problems that this may potentially address? If so, I'll expedite to get this merged.

**Comment by Sebastianv650** [comment]
@bhorn do you have some results for us?

Personaly I see no need for this PR at the moment, but let's see if bhorn has something to say.
The last bed temp. errors we had were due to a Cura issue, and beside @Angel996 problem where I'm not sure if it's fixed or not I don't know further heating problems.

As this is mainly to prevent errors during babystepping: There is not a single issue opened as far as I know. Therefore if no other feedback arrives, I would vote for a simple cli/sei around the babystepping call.

**Comment by bamkrs** [comment]
Even if this PR is closed, here are my two cents:
I've run his code for two prints of my beloved XYZ-Cube. I haven't seen any problems with it.
Printer runs fine and there are now quirks whatsoever.
But what I've seen is that all my temperatures where much smoother / less noisy: 
temperatureisr
Left: RCBugFix @ Before his PR
Right: His PR

TBH: Something seems to be wrong with the temperature-isr. I don't know why I'm the only one experiencing it this hard. Maybe because I'm running a 300x300 bed at 24v? I've PID-Tuned the s*** out of my bed. Never got a smooth print like back at 0.9.8 (or something). But this PR has raised my hopes. 
FYI: I'm still running his changes + my pid-bed-list.

**Comment by Sebastianv650** [comment]
My printer also has a 300x300mm 24V bed and I don't have such problems.
How should bed temperature changes create such a wobly surface as seen in your left print? If it is related to temperature, it should be due to huge changes in the nozzle temperature. Can you give us some numbers about your nozzle temp changes during the print?
Also some informations about your configuration may help.

**Pull request closed without merging**
