### PR TITLE
Added EEPROM functions to store total number of completed prints

### PR DESCRIPTION
**Pull request by ashwinprasadme**
using the EEPROM of arduino we have successfully tested the function to count the number of completed prints...

functions reside in the ConfigurationStore.cpp and is called from CardReader.cpp (CardReader::printingHasFinished) after each print

also added LCD menu funtions which will read from the EEPROM and display the total number of prints on LCD!

also added M codes:
M504: to retrieve the total number of prints from serial 
M505: Just to call increment function for testing ONLY!
M1000: to reset the counter

Best,
EZ3

### CODE REVIEW

**Comment by AnHardt** [comment]
The `relase` branch is closed for new features. Please try again in our development repository.
https://github.com/MarlinFirmware/MarlinDev

**Comment by AnHardt** [comment]
The counter feature as such is interesting. But mixed with LED-stuff and your personal configuration not of much value for us.

**Comment by ashwinprasadme** [comment]
Sure! I taught we're gonna discuss and keep only what's required! Shall i
delete all other files and keep only what's required for the EEPROM counter
and submit a pull for the development branch??

Best,
EZ3

**Comment by Wackerbarth** [comment]
I created a branch "TotalPrintCount" for your feature in MarlinDev. Please issue your pull request against that branch.

**Comment by KiteLab** [comment]
@Wackerbarth 
Whow! You are fast today.

**Comment by ashwinprasadme** [comment]
Will submit the request in a while!! Thanks alot

**Pull request closed without merging**
