### PR TITLE
Delta auto bed level (Updated PR)

### PR DESCRIPTION
**Pull request by maverikou**
Ported over Johann Rocholl's improvements for delta printers:
- Nonlinear auto bed leveling code. Cleaned it up to be a delta-specific AUTO_BED_LEVELING_GRID code path.
- Allen key z-probe deployment and retraction code. Cleaned it up and added safety checks.
- G29, G30, M401, M402.
- Z_RAISE_AFTER_PROBING.
- Added new test configuration (standard Mini Kossel setup) to test new bed leveling and z-probe code paths.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks good. I'm inclined to merge it, but I'll see if any testers are interested in trying it out first.

**Comment by maverikou** [comment]
Good idea.
I've only tested it on Mini Kossel with these config changes:
https://github.com/maverikou/Marlin/commit/ad50fbbc4807eebdbe6fc913aae8fd73a95aa3fc

**Comment by thinkyhead** [comment]
I'm still hoping to merge this soon. There are a lot of bed leveling related items being submitted lately. If you can resolve the current merge conflicts, I will try to get this in early in the week.

**Comment by maverikou** [comment]
Resolved.

**Comment by thinkyhead** [comment]
Excellent. Let's get this into the Development branch and see if anything breaks. :smiling_imp:

**Comment by alexborro** [comment]
Please someone TEST this added feature.

Cheers.

Alex.
Em 16/03/2015 22:17, "Scott Lahteine" notifications@github.com escreveu:

**Comment by SkyFlyer2** [comment]
These changes apply to the issue #1589 ?

**Comment by maverikou** [comment]
@SkyFlyer2 Yea it should solve #1589 - now it always raises before retracting.

**Comment by SkyFlyer2** [comment]
Ok,
I will check this.

**Comment by avluis** [comment]
Tester here - I can tell you it is not working as intended.
Here is a video that demonstrates the whole thing:
https://www.youtube.com/watch?v=BdIHuXF-Njg
First a G28, then a G29 E.
I won't do a G29 because I don't want to keep riding my micro switch on my glass...

Things to note:
The probing order is different now and the ABL routine ends on the front left instead of the front right as before.
Z_RAISE_AFTER_PROBING is raising AFTER the probe is up (I hope this is not how it was intended).
G28 still needs some love~

## 

@alexborro @thinkyhead @maverikou @SkyFlyer2

**Comment by SkyFlyer2** [comment]
avluis
Your video shows that Issue  #1589 is not solved still.

I also have checked now  - it does not work as it should.

The probe must be lifted up BEFORE any retraction, but it does not happens.

**Comment by maverikou** [comment]
G29 does this:

do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], Z_RAISE_AFTER_PROBING);

However that same code is not in G28. Is that the bug you're seeing?

**Comment by SkyFlyer2** [comment]
The probe not lift up before servo retraction. This is a bug, that I mean. In commands G28, G29, G30, M48.

**Comment by thinkyhead** [comment]
@maverikou @SkyFlyer2 The new `Z_RAISE_AFTER_PROBING` define should be working in `G29` at least, according to my reading of the code. It makes sense to do the same thing for Z homing (`G28`) but not using the same define. Instead we ought to add a `Z_RAISE_AFTER_HOMING` as a companion to the `Z_RAISE_BEFORE_HOMING` define.

**Comment by SkyFlyer2** [comment]
I will check it again.

May be is a good idea using only one define, e.g. Z_RAISE_BEFORE_RETRACTION. It is more simple, than two defines.

**Comment by thinkyhead** [comment]
@SkyFlyer2 Retraction has other connotations, so maybe `Z_RAISE_BEFORE_RETRACT_PROBE`. You're right that it should apply – when a probe is used – to both `G28` and `G29`.

**Comment by SkyFlyer2** [comment]
I checked this. Is NOT working as it should.

In g28 - no changes, servo retract and Z-axis not lift up.
In g29 - it is lift up probe AFTER servo retract, so it continue damaging servo.

I tested this just now.

---

"do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], Z_RAISE_AFTER_PROBING);" - this code must be executed before servo retraction. 
I tried put it in function probe_pt(), as result after G29 command Marlin starts printing in air, not on heated bed.

I don't understand why.

**Comment by thinkyhead** [comment]
@SkyFlyer2 Interesting. The code in G29 is supposed to start lifting the Z axis, wait for it to finish, then retract the probe.

```
do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], Z_RAISE_AFTER_PROBING);
st_synchronize();
```

This kind of code works elsewhere. The `st_synchronize` function should cause the code execution to stop and wait until the move is finished. If it's not waiting, that's peculiar. Perhaps you can add some code to print a message to the serial out or to the LCD in-between these lines, and see whether the code waits or not.

**Comment by SkyFlyer2** [comment]
it's not waiting, I check this already.

Also I found this: (probe_pt)

 #elif defined(Z_PROBE_ALLEN_KEY)
    // Move up for safety
    feedrate = homing_feedrate[X_AXIS];
    destination[Z_AXIS] = current_position[Z_AXIS] + 20;
    prepare_move_raw();

"Z_PROBE_ALLEN_KEY" is not defined.

**Comment by SkyFlyer2** [comment]
Should I define "Z_PROBE_END_SCRIPT" ?

**Comment by maverikou** [comment]
It is not working in your case because G29 calls probe_pt with act=ProbeRetract and causes a retract_z_probe() call, which in turn activates servos if SERVO_ENDSTOPS is defined.

I believe this code was getting merged at roughly the same time as Z_RAISE_AFTER_PROBING implementation and caused this high-level functionality conflict.

We could move 

```
do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], Z_RAISE_AFTER_PROBING);
st_synchronize();
```

into probe_pt and handle act=ProbeRetract or add ProbeLiftAndRetract as a special case?

**Comment by SkyFlyer2** [comment]
"It is not working in your case because G29 calls probe_pt with act=ProbeRetract and causes a retract_z_probe() "

I send this command: G29 e V4 P3
e - says no probe retraction between points.

Who does retract after the last sample point?

---

"We could move... ?"

About this I'm not sure.
Perhaps we need to test these 2 variants and select the best method.

I have tried to do so (move this code into probe_pt), the probe was raised before retract. It would seem that everything is OK? No! When I start printing, the printer starts to print in the air at a height equal to the height it was raised.
Maybe I'm just wrong code added, I do not know.

**Comment by maverikou** [comment]
Can't tell without seeing your code changes, but the return value (measured_z) is probably incorrect.

Did you do this?

```
if (retract_action & ProbeRetract)
    {
        do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], Z_RAISE_AFTER_PROBING);
        st_synchronize();
        retract_z_probe();
    }
```

**Comment by SkyFlyer2** [comment]
I insert only this line: "do_blocking_move_to(current_position[X_AXIS], current_position[Y_AXIS], current_position[Z_AXIS] + Z_RAISE_BETWEEN_PROBINGS);"

whitout "st_synchronize();"

" return value (measured_z) is probably incorrect."

But without this line, I can normal start print after auto leveling procedure.

**Comment by avluis** [comment]
Looks like my issue (with G28 and G29) was fixed with maverikou's blind fix: https://github.com/MarlinFirmware/Marlin/issues/1507

**Pull request merged**
