### PR TITLE
makefile: add buzzer.cpp

### PR DESCRIPTION
**Pull request by sorki**
ssia

### CODE REVIEW

**Comment by Wackerbarth** [comment]
This Makefile does not work in conjunction with modern version of the Arduino distribution.

Therefore, either, it needs to be updated to work with 1.5.x and 1.6.x OR it needs to be removed from the main portion of the tree and placed in the support area for those versions for which it does work.

**Comment by thinkyhead** [comment]
@Wackerbarth @sorki Does this change have any bearing on how well the `Makefile` works with 1.5.x and 1.6.x, or can this be merged as-is?

**Comment by Wackerbarth** [comment]
In its present form, the Makefile does not work with 1.6.x (and I suspect the same to be true of 1.5.x since the file system rearrangement therein).

As a result, this change has NO effect on any "newer" usage.

However, I oppose having it included "as is".
One of two things should happen:
1) As promised, one of the Makefile advocates will provide a new PR that improves the issues that are not presently addressed, or
2) The Makefile should be removed from the main portion of the Marlin tree. (In that case, it would be appropriate to include it in the Support folder(s) for the tools configuration(s) for which it does work.

To make these improvements, "as is" just removes the incentive to correct the deficiencies in either form mentioned above.

**Comment by thinkyhead** [comment]
@Wackerbarth I suppose we can move `Makefile` into the `Marlin/scripts` folder, but it will have to be slightly altered so it does a `cd ..` to get the proper working directory.

**Comment by Wackerbarth** [comment]
@thinkyhead -- I am OK leaving it in the easier-to-use location IF the promised enhancements are forthcoming as promised.  Otherwise, I would view it as something totally unsupported and expect the user who wants to use it to move it around as necessary.

As long as we continue to support Arduino IDE 1.0.x as well as later ones, NO version of the repository is going to work "out-of-the-box"  Everyone has to do something to fit the repository into their build environment.  So, I don't see moving a Makefile to be any different.

**Pull request merged**
