### PR TITLE
Add support for Composite USB on STM32 SDIO boards (experimental)

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
This PR provides the Marlin support for the (hopefully) upcoming USB composite feature (SD card and CDC USB) in the ST STM32 library.

The STM32 library changes are in [PR 586](https://github.com/stm32duino/Arduino_Core_STM32/pull/586).

The changes needed to support the new feature are:
- add flags to the **platformio.ini** environments to enable the USB composite feature
- add a section to **Sd2Card_sdio_stm32duino.cpp** so that when the USB composite feature is enabled that the Marlin access of the SD card uses the USB drivers.

This has been tested on a STEVAL board and a BLACK STM32F407 board.

It has been tested on 16G SD cards.

My 4G SD card does not work with the SDIO interface.  I need to look into that.

### CODE REVIEW

**Comment by Keltere** [comment]
Thanks, sorry to bother but this could add sd hosting capabilities to skr pro 1.1?

**Comment by thisiskeithb** [comment]
Will this conflict with existing SKR Mini * USB composite support that was added separately?

**Comment by thinkyhead** [comment]
@thisiskeithb — I don't think so. New code is added that depends on `USBD_USE_CDC_COMPOSITE` but the old code seems to still be preserved too. So this will only affect `STM32F407VE_black` and `STM32F401VE_STEVAL` builds.

**Comment by Bob-the-Kuhn** [comment]
FYI - the SD card is available to both Marlin and the PC at the same time.

I tried making them mutually exclusive but couldn't figure out how to restart either.

**Comment by Bob-the-Kuhn** [comment]
@thisiskeithb - I just downloaded the SKR Mini schematic.  It uses a SPI interface to the SD card  so the SDIO changes do not affect it.

**Comment by Bob-the-Kuhn** [comment]
@Keltere - the skr pro 1.1 uses a SPI interface for the SD card so this change does not affect this board.

**Pull request merged**
