### PR TITLE
[1.1.x] Monitor chamber temperature, with auto chamber fan control.

### PR DESCRIPTION
**Pull request by Lenbok**
This is an initial cut for feedback and testing. There are probably nicer ways of doing some of this.

Chamber temperature is currently reported along with normal hot end and bed temperatures to serial. The format is just like that used for hot end and bed temperatures, but using 'C' prefix. As there is no heater, target is always 0. Is this appropriate, or is there a better way to report chamber temperatures? Octoprint doesn't seem to mind the extra (it just ignores it).

Chamber temperatures are not reported on the LCD in any way.

When auto chamber fan is enabled, it currently just uses the same temperature threshold as the other auto controlled fans. I could imagine you may want the chamber temp set a little lower than the extruder auto fans? (you certainly wouldn't want it higher).

As the chamber temperature is not connected to any heater, it doesn't undergo mintemp/maxtemp monitoring. This would need to change in the future if active chamber heating became a feature.

### CODE REVIEW

**Comment by teemuatlut** [comment]
I'd suggest targeting bugfix-2.0.x at this point.

**Comment by Lenbok** [comment]
I'm using 1.1.x on my bot, and have never tried 2.0.x. Is 2.0.x stable enough to be used on a daily basis? If so, I could give it a crack (or maybe it would be worth waiting until the first 2.0 release?)

**Comment by teemuatlut** [comment]
It should be.
1.1.x will not have any more features added and v1.1.9 will be the last 1.1.x release.

**Comment by thinkyhead** [comment]
Watch out for a potential SD card not being detected issue with `bugfix-2.0.x` on AVR. It doesn't seem to affect everyone, but it definitely affects some.

**Comment by Lenbok** [comment]
I have ported this to bugfix-2.0.x but have yet to test it. After testing, should I open a new PR against 2.0.x, or should this one just be updated?

**Comment by thinkyhead** [comment]
I've rebased this and made one small change:
```cpp
SERIAL_PROTOCOLCHAR(
  #if HAS_TEMP_CHAMBER && HAS_TEMP_BED && HAS_TEMP_HOTEND
    e == -2 ? 'C' : e == -1 ? 'B' : 'T'
  #elif HAS_TEMP_BED && HAS_TEMP_HOTEND
    e == -1 ? 'B' : 'T'
  #elif HAS_TEMP_HOTEND
    'T'
  #else
    'B'
  #endif
);
```
If you want to do a PR for `bugfix-2.0.x` this would be an opportune time.

This would also be a good time to get feedback from @MarlinFirmware/host-software-team to see if hosts are ready to handle chamber temperatures.

**Comment by Lenbok** [comment]
@thinkyhead I already did a version for bugfix-2.0.x a few weeks ago, at #10045

**Comment by foosel** [comment]
Ready as in "won't break the parser": yes. Ready as in "will extract those values and display them": no.

**Comment by gearsawe** [comment]
I have a Rumba board and am using 2 out of the 3 extruder connections. My intention was to just use this 3rd extruder connection as method to monitor the chamber and control a fan if it got to hot. Would it have been possible to just reverse the logic for extruder 3? Though this might have been simple to reverse the logic right before the value was set for heater of extruder 3 only. The idea was the fan would just come on when over the target I am still very new to Marlin and tying to do this. Still trying to understand all this and hack my way thru the code or where even to look. Of course there might be problems with wild temperature drifts or maybe thermal run away detected. The thought is the display method is already there and a way to set a target. Also I would only be using the bang-bang for everything. Seem to have less problems of using bang-bang with wide temperature changes in the environment. The other thought is alter no code and just use an eternal Mosfet to flip the logic.

Edit: in the bugfix 1.1.x
With fan hooked up to heater 3. I got the desired result. In Conditionals_post.h I changed 
#define WRITE_HEATER_2(v) WRITE(HEATER_2_PIN, v)
to
#define WRITE_HEATER_2(v) WRITE(HEATER_2_PIN, -255+v)
but two problems the default is 0 so the fan is on at start up, not a big deal. 2nd get Thermal Runaway or heating failed once a temp is set. Since the settings are for all extruders it is a bit more difficult to isolate. 
The idea of this whole chamber thing is you want the temp to be just be the glass transition temperatures of the plastic you are printing with.

**Pull request merged**
