### PR TITLE
Use deploy/stow with FIX_MOUNTED_PROBE too

### PR DESCRIPTION
**Pull request by thinkyhead**
Follow up #4096
- Define `deploy_z_probe` and `stow_z_probe` even without ABL

### CODE REVIEW

**Comment by MagoKimbra** [comment]
Hello Scott.
A question, these are checks of defined constants:

```
if (Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE != Z_PROBE_ALLEN_KEY_STOW_1_FEEDRATE)
   feedrate = Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE;
if (Z_PROBE_ALLEN_KEY_STOW_2_X != Z_PROBE_ALLEN_KEY_STOW_1_X)
  destination[X_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_X;
if (Z_PROBE_ALLEN_KEY_STOW_2_Y != Z_PROBE_ALLEN_KEY_STOW_1_Y)
  destination[Y_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_Y;
destination[Z_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_Z;
```

 it is not best to do so?

```
#if (Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE != Z_PROBE_ALLEN_KEY_STOW_1_FEEDRATE)
   feedrate = Z_PROBE_ALLEN_KEY_STOW_2_FEEDRATE;
#endif
#if (Z_PROBE_ALLEN_KEY_STOW_2_X != Z_PROBE_ALLEN_KEY_STOW_1_X)
  destination[X_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_X;
#endif
#if (Z_PROBE_ALLEN_KEY_STOW_2_Y != Z_PROBE_ALLEN_KEY_STOW_1_Y)
  destination[Y_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_Y;
#endif
destination[Z_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_Z;
```

**Comment by thinkyhead** [comment]
> it is not best to do so?

Perhaps. But the result here will be the same. If the compiler sees `if (12 != 12) printf("Hi there!");` which will never succeed, it won't compile any code for that line.

**Comment by MagoKimbra** [comment]
I admit my ignorance, but I thought I compile the same code by adding useless. How not say sorry ..

**Comment by thinkyhead** [comment]
The current code will throw an error if any of these allen key macros are undefined. Using preprocessor macros, we need to do a little more work, because undefined macros are evaluated as zero. So really, you would need:

``` cpp
#if defined(Z_PROBE_ALLEN_KEY_STOW_2_X) && defined(Z_PROBE_ALLEN_KEY_STOW_1_X) \
  && Z_PROBE_ALLEN_KEY_STOW_2_X != Z_PROBE_ALLEN_KEY_STOW_1_X
  destination[X_AXIS] = Z_PROBE_ALLEN_KEY_STOW_2_X;
#endif
```

**Pull request merged**
