### PR TITLE
Configurator is out-of-date AGAIN

### PR DESCRIPTION
**Pull request by Wackerbarth**

### CODE REVIEW

**Comment by thinkyhead** [comment]
…and it doesn't work with the latest configs anyway due to various changes. And it doesn't make use of `Conditionals.h` or `SanityCheck.h` yet either. I hope to put in more time on it very soon. I will make a note on it, that it is EXPERIMENTAL.

**Comment by Wackerbarth** [comment]
@thinkyhead -- We have far too many versions of "almost the same" Configuration files.
It would be much better if configuration were driven off of a file that provides ALL of the defaults and produces only exceptions as the build-specific component.

View the configuration options the same way you would if it were an object oriented class inheritance.
Initially, we would only be going from a single flat base class to the derived class.

But, eventually, the idea could be extended into a more complete hierarchy.

My point is that if everyone is working off of the same base class rather than cloning and forking the file, then making consistent changes will become a less complex task.

**Comment by thinkyhead** [comment]
> It would be much better if configuration were driven off of a file that provides ALL of the defaults and produces only exceptions as the build-specific component.

Maybe. But having just a small tidy "diff" file is not a panacea. It helps sometimes to see things in context.

**Comment by Wackerbarth** [comment]
> Maybe. But having just a small tidy "diff" file is not a panacea. It helps sometimes to see things in context.
> 
> I agree that being able to VIEW the result in various ways is an important usability aspect.

However, the STORAGE need not be the same as the VIEW.
You are assuming that every user must store and look at the ENTIRE configuration space in one (or two) large files.

Think of the “exceptions” file as a patch.

However, there is no reason that the configurator could not display the entire context after it was patched.

In addition to the “out-of-sync” issue, the other problem in viewing “everything” in a flat file is that you cannot see the active material because it gets hidden in the inactive material, much of which is inapplicable to any given configuration.

At a minimum, you need to have some kind of viewing scheme which allows you to have a structured namespace and hide the portions that are not of current interest.

> It would be much better if configuration were driven off of a file that provides ALL of the defaults and produces only exceptions as the build-specific component.

**Comment by thinkyhead** [comment]
The nice thing is my configurator (when more complete) will be able to produce a file with just the edited configuration options.

The biggest downside to allowing overrides is that they will need to be included at the top of `Configuration.h` (because there are some `#ifdef` blocks in `Configuration.h`). And so, all the options in `Configuration.h` and `Configuration_adv.h` will need to be surrounded by `#ifdef` (not `#if ENABLED`) blocks in the same manner as `language_en.h` and for the same reason. This will tend to make the base (aka default) configuration files even more unreadable.

We might drop `#ifdef` blocks altogether in the configurations, but they are actually quite helpful for the configurator to be able to automatically determine which options are logically related.

**Pull request merged**
