### PR TITLE
[2.0.x] Add BABYSTEP_HOME_OFFSET feature

### PR DESCRIPTION
**Pull request by tcm0116**
This PR provides three things:

1. It fixes some issues with M206 that were missed when porting #8229 to 2.0.x.

2. It enables the use of M206 and `home_offset` for Delta machines.

This was previously not possible due to `home_offset[Z_AXIS]` being used to represent the changes made to `DELTA_HEIGHT` at runtime. But since `delta_height` was added to eliminate the use of `home_offset` in that manner, `home_offset` can now be used on Delta machines for the Z axis.

3. It adds the ability to perform babystepping in response to changes to `home_offset`.

The idea here is to provide an alternative to `BABYSTEP_ZPROBE_OFFSET` for machines that don't use the probe for homing. As has been discussed ad nauseam, `BABYSTEP_ZPROBE_OFFSET` simply won't work for machines that don't use the probe for homing due to the fact that the offsets to `zprobe_zoffset` are only temporarily realized when baby stepping is used, but they are lost when homing if the probe is not used.

`BABYSTEP_HOME_OFFSET` can be used on all machine types, regardless of the method of homing or if a probe is installed. In order to ensure state consistency, it does observe the soft stops (if enabled). However, in doing so, there is a limitation that needs to be understood.

With `BABYSTEP_ZPROBE_OFFSET`, the physical nozzle position in relation to the soft stops can change due to the use of `zprobe_zoffset` during the homing process with the probe. Since `home_offset` is a purely virtual construct, and not utilized in the homing process, M206 is unable to lower the nozzle to the bed past the soft stop limits.

For machines which home to Z- using an endstop,  this is generally addressed by positioning the endstop below the level of the bed and using M206 to provide the necessary offset to allow the nozzle to be at the level of the bed when Z = 0.

With machines that home to Z+, a similar technique would need to be employed. The simplest approach is to set `Z_MIN_POS` to a value slightly less than 0 to give M206 a bit of wiggle room when adjusting the first layer. For deltas, the delta height can be set to a value slightly larger than the actual height, which will give the necessary depth below the level of the bed to allow for live adjustment of the Z axis using M206.

I realize this isn't the most ideal solution, but it's at least consistent with how it works on machines that home to Z- using an endstop. I'm open to suggestions if there's a better way to accomplish this.

### CODE REVIEW

**Comment by LVD-AC** [comment]
I'm not in favor for re-introducing the use of home_offsets for delta's (this is a big step backwards); in this philosophy:
- printers that home using a probe use the zprobe_zoffset var to babystep
- printers that use the z-endstop to home use the home_offset[Z_AXIS] var to babystep

and
- printers that home to the top should use the delta_height var to babystep

thus having to implement 3 times the same functionality

I'm more in favor to introduce a new var (suppl_zoffset) common to all printers that can be babysteped, set with G-code, etc. and make sure that it functions the same on all printers. This is just renaming the zprobe_zoffset var to something more appropriate (or replacing it with Z_PROBE_OFFSET_FROM_EXTRUDER in case it used as such), and assuring that : 
1) changes to that var automatically persist after homing (like on printers that home with a probe)
2) probing results are not influenced by such changes.

The only thing needed to achieve this is in #9315

See #9310 for a more detailed breakdown. This also solves the "delta_height follows z-offset changes" problem not only on deltas but on all printers. The only thing that remains to be done in that PR is to change a couple of names that include a reference to "zprobe" to something more appropriate since that new z_offset is no longer probe related, it is an z-offset that can be changed, babystepped,...  additional to Z_PROBE_OFFSET_FROM_EXTRUDER, home_offset[Z_AXIS], delta_height, or whatever is used to determine the Z=0 height after homing. So the main variables Z_PROBE_OFFSET_FROM_EXTRUDER, home_offset[Z_AXIS], delta_height can be calibrated and remain unchanged by tweaking the print height of the 1st layer.

**Comment by tcm0116** [comment]
>thus having to implement 3 times the same functionality

Actually, with BAYBSTEP_HOME_OFFSET, we could remove BABYSTEP_ZPROBE_ZOFFSET, and only have a single means performing real-time adjustments to the nozzle height. Since this PR allows delta machines to use home offset, they are now in line with all of the other machines, so home offset becomes a common way to adjust the nozzle height. Babystepping the adjustments just gives the ability to realize the change in real-time instead of waiting for the next commanded movement in the Z axis. There all also existing GCode commands for adjusting the home offset, plus home offset is already a standard mechanism in the community for adjusting the nozzle height. 

My goal was to find an existing mechanism that could be used on all printers, and I think home offset is that mechanism. 

>I'm not in favor for re-introducing the use of home_offsets for delta's (this is a big step backwards)

I fail to see how allowing delta machines to use home offset is a step backwards. Before the introduction of `delta_height`, home offset was used as a hack to provide a means of adjusting the fixed `DELTA_HEIGHT`. With this PR, home offset works as intended, and provides a means of virtually adjusting the entire coordinate system.

**Comment by AnHardt** [comment]
Delta home offsets have also been used for adjusting the center, instead of hardware adjusting the endstops.

**Comment by tcm0116** [comment]
Home offset doesn't change the endstops. It offsets the coordinate system,
but still respects the endstops.

**Comment by LVD-AC** [comment]
Home_offset[Z] is indeed a hack to changing DELTA_HEIGHT, just like home_offset[X,Y] is a hack to changing DELTA_RADIUS_TRIM_TOWER, which equates to changing DELTA_TOWER_ANGLE_TRIM and changing DELTA_ENDSTOP_ADJ at the same time. When I first started auto-calibration I calibrated for the tower positions with this hack of home_offset[X,Y], while the calibration of DELTA_HEIGHT was done with the hack of home_offset[Z]. The 3 component were used with hacks because I developed this on an old Marlin version that didn't have any of those delta specific trim parameters, so I used the variable that was available (but disabled for deltas) in order to have a G33 routine that was as stand alone as possible, keeping in mind in a later stage it needed to be ported to a more resent version that didn't even remotely looked like the one I started working on.

But knowing that messing with home_offsets is messing with different delta specific parameters I only enabled the FW variable, but none of G-code or functionality to the user. There is a difference of using a hidden hack in the FW and making this very complex hack available to users to be used at their discretion. (@thinkyhead will probably claim that no such relationships exist between home_offsets and the equivalent delta specific parameters, but he's wrong).

It used to be: the non existent "delta_height" var = DELTA_HEIGHT + home_offset[Z] so "delta_height" automatically followed home_offset[Z] changes; here you just shift the problem of "delta_height needs to follow zprobe_zoffset changes" to "delta_height needs to follow home_offset[Z] changes" and create some extra ones like "delta_tower_angle_trim and delta_endstop_adj need to follow home_offset[XY] changes" as well. Home_offsets are disabled on deltas for a very good reason, that reason being they are a hack to change other (more comprehensive) delta specific parameters which in their turn are disabled on Cartesians. Now that all the required delta specific variables are available I really do not want to go back to the complexity of those home_offset hacks. Home offsets are the offsets towards min-end-stops that do not even physically exist on a delta, just like delta_tower_angle_trim and delta_endstop_adj do not physically exist on a Cartesian printer. Let's use the variables for what they really represent.

Sometimes I wonder what you people have against a good calibrated delta.

**Comment by tcm0116** [comment]
I don't think you understand how home offset works. In the current versions
of Marlin, it is only applied as an offset to the XYZ values passed to G1
and G0. It does not affect the planner or motion classes in any way. It's
essentially no different than going into the slicer and configuring it to
apply some fixed offsets to the coordinates it generates. As such, there is
no effect to commands like G33 or G29.

I have nothing against a well calibrated delta. I love my delta, and G33 is
awesome. Thank you for your work on that. I'm just simply proposing a
solution to provide live Z adjustment that will work on all machine types,
even ones without a probe.

**Comment by AnHardt** [comment]
Sorry confused with `delta_endstop_adj[]`.
Could also be a good place to adjust height.

**Comment by LVD-AC** [comment]
So please explain why on a calibrated printer the bed probes flat, but after applying a home_offset[X,Y] it probes in a tilted saddle shape typical of changing delta_tower_angle_trim or delta_radius_trim_tower. (hint: a slicer program does not use delta kinematic calculations)

And please also comment on my approach in #9310

**Comment by tcm0116** [comment]
>So please explain why on a calibrated printer the bed probes flat, but after applying a home_offset[X,Y] it probes in a tilted saddle shape typical of changing delta_tower_angle_trim or delta_radius_trim_tower. 

It shouldn't do this since `home_offset` is only applied in the G0 and G1 commands. However, I will give it a try to see what happens. 

>(hint: a slicer program does not use delta kinematic calculations)

Nor should it. `home_offset` is nothing more than a translation in the cartesian coordinate space. Setting the home offset to +10, +10 is the same as modifying the GCode to add 10 to every X command and 10 to every Y command. It is not applied at any deeper levels.

**Comment by tcm0116** [comment]
The `LOGICAL_TO_NATIVE` macro in the `GcodeSuite::get_destination_from_command` is the only place where `home_offset` is applied, so far as I can tell. All it does is add an offset to the requested XYZ destination, so it shouldn't affect the kinematics in any way. 

```
void GcodeSuite::get_destination_from_command() {
  LOOP_XYZE(i) {
    if (parser.seen(axis_codes[i])) {
      const float v = parser.value_axis_units((AxisEnum)i);
      destination[i] = (axis_relative_modes[i] || relative_mode)
        ? current_position[i] + v
        : (i == E_AXIS) ? v : LOGICAL_TO_NATIVE(v, i);
    }
    else
      destination[i] = current_position[i];
  }
```

**Comment by LVD-AC** [comment]
> It shouldn't do this...

The definition of home_offset is it changes the home position, the origin from which it calculates all other moves, or has that changed? Think of homing a delta printer to a different XY location, and think what will happens if all moves are done in relative mode (shouldn't be any different as absolute mode).

Deltas do not behave the same way as Cartesians towards a translation of the coordinate system.

so ...still it does do this. I've used this feature (hack) on purpose in the early pre-RC versions of G33 as an alternative way of calibrating the tower corrections (as I explained by lack of the appropriate variables being implemented). This is because home_offsets not only change the coordinates to move to (as a slicer program would) but also change the homing position (that is it's main and original purpose) and that has far more consequences on a Delta as on a Cartesian printer.

**Comment by tcm0116** [comment]
>The definition of home_offset is it changes the home position, the origin from which it calculates all other moves, or has that changed?

Yes, it has changed. `home_offset` is now only applied at the GCode level for command that take XYZ parameters, but does not affect movement commands generated internally. As such, commands like G28, G28, and G33 behave the same no matter what the home offset is set to. 

It sounds like you haven't actually tried the changes associated with this PR. Would you mind doing so? I think that will help your understanding of what's going on.

**Comment by LVD-AC** [comment]
> As such, commands like G28, G28, and G33 behave the same no matter what the home offset is set to.

On a Cartesian if your X-min endstop is set as such your nozzle is 5mm off the bed at homing, after applying the appropriate home_offset it will still be exactly 5mm off the bed just as it was before, when issuing a G30 X0 Y0 command it will try to probe also 5mm off the bed and G29 will try to probe off the bed as well, only during printing it will put (0,0) on the bed, but in all other cases it won't. Do I get this right?

**Comment by tcm0116** [comment]
Assuming you meant Z endstop, I believe your description is accurate. In
the case you've described, Z_MIN_POS would need to be set to at least -5 to
allow the nozzle to reach the bed once the Z home offset is set to +5 and a
G1 Z0 command is issued.

Ideally, the Z probe offset is pretty close to reality (i.e ± 1mm), and
then Z_MIN_POS is set to maybe -2. With this, one can just use the Z home
offset to dial in the first layer nozzle height as needed. The Z probe
offset wouldn't need to be changed at all.

**Comment by LVD-AC** [comment]
In my example I stated X-position and the printer is homing outside the bed area with the nozzle in mid air. Will home_offset[X_AXIS] change this?

**Comment by tcm0116** [comment]
No, it won't change the home position. If the nozzle is off the bed when homing and the home offsets are set to 0, the nozzle will be in the exact same position when homing after setting the home offsets to not-zero values. 

Home offset is applied post-homing and only to GCodes that take XYZ parameters. As I've stated numerous times, commands like G28, G29, and G33 are not affected by home offset. That may have been the case in the past, but that changed with #8229 and #8234.

**Comment by LVD-AC** [comment]
Out of curiosity: In the past Cartesian users could use home_offset to correct for such build errors with a simple G-code command. How are they supposed to do that now? (I've never owned a Cartesian, so I'm not completely familiar with them, nor with the Cartesian commands to shift an entire coordinate system to the desired spot - on a Delta doing so would lead to disaster)

**Comment by tcm0116** [comment]
>In the past Cartesian users could use home_offset to correct for such build errors with a simple G-code command. How are they supposed to do that now?

Same as before, with the M206 command. 

>on a Delta doing so would lead to disaster

Why? If I have a GCode file that has a part centered at 0, 0, and I decide that I don't want to wear out the center of my bed, I can simply send M206 with the desired X and Y offset to shift where the part is printed without having to re-generate the GCode file.

**Comment by LVD-AC** [comment]
M206 = set home_offset, but home_offset only effects printing and does no longer change the way the printer homes nor where it probes. How can one make it homes and probes on the bed if 0,0 is off the bed? That can no longer be done with M206 right?

**Comment by tcm0116** [comment]
That's correct, which is why one would have to set Z_MIN_POS to some
negative value in order to lower the endstop down to the bed. Assuming the
Z probe Z offset (for a printer with a probe) is set reasonably
accurate, Z_MIN_POS
wouldn't need to be much more than -1 to -2 millimetres.

**Comment by LVD-AC** [comment]
When your probe/nozzle is outside the bed area in X-Y you can set Z_MIN_POS to whatever you want, the probe will never reach the bed. But let's call it progress...

But back on topic : why not introduce a new variable to set the print height common to all printers:
- changes to it have to take immediate effect
- changes need to be persistent after homing
- changes may not disturb the probing results

We ran into trouble by the double use of zprobe_zoffset for that: it was used to set the distance between  the trigger point and the nozzle, and as such you need to set it before any G33 or G29 and not touch it ever again, and at the same time it is used to babystep during a print, so changing it and making the G29 and G33 data invalid. This lead to the discussion that having to re-calibrate a delta after each print in order to make the zprobe_zoffset changes permanent is a rather strange concept. IMO calibration is something you do before starting a print instead of having to do it after finishing a print...

I'm afraid we will run into similar problems by the double use of home_offset[Z]. I for one I do not want to have worspace_offsets enabled on my printer (I have a good reason for that), but really like to keep the babystep option. Are we in such need for memory space we can't spare 1 single float that takes care of babystepping for all, the way it should it done, and not try to reuse variables that are not designed for that?

I think this PR is good IMO it's just stored in the wrong variable, a new one should be created.

**Comment by tcm0116** [comment]
>why not introduce a new variable to set the print height common to all printers

Because there are already existing variables and GCodes that can be used to achieve the desired results. Why add more and more things that all basically do the same thing?

>I for one I do not want to have worspace_offsets enabled on my printer

Can you share your reason?

**Comment by LVD-AC** [comment]
Sure...

Delta inverse and forward kinematics use simplified formulas that only are valid when origin of the coordinate system is at the center of the printer; if a X-Y offset is applied to the coordinate system this is no longer the case and the much more complex kinematic formulas should be implemented (can't be done since even with the simplified ones the FW pushed an 8bit processor already to it's limits). So if the condition in order to be able to use the simplified formulas is no longer valid, all kinematic calculations will be wrong. 

Cartesians have a 1to1 kinematics, so there you translate, rotate, tilt, squish, stretch,.. the coordinate system as you please. Deltas require a bit more care to keep the center in the middle at all times and I'm not convinced the Marlin FW does that under all circumstances. Better safe than sorry, and accidentally setting an offset, tilt,... or whatever to the coordinate system that messes things up.

**Comment by LVD-AC** [comment]
I told you that with the olden home_offsets (implemented as a true offset of the coordinate system) a flat bed was seen as saddle shaped after applying an offset in XY plane. That's the error of using formulas under conditions they're no longer valid.

**Comment by p3p** [comment]
This is the point of workspace offsets is it not? all kinematics should be performed in machine space, workspace transformations should have no effect on that. if they do I see why LVD-AC has issues. coordinates are all just translated to machine space by the gcode interpreter (also I have no idea whats going on was just interesting in the topic)

**Comment by tcm0116** [comment]
>Deltas require a bit more care to keep the center in the middle at all times and I'm not convinced the Marlin FW does that under all circumstances. Better safe than sorry, and accidentally setting an offset, tilt,... or whatever to the coordinate system that messes things up.

I agree 100%. As I've done a lot of work to help make Marlin more delta safe (i.e. various measures to help prevent breaking diagonal arms), I'm all about not messing things up. 

That said, the center is still the center when using workspace offsets from a calibration perspective. All calibration is done in the machine coordinate system, regardless of the workspace offset. 

With the previous implementation of workspace offsets (pre mid-November 2017), then I can see how workspace offsets were problematic with delta calibration. However, the current implementation is delta-safe, and this PR simply enables the use of home offsets on delta machines as well as provides the ability to babystep changes to the Z home offset to provide real-time adjustment of the nozzle height. If this is determined to be the accepted solution, I would push for eliminating the Z probe Z offset babystepping so that we have a single method of live Z adjustment that works on all printers using existing mechanisms within Marlin.

**Comment by LVD-AC** [comment]
To be safe I would disable the X and Y component on deltas **and** push them to be zero...

**Comment by tcm0116** [comment]
>To be safe I would disable the X and Y component on deltas and push them to be zero...

That's already been done in this PR.

**Comment by LVD-AC** [comment]
Must have missed that...

**Comment by LVD-AC** [comment]
Tying it to a mechanism that is unknown to deltas, that is pretty useless on deltas, and that has been causing a lot of trouble on deltas (hence it was disabled) will lead to the conclusion : babystepping is for Cartesian printers only since the general knowledge still is "stay away from M206 as far as you can". The official definition of M206 still is "it is offsetting the homing position towards the min-endstops trigger points". Sure it no longer does that, but deltas still didn't grow min-endstops overnight towards you could offset to.

M206 "The values specified are added to the min-endstop position when the axes are referenced." Since deltas home at the top Deltas have M665 to do exactly that, but towards the max-endstop trigger positions instead of the min-endstops.

Not one single Delta on the planet has min-endstops so why on earth did you waste your time in making the offsets towards the min-endstops of M206 and all the related functionality "Delta proof", and in the process you've crippled the original functionality for all the people that do have min-endstops and need to be able to apply offsets to them. As such there is no need as well to make M665 "Cartesian proof" - not one single Cartesian homes at the max-endstops, so no need for them to apply offsets to those trigger positions. M206 is disabled on deltas just like M665 is disabled on Cartesians.

`How can one make it home and probe on the bed if 0,0 is off the bed? That can no longer be done with M206 right?`

Since you didn't answer my question I'll have a go at it : before #8229 just use M212, but that no longer does the trick, so get your screwdriver out and move your endstops physically. And let's call it progress...

So I repeat my plea to find a way to babystep that is universal and is not tied to specific Cartesian or specific Delta features.

**Comment by LVD-AC** [comment]
But Thomas you still didn't comment on my 5min 'if it aint broken don't fix it' approach (#9310):

The problem lies by zprobe_zoffset having a double use, so split it two and problem solved. This is only a question of giving one var two different names as the case dictates.

- set zprobe_zoffset to Z_PROBE_OFFSET_FROM_EXTRUDER (only available to printers with a probe) if it is used as a probe related offset
- set zprobe_zoffset to print_offset (available to all) if it is babystep related

That way you can't mess up existing functionality, and by splitting you automatically assure that all printers home now the same way (homing with a probe, with min-endstops, max-endstops,...), probing already remained unchanged for printers that homed with a probe so that will become universal as well.

Only drawback changes are not immediate during babystepping, you have to wait till the next line that is printed. That can be  fixed in a simple way as well. Now babystepping changes the variable and sends a command to lift/descend the nozzle without changing current_position; that command is only processed after the current line finishes to print. Just do the opposite change the variable and do not move the nozzle but change the current_position instead and the planner will take of it at the next segment, thus immediately.

In fact babystepping should be done on current_position and only the final change at exit should be added to the print_offset variable.

**Comment by ghost** [comment]
Little question : You said , if we use endstop switch , babystepping is down ? if it's the actual situation of marlin , your PR is an emergency ! And i will need this soon 👍

**Comment by LVD-AC** [comment]
I did run some tests by enabling all home_offsets on my delta and indeed home_offsets no longer influences the homing position or the probing positions so all is well on that front; however during printing home_offsets results in a changed print height (Z-hack) **AND** nice saddle shaped layers (XY-hack). It just did hide the problem of kinematic formulas no longer being valid from G33, but did't solve it.

**Comment by LVD-AC** [comment]
@p3p said:
> This is the point of workspace offsets is it not? all kinematics should be performed in machine space, workspace transformations should have no effect on that. if they do I see why LVD-AC has issues. 

If you #define NO_WORKSPACE_OFFSETS my delta printer only moves in the Z-axis but no longer in the XY plane. This is also not how one wishes the FW to behave but could be related to this glitch.

**Comment by thinkyhead** [comment]
Rebased and squashed.

**Comment by thinkyhead** [comment]
> Since `home_offset` is a purely virtual construct, and not utilized in the homing process, `M206` is unable to lower the nozzle to the bed past the soft stop limits.

I'd like to expound on this statement from the description, because it might be unclear on first reading. Forgive me if I repeat things that were already posted, but I need to work it out in my head as I go along.

To begin with, the purpose of `M206` is to modify the "home position" and it was originally conceived as a way to adjust the endstops' relationship to the bed origin.

The `home_offset` predates us all and it predates the workspace (which fixes software endstops to the same physical position) and the shift to native machine coordinates (so the internal coordinates don't _actually_ change with `G92` or `M206`).

In both the old scheme and the new scheme, so-called "soft endstops" can get in the way.
- In the old scheme, if your XMAX was 200, then after you issued `G92 X190`, you could only move 10mm to the right before being clipped. On the other hand, if you wanted to make more room for a move, you could use `G92` to gain space in one direction or another.
- In the new scheme, you can't use `G92` to give yourself more (or less) space to move. So now you can just disable the soft endstops if you need to move out of bounds. This allows moving a whole print-job to a different position on the bed while still retaining the same physical clipping area.

Meanwhile, the `M206` command shifts the `home_offset` and used to wait to get applied until the next `G28`. At some point I modified `M206` to take effect immediately. The `home_offset` was, in fact, originally conceived as a way mainly to adjust the Z and get the nozzle closer to the bed — to deal with shifty or unreliable endstops. The X and Y adjustments have always been less important.

In the old scheme, since the soft endstops were floating, you could set `M206 Z1` and then your print would start out 1mm lower. This was its purpose and it was quite handy. However, again, due to soft endstops shifting (unless you disabled _all_ the max endstops), you lost 1mm of height! So really, there has always been a trade-off to this method.

At the present time, `home_offset` and `position_shift` are combined into `workspace_offset`, and this is the only value that is used during operation. In the native machine space scheme this offset is used like a "translation matrix." The offset is subtracted from XYZ coordinates on input, and added to XYZ coordinates when they are printed on the screen or terminal.

These changes, conceived to simplify the system, have made `M206` a bit fuzzier in terms of its real utility, and it can be argued that it is now broken w/r/t its original purpose. Today, if you want the freedom to move below the bed, you have to configure your `Z_MIN_POS` as (_e.g._) -2, remembering to set your `Z_HOME_POS` to 0.

Though it may be fuzzy, the main reason to keep `M206` around is that it provides a persistent offset that can be saved and restored, whereas the `G92` offset is not saved to EEPROM (nor should it be).

Enter `BABYSTEPPING`! which changes the physical position of the nozzle without changing the current position in the firmware. Note how it has exact parity to `M206`. If you adjust the home offset at the same time, you're simply persisting the effect so it can be saved to EEPROM. (And, yes, physically moving the soft endstops too.)

To return to the new scheme before "native workspace patch," we were actually required to modify the soft endstops values in response to `M206` and `G92` changes. Since the native workspace patch we haven't been required to do this, and it has been one less thing to think about.

So the question naturally arises: What should be done, if anything, with soft endstops when the home offset is adjusted, if the aim is to start the print below the min endstop? The alternatives are:
- Do nothing, requiring min and max endstops to be configured with some leeway.
- Disable soft endstops entirely when `M206` is non-zero.
- Translate the soft endstops so you can always go to the min/max numerical values.
- …or…
- **Relax the soft endstops automagically.**

I think the last option is a pretty good one. Instead of moving all the soft endstops, only move the one(s) that would get in the way otherwise. In other words, when the X home offset is positive, the min soft endstop for X is moved left, but the max endstop stays in the same place. And so on…

Sorry to write a whole tome just for this punchline! But all things being considered, I think it's the best option for all concerned.

**Comment by thinkyhead** [comment]
>  It just did hide the problem of kinematic formulas no longer being valid from `G33`.

A reminder that all work with XYZ values must be done in native coordinates, using the `LOGICAL_TO_NATIVE` macro on all G-code coordinates before doing any maths.

From the slicer/host perspective this means that G-code must be careful to consider what the current workspace offset is, at least in terms of the `G92` offset. For example, after `G92 X100 Y100` you must send `G1 X100 Y100` to go to the home position. The `M206` offset can be ignored, because it intentionally shifts the workspace around.

In developing any feature, we should be sure to always test with `G92` and `M206` offsets to make sure it doesn't break. Most of the time it won't, because we are staggering geniuses.

So, as to your `G33` bowl-shaped problem!

First, make certain that you've used `LOGICAL_TO_NATIVE` consistently. (I believe that you have.)

Second, there's more that we forgot to consider… I hope I haven't got this completely wrong, but for a moment it made sense:

Since `M206` does affect coordinates on input, but G-code is meant to _ignore_ it, and since it may change, if you want to do maths in a generalized way (such as providing values to calibrate with) then it is important to remove the `home_offset` from those values before doing calculations. The `home_offset[Z_AXIS]` basically tells us how far away the bed should be moved.

To address that, you would need to find all the places in `G33` where `LOGICAL_TO_NATIVE` is used, and (after consideration) append `- home_offset[AXIS]` if it makes sense in that case given what I've just described. If it resolves the bowl shaped results, then we have learned something new.

But, don't rush into that process quite yet, if you're feeling ragged after all this verbiage. I want to evaluate both solutions completely before jumping in.

**Comment by thinkyhead** [comment]
One last note. I haven't committed to one approach over the other, and possibly they can both co-exist. In commenting on this topic I'm taking it seriously and seeing where it leads. There are some minor pitfalls, as with breaking the existing `G33`, but we are nothing if not experimentalists. Let's keep trying to work with the concept and see what can be learned.

And finally, the intent of `NO_WORKSPACE_OFFSETS` was to kill both `M206` and `G92` mainly for the benefit of deltas, since we wanted to get rid of the extra calculation when almost no one uses these on a delta.

My only caveat with this PR is that it brings back that calculation on every G-move command and slightly increases the load for all printing. Plus it brings back `G92` with `home_offset`, which… well… without `G92` along for the ride we could just have a Z adjustment and allow users to dump workspace offsets. This last bit is partly my fault, because I tied `M206` and `G92` together in the first place with `NO_WORKSPACE_OFFSETS`.

So… if Luc's solution manages to bypass this, allow us to forget about soft endstops and workspace offsets, I may prefer that solution. But I have yet to study it as closely as this one.

I will do that in about 12 hours — so brace yourselves for another tome!

**Comment by LVD-AC** [comment]
> So, as to your G33 bowl-shaped problem!

It's a saddle shape that is introduced by applying offsets but what the heck.

What G33 does in case of an offset is re-calibrate the printer to get rid of the saddle-shape, which results in applying the appropriate tower_radius_trim values to undo the offset (XY-offset = hack to changing tower_radius_trim). G33 can not change tower_radius_trim directly but does so by changing tower_angle_trim and endstop_adj (tower_radius_trim and tower_angle_trim are just two different ways to do the same thing).

G33 can deal with this providing probing moves result in the same height and position as printing moves 

> ...and (after consideration) append - home_offset[AXIS]

If they do not (print moves bare no relation with the corresponding probe moves), I really can't see a solution to have flat printed layers, only to have a flat probed bed.

So it is a bit pointless to introduce an XY offset on deltas if after re-calibration the corresponding delta kinematic parameters are set as such to bring back the nozzle at its original center position as if no offsets where applied. Calibration sets the conditions under which the simplified formulas are valid and result in moves in flat plane (further it tilts that plane by adjusting the endstops so it is parallel to the bed, but that is besides the point here). One has to choose: apply an offset and live with the saddle-shape or calibrate the printer to flat and undo any offset that was applied.

Simple solution: not allow any XY home_offset or position_shift on deltas.

Even simpler solution:

> And finally, the intent of NO_WORKSPACE_OFFSETS was to kill both M206 and G92 mainly for the benefit of deltas, since we wanted to get rid of the extra calculation when almost no one uses these on a delta.

Make this (intended lack of) functionality work again.

**Comment by thinkyhead** [comment]
> Simple solution: not allow any XY home_offset or position_shift on deltas.

No XY offset is intended. These would always be zero. If my explanation above forgets to mention this, apologies. I thought it was understood.

**Comment by thinkyhead** [comment]
> Make this (intended lack of) functionality work again.

It hasn't been changed. This PR is still open.

**Comment by tcm0116** [comment]
Before I forget, I noticed that the workspace offset is not considered when displaying the current position in the manual move axis screens on the LCD.

**Comment by thinkyhead** [comment]
> Before I forget, I noticed that the workspace offset is not considered when displaying the current position in the manual move axis screens on the LCD.

D'oh! I will fix that now and push it in about 2 minutes.

**Comment by thinkyhead** [comment]
Ok, changes pushed. Thanks for the heads-up!

**Comment by LVD-AC** [comment]
> Make this (intended lack of) functionality work again.
> It hasn't been changed. This PR is still open.

It stopped working somewhere after 1.1.5

**Comment by dtandersen** [comment]
Is this intended to be a way to compensate for the .1mm between the nozzle and bed when using paper to level the bed?

I've been doing something like this in my startup gcodes. Not sure if this is considered a good or bad practice.

```
G28
G29
G0 Z0
G92 .1
```
```
G28
G29
M290 -.1
```

**Comment by tcm0116** [comment]
@thinkyhead now that 1.1.9 is out, would you be interested in re-visiting this PR?

**Comment by thinkyhead** [comment]
Rebased.

**Comment by tcm0116** [comment]
@thinkyhead - what are you thinking on this? I really like having the ability to make real-time Z height adjustments that are persisted on my delta, which currently isn't possible. If you have a different approach in mind, if be happy to discuss it and possibly even take a stab at the implementation.

**Comment by thinkyhead** [comment]
This will first need a rebase and the menu changes will need to be moved to the reorganized LCD menu files. After I do that I may have more commentary.

My first comment is that this PR drops `HAS_POSITION_SHIFT` and changes the meaning of `HAS_WORKSPACE_OFFSET`, resurrecting the `position_shift` global when it shouldn't be needed.

Maybe the existing conditionals are poorly named and causing confusion…? Here's a primer on what they currently mean:

- `HAS_POSITION_SHIFT` means "needs the `position_shift` global." This array is used to remember any changes applied using `G92` under the new native machine space system.
- `HAS_HOME_OFFSET` means "needs the `home_offset` global." This array is used for setting a home offset that gets applied at the end of `G28`. It's the old-school way of dealing with flaky endstops and/or to provide a saved-to-eeprom offset to Gn motion coordinates.
- `HAS_WORKSPACE_OFFSET` means "needs the `workspace_offset` global," which Marlin just uses to save one add/subtract for every Gn move operation that would otherwise involve an add/subtract of _both_ `position_shift[]` and `home_offset[]`.

The `NO_WORKSPACE_OFFSETS` option is meant to get rid of _all_ modifiers to coordinates so we have an optimal motion system where logical and native machine coordinates are always the same.

**Comment by thinkyhead** [comment]
To get the code to conform to intended meaning of the conditionals described above, #12313.

**Comment by LVD-AC** [comment]
> The idea here is to provide an alternative to BABYSTEP_ZPROBE_OFFSET for machines that don't use the probe for homing. As has been discussed ad nauseam, BABYSTEP_ZPROBE_OFFSET simply won't work for machines that don't use the probe for homing due to the fact that the offsets to zprobe_zoffset are only temporarily realized when baby stepping is used, but they are lost when homing if the probe is not used.

This is no longer the case for Delta's; BABYSTEP_ZPROBE_OFFSET is working fine now and changes to zprobe_zoffset are persistant after homing.

**Comment by tcm0116** [comment]
Closing this as there appears to be no interest in moving forward with it.

**Comment by thinkyhead** [comment]
Interest, yes. Time to refactor it, no.

**Pull request closed without merging**
