### PR TITLE
add HardwareSerial and SoftwareSerial for Re-ARM.

### PR DESCRIPTION
**Pull request by kfazz**
HardwareSerial has been tested on Uart0 (debug header) and Uart3 (i2c connector)
Software Serial has been tested to work bi-directionally at 9600 and 115200
using pins 6 and 63 on J5, and unidirectionally (write only) at 250000.
The code used to test was Teemuatlut's tmc2208 patch, and a few small changes to main used to echo recieved chars back to a host pc.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Can you help me understand a few things?   With that many serial port options, won't the user have to configure which one is in use?   The reason I'm asking is I didn't see any changes to Configuration.h.

Also...  Can you help me understand which one I should use?    Right now a USB COM: port shows up and I can connect to it in PronterFace and talk to the board.   But the one bad thing about that is I miss all the early chit chat because the port isn't connected yet.  

On the AVR's when a USB Serial port connects it resets the firmware so all the early chit chat shows up.   Do we need to consider doing that here?

**Comment by kfazz** [comment]
I see the uarts being used for debugging, and for adding additional hardware.
This patch doesn't add any code which changes the current uart setup, just the drivers to do so.
I use Hardware Uart3 to control a tmc2208 stepper driver using an adapted #6345. see here: https://github.com/kfazz/Marlin/tree/bugfix-2.0.x-lpc_swuart/
Or attaching a serial display:
http://noritake-vfd.com/discount_sale_for_cu24063-y100.aspx
Another use could be sending debug messages over a seperate uart. Ie host pc using usb uart to print and debug messages over uart3. 
heres a quick test i used to make sure the ISR was firing, and to test reception by my host PC.
https://github.com/kfazz/Marlin/blob/bugfix-2.0.x-lpc_swuart/swuart_test.diff

**Comment by kfazz** [comment]
the usb losing the initial messages is out of scope for this patch i think, that's down to how the board is designed. On arduino the usb chip is separate from the mcu, so the mcu can be reset without taking down the usb. One way around this would be to simply loop until usb is connected, however that would break standalone usage. Or we could add a large circular buffer and a gcode to print it, a la dmesg, or a 'soft reset' command. Otherwise, you can hook a usb to uart to the debug header, and press the reset button.

**Comment by Roxy-3D** [comment]
Thank you for the explanation.   That helps me understand things!

**Pull request merged**
