### PR TITLE
[2.0.x] Korean language translation support

### PR DESCRIPTION
**Pull request by gouache**
* font : http://hangeul.naver.com/font

Signed-off-by: brian park <gouache95@gmail.com>

### Description

add initial code for Korean language translation support.
I used ubuntu 'fonts-nanum' package's NanumGothic.ttf file.

'language_ko_KR.h' translation is not perfect right now, but korean users will continue to contribute.

### Benefits

new language support for korean users.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Is the language file called `language_ko_KR.h` because there will be more than one variant of Korean, and this one applies to South Korea? Will there be another one in future called `language_ko_KP.h`?

**Comment by gouache** [comment]
> Is the language file called `language_ko_KR.h` because there will be more than one variant of Korean, and this one applies to South Korea? Will there be another one in future called `language_ko_KP.h`?

Sure, you are right. ko_KR is for south korea. As you mentioned ko_KP is for north korea.
Btw south and north korea word is very similar and ko_KR is more usual on linux world.

**Comment by AnHardt** [comment]
From the -bdf file:
> COPYRIGHT "Copyright � 2011 NHN Corporation. All rights reserved. Font designed by Sandoll Communications Inc."
_OTF_FONTFILE "NanumGothic.ttf"

Is the fonts license compatible?

**Comment by gouache** [comment]
you can refer to https://en.wikipedia.org/wiki/Nanum_font for details.
actually I'm not expert of fonts licnese, but I understood this font is
open font.
and all debian style linux already contains this font in their distribution.

is it possible any license issue?

2018년 10월 3일 (수) 오후 6:05, AnHardt <notifications@github.com>님이 작성:

**Comment by AnHardt** [comment]
I'm no advocate, but - I guess it's ok.
We just have to talk about that, before we get stress.

**Comment by gouache** [comment]
I fully agree that license is important. thanks for comment.

2018년 10월 3일 (수) 오후 6:22, AnHardt <notifications@github.com>님이 작성:

**Comment by thinkyhead** [comment]
The license is described here: https://en.wikipedia.org/wiki/SIL_Open_Font_License

**Pull request merged**
