### PR TITLE
✨ Ender 3v2 DWIN support on BTT Octopus V1.1

### PR DESCRIPTION
**Pull request by The-EG**
### Description

Add the ability to use the DWIN LCD that comes with an Ender 3 v2 on a BTT Octopus v1.1 board. Since this requires a custom cable, this also adds an `#error` warning the user of this unless `NO_CONTROLLER_CUSTOM_WIRING_WARNING` is also defined.

The custom cable is needed because the `RX` and `TX` from the DWIN need to be connected to the TFT port. All other pins on the EXP port of the DWIN can be connected as is to the EXP1 port on the Octopus board.

```c++
/**
   *        ------                 ------            ---
   *       | 1  2 |               | 1  2 |            1 |
   *       | 3  4 |            RX | 3  4 | TX       | 2 | RX
   *   ENT   5  6 | BEEP      ENT   5  6 | BEEP     | 3 | TX
   *     B | 7  8 | A           B | 7  8 | A        | 4 | 
   *   GND | 9 10 | VCC       GND | 9 10 | VCC        5 | 
   *        ------                 ------            ---
   *         EXP1                   DWIN             TFT
   *
   * DWIN pins are labeled as printed on DWIN PCB. GND, VCC, A, B, ENT & BEEP can be connected in the same
   * orientation as the existing plug/DWIN to EXP1. TX/RX need to be connected to the TFT port, with TX->RX, RX->TX.
   */
```

This can be accomplished with jumper cables with dupont connectors, but it is also possible to modify the board end of the existing cable and crimp on a 5 pin JST-XH connector for the RX/TX pins going into the TFT connector. This is much more robust:
image

### Requirements

An BTT Octopus v1.1 and the DWIN LCD from an Ender 3 v2. Only the genuine DWIN tested, but all 3 variants should work the same.

### Benefits

Allows for the DWIN LCD to be used with the BTT Octopus board.

### Configurations

[ender3v2_octopus.zip](https://github.com/MarlinFirmware/Marlin/files/9997493/ender3v2_octopus.zip)

### Related Issues

None

### CODE REVIEW

**Comment by antwal** [comment]
I used a different configuration proposed about 1 year ago and it works, but for some strange reason this generates a warning:

using:
```
// Choose the name from boards.h that matches your setup
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_BTT_OCTOPUS_V1_1
#endif

#define NO_CONTROLLER_CUSTOM_WIRING_WARNING
#define DIAG_JUMPERS_REMOVED

...
//
// Ender-3 v2 OEM display. A DWIN display with Rotary Encoder.
//
//#define DWIN_CREALITY_LCD             // Creality UI
//#define DWIN_LCD_PROUI              // Pro UI by MRiscoC
//#define DWIN_CREALITY_LCD_JYERSUI   // Jyers UI by Jacob Myers
#define DWIN_MARLINUI_PORTRAIT      // MarlinUI (portrait orientation)
//#define DWIN_MARLINUI_LANDSCAPE     // MarlinUI (landscape orientation)
```

log:
```
...
Compiling .pio/build/BIGTREE_OCTOPUS_V1/src/src/libs/numtostr.cpp.o
Marlin/src/inc/Warnings.cpp:79:6: warning: #warning "Note: Auto-assigned LCD_SERIAL_PORT. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)" [-Wcpp]
Compiling .pio/build/BIGTREE_OCTOPUS_V1/src/src/libs/stopwatch.cpp.o
   79 |     #warning "Note: Auto-assigned LCD_SERIAL_PORT. (Define NO_AUTO_ASSIGN_WARNING to suppress this warning.)"
      |      ^~~~~~~
Compiling .pio/build/BIGTREE_OCTOPUS_V1/src/src/libs/vector_3.cpp.o
Compiling .pio/build/BIGTREE_OCTOPUS_V1/src/src/module/endstops.cpp.o
...
```

even if I see written in the code:
```
/**
 * LCD_SERIAL_PORT must be defined ahead of HAL.h
 */
#ifndef LCD_SERIAL_PORT
  #if HAS_DWIN_E3V2 || IS_DWIN_MARLINUI || HAS_DGUS_LCD
    #if MB(BTT_SKR_MINI_E3_V1_0, BTT_SKR_MINI_E3_V1_2, BTT_SKR_MINI_E3_V2_0, BTT_SKR_MINI_E3_V3_0, BTT_SKR_E3_TURBO, BTT_OCTOPUS_V1_1)
      #define LCD_SERIAL_PORT 1
    #elif MB(CREALITY_V24S1_301, CREALITY_V24S1_301F4, CREALITY_V423, MKS_ROBIN)
      #define LCD_SERIAL_PORT 2 // Creality Ender3S1, MKS Robin
    #else
      #define LCD_SERIAL_PORT 3 // Other boards
    #endif
  #endif
  #ifdef LCD_SERIAL_PORT
    #define AUTO_ASSIGNED_LCD_SERIAL 1
  #endif
#endif
```

I'll have to change the lcd pins from the previous version I used but it should work even with the warning

**Comment by gsuresh2u** [comment]
Hi, is this useful for Octopus Pro also?

**Comment by The-EG** [comment]
@gsuresh2u You'd want to verify the pins and TFT port are the same, but the concept is the same

Edit: you would need to manually define the lcd serial port as well, or fix up the conditional for the pro.

**Comment by gsuresh2u** [comment]
Ok, Thanks

**Comment by gsuresh2u** [comment]
Hi, today i tried to install and connect to Ender3 V2 display to Octopus Pro 1.0
Downloaded bugfix branch, and customized as per my printer
compiled and installed to board, after installing, screen is just flickkering

i also tried firmware from mriscoc , which is compiling fine, and installed fine
but screen is just flickkering, no displa at all, connected all wires as per above
attaching my config file, can anyone please help ?
[Configs.zip](https://github.com/MarlinFirmware/Marlin/files/12707940/Configs.zip)

**Comment by ellensp** [comment]
@gsuresh2u this is not a support forum.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/2.0.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- 3D Printing Discord server. Join link: https://discord.gg/3dprinters
- Marlin specific Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Pull request merged**
