### PR TITLE
Restore FLYmaker FLY Mini Environment

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Restore FLYmaker FLY Mini environment. Verified on a real FLYmaker FLY Mini.

### Benefits

FLYmaker Mini owners can compile for their board again.

### Related Issues

Found while discussing migrating boards out of maple on Discord. This board was incorrectly added under the STM32F4 section before being accidentally ~~migrated~~ removed in https://github.com/MarlinFirmware/Marlin/pull/21507

### CODE REVIEW

**Comment by thinkyhead** [comment]
Superseded by #22356 which uses current methods.

**Comment by thisiskeithb** [comment]
Why doesn’t this board get a maple environment? We’re keeping around the maple envs for other boards for the time being.

**Comment by ellensp** [comment]
It got lost in the confusion the maple env is listed in pins now.

**Comment by thisiskeithb** [comment]
> It got lost in the confusion the maple env is listed in pins now.

Yes, but the entire maple environment is gone again because of https://github.com/MarlinFirmware/Marlin/pull/22355/commits/80ef74d2ba72976c8ed3d2f1e34b0b6cc16b5557.

I don't understand the parameters/threshold for not keeping a board's `*_maple` environment since there doesn't seem to be consistent application. Don't get me wrong, I'm all for killing of maple-based environments as soon as possible, but I assumed we'd keep them around for a while for users to fall back to.

**Comment by thinkyhead** [comment]
> threshold for not keeping a board's *_maple environment

PlatformIO has plans to drop Maple support entirely. We have been moving all the targets that require Maple to HAL/STM32 but preserving the old targets in case there are still compatibility issues. Of course, once PlatformIO drops support entirely, we will be removing all support from Marlin as well.

**Pull request merged**
