### PR TITLE
Fix runout mixed logic

### PR DESCRIPTION
**Pull request by GMagician**
Runout has mixed action.
**Note STATE=HIGH means filament is missing when input is 1**

### CODE REVIEW

**Comment by GMagician** [comment]
Fix #18592

**Comment by thisiskeithb** [comment]
~Configs are in a separate repo, but `FIL_RUNOUT_STATE` will have to be inverted there as well.~

**Comment by GMagician** [comment]
@thisiskeithb I thing configurations don't need to be changed cause it seems to be handled by code (I need to check if it's ok)

```c++
#ifdef FIL_RUNOUT_INVERTING
  #if FIL_RUNOUT_INVERTING
    #warning "FIL_RUNOUT_INVERTING true is now FIL_RUNOUT_STATE HIGH. Please update Configuration.h."
  #else
    #warning "FIL_RUNOUT_INVERTING false is now FIL_RUNOUT_STATE LOW. Please update Configuration.h."
  #endif
  #ifndef FIL_RUNOUT_STATE
    #define FIL_RUNOUT_STATE ((FIL_RUNOUT_INVERTING) ? HIGH : LOW)
    #undef FIL_RUNOUT_INVERTING
  #endif
#endif
```

**Comment by thisiskeithb** [comment]
I was looking at the MK3S/BTT002 config [and it was](https://github.com/MarlinFirmware/Configurations/blob/5dd127dc5d023881db684c12998bae16ad09721c/config/examples/Prusa/MK3S-BigTreeTech-BTT002/Configuration.h#L1155) `FIL_RUNOUT_INVERTING true`, and [is currently](https://github.com/MarlinFirmware/Configurations/blob/fc608b0d20b8518bb2635270dd1c4d0729e50add/config/examples/Prusa/MK3S-BigTreeTech-BTT002/Configuration.h#L1155) `FIL_RUNOUT_STATE HIGH`.

With the changes in this PR, it'll need to be `FIL_RUNOUT_STATE LOW`, correct?

**Comment by GMagician** [comment]
That should be what it was before. 
Configuration states that filament is **present** signal=HIGH and default invert is false
fil_runout_state is pin state when filament is **missing**.
Default should be and is correctly LOW

With configuration you report state should be HIGH

Edit: I hope not to mix with all inverted logic

**Comment by thisiskeithb** [comment]
I just wanted to double check since you had changed the wording in `SanityCheck.h` before your last commit 🙂

**Comment by GMagician** [comment]
Yes I checking old behaviour and new...probably fix will be only in M119

**Comment by GMagician** [comment]
Ok, now I properly reconstructed all... Only thing wrong here may be what M119 reports, code is perflectly working, but since M119 report "filament" and not "run out" triggered is correct when filament is present.

**Pull request closed without merging**
