### PR TITLE
Creality3D Ender 3 v2

### PR DESCRIPTION
**Pull request by thinkyhead**
Initial support for the Creality3D Ender 3 v2.
- 272 x 480 color DWIN / DGUS display with click-wheel interface.
- Support for an unspecified probe connected to the servo plug.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Glad to see it’s not another 128k Melzi 🙂

**Comment by Roxy-3D** [comment]
I'm confused...   Wasn't the purpose of ExtensibleUI to allow clean support of these displays without modification to Marlin itself?    Does this imply we need additions to ExtensibleUI in order to handle generic touch panel displays?

**Comment by thinkyhead** [comment]
> Wasn't the purpose of ExtensibleUI to allow clean support of these displays without modification to Marlin itself?

ExtUI is great for certain kinds of display devices — those which have their own menu system, receive commands in some custom protocol —mostly (if not all) over a serial port— and then send G-code to talk back to Marlin.

For the Ender 3 V2 display, Creality (or their subcontractor) opted to implement a limited menu on a minimal HMI / DWIN display with rotary encoder. Since the screen is dumb and fully controlled by Marlin, it is not suitable for ExtUI.

So, my plan is to use their code as reference to fully implement the menu system as a MarlinUI display, similar to HD44780 and DOGM.

**Comment by InsanityAutomation** [comment]
Isn't that methodology identical the the lulzbot display ExtUI was built around?

**Comment by CRCinAU** [comment]
I notice when trying to build:
```
Marlin/src/lcd/dwin/dwin.cpp: In function 'void HMI_Info()':
Marlin/src/lcd/dwin/dwin.cpp:2751:3: error: expected ';' before '}' token
   }                             
   ^                             
```
Seems to be missing the ; on `Draw_Control_Menu()`.

**Comment by thinkyhead** [comment]
> Isn't that methodology identical the the lulzbot display ExtUI was built around?

If any display wants to implement the complete Marlin menu system with editable values, select screens, and the rest, it must implement the appropriate MarlinUI methods.

**Comment by jdogmcsteezy** [comment]
@thinkyhead   I read the past comments but I am a novice around Marlin firmware.  I am trying to get Manual Mesh Bed Leveling to work on the Ender 3 V2.  I suspect it has something to do with the reasons discussed above but I want to make sure before I continue to dig.  The error received when compiling with `LCD_BED_LEVELING` and `MESH_BED_LEVELING` enabled is: "LCD_BED_LEVELING requires a programmable LCD controller."  

This is caused by this block here:

```
/**
 * LCD_BED_LEVELING requirements
 */
#if ENABLED(LCD_BED_LEVELING)
  #if !HAS_LCD_MENU
    #error "LCD_BED_LEVELING requires a programmable LCD controller."
  #elif !(ENABLED(MESH_BED_LEVELING) || HAS_ABL_NOT_UBL)
    #error "LCD_BED_LEVELING requires MESH_BED_LEVELING or AUTO_BED_LEVELING."
  #endif
#endif
```

Any insight would be greatly appreciated.

Thanks!

**Comment by thinkyhead** [comment]
At the current time `LCD_BED_LEVELING` requires an LCD controller that is implemented with `MarlinUI`. The DWIN display on the Ender 3 V2 is a custom display controller with its own custom code and no `MarlinUI` implementation. But a `MarlinUI` implementation for this display is planned in the fuzzy future because it shouldn't be too hard to accomplish.

**Comment by CRCinAU** [comment]
@thinkyhead - In a related note, I've sent you a PM via Discord re the EEPROM on the E3 V2 mainboard.... something strange is going on and I can't put my finger on it....

**Comment by jdogmcsteezy** [comment]
@thinkyhead Thanks for the quick reply and confirmation!

**Comment by ellensp** [comment]
Marlin/src/lcd/dwin/dwin.h  includes eeprom_BL24CXX.h regardless of IIC_BL24CXX_EEPROM being defined or not.

**Comment by tubalainen** [comment]
We are all waiting eagerly for the fussy future to suddenly happened 😋
Lots of the V2 beds are uneven and it would be great to get the manual mesh bed leveling working.

Thanks for all your hard work guys!

**Comment by thepixelabs** [comment]
Ender 3 v2 user here +1 on seeing support

**Comment by LouDnl** [comment]
Don't know if you have this already but I was wandering around and found a DGUS/DHWIN creator application. Seems it was used for the CR-10s Pro DWIN display. Can't reverse the E3v2 bin file with it but you can create a whole new menu. Might make it easier to implement a new MarlinUI for these displays?
Here's the link: https://github.com/juliandroid/DWIN_CR_10s_Pro

**Comment by Neonman423** [comment]
I am having a problem when using DWIN LCD with BTT 1.4 TURBO build,  Getting errors for MYSYERIAL not defined in scope.  Can anyone help me with this problem

**Pull request merged**
