### PR TITLE
Add Host Action Start

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Adds remote start to host action commands. Will request the host to start the active file. Useful when repeating the same file from Octoprint, or when starting the uploaded file after prep work (eg loading correct filament) is complete without going between both screens constantly.

Already implemented on the Octo side by @foosel 

https://github.com/OctoPrint/OctoPrint/commit/d320b1c7a3f766599cf993d9822d1d4a154a702a

### CODE REVIEW

**Comment by thisiskeithb** [comment]
@InsanityAutomation: Was there supposed to be a config option for this? `Host Start` is now enabled in the main menu with no way to disable it.

Edit: I'd still like to use `HOST_ACTION_COMMANDS`, but without this feature... or at least not in the main menu list.

**Comment by InsanityAutomation** [comment]
@thisiskeithb should be only when host prompt is enabled, I'll double check it's not defined unnecessarily.

**Comment by thisiskeithb** [comment]
I have `HOST_ACTION_COMMANDS` & `HOST_PROMPT_SUPPORT` enabled, but I don't plan to use this feature (and it takes up a top menu spot now), so being able to disable the menu item would be nice 🙂

**Comment by InsanityAutomation** [comment]
@thisiskeithb i took a peak, would you be satisfied if I opened a new PR to move the menu way down near where the custom menus are, above the sd menu? I dont like cluttering configs needlessly lol

**Comment by thisiskeithb** [comment]
> @thisiskeithb i took a peak, would you be satisfied if I opened a new PR to move the menu way down near where the custom menus are, above the sd menu? I dont like cluttering configs needlessly lol

That'd work.

**Comment by qwewer0** [comment]
Wouldn't it be better to add an ACTION_ON_START_MENU_ITEM in Configuration_adv.h? If that is enabled then ACTION_ON_START would show up in the menu. It still can be moved further down of course.
With something like this in menu_main.cpp:
```
#if ENABLED(ACTION_ON_START_MENU_ITEM)
    #ifdef ACTION_ON_START
        ACTION_ITEM(MSG_HOST_START_PRINT, host_action_start);
    #endif
#endif
```

**Comment by thisiskeithb** [comment]
> Wouldn't it be better to add an ACTION_ON_START_MENU_ITEM in Configuration_adv.h?

That’d be ideal, but I was going with the compromise.

I’d never use this feature and it eats up a main menu spot, so I’ll likely hide it in my branches if it won’t be configurable.

**Comment by qwewer0** [comment]
What do we think about this? https://github.com/MarlinFirmware/Marlin/pull/19443

Edit: That PR has ACTION_ON_START still at the top of the menu, so that might need to be changed.

**Comment by thisiskeithb** [comment]
Moving it down like @InsanityAutomation mentioned would also be good.

I don’t see why it should be at the top of the main menu.

**Pull request merged**
