### PR TITLE
Homing feedrates as XYZ array

### PR DESCRIPTION
**Pull request by rafaljot**
It allows you to tune the speed for both axis independently, which is needed for sensorless homing.

main change:

#define HOMING_FEEDRATE_XY (50 * 60)

to

#define HOMING_FEEDRATE_X (50 * 60)
#define HOMING_FEEDRATE_Y (50 * 60)

### CODE REVIEW

**Comment by rafaljot** [comment]
This PR requires much more changes...

**Comment by sjasonsmith** [comment]
> This PR requires much more changes...

Can you elaborate?

**Comment by thisiskeithb** [comment]
Don't forget to include a sanity check to alert users that `HOMING_FEEDRATE_XY` was split into `HOMING_FEEDRATE_X` / `HOMING_FEEDRATE_Y`.

**Comment by sjasonsmith** [comment]
Another option would be to change it to this form, used by some of the other feedrates:
`#define HOMING_FEEDRATE { 50*60, 50*60, 4*60 };`

This might complicate some things, though. For example, this line would break and require more rework to fix:
`#define Z_PROBE_SPEED_FAST HOMING_FEEDRATE_Z`

**Comment by rafaljot** [comment]
> > This PR requires much more changes...
> Can you elaborate?

It's already done.

**Comment by rafaljot** [comment]
> Don't forget to include a sanity check to alert users that `HOMING_FEEDRATE_XY` was split into `HOMING_FEEDRATE_X` / `HOMING_FEEDRATE_Y`.

HOMING_FEEDRATE_XY still works

I added these conditions to Conditionals_post.h 
#ifndef HOMING_FEEDRATE_X 
  #define HOMING_FEEDRATE_X HOMING_FEEDRATE_XY
#endif 
#ifndef HOMING_FEEDRATE_Y 
  #define HOMING_FEEDRATE_Y HOMING_FEEDRATE_YY
#endif

**Comment by thisiskeithb** [comment]
> HOMING_FEEDRATE_XY still works

You've removed it from the config and split the values, so a sanity check should be added to alert users that it's been replaced.

**Comment by thinkyhead** [comment]
> Another option would be to change it to this form

Sounds like it is time! I'll add a commit soon.

**Pull request merged**
