### PR TITLE
Additional cleanup of UBL code

### PR DESCRIPTION
**Pull request by thinkyhead**
Various cleanups and changes to conform to the latest code-base:

- Use the `wait_for_user` flag for typical wait-for-click scenarios
- Improved formatting correcting bad tab conversion
- Lowercase variable names
- Make longer comments foldable
- Use `ELAPSED` macro and `millis_t` type, where needed
- Use `const` where possible
- Use 8-bit values for small loop indexes
- Use `bool` where appropriate

[Concise diff](https://github.com/MarlinFirmware/Marlin/pull/6075/files?w=1)

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I'll review tomorrow morning if that is OK.   I was going to pull it down and verify everything works as expected.   If everything goes smoothly...   I might be able to give a 'Thumbs Up' by lunch time.

**Comment by Roxy-3D** [comment]
Thinky...   We have a problem...   I just moved my Configuration.h and Configuration_adv.h over to this...   And I get:
```cpp
In file included from sketch\MarlinConfig.h:39:0,
                 from C:\Downloads\3D-Printers\Roxy-Firmware\Thinky's_UBL_Cleanup\Marlin\Marlin.ino:3
SanityCheck.h:594: error: #error "The given LEFT_PROBE_BED_POSITION can't be reached by the Z probe."
         #error "The given LEFT_PROBE_BED_POSITION can't be reached by the Z probe."
          ^
exit status 1
#error "The given LEFT_PROBE_BED_POSITION can't be reached by the Z probe."
```
I'll look at more closely in the morning.   If you didn't change the LEFT and RIGHT (and FRONT and BACK) #defines...   Something must of got screwed up.   Let's not merge it until I get a couple of successful prints using it!  (and I'll help find the problem in the morning if you don't beat me to it.  But I've been out playing darts and I know better than to edit code after a few beers!)

**Comment by Roxy-3D** [comment]
We may need to think carefully about whether or not UBL is a 'Grid' based system.  I think turning on Grid logic and checks is at the root of why these changes are failing.   More in a bit...

**Comment by Roxy-3D** [comment]
@thinkyhead    OK...  I've got it compiling now.   I'm going to use that code to do a print as soon as my current print finishes.   In true Rep Rap fashion...  My printer is printing parts so that it can evolve into a better printer!

But here is what I found...  First, in UBL_line_to_destination.cpp the capitalization of this line needs to be fixed the same as everywhere else
```cpp
  extern const bool G26_Debug_flag;
```
Then in Conditionals_post.h
```cpp
  #define ABL_PLANAR (ENABLED(AUTO_BED_LEVELING_LINEAR) || ENABLED(AUTO_BED_LEVELING_3POINT))
  #define ABL_GRID   (ENABLED(AUTO_BED_LEVELING_LINEAR) || ENABLED(AUTO_BED_LEVELING_BILINEAR) || ENABLED(AUTO_BED_LEVELING_UBL))
  #define HAS_ABL    (ABL_PLANAR || ABL_GRID)
```
needs to be changed back to
```cpp
  #define ABL_PLANAR (ENABLED(AUTO_BED_LEVELING_LINEAR) || ENABLED(AUTO_BED_LEVELING_3POINT))
  #define ABL_GRID   (ENABLED(AUTO_BED_LEVELING_LINEAR) || ENABLED(AUTO_BED_LEVELING_BILINEAR))
  #define HAS_ABL    (ABL_PLANAR || ABL_GRID || ENABLED(AUTO_BED_LEVELING_UBL))
```
And we need one more change just to get things to compile.  We need to conditionally do the ABL 3-Point probe checks:
```cpp
  #else // !ABL_GRID
    #if !ENABLED(AUTO_BED_LEVELING_UBL) 
      // Check the triangulation points for 3-point leveling
      #if ABL_PROBE_PT_1_X < MIN_PROBE_X || ABL_PROBE_PT_1_X > MAX_PROBE_X
        #error "The given ABL_PROBE_PT_1_X can't be reached by the Z probe."
      #elif ABL_PROBE_PT_2_X < MIN_PROBE_X || ABL_PROBE_PT_2_X > MAX_PROBE_X
        #error "The given ABL_PROBE_PT_2_X can't be reached by the Z probe."
      #elif ABL_PROBE_PT_3_X < MIN_PROBE_X || ABL_PROBE_PT_3_X > MAX_PROBE_X
        #error "The given ABL_PROBE_PT_3_X can't be reached by the Z probe."
      #elif ABL_PROBE_PT_1_Y < MIN_PROBE_Y || ABL_PROBE_PT_1_Y > MAX_PROBE_Y
        #error "The given ABL_PROBE_PT_1_Y can't be reached by the Z probe."
      #elif ABL_PROBE_PT_2_Y < MIN_PROBE_Y || ABL_PROBE_PT_2_Y > MAX_PROBE_Y
        #error "The given ABL_PROBE_PT_2_Y can't be reached by the Z probe."
      #elif ABL_PROBE_PT_3_Y < MIN_PROBE_Y || ABL_PROBE_PT_3_Y > MAX_PROBE_Y
        #error "The given ABL_PROBE_PT_3_Y can't be reached by the Z probe."
      #endif 
    #endif
  #endif // !ABL_GRID
```

I don't think I like the extra clutter in the Configuration.h file because UBL has its own points defined for both the 3-Point probe and the UBL_MESH_NUM_X/Y_POINTS.    We would have to rework the SanityCheck.h and Conditionals_post.h files.  But it would seem we should combine that stuff into a common name.   And just have the user setup those common values like what was done to combine the
```cpp
   #define ENABLE_LEVELING_FADE_HEIGHT
```
for multiple bed leveling types.  But for now....    The above Cut & Paste's will get things compiling clean with UBL.     Oh!   One more suggestion.  If you feel like doing another global search and replace, probably we should change the name of the UBL data structure from blm to ubl.

**Comment by thinkyhead** [comment]
I patched according to your suggestions, and I think it should pass Travis CI now… I grouped the sanity checks for UBL together in their own block. Also the `PLANNER_LEVELING` flag is no longer set for UBL. If we move the UBL leveling maths into `planner.apply_leveling` and `planner.unapply_leveling` then it will automatically be integrated into much of the rest of Marlin. At some point you and I can go over the functions where leveling matters and make sure UBL is accounted for and fully integrated.

Still planning to make that "workflow" video — I'll try and do that tonight (Wednesday).

**Comment by thinkyhead** [comment]
I'm working on some ways to better visualize bed leveling grid. I wrote a script in OpenSCAD that will take a mesh and tesselate it with bilinear interpolation. I'm going to tweak the debug output so it's in a format friendly to OpenSCAD (and JavaScript, as it happens).
```js
measured_z = [
  [ -4.20, -4.13, -4.09, -4.03, -4.19 ],
  [ -4.16, -4.25, -4.27, -4.25, -4.08 ],
  [ -4.13, -4.26, -4.39, -4.31, -4.18 ],
  [ -4.09, -4.20, -4.26, -4.21, -4.18 ],
  [ -4.13, -3.99, -4.03, -4.06, -4.32 ]
];
```
Paste it into the OpenSCAD script (or web page with Javascript) and voila…
image

**Comment by Roxy-3D** [comment]
I have a few simple corrections to make to UBL.   But I'm having trouble doing them via a Pull Request.   The first one that needs to be made is to make it honor the 
```cpp
 // Gradually reduce leveling correction until a set height is reached,
  // at which point movement will be level to the machine's XY plane.
  // The height can be set with M420 Z<height>
  #define ENABLE_LEVELING_FADE_HEIGHT
```
option which can be done by doing the following and allowing the compiler to optimize out 'dead code'.   I don't know why anybody would not want this obviously needed and good feature, but in the interest of 'correctness', the option is present and UBL should honor it.
```cpp
      FORCE_INLINE float fade_scaling_factor_for_z(float current_z) {
      #ifndef ENABLE_LEVELING_FADE_HEIGHT 
           return 0.0;
      #endif
        if (last_specified_z == current_z)
          return fade_scaling_factor_for_current_height;
        last_specified_z = current_z;
        fade_scaling_factor_for_current_height =
          state.active && current_z < state.g29_correction_fade_height
          ? 1.0 - (current_z * state.g29_fade_height_multiplier)
          : 0.0;
        return fade_scaling_factor_for_current_height;
      }
    };
```
The problem is...  I can't make a repository right now with all the conflicts.   I fork Marlin, and I have to Sync because it is so far behind.   But I end up with a million conflicts and I think it is because this Pull Request is open.    I have a few more simple changes about as complicated as this one.  Would you mind if I get them in place via a 'Direct Commit' ?

**Comment by Tannoo** [comment]
image

Charted your data in Excel.

**Comment by thinkyhead** [comment]
The best way would be make a pull request targeted at this branch:
https://github.com/thinkyhead/Marlin/tree/rc_cleanup_ubl_1
…which I would then merge into this PR.

If you direct-commit them, you will have to conform to the old code, then I would have to pull them down, rebase this branch onto them, re-write them in the process…. It takes a lot more of my time and effort.

Let me finish patching this PR and merge it, then you can just make a normal PR against `RCBugFix`.

**Comment by Roxy-3D** [comment]
> If you direct-commit them, you will have to conform to the old code, then I would have to pull them down, rebase this branch onto them, re-write them in the process…. It takes a lot more of my time and effort.

> Let me finish patching this PR and merge it, then you can just make a normal PR against RCBugFix.

OK!   I don't want to make extra work for you!

**Comment by thinkyhead** [comment]
You may apply your changes now to `RCBugFix`. I'll be around, just going through some issues and PRs.

**Comment by Roxy-3D** [comment]
> You may apply your changes now to RCBugFix. I'll be around, just going through some issues and PRs.

THANK YOU!!!

Ooooops...   I posted this question in the wrong thread.   https://github.com/MarlinFirmware/Marlin/pull/6086

**Pull request merged**
