### PR TITLE
Add preheat for popular material

### PR DESCRIPTION
**Pull request by android444**
Add preheat for PET, RUBBER, HIPS, NYLON
Update all language and example configuration files.

sam_9591
sam_9592
sam_9593

### CODE REVIEW

**Comment by android444** [comment]
I want to add Polish font.
While the pull request will not merge, there is nothing I can do.

**Comment by Blue-Marlin** [comment]
Please look up and use the concept of branches.
Don't alter RCBugFix. Make feature branches for your projects.

**Comment by android444** [comment]
This is not my project!
I just want to increase the functionality.
This will be added?

**Comment by emartinez167** [comment]
@android444, Makaira is just explaining how git works... Have a read on how
branches work first, it's not that hard.

**Comment by android444** [comment]
Sorry.
I'm starting and many still do not know.
Will you help?


W dniu 2016-12-26 o 15:10, emartinez167 pisze:
> @android444, Makaira is just explaining how git works... Have a read 
> on how
> branches work first, it's not that hard.
>

**Comment by Blue-Marlin** [comment]
You have two litle sub projects.
a.) more materials.
b.) Polish font.
For both of them use new branches. Don't use RCBugFix for these. Doing so you have to wait for the merge of the one until you can work on the other.

Your current concept for adding more materials is not how __I__ like to see it.
__I__'d prefer configurable material names
And most of all a configurable amount of materials. As it is now it uses a fixed alount of memory - always, for all, even if you never need more then one material.

Your suggestion for the Polish font was much better, clean and complete. But likely it is not needed when we get #5541 (https://github.com/thinkyhead/Marlin/pull/20) to work.

**Comment by android444** [comment]
It's close.
I'll think about how to change it.

I would add Polish fonts.

**Comment by android444** [comment]
Now it is ok?

https://github.com/MarlinFirmware/Marlin/pull/5607


W dniu 2016-12-26 o 15:23, Makaira pisze:

**Pull request closed without merging**
