### PR TITLE
upgrade from (c) or (C) to ©

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Noticed Marlin has a mix of (c) and (C) for copyright, upgraded both to ©

### Benefits

less characters used, all uniform.

### CODE REVIEW

**Comment by ellensp** [comment]
Suspect case is why new file pins_CREALITY_V4210.h say Copyright (C)  2016,
it missed a mass update to 2020 due to the capital (C)

**Comment by X-Ryl669** [comment]
© requires a unicode-aware text editor to display (it bothers me when working on a terminal for example, since it doesn't display the character correctly). Why © is better than (C) here ?

**Comment by ellensp** [comment]
Configs already contain Unicode characters ů and š, maybe others, they are the ones I knew off top of head. 
 Its 2021, its time to move out of the stone age.

**Comment by X-Ryl669** [comment]
Currently, where I live, I can't move out further than 10km. I've no idea where's the iron age anymore.

**Comment by thinkyhead** [comment]
It has long been considered. But LICENSE preambles are customarily TXT and should be easily decomposable to TXT even in these futuristic times. The use of capital-C is left alone in contributed headers, but feel free to apply lower-case to Marlin headers.

**Pull request closed without merging**
