### PR TITLE
Remove PROMPT_INFO / PROMPT_GCODE_INFO

### PR DESCRIPTION
**Pull request by thinkyhead**
It is not clear that this is useful for the host. Please discuss.

@MarlinFirmware/host-software-team 

Reference: #13039

### CODE REVIEW

**Comment by foosel** [comment]
From my point of view (which is the point of view of the person who happened to have defined the prompt support protocol addition) it not only doesn't provide any use to the host (we already have the pause/resume/cancel action commands for that) but is actually abusing the *interactive* prompt feature as a notification vehicle, with dire consequences for UX (prompts are actually supposed to be blocking modals on the host...).

I've been drowning in tickets from users running into issues due to these messages.

**Comment by InsanityAutomation** [comment]
@foosel I think the main issue is that they dont have a close anywhere on the default dialog (we could add that on this side I suppose, though in the past I had asked if an X in the top right was possible to add since pressing esc isnt easy on a touchscreen or intuitive) and the cache issue returning some after they've been dismissed. My first vote would be to keep notifiers but add the close button. This is most useful on machines such as the Makergear which use Octo as the only display on the machine and when it pauses they have no indication why. I use this setup on a couple machines as well.

**Comment by foosel** [comment]
> I think the main issue is that they dont have a close anywhere on the default dialog

They were meant as ***interactive** dialogs completely controlled by the firmware*. The changes up there abused them as drive-by notification boxes, for messages for which we already had better suited notification mechanisms to boot. The prompt feature was never meant for that.

OctoPrint 1.3.12 will still add a close button in order to work around this abuse and improve UX for affected user, but this should really never have been used like this in the first place.

It sounds more like we might need a dedicated notification mechanism on top of prompt dialog functionality, which would be rendered not as blocking modals.

**Comment by InsanityAutomation** [comment]
> > I think the main issue is that they dont have a close anywhere on the default dialog
> 
> They were meant as _**interactive** dialogs completely controlled by the firmware_. The changes up there abused them as drive-by notification boxes, for messages for which we already had better suited notification mechanisms to boot. The prompt feature was never meant for that.
> 
> OctoPrint 1.3.12 will still add a close button in order to work around this abuse and improve UX for affected user, but this should really never have been used like this in the first place.
> 
> It sounds more like we might need a dedicated notification mechanism on top of prompt dialog functionality, which would be rendered not as blocking modals.

True, and I would have added a close on this end if the question about an x on the dialogue or anything was answered in the other thread suggesting to do so.

I also wouldn't term it an abuse of the dialogs if a better solution doesn't exist! As I was working with it as an exclusive display I solved a glaring problem the only way I could. If there were that many problems reported from users not knowing how to dismiss the dialogue an opened issue over here or even just answering the question on the original thread and we would have handled it on this side by adding a default close to each of them.

**Comment by foosel** [comment]
> if the question about an x on the dialogue or anything was answered in the other thread suggesting to do so.

What other thread? I'm not aware of that specific use ever having come up before this was merged, I only learned about it from tickets opened after the release of OctoPrint 1.3.11 on my repository. And I added a close button to the generated blocking modal as a consequence in 1.3.12.

And to be honest, I wasn't even sure if this originated in mainline Marlin or some forks until @thinkyhead was so kind to look into it last night after I mentioned it.

**Comment by InsanityAutomation** [comment]
In part it evolved from the summary comments on this post https://github.com/MarlinFirmware/Marlin/pull/12982#issuecomment-457164889

If you did a non blocking notification feature, this would be more doable https://github.com/MarlinFirmware/Marlin/pull/12982#issuecomment-457238335

Im fairly certain there was a thread discussing the close dialog that im not seeing immediately, but regardless its history. For host only machines, these dialogs are necessary but I can 
A. put them behind a separate enable for Notify messages so they can be turned on separate from other dialogs. 
B. Add a default close to all dialogs. 
C. Clear any stop type dialogs on certain events (print job timer started, sd print started, startup)

**Pull request merged**
