### PR TITLE
Add menu item Tune > Advance K

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Marlin's [K-factor tool](http://marlinfw.org/tools/lin_advance/k-factor.html) can get you near the correct range, but results can be heavily influenced/muddied by your first layer height.

I find it easier to live adjust the K-factor while printing a test cube (to check the corners for bulges/sharpness), but it was quite the deep dive to get through all the menus.

### Benefits

Dialing in your K-factor via LCD will be easier.

### Related Issues

None.

### CODE REVIEW

**Comment by Vertabreak** [comment]
sounds good to me ill have to check this out when i have time to.

**Comment by thisiskeithb** [comment]
> sounds good to me ill have to check this out when i have time to.

It’ll free up some of those custom menu items 🙂

**Comment by Vertabreak** [comment]
> > sounds good to me ill have to check this out when i have time to.
> 
> It’ll free up some of those custom menu items slightly_smiling_face

yea i keep managing to find more junk to cram in my custom menus to.

**Comment by Vertabreak** [comment]
IMG_20200108_141851
MVIMG_20200108_142453

looks good to me.

**Comment by rado79** [comment]
can not find this function in menu, what is the requirement?
flashed commit 2d820e62043260ee2ac32c8407389c67d7c2a7d4 right now - SKR 1.3

**Comment by Vertabreak** [comment]
Linear advance enabled and currently printing.

**Comment by thisiskeithb** [comment]
> can not find this function in menu, what is the requirement?

The Tune menu only shows up while printing.

**Comment by rado79** [comment]
thank you for the quick response
got it, i did not noticed the german translation "Vorschubfaktor" in menu

btw: there is no need to run a print - it shows after boot up
starting a print changes from default (0.00) to slicers start script setting (0.70)

**Pull request merged**
