### PR TITLE
Move pins* and language* to subfolders

### PR DESCRIPTION
**Pull request by thinkyhead**
- Take advantage of Arduino’s behavior of adding local “libraries” folder subpaths referenced in the main sketch file to the include paths.

### CODE REVIEW

**Comment by CONSULitAS** [comment]
@thinkyhead Nice! Why did you close it?

**Comment by thinkyhead** [comment]
I'm trying to solve an issue with the Makefile. I can't get it to work. If that can be solved then we're golden. (File copying might be an acceptable patch…?) Then I will re--open it.

**Comment by thinkyhead** [comment]
Travis CI won't build this with certain configurations. I think it's a problem with the Makefile, but I can't even get `make` to work without throwing an error. Anyone else want to have a crack at this? It will be a good improvement to be able to start moving parts of Marlin into subfolders!

```
$ make all
  make: *** No rule to make target `applet/wiring.o', needed by `applet/Marlin.elf'.  Stop.
```

**Comment by thinkyhead** [comment]
~~Thought this could work, but it just doesn't.~~

Can we _require_ Arduino 1.5.8 and later? It's supposed to work with recent versions, so giving it a test now...

**Comment by thinkyhead** [comment]
Argh, can't get this to work at all now. Seemed like it was working once....

**Comment by nophead** [comment]
Have you tried

#include "libraries/MarlinLanguage/MarlinLanguage.h"

**Comment by nophead** [comment]
Hmm, code quoting doesn't work in posts created by email.

**Comment by thinkyhead** [comment]
@nophead I've tried a lot of things, and nothing works. The Makefile provides workarounds (copying files to the sketch or sketchbook folder), but the IDE doesn't respect paths in `#include` at all.

**Comment by alexborro** [comment]
What if the Makefile copy the files from the original libraries folder to
the compilation tmp folder? As far as I know, the IDE/Makefile do not
compile inside original folder, right?

Cheers.

Alex.

2015-03-03 1:39 GMT-03:00 Scott Lahteine notifications@github.com:

> I've tried a lot of things, and nothing works. The Makefile provides
> workarounds (copying files to the sketch or sketchbook folder), but the IDE
> doesn't respect paths in #include at all.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/pull/1537#issuecomment-76886079
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by thinkyhead** [comment]
@alexborro Copying is the required trick used by the Makefile for some other stuff. But Marlin needs to be able to compile from the IDE. It's very odd, because I _believed_ I had it working from the IDE, but now I can't get it to compile. If someone else wants to keep playing around with this, good luck, but it looks like the IDE remains pretty dumb.

**Comment by ivan-galvez** [comment]
@thinkyhead The main problem you are facing here is that it's nearly impossible to properly use a Makefile, if you want to keep compatibility with Arduino IDE.
Arduino doesn't even allow using subfolders, thus everything must be in the main directory. Any tricks you try, such as copying files, might be even more problematic or introduce new issues.
IMHO, there's no point on maintaining out-of-the-box support for Arduino IDE, it restricts too much. Any IDE out there is much better, and I'm pretty sure that most developers/users would be using the Makefile.

**Comment by alexborro** [comment]
I see no need for Arduino IDE.

I think it is important to pick up a free IDE/Compiler/Flasher, no matter
what. Arduino IDE is, at least, prehistoric.

Most users - like me - have the Arduino IDE just to compile and upload the
printer firmware.. They will probably don't care if Marlin uses a different
one as long as we keep compatibility with current boards and the process
simple, like: Download, setup configuration.h, choose the target board,
COMM port and click compile/upload.

We can even have just a BAT file to run the compiler (using the makefile)
and flasher..

What do you guys think about it? Let's open a new thread to discuss about
it?

Cheers.

Alex.
Em 11/03/2015 07:54, "Iván Gálvez Junquera" notifications@github.com
escreveu:

**Comment by ivan-galvez** [comment]
Please not a BAT (Windows only) file!
make && make upload  is more than enough.

**Comment by alexborro** [comment]
Ivan, for a single user, the command: "make && make upload" makes no sense.
We can put such command inside a bat file named: "Click here to upload.bat".
You will always have the option to run the make by youself.
And that is not the point.

I think we can discuss the idea of adopting a new IDE and the use of
makefiles.

Cheers.

Alex.

2015-03-11 9:43 GMT-03:00 Iván Gálvez Junquera notifications@github.com:

> Please not a BAT (Windows only) file!
> make && make upload is more than enough.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/pull/1537#issuecomment-78255550
> .

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Pull request closed without merging**
