### PR TITLE
Add NOZZLE_AS_PROBE option to disable limits on probe point

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Allows negative bed offsets for probing on Taz6 and similar machines.

Posting this for some testing and feedback as I have not had time to migrate a lulzbot config in and run it on mine.

### CODE REVIEW

**Comment by thinkyhead** [comment]
The name of the option is too vague. Any probe that has been assigned a positive `M851 Z` value can usually be presumed to be "the nozzle," some mechanism in the bed, or sensorless probing.

If the aim is to describe a probe that makes electrical contact at 4 corners of the bed, maybe there is a name that Lulzbot uses for this which we can apply to the naming of the option…?

Note that it is unusual to make the Probe Bounds dependent on the Probe Type. If someone wants to probe piezos or electrical contacts mounted in the bed corners, it would be better to patch existing options as needed so that they can get the desired probing behavior using `FIX_MOUNTED_PROBE`, which can handle XY probe offsets of 0,0.

**Comment by InsanityAutomation** [comment]
@marcio-cp Figured id ping you here to take a peak when you have a minute

**Comment by TechsavvyCNC** [comment]
Lulzbot uses the name LULZBOT_FIXED_MOUNTED_PROBE I believe.  Marcio found a workaround to set probe points manually on his fork of Marlin.

https://github.com/marciot/drunken-octopus-marlin/commit/054482397734c3d746fe104a4bdb585c5ff063a8

**Comment by InsanityAutomation** [comment]
> Lulzbot uses the name LULZBOT_FIXED_MOUNTED_PROBE I believe. Marcio found a workaround to set probe points manually on his fork of Marlin.
> 
> [marciot@0544823](https://github.com/marciot/drunken-octopus-marlin/commit/054482397734c3d746fe104a4bdb585c5ff063a8)

We discussed it on discord. Fixed probe is generic where this is intended to be a subset of it.

**Comment by boelle** [comment]
NOZZLE_AS_PROBE seems pretty clear to me

**Comment by TechsavvyCNC** [comment]
Does this still need testing?  I can create a Taz 6 config and test it.

**Comment by InsanityAutomation** [comment]
Yeah, I'll get it rebased today

**Comment by TechsavvyCNC** [comment]
I built a config for my Taz 6 but I just need help defining the probe points. 
[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/3928973/Configuration.zip)
 The probe positions for the Taz 6 are
            [STANDARD_LEFT_PROBE_BED_POSITION             = -10
            STANDARD_RIGHT_PROBE_BED_POSITION            = 288
            STANDARD_BACK_PROBE_BED_POSITION             = 291
            STANDARD_FRONT_PROBE_BED_POSITION           =-9

**Comment by TechsavvyCNC** [comment]
Wouldn't it just be easier to do what @marciot did to fix this.  https://github.com/marciot/drunken-octopus-marlin/commit/054482397734c3d746fe104a4bdb585c5ff063a8

Just keep the name as Nozzle_As_Probe but the be able to define the exact probe points.

**Comment by TechsavvyCNC** [comment]
I've created a config for my Taz 6 but It won't compile.  I keep getting an error saying "Z_MIN_PROBE_PIN must be defined if Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN is not enabled.
Even though i have a z min probe pin defined.  Here are my config files
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/3933604/Config.zip)

@InsanityAutomation If you could take a look at them.  Thanks

**Comment by TechsavvyCNC** [comment]
@InsanityAutomation I figured out the issue.  I had to also define Fix_Mounted_Probe.  I thought it would define it automatically if Probe_as_Nozzle was defined.  I'll be testing it out on my printer in the morning.

**Comment by TechsavvyCNC** [comment]
@InsanityAutomation I've tried this pull request and it still wont probe out of the bed area.  I've enabled G29 debug and it goes to X280 and Y0 instead of the correct spot.

**Comment by InsanityAutomation** [comment]
Rebased and updated, Working on my Taz 6 now. Im not sure what Marcio is using these days (@marciot or @marcio-cp ) but unless @thinkyhead still wants to rename this, should be good to go. Also tested on 2 other machines to ensure other functionality wasnt affected.

**Comment by TechsavvyCNC** [comment]
I think the name is good.  I'm gonna test on my Taz 6 in a bit.  On Marcio's marlin fork he just used a workaround in G29.cpp to be able to probe the exact spots.

**Comment by TechsavvyCNC** [comment]
Is this going to get pushed into bugfix-2.0.x?

**Comment by InsanityAutomation** [comment]
I'm sure Scott will get around to it soon enough. With the holidays I'm sure he's somewhat split at the moment.

**Pull request merged**
