### PR TITLE
[2.0.x] SLIM_LCD_MENUS option

### PR DESCRIPTION
**Pull request by thinkyhead**
Based on #8947

Saving Space for 1284P (and other small) CPUs. Saves about 8K of memory. More to come.

[Concise Diff](8978/files?w=1)

### CODE REVIEW

**Comment by fiveangle** [comment]
Is this supposed to disable X/Y/Z moment menus entirely ?  Those are fundemental to having an LCD.

**Comment by thinkyhead** [comment]
If using a `DELTA` the Move Axis item is hidden until the machine has been homed.

**Comment by fiveangle** [comment]
Using Cartesian.  However, it does show movement menus after homing.  I thought for sure this used to work so that it would allow movement in the positive direction, but not negative, even before homing (assuming power-on location is origin) ?

Not critical, but the menu items shouldn't really be hidden.  If they are non-functional, they should throw error or even silently not work at worst.  A moving target UI simply confounds.  A human UI for machine control should not be designed as a state machine.

**Comment by thinkyhead** [comment]
> A moving target UI simply confounds.

Please submit your suggested improvements as a PR.

> Using Cartesian. However, it **does** show movement menus after homing. I thought for sure this used to work so that it would allow movement in the positive direction, but not negative, even before homing (assuming power-on location is origin) ?

**Move Axis** is always available in the **Prepare** menu on a Cartesian. No homing required.

```cpp
    #if ENABLED(DELTA)
      if (axis_homed[X_AXIS] && axis_homed[Y_AXIS] && axis_homed[Z_AXIS])
    #endif
        MENU_ITEM(submenu, MSG_MOVE_AXIS, lcd_move_menu);
```

**Comment by fiveangle** [comment]
So I should treat this as a bug then ?  https://youtu.be/Ef8ETqpzPTg

**Comment by thinkyhead** [comment]
I see. So "Auto Home" is actually there, but it causes a 'back' action. Somehow I missed that fact in your earlier descriptions.

**Comment by thinkyhead** [comment]
I see that all sub-menus at that level do the same thing. So, it's a more general bug. Should be easy to find and fix. I'll have a patch shortly.

**Comment by thinkyhead** [comment]
@fiveangle — So far I'm unable to reproduce the issue when building the current code. I thought I had seen the behavior once, but after re-navigating to the Move Axis menu it ceased to occur, even with later reboots.

Re-flash with the latest `bugfix-1.1.x` and see if the issue still exists, then we can look further.

**Pull request merged**
