### PR TITLE
Unknown gcode handling

### PR DESCRIPTION
**Pull request by vyacheslav-shubin**
### Description
Custom handling unknown g-code

### Benefits
Provide make custom gcode handling inside extui modules

```cpp
        #define HANDLE_UNKNOWN_GCODE

	uint8_t on_unknown_gcode(const char * gcode) {
	    SERIAL_ECHOLNPAIR("UNK:", gcode);
            return 1;
	}
	
       unknownGcodeHandler = on_unknown_gcode;
```
```
Terminal ready
M3000
UNK:M3000
ok
M50
UNK:M50
ok
M1
echo:busy: paused for user
echo:busy: paused for user
ok
```

### CODE REVIEW

**Comment by thinkyhead** [comment]
Why wouldn't we just implement G-codes as-needed? I'm not convinced this is needed at all.

**Comment by vyacheslav-shubin** [comment]
If firmware support very specific hardware set, code controlled them not need for all.
For example:
```cpp
      #if ENABLED(WIFI_CUSTOM_COMMAND)
        if (wifi_custom_command(parser.command_ptr)) break;
      #endif
```

The proposed changes make this mechanism more versatile for external UI extensions.

Now i can use M117, and ExtUI::onStatusChanged event, if prepare the command in a certain way;
M117 MARKER M## -- custom commands.

As a more radical idea, interceptor can be made before main gcode case, that can use as g-code overrider.
For example, gcode for pausing have a ui depend release.

**Comment by thinkyhead** [comment]
Under what circumstances will a sub-component of Marlin need to change `unknownGcodeHandler` at run-time? Unless that functionality is very much needed, there should simply be a standard "unknown G-code handler" localized someplace. Marlin is very much a static application, not a dynamic one.

**Comment by Sebazzz** [comment]
My guess is that @vyacheslav-shubin needs ExtUI-like extensibility for gcode.

**Comment by vyacheslav-shubin** [comment]
Yes @Sebazzz you right, and the best feature is not  extensibility, but overriding and extensibility:
if (!gcode_override()) {
   if (!std_gcode_handler())
      handle_unknown_gcode();
}
..if (!no_ok.....

**Comment by Sebazzz** [comment]
From a functional perspective there is the risk that the gcode flavour isn't Marlin anymore, when you're overriding gcodes. Even for handling unknown gcodes, one could argue that this is only possible for new command letters (so not M, N, G or D).

**Comment by vyacheslav-shubin** [comment]
@Sebazzz
The redefinition feature allows new functionality to be introduced without taking into account the current implementation, which allows re-growing variadic algorithms, including gradually enabling runtime options. It's good for project development - to be able to quickly switch unambiguous implementations

**Pull request closed without merging**
