### PR TITLE
320x240 LCD portrait mode UI

### PR DESCRIPTION
**Pull request by alexgrach**
### Description

320x240 LCD portrait mode UI.

### Requirements

MKS Robin Nano, MKS Robin TFT 2,8"

### Benefits

No additional resolution.

```cp
#if TFT_ROTATION == TFT_ROTATE_90 || TFT_ROTATION == TFT_ROTATE_90_MIRROR_X \
  || TFT_ROTATION == TFT_ROTATE_90_MIRROR_Y || TFT_ROTATION == TFT_ROTATE_270 \
  || TFT_ROTATION == TFT_ROTATE_270_MIRROR_X || TFT_ROTATION == TFT_ROTATE_270_MIRROR_Y
```
does not work correctly at `Conditionals_LCD.h` but works at `tft.h`.

`#define TFT_COLOR_UI_PORTRAIT` is used for now.

### Configurations

[Configuration_kp3s.zip](https://github.com/MarlinFirmware/Marlin/files/10367108/Configuration_kp3s.zip)

### Related Issues
#25191

### CODE REVIEW

**Comment by thinkyhead** [comment]
This is much cleaner. Maybe we should use `TFT_ROTATION` as the basis to display the screen as landscape or portrait. That assumes that the 240x320 display has to be initialized to draw in portrait mode versus a native landscape mode, meaning it should also be able to do upside-down orientations also. If that is the case with this display then we can use `TFT_ROTATION` to set up both the display init and choose whether to set a `TFT_COLOR_UI_PORTRAIT` flag. However, if the native resolution of the display is 240x320, then we can just add a top level `TFT_RES_240x320` option and set a `TFT_COLOR_UI_PORTRAIT` flag based on that instead.

**Comment by thinkyhead** [comment]
> does not work correctly at `Conditionals_LCD.h` but works at `tft.h`.

Files that need to check the value of `TFT_ROTATION` will need to define the items defined in `tft_io.h` such as `TFT_NO_ROTATION` or move these defines where they are needed for evaluation. Alternatively, the value of `TFT_ROTATION` can be tested using dummy values, as in:
```cpp
#define _CMP_TFT_NO_ROTATION 0x01
#define _CMP_TFT_ROTATE_90 0x90
#define _CMP_TFT_ROTATE_180 0x180
// etc.
#define _ISROT(N) || (_CAT(_CMP_, TFT_ROTATION) == _CAT(_CMP_, N))
#define ISROT(V...) (0 MAP(_ISROT, V))

#ifndef TFT_ROTATION
  #define TFT_ROTATION TFT_NO_ROTATION
#endif

#if ISROT(TFT_NO_ROTATION)
  #warning "TFT no rotation is selected."
#elif ISROT(TFT_ROTATE_90, TFT_ROTATE_180)
  #warning "TFT rotation is either 90 or 180."
#endif

#undef _CMP_TFT_NO_ROTATION
#undef _CMP_TFT_ROTATE_90
#undef _CMP_TFT_ROTATE_180
```

**Comment by thinkyhead** [comment]
The PR at alexgrach/Marlin#2 adds a test to set the `TFT_COLOR_UI_PORTRAIT` flag based on `TFT_ROTATION`. It's not exactly pretty, but it should work. Please merge that PR and then afterward you can make any needed adjustments and push new commits to update this PR.

**Comment by alexgrach** [comment]
Should I return TFT_RES_240x320 definition?

**Comment by thinkyhead** [comment]
> Should I return `TFT_RES_240x320` definition?

The consensus from other contributors was to have a single screen size but use `TFT_ROTATION` to pick the portrait orientation, so that is how this is currently implemented.

**Comment by alexgrach** [comment]
Does not set TFT_COLOR_UI_PORTRAIT
rot

**Comment by alexgrach** [comment]
Setting the TFT_COLOR_UI_PORTRAIT flag works correctly.

**Comment by alexgrach** [comment]
PR does not include last changes to tft_io.h and Conditionals_LCD.h

**Pull request merged**
