### PR TITLE
Fix broken LPC176x build

### PR DESCRIPTION
**Pull request by tharts**
### Requirements

Building for platform LPC1768, BOARD_MKS_SBASE (might also affect other LPC176x based boards)

### Description

After checking out the latest bugfix-2.0.x commits building MarlinFW for board MKS_SBASE failed with a compile error.
Analyzing led to the breaking commit 3583e2b and that the changed order of the AUTO_BED_LEVELING_UBL block in ultralcd_common_HD44780.h was responsible for it.

### Benefits

Fixes the failing build for platforms based on LPC176x (MKS_SBASE, SMOOTHIEBOARD, etc.)

### Related Issues

none

### CODE REVIEW

**Comment by tharts** [comment]
The commit message referes to the last working commit before the build broke giving the error message:
```
.piolibdeps\30aa480\LiquidTWI2.cpp:28:10: fatal error: WProgram.h: No such file or directory
 
******************************************************************
* Looking for WProgram.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:WProgram.h"
* Web  > https://platformio.org/lib/search?query=header:WProgram.h
*
******************************************************************
 
#include "WProgram.h"
^~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\LPC1768\libe77\30aa480\LiquidTWI2.cpp.o] Error 1
 [ERROR] Took 94.90 seconds
```

**Comment by Geend** [comment]
I just tried to build marlin for my smoothieboard. Unfortunately it still fails when buildung the bugfix-2.0.x branch from this repository. It does not compile with the same error message you described.
When I checkout your fork of marlin and build there it does compile.
So maybe the merge did not work as intended?

**Comment by thinkyhead** [comment]
Please ZIP up your configuration files so they can be tested.

**Comment by Geend** [comment]
I did not change any configuration other than setting the MOTHERBOARD to BOARD_SMOOTHIEBOARD in Configruation.h and change the env_default to LPC1769 in platformio.ini.
Which files do you need exactly?

**Comment by thinkyhead** [comment]
If that's all you changed, then hold on while I test the build.

**Comment by thinkyhead** [comment]
I see an error, but it appears totally unrelated to our recent patches:
```
.piolibdeps/30aa480/LiquidTWI2.cpp:28:10: fatal error: WProgram.h: No such file or directory
```

**Comment by p3p** [comment]
I think the reorganisation of headers has made the PlatformIO LDF pick up that library as required now, I'l put a PR in turning it off and just include the needed libs directly. Having to use the chain+ was seriously slowing down the test times anyway as it has to evaluate preprocessor before checking headers.

**Comment by thinkyhead** [comment]
Sounds like a plan!

**Comment by tharts** [comment]
It's somewhat puzzeling. As soon as I reinsert the following lines back into Marlin\src\lcd\HD44780\ultralcd_common_HD44780.h the code compiles successful.
Taking them out leads to the above mentioned error again.

``` 
#if ENABLED(AUTO_BED_LEVELING_UBL)
  #include "../../feature/bedlevel/ubl/ubl.h"

  #if HAS_LCD_MENU
    #define ULTRA_X_PIXELS_PER_CHAR    5
    #define ULTRA_Y_PIXELS_PER_CHAR    8
    #define ULTRA_COLUMNS_FOR_MESH_MAP 7
    #define ULTRA_ROWS_FOR_MESH_MAP    4

    #define N_USER_CHARS    8

    #define TOP_LEFT      _BV(0)
    #define TOP_RIGHT     _BV(1)
    #define LOWER_LEFT    _BV(2)
    #define LOWER_RIGHT   _BV(3)
  #endif
#endif
```

I didn't change more than only platform to LPC1768 and board to MKS_SBASE. 
So AUTO_BED_LEVELING_UBL is commented in config.h and therefore the lines shouldn't be of any effect when compiling the code. 
But they do. Does anybody know why?
I hope someone has a clue about it.

**Comment by thinkyhead** [comment]
Grab the latest `bugfix-2.0.x` and try it again as-is. If you have any compile errors, post your `Configuration.h` and `Configuration_adv.h` as a ZIP file and we'll see what's up.

**Comment by Geend** [comment]
It compiles now for platform LPC1769 and board BOARD_SMOOTHIEBOARD. Didn't have time to flash and test it though.

**Comment by tharts** [comment]
Working again for me, too. Thanks :-)

**Pull request merged**
