### PR TITLE
Allow Zero Endstops (e.g., for CNC)

### PR DESCRIPTION
**Pull request by deirdreobyrne**
### Description

Some machines (e.g. cheap Chinese CNC machines) come without endstops. Such machines cannot be homed, and so need to be considered to always be in a known and trusted position. It is up to the user to ensure that there are no toolhead crashes.

My test for a machine without endstops is that none of `USE_[XYZ]MIN_PLUG` or `USE_[XYZ]MAX_PLUG` are set.

The only thing I'm not sure of is in the `motion.cpp set_axis_never_homed(...)` implementation. There is a test for I2C position encoders. I cannot see how a machine cheap enough to not have endstops would ever have position encoders. Should this combination throw an error in SanityCheck.h?

### Benefits

Marlin now becomes useful on the cheapest of machines that have no endstops!

### Postscript

(p.s. my first ever PR - feedback welcome)

[Concise Diff](21120/files?w=1)

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for the submission. I've cleaned it up and extended it a bit, but haven't evaluated the question of encoders. However, since they are somewhat independent of each other, we should allow for something that has encoders but no endstops.

**Comment by deirdreobyrne** [comment]
I've just noticed that there are tests in the code for the toolhead being over the bed, with different behaviour (e.g. no skew correction) when the toolhead moves off the edge of the bed. Makes full sense in the context of a 3D printer, but I **think** in the context of a CNC that has no endstops (and hence the coordinates that correspond to "over the bed" are flexible) those tests should be bypassed. Going to look at it closer later.

**Comment by deirdreobyrne** [comment]
Next step - change levelling, because on a CNC you don't want to level the entire bed - you only want to level that part of the bed the work is on. (My particular use case is CNC PCB milling - the PCB surface is raised off the bed by (at least) the thickness of the PCB, and that is the only part that needs levelling).

**Comment by deirdreobyrne** [comment]
Currently working on implementing G68 and G69 (rotated co-ordinate systems). Not sure how I should create another PR when its ready?

My use case is PCB milling. With double-sided milling, it's important, and difficult, to get the second side of the PCB in the same orientation that it had when the first side was milled. An answer is to drill fiducials in the PCB, and use them to determine the actual orientation after flipping to the second side.

**Comment by thinkyhead** [comment]
> Not sure how I should create another PR when [it's] ready?

For simplicity, you'll want to wait for this to be merged, and then build on top of `bugfix-2.0.x` after that. Otherwise you'd have to do some git tricks to get back in sync.

**Comment by deirdreobyrne** [comment]
Cool - thanks! Is there anything I should be doing to help matters along? (I'm new to this. I've done tests, and it all seems OK to my eye. I've tested leveling, and it also seems fine).

**Pull request merged**
