### PR TITLE
Custom user commands menu

### PR DESCRIPTION
**Pull request by thinkyhead**
Bugfix and cleanup of #6875

- Shorten and simplify config options with fewer conditionals
- Allow `USER_SCRIPT_DONE` to be left undefined
- Add `CUSTOM_USER_MENUS` to the Travis CI test

### CODE REVIEW

**Comment by Tannoo** [comment]
Wouldn't it save memory by not having the USER_GCODEs defined if not needed?

**Comment by thinkyhead** [comment]
I dropped the conditionals because they add noise, as much as anything. By grouping these in sets of 2 lines separated by a blank line, I think it will be clear that they can/should be commented out in sets of 2.

1. These are samples, so we expect users will immediately edit them.
1. Users will grok that they should comment these in/out in sets of two.
1. Commenting out _either one_ is all that's required to suppress the menu item.
1. No PROGMEM is ever used unless a menu item is generated.
1. A little more memory is used by the C++ preprocessor, but it's not significant.

**Comment by Tannoo** [comment]
Okay, but why do it sets?
`#if defined(USER_DESC_1) && defined(USER_GCODE_1)`

This would not suffice?
`#if defined(USER_DESC_1)`

It would eliminate the user complaints.

**Comment by Roxy-3D** [comment]
Yes, that would suffice.   But they are matched pairs.   If either of the matched pair is missing, it makes sense to not do anything.

**Pull request merged**
