### PR TITLE
add SPINDLE_CONTROL_M106_M107

### PR DESCRIPTION
**Pull request by ruediste**
### Description
Map M106/M107 to M3/M5. This allows for printers with a laser
module connected to the fan header to use the LASER_POWER_INLINE by configuring the
fan pin as spindle PWM pin and still used unmodified G code.

### CODE REVIEW

**Comment by thinkyhead** [comment]
See any issues here?
```cpp
      #if ENABLED(SPINDLE_CONTROL_M106_M107)
        case 106: M3_M4(false); break;                            // M106: Turn ON Laser | Spindle (clockwise), set Power | Speed
        case 107: M5(); break;                                    // M107: Turn OFF Laser | Spindle
      #endif

      #if HAS_FAN
        case 106: M106(); break;                                  // M106: Fan On
        case 107: M107(); break;                                  // M107: Fan Off
      #endif
```

**Comment by thinkyhead** [comment]
Essentially, this makes `M106` / `M107` into aliases for `M3` / `M5` and it doesn't require much more explanation. One caveat is that it modifies the parameters to `M106` / `M107` so they may do things that the usual `M106` / `M107` don't do, depending on enabled options. Other considerations:

- The `M3`-`M5` commands only exist for `HAS_CUTTER` so the new option should be a sub-option of `EITHER(SPINDLE_FEATURE, LASER_FEATURE)`.
- If there is any fan on the machine, the compile will fail, as there will be two `case 106 / 107:` lines in `gcode.cpp`.
- Additional sanity-check is needed to assert the correct conditions for the new option.

**Comment by thisiskeithb** [comment]
> If there is any fan on the machine, the compile will fail

Hope you’re not using a PWM/controllable controller fan. Even newer Ender-3 boards have three controllable fan headers these days.

**Comment by descipher** [comment]
Unfortunately this PR does not deliver the stated function. When cutter_mode set to STANDARD (default) this will simply not work even with LASER_POWER_INLINE. Inline power mode require G1 Xn Yn Sn commands thus the GCODE would require "Modifications"

It could potentially work with LASER_POWER_SYNC enabled which allows M3/M5 power sets to work inline. (Not tested here as far as I can see.)

M106/M107 are already inline to the planner so I just cant see a benefit yet. Has this been tested and if so with what parameters?

**Pull request closed without merging**
