### PR TITLE
Add devcontainer for vscode

### PR DESCRIPTION
**Pull request by willis7**
This commit adds a devcontainer for simplifying building Marlin with VSCode.
The official documentation for devcontainers can be found here:
https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-development-container

### Description

Initially, this is a request for comments. While this PR does successfully compile Marlin, I have not exhaustively tested it (for example, an upload). This quality of life change will provide users of VSCode with a fully-fledged environment to compile Marlin. It will install all the relevant extensions into VSCode, and it provides a container with all OS-level libraries to compile Marlin. Because this all happens inside Docker, the user's machine remains unchanged, thus avoiding issues that can occur as a result of out of date dependencies.

From VSCode the user just needs to say open this folder in a dev container and VSCode does the rest.

I'm keen to get thoughts before committing more time to this endeavour.

### Benefits

This PR makes life easier for people wanting to build Marlin by providing them with an OS-agnostic solution based on VSCode.

It's also worth noting that [Github codespaces](https://github.com/features/codespaces) can use the dev container mechanism meaning users can compile their Marlin changes directly in Github. Similarly, dev containers are great for CI systems.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Note that if "Auto Build Marlin" were to be specified as the only dependency (plus Editorconfig), PlatformIO IDE and all of its dependencies would also be covered because ABM specifies PlatformIO IDE as its dependency, and PlatformIO IDE also specifies all its dependencies.

I would like to remove the README and move its contents to the Documentation website as an addition to the [Install Marlin with VSCode](https://marlinfw.org/docs/basics/install_platformio_vscode.html) page.

**Comment by willis7** [comment]
I have been able to successfully compile the firmware in the container and there is an option in vscode to download the firmware.bin with a simple right click. However, I have been unable to use the "upload" feature of marlin auto build. I will keep chipping away at this.

**Comment by rhapsodyv** [comment]
This seems a good addition, but note that PIO plug-in for vscode do everything by itself.

It can even install a portable python distribution and all packages in the right version.

In theory, nothing in os level is required to run vscode with pio and to build marlin.

**Comment by willis7** [comment]
> 
> 
> This seems a good addition, but note that PIO plug-in for vscode do everything by itself.
> 
> It can even install a portable python distribution and all packages in the right version.
> 
> In theory, nothing in os level is required to run vscode with pio and to build marlin.

You're quite right. 

There are some additional benefits as I mention in the first post - primarily that the developers can have a few more guarantees if they use the same devcontainer for development as they do for their CI build. THe environment is declaratively defined thus repeatable.

The other benefit is future-gazing a little. Tools like CodeSpaces and competitors will make it possible to develop using only the web.  This would make validating small changes very easy on a lightweight device like a tablet/phone or low powered PC. Not everyone's cup of tea admittedly.

**Comment by mwinters-stuff** [comment]
To be able to upload to connected printers, would require connecting the device. This can be done in the .devcontainer.json

Eg.
	"runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined", "--device=/dev/bus/usb", "--device=/dev/ttyACM0"],

This is an excerpt from my raspberry pi pico dev container.
https://github.com/mwinters-stuff/vscode-devcontainer-raspberrypi-pico

**Pull request merged**
