### PR TITLE
Update language_da.h

### PR DESCRIPTION
**Pull request by DavidBjerreBjoerklund**
Added translation mentioned in issue #3351:
Homing would be best tranlated homing, or "Kører til udgangsposition".

``` cpp
#define MSG_SET_HOME_OFFSETS
#define MSG_LEVEL_BED_HOMING
#define MSG_LEVEL_BED_WAITING 
#define MSG_LEVEL_BED_DONE
#define MSG_LEVEL_BED_CANCEL 
#define MSG_HOME_OFFSETS_APPLIED
```

### CODE REVIEW

**Comment by thinkyhead** [comment]
Unfortunately, we need to keep these strings at 16 characters or less. We have even fewer for menu sub-items. Can you update this to make sure all strings fit within those limits and fit on a 16-character-wide LCD?

**Comment by jbrazio** [comment]
@thinkyhead see my suggestion at #3420.

**Comment by thinkyhead** [comment]
In future perhaps we can have the longer LCD messages scroll. But that will only work while the machine is alive, so errors that call `kill()` won't be able to use that feature.

**Comment by thinkyhead** [comment]
I will merge this for now, with caveats, and we can try to deal with all the over-long strings soon.

**Comment by jbrazio** [comment]
Thanks it will be easier to deal with this in bulk as for Danish we had three pending PR.

> In future perhaps we can have the longer LCD messages scroll

I was thinking about this also.
Languages other than English are really verbose.. if you knew Portuguese (as an example) you would see the translations as sub-optimal.

**Comment by thinkyhead** [comment]
We'll have to start using slang and nicknames. "Err: Paco Rabanne!" It's the same in every language.

**Comment by jbrazio** [comment]
"Err: Paco Rabanne!" has 18 chars ! :-P

**Comment by thinkyhead** [comment]
Well Paco always was a bad boy.

**Pull request merged**
