### PR TITLE
MKS TFT add scroll long filename

### PR DESCRIPTION
**Pull request by Zlopi**
### Description
MKS TFT add scroll long filename

### Requirements
MKS TFT or TFT GENERIC

### CODE REVIEW

**Comment by Zlopi** [comment]
https://user-images.githubusercontent.com/13034887/139039691-9c099055-ae7d-46e0-8692-eb29e5670ac2.mp4

**Comment by Zlopi** [comment]
My board is MKS Robin Nano v1.2 and MKS Robin TFT24(FSMC)

**Comment by thinkyhead** [comment]
Too bad we can't do nice smooth scrolling, especially when a proportional font is involved. Maybe at a later time we can determine how to render the name to an off-screen buffer and then draw it with a pixel offset.

**Comment by thisiskeithb** [comment]
This works on any TFT running `TFT_COLOR_UI` and isn't specific to MKS LCDs.

**Pull request merged**
