### PR TITLE
Consolidate PSU_CONTROL into features/power, add M80 T for toggling PSU

### LINKED ISSUE #21014: Toggle PSU
add code to the M80 command to allow a Togging of the psu state, M80 S reports the state, how about M80 T toggles it. My code adjustment for M80_M81.cpp is below.  I have implemented this change on my printer and the code seems to be working great. This makes it simpler to add a single button input to control the state of the psu with things like OctoPrint. 

#if ENABLED(PSU_CONTROL)

  #if ENABLED(AUTO_POWER_CONTROL)
    #include "../../feature/power.h"
  #endif

  // Could be moved to a feature, but this is all the data
  bool powersupply_on;

  #if HAS_TRINAMIC
    #include "../../feature/tmc_util.h"
  #endif

  /**
   * M80   : Turn on the Power Supply
   * M80 S : Report the current state and exit
   */
  void GcodeSuite::M80() {

    // S: Report the current power supply state and exit
    if (parser.seen('S')) {
      serialprintPGM(powersupply_on ? PSTR("PS:1\n") : PSTR("PS:0\n"));
      return;
    }
    
    ///////////////////////////////////////////////////////////////////////
    // T: Toggles the state of the power supply
    if (parser.seen('T') && powersupply_on) {
      GcodeSuite::M81();
      return;
    }
    ///////////////////////////////////////////////////////////////////////
    else
      PSU_ON();

    /**
     * If you have a switch on suicide pin, this is useful
     * if you want to start another print with suicide feature after
     * a print without suicide...
     */
    #if HAS_SUICIDE
      OUT_WRITE(SUICIDE_PIN, !SUICIDE_PIN_INVERTING);
    #endif

    #if DISABLED(AUTO_POWER_CONTROL)
      delay(PSU_POWERUP_DELAY); // Wait for power to settle
      restore_stepper_drivers();
    #endif

    #if HAS_LCD_MENU
      ui.reset_status();
    #endif
  }

#endif // ENABLED(PSU_CONTROL)

### PR DESCRIPTION
**Pull request by slowbro**
### Description

What started as fulfilling FR #21014 turned into some cleanup of the power-related code. I thank the `// Could be moved to a feature, but this is all the data` comment for my inspiration...

### Requirements

`PSU_CONTROL` enabled.

### Benefits

Moves global `powersupply_on` out of MarlinCore and into features/power, and replaces calls to `PSU_ON()`/`PSU_OFF()` with `powerManager.power_on()`/`powerManager.powerOff()` where applicable. Also adds an initialization function for the feature like other features have, which is called on startup.

Finally, adds a new 'T' parameter to `M80` that will toggle the PSU state instead of just trying to turn it on.

### Configurations

`#define PSU_CONTROL`

### Related Issues

Resolves #21014

### CODE REVIEW

**Comment by thinkyhead** [comment]
One thing to watch out for with a change like this is whether it increases the typical build size for Marlin on something like a Melzi, which has very limited resources. Information on AVR build sizes would be useful to include in the description, and collecting that information should lead to more cautious refactoring.

**Comment by thinkyhead** [comment]
Somehow this change increases the base build size for a 644p by 34 bytes, which is not a huge increase, but it should be accounted for, and if possible the new code should always strive to be smaller than the old code.

**Comment by thinkyhead** [comment]
Accounted for. Just needed a merge of bugfix, and the code size is now the same.

**Comment by thinkyhead** [comment]
I disagree with the inclusion of `M80 T` because its behavior is not predictable without some kind of handshaking.

**Comment by slowbro** [comment]
> I disagree with the inclusion of `M80 T` because its behavior is not predictable without some kind of handshaking.

Understood. That was for #21014. Do you want to 'wontfix' that, or make a separate gcode for it? I don't think the user necessarily cared about the current state, just wanted a way to toggle it.

> Information on AVR build sizes would be useful to include in the description, and collecting that information should lead to more cautious refactoring.

I will take this into account in the future and add that information!

**Pull request merged**
