### PR TITLE
Changes to EEPROM emulation

### PR DESCRIPTION
**Pull request by thinkyhead**
Patch up #7543 for merge…

### CODE REVIEW

**Comment by p3p** [comment]
I'm not fond of this PR, there is no reason caching should be necessary (outside of chanfs), some SD cards seem to have an issue with .. something .. I don't have one that doesn't work so cant debug it. checking if a read seeks beyond the current file size and returning 0 should be done though.

**Comment by victorpv** [comment]
Dont merge this one. I shouldn't have sent the PR, just post the link to the branch with the code, since I just wanted other people to be able to test it.

**Comment by victorpv** [comment]
I have the code ready to check whether the existing file matches a size (currently set to 4096 with a define to match common eeprom size), and extends the file to that size filling up with 0. So for a new file, created as 0 bytes size, it fills 4096 0, for an existing file but smaller, doesn't overwrite the existing size, but pads zeros up to 4096. I'll post that in a separate branch.
UPDATE: It's in this branch:
https://github.com/MarlinFirmware/Marlin/compare/bugfix-2.0.x...victorpv:patch-2

**Comment by thinkyhead** [comment]
> I'm not fond of this PR

I agree with your points. I haven't really evaluated the merits of the change. Since emulation of EEPROM is necessary, if this does offer the advantages described by the original author, then perhaps there's some way to get the fix-ups without also needing to use a 4K RAM cache.

**Comment by thinkyhead** [comment]
The original PR describes these advantages:

> With this changes the EEPROM file content is cached, reducing the number of reads and writes. Also 200ms delay is inserted right after the USB port is connected.

Maybe the delay is helpful. The "reduced reads and writes" may not be an issue, because SD cards are probably background cached.

> Now the board can boot from power down or reset successfully, and can save and read configuration values from the EEPROM file.

As far as I can tell, this is already fine.

> The file is auto-read successfully on boot up.

Good that the code works.

So… I'm not sure what more this PR will fix. The low-level SD driver minimizes read/write. Only the delay is obviously new and helpful.

**Comment by thinkyhead** [comment]
@victorpv Go ahead and make a new PR whenever you want to have the code evaluated.

**Comment by victorpv** [comment]
The delay is helpful, the caching was not really needed.
There were problems with a deleted file reappearing with the same content due to the way FAT works, but that can be managed without the caching, and there are problems with some cards, that were not totally resolved by the caching, so the caching doesn't add value.
Agreed to close this one and I'll send a new PR when the other changes are ready.

**Pull request closed without merging**
