### PR TITLE
Dgus lcd UI mks issue 24376

### PR DESCRIPTION
**Pull request by ellensp**
### Description

DGUS_LCD_UI_MKS will not compile

multiple issues.

### First issue:

```CPP
Marlin\src\lcd\extui\dgus\mks\DGUSScreenHandler.cpp:261:8: error: no declaration matches 'void DGUSScreenHandler::SDPrintingFinished()'
  261 |   void DGUSScreenHandler::SDPrintingFinished() {
      |        ^~~~~~~~~~~~~~~~~

```

Wrong namespace, should be DGUSScreenHandlerMKS

### Second Issue:

```CPP
Marlin\src\lcd\extui\dgus\mks\DGUSScreenHandler.cpp:419:73: error: call of overloaded 'WriteVariable(const uint16_t&, MKS_Choose)' is ambiguous
  419 |       dgusdisplay.WriteVariable(VP_LANGUAGE_CHANGE1, MKS_Language_Choose);
      |                                                                         ^
In file included from Marlin\src\lcd\extui\dgus\mks\../mks/../DGUSScreenHandlerBase.h:24,
                 from Marlin\src\lcd\extui\dgus\mks\../mks/DGUSScreenHandler.h:24,
                 from Marlin\src\lcd\extui\dgus\mks\../DGUSScreenHandler.h:48,
                 from Marlin\src\lcd\extui\dgus\mks\DGUSScreenHandler.cpp:27:
Marlin\src\lcd\extui\dgus\mks\../mks/../DGUSDisplay.h:66:15: note: candidate: 'static void DGUSDisplay::WriteVariable(uint16_t, int16_t)'
   66 |   static void WriteVariable(uint16_t adr, int16_t value);
      |               ^~~~~~~~~~~~~
Marlin\src\lcd\extui\dgus\mks\../mks/../DGUSDisplay.h:67:15: note: candidate: 'static void DGUSDisplay::WriteVariable(uint16_t, uint16_t)'
   67 |   static void WriteVariable(uint16_t adr, uint16_t value);
      |               ^~~~~~~~~~~~~

Marlin\src\lcd\extui\dgus\mks\../mks/../DGUSDisplay.h:68:15: note: candidate: 'static void DGUSDisplay::WriteVariable(uint16_t, uint8_t)'
   68 |   static void WriteVariable(uint16_t adr, uint8_t value);
      |               ^~~~~~~~~~~~~
Marlin\src\lcd\extui\dgus\mks\../mks/../DGUSDisplay.h:69:15: note: candidate: 'static void DGUSDisplay::WriteVariable(uint16_t, int8_t)'
   69 |   static void WriteVariable(uint16_t adr, int8_t value);
      |               ^~~~~~~~~~~~~
Marlin\src\lcd\extui\dgus\mks\../mks/../DGUSDisplay.h:70:15: note: candidate: 'static void DGUSDisplay::WriteVariable(uint16_t, long int)'
   70 |   static void WriteVariable(uint16_t adr, long value);

```

Force (uint8_t) so compiler uses correct overload

###  Third Issue:

```CPP
Marlin/src/module/probe.cpp: In function 'void probe_specific_action(bool)':
Marlin/src/module/probe.cpp:312:10: error: 'class MarlinUI' has no member named 'return_to_status'; did you mean 'reset_status'?
  312 |       ui.return_to_status();       // To display the new status message
      |          ^~~~~~~~~~~~~~~~
      |          reset_status

```
Filter out return_to_status when using DGUS_LCD_UI_MKS
I'm not sure this is best solution for this. Please check and advise 

### Requirements

DGUS_LCD_UI_MKS

### Benefits

Compiles as expected

### Configurations

https://github.com/MarlinFirmware/Marlin/files/8943601/Config2.1.x-6-20.zip

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/24376
https://github.com/MarlinFirmware/Marlin/pull/24025

### CODE REVIEW

**Comment by ellensp** [comment]
Important. I can only test it compiles.

**Comment by thinkyhead** [comment]
Nothing too scary here. For some reason the same display compiles fine on RAMPS without these changes. Anyway, I'll keep moving display-dependent stuff closer to the display code as time goes on.

**Comment by LiamTal** [comment]
hi, I bought the MKS H43 Screen for my SKR mini E3 V2. having same issues as discussed in multiple issues. 
1. Can I do anything to help ? 
2. Can you explain to me the basics of what are the main problems, if we are about to solve them and if makerbase are just being not nice here like someone mentioned. 
THX

**Comment by thisiskeithb** [comment]
> hi, I bought the MKS H43 Screen for my SKR mini E3 V2. having same issues as discussed in multiple issues.

@LiamTal This PR is already merged, so download the latest [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) which includes this patch.

**Pull request merged**
