### PR TITLE
Servo & PWM support for LPC1768

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
This code fully implements the servo and analogWrite functions for the LP1768.

Time for review.

The **LPC1768_PWM.h** file has all the PWM specific routines in it.

**LPC1768_Servo.cpp** is where I joined the servo code and the PWM routines.  Turns out my concept of attaching a pin to a channel in the PWM specific code is different than the concept in the servo library.  Turns out there were only two places where I needed to link in the **LPC1768_PWM.h** routines.

I also ended up making LPC1768 specific copies of some of the Servo class & data structure files because there were some tweaks I needed to do.

The linkage between the top level software and this code is in the file **servo.h** in the **HAL** directory.

I called the PWM init routine from **main.cpp** in the **HAL_LPC1768** directory.

All the analogWrite stuff was done in the analogWrite routine in the **arduino.cpp** in the **HAL_LPC1768** directory.

One thing I'm nervous about is the priority I've assigned to the PWM interrupt.  I've put it as high as I could to minimize the jitter in the PWM pulses.  The PWM ISR execution time is 1.7 - 1.9 microseconds plus the overhead to call it & return.  I'm hoping that that is short enough to not bother the timer or stepper functions.  I couldn't determine how the AVR code handled it.

----

I'm having problems with the controller locking up.  I know that writing to the on-board SD card will lock it up about one in five times.  It also appears that running PWM channels (analogWrites) at high duty cycles (?90% and above ?) seems to make it happen faster ( about 5 minutes).

Are these lockups something that's being seen with the current code base or is this something that I've created?

### CODE REVIEW

**Comment by Roxy-3D** [comment]
> I'm having problems with the controller locking up. I know that writing to the on-board SD card will lock it up about one in five times. It also appears that running PWM channels (analogWrites) at high duty cycles (?90% and above ?) seems to make it happen faster ( about 5 minutes).

> Are these lockups something that's being seen with the current code base or is this something that I've created?

That is what I was seeing here:  https://github.com/MarlinFirmware/Marlin/pull/7390#issuecomment-321915076         I have a very slow Z-Axis.   And somehow...   Doing very short Z-Moves (.1 mm in PronterFace) causes me to see lock ups.     I haven't got more information yet.    I need to have a servo on that machine but I was hoping to eliminate all of the other changes in your branch so I could just debug the main branches issues.

But it kind of looks to me like the head and tail pointer aren't being treated as volatile in blocks_queued().    I'm sure that is not the case, but that is the level I'm at.

My guess is if you change your Z-Axis settings to my speeds here: https://github.com/MarlinFirmware/Marlin/pull/7390#issuecomment-321988808    You will be able to create the lock up by just doing a .1 mm Z move two or three times in a row.

**Comment by p3p** [comment]
>  I know that writing to the on-board SD card will lock it up about one in five times.

I doubt that is anything to do with the Z-move lockup, depending on file size it could trigger the watchdog, will either need to slow down the transfer rate, tune priorities, or do a watchdog reset, that code still needs finished (no transfers during prints ect), I'l hopefully get some more time to work on this soon.

**Comment by Roxy-3D** [comment]
@Bob-the-Kuhn    Bob, do you mind if I merge this?  I think it is close enough I can use it to work on the issues that I'm seeing.

**Comment by Bob-the-Kuhn** [comment]
That's OK with me.

**Comment by Roxy-3D** [comment]
@Bob-the-Kuhn    Bob... Just a quick FYI: for you...    I'm working in the bugfix-2.0.0 branch trying to find that lock up problem with small Z movements.    It is still there with all of your other changes stripped out.  So, those other changes are not causing the issue I'm seeing.

The other thing I noticed is now the servo kicks back and forth when the machine starts coming up from a reset.  I think the servo's are getting initialized twice or having their position set back and forth.   Its not a big deal...   But I thought I would mention it.   

Also...   I commented out the first set of #define's in  pins_RAMPS_RE_ARM.h just because that file gets pulled in so many places and I was getting too many warnings...
```cpp
//#define LCD_PINS_D5         59  // J3-8 & AUX-2
  #define DOGLCD_A0           59  // J3-8 & AUX-2
//#define LCD_PINS_D6         63  // J5-3 & AUX-2
  #define DOGLCD_CS           63  // J5-3 & AUX-2
//#define LCD_PINS_D7          6  // (SERVO1) J5-1 & SERVO connector  
  
  #define LCD_PINS_D5         71  // ENET_MDIO
  #define LCD_PINS_D6         73  // ENET_RX_ER
  #define LCD_PINS_D7         75  // ENET_RXD1
 ```

**Comment by Bob-the-Kuhn** [comment]
You'll need to give me more details on "servo kicks back and forth ".

Probably best if you drop your config files onto the reply.

**Comment by Roxy-3D** [comment]
The servo looks like it is trying to deploy.   But then stops (before it is all the way deployed). And it retracts.    And then it repeats that cycle...   If you have a BL-Touch connected, you may not see it.   But with an RC-Servo, I'm seeing it.

[Configuration_adv.txt](https://github.com/MarlinFirmware/Marlin/files/1226498/Configuration_adv.txt)
[Configuration.txt](https://github.com/MarlinFirmware/Marlin/files/1226497/Configuration.txt)

**Comment by Bob-the-Kuhn** [comment]
I'm not seeing it with a BLTouch.

Here's what's happening (confirmed with logic analyzer):
18:17:22.628 : ATTACH  pin: 11  servo: 0
18:17:22.634 : WRITE   pin: 11  value: 1420  angle (Marlin): 84  angle (standard): 82
18:17:23.136 : DETACH  pin: 11

Does it still do it if DEACTIVATE_SERVOS_AFTER_MOVE is disabled?

Maybe SERVO_DELAY is too small for that device or maybe the Stow angle is off.

**Comment by Roxy-3D** [comment]
> Maybe SERVO_DELAY is too small for that device or maybe the Stow angle is off.

The default 300 ms. delay always worked fine when used with the Atmega-2560 board.  But for how often the servo is used...   I bumped it up to 500 ms. just to make sure there were no issues.

The stow and deploy angles are correct.  I've verified them with M280 P0 S??

> Does it still do it if DEACTIVATE_SERVOS_AFTER_MOVE is disabled?

I changed this and guess what...   I think I have to walk back the previous description of what is happening.   The servo is kicking the probe leg back and forth for a much longer time now.  With DEACTIVATE_SERVOS_AFTER_MOVE turned off...   The problem is much worse.    

So...   I bumped the SERVO_DELAY up to 1500 and the convulsions last much longer.    But here is something new I noticed:    Somehow SD-Card activity is associated with this behavior.  If I copy a folder with files from my host computer to the SD-Memory card, the servo goes into convulsions kicking the probe leg back and forth.   Maybe it is something related to the SD-Memory card I'm seeing???

> You'll need to give me more details on "servo kicks back and forth ".

Even if you don't have an RC Servo to connect up and watch...  I bet what is happening can be seen on an oscilloscope.   Can you connect a test lead to the Servo control pin and take a look?

**Comment by Bob-the-Kuhn** [comment]
OK - I'll see if there is any difference between the angles generated by M280 and the init value.

I'll look at what happens when the SD card is active.

**Comment by p3p** [comment]
USB file transfer to SD Card is an expensive operation, its gonna mess with a lot of timings, USB interrupt priority will need tuned, probably to the lowest possible.

**Comment by Bob-the-Kuhn** [comment]
I don't understand why it's happening.

Let's make sure I understand the problem

Problem description:
With DEACTIVATE_SERVOS_AFTER_MOVE turned off:
1) servo moves leg part way to the correct position
2) servo moves leg all the way back to the power off position
3) loop continues forever.
4) loop time is less than a second
5) if issue M280 P0 S85 then deploys properly and there is no pulsing
6) writing from host to USD card makes it worse

Here's what I've found out on my unit:
1. M280 command results in the same pulse width as the init value
2. USB activity isn't an obvious problem
3. SD card writes result in some longer pulses.  Most of the longer pulses would increase the angle by about 1/2 degree.  The worst I found was a 2.2 degree increase.

Please try M280 P0 S86 and S87 and see if that results in movement similar to what you're seeing.  M280 only accepts integer values so we're limited to S85, S86 & S87 values.

**Comment by Roxy-3D** [comment]
Yes, your Problem description is accurate.    But I would add one thing.   Even with the servo in a stable position (either deployed or stowed), SD Card activity causes it to jitter dramatically.

Do you have an RC Servo you can plug in?   I think the BL-Touch is hiding too much of what is happening...

**Comment by Bob-the-Kuhn** [comment]
I don't understand why M280 gets rid of the jitter.

I'll put together a hybrid that uses the PWM1 module to directly control the Srevo0, 1 & 3 pins.  That'll eliminate pulse width jitter for those three pins.

**Comment by Roxy-3D** [comment]
> I don't understand why M280 gets rid of the jitter.

I don't think I believe that it does...   I'm kind of thinking the sequences is more like any SD-Card (and maybe any USB) activity interferes with the Servo pin pulses....    But independent of that,  after the first M280 the servo has been assigned and the pin is active trying to do the 'right' thing.   So that settles down a lot of the 'noise'.   But SD-Card (and maybe USB) activity still is messing with the Servo Pulses so when ever that is going on, the servo is kicking back and forth.

I'm sure what I just described is going to be proven to be 'not true'.   But right now...  It feels close to that.

> SD card writes result in some longer pulses. Most of the longer pulses would increase the angle by about 1/2 degree. The worst I found was a 2.2 degree increase.

Some more thoughts on this...   Those RC Servo's are very inexpensive.   It maybe they don't have very sophisticated logic inside them to lock onto a particular setting.   If the pulses vary back and forth (even by what appears to be a small amount to us) it maybe they can't lock on to it???

**Comment by Bob-the-Kuhn** [comment]
I've finally worked my way through enough of the quirks of a hybrid system that I have confidence in my code.

Now that it's not crashing I'm seeing some strange behavior on pins 71, 73 & 75 (could be others that aren't hooked up to the logic analyzer).  About every 1 - 1.5 seconds they seem to bounce randomly for 15mS.  If I write a large file onto the SD card (30 seconds to complete) it stretches from 1 second to 1.25 seconds.  

Any idea what could be doing that?

**Comment by Bob-the-Kuhn** [comment]
It's the LCD update for the RRD smart controller.  It's definitely playing with pins 73 & 75 when it shouldn't be.  

RRD full graphics and VIKI2 don't play with those lines.

Maybe you should try switching to a RRD full graphics and see if your system is better behaved.

**Comment by Roxy-3D** [comment]
> It's definitely playing with pins 73 & 75 when it shouldn't be.

Back on the Atmega-2560 I saw glitches on pins even though I was messing with different pins on the port.   Looking at the current code:
```cpp
void digitalWrite(int pin, int pin_status) {
  if (!WITHIN(pin, 0, NUM_DIGITAL_PINS - 1) || pin_map[pin].port == 0xFF)
    return;

  if (pin_status)
    LPC_GPIO(pin_map[pin].port)->FIOSET = LPC_PIN(pin_map[pin].pin);
  else
    LPC_GPIO(pin_map[pin].port)->FIOCLR = LPC_PIN(pin_map[pin].pin);

  pinMode(pin, OUTPUT);  // Set pin mode on every write (Arduino version does this)

    /**
     * Must be done AFTER the output state is set. Doing this before will cause a
     * 2uS glitch if writing a "1".
     *
     * When the Port Direction bit is written to a "1" the output is immediately set
     * to the value of the FIOPIN bit which is "0" because of power up defaults.
     */
}
```
Notice the comments talking about a glitch?   I wonder if we are seeing something similar.   And there is no logic after the pinMode(pin,OUTPUT);    So, what must be done after the output state is set???     It might make sense to see if the pin is already declared to be OUTPUT, and if so, not mess with it???

I haven't found the GPIO pin diagram showing what is there and how different operations affect the GPIO pin values yet.   If you stumble across the GPIO pin diagram showing how the different parts of the pin fit together, please post it!

But at section 9.1 of this manual:  http://www.nxp.com/docs/en/user-guide/UM10360.pdf  is a bunch of information about the GPIO pins.   We may need to become experts on sections 9.5.1 to 9.5.5.     I'm wondering if we need a little bit different logic than what is in that code up above.   It might be we can use M43 to pulse one pin and use that to see glitches on another pin.   If so, that would be an indication a better digitalWrite() algorithm needs to be found.

One more thing I'm wondering...   Does LPC_GPIO() need its contents wrapped with 'CRITICAL_SECTION' ?    It looks like it is very possible that it can get interrupted.   And without seeing the GPIO pin block diagram, it is hard to know how a partial completion of digitialWrite() is going to behave.

**Comment by Bob-the-Kuhn** [comment]
Chris & I have been through that section many many times.   I'm 99.999% sure the reads and writes are solid.  

I put that 2.5uS glitch comment in there so people understand why it was done differently on the Re-ARM than on the AVRs.

----

I think we have issues with the LCD displays in general and the RepRap smart controller in particular.

I've found where the software SPI interfaces with the hardware.

I haven't found where the hardware SPI interfaces with the hardware.

I'm definitely not understanding how the various levels link to each other.  I've tried top down & bottom up & always get lost in all the almost identically named routines.

----

I'm still working on the hybrid PWM system.  You know you need a break when you can't get "if (1 +1 == 2) " to work correctly.

**Comment by Roxy-3D** [comment]
> I've found where the software SPI interfaces with the hardware.
> I haven't found where the hardware SPI interfaces with the hardware.

I don't understand the SPI stuff.   I probably can't be much help on that.   But I'm toying with the idea of moving the LCD off of the ethernet pins and over to the E2 connections.  The ethernet connector is all P1.xx and the E2 step stick is a mix of everything but P1.xx   Maybe just being on a different port will help?

**Comment by p3p** [comment]
> I haven't found where the hardware SPI interfaces with the hardware.

@Bob-the-Kuhn the only thing that is hardware SPI is the onboard sd-card, and that is accessed using a driver supplied by a more uptodate version of the ChanFS library than the class based version in Marlin, ..  

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/frameworks/CMSIS/LPC1768/lib/chanfs/mmc_ssp.c

remember you do have CMSIS to help with hardware interfaces, though you seem to be doing well without it (ADC ect).

**Comment by Bob-the-Kuhn** [comment]
@Roxy-3D - OK - that explains why pins 73 & 75 are toggling with the RRD Smart Controller.  I just didn't find where the logical connection had been made.

**Comment by Bob-the-Kuhn** [comment]
@p3p  - I haven't the faintest idea what CMSIS is used for.

One of these day's I need to actually get some C++ text books.  So far it's all been by example and google and a whole lot of trial & error.

**Comment by Roxy-3D** [comment]
Oh!...  I guess I'll quit what I was working on.   I was working to get this to compile:
```cpp

void digitalWrite(int pin, int pin_status) {
//#define SERVO0_PIN         11
if ( pin==11) {
serial_echopair_P("Write to servo pin: ",pin);
serial_echo_nl();
}
  if (!WITHIN(pin, 0, NUM_DIGITAL_PINS - 1) || pin_map[pin].port == 0xFF)
    return;
  if (pin_status)
    LPC_GPIO(pin_map[pin].port)->FIOSET = LPC_PIN(pin_map[pin].pin);
  else
    LPC_GPIO(pin_map[pin].port)->FIOCLR = LPC_PIN(pin_map[pin].pin);
  pinMode(pin, OUTPUT);  // Set pin mode on every write (Arduino version does this)
}
```
And once I verified the digitalWrite() function was being told to mess with the servo pins without me doing anything on the servo, I was going to make it be smart enough to unwind the stack and tell me what the calling chain was to get to digitalWrite().   But...   If you know how to fix things now...    I'll just wait.     THANKS BOB!!!!!!

**Comment by p3p** [comment]
@Roxy-3D for future reference in general you have no access to Marlin "features" inside the HAL, it should be a one way interface (Marlin -> HAL), controlled by a strict API (its not yet but it should be ;) ) so to output on the serial just access it directly usb_serial.printf(();

**Comment by Roxy-3D** [comment]
>  for future reference in general you have no access to Marlin "features" inside the HAL, so to output on the serial just access it directly usb_serial.printf(();

Thanks...  I just found that as you posted...  
```cpp
// Program Memory
void serialprintPGM(const char * str){
  usb_serial.print(str);
}
```
I'm thinking....  If we don't have a debugger for the Re-ARM board, it might be good to have a routine that can unwind the stack and dump all the parameters to help us find what is causing stuff.   So maybe I'll plow forward.   It might be nice to test for some bad condition, and be able to dump the stack to see how the situation happened.

For example...  If the servo pin is getting touched by something non-servo related, it would be helpful to know what is doing it.   And just putting a quick test looking for the servo pin being referenced would point us right at the offending code if we had a way to unwind the stack.

If that really would be helpful...  Please say so.   Or conversely, if you have better tools (which I don't have) please also say that.   No reason to write code that doesn't help things!!!

**Comment by p3p** [comment]
I noticed the debugging discussion but didn't have an easy solution to put forward, I used an mbed for my early work that has an inbuilt USB DAP interface (the mbeds have a separate microcontroller that handles it along with usb serial and the bootloader filesystem), all modern ARM chips have the DAP interface (not usb) it communicates over SWD (or JTAG), I then connect to the USB DAP interface with OpenOCD.

**Comment by p3p** [comment]
> I haven't the faintest idea what CMSIS is used for.

@Bob-the-Kuhn it's the CMSIS driver supplied by LPC for the lpc1768, (CMSIS is an ARM standard api) I included it in the frameworks folder to help with the hardware interfacing as it was needed for the usb stack, there should be usage examples available somewhere.

**Comment by Bob-the-Kuhn** [comment]
@Roxy-3D - here's an ugly but works hybrid servo/pwm system.  Servos 0, 1 & 4 come off the PWM1 module so are as steady as they'll ever be.  I was seeing less than a microsecond variation in pulse width on those three in the 1000- 2500 range while the others had 20 uS variations with similar nominal pulse widths.

[LPC1768_PWM.zip](https://github.com/MarlinFirmware/Marlin/files/1230165/LPC1768_PWM.zip)

**Comment by Bob-the-Kuhn** [comment]
@p3p - a standard that might have saved me time & aggravation and resulted in better code?

I don't think I like that.  I'd much rather re-invent the wheel & bust down brick walls with my head.  Does it show?

Tomorrow is a good day to look it over & see if I can makes some sense of it.

**Comment by Roxy-3D** [comment]
@Bob-the-Kuhn   Bob,  the servo is **_MUCH_** better behaved now!   I've only tested on Servo-0 so far...   But the SD-Card activity no longer affects things.   Let's merge it!!!

I still have my small Z movement lock up.    I'll be going after that later today.

**Comment by Bob-the-Kuhn** [comment]
I've just created PR #7533 to switch over to a hybrid PWM system.

**Pull request merged**
