### PR TITLE
Add Skynet/ANET A10 support

### PR DESCRIPTION
**Pull request by thinkyhead**
Fix up spacing in #7016, ready to merge

----

Adding support for the ANET A10, based on the [SkyNet project](https://www.facebook.com/skynet3ddevelopment/).

Also:
- Apply tweaks to configs/conditionals ahead of Anet changes.
- Extend Travis helper `build_marlin` to build non-mega2560 boards.

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
@thinkyhead - Please merge when you are ready.

**Comment by thinkyhead** [comment]
Very soon! One more cleared from the docket....

**Comment by thinkyhead** [comment]
@Bob-the-Kuhn Quick question. Is it appropriate to show "SkyNet3D V2.4.5 (GH)" on the splash screen? Seems like that would be their official firmware version.

**Comment by benlye** [comment]
@thinkyhead, I think you can drop the "SkyNet3D V2.4.5 (GH)" splashscreen line.  SkyNet is a user-group distributed firmware, and I think that the guys who build and distribute it should put their version number in when they build the distribution.

**Comment by thinkyhead** [comment]
I'm trying to use the recommended Sanguino hardware support option to build this in Travis CI, but so far I haven't been able to get the board installed correctly. Will keep at it. Trying variants of this at the moment:
```
  - arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/Lauszus/Sanguino/master/package_lauszus_sanguino_index.json" --save-prefs
  - arduino --install-boards Sanguino:avr:1.0.2
```
The error I'm seeing is…
```
Initializing packages...
Could not find boards.txt in /usr/local/share/arduino/hardware/sanguino/variants. Is it pre-1.5?
Could not find boards.txt in /usr/local/share/arduino/hardware/sanguino/cores. Is it pre-1.5?
Could not find boards.txt in /usr/local/share/arduino/hardware/sanguino/bootloaders. Is it pre-1.5?
Could not find boards.txt in /usr/local/share/arduino/hardware/sanguino/firmwares. Is it pre-1.5?
WARNING: Error loading hardware folder /usr/local/share/arduino/hardware/sanguino
  No valid hardware definitions found in folder sanguino.
```
----
Note that we _could_ also use the hardware support from the defunct branch https://github.com/MarlinFirmware/MarlinDev/tree/MarlinPlatform-1.6.7-b …

Maybe that old hardware support should be revived as part of the new 2.0 branch, and extended as the HAL is extended. It may help to have the necessary hardware support files easier to find — then they would also usable by Travis without any extra download, to build for more variants.

There were some caveats with Marlin also having hardware support as a part of its experience, but it seems to help tie in with Arduino IDE —possibly PlatformIO— and in the long run it may be worth including hardware support to provide a slightly more seamless experience for the user. Meanwhile, the old URL still works:

https://raw.githubusercontent.com/MarlinFirmware/MarlinDev/platform/package_marlinfirmware_index.json

**Comment by thinkyhead** [comment]
No more of those errors with this combination:
```
  - arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/Lauszus/Sanguino/master/package_lauszus_sanguino_index.json" --save-prefs
  - arduino --install-boards Sanguino:avr:1.0.2

  # Anet build
  #
  - use_example_configs Anet
  - build_marlin sanguino:cpu=atmega1284p

```
…but the build still fails due to some other error. If anyone wants to figure out Travis build, that would be a big step. I will still merge this without that part.

**Comment by Bob-the-Kuhn** [comment]
> Sanguino:avr:1.0.2

What does the 1.0.2 refer to?

**Comment by benlye** [comment]
> What does the 1.0.2 refer to?

Presumably that pulls [version 1.0.2](https://github.com/Lauszus/Sanguino/releases) of the Sanguino definition, same as using the Arduino IDE's Boards Manager to install v1.0.2.

FWIW, I manually built Marlin for my Anet using the Sanguino board extension rather than the Anet one from the SkyNet3D project and it appears to work fine (compile, upload, home, move, heat, fans).

How does one see the old Travis logs?

**Comment by Bob-the-Kuhn** [comment]
I manually compiled the Anet board using the Sanguino extension and  Arduino IDEs 1.6.12 & 1.8.3.

It finally dawns on me - the 1.0.2 is the newest Sanguino IDE version that the Sanguino JSON will install.

I don't think we have any Travis tests for other 1284 boards.

I don't think the Travis test should stand in the way of merging.

**Comment by thinkyhead** [comment]
> I don't think we have any Travis tests for other 1284 boards.

True. Actually this was my first attempt to get Travis to build for a variant other than mega. I added to `build_marlin` (and will keep this):
```bash
#!/usr/bin/env bash

case "$#" in
  0 ) BOARD=arduino:avr:mega:cpu=atmega2560 ;;
  * ) BOARD=arduino:avr:$1 ;;
esac

arduino --verify --board $BOARD Marlin/Marlin.ino
```
Then in Travis you could use something like this:
```
 - use_example_configs Anet
 - build_marlin sanguino:cpu=atmega1284p
```

> I don't think the Travis test should stand in the way of merging.

I agree. Merging shortly….

**Comment by thinkyhead** [comment]
> How does one see the old Travis logs?

The travis logs for this would be obscure, but they could be sussed out. I have some in my browser history:

This is [the most recent](https://travis-ci.org/MarlinFirmware/Marlin/builds/246679417?utm_source=github_status&utm_medium=notification) where it failed with `The command "arduino --install-boards Sanguino" failed and exited with 1 during .`.

Same [here](https://travis-ci.org/MarlinFirmware/Marlin/builds/246678811?utm_source=github_status&utm_medium=notification) but the `--install-board` command is combined with `--pref`.

And here's what happens [when wget is used](https://travis-ci.org/MarlinFirmware/Marlin/builds/246671946?utm_source=github_status&utm_medium=notification) to get `Sanguino-0101r1.zip` instead. The install didn't follow all [instructions from this blog](http://dustsreprap.blogspot.com/2015/06/how-to-install-sanguino-in-arduino-164.html), so perhaps that would improve the outcome.

**Comment by Bob-the-Kuhn** [comment]
Yes!!!

**Comment by benlye** [comment]
Somewhere along the way ADC_KEYPAD has been broken.  If I try to compile as-is I get two errors:

```
ultralcd.cpp:4037: error: 'return_to_status_ms' was not declared in this scope

         return_to_status_ms = millis() + LCD_TIMEOUT_TO_STATUS;

         ^

In file included from sketch\Marlin.h:32:0,

                 from sketch\ultralcd.h:26,

                 from sketch\ultralcd.cpp:23:

sketch\ultralcd.cpp: At global scope:

ultralcd.cpp:4795: error: expected primary-expression before '__attribute__'

static const _stADCKeypadTable_ stADCKeyTable[] = PROGMEM {

                                                     ^

ultralcd.cpp:4823: error: expected ',' or ';' at end of input

```

I can fix them by changing [ultralcd.cpp#L4037](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/ultralcd.cpp#L4037) from:
`return_to_status_ms = millis() + LCD_TIMEOUT_TO_STATUS;`
to:
`static millis_t return_to_status_ms = millis() + LCD_TIMEOUT_TO_STATUS;`

And [ultralcd.cpp#L4795](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/Marlin/ultralcd.cpp#L4795) from:
`static const _stADCKeypadTable_ stADCKeyTable[] =  PROGMEM {`
to:
`static const PROGMEM _stADCKeypadTable_ stADCKeyTable[] =  {`

Are these the right fixes?  I won't be able to test on the Anet ADC keypad for a couple of hours, once I confirm that this change works I can submit a PR.

**Comment by benlye** [comment]
Confirmed that the changes above compile and the ADC_KEYPAD works.  PR #7150 created.

**Comment by DIGITALKRONE** [comment]
hi Guys. i have  3D touch  and i have the following issue with anet a8. I have seleceted double touch when homing Z but the sensor goes out, then touch the bed, then retracts and stays short (not coming out for any further probing) and then say you want to home again, the probe is not active and nozzle hit the bed. It`s happening all the time.
Any ideas on that one?
Thank you

**Pull request merged**
