### PR TITLE
Stepper interrupt protection

### PR DESCRIPTION
**Pull request by tonnico**
this is an idea to prevent an overflow.
discussions are welcome.

maybe this was the issue from @boelle #1888

### CODE REVIEW

**Comment by boelle** [comment]
no my problem was actually too high feedrate on X and Y, i lowered them to 100 and now everything is fine

**Comment by tonnico** [comment]
You could test this with your machine. This PR is mainly for the deceleration. When going down from double to single stepping. This is why your printer works at slower speed. Because you don't reach double stepping maybe.

**Comment by boelle** [comment]
i thought stepping was selected with jumpers on the stepper drivers?

**Comment by tonnico** [comment]
Yes of corse.
The problem is more a timing issue. Normally an interrupt is running until execution is ready. So if the OCR1A flag is at maybe 10 and the interrupt need 50 this is no problem.

But in some cases your interrupt flag is as maybe 50. It counts now to 40. The new timer is set to 25. Now the interrupt overflow at 65535 because it never reached 25. That can break this.

**Comment by boelle** [comment]
also part of the issue is the toshiba stepper drivers... they have a max of 10000 pulses each micro second... if you get above that they will start to do funny things...

and the pulse width needs to be longer than normal

**Comment by boelle** [comment]
but yes i can test it... and sure will, just rebuilding my extruder so it can support auto level as well

that will take the better part of the day as i have to go and by a few bits

**Comment by boelle** [comment]
@thinkyhead would you say about merging this one?

**Comment by tonnico** [comment]
This needs first some feedback. I don't want to merge this too fast. This is ISR-stuff and we should take care.

**Comment by boelle** [comment]
yep, also why i try to attract more eyes on it...

not sure if i will be ready to test today, but sure i can in weekend

**Comment by tonnico** [comment]
Maybe 1 is too less `OCR1A + 1`
I don't know how much 'delay' we need for this. Maybe 5 could be a good value, so we have ~ 40 ticks to go.

**Comment by thinkyhead** [comment]
This looks like a good approach, but yes please test and see if it helps and how it affects timing overall.

**Comment by tonnico** [comment]
I will make a more simple method for this. I think we only need that in the decelerating part of the stepper code.

When you go down from double to single the isr go from 5000Hz to 10.000Hz. The timer is set from 400 to 200 in the end of the isr. It could be possible then that the timer is allready at 201 before setting to 200. So we count now (65535-200)/2.000.000 ~ 32ms as extra time.

I can't say if this will ever happen. But if, we have this lag.

**Comment by boelle** [comment]
at least the 10000 number can be a problem for me... but time will tell

but to really test it i have to do it a real prints as my issue is so much gone i can hardly hear it... at i never know when and where on a print it comes...

**Comment by tonnico** [comment]
If you have defined the toshiba-mode (if that exists in your config) this will never happen, because you can't leave the single stepping.

**Comment by a0s** [comment]
got same issue, as in https://github.com/MarlinFirmware/Marlin/issues/1888.
toshiba-mode not helps for my drv8825 steppers )
this problem is independent of acceleration (for me), only on the speed.
subscribe

**Pull request closed without merging**
