### PR TITLE
Fix SPI_SD Outside of HAL_STM32F1

### PR DESCRIPTION
**Pull request by 3DSmitty**
### Description
This change fixes the SPI code for STM32F1 boards especially the BIGTREETECH SKR Mini V1.1 board. It has been re-designed to not use the SS_PIN inside of the HAL.

### Benefits
Allows use of the onboard SD card reader or the external SD card reader.

### Related Issues
This is related to #14041 to add Marlin support for the BIGTREETECH SKR Mini V1.1 and the original commit #14287.

### CODE REVIEW

**Comment by jmdearras** [comment]
I pulled this branch and edited for my display and SD card on the LCD.  It compiled without error and for the first time since I bought the Mini, I could read and start prints from the SD Card.  This is ready for PrimeTime, in my opinion

**Comment by tpruvot** [comment]
Finally got the LCD working : https://drive.google.com/file/d/1-KljN1W1in6805iZ3JiXPsKbMtV7U5Xs/view?usp=sharing
https://github.com/tpruvot/Marlin/tree/SKRmini-2.x

**Comment by thinkyhead** [comment]
@tpruvot — Looks good! Do you think we will need to make a separate u8g implementation file for each platform to support the Fysetc Mini Panel?

**Comment by tpruvot** [comment]
Kinda problematic, as SD card can use the same bus with another mode... :/

**Comment by 3DSmitty** [comment]
@tpruvot that looks great! Does this mean other 12864 LCD's should work as well?

@thinkyhead thanks for merging, your quite the artist with your graphical pin representations :-)

**Comment by tpruvot** [comment]
i guess so... the ones using one "wire" spi at least, but i dont own any other to try

**Comment by jmdearras** [comment]
@tpruvot Does the MKS-MINI-12864 work with this, too?

**Comment by jmdearras** [comment]
> @tpruvot Does the MKS-MINI-12864 work with this, too?

@tpruvot nope,  :(

**Comment by thisiskeithb** [comment]
Has anyone been able to get a RepRapDiscount Full Graphic Smart Controller (12864) working on an SKR Mini 1.1?

**Comment by 3DSmitty** [comment]
Hey did you guys notice Bigtreetech updated their Marlin code? Looks like they added support for a ST920 128x64 LCD 2 days ago.
https://github.com/bigtreetech/BIGTREETECH-SKR-MINI-V1.1/tree/master/firmware/stm32f103RMarlin-bugfix-2.0.xV20190615-12864-16div

**Comment by 3DSmitty** [comment]
Haha they are 10 steps behind us their SPI and SD will not work.

**Comment by thinkyhead** [comment]
> support for a ST920 128x64 LCD

Great! Hopefully a PR will be coming to us soon….

**Comment by 3DSmitty** [comment]
How do I compare the bigtree git against Marlin 2.0? Do I have to create a fork first?

**Comment by tpruvot** [comment]
not easy but their date should help.. to find the closest bugfix-2x commit and compare

**Pull request merged**
