### PR TITLE
DGUS_RELOADED version 1.03

### PR DESCRIPTION
**Pull request by Neo2003**
### Description

More details on DGUS_RELOADED printers
- Z is now displayed with 2 decimals and rounded to 0.02 (was one decimal)
- Bed temperature from int to float with 1 decimal
- Nozzle temperature from int to float with 1 decimal
- Screens adjusted accordingly with type changes and more room

Root screen
IMG_2861

Print screen
IMG_2857
IMG_2858

Other screens
IMG_2859
IMG_2860

All screens displaying current temperature for both bed and nozzle have been updated

### Requirements

This is for DGUS_RELOADED (DWIN screens)
This requires the new DWIN SET from here: https://github.com/Neo2003/DGUS-reloaded/releases
This is because some types have changed and some addresses have changed.

### Benefits

More detailed information, Z with only 1 digit cannot show the Z changes due to ABL and does not display enough details when printing with 0.08, 0.12 or 0.16 layers

### Configurations

Here is the configuration I use for my Ender 5 Plus printer with MicroSwiss direct drive
[configuration.zip](https://github.com/MarlinFirmware/Marlin/files/10942121/configuration.zip)

### Related Issues

None

### CODE REVIEW

**Comment by ellensp** [comment]
DGUST_RELOADED??  Its DGUS_RELOADED

**Comment by Neo2003** [comment]
Yes, I don't know what my fingers typed. :)

**Comment by thisiskeithb** [comment]
The Ender-5 Plus files / readmes in the configs repo would also need to be updated if we’re going to migrate away from the Desuuuu version: https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/Creality/Ender-5%20Plus

**Comment by Neo2003** [comment]
Ok, I will try to see how to fork another branch and add it to this PR

**Comment by Neo2003** [comment]
Cannot find a way to add this to same PR
https://github.com/Neo2003/Configurations/commit/4947384ab78df4720a3c9ba29d39e948ea9f385f
I hope it's fine

**Comment by thisiskeithb** [comment]
> Cannot find a way to add this to same PR
> [Neo2003/Configurations@4947384](https://github.com/Neo2003/Configurations/commit/4947384ab78df4720a3c9ba29d39e948ea9f385f)

Those changes would be a new PR in the [Configurations repo](https://github.com/MarlinFirmware/Configurations).

**Comment by ellensp** [comment]
@Neo2003 is there a way to store a version number in the dwin_set that marlin can check for?
So marlin can warn users the DWIN set is not the correct version for the firmware.

**Comment by thinkyhead** [comment]
Some of these changes are now found breaking. See #28554. Can anyone with a Reloaded compatible DGUS display confirm that the changes in #28554 are correct and that the changes made here are incorrect?

**Pull request merged**
