### PR TITLE
Add portrait support for move axis screen for TS35

### PR DESCRIPTION
**Pull request by uncellon**
### Description

This PR adds portrait support for move axis screen for MKS TS35 display (TFT_COLOR_UI interface).

Below I have attached an archive with examples of how the interface looks now.
[Examples.zip](https://github.com/MarlinFirmware/Marlin/files/11680575/Examples.zip)

### Requirements

- Board: MKS Robin Nano V3.1
- Display: TS35

### Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11680583/Configuration.zip)

### Benefits

- The "Move axis" screen displays correctly in portrait mode.

### Related Issues

https://github.com/MarlinFirmware/Marlin/pull/25629#issuecomment-1537588753

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thank you for the updates @uncellon! I went ahead and applied some additional updates that I noticed were needed while taking a cursory glance and comparing code among the different TFT sizes — mostly adjustments related to disabled XYZ axes and machines with no extruder. If you come across any more of these things needing a little cleanup please don't hesitate to submit another PR.

**Comment by thinkyhead** [comment]
After I did my cleanup round and merged those changes, this PR in its current state removes all the changes from #25942. Is there anything from that PR which should be preserved, or is this all good as it is now?

**Comment by uncellon** [comment]
I'm glad to help! I looked at the changes, I will keep in mind how to format the code in the future. It is still difficult for me to operate with such a large number of macros, but I seem to have caught the main point 🙂

**Comment by Foxies-CSTL** [comment]
Thanks to @uncellon  for the correction and to @thinkyhead for the merge.
Tested and validated on Mks_Robin_TFT35 v1 (FSCM) and Mks_TS35R_V2 (SPI)

**Pull request merged**
