### PR TITLE
Additional messages translated into Dutch

### PR DESCRIPTION
**Pull request by paulusjacobus**
New messages translated;

``` cpp
#define MSG_LEVEL_BED_HOMING                "Homing XYZ"
#define MSG_LEVEL_BED_WAITING               "Click to Begin"
#define MSG_LEVEL_BED_DONE                  "Leveling Done!"
#define MSG_LEVEL_BED_CANCEL                "Cancel"
. . .
#define MSG_HOME_OFFSETS_APPLIED            "Offsets applied"
```

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks like a conflict has arisen. `git rebase upstream/RCBugFix`, resolve conflicts, and `push -f` whenever you have a moment….

**Comment by paulusjacobus** [comment]
@thinkyhead I got some problems with rebasing my repo on Github:
$ git rebase https://github.com/paulusjacobus/Marlin.git
fatal: Not a git repository (or any of the parent directories): .git
Humm what am I doing wrong?

**Comment by thinkyhead** [comment]
You might need to add a remote for the main repo:

```
git remote add upstream git@github.com:MarlinFirmware/Marlin.git
```

Then you can fetch the latest changes:

```
git fetch upstream
```

You can make working copies of any upstream branch. It's good to keep a local copy of `RCBugFix`:

```
git checkout upstream/RCBugFix -b RCBugFix
```

Then you can make work branches as-needed:

```
git checkout RCBugFix -b my_new_work_branch
git push origin my_new_work_branch
```

To update your local `RCBugFix` branch you simply do:

```
git fetch upstream
git checkout RCBugFix
git merge upstream/RCBugFix
```

Then, to move your commits onto the end of the new `RCBugFix`, just do:

```
git checkout patch-3
git rebase RCBugFix
```

If you have any conflicts, search the code for `<<<<` and patch it up properly. After conflicts are resolved:

```
git add *
git rebase --continue
```

When `git rebase --continue` doesn't take, just use `git rebase --skip` instead. Finally, you can push your new commits to Github. The `-f` flag is needed if you're not just adding new commits.

```
git push -f
```

You can also fix up and combine your commits (please do) by using interactive rebase with the "fixup" option:

```
git rebase -i RCBugFix
git push -f
```

**Comment by thinkyhead** [comment]
I made some scripts to help with working on Marlin branches and pull requests.
They save me a lot of time and effort.

https://gist.github.com/thinkyhead/c84ef67739a54d9f9b4a

**Comment by paulusjacobus** [comment]
Thanks @thinkyhead I see the conflicts and they are all in my patch-3 branch. I wonder if I should fork a new repo from the RcBugFix release and apply the few changes there and do a new pull rather than try to fix all the issues? That might speed up things. Anyway I will give your script a go when I get home.

**Comment by paulusjacobus** [comment]
@thinkyhead I keep running into the same issue:

$ git fetch upstream
The authenticity of host 'github.com (192.30.252.xxx)' can't be established.
RSA key fingerprint is SHA256:....something
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.252.xxx' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I seems to have more luck with the Git GUI. However I need to resolve some many merge resolutions that I don't think it is worth the effort. Any suggestions? The pull request to RC seems to have no issues when I do a compare between my fork patch-3 and RC. Should I do a pull request against RC and you pick it up from there?

**Comment by jbrazio** [comment]
Instead of adding ssh based git try https:

``` bash
git remote add upstream https://github.com/MarlinFirmware/Marlin.git
git fetch upstream
```

**Comment by paulusjacobus** [comment]
Thanks @Jbrazio will give that a go tonight.

**Comment by paulusjacobus** [comment]
Managed with @thinkyhead 's help to rebase my fork to resolve the merge issues. Issued a new pull request #3412

**Comment by thinkyhead** [comment]
I have to frequently change from SSH to HTTPS connections depending on where I am. So I wrote this helpful BASH script to do the switch on all my remotes at once:

``` bash
#!/usr/bin/env bash
#
# ghtp (GitHub Transport Protocol)
#
# Set all remotes in the current repo to HTTPS or SSH connection.
# Useful when switching environments, using public wifi, etc.
#

GH_SSH="git@github\.com:"
GH_HTTPS="https:\/\/github\.com\/"

case "$1" in
  -[Hh]) TYPE=HTTPS ; MATCH="git@" ; FORMULA="$GH_SSH/$GH_HTTPS" ;;
  -[Ss]) TYPE=SSH ; MATCH="https:" ; FORMULA="$GH_HTTPS/$GH_SSH" ;;
  *)
    echo "Usage: `basename $0` -h | -s" 1>&2
    echo -e " \e[0;92m-h\e[0m to switch to HTTPS" 1>&2
    echo -e " \e[0;92m-s\e[0m to switch to SSH" 1>&2
    exit 1
    ;;
esac

REMOTES=$(git remote -v | egrep "\t$MATCH" | gawk '{print $1 " " $2}' | sort -u | sed  "s/$FORMULA/")

if [[ -z $REMOTES ]]; then
  echo "Nothing to do." ; exit
fi

echo "$REMOTES" | xargs -n2 git remote set-url

echo -n "Remotes set to $TYPE: "
echo "$REMOTES" | gawk '{printf "%s ", $1}'
echo
```

**Pull request closed without merging**
