### PR TITLE
🐛Adjust display precision in menu_advanced

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Under menu advanced is _MPC_EDIT_ITEMS wich allows you to edit various MPC settings

The first of which is power which can be in the range 0-200
The current code for this menu is 
```CPP
EDIT_ITEM_FAST_N(float31sign, N, MSG_MPC_POWER_E, &mpc.heater_power, 1, 200); \
```
But float31sign only displays a sign, 2 digits, a period and 1 digit, so when the users scrolls over 99 the display looses the 100th digit and starts again from 00

Upgraded this to a  float61  which is unsigned a uses spaces for unused digits 

 ### Requirements

128x64 mono lcd or 20x4 char display
MPCTEMP with MPC_EDIT_MENU
a probe for the probe offset menus. 

### Benefits

Display doesn't loose most significant digit

### Configurations

Example RAMPS Configuration with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER with options to enable both these advanced menus

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/12908468/Configuration.zip)

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/26262

### CODE REVIEW

**Comment by sjasonsmith** [comment]
@thisiskeithb do you have any concerns with this? The MPC change seems clear. I know there's some other conversations ongoing about probe offset ranges, so I'm less sure of that one.

@ellensp, with the larger range does the display look any different while working with small numbers? Do you get extra padded zeroes or anything?

**Comment by thisiskeithb** [comment]
> do you have any concerns with this?

I haven't tested it, but the changes make sense.

**Comment by ellensp** [comment]
Original advanced menu
orginal main menu

Updated advanced menu
updated main menu

Original edit menu
original edit menu

Updated edit menu
updated edit menu

**Comment by thisiskeithb** [comment]
It'd be nice to trim that leading zero when >1.

**Comment by ellensp** [comment]
The sign has been removed as only positive vales are settable
The variables are increased/decreased by 0.1
non used digits are replaced with spaces   

New updated advanced menu

Small value

new small main menu

Large value

new main menu

and new updated edit menu

Small value

new small edit menu


Large value

new edit menu

**Comment by ellensp** [comment]
added float41,  float61 broke display on 20x4

**Comment by ellensp** [comment]
Currently 20x4 displays loses Most significant digit  (should say 40)  

20x4 errer

Scrolling down it turns into 40.

after scroll

Converting to draft till I get some time to work out why this is happening

**Comment by thinkyhead** [comment]
I'm thinking refactor, what about you? We currently have a set of pre-built functions to draw a number with certain features:

- Number of digits, total (not including decimal or sign)
- Whether the number is right-justified (pre-padded with spaces)
- Whether the input is an integer or floating point type.
- How much the number should be scaled before being used for string conversion.
- An added rounding value.

It would be better to have a set of templates that generate new numeric format string conversions on-demand based on the given template parameters. I'll explore that in my weekly experimental coding session.

**Comment by ellensp** [comment]
Sadly the reason I converted it to a draft is still there.. 
On a 20x4 display, if you go to menu  Configuration|Advanced Setting|Temperature and scroll down till Power E1: is displayed on the bottom line.
It displays 0 vs 40 

20x4 errer

If you scroll around a bit more it turns into 40....

At first I though this was another spacing issue, but on debugging the value is lost somewhere..

**Pull request merged**
