### PR TITLE
[1.1.x] Support for the Anycubic Trigorilla Board (1.3 at least)

### PR DESCRIPTION
**Pull request by MatteoRagni**
This pull request adds [Anycubic Trigorilla board](https://www.thingiverse.com/thing:2485534/#files) support. The `pins_TRIGORILLA.h` actually includes the `pins_RAMPS.h` on which the Trigorilla is based, making a redefinition for FAN pin.

The board has been added to `pins.h` and is required with:

```
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_TRIGORILLA
#endif
```
in `Configuration.h`. The pull request is also related to issue #8349.

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for this - can finally ditch the strange configuration file supplied from anycubic.

**Comment by Profex86** [comment]
Hallo, part/filament cooling is not working. with the official firmware from anycubic is the pin D9 for the part cooling. can anyone help me to activate this? thx

**Comment by MatteoRagni** [comment]
Can you try to swap part cooling and extruder fan?

**Comment by Profex86** [comment]
Ok, I modified the Pins_Ramps.h file for the Trigorilla Board. Part cooling works fine. but the extruder fan will not start when the extruder is hot. I can start end stop the Fans with 
M106 P0 S255 (Part cooler Fan)
M106 P1 S255 (Extruder cooler Fan)
in Printrun.

Im use the latest marlin Firmware 1.1.8 I have make some settings.

Autoleveling, soft Autohome, Softwarelimit, dont move before homing, Nozzleclean (G12 P2)

Anycubic Kossel Plus
Trigorilla Board


!MOTHERBOARD 33! <-- in Configuration

[Configuration_adv.h.txt](https://github.com/MarlinFirmware/Marlin/files/1777555/Configuration_adv.h.txt)
[Configuration.h.txt](https://github.com/MarlinFirmware/Marlin/files/1777556/Configuration.h.txt)
[pins_RAMPS.h.txt](https://github.com/MarlinFirmware/Marlin/files/1777557/pins_RAMPS.h.txt) <-- Marked with ****

**Comment by MatteoRagni** [comment]
For me everything works with the original. It depends on the revision of
the board. You have to make sure you are using 1.3. the pinout is different

**Comment by ghost** [comment]
I've tried the bugfix-1.1 with a Kossel Plus. It works, but hotend fan doesn't work.

On my board, the hotend fan ouput label is Fan2 and in RAMPS.h provided by anycubic, the declaration is
```cpp
#define KosselFAN2_PIN 44
```
Should be OK according to http://www.xcsource-pic.com/TE627-E-10-9.jpg

but, there is also the following in the Anycubic files....
`Configuration.h` >> `#define MOTHERBOARD 33`
`boards.h` >> `#define BOARD_RAMPS_13_EFB      33   // RAMPS 1.3 (Power outputs: Hotend, Fan, Bed)`

Then, in pins_RAMPS.h, ther is also 
```cpp
#if ENABLED(IS_RAMPS_EFB)                      // Hotend, Fan, Bed
  #define FAN_PIN        RAMPS_D9_PIN
  #define HEATER_BED_PIN RAMPS_D8_PIN
```
With anycubic files, my fan turn automatically when hotend temp is over 60°c, not with bugfix-1.1

There is a mistake somewhere, but I didn't try yet to fix it.

I don't know my board revision number... is there a way to identify it ?

**Comment by AnHardt** [comment]
@AlexCalibur 
C*_adv.h
```cpp
/**
 * Extruder cooling fans
 *
 * Extruder auto fans automatically turn on when their extruders'
 * temperatures go above EXTRUDER_AUTO_FAN_TEMPERATURE.
 *
 * Your board's pins file specifies the recommended pins. Override those here
 * or set to -1 to disable completely.
 *
 * Multiple extruders can be assigned to the same pin in which case
 * the fan will turn on when any selected extruder is above the threshold.
 */
#define E0_AUTO_FAN_PIN -1
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define E4_AUTO_FAN_PIN -1
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED   255  // == full speed
```

**Pull request merged**
