### PR TITLE
Printrboard RevF cleanup

### PR DESCRIPTION
**Pull request by fiveangle**
-Update Arduino IDE extension descriptions
-Set default motor currents if not defined in Configuration_adv.h
-Support for MINIPANEL LCD
-Support selection of internal or panel SD

### CODE REVIEW

**Comment by thinkyhead** [comment]
Can a PrintrBelt configuration be far behind…?

**Comment by fiveangle** [comment]
PrintrBelt - hahahahaha

**Comment by thinkyhead** [comment]
BlackBelt3D too! haha! hahaha!

It's just cartesian, anyway…

**Comment by fiveangle** [comment]
I don't know how their implementation works, but I expect all the magic happens in the slicer and the kinematics are unchanged because altering the workspace angle by the bed angle just complicates things without any value add.  But does given me pause to consider how one could print a 10' 2x4 ;)

**Pull request merged**
