### PR TITLE
Addressing #7600 (Fix bug introduced with merge #7593)

### PR DESCRIPTION
**Pull request by GMagician**
Bitmaps definitions was wrongly related to HAS_TEMP_BED

### CODE REVIEW

**Comment by marcio-ao** [comment]
Opps. Sorry about that. Good catch!

**Comment by cdedwards** [comment]
too bad this wouldn't work with G29 as well. The arrow indicating which direction to turn moving up and another to indicate going down.. I am new to this, and am still confused on which way I should turn to adjust the bed.

**Comment by GMagician** [comment]
That sound strange...I have not seen what is shown on LCD but from what I know you should see an arrow that display where nozzle will move and a counter clock or anticlock to know how knob should be moved to achieve that movement...it seems so simple

**Comment by cdedwards** [comment]
never seen anything on 1.1.5 and using UBL.. just a number. I have not used this patch however.

**Comment by GMagician** [comment]
Without this patch you can't compile, so I deduct you are not using this feature.
You have to enable 'BABYSTEP_ZPROBE_GFX_OVERLAY'

**Comment by cdedwards** [comment]
I agree it's simple. but, this is only used for BABYSTEP and is not used when on the UBL edit mesh screens. I can compile bugfix, no problem. I would just like to see this feature used in another location for example UBL where it would be handy.

**Comment by GMagician** [comment]
Oh sorry,  I completely misunderstood your question. Currently I have no printer ready to check and see how to add the same for UBL, maybe marcio-ao can look at it and add the same feature in manual UBL

**Comment by marcio-ao** [comment]
@cdedwards: I posted some comments on PR #7645 regarding this.

**Comment by GMagician** [comment]
This this has been addressed by another pull request

**Pull request closed without merging**
