### PR TITLE
Added Gordo3di 's changes to limit the number of alert beeps

### PR DESCRIPTION
**Pull request by Roxy-3D**
A few more changes to limit how many times the printer beeps at the user.

### CODE REVIEW

**Comment by ghost** [comment]
It works AND passes on the RCBugFix branch.... just sayin'.

**Comment by ghost** [comment]
Travis didn't fail, but fussed about this:
```
sketch/Marlin_main.cpp:763:23: warning: type of '__bss_end' does not match original declaration
   extern unsigned int __bss_end;
                       ^
sketch/M100_Free_Mem_Chk.cpp:48:13: note: previously declared here
 extern char __bss_end;
```
I re-defined it in `marlin_main.cpp` for this next commit.
I hope this code runs and that I didn't botch it all up for ya.
I have all of the current M600 nozzle shut down stuff in it. There was a lot missing.

**Comment by Roxy-3D** [comment]
I think we have two Pull Requests for the same thing.   It is my belief that gordo3di's improvements are now consolidated in the other Pull Request.   I'm going to mark this one as 'Do Not Merge' so the Pull Requests don't step on each other.

**Comment by thinkyhead** [comment]
Of course, this would also have been closed because it's against `RC` and not `RCBugFix`.

**Pull request closed without merging**
