### PR TITLE
Allow use of Fysetc SoftwareSerialM

### PR DESCRIPTION
**Pull request by tpruvot**
When testing that, i had a python error (on ubuntu 18.04), so i fixed it...

```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str':
  File "/usr/local/lib/python2.7/dist-packages/platformio/builder/main.py", line 134:
    env.SConscript(item, exports="env")
  File "~/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
    return _SConscript(self.fs, *files, **subst_kw)
  File "~/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
    exec _file_ in call_stack[-1].globals
  File "Marlin/buildroot/share/PlatformIO/scripts/fysetc_STM32F1.py", line 32:
    UPLOADER=platform.get_package_dir("tool-stm32duino") + "/stm32flash/stm32flash",
```

### CODE REVIEW

**Comment by tpruvot** [comment]
related but not in our platformio default : bug #14892

**Comment by tpruvot** [comment]
hmm kinda "unrelated" to the original problem but python script need more love :p

**Comment by thinkyhead** [comment]
Python is still a slightly foreign language for me, so all corrections are welcome.

**Comment by tpruvot** [comment]
yep, Python itself is not really the problem, its more how its linked with the build system here...

**Pull request merged**
