### PR TITLE
Rename M86-M87 & M10-M11 G-Code includes

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
I noticed this file **M86-M87.cpp** should actually be named **M86_M87.cpp**

### CODE REVIEW

**Comment by thisiskeithb** [comment]
[`M10-M11.cpp`](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/Marlin/src/gcode/control/M10-M11.cpp) should be renamed as well.

https://github.com/MarlinFirmware/Marlin/blob/d6961b2626c1ec6fd3d3a1b094ef1d433503ca7d/ini/features.ini#L302

**Comment by thinkyhead** [comment]
Previously considered and passed over as unimportant. Files that implement a range of G-codes are named with a hyphen. Some ranges just happen to encompass only two G-codes.

**Comment by thisiskeithb** [comment]
> Previously considered and passed over as unimportant. Files that implement a range of G-codes are named with a hyphen. Some ranges just happen to encompass only two G-codes.

Every other include with two consecutive G-codes use an underscore instead of a hyphen:

```
src/gcode/control/M993_M994.cpp
src/gcode/feature/pause/M701_M702.cpp
src/gcode/motion/G2_G3.cpp
src/gcode/probe/G31_G32.cpp
src/gcode/units/M82_M83.cpp
src/gcode/temp/M106_M107.cpp
src/gcode/units/G20_G21.cpp
src/gcode/control/M350_M351.cpp
```

**Comment by thinkyhead** [comment]
Being that there are only two "outliers" this change might as well go in. File renames sometimes cause trouble when users merge two copies of Marlin with Windows File Explorer or something like that, so it's good to minimize the renaming of files, at least across minor version updates.

**Pull request merged**
