### PR TITLE
Add BEZIER_CURVE_SUPPORT — G5 command

### PR DESCRIPTION
**Pull request by thinkyhead**
Adapted from https://github.com/giomasce/Marlin/commits/Development by @giomasce and discussed in MarlinFirmware/MarlinDev#417
- G5 command supporting bezier curves in the XY plane
- Minor cleanup of configurations, Marlin.h

### CODE REVIEW

**Comment by jbrazio** [comment]
As self-contained by `BEZIER_CURVE_SUPPORT` which is disabled by default I vote for inclusion on RC. :+1:

**Comment by thinkyhead** [comment]
I just put it together so haven't had a chance to test it. I'm not sure when I will, perhaps tonight. If it works well I will merge it.

**Comment by Grogyan** [comment]
Which slicers produce G5 gcode?

**Comment by giomasce** [comment]
@Grogyan The only programs that produces G5 codes that I know so far is mine Inkscape plugin https://github.com/giomasce/thlaser-inkscape-plugin that I use for my laser cutter (it is usable and I actually use it, although it is still rather alpha). However, given how much it is easier to produce G5 codes instead of having to do that terrible biarc interpolation, I bet that other Gcode produces for laser cutters might be interested in using it.

**Pull request merged**
