### PR TITLE
Option to limit Case Light PWM

### PR DESCRIPTION
**Pull request by GMagician**
This should address #15457.
@komandrik may you test it? I don't have any case light
Once confirmed it works I'll update all other configs

### CODE REVIEW

**Comment by komandrik** [comment]
**THANK!** It works!
I have another request on this topic. Change the Light Brightness control in the Case Light display menu by a percentage.
Is it possible? Do I need to open a new query or can I add to an existing one?

**Comment by GMagician** [comment]
> I have another request on this topic. Change the Light Brightness control in the Case Light display menu by a percentage.

I think that changing to % may break something if gcode use it (it really does?) and keep lcd in % but gcode in 0-255 may lead to confusion...

Better to open a new feature request

**Comment by komandrik** [comment]
> I think that changing to % may break something if gcode use it (it really does?) and keep lcd in % but gcode in 0-255 may lead to confusion...

The percentage change works for the fan in the Temperature / Fan Speed menu. I thought it could be done similarly for light.

Thank you.
I will open a new request.

**Comment by GMagician** [comment]
@komandrik can you tell me where in menu fan is in range 0-100%? I did some check but it seems to me that it is 0-255 (menu -> adjust -> fan speed)

**Comment by komandrik** [comment]
@GMagician Lcd menu > temperature > Fan speed 0%

**Comment by GMagician** [comment]
@komandrik there are to menu sites where fan is used and one is 0-255 and other in %...please test
#15463 to see if this add % to case light as well

**Comment by komandrik** [comment]
@GMagician I checked your recommendation. It works!

**Pull request merged**
