### PR TITLE
M163 M164

### PR DESCRIPTION
**Pull request by Akex2**
Hy
Can you add in marlin the mixing gcode with m163 and m164 please ?

### CODE REVIEW

**Comment by Wackerbarth** [comment]
As presented, this request contains a lot of extraneous material. Since it is adding some (unclear just what) new features (new M commands), after appropriate rebasing, it should be offered as a pull request on the MarlinDev repository.

**Comment by Akex2** [comment]
I don't understand what i must do ? I must post in dev pull request ?

**Comment by Wackerbarth** [comment]
There are two parts to consider. First, for a pull request (to ANY branch), you should base the changes to the latest version of that branch. Thus, the pull request will contain only the changes that you are introducing. The PR presently contains a number of changes that come from other contributors. Those changes need to be removed by basing your PR on a later version on the intended branch.

The other aspect is that the Marlin repository is currently in a Release Candidate phase. We will not be adding new features to this Release and other additions need to first be "proven" as a part of the MarlinDev repository. We do this to help avoid introducing additional problems to the current Release Candidate. (We need not be quite so conservative on the dev branch) Once a feature is established, if appropriate, I, or one of the other commiters, will back-port the feature to the Releasable branch(es) in the Marlin repository.

**Comment by Akex2** [comment]
ok thank you for that clarification Wackerbarth
I don't know the exact code to make these changes
Is too complicate for me
I was just a propose, a featur a application
sorry for the inconvenience
Thanks for your work
Alex

**Comment by KiteLab** [comment]
This PR includes NO code by @Akex2. Likely this should be a 'feature request'.
The right place for that would be: https://github.com/MarlinFirmware/MarlinDev/issues

**Comment by Akex2** [comment]
Thanks kitelab
Sorry

**Pull request closed without merging**
