### PR TITLE
Fix status LEDs update when reinitializing the display

### PR DESCRIPTION
**Pull request by AnHardt**
Fix status LEDs update when reinitializing the display

By using the regular update function during init.

Fixing #2683

### CODE REVIEW

**Comment by AnHardt** [comment]
As far i can see i'm working on the RCBugFix branch. What is it for if not for bug fixing.

**Comment by Wackerbarth** [comment]
@AnHardt -- Yes, you are working on the BugFix branch. However, that doesn't mean that everything posted as a possible correction is, immediately, a verified fix.  When we get to a point of Release Candidate, we need to exercise additional care to avoid introducing errors that were not previously present.

Now that you have flagged this as "Needs Testing", I know its status. Hopefully someone will be able to verify the fix and flag it as ready to merge.

**Comment by AnHardt** [comment]
Feel free to look in the according issues.

**Comment by justmyopinion** [comment]
This one is ready for merging. Tested and verified working as intended.

**Comment by AnHardt** [comment]
@justmyopinion 
This one passes Travis, but Travis is not testing the specific configuration this is needed for.
The forward declaration is still not in.

I can't remember your board, display combination to test this again.

**Comment by justmyopinion** [comment]
My board is Azteeg_X3 and wiki display
forward declaration is needed in
ULTRALCD_IMPLEMENTATION_HITACHI_HD44780.H

static void lcd_implementation_update_indicators();

**Comment by justmyopinion** [comment]
My commits stay local at my own fork.
How are they transferred to Marlin RCbugfix?

**Comment by Wackerbarth** [comment]
@justmyopinion -- Rather than trying to get this working in RCBugFix, I think that it would be more appropriate to first get it working in MarlinDev. Once we have it working over there, we can back-port the changes to the RC branch as a bug fix.

Once a potential branch goes into the Release Candidate phase, we should not be adding ANY code that might be even questionable, much less something that needs testing.

Following the style of MarlinDev PR #253, you should provide the configuration parameters that are needed to actually invoke the code being proposed.

You might look at https://github.com/Wackerbarth/MarlinDev/tree/ConfigureInProgress/configurations/custom
to see how you can maintain your personal configuration files in the source tree without conflicting with the "standard" (whatever that is) configurations provided.

**Comment by AnHardt** [comment]
@Wackerbarth 
a.) This IS a bug.
b.) MarlinDev is for new features. Of course bug fixes should be applied there too.
c.) @justmyopinion  is my tester
d.)

**Comment by Wackerbarth** [comment]
I'm just suggesting that, because of the complexity of the changes, and the fact that MarlinDev has a structure better suited to handling the non-standard configurations, and the fact that, thus far, MarlinDev has not included significant operational changes, it might be advantageous to utilize that platform.

I am reluctant to introduce the combination of changes that are present in the present PR in their present form without first separating them with respect to functionality and testing to verify that each change is not harmful to other, existing, configurations.

The entire purpose of going to a Release Candidate was to allow us to "get something to market" for many of our users. It is not to eliminate ALL known bugs. If we hold up the release process for this issue, and the next, etc., we will never have a release.

**Comment by Roxy-3D** [comment]
> I am reluctant to introduce the combination of changes that are present in the present PR in their present form without first separating them with respect to functionality and testing to verify that each change is not harmful to other, existing, configurations.

And then continuing on with something like:

> And once WE get that done in MarlinDev I'll help move it over to RCBugFix.

Would make everybody feel like we are working together as a team.

**Comment by justmyopinion** [comment]
Ok ..that's enough..
i quit, so you folks can do the maintainance yourself.
I do not want to be part of this crazy personal circus that have ruined the Marlin community for so long.
Good luck.

**Comment by AnHardt** [comment]
@justmyopinion 
You can't commit directly to a branch where you have no write access to.
Just like in your `patch-1`, 
fork a fresh branch from `MarlinFirmware/RCBugFix`,
make your changes,
commit the changes to your new branch,
push the branch to your public repository and
make a PR from there to  `MarlinFirmware/RCBugFix`.

Back to the bug.
For a LCD_I2C_VIKI this patch is not compiled in. How could it help you? 
The LCD_I2C_VIKI has no LCD_I2C_TYPE_PCF8575 but a LCD_I2C_TYPE_MCP23017
Likely you adapted it to the right place.
Anyway, for the  LCD_I2C_TYPE_PCF8575 on the LCD_I2C_PANELOLU2 there is exactly the same LED initialization  problem.

Made some changes. Please recheck.

**Comment by AnHardt** [comment]
@Wackerbarth 
While writing you last comment, this PR was a one liner, affecting some LEDs connected to a single type of TWI-IC, for the short time between initialization and the first regular update. If this is to complex for you, ... .

**Comment by Wackerbarth** [comment]
No, if that is all that it is, I was confusing it with changes that @justmyopinion has been working on that affect the functions handled in the ISR. (And I strongly agree with the need for those improvements). My only concern is that we don't go backwards and make things worse for any users that are not having issues with the present RC2 functionality.

**Comment by Roxy-3D** [comment]
> No, if that is all that it is, I was confusing it with changes that @justmyopinion has been working on that affect the functions handled in the ISR.

I do need to say I was thinking the same thing for a while.   I was hoping your fixes were related to that issue because I want that issue to get resolved ASAP.    I don't have my new Delta up all the way, but I'm seeing it stutter.

**Comment by AnHardt** [comment]
Added some #undefs before redefining `LCD_CLICKED` to avoid warnings in MarlinDev (https://github.com/MarlinFirmware/MarlinDev/issues/275).

I will port this later to Dev `master`.

**Pull request closed without merging**
