### PR TITLE
update sim to latest IDEX version

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Update simulator used to latest release with IDEX support.

Update Simulated board pins with additional extruders heaters and thermistor pins

Rename pins from Linux to Native.  

### Requirements

the SIMULATOR 

### Benefits

Simulates IDEX

### CODE REVIEW

**Comment by ellensp** [comment]
Sim has a few issues, "spiky" render, delta broken, so on hold for now

**Comment by thinkyhead** [comment]
Anything in this PR triggering the sim issues, or do they still exist without this PR?

**Comment by ellensp** [comment]
Both issues are only in the sim.
The delta issue has been fixed, but the rendering issue remains

**Comment by thinkyhead** [comment]
Went ahead and merged everything except the change to the MarlinSimulator commit ID.

**Comment by thisiskeithb** [comment]
> The delta issue has been fixed, but the rendering issue remains

There's also been a handful of updates, so the Sim render issues may have been resolved?

image

 https://github.com/p3p/MarlinSimUI/commits/master/

**Pull request closed without merging**
