### PR TITLE
Release 1.1.0-RC5

### PR DESCRIPTION
**Pull request by thinkyhead**
We've had a lot of bug patches lately. This is a new version so we can say farewell to RC4.

### CODE REVIEW

**Comment by jbrazio** [comment]
Will it be our last RC for 1.1.0 ?

**Comment by Blue-Marlin** [comment]
Maybe.
If it survives some days without discovering newly introduced bugs.
Again too many unrevived last second changes to have an educated guess.

**Comment by ghost** [comment]
Well, README.md is still RC4.

**Comment by thinkyhead** [comment]
Moving quickly towards a final release now. We just need to squeeze out the last few issues (and figure out which are actually configuration errors). I'll be sure to properly update the `README.md` for RC6. That should be pretty soon, but I don't want to do another RC without patching for the most active issues.

Once the current LCD menu and "Move Axis" issues are patched, I think we're 95% there. It might help to add `MECHANICAL_PROBE` before release, because it's the only solution for people with those kinds of probes.

For the remainder of this release cycle I vow not to do any more "revamps" to deal with systemic flaws. Just patch up the existing stuff and make sure that nothing is crashing or acting bizarre.

Thanks to everyone who's been keeping an eye on all the recent changes and adding their feedback. I've been able to do a lot more testing lately, but don't have access to deltas and core machines, so your testing is invaluable.

**Comment by CONSULitAS** [comment]
@thinkyhead just updated the Readme.md with hints to RC5 and Arduino IDE on RCBugFix

**Pull request merged**
