### PR TITLE
Support for the Anycubic Trigorilla Board (1.3 at least)

### PR DESCRIPTION
**Pull request by MatteoRagni**
This pull request adds [Anycubic Trigorilla board](https://www.thingiverse.com/thing:2485534/#files) support. The `pins_TRIGORILLA.h` actually includes the `pins_RAMPS.h` on which the Trigorilla is based, making a redefinition for FAN pin.

The board has been added to `pins.h` and is required with:

```
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_TRIGORILLA
#endif
```
in `Configuration.h`. The pull request is also related to issue #8349.

### CODE REVIEW

**Comment by MatteoRagni** [comment]
I'm sorry for the useless `a19f33f` commit. I understood too late that was better to include the original pins_RAMPS.h

**Comment by MatteoRagni** [comment]
Mh.. it is missing a line in `board.h`. What do you think about ths number?

```
#define BOARD_TRIGORILLA        364   // Tri(3)G(6)orilla A(4)nycubic version 1.3 based on RAMPS EFB
```

**Comment by thinkyhead** [comment]
Sorry, we can only accept PRs targeted at our work branches, and not at release branches. Please re-do this PR starting with `bugfix-1.1.x`. For bonus points please make a companion PR for `bugfix-2.0.x`.

Thanks!

**Comment by ghost** [comment]
I have made this PR at #9050

**Pull request closed without merging**
