### PR TITLE
Added "IfnDef" around some definitions

### PR DESCRIPTION
**Pull request by RFBomb**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Wrapped several of the basic values in "#ifndef " statements, following the example set the by the "Motherboard" variable. 
Allows users to more easily have a custom config they can #include with their basic options turned on for easier updating the firrmware, with things such as the Motherboard, Extruders, Material Diameter, bed size, etc.).

(Many options are commented out by default, so #Including a custom config can turn these on without any issue, but some things like "EXTRUDERS" are defined here, which can overrule the #Included file if they are defined without the if statement I added here.) 

### Benefits

This change will allow people who want to go this route to more easily keep all of their settings in a file that is migrateable between firmware versions, while allowing the main Configuration.h file to receive bugfixes/additions (that would be missing / problematic if that user just copied their configuration.h file from the old version to the new version)

This allows users to have a custom config file with several DEFINES in it with basic settings that they can #include without having to modify the Configuration.h values every time they want to update the firmware, they just have to copy this custom file into the new firmware folder.  

I've only done some base values here that have are not able to be overwritten with EEPROM settings, as the EEPROM settings should carry over between firmware updates (atleast they do on my board SKR1.3). 

### Related Issues

None, was just providing an easier route for advanced users to maintain settings / options for a printer setup than having to look for every setting within Configuration.h when versions are updated. (Useful for people that do bugtesting on new firmware versions, or dislike redoing all the various settings in a 2500 line (and growing) file.

The attached file (which github wouldnt let me upload as a .h file) is the proposed accompanying file that the user would be able to use with these changes. 

[CustomConfigOverrides.txt](https://github.com/MarlinFirmware/Marlin/files/4500021/CustomConfigOverrides.txt)

Totally understand if these aren't pushed into the main branch, as this was an edge case I solved.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
But `Configuration.h` *is* the user’s config. 

I’m confused as to why you’d need another level of includes/overrides since it adds more noise to the default.

**Comment by RFBomb** [comment]
@thisiskeithb  I'm not saying we _need_ it, which is why I wrote that I don't expect this to be implemented. I just had several issues with my printer, and was recommended to try out various bugfix versions / official releases. 

I found it quite tedious to go through the Configuration.h file for every release and putting in all of my personal settings, so I just wound up creating this base file and writing the #include statement to re-activate the various options I have (BLTouch, UBL, Babystepping, etc) as opposed to going through and uncommenting every single one of those in the configuration.h files for the various releases. 

I tried using configuration.h from a previous build, but found that several variables / definitions were renamed, and it reported numerous errors at compile time. There also may be various bugfixes or additions in configuration.h / configuration_adv.h that the compiler looks for. Using a previous configuration file from a different build would result in not getting those fixes / improvements / items the compiler may be looking for that don't exist in the previous version. Basically, I made it overall less work for myself to go to a new version, by just #Including this file, which reactivates the various options & settings I want activated instead of going through configuration.h and manually editing all of those values. Plus, it shortened the amount of lines i have to look through to make adjustments (~100 vs ~2300)

This statement already exists:
```
#ifndef MOTHERBOARD
  #define MOTHERBOARD [YourMotherboard]
#endif
```
so  all I did was expand logic to only define items about other base settings people have on their printers. By rights, we likely don't need that #ifndef statement unless someone else is doing exactly what I suggested here (they could just be using the settings the firmware is always released with)

This is also a purely options thing for people to do, most likely only people that are testing the new releases / advanced users will have any interest in it.

**Comment by sjasonsmith** [comment]
If you find yourself updating a lot, I suggest you learn to use git to handle most of the merging for you. There are several different strategies for managing personal configurations using git, and I'm sure we don't all do it the same way. I can usually apply my configs to any branch I want in under a minute, and only rarely have to stop to deal with conflicts when something changes.

**Comment by thisiskeithb** [comment]
Rebasing configs with git works great!

**Comment by RFBomb** [comment]
OK, I'll look into git and close this suggestion for now

**Comment by RFBomb** [comment]
Ok cool, I got git working in Visual Studio Code, but whenever I try to
switch branches it throws out my custom configuration and replaces it with
the stock one.

I also get GIT errors about having uncommitted changes (in my config) when
I try to switch branches.

I’ve had to stash that change then “pop latest stash” to work around it. Is
that the correct / only method to work with this?

**Pull request closed without merging**
