### PR TITLE
BLTouch V3.1 changes

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Continuation here from #14064 

Picking up as @FanDjango is expecting to be occupied for the next few days.

@thinkyhead @Roxy-3D @Bob-the-Kuhn

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
Ok, I think this now encompasses everything that was left open. Works good across the 3 machines I tried it on. Feel free to beat up anything I missed @Fandjango

**Comment by InsanityAutomation** [comment]
Ok, not sure why a rebase now shows tons more differences...

Maybe @thinkyhead can answer that one better...

**Comment by InsanityAutomation** [comment]
Githib is dumb, I literally grabbed a 30s old archive of the repo, copied gcode.h and M916-918.cpp  into this and pushed it and it still shows theyre different....

**Comment by thinkyhead** [comment]
When rebasing, first make sure you have the latest bugfix in all the places:
```
git branch -D bugfix-2.0.x
git fetch upstream
git checkout upstream/bugfix-2.0.x -b bugfix-2.0.x
git push --set-upstream origin bugfix-2.0.x
```
If you take a note of the HEAD commit before you try to rebase, you can always get back to it with:
```
git reset --hard 8f7e6d5c
```

Once you get back to where you started from, you can first squashed everything down to a single commit. One way to do this is with interactive rebase. For example, to squash 4 commits down to 1 you might just start 4 commits back in time…
```
git rebase -i HEAD~4
```

If you have your changes down to a single commit, you can start afresh and just try applying the one commit to the latest HEAD…
```
git reset --hard upstream/bugfix-2.0.x
git cherry-pick 1a2b3c4d5
```

When all else fails, you can usually get most of the way there with `git diff ...`.

Once any branch is cleaned up and rebased on `bugfix-2.0.x` it can be brought over to the PR, throwing out all the other dross…
```
git checkout BLTouchV31Followups
git reset --hard my_fixed_up_branch
git push -f
```

**Comment by thinkyhead** [comment]
Rebased and squashed! To get this into your working copy:
```
git checkout BLTouchV31Followups
git fetch origin
git reset --hard origin/BLTouchV31Followups
```

**Comment by Roxy-3D** [comment]
@Thinkhead   It would be helpful to merge this branch when possible.    It is my belief everybody that has been working on the BL-Touch issues is in agreement these changes make sense.

**Comment by InsanityAutomation** [comment]
Should have known youd get it fixed before I could!!! lol 

https://github.com/InsanityAutomation/Marlin/tree/BLTouchV31Rebased

At least I cooked bacon in the meantime....

**Comment by thinkyhead** [comment]
Well, I will leave this be and see how it does with Travis CI.

BLTouch options are multiplying and it might be good to move them to `Configuration_adv.h` so non-BLTouch users can ignore them during probe selection.

**Comment by Roxy-3D** [comment]
> BLTouch options are multiplying and it might be good to move them to Configuration_adv.h so non-BLTouch users can ignore them during probe selection.

How about a compromise?   I agree with the high level direction.   But it would be helpful to get the working code merged.    

How about we merge, and the next Pull Request moves the options to the Configuration_adv.h file?

**Comment by InsanityAutomation** [comment]
Im good with that, and ill probably use the dialog that sd start and stop have now for setting drain mode in the next PR so we have text room for a big warning!

**Comment by InsanityAutomation** [comment]
And we have a happy travis now

**Pull request merged**
