### PR TITLE
"Add Laser test fire function"

### PR DESCRIPTION
**Pull request by descipher**
### Requirements

LASER_FEATURE

### Description

Add two menu items under the Laser Control SUBMENU when LASER_FEATURE is defined to fire a laser test pulse. Item 1 sets the adjustable fire time from 1 to 999 milli-seconds and the second menu item fires the trigger. A beep will occur if USE_BUZZER is defined. If PWM is supported it will fire at the power PWM setting that was previously set, if not set it defaults to 80%. No PWM results in full power with the set time duration.

### Benefits

Supports alignment, testing and calibration of more powerful laser rigs. 

### Configurations

#define LASER_FEATURE
#define REPRAP_DISCOUNT_SMART_CONTROLLER

### Related Issues

None

### CODE REVIEW

**Comment by LinFor** [comment]
This feature could be very useful!

**Comment by descipher** [comment]
Tested cleanup changes, looks good on the scope. Thanks :)

**Comment by shitcreek** [comment]
Codes look about right to me, but I won't be able to flash and test it until Thursday.

**Review by shitcreek — APPROVED** [review]
Flashed and tested working.

**Pull request merged**
