### PR TITLE
UBL: Log and display G29 progress

### LINKED ISSUE #13934: [FR] Progress for G29
During a G29, would be usefull to show, on LCD (and report via USB, for octoprint or similiar) the completed probes and the remaining ones, like:

`Calibrating 1/10`

Something similiar to the Original Prusa autocalibration.
Very useful with huge meshes and slow probe speed. My mesh is built with 10 (thinking to increase to 12) points, 3 probes and takes more than 1 hour. :)

Currently a generic "Doing G29" is shown, something more usefull like a progress indicator would be nice and useful

### PR DESCRIPTION
**Pull request by guestisp**
Add progress updates for G29 meshes via terminal and via LCD 
Fix #13934

### CODE REVIEW

**Comment by guestisp** [comment]
sneak preview image :)

download

**Comment by thisiskeithb** [comment]
144 points?! Wow!

**Comment by Roxy-3D** [comment]
Line 762 has extra white space added for no reason.    That drives Thinky bonkers....
And line 765 is extra white space for no real purpose...    

image

**Comment by guestisp** [comment]
> 144 points?! Wow!

Just to be sure that the bed leveling is not an issue during the print. :D If first layer doesn't stick, it's not the bed for sure :D :D :D :D

@Roxy-3D fixed the indentation issues.

**Comment by InsanityAutomation** [comment]
serialechopair shouldnt be used for a fixed string and this will need a good bit more to be complete. Ill try to sit down and throw some more at this one this weekend if I have time around the singlenozzle issue, idex full control offsets, and motor city comic con.

**Comment by Roxy-3D** [comment]
> 

Specifically...  InsanityAutomation is concerned about the extra RAM usage.  A literal string gets copied to RAM and C Runtime Init.    But we have functions declared to keep it from consuming any RAM and to read the literal value out of Program Memory.

Probably switching to the functions declared in Serial.cpp will alleviate the concern.  For example:
```
void serial_echopair_PGM(PGM_P const s_P, int v)           { serialprintPGM(s_P); SERIAL_ECHO(v); }
```

**Comment by guestisp** [comment]
Which function should I use instead ? I've tried with set_message (or something similiar, I don't remember exactly right now) and I wasn't able to print anything (or i've triggered some hard-crash due to inactivity)

**Comment by Roxy-3D** [comment]
The LCD stuff has changed and I haven't been back into it looking at things since that happened.   

But you want to use one of the status update functions.   Find something else that updates that line of the LCD screen and search for it.    Almost for sure, that status update function will be taking a Program Memory literal string for the message.

**Comment by guestisp** [comment]
I've used this:

```
ui.set_status_P(msg_P);
ui.quick_feedback();
```

like in https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/feature/bedlevel/ubl/ubl_G29.cpp#L946 but hardly crash for an activity timeout, like it's expecting user interaction (not at my office at the moment, i can't check better)

**Comment by Roxy-3D** [comment]
Yes!   Functions with a _P() suffix get their parameter from Program Memory.

**Comment by guestisp** [comment]
> Yes! Functions with a _P() suffix get their parameter from Program Memory.

So I have to use a string stored as constant and not a plain string, right ?
I've not tried this. i'll try tomorrow or next monday.

Just a question: how can I use a constant and also concatenate a different string with `_P()` function ? As I have to write the current and total probe point, so I can't use just an hardcoded constant

Keep in mind that I'm new to marlin and i'm not a C++ programmer, i'm just trying to contribute with somehing simply but useful

**Comment by InsanityAutomation** [comment]
I was looking at the serial echo lines with the earlier comment. ECHOPAIR is looking for a variable to follow. ECHO(LN) or ECHOPGM(LN) can be mix and matched to get as much as possible from PGM.

**Comment by guestisp** [comment]
So, what i've used is correct?

**Comment by Roxy-3D** [comment]
>> Yes! Functions with a _P() suffix get their parameter from Program Memory.

> So I have to use a string stored as constant and not a plain string, right ?  I've not tried this. i'll try tomorrow or next monday.

No.   It will work with a literal string that is defined with a #define, and it will work with a string in the form xxx_P("Some string.");        But with that said....   The correct way to do this is define a constant for the English version of the string in language.h   And then use that constant in the actual code.   At that point, when ever a non-English language file is updated, the new constant will get propagated into the various languages.   When that happens, non-English speaking people will have better use of the feature.

> Just a question: how can I use a constant and also concatenate a different string with _P() function ? As I have to write the current and total probe point, so I can't use just an hardcoded constant.

I don't believe you can in its purist form.  (Somebody else may jump in here with a correction!)   In this case I would do some form of  sprintf(RAM_string, STRING_CONSTANT # "%d / %d", done_pnts, total_pnts);    And you would use a form of the LCD status update function that did not have a _P() suffix on the name.

> Keep in mind that I'm new to marlin and i'm not a C++ programmer, i'm just trying to contribute with something simply but useful

Yes!   Thank You for your efforts!

**Comment by Roxy-3D** [comment]
> So, what i've used is correct?

Serial_Echo_xxxx() functions are used to send information out the serial port.   This is typically only useful if the person has a host console such as PronterFace or Repetier connected up to the board.

The LCD Status functions display information on the LCD Panel.

**Comment by guestisp** [comment]
I'm using both, the serial echo and a, probably wrong, function to display something on the LCD

The serial echo is probably even more useful than the LCD, as could be used by third party developers to develop plugins than show the G29 current status, in example, in octoprint would be possibile to see how many probes are left

**Pull request merged**
