### PR TITLE
BLTouch V3.0 support

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Add new commands and setup for V3.0 to function plug and play with older sensors

See #13345 

Added the 3 new commands to menus
Added logic to check the state of the endstop pullup resistor to determine if in 5v or 3.3v/5v open collector mode and set explicit 5v if endstop pullup is on
Found the old probe ignores the new method of deploy for the new probe, so fire that after the original deploy command to change mode if v3 is present or safely ignore on v2

### CODE REVIEW

**Comment by ghost** [comment]
Think I would have called it 5V_MODE and OD_MODE for "open drain" instead of OPENMODE

**Comment by Roxy-3D** [comment]
> Think I would have called it 5V_MODE and OD_MODE for "open drain" instead of OPENMODE

I would prefer OPEN_DRAIN_MODE over OPENMODE!

**Comment by InsanityAutomation** [comment]
I have to disagree with some of the changes here. The point of proving out that the new servo angles do NOT affect the older version sensors is to ensure that they can be hot swapped. Most users will have no idea which version they have until it crashes with this.

**Comment by Minims** [comment]
compilation fail with G34. 
`#include "../../feature/bltouch.h"
`

is missing in G34_M422.cpp

`Marlin/src/gcode/calibrate/G34_M422.cpp: In static member function 'static void GcodeSuite::G34()':
Marlin/src/gcode/calibrate/G34_M422.cpp:111:7: error: 'bltouch' was not declared in this scope
bltouch.reset();
^
*** [.pioenvs/megaatmega2560/src/src/gcode/calibrate/G34_M422.cpp.o] Error 1`

**Comment by InsanityAutomation** [comment]
@Minims added in #13422 thanks

**Comment by Roxy-3D** [comment]
@FanDjango 
Can you send me you shipping address?

**Comment by ghost** [comment]
@Roxy-3D 
Certainly, may I ask why?

**Comment by Roxy-3D** [comment]
Antclabs wants to send people that are helping resolve the compatibility issues a BL-Touch v3.0 probe.

**Comment by Minims** [comment]
I've tried the last version with my "Legacy BLTouch". It seems working, G28, G29, G34 are OK. 
But the BLTouch commands in the LCD Menu are not working anymore(Like AutoTest for example).But I still don't know why. I revert commit about V3 and it works again. Any ideas about this ? 

Behavior : The BLTOUCH make a DEPLOY and then BLTOUCH seems freeze. No RETRACT, RESET has no action.

Here is my configuration : 

`#define BLTOUCH
#if ENABLED(BLTOUCH)
  #define BLTOUCH_DELAY 375   // (ms) Enable and increase if needed

  // BLTouch V3.0 and newer smart series
  //#define BLTOUCH_V3
  #if ENABLED(BLTOUCH_V3)
    //#define BLTOUCH_FORCE_5V_MODE
    //#define BLTOUCH_FORCE_OPEN_DRAIN_MODE
  #endif
#endif` 


EDIT : 

 - It does not work in BLTouch Menu available in Configuration.
 - But it works with BLTouch AutoTest in Configuration > Advanced Settings.

**Comment by caseyjmorton** [comment]
Any chance this PR can be cherry picked into the 1.1.x branch?

**Comment by Roxy-3D** [comment]
It is my opinion it might make sense to do it for the BugFix 1.1.x branch.    But it probably doesn't make sense to alter the 1.1.x branch.

**Comment by caseyjmorton** [comment]
Fair enough, I’m fine with either. I would just like to be able to run my
BLTouch on a stable firmware.

**Comment by Roxy-3D** [comment]
If you generate a Pull Request for the BugFix 1.1.x branch with these changes...    It will start a discussion with the relevant people with regard to whether it should happen.

**Comment by caseyjmorton** [comment]
Will do!

**Comment by reloxx13** [comment]
connect #13345

**Pull request merged**
