### PR TITLE
Improvements for LV8729 stepping

### PR DESCRIPTION
**Pull request by chai-md**
### Description
Sometime, losing steps in quick movement under enough torque.
At first, I increased `MAXIMUM_STEPPER_RATE`.
That freed me from losing steps, but wasted MCU load.

I found too long `MINIMUM_STEPPER_CYCLES` in LV8729 settings.
It's up to about 7.7us. Too long blocking time cause uncompensatable missing steps with multiple steps per interrupt feature.
I modified `MINIMUM_STEPPER_CYCLES` to 500ns, and `MAXIMUM_STEPPER_RATE` to 200000.

But I have not understand ISR code enough for absolutely recommendation.
It's only suggestion.

### Benefits
Free from losing steps, without high MCU load.

### Related Issues
Perhaps, Trinamic drivers would suit that `MINIMUM_STEPPER_CYCLES` to 100ns, typical value from data sheet.
Duty ratio is not problem for interpolation in single edge mode.

### CODE REVIEW

**Comment by forkoz** [comment]
Has anyone else confirmed this? I don't think I hit the maximum stepper rate, if I understand it correctly, you have to be going really fast to hit that. Even at 1/64 I'm not. Stepper pulse has also been fine at 1. That one  I guess could possibly be an improvement... but is this 32 bit board or 8 bit?

**Comment by chai-md** [comment]
If you use 1.8degree steppers, I agree with you. Normally setting is 320steps/mm, able to350 mm/s.
I'm using 0.9degree steppers and LPC1768, 640 steps/mm for less vibration and restricted about 200mm/s with default LV8729 driver settings. Because total stepper positive pulse time is up to 0.985s per second without negative pulse time.

**Comment by forkoz** [comment]
That is super fast. I'm guessing this really can't hurt, but won't help me and most.

**Comment by chai-md** [comment]
Yes, that wouldn't help you just now.
As that suggests making extra rooms for more complicated compensate algorithm like LA, to release needless waiting loops in ISR.

**Comment by thinkyhead** [comment]
On AVR the smallest possible stepper delay is 1 cycle, which is 62.5ns. Each CPU cycle of code in the delay handler adds another 62.5ns delay. So on AVR a delay of "0" is likely to actually amount to a delay of at least 250ns just for the code between the pulse start and end. On ARM processors the "0" µs delay will be much closer to actually 0µs. On DUE it will be something like 12ns for a single CPU cycle, and on faster boards down to around 3ns.

**Comment by chai-md** [comment]
I'm tracing this still now, and I found some cases of problem in this patch, negative value of added pulse ticks or enforce as 1us cycle.
I'm thinking there is room of efficiency still now, but I should understand behavior of ISR more strictly.

**Comment by chai-md** [comment]
I got Saleae Logic Pro 8, logic analyzer, now!

And I confirmed malfunctioning of multiple steps per interrupt feature in original code.
My patch code corrects blocking time in ISR, in the other hands, pulse time is not corrected.
This code works enough in practically, but in partial as logical. I confirmed that with Logic Pro.

I'll make pulse time to be corrected, too.

**Comment by chai-md** [comment]
SKR1.3, LPC1768-100MHz, LV8729 xy-1280step/mm up to 600mm/s.
image

Confirmed about 760k steps/s and no missing steps!!!!
Multiple steps per interrupt feature works correctly at very high speed rate,
and are not restricted 448k steps/s.

**Comment by thinkyhead** [comment]
Good looking results! Is it working consistently across a wide variety of speeds, with `ADAPTIVE_STEP_SMOOTHING` enabled and also with it disabled?

**Comment by chai-md** [comment]
>with `ADAPTIVE_STEP_SMOOTHING` enabled and also with it disabled?

Yes, that's with `ADAPTIVE_STEP_SMOOTHING` enabled.

**Pull request merged**
