### PR TITLE
[2.0.x] Ability to add customized user interface code.

### PR DESCRIPTION
**Pull request by marcio-ao**
This PR includes modifications to Marlin required for integrating the touchscreen interface developed by LulzBot.

This PR superseeds #10619 and has been written in a way to allow source for any customized UI code to be placed into "src/extensible-ui/lib" and distributed outside of Marlin. It provides the necessary glue code for integration and an initial API (as a namespace) that exposes enough Marlin functionality for a basic touch screen UI.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Added a commit with some tweaks:
- Less repetition of declarations in `ultralcd.h`.
- `ENABLED` is preferred over `defined` for configurable options.
- Whole `.h` files shouldn't be wrapped `#if ENABLED(...)`. Wrap the `#include` instead.

I'm not sure yet how useful it is to insert an extra layer between the existing LCD methods and the functions called. I feel it would be a more viable initiative to clean up and improve the `ultralcd.cpp` code first (_e.g._, move the menus to a separate file, consolidate core functionality in a main [static] class, add a separate menu/screen class, and so on). Then the core `ultralcd.*` code should start to take on extensibility features as needed. I'm concerned that this perpetuates the same paradigm, just adding a new limb, when we already know we're going to be reworking the core LCD code not long after 2.0 is released.

**Comment by marcio-ao** [comment]
> I'm not sure yet how useful it is to insert an extra layer between the existing LCD methods and the functions called.

The reason I inserted the extra layer is to provide a well-defined interface. The ultralcd code never defined such an interface, though a lot of new LCD implementations attempted to use it as such. As you say, this gave it many limbs, which makes pruning down the "ultralcd" code and the myriad of code that depends on it much more difficult. While my API layer is yet another limb, it attempts to provide a firewall such that modules using it does not need to reach over and add more tentacles into "ultralcd". It is just a divide-and-conquer strategy.

One difficulty I see with "ultralcd" is that it attempts to be a unified interface for everyone. In practice, this means a lot of compromises. When you are taking about high-res touch screens, I think it will be very difficult to come to a consensus. Some people may want a pretty Hollywood-esque UI (the gorgeous Raise3D UI comes to mind), other people may want a feature-packed interface with less emphasis on looks (such as the Due panel). Since there is no way to really come up with one interface that pleases everyone, I think Marlin should simply provide a well-defined API for people to build UI modules. This will allow different implementations to compete and evolve. This is what I tried to accomplish.

I intentionally made no changes to UltraLCD in an attempt to minimize the modifications that would need to be merged. I would think that in the future, the "legacy" UltraLCD interface could be re-worked into a UI module and the build-in UltraLCD code could be removed.

-- Marcio

**Comment by marcio-ao** [comment]
As an FYI, I created a branch for Marlin bugfix-2.0.x with the FTDI EVE code. This demonstrates how the interface could be used:

https://github.com/marcio-ao/Marlin/tree/bugfix-2.0.x-with-ftdi-eve-touchscreen

@thinkyhead : This code should work with the panel you picked up at MRRF. You may need to adjust the configuration values in "extensible-ui/lib/ui_config.h"

**Comment by thinkyhead** [comment]
> One difficulty I see with "ultralcd" is that it attempts to be a unified interface for everyone.

In the long run the term "ultralcd" should refer specifically to displays where the full contents can be altered, and therefore can be told to display different "screens" and "menus." I agree that starting with the Malyan LCD the `ultralcd.*` files have been stretched in a bad way.

There should be a central "lcd.h" or "ui.h" file that decides whether to include `ultralcd.h` (for the graphical and character LCDs) or whether to include `malyan.h`, etc. And then each of these headers should sub-class from a root `base_ui` class — preferably a static class. The sub-class headers would define macros like `HAS_MENUS` and so on. The screens and menus should be split into a separate file — just one at first.

Anyway, this is coming along well, and I think it's a good starting-point for standardizing the interfaces. There are some stylistic changes we might still make. Marlin has been standardizing around `names_with_underscores` over `namesWithCamelHumps`, for example, and there are some syntactical benefits of using static classes over namespaces.

Right now we really need to focus on getting 1.1.9 out asap so we can return to this and focus our attention on a fully comprehensive LCD code cleanup for 2.x. The only thing holding up 1.1.9 is a mysterious lost steps issue, so that's the only issue that matters right now…

**Comment by marcio-ao** [comment]
> In the long run the term "ultralcd" should refer specifically to displays where the full contents can be altered, and therefore can be told to display different "screens" and "menus."

One of the things the current ultralcd code does well is that it supports both the graphical display and the text based displays using a common menu structure. This is a great solution for a small display with an encoder, but I do not think this concept will work well with larger touch panels. With a larger display, there are so many creative possibilities that I think trying to impose a fixed structure would be a disservice.

> there are some syntactical benefits of using static classes over namespaces.

I initially started with static classes for the API, but switched over to namespaces because of the "using" keyword. With classes, I had very tedious code that looked like this:

```cpp
bool TemperatureScreen::onTouchHeld(uint8_t tag) {
  switch(tag) {
    case 20: Extensible_UI_API::setTargetTemp_celsius(0, Extensible_UI_API::getTargetTemp_celsius(0) - getIncrement()); break;
    case 21: Extensible_UI_API::setTargetTemp_celsius(0, Extensible_UI_API::getTargetTemp_celsius(0) + getIncrement()); break;
    case  2: Extensible_UI_API::setTargetTemp_celsius(1, Extensible_UI_API::getTargetTemp_celsius(1) - getIncrement()); break;
    case  3: Extensible_UI_API::setTargetTemp_celsius(1, Extensible_UI_API::getTargetTemp_celsius(1) + getIncrement()); break;
    case  4: Extensible_UI_API::setTargetTemp_celsius(2, Extensible_UI_API::getTargetTemp_celsius(2) - getIncrement()); break;
    case  5: Extensible_UI_API::setTargetTemp_celsius(2, Extensible_UI_API::getTargetTemp_celsius(2) + getIncrement()); break;
    case 10: Extensible_UI_API::setFan_percent(       0, Extensible_UI_API::getFan_percent(0)        - getIncrement()); break;
    case 11: Extensible_UI_API::setFan_percent(       0, Extensible_UI_API::getFan_percent(0)        + getIncrement()); break;
    default:
      return false;
  }
  onRefresh();
  return true;
}
```
With namespaces, this was reduced to the following:

```cpp
bool TemperatureScreen::onTouchHeld(uint8_t tag) {
  using namespace Extensible_UI_API;

  switch(tag) {
    case 20: setTargetTemp_celsius(0, getTargetTemp_celsius(0) - getIncrement()); break;
    case 21: setTargetTemp_celsius(0, getTargetTemp_celsius(0) + getIncrement()); break;
    case  2: setTargetTemp_celsius(1, getTargetTemp_celsius(1) - getIncrement()); break;
    case  3: setTargetTemp_celsius(1, getTargetTemp_celsius(1) + getIncrement()); break;
    case  4: setTargetTemp_celsius(2, getTargetTemp_celsius(2) - getIncrement()); break;
    case  5: setTargetTemp_celsius(2, getTargetTemp_celsius(2) + getIncrement()); break;
    case 10: setFan_percent(       0, getFan_percent(0)        - getIncrement()); break;
    case 11: setFan_percent(       0, getFan_percent(0)        + getIncrement()); break;
    default:
      return false;
  }
  onRefresh();
  return true;
}
```

So, there is a reason for my madness. You did say there were some syntactical benefits of using static classes over namespaces, so I'd like to hear what they are. I think the question is whether they outweigh the brevity of the "using" keyword in this particular case.

> Marlin has been standardizing around names_with_underscores over namesWithCamelHumps

Fair point. Just so you know where I am coming from, before I started to dig into Marlin I had been doing a lot of JavaScript programming, so I do sometimes fall back on JavaScript conventions.

I admit my code isn't very consistent between the use of underscores vs camel case. This is just a consequence of there being multiple conventions fighting for supremacy in my brain. I'll see if I can try to pull it together.

> Right now we really need to focus on getting 1.1.9 out asap so we can return to this and focus our attention on a fully comprehensive LCD code cleanup for 2.x.

I fully understand. This can wait. I don't need it to be merged right now. The only reason for me putting in these PRs is to get your feedback before I veer too far off course.

**Comment by marcio-ao** [comment]
> And then each of these headers should sub-class from a root base_ui class — preferably a static class.

On this note, I would be curious to know what you think of "ui_framework.h," "ui_framework.cpp" and the file that use it, "ui_screens.cpp". It uses static classes, but has all the advantages of non-static classes. The problem it solves is that in UI, it is useful to have a method whose behavior varies depending on the type of the object, i.e. virtual methods in C++ terminology. This comes into play with methods like "onRefresh", which vary depending on the type of UIScreen we are dealing with.

I initially used plain old C++ virtual functions but I found out that "avr-g++" would store the virtual function tables in SRAM, meaning that it was highly memory inefficient. What "ui_framework.h" does is provide a few macros that create such a table in PROGMEM. It then defines a class called "ScreenRef" which uses a single byte screen ID to dispatch to the appropriate static methods by using "pgm_read_word_near" to read pointers to the static methods from the table.

So, yes, my UI code is entirely based on static methods, but yet I implement functions that behave as if they were virtual. It requires just one byte of SRAM to keep track of what screen the UI is on and uses considerably less Flash than UltraLCD.

**Comment by thinkyhead** [comment]
> benefits of using static classes over namespaces, so I'd like to hear what they are

A syntactical benefit of `static` singletons (that I appreciate, anyway) is that you can just use a dot, as in `planner.apply_leveling`. I prefer this over class-name (or namespace), as in `Planner::apply_leveling`. Double-colon notation is useful when there's a distinction between the instance and the class, but when you know all data is `static` and there's only a single instance, dot notation everywhere is just cleaner. Namespace referencing is worst when you have embedded namespaces, as in `UI::Menu::do_something`. And, there are legitimate arguments to be made that `using` makes code less clear. If one is trying to use methods and data from more than one namespace within the same code, typically one root namespace is chosen, and then all other methods have to back up to the root namespace (`::do_something`) for methods that share a name, or for methods in other namespaces (`::std::map`). Dot notation is always clear and concise in what it references, without concern for where in the class hierarchy or namespace arena the singleton happens to be rooted.

**Comment by marcio-ao** [comment]
> A syntactical benefit of static singletons (that I appreciate, anyway) is that you can just use a dot, as in planner.apply_leveling.

Hummm, this is interesting. I guess this hadn't ever occurred to me that this was possible. When I use a class that has just static methods or static data, I always use the double-colon notation and I've never thought of creating a singleton variable of that type so that I could use the dot notation. It seems a bit odd to create a variable from a class that has no instance variable or methods -- it would seem like such a variable would have size zero, which seems a bit scary, like a divide by zero.

What does the compiler do if you create an array of zero sized classes and try to iterate over it? I'm kinda curious now...

> And, there are legitimate arguments to be made that using makes code less clear.

True. I think you may have uncovered the fact that I am technically using "using" in a highly unconventional way. I'll admit I was trying to emulate something I've often missed from Pascal: the "with" keyword. If C++ had it, it would look like this:

```
class Extensible_API_UI {
   static int foo();
   static void bar(int);
}

void main() {
   with Extensible_API_UI {
     bar(foo());  // This is a lot more legible than Extensible_API_UI::foo(Extensible_API_UI::bar());
   }
}
```

If you compare it to what I actually did, you'll see I used namespaces to achieve the same effect:

```
namespace Extensible_API_UI {
   void foo();
   void bar(int);
}

void main() {
   using namespace Extensible_API_UI;
   bar(foo());  // This is a lot more legible than Extensible_API_UI::foo(Extensible_API_UI::bar());
}
```

Because all methods were static, this just happened to work. I find it quite clever, but I won't hold it against you if you disagree! At the moment, I just can't think of any other alternative to make the API calls concise.

**Comment by marcio-ao** [comment]
Humm, I suppose if I used your instance-of-zero-length class trick, I could do this instead:

```cpp
class Extensible_API_UI {
   static void foo();
   static void bar(int);
}

void main() {
   Extensible_API_UI a;
   a.bar(a.foo());
}
```
Slightly less concise than the namespace trick, but still a lot better than the `::`. I'm torn about which one is better.

**Comment by marcio-ao** [comment]
> What does the compiler do if you create an array of zero sized classes and try to iterate over it? I'm kinda curious now...

Hummm, according to [this resource](http://en.cppreference.com/w/cpp/language/ebo), instances of classes with all static members and static variables are forced to consume a single byte of memory, precisely to address the "array of empty classes" scenario.

So it would seem like using static classes as singletons does carry the small penalty of a single byte of RAM.

**Comment by thinkyhead** [comment]
A single byte. That's funny. If a class is 100% static, of course every instance is the same. Linkage is static, so there is no hidden `this` passed as the first argument. They are just as efficient as global functions. I picked up the single instance dot notation tip from "Thinking in C++," a free book on C++ that's been around for a while.

**Comment by marcio-ao** [comment]
> They are just as efficient as global functions.

Well, except for the single byte the compiler allocates to give it a unique address.

**Comment by p3p** [comment]
I think I may be the only person that actually likes double colon notation, namespaces, and rarely uses `using` (only in very restricted scope as above), I just like the conciseness I guess. Not fond of initialising static classes as it just feels off, but it's all just personal preference.

> Namespace referencing is worst when you have embedded namespaces, as in UI::Menu::do_something

I like that, clear compartmentalisation, granted people go overboard with long chains in libraries, but I would be happy with HAL::GPIO::function, HAL::ADC::function, _etc., &c., et cetera_

**Comment by thinkyhead** [comment]
> Humm, I suppose if I used your instance-of-zero-length class trick, I could do this instead…

Well, as with other singletons you'd only declare one global instance `extern` in the header and then it is seen by all code that includes the header…

#### ui_api.h:
```cpp
class Extensible_API_UI {
   static int foo();
   static void bar(int);
};

extern Extensible_API_UI ui;
```
#### ui_api.cpp:
```cpp
Extensible_API_UI ui; // token instance
```
#### everywhere…
```cpp
#include "ui_api.h"

ui.bar(ui.foo());

float temp = ui.getActualTemp_celsius(extruder);
```
_…Et cetera, etc., &c._

---
> I may be the only person that actually likes double colon notation, namespaces, and rarely uses `using`…

I can appreciate that in some projects. But at the same time, it sure adds a lot of noise that your eye has to scan through to find the important piece of information: the **name** of the function or variable. (Syntax highlighters should dim namespaces and **bold** the final atom!) And it makes your code lines a lot longer. I like being able to pack a lot of action and meaning into a small space, maybe due to my affection for Perl….

…And if only we could write Marlin in C# and eliminate headers…

> Not fond of initialising static classes as it just feels off

Yes, it's really just a "trick of the trade" specific to static singletons.

**Comment by thinkyhead** [comment]
Squashed and rebased to keep this fresh…

I'd like to merge it, but I'm averse to adding another top-level item to the `src` folder. Perhaps it can be moved into the `lcd` folder? Even though a UI doesn't have to involve an LCD, that just happens to be where all the UI-related code currently lives.

**Comment by marcio-ao** [comment]
@thinkyhead: I can move the files to the "lcd" directory. Do you still want me to change the API methods to `lowercase_underscore`?

I also need to update the files in this branch, since I've been doing work on them and not updating.

**Comment by marcio-ao** [comment]
@thinkyhead: Okay, I moved all the files into "lcd/extensible_ui" and updated all the config files with the new directory. I also added a few other things to the API, like velocity, acceleration and jerk. I also added return statements and default cases to avoid compiler warnings.

**Comment by marcio-ao** [comment]
@thinkyhead: One of the things that is missing from the API is the ability to store LCD specific configuration settings in EEPROM. For this LCD, the following settings would be useful:

- LCD brightness (it looks like there may already be an EEPROM slot for this)
- Sound volume  (it looks like there isn't an EEPROM slot for this yet)
- Touch-screen calibration data (not sure if this will be needed, so far it looks like these values can be hard-coded based on the display type).

I haven't added this to the API, because it isn't clear how it would be done. One option is simply to add the sound volume to the EEPROM and provide a getter/setter for that. Not all printers have sound though, so I'm not sure you want this. The second option is to provide an API for reading/writing a block of data pertaining to the EXTENSIBLE_UI module itself, and leave it up to the module to decide what to put in that block.

Any thoughts?

**Comment by thinkyhead** [comment]
For LCDs that can have brightness, a getter and a setter perhaps. We have an EPROM slot for contrast but not brightness yet. I’ll see how it should be best implemented later tonight.

For features, constexpr bools that return whether the extension has the feature…

**Comment by marcio-ao** [comment]
@thinkyhead : Oh, another request we get often from our education market is a passcode to allow access to the menu so students don't muck with the printer. I could add that easily if I had some space to store a passcode hash.

So, yeah, there are a lot of cool features that an UI could implement if it had the storage to do so.

**Comment by thinkyhead** [comment]
When I squash and rebase, it's vital that you use…
```
git checkout pr-extensible-ui
git fetch origin
git reset --hard origin/pr-extensible-ui
```
…before making any further changes.

If you have un-pushed changes at the time that I announce a rebase/squash then you can do some additional git magic to preserve those changes, and I can help with that if you're unfamiliar.

In any case, using `git merge` or Github Desktop to attempt to patch up a rebased and squashed branch causes a mess, as you may have noticed.

The thing is, when conflicts arise, as we currently see by the image it requires some form of resolution. The tools provided here are sufficient, but the PR tends to accumulate a lot of extra merge commits, so I favor rebasing. Still, if you would prefer to work that way and have me stop doing squash and rebase on your branches, just say so and I will leave that work to you.

**Comment by thinkyhead** [comment]
> another request we get often from our education market is a passcode to allow access to the menu so students don't muck with the printer

I can see the value in such features. After the 1.1.9 release it would be good to work on all the refinements that improve user experience and so on.

**Comment by marcio-ao** [comment]
This PR has been resubmitted as #11193

**Pull request closed without merging**
