### PR TITLE
Add bq Hephestos 3D printer

### PR DESCRIPTION
**Pull request by victorandueza**
Hi all.

I have added bq Hephestos configuration files in order to integrate it in Marlin.

Thank you!

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks! As the number of "boards" corresponding to RAMPS 1.3 multiplies, these additions are going to start getting silly. I'm happy to add this, but we may do some housecleaning soon and remove all "boards.h" entries that aren't really different boards, and use `CUSTOM_MENDEL_NAME` in `Configuration.h` instead of filling the root folder with every obscure printer model out there.

**Comment by thinkyhead** [comment]
Hey @victorandueza I wonder if you can help @MPJ987 with #1437 ? The issue might be solved by the time you check it out. It looks like a simple one.

**Comment by thinkyhead** [comment]
I see you have LCD options enabled in the example configuration. Does Hephestos come with a particular LCD display standard?

**Comment by victorandueza** [comment]
Hi,
Sure, I am glad to help @MPJ987. 

The Hephestos printer comes with a RepRap Discount Smart Controller. The ULTRA_LCD definition can be commented, because is redundant. 

Thank you.

**Comment by MPJ987** [comment]
Can you be more specific about how I do it?

Thanks.

2015-01-30 11:32 GMT+01:00 victorandueza notifications@github.com:

**Comment by victorandueza** [comment]
Replied in #1437. Thanks!

**Comment by thinkyhead** [comment]
This PR needs an update before I can merge. Rebase on Development, resolve any conflicts, and we will be good to go!

**Comment by thinkyhead** [comment]
#1446 merged!

**Pull request closed without merging**
