### PR TITLE
Update to Danush language 10/11-2016

### PR DESCRIPTION
**Pull request by boelle**

### CODE REVIEW

**Comment by boelle** [comment]
Dooh.... wanted this to go in to RC bugfix... @thinkyhead can you save my skin here so i dont have to mess more with github than i have allready done

**Comment by boelle** [comment]
ahh figured it

hope i did it right this time

**Comment by petrzjunior** [comment]
@boelle There are still two commits, one of them thinkyhead's which you probably don't want to include. However I don't know how to fix it :)

**Comment by boelle** [comment]
me neither, i just hope that @thinkyhead can pick what is needed.

and in 2-3 weeks time i can check myself as my rebuild printer will have a full graph display

**Comment by boelle** [comment]
submitting new PR

**Pull request closed without merging**
