### PR TITLE
Fix extruder dryrun

### PR DESCRIPTION
**Pull request by MagoKimbra**

### CODE REVIEW

**Comment by MagoKimbra** [comment]
Who tells me how to update my fork to the latest version and then apply the changes ...
Excuse me but github not quite understand ...

**Comment by thinkyhead** [comment]
First obtain a diff with changes from your previous Development, then apply those changes to a clean new copy of Development. For example:

```
git diff Development Fix_Extruder_DRYRUN >/tmp/dryrun_diff.txt
git fetch upstream
git checkout Development
git merge upstream/Development
git checkout Development -b my_clean_dryrun
cat /tmp/dryrun_diff.txt | git apply
```

**Comment by MagoKimbra** [comment]
Thank's @thinkyhead !!

**Comment by boelle** [comment]
@MagoKimbra could this one be rebased?

**Comment by MagoKimbra** [comment]
Sorry but i must create any pull the #2354

**Comment by boelle** [comment]
np.... its checing #2354 right now

will close this one

**Comment by MagoKimbra** [comment]
Excuse me, I take advantage of this pull which is closed to make a request ...
If it is possible and there are no problems, can be mentioned among the collaborators in marlin, even in small ... I would be very grateful ... Sorry again ...

My name is Alberto Cotronei, Italy. I have 47 years old. I am technical Engineer. Thank's

**Pull request closed without merging**
