### PR TITLE
Add heating state bitmaps to _Statusscreen.h

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR reduces the complexity and storage requirements for the `_Statusscreen.h` files by providing separation of…
- the status screen logo bitmap,
- the status screen heater bitmap, and
- the status screen fan animation bitmaps.

Also:
- Standardizes the default hotend positioning and spacing.
- References temperature drawing x-pos to the center of the nozzle/bed bitmaps.
- Moves fan animations out of status screens, to `dogm_Statusscreen.h`.
- Preserves 8-pixel (byte) boundaries for optimal bitmap drawing.
- Minimizes bitmap heights for optimal storage and drawing.

Latest changes:
- More clearly indicate hotend / bed heating status with alternate bitmaps.

Upcoming:
- Add an indicator for bed leveling enabled.
- Give a graphical indication that the SD card is inserted.
- Add support for up to 6 nozzles, switching the view from 1-3 to 4-6.
- Experiment with alternate info screen designs and active job indicators.

### DEMO:
Attached here is the [test _Statusscreen.h](https://github.com/MarlinFirmware/Marlin/files/2595525/_Statusscreen.h.gz) (gzip) that I'm using. Currently supporting:
- One hotend and bed with a large logo, or two hotends and bed with a small logo.
- If no bed heater exists it doesn't appear.
- If no print-cooling fan exists then it doesn't appear.
- Hotend off and hotend heating images.
- Bed off and bed heating images.

img_e4185
img_e4186

### CODE REVIEW

**Comment by ejtagle** [comment]
@thinkyhead : I like your icons 👍  ... At some point, i was thinking that instead of storing all of them, you could just compose them on the fly, for example, painting the number over the hotend body, to save FLASH. That should not be a problem and a very small slowdown impact in overall drawing speed is not a problem.
But i am not sure if the FLASH savings are worth the effort ;)

**Comment by thinkyhead** [comment]
Flash savings are pretty minimal. The resulting size of each nozzle bitmap is only 24 bytes. The larger bed bitmaps are 36 bytes. So it costs 48 bytes per on/off pair of nozzles and 52 bytes for the default bed image, since the "off" frame is only 6 bytes.

I did some timing of the display updates, and the difference in speed is negligible. For some cases the update speed is faster, but for those cases where the bitmap drawing takes more time it's not very significant.

So now the question is, should a hollow nozzle or a solid nozzle indicate heating?

**Comment by landodragon141** [comment]
@thinkyhead I think solid should be heating. That way it's in contrast to the mostly hollow elements that compose the remainder of the display.

**Comment by ejtagle** [comment]
Also agree with @landodragon141 . Think about it as a light indicator in a panel. ON = LIGHTED = Solid

**Comment by fiveangle** [comment]
Is there enough pixels to make heating vs not universally obvious in some way like it is on the HB ?

I would always end up having to cognitively process the hot end temp value since I would never trust the ambiguity of the HE icon, as it's relatively rare that I need to know (like when something went wrong — extruder clicking as if either cold or hot and clogged). I'd imagine most others would do the same unless they are running a print shop ? :)

**Pull request merged**
