### PR TITLE
[2.0.x] Multiple updates to STM32F1 HAL

### PR DESCRIPTION
**Pull request by victorpv**
Multiple updates to STM32F1 HAL.
Speeds up timer code, reduces ADC rate to reduce memory access by DMA, adds boards to the corresponding files.
Marlin has been tested so far with all those boards. 
STM3R_Mini and BeaST are custom boards I am using for development.
Malyan M200 and Chitu3D are commercial boards in which we have run Marlin successfully.

Includes 1 change to configuration_store to add support for eeprom emulation in MCU flash, since the flash can't be erased byte by byte. We have to erase the whole page.
We use 2 pages, so 2000 updates before they wear out. This is only needed for boards without i2c eeprom. I have successfully tested i2c eeprom with the Chitu3d, Stm3r_Mini, and BeaST

### CODE REVIEW

**Comment by Wackerbarth** [comment]
> "We use 2 pages, so 2000 updates before they wear out."  -- I've wondered about using a different strategy for the configuration store. Rather than rewriting the entire configuration each time anything changes, we could store just the changes  in a journal.

Initially, and when the configuration space is full, we would erase everything and store any values which differ from their default value. Then when some value is changed, we would append the new value to the end of the journal. The process of fetching a  value from the configuration store would be a little slower, but that is done only on boot-up and when the user explicitly reloads from the configuration rom.

**Comment by victorpv** [comment]
@Wackerbarth feel free to contribute code to improve it. At the moment we are more focused on getting things working, than getting them optimal.
The stm32duino core includes a library to store 16bit values, that uses an index, where the index would be equivalent to the address, is not exactly like I understand journal, but kind of. The information in written down to top, but read top to down. The last entry for a particular index is the only valid one.
In that, each 32bit word is split in 16bit for index, and 16bits for data.
The problem with that one is that storing 8bit values is very inefficient, so someone over the stm32duino forum posted another version that uses 8bits for index and 8 for data, so each 32word can hold 2 byte values. But then the index is limited to 8 bits. I am using it for another project that needs to store a smaller amount if information, and 256 positions is good, and storing bytes is more efficient than 16bits, but Marlin uses more than 256 positions of eeprom.

Another possibility is to take 8bits for index and 8 for data, but subdivide the flash pages in blocks, or use more pages, so we can have a 9th bit or even a 10th bit for index, with those 2 extra bytes not being stored, but rather indicating the code in what block that data is supposed to be.

There are multiple possibilities, if want to try to implement a different one we can give it a shot.

I did one implementation where the config data is saved to the sdcard, similar to what the re-arm does, but the re-arm has an sdcard onboard, not the display one, but the Marlin maintainers didn't like the idea of storing the configuration in an sdcard in the LCD display, that people may take in and out to add new files etc.

**Comment by thinkyhead** [comment]
Overall, looks good. I think we can work with it. Will merge soon, and tally ho!

**Comment by victorpv** [comment]
Thanks. I am in the meanwhile testing the multi-host from TCM, so when that's ready to merge I will have the STM hal ready and tested for those changes.

**Comment by victorpv** [comment]
I noticed I am making some mess with the readme.md file, and now have 2. I will correct that in my next PR.

**Comment by thinkyhead** [comment]
If you want to rename something, giving it a different case, such as `readme.md` => `README.md` first rename it `_README.md` in one commit and then rename it `README.md` in a separate commit. This will keep git from getting confused when using case-insensitive systems.

**Comment by ellensp** [comment]
"STM3R_Mini and BeaST are custom boards I am using for development."
Where these ever realesed? 
If not perhaps we should remove them from marlin?

**Pull request merged**
