### PR TITLE
suppress warnings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by thinkyhead** [comment]
What if we define the function this way, with `const` on the second argument (instead of casting to `char *` on the function call)? Does that also get rid of the warning?

``` cpp
void lcd_implementation_drawedit(const char* pstr, const char* value)
```

**Comment by ghost** [comment]
I apologize for the late reply,

> void lcd_implementation_drawedit(const char\* pstr, const char\* value)

it's possible.
changes in codes are here.
https://github.com/esenapaj/Marlin/commit/dfe124ab220f31ccda5bb1e7b00d8e20a29fac04

**Comment by thinkyhead** [comment]
With #3176 it encouraged the use of `const` in more places where it should be used anyway. It's a magic word, that `const`, though it has many mysterious meanings.

**Comment by ghost** [comment]
This page is I think it's helpful.
docs.oracle.com/cd/E19059-01/wrkshp50/805-4956/bajbebbg/index.html
http://docs.oracle.com/cd/E19059-01/wrkshp50/805-4956/bajbebbg/index.html

**Pull request merged**
