### PR TITLE
Add ISO10646 Turkish Font and Turkish Translation

### PR DESCRIPTION
**Pull request by ghost**
Adds Turkish language support to Marlin for 12864 graphic lcd.

Corrected copyright :) and added font source.

### CODE REVIEW

**Comment by thinkyhead** [comment]
As this is a brand new language (thank you!), it also needs to be added to the language heading in all the `Configuration.h` files (i.e., the default one, and all those in the `example_configurations` folder). Here are the altered lines:

``` cpp
//
// LCD LANGUAGE
//
// Here you may choose the language used by Marlin on the LCD menus, the following
// list of languages are available:
//    en, an, bg, ca, cn, cz, de, el, el-gr, es, eu, fi, fr, gl, hr, it, kana,
//    kana_utf8, nl, pl, pt, pt_utf8, pt-br, pt-br_utf8, ru, tr, test
//
// :{'en':'English','an':'Aragonese','bg':'Bulgarian','ca':'Catalan','cn':'Chinese','cz':'Czech','de':'German','el':'Greek','el-gr':'Greek (Greece)','es':'Spanish','eu':'Basque-Euskera','fi':'Finnish','fr':'French','gl':'Galician','hr':'Croatian','it':'Italian','kana':'Japanese','kana_utf8':'Japanese (UTF8)','nl':'Dutch','pl':'Polish','pt':'Portuguese','pt-br':'Portuguese (Brazilian)','pt-br_utf8':'Portuguese (Brazilian UTF8)','pt_utf8':'Portuguese (UTF8)','ru':'Russian','tr':'Turkish','test':'TEST'}
//
```

**Comment by thinkyhead** [comment]
Oops! The `language_tr.h` file seems to be missing too.

**Comment by boelle** [comment]
@Rigid3D you know you need to update this?

**Comment by ghost** [comment]
OK. I have forgotten the translation file when adding the files to RC-Bugfix branch. I have added it.

Updated configurations.

I know the policy about example configurations. But I have to say once again that updating all these files is a burden for the developers and in my opinion it should be discontinued or limited to some Reprap models.

**Comment by thinkyhead** [comment]
> a burden for the developers and in my opinion it should be discontinued

It's takes only a few seconds with global search-and-replace.
And there's no need to do a separate commit for each file.

If some developers prefer not to do it, I'll happily do it myself.
As it is, I need to squash these 25 commits into one anyway.

**Comment by thinkyhead** [comment]
Squashed to a single commit at #5167

**Pull request closed without merging**
