### PR TITLE
Polish font

### PR DESCRIPTION
**Pull request by android444**
Add polish font for GLCD displays only.
HD44780 work properly without polish character.
Update language_pl.h.

sam_9595
sam_9596
sam_9597
sam_9598

### CODE REVIEW

**Comment by thinkyhead** [comment]
@AnHardt @yhfudev
How does this PR sit with our deployment of the UTF-8 update?

**Comment by android444** [comment]
It is in UTF-8.
I do not understand what you're asking.

**Comment by Blue-Marlin** [comment]
@android444 
You have not looked up what this meaned.
> Your suggestion for the Polish font was much better, clean and complete. But likely it is not needed when we get #5441 (thinkyhead#20) to work.

**Comment by AnHardt** [comment]
@thinkyhead 
This PR could be merged immediately.
The 'fallback defines' in `language_pl.h` are just ugly, but don't minder the functionality.

In the process to make #5441, or something similar, ready to merge, most of the code, including the font, has to be removed again. But since there has to be removed much more, then dead code, #5441 will not suffer very much. The more work, is mainly checking the newly used symbols in `ISO10646-0-3.bdf` for the correct size.

@Blue-Marlin 
It's not #5541 but #5441.

**Comment by android444** [comment]
Where can I find the file ISO10646-0-3.bdf?
Where in this file put the Polish symbols?

**The 'fallback defines' in language_pl.h are just ugly, but don't minder the functionality.**
What to change?

**Comment by yhfudev** [comment]
@android444 
You may want to checkout the branch from here: https://github.com/thinkyhead/Marlin/pull/20
It's the latest updates of the UTF-8 branch.
Can you please update the glyph in the ISO10646-0-3.bdf if possible?

**Comment by android444** [comment]
I can update.
I can not find the file ISO10646-0-3.bdf.

**Comment by android444** [comment]
Where to do it?

**Comment by yhfudev** [comment]
The PR is not merged to master, so you have to checkout the branch from:
```bash
git clone https://github.com/yhfudev/Marlin.git
cd Marlin
git checkout -b rc_utf8_diff rc_utf8_diff
```
Find the file `ISO10646-0-3.bdf` in the directory `buildroot/share/fonts/`, and you may also read the file `uxggenpages.md` for more info.

**Comment by android444** [comment]
I use Windows, not Linux :(
Fony program does not open the file ISO10646-0-3.bdf.

**Comment by Blue-Marlin** [comment]
Try 'FontForge'. 
I know - a much to complex program where we will use about 1% of its abilities. But just shifting some pixels in a few symbols is learnable in a few minutes.

**Comment by Blue-Marlin** [comment]
Design rules for this font:
* No pixels below 'baseline' -1.
* Upper case 'A's highest point is 'baseline' +7.
* Lower case 'a's top is at 'baseline' +5.
* If in cases like 'g' a second row below the 'baseline' would be needed the lower part of the symbol is compressed. If this is unreadable, the complete symbol may be shifted one pixel up.
* Symbols like 'Ä' may not exceed 'baseline' +8.
* Max width for a symbol is 5 pixel. If not that wide like 'i' - centre.
* We prefer 'A' with a 'flat' top.

* If there is no way to squeeze a symbol in this 5x9 box you can extend to 11x11. This needs extra handling for this language then - like reducing menu-lines from 5 to 4 (f.e. Chinese).

**Comment by android444** [comment]
> Try 'FontForge'.

This is not a BDF file.

**Comment by Blue-Marlin** [comment]
No problens here with: https://github.com/fontforge/fontforge/releases/download/20161005/FontForge-2016-10-04-Windows.exe
Did you open the font with a text editor and saved it again? Maybe this messed up the line-ends (\\n <-> \\r\\n)

**Comment by android444** [comment]
Changed. Still can not open the file.

**Comment by Blue-Marlin** [comment]
Can you open 'ISO10646-0-2.bdf'?
Do you run FontForge as admin?

**Comment by android444** [comment]
FontForge run as admin.
ISO10646-0-2.bdf can not be opened :(

**Comment by yhfudev** [comment]
What's the error message?

If it opened, look like this:
fontforge-linux

**Comment by android444** [comment]
zrzut ekranu-1
To nie plik bdf
Is not bdf file

**Comment by yhfudev** [comment]
You need to check:

1. if the BDF file contains the data, it's basically a text file, you can open it with a text editor and make sure it correct

2. check if the software was compiled to support BDF file by open other BDF files, such as this:
http://wenq.org/daily/wqy-bitmapfont-bdf-gb18030-nightly_build.tar.gz

**Comment by android444** [comment]
ISO10646-0-3.bdf can be saved as ISO10646-0-3.fon?

**Comment by Blue-Marlin** [comment]
No. It contains far more than 255 symbols.

**Comment by android444** [comment]
Ubuntu installs.

**Comment by android444** [comment]
Dosn't work in Ubuntu :(
zrzut ekranu-1

**Comment by yhfudev** [comment]
@android444 
.fon is binary format, while BDF is text file. It won't work if you change the file suffix.

Can you open the BDF file with a text editor?
How about the other BDF files? for example:

- wenquanyi_9pt.bdf in http://wenq.org/daily/wqy-bitmapfont-bdf-gb18030-nightly_build.tar.gz
- or unifont-9.0.06.bdf from http://unifoundry.com/pub/unifont-9.0.06/font-builds/unifont-9.0.06.bdf.gz

**Comment by android444** [comment]
zrzut ekranu-1
zrzut ekranu-2
zrzut ekranu-3
zrzut ekranu-4
zrzut ekranu-5
zrzut ekranu-6
zrzut ekranu-7

**Comment by android444** [comment]
**yhfudev** opened in Ubuntu? The program FontForge?

**Comment by yhfudev** [comment]
@android444 Yes, I opened it by fontforge in Ubuntu. Unfortunately, the Fony.exe can only import the first 256 glyph from BDF file when I tested in Wine. Can you import the **ISO10646-0-3.bdf** by **Fony**? or can you open the file **wenquanyi_9pt.bdf** by **FontForge**?

**Comment by android444** [comment]
zrzut ekranu-1
What's next?

**Comment by android444** [comment]
zrzut ekranu-1
What's next?

File wenquanyi_9pt.bdf opened under Windows FontForge.
ISO10646-0-3.bdf is broken.

**Comment by yhfudev** [comment]
Great! So fontforge works in Ubuntu, you may try to open ISO10646-0-3.bdf with FF. If won't work, you may try ISO10646-0-2.bdf and ISO10646-0-1.bdf, since *-3.bdf is base on *-2.bdf, which is base *-1.bdf. This may help to find which file caused the problem.

**Comment by android444** [comment]
I still can not open the file.
zrzut ekranu-1
zrzut ekranu-4
zrzut ekranu-3

**Comment by android444** [comment]
What would you do accept Polish fonts?

**Comment by android444** [comment]
I opened iso10646-0-3.bdf on the Windows Fontforge.
GITHUB is buged!
zrzut ekranu-1
What now?

**Comment by thinkyhead** [comment]
Looks like the original branch or fork is now gone, so this PR can't be updated. @android444 would you be able to re-create this starting with the latest `RCBugFix`?

**Comment by android444** [comment]
Ok.
_@android444 would you be able to re-create this starting with the latest RCBugFix?_
Yes.

**Pull request closed without merging**
