### PR TITLE
Add AVR sanity check to prevent MONITOR_DRIVER_STATUS with SoftwareSerial

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

Add a Sanity Check to prevent the use of MONITOR_DRIVER_STATUS when using TMC drivers using SoftwareSerial.

This applies only to AVR, where the SoftwareSerial implementation disables interrupts for long periods of time, causing a noticeable disruption to stepper performance.

This does not impact TMC drivers connected using SPI or hardware serial.

### Benefits

A lot of issues regarding rough printer behavior have resulted in the recommendation to disable MONITOR_DRIVER_STATUS on AVR platforms. This change should help reduce the number of reported issues caused by this undesirable combination of features.

Prior to the following change monitoring was silently skipped for drivers using Software Serial. Even if people thought they were monitoring their drivers prior to May, they were not. That also explains why people say it wasn't an issue with 1.1.9.
https://github.com/MarlinFirmware/Marlin/pull/14074

### Related Issues

Issue opened soon after monitoring over SoftwareSerial was added in May.
This can probably be closed after this goes in, with "Don't use this combination of hardware/features" being the accepted solution.
https://github.com/MarlinFirmware/Marlin/issues/14183

MONITOR_DRIVER_STATUS is mentioned as one of the issues in the following, although it isn't the cause of all issues.
https://github.com/MarlinFirmware/Marlin/issues/16155

This is already closed, but disabling MONITOR_DRIVER_STATUS seemed to be the main solution.
https://github.com/MarlinFirmware/Marlin/issues/14683

### CODE REVIEW

**Comment by sjasonsmith** [comment]
Tagging @teemuatlut since this impacts features they've worked on.

**Comment by sjasonsmith** [comment]
@thinkyhead, I thought I had found some examples of sanity checks where the option could be explicitly defined to `true` to disable the sanity check. I was going to do the same for this, but could no longer find where I had previously seen that.

Clearly somebody could simply comment out the sanity check if they want, but do you have a recommended mechanism to allow overriding a boolean sanity check?

**Comment by thinkyhead** [comment]
> Clearly somebody could simply comment out the sanity check if they want, but do you have a recommended mechanism to allow overriding a boolean sanity check?

If there's an existing option that makes the sanity check unnecessary, we just add that option to the sanity check. We don't typically add new options just for the sake of skipping a sanity check.

**Comment by teemuatlut** [comment]
This is fine. I can't think of a quick fix for AVR as any SW reads will disrupt the stepper ISR.
Perhaps with later library update Marlin can override some calls and find a fix that way.

**Pull request merged**
