### PR TITLE
dry run by default not possible

### PR DESCRIPTION
**Pull request by trivalik**
try to reduce code size, I am just not sure if I can omit the "code_seen" call.

### CODE REVIEW

**Comment by thinkyhead** [comment]
1. Formatting fails to respect established standards
2. Refers to an option (`SUPPORT_DRYRUN`) that doesn't exist
3. "Dry run" is not a source of bloat

**Comment by trivalik** [comment]
In my case it saves 202 bytes. So it is not less for a function which is not really needed. I added a config entry, but my description is improvable to have the same english style as others.

**Comment by thinkyhead** [comment]
202 bytes of PROGMEM, I presume.

There are probably dozens of ways to make various parts of the code optional. Some are worth the effort, while others will only add more bloat to configurations. We have to be selective.

**Comment by trivalik** [comment]
The arduino IDE Shows that the sketch use 202 Bytes less.

**Pull request closed without merging**
