### PR TITLE
Reverse encoder for FYSETC Mini 12864 2.1 + SKR 1.3

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

BTT_SKR 1.3 Controller
FYSETC_MINI_12864 2.1 

### Description

With this combination of display and controller, the encoder is backwards. 

### Benefits

Encoder works as expected.

### Related Issues
No related issues.

### CODE REVIEW

**Comment by Evg33** [comment]
#define REVERSE_ENCODER_DIRECTION must be in Configuration.h.

Pins's files for hardware and pins. But REVERSE_ENCODER_DIRECTION  not pins.
May be here we need change pins BTN_EN1 and BTN_EN2 ?

**Comment by thinkyhead** [comment]
> May be here we need change pins BTN_EN1 and BTN_EN2 ?

Should never be needed. `REVERSE_ENCODER_DIRECTION` does exactly that.

**Comment by PKav89** [comment]
This commit seems to be wrong. I have a BigTreeTech SKR 1.3 and FYSETC MINI12864 v2.1 (NEOPIXEL RGB version), and I just compiled latest bugfix-2.0 and then spent 15 minutes trying to find out why my encoder became reversed and "REVERSE_ENCODER_DIRECTION" in "Configuration.h" does not change this behavior. Please consider rollback.

**Comment by ellensp** [comment]
@PKav89 I also have a  BigTreeTech SKR 1.3 and FYSETC MINI12864 v2.1 (NEOPIXEL RGB version) and had to Invert the encoder.  Thus the pull request.
Just to be on the same page, rotating encoder right should move down the menu items and rotating left should move Up the menu items.
Can you take hires images on your LCD, front and back, want to compare it to mine. perhaps they have two (or more) revisions ...
I had to remove the 2*5 cable sockets shells from my LCD so I could flip the cables 180. Did you do this or did you make a custom cable?  Or did you not need to do this (indicating a new version)

**Comment by PKav89** [comment]
Yes, same behavior. Left to go up in menu and decrease value, Right for down and increase. 
And yes, SKR 1.3 and, also, Smoothieboards require to rotate LCD ribbon cable connector by 180 degrees for all LCDs.
It does not seem to be a new version, but it might be just a different encoder from a different supplier with swapped pinout.

Anyway, someone might like inverted encoder rotation, and this commit makes impossible enabling/disabling inversion via Configuration.h, because it's now hardcoded in some other file somewhere deep in the Marlin directory tree. That's why i think it should be rolled back.

**Pull request merged**
