### PR TITLE
[1.1.x] Continuous Purge

### PR DESCRIPTION
**Pull request by seanboothm**
### Description

Rather than purging a set length after a filament load, prompting the user, purging again, and repeating, this feature will continuously feed filament until the user presses the button on the ultraLCD to stop purging and resume the print.

### Benefits

Rather than repetitively purging a set length, this allows the user to keep purging and stop when filament is clean.

### Related Issues

New feature - Continuous Purge

Counterpart to #10173
[Concise Diff](10176/files?w=1)

### CODE REVIEW

**Comment by thinkyhead** [comment]
Error:
```
sketch/ultralcd.cpp: In function 'void (* ap_message_screen(AdvancedPauseMessage))()':
ultralcd.cpp:4649: error: 'ADVANCED_PAUSE_MESSAGE_CONTINUOUS_PURGE' was not declared in this scope
         case ADVANCED_PAUSE_MESSAGE_CONTINUOUS_PURGE: return lcd_advanced_pause_continuous_purge_menu;   
              ^
```

**Comment by thinkyhead** [comment]
Error. This is not defined either. Will it be "extrude" or "purge"? ("Purge" is preferred.)
```
ADVANCED_PAUSE_MESSAGE_CONTINUOUS_EXTRUDE
```

**Comment by thinkyhead** [comment]
Rebased, squashed, fixed various issues, added Travis CI test…

**Comment by thinkyhead** [comment]
One good addition to this would be to have the purge stop at the configured purge length. It just means that users will want to set that value higher. Then this feature becomes, not just "continuous purge" but adds the much-needed ability to interrupt the purge in-progress.

**Comment by Roxy-3D** [comment]
Agreed...

**Comment by thinkyhead** [comment]
Ok, this is now adjusted to purge only up to the (integer part of the) configured purge length, then stop. That will prevent purging endlessly while the operator is out to lunch.

**Pull request merged**
