### PR TITLE
Fix bad runout computation

### LINKED ISSUE #26061: [BUG] Incorrect filament runout motion sensor mm_countdown.runout counting which can produce false filament runout event or delay true runout event
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When using filament runout movement sensor, on printing of small parts, there is a change of false positive filament runout event. While motion sensor is not triggered as filament actually did no move even 1mm in total. As retract movement was not calculated correct, which made Marlin "think" that filament was moved enough already with no sensor reaction.

### Bug Timeline

I installed runout sensor on 2.1.2.1 version, did not check earlier.

### Expected behavior

No matter how many retraction/deretraction events are triggered only on actual forward movement should be triggered filament runout event.

### Actual behavior

Runout event is triggered, while  filament actually is not moved enough mm while printing.

### Steps to Reproduce

1. Download file Straight_Track_100mm.stl
https://www.thingiverse.com/thing:4408535/files
2. Compile Marlin Firmware with filament runout sensor support, filament change support and runout distance 3mm
3. Use SuperSlicer with retraction on wipe, with retract 0.6mm, set "Retract amount before wipe 20%", "Minimal travel after retraction" to 0.1mm, set 0.08 or 0.04 layer height
4. Slice and print model(I suggest skipping to 3.12mm or 4.64  Z height in gcode directly, also you can insert filament in feeder just it have a grip, so no actual filament used in printing, as only move is important)
5. When it start to print bolts on rail, there will be a lot of retraction it will trigger filament change event.

### Version of Marlin Firmware

2.1.2.1

### Printer model

Ender 3

### Electronics

Ender 2 Pro stock board (4.2.3)

### Add-ons

Optical motion sensor (remix of 5710572 thing from thingeverse), BMG clone feeder, short-bowden direct, sensor is connected freely between spool and reverse bouden tube.

### Bed Leveling

No Bed Leveling

### Your Slicer

Other (explain below)

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

My optical motion sensor react accuracy is near 1mm, I set FILAMENT_RUNOUT_DISTANCE_MM=3mm in settting.
Here is the issue. On some models with high number of small details and high retraction value, Marlin calculate some of the retractions and ignore some of them, and this can lead to runout, while 3mm actually was not moved. And as my sensor mostly 1mm accurate, you can assume that not only 3mm is not moved, but even 1mm was not really moved.
I checked runout.h file, to understand what really happens. Tried FILAMENT_RUNOUT_SENSOR_DEBUG const, but output not really informative. Only that mm_countdown.runout starting to decrease very fast while a lot of retractions.
So I checked source. The RunoutResponseDelayed.block_completed function  ignores extruder movements when there is no x,y or z movement. But modern slicers like SuperSlicer can use wipe option, which means, that some of the retraction/deretraction is occured while moving and some without moving.
So I edited source, so I can see which E moves are ignored and which are not.

I will include my config (it is actually a default Ender 2 Pro config files, with minimal changes (like enabling runout sensor). I include config for bugfix release which I tested last.

I include runout.h file, which I changed to get my logs.
I include custom logs, which only include my custom info about which E moves were ignored and which were counted.
I also include gcode files I used to trigger the issue. I insert a tip of filament into BMG gears, and it takes 100mm to come to the nozzle from there, so it is enough to check gcode and not use any filament. So my gcode only use 30 degrees temperature.
retract_test_ps_464_fw.gcode - is prusa slicer 2.6 version, from 4.64 height. It uses FW retraction(I thought that it will help, but no it actually isn't). Corresponding log for it is report_bugfix_fwretract.txt. We see that only retract is counting and deretract is ignored, so on retraction events mm_countdown.runout start to grow, which is wrong, and while it will not trigger false positive, it will trigger false negative. You can just took out filament, and system will ignore that runout motion sensor is not triggered, as mm_countdown.runout is larger and larger. If there are a lot of retractions system will not stop at all, while printing them.

The rest two are SuperSlicer 2.4 gcode files. Those two with slicer retract and wiping. Also I tried firmware retract with no luck.
retract_test_ss_312_wipe_r06.gcode and report_bugfix_runout.txt this is only the end of log file, not from the begining, as Pronterface cut the rest. We see that runout distance become smaller and smaller, because some of retract/deretract movement is ignored, and finally a runout event triggered when mm_countdown.runout become negative.

retract_test_ss_464_wipe_r06.gcode and report_bugfix_overflow.txt in this situation is on the contrary, mm_countdown.runout  starts growing, which is not correct too. Those are part of the same model, just different height.

Actually I tried disable the "if" part in RunoutResponseDelayed.block_completed function:
if (b->steps.x || b->steps.y || b->steps.z || did_pause_print) {
and it really solved the issue. After that all E movement starts to count and no false runout events triggered. Also it is seen in logs, that mm_countdown.runout show correct numbers. So actual runout state when filament is stuck or ended was triggered correctly.

I guess also this workaround should probably include RunoutResponseDelayed.filament_present function modification there should be added the "if" with such condition:
if (mm_countdown.runout[extruder] < runout_distance_mm) {

So mm_countdown.runout will not reset if it is already larger (due to adding retraction movement).

I guess this is needed to prevent resetting on random sensor reaction, for bouden systems with large retraction and short runout distance. Actually runout motion sensor should not trigger on backward movement, but it may because of shaking or for other reason.

I am not sure though if it is appropriate to use this code modification. For some reason there is check for xyz movement.

[config+logs+gcode.zip](https://github.com/MarlinFirmware/Marlin/files/11985245/config%2Blogs%2Bgcode.zip)

### PR DESCRIPTION
**Pull request by GMagician**
A better solution than #26067 ?

### CODE REVIEW

**Comment by justvlade** [comment]
@GMagician This is a clever idea! And this works alright with firmware retraction. And it does not runout with Super Slicer wiping, at least. But as expected retraction with movement is taken into account. And runout mm is growing until reset on move.

I will include zip with logs:
log_M6_LOG_P3.txt - retract_test_ps_464_fw.gcode
log_M6_SS_312_LOG_P3.txt - retract_test_ss_312_wipe_r06.gcode
log_M6_SS_464_LOG_P3.txt - retract_test_ss_464_wipe_r06.gcode

By the way is there any particular reason, why not just write something like: `if (b->steps.e) {` instead of `if (b->steps.x || b->steps.y || b->steps.z || did_pause_print) {` ?

[patch_4efc227_logs.zip](https://github.com/MarlinFirmware/Marlin/files/12062192/patch_4efc227_logs.zip)

**Comment by GMagician** [comment]
Well fix was mainly intended to let G10/G11 and other retraction/unretraction works correctly and keep them out of runout logic.
What I can't understand (may fault with translation) is what you mean here below than forgive me if my answers are nosense.
1) 'But as expected retraction with movement is taken into account' I think that any x/y/z movment with E is intended as "normal" filament deposition. Don't know why a back E move is considered in logic. But if unretraction is done with other axis movements..what for unretraction? I think I should check deeply into your gcode (can you repost here involved gcode?)
2) 'By the way is there any particular reason, why not just write something like' here not sure I understand. This code is done to check when e is moving with other axes. Any movement that involve only E is considered as retraction/unretraction and not considered in runout

**Comment by justvlade** [comment]
Yes I understand that this topic is debatable. I understand that it is a classic solution to consider that retraction is only made while printhead is in still state. And actually I do not really know any other slicer which use retraction wiping except for Super Slicer. Maybe it is the future, or this maybe just some experiment which will not be proven that useful. Maybe other slicer will implement wiping or even there will be hardware wipe. Or it may not get popularity. I actually do not insist that this should be taken into account. I guess it should be a known issue at least.

I will provide an example of gcode, to show what I mean.

```
G92 E0
G1 E-0.12 F1500
;WIPE_START
G1 X17.998 Y112.81 E-0.42938
G1 X17.998 Y112.656 E-0.576
;WIPE_END
G1 E-0.6
; stop printing object Straight_Track_100mm.stl id:0 copy 0
M486 S-1
G1 Z3.12 F12000
; custom gcode: layer_gcode
;AFTER_LAYER_CHANGE
;3.12
; custom gcode end: layer_gcode

G92 E0
; printing object Straight_Track_100mm.stl id:0 copy 0
M486 S0
; acceleration to travel
G1 X17.972 Y112.656
G1 X30.094 Y116.688
; decel to extrusion
G1 X48.967 Y122.966
G1 X48.967 Y122.836
; end travel
G1 E0.6 F1200
```

As you see it makes `G92 E0` then initial small retraction, then some negative E move while moving in X,Y dimention, this makes wipe move.
After wipe it makes `G1 E-0.6`, to be sure retraction position is exactly where it should be, as wipe move consists of rounded values. Then it resets E0 again with `G92 E0`.
Then it moves to a place where deretraction/unretraction is going to be. And finally executed positive E move `G1 E0.6 F1200`.

**Comment by GMagician** [comment]
I think that this code may not be handled in any way by Marlin. It can't knows that this movement is a wipe.
Not sure if we may skip any back E move, I think some "more skilled" guy should step in.
For sure this PR fix a corner case issue and may be merged even if it doesn't fully solve your case.

**Comment by justvlade** [comment]
It is not a high priority and have a workaround. So I guess we should not overcomplicate this. Lets leave this wipe part as is. I myself tried firmware retractions before posting the issue, and liked it.
I will configure latest bugfix with this patch and my regular config and test it with some real printing.

**Comment by justvlade** [comment]
Sorry, do not want to annoy you. But to be clear, what I meant.

`This code is done to check when e is moving with other axes. Any movement that involve only E is considered as retraction/unretraction and not considered in runout`. Why exclude retraction/unretraction movement from runout calculation? Retraction is added to runout distance, and unretraction subtracted, this way they compensate each other. From mathematics point of view there is no difference, except if you try ignore retraction, you need to detect that event(which is possible only with fwretract). And if you just let numbers add and substract you do not need to calculate that.

There is also a function to display how much filament was used. And this function change filament mm numbers depend on retraction/unretraction as well. Sometimes number become smaller, then larger in real time on the screen. All in all it is the same.

That is why I asked is there any particular reason, why retraction/unretraction needed to be excluded from runout calculation.

**Comment by justvlade** [comment]
I created a draft to illustrate my idea.

**Comment by GMagician** [comment]
> This code is done to check when e is moving with other axes. Any movement that involve only E is considered as retraction/unretraction and not considered in runout.

I just reported what code does. What I suspect is that the choice which has been taken was to prevent runout during filament change. I suppose that at some point no more filament is "detected" but E is still moving.

**Comment by justvlade** [comment]
> I just reported what code does. What I suspect is that the choice which has been taken was to prevent runout during filament change. I suppose that at some point no more filament is "detected" but E is still moving.

I thought about runout event when not printing. But original condition also contains `did_pause_print` variable, which means that it is OK to run filament runout calculation while printer is paused. I actually do not know when `did_pause_print` variable actually activated.

I guess I will check my idea, if there will be some reaction on service commands. I guess there should be already some variable which indicates, are gcode commands actually part of printing file, or printer is in some pause or service state. So we can check this var instead, while counting e movement.

**Comment by GMagician** [comment]
did_pause_print seems set by M125/M600 (gcode) and in general by `pause_print` method (there are 2 methods with such name).
Your idea may be good but I'm not in the position to say yes or no because I don't know each of many different cases. I just have my "little" point of view based on my printer case use.

**Comment by justvlade** [comment]
@GMagician I have tested my idea and it works. I had to change code a little, as I found that it is not that easy as I thought it was. But all in all it works with software and firmware retraction. I used `printingIsActive` function to ignore movement while not in printing state. I also left `did_pause_print` condition part. Added check for `steps.e` not zero, as there is no point to trigger if there is no motion. Also this may be not needed.

And had to add additional variables to create a delayed reset event. As it is mandatory to not reset `runout` if it is larger than `runout_distance_mm` it is also mandatory to reset `runout` when filament present event is triggered. But we can't. So I created delayed reset flag. When `block_completed` function is called and it subtracts `mm`, after unretract it will become smaller than `runout_distance_mm` and reset can be applied. So if flag is raised it will try to reset until it succeeds.
I will try my idea also with real printing. Already tested with retract_test_ps_464_fw.gcode and retract_test_ss_464_wipe_r06.gcode and it works ok. I simulated filament runout event, and change filament work alright.

I attach full logs here. I also added message when runout reset is happening.
[patch_ec2f12d_logs.zip](https://github.com/MarlinFirmware/Marlin/files/12100857/patch_ec2f12d_logs.zip)

**Comment by thinkyhead** [comment]
Added the suggestion from @justvlade to the mix for testing.

@justvlade — For future reference, a more direct way to get changes into this PR would have been to submit a PR to @GMagician targeting his `runout-fix-2` branch. A PR targeting one of your own branches is not needed since you can just create and commit to your own branches directly.

**Pull request merged**
