### PR TITLE
Add Menu on LCD for Autoleveling TouchMI

### PR DESCRIPTION
**Pull request by Fourmi**
### Requirements

For tuning Autoleveling TouchMI
### Description

Tuning the sensor is really difficult for a beginner, so i decided to facilitate the task by offering a single-page adjustment of the LCD.
3 steps to perform:
1 - Init TouchMI ( Home all axis, deactivate endstop )
2 - Z-offset ( Tune the Z-offset & save with M851 on eeprom)
3 - Save TouchMI ( Re-activate endstop & M500)
Test TouchMi > To check the tuning at Z0

https://gyazo.com/2179001d15bfc6874a18272980165033

### Benefits

Tuning your TouchMI in 30 sec. on single page with 3 steps

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
First, PR's should target the bugfix branch, not release branches.

Second, 1.1.x is considered EOL and only critical bugfixes will be added. All new development should be targeted there.

Third, For steps like this I typically utilize the custom user menu and name it commissioning. This is not really specific to the device used, its a generic z offset process. Endstops don't need to be disabled here, proper configuration of the probe offset limits will encompass that. Sanity checks shouldn't be added to the config files, they should go in SanityCheck.h or Conditionals_XXX.h depending. PR's should update all example configs when those are modified for future reference.

**Comment by Fourmi** [comment]
Ok i'm sorry ,i'm noob on GitHub ;)
it's just for help people & easy tune Z offset 
Sorry Dude ..

**Comment by InsanityAutomation** [comment]
Not really bothering anyone, not a big deal and common to see early on when people want to contribute. But if we dont tell you now and you keep doing it then it might get to be!

**Comment by robbycandra** [comment]
This PR is not merged but i found that this is interesting.

In my printer I use 2 sequence. 
1. Offset and Corner
- Nozzle goes to first corner - user adjust first bed Level Nut to make Nozzle touch the bed..
- Printer automatically calculate the z offset of the probe.
- Probe goes to other 3 corner and user adjust the bed using probe guided by number in LCD.
2. ABL
- Now user already have calibrated z-offset and good corner level, user do ABL and save it to the eeprom. In my case. the ABL will always on (like UBL) except user manually turn it off.

I still find a way to probe distance between Nozzle and bed. Maybe I will use Tool zero Probe like CNC.

**Comment by Fourmi** [comment]
Thx @robbycandra 
I just wanted to simplify the Z Offset procedure for the user as much as possible.
Even if I coded badly, it works and it's very fast to do this operation.
I am not a coder but a mechanic;)

**Comment by Fourmi** [comment]
@InsanityAutomation 
About my mistake of deactivate/activate endstop...
I think you talk about this line in configuration.h right ?
```
// For M851 give a range for adjusting the Z probe offset
#define Z_PROBE_OFFSET_RANGE_MIN -20
#define Z_PROBE_OFFSET_RANGE_MAX 20
```

**Comment by robbycandra** [comment]
@Fourmi , I think it is not because your code is bad. But maybe Marlin focus on simplicity but perfect planner. Things like this... maybe its developers things.

**Comment by InsanityAutomation** [comment]
@Fourmi yup that and #define Z_PROBE_LOW_POINT

And Marlin is a big pile of tribal knowledge on how and where to do things. Takes awhile to get used to it all. No more no less. No issue with the code per se, just need to gain the tribal knowledge over time.

Also Scott is working on some guided stuff that is more encompassing in this area, but the focus now is more on bug fixes, sanity checks and limits, and making 2.0 stable in all configurations.

**Pull request closed without merging**
