### PR TITLE
Add heating progress bars

### PR DESCRIPTION
**Pull request by thinkyhead**
Show small progress bars next to hotends and bed when heating, or if hotend animation is used, have the hotend images themselves act like progress bars.

img_e4246

### CODE REVIEW

**Comment by yucelll** [comment]
Oh looks very good!
I think if nozzle is printing;
giphy

and if bed heating, so should be wave icon on bed

**Comment by thinkyhead** [comment]
> and if bed heating, so should be wave icon on bed

Yes, there is. The image in the post was simulated.

> I think if nozzle is printing;

I'll put it on the TODO list for later.

**Comment by Glod76** [comment]
Any way to keep the hotend and hotbed animation solid and on when it's at the set temperature? the hotend blinks on and off when printing and the hotbed animation as well.

**Comment by Glod76** [comment]
these are my setting. also could not compile with, #define STATUS_FAN_FRAMES 4 only 3 works
Awesome job so far though, loving the new stuff added. :)
```cpp
//#define STATUS_COMBINE_HEATERS    // Use combined heater images instead of separate ones
  //#define STATUS_HOTEND_NUMBERLESS  // Use plain hotend icons instead of numbered ones (with 2+ hotends)
  #define STATUS_HOTEND_INVERTED      // Show solid nozzle bitmaps when heating (Requires STATUS_HOTEND_ANIM)
  #define STATUS_HOTEND_ANIM          // Use a second bitmap to indicate hotend heating
  #define STATUS_BED_ANIM             // Use a second bitmap to indicate bed heating
  #define STATUS_ALT_BED_BITMAP       // Use the alternative bed bitmap
  #define STATUS_FAN_FRAMES 3         // :[0,1,2,3,4] Number of fan animation frames
  #define STATUS_HEAT_PERCENT         // Show heating in a progress bar
```

**Comment by thinkyhead** [comment]
> the hotend blinks on and off when printing and the hotbed animation as well.

That is the indicator that the heater is turning off and on. Previously it was a small 2x2 dot. The temperature is always fluctuating, so there's no point where it exactly matches the set temperature — it just hovers near the set temperature.

**Pull request merged**
