### PR TITLE
BigTreeTech SKR Mini E3

### PR DESCRIPTION
**Pull request by Msq001**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

1) MCU: STM32F103RCT6.
2) Supports 2.8 inch, 3.5 inch color touch screen and original Ender3 printer
LCD12864 screen(CR10_STOCKDISPLAY).
3) 4 X TMC2209 (UART mode) onboard.
4) Supports BL touch, RGB LED

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Why can’t the LCD pins be implemented similarly to how it was done on the Fysetc Cheetah (another 32-bit Ender-3/5 board)? See https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/pins_FYSETC_CHEETAH.h#L96

**Comment by Msq001** [comment]
hi~   you mean use "HAS_SPI_LCD" and "HAS_GRAPHICAL_LCD" not "ENABLED(ULTRA_LCD)" and "ENABLED(CR10_STOCKDISPLAY)" ?  this is just copy from the old version, I'll update it now. thank you

**Comment by thisiskeithb** [comment]
Does this board need build scripts like the SKR Mini 1.1?

**Comment by Msq001** [comment]
the script of this board is same as skr mini 1.1

**Comment by thisiskeithb** [comment]
Good to know!

**Comment by 3DSmitty** [comment]
Should the pins on SKR Mini V1.1 be cleaned up as well?

**Pull request merged**
