### PR TITLE
Add probing margins to output of M503

### PR DESCRIPTION
**Pull request by davidboese**
### Description

Sending the M503 command will now include probing margins in received output.

[Configurations.h](https://i.imgur.com/5lGgnl9.jpg)

[Configurations_adv.h](https://i.imgur.com/WrbBYVD.jpg)

[M503 Output](https://i.imgur.com/pf2uMCb.jpg)

### Requirements

A bed probe, related functionality defined in your marlin build, and a defined probing margin.

### Benefits

Allows users to review probing margin values (used when determining reachable probing points during probed bed leveling) along with other useful information output by the M503 command.

### Configurations

Any config with bed probe functionality and PROBING_MARGIN defined should work.

### Related Issues

None.

### CODE REVIEW

**Comment by davidboese** [comment]
Upon reviewing the output of M503, I notice that all other value sets are lead by an M*** command which can be used to set those values without modifying the source and recompiling (correct me if that's incorrect). Is this part of the program standards, that all outputs of M503 must be modifiable without recompilation, making my PR unacceptable? At least not without other additions to allow modification of the probing margins.

**Comment by ManuelMcLure** [comment]
`M503` defined as presenting the values stored in SRAM so it doesn't make a lot of sense to show an unchangeable value in `M503` output.

**Comment by davidboese** [comment]
Honestly not entirely sure what that means (and I don't think it should be your job to explain every detail to a layman). I assume EEPROM is non-volatile and SRAM is volatile. In other works things storing in SRAM are values needed/changed regularly and dynamically during 3d printing operations. Is there some other way information about probing margins in surfaced to the user without looking at the precompiled source? Some other command or menu it would be more appropriately output by?

What determines whether something is stored in SRAM or not? Is there some easy why to find that information? Obviously memory is always limited to some extent, so usage should be kept as low as is necessary. Z-probe offset is output by M503; why is z-probe offset stored in SRAM while probing margins are not?

**Comment by ManuelMcLure** [comment]
Anything that can be modified at runtime goes in SRAM. Most (all?) of the values in SRAM can also be saved in EEPROM. When Marlin boots, the values in EEPROM are used to initialize the SRAM values. When you change a value with gcode it updates the SRAM value, and the values in SRAM are only copied to EEPROM when you explicitly store them with an `M500` or by selecting the option on the LCD.
Most of the machine dimensions (`[XYZ]_[MIN|MAX]_POS`, `[XY]_BED_SIZE` and such) are considered static - it is very uncommon for these to change once the printer is set up and thus are not stored in SRAM. Until around a year ago, the X and Y probe offsets were not stored in SRAM either, only the Z offset was. The reason the Z offset was always stored in SRAM is because it could easily change when a nozzle was replaced and there needed to be an easy way to adjust it on the fly, while X and Y probe offsets are pretty much fixed once you decide on a mount for the probe.
In general, settings tend to be initially defined as static, and only moved into SRAM/EEPROM if it is found that they need to be changed often. `PROBING_MARGIN` (and it's children `PROBING_MARGIN_LEFT`, etc.) are somewhat of a gray area. I could see a use case if a user sometimes uses clips on the bed and sometimes not, but I don't know how often this occurs and whether it's worth the SRAM space it would take up.

**Comment by davidboese** [comment]
Thank you for taking the time to explain that for me. I do agree that there are use cases where it would be a useful feature to have. Perhaps it is something that could be added as an option. If the user's printer has the resources to support it and they have use for it, they can turn it on, as is the case with many features of marlin. However that requires someone with the will, ability, and time to add that feature. I can give it a try, but I have only limited programming experience so far.

Can values stored only on the EEPROM be displayed on screen (or output via some command)? Or does the operation of displaying the value on screen (or being output via some command) require moving it into SRAM, thereby negating the advantage of storing that value only on the EEPROM in the first place? Looking at the "printer info" section, I assume the information listed there is not stored in SRAM. I don't see a command that outputs information similar to that available in the printer info LCD menu.

**Pull request closed without merging**
