### PR TITLE
UBL Menu System 1.1

### PR DESCRIPTION
**Pull request by Tannoo**
/**
     * UBL System submenu
     * 
     *  Prepare
     * - Unified Bed Leveling
     *   - Activate UBL
     *   - Deactivate UBL
     *   - Mesh Storage
     *       Memory Slot:
     *       Load Bed Mesh
     *       Save Bed Mesh
     *   - Output Map
     *       Map Type:
     *       Output Bed Mesh Host / Output Bed Mesh CSV
     *   - UBL Tools
     *     - Build Mesh
     *         Build PLA Mesh
     *         Build ABS Mesh
     *       - Build Custom Mesh
     *           Hotend Temp:
     *           Bed Temp:
     *           Build Custom Mesh
     *         Info Screen
     *       - Build Cold Mesh
     *       - Fill-in Mesh
     *           Fill-in Mesh
     *           Smart Fill-in
     *           Manual Fill-in
     *           Info Screen
     *         Continue Bed Mesh
     *         Invalidate All
     *         Invalidate Closest
     *     - Validate Mesh
     *         PLA Mesh Validation
     *         ABS Mesh Validation
     *       - Custom Mesh Validation
     *           Hotend Temp:
     *           Bed Temp:
     *           Validate Mesh
     *         Info Screen
     *     - Edit Mesh
     *         Fine Tune All
     *         Fine Tune Closest
     *       - Adjust Mesh Height
     *           Height Amount:
     *           Adjust Mesh Height
     *         Info Screen
     *     - Mesh Leveling
     *         3-Point Mesh Leveling
     *       - Grid Mesh Leveling
     *           Side points:
     *           Level Mesh
     *         Info Screen
     *   - Output UBL Info
     */

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Where's ubl_G29.cpp?

----

I drop all the commits that aren't something I did for the PR.  I don't know why the "extras" sometimes show up.  I do know that including them will result in unwanted files being attached to the PR.

This is the sequence I use to rebase.  It's something Scott provided.  I'm pretty much "monkey see - monkey do" when it comes to git.

```
git remote -v
git remote add upstream https://github.com/MarlinFirmware/MarlinDocumentation.git
  only do this if the first command doesn't show this setting
git fetch upstream
git rebase upstream/RCBugFix
   git add Marlin/ultralcd.cpp
   git rebase --continue
   git rebase --abort
git rebase -i RCBugFix
  pops up a window where you can select commits to be squashed into one
git push -f
```

**Comment by Bob-the-Kuhn** [comment]
There are three lines that need to be changed from _const float_ back to _float_ in order to clear up the Travis issues.

I'd also like the  _do_blocking_move_to_z(current_position[Z_AXIS] + Z_CLEARANCE_BETWEEN_PROBES);_ restored.

_extern void lcd_quick_feedback();_  isn't needed.

**Comment by Tannoo** [comment]
Okay... I'm working on that. I was unsure what was supposed to be or not.

**Comment by Tannoo** [comment]
This:
`Merge remote-tracking branch 'origin/UBL_Menu_System_1.1' into UBL_Me…`

wasn't supposed to happen. Now, that has messed me up on doing any squashing.
Because now, trying to squash, gives me all KINDS of conflicts.

**Comment by Tannoo** [comment]
```
Marlin/ultralcd.cpp: needs merge
You must edit all merge conflicts and then
mark them as resolved using git add
~\Documents\GitHub\Tanno\Marlin\Marlin [UBL_Menu_System_1.1|REBASE-i +0 ~0 -0 !1 | +0 ~0 -0 !1 !]>
```
I'm stuck here.

Well, I think I got past it, but the squash didn't happen.

I'm going to stop making it a bigger mess. I could fix it with a new PR. lol

**Comment by Tannoo** [comment]
@Roxy-3D, do you think this file would be ok for a start on that lcd pixel mesh you talked about?
[_UBL_lcd_maps.txt](https://github.com/MarlinFirmware/Marlin/files/982583/_UBL_lcd_maps.txt)

**Comment by Bob-the-Kuhn** [comment]
I've done a sanity check and all is well.

Is it OK to merge this PR?

**Comment by Tannoo** [comment]
May I move the "grid leveling" to it's own screen?
Also a few other Text changes.

**Comment by Tannoo** [comment]
Okay. That's it. I'm done playing with it.

**Comment by Roxy-3D** [comment]
> do you think this file would be ok for a start on that lcd pixel mesh you talked about?

I understand what you are trying to do!   How about we leave the Postage Stamp idea out of this for now?   The reason is many levels of #ifdef's adds a lot of complexity.   One thing I noticed is this:  We need to be able to set and clear bits on the 'Radar Screen' anyway.    The pre-initialized bits you have set for the boarder are at the very outside.   We could just clear the 'Radar Screen' and do a quick loop around the outside independent of the mesh size.   

And...  That was the other thing I noticed...  What about a non-symmetrical mesh?  What happens if somebody defines an 7 x 11 mesh?   If we clear the 'Radar Screen' and put an appropriate boarder around it with a few loops..  We can handle what ever funny dimensions the user picks.

**Comment by Tannoo** [comment]
Oh, yeah... I'm not adding the postage stamp thingy now. It's waaaay too complicated. It can be added later.

**Comment by Tannoo** [comment]
>Is it OK to merge this PR?

Probably not. It's got to get stale or superseded first.

**Comment by bgort** [comment]
> Probably not. It's got to get stale or superseded first.

Haha.  FWIW, it looks great to me.

**Comment by Tannoo** [comment]
Maybe it will move up the chain if I introduce a bug or two first. ;p

**Comment by bgort** [comment]
Hahaha... probably wouldn't hurt ;)

**Comment by Bob-the-Kuhn** [comment]
I finally had a chance to play with the menus.

Please add the "O" option to the P2 command (line 1855) in ultralcd.cpp.  

If you give me write privileges to your repository I'll rebase & squash this PR.

**Comment by Tannoo** [comment]
Alright. I am at work now, I'll see what I can do.

**Comment by Tannoo** [comment]
Invitation sent.

**Comment by Roxy-3D** [comment]
> Probably not. It's got to get stale or superseded first.

No...   For me...  If everything is wrapped with #ifdef's so the code doesn't do anything unless the option is turned on...   It is easy for me to feel comfortable to merge it.    I just need to know it is safe and won't break the code base.

And pretty much...   That is the state this is in...   

Tannoo...  You've done a really good job on this.   I'm going to keep using PronterFace on my laptop to talk to Marlin.  But a large number of people want to do everything from the LCD screen.   This lets them do that.   And anybody that has done code for Marlin knows...  The LCD Panel code is cryptic stuff.   It is very very difficult to make do things.

**Comment by Tannoo** [comment]
This whole UBL menu is only active with UBL selected. It replaces the "Level Bed" (in the Prepare menu), from other leveling options, with "Unified Bed Leveling".

**Comment by Roxy-3D** [comment]
Yes...  That is my point.   If there is some flaw we haven't found yet...  It is isolated to people that have enabled UBL.   Everybody else will be safe.   Those kind of changes...  Even big changes like this one...  are easy to feel comfortable merging.   But Bob is the one that has been spending big amounts of time on this.  He should have the honors of merging it!

**Comment by Tannoo** [comment]
Yup.

**Comment by Tannoo** [comment]
I would have thought that you too, @Roxy-3d, would have at least played with it. To see if it has what you want for your UBL users.

**Comment by Roxy-3D** [comment]
Yes...   I really should...    But I've been so busy fighting other issues...   I have looked at the code and I know it is pretty close to 'right'.   And Bob is involved so you already have two cook's in the kitchen.   

Don't worry...   Once it is merged I'll be making small changes here and there to it.   But right now I've got some weird bug in the ubl_motion.cpp file that doesn't make any sense.   And I need to get that figured out.

**Comment by Bob-the-Kuhn** [comment]
@Tannoo - I've rebased & squashed the commits.

Please verify that nothing strange has happened.

The only change should be moving the BLTouch menu.  That's something that came over from bugfix.1.1

**Comment by Roxy-3D** [comment]
This is exciting!   Maybe by the end of the day???

**Comment by Tannoo** [comment]
All is still in tact, thanks, @Bob-the-Kuhn!

**Comment by Bob-the-Kuhn** [comment]
Thank you.

You can remove me from your contributors list.

**Comment by bgort** [comment]
Woohoo!  This looks great!  Thanks for doing it....

**Pull request merged**
