### PR TITLE
Change "Fr" symbol in LCD to ">>"

### PR DESCRIPTION
**Pull request by positron96**
A pull request for https://github.com/MarlinFirmware/Marlin/issues/18788

This is a replacement for Fr symbol on LCD UI that I drew to resemble a "fast-forward" icon on consumer electronics. I believe it represents what changing feedrate percentage does - speeds all things up or slows them all down. That might be more informative for new users who are yet to learn what feedrate is.

### Benefits

The new symbol:
* is language-agnostic
* is less likely to be confused with flow rate 
* looks (arguably) more pleasant

Untitled

I've modified a BDF source file (only 1 symbol with ASCII code 6) with Fony and regenerated a font header file with bdf2u8g. Some parameters of the font in comment changed, though visually ther is no difference to other characters. I am not quite sure if only one header file needs to be modified, neither do I know whether headers are replaced by buildroot process that regenerates headers from bdf files, so I included both bdf file and header.

### Requirements

The font array became 1 byte larger, so 1 more byte of ROM is required.

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/18788 - initial proposal (my own)

### CODE REVIEW

**Comment by charakaSamawry** [comment]
Classic ffwrd rwnd symbol the 2 arrows/triangles should be equal size, i think it might look more recognisable with the extra pixel/block/square top and bottom of the left triangle.. and one missing in the middle behind it maybe

**Comment by thinkyhead** [comment]
Let's see how this looks…
```
BBX 8 7 0 0
BITMAP
D8 ; ##.##...
6C ; .##.##..
36 ; ..##.##.
1B ; ...##.##
36 ; ..##.##.
6C ; .##.##..
D8 ; ##.##...
```
Alternatively…
```
BBX 8 7 0 0
BITMAP
88 ; #...#...
CC ; ##..##..
EE ; ###.###.
FF ; ########
EE ; ###.###.
CC ; ##..##..
88 ; #...#...
```
Or perhaps best…
```
BBX 8 5 0 1
BITMAP
88 ; #...#...
CC ; ##..##..
EE ; ###.###.
CC ; ##..##..
88 ; #...#...
```

**Comment by positron96** [comment]
Here are some more variants (1x preview can be seen in top left toolbutton)

**Comment by Speaka** [comment]
I like the hollow one (first) best. It looks like an arrow indicating (faster) movement rather than fast forwarding a tape deck. You can derive this double v shape from the V in the physical equation for the volumetric flow rate. This seems appropriate nerdy to me.  Also the others remind me of a tilted nozzle icon.

**Comment by positron96** [comment]
I actually don't know how to move forward with this PR. All of the variants fulfill the stated goals of PR and differ only in visual style, and, to my liking, all are better than current symbol. The topic of visual appearance seems highly subjective, so it is natural that someone likes one variant, someone doesn't and likes another variant. So, may I suggest that members who have the authority to merge this PR, choose one variant and I'll update the files correspondingly.

**Comment by thisiskeithb** [comment]
We’ll have to wait for Thinkyhead to decide/merge.

**Comment by ellensp** [comment]
Put them all in code including original, in standard #if def blocks so only one is used at run time.. Then let user select one

**Comment by sjasonsmith** [comment]
I think I prefer the middle one of the three images.

**Comment by thinkyhead** [comment]
> …standard #if def blocks so only one is used at run time.. Then let user select one…

Unfortunately we cannot do this with BDF files, and we have to re-generate the font data from the BDF files if any character changes. So, I think it will be good to have a look at them on a real graphical display (or a simulator 😉) to see which one looks best (and whether I got the baselines correct). And then, pick the one with the best balance of font-style-match and clarity to utilize. A character option like this already exists for the character display.

I have some specific bug reports to investigate, and then there will be more time for 128x64 layout experiments.

**Comment by ellensp** [comment]
Why does the data it have to be in the BDF files?  they just get converted to .h files. so just bypass that step. Create a non auto generated Fontdata_custom.h full of #if def's...

**Comment by positron96** [comment]
> Why does the data it have to be in the BDF files? they just get converted to .h files. so just bypass that step. Create a non auto generated Fontdata_custom.h full of #if def's...

That's akin to having binary files inside repository without the sources. Those .h files aren't human-readable and human-editable, so if one would want to tweak fonts, he won't be able to do it using only .h files. BDF files are, on the other hand, sources that can be edited by humans.

**Comment by thinkyhead** [comment]
> Here are some more variants…

The first icon style is similar to that used by Prusa and for `LCD_INFO_SCREEN_STYLE 1`. I believe there might already be a similar Unicode character included in the BDF, but don't quote me on that.

I tend to prefer the first one because if we make the icon too much like "Fast Forward" then everyone will expect it to show "Pause" ⏸️  and "Stop" ⏹️  too, and the icons will never end….

**Comment by sjasonsmith** [comment]
@thinkyhead is there any reason to keep this open? It seems like either we should go ahead and merge something, or just close it if it isn't wanted.

I personally think it is a good idea to replace the English-centric "FR" with a symbol, and prefer this one:
image

**Comment by charakaSamawry** [comment]
Personally a fan of the first idea but with the rear arrow made equal size with
2 extra pixels

**Comment by tpruvot** [comment]
Indeed in french, was really confusing... look like a language flag FR

There was also this method i use : 
image

**Pull request merged**
