### PR TITLE
Fix mangled probe_pt calls

### PR DESCRIPTION
**Pull request by thinkyhead**
- Address issue #1669
- Remove the TOPO_ORIGIN configuration setting

### CODE REVIEW

**Comment by NarimaanV** [comment]
Wait why was the TOPO_Origin option removed out of the blue?

**Comment by thinkyhead** [comment]
@NarimaanV Critical mass of bitching is why it was removed. I would be happy to restore it if that makes sense for your application. I know there are a lot of cube-shaped printers where bed leveling might make more sense to start from the parked or home position at the rear of the printer. But some of our more active voices are not sold yet on the utility of this option.

**Comment by NarimaanV** [comment]
Hehe ahh, well I mean even though I think everyone who wants to use the feature shouldn't have to move their origin, I don't see the real harm in moving it either. Kind of wish we could have done something more in the middle that somehow made both sides of the argument happy, but oh well. If there isn't already, we should definitely put a warning/note in the configuration that notifies the user to make sure their origin is front left if they want to use the feature.

**Comment by thinkyhead** [comment]
@NarimaanV Well, presumably, the code is supposed to always start at left-front for this operation, and it was for the sake of putting the topography report in this order that it's being promoted to stay in that order. But in practical terms I realize it doesn't matter so much where the probing begins and ends, as long as it's done somewhat optimally. Which is why I like the zigzag option.

**Pull request merged**
