### PR TITLE
[2.0.x] Fix switching extruder

### PR DESCRIPTION
**Pull request by GMagician**
DONT_SWITCH was used but not defined
now DO_SWITCH_EXTRUDER is moved to .h and properly initialized

@thinkyhead I don't understand correctly logic in ultralcd.c on tool change when 4 or 3 extruders are in the system..is it correct? it seems that when 4 extruder you can switch only between T0 and T1

EDIT:
```C++
      #if EXTRUDERS == 4
        switch (active_extruder) {
          case 0: MENU_ITEM(gcode, MSG_SELECT " " MSG_E2, PSTR("T1")); break;
          case 1: MENU_ITEM(gcode, MSG_SELECT " " MSG_E1, PSTR("T0")); break;
          case 2: MENU_ITEM(gcode, MSG_SELECT " " MSG_E4, PSTR("T3")); break;
          case 3: MENU_ITEM(gcode, MSG_SELECT " " MSG_E3, PSTR("T2")); break;
        }
      #elif EXTRUDERS == 3
        if (active_extruder < 2) {
          if (active_extruder)
            MENU_ITEM(gcode, MSG_SELECT " " MSG_E1, PSTR("T0"));
          else
            MENU_ITEM(gcode, MSG_SELECT " " MSG_E2, PSTR("T1"));
        }
```

### CODE REVIEW

**Comment by thinkyhead** [comment]
> it seems that when 4 extruder you can switch only between `T0` and `T1`.

…unless `T2` or `T3` have been previously applied elsewhere.

With `SWITCHING_EXTRUDER` you can have up to two switching extruders. One switches between `T0` and `T1`, while the other switches between `T2` and `T3`. The menu item shown above was made only to do the switch on the current extruder, but not to select the other switching extruder.

**Comment by thinkyhead** [comment]
Seems `bugfix-1.1.x` and `bugfix-2.0.x` did get out of sync regarding `DO_SWITCH_EXTRUDER`. The entire purpose of this flag in 1.1 as it currently stands is to make sure that if the same servo number is assigned to both the switching nozzle and the switching extruder that it only calls code to switch the servo one time — with preference given to the nozzle servo.

I've tweaked this PR with the addition of another commit that cleans up the changes and makes more clear what effects this PR has on the behavior. It might be going beyond the original intent a little, but that's ok, since it eliminates the redundant `move_extruder_servo` function when it will never be used. I'll port some of the changes here so 1.1.x gets the same benefits.

**Comment by GMagician** [comment]
@thinkyhead ok about all line.
I left `ENABLED(SWITCHING_EXTRUDER)` with `DO_SWITCH_EXTRUDER` to better clarify, when reading code, that latter is dependant on former. I was in doubt if do it like you have done and I prefered to keep both.

**Comment by thinkyhead** [comment]
Given the similarity in their names I'm not too worried we'll forget that `DO_SWITCH_EXTRUDER` has a relationship to `SWITCHING_EXTRUDER`, and I prefer not to repeat conditions already included in conditionals.

**Pull request merged**
