### PR TITLE
rebased my fork with RCBugFix release in order to push language_nl.h

### PR DESCRIPTION
**Pull request by paulusjacobus**
Closes previous pull request #3389 from a fork that was not uptodate. Re-trying a pull request based on a rebased fork RCBugFix.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Dank u veel!

**Comment by Blue-Marlin** [comment]
@thinkyhead 
I'm not so enthusiastic about most of the new translations. A lot of them used strings wider then 20 chars. Good luck with displaying them.

**Comment by thinkyhead** [comment]
@Blue-Marlin I agree. These will need to be improved. Let's ask someone who speaks Dutch.

@paulusjacobus We need strings that fit within 16 characters, ideally. This used to be stressed in the language files, but perhaps those comments are gone now?

**Comment by paulusjacobus** [comment]
Okay will check and change them to fit within 16 chars. Same for German and
Danish.  Saw they have aimilar issues. Will be easy for me to change. Will
do tonight.

**Comment by jbrazio** [comment]
@Blue-Marlin @thinkyhead which LCD do we support inside Marlin ?

**Comment by AnHardt** [comment]
@jbrazio 
All that configurable in `Configuration.h`

But i guess you wanted to ask for different display formats.
For the character based displays we want to support 16x2, 16x4, 20x2, 20x4. (ultralcd_implementation_hitachi_HD44780.h line 540++)
For the full graphic displays we only support 128x64 pixel. With the 'normal' fonts that results in 5x~21 chars. The cn-font is not strictly monospace, so the result will be around 4x~10 but highly dependent on the content.

Further restrictions for the strings come from displaying

```
DescriptionValue
0123456789012345
```

on the same line, side by side, in some menus.

**Comment by jbrazio** [comment]
Thanks @AnHardt that was exactly my question.
In the end of the day, even with dot matrix, we're bound to have lines no bigger than 21 chars at best.

**Comment by thinkyhead** [comment]
We used to have some long versions and short versions of strings, but it was more work to maintain them. And, the problem with maintaining long and short strings is that what ends up being long or short can differ a lot between languages. So we simply started limiting LCD messages to 16 characters or fewer. Users can of course customize these for their own machines if they find them too brief.

**Pull request merged**
