### PR TITLE
Enable defining a rotary encoder in addition to an ADC key

### PR DESCRIPTION
**Pull request by 7eggert**
### Enable defining a rotary encoder in addition to an ADC key

When using a rotary encoder, yo need two digital inputs for the rotary position plus one input for the button. By using a resistor network, you can add more buttons without using external shift registers - it's convenient to have "back" and "home" buttons, too.

Based on this idea, I created a custom display:
https://www.thingiverse.com/thing:3448545

### Changes

In ultralcd.cpp, the logic for reading the ADC pin was dependent on not having a digital button. Now both are read and acted upon.

Moved BUTTON_EXISTS to macros.h as it's needed for further tests

HAS_DIGITAL_BUTTONS and HAS_ENCODER_WHEEL were or-ed with a direct test for the digital pins. 

The changes are correct but might be improved as they may cover the old tests, but I'd like to hear confirmation before doing this, since I can only compile-test these:
- The old test on HAS_DIGITAL_BUTTONS (`!HAS_ADC_BUTTONS && ENABLED(NEWPANEL)`) can be removed completely since each applicable device should define the buttons
- HAS_ENCODER_WHEEL might be defined as `(HAS_SHIFT_ENCODER || (BUTTON_EXISTS(EN1) && BUTTON_EXISTS(EN2)) )` if I'm not mistaken

### PS

I noticed that the left and right keys of the ADC keypad are mapped to home and back keys. while digital buttons aren't. There seems to be a dedicated BACK button for non-ADC inputs but no home button.

The BACK button (on some encoders?), is handled by a flag while ADC is handled by directly calling the corresponding functions.

Is there a reason / documentation for this?

### CODE REVIEW

**Comment by thinkyhead** [comment]
> each applicable device should define the buttons

Note that Marlin's approach has been to define pins that *should* be used for a given function. And since 1.0.2 we've been moving away from the behavior where a feature is enabled because a pin is defined (unless the pin is intended to be defined in the configs). So while technically this will work —because we do conditionally define the button pins based on the LCD selection— it is not guaranteed to remain viable if we end up defining default or *suggested* button pins in the future.

**Comment by thinkyhead** [comment]
> `HAS_ENCODER_WHEEL` might be defined as (`HAS_SHIFT_ENCODER`…

A "shift encoder" is an encoder that uses a shift register. Click wheels use 2 digital pins that change according to a pattern based on the direction turned.

**Comment by 7eggert** [comment]
"it is not guaranteed to remain viable if we end up defining default or suggested button pins in the future."

I guess there needs to be a MAJOR rework on that code and it would turn the logic upside-down. For now I'd like to do minimal changes and thereby keep down the work for the next guy.

From what you tell, I'd do it this way: (Future work, not scope of these patches)

1. have a set of pre-defined LCD modules, e.g. `DISPLAY_ZONESTAR_LCD`
2. In some .h file: `#ifdef DISPLAY_ZONESTAR_LCD ↙ #define HAS_LCD_CHARACTER ↙ #define HAS_LCD_HD44780 ↙ #define HAS_ADC_KEYPAD` ...
2b. For my display I would define `HAS_CHARACTER_LCD, LCD_I2C_TYPE_PCF8575, HAS_ENCODER_WHEEL`, not define `HAS_ENCODER_BUTTON` but `ADC_KEYPAD`; I would not need to worry about commercial product names nor need to define DISPLAY_ZONESTAR_LCD
3. pins_ANET_10.h would read: `#ifdef HAS_ADC_KEYPAD ↙ if !defined(ADC_KEY_NUM) ↙ #define ADC_KEY_NUM 8` (not caring about ULTRA_LCD or ANET_FULL_GRAPHICS_LCD)
4. After including pins_ANET_10.h, the next include would do `#ifdef LCD_I2C_TYPE_PCF8575 ↙ #ifndef LCD_I2C_ADDRESS ↙ #define …`, so the individual board definitions would need to do as little as possible.

---

"A "shift encoder" is an encoder that uses a shift register. " That much is without doubt - but do all LCD where HAS_ENCODER_WHEEL should be true either have the encoder connected to two dedicated pins EN1 EN2 or to a shift register being enabled by HAS_SHIFT_ENCODER (in this case the test for newpanel and !adc can be replaced)

OR

is there a NEWPANEL having a third way of connecting an encoder that would not be covered? (I found none in the code I worked on)

OR

are all encoders directly connected to two dedicated pins, thus `(!HAS_ADC_BUTTONS && ENABLED(NEWPANEL))` is equal to `(BUTTON_EXISTS(EN1) && BUTTON_EXISTS(EN2))`? From the code I'd guess that there is at least one display with the encoder buttons on a shift register.

Anyway, that line will get reworked so there is no need to think about that.

**Comment by thinkyhead** [comment]
> From what you tell, I'd do it this way…

That pattern would work. The current method is a little more manageable and less opaque than splitting up into multiple files by display type, because it keeps all the dependencies and display relationships together so their family resemblances are easier to see. If the display conditionals from `Conditionals_LCD.h` are split up, it will have to be seen whether this makes LCD relationships more opaque.

One very clear and obvious thing that we should do, which we have not, is to define the 20 EXP1 / EXP2 header pins in the pins files, then use those as the pin assignments for the selected display. Once this is done for all the pins files, the LCD code that currently lives in all the pins files can likely be consolidated into a single file, leaving behind in the pins files only the board-display-combo customizations.

I will make an attempt at that problem Very Soon™.

**Pull request merged**
