### PR TITLE
Add Formbot Raptor config, fix other Formbot configs

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Add example configuration for Formbot Raptor machines.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
What does the Boot Screen look like?   Is that a picture of a dinosaur?

**Comment by silentninja1** [comment]
@Roxy-3D Its the tinymachines logo, a robot :)

**Comment by InsanityAutomation** [comment]
tm_lglogo

**Comment by Roxy-3D** [comment]
A Raptor dinosaur would have been cooler.   But we take what we can get!   :)

**Comment by InsanityAutomation** [comment]
@Roxy-3D I dont disagree, but Chris did work with me alot getting all this stuff together on both formbot machines, so ive gotta plug him somewhere!

**Comment by thinkyhead** [comment]
These appear to be contradictory statements:
```
 * Stealthchop with TMC2208 on E will disable Linear Advance!
 * Enable stealthchop to use Linear Advance with a TMC2208 on the extruder!
```

**Comment by InsanityAutomation** [comment]
They are! I meant spreadcyle. This is in relation to the current issue with these drivers shutting down with linear advance on stealthchop.

**Comment by thinkyhead** [comment]
Where did you mean "spreadcycle"? In the first statement or the second?

**Comment by InsanityAutomation** [comment]
Sorry for the delay, was driving. Second.

**Comment by thinkyhead** [comment]
Sorry, I already patched the comments, and then I lost your commits a414bfc and 90983ab in my haste to push my other changes. To recover the lost commits, you can try this:
```
git checkout FormbotRaptorExampleConfig -b backup_FormbotRaptorExampleConfig
git checkout FormbotRaptorExampleConfig
git fetch origin
git reset --hard origin/FormbotRaptorExampleConfig
git cherry-pick a414bfc
git cherry-pick 90983ab
```
If there are conflicts, then they can still be recovered in another manner, using `git diff`. But check the current code and see if it's good enough. Maybe the lost commits aren't needed.

To clean up after…
```
git branch -D backup_FormbotRaptorExampleConfig
```

**Comment by InsanityAutomation** [comment]
@thinkyhead I still had the files open here, so I copy / pasted into edits from the web gui :)

**Comment by thinkyhead** [comment]
Looks good. Will merge everything once this passes Travis CI.

**Pull request merged**
