### PR TITLE
[2.0.x] Master-only TwoWire (I2C) class for LPC1768

### PR DESCRIPTION
**Pull request by tcm0116**
I put this together a while back, so I figured I'd submit a PR.

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'll work on this a bit and merge it later today.

**Comment by thinkyhead** [comment]
@tcm0116 — Yikes, this is old. I've rebased it. Should it still be merged?

**Comment by tcm0116** [comment]
I think it provides a more generic/cleaner implementation than the current one, but I haven't tested it. I'll leave it up to you to decide.

**Comment by thinkyhead** [comment]
Does this take over i2c right away, or just provide the class for later use?

**Comment by thinkyhead** [comment]
@tcm0116 Word on the street is that this PR may be connected with #9477 causing digital pots to stop working with MKS SBASE. We should look into this further.

**Pull request merged**
