### PR TITLE
Fix MMU2 compile error with > 8 colors

### LINKED ISSUE #23773: [BUG] Extendable MMUs with more than 8 slots fail with a compile error from steppers.h
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I just upgraded Marlin to 2.0.9.3 and found that it no longer compiles with the MMU enabled and EXTRUDERS set to > 8, which should be supported.

```
Marlin/src/feature/../module/stepper.h:249:1: error: macro "LIST_15" requires 16 arguments, but only 8 given
         bool LIST_N(EXTRUDERS, E0:1, E1:1, E2:1, E3:1, E4:1, E5:1, E6:1, E7:1);
```

### Bug Timeline

Wasn't present in 2.0.9.1, is present in 2.0.9.3

### Expected behavior

I should be able to compile Marlin.

### Actual behavior

I can't compile Marlin.

### Steps to Reproduce

1. Set `#define MMU_MODEL EXTENDABLE_EMU_MMU2S` in `Configuration.h` (and enable dependencies `FILAMENT_RUNOUT_SENSOR`, `NOZZLE_PARK_FEATURE` and `EMERGENCY_PARSER`)
2. Set `#define EXTRUDERS 10` in `Configuration.h`
3. Try to compile, and observe the reported compile error.

### Version of Marlin Firmware

2.0.9.3

### Printer model

_No response_

### Electronics

_No response_

### Add-ons

_No response_

### Bed Leveling

_No response_

### Your Slicer

_No response_

### Host Software

_No response_

### Additional information & file uploads

It looks like the commit that caused this problem is 021ceeba0b0ccadd7246d5e2da56df7868349206. There might need to be a special case there handling setups with an extendable MMU, since they only have one extruder motor, even if EXTRUDERS is set to more than 1.

Also, this is the second time in a year that i noticed that a commit in Marlin broke compilation with extendable MMUs which indicates that it's easy to overlook, it might be worth considering adding a test to avoid this from happening in the future.

### PR DESCRIPTION
**Pull request by GMagician**
It should fix #23773 but a review is required

### CODE REVIEW

**Comment by thinkyhead** [comment]
Seems good to me, with just one change to also use `E_STEPPERS` for the test condition.

**Comment by thinkyhead** [comment]
For thoroughness we need to look at how the `M17` / `M18` commands apply to extruders that use multiple steppers, and to extruders that share steppers. We've already attempted to account for axes that share multiple steppers, so for example on a CoreXY you have to disable X and Y together, and if either one is enabled they are both kept enabled. We've done some accounting for unusual extruders but it can't hurt to do another audit and standardize this handling.

For example, in `manage_inactivity` there is special `EXTRUDER_RUNOUT_PREVENT` handling for `HAS_SWITCHING_EXTRUDER` and that code seems like it could be moved to the `Stepper` class. Most of the time the `stepper.ENABLE_EXTRUDER` method deals with a whole extruder, but it doesn't deal properly with the switching extruder case on its own. Then the `MIXING_EXTRUDER` has multiple E steppers, but there is only one actual extruder, E0. So that also needs to be looked at more closely.

**Comment by GMagician** [comment]
M17 and M18 disable logic is a little '#define nesting logic' nightmare. Looking into it I found this:
```cpp
constexpr ena_mask_t enable_overlap[] = {
  #define _OVERLAP(N) ena_overlap(INDEX_OF_AXIS(AxisEnum(N))),
  REPEAT(NUM_AXES, _OVERLAP)
  #if HAS_EXTRUDERS
    #define _E_OVERLAP(N) ena_overlap(INDEX_OF_AXIS(E_AXIS, N)),
    REPEAT(E_STEPPERS, _E_OVERLAP)
  #endif
};
```

I suspect that `HAS_EXTRUDERS` needs to be replaced with `E_STEPPERS` as it has been done in [c475ee5](https://github.com/MarlinFirmware/Marlin/pull/25772/commits/c475ee56ac4a61609249841a7dea8a4123570b04).

**Comment by GMagician** [comment]
I'm wondering if
```cpp
      switch (active_extruder) {
          default: oldstatus = stepper.AXIS_IS_ENABLED(E_AXIS, 0); stepper.ENABLE_EXTRUDER(0); break;
          #if E_STEPPERS > 1
            case 2: case 3: oldstatus = stepper.AXIS_IS_ENABLED(E_AXIS, 1); stepper.ENABLE_EXTRUDER(1); break;
            #if E_STEPPERS > 2
              case 4: case 5: oldstatus = stepper.AXIS_IS_ENABLED(E_AXIS, 2); stepper.ENABLE_EXTRUDER(2); break;
              #if E_STEPPERS > 3
                case 6: case 7: oldstatus = stepper.AXIS_IS_ENABLED(E_AXIS, 3); stepper.ENABLE_EXTRUDER(3); break;
              #endif // E_STEPPERS > 3
            #endif // E_STEPPERS > 2
          #endif // E_STEPPERS > 1
        }
```
couldn't be simplified to:
```cpp
        const int8_t e = _MIN(active_extruder, E_STEPPERS) >> 1;
        bool oldstatus = stepper.AXIS_IS_ENABLED(E_AXIS, e);
        stepper.ENABLE_EXTRUDER(e);
```
before moving into stepper class

N.B. also `#else` branch could be changed...

**Comment by thinkyhead** [comment]
> I'm wondering if…

Yeah, that would work. The `switch` approach is probably due to `ENABLE_EXTRUDER` having been a macro previously.

**Comment by thinkyhead** [comment]
> `M17` and `M18` disable logic is a little '#define nesting logic' nightmare. Looking into it I found this…

It's necessary to figure out which axes share enable pins, so that's done at compile-time using `constexpr` data and functions, so the `ena_pins` array ends up taking no space, and admittedly this `constexpr` stuff is never pretty. Each `constexpr` function has to consist of a `return` statement and little else. (See `verify_no_timer_conflicts` for an interesting "exception.")

That much currently works. The next piece of the puzzle is to handle steppers that are shared on CoreXY, etc., and perhaps do special handling for Delta. When there is a use case for disabling a single ABC stepper on Delta then we could differentiate between ABC parameters and Z.

**Pull request merged**
