### PR TITLE
UTF-8 language header files

### PR DESCRIPTION
**Pull request by yhfudev**
This is a language string patch for the PR #5441, by defining a macro _UxGT() to relieve the burden for maintaining the UTF-8 patches, which I suggested in #3350 (comment) . It do NOT add or change any existing functions.

@thinkyhead I tried use git rebase, and unfortunately, I deleted this branch, so I resubmit it again. Sorry!

### CODE REVIEW

**Comment by thinkyhead** [comment]
I think that it would be best for `#define CUSTOM_MACHINE_NAME` (in the `Configuration.h` files) that unless the custom name has non-ASCII characters, we should leave out `UxGT(...)`. I'd like to keep this macro out of the configurations. Will that work?

**Comment by yhfudev** [comment]
I agree, but I can't push my changes after run git rebase, so I just use the merge and reverted the changes.

**Comment by petrzjunior** [comment]
@yhfudev After rebasing you need to force push `git push repository branch -f` if I'm not mistaken...

**Comment by thinkyhead** [comment]
`git push -f origin` ftw.

**Comment by yhfudev** [comment]
It works!! Thanks @thinkyhead, @petrzjunior

**Comment by thinkyhead** [comment]
Merged this and rebased #5441 onto the latest.

**Pull request merged**
