### PR TITLE
Smart-Fill and Mesh-Tilting (both 3-point and grid) working!

### PR DESCRIPTION
**Pull request by Roxy-3D**
- Smart Fill now available to quickly populate unprobed mesh locations
- 3-Point mesh tilting now fully functional
- Grid based mesh tilting now fully functional

Also...   The memory corruption issue may be fixed.   The GCC compiler
was inlining static functions and this caused the G29() stack frame to
become much larger than the AVR could handle.

And one last addition...  The Least Squares Best Fit algorithm has been made incremental so probed points can be feed into it as they are collected and no longer need to be stored.   For large grids, this lowers the required memory by a lot!

### CODE REVIEW

**Comment by thinkyhead** [comment]
w00t!

**Comment by thinkyhead** [comment]
> inlining static functions

That is a possibility alright! Functions marked `static` are invisible outside their compilation unit, so the compiler can be liberal about inlining if it wants to. Removing the `static` keyword makes the function visible to other compilation units. Removing "`static`" has been a remedy for another compiler warning in the past too. It was complaining about unused functions and removing `static` got rid of the complaints.

**Comment by Roxy-3D** [comment]
Yeah...  But it gets more hairy than that.   Things that are not part of a C++ class are 'static' if no extra information is given.   The function   void what_command();  was not static.  But because it was not part of the class, the gcode_G29() function inlined it.   That one wasn't too bad.  It didn't have much local storage.  But the other various routines like probe_entire_mesh() and fine_tune_mesh() etc. etc.   all do have a lot of local storage.    For some reason, the compiler doesn't even try to do a union of their local storage.   It just allocates new stack space for anything it inlines.    

AND...  that is what was causing the data corruption problems we were seeing.     Auuuugggghhhh!!!!!

Next time I update the code, I'll take out the multiple warnings about 'No statics in this file' now that you understand the issue that is being avoided.   I just wanted to make sure you saw that!!!

**Comment by thinkyhead** [comment]
> Things that are not part of a C++ class are 'static' if no extra information is given. 

Not so. A function declared without `static` in a `.cpp` file can be imported using `extern` in other files, whereas a function declared `static` cannot be.

> because it was not part of the class, the `gcode_G29()` function inlined it. 

It's best to avoid declaring global functions inside headers, because each compilation unit will make its own copy. The `static` keyword actually has no effect on this, but, yes, it can also lead to the function being inlined.

Repeat: Even without `static` the function will still exist as a separate copy in each compilation unit that includes the `.h` file, because the contents of the `.h` file are simply inserted into the body of the `.cpp` file when `#include`d.

The general guideline is, if you don't need a function to be `FORCE_INLINE`, and if you don't want multiple copies of it, and you want to use it in more than one compilation unit, either move it to a `.cpp` file and just declare it in the header, or move it inside of a `class` (or `struct`) and then it's safe to declare it `static` in the class, as there will only ever be a single copy.

> The function void `what_command();` was not `static`.

If I made it `static` it was an oversight. I missed that detail somehow. Instead I should have made it to be declared in the header and defined in one of the ubl-related `.cpp` files.

**Comment by thinkyhead** [comment]
> I just wanted to make sure you saw that!!!

I did see that, and I already have a PR that removes the comments, since they apply to C++ headers always and everywhere, and I assume that developers already know that.

**Comment by Roxy-3D** [comment]
>> I just wanted to make sure you saw that!!!

> I did see that, and I already have a PR that removes the comments, since they apply to C++ headers always and everywhere, and I assume that developers already know that.

No...  I'm pretty sure most developers do **NOT** know this.   It took 4 of us working together with a hardware debugger to figure out what was happening.   Without the ability to look at the disassembled code we would have never figured it out.

Even once we saw that the stack frame was getting set to a huge size (for no apparent reason) it took more analysis to find that functions with large amounts of local storage were getting added inline and that  the compiler was just bumping up the stack frame size for each function it inlined.  It would seem the compiler could do a union and just bump the stack frame up to what ever the largest function was that it inlined and let the other inlined functions use that same space.

**Comment by thinkyhead** [comment]
> Without the ability to look at the disassembled code we would have never figured it out.

I would have figured it out with some investigation. I just didn't. This is a common error.

**Pull request merged**
