### PR TITLE
[2.0.x] L6470 - add powerSTEP01 support (replaces PR #13053)

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
This PR replaces PR #13053.  There are no functional differences between the code in the two PRs.

This PR uses the "helper" method of linking external SPI routines to the Arduino-L6470 library.

See PR #13053 for functionality information.

This PR requires a change to the Arduino L6470 library.  Here are the new library files.
[L6470 (helper).zip](https://github.com/MarlinFirmware/Marlin/files/3010673/L6470.helper.zip)

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'll bring the library files over very soon, if you haven't already submitted a PR to my fork. I'm going to be on the road to MRRF so I may be slow to fully evaluate this, but I will be checking in periodically.

**Comment by Bob-the-Kuhn** [comment]
Plans?  

Would you like me to do something?

**Comment by Bob-the-Kuhn** [comment]
This PR is now up to date with the current 2.0.x.

It has been successfully tested.

**Comment by Bob-the-Kuhn** [comment]
If wanted, I can squash all the commits down to one.  There's so many false starts and rebases that I doubt the it's useful to keep access to the individual commits.

**Comment by Bob-the-Kuhn** [comment]
This has been hanging around for 3 months.  Time to kill it.

**Comment by thinkyhead** [comment]
Old PRs don't need to be killed. I can keep them up to date as I get around to them. I have been trying to clear PRs but there are a few developers who feel the need to submit 2-3 non-essential UI enhancements a week, and this is killing our productivity in supporting hardware. I very much want to get this L6470 stuff merged whether it is "perfect" or not.

**Comment by Bob-the-Kuhn** [comment]
I don't see a reason to invest any more work into these products.  The TMC5160 is a superior solution in every way with the possible exception of the powerSTEP01 when applied to motors larger than NEMA 23.

Along that same line I'm wondering if we should just drop the support for this product line completely.  I'm only aware of two people that tried to use these drivers and I was able to pursuade one of them to go with TMC drivers.

If you see value in merging this PR then I'm willing to give it one more shot.  

I'm going to be travelling for the next 3 weeks so it'll probably be a month before I have time to pull the hardware out of storage and start the rebase/test process.

**Comment by thinkyhead** [comment]
I agree it's not a vital feature, and we can always revisit it later on. Happy travels! We'll just keep sweating it out here in Austin.

**Pull request closed without merging**
