### PR TITLE
STM32F1: Allow board_build.rename like in STM32 HAL

### PR DESCRIPTION
**Pull request by tpruvot**
Avoid to keep useless specific python scripts...

### CODE REVIEW

**Comment by tpruvot** [comment]
on hold, it doesnt do it each time... need to figure why

**Comment by tpruvot** [comment]
no, its ok, but firmware.bin need to be deleted/modified to (re)generate the renamed firmware...

**Comment by thisiskeithb** [comment]
> no, its ok, but firmware.bin need to be deleted/modified to (re)generate the renamed firmware...

Please automate this or we're going to be flooded with support tickets due to "firmware not updating".

**Comment by tpruvot** [comment]
what do you mean ? its automated, and does not affect other boards for now.... well its just i tried it on a already built firmware... its why i said "hold on" ;) its same build logic as before/usual ... as STM32 one at least

custom_board.py is only used by STM32F1 boards...

```
git grep -n custom_board.py
buildroot/share/PlatformIO/scripts/custom_board.py:2:# buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:100:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:132:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:148:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:185:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:197:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:212:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:227:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:352:  buildroot/share/PlatformIO/scripts/custom_board.py
ini/stm32f1-maple.ini:405:  buildroot/share/PlatformIO/scripts/custom_board.py
```

also most will not use that, because they encrypt their firmwares, longer board just need a specific filename on the SD card to update it

main goal was to drop STM32F103VE_longer.py and make things less complicated

**Comment by thinkyhead** [comment]
It should work to just add `offset_and_rename.py` to `extra_scripts` instead of modifying `custom_board.py`.

**Comment by thinkyhead** [comment]
Another option is to add `offset_and_rename.py` to the `extra_scripts` for `[common_stm32f1]` and that should not bother any other envs.

**Comment by thinkyhead** [comment]
Ok, I went and did that. Do you see anything in `offset_and_rename.py` that would be troublesome for Maple world?

**Comment by tpruvot** [comment]
in fact offset is already handled in custom_board.py.. Unsure what happens when both are used... will retry, i forgot to remove the pre: when i tried... ah no its not offset... its address

**Comment by tpruvot** [comment]
yes, works too

**Pull request merged**
