### PR TITLE
[2.0.x] Add endstop noise filter

### PR DESCRIPTION
**Pull request by thinkyhead**
As a way to mitigate the rare event of noisy endstops…

Moved over from #10688

### CODE REVIEW

**Comment by ejtagle** [comment]
@thinkyhead : Let´s review what it was before #10688 ...

At Endstops:update(), after polling, we had current_endstop_bits static variable with the current bits of endstops set for all triggered endstops.
And also we had old_endstop_bits with the  previous value of that variable.

To determine if an endstop was triggered, the following macro was used:

```
// TEST_ENDSTOP: test the old and the current status of an endstop
#define TEST_ENDSTOP(ENDSTOP) (TEST(current_endstop_bits & old_endstop_bits, ENDSTOP)) 
```

The return of this macro is TRUE only if both current and previous sample was true: That translated means we needed 2 consecutive samples where the endstops are triggered to be able to recognize endstops were triggered:

Implications:
-1 sampling delay (that varied based on the stepper interrupt rate) before recognition -> 1 step imprecision in recognition of swith close (or maybe more, it all depends on the pattern. For example, if due to bouncing we had the following sequence:

1010101010010101010010101001010100011111...

Then recognition would be delayed by 37 samples.

Assuming a 10khz sampling rate, well, that translates to 3.7uS of delay, Of course i agree this to be exagerated.

(https://www.allaboutcircuits.com/technical-articles/switch-bounce-how-to-deal-with-it/) ... Usually oscillations are at slower rate... about 1 to 2khz is typical.

But the main problem is not that: As explained in #10688 , the problem is with poorly designed boards that do not have a filtering capacitor in the limit inputs (most RAMPs boards). Essentially, you end hooking a wire of the ideal length to be an antenna for FM and all kinds of radio frequency to the input pin of a micrcontroller. That microcontroller has an internal weak pullup of about 20..50kohms, that is not strong enough, so the wiring acts as an antenna. And that creates a big problem.

We all agree that when the switch is closed, the possibility to pickup noise is nearly 0, as the switch acts as a nearly 0 ohm resistance to ground.

But if the switch is open, it is highly likely that noise will be confused as a switch close... How much time ? .. It is impossible to know. We assume it is likely to be less than 1mS, but there is no warranty at all.

The suposition of 50% of bad reads vs good reads is conservative. But imagine yourself locked inside the microcontroller, and the only thing you know is what the input pin tells you. There is no way for you to know if it is noise, or the switch itself being closed. And you must make a decision.

The previous algorithm was: 2 consecutive readings, then it is closed
The current algorithm is: If it says it is closed, then it must be
This PR proposes the following algorithm: If there was no change in the last 7 samples, let´s assume that that is the true state. Thats the way usually debounce/denoise is done in software, 

Undoubtly this is a mitigation, The best solution is always to fix the hardware, add the missing 100 nanofarads capacitor across the switch, and everybody is happy.

Why did I remove the original algorithm ? - Because of properly implementing Interrupt-On-Change use as endstop state detection. We don´t want to be polling switches!. And any of the mitigations (the old first, and the one proposed here) forces to poll endstops periodically.

The best solution is just to fix hardware.

And there is another more subtle reason: The old algorithm was reducing accuracy without telling the user - Conceptually that is not OK : Workarounds and mitigations, when they trade accuracy for reliability, and when there is an easy hardware fix should never be enabled by default and remain unnoticed!

**Comment by thinkyhead** [comment]
Thanks for the thorough explanation. Of course, we only have two choices: to poll or to interrupt-on-change. With polling, it's just a question of how often we poll, and how quickly we can respond. With endstops I'm not worried about a small amount of delay, but with probes we want the fastest-possible reaction-time and so any logic that makes it more definitive makes me happy.

I only wish we had some real-world tests to see what's really going on during switch-presses and just exactly how much bounce there is on various kinds of switches.

One thing (I hope and pray) we can be pretty sure about, especially at the "low" rate of sampling we use, is that when switches are pressed, even if there's a small period when they bounce, there should be a very steady 1 or 0 state once the switch is definitively pressed. I cannot imagine that it ever adds up to something as extreme as 37 samples, even when hitting an endstop at the slowest speed.

But again, I'd very much like to see real data using real switches so we know just what the best- and worst-cases really are. Maybe we can put together a tiny Arduino sketch that uses exactly our current methods and connect a few different kinds of switches to an Uno to collect some samples. Meanwhile, I'll do some Google searching and see if there are any good articles on this topic. I'd like to know what the global consensus is about switch and signal reliability.

**Comment by ejtagle** [comment]
@thinkyhead ; The main problem is noise. Bouncing is not. If there was no noise, then for limit switches i would not worry about bouncing. Just because as soon as you get the 1st logic "1", you are absolutely sure the limit switch has been pressed.
Noise masks as bouncing, and bouncing mask as noise. So, if a simple hw mod removes noise, then limit switches do not require debouncing, at least on this specific application 👍

**Comment by GMagician** [comment]
I don't know if marlin after first detection raises by space or by checking input again. In first case I agree with @ejtagle , no problem with bouncing, in second case bouncing may be an issue because we are not sure axis will raises enough for 2nd check.
By the way noise is always an issue. In my personal case I use normally closed switches that are tied to 5V and when micro detect closes to 0V so I should be "less" prone to noise, but I will add a capacitor, just to avoid also bouncing.

**Comment by ejtagle** [comment]
@GMagician Marlin just raises. The idea is that an endstop switch only forbids movements in the direction that would make the motor force the limit. That is why bouncing is not a problem. The problem is noise. ANY pulse of noise will abort the current move!! ... But not necesarily the rest of the printing (unless "abort print on endstop hit" is set)

That is why i would suggest to force that option to be always set IF we are keeping enabled endstops while printing...

But the best approach will be adding that filtering capacitor!

**Comment by thinkyhead** [comment]
> ANY pulse of noise will abort the current move

(When endstops are enabled.)

With `ENDSTOPS_ALWAYS_ON_DEFAULT` or `ABORT_ON_ENDSTOP_HIT_FEATURE_ENABLED` endstop noise (inductance) would definitely be troublesome.

**Comment by ejtagle** [comment]
@thinkyhead : You are right. Some printers do have that define enabled on their configs, some of them do not. We should be asking people on the layer-shift thread on their configurations, to try to find out correlations...

**Comment by thinkyhead** [comment]
> We should be asking people on the layer-shift thread on their configurations, to try to find out correlations...

That would be very ironic! I think there really is something going on with the planner, though, because with the very same configuration some see it in Marlin after mid-February, but before then (1.1.8 for example) they don't see the issue.

**Comment by ejtagle** [comment]
I have also inspected changes and I see no obvious change that could be causing that... But, anything that could be disabling stepper ISRs, or causing an starvation of the planner queue could cause that. The reason is that the planner never plans from stop. It always plans from MINIMUM SPEED. (Grbl plans from 0 speed). That means starvation makes the motor stop abruptly, and could lead to lost steps...

**Comment by thinkyhead** [comment]
Starvation shouldn't give an abrupt stop, because all blocks in the planner are given acceleration and deceleration slopes. The last one added assumes it needs to decelerate to zero, and prior blocks (in the reverse pass) are given deceleration slopes to match. However, if the last block is lacking a proper deceleration slope, _that_ would lead to an abrupt stop.

High jerk applied to the last block might also lead to a short but abrupt stop going from the jerk speed directly to zero.

**Comment by thinkyhead** [comment]
> …MINIMUM SPEED…

Oh! Are you saying the planner doesn't apply 0 as the exit speed on the last block added?
Geez, it really should, or it should never be above the jerk anyway.

**Comment by ejtagle** [comment]
@thinkyhead : Exactly. It caught my attention

**Comment by ejtagle** [comment]
@thinkyhead : That is the reason for sq(MINIMUM_PLANNER_SPEED). In most cases, that should be 0.0 instead
After all, if planner is working properly, it readjusts speed profiles to respect jerk
BTW: With the latest changes, MINIMUM_PLANNER_SPEED can be much lower than that speed (timer is "virtually" 32 bits... 
I think the speed limitation should be done elsewhere (Probably when computing the trapezoidal profile in calculate_trapezoid_for_block(), not at the planner forward and backward passes).  And the limitation is the maximum timer value (due to implementation details in stepper::calc_timer_interval(), 65535 on AVR, 0xFFFFFFFF on ARM targets)

**Comment by thinkyhead** [comment]
Darn, turns out for my client's custom SCARA machine I really need a public `stepper.set_position` and the `stepper.set_position` that sets a single axis. I'll have to revert those changes from the recent refactor.

**Comment by ejtagle** [comment]
Add those missing methods again 👍  -- No problem 👍

**Comment by thinkyhead** [comment]
Possibly a temporary measure. Anyway, since I made them `inline` the compiler _should_ throw them away if they're unused.

**Comment by ejtagle** [comment]
@thinkyhead : The linker DOES throw them out. I am absolutely sure of that. That is (one of the purposes of ) the -lto flag

**Comment by thinkyhead** [comment]
I figured it did, but there's this part of me that always mistrusts my assumptions about compilers and linkers.

**Comment by GMagician** [comment]
@thinkyhead lol..as I know, if memory help me, from x86 world, inline funciotn should be added by compiler as soon as they are used, linker can only merge everything and update "pointers"

**Comment by ejtagle** [comment]
With -lto, there is a change in that paradigm: The compiler parses code, creates an intermediate representation of the code and stores it into the .obj file.
The linker takes that intermediate representation, solves dependencies, inlines functions, removes what is unneccesary and does the actual compilation! ;) (yes, things have changed quite a bit... I also had the same doubts, but if you do an obj-dump of *.o files with, and without the -lto flag, you will see there is no assembler nor generated code in the *.o files if using the -lto flag (lto = linker time optimization)

**Pull request merged**
