### PR TITLE
Improve Creality EEPROM watchdog behavior

### LINKED ISSUE #20449: Ender 3 v2 UBL 15x15 Mesh save using G29 S0 causes reboot/reset
### Bug Description

I have been using ABL 10x10 mesh for bed leveling. And a similar issue has been corrected by @sjasonsmith ( Bug:#20307)
I have switched to UBL with 15x15 mesh as my glass bed is heavily wrapped. But when saving the mesh by G29 S0 the board restarts. This has been tested by bug fix branch from today.

### Configuration Files

**Required:** Include a ZIP file containing `Configuration.h` and `Configuration_adv.h`.

[config.zip](https://github.com/MarlinFirmware/Marlin/files/5683523/config.zip)

If you've made any other modifications describe them in detail here.

### Steps to Reproduce

1. G29 P1
2. G29 P3 as long as all points are filled.
3. G29 S0 

**Expected behavior:**

Saving the mesh successfully.

**Actual behavior:**
Printer/board restarts

#### Additional Information

As mentioned a previous issue saving mesh to eprom using M500 was caused by watchdog and solved by @sjasonsmith . I think this might be a similar issue but only the save process is by G29 S0

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

The BL24Cxx EEPROM is very slow, and can trigger watchdog resets while writing large meshes.

An earlier change improved this, but would only service the watchdog every 128th byte if (and only if) that byte was being modified. With some patterns of data this caused the watchdog to expire and reboots to still occur.

This change tracks the number of bytes actually written, so that it will service the watchdog for every 128th _written_ byte.

### Benefits

Avoids watchdog resets when storing large meshes.

### Configurations

Ender 3 Pro 4.2.7 example, with BLTouch and UBL with 15x15 mesh.
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/5720290/Configuration_adv.zip)

To reproduce the error prior to this change, execute the following sequence:
```
G29 P0
G29 Q2
G29 S0
G29 Q0
G29 S0
```

### Related Issues

Fixes #20449

Also improved robustness for earlier issue #20307

### CODE REVIEW

**Comment by sjasonsmith** [comment]
CI is failing because TMC slave addresses were changed in examples, but the Marlin changes have not yet merged into bugfix.

**Comment by nelsongraca** [comment]
Any clue when will be a release with this fix? I'm having this issue too

**Comment by sjasonsmith** [comment]
> Any clue when will be a release with this fix? I'm having this issue too

I don’t know when there will be a release. You can use the bugfix-2.0.x branch directly if you take note of the most recent commit number you can locate that exact “version” again later.

**Comment by sjasonsmith** [comment]
If this fix is all you need you could probably copy the single file changed from in this commit into your current released version.

**Comment by nelsongraca** [comment]
Thanks, will check the commits if there is anything relevant I just pull the branch, otherwise I'll pull a patch of this PR.

**Comment by sjasonsmith** [comment]
This PR built upon an earlier change that wasn’t quite complete. Pull the entire file if you decide you just want this one.

**Comment by nelsongraca** [comment]
I'll get the branch then, thank you

**Comment by mrseeker** [comment]
Issue also seem to appear on an Ender-3 Pro with BTT SKR 2.0 mini E3, same setup (UBL + large mesh).

**Comment by hakimio** [comment]
@sjasonsmith I have the same issue with MKS Robin Nano v2. Can this change be applied to other EEPROM write implementations?  For example, my board is using `STM32F1/eeprom_wired.cpp`.
See issue #21186 for more info.
I think your solution is better than increasing watchdog duration to 8 seconds.

**Pull request merged**
