### PR TITLE
EXP headers for RAMPS 1.x

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Update Ramps with EXPA1/EXPA2 definitions.
A step towards unified LCD configs where there is only one definition using only EXPA pins 
Also added some pin documentation.

### Requirements

none.

### Benefits

Heading towards Unified LCD pins.

### Related Issues

none.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Note that many boards which are "RAMPS-like" do not have the same EXP headers as the common RAMPS. So asserting in `pins_RAMPS.h` that the pin numbers always associate with certain EXP header pins may be misleading when trying to work out the pinouts of other RAMPS-like boards that differ from `pins_RAMPS.h`, and especially if EXP header pins end up being included in the output of `M43`.

**Comment by ellensp** [comment]
You have broken the whole point of this PR. The point of this PR is to use the same naming convention as in lpc1768/pins_BTT_SKR_common.h, lpc1768/pins_BTT_SKR_V1_3.h, lpc1768/pins_BTT_SKR_V1_4.h, stm32f4/pins_BTT_SKR_PRO_common.h and stm32f4/pins_FYSETC_CHEETAH_V20.h
So eventually we can have one for eg lcd_modules.h that just uses EXPA1 and EXPA2 pins for all boards.

**Review by ellensp — COMMENTED** [review]
You have broken the whole point of this PR. The point of this PR is to use the same naming convention as in lpc1768/pins_BTT_SKR_common.h, lpc1768/pins_BTT_SKR_V1_3.h, lpc1768/pins_BTT_SKR_V1_4.h, stm32f4/pins_BTT_SKR_PRO_common.h and stm32f4/pins_FYSETC_CHEETAH_V20.h
So eventually we can have one for eg lcd_modules.h that just uses EXPA1 and EXPA2 pins to define lcd pins for all boards.

**Comment by thinkyhead** [comment]
Sorry, I forgot to do the rest of the EXPA# => EXP# replacements. Are we expecting to have EXPB and EXPC in future?

Note my comment above about the RAMPS common pins file. It may be fine to have these in the "fallback" RAMPS pins file since it generally applies to RAMPS 1.x, but these new expansion header items should only be defined if they have not been previously defined by another pins file that is including the RAMPS one.

**Comment by ellensp** [comment]
I was thinking EXPA as expansion abstraction vs actual port names

**Comment by thinkyhead** [comment]
Most boards I've seen use the three-letter 'EXP' prefix plus a numeric digit as the silkscreen label for expansion headers.

**Comment by ellensp** [comment]
If you want to use EXP1 EXP2 vs EXPA1 and EXPA2 that is fine as long as they all change.

**Pull request merged**
