### PR TITLE
Added hyphenated strings for full graphic display

### PR DESCRIPTION
**Pull request by silvio-didonna**
I don't know how to replace some accented letters. e.g. :
-a instead of à and á
or
-a' (with apostrophe) instead of à and á

Both are wrong but probably the last is better for italian users whereas the first is better for small display.

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
> à and á
> will probably display  perfectly on a full graphic display, but not on a character display.

```
#if ENABLED(DOGLCD)
  #define WORD "wordwithá "
#else
  #define WORD "wordwitha' " // or a - thats a matter of taste. We have no rule for it.
#endif
```

**Comment by thinkyhead** [comment]
Looks like Portuguese needs the same.

**Comment by silvio-didonna** [comment]
I will update this PR shortly with this modifications. Some minutes.

**Comment by silvio-didonna** [comment]
Updated. 
@thinkyhead Please check if it is correct and please tell me if I made the rebase well.

**Comment by thinkyhead** [comment]
Seems good. I suppose you could use the 'fixup' option with `git rebase -i` to combine it into a single commit, since the first commit is, by itself, not useful.

**Comment by silvio-didonna** [comment]
Now it should be ok. Please tell me if there is any problem. 
I'm still learning git.

**Comment by thinkyhead** [comment]
Great, thanks!

**Pull request merged**
