### PR TITLE
XY Skew correction #3839

### PR DESCRIPTION
**Pull request by Paciente8159**
Hi there.
I've been fixing my printer bed skew via firmware.
I'v implemented the change to the code to address #3839
XY Skew factor is defined via M852 F(value) comand.
Value is stored in EEPROM.

### CODE REVIEW

**Comment by Grogyan** [comment]
Might be a good idea to have a calculator on the MarlinFW wiki too to help compute the correction factor

**Comment by Allted** [comment]
Would it be much harder to add it to the xz or yz axis as well? This is too cool and could really help get more accurate prints for those that care to set it.
It seems that tiny build errors that would be hard to physically adjust out could really use this. Most printers have no physical way to adjust them.

**Comment by Paciente8159** [comment]
> Would it be much harder to add it to the xz or yz axis as well?

That can be done.
I'll try to modify the code during this week and test it in order to take the bed/z skew in account.
I'll do a printable test part for it too.

**Comment by Allted** [comment]
I hope that didn't come off rude or pushy I just figure might as well get them both in there at the same time. This does seem like it might be something a slicer could do as well but if it can be done in the firmware than even better. Thanks for working on this.

**Comment by Paciente8159** [comment]
> I hope that didn't come off rude or pushy ...

Not at all. I've just addressed this matter since I felt the need to get proper printing dimensions without being slicer dependent (and the funny coincidence is that I actually decided to tested my printer for skew issues after printing some of the parts for the MPCNC, lolol).

But now thinking of the XZ/YZ skew problem, my main concern is the effect of bed leveling + skew fixing.
I got to study this carefully.

**Comment by Allted** [comment]
LOL I think my parts are some of the first that make people realize how far off there printers are! Ahhh the bed leveling Good point. Maybe start with just make it for people that don't use bed leveling. I know a majority of the users use bed leveling but maybe that will nudge them to just manually leveling there bed? Not an ideal solution but it lets some of us try it. I should actually see how far off my printers are, I have checked a few times and it did seem minimal at the time. I will try to come up with a part that can be accurately measured without first layer heights affecting it too much.

**Comment by Paciente8159** [comment]
I've added a vertical test piece to https://www.thingiverse.com/thing:2563185.
Check if it fits your needs.

**Comment by thinkyhead** [comment]
Alas, all submissions must be based upon and submitted to the `bugfix-1.1.x` and/or `bugfix-2.0.x` branches. Please recreate and resubmit for a proper review.

**Pull request closed without merging**
