### PR TITLE
Add SPI+DMA+interrupt method

### PR DESCRIPTION
**Pull request by ghost**
### Description

I added a macro USE_SPI_DMA_TC under pins_MKS_ROBIN_NANO_V3_common.h, and explained that if you open this macro, you need to cancel the knob, otherwise the color will be abnormal.
At present, there are two main amendments to this submission:

1. Use the DMA+DMA transfer completion interrupt method to refresh the LVGL, so that when the screen data is refreshed, the execution will not continue until the DMA transfer is completed, causing the execution of gcode to freeze.
2. In the function of tft_lvgl_init, the initialization of identifying SD card and U disk is added. If there is no SD card, but only a USB flash drive, then the user needs to enter the interface and manually click to switch the USB flash drive mode to use the USB flash drive. In other words, if the pictures and fonts are in the USB flash drive and there is no SD card, the update cannot be made. .

### Requirements

The update is mainly for NanoV3 + TS35_V2.0 +LVGL

### Benefits

Through the addition of DMA interrupt, more performance of MCU can be released, and the execution of gcode can be better guaranteed, and the program is not in a state of staying due to display.

### CODE REVIEW

**Comment by thinkyhead** [comment]
> makerbase-mks:bugfix-2.0.x

Pro tip: Always create a new branch before making changes instead of polluting your `bugfix-2.0.x` branch.

**Comment by thinkyhead** [comment]
> makerbase-mks:bugfix-2.0.x

Pro tip: Always create a new branch before making changes instead of polluting your `bugfix-2.0.x` branch.

**Comment by thinkyhead** [comment]
Are all changes meant to be associated with `USE_SPI_DMA_TC`? I have cleaned up the code on that assumption.

**Comment by ghost** [comment]
> Are all changes meant to be associated with `USE_SPI_DMA_TC`? I have cleaned up the code on that assumption.

Yes, I will distinguish two different DMA interrupts, one is FSMC, the other is SPI, after my use, it is relatively normal at present, I will continue to submit later

**Comment by thinkyhead** [comment]
> … I will continue to submit later

Do you want this left open to submit more commits, or is it good to merge now?

**Comment by ghost** [comment]
> > … I will continue to submit later
> 
> Do you want this left open to submit more commits, or is it good to merge now?

I hope it's merged now, because of the FSMC's DMA I need to do more testing, I'll commit again when it's done

**Comment by DvoraNoob** [comment]
This PR did the encoder stop working in the MKS UI and the Display stays yellow

https://user-images.githubusercontent.com/62312359/149787335-6f959512-228d-4917-a7a1-d6d616bd694d.mp4

**Pull request merged**
