### PR TITLE
Fix Typos

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
- Simply add `)` to docs\ConfigEmbedding.md
- Replace `"` with `'` in `cron:` in **.github/workflows/close-stale.yml** | **.github/workflows/auto-label.yml**, which is the correct sytax
```diff
-  - cron: "30 8 * * *"
+  - cron: '30 8 * * *'
```

### CODE REVIEW

**Comment by gudvinr** [comment]
What is the purpose of your changes? What issue this PR solves?  
Not only this one but also other PRs that just "fix" typos.

I don't really care if marlin maintainers are fine with that but it just looks weird.  
Although from personal perspective, this is just unnecessary noise. While not developing marlin, I sometimes skim through PRs for some useful things to test.

But more importantly, when you contribute to project this big this also leads to set of issues:
- increased load on maintainers
- reduced git blame usefulness
- CI/CD time waste

These kind of changes are never necessary unless:
- they come together with significant changes (i.e. you modify code with piggybacking typo fixes into these changes IF those are relevant to changed code)
- wording itself is an error (e.g. variable with name `max` contains minimal value or comment is misleading)

Otherwise you create changes that will waste other people's time with no practical benefit. Considering that it's not the first PR that comes from you, it looks like you do have some strategy though.

**Comment by gudvinr** [comment]
> Replace `"` with `'` in cron: in **.github/workflows/close-stale.yml** | **.github/workflows/auto-label.yml**, _which is the correct sytax_

YAML is superset of JSON, and in JSON `"` will be the correct token to wrap character sequence.

Also, according to [YAML specs](https://yaml.org/spec/1.2.2/#731-double-quoted-style) double quotes are defined as a way to define string (scalar in terms of YAML types).  
Github doesn't specifically say which spec they use for workflow files, but on their [documentation page](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions) they refer to "[Learn YAML in Y minutes](https://learnxinyminutes.com/docs/yaml/)" which uses double quotes too.

So it is unclear what you mean by "correct syntax" if `"` is not incorrect.

**Comment by classicrocker883** [comment]
>So it is unclear what you mean by "correct syntax" if " is not incorrect.

meaning if you look up how this is supposed to be, the correct usage, not only that but looking at similar files use that same syntax.


talk about a waste of time, look at how much you wrote for the very little changes, and now wasting my time. wow
this solves the issue of it being a typo, nothing major. if it were anything else I would have said so.

**Comment by classicrocker883** [comment]
first I'm told not to piggypack code with other **PR**'s because it would be irrelevant. to keep all the code separate. then I'm told keep it short because its easier and faster to get pulled/merged.

now I'm told beneficial changes, no matter how small, aren't accepted unless it solves world hunger.

well it is what it is. so what then? search for more Typos in order for this **PR** to be acceptable?

or put it into an unrelated random one?

**Pull request merged**
