### PR TITLE
Cleanup of G38.2 / G38.3

### PR DESCRIPTION
**Pull request by thinkyhead**
Rebased, cleaned up, and properly implemented #4845.
Still not keen to merge it. But since the feature is disabled… maybe.

Original request: #4677

### CODE REVIEW

**Review by Bob-the-Kuhn — CHANGES_REQUESTED** [review]
I see that this command uses the homing feedrate rather than specified/current feedrate.  6 of one, half a dozen of the other

in config_adv - please add some text
// G38 Probe Target
//   uses the Z_MIN endstop to determine when the target has been reached
//   Requires the following be set in configuration.h
//      1) FIX_MOUNTED_PROBE needs to be enabled (uncommented)
//      2) either HAS_Z_MIN_PROBE_PIN or Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN needs to be enabled (uncommented) - but not both

in marlin_main.cpp

  line 7188
    had to move "uint8_t subcode = 0;" further up or else got "crosses initialization of 'uint8_t subcode'"
    didn't matter what the variable name was (tried several besides subcode) or type

  line 7189 - 12
    from:
         uint8_t subcode = 0;
         if (_cmd_ptr == '.') {
           while (NUMERIC(_(++cmd_ptr)))
             subcode = (subcode \* 10) + (_cmd_ptr - '0');
         }
    to:
         if (_cmd_ptr == '.') {
            cmd_ptr++;  
            do {
               subcode = (subcode \* 10) + (_cmd_ptr - '0');
               cmd_ptr++;
             } while (NUMERIC(_cmd_ptr));       

```
     }
 remarks:  the original code went through the substring by two bytes at a time
           I understand why it skipped the first character after the decimal point.
           I don't understand the skipping every other character when the 
```

  line 2228
    from:  feedrate_mm_s = homing_feedrate_mm_s;
    to:    feedrate_mm_s = homing_feedrate_mm_s[Z_AXIS];

  line 5365
    a non-printable character snuck in there somewhere - replacing all the white spaces using the spcae key solved it

  line 2234 retract distance same as commanded move - excessive - went to homeing bumps

  line 2240  my first tests showed that the retract direction was the same for - moves as for + moves
             after I added print statements it worked.
             still works after removing the print statements
             I don't know why (what looks like good code) didn't work initially but is now working with no obvious changes

**Comment by Bob-the-Kuhn** [comment]
Sorry about not fully translating my code from 1.0.2 to the new style.  Just forgot.

I like your code.  Fairly easy to read.

There were a few bugs in your code.  The attached file has them corrected.  My comments a few minutes ago have the details.

The original **subcode** routine was going through the string two bytes per pass.  It looked like _**cmd_ptr_\* was acting like a pointer to a uint16_t variable instead of a uint8_t.  I couldn't figure out why so I  grabbed the parser previously used on the string (before getting to the decimal point) & substituted/modified for the **subcode** routine.

I did some playing with the retract distances.  I think using only the **x_HOME_BUMP_MM** distances is the way to go.

   Bob
[Marlin_main.zip](https://github.com/MarlinFirmware/Marlin/files/497016/Marlin_main.zip)

**Comment by thinkyhead** [comment]
The zip file is a creative touch. I'll check it out.

**Comment by thinkyhead** [comment]
How about now…?

**Comment by Bob-the-Kuhn** [comment]
??

**Comment by thinkyhead** [comment]
> ??

I applied the changes, fixed them up with `git rebase -i` and pushed them with `git push -f`.

So how does it look?

**Comment by Bob-the-Kuhn** [comment]
I'll grab the updates & look at them tomorrow.  Getting pretty late for me & I'm starting to make silly mistakes.

**Comment by Bob-the-Kuhn** [comment]
It's ready for prime time.

It compiled with no issues, does all the moves correctly and uses reasonable feed rates.

Thanks for all your work on this.

**Pull request merged**
