### PR TITLE
Pause command improvements

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Add examples for repetiere and remove pre-filled output portion to allow other hosts to work correctly

### CODE REVIEW

**Comment by thinkyhead** [comment]
@repetier — What's the proper case for sending these strings to Repetier?

- `RequestPause:FilamentRunout`
- `RequestContinue:FilamentRunoutResume`

**Comment by repetier** [comment]
To make it compatible with Repetier-Host and Repetier-Server it must be
RequestPause:FilamentRunout
RequestContinue:

no echo before it, or if you have a echo before the must be a space after echo:
RequestContinue does not show a message, it is just like hitting the continue button in host, so message can be send mit will be ignored.

But be aware that you should not combine this with
// action:paused
// action:resumed

These tell host/server to stop communication and wait for resume. This will prevent host/server from sending new commands. In repetier-firmware these are e.g. used if you start filament change over firmware controlled lcd so host/server do not interfere. Actually that is the only case we use it there. I saw in the code change that you also plan to send both. That makes me feel it was intended to be used differently. 
So is it always used as request to host to just stop the print but not stop communication? In that case I could modify it that it also is interpreted as request. 
Just be aware that host/server are eager in sending commands so buffer contains already some printing commands when it receives resp. you send the request. So you need to execute them as well as all  other commands getting send then.
You should maybe also change the order when you send both. That way the pause with additional informations come first. Host will ignore pauses in pause mode so with action first it then would show a empty pause reason even though a later line sends a reason.

**Comment by repetier** [comment]
One more question about // action:resumed - if paused is meant to pause host with a dialog, how is host supposed to close this condition. I always assumed if firmware sends action:paused there is some dialog going on that should not interfere with a print and firmware closes this dialog and sends resume after it is finished. If host now also runs a pause it should be able to close that wizard as well, or did I miss something here.

**Comment by thinkyhead** [comment]
I was thinking that the use case is different for `RequestPause:`/`RequestResume` than it is for the `//action:` items, but I'm not yet clear on the distinction.

As I understand it, the `//action:pause` tells the host that we're busy with (for example) LCD-based filament change or some other procedure, and that we want the host to stop _sending_ commands until we're done, which we signal with `//action:resume`.

If that's the exact meaning of `RequestPause:`/`RequestResume:` then this PR is generally correct.

One problem I foresee is that since we don't know which host we're talking to, our only real option is to send both the `//action:` and the `Request...` for full compatibility. It doesn't make much sense for us to set up a situation where a Repetier-compatible build of Marlin isn't compatible with OctoPrint, and vice-versa.

So, if Repetier does interpret the `//action:` commands, then we don't need to add these others.

**Comment by repetier** [comment]
> As I understand it, the `//action:pause` tells the host that we're busy with (for example) LCD-based filament change or some other procedure, and that we want the host to stop _sending_ commands until we're done, which we signal with `//action:resume`.
> 
> If that's the exact meaning of `RequestPause:`/`RequestResume:` then this PR is generally correct.

At the moment it is a different meaning. RequestPause: means firmware does nothing and "hopes" the host will show a pause. Think of it as the display less firmware solution. Then firmware can not handle filament change on it's own so it asks host to stop and user to do it. //action:paused is the opposite - It tells host to shut up so it can do the task locally without hosts/servers interference. So if all you want is the host to shut up for a while just say with // action:paused - host and server do know them already just like octoprint. So I guess what you use/send should depend on the place where you want to handle the problem.

**Comment by thinkyhead** [comment]
Ok, that is kind of what I was assuming. I'll see that this gets implemented with that in mind, if we need to implement it at all. We received a request about it, and from the person requesting the feature it sounded like Repetier wouldn't interpret the `//action:` strings. Since it does, I think we may already have everything we need. But I'll look at the case where we don't have `M600` and see what we want to do with that.

One thing we want to be careful about is a situation where the host is paused and not sending commands, and the machine is sitting idle with the heaters on for many hours. So we need to make sure during the period when we're waiting for the host to continue sending commands, we are able to power down the heaters, and then when the host starts to send new commands, we want to make sure to put an `M109` (and `M190`) in the queue before accepting new commands from the host.

**Comment by repetier** [comment]
Yes, you have to be careful about such requests. My guess is that this user expects both to show the pause and to select where to solve it. But that would be more complicated as hosts then would need to tell firmware to close its wizard. Speaking of that - if firmware supports start/stop protocol host will send
```gcode
M539 P1
```
to indicate it paused and
```gcode
M539 P0
```
to indicate pause finished. But that was more meant for the specialized printing display so it could also update informations.

Temperature handling is in deed something to think about. Especially extruders - guess disabling bed is not so good and not critical. Maybe that is something to also add on host/server side. Repetier-Firmware can store temperatures and restore them (stored just inverts temperature to negative value) so we could just call these command sin case this was wanted. But a switch in printer might also be a good addition.

**Comment by InsanityAutomation** [comment]
Since originally the prefix portion was in the M600 command, ill keep that in the config file now for full flexibility, which will make it possible to play with different commands without going out of config. Since Repetier does support the same action commands with the same method as octoprint, it should work as it was without an issue.

The current m600 does timeout the extruder heater and cool it, but retain the bed. With some of the build surfaces out there, this is the correct action. It expects the user to resolve everything from the LCD. This is currently the only place this command is used. We could expand its use to a menu driven pause / park if desired, but that would use the same pair of commands. The alternating set would only be used if we implemented an m600 that didnt rely on an lcd for filament change.

**Comment by InsanityAutomation** [comment]
Looking through the discussion a bit more thuroughly, I see octoprint expects pause / resume where repetier expects pauseD and resumeD. I will test it out tonight if octoprint still parses it with the d on the end, otherwise we may need to send both regardless.

**Comment by repetier** [comment]
Sorry for the confusion. Repetier Host and server also only require

// action:pause
// action:resume

just checked to be sure. Did not see on https://reprap.org/wiki/G-code#Action_commands that there are 2 types to write. I use the original one that always were there.

**Comment by InsanityAutomation** [comment]
Looking at the pauseD and resumeD in that article sounds like they would be expected when you pause and resume an SD job, not a streamed job. This would allow time lapse videos to be paused and such.

**Pull request closed without merging**
