### PR TITLE
follow-up the commit b82d91e

### PR DESCRIPTION
**Pull request by ghost**
follow-up the commit b82d91eca69d87334530d874de79d85d06c54c2e

No.70 thermistor is used only for Hephestos 2,
but current situation may lead to conflict or trouble 
when if people that they doesn't know or forgot it trying to add a "new" No.70 thermistor.

I left the final decision on this PR to the Marlin developers.

### CODE REVIEW

**Comment by AnHardt** [comment]
In principle we can add as much sensors as we want. But what happens when a hypotetical Hephestos 3 uses the same thermistor? Isn't there a part-number, a type, some name more characteristic to the part - not its use?

**Comment by ghost** [comment]
I think that it's the subject of the policy(rules?) of the Marlin development.
"official" repository does how far they support exclusive parts, 
or parts that those has unknown specifications, or parts that those aren't sold separately.

Marlin development team was allowed to commit b82d91e,
it also means that to allow a situation such as the following.

``` cpp
// 70 is the 100K thermistor found in the bq Hephestos 2
// 71 is the 100K? thermistor found in the bq Hephestos 3
// 72 is the unknown thermistor found in the 3dprinter foo
// 73 is the original thermistor found in the 3dprinter baa
.
.
.
```

If Marlin development team doesn't want a situation as described above,
I suggest that end-user can add their own thermistor table to `Configuration.h`, as the Repetier.
https://github.com/repetier/Repetier-Firmware/blob/master/src/ArduinoAVR/Repetier/Configuration.h

and, this is mock-up of Marlin edition.
https://github.com/esenapaj/Marlin/commit/d33a162688895b4c25bd7b01c64a611b2ef6c577

**Comment by thinkyhead** [comment]
> suggest that end-user can add their own thermistor table

**Custom Thermistor Table** is definitely on the list of things-to-do. I think it would be nice (or scary) to split up `thermistortables.h` into several files as part of that process. Then there would be a `thermistor_custom.h` file which can be included when the user generates their own table.

**Comment by jbrazio** [comment]
I tried to find the exact part number on the BOM but it's not specified, I'll contact support.

Nevertheless the thermistor table description provided by bq didn't match any existing thermistor table entry.

**Comment by thinkyhead** [comment]
"When the part number we have, apply the change to the files we shall." —Yoda

**Pull request merged**
