### PR TITLE
Fix extruder dryrun v2

### PR DESCRIPTION
**Pull request by MagoKimbra**

### CODE REVIEW

**Comment by Wackerbarth** [comment]
(1) You have based your commit on "dev", but requested that it be applied to "Development".
That causes the artifacts in the displayed diff. All of your changes are in the last commit. (Rebasing to "Development" will make it cleaner)

(2) Looking at your proposed change, I don't understand what you are attempting to accomplish. -- 
"Fix extruder dry run" gives no hint as to what you think to be broken. Please provide a description of the change in action.

**Comment by boelle** [comment]
when he does a debug print it moves the extruder, he wants it not to do so

**Comment by boelle** [comment]
https://github.com/MarlinFirmware/Marlin/pull/2242

might give some hints....

**Comment by MagoKimbra** [comment]
Sorry for the mess that I've done, but I really can not use github as it should ...
I had already made the change to DryRun, but also the extruder moved. I was asked that during DryRun the extruder must be stopped because it is possible that there is still the filament. I had already made the change but I can not update my fork to the latest release to make the change and every time I combine chaos ... Sorry....

**Comment by boelle** [comment]
np... you have not made any changes to anything on marlin yet

we have to hit merge first

**Comment by thinkyhead** [comment]
> I had already made the change but I can not update my fork to the latest release to make the change and every time I combine chaos

@MagoKimbra The Development branch was recently scrubbed to remove a lot of old commits that you probably still have in your fork, so you will need to move your working copy's Development branch to point to the new Development HEAD and start from there to make your new feature branch. When you push your updated Development branch to remote it should fix up that branch of your github-hosted fork too.

The commands I used to do this were:

```
git checkout Development
git remote update
git reset --hard upstream/Development --
```

**Comment by thinkyhead** [comment]
@MagoKimbra We're closing this since #2358 fixes the main issue. Are the other changes important? There's overlap with commits that do some of the same things.

**Pull request closed without merging**
