### PR TITLE
update example configurations

### PR DESCRIPTION
**Pull request by ghost**
update old comments
update or delete deprecated definitions
complement forgotten updates
adjust spacing
some cosmetic changes

### CODE REVIEW

**Comment by ghost** [comment]
sorry, unnecesary pull-requests stuck on this PR.
but I don't understand how to purge those.

**Comment by thinkyhead** [comment]
Are you able to do the following…?

```
git fetch upstream
git checkout RCBugFix
git merge upstream/RCBugFix
git checkout esenapaj-patch-1
git rebase RCBugFix
git push -f
```

Or, without updating your RCBugFix:

```
git fetch upstream
git checkout esenapaj-patch-1
git rebase upstream/RCBugFix
git push -f
```

I should still be able to merge this, but it's always better starting with a minimum set of commits.

**Comment by ghost** [comment]
Thank you for telling me about that how to do, I'm going to challenge now.

**Comment by ghost** [comment]
I apologize again, It doesn't seem likely that I'll be able to solve.
Therefore, I've just repost PR with sub-account. (https://github.com/MarlinFirmware/Marlin/pull/3105)

**Pull request closed without merging**
