### PR TITLE
Configuration.h - reword Z PROBE section

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
1) Rewording of the section on pins for the Z probe.  Hopefully this is
less confusing.

2) The servo probe information was consolidated into one section.

3) Addede a warning about the minimum feedrate needed for Marlin to
reliably detect the 5mS pulse from a BLTouch

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
This PR is ready for review.

**Comment by Bob-the-Kuhn** [comment]
Probably should hold off on this until PR #5729 is voted up or down.

PR #5729 eliminates the need for a warning about a minimum feedrate.

**Comment by thinkyhead** [comment]
It's generally a good addition. I'll look at it more closely, do a little cleanup, apply it to the example configs, and so on, over the next few days.

**Comment by Roxy-3D** [comment]
I might be misunderstanding the detailed error log.   But it almost looks like Travis is running a test for Deltas with UBL turned on.   (Or at least the G26 Mesh Editing.)     Right now...  I haven't actually tried UBL on a Delta.  But I would be very surprised if it worked.    

But maybe...  That <<<<<<<HEAD marker is from an unresolved Git conflict?

----------------------------------------------------------------------------
```
The command "build_marlin" exited with 0.
0.01s$ use_example_configs delta/kossel_mini
The command "use_example_configs delta/kossel_mini" exited with 0.
5.12s$ build_marlin
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Xlib:  extension "RANDR" missing on display ":1.0".
Initializing packages...
Preparing boards...
Verifying...
In file included from sketch/MarlinConfig.h:30:0,
                 from sketch/G26_Mesh_Validation_Tool.cpp:27:
Configuration.h:594: error: expected unqualified-id before '<<' token
 <<<<<<< HEAD
```

**Comment by Bob-the-Kuhn** [comment]
I don't see UBL being tested with a delta in the Travis log now that I have the problems cleaned up,

**Pull request merged**
