### PR TITLE
Optional edit steps per unit

### PR DESCRIPTION
**Pull request by plampix**
### Description
Allows disabling M92 and related menus. Saves about 1900 bytes of flash in total

### Requirements
Enable NO_EDIT_STEPS_PER_UNIT in Configuration.h

### Benefits
Less flash usage, though you lose the ability to tune steps per unit.

### CODE REVIEW

**Comment by ellensp** [comment]
you're missing platformio source filitering.. 
and src/gcode/config/M92.cpp needs to wrapped in if DISABLED(NO_EDIT_STEPS_PER_UNIT) block or Arduino ide will still compile M92.cpp

**Comment by plampix** [comment]
Disabling EDITABLE_STEPS_PER_UNIT will now result in an EEPROM Corrupt message on every bootup.

**Comment by thisiskeithb** [comment]
> Disabling EDITABLE_STEPS_PER_UNIT will now result in an EEPROM Corrupt message on every bootup.

@plampix Please create an issue so it can be tracked, or submit a follow up PR with a fix.

We could also revert the change until more testing is done.

**Comment by ellensp** [comment]
no need, I've added a pr to fix it.

**Pull request merged**
