### PR TITLE
[2.0.x] Add RESTORE_LEVELING_AFTER_G28 option

### PR DESCRIPTION
**Pull request by thinkyhead**
In response to #8670, cohort to #9774

Some would obviously like to leave bed leveling on after `G28` if it was on before `G28`. Others, like myself, very much prefer that `G28` leave the machine at 0, 0 with leveling off. This PR makes it an optional behavior for all.

If a host wants to know what's up, it can send `M420` to find out after a `G28`.

For the benefit of UBL users, a warning is given if this option is off when UBL is on.

### CODE REVIEW

**Comment by GMagician** [comment]
@thinkyhead sorry for OT, just a question to better understand.
What are benefits to turn off UBL after G28? and what are the ones keep it on?
In my short point of view if I need bed level I'll have to keep always on (ok not when g29)

Proposal: Why not to force the 'RESTORE_LEVELING_AFTER_G28' to be true or false (by default is commented) and sanity raise error when undefined?
This way people are aware of different firmware behaviour but don't need to have a different sanitycheck.h

**Comment by thinkyhead** [comment]
The benefit of leaving leveling disabled after `G28` is that it adheres to the historic specification of `G28`, which is to put the machine into its native mode. The option was added to make it clear that it is an exception to that standard to leave it on.

**Comment by GMagician** [comment]
ok but why force edit in sanity check and not force option to be true or false and trigger error when undefined? this way, leaving undefined in configuration.h, requires no custom sanity

**Comment by thinkyhead** [comment]
It's a courtesy and a compromise for UBL users who have become inured to the previous behavior.

**Comment by GMagician** [comment]
sorry to continue bother you, but why not to write in sanity:
```cpp
#elif !defined(RESTORE_LEVELING_AFTER_G28)
  #error "AUTO_BED_LEVELING_UBL (<=1.1.8) always has RESTORE_LEVELING_AFTER_G28 enable. To keep this behavior, #define RESTORE_LEVELING_AFTER_G28 true. To keep it disabled #define RESTORE_LEVELING_AFTER_G28 false.
```
and adjust code if needed to check for `#If defined(RESTORE_LEVELING_AFTER_G28) && RESTORE_LEVELING_AFTER_G28`

so you are sure user is conscious of firmware behaviour and not force him to modify sanity.h but only configuration as everyone already does

**Pull request merged**
