### PR TITLE
Update to serial.h/compat.h

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description
- Other than updating spacing...

Primary changes:  
1. **compat.h**
- Rearrange to be more like **macros.h**
- Remove duplicate code

- Clearly there must be a typo here:
```diff
-#define _SELP_3(s,v,V...)         _SEP_2(s,v); DEFER2(_SELP_N_REF)()(TWO_ARGS(V),V);
+#define _SELP_3(s,v,V...)        _SELP_2(s,v); DEFER2(_SELP_N_REF)()(TWO_ARGS(V),V);
```

and here, are `{ }` needed??
```diff
-#define _SELP_3_P(p,v,V...)       { _SEP_2_P(p,v); DEFER2(_SELP_N_P_REF)()(TWO_ARGS(V),V); }
+#define _SELP_3_P(p,v,V...)       _SEP_2_P(p,v); DEFER2(_SELP_N_P_REF)()(TWO_ARGS(V),V);
```
<br>

2. **serial.h**
- Same kind of changes to `SERIAL...`/`_SEP_`

### CODE REVIEW

**Comment by ellensp** [comment]
Please stop wasting your time and ours editing spaces.
Your just burying real fixes in copious amounts of unrelated dross.

**Comment by p3p** [comment]
> Clearly there must be a typo here:

The macro works as intended, only adding a newline after the sequence of pairs, not after each pair.
example usage:
`SERIAL_ECHOLNPGM("c_z0:", planner.get_axis_position_mm(Z_AXIS), "-", pos_zero_offset);`

> and here, are { } needed??

not needed in this case, but putting macros that expand into multiple calls in their own scope is not detrimental, and often good practice

@classicrocker883 please don't modify functionality based on assumptions, and especially don't add those changes to a cosmetic  PR.

**Comment by thisiskeithb** [comment]
@classicrocker883 We've asked you several times to stop mixing in unrelated changes to your PRs.

Please focus your efforts on the [confirmed bug list](https://github.com/MarlinFirmware/Marlin/issues?q=is%3Aopen+is%3Aissue+label%3A%22Bug%3A+Confirmed+%21%22) instead of trying to boost commit counts with cosmetic changes.

**Comment by classicrocker883** [comment]
> @classicrocker883 We've asked you several times to stop mixing in unrelated changes to your PRs.
> 
> Please focus your efforts on the [confirmed bug list](https://github.com/MarlinFirmware/Marlin/issues?q=is%3Aopen+is%3Aissue+label%3A%22Bug%3A+Confirmed+%21%22) instead of trying to boost commit counts with cosmetic changes.

if its the same file its not unrelated bud

**Comment by classicrocker883** [comment]
@thisiskeithb maybe if you paid me i would. and also whats the matter with increasing commit counts, who cares, you can count

**Comment by classicrocker883** [comment]
@p3p 

whats the point of defining `_SELP_2_P` or `_SEP_1_P`, or any of the other ones then? its not being used otherwise, only defined

**Comment by p3p** [comment]
> if its the same file its not unrelated bud

Either the attempted bug fix, or the formatting changes are unrelated, pick one, the point is not hiding functional changes with cosmetic ones, being in the same file does not make any modification related. 

> @thisiskeithb maybe if you paid me i would. and also whats the matter with increasing commit counts, who cares, you can count

Sounds like you think that wasting reviewers time with frivolous PRs is fine as long as you can increase your commit count, That would probably get you banned from further commits on most projects.

> whats the point of defining _SELP_2_P or _SEP_1_P, or any of the other ones then? its not being used otherwise, only defined

Perhaps if you paid me I would tutor you in the C preprocessor.

**Pull request closed without merging**
