### PR TITLE
Fix build for GTR and SKR PRO with usb flash drive support

### LINKED ISSUE #20750: [BUG] BIGTREE_GTR_V1_0_usb_flash_drive fails with "no match MCU defined"
GTR_v1.0
Latest 2.0.x bugfix
default_envs = BIGTREE_GTR_V1_0_usb_flash_drive
Can not compile the code.
I get this error: #error "no match MCU defined" (any many more pin map error e.g.:error: 'PB12' undeclared here (not in a function); did you mean 'PB_12'?)
When i set back to: default_envs = BIGTREE_GTR_V1_0
Then compiles well.

[Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/5798454/Marlin.zip)

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

Fix missing flags. Fix #20750

### CODE REVIEW

**Comment by gaby64** [comment]
tested with your pr, im getting this error:

`In file included from Marlin/src/HAL/STM32/HAL.h:27,
                 from Marlin/src/HAL/STM32/HAL.cpp:25:
Marlin/src/HAL/STM32/HAL.h:63:23: error: 'MSerial' was not declared in this scope; did you mean 'MSerial9'?
   63 |     #define MYSERIAL1 MSerial`

**Comment by rhapsodyv** [comment]
To use gtr with a usb flash drive, you need to move the usb jumper and not use -1 as serial in marlin, as the usb serial will not be available when using usb flash drive.

You should set it to 1, 2 or 3. I don't know the right value. You need to take a look in the gtr specs. But -1 will not be available.

**Comment by gaby64** [comment]
so this is unusable on my SKR Pro 1.2 with a BTT TFT70, I just wanted usb drive support for the motherboard.

**Comment by rhapsodyv** [comment]
> so this is unusable on my SKR Pro 1.2 with a BTT TFT70, I just wanted usb drive support for the motherboard.

I don’t have this board. But I know that you will lose the usb to computer when using usb flash drive.

but I don’t think it will stop working the tft... 

We need to take a look in the board specs to see what are the serial port available.

**Comment by rhapsodyv** [comment]
When using usb flash drive, I think you will only lose the usb connect with host/computer. The serial for the tft will not change, it will be serial 1 yet.
You just lose the serial -1.

@thisiskeithb right?

**Comment by thisiskeithb** [comment]
> @thisiskeithb right?

Sounds right, but I didn't have a TFT hooked up when I was testing it.

**Comment by gaby64** [comment]
you are right, I had changed to something other then 1 for the first serial.

**Comment by ghost** [comment]
kép
Freshly donwloaded and builded.. :(

**Comment by ghost** [comment]
Now it's works with this setting:
```cpp
/**
 * Select the serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Serial port -1 is the USB emulated serial port, if available.
 * Note: The first serial port (-1 or 0) will always be used by the Arduino bootloader.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT 1
```
```ini
#
# Bigtreetech GTR V1.0 (STM32F407IGT6 ARM Cortex-M4) with USB Flash Drive Support
#
[env:BIGTREE_GTR_V1_0_usb_flash_drive]
platform          = ${common_stm32.platform}
extends           = common_stm32
board             = BigTree_GTR_v1
extra_scripts     = ${common.extra_scripts}
  pre:buildroot/share/PlatformIO/scripts/generic_create_variant.py
platform_packages = ${stm32_flash_drive.platform_packages}
build_flags       = ${common_stm32.build_flags}
  -DSTM32F407IX -DVECT_TAB_OFFSET=0x8000
```

**Comment by rhapsodyv** [comment]
My branch didn't work for you?? I didn't understand you.

**Comment by ghost** [comment]
After all settings implemented in Config file:
kép

**Comment by ghost** [comment]
> 
> 
> My branch didn't work for you?? I didn't understand you.

No. Not work. :(

**Comment by ghost** [comment]
When i turn off the sdsupport then compiled without error:
kép

**Comment by rhapsodyv** [comment]
I think you aren't using my branch. I just compiled it without any error or warning. Configs:
```cpp
#define SERIAL_PORT 3
#define MOTHERBOARD BOARD_BTT_GTR_V1_0
#define SDSUPPORT
#define USB_FLASH_DRIVE_SUPPORT
#define USE_OTG_USB_HOST
```

**Comment by rhapsodyv** [comment]
I just added a test in the Marlin CI to build GTR + OTG USB, just to make sure it's working... and the test just finished with success...

**Comment by margaale** [comment]
Yep, i can confirm it's working fine. I was having a problem where the status message was saying "USB start failed", however i had USE_OTG_USB_HOST commented out. Thanks to your test i was able to find that out.

**Comment by ghost** [comment]
[config.zip](https://github.com/MarlinFirmware/Marlin/files/6051566/config.zip)

**Comment by rhapsodyv** [comment]
> config.zip

You need to enable the configs:
```
#define SERIAL_PORT 3
#define MOTHERBOARD BOARD_BTT_GTR_V1_0
#define SDSUPPORT
#define USB_FLASH_DRIVE_SUPPORT
#define USE_OTG_USB_HOST
```
And use this branch, not bugfix.

**Comment by ghost** [comment]
> 
> 
> I think you aren't using my branch. I just compiled it without any error or warning. Configs:
> 
> ```c++
> #define SERIAL_PORT 3
> #define MOTHERBOARD BOARD_BTT_GTR_V1_0
> #define SDSUPPORT
> #define USB_FLASH_DRIVE_SUPPORT
> #define USE_OTG_USB_HOST
> ```

ok then I try it again.

**Comment by ghost** [comment]
Thank you! It's alive! :D

**Comment by ghost** [comment]
Yes i konw... I  open another error ticket. But it is driven by curiosity.
There is still a bug still.
Even though I turn the probe offset in the plus or minus direction, the bed always moves in only one direction (it keeps moving away).

**Pull request merged**
