### PR TITLE
Fixes PR #18071 TFT_LITTLE_VGL_UI broken compilation

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

PR #18071 doesn't compile when defined TFT_LITTLE_VGL_UI.

This PR fixes all compilation erros. Note: I don't have the hardware to test.

### Related Issues

#18071 
#18401

### CODE REVIEW

**Comment by rhapsodyv** [comment]
@thisiskeithb Can you test it?

**Comment by thinkyhead** [comment]
Thanks for this. Unfortunately @makerbase-mks is too busy to do testing and patches at this time.

**Comment by thisiskeithb** [comment]
> @thisiskeithb Can you test it?

It compiles, but I just get a blank screen after flashing. I'm still waiting to hear back from MKS/Makerbase as well since there's obviously something broken with their LVGL implementation.

**Comment by rhapsodyv** [comment]
> > @thisiskeithb Can you test it?
> 
> It compiles, but I just get a blank screen after flashing. I'm still waiting to hear back from MKS/Makerbase as well since there's obviously something broken with their LVGL implementation.

Did you put the mks_pic and mks_font in the SD root?

From here: https://github.com/makerbase-mks/MKS-Robin-Nano/tree/master/hardware

**Comment by thisiskeithb** [comment]
> Did you put the mks_pic and mks_font in the SD root?
> 
> From here: https://github.com/makerbase-mks/MKS-Robin-Nano/tree/master/hardware

I tried both[ v1.x.x](https://github.com/makerbase-mks/MKS-Robin-Nano/tree/master/Nano%20firmware%20v1.x.x) and [v2.x.x](https://github.com/makerbase-mks/MKS-Robin-Nano/tree/master/Nano%20firmware%20v2.x.x) releases, but the TFT is still blank on boot/the main view. If I touch around the TFT, it displays the same few (incorrect) icons in spots where icons should be, so something is still wonky.

Using MKS's precompiled firmware works and the TFT UI looks fine.

I've seen this on BigTreeTech TFTs when mixing and matching incorrect icons with different firmware releases, but I'm not sure where the correct icons should be downloaded from since the ones in MKS' repo do not work with the binary Marlin spits out.

Edit: I wonder if there's a way we can include those `mks_pic` and `mks_font` folders so users don't have to download them from another repo. An explainer should be added to `Configuration.h` with directions on where to download icons & fonts at the very least because I'm sure we'll hear about it in the issue queue once it works correctly.

**Comment by rhapsodyv** [comment]
The code is very very broken. I could get it working in my tft after much much debugging and tracing.
Things I discovered:
- there’s a bug in the sd reading bin files that stop and don’t read anything 
- I couldn’t get the SPI_GRAPHIC_TFT to work (because my tft I think), but the fsmc mode that this code have is very broken. It’s even try use dma without initiating it...
- the code has references for bin files that don’t match any file in the mks_pic folder (bmp_Motor_off.bin, bmp_Print.bin, etc)
- a lot of files have case problem 
- the touch in the fsmc mode is broken too (spi mode I can’t test)
- The flash spi have a weird bug that it overwrite it self. Maybe is my spi flash that don’t match the mks model, but the code is very weird. I didn’t find the cause yet.

**Comment by rhapsodyv** [comment]
IMG_9327
IMG_9326

**Comment by rhapsodyv** [comment]
The good thing, is that now I know very well how this code and lvgl works :-)

**Comment by rhapsodyv** [comment]
@thinkyhead  do you think worth take the “working part” of this code and create a separated and independent full lvgl version for marlin?

**Comment by rhapsodyv** [comment]
- [x] LCD
- [x] Touch
- [x] SPI Flash
- [x] Icons
- [x] Fonts
- [ ] Check every screen... 
- [ ] Themes, Colors, etc
- [ ] Speed? (now is very low because the serial debugging.. but I think can be improved)

Working with 2MB SPI Flash in my Tronxy X5SA, stock/original 480x320 TFT.


ezgif-4-0cd88291cd07

**Comment by rhapsodyv** [comment]
@thinkyhead 
I can send a PR of this new UI. The goal will be: keep it simple, default and small so more users and displays could use.

The question now is, which path follow:

1) Create a copy of the code, to change it as we wish and need.

Pro -> It Keeps the MSK code untouched, so they continue to be the maintainer and don't mess up with their things. 
Cons -> a few routines will be duplicated, at least until we change them

2) Change the original MKS code 

Pro -> no code duplication
Cons -> It will change the MKS code in a way that they may not send more PRs to it because it may be incompatible with their current codebase....  I think the code will change a lot to keep it more generic and flexible (as I already did).

**Comment by thinkyhead** [comment]
> they may not send more PRs to it

If someone wants to help them stay up to date, they could submit a PR to the MKS fork with the changes.

**Comment by rhapsodyv** [comment]
> > they may not send more PRs to it
> 
> If someone wants to help them stay up to date, they could submit a PR to the MKS fork with the changes.

I'm really confident the PR they sent is a way way outdated with their current "real" codebase. 

But, we can try reach them... It'll be good for everyone.

**Comment by thisiskeithb** [comment]
> But, we can try reach them... It'll be good for everyone.

I have direct contact with MKS, but they are on holiday right now for the Dragon Boat Festival, so it'll be a few days at the earliest before I hear back.

**Comment by rhapsodyv** [comment]
> > But, we can try reach them... It'll be good for everyone.
> 
> I have direct contact with MKS, but they are on holiday right now for the Dragon Boat Festival, so it'll be a few days at the earliest before I hear back.

Ok. Let's wait.

I think I finished almost everything, but gcode preview. I will test new in the printer now. And prepare a PR.

IMG_9336

**Comment by thisiskeithb** [comment]
Thanks for debugging this! I'll be able to test this on a real Robin Nano/TFT35 combo later today or tomorrow if you want to send me a link to your branch.

**Comment by makerbase-mks** [comment]
Now the location of some files has changed, some header file paths have not been changed, I will modify and test it, and then submit to the marlin team for review.

**Comment by thinkyhead** [comment]
Thanks @makerbase-mks. I look forward to your patch!

**Pull request merged**
