### PR TITLE
Malyan M300 support

### PR DESCRIPTION
**Pull request by thinkyhead**
Recreating #17403 here for further testing and development, because the original was out of sync with a rebased HEAD.

### CODE REVIEW

**Comment by mojocorp** [comment]
@thinkyhead I've updated my pull request to include the autobuild and the build test passed.
Note that the last commit activate the autobuild but I don't think it's a good idea to merge it since the M300 has only 123K free flash and this limit could be randmly exeeded if the default delta config change.

**Comment by thinkyhead** [comment]
> this limit could be randmly exeeded

The build (or upload) system should be able to catch the overflow before attempting to actually upload. Let's explore that capability and see if it provides a safety barrier.

**Comment by mojocorp** [comment]
If the final firmware size exceed 122k the build fail and its perfectly normal for this machine. That was my only remark. There is nothing to explore there, everything work as expected.

**Comment by thinkyhead** [comment]
The Malyan M300 configuration over at https://github.com/MarlinFirmware/Configurations has leveling enabled but it doesn't have a probe enabled so it doesn't pass testing.

**Pull request merged**
