### PR TITLE
Update PROBE OFFSET FROM EXTRUDER comment section

### PR DESCRIPTION
**Pull request by jbrazio**
Apply the changes discussed at MarlinFirmware/Marlin#2849

### CODE REVIEW

**Comment by thinkyhead** [comment]
You'll have to apply the same change to every configuration file before this can be merged.

**Comment by jbrazio** [comment]
No worries, I'll also change comment style to // in order to comply with all the other comment sections.

**Comment by lrpirlet** [comment]
Well, @jbrazio Yes to mark x > X is to indicate the direction X "grows"... I did propose that a long way back, the idea is that, if you center the origin in the middle of the bed (delta), it indicates how to read the diagram...
The diagram can then set and read with some clear direction (a little like a map where the North is allways pointing to the top).
@thinkyhead @Roxy-3DPrintBoard  So, my printer has the origin in the back and the right of the bed... So I just need to turn the map 180 degrees before taking any conclusion about the topology...

**Comment by jbrazio** [comment]
How about this ?

```
  // Z Probe to nozzle (X,Y) offset, relative to (0, 0).
  // X and Y offsets must be integers.
  //
  // In the following example the X and Y offsets are both positive:
  // #define X_PROBE_OFFSET_FROM_EXTRUDER 10
  // #define Y_PROBE_OFFSET_FROM_EXTRUDER 10
  //
  //   +--- BACK --+
  // L |           | R
  // E |    (+) P  | I <-- probe (20,20)
  // F |           | G
  // T | (-) N (+) | H <-- nozzle (10,10)
  //   |           | T
  // ^ |    (-)    |
  // + |           |
  // Y O-- FRONT --+
  // (0,0) X+>
```

Or this ?

```
  // Z Probe to nozzle (X,Y) offset, relative to (0, 0).
  // X and Y offsets must be integers.
  //
  // In the following example the X and Y offsets are both positive:
  // #define X_PROBE_OFFSET_FROM_EXTRUDER 10
  // #define Y_PROBE_OFFSET_FROM_EXTRUDER 10
  //
  //            (++,++)
  //   +--- BACK --+
  // L |           | R
  // E |    (+) P  | I <-- probe (20,20)
  // F |           | G
  // T | (-) N (+) | H <-- nozzle (10,10)
  //   |           | T
  //   |    (-)    |
  //   |           |
  //   O-- FRONT --+
  // (0,0)
```

**Pull request merged**
