### PR TITLE
sidewinder x1 + hemera + skr v1.4 + tmc2209 + bltouch

### PR DESCRIPTION
**Pull request by pmccut**
- Sidewinder X1 V4
- Hemera using the thermistor included w/ Hemera
- SKR v1.4
- TMC2209s x5, Z2 using E1 slot. Not using the dual-z splitter port on skr 1.4
- BLTocuh w/ waggster mod using RGB pins, 3-pin harness connected to SERVO0 header (swap pins 1/3 in JST VH)
- BLTouch min-endstop signal on Z-min
- Using sensorless homing for X/Y min
- Stock TFT works (swapped the 2-row header for a single row dupont into TFT port on SKR)
- LCD12864 also working

### CODE REVIEW

**Comment by pmccut** [comment]
wrong repo, sorry

**Comment by mhannis** [comment]
where did you mean to post this? I have the same setup looking for a guide if you happen to have one.

**Comment by bitfabrikken** [comment]
@pmccut I realize this is quite old, just wanted to inform you that you haven't set microsteps from 16 to 256 on the steppers, and the current, especially for hemera e0 is rather high. 1100 * 1.414 = 1.56a, it's rated for 1.33a

**Comment by svdb99** [comment]
@pmccut Where did you connect the 2 red+black wires from the stock TFT on the SKR? Thanks.

**Pull request closed without merging**
