### PR TITLE
Marlin 2.0 Geeetech A10D Config

### PR DESCRIPTION
**Pull request by Vertabreak**
Example Config for the A10D

### CODE REVIEW

**Comment by Vertabreak** [comment]
managed to add PI3A Pro Config also.

**Comment by Vertabreak** [comment]
there are several more im still working on.

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR. It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by Vertabreak** [comment]
sorry about the mix up XD.

**Pull request closed without merging**
