### PR TITLE
General cleanup before release

### PR DESCRIPTION
**Pull request by thinkyhead**
With some important bug fixes merged recently, seems like a good time to release 1.1.3.

### CODE REVIEW

**Comment by bgort** [comment]
1.1.3 ?

**Comment by thinkyhead** [comment]
Sorry, obviously I meant 7.2.4!

**Comment by bgort** [comment]
7.2.4 sounds good, too! ;)

**Comment by thinkyhead** [comment]
There's a system, trust me! Next is 3.4.🦃

**Comment by bgort** [comment]
Makes perfect sense to me!

**Comment by emartinez167** [comment]
Goble Goble Goble!

**Pull request merged**
