### PR TITLE
Add support for a motion deployed Z probe

### PR DESCRIPTION
**Pull request by Squid116**
### Requirements

Add support for a motion deployed Z probe

### Description

Add support for a Z Probe that uses the motion of the X Axis to deploy and retract the probe.  One example of this is the Rack and Pinion in the Wilson II designed by https://github.com/mjrice

https://www.youtube.com/watch?time_continue=6&v=GoCQFhDL5eE

### Benefits

There is a discussion of this probe here: https://reprapwilson.discoursehosting.net/t/a-new-way-to-probe-the-print-bed-bed-leveling/66

### CODE REVIEW

**Comment by ant0nyk1ng** [comment]
I have done some tests with Ramps 1.4 (8bit) and working so far.

**Comment by AnHardt** [comment]
Can we find a better name?
Allen key probes are also motion deployed.

**Comment by Squid116** [comment]
Open to suggestions - it was implemented by the original author as rack_and_pinion but I thought that was a bit specific.

**Comment by ant0nyk1ng** [comment]
Rack and Pinion is the best descriptive name that matches what I would expect it to be.

**Pull request merged**
