### PR TITLE
M76 Host Pause Feature

### PR DESCRIPTION
**Pull request by charlespick**
I couldn't find this feature in any existing gcode so I wrote it. Sorry if I am doing something horribly wrong as this is my first time contributing. 

### Description

Adds the optional ability to have Marlin send a pause action notification when M76 is run. 
### Requirements

Shouldn't require any specific marlin related hardware

### Benefits

This allows you to configure your filament runout script to pause the host without the use of M600. This is great for headless printers where you want to manage the filament change process from the host instead of marlin. It also allows you to initiate a pause from one host when printing from another host (eg. a TFT display and OctoPrint). 
### Configurations

Tested on a CR10 V3 with BTT SKR Mini E3 V2 and OctoPrint
[configs.zip](https://github.com/MarlinFirmware/Marlin/files/6396246/configs.zip)

### Related Issues

None that I could find

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Why do we need to make `HOST_PAUSE_M76` unique when there’s already `HOST_PROMPT_SUPPORT`?

This can easily head down a path of adding individual actions when they should all be covered under `HOST_PROMPT_SUPPORT`.

**Comment by charlespick** [comment]
How would you configure the filament runout script to do the same thing but using host_prompt_support?

**Comment by InsanityAutomation** [comment]
From the configuration section of the runout action - // NOTE: After 'M412 H1' the host handles filament runout and this script does not apply. By default, this sends the host the filament_runout action command.

**Comment by charlespick** [comment]
Interesting, 

so then the only use cases remaining are preprogramming a point in a script to pause the print indefinitely and
pausing from another host

**Comment by InsanityAutomation** [comment]
I believe those are both handled by m0/1

**Comment by charlespick** [comment]
> I believe those are both handled by m0/1

From marlin gcode docs
> Without an LCD controller or EMERGENCY_PARSER this command is ignored.

**Comment by InsanityAutomation** [comment]
Correct, because without those, youll never be able to resume. They wait for a command to return control. 
It sounds more like you want to add an argument to M125 to simply pause without parking honestly.

**Comment by charlespick** [comment]
> youll never be able to resume

the whole idea here is to pause the host, so you would resume at the host

**Comment by thinkyhead** [comment]
I think the host should probably put up its own alert in this case, but the protocol is such that the firmware supplies the values for the buttons. So, this is not entirely weird. One thing is that an `M76` is only a "clue" that the host has paused or stopped printing. It's not an absolute guarantee. That said, it is unlikely to see `M76` outside of print pause or stop.

**Comment by thinkyhead** [comment]
In testing, does the host also put up the dialog when stopping a print, or does the host ignore it?

**Comment by charlespick** [comment]
I haven't tested with host prompt support on and I won't be able to for a few days. I'll get back to this on Wednesday 

I would imagine it would depend on the host in question as well so maybe I don't understand the question

**Comment by thinkyhead** [comment]
It appears to me that if you were to tell the host to "CANCEL PRINT" it would then respond with "Click to Resume."

**Comment by charlespick** [comment]
Why do you think that? I'm still confused 🤔

**Comment by charlespick** [comment]
@thinkyhead 
As far as I can tell, the way I've designed this only tells the host to pause when Marlin receives the M76 command, from a host, another host, or internally. There doesn't need to be any confirmation that it does stop printing since the host is handling sending commands.

**Comment by thinkyhead** [comment]
> I'll get back to this on Wednesday

Is this still good? Bad? In-between? It's ready to merge if it's still considered useful.

**Comment by charlespick** [comment]
Sadly I've switched to klipper on all my printers so I don't really have an opinion anymore. I wanted an Ultimaker or Makerbot experience and hacking octoprint and marlin together with host prompts and stuff just wasn't cutting it.

**Comment by thinkyhead** [comment]
Well, much gratitude for everything you've done so far to help us catch up with Klipper. We'll keep on keeping on improving things!

**Pull request merged**
