### PR TITLE
Draw only one graphical display segment per loop

### PR DESCRIPTION
**Pull request by thinkyhead**
This is a rebase / squash / cleanup of #4793

A note on the original commit says:
> Existing Bug: un-updated half screen

@yhfudev Is that a bug in this implementation, or an old bug?

### CODE REVIEW

**Comment by yhfudev** [comment]
@thinkyhead Yes, your patch works! It can update the screen without the half-screen problem.

**Comment by thinkyhead** [comment]
I think it's the combination of this plus the recent lcd-click patch that has it working better.

**Comment by thinkyhead** [comment]
@Sebastianv650 Do you find that this patch improves performance with `LIN_ADVANCE` – reduces or eliminates the planner buffer runout (stuttering) problem? It would be good to still be able to keep the screen updating and click events working rather than do a total block (#5204), if possible.

**Comment by yhfudev** [comment]
I tested it and found it would be better if the line is moved to the end of the block:

``` C++
    // after update the u8g, at the end of block:
    if (lcdDrawUpdate != LCDVIEW_U8G_CONTINUE)
      next_lcd_update_ms = ms + LCD_UPDATE_INTERVAL;
  }
}
```

otherwise the status screen may ``out of sync''.

**Comment by ghost** [comment]
I also confirmed that half-screen problem doesn't exists.
But, flickering exists on third line at scrolling a menu.
I think that it hasn't actual harm, but it's flickering.

**Comment by thinkyhead** [comment]
Flickering for just 1 update frame? Perhaps when responding to a click or encoder movement, we should force a full update instead of just the half update.

**Comment by thinkyhead** [comment]
As suggested, #5240 should make the "flicker" less noticeable and give a faster redraw overall.

**Comment by ghost** [comment]
It's like this.

Video clip:
[](https://www.youtube.com/watch?v=Kvf8W52LbvA)

**Comment by Sebastianv650** [comment]
The stuttering isn't specific to LIN_ADVANCE, the chance for it is increased with every additional feature that has to do extra calculations inside the planner or other things that increases the duration of the main loop.
I will do time measurements as soon as I have an hour of time!

**Comment by Sebastianv650** [comment]
This PR would work to reduce the LCD_UPDATE_THRESHOLD from my PR #5204 as the block buffer has only to survive approx. half as long without new blocks. But PR #5240 renders it useless again. If you update the second half of the LCD instantly during the next main loop, the buffer can be only filled up with max. 1 new block which is useless.

**Comment by thinkyhead** [comment]
> But PR #5240 renders it useless again

@Sebastianv650 Yeah, I figured as much. Back to the drawing board.

I'm thinking, we should strive to have the encoder and buttons responsive, but otherwise your concept of blocking screen updates isn't bad.

Too late in the game right now (and complicated) to re-write the drawing functions to be more "granular."

**Comment by thinkyhead** [comment]
I've hard-reverted this and its followup.
Sorry @yhfudev but the trade-off with this concept isn't well-loved.
We need some other "trick" to keep the planner fed.

**Comment by Sebastianv650** [comment]
> I'm thinking, we should strive to have the encoder and buttons responsive, but otherwise your concept of blocking screen updates isn't bad.

I agree, especialy as long as the user wasn't reading a warning that the buttons are not always responsible. That's why I added the `ALWAYS_ALLOW_MENU` option - if enabled the buttons are always responsive.

~~I can think of another compromise:
Use the update one page of the display only, as it's the best we have at the moment.
To prevent flickering, we have to draw the next page as soon as possible - but not too early so that the buffer can fill up again. So we could set next_lcd_update_ms to a small value that should allow a buffer refresh. Adding a block takes about 5ms, say 6ms to have some safety (only valid for cartesian, maybe delta and others take longer!). Then next_lcd_update_ms could be "ms + 6 \* block_buffer_size".
This should be short enough to keep the flickering at the amount as with #5240.~~

Edit: Sometimes calculating before writing would be better. 6*16 = 96ms, which is the same as without the reduce-flicker PR. So this idea is useless..

**Comment by thinkyhead** [comment]
@Sebastianv650 Is this problem more pronounced in kinematic situations (delta) versus cases where there are just a lot of short GCode segments? If so, we could simply make sure in the kinematic functions to wait till the planner buffer is full before calling `idle()`.

Also, it occurs to me that we could also take the approach of making sure that the planner is fully fed before returning from _any_ functions that add segments to the planner….

Pseudo-code:

```
  while (!planner.is_full() && !command_is_blocking() && command_available())
    process_next_command(no_idle);
```

**Comment by thinkyhead** [comment]
Hmm… Reviewing `prepare_kinematic_move_to`, I see that it already does that, essentially. It simply calls `planner.buffer_line_kinematic` repeatedly with no `idle` calls, and then `idle` only gets called in `planner_buffer_line` when the buffer is too full to add another segment.

However, I see that `plan_arc` does extra calls to `idle` every so often, even though it would also end up calling `idle` anyways due to the behavior of `planner._buffer_line`. I'll bet that removing the following call to `idle` / `manage_heater` in `plan_arc` would be fine. I don't think it's really needed there.

``` cpp
thermalManager.manage_heater();
if (ELAPSED(millis(), next_idle_ms)) {
  next_idle_ms = millis() + 200UL;
  idle();
}
```

Of course, the call to `idle` in `plan_arc` would only harm performance noticeably in the case where calls to `planner._buffer_line` _don't_ invoke the screen update, but the call to `idle` within `plan_arc` _does_ invoke the screen update (and the planner is almost empty).

**Comment by Sebastianv650** [comment]
I have absolutely no feeling how much the planner (add new block) will be slower with CORE or delta machines. As far as I know they need some extra math, but not very much so the runtime of about 5ms shouldn't be changed a lot? I _think_ it will not be very much influenced by other features enabled.

I was also thinking about something like your code, only call idle when the block buffer is full. But as also the heater is managed there, I was afraid a printer might end up with nearly no heater management when printing something with only short segments.

The problem is also only related to the LCD update, every other method called in idle() is nearly using no time.

Also don't forget that even if we never call `idle()`, it takes 5ms to add a new block. That means, if we print circles at a specific speed so that each segment is below 5ms, the buffer will always contain 0 (waiting) or 1 block and the printer will not move smooth. And 5ms isn't very low: Thats's a segment length of 0.2mm at only 40mm/s..

**Comment by thinkyhead** [comment]
Wow, 5ms? That's 80,000 CPU cycles. It sure seems like a lot of cycles just to do a planner block, doesn't it?

**Comment by Sebastianv650** [comment]
Ok I should mention the 5ms also includes all isr breaks. I needed real in print numbers for ensure smooth print pr.

**Pull request merged**
