### PR TITLE
Add Sovol v1.3.1 Mainboard to Marlin (used in Sovol SV06)

### PR DESCRIPTION
**Pull request by hillsoftware**
### Description

Add Sovol v1.3.1 mainboard to Marlin. This board is used in the Sovol SV06 printer currently. The board uses a GD32F103RET6 clone processor with 512K of Flash memory, and 64K of RAM.

### Requirements

This PR requires the Sovol v1.3.1 mainboard and the generic CR-10 LCD Knob display that the printer uses.

### Benefits

This PR allows future users to build Marlin easily for the Sovol mainboard.

### Configurations

SV06 configuration files attached in zip. Will be submitting them to the proper repo also.

### Related Issues

No related issues that I know of.

[configs.zip](https://github.com/MarlinFirmware/Marlin/files/10475293/configs.zip)

### CODE REVIEW

**Comment by ellensp** [comment]
GD32F103RET6 is not a clone of the STM32F103RET6, is has many deliberate differences. treating it like a stm32 is very problematic, and causes lots of issues.

**Comment by ellensp** [comment]
The board is also a clone of a creality v4 Marlin/src/pins/stm32f1/pins_CREALITY_V4.h with the addition of tmc uarts pins

so all this boards pins file needs is to include the above pins file and have the HAS_TMC_UART block

**Comment by thisiskeithb** [comment]
> treating it like a stm32 is very problematic, and causes lots of issues.

Not to mention possible license issues with USB code from ST. There’s an open/ongoing GD32 feature request discussion with more info:

- https://github.com/MarlinFirmware/Marlin/discussions/24985

**Comment by thisiskeithb** [comment]
@thinkyhead: What are your thoughts on breaking out GD32 boards/pins to their own sections & folders? While they mostly work under STM32 / Maple, “they’re not clones”.

I think it’d help us keep track of them since I’m sure we’re about to open the floodgates for GD-based support.

edit: How about a GitHub label for GigaDevice as well?

**Comment by thinkyhead** [comment]
I'm considering it once we have more. There will likely be clones of STM32F1/4/7 in future. At the moment there is only one in the pile, which is meant to be "interoperable" with STM32F1. If they are all intended to be interoperable, and also built upon the standard platforms, then it may not make sense to split them up by chip vendor, especially if more vendors enter the arena of interoperable sort-of-clones.

**Comment by ellensp** [comment]
This is already being done in for eg https://github.com/MarlinFirmware/Marlin/pull/25405/files eg Marlin/src/pins/gd32f1/pins_TRIGORILLA_V006.h

As long as they include Marlin/src/pins/gd32f1/env_validate.h
which gives the warning and support the code

#ifndef PERMIT_GD32_BUILD
  #error "WARNING: GD32 based controllers are not officially supported by Marlin."
  #error "Define PERMIT_GD32_BUILD in Configuration.h to continue at your own risk."
#endif

**Comment by thisiskeithb** [comment]
> #error "WARNING: GD32 based controllers are not officially supported by Marlin."

By merging this PR, I would assume we do.

**Pull request merged**
