### PR TITLE
Restore ENDSTOPPULLUPS in Configuration.h

### PR DESCRIPTION
**Pull request by thinkyhead**

### CODE REVIEW

**Comment by alexborro** [comment]
Why ???

Actually I don't even see any reason one wanna disable a endstop pullup...

Cheers.

Alex.

2015-03-31 1:15 GMT-03:00 Scott Lahteine notifications@github.com:

> Merged #1749 https://github.com/MarlinFirmware/Marlin/pull/1749.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MarlinFirmware/Marlin/pull/1749#event-269169613.

## 

_"Não é o mais forte da espécie que sobrevive, nem o mais inteligente. É
aquele que se adapta melhor as mudanças"  ( Charles Darwin )_

Alex Borro

**Comment by nophead** [comment]
Yes the are so weak I can't imagine them causing a problem with boards that have external pull-ups. They will change the threshold of optos sightly though.

**Comment by alexborro** [comment]
That's the reason I removed that complication about endstops pullup.

Usually a regular uC have a +20K pullup resistor, that means 250nA on 5V.. I don't know any device with a higher output impedance than that.

As you said, even a opto can output some mA. There will be a marginal drift on trigger position that means nothing for our application, specially on endstops.

Cheers.

Alex.

**Comment by nophead** [comment]
250uA, not nA. It will have a slight effect on a simple opto that is a
photo transistor without a buffer. They typically have 10K pullups.

**Comment by thinkyhead** [comment]
This section was restored to `Configuration.h` purely for historical consistency and for consistency with all the `example_configuration` files, which still have these lines. (When editing the configurations, don't forget to edit all of them so your changes will be seen as intentional.)

`Conditionals.h` still sets pullups for all enabled endstops when `ENDSTOPPULLUPS` is set.

If these settings are actually superfluous, we can remove all endstoppullup references throughout the code and say farewell to this.

**Comment by alexborro** [comment]
I think we should let only the individual pullup settings on configuration_adv.h:

#define ENDSTOPPULLUP_XMAX
#define ENDSTOPPULLUP_YMAX
#define ENDSTOPPULLUP_ZMAX
#define ENDSTOPPULLUP_XMIN
#define ENDSTOPPULLUP_YMIN
#define ENDSTOPPULLUP_ZMIN

If someone, for any reason, need to disable one pullup, it can be done here.

Cheers.

Alex.

**Comment by thinkyhead** [comment]
I agree with moving these into the _adv file. I'll just check the example configurations and fix up any that depend on the old `ENDSTOPPULLUPS` option.

**Pull request merged**
