### PR TITLE
Add digital pin compatibility to STM32 set_pwm_duty

### PR DESCRIPTION
**Pull request by descipher**
### Description

Add the ability to set a pin high or low with set_pwm_duty rather than just returning to caller.
More in line with analogWrite.

### Requirements

STM32

### Benefits

Compatibility with existing Arduino calls.

### CODE REVIEW

**Comment by DerAndere1** [comment]
Woud it work to replace digitalWrite with the WRITE() macro and to replace pinMode with the SET_OUTPUT() macro from fastio.h? Would it be preferred?

**Comment by descipher** [comment]
> Woud it work to replace digitalWrite with the WRITE() macro and to replace pinMode with the SET_OUTPUT() macro from fastio.h? Would it be preferred?

It would work, but the point here is to maintain compatibility. The calls work very differently. So it would not be preferred in this case.

**Comment by descipher** [comment]
Retested Ok

**Comment by descipher** [comment]
Out of scope? Please create separate PR and we can test them there.

**Comment by descipher** [comment]
I will create a PR to do the distinguish Marlin HAL timer naming. Then we can test that in a different scope.

**Comment by descipher** [comment]
I am creating the PR for MF_names we can put it there to have scope, should be ready shortly.

**Comment by thinkyhead** [comment]
> Woud it work to replace digitalWrite with the WRITE() macro and to replace pinMode with the SET_OUTPUT() macro from fastio.h? Would it be preferred?

No. The macros are intended only for use with pin number constants or defines, and should not be used with variable pin numbers. Even though some platforms just pass straight through to `pinMode` and `digitalWrite` – and within the HAL it would end up functioning – it would defy the semantics of those macros.

**Comment by thinkyhead** [comment]
> I am creating the PR for MF_names we can put it there to have scope, should be ready shortly.

That might be moot, as it is not clear that `STEP_TIMER`, `TEMP_TIMER`, `PULSE_TIMER` are serving the same function as `MF_TIMER_STEP` (etc.). But, please give it a try and see if you can _resolve the build errors_ that appear in the CI tests and establish that they are essentially serving the same function (timer indexes or identifiers), and see whether the attempts at overrides make sense. Some HALs do abstract the `MF_TIMER_STEP` etc. indices to refer to object instances, not items in an array, but generally the semantic purpose is the same - to identify a timer by a unique timer number … which is internal to Marlin but I suppose it may be used as an index into a timer table that is external.

**Comment by descipher** [comment]
I see, we have a shell PR now so we can work on it collectively.

**Pull request merged**
