### PR TITLE
Patch till UBL is integrated with planner-based leveling

### PR DESCRIPTION
**Pull request by thinkyhead**
The `PLANNER_LEVELING` flag should indicate that the active bed leveling is fully integrated with the planner and the bed leveling related functions in `Marlin_main.cpp`. UBL isn't yet integrated into `Planner::apply_leveling` and `Planner::unapply_leveling` so for now add UBL as a counter-condition for those functions.

- Turn off planner-leveling when UBL is enabled
- Apply the logical / raw coordinate-space conversion macros where needed
- Use `const` where needed
- Make methods that don't use UBL data `static`

### CODE REVIEW

**Comment by Roxy-3D** [comment]
>  UBL isn't yet integrated into Planner::apply_leveling and Planner::unapply_leveling so for now add UBL as a counter-condition for those functions.

Are these the only two functions that need to be supplied to make it fully integrated?  If so...   I can get those functions added.

**Comment by thinkyhead** [comment]
The functions exist already. You just need to provide UBL leveling correction in the first, and un-correction in the second. Search the code for `PLANNER_LEVELING` for all the places where the planner handles aspects of leveling.

**Comment by thinkyhead** [comment]
Note also, in the function `set_bed_leveling_enabled` that you not only have to enable/disable bed leveling, but also correct the current position by _un-applying_ bed leveling to `current_position` on enable, or _applying_ bed leveling to `current_position` on disable. You also have to pre-check to make sure leveling _actually can be_ enabled before setting it as enabled.

On another note, at the top of `gcode_G28` there's already an appropriate place where bed leveling is disabled (based on the `PLANNER_LEVELING` flag), so I moved the UBL disable there.

As for `bed_leveling_state_at_entry` and re-enabling leveling after `G28`… The choice was made to not have `G28` enable bed leveling at the end, even if it was enabled before, because `G28` is specified to home and disable any enabled bed leveling. Bed leveling should be enabled with `M420 S1` after `G28` if there's an existing mesh or grid. So I would recommend removing `bed_leveling_state_at_entry`.

**Comment by thinkyhead** [comment]
Which code did you want to keep in `set_bed_leveling_enabled`?
```cpp
        ubl.state.active = enable;
```
…or…
```cpp
      if (ubl.state.eeprom_storage_slot == 0)  {
        ubl.state.active = enable;
        ubl.store_state();
      }
```
?

**Comment by thinkyhead** [comment]
Your `ubl_line_to_destination` function is currently incompatible with non-zero `home_offset` or `position_shift`. You need to do this, or your leveling will break after `M206` / `G92`.
```cpp
    cell_start_xi = ubl.get_cell_index_x(RAW_X_POSITION(x_start));
    cell_start_yi = ubl.get_cell_index_y(RAW_Y_POSITION(y_start));
    cell_dest_xi  = ubl.get_cell_index_x(RAW_X_POSITION(x_end));
    cell_dest_yi  = ubl.get_cell_index_y(RAW_Y_POSITION(y_end));
```

**Comment by thinkyhead** [comment]
```cpp
#ifndef ENABLE_LEVELING_FADE_HEIGHT
```
We're still using `ENABLED` / `DISABLED` for options like this.

**Comment by thinkyhead** [comment]
```cpp
#if PLANNER_LEVELING || ENABLED(AUTO_BED_LEVELING_UBL)
```
This can just be `PLANNER_LEVELING` for now because UBL is included. I want to have this flag eventually include UBL for real. For now, it will filter out UBL only at the planner level until UBL is calling  `ubl.get_z_correction(rawx, rawy)` in `apply_leveling` / `unapply_leveling`.

**Comment by thinkyhead** [comment]
>        // Note: There is no Z Correction in this case. We are off the grid and don't know what
>        // a reasonable correction would be.

Bilinear bed leveling is more careful here. Instead of dropping Z correction, it applies the Z from the nearest edge or corner. This ensures there's no sudden change in Z if X or Y go outside the probed grid area.

**Comment by thinkyhead** [comment]
I'm going through the `ubl_line_to_destination` function now to make it compatible with the moving coordinate space.

**Comment by thinkyhead** [comment]
The `fade_scaling_factor_for_z` function should return 1.0 when `ENABLE_LEVELING_FADE_HEIGHT` is not enabled or when the `g29_correction_fade_height` is zero, because in these cases we want leveling to be un-scaled, hence correction multiplied by 1.0.

**Comment by Roxy-3D** [comment]
I'll review in the morning...   But activating UBL should not require correction.   The very first move will send the nozzle to the correct height.  And from there...  It will track the mesh.

> Which code did you want to keep in set_bed_leveling_enabled?

```cpp
        ubl.state.active = enable;
```

While not 100% correct...  Please leave it like this.   This will work just fine until we get correct and uncorrect into the planner.   (Any movement...   Even a .1mm movement will send the nozzle to the correct height.)

But I'll review everything in the morning and figure out how to add the correction and uncorrection in the planner.

**Comment by thinkyhead** [comment]
> The very first move will send the nozzle to the correct height.

That's not how the core of Marlin works now. When you disable the bed leveling, the current position immediately updates to become whatever the physical position is. When you enable bed leveling, the current position immediately becomes the un-leveled physical position. All the hooks are in place. UBL just has to be integrated.

**Comment by Roxy-3D** [comment]
>>         ubl.state.active = enable;
> When you enable bed leveling, the current position becomes the un-leveled physical position. All the hooks are in place. UBL just has to be integrated.

Yes.  That is true.   But it is also true that G28 always used to leave the bed leveling in a disabled state.  That is not necessary and users don't like that.   UBL should be enabled automatically after a G28 if it was active at the start of the G28.   

What I'm saying is...   That simple 'activation' will work just fine until a more sophisticated correction and uncorrection routine is added to the planner.   Think about it this way...  The GCode to do a print only has 1 G28 in it and it will be right at the very front of the file.   After the G28 the slicer is going to send the nozzle to where ever the first part of the skirt gets drawn.    That line_to_destination() is going to do a bi-linear correction and the end point (before any filament is extruded) is going to have the nozzle at the correct height.

Everything works right now...  Let's just improve one thing at a time with out lots of chaos.

**Comment by thinkyhead** [comment]
> UBL should be enabled automatically after a G28 if it was active at the start of the G28.

That's a change to the specification of `G28`, which specifically homes and disables leveling.

**Comment by Roxy-3D** [comment]
> > UBL should be enabled automatically after a G28 if it was active at the start of the G28.

> That's a change to the specification of `G28`.

I would be willing to bet you can't find an ANSII or ISO specification that says G28 should always leave the bed leveling system disabled!!!

**Comment by thinkyhead** [comment]
It's a change to user expectation, de-facto standard, and the documentation at RepRap wiki. It might very well be a change to the specification as it applies to common use in CNC world.

**Comment by Roxy-3D** [comment]
Yes.   It is a GOOD change.   And the user has full control over which way it goes.   The user gets to choose how it behaves.

**Comment by thinkyhead** [comment]
I would prefer in my own machines that G28 not re-enable leveling. So let's make that optional, at least.

**Comment by thinkyhead** [comment]
Good or not, it's a relatively important change. Let's not go off and make it without consulting those it might impact.

**Comment by Roxy-3D** [comment]
Yes...    It already is that way...     The user has to take action to make the leveling active at power up (and after a G28).    But really....    In the big picture...   It is a non-issue.   The Z_CLEARANCE numbers are going to raise the nozzle enough that a .1mm dip of the nozzle because it is corrected just doesn't matter.

**Comment by thinkyhead** [comment]
UBL does exactly as `AUTO_BED_LEVELING_BILINEAR` does, as far as the Z correction and breaking up moves on mesh lines. The `ubl_line_to_destination` function can be moved into the same location as the `bilinear_line_to_destination` and `mesh_line_to_destination` functions.

Possibly the lack of recursion in `ubl_line_to_destination` is a benefit, or possibly it isn't. We'll have to benchmark and see how it compares. MBL is nearly obsolete, pending the addition of `PROBE_MANUALLY`, so if we can have a single function that splits up moves on grid lines, that would be a good consolidation.

For Marlin 1.1.1 and 1.2 we'll encapsulate the handling of the coordinate system either within the `Planner` class, or in a new class that deals with cartesian coordinates, bed leveling, kinematics, sending moves to the planner, and translating between stepper positions and cartesian (leveled and unleveled) positions.

**Comment by Roxy-3D** [comment]
> Possibly the lack of recursion in ubl_line_to_destination is a benefit, or possibly it isn't. We'll have to benchmark and see how it compares. MBL is nearly obsolete, pending the addition of PROBE_MANUALLY, so if we can have a single function that splits up moves on grid lines, that would be a good consolidation.

The reason I said "I'll review in the morning." is because I've been playing darts.   You know what that means!   But with that qualifier, I'm pretty sure the ubl_line_to_destination() is going to be faster than any of the other line_to_destination() functions.   Mostly...  Because I cheated...  ubl_line_to_destination() does not do a bi-linear interpolation as it crosses mesh lines.   And it doesn't wind up the stack with a bunch of recursive calls that all need to do calculations to figure out how to proceed.   It only does one bi-linear interpolation per call and that is for the final destination point.  It really is coded tight (from a cpu cycle perspective --- not a code foot print perspective).

When things slow down...  I want to do a speed test...    But that can wait until there aren't any bug reports.

**Comment by Roxy-3D** [comment]
> Your ubl_line_to_destination function is currently incompatible with non-zero home_offset or position_shift. You need to do this, or your leveling will break after M206 / G92.

 >>   cell_start_xi = ubl.get_cell_index_x(RAW_X_POSITION(x_start));
 >>   cell_start_yi = ubl.get_cell_index_y(RAW_Y_POSITION(y_start));
 >>   cell_dest_xi  = ubl.get_cell_index_x(RAW_X_POSITION(x_end));
 >>   cell_dest_yi  = ubl.get_cell_index_y(RAW_Y_POSITION(y_end));

I'm trying to make any of the simple and straight forward changes you pointed out...   I'll do a Pull Request for them later today...

**Pull request merged**
