### PR TITLE
[2.0.x] MK3 laser sensor (WIP)

### PR DESCRIPTION
**Pull request by GMagician**
This is start coding for addressing #12958.
It's almost a "what do you think?" question more than a PR

### CODE REVIEW

**Comment by GMagician** [comment]
Not sure if better to use SlowSoftI2CMaster library or self written prusa one.
Latter seems shrinked and code optimized...any suggestion?

**Comment by AnHardt** [comment]
Is there good reason to use either of them?
I did my tests with standard hardware I²C (normal builtin wiring library). That's a minimum requirement for all Arduino cores.
Do you see a conflict with any other I²C device?

**Comment by revilor** [comment]
I just came accross this PR. Looks like we are aiming at the same target from different angles :-) 

Actually I'm aiming at a bigger target than just the use of the PAT9125 sensor in Marlin. I would also like to integrate the MMU2's FINDA sensor into the runout sensor framework. Unfortunatelly at the moment there is only one kind of sensor supported at a time so you can either have a switch-based sensor or an encoder. But the FINDA is kind of a switch and the PAT9125 is kind of an encoder so I'm going to refactor the runout sensor code so that different types of sensors can be used together. And for the MMU2 I also have the requirement to temporarily disable sensors while a material change is going on to avoid false positives. 

All this will take some time to finish so if you just want to use your PAT9125 sensor I'd like to contribute my working code to access the sonsor via I2C. It's just a port from Prusa's firmware using standard Arudino Wire library. Unfortunately because I also forked Marlin I can't fork your Marlin fork to create a PR there. Therefore please find my sources in the attached ZIP.

[pat9125.zip](https://github.com/MarlinFirmware/Marlin/files/2777970/pat9125.zip)

**Comment by GMagician** [comment]
@AnHardt 

> Is there good reason to use either of them?

no just my ignorance about the Arduino framework

@revilor thanks for your sources. I'll already imported some Prusa code and wire class may be the better choice (as also @AnHardt stated).
I'll start creating a class for laser PAT sensor (maybe I'll change sources from MK3 sensor to PAT since this will really identify it). I think sensor may already be disabled now (there is an enable field) but no more than one kind is supported (more sensors yes but of the same kind).
Also no more PAT sensors may be used, chip supports 3 addresses but sensor had hardwired selection (no jumper to change it).

If you think you may recycle my code (after it will be merged) to built your "multi sensor type" logic then that's good, otherwise if you think that mine is a "dead" job then I'll kill it and wait your implementation

**Comment by thinkyhead** [comment]
```
git fetch origin
git checkout 2.0.x-MK3-filament-sensor
git reset --hard origin/2.0.x-MK3-filament-sensor
```

**Comment by revilor** [comment]
I made some more changes to get the PAT9125 sensor working. Already saved me a MMU2 print so we are on the right way here. 

All my modifications are in [https://github.com/revilor/Marlin/tree/2.0.x-MK3-filament-sensor](https://github.com/revilor/Marlin/tree/2.0.x-MK3-filament-sensor) which is based on [https://github.com/GMagician/Marlin/tree/2.0.x-MK3-filament-sensor](https://github.com/GMagician/Marlin/tree/2.0.x-MK3-filament-sensor).

**Comment by GMagician** [comment]
@revilor I'm expecting my sensor on monday to start testings but I think you are a step forward. Is it better to close this PR and wait for yours?

**Comment by revilor** [comment]
No, just keep this one going. Lots of users are asking for that sensor so getting the PAT9125 support into Marlin as soon as possible is perfect to widen the test base. 

I'm still not 100% sure it's worth any further effort because of all the issues Prusa had and has with this thing. But Duet has a similar extension also based on the PAT9125 so maybe it's not complete nonsense. I will test the PAT9125 for some time to gain my own first hand experience before I start with what I have in mind regarding the filament sensors.

**Comment by GMagician** [comment]
> I'm still not 100% sure it's worth any further effort because of all the issues Prusa had and has with this thing

That's true if used like prusa did, but I found on thingiverse some people use a bearing and read it's movement. With such change you can still detect stuck/jam with any kind of filament

**Comment by GMagician** [comment]
@revilor 
```c++
if (pat9125_PID1 != 0x31 || pat9125_PID2 != 0x91)
  SERIAL_ECHOLN("PAT9125::init failed");
  SERIAL_ECHOLN(pat9125_PID1);
  SERIAL_ECHOLN(pat9125_PID2);
return false;
```

you should add this code also in "init_new" since it check again vs device pid

**Comment by GMagician** [comment]
Now sensor is reading. Hence setup is working so do y reading (tested update function).

I don't have a properly testable extruder head (missing tensioner springs).

If someone here can do some test it will be welcomed

**Comment by GMagician** [comment]
@revilor I changed setup (it's suitable to you too) and moved runout.setup after serial initialization (you need to properly echo setup status)

**Comment by revilor** [comment]
@GMagician You should merge the changes I made in my branch mentioned above, it will not work without those modifications: [https://github.com/revilor/Marlin/commit/d1fcee1acb7e9bcd829d9c6183bc3caecae0fa9b#diff-a7c736c674fcde8ddf7bf0e86181e4c0](https://github.com/revilor/Marlin/commit/d1fcee1acb7e9bcd829d9c6183bc3caecae0fa9b#diff-a7c736c674fcde8ddf7bf0e86181e4c0)

Especially the changes in stepper.cpp are important, the sensor will not be triggered otherwise.

**Comment by GMagician** [comment]
@revilor why do you think pat can't work like original encoder? I think I just replicated such logic

**Comment by revilor** [comment]
The problem is, when you define `MK3_FILAMENT_SENSOR` you end up with `RunoutResponseDebounced` which just counts down from 5 to 0 and immediately and forever triggers a filament runout because it does not react to `block_completed()` which is the place to check the laser sensor for motion.

You could change that by setting `FILAMENT_RUNOUT_DISTANCE_MM > 0` which would enable the encoder logic. But I want the `PAT9125` to trigger without delay so that's no option from my point of view. And `RunoutResponseDelayed` is not a good fit for the laser sensor, anyway. Therefore I created `RunoutResponsePAT9125` which is supposed to be optimized to how the laser sensor works.

I still got lots of false positives with what's in my repository so at the moment I'm testing a slightly different approach to detect a filament runout. If it works out I'll let you know and add the corresponding code to my repository. Unfortunately, when you need the MMU to cause trouble to test the laser sensor it just works like a charm :-)

**Comment by GMagician** [comment]
@revilor that ok but I think problem is from roots. Why can't encoder works without `FILAMENT_RUNOUT_DISTANCE_MM == 0`?
And why is pat different from encoder? Both get info only when filament moves (info is got from different source — that's ok)
I think, from concept, that `FILAMENT_RUNOUT_DISTANCE_MM` should delay every kind of sensor but all kind of sensor should work with "immediate" trigger option as well.

After that I think that MMU2 may be a special beast that change everything...but really it should?
After that..you get false trigger but is this related to how filament runout works or to laser itself?

**Comment by thinkyhead** [comment]
Updated the PR so that the filament runout sensor type is set in conjunction with enabling the sensor. It might take a few tries to pass Travis. Once it does…
```
git fetch origin
git checkout 2.0.x-MK3-filament-sensor
git reset --hard origin/2.0.x-MK3-filament-sensor
```

**Comment by thinkyhead** [comment]
I agree that the `FILAMENT_RUNOUT_DISTANCE_MM` should not be used as the motion threshold for the encoder-type filament detector (or for the PAT9125), and that the `FILAMENT_RUNOUT_DISTANCE_MM` should apply to all detector types after the runout condition has been triggered.

**Comment by GMagician** [comment]
> Is there good reason to use either of them?

@AnHardt I'm doing some test, I restored my printer, and it seems that using Wire avr will be reset as soon as printer start....
I now copied original prusa code and it seems to work (at least printer doesn't reboot)...

**Comment by GMagician** [comment]
I've done some test and code, as it has been written now, can't handle a "motion detection" sensor without "distance"...I took a look at prusa firmware, but it uses an "auto generated interrupt" (if I properly understand code) to decide when to read sensor. But this is done only when a "detectable" amount of extrusion has been done.
Code need to be changed and maybe add a "motion sensitivity amount", when I have a little bit of time I'll see what can be done

**Comment by GMagician** [comment]
@marcio-ao I'm going to change filament runout logic to let "filament presence" and "delayed runout" to work with both switch sensors and motion sensors.
For motion sensors I need a new parameter that is "sensor resolution" that is the minimum detectable motion amount (do you have used such encoders? can you give me resolutions? for sure I think I have to add a new configuration_adv parameters to let users change it).
Some of this new logic is derived from prusa but I need to know from you, since I think you wrote current runout code, if this may give issues to you.
@thinkyhead and @ejtagle to support this new logic I had to add code to isr sensitive area (just some add instructions). code should be "balanced" and just add a fixed amount of time (if add and sub instruction use same clock cycles) please tell me if this is permitted or not. Just to know if proceed or not

**Comment by marcio-ao** [comment]
> For motion sensors I need a new parameter that is "sensor resolution" that is the minimum detectable motion amount (do you have used such encoders? can you give me resolutions? for sure I think I have to add a new configuration_adv parameters to let users change it).

@GMagician: We are using hall effect sensors with a magnetic encoder wheel. The minimum detectable motion is about 2.5 mm. Feel free to implement it in a better way. There is nothing ideal about the way it is currently done. The biggest issue right now is that the code only updates the counters at the end of a move, so there is a large amount of error, as much the length of the last segment.

**Comment by GMagician** [comment]
> The biggest issue right now is that the code only updates the counters at the end of a move, so there is a large amount of error, as much the length of the last segment.

@marcio-ao new code will use sensor resolution to read motion often than before. This (*2 to avoid false detection) will be the minimum amount to detect rounout. Above this detection scheme will work "delayed" runout report...I hope be able to do it

**Comment by GMagician** [comment]
I made some test and it's not as good as I would...reading sensor take to much time, if done directly in step ISR and often mega is reset. Now I think I understand why Prusa firmware use an input attached interrupt to do such a work. I think it simulate an input pin change to fire an ISR but its execution is delayed until stepper interrupt is fully terminated. Now this can be done with avr but I don't really know what about other boards and which input pin to use (prusa has limited hardware configuration while Marlin has a lot).
I think code done till now (I have to merge latest things) may be (after a testing) merged and this let to delay switches and motion detection sensors or both works immediately. I don't know if I can find a generic solution for PAT9125

**Comment by thinkyhead** [comment]
Rebased and squashed…
```
git checkout 2.0.x-MK3-filament-sensor
git fetch origin
git reset --hard origin/2.0.x-MK3-filament-sensor
```
…but this error still remains:
image

**Comment by GMagician** [comment]
> …but this error still remains:

now they should be fixed...still remain the problem how to defer sensor reading after stepper ISR to avoid watchdog reset (this I think is the reset/bad movements cause)

**Comment by thinkyhead** [comment]
Rebased and force-pushed once more.
```
git checkout 2.0.x-MK3-filament-sensor
git fetch origin
git reset --hard origin/2.0.x-MK3-filament-sensor
```

**Comment by thinkyhead** [comment]
> still remain the problem how to defer sensor reading after stepper ISR to avoid watchdog reset

Aim for simplicity. That sometimes helps.

**Comment by GMagician** [comment]
Ok now compiles ok, at least for mega2560. For other boards is missing I2C signals definition

**Comment by GMagician** [comment]
@thinkyhead I'm moving to MK3S IR sensor and I'm not able to find a good solution to read sensor with a good resolution. This code, removing pat sensor, may be used as base to let sensors to work in "immediate" and "delayed" detection mode. I don't heve possibility to test it with encoder, but once I have IR sensor I can test it in switch mode. I may close this or remove parts of it...I'm sorry for the time you spent with this...

**Pull request closed without merging**
