### PR TITLE
Robin Nano v1 CDC and env naming

### PR DESCRIPTION
**Pull request by EvilGremlin**
env and pins tweak for CDC
Renamed robin_nano_35 envs to more sensible robin_nano_v1v2, slight description tweaks.
Adds USB_MOD define, is it worth adding to docs 'configuration' page?
Anyway, i will subbmit new configs for Elegoo Neptune 2 and mod guide a bit later after some tweking and testing.
Made `FIRMWARE_BIN` to override `board_rename` too as a quick crutch for Elegoo's 1.3 boards, but i think we need to make
filename setting more universal.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
What is a USB mod?

**Comment by ellensp** [comment]
@thisiskeithb https://discord.com/channels/461605380783472640/743347429025251357/1005822147823927406
So far there is no documentation, tho I hear it is coming...

But basically remove usb/serial chip and re wire the Controller usb pins directly to the USB port and enable CDC USB

**Comment by thisiskeithb** [comment]
Should that really be integrated here?

**Comment by ellensp** [comment]
Since it will be a public project anyone can do, yes.
It effectively just another board to support.

**Comment by ellensp** [comment]
@EvilGremlin how goes the documentation?  Got a public url for this mod yet?

**Comment by EvilGremlin** [comment]
Nope, was busy, no doc yet. Will post in a few days. Not sure whether it's better to throw in configs repo or post separately.

**Comment by EvilGremlin** [comment]
Printed some stuff, all OK, made doc: https://github.com/MarlinFirmware/Configurations/pull/802

**Comment by thinkyhead** [comment]
For some reason this PR's branch is blocked for admins to apply changes. I'll try to fix it up with edits from the web interface.

**Comment by thinkyhead** [comment]
Ok, if you merge the PR EvilGremlin/Marlin#1 then this will be cleaned up and the merge will be applied.

**Comment by EvilGremlin** [comment]
indents... i added you as collab on my repo

**Comment by EvilGremlin** [comment]
good to go now

**Comment by thinkyhead** [comment]
You haven't merged the PR I created for your branch, so the needed changes are still missing.

Even as a collaborator, I still cannot push any changes to this PR.

**Comment by EvilGremlin** [comment]
You still can't edit this?

**Comment by EvilGremlin** [comment]
ugh, conflicts on trailing spaces...
last conflict - you really just deleted nano_v1_3_f4 envs?

**Comment by EvilGremlin** [comment]
merged

**Comment by thisiskeithb** [comment]
@EvilGremlin What is the difference between "v1v2" and "v1_2" builds here? Shouldn't they both be "v1v2" since they apply to both V1 and V2 boards?

CI tests are broken because of this PR, so that's why I'm looking into it.

**Comment by EvilGremlin** [comment]
Scott broke it with cleanup - it was v1v2 all through. And i was busy at work while merging yesterday so missed that too.

**Comment by EvilGremlin** [comment]
https://github.com/MarlinFirmware/Marlin/pull/24669

**Pull request merged**
