### PR TITLE
Propose updates to issue to template

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

The quality of many reported issues is very low. This is an attempt at helping prevent the following problems with new issues:
1. Template completely ignored
2. Configurations not attached
3. Support questions asked in bug reports

### Benefits

I don't know whether it will make any difference, but it seems worth trying something.

### Configurations

N/A

### Related Issues

N/A

### CODE REVIEW

**Comment by boelle** [comment]
i totally agree here, it see the same thing as you, but also noted that @thisiskeithb and @ellensp face the same thing

**Comment by thisiskeithb** [comment]
Yes. Asking for configs is getting old and it's just a guessing game if they aren't provided.

**Comment by boelle** [comment]
i have spoken out why we dont have a bot more like the one Octoprint has, ie it does some basic checks if a template has been followed and if not it will close and ask to fix what is missing and then it will open again

**Comment by thinkyhead** [comment]
> i have spoken out why

There's no need to speak out against this injustice. We want to make it all lovely and perfect like everything OctoPrint touches, but it takes time and attention that I simply don't have at this moment.

**Pull request merged**
