### PR TITLE
[1.1.x] Minor filament change improvements

### PR DESCRIPTION
**Pull request by thinkyhead**
This PR…
- Adds commentary to filament change, pause, and resume functions.
- Show `M600: Too cold` message on LCD when M600 fails.
- Make `L` parameter to `M125` sign-agnostic.

### CODE REVIEW

**Comment by tcm0116** [comment]
@thinkyhead When you port this to 2.0.x can you double check that nothing was missed in the load/unload port from 1.1.x to 2.0.x? M600 was causing my Delta to wander off after the Z raise, and then M701 and M702 didn't work at all (i.e. no wait for start on the LCD or Z lift).

Looking at those issues is on my TODO list, but I noticed you're already working on the filament change code.

**Comment by thinkyhead** [comment]
I think it might be easier at this point to first isolate the cause, rather than go hunting for discrepancies between two large PRs. If some codes don't work at all that's a sign they never got added to the `process_command` call list.

**Comment by thinkyhead** [comment]
I started working on this because filament change still feels incomplete. If you start an SD print with no filament, it causes `M600` to be invoked right away. This puts up the "wait for filament change" screen and homes the machine as if to start the procedure. However, since the nozzle isn't heated yet it just sends "Hotend too cold" to the console, leaving the message "Home XYZ first" on the screen, and goes into a holding loop. After the loop times out it tries to continue printing instead of aborting.

So it could be more user-friendly. I've only added code to send "M600: Too cold" to the LCD status message, but it would be better if it always continues the guided procedure and goes to a heat-up selection screen next.

**Comment by tcm0116** [comment]
>I think it might be easier at this point to first isolate the cause, rather than go hunting for discrepancies between two large PRs.

Concur. I just wanted to throw out that I was having an issue, which might become obvious to you while you're porting this over 2.0.x. 

>If you start an SD print with no filament, it causes M600 to be invoked right away. 

Is this in the case of a filament sensor detecting that no filament is loaded?

**Comment by thinkyhead** [comment]
> Is this in the case of a filament sensor detecting that no filament is loaded?

Yes, with a filament sensor. It will also invoke `M600` if you start heating the nozzle while filament is out.

**Comment by tcm0116** [comment]
What if the filament sensor didn't call M600 unless the target temperature
is not 0?

**Comment by thinkyhead** [comment]
> What if the filament sensor didn't call `M600` unless the target temperature is not 0?

That would probably do the trick to prevent the pointless `M600`, but would it always make sense? I don't like having conditions that are based on a "side effect." Current conditions to invoke filament runout are:
- Print job is active and/or the SD card is being run
- Filament has run out

The new condition might be:
- Hotend target temperature is high enough

Note that this will cause `M600` to initiate as soon as you click `Preheat PLA` in the LCD menu.

So, here's the change to test…

```cpp
#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  if ((IS_SD_PRINTING || print_job_timer.isRunning())
     && READ(FIL_RUNOUT_PIN) == FIL_RUNOUT_INVERTING
     && !thermalManager.targetTooColdToExtrude(active_extruder)
  )
    handle_filament_runout();
#endif
```

**Comment by tcm0116** [comment]
>The M24 command uses resume_print to start a fresh SD print.

I don't follow why M24 would call `resume_print`. 

>Hide "wait for start of filament change" in pause_print if not unloading filament.

Wouldn't we still want that to still be displayed during the nozzle park?

>So, here's the change to test…

I like the addition of the target temperature check to the existing conditions. There's no point in doing an M600 automatically if the nozzle doesn't have a target temperature.

**Comment by tcm0116** [comment]
@thinkyhead I found the issues in 2.0.x and put together some fixes (https://github.com/tcm0116/Marlin/commit/7395776096cde4cabe746361ac1c14059a3e78c3). Do you want to incorporate them into the 2.0.x version of this PR or should I go ahead and make a new PR?

NOTE: edited to update link

**Comment by thinkyhead** [comment]
> I don't follow why M24 would call resume_print.

Possibly because `M24` is the command used to resume a print after an `M125`, which calls `pause_print`.

Anyway, my worry over the call to `resume_print` in `gcode_M24` was unfounded. The unexpected invocation of filament runout wasn't coming from there, but from having set the wrong `FIL_RUNOUT_PIN`. As soon as any SD print started it would trigger filament runout.

> Wouldn't we still want that to still be displayed during the nozzle park?

"Wait for filament change" if it's a filament change. If it's just pausing then "Moving Away" or something like that. In fact, "Moving away. Hold on." would be acceptable in both instances. Dropped this commit.

Anyway, we need to test and polish the load, unload, change, pause, resume, runout detection, and other such processes until they do everything we want. It will be kind of tedious to keep testing and refining these processes, but every little improvement helps.

**Pull request merged**
