### PR TITLE
makefile: add u8glib support

### PR DESCRIPTION
**Pull request by sorki**
ssia

### CODE REVIEW

**Comment by thawkins** [comment]
``` shell
SRC += $(shell find $(U8PATH) -name '*.c' -type f -exec basename {} \; )
```

This will only work on *nix clones, what about windows users,  thats why i put the expanded list of filenames in my PR. 

It would also have been polite to hold some discussion about this instead of just foisting a competeing PR into the repo, without any notice.

**Comment by sorki** [comment]
Are there any windows users actually using make? If so how? I'm asking because if there's make on win then there's probably bunch of dependencies so this shouldn't be a problem. 

Anyway your point makes sense but putting long list of files in makefile is sub-optimal and will lead to troubles when u8glib changes.

I'm not trying to compete with anyone but your pull request contains way too much unrelated changes - making separate PR makes things much easier to discuss.

**Comment by Wackerbarth** [comment]
@sorki -
Richard, I agree that splitting things up is helpful for discussion.  But having separate PRs for each part is a bit overboard. You can accomplish much the same result within one PR by having the various parts as separate commits within a single PR.

**Comment by sorki** [comment]
@Wackerbarth I'll try to keep my PR's balanced. I agree that related changes can be merged into one PR but preferences differ from project to project.

**Comment by thinkyhead** [comment]
@thawkins @sorki Do we have any viable alternatives to the *nix **find** command that will accomplish the same thing on Windows? Or, must we use some other method of setting `SRC`?

What shell environment are Windows users most likely to use to run **make**? Will it simply have a different variant of **find**?

**Comment by thawkins** [comment]
This may help

For make:

http://gnuwin32.sourceforge.net/packages/make.htm

For find etc (i think its in there) . Note the lack of this on Windows is why i did not use `find` in my PR.

http://sourceforge.net/projects/unxutils/files/unxutils/current/

I cant guarantee the state of these tools as i don't use windows, i have one machine i use for games and i will try loading these utils.

The Makefile contains lots of unix dialect, so it may have problems with windows setups, however it's almost bizarre that i have _literally just added_ the ability to detect the OS/ARCH it's running under for exactly this reason. It was originally so that i could run then version building tool in LinuxAddons, but it should help with sorting out these differences.

Im going go get it out today as a gist, as until we have finished the inevitable round of arguing about the changes,  it a pain to keep recreating the PR (my git foo is not strong enough).

**Comment by thawkins** [comment]
It turns out that gnuwin32 project also has a find package which i would
probably trust more that the unixutils one.
http://gnuwin32.sourceforge.net/packages.html

Use the "findutils" Package.

**Pull request closed without merging**
