### PR TITLE
RGB_Strip and DHT Sensor

### PR DESCRIPTION
**Pull request by ghost**
RGB_Strip addition with printer events with and without SD printing.

DHT Sensor support to read Ambient Temp and Humidity of the printer's environment.

### CODE REVIEW

**Comment by ghost** [comment]
I am attempting this PR against the RC due to it being new features not bug fixes.

**Comment by ghost** [comment]
Ok...that's it.

**Comment by android444** [comment]
Where is the chance?

**Comment by ghost** [comment]
@android444, I'm not quite getting what you're asking.

**Comment by ghost** [comment]
Tannoo/Marlin:RC is where this PR is coming from.

**Comment by manianac** [comment]
Given how all RCs are just RCBugfix branch snapshots, you're doing a lot of extra work by using RC.  Its highly recommended you re-do this against RCBugfix.

**Comment by ghost** [comment]
I am trying. Although, the last time I got them to work, the bed leveling system got broken... Not by me. So, I couldn't test it.

RC worked for me amd I was able to test it. I am going to try again. Especially now that my additions work.

**Comment by akaJes** [comment]
good work, but there some suggestions:

0. create PR for RCBugfix (and do not to break files cardreader.cpp and ultralcd.cpp - commits looks like You change whole files)
1. could be better to split PRs for DHT and RGB Strip and other minor changes
2. do not forget about  of other configurations when you modify Configuration.h and Configuration_adv.h
3. i think You use DHT Adafruit or other library - better is to ask in Configuration.h to include it manually from url/git/manager

**Comment by ghost** [comment]
I was thinking about separate PR's for each. The RGB_Strip was from another PR: (#5395 by @boweeble).
I just modded that one. Maybe I should put the PR against HIS PR.

So, that means I should just PR the DHT sensor. I could ask for the library to be installed. I just included the files to make life easier.
Note: Adafruit library was too large. The library I found was a non-blocking type.

I did not change the whole files of cardreader.cpp, it was modded by #5395. I may have just uploaded the whole file to GitHub. The same with ultralcd.cpp, except that I did change that one for the menu additions.

I'll close this PR and re-submit to RCBugFix just the DHT with library reference.

**Pull request closed without merging**
