### PR TITLE
Improvements and fixes to Lulzbot UI

### PR DESCRIPTION
**Pull request by marcio-ao**
- Fix for incorrect tags on background items
- Improvements to Bio printer UI
- Theme colors are now selected in HSL space.

### CODE REVIEW

**Comment by thinkyhead** [comment]
This seems like it should not work:
```cpp
  #define CLCD_MOD_RESET                 LCD_PINS_ENABLE
  #define CLCD_SPI_CS                    LCD_PINS_D4
```
…because these pins are not defined by any of the pins files unless a particular display is selected, and I don't see any special cases for these added to the pins files for the Lulzbot Touch UI. As a result, it looks like only the `OTHER_PIN_LAYOUT` will currently work for Travis testing.

**Comment by thinkyhead** [comment]
It appears that the `unicode/unicode.h` header is expected, but it is not included if building for Marlin…
```
command_processor.h:313:42: error: 'has_utf8_chars' was not declared in this scope
       const bool is_utf8 = has_utf8_chars(text);
```

**Comment by thinkyhead** [comment]
Maybe it is this disagreement between `compat.h` and `ftdi_extended.h` on whether to set `FTDI_EXTENDED`.
#### `compat.h` enables it with `LULZBOT_TOUCH_UI`
```cpp
#ifdef __MARLIN_FIRMWARE__

  // Marlin will define the I/O functions for us
  #if ENABLED(LULZBOT_TOUCH_UI)
    #define FTDI_BASIC
    #define FTDI_EXTENDED
  #endif

#else // !__MARLIN_FIRMWARE__
```
#### `ftdi_extended.h` does not
```cpp
#ifndef __MARLIN_FIRMWARE__
  #define FTDI_EXTENDED
#endif
```

**Comment by thinkyhead** [comment]
Perhaps I need more settings to get a proper build. Here is what I added to `DUE-tests`…
```
opt_set LULZBOT_TOUCH_UI LCD_ALEPHOBJECTS_CLCD_UI OTHER_PIN_LAYOUT
```
…and I also had to add to `Conditionals_LCD.h`…
```cpp
#ifndef SPI_SPEED
  #define SPI_SPEED SPI_FULL_SPEED
#endif
```
What else is needed to get a successful test build?

**Comment by thinkyhead** [comment]
I've added the non-working test for `LULZBOT_TOUCH_UI` to the `DUE-tests` file. Rather than wait for Travis to run the test, you can use the `mftest` script to run tests locally. If you can get a complete working build for DUE (or one of the other platforms) that will be useful for checking future changes.

**Comment by marcio-ao** [comment]
> This seems like it should not work:
> 
> ```c++
>   #define CLCD_MOD_RESET                 LCD_PINS_ENABLE
>   #define CLCD_SPI_CS                    LCD_PINS_D4
> ```
> 
> …because these pins are not defined by any of the pins files unless a particular display is selected, and I don't see any special cases for these added to the pins files for the Lulzbot Touch UI. As a result, it looks like only the `OTHER_PIN_LAYOUT` will currently work for Travis testing.

On certain boards, I put in a [special case](https://github.com/MarlinFirmware/Marlin/blob/e6055dce76d19b3851138e71bed28f6b146e68b2/Marlin/src/pins/rambo/pins_EINSY_RETRO.h#L170) in the pins files:

 `#if ENABLED(ULTIPANEL) || TOUCH_UI_ULTIPANEL`

This only happens on the Archim 2 and the Rambo boards which Lulzbot uses. That said, running Travis with `OTHER_PIN_LAYOUT` is probably adequate.

**Comment by marcio-ao** [comment]
I'll look into the other issues and see if I can find fixes.

**Comment by marcio-ao** [comment]
> It appears that the `unicode/unicode.h` header is expected, but it is not included if building for Marlin…
> 
> ```
> command_processor.h:313:42: error: 'has_utf8_chars' was not declared in this scope
>        const bool is_utf8 = has_utf8_chars(text);
> ```

This was an error when compiling without `TOUCH_UI_USE_UTF8`. I pushed a fix. You can compile the UI with and without that flag, plus with or without a bunch of other flags. So many permutations to test...

**Pull request merged**
