### PR TITLE
Rc bugfix ac [FR] Autocalibration for deltas #6182

### PR DESCRIPTION
**Pull request by LVD-AC**
The calibration of a delta is an iteration process that can be automated. Here's a routine to calibrate the delta height, end-stop adjustments and delta radius. It has been tested thoroughly by a multitude of users in the Flsun FB group. It should work on other deltas as well.

First one needs to enable changing and storing in EEPROM of the delta height like I explained in #4061

Here's the auto-calibration routine to determine the correct delta height, end-stop adjustments and delta radius. It iterates using a convergence matrix until the iteration process overshoots the solution and then rolls back one step.

See also #6182

### CODE REVIEW

**Comment by thinkyhead** [comment]
Good job! It will need a bit of cleanup before it can be merged. I will pull it into my fork, rebase and squash the commits, clean up the code, and submit a new PR for your review shortly.

**Comment by LVD-AC** [comment]
That's all folks (for the AC-routine); have a look at the configuration.h in the Flsun-AC dir. I reworked (cleaned from unnecessary clutter) the whole delta setting section; in the other configs, I just put the bare necessities for it to work.

**Comment by thinkyhead** [comment]
I've rebased and squashed it down, and am working on fixing the formatting and properly implementing the EEPROM code. Naturally I will make a closer study of the code as I do so.

While I'm working on that, can you explain how you're using `home_offset` and what the purpose of `DELTA_HEIGHT` is?

**Comment by LVD-AC** [comment]
`DELTA_HEIGHT` is a constant set up in the firmware = `MANUAL_Z_HOME_POS` but I've given it a more recognizable delta name. And by renaming it I could also move it to the delta section were it should be with the other delta geometry settings, so all calibrated things are in one place.

But in order to change that value with a variable, that could be change and stored in EEPROM was quite a task. I used the Z-component of `home_offset` which seems to do the trick as long as it stays reasonably small. You could call that Z-component the `Delta_height_adjustment`.

In EEPROM however I store the sum of the 2:  `DELTA_HEIGHT + home_offset [Z_AXIS]` = the real delta height, so if changes are made to the firmware `DELTA_HEIGHT` the real height value retrieved from EEPROM does not change; the `home_offset[Z_AXIS]` is changed accordingly with an EEPROM read.

**Comment by thinkyhead** [comment]
> DELTA_HEIGHT + home_offset [Z_AXIS] = the real delta height

Ah, I see. I sometimes forget there's a real use-case for `M206`.

I'm on the fence about adding another setting. `DELTA_HEIGHT` would seem a reasonable value to include, but we do already have `Z_HOME_POS` (supplied sometimes by `MANUAL_Z_HOME_POS`) and users are _already_ required to set that value. It's probably best to throw it away and just use `Z_HOME_POS` in the code instead.

As for the EEPROM, I need to look at it a bit more. You'll notice in the attached new PR #6187 (built from 59cfaab) that I've applied various changes to bring the code into better compliance. For example, the EEPROM can't be changed without bumping the version number, updating the heading, and ensuring that the data structure is consistent whether features are enabled or not, so that enabling a feature doesn't require a reset of the EEPROM.

Look that PR over and examine its changes. I've got to take off now, but I'll try to integrate 52c17b4 and 0aecc5d tomorrow, and continue to patch it up.

**Comment by LVD-AC** [comment]
I did find one bug in your clean:
```cpp
if (probe_points != 1) {
  for (int axis = 1; axis < 13; axis += step_axis)
    z_at_pt[axis] += probe_pt(abl_probe_pt_x[axis], abl_probe_pt_y[axis], true, 1);
}
if (probe_points == 4) step_axis = 2; // needs to be outside the loop
```

**Comment by LVD-AC** [comment]
Another bug:

          S1 += z_at_pt[axis];
          S2 += sq(z_at_pt[axis]); // not S1 which is the running sum

**Comment by LVD-AC** [comment]
This:

          sprintf_P(mess, PSTR("Calibr. OK   sd:%0.2f"), zero_std_dev);

gives a question mark on the LCD not the standard deviation???

**Comment by LVD-AC** [comment]
appart from the 3 issues above the revised gcode_G33 routine seems to run as it should

and:

          LOOP_XYZ(axis) endstop_adj[axis] -= z_temp; // not LOOP_XYZE of course

**Comment by LVD-AC** [comment]
> I'm on the fence about adding another setting.  

Since MANUAL_Z_HOME_POS and DELTA_HEIGHT are the same there is no objection to use MANUAL_Z_HOME_POS in all the programming code instead of DELTA_HEIGHT.

However in configuration.h I would keep these 2 lines of coding:

```
#define DELTA_HEIGHT 298.95
...
#define MANUAL_Z_HOME_POS DELTA_HEIGHT

```
it makes life so much easier to have all delta settings in one place

**Comment by LVD-AC** [comment]
> When one option negates another, as  DELTA  does to  NO_WORKSPACE_OFFSETS...

Yes the autocalibration and delta height control relies on the offsets enabled. A sanity check error will do.

However only the Z-component is used; so it is still a good idea to prevent the user to change the X-Y components (they really mess things up (**) on a delta when used) and thus disabling the M206 and M428 commands on Deltas and giving access to the Z component via M665 only (= indirectly by H delta height). M206 and M428 are typical Cartesian commands anyhow(*), I just found good use for the Z component in Deltas.

(*) While we're on the subject: on Cartesians the bed should be tilted to make it perpendicular to the physical X and Y axis so beds are put on springs and levelling routines in G29 were developed. The Z axis should be perpendicular to it but this is a hardware problem. On Deltas the 3 axis should be perpendicular to a fixed bed (if not use a washer) and calibration is done by tilting the upper triangle made up by the 3 carriages so end-stop screws and calibration routines like Esher 3D, Rick Cartell and my LVD-AC(***) were developed for that. Spring loaded beds and levelling routines that tilt the bed make no sense to me on Deltas and encourage people to calibrate deltas the wrong way. IMO G29 is in conflict with Deltas as well and should give a sanity error ALL the time; like G33 should give an error on Cartesians.

The only 'bed leveling' routine that could make sense on deltas is a detailed bed probing that does not tilt the bed but adjusts the z-height according the detailed probe map to eliminate some local bumps and hops. And a 7*7 map that still can be stored in EEPROM is a bit on the short side to do that.

(**) X-Y home offsets have a similar effect as radial tower angle corrections or xyz-delta-radius corrections to the perceived bed shape, but they also change the effective end-stops and I have no idea how the relationship is. I also have an experimental version of the LVD-AC routine that calibrates the xyz-delta-radius corrections as well (I see all the variables are already in place in Marlin-RC8), but first let's get the simplified version with only end-stops, delta height and delta-radius on the road.

(**) I'm willing to share the work I did on this routine for the last year and a half, under the open GNU licence but please restore the comment in gcode_G33 to give me some credit for it:
```
      // **************************************
      // * written by Luc Van Daele 2016-2017 *
      // **************************************
```

**Comment by LVD-AC** [comment]
I have to go trough the code with much care; found another bug:

```
              x_delta = Z100(0) + Z033(1) - Z017(5) - Z017(9) + Z017(3) - Z033(7) + Z017(11); // Z017(11) instead of Z017(1)
              y_delta = Z100(0) - Z017(1) + Z033(5) - Z017(9) + Z017(3) + Z017(7) - Z033(11);
              z_delta = Z100(0) - Z017(1) - Z017(5) + Z033(9) - Z033(3) + Z017(7) + Z017(11);
              r_delta = ZP(-2.00, 0) + Z033(1) + Z033(5) + Z033(9) + Z033(3) + Z033(7) + Z033(11);

```
Wouldn't it be better I have access to the working copy of this so I can make the necessary changes on GitHub?

**Comment by thinkyhead** [comment]
> gives a question mark on the LCD 

Ah, right. The printf on AVR doesn't do floats. D'oh!

**Comment by thinkyhead** [comment]
> Z017(11)

That seems to already have been patched last night.

**Comment by thinkyhead** [comment]
> Wouldn't it be better I have access to the working copy of this so I can make the necessary changes on GitHub?

You do. The working copy is my branch. Through git you can check out a copy of my branch, add commits to it, and submit them as a PR to my fork.

First add my fork and make a copy of the branch:
```
git add thinkyhead git@github.com:thinkyhead/Marlin.git
git fetch thinkyhead
git checkout thinkyhead/rc_flsun_delta_autocal -b work_on_autocal
```
Edit, add commits, etc. Then push them up to your fork and submit a PR…
```
git push --set-upstream origin work_on_autocal
open https://github.com/thinkyhead/Marlin/compare/rc_flsun_delta_autocal...LVD-AC:work_on_autocal?expand=1
```
Once I merge your PR into my branch, your new commits will be added to my PR at #6187.

**Comment by thinkyhead** [comment]
>
```cpp
// **************************************
// * written by Luc Van Daele 2016-2017 *
// **************************************
```

😕 I've been working on Marlin for dozens of hours a week since 2015. Notice my name all over the code?? No, you don't. Because we would rather not fill the code with a bunch of credit comments. We have enough in the headers. You have credit (or "blame") by virtue of being the one whose GitHub account is attached to the commits.

**Comment by thinkyhead** [comment]
Continue at #6187 please.

**Comment by LVD-AC** [comment]
> You do. The working copy is my branch. Through git you can check out a copy of my branch, add commits to it, and submit them as a PR to my fork.

Sorry new to GitHub, there seem to be no place in the thing I downloaded to enter commands, so completely lost here.

**Comment by thinkyhead** [comment]
Try right-clicking on the name of the repository in the left sidebar of the Github Desktop app. You should see an option to open up a command-line.

**Comment by LVD-AC** [comment]
No luck "fatal: pathspec 'thinkyhead' did not match any files"

**Comment by thinkyhead** [comment]
Sorry, I typed that incorrectly.
```
git remote add thinkyhead git@github.com:thinkyhead/Marlin.git
git fetch thinkyhead
git checkout thinkyhead/rc_flsun_delta_autocal -b work_on_autocal
```
…etc.…

**Pull request closed without merging**
