### PR TITLE
Limit Bed leveling to preset height

### PR DESCRIPTION
**Pull request by cbxbiker61**
This is the patch that I mentioned to you.   Joseph Prusa and Vojtěch Bubník at Prusa Reseach have show interest in maybe using a variation of this in their firmware.  Vojtěch suggests that we use a g-code to set the transition height, i.e.

At the moment my implementation only affects linear bed leveling, but should quite easily be adapted to the other flavors.

Mxxx 0    - disable this feature
Mxxx 2.5 - set transition height at 2.5mm

### CODE REVIEW

**Comment by cbxbiker61** [comment]
I messed up, I should have created a new branch and created the pull request on that branch.  Live and learn.

**Comment by epatel** [comment]
I think I understand what you want to do, it has been discussed many times. But, in this commit you are modifying the 3x3 matrix that is used for the non-linear ABL. And I would imagine the result being very strange because the 3x3 matrix (used to rotating the coordinate system/tilting the bed) is slowly altered in a way I can't imagine. I think you might be looking to modify this array https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/Marlin_main.cpp#L559-L560 

Well, that is what I think you are doing, I might not understand at all what you are doing.

Note. UBL has a feature to do this I think. The `blm.fade_scaling_factor_for_Z( z )` part on this line https://github.com/MarlinFirmware/Marlin/blob/devel-ubl/Marlin/planner.cpp#L1165

**Comment by Blue-Marlin** [comment]
levelling
If i do understand your suggestion, i don't want it.

**Comment by epatel** [comment]
@Blue-Marlin I don't think we even can imagine the effects as the change is all over the 3x3 matrix so it doesn't straighten the model...it will be just weird I imagine. Scaling etc etc

**Comment by Blue-Marlin** [comment]
Lets put aside the implementation.
Ether the 'plan' is the fade the normal from perpendicular to the bed to perpendicular to the machines x/y-plane (in the posting above).
Or he wants to fade only the z-correction.
fading z

Both is crap.

**Comment by epatel** [comment]
@Blue-Marlin I can agree on that

**Comment by thinkyhead** [comment]
I've been contemplating a similar idea for some time, and have mentioned it in several postings. I'm sure I've proposed it to Vojtěch also.

I think that if you have a reasonably perpendicular bed and are using a mesh-based leveling then it's not so bad to "fade out" leveling over the first centimeter or so. Once past that point the leveling can turn off and save on processing power, which is especially nice for a deltabot (assuming its usual trajectory isn't bowl-shaped).

**Comment by cbxbiker61** [comment]
@thinkyhead,

This first merge request was really more of a RFC than anything.  It did get some feedback which is good.

This first implementation was wrong, I hadn't even take a proper amount of time to understand the unity matrix, hehe, it was years ago since I had actually worked with that stuff.

The good news is that I fixed my issues, and came up with a version that works properly and gives good results.  It only affects Z height and in my tests I have it fading over 2mm.  My bed is 0.5mm off over one of the axis, so I guess that is a reasonable test.

Since my implemetation only applies to the Z-axis it even saves cpu cycles while it is in the bed-leveling zone, and of course all of the cpu-cycles are saved once it gets past the preset height.

If you want to give me an G-gode number to assign for this, I'll go ahead and submit a pull request that should satisfy everyone.

**Comment by thinkyhead** [comment]
@cbxbiker61 I suggest that you use `M850` to assign the Z-fade. Make your new PR, and of course I'll critique the hell out of it — till it's perfecto. I will follow it up with the implementation for bilinear and mesh leveling also.

**Pull request closed without merging**
