### PR TITLE
Improves travis buildroot regexp

### PR DESCRIPTION
**Pull request by jbrazio**
Follow up #3906: The regular expressions are not working properly as most of the Travis tests are outputting the text bellow, which is a sign of options aren't being manipulated.

```
Sketch uses 52,456 bytes (20%) of program storage space. Maximum is 253,952 bytes.
Global variables use 2,961 bytes (36%) of dynamic memory, leaving 5,231 bytes for local variables. Maximum is 8,192 bytes.
```

I also took the opportunity to upgrade travis Arduino IDE version to 1.6.9.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Word boundaries, nice. I never knew about those in regular expressions.

Looks like the 1.6.9 changes aren't being taken well…

**Comment by jbrazio** [comment]
There is a known bug with `ULTRA_LCD` which was patched by @Blue-Marlin a few moments ago. This PR is supposed not to pass Travis because it makes that error visible.

**Comment by thinkyhead** [comment]
If that is so, you can rebase this against `RCBugFix`, force-push, and all should be well.

**Comment by jbrazio** [comment]
``` bash
$ restore_configs
The command "restore_configs" exited with 0.

$ opt_enable ULTRA_LCD
The command "opt_enable ULTRA_LCD" exited with 0.

$ build_marlin
Picked up JAVA_TOOL_OPTIONS: 
Loading configuration...
Xlib:  extension "RANDR" missing on display ":1.0".
Initializing packages...
Preparing boards...
Verifying...
sketch/ultralcd.cpp: In function 'void lcd_update()':
ultralcd.cpp:2165: error: 'manage_manual_move' was not declared in this scope
   manage_manual_move();
                      ^
exit status 1
'manage_manual_move' was not declared in this scope
The command "build_marlin" exited with 1.
```

#3993 and #4001

**Comment by thinkyhead** [comment]
Strange. The `manage_manual_move` function is declared around line 1200, ~~without any conditions~~.

EDIT: Actually, the code is just in a hard-to-see `#if` block. PR #4011 adjusts the indentation and wraps up more vars in the conditional.

**Comment by thinkyhead** [comment]
I also note that if `manage_manual_move` is dependent on `ULTIPANEL` then that means all the LCD-based movement functions must be dependent on `ULTIPANEL` as well. So that must mean that all the menu items and other functions — basically everything but the Status Screen — is dependent on `ULTIPANEL`. But currently a lot of controller and menu code is being compiled in without checking `ULTIPANEL`.

So, I'm going to wrap everything that requires a controller in `#if ENABLED(ULTIPANEL)` blocks.

**Pull request merged**
