### PR TITLE
Add Geeetech Rostock 301 config, update GTM32 Pro VB pins

### PR DESCRIPTION
**Pull request by Phr3d13**
Add example configs for Geeetech Rostock 301 and update pins file.

### CODE REVIEW

**Comment by chepo92** [comment]
With this PR definition of heaters 1&2 and temp sensors 1&2 is lost, think should be kept for multi material printing and other uses of the board

**Comment by thinkyhead** [comment]
Sorry, I assumed this was being corrected based on the latest knowledge.

@Phr3d13 — Please collaborate with @chepo92 to provide corrections to the pins file. Use `pins_RAMPS.h` as the guide for how to properly assign extruder/bed/fan pins to functions based on the configuration.

**Comment by Phr3d13** [comment]
Yes, this is still being tested. Thinkyhead wanted a PR because of how much progress was made. Don't worry, I'm still working with this and will replace the -1's with proper values before I'm done. Yes, the thermistor table still needs work. Also with my machine (Rostock 301), it has a mixing nozzle, so I didn't notice the other temps/etc get -1'd.

**Comment by Phr3d13** [comment]
@chepo92 Have you joined the discord server?

**Comment by thinkyhead** [comment]
I put back some heater and temp sensor pins, presuming the ones most-recently supplied are ok for the Rostock 301 (with one hotend and heated bed), which is the only config example currently using the GTM32 Pro B pins.

**Comment by chepo92** [comment]
> 
> 
> @chepo92 Have you joined the discord server?

Just joined, i'm in as xepo




> 
> 
> I put back some heater and temp sensor pins, presuming the ones most-recently supplied are ok for the Rostock 301 (with one hotend and heated bed), which is the only config example currently using the GTM32 Pro B pins.

Thanks, i'll add more example configs with other setups

**Pull request merged**
