### PR TITLE
[FIX] tool change

### PR DESCRIPTION
**Pull request by studiodyne**
FIXING IN PROGRESS , please wait 

1 - T0 priming only , if different  toolchange make priming
2- Migration inhibit tool change temperature management
3 - Some mistakes 'tern and declaration'
4  - Gcode.dwell instead of safedelay() that block fans to work

I have 2020 03 19 version all works

### CODE REVIEW

**Comment by thinkyhead** [comment]
PRs can now be created as "Drafts." This is useful for things that still need work and are not intended to be merged yet.

**Comment by studiodyne** [comment]
Tool change need some fixes , at the beginning I found one fix , but , after more test , i have a few fixes to suggest. The pr was already written ,not for a draft , but for a serious bug , i have closed it , to add the others fixes , please wait , i will finish soon

**Comment by studiodyne** [comment]
Now i'm working on the temperature setting transmition , because too much problem , if modified by lcd , if autotemp and more
Please wait a little

**Comment by thinkyhead** [comment]
Ok. Please limit comments on issues so I can focus on actionable items in this queue.

If you want to socialize with me and other developers then join us on Discord: https://discord.gg/n5NJ59y

**Pull request closed without merging**
