### PR TITLE
Fix Chiron new TFT SD print after reset

### PR DESCRIPTION
**Pull request by SwiftNick**
### Description
Auto detection of the new style TFT panel on the Anycubic Chiron sometimes fails. 
When this happens you cannot print from SD card and the probing menu doesn't work correctly.
This problem does not occur if the panel type has been defined in the configuration files.

### Requirements
New style (Yellow/Blue) TFT panel.

### Benefits
Auto detection now assumes the new panel is fitted and will revert to the standard panel if this is detected.
The standard panel does not suffer from the inconsistent detection behaviour. 

### Configurations
Requires Anycubic Chiron config files from examples folder with no panel type defined.

### Related Issues
Fixes # https://github.com/MarlinFirmware/Marlin/issues/23853

### CODE REVIEW

**Comment by thinkyhead** [comment]
While we're here, let's see if we can figure out a way to fix the code so that `StatusChange` is not comparing strings to figure out what's going on. In different languages there won't be a "Ready" string to compare with, and if the string is changed to "Okay" it breaks the function. It would be best for the display to keep track of its state changes and respond to those.

There are other ways to tell if a `G29` is in progress. Specifically, there are now ExtUI messages sent when leveling starts and ends. So this display implementation just needs to be updated to handle all the latest ExtUI messages and it should be much happier.

**Comment by SwiftNick** [comment]
It would definitely be cleaner not to rely on strings for state detection.
I did have a look at this a while ago but `onMeshUpdate(const int8_t xpos, const int8_t ypos, probe_state_t state)` is never called.

Looking deeper the Chiron config sets  `AUTO_BED_LEVELING_BILINEAR`. 
There is no call to the ExtUI api from the G29 code in abl.cpp it is only implemented for UBL.
I will alter the Chiron configs and switch to UBL. So this fix will need the matching config updates too.

UBL should make manual levelling easier.

**Comment by thinkyhead** [comment]
> I will alter the Chiron configs and switch to UBL.

ABL also calls into `ExtUI`…
```
Searching 2532 files for "onMeshUpdate" (case sensitive)
. . .
~/Projects/Maker/Firmware/MarlinFirmware/Marlin/src/gcode/bedlevel/abl/G29.cpp:
  323:           TERN_(EXTENSIBLE_UI, ExtUI::onMeshUpdate(i, j, rz));
  534:         TERN_(EXTENSIBLE_UI, ExtUI::onMeshUpdate(abl.meshCount, newz));
  685:             TERN_(EXTENSIBLE_UI, ExtUI::onMeshUpdate(abl.meshCount, z));
```

**Comment by thinkyhead** [comment]
I've added a new `ExtUI` handler for the `onLevelingDone` event and am adding it to the completed/canceled code in all the `G29` handlers.

**Comment by SwiftNick** [comment]
Thanks Scott,
I'll get working on the Chiron bits.

**Comment by SwiftNick** [comment]
@thinkyhead 
I will need some bits from you to completely remove the string checking dependency when probing.

Here are my issues:

There is no API function to report failed probing, only `onStatusChanged("Probing Failed")` so I still need to parse the string message.

`AUTO_BED_LEVELING_BILINEAR`
No call made to `ExtUI::onLevelingDone()`

`AUTO_BED_LEVELING_UBL`
No call made to `ExtUI::onLevelingStart()`

With UBL a nice to have would be an implementation for `G29_RETRY_AND_RECOVER` to fail probing after a few attempts on the same spot.

**Pull request merged**
