### PR TITLE
Support for BIQU B1-SE-Plus strain gauge probe

### PR DESCRIPTION
**Pull request by bigtreetech**
### Description
STRAIN_GAUGE_PROBE  detect the slight deformation caused by pressure after the probe touched the bed. The logic is almost the same as 'FIX_MOUNTED_PROBE', But the strain gauge is high sensitivity, In order to avoid false triggering during XY movement, an enable signal is required, Which only enable the output signal of the probe during z-axis probing.

### Requirements
STRAIN_GAUGE_EN_PIN in motherboard pins.h file is required

### CODE REVIEW

**Comment by thinkyhead** [comment]
Note: The CR-6 SE also has a "strain gauge probe" but for its current configuration we just enable `NOZZLE_AS_PROBE`. That particular device also has the ability to tare, so the `PROBE_TARE` option is also enabled for that machine.

The only distinction for this new type of probe is that there is also a `PROBE_ENABLE_PIN` associated with it. But, almost any type of probe could use such an option. A strain gauge probe could be offset from the nozzle if it was a separate unit, so either `FIX_MOUNTED_PROBE` or `NOZZLE_AS_PROBE` behavior could apply to it. I suggest we don't add a whole new type of probe, but instead just a sub-option such as "`PROBE_HAS_ENABLE_PIN`" to indicate that the probe must be turned on as part of its usage.

**Comment by thisiskeithb** [comment]
I've submitted a corrected B1 SE Plus config here: https://github.com/MarlinFirmware/Configurations/pull/613. I'll also submit a B1 SE config once I verify on real hardware.

**Comment by thisiskeithb** [comment]
I submitted a correction to enforce preheating before probing: https://github.com/MarlinFirmware/Configurations/pull/614, but the strain gauge doesn't seem to work with this new `PROBE_ENABLE_DISABLE` option. I've confirmed the hardware is good with the original B1 SE Plus firmware, but I'll do some more digging.

**Comment by thisiskeithb** [comment]
@thinkyhead Reverting everything back to the original state as BigTreeTech submitted the PR / before clean up, works.

Do you have an SE Plus to debug with? I have a note into BTT's engineer as well.

**Comment by thinkyhead** [comment]
It's still in box, so I'll put it together today.

**Pull request merged**
