### PR TITLE
A4JP name corrections (not AJ4P)

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
Been this way since introduction between RC3 & RC4

Also added a comment section to boards.h with the boards sorted by names

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
@a4jp-com is a person/user.
His printer is a "Scoovo X9H"

**Comment by Bob-the-Kuhn** [comment]
Is this board available to others?  If not I'd rather drop it.

**Comment by thinkyhead** [comment]
The printer is by [abee](http://abee.co.jp) — the [Scoovo X9H](http://abee.co.jp/3dp/scoovo/x9h/). So the folder should be "abee" but references to the author of the config should be "a4jp.com".

**Comment by a4jp-com** [comment]
Yes, this board/printer is available to others and any name changes are okay. I was getting lots of help from @Wackerbarth before and just set up the folders the way he recommended. Without his help I never would have got everything working. I hope I can update the firmware again soon if everything is better than before though. My setup is working as far as I know though ^^

**Comment by thinkyhead** [comment]
Everything is getting better all the time. But that's Springtime, for you.

**Comment by a4jp-com** [comment]
I should be able to try and test any new firmware from this afternoon. ^^

A big thanks to everyone for all the work you have been doing.

**Pull request closed without merging**
