### PR TITLE
Add adaptive fan slowing

### PR DESCRIPTION
**Pull request by InsanityAutomation**
If the part cooling fan is causing the hotend temperature to drop threatening to cause a thermal runaway error, dynamically slow the part cooling fan in an attempt to allow it to recover.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
There are a lot of floating point divides here:
```            if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / 1.25))
              fan_speed[fan_index] = 0;
            else if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / 2))
              fan_speed[fan_index] = (fan_setpoint[fan_index] / 3);
            else if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / 3))
              fan_speed[fan_index] = (fan_setpoint[fan_index] / 2);
            else if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / 4))
              fan_speed[fan_index] = (fan_setpoint[fan_index] / 1.5);
```

I presume GCC will optimize this and turn them into equivalent multiplies.   But do we know that for a fact?   It might be worth while to check the commented assembly code the compiler generates to double check that.

**Comment by InsanityAutomation** [comment]
@Roxy-3D they function where intended at least. Would you prefer I used explicit casts to match the type instead of allowing the compiler to do so implicitly?

**Comment by Roxy-3D** [comment]
My gut hunch is GCC optimizes anything 'simple' like this.   GCC knows floating point divisions are VERY expensive on the AVR's.   My bet is it does the 'Right' thing.    But we don't know that.

And to that thought...    Would it make sense to add a little more 'control' to this.   Something like:
```
#if ENABLED(THERMAL_PROTECTION_HOTENDS)
  //#define ADAPTIVE_FAN_SLOWING     // Slows part cooling fan if temperature begins to drop from setpoint
   //           #DEFINE ADAPTIVE_FAN_SLOWING_FULL_STOP    1.25   // If temperature is off this much, Full stop to the part cooling fan
   //           #DEFINE ADAPTIVE_FAN_SLOWING_SLOW_ALOT    2.0
   //           #DEFINE ADAPTIVE_FAN_SLOWING_SLOW_SOME    3.0
   //           #DEFINE ADAPTIVE_FAN_SLOWING_SLOW_ALITTLE 4.0    // If temperature is off this much, slow the cooling fan down a little bit
#endif
```
which would translate to:
```
        #if ENABLED(ADAPTIVE_FAN_SLOWING) && FAN_COUNT > 0
          if (heater_id >=0) {
            const int fan_index = MIN(heater_id, FAN_COUNT - 1);
            if(fan_setpoint[fan_index] == 0 && fan_speed[fan_index] != 0) fan_setpoint[fan_index] = fan_speed[fan_index];
            if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / ADAPTIVE_FAN_SLOWING_FULL_STOP)
              fan_speed[fan_index] = 0;
            else if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / ADAPTIVE_FAN_SLOWING_SLOW_ALOT2))
              fan_speed[fan_index] = (fan_setpoint[fan_index] / 3);
            else if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / ADAPTIVE_FAN_SLOWING_SLOW_SOME))
              fan_speed[fan_index] = (fan_setpoint[fan_index] / 2);
            else if (current <= tr_target_temperature[fan_index] - (hysteresis_degc / FAN_SLOWING_SLOW_ALITTLE))
              fan_speed[fan_index] = (fan_setpoint[fan_index] / 1.5);
            else
              fan_speed[fan_index] = fan_setpoint[fan_index];
          }
        #endif
```
It may not be worth cluttering up the Configuration_adv.h file with this extra stuff.    But my guess is people that enable #define ADAPTIVE_FAN_SLOWING will have hardware where they need to be able to control the 'aggressive' nature of this code.

Any way...   Something to think about....

**Comment by InsanityAutomation** [comment]
My thought is the code may allay issues manufacturers have enabling thermal protection by preventing most false positives on a shutdown in normal printing conditions and hopefully get better acceptance turning it on from the factory rather than it being for overly aggressive hardware. 

The expensive math can be avoided by making multiple setpoints, setting each temp drop explicitly, however it will still need to calculate the new fan speed to suit. I suppose you could strip even that out by making each setpoint just trigger a ceiling for the fan speed and if its currently above that set it there, but Im not sure we would need to go that far here.

In any case, at least for the moment adjust ability probably is just adding clutter but I wouldnt be opposed to adding it should a few users request it.

The other item is adjustment of fan speed from the menu can hit some fringe cases, however in discussion with @thinkyhead I will be changing some of that code in the menu in a separate PR shortly.

**Comment by InsanityAutomation** [comment]
Obsoleted by #12853

**Pull request closed without merging**
