### PR TITLE
MarlinUI for Creality DWIN (ie. Ender 3 v2)

### PR DESCRIPTION
**Pull request by thinkyhead**
### Description

*I'm still tweaking some things and there are a few TODOs still, but this is at a point that I think it warrants some discussion, testing and a PR.*

A MarlinUI implementation for the DWIN screen included with the Ender 3 v2. Based on Thinkyhead's initial work in #19371.

Includes both landscape and portrait modes, Marlin bootscreen, custom icons and fonts.

Status screen layout is based heavily on the DOGM status screen with some liberties taken for the differences in sizes/ratios.

Landscape:
image

Portrait:
image

Menus:
image

Halted screen:
image

As with #19371, this is enabled with one of two options in `Configuration.h`:
 - `#define DWIN_MARLINUI_PORTRAIT`
 - `#define DWIN_MARLINUI_LANDSCAPE`

Additionally, the LCD will need to be flashed with new assets. See DWIN_SET.zip below.

The fonts are based on the marlin 'fixed' 6x12 BDF font file that I scaled up and manually smoothed out. The resulting HZK does *not* contain the additional 16x16 glyphs, so only ascii 0-127 is supported for this font, currently.

Tested (both landscape and portrait modes):
 - Printing from a host (OctoPrint), including setting progress and remaining time via M73
 - Printing from SD card
 - UBL Mesh Edit menu (visual interactive grid)
 - HALT screen
 - Boot screen
 - Editing values (temp, fan, etc)
 - Moving manually
 - About/Info menu items

While I did start with Thinkyhead's commit, this has diverged quite a ways from that. Notably, I moved some of the code around into different files:
 - `src/lcd/dwin/marlin/ui_common.cpp` - these are the MarlinUI functions that should work for any similar DWIN even at different resolutions, assuming that the proper defines are setup
 - `src/lcd/dwin/marlin/ui_status_480x272.cpp` - these are the MarlinUI functions (mostly the status screen) that will only work for a 480x272 DWIN screen.
 - `src/lcd/dwin/marlin/marlinui_dwin.h` - this was `ultralcd_dwin.h`, but since I split `ultralcd_dwin.cpp` into the above files I think this name is more appropriate

I also created an additional class, `DWIN_String`. This is modeled after `TFT_String` and is used heavily throughout the code to enable sending entire strings at a time instead of single characters. Sending entire strings is *absolutely necessary* in order for the menus to be usable.

TODO:
 - [x] Another clean up pass (remove old commented coded, etc)
 - [x] Smooth the larger font sizes (24x48 and up are still pixelated)
 - [x] `BABYSTEP_ZPROBE_GFX_OVERLAY` / `MESH_EDIT_GFX_OVERLAY`
 - [x] `LCD_SHOW_E_TOTAL`
 - [x] Verify the 'old' UI still works with these changes
 - [x] Add bdf->hzk script

### Requirements

A 480x272 DWIN screen with an encoder, ie. the DWIN included with the Ender 3 v2.

Updating the DWINs assets (see DWIN_SET.zip below)

### Benefits

Implements the standard MarlinUI status screens and menus for this DWIN LCD. Specific features do not require updates to the DWIN assets, etc.

### Configurations

Ender 3 v2 configuration
[Ender3v2.zip](https://github.com/MarlinFirmware/Marlin/files/6704284/Ender3v2.zip)

DWIN firmware and assets (DWIN_SET):
[DWIN_SET.zip](https://github.com/MarlinFirmware/Marlin/files/6704270/DWIN_SET.zip)

edit:
If you come across this PR because you have an Ender 3 v2 and are interested in testing, please do!

If you aren't familiar with how to do that:

1. Get this branch. You can either clone my fork and checkout the `marlinui-crealitydwin` branch . Or, you check it out from your existing clone of the main marlin repo:
   1. First, fetch this pr into a branch: `git fetch origin pull/22211/head:marlinui-crealitydwin`
   2. Then check it out: `git checkout marlinui-crealitydwin`
2. Use your desired Ender 3 v2 configs or start with mine, linked above (Ender3v2.zip).
3. Update your configuration to use the DWIN MarlinUI:
    1. Comment `#define DWIN_CREALITY_LCD`
    2. Uncomment `#define DWIN_MARLINUI_PORTRAIT` or `#define DWIN_MARLINUI_LANDSCAPE`
4. Build and flash as normal
5. Flash the LCD using the files in DWIN_SET.zip above (detailed directions [here](https://github.com/MarlinFirmware/Configurations/tree/release-2.0.9/config/examples/Creality/Ender-3%20V2#updating-the-display) )

### CODE REVIEW

**Comment by thinkyhead** [comment]
Here is the updated `DWIN_SET` for both CrealityUI and MarlinUI, containing the files…
```
0_start.jpg ...... CrealityUI Boot Screen
1_English.jpg  ... CrealityUI English Text
2_Chinese.jpg  ... CrealityUI Chinese Text
3.ICO  ........... MarlinUI Bootscreen bitmaps
4.ICO  ........... MarlinUI Status Screen bitmaps
7.ICO  ........... CrealityUI bitmaps
0T5UIC1.HZK
T5UIC1.CFG
T5UIC1_V20_4页面_191022.BIN
```

[DWIN_SET-combined.tar.gz](https://github.com/MarlinFirmware/Marlin/files/6999162/DWIN_SET-combined.tar.gz)

Applied some fixes for CrealityUI…
- Fixed the "Control" Menu to draw titles from images when `USE_STRING_TITLES` is disabled, following the same pattern as the "Prepare" menu.
- Added the English and Chinese image title for "Advanced Settings."
- Better alignment of editable values with image titles.

More CrealityUI patches later…
- ~~Need to highlight values under "Control" > "Motion" when editing.~~
- Need to add English and Chinese menu titles for the "Advanced Settings" menu
  (Finish #21534)
- Fix "Info" > "Back" so it returns to "Control" when activated from "Control."
- Scrolling Status Message.

**Comment by The-EG** [comment]
Testing this out from bugfix, it appears the fan icon and text got moved around sometime between the last time I tested this out and now:
image

This causes overlap if you have remaining time or SHOW_E_TOTAL enabled.

**Comment by tome9111991** [comment]
hi.
short question.

Remaining time  not shown in PORTRAIT mode?

**Comment by The-EG** [comment]
> Remaining time not shown in PORTRAIT mode?

It did the last time I tested it, but that was before the last round or two of 'tweaks' that went in before merge. I'll see if I can take a look sometime soon.

**Comment by aalku** [comment]
I love you.

**Pull request merged**
