### PR TITLE
BTT SKR MINI E3 in STM32

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

This PR add envs to build SKR MINI E3 boards on the new STM32 Hal.

I don't have this board. I need someone to test it with me.

### Tests

 - [x] LCD after applying #21496 (@ldursw)
 - [x] Serial (@ldursw)
 - [x] BLTouch (@ldursw)
 - [x] Fan Pwm
 - [x] Binary File Transfer (@rhapsodyv)
 - [x] SD Card (@rhapsodyv passed the D101 + D102 test)
 - [x] Speaker
 - [x] Neopixel
 - [x] MeatPack

### Requirements

BTT SKR MINI E3 board.

### Benefits

Maple (old envs) are deprecated and it seems that they are having some timer issues. This is the future! :-)

### CODE REVIEW

**Comment by GhostlyCrowd** [comment]
Posting to say i will test as soon as possible, Friends hardware so i have to wait for his print to finish.

**Comment by thisiskeithb** [comment]
~~I'll be able to test on real hardware this weekend.~~ Just kidding...I have time now!

**Comment by thisiskeithb** [comment]
### ⚠️ CONTROVERSIAL SUGGESTION AHEAD ⚠️

I originally brought in the "512k RCT" environments based on work & initial testing from the community, but I'm wondering if we drop them through this transition and stop allowing users to overflash their boards?

Users could still flash with `STM32F103RE_btt` or `STM32F103RE_btt_USB` environment if they *really* wanted to, so we wouldn't really be removing that ability.

**Comment by GhostlyCrowd** [comment]
> ⚠️ CONTROVERSIAL SUGGESTION AHEAD ⚠️
> 
> I originally brought in the "512k RCT" environments based on work & initial testing from the community, but I'm wondering if we drop them through this transition and stop allowing users to overflash their boards?
> 
> And that's not entirely accurate since users could still flash with `STM32F103RE_btt` or `STM32F103RE_btt_USB` environment if they wanted to, so we wouldn't really be removing that ability.

you're going to be pulling the rug out from under a lot of users who have 512k and expect it. I get your logic on this, but for users like my self where I used a stlink to read write and verify the whole 512K on the STM32F103RE on the SKR Mini E3 1.2 and its been working perfect for all this time, pulling the rug out means I'm going to have to chop off some config options for the platform I support for my friend.  You're going to have people like me who want that special case environment because its usable and verified as such. 

But again i get your angle and for trouble shooting and of course people are over flashing chips that cant actually take it.

**Comment by thisiskeithb** [comment]
> you're going to be pulling the rug out from under a lot of users who have 512k and expect it

You can still use `STM32F103RE_btt` or `STM32F103RE_btt_USB` (512k environments) to overflash your 256k chip, so that wouldn't change. This would simply clean up the codebase a bit.

**Comment by GhostlyCrowd** [comment]
> > you're going to be pulling the rug out from under a lot of users who have 512k and expect it
> 
> You can still use `STM32F103RE_btt` or `STM32F103RE_btt_USB` to overflash your 256k chip, so that wouldn't change. This would simply clean up the codebase a bit.

Ah got you now, misunderstood. this is reasonable I guess.  they are essentially the same. 
Might cause some confusion in the early days of the switch, but when are we all not confused just a bit?

**Comment by thisiskeithb** [comment]
> Might cause some confusion in the early days of the switch

I'm continuing discussion with rhapsodyv on Discord, but it'd just need a callout in the release notes if/when it happens.

It'd be nice for consistency since we don't have these special overflashing environments for other RCT-based boards.

**Comment by GhostlyCrowd** [comment]
> > Might cause some confusion in the early days of the switch
> 
> I'm continuing discussion with rhapsodyv on Discord, but it'd just need a callout in the release notes if/when it happens.
> 
> It'd be nice for consistency since we don't have these special overflashing environments for other RCT-based boards.

I agree entirely, just using my moment of confusion as an example of such. You suggestion is reasonable, and probably for the best, we have to stream line things eventually, why not on a major platform change if not now when?

**Comment by thisiskeithb** [comment]
This was discussed on Discord, but I figured i'd post information here as well.

I found my SKR Mini E3 V1.2 (emulated EEPROM) and threw it on the power supply with the latest changes (88462ce) using the base BTT E3 V1.2/Ender-3 config using `STM32F103RC_btt_stm32` through `STM32F103RC_btt_512k_USB_stm32` and it won't boot.

I'll have to get an ST-Link on it and see if I can collect some more feedback. I'll also try disabling some features to see if there's a hangup somewhere there as well.

**Comment by GhostlyCrowd** [comment]
> This was discussed on Discord, but I figured i'd post information here as well.
> 
> I found my SKR Mini E3 V1.2 (emulated EEPROM) and threw it on the power supply with the latest changes ([88462ce](https://github.com/MarlinFirmware/Marlin/commit/88462cede3cfde153c123bd32b48f8bd0d49156a)) using the base BTT E3 V1.2/Ender-3 config using `STM32F103RC_btt_stm32` through `STM32F103RC_btt_512k_USB_stm32` and it won't boot.
> 
> I'll have to get an ST-Link on it and see if I can collect some more feedback. I'll also try disabling some features to see if there's a hangup somewhere there as well.

Interesting I'm getting a timers in use conflict on ` STM32F103RC_btt_512K_USB_stm32` 

```
Compiling .pio\build\STM32F103RC_btt_512K_USB_stm32\src\src\HAL\shared\backtrace\unwinder.cpp.o
Marlin\src\HAL\STM32\timers.cpp:320:40: error: static assertion failed: One or more timer conflict detected. Examine "timers_in_use" to help identify conflict.
  320 | static_assert(verify_no_timer_conflicts(), "One or more timer conflict detected. Examine \"timers_in_use\" to help identify conflict.");
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~^~
Compiling .pio\build\STM32F103RC_btt_512K_USB_stm32\src\src\HAL\shared\backtrace\unwmemaccess.cpp.o
*** [.pio\build\STM32F103RC_btt_512K_USB_stm32\src\src\HAL\STM32\timers.cpp.o] Error 1
```

**Comment by thisiskeithb** [comment]
I just copied & pasted configs from https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%201.2

You'll have to tweak the `SERIAL_PORT*` settings depending on which environment you're compiling for.

**Comment by GhostlyCrowd** [comment]
> I just copied & pasted configs from https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3/BigTreeTech%20SKR%20Mini%20E3%201.2
> 
> You'll have to tweak the `SERIAL_PORT*` settings depending on which environment you're compiling for.

This works, but my configs do not which means im using something that depends on a timer thats conflicted. The configs are currently working now on Maple 2.1 with ststm32 6.1

**Comment by rhapsodyv** [comment]
Timer are dependent of the config: more features, more timers.

I didn’t play with the timers setup yet. But that will be easy when we get it booting.

but we need someone with a stlink or jlink, to debug step by step and see where it’s failing.

**Comment by thisiskeithb** [comment]
> Timer are dependent of the config: more features, more timers.

Bingo!

> but we need someone with a stlink or jlink, to debug step by step and see where it’s failing.

I'll get it setup shortly. 🙂

**Comment by GhostlyCrowd** [comment]
> Timer are dependent of the config: more features, more timers.
> 
> I didn’t play with the timers setup yet. But that will be easy when we get it booting.
> 
> but we need someone with a stlink or jlink, to debug step by step and see where it’s failing.

Agreed, Spooky thing, Deleted my .pio folder and no more conflict it compiled. 

I have a STLink but no access to the board, if no one else can I'll order a SKR E3 Mini, I have no use for it now but id like to see this through.

**Comment by thisiskeithb** [comment]
> I have a STLink but no access to the board

I have a 1.2 and 2.0 board here and an ST-link, so no worries. It’s a little painful, but rhapsodyv and I can do some remote testing/debugging this week.

**Comment by thisiskeithb** [comment]
After some testing last night using a mostly stock Ender-3/SKR Mini E3 V1.2 config & Marlin build (had to change some things to get ST-Link debugging working), I was running into boot issues when the LCD was enabled:

<details><summary>gdb backtrace:</summary>

```log
#0  WWDG_IRQHandler () at /Users/keith/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f103xe.s:114
#1  <signal handler called>
#2  pinMode (ulPin=ulPin@entry=23, ulMode=ulMode@entry=1) at /Users/keith/.platformio/packages/framework-arduinoststm32/cores/arduino/wiring_digital.c:31
#3  0x08013b10 in u8g_dev_rrd_st7920_128x64_fn (u8g=0x200009e4 <u8g+8>, dev=0x2000006c <u8g_dev_st7920_128x64_rrd_sw_spi>, msg=<optimized out>, arg=0x0) at Marlin/src/lcd/dogm/ultralcd_st7920_u8glib_rrd_AVR.cpp:123
#4  0x0802240a in u8g_InitLL (u8g=u8g@entry=0x200009e4 <u8g+8>, dev=0x2000006c <u8g_dev_st7920_128x64_rrd_sw_spi>) at .pio/libdeps/STM32F103RC_btt_stm32/U8glib-HAL/src/clib/u8g_ll_api.c:53
#5  0x080224fc in u8g_Begin (u8g=u8g@entry=0x200009e4 <u8g+8>) at .pio/libdeps/STM32F103RC_btt_stm32/U8glib-HAL/src/clib/u8g_ll_api.c:191
#6  0x08022544 in u8g_InitSPI (u8g=u8g@entry=0x200009e4 <u8g+8>, dev=<optimized out>, sck=<optimized out>, mosi=<optimized out>, cs=24 '\030', a0=255 '\377', reset=255 '\377') at .pio/libdeps/STM32F103RC_btt_stm32/U8glib-HAL/src/clib/u8g_ll_api.c:255
#7  0x08021f50 in U8GLIB::initSPI (this=this@entry=0x200009dc <u8g>, dev=<optimized out>, sck=sck@entry=25 '\031', mosi=mosi@entry=23 '\027', cs=<optimized out>, cs@entry=24 '\030', a0=<optimized out>, a0@entry=255 '\377', reset=<optimized out>, reset@entry=255 '\377')
    at .pio/libdeps/STM32F103RC_btt_stm32/U8glib-HAL/src/U8glib.cpp:45
#8  0x08012b5e in U8GLIB::U8GLIB (reset=255 '\377', a0=255 '\377', cs=24 '\030', mosi=23 '\027', sck=25 '\031', dev=<optimized out>, this=0x200009dc <u8g>) at .pio/libdeps/STM32F103RC_btt_stm32/U8glib-HAL/src/U8glib.h:75
#9  U8GLIB_ST7920_128X64_RRD::U8GLIB_ST7920_128X64_RRD (reset=255, cs=24, mosi=23, sck=25, this=0x200009dc <u8g>) at Marlin/src/lcd/dogm/HAL_LCD_class_defines.h:63
#10 __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at Marlin/src/lcd/dogm/marlinui_DOGM.cpp:79
#11 _GLOBAL__sub_I_u8g () at Marlin/src/lcd/dogm/marlinui_DOGM.cpp:472
#12 0x08022c30 in __libc_init_array ()
#13 0x08009266 in Reset_Handler () at /Users/keith/.platformio/packages/framework-arduinoststm32/system/Drivers/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/startup_stm32f103xe.s:97
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
</details>

After cherry picking the U8glib fixes from https://github.com/MarlinFirmware/Marlin/pull/21496, it now boots and I can use the screen! I'll get it into a printer for a more complete build with things like `SPEAKER`, `BLTOUCH`, `NEOPIXEL_LED`, etc. enabled to see if there are any potential issues.

**Comment by rhapsodyv** [comment]
> > This was discussed on Discord, but I figured i'd post information here as well.
> > I found my SKR Mini E3 V1.2 (emulated EEPROM) and threw it on the power supply with the latest changes ([88462ce]

Can you share your config that generate the timer conflict?

**Comment by GhostlyCrowd** [comment]
> Can you share your config that generate the timer conflict?

I did removed my .pio folder and did a clean rebuilt and it disappeared, if it comes back i will let you know, unless you still want the configs? let me know.

**Comment by GhostlyCrowd** [comment]
> After some testing last night using a mostly stock Ender-3/SKR Mini E3 V1.2 config & Marlin build (had to change some things to get ST-Link debugging working), I was running into boot issues when the LCD was enabled:
> 
> gdb backtrace:
> After cherry picking the U8glib fixes from #21496, it now boots and I can use the screen! I'll get it into a printer for a more complete build with things like `SPEAKER`, `BLTOUCH`, `NEOPIXEL_LED`, etc. enabled to see if there are any potential issues.

Can you confirm USB is working and the host can see the SD as mass storage? if this is the case then i can have my friend test as well as he will be able to flash and reflash with out disassembling the whole rig.

**Comment by thisiskeithb** [comment]
> Can you confirm USB is working and the host can see the SD as mass storage? if this is the case then i can have my friend test as well as he will be able to flash and reflash with out disassembling the whole rig.

You just need to remove the microSD card to load the firmware, so there shouldn't be any reason to tear anything apart...

Enabling `SDSUPPORT` causes the 1.2 board to not boot, so I'm working with rhapsodyv to figure out why. He'll also have an SKR Mini E3 V2 board in a day or so which should move debugging along more quickly.

**Comment by sl1pkn07** [comment]
For the real 512K envs (RET), instead of using a STlinlk for program the board. why not Marlin privides a custom bootloader like the original RCT without the >256K restriction?

i have modified one (form bootloader created by a guy in the ST forums). but only work the first time (only work if the firmware is flashed the first time, flash new firmware not works)

https://github.com/sl1pkn07/SKR_E3_DIP_Bootloader

greetings

**Comment by GhostlyCrowd** [comment]
> > Can you confirm USB is working and the host can see the SD as mass storage? if this is the case then i can have my friend test as well as he will be able to flash and reflash with out disassembling the whole rig.
> 
> You just need to remove the microSD card to load the firmware, so there shouldn't be any reason to tear anything apart...
> 
> Enabling `SDSUPPORT` causes the 1.2 board to not boot, so I'm working with rhapsodyv to figure out why. He'll also have an SKR Mini E3 V2 board in a day or so which should move debugging along more quickly.

The board is mounted in an inaccessible location where the  printer has to be tipped over, the whole bottom plate taken off and then recalibration has to happen every time this is done lol 

So SD support and being able to have USB accessible by the host so we can push firmware to the SD via it appearing as a USB flash disk on the host like it currently is on the stm32f1 build is a must in order for my friend to let me test this on his rig lol

**Comment by rhapsodyv** [comment]
I fixed the env, the SD, the LCD, the USB... I think everything is working now, except the `_USB` envs, because a stm32duino issue. Here: https://github.com/stm32duino/Arduino_Core_STM32/pull/1088#issuecomment-812656069

I will fix the _USB env later, as the name of the class will change and I need update more places to use the new name...

**Comment by thisiskeithb** [comment]
> I think everything is working now, except the _USB envs

USB mass storage support pretty important to users of these boards, but it's the lesser of two evils when compared to the timer changes & conflicts under the STM32F1 HAL.

**Comment by rhapsodyv** [comment]
It's on top of my list.

But I need to change the usb class name in stm32duino. That will impact all usb mass storage code on stm32. So I prefer do it in a separated PR.

**Comment by thisiskeithb** [comment]
No worries! I just wanted to make sure you knew those were commonly used & we'd hear about it if those went missing 😆

**Comment by ldursw** [comment]
I used this PR as a starting point and managed to port the MKS Robin E3 board to STM32.

- Working
  - LCD after applying #21496
  - Serial
  - BLTouch
- Broken
  - Binary File Transfer (stops randomly)
- Not tested
  - SD Card (it is detected but I didn't try printing from it)
  - Speaker
  - Neopixel
  - MeatPack

When I enabled the BLTouch support I had a timer conflict with `TP_TEMP`. Changing `TIMER_SERVO` from `TIM2` to `TIM5` compiled successfully and it works as expected.

I noticed that the fans and heatbed now have an audible noise when PWM is active. I guess the frequency is higher than it was with STM32F1. For now I'm using `FAST_PWM_FAN` and `FAST_PWM_FAN_FREQUENCY 30` to work around it.

If you prefer that I open a separate issue let me know. As both boards use the same microcontroller I though it would be appropriate to post here.

The changes are in ldursw/Marlin@4690681. I'll open a PR once #21496 and this one are merged.

**Comment by rhapsodyv** [comment]
Thanks for your testing.

I will test the SD related stuff (binary transfer, meat pack, etc). I added some gcode for testing it sometime ago. I will add the timer settings.

I added a task in my list to understand the differences with pwm between stm32f1 and stm32 Hals. I already did it with other features, to better match the two Hal and make migration easy.

It's a big opportunity to start using stm32.
All f4 boards already use it.

**Comment by rhapsodyv** [comment]
@ldursw I added a test task list in the PR description, so we can keep track of it.

**Comment by rhapsodyv** [comment]
I tested `BINARY_FILE_TRANSFER` and it's fully working for me... I just need make sure the file name I'm transferring have a valid 8.3 name.

**Comment by ldursw** [comment]
I did some more tests and I don't think there's an issue with BFT itself. It periodically shows `Packet corrupted` errors during transfer. The serial connection seemed to be working with a simple object but when I started printing a more complex one there were a few resends just minutes after starting. I'll investigate further about the serial corruption.

To reiterate I'm testing on a MKS Robin E3, not a SKR MINI E3.

**Comment by rhapsodyv** [comment]
MKS Robin E3 uses the same envs?

**Comment by ldursw** [comment]
Both use the STM32F103RCT6 microcontroller but the platformio env is different. The SKR MINI E3 uses USB serial whereas the Robin E3 uses hardware serial and CH340G. The pinout is also different.

I'll figure out what is happening with this board. I just wanted to comment to help the work on F103Rxx running on the STM32 HAL. If I'm doing more harm than good and causing confusion please let me know.

**Comment by rhapsodyv** [comment]
> Both use the STM32F103RCT6 microcontroller but the platformio env is different. The SKR MINI E3 uses USB serial whereas the Robin E3 uses hardware serial and CH340G. The pinout is also different.
> 
> I'll figure out what is happening with this board. I just wanted to comment to help the work on F103Rxx running on the STM32 HAL. If I'm doing more harm than good and causing confusion please let me know.

No no, that is good.

**Comment by thisiskeithb** [comment]
I just found another related issue that this PR should help with: https://github.com/MarlinFirmware/Marlin/issues/20670

**Comment by rhapsodyv** [comment]
I think we can merge this to let more users test.

**Comment by rhapsodyv** [comment]
> For the real 512K envs (RET), instead of using a STlinlk for program the board. why not Marlin privides a custom bootloader like the original RCT without the >256K restriction?
> 
> i have modified one (form bootloader created by a guy in the ST forums). but only work the first time (only work if the firmware is flashed the first time, flash new firmware not works)
> 
> https://github.com/sl1pkn07/SKR_E3_DIP_Bootloader
> 
> greetings

I’m working in a generic bootloader for any stm32 chip. It should work with any board supported by stm32duino with SPI SD.

Here: https://github.com/rhapsodyv/OpenBLT-STM32

If you want try it, you can call me on discord.

**Comment by qwewer0** [comment]
Before:
```
RAM:   [===       ]  30.1% (used 14792 bytes from 49152 bytes)
Flash: [====      ]  44.9% (used 235412 bytes from 524288 bytes)
```

After:
```
RAM:   [===       ]  28.5% (used 14000 bytes from 49152 bytes)
Flash: [========  ]  84.4% (used 221268 bytes from 262144 bytes)
```

14144 byte reduction
Awesome work!

**Comment by GhostlyCrowd** [comment]
Curious is USB working now? IE Host mountable SD card via the usb connection for file transfer.

**Comment by rhapsodyv** [comment]
Usb works. But not usb media sharing (_USB env) yet, because I'm waiting a reply from stm32duino.

**Comment by GhostlyCrowd** [comment]
> Usb works. But not usb media sharing (_USB env) yet, because I'm waiting a reply from stm32duino.

Yea i saw your PR on stm32duino is kinda hanging out still. I'll wait since i'm a niche case and depend on that for flashing firmware with out having to play bob the builder on the printer lol

**Comment by rhapsodyv** [comment]
Soon I may send the _USB fixes.

**Comment by Taomyn** [comment]
So far so good for my v1.2 board (512k_stm32), even allows me to drop my modded library for NeoPixel support as 1.8 seems to have fixed the issues, and all previous lighting options working perfectly. So yes, contrary to the sanity check, they do work with this board with no special changes.

**Comment by thisiskeithb** [comment]
> So yes, contrary to the sanity check, they do work with this board with no special changes.

That sanity check is there because NeoPixel support is iffy on *most* boards under the STM32F1 HAL.

> So far so good for my v1.2 board (512k_stm32)

Also you’re compiling with `STM32F103RC_btt_512K_stm32` which is under the STM32 HAL and not `STM32F103RC_btt_512K` which is under the STM32F1 HAL so you don’t need to modify anything.

The goal is to retire the current SKR Mini envs under the STM32F1 HAL due to all the issues & lack of PIO support in the future.

**Comment by Taomyn** [comment]
> > So far so good for my v1.2 board (512k_stm32)
> 
> Also you’re compiling with `STM32F103RC_btt_512K_stm32` which is under the STM32 HAL and not `STM32F103RC_btt_512K` which is under the STM32F1 HAL so you don’t need to modify anything.
> 
> The goal is to retire the current SKR Mini envs under the STM32F1 HAL due to all the issues & lack of PIO support in the future.

I don't get the question, the _stm32 build options only just appeared the past few releases so I switched to it today to see if they worked for me.

image

**Comment by thisiskeithb** [comment]
> I don't get the question, the _stm32 build options only just appeared the past few releases so I switched to it today to see if they worked for me.

There's no question. I was just clarifying the reason for the sanity check & the differences with these new build options. The `*_stm32` environments will be the future for the SKR Mini E3 boards.

We appreciate the testing!

**Comment by Yoghoo** [comment]
> There's no question. I was just clarifying the reason for the sanity check & the differences with these new build options. The `*_stm32` environments will be the future for the SKR Mini E3 boards.
> 
> We appreciate the testing!

I successfully compiled with the STM32F103RC_btt_512K_stm32 environment. But I see the "We appreciate the testing!" comment. Does this mean that this is still in a testing phase or is it ready for production use?

Don't mind a little testing but do want to know what to expect.

*Edit*

Here some numbers btw:

Old:
RAM:   [====      ]  36.3% (used 17832 bytes from 49152 bytes)
Flash: [====      ]  38.9% (used 204044 bytes from 524288 bytes)

New:
RAM:   [====      ]  35.3% (used 17372 bytes from 49152 bytes)
Flash: [====      ]  36.7% (used 192424 bytes from 524288 bytes)

So it's a little smaller which is always good. What I don't like that it needs 1 Gb of new packages on my PC. That's twice the amount it needed for the old environment.

**Comment by Doogiy** [comment]
Dude, this fixed the issues with my SKR Mini E3 V2.0 where it was stopping mid-print, and stopping during ABL with the bed heater on. Just finished a 5 hour print, no issues. Thank you, so much! I love this board but with all of the power failing issues, I was about to yank it out of my Ender 3 Max. I'm using this environment with 2.0.8.1. I have the TFT35 E3 V3.0, also. (For anyone referencing)

**Comment by Doogiy** [comment]
> Dude, this fixed the issues with my SKR Mini E3 V2.0 where it was stopping mid-print, and stopping during ABL with the bed heater on. Just finished a 5 hour print, no issues. Thank you, so much! I love this board but with all of the power failing issues, I was about to yank it out of my Ender 3 Max. I'm using this environment with 2.0.8.1. I have the TFT35 E3 V3.0, also. (For anyone referencing)

Printed 3 times flawlessly. Only issue: my TFT35 doesn't read out the fan speed on the status screen that the slicer GCODE sets. The fans physically come on, but the screen shows 0%. I can go in and set a percentage, and it shows what I set. I can enter M106 S255 and it reads out 100%, as well. It ONLY does this in the touchscreen mode. (Maybe I need to update the BTTTFT35 firmware?) Marlin mode is perfecto. No complaints here. I'm just happy it's completing prints.

**Comment by Doogiy** [comment]
Didn't change anything.. Not sure why this started, but now its powering off during ABL with the bed heater on. This only happens when the command is sent outside of a GCODE file. If I run a print with it, it works just fine. I think I'm just going to make a GCODE file for the ABL sequence lmao

**Comment by GhostlyCrowd** [comment]
> Didn't change anything.. Not sure why this started, but now its powering off during ABL with the bed heater on. This only happens when the command is sent outside of a GCODE file. If I run a print with it, it works just fine. I think I'm just going to make a GCODE file for the ABL sequence lmao

I'm not seeing this, what kind of ABL you using? I'm currently testing UBL and it seems to be working fine, 

In fact this is working amazing i cant wait for usb media sharing

**Comment by rhapsodyv** [comment]
`_USB` env support was merged in bugfix

**Comment by 00ihsan** [comment]
Hi,

I have a SKR MINI E3 V2.0 board with a STM32103RC chip. To use NeoPixel i need to compile for the stm env. however, the software is not optimized enough. Great alternative is using maple but than my NeoPixels won't work. Any ideas?

**Pull request merged**
