### PR TITLE
[1.1.x] Add korean Support

### PR DESCRIPTION
**Pull request by portalab**
Add korean Support

### Requirements
You need a FULL GRAPHIC CLCD 

### Description

This feature supports Korean CLCD on FULL GRAPHIC LCD likes RepRapDiscount FULL GRAPHIC Smart Controller

Font : Copyright (c) 2010, NAVER Corporation (https://www.navercorp.com/) , NanumGothic, SIL OPEN FONT LICENSE

### Benefits

You cau use Korean UI on GLCD

(Main Info)

(On Thermal Runaways)
### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/15629

### CODE REVIEW

**Comment by boelle** [comment]
please send this to the 2.0.x branch instead, the other branches do not get updates anymore

**Comment by portalab** [comment]
This PR is for user who wants to use korean in 1.1.x version. Many People still use 1.1.x version but Not support korean (only in 2.0.x). So It would be great if other korean users still in 1.1.x use this contribution. :)

**Comment by boelle** [comment]
but 1.1.x version will not get more updates,

why not use 2.0.x if it has korean? its both 8 bit and 32 bit

**Comment by portalab** [comment]
I think marlinfw is great and many people use them, but some people (at lease my frineds) they aren't professional. they don't have programming or engineering skills. and they depend on manafactures's stock firmware come's out together and many forum's problem solving reference. 
So It is so hard to makes  configuration files themselves and solve problem if they have. In this situation I want to makes more easier using  3D printer for legacy korean user.

**Comment by thinkyhead** [comment]
Thanks @portalab ! — While there may not be a formal 1.1.x release planned, we continue to accept fixes to breaking issues in `bugfix-1.1.x` and anything that fills in a missing piece without adding a whole new feature. This qualifies as a welcome enhancement, and your work is appreciated. Will merge soon…

**Pull request merged**
