### PR TITLE
Fix for Meshpositions if printer has negative endstop positions

### PR DESCRIPTION
**Pull request by oderwat**
There may be different ways to fix that but I believe this is the best universal solution.

### CODE REVIEW

**Comment by fiveangle** [comment]
Perhaps review #5581 for the discussion of how @thinkyhead wanted to accomplish stuff like this ?

**Comment by oderwat** [comment]
A well. I forgot about Delta (even when I own one...) I will think about a saver way to do it

**Comment by thinkyhead** [comment]
I don't see what this is meant to fix.

**Comment by oderwat** [comment]
If you have the min values (because of the endstops) at say -33 for X and -16 for Y, so that your left front edge of the bed is 0/0 and then try to use manual mesh leveling, the calculated values for the mesh are outside the bed area.

**Comment by oderwat** [comment]
I think it would be helpfull to distinguish between "reachable" and "printable" positions. So you could say: I have: min stop + 20 (air) + 200 (bed) + 10 (air) + max (without crash) + endstop max. Then one endstop needs to be the "homing" endstop. The other is optional. This way one could define probe and mesh offsets more correctly. For Delta this is not needed because of the square mesh.

**Comment by thinkyhead** [comment]
I agree that the `MESH_INSET` stuff is hackish. We can now sanity-check using the probe offsets to determine what's reachable. But let's merge this for now and see whose systems it breaks.

**Comment by thinkyhead** [comment]
In the long run this logic is also flawed:
```cpp
#if X_MIN_POS < 0
```
…because `X_MIN_POS` may be less than zero on *any* machine for *various* reasons.
And of course it is *always* less than zero on delta.

**Comment by oderwat** [comment]
Well. I would not have merged it. It is flawed and I already wrote it breaks on delta. I thought this PR could be used to discuss a better method actually.

**Comment by thinkyhead** [comment]
I went on a merge-frenzy yesterday. Oops!

**Pull request merged**
