### PR TITLE
Some minor cleanups to code formatting

### LINKED ISSUE #6472: Compiler warning
I've been seeing this warning in the latest BugFix (I update it almost every day) for a few weeks now. Compiling with Arduino IDE 1.8.2.

```
In file included from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\MarlinConfig.h:27:0,

                 from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\Marlin.h:36,

                 from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp:47:

C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp: In static member function 'static void Stepper::init()':

C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\macros.h:123:37: warning: invalid conversion from 'volatile void*' to 'void*' [-fpermissive]

 #define ZERO(a) memset(a,0,sizeof(a))

                                     ^

C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp:1102:5: note: in expansion of macro 'ZERO'

     ZERO(e_steps);

     ^

In file included from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\Marlin.h:28:0,

                 from C:\Users\jbwin\AppData\Local\Temp\arduino_build_210250\sketch\stepper.cpp:47:

c:\program files (x86)\arduino\hardware\tools\avr\avr\include\string.h:235:14: note: initializing argument 1 of 'void* memset(void*, int, size_t)'

 extern void *memset(void *, int, size_t);

              ^
```

Everything appears to be working ok, but I hate warnings. ;-)

Thanks.

### PR DESCRIPTION
**Pull request by thinkyhead**
- Combine grouped case statements
- Use new serial spacing function to save PROGMEM
- Adjust spacing for casts and others
- Resolve #6472

### CODE REVIEW

**Comment by Roxy-3D** [comment]
```cpp
    const bool inf_normalized_flag = isinf(e_normalized_dist),
                       inf_m_flag = isinf(m);
```
I wasn't sure if the order of evaluation for pre-initialized variables is as the compiler sees them.   That is why I put them outside of the declaration.   e_normalized_dist and m need to be evaluated prior to assigning these flags.     So this is safe to do?

**Comment by thinkyhead** [comment]
> I wasn't sure if the order of evaluation for pre-initialized variables…

The `const` keyword simply indicates that a variable will not be altered once assigned. It is not "pre-initialized." The `constexpr` keyword, however, requires the assigned value to be determinable at compile-time.

**Comment by thinkyhead** [comment]
> I wasn't sure if the order of evaluation for pre-initialized variables…

The `const` keyword simply indicates that a variable will not be altered once assigned, and gives the compiler an optimization hint. It does not cause a variable to be "pre-initialized." (I presume you mean, at compile-time.)

If a `const` variable is invariant, assigned to a constant value, and can be determined at compile-time, the compiler may treat it like `constexpr`.

`static const` is generally used in that case, unless the `const` value needs to be accessible in a separate compilation unit.

The `constexpr` keyword requires that the assigned value _must_ be determinable at compile-time (unlike `const`), and `constexpr` values are treated similarly to constants by the compiler. (Though you cannot refer to them in preprocessor expressions like `#if`.)

**Comment by Roxy-3D** [comment]
No...  Maybe we are looking at things differently.  But when I look at:
```cpp
   const float e_normalized_dist = e_position / on_axis_distance,
                z_normalized_dist = z_position / on_axis_distance;
    const float m = dy / dx,
                c = start[Y_AXIS] - m * start[X_AXIS];
   const bool inf_normalized_flag = isinf(e_normalized_dist),
                       inf_m_flag = isinf(m)
```
what I see is the compiler is being told to allocate storage (of type const bool) for multiple variables.   But to do that, it has to call a function called isinf() with parameters that are also in the pre-initialized list (on a preceding declaration).   That is why I thought it was safer to explicitly assign them rather than pre-initialize them.   

> (I presume you mean, at compile-time.)

Yes...   The compiler is being told to assign a value to these variables before they are used.  I know the 'right' thing will happen if I assign them.   I wasn't sure if the order of evaluation guaranteed that e_normlized_dist and m were known at the time this storage was set aside.

**Pull request merged**
