### PR TITLE
[1.1.x] Segmented manual moves for kinematics

### PR DESCRIPTION
**Pull request by thinkyhead**
Derived from #7894, with changes limited to kinematic robots.

This should block less, as it allows movement to accrue even if segmented moves fill the planner.

### CODE REVIEW

**Comment by tcm0116** [comment]
>This should block less, as it allows movement to accrue even if segmented moves fill the planner.

Unfortunately, this won't work. `Planner::_buffer_line` calls `idle()` if the buffer is full, which could allow `lcd_move_[x|y|z|e]` to be called if the encoder is turned while `manage_manual_move` is still being blocked by the previous move. If this happens, when the first call to `prepare_move_to_destination` completed, it will update `current_position`. The second queued movement will then be erroneous because the offset was based on the `current_position` from prior to the first call to `prepare_move_to_destination`. This will result in the printer going into an oscillation, which is exactly what happened when I was working on #7894.

Another issue is that in `manage_manual_move`, you're modifying `current_position` and then calling `set_destination_to_current`. The subsequent call to `prepare_move_to_destination` will compare `current_position` to `destination` and determine that nothing has changed, and will not segment the move, thus defeating the while purpose of this change. I **strongly** recommend that we disallow modification of `current_position` in order to command a movement as it breaks Delta and SCARA segmentation.

**Comment by thinkyhead** [comment]
> Unfortunately, this won't work.

Elements of it will work. But you're right that it can't overwrite `current_position` ahead of the move because it causes the movement functions to see no movement. So, that value will have to be stored elsewhere!

> disallow modification of current_position in order to command a movement

That might be hard, since it is a common paradigm throughout the code. The problematic side-effect is that `current_position` is being stepped on by `prepare_move_to_destination`, and the LCD movement functions also desire to utilize it.

An alternative would be to capture the axis current position at the start of axis movement and use that value rather than `current_position` for tracking the new position. That value would be guaranteed not to be stepped on by `prepare_move_to_destination`.

**Comment by tcm0116** [comment]
>An alternative would be to capture the axis current position at the start of axis movement and use that value rather than current_position for tracking the new position.

⁣i don't think that is feasible because of the possibility of having multiple calls to `manage_manual_move` on the stack due to the call to `idle()` in `Planner::_buffer_line`.

I think the most straight forward way to accomplish what you're looking for is to ensure that `prepare_move_to_destination` doesn't block if there's not enough room in the planner's buffer to hold the segments. This way, `current_position` can always be used as a reliable reference point for the movement since it will be updated if the movement is successfully queued, and not if it isn't. ​

**Comment by thinkyhead** [comment]
Hmm, given the way the LCD moves are set up, it makes it hard to work around all the issues to get a simple single-axis manual move system that works well for both cases. Fortunately, we just ignore whether there are other moves going on, such as a `G1` that might get sent in the middle of Axis Move. That keeps it simpler.

So, to get the working segmented moves, I'll revert this back one commit, to the point before attempting to allow concurrent added moves. That should then work. It has the fixed setting of `destination`, plus the needed imports. — I'll revert the other PR back to the same point so it works as originally designed.

----
To fix the issues that make it harder to do manual moves, I propose a simple interim solution. I originally wrote the manual move manager that we're using today, with the `manual_move_axis` flag to indicate which axis, if any, is moving. And then the display code uses `current_position[manual_move_axis]` to get the value for display. Instead, it should be made so that when you start to edit XYZE, a copy of the `current_position` for that axis is made, and then all lcd manual movement code can just use that value.

That would allow value editing to continue, leaving only last coordinate value waiting until segment processing is done.

Anyway, let me revert this, and we can go from there…

**Pull request merged**
