### PR TITLE
Error in latest release

### PR DESCRIPTION
**Pull request by rockman44181000**
### Requirements

#define DEFAULT_AXIS_STEPS_PER_UNIT   {80.000,80.000,4000.000,93.00}  // default steps per unit 

### Benefits

Changing it to 400 Steps for the Z axis will prevent this from occurring. And if people want to go faster, it provides a safety margin.

### CODE REVIEW

**Comment by swilkens** [comment]
Even though this PR is faulty, it looks like this happened here by @thinkyhead:

https://github.com/MarlinFirmware/Marlin/commit/b4d48fdc917cb89d89187c8b95b97cda9ae2c08d#diff-8270513bcf2a548cd418cdfe123f27d3R719

**Comment by thisiskeithb** [comment]
The default config is for an Ultimaker, which has 4000 steps/mm for Z, but you should [use a pre-built printer config](https://github.com/MarlinFirmware/Configurations) or build one to match your specific hardware.

**Comment by ellensp** [comment]
"wants to merge 1,837 commits into 2.0.x from bugfix-1.1.x"
This is just wrong...
You can't commit to 2.0.x you can only commit to bugfix. 
also you definitely shouldn't be trying to push old 1.1.x onto anything 2.0

**Comment by Roxy-3D** [comment]
487 files changed in this commit?     

This can't be merged.

And the only place things get changed (or merged) is into BugFix v2.0.x

**Comment by rockman44181000** [comment]
I got it, but there is no mention in the download package up front that says Marlin 2.0.5.3 is specifically designed for the Ultimaker. That's what screws a lot of us up, we think we're getting a Universal Package and not one for One Party Only. Make that Perfectly Clear to those of us who aren't Programming Wizards. Furthermore, changing the Steps per for the Z-Axis from 4000 to 400 for those of us who aren't working on an Ultimaker does Nothing. I had to go into Advanced Configuration on my LCD and spend 5 minutes Dialing it down from 4000 to 400. Because even setting it up in the firmware for 400, it over wrote it to 4000. Everything else worked except Manual Mesh, because when I try and use it, I get No Response.

**Comment by randellhodges** [comment]
Steps per mm are stored in the configuration in the eeprom. Making a change to the firmware and uploading it won't override what's in your eeprom. You either need to use the UI to change it, or reload your eeprom from the hard coded defaults (which is what you specify with you change the firmware)

If you have something like octoprint installed, you can execute an M502
https://marlinfw.org/docs/gcode/M502.html

Otherwise, it is in the menus somewhere, like initialize eeprom or something like that.

**Comment by Roxy-3D** [comment]
> You either need to use the UI to change it, or reload your eeprom from the hard coded defaults (which is what you specify with you change the firmware)

Or maybe use the code as provided by your machine's manufacturer.    There is some pain to be expected when you start trying to reconfigure your machine away from factory defaults.

**Comment by rockman44181000** [comment]
Okay

**Pull request closed without merging**
