### PR TITLE
MAX feedrates not being used

### PR DESCRIPTION
**Pull request by Grogyan**

### CODE REVIEW

**Comment by Grogyan** [comment]
# 

This has extensive changes to some of the core parts of the firmware.

# Requires extensive testing!

I encountered a MAJOR bug whilst trying to do a test print on my old RepRap, a Sells Mendel.  The one which had a belt driven Z axis.
What I encountered was no matter what acceleration setting to feed rate I applied to the Z axis,  Marlin was ignoring it, so only the homing and jog feed rates were being used.

On this old machine, the feed rate needs to be much lower than that of modern machines.
This fix i hope will fix this as I saw some definitions that were not being addressed properly.

I have compiled on my laptop using;
Arduino 1.5.2
Stock settings

The fix also fixes some confusing naming conventions, which makes things a little bit easier to understand what is what.

**Comment by Grogyan** [comment]
Compiles ok
With Arduino 1.5.2

**Comment by nophead** [comment]
In the diff I can only see name changes. I.e. removal of the DEFAULT prefix. How does this fix a bug?

I assume DEFAULT prefix is there to indicate it can be changed with M codes and the LCD.

**Comment by Grogyan** [comment]
The problem was that the planner.cpp and configurationstore were looking for MAX_FEEDRATE to bind to  a local variable. The declaration was DEFAULT_FEEEDRATE but that is misleading. 
Essentially I  compared the code with Sprinter Firmware and saw that this code is essentially identical.  
I wrote this fix late last night, and had enough not yet tested it out on my Sells Mendel.

**Comment by nophead** [comment]
To be clear: are you saying this fixes a bug in the current version of Marlin or are you just renaming variables to make it clearer in your eyes?

Looking at the diff I don't see anything that would affect run time, just name changes. 

DEFAULT_MAX_FEEDRATE gets copied into max_feedrate here: https://github.com/MarlinFirmware/Marlin/blob/ccdb086fc892eb79ceec99aff9f621b47b3f5e42/Marlin/ConfigurationStore.cpp#L427 in Config_ResetDefault(). I.e. the values in configuration.h are the defaults but can be changed, hence the names starting with DEFAULT_.

**Comment by bluesign2k** [comment]
I agree with @nophead here. The net change of the commits in this PR do nothing other than change the names of constants to something slightly less meaningful.

**Comment by daid** [comment]
(Pretty sure this is a miss understanding on how Marlin works from the submitter side. Closed till discussion shows that there is an actual problem)

**Comment by boelle** [comment]
@daid if you have time to spare can you check that i have labeled the other issues right and maybe close others where users mistake how marlin works... i think there are plenty of issues open...

_sigh_ and a small prayer that some of the serious bugs gets worked on instead of just talking and going in circles

**Comment by Grogyan** [comment]
Give me a chance to get to the next day. 
I live on the other side of the planet. 

Both Marlin_Main and Planner reference local variables for max_feedrate but isn't used so when  a feed rate is parsed via gcode that is higher than what the machine can handle there is no override mechanism. 

If you check yourself DEFAULT_FEEEDRATE, doesn't get used at all,  and a lot of the default declaration constants are actually the maximum limit. 
Renaming these as well while I was fixing the max feed rate bug makes it much clearer what those constants actually do.

**Comment by Grogyan** [comment]
Nevermind, found the local variable in ConfigurationStore
Line 373
tmp2[]=DEFAULT_MAX_FEEDRATE
Then later on line 378
max_feedrate[i]=tmp2[i]; 

However fiddling around with the Z max feedrate, making it as small as possible didn't do anything to override the incoming gcode.  Bug still exists, this pull request as mentioned doesn't fix the issue.

**Comment by daid** [comment]
While I'm not sure of the current state of Marlin, I know the Z max feedrate worked fine when the Ultimaker and Ultimaker2 firmwares where forked.

**Comment by nophead** [comment]
If you have EEPROM enabled the firmware defs have no effect until you clear
it. That is why they are DEFAULTs.

I don't think there is a bug at all as most slicers rely on this.

**Comment by alexborro** [comment]
I set my Slicer to ridiculous high travel speeds like 500mm/s for all axis
and then I limit in firmware. And I can assure you those limits work pretty
well.

Check the planner_buffer_line function and you will figure it out.

Cheers

Alex.
Em 16/01/2015 17:15, "Chris" notifications@github.com escreveu:

> If you have EEPROM enabled the firmware defs have no effect until you clear
> it. That is why they are DEFAULTs.
> 
> I don't think there is a bug at all as most slicers rely on this.
>

**Comment by thinkyhead** [comment]
And M502 doesn't help...?

**Comment by Grogyan** [comment]
https://github.com/MarlinFirmware/Marlin/issues/1374

**Pull request closed without merging**
