### PR TITLE
Add microstepping comment

### PR DESCRIPTION
**Pull request by qwewer0**
### Description

Small description change for `DEFAULT_AXIS_STEPS_PER_UNIT` comment, to inform the user that it includes microstepping.

PS:
I might not used the best wording to represent the settings, so suggestions and opinions might be needed.

### Requirements

Default

### Benefits

Less misunderstanding from users.

### Configurations

Default

### CODE REVIEW

**Comment by thinkyhead** [comment]
In Marlin the word "steps" always refers to the STEP pulse count-per-millimeter as derived by:

```
(motor_steps_per_rev × driver_micro_steps) ÷ distance_per_rev
```

Marlin doesn't maintain any "awareness" of the micro-step multiplier. "Steps" in Marlin are just pulses-per-unit. This blindness to the concept is the reason we have to update with `M92`anytime you modify your micro-steps either by changing jumpers, or by using a G-code command like `M350`.

**Comment by qwewer0** [comment]
> In Marlin the word "steps" always refers to the STEP pulse count-per-millimeter as derived by:
> 
> ```
> (motor_steps_per_rev × driver_micro_steps) ÷ distance_per_rev
> ```
> 
> Marlin doesn't maintain any "awareness" of the micro-step multiplier. "Steps" in Marlin are just pulses-per-unit. This blindness to the concept is the reason we have to update with `M92`anytime you modify your micro-steps either by changing jumpers, or by using a G-code command like `M350`.

Ok, so it's a no go? I still think some reference would be good idea, but I don't know what would be the best.

**Comment by thinkyhead** [comment]
Linguistically, the term "microsteps" is problematic even to raise, because it is used interchangeably to refer to a value like 3200 microsteps, 16x microsteps, or 80 microsteps. For this reason I'm hesitant to introduce the new comment to the party conversation.

**Comment by qwewer0** [comment]
> Linguistically, the term "microsteps" is problematic even to raise, because it is used interchangeably to refer to a value like 3200 microsteps, 16x microsteps, or 80 microsteps. For this reason I'm hesitant to introduce the new comment to the party conversation.

I agree, didn't thought about that.

**Comment by thinkyhead** [comment]
I'm assuming no one thinks they should be starting off with 200, 400, or 16 in this instance, so I think it's safe to leave as-is.

**Pull request closed without merging**
