### PR TITLE
[1.1.x] BIBO TouchX configuration

### PR DESCRIPTION
**Pull request by shaktee**
I hope I got the pull request right this think :) Please add BIBO2 Laser Touch X configs to Marlin bugfix-1.1.x

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks good! I'll evaluate and merge if everything is proper.

In future, note that it's better to make a copy of the existing branch with a new name before modifying. This ensures you have unmodified copy of `bugfix-1.1.x` that can be updated and used as basis for future work. Now that your `bugfix-1.1.x` is modified, the only way to get it back into shape so it can be used again in the future is to use `git reset` from the command line.

**Comment by thinkyhead** [comment]
Looks like the configs you're submitting are outdated compared to current configs. I will apply the necessary changes on your behalf.

**Comment by shaktee** [comment]
Thanks much!

**Comment by thinkyhead** [comment]
Thanks for the contribution!

**Comment by shaktee** [comment]
You are welcome! I'm just getting started with Marlin , so I I'm very happy
you guys are so responsive ! Have a wonderful day.

**Pull request merged**
