### PR TITLE
(SKR 1.3) Default pin assignment for filament run out on SKR 1.3

### PR DESCRIPTION
**Pull request by Ari-SSO**
### Description

The FIL_RUNOUT PIN was changed since it was using the XMAX connector, which is used by a large number of printers leaving the XMIN free, especially with DELTAs that do not have the concept of XMIN and YMIN. The socket (1_29) is now assigned by default to FIL_RUNOUT which is less likely to be occupied by an endstop.

In addition, it is also consistent with the ZMIN connector that is used for the height probe.

Now the line of the {X,Y,Z} MIN connectors remains by default to be able to connect the "extra things", in this case the height PROBE, Extruder Filament Sensor 1 and 2 (XMIN, YMIN Respectively)... All the "mandatory" endstop connectors for all printers uses the {X,Y, Z}MAX line, while the optional ones remain in the {X, Y, Z}MIN Line. Much neater and more elegant.

### Requirements

SKR 1.3
(A probe, a flament runout o just do a brigde with a wire to check it)

### Benefits

Now the line of the {X,Y,Z} MIN connectors remains by default to be able to connect the "extra things", in this case the height PROBE, Extruder Filament Sensor 1 and 2 (XMIN, YMIN Respectively)... All the "mandatory" endstop connectors for all printers uses the {X,Y, Z}MAX line, while the optional ones remain in the {X, Y, Z}MIN Line. Much neater and more elegant.

### Configurations

N/A.

Just connect a filament run out sensor, a touch probe, or do a bridge with a wire, and check it with gcode M119.

### Related Issues

It is a Improve of default pin assignment.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> The FIL_RUNOUT PIN was changed since it was using the XMAX connector, which is used by a large number of printers

Most printers home to min, not max.

We use X/Y max pins when a dedicated runout pin isn't available on other boards and this change will now break consumer builds & retail machines that have used this pin for runout for the past four years.

**Comment by Ari-SSO** [comment]
Yes, you're right, I should have put #ifdef DELTA so that it applies only to DELTA.

**Comment by Ari-SSO** [comment]
I will close this and send the solution with the #ifdef DELTA, but I'm wondering if it's convenient to put that #ifdef inside the PIN or directly in the configuration.h

What do you think which is better solution?

**Comment by thisiskeithb** [comment]
> I will close this and send the solution with the #ifdef DELTA, but I'm wondering if it's convenient to put that #ifdef inside the PIN or directly in the configuration.h

Take a look at other parts of the pins file on how we handle it. You can't just assume all deltas use max pins, since ones that use sensorless homing, have to use the min pins as those are connected to the TMC diag pins.

This change would ideally be in your own personal config and not something that should be pushed upstream since we wrapped the pin with an `ifndef` that easily allows users to override it.

**Comment by Ari-SSO** [comment]
Thanks!!!

**Pull request closed without merging**
