### PR TITLE
Allow mpctemp tuning to use the alternative method

### PR DESCRIPTION
**Pull request by StevilKnevil**
### Description
This PR builds on [previous refactoring](https://github.com/MarlinFirmware/Marlin/pull/25503) to allow MPC autotuning to use an alternative method to establish model parameters from the rate of change of heating.

The tuning algorithm falls back to this method if the original (analytic?) method fails to produce sensible values for the `sensor_responsiveness` and `block_capacity`

For ease of review I've created a [draft PR](https://github.com/StevilKnevil/Marlin/pull/5) against the code from the [restructuring of the MPC temp code](https://github.com/MarlinFirmware/Marlin/pull/25503) to see the changes for this in isolation

### Requirements

None

### Benefits

This makes the MPC Temperature auto tuning more reliable in situations where the original method fails.

### Configurations

N/A

### Related Issues

- [[FR] Allow MPCTEMP tuning to use the "Alternative Method"](https://github.com/MarlinFirmware/Marlin/issues/25496)
- [[BUG] MPCTEMP tuning fails with thermal runaway](https://github.com/MarlinFirmware/Marlin/issues/25481)

### CODE REVIEW

**Comment by thinkyhead** [comment]
It's a bad idea to have two overlapping PRs open at the same time. You should combine them into a single PR and close the older one.

**Comment by thinkyhead** [comment]
Flash space and SRAM especially are at a premium on AVR boards, so:
- Features should avoid permanently allocating SRAM for values that are only used while the feature is in-use. For example, data members like `curr_time_ms` should be allocated on the stack and passed as parameters between methods that require them.
- Singleton classes should declare all methods and data members with `static` so that there is no hidden `this` variable being passed as a parameter in method calls.

**Comment by thinkyhead** [comment]
Ah, I see that `MPC_autotune tuner` is allocated on the stack. That's good! However, we should still make its internals all static so that there is no `this` parameter in method calls.

**Comment by thinkyhead** [comment]
In terms of program size, `MPCTEMP` is significantly more costly than `PIDTEMP`. Building each option with the default configuration yields the following build sizes:
```
PIDTEMP:
RAM:   [===       ]  30.3% (used 2483 bytes from 8192 bytes)
Flash: [==        ]  21.7% (used 55028 bytes from 253952 bytes)

Current MPCTEMP:
RAM:   [===       ]  30.4% (used 2492 bytes from 8192 bytes)
Flash: [==        ]  23.1% (used 58538 bytes from 253952 bytes)   + 3510

Extended MPCTEMP:
RAM:   [===       ]  30.4% (used 2492 bytes from 8192 bytes)
Flash: [==        ]  23.7% (used 60264 bytes from 253952 bytes)   + 1726 (+5236 over PIDTEMP)
```
5.1KB (and even 3.5KB) is a large amount of SRAM for a single feature. Anything that we can do to reduce the size of the code will go a long way towards making the feature accessible to more setups. It can also help to make some parts of `MPCTEMP` which may not be useful to everyone into optional sub-features. For example, one could use `MPCTEMP` but disable the automatic tuning for a significant cost reduction.

**Comment by thinkyhead** [comment]
After adding the option `MPC_AUTOTUNE` to enable/disable auto-tuning I get these results:
```
PID with Autotune (No LCD):
RAM:   [===       ]  30.3% (used 2483 bytes from 8192 bytes)
Flash: [==        ]  21.7% (used 55028 bytes from 253952 bytes)

MPC no Autotune (No LCD):
RAM:   [===       ]  30.3% (used 2480 bytes from 8192 bytes)
Flash: [==        ]  20.8% (used 52848 bytes from 253952 bytes) // -2180 under PIDTEMP

Full MPC with Autotune (No LCD):
RAM:   [===       ]  30.4% (used 2492 bytes from 8192 bytes)
Flash: [==        ]  23.7% (used 60238 bytes from 253952 bytes) // +7390 (+5210 over PIDTEMP)
```

**Comment by StevilKnevil** [comment]
> we should still make its internals all static so that there is no `this` parameter in method calls.

I can take a look at that.

Is it OK to change it to static functions with an explicit `this` pointer passed in? Should avoid POD types being copied into stack memory I believe, at the cost of de-referencing the `this` pointer of course.

**Comment by StevilKnevil** [comment]
> In terms of program size, `MPCTEMP` is significantly more costly than `PIDTEMP`. Building each option with the default configuration yields the following build sizes:

I never thought of doing this! I'll have another pass and see whether there are some wins to be had. Are there tools for doing builds of different configs for comparison, or did you do that comparison manually?

**Comment by thinkyhead** [comment]
> did you do that comparison manually?

I just did the comparisons manually (using the included `mftest` script).

I'm going to close this PR and add its differences to #25503 for simplicity.

**Comment by thinkyhead** [comment]
> Is it OK to change it to static functions with an explicit this pointer passed in?

It may not be too important, actually. We have the option to pass an object reference to a set of methods, or just use a class that takes a `this` parameter, and either one is about as good as the other, especially for a stack-based object. We can just use the standard class approach and let the compiler sort it out. The main thing we like to avoid is polymorphism with virtual methods, which will add a VTOC to the classes. Namespaces offer a way around that. But, in general, for more complex stuff like future UI options where performance isn't as important as code size and/or code maintainability we might allow some leeway for that kind of polymorphism.

**Pull request closed without merging**
