### PR TITLE
Ender 5 Pro Homing to 220, 220, 0.

### PR DESCRIPTION
**Pull request by LeeL55340**
Hi, 
I was not sure if this is a bug report or a pull request.

For the last week I have been trying to get Version 2.0 of Marlin installed on my Ender 5 Pro with the silent 1.1.5 board.   I used the official release 2.0.5 and the config files for that release and I had trouble.  Extracted them and set them in a new folder in the root of my C drive.  Copied the Ender 5 Pro folder from the config file into the main folder and copied the 4 files in to the Marlin folder where Configuration.h and Configurtation_adv.h are located  After getting the config done with the BLTouch and compiled in VS Code with the Marlin Extension using the Melzi Optimized selection, I flashed the firmware to the printer.   Powered on and started testing.  The autohome sent the the nozzle to the correct position on the bed back right corner bumping the endstop switches, but the LCD reported that it was 220, 220, 0.  When I tried to move the x or y axis the nozzle moved opposite direction of LCD input.  The z axis and extruder moved correctly.  The BLTouch went to the center of the bed and dropped the build plate down as it should, however  Bed leveling did not work right on x and y axis.

On Sunday July 26, 2020 I decided to make changes one at a time.  I downloaded the latest Bug fix version and the Bug fix config zip.  Doing the same as above in a new folder in the root of my C drive.  This time I compiled the firmware with no other changes.  Flashed it to the printer and it did as above with autohome.  LCD shows 220, 220, 0.  I decided to look at the 1.1.6 source config files from Creality .  (The Creality firmware.hex does work, but that is 1.1.9 according to the website) That led me to make the setting changes below.  These changes made the nozzle move to home and report 0, 0, 0. The moving of X and Y from the LCD where also correct.  So I made these changes to the configuration.h file I used in the above firmware.  It also worked to fix the homing and movement errors.  However the BLtouch still had issues.  It would move the probe off the left edge of the bed.  After some more searches, trial and error, I discovered The BLtouch offsets were backward.  The probe looks at the bed back as the front and the front as the back,  Changing the offsets to 42, 6, 0 (instead of negative) makes the probe work, but it is backward, It starts at the back right and goes to left front.  The Creality firmware does it from left front to back right.

So something is still not right in the configuration.

Below are the changes I made to correct the autohome issue.  Worked, but still issue with BLTouch

// Specify here all the endstop connectors that are connected to any endstop or probe.
// Almost all printers will be using one per axis. Probes will use one or more of the
// extra connectors. Leave undefined any used for non-endstop and non-probe purposes.
#define USE_XMIN_PLUG
#define USE_YMIN_PLUG
#define USE_ZMIN_PLUG
//#define USE_XMAX_PLUG
//#define USE_YMAX_PLUG
//#define USE_ZMAX_PLUG

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false
#define INVERT_Y_DIR false
#define INVERT_Z_DIR true

// Direction of endstops when homing; 1=MAX, -1=MIN
// :[-1,1]
#define X_HOME_DIR -1
#define Y_HOME_DIR -1
#define Z_HOME_DIR -1

It is like a conflict in the software and hardware endstops.

I have not done a print as yet, since am waiting for a new high thermistor for the nozzle, so I can use the Micro Swiss hot end for high temp filaments.  Attached are my config files and the older Creality source code.  The Creality files are the ones starting Ender 5.
Attached are my configuration files and the bottom set are from Creality's website

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/4984507/Configuration.zip)

[Ender 5 Source Code 1.1.61.zip](https://github.com/MarlinFirmware/Marlin/files/4984526/Ender.5.Source.Code.1.1.61.zip)
[Ender-5Marlin1.1.9EnglishTMC2208(T84).zip](https://github.com/MarlinFirmware/Marlin/files/4984528/Ender-5Marlin1.1.9EnglishTMC2208.T84.zip)

I would really like to get this to work correctly.  I am sorry if this was the wrong area, 

Thanks for any help you can provide.

Lee

### Benefits

Trying to get the printer to work as the manufacture has designed

### Related Issues

Main Issue :  Generic firmware for the Ender 5 Pro does not work correctly.
Issue 2 :BLTouch does not function as expected.

### CODE REVIEW

**Comment by sjasonsmith** [comment]
This is really neither a pull request nor a bug.

Homing to the back right as (220, 220) is expected and correct behavior. It is not like they come from the factory, but in this case Creality did it wrong. They basically just used an Ender 3 config on an Ender 5 and didn't care that they made the Ender 5 series backward for everybody.

For best results getting help with configuration and troubleshooting, please use the following resources:

- MarlinFW.org [Marlin Documentation](http://marlinfw.org/)
- RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
- [Tom's 3D Forums](https://forum.toms3d.org/)
- Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
- Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- Marlin Discord server. Join link: https://discord.gg/n5NJ59y

After seeking help from the community, if the consensus points to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Comment by LeeL55340** [comment]
Jason,

 

WOW!!!!!!!

 

In a few simple sentences you have indicated that you think I am stupid.  I did not read or investigate instructions or use videos from youtube or use google searches.  You even show a personal dislike for Creality and that the Ender 5 places the nozzle at the right rear of the printer for the home position.  Your dislike for Creality and the Ender 5 is your issue, please do not make it mine.

 

This is the quickest blow off I have ever had looking for some help.

 

It is similar to computer technicians that automatically tell the customer they have to reformat the hard drive and reload everything.  

 

I AM NOT STUPID

 

I have been working at this for about 3 weeks.

1:  Looking at where to get the firmware and what is used on the Creality printers.

2:  Researching how to load the firmware and get the correct file.

3: Choosing between ArduinoIDE, Atom (no longer recommended), and VS Code.  Discovering the new Marlin extension for VS Code.

4:  What extension, libraries, and other preferences to use in the software.

5: Use the instructions per Marlin or from videos to make changes to the configuration files and get ready to compile the firmware.

6. Compile the firmware and learn to fix any errors that occur.

7. Connect to the printer and load the firmware.

8 Test the firmware on the printer.

 

The searches on 220 220 0 homing issue do bring up some results, but they never have a solution, as most individuals state they decided to switch to a new 32 bit motherboards.

 

Thanks for the no help help.

 

Lee Landsteiner

**Comment by sjasonsmith** [comment]
@LeeL55340 I am sorry you interpreted my tone very differently than I intended. I try to be reasonable with people. I do this for fun because I enjoy helping people. I invited you to the channels where you can communicate with other Marlin users (including myself) and discuss the concern. Feel free to jump over to The Discord channel using the link above and tag me if you want to continue a discussion over there. I have the same username on github and Discord.

I did not intend any personal judgement. I don't dislike Creality, although I do judge them a bit on this particular decision. I have both an Ender 3 and an Ender 5, and I stand by my position that they made a mistake shipping the Ender 5 the way they did. I was very pleased to see the Marlin example fix the backward configuration they chose to ship from the factory. It might feel normal to you if the Ender 5 is your only printer, but it is extremely irritating if you use it after working with other printers.

I certainly did not intend to imply you were stupid, just that this wasn't the right venue to continue any discussion. This was closed for a few different reasons:

1. It was opened as a malformed pull request. I'm sure this was unintentional, but it can't be allowed to sit open this way.
1. The description was very long, making it hard to pick out what the actual important details were. I switched from my phone to computer to absorb it the best I could and I _think_ I responded to the correct concern, but may have missed something.
1. This behavior has been discussed multiple times and is very intentional. I'm happy to discuss it with you on Discord if you like, but can't keep hashing out the same things in the issue (or pull request) queues.

**Comment by LeeL55340** [comment]
Jason,

 

Yes, the Ender 5 Pro is my first and only printer.  I purchased February of this year, because I liked the design, the bed moving up and down controlling the layers, x and Y moving the nozzle to control the shape, for me the nozzle moving to right back of the printer is great.  It clears the bed making removal of the print easy.  Yes the BLTouch will change that. 

 

I understand that where I posted was incorrect, I made a comment to that effect.  My other mistake was too much information and for that I am sorry.

 

Please try to understand that Creality did not create the first issue.  Their config file(1.1.6) I referenced is how I found a fix, but it is incompatible with Marlin 2.0 and TMC2208 drivers are not there.   No Creality source files were used in compiling any of the firmware I flashed to the printer.  I did try their precompiled hex file for the Ender 5 Pro with Bltouch to confirm I installed it correctly.  Since the hex file is not editable, and I want make full use of my all metal hotend the configuration files are needed.

 

The original issue starts as a direct result of using files downloaded from Github/Marlinfw.org.  Nozzle moves to right rear and hits the switches,  LCD shows 220 220 0 as the location, moving x and y is opposite is opposite from LCD.  Z and extruder work correctly.  This occurred using both the stable release of Marlin 2.0 and the Bug fix version with proper config files from the same sources.   I have repeated these results at least 4 times.

 

You originally stated that the LCD showing 220 220 0 is the correct home position for the Ender 5 Pro.  If that is true then why does the z show as 0, should it not be 300.

 

I did create an account at Discord, but was too tired to learn how to use/navigate on it.

 

Please do not respond to this email, you and I do not seem to be a good match for working this out.  Should I wish any further discussion with you, I will reach out to you at Discord.

 

I will go back to my trial and error method change some settings and see what they do.  If they work great, if not change them back and try some other settings.  Hopefully I will stumble on a fix.

 

Sometimes in life we learn more from our mistakes, then we do from our successes. 

 

Thanks for the effort

 

Lee Landsteiner

**Comment by thisiskeithb** [comment]
Jason is correct in that Crealtiy shipped the Ender-5 with Ender-3 settings, so the entire printing area is effectively 180 out from what is standard since it homes to the X & Y max endstops instead of min (as their firmware is configured).

It's been discussed many times about how configs here (and popular forks) are "wrong" compared to Crealtiy's, but the Creality's firmware is not correct. Keep in mind that Crealtiy's firmware should not be considered correct (or safe for that matter) since they were also shipping printers with thermal runaway protection disabled.

Please hop on [Marlin's Discord](https://discord.gg/n5NJ59y) to discuss this issue further.

**Comment by LeeL55340** [comment]
Thank you

 

 

 

Lee Landsteiner

**Pull request closed without merging**
