### PR TITLE
Update pt-br translation

### PR DESCRIPTION
**Pull request by hydrocat**
### Description

- Changed messages to use _UxGT
- Translated more messages. 

### Benefits
Easier for Brazilian consumers

### CODE REVIEW

**Comment by hydrocat** [comment]
Should I do a pull to 2.x ?

**Comment by thinkyhead** [comment]
I'll need to fix some errors here. For example, `MSG_XSTEPS`, `MSG_YSTEPS`, and `MSG_ZSTEPS` have been replaced. Did you start with an older branch?

**Comment by thinkyhead** [comment]
Before you can apply changes, you'll need to re-download your branch. From Github Desktop, open the Git terminal / command-line. Then use this command:
```
git fetch origin
git reset --hard origin/bugfix-1.1.x
```

**Comment by hydrocat** [comment]
Oh dang, yes I started from older branch. Seems that I took too long to
make the pull request.
Can you explain me better what is wrong with the branch?

Em qua, 11 de abr de 2018 9:35 PM, Scott Lahteine <notifications@github.com>
escreveu:

**Comment by thinkyhead** [comment]
> Can you explain me better what is wrong with the branch?

- These strings are all too long (20 characters max):
```cpp
//                                                 12345678901234567890
#define MSG_PROGRESS_BAR_TEST               _UxGT("Barra de Progresso T|este")
#define MSG_EDITING_STOPPED                 _UxGT("Fim da Edição da Mal|ha")
#define MSG_UBL_UNHOMED                     _UxGT("Reposicione a Extrus|ora")
#define MSG_UBL_LEVEL_BED                   _UxGT("UBL-Unified Bed Leve|ling")
#define MSG_UBL_MANUAL_MESH                 _UxGT("Fazer a malha manual|mente")
#define MSG_UBL_EDIT_CUSTOM_MESH            _UxGT("Editar Malha Customi|zada")
#define MSG_UBL_DONE_EDITING_MESH           _UxGT("Fim da Edição da Mal|ha")
#define MSG_UBL_BUILD_CUSTOM_MESH           _UxGT("Montar malha Customi|zada")
#define MSG_UBL_MESH_HEIGHT_ADJUST          _UxGT("Ajustar altura da ma|lha")
#define MSG_UBL_VALIDATE_CUSTOM_MESH        _UxGT("Checar Malha Customi|zada")
#define MSG_UBL_CONTINUE_MESH               _UxGT("Continuar malha da m|esa")
#define MSG_UBL_GRID_MESH_LEVELING          _UxGT("Nivelação da malha e|m grade")
#define MSG_UBL_OUTPUT_MAP_HOST             _UxGT("Enviar malha para o |Host")
#define MSG_UBL_OUTPUT_MAP_BACKUP           _UxGT("Salvar backup da mal|ha")
#define MSG_UBL_FILLIN_AMOUNT               _UxGT("Quantidade de Enchim|ento")
#define MSG_UBL_FINE_TUNE_CLOSEST           _UxGT("Ajuste fino do Próxi|mo")
#define MSG_UBL_STORAGE_MESH_MENU           _UxGT("Armazenamento da Mal|ha")
#define MSG_UBL_RESTORE_ERROR               _UxGT("Erro ao restaurar UB|L")
#define MSG_RESTORE_FAILSAFE                _UxGT("Restauração de emerg|ência")
#define MSG_USERWAIT                        _UxGT("Clique para continua|r")
#define MSG_SKEW_FACTOR                     _UxGT("Fator de Cisalhament|o")
#define MSG_ERR_REDUNDANT_TEMP              _UxGT("Erro: Temperatura Re|dundante")
#define MSG_ERR_MAXTEMP                     _UxGT("Erro: Máxima Tempera|tura")
#define MSG_ERR_MINTEMP                     _UxGT("Erro: Mínima Tempera|tura")
#define MSG_ERR_MAXTEMP_BED                 _UxGT("Erro: Mesa Máxima Te|mperatura")
#define MSG_ERR_MINTEMP_BED                 _UxGT("Erro: Mesa Mínima Te|mperatura")
#define MSG_DELTA_AUTO_CALIBRATE            _UxGT("Calibração Automátic|a")
#define MSG_DELTA_HEIGHT_CALIBRATE          _UxGT("Calibrar Delta Altur|a")
#define MSG_UBL_LEVELING                    _UxGT("UBL-Nivelamento Unif|icado de Mesa ")
#define MSG_INFO_PRINT_COUNT                _UxGT("Contagem de Impressã|o")
#define MSG_DAC_EEPROM_WRITE                _UxGT("ESCREVER EEPROM COM |DAC")
#define MSG_FILAMENT_CHANGE_OPTION_HEADER   _UxGT("OPÇÕES PARA CONTINUA|R:")
#define MSG_ERR_HOMING_FAILED               _UxGT("Falha ao Ir para ori|gem")
#define MSG_FILAMENT_CHANGE_EXTRUDE_2       _UxGT("extrusão de filament|o")
```
- `MSG_VX_JERK`, `MSG_VY_JERK`, `MSG_VZ_JERK` have been replaced by `MSG_VA_JERK`, `MSG_VB_JERK`, `MSG_VC_JERK`. (I have fixed these.)
- `MSG_XSTEPS`, `MSG_YSTEPS`, and `MSG_ZSTEPS` have been replaced by `MSG_ASTEPS`, `MSG_BSTEPS`, and `MSG_CSTEPS`. (I have fixed these.)

Before you can apply the needed changes, you'll need to re-download your branch. From Github Desktop, open the Git terminal / command-line. Then use these commands:
```
git fetch origin
git checkout bugfix-1.1.x
git reset --hard origin/bugfix-1.1.x
```

**Comment by hydrocat** [comment]
> Can you explain me better what is wrong with the branch?

Hey, thank you for helping me. If it weren't for you, it would be way way harder!

> git fetch origin
> git checkout bugfix-1.1.x
> git reset --hard origin/bugfix-1.1.x

I meant (badly expressed though), what is the purpose of these commands ? (to refresh my local repository ?).
Or better, why do I need to re-download my branch ?

**Comment by thinkyhead** [comment]
> Or better, why do I need to re-download my branch ?

Because I rebased, squashed, and patched your branch to correct some other issues, and Github Desktop will only revert all those changes if used.

**Comment by thinkyhead** [comment]
I see that in the non-UTF8 language file, some accents were left in or added. Are these errors, and should all accented characters in that file be replaced?

**Comment by thinkyhead** [comment]
Is this correct? `ESCAPE TEHRMICO`

**Comment by thinkyhead** [comment]
@hydrocat — Some duplicates are left over. Which ones are correct and which should be removed? (Shorter is better for these labels.)
```cpp
#define MSG_INFO_PRINT_COUNT                _UxGT("Qtd de Impressoes")
#define MSG_INFO_COMPLETED_PRINTS           _UxGT("Fim")
#define MSG_INFO_PRINT_TIME                 _UxGT("Tempo de Impressao")
#define MSG_INFO_PRINT_LONGEST              _UxGT("Trabalho Mais longo")
#define MSG_INFO_PRINT_FILAMENT             _UxGT("Total Depositado")

//#define MSG_INFO_PRINT_COUNT                _UxGT("Qtd Impressoes")
//#define MSG_INFO_COMPLETED_PRINTS           _UxGT("Completas")
//#define MSG_INFO_PRINT_TIME                 _UxGT("Tempo de Imprimindo")
//#define MSG_INFO_PRINT_LONGEST              _UxGT("Impressao Mais Longa")
//#define MSG_INFO_PRINT_FILAMENT             _UxGT("Depositado")
```

**Comment by hydrocat** [comment]
> Is this correct? ESCAPE TEHRMICO

No, it "Escape Térmico".
> @hydrocat — Some duplicates are left over. Which ones are correct and which should be removed? (Shorter is better for these labels.)

The commented block is better but not very good. Should I do a new PR if I want to fix it ?

**Comment by thinkyhead** [comment]
> Should I do a new PR if I want to fix it ?

Sure, you're welcome to submit patches anytime, whether big or small.

**Pull request merged**
