### PR TITLE
Check compatibility for Teensy-based processor

### PR DESCRIPTION
**Pull request by Wackerbarth**
The instruction say to set a #define in fastio.h
However, that value is not included before this test.

### CODE REVIEW

**Comment by AnHardt** [comment]
@Wackerbarth 
Does it really make sense to complain about a #define what you could have made yourself right before the #include.

**Comment by AnHardt** [comment]
I'm confused:
https://github.com/MarlinFirmware/Marlin/blob/Release/Marlin/Marlin.h#L21

**Comment by Wackerbarth** [comment]
@AnHardt  -- The issue is related to the way that ino compiles library routines.

If I follow the instructions and enable the #define in fastio, the error still aborts the compile.

The test in the pins routine gets pulled in without fastio being included because the library needs the pins, but knows nothing about fastio.

In any case, it doesn't hurt to try to include fastio. The contents of properly coded headers gets pulled in only once.

**Comment by Wackerbarth** [comment]
@AnHardt -- "Does it really make sense to complain about a #define that you could have made yourself right before the #include."

That is the equivalent to saying "Does it make sense to fix ANY bug? After all, you can always patch your copy of the source."

**Comment by AnHardt** [comment]
@Wackerbarth 
At first i have only seen your patch:

```
   #error Oops!  Make sure you have 'Brainwave Pro' selected from the 'Tools -> Boards' menu.
 #endif

 +#include "fastio.h"
+
 #ifndef AT90USBxx_TEENSYPP_ASSIGNMENTS  // use Teensyduino Teensy++2.0 pin assignments instead of Marlin alphabetical.
  #error  Uncomment #define AT90USBxx_TEENSYPP_ASSIGNMENTS in fastio.h for this config
 #endif
```

My immediate thought was. It should look like:

```
   #error Oops!  Make sure you have 'Brainwave Pro' selected from the 'Tools -> Boards' menu.
 #endif

+ #define AT90USBxx_TEENSYPP_ASSIGNMENTS
 +#include "fastio.h"
+
- #ifndef AT90USBxx_TEENSYPP_ASSIGNMENTS  // use Teensyduino Teensy++2.0 pin assignments instead of Marlin alphabetical.
 - #error  Uncomment #define AT90USBxx_TEENSYPP_ASSIGNMENTS in fastio.h for this config
 -#endif
```

Then i greped for "fastio.h" to find out its only one time included, in marlin.h.

```
#include "fastio.h"
#include "Configuration.h"
#include "pins.h"
```

So every time marlin.h is included fastio.h is included before pins.h includes pins_BRAINWAVE_PRO.h.
At this point, not recognizing pins.h could be included somewhere else, i posted to be confused.
A further grep for AT90USBxx_TEENSYPP_ASSIGNMENTS showed several tests for it in several pins_xx.h files  So your PR is, if the right way at all, a work around for your special case, but not a fix.

Next greped for "pins.h".
Besides of several irrelevant occurrences in comments, the entry's in Marlin.ino and Marlin.pde attracted my interest. They have similar constructs as in Marlin.h but without the inclusion of fastio.h. I have no idea if this could fix your problem, nor i can test this without setting up a new virtual machine. But maybe you can.

**Comment by Wackerbarth** [comment]
1) _I_ don't have an issue myself because I use the Arduino IDE and, there, I define AT90USBxx_TEENSYPP_ASSIGNMENTS as a part of _MY_ Boards.txt.  However, I encountered the problem when trying to get Travis to build my configuration.

Now, you need to recognize that Travis does not use the IDE (it uses `ino`, which is similar to `make` in design).  In any case, the .ino (and the .pde file which really should be purged) only apply to the main marlin.cpp.  Libraries are compiled separately. Anything done in the .ino file has NO effect on that portion of the compilation.

**Comment by Wackerbarth** [comment]
I suspect, but don't really care to confirm, that there is a "circular include" issue caused by the desire to have the Configuration.h including ALL of the "sanity checks" which, in turn, need a lot of other stuff that isn't needed in specific situations.

**Comment by AnHardt** [comment]
OK.
Let's assume the include of "fastio.h" in pins_BRAINWAVE_PRO.h is the fix for compiling for BRAINWAVE_PRO with ino. What is different in pins_TEENSY2.h - why should that work without the inclusion? Or pins_PRINTRBOARD.h. Here the test is the other way around (#ifdef) - passing the test could mean we have not read "fastio.h" at all - and indeed, if i follow your argumentation, we have not.

The special case i meant was neither Arduino, nor Ino, nor Make, but your configuration (BRAINWAVE_PRO)

**Comment by AnHardt** [comment]
What do wee need to tell Ino our needs?
Do we need a special Makefile, as PR#1745 suggests.

**Comment by Wackerbarth** [comment]
Indeed, there are also problems with the other Teensy-based setups.

As for #1745, the Makefile is basically a replacement for the ino build.

There are (at least) 4 ways to go from the source files to a hex image.
1) use make and a customized Makefile
2) Use ino, or some other substitute for the Arduino IDE
3) Use the (recently added) arduino command line tool
4) Use the Arduino IDE

For "user friendliness", I think that we need to support (4).
This implies testing not only the Marlin source, per se, but also the ArduinoAddons needed to support the build.
Unfortunately, (3), which actually runs the java code of the IDE, needs a graphical head.
I don't know how difficult it will be to do so in the Travis CI environment.
The fact that Travis continues to be based on an older Ubuntu release makes it difficult to utilize more up-to-date versions of the various supporting toolset.
(2) ino is basically a rewrite of the IDE Java code. Here too, it does not support the current file layout or tools from current versions of the IDE.
(1) A makefile never supports the processing of the Arduino platform information. It bypasses all of that and performs a direct compilation and build.As such, it differs sufficiently from (4) to cause headaches keeping the two build schemes in sync.

**Pull request closed without merging**
