### PR TITLE
LCD_UBL_memory_slot_corrections

### PR DESCRIPTION
**Pull request by Tannoo**
Changed the memory slot edit function to work with the
`settings.calc_num_meshes()`

### CODE REVIEW

**Comment by Tannoo** [comment]
I need to add another thing to this.

**Comment by Roxy-3D** [comment]
OK....   I was ready to hit the merge button...  But I'll wait for what ever other goodie you are going to add!

**Comment by Tannoo** [comment]
I'm good, if Travis likes it. That Merge bit was not on purpose... but it was because of your edits. No big deal.

I added memory error handling on the LCD screen of the storage slot menu.

**Comment by p3p** [comment]
Should changes like these not go to bugfix-1.1.x first (apart from the minor edit that's in the HAL)

**Comment by Tannoo** [comment]
I completely spaced that bugfix-1.1.x still existed. I can PR one on that.

**Comment by Roxy-3D** [comment]
> Should changes like these not go to bugfix-1.1.x first 

Maybe...   But right now we are running two parallel branches.  Any change in one, in theory will end up in the other if it is appropriate.   And from my perspective...  I think it is good to have stuff in the 32-bit branch that people want.   It might help pull people over to the 32-bit world.

**Comment by fiveangle** [comment]
I have to say that I kind of agree with Chris that these general marlin fixes are probably best to go into bf1 first so they can be vetted like anything else... let Scott deal with however he wants to deal with it. 

This leaves bf2 for everything that's 32-bit specific and we can merge/messwith/rollback with reckless abandon until it gets "good enough" then let Scott loose on doing a master merge.  This also prevents having to do the work twice (one in each branch).

That's what everyone complained about with 32-bit: too many uncessary changes making heavy lifting work to get the 32-bit boards just _functional_ a little tedious.

**Comment by Roxy-3D** [comment]
OK!   I did the double lift to get a UBL correction into each branch earlier today.  But I do understand that perspective.   Those fixes were not critical to the 32-bit work.   They can wait to be brought over to the 2.0.0 branch.

With that said...  There are going to be changes made to the 2.0.0 branch that ultimately need to go to 1.x.x branch.   Maybe that happens when the two branches merge soon....

**Pull request merged**
