### PR TITLE
Bugfix 2.0.x - Anet A2 Configurations

### PR DESCRIPTION
**Pull request by ModMike**
### Requirements

Anet A2 or A2 Plus

### Benefits

Tested on stock Anet A2 Plus. Printer now operates properly.  Previous version had incorrect:

- Stepper directions (were inverted and caused printer to crash)
- Axis steps
- Temp sensors (Were 11 instead of 5)
- Incorrect Bed sizes.  Previously:

```
//ANET A2 with glass bed clamps and safety margin, X0/Y0 0 front left bed edge:
#define X_BED_SIZE 190
#define Y_BED_SIZE 250
#define X_MIN_POS -7
#define Y_MIN_POS -5
#define Z_MIN_POS 0
#define Z_MAX_POS 180
```

These are not stock sizes but custom sizes and configs of original contributor.  Standard A2 Plus bed size is 220 X 270 X220.

- Filament width: Was defaulted to 3.0, printer is delivered with hot end PTFE tube installed in hot end, default is 1.75.

- inactive extruder settings: Extruder disable was enabled

Added 

- Level bed corners
- A2 version

### CODE REVIEW

**Comment by thinkyhead** [comment]
We already have A2-Plus configurations in the `examples/Anet` folder. Please compare them and decide which options should be kept the same and which should be changed.

**Comment by thinkyhead** [comment]
I've added a commit applying your changes to the existing Anet A2 Plus configuration. There are a lot of differences between yours and the one submitted earlier. Please compare these and make all the changes needed to bring everything into alignment.

If there are questions, please discuss with @MaiTaiSui.

**Comment by ModMike** [comment]
I actually tried those on my A2 Plus and they are a disaster.

The other A2 files come from the Skynet branch and are not only completely incorrect, but some how corrupt.  I could not change stepper direction no matter what I did.  Please check my PR comments for a list of the more serious issues.

I started with a new blank sample config and manually configured it.  Tested on my A2 plus and runs perfect.

**Comment by thinkyhead** [comment]
@ModMike — Are there any of the features enabled in the SkyNet version that would be useful to leave enabled (`ADVANCED_PAUSE_FEATURE`, `BABYSTEPPING`, `LCD_INFO_MENU`, etc.) ?

**Comment by ModMike** [comment]
Funny you should ask.  A bunch of stuff, such as auto level was enabled, wrong temp sensor, etc.

As I said, I took a template and worked from there to make sure an out of the box A2 plus would work.  I also created one for A2.

The other benefit is I saved a good amount of memory which is so scarce on a 1284p.

**Comment by ModMike** [comment]
Sorry to take so long to get back to you but I wanted to do some tests to validate size requirements.

I was hesitant to enable many extra features because we are dealing with a 1284p.  When I first got the printer I tried to enable Auto Level and went over the allowable size, which corrupted my boot loader.  An unfortunate set back for a new user.

When I enable the advanced pause and Baby stepping we get:

screen shot 2018-09-02 at 9 08 15 am

In fact I remember seeing several variations of the config files on Skynet.  There was an auto level one which I guess was shoehorned in by stripping it down.  I did go a little too far when I disabled SD Support so I put that back in and will update.  As it stands now:

screen shot 2018-09-02 at 9 22 37 am

It has be stripped even more if you want auto level, I removed SD support in my case because I had Octoprint.

I'm not sure what I did back then but I think it might be more prudent to allow users to choose advanced features.  I could be wrong, let me know what you think is best.

**Comment by ModMike** [comment]
Ok I re-enabled SD support and it is now bare bones.  We could add a few more features in but as I said, it will preclude the use of auto level which is probably the first go to upgrade new users make.

Let me know if you need me to validate anything else soon because I am selling the machine.

**Comment by thinkyhead** [comment]
I trust that @houseofbugs can help us figure out the best combination of features for these configs, as he does a lot of work with the Melzi-based printer configs.

**Comment by ModMike** [comment]
Not sure what that means.  Do you want me to close the pull request?

**Comment by ModMike** [comment]
@thinkyhead 

I updated the description to point out the errors of the current config and defined ENDSTOP_INTERRUPTS_FEATURE

The long and short of it is the current A2 configs you have are for a very custom A2 Plus built by the contributor.  I am also not sure why this the case, but all the axis are improperly inverted, maybe Anet changed their wiring or suppliers when I got mine last February.  I am sure I did not make a wiring mistake as the plugs are all keyed.

It is very easy for you to look at a few values and see that the config is non-standard.  In any case, I will close this PR if you do not want it or don't trust it.

Again, let me know what you want to do.

**Comment by AnHardt** [comment]
What we want is consensus about how this should look, by the interested parties (@ModMike,  @MaiTaiSui and @houseofbugs).
We don't want to edit the files back and forth. We don't have a clue about Anet A2 printers. We don't own one of them, nor have access to one for any test. We don't have time to make us a picture just by reading documentation or for searching it.  We do have to trust the interested parties. If they disagree - we don't can, nor want to judge about that. All we can do, is to try to bring the parties together by calling their names with an @ before - what should alert them.
So please be patient for a few days to give him a chance to react.

**Comment by ModMike** [comment]
@AnHardt 

Oh my!  I appreciate the work the devs do very much and respect their time, so much so that I patreoned thinkyhead.  May be not much, but at least I did.

When I submitted my PR, I tried to detail  obvious errors that could be used to easily cross check the validity of the current config.  The idea was that once he realized the existing one was for a custom A2 plus, he could quickly make a decision.

As to your other points, I DO HAVE an A2 plus for some time and have had massive issues with configs, especially when derived from Skynet.  Even the out of the box axis directions were wrong.

When I decided to sell my A2 last week, I wanted to put a clean config on it so I downloaded the one in question.  There were serious issues in the config itself and a few compilation errors that I needed to fix, but I soldiered on.  After a frustrating hour trying to set axis directions I started to suspect  the mix of custom configs and older code was somehow working against itself so I made the decision to start fresh.

This completely fixed my printer and more importantly, provided a good base configuration that stock A2 owners could build on, rather than decipher and walk back.  Thats the point of stock configs.

@thinkhead take all the time you need, I wasn't pushing you to make a snap decision, I thought I was helping but clearly I wasn't.  Sorry for any misunderstanding.

**Comment by AnHardt** [comment]
For example the stepper plugs.
Is there a notch at the plug or not. Do the instructions include the direction of the notch. Or is it color coded and, do the instructions determine it. Or are there 4 separate plugs - colours given in the instructions?
If nothing is given, the direction of the motor is random and you just have to turn the plug to make it right  No need to change that in software - and more - no **correct** direction in software. I simply don't know if there is a fixed direction, or if it does not fit because you followed your own rules.
I really don't want to investigate nor judge that.

**Comment by ModMike** [comment]
@AnHardt As I said a couple of posts ago, both sides of the connector are keyed, no way to invert motor or board side.

**Comment by thinkyhead** [comment]
> @thinkhead take all the time you need, I wasn't pushing you to make a snap decision, I thought I was helping but clearly I wasn't. Sorry for any misunderstanding.

You're good, no worries. I'm just interested to gather more feedback because I know that with careful option tuning we can get a good assortment of features to fit within the (less than) 128K limit, and we can also make use of all that extra free SRAM … about 10K of it.

> It is very easy for you to look at a few values and see that the config is non-standard. In any case, I will close this PR if you do not want it or don't trust it.

We can continue to work with this PR as our "exhibit A" and keep it open. Adding more commits is not a problem, so feel free to keep tweaking this till you're satisfied. I won't merge it until it's ready, and I can always "squash" all the commits at any point, or upon merge.

**Comment by ModMike** [comment]
@thinkyhead Did you change your mind and merge it?  If so I will delete my branch so I can use github properly.  Can you confirm if the following is the correct work flow?

1) Fork the branch to my GitHub
2) Clone to my machine
3) Check out the code by creating a new local branch (something I never did before)
4) Push commits from my branch to my GitHub fork (or my local machine?)
5) Create a pull request

Thanks!

**Comment by ModMike** [comment]
> I know that with careful option tuning we can get a good assortment of features to fit within the (less than) 128K limit, and we can also make use of all that extra free SRAM … about 10K of it.

That's a good point.  I will make 2 more configs, much like Skynet was set up.  One will be the config that crams in as many features as possible and the 2nd will be an auto level config.

**Comment by thinkyhead** [comment]
I did change my mind and merge it. Might as well, as there's hardly anyone adopting this branch yet outside of hardcore testers.

**Comment by thinkyhead** [comment]
> That's a good point. I will make 2 more configs, much like Skynet was set up. One will be the config that crams in as many features as possible and the 2nd will be an auto level config.

Take a look at the [TH3D Unified Firmware](https://github.com/houseofbugs/TH3D-Marlin/releases) for guidance about what features can fit within 128K, and let's try to keep it down to a single configuration per machine.

**Comment by thinkyhead** [comment]
> Can you confirm if the following is the correct work flow?
> 
> 1. Fork the branch to my GitHub ✔️ 
> 1. Clone to my machine ✔️
> 1. Check out the code by creating a new local branch (something I never did before) ✔️
> 1. Push commits from my branch to my GitHub fork (or my local machine?) ✔️
> 1. Create a pull request ✔️

Number 3 is the tricky one. You should set your fork's default branch to be `bugfix-2.0.x` (from your fork's web page -> settings) before you use GitHub Desktop to create a new branch so it has the right root point.

Also, almost no one does this… But it's helpful to keep your fork's branches in sync with the main repository if you plan to keep making contributions. The `git` command-line is best for that.
```sh
git fetch MarlinFirmware
git checkout bugfix-2.0.x
git reset --hard MarlinFirmware/bugfix-2.0.x
git push -f origin
```

And, always create a new branch when you want to start making changes. It's best to never modify the branches that correspond to branches in the main repo. So, for example…
```sh
git checkout MarlinFirmware/bugfix-2.0.x -b my_new_feature_branch
```
(This is what GitHub Desktop app does when you use it to create new branches, assuming you've updated your fork's default to bugfix-2.0.x.)

**Comment by ModMike** [comment]
@thinkyhead As always, thank you for the clarification and direction. 

I followed your advice and looked at the Houseofbugs unified files, it was illuminating.  I will retool the files and re-submit.

**Comment by ModMike** [comment]
@thinkyhead 

> I did change my mind and merge it. Might as well, as there's hardly anyone adopting this branch yet outside of hardcore testers.

I used 2.0.x because someone told me, might have been you, that 2.0.x has smaller config files than 1.1x, not sure if this is still the case with 1.19.

The other reason is I am given to understand, maybe erroneously, that 1.19 is the end of the line for the 1.1x branch.

I have been using this branch, as you are painfully aware :-), for some time and don't understand why everyone isn't using it. Works great for me.  Granted I have a sample of 1 printer so I may not be seeing the big picture.  I am sure it will explode once it become 2.0.0.

**Comment by thinkyhead** [comment]
2.0 config files are slightly larger than 1.1.9 due to supporting more LCDs and a few extra options.

The bugfix-2.0.x branch is always changing and may be more prone to bugs as things are refactored and so on. For this reason it's not yet recommended for everyone. But it does work well, and is already much improved over 1.1.x.

1.1.9 is the last release of 1.1. The next release will definitely be 2.0, as soon as we've got our current crop of 32-bit boards pretty well stabilized.

**Comment by mozzbozz** [comment]
Sadly, none of the linked persons have answered in this thread. I'm new to the Marlin / Anet party (until now only printed with the original Anet firmware) and trying to use the Marlin firmware on my Anet A2 (not plus; ordered 2017-03-10) now. Thanks for your contribution, @ModMike, you were of great help!

However, I found some obscurities. Those are:

* Stepper directions (yep, you inverted those, I inverted them again, back to original?!). I have a question about this to you, ModMike: Which axis orientation did you assume? [This](https://3dprinting.stackexchange.com/q/2593) one (you need to kind of change the y-axis plus and minus in your head in the linked picture as it is relative to the nozzle, not the bed)?

* Also your extruder invert setting was the wrong way for me...

* In one of the comments, you wrote, you re-enabled SDSUPPORT setting. But it was disabled for me? I re-enabled it, because this is the "standard" way to use the ANET printers for beginners (as well as me, at least for now :p )

Also I changed the following setting after I compared it to the ANET A8 settings and after some research it just made sense:

* `BED_MAXTEMP` set to 130 instead of your 150, because according to [this](https://3dprint.wiki/reprap/anet/a8/improvements/understanding_my_heatbed) it won't even reach 120°C (only about 115) under normal conditions... and we all know better be safe than sorry with the Anet printers. 130 is also the stanadard temp for the Anet A8 config.

Oh and you forgot one difference in your Anet A2 plus vs. Anet A2 config: The ANET A2 (not plus) has a different LCD. Therefore I disabled `ANET_FULL_GRAPHICS_LCD` and enabled the correct `ZONESTAR_LCD` option (which according to the comments also is meant for the simple Anet display and is also used by the Anet A8 config).

Only "bug" I noticed is that the "enter" button next to the display doesn't really work and I need to use the "menu" button to enter a menu... not a big deal, but wondering if this is a problem for the Anet A8 with Marlin, too? Because comparing the 2 configs, I can't find a difference explaining this behaviour?

Oh and I can confirm there is no way to change the stepper directions accidentally, the plugs are "fool proof" (at least assuming they aren't assembled in different ways). So no idea why your axis are controlled the other ways round? Is there really a difference between the A2 and A2 plus apart from the LCD and the higher z axis?

I hope we can clarify the points above, soon. I'll then try to submit a pull request for the A2 (not plus) printer ASAP. I'm currently printing with my own A2 config based on ModMikes config and at least for now everything seems to be working fine...

EDIT: I've attached a picture of the wiring with colors on my Anet board. Also an example picture of the z stepper motor connector (left / bottom to right / up: red; blue; green; black), to show the order of the colors of the cables... (left to right: black; red; green; blue)

Strange, that those cables don't have the same order of colors on both plugs / sides of the cables... on the other hand, those two sides of the cable have 2 different kinds of plugs, not sure if that's normal for 3d-printers.

anet_board_steppers

anet_z_stepper

**Pull request merged**
