### PR TITLE
Update jgaurora_a5s_a1_with_bootloader.py

### PR DESCRIPTION
**Pull request by pinchies**
fix build script for jgaurora ... not sure why the files are being renamed to firmware.elf, but it broke the build script

### CODE REVIEW

**Comment by ellensp** [comment]
The firmware is always firmware.elf until you normally run objdump over it to convert to to the correct output format. .hex. .bin etc and rename as needed by the bootloader.

**Comment by thisiskeithb** [comment]
There's also some existing `os.rename`s, though one is disabled: https://github.com/MarlinFirmware/Marlin/blob/76a0cab782d3822776bf9455426fae940a6b82b8/buildroot/share/PlatformIO/scripts/jgaurora_a5s_a1_with_bootloader.py#L37-L38

**Comment by ellensp** [comment]
in the build env it has 
board_build.rename          = firmware_for_sd_upload.bin

So it should be creating the bin correctly

**Comment by ellensp** [comment]
Issue is in ini/stm32f1.ini

```
#
# JGAurora A5S A1 (STM32F103ZET6)
#
[env:jgaurora_a5s_a1]
extends                     = stm32_variant
board                       = genericSTM32F103ZE
board_build.variant         = MARLIN_F103Zx
board_build.offset          = 0xA000
board_build.rename          = firmware_for_sd_upload.bin
board_upload.offset_address = 0x0800A000
build_flags                 = ${stm32_variant.build_flags}
                              -DSTM32F1xx -DSTM32_XL_DENSITY
extra_scripts               = ${stm32_variant.extra_scripts}
                              buildroot/share/PlatformIO/scripts/jgaurora_a5s_a1_with_bootloader.py
```
buildroot/share/PlatformIO/scripts/jgaurora_a5s_a1_with_bootloader.py renames and build version with bootloader
but Marlin saw "board_build.rename          = firmware_for_sd_upload.bin" and renamed it before the script was called.

delete  "board_build.rename          = firmware_for_sd_upload.bin"  from the build environment

**Pull request closed without merging**
