### PR TITLE
Filament diameter changed. Hephestos uses 1.75mm filament.

### PR DESCRIPTION
**Pull request by silvio-didonna**
I don't know if this value affects something other than filament sensor at this time. However it would be better to maintain the correct value IMO.

### CODE REVIEW

**Comment by Rikrdoga** [comment]
This value only apply when filament width sensor is defined

**Comment by jbrazio** [comment]
This is the default value for all configurations, Hephestos config is not using it as the filament width sensor is disabled.

**Comment by silvio-didonna** [comment]
thank you,
If you want I'll close this pull request. On the contrary I'll rebase it. 
I just realized that the branch is wrong.

**Comment by jbrazio** [comment]
I would suggest to keep the default values equal on all configs which mean you should close this PR request. Nevertheless thank you for this PR, don't hesitate to submit more.

**Comment by silvio-didonna** [comment]
Ok.
I know that there isn't a filament width sensor on hephestos, but in the configuration file of hephestos 2 there is filament diameter set to 1.75.

**Comment by jbrazio** [comment]
That must have been a typo.
Doing a quick grep shows that `kossel_xl` is also using a non-default value.

**Comment by silvio-didonna** [comment]
ok, if you want I can fix it

**Comment by jbrazio** [comment]
Also have a look at `biv2.5` example config.

Please go ahead, if none of them use the filament width sensor just submit a PR against **RCBugFix** stating that you're change those settings for consistency between all example config files.

**Comment by silvio-didonna** [comment]
@jbrazio I'll make it tomorrow

EDIT: done

**Pull request closed without merging**
