### PR TITLE
[2.0.x] Add beginTransaction to HAL SPI

### PR DESCRIPTION
**Pull request by revilor**
Adds `beginTransaction` function to HAL SPI to set bus clock, bit order and data mode for the upcoming SPI transfer (same as in Arduino SPI library).

I implemented and tested the function for AVR, also implemented but untested for STM32 and Teensy35/36 based on Arduino SPI.

Someone familiar with Due and LPC1768 would have to implement the corresponding functions as I have no knowledge of those platforms.

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Sorry for being so late.

Can you provide some info on where this is going?

My only comment on the code itself concerns the spiClock argument.  Apparently this is a divisor.  I'd much rather see a speed being passed/specified.

@p3p  started a spi manager.  We just haven't had time to pursue it.  Is the attached what you're aiming for?

[p3p spi manager.zip](https://github.com/MarlinFirmware/Marlin/files/1604585/p3p.spi.manager.zip)

**Comment by p3p** [comment]
Although I stand by the API, mostly, the implementation may have been a bit optimistic with the auto reconfiguring of the hardware on cs_enable depending on which logical channel was selected, It was very nice running both the display and sd card over the same hardware spi channel though. If I was to continue the idea it would need considerable reworking, how to define software / logical channels in the config / pins ect .. the goal was to get multiple software and hardware spi channels going through the same interface and it never got that far.

**Comment by revilor** [comment]
@Bob-the-Kuhn I have no further plans regarding SPI at the moment. The project I'm working on just required a way to configure bit order and data mode of the SPI bus, in fact I just added the beginTransaction function from the Arduino SPI library to the HAL. And spiClock actually is the requested speed of the bus, the respective divider is calculated inside the function.

**Comment by Bob-the-Kuhn** [comment]
Chris - here's a very rough top level view of my interpretation of your SPI manager.  I hope you recognize some of it.

Please modify/correct as you see fit.

The **create_logical_spi_channel** routine is my idea of how to avoid making the configuration file a nightmare and push all the details down to the app.

The **modify_logical_spi_channel** routine is needed to accommodate @revilor's recent addition.

Should I open a topic to discuss a Marlin SPI manager?

----

```
one common API for SPIs.
  does not include SW SPIs for U8G graphics routines
     If we want to include U8G we'd need
       a) a method of specifying MOSI, SCK & cs
       b) rewrite of the U8G drivers
  
hardware layer is CPU dependent
  SPI hardware setup/changes done when changing logical channels
  hardware_channel 0 is the one used by the SD card
  
logical channel 0 uses hardware channel 0 and assumes the app controls the chip select  

logical channel 0 is setup by default, all others are created at run time

any RTOS features?

works with app controlled cs or will control cs

defaults to app controlled cs, logical channel 0




 
void spiInit(uint32_t spiRate, int8_t logical_channel /* = 0 */); // logical channel 0, rates of 0-6 treated as SD card rates

void spiBegin() {}  // SPI hardware setup/changes done when changing logical channels

void spiSend(uint8_t b, int8_t logical_channel /* = 0 */);
void spiSend(const uint8_t* buf, size_t n, int8_t logical_channel /* = 0 */);

uint8_t spiRec(int8_t logical_channel /* = 0 */);
void spiRead(uint8_t*buf, uint16_t nbyte, int8_t logical_channel /* = 0 */);

void spiTransfer(const uint8_t *buffer_write, uint8_t *buffer_read, int8_t logical_channel /* = 0 */);



int8_t create_logical_spi_channel(int8_t hardware_channel, pin_t cs_pin, uint32_t spiRate, uint8_t spi_mode, bool bit_order); 
  // cs_pin of -1 means the ap controls the chic select
  // spi_mode - SCK inactive high or low, clock edge leading or trailing
  // bit_order - msb or lsb first
  
bool modify_logical_spi_channel(int8_t hardware_channel, pin_t cs_pin, uint32_t spiRate, uint8_t spi_mode, bool bit_order, int8_t logical_channel /* = 0 */);  
```

**Comment by p3p** [comment]
My intention was spiInit, spiBegin ect style functions would be removed completely it was just a nice place to hook into the old SPI interface, I also hooked into the U8Glib driver using the new API. It worked well but was very much just a proof on concept. 

Everything in spi_impl.cpp is hardware dependant as long as a platform implemented the spi_api.h interface correctly it doesn't matter what is in that platforms implementation. For the LPC1768 that meant creating the 2 hardware channels, and then as a temporary measure hardcoding 3 logical channels. The logical channels would really have been added from the pins file? config? 

I have since had second thoughts of having static logical channels in that way as it may be too hard to configure (although static at runtime was the plan to keep AVR people happy), being able to initialise arbitrary channels at runtime would be better like: 

```
uint8_t hw_spi_channel = HAL::SPI::initialise(HAL::SPI::CHANNEL_1, cs_pin, config);
uint8_t sw_spi_channel = HAL::SPI::initialise(clk_pin, miso_pin, mosi_pin, cs_pin, config);
```

I think that may be the best way forwad? but as with everything I'm not sure how feasable it would be for AVR, (It's always what puts me off finishing this)

> any RTOS features?

I'm not sure its an RTOS feature just an asynchronous feature, the hardware channels have a busy flag :wink: 

> b) rewrite of the U8G drivers

I guess that is what I did, as I just modified the implementation as it was at that time to redirect through my new api

**Comment by revilor** [comment]
I'm new to Marlin so I don't know what the reasoning behind the HAL SPI was and what issues have been or will be solved using that API. But let me add my 2 cents on the topic anyway: I wonder if it's a good idea to have the SPI stuff in the HAL at all. The reason: there are lots of Arduino libraries out there for any kind of stuff using SPI. And probably all those libraries are based on the Arduino SPI lib. To use any of those libraries for Marlin you would have to reimplement all the SPI-related stuff based on the HAL. 

Or use the Arduino SPI lib and the HAL SPI in parallel. But then why have the HAL SPI at all? Wouldn't it be a better strategy to improve/extend the Arduino SPI library and then just use it in Marlin? I didnt't think this through any further, but maybe one could incorporate some kind of abstraction layer into the Arduino SPI  so if necessary you would be able to define a different SPI backend implementation - like Software SPI for example - and still use all those existing libraries out of the box.

**Comment by p3p** [comment]
Marlin 2.0 isn't limited to just the Arduino framework anymore, the platforms can be bare metal (well CMSIS) like the LPC1768 platform or use any framework / RTOS they want as long as they implement the required HAL interfaces Marlin needs. This means that we need to "shim" any device driver (lib) through a HAL interface so it can be implemented for all platforms, in general no library should be used directly without being redirected through a HAL shim, obviously if a library exists for the platform already (eg. AVR / DUE may both have Arduino libs) then the implementation will just pass straight through to that library, this will usually be optimised away at no runtime cost by the compiler. It's all a work in progress though and It hasn't even really been discussed very well between the main developers, and tbh I think it may only be me that is interested in the separation of Marlin from the Arduino framework

**Comment by Bob-the-Kuhn** [comment]
Here's the SPI users I found:
- SD card
- U8G hardware SPI
- U8G software SPI
- MAX6675
- DIGIPOTSS
- TMC stepper drivers
- dac084s085

I'm waffling on the U8G software SPI.  We're using a private library now so we can make the change.  On the other hand it's be a lot simpler to leave the software SPIs to U8G and it may make the transition to U8G2 easier.

Getting rid of the old spi API entirely ... hmmm ...  I've been assuming that there's something with the Arduino IDE that requires them.

The biggest issue I see is the effect on AVR FLASH size.  If there was a way to isolate the AVR boards from the size increase then we'd be able to proceed.  But then we couldn't convert the other things like the MAX6675.  I'm having visions of huge numbers in **#if AVR** conditional compilation sections.

Maybe it's best to keep the SPI manager in the 32 bit world and keep the current system for the 8 bit boards.  Ugly, ugly, ugly but a possible way forward.



----

```

8 bit boards stay as is
  lots of conditional compiles but won't increase FLASH usage

32 bit boards
one common API for all SPIs (both hardware & software).
    
hardware layer is CPU dependent
  SPI hardware setup/changes done when changing logical channels
  
no RTOS specific features
  there is a busy flag for each channel

works with app controlled chip select or will control cs


// proposed API calls

#ifndef _SPI_API_H_
#define _SPI_API_H_

#include <stdint.h>
#include "HAL_spi_pins.h"

namespace HAL {
namespace SPI {

enum SPI_CHANNELS {
  CHANNEL_0 = 0,
  CHANNEL_1,
  CHANNEL_2,
  CHANNEL_3,
  CHANNEL_4,
  CHANNEL_5
};

int8_t create_logical_spi_channel(int8_t hardware_channel, pin_t cs_pin, uint32_t spiRate, uint8_t spi_mode, bool bit_order);
int8_t create_logical_spi_channel(pin_t SCK, pin_t MOSI, pin_t MISO, pin_t cs, uint32_t spiRate, uint8_t spi_mode, bool bit_order);
  // returns logical channel number
  // cs_pin of -1 means the ap controls the chic select
  // spi_mode - SCK inactive high or low, clock edge leading or trailing
  // bit_order - msb or lsb first
  // spiRates for software SPIs would probably be 750KHz, 1 - 2MHz & 3-4MHz 
       750KHz for ST7920 displays, 
 
void rate(uint8_t channel, uint32_t spiRate);  // only used to change rates

void read(uint8_t channel, uint8_t *buffer, uint32_t length);
uint8_t read(uint8_t channel);

void write(uint8_t channel, const uint8_t *buffer, uint32_t length);
void write(uint8_t channel, uint8_t value);

void transfer(uint8_t channel, const uint8_t *buffer_write, uint8_t *buffer_read, uint32_t length);
uint8_t transfer(uint8_t channel, uint8_t value);

void end_transfer(int8_t logical_channel);  
   // so API can set cs inactive
  // maybe set cs inactive after every read/write/transfer and git rid of this call
}
}
 #endif /* _SPI_API_H_ */
 ```

**Comment by Bob-the-Kuhn** [comment]
The next step is an I2C manager.  Should be very similar.

**Comment by p3p** [comment]
I think you will always need a begin/end transfer (or as I preferred enable/disable cs) functions, its not always easy to prefill a buffer with an entire transaction before transmission and may want to send multiple single bytes without changing the cs also I don't think hardware spi has a default hardware cs pin so I think it will always need specified?

I'm not sure how much flash the AVR implementation would take, but I really hope we wouldn't have to keep both around with the preprocessor that would be a real mess.

**Comment by Bob-the-Kuhn** [comment]
I like the begin/end transfer functions.  Names can be easily changed.  I like begin/end transfer is it's a better description of what is happening and doesn't imply that the API is always controlling the cs.

My idea of begin is to fully initialize the SPI controller and, if applicable, set cs active.

End would be just setting cs inactive if applicable.

What is "ssel_override"for?

**Comment by p3p** [comment]
I'm not worried about the naming .. but why rate over frequency? and create_logical_spi_channel should just be create_channel, but honestly I don't mind :wink: 

ssel_override was just a flag that is set if the cs pin is manually enabled so it isn't changed automatically, It looks like it is never set though, I may have been changing things in that version of the code its been a while (the interrupts are not used either).

begin_transfer would have to check if the hardware channel was in use, whether the correct config was enabled, and if not reinitialise it. I only allowed the frequency to differ between the logical channels on the same hardware port as you could change it instantly without re-initialising and the display and sd cards used the same spi mode, (although reverse cs active state).

**Comment by Bob-the-Kuhn** [comment]
Frequency & create_channel sound good.

My first idea was to have the logical channel creation at the top level. Keeping it in the hardware level allows adding items like the settings for the frequency registers to be part of the structure.

In the general case things like spi mode and msb/lsb first can also change between logical channels.  I think it's best to completely re-initialize the SPI controller when a begin_transmision is received.

**Comment by p3p** [comment]
> My first idea was to have the logical channel creation at the top level. Keeping it in the hardware level allows adding items like the settings for the frequency registers to be part of the structure.

I'm not sure what you mean, the hardware port(channel) definitions should always be hidden behind the interface as it will always be platform specific and can't change?

I agree that logical channels should be able to have any mode even when on the same hardware port, how that is accomplished will be platform dependant and may incur a performance penalty, It will be better to only reinitialise if required (mode change), with caching the frequency registers I couldn't even see the delay on my logic analyser when it switched between lcd and sdcard, but that was more than likely due to skipping slow cmsis init functions.

**Comment by Bob-the-Kuhn** [comment]
@revilor - what are the values for your spi mode and what are their meanings?

Something like this made up example?
0 - sck idle low, leading transition clocks data into slave
1 - sck idle high, trailing transition clocks data into slave
2 - sck idle high, leading transition clocks data into slave
...
46 - we all go out for a beer

**Comment by p3p** [comment]
Hopefully its just the standardish convention?
https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus#Mode_numbers

**Comment by revilor** [comment]
@Bob-the-Kuhn The value set for dataMode is 

SPI_DATAMODE_0
SPI_DATAMODE_1
SPI_DATAMODE_2
SPI_DATAMODE_3 

as defined in SPI.h. Following the SPI data mode convention.

**Comment by Bob-the-Kuhn** [comment]
BEGIN_TRANSMISION and END_TRANSMISION are out because the LCD routines have nothing similar.

The SD card and the RRDFG display are working.  There's a problem switching baud rates which is probably caused by problems switching channels.  

Yes, a little bit of research convinced me that there is a SPI data mode convention.  The LPC's SPI controller matches it exactly so it was easy to implement.

By any chance can one of you point me to a software SPI that implements the data modes?  There has to be a better way than the one I came up with.

**Comment by revilor** [comment]
@Bob-the-Kuhn RIOT (https://github.com/RIOT-OS/RIOT) according to their documentation has support for data modes in the software SPI (see http://riot-os.org/api/group__driver__soft__spi.html). If you want to have a look at the implementation, it's in RIOT/drivers/soft_spi/soft_spi.c

**Comment by Bob-the-Kuhn** [comment]
Here's what I have so far.  I've tested both the hardware SPI and software SPI sections with the SD card and with the RRDFG LCD.  

[SPI_manager_LPC1768.zip](https://github.com/MarlinFirmware/Marlin/files/1614226/SPI_manager_LPC1768.zip)

Right now it uses a static structure of 20 elements for the logical channels.  I have no idea how many logical channels are really needed.  Options are to pick a size & stick to it, make it a configuration item or go to dynamic arrays.

To do items:
1) add a way to warn the user if out of logical channels
2) get feedback from Chris
3) start looking at an AVR version

**Pull request merged**
