### PR TITLE
Anycubic Kossel Z probe invert fix

### PR DESCRIPTION
**Pull request by MrDiba**
### Description
This fixes the the NO/NC issue between the V1 and V2 probe on the Anycubic Kossel Delta printer. 

### Benefits

Fixes the probe issue creating an nicer "out of the box" experience.

### Related Issues

#11858 this one has already a fix for the bugfix-2.0.x branch.
#12092 had the same problem as the issue above.

### CODE REVIEW

**Review by MrDiba — COMMENTED** [review]
Hi Thinkyhead, I tried to do the exact same code as you did with this commit but when compiling the code the code would error on me with the following error code:

```
In file included from sketch/MarlinConfig.h:39:0,
                 from sketch/digipot_mcp4451.cpp:23:
macros.h:115:25: error: pasting "SWITCH_ENABLED_" and "(" does not give a valid preprocessing token
 #define ENABLED(b) _CAT(SWITCH_ENABLED_, b)
```

```
sketch/HAL.h:153:22: note: in definition of macro '_CAT'
 #define _CAT(a, ...) a ## __VA_ARGS__
```

```
sketch/SanityCheck.h:830:11: note: in expansion of macro 'ENABLED'
     #elif ENABLED(Z_MIN_PROBE_ENDSTOP_INVERTING) != ENABLED(Z_MIN_ENDSTOP_INVERTING)
```

```
Configuration.h:650:33: error: missing binary operator before token "("
 #define Z_MIN_ENDSTOP_INVERTING (ANYCUBIC_PROBE_VERSION + 0 == 1) // V1 is NO, V2 is NC
```

That is the reason I used the long (bit messy) notation.
Could you please try this for your yourself?

**Comment by thinkyhead** [comment]
@MrDiba — I've removed all use of `ENABLED`/`DISABLED` with the "INVERTING" options, because they're not compatible with `ENABLED`/`DISABLED`.

**Comment by MrDiba** [comment]
@thinkyhead  — I do not understand what you are saying, but when I download the current debug-1.1.x branch and insert the Anycubic Kossel config files and try to compile it it will result in a error as said above.

**Comment by thinkyhead** [comment]
Don't expect a lot of patches to `bugfix-1.1.x`. We are moving on to 2.0 now. Please do all further testing with `bugfix-2.0.x`.

**Comment by MrDiba** [comment]
That is alright. All I'm saying is that the commit you made in the configfile triggers something in the SanityCheck when compiling and failing the build. My advice is to revert to commit 8371f632c190d2b21a754864d4c3620d603606bb to have a working config file in the `bugfix-1.1.x`.

**Comment by thinkyhead** [comment]
Issue is now patched.

**Pull request merged**
