### PR TITLE
Use preheat labels in place of "PLA" and "ABS"

### PR DESCRIPTION
**Pull request by Ludy87**
PLA to PREHEAT_1
ABS to PREHEAT_2

### CODE REVIEW

**Comment by thinkyhead** [comment]
Makes you wonder why these custom items exist, duplicating existing items.

**Comment by Ludy87** [comment]
Sorry, I don't understand your message.

**Comment by thinkyhead** [comment]
Items in `CUSTOM_USER_MENUS` duplicate the existing preheat items. I guess they make good examples though.

**Comment by Ludy87** [comment]
My favorites 
```cpp
    #define USER_DESC_2 "FAN-Speed max"
    #define USER_GCODE_2 "M106 S255"
    
    #define USER_DESC_3 "FAN-Speed half"
    #define USER_GCODE_3 "M106 S127"
```

**Pull request merged**
