### PR TITLE
Redirect autoreport to all serial ports

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Resolves reported issues with touchscreens where auto report does not report temps to hosts such as octoprint. Reported on CR6 and E3V2.

### CODE REVIEW

**Comment by X-Ryl669** [comment]
Is it what everybody want ? (your change is global for everyone).

Wouldn't it be better if you updated the port mask via `Temperature::auto_reported.report_port_mask = SERIAL_ALL;` in your HAL ?

If I understand the code correctly, in `autoreport.h`, if you have a multiserial configuration (which it seems you have), then all report are already reported to all serial (see in  the constructor, it sets the mask to SERIAL_ALL and the `tick` method call PORT_REDIRECT with this mask before reporting).

**Comment by InsanityAutomation** [comment]
@X-Ryl669 in this case the second serial port is for the touchscreen, and the reports vanish into the ether. Adding the above restored them to the only gcode configured serial port. We did not have the second serial interface configured outside the DGUS serial port.

Glancing for what you had referenced, 

TERN_(HAS_MULTI_SERIAL, PORT_REDIRECT(report_port_mask));

This could be changed to #IF HAS_MULTI_SERIAL || defined(LCD_SERIAL_PORT) as a functionally equivalent as would also set it to redirect to all. Just does the same thing a little higher up the ladder.

**Comment by X-Ryl669** [comment]
Can you describe your setup at bit more ?

**Comment by InsanityAutomation** [comment]
Stock ender 3 V2 with DWIN / DGUS touchscreen and stock CR-6 with Extui based serial touch screen. Both set and use LCD_SERIAL_PORT for communication. Its likely if I tested this on the Taz pro with FTDI using ExtUI we would find the same.

Here is one of the branches where the problem was exhibited and the additional redirect resolved it.
https://github.com/InsanityAutomation/Marlin/tree/CR-6Devel

The configuration here also exhibited the issue
https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20V2

And was fixed with the above in my branch here 
https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin2.0_Bleeding

Essentially, given the intent this function should always redirect to all serial ports, and the lcd serial port is causing it to lose that association and it isnt caught as it only broadcasts to all with multi serial enabled. Given the traffic rate, last used serial port will almost always be the lcd serial port.

**Comment by X-Ryl669** [comment]
I'm still not sure I understand the issue. In the configuration you've posted, you have a single serial port. Because of this, no multiserial get instantiated. If you look at Marlin/src/core/serial.h, when HAS_MULTI_SERIAL is not defined, then PORT_REDIRECT does nothing (it's a NOOP).

If you need to use another serial port (or to duplicate the serial port output to 2 physical serial port), you need to enable 2 serial port in the configuration, and then it'll define HAS_MULTI_SERIAL and the PORT_REDIRECT will do something. But in that case, your patch will do nothing since, by default, autoreport does a port redirect to all serial port.

Currently, the autoreport does redirect to all serial port by default (see the tick method, that's where all report are being generated).

**Comment by thinkyhead** [comment]
> Resolves reported issues with touchscreens where auto report does not report temps to hosts such as octoprint. Reported on CR6 and E3V2.

What are the issue numbers so that we can compare notes with the original testers?

**Comment by thinkyhead** [comment]
> But in that case, your patch will do nothing…

Let's take a closer look. At this time `HAS_MULTI_SERIAL` doesn't consider whether there is an `LCD_SERIAL_PORT`.

**Comment by thinkyhead** [comment]
> auto report does not report temps to hosts

As it stands now the redirect for auto-reports should be reporting to all serial 1 and serial 2 connected hosts. Perhaps this patch is only hiding another problem where a previous redirect (presumably to the touch screen serial output) isn't getting reset back to the previous serial destination…? That should be investigated as a potential root cause, especially as it would be likely to crop up again in some other place.

**Comment by thinkyhead** [comment]
> the lcd serial port is causing it to lose that association

That would seem to be the most likely scenario, but it's not clear yet why. The Creality DWIN, for example, is sending bytes directly to the display's serial object in a way that should have no effect on the "current port" which is used by `SERIAL_ECHO`. If the `multiSerial.portMask` is being changed in some way that breaks the redirect before `Helper::report` it seems like the cause should be obvious. So far, not so much… I will keep looking.

Some serial LCDs can send commands to Marlin over their serial port like a host and Marlin reacts by redirecting serial output during the G-code, but the DWIN screen isn't set up to work like that so Marlin should never be redirecting any output back to it as if it was a command source.

**Comment by thinkyhead** [comment]
@InsanityAutomation — For isolation testing see if you can run one of those machines with the display disabled to see whether the same problem arises. I can't see anything in the support of the Ender-3 V2 (for example) that would lead to the breakage of `SERIAL_REDIRECT`, no matter how many serial ports you might have, or what kind of display you are using.

At this time we don't have CR-6 SE support ready, so that's not something we can fix here yet.

**Comment by X-Ryl669** [comment]
In his configuration, he only has 1 serial port, so there is no multiserial instance declared (and none instantiated). PORT_REDIRECT is a no-op in that case. Maybe you've understood his serial configuration, but I haven't. As far as I've understood, he is using the lcd serial port as the printer's output port that's connected to octoprint. Yet, his configuration does not declare any LCD_SERIAL_PORT, so I don't understand why it would be created either. 

Wouldn't it be simpler to just declare SERIAL_PORT to point to the LCD serial port in Configuration.h and forget about multiserial here ?

**Comment by thinkyhead** [comment]
> In his configuration, he only has 1 serial port, so there is no multiserial instance declared…

The OP only says "_…resolves reported issues with touchscreens…_" so it is possible only other users did testing. Afterward I guess they reported the problem was gone, and so that is where our investigation shall begin. This PR indicates one workaround, so now we've got to…
- actually reproduce the bug, and
- find the root cause.

**Comment by X-Ryl669** [comment]
Yes, I don't understand how the initial patch could do anything.
Actually, AutoReport::tick calls:
```
PORT_REDIRECT(SERIAL_ALL);
Helper::report();
```
The patch does (pseudo code):
```
Helper::report()
{
  + PORT_REDIRECT(SERIAL_ALL);
[...]
```
So unless I'm mistaken, whatever the state of MULTI_SERIAL, the patch can not resolve anything since it's doing the exact same thing that was done before without the patch.

**Comment by thinkyhead** [comment]
> …the patch cannot resolve anything…

Some distrust of the `REMEMBER` macro (and so also the `PORT_REDIRECT` macro) has been expressed. But in all my testing it works correctly.

> in this case the second serial port is for the touchscreen

I can't see any issue on the Ender-3 V2, which doesn't have a touch screen. Auto reporting goes to the appropriate serial port. I don't yet have a branch of Marlin ready to test on the CR-6 SE, but once that is completed then I can try investigating the issue on that machine.

**Comment by X-Ryl669** [comment]
Yep, sorry, it's not a criticism. My remark is that there are 2 successive PORT_REDIRECT with the same parameter with the patch applied, so the latter does not change anything. The RAII works well, so Remember<T> works as well. It's just useless in case it's instantiated with the same value twice and that's what the patch does.

**Comment by InsanityAutomation** [comment]
Just to drop a quick update as I'm still running around in circles... I do agree this is likely hiding a different problem. Disabling autoreport caused octoprint to function normally as it fell back to polling.

Issues were reported to tinymachines via email, not here so I don't have a link to them however the report was simply temperature not updating in octoprint. 

It's entirely possible as I ran through it I tested a branch with the above and autoreport off by accident, but wanted to toss something up to point to the issue and area it was in before I have time to get back to it tomorrow. I knew the serial refactor likely had an impact and there was a good chance the root cause would jump out at someone else rather than my bandaid and this would just vanish :) For a CR6 test, just use the branch linked above and turn autoreport back on.

**Comment by thinkyhead** [comment]
I'll do careful testing on the CR-6 SE tonight and try to isolate the issue.

**Pull request closed without merging**
