### PR TITLE
Updates for Touch UI FTDI EVE on AVR

### PR DESCRIPTION
**Pull request by thinkyhead**
Based on work by @RudolphRiedel and @sl1pkn07. See https://github.com/MarlinFirmware/Marlin/issues/16628#issuecomment-617511620

Changes to get this controller working with AVR boards.

### CODE REVIEW

**Comment by sl1pkn07** [comment]
the real work is done by @RudolphRiedel. i only collect it and try to test it

**Comment by sl1pkn07** [comment]
i made a changes in my repo (i forgot edit the pin draw in `pins_RAMPS.h` ramps and uncomment a #error in `pins_BTT_SKR_E3_DIP.h` (also in `pins_RAMPS.h`)

how i can push it here?

**Comment by thinkyhead** [comment]
> how i can push it here?

Two possible options…

---

- Check out the branch this PR is based on:
  - https://github.com/thinkyhead/Marlin/tree/TOUCH_UI_FTDI_EVE
- Make changes and add commits to your working copy and push to your own fork.
- Submit a PR to my `TOUCH_UI_FTDI_EVE` branch and when accepted it is added to this.

The GitHub Desktop interface may simplify the last 2 steps.

---
GitHub may show direct editing options in the top-right corner when viewing a file under the Files tab, so you can submit a "proposed change" and when it is accepted it becomes a commit.

**Review by sl1pkn07 — CHANGES_REQUESTED** [review]
fffffff

**Pull request merged**
