### PR TITLE
Change CR10_STOCKDISPLAY product link

### PR DESCRIPTION
**Pull request by minding-myown-business**
Solves issue #26668 

### Description

Fixes broken link (issue #26668 )

### Requirements

no requirements, it is an issue in `configuration.h`

### Benefits

fixes broken link

### Configurations

not needes

### Related Issues

fixes "bug", issue #26668

### CODE REVIEW

**Comment by ellensp** [comment]
not official creality page, is a 3rd party..    Perhaps use https://www.aliexpress.com/item/33052591632.html  which is actually creality

**Comment by ellensp** [comment]
Im not really comfortable linking to a 3rd party site that is not official Creality for a Creality product. It could be seen as advertising or endorsing them.. 

Perhaps we should just point  it to https://marlinfw.org/docs/hardware/controllers.html#cr10_stockdisplay and let any user search for a place to get one.

**Comment by minding-myown-business** [comment]
> Perhaps we should just point it to https://marlinfw.org/docs/hardware/controllers.html#cr10_stockdisplay and let any user search for a place to get one.

Alright! I hadn't seen that page before but linked it in [acfa478](https://github.com/minding-myown-business/Marlin/commit/acfa4785ab2b915846d68d7355b1e68006edc2eb)

**Comment by ellensp** [comment]
That display controller page is one of my pet projects..  First public appearance was on Sep 24, 2023, still adding to it as images are provided

**Pull request merged**
