### PR TITLE
New colors for Marlin TFT COLOR UI

### PR DESCRIPTION
**Pull request by DvoraNoob**
I added 2 new colors to select in the Marlin Color UI

I did it because I don't like the original colors

I only tested in my MKS ROBIN NANO V2 with MKS TFT35 V2

### CODE REVIEW

**Comment by rhapsodyv** [comment]
You need to send this PR to bugfix branch, not the 2.0.x one.

Add some photos of the new themes.

One question: why should we support hard coded pre made themes when all the colors (almost at least) can be overwritten by the configuration?

**Comment by rhapsodyv** [comment]
See this PR: https://github.com/MarlinFirmware/Marlin/pull/19484

**Comment by DvoraNoob** [comment]
I did this because it is easier to change colors, and not everyone knows how to change colors in the tft_color.h file, I also put variables that were in other files in tft_color.h, now you can change all colors in tft_color.h

I'll take the photos of the predefined themes and make a pull request again on the Bugfix branch

**Comment by rhapsodyv** [comment]
Take a look in the above PR. You don't need to change the colors, but the color "configs".

**Pull request closed without merging**
