### PR TITLE
G2 and G3 Math Error Correction (referencing issue #20258)

### PR DESCRIPTION
**Pull request by ghost**
Utilize either CW or CCW angle depending on user specification (via
G2/G3) when calculating minimum number of segments (min_segments)

### Description

Short Version:

The goal of this pull request is to essentially ensure that equivalent G2 and G3 commands utilize the same number of minimum segments when the arc is converted into linear movements. Currently a G2 command will utilize the number of segments that a G3 command with the same target vector would utilize. In other words, G2 commands presently would never utilize the correct number of segments. G3 works perfectly. This pull request attempts to fix G2. 

Longer Explanation:

Current code:
atan2 returns the shortest CW **or** CCW angle it takes to reach the target vector. Negative values returned indicate CW motion and positive values indicate CCW motion. If the value returned by atan2 is negative, which means a CW angle, we add 360 degrees (2pi radians) to get the equivalent CCW angle to reach the same target vector. Thus we went from a CW or CCW angle to only a CCW angle; or with direct numbers: we went from -pi to +pi to 0 to +2pi. This value is then used to calculate minimum number of segments. This works perfectly for G3 because the angular travel reflects a CCW angle. But for G2, this is incorrect and behaves differently than G3. For G2, we must not utilize CCW angles, but CW angles. 

Pull request code:
To convert a CCW angle to CW, we simply subtract 360 degrees (2pi radians). This must be done before minimum number of segments is calculated and not after. This is done because Marlin is the not supposed to decide if motion is CW or CCW; the user via specifying G2 versus G3 decides which direction the motion is supposed to be. Hence, we calculate the correct angular travel for the direction of motion and then use that value to calculate minimum number of segments. But given that G2/CW motion will have negative number, we must simply use the ABS function to ensure the value is always positive when calculating the correct number of minimum segments. 

To remedy what I described above, I created a switch statement that clearly describes what is happening for each possibly variation of G2/G3 and value returned by atan2. Please read the comments if still confused and also please see the diagram i posted below as well. I was uncertain before if this was a bug, but now I am certain having gone through all the math. This is definitely a bug. 

Here is a visual layout of the root problem that I used in the original issue. 
100005351-6c450280-2d8e-11eb-9e3d-4389e5d7352a

### Benefits

1.) G2 and G3 now behave the same and the math makes more logical sense
2.) the switch statement has better readability and makes clearer what is happening with the respective comments

### Configurations

The default config files work perfectly assuming "#define ARC_SUPPORT" is enabled, which it is. 

### Related Issues

#20258

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks! I suppose that angles over 180° are now becoming more common, especially with at least one slicer now producing actual G2 / G3 commands.

**Comment by ghost** [comment]
No problem!

**Review by yash-fn — COMMENTED** [review]
If you don't like switch cases you could use this instead with a simple xor
```
if ( (angular_travel < 0) != clockwise ) {
  angular_travel += RADIANS(360) * (1 - 2 * clockwise);
}
```
as a bonus i feel the logic is simpler and more readable with fewer lines.

**Comment by yash-fn** [comment]
oh sorry. I don't know what this code review thing is. I thought I was just leaving a comment. Please let me know if I need to undo something.

**Comment by thisiskeithb** [comment]
> oh sorry. I don't know what this code review thing is. I thought I was just leaving a comment.

You did. On a merged pull request from Nov. 2020.

**Pull request merged**
