### PR TITLE
Fix build fail on windows

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

PlatformIO points to a invalid compiler on startup, on Windows. I did a quick fix to find the current g++. We need to work more on that later.

Its a quick fix. We may work more on this windows issue later.

### Related Issues

#18720
#18699

### CODE REVIEW

**Comment by thinkyhead** [comment]
> PlatformIO points to a invalid compiler on startup, on Windows.

On my macOS system `/usr/bin/cc` points to `clang` and this might not always be desirable either.

When building for AVR, PlatformIO is using `avr-g++`, and I'm sure it picks different compilers for different platforms. So, one way to ensure the correct compiler is to get PlatformIO to do the `-dM` build by creating a new `[env:config]` entry and in the Python script invoke `pio` to do the build of that env. I don't think it matters which architecture we specify for this step, as long as PlatformIO is allowed to pick the compiler. However, it would be best to have it use the same platform as the target so that it doesn't *always* download the AVR toolkit.

**Comment by thinkyhead** [comment]
Poking around I see there is a `CC` entry in the dictionary similar to the `CXX` entry, except in my case the value for the `CC` key is lowercase `cc` which is more correct on my system. Have a look at the `CC` entry on Windows to see if it's in any way better.

**Comment by thinkyhead** [comment]
Darn. The value we want is only available in `projenv` which doesn't exist in pre: scripts.

So, we are back to choosing between `CXX` and `CC` for the build tool. With my system having `('CXX', 'CC')` and `('CC', 'cc')` it implies that the `CXX` value is the _key_ for the compiler name, and not the compiler name itself.

So, of course this works for me: `env.get(env.get('CXX'))` but I don't expect that to work everywhere.

**Comment by bywebberen** [comment]
DID ANYONE FIX THIS - In a way that normal windows 10 users can fix ??

**Comment by rhapsodyv** [comment]
> DID ANYONE FIX THIS - In a way that normal windows 10 users can fix ??

Sorry, I didn't understand what you mean. This is the fix.

Open an issue if you think there's a bug.

Thanks.

**Pull request merged**
