### PR TITLE
New Board I3DBEEZ9

### PR DESCRIPTION
**Pull request by I3DBeeTech**
### Description
stm32f407zgt6 Based 9 Drive board.

<!--

### CODE REVIEW

**Comment by I3DBeeTech** [comment]
hi @thinkyhead @thisiskeithb  can you please check into this ?
This is new upcoming board to market by this new week. 
we request for the support from marlin .
Thank you

**Comment by I3DBeeTech** [comment]
i3dbee

This is our new board

Hi there...!!!
Hope you are doing great,
This is venkat from I3dbee technologies pvt ltd, INDIA
we are releasing few 3d boards into the market and we request to support us with your global popular firmware. since this is our startup and lack of funds we are sponsoring the lowest from your list. but sure we will get to shop and higher sponsoring category. Your support is most valuable.
can you please look into it ?

Thank you for your Amazing efforts and Knowledge. @thinkyhead  and @thisiskeithb

**Comment by EvilGremlin** [comment]
Looks nice, you get brownie points for using beefy actual ST chip.
I think there is room to squeeze layout and save cost, while also adding real EEPROM and SPI flash, or at least leave pads (if you have free MCU pins). 1MB of flash is quite a lot, but SPI flash will futureproof this. Native TFT displays are getting more popular, and while only LVGL_UI use external flash now, this won't always be the case.

**Comment by I3DBeeTech** [comment]
> Looks nice, you get brownie points for using beefy actual ST chip. I think there is room to squeeze layout and save cost, while also adding real EEPROM and SPI flash, or at least leave pads (if you have free MCU pins). 1MB of flash is quite a lot, but SPI flash will futureproof this. Native TFT displays are getting more popular, and while only LVGL_UI use external flash now, this won't always be the case.

yes we agree with you.
hopefully we will do in next project. in this board most of the MCU pins were used
Thank you for the compliment :)

**Comment by I3DBeeTech** [comment]
Greeting @thinkyhead 
any update on the pull request ..?
based on your commit we will be launching our board to market which is our first product
Thank you

**Comment by thinkyhead** [comment]
I can do a final cleanup on this and get it merged today. I'm not sure how it got lost in the shuffle. Just very focused on other tasks lately, I guess!

**Comment by I3DBeeTech** [comment]
> I can do a final cleanup on this and get it merged today. I'm not sure how it got lost in the shuffle. Just very focused on other tasks lately, I guess!

Thank you @thinkyhead

**Pull request merged**
