### PR TITLE
Stock Ender-3 Pro

### PR DESCRIPTION
**Pull request by Kaimberex**
Stock Ender 3 Example Configurations for Vanilla Marlin

### Description
Bone Stock Ender 3 Pro Marlin Example Configuration

### CODE REVIEW

**Comment by Kaimberex** [comment]
Bone Stock Ender 3 Pro Configuration of Vanilla Marlin

**Comment by Kaimberex** [comment]
Bone Stock Ender 3 Pro Configuration of Vanilla Marlin

**Comment by Bob-the-Kuhn** [comment]
You'll need to go over to the [Marlin example configurations page](https://github.com/MarlinFirmware/Configurations) to make this addition.

Here's a [PR](https://github.com/MarlinFirmware/Configurations/pull/889) that was recently merged that does something similar.  You can use it as a model for your PR.

There are already [multiple example configurations](https://github.com/MarlinFirmware/Configurations/tree/import-2.1.x/config/examples/Creality/Ender-3%20Pro) for this printer.  What is the value add of your example configuration?

**Comment by Kaimberex** [comment]
This was done in error

**Pull request closed without merging**
