### PR TITLE
G34: fix bugs; add HOME_AFTER_G34 option

### PR DESCRIPTION
**Pull request by mummelix**
### Requirements

-Multiple Z axis
-Z_STEPPER_AUTO_ALIGN

### Description

Does four things:
1) The formula for calculating z_probe in G34 was messed up. Now, it used Pythagoras' theorem correctly, calculating z_probe as the maximum distance of any 2 Z_STEPPER_ALIGN_STEPPER_XY points, multiplied by G34_MAX_GRADE.

2) If G34 is aborted, declare the Z axis as not homed, because the coordinates are messed up in that case. Moving to Z=0 would probably ram into the build plate, for instance.

3) Minor display bugfix

4) Added an option to omit the re-homing of Z at the end of G34 and instead calculate the Z height using z_measured_min:

z_measured_min is used, because even if target accuracy is achieved, the stepper correction routine is run a last time and moves each stepper another tiny bit, except the one with the smallest Z coordinate, so that all steppers are at z_measured_min:

`float z_align_move = z_measured[zstepper] - z_measured_min;`

Therefore, if this variable is subtracted from current_position.z, the Z height should be correct again:

`current_position.z -= z_measured_min - (float)Z_CLEARANCE_BETWEEN_PROBES;`

I tested this on my machine, with the new approach and with the old home-again variant, i.e. G34, then G0 X150 Y150 Z0. The difference in Z height was about 0.1 or 0.2mm. The bed has a bump of about 0.1mm, so that could explain the lack of precision. That's why I made this feature optional (Configuration_adv.h)

### Related Issues

Follow-up to PR #17052. I create a new PR because I messed up my fork repository, sorry.

@thinkyhead suggested `CBI(axis_known_position, Z_AXIS)`. That would allow to re-enable the too-early sanity check, but would take flexibility away from the amount by which the Z=0 level can be exceeded:

`const float z_probe_low_point = TEST(axis_known_position, Z_AXIS)
                              ? -offset.z + Z_PROBE_LOW_POINT : -10.0;`

-10.0 is hardcoded. If the user wants to be able to correct larger misalignments for some reason, this would be not possible. If the user defines a small G34_MAX_GRADE, -10.0 could be "too much" and create a safety-risk on its own. Honestly, I think the way it is now isn't too bad, if you don't want to change the probe routines themselves.

### CODE REVIEW

**Review by mummelix — COMMENTED** [review]
I think you reintroduced a bug here:

`SERIAL_ECHOLNPAIR("PROBEPT_", ('0' + i), ": ", z_measured[i]);`

prints the ASCII codes for '0', '1', '2':

> Recv: PROBEPT_48: 14.16
Recv: PROBEPT_49: 14.16
Recv: PROBEPT_50: 14.17

whereas

`SERIAL_ECHOLNPAIR("PROBEPT_", i, ": ", z_measured[i]);`

prints the actual `i` numbers:

> Recv: PROBEPT_0: 14.08
Recv: PROBEPT_1: 14.08
Recv: PROBEPT_2: 14.07

**Comment by sjasonsmith** [comment]
@jufimu12 I noticed the same thing yesterday it is fixed in one of my open PRs.
It uses ‘1 + i' so the prints are for 1, 2, and 3.

Oh wait, I didn’t fix this! I fixed a similar issue when points are printed back using M422. I missed this one!

**Comment by sjasonsmith** [comment]
It looks like @InsanityAutomation foxed it along with his other changes in #17122

**Comment by InsanityAutomation** [comment]
Yup, I saw it in Brett's post on discord this morning and dropped it in. Now I see it here too :)

**Pull request merged**
