### PR TITLE
TFT_NEWCOLOR_UI

### PR DESCRIPTION
**Pull request by EvilGremlin**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Removed all unrelated changes.
```sh
git fetch upstream ; git merge upstream/bugfix-2.0.x
git diff HEAD upstream/bugfix-2.0.x | git apply
```

**Comment by thinkyhead** [comment]
… Fixed and properly re-integrated `TFT_NEWCOLOR_UI` …

**Comment by EvilGremlin** [comment]
Wow thta's a mess. why github add whole branch to PR automatically now? I thought it'll be PR for one commit. Please don't do merge all that junk.

**Comment by thinkyhead** [comment]
> I thought it'll be PR for one commit.

You are submitting all changes in your branch when you create a PR. To isolate a commit, cherry-pick it into a new branch before starting your PR…
```
git checkout upstream/bugfix-2.0.x -b my_new_PR
git cherry-pick a1b2c3d4e5
```

**Comment by EvilGremlin** [comment]
Yea, figured... Thought github would be smart enough to set cherrypick for me, but it's apparently not. Or is that how you've set it up?

**Comment by cp2004** [comment]
GitHub has always taken the whole branch, at least as long as I've known it.

**Comment by thisiskeithb** [comment]
> GitHub has always taken the whole branch, at least as long as I've known it.

There's no way for git/GitHub to know which commits you intended to include in the PR, so the entire branch is included.

Cherry picking is great when you accidentally forget to branch or get sidetracked with unrelated work on a current branch and can't easily stash/pop changes.

**Comment by EvilGremlin** [comment]
There is very easy way - don't include commits newer than PR. Oh well, there are upsides and downsides to each way.

**Pull request merged**
