### PR TITLE
Remove 6x9 font

### PR DESCRIPTION
**Pull request by AnHardt**
in dogm_lcd_implementation.h
by using standard font and
shifting down temperature displays by one pixel
Saves 2300 bytes.
Bevore:
picture 113

Font replaced:
picture 112

And temperatures shifted down:
picture 114

### CODE REVIEW

**Comment by thinkyhead** [comment]
Huh, that custom font is a bit more readable. Seems a shame to have to lose readability to save SRAM.

**Comment by AnHardt** [comment]
I agree - the zeros are a bit on the ugly side.
I didn't make the font nor selected it for Marlin, but i could change it.
@boelle asked for code size. Just an option.
On the other side this could be optional like BIG_EDIT_FONT. How about that?
Another option could be to use the 6x9 font in the menu. I'll make pictures.

**Comment by AnHardt** [comment]
No. The 6x9 in the menu is a bit to small. 4 pixel for the small letters is not enough.
picture 116

**Comment by AnHardt** [comment]
How about this one?
picture 117
picture 118
Looks a lot cleaner.

**Comment by alexborro** [comment]
I like it.
Em 16/03/2015 20:34, "AnHardt" notifications@github.com escreveu:

**Comment by avluis** [comment]
Much better looking, does the second font option save a similar amount of sram?

**Comment by AnHardt** [comment]
The last pictures i posted show a font saving another 21 bytes. But as far i have investigated this the saving will be in progmem not in sram.

**Comment by thinkyhead** [comment]
I'm pleased with the most recent look. So, this is pretty close to ready!

**Comment by ntoff** [comment]
While we're at it, do we really need an animated fan logo? I've noticed while printing it doesn't animate smoothly all the time anyway.

**Pull request merged**
