### PR TITLE
Nucleo STM32H743ZI support

### PR DESCRIPTION
**Pull request by thinkyhead**
Based on #13657 by @dekra54

---
> This Pull request adds the basics for the Nucleo STM32H743 as a new Printer Board. There is still much work to do and I'm already working on some Hardware. I'm more a hardware guy so some help from more experienced programmers is appreciated.

### CODE REVIEW

**Comment by xC0000005** [comment]
I wonder if this is needed with the work done recently on HAL_STM32?

**Comment by sjasonsmith** [comment]
So this is adding a fourth STM32 HAL?

I thought the intention was to eliminate STM32_F4_F7 to get down to two...

**Comment by thinkyhead** [comment]
> I wonder if this is needed with the work done recently on HAL_STM32?

This PR is presented to raise and explore that question.

> I thought the intention was to eliminate STM32_F4_F7 to get down to two...

This PR is so we can compare what was presented for STM32H7… and see how it comports with the recent work on STM32 HAL. This includes a pins file, which we might want to keep. If most of this is superseded now, which is what I expect, that is great. I just want to make sure there is nothing we're forgetting, and I want to make sure we have some kind of example for the STM32H7… going forward, with at least a good pins file and a good `platformio.ini` env entry.

**Comment by LinoBarreca** [comment]
going with another hal is out of any logic for me since the STM32 should be able to handle them all.

**Comment by thinkyhead** [comment]
> going with another hal is out of any logic for me since the STM32 should be able to handle them all.

If we could also get rid of `HAL_STM32F4_F7` that would be great.

**Comment by LinoBarreca** [comment]
Not at the computer until tomorrow so I can't check but...Are there features in f4/7 that aren't implemented in stm32? If not just retarget boards to stm32 in platformio.ini and leave that f4/f7 unused. No user will notice the difference....and it's an easy revert just in case. If in one month we will not receive any major complaints (for something that we didn't consider) we will eliminate the hal itself.

**Comment by thinkyhead** [comment]
> Are there features in f4/7 that aren't implemented in stm32?

The only question concerning us is whether users can use Arduino IDE to build Marlin for the STM32 boards that Arduino IDE supports? It would be good to make sure these builds work, and allow Marlin to be adaptable to the alternative frameworks that they might use.

**Pull request closed without merging**
