### PR TITLE
Offset XY movement during Z-Probe Wizard prep

### PR DESCRIPTION
**Pull request by neclimdul**
Ensure Z-Probe Wizard follows probe offset logic to safely move to the probe position.

### Description

The Z-Probe wizard does not currently take into account the clearance settings during its setup process to the initial probe move is moved at z = 0 leading to the nozzle dragging on the bed in some cases. 

### Requirements

n/a

### Benefits

Ensures safe mode during Z-Probe Wizard movement. 

### Configurations

n/a

### Related Issues

#25491

### CODE REVIEW

**Comment by neclimdul** [comment]
Not sure this is the "correct" fix because I'm not very familiar with the code base and I mostly cribbed this from the tramming wizard which was moving safely. It fixed the problem for me though so hopefully its good to go.

**Comment by thinkyhead** [comment]
There seems to be a more general issue for all XY moves with the probe, especially with BLTouch high-speed mode, so I've tried to apply a more general fix. Please test with all your probing procedures, including `G30`, `M48`, and `G29` just to make sure it's all working as it should.

**Comment by neclimdul** [comment]
- Probe Wizard worked great.
- Tramming Wizard worked great.
- G30 worked great.
- UBL looked like it was working but at some point crashed out.


Not sure if the UBL crash was BLTouch acting up or something else. Will try some more this evening.

**Comment by thinkyhead** [comment]
> Not sure if the UBL crash was BLTouch acting up or something else. Will try some more this evening.

If we can trace the issue to a bug in or around UBL that would be a good patch to include here. You can also enable `DEBUG_LEVELING_FEATURE` and send `M111 S32` to get extra logging, and that might give some extra clue in the serial output.

**Comment by neclimdul** [comment]
Thanks! I'll keep testing this and report if I find any other bugs.

**Comment by thisiskeithb** [comment]
This PR seems to cause a new, extra Z move when using a BLTouch:

- https://github.com/MarlinFirmware/Marlin/issues/25565

**Pull request merged**
