### PR TITLE
[2.0.x] PersistentStore update followup

### PR DESCRIPTION
**Pull request by p3p**
Remove duplication of renamed files caused by merge and fix LPC1768 and due builds with flash emulated EEPROM, also MarlinConfig.h is required for serial and the emulated EEPROM functions.

Added a EEPROM_SETTINGS test to LPC1768 and Due tests, the tests probably need expanded on now the platforms are ran in parallel and it doesn't take 30 mins.

#11543

### CODE REVIEW

**Comment by marcio-ao** [comment]
@p2p: I can confirm that this patch allows me to compile, once I fix a likely unrelated error:

In "HAL/HAL_DUE/Servo_Due.cpp", `#include "../servo.h` needs to be `#include "../shared/servo.h"`

**Comment by p3p** [comment]
ah that's from the shared folder PR, I fixed a few others to do with that so may as well fix that one too.

**Comment by thinkyhead** [comment]
Anything else to add before we merge this?

**Comment by p3p** [comment]
I don't think so.., Not sure if you want to just use MarlinConfig.h or are OK with using MarlinConfigPre.h then only if the feature is enabled pulling in the rest of the headers,

There are things that should probably be done, renaming E2END and changing the spi and i2c eeprom to use PersistantStore but that's for another PR.

**Comment by thinkyhead** [comment]
`MarlinConfigPre.h` is preferred at the top of source files where only the configuration values are needed (to test for enabled config options). `MarlinConfig.h` should be used when `MarlinConfigPre.h` doesn't provide enough root headers to allow the code to compile.

**Comment by thinkyhead** [comment]
> …renaming E2END…

We use that name because it's what the Arduino platform headers define. We can't entirely eliminate its use for the platforms that use it to determine the EEPROM size.

**Comment by p3p** [comment]
We can outside of the platforms though, the only usage in Marlin core is now in the pins files where it is defined to specify the size of i2c/spi attached EEPROMs.

**Comment by thinkyhead** [comment]
Sounds like we should roll the i2c-based methods into the `PersistentStore` implementations and just use the `capacity`, as established for the other storage types. i.e., `persistent_store_i2c.cpp`…

**Comment by p3p** [comment]
Indeed that was the plan, was one of the reasons I wrote the PersistentStore api to begin with along with unified api for platforms.

There will probably 3-4 shared implementations rather than platform specific ones
persistent_store_eeprom (using the avr eeprom interface)
persistent_store_i2c (wire interface)
persistent_store_spi (marlins spi interface)
persistent_store_sdcard (Marlins sdcard interface, STMF1 platform has an example of this)

**Comment by fiveangle** [comment]
> In "HAL/HAL_DUE/Servo_Due.cpp", #include "../servo.h needs to be #include "../shared/servo.h"

It must have been 4 times I'd re-done this exact change in the Servo_Due.cpp so not sure where the reverts kept coming from in my chain.

I've burned an old Fortran 77 reference book in effigy to the git gods and will monitor to ensure no similar shenanigans..

**Pull request merged**
