### PR TITLE
Extend M106/M107 for better laser module support

### PR DESCRIPTION
**Pull request by DrywFiltiarn**
### Requirements

Improving laser grayscale scan-line engraving using Marlin on a 3D printer or purpose build machine, when using a fan-port to control the PWM signal to fire the laser module.

### Description

This feature change is aiming to implement synchronous support of M106/M107. The goal of this is to take back control of when these commands fire in the motion cycle of Marlin, so that they can be used to fire the laser at the right moment or turn it off again at the right moment. Default nature of Marlin is to apply M106/M107 gcode commands as soon as it can through use of an interval controlled (~10Hz) call on check_axes_activity() in the planner.

Both the "as soon as possible" and the low call rate of the check_axes_activity() method prevent high quality laser engraving through the fan ports.

Situation before the changes contained in this pull request:
IMG_1987
In above image you can clearly see the misfiring of the laser module. It has lines where they should not be due to the laser falsely being turned out, and on the other side it's missing lines where there should have been.

The same engraving redone with the changes contained in this pull request:
IMG_1992
This image shows that the synchronization of the pwm controls with M106/M107 has a great impact on the engraving quality. Note that the speed of this image at 10mm/s is due to the fact it was testing with a low power 500mW laser, so going fast won't do much otherwise. The synchronization principle is fully functional with high(er) speeds as well.

### Benefits

The M106/M107 commands will become synchronized and will get executed in order of communication to Marlin, which allows highly accurate firing of a laser module on a printers part cooling fan pwm port.

With synchronized M106/M107, people that want to run laser modules on their 3D printers (and may be limited to using the fan port, i.e. Creality Ender for instance with the stock board), can achieve very high quality laser engravings, something that can't be done without the synchronized M106/M107 commands.

Some more examples of the results with the changes in this pull request:
IMG_1998
IMG_1999

### Related Issues

Use of M106/M107 has been mentioned in the following ticket, as well as example pictures of the issue of non-synchronous fan pin control in the planner.
- #11575
- #16058

### CODE REVIEW

**Comment by DrywFiltiarn** [comment]
This is the updated PR against the correct branch of #16077 

Things turned a bit messy yesterday as the original pull-request and my development was occurring right at the time the 2.0.x release branch was created.

**Comment by thinkyhead** [comment]
Things will be even more fun as we're now going to be diverting some PRs to the `dev-2.1.x` branch and others to the `bugfix-2.0.x` branch.

**Comment by thinkyhead** [comment]
Overall the approach is sound. However, I suggest we extend this just a little more so that we can keep fan kickstart and fan minimum speed settings. My proposal is that it's time we added the `M450`-`M459` commands to specify that the current tool is an extruder, laser, spindle, etc. When the machine is in LASER mode then the behavior of `M106` is changed (for the "fan" port) to which the laser is connected. This will also allow us to have up to two controllable cooling fans plus the laser at the same time.

**Comment by DrywFiltiarn** [comment]
@thinkyhead if there is anything I can do towards your suggestion of implementing M450 - M459 let me know. I think it indeed would make sense to start supporting these, as it's becoming more common for machines to be multi-tool, at least in terms of 3D printing + laser.

I also agree with you that ideally fan kickstart and min-speeds should not be sacrificed for my change, however, without further expanding the changes and indeed support M450 - M459 I don't see an option to do this currently.

**Comment by thinkyhead** [comment]
I got the new commands started. There are probably several behaviors that will need to account for the tool mode. I'll add more to this PR over the coming days.

**Comment by ellensp** [comment]
is adding more gcodes the answer when marlin already has M3 - M5? Perhaps fixing M3-M5 is the way to go? #11576

**Comment by Sorin0209** [comment]
I am new to this but this is definitely the topic i'm interested in. Is there any way to implement these manually without messing with the 3d printer part ? I have an Ender 3 and everything other than vector cutting which is straight forward 100% , doesnt seem to work. Its out of sync, it takes time to ramp up and the greyscale is not even, and so on. How can i make this work. I have no idea how to code, but im really good at listening to good advice, and copy/ pasting the settings into my Marlin. Appreciate the work all of you do here.

**Comment by shitcreek** [comment]
@Sorin0209 There has been lots of improvements to the laser/spindle codes and setting it up is straight forward. I recommend using M3/M4 and M5 instead of M106/M107 which is tied up with the fan. See `LASER_FEATURE` in the config_adv file.

**Comment by Sorin0209** [comment]
@shitcreek Thank you for your answer. Ok so I uncomment the LASER_FEATURE to be able to use the M3,M4 and M5 commands. doesnt that conflict with the 3d printer part. Is there any rewiring i have to do to my fan port ? just asking because there are any other ports available on the creality ender 3 board.

**Comment by shitcreek** [comment]
@Sorin0209 long as it is a PWM port if you want to use PWM. For simple on/off, you can use any port. Just make sure the pin isn't assigned/used by something else which it shouldn't.
You will probably want to look into `LASER_POWER_INLINE` and its children - this may make this PR obsolete as it handles rastering pretty well.
Have a good read of that whole section in the config_adv file and check out the updated documentation of M3/M4 on [MarlinFW.org](http://marlinfw.org)

**Comment by whlina** [comment]
Hello Shitcreek, I am new in this total environment and I am trying to build up a laser cutter with the BTT SKR1.4 Turbo. Actual I cannot find the 3 PIN definition lines in the latest Marlin and bugfix Files as mentioned in the Documentation. Could you help me please?

**Comment by Sorin0209** [comment]
@whlina . Get the Marlin- 2.0.x and you will find the source and pinout files there. Marlin 2.0.x/ Marlin/src/pins  You just replace the config files from the bugfix into Marlin 2.0.x

**Comment by Sorin0209** [comment]
@shitcreek Is there any way we can get a step by step on how to implement these changes. ? i found a pin that is available on the ender 3 series. pin 29 is unnasigned and i can use it. but its all down to the code changes; and even though i realize this is all beta and bugfixes, i cannot find anywhere on how to apply these changes to the firwmare. Newbie here. sorry :)

**Comment by shitcreek** [comment]
I'll do up a video on how to configure Marlin for lasering/milling at some point.
Which pin file are you using? It may also help to know which version of the Ender-3 you have. The latest Ender-3 comes with the Creality3D v1.1.4 board.

**Comment by Sorin0209** [comment]
@shitcreek . Thank you. A video would be very helpfull. I have a 1.1.4 board. I want to use pin 29 on the board,  but pin 27( buzzer pin) should also work if reconfigured. Pin 29 on the ender 3 is not assigned and a header needs to be soldered, ground can be taken from the ISP pins thay are used to flash the bootloader.

**Comment by shitcreek** [comment]
Why not just use a PWM fan pin? I believe the main pin file for the Ender-3 is `pins_MELZI_CREALITY.h` which includes `pins_MELZI.h` which includes `pins_SANGUINOLOLU_12.h` which includes `pins_SANGUINOLOLU_11.h` which is the root pin file.  Take a look in there, particularly near the bottom.

**Comment by Sorin0209** [comment]
@shitcreek Fan pin can also work, i was actually using fan before with a Y splitter to be able to switch back and forth between the laser and fan when using it for 3d printing . If i was to use fan pin. Do i have to remap the pins in the Melzi_Creality ?

**Comment by shitcreek** [comment]
At the very bottom of that pin file you will see:
`#define SPINDLE_LASER_PWM_PIN             15  // Hardware PWM`
I believe the fan is pin **4**

Side note: there is a comment at the bottom that tells you how to use the X stepper socket instead for a dedicated lasering/milling machine.

**Comment by whlina** [comment]
Luu, do you have any suggestion which PIN’s I should use for the Laser Power up and 5V PWM for Laser control on the SKR 1.4 Turbo?

**Comment by shitcreek** [comment]
@whlina just use your PWM fan pin: **P2_03**
The root pin file for your board is `pins_BTT_SKR_common.h`
Add: `#define SPINDLE_LASER_PWM_PIN P2_3`
You may want to reassign the `FAN_PIN` to **-1**

**Comment by thinkyhead** [comment]
I've merged the latest code and cleaned this up a bit. In light of the latest laser changes, please take another look at how much new code is needed to drive the laser via `M106` and how you might want to hook into the updated methods.

**Comment by Sorin0209** [comment]
@shitcreek I guess i will wait for that video. i really dont want to mess anything up. It will be like Christmass in the summer :)

**Comment by Sorin0209** [comment]
@shitcreek Any update regarding the video ?

**Comment by I3megaS** [comment]
> @Sorin0209 There has been lots of improvements to the laser/spindle codes and setting it up is straight forward. I recommend using M3/M4 and M5 instead of M106/M107 which is tied up with the fan. See `LASER_FEATURE` in the config_adv file.

Hello, in my case, following your advice I tried to use “LASER FEATURE” but I had some problems that I don’t know how to solve.

The first one is that when I activate “LASER FEATURE” the controller fan speed can’t be modified from 255 if you want the fan to run. The only value accepted is 255 and any other value activate the output but at a very low voltage.

Another problem is that when I try to print a square of 10x10mm it prints correct if the laser power is low, for example S30. But when I try to print **the same gcode file** but changing the power to S200 for example, it makes a square of around 10x15mm. Hardware/software problem?

I am doing these tests over an Anycubic I3 Mega-S, with TMC2209 full Uart, a laser with a PWM of 20kHz and Marlin FW 2.0.7.2
[Config Files.zip](https://github.com/MarlinFirmware/Marlin/files/5425911/Config.Files.zip)

Sorry if this comment should not go here.

**Comment by shitcreek** [comment]
@Sorin0209 Sorry I was away for a while and been busy. Working on the video this week, hopefully I'll have it out in a couple days. Sorry if I kept you waiting.

@I3megaS You will probably get more attention if you started a new thread. But be certain it's a bug and not configuration issue before you do. I recommend joining our Discord channel.

For your first issue, are you certain you are using a PWM pin?
For the second issue, that's a strange one. I'd check your connections.

**Comment by Sorin0209** [comment]
@shitcreek Welcome back, hope you are ok. No worries about that video, i'm not in a hurry, i like to create and experiment and tinker with my 3d printer, but i'd not want to break it; so i will wait patiently for that video 👍

**Comment by I3megaS** [comment]
@shitcreek, thank you for your response. I have opened an issue #19883 for the first issue.
_For your first issue, are you certain you are using a PWM pin?_ Yes I am using it. I have checked it with an oscilloscope.
Sorry but I am new to Github. Where can I find the Discord channel?
The second issue I have already solved. I have routed the Laser input signal wires by another place and I have also used a twisted cable. I thought it was a hardware issue because the position info shown in the screen was correct, but the movements were incorrectly made…

**Comment by sjasonsmith** [comment]
What is happening with this PR? It has been open for nearly a year. The pictures are very impressive, but it is not clear whether these changes are still needed, or if they have already been addressed?

@shitcreek should this remain open? It seems the submitter hasn't been here for a while...

**Comment by shitcreek** [comment]
Well this PR still needs work and we'll also need to add `M450` (set tool) to go with it if we don't want to sacrifice fan kickstart and min speed. Meanwhile we have M3/M4/M5 that work well. But I'm impartial because I think this will make Marlin more robust. It just needs some TLC. * poke @DrywFiltiarn *

**Comment by DrywFiltiarn** [comment]
> Well this PR still needs work and we'll also need to add `M450` (set tool) to go with it if we don't want to sacrifice fan kickstart and min speed. Meanwhile we have M3/M4/M5 that work well. But I'm impartial because I think this will make Marlin more robust. It just needs some TLC. * poke @DrywFiltiarn *

My work on this is quite a while back and since then more changes were already made I believe to allow for scheduled fan control rather then the original as-soon-as-we-can way of fan control (being underlying cause of the original issue).

@thinkyhead did start some work on the toolchange stuff on my pull request code, but that’s out of my league to work on.

And although perhaps M3/M4/M5 may work well now, I’m not sure how well this works with machines that are dual purpose as a 3D printer and laser engraver, where it’s common to reuse fan port for the laser PWM control, which means using M106 for that. It’s not something I have been recently working with in that regard, as I have my own Marlin fork running with this PR which for me solves the issue.
I posted here originally as I came across more people running into the async issue with M106 laser control at the time.

**Comment by MichaelDu9226** [comment]
I want to know what  differences between this pull and the pull of LASER improvements.https://github.com/MarlinFirmware/Marlin/pull/15335

**Comment by shitcreek** [comment]
@MichaelDu9226 #15335 improves M3,M4,M5 with added trapezoidal power and inline power, as well as the ability to trigger the laser/spindle with an 'S' parameter along with a G move command eg `G1 X10 S255`. And some.
This PR focuses on M106/M107 and decouples the laser from the fan and allows for adjusting frequency thus improving the laser rastering. I think the idea is to eventually make M106/M107 behave just as M3/M4/M5 (how they ought to behave), so this PR may not be needed.

**Comment by Sorin0209** [comment]
I was just wondering, where are we with this? i just need a "simple" way to delay the movement of the laser head so it fires where its suppose to with m106/m107 commands (i'm using lightburn, if that makes a difference), been reading on creality forums, marlin updates. nothing. 
This seems to be the only forum that addresses the issue, but since i'm a newbie, i have no clue how to test this out, apply it ,etc.  
So far the only way i can raster is to lower the power by a looot and lower the speed to a point where i can get a decent raster.

**Pull request merged**
