### PR TITLE
Move menus for usability

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Following discussion with @marcio-ao earlier, put SD menu below change SD so its at the bottom again. Also move cooldown to the bottom of the temperature menu for the same reasoning.

### CODE REVIEW

**Comment by gloomyandy** [comment]
Can you summarise the reasoning behind this change? Personally I don't find it very convenient to get to the last item in a menu, but perhaps I'm missing an obvious way to do it.

**Comment by robbycandra** [comment]
I agree.... My Reason is... to get SD menu you just turn the encoder to the bottom and click.
Bottom menu is easier to choose than menu in the middle.

Actually, i dont know the benefit of Change SD for 12864 or 2004.

**Comment by InsanityAutomation** [comment]
The SD menu is only for encoder wheels, has a catch for has encoder. It was the result of a usability study by Aleph Objects awhile back. As @robbycandra stated, its just a flick of the wheel and click. As these are the common items in each menu it was found to be the optimal place. Keep in mind the Lulzbot repo has both of these in place here already.

**Comment by gloomyandy** [comment]
@robbycandra why does the display type make any difference to if "Change SD" is required? I believe it has been changed to be "Release SD" now (at least in some configurations) and calls M22 rather than M21. This is particularly important on systems that can share the SD card between Marlin and a PC via USB.

@InsanityAutomation thanks for the update. I can see the argument, I guess this works well for folks that are familiar with the system, pity it kind of hides pretty important menu items from new users. But I guess you soon find your way around.

**Comment by InsanityAutomation** [comment]
It doesn't really hide remove or change anything, just move the positioning of the couple items. One of these days things will be static enough to actually create a good menu tree document and guide....

**Comment by gloomyandy** [comment]
What I mean is that the practice of putting a frequently used item as the last one in the menu (so it is easier to select) means that it is often not visible when you first enter that menu, which I think for a new user makes it a little more difficult. I think most users would probably expect that the "important things" are near the top (and yes I know it wasn't near the top in this case!). But there is no right solution in this situation.

**Comment by InsanityAutomation** [comment]
Agreed, no right so we go with least left. At least in these scenarios it's been discussed at length on here before and it looks like a recent change just went around it a little bit. realistically you could say this is doing nothing more than recovering them to the position they were immediately following the agreement with all hands a few months ago. There was much debate and many opinions to be had then as well.

**Pull request merged**
