### PR TITLE
Update Greek language

### PR DESCRIPTION
**Pull request by lefterisgar**
### Description

Hi there!

Seeing that current translations for the Greek language are a bit old, I created this pull request to update the following language files:

- language_el.h
- language_el_gr.h

### Benefits

- Updated Greek translations
- Added a few entries that were not present
- Improved readability & shortened a few messages (especially those that were marked as "in need of shortening")
- MISC fixes (such as fixing words with missing accentuation, e.t.c.)

### Related Issues

- Note: There was/is a lot of inconsistency between language_el and language_el_gr. Even tho they are the same language and therefore should be identical (yes, el is the same as el_gr even tho their ISO code is different). For example one file may fall behind by 1 commit while the other is 1 commit ahead and/or 1 commit behind).

- Beware, that I don't personally have an LCD display on my printer (it's an Ender 3 V2 so I don't think I will ever be able to test that) so there might be any problems that I didn't think of, but I still think that it improves the previous work done by @psavva. For Greek people (and not only): feel free to test it out and notify me if there lies any problem. 

Thanks!

### CODE REVIEW

**Comment by psavva** [comment]
Thank you @lefterisgar, I will definitely test it out and report any issues here.

I'm very happy to see interest in the Greek Language translations.

@thinkyhead  I was thinking to implement el_CY which may have some differences with el_GR.

Can we implement a feature that will look at the set locale, eg: el_GR, if the translation does not exist search in 'el'. Similarly, if el_CY is set, first look for the translation there, if it doesn't exist, fall back to 'el'.

We can use el as the Greek language 'el' with all the transactions, and override specific difference in the dialect 'el_CY'.

We could then on this way only maintain 'el' and remove all translations from el_GR which makes maintenance a lot easier (no more duplication as suggested by Lefteris.

**Comment by thinkyhead** [comment]
> … if the translation does not exist search in 'el' …

Erm, it's not so simple, and it's not necessary. Currently if you try to specify a language and the files are missing, the compile will fail. Or if you specify a language code that Marlin doesn't handle, the compile will fail.

**Comment by thinkyhead** [comment]
> I was thinking to implement `el_CY` which may have some differences with `el_GR`.

Go for it. There will simply be two separate language files, and since the new one will have been derived from the old one, they will be easy to compare side-by-side in any diff tool to see where entire lines are missing.

**Comment by thinkyhead** [comment]
> Can we implement a feature that will look at the set locale (e.g., `el_GR`) if the translation does not exist search in `el`.

Actually, I think it's possible. We are using namespaces, so the `el_CY` namespace simply has to do something like this:
```cpp
#include "language_el.h"

namespace Language_el_CY {
  using namespace Language_el; // Inherit undefined strings from Greek (or English)
  . . .
};
```
Note that this will break the current `findMissingTranslations.sh` script, so that would need to be updated to do a mashup of language files with this kind of inheritance.

**Comment by thinkyhead** [comment]
Are we certain that `el` and `el_gr` were accidentally created as distinct files and yet neither of them was ever intended to be Cyprian Greek?

**Comment by psavva** [comment]
> Are we certain that `el` and `el_gr` were accidentally created as distinct files and yet neither of them was ever intended to be Cyprian Greek?

Yes, The initial idea was to support Greek, not realizing that we would need to maintain 2 files (el, el_GR) which GR is for Greece, and also conforming to the ISO 639-1 format for Language and ISO 3166-1 for the Country.

I am a Greek Cypriot from Cyprus.  The language code for my country is el_CY and due to the division of the island in 1947, we also have tr_CY as our other languages, spoken in the Turkish breakaway state in the North.

**Comment by thinkyhead** [comment]
Ok, so for this PR the extra language file can just be removed, so there is only `el`, and when `el_CY` is ready that can be added, inheriting from `Language_el` any strings that don't need to change. Alternatively, the `el_gr` can be renamed to `el_cy` as a placeholder, and you can add onto it gradually over time.

**Comment by lefterisgar** [comment]
Sorry for being late to answer but anyways...
Thanks everyone for your support!
I'm also very glad to see that people are interested in this.

@psavva Your "fallback" idea is just awesome! I also want to add that we might need to translate a few more strings to Greek, because from what I can tell by having a look at language_en.h, there is a ton of entries we haven't yet imported and (I suspect) new ones are added on a very frequent basis.

@thinkyhead Which solution do you prefer about the aforementioned issue? I personally think of removing the extra language file (and adding it if there is any need) because there is little to no difference between Greek and Cyprian Greek terminology wise. This way we can focus on shortening the text which as stated, doesn't fit the LCDs printers use. Another thing I want to ask: Can those files be used (somehow) on a DWIN display? I read on a PR you made that you plan to support Cyrillic characters but I don't know if you made any progress. Is there any way I can help with that?

**Comment by thinkyhead** [comment]
> Can those files be used (somehow) on a DWIN display?

At the current time there are no bitmap fonts with Greek characters included as part of a `DWIN_SET`. It is theoretically possible to add them, but it's going to take some work, and the tools for DWIN are not great. We don't use all the font sizes that are currently included in the `DWIN_SET` for the Ender-3 V2 (for example) so there is certainly some space available by removing the unused fonts. Any extra installed fonts would need to be made in all the sizes (three, I believe) that we are currently using. Ideally, we would have scripts similar to the ones we use to generate the minimal DOGM fonts, only encoding the characters that are actually used by the installed languages. I believe that the text drawing for DWIN is not based on UTF-8 so we would need to generate character mappings to convert strings before sending them to the display. Finally, the stock code supporting the Ender-3 V2 (for example) is hard-coded with only English and Chinese (bitmaps); however, the MarlinUI support for that display offers the possibility to use any language once there is some way to get the fonts and character mappings sorted out.

Meanwhile, the language support for MKS UI and FTDI EVE is much better, so there are far fewer barriers with those displays.

**Comment by thinkyhead** [comment]
I've added a placeholder for el_CY so that can be added onto in the future. The `findMissingTranslations.sh` script has been adjusted to look at language inheritance when listing untranslated strings. In future it may also be updated to skip strings that don't require translation — probably by moving those strings in the `language_en.h` file to a section of their own at the end.

**Pull request merged**
