### PR TITLE
ini/stm32f1.ini … env:chitu_f103 … build_board.offset 0x8800

### PR DESCRIPTION
**Pull request by tommywienert**
### Description

This is a PR to fix the issue that building the "normal" (as in not _maple) update.cbd will get rejected by Tronxy Printers.
As the maple build worked, @ellensp  suggested to add the address offset like it is set in the maple build. Furthermore @tpruvot  recommended to remove the DSTM32_XL_DENSITY parameter as it is unnecessary and wrong anyways ( -> High Density would be the correct value). Changing both created an update.cbd that was accepted by the printer.
This was tested on a Tronxy X5SA Pro, Mainboard CXY-V6-191017, but will work on other Tronxy Printers with Mainboard CXY-V6-191017, and maybe even Tronxy Printers with slightly different Mainboards (like V5 or V8).

### Requirements

Tronxy Printer with Mainboard CXY-V6-191017 ( others may be possible)

### Benefits

Tronxy Printer with Mainboard CXY-V6-191017 ( others may be possible) do not depend on the maple builds anymore

### Configurations

not needed i guess, but this is what i used:

[Tronxy.zip](https://github.com/MarlinFirmware/Marlin/files/7615808/Tronxy.zip)

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/23198

### CODE REVIEW

**Comment by ellensp** [comment]
Ignore this error, its is unrelated to your PR, everyone is getting it at the moment

**Comment by ellensp** [comment]
Relate to https://github.com/MarlinFirmware/Marlin/issues/23223 also

**Comment by ellensp** [comment]
And now your getting caught with bad Configuration_adv.h from Configuration repos causing Ci issues
see https://github.com/MarlinFirmware/Configurations/issues/627 for details.

**Comment by tommywienert** [comment]
Forgive me, I do not understand what is going on. I'm used to bitbucket and can't follow what the following commits mean or do.

**Pull request merged**
