### PR TITLE
added SPINDLE_SERVO feature

### PR DESCRIPTION
**Pull request by spin7ion**
### Requirements

Added feature to drive hobby kind of servos with M3-M5 commands

### Description

Hobby ESC for rc motors are driven by special type of PWM:
servo-pwm-signal_orig

Added SPINDLE_SERVO define to drive such motors.

### Benefits

It's now possible to build CNC machines with hobby brushless motors and ESCs.

### Configurations
Test purpose only configuration files:
[config.zip](https://github.com/MarlinFirmware/Marlin/files/5469750/config.zip)

### Related Issues

[[FR] Servo control by M3-M5 commands #19967](https://github.com/MarlinFirmware/Marlin/issues/19967)

### CODE REVIEW

**Comment by ManuelMcLure** [comment]
How does this differ from the servo signals generated by `M280`?

**Comment by spin7ion** [comment]
> How does this differ from the servo signals generated by `M280`?

It is not differ. Actually it use same servo class as M280. The main idea is to allow M3-M5 commands to drive the spindle made of RC hobby brushless motor and ESC. So g-code will be compatible with different CNCs.
Please, look at [this feature request](https://github.com/MarlinFirmware/Marlin/issues/19967)

**Comment by sjasonsmith** [comment]
I'm just adding a link to the closed request which was incorrectly targeting the 2.0.x branch. I have not looked at the new changes yet to determine whether my concerns were all resolved.
#19968

**Comment by spin7ion** [comment]
> I'm just adding a link to the closed request which was incorrectly targeting the 2.0.x branch. I have not looked at the new changes yet to determine whether my concerns were all resolved.
> #19968

Now it uses spindle_laser class. As for your consern about configuration, I resolved it.

**Comment by MagicAlien** [comment]
Activating Spindle_Servo on RAMPS 1.4 with hobby servo connected in servo_0 (pin D11) and with any cutter power unit, M3 S[any number other than 0 ] moves the servomotor at an angle of 180°. 
This enabled feature should move a hobby servo at any angle given by S[number]?

**Pull request merged**
