### PR TITLE
Missing thermistor 331 Name

### PR DESCRIPTION
**Pull request by tpruvot**
see #14931 comments

### CODE REVIEW

**Comment by tpruvot** [comment]
well on the F1... which is 3.3V... that show -14°c with it... hmm (3950 4.7k pullups) the 1 seems fine else

**Comment by tpruvot** [comment]
image

**Comment by tpruvot** [comment]
so this name could be confusing...

**Comment by AnHardt** [comment]
This table is for a processor with analog reference voltage at 5V with the pullups to 3.3V.
Just don't use it.
For a normal 5 or 3.3V systems use the *normal* table.

**Pull request closed without merging**
