### PR TITLE
Fix Trigorilla Pro for HAL/STM32 build

### LINKED ISSUE #22606: 2.0.9.1 Will Not Compile
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I am currently running Marlin 2.0.9

When I download and unzip 2.0.9.1, and install the configuration.h and configuration_adv.h files from the config/examples/delta/anycubic/predator folder, it will not compile under Platformio under VSCode.

It throws this problem:
Cannot find "C:\Users\rquin\.platformio\packages\framework-arduinoststm32@4.10900.200819\variants\MARLIN_F103Zx".

Marlin 2.0.9 compiles fine.

### Bug Timeline

Just noticed today.

### Expected behavior

I expect Marlin 2.0.9.1 to compile.

### Actual behavior

Marlin 2.0.9.1 fails to compile, and is looking for a non-existent file.

### Steps to Reproduce

1). Download Marlin 2.0.9.1 and unzip it.
2) Download the configuration files from the /config/examples/delta/Anycubic/Predator/ folder
3) Install those files in the Marlin directory
4) Modify platformio.ini to the trigorilla_pro
5) Attempt to compile

### Version of Marlin Firmware

2.0.9.1

### Printer model

Anycubic Predator

### Electronics

Stock

### Add-ons

none

### Bed Leveling

_No response_

### Your Slicer

_No response_

### Host Software

_No response_

### Additional information & file uploads

_No response_

### PR DESCRIPTION
**Pull request by thinkyhead**
Fixes #22606

Patches another glitch from the updated STM32 build environments. The build flags are borrowed from the MKS Robin environment, as inherited from the Maple environments. Due to differences in the platforms it is unclear whether the build flags are entirely correct.

### CODE REVIEW

**Comment by rq3** [comment]
Just tried the latest bugfix with latest configuration files. Got FSMC_SD is now Show_SD error. Fixed that, compiled into 217KB firmware.bin.

Still blank display.

**Comment by thinkyhead** [comment]
When you compile the Maple target the display is okay? Can you discern any difference in the output of `M43` (`PINS_DEBUGGING`) when you run the HAL/STM32 build compared to the Maple build?

**Comment by tpruvot** [comment]
try to add -DHAL_PWR_MODULE_ONLY, i see your thermal sensors are PA0 PA1 like the longer 3D board. By default the STM32 Hal define a Low power Wake up pin on PA0 without this flag. May be a good idea to set that in the variant folder MARLIN_F103Zx/hal_conf_custom.h

**Comment by thinkyhead** [comment]
@tpruvot — ~~I can't find any reference in the platforms to `HAL_PWR_MODULE_ONLY`. However there is a flag `HAL_PWR_MODULE_ENABLED`.~~

Hold on, there it is. `low_power.h` / `low_power.c`.

It's not entirely clear whether `HAL_PWR_MODULE_ONLY` will get picked up in `low_power.h` / `low_power.c` if set in `hal_conf_extra.h`.

**Comment by thinkyhead** [comment]
Hold on, there it is. `low_power.h` / `low_power.c`.

**Comment by tpruvot** [comment]
In fact i dont think we need HAL_PWR_MODULE at all, seems related to battery powered boards. I disabled the whole module on the Longer board without issues... but HAL_PWR_MODULE_ONLY works too... ah right its needed for RTC clock feature, but our board dont have the second 32.7kHz crystal for that... nor the 3V battery to keep the clock ;p

**Comment by thinkyhead** [comment]
I don't think we can simply disable `HAL_PWR_MODULE` in the custom variant, because it is shared among several boards. It would need to be verified that none of the boards can use it.

**Pull request merged**
