### PR TITLE
Fix typo in Configuration_adv.h

### PR DESCRIPTION
**Pull request by notabucketofspam**
### Description

At present there exists a bug which prevents Marlin from compiling, due to a missing right brace in an if statement.

### Benefits

Allow compile without error. Also fix indentation.

### Related Issues

May be related to PR #18421.

### CODE REVIEW

**Comment by p3p** [comment]
It's 4am, so may be reading this wrong, but I'm pretty sure that this does not correctly maintain the logic, I think removing the brace from line 3102 would be the correct fix.

**Comment by notabucketofspam** [comment]
You're correct. Sorry for the mistake.

**Comment by notabucketofspam** [comment]
Also included a very minor typo fix that didn't seem substantial enough to open a separate PR for.

**Comment by scott4290** [comment]
Wasn't the missing brace at line 3109?  I normally write Python, so I could be completely wrong.

**Comment by notabucketofspam** [comment]
@scott4290 Removal of the brace on line 3102 is correct. Equivalent statements on lines 3219 and 3333 for heated bed and chamber respectively follow this format.

**Comment by p3p** [comment]
The brace was fixed in https://github.com/MarlinFirmware/Marlin/commit/9546847dc1af1d4df4842b99576010890bdaf8b1, merged the typo fix.

**Pull request merged**
