### PR TITLE
Add more Babystep options

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Brought back changes from the original state of #13191 following additional discussion there and #13129 

Tested the require homing with auto homing which allows entry at any time with auto homing. Added the screen from the ubl menus when homing.

Tested the allow when steppers active. without auto homing.

Prevent stepper timeout needs a little work, ill wrap that up tomorrow. Its late and I have an early conference call.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
The features in this Pull Request address many of the issues we have heard from the Z-BabyStep users.    Of course we need it to pass Travis.   But I look forward to seeing these changes merged ASAP.    

And once these are merged, I'm thinking we need to discuss and look at what should be done to re-enable the Stepper Motors if they have timed out.   I'm of the opinion that if the user says to BabyStep the Z-Axis, we should re-enable the the Steppers and do it.   If there is a reason not to do this, I would welcome a discussion of why that is a 'bad thing'.

**Comment by dot-bob** [comment]
Just an FYI this breaks the MOVE_Z_WHEN_IDLE functionality as jumps to babystepping when the printer is not busy.  Move MOVE_Z_WHEN_IDLE was modeled after similar functionality of prusa MK2/3 printers.

Perhaps the printer_busy() should be extended with a timer or mutually exclusive with MOVE_Z_WHEN_IDLE .

**Comment by InsanityAutomation** [comment]
@Roxy-3D The travis failure is the same stm32 issue impacting head right now. I havnt looked into it yet. Travis has been failing for a couple days.

@dot-bob Correct, a sainty check is probably needed between the auto homing method and move z when idle so only one or the other can be enabled. The move z when idle should still work when outside the babystep conditions. IMO its a matter of the user selecting the idle action they want between the two. Ill test the interaction between the two tonight after the day job.

**Comment by forkoz** [comment]
move z when idle should work without homing.

**Comment by Roxy-3D** [comment]
I don't understand why some people feel BabyStepping should be dependent on the machine being homed or the machine being busy....     This feels like a psychological obsession.    

The BabyStepping is all done independent of Marlin.    Why should the machine be homed for it to work?  Why should the machine be busy for it to work?

SERIOUSLY...   a lot of people want it to work in spite of either of those conditions.    Why are we trying to restrict how those people use their machines?

**Comment by dot-bob** [comment]
Here is an idea...  Let's leave double click babystepping enabled all the time when selected in the configuration file.  When printer_busy() it behaves as it is now using the BABYSTEP_MULTIPLICATOR.  When it is !printer_busy() have babystepping change it's step based on the speed that the dial is rotated (like extruder temperature does) up to a max multiplier you can define (default max to 1mm per encoder step).  Then we can remove MOVE_Z_WHEN_IDLE as babystepping in theory provides the same functionality.

**Comment by forkoz** [comment]
Yea its a bit weird, I only use BS to adjust the first layer. Naturally the printer will be homed and printing or in theory about to print. If move Z is forced to home its basically usesless to get the nozzle off your failed print or away from the bed.

I thought the fight was to allow babystepping while idle in lieu of moveZ, not all these extra limitations.

**Comment by Roxy-3D** [comment]
> When printer_busy() it behaves as it is now using the BABYSTEP_MULTIPLICATOR. When it is !printer_busy() have babystepping change it's step based on the speed that the dial is rotated (like extruder temperature does) up to a max multiplier you can define (default max to 1mm per encoder step).

I like this idea.   This would increase the value of the BabyStepping because it would adapt to the machine's current state.

**Comment by InsanityAutomation** [comment]
@Roxy-3D I'm perfectly content allowing configuration options for either use case. I will gladly configure mine to jog when position is not known and babystep when it is, and leave the other methods open to whoever wants them!

**Comment by InsanityAutomation** [comment]
> > When printer_busy() it behaves as it is now using the BABYSTEP_MULTIPLICATOR. When it is !printer_busy() have babystepping change it's step based on the speed that the dial is rotated (like extruder temperature does) up to a max multiplier you can define (default max to 1mm per encoder step).
> 
> I like this idea. This would increase the value of the BabyStepping because it would adapt to the machine's current state.

May need to watch some limits here. If it's babystepping at a fast rate you can easily enqueue way more distance than intended and ram the z axis into the top or bottom of the gantry.

**Comment by Roxy-3D** [comment]
> May need to watch some limits here. If its babystepping at a fast rate you can easily enqueue way more distance than intended and ram the z axis into the top or bottom of the gantry.

Yeah...  Some limits and sanity checks probably make sense.   I think it might be better to limit how much gets enqueued instead of limiting the speed multiplier.  What I'm thinking is let the machine jog at a good speed.    But make sure it quits moving as soon as the user is not spinning the dial fast.

**Comment by thinkyhead** [comment]
> The travis failure is the same stm32 issue impacting head right now. I havnt looked into it yet.

No need. It's an issue with platformio STM32 headers, as far as can be determined. See issue 13261

**Comment by thinkyhead** [comment]
I strongly protest `AUTOHOME_BEFORE_BABYSTEP`. Please don't include this option. There should be no instance where homing occurs on entry to a menu. It should be deliberate, and menu behavior should be predictable.

**Comment by Roxy-3D** [comment]
> I strongly protest `AUTOHOME_BEFORE_BABYSTEP`. Please don't include this option. There should be no instance where homing occurs on entry to a menu. It should be deliberate, and menu behavior should be predictable.

Actually....  I missed this when looking at the Pull Request.   There are other places in the code where an 'Auto Home' is performed.   For example, in UBL's G29.     It was put in as a 'labor saver', but in hind sight....   It is too dangerous.   It should be removed.

**Comment by InsanityAutomation** [comment]
The auto homing I put in because someone mentioned it somewhere. Personally it was one I would leave off in favor of the jog when idle and let those two cover every scenario. Double click will always do something! I can see it as dangerous but wanted everything mentioned here for discussion sake at least.

**Comment by thinkyhead** [comment]
Double-click is too easy to do by mistake. I worry about the heart attacks that may be caused.

**Comment by thinkyhead** [comment]
Rebased and squashed, fixed up missed configs, disabled new options by default.
```
git fetch origin
git checkout Babystep-Usability-Enhancements
git reset --hard origin/Babystep-Usability-Enhancements
```

**Comment by Roxy-3D** [comment]
> Double-click is too easy to do by mistake. I worry about the heart attacks that may be caused.

No...  I don't think so...  It is possible to Double Click by accident...  But it drops you into a clearly communicated screen for the new behavior.   And that new behavior requires twisting the dial to cause changes.   And even if the user accidentally includes a little bit of a twist or two...  The user can back those Baby Steps out because the screen tells you how much movement has been done.

**Comment by thinkyhead** [comment]
> Double-click is too easy to do by mistake. I worry about the heart attacks that may be caused.

…by the machine suddenly homing when you just wanted to go back to the info screen.

**Comment by thinkyhead** [comment]
The latest changes aim at simplicity…
- There's just a single option (`BABYSTEP_ALWAYS_AVAILABLE`) to allow Z babystepping at all times. With this option steppers will be enabled as-needed, and the stepper timeout will be reset on any babystep.
- Previously `BABYSTEPPING` always required homing to work. Now `BABYSTEP_WITHOUT_HOMING` can be enabled to change this behavior.

**Comment by Roxy-3D** [comment]
> The latest changes aim at simplicity…

I like both of these options!

**Comment by InsanityAutomation** [comment]
@thinkyhead are you opposed to the option to switch between move z when idle and babystepping based on steppers active? Id prefer to have babystepping always available if the steppers are active and position is known, and jog z if either of those is not met.

Also, ill likely finish up what I had started with the stepper idle timeout defer while in the babystepping screen at some point if you arent opposed to that.

**Comment by thinkyhead** [comment]
> are you opposed to the option to switch between move z when idle and babystepping based on steppers active?

If the steppers have slept, then why wouldn't we just turn on the steppers like we now do for `BABYSTEPPING_ALWAYS_AVAILABLE` and then proceed with the regular Move Z?

And again we're talking about a behavior change based on whether the motors are humming, which you can't easily determine at a glance. I would prefer the double-click behavior to change only based on whether you're actively moving/printing versus not actively moving/printing, and not based on whether some of the steppers are asleep.

One of the things I'm trying to avoid is to have a bunch of 3D printers that look identical, but which exhibit starkly different and unpredictable behaviors from one another with no up-front cue. Doing one thing or something else based on whether the steppers have slept is going to annoy users, including you from time to time, and I would prefer not to offer the option to change behavior based on stepper sleep states.

**Pull request merged**
