### PR TITLE
Azteeg X5 Mini support

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Digipots differ from wifi version.

Add ifndef to digipot setpoints to allow override from configuration_adv.h

As tested by @klcjr89

### CODE REVIEW

**Comment by klcjr89** [comment]
I recommend that whoever has access to the newer wifi version of the X5 Mini to test to see if the regular v3 X5 Mini (ethernet model) is identical, so the two boards can be merged into one definition if they are indeed one and the same. To perform the test, simply use the proposed 1762 board definition: "BOARD_AZTEEG_X5_MINI" on your X5 Mini Wifi board.

The predefined board file for the X5 Mini Wifi didn't work for me on the v3 X5 Mini, because the digipot addresses were wrong. The addresses didn't need to be shifted at all, but in the predefined board file, they were shifted for some reason. Which ~~begs~~ raises the question: is the definition wrong and untested, or is the Wifi version of the board different compared to the older v3 X5 Mini?

Perhaps it may be a good idea to have separate board definitions when/if Marlin supports the Wifi and Ethernet modules that come on these boards.

**Comment by klcjr89** [comment]
@ModMike What are your thoughts?

**Comment by ModMike** [comment]
I believe they can because they use the same pins for communications but I haven't touched that stuff in a while and am in the middle of another project.

**Comment by thinkyhead** [comment]
Somebody at the MRRF must have an X5….

**Comment by InsanityAutomation** [comment]
@thinkyhead you distract em, I'll flash multiple test versions and check driver current! Lol

**Comment by ModMike** [comment]
No need, I have the dip trace files.  I can check tomorrow

**Comment by klcjr89** [comment]
@ModMike I don't see the dip trace files listed on panucatt's site in the zip folder, only the x5 mini v3 (ethernet). Can I have them? Also, I remember talking to you over a year ago, you probably don't remember me.

**Comment by ModMike** [comment]
They are not public and I can’t share them.

**Comment by klcjr89** [comment]
Send them my way please. They should be listed on the site..

**Comment by InsanityAutomation** [comment]
@ModMike taking all the fun out of it.... Lol Thanks :)

**Comment by ModMike** [comment]
Guys,  I have time this weekend but slammed with work until Friday.  I will need to set up
Printer, just redid my whole office.

**Comment by klcjr89** [comment]
Guess I'll email Panucatt for the files if you won't provide them..

The wifi board doesn't have SD breakout pins like the v3 does, which is a shame for TMC drivers..

**Comment by ModMike** [comment]
Dude I’m sorry but I take my NDAs seriously.  Bloody Sony had me listed with FBI once because they lent me their IP

**Comment by klcjr89** [comment]
I already know that, you told me before.

**Comment by InsanityAutomation** [comment]
@klcjr89 he may not be permitted to depending on agreements around obtaining them. Requesting them through official channels would be the best option.

**Comment by klcjr89** [comment]
Makes no sense; the wifi is the exact same board as the v3, except with an ESP module replacing the ethernet interface and that board is listed publicly.

**Comment by InsanityAutomation** [comment]
It may just be an oversight, but official channels are the way to go about it. Breach of nda is career ending in some industries...

**Comment by ModMike** [comment]
By the way, I did a pin file for the x5 mini wifi, did it get flushed?

**Comment by klcjr89** [comment]
That's the topic of this thread.. to merge the two boards and/or check to make sure they're exact, because the wifi pin definition for the shifted digipots didn't work on the v3 board. I had to use unshifted (original) values.

**Comment by InsanityAutomation** [comment]
@ModMike this PR was based on it, just making the digipot different so the wifi just includes the base with the prior definition prevailing.

**Comment by ModMike** [comment]
Did you check my notes on the shift?

MT

**Comment by klcjr89** [comment]
I did..

**Comment by ModMike** [comment]
Dudes, I am trying to sleep. Ping me in the morning and I will pull up the files for a look.

**Comment by klcjr89** [comment]
@ModMike What did you find out?

**Comment by ModMike** [comment]
That I have a terrible memory?  I will do now.  Can I ask what is the point is of merging 2 board definitions?  It's not like there aren't a kazillion already.

**Comment by klcjr89** [comment]
It's not about merging sepcifically, it's to see if the v3 mini definitions work on the Wifi (v4) board basically.

**Comment by ModMike** [comment]
Gotcha.  I moved the file and need to hunt for it, give me a few minutes and I will get back to you.  IN the meantime can you list all the questions you want answered?

**Comment by ModMike** [comment]
The predefined board file for the X5 Mini Wifi didn't work for me on the v3 X5 Mini, because the digipot addresses were wrong. The addresses didn't need to be shifted at all, but in the predefined board file, they were shifted for some reason. Which raises the question: is the definition wrong and untested, or is the Wifi version of the board different compared to the older v3 X5 Mini?
> 
1. t is correct and extensively tested by me.
2. It is different because they use a SN74CBTLV3257PWR multiplexer/de-multiplexer to add extra inputs.

**Comment by klcjr89** [comment]
Mike, the difference makes sense now if a different IC is being used.

On an unrelated matter, I am having SD card dropout issues on my computer after hooking TMC5160 drivers to the SD card breakout pins. I wasn't having this issue with TMC2130s using the same pins.

**Comment by ModMike** [comment]
I'm sorry but I have no experience with those drivers.  Do they have serial communications and did you set it up?  Is it possible you're inadvertently stepping on the ports?

And do you mean on your computer or controller?

**Comment by klcjr89** [comment]
Yes, the drivers are setup correctly and I have been getting good prints. And I am talking about my computer, with the x5 mini board plugged in via USB, the SD card used to stay mounted on my computer even during a print without dropping out.

Also, on a probably related matter, the screen/encoder on the printer enters menus by itself randomly when it didn't do that before.

**Comment by ModMike** [comment]
> Yes, the drivers are setup correctly and I have been getting good prints. And I am talking about my computer, with the x5 mini board plugged in via USB, the SD card used to stay mounted on my computer even during a print without dropping out.
> 
> Also, on a probably related matter, the screen/encoder on the printer enters menus by itself randomly when it didn't do that before.

That confirms you have a serial communication issue.  I would go back and revise each step you did to see where the issue started.  It's been a while since I played with my printer because I am building a Voron 2.1. and am using different boards.

I am sure someone here can help you sort it out.

**Comment by klcjr89** [comment]
I don't know, unless there is something different with the TMC5160 library, there weren't any problems with the 2130's, also running in SPI.

I am about to post it as a new issue and hopefully I get help.

**Comment by InsanityAutomation** [comment]
@ModMike as you seem to be the most knowledgeable azteeg reference, do you know if the mentioned x5 pro expansion can be chained? Looking for a 32bit board for up to 10 drivers atm.

**Comment by thinkyhead** [comment]
How worthy of merging is this PR now?

**Comment by klcjr89** [comment]
@thinkyhead I believe the X5 mini v3 should have its own board definition, as the digipots are different than the v4 (Wifi) model. So, I would say very worthy.

**Comment by InsanityAutomation** [comment]
@thinkyhead looking through the above, based on the confirmation 
> It is different because they use a SN74CBTLV3257PWR multiplexer/de-multiplexer to add extra inputs.

This pr should then be correct and able to be merged.

**Pull request merged**
