### PR TITLE
Fix for #14733

### LINKED ISSUE #14733: [BUG] MKS SGEN_L LCD pin not correct for CR10_STOCKDISPLAY
### Description

MKS SGEN_L LCD pin not correct for CR10_STOCKDISPLAY

### Steps to Reproduce

1. Download Marlin 2.0
2. #define MOTHERBOARD BOARD_MKS_SGEN_L in Configuration.h
3. #define CR10_STOCKDISPLAY in Configuration.h
4. compile

**Expected behavior:** [What you expect to happen]

Should compile without any errors

**Actual behavior:** [What actually happens]

Compiling fails with the following error:
`/pins/lpc1768/pins_MKS_SGEN_L.h:195:28: error: 'P1_0' was not declared in this scope
`

### Fix
In **pins_MKS_SGEN_L.h** `#define LCD_PINS_RS   P1_0 ` needs to be changed to
`#define LCD_PINS_RS    P1_00`
There is a **0** missing

**Additional information**
Found in the [makerbase marlin repo](https://github.com/makerbase-mks/MKS-SBASE/blob/160580d0e9ddded5058e3af65baa55304e59e3b9/Firmware/Marlin-bugfix-2.0.x/Marlin/src/pins/pins_MKS_SGEN_L.h#L237)

### PR DESCRIPTION
**Pull request by boelle**
This should fix #14733

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I was *just* getting ready to submit a PR for this. Good work!

**Comment by boelle** [comment]
yeah, the fix was provided so thought why not

**Comment by thinkyhead** [comment]
@boelle — Please make patches using branches in your own fork. Don't create new `MarlinFirmware/Marlin` branches.

**Comment by boelle** [comment]
i thought i did so, :-(

**Comment by thinkyhead** [comment]
Double-check. Triple-check. Marlin is not unlike the Apollo mission.

**Comment by boelle** [comment]
yeah, i tried to mod a file, and before i joined the team it would automatic create a branch on my own fork, so it was a case of keeping my eyes open

**Pull request merged**
