### PR TITLE
Further adjustments to UBL code

### PR DESCRIPTION
**Pull request by thinkyhead**
- Add convenience macros `WITHIN` and `FIXFLOAT`.
- Apply `const` and `const float &` where needed.
- Make calls to `print_line_from_here_to_there` compatible with `G92` / `M206`.
- Make 3-point leveling compatible with `G92` / `M206`.
- Pass `destination` as an argument to `retract_filament` and `un_retract_filament`.
- Pass no XYZE arguments to `ubl_line_to_destination`, which always uses `destination`.
- Rename `probe_index` to `mbl_probe_index` for MBL.
- Reduce PSTR storage cost for `debug_current_and_destination`. (PSTRs are not coalesced!)
- Add `ENABLE_LEVELING_FADE_HEIGHT` to the Travis CI tests.
- Drop bad idea `enqueue_and_echo_command_now`.

[(Concise diff)](https://github.com/MarlinFirmware/Marlin/pull/6181/files?w=1)

### CODE REVIEW

**Comment by Roxy-3D** [comment]
> Make calls to print_line_from_here_to_there compatible with G92 / M206.

@thinkyhead  I don't think this makes sense.   That function is used by the G26 Mesh Validation Print.  It is used to show exactly where the mesh points are located on the bed and let the user easily edit a mesh point if the Z-Height correction needs to be adjusted.   We don't want any `LOGICAL_?_POSITION()` changes to the numbers being used.  We need the real, unaltered physical locations of the mesh points being used.

**Comment by thinkyhead** [comment]
All points sent to the planner must be relative to the shifted coordinate space.

An `M206 X20`command causes the workspace to offset by 20mm to the left. So does a `G92 X20` when you're at X=0. When you subsequently issue a `G1 X40` the tool moves to the point which is currently X=20, namely 20mm from the left endstop (on a Cartesian).

You probably never tested UBL in conjunction with `G92` and `M206`. Try it now. Install your last good working version of UBL and try `G26` after using `M206 X100`. You should discover that all its moves are 100mm too far to the left.

**Comment by Roxy-3D** [comment]
OK...   I think I understand.   The `LOGICAL_x_POSITION()` is needed because the planner is going to undo that with a `RAW_x_POSITION()`. Thank you for catching and fixing that. And you are correct... I don't use `G92`.

**Comment by thinkyhead** [comment]
Next on the agenda: Evaluate and compare performance of `ubl_line_to_destination` versus the recursive `mesh_line_to_destination` and `bilinear_line_to_destination` functions.

**Comment by thinkyhead** [comment]
> the planner is going undo that with a RAW?_POSITION()

All coordinates sent to the planner should be in terms of the current working-space — what we refer to as "logical" coordinates. On Cartesian machines, the steppers' `count` values are actually in terms of the logical coordinates. It may turn out to be more optimal to have the steppers always reflect the "physical position" and remove the offsets before sending coordinates to the planner. A regex search on `(LOGICAL|RAW)_([XYZ]|CURRENT)_POSITION` gives an indication of the scale of the problem.

**Comment by Roxy-3D** [comment]
> Evaluate and compare performance of ubl_line_to_destination versus the recursive mesh_line_to_destination

This should be a fun one!   My suggestion is lets send the coordinates from a real life GCode file and time that.   I'm pretty sure the ubl version is going to win.  But the shorter the movements being fed to it, the less advantage it will have.   So...   If we were to feed a real GCode file in...  It would be very interesting to slice the part at 100%.   And then also slice it at 200%.    It is my belief the bigger scaled part will show more of an advantage with the ubl version.

**Comment by thinkyhead** [comment]
I dunno! Smaller code may execute faster just on the basis that it's smaller. Recursion may not turn out to be that expensive. It will be interesting to see!

**Comment by Roxy-3D** [comment]
> We shall see! Smaller code may execute faster just on the basis that it's smaller. Recursion may not turn out to be that expensive. It will be interesting to see!

Agreed...   And even if the recursive or bi-linear version wins...   It may be possible to further improve the speed of the winner by deploying some of the 'tricks' in the ubl version.   It would be nice to get down to one version that works for everybody.

**Comment by thinkyhead** [comment]
> deploying some of the 'tricks' in the ubl version

If it performs at all faster, you can count on it.

**Pull request merged**
