### PR TITLE
[2.0.x] Filament load/unload add acceleration for Bowden

### PR DESCRIPTION
**Pull request by seanboothm**
### Description

Adds acceleration to filament changes, filament loading, and filament unloading. 

### Benefits

This is especially useful for bowden extruders because a slower acceleration often allows a higher maximum velocity to move filament through the bowden tube much faster.

Counterpart to #10177
[Concise Diff](10172/files?w=1)

### CODE REVIEW

**Comment by thinkyhead** [comment]
This is quite different from the (revived) 1.1.x version of this PR (#10177). Should the 1.1.x version follow the same pattern as this (incomplete) PR? That is, dropping the slow/fast load, commenting out the new options, etc?

**Comment by seanboothm** [comment]
They were intended to be the same feature yes. For the 2.0 version I decided to postpone the fast / slow load, or decided maybe I will add it in as a separate pull since the acceleration itself is only a few small changes, but that fast / slow was a bit more complex and not quite as necessary. 
If I add the fast / slow feature would it be better to have it as a separate pr, or combined with this one as it's similar?

**Comment by thinkyhead** [comment]
I'm good with them being separate PRs, if that's your preference.

Note that before this can be merged, the changes made in the main config will need to be propagated to all the example configs.

**Comment by seanboothm** [comment]
I'm a bit new to github, but is there a more efficient way to do that than copy/pasting to each of the 114 example config files?

**Comment by thinkyhead** [comment]
> I'm a bit new to github, but is there a more efficient way to do that than copy/pasting to each of the 114 example config files?

You can use search-and-replace in a project editor like Sublime Text 3. Search for text that follows or precedes the change and replace with the changes plus the searched-for text. For example, search for…
```
// (mm/s) Unload filament feedrate. This can be pretty fast.
(plus the carriage return)
```
Replacing with…
```
// (mm/s) Unload filament feedrate. This can be pretty fast.
  //#define FILAMENT_CHANGE_UNLOAD_ACCEL 25   // Slower acceleration may allow a faster feedrate for Bowden.
(plus the carriage return)
```
This is made easier by some editors (like Sublime Text 3) where the `Ctrl-E` keyboard shortcut is "Search for selection" and `Ctrl-Shift-E` is "Replace with selection."

And don't forget to strip the trailing whitespace that seems to plague your PRs. We very much appreciate attention to formatting.

**Comment by thinkyhead** [comment]
Once I augment this with the slow/fast lengths from #10177 it can be merged. Meanwhile, I will merge #10177 so these additions are available in the 1.1.9 release, which is imminent.

**Pull request merged**
