### PR TITLE
sanity check for Z_CLEARANCE_FOR_HOMING

### PR DESCRIPTION
**Pull request by DerAndere1**
### Description

Certain configs require  Z_CLEARANCE_FOR_HOMING <= 0 to prevent a crash into Z max during homing. This adds another sanity check

### Requirements

```
#define Z_HOME_DIR 1
#define HOME_Z_FIRST
```

### Benefits

prevent a crash into Z max during homing

### Configurations

None

### Related Issues

None

### CODE REVIEW

**Comment by DerAndere1** [comment]
https://github.com/MarlinFirmware/Configurations/pull/1093 must be merged first so the tests can pass

**Comment by DerAndere1** [comment]
https://github.com/MarlinFirmware/Configurations/pull/1094 must be merged first to pass CI tests

**Comment by thinkyhead** [comment]
Especially when homing Z first, there should probably never be any instance where `Z_CLEARANCE_FOR_HOMING` is less than 0 because this would inevitably cause the toolhead to dig into the bed or workpiece. So the only change I would suggest is to assert that it must be == 0 instead of <= 0.

**Comment by thinkyhead** [comment]
While we're ruminating on homing and raises, I believe we need a `z_min_trusted` flag to avoid unnecessary raises. Here is a common scenario:

- Start a 3D printer and before using **Home All** use **Home X**.
- The machine raises Z before homing X because Z is "not homed" and "not trusted."
- Click on **Home X** again.
- The machine raises Z before homing X because Z is "not homed" and "not trusted."
- …and on it goes…

With the new flag we can get the desired effect…

- Start a 3D printer and before using **Home All** use **Home X**.
- The machine raises Z before homing X because `z_min_trusted` is `false`.
- As soon as the Z motor is powered set `z_min_trusted`.
- Click on **Home X** again.
- The machine doesn't raises Z  because `z_min_trusted` Is `true`.

The `z_min_trusted` flag would be cleared only when the Z motors go to sleep on a delta or other machine where the consequence would be a smaller (possibly zero) Z coordinate. If the steppers were powered off and back on in such a scenario, the Z position would be meaningless, so we would want to keep `z_min_trusted` set to `false` until the machine was re-homed. In any case, the situation with `z_min_trusted` would need to be evaluated on a case-by-case basis, but basically it will either track with `axes_trusted` or it won't depending on the mechanics.

**Pull request merged**
