### PR TITLE
Add bq Witbox 3D printer

### PR DESCRIPTION
**Pull request by victorandueza**
Hi all.

I have added bq Witbox configuration files in order to integrate it in Marlin.

Thank you!

### CODE REVIEW

**Comment by victorandueza** [comment]
Solved. Thank you!

**Comment by thinkyhead** [comment]
Thanks for the additions! The WITBOX link should actually point to the firmware location, which is this Git repo, like some others. If you change that then this can be merged.

**Comment by victorandueza** [comment]
Thank you for your report! Now the WITBOX link is pointing to this repo.

**Comment by victorandueza** [comment]
Thank you!

**Pull request merged**
