### PR TITLE
POLARGRAPH_MAX_BELT_LEN => HYPOTENUSE_LEN_AT_HOME_POS

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Per @i-make-robots on Discord:

> After much confusion among polargraph users, I'd like to ask someone on the dev team to please rename `POLARGRAPH_MAX_BELT_LENGTH` to `HYPOTENEUSE_LENGTH_AT_HOME_POSITION`.
> several people were confused that the belt length was not, in fact, the belt length.

I bumped the `EEPROM_VERSION` out of safety since I wasn't sure if a rename would cause older EEPROM values to not work.

I also dropped the old, non-English `MSG_MAX_BELT_LEN` translations since they no longer applied and I'm not sure what the correct translations would be for `MSG_HYPOT_LEN_AT_HOME_POS`.

### Requirements

Polargraph

### Benefits

Clears up configuration confusion by Polargraph users.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I'm waiting on comments/testing from @i-make-robots before moving this PR out of draft.

**Comment by i-make-robots** [comment]
Looks like what I did locally on my old branch from 2.0.9.5, only you also found the EEPROM updates I missed.

**Comment by thisiskeithb** [comment]
> Looks like what I did locally on my old branch from 2.0.9.5, only you also found the EEPROM updates I missed.

If you've tested the changes in this PR and they work on current `bugfix-2.1.x`, I'll move this PR out of draft.

**Comment by i-make-robots** [comment]
I'm not sure calling it hypotenuse is the best idea.  Distance from home to switch can vary a lot between builds.  There was one person on the discord who had a build with 3 pullies which added to the distance to the end switch, making the difference between belt length and hypotenuse quite large.

**Comment by thisiskeithb** [comment]
> I'm not sure calling it hypotenuse is the best idea. 

So what do you want to call it?

**Comment by i-make-robots** [comment]
i had called it something like "max length at home position" or "max length at switch position".

**Comment by thisiskeithb** [comment]
> i had called it something like "max length at home position" or "max length at switch position".

Maybe just updating the comment is enough instead of a full rename?

**Comment by i-make-robots** [comment]
well... should a variable name be clear or not?

**Comment by thisiskeithb** [comment]
> well... should a variable name be clear or not?

It should, but this PR was created at your request and I am not familiar with polargraph kinematics/usage.

Please suggest a new define name with an updated comment that will work for you so I can add it to `Configuration.h`.

**Pull request closed without merging**
