### PR TITLE
Idex Mirror mode based on Formbot / vivedino Symetric mode

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Allows mirrored duplication on IDEX systems and changes default mode to what has been most tested.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
@InsanityAutomation    Thank You for getting this done!!!

**Comment by InsanityAutomation** [comment]
No problem! All I did was the legwork to update configs and comments, text strings ect. Nothing major is mine this time.

**Comment by thinkyhead** [comment]
A bit of cleanup applied, and should be ready to go at this point. It may be worthwhile to smartly update the X software endstops so that the first X carriage will be automatically prevented from moving past the point where it just meets the other carriage in mirrored mode.

It should be tested that the correct position is shown by `M114` in all cases after doing a mirrored move followed by a mode change and then a tool-change.

**Comment by InsanityAutomation** [comment]
For that start point would need to be fixed and calculated based on bed size, or a run-time calculation based on stored start position. Former easier and less memory intensive, latter most flexible. Either way, something I've considered along with an auto push inactive head before crashing in full control mode.

**Comment by thinkyhead** [comment]
I see the initial distance is enforced on `M605 S2 X[dist]` first, then followed by `M605 S3`, so that's a good way to be able to align where you want the outer bounds of the mirrored things to be. The tricky part for me is imagining how it can be aligned without knowing what the bounds of the print will be. I guess you have to slice with mirroring in mind… or can workspace offsets be used also?

**Comment by thinkyhead** [comment]
> can workspace offsets be used also?

A: Yes, they can. If the thing was sliced to be centered at 100, it could be moved to the left to be centered at 50 instead.

**Comment by InsanityAutomation** [comment]
Typically the slicer is limited to half the bed size. Most mfg's provide two separate profiles, one with the split bed size for duplicate mode. Otherwise there's no way to ensure all geometry fits the newly reduced size and the part will be able to complete.

**Pull request merged**
