### PR TITLE
Vietnamese language

### PR DESCRIPTION
**Pull request by thinkyhead**
Revived from #13673 without the last couple of commits from a SNAFU'ed repository.

### CODE REVIEW

**Comment by lehuuloc-0104** [comment]
Help me,
I have downloaded fw to add the Vietnamese language that you share, but special characters such as "ẵ", "ể", ... are not displayed on the LCD full graphic.
Do you have any way to fix it?
IMG_20190821_165220
IMG_20190821_165228

**Comment by AnHardt** [comment]
@lehuuloc-0104 
If i'm remembering right.
Open https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/marlin-6x12-3.bdf in [fontforge](https://fontforge.github.io/en-US/). Look up the (missing) [glyphs](https://www.utf8-chartable.de/unicode-utf8-table.pl) and if thy are empty, draw them.

Most missing ones should be in the block from U+1E00 (Latin extended additional) on.

Then add 'vi' in [genallfont.sh](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/genallfont.sh) and run.

Or that like.

**Comment by lehuuloc-0104** [comment]
> @lehuuloc-0104
> If i'm remembering right.
> Open https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/marlin-6x12-3.bdf in [fontforge](https://fontforge.github.io/en-US/). Look up the (missing) [glyphs](https://www.utf8-chartable.de/unicode-utf8-table.pl) and if thy are empty, draw them.
> 
> Most missing ones should be in the block from U+1E00 (Latin extended additional) on.
> 
> Then add 'vi' in [genallfont.sh](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/genallfont.sh) and run.
> 
> Or that like.

Oh, Thank you for your support.
I found in the file langdata_vi.h in Marlin/src/lcd/dogm/fontdata/ , I see the glyphs I need.
But in the file "marlin-6x12-3.bdf" I could not find them, so how do I draw on [fontforge]?
Capture
Untitled

**Comment by AnHardt** [comment]
This is not the FontForge support.

Double klick the glyph and draw in the appearing new window.

https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/uxggenpages.md may help in the later process.

**Comment by lehuuloc-0104** [comment]
> @lehuuloc-0104
> If i'm remembering right.
> Open https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/marlin-6x12-3.bdf in [fontforge](https://fontforge.github.io/en-US/). Look up the (missing) [glyphs](https://www.utf8-chartable.de/unicode-utf8-table.pl) and if thy are empty, draw them.
> 
> Most missing ones should be in the block from U+1E00 (Latin extended additional) on.
> 
> Then add 'vi' in [genallfont.sh](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/genallfont.sh) and run.
> 
> Or that like.

I drew character "ẵ" to the file marlin-6x12-3.bdf, then I proceeded to upload, but it still didn't work.
Do you have a way for it to work?

**Comment by AnHardt** [comment]
The .bdf is never uploaded.
You have to regenerate the actual forts and conversion tables first.
Please read https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/uxggenpages.md

**Comment by lehuuloc-0104** [comment]
> The .bdf is never uploaded.
> You have to regenerate the actual forts and conversion tables first.
> Please read https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/uxggenpages.md
Oh, thanks.
I understood your idea.
As far as I learn, I need to run file genallfont.sh after drawing the glyphs. Can you guide me to run the file "genallfont.sh" on Windows 10? I installed Cygwin but failed to create the file langdata_xx.h.
Help me, please.

**Comment by lehuuloc-0104** [comment]
> The .bdf is never uploaded.
> You have to regenerate the actual forts and conversion tables first.
> Please read https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/buildroot/share/fonts/uxggenpages.md

I followed the instructions in the file "buildroot/share/fonts/uxggenpages.md", but I still can't run the script "genallfont.sh".
Even installing and running the u8glib-master library with the "get-bdf2u8g.sh" command also failed, are you looking for a solution?

**Comment by thinkyhead** [comment]
Hey @lehuuloc-0104 — Thanks for helping us out. This PR is only being delayed by the font issue, so once we have that solved this can (finally) get merged. It looks like you've gotten pretty far in your efforts. I'm not sure why the `genallfonts.sh` script is failing for you. If you could ZIP up all your font work files and drop them into your next reply, I will try to get it working.

**Comment by thinkyhead** [comment]
Ah, I see that your main issue is you have to build `bdf2u8g` using the provided script. Sorry about the error message. We will change the script to improve the error for future usage.

**Comment by thinkyhead** [comment]
- See if `unzip u8glib-master.zip` works from the command line after the script fails.

**Comment by lehuuloc-0104** [comment]
> Hey @lehuuloc-0104 — Thanks for helping us out. This PR is only being delayed by the font issue, so once we have that solved this can (finally) get merged. It looks like you've gotten pretty far in your efforts. I'm not sure why the `genallfonts.sh` script is failing for you. If you could ZIP up all your font work files and drop them into your next reply, I will try to get it working.

Hi @thinkyhead,
I created additional Vietnamese fonts from glyph 7840 to glyph 7929 in the file [marlin-6x12-3.bdf]. 
I send you the folder [buildroot], [language_vi.h] and [langdata_vi.h]. I hope you can help me compile the marlin-6x12-3.bdf font to the file [langdata_vi.h] I need to upload the marlin firmware.
Thanks for your support.
[marlin_fontdata_vietnamese.zip](https://github.com/MarlinFirmware/Marlin/files/3536947/marlin_fontdata_vietnamese.zip)

**Comment by thinkyhead** [comment]
Do you think the translations are okay? Our friend @shitcreek is entirely to blame. 😅

**Comment by thinkyhead** [comment]
Theoretically this should now work! I will test it shortly, since I am re-flashing a printer anyway.

**Comment by thinkyhead** [comment]
I have tested this and I can confirm that it now works. The diacriticals are drawn on top of other things, but this is not a problem. It is still very readable.

**Comment by lehuuloc-0104** [comment]
Hi @thinkyhead,
Now, with your edit, when I want to change the glyphs of the file [marlin-6x12-3.bdf], can I run the file [genallfont.sh]?
How can I run it to compile to the file [langdata_vi.h]? Can you guide me?

**Comment by lehuuloc-0104** [comment]
Hi @thinkyhead ,
As you say "I have tested this and I can confirm that it now works.", I have checked and edited the glyphs for a better fit. But I don't know how to compile into the [langdata_vi.h] file, can you help me compile it?
[fonts.zip](https://github.com/MarlinFirmware/Marlin/files/3537869/fonts.zip)

**Comment by lehuuloc-0104** [comment]
Hi @thinkyhead 
I tried running the file [get-bdf2u8g.sh], but it failed. Can you help me?
Capture

**Comment by lehuuloc-0104** [comment]
Hi @thinkyhead ,
I was able to compile fontdata at my discretion, thank you for your support very much.

**Pull request merged**
