### PR TITLE
[2.0.x] Improvements to runout sensor, fix for screen size when using LIGHTWEIGHT_UI #12542

### PR DESCRIPTION
**Pull request by marcio-ao**
Improvements to filament runout sensor
----
- Will ignore retraction/extrusion without movement.
- Enhanced debug message for legibility.

Fix screen size when using LIGHTWEIGHT_UI (#12542)
----
- LIGHTWEIGHT_UI uses text mode for the status screen but continues
to draw the menu with u8g. Therefore, the menus should not be resized
when using LIGHTWEIGHT_UI

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
Fyi, we we're able to reduce the false triggers during start of print and when e moves exceed runout distance by modifying changing line 77 from just enabled to : if (enabled && !filament_ran_out && (IS_SD_PRINTING() || print_job_timer.isRunning())) {

I may add another check to run where it clears accumulation if the sensor comes back so a noisy line doesn't trigger it repeatedly.

**Comment by marcio-ao** [comment]
@InsanityAutomation: That's weird. `run()` is the only thing that can trigger a runout, `block_completed()` simply updates the counters. I don't understand how adding redundant checks to `block_completed()` makes any difference.

BTW, in a recent commit I implemented @thinkyhead's suggestion to only increment the extrusion counter when XYZ moves are also happening. This should cause most retract/prime moves to be ignored. Is it possible you pulled that code and it is that which is making a difference?

**Comment by InsanityAutomation** [comment]
Definitely didn't get that code. Had 5 machines constantly tripped at the start of a print job with a snapshot from the 20th, and adding that line all but 1 stopped. Merged this with that last night and will get feedback today on if the combination got rid of any more false triggers.

**Comment by marcio-ao** [comment]
@InsanityAutomation: Could you upload the GCODE where you were seeing these false positives? Perhaps you were doing extruder moves while print job timer was not running and adding a check for `print_job_timer.isRunning()` kept the runout code from executing at the start of your print.

If that is the case, it simply masks the problem, rather than fixing it. Could you try my most recent commit without your modification and tell me if it works just as well?

**Comment by thinkyhead** [comment]
I fixed a bug in filament runout yesterday (#12547) where the fil-runout-inverting wasn’t being handled correctly. I noticed this right away when I flashed my CR-10S with the same configuration as I had been using and it kept false triggering a runout. I was using fil-runout-inverting.

**Comment by InsanityAutomation** [comment]
I didn't forget about retesting, just got busy! I'll get it this weekend....

**Pull request merged**
