### PR TITLE
Add Joystick

### PR DESCRIPTION
**Pull request by schirrel**
I think i learned how to make a pr now hehe

### CODE REVIEW

**Comment by KiteLab** [comment]
The Travis check fails because you deleted  Marlin.pde .
A PR should be in a way, not including your personal changes. (Changed README.md)
Defining a new feature by default is not a good idea. Add it commented to all configurations.
We have several Configuration.h files
Did you define `JOYSTICK_SENSIBILITY` somewhere? I can't find the definition, only the use.
The `Release` branch is closed for ANY further development.

Thanks for sharing your code. The feature as such, as well as the implementation are looking promising to me.
EDITED

**Comment by Wackerbarth** [comment]
@KiteLab -- The Travis checks fail, not because Marlin.pde was deleted (it is deprecated and no longer used) but rather because this the change is presented against an inappropriate source branch.

For usability, the contributor should really utilize a branch name which is different from that of the branch which he is modifying. (e.g. "joystick" might be a good name.)

The "Release" branch is never the appropriate branch for new code.
The contribution really needs to be made against the MarlinDev repository "master" branch.

**Comment by schirrel** [comment]
Yeah @KiteLab  i think i forget this.
In fact i was using an old release of the firm for the test of the joystick and now i'm porting to the new version , my bad. Tonight i'll fix it and commit :3

**Comment by KiteLab** [comment]
Dear @Wackerbarth 
https://travis-ci.org/MarlinFirmware/Marlin/builds/93356299 line 603

> The command "rm Marlin/Marlin.pde" failed and exited with 1 during .

failed **exactly** because 'Marlin.pde' was removed in commit https://github.com/CoderSquirrel/Marlin/commit/73963d9416b1b66bcaab15b5adf96aabd1c2df3e

Discussing the correct repository/branch was left out for the expert intentionally.

**Comment by schirrel** [comment]
Correted the missing #define.
As i said it need to be tested in a normal or bigger lcd, i only tested at a 16x2, that is the only one i have

**Pull request closed without merging**
