### PR TITLE
Fix M115 parsing

### PR DESCRIPTION
**Pull request by kisslorand**
### Description

PR #26806 broke the parsing of the printer's name ("MACHINE_TYPE:") on some printers. (The parsing is done by extracting the text between "MACHINE_TYPE:" and "EXTRUDER_COUNT:".) This PR fixes this issue.

The parameter "KINEMATICS:" is moved to a place where it is preceded by numerical values (extruder count or axis count) so it does not interfere with parsing of the extruder count and/or axis count.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I've already patched this in BTT's TFT firmware: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2913

This PR now breaks the printer name in their firmware again.

**Comment by kisslorand** [comment]
There are numerous printers with other FW than the one mentioned. It's best practice to address the underlying cause of an issue rather than just its immediate effect.

**Comment by thisiskeithb** [comment]
> There are numerous printers with other FW than the one mentioned. It's best practice to address the underlying cause of an issue rather than just its immediate effect.

Can you provide an example? My fix is backward compatible with older & newer versions of Marlin.

**Comment by kisslorand** [comment]
An example would be any random custom firmware. (ex.: https://www.thingiverse.com/thing:4294049)

**Comment by thisiskeithb** [comment]
> An example would be any random custom firmware. (ex.: https://www.thingiverse.com/thing:4294049)

They just need to pull in the latest TFT firmware from BTT's repo.

@digant73: Don't forget to update your fork(s) 😄

**Comment by kisslorand** [comment]
Than we're back what I've just said: "It's best practice to address the underlying cause of an issue rather than just its immediate effect."

**Comment by thisiskeithb** [comment]
> Than we're back what I've just said: "It's best practice to address the underlying cause of an issue rather than just its immediate effect."

This PR is just a workaround when the actual fix has already been applied to BTT's TFT firmware.

Update your TFT firmware to the latest version and you'll be set.

**Pull request closed without merging**
