### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by lpgn**

### CODE REVIEW

**Comment by galexander1** [comment]
oh! I misunderstood at first.  I think you closed it without merging it, so it doesn't need to be reverted. :)

**Comment by lpgn** [comment]
cool :)

**Comment by boelle** [comment]
we welcome that features etc are ported back in to marlin, but at the moment we are in the process of doing some bugfixing and cleanup of the code... so it might take some time before a merge happens

**Comment by lpgn** [comment]
I have been reading every message! sometimes hundreds a day ;-). good work @boelle ! but in my case it was an accident.
If you need a tester I volunteer. I use the printrboard with a printer a designed/build.

cheers,

**Pull request closed without merging**
