### PR TITLE
Fix 2.0.x CI Tests

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Fix 2.0.x CI Tests

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Silly bot!

**Comment by thisiskeithb** [comment]
Ahh, good. I was hoping CI would catch this! We have a new bug in the `2.0.x` branch:

```prolog
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../core/drivers.h:83:51: error: missing binary operator before token "("
   83 | #define AXIS_DRIVER_TYPE(A,T) AXIS_DRIVER_TYPE_##A(T)
      |                                                   ^
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../core/drivers.h:1[23](https://github.com/MarlinFirmware/Marlin/runs/6738199285?check_suite_focus=true#step:7:24):31: note: in expansion of macro 'AXIS_DRIVER_TYPE'
  123 | #define AXIS_IS_TMC(A)   (    AXIS_DRIVER_TYPE(A,TMC2130) || AXIS_DRIVER_TYPE(A,TMC2160) \
      |                               ^~~~~~~~~~~~~~~~
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../../Configuration_adv.h:2881:7: note: in expansion of macro 'AXIS_IS_TMC'
 2881 |   #if AXIS_IS_TMC(U)
      |       ^~~~~~~~~~~
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../core/drivers.h:83:51: error: missing binary operator before token "("
   83 | #define AXIS_DRIVER_TYPE(A,T) AXIS_DRIVER_TYPE_##A(T)
      |                                                   ^
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../core/drivers.h:123:31: note: in expansion of macro 'AXIS_DRIVER_TYPE'
  123 | #define AXIS_IS_TMC(A)   (    AXIS_DRIVER_TYPE(A,TMC2130) || AXIS_DRIVER_TYPE(A,TMC2160) \
      |                               ^~~~~~~~~~~~~~~~
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../../Configuration_adv.h:[28](https://github.com/MarlinFirmware/Marlin/runs/6738199285?check_suite_focus=true#step:7:29)91:7: note: in expansion of macro 'AXIS_IS_TMC'
 2891 |   #if AXIS_IS_TMC(V)
      |       ^~~~~~~~~~~
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../core/drivers.h:83:51: error: missing binary operator before token "("
   83 | #define AXIS_DRIVER_TYPE(A,T) AXIS_DRIVER_TYPE_##A(T)
      |                                                   ^
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../core/drivers.h:123:31: note: in expansion of macro 'AXIS_DRIVER_TYPE'
  123 | #define AXIS_IS_TMC(A)   (    AXIS_DRIVER_TYPE(A,TMC2130) || AXIS_DRIVER_TYPE(A,TMC2160) \
      |                               ^~~~~~~~~~~~~~~~
buildroot/share/PlatformIO/scripts/../../../../Marlin/src/inc/../../Configuration_adv.h:[29](https://github.com/MarlinFirmware/Marlin/runs/6738199285?check_suite_focus=true#step:7:30)01:7: note: in expansion of macro 'AXIS_IS_TMC'
 2901 |   #if AXIS_IS_TMC(W)
      |       ^~~~~~~~~~~
```

**Comment by thisiskeithb** [comment]
Also see: 
- https://github.com/MarlinFirmware/Marlin/issues/24287

**Comment by thisiskeithb** [comment]
Can you bring back `test-builds.yml`? It would have caught the issues with `2.0.x` / `2.0.9.4` not compiling.

**Comment by thinkyhead** [comment]
> Can you bring back `test-builds.yml`?

We'll see. I'm starting out by deleting all actions except those that live on the default branch, which is where GitHub has been finding some of our actions. Actions that should behave differently on a different branch can then be restored to that branch. For example, different branches will want to use different config versions, so either different actions are needed, or the `use_example_config` script can be modified to use the same name as the current branch, or it may take an additional argument…. Well, in that case the action may just remain the same…. I'll find out more after some experimentation.

**Pull request closed without merging**
