### PR TITLE
[2.0.x] Filament Loading LCD menu

### PR DESCRIPTION
**Pull request by thinkyhead**
Replacing #9703 by @Studiodyne

### CODE REVIEW

**Comment by junwoo091400** [comment]
Persona Non Grata? :P

**Comment by thinkyhead** [comment]
It's Latin for "person not appreciated."

**Comment by Studiodyne** [comment]
Mdrrr !
It's me !
😄

**Comment by ghost** [comment]
Note: Can make confusion if advanced pause enabled , because of 2 same name menus , if you can find and little idea to avoid 2 same name menus , it's perfect

**Comment by cjsoong** [comment]
I really like this feature

**Comment by junwoo091400** [comment]
Haha I looked at the history and i feel where 'Persona Non Grata' came from. Very interesting...

**Comment by Studiodyne** [comment]
I'm a good guy , but only god knows this 😄

**Pull request closed without merging**
