### PR TITLE
Fix SKRmini test required serial port(s)

### PR DESCRIPTION
**Pull request by tpruvot**
If needed, you can find a sample config there :  https://github.com/tpruvot/Marlin/tree/SKRmini-2.x/Marlin

but this card can be used with many different drivers/bed etc.

### CODE REVIEW

**Comment by tpruvot** [comment]
oh btw, i see "BOARD_BIGTREE_SKR_E3_DIP" in the mini test, different one

**Comment by tpruvot** [comment]
to put in #14832 maybe... travis test could be droped then

**Comment by thinkyhead** [comment]
The E3 is standing in until we resolve "Serial port 0 does not exist" with the MINI_V_1_1.

**Comment by tpruvot** [comment]
but these options are the really used/working ones on the SKR mini. Serial "TFT" connector + USB serial

**Pull request merged**
