### PR TITLE
Remove Old Experimental Tags

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Several features in Marlin have been marked as experimental for 5...6...7 years at this point and a common question from users is if they should enable X feature because it's marked as experimental.

So, let's remove some old experimental tags!

#### Removed / Updated

Remove experimental comment from:
- `ABL_BILINEAR_SUBDIVISION`
- `NOZZLE_CLEAN_FEATURE`
- `PID_EXTRUSION_SCALING`
- `EXPERIMENTAL_I2CBUS`

Rename `EXPERIMENTAL_I2CBUS` to `I2CBUS`.

Completely remove `EXPERIMENTAL_SCURVE` so users are free to enable `S_CURVE_ACCELERATION` with `LIN_ADVANCE`.

#### This following tags/features will remain marked as experimental
- `MPCTEMP` (even though it works well, this needs wider adoption/testing)
- `THERMAL_PROTECTION_VARIANCE_MONITOR` (this feature causes issues on builds with stable temps and I personally do not recommend it)
- `INPUT_SHAPING_X/Y` (new, still needs work/testing)
- `MULTI_VOLUME` (flash drive support is still buggy in general)
- `INTEGRATED_BABYSTEPPING` (even though it works well, this needs wider adoption/testing)
- `EXPERIMENTAL_I2S_LA` (new, needs wider adoption/testing)

### Benefits

Fewer questions about features being safe to enable.

### Related Issues

None. Discussion came up on Discord.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Configs repo will need to be updated for tests to pass.

**Comment by GMagician** [comment]
Just a question about S curve and lin_advance. I removed one because of "experimental", since I didn't know where/if something wrong could be caused by the presence of both.
Are there in the wild a lot of people, that you are aware, that use both without issues?
Thanks.

**Comment by thisiskeithb** [comment]
> Are there in the wild a lot of people, that you are aware, that use both without issues?
Thanks.

I haven’t seen reported issues.

I run them together on builds here and have both enabled in my PrusaAIO fork (for users who upgrade their MK3/S printers with 32-bit boards) without issues.

There may have been a time when the two were incompatible initially, but that doesn’t seem to be the case anymore.

**Comment by thinkyhead** [comment]
The I2CBUS stuff is meant for developers to experiment, and doesn't do anything useful without added code. So I don't mind continuing to call it "experimental." It would be interesting to see if anyone has applied it to an actual problem.

**Comment by nerdyscout** [comment]
I just experienced some issues building marlin with `EXPERIMENTAL_I2CBUS` for samd51.
When enabled I can build and upload, but no tty comes up. looks like some firmware is not booting, guess some memory leaking or so... behavior is exactly like [22456](https://github.com/MarlinFirmware/Marlin/issues/22456)

**Comment by thisiskeithb** [comment]
> I just experienced some issues building marlin with `EXPERIMENTAL_I2CBUS` for samd51. When enabled I can build and upload, but no tty comes up. looks like some firmware is not booting, guess some memory leaking or so... behavior is exactly like #22456

As [noted above](https://github.com/MarlinFirmware/Marlin/pull/25238#issuecomment-1383101105):

> The I2CBUS stuff is meant for developers to experiment, and doesn't do anything useful without added code.

So you’d need to add code for it to work. This isn’t the place to ask for help though. 

<hr>

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.com/servers/marlin-firmware-461605380783472640) Discord server

**Pull request merged**
