### PR TITLE
Polargraph settings

### PR DESCRIPTION
**Pull request by arthursw**
### Requirements

Enable to update the bed dimensions at run time for polargraph machines.

### Description

[Polargraph](http://www.polargraph.co.uk/) machines size can change when moved from one wall to another. 
It is important for some polargraph users to be able to change the machine dimensions without rebuilding the firmeware.
Thus, the command M665 can be used to modify the draw area, along with the segments-per-seconts and the max-belt-length.

### Benefits

Enable to change machine dimensions at run time.

### Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/8985387/Configuration.zip)

### Related Issues

https://discord.com/channels/521753686238560256/780846006945579058/976791012766810142

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for the update! We'll need to also update the documentation of `M665`, and we can add any additional details about the Polargraph system there.

The one fix I had to make here was for compatibility with `G20`.

**Comment by i-make-robots** [comment]
I'd like to suggest that dual-wielding M665 for deltas AND polargraphs is confusing.  How about an unused code like M667?  (i used https://marlinfw.org/docs/gcode/M665.html to locate nearby unused codes)

**Comment by arthursw** [comment]
@thinkyhead you mean [this doc repo](https://github.com/MarlinFirmware/MarlinDocumentation/tree/master/_gcode)?
@i-make-robots I am open to any code, M665 or M667 is ok to me!

**Comment by thinkyhead** [comment]
> you mean [this doc repo](https://github.com/MarlinFirmware/MarlinDocumentation/tree/master/_gcode)?

Yes, and also the RepRap wiki G-code page must be updated, because all (?) the active firmware developers are using that document as a point of reference for choosing new G-codes.

**Pull request merged**
