### PR TITLE
add missing mks robin2 env

### LINKED ISSUE #25782: [BUG] MKS_ROBIN2 env missing
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When using a MKS_ROBIN2 BOARD , latest Marlin 2.1.x dose not compile ... 

PS E:\3D\Arduino\Predator\MKS Robin 2\MKS-Robin2-master\firmware\Marlin-bugfix-2.1.x_Robin2> platformio run --silent -e MKS_ROBIN2
Error: Unknown environment names 'MKS_ROBIN2'. Valid names are 'STM32F103RC_creality_xfer, ........

### Bug Timeline

_No response_

### Expected behavior

In file stm32f4.ini there is no env for MKS_ROBIN2 (STM32F407ZET6) 

### Actual behavior

Error compiling

### Steps to Reproduce

1. Configuration.h setup MKS_ROBIN2 board  
#ifndef MOTHERBOARD
  #define MOTHERBOARD BOARD_MKS_ROBIN2
#endif

2. compile Marlin with env 
[platformio]
src_dir      = Marlin
boards_dir   = buildroot/share/PlatformIO/boards
default_envs = MKS_ROBIN2
include_dir  = Marlin

3. error...compiling

### Version of Marlin Firmware

2.1.x

### Printer model

bulding it

### Electronics

upgrading

### Add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/11405157/Configurations.zip)

### PR DESCRIPTION
**Pull request by ellensp**
### Description

It was recently noticed that although the mks robin2 board and pins had been added to Marlin in #16270. The required build environment had not.

Data extracted from  https://github.com/makerbase-mks/MKS-Robin2/tree/master/firmware/Marlin2.0-MKS-Robin2
and https://github.com/makerbase-mks/MKS-Robin2/blob/master/Hardware/MKS%20Robin2%20V1.0_002/MKS%20Robin2%20V1.0_002%20SCH.pdf

Then updated for a more modern platformio

### Requirements

mks_robin2 controller 

### Benefits

Will now build

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/25782

### Note: This is completely untested beyond compiling. 
This is just an semi educated guess as to what it should be.
I do not have access to a mks_robin2

### CODE REVIEW

**Comment by thinkyhead** [comment]
Good to see the variant was already worked out by @mks-viva over there. If this is derived from that board JSON and set of variant files then I expect this is pretty close.

I just applied some basic cleanup:
- The `board_build.variant` field is already specified in the JSON file, so removed.
- The `offset_and_rename.py` script creates `VECT_TAB_OFFSET` from `board_build.offset`, so removed.

I also have no Robin 2 to test on, and even if I did I couldn't do very comprehensive testing, so we may just release this into the wild and fix up any issues as we find them. Since it's based on the MKS's own firmware I have pretty high confidence it will be ok.

**Comment by ellensp** [comment]
There is no V2 in the name on the controller or in the docs 

they call it MKS Robin2 V1.0

so calling it V2 is not correct and confusing

**Comment by cheriodone** [comment]
[Marlin-bugfix-2.1.x.zip](https://github.com/MarlinFirmware/Marlin/files/11428661/Marlin-bugfix-2.1.x.zip)
 can up load files use git for now,here files i used to get Robin2 work with usb and sdcard

**Comment by LordsWars** [comment]
BOARDS_MKS_ROBIN2 V1.0
I needed to update the Marlin firmware, I saw the possibility of working with USB, I decided to download it and try it..
I downloaded the file from here:
@ncksnydr
[Merge branch 'bugfix-2.1.x' of](https://github.com/ncksnydr/Narungol-Marlin-Firmware/commit/18a63f3a2d6c35c3af844f8c67f66265a25e8811) https://github.com/MarlinFirmware/Marlin[…](https://github.com/ncksnydr/Narungol-Marlin-Firmware/commit/18a63f3a2d6c35c3af844f8c67f66265a25e8811) …
[18a63f3](https://github.com/ncksnydr/Narungol-Marlin-Firmware/commit/18a63f3a2d6c35c3af844f8c67f66265a25e8811)
I added the configuration files from this message, I compiled it and the system complained about the lack of definitions...
#define BOTH(V1,V2) ALL(V1,V2)
#define EITHER(V1,V2) ANY(V1,V2)
ok added it and I get the error again:
```

Executing task in folder Marlin-bugfix-2.1.x_usb_cd: C:\Users\LORD\.platformio\penv\Scripts\platformio.exe run

Processing MKS_ROBIN2_USB (board: marlin_MKS_Robin2; platform: ststm32@~12.1; framework: arduino)
-------------------------------------------------- -------------------------------------------------- -------------------------------------------------- ---------------------Verbose mode can be enabled via `-v, --verbose` option
Generating config.ini ...
Error: Build environment 'MKS_ROBIN2_USB' is incompatible with BOARD_MKS_ROBIN2. Use one of these environments: mks_robin2
===================================================== ===================== [FAILED] Took 7.49 seconds ======================= ================================================================

Environment Status Duration
-------------- -------- ------------
MKS_ROBIN2_USB FAILED 00:00:07.489
===================================================== ================ 1 failed, 0 succeeded in 00:00:07.489 ======================= ===========================================================
  * The terminal process "C:\Users\LORD\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.
  * Terminal will be reused by tasks, press any key to close it.
```
how to assemble this correctly? Is there an archive (full with marlin inside) where this version of the board compiles normally? I understand that I will then have to transfer the internals for my tasks, but I would still like it to compile without errors and not look for and fix a bunch of faults.....

**Comment by thisiskeithb** [comment]
@LordsWars: This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on [this page](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.1.x/.github/contributing.md#i-dont-want-to-read-this-whole-thing-i-just-have-a-question).) For best results getting help with configuration and troubleshooting, please use the following resources:

- [Marlin Documentation](https://marlinfw.org) hosted on MarlinFW.org
- [Marlin Forum](https://forums.reprap.org/list.php?415) hosted on RepRap.org
- [Marlin Firmware](https://www.facebook.com/groups/1049718498464482/) Facebook Group 
- [Marlin Firmware for 3D Printers](https://www.facebook.com/groups/3Dtechtalk/) Facebook Group
- [Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
- [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server

**Comment by LordsWars** [comment]
So should I create a separate branch? Why create branches if all the developers are here and I have such a board and I can check this version of support...at the same time, I am a programmer myself and after spending a lot of time I’ll figure it out myself like I did last time https://github.com/makerbase-mks/MKS-Robin/issues/185#issuecomment-805756951
I just want to do it quickly and efficiently so that all the functions of the board work. oh well... the compilation went BUT it stopped again... what I did: in the file: PINS.H
changed to 
#include "stm32f4/pins_MKS_ROBIN2.h"               // STM32F4                             env: mks_robin2
to   
#include "stm32f4/pins_MKS_ROBIN2.h"              // STM32F4                              env:MKS_ROBIN2
and the compilation continued but again ran into errors:
```
Compiling .pio\build\MKS_ROBIN2_USB\src\src\HAL\STM32\MarlinSerial.cpp.o
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:54,
                 from Marlin\src\HAL\STM32\HAL.cpp:26:
Marlin\src\HAL\STM32\../../inc/Changes.h:86:4: error: #error "ALLOW_LOW_EJERK is deprecated and should be removed."
   86 |   #error "ALLOW_LOW_EJERK is deprecated and should be removed."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:55,
                 from Marlin\src\HAL\STM32\HAL.cpp:26:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:993:6: error: #error "MPC_INCLUDE_FAN requires at least one fan."
  993 |     #error "MPC_INCLUDE_FAN requires at least one fan."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:54,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:26:
Marlin\src\HAL\STM32\../../inc/Changes.h:86:4: error: #error "ALLOW_LOW_EJERK is deprecated and should be removed."
   86 |   #error "ALLOW_LOW_EJERK is deprecated and should be removed."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:54,
                 from Marlin\src\HAL\STM32\HardwareSerial.cpp:32:
Marlin\src\HAL\STM32\../../inc/Changes.h:86:4: error: #error "ALLOW_LOW_EJERK is deprecated and should be removed."
   86 |   #error "ALLOW_LOW_EJERK is deprecated and should be removed."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:54,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/Changes.h:86:4: error: #error "ALLOW_LOW_EJERK is deprecated and should be removed."
   86 |   #error "ALLOW_LOW_EJERK is deprecated and should be removed."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:55,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:26:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:993:6: error: #error "MPC_INCLUDE_FAN requires at least one fan."
  993 |     #error "MPC_INCLUDE_FAN requires at least one fan."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:55,
                 from Marlin\src\HAL\STM32\HardwareSerial.cpp:32:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:993:6: error: #error "MPC_INCLUDE_FAN requires at least one fan."
  993 |     #error "MPC_INCLUDE_FAN requires at least one fan."
      |      ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:55,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:993:6: error: #error "MPC_INCLUDE_FAN requires at least one fan."
  993 |     #error "MPC_INCLUDE_FAN requires at least one fan."
      |      ^~~~~
*** [.pio\build\MKS_ROBIN2_USB\src\src\HAL\STM32\HAL.cpp.o] Error 1
*** [.pio\build\MKS_ROBIN2_USB\src\src\HAL\STM32\HardwareSerial.cpp.o] Error 1
*** [.pio\build\MKS_ROBIN2_USB\src\src\HAL\STM32\HAL_SPI.cpp.o] Error 1
*** [.pio\build\MKS_ROBIN2_USB\src\src\HAL\STM32\MarlinSerial.cpp.o] Error 1
```

**Pull request merged**
