### PR TITLE
RADDS: Add EEPROM Size

### PR DESCRIPTION
**Pull request by smoki3**
needed for UBL

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I'm not sure 8KB makes sense.    Do we really need that much persistent storage?

I'll merge and we can still discuss.   At least the compile errors will go away for the RADDS people!

**Comment by thinkyhead** [comment]
Probably `0x800` (2K) is enough, but `0xC00` (3K) would give a good amount of extra overhead.

**Comment by Roxy-3D** [comment]
Most of the AVR parts are 4 KB.   Or 0x1000 in size.    Wouldn't it make sense to use that number?
I don't know that it really matters.   But the less changes from the normal platforms the better....

**Comment by thinkyhead** [comment]
For 32-bit or SD card-based, 0x2000 will certainly leave lots of room. We'll probably find a use for it in the future.

**Pull request merged**
