### PR TITLE
completed french translation

### PR DESCRIPTION
**Pull request by gege2b**
I'm not sure why there is 16 commits
I've only synced my fork, edited the language file and pushed it back

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Sometimes Git adds "extra" commits. 

My solution is to do the usual rebase and then do an interactive rebase after that.  An edit window pops up where you can select which commits to keep, to drop and to merge/squash.  There's as section in [Contributing Code with Pull Requests](http://marlinfw.org/docs/development/getting_started_pull_requests.html) that gives some info on how to do that.

This has happened to me several times & so far dropping the "extra" commits hasn't hurt anything.

**Comment by thinkyhead** [comment]
You should do your work in a copy of `RCBugFix` so you can keep a pristine copy of the branch around. Next time.

Anyway, to update this branch you should do…
```
git remote add upstream git@github.com:MarlinFirmware/Marlin.git
git fetch upstream
git checkout RCBugFix
git rebase upstream/RCBugFix
```
Resolve any conflict, and after each resolution…
```
git add *
git rebase --continue
```
Finally…
```
git push -f
```

**Comment by thinkyhead** [comment]
Or, you can fix things up in another branch, starting from a copy of the latest `RCBugFix`. Once the branch is as you like it, replace this PR with the new commits.

For example, to add your single French commit to a fresh `RCBugFix` and replace this PR:
```
git remote add upstream git@github.com:MarlinFirmware/Marlin.git
git fetch upstream
git checkout upstream/RCBugFix -b my_new_french_branch

git cherry-pick 69fdfb6

git checkout RCBugFix
git reset --hard my_new_french_branch
git push -f
```

**Comment by gege2b** [comment]
OK I got it.
I'll close this one for now, and open a new one.
thank you for your help !

**Pull request closed without merging**
