### PR TITLE
[1.1.x] Update CR-10 _Bootscreen.h

### PR DESCRIPTION
**Pull request by plainpylut**
Correct `_Bootscreen.h` from #9660.
Provide `_Statusscreen.h` for CR-10 Mini.

### CODE REVIEW

**Comment by plainpylut** [comment]
_Bootscreen needs to be updated in subdirectories 'Creality/CR-10' and 'Creality/CR-10S'.
_Statusscreen needs to be updated in subdir 'Creality/CR-10'.

[_Statusscreen.zip](https://github.com/MarlinFirmware/Marlin/files/1742279/_Statusscreen.zip)

**Comment by AnHardt** [comment]
Does it really work without defining `CUSTOM_BOOTSCREEN_BMPHEIGHT`.
Why did you burn (23+ 24) * 16  = 752 bytes for centering the writing vertically, when the used algorithm does the same.
https://github.com/MarlinFirmware/Marlin/blob/ac3fab7a9680a880fd1b113be7e758c6dabb2a57/Marlin/ultralcd_impl_DOGM.h#L290-L299.

**Comment by thinkyhead** [comment]
Reduced the "Creality 3D" bootscreen and the (inverted) Ender bootscreen also. See the PR below.

**Comment by thinkyhead** [comment]
The `_Statusscreen.h` won't be included until we have a CR-10 Mini configuration.

**Comment by thinkyhead** [comment]
> Does it really work without defining `CUSTOM_BOOTSCREEN_BMPHEIGHT`.

This value is now derived from the width and total size.

**Comment by plainpylut** [comment]
Scott,

Here is the response from my twin brother, Larry.
If you have more questions, his email is ****

He has a Creality CR-10 Mini and has Marlin BugFix 1.1.8 compiled and running on it.

Garry


From: Larry Kraemer 

Garry,

Yes, the Marlin-bugfix-1.1.x software works without defining either CUSTOM_BOOTSCREEN_BMPHEIGHT or
CUSTOM_BOOTSCREEN_BMP_BYTEWIDTH


I've used grep to locate where that definition is located:
~/arduino-1.8.5/Sketchbook/Marlin-bugfix-1.1.x$ grep -r CUSTOM_BOOTSCREEN_BMPHEIGHT ./*

./Marlin/dogm_bitmaps.h:#ifndef CUSTOM_BOOTSCREEN_BMPHEIGHT
./Marlin/dogm_bitmaps.h:  #define CUSTOM_BOOTSCREEN_BMPHEIGHT (sizeof(custom_start_bmp) / (CUSTOM_BOOTSCREEN_BMP_BYTEWIDTH))
./Marlin/ultralcd_impl_DOGM.h:          (LCD_PIXEL_HEIGHT - (CUSTOM_BOOTSCREEN_BMPHEIGHT)) / 2,
./Marlin/ultralcd_impl_DOGM.h:          CEILING(CUSTOM_BOOTSCREEN_BMPWIDTH, 8), CUSTOM_BOOTSCREEN_BMPHEIGHT, custom_start_bmp


from that I've zipped dogm_bitmaps.h, ultralcd_impl_DOGM.h, along with my configuration.h and configuration_adv.h,

plus the original _Bootscreen.h (LARGE SIZE) and the minimumized version I just submitted a few minutes ago,

Both _Bootscreen.h files are centered on the screen and look the same (except for the LARGE size).

I've attached the ZIP, so Scott has the exact files I'm using.  (I built the bugfix ver 1.1.x today with the smaller _Bootscreen.h

and it works fine.  Display of "Creality 3D" is centered Vertically & Horizontally.  I reduced the size because of some concern

about using that much Flash Memory.

**Comment by thinkyhead** [comment]
I didn't ask any questions, but thanks! I've done your brother a favor and removed his email address from this public posting.

**Pull request closed without merging**
