### PR TITLE
Use 'extends' for STM32F1

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

Utilize `extends` in PlatformIO to extract the commonalities between all STM32F1 environments.

Visual Studio Code doesn't properly recognize environments if their `platform` is included as part of an `extends` variable. For this reason I have left `platform` in each environment even though PlatformIO does not require it.

This PR overlaps with another PR of mine: #18089.
If this PR is merged then #18089 is not necessary.

### Benefits

Allows STM32F1-specific changes to be made in one place and apply to all environments.
In this changelist, the only real change is reducing the version of the `Adafruit MAX31865 library`, since version 1.2 is incompatible with the STM32F1 HAL.

### Related Issues

#18081

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I am currently printing on an SKR Mini E3 1.0 built using these changes from inside VS Code.

**Comment by sjasonsmith** [comment]
I've updated this to use a dynamic variable for the platform name, rather than redefining `ststm32` in every environment. This way we satisfy VS Code's need for every environment to contain a platform entry, while still allowing it to be overridden from one place.

**Comment by thinkyhead** [comment]
Unfortunately, last I checked with PlatformIO, the VSCode extension still doesn't know what to do with `extends` and it won't display any environment that includes it in the Tasks list. That's why I have not re-applied `extends` yet since I first tried it in December.

**Comment by thinkyhead** [comment]
Just checked, and the PlatformIO extension still hasn't been updated since November. So we have to wait for that to happen before we can enjoy the benefits of `extends`.

**Comment by sjasonsmith** [comment]
> Unfortunately, last I checked with PlatformIO, the VSCode extension still doesn't know what to do with `extends` and it won't display any environment that includes it in the Tasks list. That's why I have not re-applied `extends` yet since I first tried it in December.

@thinkyhead, it shows them as long as you define `platform` in each environment. If you comment out `platform` they disappear as you describe.

**Comment by thinkyhead** [comment]
Oh, that's interesting. I wonder why that matters.

**Pull request merged**
