### PR TITLE
On pause still report "SD printing byte X/Y".

### PR DESCRIPTION
**Pull request by arekm**
When printing from sd card and print is paused (via lcd or filament
runout happens) then Marlin starts reporting "Not SD printing" (over serial)
which is not really what is happening.

This causes problem with OctoPrint. When it sees "Not SD printing"
is considers that printing is cancelled and migrates it's state
from "Pausing" to "Cancelling", executes cancel-gcode (defined by user)
etc and basically stops entire print. (In my cause that was on filament
runout).

Anyway, reporting "SD printing byte X/Y" (where X simply doesn't
raise) makes sense. We are indeed in middle of printing, just paused
at the moment.

### CODE REVIEW

**Comment by arekm** [comment]
btw. Prusa firmware prints "SD print paused" in such case but not sure if that's desired in marlin, too (and other text for USB printing) .

```
void CardReader::getStatus(bool arg_P)
{
    if (isPrintPaused)
    {
        if (saved_printing && (saved_printing_type == PRINTING_TYPE_SD))
            SERIAL_PROTOCOLLNPGM("SD print paused");
        else
            SERIAL_PROTOCOLLNPGM("Print saved");
    }
   else if (sdprinting)
    {
[...]
   SERIAL_PROTOCOLRPGM(_N("SD printing byte "));////MSG_SD_PRINTING_BYTE
[...]
    }
    else
        SERIAL_PROTOCOLLNPGM("Not SD printing");
```

https://github.com/prusa3d/Prusa-Firmware/blob/MK3/Firmware/cardreader.cpp#L558-L587

**Comment by thinkyhead** [comment]
> btw. Prusa firmware prints "SD print paused" in such case but not sure if that's desired in marlin, too (and other text for USB printing) .

Marlin is still less stateful and less verbose than the more targeted Prusa Firmware, and has been more conservative in part due to the standing aim to keep the default firmware as small as possible so it still fits on small (32K) controllers. We should definitely back-port a number of things which have not yet been back-ported from Prusa Firmware, such as these added state reports.

Marlin has a longstanding custom to make any additions that grow the default firmware build size optional. At this point, it's an open question whether to support the smallest AVR controllers. We don't automatically test for the minimum build size, but it would be interesting to build the smallest usable Marlin firmware across many versions and put those build sizes into a spreadsheet. For science!

**Comment by arekm** [comment]
IMO proposed patch is just fine since Marlin reports information about pause anyway ("echo:busy: paused for user" with appropriate options).

**Comment by kisslorand** [comment]
How will an external host (Octoprint, serial TFT) know that the print is resumed after a pause ("echo:busy: paused for user")?

**Comment by arekm** [comment]
OctoPrint sees bytes progress and also reacts on "actions" like:

```
2022-08-30 22:24:26,524 - Recv: //action:resumed
2022-08-30 22:24:26,525 - Printer signalled that it resumed, switching state...
```

and, as mentioned earlier, without this patch OctoPrint will cancel print seeing that printer says it doesn't print.

No idea about serial TFT.

**Comment by kisslorand** [comment]
I am asking these because this PR breaks the Bigtreetech TFT's firmware behaviour. It was relying on "Not SD printing" to know that it's paused" and "SD Printing byte" to know pause has been resumed.

**Comment by arekm** [comment]
How it know in case of cancelled print? (which is also "Not SD printing")

**Comment by kisslorand** [comment]
...by the ":cancel" keyword

**Comment by arekm** [comment]
Ah, ok, so best solution for it is to react on explicit "//action:resumed" instead of guessing.

**Comment by kisslorand** [comment]
Yup, a patch will be needed if this PR gets into the master branch.

**Comment by arekm** [comment]
Why master? It's already in bugfix-2.1.x.

**Comment by kisslorand** [comment]
Not all PRs from "bugfix" branch get into the master.

**Comment by thisiskeithb** [comment]
> Not all PRs from "bugfix" branch get into the master.

`bugfix-2.1.x` is "master"/default here.

All of the commits from `bugfix-2.1.x` will go into `2.1.x` before the next tagged `2.1.x` release. Some of the `bugfix-2.1.x` commits will be backported to `2.0.x`, but don't count on it.

**Pull request merged**
