### PR TITLE
Allow BLTouch on Biqu BX

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Shift pins around in BX variant to allow a BLTouch to work on default servo pin `PA2`.

"ServoPin_t problem limit pinNum <= 63, set PA2 = 62 fix Bltouch problem" Ported from https://github.com/bigtreetech/BIQU-BX/commit/353ddaf922e813f0db871d8f28d48445aa01485d

### Requirements

Biqu BX

### Benefits

Allows BLTouch use on a Biqu BX

### Configurations

[/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/BIQU/BX](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/BIQU/BX)

### Related Issues

N/A found while working on other BX issues.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This PR needs to be tested on real hardware to make sure nothing else breaks 🙂

My BX board & TFT are still on my desk and not in a printer.

**Comment by thinkyhead** [comment]
Kind of strange. I always thought the port-index defined pins were numbered in a fixed way tied to the processor. So, what do the integer values assigned to these pin names mean, if they can be changed to suit an application? Or, is this more like a correction to a typo (i.e., moving `PA2` up to position 62 because that's where it properly belongs) and the board would never boot without this change?

**Comment by sjasonsmith** [comment]
I’m more concerned about the statement from the BTT commit that a PIN number can only be up to 63. This limitation makes sense on an AVR, but this should really be changed to 31 bits on 32-bit platforms:

```
typedef struct {
  uint8_t nbr        : 7 ;            // a pin number from 0 to 127
  uint8_t isActive   : 1 ;            // true if this channel is enabled, pin not pulsed if false
} ServoPin_t;
```

Now that I pasted that I see that is an unsigned 7 bit, so it should have worked up to 127 already, as the comment mentions.

**Comment by rhapsodyv** [comment]
Btt bx for is 2.0.6. Maybe they have another issue and fixed changing the variant… hard to tell.

maybe we should let this change out until someone complain about servos with BX.

**Comment by sjasonsmith** [comment]
@thinkyhead, this PIN number converts between the actual pin name/number (PA_2) and “fake Arduino” pin number (PA2). I believe they are completely arbitrary.

You’ll see the Keith is not changing PA_2. That change is in an array, not an enum. That constant is defined by the framework, not by the variant, because it does indeed map to hardware.

PA2 contains a different number, and provides an easy mapping from the “physical port/pin name” to the fake Arduino PIN number.

Occasionally issues arise because people mix up the constants with and without underscores. They are different and not interchangeable.

I believe this change would only cause problems if a user assigned their pins using actual integer literals, rather than `PA2`. Hopefully nobody is doing that.

I still favor removing any limitations that led to this change in the first place, though.

**Comment by sjasonsmith** [comment]
> Btt bx for is 2.0.6. Maybe they have another issue and fixed changing the variant… hard to tell.

Maybe the type used to only allow 6 bits and it changed to 7 at some point? Or was signed and is now unsigned?

**Comment by rhapsodyv** [comment]
The ServoPin_t didn’t changed. But there’re so many difference between 2.0.6 and now that another code could be the limitation… 🤷‍♂️

I keep my option that we should wait for a user that needs it.

Or test bltouch with and without this change, in a bx, if we can.

**Comment by sjasonsmith** [comment]
I agree with @rhapsodyv. This was a workaround at one point, but not really a proper fix. It would have left problems for the next person needing a Servo in a random pin. If there are still issues it should be  done in a way to fix the pin limitation for all boards.

**Comment by thisiskeithb** [comment]
Closing since I can't confirm if this change is still needed or if it actually does anything.

rhapsodyv pointed out this commit was missing from upstream while we were working through the BX issues, so I created a PR. If/when someone tries to use a BLTouch on a BX & has issues, then we can look at this again.

**Pull request closed without merging**
