### PR TITLE
Refactor LCD menus / screens

### PR DESCRIPTION
**Pull request by thinkyhead**
LCD menus are becoming long and unwieldy. To better organize them, this PR starts out by moving all LCD menu / screen handlers to a separate compilation unit. Once this is stabilized and passes Travis CI testing, the menus will be further subdivided by feature into a subfolder of `src/lcd`. But the first step is to ensure everything compiles under a wide variety of configurations.

### CODE REVIEW

**Comment by thinkyhead** [comment]
With this patch the binary is a couple hundred bytes larger than a build with the same test configuration. As this just the first rough result, I'm sure it can be optimized a lot to ensure that no code or data is being duplicated.

**Comment by Roxy-3D** [comment]
This is somewhat like breaking Marlin_main.cpp apart into little pieces.  It helped a huge amount to clean up the code.

**Comment by thinkyhead** [comment]
It should help! though it does make the binary a bit larger. There are probably some tricks that can be applied to get better linkage and reduce the binary size a lot, but this is a good first draft and does a good deal to reveal the dependencies that each menu has on various modules and features.

**Comment by thinkyhead** [comment]
And, oh yeah… Finally… finally! got rid of those LCD implementation `.h` files that weren't really headers and converted them to proper `.cpp` files.

**Comment by Roxy-3D** [comment]
> And, oh yeah… Finally… finally! got rid of those LCD implementation .h files that weren't really headers and converted them to proper .cpp files.

FINALLY!   Yes!   This is a very good thing to do!

**Pull request merged**
