### PR TITLE
Fix NEO_GRB/NEO_RGB typo / Partially Revert #23590

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

https://github.com/MarlinFirmware/Marlin/pull/23590/commits/4d731a2ea6d7bce3d4d62b274a1cc10ef701017f and https://github.com/MarlinFirmware/Marlin/pull/23590/commits/f6464103bb759e05dd87f8dfc5b0bae3587f6350 from #23590 changed `NEO_GRB` to `NEO_RGB` by mistake (?), but only `NEO_GRBW` & `NEO_GRB` are valid config options:

https://github.com/MarlinFirmware/Marlin/blob/fc50018b06285bc5c28288530df38f1d6724eaa0/Marlin/Configuration.h#L3047-L3051

### Requirements

`FYSETC_MINI_12864_2_1` or clone (`MKS_MINI_12864_V3`, `BTT_MINI_12864_V1`)

### Related Issues

- ~~None.~~ Discovered while rebasing some old configs that utilize one of these screens.
- https://github.com/MarlinFirmware/Marlin/issues/23808

### CODE REVIEW

**Comment by nicobits46** [comment]
hi I  just saw this im having this same problem with an mks tinybee and the btt mini 12864
any help? 

how can I fix this thank u, I see you r using skr 1.4?

<details><summary>Log Output</summary>

```
Compiling .pio\build\mks_tinybee\src\src\HAL\ESP32\Tone.cpp.o
In file included from Marlin\src\HAL\ESP32\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\HAL\ESP32\HAL.cpp:24:
Marlin\src\HAL\ESP32\../../inc/SanityCheck.h:2452:6: error: #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB."
     #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB." //NICO CHANGE NEO_RGB X NEO_GRB
      ^
                 from Marlin\src\HAL\ESP32\HAL_SPI.cpp:25:
Marlin\src\HAL\ESP32\../../inc/SanityCheck.h:2452:6: error: #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB."
     #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB." //NICO CHANGE NEO_RGB X NEO_GRB
      ^
In file included from Marlin\src\HAL\ESP32\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\HAL\ESP32\Servo.cpp:24:
Marlin\src\HAL\ESP32\../../inc/SanityCheck.h:2452:6: error: #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB."
     #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB." //NICO CHANGE NEO_RGB X NEO_GRB
      ^
In file included from Marlin\src\HAL\ESP32\../../inc/MarlinConfig.h:50:0,
                 from Marlin\src\HAL\ESP32\Tone.cpp:32:
Marlin\src\HAL\ESP32\../../inc/SanityCheck.h:2452:6: error: #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB."
     #error "Your FYSETC Mini Panel requires NEOPIXEL_TYPE to be NEO_RGB." //NICO CHANGE NEO_RGB X NEO_GRB
      ^
cc1plus.exe: warning: unrecognized command line option '-Wno-register'
*** [.pio\build\mks_tinybee\src\src\HAL\ESP32\HAL.cpp.o] Error 1
cc1plus.exe: warning: unrecognized command line option '-Wno-register'
cc1plus.exe: warning: unrecognized command line option '-Wno-register'
*** [.pio\build\mks_tinybee\src\src\HAL\ESP32\Servo.cpp.o] Error 1
*** [.pio\build\mks_tinybee\src\src\HAL\ESP32\HAL_SPI.cpp.o] Error 1
cc1plus.exe: warning: unrecognized command line option '-Wno-register'
*** [.pio\build\mks_tinybee\src\src\HAL\ESP32\Tone.cpp.o] Error 1
```
</details>

**Comment by thisiskeithb** [comment]
@nicobits46 Wait until this PR is merged or set `NEOPIXEL_TYPE` to `NEO_RGB` for now.

**Comment by nicobits46** [comment]
> @nicobits46 Wait until this PR is merged or set `NEOPIXEL_TYPE` to `NEO_RGB` for now.

ok, and where do I do that?? thanks

**Comment by thisiskeithb** [comment]
@nicobits46: Now that this PR is merged, you should no longer get a sanity check error alerting you to change `NEOPIXEL_TYPE` to `NEO_RGB`.

If you still need help, please join the [Marlin Firmware](https://discord.gg/n5NJ59y) Discord server.

**Pull request merged**
