### PR TITLE
Ender-3 Pro example configuration

### PR DESCRIPTION
**Pull request by Nikkelmann**
### Requirements

None

### Description

Copied from the Ender-3 example configuration, but changed the status screen logo to the Ender-3 Pro version from the [stock Ender3 Pro version 1.1.61 source code](https://www.creality3d.cn/download/firmware_c0001) using the [online tool](http://marlinfw.org/tools/u8glib/converter.html) to convert from hex to binary format and merging the images.

### Benefits

Brings back the stock image of the Ender-3 Pro on the status screen.

### Related Issues

None

### CODE REVIEW

**Comment by boelle** [comment]
you should push to 2.0.x and not 1.1.x

**Comment by InsanityAutomation** [comment]
The readme file will need to be removed as it doesn't apply to this. Also current status screen's only show the logo and hotends ETC are drawn on demand from the firmware side so that will need to be trimmed to match the 2.0 format.

Overall though, im not convinced the differing logo is enough cause to maintain a separate config file. Maybe just drop it next to the other in the Ender3 folder?

**Comment by thisiskeithb** [comment]
> The readme file will need to be removed as it doesn't apply to this. 

The [readme was removed](https://github.com/MarlinFirmware/Marlin/commit/02859eb2b15855ba464feb8b14f5f81b2f951eb2) because it no longer applies.

For the status screen, we could do [something similar to the Tornado configs](https://github.com/MarlinFirmware/Marlin/tree/8f0aedeeadff5e40d5435ee48e5d32facbb46da4/config/examples/Tevo/Tornado) (it uses two different boards, hence the different configs, but you get the idea).

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

---

Thanks for your contribution! Unfortunately we are no longer accepting PRs directed to the 1.1.x branch. Please redo this PR starting with the `bugfix-2.0.x` branch and be sure to target `bugfix-2.0.x` when resubmitting the PR.

**Pull request closed without merging**
