### PR TITLE
Reworked bootsplash for DOGM displays another time - saved 1786 bytes

### PR DESCRIPTION
**Pull request by AnHardt**
Result locks like:
picture 36
With #define START_BMPHIGH 
picture 37

### CODE REVIEW

**Comment by boelle** [comment]
ehmmm drop the reprap.org part... if anything put out own url there

2015-02-03 10:25 GMT+01:00 Andreas Hardtung notifications@github.com:

**Comment by AnHardt** [comment]
@boelle 
I didn't change that.
a) http://reprap.org/wiki/Marlin ?
b) https://github.com/MarlinFirmware/Marlin ?

Both a bit long but i'l do my best - if you can decide for one.

**Comment by boelle** [comment]
i did not speak to any individual directly....

i just saw the pic and spoke before thinking :-D

hmmm maybe use google url shortner tool?

http://goo.gl/3jzcuN

or maybe even go without any link?

2015-02-03 10:51 GMT+01:00 Andreas Hardtung notifications@github.com:

**Comment by AnHardt** [comment]
@boelle 
Limit is 22 characters for the url.

**Comment by boelle** [comment]
http://goo.gl/3jzcuN

should be 20

2015-02-03 10:55 GMT+01:00 Andreas Hardtung notifications@github.com:

**Comment by AnHardt** [comment]
@boelle 
http://goo.gl/3jzcuN is not really readable and you can't click it anyway.

**Comment by AnHardt** [comment]
@boelle 
Bootsplash is shown less than a second. No way to write it down.

**Comment by AnHardt** [comment]
Without an URL is no problem.

**Comment by boelle** [comment]
:-) then we should drop it.. and center ver no

2015-02-03 11:03 GMT+01:00 Andreas Hardtung notifications@github.com:

**Comment by AnHardt** [comment]
@boelle Done.
It's really easy to change now.
Maybe one day i'l make a dual line version.

**Comment by daid** [comment]
I own the very short domain name daid.eu, so I could provide you with a very short forward URL like daid.eu/m or m.daid.eu
Should be easier to remember in 1 second compared to the goo.gl url.

**Comment by AnHardt** [comment]
@boelle 
Dual line version done.
For example i added STRING_VERSION_CONFIG_H in line 2.
Dofault will be:
 //#define STRING_SPLASH_LINE2 STRING_VERSION_CONFIG_H
Put in later what ever you want.
picture 38
picture 39

**Comment by boelle** [comment]
+1

link does not make sense.... shown to short a time ....

2015-02-03 12:19 GMT+01:00 Andreas Hardtung notifications@github.com:

**Comment by boelle** [comment]
i can agree if its that short

2015-02-03 12:12 GMT+01:00 daid notifications@github.com:

**Comment by boelle** [comment]
or if someone had the cash to register marlin.eu?

2015-02-03 12:12 GMT+01:00 daid notifications@github.com:

**Comment by thinkyhead** [comment]
Looking very good @AnHardt. Once the changes and final link are settled upon, if you don't mind applying the same changes to all the `Configuration.h` files in the `example_configurations` directory, then this will be ready to merge.

If you find an available domain name, and if you need to forward it or host something modest, I can provide free hosting because I own a Hostgator hosting account.

**Comment by AnHardt** [comment]
@thinkyhead 
Done.

**Pull request merged**
