### PR TITLE
Bugfix 2.1.x

### PR DESCRIPTION
**Pull request by mikemerryguy**
### Requirements

none

### Benefits

prevents having one driver example Z2 with stealthchop OFF while Z has it enabled

### Configurations

* Use Trinamic's ultra quiet stepping mode.
   * When disabled, Marlin will use spreadCycle stepping mode.
   */

  #if HAS_STEALTHCHOP
    #define STEALTHCHOP_XY
    #define STEALTHCHOP_Z
	#define STEALTHCHOP_Z2
	#define STEALTHCHOP_Z3
	#define STEALTHCHOP_Z4
    #define STEALTHCHOP_I
    #define STEALTHCHOP_J
    #define STEALTHCHOP_K
@ -3076,6 +3080,13 @@
    #define STEALTHCHOP_V
    #define STEALTHCHOP_W
    #define STEALTHCHOP_E
	#define STEALTHCHOP_E1
	#define STEALTHCHOP_E2
	#define STEALTHCHOP_E3
	#define STEALTHCHOP_E4
	#define STEALTHCHOP_E5
	#define STEALTHCHOP_E6
	#define STEALTHCHOP_E7
  #endif

### CODE REVIEW

**Comment by thisiskeithb** [comment]
These extra defines won't do anything without further code changes.

**Comment by mikemerryguy** [comment]
> 

Yes you are correct, however if you define any of the extra drivers, it won't even enable stealthchop unless you add them.

Simplifies the code for beginers, ensures the drivers have matching settings.

**Comment by thinkyhead** [comment]
> Yes you are correct, however if you define any of the extra drivers, it won't even enable stealthchop unless you add them.

Incorrect. X also applies to X2, Y also applies to Y2, Z also applies to Z2, Z3, Z4. E applies to all extruders. See `reset_trinamic_drivers()` in `trinamic.cpp`.

**Comment by mikemerryguy** [comment]
Well there must be an error, as I recently updated to 2.0.9.3( bugfix) and Z2 stealthcop is OFF by default while Z is ON. 
Added this and now both are ON.

**Comment by mikemerryguy** [comment]
yup, i dunno, must have just been a random compile error, my bad, they are all working without this, just strange it had it off on z2 on my initil build!

**Pull request closed without merging**
