### PR TITLE
Remove BTT SKR Mini 512K "RCT6" Environments

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Now that all the SKR Mini E3 boards are migrated to the STM32 HAL, it'd be a good idea to remove the 512k "RCT6" environments which allowed users to overflash 256k chips at the potential risk of lockups or other unexplainable (and potentially unsafe) scenarios.

Initial reports (https://github.com/MarlinFirmware/Marlin/pull/15890) were good, but long-term testing has shown these environments to not be stable for everyone.

**Edit:** Blackopsman_21 on Discord just pointed me to an [SKR Mini E3 V2 with a genuine RET6 chip](https://www.amazon.com/gp/product/B092JBHDYC), so I've added those environments as options for that board. That now makes the SKR Mini E3 DIP and E3 V2 boards that shipped with both RCT and RET chips.

### Benefits

- Safer firmware
- More consistent code/application of a "feature"

### Related Issues

Probably some in the queue that were related, though most of the headaches come from STM32F1/maple/timer conflicts.

### CODE REVIEW

**Comment by thinkyhead** [comment]
This seems like a fine idea to me. I'll look at ways to provide better guidance on this in Auto Build going forward.

**Comment by Taomyn** [comment]
So for those of us running successfully for well over a year with a v1.2 RCT and set at 512K, what are we supposed to do to get this back?

**Comment by thisiskeithb** [comment]
> So for those of us running successfully for well over a year with a v1.2 RCT and set at 512K, what are we supposed to do to get this back?

You can revert this PR or use an RE environment.

Try building in the new / non-`_maple` environments. You will have smaller builds and may be able to use the correct environment for your board without having to disable any features.

**Comment by rhapsodyv** [comment]
> So for those of us running successfully for well over a year with a v1.2 RCT and set at 512K, what are we supposed to do to get this back?

The RC env with 512kb is a misconception. If you have a RC chip that supports 512, you can use the RE env.

RE env is exactly the same as RC, but with 512kb flash.

**Comment by thinkyhead** [comment]
Indeed. The chip might be marked "RC" but inside there is actually an "RE."

**Comment by Taomyn** [comment]
In case anyone else comes looking, some instructions from a very helpful person https://github.com/MarlinFirmware/Marlin/issues/22140#issuecomment-861314980

**Comment by thisiskeithb** [comment]
> In case anyone else comes looking, some instructions from a very helpful person [#22140 (comment)](https://github.com/MarlinFirmware/Marlin/issues/22140#issuecomment-861314980)

Don’t do this. Just use an RE environment as those instructions will become out of date.

**Comment by Taomyn** [comment]
> > In case anyone else comes looking, some instructions from a very helpful person [#22140 (comment)](https://github.com/MarlinFirmware/Marlin/issues/22140#issuecomment-861314980)
> 
> Don’t do this. Just use an RE environment as those instructions will become out of date.

Well can you document how to do that because I gave it a go and it wouldn't appear, at least with the other person they explained the procedure.

**Comment by ellensp** [comment]
The current STM32F103RE_btt env also enables serial3 which is incompatible with this board.    PB10 and PB11 are used as ystep and yenable, enabling serial3 disables these pins.

**Comment by thisiskeithb** [comment]
> The current STM32F103RE_btt env also enables serial3 which is incompatible with this board. PB10 and PB11 are used as ystep and yenable, enabling serial3 disables these pins.

Which board? These environments cover a lot of BTT’s lineup.

**Comment by ellensp** [comment]
BOARD_BTT_SKR_MINI_E3_V1_2

**Comment by thisiskeithb** [comment]
Maybe @rhapsodyv has some thoughts on how to handle boards with non-functional serial options/options that break board features.

Maybe some kind of flag like `ALLOW_SERIAL_1/2/3` in the pins file?

**Comment by rhapsodyv** [comment]
If I remember right, in theory, as long we don’t directly use the serial object, there’s no issue in enabling it. That should not conflict with other peripheral.
But I never tested myself.
@ellensp did you test and found any issue?

**Comment by ellensp** [comment]
@rhapsodyv no. I lack the hardware to test it.  I noted several important  changes from STM32F103RC_btt to STM32F103RE_btt

Thers are all not in STM32F103RC_btt but are in STM32F103RE_btt
-DHAL_SD_MODULE_ENABLED 
-DSS_TIMER=4 
-DENABLE_HWSERIAL3 
-DTRANSFER_CLOCK_DIV=8

I would expect HAL_SD_MODULE_ENABLED and ENABLE_HWSERIAL3 to cause issues/pin conflicts

This needs testing.

**Comment by rhapsodyv** [comment]
HAL_SD_MODULE_ENABLED will only have any effect when calling a SDIO function. As long as sdio support keep disabled on marlin, no sdio code of the framework will be called, so no pin will conflict.

I kept it enabled exactly for that reason: now this env can be used with SD SPI and SDIO, with no issue.

This should be the same behavior with hw serial.

It’s very common setup (that I aware about it just recently): keeping common framework modules enabled to allow wider usage.

**Comment by Taomyn** [comment]
Is adding env:STM32F103RE_btt to the Mini E3 V1_2 entry in pins.h enough to test this out? I changed nothing else and kept the changes I did for getting the RC _btt_512 to compile.

I did it and it compiles, but I haven't tried flashing it to the board yet.

**Comment by rhapsodyv** [comment]
> Is adding env:STM32F103RE_btt to the Mini E3 V1_2 entry in pins.h enough to test this out? I changed nothing else and kept the changes I did for getting the RC _btt_512 to compile.

Yes.

I tested both RC (256) and RE (512) in my SKR MINI E3 V2 (RC).

**Comment by Taomyn** [comment]
Success, it flashed fine and started up as normal including my impossible NeoPixels :-P and started a small print as if nothing had changed.

Thanks all for the help.

**Comment by Floppy** [comment]
I was also running the 512K version happily on an SKR Mini E3 1.2. I can also confirm that adding `env:STM32F103RE_btt` to the include line as mentioned above works just fine. Thanks @Taomyn and @rhapsodyv for figuring this out. https://github.com/Floppy/Marlin/commit/768bae5ebd31f5d013af260cc9ce7bfe39352827

**Pull request merged**
