### PR TITLE
Env mega2560ext adds pins 70-85

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

A ATmega2560 based controller that uses pins > 70   (in this case it was a ULTIMAIN_2) 

### Description

Currently if you try and build marlin for some mega2560 based board, they use the standard mega2560 environment. 
But some of these boards use pins > 70 and the standard Arduino env: stops at pin 69.

### Benefits

Give the user a really easy way to use extended pins 70-85, by just updating the env: from mega2560 to mega2560extd

### Related Issues

Has been discussed on discord a few times. and issue #18517 is related.

### Future plans
Remove custom board definitions like reprap_rambo which just uses these extra pins and force ULTIMAIN_2 to use mega2560extd

### CODE REVIEW

**Comment by ellensp** [comment]
One possibility is we just upgrade env:mega2560 to what is currently env:mega2560extd so it is used in all boards...
I don't see a down side to this, but perhaps others can?

**Comment by grauerfuchs** [comment]
This basically exists in PlatformIO with their default inclusion of the MegaCore board definitions. To use it, all you need to do is edit the platformio.ini file and point the env as follows:
```
- board         = megaatmega2560
+ board         = ATMega2560
```

For an example, look at the MightyBoard envs. The MightyBoard uses the MegaCore variant PIO "board" definition, which addresses all of these additional pins and then some. Since this PR also requires PlatformIO and functions more or less the same way but with a few additional limitations, it looks to me like it would be only duplicating work already completed.

**Comment by ellensp** [comment]
ATMega2560 is part of megacore, but that changes other things also not just the pins...

**Comment by grauerfuchs** [comment]
All right. I just ran through what I could (quickly) break down in the PIO frameworks, libs, etc. that are included by each board definition. You're right; It looks like there are far more differences between included files than I had previously noted. Although it may have started off as bug-fixes and extensions to the then-common versions, the alternate core may by now have introduced more complications than solutions and only a detailed analysis could rule that out.

Since this PR looks like it will only alter the pins definitions in the project build tree and nothing else, it's a cleaner, simpler approach that will also aid in future troubleshooting. As for downsides to the requested change, I no longer see any.

**Comment by thinkyhead** [comment]
Marlin can already address extended pins on the Mega because we use FastIO. Is this change needed because we want to use extended pins with some Arduino libraries like Software Serial or SPI?

Instead of making a hard alteration to the framework in-place, it seems to me like it would be better to copy the board variant folder into the Marlin project and then make the needed changes there. Or, if possible, only override the one or two settings which change by some other method, such as making the modification between the reading of the board variant data and the use of the variant data, if that is possible.

**Pull request merged**
