### PR TITLE
Create pins_RAMP_14.h

### PR DESCRIPTION
**Pull request by marobol**
this configurate pin 19 for z end stop for delta printers with MKS 1.4 board.

### CODE REVIEW

**Comment by jbrazio** [comment]
Please submit your PR against `RCBugFix` branch.
We already have a `pins_RAMPS_14.h` file, please check your PR for conflicts.

**Comment by marobol** [comment]
Yes but the MKS 1.4 use pin 19 for z min or z end switch.

In Ramps use pin 32.

I write one solution posible in this code.

In this chek if the MKS board, if yes use pin 19 uf not use pin 32.

Best regadrs

Obtener Outlook para Android

On Tue, May 10, 2016 at 3:35 AM -0700, "João Brázio" notifications@github.com wrote:

Please submit your PR against `RCBugFix` branch.
We already have a `pins_RAMPS_14.h` file, please check your PR for conflicts.

---

**Comment by Blue-Marlin** [comment]
I really hate the idea of using the `Z_MAX_PIN` for the probe by default.
That blocks the safest option to use a z-probe - together with a z-max-endstop.

Having `Z_MIN_PROBE_PIN  32` on the RAMPS is also not the best idea because 32 is on AUX-4 what is usually blocked when a display is used. Some pin on AUX-1 (D0, D1, D57, D58) or AUX-2 (D63, D40, D42, D65, D59, D64 D44, D66) is much better accessible. For D1 and D57 (AUX-1) one could use the same connectors as on the 'normal' endstops.

**Comment by Blue-Marlin** [comment]
@marobol 
The right place for your change is `pins_MKS_13.h`

just add

```
#undef Z_MIN_PROBE_PIN
#define Z_MIN_PROBE_PIN ??
```

at the end of the file.

**Pull request closed without merging**
