### PR TITLE
RAMPS users cannot run a combined Cutter and 3D printer fix

### PR DESCRIPTION
**Pull request by descipher**
### Description

RAMPS users cannot run a combined Cutter and 3D printer when SPINDLE or LASER _FEATURE is defined.

### Requirements

RAMPS based pin config including boards like the MKS_GEN_L etc.

### Benefits

User can run the combination of features as desired.

### Configurations

#define BOARD_RAMPS_14_EFB
#define LASER_FEATURE 

### Related Issues

#23406

### CODE REVIEW

**Comment by hwmland** [comment]
I think it's still not fully OK, see my additional remark in the original issue

**Comment by thinkyhead** [comment]
A combined extruder/laser setup likely needs to use `LASER_SYNCHRONOUS_M106_M107` because there is no option currently to change tool modes (`M450` - `M453.9`). So, the right solution is to throw a compile error if `EXTRUDERS` is not zero when Spindle / Laser is enabled.

**Comment by descipher** [comment]
> A combined extruder/laser setup likely needs to use `LASER_SYNCHRONOUS_M106_M107` because there is no option currently to change tool modes (`M450` - `M453.9`). So, the right solution is to throw a compile error if `EXTRUDERS` is not zero when Spindle / Laser is enabled.

Please consider that I have a Laser + 3D printer which does not use M106 and so does #23406
so the LASER_FEATURE needs to be possible.

**Comment by thinkyhead** [comment]
I don't have any lasers to play with, and I have a big pile on my plate already, so don't be waiting on me to get the combination working in a full featured way.

**Comment by descipher** [comment]
Thanks, yes you have way too much load.

**Comment by descipher** [comment]
Checking into tool modes.

**Pull request merged**
