### PR TITLE
Fix stepper use before init. Add Ultimaker2+ Extended clone config

### PR DESCRIPTION
**Pull request by svpcom**
1. Fix stepper use before init. EEPROM read function try to control streppers before init (this results in extruder move during system boot).
2. Add support of hotend fan for Ultimainboard V2.0. It located on non-standard pin which is unaccessable from arduino lib.
3. Add sample configs for Ultimaker2+ Extended clone from AliExpress

### CODE REVIEW

**Comment by p3p** [comment]
Marlin has a method for accessing non Arduino pins, PJ6 is mapped as pin 77 .. at least that's what is in the fastio_1280.h file.

**Comment by svpcom** [comment]
https://www.arduino.cc/en/Hacking/PinMapping2560
PJ6 is not mapped on atmega2560

**Comment by p3p** [comment]
Marlin uses its own FastIO macros, not the Arduino functions, this file ([src/HAL/HAL_AVR/fastio_1280.h](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/HAL/HAL_AVR/fastio_1280.h)) maps the pin identifiers to the ports, and it looks like 77 is mapped to PJ6.

**Comment by svpcom** [comment]
PINJ6 is not defined anywhere in sources:
```cpp
/**
 * Pin mapping for the 1280 and 2560
 *
 *   Hardware Pin  : ... 69 ...
 *   Port          : ... J6 ...
 *   Logical Pin   : ... xx ...
 */
```

```
$ git grep PINJ6 upstream/bugfix-2.0.x
upstream/bugfix-2.0.x:src/HAL/HAL_AVR/fastio_1280.h:#define DIO77_PIN   PINJ6
upstream/bugfix-2.0.x:src/HAL/HAL_AVR/fastio_1280.h:#define PJ6_PIN     PINJ6
```

**Comment by p3p** [comment]
It's from the AVR headers. Just using pin 77 in the pins file should work.

**Comment by dot-bob** [comment]
This commit has breaks stepper initialization if your printer uses HAS_MOTOR_CURRENT_PWM.  Currents do not get updated upon boot.

**Comment by svpcom** [comment]
@dot-bob Why?
`` Stepper::init -> digipot_init -> digipot_current``

**Comment by dot-bob** [comment]
I just submitted a pull request that fixes the issue.

**Pull request merged**
