### PR TITLE
Clean up HAL trailing spaces, MKS SBASE pins

### PR DESCRIPTION
**Pull request by thinkyhead**
Followup to #7945, merged without application of standards.

- Replace tabs with spaces
- Remove trailing whitespace
- Remove forced settings of `SDCARD_SORT_ALPHA`
  (Add to a custom config if needed!)

Also:
- Clean up some other HAL spacing/formatting

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Can you generate a Pull Request to repair the 32-bit build?   If so...   I'll merge it ASAP !

Otherwise, I can revert #8077 but I would prefer not to do that.

**Comment by tcm0116** [comment]
@Roxy-3D the following commit from #8063 can be used for a PR: https://github.com/MarlinFirmware/Marlin/commit/1b6497a3a630cd93fdad268b1b196a925047a005

I'm not at a computer currently, otherwise I'd create a PR.

**Comment by Roxy-3D** [comment]
Can I just merge #8063 ???   Would that be OK ?  It looks like it is in an OK state to merge:

image

**Comment by p3p** [comment]
I can create a PR if you want, #8063 still needs fully reviewed and testing to make sure the sd card issue is localised to @Spawn32

**Comment by Roxy-3D** [comment]
OK...  I'll wait for a Pull Request to show up.    

Thank You p3p !!!!

**Comment by tcm0116** [comment]
#8063 should be good to go as @Spawn32 has been helping me with testing
while I've been away from my printers. However, I was hoping to get a
little more peer review from you, @p3p, and @thinkyhead before merging. If
you're comfortable with merging it, then by all means.

**Comment by Roxy-3D** [comment]
The SD issues are only on the 32-bit side of the fence, right?    Its not an AVR issue in general, right?

If that is true....   I'm comfortable merging to get rid of this other problem.

**Comment by p3p** [comment]
Well I wasn't comfortable with it, it was an invasive PR with new changes that were not reviewed or tested, Didn't even get 20 mins to make the PR and Travis takes 10! ^^

**Comment by Roxy-3D** [comment]
Sorry....   It seemed like you were out of pocket.     And I have to run out the door so I didn't want to leave things in a broken state.

**Comment by Spawn32** [comment]
testing it now, will report back...

**Comment by p3p** [comment]
@Roxy-3D No problem, we can just blame @tcm0116 if it breaks everything :wink:

**Comment by Spawn32** [comment]
compiles without errors, M43 works great, and the new pin numbering is just fantastic 😄 
but i stil dont have a working sd-card communication from windows trough usb..
i have a binary from 20.10, in that one the sd card works like it should, so something must have been merged after that date that broke it ?
should i just close https://github.com/MarlinFirmware/Marlin/issues/8099 and make a new issue for the sd-card, and dose the re-arm board now have the same sd problem ?

@apballard could you do a test compile now and se if the sd card is ok on the re-arm ?

Btw, great work @tcm0116  ;)

**Comment by p3p** [comment]
@Spawn32 After a quick test Re-ARM seems to be running ok, well it compiles (with SDCARD Sort disabled), booted and sd-card worked ect, I'l test more in a bit

**Comment by Spawn32** [comment]
"SDCARD Sort" ? did i miss something, did something change in the config and / or _adv files after 20.10 ?

**Comment by p3p** [comment]
It used to be overridden and enabled in the Re-ARM pins file to fix spi display corruption issues, but it should be in a example configs I guess, It's a Marlin feature though it doesn't effect the USB mass storage driver that's internal to the LPC1768 platform.

**Comment by Spawn32** [comment]
ah, ok.
i disabled #define SDSUPPORT just to test, same fault, windows wants to format the sd card, bla, bla, bla :) back to the 20.10 binary and all is well, strange :/

i sendt my config files to @tcm0116 so he can have a look in case i messed up :)

**Comment by Roxy-3D** [comment]
@Spawn32    Can you find the commit that breaks the SD-Card on your machine?   If you can load each version (from when it worked), it would be very helpful to know what exactly broke the SD-Card on your machine.

**Comment by Spawn32** [comment]
No problem, i can do that, but how do i then pull every version of the github ?

I have no ideer, using web version if that matters...

**Comment by Roxy-3D** [comment]
There maybe an easier way to do this.   But what I do is
- goto the Code tab and select the branch I'm interested in
- Right above the Branch name (left side of screen) is a link that will say something like **_8700 Commits_**
- Scroll down 1/2 from now until you know the code worked.   (do a binary search!  Don't check each and every commit)
- Click on the **_<>_** on the far right side of the commit.
- Download a .ZIP file of it and drop your Configuration.h files in the right place.  Compile, flash and test.

**Pull request merged**
