### PR TITLE
MKS UI: Monitoring state when idle 

### PR DESCRIPTION
**Pull request by leoric**
### Description

Add monitoring when idle: icons and labels for extruder temp, bed temp, fan speed. Move existing buttons down a bit.
Change labels when printing: "_current temp_ -> _target temp_", fan speed in percents
Add configuration option to swap OK and Cancel buttons, _SWAP_OK_CANCEL_, disabled by default

### Requirements

Designed on Flying Bear Ghost 5, no changes exceed the limits of its screen

### Benefits

Ability to monitor printer state when not printing

### CODE REVIEW

**Comment by thinkyhead** [comment]
Making it simple to swap the position of 'Confirm' and 'Cancel' buttons would seem to invite inconsistency from machine to machine. 'Confirm' and 'Cancel' buttons should have a standardized placement that we stick with. Almost universally, across most systems and dialogs, the Cancel option is positioned on the left.

**Comment by leoric** [comment]
> Making it simple to swap the position of 'Confirm' and 'Cancel' buttons would seem to invite inconsistency from machine to machine. 'Confirm' and 'Cancel' buttons should have a standardized placement that we stick with. Almost universally, across most systems and dialogs, the Cancel option is positioned on the left.

That's why I introduced those changes, they move Cancel button to the left:
https://imgur.com/a/HQtLjRI

**Comment by thinkyhead** [comment]
Yeah, I figured that had to be the reason. Perhaps we should just put it on the left by default and put in a _hidden_ option to put it back on the right, for those who _really_ want it.

**Comment by thinkyhead** [comment]
Good enhancement, and no point in further delay…. and I've got more MKS UI cleanup to push!

**Pull request merged**
