### PR TITLE
SKRmini: store EEPROM config in flash

### PR DESCRIPTION
**Pull request by tpruvot**
avoid confusion between the 2 possible SDs... and automount/load possible issues

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Could something like this be applied to the [SKR Pro (STM32F4)](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/stm32/pins_BIGTREE_SKR_PRO_V1.1.h) or is this only applicable to STM32F1-based boards?

**Comment by tpruvot** [comment]
i dont have it tell me :p
```cpp
#define BOARD_NAME "BIGTREE SKR Pro 1.1"

// Use one of these or SDCard-based Emulation will be used
//#define SRAM_EEPROM_EMULATION   // Use BackSRAM-based EEPROM emulation
//#define FLASH_EEPROM_EMULATION  // Use Flash-based EEPROM emulation
```

**Comment by thisiskeithb** [comment]
I don't have an SKR Pro/STM32F4-based board to test with 🙁

**Comment by thisiskeithb** [comment]
I posted a link to this PR in the "new" [SKR Pro group on Facebook](https://www.facebook.com/groups/357204398528031/permalink/357390108509460/) for others to test. Hopefully someone will report back.

**Comment by tpruvot** [comment]
the SKR Pro is not using the same framework... may be out of topic in this PR

**Comment by thisiskeithb** [comment]
Ahh. Bummer.

**Comment by hallphilip** [comment]
I have tested this and it is not placing anything on the SD card. M500 reports back "no eeprom".

**Pull request merged**
