### PR TITLE
Bump version number

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Bugfix and release 2.0.9.3 both have version 2.0.9.3, but bugfix and release config files are not compatible.

This is causing a lot of support headaches  

Please increase bugfix version number 

### Benefits

Less support requests for error: 'manual_feedrate_mm_s' was not declared in this scope

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/23904
https://github.com/MarlinFirmware/Marlin/issues/23656
https://github.com/MarlinFirmware/Marlin/issues/23712
https://github.com/MarlinFirmware/Marlin/issues/23671
https://github.com/MarlinFirmware/Configurations/issues/684

### CODE REVIEW

**Comment by ellensp** [comment]
Failed CI test are to be expected

**Comment by thisiskeithb** [comment]
Yes please!

**Comment by thinkyhead** [comment]
Note: the next tagged version might be 2.1.

**Comment by ellensp** [comment]
Even if so, It wouldn't hurt to bump the bugfix version up a little in the mean time.

**Pull request closed without merging**
