### PR TITLE
Set LCD contrast min max constraints on FYSETC_MINI_12864

### PR DESCRIPTION
**Pull request by descipher**
### Description

Previously contrast settings were initially set via LCD_CONTRAST_INIT, this was removed and are now initialized by settings however this results in a 0 value as there are no min max constraints for the FYSETC_MINI_12864 series and the default is only set on NVRAM default initialization.

### Requirements

Any FYSETC_MINI_12864 LCD

### Benefits

Visible display.
Other LCD's may need the same. However the min values are not known.

### Configurations

#define HAS_FYSETC_MINI_12864 1

#23528

### CODE REVIEW

**Comment by newbeetle** [comment]
I have just compiled and tested, the logo is more visible but the contrast is still less than the marlin logo.

**Comment by descipher** [comment]
The min is set to 120 we can bump it up. You should set it on the menu and save the settings.
Please indicate what you think the minimum should be.

**Comment by newbeetle** [comment]
When I load your last commit, the contrast in the menu is 255
I tried different values and the same values as (MKS_MINI_12864_V3, BTT_MINI_12864_V1) are the best because you have the contraste for the bootscreen as for the marlin bootlogo and the menu.

```
#elif ENABLED(FYSETC_MINI_12864)
  #define _LCD_CONTRAST_MIN  255
  #define _LCD_CONTRAST_INIT 255
  #define _LCD_CONTRAST_MAX  255
```
these are the values I will use for my next firmware.

**Comment by thinkyhead** [comment]
```
  #define _LCD_CONTRAST_MIN  255
  #define _LCD_CONTRAST_INIT 255
  #define _LCD_CONTRAST_MAX  255
```

When the min and max are the same, we should hide the edit menu, since it's pointless.

**Comment by thinkyhead** [comment]
@newbeetle — I've altered the code here to follow the same pattern as lcd brightness. Please check whether it does the right thing, both with and without `EEPROM_SETTINGS` enabled. It should work, but if not, we can also try adding a call to `ui.refresh_contrast` in `MarlinSettings::postprocess` to update the LCD at a slightly later point.

**Comment by newbeetle** [comment]
Contrast very low at bootscreen both with and without `EEPROM_SETTINGS` with last commit

Without `EEPROM_SETTINGS`, it is not possible to save anything modified with the menu, the options LOAD SETTINGS and SAVE SETTINGS are not present

**Comment by descipher** [comment]
Not sure whats up. It was fully tested and working on my commits.

**Comment by newbeetle** [comment]
[ 78863de](https://github.com/descipher/Marlin/tree/78863dede9aaac744cc2bcf122a592ffdda13b95) is not working on my printer
Contrast low

[c38a923](https://github.com/descipher/Marlin/tree/c38a92351f8895409b0dc2936d01740875935fb8) not more
Contrast always high even if modified in the menu

**Comment by descipher** [comment]
Too much unrelated change here now, I will leave it alone.

**Comment by newbeetle** [comment]
It works, Bootscreen and marlin screen are now dependant of screen crontrast value saved in EEPROM

**Comment by HeinzN** [comment]
Also everything fine now again on my Sidewinder, works flawlessly!

**Comment by thinkyhead** [comment]
Thanks for the confirmation. I went down a bit of a rabbit-hole with this to sort out some out of date assumptions. Maybe soon I'll also figure out what `HAS_DISPLAY` and `HAS_WIRED_LCD` now mean in the context of the newer display models.

**Pull request merged**
