### PR TITLE
Case light menu entry

### PR DESCRIPTION
**Pull request by Kaibob2**
Referenced to this #5194  (and this #5243 because i don't understand github) i implemented a (definable) Menu entry on the main screen to toggle the case lights. I had this long before the #define CASE_LIGHT_PIN 4 and always found it extremely useful to be able to switch off the case light from by LCD. The host is shut down most of the time, so if #define CASE_LIGHT_DEFAULT_ON is enabled there is no way to switch of the case light if the printer is printing for 20 hours.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Best when starting a new branch to `git fetch upstream` and make sure you're building off the latest `RCBugFix`. `git fetch upstream ; git checkout upstream/RCBugFix -b my_feature`… Otherwise the PR won't be compatible.

**Comment by Kaibob2** [comment]
@thinkyhead WHere do i have to enter this `git fetch upstream ; git checkout upstream/RCBugFix -b my_feature` stuff???

**Comment by thinkyhead** [comment]
You can always bring a branch up-to-date with `git fetch upstream ; git rebase upstream/RCBugFix`.

This all presumes you've made an `upstream` remote as an alias to `MarlinFirmware`.

```
git remote add upstream git@github.com:MarlinFirmware/Marlin.git
```

**Comment by thinkyhead** [comment]
> Where do i have to enter this git fetch upstream ; git checkout upstream/RCBugFix -b my_feature stuff???

Hmm. I forget that some proprietary OS's don't have a BASH. If using GNU tools on a frequent basis it's good to have a proper environment. In Windows it's a bit of work to add one.

**Comment by Kaibob2** [comment]
I'm on WIn10 64bit and do all editing online here at github.
For testing i use Aduino IDE

**Comment by thinkyhead** [comment]
You can do some of these things using the GitHub Desktop client.
Read the documentation provided for it, [somewhere on this site](https://help.github.com/desktop/).

**Comment by thinkyhead** [comment]
Ultimately all you really need is a `git` command in your CLI, and you can do all the fanciness.

**Comment by thinkyhead** [comment]
While Github Desktop doesn't provide detailed `rebase` it can do `merge`. The `sync` option is a combination of `git pull` and `git merge`. Merge will apply changes following your commits, while a rebase re-applies commits in a branch to a more recent root commit.

**Comment by Kaibob2** [comment]
Puh, sounds a liitle complicated, but i think i have to dig into this. Can my pull request be merged anyway?

**Comment by thinkyhead** [comment]
Without resolving conflicts, it cannot be merged.

**Comment by Kaibob2** [comment]
Damn, so close :)
Ok. I will just delete my whole repository and start with a fresh fork.
That's what i did yesterday and this worked. For the future i will check out Github desktop.

**Comment by Kaibob2** [comment]
I'll close here. Please have a look at #5255
Thanks for the fast support!

**Pull request closed without merging**
