### PR TITLE
PIO env for MKS Nano boards in STM32

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

This add nano env board for STM32.

### Benefits

A popular board using STM32.

### CODE REVIEW

**Comment by sjasonsmith** [comment]
Should we replace the maple environment, instead of adding a new one?

**Comment by rhapsodyv** [comment]
> Should we replace the maple environment, instead of adding a new one?

Add, for now. LVGL is used by a lot of nano users. The code for LVGL to work in STM32 is not ready yet.

But I have done:
 - Nano V2 to STM32
 - LVGL for STM32
 - F4 for STM32
 - Nano V3 for STM32
 - Full SPI/DMA class for STM32
 - Thumb driver support for STM32

But most of that devs are incomplete waiting for one thing or another. So I will start to send some parts, even if it will not be currently used by Marlin users, to avoid a big waiting forever PR....

**Comment by thinkyhead** [comment]
Good to see this migration slowly coming along, like a herd of majestic caribou…

**Comment by Malderin** [comment]
> ### Description
> This add nano env board for STM32.


Mks robin nano v2 board. 
My configs: https://github.com/MarlinFirmware/Marlin/files/5440936/Conf.zip
I tried to build the firmware with default_envs = mks_robin_nano35_stm32
Failure:
```
Marlin\src\HAL\STM32\timers.cpp:278:41: error: static assertion failed: One or more timer conflict detected
  278 | static_assert(verify_no_duplicate_timers(), "One or more timer conflict detected");
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
*** [.pioenvs\mks_robin_nano35_stm32\src\src\HAL\STM32\timers.cpp.o] Error 1
========================= [FAILED] Took 34.05 seconds =========================
```

**Comment by sjasonsmith** [comment]
Nice, my check worked!

I have caught myself on that timer conflict check a surprising number of times since I added it.

**Comment by sjasonsmith** [comment]
@Malderin you can get past the timer conflict by adding the following lines to `pins_MKS_ROBIN_NANO_V2.h`, but your configs hit quite a few more issues after that. I think this is great, it provides a good test for this board in the new HAL.

Probably place these below `BOARD_INFO_NAME` near the top of the file. I'm not positive if this is the best timer to choose, but I _think_ it will work.
```
#if defined(ARDUINO_ARCH_STM32) && !defined(STM32GENERIC)
  // Variant default conflicts with Servo timer
  #define TEMP_TIMER 5
#endif
```

@rhapsodyv could you take a look at these configs? The serial port number needs changed, but after that it hits some issues in the MKS UI and SPI code.

By the way, to debug those time conflicts, you can hover over the `timers_in_use` array in VS Code and see which indexes conflict in the popup.
image

**Comment by Malderin** [comment]
> Probably place these below `BOARD_INFO_NAME` near the top of the file. I'm not positive if this is the best timer to choose, but I _think_ it will work.
> 
> ```
> #if defined(ARDUINO_ARCH_STM32) && !defined(STM32GENERIC)
>   // Variant default conflicts with Servo timer
>   #define TEMP_TIMER 5
> #endif
> ```

**Comment by rhapsodyv** [comment]
You can't use `#define SERIAL_PORT_2 -1` in Nano V2.

**Comment by Malderin** [comment]
> You can't use `#define SERIAL_PORT_2 -1` in Nano V2.


I pointed it out like this:
#define SERIAL_PORT 3
//#define SERIAL_PORT_2 -1
In file pins_MKS_ROBIN_NANO_V2.h i indicated it like this (otherwise a timer error is thrown):
#if defined(ARDUINO_ARCH_STM32) && !defined(STM32GENERIC)
  // Variant default conflicts with Servo timer
  #define TEMP_TIMER 5
#endif

A new error appears:

```
Compiling .pioenvs\mks_robin_nano35_stm32\src\src\lcd\extui\lib\mks_ui\draw_wifi_settings.cpp.o
Marlin\src\lcd\extui\lib\mks_ui\draw_ui.cpp: In function 'void GUI_RefreshPage()':
Marlin\src\lcd\extui\lib\mks_ui\draw_ui.cpp:954:8: error: 'systick_uptime_millis' was not declared in this scope
  954 |   if ((systick_uptime_millis % 1000) == 0) temps_update_flag = true;
      |        ^~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs\mks_robin_nano35_stm32\src\src\lcd\extui\lib\mks_ui\draw_wifi_tips.cpp.o
Marlin\src\lcd\extui\lib\mks_ui\draw_ui.cpp:955:8: error: 'systick_uptime_millis' was not declared in this scope
  955 |   if ((systick_uptime_millis % 3000) == 0) printing_rate_update_flag = true;
      |        ^~~~~~~~~~~~~~~~~~~~~
*** [.pioenvs\mks_robin_nano35_stm32\src\src\lcd\extui\lib\mks_ui\draw_ui.cpp.o] Error 1
Compiling .pioenvs\mks_robin_nano35_stm32\src\src\lcd\extui\lib\mks_ui\gb2312_puhui16.cpp.o
========================= [FAILED] Took 82.57 seconds =========================
 
Environment             Status    Duration
----------------------  --------  ------------
mks_robin_nano35_stm32  FAILED    00:01:22.574
==================== 1 failed, 0 succeeded in 00:01:22.574 ====================
```

**Comment by rhapsodyv** [comment]
LVGL was not ported to STM32 yet. You can’t use that yet.
Try color ui.

**Comment by Malderin** [comment]
> LVGL was not ported to STM32 yet. You can’t use that yet.
> Try color ui.

ok. thanks!

**Pull request merged**
