### PR TITLE
UBL G29 -P3.1 smart fill

### PR DESCRIPTION
**Pull request by oldmcg**
UBL G29 -P3.1 smart fill using distance-weighted least squares fit from valid mesh points to extrapolate missing mesh points in single pass.

For delta print beds especially, many mesh points are not probeable or manually reachable, yet there must be mesh point values for at least first layer of mesh points beyond the printable radius in order for the bilinear interpolation to work correctly.

This adds ~2K progmem and no additional data for UBL and can be disabled by macro, but currently enabled by default for UBL on delta and cartesian since it could be useful for both.

Before accepting this PR please make sure it is against the correct bugfix-1.1.x marlin branch -- the github webui gives me no confidence that's where this is headed.  Thx.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
> Before accepting this PR please make sure it is against the correct bugfix-1.1.x marlin branch -- the github webui gives me no confidence that's where this is headed. Thx.

I'll review it in the morning.   But at least this part won't bite us again!   :)   The decimal sub-parameters make a lot of sense.  Probably the code that does that will ultimately end up in https://github.com/MarlinFirmware/Marlin/pull/6634

> For delta print beds especially, many mesh points are not probeable or manually reachable, yet there must be mesh point values for at least first layer of mesh points beyond the printable radius in order for the bilinear interpolation to work correctly.

Yes...   And a Delta P3 that extends out the values a little past DELTA_PRINTABLE_RADIUS makes a lot of sense.   But we still need to move the nozzle as close as possible and edit the surrounding (out of DELTA_PRINTABLE_RADIUS) point.  I changed the G29 P4 mesh edit to be able to edit NAN's today.  I think if we define a new type for find_closest_point_of_type() that includes locations within 1 mesh line of the DELTA_PRINTABLE_RADIUS we are going to have a very nice solution for the user.

**Comment by oldmcg** [comment]
At the moment P3.1 fills all the nan entries in one pass, but it has to recompute the LSF for each nan point separately because the distance weights are all different.  By doing all in single pass, it first creates bitmap (32 bytes on the stack) of all the originally-valid mesh points so that all the extrapolated mesh points are only extrapolated from originally-valid points.  In other words, it doesnt extrapolate from an extrapolated point.

It would not be difficult to change this code to compute WLSF for single mesh point per call, then called for each find_closest nan from origin, but by doing these one at a time, previously extrapolated points will become input for extrapolating additional points.  Maybe that is ok -- I just thought it best to only extrapolate from known good locations.  If we want to keep track of which points are original vs which points are extrapolated to avoid using those for further extrapolation while building a complete mesh, we'd need to keep the 32-byte original-vs-extrapolated bitmap in static data.

**Comment by oldmcg** [comment]
I now have an alternate version of this that fills single point at a time (could also call for single point) from center outward.  But this alternate version doesn't track original vs extrapolated points, so outermost  points are extrapolated from other extrapolated values.  The overall resulting values still look "reasonable", and for a plain P3.1 with zero nearest neighbor weighting it will produce the same answer because all the extrapolated points are on the same plane.  Let me know if you'd prefer this approach and I will push to this PR.

**Comment by Roxy-3D** [comment]
It would seem what you did for the weighted LSF fill should work for the non-Delta case too, right?

We probably should move slow...  But it probably makes sense in a week or two to switch the Cartesian machines over to the more sophisticated code once it is shaken out....

**Comment by oldmcg** [comment]
We talked about bed edges curving up or down on square glass -- this won't project any curvature, just treats the whole bed as an average tilted plane, but with optionally much greater weight given to points nearest the point being extrapolated.   The result is still fairly flat following average tilt.

At least for delta it seems to work much better than existing G29 -P3 which produces some extreme corner values when iterated enough times to fill the whole mesh.  How it will work for cartesian beds I can't say but I recommend trying it compared to -P3, probably with very high nearest weighting like -P3.19 (10^9th weighting).  

If I were better at math I'd try parabolic vs planar fitting.

Here is my delta bed tilted by about 0.6mm using iterative G29 -P3 to fill all the holes...
image

And here is same bed using G29 -P3.13...
image

**Comment by Roxy-3D** [comment]
OK...   That is helpful!

**Pull request merged**
