### PR TITLE
Allow custom version file and information to be set POST configuration.h

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Move inclusion of Version.h after configuration.h
Add ifndef around all version strings
Add option to include custom version file
Move strings in configuration.h that relied on Version.h to configuration_adv behind additional HAS_SPI_LCD check

This will allow version information to be generated by vendors based on options selected in the configuration file. This means version data shown on the graphical lcd can be used to confirm particular machine options easily.

Though it seems platformio will not allow me to change the Due c++ revision to support __has_include, I still used it on platforms where we could as an extra check.

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
The ifndef on __has_include is the standard compliant method of determining if we have a new enough version of GCC to use it. Even if the platform is not using c++17 yet, it allows it to have the extra safety on anything that does now or in the future.

**Comment by thinkyhead** [comment]
> The ifndef on __has_include is the standard compliant method

Ah, so it is…

**Comment by thinkyhead** [comment]
So let's see… With this we still have the version generator script which will create a "primary" version file (now just used in Travis testing). And then we've got the ability to also set any version value from the `Makefile`. Version values should also work if set from the configuration files. So, a check for the presence of the "primary" version file would be a fine addition. Then later, as everything is certain to have `__has_include` the placeholder "primary" version file can be removed as obsolete!

**Comment by InsanityAutomation** [comment]
Ok, rebased, set custom file to default to all options disabled so nothing is overridden, removed the parameters that shouldnt really be user controlled such as minimum version number from the user version.h, and hopefully travis doesnt yell about hexify anymore...

**Comment by InsanityAutomation** [comment]
Ok, I think we're finally good with Travis, found the last snippets left making it fail. Should be ready for you @thinkyhead

**Comment by InsanityAutomation** [comment]
Ok, travis is happy and I think this covers what you needed now @marcio-ao lmk if theres anything else or if you want any other tweaks

**Comment by InsanityAutomation** [comment]
@thinkyhead Rebased and a couple new configs patched. Hopefully this can get merged before I need to touch another 188 files....

**Comment by thinkyhead** [comment]
I squashed everything down to a single commit with `git reset upstream/bugfix-2.0.x`. So…
```
git fetch origin
git checkout MoveVersion.h
git reset --hard origin/MoveVersion.h
```

**Pull request merged**
