### PR TITLE
[2.0.x] Anycubic LinearPlus, Trigorilla 1.4

### PR DESCRIPTION
**Pull request by thinkyhead**
Changes from #11356 @grbd

- Add configs for LinearPlus delta.
- Mods for Trigorilla 1.4

### CODE REVIEW

**Comment by thinkyhead** [comment]
Perhaps @anycubic-3d would like to review this…?

**Comment by brandstaetter** [comment]
we should check the diffs with my #11725 and check if we can unify them more

**Comment by thinkyhead** [comment]
Is the AnyCubic LinearPlus the same as the "Kossel"?

To compare configs, I usually just drop the ones I want to compare onto the configs open in Github Desktop and then the diffs are all highlighted and ready to cherry-pick line by line.

**Comment by brandstaetter** [comment]
Yes, the full name should be Anycubic Kossel Linear Plus - it's the bigger brother of the normal Anycubic Kossel.

I did some initial comparing of the 2 configs, and it looks like I activated way more features on my version (Autocalibration, other convenience things...) - I'll work on unifying the configs and will provide an updated pull request for Anycubic Kossel and Anycubic Kossel Linear Plus so I vote against merging our 2 pull requests for now

**Comment by thinkyhead** [comment]
You can just add commits to your PR's branch to update it. I posted instructions there.

And, you can submit any changes to this PR by
- checking out my [bf2_linearplus_and_trigorilla](https://github.com/thinkyhead/Marlin/tree/bf2_linearplus_and_trigorilla) branch
- adding commits to your working copy
- publishing those changes to your fork (i.e., `origin`), and
- submitting a PR from your copy of `bf2_linearplus_and_trigorilla` to the `bf2_linearplus_and_trigorilla` branch in my fork.

When I merge your PR to `bf2_linearplus_and_trigorilla` it will cause this PR to also be updated.

**Comment by brandstaetter** [comment]
please discard in favour of #11752

**Comment by thinkyhead** [comment]
I brought your changes into this PR instead. I also combined the V1 / V2 configs to cut the number of configs in half.

**Comment by brandstaetter** [comment]
Thanks - although I work with git daily, github does some things differently than we do, so I was confused.

I'll add another sample config soon (as soon as I've tested it) for the version without heated bed and without autolevel.

Who could support me with issue #11337 because it makes this firmware a bit dangerous for the unaware (can break the z-probe)?

**Comment by Palatis** [comment]
I think the pins are correct for E1 except E1_CS_PIN (which is used for FAN2_PIN)

https://github.com/ANYCUBIC-3D/I3-MEGA/blob/master/Marlin_TFT_CR_V1.1.1/pins_RAMPS.h#L73

however I prefer something like
```
#if defined(E1_CS_PIN) && defined(FAN2_PIN) && (E1_CS_PIN == FAN2_PIN)
  #warning E1_CS_PIN and FAN2_PIN are the same
#endif
```
so it don't `#undef` my CS defs in `configuration_adv.h`...

**Comment by brandstaetter** [comment]
@Palatis can you provide a pull request for this change?

**Comment by Palatis** [comment]
> 
> 
> @Palatis can you provide a pull request for this change?

please take a look at https://github.com/MarlinFirmware/Marlin/pull/11869 :-D

**Pull request merged**
