### PR TITLE
Poll *all* enabled endstop pins

### PR DESCRIPTION
**Pull request by kpter**
It's solving my problem  #13926 

### Description
Problem was:  "Z-MIN - not stopping if move to it" if -
 - Z-MAX endstop enable and
 - Z-probe not use Z-MIN endstop and
 - Z_HOME_DIR 1 (homing to Z-MAX endstop).

### Benefits
I use it fix long time, can you add it in source code?

### Related Issues

Similar issue #12841

### CODE REVIEW

**Comment by thinkyhead** [comment]
I see where you're going. But… When homing to `Z_MAX`, then we should not expect the code to trigger the `Z_MIN` bit. Let's instead look at the case related to homing to `Z_MAX` and make sure it is correct.

**Comment by thinkyhead** [comment]
~~I suspect that you have failed to enable this:~~
```cpp
#define USE_ZMAX_PLUG
```

**Comment by thinkyhead** [comment]
Hmmm… actually I see the Sanity check would have caught that. Let me see if I can download your configs from the other issue and track down the correct solution.

**Comment by kpter** [comment]
>  Let me see if I can download your configs from the other issue and track down the correct solution.

Attached, includes configs and diffs.
[last_configs.zip](https://github.com/MarlinFirmware/Marlin/files/3723225/last_configs.zip)

**Comment by thinkyhead** [comment]
~~Ok. Just to make sure I comprehend the issue….~~
- ~~We use the probe for Z homing whenever there is a probe and there is _**no**_ Z min endstop~~
- ~~BUT: We should _**not**_ be using the probe for homing when there _**is**_ a Z max endstop~~
- ~~_**Something**_ about this combination is causing the Z MAX endstop to not get checked~~
- ~~We need to make sure Z MAX endstop is being checked when homing to Z MAX~~

**Comment by thinkyhead** [comment]
Ok, so on re-re-reading your description, it now seems that what you want is to have a Z min endstop that is functional for the ABORT feature, but otherwise it is not used. That is an interesting case.

**Comment by thinkyhead** [comment]
…and, under that kind of setup your patch seems fine.

**Comment by tesla128** [comment]
Is this supposed to be fixed in the Marlin 2.0.x?  I am currently having this exact same issue while building a CNC and came to the same conclusion that there is a problem with how HAS_Z_MAX and HAS_Z_MIN are being evaluated. Dual z axis with dual endstops does not stop when Z_HOME_DIR is +1, but works fine if Z_HOME_DIR is -1.  

With the CNC, you want to be able to home it at the top before even touching X and Y to prevent tool crashing and then re-zero to the work surface using the tool (of possibly different length every tool-change) as the probe.

My ideas to temporarily fix it were similar (force the definitions), but I thought I'd google it first to make sure I wasn't just missing something simple like an improper conflicting configuration

To clarify:  USE_ZMIN_PLUG is enabled because that input is being used for a maximum Z height limit switch on one of TWO Z axis.  It appears to be a naming issue, but feels like it could go deeper.  It's not a MIN, but the defines don't really offer Z2_MAX in the configuration.

edit:

If configuration_adv.h has Z2_USE_ENDSTOP _ZMAX_
then
Under conditionals_post.h
#if _HAS_STOP(Z,MIN) evaluates to true, but no clear way to change that.  The pin exists but is being used for a MAX not a MIN purpose
#if _HAS_STOP(Z,MAX) evaluates to false, possibly because it IS_Z2_ENDSTOP

If configuration_adv.h has Z2_USE_ENDSTOP _ZMIN_
then
HAS_Z_MIN and HAS_Z2_MIN evaluate to false as desired and HAS_Z_MAX and HAS_Z2_MAX evaluate to true as desired
but
both Z axis still continue to move after either or both end-stops are triggered
M119 now only responds to the ZMIN switch and reports it for both z_min and z2_max - the fact that z_min exists on the console not z_max is a clue

I'm still sure it's something simple I'm doing wrong, but judging by the number of google results going back years with the same issue, I think this could be dummy-proofed or at-least commented to help them(us) out.

**Comment by kpter** [comment]
> 
> I'm still sure it's something simple I'm doing wrong, but judging by the number of google results going back years with the same issue, I think this could be dummy-proofed or at-least commented to help them(us) out.

I have only one Zmin and one Zmax endstops, and it works fine (Marlin-2.0.7.2).
Maybe, it helps you, check this:
find endstops.cpp, and find  this part of code
```
    else { // Z +direction. Gantry up, bed down.
      #if HAS_Z_MAX || (Z_SPI_SENSORLESS && Z_HOME_DIR > 0)
        #if ENABLED(Z_MULTI_ENDSTOPS)
          PROCESS_ENDSTOP_Z(MAX);
```
then, add to this line:
```
      #if HAS_Z_MAX || (Z_SPI_SENSORLESS && Z_HOME_DIR > 0)
```
this compare ( || HAS_Z2_MAX), and in result this code will be:
```
    else { // Z +direction. Gantry up, bed down.
      #if HAS_Z_MAX || HAS_Z2_MAX || (Z_SPI_SENSORLESS && Z_HOME_DIR > 0)
        #if ENABLED(Z_MULTI_ENDSTOPS)
          PROCESS_ENDSTOP_Z(MAX);
```

**Pull request merged**
