### PR TITLE
[2.0.x] DUE: Several fixes to the backtracker

### PR DESCRIPTION
**Pull request by ejtagle**
Several fixes to the backtracker. Now when a crash is detected, it is able to properly print the traceback, even if no -funwind-tables flag is present.

I discovered that the backtracker was aborting without trying to follow the call stack. This is now fixed. 
Also, i added a basic backtracker that does not depend on the unwind tables. Not as reliable, but seems to work

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Definitely an improvement!

Only the ISR info is available when the WDT occurs during an ISR.  Can you (if it's reasonable) backtrace from where the ISR interrupted?

For a while I was hoping that name demangling could also be done but then I realized the needed info was in the ELF file, not the FLASH image.  We'd only need 2-4MB of FLASH for that. 😉

**Comment by Bob-the-Kuhn** [comment]
I'm starting to wonder what it would take to port this to the LPC1768 or the STM32.

Could you do me a favor and put together a top level design view of how it's done on the DUE? 

I know some of the info.
a) Setup WDT so that it generates an interrupt rather than a reset vector
b) Interrupts can't be used so use serial port 0 in a polling mode to send the info out.  
c) No buffering is needed because the host USB link is still up because the 16U2 chip hasn't been reset.
d) Use the reset controller to send the chip through a normal reset.

A big problem for the LPC1768 is finding a way to get the traceback info out.  It normally uses only it's USB controller for outside communication.  Once interrups are disabled then the USB stack is down and the host link goes down.  Some possibilities that come to mind:
1. Send it out a standard UART port.  This would require a second cable and a second terminal to receive the data.
2. Write the data to the LCD's SD card.  That code doesn't use interrupts.  The Marlin startup code could then check if it exists and send it out the USB port.
3. Find some RAM that isn't cleared on reset and buffer the info there.  I don't know if such a place exists.

**Comment by Roxy-3D** [comment]
> Find some RAM that isn't cleared on reset and buffer the info there. I don't know if such a place exists.

We can make a place...   We just declare less RAM memory than is really available and store the information there.    And any time the processor resets...   It dumps that area (and then clears it).

But it would seem to me it would be easier to just turn off all interrupts, and send the information out the serial port in a polled fashion.   The firmware is so sick you can't continue anyway.  Turning off interrupts and polling the Tx side of the UART to send the information probably wouldn't be too hard.

**Comment by Bob-the-Kuhn** [comment]
I use a BAT file to grab the ELF & feed it to the arm-none-eabi-addr2line utility.  It then start pasting in the PCs from the traceback and it  nicely spits out human friendly source code line numbers and file names (with path).

I was just dreaming of having the DUE do that but came to realize that's not possible.

**Comment by Bob-the-Kuhn** [comment]
> send the information out the serial port in a polled fashion

That's exactly how it's done on the DUE.

On the LPC1768 we normally don't have a UART attached.  In debugging mode attaching another cable to the controller is a possibility.

I like the "reserve a section of RAM" idea for the LPC1768.  We'd need 1K bytes for this.  That would give us more than 15 levels.  512K would get us 2 or 3 levels.

**Comment by ejtagle** [comment]
Essentially, the code can be used as-is on all ARM Cortex M0/M3/M4. The backtracer itself is completely generic. The file DebugMonitor_DUE.cpp is also mostly usable on the LPC. The only bits that are needed to be touched are the TX* functions (that do the serial output without using interrupts, by polling. And also, the validate_addr() function must be adapted so it validates a given address is valid for the given target.
So, porting to LPC could probably take 10 minutes most... ;)

**Comment by ejtagle** [comment]
Regarding what is possible, and what it is not:
1) ISR tracing should work (and it works for me), but, if you are not compiling with -funwind-tables, and you are testing the code with a while(1) {}, the backtracer defaults to "simulate execution", so it interprets the ARM Thumb code and follows execution tracing returns to the previous function,
The problem is that if you use a while(1) {}, GCC realizes the function will never return and does not generate the remaining of the function code !... So the tracer is unable to backtrace.
You should try testing with the following code:
volatile bool loopForever = true; // << Declare it outside of function, to make it global
while (loopForever) {} // << This inside the function. GCC can´t assume the value, so it will generate the rest of the code, and you will see the backtrace.

If you compile with -funwind-tables, then there will be no simulation, and backtrace only depends on those tables

2) If you compile with -mpoke-function-name, then you will get the mangled function names with the traceback. Without that flag, you just get the PCs of the traceback. - Name unmangling CAN be done if needed (it is just a set of fixed rules) if names are present.

3) As said, porting to LPC or the STM is mostly trivial. 

4) Outputting to Serial, LCD or to a RAM buffer is possible. Serial is easiest, LCD a bit more complex (no interrupts, we don´t know the state of the rest of the runtime, so a minimalistic lcd output routine should be written). RAM buffer is another possibility, and then that buffer could be dumped at startup... Writing to EEPROM or SD is also possible. But i prefer to keep things as simple as possible here. 

5) Your top level design view is correct. The backtracer uses either the unwind tables (official format as specified by ARM) or a "virtual execution simulator", so it should work on all ARM Cortex devices. We only depend on watchdog to detect locks, but invalid accesses, null pointers, etc, use default exception handlers present on all ARM variants

6) Yes, such enhanced traceback as you can get from addr2line is not possible without debugging information. The most we can get are function names and PC values.

**Comment by Bob-the-Kuhn** [comment]
I've been doing some playing with this code trying to understand a TMC2130 problem. 

I think it'll be useful to modify the kill() function so that we can get a WDT interrupt.  The wait forever loop has to be before the cli() function or the WDT interrupt will be disabled.

```
#if !defined(__AVR__) && defined(WATCHDOG_RESET_MANUAL)
  while(1){};  // traceback function enabled - cause WDT timeout so debug info will be generated
#endif
cli(); // Stop interrupts
```

I'm going to merge the PR as is and then do a separate PR for the kill() mod.  There may be other ideas on how/where to do the mod.

**Pull request merged**
