### PR TITLE
STM32F1: Support M997 - Reset and begin flash

### PR DESCRIPTION
**Pull request by reloxx13**
sorry, had some rebase problems :(, but got it fixed now and learned sth 👍 
rebased to get travis build success.   

### Description
Adds M997 gcode command to the stm32f1 platform to support a fw reset and triggering a flash from sd card by bootloader.

Tested and works on my SKR mini E3.

### Benefits
Remotly Firmware flashing by USB like LPC Style:   
- Mount Printer SD Card
- Copy firmware.bin on mounted card
- Trigger a reset by M997

### Related
https://github.com/MarlinFirmware/Marlin/pull/13281
https://github.com/MarlinFirmware/Marlin/issues/11128
https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/issues/103
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3-/issues/14

### CODE REVIEW

**Comment by thisiskeithb** [comment]
It'll be nice to flash the SKR Mini boards just as easily as the SKR 1.3.

**Comment by JohnnyTheOne** [comment]
What about the PRO is it possible?

**Comment by AnHardt** [comment]
> ... PRO ... ?

The code for the reset should work when put into the right HAL.
But up to now there is no way to put the firmware onto the onboard SD remotely.

**Comment by Rmkiv4** [comment]
How do you upload firmware.bin. Using Octoprint firmware updater? What kind of update method do yo use?

**Comment by Rmkiv4** [comment]
How do you upload firmware.bin. Using Octoprint firmware updater? What kind of update method do yo use?

**Comment by reloxx13** [comment]
@Rmkiv4 
see here pls: https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/issues/103#issuecomment-569449404

**Pull request merged**
