### PR TITLE
[2.0.x] General code clean/comment

### PR DESCRIPTION
**Pull request by thinkyhead**
Some cleanup / clarification / comments.

Formerly a PR about a de-bouncer.

### CODE REVIEW

**Comment by AnHardt** [comment]
> (Endstops don't need a de-bouncer because they only need to detect the initial trigger.)

???
( Even endstops need a de-bouncer - currently they need to be triggered in two consecutive steps.)

**Comment by thinkyhead** [comment]
> triggered in two consecutive steps

Are you referring to…?

### The initial fast homing movement gets the axes to the endstops as quickly as possible. The second homing movement (re-bump) gives a more accurate position to establish "home."

The endstops are latched as soon as their state changes. After that we don't wait for them to "settle" with a de-bouncing routine. A "threshold" de-bouncer like this one is only needed when you want to establish the steady state of a button that is being evaluated continuously at a high rate.

Anyway, per my comments in #8509, I'm skeptical whether this de-bouncer will help, because double-trigger already seems like it should be rare under the existing scheme.

**Comment by AnHardt** [comment]
Ah - you removed the cited line. Well done.

No i am referring to `old_endstop_bits` and its usage. Most of all in:
```cpp
// TEST_ENDSTOP: test the old and the current status of an endstop
#define TEST_ENDSTOP(ENDSTOP) (TEST(current_endstop_bits & old_endstop_bits, ENDSTOP))
```

I admit, its not easy to find the actual code in all this distributed macros - but that's not my fault.

Because of:
https://github.com/MarlinFirmware/Marlin/blame/f6f881f5ed954bc2f44ca64895b6af99e74265a2/Marlin/temperature.cpp#L2120-L2129
its not 'two consecutive steps' anymore - but 'two consecutive tests' - in some cases.

**Comment by AnHardt** [comment]
We already have two buttons working with a `Threshold-based button debounder`
```cpp
  #if HAS_KILL

    // Check if the kill button was pressed and wait just in case it was an accidental
    // key kill key press
    // -------------------------------------------------------------------------------
    static int killCount = 0;   // make the inactivity button a bit less responsive
    const int KILL_DELAY = 750;
    if (!READ(KILL_PIN))
      killCount++;
    else if (killCount > 0)
      killCount--;

    // Exceeded threshold and we can confirm that it was not accidental
    // KILL the machine
    // ----------------------------------------------------------------
    if (killCount >= KILL_DELAY) {
      SERIAL_ERROR_START();
      SERIAL_ERRORLNPGM(MSG_KILL_BUTTON);
      kill(PSTR(MSG_KILLED));
    }
  #endif

  #if HAS_HOME
    // Check to see if we have to home, use poor man's debouncer
    // ---------------------------------------------------------
    static int homeDebounceCount = 0;   // poor man's debouncing count
    const int HOME_DEBOUNCE_DELAY = 2500;
    if (!IS_SD_PRINTING && !READ(HOME_PIN)) {
      if (!homeDebounceCount) {
        enqueue_and_echo_commands_P(PSTR("G28"));
        LCD_MESSAGEPGM(MSG_AUTO_HOME);
      }
      if (homeDebounceCount < HOME_DEBOUNCE_DELAY)
        homeDebounceCount++;
      else
        homeDebounceCount = 0;
    }
  #endif
```
For me this is not working very good. The frequency `manage_inactivity()` is executed depends a bit on the workload. So the time you have to press kill varies strongly. I guess with a timer based concept the experience would be better.

**Comment by thinkyhead** [comment]
I agree. If the frequency of the function call is low then a false signal is very rare. A timer-based solution where it requires ~4ms since the last read should work fine. That's why I threw away my previous debounder.

**Pull request merged**
