### PR TITLE
Prune unmaintained languages

### PR DESCRIPTION
**Pull request by jbrazio**
Removes unmaintained Spanish language variations:
- Aragonese (`language_an.h`)
- Basque-Euskera (`language_eu.h`)
- Catalan (`language_ca.h`)
- Galician (`language_gl.h`)

For now we still keep unmaintained:
- Bulgarian (#3348)
- Finnish (#3355) 
- Polish (#3360)

Closes: #3357, #3354, #3349, #3347

This PR has the side effect of move `example_configurations/Felix/Configuration_DUAL.h` into its own `DUAL` folder and renaming it to `Configuration.h`. This is so the config file can be catched when doing mass edits based on `find . -name Configuration.h | xargs <something>`.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Aww… I love being able to tell people Marlin supports "dozens" of languages.
Now I'll be an even _bigger_ liar! 😄

**Comment by jbrazio** [comment]
Well these are non mainstream languages..
(I'm trying to see where they are hidden so we can convince them to update the language files :-)

**Comment by thinkyhead** [comment]
@jbrazio It probably will happen that after 1.1.0 release, the language maintainers will appear with patches. But maybe not before. Have you messaged the individuals who made the most recent commits to these languages already?

**Comment by jbrazio** [comment]
Good idea, I will ping them.

**Comment by jbrazio** [comment]
@thinkyhead All of them have been pinged, if no reply within a week this PR should be merged.

**Comment by jbrazio** [comment]
@thinkyhead All of them have been pinged, if no reply within a week this PR should be merged.
All of the languages on this PR had the first commit and no more updates on the native language, all the following updates on the blame history were English additions.

**Comment by rafacouto** [comment]
Galician syncronized at the moment. Thank you for pinging to me :+1:

**Comment by jbrazio** [comment]
Thank you for your contribution @rafacouto !

**Comment by CONSULitAS** [comment]
@jbrazio 
@rafacouto 
We have discussed the idea of language care takers before.

Should we add a header to maintained translations with the care taker(s) like in https://github.com/MarlinFirmware/Marlin/blob/RC/Marlin/example_configurations/K8200/Configuration.h#L23 ?

So it would be easier to find natives for the next update...

**Comment by jbrazio** [comment]
I like the idea, but how about using github teams ?
This way we could ping them with the "@" thing.

**Comment by jbrazio** [comment]
I like the idea, but how about using github teams ?
This way we could ping them with the "@" thing.

```
@MarlinFirmware/lang-en
@MarlinFirmware/lang-pt
@MarlinFirmware/lang-de
etc
```

Or have a unique `@MarlinFirmware/localization-team` with all the lang people inside, usually it's more than one lang file that needs updating.

@Roxy-3DPrintBoard

**Comment by Blue-Marlin** [comment]
In my opinion the unmaintained languages should be kept in.
For German i know there are dozens of 'personal' translations out there. The hurdles are not, to change some translations for your self but to judge is they are acceptable for a bigger audience and to do the PR with github. Removing the examples for the languages would make the hurdle for these 'personal' translation much higher.

**Comment by rafacouto** [comment]
I am going to give it a try to this script: https://github.com/nevik/gitwatch

Another option could be a [webhook](https://developer.github.com/webhooks/) to watch changes on the main language file and send an email to the maintainers declared in the header of the language files (@CONSULitAS ' idea).

**Comment by jbrazio** [comment]
Closing due the creation of @MarlinFirmware/language-team.
Still some languages are problematic and lack maintainers.

**Pull request closed without merging**
