### PR TITLE
Made Arduino DUE port compile and work again

### PR DESCRIPTION
**Pull request by ejtagle**
### Description

I am updating my printer with the latest changes, and found out the Arduino Due port was not compiling due to changes in the DELAY_*() macros. So, this pull request represents the bare minimum to make 2.1.x work on Due

### Requirements

Arduino Due with RAMPS2DUE board

### Benefits

Due target compiles with the Arduino Due environment

### Configurations

I am using the MakerParts configuration, exactly as found in the Config repo

### CODE REVIEW

**Review by ellensp — COMMENTED** [review]
```static void adc_enable(const uint8_t) {}```
This isn't very nice,,,

**Comment by ellensp** [comment]
apart from a few warning It compiles fine as was on platformio using MakerParts Configuration files.

**Comment by ejtagle** [comment]
@ellensp : First, thanks for your prompt review! :) 💯 

> `static void adc_enable(const uint8_t) {}` This isn't correct... You need a variable name

I know not having a variable name does not "feel" right, but, it is the easiest way to remove the "unused argument" warning that this otherwise would produce, and in fact, IS very standards compliant. C++11 N3337 standard, section 8.4.1/6 "Function definitions > In general" (https://stackoverflow.com/questions/2319663/why-does-c-code-missing-a-formal-argument-name-in-a-function-definition-compil)

Alternatively, I could write 

`
static void adc_enable(const uint8_t /*ch*/) {}
`

(Did I mention that I HATE not needed warnings, as they tend to mask actual bugs? ;) )

The problem with the Arduino IDE is that the DUE compiler is pretty old, has problems with constness, and that is why I had to do this patch. And I still have some issues with the resulting firmware, such as lockups when trying to access the SD from the PC -- It used to work because I was the one that contributed the USB code and the Makerparts target.

Sorry for my long rant, thanks for your review, let's keep going, and find a proper way to fix warnings and make the DUE port work again as it was originally doing! :D

**Comment by EvilGremlin** [comment]
there is `UNUSED` macro made specifically to shut up compiler

**Comment by thisiskeithb** [comment]
> The problem with the Arduino IDE

While compiling Marlin in Arduino IDE isn’t deprecated, we highly recommend everyone move to VSCode with PlatformIO.

**Comment by ejtagle** [comment]
@EvilGremlin : Don´t be so evil! 🥇 

> there is `UNUSED` macro made specifically to shut up compiler

That is a good point!... 💯 ,  But you should admit that it could be better if trying to avoid bugs the removal of the argument name. There is a rationale behind this:
Let´s assume we add the ´UNUSED(ch);´ at the start of an empty function and, later in time, a developer decides to implement it: 
>If the macro is still there, it is too easy to not take into account the parameter value in the implementation, and ignore it - The UNUSED macro gives the idea of "unimportant/meaningless/deprecated argument"
>If we comment out the parameter name, then the developer will NEED to follow the code to understand what is exactly passed as argument value when the function is called, forcing him/her to take the value into consideration, or at least be fully aware of the implications of not taking into account its value.
I know, i know, a subtle difference! ;)

To be honest, i am OK with all proposed solutions so far. I don´t intend to defend mine: The only purpose of this pull request is to get things ironed out and working 👍 - So feel free to suggest the better one and I will adopt it!

@thisiskeithb : I have used PlatformIO/VSCode for several other projects of mine... Still not happy with it. I still see VSCode as a glorified text editor. You should try Microsoft Visual Studio (yes, I know, not open source) as a debugger/IDE for embedded development. THAT is what I would call and extremely good IDE with fantastic refactoring/code cleanup features. 
And for Arduino DUE, try Atmel Studio (nowadays Microchip Studio). Once you go that route, VSCode will be a thing of the past for you ;) - And yes, you can use Atmel Studio to compile Marlin using its Arduino support: That is exactly what I did and that is the main reason of me worrying about using Arduino to compile Marlin on the first place! ;)

**Comment by thinkyhead** [comment]
Good to see you, @ejtagle … Especially in these exciting times as we're getting into input shaping and might need to deconstruct s-curve. I'm sure there will be questions. We're also thinking about that Filtered B-Spline stuff somewhere down the road…. We'll get those Ender-3 print speeds boosted to X1 Carbon levels one way or another!

**Comment by ejtagle** [comment]
X1 Carbon speeds are perfectly possible. The printer I have (the makerparts) has an all metal frame that is pretty sturdy, and I have tried printing at 300mm/s. The problem i ran into was that the nozzle heater is unable to heat the required amount of plastic, as required by that print speed. But, probably improving it, it would work :)

**Pull request merged**
