### PR TITLE
[PR] Soft reset functionality

### PR DESCRIPTION
**Pull request by fedetony**
### Description

Added soft reset functionality:
    ```DO_SOFT_RESET_ON_KILL```  
After kill instead of locking will auto reset the machine.

`INCLUDE_SOFT_RESET` 
Allows to reset the machine with `^X` or `KILL` command. The command can be sent by remote host through serial or from any Gcode terminal or TFT display .

### Requirements
None.

### Benefits
You can reset the machine remotely, not become locked until someone comes to push the button.

### Configurations
[Marlin_Configs.zip](https://github.com/MarlinFirmware/Marlin/files/6331683/Marlin_Configs.zip)

### Related Issues
Working fine with  SKR1.4 and TFT35.

### CODE REVIEW

**Comment by X-Ryl669** [comment]
Jumping to address 0 is not the right way to reset. You'll leave all peripheral enabled (like DMA / ADC /etc) so next boot will not work as expected and likely crash the machine. There's already multiple way to reset the machine, depending on the configuration:
1. If the machine uses a watchdog, stop feeding it
2. If the machine does not use a watchdog, you've to call CPU specific code for reset that does actually reset all peripherals.
3. If none of the above is working or possible (for example, Linux), you'll have to rely on external function.

Please have a look [here](https://github.com/MarlinFirmware/Marlin/blob/5d8727a59c0b6a38e7c2cbd73feec3e76036db44/Marlin/src/HAL/shared/cpu_exception/exception_arm.cpp#L231) for ARM CPU implementation.

I guess similar code could be used and written for AVR, and ESP32. On ESP32 arduino, simply call `ESP.restart();`

If you do that, let's merge all reset code in a HAL function so there's only one instance of the reset code in Marlin's firmware.

**Comment by rhapsodyv** [comment]
Something like this was already discussed in the past.
The kill() is a safety mechanism. It will be called on situations that is very very likely that the printer demands someone to check some hardware or environment issue. It’s not just a simple freeze.

Allowing a remote reset may not be a good and safe way to handle a kill() call...

**Comment by X-Ryl669** [comment]
I've had experiences where the printer was "killed" by a temperature issue and there was no problem at all (rebooting solved it). Yet, I won't trade a false alarm from time to time to a safety measure in the case it was actually an issue. 

So I agree with Victor here. If something is not dangerous enough to reset, it shouldn't kill the printer so maybe it's worth fixing this instead. Else, resetting might only hide a bigger problem...

**Comment by fedetony** [comment]
There are two things here: 
- one is the ability for the printer to be soft reset through a command, as you have in Grbl and CNC machines. Overlooking my limited knowledge (and poor implementation) on how to reset properly any type of machine, the basic functionality is that the host can reset the machine through code. This is done in my implementation by the codes ^X and KILL. Of course I am only pointing to 0 in memory, but there are other ways it can be supplemented or coded correctly.
- Second is the Auto-reset after KILL, that one could leave it for manual reset, but the issue is that normally is triggered by any kill and makes the machine unresponsive to all, Even to soft-reset or to see the last position. For example if I send M112 command Kill is called, and I cannot reset the machine, except manually. 

At least number one is quite useful to me. :)

**Comment by thinkyhead** [comment]
If some platforms supply a method that can do a "clean" reset of the board right away, that would be a useful function to add to the HALs to replace our current jump-to-zero. Running out the watchdog also does work, but it takes 4 long seconds.

**Comment by X-Ryl669** [comment]
>     * one is the ability for the printer to be soft reset through a command

I agree.

**Comment by ellensp** [comment]
you should look at extending M997  which is a reboot, designed to start a firmware update but is a reboot all the same

**Comment by thinkyhead** [comment]
Right. The `flashFirmware` function is just a reboot, and on an old AVR board it would never actually result in a firmware flash. So, that function will need to be renamed, and `flashFirmware` can be a function that calls through to it on some platforms.

**Comment by fedetony** [comment]
What about M999?

**Comment by thinkyhead** [comment]
`M999` is specifically intended to continue after a `stop()`. Marlin doesn't throw a `stop()` for very many conditions, but it puts the firmware into a STOPPED state, continues to run the main loop, but only it requires `M999` to be sent before it will continue accepting commands from the host. This is an old protocol measure for hosts to be able to deal with a messed up machine until the user can fix the issue and continue. A `kill` is more severe, requiring nothing short of a reboot, because the board is assumed to be "on fire."

**Comment by thinkyhead** [comment]
Here are the reset methods I've compiled together for reference:
### AVR
```cpp
void HAL_reboot() {
   #if ENABLED(USE_WATCHDOG)
     while (1) { /* run out the watchdog */ }
   #else
     void (*resetFunc)() = 0;  // Declare resetFunc() at address 0
     resetFunc();              // Jump to address 0
   #endif
 }
```
### DUE
```cpp
void HAL_reboot() { rstc_start_software_reset(RSTC); }
```
### ESP32
```cpp
void HAL_reboot() { ESP.restart(); }
```
### LPC176x, SAMD51, STM32
```cpp
void HAL_reboot() { NVIC_SystemReset(); }
```
### STM32F1
```cpp
void HAL_reboot() { nvic_sys_reset(); }
```
### Teensy
```cpp
void HAL_reboot() { _reboot_Teensyduino_(); }
```

**Comment by thinkyhead** [comment]
The current behavior in Marlin has been that after a press of the KILL button, a second press of the KILL button will do a soft reboot of the machine. And in the case of a `kill()` or `minkill()` coming from a machine error such as a thermal alarm, the KILL button can still be used as a substitute RESET button.

I agree it's a bad idea to just let a soft reboot happen at the end of `kill()` because it will give no clue to what happened if you happened to be away from the machine. However, the `SOFT_RESET_ON_KILL` option can still be convenient if you don't have a KILL button, or just want another quick way to restart the machine. So in addition to adding platform-specific reboot functions, I've also modified this PR so you can do a soft reboot by pressing the controller button as a substitute for the KILL button when `SOFT_RESET_ON_KILL` is enabled.

**Pull request merged**
