### PR TITLE
Anet 1.0 alternative graphical LCD wiring

### PR DESCRIPTION
**Pull request by bizzehdee**
### Requirements

Ability to switch on the alternate wiring without having to modify the pins header for anet.

### Description

Define the alternate wiring in the pins header for anet10 LCDs so that it can be enabled from configuration.h instead of having to maintain a local copy of the header.

### Configurations

adds new #define to configuration.h
#define ANET_FULL_GRAPHICS_LCD_ALT_WIRING

### Related Issues

n/a

### CODE REVIEW

**Comment by sjasonsmith** [comment]
How does somebody know if they have alternate wiring? Are these custom cables, or different displays?

**Comment by bizzehdee** [comment]
> How does somebody know if they have alternate wiring? Are these custom cables, or different displays?

unofficial ones are usually alt wiring, but there is no real way to know other than have it not work, then require these changes (which are documented in the comments of pins_*.h) and then have it work.

**Comment by sjasonsmith** [comment]
So not custom cables? Two different pinouts on boards with otherwise similar hardware?

**Comment by bizzehdee** [comment]
> So not custom cables? Two different pinouts on boards with otherwise similar hardware?

yeah, the cables and connectors are the same, but the pins are in a completely different order on the board. i dont know why this is, i just know that it is, and that i have run into it, and that this could be something else others run into (given that there are already comments about it), and thought given that im capable of creating a patch to speed this up in future, i thought i would

**Comment by sjasonsmith** [comment]
OK, interesting. I am opposed to including custom cables in configurations or pins file, but this seems ok since it actually represents hardware that is available to purchase.

**Pull request merged**
