### PR TITLE
Add CONTROLLER_FAN_BED_HEATING option to control to run/not run the controller fan when the bed is heating

### PR DESCRIPTION
**Pull request by rondlh**
### Description

Add the option to run/not run the controller fan when bed heating is enabled, as this is often not needed.
This is done in Configuration_adv.h, by defining "CONTROLLER_FAN_BED_HEATING", which will run the controller fan when bed heating is enabled (the current default).
When the line is commented out the controller fan will not run anymore when the bed his eating, as this is often not needed, like for example when a main power bed heater is used or the controller fan does not affect the bed heating power supply.

### Requirements
This PR does not require any specific boards. Obviously you need a controller fan, and a heated bed for this to be useful.

### Benefits
Allow to have the bed heating, without running the controller fan, this will reduce noise, and can be useful when the bed is heating without the steppers being active. In my printer the bed is heated first, which takes some time, then homing starts. The controller fan does not need to run during the bed heating time. I also sometimes have the bed heating for some time without actually printing.

### Configurations
Nothing special is needed, just at #define CONTROLLER_FAN_BED_HEATING to the Configuration_adv.h

### Related Issues
No related issues.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
> Add the option to run/not run the controller fan when bed heating is enabled, as this is often not needed.

This is *especially* necessary for the bed mosfet since that will be the largest mosfet doing the most work.

**Comment by rondlh** [comment]
> > Add the option to run/not run the controller fan when bed heating is enabled, as this is often not needed.
> 
> This is _especially_ necessary for the bed mosfet since that will be the largest mosfet doing the most work.

Agree, in some cases it's necessary and or useful to run the controller fan when the bed is heating, but in some cases it's not. I have seen several printers where the bed heating has nothing to do with the controller fan, often only the stepper drivers are targeted with the controller fan and even the power supply is not affected or has it's own independent fan.

In my experience mosfet bed driver should not get hot, especially the mains voltage ones. I run my bed at 12A 36V, and my basic MKS mini mos only gets slightly warmer than ambient. If the mosfet gets hot it's usually a sign that something is not configured correctly. If a mosfet is driven correctly then the resistance is only a few mOhms, and Marlin keeps the switching frequency quite low, so also there should not be an issue.

Anyway, the PR gives an option, if you need the controller fan during bed heating, then that's still the default.

**Comment by thinkyhead** [comment]
If there's some straightforward way to disable this option for the appropriate example configurations we should apply that change across the examples repository after this is merged.

**Comment by thisiskeithb** [comment]
> If there's some straightforward way to disable this option for the appropriate example configurations we should apply that change across the examples repository after this is merged.

You can search for `#define TEMP_SENSOR_BED 0` which results in 52 matches. Then you can refine that further by the configs with `USE_CONTROLLER_FAN` enabled.

Having said that, it'd be best to leave enabled for cases where the config is updated with a new/aftermarket motherboard that has an additional PWM fan connection.

Based on this PR, Marlin will undefine `CONTROLLER_FAN_BED_HEATING` when `!TEMP_SENSOR_BED` is true, so that'd be the safer way to handle things.

**Pull request merged**
