### PR TITLE
Make options externally overridable

### PR DESCRIPTION
**Pull request by thinkyhead**
This sweeping change allows configuration options that are enabled with `#define MY_OPTION` (switches) to be overridden externally by defining them as `0`, `1`, `false`, `true`, or as a simple `#define`. If defined as `0` or `false` the `ENABLED` macro returns `false` (unlike `#ifdef` or `defined`). If defined as `1`, `true`, or with no value, the `ENABLED` macro returns `true`. Allowing configuration switches to be set to `0` or `false` makes them overridable through a Makefile or by prefixing with an `#include`.

To override an option this way assumes that the compiler will ignore subsequent attempts to `#define` the setting. For the cleanest usage, this allows a block like:

```
#ifndef MY_SETTING
  #define MY_SETTING
#endif
```

With this change, you could put only a few settings into a separate file – and `#include` it at the top of `Configuration.h`, and the compiler will pass those values through, including disabled switches.

Options that are enabled by setting some other value are not affected by this change, which is especially suited to options that are disabled by default or rely on conditions to be enabled.
- Create `macros.h` for… macros
- Add `ENABLED` / `DISABLED` macros to test whether options are enabled
- Supplant `#ifdef`, `#ifndef`, `defined` and `!defined` with new macros

Supersedes #2459, #2343, #2333

### CODE REVIEW

**Comment by clefranc** [comment]
@thinkyhead What I'm doing wrong?

```
In file included from C:\Users\CHRIST~1\AppData\Local\Temp\build7164299912364488230.tmp\sketch\Marlin.h:22:0,
                 from C:\Users\CHRIST~1\AppData\Local\Temp\build7164299912364488230.tmp\sketch\blinkm.cpp:5:
C:\Users\CHRIST~1\AppData\Local\Temp\build7164299912364488230.tmp\sketch\Configuration.h:6:33: fatal error: Configuration_BIV25.h: No such file or directory
 #include "Configuration_BIV25.h"
                                 ^
compilation terminated.
Error compiling.
```

**Comment by thinkyhead** [comment]
@clefranc That looks like the compiler is getting confused. Do you find the string "BIV25" anywhere in your copy of Marlin?

**Comment by clefranc** [comment]
@thinkyhead I too am confused, because I'm too impatient...

Solution:
The name of the new configuration file is irrelevant, the problem was I just not added it to the sketch (or just restart the Arduino IDE).

The custom config file needs to be `#include` at the top of the Marlin.h. That's it. Mine includes `#define` from Configuration.h, Configuration_adv.h and pins_RUMBA.h.

On the practical side, you should add a new file, like Configuration_overrides.h, or something like that, should be near the Configuration.h to be easily accessible, add it to Marlin.h. A description of its usage should also be put at the top of this new file.

**Comment by thinkyhead** [comment]
@clefranc Well, this PR is just to get a mechanism in place, so you can override from a Makefile. We will have to experiment to see how useful it is for other override methods. I think that if we go to a `Configuration_custom.h` style, we will need to add preemptive #ifdefs around most configuration options (in `Configuration.h` and `Configuration_adv.h`) first.

**Pull request closed without merging**
