### PR TITLE
U8glib-HAL extern cleanup

### PR DESCRIPTION
**Pull request by tpruvot**
was U8glib-HAL changed recently ? i only see commits from 2 years ago.

seems to bug on .c files... now, on "c++ only" headers

### CODE REVIEW

**Comment by tpruvot** [comment]
so in fact its not related to gcc version... tried to force gcc 8.2 but maple framework has errors on double inline stuff...

**Comment by tpruvot** [comment]
unsure what changed today... but now i need to fix u8g manually :

#### `U8glib-HAL_ID1932/src/lib/u8g_delay.c`
```cpp
/*== Arduino Delay ==*/
#if defined(USE_ARDUINO_DELAY)

+#ifdef __STM32F1__
+#include <libmaple/delay.h>
+#define delayMicroseconds(us) delay_us(us)
+#endif

void u8g_Delay(uint16_t val)
{
#if defined(__arm__)
  delayMicroseconds((uint32_t)val*(uint32_t)1000);
#else
  delay(val);
#endif
}
void u8g_MicroDelay(void)
{
  delayMicroseconds(1);
}
void u8g_10MicroDelay(void)
{
  delayMicroseconds(10);
}
#endif

```

**Comment by GMagician** [comment]
u8g comes from dev branch, but it needs to be changed to support samd51 (thinkyhead is currently working on such lib)

**Comment by tpruvot** [comment]
yep, its weird, i dont see any changes related...

else just for information, maple just need a few changes for gcc 8, but ive no real hope they will fix that soon...

**Comment by tpruvot** [comment]
oh i see what that could be now, he renamed branch names on u8g HAL i guess

**Comment by thisiskeithb** [comment]
Is this related? https://github.com/MarlinFirmware/Marlin/issues/15085

**Comment by thinkyhead** [comment]
> was U8glib-HAL changed recently ? i only see commits from 2 years ago.

The `dev` branch was altered temporarily. Changes / testing was moved to a `reorg` branch. Delete `~/.platformio/.cache` and `.pio/libdeps` before building again.

**Comment by tpruvot** [comment]
ok, the ststm32 change at the same time confused me, no logs with this zipped lib

**Comment by tpruvot** [comment]
rebased, i dont think a redefine of a extern cause warnings, but well just to be sure :p

**Comment by thinkyhead** [comment]
I wish I knew why the LPC176x builds take 10 times longer than other platforms. Single-threaded compiler?

**Comment by tpruvot** [comment]
its one single travis task yep... cpu is used to build other tasks in parallel so its much slower

**Pull request merged**
