### PR TITLE
G10 L2/L20 CNC work offset support

### PR DESCRIPTION
**Pull request by Domush**
## G10 CNC L2/L20 work offset support
- Relocated G10_G11.cpp to more appropriate multi-use directory

### Requirements
- CNC_COORDINATE_SYSTEMS must be enabled

### Benefits
- Adds ISO compatible G10 CNC workspace offset support
- Based on:
  - http://linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G10-L2_
  - http://linuxcnc.org/docs/2.6/html/gcode/gcode.html#sec:G10-L20_
- Adds support for gcode senders which expect ISO support, such as CNCjs.

### Configurations
- #define CNC_COORDINATE_SYSTEMS

**Coordinate Offset Example:**
```
Suppose the current machine coordinates are..

    X=110
    Y=110
    Z=20

.. and you want to make this the origin (i.e. X=0, Y=0, Z=0) of the second coordinate system 
(accessible via G55), then there are two options:

    G10 L2 P2 X110 Y110 Z20
    G10 L20 P2 X0 Y0 Z0

The first example will set offsets to be subtracted from the current machine coordinates.

The second example will set the coordinates of the current position in the specified coordinate 
system directly.
```

### Related Issues
https://github.com/MarlinFirmware/Marlin/issues/14734 - Add G10 CNC support (L2, L20)

### CODE REVIEW

**Comment by Domush** [comment]
Unsure why the tests are failing. There are proper checks in place.

**Comment by Domush** [comment]
## Code now fully tested and ready to merge.

**Comment by thijstriemstra** [comment]
> Code now fully tested and ready to merge.

Why was this closed and not merged (or even reviewed)?

**Comment by Domush** [comment]
> > Code now fully tested and ready to merge.
> 
> Why was this closed and not merged?

The lead maintainer is hostile to outside pull requests, and I got tired of fighting to get any of my CNC support improvements pull requests merged. I ended up creating a CNC-specific fork with this and multiple other CNC improvements:

https://github.com/Domush/mvCNC-Modern-Vintage-CNC-Firmware

**Pull request closed without merging**
