### PR TITLE
Cooler (for Laser) - M143, M193

### PR DESCRIPTION
**Pull request by descipher**
### Description

Laser Cooling Feature.

This code controls a passive or active cooling device such as an external chiller via relay or a TEC device or any fan driven radiator/coolant systems. The coolant can be a liquid or just a solid state laser with a fan cooled heatsink TEC coupling. Temperature sensing can be any of the supported thermistors and even some solid state laser equipped ones. This first pass include basic LCD menu's such as the 4x20 or the FULL Graphic LCD e.g. 12864

The code presents a coolant temperature control menu and a temperate status screen icon. Example attached on a 12864 LCD.   

### Requirements

RAMPS compatible board.

### Benefits

Extends the control capability of all laser cutters, especially CO2 lasers.
Automatic Thermal safety and protection for Laser diodes or CO2 tubes. (Sensor only capable as well)

### Configurations
laser1
Laser2

Config files
[Laser.Cooler.Config.zip](https://github.com/MarlinFirmware/Marlin/files/6088114/Laser.Cooler.Config.zip)

### Related Issues

None

gcodes are as follows:
M143 S0 = Cooler off
M143 S16 = Cooler on target 16C
M193 S15 = Cooler on target 15C and wait for target temp to be reached.
Any temp above COOLER_MAXTEMP becomes the lesser.

### CODE REVIEW

**Comment by descipher** [comment]
Conflicts need fixing, working on it as time permits.

**Comment by descipher** [comment]
Some issues to deal with.

Marlin\src\lcd\menu\menu_temperature.cpp:193:49: error: 'class Cooler' has no member named 'cooling'

Never mind, this was a naming change

**Comment by descipher** [comment]
Marlin\src\module\temperature.cpp:2982:83: error: 'WRITE_HEATER_COOLER' was not declared in this scope
Unfortunately thats why the rename of HAS_HEATED_BED the Macro uses the key word HEATER all over the place. 
#define _PWM_LOW(N,S) do{ if (S.count <= pwm_count_tmp) WRITE_HEATER_##N(LOW); }while(0)

**Comment by descipher** [comment]
Are we OK with strange naming such as WRITE_HEATER_COOLER or do we rename?
Could do a conditional on COOLER and break out to new Macro.

**Comment by descipher** [comment]
Issue: a preheat material menu called when there is no heating element to preheat. (Materials ABS and PLA are defined)
Renaming using PRESET_TEMP_COUNT was the addressing method, could simply do a conditional to handle it. 
Marlin\src\lcd\menu\menu_temperature.cpp:255:63: error: 'do_preheat_end_m' was not declared in this scope
         ACTION_ITEM_S(ui.get_preheat_label(m), MSG_PREHEAT_M, do_preheat_end_m);

**Comment by descipher** [comment]
Minor but noted:
```
*** [.pio\build\mega2560\src\src\lcd\menu\menu_temperature.cpp.o] Error 1
Marlin\src\module\temperature.cpp: In function 'void print_heater_state(const float&, const float&, heater_id_t)':
Marlin\src\module\temperature.cpp:3381:12: warning: enumeration value 'INDEX_NONE' not handled in switch [-Wswitch]
     switch (e) {
            ^
```
Occurs when no default is defined on the switch/case. The condition only occurs when no hot end is defined.

**Comment by descipher** [comment]
This PR is now functional and can be tested by anyone who would be interested. Thanks Scott.

**Comment by thinkyhead** [comment]
With this addition I can see it's about time I put together a proper template class to encapsulate temperature controllers.

**Comment by descipher** [comment]
A template would keep it much cleaner, there is a fair amount of duplication.

**Comment by descipher** [comment]
Wait what!, that's useful. Wish I knew that b4 .. lol

**Comment by thinkyhead** [comment]
Cleaned up and ready to compile…. Please give it a run and make sure it's all good.

**Comment by descipher** [comment]
Already happening .. lol

**Comment by descipher** [comment]
Runs on RAMPS 1.4, first pass, no issues. There is much more to come. I will look at flowmeter integration capability and coolant pump controls next. Will also ask for gcode doc adds once it's good. Will send a note to the Lightburn guys on the same gcode. 
Thankyou. :)

**Pull request merged**
