### PR TITLE
Break out gcode handlers - part 1

### PR DESCRIPTION
**Pull request by thinkyhead**
- Only affects Marlin_main.cpp
- Incurs no extra code size or overhead
- Makes process_commands simpler
- Makes code easier to read and maintain

### CODE REVIEW

**Comment by thinkyhead** [comment]
Replacing #1440 to remove distracting commits

**Comment by galexander1** [comment]
I still like this patch, and once we tag a stable, I think we should
merge it, and then clean up any issues it might introduce as a separate
pull request.

I do still have some comments. :)

@thinkyhead said:

> I certainly agree that a change like this seems large and deserves much
> review, but it's almost mechanical, moving the exact code into a
> separate function and doing a little cleanup.

I agree that it's mechanical to move the code, but you did cleanup on
a bunch of scattered code that you didn't move.  It's not the end of the
world, it's just that it could stand to be a separate commit ("sanitize
whitespace") and that that commit itself should hold off until after
someone checks in a style guide.

And this is pointless/bad:

```
 case 90: // G90
```
-      relative_mode = false;
-      break;
   case 91: // G91
-      relative_mode = true;
-      relative_mode = gCode == 91;
     break;

The switch statement is one compare, and then the (gCode == 91) is a
second compare.  The old code had only one compare operation.  The
performance of process_command() doesn't really matter, but there's no
point giving up performance just to make the code less readable.

But the real problem with the G90/G91 change is that it doesn't have
anything to do with the commit message.

I'm real torn about the other things that do have to do with the commit
message (i.e., gcode_G2_G3(gCode==2)).  On the one hand, that does make
it better if the compiler decides to inline it, but on the other hand it
almost certainly produces an extra comparison instruction if it doesn't
inline it.  Plus, the compiler will only inline the function if it is
very small (because of -Os), and in that case you really would probably
prefer two copies of the code instead of one copy with the extra
comparison...

A few notes about inline.  The C++ "inline" keyword is almost (but not
quite) the exact same as the C "static" keyword.  It doesn't tell the
compiler to inline it.  What it does do is if all of the calls are
inlined, then it doesn't have to produce the out-of-line definition.

Also, function calls are cheap.  This is an axiom to live by, and I
checked and avr-gcc honors it.  So don't worry about inlining, in your
mind, leave it as a function call and let the compiler decide whether it
is worthwhile to inline it.  Mostly, unless it is a very simple wrapper
function, the compiler will (and should) decide not to inline it with
-Os, and that is just fine.  It won't slow things down, unless maybe it
is inside the ISR, and even then we probably only care if it is inside a
loop.

But my biggest objection is that one advantage of factoring out the body
of a giant switch statement is that the switch becomes stupider.  Stupid
is good in rote tabular code.  And:
   case 2: gcode_G2_G3(true);  break; // CW arc
   case 3: gcode_G2_G3(false); break; // CCW arc
is stupider than:
   case 2: // CW arc
   case 3: // CCW arc
     gcode_G2_G3(gCode == 2);
     break;
The redundant comparison is simply more reading, more spots for a typo or
a surprise to hide.

But that's a pretty minor nit overall.  It's hard when doing a needed
major restructure to identify which changes are needed and which are
gratuitous, but I'm just trying to nudge in the direction of fewer
gratuitous changes. :)

**Comment by thinkyhead** [comment]
The `(gCode == 91)` change is intentional, to prevent the newly-added `inline` specifier from doing two expansions. The compiler might notice the invariance of the two code paths when it's expressed this way, but I anticipate that it would treat two invocations in a less intelligent way and do two expansions – wasting code space – or just not inline it, which wastes cycles (though of course these G-codes aren't in any sense a bottleneck). But I would like to try both and compare.

**Comment by thinkyhead** [comment]
I noticed before I added `inline` that the compiler was already inlining, but I presume that compiler options will change this behavior in some way, and I think that is why @bkubicek suggested that I do the `inline` commit.

**Comment by thinkyhead** [comment]
I just checked it out (with `gcode_G2_G3`) and the difference amounts to 8 bytes, so it seems that putting in 2 invocations causes them not to `inline` _even with the inline specifier_. It's true that function calls are cheap, and it's mostly G0 and G1 that needs to be optimal, since they are the workhorses.

**Comment by galexander1** [comment]
gCode == 91 change isn't a function call, though, it's a variable
assignment, and in that case it's an unambiguous loss.

gCode == 2 is a function call, and involves the inliner conundrum you
face.

The reason we re-factor code for readability is that in the 70s someone
proved that function call overhead isn't worth worrying your head over.
If they hadn't proved this already, we would have to reject this pull
request out of hand.

I don't see why we would build on top of that wisdom only to go back to
the 60s and worrying about the tremendous expense of function call
overhead.  The expense is nothing.  Maybe in the ISR, _maybe_.

The only expense we actually care about for the G-code parser is size.

**Comment by galexander1** [comment]
I have said several times now that the C++ "inline" keyword is the same
as the C "static" keyword.  It doesn't cause inlining, it allows the
compiler to delete the out-of-line copy if it inlines all of the calls.
Otherwise you could potentially have two copies of the function where one
would do.

**Comment by thinkyhead** [comment]
I learned to program in the early 80's on machines with 48K RAM where you had to squeeze out every byte for performance and size, so it's an ingrained habit. When I see Marlin hitting the ceiling trying to do delta plus graphical LCD it makes me feel that every cycle is starting to count....

**Comment by galexander1** [comment]
G0 and G1 do not need to be especially optimized.  A typical G-code file
contains around 20 G1s per second.  Our AVR runs at multiple millions of
cycles per second.

We don't get stuttering with graphic LCD + delta because our code is
"slow", we get it because our code blocks.  The graphic LCD code performs
a relatively long loop during which no other "foreground task" (G-code
parsing, or delta interpolation) can occur.  If we turned delta
interpolation into a background task (tied to a timer interrupt, for
example), we might solve most of that problem (though that would be a
touchy change!).  But no matter how fast we make our G-code parser, it
won't execute while the graphic LCD copy is blocking everything.

You might try to optimize the graphic LCD copy loop, or try to break it
up so it doesn't block as long at one go.

There is no end we serve by obfuscating the G-code parser.

**Comment by thinkyhead** [comment]
In my deep reading of C / C++ code, `gCode == 91` is only _apparently_ a `bool` variable assignment. Anticipating the compiler, we can see that what it really is is a queue to the compiler that there will be a certain codepath. The compiler can see that `gCode` can _only ever_ `== 91` when `case 91`. So it is simply a way of _"tricking"_ the compiler into giving us an inline for no extra cost. The comparison actually never gets compiled in.

So I dunno, perhaps "obfuscating" is a strong term. I don't know anyone who would be reading this codebase who is so dull as not to be able to understand what you and I are discussing, or if they _are_ new to programming, who would not look at this example without learning something interesting and perhaps valuable.

Anyway, I can always make my own fork and indulge my need to clean up and re-express the code. One reason I am doing so is to gain the deepest possible understanding of the code-base, reduce it to essentials, and find those places where redundancies or similar elements might be combined. The codebase feels a bit cobbled together, not yet fully adaptable to the next generation of boards, and this initial push on my part is intended to make clearer the higher level structure of the code, and look at how it can be adapted for a growing field of more capable – yet still Arduino-programmable boards. I'm a fast coder, so admittedly in quite the rush to get to the next stage! :)

**Comment by galexander1** [comment]
This is the gCode == 91 bit:

```
 case 90: // G90
 case 91: // G91
   relative_mode = gCode == 91;
   break;
```

It is possible for an optimizer to do a number of things to combine the
two conditionals, but generally speaking if it happens it is only luck.
It winds up being controlled by constant propagation, which is a very
touchy optimization (coincidences can obscure it).  A quick experiment
shows that avr-gcc -Os will take 3 more instructions for the way you have
it compared to the status quo ante, though I'm sure that number will
change in context.

If I came along and the code was as you have it, I wouldn't change it.
And if I came along to the status quo ante, I also wouldn't change it.
But if you suggest a change from before to after, I expect that change to
be concretely motivated.

I hope you can tell that the reason I'm lecturing is that this is a
lesson that was also hard for me to learn. :)

When you first write code, you agonize over "if" vs. "switch" vs. "? :".
When you read code, you don't need that agony.

Some of the code is so mangled, it can't be read.  That is why I advocate
for a refactoring -- gcode_G29() being its own function with its own
local variables is a godsend.  But a lot of what you are touching was
perfectly readable...you cringe while you read it, but you don't have any
doubt about what it is doing.

On a practical note, you'll read faster if you set the pen down --
cringing is faster than editing.  With how much time you've spent
reformatting code that isn't broken, you could already be deep into
grokking the planner and the stepper ISR, and then I think you'd really
understand why it is that big blocking LCD writes turn into visible
stutters, and why some innocent-looking firmware retract code caused a
hard-to-track single-wall bug, and why there is still a trickle of delta
bugs.

**Comment by thinkyhead** [comment]
(Oops, I meant G2-3 I suppose, since that's the one with the bool thing.) G90-91 was meant to align with the others and make use of the now-handy gCode value, but yeah, wtf thinkyhead?

**Comment by thinkyhead** [comment]
#1456

**Pull request closed without merging**
