### PR TITLE
SKR Pro TMC uart fix

### PR DESCRIPTION
**Pull request by Evg33**
SKR PRO 1.1 Fix TMC2209 UART communication
https://github.com/MarlinFirmware/Marlin/issues/14615

### CODE REVIEW

**Comment by Evg33** [comment]
Compiles successfully.
Verification required.
I can check it in a few hours.

**Comment by RudyBenner** [comment]
If it's not cached, it does not fetch TMCStepper

**Comment by RudyBenner** [comment]
Hate to be the dissenting voice. Cleared stored files in cache and .pio, same result.

image

**Comment by Evg33** [comment]
@RudyBenner Software disabled ?
`  //#define SOFTWARE_DRIVER_ENABLE`

**Comment by RudyBenner** [comment]
image

**Comment by RudyBenner** [comment]
sorry, no go, either way.

**Comment by teemuatlut** [comment]
`TMCStepper@<1.0.0` means version *anything* below 1.0.0 and I'm now at `v0.5.0`.
The version condition is there because moving from 0.x.x to 1.x.x is a major revision change and can have API changes and does not need to be backwards compatible.

**Comment by viper93458** [comment]
I had the same issue with 2208s and realized that I had to move the recommended library include (from the bigtreetech GitHub repository readme) to the SKR Pro section and NOT the common section to get it to compile.

**Comment by teemuatlut** [comment]
The STM32 platform now ships with a SW Serial library and that workaround should no longer be necessary.

**Comment by viper93458** [comment]
Unfortunately for me as of the latest BF 2.x download from yesterday afternoon it was still needed otherwise I got the same errors about HWSerial as the above screenshot. As I am not knowledgeable enough to comment further, I will bow out and not attempt to hijack the thread. I just saw the error and thought it may be helpful. :)

**Comment by Evg33** [comment]
It's working with 2208 via uart.
2 middle blue contacts on 2208 is soldered.
Video: https://youtu.be/1tiIr5R-jok

image


```
SENDING:M122
		X	Y
Enabled		true	true
Set current	850	850
RMS current	826	826
MAX current	1165	1165
Run current	26/31	26/31
Hold current	13/31	13/31
CS actual	26/31	26/31
PWM scale	107	255
vsense		1=.18	1=.18
stealthChop	true	true
msteps		64	64
tstep		max	max
pwm
threshold
[mm/s]
OT prewarn	false	false
OT prewarn has
been triggered	false	false
off time	3	3
blank time	24	24
hysteresis
-end		-1	-1
-start		1	1
Stallguard thrs
DRVSTATUS	X	Y
stst		*	*
olb			*
ola			*
s2gb
s2ga
otpw
ot
157C
150C
143C
120C
s2vsa
s2vsb
Driver registers:
		X	0xC0:1A:00:00
		Y	0xC0:1A:00:C0
Testing X connection... OK
Testing Y connection... OK

```

**Comment by Evg33** [comment]
With TMC5160 SPI working too. (not soldered !!!)
```
SENDING:M122
		X	Y
Enabled		true	true
Set current	850	850
RMS current	839	839
MAX current	1183	1183
Run current	16/31	16/31
Hold current	8/31	8/31
Global scaler	133/256	133/256
CS actual	8/31	8/31
PWM scale	12058879	65579
vsense
stealthChop	true	true
msteps		64	64
tstep		max	max
pwm
threshold
[mm/s]
OT prewarn	false	false
OT prewarn has
been triggered	false	false
off time	3	3
blank time	24	24
hysteresis
-end		-1	-1
-start		1	1
Stallguard thrs	0	0
DRVSTATUS	X	Y
stallguard
sg_result	0	0
fsactive
stst		*	*
olb		*
ola		*
s2gb
s2ga
otpw
ot
Driver registers:
		X	0xE0:08:40:00
		Y	0x80:08:40:00
Testing X connection... OK
Testing Y connection... OK

```

**Comment by Evg33** [comment]
@RudyBenner  https://github.com/MarlinFirmware/Marlin/issues/14615#issuecomment-534742630

**Comment by thinkyhead** [comment]
This PR has no effect on which version of `TMCStepper` will be used. It may help to delete `.platformio/.cache` from your HOME folder and build again.

**Pull request closed without merging**
