### PR TITLE
Get rid of german umlaute - additions for 4th extruder - more translations

### PR DESCRIPTION
**Pull request by AnHardt**
German Umlaute (ÄÖÜäöüß) are not displayed correct - at least on REPRAP_DISCOUNT_SMART_CONTROLLER and REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER.
Changes in wording of language_de.h can avoid that.

Added the needed changes for the 4th extruder in language_de.h
Translated some further messages.

Removed  unused MSG_RECTRACT from language_en.h and language_de.h

### CODE REVIEW

**Comment by CONSULitAS** [comment]
+1 from me :+1: 

@AnHardt Have been working on the same changes. :-)

**Comment by JustAnother1** [comment]
I hope that it is clear to everybody that this is an ugly work around. The Menu becomes harder to understand. OK easier than with Umlaute not working, but harder than with working Umlaut.

So the better solution would be to add the symbols for the Umlaut so that the Displays can show Umlaute. That should be possible at least for _FULL_GRAPHIC_ Displays.

So please don't merge this !

**Comment by AnHardt** [comment]
Hello @JustAnother1 
Yes, its not a perfect solution, but the working one I could do.
I don't think that the changes from:
Hauptmenü -> Hauptauswahl,
Vorwärmen -> Vorheizen
Düse -> Duese (für Düse ist mir echt nix brauchbareres eingefallen)
can be a problem for anyone.
We can discuss about my other changes.

**Comment by JustAnother1** [comment]
I will not argue on "Vorwärmen" -> "Vorheizen" That seems OK to me.
"Hauptauswahl" on the Other side ? I don't know any badly translated interface that use something else than "Hauptmenü"
"Duese" is the bad workaround done in the 80ties when DOS was hightec and computers only came with US-ASCII.

So unless the Marlin Developers decide that there is absolutely no space available for those few extra characters I would not want this change of your to be merged.

You might have solved the current problem by using words that don't contain Umlaute but this will then come up in the feature with every new Menu Entry or message. 
What about G-Code M117( M117 = show messages on Display) ? 
M117 Prüfe Filament Sensor

What about displaying file names("Hütte.gcode")?

Changing the wording to work around the issue is a bad thing. If you need a solution right now and cant fix the font then put something in that automatically replaces all Umlaute with their 80s version:
ä -> ae
ü -> ue
ö -> oe
ß -> ss

that would be the second best solution. I would still prefer extending the font.

**Comment by AnHardt** [comment]
Hello @JustAnother1
"Hauptmenü" is only used to return from first level submenus. How about "Hauftmenü" -> ".." ?
Well understood by geeks - but they don't need a German translation.

YOU are responsible for what You name Your files, or what YOU want the machine to display. Ideally this should take in account the capabilities of the machine. Ok, ok - ideally the machine should do what you think. ;-)

Do you have an idea how to solve the problem with character based displays?

**Comment by JustAnother1** [comment]
Last Time I checked a character Displays Data sheet they had an option to program your own character. You can in that mode define each pixel for that character and map it to y byte value. Basically what you do is to extend the font of the Display. The Ulticontroller is character based, but has special characters for Temperature, Heater Bed, Feed rate and Time. So maybe look at that code. I think I saw the source code for that characters somewhere, but can't remember where.

I know that I could avoid Umlaute in Filenames and could avoid them in M117's. But wouldn't it be better if I wouldn't have to avoid them. These are two features you get for free if someone teaches those displays how the umlaut characters should look like.

I don't understand "Hauftmenü" maybe I'm not geeky enough, but I can prove to be German,.. And it still has an "ü" so what is the point?

**Comment by galexander1** [comment]
For what it's worth, HD44780 (most popular cheap text LCD controller) only has 8 programmable characters.  You can probably use one of them for u-umlaut, but it's not exactly free.

**Comment by AnHardt** [comment]
@JustAnother1 Sorry for misspelling "Hauptmenü" once.

@galexander1 I see. All custom characters are used. Hmmm... How about replacing one or more when leaving info-screen and switching back when entering?  Too complicated for me.
How on using filesystem-symbols on toprows of submenues? "/" for main, ".." for submenues? At least this have not to be translated.

...
thinking

**Comment by JustAnother1** [comment]
@AnHardt ah! Now I get it ".." would be a geeky version indeed. For all the Dos and command line lovers out there ;-)

Did you look into how graphic displays handle the special characters ? Might give you food for thinking,..

**Comment by bkubicek** [comment]
just use "retour" instead of any "Haupt*"...

Bernhard

**Comment by thinkyhead** [comment]
Due to recent changes for the Progress Bar feature, there are 3 extra custom characters available everywhere but the info screen. Take a look at the hitachi lcd init code.

**Comment by floyd871** [comment]
What about change die "Umlaut" to the  corresponding Hex-Value? This works great for me (REPRAP_DISCOUNT_SMART_CONTROLLER)
...
#define MSG_PREHEAT_PLA                     "Vorw\xe1rmen PLA"
....
#define MSG_FAN_SPEED                       "L\365ftergeschw."

**Comment by AnHardt** [comment]
@floyd871 
Well. And on REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER is at least not so bad as before. Only one charecter of pixeldust insted of two!

Closing this pullrequest.

**Comment by CONSULitAS** [comment]
@AnHardt 
@JustAnother1 
@floyd871 
As stated before, I am interested in a working german translation, too.

Do you know the c't-article "Selbstanzeige - 3D-Druckerbausatz mit Display und SD-Kartenslot erweitern" (c’t 2014, Heft 10, https://www.heise.de/artikel-archiv/ct/2014/10/172_Selbstanzeige )?
- They tell: "Deutsche Umlaute kann der Controller für das Display nicht verarbeiten. Wen’s stört, der kann die Texte im Firmware-Quellcode anpassen." (rough: The LCD can't display german umlaut, you could modify firmware)
- And: "Statt „Vorwärmen PLA“ kann man zum Beispiel einfach „Vorheizen PLA“ eintragen. ... Vielleicht findet sich auch alsbald jemand, der eine Anpassung der deutschen Texte anderen via Internet zur Verfügung stellt." (rough: You could change the wording to synonyms. ... Perhaps somebody will contribute on the internet.)
- BTW: This is the machine I own and the change of wording worked for me.

But the proposal of @floyd871 made me curious and I did a little research about "HD44780 umlaute arduino" and found some interesting facts.

You all three are right - in a way. And it is rather complex:
- There are three different ROM versions for the character set on HD44780 (http://www.adafruit.com/datasheets/HD44780.pdf).
  - "ROM Code: A00" which has japanese characters supported (page 17)
  - "ROM Code: A02" which has european characters supported (page 18)
  - some manufracturers have custom character sets
- If you have japanese ROM you could only use custom characters.
- If you have european ROM you are lucky and can use the way @floyd871 proposed.
- If you have a full graphics display you need a totaly different solution. (Or does the current translation just work out of the box?)
- The custom characters are used for nozzle bed and so on, so there is no way to use them on the Info screen because umlaut would not work for status messages - annoying.

So I see the following possible solutions:
1) Skip any umlaut and go the way of @AnHardt.
- Not very elegant, but working.

2) Do more than one german translation.
- language_de_umlaut / language_de_ae_oe_ue / language_de_HD44780 (with "Vorw\xe1rmen PLA"...)
- Not very convenient for the user, but makes the best out of the hardware you have.

3) Deal with different types of hardware in precompiled code.
- We could invent a `#define HD44780_jap`,  `#define HD44780_eu` and `#define HD44780_cust` with many `#if`
  - Simple, but should work.

4) Deal with different types of hardware in dynamic code.
- We invent similar defines like in 3., but with a parser that translates on runtime depending of the hardware (like http://forum.arduino.cc/index.php?topic=6111.0)
- Needs more ressources and more work, but is the most sophisticated solution.
- Would work for other special signs and other languages with special characters like french, too!!! 

Do you see any other solution? I would rank it 4. -> 3. -> 2. -> 1.

So please stop arguing and let's work together to build a working solution which reflects this. OK?

If we get to a common sense, I would try to build a prototype for this.

**Comment by CONSULitAS** [comment]
@AnHardt Oops: You closed while I was writing. What do you think?

**Comment by thinkyhead** [comment]
Most universal solution (for HD44780) is to make umlaut available everywhere but the info screen, but if you very much wanted to use ü in status messages, the Degree character can be replaced with a near-equivalent extended character, and the current "degree" character can be replaced with ü.

**Comment by JustAnother1** [comment]
@CONSULitAS 
I remember reading that article and Thinking WTF? It's part of the reason why I do not read c't anymore. I loved to read c't but the quality of the articles got really bad.. OK back to topic.

I'm a bit confused what your proposals are (the numbering is missing in the post).
This is totally my opinion and others might have good reasons to disagree, but I would suggest this:

@AnHardt seems to have the language_de_HD44780 with a wording that avoids Umlaute. So offering that as a pull request. Not as a replacement but as a alternative for German text would be something that would make sense. This way the c't people get their wish (the version is available on the Internet (I don't understand why they don't put it on-line themselves) and maybe Marlin merges that.

A second pull request would make sense. A version for all Text based displays. Here the unused special chars are used to create ÄÖÜß. With @thinkyhead s idea of using the degree sign this would even work on the info screen for Düse. For a perfect solution we would need 7 (ÄÜÖßäöü) special characters. It would probably make sense to do this in a way so that it can be reused for French, Spanish,... texts.

I have no idea how the text is put on the display so it might make sense to do a on the fly conversion ä->ae, ü->ue before sending it to the display.

For graphical displays the "Hauptmenü" and "Düse" should stay and these displays should be able to handle the Umlaute. Or a Pull request to make them handle them should be possible.

If I can help creating one of the described pull request (except the Umlaut avoidance) then let me know.

**Comment by CONSULitAS** [comment]
@JustAnother1 Oops - Markdown didn't do what I wanted it to... I Think its clearer now.

My proposal 4) is the on the fly idea with conversion tables for the different hardware.
update: 3) was a typo /update

BTW: I don't understand the c't people, too.
BTW 2: But the Vellemann people are worse: They offer a Malin older than august 2013 as V2 Update. :-)

**Comment by AnHardt** [comment]
Until someone has a better solution i sugest somting like this.
Please comment.

/**
- German
  *
- LCD Menu Messages
- Please note these are limited to 17 characters!
  *
  */
  #ifndef LANGUAGE_DE_H
  #define LANGUAGE_DE_H

// uncomment your style
//#define UMLAUTE_DE 1 //                     ü > ü
//#define UMLAUTE_DE 2 // for HITACHI_HD44780 ü > \365
//#define UMLAUTE_DE 3 // for Langform        ü > ue
//#define UMLAUTE_DE 4 // for my (your) way

//please test next. REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER defines  REPRAP_DISCOUNT_SMART_CONTROLLER to.
#ifndef UMLAUTE_DE
  #if defined (REPRAP_DISCOUNT_SMART_CONTROLLER) && !( defined ( REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER ) )
    #define UMLAUTE_DE 2
  #else
    #define UMLAUTE_DE 3
  #endif
#endif

#if UMLAUTE_DE <= 1
  #define MSG_MAIN                          "Hauptmenü"
  #define MSG_NOZZLE                        "Düse"
  #define MSG_NOZZLE1                       "Düse2"
  #define MSG_NOZZLE2                       "Düse3"
  #define MSG_NOZZLE                        "Düse"
  #define MSG_NOZZLE1                       "Düse2"
  #define MSG_NOZZLE2                       "Düse3"
  #define MSG_FAN_SPEED                     "Lüfter"
  #define MSG_CARD_MENU                     "SDKarten Menü"
#elif UMLAUTE_DE <= 2
 // Romcode A00; ä > \341 \xe1, ö > \357 \xef, ü > \365 \xf5, ß > \342 \xe2, ° > \337 \xdf               // octal hex
 // Romcode A02; ä > \344 \xe4, ö > \366 \xe6, ü > \374 \xfc, ß > \337 \xdf, ° > \260 \xb0, Ä > \304 \xc4, Ö > \326 \xd6, Ü > \334 \xdc
  #define MSG_MAIN                          "Hauptmen\365"
  #define MSG_NOZZLE                        "D\365se"
  #define MSG_NOZZLE1                       "D\365se2"
  #define MSG_NOZZLE2                       "D\365se3"
  #define MSG_NOZZLE                        "D\365se"
  #define MSG_NOZZLE1                       "D\365se2"
  #define MSG_NOZZLE2                       "D\365se3"
  #define MSG_FAN_SPEED                     "L\365fter"
  #define MSG_CARD_MENU                     "SDKarten Men\365"
#elif UMLAUTE_DE <= 3 
  #define MSG_MAIN                          "Hauptmenue"
  #define MSG_NOZZLE                        "Duese"
  #define MSG_NOZZLE1                       "Duese2"
  #define MSG_NOZZLE2                       "Duese3"
  #define MSG_NOZZLE                        "Duese"
  #define MSG_NOZZLE1                       "Duese2"
  #define MSG_NOZZLE2                       "Duese3"
  #define MSG_FAN_SPEED                     "Luefter"
  #define MSG_CARD_MENU                     "SDKarten Menue"
#elif UMLAUTE_DE <= 4 
  #define MSG_MAIN                          ".."
  #define MSG_NOZZLE                        "Duese"
  #define MSG_NOZZLE1                       "Duese2"
  #define MSG_NOZZLE2                       "Duese3"
  #define MSG_NOZZLE                        "Duese"
  #define MSG_NOZZLE1                       "Duese2"
  #define MSG_NOZZLE2                       "Duese3"
  #define MSG_FAN_SPEED                     "Luftmenge"
  #define MSG_CARD_MENU                     "SDKarte"
#endif

#define WELCOME_MSG                         MACHINE_NAME " Bereit."
#define MSG_SD_INSERTED                     "SDKarte erkannt"
#define MSG_SD_REMOVED                      "SDKarte entfernt"
#define MSG_AUTOSTART                       "Autostart"
#define MSG_DISABLE_STEPPERS                "Motoren Aus"
#define MSG_AUTO_HOME                       "Auto Nullpunkt"
#define MSG_SET_HOME_OFFSETS                "Set home offsets"
#define MSG_SET_ORIGIN                      "Setze Nullpunkt"
#define MSG_PREHEAT_PLA                     "Vorheizen PLA"
#define MSG_PREHEAT_PLA0                    "Vorheizen PLA 1"
#define MSG_PREHEAT_PLA1                    "Vorheizen PLA 2"
#define MSG_PREHEAT_PLA2                    "Vorheizen PLA 3"
#define MSG_PREHEAT_PLA3                    "Vorheizen PLA 4" 
#define MSG_PREHEAT_PLA0123                 "Vorh. PLA Alle"
#define MSG_PREHEAT_PLA_BEDONLY             "Vorh. PLA Bett"
#define MSG_PREHEAT_PLA_SETTINGS            "Vorh. PLA Ein."
#define MSG_PREHEAT_ABS                     "Vorheizen ABS"
#define MSG_PREHEAT_ABS0                    "Vorheizen ABS 1"
#define MSG_PREHEAT_ABS1                    "Vorheizen ABS 2"
#define MSG_PREHEAT_ABS2                    "Vorheizen ABS 3"
#define MSG_PREHEAT_ABS3                    "Vorheizen ABS 4"
#define MSG_PREHEAT_ABS0123                 "Vorh. ABS Alle"
#define MSG_PREHEAT_ABS_BEDONLY             "Vorh. ABS Bett"
#define MSG_PREHEAT_ABS_SETTINGS            "Vorh. ABS Ein."
#define MSG_COOLDOWN                        "Heizungen Aus"
#define MSG_SWITCH_PS_ON                    "Netzteil Ein"
#define MSG_SWITCH_PS_OFF                   "Netzteil Aus"
#define MSG_EXTRUDE                         "Extrude"
#define MSG_RETRACT                         "Retract"
#define MSG_MOVE_AXIS                       "Achsen bewegen"
#define MSG_MOVE_X                          "X bewegen"
#define MSG_MOVE_Y                          "Y bewegen"
#define MSG_MOVE_Z                          "Z bewegen"
#define MSG_MOVE_E                          "Extruder"
#define MSG_MOVE_E1                         "Extruder2"
#define MSG_MOVE_E2                         "Extruder3"
#define MSG_MOVE_01MM                       "0.1 mm bewegen"
#define MSG_MOVE_1MM                        "1.0 mm bewegen"
#define MSG_MOVE_10MM                       "10  mm bewegen"
#define MSG_SPEED                           "Geschw."
#define MSG_BED                             "Bett"
#define MSG_FLOW                            "Fluss"
#define MSG_FLOW0                           "Fluss 0"
#define MSG_FLOW1                           "Fluss 1"
#define MSG_FLOW2                           "Fluss 2"
#define MSG_CONTROL                         "Einstellung"
#define MSG_MIN                             "\002 Min"
#define MSG_MAX                             "\002 Max"
#define MSG_FACTOR                          "\002 Faktor"
#define MSG_AUTOTEMP                        "AutoTemp"
#define MSG_ON                              "Ein"
#define MSG_OFF                             "Aus"
#define MSG_PID_P                           "PID-P"
#define MSG_PID_I                           "PID-I"
#define MSG_PID_D                           "PID-D"
#define MSG_PID_C                           "PID-C"
#define MSG_PID_P1                          "PID-P E2"
#define MSG_PID_I1                          "PID-I E2"
#define MSG_PID_D1                          "PID-D E2"
#define MSG_PID_C1                          "PID-C E2"
#define MSG_PID_P2                          "PID-P E3"
#define MSG_PID_I2                          "PID-I E3"
#define MSG_PID_D2                          "PID-D E3"
#define MSG_PID_C2                          "PID-C E3"
#define MSG_ACC                             "Acc"
#define MSG_VXY_JERK                        "Vxy-jerk"
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax "
#define MSG_X                               "x"
#define MSG_Y                               "y"
#define MSG_Z                               "z"
#define MSG_E                               "e"
#define MSG_VMIN                            "Vmin"
#define MSG_VTRAV_MIN                       "VTrav min"
#define MSG_AMAX                            "Amax "
#define MSG_A_RETRACT                       "A-Retract"
#define MSG_XSTEPS                          "X steps/mm"
#define MSG_YSTEPS                          "Y steps/mm"
#define MSG_ZSTEPS                          "Z steps/mm"
#define MSG_ESTEPS                          "E steps/mm"
#define MSG_TEMPERATURE                     "Temperatur"
#define MSG_MOTION                          "Bewegung"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED              "E in mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "Filament D 1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Filament D 2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Filament D 3"
#define MSG_CONTRAST                        "LCD Kontrast"
#define MSG_STORE_EPROM                     "EPROM speichern"
#define MSG_LOAD_EPROM                      "EPROM laden"
#define MSG_RESTORE_FAILSAFE                "Konfig. Reset"
#define MSG_REFRESH                         "Aktualisieren"
#define MSG_WATCH                           "Info"
#define MSG_PREPARE                         "Vorbereitung"
#define MSG_TUNE                            "Justierung"
#define MSG_PAUSE_PRINT                     "Druck anhalten"
#define MSG_RESUME_PRINT                    "Druck fortsetz"
#define MSG_STOP_PRINT                      "Druck stoppen"
#define MSG_NO_CARD                         "Keine SDKarte"
#define MSG_DWELL                           "Warten..."
#define MSG_USERWAIT                        "Warte auf Nutzer"
#define MSG_RESUMING                        "Druck Fortsetzung"
#define MSG_PRINT_ABORTED                   "Druck abgebrochen"
#define MSG_NO_MOVE                         "Kein Zug."
#define MSG_KILLED                          "KILLED"
#define MSG_STOPPED                         "GESTOPPT"
#define MSG_CONTROL_RETRACT                 "Retract mm"
#define MSG_CONTROL_RETRACT_SWAP            "Wechs. Retract mm"
#define MSG_CONTROL_RETRACTF                "Retract  V"
#define MSG_CONTROL_RETRACT_ZLIFT           "Hop mm"
#define MSG_CONTROL_RETRACT_RECOVER         "UnRet +mm"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "Wechs. UnRet +mm"
#define MSG_CONTROL_RETRACT_RECOVERF        "UnRet  V"
#define MSG_AUTORETRACT                     "AutoRetract"
#define MSG_FILAMENTCHANGE                  "Filament wechseln"
#define MSG_INIT_SDCARD                     "SDKarte init."
#define MSG_CNG_SDCARD                      "SDKarte getauscht"
#define MSG_ZPROBE_OUT                      "Sensor n. a. Bett"
#define MSG_POSITION_UNKNOWN                "X/Y vor Z Homen"
#define MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Endstop Abbruch"

#ifdef DELTA_CALIBRATION_MENU
    #define MSG_DELTA_CALIBRATE             "Delta Calibration"
    #define MSG_DELTA_CALIBRATE_X           "Calibrate X"
    #define MSG_DELTA_CALIBRATE_Y           "Calibrate Y"
    #define MSG_DELTA_CALIBRATE_Z           "Calibrate Z"
    #define MSG_DELTA_CALIBRATE_CENTER      "Calibrate Center"
#endif // DELTA_CALIBRATION_MENU

#endif // LANGUAGE_DE_H

Yes.  language_de.h changed again.

**Comment by JustAnother1** [comment]
@AnHardt   I like it.

**Comment by AnHardt** [comment]
> @AnHardt https://github.com/AnHardt I like it.

So let's have an other try. pull request will follow.

**Comment by AnHardt** [comment]
Am 28.01.2015 17:04, schrieb Andreas Hardtung:

> > @AnHardt https://github.com/AnHardt I like it.
> 
> So let's have an other try. pull request will follow.
> 
> pushed:
> make use of dispays capabillitys and fit to taste language_de.h
> https://github.com/MarlinFirmware/Marlin/pull/1430

moved #defines around to represent menu-structure and messages. extended
translation in language_de.h
https://github.com/MarlinFirmware/Marlin/pull/1431

**Comment by thinkyhead** [comment]
Characters can be changed between screen init+clears. If an umlaut character is used in the language_de.h file, for example using the Japanese character which is its equivalent on the Japanese version of the HD44780, then for Japanese displays we can convert it to the substituted code, 1-7. We only have 3 or 4 characters to play with, so only a few umlaut'ed letters will be usable.

**Comment by AnHardt** [comment]
My next attempt could lock like this.

in language.h

//#if (code to find rigth display)
#define DISPLAY_CHARSET 3
//#entif

#if DISPLAY_CHARSET==0 // long form
#define STR_Ae "Ae"
#define STR_ae "ae"
#define STR_Oe "Oe"
#define STR_oe "oe"
#define STR_Ue "Ue"
#define STR_ue "ue"
#define STR_sz "ss"
#define STR_Deg "Grad"
#endif

#if DISPLAY_CHARSET==1 // HD44870 ROM Code: A00 (Japan)
#define STR_Ae "Ae"
#define STR_ae "\xe1"
#define STR_Oe "Oe"
#define STR_oe "\357"
#define STR_Ue "Ue"
#define STR_ue "\365"
#define STR_sz "\342"
#define STR_Deg "\271"
#endif

#if DISPLAY_CHARSET==2 // HD44870 ROM Code: A02 (Western)
#define STR_Ae "\216"
#define STR_ae "\204"
#define STR_Ou "\211"
#define STR_ou "\204"
#define STR_Uu "\212"
#define STR_ue "\201"
#define STR_sz "\160"
#define STR_Deg "\337"
#endif

#if DISPLAY_CHARSET==3 // U8glib
#define STR_Ae "\304"
#define STR_ae "\344"
#define STR_Oe "\326"
#define STR_oe "\366"
#define STR_Ue "\334"
#define STR_ue "\374"
#define STR_sz "\337"
#define STR_Deg "\272"
#endif

in Language_de.h

something like:

#define MSG_MAIN    "Hauptmen"STR_ue

sadly this crashes with:

ultralcd.cpp: In function 'void lcd_tune_menu()':
ultralcd.cpp:423: warning: only initialized variables can be placed into
program memory area
ultralcd.cpp:423: error: expected `)' before 'STR_ue'

423    MENU_ITEM(back, MSG_MAIN, lcd_main_menu);

HELP!

**Comment by thinkyhead** [comment]
Looks good to me!

I think the source of your error is just a typo someplace. I just tested the concept, with `STR_ue` defined in `language.h` and `MSG_MAIN` defined in `language_en.h` as  `"Main"STR_ue` and it worked fine for me!

**Pull request closed without merging**
