### PR TITLE
Add max31865 support for heated bed

### PR DESCRIPTION
**Pull request by dbuezas**
### Description
Adds max31865 for heated bed.

### Requirements

A max31865 board connected to the bed thermistor

### Benefits

In e.g the Ultimaker2, the bed thermistor is internal to the bed.

### Configurations

Example:
```cpp
#define TEMP_BED_CS_PIN                   E1_DIR_PIN
#define TEMP_BED_SCK_PIN                  TEMP_0_SCK_PIN
#define TEMP_BED_MISO_PIN                 TEMP_0_MISO_PIN
#define TEMP_BED_MOSI_PIN                 TEMP_0_MOSI_PIN
```

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/23146

### CODE REVIEW

**Comment by dbuezas** [comment]
Obviously there's code duplication on this one, but the existing functionality for hotends is so heavy on macros that I don't see a way to reuse the code without making the problem even worse.
IMHO, the code related to these amplifiers would be better if either:
* Macros are used to generate unique functions per thermistor (bigger flash footprint, less ram and cpu)
* Less macros are used and all thermistors are handled via real parameters (smaller flash, more ram and cpu)

But I don't have test boards to validate the bigger refactoring.

**Comment by dbuezas** [comment]
Thank you for putting your time in polishing my PR

**Comment by thinkyhead** [comment]
I think I patched all the code pertaining to the bed thermistor, so please test at your earliest convenience.

Based on the code in `Temperature::read_max_tc` it appears that all hot-end thermocouples must all be of the same type when using one of the libraries rather than the built-in SPI code, so more work will need to be done at some point to make the library-based hot-end temperature sensor code more flexible.

**Comment by dbuezas** [comment]
Great, thank you. I'll test this soon.

**Comment by dbuezas** [comment]
CONFIRMED TO WORK
Works fine with my two max31865 (one on an extruder, the other ono the heated bed)

**Comment by thinkyhead** [comment]
Thank you for the confirmation. Please post followups if you discover any issues. Have a good weekend!

**Pull request merged**
