### PR TITLE
[2.0.x] Arduino Due XON/XOFF implementation

### PR DESCRIPTION
**Pull request by thinkyhead**
Package up #7936 for merge

### CODE REVIEW

**Comment by MagoKimbra** [comment]
I have tried these features on my own, until you use the serial UART for connection to HOST you can safely use serial1 to serial3 for other devices (see Nextion).
But if you use serial USART for connection to host by changing the handler call, install_isr (HWUART_IRQ, UART_ISR); the classic Serial1-serial2 and serial3 are unusable.

Host Example Uses Serial
#define MYSERIAL customizedSerial (UART)
Nextion uses Serial2
#define NEXTION_SERIAL Serial2; (USART)

All ok ...

Host uses Serial1
#define MYSERIAL customizedSerial (USART)
Nextion uses Serial2
#define NEXTION_SERIAL Serial2; (USART)

Nextion does not tell why the Handler call goes to the UART_ISR routine and not the one integrated in the variants.

The solution is like in variants to create all four serial and put the values ​​in the right ringbuffer for each serial.
But my question is worth it?
Or is there a way to change the handler call only for the USART you use? I could not find it ...

**Comment by ejtagle** [comment]
@MagoKimbra: Maybe on the hardware you are using there is just one ISR handler for all Serial ports.

`install_isr()` returns the address of the previously installed ISR, so , if needed, call chaining could be implemented. But the Arduino-native serial port implementation is quite limited.

In fact, i have myself already considered, for example, using DMA to TX chars and also RX chars, saving CPU cycles, or we could even factor out common code for all ARM based boards, instead of having different USART implementations for each one...

**Comment by thinkyhead** [comment]
Does it seem OK to merge this? If further refinements are needed, they could be done in a new PR.

**Comment by ejtagle** [comment]
OK to push. Enabling multiple instances of customSerial would only require minor modifications to the class (instead of using static variables, use per instance private variables. Not a big deal

**Comment by thinkyhead** [comment]
🤞

**Pull request merged**
