### PR TITLE
[2.0.x] Regression: Endstops Core compatibility

### PR DESCRIPTION
**Pull request by thinkyhead**
The recent endstops update broke Core kinematics endstop detection.
This PR fixes it and does some other cleanup.

### CODE REVIEW

**Comment by ktand** [comment]
There is a name clashing between SET_BIT in macros.h and the STM32Generic Arduino framework causing STM32 builds to fail.

**macros.h**
`#define SET_BIT(N,B,TF) do{ if (TF) SBI(N,B); else CBI(N,B); }while(0) `

**framework-arduinoSTM32GENERIC\STM32\system\STM32F4\CMSIS_Inc\stm32f4xx.h**
`#define SET_BIT(REG, BIT)     ((REG) |= (BIT))`

**Comment by dot-bob** [comment]
After applying update this the Y axis on my CoreXY is crashing when homing.  The X axis seems to work fine for homing just the Y axis is having issues.  Endstops are triggering and registering with M119.  It seems when it double taps on the endstop the stepper direction isn't reversing to back off on the first hit.  Reverting to prior code is fixing the issue for me.

**Comment by thinkyhead** [comment]
@ktand — Thanks for the report. That is patched now.

**Comment by thinkyhead** [comment]
@dot-bob — I'm not sure why this PR would break core homing. The logic to determine whether a particular core axis is moving was incorrect prior to this PR, and I don't see how it would prevent the homing bump.

I've done a small patch as a followup to this, but it's just cleanup so I doubt it would fix the issue. Still, give it another try, and if the issue persists we'll do more investigation.

**Comment by Studna3D** [comment]
I have the same problem.

**Comment by thinkyhead** [comment]
@ejtagle — Maybe you can spot the logical error since this change…?

**Comment by ejtagle** [comment]
@thinkyhead : There is an small bug in the code. Please check stepper::stepper_block_phase_isr()

The macro 
```
#define D_(N) motor_direction(CORE_AXIS_##N)
```

Should read

```
#define D_(N) TEST(current_block->direction_bits, CORE_AXIS_##N)
```

As calling the motion_direction() function would return old data.

(the variable last_direction_bits is being set after this block of code executes, not before. That is why the macros must access current_block-> members directly)

**Comment by ejtagle** [comment]
@Studna3D , @dot-bob : The above comment probably is the fix for the problem. If you are able to try it, please do so! ... We are trying to iron-out most of the bugs! 👍

**Comment by thinkyhead** [comment]
@ejtagle — Thanks for your sharp eye. My brain is very dull today.

**Comment by dot-bob** [comment]
Sorry it took so long to get back (work, and forced by windows to update)... Homing is now functioning fine.

**Comment by thinkyhead** [comment]
w00t!

**Pull request merged**
