### PR TITLE
Break out gcode handlers - part 1

### PR DESCRIPTION
**Pull request by thinkyhead**
- Only affects `Marlin_main.cpp`
- Incurs no extra code size or overhead
- Makes `process_commands` simpler
- Makes code easier to read and maintain

### CODE REVIEW

**Comment by galexander1** [comment]
I don't have any objections to this one. :)

I don't know if there's much benefit to factoring small ones like
M126-M129, but I don't think there's any pain in it either.

**Comment by thinkyhead** [comment]
Yeah, I figure that factoring out the handlers even for single-line actions at least exposes the implemented g-code in the interface. Though they are tied currently to the gcode processor, we can already start to see how they might be extended or even be made to run an alternate condensed form of gcode... stuff like that.

**Comment by nophead** [comment]
If you are in a tidying mood you could replace all the
&cmdbuffer[bufindw][strchr_pointer - cmdbuffer[bufindw] + 1] with
strchr_pointer + 1. They should compile to the same thing but the current
form is insanely convoluted.

**Comment by thinkyhead** [comment]
Whew! Now that I've finished moving all the gcode handling into their own subroutines, I think I'll wait till this PR gets poked and prodded a little, and hopefully merged. Then I'll replace those convoluted snippets with `strchr_pointer + 1` on the next PR.

Obviously I can't _guarantee_ that I've done a _perfect_ job of moving this code over, but I did spend a lot of time going over each handler to make sure it preserves the original behavior, and I have been comparing these to the originals as I go along, and trying to update the documentation for commands that have evolved.

For anyone wanting to compare the old and new code, Git diff is useless, but they can be compared side-by-side to see how each new handler function compares to the original code in `process_commands`. A fair amount of cleanup and improvement has been applied, and some bugs have been fixed as well.

As mentioned, I noticed along the way that the code documentation for much of the GCode is out of date, so I've done some updates in the function comments as a start. Among the issues I discovered is one apparent bug (at line 3640 in the current Marlin_main.cpp file) affecting the M600 (pause for filament change) command, which I would expect to cause the X axis to move unpredictably.

**Comment by galexander1** [comment]
I think the only thing holding up a merge is that I think we should tag a
stable first.  Any other opinions on that?  Should we just call it 1.0.3?
I don't have any preferences for how that's accomplished -- a new branch,
or a tag on the development branch, or what.

**Comment by thinkyhead** [comment]
Now is a pretty good time to add a new tag. There are no serious blocking bugs in the issue queue. We do have a bugfix for M600 pending, which we might want to apply first. (I've already applied the equivalent changes to this PR's branch).

**Comment by thinkyhead** [comment]
Ok, all pending bug patches have been applied, including the fix to M600 and updates to improve usability on DOGLCD. If we leave the code as-is for a few days, only patch up any glaring bugs that crop up, and if everything seems stable, then I think we should tag it, then merge this PR and give these updated gcode handlers a thorough round of testing.

**Comment by thinkyhead** [comment]
This seems like an opportune time to merge this, but there are just one or two annoying bugs that it would be nice to see fixed for the 1.0.3 stable tag before I go for it. I'd certainly like to get this into the hands of testers soon and catch any typos or oversights. So perhaps in a few days....

**Comment by thinkyhead** [comment]
process_commands is replaced by [lines 1419-4550](https://github.com/MarlinFirmware/Marlin/blob/0c2b2e705fe311413c3abcc3327457f57329f94d/Marlin/Marlin_main.cpp#L1419-L4550) while leaving the rest pretty much alone.

**Comment by alexborro** [comment]
@thinkyhead , If you have Skype, add me so we can exchange some ideas faster.

**Comment by thinkyhead** [comment]
@alexborro I do, also I can connect to the Marlin Firmware IRC channel if that's something you also use.

**Pull request closed without merging**
