### PR TITLE
🩹 Fixup USE_Z_MIN conditions

### PR DESCRIPTION
**Pull request by The-EG**
### Description

Since #25758, endstops are automatically chosen and certain scenarios are not handled properly. One of these cases is use of a probe with `USE_PROBE_FOR_Z_HOMING` and  *not* `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN`.

Currently, this scenario results in both a probe and Z_MIN endstops being defined. This can be confirmed by the output of `M119`. In this case, USE_Z_MIN should not be defined.

### Requirements

A probe with `USE_PROBE_FOR_Z_HOMING` that uses a dedicated probe port and not `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN`.

### Benefits

USE_Z_MIN is not automatically defined, the Z_MIN endstop is not enabled.

### Related Issues

- https://github.com/MarlinFirmware/Marlin/issues/26147#issuecomment-1685098675

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I replied on Discord, but the Z MIN state still shows up in the Endstop Test menu (`LCD_ENDSTOP_TEST`) with `Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN` disabled.

`M119` works correctly:
```
SENDING:M119
Reporting endstop status
x_min: open
y_min: open
z_probe: open
filament: TRIGGERED
```

**Comment by The-EG** [comment]
After some discussion in discord:
`M119` uses `USE_Z_MIN` and `LCD_ENDSTOP_TEST` uses `HAS_Z_MIN_STATE`. I've kept the definition of `HAS_Z_MIN_STATE` in this scenario. This is mainly due to the existence of a sanity check:

```c++
#elif Z_HOME_TO_MIN && !HAS_Z_MIN_STATE
    #error "Z_MIN_PIN, Z_STOP_PIN, or Z_SPI_SENSORLESS is required for Z axis homing."
```

Leaving `HAS_Z_MIN_STATE` undefined and bypassing the above sanity check works for both cases.

I'll update this to disable the definition of `HAS_Z_MIN_STATE` and pass the sanity check as long as `USE_PROBE_FOR_Z_HOMING` is enabled.

**Comment by thisiskeithb** [comment]
`M119` & Endstop Test menu / `LCD_ENDSTOP_TEST` both work correctly. 👍

**Review by thisiskeithb — APPROVED** [review]

**Comment by thinkyhead** [comment]
I can't think of any scenarios where the `Z_MIN_PIN` would be used in conjunction with probe-based Z min homing, and after doing a quick analysis of the change I can't see any way to simplify the `#if` statement, so this seems good.

In the cause of simplification I looked at `HOMING_Z_WITH_PROBE` to see if we could use that instead, like so…
```cpp
#if _USE_STOP(Z,,MIN,DISABLED(HOMING_Z_WITH_PROBE))
```
…but when expanding it out, it doesn't seem to be a true one-to-one equivalent. Too bad. It would have been slightly prettier.

Thanks for taking the time to sort it out!

**Comment by Bigbull666** [comment]
> I can't think of any scenarios where the `Z_MIN_PIN` would be used in conjunction with probe-based Z min homing, and after doing a quick analysis of the change I can't see any way to simplify the `#if` statement, so this seems good.
> 
> In the cause of simplification I looked at `HOMING_Z_WITH_PROBE` to see if we could use that instead, like so…
> 
> ```c++
> #if _USE_STOP(Z,,MIN,DISABLED(HOMING_Z_WITH_PROBE))
> ```
> 
> …but when expanding it out, it doesn't seem to be a true one-to-one equivalent. Too bad. It would have been slightly prettier.
> 
> Thanks for taking the time to sort it out!

Hello,
currently I am building CNC router. I need both endstops on each axis to prevent damage of my machine (I am using 12Nm steppers with ballscrews). I also need probe to set propper start position (I am using copper plate as switch temporarely placed on the top of material).

Currently I am using BBT Octopus board and all endstop ports are currently ocupied (min/max on axis X, Y, Y2 and Z). It would be nice to have option to use separate port/input for probing.

Removing Z_Min endstop could lead to damaging Z asix or working table. I would like to use separate port for Z-Probe.
Is there any other way to not use Z-Probe connected in paralel with Z-Min endstop?

Thank you.

**Pull request merged**
