### PR TITLE
Extra cartesian axis in corexy

### PR DESCRIPTION
**Pull request by serranolopez**
Regards,

I have manufactured a large corexy printer that uses a fourth axis to load the entire weight of motors, cables, bowden tubes, etc.

Its biggest advantage is that it allows to eliminate all the overweight of the extruder with a bowden system of about 30 cms long of tube in a printer of half cubic meter of size.

I need to move that fourth axis Cartesian way to accompany the movements on the X axis of my corexy printer. If possible, differentiating his steps independently. Would it be too complicated to implement in the firmware?

The mechanics have been simple but modifying the firmware by myself is driving me crazy.

Thanks in advance.

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
Marlin is made for 3 independent axis, plus n extruders.
Adding an other independent axis requires a major rewrite of the planner. This will not happen (in the near future).

**Comment by serranolopez** [comment]
I think I have not explained well. In a Cartesian printer i only need to duplicate the X axis with the X_DUAL_STEPPER_DRIVERS functionality. My problem is that I use a coreXY system to move the fuser.

i would need the X_DUAL_STEPPER_DRIVERS to use Cartesian kinetics while the rest of the system uses COREXY kinetics.

**Comment by Blue-Marlin** [comment]
Since core-kinematics is applied before distributing movements to the stepper axis i see no chance. Your additional x-axis would be independent from the a and b axis.

**Comment by serranolopez** [comment]
Sorry. Thanks for your quick response. I close the request.

**Comment by thinkyhead** [comment]
> Adding an other independent axis requires a major rewrite of the planner. This will not happen (in the near future).

Exactly what my current client is asking for. I think I may be able to work around it by not moving the new axis in tandem with the others, but only by itself, treating it as a switched extruder.

**Comment by serranolopez** [comment]
This would be interesting, in fact, I opened this request trying to contact you. I have been using this system for several years in my machines, the problem arises when you try to implement it in large printers where you can not only use mechanical advantages without motorization. It is a pity that it is so hard to modify the code without more extensive documentation. If you need some advice on its mechanical implementation feel free to contact me at josem@serrano.studio, I will be happy to save you some time in its development. Greetings.

**Comment by thinkyhead** [comment]
> i would need the `X_DUAL_STEPPER_DRIVERS` to use Cartesian kinetics while the rest of the system uses `COREXY` kinetics.

So… It's a `COREYZ` then?

> Greetings.

The system I'm building is a SCARA arm. The extra axis in my case is for a pick-and-place tool. I'll be working on this more once the tool is available to test with.

**Pull request closed without merging**
