### PR TITLE
[2.0.x] Macro G-codes

### PR DESCRIPTION
**Pull request by revilor**
This PR adds g codes M810 to M819 which allow to define g code macros.

Example usage:
- Define macro 0
  M810 G1 X0 Y0 Z0 F200|G4 S10|G1 X10 Y10 Z10

- Use macro 0
  M810
  will enqueue the g code commands
  G1 X0 Y0 Z0 F200
  G4 S10
  G1 X10 Y10 Z10

Background: for my multi-material setup based on a Prusa stepper multiplexer and a self-designed 4x Y-Splitter I needed material change procedures which are more complex than what M701 and M702 provides. As it is a very specific requirement for my setup it makes no sense to extend M701 and M702 accordingly. Instead I added a way to create macros which may be a useful feature for other Marlin users and different use cases, too.

### CODE REVIEW

**Comment by Sebastianv650** [comment]
Just because I'm curious: Wouldn't it be easier in your case to use slicers gcode on tool change section?

**Comment by revilor** [comment]
@Sebastianv650  I did exactly that so far. But let me add two more pieces for the complete picture. First, my printer has interchangeable hotends, and a E3D Volcano requires a different material change procedure than a regular E3D hotend. Second, there is a post-processing script involved which adds all the required purge tower stuff to the g code generated by slic3r. 

The script does automatic placement of the towers and I want the tool change to happen at the position of the purge towers. So far I used self-defined placeholders in the slic3r tool change g-codes which were replaced by the post-processing script with the coordinates of the purge towers. But this way the script has to scan lots of g code lines for the placeholders to replace them. To fasten things up I decided to have the script handle the complete tool change/purge tower procedure. That's where the g-code macro idea came into play because this way the script just places a single M810 when the material change should happen. What M810 means for the current print is defined in the slic3r start g-code section.

Maybe this macro stuff is complete nonsense, and I'm not sure it's a general purpose feature for Marlin, either. But it's implemented now, so if anyone has use for it, there you go.

**Comment by thinkyhead** [comment]
I've reworked this a bit to get it ready to merge. Please look over the changes and see if you want to add anything before it's merged.

**Comment by thinkyhead** [comment]
Hmm, I see that actually this cannot work without further additions.

First of all, if you use `enqueue_and_echo_command` and the command queue is full, the command will just be dropped.

If, as I attempted to do, you instead use `enqueue_and_echo_command_now` and the queue is full, the machine will go into an infinite loop and stop. This is because the next command cannot be removed from the queue until after the `M810` command has returned back to the main loop.

The correct way to deal with multiple commands is to use `enqueue_and_echo_commands_P`, which will drain them as part of the main loop. But there is no equivalent function taking non-PROGMEM strings.

So, in order to support this feature, the G-code core parser would need to be extended with an additional variable (`injected_commands_SRAM`) to contain the multi-line command to be queued by the main loop, and an additional function call (`drain_injected_commands_SRAM`) would need to be added to `get_available_commands`.

**Comment by revilor** [comment]
@thinkyhead thank you for the feedback. I'll have a look at `enqueue_and_echo_commands_P` and will implement an SRAM equivalent in the way you suggested. 

And I understand from your changes that configuration for this kind of feature should be placed into `Configuration_adv.h` and not `Configuration.h`. I'll keep that in mind.

**Comment by thinkyhead** [comment]
Most new options should go in `Configuration_adv.h`. The main configuration is gradually reducing to the settings that apply to most typical setups.

**Comment by thinkyhead** [comment]
@revilor I've finished this up but haven't yet given it a test run. Have a look at your earliest convenience. If it works as-advertised then it can get merged soon.

**Comment by revilor** [comment]
@thinkyhead I've been working on more complex extension of the command queue. To not mix it up with this PR I created a separate PR #9479. I can of course also integrate my queue extensions into this PR in case you prefer it that way.

**Comment by revilor** [comment]
@thinkyhead Thank you for your latest additions to this PR, everything works fine for me. Feel free to merge and deal with PR #9479  independently.

**Comment by thinkyhead** [comment]
> I can of course also integrate my queue extensions into this PR in case you prefer it that way.

Let's keep that separate. It needs to be more carefully considered. We have very limited SRAM to use, and the current PSTR-based method works well to keep RAM use low. A "command stack" is going to involve another large, persistent buffer, which never makes us happy. Obviously for 1284p with its generous 16K or SRAM, no problem. But most of us are still using Mega2560, and are already very close to limits.

Use `M100` a lot to evaluate its behavior.

**Comment by marcio-ao** [comment]
FYI, I suspect this implementation will suffer from one defect. When the custom macro GCODE is executed, it will enqueue the custom GCODEs after whatever may already be in the queue (which may include commands that are after the macro GCODE itself). This means that the custom macro may be executed out-of-order, in some cases.

See how I solved this problem in PR #10450 by defining a new function "execute_commands_immediate_P" which seems like a better alternative than enqueueing commands in cases like this.

I suspect the "execute_commands_immediate_P" also solves the recursion problem that you mentioned in #9479. Overall, I think the "enqueue_and_echo_commands_P" approach is fraught with problems.

**Comment by Roxy-3D** [comment]
> See how I solved this problem in PR #10450 by defining a new function "execute_commands_immediate_P" which seems like a better alternative than enqueueing commands in cases like this.

I like this.   But I would also like an equivalent execute_commands_immediate() that uses a string constructed in RAM.   Presumably execute_commands_immediate() would block until the command was done executing, and if multiple commands are needed to accomplish the developer's goal, the same character  buffer can be used again and again for the next execute_commands_immediate().

As a separate discussion...   If we have execute_commands_immediate_P() and execute_commands_immediate(), do we need the enqueue_and_echo_commands_P() family of functions?   Would it make sense to change all of those to execute_commands_immediate_P() ?

**Comment by marcio-ao** [comment]
> But I would also like an equivalent execute_commands_immediate() that uses a string constructed in RAM.

Should be trivial to do this.

> Would it make sense to change all of those to execute_commands_immediate_P() ?

It was on the back of my mind, but I didn't want to be the one to suggest such a big task -- but now you have done it for me :)

I would think that would be a logical next step, but probably makes sense to leave both in place until we learn if there are any shortcomings to execute_commands_immediate_P(). But if there isn't, the implementation of enqueue_and_echo_commands_P() is convoluted and I wouldn't mind to see it go :)

**Comment by marcio-ao** [comment]
@Roxy-3D: I do have a small concern about execute_commands_immediate_P() that perhaps you or @thinkyhead can comment on whether it is an issue.

When using enqueue_and_echo_commands_P(), all the commands would be placed on the queue, so if you had a bunch of movement commands, these would get enqueued independently and the queueing code would get to decide when to execute them.

With execute_commands_immediate_P(), there is no queuing and a single GCODE routine that calls execute_commands_immediate_P() can trigger multiple G0 commands to execute. I know that the planner has a buffer. It's not clear to me whether the command queue plays a role in avoiding that buffer from filling up, and if so, whether bypassing it could be problematic.

I've seen that many gcode routines (such as G29) issue many movements in series, so I suspect that if it isn't a problem there, it isn't a problem in execute_commands_immediate_P() either, but I thought I would ask.

**Comment by Roxy-3D** [comment]
> I would think that would be a logical next step, but probably makes sense to leave both in place until we learn if there are any shortcomings to execute_commands_immediate_P(). But if there isn't, the implementation of enqueue_and_echo_commands_P() is convoluted and I wouldn't mind to see it go :)

Agreed...    Leaving both in place allows for a methodical migration to the preferred architecture.   Changing everything all at once makes it much more difficult to resolve issues if there is a problem.   Once everything is migrated, we can delete the unused functions.

**Comment by thinkyhead** [comment]
> It's not clear to me whether the command queue plays a role in avoiding that buffer from filling up, and if so, whether bypassing it could be problematic.

The planner's current position is independent of the high-level current position, so it can handle interjected moves. But the problem is that it executes them just as if they were part of the normal cycle. So if (for example) you injected a `G1` move to home in-between two printing moves in the queue, the blocks currently in the planner would run, then your G1 move to home would run, and then the next printing move would be done starting at the home position, spilling filament into empty space. To avoid this, the planner would have to move back to wherever it was when the interjected move started before carrying on with the next move.

This problem is not limited to "immediate" commands executed ahead of the queue. Exactly the same problem exists for movement commands injected into the main G-code queue.

So you'd need to differentiate between normal and interjected moves at the planner level, and have the planner be able to return to that start position before carrying on with the next move. This could be done by adding to the planner the ability to "push" its current position and then later, to move back to that pushed position. Or, the planner could store not just the destination, but the start position of every move, and when moves don't chain up, the planner would interject a separate move.

In either case, you'd have to define some special G-codes for this purpose: One to "push" the current planner position, and one to "pull" and return to the pushed position with some feedrate.

> many gcode routines (such as G29) issue many movements in series

This is ok for procedures outside or ahead of printing moves.
During a print you have the problem I've described.

**Comment by thinkyhead** [comment]
> `enqueue_and_echo_commands_P()` is convoluted and I wouldn't mind to see it go

It is possible to replace it with `process_commands_now_P` from within G-code command handlers, but you have to watch out for blocking other functions, such as updating the LCD, getting user input, managing the heaters, queueing commands sent from the host, etc.

Commands that take a long time block `loop()` (by design). This prevents the next command in the queue from being processed. Any command that takes a long time (i.e., doesn't return right away) has to call `idle` or `manage_inactivity` periodically or many important functions won't get done. One of those functions is to get any commands waiting on the serial input or on the SD card into the queue. So, while the queue-emptier can be blocked, the queue-filler is only blocked when the queue is full, and then both serial and SD inputs are suspended.

Marlin sends a "busy signal" to hosts during times like this, and doesn't send "ok" until the busy command returns back to the main loop, and then queue processing resumes.

You won't be able to use `process_commands_now_P` from other places in the code, such as the LCD menus, unless the specific commands are very quick and non-blocking. Recursion also becomes an issue, since commands that call `idle()` end up calling `lcd_update`.

**Comment by marcio-ao** [comment]
@revilor : Sorry for jumping in to your thread and taking it on a tangent. It looks like @thinkyhead merged in "[process_subcommands_now_P()](https://github.com/MarlinFirmware/Marlin/blob/5cc7916e699a711bee82f0fbe342b7ebd80b6b37/Marlin/src/gcode/gcode.cpp#L702)". This would be a better candidate for your macro G-CODEs than enqueue_and_echo_commands() as it would solve the following things:

- This would prevent the contents of your macros being enqueued after future commands that were already in the queue prior to your macro GCODE (from a user's perspective, this would mean your macros would get executed out-of-order with respect to the order of lines of the GCODE file).
- The "ok" would be issued after your macro finished executing, rather than after enqueuing but before the macros conents were actually run.
- It also handles recursion, so I suspect PR #9479 would not be necessary.

The only changes would would need to make would be to implement an SRAM equivalent of process_subcommands_now_P(), replace your call to enqueue_and_echo_commands_SRAM() with it, and add a new stanza to "[Conditional_post.h](https://github.com/MarlinFirmware/Marlin/blob/5cc7916e699a711bee82f0fbe342b7ebd80b6b37/Marlin/src/inc/Conditionals_post.h#L1451)" to enable the USE_EXECUTE_COMMANDS_IMMEDIATE when GCODE_MACROS is defined.

UPDATE: It looks like both process_subcommands_now_P() and process_subcommands_now() would need to be updated to allow either "\n" or "|" as a delimiter, the latter being necessary for use with M810

**Comment by marcio-ao** [comment]
@revilor : I guess I'll also throw in another suggestion. It seems like currently M810 to M819 are all intended to be run-time configurable macros, i.e. they are stored in RAM. Perhaps you could make some of these static, compile-time macros instead, as I can see that both types might be useful in different occasions.

```
#if ENABLED(GCODE_MACROS)
   // To define static macros, define them here, with individual lines delimited by '\n'
   //#define GCODE_STATIC_MACRO_M810 "M117 This is a static macro M810"
   //#define GCODE_STATIC_MACRO_M811 "M117 This is a static macro M811"
   //#define GCODE_STATIC_MACRO_M812 "M117 This is a static macro M812"
   //#define GCODE_STATIC_MACRO_M813 "M117 This is a static macro M813"
   //#define GCODE_STATIC_MACRO_M814"M117 This is a static macro M814"

   // Dynamic macros are from M815 through M820 and can be changed at run-time
   #define GCODE_DYNAMIC_MACROS_SLOTS          5  // Up to 5 may be used
   #define GCODE_DYNAMIC_MACROS_SLOT_SIZE  50  // Maximum length of a single macro
#endif
```

**Comment by marcio-ao** [comment]
@reveilor: One more thought:

Perhaps the syntax for defining macros could be:

`M810 = G1 X0 Y0 Z0 F200|G4 S10|G1 X10 Y10 Z10`

The extra '=" could be used to indicate macro definition unambiguously. I am just thinking ahead to a future use case where maybe the macro invocation could actually take arguments of its own and do some type of variable substitution. A lot of thought would need to go into defining a macro language, so I am not suggesting that right now, but by having an unambiguous way to indicate definition keeps that possibility open.

**Comment by lrpirlet** [comment]
humm

I am not sure that I do like this ```execute_commands_immediate_P()``` as it may allow two **_unserialized_**  Gcode using a common resource without synchronisation... (I need to verify that assertion)

Please make sure NOT to have that enabled by default... I do NOT want to have a Gcode result printing right in the middle of another Gcode output...

**Comment by marcio-ao** [comment]
@lrpirlet : I do not think this would in fact happen. Marlin is not multi-threaded.

**Comment by thinkyhead** [comment]
G-code macros invoked from within a G-code handler and direct-executed with `process_commands_now_P` will block the G-code queue-emptier until all the commands are done executing, just in the same way that a lengthy command (like `G29`) does.

It's important to note that `G0`-`G5` moves inserted in the middle of a print job will disrupt both the current position and the planner, so you must be very, very cautious how you design and use these kinds of macros. But the same would be true if they went into the normal G-code queue.

After giving some examination to the way that `process_commands_now_P` works versus the "immediate queue" I see that there are some merits to both. You cannot run commands from just anywhere using the `process_commands_now_P` method, but it's perfectly fine for running commands from within G-code handlers. So it's an ideal method for `M810` (etc.) macros.

If it were used from the LCD menus, some bad things would happen depending on the command. For example, it would cause some mayhem if used to initiate `G29` or really any command that doesn't return right away. Even a `G1` command would cause trouble because it might wait around for several seconds until the planner has space, leading to recursion into the menu. We have ways to automatically detect and deal with LCD menu recursion, such as changing to a modal "waiting..." screen until the lcd is non-recursing. But still, for any lengthy command, it gives more predictable results to insert them into the immediate queue and continue execution so that the commands are dequeued and handled from the main loop.

At some point I'll have to flowchart all this so it's quicker to reference!

**Comment by marcio-ao** [comment]
> so you must be very, very cautious how you design and use these kinds of macros. But the same would be true if they went into the normal G-code queue.

Statements like this worry me, because not everyone has the background or understanding to make that kind of judgement. Is there anything that could be done to make `process_commands_now_P` safer? For example, you mentioned the current position and planner may get out of sync. I've come across commands like `stepper.synchronize();` and `sync_plan_position();`. Would calling something like this at the end of `process_commands_now_P` help make `process_commands_now_P` a little more robust to use or inadvertent mis-use?

**Comment by dot-bob** [comment]
I have most of my printers are tuned very similar and can use the same print profile other than the start and stop g-code.  I have been toying with the idea to have the start and end g-code of each of my printers embedded in the machine/firmware.

This may be a good use case for this pull request.  I could embed M810 in my start script and M811 for my stop script.  This would make my sliced g-code universal across all my printers similar to tool paths for CNC.

**Comment by thinkyhead** [comment]
I've rebased this and updated the code to use the `process_subcommands_now` method, added by @marcio-ao quite a while ago. This method will run everything in the macro immediately, ahead of anything else that might have been added to the queue before the `M81x` command gets to the front of the queue. So it effectively makes `M81x` an alias for the commands it contains.

Also:
- Updated all example configs added since this PR was introduced.
- Moved the Travis CI test into the Teensy tests file (which has the fewest tests).
- Moved the example config updates to a separate commit.

To obtain the updated code in your working copy…
```
git fetch origin
git checkout macro-gcodes
git reset --hard origin/macro-gcodes
```

**Pull request merged**
