### PR TITLE
Do -NOT- merge.  These changes are already  merged.

### PR DESCRIPTION
**Pull request by Roxy-3D**
@thinkyhead    THANK YOU for pausing UBL changes long enough for me to figure out how to get it up and running again.    I need these changes merged.   AND...   I don't need things 'Quiet' any longer.  Please continue and do what ever makes sense....

THANKS AGAIN!!!!

### CODE REVIEW

**Comment by Roxy-3D** [comment]
@thinkyhead    Can you resolve these conflicts?    I don't understand why they are here?

But it will be very obvious to you what is 'Good' code and what should be stripped out!!!

**Comment by Bob-the-Kuhn** [comment]
I think the conflict is because of g26_debug_flag instead of g26_**D**ebug_flag

**Comment by Roxy-3D** [comment]
> I think the conflict is because of g26_debug_flag instead of g26_Debug_flag

Oh???   Did the name change again?   Well...   I'll leave it alone...  @thinkyhead will know exactly what has to be done.   And assuming the merge happens, I'll be working tomorrow on getting the UBL map print out to be compatible with Excel so the user can graph what their bed looks like.

**Comment by ghost** [comment]
Should also work with most spre(a)dsheet programs.

**Comment by Roxy-3D** [comment]
I agree...   But I know very little about what the spreadsheet programs require.   I'll get it going with Excel and if somebody says "I need a change..."   I'll keep making the data format more robust until nobody is saying they want a change!

**Comment by JustAnother1** [comment]
@Roxy-3D The open Source  LibreOffice Calc should be an easy to test alternative to the closed source and proprietary M$ Excel

**Comment by ghost** [comment]
I wouldn't say that MS Office is proprietary, but it is closed source like StarOffice. OpenOffice and LibreOffice are open source.

**Comment by JustAnother1** [comment]
@Tannoo Wikipedia disagreees with you:
"Proprietary software is computer software for which the software's publisher or another person retains intellectual property rights — usually copyright of the source code, but sometimes patent rights."
https://en.wikipedia.org/wiki/Proprietary_software

If you ask Microsoft they will also tell you that their software is proprietary. That is their business model, they are not ashamed of it.

And yes Apache open Office would be another alternative to proprietary Excel.

**Comment by ghost** [comment]
So, would all other forms of an "office clone" be violating that? Although, MS did make an easier to use spreadsheet than Lotus 1-2-3.

**Pull request closed without merging**
