### PR TITLE
[2.0.x] Debug Travis tests and scripts

### PR DESCRIPTION
**Pull request by thinkyhead**
- Making sure the updated Travis tests and helper scripts work correctly.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
https://github.com/MarlinFirmware/Marlin/pull/11690  Should be the initial test case.

What ever care we expend to make sure things are correct before they are merged....  Things that change Travis should get 2x the scrutiny.

**Comment by thinkyhead** [comment]
Scrutinizing…

**Comment by Roxy-3D** [comment]
> Scrutinizing…

Thank You!!!

**Comment by Roxy-3D** [comment]
Now AtMega256 is broken again...  It was OK.   But it is complaining about custom boot screen.

**Comment by p3p** [comment]
@thinkyhead I don't know what issue you were fixing with the scripts, but the intention was to have the env backup/restore around each set of tests, with this modification it will try and run all the test files without that which causes issues when running all platforms sequentially.

**Comment by thinkyhead** [comment]
Thanks for catching that! That was totally unintentional.

**Pull request merged**
