### PR TITLE
2.0.x LPC1768 - M42 compatibility with Repetier Host

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
Currently,  trying to set P1_20 via M42 fails when using Repetier Host.  This is because Repetier Host deletes trailing zeros.  The result is M42 **P1.2** S0 and M42 **P1.20** S0 both are sent by Repetier Host as M42 **P1.2** S0.

P1_2/P1_20 is just one of the seven pairs or pins that have this issue. Any pin number that ends in zero has this issue.

This solution gets around the problem by 
1. Changing the names of the single digit pins.  P1_2 will be P1_02, ...
2. Changing the code so that a trailing zero is added to pin numbers received from the host with a single digit for the pin portion.  P1.2 is translated P1.20, P0.3 to P0.30, ...

This has been tested with Repetier Host and Pronterface.

----

**UPDATE**
The port/pin name being entered into the host has been changed to an integer.  Marlin internal P1_20 would be entered into the host as P120, P1_02 as P102, ...

### CODE REVIEW

**Comment by Roxy-3D** [comment]
This seems like a good work around.    It might be helpful to include an error (or warning) message inside the M42 (and M43) command if the user enters a pin number that is not 2 digits in size.   Otherwise, somebody (myself included) is going to be spending a lot of time trying to figure out why P1.2 doesn't go to the 'right' pin.

**Comment by Bob-the-Kuhn** [comment]
This code can't tell the difference between P1.2 entered in error and P1.20.   It can't send a message for just the error condition.

The best alternative I can think of is to echo the command.  Maybe something like "received M42 P1.20 S67".

**Comment by Roxy-3D** [comment]
> This code can't tell the difference between P1.2 entered in error and P1.20. It can't send a message for just the error condition.

I was thinking something like this...    Just enough to give the user a chance of figuring things out easily.  I know I will forget that pins need to be two digits...   Some warnings will save me (and others) a lot of frustration.

If they enter P1.02 everything is fine.  If they enter P1.20 and the zero gets chopped off and added back in, they still know everything is OK.  If they enter P1.2 they see the value got changed and know to add a leading 0.

```cpp
 if (sscanf(parser.strval(code), "%d.%2s", &port, pin_string) == 2) {
    if (pin_string[1] == '\0') {
      pin_string[1] = '0';   // add trailing ascii zero if a null is found
      pin_string[2] = '\0'   // add trailing null byte.
      SERIAL_ECHOPAIR("Warning:  Pin .", (int) (pin_string[0]-'0'));
      SERIAL_ECHOPAIR(" converted to: ", (int) (pin_string[0]-'0')*10);
      SERIAL_ECHO("\n");
    }
    pin = (10 * (pin_string[0] - '0')) + (pin_string[1] - '0');  // convert string to number
```

**Comment by Bob-the-Kuhn** [comment]
My concern is that they'll get the warning if 1.20 is entered in addition to being warned when 1.2 is entered.

**Comment by Roxy-3D** [comment]
Yes.   But that will only happen on Repetier Host.    And pretty much, M43 is for Developers, or users being assisted by a Developer.   

I guess to my way of thinking, a 'Warning' is just that.   In this case the firmware doesn't know if the user specified a trailing zero.  So it warns about what action it is going to take.    I would prefer to be warned than have no warning and have the firmware make the wrong assumption about what to do.

**Comment by thinkyhead** [comment]
I simply don't think it's wise to abuse `float` parameters this way, as hosts should be able to freely munge them.

How about `M42.1 P20` ? `M42 P20` would be the same as `M42.0 P20` on platforms using `port.pin` scheme.

Do any of the other MCUs have 100 or more pins? Then how about `M42 P102`, `M42 P120`? Then, all pin numbers indicate port `x/100`, pin `x%100`. It only needs to throw an error in the case where pins don't exist. And, it will be natural to convert pin numbers as-documented.

I see DUE has pins up to 107, but they are numbered normally, so on DUE we'd just use the `P[pin]` method.

And, again `M42 I[port] J[pin]` or `M42 R[port] P[pin]` isn't the worst thing either. It allows hosts to be as dumb as they like.

**Comment by thinkyhead** [comment]
Rebase, patched pins matching `[^A-Z_]P\d_\d\D`.

Since this has been rebased, don't use Github Desktop's merge. It will bring in obsolete commits. Use:
```
git fetch origin
git checkout P1.02-P1.20
git reset --hard origin/P1.02-P1.20
```

**Comment by Roxy-3D** [comment]
> Do any of the other MCUs have 100 or more pins? Then how about M42 P102, M42 P120? Then, all pin numbers indicate port x/100, pin x%100. 

'Pin' is used for 'Bit'.    So M42 P102 would translate to Port-1 Bit 2.    I don't believe the 'Pin' number has anything to do with the actual physical pin on the processor.    

I think the Ports are limited to less than 10 right now.   It would be good to double check that.   But even so, even if they go up to 200, this scheme works because we could do a M42 P20031 to get to Bit 31 of Port 200.

**Comment by thinkyhead** [comment]
Under LPC1768 the pin numbers are a little less abstract than on other platforms. The reason for pushing this scheme is that it matches all the documentation, so it's the easiest to understand in those terms. All the other platforms use single-number pin mapping based on the scheme originally pushed by arduino.cc (for the sake of simplicity).

But yes, under the hood all pins in Marlin map to a port:pin scheme, with the fastio macros being direct compile-time conversions to the port (address) and pin (bit). And functions like `digitalWrite` do the (much slower) mapping at runtime.

**Comment by thinkyhead** [comment]
> I think the Ports are limited to less than 10 right now.

A lot fewer. On the LPC1748 we have port 0-4.

**Comment by thinkyhead** [comment]
Ok, so… I added a commit to the end which:
- Fixes up a dependency issue so `MarlinConfig.h` isn't required for `pinmapping.h`. The inclusion of our magic config-plus header causes trouble when `pinmapping.h` is included in some headers.
  - That required moving things that depend on `SERIAL_PORT` to `pinmapping.cpp` and making some of the compile-time `constexpr` functions into runtime linked functions.
- Demos wasting some RAM to simplify (and speed up) pin mapping.
  - This also greatly simplifies the pin conversion macros.
- Demos a simplified integer pin mapping, where `M42 P100` corresponds to `P1_00` and `M43 S100 E302` indicates the full range of (valid) pins from `P1_00` to `P3_02`.

**Comment by Roxy-3D** [comment]
> Demos a simplified integer pin mapping, where M42 P100 corresponds to P1_00 and M43 S100 E302 indicates the full range of (valid) pins from P1_00 to P3_02.

I like the Port.Pin nomenclature....   But my vote is to go with this scheme.   It is future safe, and it isn't going to cause tons of confusion.

**Comment by thinkyhead** [comment]
I wish we could use the port.pin nomenclature, but I've seen that some other firmware (Smoothieware) actually treats 1.2 as 1.20. It's probably there specifically to accommodate hosts dropping trailing zeros. And… it's weird.

I've taken a step backward in allowing `pinmapping.h` to depend on `MarlinConfig.h` because `NUM_DIGITAL_PINS` (etc.) needs to be constant. If other `.h` files have issues due to including `pinmapping.h` we can just deal with it there.

**Comment by thinkyhead** [comment]
I do wonder… What would hosts do if we had `M42 1.20` with no letter at all? Would they treat it like M117 and just pass it through? If so, then it would be the `string_arg`. But, it would be equally weird.

**Comment by thinkyhead** [comment]
Dependencies are a trick to sort out. The file `pinmapping.h` refers to `SERIAL_PORT` but it doesn't include `MarlinConfig.h` which is required to define it. The only reason `pinmapping.h` doesn't throw an error is because `#if` statements don't require the symbols they reference to be defined.

**Comment by thinkyhead** [comment]
Ok, after much trial and tribulation, it builds. I've split `MarlinConfig.h` into two pieces. The first part (`MarlinConfigPre.h`) has all the config headers that precede the `HAL.h` include in `MarlinConfig.h`. It's suitable for situations where you want to be able to use configuration conditionals but don't want the rest.
```cpp
#include "../core/boards.h"
#include "../core/macros.h"
#include "Version.h"
#include "../../Configuration.h"
#include "Conditionals_LCD.h"
#include "../../Configuration_adv.h"
#include "Conditionals_adv.h"
```

**Comment by Bob-the-Kuhn** [comment]
I'm happy with this solution.

**Pull request merged**
