### PR TITLE
Ender 3 S1 MarlinUI Fixes

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Allow customer bootscreen dwell to view custom logo startup
Fix scrolling text by drawing a solid background over prior text
Add BG Load to clear screen to prevent artifacts in more screens

### CODE REVIEW

**Comment by ETE-Design** [comment]
@InsanityAutomation Sorry to hijack this PR, but could you also make a PR for SerMoon D1 so your work can be on Marlin's Github...

**Comment by InsanityAutomation** [comment]
A. theres still issues on the D1, its on my bench right now and B. the touchscreen code is setup as a library to drop in, and while it may eventually make it in upstream, currently changes too much to track here. 
Its one of 2 pure ExtUI implementations that can drop in as a library, the other being the code Marcio did for syndaver / lulzbot / cocoa press.

**Comment by ETE-Design** [comment]
@InsanityAutomation So you'r fixing issues for it right now? Great, cause have an SerMoon I will mount BLTouch, so have to keep an eye at your Github :-)

**Comment by tititopher68-dev** [comment]
@InsanityAutomation @thinkyhead
WARNING : You add a lot of DWIN_UpdateLCD(); -> this leads to a paralysis of the other interfaces. Have you only updated the config.txt of the DACAI screens. In all our tests before your commit, there are no weird display overlay issues with the new version of config.txt.... (Pro, crealityUI, JyersUI,...)

**Comment by thinkyhead** [comment]
Yes, I thought that might be an issue. Please patch!

**Comment by The-EG** [comment]
These changes break the status display, at least on a genuine DWIN screen, and cause flickering on the status screen.

**Pull request merged**
