### PR TITLE
ExtUI Heated Chamber support

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Extend heater functions with CHAMBER support
Add tests to DUE platform for EXTENSIBLE_UI
Fix scope issue of synchronize function thats only for SPI_LCD's

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
One thing I noticed doing this, heated chamber does not have an idle timeout. Was this intentional or should it be added?

**Comment by thinkyhead** [comment]
Do you think the heated chamber should be paused when a print is paused? It sounds like a bad idea for materials requiring a heated chamber.

**Comment by ManuelMcLure** [comment]
IMHO only the hotend should be paused. Bed and chamber should remain heated.

**Comment by InsanityAutomation** [comment]
I would agree for pause during a print job and such, I bring it up primarily because I would think it's also a bad idea for the bed yet the idle timer stuff for the bed exists. For consistency's sake I considered if it was desirable. Could have an idle timeout when the print job timer is not paused so that somebody doesn't accidentally leave the chamber heated for 3 days with nothing going.... 

Just an observation and passing thought though. I'll leave things as they are and just ignore it for now unless somebody asks for it specifically.

**Pull request merged**
