### PR TITLE
Reactivate tests for more extruders in Travis

### PR DESCRIPTION
**Pull request by AnHardt**
BOARD_ULTIMAKER was not the default any more - sed failed to change the
board - RAMPS_EFB has no second extruder - ...

### CODE REVIEW

**Comment by Wackerbarth** [comment]
This is already handled in PR #2269 and creates a conflict with it.

**Comment by AnHardt** [comment]
Ideally **all** boards are tested.
Until now nobody cared about this enough to integrate all.
My choice here was driven by the thought, to test the standard Configuration.h and to make as few changes as possible to make a maximum of **working** tests.

**Comment by Wackerbarth** [comment]
From a practical POV, it is rather wasteful to do a full CI testing for our environment.
Rather, having a few tests that are likely to catch obvious problems run for each PR and additionally having a more comprehensive suite that can be run as a gatekeeper to the actual integration is a more realistic approach.

Additionally, we should be trying to reduce the number of different (but almost the same) board declarations. Partially this can be helped by defining the configurations in a modular fashion.

But that kind of change will take time and should be designed as a part of some future version.

**Comment by thinkyhead** [comment]
> we should be trying to reduce the number of different (but almost the same) board declarations

Indeed. We just got rid of the Witbox and Hephestos "boards" because they aren't actually boards. The remaining boards are mostly unique, with a half dozen RAMPS variants. It will be quite tricky to reduce them further, because each of the boards currently existing is unique in some way.

**Comment by Wackerbarth** [comment]
"a half dozen RAMPS variants. ...  each of the boards currently existing is unique in some way."

We need to be describing them with a single common description plus a short set of differences rather than pretending that each board is totally a thing unto itself.

**Comment by thinkyhead** [comment]
> a single common description plus a short set of differences

As always, go for it. Submit a PR.

**Comment by AnHardt** [comment]
Will work again when the beeper code is repaired. Merge #2304 or #2307 first - than retest Travis here.

**Comment by thinkyhead** [comment]
Re-running the test after merging #2307. Hopefully it gets the update….

**Comment by Wackerbarth** [comment]
@AnHardt -- I rebased this to handle the changes we made yesterday. GitHub wouldn't let me post a pull request against your repository. But you can pull the change from mine (Wackerbarth:Travis-moreExtruders). All of these tests now pass.

However, I consider this method of handling the tests to be EXTREMELY fragile since the environment for one test depends on the setup of the previous test. Editing files in place is NOT a good methodology.

**Pull request closed without merging**
