### PR TITLE
Renkforce RF100 (V1), V2, XL, and XL Plus configuration files

### PR DESCRIPTION
**Pull request by dok-net**
This PR provides the configuration files for the Conrad Renkforce RF100 printers version 1 and 2.
The settings are the culmination of work by various authors, the current state has been extensively tested with both PLA and PETG on an RF100 V1, and somewhat on a V2 against Marlin release 1.1.9. The only pertinent difference from V1 to V2 is the extended build volume of the printer hardware.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Do these really use RAMPS 1.3 layout? Most boards use 1.4. The main clue is the first `SERVO_PIN`. If it's 11 then you have a 1.4 board. If it's 7 then you have a 1.3 board.

**Comment by dok-net** [comment]
@thinkyhead [Page 4 of Renkforce RF100 PCB documentation](https://produktinfo.conrad.com/datenblaetter/1500000-1599999/001522161-an-01-en-EINBAU_RF100_ERSATZTEIL_HAUPTPLATINE.pdf) has an image of it. I take it, that D11 SERVOS in the lower right corner is the indication that this PCB is indeed a RAMPS 1.4? I'm taking the clue and commiting the change to RAMPS_1.4 in advance of your confirmation :-)

**Comment by dok-net** [comment]
*sigh* 2.0.x "bricks" the printer. Reflashing to 1.1.9 works, fortunately. I have backported our recent changes to 1.1.9.

**Comment by thinkyhead** [comment]
> sigh 2.0.x "bricks" the printer

Try a minimal install and see how it fares. This is rebased and configs updated, so it's ready to use. To update your working copy use the git console and do…
```
git fetch origin
git checkout bugfix-2.0.x_renkforce_rf100
git reset --hard origin/bugfix-2.0.x_renkforce_rf100
```

**Comment by dok-net** [comment]
@thinkyhead
Update: LOL - my bad. Must have slipped in. Fixed in #16017:


Double checking for FAN_PIN, is that on (copy&paste safety) purpose?
`Marlin/src/pins/ramps/pins_RAMPS.h`:
```
#ifndef FAN_PIN
  #if EITHER(IS_RAMPS_EFB, IS_RAMPS_EFF)          // Hotend, Fan, Bed or Hotend, Fan, Fan
    #ifndef FAN_PIN
      #define FAN_PIN      RAMPS_D9_PIN
    #endif
```

**Pull request merged**
