### PR TITLE
Tower angles calibration for Delta's - M665 B(bed radius)

### PR DESCRIPTION
**Pull request by LVD-AC**
- Refinement to delta autocalibration routine including tower angle corrections
- Delta probe grids upto 7*7 points
- Made M665 compliant with RepRap Wiki (Repetier and Smoothieware)

### CODE REVIEW

**Comment by LVD-AC** [comment]
I do not know what those conflicts are???

**Comment by Bob-the-Kuhn** [comment]
I don't like using the **Resolve conflicts** button on the PR.  I'd much rather use my preferred text editor so the method I use is in the **Make the PR pretty & sync to main repository** in the guide you used to get here.

Basically what it does is try to bring the proposed code up to date with RCBugFix.  That should result in the same conflicts as above.

**Comment by LVD-AC** [comment]
@Bob-the-Kuhn that didn't seem to go well - where did my go commits disappear to

**Comment by Bob-the-Kuhn** [comment]
I haven't seen that before.

Can you still see something when you're in your local repository?

Does the history tab for that branch in Git Desktop show anything?

**Comment by Bob-the-Kuhn** [comment]
@thinkyhead - can you help here?

**Comment by LVD-AC** [comment]
No, desktop shows no changes or commits - and local files in my work dir have been restored (and I didn't make a backup)

**Comment by teemuatlut** [comment]
@LVD-AC Hey, I had intended to help you out with the merge and I made a local copy of your fork. You can still get it from my repo [here](https://github.com/teemuatlut/Marlin/tree/LVD-Delta). It's a couple of days old but at least it still mostly there. Commit history and everything. [Here's](https://github.com/MarlinFirmware/Marlin/compare/RCBugFix...teemuatlut:LVD-Delta) the diff too.

**Comment by LVD-AC** [comment]
thanks @teemuatlut ; I did recreate the PR in #6410

**Pull request closed without merging**
