### PR TITLE
Fix thermal protection min max code

### PR DESCRIPTION
**Pull request by ghost**
Fix the thermal protection raw min/max code, plus make the compiled code smaller if more than one hot end is present.

Currently the code just **does not work**, it's got the raw ADC analysis wrong, it should be treating the raw ADC values as the inverse of temperature (which it is currently not doing).

As temperature goes up, raw ADC values go down.

### CODE REVIEW

**Comment by gloomyandy** [comment]
I'm struggling to see what was wrong with the old code didn't the TEMPDIR macro take care of thermistors that have raw values that drop as temperatuire increases? It looks like that is how it was intended to work? Also I don't see how your new code works if you have a termistor that has a raw value that increases with temperature.

**Comment by ghost** [comment]
You have to go with what you think is best really, we can only guide you into having a working firmware, which we would then consider using in our printers, but as yet we can't.

Maybe start with having a look at your **temp_range[x].raw_min** and **temp_range[x].raw_max** values after initialization, and move on from there ?

**Comment by gloomyandy** [comment]
Sigh... I've told you this before, this is not my code, please stop referring to it as if it is. I have no more control over what goes into Marlin than you do, my only contact with this project is that I've made a few contributions in the past. I'm just trying to help by providing input on PRs that look interesting to me, like this one. That way hopefully we all end up with a better version of Marlin.

I was just asking for an explanation as to what it is that is wrong with the exiting code. It looks to me as if the major functional difference in this PR is that you have dropped the use of TEMPDIR. It seems to me as if the TEMPDIR macro should allow the use of thermistors that have both positive and negative slopes. Is there a problem with it? In addition I don't see how the new code handles both cases? Perhaps it does not matter and there are no temperature sensors with a positive slope?

**Comment by gloomyandy** [comment]
But anyway I've taken a look at the values you suggested (by printing out the values and the loop that computes them) and with my Thermistor (A type 5) then I get the following for min...
```
Initial values target 300.000000 actual 0.000000 raw 16383 tempdir -1
target 5.000000 actual 0.000000 raw 16383 tempdir -1
target 5.000000 actual 0.000000 raw 16367 tempdir -1
target 5.000000 actual 0.000000 raw 16351 tempdir -1
target 5.000000 actual 0.000000 raw 16335 tempdir -1
target 5.000000 actual 0.000000 raw 16319 tempdir -1
target 5.000000 actual 0.000000 raw 16303 tempdir -1
target 5.000000 actual 0.000000 raw 16287 tempdir -1
target 5.000000 actual 0.000000 raw 16271 tempdir -1
target 5.000000 actual 0.000000 raw 16255 tempdir -1
target 5.000000 actual 0.000000 raw 16239 tempdir -1
target 5.000000 actual 0.000000 raw 16223 tempdir -1
target 5.000000 actual 0.000000 raw 16207 tempdir -1
target 5.000000 actual 0.000000 raw 16191 tempdir -1
target 5.000000 actual 0.000000 raw 16175 tempdir -1
target 5.000000 actual 0.062500 raw 16159 tempdir -1
target 5.000000 actual 1.062500 raw 16143 tempdir -1
target 5.000000 actual 2.062500 raw 16127 tempdir -1
target 5.000000 actual 3.062500 raw 16111 tempdir -1
target 5.000000 actual 4.062500 raw 16095 tempdir -1
Final values: actual 5.062500 raw 16079
```
Which all looks pretty good to me. However the output for the max raw value is not so good...
```
Max temp 300
Initial values target 300.000000 actual 0.000000 raw 0 tempdir -1
Final values: actual 0.000000 raw 0
```
But looking more closely I think that this is a problem with the call to analog_to_celsius_hotend not correctly handling the case of a raw value of 0. Looking at the history for this it seems that there was a recent fix (https://github.com/MarlinFirmware/Marlin/pull/14080). The original fix (https://github.com/MarlinFirmware/Marlin/pull/14080/commits/9b4b14e294dd57554ee6bf7030d8d15f50ccea78) had code that looked like...
```C
#define SCAN_THERMISTOR_TABLE(TBL,LEN) do{                             \
  uint8_t l = 0, r = LEN, m;                                           \
  for (;;) {                                                           \
    m = (l + r) >> 1;                                                  \
    if (m <= 0) return (short)pgm_read_word(&TBL[0][1]);               \
    if (m == l || m == r) return (short)pgm_read_word(&TBL[LEN-1][1]); \
    short v00 = pgm_read_word(&TBL[m-1][0]),                           \  
```
But later on @thinkyhead changed the code (https://github.com/MarlinFirmware/Marlin/pull/14080/commits/a80d6f344c65e30852080e17150ff60cfb2af419 ) to...
```C
#define SCAN_THERMISTOR_TABLE(TBL,LEN) do{                             \
  uint8_t l = 0, r = LEN, m;                                           \
  for (;;) {                                                           \
    m = l + r;                                                         \
    if (!m) return (short)pgm_read_word(&TBL[0][1]);                   \
    m >>= 1;                                                           \
    if (m == l || m == r) return (short)pgm_read_word(&TBL[LEN-1][1]); \
    short v00 = pgm_read_word(&TBL[m-1][0]),                           \
```
Which I think has broken the original fix. Reverting that change I get the following search result...

```
Max temp 300
Initial values target 300.000000 actual 713.000000 raw 0 tempdir -1
target 300.000000 actual 713.000000 raw 0 tempdir -1
target 300.000000 actual 713.000000 raw 16 tempdir -1
target 300.000000 actual 687.187500 raw 32 tempdir -1
target 300.000000 actual 661.375000 raw 48 tempdir -1
target 300.000000 actual 635.562500 raw 64 tempdir -1
target 300.000000 actual 609.750000 raw 80 tempdir -1
target 300.000000 actual 583.937500 raw 96 tempdir -1
target 300.000000 actual 558.125000 raw 112 tempdir -1
target 300.000000 actual 532.312500 raw 128 tempdir -1
target 300.000000 actual 506.500000 raw 144 tempdir -1
target 300.000000 actual 480.687500 raw 160 tempdir -1
target 300.000000 actual 454.875000 raw 176 tempdir -1
target 300.000000 actual 429.062500 raw 192 tempdir -1
target 300.000000 actual 403.250000 raw 208 tempdir -1
target 300.000000 actual 377.437500 raw 224 tempdir -1
target 300.000000 actual 351.625000 raw 240 tempdir -1
target 300.000000 actual 325.812500 raw 256 tempdir -1
Final values: actual 300.000000 raw 272
```
Which again now looks OK to me. 

So it seems to me that the original code that can handle both positive and negative slopes in the conversion may have been fine. But it looks like there may have been a bug introduced into the previous fix to analog_to_celsius_hotend.

Have you seen other problems?

**Comment by thinkyhead** [comment]
I've patched the `SCAN_THERMISTOR_TABLE` macro to fix [the error](https://github.com/MarlinFirmware/Marlin/pull/14080/files#diff-b19d32f773d8fe238e852950727c2681R1194). Only meant to get rid of the signed comparison warning, but forgot that `1 >> 1` yields 0. Oops!

**Comment by gloomyandy** [comment]
@thinkyhead Although the SCAN_THERMISTOR_TABLE was definitely the problem I saw, I'm not sure if there are other problems that @doggyfan changes address. I'd like to understand more about the problems that he was seeing with the original code.

**Pull request closed without merging**
