### PR TITLE
Replace separating char for filename scrolling

### PR DESCRIPTION
**Pull request by XDA-Bam**
### Description

Replace separating char for filename scrolling. The current choice '.' always looks like part of the filename at first glance. The suggested char '|' is not allowed as part of filenames in most file systems and therefore is a better separator.

### Requirements

LCD and `STATUS_MESSAGE_SCROLLING` enabled.

### Benefits

Beginning and end of scrolled file name easier to recognize.

### Configurations

None.

### Related Issues

None.

### CODE REVIEW

**Comment by rhapsodyv** [comment]
I think '.' is better because it gives the idea of continuation... 
And it seems to be a standard for text scrolling...

**Comment by XDA-Bam** [comment]
Yes, it's common to have three dots and following spaces. The problem with Marlin scrolling - at least in the cases I have seen on my screen - is, that there is only one or two dots between the end and the beginning of the scrolled filename and zero spaces. And in that case, dots are just bad to read, because they are also used to mark the file type and - depending on your naming scheme - appear in version numbers or dates.

Currently it looks like this:
```
Super_long_filename_to_print_v1.0.gcode..Super_long_filename_to_print_v1.0.gcode..Super_long_filename_to_print_v1.0.gcode
```
I think that is just too cramped and not clearly separated. I would be much happier with either the suggested
```
Super_long_filename_to_print_v1.0.gcode||Super_long_filename_to_print_v1.0.gcode||Super_long_filename_to_print_v1.0.gcode
```
or something like
```
Super_long_filename_to_print_v1.0.gcode... Super_long_filename_to_print_v1.0.gcode... Super_long_filename_to_print_v1.0.gcode
```
Both of which are much easier to read on the small display.

**Comment by thinkyhead** [comment]
I would suggest `-` rather than `|`. The ` ` (space) character can also work if there are enough of them.

**Comment by XDA-Bam** [comment]
```
Super_long_filename_to_print_v1.0.gcode--Super_long_filename_to_print_v1.0.gcode--Super_long_filename_to_print_v1.0.gcode
```
Looks only marginally better to me. Space works better:
```
Super_long_filename_to_print_v1.0.gcode  Super_long_filename_to_print_v1.0.gcode  Super_long_filename_to_print_v1.0.gcode
```
Maybe something like
```
Super_long_filename_to_print_v1.0.gcode, Super_long_filename_to_print_v1.0.gcode, Super_long_filename_to_print_v1.0.gcode
```
where the first separator is `,` and all following are ` ` (space) would look even better?

**Pull request merged**
