### PR TITLE
resolve #13274: expose SD_AUTO_START

### LINKED ISSUE #13274: [BUG] MKS SBASE: expose controller sd card to host as mass storage device
1. **PROBLEM**
here: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/pins_MKS_SBASE.h#L157
a combination of options:
```
#define USB_SD_ONBOARD
#define LPC_SD_ONBOARD
```
is supposed to expose controller sd card to host as mass storage device,
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/pins_MKS_SBASE.h#L221
which does not work, due to
```
  #define SS_PIN           P0_06   // Chip select for SD card used by Marlin
  #define ONBOARD_SD_CS    P0_06   // Chip select for "System" SD card
```

2. **SOLUTION**
borrowing similar snippet from
https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/pins/pins_BIGTREE_SKR_V1.3.h#L213
```
  #define SS_PIN           P0_16   // Chip select for SD card used by Marlin
  #define ONBOARD_SD_CS    P0_06   // Chip select for "System" SD card
```
now makes it work for MKS SBASE: sd card does show up on host as block device

3. working configuration snapshot
https://github.com/random-builder/Marlin/commit/2e4ab83204541d2a7b214feb1b2eac490b302ef7

### PR DESCRIPTION
**Pull request by Andrei-Pozolotin**
### Description

expose for users `SD_AUTO_START` as part of `Configuration_adv.h`

### Benefits

reduce confusion, i.e. #13274, improve configurability.

### Related Issues

See #13274

### CODE REVIEW

**Comment by gloomyandy** [comment]
Although the comments about mass storage etc. are valid (and why this PR has been created). I'm not sure that they really describe what exactly this option means. So for instance my understanding is that it defines if the Marlin SD autostart capability is used on boot. This capability will
1) Attempt to mount the SD card.
2) Run any autostart gcode from that card.
what happens with mass storage is really a side effect of step 1.

I also think it is worth documenting all possible outcomes here:
#define SD_AUTO_START true // always attempt to do autostart
#define SD_AUTO_START false // never attempt to run autostart
#define SD_AUTO_START DISABLED(ULTRA_LCD) // run autostart if no LCD or if SD card has a detect pin and that pin is triggered.
At the moment no mention is made of the "true" option. Some folks may actually want if they have an LCD with no sd detect pin.

Can anyone explain why the current logic is the way it is? I don't really understand why:
a) the decision over running the autostart is devolved to the LCD (when one is available)?
b) why if no SD detect pin is available the LCD does not run the autostart (even though we try and run it anyway if no LCD is being used)?
I'm not saying that what we do is wrong, there may be a very good reason for it, I'd just like to understand what it is!

Oh and there is also the question of should it be possible to control the mounting of the card separately from running the autostart gcode? But perhaps that is a step too far?

Sorry for the ramble!

**Comment by thinkyhead** [comment]
> the decision over running the autostart is devolved to the LCD

The SD and LCD initialization take some time, so the "firing" of the SD mounting attempt occurs in the 100Hz LCD handling part of the code. The SD card has long been associated with LCD as a set of accompanying or integrated peripherals, both using SPI, generally, so that may also have some bearing on the historic location of this code. The still valid technical advantage is that if the SD check were done in some other area of the code, it would be executed more often and use up more CPU cycles.

**Comment by thinkyhead** [comment]
This PR misunderstands what is going on in Marlin. If there is no LCD the autostart handling is in one place (adjunct to the main loop). But if there is an LCD then the handling of autostart is done in a different place (in the 100Hz LCD handler). Thus, the SD card mounting and autostart handling is always done, whether there is an LCD attached or not.

**Comment by gloomyandy** [comment]
> Thus, the SD card mounting and autostart handling is always done, whether there is an LCD attached or not.

@thinkyhead This is not correct. The SD card is not mounted by the LCD code if there is no SD detect pin defined. But it will always be mounted if no LCD is present. This may not be intentional, but it is how it works at the moment. You can see this in the code here: https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/ultralcd.cpp#L702

I think there is a need to allow a user to specify what happens with the SD card on boot. Should it be mounted or not. Can you suggest a better way of achieving this (given the involvement of the LCD)? This control is needed on some 32bit systems because the SD card can be (and often is) shared between Marlin and a PC, but it is only safe to have one of those in control of the card. Some users like to have the card available to the PC on boot, others want it mounted by Marlin. At the moment we have a situation that is confused and is different depending on if you have an LCD or not. This does not seem a very good solution.

**Comment by thinkyhead** [comment]
It should be mounted as soon as it is safe to do so. The LCD waits for the detect pin. Without the detect pin, the card must be mounted manually. It may or may not be safe to periodically attempt to mount the SD card when there is no SD detect pin. It's unclear when it is safe to mount the SD card in the boot process, but attempting it once at the end of `setup()` has been the standard workaround for unresponsive SD cards.

**Comment by gloomyandy** [comment]
That may well be correct, but the thing is that with no LCD the card will be mounted as part of the start up code. It seems inconsistent that it is ok to mount the card with no sd detect pin when there is no LCD but not so when there is. Is this behaviour intentional? If not then perhaps the start up code used when no LCD is present should be amended so that it does not mount the SD card (and perform autostart) if no sd detect pin is present. 

I still think that there should be an option for the user to choose if the SD card should be mounted at all at system startup. As described above when that card is being shared via USB it seems reasonable to have that choice. It also seems reasonable to force the mount if the user wants that even if there is no sd detect pin.

**Comment by thinkyhead** [comment]
If you would like to make improvements in the SD code, please do so. It is old and crufty. I have too much on my plate to jump into a reform of that code right now.

**Comment by gloomyandy** [comment]
OK when I get chance I'll take a deeper look at it and try and understand it a little better than I do at the moment! Thanks for the feedback.

**Pull request closed without merging**
