### PR TITLE
Allow negative retract values in the LCD

### PR DESCRIPTION
**Pull request by FHeilmann**
This can already be done via G-Code, so adding the capability to the LCD should be straight forward.

Possibly, `MSG_CONTROL_RETRACT_RECOVER` has to be changed to reflect this (remove the "+")

### CODE REVIEW

**Comment by Blue-Marlin** [comment]
You could try `float32`.

**Comment by FHeilmann** [comment]
Sure, I merely adjusted the limits of the existing code.

**Comment by thinkyhead** [comment]
Submitted some changes at FHeilmann/Marlin#8

**Comment by FHeilmann** [comment]
Thanks! Merged

**Pull request merged**
