### PR TITLE
piston extruder 5339

### PR DESCRIPTION
**Pull request by BillStruve**
##Why (short version)
Printing by extruding a paste with a stepper motor driven piston does not require
temperature control of the extruder head or the bed.

It does require control of a fan to dry the paste after extrusion.
When not dried, the print will collapse when it is tall.
The manufacturer provides a warm air blower fan for this.
	M35 turns fan on, M36 turns fan off.
	
It also requires a means of adjusting the extrude rate during printing.
The manufacturer has provided a pot with a knob for the user.
	M37 A# - turns on/off the E multiplier Adjustment
	M37 S# - turns on/off Showing of the E multiplier
	M37 R##.# - adjusts the sensitivity of the knob (%)
		equation: y = mx + b  where y = multiplier,
		m = R/100/512,  x = ADC reading, b is calculated
		assuming (max x)/2 = 512 and at the midpoint of the
		adjustment, the multiplier will be 1.000
	
##What (overview)
Configuration.h
	add a section for a piston extruder printer
	add 2 defines to direct compiler
	add 2 default values
Marlin.h
	add 6 extern vars for use in Marlin_main.cpp,
		planner.cpp, and temperature.cpp
Marlin_main.cpp
	set initial values for vars
	add descriptions for M35, M36, and M37
	add code for M35, M36, and M37
	add case's for M35, M36, and M37
enum.h
	add a Prepare/Measure pair for ADC
pins_RAMPS.h
	define a pin for the dryer fan
	define a pin for the ADC input
planner.cpp
	alter extrusion with E multiplier
temperature.cpp
	setup for analog read
	use analog read to calculate E multiplier
	provide user feedback of E multiplier
example_configurations
	add MMM folder
	add a specific Configuration.h to MMM folder

### CODE REVIEW

**Comment by boelle** [comment]
@thinkyhead should @BillStruve not rebase this on RCBugfix?

what got my attention is: from BillStruve:RC

**Comment by BillStruve** [comment]
Unlike programming, I have no idea what I'm doing in git. Studied it a week, but must be missing some basic concept. Seem to be able to handle git locally, but when it comes to remote stuff, I'm lost.

**Comment by boelle** [comment]
i guess you have forked Marlin:RC made the changes and then wanted to submit the PR to Marlin:RCBugfix?

**Comment by BillStruve** [comment]
Did not know how to fork from RCBugFix - tried several things without success.

**Comment by BillStruve** [comment]
Yes, I want my pull to go to RCBugFix, and cloned that on my PC and made the changes to it.

**Comment by boelle** [comment]
select rcbugfix and hit clone/fork?

**Comment by boelle** [comment]
what you have on your pc is RC and not RCBugfix. When you submit a PR it tell github what you have cloned and where you want the PR to go

**Comment by BillStruve** [comment]
The clone link from github did not seem to give me a branch option, so how is it set?
git clone https://github.com/MarlinFirmware/Marlin.git

**Comment by boelle** [comment]
http://imgur.com/a/eSMVN

**Comment by BillStruve** [comment]
OK hope this does not mean I need to start over...

**Comment by boelle** [comment]
there is a rebase command, but i know as little as you when it comes to git. i edit stuff directly from the webpage. but @thinkyhead should be able to guide you in the right direction once he is arround

**Comment by BillStruve** [comment]
Thanks Bo.

**Comment by BillStruve** [comment]
Bo, I deleted the fork and made a new one from RCBugFix. When I push to the
link in the Clone button of my fork, it takes in the commits from my PC.
Now, the pull request is OK.
Command for push:
git push https://GitHub.com/BillStruve/PistonExtruder.git

**Comment by thinkyhead** [comment]
Has a new PR been made for this?

**Comment by BillStruve** [comment]
Not yet,, awaiting your answers to the above, then it will take some time to revise the code and test.

**Comment by BillStruve** [comment]
@thinkyhead  What on earth does the **D'oh** label mean?

**Comment by thinkyhead** [comment]
Wrong issue. Should have been on the tab next to it.

**Comment by BillStruve** [comment]
OK, I'll get to work - may be awhile, need to get some stuff done for my talk at ISGB in Las Vegas on 3D printing.

**Pull request closed without merging**
