### PR TITLE
Pinda v2

### PR DESCRIPTION
**Pull request by tompe-proj**
### Requirements

* Heated bed with temperature sensor
* Z-probe with temperature sensor (e.g. P.I.N.D.A V2)
* Spare input for the probe thermistor

### Description

I mainly print ABS with enclosure and experienced inconsistent first layer. Therefore I added my spare P.I.N.D.A V2 probe (from original MK3S) to the system. Thermistor of probe is simply connected where usually the thermistor for a second extruder goes (Note: for tests one can also zip-tie a spare thermistor to a standard probe).
Therefore, first changes were to add temperature readings for a probe thermistor.
When running G29, after each probe the temperatures will be read and according compensation values will be added to the measured z-value. There are three tables (bed/hotend/probe), whereas each holds compensation values for a range of its temperatures.
In order to find these values I initially planned to simply copy the Prusa MK3 P.I.N.D.A calibration process. However, this process does not even work properly on my original MK3S and I honestly think Prusa does not care too much about this feature so I came up with my own but similar process. Also I found that different bed temperatures significantly effect first layer so I included it in the calibration process. For the sake of completeness I also added a table for hotend temperatures but no auto-calibration. Values for hotend have to be added manually. (calibrate: G76, modify values: M871).

For calibration it is important that while one component gets calibrated, the others temperature is held constant. E.g. when calibrating probe, bed temperature is held constant (100°C). First z-probing is always the base value (e.g. probe at 30°C), following probes will then calculate the delta (i.e. the relative error due to temperature change of probe). E.g. second probe (probe at 35°C) will measure a delta of 5um, therefore if I ever do a bed leveling and my probe measures 35°C I would have to subtract this value from the measured_z. This relative errors are the compensation values that will then be stored in a table.
When calibrating bed temperatures, we first park the print-head in a position where the probe can cool down below 30°C, then move it to the probe point close to the bed and wait until it reaches 30°C, finally do the probing. Doing this over and over again allows to measure different bed temperatures at constant 30°C probe temperature.

**Probe calibration:**
Note: make sure fans are not blowing at probe or it will not heat up enough, we should at least reach 45-50°C to get enough data for a linear regression and extrapolation to be somewhat accurate
 * Move probe to cooldown point.
 * Heat up bed to 100°C.
 * Move probe to probing point (1mm above heatbed).
 * Wait until probe reaches target temperature (30°C).
 * Do a z-probing (=base value) and increases probe target temperature by 5°C.
 * Wait until probe reaches increased target temperature.
 * Do a z-probing (delta to base value will be a compensation value) and increases probe target temperature by 5°C again.
 * Repeats last two steps until max. temperature reached or timeout (i.e. probe does not heat up any further).
 * Missing compensation values of higher temperatures will be extrapolated (using linear regression first). Note: While this is not exact by any means it is still better than simply using the compensation value of highest temperature in table.

**Bed calibration:**
Note: heating up the probe to 30°C should be no problem, even at a bed temp. of 60°C (otherwise shield probe from fans again)
 * Move probe to cooldown point.
 * Heat up bed to 60°C.
 * Move probe to probing point (1mm above heatbed).
 * Wait until probe reaches target temperature (30°C).
 * Do a z-probing (=base value) and increases bed temperature by 5°C.
 * Moves probe to cooldown point.
 * Wait until probe is below 30°C and bed has reached target temperature.
 * Move probe to probing point and waits until it reaches target temperature (30°C).
 * Do a z-probing (delta to base value will be a compensation value) and increases bed temperature by 5°C.
 * Repeat last four points until max. bed temperature reached (110°C) or timeout. Note: Not sure if some people might get a "heating failed" error before the timeout in case their bed is unable to reach such high temperatures.
 * Missing compensation values of higher temperatures will be extrapolated (using linear regression first). Note: While this is not exact by any means it is still better than simply using the compensation value of highest temperature in table.

**Command examples:**
G76 // calibrate bed and probe values
G76 P // calibrate probe values only (B for bed only)
M871 // print current compensation values [um]
M871 P I1 V-5 // Set probe value at index 1 to -5um (B for bed)

**Note:**
I´m not a professional when it comes to Marlin, in fact this was my first time changing more than just the config files. There might be errors in it or simply malfunction due to a different setup that I had not thought about. However, I thought this might be useful for others so I would like to share it.
In case there are any questions feel free to contact me.

### Benefits

Adding support for z-probes with a thermistor (e.g. P.I.N.D.A V2) and a way to calibrate first layer temperature calibration values (will then be used with G29).

### Related Issues

More consistent first layers at various bed and probe temperatures.
P.I.N.D.A V2 support in Marlin was already requested as a feature before.

### CODE REVIEW

**Comment by tompe-proj** [comment]
I just realised that almost all checks failed. This is probably because in the pins files, the define for the thermistor pin is missing. I added following lines only to the pins_BTT_SKR.h file (where it succeeded) as I use a BTT_SKR_V1_3.

#if ENABLED(USE_TEMP_COMPENSATION)
  #define TEMP_PROBE_PIN TEMP_1_PIN
#endif

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR. It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by drphil3d** [comment]
I didn't know where to ask this question so I'll put it here. I've been looking through the repo and searching google to see if marlin has support for I2c digital tempature sensors. I've been thinking alot about measuring probe tempature and I've realized it's kinda difficult to do this when using a board like the SKR mini e3 or for that matter most boards that only have 2 thermistor ports without external circuitry for a thermistor.  I figured instead of using the PINDA probe which has its limitations (2 mm sensing range), why not use a DS18B20 Digital Temperature sensor via I2C taped to the tip of the probe and or epoxy it in place / print a cover to insulate everything.

For a majority of use cases it should work, the DS18B20 has a max operating tempature of 125c.

**Comment by AnHardt** [comment]
[DS18B20](https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf) is not I²C it's  1-Wire bus.
We don't support  1-Wire bus, because it has a protocol with a relatively strict timing and non(e) of our supported processors has something like a 1-Wire bus hardware support. We'd have to bit-bang. We had to decide if we want to read the sensor or if we want to step in time.

Forget it.

**Comment by drphil3d** [comment]
Ohh I see, that makes sense

**Pull request closed without merging**
