### PR TITLE
Bugfix_2.0.x - fix ultralcd.cpp compile error (int* to int16_t*)

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Bob, do you know why Travis doesn't work any more on the bugfix branches?

**Comment by fiveangle** [comment]
arduino core can't be used on lpc* and other 32 bit targets, so p3p pushed his travis yaml config to the bf20 branch which uses PlatformIO (for all targets), and it needs some tweaking.  It definitely is "working"; it's just not all the targets are succeeding.

**Comment by fiveangle** [comment]
i was working on some fixes for the travis config, but this was on the "dev" branch (p3p's branch which he has now deleted).  I'm going to just forget about fixing it until the dust settles, then if no one else does, I'll jump in.

**Comment by fiveangle** [comment]
Oh, it looks like things got much worse since yesterday, this is new.  Now I see what you mean:

```
The command "generate_version_header_for_marlin ${TRAVIS_BUILD_DIR}/Marlin" failed and exited with 127 during .
Your build has been stopped.
```

**Comment by Roxy-3D** [comment]
Yeah but...  It would be good if Travis worked on bugfix-1.1.x and bugfix-2.0.0

**Comment by fiveangle** [comment]
Looks like Travis broke himself, because this config was pushed 6 days ago there was a successful build just 21hrs ago but now travis cant find the buildroot/bin scripts:

```
0.22s$ generate_version_header_for_marlin ${TRAVIS_BUILD_DIR}/Marlin
generate_version_header_for_marlin: command not found
```

I'll push a fresh bf20 copy to my repo and see if I can figure out what's pissing travis off ;)

**Comment by fiveangle** [comment]
Yeah, Travis is having issues because I pushed bf20 from this exact commit and it succeeded with only a few target warnings:

https://travis-ci.org/fiveangle/Marlin/builds/260434442

**Comment by Roxy-3D** [comment]
Can we just put the Travis file back the way it was?

**Comment by fiveangle** [comment]
No, it's not us, it's Travis.  I download the identical tree from MarlinFirmware/Marlin/bugfix2.0.x  at commit https://github.com/MarlinFirmware/Marlin/pull/7417/commits/70f91d0400b4af65d2149675c8dbbd0596c22b8f and uploaded to fiveangle/Marlin/bugfix2.0.x and it passed.  Everything (including .travis.yml) was identical, and it passed on my account.

I'm still looking at some things, but I think travis-ci.org is having some intermittent problem with their build VMs.  There's no way to explain the build VM OS "loosing" the buildroot/bin hard link after it's been created (!)

**Comment by fiveangle** [comment]
Update: Looks like for some reason the builds on my account are happening on _precise_ :

```
travis-build version: 9af302805
[34m[1mBuild image provisioning date and time[0m
Thu Feb  5 15:09:33 UTC 2015
[34m[1mOperating System Details[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
[34m[1mLinux Version[0m
```

while the ones on the MarlinFirmware account are happening on _trusty_:

```
travis-build version: 9af302805
[34m[1mBuild image provisioning date and time[0m
Fri Jul  7 18:52:25 UTC 2017
[34m[1mOperating System Details[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
[34m[1mLinux Version[0m
```

I'm working on unwinding why...

**Comment by p3p** [comment]
@fiveangle I think they are rolling out the [upgrade](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default) before removing the precise version, though I'm unsure why running on trusty breaks the Travis script.

**Comment by fiveangle** [comment]
ah, that makes more sense.

I'm testing trusty to find out why and if i can't fix it, I'll push a PR to bf20 to switch back to precise (and fix the PIO build filter for printrboard_revf, which looks like it was omitted from the change the other day)

**Pull request merged**
