### PR TITLE
fixin boards.h configuration

### LINKED ISSUE #1198: board select
Hi All
how can I select board on board.h file ?
regards

### PR DESCRIPTION
**Pull request by stv0g**
- reformatting of `Configuration.h`
    - fixed indention
    - added units to more settings
    - added comments for closing `#endif // AUTO_BED_LEVELING`
    - moved board config to the top (fixes #1198)
    - made RAMPS the default motherboard
  - moved default configurations to be more prominent in top dir

### CODE REVIEW

**Comment by boelle** [comment]
will have a look in a bit

Den lørdag den 10. januar 2015 skrev Steffen Vogel <notifications@github.com

**Comment by nophead** [comment]
Not sure what this addition is for but it is nonsense. P = I^2 R, not I^2 / R.
```
+// If you want the M105 heater power reported in watts, define the BED_WATTS, and (shared for all extruders) EXTRUDER_WATTS
+#define EXTRUDER_WATTS (2*2/5.9) //  P=I^2/R
+#define BED_WATTS (5.45*5.45/2.2)      // P=I^2/R
```

**Comment by stv0g** [comment]
Oh you're right. This was already there. I just fixed the indention whitespaces.
I will remove it.

**Comment by boelle** [comment]
me seen that before also.... will not make much sense

and then again some might like to see what power they use... but i have not seen any hosts like pronterface support it

**Comment by nophead** [comment]
Should be V^2/R I think because people are more likely to know the voltage
than the current.

**Comment by boelle** [comment]
agree... R they can messure and voltage also...so @stv0g if keeping it change the math

but open Q.... how many can me assume use this one? and how much importance factor should we give it? ie are the likely usage be so little that it cant justify that the feature is there at all?

**Comment by boelle** [comment]
and a small sidetrack... @nophead are there anything Mendel90 spec you would see in marlin so its there out the box ?

**Comment by nophead** [comment]
I don't use the bleeding edge version of Marlin. It's far too unstable to
send out with kits. How long has the build sloping objects bug been in?
Ever since firmware retraction probably. Fortunately the version I use has
had 2 years less random hacking so doesn't include it.

Unless software has a complete set of regression tests it always gets worse
over time. Unfortunately testing real time software that interacts with
hardware is very difficult. Testing software that supports and almost
infinite set of build time switches and runs on a massive array of very
different hardware is pretty much impossible.

**Comment by boelle** [comment]
i agree... issues have been hanging for years without anyone doing something about it...

i just hope we can get it on track again

**Pull request closed without merging**
