### PR TITLE
STM32F1: import SPI class from unmaintained repo

### PR DESCRIPTION
**Pull request by tpruvot**
taken from https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/SPI

reindented, with warnings fixes from PR https://github.com/rogerclarkmelbourne/Arduino_STM32/pull/653

see travis for the differences... PR is made to allow us to tune/fix/improve it...

### CODE REVIEW

**Comment by tpruvot** [comment]
hmm, unsure its enough... damn "external libs"

**Comment by thinkyhead** [comment]
Side note: I'd like to add a `README.md` to each of the HAL folders explaining how to build them in Arduino IDE and/or PlatformIO, including a list of which MCUs and boards that they target. This will be especially useful for the STM32 family, because it has such a wide variety of models with different levels of power, and there are several ways to build for them, including **STM32duino**, **libmaple**, **STM32GENERIC**, and a probably a few others. We can of course have all this info on the website too, but I think that for HAL developers and during the (eternal) beta phase having the instructions within the project will be useful.

**Comment by tpruvot** [comment]
yep the F1 folder has a README.md with that already... the problematic boards are the F4/F7 which could be more recent than this framework.

**Comment by tpruvot** [comment]
Ok, seems to work as wanted now :)

**Pull request merged**
