### PR TITLE
Update Various file fixes

### PR DESCRIPTION
**Pull request by classicrocker883**
### Description

Changes that matter:
- Add `MarlinUI::kill_screen()` to Creality UI inorder to remove `HAS_UI_UPDATE 1`
- Move `#define HAS_STATUS_MESSAGE 1` under where `HAS_DISPLAY` is defined
- Move Extra Icons to **e3v2/common**
- Update **endstops.cpp** -  add `FILAMENT_IS_OUT()`, put `#include` in useful `#if` statements

### CODE REVIEW

**Comment by thinkyhead** [comment]
Where are we in sorting out the DWIN_SET versus TJC situation?

It would be great if you could coordinate with @mriscoc on putting together a comprehensive set of changes. The 2.1.3 beta period will be on for another couple of weeks. If you can gather the most up to date implementation and package it up in a neat PR then I will be very happy to help it get cleaned up and merged ASAP.

**Comment by thisiskeithb** [comment]
> Where are we in sorting out the DWIN_SET versus TJC situation?

Still a WIP: https://github.com/MarlinFirmware/Configurations/pull/1105#issuecomment-2407288373

**Comment by mriscoc** [comment]
> Where are we in sorting out the DWIN_SET versus TJC situation?
> 
> It would be great if you could coordinate with @mriscoc on putting together a comprehensive set of changes. The 2.1.3 beta period will be on for another couple of weeks. If you can gather the most up to date implementation and package it up in a neat PR then I will be very happy to help it get cleaned up and merged ASAP.

I stopped using bitmap labels a long time ago. Now I use strings.

**Comment by classicrocker883** [comment]
unfortunately I do not have a TJC display for testing either. I know the community would be more than willing to help. I would just need a starting point.

I did find a way to incorporate DWIN `ICON_` for TJC files *.zico* IIRC, its a chinese program that should do the trick. in other words, I should be able to copy over the DWIN jpg into the TJC files format, and if that all goes well we can move to step 2.

but the hard part then is putting everything all in order so it doesnt appear jumbled. from what I gather TJC display had fonts in different sizes??

I just do not know the main differences as to what needs changing in order for everything to work correctly.
A good write-up about it and really the differences between DWIN and TJC would speed things along, basically all the information we can get, I could put together something to test with and then go from there.


Furthermore,
what about **DACAI**?
this seems to be about the only difference having that enabled.
```y
void DWIN_ICON_Show(uint16_t x, uint16_t y, uint16_t addr) {
  #if ENABLED(DACAI_DISPLAY)
    DACAI_ICON_Show(x, y, addr);
  #else
    DWIN_ICON_Show(0, 0, 1, x, y, addr);
  #endif
}
```

just wanted to point it out, but probably something to discuss further another time

**Comment by thinkyhead** [comment]
My general interest was in whether the "Extra Icons" would be available on all the supported displays. If not then we should not assume they are present. If we did work it out so the code isn't referring to any icons that might be missing, then at least this PR is all good.

It's fine that ProUI is no longer including Chinese translations and bitmap labels, as it is likely easier for one person to maintain. Now that we have AI tools to assist us, it should be a lot easier to put them back in whenever we decide to go beyond the Roman alphabet.

**Pull request merged**
