### PR TITLE
Added negative temperatures for thermistor type 1 (100K)

### PR DESCRIPTION
**Pull request by AndKe**
This allows lower mintemp, which in turn lets the machine start/operate in sub-zero temperatures.

### CODE REVIEW

**Comment by FHeilmann** [comment]
two things:
first, you have to create your pull request against RCBugFix, not RC
second, this only adds negative temperatures for one thermistor table, leaving the others unchanged, so depending on whether these tables already have negative table entries or not this PR may do nothing at all.

**Comment by AndKe** [comment]
Yes, I preferred not to mess with thermistors I could not test - from an electrical point of view, all analog thermistors should give make huge difference when disconnected, so it should be ok.

**Comment by boelle** [comment]
@AndKe "first, you have to create your pull request against RCBugFix, not RC"

**Comment by FHeilmann** [comment]
What I mean is you are advertising that this PR adds handling of negative temperatures whereas for some Thermistors going to -1C will still trigger the disconnect, and thus not allow to use sub-zero temperatures.

This can be fixed by simply rewording the PR to "Add negative temperatures for Thermistor X"

**Comment by AndKe** [comment]
Changed PR name & target branch

**Comment by thinkyhead** [comment]
Applied in https://github.com/MarlinFirmware/Marlin/commit/6fa8fd15e235e2461c82aebbc28985999fda4268

**Pull request closed without merging**
