### PR TITLE
[menu] Fix wrong extruder stepper on filament change

### LINKED ISSUE #19911: [BUG] "Change filament" from menu will always use second extruder on mixing extruder setup
### Bug Description

"Change filament" from menu will always use second extruder on mixing extruder setup.

This means that choosing "E1" will then change filament on the second extruder.
Choosing "E2" will change filament on the second extruder as well (as expected).

This is a regression. It was working fine before on a branch based on a much older commit:
https://github.com/fishcu/Marlin/tree/find-problem

### My Configurations

My config is here: https://github.com/fishcu/Marlin/tree/2.0.7.2-a10m

This is based on tag 2.0.7.2.

Flashed on a Geeetech A10M with GT2560 v3.0 board.

### Steps to Reproduce

As described above, use the menu to try and change filament on the first extruder.

**Expected behavior:** Change filament on the first extruder if I choose E1 in the menu.

**Actual behavior:** Filament is changed on E2 in any case.

#### Additional Information

It could be possible to do a `git bisect` with some manual work (cherry-picking or similar) on these commits:
bad: https://github.com/fishcu/Marlin/tree/2.0.7.2-a10m
good: https://github.com/fishcu/Marlin/tree/find-problem

### PR DESCRIPTION
**Pull request by fishcu**
### Description

The "change filament" menu produces a wrong extruder parameter (`T` parameter) in some circumstances.
Conditions:
- Mixing extruder
- User is trying to change the filament from a cold hotend

### Benefits

The correct extruder is chosen according to the menu presented to the user.

Fixes #19911 

### Configurations

Tested on this branch here: https://github.com/fishcu/Marlin/tree/2.0.7.2-a10m

Which is based on tag 2.0.7.2. Tested on a Geeetech A10M printer with mixing extruder (2-in-1-out).

### Related Issues

Fixes #19911

### CODE REVIEW

**Comment by fishcu** [comment]
How can I remove the "PR Bad Target" error? I've already changed the target branch to the correct one and even closed and reopened a new PR.

**Comment by thinkyhead** [comment]
The "bad target" error seems to be spurious. We can safely ignore it.

**Comment by thinkyhead** [comment]
Are you aware that your branch is almost a year old?

**Comment by fishcu** [comment]
The branch was created fresh just for this PR. Something must have gone wrong with the parent commit. I will try again.

Could you elaborate what you mean by "Try this instead" @thinkyhead ?

I assume you meant "Look at a fix of `LCD_FIRST_TOOL` or `lcd_put_u8str_ind_P` instead".

**Pull request closed without merging**
