### PR TITLE
Babystep also requires homing

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Add additional options for babystep control as per issue #13129

### CODE REVIEW

**Comment by thinkyhead** [comment]
I think it's important to retain the association between babystepping and active printing. This is going to be important going forward as we integrate live mesh editing, expand support for touch screens, and expand Marlin's G-code dialect to be more fully compatible with RepRap Firmware, the Duet Wifi onboard print server, and so on.

**Comment by InsanityAutomation** [comment]
On this point I disagree. Its best to set the z offset with a feeler gauge prior to beginning printing and this is the fastest method to do so. You can avoid many crashes and nozzles dragged across the bed checking this statically before starting a print when calibrating a machine. The configuration options allowed it to be set the user desired. Working from a static point should be far less intrusive in any of those scenarios than while moving, especially when its tied with M851.

**Comment by Roxy-3D** [comment]
> I think it's important to retain the association between babystepping and active printing.

I'm not sure this is true.   Many people feel BabyStepping should always be available as a way to reposition the nozzle without upsetting any of Marlin's internal calculations.  I do not think we can jump to the conclusion that BabyStepping should only be available while actually printing.   We should have a long and detailed discussion before accepting that as 'Fact'.

**Comment by thinkyhead** [comment]
I'm working on live mesh editing, which will be far preferable to babystepping for those using mesh leveling. I do not see a user-friendly scenario where printer owners should expect to use babystepping with a feeler fauge while the machine is idle prior to each print. I'm also working on live Z probe Z offset calibration, which should be a better UI for establishing consistent nozzle height at the start of a print. Overuse of babystepping is symptomatic of some kind of issue.

**Comment by Roxy-3D** [comment]
No...  It depends on how the user actually uses the machine.    I deliberately have the machine home with the nozzle a very small amount too high.   And when I start a print, I can lower the nozzle a small amount when the skirt of the part is being printed.   That works very well for me.   

It maybe Z-BabyStepping is mutually exclusive with what ever Live Mesh Editing turns out to be.    But for right now...   And certainly in the case where Live Mesh Editing is not enabled...    It should be available.

**Comment by InsanityAutomation** [comment]
The use of the feeler gauge is not before each print, it's typically the initial setup after nozzle changes and such. I often start prints remotely and rarely touch it between maintenance cycles.

**Comment by thinkyhead** [comment]
> And when I start a print, I can lower the nozzle a small amount when the skirt of the part is being printed. That works very well for me.

So you are using babystepping as designed. So am I.

**Comment by thinkyhead** [comment]
> The use of the feeler gauge is not before each print, it's typically the initial setup after nozzle changes and such.

A complete re-probe of the bed is recommended in that case, preceded by using the Z Probe Offset Wizard —— coming soon!

**Comment by Roxy-3D** [comment]
How about we add a control to the Baby Stepping section of the Configuration_adv.h file:
```
#define Z_BABYSTEPPING_ALWAYS_AVAILABLE    // Maybe incompatible with future 'Live Z Mesh Editing'
```
and it can defeat the (planner.movesplanned() || IS_SD_PRINTING)  :
```
      #if ENABLED(DOUBLECLICK_FOR_Z_BABYSTEPPING) && ENABLED(BABYSTEPPING)
        static millis_t doubleclick_expire_ms = 0;
        // Going to lcd_main_menu from status screen? Remember first click time.
        // Going back to status screen within a very short time? Go to Z babystepping.
        if (screen == lcd_main_menu) {
          if (currentScreen == lcd_status_screen)
            doubleclick_expire_ms = millis() + DOUBLECLICK_MAX_INTERVAL;
        }
        else if (screen == lcd_status_screen && currentScreen == lcd_main_menu && PENDING(millis(), doubleclick_expire_ms) 
#if Z_BABYSTEPPING_ALWAYS_AVAILABLE
        )
#else
        && (planner.movesplanned() || IS_SD_PRINTING))
#endif
          screen =
            #if ENABLED(BABYSTEP_ZPROBE_OFFSET)
              lcd_babystep_zoffset
            #else
              lcd_babystep_z
            #endif
          ;
      #endif
```

**Comment by AnHardt** [comment]
Babysteps require homing.
After homing your babysteps are gone! So what for?

**Comment by Roxy-3D** [comment]
Personally...   I don't believe we should require homing for BabySteps.   The hardware can generate the pulses whether the machine is homed or not.

But independent of that.   In this post https://github.com/MarlinFirmware/Marlin/pull/13191#issuecomment-466419728 I said

"I deliberately have the machine home with the nozzle a very small amount too high. And when I start a print, I can lower the nozzle a small amount when the skirt of the part is being printed. That works very well for me."

**Comment by thinkyhead** [comment]
Babysteps may typically also be lost on stepper sleep. I will add the "BABYSTEPS_ALWAYS" option in the next day or two to satisfy the popular demand. It will be interesting to see how users find new and fun uses for it.

**Pull request merged**
