### PR TITLE
UTF-8 mapper for Czech

### PR DESCRIPTION
**Pull request by petrzjunior**
Making new fonts isn't that hard, is it? Quick addition for Czech accents the same way Polish language does.

P.S. I know, there is now much work due to reorganization and 32-bit HAL, so I'll just leave it here. No problem to rebase it in the future.

### CODE REVIEW

**Comment by thinkyhead** [comment]
This could be merged any time. The only question I have is whether the names could be these instead?
```
language_cz.h
language_cz_utf8.h
```
I would then do the same for the Polish language….

The reason I'm interested is because we have an old UTF-8 PR hanging around which could be incorporated in the future. It does everything using UTF-8, so there are half as many language files to be edited. The only caveat is that you have to do an extra step to re-generate the fonts when languages are edited.

That patch is desirable because it gets rid of the need to use the mappers at runtime. Instead it runs the mappers on all the strings beforehand, so everything is pre-mapped.

As you can imagine, that would save a lot of processing and make all displays run a little more efficiently.

So anyway, let me know if the name change makes sense, and I would be happy to merge this any time.

I can't review it too closely. I leave it between you and Czechoslovakia.

**Comment by petrzjunior** [comment]
@thinkyhead OK, probably a good idea. Should the UTF-8 version be selected automatically or let user choose `#define LCD_LANGUAGE cz-utf8`? The UTF-8 version doesn't work on HD44780 of course, so some kind of sanity check would be needed.

P.S. No Czechoslovakia anymore, now Czechia and Slovakia. 😃

**Comment by thinkyhead** [comment]
> P.S. No Czechoslovakia anymore, now Czechia and Slovakia. 😃

Ah, I see ~1993 it changed! I was so disengaged from the world that year. Glad it has worked out…

**Comment by thinkyhead** [comment]
> Should the UTF-8 version be selected automatically?

For now, it has to be an explicit selection, since not all languages have both an ASCII and UTF-8 version. Use an underscore, so it is `#define LCD_LANGUAGE cz_utf8`.

**Comment by petrzjunior** [comment]
OK, seems good to me now.

**Comment by thinkyhead** [comment]
Looks great! I will merge it shortly at #7237. I also took the opportunity to update the [LCD font documentation](http://marlinfw.org/docs/development/lcd_language.html) on the website and refresh my understanding of how LCD languages work.

**Pull request closed without merging**
