### PR TITLE
[2.0.x] Rename and document some configuration options

### PR DESCRIPTION
**Pull request by thinkyhead**
In response to #10856

- Change `BEZIER_JERK_CONTROL` to `S_CURVE_ACCELERATION`
- Rename Junction Deviation sub-options
- Adjust some spacing

Counterpart to #10857

### CODE REVIEW

**Comment by TheSFReader** [comment]
"Because this is computationally-intensive, a 32-bit MCU is required. " 
I thought a "lightweight" version had been written for (at least some) 16 bits AVR ?

**Comment by ejtagle** [comment]
@TheSFReader : We actually managrd to make it work in AVR. That sentence should be removed ,as it is not true anymore

**Comment by TheSFReader** [comment]
Yep, I wanted confirmation. But perhaps marlin supports other 16bit architecture than AVR ?
Anyway, if AVR supports S_CURVE_ACCELERATION, I think the sentence should be at least corrected indeed.

**Comment by ejtagle** [comment]
@TheSFReader Marlin supports only AVR 8bit architectures and ARM architectures. So Bezier acceleration is supported for all targets 👍 
That sentence was added at the beginning, when there was only support for ARM based controllers

**Comment by thinkyhead** [comment]
> Because this is computationally-intensive, a 32-bit MCU is required

I removed that from the 1.1.x branch. Guess I forgot to remove it from this one.

**Pull request merged**
