### PR TITLE
Fix dual MAX31865 initialization issues

### LINKED ISSUE #23439: [BUG] (MAX31865 no longer works after recent changes)
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Marlin now reports 989 as the temperature for both E0 and E1 after the recent changes to the MAX31865.cpp and associated files. With the older versions of Marlin, we were able to read temperatures successfully with the same hardware. Currently running on a Bigtreetech GTR V1.0 board using SPI pins as follows:
```cpp
#define TEMP_0_CS_PIN                       PD4 
#define TEMP_0_SCK_PIN                      PB3 
#define TEMP_0_MISO_PIN                     PB6 
#define TEMP_0_MOSI_PIN                     PG15 /

#define TEMP_1_CS_PIN                       PC12 
#define TEMP_1_SCK_PIN           TEMP_0_SCK_PIN
#define TEMP_1_MISO_PIN         TEMP_0_MISO_PIN
#define TEMP_1_MOSI_PIN         TEMP_0_MOSI_PIN
```
These pins are different from the defaults in the firmware, but did work on previous versions of Marlin. Also have confirmed that SPI bus can be read by a Raspberry pi directly before entering the board. I can revert to the older firmware and get readings.

### Bug Timeline

new

### Expected behavior

Read temperatures correctly. 

### Actual behavior

Temperatures read 989 on boot. Err is then displayed, 

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

2.0.9.3

### Printer model

_No response_

### Electronics

BTT GTR V1.0 STM32F4

### Add-ons

M5 extender

### Bed Leveling

_No response_

### Your Slicer

_No response_

### Host Software

_No response_

### Additional information & file uploads

[MAX31865_issue.zip](https://github.com/MarlinFirmware/Marlin/files/7803810/MAX31865_issue.zip)

### PR DESCRIPTION
**Pull request by zeleps**
In response to #23439, I added some extra initialization steps to MAX31865.cpp, which ensure no fault exists on init and reset the threshold registers to their default values. This seems to solve a hardware issue, where two MAX31865 sensors are hooked up _on the same SPI_ and they initialize with fault.

I also added another initialization fault bypassing mechanism, as suggested by @GadgetAngel. This can be configured by the corresponding setting (MAX31865_IGNORE_INITIAL_FAULTY_READS) in Configuration_adv.h.

This PR does not close #23439, since there seems to be an issue with software SPI conflicting with SD support (evidently, issue first appeared after #22682). Hardware SPI works fine with the above fix.

### Requirements

2 MAX31865 sensors on the same SPI.

### Benefits

Bugfix. Also some code deduplication, additional debug logging, and fine tuning of sensor polling times.

### Configurations

-

### Related Issues

#23439

### CODE REVIEW

**Comment by zeleps** [comment]
I've taken up checking the SPI routines included in MAX31865 and it seems there's a lot of space for improvment. First of all, there were some exceptions regarding LPC1768 (to use SoftwareSPI.cpp) which actually makes things worse (I have an LPC1768 board and it seems to have issues with SoftwareSPI.cpp). SoftwareSPI.cpp is actually built using some cryptic delay-generating loops which really do not make any sense when we have DELAY_NS_VAR() available.

Also, the nominal SPI speed for a MAX31865 is a given (5MHz), configuring this is unnecessary.

I'm making a few changes and lots of tests on this, so I'm keeping this as a draft for the moment.

**Comment by thinkyhead** [comment]
Thanks for looking into the SPI stuff. It has all been very tenuous and it has not gotten a huge amount of testing.

**Comment by zeleps** [comment]
@thinkyhead, in your last commit you modified buildroot/share/scripts/upload.py, was that intended?

**Comment by thinkyhead** [comment]
Take another merge of upstream/bugfix-2.0.x and it might disappear. It's just a global replace of trailing whitespace, so it can be left in this PR if it hasn't been otherwise pushed to bugfix.

**Comment by GadgetAngel** [comment]
> I've taken up checking the SPI routines included in MAX31865 and it seems there's a lot of space for improvment. First of all, there were some exceptions regarding LPC1768 (to use SoftwareSPI.cpp) which actually makes things worse (I have an LPC1768 board and it seems to have issues with SoftwareSPI.cpp). SoftwareSPI.cpp is actually built using some cryptic delay-generating loops which really do not make any sense when we have DELAY_NS_VAR() available.
> 
> Also, the nominal SPI speed for a MAX31865 is a given (5MHz), configuring this is unnecessary.
> 
> I'm making a few changes and lots of tests on this, so I'm keeping this as a draft for the moment.

@zeleps If you need a board to help test out these MAX31865 problems with Marlin, please let me know.  

I have **all** the BTT boards and I can loan a board to you. To do that I need to get your mailing address. I can ship them to you with a return shipping label. It might take a week or two to get to you in Greece but I am willing to share my resources since I can not share my time.

Presently, I can not do this testing because I am trying to build two Voron 2.4 printers and that is taking up all my free time

**Comment by zeleps** [comment]
Hey JoAnn! Thanks a lot for the offer, though I think it's an overkill to send the boards over to Greece. I'll try to source one locally (although it seems it has disappeared from everywhere), or find someone to give the code a run (it shouldn't be that hard :) ). If all else fails, I'll get back to you on that.

Meanwhile, my first tests seem to work smoothly on my SKR1.4, I'll also try it on an atmega I have at hand (probably in the weekend). If anyone has a heart to test this on any system, your feedback will be much appreciated.

**Comment by zeleps** [comment]
@thinkyhead I've tested this on LPC1768 and AVR (Arduino Mega + RAMPS), many combinations (1/2 sensors, on the same / different SPI), and it seems to work fine. I can't test it on any other platform at the moment, I've ordered a BTT GTR to figure out what's wrong with @kurtis-potier-geofabrica 's setup (#23439), but that's all I can do for now. Most of my changes in SPI are mainly hardcoded timings (based on the MAX31865 datasheet) and some pin states on entry and exit.

So, do we merge it at this point? Is there a test channel, where we ask more people to try this? If not, shouldn't there be one (or at least a registry of people who are willing to test things out)?

**Comment by thinkyhead** [comment]
> do we merge it at this point?

We can put a call out on Discord in a couple of channels there. There is a "testing" channel, and hopefully it's being used for the purpose of gathering testers. I haven't created a "testers" role, but that would be a good thing, as it would then be possible to send a message to all members of the role.

**Comment by zeleps** [comment]
> I haven't created a "testers" role, but that would be a good thing, as it would then be possible to send a message to all members of the role.

This is an important development leap, I think it would speed up a lot of things and greatly reduce backlog. I'd certainly be willing to participate, at least on components / features I'm using and I'm familiar with.

**Comment by zeleps** [comment]
Tests with a BTT GTR 1.0 and sw SPI on stepper driver SPI pins worked flawlessly. This was the case reported in #23439, so I guess the issue is not with this PR (or previous MAX31865 cases), but probably some conflicting configuration in that specific setup. 

So far we have no other reported issues, and I've successfully tested this PR on 3 different setups (LPC1768 in production, AVR, STM32f4). I think it's ready for merging.

**Comment by zeleps** [comment]
Tests with a BTT GTR 1.0 and sw SPI on stepper driver SPI pins worked flawlessly. This was the case reported in #23439, so I guess the issue is not with this PR (or previous MAX31865 cases), but probably some conflicting configuration in that specific setup.

So far we have no other reported issues, and I've successfully tested this PR on 3 different setups (LPC1768 in production, AVR, STM32f4). I think it's ready for merging.

**Pull request merged**
