### PR TITLE
add gcode M820 to display the macros over serial

### PR DESCRIPTION
**Pull request by fmuntean**
### Description

Added M820 command to display all the macros over the serial.

### Requirements

No

### Benefits

It allows to view the defined macros for debugging or for saving purposes.

### CODE REVIEW

**Comment by ellensp** [comment]
where is updated Marlin/src/gcode/gcode.cpp  ?

**Comment by fmuntean** [comment]
> where is updated Marlin/src/gcode/gcode.cpp ?

Sorry, I forgot to pull that change into this branch.

**Comment by ellensp** [comment]
SERIAL_PRINT is not available on all platforms

**Comment by fmuntean** [comment]
> SERIAL_PRINT is not available on all platforms
> 
> 

Sorry, I don't have all the platforms. What do you recommend?

**Comment by ellensp** [comment]
The current CI error is not related to anything you did. That is waiting on https://github.com/MarlinFirmware/Configurations/pull/1109

**Pull request merged**
