### PR TITLE
Add fly_mini for stm32duino

### PR DESCRIPTION
**Pull request by ellensp**
### Description

added env:FLY_MINI non maple env.

### Requirements

BOARD_FLY_MINI

### Benefits

Less maple

### CODE REVIEW

**Comment by ellensp** [comment]
@thisiskeithb can you try these, since you have the board?

**Comment by thisiskeithb** [comment]
Duplicate of https://github.com/MarlinFirmware/Marlin/pull/22355

**Comment by ellensp** [comment]
No, your way is old way and this PR  adds non maple env
no need for buildroot/share/PlatformIO/scripts/fly_mini.py anymore.

**Comment by ellensp** [comment]
non need for buildroot/share/PlatformIO/scripts/fly_mini.py  anymore.

**Comment by ellensp** [comment]
have removed my reinstatement of fly_mini, left it as creating stm32duino env so as not to conflict.

**Pull request merged**
