### PR TITLE
Fix BUZZ(ER) and cleanup

### PR DESCRIPTION
**Pull request by Ludy87**

### CODE REVIEW

**Comment by thinkyhead** [comment]
Sometimes the tedium of repeating `#if` conditions has led us to define empty functions/methods, trusting the compiler to remove empty code-paths. Do you find that this change is needed to reduce the size of the compiled code?

**Comment by Ludy87** [comment]
The assessment of me, yes it helps to save something.
But I am not a professional like you. I am in the learning phase.

**Comment by Ludy87** [comment]
I have not changed everything in Marlin, which includes buzzer, only where I thought it was useful.

**Comment by thinkyhead** [comment]
I can see why the empty completion feedback method might cause some oddity.

**Comment by Ludy87** [comment]
https://github.com/MarlinFirmware/Marlin/blob/1579091c206c14bbf7c88186fae07ccddc001a36/Marlin/src/libs/buzzer.h#L28

If `LCD_USE_I2C_BUZZER` is enabled,`ui` will not be found, after three hours, I could not find the error.

**Comment by thinkyhead** [comment]
The `.cpp` file that wants to refer to `ui` must include `lcd/ultralcd.h`.

**Pull request merged**
