### PR TITLE
M48 needs a real probe

### PR DESCRIPTION
**Pull request by thinkyhead**
Addressing #7202

### CODE REVIEW

**Comment by Roxy-3D** [comment]
I don't have strong feelings on this....    But I think I would argue that if it is valid to 'manually probe' bed locations, it is also valid to be able to test how accurately your manual probe technique is.

The purpose of M48 is to see how 'repeatable' your probe can measure a location on the print bed.   It would seem to me that purpose is independent of what the probe is.   We don't disqualify inductive probes just because they were not around when M48 was designed and written.   And probably that same logic applies to 'manual probes'.

**Comment by thinkyhead** [comment]
Until `M48` is rewritten to allow for manual probing, this is an interim better error message.

I think it would be interesting to see how accurate one's personal feeler gauge, business card, paper shim, or eyeballing technique is. It's not a high demand feature, but it would be a good exercise for the new LCD API once that is ready.

**Comment by Roxy-3D** [comment]
> Until M48 is rewritten to allow for manual probing, this is an interim solution.

The manual probing should be handled by the probing sub-system.   Anything that wants to probe should just use that class.  And how that class does its work should not impact stuff that is using the class.   M48 doesn't need to be rewritten.   The probing class needs to be smarter to know there are various ways to probe.

**Comment by thinkyhead** [comment]
Well, `PROBE_MANUALLY` is not a probe, per se, but a modification to the ABL version of `gcode_G29`. As such, it decomposes the G29 procedure and uses more SRAM than any real probe would ever require. If it were possibly for it to be "just another probe" then it would already be.

Not to say that we can't build a more clean, formal, and hot-pluggable LCD / UI / G-code step-by-step / wizard-ish system, but within the current scheme what we have is not extricable from G29 itself.

**Comment by Roxy-3D** [comment]
Yes...  But here is my perspective:  All 3 Mesh Based leveling systems have a concept and have implemented some flavor of 'Manual Probe'.  They all do it differently.   What I'm arguing is when we make a class to handle probing, 'Manual Probes' ought to be a default instance and machine controlled probing is just a fancier version of it.   And very possibly, every machine has 'Manual Probing' available to it (and M48 ought to function even though there is no computer controlled probe.)

Some bed leveling systems (like Linear) will never need to use the manual probe.   But they could if there is no machine controlled probe available.   And other systems such as UBL can optionally use the manual probe capability where convenient.  (to fill in the unprobed areas of a freshly generated mesh that are missing because of  X & Y_PROBE_OFFSET_FROM_NOZZLE)

I'm just saying M48 doesn't need to be rewritten...  We need a new probe class with manual probing as one of the instances of it.

**Comment by thinkyhead** [comment]
> …when we make a class to handle probing…

We may still want to continue with a three-tiered system, depending on user needs:

**MBL** level is included as a legacy option in 2.0 because it uses a tiny amount of PROGMEM. We can corral any obsolete code it might still rely upon as a new system is built.

**ABL** level provides a minimalistic "require-G28-first / probe-activate-save / load-reactivate" approach. Built to be baseline with vendor customization in mind, it has a utilitarian submenu, a basic LCD wizard, and a no-frills Z adjuster. Only `BILINEAR` provides the point editing option, but (currently) no LCD-based re-probe point.

**UBL** level provides a fixed-size / fixed-position mesh, but provides a more complete suite of options for fine tuning, and more choices about how to manage unreachable points.

> Some bed leveling systems (like Linear) will never need to use the manual probe.

Whoops! Well, you can if you want, currently… And three-point…

**Comment by thinkyhead** [comment]
> (to fill in the unprobed areas of a freshly generated mesh that are missing because of X & Y_PROBE_OFFSET_FROM_NOZZLE)

While developing BILINEAR and testing it with SCARA, I found that to manage those areas, you have to extend your grid to the whole of the bed (or print area) and just allow the unreachable points to exist and get skipped on the auto-probe. This is preferable to having the grid automatically avoid the unreachable areas and not allow the unreachable points to be represented.

But I didn't extend `G29` with a manual probing option. If I had been asked to solve the issue of filling in those points, I probably would have made manual probing a standard extension of `G30`.) In this case, by "manual probing" I just mean recording the current Z position for the nearest probe point, not activating the knob…)

Currently `G30` is a command to probe and just throw away the result. So, I would have extended it with `G30 S` (or something) as an added option to save the current Z as a mesh point, if close enough. And… `G30 C` would start LCD Z adjustment — a blocking function that takes over the machine and LCD ("Place shim…") to adjust Z until a click. The caller can store the `RAW_CURRENT_POSITION(Z)` and carry on……

When there is no LCD, `G30 C` would reply "`Adjust Z, then do 'G30 S'.`"

A subtle manual probe via G-code with ABL: `G29 W I0 J0` will
save the raw current Z as the Z for the mesh point 0, 0.

**Comment by Roxy-3D** [comment]
> This is preferable to having the grid automatically avoid the unreachable areas and not allow the unreachable points to be represented.

UBL 'prefers' all mesh points are populated.   But there are multiple paths to get there.  (Manual probing... Extrapolating off of near by points...  Filling with a user specified value...  Using G26 to see how far off they are and then editing the point...)   With that said...  In UBL, the grid covers the printable area of the bed.  

In the Delta version of UBL, it is necessary to have unreachable points be represented.  For speed reasons, a square mesh makes sense even though not all mesh points are reachable.   And because we are doing a bilinear interpolation the edge mesh cells have mesh points that are not reachable.   Once again, there are multiple ways to acquire those numbers...

If we had a probing class 18 months ago...  things would have evolved differently.   But even so, putting a probe class in place now would still help to clean up and make the code base more consistent.

**Comment by fiveangle** [comment]
> But I didn't extend G29 with a manual probing option.

Which is the main reason I had to switch to full manual probing with BBL to get a clean first layer (well, once I get it working which I'm sure I will)

Your proposed extension to allow manual G30 probing is a great idea, and would surely be a boon, but as the primary reason to use BBL over UBL is PROGMEM use, extending BBL any further pushes it that much further out of its sweet spot between MBL and UBL.

Moving forward, changes other than those requested by paying entities (e.g. scara work for MakerArm, etc), I would suggest to err on the side of omitting changes that increase PROGMEM use any real amount, since BBL is on the very raged edge of usable on 128k boards with LCD (no SD).  If it gets any bigger, it will be back to MBL for all of them (and hence back to the bed countour contining throughout the print).

**Comment by thinkyhead** [comment]
> changes other than those requested by paying entities (e.g. scara work for MakerArm, etc)

Features that will come from that work include: Wifi support, IR sensor support, more CNC features, closed loop encoder support, enhanced SCARA kinematics, and more. But nothing that should affect the general workings or size of Marlin when those features are not used.

> since BBL is on the very raged edge of usable on 128k boards with LCD

Auto Bed Leveling (3-point, linear, bilinear) is about as economical as it can get without cutting down string sizes and so on. Mesh Bed Leveling is better suited to smaller boards and works on the same principle as `AUTO_BED_LEVELING_BILINEAR`+`PROBE_MANUALLY`. It uses less SRAM also.

**Comment by thinkyhead** [comment]
> Your proposed extension to allow manual G30 probing is a great idea, and would surely be a boon…

The code to set a mesh point already exists, so that would just be moved. And the code to input Z using the controller knob for a manual probe is quite small.

For `G33`, Luc just added Z adjustment via LCD, and in cleaning that up I was able to reduce the code down to a single call that looks just like the probe call:
```cpp
#if ENABLED(PROBE_MANUALLY)
  z_at_pt[0] += lcd_probe_pt(0, 0);
#else
  z_at_pt[0] += probe_pt(dx, dy, stow_after_each, 1, false);
#endif
```

As for getting back program memory, code is the smallest concern. It's mainly `PROGMEM` strings that eat up the most space, so we should always try to keep them concise. I'm usually able to reduce the size of Marlin (with default config) by around 200 bytes each time I go looking for strings and redundancies that can be reduced.

If using a graphical display, dropping the boot screen gives back the largest amount.

**Comment by fiveangle** [comment]
> While developing BILINEAR and testing it with SCARA, I found that to manage those areas, you have to extend your grid to the whole of the bed (or print area) and just allow the unreachable points to exist and get skipped on the auto-probe. This is preferable to having the grid automatically avoid the unreachable areas and not allow the unreachable points to be represented.

`<mind blow>`


I hate to make more work for others, but your G30 extension really seems like something that could help anyone using BILINEAR (most 128k boards).  I'm still working on how to prevent others from struggling like I did with some doc improvement (just amassing notes at this point).

FYI, you may find this interesting, but below is current state of many Marlin options affect on PROGMEM (of course many of these are dependant on other factors, but it's interesting to see which features actually use the most).  Many "nice to have but not-mission-critical features are surprisingly greedy with PROGMEM.  Sorry PREVENT_COLD_EXTRUSION and PRINTCOUNTER, don't call us, we'll call you ;)

I'm just learning a bit about TravisCI and may look into seeing if it could be used to generate a "usage report" for the various features automatically, which would be nifty.

I don't know why, but I've always found it a stimulating challenge to try and do more with less powerful systems that others think are obsoleted.  I think it comes from having always used hand-me-down computers back in the day.  But then I also do stuff like [install 250 networked Mac SE/30 systems as an "art installation"](http://www.c-trl.com/68k/)   Obsolescence  is just a lack of imagination :)

<details><summary>PROGMEM usage of bugfix1.1.x as of today</summary>

```
speedster@FiveAngle[~/dev/github/Marlin/Marlin]$ grep bytes Config*|grep //
Configuration.h://#define STRING_CONFIG_H_AUTHOR "(fiveangle@gmail.com)" // Who made the changes. // 220 bytes
Configuration.h://#define SHOW_BOOTSCREEN // 458 bytes
Configuration.h:#define CUSTOM_MACHINE_NAME "Printrbot Metal" // 16 bytes
Configuration.h:#define POWER_SUPPLY 0 // 0 bytes
Configuration.h:  //#define PID_AUTOTUNE_MENU // Add PID Autotune to the LCD "Temperature" menu to run M303 and apply the result. // 296 bytes
Configuration.h:  //#define PID_DEBUG // Sends debug data to the serial port. // 214 bytes
Configuration.h:  //#define PID_BED_DEBUG // Sends debug data to the serial port. // 396 bytes
Configuration.h://#define PREVENT_COLD_EXTRUSION // 1914 bytes
Configuration.h:#define PREVENT_LENGTHY_EXTRUDE // 0 bytes
Configuration.h:#define THERMAL_PROTECTION_HOTENDS // Enable thermal protection for all extruders // 448 bytes   // both of these together
Configuration.h:#define THERMAL_PROTECTION_BED     // Enable thermal protection for the heated bed // 406 bytes  // saves 1522 bytes
Configuration.h:#define FIX_MOUNTED_PROBE // 3780 bytes over PROBE_MANUALLY
Configuration.h://#define PROBING_HEATERS_OFF       // Turn heaters off when probing // 156 bytes
Configuration.h://#define PROBING_FANS_OFF          // Turn fans off when probing // 16 bytes
Configuration.h://#define PROBE_DOUBLE_TOUCH // 0 bytes
Configuration.h://#define Z_MIN_PROBE_REPEATABILITY_TEST // 3768 bytes
Configuration.h:#define DISABLE_REDUCED_ACCURACY_WARNING // -64 bytes
Configuration.h:#define DISABLE_E false // For all extruders // 0 bytes
Configuration.h://#define DISABLE_INACTIVE_EXTRUDER true // Keep only the active extruder enabled. // 36 bytes
Configuration.h:#define MIN_SOFTWARE_ENDSTOPS // 128 bytes
Configuration.h:#define MAX_SOFTWARE_ENDSTOPS // 128 bytes // together with MINSOFTWARE_ENDSTOPS, uses 476 bytes
Configuration.h://#define AUTO_BED_LEVELING_3POINT // 6366 bytes (w/o LCD)
Configuration.h://#define AUTO_BED_LEVELING_LINEAR // 18386 bytes (w/o LCD)
Configuration.h:#define AUTO_BED_LEVELING_BILINEAR // 9804 bytes (w/o LCD)
Configuration.h://#define AUTO_BED_LEVELING_UBL //48592 bytes (w/o LCD)
Configuration.h://#define MESH_BED_LEVELING // 7220 bytes (w/o LCD)
Configuration.h://#define DEBUG_LEVELING_FEATURE // 3312 bytes
Configuration.h:  #define ENABLE_LEVELING_FADE_HEIGHT // 828 bytes
Configuration.h:  //#define PROBE_Y_FIRST // 0 bytes
Configuration.h:    #define EXTRAPOLATE_BEYOND_GRID // -72 bytes
Configuration.h:    //#define ABL_BILINEAR_SUBDIVISION // 1802 bytes
Configuration.h://#define LCD_BED_LEVELING // 2070 bytes
Configuration.h:#define Z_SAFE_HOMING // 256 bytes
Configuration.h://#define DISABLE_M503    // Saves ~2700 bytes of PROGMEM. Disable for release!
Configuration.h:#define HOST_KEEPALIVE_FEATURE      // Disable this if your host doesn't like keepalive messages // 626 bytes
Configuration.h://#define M100_FREE_MEMORY_WATCHER // uncomment to add the M100 Free Memory Watcher for debug purpose // 2578 bytes
Configuration.h://#define INCH_MODE_SUPPORT // 1126 bytes
Configuration.h:#define NOZZLE_PARK_FEATURE // 392 bytes
Configuration.h://#define PRINTJOB_TIMER_AUTOSTART // 162 bytes
Configuration.h://#define PRINTCOUNTER // 2048 bytes
Configuration.h://#define SDSUPPORT // 18036 bytes
Configuration.h:#define INDIVIDUAL_AXIS_HOMING_MENU // 242 bytes
Configuration.h://#define FAST_PWM_FAN // 102 bytes
Configuration.h:#define FAN_SOFT_PWM // 16 bytes
Configuration.h:  #define MAX_MEASUREMENT_DELAY       20    // (bytes) Buffer size for stored measurements (1 byte per cm). Must be larger than MEASUREMENT_DELAY_CM.
Configuration_adv.h:  //#define PID_EXTRUSION_SCALING // 650 bytes
Configuration_adv.h://#define AUTOTEMP // 2204 bytes
Configuration_adv.h://#define SHOW_TEMP_ADC_VALUES // 122 bytes
Configuration_adv.h://#define FAN_KICKSTART_TIME 200 // 116 bytes
Configuration_adv.h://#define FAN_MIN_PWM 50 // 26 bytes
Configuration_adv.h://#define HOME_Y_BEFORE_X // 0 bytes
Configuration_adv.h:#define HOME_AFTER_DEACTIVATE  // Require rehoming after steppers are deactivated // 0 bytes
Configuration_adv.h:#define SLOWDOWN // 166 bytes
Configuration_adv.h:#define LCD_INFO_MENU // 1912 bytes
Configuration_adv.h:#define STATUS_MESSAGE_SCROLLING // 248 bytes
Configuration_adv.h://#define LCD_DECIMAL_SMALL_XY // 154 bytes
Configuration_adv.h:#define LCD_TIMEOUT_TO_STATUS 30000 // 0 bytes
Configuration_adv.h:  #define XYZ_HOLLOW_FRAME // 198 bytes
Configuration_adv.h:  #define MENU_HOLLOW_FRAME // 44 bytes
Configuration_adv.h:  // A bigger font is available for edit items. Costs 3120 bytes of PROGMEM.
Configuration_adv.h:  //#define USE_BIG_EDIT_FONT // 3094 bytes
Configuration_adv.h:  // A smaller font may be used on the Info Screen. Costs 2300 bytes of PROGMEM.
Configuration_adv.h:  //#define USE_SMALL_INFOFONT // 2300 bytes
Configuration_adv.h://#define USE_WATCHDOG // 30 bytes
Configuration_adv.h:#define BABYSTEPPING // 932 bytes
Configuration_adv.h://#define ARC_SUPPORT               // Disable this feature to save ~3226 bytes
Configuration_adv.h:// Support for G5 with XYZE destination and IJPQ offsets. Requires ~2666 bytes.
Configuration_adv.h:// To save 386 bytes of PROGMEM (and TX_BUFFER_SIZE+3 bytes of RAM) set to 0.
Configuration_adv.h:// To buffer a simple "ok" you need 4 bytes.
Configuration_adv.h:// For ADVANCED_OK (M105) you need 32 bytes.
Configuration_adv.h:// For debug-echo: 128 bytes for the optimal speed.
Configuration_adv.h://#define ADVANCED_PAUSE_FEATURE // 6616 bytes
Configuration_adv.h://#define AUTO_REPORT_TEMPERATURES // 290 bytes
Configuration_adv.h:#define EXTENDED_CAPABILITIES_REPORT // 474 bytes
Configuration_adv.h:#define NO_WORKSPACE_OFFSETS // -3146 bytes
```

</details>

**Comment by thinkyhead** [comment]
I'll do the `G30` extension so you can have it in your hands. And it will be a good reference for "how to probe manually" that other G-codes can copy.

**Comment by thinkyhead** [comment]
> below is current state of many Marlin options affect on PROGMEM

That's something I definitely @want to have on the website, so thanks for doing the legwork!

Specifically, we currently have a page covering all configuration options in detail (still needs most of `Configuration_adv.h` added) but I want to do a more concise page just giving an overview of configuration, covering the core settings, plus the most major features, and I wanted to be able to state the cost of each feature.

Of course, the actual cost changes depending on which _other features_ are enabled. For example, enabling bed leveling costs a lot more if you also have an LCD. So, we should be able to state that the cost is A with no LCD, B with a character LCD, and C with a graphical LCD…

A Marlin config utility could then show the predicted size of a build with the selected options.

**Comment by thinkyhead** [comment]
Hmm, I wonder why `AUTO_BED_LEVELING_LINEAR` is so costly compared to the others. Almost twice the cost of `BILINEAR`.

**Comment by Roxy-3D** [comment]
> Hmm, I wonder why AUTO_BED_LEVELING_LINEAR is so costly compared to the others. Almost twice the cost of BILINEAR.

Wonder no more!   Linear bed leveling pulls in the QR_SOLVE library which is huge.    The  least_squares_fit.cpp is very small compared to this.   It is almost trivial to switch from one to the other.  And it will knock 10 KB of program memory off of the image.

**Comment by thinkyhead** [comment]
> It is almost trivial to switch from one to the other. And it will knock 10 KB of program memory off of the image.

That would be great. Let's trim that fat!

**Pull request merged**
