### PR TITLE
MKS_UI compilation error (#22387) fix.

### PR DESCRIPTION
**Pull request by Malderin**
### Description

Fixing compilation error with mks robin nano 2 board, with mksui interface

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/22387

### CODE REVIEW

**Comment by ellensp** [comment]
and https://github.com/MarlinFirmware/Marlin/issues/22349 
and https://github.com/MarlinFirmware/Marlin/issues/21069

**Comment by ellensp** [comment]
Seems to work fine.

**Comment by thinkyhead** [comment]
It seems to me that only things related to `ENABLED(MKS_TEST)` should be in a header called "`mks_hardware_test.h`" so maybe the header and corresponding `.cpp` file ought to be renamed as well.

**Comment by thinkyhead** [comment]
Note: The only way that `mks_test_flag` will ever be equal to `0x1E` is when `SDSUPPORT` is enabled and `mks_test_get` is called by `tft_lvgl_init`. So, code size may be slightly reduced by wrapping code that responds to the impossible `mks_test_flag == 0x1E` in `ENABLED(SDSUPPORT)`.

**Pull request merged**
