### PR TITLE
Change G26 and G29 bit function names to avoid HAL name collision

### PR DESCRIPTION
**Pull request by Roxy-3D**

### CODE REVIEW

**Comment by Roxy-3D** [comment]
Probably this doesn't need to be done to the bugfix_v1.1.x branch because there are no HAL's that conflict with the G26 and G29 bit function names in that branch.

**Comment by Roxy-3D** [comment]
I was also going to add the void G26()  return code fix...   

But Sync didn't get those changes added quick enough.   So that still has to be done.

**Comment by thinkyhead** [comment]
They were done earlier, so were not needed here.

**Comment by Roxy-3D** [comment]
Oh....

**Comment by tcm0116** [comment]
>Probably this doesn't need to be done to the bugfix_v1.1.x branch

But it would be nice if both branches were the same

**Comment by thinkyhead** [comment]
Already done.

**Pull request merged**
