### PR TITLE
[2.0.x] Fix do_probe_move with fr_mm_s

### PR DESCRIPTION
**Pull request by MagoKimbra**
### Requirements

* None

### CODE REVIEW

**Comment by Zwaubel** [comment]
Fixes the issue #10577.
Thanks!

**Comment by thinkyhead** [comment]
Thanks! It's high time we got this consistent across both the homing and probing moves.

**Comment by forkoz** [comment]
can you please merge for 1.1.x... I mistook "Fix homing with probe feedrates" for having this fix applied and now I'm UBL for I think 20 minutes and it has probed 2 spots.

**Comment by thinkyhead** [comment]
Yes, did so immediately following this merge.

**Comment by Roxy-3D** [comment]
> can you please merge for 1.1.x...

Pretty much...  Anything for one branch that gets updated gets updated in the other branch at the 'same time'.    We need to get down to **_ONE_** branch.  But the two branches are in synchronization.

**Comment by thinkyhead** [comment]
Issue 10446 is the very last one holding up 1.1.9. Working on it now!

**Pull request merged**
