### PR TITLE
fix bootloop caused by liquidcrystal library

### PR DESCRIPTION
**Pull request by Vertabreak**
fix bootloop caused by liquidcrystal 1.5.0 by reverting to 1.3.4

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This will need to be tested on several boards / HALs since we were using two different versions before.

See https://github.com/MarlinFirmware/Marlin/commit/770e5398592f2683e6057d44248a9d29bc21c547 for some additional discussion.

**Comment by Vertabreak** [comment]
confirmed on gt2560 v3 with a lcd2004.

**Comment by thisiskeithb** [comment]
>  fix bootloop caused by liquidcrystal 1.5.0

Using `arduino-libraries/LiquidCrystal@^1.0.7` for everything after https://github.com/MarlinFirmware/Marlin/commit/770e5398592f2683e6057d44248a9d29bc21c547 is the issue. We were only using it for LPC before and `bitbucket-fmalpartida/LiquidCrystal@1.5.0` *was* working fine for everything else until it disappeared.

Updating `features.ini` to `USES_LIQUIDCRYSTAL = fmalpartida/LiquidCrystal@1.5.0` and everything works on my BTT002/2004 LCD build. So hopefully `bitbucket-fmalpartida/LiquidCrystal@1.5.0` == `fmalpartida/LiquidCrystal@1.5.0`...?

`ini/lpc176x.ini` could be reverted back to using `custom_marlin.USES_LIQUIDCRYSTAL = arduino-libraries/LiquidCrystal@~1.0.7` again.

**Comment by Vertabreak** [comment]
im going to mess with it a little more this was just my first go to fix.

**Comment by Vertabreak** [comment]
so i tested USES_LIQUIDCRYSTAL = fmalpartida/LiquidCrystal@1.5.0 and found no bootloop on my machine.
it seems that  arduino-libraries/LiquidCrystal@^1.0.7 resulted in bootloop it was auto updating to 1.5.0
but looks like checks are still failing on some boards.

**Comment by thisiskeithb** [comment]
> but looks like checks are still failing on some boards.

Add `custom_marlin.USES_LIQUIDCRYSTAL = arduino-libraries/LiquidCrystal@~1.0.7` back to [`ini/lpc176x.ini`](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/ini/lpc176x.ini) again.

Basically revert https://github.com/MarlinFirmware/Marlin/commit/770e5398592f2683e6057d44248a9d29bc21c547 and only change `USES_LIQUIDCRYSTAL` in `features.ini` to `fmalpartida/LiquidCrystal@1.5.0`, leaving `lpc176x.ini` to use `arduino-libraries/LiquidCrystal@~1.0.7`.

**Comment by Vertabreak** [comment]
lets see how checks end up.

**Comment by descipher** [comment]
fmalpartida/LiquidCrystal@1.5.0 on RAMPS 1.4, MEGA2560, DISCOUNT REPRAP (2004) tested ok so far.

**Comment by Vertabreak** [comment]
I think there gonna maintain there own library instead unsure if I should close the issue. Thanks for running the test 🙂.

**Comment by thisiskeithb** [comment]
This PR will likely be succeeded by https://github.com/MarlinFirmware/Marlin/pull/21704.

**Pull request merged**
