### PR TITLE
G29: Report final position back to host when using MBL

### LINKED ISSUE #3770: ABL issue with probe offset
Am I missing something here?

I have an issues where I cannot configure and then set the Z offset correctly, when auto bed leveling is enabled.
# **Issue 1:**

After issuing  G28,  M114 reports:
RECV: X:65.00 Y:95.00 Z:0.00 E:0.00 Count X: 4622 Y:6755 Z:0
=>As expected

Then I issue G92Z10 & M114, I get:
RECV: X:65.00 Y:95.00 Z:10.00 E:0.00 Count X: 4622 Y:6755 Z:3984
=>As expected

However Z cannot be moved down after the above (if I move it up then Z is correctly set to 11):

SENT: G91
SENT: G1 Z-0.1 F201
SENT:RECV: ok
 G90
SENT: M114
RECV: ok
RECV: ok
RECV: X:65.00 Y:95.00 Z:10.00 E:0.00 Count X: 4622 Y:6755 Z:3984
RECV: ok
# **Issue 2:**

After G28, Z refuses to obey the "Z_PROBE_OFFSET_FROM_EXTRUDER" , essentially I cannot lover the hotend no matter what value I put 
# **I am using:** 

RC6, Ramps 1.4, MEGA, Full discounted LCD & proximity sensor

### PR DESCRIPTION
**Pull request by jbrazio**
Closes #3770, fix by @Blue-Marlin.. but too lazy to submit it !

:beers:

### CODE REVIEW

**Comment by thinkyhead** [comment]
Very nice. Do we also have a PR (or want to extend this) to keep the nozzle where it is at the end of probing, instead of moving it back down to Z=0? On my own setup, I used `MIN_Z_FOR_HOMING` to prevent the nozzle from scraping the bed on the final `G28` after MBL. But maybe I don't need that if all the `G29` routines will leave the nozzle above the bed.

Side note: Since we have `home_offset[Z_AXIS]`, any final move intended to be at the bed height should actually be to Z=`home_offset[Z_AXIS]`, rather than to Z=0 anyway. (Haven't checked the code to see whether that is the case.)

**Comment by jbrazio** [comment]
> Do we also have a PR (or want to extend this) to keep the nozzle where it is at the end of probing

I would say no.. it may cause us more problems than benefits.

**Comment by epatel** [comment]
Well, the reason for doing this reporting is to **not** having to move to `[0,0,0]`. So not adding that change seem confusing I think. I have a commit for this that @brainscan has agreed to test over here https://github.com/MarlinFirmware/MarlinDev/issues/162#issuecomment-219864846

**Comment by jbrazio** [comment]
@epatel but that's is only related with MBL's G29 right ?
MBL is your domain I will not fight for it despite I believe no probing or homing should leave the nozzle touching the bed for obvious security reasons.

**Comment by epatel** [comment]
@jbrazio Yes it is for MBL only. There are request for both behaviors and I do not see this that dangerous, I have actually been using it like that for over a year. But again, I don't leave my hotend hot for long periods of time if I don't print with my printers. Also, if MBL is active it shouldn't drag across the bed as MBL should be compensating the bed as intended. If it is not active, well, then we are back to the discussion about having the endstop at the bed or above (which I consider a much more important security issue, but hey that new stuff is in so what can I do?)

Also, I set the default behavior to not do this move.

Well, I guess there are a lot of printers that have no bed leveling and have the Z endstop on the bed (I guess this would be pretty normal too)

**Pull request merged**
