### PR TITLE
More compatible uint8_t for Experimental i2c Bus buffer

### PR DESCRIPTION
**Pull request by aleknest**
Fix compile error in twibus.h for LPC1768 (SKR 1.3)

### CODE REVIEW

**Comment by sthgardner** [comment]
Still gets theverrors.

**Comment by p3p** [comment]
That's odd has this just started? I didn't change anything to do with Wire and the Wire library still matches the other Arduino frameworks.

**Comment by thisiskeithb** [comment]
What compile error are you seeing? [My SKR 1.3 build](https://github.com/thisiskeithb/Marlin/tree/3a231b39eef9e3ac5f534ebb8764637441209efe) rebased on the latest commit + latest PIO/Lib updates doesn't generate any compile errors.

**Comment by aleknest** [comment]
> That's odd has this just started? I didn't change anything to do with Wire and the Wire library still matches the other Arduino frameworks.

I recently started working on filament change modules and got compilation errors. This was before today's fixes of framework.
Since I began to correct, why not share?)

Знімок екрану_2019-11-03_20-11-24
[conf.zip](https://github.com/MarlinFirmware/Marlin/files/3801930/conf.zip)

**Comment by aleknest** [comment]
> What compile error are you seeing? [My SKR 1.3 build](https://github.com/thisiskeithb/Marlin/tree/3a231b39eef9e3ac5f534ebb8764637441209efe) rebased on the latest commit + latest PIO/Lib updates doesn't generate any compile errors.

Uncomment it
//#define EXPERIMENTAL_I2CBUS

**Comment by p3p** [comment]
It appears the AVR platform builds with "-tpermissive" so this error is ignored, that would explain why this wasn't noticed at least.

**Comment by thinkyhead** [comment]
The platform is wrong-sh. It should say `virtual size_t write(uint8_t const *, size_t)` with `const` on the data pointer, not `const` on the data (or a "promise `const`" on both). Anyway, the compiler seems more annoyed by the sign on the data type.

**Pull request merged**
