### PR TITLE
Show Custom M_Code for Z-Probe Offset when entering M503

### PR DESCRIPTION
**Pull request by floyd871**
It is difficult when you want to adjust the Z-Probe Offset, without knowing the old value stored in EPROM.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Looks good! We should definitely be showing everything stored into EEPROM in `ConfigurationStore`.

Before this gets merged, most headings include a colon and the units, so if you change the heading to `"Z-Probe Offset (mm):"` for consistency it will be all set to go!

**Comment by floyd871** [comment]
Done.

**Comment by hovissimo** [comment]
It would be great to see this in the release branch. Any hope for getting it there soonishly?

**Comment by thinkyhead** [comment]
Hi @hovissimo Release will be updated pretty soon. We are clearing out some last bugs, and after a round of testing, I personally hope to see it released in the first half of June. But actually the Development branch is, today, in very good shape. I recommend trying it out, though watch the configurations, as they have some new and altered options.

**Pull request merged**
