### PR TITLE
Fix for mount not initialized SD card

### PR DESCRIPTION
**Pull request by Serhiy-K**
### Description

I have two test boards - based on LPC1768 and on STM32F401. My SD card 2GB works good with LPC, but with STM not - after inserting SD card LCD panel hangs up until I remove SD card. In my case problem located somewhere in low level STM library. I tried find this problem with step-by-step debugging and oscilloscope but I haven't found yet.

In any case, problem with init SD card may happen any time. So we don't need enter to cdroot() function after wrong SD init and need inform user about problem with his SD card.

### Benefits

This fix excludes panel hang by bypassing cdroot() function after wrong SD init and informs user about problem with SD card on panel in status line.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Marlin now errors out on boot without an SD card inserted. Is there a way to not display the error message on boot?

**Comment by thisiskeithb** [comment]
@Serhiy-K / @thinkyhead: Can this be disabled on boot? I've seen users report this issue of "SD Init Fail" across several Facebook groups now when (intentionally) booting without an SD card inserted which is causing confusion.

**Comment by JaysenSingh** [comment]
@Serhiy-K/@thinkyhead: I’m having the same issue too. Is there any fix for this.

**Comment by thisiskeithb** [comment]
This is still an issue: https://github.com/MarlinFirmware/Marlin/pull/19226#issuecomment-686065814

SD card access/printing worked fine before this change on several different configs, but now users are presented with this false error on boot which doesn't make sense.

Should this patch be reverted?

**Pull request merged**
