### PR TITLE
No Case Light Error

### PR DESCRIPTION
**Pull request by ghost**
If `HAS_CASE_LIGHT` is not defined and `M355` is called, it would break
the serial connection.

I changed it to NOT break the serial connection and make the warning a
little more visible in the serial monitor.

### CODE REVIEW

**Comment by ghost** [comment]
I am trying to keep most of the code intact as it was.
I don't care if it's displayed in the serial monitor, but others might.

The original code was causing my printer to disconnect from the host, if the Case light was not enabled and an M355 was issued.

In my case, I had several gcode files that had already had the M355 injected via slicer setting when it was created.
I had removed the case light and switching to an RGB strip light.
I can go back and remove the M355 commands from those files, oooor correct this to not disconnect the host connection.

**Comment by manianac** [comment]
Honestly this doesn't seem to be a problem with Marlin, but rather the host software disconnecting whenever it sees "error".  If you're using Octoprint, you can disable that behavior.

**Comment by ghost** [comment]
I was aware of this in Octoprint:

"Ignore any unhandled errors from the firmware. Only use this if your firmware sends stuff prefixed with "Error" that is not an actual error. Might mask printer issues, be careful! Warning "

I haven't had any issues that wasn't a show-stopper. So, I should just have Octoprint ignore show-stopping errors because of a case light issue?

**Comment by manianac** [comment]
Just a quick glance, issuing:
- M42 on a protected pin
- M105 without any thermistors
- M145 on an invalid material index
- M261 with a bad i2c request
- M280 with an invalid servo index
- M301 with an invalid extruder index
- M303 without PID heating

all cause an error message which will cause disconnects with OctoPrint.  I think standard Marlin behavior is if you issue a command that shouldn't be present on that firmware (due to your configuration), it will pop an error.

**Pull request closed without merging**
