### PR TITLE
support  bed level with BDsensor

### PR DESCRIPTION
**Pull request by markniu**
Support Bed_Distance_sensor ,This is a high resolution inductive Bed Distance Sensor, it can measure the distance from bed to nozzle with distance resolution 0.01mm in real time. for more details:https://github.com/markniu/Bed_Distance_sensor

Description
Requirements
Need 2 GPIO to communicate to this BDsensor with software master I2C library,so add markyue/Panda_SoftMasterI2C in the ini files. now I have tested on the stm32 based board PANDA_PI_V29 and esp32 based board PANDA_ZHU

Benefits

1,Menu Bed leveling: The Distance between bed and hotend will be displayed on the screen while you do menu bed leveling so you do not need paper.

2,Auto Bed leveling:there is no Z axis up and down while do mesh bed leveling probe,so whole bed leveling will be very fast.

3,Auto adjust hotend at every point in real time.

4, Easy to use, for there is no Z offset setting.

Configurations
Enable this features by #define BD_SENSOR 1 in the Configuration.h , enable #define BABYSTEPPING in the Configuration_adv.h and add lib_deps = markyue/Panda_SoftMasterI2C in the ini file.

### CODE REVIEW

**Comment by PendulumPit** [comment]
Just wondering how many people got this working. 3 of us tried and nope.

**Comment by markniu** [comment]
> Just wondering how many people got this working. 3 of us tried and nope.
I have made an open box video hope that can help someone. https://www.pandapi3d.com/post/install-bed-distance-sensor-video
as far as I know most of the case is because the max sense range is only 4mm and we did not mount it in the sense range, also there is a very weak led light from the sensor in the early version that is hard to see.

**Comment by markniu** [comment]
I have made an open box video hope that can help someone. https://www.pandapi3d.com/post/install-bed-distance-sensor-video
as far as I know most of the case is because the max sense range is only 4mm and we did not mount it in the sense range, also there is a very weak led light from the sensor in the early version that is hard to see.

**Comment by neshami** [comment]
Problem with BDSensor and CR-FDM-v24S1_301 board.
When use pins PC14 and PC13, message "BD_I2C_SENSOR Init Fail return code:-2" on printer init.

**Pull request merged**
