### PR TITLE
Save Bed Leveling to EEPROM

### PR DESCRIPTION
**Pull request by thinkyhead**
Use `M500` to save the current Bed Leveling mesh / grid / matrix to EEPROM
(Only the changed parts of EEPROM are overwritten now!)
Use `M501` to load the last-saved grid from EEPROM.
Use `M420 S1` to enable the loaded mesh / grid / matrix.
Use `M502` to reset the bilinear grid to empty and disabled.

Since `G28` resets the matrix data you must reload it afterward with `M501`. It's recommended that you place `M501` after `G28` at the top of your GCode, but before any commands, like `M92`, `M201`, etc., that change defaults.

Commits:
- `ABL_GRID_POINTS_*` => `ABL_GRID_MAX_POINTS_*`
- Patch `M10` / `M11` hop height un-hopping after Z change
- Fixup `reset_bed_level()` to disable leveling up front
- Minor tweak to `G29` grid points
- Define an "`UNPROBED`" value for points the bilinear grid can't reach
- Re-enable MBL/ABL after `M48`
- Print an error in `M420` if it can't enable leveling
- Improve EEPROM error handling
- Save Bilinear Grid to EEPROM
- Save mbl.has_mesh or abl_enabled flag, not both.
- Save ABL Grid to EEPROM
- Disable bed leveling in `G28` — but don't purge old bed leveling data

### CODE REVIEW

**Comment by boelle** [comment]
could this one maybe be extended to also save LINEAR mode ?

ok if it has to wait

**Comment by manianac** [comment]
I love this feature, will be doing using it today to test

**Comment by manianac** [comment]
Small recommendation, consider bumping the version number to invalidate the eeprom.

The checksum on the old eeprom validated correctly, but everything below home offsets was corrupted, causing some odd issues.

Also: https://github.com/thinkyhead/Marlin/pull/19

**Comment by manianac** [comment]
Yea, I'll keep testing this when I'm able, but I'm going to have to rollback for now.  I can't even imagine why this is happening, overflow possibly?

https://goo.gl/photos/AibCGMpRWGtKTyf58

**Comment by Blue-Marlin** [comment]
Planned range is -999.99 to 9999.99. Possible but unlikely.

**Comment by thinkyhead** [comment]
> Small recommendation, consider bumping the version number to invalidate the eeprom.

It was bumped just a day ago. There may be a few instances of RCBugFix installed in the last 36 hours, but we can ignore them. The EEPROM checksum will catch those.

**Comment by thinkyhead** [comment]
> I can't even imagine why this is happening, overflow possibly?

Under what circumstances does that occur? On initial startup or after `G29`?
Does it also occur if `EEPROM_SETTINGS` is disabled?

**Comment by manianac** [comment]
After G29.  Will have to test without EEPROM later.

The other odd behavior I just noticed is only after G29, Z_HOMING_HEIGHT is not respected.  After issuing a G28 after G29 (just for testing sakes), the hotend drops down to the glass, and homes X/Y.  No change has been made to Z probe height, and works fine before this PR.

**Comment by thinkyhead** [comment]
Sounds like the coordinates (especially Z) after `G29` are simply incorrect.

**Comment by thinkyhead** [comment]
I've dropped the last two commits, so `G29` should itself behave more like it did before. See if this fixes the Z homing height issue. https://github.com/thinkyhead/Marlin/archive/rc_save_your_mesh.zip

**Comment by manianac** [comment]
I will be able to tonight after wwork, roughly 7pm EST

**Comment by manianac** [comment]
Confirmed it behaves properly now, it now lifts and homes without dragging the plate.  Looking through your rollback I'm still not sure what exactly caused it.  

----
Looking into it, it definitely fubars Z steps after the probe_retraction (in this case I have a BLTouch, so I raise to 8mm.

```
Send: N4 M502*32
Recv: echo:Hardcoded Default Settings Loaded
[...]
Send: N6 G28*21
Recv: X:-5.00 Y:0.00 Z:0.00 E:0.00 Count X: -400 Y:0 Z:0
[...]
Send: N7 G29*21
Recv: G29 Auto Bed Leveling
Recv: Bilinear Leveling Grid:
Recv:       0     1     2
Recv:  0 -0.77 -0.72 -0.68
Recv:  1 -0.75 -0.67 -0.73
Recv:  2 -0.82 -0.76 -0.79
Recv: 
Recv: X:262.00 Y:200.00 Z:0.00 E:0.00 Count X: 20960 Y:16000 Z:-2147483648
```

It is after this when I perform a `G28` does it lower into the bed and homes X/Y, then finally homing Z correctly.

**Comment by thinkyhead** [comment]
Next we need to check how `M420` affects the current position after loading a saved grid from EEPROM. If you do `M420 S1` then `M114` then `M420 S0` then `M114` it should vary by the Z adjustment at the current XY point.

**Comment by manianac** [comment]
Checking now, but here is the same command with debugging on (should have turned it on to begin with)

```
Recv:   current_position=(262.00, 200.00, 10.17) : clean_up_after_endstop_or_probe_move
Recv:   current_position=(262.00, 200.00, 10.17) : > probing complete
Recv: Extrapolate [ 1+  1+] (done)
Recv: Extrapolate [ 1-  1+] (done)
Recv: Extrapolate [ 1+  1-] (done)
Recv: Extrapolate [ 1-  1-] (done)
Recv: Extrapolate [ 1+  0+] (done)
Recv: Extrapolate [ 1-  0+] (done)
Recv: Extrapolate [ 1+  2-] (done)
Recv: Extrapolate [ 1-  2-] (done)
Recv: Extrapolate [ 0+  1+] (done)
Recv: Extrapolate [ 2-  1+] (done)
Recv: Extrapolate [ 0+  1-] (done)
Recv: Extrapolate [ 2-  1-] (done)
Recv: Extrapolate [ 0+  0+] (done)
Recv: Extrapolate [ 2-  0+] (done)
Recv: Extrapolate [ 0+  2-] (done)
Recv: Extrapolate [ 2-  2-] (done)
Recv: Bilinear Leveling Grid:
Recv:       0     1     2
Recv:  0 -0.77 -0.70 -0.62
Recv:  1 -0.72 -0.62 -0.65
Recv:  2 -0.78 -0.72 -0.71
Recv: 
Recv: G29 uncorrected Z:10.17
Recv:  corrected Z:0.00
Recv: <<< gcode_G29
Recv:   current_position=(262.00, 200.00, 0.00) : sync_plan_position
Recv: X:262.00 Y:200.00 Z:0.00 E:0.00 Count X: 20960 Y:16000 Z:-2147483648
```

Here is disabling the grid after a G29:
```
Send: N27 M420 S0*83
Recv: X:262.00 Y:200.00 Z:0.00 E:0.00 Count X: 20960 Y:16000 Z:-2147483648
Recv: X:262.00 Y:200.00 Z:-536870.93 E:0.00 Count X: 20960 Y:16000 Z:-2147483648
[...]
Send: N30 M114*20
Recv: X:262.00 Y:200.00 Z:-536870.93 E:0.00 Count X: 20960 Y:16000 Z:-2147483648
[...]
```
And re-enable:
```
Send: N38 M420 S1*92
[...]
Send: N41 M114*18
Recv: X:262.00 Y:200.00 Z:0.00 E:0.00 Count X: 20960 Y:16000 Z:-2147483648
```

Saved EEPROM with `M500`, rebooted printer.  After performing a `G28`, I receive:
```
Send: N21 M420 S1*84
Recv: Error:Failed to enable Bed Leveling
```

**Comment by thinkyhead** [comment]
> It is after this when I perform a G28 does it lower into the bed and homes X/Y, then finally homing Z correctly.

I assume you mean before I removed the problem commits.

I'll post those commits as a followup in a new PR. The issue is that the code that deals with correcting the current position and/or planner/stepper position when enabling or disabling bed leveling is still in flux. There are occasions when it makes sense to get the current position from the stepper positions and convert them back into the XYZ space. Sometimes we want to subtract or undo leveling compensation on some XYZ coordinate. When starting a `G29` with bed leveling enabled, of course it makes sense to disable bed leveling first. This changes the `current_position` so it now corresponds to the stepper positions. But whenever we get a position-in-mm from the steppers into `current_position`, we need to feed it back into the steppers because… float imprecision.

It adds up to some confusion here and there. We'll sort it out I'm sure.

**Comment by manianac** [comment]
On your first statement, correct.  Your redacted commits fix that.

**Comment by manianac** [comment]
On your first statement, correct.  Your redacted commits fix that.

But now I'm concerned, I save the bed to EEPROM, reboot the printer, and issue a G28.  But now a `M420 S1` always results in failed to enable bed leveling.
```
Send: N21 M420 S1*84
Recv: Error:Failed to enable Bed Leveling
```

I've not changed the grid size, so I don't see how the information could've gone stale or corrupted?

**Comment by manianac** [comment]
So looking into the floating point issues, I'm pretty sure the problem is at https://github.com/thinkyhead/Marlin/blob/78a2b8a39ba3e55bc2955865c92c8d6f05b19c37/Marlin/Marlin_main.cpp#L4377 .

I added an extra debug statement
``` C
SERIAL_ECHOLNPAIR(" bilinear_z_offset:", bilinear_z_offset(current_position));
```
And at the end of `G29` I receive
``` gcode
Recv: G29 uncorrected Z:10.17
Recv:  bilinear_z_offset:0.00
Recv:  corrected Z:0.00
```

**Comment by thinkyhead** [comment]
In answer to @boelle's request I've added code to support saving the 36-byte `matrix_3x3` bed tilt matrix for 3-point and grid leveling. I didn't mess with other code (very much) this time around. A full EEPROM re-write with `M502`, `M500` is recommended, of course.

----
> And at the end of G29 I receive
    `Recv: G29 uncorrected Z:10.17`
    `Recv:  bilinear_z_offset:0.00`
    `Recv:  corrected Z:0.00`

@manianac — It almost looks like your code should have a typo, like it's missing the `-` in `-=`:
```cpp
current_position[Z_AXIS] = bilinear_z_offset(current_position);
```
It makes no sense for 10.17 - 0.0 to come out to 0.0.

**Comment by manianac** [comment]
> @thinkyhead — It almost looks like your code should have a typo, like it's missing the - in -=:

I've confirmed its still the same as [your code.](https://github.com/thinkyhead/Marlin/blob/78a2b8a39ba3e55bc2955865c92c8d6f05b19c37/Marlin/Marlin_main.cpp#L4377)


> It makes no sense for 10.17 - 0.0 to come out to 0.0.

I completely agree.  Whether its my RUMBA board flaking out, or a gcc bug, I guess we'll find out if you introduce those changes again and we get more testers.

Thank you for commit a1d8fc94e4bdcd6e9dee4244a36ab02096470eb7, I'll try it more tonight.

**Comment by boelle** [comment]
nice :-D

will try it out first chance i get after its added. But no stress as I want to devote time to figure why my K8200 freaks out

**Comment by manianac** [comment]
Confirmed these latest commits work amazingly well.  9x9 grid surviving resets is a godsend.

**Comment by boelle** [comment]
@manianac so once you have the level data saved you just do a G28 and it still just works? cant wait for that

**Comment by manianac** [comment]
Yes,  pretty much. A M420 S1 is needed after every homing,  but it works.

**Comment by manianac** [comment]
```
---------------------------- Marlin/Marlin_main.cpp ----------------------------
index f22e747..751808d 100755
@@ -3890,6 +3890,10 @@ inline void gcode_G28() {
    *     assist with part placement).
    *     Not supported by non-linear delta printer bed leveling.
    *
+   *  Z  Apply additional offset to Z Probe height. Example: "G29 Z-0.1"
+   *
+   *  X  Only print bilinear bed leveling grid. (Only works if ABL is enabled)
+   *
    *  F  Set the Front limit of the probing grid
    *  B  Set the Back limit of the probing grid
    *  L  Set the Left limit of the probing grid
@@ -3917,6 +3921,12 @@ inline void gcode_G28() {
       if (query) return;
     #endif
 
+
+    if (planner.abl_enabled && code_seen('X')) {
+      print_bed_level();
+      return;
+    }
+
     // Don't allow auto-leveling without homing first
     if (axis_unhomed_error(true, true, true)) return;
 
```

May I suggest some code to print the leveling grid, hell maybe set up M421 to update it if need be?  I hacked this ugly patch together in the mean time, figure the final solution would be more elegant.

Also I never realized 'Z' was in G29 for adjusting the offset.

**Comment by thinkyhead** [comment]
> May I suggest some code to print the leveling grid

@manianac I've added a `V` flag to `M420` to print the leveling grid.

And I've made it so `M421 In Jn Zn` can be used to override mesh points in an _existing_ mesh.

> I never realized 'Z' was in `G29` for adjusting the offset

It's a recent addition for `BILINEAR` only, but I have not had to use it.

I'd be interested to see the current output from `G29 V4` with ABL `BILINEAR` when using `DEBUG_LEVELING_FEATURE` with `M111 S32` to enable lots of logging, and then the output of `M421 V` afterward. I'd like to make sure it's storing the probed points without the probe offset (so a perfectly level Z point is 0.0).

**Comment by manianac** [comment]
I was under the impression you still have to do a full bed measure before
you could see the table. G29 V will show the saved table without measuring
the bed?

**Pull request merged**
