### PR TITLE
Check probes only when deployed

### PR DESCRIPTION
**Pull request by Wackerbarth**
Aim: Test probes in update_endstops only when activated

Changes:
Configurations
 Add define for FIX_MOUNTED_PROBE to handle the situation where formerly ENDSTOPS_ONLY_FOR_HOMING had to be set to lower the nozzle below Z_PROBE_OFFSET_FROM_EXTRUDER without a endstop hit message.
 Add define for Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN to indicate the common situation, that we have a probe but it is connected to an endstop pin
 Add some comments
 Shift some entries to have related thins together.

Conditionals.h
 We have a probe (HAS_Z_MIN_PROBE) if one of the pins is defined and one of the probes is defined.

SanityCheck.h
 Add some tests if the probe is connected and if we have defined a probe.

stepper.cpp
 Changes to test the probe only when it is deployed (z_probe_is_active).
 Test update_endstops() when the probe is deployed.

MarlinMain.cpp
 a. set and reset z_probe_is_active in deploy_z_probe(), stow_z_probe() and dock_sled()
 b. set and reset z_probe_is_active in the case a z-servo is moved to a defined position. The only remaining unhandled servo move is in M280 where we do not end in a defined position. If you want to handle a probe use M401/402
 c. skip deploying/stowing when already deployed/stowed in the dedicated deploy/stow functions.
 d. Handle the new FIX_MOUNTED_PROBE in parallel to a servo driven probe/endstop.

 To do: In an other PR. handle all probes in deploy/stow_z_probe.
 Sort out SERVO_LEVELING vs. HAS_SERVO_ENDSTOPS.

### CODE REVIEW

**Comment by Wackerbarth** [comment]
This replaces #2819

**Comment by thinkyhead** [comment]
I have a bee in my bonnet to help shepherd 1.1.0 through to release — dutifully integrating and applying bug-fixes until reported bad behaviors are no more! Murmurs from the interwebs suggest that we should avoid adding new features or altering configuration options from now on, due to fears that overly-fresh code may be unstable. So I'll put less emphasis on keeping parity with MarlinDev, just focus on integrating confirmed bug-fixes.

With all that in mind, is this PR a necessity (fixes a bug or bad behavior) for 1.1.0?

**Comment by KiteLab** [comment]
Its one of the many needed answers to the problems with hardware endstops / probes, we talked about in https://github.com/MarlinFirmware/MarlinDev/issues/285.
Maybe you have a better one.

**Comment by thinkyhead** [comment]
@KiteLab Honestly, I haven't looked closely at the endstop / probe issues in a while, so I'm happy to defer to those who have been playing with this code more heavily. I'll wait until I've read through https://github.com/MarlinFirmware/MarlinDev/issues/285 before I form any judgment on the solution. In the long run I hope we can make these features relatively simple for end-users while still keeping the flexibility needed for a wide variety of bots.

Is this code also being merged into MarlinDev?

**Comment by thinkyhead** [comment]
Ok, I finally read through all of MarlinFirmware/MarlinDev#285 and I believe I get the gist of the proposed solution. The code should be this way generally, forever-more. If a probe is not deployed, it should not be checked. As an add-on, you might want to disable the probe in-between probing points, even if it is still deployed.

In that conversation you and @Roxy-3DPrintBoard also discussed whether to run the general before/after-probing GCode script in the `stow()` / `deploy()` routines. The conclusions:
- The current script options are intended for the initial `deploy` and final `stow` of things like allen key and sled probes, so you wouldn't want to use them with every individual probe (as with the "E" option).
- And anyway, you can't currently run GCode from within a GCode handler. You can only add it to the end of the queue. The GCode processor needs a hook to allow such chicanery. [Basically moving most of `process_next_command()` into a new `process_command(char *commandStr)` function that can be called from anyplace, and implementing a concise `process_more_commands(char *manyCommandsStr)` function that runs delimited commands immediately. Also, to allow multi-threaded argument-handling, the global `current_command` pointer would need to be replaced with a pointer argument to the command handlers. Another thread on this may exist someplace…?]

Anyway, next I will take a closer look at the commits to see that I fully understand the solutions.

In the longer run, it's good to be looking now at the endstop problem as a whole in a comprehensive way and getting a bird's-eye view. There are two facets of the problem: (1) updating the endstop states, and (2) responding to the endstop states. Within that there is the question of how to relate probes and endstop switches. Maybe we make a general `switches.cpp` interface first, then make `endstops.cpp` and `probes.cpp` as special cases. Or perhaps the current lean-but-distributed approach is still good.

In any case, the most "programmerly" way to approach the problem up-front is to write up a flow-chart or step-by-step list describing the behavior that we want to see realized for each potential configuration.

Next to that, write down the current endstop and probe behavior for each configuration (by having testers use the debug options for homing and leveling or by running the source code in your head).

We ultimately want to know every function that is called, at what time, in what order, and with what parameters. With the "endstop machinery" isolated, it should be much easier to consolidate. And the same with probing and leveling. These functions can definitely all be generalized into instances of "special commands that do info gathering" and "special commands that apply gathered info." It's worth taking a look at the current single-probe GCodes and thinking of ways to take a GCode-based approach to these kinds of processes.

**Comment by Roxy-3D** [comment]
> In the longer run, it's good to be looking now at the endstop problem as a whole in a comprehensive way and getting a bird's-eye view. There are two facets of the problem: (1) updating the endstop states, and (2) responding to the endstop states. Within that there is the question of how to relate probes and endstop switches. Maybe we make a general switches.cpp interface first, then make endstops.cpp and probes.cpp as special cases. Or perhaps the current lean-but-distributed approach is still good.

And, as I'm sure you are aware, the MarlinDev/Jan20 branch has much of this functionality broken out and isolated.   Going forward, it is going to be easier to keep things behaving properly.   All of the probe stuff is in 'probe_management' now.

**Comment by thinkyhead** [comment]
> as I'm sure you are aware, the MarlinDev/Jan20 branch

I'm not dealing with MarlinDev while working on the 1.1.0 patches and documentation, but once the code and documentation are ready for the world I will start to pay more attention to 1.2.x.

**Comment by thinkyhead** [comment]
Rebased to RCBugFix.

**Pull request closed without merging**
