### PR TITLE
Add example configuration files for MakerFarm Pegasus

### PR DESCRIPTION
**Pull request by geeksville**
I don't know if you are looking for more config examples, but if you are you can have this (I'm happy to volunteer to keep it working - the version of Marlin shipped by Makerfarm was very old).

These configuration files are unofficial (community supported) configs for the MakerFarm Pegasus printers.
These configuration files are based off the 1.1.1 template files, but with changes from the (old)
MakerFarm 1.0.2 tree.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
There is a new tool to convert old configuration.h files to the current version.   You should give it a try.   If it doesn't give you what you need to run the current https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x it will be very very close.    

I think you can get it at:  https://github.com/akaJes/marlin-config/releases/tag/2.6.0

**Comment by thinkyhead** [comment]
We don't accept PRs targeted at the current release branch.
You must start from `bugfix-1.1.x` and target PRs to `bugfix-1.1.x`

**Comment by geeksville** [comment]
Ok - will do.  But before I bother - just checking, do you want configs like this or is that something you don't really need anymore (i.e. more configs for different printers)?

**Comment by thinkyhead** [comment]
> do you want configs like this

@geeksville Well… yes and no. If this is a unique printer shipping hundreds of units a month, which uses Marlin, and the vendor doesn't tend to update their firmware very often, then I think it merits being included as a config. Eventually, we may include a simple web tool that produces a config based on much smaller files, but for now we just have to collect them as complete configurations.

**Pull request closed without merging**
