### PR TITLE
[bugfix-1.1.x] Yet another auto build update & add Sublime menu support

### PR DESCRIPTION
**Pull request by Bob-the-Kuhn**
1) Update Auto-build so that it can open the file paths that show up in warnings.

2) Add support file and rough instructions on adding the Auto-build menu to Sublime.  This requires installing the WebDevShell package into Sublime and copying a new menu file to the correct location.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Squashed and rebased. Restored the sublime project file. To update your working copy…

```
git fetch origin
git checkout yet-another-Auto-build-update
git reset --hard origin/yet-another-Auto-build-update
```

**Comment by thinkyhead** [comment]
I've written some simple Sublime packages, including some usage of Python. They're fun to write! Here's one that converts the currently open G-code file into SCARA-compatible G-code:

[CartesianToSCARA.zip](https://github.com/MarlinFirmware/Marlin/files/2025141/CartesianToSCARA.zip)

I've also written a couple that use the usual Ctrl/Cmd-B key combo to build. For example, [my plugin](https://github.com/thinkyhead/6502-Tools/tree/master/Sublime) that…
- runs AtariBASIC (`.LST`) source files in the `atari800` emulator,
- compiles bAtariBasic (`.BAS`) files with `dasm`, running them in the Stella 2600 emulator, and
- provides 6502 assembler syntax highlighting…

not that we need 6502 highlighting! But AVR assembler highlighting could be useful…

Anyway, at some point maybe we could make a more complete Sublime Package out of this, with the menu and the script together in a folder that gets dropped into `Packages/User`, and other useful tools such as one that generates and opens the assembler output.

~~Meanwhile, have you also checkout out the "Deviot" package for Sublime? It might provide some hooks that Autobuild could take advantage of. Last time I used Deviot it had issues, but maybe it's better now.~~

I see you have! Notes about it in the README. Kewl.

**Comment by thinkyhead** [comment]
As per the README, Deviot may be optional if PIO is already installed by another method. I believe it always ends up installed in `~/.platformio` whether installed from Atom, VSCode, or Deviot.

**Comment by Bob-the-Kuhn** [comment]
There's all kinds of things we can do but I think we're pretty close to the point of diminishing returns.

It's to the point where it does what I need when I'm debugging/optimizing code.  Are there other things you want it to do?

The open items that I can think of are:
- Make it play nice with VS.  Do you have any suggestions?  I've just downloaded the free version so I can start playing.
- Document it so that it's easy for the beginner to install & use.
- Get the CDC downloads to work.  I have a Teensylu coming so I can verify if the problems I'm seeing are BrainWave Pro specific.
- Low priority - the at90USB boards don't have a "% used" function.  That wouldn't be hard to add to the tail end of the script.

**Comment by thinkyhead** [comment]
I can’t say much about VS, as they don’t make it for my platform. I’m a big fan of the free Visual Studio Code however, and it should be straightforward to write plugins for. At least as straightforward as Atom, anyway.

**Pull request merged**
