### PR TITLE
[2.0.x] Creality Ender-3 Configuration

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description
Adds support for the Creality Ender-3 based on the [output from the stock firmware](https://pastebin.com/vxV8etsJ) and a combination of the stock Creality configs. I've also "reverse engineered" _Statusscreen.h to match the stock screen config.

### Benefits
The Ender-3 runs Marlin 1.0, so this allows you to run a modern version.

### Related Issues
None.

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks! We'll be happy to add this.

**Comment by thisiskeithb** [comment]
Thank you!

**Comment by datmoe** [comment]
Hello, I could not compile it. I think there is a line like this missing:

#define FAN_ANIM_FRAMES 2

Because when I added it it worked. But I am a noob ;)

**Comment by thisiskeithb** [comment]
It compiled for me before I submitted a pull request. The error is related to `_Statusscreen.h`, which isn't needed & can be commented out from `Configuration.h`

Should I submit another pull request removing `_Statusscreen.h`?

**Comment by datmoe** [comment]
Thank you for your quick reply.
I think _Statusscreen.h is needed, because I want the ender logo on status screen. 
So this file should be fixed.

I compared it to the cr10s _Statusscreen.h and there was the line #define FAN_ANIM_FRAMES in the header.

**Comment by thisiskeithb** [comment]
The fix is to add `#define FAN_ANIM_FRAMES 2` to _Statusscreen.h. I tried to put in a pull request since [I updated my repo](https://github.com/thisiskeithb/Marlin/blob/bugfix-1.1.x/Marlin/example_configurations/Creality/Ender-3/_Statusscreen.h), but Github wasn't having it. @thinkyhead: Can you push this change?

**Comment by thisiskeithb** [comment]
My apologies for not catching this before I submitted the Ender-3 config files. I must have had a weird combination of library versions when I moved from Arduino 1.8 to 1.9 & back down 1.8 that allowed me to compile without errors.

**Comment by thinkyhead** [comment]
Thanks for the update. I'll do the patch first thing in the morning.

**Comment by ModMike** [comment]
Quick question, do I need to flash the boot loader and do I use Sanguino1284 to compile?

**Comment by thinkyhead** [comment]
@ModMike — Yes to both.

**Comment by ModMike** [comment]
USBasp all connected and was waiting for confirmation.  Thanks!

Forgot to ask, I plan to use 2.X bug fix, does it fit on this board?

**Comment by thinkyhead** [comment]
@ModMike — There should be little difference in size between the final binary output of 1.1.x and 2.0.x.

**Comment by ModMike** [comment]
Just a quick note to let everyone know it worked perfect.  Flashed Sanguino boot loader and then Flashed Marlin 2.X with thisiskeithb Ender 3 config.  Not a single warning, let alone error.

**Comment by ModMike** [comment]
I ran into a memory limitation with the sanguino boot loader after activating auto level and a few other features.  Is there an optiboot boot loader I can use instead of sanguino for the Ender 3 (Creality 1.12 controller 1284P).

Thanks.

**Comment by thinkyhead** [comment]
Did a Google search, and according to https://github.com/Optiboot/optiboot …
> Believed to work with ATmega1280 ("Mega"), ATmega644 ("Sanguino"), and ATmega1284 ("Mighty")

**Comment by ModMike** [comment]
I did go through that but finally found info confirming that the boot loader I was using is an optiboot version.  Unfortunately I will need to start disabling a ton of feature or move to another system.

Thanks for responding!

**Comment by thisiskeithb** [comment]
@thinkyhead - It doesn't appear that the fix for _Statusscreen.h was ever made.

Using bugfix-2.0 from [this commit](https://github.com/MarlinFirmware/Marlin/tree/a35abce1acd19da04c160ae5a861dbd086df82fd), I added `#define FAN_ANIM_FRAMES 2` below line 34 in [_Statusscreen.h](https://github.com/MarlinFirmware/Marlin/blob/a35abce1acd19da04c160ae5a861dbd086df82fd/Marlin/src/config/examples/Creality/Ender-3/_Statusscreen.h#L34) & it compiled.

**Comment by ModMike** [comment]
What does your patch fix?  I get a ton of compilation warnings when the screen is enabled.

**Comment by thisiskeithb** [comment]
@ModMike: The original pull request I put in was missing the `#define FAN_ANIM_FRAMES 2` line, which caused compilation errors. @datmoe was the one that originally found the fix.

What errors are you getting?

**Comment by ModMike** [comment]
Here is a sample of the warning I get over and over again.  It just seems to complain about values not being default values.  What do I do to set them as default?
```
In file included from Marlin/src/libs/../inc/MarlinConfig.h:28:0,
from Marlin/src/libs/hex_print_routines.cpp:23:

Marlin/src/libs/../inc/../HAL/HAL_LPC1768/HAL.h:71:0: warning: "ST7920_DELAY_1" redefined
#define ST7920_DELAY_1 DELAY_NS(600)
 
In file included from Marlin/src/libs/../inc/MarlinConfigPre.h:32:0,
from Marlin/src/libs/../inc/MarlinConfig.h:26,
from Marlin/src/libs/hex_print_routines.cpp:23:
Marlin/src/libs/../inc/Conditionals_LCD.h:123:0: note: this is the location of the previous definition
#define ST7920_DELAY_1 DELAY_NS(125)
 
In file included from Marlin/src/libs/../inc/MarlinConfig.h:28:0,
from Marlin/src/libs/hex_print_routines.cpp:23:
Marlin/src/libs/../inc/../HAL/HAL_LPC1768/HAL.h:72:0: warning: "ST7920_DELAY_2" redefined
#define ST7920_DELAY_2 DELAY_NS(750)
 
In file included from Marlin/src/libs/../inc/MarlinConfigPre.h:32:0,
from Marlin/src/libs/../inc/MarlinConfig.h:26,
from Marlin/src/libs/hex_print_routines.cpp:23:
Marlin/src/libs/../inc/Conditionals_LCD.h:126:0: note: this is the location of the previous definition
#define ST7920_DELAY_2 DELAY_NS(125)
```

**Comment by thisiskeithb** [comment]
@ModMike Do you get the same errors if you replace the configs with ones from the CR-10 folder & enable the custom status screen?

If status screens are broken (@thinkyhead may be able to chime in here), then commenting out `#define CUSTOM_STATUS_SCREEN_IMAGE` should let you compile. Hopefully this is worked out before the next release of Marlin.

**Comment by ModMike** [comment]
I can compile no problem, I just get a ton of errors.  Especially:

Marlin/src/libs/../inc/Conditionals_LCD.h:126:0: note: this is the location of the previous definition
#define ST7920_DELAY_2 DELAY_NS(125)

**Comment by thinkyhead** [comment]
The code has been patched. Please test the latest `bugfix-2.0.x` to see that the warning goes away.

**Comment by ModMike** [comment]
```
In file included from Marlin/src/lcd/ultralcd.cpp:105:0:
Marlin/src/lcd/ultralcd_impl_DOGM.h:135:47: error: 'LCD_PINS_ENABLE' was not declared in this scope

U8GLIB_ST7920_128X64_RRD u8g(LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS); // Number of stripes can be adjusted in ultralcd_st7920_u8glib_rrd.h with PAGE_HE
IGHT
^~~~~~~~~~~~~~~
Marlin/src/lcd/ultralcd_impl_DOGM.h:135:47: note: suggested alternative: 'LCD_PINS_D6'
U8GLIB_ST7920_128X64_RRD u8g(LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS); // Number of stripes can be adjusted in ultralcd_st7920_u8glib_rrd.h with PAGE_HE
IGHT
^~~~~~~~~~~~~~~
LCD_PINS_D6
Marlin/src/lcd/ultralcd_impl_DOGM.h:135:64: error: 'LCD_PINS_RS' was not declared in this scope
U8GLIB_ST7920_128X64_RRD u8g(LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS); // Number of stripes can be adjusted in ultralcd_st7920_u8glib_rrd.h with PAGE_HE
IGHT
^~~~~~~~~~~
Marlin/src/lcd/ultralcd_impl_DOGM.h:135:64: note: suggested alternative: 'LCD_PINS_D6'
U8GLIB_ST7920_128X64_RRD u8g(LCD_PINS_D4, LCD_PINS_ENABLE, LCD_PINS_RS); // Number of stripes can be adjusted in ultralcd_st7920_u8glib_rrd.h with PAGE_HE
IGHT
^~~~~~~~~~~
LCD_PINS_D6
*** [.pioenvs/LPC1768/src/src/lcd/ultralcd.o] Error 1
```

**Comment by ModMike** [comment]
OOPS!!!!

Sorry I forgot to update my custom Azteeg X5 GT pins file.  Works now but I do get 1 warning:
```
Compiling .pioenvs/LPC1768/lib656/U8glib-HAL_ID1932/clib/u8g_rot.o
.piolibdeps/U8glib-HAL_ID1932/src/clib/u8g_rot.c:48:27: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
u8g_dev_t u8g_dev_rot = { u8g_dev_rot_dummy_fn, NULL, NULL };
^~~~~~~~~~~~~~~~~~~~
.piolibdeps/U8glib-HAL_ID1932/src/clib/u8g_rot.c:48:27: note: (near initialization for 'u8g_dev_rot.dev_fn')
```
Rest is clean.

**Comment by thisiskeithb** [comment]
Which version of U8GLIB are you using? 1.19 is the latest, but switching to 1.18 should allow you to compile.

**Comment by ModMike** [comment]
The new patch Thinkyhead mentioned above works almost perfectly.  I just get 1 warning now.

**Comment by talldonkey** [comment]
Hi @thisiskeithb I'm curious as to why the X/YJerk values are set to 10, while in the stock Ender-3 Firmware the X/Y Jerk is 20?  I was having rounded corners with the 10 settings even at slow (20mm/s) 
print speeds until I figured out whats going on (because I observed my stock ender firmware printed corners sharper/better!).   I set X/Y Jerk back to 20 and I got my sharp corners without corner swell back.  How intentional was this adjustment?

Same observation for ZJerk, in this config its 0.3, while stock Ender-3 is 0.4.

This can be seen in your [config output you referenced also.](https://pastebin.com/vxV8etsJ)

Jerk Values of 20 and 0.4 can also be seen in the released/open sourced [Creality Ender-3 Firmware](https://github.com/Creality3DPrinting/Ender-3/blob/ae8ca2ababff6da50f4a6620a22d05896e55ca4f/Ender-3%20Firmware%20(Marlin)/Ender-3%20(includes%20power%20failure%20resume-%20English)/Marlin/Configuration.h) at Line 425-427.

**Comment by thisiskeithb** [comment]
@talldonkey The firmware that Creality released is also very old and not an exact copy of what was shipped on your printer. 

New versions of Marlin need those values cut in half (I’m not sure when they made the change), but if increased accel and jerk values work for you, great.

**Comment by talldonkey** [comment]
Thanks - I searched around and found https://github.com/MarlinFirmware/Marlin/pull/8888

**Pull request merged**
