### PR TITLE
Updated pin description for MKS BASE V1.6

### PR DESCRIPTION
**Pull request by DanielMazurkiewicz**
### Description

Pinout description for MKS BASE 1.6 updated

### Benefits

Better pinout description

### Related Issues

#16783

### CODE REVIEW

**Comment by thinkyhead** [comment]
Note that these pins from `pins_MKS_BASE.h` are for features which *may* be optionally enabled, in which the unused extra pins are available for other things.
```cpp
#define CASE_LIGHT_PIN            2

//
// M3/M4/M5 - Spindle/Laser Control
//
#define SPINDLE_LASER_PWM_PIN     2   // Hardware PWM (X_MAX_PIN)
#define SPINDLE_LASER_ENA_PIN    15   // Pullup!      (Y_MAX_PIN)
#define SPINDLE_DIR_PIN          19   //              (Z_MAX_PIN)

#include "pins_RAMPS.h"
```
So, if the board has unused endstop pins, those can be repurposed for a laser or a case light. If these pins are copacetic with 1.6, as they are with previous versions of MKS BASE, then we can replace `#include "pins_RAMPS.h"` with `#include "pins_MKS_BASE.h"` and remove the extra define of `MOSFET_D_PIN`.

**Comment by DanielMazurkiewicz** [comment]
@thinkyhead If if was up to me, actually I would keep clean pin definitions for boards, without any "alternative" features, best solution in my opinion should be introducing 3rd configuration file "configuration_pins.h" where anyone could define all pin modifications against standard board.

**Comment by thinkyhead** [comment]
> …best solution in my opinion…

Whoever brings us a fully reformed and improved system for pins, HALs, and configurations will be carried through the streets as a hero. I only wish I had the time for another big refactor, but at the moment we're busy trying to get STM32 and TMC drivers solid, clearing up extant bugs, improving the UI, and writing a configuration tool.

**Comment by DanielMazurkiewicz** [comment]
@thinkyhead 

> Whoever brings us a fully reformed and improved system for pins, HALs, and configurations

That is rather a big tasks and as there is no money for it I can only help you from time to time with small things, especially ones that affects my printers.

**Comment by thinkyhead** [comment]
> I can only help you from time to time with small things

Drat! What we really need is some interns.

**Comment by DanielMazurkiewicz** [comment]
@thinkyhead 
Has someone applied for interns from Google Summer of Code maybe?

**Pull request merged**
