### PR TITLE
Automatically turn on LEDs on startup

### PR DESCRIPTION
**Pull request by charlespick**
### Description
Adds the option to have the case LEDs turn on automaticlly when the printer is turned on like Flashforge, Makerbot, Ultimaker, etc

### Requirements
LEDs
Tested on an SKR Pro inside a Creator Pro 2

### CODE REVIEW

**Comment by ManuelMcLure** [comment]
Why can this not be already achieved with `CASE_LIGHT_DEFAULT_ON` and/or `LED_USER_PRESET_*` with `LED_USER_PRESET_STARTUP`?

**Comment by ManuelMcLure** [comment]
The only thing I could see is that perhaps `LED_USER_PRESET_*` and `LED_USER_PRESET_STARTUP` require `LED_CONTROL_MENU` - separating those so they can be used at startup without the menu would probably fulfill the requirements.

**Comment by charlespick** [comment]
Apparently case light and the rgb system are different

**Comment by ManuelMcLure** [comment]
Yes, but both have options to enable them automatically at printer boot time.

**Comment by charlespick** [comment]
I'll look into 'CASE_LIGHT_USE_RGB_LED' - might have missed that

**Comment by ManuelMcLure** [comment]
But what your PR does can be done with
```
      #define LED_USER_PRESET_RED          255  // User defined RED value
      #define LED_USER_PRESET_GREEN        255  // User defined GREEN value
      #define LED_USER_PRESET_BLUE         255  // User defined BLUE value
      #define LED_USER_PRESET_WHITE        255  // User defined WHITE value
      #define LED_USER_PRESET_BRIGHTNESS 255  // User defined intensity
      #define LED_USER_PRESET_STARTUP         // Have the printer display the user preset color on startup
```

**Comment by charlespick** [comment]
Having Problems:

```
Marlin/src/feature/caselight.cpp: In static member function 'static void CaseLight::update(bool)':
Marlin/src/feature/caselight.cpp:83:5: error: no matching function for call to 'LEDLights::set_color(LEDColor, bool)'
   83 |     );
      |     ^
In file included from Marlin/src/feature/caselight.h:27,
                 from Marlin/src/feature/caselight.cpp:27:
Marlin/src/feature/leds/leds.h:149:15: note: candidate: 'static void LEDLights::set_color(const LEDColor&)'
  149 |   static void set_color(const LEDColor &color
      |               ^~~~~~~~~
Marlin/src/feature/leds/leds.h:149:15: note:   candidate expects 1 argument, 2 provided
Marlin/src/feature/leds/leds.h:155:22: note: candidate: 'static void LEDLights::set_color(uint8_t, uint8_t, uint8_t)'
  155 |   static inline void set_color(uint8_t r, uint8_t g, uint8_t b
      |                      ^~~~~~~~~
Marlin/src/feature/leds/leds.h:155:22: note:   candidate expects 3 arguments, 2 provided
Compiling .pio/build/BIGTREE_SKR_PRO/src/src/gcode/config/M302.cpp.o
*** [.pio/build/BIGTREE_SKR_PRO/src/src/feature/caselight.cpp.o] Error 1
Compiling .pio/build/BIGTREE_SKR_PRO/src/src/gcode/config/M309.cpp.o
```

Compiling with this configuration:
```
#define CASE_LIGHT_ENABLE
#if ENABLED(CASE_LIGHT_ENABLE)
  //#define CASE_LIGHT_PIN 4                  // Override the default pin if needed
  #define INVERT_CASE_LIGHT false             // Set true if Case Light is ON when pin is LOW
  #define CASE_LIGHT_DEFAULT_ON true          // Set default power-up state on
  //#define CASE_LIGHT_DEFAULT_BRIGHTNESS 105   // Set default power-up brightness (0-255, requires PWM pin)
  #define CASE_LIGHT_NO_BRIGHTNESS          // Disable brightness control. Enable for non-PWM lighting.
  //#define CASE_LIGHT_MAX_PWM 128            // Limit PWM duty cycle (0-255)
  #define CASE_LIGHT_MENU                   // Add Case Light options to the LCD menu
  #if ENABLED(NEOPIXEL_LED)
    //#define CASE_LIGHT_USE_NEOPIXEL         // Use NeoPixel LED as case light
  #endif
  #if EITHER(RGB_LED, RGBW_LED)
    #define CASE_LIGHT_USE_RGB_LED          // Use RGB / RGBW LED as case light
  #endif
  #if EITHER(CASE_LIGHT_USE_NEOPIXEL, CASE_LIGHT_USE_RGB_LED)
    #define CASE_LIGHT_DEFAULT_COLOR { 255, 255, 255 } // { Red, Green, Blue, White }
  #endif
#endif
```

**Comment by charlespick** [comment]
I'm going to close this as it looks like this feature is already meant to be implemented in the case light support, just may need some work or different configurations

**Comment by charlespick** [comment]
> But what your PR does can be done with
> 
> ```
>       #define LED_USER_PRESET_RED          255  // User defined RED value
>       #define LED_USER_PRESET_GREEN        255  // User defined GREEN value
>       #define LED_USER_PRESET_BLUE         255  // User defined BLUE value
>       #define LED_USER_PRESET_WHITE        255  // User defined WHITE value
>       #define LED_USER_PRESET_BRIGHTNESS 255  // User defined intensity
>       #define LED_USER_PRESET_STARTUP         // Have the printer display the user preset color on startup
> ```

Except this requires an LCD, which this printer does not have

**Comment by ManuelMcLure** [comment]
I think a PR to allow the user preset to be used without an LCD would be a good idea.

**Comment by charlespick** [comment]
image
This change is compiling and working. Guessing this is just a bug from a refactor in the past? Should I open a different PR for it?

**Comment by ManuelMcLure** [comment]
Actually, there’s an easier solution that requires no code changes. Just add the appropriate `M150` gcode to `STARTUP_COMMANDS`.

**Comment by charlespick** [comment]
> Actually, there’s an easier solution that requires no code changes. Just add the appropriate `M150` gcode to `STARTUP_COMMANDS`.

While that would work, seems kinda kludgy

**Comment by ManuelMcLure** [comment]
I don’t see why. It avoids proliferation of special case configuration variables, of which there are already more than enough.

**Comment by charlespick** [comment]
In my mind, `STARTUP_COMMANDS` is intended for implementation of things specific to one machine. Turning on the light on startup like every big name 3d printer doesn't seem to fit that category, and indeed someone else thought that so it got implemented in Marlin as `CASE_LIGHT_DEFAULT_ON`.

**Comment by charlespick** [comment]
looks like these compile bugs have been fixed since the last release

**Pull request closed without merging**
