### PR TITLE
Document some DGUS Extensible UI Display firmwares

### PR DESCRIPTION
**Pull request by ellensp**
### Description

I am looking at various DGUS Extensible UI Displays, found it all rather confusing as everything said they use the Marlin
DWIN_SET. But this is not accurate

Added some details to the Configuration.h as to the actually DWIN_SET's each display uses. 
Not sure if you want there here, but is a starting point.  

### Benefits

Less Confusion (perhaps)

### CODE REVIEW

**Review by RipperDrone — CHANGES_REQUESTED** [review]
needs to read 'specified' instead of 'spesified' :-)

**Comment by ellensp** [comment]
@RipperDrone Corrected typo.

**Comment by ellensp** [comment]
Looks like new teensy platform 4.13.0 breaks marlin tests. released 12 hours ago. https://github.com/platformio/platform-teensy/releases

**Comment by thinkyhead** [comment]
Note that I'm trying to work it out so that we have just one `DWIN_SET` that applies to all of our customized DWIN/HMI implementations, with some icons shared and others specific to certain UIs, but I will need to keep whittling down the existing pile of PRs before I will be able to dive into that with gusto.

**Comment by thinkyhead** [comment]
Note that the `DWIN_SET` for Ender-3 V2 is included with its configuration files in the `Configurations` repository, although the screen that comes with the Ender-3 V2 can likely be used with any board.

**Comment by ellensp** [comment]
Do you intend on removing these original UI's? 
"Note that I'm trying to work it out so that we have just one DWIN_SET "  is this in addition to the MarlinUI or are you referring to the MarlinUI?

**Comment by thinkyhead** [comment]
I am referring to all the `DWIN_SET`s that pertain to the Ender-3 V2 display, and only that display. There are currently 3 separate PRs dealing with that display, and I would like to eventually have them all share the same `DWIN_SET`. Even though the `MarlinUI` implementation doesn't need any of the assets from the Creality UI or the Jyers UI, it doesn't hurt to have them on the display, and the `MarlinUI` only adds a tiny amount of bitmap data to the pile.

**Comment by thisiskeithb** [comment]
> Note that the `DWIN_SET` for Ender-3 V2 is included with its configuration files in the `Configurations` repository, although the screen that comes with the Ender-3 V2 can likely be used with any board.

You can now [buy the LCD as a standalone upgrade](https://www.amazon.com/gp/product/B08Y69PPLT) for any Creality 4.x board, but as you noted, it works with just about any board as long as you create the correct cable & setup pins in Marlin correctly. This screen is commonly used on BTT E3 Mini V2 boards for example.

The same goes with the to-be-supported touch screen from the CR-6 SE. You can also [buy the standalone TFT](https://www.amazon.com/gp/product/B08Z3BV26Y) as an upgrade for any printer.

**Comment by ellensp** [comment]
@thisiskeithb I have already helped several people put this LCD on their non creality 4 motherboards. 
It works fine, just needs a serial port correct LCD_SERIAL_PORT and   #define ENCODER_5X_STEPS_PER_SEC    30 (as this is only in ender 3v2 config)

**Comment by thisiskeithb** [comment]
> I have already helped several people put this LCD on their non creality 4 motherboards.

Yes, that’s what I said above. Those LCDs/TFTs will work on other boards with the proper cable and Marlin settings.

**Pull request merged**
