### PR TITLE
Spider support up to 5 hotends

### PR DESCRIPTION
**Pull request by GerogeFu**
FYSETC SPIDER board support up to 5 hotends / extruders

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I'm sure you know your board better than anyone, but does this board really support up to 5 hotends?

These pins are included at the bottom of the Fysetc Spider pins:
https://github.com/MarlinFirmware/Marlin/blob/3b3a3fa84563c6a806e38c9be3c47a0bbbd8a630/Marlin/src/pins/stm32f4/pins_FYSETC_S6.h#L160-L166

 I only see a total of four thermistor inputs on the board as well. 3 for the hotend and 1 for the bed:
<p align="center"></p>

Is there a new revision with more hotend/thermistor input?

**Comment by thinkyhead** [comment]
If you can find some free PWM outputs to attach external MOSFETs for the heaters and ADC inputs for the temp sensors, add them into this and it'll be all set to go.

**Comment by GerogeFu** [comment]
> If you can find some free PWM outputs to attach external MOSFETs for the heaters and ADC inputs for the temp sensors, add them into this and it'll be all set to go.

Yes , this board supports 5 extruder stepper motor outputs E0~E4. So will be possible to support 5 extruders.

**Comment by thinkyhead** [comment]
> Yes, this board supports 5 extruder stepper motor outputs E0~E4. So will be possible to support 5 extruders.

No it won't. Not unless there are also 5 HEATER pins and 5 TEMP_SENSOR pins. Please provide those pins.

**Comment by GerogeFu** [comment]
> > Yes, this board supports 5 extruder stepper motor outputs E0~E4. So will be possible to support 5 extruders.
> 
> No it won't. Not unless there are also 5 HEATER pins and 5 TEMP_SENSOR pins. Please provide those pins.

We may use EXP1 and EXP2 and external heater module even we don't have the module yet, but the board has the possiblity. But it is only my opnion.

**Comment by thinkyhead** [comment]
Sure enough. We don't expand pins for hypotheticals, but for real peripherals. As soon as we have concrete and well-established pin numbers for the extra heater and extra sensor, we can merge this. Only one extra set of suitable pins is needed, since the bed heater can be used for one of the added extruders when there is no heated bed.

**Pull request closed without merging**
