### PR TITLE
Kossel Clear configuration

### PR DESCRIPTION
**Pull request by Vertabreak**
after working with the owner of the machine this is the final fully fine tuned copy of the config.
JPEG_20191211_194831
JPEG_20191211_212221

### CODE REVIEW

**Comment by JohnEcker** [comment]
User here. This is stable code. Would recommend to other Kossel Clear owners. 5 Stars.

**Comment by Vertabreak** [comment]
with a little back n fourth we have come up with this config its ready to go.

**Comment by Vertabreak** [comment]
found a slight issue post first print working on a fix it does print for sure just a slight issue to work out.

**Comment by Vertabreak** [comment]
just working out a slight print skew issue then this will be finished.

**Comment by Vertabreak** [comment]
the skewed print issue has been patched and it should be ready to go now.

**Comment by JohnEcker** [comment]
User here. Did a mechanical tune up and reset from square one. DELTA_RADIUS value was a guessing game until I found, in the old firmware, it had a formula. Came out to 159 and made the printer dead-on-nuts accurate. Good build. Should be print and play for anyone with a similar Kossel Clear.

**Comment by Vertabreak** [comment]
going to call this port complete.

**Comment by thinkyhead** [comment]
Why are you making PRs against your own branch? You can push commits directly to it. Even if you're merging from `upstream`, you can just do `git merge upstream/bugfix-2.0.x` followed by `git push`.

**Comment by Vertabreak** [comment]
still acclimating to GitHub went with what worked last i used the git client made a huge mess in my fork and had to wipe it and start over. i need to wipe it and start clean again soon my base bugfix branch went missing it deleted it self some how and ive been having issue with getting the web site to even merge source at all. it was showing me no changes for like a week and i selected bugfix then selected it again and it showed up it keeps doing it.

**Comment by thinkyhead** [comment]
> my base bugfix branch went missing

```
git fetch upstream
git checkout upstream/bugfix-2.0.x -b bugfix-2.0.x
git push --set-upstream origin bugfix-2.0.x
```

> it deleted it self some how

Maybe you typed this by mistake:

```
git push --delete origin bugfix-2.0.x
```

**Comment by thinkyhead** [comment]
> i selected bugfix then selected it again

Once you've created it, you should set the default branch on your fork to `bugfix-2.0.x` instead of `2.0.x` for convenience.

**Comment by Vertabreak** [comment]
my default branch is bugfix i deleted stable

**Comment by thinkyhead** [comment]
> my default branch is bugfix i deleted stable

Ah, then…

```
git fetch upstream
git checkout upstream/2.0.x -b 2.0.x
git push --set-upstream origin 2.0.x
```

If on the other hand a "`2.0.x`" working branch exists…
```
git checkout 2.0.x
git fetch upstream
git reset --hard upstream/2.0.x
git push --set-upstream origin 2.0.x
```

**Pull request merged**
