### PR TITLE
Move stepper driver defaults to Conditionals_adv.h

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Fixes issues with PR 19798
Test where introduced into Conditionals_LCD.h requiring unavailable setting from Configuration_adv.h   
Moved these tests to  Conditionals_adv.h

### Benefits

Works as expected

### Related Issues

PR #19798

### CODE REVIEW

**Review by thisiskeithb — APPROVED** [review]

**Comment by thisiskeithb** [comment]
Confirmed working on my dual Z TMC config.

**Comment by ManuelMcLure** [comment]
I can also confirm that it fixes my dual Z configuration.

**Comment by discip** [comment]
Yes, that definitely works.

**Comment by Minims** [comment]
Works with my Triple Z too, thx !

**Comment by thinkyhead** [comment]
Thanks! I moved the tests just a bit earlier so some tests in the same file that depend on driver types would also get the benefits.

**Pull request merged**
