### PR TITLE
Fix 8 extruders + Graphical LCD

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

Several macros and variables were not updated to allow 8 extruders.

### Benefits

Fixes errors similar to the following:
```
In file included from Marlin/src/lcd/dogm/status_screen_DOGM.cpp:32:
Marlin/src/lcd/dogm/dogm_Statusscreen.h:1429:1: error: macro "LIST_8" requires 9 arguments, but only 6 given
 1429 |   constexpr uint8_t status_hotend_width[HOTENDS] = ARRAY_N(HOTENDS, STATUS_HOTEND1_WIDTH, STATUS_HOTEND2_WIDTH, STATUS_HOTEND3_WIDTH, STATUS_HOTEND4_WIDTH, STATUS_HOTEND5_WIDTH, STATUS_HOTEND6_WIDTH);
      | ^ ~~~~
```

### Related Issues

N/A

### CODE REVIEW

**Comment by thisiskeithb** [comment]
This is mostly a question for @thinkyhead since Jason and I chatted about this on Discord.

With 8 extruders + bed enabled, only 4 extruders show up on screen. I noticed there's 5 hotend graphics in [`dogm_Statusscreen.h`](https://github.com/MarlinFirmware/Marlin/blob/bugfix-2.0.x/Marlin/src/lcd/dogm/dogm_Statusscreen.h), so I'm not sure what the desired behavior is when enabling this many hotends.

[Link to config with the fix from this PR merged](https://github.com/thisiskeithb/Marlin/tree/testing/btt-gtr-m5)

image

Is anything supposed to be displayed in the blank space on the far right or is this a bug?

**Comment by sjasonsmith** [comment]
> With 8 extruders + bed enabled, only 4 extruders show up on screen.

I wonder how hard it would be to make the view alternate between 1-4 and 5-8.

**Comment by AnHardt** [comment]
An idea from years ago was to display the, most important, current extruder at the fist (left most) place and the others at the second place, cycling at blink rhythm. That would leave space for the bed and fan(s).

**Comment by thisiskeithb** [comment]
I edited my comment above, but: Is anything supposed to be displayed in the blank space on the far right of the image above or is this a bug?

**Comment by thinkyhead** [comment]
> Is anything supposed to be displayed in the blank space on the far right or is this a bug?

This is just awaiting someone to choose a method and implement the behavior. It might, for example, show 1-4 on even blink and 5-8 on odd blink (or, slightly different when a bed / chamber are present). Traditionally, fan / bed would be shown always, but that is negotiable.

**Pull request merged**
