### PR TITLE
menu_item: prevent useless float operations

### PR DESCRIPTION
**Pull request by ramiropolla**
### Description

Don't do +0 on float operations.

Note: this change is untested, but it seems to make sense in the disassembly.

### Benefits

This saves 314 of program memory on my Anet V1.0.

### Related Issues

#21568 #21575

### CODE REVIEW

**Comment by thinkyhead** [comment]
The `-fno-signed-zeros` flag should have the same effect. There is some question whether this flag —or just some other aspect of my NAN patch— was causing bad motion, surely as a result of some hard-to-locate mathematical difference. I wouldn't be surprised if a lack of 'signed zero' could have some effect somewhere in the flow, but on the other hand I can't think of anyplace where it would be depended-upon. So, I've added the flag here to take the chance that it might be safe.

**Comment by rhapsodyv** [comment]
I have only one question: why submit an untested change?

cant you test it and submit something you are sure it’s working?

It’s not a critique. Just a point that we should take more care in marlin: test and stability of the code base.
We are having a really bad with untested changes breaking random things lately.

**Comment by thinkyhead** [comment]
What you're asking for is that we have a stable of testers at the ready at all times, and to assume that if they didn't see an issue after following an exhaustive list of well-defined tests, then there probably isn't an issue. Or, that I myself take on testing as a part of my daily routine, breaking away from the mindset of project management and implementation details and focusing heads-down on boards / printers / debuggers / simulators running print tests and waiting for anomalous behavior.

It's true that I would love to do more testing, and I even brought in a live-in assistant thinking he'd be paying attention to the same things as me and doing QA and testing on everything, but let me tell you about herding cats….

**Comment by rhapsodyv** [comment]
> What you're asking for is that we have a stable of testers at the ready at all times, and to assume that if they didn't see an issue after following an exhaustive list of well-defined tests, then there probably isn't an issue. Or, that I myself take on testing as a part of my daily routine, breaking away from the mindset of project management and implementation details and focusing heads-down on boards / printers / debuggers / simulators running print tests and waiting for anomalous behavior.
> 
> It's true that I would love to do more testing, and I even brought in a live-in assistant thinking he'd be paying attention to the same things as me and doing QA and testing on everything, but let me tell you about herding cats….

No, I'm just asking _PR authors_ to submit things that they can test in some level. Of course that no one can test everything and some changes are simple. But, as the PR author changed the code for _some reason_, I would expect that he tested it and it fix something for him... Or, at least, it don't break a lot of things for others...

**Comment by thinkyhead** [comment]
Well, just looking at my terrible workflow, I know that often these things are just "thrown out there" and even if the author tested something, they most likely have only a limited number of printers and conditions, and as I alluded to, I have not set out –or adopted– a set of tests that should always be run, and a list of every machine that they should be run on. I have not built up a set of automated tests that would immediately catch flaws in something like this proposal.

These things could all be done. I am glad to hear that I am not the only one aware of it. I simply have no expertise, and would need guidance to get these things set up.

But, back to human testers. This is the "cutting edge" bugfix branch and it cannot be guaranteed to be stable, the way it is sometimes used, and so users of this branch are _de facto_ testers. I understand that we constantly advise people to come to the latest nightly build for fixes if the release has a problem. So, maybe some intermediate "beta" branch is needed in-between as a buffer, whereas the bugfix branch can include experimental code sometimes.

The benefit to placing these things before a wider set of users is just that we very quickly catch things from the parallelism of it, and it can happen while I'm asleep. Whereas it is harder to parallelize a half dozen people who happen to have signed on as testers but have other lives. There actually turns out to be some extra value in the randomness of the testers, as much as the parallelism and time-displacement.

I'm trying to find some way to be a bit lazy, so I can focus on implementation and improvements going forward. I don't want to spend too much time managing a lot of humans, with all their expectations, and so on. My shoulders ache from typing, so stuff like that would all have to be moved to Zoom or Discord by Video, or something…

We can discuss more elsewhere. I'd especially like to figure out automated tests.

**Comment by ramiropolla** [comment]
> I have only one question: why submit an untested change?
 
I kind of expected Scott to test since he's done some work in this area recently :). I just checked that the compiled code looked ok. I don't have access to my printer at the moment. And I'm actually just preparing this printer to give it away, so soon I won't have any printer to test anymore.

I see a lot of low-hanging fruits and a lot of potential for improvement in this project. But I can't get involved for personal reasons.

I do have quite a lot of experience with continuous integration and automated testing though. I'm all for a Zoom meeting to share whatever help I can on improving this front.

I just joined the Discord channel, @thinkyhead feel free to ping me there so we can find some time to talk.

**Pull request merged**
