### PR TITLE
Enforce sensor range for temperature target

### LINKED ISSUE #18453: Temperature set above sensor range
### Bug Description

After having noticed, that there was a difference between the readings of the heat bed thermistor compared to the readings of the heater block PT1000 sensor, I searched the web for similar issues, but did not find a solution to my problem yet.

Instead I found someone ,who could probably help here: [Link](https://github.com/MarlinFirmware/Marlin/issues/2912#issuecomment-644555124).

But while following the lead of this nice person (@bsculley) I noticed the dangerous behavior, described in the headline.
**If I would not had an external thermometer attached to the heater block, I would not have noticed, that the temperature kept rising.**

### My Configurations

**[Here](https://github.com/MarlinFirmware/Marlin/issues/2912#issuecomment-646596059)** are the *specs* of my setup and the *demanded files*.

## You should only try to reproduce this, if your setup is capable of withstanding temperatures above 300°C.
(I'm just saying. So you can not blame me, for not having warned you.)
1. In **Configuration.h** change the line **`#define HEATER_0_MAXTEMP 275`** to **`#define HEATER_0_MAXTEMP 315`** and update your firmware on the machine.
2. Attache a thermometer to your heater block.
3. Connect your machine to your PC, set the nozzle temperature to **`300°C`** via *Pronterface* and watch both the readings of the temperature in *Pronterface* and on the attached thermometer.
4. After reaching the temperature you set in *Pronterface* the reading should halt at **`300°C`**, but the reading of the thermometer should rise even further.

**Expected behavior:**

The heater cartridge does not heat past the temperature, which was set.

**Actual behavior:**

The heater cartridge keeps heating way beyond the temperature, which was set.

If there is something not clear enough, or if there are missing any details, please feel free to ask for those.

thank you in advance
kind regards

### PR DESCRIPTION
**Pull request by thinkyhead**
Closing #18453

Currently a temperature can be set beyond what the thermistor or thermocouple can read. This PR adds code to include the thermistor table's top temperature when initializing the temperature range values.

### CODE REVIEW

**Comment by sjasonsmith** [comment]
Is this limiting the requested temperature to exactly the range of the sensor?

If it limits right at the max, it still won't be able to differentiate between a saturated sensor and a temperature runaway. It seems the max temperature should have to be far enough below the saturation point to allow runaway detection.

**Comment by AnHardt** [comment]
Limiting the possible setpoints is one good component to solve the problem.
But extrapolating the tables beyond the limits is the second needed component to make it save.

If ADC-value is below the table take the lowest interval and calculate the temp from it.
Dito for the upper limit with the highest interval.

**Comment by AnHardt** [comment]
The  PT100/1000 resistors have their own problems.
Their temperature table is defined from about -200°C to +850°C - theoretically.
But there is no single existing sensor what can be used in the complete range because either carrier material, hull, ... or isolation degrades at the upper or lower end.

We'd need either a table for each existing realization of a sensor we want to use, or we again have to set meaningful max- and min-temps.

**Comment by thinkyhead** [comment]
> But extrapolating the tables beyond the limits is the second needed component to make it save.
> We'd need either a table for each existing realization of a sensor we want to use, or we again have to set meaningful max- and min-temps.

These are good ideas. This PR is just bringing a little tighter range to prevent setting the temperature outside the allowed range of the sensor at runtime. The "MAXTEMP" set in the configuration will usually be a lower number than the max temp picked up from in the table, and likewise the configured min will usually be a higher value.

I've made this now subtract 1 from the top value in the thermistor table so the topmost celsius value is in the error range. Other code in Marlin already prevents setting the temperature within the `HOTEND_OVERSHOOT` of the "maxtemp" value, so there's no need to account for overshoot in this change.

**Comment by thinkyhead** [comment]
> Their temperature table is defined from about -200°C to +850°C

I've extended it up to 500°C with the same linear interpolation. Maybe it can go higher, but someone should test it to be sure.

**Pull request merged**
