### PR TITLE
Add. Kis3d Silicone heater and precision cast plate thermistor combination

### PR DESCRIPTION
**Pull request by le3tspeak**
**Description**
Added Kis3d silicone heating mat / thermistor combination with precision cast plate 6mm.
To get the correct temperature readings on the surface of the plate.

**Benefits**
Easier for users to find their specific thermistor type.

**Related Issues**
None that I'm aware of.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Do you have a link to this mat/bed combo? Google doesn’t return anything.

**Comment by le3tspeak** [comment]
The combination is now used by many, but there was no suitable thermistor where the exact value provides on the top of the plate

Silicone heating mat: https://kis3d.myshopify.com/collections/two-trees-sapphire-pro/products/silikon-heizmatte-235x235-24v

G.AL® C250 precision cast plate: https://kis3d.myshopify.com/collections/prazisionsgussplatten/products/g-al%C2%AE-c250-prazisionsgussplatte-235x235x5mm-3-5-punkt

**Comment by thisiskeithb** [comment]
> but there was no suitable thermistor where the exact value provides on the top of the plate 

They have this listed on their site: `#define TEMP_SENSOR_BED 1`

It’s not uncommon for temperature readings to be off between the the bottom and top of the build surface depending on material and thickness or addons like glass.

**Comment by le3tspeak** [comment]
And for the comparison measurement, 5 plates and heating mats were used and an average value was determined and the difference was up to 13 ° and a minimum of 11 °, which in my opinion is too much if I use sensor 1 or 11, which has been stated so far

**Comment by le3tspeak** [comment]
So that the correct thermistor can be specified on the shop page for the future.
And also for the printer KiS-3d S235 where is offered to make it as easy as possible for the end customer to use Marlin

**Pull request merged**
