### PR TITLE
Move Hollow Frame options to config-adv

### PR DESCRIPTION
**Pull request by thinkyhead**
- Move the new `DOGLCD` optimizations to `Configuration_adv.h` so they are all in one place.

### CODE REVIEW

**Comment by ghost** [comment]
When `SPLIT_UP_SCREEN_DRAWING` is disabled, GLCD operation is as comfortable as before.

But even if `SPLIT_UP_SCREEN_DRAWING` is disabled, [displaying problems of `m600` when `ENSURE_SMOOTH_MOVES` is enabled and `ALWAYS_ALLOW_MENU` is disabled ](https://github.com/MarlinFirmware/Marlin/issues/5403#issuecomment-265392956) still exists.

__EDIT:__
It looks like only broken first screen is solved. It's skipped simply.

**Comment by thinkyhead** [comment]
> It looks like only broken first screen is solved. It's skipped simply.

Yes, I figured this wouldn't have any effect on the Filament Change problem. I'm back in Portland with my beloved 3D printers so I can debug that tonight.

**Comment by jbrazio** [comment]
@thinkyhead Just uploaded RC8 today and the screen rendering is awful IMO, there shouldn't be a reason when the printer is idle to see the buffer pages being drawn on screen.

This PR should be merged and enabled by default.

One question is the inverted ZYZ rectangle such a penalty hit in order to also be removed ?

**Comment by AnHardt** [comment]
@jbrazio 
I'm working on it. Try preview https://github.com/AnHardt/Marlin/pull/71.

ultralcd_impl_DOGM.h
```
  // Enable to save many cycles by drawing a hollow frame
  #define XYZ_HOLLOW_FRAME
  #define MENU_HOLLOW_FRAME
```
are real time killers. If i remember right ~8ms / full screen update for the status screen.

**Comment by jbrazio** [comment]
If I remember those tests from https://github.com/AnHardt/Marlin/pull/13 they were made without the optimisations brought in by #5204, at the time 8ms was a huge difference, but now does it makes such huge difference in practice ?

I find it more visually appealing to have the invert rect on the main screen and active menus.

**Comment by Blue-Marlin** [comment]
Just test it under critical conditions. It's only one comment and recompiling away.

**Comment by thinkyhead** [comment]
I don't mind submitting this because it outlines where the hooks will need to go. But for the "final solution" we want to have a mash-up where if there's time for the screen to draw the next segment, it will update it right away. But if it looks like the planner buffer needs to be fed, then it will yield back to the main loop until the next `lcd_update` call.

The result will be that the screen will update neatly during idle times, but when the machine needs to keep the planner full it will sacrifice screen perfection for printing perfection.

**Comment by thinkyhead** [comment]
A good mashup of this plus AnHardt/Marlin#13 would be ideal.

**Comment by AnHardt** [comment]
'Adaptive screen updates for all kinds of displays' #5495 hopefully solves most of the problems.

@thinkyhead 
Most of the ideas i developed in https://github.com/AnHardt/Marlin/pull/13 are now in RCBugFix or are about to go in there, in a improved manner. The single remaining idea, is to split up the big monolithic heater graphic. To implement that, needs a bit of discussion about, how it should look at the end, what to display where, and how a similar concept could be realized for the char-displays.
With up to 4 hotends, up to four part fans, bed-, environment-, chamber-, chocolate-reservoir-, ...,  temprature the 5 places in the top row are not enough to display them all at once. On the char displays it's even worse.
For the 128x64 displays i suggest to display:
* The current hotend at the left most place
* Altering through the remaining hotends at the next place
* Altering through the part fans at the right most place
* Alter between the remaining heaters at place 3 from the left
* and displaying the measured temperatures without heaters between these and the fans.
* If any of this block is not used, it is omitted  and the remaining blocks can be re positioned to fill the space nicely.

For the char displays i suggest to display:
* The active hotend at the first place
* Altering the remaining hotends at the second 'extruder' place - if this is available. Else alter all hotends at place one.
* Use the bed-temperature-place for the bed and all other 'heaters'.
* Measured only temperatures and fans are not displayed.

Reorganizing the heaters to a array of heater-structs (objects) may help to eliminate the extra bed heater code but is not essential for the 'graphics-project'.

**Comment by thinkyhead** [comment]
I do like the idea of alternating through the extra heaters and fans that can't fit on the screen. Maybe then we need to put numbers on the heaters.

If there's a redesign to be done in the screen layout, heater graphics, etc., then count me in. I enjoy pixel-art. I presume that with 4 stripes, we should aim for graphics that are no more than 16 pixels tall, so they draw only once, distribute them vertically, if possible.

128x64 should is a challenge to work with. The info screen can of course have more than one full screen page, alternating between different whole displays, if we need it.

**Comment by AnHardt** [comment]
The symbols i made for https://github.com/AnHardt/Marlin/pull/13 are only 12 pixel high and numbered. 
extruder extruderon extruder0 extruder0on extruder1 extruder1on extruder2 extruder2on extruder3 extruder3on extruder4 extruder4on bed bedon fan1 fan2 sd_in sd_out

The fan is 18x18 but does not need target __and__ current value. The black spot in the middle can be enlarged to fit a number in - i hope.

With our 7 pixel high numbers and one pixel space, two rows of text would exactly fit in a 16 pixel stripe. If we'd draw: 

220°
219°
extruder

above each other, in this order, nothing would have to be drawn twice - except the fan graphics.
Do we need more than one bed?

An other idea is to make a proportional font for the numbers. That would save some space in the horizontal. Would complicate the positioning a bit. "0123456789.°%+-". Savings could be in '1', '.','°'.
However currently we are limited to 128/6 = 21.33 -> 21 chars. 21/4 chars = 5.5 -> 5 places The remaining 0.5 is just enough to have things separated a bit. For the heaters we can only trust in a saving at the '°' symbol -> not enough for a 6th position.

When trying to distribute the heater to two rows and 3 columns, the fan would need 2 rows -> again 5 places. 
Two rows 4 columns? 21/4 = 5.25 chars. "123/123" needs at least 6 better 7 chars -> no chance.
With a narrower 4th column? (21-4) / 3 = 5.6 -> no chance.

Any other ideas?

**Comment by AnHardt** [comment]
Fans 18x18
fan1
fan2
fan1-0
fan2-0
fan1-1
fan2-1
fan1-2
fan2-2
fan1-3
fan2-3
fan1-4
fan2-4
fan2-0alt alternative 0
fan1-0alt alternative 0

**Comment by AnHardt** [comment]
Some alternatives for 16x16 fans
v0 18x18 without frame
fan16_1 fan16_1-0 fan16_1-0alt fan16_1-1 fan16_1-2 fan16_1-3 fan16_1-4 
fan16_2 fan16_2-0 fan16_2-0alt fan16_2-1 fan16_2-2 fan16_2-3 fan16_2-4 
va readd frame and make 1 pixel space
fan16_1-0a fan16_1-0alta fan16_1-1a fan16_1-2a fan16_1-3a fan16_1-4a fan16_1a 
fan16_2-0a fan16_2-0alta fan16_2-1a fan16_2-2a fan16_2-3a fan16_2-4a fan16_2a
vb shrink the rotor when diagonal
fan16_1-0altb fan16_1-0b fan16_1-1b fan16_1-2b fan16_1-3b fan16_1-4b fan16_1b 
fan16_2-0altb fan16_2-0b fan16_2-1b fan16_2-2b fan16_2-3b fan16_2-4b fan16_2b
vc enlarge the corners
fan16_1-0altc fan16_1-0c fan16_1-1c fan16_1-2c fan16_1-3c fan16_1-4c fan16_1c
fan16_2-0altc fan16_2-0c fan16_2-1c fan16_2-2c fan16_2-3c fan16_2-4c fan16_2c

Have to see them animated - but vc seems to be good.

**Comment by AnHardt** [comment]
Some other 12x12 symbols
a12x12 a12x12on
b12x12_1 b12x12_2
c12x12
d12x12 d12x12_on
e12x12 e12x12_on

__Can you find out what i had in mind?__

**Comment by AnHardt** [comment]
In the end could look like:
```
321° 321° 321°      FANG  __ 8 pixel
123° 123° 123° 123° FANG  __ 8 pixel
EGR  EGR  BEDG ENVG 100%  __12 pixel
                          __ 4 pixel remaining for the upper half of the coordinate bar
```
EGR = extruder/nozzle graphic with matching number.
BEDG = Bed or other heaters graphic.
ENVG = environment or other temperature we only measure but not heat.
FANG = numbered fan graphic.

**Comment by AnHardt** [comment]
5x7 art for the character displays.
The combinations of a letter 'B'ed, 'C'hamber, 'E'nvironment, 'N'ozzle, 'P'aste, 'R'eservoir with the '°'Grad symbol could save the '°' at the end and would make room for a nozzle-number in normal size. Maximal three of the symbols are in use at the same time.
environment
gradbed
gradchamber
gradenvironment
gradnozzle
gradpaste
gradresevoir
nozzle
nozzle0
nozzle1
nozzle2
nozzle3
nozzle4
paste
resevoir
bed
chamber

(somewhere in your browser should be a '+'-button to enlarge the content)
Formats for a single entry could be ether

N'symbol_with_°'123/321
or
'symbol_with_number'123/321°

with N = single digit number.
 - A matter of taste.

**Comment by thinkyhead** [comment]
A lot of good stuff, there.

I don't know if we need a new graphic for a second bed. If there's a 2-zone bed, perhaps it can just be drawn twice.

I like the stacked columns layout. And it would be good to have smaller fan graphics. That's a lot of space that can be put to better use.

Comes out to be 14 x 3 for three heaters:

`190° 190° 190°`
`150° 184° 189°`
   extruder0on      extruder1on       extruder2on

----
Slightly more compact use of 3 lines (i.e., 9 x 3):

extruder0on`150|190°`
extruder1on`184|190°`
extruder2on`189|190°`

----
> Have to see them animated - but vc seems to be good

Yes, I like the more rounded inner-corners. Makes it more fan-like.

> Some other 12x12 symbols
a12x12 a12x12on
b12x12_1 b12x12_2
c12x12
d12x12 d12x12_on
e12x12 e12x12_on
>
> __Can you find out what i had in mind?__

I didn't score high:
- Bed heater: off on
- Chamber heat: off on
- ???
- Power: on off ?
- ???

**Comment by AnHardt** [comment]
How about 'mini nozzle information center'?
mini_nozzle_information_center_enlarged
From the left top clockwise:
* Power bar for the Nozzles heater
* Part-fan. Omitted when off - animated when on
* Power bar for the part fan
* Auto-fan. Omitted when off - animated when on
* Nozzle number. Omitted for current nozzle. (Or 'C'?)
* Nozzle symbol

Bed with power bar:
mini_bed_information_center_enlarged

Chamber with power bar:
mini_chamber_information_center_enlarged

These are small enough to have 3 rows.
But they are __very__ small!

Elements:
          c nozzle bed fan0 fan1 inside outside 
For comperation the fonts zero:
fons_zero mini_inside_information_center mini_nozzle_information_center mini_outside_information_center mini_bed_information_center
Fans stand alone (7x7):
fan_standalone0 fan_standalone1

**Comment by AnHardt** [comment]
Shrinked that far we have place for ether:
up to 5 elements with one row, 5 columns,  
`123° 123° 123° 123° 123°`
` `    mini_nozzle_information_center  ` `    mini_nozzle_information_center   ` `   mini_nozzle_information_center   ` `   mini_nozzle_information_center   ` `    mini_bed_information_center
`321° 321° 321° 321° 321°`
or 
up to 6 elements with three rows, 2 columns.
 mini_nozzle_information_center123|321°  mini_nozzle_information_center 135|531° 
 mini_nozzle_information_center123|321°  mini_nozzle_information_center 135|531° 
 mini_nozzle_information_center123|321°  mini_bed_information_center 135|531° 

Both varieties would use 24 pixel in the high.
No element is drawn in more then 1 stripe.
The 'coordinate bar' could begin 4 pixel higher. For the inverse bar this is still not enough to fit completely into the upper half. But drawing only one row of pixels in the second half will solve that. The framed bar will need two rows more.
The fans could be extra or integrated into the 'nozzles'.

**Comment by AnHardt** [comment]
I see a 'Configuration_GLCD_status_display_content.h'.
Here we could set up an array of display positions, pointing to arrays where the items are listed what to alter at that position - pointing to the drawing functions. Switching between 1x1-5 and 3x2 could be automated with n_display_positions<6.
While at it, we could do something similar for the content of the 'coordinate bar'. Maybe switching the content when running a program.

**Pull request merged**
