### PR TITLE
menus: allow 0.025mm moves on Z axis

### PR DESCRIPTION
**Pull request by tpruvot**
Can be useful to test Z probes.

**If** Z steps are 400/mm, 0.025mm = 10 steps

### CODE REVIEW

**Comment by thinkyhead** [comment]
I'm betting you could have done more than just the English and French translations….

**Comment by tpruvot** [comment]
indeed, but we only do a french and an english firmware

**Comment by tpruvot** [comment]
ok lol, you were faster than me

**Comment by thinkyhead** [comment]
Regular expression magic.

**Pull request merged**
