### PR TITLE
Make external override of configurations easier

### PR DESCRIPTION
**Pull request by thinkyhead**
This sweeping change allows configuration options that are enabled with `#define MY_OPTION` (switches) to be overridden externally by defining them as `0`, `1`, `false`, `true`, or as a simple `#define`. If defined as `0` or `false` the `ENABLED` macro returns `false` (unlike `#ifdef` or `defined`). If defined as `1`, `true`, or with no value, the `ENABLED` macro returns `true`. Allowing configuration switches to be set to `0` or `false` makes them overridable through a Makefile or by prefixing with an `#include`.

To override an option this way assumes that the compiler will ignore subsequent attempts to `#define` the setting. For the cleanest usage, this allows a block like:

```
#ifndef MY_SETTING
  #define MY_SETTING
#endif
```

With this change, you could put only a few settings into a separate file – and `#include` it at the top of `Configuration.h`, and the compiler will pass those values through, including disabled switches.

Options that are enabled by setting some other value are not affected by this change, which is especially suited to options that are disabled by default or rely on conditions to be enabled.
- Create `macros.h` for… macros
- Add `ENABLED` / `DISABLED` macros to test whether options are enabled
- Supplant `#ifdef`, `#ifndef`, `defined` and `!defined` with new macros

### CODE REVIEW

**Comment by Wackerbarth** [comment]
@thinkyhead  You need to rebase your changes to the current dev branch so that we can see them without all of the other changes cluttering the diffs

**Comment by thinkyhead** [comment]
@Wackerbarth Will do, pretty soon. Gotta fix a typo…

**Comment by thinkyhead** [comment]
@Wackerbarth This PR really does change 108 files.

**Comment by AnHardt** [comment]
Do these ENABLED(), DISABLED() -macros really improve the readability of the code?

At least not for me. Everyone who knows a bit of the c language at least knows what #ifdef, #ifndev, defined() are for. The names of the macros are well chosen and what they do is quite intuitive, but when i tried to understand how they work, i had a hard time (and i'm still not sure if i really got it).

**Comment by Wackerbarth** [comment]
I think that the real purpose is to provide a true/false indicator rather than the tri-state true/false/undefined.
That way, a flag can be defined to be false rather than just having defined/undefined as proxies for true/false.

**Comment by thinkyhead** [comment]
> Do these ENABLED(), DISABLED() -macros really improve the readability of the code?

These macros are not for beauty – they are required for settings to be overridable. Under the current system we use `#ifdef`, `#ifndef` and `defined`. These are problematic because you can't set them as "not enabled" from an external source like a Makefile. All you can do is to not define them. So, this doesn't work: `#ifndef THING … #define THING … #endif`. This PR replaces all use of `defined` with `ENABLED` so that a symbol can be `0` or `false` in addition to being `undefined`. All 3 of these count as `!ENABLED`.

**Comment by AnHardt** [comment]
@thinkyhead 
Ahhh. Now i got it.

**Comment by thinkyhead** [comment]
#2169

**Pull request closed without merging**
