### PR TITLE
Follow up the PR #5167 (Add Turkish Language), etc

### PR DESCRIPTION
**Pull request by ghost**
Follow up the PR #5167 (Add Turkish Language), etc

・Remove all the `#ifndef`
・Follow the PR #4603 (Strip never-translated strings from language files)
・Follow the PR #4634 (Set language display charset in language.h)
・Follow the PR #4936 (Put max_jerk vars in array, clean up jerk code)

・Add new Turkish translation that it's [suggested by @Rigid3D](https://github.com/MarlinFirmware/Marlin/pull/5171#issuecomment-258698904)

| directive | translation | notes |
| --- | --- | --- |
| `MSG_BLTOUCH_SELFTEST` | `BLTouch Self-Test` | same as original English |
| `MSG_BLTOUCH_RESET` | `Sýfýrla BLTouch` | |
| `MSG_ERR_Z_HOMING` | `G28 Z Yapýlamaz` | |
| `MSG_DRIVE_STRENGTH` | `Sürücü Gücü` | |
| `MSG_DAC_PERCENT` | `Sürücü %` | |
| `MSG_DAC_EEPROM_WRITE` | `DAC'ý EEPROM'a Yaz` | |

・Adjust spacing

### CODE REVIEW

**Comment by ghost** [comment]
@Rigid3D
on newest RCBugFix, some new strings were added.

・https://github.com/MarlinFirmware/Marlin/pull/4789 (Various cleanups ahead of more…)
[`MSG_ERR_Z_HOMING`](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_en.h#L421) was added

・https://github.com/MarlinFirmware/Marlin/pull/4856 (Fix and extend BLTouch support)
[`MSG_BLTOUCH_SELFTEST`](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_en.h#L373) and [`MSG_BLTOUCH_RESET`](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_en.h#L376) were added

・https://github.com/MarlinFirmware/Marlin/pull/4967 (Revised DAC Drive Strength Menu)
[`MSG_DRIVE_STRENGTH`](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_en.h#L536), [`MSG_DAC_PERCENT`](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_en.h#L539), and [`MSG_DAC_EEPROM_WRITE`](https://github.com/MarlinFirmware/Marlin/blob/RCBugFix/Marlin/language_en.h#L542) were added

**Comment by ghost** [comment]
@esenapaj Sorry for the not complete translation and thank you for your corrections. I actually worked on the RC version and missed some things.

I have translated the new messages but I couldn't add them to this pull request maybe you can add it.

``` cpp
#define MSG_BLTOUCH_SELFTEST              "BLTouch Self-Test"
#define MSG_BLTOUCH_RESET                   "S\xfd\x66\xfdrla BLTouch"
#define MSG_ERR_Z_HOMING                    "G28 Z Yap\xfdlamaz"  
#define MSG_DRIVE_STRENGTH                 "\x53\xfc\x72\xfc\x63\xfc \x47\xfc\x63\xfc" 
#define MSG_DAC_PERCENT                      "\x53\xfc\x72\xfc\x63\xfc %"  
#define MSG_DAC_EEPROM_WRITE           "DAC\x27\xfd EEPROM\x27\x61 Yaz"  
```

**Comment by ghost** [comment]
@Rigid3D
I've added those.

**Comment by yhfudev** [comment]
Hi, I noticed that you added the Turkish recently, and I'm maintaining a UTF-8 patch (https://github.com/MarlinFirmware/Marlin/pull/4704), so can you please to upload a UTF-8 version of this language so both of the branches may keep sync?

Or it would be better if your language contents like this:

``` C++
// string format:
//#define MACRO <tranlated string> // _UxGT(<utf8 string>) // <english string>

#define MSG_BLTOUCH_SELFTEST "BLTouch Self-Test"     // _UxGT("BLTouch Self-Test" ) // "BLTouch Self-Test" 
#define MSG_BLTOUCH_RESET "S\xfd\x66\xfdrla BLTouch" // _UxGT("Sýfýrla BLTouch") // "BLTouch Reset"
```

Thanks!

**Comment by thinkyhead** [comment]
Thanks again, @esenapaj. I should have caught the `#ifndef` lines at the very least.
As usual I'll blame it on not enough sleep.

**Comment by thinkyhead** [comment]
@yhfudev Good to see you! I still look forward to merging your UTF-8 patch. It's kind of grown on me, and I'm less worried about performance issues. There are certainly more important bottlenecks I should focus on. If you need any further help getting it into shape, let me know.

**Comment by ghost** [comment]
@yhfudev 
If you want a `language_tr_utf8.h`, you need to explain to @Rigid3D the necessity of it and have him (them) create it.
Because maintainer of Turkish is only @Rigid3D at this time.
I'm not sure about Turkish language, I can only convert character encoding.

**Comment by thinkyhead** [comment]
@Rigid3D Can you add a UTF-8 version of Turkish for us? Use the other UTF-8 files for guidance, and consult with @yhfudev if you get stuck.

**Comment by ghost** [comment]
@thinkyhead OK I was planning to work on it this weekend. I think I will be able to post it next week.

**Pull request merged**
