### PR TITLE
Example configuration for Prusa i4 printer.

### PR DESCRIPTION
**Pull request by webhive**
Here is example configuration for Prusa i4 printer -- chineese clone of Prusa i3.
Tested it on my own printer and it work fine.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
One question I have is the Prusa i4 owners would normally be running the Prusa version of Marlin, right?  Does it make sense to add another Configuration.h file example here if it won't be used?

**Comment by webhive** [comment]
Prusa i4 has own Marlin version of 29 May 2015. So it outdated for 2 years. This configuration just a migration to v1.1.1. So I used diff tool to get a difference, updated corresponding values and tested on my own printer.

So this configuration for owners who want to upgrate Marlin to v1.1.1. Manufacturer does not updated firmware so I did it myself. Really my reason to upgrade was attempt to test autolevel feature. I just wainting for leveling sensor and while wainting for it decided to get latest firmware possible.

**Comment by Roxy-3D** [comment]
How difficult would it be to move over the Prusa alignment code too?   With that, it is possible the Prusa i4 owners would start migrating back to the main Marlin branch?

**Comment by webhive** [comment]
I don't know. Really firmware I got from supplier was in broken archive file and I have lot of notices about same broken firmware files from other owners of such device. So found original firmware on one of shops selling it. And also I did attempt to rollback to original firmware (just to check if it work). But original firmware requested some old version of Arduino so finally I stopped my attempt.

So current situation is -- we have Prusa i4 with some outdated firmware from 2015 and it does not work with new Marlin v.1.1.x because has no configuration for it. Just because manufacturer does not care. So currently no way to use latest Marlin on this device until someone will adjust configuration. 

Really I dont see a problem -- I dont try to modify original Marlin code, but just add some example configuration.

**Comment by jhitesma** [comment]
I was confused by this at first too and wondered "why don't they just use the Prusa release" but then I realized "i4?  Wait..what?"  Prusa has never released an i4.  The "Prusa i4" has nothing to do with Prusa or their firmware, it's a Chinese clone that is somewhat different in design than real Prusa machines: http://forums.reprap.org/read.php?1,666165

So this isn't actually running the Prusa firmware with their alignment code, it's just another Chinese printer that used a confusing name.

**Comment by Roxy-3D** [comment]
Yeah...   It looks like the Prusa machines jump from i3 to the MK series.     

I think we can include it.   The reason there is some question about whether it should be included is every time we change or add options to the Configuration.h files...   It is "Yet Another File Set" that has to be updated...

**Comment by fiveangle** [comment]
I would be hesitant to add any example config named "Prusa"-anything other than a printer made by Prusa Research.  This Sunhokey (😂) i3 clone they conveniently named "i4" to try and confuse some into thinking it is a new PR varient is a big sour.  It's just a reprap with some nutty board stuck stuck in it, so seems more wrought for confusion than clarity.

reprap sunhokey i3

Regarding the maintenance angle, I would think you'd want to maintain a minimal number of configurations that cover the bulk of what most users would need for examples, preferably with some value add as well (for example, an AT90USB based cartesion example that may also be a super popular device that was somewhat abandoned by their original designer [cough]printrbot[cough] and so would see a reasonable amount of traffic by users looking here to do major software heart surgury on their old 'bot)

**Comment by webhive** [comment]
@jhitesma Yes it is not a really an original Prusa. Just some chineese clone. Anyway even if Prusa will do i4 version there will be a big confusion because internet full of Prusa i4 links to this device.  

Anyway I just tried to share working configuration. If you dont want to use prusa folder - may be move it to some else place. I dont think 2 files of exampple configuration break something. But from other side - more ready to go configurations - more people can try this firmware.

**Comment by Roxy-3D** [comment]
> I would be hesitant to add any example config named "Prusa"-anything other than a printer made by Prusa Research. This Sunhokey (:joy:) i3 clone they conveniently named "i4" to try and confuse some into thinking it is a new PR varient is a big sour. 

yeah...  If we add this... We probably want to change the name to Sunhokey-i4

**Comment by webhive** [comment]
Hmm may be better I will prepare detailed readme about situation with this printer? I a afraid no one know this printer as Sunhokey-i4 and ... really weird situation when real Prusa i4 will appear I think there will be a big confusion :)

**Comment by thinkyhead** [comment]
> We probably want to change the name to Sunhokey-i4

Definitely. Out of respect for Josef, who does not approve of this specific use of his name.

**Comment by thinkyhead** [comment]
You'll need to make a new PR targeting the `bugfix-1.1.x` branch, so this PR is closed.

**Pull request closed without merging**
