### PR TITLE
Prefer MAX6675 SPI pins for MAX31865 over SPI pins

### PR DESCRIPTION
**Pull request by ghost**
### Description
MAX31865 sensor is tied to the MAX6675 sensor's functions by HEATER_0_USES_MAX6675
MAX6675 has sanity checks that look for MAX6675_SS_PIN. 
I propose to use MAX6675_SS_PIN instead of CS_PIN, so as to have only MAX6675_SS_PIN declared in the pins file. Otherwise we have to declare both MAX6675_SS_PIN and CS_PIN in the pins file, on the same pin number, or else it doesn't work.
That, or adjust sanity checks to look for either MAX6675_SS_PIN or CS_PIN.
### Benefits

removes the need to have both MAX6675_SS_PIN and CS_PIN declared in pins file, for the MAX31865 sensor to work.

### CODE REVIEW

**Comment by ghost** [comment]
this would work for hardware SPI, but if using software SPI, we'd need to have both  MAX6675_SS_PIN and MAX31865_CS_PIN declared in pins files.
I think fixing the sanity checks to look for either MAX31865_CS_PIN or MAX6675_SS_PIN is the simplest way.
This way for hardware SPI we declare MAX6675_SS_PIN in pins file, for software SPI we declare MAX31865_CS_PIN + MAX31865_SCK_PIN + MAX31865_MOSI_PIN + MAX31865_MISO_PIN.

**Comment by thinkyhead** [comment]
In the long run we want to be able to allocate hardware / software SPI buses more freely to each feature that wants one, at least to be able to combine the (main) hardware SPI with an arbitrary number of software SPI buses.

**Comment by AnHardt** [comment]
@thinkyhead 
We should care a bit more about naming! (again ;-) )
It's the same mess as with ULTIPANEL. MAX6675 was just the first of this kind.
`MAX6675_IS_MAX31865` is logical crap.
It means MAX31865 is a temperature sensor using SPI in (almost) all cases.

In the end, when we can use SPI temp sensors for all temperatures and they can be of different kind, we will need something like this:
```
// define SPI buses/masters
#define SOFT_SPI1 {sclk_pin, miso_pin, mosi_pin} // With optional MOSI for read only  buses (-1)

// select a bus for the temp-sensors
//#define SPI_TEMP_SENSOR_BUS HARDWARE_SPI1
#define SPI_TEMP_SENSOR_BUS SOFT_SPI1 //assuming all SPI temps sensors are on the same bus.

// define the properties for the slaves/devices/sensors
//#define SPI_TEMP_SENSOR_BUS_0 SOFT_SPI1 // assuming all SPI temps sensors can be on different buses.
#define SPI_TEMP_SENSOR_TYPE_0 MAX31865 // or MAX6675 or whatever
#define SPI_TEMP_SENSOR_MODE_0 xxx
#define SPI_TEMP_SENSOR_SPEED_0 yyy
#define SPI_TEMP_SENSOR_CS_0 pin cs_pin

// next slave
//#define SPI_TEMP_SENSOR_BUS_1 SOFT_SPI1 // assuming all SPI temps sensors can be on different buses.
#define SPI_TEMP_SENSOR_TYPE_1 MAX31865 // or MAX6675 or whatever
#define SPI_TEMP_SENSOR_MODE_1 xxx
#define SPI_TEMP_SENSOR_SPEED_1 yyy
#define SPI_TEMP_SENSOR_CS_1 pin cs_pin
```

**Comment by ghost** [comment]
> `MAX6675_IS_MAX31865` is logical crap.

Yeah I tried following MAX6675 stuff to try and make HEATER_0_USES_MAX31865 but gave up at some point. Not that good at coding.

**Pull request merged**
