### PR TITLE
Support for COREXZ kinematics

### PR DESCRIPTION
**Pull request by thinkyhead**
As requested in #1468

### CODE REVIEW

**Comment by Wackerbarth** [comment]
@thinkyhead --

I'll argue that you are perpetuating a BUG in the configuration system by expecting EVERY configuration to add something when you introduce this code which has absolutely nothing to do with the previously existing configurations.

**Comment by thinkyhead** [comment]
@Wackerbarth I am just doing things as they have been done so far, a situation that I did not create, and which I alone am not responsible for perpetuating. It has nothing to do with me personally expecting anything. And if you check the change log, you'll see that I've personally done much of the work of reducing the configurations down to just those values which should be altered, splitting up pins.h and language.h into separate files, and making several other adjustments to move the configuration system in a better general direction.

Until the configuration system changes, for the time-being, it makes the most sense to keep all the configuration files in the repository in sync. If there is some panacea to solve all this, I welcome it immediately.

Developers and users have been discussing how to manage and fix the configuration situation for as long as I've been hanging around here (about 8 months now) and so far there hasn't been any viable replacement produced. But it's not as easy as 1-2-3. A lot of preliminary work has needed to be done.

We also have to give some consideration to users migrating from previous versions of Marlin, to try to make the process less difficult and closer to what they may already be familiar with and what they find documented all over the place.

The current configuration system —with one basic configuration file and one advanced configuration file— has not actually been all that bad. And the idea has always been that you could just take the two files, change only the options you need, and then you're done. It is elegant in its simplicity, and that has some advantages that should not be discounted.

**Comment by Wackerbarth** [comment]
> On Jun 12, 2015, at 1:09 AM, Scott Lahteine notifications@github.com wrote:
> The current configuration system —with one basic configuration file and one advanced configuration file – has not actually been all that bad. And the idea has always been that you could just take the two files, change only the options you need, and then you're done. It is elegant in its simplicity, and that has some advantages that should not be discounted.
> 
> Well, the difference that I am suggesting (as an interim step to some future scheme that might be developed) is to change only one thing — namely frrop the concept that you can start from ANY pair of configuration files and edit them by uncommenting stuff that is currently inactive.

Instead, I suggest that all of the inactive stuff, and, perhaps more importantly the stuff that appears “active” but is really inactive because the “feature selector” is suppressing them, be removed.
For any particular configuration, this leaves just the part that is needed to compile that configuration.

If someone wants to add to the configuration, then they edit their configuration files by copying selected lines from the ONE master copy of all possible options. Note that this master copy is essentially the copy that you have in your configurator assistant.

So, the difference is that the user edits by adding feature lines rather than changing lines that are already in the file. (Or they use a configurator assistant that does the same for them).

I have two problems with the current procedure:
First, Having to change EVERY configuration just because you add a new feature is a PITA and leads to “errors” because some file was not “online” at the time that the change was added.
Second, having all of that “extra” material in a particular configuration file makes it very difficult to understand the code.

I consider the #defines in the Configuration files to fall into three categories.
1) #defines that indicate the presence of some optional feature.
2) Settings that customize the description of an option.  These might be values particular to a particular printer, eg. PID values, or values that create a specific case of a more general option. eg. That a particular model of LCD display has 4 rows of 20 characters.
3) Transitive implications - If you have feature B, then you must also have feature A as a prerequisite.
There are two ways to approach the enforcement of these implications at compile time.
In one approach, you have your “sanity checks” which produce an error should the configuration violate to the constraint. You have already segregated these away from the Configuration files.
The other approach is to automatically handle the implication by conditionally activating additional #defines in the Configuration file. It is this format that is cluttering the Configuration files and obfuscating to valid content. The user who does not have a delta print, doesn’t need a configuration file full of “options” that apply only to a delta printer. Similarly, a user who does not have a graphical display doesn’t need those options either.

My objective in reorganizing the content of the Configuration files is not to change the result, but to change the presentation so that it is both easier to understand and less difficult to maintain.

**Comment by thinkyhead** [comment]
> to change the presentation so that it is both easier to understand and less difficult to maintain

I am all for that, of course, but I am dubious that a significantly simpler system can be produced within the AVR environment. I would love to be proved wrong in this instance!

**Comment by Wackerbarth** [comment]
I guess that you have to define the constraints of AVR environment.
The major stumbling block that I see is the lack of proper handling of #include (hierarchal).
Of course, if you will allow me to demand that the user build within either the Arduino IDE or using a Makefile system that I specify, we have the "hooks" do do all kinds of things, including writing a description of the configuration in some custom language.

Therefore, I don't see "the AVR environment" being any more restrictive than any other environment.

But I don't think we need go that far to obtain some reasonable improvements.

First, I suggest dropping the idea of attempting to preserve the input to a configurator in EVERY copy of the Configurations. Have ONE master copy, which has every option. Within that structure, have only placeholders for specific measurements. Place the corresponding actual values in an individual folder describing a particular model.

Reduce each configuration to a single build specific file that reads like a presentation slide.

Back in the "master" file you can document all of the gory details about the features.
But, even there, I would organize them in a hierarchical structure.  Large, flat files are a poor way to present information.

**Comment by MagoKimbra** [comment]
Sorry if I'm intruding ...
But just you do not like the possibility of having a file `Configuration.h` where only the normal things that we will always find, type the baud, the board or the type of printer, and then load the file configuration_ suitable for that type of printer?
A bit like I did in my fork...
In this way the user knows that has a delta and opens the file configuration_delta and does not see the parameters of other models of printers and vice versa.
The same thing for the display and other options.
Again I ask pardon if I allowed myself ...

**Comment by Wackerbarth** [comment]
@MagoKimbra -- I don't know to whom you address your remarks. However, it seems that we both have the same goal, and an at least similar approach.

I get the feeling that some individuals don't care about anything that does not match THEIR configuration.

**Comment by MagoKimbra** [comment]
It was not reported to anybody. I just want to help as much as I can and I will not create other problems. It was just an idea.

**Comment by thinkyhead** [comment]
> the possibility of having a file `Configuration.h` where only the normal things that we will always find, type the baud, the board or the type of printer, and then load the `Configuration_MY_PRINTER.h`…

It is worth trying. But note that the baud rate is not the same for all printers, and in fact there are very few parameters which can be set universally. One point of the `Configuration.h` and `Configuration_adv.h` files is to provide semi-detailed documentation about each option, and to ensure that (apart from the delta/scara variants) all configurable options are stored in a consistent location for editing, so users can do their own customizations, such as using substitute parts in their Ultimaker 2s, without needing to add on more files – which the IDE wouldn't initially see without adding a new `#include` line to one or more of the current configuration files.

I have in the past advocated for settings to be split up into sections, and for optional features to each have their own configuration file (such as `Configuration_filament_change.h`, etc.) but everything I have tried only makes things more complex. I know the current Marlin configuration system is imperfect, so I encourage all developers to go ahead, try overhauling the configuration system. Until you've actually tried to make it better it's hard to see just how good we have it now.

**Comment by thinkyhead** [comment]
#2300

**Pull request closed without merging**
