### PR TITLE
Fix G2/G3 rounding error

### LINKED ISSUE #14745: [BUG] [bugfix-2.0.x] G02 mathematical bug in calculations
### Steps to Reproduce

1. Latest bugfix-2.0.x
2. Enable in configs: CNC and G2 G3 and SD card support (configs attached)
3. Build with Platform IO to Arduino 2560 r3 and RAMPS 1.4
4. Real example G-code that behavior explain the problem
```
; - 1 - BUG, Mistake! (Seen linear fast motions parallel to the X axis, not circles)
G00  Z0 
G00  X61.075 Y10 
G02  X64.325 Y10 R1.625 F500 
G02  X57.825 Y10 Z-0.125 R3.25 

; - 2 - GOOD (circles)
G00  Z0
G00  X21.075 Y10 
G02  X24.325 Y10 R1.625 F500 
G02  X17.825 Y10 Z-0.125 R3.25 

; - 3 - GOOD (circles)
G00  Z0 
G00  X61.075 Y10 
G02  X64.325 Y10 R1.62501 F500 
G02  X57.825 Y10 Z-0.125 R3.25001 
```

#### Additional Information

Analyzing the differences, I came to the conclusion that here the arithmetic error of calculations with roundings in the AVR platform leads to the fact that the semicircle radius is smaller than the calculated diameter of the semicircle along the coordinates.

I do not program in C - therefore I cannot implement a check myself that would correct the situation.

[All my configs.zip](https://github.com/MarlinFirmware/Marlin/files/3438300/All.my.configs.zip)

### PR DESCRIPTION
**Pull request by edwilliams16**
### Description

This fixes the problems from rounding error discussed in https://github.com/MarlinFirmware/Marlin/issues/14745
and an error introduced in the refactoring https://github.com/MarlinFirmware/Marlin/commit/56595a4c9cfad38a5fdd46d48e370edf70e0a079

### Related Issues
fixes #14745

### CODE REVIEW

**Comment by thinkyhead** [comment]
Good fix, thanks!

**Comment by Evg33** [comment]
DUE_USB                  FAILED  
```
Marlin\src\gcode\motion\G2_G3.cpp: In static member function 'static void GcodeSuite::G2_G3(bool)':
Marlin\src\gcode\motion\G2_G3.cpp:293:46: error: expected ',' or ';' before '/' token
           const xy_pos_t s = { -d2.y, d2.x } / len;      // Unit vector along perpendicular bisector
                                              ^
*** [.pio\build\DUE_USB\src\src\gcode\motion\G2_G3.cpp.o] Error 1

```

**Review by edwilliams16 — COMMENTED** [review]
`{ -d2.y, d2.x } / len`  didn't compile for me either
`{-d2.y, d2.x} * RECIPROCAL(len)` looked slower (1 divide, 2 multiplies instead of two divides)

so I used `{-d2.y/len, d2.x/len}`  
  The alternative of overloading `/` for the xy_pos_t type was more than I wanted to tackle  for this instance, as it would likely result in the same compiled code.

**Comment by thinkyhead** [comment]
Casting was needed. `xy_pos_t({ -d2.y, d2.x }) / len`. But we just moved the divide to the next line.

**Pull request merged**
