### PR TITLE
Update some G26 plausible values and add speed control

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Update temp limits to use configured max values
Update plausible nozzle size considering supervolcano
Add ability to define first layer speed, considering the multitude of build surfaces

### CODE REVIEW

**Comment by lrpirlet** [comment]
I am not sure why G26_XY_FEEDRATE gets a fixed value that overwrites the definition in G26.cpp?
The definition used to be
```C++
#ifndef G26_XY_FEEDRATE
  #define G26_XY_FEEDRATE (PLANNER_XY_FEEDRATE() / 3.0)
#endif
```
The modification seems to be tied with this merge…

```
$ git blame -L 1130,+5 Marlin/Configuration.h
d54741eda8 (InsanityAutomation 2019-03-08 04:13:44 -0500 1130)     #define MESH_TEST_BED_TEMP      60    // (°C) Default bed temperature for the G26 Mesh Validation Tool.
d54741eda8 (InsanityAutomation 2019-03-08 04:13:44 -0500 1131)     #define G26_XY_FEEDRATE         20    // (mm/s) Feedrate for XY Moves for the G26 Mesh Validation Tool.
5ce7f23afa (Scott Lahteine     2017-11-23 17:49:05 -0600 1132)   #endif
5ce7f23afa (Scott Lahteine     2017-11-23 17:49:05 -0600 1133)
cf94688925 (Scott Lahteine     2017-03-18 10:02:54 -0500 1134) #endif
```
Sorry, I just rebased and my configuration.h chocked on that very variable…. I wish I could have seen it before the merge.

**Comment by InsanityAutomation** [comment]
> I am not sure why G26_XY_FEEDRATE gets a fixed value that overwrites the definition in G26.cpp?

@lrpirlet 

Basically this allows you to override it from configuration.h - In my case it was way too fast for the polypropelene plates Tinymachines distributes so it needed to be slowed down. We did not want to touch the maximum axis speed, so this was the next best option. If the value was not defined in config, then we define it based on a calculation as always. If there is a desire, it could be made a new argument however I feel this should typically be slow regardless to allow users to really see whats going on.

**Comment by lrpirlet** [comment]
@InsanityAutomation. 

OK I do appreciate and may even like this feature… _**EXCEPT** for the fact that this is a **SILENTLY CHANGED BEHAVIOR**. The variable value changed from an 'adaptative' value based on the minimum X or Y FEDDRATE to a fixed value **WITHOUT WARNING** to the user_…

I suggest having this entry in the configuration.h commented by default and the associated comment outlining the fact that it overwrite a calculated value…

Thanks to take care.

**Comment by lrpirlet** [comment]
Of course, I think that any example configuration.h is not into consideration and better still, should have the best variable value...

**Pull request merged**
