### PR TITLE
fix Creality v4.3.1 pins

### PR DESCRIPTION
**Pull request by Chicos123**
### Description
fix Creality v4.3.1 pins

Pinout source from 
https://github.com/ginge/Ender6/blob/main/README.md
> https://docs.google.com/spreadsheets/d/1DYhh9fwLnvZzuNvMoBen9Dl68KN-4TWkbO94lJ4iwe4

tested by my own board

### Benefits
creality v4.3.1 board pins fix

### Related Issues

### CODE REVIEW

**Comment by thinkyhead** [comment]
Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases. Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

It may help to set your fork's default branch to `bugfix-2.0.x`.

See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.

**Comment by thinkyhead** [comment]
The linked spreadsheet actually shows the X and Y pins as what we already have, but does have different E0 pins than we currently have… Is the spreadsheet wrong?
```
name | 4.3.1
-----|-------------
PB8  | X_STEP_PIN
PB7  | X_DIR_PIN
PC2  | Y_STEP_PIN
PB9  | Y_DIR_PIN
PB3  | E0_STEP_PIN
PB4  | E0_DIR_PIN
```

**Comment by thinkyhead** [comment]
Reposted, with corrections, as #22704.

**Comment by Chicos123** [comment]
i gave firmware someone for test, just now
he has ENDER 3 v2 4.3.1 board(original board, not replaced)
that board are X,Y  pins switched

```
name | 4.3.1
-----|-------------
PC2  | X_STEP_PIN
PB9  | X_DIR_PIN
PB8  | Y_STEP_PIN
PB7  | Y_DIR_PIN
```

So maybe, there are some of 4.3.1 boards are slightly different variation?
```
name | 4.3.1_a
-----|-------------
PB8  | X_STEP_PIN
PB7  | X_DIR_PIN
PC2  | Y_STEP_PIN
PB9  | Y_DIR_PIN

name | 4.3.1_b
-----|-------------
PB8  | X_STEP_PIN
PB7  | X_DIR_PIN
PC2  | Y_STEP_PIN
PB9  | Y_DIR_PIN
PB3  | E0_STEP_PIN
PB4  | E0_DIR_PIN

name | 4.3.1_c
-----|-------------
PC2  | X_STEP_PIN
PB9  | X_DIR_PIN
PB8  | Y_STEP_PIN
PB7  | Y_DIR_PIN

```

**Comment by ellensp** [comment]
Ender 3 v2 comes with V4.2.2 or V4.2.7's  Never seen one with a V4.3.1... 

Though its creality, they like to change things without telling anyone!

Your "name | 4.3.1_c" is the a V4.2.2 pins  Marlin/src/pins/stm32f1/pins_CREALITY_V4.h  BOARD_CREALITY_V4 not a V4.3.1

It is possible the  4.3.1 X and Y are swapped. The Pins where derived from firmware.bin for a core X, Y, so there was no real X or Y

Its also quite possible that creality are sticking the wrong steppers in the wrong board plugs and just correcting for it in firmware.

**Pull request closed without merging**
