### PR TITLE
Fix SKR/GTR PeripheralPins.c

### PR DESCRIPTION
**Pull request by thinkyhead**
Suggested by @GhostlyCrowd in #17918

Redundant PWM pin definitions are breaking SKR / GTR timers and functionality. This PR removes the redundant definitions.

### CODE REVIEW

**Comment by GhostlyCrowd** [comment]
I know that this will fix the SKR Pro for sure, I'm not sure if it will cause a regression for the GTR since they use the same variant shared files. The person who added GTR support enabled these Pins (in error possibly?) or on purpose for the GTR, if the latter is the case then the solution would b to split the boards in the variants? Or fixing one will break the other if that's the case.

**Comment by randellhodges** [comment]
What's interesting is that, you don't even need the value there for PA_1 or PA_2 with a bltouch. The servo library is only using TIM5 to use a sort of software PWM for the server/bltouch.

You can completely comment out
```cpp
{PA_1,  TIM5,   STM_PIN_DATA_EXT(STM_MODE_AF_PP, GPIO_PULLUP, GPIO_AF2_TIM5, 2, 0)}, // TIM5_CH2    BL-TOUCH-SERVO
```
and the servo will work.

What I'm curious, because I don't have the knowledge of how this stuff works, is, does the hardware PWM that is defined here use the TIM5 timer? Could that somehow interfere with bltouch?

There is a note in the variant.h that says
```
//Do not use timer used by PWM pins when possible. See PinMap_PWM in PeripheralPins.c
```
but TIM5 is a timer used by PWM pins.

**Comment by thinkyhead** [comment]
> I know that this will fix the SKR Pro for sure, I'm not sure if it will cause a regression for the GTR since they use the same variant shared files.

Well that is easy enough to remedy. Let me take that approach first, and then maybe someone will be able to tell us what can be kept in the new file(s) and what can go.

**Comment by thinkyhead** [comment]
One thing I wasn't too sure about was the MOSI pin change that came along with the GTR submission from @bigtreetech. I also noticed that the chip model numbers are slightly different between SKR and GTR, so maybe there should be other small differences in the variants.

**Pull request merged**
