### PR TITLE
More custom user menu items

### PR DESCRIPTION
**Pull request by borland1**
Proposed PR adds option for user defined g-code script custom menus in Configuration Menu.

Reference:
 a. FR Issue #18096,
 b. Closed PR #18166  with bad Target

Requirements
For peripheral hardware that can be configured by G-code (e.g., a Wireless Serial WiFi/Bluetooth Radio), placing Custom Menus in the Main Menu seems awkward and can cause menu clutter.

Description
This proposed change provides for placing Custom user defined g-code menus in the Configuration Menu.

Benefits
Less menu clutter. Places less used menus further inside menu tree.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
It’d probably be beneficial to make this move optional via config setting.

**Comment by borland1** [comment]
It is by default disabled in `Configuration_adv.h`  Enabling is done by un-commenting the '#define' statement, which allows user-defined menus to be placed in Main Menu.  This PR provides ability for users to place these user-defined menus in either, or both, the Main and Configuration menus.

**Comment by sjasonsmith** [comment]
@borland1 are you still hoping to get this feature in?

@thinkyhead do you have opinions on whether this should move forward or not? If it is a desired feature, we can work with @borland1 to fix up issues.

If this has been ignored because the feature is unwanted, then we should go ahead an close it and the corresponding feature request.

**Comment by borland1** [comment]
> @borland1 are you still hoping to get this feature in?

Yes, still interested.

**Review by borland1 — COMMENTED** [review]
Looks good.

**Comment by ghost** [comment]
Just wanted to link https://github.com/MarlinFirmware/Marlin/issues/19072 since this solves that, too.

**Comment by thinkyhead** [comment]
Thank you for the contribution! I've cleaned it up and tweaked the code a bit, providing the "confirm first" option and adding code for the FTDI EVE to cover the basics that it does right now. At some point FTDI EVE may be extended to do both custom menus, and maybe confirmation as well.

**Pull request merged**
