### PR TITLE
add ZONESTAR_LCD on RAMPS and REARM warning

### PR DESCRIPTION
**Pull request by ellensp**
### Requirements

A RAMPS or derivative with a RAMPS AUX2 port layout
A ZONESTAR_LCD

### Description

Directly plugging the zonestar lcd into the RAMPS AUX2 port with the standard straight through cable will connect the RAMPS 5v to the LCD GND pins and the RAMPS GND to the LCD 5v pins. This is not at all desirable.
These pins need to be swapped over in hardware.

Added an Error condition into the pins_RAMPS.h to warn the user about 5v and GND needing swapped. 

### Benefits

Warns users about needing to swap the 5V and GND pins with this combination of hardware.

### CODE REVIEW

**Comment by ellensp** [comment]
This breaks the CI build of a ramps with a zonestar....  not sure best way to deal with this conflict of interest.

**Comment by ellensp** [comment]
that should do it.  ZONESTAR_LCD CI test move onto a non RAMPS board.

**Comment by ghost** [comment]
Hey,  
I checked if zonestar LCDs could work on my re-arm board, which also uses the ramps shield / pins file and ended up on this issue : https://github.com/MarlinFirmware/Marlin/issues/14552  
It seems like the Keypad is 5v logic and Re-arm boards are 3.3v (maybe 5v tolerant but others lpc176x might not be), issue above shows "proper" solutions for this, but as it requires hardware modifications, it might be worth to mention this specific case in the warnings ;)

**Comment by ellensp** [comment]
> It seems like the Keypad is 5v logic and Re-arm boards are 3.3v (maybe 5v tolerant but others lpc176x might not be), issue above shows "proper" solutions for this, but as it requires hardware modifications, it might be worth to mention this specific case in the warnings ;)

All ADC pins on the LPC176x are not 5v tolerant. So the zonestar lcd will not work without modification.
But Aux2 is 3.3v on REARM But is also missing most IO pins...

**Pull request merged**
