### PR TITLE
Added Malyan M180 pin board files and configurations

### PR DESCRIPTION
**Pull request by McNugget6750**
Added Malyan M180 mainboard pin and configuration files. You can ignore the Configuration.h. I know it's in the wrong pull request.

Description
Added Malyan M180 Dual Extruder Mainboard pins_MALYAN_M180.h, board.h and pins.h files to allow almost full compatibility with the M180 printer. I could not get the second extruder fan to work but I added the pin for it regardless. The original firmware can only control both at the same time and only 0% or 100% PWM. Marlin can control one fan with any duty cycle.

I also added an example Configuration.h that uses these new/changed files.

LCD is NOT working. The Malyan M180 seems to be using a proprietary LCD. Needs work!

Requirements
No requirements. Just install on Malyan M180 and feed with Octoprint or any other gcode sender like you would with a serial 3D printer.

Benefits
Added Malyan M180 config which was not supported by Marlin so far. Allows full take-over of proprietary printer to set new feeds and speeds, new temperatures and accelerations and everything else Marlin supports. Original firmware is extremely limited and not updated by Malyan anymore.

Configurations
None needed. Included in this pull-request.

Related Issues
None.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
Configurations should be targeted at the `import-2.0.x` branch in the [Marlin Configurations repo](https://github.com/MarlinFirmware/Configurations), not here.

**Comment by McNugget6750** [comment]
I can target a pull request to import-2.0.x for the configuration. Should I redo this one or can we just ignore the Configuration.h in this PR?

**Comment by thisiskeithb** [comment]
> Should I redo this one or can we just ignore the Configuration.h in this PR?

Just revert changes to `Configuration.h` in this PR and then you'll have to put in a separate one for the config in the Configurations repo.

**Comment by McNugget6750** [comment]
Done!

**Pull request merged**
