### PR TITLE
Display unknown XYZ on the LCD as "---"

### PR DESCRIPTION
**Pull request by thinkyhead**
- Also show 2 digits past decimal for Z on DOGM

### CODE REVIEW

**Comment by AnHardt** [comment]
@thinkyhead 
You have been faster. :-)

**Comment by AnHardt** [comment]
To M114 we still answer with:
X:0.00 Y:0.00 Z:0.00 E:0.00 Count X: 0.00 Y:0.00 Z:0.00
after a reset. Hosts are used to it. :-) But let's keep this in mind.

**Comment by thinkyhead** [comment]
Maybe hosts will be ok in the future with something like….

```
x:0.00 y:0.00 z:0.00 E:0.00 Count X: 0.00 Y:0.00 Z:0.00
```

Using lowercase to indicate XYZ are not set, or…

```
X:0.00 Y:0.00 @Z:0.00 E:0.00 Count X: 0.00 Y:0.00 Z:0.00
```

…using an `@` character to indicate the same idea (for Z). This might even be backward-compatible.

**Comment by thinkyhead** [comment]
One caveat occurs to me with this, and that is that you can still use the babystepping methods to move the axes when the axis positions are unknown. So the user experience would be to see "No coordinates set" but then the babystepping screen for each axis shows the raw stepper coordinate as you change it.

So I'm thinking, perhaps when axes are unknown it should also "hide" coordinates in the babystep options. Or, rather, always start them from 0 and show `+nnn.n` or `-nnn.n` – the relative movement.

Another alternative would be to indicate in some way that the coordinates shown are "faux." A 20x4 LCD display is arranged like so:

```
|† 19/0°   • 20/0°   |
|X  0  Y  0  Z  0    |
|ƒ100%  SD---% T00:00|
|12345678901234567890|
```

This feature makes it look like:

```
|† 19/0°   • 20/0°   |
|X---  Y---  Z---.-- |
|ƒ100%  SD---% T00:00|
|12345678901234567890|
```

But it could instead do something like:

```
|† 19/0°   • 20/0°   |
|X  0? Y  0? Z  0   ?|
|ƒ100%  SD---% T00:00|
|12345678901234567890|
```

Or perhaps:

```
|† 19/0°   • 20/0°   |
|X?  0 Y?  0 Z?  0   |
|ƒ100%  SD---% T00:00|
|12345678901234567890|
```

**Comment by fmalpartida** [comment]
This alternative looks good to me:
|† 19/0°   • 20/0°   |
|X---  Y---  Z---.-- |
|F100%  SD---% T00:00|
|12345678901234567890|

**Comment by AnHardt** [comment]
It's not only babystepping but also preparation/move Axis/... - both should work in relative mode then (and indicate this). Maybe with a additional text like "+/-".

Currently in the 'move Axis/...' i can't go towards my min-endstop but away from it. Here we limit the input to the ?_MIN_POS ?_MAX_POS. That normally means - with X_MIN_POS = 0 - you can't go to the left (towards the min-stop) of your start position.

**Comment by thinkyhead** [comment]
#2074

**Pull request closed without merging**
