### PR TITLE
Max endstopp

### PR DESCRIPTION
**Pull request by tonnico**
no user will home to 0 with a max endstopp
#1940
#1942

### CODE REVIEW

**Comment by fitch22** [comment]
This fix appears to have resolved my issue #1939.  Thank you!

**Comment by thinkyhead** [comment]
I've been looking at this endstop code, a little cross-eyed. Surely no one made homing code that sets position to 0 for a max endstop? But of course, someone did. I'm glad to see this is found!

**Comment by thinkyhead** [comment]
I'm not sure if this is really a bug! Hosts should not be sending `G28` with `X0`, `Y0` or `Z0` unless they intend to set the coordinate to 0 after homing. However they should be able to use `G28 X` to mean _Home X Only_. I have a feeling that people are just misusing `G28` and we need to improve documentation.

**Comment by tonnico** [comment]
I don't think that we should make any modification of the position with G28. There are other commands to do this.

Some other points come also from @nophead. His Mendel90 home not to 0, so this is not anymore only for max-endstops. It's for any endstop which doesn't home to 0. And there are a lot in the market.

Also, any other firmware i've found is ignoring the values behind X/Y/Z.

**Comment by thinkyhead** [comment]
@Wurstnase I agree. The [documentation for G28](http://reprap.org/wiki/G-code#G28:_Move_to_Origin_.28Home.29) on the RepRap wiki states that these are flags, and not to be used for setting the current position. So we should actually redo `G28` to ignore _any_ values and only treat XYZ as flags.

**Pull request merged**
