### PR TITLE
Assert Thermistor 66 (Dyze Design) Minimum Requirements

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Thermistor 66 (Dyze Design & Trianglelab T-D500) have several minimum requirements that are usually noted on the purchase page or [support docs](https://docs.dyzedesign.com/hotends.html#_500-%C2%B0c-thermistor), but can easily be missed.

I didn't assert the `HEATER_*_MAXTEMP` settings because users may need a lower max temp and it doesn't affect how the thermistor works.

### Requirements

Dyze Design or Trianglelab T-D500 500°C high temperature thermistor

_Note: The Trianglelab T-D500 is identical to the Dyze Design HT thermistor, but in cartridge form._

### Benefits

Users will be alerted to required firmware settings while compiling if their config doesn't meet the minimum requirements.

### Related Issues

- https://github.com/MarlinFirmware/Marlin/issues/23737

### CODE REVIEW

**Comment by EvilGremlin** [comment]
wasn't there macro to catch all TEMP_SENSOR_ numbers in one expression?
yep, it's ##, i.e. `TEMP_SENSOR_##N == 66`

**Comment by thisiskeithb** [comment]
> wasn't there macro to catch all TEMP_SENSOR_ numbers in one expression?

```prolog
In file included from Marlin/src/gcode/config/../../inc/MarlinConfig.h:49:0,
                 from Marlin/src/gcode/config/../gcode.h:330,
                 from Marlin/src/gcode/config/M92.cpp:23:
Marlin/src/gcode/config/../../inc/SanityCheck.h:2297:18: error: token "##" is not valid in preprocessor expressions
 #if (TEMP_SENSOR_##N == 66)
```

Using:

```cpp
#if (TEMP_SENSOR_##N == 66)
  #if MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED < 5
    #error "Thermistor 66 requires MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED to be ≥ 5."
  #endif

  #if MILLISECONDS_PREHEAT_TIME < 30000
    #error "Thermistor 66 requires MILLISECONDS_PREHEAT_TIME to be ≥ 30000."
  #endif
#endif
```

**Comment by EvilGremlin** [comment]
not that simple, here's better example of token pass
```
#define _IS_HW_SPI(P) (defined(TMC_SW_##P) && (TMC_SW_##P == SD_MOSI_PIN || TMC_SW_##P == SD_MISO_PIN || TMC_SW_##P == SD_SCK_PIN))
    #if DISABLED(DUE_SOFTWARE_SPI) && (_IS_HW_SPI(MOSI) || _IS_HW_SPI(MISO) || _IS_HW_SPI(SCK))
 ```
so should be somehing like 
```
#define TEMP_IS_66(N) (TEMP_SENSOR_##N == 66)
#if ANY (TEMP_IS_66(0), TEMP_IS_66(1), TEMP_IS_66(2), ...)
  #dostuff
 ```

**Comment by EvilGremlin** [comment]
still one-way and no true loops, but way less clutter

**Comment by EvilGremlin** [comment]
and you can use `DO` macro to remove even more clutter like here: https://github.com/MarlinFirmware/Marlin/blob/945d5dbe1357e8042e19bcb79e6db5414a939141/Marlin/src/HAL/LPC1768/inc/SanityCheck.h#L92 https://github.com/MarlinFirmware/Marlin/blob/945d5dbe1357e8042e19bcb79e6db5414a939141/Marlin/src/HAL/LPC1768/inc/SanityCheck.h#L119

**Pull request merged**
