### PR TITLE
M114 with axis details (#12192)

### PR DESCRIPTION
**Pull request by TheSFReader**
Added a new option to M114 (M) which returns (parts) of the Modal state : XYZ and E absolute/Relative mode, and unit (inch/mm temp) if enabled.

Will update the other configuration files and doc after first review from @thinkyhead

### CODE REVIEW

**Comment by thinkyhead** [comment]
What's the justification for this feature and adding a new irrevocable Capability string in the `M115` output applying to all setups?

**Comment by TheSFReader** [comment]
It was in answer to #12192 . But if unwelcome, it can as well be out. As for the capability, I thought it would allow a host to check if it could ask for these details to make sure it's not out of synch after potential external/manual intervention. 

BTW, is there a way to check if some "Issues"/Feature Requests" are more worthy to work on rather than others ? Should I just look for ones tagged "Feature Request" ?

**Comment by thinkyhead** [comment]
The host is in control of whether the machine is in relative or absolute mode, with the historical understanding that the machine may be in either state at boot up. The same goes for inches versus millimeters. All slicers customarily include a G-code precursor to set absolute mode, millimeters, and to reset the current E position to zero.

At this time the priority is always on bug fixes, implementing missing features for 32-bit boards which have already been implemented for AVR, and on writing documentation, which is falling far behind. New features are lowest of the low priority.

**Comment by TheSFReader** [comment]
Thanks

**Pull request closed without merging**
