### PR TITLE
Fix show elapsed time at end of print, instead of freezing at 99%

### PR DESCRIPTION
**Pull request by mikemerryguy**
Fix issue that Blink leaves a finished print showing 99% vs time completed. It will now stop displaying percentage at 98% and stay on elapsed time, same as when you start a print it stays on elapsed time until percentage is at 1% or above.

### CODE REVIEW

**Comment by ellensp** [comment]
Non valid code 

```CPP
Marlin/src/lcd/dogm/status_screen_DOGM.cpp:490:29: error: expected primary-expression before '<=' token
  490 |       if (progress != 0 and <= 98) {
      |                             ^~

```

**Comment by mikemerryguy** [comment]
ah, got hasty there, I fixed it, my appologies!!

**Comment by thinkyhead** [comment]
This change just makes the progress bar get stuck at 98% instead of displaying 100% at the end of the print.

Before:
image

After:
image

The point of not overwriting the % display when it goes to 0 is to leave the last-displayed value up. If the last-displayed value was never 100% then it will never display 100%. The correct solution is probably to force a screen update at the end of the print before the file is closed and the progress (file position) is reset to 0.

**Comment by mikemerryguy** [comment]
> This change just makes the progress bar get stuck at 98% instead of displaying 100% at the end of the print.

Yes, actually I have realized this, sometimes it just freezes at the 98 now, been looking for a solution still the issue is that when print is done it sometimes just gets stuck at percentage VS leaving the time elapsed on screen, the status bar will show time elapsed but after some time it will reset to "printer name Ready" and if you don't see it in time, the status is still stuck at (usually) 99% and no clue how long the print took!!

**Comment by thinkyhead** [comment]
Maybe you'd like to implement this for us…?

image

**Comment by thinkyhead** [comment]
> after some time it will reset to "printer name Ready"

This likely depends on `STATUS_MESSAGE_TIMEOUT_SEC`. The status message can have an alert level associated with it so that it won't be overwritten by a message with a lower alert level (which may not always prevent `ui.reset`). If a message should not expire then it can be set with `set_status_no_expire` (or `set_status(..., true)`) instead of the usual method.

**Comment by thinkyhead** [comment]
> after some time it will reset to "printer name Ready"

I went ahead and made `M31` always set the status as non-expiring.

**Pull request merged**
