### PR TITLE
[2.0.x] Constrain setting hotend temperature to maxtemp

### PR DESCRIPTION
**Pull request by rmoravcik**
The current code is able to accept request to set a higher hotend temperature then maxtemp limit set in Configuration.h. 

Set of higher bed temperature then BED_MAXTEMP is already limited in Temperature::setTargetBed().

### CODE REVIEW

**Comment by Ludy87** [comment]
Did you test it?

Heatbed heats up to Nirvana, the same with the Hotend. This fix does not work.

**Comment by rmoravcik** [comment]
I tested it on my spare Arduino Mega with RepRapDiscount FULL GRAPHIC Smart Controller connected to it.
I tried to set higher temperature than HEATER_0_MAXTEMP (set to value 275 in Configuration.h) and ThermalManager started to heating to 275C instead of 300C (M104 S300).

**Comment by rmoravcik** [comment]
> Did you test it?
> 
> Heatbed heats up to Nirvana, the same with the Hotend. This fix does not work.

What is your values of HEATER_0_MAXTEMP and BED_MAXTEMP in Configuration.h?

**Comment by Ludy87** [comment]
My settings:

```
#define HEATER_0_MAXTEMP 200
#define BED_MAXTEMP 50
```

`M303 E-1 S80` it heating to >80°C
`M303 E0 S230` it heating to >230°C

**Comment by rmoravcik** [comment]
If you want to try it with M303, you need also apply https://github.com/MarlinFirmware/Marlin/pull/12691

**Comment by Ludy87** [comment]
My reference was to PID-AutoTune, sorry

**Comment by AnHardt** [comment]
@Ludy87 
What temperature sensors do you use?

**Comment by Ludy87** [comment]
5 : 100K thermistor - ATC Semitec 104GT-2/104NT-4-R025H42G (Used in ParCan & J-Head) (4.7k pullup)

**Pull request merged**
