### PR TITLE
Added support for Chitu V9 boards.

### PR DESCRIPTION
**Pull request by VTXtruder**
### Description

The submitted changes add support for Chitu V9 boards used in the Tronxy X5SA-500-2E, and possibly others.
The V9 board is similar to the V6 board with just a few pin changes. The changes are as follows.

- Changed Z_MIN_PIN to PA14
- Added Z2_MIN_PIN as pin PA13
- Added Z_MIN_PROBE_PIN as PG9

### Requirements

This PR requires a Chitu V9 board.

### Benefits

Adds support for the Chitu V9 board.

### Configurations

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6843895/Configuration.zip)

### Related Issues

No.

### CODE REVIEW

**Comment by ellensp** [comment]
perhaps its time to have a BOARD_CHITU3D_common.h and just list the changed pins in the specific versions?

**Comment by ellensp** [comment]
perhaps its time to have a pins_CHITU3D_common.h and just list the changed pins in the specific versions?
Or just include lowest version and make required pin changes

**Comment by thinkyhead** [comment]
An automated action should have rejected this PR because it is targeted to 2.0.x (and also based on a very old 2.0.x), but that action is no longer functioning. So I went ahead and rebased this on `bugfix-2.0.x` and force-pushed the result to your `2.0.x` branch.

P.S., Always make a new branch before making changes and submitting them as a PR, otherwise you will be introducing conflicts into your branches which are supposed to remain pristine clones.

**Comment by thinkyhead** [comment]
> …perhaps [it's] time to have…

Done.

**Comment by leseaw** [comment]
Hello,

the config files for the Tronxy are not correct.
Port1 1
Port_2 3
Baud rate should be 250000
And pins are missing for Endstop in the pins_CHITU3D_V9.h
#ifndef Z_MIN_PROBE_PIN 
  #define Z_MIN_PROBE_PIN PG9
#endif

can anyone else confirm this or am I wrong?

**Comment by ellensp** [comment]
The following pins where lost during the commit shuffle

#define Z2 STOP_PIN                         PA13
#define Z_MIN_PROBE_PIN                    PG9

**Comment by Eliminateur** [comment]
The configuration change broke the v5 board support:
on v5 boards, Z_STOP_PIN  must be PA14
the latest commit changed the v5 to PG9 leading to non-functioning Z endstop

**Pull request merged**
