### PR TITLE
M600 Strange Behavior since last release and 1.1.5

### PR DESCRIPTION
**Pull request by ghost**
#### M600 have a serious issue , not on the old release

> When go on pause , Retract and recover immediatly , and loading two times the loading setting

Try it yourself , set a park pause and zlift , apply M600 and look !
[Code overloaded of SERIAL ECHO for testing and see E pos never update ](https://github.com/MarlinFirmware/Marlin/issues/7869)
Why ? : 
1. There is confusion in the way of moving . Old releases used RUNPLAN that will moves only axes asked , and now are introduced 'do_block_moves' that uses **all axes** in a movement, make INTERPOLATION and need you specify correctly all destination of all axes  , and verify all current position of all axes 
2. Current E axis never updated , you set destination=10 and after move , current E always=0 .I don't know if extrusion is just manually setted , or if it's a bug of marlin that never update E position automatically

#### Three ways of fixing

1. Use the old code , that only use RUNPLAN and it works , 'not made for the future ' but works now
or
2. Update planner move functions to UPDATE E CURRENT POSITION AFTER ALL MOVEMENT
or
3. Add code in M600 to specify the current E position before each do_block_moves

My wish is to update planner to have the E current position always updated , but , i need to know why E current pos is never updated before make a fix

#### For devs
@thinkyhead 
@Bob-the-Kuhn 
@Roxy-3D 
@Tannoo 

Why E current pos never updated ? It's a bug , or just because not interesting to process this , and the way to do it is to increment or decrement as we want without Position memorised ?
I think this changes are ' a batch ' and not a human writting , because not TESTED , and i'm really afraid this ' batch ' may be , have  breaks many other processing in marlin ...

### CODE REVIEW

**Comment by tcm0116** [comment]
The changes you're referring to were done in #7518. I submitted that PR because the previous implementation didn't work with Delta machines and could potentially drive the nozzle into the bed because it wasn't using movement commands that would properly segment the movements. I also have a Cartesian machine, so I'll try and find some time to put 1.1.6 on it and see if I can replicate your issue.

**Comment by ghost** [comment]
It's ok 
The best choice is to rewrite Doblockmovement  and only make a move with the arguments in the calling only

Why ?
- Because Current E position never actualised by the planner , only hand actualised and if a destination is applied and a doblockmove before , the second doblockmoves will return to the old E position
- And the second reason is ,  Imagine a cartesion , with the pause park on the right outside of the bed, and with a moving bed , if i want to go on pause , i don't need to move the bed , but only the X axis , with your do block move if i don't give an Y position , it will move all axes and my bed will moves
try to write your doblockmoves , with this option ' If not argument , no axis movement ' , if Y_Park_Pause not defined , than that is not equal to 0 , but only equal to ' NO MOVE ON Y AXIS'

If doblockmove is rewritten to make the movement only with the argument in the calling , the issue disappear 👍

**Comment by ghost** [comment]
Be quick , because if some users download the 1.1.6 , the pause not working
Make a compilation switch ' if delta ' and add your code , and leave the old code
It's a shame , a new user have this big bug on A STABLE RELEASE

**Comment by thinkyhead** [comment]
> bug on A STABLE RELEASE

Stable means unchanging, not bug-free.

**Pull request closed without merging**
