### PR TITLE
Update pins_GT2560_REV_A_PLUS.h

### PR DESCRIPTION
**Pull request by Sblop**
Assisting comment

### CODE REVIEW

**Comment by fiveangle** [comment]
Why just a comment ?  If pin 32 should be used, why not just put the logic in to automatically switch to the correct pin if that's what's supposed to happen ?

**Comment by Phr3d13** [comment]
`#if ENABLED(BLTOUCH)
#define SERVO0_PIN  33
#elif
#define SERVO0_PIN  11
#endif`

**Comment by Phr3d13** [comment]
code tags don't work correctly

#if ENABLED(BLTOUCH)
#define SERVO0_PIN  33
#elif
#define SERVO0_PIN  11
#endif

**Comment by Phr3d13** [comment]
Just tested compiles for with and without bltouch enabled, both compile.

**Comment by fiveangle** [comment]
@Phr3d13 - if you want to submit PR with the fix feel as both of these PRs don't really fix anything.

**Comment by Sblop** [comment]
@Phr3d13 please note you wrote pin 33 instead of 32 in your code snippet. Correct pin number is 32.

**Comment by fiveangle** [comment]
@Sblop - can you please close #7737

**Pull request closed without merging**
