### PR TITLE
Universal X axis twist compensation

### PR DESCRIPTION
**Pull request by tombrazier**
### Description

Concept demonstrator for comment...

X axis twist compensation is coupled to AUTO_BED_LEVELING_BILINEAR but it needn't be. This change moves the adjustment into `probe.probe_at_point()`. Also the files are moved out of the abl subdirectory.

Notes:
- This was a small and simple change. It could do with more testing.
- Note also the change to config which will need to be applied to MarlinConfigurations.
- XATC now also applies to Z Probe Wizard, G33 - Delta Auto Calibration, The Tramming Wizard and G35 - Tramming Assistant, DWIN menu options that measure bed height, G34 - Z-Stepper automatic alignment, G30 - Single Z-Probe and M48 Probe Accuracy Test. Does any of these need an option to switch XATC off? Or maybe a global gcode to enable/disable?
- I think `xatc.compensation(npos + offset_xy)` in `probe.probe_at_point()` is right, i.e. that the compensation applies to the nozzle position, not the probe position. If I have that wrong then the `+ offset_xy` is wrong. @Giuseppe499 are you able to comment?

### Requirements

An X axis with parallel bars and a bed probe.

### Benefits

Several people are asking for XATC with UBL. This makes it available everywhere.

### Configurations

#define X_AXIS_TWIST_COMPENSATION

### Related Issues

#23238

### CODE REVIEW

**Comment by tombrazier** [comment]
Also added a default value for Z offsets. So config can be in Configuration_adv.h or EEPROM.

**Comment by Giuseppe499** [comment]
Hi @tombrazier ,

I think that this is a nice approach to extend XATC to other features such as UBL.

> * I think `xatc.compensation(npos + offset_xy)` in `probe.probe_at_point()` is right, i.e. that the compensation applies to the nozzle position, not the probe position. If I have that wrong, then the `+ offset_xy` is wrong. @Giuseppe499 are you able to comment?

`xatc.compensation(npos + offset_xy)` should be correct.

> * XATC now also applies to Z Probe Wizard, G33 - Delta Auto Calibration, The Tramming Wizard and G35 - Tramming Assistant, DWIN menu options that measure bed height, G34 - Z-Stepper automatic alignment, G30 - Single Z-Probe and M48 Probe Accuracy Test. Does any of these need an option to switch XATC off? Or maybe a global gcode to enable/disable?

I don't see a reason for a user to use XATC with a delta printer, so I think that "G33 - Delta Auto Calibration" should be ok. To stay safe, you could add a warning if a user tries to compile marlin for a delta printer with XATC enabled. 

For the Z Probe Wizard, I think that this approach is even better than leaving XATC as it is. This should make XATC compatible with the z-offset wizard, so if a user wants to just update the z-offset he can use the z-offset wizard and if he wants to update the XATC values compensation along with the z-offset he can run the x-twist wizard.

For "Tramming Wizard and G35 - Tramming Assistant", "G30 - Single Z-Probe" and "M48 Probe Accuracy Test" I don't think that these should have a problem with this PR, but I didn't test them.

"G34 - Z-Stepper automatic alignment" could have some issue with this PR because the twist of the X-axis can change when the Z-Stepper are moved relatively to each other.  Unfortunately, I can't test this feature on my printer.

In regard to "DWIN menu options that measure bed height", I'm not familiar with this, so I can't help.

In general, I think that an option to switch XATC off globally should be added. I also think that a gcode support for XATC would be usefull and if we have it we could add an option for switching XATC on and off. We should check what the maintainers of marlin think about adding gcode for XATC.

**Comment by tombrazier** [comment]
@Giuseppe499 Deltas: doh! Good point.

I see @thinkyhead has added `M423` to your #23745 PR. So I guess this would be a good place to add an enable/disable feature.

The PR will cause merge conflicts with #23745 so it probably makes sense to get that merged first.

PS I really like your wizard. I did not even know I had X axis twist (or realise it was a problem) until yesterday when I wondered what the `x_twist.*` files did. Having enabled it, I found it intuitive and easy to use. And it turns out I have a delta of about 0.1mm across the width of my i3 clone X axis.

**Comment by tombrazier** [comment]
@thinkyhead ma cupla, `XATX_Z_OFFSETS` has a typo - should be `XATC_Z_OFFSETS` (C rather than X).

And question: will the default value be applied if EEPROM_SETTINGS is not enabled?

**Comment by thinkyhead** [comment]
> will the default value be applied…?

When `EEPROM_SETTINGS` are not enabled, settings are still initialized by `settings.reset()`.

**Comment by thinkyhead** [comment]
> The PR will cause merge conflicts…

True, but I think it will be easier to merge this PR first, then clear up conflicts in the other PR.

**Pull request merged**
