### PR TITLE
template struct simplification for serial

### PR DESCRIPTION
**Pull request by dgrat**
@thinkyhead @ejtagle 
There is no need for two MarlinSerialCfg* definitions.

### CODE REVIEW

**Comment by ejtagle** [comment]
@dgrat : You are absolutely right. Nice touch there!

**Comment by ejtagle** [comment]
But, i assume if someone needs a very differently configured UART, in that case a "new" MarlinSerialCfg struct will be needed. There is an ongoing attempt to port MMUv2 to Marlin, and that requires a UART interface with wildly different configurations (no XON/XOFF, no stats, probably smaller TX/RX buffers...)

**Comment by dgrat** [comment]
@ejtagle  
I agree

**Comment by ejtagle** [comment]
@dgrat : Don´t ask why an explicit instantiation of serial classes is required. I agree it shouldn´t. But if i don't do them, link fails. 
I assume this has something to do with a bug in LTO (Link time optimizations).... But on both DUE and AVR the explicit instantiation is needed...

**Pull request merged**
