### PR TITLE
STM32 non-generic PWM_PIN and USEABLE_HARDWARE_PWM

### PR DESCRIPTION
**Pull request by thinkyhead**
@ktand reports that STM32GENERIC can do PWM on any pin because it implements PWM in software. But STM32 core can only do PWM on hardware-supported pins.

### CODE REVIEW

**Comment by hasenbanck** [comment]
Wait, why does this PR then implements the exact opposite?

Marlin/src/HAL/HAL_STM32/fastio_STM32.h now sets ```#define PWM_PIN(p) true```  which would be fine, if PWM was software based in the official STM32 core, but there it's hardware based.

The STM32 HAL does not target STM32GENERIC.

**Comment by thinkyhead** [comment]
I thought that the STM32 HAL was STM32GENERIC and the others were not. In any case, it was simply left as it was. So, if I got it wrong, please submit a new PR correcting my error.

**Comment by thinkyhead** [comment]
…and please add comments to the top of all the `HAL.h` files in each of the STM32 HALs explaining what cores they are intended to be compiled with.

**Comment by hasenbanck** [comment]
I think the Readme files already contained such an information, but the
core names can get a little confusing.

Tomorrow I will open a PR to fix the issue and add some clarifications.

**Comment by thinkyhead** [comment]
Ah, right. I missed that there are README files for each. n/m

**Pull request merged**
