### PR TITLE
Fan Tail Speed Initialization Fix

### PR DESCRIPTION
**Pull request by descipher**
### Description

On startup fans may not be initialized to an off state until fans_need_update is true.
By moving the tail_fan_speed array  and bool state flag out of the check_axes_activity call we save 4 bytes of ram and eliminate extra processing. With the bool variable outside of the call we are able to one time init the fans_need_update bool to properly set the update of fans on boot.

### Requirements

None

### Benefits

Corrects fan boot state to off.

### Configurations

Any

### Related Issues

#24055

### CODE REVIEW

**Comment by thinkyhead** [comment]
- `fans_need_update` is always set to `false` at the start of `check_axes_activity` so it can just be a local variable.
- Did you intend to initialize `tail_fan_speed` to all zeros? It was previously initialized to all 128 to trigger `fans_need_update` on the first iteration.

**Comment by thinkyhead** [comment]
As to the original issue, my guess is that on your setup the `thermalManager.scaledFanSpeed` method is returning 128, so `fans_need_update` is not being set until fans are changed later. Initializing the `tail_fan_speed` array to something unlikely (e.g., 13) should solve that issue.

**Comment by descipher** [comment]
Correct me if I'm wrong but the issue here is that setting thermalManager.scaledFanSpeed will not result in a fan_speed setting since there is no active temps to manage there. So the original commit here is required and the value should be 0 then the fans_need_update flag will trigger the update. This action does not depend on the thermal manager return value. The fans_need_update flag triggers the sync_fan_speeds(tail_fan_speed) call and invokes the FAN_SET macros at the latter part of  check_axes_activity().   

Also the array needs to be initialized to zero and not 128 etc. This was validated by testing.
In the case of PWM this is required to set it to the off state.

See:

```
  void Planner::sync_fan_speeds(uint8_t (&fan_speed)[FAN_COUNT]) {

    #if FAN_MIN_PWM != 0 || FAN_MAX_PWM != 255
      #define CALC_FAN_SPEED(f) (fan_speed[f] ? map(fan_speed[f], 1, 255, FAN_MIN_PWM, FAN_MAX_PWM) : FAN_OFF_PWM)
    #else
      #define CALC_FAN_SPEED(f) (fan_speed[f] ?: FAN_OFF_PWM) <- when off is not actually 0
    #endif
```
The last changes do not work.

**Comment by descipher** [comment]
I think I missed something when compiling, the updated code does work, looking closer to see what went off the rails.

**Comment by descipher** [comment]
Just my error, this is good to go.

**Pull request merged**
