### PR TITLE
Provide LONG_FILENAME_LENGTH for headers

### PR DESCRIPTION
**Pull request by Rotule666**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Added defines to `Conditionals_LCD.h` to be able to build with the following configurations
```cpp
#define CR10_STOCKDISPLAY
//SDSUPPORT
```
Tested with Rearm with RAMPS 1.6 on Creality Ender 3

### Benefits

Be able to build without changing Conditionals_LCD.h

### Related Issues

Fixes Issue #15502 [BUG] Can't compile with SDSUPPORT disabled - LONG_FILENAME_LENGTH was not declared in this scope
https://github.com/MarlinFirmware/Marlin/issues/15502

### CODE REVIEW

**Comment by thinkyhead** [comment]
The modified code should cover all cases. Thanks for the patch!

**Comment by thisiskeithb** [comment]
Thank you!

**Comment by sl1pkn07** [comment]
little question. if you disable the SD, and the ender LCD comes without bundle it, how you update and store the eeprom and the firmware?, or the SDSUPPORT is only for able read the Gcodes?

and little oftopic, the ramps 1.6 working with 24v? or you have make a mod? (ender 3 is a 24v machine) 

greetings

**Comment by Rotule666** [comment]
> little question. if you disable the SD, and the ender LCD comes without bundle it, how you update and store the eeprom and the firmware?, or the SDSUPPORT is only for able read the Gcodes?
> 
> and little oftopic, the ramps 1.6 working with 24v? or you have make a mod? (ender 3 is a 24v machine)
> 
> greetings

Hello,

Yes Ramps 1.6 works with 24V, the only real flaw that I have found is that the 5V regulated is very weak, so I had to add a 5V Regulator for my 3Dtouch.

I'm using this board : https://www.amazon.ca/gp/product/B07TJGWCY2/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

Sorry for the off topicness.

I'll leave someone else answer about the SD, I'm using it disabled because I'm using rearm.

**Comment by sl1pkn07** [comment]
i have the same board (original by panucatt, not clone, the 5v LDO with it works with BLtouch, LCD and a Thoshiba Flashair without problem) in my ender 3. but i have enabled that option, for this i ask

**Pull request merged**
