### PR TITLE
make the dual z-endstop optional

### PR DESCRIPTION
**Pull request by tonnico**
it's disabled by default

### CODE REVIEW

**Comment by thinkyhead** [comment]
Failing the Travis check!

**Comment by tonnico** [comment]
@thinkyhead Got a small heart attack after reading my mails this morning :) Could not believe that this PR makes a problem, because I merged it before Travis check. But afaik Travis don't check dual z endstops. Anything is ok, you saw it also :+1:

**Comment by thinkyhead** [comment]
Travis will also fail if a branch is deleted before it finishes testing, so perhaps this is why it fails.

**Comment by tonnico** [comment]
Good to know.

**Pull request merged**
