### PR TITLE
Touch fixes

### LINKED ISSUE #26454: Touch screen does not work after PR#26445
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Touch screen support is broken in https://github.com/MarlinFirmware/Marlin/pull/26445
Reverting this PR fixes the problem.

### Bug Timeline

https://github.com/MarlinFirmware/Marlin/pull/26445

### Expected behavior

UI respond to touching elements
Touch screen calibration can be completed successfully.

### Actual behavior

UI does not respond to touching elements
Touch screen calibration fails every time

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

bugfix-2.1.x (Nov 22 2023 17:57:56)

### Printer model

_No response_

### Electronics

MKS Robin Nano V3.1

### LCD/Controller

MKS TS35 V2.0

### Other add-ons

_No response_

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

_No response_

### LINKED ISSUE #26485: [BUG] Touch screen cannot be calibrated
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

The touchscreen calibration remains in an infinite loop. It continuously repeats the calibration cycle without the possibility of termination.
If I disable calibration and enable 
  #define TOUCH_CALIBRATION_X 17880
  #define TOUCH_CALIBRATION_Y -12234
  #define TOUCH_OFFSET_X -45
  #define TOUCH_OFFSET_Y 349
touch screen does not respond to touch.

### Bug Timeline

new bug

### Expected behavior

_No response_

### Actual behavior

_No response_

### Steps to Reproduce

_No response_

### Version of Marlin Firmware

Marlin 2.1 Bugfix Branch DISTRIBUTION_DATE "2023-11-30"

### Printer model

Two Trees BlueR V2

### Electronics

MKS robin nano V1.2

### LCD/Controller

MKS_ROBIN_TFT35

### Other add-ons

_No response_

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Repetier Host

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

[Marlin_config.zip](https://github.com/MarlinFirmware/Marlin/files/13516657/Marlin_config.zip)

### PR DESCRIPTION
**Pull request by thinkyhead**
Followup to #26445 — as reported in #26454

Fix some oopsies that broke touch. Unclear which changes are breaking. We'll keep tweaking this until it's solved.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
I’ll test this on a BTT SPI TFT35 & BX TFT70 tomorrow.

**Comment by thisiskeithb** [comment]
Touch is still broken with this PR and calibration always fails.

**Comment by thinkyhead** [comment]
> Touch is still broken with this PR and calibration always fails.

OK. My testing was done in the Simulator, so I appreciate your testing on real hardware. I have the MKS Robin E3D and MKS TFT35 out and will do some of my own testing.

The idea here is just to selectively and somewhat blindly revert small parts of the recent touch update until it works, and then do any needed tweaks after that. You'll probably find the line that broke things before me, as I'll be wrestling with these MKS units for a while before I can start testing.

**Comment by thisiskeithb** [comment]
> MKS TFT35

I assume you meant TS35, their SPI TFT?

You’ll need to cherry pick / apply changes on top of #26052 since SPI TFTs are still broken for F1 and F4 in current bugfix (not that they’re much better with that PR).

> You'll probably find the line that broke things before me, as I'll be wrestling with these MKS units for a while before I can start testing.

I don’t even know where to begin with your changes / know which line caused the issue, but fully reverting #26445 fixes it.

**Comment by jmz52** [comment]
Major problems I've found so far
`bool(point)` check does not work - {0,0} point is `true` when the original check was `x != 0 && y != 0`
```
DEBUG_ECHOLNPGM("  point : ", point.x, ", ", point.y, " : ", bool(point) ? "true" : "false");
  point : 0, 0 : true
```

`touch_calibration_t` does not work as intended
```
  void reset() {
    set(xy_long_t({ TOUCH_CALIBRATION_X, TOUCH_CALIBRATION_Y }),
        xy_int_t({ TOUCH_OFFSET_X, TOUCH_OFFSET_Y }),
        TOUCH_ORIENTATION);
```
results in
```
DEBUG_ECHOLNPGM("  TOUCH_CALIBRATION_X : ", _TOUCH_CALIBRATION_X);
DEBUG_ECHOLNPGM("  TOUCH_CALIBRATION_Y : ", _TOUCH_CALIBRATION_Y);
DEBUG_ECHOLNPGM("  TOUCH_OFFSET_X : ", _TOUCH_OFFSET_X);
DEBUG_ECHOLNPGM("  TOUCH_OFFSET_Y : ", _TOUCH_OFFSET_Y);
DEBUG_ECHOLNPGM("  TOUCH_ORIENTATION : ", _TOUCH_ORIENTATION);

  TOUCH_CALIBRATION_X : 1
  TOUCH_CALIBRATION_Y : 0
  TOUCH_OFFSET_X : 514
  TOUCH_OFFSET_Y : -24
  TOUCH_ORIENTATION : 1
```
where `TOUCH_CALIBRATION_X` and `TOUCH_CALIBRATION_Y` are not what they should be (-17253 and 11579)

There is also flawed logic in touch screen calibration but I can't debug it in current state.

**Comment by thinkyhead** [comment]
This now reverts most changes but keeps the innocuous (?) ones. Touch should function properly.

Touch calibration was broken in the Simulator before I made the previous touch fixes, and this PR currently reverts that fix. So, if this PR currently fixes touch issues on real screens, I'll add one more commit to fix the Simulator touch calibration issue. And if that doesn't break anything on real touch screens then this will be good to go.

Thanks for the assist. This should be good to go later today.

**Comment by jmz52** [comment]
Tested on MKS Robin Nano v3.1. Touch and calibration work fine.

**Comment by thisiskeithb** [comment]
This seems fixed now.

Tested:
- Biqu BX with `BIQU_BX_TFT70` (LTDC)
- SKR V3 with `BTT_TFT35_SPI_V1` & `MKS_TS35_V2_0` (SPI)

**Review by thisiskeithb — APPROVED** [review]

**Pull request merged**
