### PR TITLE
Small / Large Boot Screen option for TFT_COLOR_UI follow-up

### PR DESCRIPTION
**Pull request by thisiskeithb**
### Description

Quick follow-up so `TFT_CLASSIC_UI` (`TFT_SCALED_DOGLCD`) is also included in `BOOT_MARLIN_LOGO_SMALL` check.

### Benefits

The `BOOT_MARLIN_LOGO_SMALL` setting will now be honored when `TFT_CLASSIC_UI` is enabled. Simply comment it out to use the the old/large bootscreen.

Just to confirm that everything works as expected, I tested it with the following:

- A real `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`
- `TFT_CLASSIC_UI` (`TFT_SCALED_DOGLCD`)
- `TFT_COLOR_UI`

### Related Issues

https://github.com/MarlinFirmware/Marlin/pull/20578#issuecomment-751728286

### CODE REVIEW

**Comment by tpruvot** [comment]
no no, it was working, its the reverse :p no way to put/keep the big one... seems only a problem with the colored bitmaps... much bigger

**Comment by thisiskeithb** [comment]
> no no, it was working, its the reverse :p no way to put/keep the big one...

Using the updated `ANY()` check from this PR, can't you just comment out `BOOT_MARLIN_LOGO_SMALL`?

https://github.com/MarlinFirmware/Marlin/blob/a8c361c93bdda3110d147c5f47f96f57298c0a13/Marlin/src/lcd/dogm/dogm_Bootscreen.h#L46-L52

**Comment by tpruvot** [comment]
just #if ENABLED(TFT_COLOR_UI) is required so... maybe LVGL one too, later but i dont know this one yet.

**Comment by thisiskeithb** [comment]
> maybe LVGL one too, later but i dont know this one yet.

LVGL has it's own image for a bootscreen, so it's not affected by Marlin's bootscreen settings.

**Comment by tpruvot** [comment]
TFT_SCALED_DOGLCD is already set by HAS_MARLINUI_U8GLIB
the change is not useful ... well its using u8g (dogm) else yea, i could just comment but i want to let the users the choice of the ui... in a simple switch

was an "undef" on my local commit https://github.com/tpruvot/Marlin/commit/79543d0ecd503cda87d0ff914e14f17dc999fab8#diff-c7a3fa925098d81e51840820898b66e3d3e48f121a83e4d0b6c65e5ab4f2fba0R1156

**Comment by thisiskeithb** [comment]
> TFT_SCALED_DOGLCD is already set by HAS_MARLINUI_U8GLIB
> the change is not useful ... well its using u8g (dogm)

You sure about that 🙂 I just tested my PR on an ET5 with a TFT35 and it works as expected.

Leaving `BOOT_MARLIN_LOGO_SMALL` enabled will give you the small bootscreen.

Commenting out `BOOT_MARLIN_LOGO_SMALL` will give you the normal/large bootscreen.

**Comment by tpruvot** [comment]
yep, i could comment but in this case i need to uncomment on COLOR_UI switch :p

**Comment by tpruvot** [comment]
there is another one bugging me on the switch, had to add that :
```
#if ENABLED(TFT_COLOR_UI)
 #undef CUSTOM_STATUS_SCREEN_IMAGE // only in Classic UI
```

**Comment by tpruvot** [comment]
by simple switch i mean there in Marlin/Configuration.h
```
/**
 * TFT UI - User Interface Selection. Enable one of the following options:
 *
 *   TFT_CLASSIC_UI - Emulated DOGM - 128x64 Upscaled
 *   TFT_COLOR_UI   - Marlin Default Menus, Touch Friendly, using full TFT capabilities
 *   TFT_LVGL_UI    - A Modern UI using LVGL
 *
 *   For LVGL_UI also copy the 'assets' folder from the build directory to the
 *   root of your SD card, together with the compiled firmware.
 */
//#define TFT_CLASSIC_UI
#define TFT_COLOR_UI
//#define TFT_LVGL_UI
```

**Comment by thisiskeithb** [comment]
> there is another one bugging me on the switch, had to add that :
> 
> ```
> #if ENABLED(TFT_COLOR_UI)
>  #undef CUSTOM_STATUS_SCREEN_IMAGE // only in Classic UI
> ```

I'm sorry, but what does that have to do with this PR?

Please undo custom changes to your fork & confirm that my PR fixes the bootscreen sizes without muddying the main issue.

**Comment by thisiskeithb** [comment]
I've confirmed using a full graphics LCD as well as an emulated full graphics LCD (with `TFT_CLASSIC_UI` & `TFT_COLOR_UI`) uses the correct bootscreen size depending on if you leave `BOOT_MARLIN_LOGO_SMALL` enabled or disabled.

**Comment by tpruvot** [comment]
https://github.com/tpruvot/Marlin/blob/dev/buildroot/tests/STM32F103VE_longer-tests#L23-L25

may explain better...

**Comment by tpruvot** [comment]
to return on this PR topic... it was already small by default for TFT_CLASSIC_UI with the commit merged yesterday

**Comment by thisiskeithb** [comment]
I have no idea what you're trying to point out.

Please put in a separate PR to fix whatever issue you've found.

**Pull request closed without merging**
