### PR TITLE
Adjustments due to recent changes

### PR DESCRIPTION
**Pull request by Tannoo**
UBL Menu adjustments.

### CODE REVIEW

**Comment by Tannoo** [comment]
Is there going to be a replacement for `G29 N`?

**Comment by Tannoo** [comment]
Maybe a condition to write in that N (or whatever it may become) cannot be used by itself or with P?

Unnecessary movements if your getting info about UBL and don't need to home the machine.
But, ok.

**Comment by Roxy-3D** [comment]
How strongly do you feel about having the ability to do UBL things without homing the machine?  We can certainly put a mechanism in place to do that.    But in general...   The user really ought to home the machine before they do much with it.     Mostly, I was trying to get rid of the **_critical comments_** that keep appearing in my code:
```cpp
    // Don't allow auto-leveling without homing first
 -    if (!(code_seen('N') && code_value_bool()) && axis_unhomed_error()) // Warning! Use of 'N' flouts established standards.
 +    if (axis_unhomed_error()) 
        home_all_axes();
  }
```

**Comment by Tannoo** [comment]
It doesn't hurt anything to home for every command, just additional wear-n-tear. That's all.

**Comment by Tannoo** [comment]
It just has to home or be homed to:
`G29 L(x)`
`G29 S(x)`
`G29 O(x)`
`G29 W`
`G29 A`
`G29 D`.

It would be nice to not have to home (if not homed) to do the above functions.

Don't really need a parameter to ignore homing, but maybe add/remove homing conditionals to those functions?

**Comment by Roxy-3D** [comment]
> It doesn't hurt anything to home for every command, just additional wear-n-tear. That's all.

No!  It shouldn't happen for every command.   It is a one time thing.  After the first command, the machine will be homed...   And it should not home for subsequent commands.   If that is not the case...  We need to fix it!

**Comment by Tannoo** [comment]
>No! It shouldn't happen for every command.

I stand corrected, You are correct. If the steppers haven't timed out, or a print has finished with an M84...Then all is good.

Otherwise, they will home again. There's nothing to fix on that end.

**Comment by Tannoo** [comment]
How's this?
```
    if (axis_unhomed_error()) 
      if (!code_seen('P') || !code_seen('J') || !code_seen('U') || !code_seen('Q') || !code_seen('I')) {
      }
      else {
        home_all_axes();
      }
```

**Comment by Roxy-3D** [comment]
I don't think Q or I requires the machine to be homed...  It is probably OK to yank those out.   But isn't that logic backwards?  Shouldn't it be:
```cpp
    if (axis_unhomed_error()) 
      if (!code_seen('P') && !code_seen('J') )) {
      }
      else {
        home_all_axes();
      }
```
which would translate into:
```cpp
    if (axis_unhomed_error()) 
      if (code_seen('P') || code_seen('J') )) {
        home_all_axes();
      }
   }
```
which further simplifies to:
```cpp
    if (axis_unhomed_error() && (code_seen('P') || code_seen('J') )) {
        home_all_axes();
      }
   }
```

Because scanning through the list of options...  It would seem only the P and J commands need the machine homed.

**Comment by Tannoo** [comment]
Well, upon testing, `G29 J` didn't home when it needs to. <-- 3-point mesh leveling.

**Comment by Roxy-3D** [comment]
> Well, upon testing, G29 J didn't home when it needs to. <-- 3-point mesh leveling.

OK.   If the status changes...  Let me know.   But I'll look into it in the morning and get that fixed.   For your menu system...   Please just assume G29 J    or G29 J0 will do 3-Point Leveling...

**Comment by Tannoo** [comment]
Ok. I have it set for `G29 J`.

**Comment by Roxy-3D** [comment]
> Ok. I have it set for G29 J.

I will test that exact construct in the morning and resolve the issue you are seeing.    

THANK YOU!!!  @Tannoo 

If your updates are complete...   Please let me know...  It might make sense to merge them prior to me getting G29 J0 working just because I'll be able to put a little bit of test time on to your updates.

**Comment by Tannoo** [comment]
No problem.... But also noticed that your mesh height is now P6... Getting that in there also.

**Comment by Roxy-3D** [comment]
P6 doesn't need the machine homed...  But I don't think we want to be that granular.   And P6 will not get used very often.

**Comment by Tannoo** [comment]
I agree, I just put it in the menu for the Mesh height adjustment. It used to be Z.

**Comment by Tannoo** [comment]
>which would translate into:
>```    if (axis_unhomed_error()) 
>      if (code_seen('P') || code_seen('J') )) {
>        home_all_axes();
>      }
>   }
>```

This is good. Tests ok for me.

**Comment by Tannoo** [comment]
```
    if (axis_unhomed_error()) {
      if (code_seen('P') && !code_seen('P6') || code_seen('J')) {
        home_all_axes();
      }
    }
```

I added that for P6 because adjusting the mesh height doesn't need homing. It works.

**Comment by Tannoo** [comment]
I am done. This is a good solution to losing the `N`.
I have also swashed it all.

**Comment by Roxy-3D** [comment]
> I have also squashed it all.

I might be mistaken...   But I don't believe you need to do that in most cases.  One of the options is 'Squash & Merge'.   So if everything is associated with a single topic, we can just hit the 'Right' button and make that happen.

**Comment by Tannoo** [comment]
ok. It gave me more practice anyway. lol

**Comment by Roxy-3D** [comment]
So I haven't tried to compile the code...  But I don't understand how this can pass the Travis test:
```cpp
     if (code_seen('P') && !code_seen('P6') || code_seen('J')) {
```
'P6' is **_NOT_** a character!    My guess is the compiler issues a warning that it has truncated that to 'P' and Travis is ignoring warnings????   I don't know the answer.   But that 'P6' isn't right.

**Comment by Tannoo** [comment]
It also compiles and works.

**Comment by Roxy-3D** [comment]
P6 works???   I'm a little bit skeptical....     I think that is going to evaluate to (code_seen('P') && !code_seen('P')) which is always 0.

**Comment by Tannoo** [comment]
It works without homing while unhomed.

**Comment by Roxy-3D** [comment]
yeah...  and the other P commands will do the same... P1 will try to do its thing without homing if it is not homed.   Right?   Give that a quick check.

**Comment by Tannoo** [comment]
With the printer unhomed and manually moved X and Y off the limits (steppers were disabled), I sent `G29 P1`.

It homed and started to probe.

**Comment by Roxy-3D** [comment]
OK...   Something else is going on.   Who knows?  But code_seen(char) expects a character to be passed in.    And 'P6' doesn't seem like a 'normal' character to me.    Don't worry about it...  I'll poke it with a stick a few times in the morning and see if I can figure it out....
```cpp
// GCode support for external objects
bool code_seen(char);
int code_value_int();
```

**Comment by Tannoo** [comment]
Proof of G29 P1?
```
echo:Z-Probe Offset (mm):
echo:  M851 Z-3.65
echo:DEBUG:ECHO
ok
echo:SD card ok
echo:G29 P1
echo:Home XYZ first
echo:busy: processing
X:0.00 Y:0.00 Z:5.65 E:0.00 Count X:0 Y:0 Z:21712
Mesh invalidated. Probing mesh.


Mesh only partially populated.

ok
```

**Comment by Tannoo** [comment]
Proof G29 P6?
```
echo:  M851 Z-3.65
echo:SD card ok
echo:DEBUG:ECHO
ok
echo:G29 P6.3
echo:Home XYZ first
ok
```
The serial message of 'Home XYZ first' came from elsewhere in the code. The printer is still not homed and steppers are still disabled.

**Comment by Roxy-3D** [comment]
> The serial message of 'Home XYZ first' came from elsewhere in the code. The printer is still not homed and stepper are still disabled.

OK...   I'll hunt that down in the morning too.  I'll get that so it is consistent...

**Comment by Tannoo** [comment]
Okay. No rush.

**Comment by Tannoo** [comment]
Wow...what happened here?

I'll create another PR.

**Comment by thinkyhead** [comment]
I resolved the conflicts… or was in the process of resolving them. Also, the HEAD of the Marlin tree got a little fudged. Anything rebased very recently will be annoyed.

**Pull request closed without merging**
