### PR TITLE
Support for COREYX, COREZX, COREZY

### PR DESCRIPTION
**Pull request by thinkyhead**
Some core / h-bot machines have an arrangement that reverses the second core axis compared to the usual. This PR accommodates these setups.

### CODE REVIEW

**Comment by landodragon141** [comment]
Lol now I'll have to rewrite that part of the documentation... sigh... XP

**Comment by thinkyhead** [comment]
Actually, @landodragon141 I'm not sure this will be merged right now. I thought possibly I was dealing with a machine where the XY were reversed. But it turned out to be a typical CoreXY. However, Repetier-Firmware does allow for this, so… maybe we'll integrate it. But don't feel you have to document it now. I'll probably hold off on this until after 1.1.0-RC8.

**Comment by landodragon141** [comment]
I know I was mostly teasing. Good to know though.

**Comment by thinkyhead** [comment]
Holding off on this until it's obvious that we need it. So far no one has actually requested this set of options, and I made it just for completeness.

**Pull request merged**
