### PR TITLE
Followup to bl touch and ext ui

### PR DESCRIPTION
**Pull request by InsanityAutomation**
Remove crash by default settings of V3 probe and refix ExtUI compile error.

Z_VALUES is a macro to return a single point and does not reference the complete array. Usage as the complete array results in a compile error.

Most users will have no ideas they got a V3 until it crashes. The only physical indication is a tiny etch on the PCB. Since the V2 safely ignores the new commands, they should be issued regardless.

### CODE REVIEW

**Comment by InsanityAutomation** [comment]
Tagging #13345 

Also, given the likelihood of issues with these probes, I feel it may be worth discussing a late patch to 1.1.9 with the same commands added, as many users are still on it. Since there is no tagged snapshot to point users to, the user base there is still quite large.

**Comment by ghost** [comment]
What confuses me is
```
#elif ENABLED(ENDSTOPPULLUPS) || (ALL(ENDSTOPPULLUP_ZMIN, Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN)) || (ENABLED(ENDSTOPPULLUP_ZMIN_PROBE) && DISABLED(Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN))
    set_5V_mode();                  // Assume 5V DC logic level if endstop pullup resistors are enabled
```
I always thought that if there is an open-drain output, I NEED a pull-up. So that if pull-ups are enabled, I would probably be in open-drain mode.
Conversely, in 5V mode, I thought that the probe will output Logic 0 = close to 0V and Logic 1 = close to 5V and would NOT NEED a pull-up.
Anyhow, deducing the needed mode from the pull-up configuration is iffy. I would have thought it goes the other way round - you define the desired BLTouch config and the enforce (or not) a pull-up on that pin.
Of course, @InsanityAutomation, you have tested your V3.0 and I am sure you have got it right, no sweat, but I remain confused - without schematics from ANTClabs 'tis difficult to know.
Apart from that, I have downloaded the current version and not enabled the V3 and at least can confirm that it still works with BLTouch V2.

**Comment by InsanityAutomation** [comment]
@FanDjango The intention is by default to make a best guess to what will work the most reliably. The documentation states the pull up is required wehen using open drain mode 

> Set Zmin pull-up on your firmware when using Logic Free (In most cases, it is already set up) 

And most machines are 5v with pullups enabled.

I agree deducing needed mode is a bit iffy, but the goal here is to prevent damage when an unsuspecting user swaps a damaged probe for a new one not realizing they got a 3.0. Anyone using a new enough 32bit board with 3.3v logic is most likely an advanced user that will know to set it given the current market penetration so take a best guess towards 5v erroring on the side of 5v is the most prudent course.

**Comment by ghost** [comment]
I agree and support totally your viewpoint.
It is the logic implementation that confuses me:

> The documentation states the pull up is required wehen using open drain mode

In that case, why, in the code, do you infer **5V Mode** from enabled pull-ups? (instead of open-drain mode).

Aaah! Ok, setting 5V Mode won't break anything? It will still work on a pull-up enabled machine (will it?). I understand now, I think.

In that case you might want to select 5V Mode in ALL cases unless the user explicitly wants OD-Mode in the config.

```
 #if ENABLED(BLTOUCH_FORCE_5V_MODE)
    set_5V_mode();
  #elif ENABLED(BLTOUCH_FORCE_OPEN_DRAIN_MODE)
    set_OD_mode();
  #else
    set_5V_mode();
  #endif
```

**Comment by InsanityAutomation** [comment]
@FanDjango Because I could verify it always worked, and I dont have anything 3.3v to test with. I could mess with open drain more if I had a 3.3v logic level board but im mostly erroring towards safe with what worked on each of the 3 boards I tried it on here.

On the other hand, I could always assume 5v mode unless explicitly set as 3.3v, and edit alot of the board definitions with known logic levels. That would take some input from people who know alot of the boards out there.

**Comment by ghost** [comment]
On a 3.3V board, and you are suppying the BLT with 5V, setting 5V Mode for the output could potentially kill your board if the input pin is not 5V compliant/tolerant. Can of worms being opened here. On your scope, what's the output level in 5V Mode on an unconnected black/white lead?

**Comment by InsanityAutomation** [comment]
True enough, the latter option is more than likely the correct course of action, documenting board logic levels. Would probably need the most input on the 32 bit boards. A day of googling can probably determine that. Then we can add an ifndef BLTOUCH_FORCE_5V_MODE and BLTOUCH_FORCE_OPEN_DRAIN_MODE set whichever the board is.

**Comment by ghost** [comment]
From BLTouch V3 they have finally moved to a default config of Open Drain, which works fine on 3.3V and 5V (but it needs pull-ups on) and this mode CANNOT destroy an input pin.
I think that they did this because the BLT was becoming too difficult to interface to any input pin that was NOT 5V logic - such as many/most of the 32-bit boards and some other 8-bit ones. 
But how could they ship these new ones (the poor guy with the 💯 pieces 👎  ) just like that, sheesh.
Anyway, could one not take this from the other route: If BLTouch is defined, regardless of V2 or V3, force the pull-up on that pin to enable and always set open-drain mode, regardless of board? Should still work with the old V2's and should work with the V3, on 5V and 3.3V boards. The V2's are capable of setting a logic 0 against the pull-up.

OMG a can of worms indeed thanks for you patience on this

**Comment by InsanityAutomation** [comment]
> Anyway, could one not take this from the other route: If BLTouch is defined, regardless of V2 or V3, force the pull-up on that pin to enable and always set open-drain mode, regardless of board? Should still work with the old V2's and should work with the V3, on 5V and 3.3V boards. The V2's are capable of setting a logic 0 against the pull-up.

In theory probably, provided the board has one forcing the pullup on should work, just as we force pin inverting for the bltouch. Ill play with that a little on the 5v boards later today.

Wishing I had something 3.3v to mess with as well :(

**Comment by ghost** [comment]
Ok. I can relate to all that you are saying and thanks for the discussion. And no one can expect the devs to have all boards on stock for this kind of problem. Be more the duty of the ANTClabs people actually.

One of my boards is an MKS SBASE. I had a look at the schematic and I can see that the input pins chosen for the endstops (and thus my BLTouch) are on P1.xx. According to the LPC1769 datasheets these pins are 5V tolerant when configured as digital input pins. So, no problem to set the BLTouch to 5V Mode on this board - as a matter of fact, my BLT is V2.0 so it is actually in 5V mode already by default (didn't cut the 3.3V trace on the circuit board).  The LPC1769 is a sensible choice in this respect - 5V tolerance is a very nice thing and saves a lot of hassle on the interfaces to external components.

Info which 3.3V boards are not 5V tolerant on the pin recommended for the BLTouch would actually be something I would expect to see in the pre-V3.0 instructions from ANTCLabs, they have their wiring recommendations for quite a few boards, but who knows how well they did their homework, is the information complete? If all boards are 5V tolerant, the current commit would be perfectly ok even on any 3.3V board.

**Comment by InsanityAutomation** [comment]
@FanDjango Aside from that, anyone doing a replacement knows they had to modify things for 3.3v and will look into that once they realize the trace isnt there any more. By default it operates electrically at 5v with the current units so if one side should be looking to change modes, its 3.3v

**Comment by Roxy-3D** [comment]
> Also, given the likelihood of issues with these probes, I feel it may be worth discussing a late patch to 1.1.9 with the same commands added, as many users are still on it. Since there is no tagged snapshot to point users to, the user base there is still quite large.

My vote would be we put it in the 1.1.x BugFix and verify it does everything it is supposed to.    And if that turns out to be the case, we cross those same changes over to v1.1.9.

**Comment by InsanityAutomation** [comment]
@Roxy-3D Id agree there, ill toss that PR together tomorrow probably. Since 1.1.9 is EOL though itll be a simplified version with just the necessities.

**Comment by thinkyhead** [comment]
Version 1.1.9 gets no more patches. Patches to `bugfix-1.1.x` only. If it accumulates enough patches to warrant a release tag, we have the choice of 1.1.9.1, 1.1.10, 1.1.9-1, etc….

**Pull request merged**
