### PR TITLE
Add option and sanity check for M600 requires Home

### PR DESCRIPTION
**Pull request by ghost**
As suggested in comments to pull request #7052, this pull adds an option and sanity check.

### CODE REVIEW

**Comment by ghost** [comment]
My inexperience is showing... I don't know why it's including the previous commit in this pull request.

**Comment by tcm0116** [comment]
> I don't know why it's including the previous commit in this pull request.

You can rebase and squash the commits. Google git rebase and there are several examples. 

However, I have a few comments. First, the new option should probably be disabled by default (and the spacing of the comment adjusted to align with the other comments). Second, the new option needs to be added to all of the example configuration files.

**Comment by ghost** [comment]
Gotcha. What's the best way to delete this pull request?

Thanks.

**Comment by FHeilmann** [comment]
When you create a new configuration option you also need to update all example configurations. Just FYI

**Comment by Roxy-3D** [comment]
> When you create a new configuration option you also need to update all example configurations. Just FYI

I'm on Windows.   What I do is run AstroGrep and it will find all the files with the search phrase.   I can just double click on each example/???/configuration.h file and it goes right to the correct location.  I then paste in the update.

**Comment by ghost** [comment]
Still not clear on how to get rid of this pull request so that I can do a new one with the above suggestions.

Thanks.

**Comment by tcm0116** [comment]
You don't have to get rid of this PR. You can just keep pushing commits to
the branch in your fork, and that will update this PR. When everything is
satisfactory, you can rebase your branch to squash all of the commits
together, and then do a forced push to your branch, which will then result
in one change showing on this PR.

**Comment by Roxy-3D** [comment]
As long as it is a single topic...   We can do the Squash when we Merge.   He doesn't have to do that part of it.

**Comment by ghost** [comment]
Ok, I think I've got it this time... Still have that conflict between the original commit and PR though... I'm guessing someone will resolve that?

Thanks.

**Comment by Roxy-3D** [comment]
This is brute force...  But if you set your current directory aside...   And re-fork Marlin, you should be able to copy your changes into the new fork.   And the conflicts will magically go away.

**Comment by tcm0116** [comment]
> This is brute force... But if you set your current directory aside... And re-fork Marlin, you should be able to copy your changes into the new fork. And the conflicts will magically go away.

To do that, you'll need to follow these steps:

```
# In a different working directory, clone your GitHub fork.
cd Marlin
git remote add upstream https://github.com/MarlinFirmware/Marlin.git
git fetch upstream        ;# always do this to get the latest from the main Marlin GitHub
git checkout upstream/bugfix-1.1.x
git checkout -b M600Home  ;# Copy the changed files from the original working directory
git diff                  ;# to make sure you're happy
git add -u                ;# stages all unstaged files
git commit -m "Don't allow filament change without homing first"
git push -f --set-upstream origin M600Home  ;# -f to replace M600Home in your fork
```
That should overwrite the commits on the PR with a single commit with your changes against bugfix-1.1.x.

P.S. Don't ask why I know how to do that... ;-)

**Comment by ghost** [comment]
@tcm0116, followed your instructions. Hope this does it.

Thanks.

**Comment by Roxy-3D** [comment]
>> This is brute force... But if you set your current directory aside... And re-fork Marlin, you should be able to copy your changes into the new fork. And the conflicts will magically go away.

> To do that, you'll need to follow these steps:

No...  I'm more brute force than that.   I use ExamDiff Pro to show me every file that is different.   And I just take my changes and tell them to jump from one column to the other...   (from one file in one branch to the same file in the other branch).   And then I commit and there aren't any conflicts any more.

You can use NotePad++ with the visual diff plug in and do the same thing...

**Comment by tcm0116** [comment]
>  Hope this does it.

@JimBrown Looks like it did. It passed the Travis checks, and it's only one commit. Glad those instructions worked. I pretty much follow steps 4 to the end whenever I have a change I want to create a PR. That process ensures that you're starting with the latest bugfix-1.1.x. If you have a branch that has your configuration files, you can do `git checkout my_branch -- Configuration.h Configuration_adv.h` after step 5 to get them into your working directory. Just unstage them before you commit your other changes, and you're good to go.

**Comment by thinkyhead** [comment]
I've moved your commit over to #7071 and made some tweaks. Will be merged shortly!

**Pull request closed without merging**
