### PR TITLE
Change Filament Feature

### PR DESCRIPTION
**Pull request by antonkopa**
I decided to test out the "Change Filament" feature, and before it continues the print, it pulls the filament completely back out again.

When I commented out #define AUTO_FILAMENT_CHANGE, it doesn't have this issue.

The issue here I believe is the current position of the extruder is not being restored from the remembered position.

FILE: Configuration_adv.h

```
// Add support for experimental filament exchange support M600; requires display
#if ENABLED(ULTIPANEL)
#define FILAMENTCHANGEENABLE
  #if ENABLED(FILAMENTCHANGEENABLE)
    #define FILAMENTCHANGE_XPOS 3
    #define FILAMENTCHANGE_YPOS 3
    #define FILAMENTCHANGE_ZADD 10
    #define FILAMENTCHANGE_FIRSTRETRACT -2
    #define FILAMENTCHANGE_FINALRETRACT -100
    #define AUTO_FILAMENT_CHANGE                //This extrude filament until you press the button on LCD
    #define AUTO_FILAMENT_CHANGE_LENGTH 0.04    //Extrusion length on automatic extrusion loop
    #define AUTO_FILAMENT_CHANGE_FEEDRATE 300   //Extrusion feedrate (mm/min) on automatic extrusion loop
  #endif
#endif
```

### CODE REVIEW

**Comment by KiteLab** [comment]
Sorry I'm unable to find your changes, if any. Would you please make a new PR against RCBugFix.
If this is not a Pull Request, where you want to contribute some of your code. Please close this PR and open a new Issue at https://github.com/MarlinFirmware/Marlin/issues

**Comment by thinkyhead** [comment]
Good catch! Even though this feature is labeled "experimental" I feel it should definitely be patched up for RC4, so please re-do the PR. If you have any difficulty rebasing it onto RCBugFix feel free to ask for assistance! As a side-note, in future it would be good to remove the requirement for an LCD display, perhaps by expanding `M600` with an extra parameter.

**Comment by alexkaps** [comment]
Trying to troubleshoot  #2933 

The problem exists somewhere between these lines:
`current_position[E_AXIS] += AUTO_FILAMENT_CHANGE_LENGTH;
        destination[E_AXIS] = current_position[E_AXIS];
        line_to_destination(AUTO_FILAMENT_CHANGE_FEEDRATE);
        st_synchronize();
`

`#if ENABLED(AUTO_FILAMENT_CHANGE)`
`current_position[E_AXIS] = 0;`
`st_synchronize();
`

`if (code_seen('L')) destination[E_AXIS] -= code_value();
      #ifdef FILAMENTCHANGE_FINALRETRACT
    else destination[E_AXIS] -= FILAMENTCHANGE_FINALRETRACT;
    #endif
`
`current_position[E_AXIS] = destination[E_AXIS]; //the long retract of L is compensated by manual filament feeding
    plan_set_e_position(current_position[E_AXIS]);`

Inside M600 there are 3 variables concerning each axis, i'm focusing on E axis:
lastpos[E_AXIS] , current_position[E_AXIS],  destination[E_AXIS]
Need some clarification,
**lastpos**:              temporal variable, stored the position of the axis at the time of pause?
**destination**:        tells the axis to move to a defined position ?
**current_position** sets the position that the axis THINK to be?

what is:
line_to_destination ?
plan_set_e_position?

while auto_filament_change is enabled and Lcd button is not pressed  the E axis moves in a loop that is added to his current position. When the button is pressed it needs to return at the lastpos for all axis. The problem is that E axis has a value far from initial because of the auto_filament loop. 

How can i set the E axis think that is at the lastpos when X,Y,Z return without moving?
Tried to set current_position = lastpos but it moves to that position instead of "be" there.

**Comment by thinkyhead** [comment]
I would like to look at this further, but the commits need to be rebased against `RCBugFix` so we can see the changes in isolation.
- First, make sure your working copy has a proper `upstream` remote. If needed, use `git remote add upstream git@github.com:MarlinFirmware/Marlin.git` to add this repo as a remote.
- Now you can use `git fetch upstream` to fetch all the latest commits and branches from this repo.
- To fix up the branch you've been working with you'll need to use `git checkout RC -b my_filament_patch` to copy your commits to a new branch.
- Now you can use `git rebase upstream/RCBugFix` to re-stage your commits on top of the latest `RCBugFix` branch. You may need to patch conflicts during this process. Keep using `git add * ; git rebase --continue` or `git rebase --skip` until all the commits are as they should be.
- When you submit your new PR, be sure to make it against `RCBugFix` and not against `RC`.

**Comment by thinkyhead** [comment]
I will close this for now and we can continue to discuss this issue in a new topic around M600. Current topics of discussion are:
- Integrating Josef Prusa's general implementation of `M600`
- Adding `keepalive` and `paused for input` messages to keep hosts happy during long operations

See #3068 and #2933 for some background.

**Pull request closed without merging**
