### PR TITLE
Map clean up of UBL

### PR DESCRIPTION
**Pull request by Roxy-3D**
UBL's maps are cleaner.   And with a 1 value, G29 O 1  will generate a
map suitable to be Cut & Pasted into Excel so a Suface Map can be
generated.

@Tannoo   Please check it out and see if you have any recommendations to make it better.

### CODE REVIEW

**Comment by ghost** [comment]
Ok, cool!

**Comment by Tannoo** [comment]
Well, `G29 O1`, or `G29 O 1` gives me this:
```
       .                 .            0.07969     0.06484     0.07448     0.04740     0.11120     0.11146     0.02188    -0.19792   
 
       .                 .            0.16589     0.18958     0.22057     0.21016     0.30417     0.21667     0.12760    -0.14036   
 
       .                 .            0.22318     0.26224     0.33359     0.31745     0.30000     0.34740     0.14089    -0.08828   
 
       .                 .            0.23698     0.30833     0.39427     0.42161     0.45391     0.31979     0.25677    -0.07708   
 
       .                 .            0.24740     0.33516     0.38099     0.42474     0.42943     0.34010     0.24427    -0.01562   
 
       .                 .            0.21563     0.33464     0.41771     0.40807     0.41536     0.38438     0.27786     0.04245   
 
       .                 .            0.21901     0.31875     0.38438     0.39453     0.40026     0.38568     0.32318     0.11276   
 
       .                 .            0.21563     0.28229     0.35365     0.37865     0.39479     0.41094     0.37839     0.15313   
 
       .                 .                 .                 .                 .                 .                 .                 .                 .                 .          
 
[      .       ]        .                 .                 .                 .                 .                 .                 .                 .                 .          
```

**Comment by ghost** [comment]
Scratch that.... h/o.

**Comment by ghost** [comment]
With `G29 O1` or `G29 O 1`, I get this:
```
NAN,NAN,0.130,0.108,0.093,0.134,0.105,0.085,0.045,-0.178
NAN,NAN,0.211,0.227,0.230,0.323,0.216,0.212,0.156,-0.119
NAN,NAN,0.229,0.271,0.338,0.402,0.405,0.272,0.218,-0.088
NAN,NAN,0.253,0.337,0.399,0.420,0.437,0.410,0.202,-0.045
NAN,NAN,0.261,0.343,0.426,0.490,0.416,0.372,0.253,0.007
NAN,NAN,0.254,0.342,0.425,0.418,0.412,0.391,0.280,0.053
NAN,NAN,0.218,0.319,0.390,0.402,0.420,0.406,0.322,0.120
NAN,NAN,0.214,0.285,0.354,0.380,0.398,0.408,0.377,0.190
NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN
NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN
```
What's up the the `NAN`s?

**Comment by BillStruve** [comment]
Not A Number NAN is an attempt to divide by zero.

**Comment by Roxy-3D** [comment]
> What's up the the NANs?

When you do a G29 P1, the entire Mesh is set to 'invalid'.   That is what the '.' means when you do a map.   

In this specific case, your X_OFFSET_FROM_EXTRUDER and Y_OFFSET_FROM_EXTRUDER are large enough that the automatic probing can not reach the mesh points where NAN appears.   Populating the mesh with NAN's is way to guarantee invalid locations do not get used in the calculations.  The floating point number standards specifically state that if NAN is used in a calculation, the result will be NAN.   So, without doing lots of extra (and CPU cycle burning) checks...   You can just go ahead and do the calculations and assume every thing is OK.  And then just check the final number and see if it is NAN.  If it is...   You throw it out and don't use it.

OK...   What does this mean for you?   It means you do  not have Z-Height correction across your entire bed.  Some of the bed could not be probed because of the location of the Z-Probe.  There are a number of ways to deal with it.
- Ignore it...  And just accept the fact that in your case any coordinate close to X=0 or Y=0 is uncorrected.   This is what you have been doing but is not recommend.
- Print a G26 Mesh Validation Pattern and edit the locations with NAN.   Even though those numbers are not helping with Z-Height correction, you can still edit them and at that point they will start contributing to the calculations.
- Position the nozzle in an area.   If I were doing this, I would put the nozzle in the upper left.  I would then give the system G29 P3 O R3 C.25 commands.   You will see more and more NAN's disappear and get replaced with .25 which are not 'corrrect' but closer to correct than no calculation at all.   When the numbers got a little bit around the corner, I would switch to G29 P3 O R3 C.4    Now you can save the mesh and start a G26 Mesh Validation Pattern and fine tune things.
- Very soon, there will be a new G29 P command that extends the known (and measured) mesh outwards.   This single command will do what the previous bullet point did, except automatically and with more precision.

**Pull request merged**
