### PR TITLE
Option to leave heaters set on SD abort

### PR DESCRIPTION
**Pull request by kaushikvemparala**
### Requirements

* None

### Description
I saw someone request this feature in the issues forum (#13987), so I thought it would be nice to have it as an option. I added one macro in Configuration.h (DONT_COOLDOWN_ON_PRINT_ABORT) and a little code in Marlin.cpp.
I tested with and without the macro being declared, and it works. The declaration is currently commented out.

### Benefits
Issue #13987 

### Related Issues
#13987

### CODE REVIEW

**Comment by thinkyhead** [comment]
Moved the option to `Configuration_adv.h`, renamed to `PRINT_ABORT_NO_COOLDOWN`, added the new option to the example configurations.

**Comment by forkoz** [comment]
Yes please... Nice to be able to restart a failed print right away.

**Comment by thinkyhead** [comment]
In the future we'll actually implement a per-tool standby temperature, at which time this will go away.

**Comment by ghost** [comment]
I uncommented the #define SD_ABORT_NO_COOLDOWN but the heaters turn off 2 seconds after I click on stop print. Why is this happening?
Ender 3 with MKS GEN L and reprapdiscount full graphic display. 

Thanks

**Pull request merged**
