### PR TITLE
MKS PWC module adds macro definition

### PR DESCRIPTION
**Pull request by mks-viva**
### Description
MKS PWC module adds macro definition, the main reason is that using the MKS PWC module in the past, there were too many modifications, and the difficulty of using it increased. This modification makes it easier to use MKS PWC. 

1. In Confiuration.h file
   - Add: #define MKS_PWC
2. Include the motherboard is
   - MKS Robin Nano V3
   - MKS Robin Nano V2
   - MKS Robin Nano
   - MKS Robin E3
   - MKS Robin Pro
   - MKS Sgen l V1,V2
   - MKS Sbase, SGEN
3. If use LVGL, has #undef PSU_CONTROL

### CODE REVIEW

**Comment by thinkyhead** [comment]
It looks like `PSU_CONTROL` with certain boards is just always going to be `MKSPWC`. So I have replaced `MKS_PWC` and `MKSPWC` with `PSU_CONTROL`-on-MKS-boards.

There are still some pins overlapping that need to be looked at. In particular, the `POWER_LOSS_PIN` overlaps the `KILL_PIN` and the `PS_ON_PIN` overlaps with `SUICIDE_PIN`.

**Comment by mks-viva** [comment]
> It looks like `PSU_CONTROL` with certain boards is just always going to be `MKSPWC`. So I have replaced `MKS_PWC` and `MKSPWC` with `PSU_CONTROL`-on-MKS-boards.
> 
> There are still some pins overlapping that need to be looked at. In particular, the `POWER_LOSS_PIN` overlaps the `KILL_PIN` and the `PS_ON_PIN` overlaps with `SUICIDE_PIN`.

Yes, as you said. Looks more reasonable.

**Comment by javicarrera** [comment]
Please if you can check my proposal for PWC+UPS: 
https://github.com/MarlinFirmware/Marlin/commit/c1a533b45e21c43eda6fedb9679976747bca6845#commitcomment-54579264

**Comment by Rockman18** [comment]
Hello @mks-viva, @thinkyhead,

Since this commit, on TFT_LVGL_UI, with MKS PWC on a Robin Nano v2, the KILL_PIN is not set anymore so the MKS PWC switch doesn't shutdown the printer anymore. Ask for a shutdown with the UI menu works (SUICIDE is ok).

Why create an error "PSU_CONTROL cannot be used with TFT_LVGL_UI". This should work. Perhaps something like this could be better : 

```
#if HAS_TFT_LVGL_UI
  #define SUICIDE_PIN                       PB2
  #define SUICIDE_PIN_INVERTING            false
#endif
#if ENABLED(PSU_CONTROL)                          // MKSPWC
  #ifndef KILL_PIN
    #define KILL_PIN                        PA2
    #define KILL_PIN_STATE                  HIGH
  #endif
  #if !(HAS_TFT_LVGL_UI)
    #ifndef PS_ON_PIN
      #define PS_ON_PIN                       PB2   // SUICIDE
    #endif
  #endif
#endif
```

**Comment by thinkyhead** [comment]
Thanks, I'll patch these up where appropriate. The `#error` line replaces the old line which was `#undef PSU_CONTROL`. Unfortunately the original contributor from MKS failed to affirm or refute my edits, so we are only now getting clarification.

**Comment by Rockman18** [comment]
I haven't check but perhaps keeping PSU_CONTROL defined will cause issue.
We can imagine doing that :
```cpp
#if ENABLED(PSU_CONTROL)                          // MKSPWC
  #if HAS_TFT_LVGL_UI
    #error "PSU_CONTROL cannot be used with TFT_LVGL_UI. Disable PSU_CONTROL to continue."
  #endif
  #ifndef PS_ON_PIN
    #define PS_ON_PIN                       PB2   // SUICIDE
  #endif
  #ifndef KILL_PIN
    #define KILL_PIN                        PA2
    #define KILL_PIN_STATE                  HIGH
  #endif
#else
  #define SUICIDE_PIN                       PB2
  #define SUICIDE_PIN_INVERTING            false
  #if HAS_TFT_LVGL_UI && ENABLED(MKSPWC)
    #define KILL_PIN                        PA2
    #define KILL_PIN_STATE                  HIGH
  #endif
#endif
```

**Comment by thinkyhead** [comment]
@Rockman18 — It's not entirely clear, as I found some instances where `TFT_LVGL_UI` was apparently the requirement, versus the original commits from this PR where `TFT_LVGL_UI` was anathema to `PSU_CONTROL`. For example, see https://github.com/MarlinFirmware/Marlin/pull/22528/commits/7b7c1f72464e2fa964b3fe34bb4275140e6996ef#diff-7198171b0eac3f73749d703c215050b5bddf5ed6e560baaa1c90a672062b41fbR132

**Comment by thinkyhead** [comment]
So, I need some clarification on why a separate `MKSPWC` (or `MKS_PWC`) option makes sense for this hardware add-on and why it is not simply equivalent to `PSU_CONTROL` when using one of the MKS boards with the MKS_PWC add-on.

The original proposal seemed to imply that the only way you would be able to use `PSU_CONTROL` with one of these boards is with the add-on, so I took the leap to avoid adding a new top-level option.

So, is it in fact unavoidable that we must make "`MKS_PWC`" a main configuration option?

**Comment by thinkyhead** [comment]
Please examine the PR #22557 which is based on the state of this PR before I attempted to make `MKS_PWC` equivalent to `PSU_CONTROL`. The first commit in that PR reverts MKS pins files to that point in time, with some cleanup to remove some redundant elements. The other commits are fixing up the KILL and filament sensor pins. Some of the pins files, —particularly Monster 8— still have some confusion, with various potentials for pin overlaps.

**Comment by Rockman18** [comment]
In my mind, PSU_CRONTROL was for Marlin UI and MKS_PWC for LVGL UI. If only one define can be shared it will be easier.
I thought they have create the 2 defines because PSU_CONTROL could mess up LVGL UI but I don't know...

**Comment by Rockman18** [comment]
> Please examine the PR #22557 which is based on the state of this PR before I attempted to make `MKS_PWC` equivalent to `PSU_CONTROL`. The first commit in that PR reverts MKS pins files to that point in time, with some cleanup to remove some redundant elements. The other commits are fixing up the KILL and filament sensor pins. Some of the pins files, —particularly Monster 8— still have some confusion, with various potentials for pin overlaps.

Ok I will have a look

**Pull request merged**
