### PR TITLE
Rigidbot V2 support - has MCP4728 digipot

### PR DESCRIPTION
**Pull request by edwilliams16**
This is to support the Version 2 of the Rigidbot motherboard.  It has the same pin-out but has stepper digipots controlled by an MCP4728 DAC.  Added new board type and updated the DAC coding to the current Wire library: Wire.receive() -> Wire.read  Wire.send() -> Wire.write()
  Major contributor was Jayson Kelly, who made the first cut at the coding.

### CODE REVIEW

**Comment by edwilliams16** [comment]
I got in a big mess trying to squash these commits together, so I went with this...

**Comment by thinkyhead** [comment]
Having trouble squashing commits? It should be very simple using `git rebase -i` from the command-line. Where is your confusion?

**Comment by edwilliams16** [comment]
I think things went awry when I rebased before pulling down the latest commits from RCBugFix.  I ended up stashing my changes, starting a new branch on the latest bugfix, and committing my changes to it - but I still ended up with this tangled history, when I thought I'd get a clean slate.  
   I feel like I'm learning to drive in a race car  with no brakes!  I'll study up on rebase.

   I just took a look at your git scripts - but I'm a little reluctant to run them without knowing precisely what they do.

  How about this workflow:
https://gist.github.com/nicholashagen/2855167

**Comment by thinkyhead** [comment]
Did you already do this? http://learngitbranching.js.org/
Then read this: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by thinkyhead** [comment]
So with #4159 it was easier to just take a diff and re-make the PR.

``` sh
git checkout RCBugFix -b rc_rigidbot_diff
git diff RCBugFix edwilliams16/RB2 | git apply
```

Also needed to make some additions and changes.

**Pull request closed without merging**
