### PR TITLE
[2.0] Fix readme link

### PR DESCRIPTION
**Pull request by GMagician**
This version of readme is present only in 2.0 so can't fix using 2.0.bugfix as base

### CODE REVIEW

**Comment by thinkyhead** [comment]
You'll have to start with 2.0.x (as it currently exists) otherwise I can't see the changes.

**Comment by GMagician** [comment]
@thinkyhead not sure what you mean with "start with 2.0.x". This PR start from MarlinFirmware:2.0.x branch...isn't the same thing?

**Comment by thinkyhead** [comment]
Start with this:
```
git checkout 2.0.x
git fetch upstream
git reset --hard upstream/2.0.x
```
Then when you apply your changes it will be easy to see them.

**Comment by GMagician** [comment]
Ok, I'm almost sure I did a refresh just before posting my PR and PR started from 2.0.x....

**Comment by GMagician** [comment]
only change was to address dev.2.1 instead of dev.2.0 for new PRs

Edit:

> Submit New Features to the (dev-2.0.x) branch.

**Comment by thisiskeithb** [comment]
@thinkyhead The readmes between `bugfix-2.0.x` and `2.0.x` don't match, so where do we make the change?

The readme in [`2.0.x`](https://github.com/MarlinFirmware/Marlin/blob/4c261313eec206280e1c1163563e9fe62a89ea96/README.md) has a link to "Submit New Features to the ([dev-2.0.x](https://github.com/MarlinFirmware/Marlin/tree/dev-2.0.x)) branch", but that branch doesn't exist:
https://github.com/MarlinFirmware/Marlin/blob/4c261313eec206280e1c1163563e9fe62a89ea96/README.md#L42-L47

The readme in [`bugfix-2.0.x`](https://github.com/MarlinFirmware/Marlin/blob/f64649933f3a2195df7a2bd3ec95ab6ed3885975/README.md) doesn't have that section of text, so there's nothing to fix/change there:
https://github.com/MarlinFirmware/Marlin/blob/f64649933f3a2195df7a2bd3ec95ab6ed3885975/README.md#L54-L60

Should these be synced back up?

**Pull request closed without merging**
