### PR TITLE
Insert Debug DRYRUN Repetier Host compatible

### PR DESCRIPTION
**Pull request by MagoKimbra**
For testing all mechanism of the printer widthout temperature.

### CODE REVIEW

**Comment by AnHardt** [comment]
Also a nice one.
But i'd like to see messages sent over the serial line to reside in `language.h` and only there. Everything else will make problems with the hosts sooner or later.

**Comment by clefranc** [comment]
@MagoKimbra Thanks a lot, very usefull for debuggers or printer designers. Was wondering when someone will introduce it to Marlin.

**Comment by eboston** [comment]
In your GCode handlers, like for M190, I would suggest putting the return after the LCD message is posted.  That way LCD messages are still displayed.  I was looking for something like this to test out a new display I have been working on.  Wanted the messages to come through without actually having to run a heater.

**Comment by AnHardt** [comment]
@eboston 
To test a display disconnect the heaters and use dummy sensors 998 and 999.

The display code periodically directly pulls the set values, actual temperatures, all values. Only the status-line is kind of pushed into a buffer. There is no way (in the current code) to set the display without setting the value.

**Comment by MagoKimbra** [comment]
@AnHardt what should I do?

**Comment by AnHardt** [comment]
@MagoKimbra
See my first comment on this. 
Put your messages into `language.h` not `language_xx.h`. They are sent over the USB connection, not the display. At least **I** will not merge this as it is.

**Comment by MagoKimbra** [comment]
Ok, just a question ... In repetier Host keys debugging are located in various languages. It makes sense to press a button where it says Stampa a vuoto (in Italian) and read DryRun ENABLED and not stampa a vuoto abilitata?

**Comment by AnHardt** [comment]
Anyone out there who knows how Repetier-Firmware reacts on a M111 on the serial output? Does this differ with the language setting?

**Comment by clefranc** [comment]
@MagoKimbra In planner.cpp, shouldn't it be

```
if (degHotend(extruder) < extrude_min_temp && ((marlin_debug_flags & DEBUG_DRYRUN) !=0)) {
```

**Comment by clefranc** [comment]
@MagoKimbra I also get an unlimited serial console:

```
echo: cold extrusion prevented
```

**Comment by MagoKimbra** [comment]
@AnHardt I use this function for more than a year without any problems, repetier does not expect an answer if not ok ...

@clefranc That line is wrong not as I put it ...
This is exact:
if (degHotend(extruder) < extrude_min_temp && !(marlin_debug_flags & DEBUG_DRYRUN)) {

**Comment by MagoKimbra** [comment]
@AnHardt However if you want to move the answer in English in the file language.h and delete it from .en and .it, for me is not a problem. I think the important is the function.

**Comment by AnHardt** [comment]
@MagoKimbra 
I'd feel better than.

**Comment by thinkyhead** [comment]
I'm so happy to see `M111` is getting used. Are there other debug flags that are already defined for hosts or other firmware that we should be supporting?

**Pull request merged**
