### PR TITLE
[2.0.x] MKS Sbase Delta sample config

### PR DESCRIPTION
**Pull request by DavidBates**
Merged existing delta/generic and mks/sbase configs for users with Delta running MKS Sbase boards.

### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Merged the config examples in delta/generic and mks/sbase to create a sample config for users like me with delta printers using MKS Sbase. I stayed away from putting my own printers config in and keeping it inline with the current generic delta config. 

### Benefits

Enabling delta printer owners running MKS Sbase boards a shorter time to adopting Marlin

### CODE REVIEW

**Comment by thinkyhead** [comment]
If you do a simple `README.md` it can have basic formatting and looks pretty on the Github page when you open the containing folder.

**Comment by thinkyhead** [comment]
That said, I'm not entirely sure we want to merge this. We would prefer to associate configs with specific brand and models, not to include every possible combination of board and printer type.

**Comment by DavidBates** [comment]
Thanks for your consideration. I can definitely add a readme but wanted to keep it as close to the current mks mbase structure as possible. 

As far as your acceptance question this was based on the generic delta config that already exists which many use as a base for machines that don’t exist in the config and/or custom machines. If need be I can supply my config for the blue eagle labs all metal delta when tuned but it will contain specifics to my build I thought this would be preferred as a base over a specific model.

**Comment by DavidBates** [comment]
@thinkyhead I've added the readme as suggested with a picture of the board.

**Comment by thinkyhead** [comment]
> this was based on the generic delta config that already exists

The generic delta config exists for legacy reasons, harking back to the days when people actually built deltas from scratch. The example configurations have never been about boards, but have been expanding to support specific printer models and brands that otherwise would be stuck on old versions of Marlin supplied by the vendor.

The generic Delta and Kossel configs are intended to be board-agnostic, so you could throw in a RAMPS or a Brainwave without any other changes, and going forward we'd prefer to keep the number of generic examples down to a minimum.

If the "Blue Eagle Labs All Metal Delta" is an established model that's gaining wide adoption, it would definitely be preferable to associate the configuration with that —even if it contains your specific tunings— and place it the folder `examples/delta/Blue_Eagle_Labs`.

**Comment by Driley142** [comment]
Hiya @thinkyhead,
Re: "The generic delta config exists for legacy reasons, harking back to the days when people actually built deltas from scratch. The example configurations have never been about boards, but have been expanding to support specific printer models and brands that otherwise would be stuck on old versions of Marlin supplied by the vendor.

The generic Delta and Kossel configs are intended to be board-agnostic, so you could throw in a RAMPS or a Brainwave without any other changes, and going forward we'd prefer to keep the number of generic examples down to a minimum."

I don't get that. BTW, I only build deltas ... from scratch. Shouldn't the config files be as GENERIC as possible???? It always perplexed me that the old (ver. 010100) configuration.h offered a list of 22 specific motherboards, 14 temperature sensors etc. Now it's even worse.

I had trimmed my old config file down to about 516 lines. The 1.1.9 generic Delta configuration.h is 2044 lines, more or less. The config file has to call up the different boards and DACs and Digipots and languages files anyway, so why does everyone and their grandmothers get to have their probes and displays and controllers explicitly defined inside configuration .h ?  

Shouldn't the sections for defining those things just say "goto probelist(extruderlist, sensorlist, etc.).txt and select your probe(extruder, sensor, etc.) type and insert it's code here"? It would sure make configuration.h easier to navigate when searching for pesky stuff like speeds and offsets and things we might actually need to change.

Anyway, it was just a dumb Idea I had. Marlin is totally awesome and I thank you and all who have made it possible for me to make and use 3d printers.

**Comment by thinkyhead** [comment]
@Driley142  — Thanks for the feedback. We've considered splitting up the configurations into several files in the past, but so far no comprehensive attempt has been made. If you have a bee in your bonnet to try your hand at improving the configuration system then please give it a shot and submit a PR. If you can come up with something neater and more maintainable, that would be great! But there are certain advantages to the current two-files configuration system that we have found hard to sacrifice, such as being able to compare one configuration to another and keep them all up to date as features are added, moved, or enhanced.

**Comment by tcm0116** [comment]
While it's a bit tedious to have the printer-specific configuration files contain all of the possible options, it makes things a lot easier when upgrading Marlin to newer versions. Removing all of the unused configuration options leads to diffs with tons of differences that are time consuming to resolve. 

I actually think we should eliminate the generic delta configuration and merge the changes into the basic example configuration. There are a few of the differences that can be automatically handled in the Conditionals_post.h.

**Pull request merged**
