### PR TITLE
Simplify PROBING_STEPPERS_OFF code by implying PROBING_ESTEPPERS_OFF

### LINKED ISSUE #21854: [BUG] probe.cpp fails to compile with `DELTA`, a probe with quiet probing and `PROBING_STEPPERS_OFF`
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Since March 2nd commit (https://github.com/MarlinFirmware/Marlin/commit/35791c6371dad924f9a3f0fb3aebacfd298ecc35#diff-844640fa2c3026003779111f0d4594b9370678140e782a408409d57a9c1dc809), platformio build with `DELTA`, a bed probe that results in `HAS_QUIET_PROBING` and with `PROBING_STEPPERS_OFF` defined fails thus:
```
Marlin/src/module/probe.cpp: In static member function 'static void Probe::set_probing_paused(bool)':
Compiling .pio/build/mega2560/lib1ed/U8glib-HAL/clib/u8g_dev_flipdisc_2x7.c.o
Marlin/src/module/probe.cpp:265:24: error: 'old_trusted' was not declared in this scope
         axis_trusted = old_trusted;
                        ^~~~~~~~~~~
Marlin/src/module/probe.cpp:265:24: note: suggested alternative: 'axis_trusted'
         axis_trusted = old_trusted;
                        ^~~~~~~~~~~
                        axis_trusted
Compiling .pio/build/mega2560/lib1ed/U8glib-HAL/clib/u8g_dev_gprof.c.o
Compiling .pio/build/mega2560/lib1ed/U8glib-HAL/clib/u8g_dev_ht1632.c.o
*** [.pio/build/mega2560/src/src/module/probe.cpp.o] Error 1
```
scrutiny of the source code shows that if `DELTA` is defined, then `old_trusted` is not declared, but is still referenced.

```
#if HAS_QUIET_PROBING

  #ifndef DELAY_BEFORE_PROBING
    #define DELAY_BEFORE_PROBING 25
  #endif

  void Probe::set_probing_paused(const bool dopause) {
    TERN_(PROBING_HEATERS_OFF, thermalManager.pause(dopause));
    TERN_(PROBING_FANS_OFF, thermalManager.set_fans_paused(dopause));
    #if ENABLED(PROBING_STEPPERS_OFF)   
      IF_DISABLED(DELTA, static uint8_t old_trusted);
      if (dopause) {
        #if DISABLED(DELTA)
          old_trusted = axis_trusted;
          DISABLE_AXIS_X();
          DISABLE_AXIS_Y();
        #endif
        disable_e_steppers();
      }
      else {
        #if DISABLED(DELTA)
          if (TEST(old_trusted, X_AXIS)) ENABLE_AXIS_X();
          if (TEST(old_trusted, Y_AXIS)) ENABLE_AXIS_Y();
        #endif
        axis_trusted = old_trusted;
      }
    #endif
    if (dopause) safe_delay(_MAX(DELAY_BEFORE_PROBING, 25));
  }

#endif // HAS_QUIET_PROBING
```
I would propose a patch, but I have not a clue what would fix this safely. I can hear my hotend crashing into my print bed even thinking about it.

### Bug Timeline

March 2nd 2021 https://github.com/MarlinFirmware/Marlin/commit/35791c6371dad924f9a3f0fb3aebacfd298ecc35#diff-844640fa2c3026003779111f0d4594b9370678140e782a408409d57a9c1dc809

### Expected behavior

I expect Marlin to compile.

### Actual behavior

```
Marlin/src/module/probe.cpp: In static member function 'static void Probe::set_probing_paused(bool)':
Compiling .pio/build/mega2560/lib1ed/U8glib-HAL/clib/u8g_dev_flipdisc_2x7.c.o
Marlin/src/module/probe.cpp:265:24: error: 'old_trusted' was not declared in this scope
         axis_trusted = old_trusted;
                        ^~~~~~~~~~~
Marlin/src/module/probe.cpp:265:24: note: suggested alternative: 'axis_trusted'
         axis_trusted = old_trusted;
                        ^~~~~~~~~~~
                        axis_trusted
Compiling .pio/build/mega2560/lib1ed/U8glib-HAL/clib/u8g_dev_gprof.c.o
Compiling .pio/build/mega2560/lib1ed/U8glib-HAL/clib/u8g_dev_ht1632.c.o
*** [.pio/build/mega2560/src/src/module/probe.cpp.o] Error 1
```

### Steps to Reproduce

- Download and install PlatformIO as per instructions
- clone the 2.0.x source code
- set up a delta based configuration that includes the following defines:
```
#define DELTA
#define FIX_MOUNTED_PROBE
#define PROBING_STEPPERS_OFF
```
- attempt compile

### Version of Marlin Firmware

2.0.8

### Printer model

Velleman Vertex Delta K8800

### Electronics

Stock

### Add-ons

None

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/6447541/Configuration.zip)

### PR DESCRIPTION
**Pull request by sjasonsmith**
### Description

PROBING_STEPPERS_OFF caused delta builds to fail to compile.

This change alters the Conditionals_post logic to ensure PROBING_ESTEPPERS_OFF is implied by PROBING_STEPPERS_OFF, rather than prohibiting that they be used at the same time. This allows the actual code to disable motors to have far fewer conditionals based on whether or not the printer is a DELTA.

### Requirements

See description in bug #21854 

### Benefits

Allows PROBING_ESTEPPERS_OFF on Delta, even though it is really going to be functionally equivalent to PROBING_ESTEPPERS_OFF.

### Configurations

These are the configs from the related bug, more or less brought up to date.
[Bug21854_Configs.zip](https://github.com/MarlinFirmware/Marlin/files/6996616/Bug21854_Configs.zip)

### Related Issues

#21854

### CODE REVIEW

**Comment by sjasonsmith** [comment]
I have not actually tested these changes, I've only verify that they compile. They are pretty simple and look correct to me, but it is possible I've made mistakes.

**Comment by tpruvot** [comment]
here is what i did when i figured i could fix my problem just moving the  X motor wires out of my cable "tube" https://github.com/tpruvot/Marlin/commit/3a5e9efd82e26cd9fe2404758849335671c5e7e3 its basically on each deploy command and one stow... but with X can make problem on the right end of the axis... ptfe and/or cables can move a bit the head back to the left..

**Comment by sjasonsmith** [comment]
@tpruvot did you reply to the wrong PR? I don't understand how your your post is related to this change.

**Comment by sjasonsmith** [comment]
I guess it is somewhat related. I don't really care about BLTOUCH specific or different ways to solve the problem. I'm just solving a compilation bug that was reported.

**Comment by tpruvot** [comment]
yes, was just to point where i placed the "steppers off"... indeed no problems to turn off Extruder ones, should even be made by default imo ;) but other ones are mandatory on a delta... i guess

**Comment by sjasonsmith** [comment]
> indeed no problems to turn off Extruder ones

I didn't actually change the behavior, only simplified the code.

Previously it had separate implementations for PROBING_STEPPERS_OFF and PROBING_ESTEPPERS_OFF. This required the options to be mutually exclusive.

By changing it so that PROBING_STEPPERS_OFF **requires** PROBING_ESTEPPERS_OFF, I was able to turn it into one code path with much less #ifdef indirection.

**Comment by tpruvot** [comment]
yep, in the bug report, he want to set PROBING_STEPPERS_OFF on a DELTA ? is that logic ? the head will move doing that no ?

**Comment by sjasonsmith** [comment]
> yep, in the bug report, he want to set PROBING_STEPPERS_OFF on a DELTA ? is that logic ? the head will move doing that no ?

That was my initial thought, but it is defined as only disabling motors which are not needed to maintain position. For a Delta user PROBING_STEPPERS_OFF and PROBING_ESTEPPERS_OFF are currently the same.

**Comment by tpruvot** [comment]
oh ok, nice to know, sorry for the noise

**Comment by sgparry** [comment]
I am the issue OP.
The problem was really simple - the variable declarations, assignment and #defines in `Marlin/src/module/probe.cpp` did not align, causing a compilation failure - it seems a lot more sensible just to move the variable assignment and treat the STEPPERS v ESTEPPERS as a separate issue:
```diff
diff --git a/Marlin/src/module/probe.cpp b/Marlin/src/module/probe.cpp
index 2b3a189884..879211c58f 100644
--- a/Marlin/src/module/probe.cpp
+++ b/Marlin/src/module/probe.cpp
@@ -259,8 +259,8 @@ xyz_pos_t Probe::offset; // Initialized by settings.load()
         #if DISABLED(DELTA)
           if (TEST(old_trusted, X_AXIS)) ENABLE_AXIS_X();
           if (TEST(old_trusted, Y_AXIS)) ENABLE_AXIS_Y();
+          axis_trusted = old_trusted;
         #endif
-        axis_trusted = old_trusted;
       }
     #endif
     if (dopause) safe_delay(_MAX(DELAY_BEFORE_PROBING, 25));
```
I cannot comment on the correctness of the combination of flags for a Delta - they were derived from the 1.0.4 official source code for my printer - a Vertex K8800. They *appear* to be working as is with the above patch, as much as my printer ever appears to work.

**Comment by sjasonsmith** [comment]
@sgparry your suggestion changes fewer lines of code, but I think my solution leaves the solution cleaner. Fewer blocks of conditionally compiled code usually makes things easier to understand and test.

**Pull request merged**
