### PR TITLE
Support for 'BTN_ENC_EN' pin in emulated DOGM

### PR DESCRIPTION
**Pull request by guruathwal**
### Description
On Smart TFT controller with dual modes (like BigTreeTech TFT35 V3), the encoder pins are hard-wired to the EXP ports. This results in unexpected changes on the printer when the encoder is used on these controllers in modes other than ST7920 emulators.
This PR adds an option to check for encoder active signal on pin `LCD_PINS_D7` on `EXP1` when ST7920 emulator is active on these controllers.

### Benefits
Prevent unintended/unexpected changes on the printer while the encoder is used on the controllers in any mode other than ST7920 emulator by enabling `CHECK_ENCODER_ACTIVE_SIGNAL` in Configuration_adv.h.

*Tested on BOARD_BTT_SKR_V1_4 with BigTreeTech TFT70 V3 controller*

### CODE REVIEW

**Comment by thinkyhead** [comment]
- Which board / controller combinations will use the `LCD_PINS_D7` pin this way?
- Do we expect any board / controller combinations to use a pin other than `LCD_PINS_D7`?
- Can we pre-define the `BTN_ENC_EN` value in some of the pins files (when it is not `LCD_PINS_D7`)?

Rather than add another exposed configuration option, this could be modified so that if you have one of the known board / controller combinations we simply define `BTN_ENC_EN` in the pins file. Then, instead of looking for `CHECK_ENCODER_ACTIVE_SIGNAL` to be enabled, we would just look for the existence of `BTN_ENC_EN`.

**Comment by guruathwal** [comment]
> * Which board / controller combinations will use the `LCD_PINS_D7` pin this way?
> * Do we expect any board / controller combinations to use a pin other than `LCD_PINS_D7`?
> * Can we pre-define the `BTN_ENC_EN` value in some of the pins files (when it is not `LCD_PINS_D7`)?
>
> Rather than add another exposed configuration option, this could be modified so that if you have one of the known board / controller combinations we simply define `BTN_ENC_EN` in the pins file. Then, instead of looking for `CHECK_ENCODER_ACTIVE_SIGNAL` to be enabled, we would just look for the existence of `BTN_ENC_EN`.

I agree with this suggestion. The requirements for this option are:
- The controller emulates `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` with SPI based displays and uses EXP ports to connect with the main board.
- Boards which have both EXP1 and EXP2 ports to allow connecting the above mentioned controller. The `LCD_PINS_D7` is defined on these board but not used when the SPI Graphic LCD is used.

Checking for `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` along with `LCD_PINS_D7` can be use to enable the option.
To remove the need for a configuration option the logic also needs to be inverted to disable encoder when `LCD_PINS_D7` reads to *low* instead of *high* because the controller mimics the `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and this will leave the encoder disabled because the respective PIN on the original controller is not connected.

**Comment by thinkyhead** [comment]
I'm not quite fully awake yet, just getting into issues and PRs. Would you be able to modify one of the relevant pins files to check the conditions you've itemized and have it `#define BTN_ENC_EN LCD_PINS_D7` directly in the pins file, to give an example? I would dive into this myself now, but I've got to skim other issues and catch up on PRs for a couple of hours. If you're also pressed for time, no worries. I have a general sense of which conditions to check for and I'll explore the problem in more detail after a round of janitorial duties.

**Comment by guruathwal** [comment]
I updated the changes as discussed. 
The `BTN_ENC_EN` is defined in **pins_BTT_SKR_V1_4.h** if `U8GLIB_ST7920` is enabled.
Changed the pin read logic to make sure the encoder is enabled if the pin is not connected.

**Comment by guruathwal** [comment]
`TFT_SCALED_DOGLCD` is not enabled when `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` is selected.

**Comment by guruathwal** [comment]
`BTN_ENC_EN` did not work with `TFT_SCALED_DOGLCD`.
worked with `DOGLCD` , `U8GLIB_ST7920` or `IS_RRD_SC`

**Comment by thinkyhead** [comment]
If you could take a peek at `Conditionals_LCD.h` and figure out which of the LCD flags represents the fact that there is a dual-mode display, that would be good. The changes have come so rapidly lately, and there is such a wide array of new weird display options, that truly I cannot figure out which flags apply to which things anymore.

**Comment by guruathwal** [comment]
There is no flag which states a dual-mode display. I don't think that at any point the marlin firmware knows that a dual-mode controller is connected because only one controller/display type can be enabled at a time.
To make sure we are on the same page this PR is regarding the dual-mode controller like BTT TFT35 V3 and TFT70 V3 which emulates ST7920 and not the newer EXTUI based controller used on BIQU BX. The one used in BIQU BX does not suffer from this issue and confirmed by BTT.

**Comment by thinkyhead** [comment]
> I don't think that at any point the marlin firmware knows that a dual-mode controller is connected

I suppose this is could be a fact, since the touch controller is just another device on the serial port. But not all of the serial touch screens are invisible to the firmware. Some of them have unique communication protocols. I'm surprised that we never created specifically-named controller defines for these dual-mode devices, because that might come in handy.

**Comment by thinkyhead** [comment]
How about the existence of a graphical display scaling factor? I'm going to go out on a limb and guess that all displays that scale up the standard graphical interface are dual-mode. But, that is not a guarantee, and there are probably small dual-mode displays that don't scale.

**Comment by thisiskeithb** [comment]
> How about the existence of a graphical display scaling factor?

For standalone BigTreeTech dual-mode TFTs, that's handled in the TFT firmware.

>  I'm going to go out on a limb and guess that all displays that scale up the standard graphical interface are dual-mode. But, that is not a guarantee, and there are probably small dual-mode displays that don't scale.

It's not recommended to scale up the BigTreeTech TFT24 due to performance issues.

**Comment by guruathwal** [comment]
> How about the existence of a graphical display scaling factor? I'm going to go out on a limb and guess that all displays that scale up the standard graphical interface are dual-mode. But, that is not a guarantee, and there are probably small dual-mode displays that don't scale.

It's hard to identify these controllers as they mimic the ST7920 LCD and the communication is one-way on the EXP ports for these SPI displays. I agree with you, the scaling factor will be false positive most of the time as it is for the TFT LCDs which are directly connected to the mainboard, but can be useful if the controller is EXTUI based.

**Comment by thinkyhead** [comment]
Note! If you try to run `M600` (or any other command that requires MarlinUI menus) while in the serial mode, bad things could happen. So, we need to check `BTN_ENC_EN` and provide some feedback that the command is forbidden.

**Comment by guruathwal** [comment]
The encoder is now disabled when the controller is in the serial mode. No change occurs on the native marlin screen unless the mode is changed to emulator mode.

**Comment by NicoletoAerials** [comment]
> REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

When compiling the latest bugfix 2.0.x for the BTT TFT 35 V3.0 along with the SKR mini E3 V2.0, I can only uncomment R10_STOCKDISPLAY and in such case, the option to check for encoder active signal won't work.

REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER must be disabled otherwise it won't let me compile and gives me an error that says "Please select only one LCD controller option."

**Here both REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER and R10_STOCKDISPLAY are uncommented**
Screen1

**Here only REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER is uncommented**
Screen2

**Here only R10_STOCKDISPLAY is uncommented**
screen3

**Comment by radek8** [comment]
Tested on SKR1,4 and TFT32 E3 - works perfectly.
Thank you

**Pull request merged**
