### PR TITLE
Add LED strip UI menu in LVGL

### PR DESCRIPTION
**Pull request by X-Ryl669**
### Description

This simply adds a graphical menu to set the RGB led color for the complete strip or individually for each LED in strip. This is linked with NeoPixel work.

### Requirements

A MKS board with LVGL menu

### Benefits

Typing M150 commands is painful and not visually pleasing. This adds a color hue ring that can be manipulated to select both the hue, the saturation and the luminosity of a color and apply this to one or all led in strip.

You can select the color to apply on the led strip visually:
IMG_20210223_232137_HHT

The interface looks like this:
IMG_20210223_232152

### Configurations

mks_robin_35

### Related Issues

None

### CODE REVIEW

**Comment by X-Ryl669** [comment]
I'm waiting for @MKS-Sean or @mks-viva to merge the LVGL color's picker change in their repository [here](https://github.com/makerbase-mks/LVGL-6.1.1-MKS/pull/1) so I can restore the library location to their repository instead of mine. 
Once it's done, I'll remove the configuration stuff that's blocking the CI and get out of draft mode

**Comment by MKS-Sean** [comment]
@X-Ryl669 Hello, I merged it and tested it to work normally

**Comment by X-Ryl669** [comment]
Thanks! I'll restore the path to your repository and remove the configuration stuff that's breaking the build.

**Comment by X-Ryl669** [comment]
@MKS-Sean Here's the missing icon in the more menu. I don't know what is the process for you to include it in the official assets zip file:
[bmp_rgbstrip.bin.zip](https://github.com/MarlinFirmware/Marlin/files/6054941/bmp_rgbstrip.bin.zip)
The source file for the icon is here:
bmp_speed127

Without this icon, a ugly "No image data" default icon appears in the menu.

**Comment by X-Ryl669** [comment]
@rhapsodyv Do you know if platformio will download again `master.zip` if it's modified in a repository when specified this way in platformio.ini?
```
HAS_TFT_LVGL_UI         = lvgl=https://github.com/makerbase-mks/LVGL-6.1.1-MKS/archive/master.zip
```

**Comment by rhapsodyv** [comment]
> @rhapsodyv Do you know if platformio will download again `master.zip` if it's modified in a repository when specified this way in platformio.ini?
> 
> ```
> 
> HAS_TFT_LVGL_UI         = lvgl=https://github.com/makerbase-mks/LVGL-6.1.1-MKS/archive/master.zip
> 
> ```

No, it won't. You need to delete the lvgl folder on libdeps manually to pio download it again.

**Comment by X-Ryl669** [comment]
Ok, so I'll change it back to a git repository URL then.

**Comment by p3p** [comment]
We are supposed to be avoiding git links in platformio.ini whenever possible as it adds git as a build requirement, which can complicate things for non technical users. Linking to specific release versions (when available) rather than master is also recommended.

I think the platformio team really wants us to use custom libs registered with them for everything (as annoying as it is) as they get a fair few error reports from countries where github is blocked..

**Comment by X-Ryl669** [comment]
@thinkyhead Don't merge it yet, the bmp icon.bin must be included in the MKS's assets, else it's ugly in the menu. I think they (makerbase) will have to make a release of their LVGL port so I can update the link in `platformio.ini` instead of using a git release, as @p3p said.

**Comment by X-Ryl669** [comment]
@MKS-Sean Can you make a release of the LVGL-6.1.1 repository, so I can update the link in platformio to point to the release's zip file, please ?
And the same for this repository: `https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware/` for fetching assets? (or better, create an `LVGL-Assets` repository so I can submit a PR for the new icon) ?

**Comment by Valnar8** [comment]
So it seems that Marlin 2.0.8 has Neopixel functioning now. But when I tried to add your menu, I realised that platformio.ini seems to have changed dramatically since then. The lines to change aren't there anymore. Is there a fix for this? I just added the missing lines but it didn't do job.

**Pull request closed without merging**
