### PR TITLE
Make timer definition in pin files for STM32 possible

### PR DESCRIPTION
**Pull request by hasenbanck**
The board RemRam needs to redefine a particular timer to work correctly.
The STM32 HAL did foresee this possibility and checks if the timer was
already defined for a either the stepper or temperature timer.

Prior to this commit the header file for the timers couldn't see
those definitions in the pin file, but this commit will fix this.

Tested on an actual hardware to verify (it wouldn't boot without it).

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
Could it be that the default in HAL_timers_STM32.h is wrong?

The default for the F4xx on the TEMP_TIMER is pointing to a non-existent timer.

**Comment by Bob-the-Kuhn** [comment]
I took a quick look at the STM32F7xx reference manuals and all seem to have the same set of timers.

Can you provide a high level explanation of what your board needs?  CPU, what timers are acceptable, which function the timer is for, …


---


I don't know what the optimum approach is for this issue.  The STVAL board will need to follow whatever approach is settled on for this PR.

Right now the F4xx default for the TEMP_TIMER is pointing at 7.  That timer exists on the more advanced F4xx parts but not the F401 parts.  Timers 6, 7 & 8 do not exist on the F401 so I'm guessing that timer 9 is acceptable.

**Comment by hasenbanck** [comment]
@Bob-the-Kuhn I don't know what you are talking about. The STM32 HAL already has the functionality to select a custom timer by defining it in the board pin definition file.

Please have a look at the the ```HAL_timers_STM32.h```:
```
  #ifndef STEP_TIMER
    #define STEP_TIMER 5
#endif
```

And the pin file for ```pins_REMRAM_V1.h```
```
//
// Timers
//

#define STEP_TIMER 2
```

The functionality simply wasn't working and I just didn't realized it up until now, since my development boards were at beta testers places and I just received a new batch to develop again.

This PR simply fixes a bug that the ```HAL_timers_STM32.h``` couldn't see custom timer definition in the pin file.

**Comment by Bob-the-Kuhn** [comment]
I'm a newbie to the STM32 world and was wondering if you were fighting the same problem we had with the STEVAL board.  Definitely not the same problem.

I was a bit surprised that you need to use timer 2 rather than 5.  As I read the F7xx reference manuals timers 2-5 on all the chips are gouped together as "general purpose timers" but then I found a reference to using TIM2/3/4 (no mention of 5) along with one of the advanced timers.

Anyhow, not germane to this PR so it's time for me to bow out.  

I'll wait for this PR to complete and then propose STEVAL use the same solution.

**Comment by hasenbanck** [comment]
@Bob-the-Kuhn I was just a bit perplexed that you opened the topic on timer selection, since we foresee the issue of boards needing different timers. In the case of RemRam the board would HALT right after boot, since we use the timer 5 for hardware PWM generation. That why we need to use a different timer. But timer 5 in general seems fine for F7 CPUs. Just not in our specific case.

**Comment by ktand** [comment]
@hasenbanck @thinkyhead @Bob-the-Kuhn 

Hi. This change breaks the use of two serial ports (USB + UART for example) because SanityCheck.h is included before the the `MYSERIAL / NUM_SERIAL` definitions in `STM32\HAL.h`. `SanityCheck.h` is included from `../../inc/MarlinConfig.h` which is included from `HAL_timers_STM32.h` with this change.

One solution would be to include `HAL_timers_STM32.h` **after** the `MYSERIAL` definitions in `HAL.h` but I'm not sure that is the prettiest solution. What do you think?

Do you have any other ideas?

**Comment by thinkyhead** [comment]
> include `HAL_timers_STM32.h` **after** the `MYSERIAL` definitions in `HAL.h`

That's good. It makes sense to have each `HAL.h` include the timers, SPI, and other definitions that would typically come in all-at-once with, e.g., `Arduino.h`.

**Pull request merged**
