### PR TITLE
Fix runout

### LINKED ISSUE #26061: [BUG] Incorrect filament runout motion sensor mm_countdown.runout counting which can produce false filament runout event or delay true runout event
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When using filament runout movement sensor, on printing of small parts, there is a change of false positive filament runout event. While motion sensor is not triggered as filament actually did no move even 1mm in total. As retract movement was not calculated correct, which made Marlin "think" that filament was moved enough already with no sensor reaction.

### Bug Timeline

I installed runout sensor on 2.1.2.1 version, did not check earlier.

### Expected behavior

No matter how many retraction/deretraction events are triggered only on actual forward movement should be triggered filament runout event.

### Actual behavior

Runout event is triggered, while  filament actually is not moved enough mm while printing.

### Steps to Reproduce

1. Download file Straight_Track_100mm.stl
https://www.thingiverse.com/thing:4408535/files
2. Compile Marlin Firmware with filament runout sensor support, filament change support and runout distance 3mm
3. Use SuperSlicer with retraction on wipe, with retract 0.6mm, set "Retract amount before wipe 20%", "Minimal travel after retraction" to 0.1mm, set 0.08 or 0.04 layer height
4. Slice and print model(I suggest skipping to 3.12mm or 4.64  Z height in gcode directly, also you can insert filament in feeder just it have a grip, so no actual filament used in printing, as only move is important)
5. When it start to print bolts on rail, there will be a lot of retraction it will trigger filament change event.

### Version of Marlin Firmware

2.1.2.1

### Printer model

Ender 3

### Electronics

Ender 2 Pro stock board (4.2.3)

### Add-ons

Optical motion sensor (remix of 5710572 thing from thingeverse), BMG clone feeder, short-bowden direct, sensor is connected freely between spool and reverse bouden tube.

### Bed Leveling

No Bed Leveling

### Your Slicer

Other (explain below)

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

My optical motion sensor react accuracy is near 1mm, I set FILAMENT_RUNOUT_DISTANCE_MM=3mm in settting.
Here is the issue. On some models with high number of small details and high retraction value, Marlin calculate some of the retractions and ignore some of them, and this can lead to runout, while 3mm actually was not moved. And as my sensor mostly 1mm accurate, you can assume that not only 3mm is not moved, but even 1mm was not really moved.
I checked runout.h file, to understand what really happens. Tried FILAMENT_RUNOUT_SENSOR_DEBUG const, but output not really informative. Only that mm_countdown.runout starting to decrease very fast while a lot of retractions.
So I checked source. The RunoutResponseDelayed.block_completed function  ignores extruder movements when there is no x,y or z movement. But modern slicers like SuperSlicer can use wipe option, which means, that some of the retraction/deretraction is occured while moving and some without moving.
So I edited source, so I can see which E moves are ignored and which are not.

I will include my config (it is actually a default Ender 2 Pro config files, with minimal changes (like enabling runout sensor). I include config for bugfix release which I tested last.

I include runout.h file, which I changed to get my logs.
I include custom logs, which only include my custom info about which E moves were ignored and which were counted.
I also include gcode files I used to trigger the issue. I insert a tip of filament into BMG gears, and it takes 100mm to come to the nozzle from there, so it is enough to check gcode and not use any filament. So my gcode only use 30 degrees temperature.
retract_test_ps_464_fw.gcode - is prusa slicer 2.6 version, from 4.64 height. It uses FW retraction(I thought that it will help, but no it actually isn't). Corresponding log for it is report_bugfix_fwretract.txt. We see that only retract is counting and deretract is ignored, so on retraction events mm_countdown.runout start to grow, which is wrong, and while it will not trigger false positive, it will trigger false negative. You can just took out filament, and system will ignore that runout motion sensor is not triggered, as mm_countdown.runout is larger and larger. If there are a lot of retractions system will not stop at all, while printing them.

The rest two are SuperSlicer 2.4 gcode files. Those two with slicer retract and wiping. Also I tried firmware retract with no luck.
retract_test_ss_312_wipe_r06.gcode and report_bugfix_runout.txt this is only the end of log file, not from the begining, as Pronterface cut the rest. We see that runout distance become smaller and smaller, because some of retract/deretract movement is ignored, and finally a runout event triggered when mm_countdown.runout become negative.

retract_test_ss_464_wipe_r06.gcode and report_bugfix_overflow.txt in this situation is on the contrary, mm_countdown.runout  starts growing, which is not correct too. Those are part of the same model, just different height.

Actually I tried disable the "if" part in RunoutResponseDelayed.block_completed function:
if (b->steps.x || b->steps.y || b->steps.z || did_pause_print) {
and it really solved the issue. After that all E movement starts to count and no false runout events triggered. Also it is seen in logs, that mm_countdown.runout show correct numbers. So actual runout state when filament is stuck or ended was triggered correctly.

I guess also this workaround should probably include RunoutResponseDelayed.filament_present function modification there should be added the "if" with such condition:
if (mm_countdown.runout[extruder] < runout_distance_mm) {

So mm_countdown.runout will not reset if it is already larger (due to adding retraction movement).

I guess this is needed to prevent resetting on random sensor reaction, for bouden systems with large retraction and short runout distance. Actually runout motion sensor should not trigger on backward movement, but it may because of shaking or for other reason.

I am not sure though if it is appropriate to use this code modification. For some reason there is check for xyz movement.

[config+logs+gcode.zip](https://github.com/MarlinFirmware/Marlin/files/11985245/config%2Blogs%2Bgcode.zip)

### PR DESCRIPTION
**Pull request by GMagician**
May fix #26061

**Needs a seriuous review before testing it**

I decided to limit changes only when runout works with distance because it shouldn't be a problem in other cases

### CODE REVIEW

**Comment by GMagician** [comment]
**Needs a seriuous review**

**Comment by thisiskeithb** [comment]
Converted to draft since the patch doesn’t seem to work: https://github.com/MarlinFirmware/Marlin/issues/26061#issuecomment-1633640069

**Comment by justvlade** [comment]
@GMagician Yes, looks like now it is counting runout mm correctly, at least with retract_test_ps_464_fw.gcode. But for some reason printer is reloading while printing. I checked that its behavior depends on MIN_STEPS_PER_SEGMENT value.
If I set `MIN_STEPS_PER_SEGMENT=1` then it is counting runout mm right, and successfully detects runout and runs M600 command to change filament. But if `MIN_STEPS_PER_SEGMENT=6` (as default for ender 2 pro config), then runout is calculated correctly, but for some reason printer reboots during print. I also changed current bugfix code with `MIN_STEPS_PER_SEGMENT=6` and it completes the print as it cannot detect runout.
I am attaching those logs in zip. I have found a way to get full logs using `tail -f` directly from printer, so those logs are full from start to finish with maximum verbosity.

I have used this branch to test patch https://github.com/GMagician/Marlin/tree/850d848e942682c284cd92174b304ec7b82f220d (as I understand it is current bugfix with patch applied)

log_M1_LOG.txt - MIN_STEPS_PER_SEGMENT=1 with patch
log_M6_LOG.txt - MIN_STEPS_PER_SEGMENT=6 with patch
log_M6_LOG_NOP2.txt - MIN_STEPS_PER_SEGMENT=6 current bugfix

[patch_850d848_logs.zip](https://github.com/MarlinFirmware/Marlin/files/12060412/patch_850d848_logs.zip)

**Comment by GMagician** [comment]
@justvlade I was sure not to reenter the calling block that may generate a loop but maybe I'm wrong. I approached in a different way this issue and if it runs it's a lot cleaner than this (and also more resources saver). May you try it? it's #26082

**Comment by GMagician** [comment]
Replaced by #26082

**Pull request closed without merging**
