### PR TITLE
Creality Ender-5 Configurations

### PR DESCRIPTION
**Pull request by leoheck**
This PR adds the initial configuration for Creality Ender-5 printers.

### CODE REVIEW

**Comment by thisiskeithb** [comment]
`1.1.x` is only receiving critical patches and the Ender-5 is already supported in `bugfix-2.0.x`. [Link to configs](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/config/examples/Creality/Ender-5)

**Comment by boelle** [comment]
yep @leoheck you should not use 1.1.x, go to 2.0.x

**Comment by leoheck** [comment]
Oh, good guys, thank you. Do you believe this version bugfix-2.0.x is to go? If so I will flash it.

**Comment by boelle** [comment]
yes, always use 2.0.x :-D

**Comment by leoheck** [comment]
I will close, this. @boelle , where I can find the differences between version 1.1.* and version 2.0.*?

**Comment by boelle** [comment]
you can use a tool like winmerge to find whats is different

**Comment by leoheck** [comment]
Ok thanks.

I was trying to build Marlin 2.0 but I don't know the right way to do that.

With 1.1.x I was setting the Sanguino as the board on the Arduino IDE. 
Now, the 2.0.x instructions say to user Arduino Mega board, is that the same thing?
I am trying to build it for Ender-5.

**Comment by boelle** [comment]
you can also use vscode+platform.io to do the build
google is also a great help

or one of these places:

RepRap.org [Marlin Forum](http://forums.reprap.org/list.php?415)
[Tom's 3D Forums](https://discuss.toms3d.org/)
Facebook Group ["Marlin Firmware"](https://www.facebook.com/groups/1049718498464482/)
Facebook Group ["Marlin Firmware for 3D Printers"](https://www.facebook.com/groups/3Dtechtalk/)
[Marlin Configuration](https://www.youtube.com/results?search_query=marlin+configuration) on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
After seeking help from the community, if the consensus points to to a bug in Marlin, then you should post a [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose).

**Pull request closed without merging**
