### PR TITLE
[2.0.x] Add TMC2130 sensorless probing

### PR DESCRIPTION
**Pull request by tcm0116**
This PR adds the ability to use the stall guard feature of the TMC2130 to enable using the nozzle as a bed probe. I've tested it on my delta machine, and it seems to work pretty well (as can be seen in https://www.youtube.com/watch?v=xb8dM9duGOs). Mileage will vary with cartesian machines that use lead screws or threaded rods, but I think it's definitely viable on delta machines.

For reference, on my machine, I'm using the traditional max endstops and I have the TMC2130 DIAG1 outputs connected to the min endstops. It should be possible to use both `SENSORLESS_HOMING` and `SENSORLESS_PROBING` at the same time, but the DIAG1 outputs of the TMC2130s would need to be connected to both max and min endstops in parallel (or the pins file modified to use the same pins for both).

### CODE REVIEW

**Comment by teemuatlut** [comment]
I still think this should be Delta only.
Too many steps per mm to be accurate and enough torque to bend the bed or damage the nozzle.

**Comment by tcm0116** [comment]
That's why I put the following caution in the description of the `SENSORLESS_PROBING` feature.

```
CAUTION: This could cause damage to machines that use a lead screw or threaded rod
         to move the Z axis. Extreme care must be taken when attempting to enable
         this feature.
```

**Comment by teemuatlut** [comment]
I think I'd rather see `#if ENABLED(DELTA)` and then remove it if someone can show it working safely on a lead screw driven system.

**Comment by thinkyhead** [comment]
With the addition of these sensitive features, maybe it would be good to have a separate sketch that does testing on the stepper drivers to figure out the proper value limits and ranges —especially for stall sensitivity— so users can be pretty confident about them before plugging them into Marlin and leaping straight to `G29`.

Or… have a `marlin_calibrated` flag that is `false` by default, and only gets set `true` after the machine has been put through an initial setup and testing procedure. Until that flag is set (requiring an EEPROM) the firmware will always boot into the setup procedure.

**Comment by tcm0116** [comment]
For this, I just used `G30` and `M914` to dial in the stall sensitivities prior to moving on to `G33` and `G29`.

Also, I believe having a separate sketch isn't currently possible with the LPC1768 HAL. 

A calibration procedure would be nice, but isn't always necessary. As I've dialed in the parameters like Z offset and stall sensitivity, I've updated my configuration files, which ensures that the system is safe to operate when updating to newer versions of Marlin.

**Comment by thinkyhead** [comment]
Holding this until after the 1.1.9 release, which could be pretty soon. Still a few bugs to look into.

**Comment by tcm0116** [comment]
I'm not aware of any bugs. Just concerns that this might not be as usable
on some machines as others.

**Comment by thinkyhead** [comment]
I'm referring to bugs generally that I need to look into before releasing 1.1.9. Not bugs in this PR.

**Comment by marcio-ao** [comment]
> I think I'd rather see #if ENABLED(DELTA) and then remove it if someone can show it working safely on a lead screw driven system.

@teemuatlut : We have printers we are working on which use a belted Z axis with direct (non-geared) drive, so the assumption that if it is a Cartesian it has gearing and/or a lead-screw is soon-to-be incorrect. I may give this option a try and see if it works. My concern isn't with damage, but with false positives due to Z binding.

**Comment by marcio-ao** [comment]
Just a heads up that due to #10294, the polarity of DIAG1 will change. Not sure whether this necessitate any corrections to this PR, but since it was related, I thought I would mention it.

**Comment by mylife4aiurr** [comment]
@tcm0116 I saw your video. It's nice to use stallguard to get rid of endstops. It's great to make your printer quieter. But using stallguard as a bed probe is like next level. 
If it's  accurate it would be awesome.
I'd like to try it out and help get it working on another Delta? 
Do I simply bridge xyz diag pins together as one output then connect that to zmin?
Not totally sure what changes need to be made on firmware side, but I'd think the firmware would see signal from any diag pin as a probe hit? So I don't think any firmware changes necessary as far stallguard as probe are necessary? Just the bridging of daig pins? Is that correct?

**Comment by mylife4aiurr** [comment]
Hope this feature gets into 1.1.x as well, please, please.

**Comment by thinkyhead** [comment]
> Hope this feature gets into 1.1.x as well, please, please.

Not a chance. But 2.0.x for AVR has complete parity with 1.1.x, so there's nothing precluding the use of 2.0.x.

**Comment by hpcre** [comment]
I think using the bed nozzle as a probe is fine with printers using lead screws if the bed is mounted on springs. springs will add unsual resistance to the probing mechanism which should be detected by the z-axis motor drivers.
Just need to first add a condition to use manual bed leveling to dial in to a fraction of a mm. that way the automated probing will take this into account and lower the nozzle in baby steps starting from the previously defined manual positions.

**Comment by tcm0116** [comment]
@thinkyhead - now that 1.1.9 is released, can we re-visit this PR?

**Comment by thinkyhead** [comment]
Still some things to be done for completeness, but soon we can merge it and see what kind of feedback we get about it.

**Comment by thinkyhead** [comment]
Current configurations claim that StallGuard is only usable with TMC2130 drivers. But this PR claims it can be used also with TMC2208 drivers. Is the current configuration wrong?

**Comment by tcm0116** [comment]
>Is the current configuration wrong?

No. I was mistaken. I've updated the configuration files and re-based.

**Comment by thinkyhead** [comment]
I've also done a bit of tweaking, rebased, and pushed changes. Did you change anything other than the comments reading `// TMC2130/TMC2208 only`…

…and the sanity checks?

**Comment by thinkyhead** [comment]
Ok, should be good to merge once it passes Travis CI. Previously none of the TMC2130 or 2208 tests were being run, so I want to make sure they're all passing now.

**Comment by tcm0116** [comment]
>…and the sanity checks?

The sanity checks were all correct. It was just the comments that were wrong.

**Comment by thinkyhead** [comment]
This error message is correct? How do we use it with TMC2208?
```cpp
#error "SENSORLESS_PROBING requires TMC2130 or TCM2208 drivers for X, Y, and Z."
```
Also, oops, a little dyslexia fell in with "`TCM2208`."

**Comment by Palatis** [comment]
hello, @tcm0116, can you give a quick explanation on how you wired the pins?
i would like to give this a try but can't figure out the wiring.

**Comment by tcm0116** [comment]
@Palatis - in my setup, I'm using conventional endstops for homing the three towers, which are wired to the X/Y/Z Max inputs on my board. I then have the diag1 output of the TMC2130s wired to the X/Y/Z Min inputs on the board. Marlin is configured with all six of the endstops enabled and `SENSORLESS_PROBING` enabled. `G30` and `M914` can be used to determine the proper sensitivity settings for the TMC2130s. I think I'm running the slow probe speed at 40 mm/s and a stall sensitivity of 4 or 5.

**Pull request merged**
