### PR TITLE
G29 endstop handling

### PR DESCRIPTION
**Pull request by AnHardt**

### CODE REVIEW

**Comment by AnHardt** [comment]
Tuch

**Comment by thinkyhead** [comment]
This looks pretty cool. Is there a newer version of this idea, or is this defunct?

**Comment by AnHardt** [comment]
Double touch for Deltas in run_z_üorobe() is still a good idea.
Minimizing the time the endstops are checked is not. For me they should be always checked, if not explicitly disabled and never before homing. It's only the probe what should be checked only when deployed. (all kinds of probe).
The other good idea here, was to respect/restore the check state, set by M120/M121, in clean_up_after_endstop_move().

The whole PR was not ready. I send it to here by accident and closed it some minutes later.
Feel free to use any code you like. (But don't put in a new macro)

**Comment by thinkyhead** [comment]
> Feel free to use any code you like. (But don't put in a new macro)

Just be glad we're not writing this in Perl!

**Pull request closed without merging**
