### PR TITLE
Reduce PROGMEM warnings

### PR DESCRIPTION
**Pull request by odewdney**
2nd attempt at clearing progmem warnings. - So we can see the other warnings generated more clearly.

### CODE REVIEW

**Comment by daid** [comment]
PROGMEM warning are a bug in a very old gcc, working around this bug is anything but pretty, and we should just upgrade avr-gcc instead of littering Marlin with hacks like this.

prog_uint8_t types and friends are depricated, and no longer supported in latest versions of avr-gcc, and thus should not be used.

**Comment by chertykov** [comment]
I can explain this bug. 
This is not an avr-gcc bug it's avr-g++ bug. (ie it's actual only for C++)
It's because avr-g++ generally unsupportred.

According to [Compilation](https://github.com/MarlinFirmware/Marlin/blob/Development/Documentation/Compilation.md) the right avr-gcc version is 4.3.2 (August, 2008) which is come with arduino 1.0.6 and 1.0.5.

Does anyone have a positive experience with latest Marlin and latest avr-gcc (GCC 4.9.2) ?

**Comment by ErikZalm** [comment]
Do not try to fix the warnings. The pull request will be rejected.
We had a lot of problems with PROGMEM in the past. And it is only a warning.

**Comment by chertykov** [comment]
It is difficult to clean up the code with so many warnings.

**Comment by daid** [comment]
Not getting these warning with:

$ /c/WinAVR/avr/bin/g++ --version
g++.exe (WinAVR 20100110) 4.3.3

And I'm using the latest avr-gcc from Ubuntu to compile all the Ultimaker firmwares without issues.

**Comment by chertykov** [comment]
> Not getting these warning with:
> 
> $ /c/WinAVR/avr/bin/g++ --version
> g++.exe (WinAVR 20100110) 4.3.3

It's very strange because this bug was fixed only in 2011.
[Bug 34734](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=34734)

> And I'm using the latest avr-gcc from Ubuntu to compile all the Ultimaker firmwares without issues.

Please, avr-gcc version. (Or Ubuntu version)
Are you use compiled firmwares for printing ? (May be you use it for compile tests)

**Comment by daid** [comment]
Oh, never mind. Now I remember. I patched the avr-gcc include file:

#ifndef **ATTR_PROGMEM**
//#define **ATTR_PROGMEM** **attribute**((**progmem**))
#define **ATTR_PROGMEM** **attribute**((section(".progmem.data"))) 
#endif

Not a perfect solution, but hides most of the warnings and problems during development for me without making a mess of the sourcecode.

**Comment by chertykov** [comment]
> > And I'm using the latest avr-gcc from Ubuntu to compile all the Ultimaker firmwares without issues.
> 
> Please, avr-gcc version. (Or Ubuntu version)
> Are you use compiled firmwares for printing ? (May be you use it for compile tests)

**Pull request merged**
