### PR TITLE
[2.0.x] Update PlatformIO lib_deps

### PR DESCRIPTION
**Pull request by tcm0116**
Relevant portions of #8452 packaged for 2.0.x

### CODE REVIEW

**Comment by teemuatlut** [comment]
Question to @MarlinFirmware/32bit-maintainers 
Should the LPC HAL include common.libdeps as its' dependencies or is there a reason it's been left this way?

**Comment by tcm0116** [comment]
I thought about adding common.lib_deps to the LPC1768 environment, but I
assumed that since they aren't there currently, no one's tested those
features.

I can go ahead and add them, making sure they at least compile and we can
tackle any issues as they arise.

**Comment by p3p** [comment]
The LPC1768 platform isn't an Arduino platform (as you probably know), most, if not all Arduino libraries would need to be modified to work with the compatibility layer, If a library only uses part of the Arduino API we have implemented and no AVR code it may work though.

**Comment by tcm0116** [comment]
I tried the following in the LPC1868 environment, and they won't compile due to preprocessor checks for `ARDUINO`:

- LiquidCrystal_I2C
- TMC2130Stepper
- Adafruit NeoPixel

I got stuck on TMC26XStepper because the compiler couldn't find its headers file, and then I ran out of time. 

Since Arduino-L6470 won't even compile on 1.1.x due to Marlin trying to pass a parameter to the init function, I didn't even bother trying.

**Comment by thinkyhead** [comment]
I couldn't find the call to L6470 `init(something)` (with a parameter) by global search. Can you point it out?

**Comment by tcm0116** [comment]
https://github.com/MarlinFirmware/Marlin/blob/29730e6e6525330af2b73258efe12b54057ba928/Marlin/src/module/stepper_indirection.cpp#L256

**Comment by tcm0116** [comment]
It looks like my assumption that this issue was in 2.0.x and 1.1.x is incorrect. The following line is from 1.1.x, which passes a parameter to the init function. However, no parameter is passed in 2.0.x. 

https://github.com/MarlinFirmware/Marlin/blob/4f05a66ee155d4733f2fbb69ca761098dde8b77a/Marlin/stepper_indirection.cpp#L294

**Comment by thinkyhead** [comment]
I remember that at some point the `*_K_VAL` was supposed to be sent as part of the initialization. If the `init()` actually takes no parameters, we should figure out what to do with the `*_K_VAL`s.

**Comment by tcm0116** [comment]
That's where I got, and decided that I don't know enough about those
drivers to proceed.

**Pull request merged**
