### PR TITLE
[1.1.x] AnyCubic Linear Plus, Update Trigorilla 1.4

### PR DESCRIPTION
**Pull request by Hecatron**
### Description

  * Added example configurations for the anycubic kossel delta linear plus (with probes)
  * Added a change to pins_TRIGORILLA_13.h so that the fan outputs coincide with the recommended wiring by Anycubic
  * Added example images for both probe types so that the end user can identify which one they have

Note if the changes to pins_TRIGORILLA_13.h are not acceptable then I may need to create a new board header file. I've basically set the fan outputs to how they are normally wired for this type of delta printer
Benefits

### Benefits

  * Makes it easier to get started with the latest marlin and the anycubic kossel delta linear plus
  * Should allow other delta's that use the trigorilla board to avoid any hacks to the pins_TRIGORILLA_13.h

### CODE REVIEW

**Comment by thinkyhead** [comment]
The pins for the Trigorilla boards have been through several iterations and the last time with a lot of feedback from users. So I want to consult those users before merging these changes. Also, can you check to see if the Trigorilla 1.4 pins are closer than the 1.3 ones with your system?

**Comment by Hecatron** [comment]
It looks like the only current difference between trigorilla 1.3 vs 1.4 according to Marlin
is if IS_RAMPS_13 is set or not (via pins_RAMPS_13.h)
which then influences if SERVO0_PIN is set to 7 or 11 within pins_RAMPS.h
I've not tested that but it's not a pin I'm using

I did also come across this thread now that you mentioned it
https://github.com/MarlinFirmware/Marlin/issues/8349

I don't mind using pins_TRIGORILLA_14.h instead if you'd like

for info I've attached an image which matches up against my board
Also the order in which the fans are wired is the one recommended in the Anycubic manual you get with the Kossel Linear Plus model

  * FAN0 / D9 - Part Fan (the connector on the left on the diagram)
  * FAN1 / D7 - unused
  * FAN2 / D44 - Fan for cooling the hotend
  * another image here - https://www.3dhubs.com/talk/thread/anycubic-kossel-wiring

anycubic_i3_mega_trigorilla_board

**Comment by thinkyhead** [comment]
As I understand it the Trigorilla 1.4 has support for up to 2 extruders, while the 1.3 only supports one. Assuming this is correct, if your board has two E stepper plugs, then it's a 1.4 board.

**Comment by Hecatron** [comment]
mine has an E0 and an E1 in that case it must be a 1.4 board
I'll make some changes to the commits so that this is for the 1.4 instead of 1.3 board

**Comment by Hecatron** [comment]
Okay the changes should now be switched across to the trigorrila 1.4 board definition

  * I've tried compiling it and that works fine, although I can't test it at the moment since i've recently moved across to a duet board. That being said it worked fine with the previous version so this should also be fine
  * I've disabled the pins for the E1 stepper even though there is a E1 stepper output, I suspect the default pinouts within pins_RAMPS.h are incorrect for E1 for this board. This is due to at least one of them being pin 44 which is the same one as the extruder fan output

**Comment by thinkyhead** [comment]
Will it confuse your workflow if I modify your `bugfix-1.1.x` branch (the source of this PR) so that it contains `bugfix-2.0.x` plus these changes instead? (Ideally you should make a copy of a branch before modifying it and submitting it as a PR.)

**Comment by Hecatron** [comment]
That would be fine
I dont have any plans to make any other changes so feel free to modify

**Comment by thinkyhead** [comment]
Perhaps @anycubic-3d would like to review this…?

**Pull request merged**
