### PR TITLE
Bedleveling: X and Y must be Integers not Float!

### PR DESCRIPTION
**Pull request by tonnico**
https://github.com/Wurstnase/Marlin/blob/Development/Marlin/Configuration.h#L427

### CODE REVIEW

**Comment by thinkyhead** [comment]
Hmm, wouldn't it be better if they _could_ be floats?

**Comment by tonnico** [comment]
could be... this is only an 'update' for the manual. In the config.h under ABL it's already marked.

**Comment by thinkyhead** [comment]
Oh yeah, so it is! Check.

**Comment by thinkyhead** [comment]
(I guess I can see that accuracy here isn't as important as, say, the distance between extruders. So it's fine as-is.)

**Pull request merged**
