### PR TITLE
Editing a mesh causes a disordered movement of the Z axis towards the bottom stop of the Z tower.

### PR DESCRIPTION
**Pull request by Foxies-CSTL**
### Requirements
On a Delta printer (QQS) when I want to edit mesh by UBL Tools menu, only axis z want to go at the bottom of the Z tower.

### Description
On a Delta when I edit a mesh using the menu.
"Select "Motion/Unified Bed Leveling/Mesh Edit"

Steps to Reproduce:
Last BugFix with PR # 20248 and # 19804 included, I perform the following operations:

 - reset the eeprom = ok
 - launch of an auto-calibration (G33) = ok
 - Launch of a cold mesh by UBL Tools = ok
 - Editing of the mesh via the menu and the two XY axes are positioned towards H - 50mm but the Z axis is positioned towards 0. 
  I stop it before the axis motor locks at the bottom (I have no endstop mini).

### Benefits
To be able to visualize the mesh in order to correct bad level measurements.

### Configurations
[20201122-QQS_Pro-Configs.zip](https://github.com/MarlinFirmware/Marlin/files/5585270/20201122-QQS_Pro-Configs.zip)

### CODE REVIEW

**Comment by sjasonsmith** [comment]
Did you intend to include code to fix this, or did you intend to post it as a new issue? Pull requests are for submitting code changes.

**Comment by Foxies-CSTL** [comment]
I intend to post it as a new issue but i was waiting to include a video of the failure sequence.

**Comment by thisiskeithb** [comment]
> I intend to post it as a new issue

Closing since shouldn't have been a PR.

**Comment by Foxies-CSTL** [comment]
> Closing since shouldn't have been a PR.

Ok...................

**Comment by sjasonsmith** [comment]
@Foxies-CSTL a Pull Request is a way for you to fix code and provide changes back to Marlin. To report a problem you should open an Issue, not a Pull Request.

**Pull request closed without merging**
