### PR TITLE
[WIP] Fix nozzle to probe offset

### LINKED ISSUE #20278: [BUG] Nozzle to probe offset ignored
### Bug Description

Nozzle to probe offset is ignored. Probably on X and Y axis.

### Configuration Files

Not relevant

### Steps to Reproduce

Compile latest 04c4c6004e752582235357b14aebdd5ff579f477 bugfix with bed leveling support.

**Expected behavior:**

Nozzle to probe offset will be correctly applied

**Actual behavior:**

Nozzle to probe offset is ignored.

#### Additional Information
Reverting 296a2ad7e45d88a10db4b3305ea183e5c0c177a5 this commit will fix the issue. [Here is the issue](https://github.com/MarlinFirmware/Marlin/commit/296a2ad7e45d88a10db4b3305ea183e5c0c177a5#r44537759) 

Probe::offset is copied and then referenced instead of just referenced.

### PR DESCRIPTION
**Pull request by daleckystepan**
### Description

Trying to fix issue with ignoring nozzle to probe offset https://github.com/MarlinFirmware/Marlin/issues/20278

I don't know Marlin code base much so I have tried to do my best to fix the issue.  Just removed the reference and rename other variables.

### Benefits

Nozzle to probe offset will work again.

### Configurations

Tested with
https://github.com/daleckystepan/Marlin/blob/geeetech_a10/Marlin/Configuration.h
https://github.com/daleckystepan/Marlin/blob/geeetech_a10/Marlin/Configuration_adv.h

### Related Issues

https://github.com/MarlinFirmware/Marlin/issues/20278

### CODE REVIEW

**Comment by sjasonsmith** [comment]
@daleckystepan thanks for posting this. This is more change than I expected, since you elimianted offset_xy.

Does this work if the _only_ change you make is this?
```
#if HAS_PROBE_XY_OFFSET
  const xy_pos_t &Probe::offset_xy = Probe::offset;
#endif
```

All I did was remove the  `xy_pos_t` from the `xy_pos_t(Probe::offset)`. This should eliminate the copy, and `xyz_pos_t` looks like it should be able to provide the `xy_pos_t` reference needed.

**Comment by swissnorp** [comment]
https://github.com/MarlinFirmware/Marlin/commit/296a2ad7e45d88a10db4b3305ea183e5c0c177a5#commitcomment-44572839

> I am no coder but may it would be worth testing replace
> `const xy_pos_t &Probe::offset_xy = xy_pos_t(Probe::offset);`
> by
> `const xy_pos_t &Probe::offset_xy = xy_pos_t(offset);`

You may could try this and leave to code like it was

**Comment by tpruvot** [comment]
yes @sjasonsmith but double check the ubl grid editor, seems not enough on the left side (with a probe on the left)

but seems ok for the G28 Z

**Comment by sjasonsmith** [comment]
@tpruvot did UBL break in the same commit, or is that just another issue?

**Comment by tpruvot** [comment]
didnt "break", its just not using the xy offsets neither

**Comment by tpruvot** [comment]
ah no, nvm... grid editor is for manual adjustment... not probing

**Comment by tpruvot** [comment]
i think thinkyhead is trying new gcc versions, maybe that show some cast warning... maybe &Probe::offset or such is better

**Comment by sjasonsmith** [comment]
> i think thinkyhead is trying new gcc versions, maybe that show some cast warning... maybe &Probe::offset or such is better

`xyz_pos_t` has explicit conversion operators to return `xy_pos_t` by reference.

```
  FI operator       XYval<T>&()                        { return *(XYval<T>*)this; }
  FI operator const XYval<T>&()                  const { return *(const XYval<T>*)this; }
```

**Comment by sjasonsmith** [comment]
I pushed changes to just fix the assignment to the reference. I've not force-pushed anything, so nothing is lost from @daleckystepan's original change, if we need to go back.

**Comment by sjasonsmith** [comment]
With @tpruvot's confirmation that it seems to work we can put this in as soon as the CI checks pass.

**Comment by tpruvot** [comment]
yep, i never liked this const & = v ... c++ syntax :p

**Comment by qwewer0** [comment]
With the latest changes, the problem is fixed.

**Pull request merged**
