### PR TITLE
Added support for SSD1306 OLED I2C LCDs

### PR DESCRIPTION
**Pull request by fmalpartida**
Added support for SSD1306 OLED I2C based LCDs.
Generic LCD definition.
Included pin definition for SAV MkI.

### CODE REVIEW

**Comment by AnHardt** [comment]
I'm quite sure you wanted to make a PR to Development - not Release.

**Comment by AnHardt** [comment]
Have you tried U8GLIB_SSD1306_128X64_2X?
Should be factor 2 faster - only 4 loops in 
do { ...  } while (u8g.nextPage());
instead of 8.

**Comment by fmalpartida** [comment]
Hi An Hardy,

yes the intention was to PR development... Did you pull the changes to development? 
I'll give 2X a shot and se if it goes better. Thanks for the tip. 

I was trying to use the last version of the 8uglib, but couldn't get it to compile today.

**Comment by Wackerbarth** [comment]
PRs should be based on RECENT versions of the accepted Development branch.

This needs to be rebased before it is considered for merging.

**Comment by AnHardt** [comment]
@fmalpartida 
Hmm, yes could not compile it ether. But that was not a matter of U8GLIB but of lcd_buzz().

The quick fix is:

```
#ifdef U8GLIB_SSD1306
  #undef HAS_LCD_CONTRAST
  #undef HAS_LCD_BUZZ
#endif  
```

For the real fix the conditionals of HAS_LCD_BUZZ have to be checked. I suppose we have to use ULTIPANEL instead of ULTRALCD - something in this direction.

**Pull request closed without merging**
