### PR TITLE
LVGL and Classic UI on STM32

### PR DESCRIPTION
**Pull request by rhapsodyv**
### Description

This PR complete the support for TFT_LVGL_UI and TFTCLASSIC_UI on hal STM32.

### Benefits

STM32 being more complete, we can migrate more boards;
Fixed an issue when our generic `stm32_bootloader.py` didn't update the firmware file when encryption weren't used;
Fixed an issue where classic ui didn't handle TOUCH_ORIENTATION;
Fixed an issue with the ANET ET4 firmware generation for OpenBTL.
Made ANET ET4 works with Classic UI.

### Tests Done

SPI + F1
- [x] LVGL UI on F1 SPI
- [x] CLASSIC UI on F1 SPI
- [x] COLOR UI on F1 SPI

FSMC + F1
- [x] LVGL UI on F1 FSMC
- [x] CLASSIC UI on F1 FSMC
- [x] COLOR UI on F1 FSMC

SPI + F4
- [x] LVGL UI on F4 SPI
- [x] CLASSIC UI on F4 SPI
- [x] COLOR UI on F4 SPI

FSMC + F4
- [x] LVGL UI on F4 FSMC
- [x] CLASSIC UI on F4 FSMC
- [x] COLOR UI on F4 FSMC

### CODE REVIEW

**Comment by rhapsodyv** [comment]
@thisiskeithb can you test this PR on your F4 FSMC (Anet et4)? You can try TFT_CLASSIC_UI and TFT_COLOR_UI.

**Comment by rhapsodyv** [comment]
I tested all boards and combinations I have, and everything is working fine.

**Comment by thisiskeithb** [comment]
> @thisiskeithb can you test this PR on your F4 FSMC (Anet et4)? You can try TFT_CLASSIC_UI and TFT_COLOR_UI.

The current pins file isn’t setup to work with other UI types (there’s no `HAS_TFT_LVGL_UI` like what’s found in the Nano pins file), so I’ll need to figure out what’s needed first.

**Comment by thisiskeithb** [comment]
We found firmware generation bugs with encrypted versions as well as one bug specific to the ET4/P motherboards, but I can confirm that `TFT_CLASSIC_UI` now works on them and `TFT_COLOR_UI` still works.

**Comment by thinkyhead** [comment]
Is there anything that needs to be done to fix the encrypted firmware generation issue?

**Comment by rhapsodyv** [comment]
seems that it's fully working now for @thisiskeithb, so I think everything was fixed

**Comment by thisiskeithb** [comment]
> Is there anything that needs to be done to fix the encrypted firmware generation issue?

Nope. It's in this PR (even if it should have probably been in another one...)

**Pull request merged**
