### PR TITLE
[1.1.x] Allow override of RAMPS CS Pins

### PR DESCRIPTION
**Pull request by floyd871**
I have installed an LCD and the TMC2130 drivers. So some of the default pins are blocked. With this change the pins could be redefined.

### CODE REVIEW

**Comment by psavva** [comment]
What do you mean when you say that the default pins are blocked?
How did you determine this?
If they are re-defined, you should get a warning, no?

@teemuatlut, since this is your baby, have a look :)

**Comment by teemuatlut** [comment]
Well I don't think this PR actually accomplishes anything. The pins typically are _meant_ to be defined in the pins file. If you need to use some other pins, just change the definition.

I may change the default pins in future because we've recently gotten a lot of reports of Y axis especially acting up for users. The pins anyway are a remnant from days past when Marlin first used another library for TMCs.

**Comment by tcm0116** [comment]
I actually like this approach. Having to modify the pins file is kind of annoying, and I'd rather have the ability to just define my custom pin mappings in my configuration file. My preference would be to have every pin definition wrapped in an #ifndef block in all of the pins files.

**Comment by floyd871** [comment]
@psavva: Pin 53 on Aux3 ist blocked by "Reprap Discount Smart LCD with SD-Card Reader". With multiple Definitions i Did't get a IDE Warning.

@teemuatlut: Yes, you're right, my first approach was modifying the pin_File, but all Configuration should be done in Configuration.h or Configuration_adv.h right?? So, this is more Userfriendly.
I've added in Configuration_adv.h :
  #define X_CS_PIN           45
  #define Y_CS_PIN           47
  #define Z_CS_PIN           32
  #define E0_CS_PIN         43
@tcm0116: I would say, only the custom pins (not hardwired on the board) should become a #ifndef block.

**Comment by teemuatlut** [comment]
> but all Configuration should be done in Configuration.h or Configuration_adv.h right??

Nope. The `_pins` files are used for pin definitions and config files for machine settings. There are still some pins defined in adv config but we try to avoid adding them.

**Comment by p3p** [comment]
> There are still some pins defined in adv config but we try to avoid adding them.

Especially now pin format is platform dependant just to mix things up a bit more, and the impossibility of supplying a sane default. Although I agree that in theory any user config should be handled in the config files, In my opinion pin setup should probably stay localised to the platform / board pins file.

**Comment by tcm0116** [comment]
>Although I agree that in theory any user config should be handled in the config files, In my opinion pin setup should probably stay localised to the platform / board pins file.

I think the default pin assignments should be in the pins files, but the user should have the option to override the default pins in a configuration file.

**Comment by p3p** [comment]
I don't have a problem with that in principal, although the mess it will make of all the pins files to make it generic is off putting.

**Comment by tcm0116** [comment]
Totally agree. I was trying to come to with a clean way to do it, but the
preprocessor is too limiting.

**Comment by psavva** [comment]
Given that we have HAL, and different pin formats of the pin definition which is based on the HAL, I don't think you can put this in the config files.  Example, the Re-Arm uses Port_PIN, whereas AVR uses only pin numbers. It's always been the case that if you want to change the pins due to some hardware requirement, you need to modify the pins file.  I don't think that should change.

The issue that this PR was trying to fix didn't actually fix it.  We just need to define the default pins on free pins, ie: ensure they are not used anywhere else.

**Comment by tcm0116** [comment]
>Given that we have HAL, and different pin formats of the pin definition such is based on the HAL, I don't think you can put this on the config files.

Why not? The configuration file is specific to a printer, so if the person configuring Marlin needs to define a different pin for some function for that specific printer, the configuration file seems like a great place. Besides, there are already a few places where that's done, such as the MK2 multiplexer. 

>It's always been the case...

That's the attitude that stifles innovation and stops progress. 

>The issue that this PR was trying to fix didn't actually fix it.

Good point. 

>We just need to define the default pins on free pins, ie: ensure they are not used anywhere else.

And back to my point. What if the default pins we somewhat arbitrarily pick don't work out for someone? It should be easy for the user to change that without having to dig for the pins file.

**Comment by psavva** [comment]
> That's the attitude that stifles innovation and stops progress. 

No attitude and no bad intentions here...
I see your point w.r.t the MK2 multiplexer.  Maybe that's the way to go then...

**Comment by thinkyhead** [comment]
@floyd871 I don't have a problem with this PR in principle. We have tended hold off on putting pin definitions into `#ifdef` blocks until it has become commonplace to override the defaults. If you have the sense that users want to use CS lines other than the ones we recommend, then this is the correct way to to accommodate that trend. We generally don't want to require end-users to modify the pins files for things which may be quite common, but we don't mind leaving the burden in place for less common customizations.

**Comment by floyd871** [comment]
My opinion: The pins_xx file(s) should cover the the most common hardware extensions.
Any additional thing (Mux-Extruder, Filamentsensor, fancy Stepper drivers, etc..) should be reconfigurable without modifying die pins - Files.
This PR is the way to do it and works for me and might be for others too...

**Comment by teemuatlut** [comment]
This is what the TMC2208 section would look like and why I do not welcome this change.
```cpp
#if ENABLED(HAVE_TMC2208)
  /*
   * TMC2208 stepper drivers
   *
   * Hardware serial communication ports.
   * If undefined software serial is used according to the pins below
   */
  //#define X_HARDWARE_SERIAL  Serial1
  //#define X2_HARDWARE_SERIAL Serial1
  //#define Y_HARDWARE_SERIAL  Serial1
  //#define Y2_HARDWARE_SERIAL Serial1
  //#define Z_HARDWARE_SERIAL  Serial3
  //#define Z2_HARDWARE_SERIAL Serial1
  //#define E0_HARDWARE_SERIAL Serial1
  //#define E1_HARDWARE_SERIAL Serial1
  //#define E2_HARDWARE_SERIAL Serial1
  //#define E3_HARDWARE_SERIAL Serial1
  //#define E3_HARDWARE_SERIAL Serial1

  /*
   * Software serial
   */

  #ifndef X_SERIAL_TX_PIN
    #define X_SERIAL_TX_PIN    59
  #endif
  #ifndef X_SERIAL_RX_PIN
    #define X_SERIAL_RX_PIN    63
  #endif
  #ifndef X2_SERIAL_TX_PIN
    #define X2_SERIAL_TX_PIN   -1
  #endif
  #ifndef X2_SERIAL_RX_PIN
    #define X2_SERIAL_RX_PIN   -1
  #endif

  #ifndef Y_SERIAL_TX_PIN
    #define Y_SERIAL_TX_PIN    64
  #endif
  #ifndef Y_SERIAL_RX_PIN
    #define Y_SERIAL_RX_PIN    40
  #endif
  #ifndef Y2_SERIAL_TX_PIN
    #define Y2_SERIAL_TX_PIN   -1
  #endif
  #ifndef Y2_SERIAL_RX_PIN
    #define Y2_SERIAL_RX_PIN   -1
  #endif

  #ifndef Z_SERIAL_TX_PIN
    #define Z_SERIAL_TX_PIN    44
  #endif
  #ifndef Z_SERIAL_RX_PIN
    #define Z_SERIAL_RX_PIN    42
  #endif
  #ifndef Z2_SERIAL_TX_PIN
    #define Z2_SERIAL_TX_PIN   -1
  #endif
  #ifndef Z2_SERIAL_RX_PIN
    #define Z2_SERIAL_RX_PIN   -1
  #endif

  #ifndef E0_SERIAL_TX_PIN
    #define E0_SERIAL_TX_PIN   66
  #endif
  #ifndef E0_SERIAL_RX_PIN
    #define E0_SERIAL_RX_PIN   65
  #endif
  #ifndef E1_SERIAL_TX_PIN
    #define E1_SERIAL_TX_PIN   -1
  #endif
  #ifndef E1_SERIAL_RX_PIN
    #define E1_SERIAL_RX_PIN   -1
  #endif
  #ifndef E2_SERIAL_TX_PIN
    #define E2_SERIAL_TX_PIN   -1
  #endif
  #ifndef E2_SERIAL_RX_PIN
    #define E2_SERIAL_RX_PIN   -1
  #endif
  #ifndef E3_SERIAL_TX_PIN
    #define E3_SERIAL_TX_PIN   -1
  #endif
  #ifndef E3_SERIAL_RX_PIN
    #define E3_SERIAL_RX_PIN   -1
  #endif
  #ifndef E4_SERIAL_TX_PIN
    #define E4_SERIAL_TX_PIN   -1
  #endif
  #ifndef E5_SERIAL_RX_PIN
    #define E5_SERIAL_RX_PIN   -1
  #endif
#endif
```

**Comment by thinkyhead** [comment]
As I stated earlier:

> We generally don't want to require end-users to modify the pins files for things which may be quite common, but we don't mind leaving the burden in place for less common customizations.

You can decide which pins you prefer users edit in the pins files, but remember this adds more burden for upgrading and is not the preferred method. I have no problem with `#ifndef` blocks, the idea being that the pins files should be built to last. If the section won't be getting changed every 2 weeks, then I don't care if it's ugly. We can stick it at the bottom and learn to ignore it.

**Comment by floyd871** [comment]
What about the following change:
Completly remove the pin of the xx_CS_PIN  definition in  pin_RAMPS.h and do it like the FANMUX[012]_PINs or Ex_AUTO_FAN_PIN in Configuration_adv.h and add:
```cpp
#define X_CS_PIN -1
#define Y_CS_PIN -1
#define Z_CS_PIN -1
#define E0_CS_PIN -1
#define E1_CS_PIN -1
```
There comes one question in my mind. Why is the CS_PIN definitions only in pin_RAMPS.h and not in any other pin_xxx ? It is possible to use the TMCs on any other board that has free pins?
On my second Printer (delta) i have a Megatronics 3.0 board. I want to add these drivers there too...

**Comment by psavva** [comment]
There is a solder tab on the TMC2130 which allows it to operate without the SPI Interface, essentially turning them into TMC2100 equivalents...

The pins are used for SPI communications, as long as you can get the SPI interface working, (which includes the CS PIN for each slave device), you should be able to get the drivers up and running...

Otherwise, just solder the tab to get them working in non-SPI Mode, but that would be a real pity...

**Comment by teemuatlut** [comment]
> Why is the CS_PIN definitions only in pin_RAMPS.h and not in any other pin_xxx ?

Because the developers don't have all the boards nor even the knowledge if the drivers can be used on all the boards. RAMPS is the reference platform and you would take example from it if you wanted to add a pin for your board.

**Comment by thinkyhead** [comment]
> Completly remove the pin of the xx_CS_PIN definition in `pins_RAMPS.h` and do it like the `FANMUX[012]_PIN`s or `Ex_AUTO_FAN_PIN` in `Configuration_adv.h` and add:

The pins files are now specifying the _recommended_ pins for each board/feature. We're phasing out cases where the existence of a pin causes a feature to turn on.

**Pull request merged**
