### PR TITLE
Support for TENLOG TFT display

### PR DESCRIPTION
**Pull request by IGHMC-Reg**
### Requirements
CBaugham provided Pins/Config to support the Tenlog Mainboard under #18263 but Marlin does not support the stock screen.
This Pull will add support for the standard screen with the intention of bringing all Tenlog/Hictop TFT screen based printers to Marlin 2 and removing users dependence on the manufacturer for updates.

### CODE REVIEW

**Comment by thinkyhead** [comment]
This cannot be merged without a lot more cleanup and completion.

**Comment by thinkyhead** [comment]
@rhapsodyv — How does this display fit into the current family? The implementation seems out of date with the latest stuff.

**Comment by rhapsodyv** [comment]
> @rhapsodyv — How does this display fit into the current family? The implementation seems out of date with the latest stuff.

The TENLOG TFT uses serial and have its own mcu. It doesn't support any marlin controlled UI.

**Comment by sjasonsmith** [comment]
I am pretty confused by this PR. If this is a serial-connected display why does it need Marlin changes at all?

**Comment by rhapsodyv** [comment]
> I am pretty confused by this PR. If this is a serial-connected display why does it need Marlin changes at all?

Looking at the code, seems it have a custom protocol to talk to screen.

**Comment by IGHMC-Reg** [comment]
Apologies if this is causing confusion, feel free to ignore/close if its not following the correct process. I've asked InsanityAutomation to help me get the code in shape to fit the standards. He tells me that this should be mirroring the DWIN handling so I'm poking it into shape when time allows. The stock screen is a black-box using serial comms, pushing buttons generates proprietary 'gcode ' (eg: M1022) which tl_tft_display.cpp translates to inject sequences of standard gcode. It works for most elements of the screen implementation but breaks some of the current design preferences with the way it hooks into Marlin proper. The mainboard also seems to have foibles around the handling of homing the second extruder which I'm trying to resolve first.

**Comment by sjasonsmith** [comment]
@IGHMC-Reg what is the state of this? You marked it ready for review, but your last comment seems like it might be replaced with a new PR?

**Comment by sjasonsmith** [comment]
Closing this PR. It is very far from a state which could be included into Marlin, and more than a month has passed since my previous question about this PR's progress.

My main concern is that many modifications are made throughout Marlin specifically for this display. They are not confined to a display file. We do not want to change how Marlin behaves for users that do not have these displays.

**Pull request closed without merging**
