### PR TITLE
UBL no longer flouts the sacred GCode standard

### PR DESCRIPTION
**Pull request by Roxy-3D**
And other misc. clean ups and corrections.    For example:  https://github.com/MarlinFirmware/Marlin/issues/6741

### CODE REVIEW

**Comment by Tannoo** [comment]
Removed G29 Z(x) and T?

**Comment by Roxy-3D** [comment]
Yes to the first part...    I'm not sure if the Z offset stuff makes any sense.   We have too many ways to adjust the Z-Height.    Everything from Z_PROBE_OFFSET_FROM_EXTRUDER which turns into zprobe_zoffset.   And that can be adjusted by M851.   And besides that, we have Z-BabyStepping with optional zprobe_zoffset  adjustment.  Etc.  Etc.   

If there really is a need for it, we can uncomment the code and put it back.   But it would be good to simplify things a little bit.

On the T option...   Three Point Leveling is still there.  But it is invoked with a G29 J   or  G29 J0     If the grid size specified in the G29 J command is 0, we are not doing a 'grid'.  We are doing a 3-Point Leveling.

**Comment by Tannoo** [comment]
Ok.. I'll submit a PR to correct the UBL LCD menu.

**Comment by Roxy-3D** [comment]
I apologize...  I forget about your recent LCD code...  Or I would have warmed over those menu items.  When you get the changes done, can you please verify it is still possible to invoke the 3-Point leveling from the LCD Panel?

**Comment by Tannoo** [comment]
ok.

**Comment by Tannoo** [comment]
K.. on to testing it. PR #6748.

**Comment by Tannoo** [comment]
Oh...wait, you also changed the M to O. Let me get that in there.

**Comment by Tannoo** [comment]
Nvrmd, I was seeing things. lol

**Comment by Tannoo** [comment]
Sorry, I'll comment on my PR about this.

**Comment by Tannoo** [comment]
Is there going to be a replacement for it?

**Comment by Tannoo** [comment]
OK.. 3-point works fine. And can still do the grid-based leveling.

**Comment by thinkyhead** [comment]
> the sacred GCode standard

I'm all for being more liberal with parameter letters in some cases. For example, if you need 6 parameters in a row, I think `A`-`F` should be okay to use, as long as `F`eedrate and `E`xtruder number (usually `T` anyway) isn't needed. However, I think for prudence's sake we must currently remain close to the CNC world and avoid using `G`, `M`, and `N` in all cases. In general, when we see letter parameters multiplying to more than ~8 we should consider using a separate M-code, or using a subcode, such as `G29.1`, `G29.2`, etc. While I think some expansion of the Marlin GCode standard is probably warranted, for the 1.1.x release it was specified that we should remain close to the spirit and flavor of previous versions. Version 1.2 is where we will be free to tear things up more.

**Comment by thinkyhead** [comment]
> // Why is M32 allowed to flout the sacred GCode standard?

You'll have to ask Erik Zalm or some other early developer about `M32`. I think the consensus is that it's a hack.

We are rubbing up against CNC world, and there are a lot of requests to support CNC features. Someone has to consider the bigger picture while everyone else is heads-down on their pet features.

All I am doing is guarding against potential conflict areas that will make it harder for Marlin to be taken seriously in a CNC context. The very job I'm on is incorporating CNC features. Diluting the GCode standard further only makes this harder for the actual integration I must do involving Marlin parsing GCode that is more classically CNC-oriented.

**Comment by Roxy-3D** [comment]
> All I am doing is guarding against potential conflict areas that will make it harder for Marlin to be taken seriously in a CNC context. The very job I'm on is incorporating CNC features. Diluting the GCode standard further only makes this harder for the actual integration I must do involving Marlin parsing GCode that is more classically CNC-oriented.

I can actually buy into and consider a perspective like this.   But not only is this an 'Open Source' group...  It is a 'RepRap' group.   RepRap'ers are notorious for being very difficult to lead.   You need to spend the time communicating and winning support for what ever idea is important to you.

**Pull request merged**
