### PR TITLE
update m206 offset immediately

### PR DESCRIPTION
**Pull request by Sunz3r**
bug: have to homing to update m206 offset values

now: offset update immediately

### CODE REVIEW

**Comment by alexborro** [comment]
I don't think this is the expected behavior of M206.. It is a "Homing Offset", I mean, suppose to be added during homing...If you need a more immediate behavior, use G92.

But again, this is only my opinion.. Let's what others say about it.

Cheers.

Alex.

**Comment by Sunz3r** [comment]
my problem is i have to rehoming my z-axis after set z-offset. but i had my endstop on the top of the axis so i had to wait till the axis move to up (257mm at 5mm/s) and move to bottom to check the new offset with my measure tool.

this patched save time and my rods live. i can't see any disadvantage to this?!

Lg

by the way: at my display i have a option to update my offset "lcd_set_home_offsets()". there a way to give M206 a extra argument to update offsets immediately? a have to admit the patch maybe can get in conflict with movement when i update this settings while printer runs (see RepetierHost EEPROM-Settings). what about difference behavior? update offset immediately only when printer idles?

**Comment by daid** [comment]
I think the current behaviour is what you would expect. If you want to change both the offset AND the current position you should use M206 and G92. The G92 behaviour of applying the homing offset is a bug (see other issue about that)

**Comment by Sunz3r** [comment]
as far as i know the G92 should not use offsets. G92 resets all axis to zero therefore M206 with G92 cant solve my problem.
G92 needs to redo after reset oder poweron my printer. M206 solve my problem till my offset needs to re-correct.

okay, i think i need more detailed explain. sry 4 my bad english, i from germany.

when i need to calibrate my printer i do follow things:
1. homing all axis with G28
2. go to calib-position: G0 X100 Y100 Z1
3. measure hight with feller gauge (Fuehlerlehre)
4. calculate difference between 1mm, measured value and old offset in M206
5. update new hight: M206 Zx
6. raise Z-axis by 10mm: G0 Z10
7. again down to measure height: G0 Z1
8. redo step 3. till measured value equals to correct height
9. FIN :D

with this bug i have to start with step 1. this takes much time and kills my threaded rods over time :D

why 1mm height to measure? i prevent scratching hotend on heat bed :D

**Comment by lordofhyphens** [comment]
This change breaks the specified behavior of M206 (as given in http://reprap.org/wiki/G-code#M206:), and thus would be a bug in and of itself. So no, I wouldn't pull this into the main branch.

G92 supports providing different axes to them (http://reprap.org/wiki/G-code#G92:_Set_Position)
So you could run G92 Z-0.1 and the Z axis would be immediately set to -0.1.

So in your workflow, you can add the difference in offset to 10 after hitting G1 Z10, then go down to G0 Z1. Add the difference in offset to your M206 value.

When you finally figure out what offset you're using, you can test it once. 

If you don't agree, well, you have your own branch so you can use it yourself.

**Comment by Sunz3r** [comment]
Thank you, i accept your explain to use G92 which solve my calibration problem and respect the M206 design specification are more important for consistency.

i will close my request and hope i can help more in another issue :)

**Comment by lordofhyphens** [comment]
No problem :)

"Nothing unreal exists." - Kiri-kin-tha's First Law of Metaphysics.

**Pull request closed without merging**
