### PR TITLE
Update Dagoma F5 board configuration

### PR DESCRIPTION
**Pull request by 0r31**
Hi,

This PR updates the Dagoma F5 board pins configuration.
It comes with an update of the related printer configuration in a [PR submitted](https://github.com/MarlinFirmware/Configurations/pull/300) on the **Configurations** repository.

Regards,
Orel

### CODE REVIEW

**Comment by thisiskeithb** [comment]
You'll want to add a sanity check to alert users that the board name has changed.

**Comment by 0r31** [comment]
Hi @thisiskeithb ,

Thanks for the advice , i will do this asap.

Regards,
Orel

**Comment by sjasonsmith** [comment]
I have some general concerns about this and the changes in the corresponding example PR.

The changes are so extreme that it makes me question whether they are even the same printer. I think @InsanityAutomation wrote the original example, so I presume this is one of the printers he has worked with.

**Comment by 0r31** [comment]
Hi @sjasonsmith ,

The original version was a kind of draft with many missing stuff.

I've discussed with @InsanityAutomation on this topic several weeks/months ago. I am not sure he owns this printer. I let him confirm.

I own this printer but I didn't have any time to finalize the work until this week.

I am curious about the extreme changes you point out.

If you speak about DAC steppers for instance, i confirm, the board has a mcp4728 chip.
Another major change is related to the fact that i introduce the second optional extruder (which doesn't have any impact on single extruder configuration).
That's all i see as extreme. All other stuff are small details (adding language choice,...)

Regards,
Orel

**Comment by sjasonsmith** [comment]
By "extreme change" I was referring more to replacing the board, and the changes in the examples. Switching the example to two extruders stands out as a major change for an example.

Users often submit changes that help them while hurting everybody else, and I wanted to be sure that was not the case here.

InsanityAutomation has informed me that you are actually the expert on these printers, so I can step back and let you do your work.

**Comment by 0r31** [comment]
@sjasonsmith ,

I understand your initial concerns. You were right to warn on these changes. Here is few more explanations.

I changed the board filename as it reflects the board name itself:
image

I set the extruders number to 2 and expect no different behavior as it is a single nozzle printer.
On this point, let me double check that tomorrow morning in unplugging second extruder motor and filament runout.

Regards,
Orel

**Comment by 0r31** [comment]
@sjasonsmith : I confirm having the dual extruders configuration file with e1 stepper and filrunout unplugged (so physical config equivalent to single extruder) works flawlessly.

@thinkyhead : Thanks for the improvements, especially the sanity check addition (i planned to do this today, but you are too fast!).

**Pull request merged**
