### PR TITLE
Merge of Skynet3d 2.3.1 (based on Marlin RC8) and Marlin RCBugFix (HW support for Anet A6/A8)

### PR DESCRIPTION
**Pull request by thijsk**
I merged the changes from Skynet 3D (https://github.com/thijsk/Skynet3d) to support the ANET A8 printers into the Marlink RCBugFix branch. Skynet3d doesn't use source control but distributes its source via a zip file.

Code compiles without errors using the Anet A8 configuration.h and I didn't notice anything else really breaking. But obviously needs a review by someone who knows Marlin better then I do.

### CODE REVIEW

**Comment by Roxy-3D** [comment]
You have a problem with the `LCD_CLICKED` macro.   You also (earlier) had a problem with the Sanguino board checks.   I don't know what is causing that.

I have not reviewed your `LCD_CLICKED` macro changes, but please be very careful modifying things like this.   It is used at the lowest levels of the system and is instantiated in different ways depending upon the hardware.

You can view the errors that Travis detected by going to:   https://travis-ci.org/MarlinFirmware/Marlin/builds/210562011

**Comment by benlye** [comment]
I wonder if this ought to be broken up into two (or more) pull requests?  One to add the ADC keypad support (which is where the bulk of the changes are) and the other to add support for the Anet board?

**Comment by oysteinkrog** [comment]
You are pulling in a lot of files here, including STL's etc.
You need to clean up the commits a lot, please only include the necessary changes :)

**Comment by fiveangle** [comment]
Some overlap with existing #5978 ?

**Comment by thijsk** [comment]
Can anyone tell me how to run the Travis CI-buils on my local machine? I'd like to add some builds for the ADC keypad and Anet board separately.

**Comment by Blue-Marlin** [comment]
You can't run Travis locally, but in your own github repository. Just activate it in the config of your repository.

**Comment by thijsk** [comment]
What else can I do to get this accepted? (Besides more testing of course)

**Comment by thinkyhead** [comment]
Sorry this hasn't been reviewed in a while. We're doing prep for the release, so patching old bugs and getting UBL into shape are the top priorities. I'll mark this for 1.1.1.

**Comment by thijsk** [comment]
In the meanwhile the creators of Skynet3d have also set up a github repository here: https://github.com/SkyNet3D/Marlin/tree/SkyNet3D-Devel (previously they only released .zip files through facebook, thats what I re-merged with marlin).

Maybe it's wise to get them to submit a pull request here.

**Comment by Bob-the-Kuhn** [comment]
Looks like they're shadowing Marlin.  This [branch](https://github.com/SkyNet3D/Marlin/tree/SkyNet3D-Oderwat) is based on Marlin 1.1.  That'll make the changes a lot easier to implement.

**Comment by Bob-the-Kuhn** [comment]
Take a look at PR #7016.  Let me know if this covers some or all of what this PR wants to do.

**Comment by thinkyhead** [comment]
I think we've captured the essence of this now…

**Pull request closed without merging**
