### PR TITLE
Fixed BLTouch HSMode broken after #26033

### PR DESCRIPTION
**Pull request by eoyilmaz**
### Description

Fixes BLTouch High Speed mode which is not working after #26033. The intention of ther PR was to be sure the BLTouch is deployed when the `MEASURE_BACKLASH_WHEN_PROBING` is enabled. But it broke the normal High Speed mode when `MEASURE_BACKLASH_WHEN_PROBING` is not enabled. This PR fixes that by also preserving the intended functionality in #26033 .

### Requirements

None

### Benefits

Fixes BLTouch High Speed mode which is broken after #26033 .

### Configurations

None

### Related Issues

#26246

### CODE REVIEW

**Comment by thinkyhead** [comment]
So is the comment "Does nothing if already deployed" wrong? What actually does happen if it's already deployed?

**Comment by eoyilmaz** [comment]
I shared a comparison video in #26246

**Comment by eoyilmaz** [comment]
Aah sorry, I added another change to my branch... that is completely irrelevant with this one.

It is about MMU initialization. In the current branch, after sending an `MMU2::rx_start()` it waits for 30 seconds for a response. But this 30 seconds is calculated from the printer start. And if the user sends a `MMU2::reset()` after this 30 seconds has passed, and if the MMU2s doesn't respond with an answer quickly enough they are immediately responded with a "MMU not responding - DISABLED" message as the 30 seconds has already passed.

My commit solved that by calculating the 30 seconds from the previous request.

**Comment by eoyilmaz** [comment]
Tbh, I can do it in another branch if you like to have a cleaner PR.

**Comment by eoyilmaz** [comment]
okay reverted that and created a new branch

**Comment by thinkyhead** [comment]
> I shared a comparison video in #26246

I see. So when we call `deploy` it doesn't "do nothing" after all. There is a check for an alarm state via `_deploy_query_alarm` and this adds a pause based on the larger of `BLTOUCH_DEPLOY_DELAY` and `BLTOUCH_DELAY`. I wonder if that alarm query is needed in the case of HS mode. It's meant to be a safety feature for deploy or stow, to catch instances where the deploy failed (i.e., the probe is reading "triggered").

So, what happens if you intentionally block the probe from deploying in HS mode, before and after the change in this PR?

**Comment by izzymoren0** [comment]
so, i have the same problem. it looks here like it was solved, but i still have this issue in a current build. have i something to change in the config?

**Comment by thisiskeithb** [comment]
> i still have this issue in a current build. have i something to change in the config?

@iZz0s: This PR is still pending and has not been merged into current `bugfix-2.1.x`.

**Comment by eoyilmaz** [comment]
> So, what happens if you intentionally block the probe from deploying in HS mode, before and after the change in this PR?

I'll try to look in to this, but I can say that after the fix applied if I block the probe before getting deployed, let say while homing the head keeps going down until it crashes to the bed.

**Comment by eoyilmaz** [comment]
That's interesting... I merged the upstream changes... But I think there is a bug with GitHub's code, as it shows 84 commits ahead and 75 commits behind and 155 files changed... where as in my local, when I compare with upstream bugfix-2.1.x branch I see only the `probe.cpp` has the changes that I'm trying to merge (plus @thinkyhead 's modification to my PR)... I'm ignoring this, but please let me know if I did something wrong...

**Comment by eoyilmaz** [comment]
> So, what happens if you intentionally block the probe from deploying in HS mode, before and after the change in this PR?

Okay finallly I had time to test this, sorry for responding so late. As you see in the comparison video, the behaviour is the same, if I block the probe with or without my changes it will stop homing:

https://github.com/MarlinFirmware/Marlin/assets/1786804/3a24f028-3230-420c-bf05-220c3f386d61

**Comment by eoyilmaz** [comment]
@thinkyhead do you need any other tests for this?

**Comment by thinkyhead** [comment]
> @thinkyhead do you need any other tests for this?

I'll go ahead and merge this and we'll see if it triggers any edge cases.

**Pull request merged**
