### PR TITLE
[1.1.x] More featureful CR-10 configurations

### PR DESCRIPTION
**Pull request by thinkyhead**
The 1284P has only 128K of flash, but this is enough to enable several useful features to improve the CR-10 experience. The 1284P also has a generous 16K of SRAM, so features that use SRAM can also be used more liberally. This PR enhances the CR-10 example configurations with the following features:

- Marlin splash and demo boot screens
- `LEVEL_BED_CORNERS`
- `PRINTJOB_TIMER_AUTOSTART`
- `QUICK_HOME` (!)
- `STATUS_MESSAGE_SCROLLING`
- `SDCARD_SORT_ALPHA` (100 x 28 reserves 2.73k SRAM) … (256 x 28 reserves 7k SRAM)
- `BABYSTEPPING` (Z only, with 10x multiplier and double-click option)
- Disabled `ARC_SUPPORT` — Rarely needed, non-standard in all slicers.
- `ADVANCED_PAUSE_FEATURE` + `PARK_HEAD_ON_PAUSE` + `HOME_BEFORE_FILAMENT_CHANGE`
- `NO_WORKSPACE_OFFSETS` — `G92` simply uses old behavior.

### CODE REVIEW

**Comment by fiveangle** [comment]
I noticed someone submitting a bunch of Anet example configs and they were all minimal functionality/usefulness.  Be on the lookout ;) 

If there's not much care put into the config, I question if that's better than the user just configuring themselves (and not have to keep the "_oh hey look, I set the board and enabled ULTRA_LCD !_" configs up to date in perpetuity :-D

**Comment by thinkyhead** [comment]
Hictop / Creality / etc. definitely went the minimal route with the CR-10. I got a copy of the firmware source code they are currently distributing, and it's an anonymous Marlin 1.0 version from early 2015 with a chirpy LCD click and no features enabled (not even `EEPROM_SETTINGS`).

The Melzi board on the lower-end machines has no bootloader on it, which makes it a hassle for the common user to flash a new firmware. However, at least one person is making hay out of the situation by selling pre-flashed Melzi boards with a more recent version of Marlin supporting their leveling probe accessory (EZABL) as part of the whole package.

I don't often get to do upgrades from "1.0" to the latest Marlin, and, wow, the difference in the LCD UI between versions is pretty striking. With so much attention on UI these days, I can see lots of places where stock Marlin still has room for improvement (such as adding "first time setup" procedures, making info screen layout configurable, etc.) — but what we have now is a major improvement over the look, feel, and organization of Marlin 1.0. The savvy contributors who helped optimize the graphical display code did some great work.

I know someone who has the ear of Creality, so maybe they will provide an upgrade path soon, or offer a flashable board trade-in. (Since they could make the traded-in boards flashable, then re-use them as good-as-new.) I flashed my client's CR-10 using an Arduino Mega, and was stuck for hours until I wired a 22µF cap to the Mega's reset pin. An Uno is recommended instead, and there are videos popping up on how to do this.

Anyway, breakfast time… and then I'll be trawling the Issue Queue.

**Comment by Deneteus** [comment]
I upgraded my CR-10 with 1.1.4 with EZABL using a regular USBASP 2.0 programmer that cost me $3. All it takes is moving one jumper for the power and the remembering to move it back after you flash or you will get a black screen.  
image

**Comment by fiveangle** [comment]
> With so much attention on UI these days, I can see lots of places where stock Marlin still has room for improvement (such as adding "first time setup" procedures, making info screen layout configurable, etc.)

Yes, I don't like badmouthing things built by volunteers who are doing the best they can, but the UX of Marlin pales in comparison to that of others: Prusa Research fork for example.  I started sketching out an improved menu tree that is laid out more from the standpoint of usability and reduced traverse rather than the current which lumps everything under 2 or 3 top level branches (very "Engineering" way to do it, but bad UX as everything you want to do us buried under at least one extra menu traverse for no reason, and you have to traverse all the way back up, then back down to do stuff that should be grouped together).  It would definitely fail the ol' PalmOS "tap checker" UX meter ;)

But agreed, the quality of the current implementation vs that of the old Marlin 1.0 is a mass improvement (!)  The functions themselves are great, but there's definitely room for improvement in execution path / logical grouping.

**Comment by fiveangle** [comment]
...also, I can understand the intent behind dropping the bootloader on these boards with limited PROGMEM, but not when they aren't even using it.  That sucks.  Hopefully Creality will turn this around.

I did some research a while back on small bootloaders for the AT90USB targets and found [source for a bootloader for AT90USB that fits in 512k](http://www.avrfreaks.net/projects/usbl-256-word-usb-bootloader?module=Freaks%20Academy&func=viewItem&item_id=2739&item_type=project) posted by a claimed friend of Paul (of Teensyduino) which is apparently an early implementation of the method Paul used in his Halfkay bootloader.  I haven't had the guts to try it on my Printrboard myself :-D

Burning a bootloader can be tricky since you have to set the bootloader region lock bits correctly, so I can see a lot of people messing that up if they aren't savvy.

**Comment by Deneteus** [comment]
If you look around there are some posts talking about boot-loaders being created in 260 bytes. I don't think space was really their concern. Leaving the boot-loader out basically lowered the bar on their scope of support.

http://www.avrfreaks.net/forum/smallest-bootloader?page=all

**Comment by fiveangle** [comment]
> If you look around there are some posts talking about boot-loaders being created in 260 bytes.

Not on native-USB targets =)

**Comment by thinkyhead** [comment]
>  can understand the intent behind dropping the bootloader on these boards with limited PROGMEM, but not when they aren't even using it. That sucks. Hopefully Creality will turn this around.

I understand it's a support hassle for them if people can flash their boards, and don't have a factory-tested version of Marlin onboard. Such actions should trip the warrantee. I feel that the lack of a bootloader is much less an issue if they would provide a more up-to-date and full-featured firmware. The more open path would be to provide a bootloader and a copy of the firmware source code, discourage the use of untested firmware, and then provide semi-frequent (monthly) updates to their firmware, essentially the latest Marlin 1.1 plus their configs/bootscreen.

I've also recommended to vendors generally that they always start from a tagged version of Marlin so that issues are known and changes are easier to track. I think that as more official version releases happen, vendors may start to trust Marlin more and take advantage of the ecosystem we have in place to foster innovation.

I agree with you about the UI having taken a long time to revamp. There were a lot of fundamentals to sort out in getting screen drawing to be efficient, to add static text, make it simpler to add menu items, and so on, and as with so much, cleanup of existing code and rethinking of the implementation had to be done before digging into a fancier UI.

At the moment, I'm ready to put in an option to hide X and Y on the character display and use a layout closer to Prusa MK2 firmware, though not identical. For example, the fan speed could be shown. Stacking the temperatures vertically makes sense. In the long run, the info screen should probably be made configurable. Just specify what to display, in what order, from a set of available things, and we'll have some simple logic "word wrap" the elements into the proper places.

The next thing on the agenda for the menu code is to —surprise!— split it up into 2-3 units. The LCD code needs to be cleaned up in-general and probably encapsulated one or more classes. Following that, we'll add standard interfaces for G-code handlers and other code that wants to temporarily take over the LCD, include the heater state on the screen, and so on. Along the way the UI will be made more independent from the rest of the code so that it can be more modular.

Anyway, all of this will come next month after the HAL is patched into working shape and I've patched the worst bugs in 1.1.x and brought those patches over to 2.0.x. So, you know, aiming to get a great new UI out just in time for Xmas….

**Pull request merged**
