### PR TITLE
[2.0.x] Option to force homing of a dependent axis

### PR DESCRIPTION
**Pull request by smoki3**
#9662

On some rare setups you can't home X without the Y axis (or _vice versa_) in the homed position. This PR adds options to perform homing of the other axis first when needed.

### CODE REVIEW

**Comment by tcm0116** [comment]
How is this different than just enabling or disabling `HOME_Y_BEFORE_X`?

**Comment by tcm0116** [comment]
Nevermind. I just read the PR. 

Perhaps these can be combined into a single feature than can be enabled to force the independent axis to be homed before the dependent axis. `HOME_Y_BEFORE_X` already defines the order, so maybe something like `XY_SAFE_HOMING`.

**Comment by smoki3** [comment]
I thats also an option. we can just rename FORCE_HOME_Y and FORCE_HOME_X to XY_SAFE_HOMING. Then it should work

**Comment by tcm0116** [comment]
Just add a good description in the configuration file as to what `XY_SAFE_HOMING` does. Don't forget to update all of the example/default configuration files. You should also make another PR that incorporates this change into bugfix-1.1.x.

**Comment by ghost** [comment]
My question was , if x already homed ,  your PR force to remake the x homing whatever the homing status of the x axis  ?

**Comment by smoki3** [comment]
yes

**Comment by thinkyhead** [comment]
Ok, so I've reduced this down to a single option (`CODEPENDENT_XY_HOMING`) since one is better than two. If you must home Y before it's possible to home X then you will also enable `HOME_Y_BEFORE_X`.

**Comment by smoki3** [comment]
@thinkyhead looks good :)

**Comment by thinkyhead** [comment]
I particularly like the new option name. It makes me laugh bitterly.

**Pull request merged**
