### PR TITLE
[1.1.x] Add JGAurora A5 support

### PR DESCRIPTION
**Pull request by thinkyhead**
Based on changes to 1.1.8 from http://samuelpinches.com.au/3d-printer/jgaurora-a5-firmware/

Corresponds to #9283

**_Bonus points if anyone knows the power failure detection pin._**

### CODE REVIEW

**Comment by pinchies** [comment]
We left those features enabled as some users prefer to use their own direct connection LCD rather than the MKS LCD which only talks over serial connection. 

There is no power failure pin - the power supply is a MeanWell 24V slim 350W PSU, and the MKS LCD module handles all the power failure operation. As a result, there is no power failure protection provided when printing off USB cable direct to the marlin board.

Please note there is a thermistor calibration table I put together for the hotend "thermistor 15", but the "thermistor 1" was measured to be perfectly accurate for the temperature obtained at the centre of the top of the bed.

I'd also like to say thanks for all your work on Marlin!! It's an amazing project, and I've appreciated it heaps. We're working on an A3S firmware as well, it only has some geometry changes, everything else is the same.

Our groups' work is over at https://github.com/GilardiLabs/Marlin/tree/JGAurora-A5 - there's also a branch there for the A3S I'll update in a few mins.

**Comment by thinkyhead** [comment]
Thanks for the feedback! I've added the README, as mentioned, and it includes basic instructions to enable the graphical display. Is there a page or video that shows how to install the display? If so, we can add a link in the README.

**Comment by pinchies** [comment]
No, I dont know that it is a popular modification - it was just left in because it was “free”.

**Comment by thinkyhead** [comment]
> "thermistor 1" was measured to be perfectly accurate

Maybe, for simplicity, we would just use "1" since it is probably a standard EPCOS 100k or equivalent, and we don't want to multiply our thermistors if there's no specific new identifier.

**Comment by pinchies** [comment]
It’s about 10-12C colder than reported at 200C+, which I think is too much to be acceptable for following suggested filament temperatures, and I couldn’t find a calibration in the list that was even close. I too would like to know which part number it actually is, but this is the best I could do. JGAurora doesn’t share anything.

I'd prefer it was kept personally, but it's your call.

**Pull request merged**
