### PR TITLE
New Advanced Settings menu for Ender3v2 with DWIN display

### PR DESCRIPTION
**Pull request by mriscoc**
### Description

This PR, implements a new submenu in the Control Menu: Advanced Settings

<details><summary>IMAGES</summary>

AdvancedSettings

IMG_20210403_201109_924
</details>

It is going to be more populated on the future, but now, has five items, submenu Home Offsets, submenu Probe Offsets (only visible when exist a leveling probe), Hotend PID, Bed PID and Powerlost recovery enabler.

### Requirements

Ender 3v2 with a DWIN display, but could be user with any Ender with a DWIN display

### Benefits

A new submenu, where to put special settings not available to the user in stock firmware.

### Configurations

[Configurations.zip](https://github.com/MarlinFirmware/Marlin/files/6253858/Configurations.zip)

### CODE REVIEW

**Comment by thinkyhead** [comment]
It looks like you may have an Ender 3 V2 DWIN display, and also some general C++ knowledge! Another PR that needs help and testing is #19371 which is nearly complete, but it's tricky to update these displays so it's not drawing correctly. When that PR is finished the complete Marlin menu system will be available, including mesh editing, confirm dialogs, etc., and it will initially support all Western languages, and soon other languages once we can install the needed fonts on the display.

**Comment by thinkyhead** [comment]
Before this PR will be complete, it should also add image assets to the `DWIN_SET` for the new menu items, both in English and in Chinese, and include the code needed to draw them. The files to be modified are [located here](https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20V2/DWIN_SET). I have the asset file I used to update the English JPEG around here someplace. I'll drop it in a followup message soon.

**Comment by mriscoc** [comment]
> Before this PR will be complete, it should also add image assets to the `DWIN_SET` for the new menu items, both in English and in Chinese, and include the code needed to draw them. The files to be modified are [located here](https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Creality/Ender-3%20V2/DWIN_SET). I have the asset file I used to update the English JPEG around here someplace. I'll drop it in a followup message soon.

Hi Thinkyhead, I did see your advance with the MarlinUI at #19371, but I was not be able to have any near to be funcional. About of DWIN_SET, I think that have the menu items on image assets limits the languages supported on the future and really, I don't know anything about Chinese, maybe only to use Google translate. Are you planning to use image assets for the text on MarlinUI?

**Comment by thinkyhead** [comment]
> I think that have the menu items on image assets limits the languages supported on the future

Indeed they do. They were created by Creality3D for its market, and since they are being maintained for the benefit of Creality they need to be properly extended to support the two languages that they are targeting: English and Chinese.

> Are you planning to use image assets for the text on `MarlinUI`?

Nope! Unfortunately text won't look as good because it's not anti-aliased, but a working `MarlinUI` will provide the entire Marlin menu system to the new display, and all Western languages. Supporting languages like Kana, Greek, and Chinese are still problems left to solve. … and the TODO list is endless … So I will continue to beg talented coders with E3V2s to join in my effort to extend the `MarlinUI` API to support more displays, instead of building a whole separate program on Creality's UI and Creality's assets.

**Comment by thinkyhead** [comment]
Here are the assets we are working with… The working copies are in basic PSD format.
[DWIN-work.tar.gz](https://github.com/MarlinFirmware/Marlin/files/6261842/DWIN-work.tar.gz)

**Comment by mriscoc** [comment]
> Here are the assets we are working with… The working copies are in basic PSD format.
> [DWIN-work.tar.gz](https://github.com/MarlinFirmware/Marlin/files/6261842/DWIN-work.tar.gz)

Thank you.

**Comment by mriscoc** [comment]
I added two more items: Home Offsets sub menu, and Power lost recovery enabler. Also I added a new UI element, DWIN check box.

**Comment by gokhanselen** [comment]
Ender3

**Comment by mriscoc** [comment]
@thinkyhead 
Warning, there is an error in the new definition of **HMI_HomeOffN**
Line 3470:  set_home_offset(**X_AXIS**, posScaled / 10);
The axis must be also a parameter.

```cpp
  void HMI_HomeOffN(const AxisEnum AXIS, float &posScaled, const_float_t lo, const_float_t hi) {
    ENCODER_DiffState encoder_diffState = Encoder_ReceiveAnalyze();
    if (encoder_diffState != ENCODER_DIFF_NO) {
      if (Apply_Encoder(encoder_diffState, posScaled)) {
        checkkey = HomeOff;
        EncoderRate.enabled = false;
        set_home_offset(AXIS, posScaled / 10);
        DWIN_Draw_Signed_Float(font8x16, Color_Bg_Black, 3, 1, 216, MBASE(select_item.now), posScaled);
        return;
      }
      LIMIT(posScaled, lo, hi);
      DWIN_Draw_Signed_Float(font8x16, Select_Color, 3, UNITFDIGITS, 216, MBASE(select_item.now), posScaled);
    }
  }

  void HMI_HomeOffX() { HMI_HomeOffN(X_AXIS, HMI_ValueStruct.Home_OffX_scaled, -500, 500); }
  void HMI_HomeOffY() { HMI_HomeOffN(Y_AXIS, HMI_ValueStruct.Home_OffY_scaled, -500, 500); }
  void HMI_HomeOffZ() { HMI_HomeOffN(Z_AXIS, HMI_ValueStruct.Home_OffZ_scaled,  -20,  20); }
```

**Comment by thinkyhead** [comment]
Thanks, it's now patched!

**Pull request merged**
