### PR TITLE
Fix some DWIN labels

### PR DESCRIPTION
**Pull request by mriscoc**
### Description

Some labels have display errors on the Control/Motion Menu of the DWIN Display

### CODE REVIEW

**Comment by otioss** [comment]
@mriscoc The current labels in control and motion menu look just fine to me.  What is this patch trying to fix? I see you have changed the coordinates of some labels. Please upload a before and after screenshot.

**Comment by thinkyhead** [comment]
Are you using the DWIN_SET from https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/Ender-3%20V2 ?

**Comment by mriscoc** [comment]
> Are you using the DWIN_SET from https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Creality/Ender-3%20V2 ?

No, I see, it is with the DWIN_SET provided by the firmware archive on Creality  site. 

1_English_

**Comment by mriscoc** [comment]
But, maybe is better idea to Enable the "USE_STRING_TITLES" define. Can be USE_STRING_TITLES enable by default? I have a fork when I enabled it for add some additional menus.

**Comment by thinkyhead** [comment]
The main reason to enable `USE_STRING_TITLES` is when using languages other than English and Chinese. There is probably plenty of space on boards using this display, but strings take up more space. Generally we turn off options that would increase the build size so the default is a smaller build. The fact that the default results in a bad appearance if users fail to also update the `DWIN_SET` is a good thing, because it prevents users from forgetting that the `DWIN_SET` also needs to be updated.

**Pull request closed without merging**
