### PR TITLE
Extruder behavior in DRYRUN mode

### PR DESCRIPTION
**Pull request by clefranc**
@MagoKimbra @Wackerbarth @thinkyhead
Can you take a look at this PR? It's just my version of what I think should be the DRYRUN behavior. With the extruders option `EXTRUDER_X_DRYRUN_ENABLE`, you can make a regular dry run "à la Repetier", or make it more compliant to a "real" test run. The code can be refined, or simply rewriten. I just wanted to know if it's worth an inclusion in Marlin.

### CODE REVIEW

**Comment by Wackerbarth** [comment]
Since you wrote this originally, we have incorporated some changes which affect your code.

Please rebase it on the latest Development.

I'm somewhat confused as to what you expect to accomplish with this "test run".
Please describe the use case in a bit more detail.

**Comment by clefranc** [comment]
@Wackerbarth Dry run was introduced on 1 June by @MagoKimbra with https://github.com/MarlinFirmware/Marlin/pull/2221. It was then discussed later if the extruder motor should move during a dry run.

One of the main argument is that you can check all printer functionalities (except heaters) with the original PR. Some argue that removing the filament is a little too much effort prior to launch a dry run test (me).

In both case this is legitimate claim. So this PR is just an attempt to join both needs.

On the other hand, looking at this PR, I've naively change 2 variable declarations from `long` to `float` to accommodate my low programming skills. I've no idea of the implication it can have on the prints. This is why I asked for the code to be reviewed and possibly rewritten (if admissible).

**Comment by Wackerbarth** [comment]
@clefranc -- I still fail to see the value in having the capability. What do you gain by having the ability to run the extruder motor with the heaters off.  I could have used the feature only once (when initially assembling the machine). Fundamentally, I see this "feature" as nothing more than "bloat".

"Dry run" goes through the mechanical movements without either the heaters or filament motion. I do see some value to having that feature.  But, with the "cold extrude" issues, etc., I still fail to see any value in having the additional mode.

**Comment by thinkyhead** [comment]
> I still fail to see any value in having the additional mode

It comes down to whether users would prefer to have the ability to trigger a "dry run" of any pre-existing GCode, or whether users will be forced to use some tool, such as a "dry run" checkbox in their slicer, a "dry run" checkbox in their host, or a text filter to convert GCode into the equivalent "dry run" GCode. The added value of having it as a convenient debug mode seems pretty clear. Of course, we could add a new configuration option (perhaps only in `Configuration_adv.h`) so that users can compile Marlin without support for dry run mode, reducing the build size by dozens of bytes and slightly increasing performance (since no dry-run flag would need to be checked for every move). I personally do like having this debug option, but I also think it would be nice to be able to build Marlin without it.

**Comment by thinkyhead** [comment]
@clefranc To make rebasing PRs faster, lately I've had the best luck using `git push -f` as the last step instead of using the Sync button in the Github app. It avoids all attempts by git to merge with your remote branch, when all you want to do is replace the existing branch with "my new commits on Development." The end result tends to be very clean.

**Comment by Wackerbarth** [comment]
> On Jul 22, 2015, at 3:26 PM, Scott Lahteine notifications@github.com wrote:
> I still fail to see any value in having the additional mode
> 
> It comes down to whether users would prefer to have the ability to trigger a "dry run" of any pre-existing GCode,
> 
> I disagree. The issue isn’t about having a “dry run”. We should, and do, have that capability.

You have 3 operatinal “dimensions” involved —
- heaters
- extruder motors
- filament present.

If all are true(active), then you are in normal operation.
“Dry run” deactivates the first two of these and doesn’t care about the third.

Now, the issue is about having this “test run” mode which would turn off only the first.
However, because of cold extrusion issues, the third would also have to be false.

What are you gaining by turning the extruder motors with no filament present?
Do you really need to be able to do this with the heaters off?

**Comment by thinkyhead** [comment]
> What are you gaining by turning the extruder motors with no filament present?

Nothing to be gained here, except to see that they (like the other axes) are turning when they should, which might be useful in a multi-extruder setup. But my sense of "dry run" is that it should not move the E motors, because that defeats the purpose, which is to have all movement except the E axis. As long as the internal current position of the E axis is updated, for testing purposes it doesn't matter if it actually moves, and for "dry run" purposes, I don't think it _should_ physically move.

> Do you really need to be able to do this with the heaters off?

Perhaps others can give examples where having heaters enabled is useful. But my sense of the "dry run" mode is that it should always have extruder motors deactivated at the very least, and it should almost certainly have heaters off so you don't clog up the nozzle and waste energy. And in dry-run mode, any filament sensor should be ignored. Its state may be updated, but it should not throw runout errors.

The thing is, if you want a "dry run" with heaters and extruders going, you can just pull out the filament and print as usual. Nothing will actually be printed, but everything on the machine will be operable. The only use for enabling "dry run" in that case would be to ignore the filament sensor.

Generally, I have seen the Dry Run as simply a way to **run any print job without producing an object**, and **without having to remove the filament**. Having the heater on is a waste of energy for that case, and having the extruder motors moving means you have to remove the filament, so they should not move in this mode.

**Comment by clefranc** [comment]
@Wackerbarth @thinkyhead Thank you for the explanations. I'm closing this as it is a statu quo. I'm sorry I used your time on this issue, there is more urgent and significant matters you're taking care of.

**Pull request closed without merging**
